### ISSUE TITLE
[FE] Implement Validate Page Mock Ups

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29469]
## User Story

As a Veteran, I should be able to input my details to gain access to my data. 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/25Znl2y)

## Description

Implement mock-up, with accessibility in mind

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Add content
- [ ]. Add text boxes
- [x] Capture input in state
- [x] Add focus to first H1
- [ ] Create unit tests
- [x] Create e2e tests
- [x] Update relevant documentations

## Acceptance Criteria

> when is the ticket done

- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging, but only behind a feature flip
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
