### ISSUE TITLE
[Kubernetes] Datadog agents - evaluate requests/limits

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29460]
## Description
The datadog agents deployed to our eks clusters are consistently being throttled.  Evaluate the requests/limits and adjust accordingly.

https://app.datadoghq.com/monitors/34165060?p=2

---
## Tasks
- [ ] adjust requests/limits on throttled datadog deployments
- [ ] redeploy to appropriate clusters

## Acceptance Criteria 
- [ ] datadog agents no longer being throttled

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/29812
