### ISSUE TITLE
[Kubernetes] Argo - reorganize deployment and images

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29465]
## Description
Both Argo workflows and argo notifications are pulling directly from docker hub which has presented issues with rate limiting.  We will need to get these images into ecr and pull from there.  While we are at it, we could probably benefit from moving all of the images to a single repo.

![image](https://user-images.githubusercontent.com/76792875/131376817-7d28dc4b-be1d-4553-a220-08e486860a23.png)

---
## Tasks
- [x] move all argo related images to a single ecr repo `argo`
- [x] destroy old argocd erc repos
- [x] create infra repos for notifications/workflows/rollouts with image build and manifest repo update
- [x] update the references here for default argo deployment -> https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml (not auto deployed because argocd doesnt automatically deply itself)

## Acceptance Criteria 
- [x] argo related images are contained inside a single ecr repo
- [x] image build processes via GHA for each infra repo
- [x] GHA to update manifests for notifications, workflows, and rollouts
- [x] GHA to update argocd images referenced in the infra repo

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
argo components updated (argocd/dex/redis), all pulling from the new ecr repo

![image](https://user-images.githubusercontent.com/76792875/131722579-fcb57214-bb2a-4d26-bba4-c1e0b5fe0cfd.png)
![image](https://user-images.githubusercontent.com/76792875/131722613-14c8dadd-b8b4-46f7-bab2-3c92039374d9.png)
![image](https://user-images.githubusercontent.com/76792875/131722676-f866b1ae-be9c-41af-a9d6-95945869b7a4.png)

**Comment by mleclerc00** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29603

**Comment by mleclerc00** [comment]
Argo notifications infra repo, gha for mirroring image, and gha for updating manifests complete.
https://github.com/department-of-veterans-affairs/vsp-infra-argo-notifications-controller
https://github.com/department-of-veterans-affairs/vsp-infra-argo-notifications-controller/actions

**Comment by mleclerc00** [comment]
Argo notifications infra repo, gha for mirroring image, and gha for updating manifests complete.
https://github.com/department-of-veterans-affairs/vsp-infra-argo-workflows-server
https://github.com/department-of-veterans-affairs/vsp-infra-argo-workflows-server/actions
![image](https://user-images.githubusercontent.com/76792875/133158964-4a2848b3-8af1-4a74-b9c2-164a1c9d4c47.png)
![image](https://user-images.githubusercontent.com/76792875/133159108-300343ff-09ec-476b-b518-e7889890173e.png)

**Comment by mleclerc00** [comment]
Argo rollouts infra repo, gha for mirroring image, and gha for updating manifests complete.
https://github.com/department-of-veterans-affairs/vsp-infra-argo-rollouts
https://github.com/department-of-veterans-affairs/vsp-infra-argo-rollouts/actions
![image](https://user-images.githubusercontent.com/76792875/133166035-a7be2f65-538e-4973-bed9-cee7407dbe68.png)
![image](https://user-images.githubusercontent.com/76792875/133166067-63466922-dc52-402b-b83c-f6c68d581372.png)

**Comment by jbritt1** [comment]
Great work on this @mleclerc00!
