### ISSUE TITLE
Remove IRIS text on VBA detail pages in Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29461]
## Issue Description
Currently, Facility Locator detail pages for Benefit locations contains text about the IRIS system. 
We need to remove that text in preparation for the upcoming deprecation of the IRIS system. 
Decisions about replacing that text with the new system will be a separate effort. 

Example: Detail page for [Washington D.C. National Capital Regional Office](https://www.va.gov/find-locations/facility/vba_372)

<details>
<summary> Screenshot of current display </summary>

![image](https://user-images.githubusercontent.com/55411834/131371956-605da348-a34f-4f79-9a12-e21289c22fb0.png)

</details>

---
## Tasks
- [x] Remove the following sentence (and link) which appears on detail pages for benefit facilities:  "For other benefit questions, use our online customer service tool called IRIS (Inquiry Routing & Information System)."
- [x] All other text should be maintained

## Acceptance Criteria
- [x] When facility type = Benefits, detail pages should contain the following text between the Directions link and Services heading: 

> To check on the status of your claim or appeal, use our online claim status tool.
> To get help with benefits, call 800-827-1000 toll-free. We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. If you have hearing loss, call TTY: 711

**Comment by mmiddaugh** [comment]
Looks good! Thank you
