### ISSUE TITLE
[FE] Update Ticket Templates

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29467]
## Description 

I need to iterate on the ticket template for the FE team located at https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/engineering/ticket-templates/front-end

## Tasks

- [ ] Add notes about QA
- [ ] Fix spelling errors
- [ ] Add steps for documentation
- [ ] Update document links
- [ ] Share with other teams. 
- [ ] Coordiate with PM for anything else missing

## Acceptances

- Ticket template is pushed to master and being used.
