### ISSUE TITLE
[FE] Integrate with API for validation feature

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29477]
## Description

Integrate with the vets API around the last 4 and name. This includes mocks and real integration. 
## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update sequence diagram to match  [this](https://dsva.slack.com/archives/G01BA04FVGF/p1631048267003500)
- [ ] Create local mock API calls based on agreed-upon structure for the auth endpoint 
- [ ] Call new auth API endpoint on `Landing` only if the new feature is enabled
- [ ] Call the new auth API endpoint with the last name and 4 on validate button click
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Create Pact tests
- [ ] Update relevant documentations

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
New diagram https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/phase-2/architecture/README.md
