### ISSUE TITLE
[FE] Update Redux storage schema

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29472]
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

- Update Redux storage to accommodate for low auth and for multiple appointments

## Tasks

- [x] Add fields for `facility`, `authorization` and `appointments`
- [x] Update HOCs to check of appropriate data
  - [ ] Required data
  - [ ] With low auth'd
- [x] Create units tests
- [x] Ensure backs capability

## Acceptance Criteria

- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Product team has signed off on the  feature
