### ISSUE TITLE
Audit QA efforts 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2948]
- [x] Check in with all VFS teams 
- [x] Create excel sheet to track check-ins and what we need to do next
- [x] create tickets for future work

**Comment by peterhill-oddball** [comment]
First pass at creating a basic spreadsheet to track check-ins with VFS teams -- https://docs.google.com/spreadsheets/d/1lXI6KwwI6yAFKop1xBe5kYikAbSxYs1ORz0Sry_lNw4/edit?usp=sharing
