### ISSUE TITLE
[Tech-Debt]  Updated Playbook of System and Facility Health services for St Louis/Jefferson Barracks and load into CMS [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#29488]
## Story
As a CMS editor, I need all system and facility health services loaded, so I can validate that the services have been loaded correctly for the Veteran

## Goal
Update all sites/facilities with correct health care services

## Task
Update System and Facility health service in playbook and CMS system for the following:
- [x] Jefferson Barracks (St Louis health care)
- [x] Greater LA 

## Acceptance Criteria
- [x] Playbooks have been updated with health service information for the new locations (if applicable)
- [x] CMS System/facility have been updated with missing health services.

**Comment by bcastoe** [comment]
#29488 - Updated Playbook of System and Facility Health services for St Louis/Jefferson Barracks and load into CMS - Completed and moved to validate.  Greater LA has been completed; there was one health services missing from the Sepulveda VA Medical Center.  Jefferson Barracks/St Louis worked with Lisa to complete and on 09012021 on team standup that she completed.
