### ISSUE TITLE
Restore delayed VAMC system names to robot.txt file 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29499]
## Story
Due to hurricane impact and staff changes, the go-live date for several VAMC systems has been pushed back. As a result, we need to roll back some of the changes we made to the robot.txt file (#29395 and #29153) 

## Goal
Restore disallow so crawlers and browsers do not have access to VAMCs with delayed roll-outs 

## Task
Restore the following system names to robot.txt file 
- [ ] Central Iowa health care
- [ ] Hampton health care
- [ ] Fayetteville-Arkansas health care
- [ ] Alexandria health care
- [ ] Gulf coast Iowa health care
- [ ] Southeast Louisiana health care

## Acceptance Criteria
All System names are once again included in robot.txt file
