### ISSUE TITLE
Transition TUD to Testing Tools Team

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#29501]
## Issue Description
This ticket covers everything the Identity Team needs to cover as part of transitioning ownership of the Test User Dashboard to the Testing Tools Team
---
## Tasks
- [x] Brief relevant Testing team members on how to navigate TUD as a user
- [x] Give a technical overview of the TUD frontend architecture
- [x] Give a technical overview of the TUD backend architecture
- [x] Share relevant design documents, documentation, and research with the Testing team 
- [x] Ensure the `VSP-testing-team` and its relevant members have administrative access to the TUD frontend repository
- [x] Add the `VSP-testing-team` as codeowners to TUD files in `vets-api`
- [x] All active TUD tickets are assigned to the Testing team
- [x] All post-MVP TUD tickets are assigned to the Testing team
- [ ] The [TUD MVP Epic](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/13714) is completed and closed out.
- [x] The [TUD post-MVP Epic](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/23078) is updated with relevant information.

## Acceptance Criteria
- [ ] The Testing team will be actively maintaining and developing the TUD app
- [ ] The Identity team will not be directly included in any TUD issue

**Comment by nsoutouras** [comment]
Will wrap up at end of 61
