### ISSUE TITLE
Discovery: VAMC/Vet Center phone number filter

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29502]
## Issue Description
We have used the phone number filter to make the front end display of phone numbers more defensive. This issue is to discover where the filter is currently in place and where else it might be used across the VAMC and Vet Center products

---
## Tasks
For VAMC and Vet Center pages
- [ ] Identify and document which templates currently use the phone number filter and which formats it is currently covering
- [ ] Identify and document other templates could use this filter (what other pages/accordions) might contain phone numbers 

## Acceptance Criteria
- [ ] Recommendations for other applications of the phone number filter on VAMC and Vet Center pages
