### ISSUE TITLE
Expose Endpoint for generic RPC

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#29505]
This is a stopgap measure for fleshing out functionality for RPC creation to test without security issues. 

- [x] Expose Endpoint
- [x] Test against Shane's running test version
- [ ] Get connection details for Bay Pines test site
- [ ] Configure staging site to connect to Bay Pines
- [ ] Test

**Task is Done When:**
When we can hit bay pines testing site from the staging server

**Comment by kjduensing** [comment]
Bay Pines bringing VistA System back to on-prem: finished 9/13

**Comment by kjduensing** [comment]
need vista link account
