### ISSUE TITLE
Notice of Disagreement Decision Date error

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29517]
## Issue Description
When entering issues by hand, the decision date entry screen displays an error if the year is not 2020 or 2021. Recommend we include language about why nothing earlier than 2020 can be accepted.

---
## Tasks
- [ ] Update language to explain error

## Acceptance Criteria
- [ ] Updated language
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
This has been fixed by adding more context to the page. In the instruction text above the form field, we have added "You can request a Board Appeal up to 1 year from the date on your decision notice" clarifying the expectations on the date entered. The changes can be viewed here:

https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/v/xyRA5J/a/jgMAyob/r/xyRAxl

**Comment by kevinstachura** [comment]
Tagging @Mottie for awareness as this will likely be an FE ticket soon.
