### ISSUE TITLE
Perform Load Testing on Rated Disabilities

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2951]
## User Story
As a frontend engineer, I want to be able to test this page to ensure it will not go down under heavy traffic.

## Considerations
- Docs for load testing [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/auth-session-loadtest.md)
- VSP QA: Peter Hill (peter.hill@oddball.io)
- VSA QA (for manual, front-end UI testing on Staging): Tze-chiu Lei (tze@adhocteam.us)
- Rated Disabilities needs to have all its endpoint components in place to fully load test given the network requirements
- Access to internals tools is required to perform load testing.

## Tasks
- [x] Perform load tests on Rated Disabilities after all the above considerations have been addressed. 
- [ ] Notify Mike Walker of increased traffic

## Acceptance Criteria
- [x] Rated Disabilities has successfully passed all load tests run against it.

**Comment by tlei123** [comment]
@micahchiang , please add to this ticket:

1. link to Locust test-file in devops repo; and
1. copy of test-results.

I saw your [comment in \#3099](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3099#issuecomment-559871464) saying testing has been completed.

Thanks much!

**Comment by micahchiang** [comment]
@tlei123 - you can checkout the test file [here](https://github.com/department-of-veterans-affairs/devops/blob/2951-rd-load-tests/loadtest/rated_disabilities/rated_disabilities_locust.py). I still need to add a README with a summary of why we tested, and then submit a PR. 

I have a bunch of .csv files from the test, which I can send you if you want, but here are some screenshots of the results. I'll admit, I don't know how to really interpret these 😬 maybe you can help me understand them better. 

![Screen Shot 2019-11-27 at 11 12 35 AM](https://user-images.githubusercontent.com/15097156/69978052-b0d1f100-14e0-11ea-8406-0939c21f1dbd.png)

<img width="1673" alt="Screen Shot 2019-11-27 at 11 11 50 AM" src="https://user-images.githubusercontent.com/15097156/69978093-c0513a00-14e0-11ea-834a-842ad6a48316.png">

![Screen Shot 2019-11-27 at 11 12 27 AM](https://user-images.githubusercontent.com/15097156/69978180-e4ad1680-14e0-11ea-9af9-ba9edf44a2b2.png)

It seems a lot of the errors were a result of using up all available staging connections. I wasn't sure how long the tests should run for...so I let them run for a while 😬 .

**Comment by tlei123** [comment]
@peterhill-oddball, do you know who on the Platform side knows enough about load-testing to explain how to interpret the results in @micahchiang’s comment above?

Beyond just understanding the numeric columns in the Statistics (top) screenshot, I need to determine whether the quick ramp-up of errors is a real concern (QA fail?) in the Total Requests per Second chart (bottom screenshot, top graph, around 9:58:40 AM).

The [load-testing docs in devops](https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest) repo only outline how to run the tests, not how to interpret the results.

Please let us know.  Thanks much!  :)

P.S.  @micahchiang, I am hoping the error-ramp-up is staging running out of connections as you mentioned, and running out of connections is not a real problem for us.  :::fingers crossed:::

**Comment by peterhill-oddball** [comment]
> @peterhill-oddball, do you know who on the Platform side knows enough about load-testing to explain how to interpret the results in @micahchiang’s comment above?

I can try to help you interpret the results, but we may need to consult some others for their thoughts as well.

> Beyond just understanding the numeric columns in the Statistics (top) screenshot, I need to determine whether the quick ramp-up of errors is a real concern (QA fail?) in the Total Requests per Second chart (bottom screenshot, top graph, around 9:58:40 AM).
> 

Similar to Micah, I've also run into running out of available connections on staging if I let the test run for long enough.  It's not necessarily a fail.

> The [load-testing docs in devops](https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest) repo only outline how to run the tests, not how to interpret the results.
> 

That's true.  I think guidelines for pass/fail status are still being cooked up.  Generally, it's good to look for 95 percentile response times < 2 seconds or so.  As well, a failed response without a cause explained by the staging environment's shortcomings is something that needs to be fixed.

> Please let us know. Thanks much! :)
> 
> P.S. @micahchiang, I am hoping the error-ramp-up is staging running out of connections as you mentioned, and running out of connections is not a real problem for us. :::fingers crossed:::

I am having trouble getting the test to run.  In particular, it seems to be choking on importing the "between" package.  Am I missing something?  Did either of you run into this issue?

`[2019-12-02 14:15:00,667] THEFLOOD/ERROR/stderr: from locust import between, HttpLocust, TaskSet, task
[2019-12-02 14:15:00,668] THEFLOOD/ERROR/stderr: ImportError  
[2019-12-02 14:15:00,670] THEFLOOD/ERROR/stderr: cannot import name between`

**Comment by micahchiang** [comment]
@peterhill-oddball - Not sure if yours is the same issue, but I had to specify the path to locust in my IDE settings: 

```  
"python.autoComplete.extraPaths": [
    "~/usr/local/lib/python2.7/site-packages/locust"
  ],
```

**Comment by peterhill-oddball** [comment]
Ok, I finally have the test working on my box.  Anyway, with 100 users I am getting a RPS of ~61.  I'm also seeing some failures.  Unfortunately, there aren't any detailed error logs available.  I'm seeing two different failures --
`HTTPError(u'503 Server Error: Service Unavailable for url: https://staging-api.va.gov/v0/disability_compensation_form/rated_disabilities',)`  
and  
`HTTPError(u'500 Server Error: Internal Server Error for url: https://staging-api.va.gov/v0/disability_compensation_form/rating_info',)`

Perhaps we need to get a hold of staging's server logs to see what kind of 500 error that was.  Also, the 503 can't necessarily be dismissed without some more analysis about what caused the service to be unavailable.  Is it just a resource issue with staging?  Or, is it something innate to the code that you've written?

**Comment by micahchiang** [comment]
I agree, I think the acquiring the server logs for staging might be a good next step. My thought is that it's a resource issue with staging, but only because our PM has been manually QA-ing different staging accounts and data has been coming back fine. Do you know how we can go about getting the server logs for staging?

**Comment by peterhill-oddball** [comment]
I don't know how to get at those staging server logs off the top of my head, but I'm digging into it now.

**Comment by micahchiang** [comment]
@peterhill-oddball, @tlei123 - I spoke with Silvio and we were able to take a look at the vets-api server logs for staging to help analyze the results of the load test. In summary, it seems the 500 and 503 errors are an issue with EVSS running out of available connections. Longer post incoming below.

**Comment by peterhill-oddball** [comment]
Excellent, I tried Sentry and Grafana for more details, but I made no progress.  I asked JP a few questions as well, but we weren't quite sure how to get a hold of the staging logs.  Any change you can write down the steps you took to retrieve those logs for future reference?

**Comment by micahchiang** [comment]
Here is a screenshot of the test I just ran:
![Screen Shot 2019-12-03 at 12 39 27 PM](https://user-images.githubusercontent.com/15097156/70087910-0635fd00-15ca-11ea-8bea-b7159163e00a.png)

Here is a screenshot of the corresponding failures in that test:
![Screen Shot 2019-12-03 at 12 39 33 PM](https://user-images.githubusercontent.com/15097156/70087937-177f0980-15ca-11ea-9ded-7ad1c88de70f.png)

Here is a piece of the stack trace we looked at in tandem with the load test. It's part of a larger log object that also contained an error message about unavailable external services. It matches up with one of the 503 errors from the test:
```
/srv/vets-api/src/lib/evss/disability_compensation_form/service.rb:71:in `handle_error'\n/srv/vets-
api/src/lib/evss/service.rb:42:in `rescue in with_monitoring_and_error_handling'\n/srv/vets-
api/src/lib/evss/service.rb:37:in `with_monitoring_and_error_handling'\n/srv/vets-
api/src/lib/evss/disability_compensation_form/service.rb:34:in `get_rated_disabilities'\n/srv/vets-
api/src/app/controllers/v0/disability_compensation_forms_controller.rb:9:
```
What we found was that too many attempts to query EVSS would result in vets-api handling an error received back from the external service. This is what the above stack trace represents. As far as I understand it, `with_monitoring_and_error_handling` handles errors from EVSS.

Here are the steps for retrieving logs:
- prerequisites: AWS access with permissions to view log groups in CloudWatch. 
1. Log into the AWS console.
2. Open up CloudWatch.
3. Select Log Groups.
4. Search for `dsva-vagov-staging/srv/vets-api/src/log/vets-api` to bring up log groups for staging.

@peterhill-oddball - As far as documenting the steps for retrieving logs, do you know of a more permanent place for the above steps to live? Happy to record them elsewhere as well.

**Comment by peterhill-oddball** [comment]
I think this will be most relevant to load testing.  Perhaps we could create an article for how to retrieve error logs within the devops/loadtesting space.  I would like to try reproducing your steps, but I don't have AWS access.  Once I am able to do that, I volunteer to write up those 4 quick little steps maybe with some screen shots.  Thanks for writing that down!

**Comment by micahchiang** [comment]
PR here https://github.com/department-of-veterans-affairs/devops/pull/6025
