### ISSUE TITLE
Content - Directing users to 686 form on BDD submission page

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#29513]
## Issue Description
Per our SME (Kevin Hillegas from VBA), we should have some verbiage directing users to the logical next step (if applicable) on the BDD submission page. We were given this language from Kevin H. for use:

>If you have a spouse or child/children, you may be entitled to additional compensation for these dependents.  The additional payment amount depends on your disability rating and the number of dependents.  To claim family members, complete the following (direct to Dependency Wizard) or ensure that you fill out and submit a signed VA Form 21-686c, Application Request to Add and/or Remove Dependents.  If claiming a child in school between the ages of 18 and 23; also submit a completed VA Form 21-674, Request for Approval of School Attendance.  
 
>If claiming benefits for a seriously disabled (helpless) child, also submit all relevant treatment records for your child's disabilities.  You may also in certain circumstances receive an allowance for dependent parents by completing and submitting a signed VA Form 21P-509, Statement of Dependency of Parent(s).

I took this content and fit it into this design, under a section titled "what should I do next?":

![Screen Shot 2021-08-31 at 2.19.35 PM.png](https://images.zenhubusercontent.com/5d65638e0845ad5f24bada4a/dda4ea01-5ad5-42f4-a6a5-abbda394b324)

We would like for our content experts to refine the content to fit proper voice, tone and style.
---
## Tasks
- [ ] Work with Beth to create better language for the requirement to send users to the 686 form
- [ ] Add updated language into BDD design

## Acceptance Criteria
- [ ] Language has been created and updated in design
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@kevinstachura I will try to get to this on Friday of this week, but may have to get back to you early next week. Will that timing work?

**Comment by bethpottsVADEPO** [comment]
@kevinstachura Did Form 686c go to 100% yet? I think we should wait on this until it does so we can send users to our VA.gov app. Or just point to the PDF for now (in which case we'd have to rework the text a bit). Doesn't look like we have the 21-674 on our site yet either, so I wrote it as if we only have the PDF to offer. Let me know if this ends up being too long--I included all the info from the stakeholder. I noticed that you had cut some of it. Not sure which of it is really essential to have in this location. But here it is in our VA.gov voice and in plain language:

**What should I do next?**

**If you have a spouse or child,** you may be entitled to additional compensation. [Apply online to add a dependent]

Or you can fill out and submit an Application Request to Add and/or Remove Dependents (VA Form 21-686c).

Download VA Form 21-686c (PDF)

**Note:** If you’re claiming benefits for a seriously disabled (helpless) child, you must submit all relevant treatment records for your child's disabilities. 

If you’re claiming a child between the ages of 18 and 23 who is in school, you’ll need to fill out and submit a Request for Approval of School Attendance (VA Form 21-674) so we can verify their attendance. 

Download VA Form 21-674 (PDF)

 **If you have dependent parents,** you may be entitled to additional compensation. Fill out and submit a Statement of Dependency of Parent(s) (VA Form 21P-509).

Download VA Form 21P-509 (PDF)

**Comment by kevinstachura** [comment]
Hey @bethpottsVADEPO ! Picking this effort back up for this sprint..so yes, 686 is now on va.gov at 100%. I asked Jim Adams about this on Friday. He let me know that the only lingering thing is that some links on content pages around 686 may still be pointing to EBN. Other than that though, it seems like everything is set.

I think we should be good to direct users to the online form at this point! But we can chat about it further. Most of this content should stay the same, right?

**Comment by kevinstachura** [comment]
@bethpottsVADEPO this is what the design looks like after changes:

<img width="698" alt="Screen Shot 2021-09-28 at 10 46 33 AM" src="https://user-images.githubusercontent.com/54544300/135110621-c088e3c7-1e24-42ec-8d75-45423675cb8e.png">

I'm guessing this is all set, but let me know if you have any other changes!

**Comment by bethpottsVADEPO** [comment]
@kevinstachura I found parallel content already written/live [on this page](https://www.va.gov/view-change-dependents/add-remove-form-686c), and I'd like to mirror some of the wording from there. Would you mind making a couple tweaks? Then I think we're good to go. Is the next step showing this to the stakeholder who made the request?:

1/ **Note:** If you’re claiming your child who became permanently disabled before they turned 18, you’ll need to submit all private medical records relating to the child’s disabilities with your application.

2/ **If you're claiming a child who's between 18 and 23 years old and attending school full time,** you'll need to fill out and submit a Request for Approval of School Attendance (VA Form 21-674) so we can verify their attendance.

And then just make sure all the links are going to the right place. (I know this is obvious, but checking this does sometimes slip through the cracks, so I wanted to reinforce since I can't do that on my end.)

**Comment by kevinstachura** [comment]
No problem! Here's the updated screenshot:

<img width="644" alt="Screen Shot 2021-09-29 at 10 06 56 AM" src="https://user-images.githubusercontent.com/54544300/135284931-c49cdae1-72f2-4734-bd6c-3f711fd6a885.png">

We will definitely make sure that the PDF links (and the link to the online 686 form) is correct 👍 We actually did not have plans to run this by the stakeholder again (before implementation), but if you would like an accuracy check, then we certainly could! My feeling is that it's probably fine if you found that parallel content and decided to mirror it, but it never hurts to double check 🤷‍♂️

**Comment by bethpottsVADEPO** [comment]
@kevinstachura I think it would be good to send them the above screen shot even if just as an FYI as opposed to necessarily asking for approval. That way, if the SME notices any inaccuracies, they'll let us know. But from my perspective, this content is ready.

**Comment by kevinstachura** [comment]
Sounds like a plan - thanks Beth! I will let you know if they recommend any edits 👍

**Comment by kevinstachura** [comment]
After reaching out to our stakeholder (Kevin H.) and sending him the revised content, he only had one request:

> Is it too late to modify “private medical records” to read “military/private medical records” in connection with the seriously disabled (helpless) child question?

Beth and I chatted and were able to include this change in a plain language format:

>Note: If you’re claiming your child who became permanently disabled before they turned 18, you’ll need to submit all military and private medical records relating to the child’s disabilities with your application.

And updated the design to reflect it:
<img width="740" alt="Screen Shot 2021-10-01 at 1 53 58 PM" src="https://user-images.githubusercontent.com/54544300/135667154-4f7e5d7c-e04c-411e-b5bb-cc622d1612a9.png">

So the content aspect of this ticket is done! I will link this ticket in @ashagross 's implementation ticket and we can take it from there.
