### ISSUE TITLE
[Kubernetes] Intermittent DNS failures with RDS database for Sentry

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#29511]
## Description
Sentry is having some intermittent failures with DNS resolution for the postgres database in RDS. 
After some research:
- https://stackoverflow.com/questions/55584935/kubernetes-dns-intermittently-failing-with-kube-dns-service-and-coredns-pods-see
- https://github.com/kubernetes/kubernetes/issues/56903
- https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

It appears that we might want to set up NodeLocalDNS so that we can try to eliminate any time-outs that might be occurring.

---
## Tasks
- [ ] Investigate the best path forward to eliminate the issue we are seeing with DNS
- [ ] Try the chosen method and determine if it resolves the issue

## Acceptance Criteria 
- [ ] Sentry no longer has errors about temporary failures in name resolution

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
