### ISSUE TITLE
Notice of Disagreement - resolve multiple entry issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29519]
## Issue Description
When entering issues by hand, the system accepts multiple entries of the exact same issues with the same decision date.

---
## Tasks
- [x] Prevent adding duplicate issues
- [x] On the “Issues for review” screen that pops up asking what the disagreement is about, recommend adding the decision date along with the issue name (because of # 4 above).

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
