### ISSUE TITLE
Notice of Disagreement Mailing Address Check box

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29516]
## Issue Description
Notice of Disagreement content change

---
## Tasks
- [x] On change mailing address screen, there is a check box that says “I live on a US military base outside the US.” I presume that’s for APO/FPO addresses, but use of that address does not require that someone live on a base. Recommend changing to “I have an APO/FPO address” or something similar.

## Acceptance Criteria
- [x] Suggestion has been pointed to the global design system team for consideration
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
I have made mention of this global item for the design team to potentially review:

https://dsva.slack.com/archives/C0NGDDXME/p1631541208068800

**Comment by kevinstachura** [comment]
Based on comments from the above Slack link, it seems that content is taking a look at this. Closing as complete.
