### ISSUE TITLE
[Quality Assurance Audit] Post Production Audit of VAMC Shreveport, for links, standards, and design standards.[BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#29539]
## User Story
As a VHA Digital Media web manager, the system websites need to be audited for standardization and mistakes, so websites can be updated an corrected to meet design standards.

## Goal
Remove deviations from standards. 

## Resources - Tools - Documentation
[Audit checklist](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FChecklists%5Fand%5Ftools)

## Tasks
Using the audit check list, review all areas of Fully published websites (Pass or Fail) web pages and profide notes:
- [x] Review all pages using checklist.
**PART TWO**
- [x] Review all pages for content and plain language standards
**Focus on new pages, or pages that were changed/created**

## Acceptance Criteria
- [x] Rename the file as [system name] audit final [date] and save in:
[QA_Documents folder](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FQA%5FDocuments)
- [ ] Content has compelted review of new/changed pages
- [ ] Document with corrections/proposed changes is saved in QA Documents folder

**Comment by bcastoe** [comment]
#29539 - Post Production Audit of VAMC Shreveport, for links, standards, and design standards. - has been completed and moved to validate. * 1st pass of qa has been documented; excel spreadsheet and tabs for findings.
