### ISSUE TITLE
Create guidance for Platform teams on VIDEOS/IMAGES best practices

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29534]
# User story

As a Platform team member, I need to know how to structure VIDEOS that go on the Platform website, so that I can convey informaiton as smoothly as possible to customers.

# Tasks

- [x] Determine what has to go into the guidance
- [x] Create guidance around VIDEOS hosted in Platform website
- [ ] Inform teams that guidance around VIDEOS is available

Acceptance criteria
- To come.

# Reference info
- To come

**Comment by lianilychee** [comment]
Weds 9/8:
- Amy currently reviewing w/ G!
- Aiming to wrap up before the end of the week (hopefully today, if not mid tmr)

**Comment by lianilychee** [comment]
9/9 Thurs:
- I feel better abt finishing it today!
- will show at SU tomorrow

**Comment by lianilychee** [comment]
9/14 Tues:
- ready to share
- need to double check that our current accessibility recs match the resource that Amy found

**Comment by lianilychee** [comment]
9/15 Weds:
- been published!
- ready for demo :D
