### ISSUE TITLE
Create guidance for PDFs and slide deck best practices

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29533]
### User Story
As a Platform team member,
I need to know how to structure slide decks that go on the Platform website,
so that I can convey information as smoothly as possible to customers.

As a Platform team member,
I need to understand how to guide other Platform team members to link to PDFs or slide decks on the Platform website,
so that I can document this in the existing Platform website style guide.

### Tasks

- [ ] Determine what has to go into the media types guidance
- [ ] Update "Media, Images, etc" section of style guide 
- [ ] Inform teams that guidance is available

## Acceptance Criteria

- [ ] Style guide has been updated.

**Comment by lianilychee** [comment]
9/9 Thurs:
- haven't pulled into "to-do", but will probs have the prep work done by EOS
  - Prep work = prelim research, draft outline with info to deliver

**Comment by CherylEvans** [comment]
@jknipes Wow, this is old. Should I contact @lianilychee to see if it's still relevant or go through the User Story and tasks to determine relevancy?

**Comment by jknipes** [comment]
@CherylEvans yes, please reach out to determine relevancy. You can mention we can no longer link to Google Drive docs, sheets, slides, etc. and this may help determine whether the issue is still relevant.

**Comment by CherylEvans** [comment]
@jknipes According to her [LinkedIn profile](https://www.linkedin.com/in/lianilye/details/experience/), Liani Lye left Ad Hoc and VA.gov in July 2023. The issue now seems irrelevant since we can no longer link to Google Drive docs, sheets, slides, etc.. What do you suggest?

**Comment by jknipes** [comment]
Per comments above, closing ticket, no longer relevant
