### ISSUE TITLE
Prep to iterate on V3 of IA

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29530]
# User story

As a Platform customer, I need to know where to find developer info on the Platform website, so that I have the info I need in order to create my veteran-facing service.

As a Content team member, I need to solicit feedback from Platform customers, so that I can begin to craft the Platform website IA (aa where to find info on the Platform website).

# Tasks

- [ ] Codify research goals
- [ ] Prepare research test
- [ ] Socialize that the research test is coming

Acceptance criteria
- To come

# Reference info
- To come
