### ISSUE TITLE
Launch MVP of list to tools

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29535]
# User story

As a Platform customer, I need to know what VA.gov tools to access, so that I can build my veteran facing service.

# Tasks

- [ ] Wrapping up audit 
- [ ] Writing descriptions
- [ ] Validating list with other folks
- [ ] Publishing list on Platform website

Acceptance criteria
- The list has been published on Platform website

# Reference info
- "List" - still an introduction, but not a comprehensive guide

**Comment by lianilychee** [comment]
9/8 Weds:
- My spreadsheet is 95% ready to share w/ other ppl to get feedback!
- End of today: Content is in Conf page ready to share w/ other ppl
  - Other ppl tbd
  - Async feedback: seeking validation on tools that are missing/extraneous, inaccurate info, etc
    - But it is okay if we don't get this validation, since our customers can inform us anyway

**Comment by lianilychee** [comment]
9/9 Thurs:
- My [Conf page](https://vfs.atlassian.net/wiki/spaces/~369451595/pages/1872855066/Platform+Tools) is ready for review!  
- Just thinking what I who to ask to review, as well as what to ask ppl to review _for_

**Comment by lianilychee** [comment]
9/10 Fri:
- Finished
  - I wrapped up the list to "good enough"
  - I drafted a message to share in the platform team channel; wanna have Liani, Amy, maybe Rachael look at it

**Comment by lianilychee** [comment]
9/13 Mon:
- 
- Liani to look at

**Comment by lianilychee** [comment]
9/15 Weds:
- After user tasks, Gretchen will round up feedback
