### ISSUE TITLE
Create guidance for Platform teams on PDFs best practices

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29532]
# User story

As a Platform team member, I need to know how to structure decks that go on the Platform website, so that I can convey informaiton as smoothly as possible to customers.

# Tasks

- [ ] OPTIONAL - Inform Platform teams that change is coming
- [ ] Determine what has to go into the guidance
- [ ] Create guidance around PDFs hosted in Platform website
- [ ] Draft and send comms to Inform teams that guidance is available

Acceptance criteria
- To come.

# Reference info
- To come

**Comment by lianilychee** [comment]
combining with decks guidaec https://github.com/department-of-veterans-affairs/va.gov-team/issues/29533
