### ISSUE TITLE
[BACKEND] Implement new endpoint for uniqueness and pagination of community care results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29545]
## Issue Description
We can now use the new PPMS endpoint for uniqueness and to restore pagination of community care results

---
## Tasks
Change endpoint for community care searches, including
- [ ] community care providers
- [ ] community urgent care
- [ ] community emergency care 
- [ ] community pharmacies
Identify pagination parameters for front end

## Acceptance Criteria
- [ ] Community care searches (including providers, urgent care, emergency care and pharmacies) will use new endpoint for uniqueness
- [ ] Front end can restore pagination to these searches
