### ISSUE TITLE
[FRONT END] Re-enable pagination for community care searches (1b)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29546]
## Issue Description
Following the backend implementation of the new endpoint for uniqueness and pagination of community care results (#29545), we can restore pagination to  community care results. Due to data issues, the Facility Locator has been hard coded not to use pagination when returning community care search results. 

Feature flag on backend to enable new facility service locator endpoint

Out of scope:  
- Pagination for VA facility searches is buggy and will be addressed in #29942
- Community urgent care and urgent care mashup searches because pagination changes by PPMS were not applied to the Place of Service Locator
     
---
## Tasks
- [x] Remove hard coding to suppress pagination
- [ ] Page and per page will be available for pagination of following searches
       - [ ] community care providers
       - [ ] community emergency care
       - [ ] emergency care mashup
       - [ ] community pharmacies
- [x] Add toggle to experiment with pagination 

## Acceptance Criteria
- [ ] Veterans can see search results expressed 10 per page (as appropriate) for the following searches
      - community care providers
      - community emergency care
      - emergency care mashup
      - community pharmacies
- [ ] Pagination can be toggled

**Comment by gescobardev** [comment]
@mmiddaugh I just want to confirm - are we not restoring pagination for urgent care?

**Comment by mmiddaugh** [comment]
@Gaida fyi - we get urgent care data from the Place of Service (POS) locator - it's a different endpoint than the other community care queries (which come from the Provider Locator). The pagination parameters and provider dedup logic, were only applied to the Provider locator. We've requested they be added to the POS endpoint but haven't yet heard that they are available. So, in the meanwhile, we'll return pagination for everything except urgent care.

**Comment by gescobardev** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/19308 Restores pagination for community care providers, emergency care(see exclusions below), and pharmacies.
**Does NOT restore pagination for PPMS urgent care, urgent care mashup or emergency care mashup.**

See [slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1636128085267500) for more info on about pagination for mashups.
