### ISSUE TITLE
Audit for VAMC communication options

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29548]
## Problems to be solved
There are a growing number of ways for Veterans to connect with clinicians for health related needs. It may be confusing for Veterans to find the right one for their needs and/or differentiate between the tools.

New options for contacting the VA are becoming available and need to be added to the VAMC pages. Before we can determine the right experience for Veterans, we need to understand both the individual options and the landscape

The following options are available
- Phone numbers
- Crisis Line
- Mental health phone numbers
- VA health chat (Discovery effort in #27686)
- Secure messaging (Discovery effort in #27687)
- VA health connect (Discovery effort in #27688)

Plus others, such as...

- [this list of "helpful numbers"](https://www.va.gov/resources/helpful-va-phone-numbers/)
- new "new single access telephone contact point" 800-MyVA411
- From [Pittsburgh Make an appointment page](https://www.va.gov/pittsburgh-health-care/make-an-appointment/)
  - Primary care call center - Toll free and direct 
  - Behavioral health call center
  - For drug or alcohol evaluation and treatment appointments - Center for Treatment of Addictive Disorders (CTAD)
  - Specialty care specific lines
- A-Z list on the [Contact us page](https://www.va.gov/pittsburgh-health-care/contact-us/)

## Tasks

- [x] Consider communication audit across VAMC product to identify all the places and options presented to Veterans
- [ ] Determine which options are legislatively required to be present  
- [ ] Determine which options are still in use
- [ ] Identify what options are missing, if any
- [ ] Understand use cases for the various methods to develop future Veteran research
- [ ] Research from call center may also be helpful

**Comment by lildziner** [comment]
**Phone Number Audit:**
Here is a [link to the spreadsheet ](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Facilities%20Team/2021%20-%20Mobile%20Clinic%20Discovery%20and%20Design/VISN%208%20Phone%20Audit.xlsx?d=wde893f1280744f7fbc565dec58595748&csf=1&web=1&e=bLXYrw)documenting the main phone numbers present on VISN 8 facility pages and facility locator. The spreadsheet lists the Veteran facing language and listed number. The last column flags numbers that seem like logical candidates for replacement by VISN 8's Clinical Contact Center, "VA Health Connect" - 1-877-741-3400.

This is still in progress. Numbers have not yet been mapped to stakeholders.

**Comment by lildziner** [comment]
@nicko-amida I am taking screengrabs of the main pages with phone numbers on them and tagging them by type of phone in [this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1630421025033/f184b85a498694d12baced65c028f8be8545760a?sender=leydahughes3111). This goes with the phone spreadsheet above but maybe this Mural can be the start of our combined synthesis to identify all the communications methods as well (what Veterans see, how it's worded and where)?  Maybe we can discuss first to see what the ultimate output could be.

**Comment by nicko-amida** [comment]
@lildziner Ok thanks, sounds good. I can start adding anything relevant from my discovery to the board.

**Comment by nicko-amida** [comment]
@lildziner Here's where I'm starting the top categories by [call type and questions viewed](https://app.mural.co/t/vsa8243/m/vsa8243/1630421025033/f184b85a498694d12baced65c028f8be8545760a?wid=0-1631811579454).
