### ISSUE TITLE
Update alert icons on Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29543]
## Issue Description
In #27206, we updated the operating status alerts to use the informational icon. The changes were reflected  on the Facility Locator and VAMC pages but not on the Vet Center pages. 

Example: Reno Vet Center 
<details>
<summary> As it appears on the Facility Locator </summary>

![image](https://user-images.githubusercontent.com/55411834/131585529-50c9add1-7f3f-40fb-a171-ce75da6c7670.png)

</details>

<details>
<summary> As it appears on the Vet Center pages  </summary>

![image](https://user-images.githubusercontent.com/55411834/131585475-86c1bb2c-bc94-49d5-9210-cf9a2626093c.png)
![image](https://user-images.githubusercontent.com/55411834/131585662-814ef937-8293-4444-9228-cb38b492b346.png)

</details>

---
## Tasks
- [x] Refer to the [VA design system for icons](https://design.va.gov/design/icons#feedback)
- [x] Ensure the implementation on all Facility Locator, VAMC and Vet Center pages display the informational icon for `Limited services and hours` operating status alerts

## Acceptance Criteria
When a facility's operating status = `Limited services and hours` 
- [x] Veterans viewing the facility operating status on a Vet Center main page will see the informational icon. 
- [x] Veterans viewing the facility operating status on a Vet Center Locations page will see the informational icon.

**Comment by mmiddaugh** [comment]
@gescobardev See also [Alert component](https://design.va.gov/components/alertboxes)
