### ISSUE TITLE
Update error message placement for single checkbox

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29551]
## Issue Description
The guidance for the checkbox component advises inconsistent error message placement. The error message appears below the input for a single checkbox, but above if there is a group of checkboxes. Refer to this issue for details https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/535

**Correct placement (Checkbox group):**
![Form feedback - VA.gov Design System 2021-09-01 09-12-32.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/77d69397-b270-45e0-95fa-4a8c7a04e47f)

**Incorrect placement (Single checkbox):**
![Form feedback - VA.gov Design System 2021-09-01 09-12-17.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/18b79a30-befe-4b5b-a42f-d49a07ed2c8c)

---
## Tasks
- [ ] Error messages should appear consistently regardless of how many checkboxes are in a group - under the label, and above the first input (like we do for a checkbox group).

## Acceptance Criteria
- [ ] Error messages should appear consistently regardless of how many checkboxes are in a group - under the label, and above the first input (like we do for a checkbox group).
- [ ] Design system guidance recommends consistent placement of error messages.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
