### ISSUE TITLE
Send Ch31 submission communication preferences to VRE

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#29552]
## Description
VRE needs to see communication preferences for each submission. As there is no CMS in place at VRE it makes this difficult, and GA was not the best choice since they could click EVA and TeleCounseling back and forth and provide false data.

## Reference
![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/4f8905d9-a9dc-40a3-972f-c331e6b43712)

## Tasks
- [x] Using the already parsed claim objects, add two columns to the nightly summary email and output the claims's preferences for useEVA and TeleCounseling

## Acceptance Criteria
- [x] Two new columns exist with the applicants response as Yes or No
- [x] PR is submitted for review
