### ISSUE TITLE
[MCP] Use case: No history at a facility when other active balances exist

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29565]
## Issue Description
This ticket is part of the epic where we will be creating mocks for each of our use cases for testing and engineering purposes.

**Use case:** No history at a facility when other active balances exist

---
## Tasks
- [x] Create a design that reflects the use case above
- [ ] ~Upload to UXPin~
- [ ] ~[Update GH use case file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Docs/MCP-Use-Cases.md)~

## Acceptance Criteria
- [ ] ~Designs uploaded to UXPin~
- [ ] ~GH file updated and linked in ticket~

**Comment by rebeccawalsh** [comment]
After doing some design work, Riley and I came to the conclusion that we will just not show facilities who don't have charges within the past 24 months in the tool until testing can determine if this is a necessary feature. Here are some of the designs we put together during our discussions:

## Design one - non-interactive card
This design would probably cause some issues with the interactive 0-balance cards that are clickable. A Veteran may wonder why one is clickable but not the other.
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/a406b516-3820-4a7f-8774-7aa85f1a18a0)

## Design two - non-active facility ul
This design de-emphasizes non-active facilities and encourages Veterans to go update their preferred facilities in Liz's design on VA Profile. We're unsure if it's wise to encourage leaving our tool, though.
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/cc6a2306-7748-4d6c-b5a2-cec8dc53261e)

## Decision
Don't show VA facilities without activity for the past 24 months!
