### ISSUE TITLE
Audit existing GA implementation materials and scope new ones

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29569]
## Issue Description
VFS teams understand how to read user interaction data and navigate the modernized view in Google Analytics. Platform Analytics team needs to understand what resources are already available on Github to update/transfer to Confluence and what gaps still need to be met.

---
## Tasks
- [ ] Audit existing documentation.
- [ ] Compare existing documentation to needs identified in [Mural workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1598479416734/2f7bfbc19bf0629c0c9b5fcc559444aec95e2256?sender=uefee97503966efdb24069760).
- [ ] Update document creation ticket with specific content gaps.

## Acceptance Criteria
- [ ] Platform Analytics team has migrated everything that can be transferred to Confluence and understands the new documentation that needs to be created.
