### ISSUE TITLE
CHIP Returns a list of updated appointments

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#29579]
We need a series of endpoints to update the list of appointments viewable to a Veteran.

CHIP side - CHIP can pass appointment data with a Patch or Put endpoint

LoROTA side - LoROTA endpoint for updating data so when CHIP passes appointment data with a Patch or Put endpoint

**Task is Done When:**
Appointment data can be updated through CHIP and LoROTA

**Comment by kjduensing** [comment]
Split into 2 stories

**Comment by kjduensing** [comment]
CHIP Story: 5
LoROTA STory: 5

**Comment by kjduensing** [comment]
Questions:
- Is stationNo something that should be considered 'read.basic'?
- Does CHIP need to re-up the options when putting to LoROTA?
  - Resend options as they are?
  - Recalculate valid start/end times?

TODOS:
- [ ] ask FE to send appointmentIEN
- [ ] collab with Carl/FE team to choose response structure
- [ ] collab with Carl/FE team on if this is a full replace
- [ ] Getting patientDFN requires updates from VEText
- [ ] Implement appointment eligibility calc for payload (can leverage validators?)
