### ISSUE TITLE
Create new page for COVID-19 vaccine records online and update vaccine mini hub content

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#29572]
## Issue Description
Now that Veterans can get a copy of your VA COVID-19 vaccine records through the My HealtheVet website or on their mobile device, we are going to create a child page of the vaccine mini-hub to use for information and questions pertaining to vaccination records.
This page will also need to be translated as well as questions added/updated on the mini-vaccine hub.

**Doc sent to translators:**
[Covid Content Update 08.30.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7099203/Covid.Content.Update.08.30.21.docx)

---
## Tasks
- [x] _Create child page for COVID-19 vaccine records online_
- [x] _Add questions to mini-vaccine hub_
- [x] _Send content to translators_
- [x] _Update chatbot_
- [x] _Create Tagalog child page for COVID-19 vaccine records online_
- [x] _Create Spanish child page for COVID-19 vaccine records online_
- [x]  _Review and publish pages_

## Acceptance Criteria
- [x] _Child page for COVID-19 vaccine records online is live_
- [x] _Tagalog child page for COVID-19 vaccine records online is live_
- [x] _Spanish child page for COVID-19 vaccine records online is live_
- [x] _Updates to vaccine mini-hub are live_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht here's the new page for review. http://preview-prod.vfs.va.gov/preview?nodeId=3479

**Comment by lunascoop** [comment]
@RLHecht the translated pages are ready for review. My notes are below.

**Translated docs**

- [13576_Covid Content Update 08.30.21_Spanish Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7130526/13576_Covid.Content.Update.08.30.21_Spanish.Final.docx)
- [13575_Covid Content Update 08.30.21_Tagalog Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7130527/13575_Covid.Content.Update.08.30.21_Tagalog.Final.docx)


**Tagalog pages**

- Paano makuha sa online ang talaan ng bakuna para sa COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=35108 (had to shorten meta title) (The more helpful information section needs to be translated. I've attached a doc that can be sent to the translation team below)
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413 (A sentence for the Is there a cure or any FDA-approved treatments for COVID-19? question needs to be translated. It's also included in the doc to send to the translation team.)

**Spanish pages**

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Cómo obtener su historial de vacunas COVID-19 en línea: http://preview-prod.vfs.va.gov/preview?nodeId=35120 (had to shorten meta title)

**Doc to send to translation team**

- [Covid Content updates 9.8.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7130534/Covid.Content.updates.9.8.21.docx)

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back for the pieces that were missing. [https://app.zenhub.com/files/133843125/c473b920-2f2f-4da2-abb2-491b187e0097/download](https://app.zenhub.com/files/133843125/c473b920-2f2f-4da2-abb2-491b187e0097/download)

[https://app.zenhub.com/files/133843125/b1598016-49b6-4cb5-b243-1866c9bd3c83/download](https://app.zenhub.com/files/133843125/b1598016-49b6-4cb5-b243-1866c9bd3c83/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

Tagalog pages

- Paano makuha sa online ang talaan ng bakuna para sa COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=35108 
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

Spanish pages

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
The Spanish and Tagalog pages have now been published.

**Comment by RLHecht** [comment]
This page is live. Closing for now and will open if Mateo's team has any updates for us to make.

**Comment by RLHecht** [comment]
@lunascoop Here are Mateo's comments. Can you please update the pages with his changes?

[COVID Vaccine Online Records.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7197161/COVID.Vaccine.Online.Records.docx)
[VHA Translation COVID Vaccine Online Tagalog.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7197164/VHA.Translation.COVID.Vaccine.Online.Tagalog.docx)

**Comment by RLHecht** [comment]
Bringing over Selina's comment from a different ticket: 

@RLHecht these pages are ready for review. I think these pages were originally tracked in another ticket (#29572 )

Paano makuha ang iyong talaan ng bakuna para sa COVID-19 online: http://preview-prod.vfs.va.gov/preview?nodeId=35108

Had to shorten title for meta title tag (perhaps we should let the translators know that the title has to be w/in a certain character limit)
For step 4 of the 1st process list, I partially updated the translation of the first bullet, second sentence. The translation provided seems to have started mid-sentence. I'm unsure if that was intentional. Based on Google translate, adding "iyong" to the current sentence vs. the translation provided sounds closer to the English version.
I'm unsure about the "More helpful information" translation. It seems the current version is closer to the one they provided. I did make the change though, but perhaps it should be confirmed.
Cómo obtener su historial de vacunas COVID-19 en línea: http://preview-prod.vfs.va.gov/preview?nodeId=35120

**Comment by RLHecht** [comment]
Thanks @lunascoop I published both of these pages.

**Comment by RLHecht** [comment]
Work completed on this. Closing ticket.
