### ISSUE TITLE
Create new GA usage documentation

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#29573]
## Issue Description
VFS teams understand how to read user interaction data and navigate the modernized view in Google Analytics. To be started once discovery/audit of existing documentation (#29569) is complete.

---
## Tasks
_Platform Analytics to update list of artifacts here needed here once auditing work complete. Below are ideas from [Mural session](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1598479416734/2f7bfbc19bf0629c0c9b5fcc559444aec95e2256?sender=uefee97503966efdb24069760):_
- [x] GA 101 to help completely new users get started.
- [x] Expanded FAQs for GA (currently in WIP folder)
- [ ] Guide to GA segmentation: how to do, what fields to use, and what to look for.
- [ ] Guide to GA findability metrics: page paths, campaigns, sources, etc.

## Acceptance Criteria
- [ ] VFS teams have access to new resources that explain and model how to use GA to answer their own analytics questions.

**Comment by bsmartin-ep** [comment]
### Complete:

_GA 101 to help completely new users get started._
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/New-Users-to-Google-Analytics.1877704964.html

_Expanded FAQs for GA (currently in WIP folder)_
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Frequently-Asked-Questions.1783333118.html

### TODO:

_Guide to GA segmentation: how to do, what fields to use, and what to look for._
Existing content:  https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics.1877999672.html#GoogleAnalytics-Segments

_Guide to GA findability metrics: page paths, campaigns, sources, etc._
