### ISSUE TITLE
Wire up Alarms and PagerDuty Alerts for Synthetic Monitors

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#29589]
# Description
There are currently three Canaries that are not wired up to alarms in AWS or PagerDuty alerts.

## Tasks
- [x] Create an AWS alarm and PagerDuty alert for `build-error-check`
- [x] Create an AWS alarm and PagerDuty alert for `vagov-heartbeat`
- [x] Create an AWS alarm and PagerDuty alert for `data-fetch`

**Comment by rjohnson2011** [comment]
The 3 alarms were successfully created.
