### ISSUE TITLE
Upgrade Cypress to Current Version After GitHub Actions Release

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#29597]
# Description
We have fallen a bit behind the current Cypress version ([8.7.0](https://docs.cypress.io/guides/references/changelog#8-7-0)). We are currently on Cypress 7.6.0 which was released on Jun 23, 2021. Once GHA is released and stable, we should make the upgrade and resolve any issues that result.

## Tasks
- [ ] Upgrade `vets-website` to current Cypress version (8.3.1 at time of writing)
- [ ] Resolve issues with any breaking test specs in `vets-website`
- [ ] Upgrade `content-build` to current Cypress version (8.3.1 at time of writing)
- [ ] Resolve issues with any breaking test specs in `content-build`
