### ISSUE TITLE
[Kubernetes] Argo - certificate signed by unknown authority

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29603]
## Description
After the update yesterday, it seems that argo is having trouble fetching some helm charts.  This is because I missed the fact that we were building the needed containers from dockerfiles that integrated the VA certs.  In the most recent GHA I implemented, the images are being pulled directly from the repo itself instead which means the certs are missing.

![image](https://user-images.githubusercontent.com/76792875/131880619-8a992caa-6b65-42aa-aa2f-64b8aa299e25.png)

To make things more interesting, a new ami for the worker nodes was built last night so I had to disable the eks rolling update wand fix this before all of the nodes are cycled out.  With the current helm chart deployment issues this would have most likely caused a outage of some sort or another. 

https://dsva.slack.com/archives/C37M86Y8G/p1630561519057600
https://github.com/department-of-veterans-affairs/devops/pull/9883

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29465#issuecomment-910535839 

---
## Tasks
- [x] disable eks rolling update so the clusters don't blow up
- [x] rework GHA to build from dockerfile that incorporates VA certs
- [x] redeploy argo
- [x] re-enable eks rolling update and deploy new nodes to all clusters
## Acceptance Criteria 
- [x] Argo no longer complains about certificate issues

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Argo has been redeployed and is no longer failing to fetch helm charts

![image](https://user-images.githubusercontent.com/76792875/131930670-d023eb94-5b0f-4415-9aba-93ca42a7e2a3.png)

**Comment by mleclerc00** [comment]
https://dsva.slack.com/archives/C37M86Y8G/p1630689134070400

**Comment by dginther** [comment]
Looks good!
