### ISSUE TITLE
Add LGBTQ+ to word list

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29607]
## Issue Description
Now that we are using LGBTQ+ on VA.gov pages, we need to add this as an entry to the word list in the style guide.

## Tasks
- [x] Add LGBTQ+ entry to word list (Randi)
- [x] Review merge PR (Danielle)

## Acceptance Criteria
- [x] LGBTQ+ listed in style guide word list

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I added this entry to the word list in the same branch as the quotation mark entry if you want to review both at the same time: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/496

**Comment by RLHecht** [comment]
Kelson, pulled out the LGBTQ+ work into a separate PR, which I reviewed and merged. It's here for reference: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/540. Moving this to validate and will close once the changes are live in the style guide.

**Comment by RLHecht** [comment]
These addition is now live in the style guide. I'll add it to the what's new section when we finish the apostrophe section so that they both get listed together.
