### ISSUE TITLE
Update non-government headstones and markers content on Veterans burial allowance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29615]
## Issue Description
Stakeholder Angie Smith asked us to update content on the [How to apply for Veterans burial allowance page](https://www.va.gov/burials-memorials/veterans-burial-allowance/). 

In the section "Headstone or marker allowance amounts" the new information provided is:

For non-government markers, the amount of reimbursement will be the lesser of the
- actual cost of the non-government headstone, marker, or additional engraving, or
- amount determined by NCA to be in effect at the time of purchase.

This information needs to be reworked into plain language and VA's voice and style and will replace the the table that is there currently.

# Tasks
- [ ] Remove table and replace with reworked plain language text
- [ ] Send to stakeholders for approval
- [ ] Review and publish
- [ ] Alert stakeholder that change is live on site

## Acceptance Criteria
- [ ] New headstones and markers content is on live page

**Comment by RLHecht** [comment]
Waiting to hear back from Angie for clarification on whether the text provided is replacing the table or if it's in addition to what is on the page.

**Comment by RLHecht** [comment]
@bethpottsVADEPO What do you think of this update?

For non-government markers, we'll reimburse you for whichever amount is less: 
- The actual cost of the non-government headstone, marker, or additional engraving, **or**
- The cost set by NCA that's in effect at the time of purchase

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here are my suggestions for the updated burial allowance content: [https://app.zenhub.com/files/133843125/c5a831ad-13f6-40bc-934d-412e6722c080/download](https://app.zenhub.com/files/133843125/c5a831ad-13f6-40bc-934d-412e6722c080/download)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks for working this up! I have 3 edits for you:
1/ Can you change "We'll give you and allowance toward the purchase of" to "We'll give you an allowance for purchasing" 
2/ For this: Check the chart to determine how much the allowance is based on when you purchased the headstone or marker.
Let's say: Check this chart to find out how much allowance you can get based on when you purchased the headstone or marker.
3/ For this: We'll reimburse you for whichever amount is less:
Let's say: We'll pay you back for whichever amount is less:
4/ For this: The cost set by the National Cemetery Administration (NCA) at the time of purchase
Do we mean this? (and will you find out if the SMEs are ok with this): 
"The amount set by the National Cemetery Administration for covering this cost (whatever amount is in place at the time of purchase)"

**Comment by RLHecht** [comment]
We sent these changes to the stakeholders on November 5 but they responded that NCA needs to work with VBA to figure out the best way tot communicate this. This ticket is blocked until they get back to us. @bethpottsVADEPO should we follow up on this request?

**Comment by bethpottsVADEPO** [comment]
Yes, thank you, @RLHecht, would you follow up?

**Comment by SgardnerPMP** [comment]
@RLHecht will send follow up email 3/30 to engage stakeholders.  Still in blocked.

**Comment by RLHecht** [comment]
Update: Emailed stakeholder on 3/30 and he said they'd begin working on it ASAP. I'll move out of blocked once they send us back their edits.
