### ISSUE TITLE
COE - Build document upload widget for Eligibility App

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#29617]
## Description
After a veteran submits a request for a COE, their application is pending. During this time, it's possible LGY requests further documentation to support a veteran's application. The eligibility app should include a document upload widget that accepts specified file types, displays a list of document types (dd214, separation of service, marriage certificate etc), and allows a veteran to submit further documentation with just a few clicks. 

## Considerations
- [most updated document upload mockups](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140741546/simulate/sitemap)
- [Claims status tool upload tool](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/applications/claims-status/components/AddFilesForm.jsx#L1)
- Schemaform may be too heavy for what we want to do here.

## Tasks
- [ ] Create a document upload widget that allows file upload and includes a dropdown list of document types

## Acceptance Criteria
- [ ] Widget has been created and tested. 
- [ ] PR has been submitted
