### ISSUE TITLE
Migrate from attr_encrypted to lockbox for db key rotation 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29612]
## Issue Description
After running into malformed data and other blockers while working on a custom solution for rotating encryption keys via the attr_encrypted gem, the [Lockbox gem](https://github.com/ankane/lockbox) looked to already have built in functionality for key rotation. The lockbox documentation also provides a [migration path](https://github.com/ankane/lockbox#migrating-from-another-library) if you’ve already implemented attr_encrypted.

---
## Tasks
- [x] update devops settings [PR merged](https://github.com/department-of-veterans-affairs/devops/pull/9882)
- [x] add new columns via migration/update schema [PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/7817)
- [x] add encrypts to models with the migrating option 
- [x] create rake task to migrate existing models
- [x] run said rake task in dev first (and other envs next)
- [x] run test suite/test locally
- [x] if all is well, create migration to remove old attr_encrypted columns and model references

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ericboehs** [comment]
Some things to consider:
  - Are we auditing any of these fields with an auditing library (e.g. paper trail)?
  - What is the old cipher/algorithm? Is AES-GCM sufficient?
  - Let's add a ticket for kms
  - We should add padding to guard against data leakage. No?

**Comment by LindseySaari** [comment]
Latest update: waiting for a review from vsp-security. Thread [here](https://dsva.slack.com/archives/C01CJV0L9PS/p1631122211049300)

**Comment by LindseySaari** [comment]
The [lockbox PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7816) has been merged into master. The rake task will be run in dev/staging upon deploy. This change will not be released to production until Tuesdays deploy. After the successful deploy, the migration rake task will be run in prod.

**Comment by LindseySaari** [comment]
Latest update:
Lockbox.migrate was run for all models with encrypted attrs across all envs. Prod was the slowest (obv) with having to rotate ~9 million records. The next step is to work towards removal attr encrypted. Some testing is needed and a [draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7848) has been started

**Comment by LindseySaari** [comment]
Update: Working on breaking up [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7848/files) to appease danger so that /db and code changes don't go out at the same time for backwards compatibility purposes
