### ISSUE TITLE
[Epic] Content and IA request from My Education Benefits Team (Wizard Update & URLs)

### ISSUE THREAD

**Issue by rlyons89** [department-of-veterans-affairs/va.gov-team#29622]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [X] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
*Use this space to describe your content need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

- Review and provide guidance on recommended URLs for the pages within our new education benefit application (excel with URLs attached to this form)
- Review and provide guidance on updating the wizard on the education 'how to apply' page to properly direct users to our new application
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Product%20Outline.md
- Link to or attach user flows: https://accenturefederal.invisionapp.com/freehand/document/KVt7Z0odx
- Link to prototype or mockups:
    - How to apply: https://share.goabstract.com/d824fa12-012c-4dc5-b1a8-19a68e5db3d3?collectionLayerId&mode
    - Application Instructions: https://share.goabstract.com/0b13d6f3-118b-4dd8-a1df-edeb915ea8ec?collectionLayerId&mode
    - Applicant Information: https://share.goabstract.com/ab19d419-c464-4c89-8452-3540e39dad19?collectionLayerId&mode
    - Contact Information: https://share.goabstract.com/53efdc99-69e5-4e7b-8984-5891f0e9f593
    - Service History: https://share.goabstract.com/0eecdcc8-679a-47f1-993f-8845c513fd1f
    - Benefit Selection: https://share.goabstract.com/899dfce6-6748-47a4-a310-3314187ab45f
    - Additional Considerations: https://share.goabstract.com/905fde97-abe9-4429-ae4c-a08536a2a9d1
    - Application Review: https://share.goabstract.com/3818f1fd-5e90-452e-a3e8-a4e8c28d35d4
    - Application Confirmation: https://share.goabstract.com/95d711f4-7a67-4344-bcc6-e74063ec3bb0
[URLs for MVP.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7100803/URLs.for.MVP.xlsx)

- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26551#issuecomment-867659068

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: 12/18
- Estimated staging review date: 11/1
- Content and IA work needed by: 9/16

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: My Education Benefits
-	OCTO-DE product owner: Matt Self
-	Product manager: Shamik Desai
-	Designer: Russell Lyons, Leelah Holmes
-	FE engineer: Cesar Santiago
-	Product/team Slack channel: https://app.slack.com/client/T03FECE8V/C02825JJJRW 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
@rlyons89 I'm digging into this work, and have a few questions for you as I work through things:
1. For authenticated users that have an application in progress, when they are prompted to continue, I'm assuming the logic knows which version of the 1990 flow to send them to? 
2. In the wizard you have included a link to "Learn more about the Post-9/11 GI Bill" in that question.  This link will take them to a different page and when they return they will need to start the wizard again.  We do not provide "learn more" links for any of the other options. Just wanted to call that out. 
3. Is the intent to eventually fold the other 1990 flows (unauth and MGIB) into this version of the form flow over time?  If so, that could impact our URL structure - i.e. the URL would not need to be specific to Post-9/11.  
4. FYI, the breadcrumb, once in the form flow, does not change.  On your confirmation page, you show a variation that includes "Application confirmation".  
5. On the confirmation page, where does the link to "View an explanation of your benefits" go?

**Comment by rlyons89** [comment]
@mnorthuis, see responses below:

1. Yes, if they will be directed to the correct version when picking an application back up.
2. If it would be preferred/recommended to remove this link, our team is fine with that.
3. Ideally, the user would be able to switch to this new form if they signed in when starting with the unauthenticated version in the future, but the current unauthenticated version would still be needed (or some version that users can manually enter data into). And yes, we intend to add MGIB to this version in a future release.
4. That is an oversight on our part, we will update.
5. It would take users to the statement of benefits page: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/

**Comment by rlyons89** [comment]
2. Sounds good, we will update.
3. Sounds good, no concerns here.
5. It is possible but unlikely that the user would have enrollment activity immediately after applying. Our goal was to start directing users to where they could track their entitlement usage when they start attending school. I will confirm there is need to direct applicants that are under review or declined to that page.
6. Our goal was to introduce that page as the main point that a user can return to in order to access all their education benefit info in the future, since they could very well have no idea that the My VA page exists at that point. It would be an important access point to their CoE letter of denial letter if they misplaced it after leaving the confirmation page.
7. We wanted to make sure personal information was a clear step on its own since modifying this information affects whether or not we can automate the processing of the application. Also, there could be additional information added to the personal info page in the future when we add in functionality for beneficiaries that are applying for benefits based on the service of a family member.
8. Partly, this is the way the questions are currently organized on the application so we didn't want to move too far away from that. The questions are all related to your military service record but in the future we might have a need to add questions that aren't related to the applicants service history.

We have already taken the designs for usability testing and will be sharing some of our findings during the weekly design sync next week. We did a midpoint review a few weeks back ahead of testing and have had a few follow-up conversations with Rachael R and Ryan T since then to address some of the feedback.

**Comment by mnorthuis** [comment]
@rlyons89 Core IA information is available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-1990-post-9-11.md

A couple of things to note:
- There are ways that users can directly link to the existing 1990 form.  I am assuming that when this happens, the user will complete the existing 1990 as it is - including in an authenticated state if they are logged in. 
- I did not provide URL slugs for each step in the form flow.  Once past the initial page, the URL isn't as critical, so teams generally assign those segments themselves. You should continue to follow general best practices for URLs:
  - Keep each segment/slug short and succinct - preferably 1 or 2 words
  - separate words in the segment with dashes
  - use plain language and words that our Veterans use
  - I personally do not think the URLs do not need to represent the groupings that the steps use within the flow - this creates extra hierarchy and length in the URL that isn't necessary (i.e. if the page is "Provide your phone and email" the slug can be /phone-email/ or /contact-phone-email/ , and doesn't need to be /contact-information/phone-email/.

If you have any questions please let me know.

**Comment by bethpottsVADEPO** [comment]
@rlyons89 Here's some content feedback for How to apply / Application instructions / Applicant Information screens. I'd like to revisit some of the content in the rest of the screens before staging review, so I'll be in touch to figure out the timing of that. But I believe these are the screens that will have the most edits from me--especially the intro screen. (I did click through the others, and one thing jumped out at me: Would find out the messaging the designers/devs normally use on the confirmation screen--because "Wait right there" isn't our VA.gov voice. I'm sure there's some standard language for that. Thanks for checking on that!)

**1/ How to apply: https://share.goabstract.com/d824fa12-012c-4dc5-b1a8-19a68e5db3d3?collectionLayerId&mode**

- New question is missing a hyphen. Should be: Post-9/11 GI Bill

- Remove the link: Learn more about the Post-9/11 GI Bill (I see Mikki already raised this--I wanted to second that!)

**2/ Application Instructions: https://share.goabstract.com/0b13d6f3-118b-4dd8-a1df-edeb915ea8ec?collectionLayerId&mode**

- Under the H1 (**Apply for VA education benefits**), please change the order of the subheading there to align with our new style, and capitalize the F in "Form": Application for VA Education Benefits (VA Form 22-1990). Apply this change across all screens.

- In the warning alert box, change "Currently" to "At this time" to follow our plain language standards.

- In the warning alert box, change this sentence: "If you would like to apply for other benefits, please visit our How to Apply page." 
To this: "If you want to apply for other education benefits, find out what you're eligible for."
[Find out about GI Bill and other education benefit eligibility] https://www.va.gov/education/eligibility/
(I think it makes more sense to link to eligibility than how to apply because the former has links to all the specific education benefit pages, but how to apply doesn't.)

- Move the blue stripe info alert box down under the subway map. This new placement tested well in user research for both the FSR (debt) application and the HC app. I will follow up in this ticket with a screen shot when I can get my hands on one. Or you can check in with designer Dene Gabaldon, who ran the testing for the HC app.

- Subway map edits (this is a new approach we're starting to take on intro pages):
Header: **Follow these steps to get started** (cut the text about "What if I need help filling out my application?")

1. **Check your eligibility**
Make sure you meet our eligibility requirements before you apply.
_Additional info link:_ What are the Post-9/11 GI Bill eligibility requirements?
_Unfurled text:_ 
At least one of these must be true:
- You served at least 90 days on active duty (either all at once or with breaks in service) on or after September 11, 2001, **or**
- You received a Purple Heart on or after September 11, 2001, and were honorably discharged after any amount of service, **or**
- You served for at least 30 continuous days (all at once, without a break in service) on or after September 11, 2001, and were honorably discharged with a service-connected disability, **or**
- You're a dependent child using benefits transferred by a qualifying Veteran or service member

2. **Gather your information**
Here's what you'll need to apply:
- Your military service history
- Your current address and contact information

3. **Start your application**
We'll take you through each step of the process. It should take about 15 minutes.
_Additional info link:_ What happens after I apply?
_Unfurled text:_ 
After you apply, you may get an automatic decision. If we approve your application, you'll be able to download your Certificate of Eligibility (or award letter) right away. If we deny your application, you can download your denial letter. We'll also mail you a copy of your decision letter. 

**Note:** In some cases, we may need more time to make a decision. If you don't get an automatic decision right after you apply, you'll receive a decision letter in the mail in about 30 days. And we'll contact you if we need more information.

**3/ Applicant Information: https://share.goabstract.com/ab19d419-c464-4c89-8452-3540e39dad19?collectionLayerId&mode**

- Change "Applicant information" throughout to "Your information"

- My understanding is that you can't change your personal information online in your profile. You can only change your address and other contact info that way, but not your name or birth date. Please change that content to say this: This is the personal information we have on file for you. If you notice any errors, please correct them now. Any updates you make will change the information on this application only.
**Note:** If you need to update your personal information with VA, you can call us at 800-827-1000. We're here Monday through Friday, 8:00 a.m. to 5:00 p.m. ET.

- In the green box "Application has been saved" please change "Last saved at" to "Last saved on"

**Comment by audayotte** [comment]
@bethpotts Thanks for the feedback, we're currently reviewing the proposed changes with our Product Owners at EDU. If possible, could you also provide any content questions/feedback on the other pages by EOD 9/20? Our dev team will need to create new stories to address so we want to give them as much notice as possible for changes as we get close to the end of our Program Increment.

**Comment by bethpottsVADEPO** [comment]
@audayotte I can at least give high-level content feedback by then. Then you'll get more detailed edits from your collab cycle review with @peggygannon. And I'll communicate with her about which screens I haven't been able to spend as much time on, so she's aware.

**Comment by bethpottsVADEPO** [comment]
@rlyons89 @audayotte @peggygannon I'm putting the staging link here for the intro to the health care form that was shared in the design meeting today for your reference. You could definitely add the "Why we're asking for this information" additional info component: https://staging.va.gov/health-care/apply/application/introduction

**Comment by bethpottsVADEPO** [comment]
@rlyons89 @audayotte Here's some more content feedback--for contact information. It sounds like you wanted to wrap up my feedback by today, but if you want to extend this into a future sprint, I could put aside some more time over the next week or two to finish getting through the rest of the screens. Otherwise, you can get edits from @peggygannon during the next collab cycle review. 

@peggygannon I've gotten through these screens, so you can focus your efforts more on the others that I didn't have time to dig into:
How to apply: https://share.goabstract.com/d824fa12-012c-4dc5-b1a8-19a68e5db3d3?collectionLayerId&mode
Application Instructions: https://share.goabstract.com/0b13d6f3-118b-4dd8-a1df-edeb915ea8ec?collectionLayerId&mode
Applicant Information: https://share.goabstract.com/ab19d419-c464-4c89-8452-3540e39dad19?collectionLayerId&mode
Contact Information: https://share.goabstract.com/53efdc99-69e5-4e7b-8984-5891f0e9f593

### Text for "Need help?" that appears on several screens

Please change the text to this (based on the HC application again but with EDU-specific details):

**If you have trouble using this online application,** call our MyVA411 main information line at <a href="tel:+18006982411" aria-label="8 0 0. 6 9 8. 2 4 1 1.">800-698-2411</a> (<a href="tel:711" aria-label="TTY. 7 1 1.">711</a>). We're here 24/7.

**If you need help to gather your information or fill out your application,** you can call us at <a href="tel:+18884424551" aria-label="8 8 8. 4 4 2. 4 5 5 1.">888-442-4551</a> (<a href="tel:711" aria-label="TTY. 7 1 1.">711</a>). We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. If you're outside the U.S., call us at 001-918-781-5678.


**https://app.abstract.com/share/53efdc99-69e5-4e7b-8984-5891f0e9f593**
### Contact information

1/ Review your phone numbers and email address
Change the 2 bullets to this:
- Contact you if we have questions about your application
- Tell you important information about your benefits

Change the text immediately under the bullets to:
This is the contact information we have on file for you. If you notice any errors, please correct them now. Any updates you make will change the information for your education benefits only. 
**Note:** If you want to update your contact information for all your VA benefits, you can do that from your profile.
[Go to your profile]

2/ Review your mailing address
Change the text to:
This is the mailing address we have on file for you. If you notice any errors, please correct them now. Any updates you make will change the information for your education benefits only.
**Note:** If you want to update your contact information for all your VA benefits, you can do that from your profile.
[Go to your profile]

### Choose your notification method
Change this header to: **Choose how you want to get notifications**
Change the text to: We recommend that you opt in to text message notifications about your benefits. These include notifications that prompt you to verify your enrollment so you'll receive your education payments. This is an easy way to verify your monthly enrollment. 

Would you like to receive text message notifications about your education benefits?
Yes, send me text message notifications
No, just send me email notifications

Change the blue info alert text to:
If you choose to get text message notifications, messaging and data rates may apply. At this time, we can send text messages about your education benefits only to U.S. mobile phone numbers.

Change the first yellow info alert text to:
You can't choose to get text message notifications because you have an international mobile phone number. At this time, we can send text messages about your education benefits only to U.S. mobile phone numbers.

Change the second yellow info alert text to:
You can't choose to get text message notifications because we don't have a mobile phone number on file for you.

**Comment by audayotte** [comment]
@bethpotts thank you for the feedback - we'll take this back for review with our EDU Product Owners. Following up on previous feedback, we're planning to implement your suggested changes, with the exception of the following below. Let us know if you have any additional questions, and thanks again for your time!

- Application Instructions - Alert that this application is only for Post-9/11 GI Bill: The intention of this alert is to warn them that this application is only for the Post-9/11 GI Bill vs providing eligibility for other benefits. This tested really well in usability testing w/users and we recommend keeping as is. 
- Application Instructions - Removal of 'What if I need help filling out this application' section: We recommend keeping this section as is. We understand that some Veterans may need help filling out applications, and wouldn't want to remove the ability for them to find assistance on this page. 
- Application Instructions - New Copy for 'Check your Eligibility': We plan to include most of this but will remove the bullet for 'you're a dependent child' since our application will only accept those using their own entitlement, and this will be accounted for in the 'How to Apply' flow leading to the application. 
- Applicant Information - Changing Personal Information Online: In the managed service, updates they make on the application will carry through to the EDU instance of contact information & future claimant service. Therefore, text as is is accurate. 
- Application Confirmation - Removal of My VA Dashboard: We recommend keeping this on all pages to keep actionable and to direct users back to their dashboard. 
- Application Confirmation - Wait right there: This is OBE. Per our development team, the form framework does not currently allow this, so we will not be using this screen.

**Comment by bethpottsVADEPO** [comment]
All of your notes here make sense, but I wanted to clarify what I was trying to convey with the "go to your profile" link (I think that's what you were referring to with "Removal of My VA Dashboard"). I would like to just move the inline link within the sentence onto its own line. Sorry that wasn't clear--I was trying to show that with brackets. This is the style we use most often on our site. 
**Note:** If you want to update your contact information for all your VA benefits, you can do that from your profile.
[Go to your profile]

**Comment by audayotte** [comment]
@bethpotts  That makes sense. The VA Dashboard piece was in relation to the comment above "I spoke with Beth Potts about the link to My VA at the bottom of each confirmation page version - we believe this link only makes sense for the scenario where the application is still under review, so they can check their status. Would that be correct? I'm not sure what other information would be on My VA once the application is approved, or if it is declined." We think it makes sense to keep this piece on all confirmation pages (approved, denied, under review). For near term, it will direct them to a 'home base' for My VA, and for future term, we're looking to update the Education space of the dashboard so that they will be able to see their status and benefits (even across other programs in the event they are declined for one program and not another).

**Comment by mnorthuis** [comment]
I believe IA work for this is complete per my comment above, taking myself off the issue.  Please connect with me if you need anything additional. 


> @rlyons89 Core IA information is available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-1990-post-9-11.md
> 
> A couple of things to note:
> 
> * There are ways that users can directly link to the existing 1990 form.  I am assuming that when this happens, the user will complete the existing 1990 as it is - including in an authenticated state if they are logged in.
> * I did not provide URL slugs for each step in the form flow.  Once past the initial page, the URL isn't as critical, so teams generally assign those segments themselves. You should continue to follow general best practices for URLs:
>   
>   * Keep each segment/slug short and succinct - preferably 1 or 2 words
>   * separate words in the segment with dashes
>   * use plain language and words that our Veterans use
>   * I personally do not think the URLs do not need to represent the groupings that the steps use within the flow - this creates extra hierarchy and length in the URL that isn't necessary (i.e. if the page is "Provide your phone and email" the slug can be /phone-email/ or /contact-phone-email/ , and doesn't need to be /contact-information/phone-email/.
> 
> If you have any questions please let me know.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Can this ticket be closed or is this still being worked on?

**Comment by mnorthuis** [comment]
Per our slack conversation, here is the full list of modernized URLs for the education benefits space...these revised URLs follow the pattern established for other applications on va.gov and are optimized for readability and SEO.  The STEM and VRRAP URLs are already modernized, but listed here for reference. 

- /education/apply-for-gi-bill-benefits-form-22-1990/
- /education/survivor-dependent-benefits/apply-for-dependent-benefits-form-22-5490/
- /education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/
- /education/other-va-education-benefits/national-call-to-service-program/apply-for-benefits-under-ncs-form-1990n/
- /education/other-va-education-benefits/stem-scholarship/apply-for-stem-scholarship-form-22-10203/
- /education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/

As also discussed, as a standard, the breadcrumbs and title tags all need to be updated per standards and for accessibility improvements.  Essentially, the breadcrumb and title tag should directly pull the H1 - breadcrumb is sentence cased and title tags are initial capped.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
