### ISSUE TITLE
[Kubernetes] Datadog - gather metrics from argo

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29620]
## Description
Add prometheus scrape annotations to appropriate argo pods in order for datadog agent to capture stats from the /metrics endpoint.

argocd-application-controller -> port 8082
argocd-dex -> port 5558

## Technical notes
https://docs.datadoghq.com/agent/kubernetes/prometheus/#configuration-1

---
## Tasks
- [x] modify helm values.yml file (https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml) to add pod annotations
- [x] re-deploy argo

## Acceptance Criteria 
- [x] argo metrics can be found in datadog ui

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/commit/dcd35c48d24994467c129f7935a153a18fe0c88e

![image](https://user-images.githubusercontent.com/76792875/131934145-e9d47ab1-ada9-4539-ba3c-347cb5bcdbfb.png)

**Comment by dginther** [comment]
Looks good.
