### ISSUE TITLE
[Access Requests] Review AWS Access section of "Granting Access to Internal Tools" 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#29630]
## Description
Review AWS Access section of "[Granting Access to Internal Tools](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools)" 

## Background/context 
https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools

---
## Tasks
- [x] make sure correct pocs are identified 
- [x] make sure the process is clear and accurate
- [x] ensure all ops team members can view this doc in confluence

## Acceptance Criteria 
- [x] The confluence doc is updated w/ the latest information

**Comment by jhouse-solvd** [comment]
This looks good. Please see linked doc. 

Closing.
