### ISSUE TITLE
Medical Copay Alerts

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29643]
## Issue Description
Create alert components for the various use cases outlined below. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141469738/simulate/sitemap?mode=i) for details

Veteran is not enrolled in VA health care
![MCP Desktop - UXPin Preview 2021-09-03 16-02-41.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/26ec8b5f-9dbb-4db1-9bf6-74c197fe3811)

Veteran has no history of medical copays
![MCP Desktop - UXPin Preview 2021-09-03 16-02-57.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/20deed44-cee5-4a1b-8da0-8fc48a9077c7)

Veteran is deceased
![MCP Desktop - UXPin Preview 2021-09-03 16-03-14.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/6d9fcefd-dc07-4280-b1b0-f2cee3a69639)

---
## Tasks
- [ ] Create alerts using the `<va-alert/>` component

## Acceptance Criteria
- [ ] All 3 alerts should render based on use case
- [ ] Alerts should match the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141469738/simulate/sitemap?mode=i)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
@craigwheeler FYI we added the alert to the prototype ([view it here!](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142029940/simulate/sitemap?mode=i)). We're gonna sync with the sitewide content team this afternoon to get the content reviewed
