### ISSUE TITLE
[AWS] Service Account credentials for Domo's CloudWatch Connector

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#29641]
## Description
I'm attempting to pull Cloudwatch data into Domo using Domo's CloudWatch connector and getting a permissions error when providing my AWS Access & Secret Key. Demian suggested using a Service Account for these purposes.
https://domohelp.domo.com/hc/en-us/articles/360043433093-Amazon-CloudWatch-Connector
![image](https://user-images.githubusercontent.com/72466113/135670140-753f3ddd-ab17-4089-b3cb-beee03fd5172.png)

## Background/context 
Attempting to connect to CloudWatch using this Domo connector: https://www.domo.com/appstore/connector/amazon-cloudwatch-connector/overview
to complete this ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28852

## Technical notes
I'm getting the error: User: arn:aws-us-gov:iam::008577686731:user/Ryan.Johnson is not authorized to perform: cloudwatch:DescribeAlarmsForMetric with an explicit deny (Service: AmazonCloudWatch; Status Code: 403; Error Code: AccessDenied; Request ID: 866d49f4-bf69-4248-b1e5-cf51c030eaef)

---
## Tasks
- [x] Investigate what policies the Domo connector requires
- [x] Creation of an AWS service account that has access to AWS CloudWatch metrics (per Demian's suggestion over Slack - https://dsva.slack.com/archives/CBU0KDSB1/p1630692876304200?thread_ts=1630692097.301600&cid=CBU0KDSB1.
- [x] Apply the correct policy to the SA created above
- [x] Provide Access key ID & Secret Access key for Cloudwatch -> Domo Connector

## Acceptance Criteria 
- [ ] AWS Service Account creds allow successful retrieval of CloudWatch metrics in Domo connector.

**Comment by rwilliams-oddball** [comment]
Feature not available in Domo.
