### ISSUE TITLE
[Design] Notification Prefs: Update mocks and FE documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29646]
## Background
We need to make some updates to the mocks and FE documentation due to the removal of the Covid/stay information notification item.

## Tasks
The following updates are needed to mocks:
- [x] Remove covid/stay informed notification group and item from all views 
- [x] Update alert messaging/copy in FE documentation and mocks to remove references to email address (irrelevant for mvp) and how we'll use it to contact them
- [x] Update mocks with conditional examples as noted in [test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md)
- [x] Update mocks and FE documentation with new designs for changes to profile personal contact information section (remove references to email?) and link in FE documentation

**Comment by andaleliz** [comment]
All mocks-n-docs updated
