### ISSUE TITLE
[Offboarding Requests] Disable unfurl in Slack when new request is created

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#29659]
## Description
The Github issue links sent by https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/slackRemovalRequest.yml are being unfurled which creates too much clutter in the channel.

## Background/context 

- GitHub workflow [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/slackRemovalRequest.yml)
- Slack action [here](https://github.com/department-of-veterans-affairs/vsp-github-actions/tree/main/slack-socket)
- Internal docs [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595275/Slack+Notifications+from+Github+Actions)

---
## Tasks
- [ ] Re-configure the workflow and action for sending Slack notifications to the Slack admins

## Acceptance Criteria 
- [ ] Slack removal request GHA uses our standard action for sending Slack requests
- [ ] Links are not unfurled when DSVA Slack removal requests are submitted

## Example 
This is what is seen in #vsp-slack-user-management when a `/request` is sent (Cory Trimm shared this):
![image (2)](https://user-images.githubusercontent.com/10993987/160487592-40d896a6-d58d-4e26-91cb-d4df09cc3156.png)

**Comment by jhouse-solvd** [comment]
Assigning to Rebecca. 

@rmtolmach - If you can take a look and find out what's needed here and help determine the level of effort to complete it, that would be awesome!

**Comment by rmtolmach** [comment]
_Summary: Fixing this would require a non-trivial amount of work._

The offboarding requests come to our internal Slack channel by way of [GitHub's Slack integration](https://github.com/integrations/slack#readme). You can see what we're subscribed to by using the `/github` command in Slack, like this: 

`/github subscribe list features`
**GitHub APP**
> Subscribed to the following repository
> [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team)
> `issues`, `+label:'Offboarding'`
[Learn More](https://github.com/integrations/slack#configuration)

I was hoping this would be a simple setting change, but nope! I found these two issues where people are asking for the same thing:
https://github.com/integrations/slack/issues/162
https://github.com/integrations/slack/issues/564

As a workaround, I tried fixing this by changing my preferences in Slack to uncheck the last option, but the GitHub App's settings overrides Slack's settings.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/10993987/160462344-c84c0d95-756f-49cc-9583-510f7bd35b15.png">
From the [Slack docs](https://slack.com/help/articles/204399343-Share-links-and-set-preview-preferences#turn-off-link-previews):
> Note: For some apps and integrations, link previews won't be disabled when the options above are unchecked.

One option might be to disable the GitHub app in our channel and create a new workflow/GH Action instead. The action could send a message to the internal channel notifying us that there is a new offboarding request. 

Or, we could wait for GitHub to fix this. (The issue tracking this has been open for > 4 years, so it doesn't seem like a priority 😑 )

**Comment by ph-One** [comment]
What is seen in Slack is _not_ a preview, but the actual body of the message being sent (which we cannot adjust, from my understanding). As we do not get a tremendous amount of these requests, I think it is fine as-is, and if the noise picks up, we can drop these into another channel. I find that having dedicated channels for notifications is better than using the team's shared channel anyhow.

**Comment by rmtolmach** [comment]
ah, I got this wrong. https://github.com/department-of-veterans-affairs/va.gov-team/issues/29658 was closed as a duplicate of this Issue. https://github.com/department-of-veterans-affairs/va.gov-team/issues/29658 makes it clear that the ask is for disabling the unfurling of the message that is received by the Slack admins to remove a user from Slack. While that's _part of_ the offboarding request, it's different from the message we get from github in our internal channel.

I am going to remove the screenshot and change to description to reflect the original ask.

**Comment by rmtolmach** [comment]
Fixed by #39261 
Verifying:
The payload includes the correct parameters. [Link to Action](https://github.com/department-of-veterans-affairs/va.gov-team/runs/5737708285?check_suite_focus=true)
```
DEBUG: Payload {"channel":"vsp-slack-user-management","text":"Hello! Please remove Homer Simpson from DSVA Slack based on issue URL https://github.com/department-of-veterans-affairs/va.gov-team/issues/39221","icon_emoji":":wave:","unfurl_links":"false","unfurl_media":"false"}
```
Cory Trimm validated that the message being sent is no longer unfurled 🎉  (it's the Homer Simpson message at the bottom)
![Image from iOS](https://user-images.githubusercontent.com/10993987/160626225-c2123606-7f31-4919-8c47-2926497dcd0d.png)
