### ISSUE TITLE
Mobile VHA traveling clinic design iteration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29667]
## Issue Description
Following the discovery effort, it was recommended that only MMUs acting as traveling clinics should have dedicated VAMC pages. The information needed for Veterans is slightly different for this type of facility compared to standard brick and mortar locations and the design needs to be adapted for this purpose.

## Out of scope
- emergency response mobile units
- events such as immunization clinics

## Tasks
Based on feedback to date: 
- [ ] Create mobile first design specs for mobile health clinics with a routine schedule of service locations, which includes
      - Dates/schedule
      - Location including street address, city and state)
      - Parking info
      - Transportation info
- [ ] Call out important editorial considerations for collaboration with CMS

## Acceptance Criteria
- [ ] Mobile first design spec ready for review with stakeholders

**Comment by lildziner** [comment]
Here are the [design specs for the Mobile clinic facility pages](https://preview.uxpin.com/20fd05cf8e86ce628f0c813166424d0a6ca38bfd#/pages/142311876) with a new "Schedule" option that can replace the "Hours" section. 

Here are file format options for a new mobile clinic image placeholder

<details>
<summary>jpg</summary>
![MMU-placeholder.jpg](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/a489c608-b7b6-4d0b-a98d-cbf00ef943a3)
</details>

<details>
<summary>png</summary>
![MMU-placeholder.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/ef3f054d-e775-4f64-a26b-86d29aa14d45)
</details>

<details>
<summary>svg</summary>
![MMU-placeholder.svg](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/46e6e49c-aa0c-46e0-bfb3-f3cdc8cae51a)
</details>

**Comment by lildziner** [comment]
Making a note that we will want to address Mikki's concerns and try [suggestions listed under V4](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29332#issuecomment-921302944) in future iterations as we evolve this page, talk to Veterans and stakeholders.
