### ISSUE TITLE
Add Loki CLI access to SOCKS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#29663]
## Description
As a security engineer I need to be able to run cli commands against all Loki instances (such as http://loki-staging.vfs.va.gov/). The reason for this requirement is that I run log queries today within cloudwatch for fraud waste and abuse when an incident occurs. We also run daily extracts in order to detect fraud related incidents. Switching to Loki I will need the same ability to create csv reports that are in most cases longer than 5k results (cap for UI based query exports). This ticket is a request to allow the Loki instances to be accessed from the SOCKS proxy, which during current testing is not functioning. 

## Technical notes
Instructions on how to use logcli can be found here: https://grafana.com/docs/loki/latest/getting-started/logcli/
Key point: you need to set the LOKI_ADDR environment variable when using logcli.
---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
I should be able to perform two actions after this ticket for all environments, including Prod:

1.  Run `curl -i http://lok-staging.vfs.va.gov/loki/api/v1/labels` (or its equivalent for the version we are running) and I should see a set of labels.
2. Run `logcli labels job` (this uses the logcli binary provided by Loki and makes a call to get the labels). This should show all the labels from Loki

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by joeniquette** [comment]
Slack thread: https://github.com/department-of-veterans-affairs/va.gov-team/issues/29663
