### ISSUE TITLE
Platform Orientation - Discovery research around VFS challenges

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29671]
## Background
The revised Platform Orientation process was launched in March of 2021. Below are some observations, assumptions and/or thoughts from the Governance team on the challenges of the Platform Orientation process from the last 6+ months.

Thoughts, ideas, assumptions from Governance team:
- Lots of information - overwhelming.
- Have general/static information available in a video so orientation session can be more conversation-focused
- move away from the slide deck as source of truth
- TLDR Approach - what is most essential that VFS teams know. 5 things you need to know.
- reorganize content - start with definition of terms, main takeaways
- have clear action items for people who attend (here's what you need to know, here's what you're going to do next)
- "I know I can always go back to Platform Website, so I don't pay attention now"
- Research with VFS team members who have completed Platform Orientation within the last 6 months
- Transfer vets.gov-write responsibility to another Platform team
- Create a trigger for Platform teams to know when VFS Platform Orientation ticket is ready for Platform action
- Identify overlaps and gaps between the different orientation sessions
- "Platform Orientation" as a name could be confusing; test this with new hires

## Problem Statement 

VFS teams are asked to partake in Platform Orientation so that they may learn of Platform's processes, tools and expectations before beginning to support their VA.gov product. While the Governance team has made some assumptions about the challenges VFS teams face with Platform Orientation, the team would like to partake in a discovery research session with new VFS team members so that a) our assumptions can be validated and/or b) new, larger problems can be found and prioritized.

How might we conduct discovery research to better understand the VFS pain points and challenges with Platform Orientation so that we address the larger impact concerns first?

#### Original intent of epic
The content in the General Orientation slide deck will be the first to be extracted from the deck and converted to pages on Platform Website, then made accessible via the Getting Started page. In this ticket we need to:
- Refine and/or add missing content identified in the research review findings
- Identify additional content listed in the inventory that applied to all new VFS team members and ensure it's covered in General Orientation.
- Determine what new Platform Website pages will need to be created
- Determine what other changes will have a positive impact on new team members
- Determine what changes will minimize complexity and challenges for governance team and other Platform Orientation hosts
---
## Hypothesis or Bet
If we complete cohesive discovery research then we'll know which high-level problems to prioritize.
(Post-discovery initiative) If we address the high-level problems VFS teams face at Platform Orientation, then we'll improve the orientation process, allowing VFS teams on onboard quicker, allowing them to easily find Platform guidance, and will not slow them down when it comes to supporting the development of their products. 

## We will know we're done when... ("Definition of Done")

- [x] We have a list of VFS pain points and/or challenges with the Platform Orientation process.
- [x] We understand how those pain points and/or challenges currently impact Platform and/or VFS teams
- [x] We have a proposed plan of which pain points and/or challenges to prioritize

## Artifacts
*List any links to guidance/documents/sketches/flows etc. created throughout the initiative* 
  * [Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2425978881/Research+Plan+Platform+Orientation+Discovery)
  * Conversation guides: [VFS Teams](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2432172044/Conversation+Guide+VFS+Team+members) | [Platform Orientation Hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2437546120/Conversation+Guide+Orientation+hosts)
  * [Current User Flow](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1668529634868/a5b8ecb4ac2acabc00f51215ad4ed5521941ec0a?sender=u792eff8ef82f499a192a4934)
  * Alignment Personas (noticeable differences across practice areas did not emerge in this research - decided against persona work 12/22)
  * Interview Notes ([VFS Teams](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1669918414107/1e6e8f97f14f171dc80ca22bee3f207cb0bb9b8b?sender=u792eff8ef82f499a192a4934) | [Orientation Hosts](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1670425669150/be8aa9927d912e89982b94e9129e5fde79d3d71e?sender=u792eff8ef82f499a192a4934))
  * Research synthesis - Affinity Maps ([VFS Teams](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1671687851786/cdf61904437efd5cd7b04deb6f16d6f99a30c1a0?sender=u792eff8ef82f499a192a4934) | [Orientation Hosts](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1671812351098/401c6e6f28b678a9eeb5e72811f4b781290dd8d6?sender=u792eff8ef82f499a192a4934))
  * Solutions for research findings ([Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1673040569339/1436de8054f492e2aac4873e3b8af663068a372d?sender=u792eff8ef82f499a192a4934))
  * [Research Findings Document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2470543386/Research+Findings+Platform+Orientation+Discovery+Research)
  * [Research Readout](https://docs.google.com/presentation/d/1tM-gwxYLWlZ7feXUIH2moK-8_IjTVDqvsaJZIrT1hIk) Presentation to OCTO-DE on 1/17/22

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
November-December 2022

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
@raywangoctova this initiative is closed. All findings and artifacts created for this effort are linked above under Artifacts. I have an action item still to create 2 new initiatives to align with our top 2 recommendations: 1) introduce asynch options for orientation sessions and 2) break down the Platform Orientation template into smaller pieces or "chunks". I will update this comment and link the new initiatives here once drafted. Please let me know if you have any other questions.
