### ISSUE TITLE
[MCP] 'Notice of rights and responsibilities' modal 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29677]
## Issue Description
Our stakeholders requested that we include the 'Notice of rights and responsibilities' content that's attached to the back of a Veteran Patient Statement (VPS).

A balance's detail page has a link below the 'Download statements' section that reads 'Notice of rights and responsibilities'. Clicking that will open a modal displaying that content. Due to the amount of content, we'll follow the Privacy Act Statement modal's pattern to allow scroll at a max height ([ex. the form 40-10007 Privacy Act Statement](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction))

Additional resources:
- [The content with corresponding heading levels in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/design/notice-of-rights-responsibilities-content.md)
- [Rough outline of what the modal would look like (unable to simulate scrolling within the modal)](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141491503/simulate/sitemap?mode=i)

---
## Tasks
- [ ] The balance details page's 'Notice of rights and responsibilities' link opens a modal with the provided content 
- [ ] The height and scrolling interaction matches the example Privacy Act Statement 

## Acceptance Criteria
- [ ] MCP's UI has been updated to include the modal 
- [ ] A designer has reviewed the UI in staging

**Comment by craigwheeler** [comment]
duplicate of issue [29678](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29678) closing
