### ISSUE TITLE
Design the new Getting Started page on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29670]
## Issue Description
Platform and OCTO-DE agreed that orientation materials belong under the Getting Started section of Platform Website. In order to incorporate orientation materials seamlessly, the Getting Started page will need to be redesigned. This ticket will determine where/how to incorporate orientation materials/docs into the existing Getting Started section of the Platform Website. 

---
## Tasks
- [x] Create design mockups of the MVP Orientation Materials page to be located in the Getting Started section of the Platform Website
- [x] Get feedback on the page design mockup from Content & IA team
- [x] Revise design mockups

## Acceptance Criteria
- [x] Orientation docs posted to the new Orientation Materials page are VFS customer-facing (not internal docs)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@rebekahickey @jchasia-adhoc @jonathanjnelson FYI

I left this ticket pretty blank. Would you share what the anticipated output of this work would be? I think this will help me with the other pieces of work for this initiative. Thanks!

**Comment by rebekahickey** [comment]
I shared the first draft of the design mockup for the MVP Orientation Materials page with Gretchen today. I have a couple of revisions to make and then will post it here and in the platform-orientation-team slack channel for the group's feedback.

**Comment by shiragoodman** [comment]
thanks @rebekahickey !

**Comment by rebekahickey** [comment]
Design mockups attached. I prefer the first option with all materials in a single list, but also attached a version that shows the materials grouped by area (using the Platform website's IA).  In both versions, there is a spot for intro text to provide context for VFS teams/team members followed by links to current orientation materials (in their existing formats - Google Slides, Docs, etc.).![Platform Orientation MVP.png](https://images.zenhubusercontent.com/605ba3150bd73661a1d080ff/da0f24ed-8704-4eaf-b3d9-c21b67bfc7d9)![Platform Orientation MVP - Grouped List.png](https://images.zenhubusercontent.com/605ba3150bd73661a1d080ff/288eec9e-6bb9-4471-985d-c52a7d4b702c)

**Comment by shiragoodman** [comment]
Intro text: "Below are the materials used in the various orientation meetings hosted by Platform for VA.gov."

@rebekahickey not sure what else we wanted to covey in this intro text. Did you have anything specific?

**Comment by rebekahickey** [comment]
9/24/21 - Intro text added to design mockup (attached) and draft Orientation page in Confluence and shared in #platform-orientation-team.  

9/27/21 - Final page reviewed & approved for go live by Naomi & Peggy: https://dsva.slack.com/archives/C02CFJDKBFT/p1632506347036100.  

9/27/21 - Orientation page published to Platform website: https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
