### ISSUE TITLE
Implement Calendly as scheduling tool in the Collaboration Cycle for staging and midpoint

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29686]
## Issue Description
Platform will implement the use of Calendly, a scheduling tool, into the Collaboration Cycle to make scheduling Collaboration Cycle Staging and Midpoint Reviews much simpler. This ticket will impact the following VFS-facing documents/resources:

- Staging Review touchpoint
- Staging Review gh template
- Midpoint Review touchpoint
- Midpoint Review gh template
- Platform Collaboration Cycle calendar
- [Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-us.1764524036.html)

Internal resources:

- [How to schedule and respond to CC requests ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748828191/CC+-+How+to+Schedule+and+Respond+to+Collab+Cycle+requests)for:
   - Staging Review
   - Midpoint Review

Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28115 and https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31577

Staging Review calendar in Calendly: https://calendly.com/collaboration-cycle/staging-review
Design Intent/Midpoint Review calendar in Calendy: https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review

---
## Tasks
- [x] Update GH templates (Midpoint & Staging)
- [x] Update internal documentation and instructions (Moderator Responsibility for Midpoint & Staging)
- [x] Update the Platform Website documentation and calendars (Resources, Platform Collaboration Cycle Calendar)
- [x] Update the midpoint and staging Calendly settings 
- [x] Verify that the Midpoint, Staging and Design Intent Calendly settings are aligned/consistent
- [ ] Review Research REadout and make the recommended changes to all 3 touchpoints

## Acceptance Criteria
- [x] The GH templates have been updated and it is clear to users how to schedule the review
- [x] VFS PMs are able to schedule the review and add their attendees
- [x] The Calendly invite has the correct title and GH link in the body
- [x] The Platform website has updated calendars and resources
- [x] Our internal documentation has been updated with new instructions on how to schedule a meeting
- [x] Product support can add their attendees to the Calendly meeting
- [ ] We have communicated the Calendly change to VFS teams thru the Collaboration Cycle Change history, ToT and thru #vfs-all-teams channel
- [ ] Remove the REVIEW BLOCKS and STAGING BLOCKS from calendar once we go live

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@shiragoodman I believe we are all set to launch the pilot for staging. When you are ready to announce it let me know and I can push all the changes.
[Change history](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1936424969/Copy+of+Change+history)
[Staging review GH ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/31290)
[Scheduling staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1934196812/Allison+Copy+of+Staging+Review)
[Resources](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1936425018/Copy+of+Resources)
[Platform Collaboration Calendars](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1936425003/Copy+of+Platform+Collaboration+Calendars)
