### ISSUE TITLE
[VAMC] Publish Systems in VISN-1 to Dual-State [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#29694]
## STORY
As a web user I need to be able to see my system in a web format, so I can complete my training and then fix how each page appears in a published state. 

## Resources
[Tugboat](https://tugboat.vfs.va.gov/5ffe2f4dfa1ca136135134f6)
[Site Page Checklist](https://drive.google.com/drive/folders/1v0CGhpx7BM2tWbZx7zNY_ZkQ-Y9abFg0)

## TASKS
Only after systems has been preped in Tugboate (Dependency)
- [x] In production, publish all nodes and pages that are in Draft.
** Publishing should only be processed on Tuesday-Wednesday-Thursday early in the morning, and prior to daily software release. 
** To prevent overlap, please time release of content between 15 after and 15 til the hour as to avoid conflict with hourly content release.
1. Confirm total number of pages in Draft
2. Check number of pages that have been archived, make sure only the propper pages are archvied.
3. Confirm what nodes have already been published (i.e. Covid-19 SHS/FHS)
4. Move any incorrect Archives to Draft
5. Using "Content>Bulk edit content"  
6. Select the correct system from "Section" drop down
7. Select "Draft" from Moderation State	
8. Validate numbers correspond with above.
9. Select check box next to (Select/deselect all results in this view)
10.Chose "Publish Latest Revision" from action drop down
11. click "Apply to selected items"
12. Wait for pages to confirm.  Select "Confirm" 
13. Open Jenkins and view 
**Systems included**
- [x] VA Bedford health care
- [x] VA Boston health care
- [x] VA Central Western Massachusetts health care
- [x] VA Connecticut health care
- [x] VA Maine health care
- [x] VA Manchester health care
- [x] VA Providence health care
- [x] VA White River health care
_
- [x] Update Operational Status to include the following Banner"
1. Informational  **Dismissable**
- title: "Website coming soon - not the official VA [System Name] health care website"
- body: "We hope you enjoy your look at our new website. This is not our official website at this time, but will be soon. To continue your health care journey in the VA [System Name] Healthcare System, please return to our official [System Name website (in hyperlink to legacy site)]"

## Acceptance criteria

- [x] System is published and avialable under "https://www.va.gov/system-name-health-care/
- [x] Informational Banner is visible

**Comment by ltrombley** [comment]
Task #29694  - Publish Systems in VISN-1 to Dual-State [VAMC] - is Complete and moved to Validate.
