### ISSUE TITLE
[FE] Temporarily Disable Update Information page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29690]
## Description

Comment out the Update page, save it for it later. 

[Context](https://dsva.slack.com/archives/C022AC2STBM/p1631039282193000)

## Tasks

- [ ] Remove the page for the flow. 
- [ ] Update e2e tests

## Acceptance Criteria

- [ ] Deployed to staging.
- [ ] Product team has signed off on the  feature
