### ISSUE TITLE
Find a VA Form: Mock up accessible PDF alert

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29704]
## Issue Description
We will implement a modal that users must acknowledge before downloading a PDF form.  The workflow would be as follows:
		

1. I search for a form
2.  I get search results
3. I find the form I'm searching for
4.  I want the PDF vs. online tool
5.  I click Download PDF
6. The modal is triggered - see design system https://design.va.gov/storybook/?path=/docs/components-modal--default
7.  Modal title says "**Adobe Reader DC Required**"  (final copy TBD by Content team)
8.  Modal text says "All PDF forms do not function fully in a web browser or other PDF viewer.  Please download the form and use Adobe Acrobat Reader DC to fill out. For specific instructions about working with PDFs, [please read our Resources and Support article](https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form)"  (final copy TBD by Content team)
9. There are three options below that:
   -   [Get Adobe Reader](https://get.adobe.com/reader/)
   -  Download VA Form 10-10EZ
   -  Cancel button to close the modal

## Tasks
- [x] Mock up modal as described above
- [x] Provide Sketch link to mockup in comment in this ticket

## Acceptance Criteria
- [x] We will have modal mockup that we can use for context when requesting content tweaks and for Zach to follow when building
---

**Comment by callen2563** [comment]
![FAF_PDF_Modal_mobile](https://user-images.githubusercontent.com/68560244/133144945-1e2d305e-400a-495b-9521-2b6abedcd7c7.png)
@MarciMcGuireGCIO I had to shorten the FPO copy above the bullets so it would fit better. Let me know if you'd like something else as a placeholder.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 thank you!  This looks very nice.   Would you mind making a few minor tweaks?  

- Replace the bullet list with the three options below (please don't laugh at my janky mockup). 

- First link would go to https://get.adobe.com/reader/

- Action link goes to https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf

- Cancel button closes the modal.

![image](https://user-images.githubusercontent.com/73354907/133153233-7f2abb58-e37c-4aec-8c29-0fabbf463fcc.png)

**Comment by callen2563** [comment]
You got it! np

**Comment by callen2563** [comment]
![FAF_PDF_Modal_desktop](https://user-images.githubusercontent.com/68560244/133317774-f806cc7b-e8bd-49a8-a545-1694e7cb9e49.png)

**Comment by zacharymorel** [comment]
@callen2563 Is the "Cancel" button a close button of the modal, correct?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Cassandra's not in yet, but you are correct!

**Comment by callen2563** [comment]
@zacharymorel @MarciMcGuireGCIO So I thought that cancel button was odd but that is what was in the style guide. I think we should change that to close. What do you all think?

**Comment by zacharymorel** [comment]
I'm on board!

**Comment by MarciMcGuireGCIO** [comment]
So funny... I was thinking about that this morning.  Let's you and I attend the next design council meeting and get some feedback.  It looks odd to me too; like it's out of balance. But you're right- it's in the design system.  But I bet that alert design preceded action links.

**Comment by MarciMcGuireGCIO** [comment]
The cancel button also seems redundant because there is X to close, but that may be an accessibility consideration.  When I met with Ryan and Angela, that was part the conceptual design. I wonder if the cancel button can be there but only detected by screen readers?

**Comment by callen2563** [comment]
![Modal_desktop](https://user-images.githubusercontent.com/68560244/134392860-7bd260f9-4b15-4621-ad26-add3ddda8a0c.png)
I have updated the button but I agree I believe the close button is a good idea since the x in the corner might not be visible for low vision users.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @callen2563 !  Ryan and Angela specifically mentioned it would be a "Cancel" button but @zacharymorel let's go ahead and work on getting this on Staging next sprint so that Angela can review with a screen reader and Ryan & the Content team can also have a look.

**Comment by MarciMcGuireGCIO** [comment]
@cassandra & @zacharymorel - I attended Platform office hours earlier, and here's the feedback on the modal:  

- In the paragraph, the messaging should say download Adobe Reader first and download the PDF second - Peggy also said Content can probably trim the verbiage down, so I'll create a new request for that.
-  Since there is no Adobe Reader that allows for filling 99% of these forms on mobile, we probably shouldn't  display the Adobe download link for mobile (my own note - perhaps we instead show an alternate message fill electronically on Mac or PC?)
- It might require a little bit more user education (I explained that is what the R&S article link is intended for)
- We may need to add a cookie so it doesn't show up every single time
- Sketch file for modals show a Cancel button (not close)

**Comment by MarciMcGuireGCIO** [comment]
I'm reopening, but @callen2563 let's not make any changes until we get some recommendations on the content.  @zacharymorel I think it's still good to get this on Staging with the button saying "Cancel" so that Angela can give it a test drive.

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO Can we try this text for the modal and see if it's too long?:

### Download this PDF form and use Acrobat Reader to fill it out

First, download this PDF to your desktop or laptop. Then use Adobe Acrobat Reader DC to open and fill out the form. If you try to open the PDF on a mobile device or fill it out in your browser, you may have trouble.

**Want to just print the form and fill out a paper copy?**
Simply open the PDF in your browser and print it from there. You don’t need to download the PDF.

[Learn more about how to download and open a PDF] 
[Get Adobe Acrobat Reader DC]
[Download VA Form 10-10EZ]

**Comment by MarciMcGuireGCIO** [comment]
Hi @bethpottsVADEPO, thanks! I don't know if it's yet common knowledge, but Zach and I are moving over to work on the Authenticated side as of today.  

We'll do a transfer with the team that takes over Find a VA Form so they can take this and run with it.
