### ISSUE TITLE
Rx Shipment Tracking - (663) Puget Sound HCS

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29710]
- [x] Confirm facility POC (Francesca Wilder)

- [x] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits)

- [x] Send Email with Checklist

- [x] Advertise Upcoming Feature

- [x] Confirm Go-Live Date [11/01/2021]

- [x] Configure/Deploy

**Comment by pcshah1026** [comment]
went live on 11/01
