### ISSUE TITLE
Rename BAM2 team in GitHub

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29713]
## Issue Description

Since the BAM2 team has been renamed to the VSA Debt Team. The frontend team in [GitHub](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-frontend/teams) should be renamed from `vsa-bam-2-frontend` -> `vsa-debt-frontend ` for consistency

---
## Tasks
- [ ] [GitHub](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-frontend/teams) team should be renamed from `vsa-bam-2-frontend` -> `vsa-debt-frontend `
- [ ] [CODEOWNERS](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS) file should be updated to reflect the change

## Acceptance Criteria
- [ ] [GitHub](https://github.com/orgs/department-of-veterans-affairs/teams/vsa-frontend/teams) team should be renamed from `vsa-bam-2-frontend` -> `vsa-debt-frontend `
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
