### ISSUE TITLE
Rx Shipment Tracking - (590) Hampton, VA [Go-Live:  03/21/22]

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29719]
**NOTE:**  This facility is part of VISN 6 funding (Dr. Major).

- [x] Confirm facility POC

- [x] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits)

- [x] Advertise Upcoming Feature

- [x] Confirm Go-Live Date -- **03/21/2022**

- [ ] Configure/Deploy

**Comment by pcshah1026** [comment]
Site is live
