### ISSUE TITLE
Bug: Auth session does not always hit v1

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#29714]
## Issue Description
Trevor mentioned that in vets-website sometimes the FE hits the `sessions/idme/new` instead of the `v1/sessions/idme/new` endpoint when logging in/out and refreshing the page [original thread here](https://dsva.slack.com/archives/C019S3NSSAD/p1631056139007100).  He believes there might be a weird state where the Flipper values don't return immediately causing this issue.

Because the v0 sessions controller is being removed as well as all SSO flipper features this is a good opportunity to refactor the FE.

---
## Tasks
- [x] Removes Flipper features for SSO (temp)
- [x] Remove all instances of v0 for Auth
- [x] Modify utility & component files to allow only v1 sessions endpoints to be hit
- [x] Update unit tests (remove v0 unit tests)

## Acceptance Criteria
- [x] All auth endpoints hit the v1 sessions controller endpoint
- [x] All unit tests work as required
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
E2E Tests are failing because of the current implementation.  By removing the ssoeInbound feature flag in (VSP Identity) teams code, the SingleSignOnModal is popping up in the E2E tests because mocked users have the `session: { ssoe: true }` in their JSON.

I reached out to Testing Tools team to figure out how we want to handle this and gave them 2 options ([original thread here](https://dsva.slack.com/archives/C01CHAY3ULR/p1631719557146700))

Option 1 - We refactor a lot of the E2E tests, might take a longer time, larger PR process to review all the tests. (* Ideally this is what we want to get to)
Option 2 - We disable the SSOInfoModal just for Cypress tests, Smaller PR process, a little faster to get done (* This would just be temporary until the larger refactor effort)

Ideally we want to go with Option 1 but we are sort of blocked until we can figure out what the Testing Tools team wants to do as they were initially talking about refactoring all the spec files.

**Comment by nsoutouras** [comment]
Blocked - Waiting on TTT to respond

**Comment by nsoutouras** [comment]
Blocked by: https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/29865

**Comment by AGarcia-Clarity** [comment]
@nsoutouras This can be closed pending your approval
