### ISSUE TITLE
[FE] Put Update page  behind a feature flip. 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29712]
## Description

We short term fixed the removal of the update page. But that should be behind a feature flip to avoid technical debt and code rot. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create feature flip
- [x] Reenable the tests that include it
- [x] Create user tests
- [x] Create e2e tests
- [x] Update relevant documentations

## Acceptance Criteria

> when is the ticket done

- [x] Make sure it's disabled by default
- [ ] Deployed to staging.
- [ ] Deployed to production.
- [ ] Product team has signed off on the  feature
