### ISSUE TITLE
Rx Shipment Tracking - (659) Salisbury, NC

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29724]
**NOTE:**  This facility is part of VISN 6 funding (Dr. Major).

- [x] Confirm facility POC

- [x] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits)

- [x] Advertise Upcoming Feature

- [x] Confirm Go-Live Date

- [x] Configure/Deploy

**Comment by lindsay-insco** [comment]
Go-Live date: 10/25/2021

**Comment by pcshah1026** [comment]
went live on 11/22.
