### ISSUE TITLE
Publish VA.gov Overview video in Platform Orientation materials

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29725]
## Issue Description
In [ticket #31543](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31543), OCTO-DE Platform lead Rachael Roueche recorded a VA.gov overview video to be included in Platform Orientation materials. 

---
## Tasks
- [x] Transfer video to Platform YouTube channel
- [x] Ensure the video is accessible (confirm with Noah Gelman)
   - [x] Do we need to include a transcription? Yes. Nvda is free.
   - [x] Determine where transcription should live.
 - [x] Follow up with #vsp-confluence channel wrt how to share the transcription in Confluence or in Platform Website
 - if confluence, is it okay to link to the page from Platform Website?
- [x] Add video and contextual language to Platform Website/ Getting Started/ Platform Orientation page
   - Embed video and also include link to view on YouTube
- [x] Add checklist item to watch video in Platform Orientation template

## Acceptance Criteria
- [x] VA.gov Overview video is watched by new VFS team members
- [x] VFS team members are familiar with VA.gov before they begin developing their VA.gov products
- [x] The VA.gov Overview video transcription is available to VFS team members

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by seanasewell** [comment]
@allison0034 I uploaded the video to the Youtube channel. Here is the embed link.

<iframe width="560" height="315" src="https://www.youtube.com/embed/0cc-VdfI4Q8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by seanasewell** [comment]
@shiragoodman The videos uploaded to the Youtube channel thus far do not have transcripts. I asked @noahgelman about whether or not it is needed and his response was that he didn't think so but it was a bit outside his authority. Is there someone I can approach about this to ensure whether or not we need to add it?

**Comment by shiragoodman** [comment]
@seanasewell thank you! Since this isn't Veteran-facing, it's only VFS-facing, we don't have to enforce the same level of accessibility. Can you move forward with publishing? I'll put it on my agenda today to discuss with Rachael at our 1:1.

**Comment by allison0034** [comment]
The link to the video and page are updated on Platform website

**Comment by briandeconinck** [comment]
[Draft transcript](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2049245421/Brian+-+Transcript+of+VA.gov+Overview+video) generated. Still needs to be reviewed one more time with the video to decide if any additional descriptions of the visuals are needed.

**Comment by shiragoodman** [comment]
thanks @briandeconinck !I made 1 small comment re the spelling of Rachael's name. Also any idea where we can publish this? Does YouTube allow you to add a transcript as part of the page?

@chaseakirby could you ask someone to PR this for Brian?

**Comment by briandeconinck** [comment]
@shiragoodman YouTube generates a timed transcript from its auto-captions, so there's already a medium-low-quality transcript available on YouTube for the video. (Steps to view that transcript: From the video, click the 3 horizontal dots next to the like/dislike/share/save buttons. Then select "Open Transcript.")

I don't know YouTube super well, but I believe that's the only place specifically designated for a transcript. Whoever owns the video on YouTube should be able to upload this copy of the transcript to replace the auto-generated version. I've also seen people add transcripts into the video description to make them more visible.

But since the video will be embedded on the platform website, I would probably recommend also publishing the transcript there, with a link to that page alongside the embedded video. That's maybe the most straightforward option and is a fairly common pattern (video + "View transcript" link). It's also a lot easier to follow than "Go to the video on YouTube, then find these mysterious three dots."

**Comment by shiragoodman** [comment]
@briandeconinck thank you! that's super helpful information.

Currently, the video is NOT embedded into Platform Website. There are 2 ways that VFS teams can access it from Platform documentation:
1. via the Platform Orientation gh template
2. via the Platform Orientation page on Platform Website

both places link out to YouTube, so I think just updating the transcript within YouTube should suffice. 

I can invite you to collaborate in the Platform YouTube channel and you should hopefully be able to make the changes to the transcript. If you don't receive an invite, let me know.

**Comment by briandeconinck** [comment]
Per the discussion above, the video transcript is now on YouTube, viewable when a user brings up the built-in transcript functionality. And as an added benefit, the captions are better now too (no more "via.gov" instead of va.gov).

**Comment by shiragoodman** [comment]
thank you @briandeconinck !!
