### ISSUE TITLE
Create additional redirects mapping for MHV

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#29729]
## Issue Description
The MHV team requested the ability to have a custom redirect back to the MHV site [original thread here](https://dsva.slack.com/archives/CSFV4QTKN/p1630590381010100).  

The requested login flow will be the following:
1. User starts on MHV site > Clicks Sign In
2. User is navigated to the VA.gov Sign in page (https://staging.va.gov/sign-in/?application=mhv&to=_pageToRedirectOnMHV_) with query parameters of application being **mhv** and the **to** being the endpoint (i.e. myhealth.va.gov/mhv-portal-web/web/myhealthevet/) and chooses a service provider
3. User authenticates with service provider (ID.me, etc.) SSOe
4. User returns to VA.gov > Custom redirect initiated and authenticates back to MHV.

---
## Tasks
- [x] Add MHV mapping
- [x] Add unit test to test redirect

## Acceptance Criteria
- [x] Verify MHV redirect flow works as intended
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
