### ISSUE TITLE
VA.gov overview and test scenarios

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29723]
## Issue Description
Platform is making an assumption that VFS teams don't know what VA.gov is and how it works prior to general orientation (or in their early days of building on VA.gov). Platform would like to implement a solution where new VFS team members experience VA.gov as a Veteran would by executing scenarios on VA.gov using staging logins. 

In conjunction with this, VFS team members will also be asked to watch a ~4 minute "VA.gov Overview" video that walks through the organizational architecture of VA.gov, including the various hubs. 

This ticket will involve acquiring staging logins for the specific test scenarios. The setup/creation of the login is dependent on the specifications of the scenario. Once the scenarios are created and approved by OCTO, we will need to reach out on #vsp-identity channel to get their support creating the logins.

This ticket will also involve documenting various tasks the new team member can perform, writing instructions for the new team member, and linking/including on Platform Website and/or within the new user orientation gh ticket. 

Adhoc use to have a similar process for their new team members in the early days of VSP. That process was for Vets.gov, and was as follows:

> Explore VA.gov by [trying out tools as a staging user:](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/635f35ad555d0cdac50667ac48c92fef2b719c64/Work%20Practices/Accessing-Staging.md)
> 
> - Figure out how to apply for Health Care.
> - Figure out how to find a VA hospital near you.
> - Figure out how to provide feedback to VA about a college you attended with your Education benefits.
> - Figure out how to change the address VA has on file for you.
> - Figure out the status of your latest Disability Compensation claim.
> 

For this ticket, we can either try to update the Adhoc instructions above (and the scenarios referenced in the github link) or we can come up with new scenarios relevant to the current state of VA.gov.

---
## Tasks
- [ ] Reach out to identity when user scenarios have been documented so that they can create the staging logins.
- [x] Define the scenarios:
   - [x] Healthcare
   - [x] Education
   - [x] Disability
   - [x] MyProfile
   - [x] Facility locator
   - [x] Find a VA Form Search
   - [x] Burials & memorials
   - [x] Records
   - [x] Caregivers
- [ ] high level hub information (VA.gov Overview video)
- [x] sync with Ryan and Rachael on what to include in overview.

## Acceptance Criteria
- [ ] VFS teams have a general understanding of how VA.gov is laid out.
- [ ] VFS teams have a general understanding of the sign-in process.
- [ ] VFS teams have a general understanding of the VA.gov hubs.
- [ ] VFS teams have clear guidance on how to choose and execute a test scenario.
- [ ] Platform is efficiently notified of staging logins that need to be reset.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
