### ISSUE TITLE
Rx Shipment Tracking - (652) Richmond, VA

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29720]
**NOTE:**  This facility is part of VISN 6 funding (Dr. Major).

- [ ] Confirm facility POC

- [ ] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits)

- [ ] Advertise Upcoming Feature

- [ ] Confirm Go-Live Date

- [ ] Configure/Deploy

**Comment by pcshah1026** [comment]
tracking info not available in VistA for Richmond, VA, so they are not able to use the VEText pharmacy feature at this time.
