### ISSUE TITLE
Rx Shipment Tracking - (658) Salem, VA

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#29722]
**NOTE:**  This facility is part of VISN 6 funding (Dr. Major).

- [x] Confirm facility POC

- [x] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits)

- [x] Advertise Upcoming Feature

- [x] Confirm Go-Live Date

- [x] Configure/Deploy

**Comment by lindsay-insco** [comment]
Updated Go-Live : 12/01/21

**Comment by pcshah1026** [comment]
Went live on 12/09
