### ISSUE TITLE
Add monthly enrollment verification link to education landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29734]
## Issue Description
Stakeholder Tammy Hurley asked that we add the following link on the education hub landing page under the "more information and resources" section since monthly verification of enrollment is now required:

[Monthly Enrollment Verification](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp) >
Learn more about the requirement for Post-9/11 GI Bill students to verify enrollment every month, including quick and easy steps for using text message verification.

This needs to be rewritten to fit our voice and style. 

## Tasks
- [ ] Rewrite blurb
- [ ] Share with stakeholder
- [ ] Add to Drupal, review and publish
- [ ] Alert stakeholder that change is live

## Acceptance Criteria
- [ ] New link and blurb are live on the page

**Comment by RLHecht** [comment]
We've gone back to Tammy with using an alert on the Post 9/11 GI Bill page instead of putting a link at the bottom of the education hub landing page. We've also added content to the the WAVE FAQs page. @lunascoop can you please make these edits?

Here are Beth's edits to Tammy's changes that need to be put in:

New requirement to verify your enrollment

If you’re in a non-college degree program and you get Monthly Housing Allowance (MHA) and/or College Fund (“kicker”) payments under the Post-9/11 GI Bill, you must verify your enrollment each month. If you’re at an Institution of Higher Learning, you'll need to start verifying your enrollment for terms that start on or after December 17, 2021. Check back here soon to find out when this new requirement will start for you. [Learn more about verifying your enrollment](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp)

WAVE FAQs
**How do I verify my enrollment?**
**If you receive education benefits under the Montgomery GI Bill (MGIB),** you’ll need to use WAVE to verify your enrollment.
 
**If you receive education benefits under the Post-9/11 GI Bill,** you can verify your enrollment by responding to a monthly text message from us. Or you can call us at 888-442-4551. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. [Find out how to opt in to text message verification](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp)
 
**If you receive education benefits under the Survivors’ and Dependents’ Educational Assistance (DEA) program and you’re enrolled in a non-college degree program,** call us instead at 888-442-4551 to verify your enrollment. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.
 
**You don’t need to verify your enrollment if you receive education benefits under either of these programs:**

- The Veterans’ Educational Assistance Program (VEAP), **or**
- DEA and you’re enrolled in a college degree program

**Comment by lunascoop** [comment]
@RLHecht these pages have been updated and are ready for review.

- How do I verify my enrollment? http://preview-prod.vfs.va.gov/preview?nodeId=16481 (single QA related to GI Bill Wave FAQs)
- Post-9/11 GI Bill Statement of Benefits: http://preview-prod.vfs.va.gov/preview?nodeId=3007 (@bethpottsVADEPO I also have a previous edit to this page where I removed an eBenefits in the screenshot below)

<img width="625" alt="Screen Shot 2021-10-01 at 10 52 37 AM" src="https://user-images.githubusercontent.com/42546515/135641245-b68b49d0-fe22-4030-94ce-b0218ca0ab30.png">

**Comment by RLHecht** [comment]
Thanks @lunascoop I lowercased monthly housing allowance, college fund, and institution of higher learning in the alert but no other changes. @bethpottsVADEPO Let us know if I should send these previews to Tammy or they are OK to publish once you've looked at them.

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht 
I see 2 things to fix:
1/ The info alert is on the wrong page. It should be on the Post-9/11 GI Bill page https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ rather than the Statement of Benefits page.
2/ The text you put on the Statement of Benefits page is old--use the text above that includes Tammy's edits. Here it is again:

**New requirement to verify your enrollment**

If you’re in a non-college degree program and you get Monthly Housing Allowance (MHA) and/or College Fund (“kicker”) payments under the Post-9/11 GI Bill, you must verify your enrollment each month. If you’re at an Institution of Higher Learning, you'll need to start verifying your enrollment for terms that start on or after December 17, 2021. Check back here soon to find out when this new requirement will start for you. [Learn more about verifying your enrollment]

**Comment by RLHecht** [comment]
@bethpottsVADEPO The alert is on the Post 9/11 page. It's node 935.

**Comment by bethpottsVADEPO** [comment]
Can you please remove it from node 3007? That's the Statement of Benefits page.

**Comment by RLHecht** [comment]
I removed it from the other page and updated the content on the Post 9/11 page. Let me know if it looks OK and I'll send it back to Tammy.

**Comment by bethpottsVADEPO** [comment]
Thanks, yes, please send to Tammy.
