### ISSUE TITLE
Implement previous_versions defaults for Lockbox

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#29748]
## Issue Description
As part of automating the Lockbox key rotation, we can set some default options in the Lockbox initializer for previous keys/rotation purposes. 

It looks to be as simple as adding
`Lockbox.default_options = { previous_versions: [ master_key: Settings.lockbox.previous_key ] }`
to the lockbox initializer and then adding a new key to the setting.yml in vets-api and in all envs (devops repo)

---
## Tasks
- [ ] Define default options in the initalizer
- [ ] Add a new key to the setting.yml (vets-api)
- [x] update paramstore keys
- [x] Add a new key to the setting.yml (all envs, devops repo)

**Comment by LindseySaari** [comment]
Devops PR [here](https://github.com/department-of-veterans-affairs/devops/pull/10011)
