### ISSUE TITLE
Remove table from the details page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29747]
## Issue Description
It has been determined that we will not be including a table to display copay charges. As a result the "Your charges and payments" section of the detail page should be replaced with the "Download your statements" section 

![Medical Copays  Veterans Affairs 2021-09-08 13-27-11.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/33a3c611-7644-4f9e-a883-211b524b9cf9)

---
## Tasks
- [ ] Remove the "Your charges and payments" section from the detail page
- [ ] Relocate the "Download your statements" section to the same area

## Acceptance Criteria
- [ ] The "Download your statements" section should replace "Your charges and payments" on the detail page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
