### ISSUE TITLE
[PM] Dependent User Role: Product outline for user role - dependent research

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29752]
## Background
We had a discussion with folks from the Identity team to help support research and scoping of a user role MVP, specifically for a dependent user role on VA.gov. We need to create a brief product outline to capture understanding and share back with that group and stakeholders.

## Tasks
- [ ] Prepare product outline
- [ ] Review with Liz and Tressa
- [ ] Share with Kevin and Identity team stakeholders

**Comment by andaleliz** [comment]
[Here are notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/user-roles/user-roles-discovery-kick-off-notes.md) from that meeting if it's helpful

**Comment by ajakabcin** [comment]
revised product outline (draft version) for expanded scope of research beyond just dependent role: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/user-roles/project-outline-user-roles-permissions-research.md
