### ISSUE TITLE
FSR Training Video

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#29758]
## Issue Description
_FSR Training Video _

---
## Tasks
- [ ] _Going through each steps in FSR's workflow in staging and record video_

## Acceptance Criteria
- [ ] _A well understood training videos for new users to understand how to submit and FSR_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
