### ISSUE TITLE
*DECISION TOOLS SPRINT 56 PRIORITIES*

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#29757]
<hr>

## 🏖️ Sprint 56 Vacation/PTO/Holidays
None scheduled

<hr>

### 1. FIND A VA FORM
- [ ] Marci - Schedule meeting for Cindy to present research findings to VA stakeholders **9/20 or 9/21 - who should be involved**?   Date/attendees still TBD 
- [x] Cassandra - #29704
- [x] Marci - #29731
- [x] Marci - #29705
- [x] Dave / Marci #18985 
- [x] Dave / Marci #19005
- [ ] Cindy - #29754 Date/attendees still TBD 
- [ ] Zach **(STRETCH)** - #29706
- [x] Zach **(STRETCH)** - #29707
- [ ] Marci - request permanent server-side redirect from old form search to new  Have contacts & info now from Stan

<hr>

### 3. TECH DEBT 
- [x] Zach - #12535  ~~[NOTE - NEED CONFIRMATION WE HAVE CORRECT LINKS]~~ 
- [x] Zach - #28351
- [x] Zach - #29553
- [x] Zach - #22307
- [x] Zach - #9374 (Yellow Ribbon)

###  🗨️  Discussion Topics/Grooming 
- [ ] Ok for Marci to make updates in CMS? 
- [ ] Topic
- [ ] Topic
