### ISSUE TITLE
MCP - Extract Vista ID from user login

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#29761]
## Issue Description
_Extract VISTA ID once a user logs into MCP_

---
## Tasks
- [ ] _Connect with the VISTA ID work Identity team did for us to extract Vista ID_

## Acceptance Criteria
- [ ] _Once a user logs into MCP we can pull their VISTA ID as well as their EDIPI to connect with their copay bill endpoints_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
Slack [thread](https://dsva.slack.com/archives/CSFV4QTKN/p1630605267018700) about the VSP identity team adding VISTA ID support to vets-api.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28888) where the VISTA IDs were added to the global User object.
