### ISSUE TITLE
Default placeholder VAMC facility images 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29770]
## Issue Description
We're trying to avoid a precedent of CMS passing a "false" value - such as placeholder facility images. Default images should be implemented on the FE as a response to image = null in the query. 

---
## Tasks
- [ ] Implement handling of default images in the FE template. 
- [ ] This change will need to be followed by CMS removing the placeholder images which have been already loaded 

## Acceptance Criteria
- [ ] When a facility image is not available, the FE will include the default placeholder image. 
- [ ] If a facility has been seeded with a placeholder image in Drupal, the FE does not render duplicate/multiple placeholder images.
