### ISSUE TITLE
Request to add new members to accessibility meetings

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#29775]
## Issue Description
Noah will be taking over the weekly 508 discussion with Martha, and the Design System Council seat for Trevor. I'd like to request he be added to these calls, and Joe and Peter be added as optional attendees.

---
## Tasks
- [ ] Create a new weekly meeting for informal discussion with Noah, and Peter and Joe optional
- [x] Add Joe and Peter as optional to the monthly VA 508 call

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by 1Copenut** [comment]
@JoeTice & @pjhill & @noahgelman for visibility

**Comment by pjhill** [comment]
Is there a list of relevant meetings that we can tick off as we go? Are the meeting organizers different people (who are we making the meeting requests to)?

**Comment by artsymartha68** [comment]
Joe and Peter, I just added you to the monthly 508 Office meeting.

**Comment by 1Copenut** [comment]
Thank you @artsymartha68 !
