### ISSUE TITLE
[FE] Notification Prefs: Treat missing mobile phone as missing all contact info

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29773]
## Background
Due to the removal of the covid/stay informed notification item for MVP, the only communication channel for MVP is mobile phone/text. Therefore we need to remove all instances of/references to email address from the notification settings page, and treat scenarios where the user is missing mobile phone number as missing _all_ contact information as previously outlined in the FE documentation.

## Tasks
- [x] Make the change
- [ ] Rewrite tests

## Acceptance Criteria
- [x] If user is missing mobile phone they will see the screen as noted [here](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/141757595/simulate/sitemap?mode=i)
- [x] User's email address never shows on the notification preferences screen

**Comment by erikphansen** [comment]
PR merged for this. It can be validated on staging soon.

One thing to note: The API is still returning the COVID-19 item so that will still show up in the notification settings page.

**Comment by ajakabcin** [comment]
Confirmed on staging - closing. Thanks Erik!
