### ISSUE TITLE
[MCP] Create mockups for limited detail page MVP

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29787]
## Issue Description
Due to data availability, we need to remove the table and promote the PDF downloads for the initial release of MCP. 

---
## Tasks
- [x] Create design for reduced MVP
- [x] Upload design to UXPin
- [x] Update use case documentation with/for Tze

## Acceptance Criteria
- [x] Designs in UXPin and linked to this ticket
- [x] Use cases updated and confirmed with Tze

**Comment by rileyorr** [comment]
- Updated the MVP design and exported to UXPin ([link](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141562175/simulate/sitemap?mode=i))
- Updated the use case document and notified Tze that we removed the table ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Docs/MCP-Use-Cases.md))
