### ISSUE TITLE
Update videos on vaccine CLP with 2 new ones

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29798]
## Issue Description
There are 2 videos on the vaccine campaign landing page about Veterans' experiences with getting the vaccine. There are 4 videos available to use, so we need to swap out the 2 currently in there and replace with the 2 others. We need to rotate these videos every other week.

CLP page:

https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/

New videos to add: https://prod.cms.va.gov/media/image/4430
(video link: https://www.youtube.com/watch?v=Dcnx5fOY268)

 https://prod.cms.va.gov/media/image/4431
(video link: https://www.youtube.com/watch?v=X2c7NMAWgHM)

We need to update the Veterans' names and the military branch on the page as well. 

## Tasks
- [x] Update new videos, names, and service branch (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] New videos are on live CLP

**Comment by lunascoop** [comment]
@RLHecht this page has been updated and is ready for review.

Have questions before you get your COVID-19 vaccine?: http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks, @lunascoop I published this. will set up a new ticket for swapping them out in 2 weeks.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
