### ISSUE TITLE
Grant Permissions to BE-Tools Team for Detaching EC2 Instances

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#29804]
## Description
Backend tools team members routinely have a need for detaching lower environment vets-api EC2 instances from autoscaling groups for testing. This has been a tedious process as the team members typically have to reach out to an Operations team member to get an instance detached for testing. 

## Background/context 
We should promote more self-service in these kinds of tasks and enable other platform teams to be able to detach and test on instances in lower environments.

---
## Tasks
- [x] IAM group permissions for be-tools team needs to be updated to allow detaching of instances to dev/staging vets-api ASGs

## Acceptance Criteria 
- [x] Perms granted to enable this action
- [x] Verification with a be-tools team member to ensure the perms work

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
