### ISSUE TITLE
HLR v2: Get contestable issues from updated API

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29802]
## Description

When the Higher-Level Review form retrieves the Veteran's contestable issues, the `v0` endpoint is still being used. Update this to use `v1` based on the feature flag

## Tasks

- [ ] Use `v1` contestable issues API endpoint for HLR v2
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
