### ISSUE TITLE
[Kubernetes] Goldilocks - requests/limits recommendation tool

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29812]
## Description

In order to help us determine acceptable requests and limits for our kubernetes deployments we are looking to implement Goldilocks on our clusters. We have been having trouble with deployments being throttled under normal operating circumstances which is not wanted.

## Technical notes

https://www.fairwinds.com/blog/introducing-goldilocks-a-tool-for-recommending-resource-requests 
https://github.com/FairwindsOps/goldilocks
https://github.com/FairwindsOps/charts/tree/master/stable/goldilocks

---
## Tasks
- [x] Create ecr repo for goldilock images
- [x] Deploy helm chart to dev cluster for testing
- [x] If all goes well repeat process for all clusters
- [x] Implement GHA for image builds, push to ecr, and updating manifests

## Acceptance Criteria 
- [x] Goldilocks deployed to all clusters and has infra repo build/manifest updates

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-goldilocks

![image](https://user-images.githubusercontent.com/76792875/133860976-6103c92f-f37b-4fda-b582-cf7247349bab.png)
![image](https://user-images.githubusercontent.com/76792875/133861054-764cb9d7-54ae-4193-97d8-0298e591abfd.png)

**Comment by dginther** [comment]
Closed. Complete.
