### ISSUE TITLE
[HAProxy] Upgrade to 2.0.25

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#29820]
## Description
HAProxy is in need of an update due to a new vulnerability

## Background/context 
- https://portswigger.net/daily-swig/haproxy-vulnerability-enables-http-request-smuggling-attacks
- https://dsva.slack.com/archives/CJYRZK2HH/p1631223009315500

---
## Tasks
- [x] update version and checksum in ansible config files
- [x] manually generate new image and tag for fwdproxy
- [x] deploy to dev for testing
- [x] if all goes well deploy to all environments

## Acceptance Criteria 
- [x] Version 2.0.25 haproxy running on all instances of fwdproxy   

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Reviewed and verified that we are running the desired version of HAProxy outlined here: 

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/a74607a0-cd20-4867-a7e0-6eb1449b02d2)
