### ISSUE TITLE
Update feature flag names

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29839]
## Issue Description
Rename feature flag names in [featureFlagNames.js](https://github.com/department-of-veterans-affairs/vets-website/blob/caa65b236ea47a325cfa51d0c25886c3eef636de/src/platform/utilities/feature-toggles/featureFlagNames.js#L51) to use snake_case instead of camelCase

Docs: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/
```
const FEATURE_FLAG_NAMES = Object.freeze({
 showYourFeatureName: 'app_name_then_your_feature_name',
})
```

---
## Tasks
The following feature flags should be renamed
- [ ] show526Wizard
- [ ] debtLettersShowLetters
- [ ] showFinancialStatusReport
- [ ] showFinancialStatusReportWizard

## Acceptance Criteria
- [ ] feature flags should be snake case
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
