### ISSUE TITLE
Remove 75b alert from the debt portal

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29831]
## Issue Description
DMC has verified the 75b debt email notification issue has been resolved so the alert should be removed from the debt portal on `manage-va-debt/your-debt/`

slack: https://dsva.slack.com/archives/CPE4AJ6Q0/p1631210571080300

![Your VA Debt  Veterans Affairs 2021-09-10 11-48-20(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/b8cf01bb-4555-4a71-a800-bd664990314a)

---
## Tasks
- [ ] remove alert from debt portal

## Acceptance Criteria
- [ ] alert should be removed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
