### ISSUE TITLE
Change out Veteran videos on vaccine CLP

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29843]
## Issue Description
We need to swap out the 2 stories videos on the vaccine CLP with the 2 Veterans we had previously used. 

2 videos to use:

Robert Bonner
https://www.youtube.com/watch?v=wMVj5kYn8ps

Ronald Pipkins
https://www.youtube.com/watch?v=jpykh5DMZb8

## Tasks
- [x] Update CLP with new videos (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] CLP has new videos on live site

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published. Will open a new ticket to swap these out again in 2 weeks.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
