### ISSUE TITLE
DGIB: Transition EDU Comparison Tool Redesign

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#29855]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/ct-redesign-discovery_product-outline.md)

## Description:
This is a placeholder epic that contains backlog work related to Comparison Tool Redesign that is being transitioned to the Digital GI Bill project.

## Resources:
[Documentation in repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/redesign)
BIP Epic: #13502

## VSP Collaboration Cycle.
- [x] Project Kickoff - #14570
- [x] Design Intent Collaboration - #16546 (open issues attached)
- [x] Usability Testing Prep - #18610
- [x] Research Plan Review - Requested via slack on 2021-01-28
- [x] ~Information Architecture (IA) Request~ Not doing - this is now part of content review (during staging)
- [x] Analytics Request - #27074
- [x] Staging Review - #28682
- [x] Privacy and Security Review - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/316
- [x] Contact Center Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

**Comment by mrblanco1** [comment]
Transitioning of the VA Comparison Tool between BAH and AFS occured on Sep 30th, 2021.
