### ISSUE TITLE
Debts endpoint gateway timeout errors

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29868]
## Issue Description
Sentry reporting gateway timeout errors the the debts endpoint `/v0/debts`

http://sentry.vfs.va.gov/organizations/vsp/issues/14866/?environment=production&project=3&query=is%3Aunresolved+source%3Ayour-debt&sort=freq&statsPeriod=7d

```
code: 504, 
detail: Did not receive a timely response from an upstream server, 
status: 504, 
title: Gateway timeout
```
---
## Tasks
- [ ] Look into Sentry and Loki to drill into why the timeout is occuring

## Acceptance Criteria
- [ ] We understand the reasons behind the timeout and have created followup work to resolve the issue
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
possibly related issue .. https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/30141

**Comment by denisecoveyduc** [comment]
We agreed during planning that @ScottyRJames will do some investigation and will update the tasks, acceptance criteria and size this one once he has a better handle on what "investigate" means. Further work can be broken into other issues for future sprints if needed.

**Comment by ScottyRJames** [comment]
This has been validated to no longer be a reoccurring issue and has been resolved on Sentry
