### ISSUE TITLE
Remove ssoe feature flags on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#29865]
## Issue Description
This will remove the feature flags for all ssoe related.  Additionally, it will remove any dependencies for the feature flags including Redux, etc.

---
## Tasks
- [ ] The `featureFlagNames.js` file is updated to remove ssoe
- [ ] Feature Flag YAML file is updated.

## Acceptance Criteria
- [ ] Verify ssoe feature flags are removed and functionality remains intact.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
