### ISSUE TITLE
Content updates to Post-9/11 GI Bill (Chapter 33) page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29860]
## Issue Description
We need to make some text changes to the [Post 9/11 GI Bill (Chapter 33)](va.gov/education/about-gi-bill-benefits/post-9-11/) page now that we will have an R&S page with information on how much of the benefit you can qualify for.

Under the question **What benefits can I get through the Post-9/11 GI Bill (Chapter 33)?** we need to remove the following content section:

Here’s how we’ll determine how much of the benefit you’ll qualify for:

The specific amount you’ll receive will depend on how much active service you’ve had since September 10, 2001. We’ll calculate this amount based on a percentage of the maximum benefit.

For example: If you had 90 days of active service since September 10, 2001, you would qualify for 40% of the maximum amount. If you served for 3 years, you would qualify for 100% of the benefit. So if your school charges $22,000 for in-state tuition and fees, you would receive $8,800 if you had 90 days of active service and the full $22,000 if you had 3 years of active service.

Note that this will change August 1, 2020. In this example, 90 days of active service would qualify you for 50% of the maximum amount as of August 1, 2020.

This text will be replaced with a link to our new R&S article, which will most likely be called **How we determine the amount of Post-9/11 GI Bill benefits you can get**

## Tasks
- [ ] Update text on benefits page to remove old section and add text with link to new article
- [ ] Review and publish
- [ ] Alert stakeholders that page is live

## Acceptance Criteria
- [ ] New content and link to new R&S article live on benefits page
