### ISSUE TITLE
[FSR] Update 'Make a payment' terminus in the wizard

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29875]
## Issue Description
We received feedback from IA to provide more specific info/link directly to all the ways Veterans can make a payment on a debt. To align with the medical copay portion of the wizard, we want to add another question to ask how the Veteran wants to make a payment: online, by phone, or by mail. 

---
## Tasks
- [ ] Update the FSR wizard to add a question 'How do you want to make a payment?' when 'Make a payment on a balance' is selected ([refer to this UXPin](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691610/simulate/sitemap?mode=i))
- [ ] Add the three different termini for making a payment online, by phone, or by mail ([refer to this UXPin](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691609/simulate/sitemap?mode=i)) 

## Acceptance Criteria
- [ ] The wizard has been updated to include the additional question outlined above
- [ ] The new wizard termini have been added 
- [ ] A designer has reviewed the UI updates

**Comment by craigwheeler** [comment]
duplicate of issue [29876](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29876) closing
