### ISSUE TITLE
[FE] Notification Prefs: Display hint text for Rx tracking conditionally

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29879]
## Background
Per our findings in #28982, we're going to to revise the hint text to be more evergreen and conditionally display it for Veterans when they are registered with more than one VA facility where at least one of those facilities is a participant in the pilot Rx tracking feature. They will not see the hint text if they are associated _only_ with facilities that support the feature.

## Tasks
- [ ] Implement revised text
- [ ] Implement conditional rules for when to display hint text

## Acceptance Criteria
- [ ] Hint text is hidden if users are associated only with facilities that support the Rx tracking feature

**Comment by erikphansen** [comment]
I have a PR up for this, but am still awaiting final copy.
