### ISSUE TITLE
526: Discover & fix `toLowerCase` of undefined Sentry error

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29882]
## Description

The linked Sentry error shows a JS error `Cannot read property 'toLowerCase' of undefined`. After a quick investigation, there isn't one specific instance that jumps out, but maybe adding extra checks to existing `toLowerCase` function may prevent this event in the future.

Sentry event: http://sentry.vfs.va.gov/organizations/vsp/issues/47091

## Tasks

- [ ] Add default and/or fallbacks to prevent string manipulation function errors
- [ ] Add/update unit tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
