### ISSUE TITLE
[VAMC] Update Operating systems with correct facilities for use in this system operating status [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#29892]
## Story
As a PAO editor I must have all correct facilities listed in the Operating Status, so I can keep correct status updates listed for each facility.

## GOAL
Update last remaining operating status pages witl the correct facilities for the system.

## TASK
Update each operating status page for each of the below systems with the correct facilities associated to that system.  Make sure Medical center is listed first and then all remaining clinics are in alphabetic order there after.
VISN 02
- [ ] VA Bronx health care
VISN 04
- [ ] 	VA Philadelphia health care
- [ ] 	VA Erie health care
VISN 06
- [ ] 	VA Hampton health care
- [ ] 	VA Richmond health care
VISN 08
- [ ] 	VA West Palm Beach health care
- [ ] 	VA Bay Pines health care
- [ ] 	VA North Florida health care
- [ ] 	VA Tampa health care (edited) 
VISN 16
- [ ] 	VA Jackson health care
VISN 19
- [ ] 	VA Western Colorado health care
- [ ] 	VA Sheridan health care
- [ ] 	VA Montana health care
- [ ] 	VA Cheyenne health care
- [ ] 	VA Eastern Colorado health care
VISN 21
- [ ] 	 VA San Francisco health care
VISN 23
- [ ] 	VA Black Hills health care
- [ ] 	VA Nebraska-Western Iowa health care
- [ ] 	VA Iowa City health care

## Acceptance Criteria
- [ ] All system operating status page is updated with facilities associated to that system
- [ ] Facilities are visible in publication of that system

**Comment by ltrombley** [comment]
Task #29892 -  Update Operating systems with correct facilities for use in this system operating status [VAMC] - is Complete and moved to Validate
