### ISSUE TITLE
526: Discover & fix Sentry `undefined is not an object` for `n.definitions`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29893]
## Description

The linked Sentry event shows a JS error `undefined is not an object (evaluating 'n.definitions')`. After viewing related events, this issue appears to occur on the `/new-disabilities/follow-up/:index` pages. This error may live within the platform code, or within the `react-jsonschema-form` repo.

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/49240

## Steps to duplicate

1. Go to: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up/0
2. Edit rated disabilities manually (just so that api would update them back to what they were)
3. Exit form 
4. Paste https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up/0 into URL bar

## Tasks

- [ ] Get test data to allow easier troubleshooting
- [ ] Find source of the JS error
- [ ] Fix souce of the error
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
Still trying to find a good data source to duplicate this error. Will need to push this ticket into the next sprint.

**Comment by Mottie** [comment]
This Sentry error is a lot more rare now! 🎉  We will continue to monitor until the end of this sprint and close this issue if it doesn't show up again, or we're unable to obtain data from an occurance.

**Comment by Mottie** [comment]
No current Sentry events. Closing this issue now, but will reopen if it occurs again.

**Comment by Mottie** [comment]
New Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/60670/
