### ISSUE TITLE
NOD: Update additional issue content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29914]
## Description

Updating the Notice of Disagreement additional issues page content based on feedback from the Board

Related: 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/29517
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/29518
- Design: https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/v/xyRA5J/a/jgMAyob/r/xyRAxl

<img width="613" alt="Screen Shot 2021-09-14 at 9 42 57 AM" src="https://user-images.githubusercontent.com/136959/133279287-c12925bd-c161-4cba-a4e8-ffbdf02a0450.png">

## Tasks

- [ ] Update NOD content

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
