### ISSUE TITLE
BDD: Evidence content changes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#29915]
## Description

On step 3 of 5 page of the Benefits Delivery at Discharge flow for Form 526, there was a recommendation to revise "What type of evidence do you want us to review as part of your claim?" to "What type of evidence do you want to submit as part of your claim?"

Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/27144

![](https://user-images.githubusercontent.com/54544300/133093753-b9fb6c26-868c-4f62-91ea-449b614d42f0.jpg)

## Tasks

- [ ] Update evidence page content

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
