### ISSUE TITLE
Implement standardized process for new VFS team members

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29919]
## Issue Description
The creation of the [Platform Orientation - Current State Service Blueprint](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1634334965737/bf671d055e1072a001d00cd1d6b7dc89b0987bfc?sender=u0574179b1d97118ccc0e3591) allowed Platform to recognize many areas for improvement in the current process. All Improvement Opportunities identified have been documented in the [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13709) for this effort. 

The objective of this ticket is address Improvement Opportunity # 1: Communication of new team/team member varies depending on program (AKA no consistent form of intake). By editing [Platform Website/ Getting Started/ Platform Orientation page ](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) to include guidance that all new VFS team members should assign themselves the [Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template), we can standardize the intake process of all new VFS team members.

In addition, the [Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template) can be modified to include a direct link to the [Calendly sign up for General Orientation. ](https://calendly.com/collaboration-cycle/general-orientation-for-va-gov-platform)

---
## Tasks
- [x] Update Platform Orientation template to include Calendly link for General Orientation
- [x] Update Platform Website/ Getting Started/ Platform Orientation page to include:
   - [x] welcome message for new VFS team member
   - [x] link to the Platform Orientation template
   - [x] instructions asking new VFS team members to self-assign themselves the linked template so that they may be successfully onboarded to VA.gov Platform

## Acceptance Criteria
- [x] We have shared this new process with VFS teams via #vfs-all-teams and Team of Teams
- [x] We have shared this new process with Platform via #platform-team
- [x] Platform team members will be able to easily direct new VFS team members to Platform Website

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
