### ISSUE TITLE
Standardize scheduling of role-based orientations

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29920]
## Issue Description
In November of 2021, Platform made the decision to no longer schedule/coordinate 1:1 with new team members for General Orientation. Instead, Platform would host General Orientation once a month (the first Tuesday of each month at 3:00pm ET). Simultaneously, Platform also began using Calendly for scheduling General Orientation for VA.gov Platform. Calendly tool allows VFS team members to click a link, see what availabile dates/times exist for General Orientation, and sign up themselves. In [this ticket, ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29919) Platform added the General Orientation Calendly sign-up link to the Platform Orientation template, making it very easy for new VFS team members to sign up for General Orientation.

Platform would like to replicate the new General Orientation scheduling process with the other role-based orientations:

- Design orientation (First Monday of every month @ 4:00 PM EST)
- Front-end orientation (Fourth Tuesday of every month @ 10:00 AM EST)
- Back-end orientation (First Wednesday of every month @ 3:00 PM EST)
- Analytics orientation (First Thursday of every month @ 2:30 PM EST)
- Accessibility orientation (First Friday of every month @ 3:00 PM EST)
- QA orientation (Third Thursday of every month @ 3:00 PM EST)
- ATO orientation (this orientation may be exempt. Need to check with Platform leadership). Update 1/12: No need to include ATO orientation. We have plans to include this in the New VFS Team ticket #33198 

---
## Tasks
- [x] Contact the owners of each of the below orientations (via #platform-team and cc Shira) and share with them our proposal:
`'Platform would like to move away from the adhoc/on-demand scheduling of the role-based orientations for Platform Orientations and begin using Calendly for scheduling the role-based orientations. In order to do this efficiently and easily, role-based orientations will need to be hosted on a set cadence, preferably once a month. General Orientation is currently hosted the first Tuesday of the month at 3:00pm ET. We'd like to set up a similar schedule for the other orientations and need your support. Please share with us which date/time you/your team can commit to on a monthly basis for hosting the role-based orientation. Because we are using Calendly to schedule, and because Calendly looks at the Platform Collaboration Cycle calendar for availability, the times for the role-based orientations must not conflict with the existing events on the calendar (ie the Collaboration Cycle reserved timeslots and General Orientation)` WIP
   - [x] Design orientation (Naomi & Allison) 
   - [x] Front-end orientation (Lainey Trahan & Tim Wright)
   - [x] Back-end orientation (Nate Peterson & Travis Hilton)
   - [x] Analytics orientation (Michelle Dooley)
   - [x] Accessibility orientation (Noah Gelman)
   - [x] QA orientation (Peter Hill)
- [x] Ensure chosen timeslots due not conflict with events on the Platform Collaboration Cycle calendar
- [x] Set up Calendly events for the orientations once dates/times have been decided - Shira will update here when complete.
- [x] Shira - Send the Calendly booking pages to the owners of each orientation and complete the following:
   - Have them sign up for the orientation from January 2022 (if still applicable) until December 2022
   - Have them review the event description and provide feedback.
   - Ask them to identify any dates that need to be modified (due to a holiday or PTO, if known)
   - Ask them to provide their Zoom details to be added to the event (once created). 
- [x] Shira - Modify the event description in Calendly, if needed.
- [x] Shira - Adjust dates that need to be modified (per orientation owner direction)
- [x] Shira - Add the orientation owner's Zoom information
- [x] Sean - Update the Platform Orientation template  to include the Calendly sign-up links and remove guidance to DM via Slack (see General Orientation for reference)
- [ ] Shira - Document how the scheduling process works in Confluence/Platform Orientation space

## Acceptance Criteria
- [x] VFS teams are able to sign up for role-based orientations via Calendly
- [x] There is a monthly reoccurring meeting for each orientation
- [ ] The orientation hosts understand their role and duties
- [ ] Operation/internal documentation exists in confluence

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by seanasewell** [comment]
Update: Reached out to the orientation owners via Slack (#platform-team). Awaiting responses.

**Comment by seanasewell** [comment]
UPDATE: Time slots for all role-based orientations have been filled. (time-slots below)

Design orientation (First Monday of every month @ 4:00 PM EST)
Front-end orientation (Fourth Tuesday of every month @ 10:00 AM EST)
Back-end orientation (First Wednesday of every month @ 3:00 PM EST)
Analytics orientation (First Thursday of every month @ 2:30 PM EST)
Accessibility orientation (First Friday of every month @ 3:00 PM EST)
QA orientation (Third Thursday of every month @ 3:00 PM EST)

@shiragoodman  Do we know if ATO will conduct an orientation? How would you like me to connect with Platform leadership in order to get this information?
ATO orientation (this orientation may be exempt. Need to check with Platform leadership).

**Comment by shiragoodman** [comment]
@seanasewell i updated your comment from yesterday with the new time from Lainey for Front End orientation. 

I am getting the Calendly events set up now and will share here when they're ready :)

**Comment by shiragoodman** [comment]
@seanasewell here are the Calendly links for each of the orientations:
Accessibility Orientation: https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform
Design Orientation: https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform
Front-end Orientation: https://calendly.com/collaboration-cycle/front-end-orientation-for-va-gov-platform
Back-end Orientation: https://calendly.com/collaboration-cycle/back-end-orientation-for-va-gov-platform
Analytics Orientation: https://calendly.com/collaboration-cycle/analytics-orientation-for-va-gov-platform
QA Orientation: https://calendly.com/collaboration-cycle/qa-orientation-for-va-gov-platform

**Comment by seanasewell** [comment]
@shiragoodman I updated the orientation template to include the calendly links for each role. Still needs to be merged.

**Comment by shiragoodman** [comment]
@seanasewell can you assign me as a reviewer in your PR?

**Comment by seanasewell** [comment]
@shiragoodman Just assigned you!

**Comment by seanasewell** [comment]
Merged orientation template updates on GitHub

**Comment by shiragoodman** [comment]
The task, "Document how the scheduling process works in Confluence/Platform Orientation space" and the AC, "The orientation hosts understand their role and duties" and "Operation/internal documentation exists in confluence" will be handled in ticket #35519.
