### ISSUE TITLE
Update how to cc kickoff and custom track flow questions

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#29925]
## Issue Description
The [How to for CC Kickoff documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/CC+-+Collaboration+Cycle+Kickoff?focusedCommentId=1886191655#comment-1886191655) is currently outdated and does not match the questions on the [custom track flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow).

---
## Tasks
- [ ] Review the questions on the [custom track flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) and make sure they are still current
- [ ] Review verbiage on how to cc kickoff and make sure it is current
- [ ] On how to cc kickoff replace "Please review the guidance on our Collaboration Cycle README page for next steps." with "Please review the guidance on our [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page for next steps."

## Acceptance Criteria
- [ ] The how to cc kickoff documentation is current
- [ ] The custom track flow questions match how to cc kickoff
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 what's the status of this? I marked it complete in Sprint 62..

**Comment by allison0034** [comment]
It is complete! When I reviewed the kickoff ticket a team requested I was able to compare. I only saw the difference in the numbered questions which has been update
