### ISSUE TITLE
Create Analysis & Insights training

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#29939]
## Issue Description
VFS teams understand how to analyze their data using basic exploratory analysis.

They may or may not use the data dictionaries for this purpose.

They should be able to use the data that Platform Analytics & Insights provides to understand their product's pain points and/or make further recommendations.

It can be asynchronous, but the Platform Analytics & Insights team can use whatever we create to do a live training if needed.

---
## Tasks
- [x] Create an outline for scope of topics covered (i.e. stats 101, KPI framework, exploratory analysis, questions to ask, etc.)
- [x] Define MVP scope
- [x] Build slide deck
~~- [ ] Record deck video (20 min presentation)~~ _will record after presenting to several test teams and iterating flow_ 
- [x] Create a survey for feedback

## Acceptance Criteria
- [x] Platform Analytics can test a "analysis & insights" training with the VFS teams.

## Definition of Done
- [x] A training deck and script is completed.

**Comment by joanneesteban** [comment]
@chloedotbrown to attach the training to the ticket.

Focusing on exploratory analysis. Collab with @laurensimpson14 .

**Comment by chloedotbrown** [comment]
Outline for current (and some future) trainings available [here](https://docs.google.com/document/d/1jujHe0OZKnTD-lkp8ArczrXBV3N79AFINM0Mhxr2I0Q/edit?usp=sharing) – this sprint's training will be **Exploratory analysis and descriptive statistics**. I'll clean up as I work through the slides, but hopefully this should still give a helpful sense of scope!

I've also created some notes for future trainings I can imagine being useful:

- **Getting to know your data (and what data matters)**: This could be a useful primer plus tie-in to the Analytics Playbook that could come before the one above (when both exist). For now, it seems less pressing, since we do have more resources for this that already exist.
- **A/B testing and experiment design**: Keeping extremely high level for now, since we haven't talked much about what this capability will look like for our team. But I'd love to plan ahead so that we can have this ready as soon as it's something we start doing!

**Comment by chloedotbrown** [comment]
Here's a link to the [new insights training](https://docs.google.com/presentation/d/1uAQwY5HvDQSLhcPyBW6rRJYGgIpPU6AwpMSMSvgcWBw/edit?usp=sharing)! Might be tight to fit it to 20 min, but I think I can get it there by Monday. A draft of a [feedback form](https://docs.google.com/forms/d/1Xd2TR0NW9i7C_gDzuQGpepjiPS5Hzy0UlClOfcSft5o/edit?usp=sharing) is here as well.

I've moved these files into the Platform Analytics folder on Oddball's shared drive and also given the team + Andrea individual editor access. That said, if anyone has trouble accessing, please let me know!
