### ISSUE TITLE
Create Documentation Around TIC Gateway Outages

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#29934]
## Description
We (operations team) need a document that outlines the proper process to obtaining assistance from Gateway Ops when a TIC Gateway goes down.

## Background/context 
https://dsva.slack.com/archives/C24RH0W11/p1631643451071900

---
## Tasks
- [ ] Create document outlining proper process for TIC Gateway outages

## Acceptance Criteria 
- [ ] Clear and concise doc on this topic exists in Confluence

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
A SNOW ticket can be placed to reach to the Gateway TIC team. Documentation/process still needs work
