### ISSUE TITLE
Create Google Analytics training

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#29940]
## Issue Description
VFS teams understand how to navigate the **VA**'s Google Analytics properties.

It can be asynchronous, but the Platform Analytics & Insights team can use whatever we create to do a live training if needed.
---
## Tasks
- [x] Modify the Empirical Path training deck
- [x] Grab links for Google's GA courses
- [ ] Test out a 20 minute video recording
- [x] Schedule a training with Randi Hecht's team
- [x] Create a survey for feedback

## Acceptance Criteria
- [ ] Platform Analytics can test a Google Analytics training with the VFS teams.

## Definition of Done
- [x] A training (deck, video, etc.) is completed.

**Comment by laurensimpson14** [comment]
Link to the deck that we are working off of for this GA training ➡️  https://docs.google.com/presentation/d/1VqFTJso8IkatklBSvbW--dc9j51SNLh9nDedoEoTyDU/edit?usp=sharing

**Comment by joanneesteban** [comment]
@laurensimpson14 has been leading the GA training documentation. We can put something on the calendar for next week. 

CC: @chloedotbrown might need to create the Zoom room (for recording).

**Comment by laurensimpson14** [comment]
Update: 
-  The [training deck](https://docs.google.com/presentation/d/1VqFTJso8IkatklBSvbW--dc9j51SNLh9nDedoEoTyDU/edit?usp=sharing) is completed
- Chloe created a [feedback form](https://docs.google.com/forms/d/1Xd2TR0NW9i7C_gDzuQGpepjiPS5Hzy0UlClOfcSft5o/edit?usp=sharing) to be used for both platform analytics trainings (GA & Exploratory Analysis) 
- Training with Randi's team is scheduled for 10/7 at 11:45 am EDT
