### ISSUE TITLE
Reduce VA facility search results per page from 20 to 10

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#29942]
## Issue Description
~Currently, search results for VA facilities are returned with pagination but the number of results are not limited per page.~
Currently, search results for VA facilities are paginated with 20 listings per page. This was done because we couldn't paginate PPMS data. Now that PPMS is supporting pagination, we can start by reduce this to 10 per page. 

Steps to reproduce:

- Use the Facility Locator to search for VA health facilities in Brooklyn, NY
- Observe pagination is available for two pages
- Observe the first page of results includes 20 locations up to 35.8 miles away, beginning again at letter A
- The second page of results is for locations beginning at 31.7 miles away (distance overlaps but locations are unique)

[Loom link](https://www.loom.com/share/475648fc0e7e44a985dc5c2ebaf1bf8c)

[Reference for computing distance](https://github.com/department-of-veterans-affairs/vets-website/blob/5c88ad68f93f4abfb595838261193c5596666d2d/src/applications/facility-locator/actions/index.js#L152)

This issue is limited to fixing existing pagination for VA facilities with the intent of applying these same rules to Community Care in a subsequent issue

---
## Tasks
- [ ] Ensure 10 results are returned per page
~- [ ] Restart letter conventions with each page~ This is already working.
- [ ] ~Sort by distance (as computed from the center), not by drive time~ (moving into a separate issue #30212 )
* Results are already sorted by distance from map center on the client side. The issue is that the map center is recalculated when paginating. To fix, we could compute distance on the back end instead, or query all records and paginate client side (harder and less performant).
- [ ] Add/update tests as needed

## Acceptance Criteria
- [x] The first result on page 2 is letter A
- [ ] Each page of results has 10 (assuming there are at least that number)
- [ ] ~Results are sorted by distance from one page to another~
