### ISSUE TITLE
Update TUD Account on User Login & Logout

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#29949]
## Issue Description
The TUD currently gets its account data from a `.csv` that is imported directly into its database. This will lead to account data becoming out-of-date as the user accounts the TUD references are used and modified. We already have the user object present in some TUD logic that occurs on login and logout; we should take that opportunity to update the TUD with that user's information while we have access to it to keep it up to date.

---
## Tasks
- [ ] Update the following TUD fields on user login:     
      
      * first_name
      * middle_name
      * last_name
      * gender
      * birth_date
      * ssn
      * phone
      * loa
      * idme_uuid
      * services

- [ ] update the same fields on user logout

## Acceptance Criteria
- [ ] The TUD will be updated with it's related user's current information whenever they log in
- [ ] The TUD will be updated with it's related user's current information whenever they log out
