### ISSUE TITLE
Publish and train re: CHANGELOG guidance

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29955]
# User story

As a Platform team member, I need to know make announcements via the Platform website, customers are aware of (and can refer to) our changes.

# Tasks

- [ ] Clean up 
  - Reach out to PS, Analytics since they already have announced
  - Prepare the developer docs August changelog
- [x] Schedule sesh w/ PMs and their documentation team members (that will be recorded)
- [x] Create messaging to socialize
- [x] Disseminate guidance and recording

# Acceptance criteria
- Platform teams know where to find the guidance
- Platform teams have been trained (or know where to find the training)

# Reference info
- Needs robust rollout
- For future thinking: Incl. in initiative launch checklist?
- Would changelog vs. newsletter need to be addressed?  Let's wait till we get questions

**Comment by lianilychee** [comment]
9/16 Thurs:
- Will schedule something with the PMs
  - Weds IA session worked, maybe it will still work?

**Comment by lianilychee** [comment]
9/21 Tues:
- gonna focus on this today (bc of Shira and general training tmr)

**Comment by lianilychee** [comment]
9/27 Mon:
- All tasks are done!
- But... adding our changelog announcement to the Platform website (telling customers about changelogs)
