### ISSUE TITLE
Draft Sept newsletter edition

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29953]
# User story

As a VFS team member, I want to understand any Platform releases, so that I can build my VA.gov service.

# Tasks

- [x] Conduct pair-writing sessions (Amy)
- [ ] Draft newsletter edition
- [ ] Conduct reviews for technical accuracy and OCTO-DE signoff

Overall newsletter production tasks:
- Solicit content (Service Design)
- Conduct pair-writing sessions (Amy)
- Draft newsletter edition
- Conduct reviews for technical accuracy and OCTO-DE signoff
- Prepare MailChimp version (Service Design, but we support)
- Publish the newsletter via email (Service Design)
- Announce the newsletter via Slack (Service Design)

# Acceptance criteria
- To come.

# Reference info
- n/a

**Comment by lianilychee** [comment]
9/20 Mon:
- will get drafts ready to go so can review with Gretchen when G returns on Tues

**Comment by lianilychee** [comment]
9/21 Tues:
- maybe pencil a review in for today, maybe tomorrow! :sweat-smile:

**Comment by lianilychee** [comment]
9/27 Mon:
- Gonna let James know that the newsletter will be published on Weds
- Hoping to send out draft for feedback by EOD
- Having trouble w/ Jesse's submission; it's pretty detailed.  Also, is it a new release or coming soon?
