### ISSUE TITLE
Socialize PLATFORM TOOLS

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29958]
# User story

As a Platform customer, I need to know what tools the VA.gov Platform uses so that I can smoothly start to building my application.

# Tasks

- [ ] Background research
  - Identify what about Platform tools requires the doc to be socialized differently from prev guidance
  - Identify how it's most helpful for customers to receive the Platform tools info
- [ ] Tasks from background research
- [x] Sync w/ Product Support to make sure that they are incl. Platform tools during Orientation
- [x] Sync w/ SD - does this align w/ their communications plan?
- [ ] Socialize!

# Acceptance criteria
- Customers know about and can find the new page

# Reference info
- To come

**Comment by lianilychee** [comment]
9/16 Mon:
- huddle as a team.  we'll maybe use SU tmr, but depends on reviewing draft message to socialize videos and images guidance

**Comment by lianilychee** [comment]
9/28 Tues:
- have not started :D
- Brainstorming of what goes in the message:
  - One message that is modified for the different channels
    - **Why we created it:** Help teams' new members get started by learning about Platform tools
    - **What pain point(s) this work addresses:** No comprehensive list of Platform tools, either home-grown or third-party.  This means that people have to hunt for information.  Less time doing the work, and more time on finding resources.
    - **Overview of what it is, what it contains:** a list of home-grown and third-party Platform tools and setup instructions
    - **Who it's for:** VFS teams' new members
    - **How to use it:** All in one!
    - **If applicable, timeline involved:**  Will be sharing the Platform website link over the next couple of weeks.
    - **ToT messaging for anticipated release:** The Platform will soon be releasing “Platform tools,” a list of home-grown and third-party Platform tools and setup instructions, that will help your team’s new members get started building their application. More to come about anticipated release date!

- Service design communications channels
  - New or changed product, service, process, software tool 
  - Team/people changes
- Branding/naming changes
- Bottom Up:
- 
- Quarterly platform customer satisfaction survey
- 
- Product Support Surveys
- 
- User interviews
- 
- Feature Requests
- 
- Leadership:
- 
- Platform strategy
- 
- Platform roadmap
- 
- Announcements
- 
- Info about business processes
- 
- Crisis/Emergency:
- 
- Deployment issues
- 
- Infrastructure outages
- 
- Security incidents
- 
- Marketing Campaign:
- 
- Roadshows
- 
- Community events
- 
- Platform Orientation
