### ISSUE TITLE
Validate non-eng TOP TASKS

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#29956]
# User story

As a Content team member, I need to validate and finalize the non-eng top tasks, so that I can identify what writing work results from this research round-up.

# Tasks

- [ ] Validate with Rachael Roueche and dial in the level of refinement needed
- [ ] Refine spreadsheet into presentable form
- [ ] Determine with whom to additionally validate

# Acceptance criteria
- To come.

# Reference info
- Can top tasks incl work that we want prompt customers to do?  
  - Ex: config synth monitoring, monitoring the FE performance of their tools, reaching out to set up their KPI dashes, monitoring, etc.
  - ^^ go to the different teams on Platform crew; ask em what _they_ think are frustrating that customers aren't doing on their own
- Less granular = :thumbs-up:

**Comment by lianilychee** [comment]
9/27 Mon:
- Talk to Rachael - Liani to schedule and Gretchen to tie up in prep for that session

**Comment by lianilychee** [comment]
9/29 Weds:
- Slack up w/ Rachael

**Comment by vbellissimo** [comment]
Cancelling; old task
