### ISSUE TITLE
Update platform website/confluence docs to show IA changes (remove Mikki and add Jim)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#29960]
## Issue Description
Mikki is no longer on the Platform team and Jim Ryan has been added. The IA request is also no longer part of the collaboration cycle. We need to review and update any incorrect IA information on platform website and confluence.

---
## Tasks
- [x] Review the [contact us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-us.1764524036.html) to see if IA info is correct
- [x] Review the how to cc [design intent]
    - [x] Mikki and Jim should both be listed under "Invite the following"
- [x] Review the[ how to cc midpoint review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/CC-+Midpoint+Review). Jim should be listed under "Invite the following". 
    - [x] Jim should be listed under "Invite the following". 
- [x] Review the [how to cc staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/CC+-+Staging+Review). 
    - [x] Jim should be listed under "Invite the following". 
    - [x] Confirm with Mikki that she will not be attending

## Acceptance Criteria
- [x] All information for IA on the [contact us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-us.1764524036.html) is correct
- [x] All information for IA on the [design intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/CC+-+Design+Intent) is correct
- [x] All information for IA on the [how to cc midpoint review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/CC-+Midpoint+Review)
- [x] All information for IA on the [how to cc staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/CC+-+Staging+Review)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jimuhh** [comment]
I reached out to @mnorthuis and she confirmed that she would be attending the staging review meetings until I get up to speed on them, so am keeping her name there for the time being.

**Comment by jimuhh** [comment]
Pages checked, edited and published. LMK if you see anything I missed.
