### ISSUE TITLE
[MCP] Create preliminary design diagrams for inclusion of HTML statements

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29972]
## Issue Description
We are currently investigating if the HTML statements that are currently being rendered and produced on AccessVA are accessible; we need to think about how this feature might be incorporated into our existing design.

---
## Tasks
- [x] Ideate methods of including the HTML statements
- [x] Create a wireflow diagram showing how we might include them into the UI

## Acceptance Criteria
- [x] Wireflows uploaded to GH and linked in this ticket

**Comment by rileyorr** [comment]
Added the preliminary designs to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/design/html-vps-ideation.md))
