### ISSUE TITLE
[FE] API Call Clean Up

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29979]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

After the quick push to production We need to clean the API calls

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Add error handling for API alls that redirect to the error page
- [ ] Check GA API logging as well as PHI/PII is stripped
- [ ] Refactor the mock endpoints into a better solution(?)
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Added basic API error handling here: https://github.com/department-of-veterans-affairs/vets-website/pull/18746
