### ISSUE TITLE
[FSR] Enhancements Usability conversation guide

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29978]
## Issue Description
This ticket captures the conversation guide creation for the Enhanced FSR usability study. 

---
## Tasks
- [ ] Draft the conversation guide

## Acceptance Criteria
- [ ] Conversation guide has been uploaded to GH and linked in this ticket
- [ ] The conversation guide has been sent out for review/feedback

**Comment by denisecoveyduc** [comment]
@mgleo @charlottecesana  Just pointing this ticket out for clarity... can you confirm the labels etc are appropriate so you have visibility to it.
