### ISSUE TITLE
[FSR] FSR Enhancements research discovery

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29976]
## Issue Description
This ticket is for research discovery for the FSR enhancement release

---
## Tasks
- [x] Review previous FSR research, exploring how to build on that research and compare new research to issues seen and changes we have to improve the experience. 
- [x] Review [FSR enhancements](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/25881) and changes to guide research questions
- [x] Sync with other designers working on list loops
- [x] Draft the research plan - (Denise will add the link) 
- [x] Watch Recording of Riley showing UX Prototype  
- [x] Review [UX improvements](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/25881) to understand what changes are we making
- [x] Review [Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/readout.md#are-veterans-able-to-easily-use-the-new-list-loop-component) that describes why these changes are important and why original List loop implementation wasn’t successful  [Example: User Research showed confusion, Accessibility Issues, etc.]

## Acceptance Criteria
- [x] The draft research plan has been added to GH and linked in this ticket

**Comment by mgleo** [comment]
[Enhanced FSR Research Plan- draft](https://docs.google.com/document/d/19QB5-GLzIRS5tRAI1_-p2vDryeFvqI6m5Vfi386mUyU/edit?usp=sharing)
