### ISSUE TITLE
[FSR] List loop wireflows

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#29974]
## Issue Description
Because list loops did not test well in the FSR, we need to investigate alternative directions for the FSR's design.

Once ideation is complete, we will take the final outcomes from our presentation and compile it into a more fleshed-out wireflow spec for approval by our stakeholders

---
## Tasks
- [x] Create wireflows and document in GH
- [x] Discuss with team

## Acceptance Criteria
- [x] Wireflows documented in GH and linked to this ticket

**Comment by rebeccawalsh** [comment]
High level wireflows can be found here under the V2 section!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wireflows-change-log.md
