### ISSUE TITLE
Notify Veteran if Submission Fails

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29985]
## Issue Description
We would like to be able to notify the Veteran in the event of a disability claim submission failure.

Slack Thread: https://dsva.slack.com/archives/C5AGLBNRK/p1631741755144200
Backend Failed notification call location: EVSS::DisabilityCompensationForm::SubmitForm526#sidekiq_retries_exhausted

---
## Tasks
- [ ] Investigate possibility of engaging VA Notify team to implement automated notification after pre-determined number of tries.

## Acceptance Criteria
- [ ] Automated notifications implemented.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
I don't think this is a backend issue yet.  @vhenry07 I think the first step would be you getting in touch with the VA Notify team and then someone planning the content of the email.

**Comment by vhenry07** [comment]
Agreed. I've engaged VA Notify team https://github.comq/department-of-veterans-affairs/va.gov-team/issues/30005 and created ticket for design to work on content. https://github.com/department-of-veterans-affairs/va.gov-team/issues/30070

**Comment by drorva** [comment]
Based on a comment that @annaswims made, we have 4 cases:
1. Success when the vet submits.
2. Failure when vet submits (not all errors are retry-able)
3. Initial failure and eventual success after retries.
4. Initial failure and eventual failure after retries.
We should probably send a notification in all cases.

**Comment by vhenry07** [comment]
@michelpmcdonald Can you give me an idea of what kind of error messaging would be appropriate for scenarios 2, 3, & 4? We'd like to document a rough draft of a useful error and then have design work with content to tweak. [Link to design ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30070)

**Comment by vhenry07** [comment]
Work is being completed in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36090). Leaving this open for history and tracking until complete.

**Comment by vhenry07** [comment]
Closing this ticket as work is complete.

**Comment by drorva** [comment]
So in every failure case, we now notify veterans?

**Comment by vhenry07** [comment]
Yes.
