### ISSUE TITLE
Add new quick start guides to Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#29987]
## Issue Description
Stakeholder Justin Hoffman has new quick start guides that need to be uploaded to the Welcome Kit page. He has already uploaded them to the media library in the CMS.

The new QSGs:

Get Started with Veteran-Owned Small Business support
Get started with services for LGBTQ+ Veterans

These should be placed under the "For Veterans" section.

---
## Tasks
- [x] Add QSGs to welcome kit page (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that page is live (Randi)

## Acceptance Criteria
- [x] New guides are live on the Welcome Kit page

**Comment by lunascoop** [comment]
@RLHecht the QSGs have been added and the page is ready for review.

Print out your VA Welcome Kit: http://preview-prod.vfs.va.gov/preview?nodeId=716

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published this page. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
Page is live. Closing ticket.
