### ISSUE TITLE
[FE] Restrict Retries

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29983]
## User Story
- As a veteran, I should be able to try to validate my identity 3 times in case I mistyped my identity. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

A veteran should only be able to attempt to verify at most 3 times. After three times the veteran should be directed to a staff member after 3 fails

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Add a retry counter to the valid endpoint call
- [ ] Allow the counter to be configured, set to the 3 to start
- [ ] After `counter` times it should redirected to an error page
- [ ] Add session restriction to not longer allow retries
- [ ] Create Error page of too many attemptss
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
There are updated mocks in the sketch files around the error messages

**Comment by zach-park** [comment]
Hi @DanielleThierryUSDSVA (cc @kristenmcconnell @niradatta1 )

My name is Zach Park. A new ux designer, working on the error UI. And I've would like to get your feedback on the latest iteration of the wireframe with verbiage based on your feedback with Nira. So please take a look at the UI from the link below and let us know what you think. Also, it would be great if you could provide us with your feedback by early Tuesday (11/02), it would. be really appreciated as that is our last day of the sprint.

Thanks so much!

#29114: We couldn’t check you in: https://www.sketch.com/s/61f31b11-e47d-4706-82d0-981602c66f33/p/C03FA624-B45E-4F7D-A98C-00F807D10AB3

**Comment by julieadair1** [comment]
@jparker0425  what epic should this be attached to?

**Comment by dcgoodwin2112** [comment]
Moving to blocked until the FE refactor of the utils and hooks is complete

**Comment by kristenmcconnell** [comment]
Clarification on the different error messages needed when an entered last name or SSN doesn't match our records:

1. When the Veteran can still retry in both check-in and pre-check-in
![error icon.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/4b0a5f43-af49-448d-848a-f98041509cf1)
2. When the Veteran can no longer retry during day of check-in
![Confirmation.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8b2161f5-e7ad-4ff5-9e5a-60e0dfbc2a69)
3. When the Veteran can no longer retry during pre-check-in
![Confirmation - large.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/cf73438d-f0dc-4908-b55f-2edcee2c2550)

**Comment by dcgoodwin2112** [comment]
Pre-check-in Alert message
![pre-check-in-alert.png](https://images.zenhubusercontent.com/6144d3396adfc573505df211/264ac196-a961-4318-957a-5e499f3c89a9)

Pre-check-in Max validation retries error page
![pre-check-in-error.png](https://images.zenhubusercontent.com/6144d3396adfc573505df211/53028a66-5821-4353-8ef8-37414832926d)

Day-of Alert message
![day-of-alert.png](https://images.zenhubusercontent.com/6144d3396adfc573505df211/dc6e9b8d-10e2-481e-9991-6c48e1df7c4c)

Day-of Max validation retries error page
![day-of-error.png](https://images.zenhubusercontent.com/6144d3396adfc573505df211/2116be96-6481-4c0a-82ad-ceed182b6898)

**Comment by kristenmcconnell** [comment]
I can verify that those screenshots match the above wireframes. @niradatta1 is going to try to coordinate another UX testing session for numerous tickets. She is going to bring up this idea at stand up.

**Comment by sarahknoppA6** [comment]
@dcgoodwin2112 to sync w/ @randomsync on next steps

**Comment by niradatta1** [comment]
@dcgoodwin2112 Clarifying, so Veterans will see the first validation error message after 3 or less attempts; And then they will see the second one for 4 or more. Is that correct? 'cc @kristenmcconnell

**Comment by dcgoodwin2112** [comment]
thanks @randomsync ! The error messages in that ticket (36957) should work great. I'll need to make some minor tweaks to the validate page logic, but I'll probably open up a new FE ticket to handle those since the main branch for this one has already been merged.

**Comment by dcgoodwin2112** [comment]
After call/discussion with @acrollet, we decided to update this branch to only send updates to the demographics endpoint for pages that a veteran has reviewed instead of assigning default values. This will match up with pre-check-in and prevent the edge case of having a false response assigned to a page that was intentionally skipped. 

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1646937926043839?thread_ts=1645791682.440809&cid=C02G6AB3ZRS

**Comment by randomsync** [comment]
```
{
	"errors": [
		{
			"title": "Authentication Error",
			"detail": "Authentication Error",
			"code": "LOROTA-MAPPED-API_401",
			"status": "401"
		}
	]
}
```

**Comment by dcgoodwin2112** [comment]
This can be closed when ticket #38018 has passed validation

**Comment by dcgoodwin2112** [comment]
Tested and verified on production 03/22/22
