### ISSUE TITLE
[FE]

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29986]
## User Story

As a veteran, I should get feedback for required fields so that I can provide all the information needed to verify my identity

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

We need to mark the two input fields as required and provide accurate error messages

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ]  Mark the last name required
- [ ] Mark the Last 4 required
- [ ] Add a 4 number limit to the last 4 (change to type number) 
- [ ] Do not call the API if the items are not there. 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
The work is done and this is deployed and e2e tested, but unit tests are blocked until a babel fix happens https://dsva.slack.com/archives/CBU0KDSB1/p1632163115337400

**Comment by acrollet** [comment]
I updated #30129 with the AC to limit input to 4 numeric characters.
