### ISSUE TITLE
Remove Trevor from Product Support/Collaboration Cycle guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#29991]
## Issue Description
Trevor Pierce departed VSP/Platform Product Support on September 10. Trevor is mentioned in VFS-facing documentation on Platform Website, as well as in internal documentation on Confluence.

The purpose of this ticket is to remove Trevor from all guidance and documentation.

Note: Trevor has already been removed from the [How to Staging](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review) docs so this document can be used as a reference.

---
## Tasks
- [ ] Look for Trevor's name on [Platform products and service](https://vfs.atlassian.net/wiki/spaces/PPS/overview)s
- [ ] Look for Trevor's name on [Collaboration cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)

## Acceptance Criteria
- [ ] Trevors name has been deleted from platform products and services and collaboration cycle
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jimuhh** [comment]
Hi Allison,
On the[ Midpoint Review page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review), Trevor has his own table column header. What should I replace his name with there?

**Comment by jimuhh** [comment]
OK. I've gone over both sets of pages and removed mentions of Trevor. I'm pretty sure I got everything but am not one of nature's great proofreaders, so LMK if there are any oversights. If there are no objections, I'll close this now.

**Comment by jimuhh** [comment]
@peggygannon -- I've added Angela and Josh tot he VSA part of Midpoint review. Please review and make sure it's to your liking.

**Comment by peggygannon** [comment]
thanks @jimuhh I took a look and made just a few wording tweaks. Otherwise looks good!

**Comment by jimuhh** [comment]
Great. If there's no objection. Ima gonna close this now.
