### ISSUE TITLE
[FE] Redirect validated user

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29995]
## User Story

As a veteran, I should be redirected past the validate page if I am already validated

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Once a user loads the app after they have validated, they should go straight to the check-in now page

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Add check on the Landing page that checks the current sessions
- [x] If the user already has `read.full` permissions, then redirect the user to the appointment page
- [x] Create unit tests
- [x] Create e2e tests
- [x] Update relevant documentations
  - [x] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
