### ISSUE TITLE
[FE] Make sure the page can be refreshed

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#29994]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Validate the when each page is refreshed it starts the user over at the appropriate page (the start) 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Check the pages: 
- [ ] Validate
- [ ] Appoitemtns
- [ ] confirm
- [ ] error(generic)
- [ ] error (validate)
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
This was caught in the most recent production deploy
