### ISSUE TITLE
Add basic auth to the TUD site

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#30006]
## Issue Description
To prevent unauthorized use as we start piloting the Test User Dashboard a recommendation was made to lock down the site.  Basic auth is the simplest form to lock down the site in a quick manner. 

---
## Tasks
- [x] Create a htaccess/htpasswd file for TUD
- [x] Ensure credentials are hashed

## Acceptance Criteria
- [x] When visiting TUD, I need to sign in with Basic Auth to view the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
So I ran into a bunch of issues.  Instead of the creation of the htpasswd file the Basic Auth is implemented in Traefik (Kubernetes) with the help of Demian and the Ops team.  What spun out of this is that the original Traefik middleware could not read the credential and the Ops team created a new dev instance for TUD.

1. The htpasswd generated credential is placed into AWS
2. The application manifest repo pulls in the generated credential into the middleware.yaml file
3. The Traefik middleware then applies the credential and creates Basic Auth.
