### ISSUE TITLE
Upgrade to va-alert web components

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#30008]
## Issue Description
The Design System team has isssue a notice of the AlertBox becoming deprecated.  To ensure there is no lapse in functionality and user experience for the user we want to replace the AlertBox with the `<va-alert />` web component.

---
## Tasks
- [x] Replace AlertBox with the va-alert web components
- [x] Remove AlertBox imports
- [x] Ensure unit tests are updated accordingly

## Acceptance Criteria
- [x] No deprecation notices exist
- [x] No lapse in functionality/UX for users
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras This can be closed.
