### ISSUE TITLE
Remove moment dependency in sso utilities

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#30007]
## Issue Description
Currently the `utilities/sso` file uses the moment library to work with JavaScript dates.  Since the use is very limited (difference between 2 dates for session timeouts) we should remove the dependency and create a utility function to parse the dates.

---
## Tasks
- [x] Ensure there are no other JS date parser utils in vets-website
- [ ] Create a utility file for parsing between JS dates
- [ ] Write unit tests to ensure consistent results

## Acceptance Criteria
- [x] Moment library is removed from the Identity teams files
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
Nick: General cleanup of tech debt.
