### ISSUE TITLE
[Kubernetes] Fix argocd-application.libsonnet jsonnet library

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30036]
## Description
When deploying a new argocd application object it is built from the jsonnet template lib argocd-application.libsonnet.  It offers two sync policies automatedDefault() (auto sync enabled) and automatedDisabled() (auto sync disabled).  The problem being if you attempt to deploy a new app in a new namespace with the automatedDisabled() functionality the namespace will not be created and the deploy will fail.

This is due to the automatedDisabled() function not including the needed syncOptions (CreateNamespace=true) when defining a argocd application object.

https://github.com/argoproj/argo-cd/issues/1809#issuecomment-860123674
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/c628936ffc72a493cf7e6e0d965ad8045685c8e6/jsonnet/lib/argocd-application.libsonnet#L75-L103

---
## Tasks
- [x] Add CreateNamespace=true to syncOptions for the automatedDisabled() function 

## Acceptance Criteria 
- [x] Apps being deployed to a new namespace should create said namespace if it doesn't already exist if its using either  automatedDisabled() or automatedDefault() policies

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by dginther** [comment]
Closed, complete.

**Comment by mleclerc00** [comment]
Confirmed that deploying new applications to a new namespace with the automatedDisabled() sync policy doesn't fail anymore.
