### ISSUE TITLE
Platform Infrastructure: Migrate reverse proxy to EKS

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30038]
## Problem Statement 
The platform is implementing container orchestration as a way for development teams to host and deploy applications and services in a way that is reliable, scalable, and secure. Before offering container-orchestration-as-a-service to other teams using the platform, the Ops team is using container orchestration to host and deploy the applications and services that it manages and maintains. By doing this, Ops will help to ensure that they are both a developer and consumer of the solutions that it offers to others.

Once the main Ops-managed utilities have been migrated and are live in all environments, the final remaining pieces are to migrate the reverse proxy and the fwdproxy. In order to…

Migrate revproxy to EKS: lift and shift the current revproxy (open resty) configuration and move it into a container that running in EKS (rather than on an EC2 instance). There are some details to work through in terms of network routing as we translate that service into Kubernetes. In addition, we want to be sure that we can deploy the reverse proxy routinely and reliably using CI/CD. We need to be sure that we have full observability and alerting for the reverse proxy so that on-call personnel are notified accordingly. Lastly, we need to document the new setup and configuration for reverse proxy running in EKS. 

*Follow your problem description up with a "How might we... _______" statement re-framing that challenge as an opportunity. Don't hint too much at what the solution might be, you should have enough of a focal point here to guide your ideas, but plenty of freedom to think laterally and innovatively as you experiment and prototype later.*

## Hypothesis or Bet
*How will this initiative impact the quality of VFS or VSP teams' work?*
*How will this initiative be easy for VFS or VSP teams? Or how will it be easier than what they did before?*

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
End of Q4 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by mchelen-gov** [comment]
Notes for definition of done:
- deploy to EKS prod
- observability & logging
- internal documentation

**Comment by jhouse-solvd** [comment]
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: revproxy-http-tgb
spec:
  serviceRef:
    name: web # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-revproxy-http/ef467269502e6954
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: revproxy-https-tgb
spec:
  serviceRef:
    name: secure # route traffic to the awesome-service
    port: 443
  targetGroupARN: arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:targetgroup/vagov-dev-revproxy-https/856b95b9d31a8a59

**Comment by jhouse-solvd** [comment]
There's been some good recent discussion on what might be a more direct solution using Traefki that is potentially more sustainable given the desired future state. 

Here is the high-level plan hat will allow us to pursue the alternate solution w/ Traefik: 

_Given that there exists a Traefik target group that we could point traffic to from the revproxy ALB, a route could be added to the revproxy ALB w/ a rule activated by a special header._ 

1. **Set header manually for testing -> Make a request (e.g. to dev.va.gov) ->  ALB intercepts request with pre-defined header -> sends to Traefik -> sends to pods.** 
Note: This could be achieved immediately and doesn't affect anything already running. 
2. **Use this setup to test the performance of adding the additional hop through Traefik.** 
3. **Compare this to the latency of a request for traffic that does/doesn't have this header and determine if the latency is acceptable.** 

_If the latency is unacceptable_, then **make the determination whether or not to go forward w/ solution that uses routing for Calico**.

**Comment by mchelen-gov** [comment]
@jhouse-solvd that sounds reasonable, can you create a ticket within this epic to cover that work?

**Comment by jhouse-solvd** [comment]
@mchelen-gov - I've linked the epic into the comment above for posterity's sake, and also provided here: 

https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/32615

**Comment by jhouse-solvd** [comment]
Based on decisions and discussions coming out of quarterly planning for Q1 2022, this work will likely be merged with and superseded by #35039. 

In order to move forward with the reverse proxy migration, we need to be able to test with Vets-API.

**Comment by jhouse-solvd** [comment]
This is merging into #35039

**Comment by jhouse-solvd** [comment]
This is moving into upcoming initiatives to be re-evaluated and re-prioritized. It will likely still need to be done at some point. 

Please check in w/ Mike Chelen and me for the latest status.

**Comment by jhouse-solvd** [comment]
@ph-One - It will be good to understand where this work might land, based on recent conversations w/ the new Cloud Isolation Team (Platform Spike team). 

@dginther - As your plan comes together, we'd like to understand how that impacts this existing body of work. 

No immediate action required, but there is some good info in this Epic that will be useful to our conversations as it pertains to technical details and progress around the migration of revproxy.
