### ISSUE TITLE
[Debt Portal] Business and content review for status card redesigns

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#30031]
## Issue Description
We consolidated designs for the status cards in debt portal to mimic the cards created for MCP - we also incorporated payment plan information into these new cards. We need to introduce these new designs to VBA/DMC and hand them off for fact check then content review.

---
## Tasks
- [x] Send concepts to Jill and Co. for review

## Acceptance Criteria
- [x] Review kicked off with DMC
- [x] A ticket for content spot-check is linked to this ticket

**Comment by rileyorr** [comment]
I wrapped up setting up the spreadsheet ([link](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Debt%20Letters%20MVP/Iteration%203/Debt%20Portal%20Statuses%20V2.0.xlsx?d=w3ab9eb260d2c4074a53f27fb01e2d36e&csf=1&web=1&e=lU056K)) and updated the designs ([link](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/142818160/simulate/no-panels?mode=i)). Also set an email to the DMC team to review our new status cards to ensure we're accurately representing the diary codes!

**Comment by rileyorr** [comment]
@denisecoveyduc I updated this ticket's description based on this morning's chat to open a spot-check ticket for Troy to do a quick overview to ensure the content meets plain language standards. 

[That ticket can be found here!](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/34989)
