### ISSUE TITLE
526: Contact info prefill

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30032]
## Description

Since the contact info page was moved from near the end of the flow to the beginning, the prefill has stopped working. The phone, email and address is all empty in redux. Looking at the prefill data from the API, the data is there, it's not being added to the form.

## Tasks

- [ ] Discover why the form is dropping the API data
- [ ] Fix contact info prefill
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
