### ISSUE TITLE
Confluence Documentation for Updating GHA Runner Configurations

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30040]
## Description
As an Operations team member, I need to know the proper process for updating GHA runner configurations

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1631803704139000

---
## Tasks
- [x] Confluence doc outlining proper process for updating GHA runner configs
    - update terraform, pull request, apply upon approval
    - manually change asg size (if changes are made) due to the [lifecycle ignores](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-utility/gha-runners.tf#L153-L156)
    - update the launch template version being used
    - instance refresh

## Acceptance Criteria 
- [x] Confluence doc exists clearly outlining all steps in the process of updating existing GHA runner configurations

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Solved by notes added to https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners
