### ISSUE TITLE
[FE] Remove Clinic Phone number from footer

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30049]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Based on research, we need to remove the phone number from the footer. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Set the footer to never show the phone number.
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
@kristenmcconnell This is in staging, can you validate this and see what feedback you have?

**Comment by kristenmcconnell** [comment]
@mdewey I was able to review it in staging on the identity verification and error state pages. It looked great. "Ask a staff member." - perfect. 

I wasn't able to get past that page though. I'll talk with Stephen about my account and what I need to enter there in staging.
