### ISSUE TITLE
AutoSuggest highlight

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30054]
## Description

In our form 526, Veterans enter disability names in an autosuggest-enabled input. During research sessions, Veterans were confused by the seemingly random results. To help alleviate this problem, we will highlight portions of the suggested list that match the user input (see screenshot)

<details><summary>Current state</summary>

![Screen Shot 2021-09-16 at 2 27 18 PM](https://user-images.githubusercontent.com/136959/133680531-06cf1a06-1fb6-4a3d-962b-b433503375fc.png)</details>

<details><summary>Highlighted suggestions</summary>

![Screen Shot 2021-09-16 at 2 24 31 PM](https://user-images.githubusercontent.com/136959/133679027-8cfa048f-e7c7-48fa-be28-ddcde4dea072.png)</details>

## Tasks

- [ ] Update autosuggest field to highlight matches
- [ ] Enable feature within the `ui:options`
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
