### ISSUE TITLE
[FE] Refine validation error message

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30050]
## User Story

As a veteran, I should get better error messaging around why validation failed. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The API is returning the reason why validation failed, we should display the reason to the veteran why the validation failed

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Confirm the error message and structure from the API 
- [ ] Get messaging content from design. 
- [ ] Add messaging for Last name/last 4
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
This is tied to the restrict retries ticket

**Comment by mdewey** [comment]
Closing, this is covered by the retry work and not a feature we want to do currently
