### ISSUE TITLE
[FE] Phone number display bug

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30058]
## User Story

As a veteran, I should see a phone number that makes sense, so I know what I am calling 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The platform-level component doesn't support ext. Figure out why and maybe fix it? 
![image](https://user-images.githubusercontent.com/1793923/133682111-06843956-1917-43d5-afa6-c8c697106ba7.png)

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Investigate the problem
- [ ] address the fix
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
- Component docs: https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers
- util for parsing phone numbers: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/utils/phoneNumbers.js
- usage example with extension: https://github.com/department-of-veterans-affairs/vets-website/blob/012af4d099fdb59dc9d1755171d2420e1e2e9c24/src/applications/facility-locator/components/search-results-items/common/LocationPhoneLink.jsx#L16
- Slack thread with some background: https://dsva.slack.com/archives/C5HP4GN3F/p1607546529152700

**Comment by mdewey** [comment]
![Screen Shot 2021-12-16 at 10.08.25 AM.png](https://images.zenhubusercontent.com/5ecebb879a043b865f6cb5b6/1a0033df-e924-4f2b-8e47-fda79b25c6d8)

No longer needed since we are not showing phone numbers anymore

**Comment by julieadair1** [comment]
Closing per @mdewey comment above.
