### ISSUE TITLE
AutoSuggest field custom matching

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30061]
## Description

The AutoSuggest field uses the fast Levenshtein distance function to "fuzzy" match results based on the input length. The resulting suggestions are not always optimal for our needs. I'd like to add a `ui:option` custom matching function that overrides the built-in fuzzy match.

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6006

## Tasks

- [ ] Add `ui:option` custom matching function
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
We need to improve the core algorithm for finding matches.
