### ISSUE TITLE
 KPI Dashboards: Iterate on Standardized KPI Dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30065]
## Problem Statement 
Platform Analytics has built scalable KPI dashboards for VFS teams with Forms, Content, and Search VFS products. The current data on the KPI dashboards doesn't necessarily tell the _entire_ user journey (which is because of, but not limited to, the dashboard only containing Google Analytics data). KPI dashboard customers are also looking at the dashboards once a month, but most are not coming back to their dashboards more than once a month or sharing data directly from their dashboards in stakeholder meetings.

Separately, there are several VFS products that do not fall under Forms, Content, or Search products; KPI dashboard creation for these products is slow, and those VFS teams are not receiving their dashboards fast enough.

How might we iterate on the KPI dashboards so that more VFS teams are incentivized use their dashboards for VA.gov product decision making more often?

## Hypothesis or Bet
If we iterate on our KPI dashboards using insights from our backlog, feature requests, and user research, then we expect to be alleviate customer pain points with incomplete data on their KPI dashboards and more VFS teams will come back to their dashboards more often.

## We will know we're done when... ("Definition of Done")
- [ ] Platform Analytics has synthesized user research and feature recommendations, 
- [ ] Platform Analytics has collaborated with the Operations and Backend Tools on if we should pull website performance data into BigQuery and Domo, and if so, how 
- [ ] Platform Analytics has built the iterations recommended from the backlog, feature requests, and user research

## Known Blockers/Dependencies 
_Risks_
- Inability to standardize more complex data
- BI Tooling limitations
- Lack of time - holidays

## Projected Launch Date
End of Q4 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline+-+WIP) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan]().

### Documentation
* **`PRODUCT_NAME`**: KPI Dashboards
* **[Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline+-+WIPe**
* **README**: [link](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html)
* **User Guide**: [link](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **[Success metrics](https://va-gov.domo.com/page/514439234)**
* **[Release plan](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/30066)**

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by michelle-dooley** [comment]
Ready to close after data dictionary updates.  Will open new for future iterations/v2
