### ISSUE TITLE
Content updates to VA help to avoid foreclosure page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30068]
## Issue Description
Stakeholder Raleigh Contreras has updates to the [VA help to avoid foreclosure](https://www.va.gov/housing-assistance/home-loans/trouble-making-payments/) page.

We need to input these changes and update for plain language and VA's voice and style. 

[https://app.zenhub.com/files/133843125/7b7cb31d-9daf-4f81-b171-09fcc49316bd/download](https://app.zenhub.com/files/133843125/7b7cb31d-9daf-4f81-b171-09fcc49316bd/download) 

## Tasks
- [x] Review updates and rewrite for plain language (Beth)
- [ ] Send updates to stakeholder for approval (Beth/Randi)
- [x] Review and publish (Randi)
- [x] Notify stakeholder changes are live (Randi)

## Acceptance Criteria
- [x] Updates are live on the site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here are my edits to Raleigh's request:

**What should I do if I'm having trouble paying my mortgage?**
2nd paragraph:
Keep our first sentence as is. It's long enough. Then add: You can also email us at LGYLANational.VBACO@va.gov (please include the name and address on the loan).

**How can I avoid foreclosure?**
Text to add to Nos. 5 and 6 (we don't have run-in notes often, but we'll do it here... and FYI that I didn't have any changes to the text they sent us for this except that it shouldn't be italicized):
**Note:** This option could result in a loss or reduction in your future home loan benefit. Contact a VA loan technician at 877-827-3702 for more details.

**What if I need help or more information?**
Please let Raleigh know that we don't think we need to link to VCL from this location since a prominent link to it is at the top of the page (and every page on VA.gov).

**Info alert on this page**
Go ahead and change this link.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Under How can I avoid foreclosure?

Let's move some things around so that the phone numbers aren't so clustered.

We'll bring up that last line of text that's currently appearing after No. 6 to the text immediately under the H2. So:

**How can I avoid foreclosure?**
There are 6 general ways you can try to avoid a foreclosure. Our VA loan technicians can help you figure out which option is best for you. Contact a VA loan technician at 877-827-3702.

**These are your options for trying to avoid foreclosure:**

Then there'll be no text appearing beneath this list of 6 options. And you can mention to the SMEs that we moved that we moved that text up higher in that section of content.

**Comment by RLHecht** [comment]
These changes were made and I published the page minus the change to the alert, which we are still working through.

**Comment by RLHecht** [comment]
Changes are live and I emailed Raleigh to let him know. Since we are not changing the link in the on-page alert we asked him if there is any home loan info that needs to be added to the coronavirus FAQs page. If there is, we can follow up with a separate ticket. Closing this one.
