### ISSUE TITLE
Redirect and archive Add or Remove Dependents page in disability

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#30069]
## Issue Description
These pages are duplicative (https://www.va.gov/disability/add-remove-dependent/ and https://www.va.gov/view-change-dependents/. We need to:

- Redirect https://www.va.gov/disability/add-remove-dependent/ to https://www.va.gov/view-change-dependents/
- Update the link in the disability hub to https://www.va.gov/view-change-dependents/

---
## Tasks
- [x] - Redirect https://www.va.gov/disability/add-remove-dependent/ to https://www.va.gov/view-change-dependents/ **[Kelson]**
- [x] - Update the link in the disability hub to https://www.va.gov/view-change-dependents/ **[Selina]**
- [ ] - Archive add or remove dependents page in disability: https://www.va.gov/disability/add-remove-dependent/ **[Selina]**

## Acceptance Criteria
- [x] Redirect has been implemented
- [ ] Add or remove dependents page in disability is archived and unreachable
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9967 @lunascoop is this redirect to go live now?

**Comment by lunascoop** [comment]
Hi @kelsonic you can redirect this now. Thanks!

**Comment by kelsonic** [comment]
Redirect live on prod: https://www.va.gov/disability/add-remove-dependent/

**Comment by brianalloyd** [comment]
Thanks Kelson,  validated and closing in support.

**Comment by lunascoop** [comment]
@brianalloyd I need to do more work on this ticket so that I can archive the add remove dependents page. I'll reopen but no more work is needed from the PW team. thanks!

**Comment by brianalloyd** [comment]
Oh man, sorry @lunascoop thanks for reopening and for the additional context.

**Comment by RLHecht** [comment]
Thanks @lunascoop I published all of these except for the cloned 2021 past rates page, which we can publish when we create the new 2022 page in December.
