### ISSUE TITLE
[FE] Trim the lastName

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30074]
## Related Documentation
> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

The user data sometimes has extra spaces. Trim those extra spaces. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Trim the spaces. 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
