### ISSUE TITLE
[Lighthouse UX Toolkit] Add S3 buckets variable and any buckets needed

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#30079]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The UX Toolkit requires S3 buckets to work.

---
## Tasks
- [ ] Add any buckets needed in Terraform
- [ ] Add any permissions needed to the ux-toolkit GHA user and team marmoset
- [ ] Assist in getting the S3 bucket variables needed into Parameter Store and into the manifest as secrets/variables

## Acceptance Criteria 
- [ ] Lighthouse UX Toolkit has S3 buckets created, configured, and available to their application running in EKS

**Comment by jbritt1** [comment]
Not sure that `lighthouse-ux-toolkit` is a currently ongoing project. Closing this, but happy to reopen if the need should resurface.
