### ISSUE TITLE
[Datadog] Enable synthetic monitoring for platform owned services

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30088]
@mydesignrocks commented on [Tue Sep 14 2021](https://github.com/department-of-veterans-affairs/devops/issues/9937)

## Description
Create datadog synthetic monitors for platform owned services
loki 
grafana 
promtail
traefik
more to be added

## Technical notes
Solution overview: Identify loki end points for health checks and use terraform module for datadog synthetic monitoring
---
## Tasks
- [x] Identify health endpoints for loki and grafana
- [x] write terraform code for creating datadog synthetic monitors

## Definition of Done
- [x] alert notification sent to slack when loki or grafana end points are not accessible

**Comment by jhouse-solvd** [comment]
Individual issues will be created to track the implementation on a per-service basis. 

Will leave this open until those are linked in. This can then be closed.

**Comment by jbritt1** [comment]
Synthetics added for ops owned services: https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog/catalog/synthetics. Can we close?

**Comment by jhouse-solvd** [comment]
Closing. 

_note: @mchelen-gov: let's open a new issue if anything additional is needed_
