### ISSUE TITLE
[Support Slackbot] Decommission the Heroku support slackbot

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30089]
@dginther commented on [Fri May 14 2021](https://github.com/department-of-veterans-affairs/devops/issues/9163)

Description:
Once the slackbot is deployed in EKS, we will need to decommission the Heroku version.

Tasks:
- [ ] Determine order of launch/decommission we need to perform in order to minimize downtime
- [ ] Document the above step in this ticket
- [ ] Perform the steps required to decommission the Heroku version
- [ ] Verify that the new EKS version is being utilized by the support workflows in Slack

**Comment by jbritt1** [comment]
Reassigning to @zachclarity and Platform-SRE team as we feel this is more fitting for that board vs the Platform-Infrastructure team's backlog.

**Comment by powellkerry** [comment]
This application has been moved to the Heroku enterprise account. We will evaluate if this meets the needs of the support bot before attempting to move it to AWS/EKS
