### ISSUE TITLE
[App Hosting and Deployment] Implement Argo rollouts for platform-owned services

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30085]
@mydesignrocks commented on [Tue Sep 14 2021](https://github.com/department-of-veterans-affairs/devops/issues/9939)

## Description
Plan is to start implement blue green deployment strategy for platform owned services to avoid downtime during deployment/upgrades
1. loki
2. more to come

## Technical notes
convert deployment files to rollout files for each component in loki
change the ingress controller to point stable or active version of loki service
---
## Tasks
- [ ] extract the helm chart from tar file
- [ ] update the template files to use argo rollouts
- [ ] update the template to point to both stable and active versions during blue green rollouts
- [ ] test the changes to check the traffic is failover and failed back to between blue and green deployments

## Definition of Done
- [ ] rollout changes without downtime

**Comment by jhouse-solvd** [comment]
This might be at a good stopping place for now. Let's discuss and see what we can document and share and identify for the future.

**Comment by jhouse-solvd** [comment]
The scope and purpose of this issue is not clear. My recommendation is to close this and open a new issue, based on product requirements. 

Closing.
