### ISSUE TITLE
upgrade loki and its container docker images

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30086]
@mydesignrocks commented on [Tue Sep 14 2021](https://github.com/department-of-veterans-affairs/devops/issues/9938)

## Description
build and deploy docker images for the below:
- loki 2.3.0
- nginx 1.21-alpine
- promtail 2.3.0
- memcached 1.6.10-alpine
- Memcached-exporter v0.9.0.

## Technical notes
 get the stable version of the above listed images and push them to ECR. 
roll out the changes to argocd to deploy on eks
---
## Tasks
- [x] update the image versions for the above to build the new images and push them to ECR
- [x] update the manifest file [env]-values.yaml for loki to use the above images 

## Definition of Done
- [x] loki should be functional with the image versions listed above

**Comment by jbritt1** [comment]
The referenced versions are all reflected within `version.txt` files in the [vsp-infra-loki repo](https://github.com/department-of-veterans-affairs/vsp-infra-loki) as well as images currently existing with the [ECR repo](https://console.amazonaws-us-gov.com/ecr/repositories/dsva/loki?region=us-gov-west-1).
