### ISSUE TITLE
Reorganize Contact us page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30095]
## Issue Description
We reorganized the [Contact us](https://www.va.gov/contact-us/) page for better flow. We moved the R&S information out of the featured content block and reworked it into the page. 

## Tasks
- [x] Rework Contact us page for better organization
- [x] Review and publish

## Acceptance Criteria
- [x] New Contact us version is live on the site

**Comment by RLHecht** [comment]
This page is published.

**Comment by RLHecht** [comment]
Page live. closing ticket.
