### ISSUE TITLE
Continue-on-error for slack notification in workflows

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#30099]
## Details

It was brought up in [Slack](https://dsva.slack.com/archives/CQH357ZTP/p1631891203097600) that a job may fail due to Slack notification in Github Actions. Jenkins has a try/catch implemented to not fail flow in the event it occurs. We want something similar in place to ensure the flow does not fail.

Github Actions natively uses `continue-on-error` for this situation. We currently have it in place for [testing-reports](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/continuous-integration.yml#L635) as we don't wish our CI to fail in the event fails.

Rather than apply it to a job level, we can specifically apply it to `steps` that call `Slack Notification`

Examples of flows failing due to Slack failing to send notification:

https://dsva.slack.com/archives/C024DUC9S1K/p1631815796002200
https://dsva.slack.com/archives/C024DUC9S1K/p1631815796002200

## Tasks
- [x] Apply `continue-on-error` to slack notification in CI workflow for `vets-website`
- [x] Apply `continue-on-error` to slack notification in CI workflow for `content-build`
- [x] Apply `continue-on-error` to slack notification in daily deploy workflow for `vets-website`
- [x] Apply `continue-on-error` to slack notification in daily deploy workflow for `content-build`
- [x] Apply `continue-on-error` to slack notification in content-release workflow for `content-build`
- [x] All workflows continue to work as intended

**Comment by oseasmoran73** [comment]
PR has been merged into respective repos
