### ISSUE TITLE
Platform Website — Research: Validate PW effectiveness in completing top tasks

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#30100]
## Problem Statement 

Platform teams have spent 2021 Q2 and Q3 contributing to the Platform website.  But, we aren't sure if the contributed content is actually helping our customers more quickly build their applications.

_HMW validate if the contributed content is helping customers build their applications?_

## Hypothesis or Bet

If we gauge how well participants are able to accomplish Some Top Task(s) given relevant documentation, then we will be able to measure the effectiveness of Platform website's contributed content.

## We will know we're done when... ("Definition of Done")

* We have a list of points to address when writing guidance
  * The guidance: Guide teams to gauge their content's effectiveness
* We have a yes/no answer to the question "Can a customer accomplish Some Top Task with only the documentation?"
  * Some Top Task = a top task for each user type: designer, PM, developer

## Known Blockers/Dependencies 
* Finding and scheduling VFS participants
* Service Design to 
  * Gut check the top task we are choosing to validate
  * Gut check our research approach
* The top task's doc's owner.  For example, if we are studying a Collab Cycle task, we should be in regular sync with Product Support

## Projected Launch Date
End of 2021 Q4

## Launch Checklist

<details>

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

</details>

## Required Artifacts

<details>

### Documentation
* **`PRODUCT_NAME`**: Platform website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**:  Platform website [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README & User guide**: [Contributing to the Platform website guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)

### Testing

N/A - this is a research initiative

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
  - Time to complete X Task
  - Number of tasks 
  - Number of participant questions during study
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/30106

</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by lianilychee** [comment]
Closing, since this work is pivoting to https://github.com/department-of-veterans-affairs/va.gov-team/issues/33511
