### ISSUE TITLE
Update ID.me Login to combine LOA1 & LOA3 Requests

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#30116]
## Issue Description
The ISAM team has [recently updated SSOe iDev to handle Authn Context comparisons](https://dsva.slack.com/archives/CSFV4QTKN/p1629401403109800), enabling us to attempt to authenticate an ID.me user first by LOA3, and then by LOA1 if the account is not LOA3. vets-api needs to update its initial request to ISAM to include both Authn contexts for ID.me logins, as well as modify the `saml_callback` workflow to parse the returned Authn contexts and remove the LOA3 upleveling attempt that currently occurs with ID.me logins.

---
## Tasks
- [x] the `render_login` workflow that produces the SAML headers sent to ISAM is updated to include both LOA1 & LOA3 and uses a "maximum" AuthnContext Comparison instead of the default "exact":
```
<samlp:RequestedAuthnContext Comparison="minimum">
	<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/1/vets</saml:AuthnContextClassRef>
	<saml:AuthnContextClassRef>https://eauth.va.gov/csp?Select=idme3</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
```
- [x] the `saml_callback` workflow is updated to properly parse the new SAML returned for LOA1 & LOA3 ID.me users
- [x] affected unit tests are updated

## Acceptance Criteria
- [x] ID.me/LOA1 users will go through the authentication process once when signing into va.gov
- [x] ID.me/LOA3 users will go through the authentication process once when signing into va.gov

**Comment by bramleyjl** [comment]
@jscanish and I worked together to update the SAML headers we send to ISAM, the full block looks like this:
```
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="http://localhost:3000/v1/sessions/callback" Destination="https://int.eauth.va.gov/isam/sps/saml20idp/saml20/login" ForceAuthn="true" ID="_3d9b8510-dcbc-44d1-9180-a8e7bfd57937" IsPassive="false" IssueInstant="2021-09-17T17:55:00Z" Version="2.0"><saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://ssoe-sp-localhost.va.gov</saml:Issuer>

<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>

<samlp:RequestedAuthnContext Comparison="maximum">

<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/3</saml:AuthnContextClassRef>

<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/1/vets</saml:AuthnContextClassRef>

<saml:AuthnContextClassRef>https://eauth.va.gov/csp?Select=idme3</saml:AuthnContextClassRef>

</samlp:RequestedAuthnContext>

</samlp:AuthnRequest>
```

With these headers we get passed through to ID.me, but then encounter a 500 error after submitting the login form with an LOA3 ID.me account's credentials.![Screenshot from 2021-09-17 12-46-35.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/c88e60ac-b073-4b73-a1f2-3136511de209)

**Comment by bramleyjl** [comment]
After some updated guidance from the ISAM team on how to configure the SAML headers, mainly to put the LOA 1 over LOA3, this is what the updated headers look like:
```
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="http://localhost:3000/v1/sessions/callback" Destination="https://int.eauth.va.gov/isam/sps/saml20idp/saml20/login" ForceAuthn="true" ID="_0a7d5e2f-83bd-4ae9-8cea-f3d7f47176ce" IsPassive="false" IssueInstant="2021-09-22T19:13:38Z" Version="2.0">
	<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://ssoe-sp-localhost.va.gov</saml:Issuer>
	<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>
	<samlp:RequestedAuthnContext Comparison="maximum">
		<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/1/vets</saml:AuthnContextClassRef>
		<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/3</saml:AuthnContextClassRef>
		<saml:AuthnContextClassRef>https://eauth.va.gov/csp?Select=idme3</saml:AuthnContextClassRef>
	</samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

**Comment by bramleyjl** [comment]
SAML headers have been updated again:
```
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="http://localhost:3000/v1/sessions/callback" Destination="https://int.eauth.va.gov/isam/sps/saml20idp/saml20/login" ForceAuthn="true" ID="_bb9c64d7-dfd5-48f7-bb02-ba43ae5d2c21" IsPassive="false" IssueInstant="2021-09-23T17:03:03Z" Version="2.0">
<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://ssoe-sp-localhost.va.gov</saml:Issuer>
<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></samlp:NameIDPolicy>
<samlp:RequestedAuthnContext Comparison="minimum">
<saml:AuthnContextClassRef>http://idmanagement.gov/ns/assurance/loa/1/vets</saml:AuthnContextClassRef>
<saml:AuthnContextClassRef>https://eauth.va.gov/csp?Select=idme3</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

The request is successfully carried to ID.me and I am able to authenticate and be passed back to VA.gov as a logged-in user. However, the SAML response from ISAM does not carry the expect LoA3 status, instead my LoA3-enabled account is only logged in as LoA1 - ie the current expected behavior.

**Comment by nsoutouras** [comment]
**Carries to Sprint 62.  Blocked by ID.me**

**Comment by bramleyjl** [comment]
As of this morning (10/4) we are still blocked - the SAML response from ISAM is still returning an LoA1 status for an LoA3-enabled account.

**Comment by bramleyjl** [comment]
vets-api is still receiving LoA1 for an LoA3 account and has to upcert normally - no changes.

**Comment by joeniquette** [comment]
@bramleyjl IAM informed us today that dev is working for this functionality as of 11/2 1500 ET. Please work with me in the AM to perform tests. SQA is being planned to be rolled out soon.

**Comment by bramleyjl** [comment]
Removing existing upcert functionality is not necessary at the moment and could be disruptive due to the incoming Login.gov implementation which relies on the same functionality. After Login.gov has also switched to using the "minimum" headers this area of the code can be refactored, as covered in #32605

**Comment by bramleyjl** [comment]
We believe ISAM is incorrectly interpreting vets-api's IAL2 call and returning the IAL1 user it already has from the first vets-api call instead of making a call to Login.gov for the upleveled IAL2 user, this is preventing us from using the `ForceAuthn = false` headers to upcert a user without authenticating again. IAM has been provided with an example of the calls made and is investigating the issue.

In addition, I will to refactor the `verify_url` code block to no longer rely on the authn_context passed back by ISAM, this will resolve the issue of the unexpected authn_context value. ISAM's response already includes a `type` attribute that denotes the specific CSP and whether or not it was a 2FA, this is a better attribute to use to derive the `verify_url` SAML headers from.

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/8473
