### ISSUE TITLE
Add Datadog Terraform Configs to Terraform GHA Filters

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30117]
## Description
We need to add the Datadog "environment" in Terraform to the filters/watchlist of the Terraform GHA automation

## Background/context 
The [Terraform GHA](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/terraform.yml) has specific path filters that tell it which directories to watch and plan from. We need to add the newer Datadog one to the list if we want these automated Terraform plans for changes to the files that exist there.

---
## Tasks
- [ ] Add Datadog dir to filters for the Terraform GHA to watch
- [ ] Add the logic that tells the action what actions to take against files in that dir/path

## Acceptance Criteria 
- [ ] Terraform GitHub action automatically plans changes to the Datadog dir/env/path

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
