### ISSUE TITLE
[PM] Profile: Scope/prioritize reminder to update mailing address if you've updated home address

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30112]
## Background
Per documentation shared with us via VA Profile, it's been brought to our attention that often times a Veteran will update their residential address but forget to update their mailing address (or vice versa). We received a request from VA Profile to create a prompt, reminder or hint text of some sort such that when the Veteran updates one of those addresses they are reminded that they may need to update it in other locations to ensure proper delivery of prescriptions, correspondence, and other VA communications.

Needs further discussion internally to determine scope of work.

## Tasks
- [x]  Meet with Stakeholders, PO
- [x] Determine root cause of issue
- [x] Determine scope of change
- [x] Define tasks

**Comment by andaleliz** [comment]
Hey @ajakabcin! Thanks for creating this. What's the scope of this particular ticket? Is it just to create a mock-up, or do I go through the whole design process (involve content, FE, etc)?

**Comment by ajakabcin** [comment]
@andaleliz I think still TBD on the scope. I added a label for "needs business decision" to indicate that and I created a new label for us to denote requests from external teams (AE-ext-request) to start tracking inbound requests. I'll add a note to the body indicating that we need to have a discussion about scope as well.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO updating assignees on this since AJ is no longer focusing on profile, and she's on leave. I'll forward you an email thread that will tell you what I know :)

**Comment by andaleliz** [comment]
I'm also updating the ticket name and removing myself since this isn't really ready for design yet.  If it helps w/ scoping, LOE, a couple of ideas off the top of my head are:
- a confirmation modal to let people know
- a checkbox in the address form that says something like "My home and mailing address are the same" or "Apply this update to my home/mailing address too"

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @andaleliz !

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz just adding to your above comments that it's probably important to specifically call out that the mailing address is where their prescriptions will be sent (so they understand the significance), and that they need to verify that it is correct.

**Comment by Samara-Strauss** [comment]
We need to talk to this team again to fully understand the problem. We already say in the profile that we use this information to determine where prescriptions go. We need to understand scale and specifically where confusion is happening before we determine a solution.

**Comment by Samara-Strauss** [comment]
OK, we just met with the team and walked through the problem, so I'm all caught up. It sounds like this is the flow that's the problem:

- Someone updates their home address
- They don't realize they need to update their mailing address, and then mail/prescriptions don't go to the right place

Liz listed the following potential solutions above:

- a confirmation modal to let people know **This is something to consider and likely easy to implement, just remember it will need to go after any address validation flows**
- a checkbox in the address form that says something like "My home and mailing address are the same" or "Apply this update to my home/mailing address too" **This is also something to consider, but the Home address field already has a checkbox at the top that says "My home address is the same as my mailing address", which populates the home address fields with the existing mailing address. So, we'd want to consider how any additional check boxes might work or conflict with what we already have**.

And Marci mentioned the following solution in a DM on Slack:

- Clear messaging in the home address field that people need to update their mailing address in order to receive mail/prescriptions

And there are probably more things we could do that I'm not thinking of off the top of my head. Thoughts, @MarciMcGuireGCIO @andaleliz?

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @Samara-Strauss.  The only other suggestion I have is that is should be very clear which direction the copy will happen.  The current language says "My home address is the same as my mailing address" which is a little vague.   

I could envision someone being hesitant to check that because they don't know if it's going to copy the Mailing address above into the Home address or vice-versa.

**Comment by Samara-Strauss** [comment]
> The current language says "My home address is the same as my mailing address" which is a little vague. I could envision someone being hesitant to check that because they don't know if it's going to copy the Mailing address above into the Home address or vice-versa.

Given that people are in the home address field when they see this message, I would hope that was clear that the update would happen in the home address field. But it's been years since we user tested this and could be worth validating again or updating the language to clarify further.

**Comment by andaleliz** [comment]
I feel like a dummy but I did not realize this checkbox was already in the home address field. Since that's the case I think it'd be a great idea to conduct some usability testing because we need to understand why that checkbox isn't working for people.

Did they share any data points? For example, do we know how many people update an address and check this box vs those that don't, and then experience the address mismatch problem? Are we sure the updates where this mismatch is taking place is due to updates made directly IN our profile?

Is it possible that people are updating their home address in applications somewhere, and that data sent back to VA Profile API? If that is a possibility, it could warrant some other solution like detecting the difference when a user visits the contact info page and displaying a warning at that point, rather than during the update process.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz I didn't see it either until was looking at something else on Staging yesterday!  

@Samara-Strauss may have caught something that I missed, but here are my takeaways - They did not give any specific numbers of occurrences (just said "several cases"), and mentioned a couple of specific instances.   

They also didn't provide definitive evidence that this was only happening a direct result of changes being made in the VA.gov profile, but Elizabeth said that some people are making an assumption that it will change the other address when they change their mailing address there.   One attendee stated that she actually thought that it automatically updated the other field as well.   

Their overall concern seemed to be setting user expectations so they understand exactly will and won't happen when they make a change, and how failing to update their mailing address could impact receipt of correspondence or prescriptions.

**Comment by andaleliz** [comment]
Thanks Marci, that's helpful. I still think user research would be a good next step to understand how we might better prevent this error in profile.

**Comment by MarciMcGuireGCIO** [comment]
That definitely sounds reasonable to me.  We're just guessing at why people are struggling otherwise.

**Comment by Samara-Strauss** [comment]
> I feel like a dummy but I did not realize this checkbox was already in the home address field. Since that's the case I think it'd be a great idea to conduct some usability testing because we need to understand why that checkbox isn't working for people.

I don't know that we need user research. The "my home address is the same as my mailing address" checkbox is on the home address form, and will update the home address form with whatever is in the existing mailing address form. The problem we talked about is not syncing up the home address with the existing mailing address, but with updating the mailing address _after_ the home address has been updated, hence the suggestion to remind people after they've updated the home address to also go update the mailing address.

Does that make sense? So, the issue has nothing to do with the existing checkbox, hence why I don't think usability testing is needed because the checkbox isn't causing any problems.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss sounds good.  So the scope is designing and implementing an alert or some less obtrusive message when someone updates an address.   I feel like this action should occur regardless of the address updated.  That ensures consistency and decreases the chances of them forgetting to keep their addresses synced up if the mailing & home are the same.  Thoughts @Samara-Strauss & @andaleliz ?  Also - will Liz be working on this or Christina?

**Comment by Samara-Strauss** [comment]
>  So the scope is designing and implementing an alert or some less obtrusive message when someone updates an address.

The scope is figuring out the right design solution for this issue, but yes, that might be some sort of messaging before or after updating the home address.

> Also - will Liz be working on this or Christina?

No, Liz can cover this one.

**Comment by andaleliz** [comment]
>The "my home address is the same as my mailing address" checkbox is on the home address form, and will update the home address form with whatever is in the existing mailing address form.

@Samara-Strauss thanks for clearing this up for me. It took me reading this aloud to get through my head what is happening here and I can now see why this may be problematic, without user research. Depending on the solution we land on, maybe we'll need to do some research after the fact to validate it works for people. Marci will spin up some tickets for me to work on.

>They did not give any specific numbers of occurrences (just said "several cases"), and mentioned a couple of specific instances.
> They also didn't provide definitive evidence that this was only happening a direct result of changes being made in the VA.gov profile, but Elizabeth said that some people are making an assumption that it will change the other address when they change their mailing address there. One attendee stated that she actually thought that it automatically updated the other field as well.

In this case, I think our current UX warrants revisiting because it can certainly be made more clear. However, I think when we get requests from teams to make changes in profile, it'd be super helpful to have data to validate their request. "Several cases" is vague and will be hard to correlate our effort to improvements.  This will be a relatively small change but sounds like it _could_ be impactful. I would love to explore how we measure the success of the changes we make to know whether or not we're helping Veterans with this problem.  Could we check with them about any data points we can use as a baseline?

**Comment by andaleliz** [comment]
Oh, I also realize that there are probably analytics somewhere that can help us understand how often both addresses get updated in the same session, and how often that checkbox is used. That might be useful information. @MarciMcGuireGCIO can you add a task in my ticket to look at analytics for any helpful metrics? Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz - done!  Here is some GA data on how often addresses are changed.  Don't know about the checkbox, but there should be an action we can track.  https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/

**Comment by MarciMcGuireGCIO** [comment]
Epic for this work: #33732; scope is defined and prelim tasks listed in the epic.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO and @Samara-Strauss, aside from prescriptions and correspondence, are there other things the mailing address is used for that the stakeholders brought up (or you are aware of)? This will be helpful to know as we work on content.

**Comment by Samara-Strauss** [comment]
It's used for all correspondence with the VA. Considering they still need to send written details for pretty much everything, that's *a lot* of stuff. I don't have a more detailed list than that, but I don't know that we need one beyond prescriptions + literally all other correspondence.
