### ISSUE TITLE
Platform orientation for 4 new VFS Teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#30115]
## Description
There are 4 new teams joining VA.gov and need orientation from Platform in order to get up and running. The 4 new teams are:

1. Check-in experience (Contract team: Agile 6) - Primary OCTO POCs: Patrick Bateman & Stephen Barrs. 
_A note on this one: In case you're feeling deja vu, yes there is a GCIO doing check-in team now. That GCIO team is effectively merging with the A6 check in team. For Team of Teams, there should only be 1 check-in update from this combined A6 & GCIO team._ 
2. Health apartment (Contract team: Mo Studio) - Primary OCTO POC: Meg Peters 
3. Clinical decision support apps (Contractor: Coforma & Thoughtworks) - Primary OCTO POC: Kaeli Yuen 
4. TEVI (Contractor: Oddball) - Primary OCTO POC: Shane Elliott 

In order to make this process more efficient, we would like to try and onboard all 4 teams at once, meaning 1 orientation meeting (as listed below) will support all 4 teams.

Note: testing this new template out to better track new team onboarding. Please feel free to edit, comment or add helpful info if necessary.

## Tasks

- [ ] Host the following orientation meetings:
   - [ ] General Orientation @shiragoodman  (for all)
   - Date/time: September 22, 4:00pm ET
   - [ ] PM Orientation @shiragoodman (for PMs)
   - Date/time:   
   - [ ] Design Orientation @allison0034 or @naomimarcussen  (for designers and researchers)
   - Date/time:
   - [ ] Front-end orientation @meganhkelley (for front-end engineers)
   - Date/time:
   - [ ] Back-end orientation @jeff2d2 (for back-end engineers)
   - Date/time:
   - [ ] Analytics Intro @joanneesteban (for PM and front-end engineers)
   - Date/time:
   - [ ] Accessibility/508 intro @noahgelman (for PM, designers and front-end engineers)
   - Date/time:
   - [ ] QA intro @pjhill (for PM, front-end and back-end engineers)
   - Date/time:
   - [ ] ATO intro @fowusu2 (for PM and engineering lead)
   - Date/time:
- [ ] Create VFS Orientation Epic github ticket and assign to PM or PO:
   - [ ] Check-in experience
   - [ ] Health apartment
   - [ ] Clinical decision support apps
   - [ ] TEVI
- [ ] Add new teams and team members to [VFS Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=877379155)

## How to configure this issue
- [ ] **Labeled with `vsp-product-support` Team**
- [ ] **Orientation is complete and new VFS team is operating in their development workflow**

**Comment by shiragoodman** [comment]
Quality Assurance Orientation availability:

- Tuesday, 9/28 at 1PM ET, 2PM ET, or 3PM ET 
- Wednesday, 9/29 at 2PM ET
- Thursday 9/30 at 12PM ET

**Comment by noahgelman** [comment]
Accessibility Orientation Availability: 
Tuesday, 9/28 at 4PM ET
Thursday, 9/30 at 2PM ET or 3PM ET

**Comment by shiragoodman** [comment]
@joanneesteban @jeff2d2 @meganhkelley @naomimarcussen @allison0034 @fowusu2  - reminder. Please post your availability for hosting your teams orientation. I'd like to get orientation scheduled ASAP. Please pick times in the afternoon to accommodate west coast folks. thanks.

**Comment by joanneesteban** [comment]
Analytics Orientation Availability (EST):
Thursday, 9/23 @ 1-1:30pm, 2:30-3pm, 4:30-5pm
Friday, 9/24 @ 12-12:30pm, 12:30pm-1pm, 3-3:30pm, 3:30pm-4pm

**Comment by jeff2d2** [comment]
Travis (who does the BE orientation) edited the description with a date/time

**Comment by shiragoodman** [comment]
@thilton-oddball is it 30 min or 60 min?

**Comment by timwright12** [comment]
Frontend Tools Availability:
Mon 9/27 10:30am-11:30am ET
Mon 9/27 2pm-5pm ET
Wed 9/29 2pm-3pm ET
Thurs 9/30 1pm-2pm ET
Fri 10/1 1pm-3pm ET

**Comment by shiragoodman** [comment]
hey @joanneesteban @naomimarcussen @allison0034 @thilton-oddball @timwright12 @pjhill @noahgelman  - orientation dates have been scheduled. See the updated dates above. 

Please send me your Zoom (via DM on Slack) for the timeslot above. I will schedule the meeting, but I will include your Zoom info since you are the host. 

Let me know if you have any questions. Thanks!

**Comment by peggygannon** [comment]
@shiragoodman can you also add leah.delacosta@adhocteam.us to upcoming orientation sessions? She is the new VAOS team member.

**Comment by shiragoodman** [comment]
@fowusu2 this ticket is mostly complete, however the last item is ATO orientation. The new teams have been assigned tickets that also communicate that they'll need the ATO orientation. Do you want to reach out to the leads of these teams and schedule?
