### ISSUE TITLE
[FE] Disable autocorrect and spellcheck on LastName field

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#30127]
## User Story

- As a Veteran, I wish to not have autocorrect enabled on the LastName field, so that my last name is not modified and I may complete the check-in process.
- As a Veteran, I wish to not have spellcheck enabled on the LastName field, so that my last name is not shown as incorrect and potentially causing confusion.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocorrect
- https://caniuse.com/?search=spellcheck

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Text in the LastName field is not autocorrected in Safari
- [ ] Misspelled text in the LastName field is not highlighted 
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
UX review happened in slack: https://dsva.slack.com/archives/C022AC2STBM/p1632408155062000?thread_ts=1632337879.046900&cid=C022AC2STBM
