### ISSUE TITLE
[FE] Use number input type on Last4 field

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#30129]
## User Story

As a veteran, I wish to be presented a numeric keypad when I fill the Last4 field, so that I cannot enter non-numeric characters and fail to complete the check-in process.
As a veteran, I wish to be presented a numeric keypad when I fill the Last4 field, so that I can easily enter numbers with a dedicated UI.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

Hypothesis: filling out the last 4 field will be easiest if Veterans are presented with a numeric keypad rather than the standard QWERTY keyboard.

## Implementation

https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] A numeric keypad is presented when filling the Last4 field on mobile devices
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
@acrollet thanks! Was there a separate ticket associated to adding that to the component library? Basically, I was working on a monthly report yesterday of the work completed and I have to tie everything to github tickets for showing completed work, so I wasn't able to show that we had worked on this.
In the future, could we open a ticket for that kind of work to track the time and effort, even if it's not a finalized delivery of something in the apps we're working?

**Comment by acrollet** [comment]
@jparker0425 nope, it also tracks the work to improve the UX on the last4 field, that PR is now ready for review [here](https://github.com/department-of-veterans-affairs/vets-website/pull/19058).
