### ISSUE TITLE
[DESIGN] Update check-in poster based upon Phase 2 usability and Martinsburg visit findings

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#30148]
Based upon the research findings from the Martinsburg visit ([draft research report](https://dsva.slack.com/archives/C022AC2STBM/p1631824953375300)) and Phase 2 Usability study ([Synthesis document - report coming soon](https://app.mural.co/t/vsa8243/m/vsa8243/1629923298341/3f6e350a2b322a4c77a92b30ae0dac25e42439d5?sender=uc940f53ad96ac0203d6d3631)), the following UX/UI updates are recommended to be made to the poster:

## Tasks
- [ ] Explore new visuals to highlight starting with a text and that a link will be coming through.
- [ ] Create new wording to highlight that Veterans should wait for a link to appear to complete check-in.
  - Review with Danielle Thierry (site-wide content).
- [ ] Create final version in Illustrator for the following size posters: 8.5X11, 11X17, 24X36
- [ ] Determine need to usability test this new version. 

## Acceptance Criteria
- [ ] Post to [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral). Don't override the original designs until we usability test this version.

**Comment by kristenmcconnell** [comment]
@niradatta1 The GitHub link in the acceptance criteria section is where you can find the raw files.

**Comment by kristenmcconnell** [comment]
@niradatta1 The ticket estimate is leftover from my earlier estimation. We can discuss estimates.

**Comment by niradatta1** [comment]
@kristenmcconnell Added one more task here to write the usability test plan related to the poster, and coordinate with @Evafloyd so it's integrated in the other UX research tests she's working on this sprint.

**Comment by zach-park** [comment]
Once poster design is approved with in 24"x36" as template, populate the 8.5" X 11" and 11" X 17" as follow up. @kristenmcconnell  @Evafloyd @niradatta1 @ya-ching
