### ISSUE TITLE
[RESEARCH] Question to answer: number of appointments for on Veteran at different facilities each day.

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#30158]
Can we answer the question "How many Veterans have appointments at more than one facility in any given day?"
- This idea was brought up by a few Veterans during usability testing and the Martinsburg visit.
- Stakeholder brought it up as well.

## Tasks
- [ ] What analytics should we look at to determine this. Should the team just make the decision.
- [ ] Message Shane Elliott to get report
- [ ] Decide if there is a good use case. If so, add facility information to the appointment page.

**Comment by kristenmcconnell** [comment]
Based upon meeting with team on September 20, we will be adding facility data to the "Your appointments" page.

**Comment by kristenmcconnell** [comment]
Based upon meeting with team on September 20, we will be adding facility data to the "Your appointments" page.

**Comment by kristenmcconnell** [comment]
This ticket is no longer needed.
