### ISSUE TITLE
526: Discover & fix Sentry `undefined is not an object` for `query`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30157]
## Description

The linked Sentry event shows a JS error `Cannot read properties of undefined (reading 'query')`.

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/49526

## Tasks

- [ ] Get test data for the event
- [ ] Find source of JS error
- [ ] Fix source of the error
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
Attempted to duplicate 2x using 2 different users, unsuccessfully.

**Comment by Mottie** [comment]
This Sentry error is a lot more rare now! 🎉  (possibly due to this update - https://github.com/department-of-veterans-affairs/vets-website/pull/18832). We will continue to monitor until the end of this sprint and close this issue if it doesn't show up again, or we're unable to obtain data from an occurrence.

**Comment by Mottie** [comment]
This error has not appeared in the past 10 days. This may be due to this update - department-of-veterans-affairs/vets-website#18832 - I'll go ahead and close it now. I'll reopen it if this error recurs _and_ user data is available and provides a method to duplicate the error.
