### ISSUE TITLE
526: Discover & fix Sentry `undefined is not an object` for `e.type`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30151]
## Description

The linked Sentry event shows a JS error `undefined is not an object (evaluating 'e.type')`.

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/49515/

## Tasks

- [ ] Get test data for the event
- [ ] Find source of JS error
- [ ] Fix source of the error
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
We have not been able to obtain data for these Sentry events. That combined with this error rarely occurring now (possibly due to this update - https://github.com/department-of-veterans-affairs/vets-website/pull/18832), have made it difficult to reproduce. We will continue to monitor until the end of this sprint and close this issue if it doesn't show up again, or we're unable to obtain data from an occurrence.

**Comment by Mottie** [comment]
Plan to continue investigating this error in the next sprint.
