### ISSUE TITLE
526: Discover & fix Sentry `t.map is not a function`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30154]
## Description

The linked Sentry event shows a JS error `t.map is not a function`.

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/49505

## Tasks

- [ ] Get test data for the event
- [ ] Find source of JS error
- [ ] Fix source of the error
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
