### ISSUE TITLE
[PM] Notification Prefs: QA go/no go

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30163]
## Background
We need to confirm that we're ready to send the feature forward for formal QA

## Tasks
- [x] Ensure feature is done
- [x] Review the feature and functionality
- [x] Complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/QA/notification-prefs-QA-go-no-go.md) with team

**Comment by ajakabcin** [comment]
Go/no-go session scheduled with the team for Thursday afternoon right after standup (9/23)

**Comment by ajakabcin** [comment]
Move go/no-go to the following Monday (9/27) to allow more time for development

**Comment by ajakabcin** [comment]
Readiness checklist complete - ready to proceed with QA once test users are reset to null state.
