### ISSUE TITLE
[FE] Integration API for displaying multiple appointments

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30168]
## User Story

- As a user, I should be able to check in to my appointments if I have multiple appointments on the same day 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

This is about the integration with the API for pulling and displaying multiple appointments.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create new Redux action for API call that looks for an array of appointments
- [x] Display the multiple appointments
- [ ] Ensure that back buttons always reload the page. 
- [x] Create unit tests
- [x] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
