### ISSUE TITLE
Content updates to S-DVI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30161]
## Issue Description
There are 2 sets of updates we need to make to our [S-DVI insurance](https://www.va.gov/life-insurance/options-eligibility/s-dvi/) page.

Lori Hamilton requested the following change: 

The fourth bullet in the eligibility section needs to be changed to the following:

**Apply by December 31, 2022 or within two years of your rating, whichever occurs first.**

Paul Weaver requested the following 2 changes:

Under the question "Can I get more life insurance coverage if I need it?"  the first bullet should be changed to:

Apply for the coverage by December 31, 2022 or within 1 year from the date you get notice of the grant of waiver, whichever comes first; and

Under the question "How do I get these benefits?" change the last sentence in the paragraph under the address to the following: You must apply for the coverage by December 31, 2022 or within one year from the date you receive notice of the grant of waiver of premiums, whichever comes first.

We need to copy edit and make sure it's consistent with VA.gov's voice and style before publishing the page.

## Tasks
- [x] Update S-DVI page with new content
- [x] Review and publish
- [x] Alert stakeholder that change is live

## Acceptance Criteria
- [x] Updated content is live on the page

**Comment by RLHecht** [comment]
@bethpottsVADEPO Should the above be changed to:

Apply by December 31, 2022, or within 2 years of receiving your disability rating (whichever comes first).

Let me know if this is OK and if I should send to Lori Hamilton before we make the change on the page.

**Comment by bethpottsVADEPO** [comment]
@RLHecht  Your revision looks great, thanks!

**Comment by RLHecht** [comment]
This page has been published. Will send Lori a link once it's live.

**Comment by RLHecht** [comment]
Change is live. Closing ticket.

**Comment by RLHecht** [comment]
I added Paul Weaver's requests to this page to the ticket as well so reopening.

**Comment by RLHecht** [comment]
@bethpottsVADEPO For Paul Weaver's updates I was going to change to the following:

Apply for the coverage by December 31, 2022, or within 1 year from the date you get notice of the grant of waiver (whichever comes first), and

You must apply for the coverage by December 31, 2022, or within 1 year from the date you receive notice of the grant of waiver of premiums (whichever comes first).

Let me know if these are OK and I'll update the page.

**Comment by bethpottsVADEPO** [comment]
@RLHecht The first edit looks good.

For the second one:

- Hard return (new paragraph) for the second sentence (and change "file" to "fill out and submit": To apply for supplemental S-DVI, fill out and submit an Application for...
- Flip the order of the download link and the last sentence (go with your edits) and put the last sentence in a Note

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
