### ISSUE TITLE
[FE] Address Content Change feedback 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30178]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Comments](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/29112)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Address content change from UA

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
"ineligible" check-in status.
![](https://files.slack.com/files-pri/T025UGMV9-F02FXD0HZ9C/screen_shot_2021-09-29_at_3.28.52_pm.png)

New Wording for validae

![](https://files.slack.com/files-pri/T025UGMV9-F02G6AQQC12/screen_shot_2021-09-29_at_3.30.10_pm.png)

**Comment by mdewey** [comment]
New wording 
<img width="318" alt="Screen Shot 2021-09-29 at 3 30 10 PM" src="https://user-images.githubusercontent.com/1793923/135341366-896298ea-e3f3-4c16-8c98-2b28fe476f79.png">
<img width="317" alt="Screen Shot 2021-09-29 at 3 28 52 PM" src="https://user-images.githubusercontent.com/1793923/135341370-d54a7b3f-7ce8-4337-b547-3b07631f36ad.png">

**Comment by brianseek** [comment]
@kristenmcconnell this is ready to review in screenshots. I have them attached to the PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/19010

**Comment by kristenmcconnell** [comment]
@ytsaoca Screenshots are available for review here as well.

**Comment by ytsaoca** [comment]
@mdewey The content looks good.
@brianseek Could you make the facility and clinic information as Heading / H6. (Like what it is shown on the Sketch) Thanks

cc. @kristenmcconnell

**Comment by brianseek** [comment]
> @mdewey The content looks good. @brianseek Could you make the facility and clinic information as Heading / H6. (Like what it is shown on the Sketch) Thanks
> 
> cc. @kristenmcconnell

Do you want the text wrapped in an H6 HTML tag? If so, I don't think that this would be a proper heading level for this content. There are no H3 - H5 headings proceeding it. If you just mean from a text style point of view, I think H6 style seems too small from what I see in the design system. https://design.va.gov/utilities/font-size

Please let me know if I am miss-understanding something.
