### ISSUE TITLE
Updates and reorganization of vaccine mini hub 9/17/21

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30176]
## Issue Description
Sitewide content recently made updates to the COVID-19 vaccine mini hub page to remove outdated content and provide new updated content. We also reordered some of the page. This work also needs to be done on the translated pages and the questions in the chatbot need to be updated with the correct content.

## Tasks
- [x] Update English page (Danielle)
- [x] Review and publish English page (Danielle)
- [ ] Update chatbot (Selina)
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish Spanish and Tagalog pages (Randi)
- [x] Send final copy to volunteer translators (Randi)

## Acceptance Criteria
- [x] English page is updated
- [ ] Chatbot is update
- [x] Spanish and Tagalog pages are updated

**Comment by RLHecht** [comment]
@lunascoop Here's the copy back from the translators. A few things:

1. Per guidance, Danielle went back to the original text for the paragraph under the H2 "How to get a COVID-19 vaccine at VA" so this new translated copy does not need to be added there. She also put back in the second sentence in the third bullet of that section "Both the Pfizer BioNTech and Moderna vaccines require 2 doses to be effective."

2. Make sure when you add in the translations that you compare the page to the English one and also open up the accordions. Danielle removed some copy from places (so that wasn't set to the translators). 

[https://app.zenhub.com/files/133843125/42d9e56b-92f9-4b99-99e5-38cdc5f20eb2/download](https://app.zenhub.com/files/133843125/42d9e56b-92f9-4b99-99e5-38cdc5f20eb2/download)
[https://app.zenhub.com/files/133843125/66243e38-2749-4a29-9a42-91d17f862544/download](https://app.zenhub.com/files/133843125/66243e38-2749-4a29-9a42-91d17f862544/download)

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. The second sentence in the third bullet of that section "Both the Pfizer BioNTech and Moderna vaccines require 2 doses to be effective" wasn't translated. It seems to be a combination of a sentence previously in the **What should I know if I get vaccinated outside the VA** question. I've google translated for now.

Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
Thanks @lunascoop These 2 pages are now published. I'll send Mateo the live links with changes once it's published.

**Comment by RLHecht** [comment]
I emailed Mateo the most recent changes. Closing this ticket and will reopen if he has changes to make.
