### ISSUE TITLE
Updates to additional dose and booster page 9/17/21

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30174]
## Issue Description
We've made content updates to the additional dose/booster page to based on new information for who is eligible to receive additional doses. We need to also update the chatbot and the Spanish and Tagalog pages.

## Tasks
- [ ] Update English booster page
- [ ] Review and publish English booster page
- [ ] Update chatbot (Selina)
- [ ] Send text to translators (Randi)
- [ ] Input Spanish translation (Selina)
- [ ] Input Tagalog translation (Selina)
- [ ] Review and publish translated pages (Randi)
- [ ] Send to volunteer translators for final review (Randi)

## Acceptance Criteria
- [ ] Content is live on English page
- [ ] Updated content is live in chatbot
- [ ] Updated translated pages are live

**Comment by RLHecht** [comment]
@lunascoop Here are the translations to be input:

[https://app.zenhub.com/files/133843125/85fa7fd3-b43d-4b47-8af2-9cb5d80c3776/download](https://app.zenhub.com/files/133843125/85fa7fd3-b43d-4b47-8af2-9cb5d80c3776/download)

[https://app.zenhub.com/files/133843125/916e1850-2233-48a8-a16e-3e101034af88/download](https://app.zenhub.com/files/133843125/916e1850-2233-48a8-a16e-3e101034af88/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. Mateo also provided translations in #28801 so they are combined for the Spanish page (since the Spanish translation Mateo provided is a bit outdated). I referred to Mateo's changes for the Tagalog page.

Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394
Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408

**Comment by RLHecht** [comment]
Thanks @lunascoop These pages are both published.

**Comment by RLHecht** [comment]
This ticket is completed. Closing!
