### ISSUE TITLE
[UX] Create UX Roadmap

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#30179]
## Description
With all of the new UX team members, we need to create a roadmap of work for UX over the next few weeks/months. This way with can begin to divide up work.

## Tasks
- [x] Hold discussions about the roadmap
- [x] Create a Mural of the roadmap 

## Acceptance Criteria
- [x] Review roadmap with Patrick and product
- [x] Write any necessary tickets in GitHub

**Comment by kristenmcconnell** [comment]
- [Mural Roadmapping Document](https://app.mural.co/t/vsa8243/m/vsa8243/1632323185803/ddbd0b5970d2aa3842dd964ddabea0ff1007099c?sender=uc940f53ad96ac0203d6d3631)
- [GitHub Tickets](https://app.mural.co/t/vsa8243/m/vsa8243/1632323185803/ddbd0b5970d2aa3842dd964ddabea0ff1007099c?sender=uc940f53ad96ac0203d6d3631)
