### ISSUE TITLE
Authenticated Experience: Sprint 62 (12/1 - 12/14)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30188]
## Priorities

1. Complete any items unfinished from last sprint
2. Begin Collab Cycle/Design Intent for My VA: Payments information MVP
3. Update On-site Notifications design and define needs with VA Notify team
4. Complete testing on My VA using Login.gov credentials - [Slack Thread](https://dsva.slack.com/archives/CSFV4QTKN/p1637779695258300?thread_ts=1637702433.249300&cid=CSFV4QTKN)

PTO/Not Available
- Liz: Dec 3, 8 - 13
- Lihan: Dec 10 - 23
- Tressa: Dec 6, 8 - 10 (slow responses)
- 

## On-site Notifications (#30611)

**PM**
- [ ] ~#33300 On-site Notifications: Work with VA Notify to define needs and delivery timeline for MVP~

**Design/Research**
- [ ] #33266 On-site Notifications: Update design on MVP notification 
- [ ] #33301 On-site Notifications: Follow-up with Design Intent tickets 
- [ ] ~#33300 On-site Notifications: Work with VA Notify to define needs and delivery timeline for MVP~

**FE**
- [ ] ~#33300 On-site Notifications: Work with VA Notify to define needs and delivery timeline for MVP~

**BE**
- [ ] ~#33303 On-site Notifications: Determine next steps for backend build~
- [ ] ~#33300 On-site Notifications: Work with VA Notify to define needs and delivery timeline for MVP~

## My VA 2.0 Enhancements (#31611) - Adding Payment information

**PM**
- [x] #32291 My VA Enhancements: Submit collab cycle kick-off request  
- [x] #33293 My VA Enhancement - Payments: Schedule & prep for Design Intent 

**Design/Research**
- [x] #32289 My VA - Payments Information: Design work
- [x] #33293 My VA Enhancement - Payments: Schedule & prep for Design Intent 
- [x] #33294 My VA Enhancements - Payments: Run Design Intent for Payment section on va.gov 
- [x] #33992 My VA - Payments Information: Put together use cases for review

## Communications permissions (ie. notification preferences) (#18071)

**FE**
- [x] #32917 Notification Preferences: Remove feature flag code for Notification Preferences 

## General/Other
- [x] #33261 [PM] My VA: Functionality testing using login.gov credentials 
- [x] #33124 [Design] My VA: Update components and files to reflect the removal of breadcrumbs 
- [x] #33976 My VA: Update "VA Benefits you might be interested in" section to show the Education benefit block persistently 
- [x] #33994 [Design] My VA: Consider My VA structure design overhaul

**Comment by Samara-Strauss** [comment]
I think #32917 is being tracked as part of Marci's sprint. Can you confirm? If so, you can remove it from this list.
