### ISSUE TITLE
Authenticated Experience: Sprint 61 (11/17 - 11/30)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30187]
## Priorities

1. Launch notification prefs to all users and monitor progress!
3. Continue research/design on My VA: Payment information
3. Synthesize research on User Roles

PTO
_(FYI - Nov 25th is Thanksgiving Holiday)_
- Tressa: Nov 17, 25 - 26
- Liz: Nov 24 - 26
- AJ: Nov 24(pm) - 26
- Samara: Nov 24 - 26
- Taylor: Nov 25 - 26
- Heather: Nov 25
- Lihan: Nov 25
- Erik: Nov 25

## Notification Preferences (#18071)
**PM**
- [x] Touch base with Profile team for feature handoff #32973

## My VA 2.0 Enhancements (#31611)

**PM**
- [ ] My VA 2.0 enhancements: Submit collab cycle kick-off request #32291 
- [x] My VA 2.0 Enhancements: Share findings and determine MVP #32730 

**Research/Design**
- [x] My VA 2.0 enhancements: Payment feature familiarization #32558
- [x] My VA 2.0 enhancements: Sync with debt team #32559
- [x] My VA 2.0 Enhancements: Share findings and determine MVP #32730 

**FE**
- [x] My VA: Remove breadcrumbs in My VA #31231

## User Roles Research (#30894)

**Research/Design**
- [x] User Roles Research: SME interview synthesis #32405
- [x] User Roles Research: Conduct interviews with SMEs #32292

## Backend
- [x] Lihan supporting Identity team

## General/Other
- [x] [PM] Onboarding: Heather Justice - wrap-up final tasks #32946
- [x] [FE][Bug] Contact Info: Edit mode is not exited when moving between Contact Info and other Profile sections #32114
- [ ] [Discovery] - Auth Exp best practices research phase 3 #24975
