### ISSUE TITLE
Authenticated Experience: Sprint 60 (11/3 - 11/16)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30186]
## Priorities

1. Begin Notification settings phased launch
2. Finalize design of on-site notifications
3. Finalize MVP requirements for on-site notifications
4. Complete as many SME interviews for user role research as possible
5. Determine final direction for My VA enhancements
6. Onboard Heather!

PTO
- Erik 11/3 - 11/17
- Tressa 11/9, 11/15 - 11/17
- Samara and Taylor, 11/11 Veterans Day
- Liz 11/9 - 11/11

## Notification Preferences (#18071)
**PM**
- [x] Launch Notification Prefs to 25% #30808
- [x] Launch Notification Prefs to 50% #30809 
- [x] Launch Notification Prefs to all users #30810

**FE**
- [x] [Content styleguide] Labels or instructions aren't provided when content requires user input. (05.11.1) #31444 (from previous sprint)
- [x] Launch Notification Prefs to 25% #30808
- [x] Launch Notification Prefs to 50% #30809 
- [x] Launch Notification Prefs to all users #30810

## On-site Notifications (#30611)
**PM**
- [ ] ~Define/share requirements with VA Notify #32281~

**Design/Research**
- [ ] ~Define/share requirements with VA Notify #32281~ 
- [x] Design feedback - design intent - AE, Notifications #32297
- [ ] ~Finalize design #32293~
- [ ] ~Work with Content on notifications on va.gov #31615~

**FE**
- [ ] ~Define/share requirements with VA Notify #32281~
- [ ] ~Technical discovery around notifications defined for MVP #30610~
- [x] Investigate how our system handles markdown #32446

**BE**
- [ ] ~Define/share requirements with VA Notify #32281~
- [ ] ~Technical discovery around notifications defined for MVP #30610~

## My VA 2.0 Enhancements (#31611)

**Research/Design**
- [x] Synthesize discovery findings #32290 
- [ ] Sync with debt team #32559
- [ ] Payment feature familiarization #32558

## User Roles Research (#30894)

**Research/Design**
- [x] Create conversation guide(s) #31617
- [ ] Conduct interviews with SMEs #32292
- [ ] SME interview synthesis #32405

## Direct Deposit
- [x] Edit mode is not exited when moving between Profile sections #25788 
- [x] (Bug) Warning for unsaved bank info changes not always shown #25792

## Backend
- [x] Lihan supporting Identity team

## General
**PM**
- [x] Onboarding: Heather Justice #31921 

**FE**
- [x] Disability rating should be two lines on mobile/small screens #32099
- [ ] Edit mode is not exited when moving between Contact Info and other Profile sections #32114
