### ISSUE TITLE
[Datadog] Implement simple monitors for sentry

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30180]
## Description
Add a few simple monitors for sentry to pick up any hiccups that may be occurring with this service.

- synthetic test to hit endpoint http://sentry.vfs.va.gov/_health/ and make sure that the string 'ok' is returned
- monitor to make sure events are still being processed
- monitor to make sure all jobs launched by sentry are completed successfully

---
## Tasks
- [x] create datadog monitors and alerts in terraform that are sent to slack for testing
- [x] make sure that they are not spamming slack
- [x] integrate with pagerduty

## Acceptance Criteria 
- [x] Simple monitors are created to monitor the sentry service that are tied to both slack (#oncall) and pagerduty (sentry service)

**Comment by dginther** [comment]
Verified these monitors are in place
