### ISSUE TITLE
Add RBAC Permissions to Argo for CMS Team

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#30196]
## Description
Request the creation of a ArgoCD/EKS RBACs for CMS Team members @olivereri @ElijahLynn @indytechcook @ndouglas 

## Background/context 
VA.gov-CMS team is beginning the on-boarding process to migrate CMS Test infrastructure to EKS.

## Technical notes
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30177

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6285

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] RBAC Permissions in ArgoCD/EKS added for @olivereri @ElijahLynn @indytechcook @ndouglas 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
