### ISSUE TITLE
[FE] Profile: Rename "status and disability" banner to "my information"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30202]
## Background
As outlined in #29068 we needed to rename the blue "status and disability" banner because when the Veteran does not have a disability rating this name is misleading and confusing.

## Tasks
- [ ] Rename the banner to be "my information"
- [ ] Tag Josh or Angela to validate

## Acceptance Criteria
- [ ] Screenreader reads the banner as "my information region"

**Comment by tmitchellgcio** [comment]
@ajakabcin ready for validation

**Comment by ajakabcin** [comment]
@joshkimux can you give this a look when you have a moment? Thanks!!

**Comment by joshkimux** [comment]
@ajakabcin , I'm having trouble logging in on staging at the moment, but will review as soon as it's working

**Comment by joshkimux** [comment]
<img width="1769" alt="Screen Shot 2021-10-01 at 11 14 00 AM" src="https://user-images.githubusercontent.com/14154792/135645673-38060258-a750-4b9c-b1b8-083ecaec2741.png">

Wonderful! 👏
