### ISSUE TITLE
Learn how to connect to VISTA

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30209]
## Issue description
Online scheduling data is available via VISTA. We know services may not be coded the same across all facilities.

## Tasks
- [ ] Identify point of contact for VISTA (Shane Elliott - VeText?)
- [ ] Learn how to connect to VISTA for online scheduling data and how to identify Mental health and primary care services across all facilities

## Acceptance criteria
- [ ] We can make a plan for connecting to VISTA for mental health and primary care services for all (or a small subset) of facilities
