### ISSUE TITLE
[Design] My VA, Profile: IA discussion about future of My VA and Profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30205]
## Background
We received a request to meet with IA about the future of My VA and Profile.

## Tasks
- [ ] Design and product to meet with Mikki from IA (scheduled for 9/27)
- [ ] Document any next steps
- [ ] Create tickets as needed

**Comment by andaleliz** [comment]
@ajakabcin are there any next steps from this meeting? Wondering if we can consider this done.

**Comment by ajakabcin** [comment]
I think we can close this for now based on the feedback Samara in the DGIB session yesterday. Thanks!
