### ISSUE TITLE
Linting for vsp-infra-application-manifests repository

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30200]
## Description
As an Operations member, it would be helpful if there were automated linting checks for pull requests made to the [vsp-infra-application-manifests repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests)

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1631890221197900

---
## Tasks
- [ ] Add some form of linting to vsp-infra-application-manifests repository

## Acceptance Criteria 
- [ ] Working linter exists

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
