### ISSUE TITLE
Move remaining QA and Accessibility Collab Cycle documentation to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#30216]
## Issue Description
Almost all of the Collaboration Cycle guidance and documentation is available on Platform Website, with the exception of the following QA and Accessibility documentation that is referenced in the Staging Review touchpoint:

- [x]  [QA Artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)
- [x] [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md)
- [x] [Accessibility Defect Severity Rubric](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md)
- [x] [Accessibility post-launch audit processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md)
- [x]  Update links in Staging Review touchpoint doc
- [x]  Update links in Full Accessibility/508 audit touchpoint doc
- [x] Update links in Midpoint review touchpoint doc
- [x]  Add message to Github files about documents moving to Platform website

The QA document should live in [this location ](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html)and the Accessibility artifacts should live in [this location ](https://depo-platform-documentation.scrollhelp.site/developer-docs/Accessibility-testing.1255931908.html)on Platform website. 

Testing Tools Team has this work on their plate via ticket #25086, however in order to meet [Product Supports OKR for Objective 1](https://docs.google.com/spreadsheets/d/1qVAJKXVYys_YlRifglZGVbYQc09mKsLAsI1RTqPbHa8/edit#gid=715168434), "100% of Collaboration Cycle documentation is available in Platform Website." by end of Q3, Product Support will be taking on this work.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Hi, @allison0034 @jimuhh This Accessibility and Q/A documentation has been migrated over to Platform website. If you get a chance, can you review and let me know if you see any issues? 

https://depo-platform-documentation.scrollhelp.site/developer-docs/Accessibility-testing.1255931908.html

https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-artifacts.1906999390.html

**Comment by jimuhh** [comment]
Are all of the accordion articles "How-tos?"

**Comment by pjhill** [comment]
Thanks for migrating that document, Peggy! Incidentally, I had been working on migrating all the other QA documentation. So, there are now quite a few QA documents moved over to the Platform website.

I click through the links in the QA artifacts document, and I didn't see any issues. Thanks again!
