### ISSUE TITLE
Update covid FAQS alert on Spanish and Tagalog pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30210]
## Issue Description
We current alert we have on the coronavirus FAQs page for Spanish and Tagalog are out of sync with what is on the English page. We need this translated so we can update the page.

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish Spanish and Tagalog pages (Randi)

## Acceptance Criteria
- [x]  Alert on Spanish and Tagalog pages match the English page on live site

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy for the alert

[https://app.zenhub.com/files/133843125/2195bade-181f-4f8c-b094-43733d205155/download](https://app.zenhub.com/files/133843125/2195bade-181f-4f8c-b094-43733d205155/download)

[https://app.zenhub.com/files/133843125/165ce1da-4191-4b82-9712-e811bd4d9041/download](https://app.zenhub.com/files/133843125/165ce1da-4191-4b82-9712-e811bd4d9041/download)

**Comment by RLHecht** [comment]
Thanks @lunascoop These have been reviewed and published.

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket.
