### ISSUE TITLE
[Datadog] Implement simple monitors for external-secrets

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30217]
## Description
Add monitor for external-secrets to pick up any hiccups that may be occurring with this service.  Only one real statistic to alert on here which is wether or not the secrets synced correctly.

---
## Tasks
- [x] create datadog monitor and alert in terraform that are sent to slack for testing
- [x] make sure that they are not spamming slack
- [x] integrate with pagerduty

## Acceptance Criteria 
- [x] Simple monitors are created to monitor the sentry service that are tied to both slack (#oncall) and pagerduty (eks service)

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by dginther** [comment]
Looks good
