### ISSUE TITLE
Use server distance for sort order 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30212]
## Issue Description
In #29942, we addressed the number of search results per page and lettering conventions from one page to the next. 
The overlapping radius scenario may be due to a small shift in the map occurring between queries for a page of search results, which slightly alters the computed distance. 

During grooming of #29942 we determined that we would return to this item and consider approaches to getting a full set of data to avoid this risk.

Steps to reproduce:
- Use the Facility Locator to search for VA health facilities in Brooklyn, NY
- The second page of results is for locations beginning at 31.7 miles away (distance overlaps but locations are unique)
- [Loom link](https://www.loom.com/share/475648fc0e7e44a985dc5c2ebaf1bf8c)

[Reference for computing distance](https://github.com/department-of-veterans-affairs/vets-website/blob/5c88ad68f93f4abfb595838261193c5596666d2d/src/applications/facility-locator/actions/index.js#L152)

Dev notes
- need to look at api calls to find out if the queries are different
- Lighthouse may not be using lat/long but are referencing bounding box
- May get more consistent results if we use lat/long
- Lighthouse would give distance if we use lat/long and then we wouldn't need to calculate distance

Query 1: https://api.va.gov/facilities_api/v1/va?bbox[]=-74.6996&bbox[]=39.9001&bbox[]=-73.1996&bbox[]=41.4001&type=health&page=1&per_page=20&mobile=false&radius=16&latitude=40.6501&longitude=-73.9496

Query 2: https://api.va.gov/facilities_api/v1/va?bbox[]=-74.6996&bbox[]=39.9001&bbox[]=-73.1996&bbox[]=41.4001&type=health&page=2&per_page=20&mobile=false&radius=16&latitude=40.6501&longitude=-73.9496

https://developer.va.gov/explore/facilities/docs/facilities?version=current
A query by latitude and longitude returns all facilities in the system, sorted by distance from that location.

[Link to action for sort order](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/actions/index.js#L115
)

---
## Tasks
- [x] Work with Lighthouse to identify best method for identifying location (bounding box vs lat/long)
- [x] If Lighthouse will take lat/long rather than bounding box, then we can change the query 
- [x] Document method for computing distance (drive distance vs mileage)
- [ ] Consume distance from Lighthouse and PPMS to use for sort order
- [ ] Remove calculated distance logic 

##Acceptance Criteria
- [ ] Results list is sorted in descending order by distance
- [ ] No overlapping from page to page
- [ ] Within a mash-up, sort order is maintained across the two sources
- [ ] Calculated distance is no longer used for sort order

**Comment by mmiddaugh** [comment]
This should be resolved by #31527

**Comment by mpelzsherman** [comment]
I can no longer reproduce the overlapping data issue described in this ticket. I’m not sure why - maybe the Lighthouse data changed?

**Comment by mmiddaugh** [comment]
This task is being returned to the backlog due to usability issues discovered when the results are unlimited by radius or bounding box. Can return to this work when Lighthouse adds a radius parameter.

**Comment by mmiddaugh** [comment]
We were able to see that the overlapping sort order is resolved by the change to send lat/long but we are unable to enable this change in Prod due to usability issues caused by the unbounded data set.

**Comment by Agile6MSkinner** [comment]
@mmiddaugh this is the last issue standing in Epic #19065. What are your thoughts on it?

**Comment by jilladams** [comment]
Given the age of the ticket, the low priority of the work, the complications of distance with LH, their backlog, and the pending migration to Github Projects, I'm going to go ahead and close this. We can reopen as needed in the future, or use the notes here to inform a new ticket.
