### ISSUE TITLE
Bug in `removeDeeplyEmptyObjects`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30211]
## Descriptions

While troubleshooting a JS error that shows up during submission, I found a fun bug in the `src/platform/utilities/data/removeDeeplyEmptyObjects` function. If you pass in 

```js
{
  array: [ { test: '1' }, {}, { test: '3' } ],
}
```

it returns an object:

```js
{
  array: {
    0: { test: '1' },
    2: { test: '3' },
  },
}
```

## Tasks

- [ ] Add check for an array type & iterate it's items
- [ ] Add unit test

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
