### ISSUE TITLE
[FE] Confirmation Page Update 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30222]
## User Story

> these should be why the veteran cares, and the veteran gets out of it.

As a veteran, I should be able to see what appointment I check-in so I know I checked into the correct appointment

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The confirmation page should display the appointment that was checked in and should have a back button if there are more appointments

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Show appointment time 
- [x] Bold the clinic name
- [x] Add back link
- [x] Confirm and implement back link logic
- [x] Create unit tests
- [x] Create e2e tests
- [x] Update relevant documentations
  - [x] README
  - [x] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
