### ISSUE TITLE
Remove PagerDuty/DataDog services/integrations

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#30228]
## Description
Before we decided to use messages in DataDog to route to services if they were in critical environments, some services and integrations were made in Datadog/Pagerduty which correspond to particular environments/EKS clusters. We need to remove these so they don't get confusing.

---
## Tasks
- [ ] Remove pagerduty services for Loki that are scoped to an environment
- [ ] Remove pagerduty services for EKS Infrastructure that are scoped to an environment
- [ ] Remove DataDog PagerDuty integrations for the above services

## Acceptance Criteria 
- [ ] There is only one service in PD for Loki
- [ ] There is only one service in PD for EKS Cluster/Infra
- [ ] There are no services in the DataDog Pagerduty Integration which can be used to alert to a particular environment

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by dginther** [comment]
EKS_Cluster_-_Prod and EKS_Cluster_-_Utility should be removed as well, but if there are anything using them, then we want to redirect those to Infrastructure-EKS.

In addition, we should remove the corresponding services in Pagerduty.

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - Can you take a look at Demian's feedback above and follow up as needed? Thank you!

**Comment by rbeckwith-oddball** [comment]
I don't want to delete any services unnecessarily. I don't see any services in PagerDuty that still need to be removed at this point. The integrations Demian mentioned have been removed.

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - Please check off tasks and acceptance criteria (you can re-write for accuracy if needed).

**Comment by jhouse-solvd** [comment]
@jsgarmon - If we can take a look here to verify what was/wasn't done, and create new tickets for any follow-up items, that would be awesome.

**Comment by jsgarmon** [comment]
I'm not seeing anything environment-specific in https://app.datadoghq.com/account/settings#integrations/pagerduty:
![image](https://user-images.githubusercontent.com/47490730/159791778-3e98615f-fa25-4eb4-9cac-a739bb49a0f7.png)

I'm marking the acceptance criteria as met and closing this issue.
