### ISSUE TITLE
[Design]  UX design solution for APO/FPO/DPO flow

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3023]
## User Story

As a UX designer, I want to be able to create UX design to show the process of moving "US COUNTRY" to a later part of the flow when a user inputs their address/APO/FPO/DPO information. 

## Tasks 

Create UX mock up design to show this flow with clickable prototype

## Acceptance Criteria 

- [x] Upload UX mock ups and design and share with team members and design team.
- [x] Any revisions made from feedback. 
- [x]  Updated messaging is review by Content editor
- [x] Approved to move forward with FE dev work

##  Upload Screenshots Below:

**Comment by artistgreen** [comment]
Discovery points:

Discussion with @lihanli  uncovered that there is confusion when a user inputs a military address and selects a 'Country' option outside of United States.  Lihan suggested that when a user inputs APO, FPO or DPO for their City, we automatically select a new option for 'Country': Military Base.  Lihan advised he can treat 'Military Base' the same as he would 'United States' on the back end.

Discussion with @lkoenigsberg and @Justin-Pickett  generated 2 front end options to explore:

1. When the user inputs APO, DPO or FPO for their 'City', we force 'United States' in the 'Country' field and do not allow them to change it unless they change their 'City' value from APO/DPO/FPO.  We would also show an inline message to explain.

2.  When the user inputs APO, DPO or FPO for their 'City' and then selects a country outside of the United States for their 'Country', we display an inline error message, that advises them they need to select 'United States', and do not allow them to update the address.

In order for this flow to be optimized, we need to consider moving the 'Country' field from the top of the Edit Mailing Address form to below the 'State' field.

**Comment by artistgreen** [comment]
@lkoenigsberg @Justin-Pickett 

Here are the 2 UX options we discussed:  https://invis.io/8NUNI0364VK

There are some considerations I included in the wireframes and will document them here once we can touch base and discuss.

Thanks!

**Comment by lkoenigsberg** [comment]
+ @Samara-Strauss to take a look at this effort as well.

**Comment by Justin-Pickett** [comment]
My thoughts -I like option #2 -  I feel the "error" messaging is just a gentle explanation to the user of the need to select United States to proceed to updating their mailing info. That scenario feels more like we are letting the user still feel in control of their info. Also, as mentioned by @lkoenigsberg,  in the "state" section i think the state name should still be shown. But not sure if that will impact the ablilty to input APO/DPO/FPO or if a state is selected the system could automatically detect which state name could = APO/FPO or DPO. 

I think option 1 would be more confusing to a majority of users as they will be trying to understand WHY they can't select a different option other than United States. Kind of takes away that lack of the user being able to decide vs feeling forced to do what we tell them.

**Comment by artistgreen** [comment]
@lkoenigsberg - thanks for the feedback.
- I have removed the homepage screens
- The asterisks have been added to the required fields
- I have edited the State name to be the full name
- I added United States to the Country field for #2 - and I do not think this would be too confusing

@Justin-Pickett  - thanks
I prefer #2 as well - #1 may confuse users with the greyed out Country field

Adding @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Hi all — sorry it's taken a few hours to chime in here.

I am not going to vote on an approach at this time because some thought needs to be into the conditional functionality of the Country dropdown as it currently stands. The reason that field is at the top of the form is because if any other country besides the US is chosen, the State drop down changes to an open State/Province/Region field, and the Zip Code changes to an International Postal Code field. We need to account for this when approaching the APO/FPO/DPO problem.

I'm trying to get a screenshot but the upload functionality on GitHub isn't working for me right now, so please sign in to staging and play with the mailing or home address form to see this in action. Sorry to have to send you there instead of including a screenshot.

I don't know what this means for an approach — I am sure there is a solution to this problem but it might not be moving the country menu.

**Comment by artistgreen** [comment]
@Samara-Strauss - thank you for the feedback and information.

Quick potential solution if we need to keep the 'Country' field at the top:

I like the concept of adding a checkbox for 'Is this a military base' near the top of the form and we can lock the 'Country' field to United States if they check the box.  

I will produce a layout with this concept and update here when it is ready for review.  I'll also do some more thinking regarding other possible solutions.

**Comment by Samara-Strauss** [comment]
> I will produce a layout with this concept and update here when it is ready for review. 

I think this is a great idea. Feedback on implementation — I know we don't write the copy, but the copy will need to be something like "I live on a United States military base." I believe that our style guide usually states actions like this in the form of a statement instead of a question.

> I'll also do some more thinking regarding other possible solutions.

Great. Definitely open to other ideas if you have them.

**Comment by artistgreen** [comment]
Thank you for the clarification!  I'll use that copy until Content provides us the final :-)

Sounds great!!

**Comment by artistgreen** [comment]
Here are 3 screens that propose a checkbox on the 'Edit mailing address' form with 3 variations for review and discussion.

On the 'Edit mailing address' form, User checks 'I live on a United States' military base and:

1.  Country field is removed from view
2.  Country field is forced to 'United States'
3.  Country field is not forced and error message is displayed if user selects anything besides 'United States' for Country

#1 feels the best - @erikphansen advised that we currently have this pattern of hiding fields on forms based on user input choices

Screen for #1 - Country field is removed view

![Profile  - Remove Country field](https://user-images.githubusercontent.com/53535009/68328267-f7c4f600-009c-11ea-8ab6-b15e21517df2.png)

Screen for #2 - Force Country field

![Profile  - Military Base checked](https://user-images.githubusercontent.com/53535009/68328307-06131200-009d-11ea-81d5-0842e536dab3.png)

Screen for #3 - Error message

![Profile  - Error message](https://user-images.githubusercontent.com/53535009/68328337-12976a80-009d-11ea-8046-b978d490968f.png)

**Comment by Justin-Pickett** [comment]
@artistgreen will review with @lkoenigsberg and @Samara-Strauss  to gather feedback and finalize design approach for Sprint 8. Then review with additional stakeholders in upcoming Sprint 9.

**Comment by Samara-Strauss** [comment]
I have a question — how does someone actually write their address if they live on a military base?

Also, I think we can safely throw out option 3 — if all military bases are considered to be in the US even if they are in a foreign country, there's no need to allow people to edit the country menu only to make a mistake. 

I personally feel number 2 is the best so that people know a country has been selected and so they don't potentially get confused that there is no way to select a country. However, I don't actually think we have helper text for fields (worth confirming), so that is worth looking into before pursuing this approach. I would love if we did have helper text, so I don't think we should throw out this option if helper text currently isn't part of our design system.

**Comment by artistgreen** [comment]
Thanks @Samara-Strauss!  

This link shows how a military base address is formatted:
https://support.blurb.com/hc/en-us/articles/207794356-How-do-I-format-an-APO-or-FPO-address-

the TL;DR version:

Name: PFC Jack Lyon
Address 1: 23rd Battalion
Address 2: Unit 1234, Box 56789
Country: United States
City: APO
State: AP
Zip/Postal Code: 96522-1215

---

I absolutely agree about no. 3.  It was being lightly considered on the basis that users may be confused if they are not able to make a selection.

I'll look into it and confirm for us whether or not we have helper text - would be awesome.  

If we do not currently use helper text would it be worth considering proposing for it to be integrated into the design system?

**Comment by Samara-Strauss** [comment]
Given that this includes the country, we should not hide the country dropdown. Let's go with approach 2.

**Comment by artistgreen** [comment]
@Justin-Pickett - Yes, no. 2

I am researching the last bit of the design regarding 'helper text' on the form and hope to have those answers today.

**Comment by Samara-Strauss** [comment]
Great. All of this sounds good to me. Thanks for the update.

**Comment by Samara-Strauss** [comment]
I'm sorry — do we have final designs?

**Comment by Samara-Strauss** [comment]
One more thing — this was estimated as a 1 but has open for almost 3 weeks. Justin/Arthur – can you please adjust the estimate as you see fit for this ticket? I am assuming that the benefits and memorials related discussion/work is being tracked in another ticket (which is what Justin mentioned above), so that probably does not need to be factored in to this estimate.

**Comment by Justin-Pickett** [comment]
This ticket is still ongoing. More discovery research is needed to understand how/if APO/FPO/DPO flow affects any other eBenefits forms across the VA.gov website. @artistgreen is looking into this. Follow up conversation is also being set up with the Benefits and Memorials team to discuss the flow of this and get some clarification on some questions regarding forms and the databases they interact with.

**Comment by Samara-Strauss** [comment]
> More discovery research is needed to understand how/if APO/FPO/DPO flow affects any other eBenefits forms across the VA.gov website

@Justin-Pickett to be clear, these are not eBenefits forms. These are benefit applications that live on VA.gov. This has nothing to do with eBenefits.

> @artistgreen is looking into this. Follow up conversation is also being set up with the Benefits and Memorials team to discuss the flow of this and get some clarification on some questions regarding forms and the databases they interact with.

We need documentation on what has been discussed and learned so far. It is impossible to tell what has been done at this point, which makes it impossible to tell if we've met our sprint objectives or not for sprint 9. It also makes it impossible to tell if we are on the right track and pursuing the right problems/solutions.

**Comment by artistgreen** [comment]
Met with @AZSchneider @YanaRoy and @Justin-Pickett  to discuss impact of our proposed solution on their forms.  

Andrea advised that some forms run on PPIU and some on Vet360 - we do not think adding a checkbox for 'I live on a US Military Base' will break their forms.  
We planned to follow up and continue the discussion - Andrea was going to confirm this solution will be OK and what forms are running on Vet360.

**Comment by artistgreen** [comment]
@lkoenigsberg - here is my list of forms I discovered on staging:

https://staging.va.gov/records/download-va-letters/letters/confirm-address

https://staging.va.gov/health-care/apply/application/veteran-information/personal-information

https://staging.va.gov/pension/application/527EZ/applicant/information

https://staging.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information

https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information

https://staging.va.gov/profile/

**Comment by artistgreen** [comment]
Design discovery

Military addresses have several different formats depending on these factors:

Within US / Barracks:
John Smith
Unit # Box #
Fort Bragg, NC 20813

Within US / Base Housing:
John Smith
4780 Camel Rd
Fort Bragg, NC 20813

Outside of US:
John Smith
Unit # Box #
APO, AE 09021

With these differences in formats, we can think about adjusting the UX/UI slightly based on whether the user is entering an address for a military base within or outside of the US.

For bases within the US:
- no change to the form fields since these addresses use the same format as any US address

For bases outside of the US:
- change the label from City (APO/FPO/DPO) to just APO/FPO/DPO and make it a drop down (since the user can only select one of these options)
- change the options in the State field to the different regional options: AA (Armed Forces Americas), AE (Armed Forces Europe) or AP (Armed Forces Pacific)

**Comment by artistgreen** [comment]
Due to the differences in address formats for military bases within the US versus bases outside of the US, the checkbox label should something more descriptive to the effect of: 
"I live on a United States military base outside of the United States"

![ Edit Mailing Address Overlay.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/2ac07d61-3000-4ef4-939e-a3479b3dc9a5)

Users will select United States for their country if they live on a military base within the US.

When the user checks the box:
- The UI will display helper text informing as to why the Country field is greyed out
- the Country field will become disabled and default to 'United States'
- The City field label will change to APO/FPO/DPO and will become a drop down element (versus an input box)
- The State field options will be reduced to just the regions:  AA, AE and AP

![Military Base checked.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/d42fd6c2-579f-4120-b361-bc046d2bc715)

![APO-FPO-DPO dropdown.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/6306f817-0547-48cb-a4be-0849f524f9f1)

![State drop down options.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/af8654ab-9293-4168-8c76-3283ab0dbef4)

**Comment by artistgreen** [comment]
Current InVision clickable prototype:  https://invis.io/ZRV4G12VEU7

**Comment by artistgreen** [comment]
@peggygannon - as we discussed, please provide copy for the checkbox label and helper text.  I'd be happy to discuss or any answer any questions - thank you!

**Comment by artistgreen** [comment]
In an effort to understand the impact on other forms on VA.gov this list was compiled.  These are the forms that have an address section which may be impacted by these changes.

https://staging.va.gov/records/download-va-letters/letters/confirm-address

https://staging.va.gov/health-care/apply/application/veteran-information/personal-information

https://staging.va.gov/pension/application/527EZ/applicant/information

https://staging.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information

https://staging.va.gov/profile/

**Comment by artistgreen** [comment]
For the Letters section, users are asked to make sure their address is current.  @erikphansen advised that this edit address FE is the same as the profile edit address component.  When a user updates their address here, the changes take effect on their profile also.

![Download VA Letters and Documents   Veterans Affairs.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/7e9e0357-2872-4d9e-90f0-6a99ccb9a6d5)

![Download VA Letters and Documents  edit address.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/a1964308-7116-4154-84e0-736cef045a9e)

**Comment by peggygannon** [comment]
@artistgreen Hello, please see my content recommendation below. I've also provided some screenshots of form pages where we have used helper text. 

{checkbox} I live on a U.S. military base outside of the United States. 

{copy} The United States is automatically chosen as your country since you live on a military base outside of the country.  

-----

A couple of other tweaks to mention: 

- What are the red dots in the screenshots? Should these be (*Required) instead? 

- Labels and buttons should be sentence-cased. Can you update your mockup to have the label Street Address>> Street address

- Zip code label should be: Postal code. (I know there is some inconsistency across forms and pages etc. and I'm trying to fix as I see them.)

- also, I saw there was question above about helper text in forms. We have used helper text in forms. I've upload a few screenshots as a visual. Let me know if we'll need any additional helper text for this design? 

Health care form https://staging.va.gov/health-care/apply/application/insurance-information/va-facility
![2019-12-04 (1)](https://user-images.githubusercontent.com/17554224/70173610-11e7f900-1688-11ea-8d0c-e61943a3fc5d.png)

![2019-12-04 (2)](https://user-images.githubusercontent.com/17554224/70173622-17ddda00-1688-11ea-8a8b-b75c9fed03bf.png)

**Comment by Samara-Strauss** [comment]
Is this ticket done? Why is this ticket still open?

Also, has a ticket been created for the FE for the profile updates? It looks like the copy for the profile is done, so that should be moved over into a FE ticket.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss yes the FE ticket for the profile updates has been created #4116. Just needs to be groomed (the content in this ticket moved into there appropriately for the FE engineer to pick it up).  I will close out this ticket soon as the info is moved into that ticket.

**Comment by Justin-Pickett** [comment]
@artistgreen is the copy and updated screen shots correct above so we can get this ticket closed and the appropriate info moved over into the FE ticket #4116?

**Comment by Samara-Strauss** [comment]
OK, thank you @Justin-Pickett

**Comment by artistgreen** [comment]
@Justin-Pickett - yes, this can be closed. I finished out the copy request in #3980 - thanks.

**Comment by Samara-Strauss** [comment]
For clarity, the rest of this work has been broken out into the following tickets:

- Design Discovery for APO/FPO/DPO #3979
- Create list of all benefits applications #3893
- Propose solution for how to handle military addresses in benefit applications that use VA Profile data. #3895
- Copy for Profile for APO/FPO/DPO #3980
