### ISSUE TITLE
[FE] Onboard new Developers to the team 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30233]
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Help the new developers get on board and help figure out what role folks will play . 
## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Have pair programming sessions
- [ ] Have new folks approve some PRs
- [ ] Support where needed
