### ISSUE TITLE
Add login.gov keep-alive mapping

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#30235]
## Issue Description
As Login.gov is added as a CSP we need to add the mapping for the keep-alive endpoint on vets-website for eAuth.  The headers need to be verified for both IAL1/2 Login.gov so we can accurately reflect their mappings.  This feature should additionally be feature flagged to ensure a proper roll-out to staging before systematically rolling the feature out. 

## User Story

---
## Tasks
- [x] Verify va_eauth_csid for Login.gov (IAL1/2)
- [x] Add mapping for keep-alive
- [x] Write unit testing to ensure proper functionality

## Acceptance Criteria
- [x] The keep-alive method is called
- [x] The va_eauth_csid maps to the correct authn context
- [x] The va_eauth_authncontextclassref uses the correct IAL1/2 strategy
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Update.  This is blocked until the `va_eauth_authncontextclassref` is returned (IAM & John)

**Comment by nsoutouras** [comment]
Waiting on IAM/ISAM, carries to Oct 11 Sprint (Sprint 63)

**Comment by nsoutouras** [comment]
Should be unblocked shortly, carries to next sprint

**Comment by bramleyjl** [comment]
After speaking with Craig about this @bosawt & I were told that ISAM had to make some unwanted changes to manipulate that value in order for our `keep-alive` to work and that they would rather not have to repeat the same practice for Login.gov - see #32757 for some more details.

I was unable to figure out how to interact directly with the `keepAliveSSO.js` file myself, but after looking at it and comparing the attributes available at https://int.eauth.va.gov/IAM after I authenticated with my Login.gov account, wouldn't it be possible just to check for the `va_eauth_ial` attribute and use one of two coded authn_context based on it coming back as 1 or 2? Or does the keep-alive call not have access to all of the same attributes?

**Comment by nsoutouras** [comment]
MSI - Will unblock after design tweaks

**Comment by AGarcia-Clarity** [comment]
We cannot access the `va_eauth_ial` in the headers because they are not exposed to the FE.  Login.gov users will be able to login, however the Auto SSO feature will not work for them (Signed in to Login.gov and navigates to VA.gov).

We need the eAuth keepalive endpoint to adjust their response headers for
`access-control-allow-headers` and `access-control-expose-headers`
 to include the `va_eauth_ial`.

We can then build out the AuthnContext to what is expected for each IAL
Example of AuthnContext
`va_eauth_csid`, `va_eauth_ial`, result
LOGINGOV, 1, logingov_1
LOGINGOV, 2, logingov_2

**Comment by nsoutouras** [comment]
Note to Nick: Allows auto login
