### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on September 27

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30244]
## Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file prior to their upcoming go-live

- [ ] /palo-alto-health-care
- [ ] /alexandria-health-care/
- [ ] /fayetteville-arkansas-health-care/
- [ ] /gulf-coast-health-care/
- [ ] /eastern-colorado-health-care/
- [ ] /southeast-louisiana-health-care/

## Acceptance Criteria
System names are removed from robot.txt file

**Comment by mpelzsherman** [comment]
gulf-coast-health-care was not present
