### ISSUE TITLE
526: Discover & fix Sentry `Internal error: too much recursion`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30259]
## Description

The linked Sentry event shows a JS error `InternalError: too much recursion`

Sentry error: http://sentry.vfs.va.gov/organizations/vsp/issues/49804

## Tasks

- [ ] Get test data for troubleshooting
- [ ] Find source of the JS error
- [ ] Fix source of JS error
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
I haven't seen this error in over a month. I'm going to close this one and open a new one if the Sentry event shows up again.
