### ISSUE TITLE
HLR v2: Add unique issues & max selected validation

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30255]
## Description

Copy code from Notice of Disagreement that prevents the additional-issues page from added duplicate existing rated disabilities or duplicate new disabilities for the Higher-Level Review v2 form. Also include max number of selected issues selected validation with modal message.

## Tasks

- [ ] Copy/paste code
- [ ] Add unit tests

## Definition of done

- [ ] All tasks done
- [ ] All tests passing
