### ISSUE TITLE
Adding mobile tool link to CST

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30252]
## Issue Description
Mina Farzad presentation suggested we leverage biometrics in Claim Status Tool, as the web app login experience can be daunting. Therefore we decided that a near term solution could be to promote the VA Mobile App on the Claim Status Tool. (Slack discussion with mobile team [here](https://dsva.slack.com/archives/C018V2JCWRJ/p1630419846035000)) 

Kevin's proposed implementation:
![image.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/b991e3c6-bb9b-4ab9-84e4-49cc749aa0ce)

---
## Tasks
- [ ] Determine best implementation - all users, mobile only? 

## Acceptance Criteria
- [ ] Link created on Claim Status Tool page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ambikaroos** [comment]
@vhenry07 glad to see this looks like it's getting prioritized! Wanted to flag the open questions/comments we (mobile team) has for implementation of this:

- Our team will need to provide you with the right links to the Apple and Google app stores
- Will you be detecting whether users are on an iOS or Android device, to display Apple and Google specific text and links?
- How will analytics work for this? Can you give us a sense of traffic to this page, and expected clicks on the banner?

**Comment by vhenry07** [comment]
@ambikaroos yes! 

- Will await links from your team
- Traffic (Pageviews were near 3 million for August, about 670k per week.) from our [slack conversation](https://dsva.slack.com/archives/C018V2JCWRJ/p1630419846035000). 
- @Mottie or @ashagross Can you confirm if we can detect iOS or Android and display link accordingly?

**Comment by Mottie** [comment]
> Can you confirm if we can detect iOS or Android and display link accordingly?

We could do this if needed. What about Microsoft phones?

Should a desktop show both links?

> How will analytics work for this? Can you give us a sense of traffic to this page, and expected clicks on the banner?

[Google Analytics for CST](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Ftrack-claims~2Fyour-claims~2F)

**Comment by ambikaroos** [comment]
@Mottie I think the ideal scenario for us would be:

1. If we detect you're on an iOS device, display iOS-specific text and a campaign link to the App Store
2. If we detect you're on an Android device, display Android-specific text and a campaign link to the Google Play Store
3. Otherwise, display generic text and a campaign link to both

@lexicalninja can you help provide the right links for iOS and Android that should be used for these banners?

**Comment by lexicalninja** [comment]
APPLE_STORE_LINK= https://apps.apple.com/us/app/va-health-and-benefits/id1559609596 
GOOGLE_PLAY_LINK= https://play.google.com/store/apps/details?id=gov.va.mobileapp

**Comment by Mottie** [comment]
The alert was merged in on Friday. It is now available in staging & production.

**Comment by ambikaroos** [comment]
Nevermind! @lexicalninja let me know that the PR code shows an ios/android check. Thank you!

**Comment by Mottie** [comment]
Mobile alert is set to be visible in production at next deploy - around 3pm ET - it's not behind a feature flag

**Comment by Mottie** [comment]
It's now visible in production.

**Comment by ambikaroos** [comment]
@Mottie @vhenry07 this banner is still up, correct? cc @leanna-usds

**Comment by Mottie** [comment]
Yes, I just saw it on Monday when I was talking to someone about the CST.
