### ISSUE TITLE
Authenticated Experience: Sprint 70 (3/23 - 4/5)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30275]
## Priorities

1. Payment Info: Complete Staging and Privacy & Security reviews
2. On-site Notifications: Complete FE connection to BE API
3. Add new Cerner facility to My VA Cerner alert

PTO
- Angela: 3/28, 4/1
- Taylor: 4/1 (half-day)

## Payment Info (#31611)
**PM**
- [x] #38806 Attend Staging review
- [x] #37881 Privacy & Security review
- [x] #38148 UAT go/No Go

**FE**
- [x] #37881 Privacy & Security review
- [x] #39140 Fix Flaky Test

 
## On-site Notifications (#30611)
**PM**
- [x] #38801 Continue to regroup with VA Notify

**FE**
- [x] #36180 Add header for notifications

## Medical Copays (#31611)
**Design**
- [ ] #38984 Explore adding amounts

## My VA Audit (#38967)
**Design**
- [x] #38969 Audit Nametag
- [x] #38970 Audit Claims and appeals

## Cerner Alert update (#39141)
**Design**
- [x] #38508 Add Walla Walla to Cerner

**FE**
- [x] #38508 Add Walla Walla to Cerner

## General
- [ ] #38658 aligning links
- [ ] #38858 Add success/fail tracking 
- [x] #36340 Review various alerts and errors
