### ISSUE TITLE
 Rx Shipment Tracking - (656) St. Cloud, MN

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#30293]
- [x] Send intro email

- [x] Confirm facility POC (Melissa LeFleur)

- [x] Confirm site uses Endicia or has tracking information in VistA

- [x] Funding (i.e. AWS Cloud Credits) -- will be funding in FY22

- [x] Send Email with Checklist

- [x] Advertise Upcoming Feature

- [x] Confirm Go-Live Date [11/01/2021]

- [x] Configure/Deploy

**Comment by lindsay-insco** [comment]
Gone live
