### ISSUE TITLE
[Tech-Debt} Remove CLC/DOM/Mobile from Ops status page & disable on Menu [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#30309]
## User Story
As a VHA Digital Media web manager, the mobile, clc, and dom systems need to be archived, removed from Operation status, and remove from Menu (Locations), so a new experience can be created for these products.

## Goal
Remove tech-debt for all new hardened policies pages.

## Resources - Tools - Documentation
TBD

## Tasks
- [ ] Remove all operating status listings of mobile/clc/doms
- [ ] Archive Moble/clc/dom facility pages
- [ ] Disable menu selections for these facility types.

## Acceptance Criteria
- [ ] All mobile/clc/dom facility types are archived and not visible
- [ ] These types are NOT deleted so they can be pulled back into new product type when ready.

**Comment by ltrombley** [comment]
Task #30309 -  Remove CLC/DOM/Mobile from Ops status page & disable on Menu [BA] - is Complete and moved to Validate
