### ISSUE TITLE
[Quality Assurance Audit] Post Production Audit Part 2 of VAMC VA Lebanon for links, standards, and design standards.[BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#30323]
## User Story
As a VHA Digital Media web manager, the system websites need to be audited for standardization and mistakes, so websites can be updated an corrected to meet design standards.

## Goal
Remove deviations from standards. 

## Resources - Tools - Documentation
[Audit Part 1 checklist](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FQA%5FDocuments)

## Tasks
Using the audit Part 1 check list, review all pages that appear to be written or added after dual-state publishing. Use input from BA team to determine pages that need most attention. (Pass or Fail) web pages and profide notes:

**PART TWO**
- [ ] Review all pages for content and plain language standards
- [ ] Add Content to word document to track changes and use as document to train customer.
**Focus on new pages, or pages that were changed/created**

## Acceptance Criteria
- [ ] Rename the file with new Date/ audit final [date] and save in:
[QA_Documents folder]
- [ ] Content has completed review of new/changed pages
- [ ] Word Document(s) with corrections/proposed changes is saved in QA Documents folder

**Comment by larrywest52** [comment]
DONE
