### ISSUE TITLE
526 Claim submission support

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30334]
## Issue Description
Email (sent to Anna and forwarded to Michel) from Paul Shute requesting assistance with Veteran support:

A Veteran reached out to me about an issue he’s encountering filing a claim on VA.gov. When he attempts to file the claim, he receives the error message below. When I checked his VBA record, his date of birth is available.

---
## Tasks
- [ ] Troubleshoot submission error

## Acceptance Criteria
- [ ] Issue resolved.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Root cause: the veteran does not have a date of birth in MPI or the identity provider. VBMS does have a date of birth, but we don't typically get DOB from them for form 526.  I think the correct thing to do would be to update the FE text to call an identity related number. 

Asked VSP-contact center
https://dsva.slack.com/archives/CNCEXNXK4/p1632318265021500

 ![image](https://user-images.githubusercontent.com/19188/134358873-f708abf2-f484-4205-bb49-c9e4b9274167.png)

**Comment by vhenry07** [comment]
Root cause and MPI contact passed on to Paul.
