### ISSUE TITLE
Connect redux to endpoint data

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30344]
## Issue Description
This is a follow up ticket to fetch copay data from the medical copays endpoint `/v0/medical_copays` when available

- [VBS.Api Swagger Docs](https://yf7yvyucfj.execute-api.us-gov-west-1.amazonaws.com/Prod/swagger/index.html)
- [Mock](https://preview.uxpin.com/18073b171729031ac0af64822d31a7427b012d66#/pages/139873795/simulate/sitemap?mode=i)

---
## Tasks
- [ ] data rendered on FE should be coming from the medical copays endpoint

## Acceptance Criteria
- [ ] redux is configured to fetch copay data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
