### ISSUE TITLE
[BE] Version vets-api  controllers and routes to basic V2

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#30353]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- Version the Check-in module to Version 2

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Version Check-in controllers to V2
- [x] Setup routes and namespaces under V2
- [x] Setup settings and configuration for V2

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] FE engineering team has signed off on the  feature
