### ISSUE TITLE
Initial Discovery Tasks for SEP

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30358]
## Background
We need to start discovery on SEP and should spend some time breaking down all the parts that need to be analyzed and addressed

## Considerations
- https://www.sep.va.gov/sep/web/guest/sep

## Tasks
- [ ] Identify users, flow and functionality
- [ ] Organize initial documents

## Acceptance Criteria
- [ ] Results have been shared with the Team

**Comment by candy-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-POA/SEP
