### ISSUE TITLE
Sync Mockups for Search Rep

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30360]
## Background
Now that we have some feedback from VSOs, we need to solidify the content for the update representative feature with Content folks.

## Tasks
- [ ] Work with Beth to get new content for rep prototypes based on VSO interviews. (Another ticket)
- [ ] Update content in [uxpin prototype](https://preview.uxpin.com/61c3ebf323d3662f44e38a8cbb28a7d326533703#/pages/140758443/simulate/sitemap) (<- that is the mobile mockup, I need to get Jim's desktop version link)

## Acceptance Criteria
- [ ] Content and any changelog notes are created and shareable (STRETCH)

**Comment by candy-gcio** [comment]
Workflows and wireframes: https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2
