### ISSUE TITLE
Find a VA Form: Add new PDF Alert to each PDF link on form detail pages 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#30377]
## Issue Description
Our recent user research revealed that users overlooked PDF help text positioned near each PDF link, presumably because it was not visible enough or they ignored it because of past familiarity with Acrobat Reader and PDF.  

Users also overlooked or ignored info windows positioned at the top of the search page.   We also observed that the majority of users in our research study clicked the detail page link from the search results and downloaded the PDF from there rather than directly from the search results.

This story is to add a modal alert that will be invoked when a user attempts to download a PDF document from a form detail page.  The purpose is to force them to acknowledge the alert and hopefully read its contents before accessing a PDF form.

---
## Tasks
The modal shall: 
- [ ] Be created behind a feature flag so that it can be tested for accessibility using a screen reader
- [ ] Be based on a recent mockup #29704 and will follow the [Modal definition](https://design.va.gov/components/modal) in the design system
- [ ] Be invoked when a user attempts to download any PDF from any Find a VA Form detail page.   
- [ ] Be accessible and easily dismissible for all users, including those using screen readers
- [ ] Function as a buffer between the detail page and the actual PDF.  The PDF cannot be downloaded without clicking the PDF action link contained in the modal.
In addition:
- [ ] The PDF action link will behave in the same manner as the PDF action link currently in Production (will use the "download" property to attempt to download the PDF rather than open in another tab or the parent window)

## Acceptance Criteria
- [ ] The modal will only be visible on Staging
- [ ] The modal will appear any time a user clicks a link to download a PDF
- [ ] The modal will contain a way to dismiss the modal, access the Resources & Support PDF page, and will have a link to the appropriate PDF file that will download to the user's local machine if technically feasible.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by zacharymorel** [comment]
Discovery => https://github.com/department-of-veterans-affairs/va.gov-team/issues/29707#issuecomment-923083885

**Comment by MarciMcGuireGCIO** [comment]
How do @zacharymorel! Angela Fowler took this for a spin earlier and noted a small typo (no worries since the final copy is still TBD), and also said the modal doesn't pop up on every PDF click.  

I've asked if she knew any specific examples, so I'll update if I get more information.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Oh weird fluke then.... I'll keep my eye out. 
As far as @AngelaFowler82 taking it for a spin, I am happy she had the time to do that. I'm excited that we can finally get somewhere further after the user research with this issue.

**Comment by zacharymorel** [comment]
Team, this is also in a state ready for validation.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel ! Content is still working out the final verbiage, but we can close this and I'll create a new one for tweaking the text.
