### ISSUE TITLE
[Research] Profile: Research plan + conversation guide for contact info edit-in-place functionality

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30373]
## Background 
(Part 2 of 2 issues) In #26914 we did some initial discovery ([documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/discovery/improving-editing-mid-task.md)) around edit-in-place functionality.  

We determined that the next step would be to conduct usability testing for the existing modal solution, and possibly the in-line editing flow.  Proposed test flows:

- Notification settings (simple task, one field)
- Form flow (updating within form flow, and during review stage at the end of the flow)

Ideally, we'll also include some other smaller things to test that we wouldn't normally create an entire study flow. Ideas captured in this [possible research document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/possible-research.md).

This could also be tied into research for the first post-MVP iteration of notification settings.

**Tasks**

- [ ] Draft research plan (including figuring out whether or not it makes sense to _also_ test the in-line editing solution. At this point I'm thinking it does not since it would double the amount of work needed to create a prototype and adds significant complexity to the research plan/tasks.)
- [ ] Draft conversation guide
- [ ] Review with team + OCTO PO
- [ ] Finalize docs to prepare for submission to Lauren Alexanderson/Perigean

**Comment by niradatta1** [comment]
@ajakabcin Hi there, 

We finished the edit design pattern as part of our pre checkin usability testing. We didn't observe any major usability issues, and all veterans were able to complete their tasks. A couple commented that this was "straightforward". After being asked to edit information, it seemed to work as expected for Veterans. 

Here's a link to the prototype we tested that includes the edit pattern after clicking on 'Mailing Address' on the Contact info.https://preview.uxpin.com/349cb3520e4ad95ebfb3e7b5dc0a40a2e582ac64#/pages/143334663/simulate/no-panels?mode=cvhidm

When we are able to offer the ability to edit in pre checkin / checkin experience, we'll be switching the the edit modal to a page, so it's in line with accessibility best practices.  @zach-park Is working on those mockups.  

Will be making full research report available soon. Hope this helps!  'cc @ytsaoca @kristenmcconnell

**Comment by andaleliz** [comment]
Thanks @niradatta1! @ajakabcin is on leave and won't work on profile when she returns - @MarciMcGuireGCIO is the new PM for that team, just FYI.

**Comment by andaleliz** [comment]
@niradatta1 am I correct that the modal was not approved in the collaboration for your team, in favor of a new page? I'm just wondering if the modal is even something our team should consider anymore.  Thanks!

**Comment by niradatta1** [comment]
@andaleliz Yes, that is correct. The concern is that the modal presents accessibility issues, and so it was decided to proceed with a page design after a veteran selects edit. Hope that clarifies, please let me know if you have any other questions. 'cc @kristenmcconnell @ytsaoca

**Comment by andaleliz** [comment]
Thanks @niradatta1 - are we retiring modals from VA.gov then? Or improving the modal? Just trying to get a sense of what the issue is. We have other modals in profile.  If there are docs available I'm happy to read through them. Thanks!

**Comment by niradatta1** [comment]
Good question -- I think that's going to be part of a larger discussion, but I'm not sure if that's been initiated as of yet. 
@kristenmcconnell Do you have thoughts here?

**Comment by MarciMcGuireGCIO** [comment]
On a related note, we are introducing a modal on Find a VA Form, but only after testing inline options that the majority of users totally overlooked.  

Angela Fowler was heavily involved in the user testing where users missed inline info, and after discussion with Ryan, we all agreed that in this particular circumstance, there really was no better option.

To my knowledge, modals aren't being totally retired, but they definitely aren't the preferred option.

**Comment by kristenmcconnell** [comment]
I don't have any additional information on the overall status of modals. It seems like Marci might have a good use case for them. We really just determined that check-in/pre-check-in would utilize a page design, similar to "Request for Higher-level Review."

**Comment by andaleliz** [comment]
Closing this out as it's outdated and we likely won't explore a modal solution when we get to this.
