### ISSUE TITLE
[Kubernetes] Gather calico metrics to datadog 

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30375]
## Description
The goal here is to open up the calico metrics endpoint to datadog agents so we can create a dashboard for them.  However there are a few extra steps that will come with this.  It is highly suggested to lock down the calico /metrics endpoint so it is only reachable from the datadog agents themselves.

https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics
https://docs.projectcalico.org/security/comms/secure-metrics

---
## Tasks
- [ ] open up metrics endpoint for calico
- [ ] install calicoctl
- [ ] create policy on metrics endpoint that allows only datadog agent to reach it

## Acceptance Criteria 
- [ ] metrics from calico are being sent to datadog
- [ ] policy to secure metrics endpoint is in place

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics
Felix metrics are being sent to datadog  
![image](https://user-images.githubusercontent.com/76792875/142271890-e4e1210d-a9bd-4964-99d1-3f4859f9ade3.png)

However I am still troubleshooting calico kube controller metrics.  Based on the docs these should be enabled by default which aligns with the CRD, but the connection is being refused to the pod.

![image](https://user-images.githubusercontent.com/76792875/142272304-79686dbc-4708-4c26-a5de-5d30f6bdf68a.png)
![image](https://user-images.githubusercontent.com/76792875/142272327-b2167652-144b-4cbc-a9ff-c1551993a74c.png)

**Comment by mleclerc00** [comment]
Updating calico resolved the connection issue I was seeing for the calico kube controllers prometheus endpoint.  They are now being sent to datadog 

![image](https://user-images.githubusercontent.com/76792875/142684977-63347a05-9bcf-4b0a-ba28-1a96f179bf5a.png)


![image](https://user-images.githubusercontent.com/76792875/142682794-c9384f96-d019-4db3-808b-2c9971b502ed.png)

**Comment by mleclerc00** [comment]
Calico metrics are now being sent to datadog.  Will likely need to follow up on this to see if we can create any useful monitors and or dashboards from said metrics.
