### ISSUE TITLE
[Discovery] Design Refactoring for Outreach & Events Hub (Filtering and Recurring Events)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30381]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)

## High Level User Story/ies
As a VA digital comms lead and user of the VA.gov CMS, I need new capabilities and features as a publisher in the Outreach & Events hub, so I can provide information more effectively to my Veteran and caretaker audience.

## Discovery
Review current UX and how might we make the Outreach Hub events calendar more personalized for users (e.g. filtering events by date, time,). This discovery ticket will be to capture design ideas as outlined in the "Product Outline" and to discuss UX on how to personalize the Outreach Hub experience.

CMS Team did some initial work on this HERE: 
[Recurring events.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

## Tasks
- [ ] Design Filtering component for DATE/TIME
- [ ] Design Recurring Events 
- [ ] Provide a sketch design or wireframe in order to PO/PM to visualize recommendations

**Comment by callen2563** [comment]
![Outreach events - Desktop V2](https://user-images.githubusercontent.com/68560244/134441928-70517bb3-67dd-4ffe-bd97-00045ba9d456.png)

**Comment by brianalloyd** [comment]
@callen2563 can we change "Search" to "Filter" events, as that's really the function of this modal.  

![Screen Shot 2021-09-23 at 10 34 53 AM](https://user-images.githubusercontent.com/70410912/134548427-d6489818-3bad-468f-89af-024ae5f9271f.png)

Also we'll need to mock up a design for recurring events and how that might look from a user prospective.  We can discuss more during our link up this afternoon.

**Comment by callen2563** [comment]
V3 - filter by date and time with calendar picker

![Outreach events - Desktop V3](https://user-images.githubusercontent.com/68560244/135299604-fa1dc145-4801-47cf-a2c6-e710fe96e76f.png)

![Outreach events - Desktop V3 Cal open](https://user-images.githubusercontent.com/68560244/135299654-5090ca47-0cfc-4743-913f-e1ec89cb9d69.png)

V4 - filter by month and time

![Outreach events - Desktop V4](https://user-images.githubusercontent.com/68560244/135299753-a7b6b58b-65b2-4955-8e4e-20b485f8d4f6.png)


![Outreach events - Desktop V4 Month selected](https://user-images.githubusercontent.com/68560244/135299787-6acca44b-0bd9-43d0-bfcc-e9326a54c069.png)

**Comment by AngelaFowler82** [comment]
I would be more than happy to help. Can we meet sometime in the next few days and discuss the mark-ups?

**Comment by AngelaFowler82** [comment]
Sounds good. Just grab some time off my calendar when convenient.

**Comment by sporeboy** [comment]
Stubbed-out a hub page for O&E discovery and [initial design work here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/readme.md)

Created outline for O&E design [discovery doc here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o&e-calendar-feature-baseline.md)

**Comment by sporeboy** [comment]
Baselining feature flows in [design discovery doc here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o%26e-calendar-feature-baseline.md)

**Comment by sporeboy** [comment]
Ready to be closed. All tasks/AC complete. Links below to work products:
- [Brief discovery doc outlining baseline feature flow and functionality created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o&e-calendar-feature-baseline.md)
- [Diagram uses cases and high-level feature flows](https://xd.adobe.com/view/32a7ce8e-7df2-4a7e-ad3f-ef42fa09c753-67f4/screen/06a28bfa-0367-4077-9dfe-e2a99c54b1dd)
- Wireframe UI suggestions illustrating features (including date/time filtering) in context. [Filtering feature](https://xd.adobe.com/view/32a7ce8e-7df2-4a7e-ad3f-ef42fa09c753-67f4/screen/f1253770-f429-4ef3-86e0-8980e8c4b3a1) and [Recurring events](https://app.mural.co/t/vsa8243/m/vsa8243/1634651992163/439beeb6c6f54295c81a2b62d2d4c766f6b23205?sender=u0f20e7e71fbe03bbc4016208)

Diagrams, wireframes and links are included in the discovery doc. [Direct link to full recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o&e-calendar-feature-baseline.md#recommendations)
