### ISSUE TITLE
[BE]

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#30384]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- Create an API to API call to refresh the LoROTA data for a given user's UUID on the Check-in services layer.
- This call must happen if the call to check if a user's session exists returns true.
- Vets API Check-in V3 service layer must have the ability to invoke a CHIP endpoint with appointment data(patientDFN and stationNumber) already stored in Redis and have CHIP refresh LoROTA with the latest appointment statuses for the user.
- Once CHIP updates LoROTA with the latest appointment data for the user, vets-api must make a service call to LoROTA to fetch this data and then return it back to the UI.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Write rspec tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] FE engineering team has signed off on the  feature
