### ISSUE TITLE
[BE] Format multiple appointment data received from LoROTA

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#30386]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- Vets API must handle receiving an Array of appointment data from LoROTA and passing it to the vets-website, formatted.
- Use a serializer if necessary to parse out sensitive information like the `patientDFN` and other attributes as deemed necessary.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Write rspec tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] FE engineering team has signed off on the  feature
