### ISSUE TITLE
Fix broken link on SGLI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30388]
## Issue Description
There is a broken link for milConnect in the process list of the [Servicemembers' Group Life Insurance]( https://www.va.gov/life-insurance/options-eligibility/sgli/) page. 

The new url should be: https://milconnect.dmdc.osd.mil/milconnect/
---
## Tasks
- [x] Update link in process list
- [x] Review and publish
- [x] Notify stakeholders that page is live

## Acceptance Criteria
- [ ] New link is working on live page

**Comment by RLHecht** [comment]
Page is live. Closing ticket.
