### ISSUE TITLE
Find a VA Form: Create Slide Deck to Summarize PDF Audit Findings

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#30403]
## Issue Description
- Create a slide deck that summarizes the findings of the PDF audit at a high-level view appropriate for VA stakeholders

---
## Tasks
- [ ] Create a PowerPoint presentation using the data collected in the Sept 2021 PDF audit

## Acceptance Criteria
- [ ] Create audience-appropriate slide deck
- [ ] Summarize findings
- [ ] Describe how the findings impact Veterans
- [ ] Include possible solutions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
