### ISSUE TITLE
Implement Login.gov IAL1 authentication

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#30408]
## Issue Description
This issue is the first part of our initial Login.gov rollout; our initial implementation will use the double-verification process currently in use with ID.me, except with IAL1/IAL2.This issue will cover the first IAL1 trip through ISAM's response to the `saml_callback` function, ticket #30412 covers the upleveling process from IAL1 to IAL2 with Login.gov. Future planned changes to the LoA/IaL verification process to make it more efficient have been discussed but will be broken out into future tickets - the purpose of these two is to get a functional Login.gov/ISAM implementation up as quickly as possible.

---
## Tasks
- [x] Add Login.gov routing and handling in `v1/sessions_controller`
- [x] Update SAML header creation to include Login.gov as an IDP
- [x] Update `saml_callback` and `user_login` methods to handle Login.gov logins and successfully authenticate Login.gov users

## Acceptance Criteria
- [x] A user will be able to create a Login.gov account and use it to log into va.gov
- [x] A user will be able to use an existing Login.gov account and log in at LoA1
- [x] The `v1/sessions/login/new` route will be available for use by `vets-website` or other consuming applications

**Comment by nsoutouras** [comment]
Moving from test instance to staging instance.  Seeing issues with redirect on return trip.  

_Potentially_ blocked by IAM.  Will validate at mid-sprint check in.
**Carries to Sprint 62.**

**Comment by bramleyjl** [comment]
IAL1 SAML headers have been added to the ISAM call and are successfully passed through to Login.gov - on the return to ISAM we are encountering a 302 error and cannot complete the trip back to va.gov. Currently in talks with ISAM and Login.gov teams on how to resolve the issue, blocked for now.

**Comment by nsoutouras** [comment]
@bramleyjl to update by EOD 10/18

**Comment by bramleyjl** [comment]
The IAM team has updated ISAM to handle the Login.gov credentials and pass a successful authentication back to vets-api, as such I am now able to login as an IAL1 or IAL2  verified user with Login.gov. However, there appear to be two separate issues, both of which have I believe are related to an external service partner:

First, the usage of the `authn_context_comparison = minimum` header does not appear to be functioning properly. Our SAML headers are asking for IAL1 with `minimum` so that if a user is IAL2 ISAM & Login.gov will handle the upcert and return to us an IAL2 response. Instead, asking for IAL1 will only return a response with an IAL1 and a "user maximum IAL" of 1 as well, despite the user in question being IAL2. If I change the headers to ask for IAL2 and authenticate with the same user they will come back as IAL2 with additional attributes. I followed up on this on int.eauth.va.gov/IAM and was able to confirm that ISAM is regarding my user as either current & max LOA1 or LOA2 depending on which IAL the SAML headers specified.

Second, we are having problems pulling my user's data from MPI, despite the IAL2 possessing the ICN neccesary to query MPI. I tracked the flow through our request logic and we appear to be building the request properly - nothing in that logic has or should need to change since all that is necessary is an ICN. The MPI response is always a 404, not a 500 or some other authentication or configuration-based error. I'll keep digging into this one, but I suspect that additional work needs to be done between ISAM and MPI in order to create the account in MPI that vets-api is attempting to look up.

**Comment by bramleyjl** [comment]
IAL1 logins are currently working on localhost & dev but encountering an error on the return to ISAM on staging:

![image.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/e6574f74-5fab-446e-8b02-383a4309bf8b)

**Comment by joeniquette** [comment]
IAM stated they haven't implemented IAL1 logins on staging as of 11/8

**Comment by nsoutouras** [comment]
Carries to next sprint
