### ISSUE TITLE
[RESEARCH] Check-in Phase 2 & 3 UAT and Phase 4 Usability Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#30419]
## User Story
- As a Veteran, I want to feel secure when checking in for my appointment. (additional identity verification steps)
- As a Veteran, I want to be able to use my mobile phone to check in for all of my VA appointment that I have within any given day. (multiple appointment feature)
- As a Veteran, I want to be able to review my contact information on my phone instead of having to speak with an MSA. (the first phase of pre-registration feature- read only review of contact information).
- As an MSA, I should have minimal impact to my workflow due to the mobile check-in product and be able to successful manage check-in and pre-registration at my clinic.
- As a product development team, we want to know if the additional identity verification step and ability to check-in for multiple appointments in one day is meeting the needs of Veterans and staff now that the features are live at the pilot site.

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
  - How are the additional identity verification and multiple appointments features doing now that they are live at the pilot site?
  - What is the impact to Veterans and staff?
  - Usability review of the read-only contact information review feature.
  - Usability testing of the revised poster.
    - Is the new poster solving the previously found usability problems or Veterans not understanding how to text and that they should wait for a link to appear in their test message to complete check-in.

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing).
- [x] Create research plan
  - Utilize the new [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) developed by the research ops group.
- [x] Create conversation guide
  - This was the [combined research plan and conversation guide for the last UAT study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-plan.md).

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan and conversation guide to GitHub folder
