### ISSUE TITLE
Add feature flag for Login.gov

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#30411]
## Issue Description
This feature will add a `login_gov` feature flag to Flipper so that the Identity team can gate Login.gov work on the Backend/Frontend for testing, verification, and troubleshooting in higher environments (staging & production)

---
## Tasks
- [x] Add the `login_gov` feature flag in the `config/features.yml` with a description.
- [x] Ensure only enabled in development and disabled in higher environments

## Acceptance Criteria
- [x] I can hit the `/flipper/features` endpoint and see the `login_gov` on the Flipper Client UI
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
