### ISSUE TITLE
Implement IAL2 upleveling with Login.gov

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#30412]
## Issue Description
This issue is the second part of our initial Login.gov rollout; our initial implementation will use the double-verification  process currently in use with ID.me, except with IAL1/IAL2. This issue ticket covers the upleveling process from IAL1 to IAL2 with Login.gov. 

---
## Tasks
- [x] add `verified_at` attribute to User Identity models & attribute check in `should_uplevel?` method
- [x] add `LOGIN_GOV_IAL2` authn_context in relevant config files
- [x] split upleveling authentication route into discrete ID.me/Login.gov workflows
- [x] create Login.gov IAL2 verification SAML headers
- [x] if necessary, add additional handling in `saml_callback` route for incoming IAL2 responses

## Acceptance Criteria
- [x] A user will be able to use an existing Login.gov account and log in at LoA2
- [x] A user will be able to uplevel an existing Login.gov IAL1 account to IAL2
---

**Comment by bramleyjl** [comment]
Currently blocked pending ISAM including the `verified_at` attribute into the LOA1 Login.gov response SAML.

**Comment by bramleyjl** [comment]
I've developed as far as I could using a mocked `verified_at` attribute and have made it to the point of making the second call out to ISAM - at this point we need to know exactly what the SAML headers for the Login.gov verification call, my first attempt was to copy the existing `idme_loa3` pattern exactly:

```
<samlp:RequestedAuthnContext Comparison='exact'>

<saml:AuthnContextClassRef>logingov_ial2</saml:AuthnContextClassRef>

</samlp:RequestedAuthnContext>
```

but this was not accepted by ISAM. I then added the Login.gov `AuthnContextClassRef`:
```
<samlp:RequestedAuthnContext Comparison='exact'>

<saml:AuthnContextClassRef>logingov_ial2</saml:AuthnContextClassRef>

<saml:AuthnContextClassRef>https://eauth.va.gov/csp?Select=logingov3</saml:AuthnContextClassRef>

</samlp:RequestedAuthnContext>
```

which was passed through to Login.gov, at which point it encountered a `Authn context: Unauthorized authentication context` error. I suspect that additional work will need to be done either by IAM or Login.gov to make this route work, but will continue to experiment with different authn contexts in the meantime.

**Comment by nsoutouras** [comment]
May be unblocked, carries to next sprint

**Comment by bramleyjl** [comment]
We believe ISAM is incorrectly interpreting vets-api's IAL2 call and returning the IAL1 user it already has from the first vets-api call instead of making a call to Login.gov for the upleveled IAL2 user, this is preventing us from using the `ForceAuthn = false` headers to upcert a user without authenticating again. IAM has been provided with an example of the calls made and is investigating the issue.

In addition, I will to refactor the `verify_url` code block to no longer rely on the authn_context passed back by ISAM, this will resolve the issue of the unexpected authn_context value. ISAM's response already includes a `type` attribute that denotes the specific CSP and whether or not it was a 2FA, this is a better attribute to use to derive the `verify_url` SAML headers from.

**Comment by bramleyjl** [comment]
User Login.gov account verification (manual, not from saml_callback) is currently being blocked by ISAM returning different `authn_context` values for localhost versus other environments. Related PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/8474
