### ISSUE TITLE
Redesign Several Existing Test Specs with New Cypress Design Pattern

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30424]
# Description
We should dogfood the [prescribed design pattern](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/30434) for test specs.

## Tasks
- [x] Select a candidate test specifications for refactor
- [x] Discuss the candidates with other team members
- [x] Refactor the best candidate to use the new design pattern
- [x] Submit a PR for review by FE Tools and the relevant VFS team
- [x] Select two additional test specs to refactor
- [x] Submit a PR with the two additional test specs refactored

**Comment by pjhill** [comment]
> @pjhill that PR refactored four tests for one feature. Should we identify two more feature test suites that can be refactored, or is one PR with multiple tests sufficient for using as an example in our documentation?

I think the aim is to see the pattern applied to a diverse and representative sample of products on the Platform. I believe you've indicated previously that it's difficult to find prime candidates for a re-design, but does it seem like an attainable goal to re-design a couple more test specs?

**Comment by pjhill** [comment]
Thanks!
