### ISSUE TITLE
Migrate E2E Specs to Recommended Pattern

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30422]
## Problem Statement 
VA.gov's Cypress end-to-end test specs are not consistent in their approach to selecting elements and interacting with common areas of a page.

How might we make make the e2e test spec code that VFS teams write easier to maintain, less flaky, and more efficient?

## Hypothesis or Bet
If E2E test specs are more robust and efficient VFS teams will spend less time maintaining the code for the e2e test specs and more time building new features and enhancements to their products.

If VFS teams are producing more robust test specs then VSP will spend less time supporting flaky tests and maintaining inefficient test spec code.

## We will know we're done when... ("Definition of Done")
* Documentation prescribing the method for using Application Actions pattern in Cypress specs has been created
* VFS Teams have been notified of the documentation and asked to migrate to the new pattern
* KPIs are identified and actively measuring to gauge adoption and effectiveness

## Known Blockers/Dependencies 
* No known blockers

## Projected Launch Date
End of Q4 2021

### ... tested?
- [ ] Usability test has been performed (ADD RESULTS LINK HERE)
   - [ ] Any issues have been documented, and blocking issues have been resolved
- [ ] Testing has been done on the documentation to verify it is usable and complete, and revised accordingly
   - [ ] Any issues have been documented, and blocking issues have been resolved

### ... documented? (TBD)

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable
- [ ] Have identified how to track adoption rate, and have begun recording this data
- [ ] Have identified how to track test flakiness, and have begun recording this data
- [ ] Have identified how to track the amount of changes to test specs, and have begun recording this data
- [ ] Have identified how to track lines of code, and have begun recording this data

### Documentation (TBD)
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing (TBD)
* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement
- 25% of VFS teams have adopted the new design pattern one quarter after its release
- Test flakiness would be reduced
- Reduce the amount of changes to test specs
- Reduce lines of code

### Release Plan (TBD)
* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_
