### ISSUE TITLE
Create Revised Cypress Design Pattern Notification and Notify Teams

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30425]
# Description
We need to notify VFS teams that Platform has updated the recommended design pattern for Cypress.

## Tasks
- [x] Determine a window for the release of the revised design pattern
- [x] Create a draft of a message to VFS teams in Slack
- [x] Work with the team to revise the draft and finalize the message. Joe has approved the language of the message.
- [x] Include information about this release in the Team of Teams slide for our team the week before we finish/release it
- [x] Send the notification to the targeted channels --- #vfs-all-teams and #platform-team
- [x] Include link to updated documentation regarding design pattern in notice
