### ISSUE TITLE
IRIS Q&As: Education Coverage, failing grade

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#30420]
**Issue**

Per discussion on Slack, the single Q&A article, **If I fail a class will I have to pay VA back?** was eliminated.

Instead, it should appear in the existing R&S article VA debt management.
Per Beth, it should appear as a note under the accordion menu that has the H2 **Understand your VA debt** 

**Tasks**

- [ ] Beth to get SME approval and draft copy

- [ ] Randi to proof and make change in Drupal

- [ ] Randi to publsh

**Acceptance Criteria**

- [ ] Updated page is live

**Comment by bethpottsVADEPO** [comment]
Here's the content:
If you finished the class, you won’t have to pay back the GI Bill benefits you used for that class. You can even take the class again using GI Bill benefits.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - FYI, the page views # for this faq is 1082, which is one of the higher ones we have. Confirming that you still want to eliminate http://preview-prod.vfs.va.gov/preview?nodeId=37410 as an article.

**Comment by bethpottsVADEPO** [comment]
I'm closing this because we're reverting back to publishing a single Q&A about this topic.
