### ISSUE TITLE
[DESIGN] Check-in Phase 4 UI Refinement

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#30439]
# Description
- Finalize the UI for Check-in Phase 4, create engineering specifications, and prep a prototype for usability testing.
 - Phase 4 is definition [(complete draft wireframe set)](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/Mya5Oob/play):
  - The ability for a Veteran to review a read-only list of their contact information (mailing address, home address, home phone, mobile phone, work phone, and email address)
    - [A draft wireframe of this as a single page](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/bgW9PE0)
    - Content and interaction patterns are really what need to be finalized. VA.gov patterns to be aware of:
      - Platform is really shifting toward asking one question at a time to reduce cognitive load.
      - Ask Kristen about the mobile big buttons paired with a back button. This started with the COVID screener . Check-in helped test this and still needs to submit to the design system.
- If a Veteran does need to update their information, then they will be directed to a staff member. 
  - This page is already in production, so changes aren't a high-priority with this round of edits unless we think of something compelling.

We also need to think through edge cases:
- If a Veteran doesn't have any contact information in the system (I'm not sure if this is possible though, we might want to check with Shane Elliott)
- If a Veteran is homeless 
  - Some information about this is available in [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1632247976475500)
- 404
- Anything else 

# Tasks
- [ ] Update Sketch with final content and design specifications for engineering
- [ ] Create UXPin prototype

# Acceptance Criteria
- [ ] Review with team (FE, Kristen, Patrick and product)
- [ ] Post link to final designs to check-in Slack channel
- [ ] Link prototype to Phase 4 usability document (which is being created in ticket 30419)

**Comment by ytsaoca** [comment]
@kristenmcconnell 

1. Do we need to make users check one kind of contact information at a time in this phase? Or do we go with a read-only list now, and maybe create screens with one question at a time for user testing?

2. Could you tell me more about "Ask Kristen about the mobile big buttons paired with a back button. This started with the COVID screener. Check-in helped test this and still needs to submit to the design system.

**Comment by kristenmcconnell** [comment]
@ytsaoca 
1. I think we want to stay away from Veterans reviewing each data point at a time. So not..."Is you home address correct?" followed by "Is your mobile phone correct?" We want check-in to be fast, so we should combine as much as possible at this time, particularly, because we aren't giving Veterans the ability to edit any of this information. If any one thing on [this page](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/bgW9PE0) needs update, then it is the same result...go talk to staff. I hope this answers your question.
2. The items circled in red are part of the UI pattern that I was discussing. It is a new way to navigate on VA.gov, but we tested in our check-in workflows and the COVID screener tested it as well. We still need to submit it to the design system, so it is officially added for other teams to use, but we proved that it should be the UI pattern utilized in our workflow. 
![Screen Shot 2021-10-01 at 12.00.14 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/cbb9e88c-ae4d-4f21-b26b-9198dc6bf301)

Previously, the UI pattern was to have Yes and No as radio buttons, then the Veteran would navigate by clicking Back or Continue buttons.

Let me know if you have any additional questions.

**Comment by ytsaoca** [comment]
@kristenmcconnell 
Please correct me if I'm wrong. My task about the UI for Check-in Phase 4 is:
(1) discussing the content with Nira (the meeting will be on Monday) and then edit Sketch accordingly without changing other interaction patterns
(2) creating screens for edge cases
(3) preparing a prototype for usability testing after (1) and (2)

Will you submit the UI patterns to the design system or I can help with this part?

Finally, not related to the tasks here, but I was wondering if it is possible that a user who actually needs to update their contact information or emergency contact uses the "Back to the last screen" button and chose the other option so that they can check-in without contacting a staff member?

Thanks!

**Comment by kristenmcconnell** [comment]
You are correct. Those are the top tasks. 

If you want to submit the UI pattern to the design system that would be great. I already have a [ticket ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/27762)started for that. We could pull it in next sprint or the one after. I can help explain the submission process when the ticket is picked up.

Lastly, yes. At this time, a Veteran could use the back buttons to get around talking to a staff member. We had that discussion awhile and decided to let that happen for now.

**Comment by kristenmcconnell** [comment]
Unless you have a good argument for changing the other UX patterns, I'm always open to better ideas. We just need to finalize the design soon, so we can pass it off to engineering.

**Comment by kristenmcconnell** [comment]
Actually let me regroup...Eva, Nira, and I just met to discuss research plans. We are going to UAT test Phase 4 (after it is coded and not usability test). We wouldn't be able to get feedback back in time to impact when engineering is going to start to build. Therefore, you no longer have to build a UX prototype. 

Your tasks for this ticket are:
(1) discussing the content with Nira (the meeting will be on Monday) and then edit Sketch accordingly without changing other interaction patterns
(2) creating screens for edge cases

**Comment by ytsaoca** [comment]
@kristenmcconnell 

Thank you for the information! And yeah, I'm happy to submit the UI pattern to the design system in the future sprint.

**Comment by kristenmcconnell** [comment]
@niradatta1 @ytsaoca Definitely take a look at the error states and messaging utilized in VA.gov profile. They already have a lot of these use cases, so we should match whatever they already created. Liz Lantz and Tressa Furner would be the designers to talk to about what exists in the profile. You can also check it out in staging.
