### ISSUE TITLE
NOD: Fix bug in name

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30450]
## Description

Fix `showAddIssuesPage` misspelled variable & logic in the Notice of Disagreement form. The function is checking for `constestableIssues` (extra "s") instead of `contestableIssues`. Fixing this requires a fix to the internal logic and unit tests.

## Tasks

- [ ] Rename value to `contestableIssues`
- [ ] Fix logic
- [ ] Fix unit tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
- [ ] Manually test logic
