### ISSUE TITLE
Create a Lockbox.rotate rake task

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#30459]
## Issue Description
A part of key rotation (regardless of KMS or using parameter store) we will need to rotate the encryption keys and then call Lockbox.rotate to re-encrypt attributes with the new encryption key. This  should be wrapped into a rake task for reuse.

See [Key Rotation Docs](https://github.com/ankane/lockbox/blob/75dae4f797136237a76a8bdf3333fbe3e80e4cd5/README.md#key-rotation)

---
## Tasks
- [ ] Create rake task to re-encrypt attrs after rotating keys 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
