### ISSUE TITLE
Add Additional Logging for 686 Notes

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#30453]
## Background
Notes are not showing in Production for MANUAL_VAGOV claims, but they are being added in Linktest.  Additional logging needs to be added so we can determine why notes are not being added in Production. 

## Considerations
Notes only getting added for claims that are set to MANUAL_VAGOV.

## Tasks
- [ ] Add additional logging around the `createNote` service

## Acceptance Criteria
- [ ] Logging has been added for BGS notes
- [ ] A PR has been requested for merging
