### ISSUE TITLE
Content updates for end of debt relief on September 30

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30461]
## Issue Description
The pause on VA debt collection due to COVID-19 is over September 30, 2021. We need to update content on our site to reflect this change. We need to remove all mentions of the date and pausing collection on our R&S pages, benefit detail pages and alerts.

There will also be new FAQs added to the [debt relief options FAQ](https://www.va.gov/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents/). 

List of pages with changes:

- [x] Coronavirus FAQs
- [x] Manage your VA debt
- [x] VA debt management
- [x] VA COVID-19 debt relief options for Veterans and dependents
- [x] Pay your VA copay or subpages
- [x] Dispute your VA copay charges
- [x] Request VA financial hardship assistance
- [x] Chatbot

## Tasks
- [x] Do audit of VA.gov pages with mentions of pausing debt collection
- [x] Update pages
- [x] Add Q&As to FAQs page
- [x] Review and publish changes

## Acceptance Criteria
- [x] All content about debt relief ending September 30, 2021, is no longer on live pages

**Comment by RLHecht** [comment]
These pages have all been reviewed and published.

**Comment by RLHecht** [comment]
This work is all complete. Closing ticket.
