### ISSUE TITLE
526: Discover limits & add limits to form 781/781a schema

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30463]
## Description

Ancillary forms 781/781a within the form 526 flow have been getting data overflow errors

> we received a complaint about a problem with data overflowing a field on a 781 form...
> Fields 8e (description of incident) and 14 (remarks) were identified in the email

EVSS reports that they are unable to reproduce this issue, so the problem could be through VA.gov

- Slack conversation: https://dsva.slack.com/archives/C8R3JS8BU/p1632409886040500

## Tasks

- [ ] Determine character limits for fields 8e and 14
- [ ] Update vets-json-schema all-claims with limits for ancillary form 781/781a
- [ ] Set limitations and error messaging in FE code
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by annaswims** [comment]
No changes are needed.  if the FE submits a form with more next than fits into the form, we put "see add'l info" in the form and attach an extra pdf
