### ISSUE TITLE
Activate CodeSpaces in vets-website 

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#30478]
## Reopening this issue

We had codespaces in vets-website working without vets-api at last check in. This ticket was blocked trying to get vets-api working. Now that teams want to start using codespaces we're reopening it and are going to attempt to get this cooking again.

## Tasks
- [ ] Create a running instance of va.gov inside a codespace
- [ ] Confirm vets-api is working in codespaces

## Enhancement (probably new ticket)
- [ ] Add check to CI if codespace spin up fails

**Comment by timwright12** [comment]
Bringing in @f1337 for vets-api / Docker support here

**Comment by timwright12** [comment]
Opening this back up and going to try to get vets-api running in the container for vets-website

**Comment by mchelen-gov** [comment]
Suggest a follow up issue for adding Codespaces check to CI

**Comment by timwright12** [comment]
**Active working branch:**

https://github.com/department-of-veterans-affairs/vets-website/tree/feature/30478-activate-codespaces-in-vets-website

**Current status:**

vets-website by itself is running in a CodeSpace, but I had to max out the memory to complete the setup process. I'm working on content-build right now (TBD on whether or not we'll be able to get enough memory). Just as before, they still take a _very_ long time to spin up, which is just the nature of the Metalsmith build time. After I get content-build working, I'm going to pull in @mydesignrocks to lend a hand getting vets-api up and running the container.

After all that is up and running, I'll spin up another ticket to auto-spin up in CI (you have to click a button in the UI normally) and we can tune that up appropriately.

I'd also like to get a third ticket going to see if we can speed up the overall creation time.

**Comment by timwright12** [comment]
Just saving this here, it's an endpoint to grab the latest production release of content-build: https://api.github.com/repos/department-of-veterans-affairs/content-build/releases/latest

I was wondering if we could grab the latest built assets from content-build instead of running the 30min+ build in a codespace to speed things up. This isn't the link to do that (the assets are not built), but I didn't want to lose the URL or the idea

**Comment by timwright12** [comment]
This PR gets codeSpaces running again, we still need vets-api wired up https://github.com/department-of-veterans-affairs/vets-website/pull/21958

**Comment by laineymajor** [comment]
@mydesignrocks @theodur can you add some info to the body of this ticket (what you've done, what's next, roadblocks)? Thanks!

**Comment by theodur** [comment]
After some tinkering with the image and setup, I was able to get the `vets-api` container along with its dependent services running in CodeSpaces. This was accomplished by using the default CodeSpaces [image](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux) instead of the image built from the `vets-website` Dockerfile. The reason the default image is needed is because Docker needs to be in installed so that the `vets-api` containers can be started within the devcontainer. The default CodeSpaces image comes with Docker and node installed, so we are able to build `vets-website` and start the `vets-api` containers in devcontainer.

The issue we ran into is safely using secrets in CodeSpaces. Even though the `vets-api` containers are working in CodeSpaces, in order for us to get close to normal functionality of the API, we either need to clone the private [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata) repo in the devcontainer, or access the param store to get the same [secrets](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/review-instance-configure/vars/settings.local.yml) that are used in review instances. Both of these options require secrets being added to CodeSpaces, either for cloning the private repo, or getting access to the param store. The problem with making the needed secrets available to CodeSpaces is that they can be exposed in the devcontainer, since secrets in CodeSpaces are [exported as environment variables](https://docs.github.com/en/codespaces/managing-your-codespaces/managing-encrypted-secrets-for-your-codespaces#using-secrets). This means anyone using CodeSpaces in `vets-website` would have access to these secrets, which is a security risk.

Sri [reached out](https://dsva.slack.com/archives/CU1E4CX9U/p1663937257199789) to the GitHub support to see if there's a way to use secrets iatbuild time rather than run time, so that the secrets wouldn't be accessible to CodeSpace users. We haven't received a definitive answer yet.

Here's the branch where the changes to get the `vets-api` containers running were made: https://github.com/department-of-veterans-affairs/vets-website/compare/add-vets-api-to-codespaces
Once the devcontainer is up and from that branch, you can run the `.devcontainer/post-create.sh` script to start `vets-api` and `vets-website`.

**Comment by timwright12** [comment]
@CBonade it was an investigation into replacing review instances. It's actually active already, but we never got vets-api working fully. It's probably safe to close, but you might also consider removing the codespaces work that's already merged into `main`, it would be whatever is inside `/.devcontainer` for vets-website and content-build

**Comment by CBonade** [comment]
Thanks @timwright12 !
