### ISSUE TITLE
[FE] Create React Component to Handle Feature Toggle States

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#30486]
## User Story

- As a Developer, I should be able to easily tell which components will be rendered when a feature flag is enabled and which components will be rendered when a feature is disabled

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create a new React component to handle feature toggles. This should be a compound component with child components to handle **ON** and **OFF** states. Only the **ON** state should render when a feature is enabled and only the **OFF** state should render when the feature is disabled.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create the feature toggle parent component
- [x] Create the ON and OFF state child components
- [x] Update the Check-in index page to use the feature toggle component
- [x] Create unit tests
- [ ] Create e2e tests
- [x] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
