### ISSUE TITLE
[FE] Sunset `lowAuthEnabed` Feature Toggle

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30487]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

In order to keep code clean and moving forward, feature toggles should be sunsetted when no longer needed. We should sunset the `isLowAuthEnabled` Feature toggle. This is effectively removing v0 from the app. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] create sunset guide
- [x] Remove from the `withFeatureFlip` HOC
- [x] Remove from app
- [x] Remove from mocks
- [x] Create unit tests
- [x] Remove/Migrate v0 e2e tests
- [x] Update relevant documentations
  - [x] README
  - [x] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] API is updated. 
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Rough sunset guide for removing FF: 

First PR

1) remove the flip from the generator function 
2) remove from props
3) remove logic from flip
4) Migrate e2e tests

Second PR
remove from platform files

Then remove from API
