### ISSUE TITLE
Create GitHub Team in DSVA Org for New SREs and Add Access to DevOps Repo

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30485]
## Description
New SRE team needs a GitHub Team created with access to write to the `devops` repository.

## Background/context 
See description

---
## Tasks
- [x] Create new GitHub team for new SRE teammates
- [x] Ensure new team can write to the `devops` repo

## Acceptance Criteria 
- [x] Team created with write access to `devops` repo

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Team created: https://github.com/orgs/department-of-veterans-affairs/teams/vsp-sre/members

**Comment by jbritt1** [comment]
Write access to `devops` repo granted 
![image](https://user-images.githubusercontent.com/56260532/134696242-66cce537-b314-4521-9016-d50425d1023e.png)
