### ISSUE TITLE
Hosting/Setup Discovery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30496]
## Issue Description
We need to understand what our hosting solution will be for the entire integrated test environment including `vets-website`, `vets-api`, `content-build`, and the MVP subset of external services. Will we be using AWS? Is the environment ephemeral or persistent? What is the deployment cadence?

---
## Tasks
- [ ] Research what the desired hosting solution for an integrated test environment that operates all necessary system components would look like.
- [ ] Discuss the potential hosting solutions with Operations in order to understand what is possible and maintainable.

## Acceptance Criteria
- [ ] We have a hosting solution designed and documented
- [ ] We have radiated intent about the solution with stakeholders from Ops, FE Tools, and BE Tools
