### ISSUE TITLE
Create new AWS Service Account to support the developer-portal repo

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/va.gov-team#30500]
## Description
Okapi needs to have an AWS Service Account setup so that we may handle the uploading of builds to S3 and triggering of CodeBuild jobs from GitHub Actions.

## Background/context 
https://vajira.max.gov/browse/API-9848
Builds are currently taking a long time due to repeated steps and sequential CI tests. A deploy to production if everything happens perfectly takes about an hour.

## Technical notes
This account would need standard access permissions to these s3 buckets and also the ability to trigger CodeBuild jobs via the aws-cli

```
dev-developer.va.gov
staging-developer.va.gov
developer.va.gov
developer-portal-builds-s3-upload
review-developer-va-gov
```

---
## Tasks
- [ ] Create the account
- [ ] Apply proper permissions

## Acceptance Criteria 
- [ ] Account is able to upload/download from the above listed boxes
- [ ] Account is able to trigger CodeBuild jobs

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by gileswells** [comment]
^ This PR is but a part of the work that this user would be used for. Another PR will be coming once this service account is created.

**Comment by evelez-va** [comment]
https://vajira.max.gov/browse/API-10482

**Comment by evelez-va** [comment]
> https://vajira.max.gov/browse/API-10482

GHA service account created with corresponding permissions on this PR
