### ISSUE TITLE
External Services

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30503]
## Issue Description
We need to plan for how the test environment will provide test services for services outside of `vets-api`. Various of our service partners provide lower environments that we can integrate with. However, control over the test data that exists in those lower environments is almost non-existent. Correlating test identities with that data can also be a struggle.

---
## Tasks
- [ ] Determine how we can provide system integration testing that is more robust in a test environment.
- [ ] Select a subset of external services to provide the proposed solution for in the MVP.
- [ ] Spec out the infrastructure required to provide testing against those services.

## Acceptance Criteria
- [ ] A list of external services that we will provide system integration testing for is created.
- [ ] Infrastructure required for each external service has been described.
---
