### ISSUE TITLE
Reworking vaccine mini hub main page 9/24/21

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30508]
## Issue Description
Now that we've created a child page to the mini hub with more information, we have reworked the [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page, taking off some content and reorganizing the accordions. There is some new text that has been added that will also need to be translated. 

## Tasks
- [ ] Rework page (Danielle)
- [ ] Review and publish (Randi)
- [ ] Send text to translators (Randi)
- [ ] Update chatbot (Selina)
- [ ] Input text on Spanish page (Selina)
- [ ] Input text on Tagalog page (Selina)
- [ ] Review and publish translated pages (Randi)
- [ ] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [ ] Updated English page is live
- [ ] Updated translated pages are live
- [ ] Updated chatbot is live

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy ready for you:

[https://app.zenhub.com/files/133843125/8c852d4e-efa4-4188-aed5-3acba0f7b60a/download](https://app.zenhub.com/files/133843125/8c852d4e-efa4-4188-aed5-3acba0f7b60a/download)

[https://app.zenhub.com/files/133843125/86d35852-92f5-43ac-bbfb-8c482a26cdc6/download](https://app.zenhub.com/files/133843125/86d35852-92f5-43ac-bbfb-8c482a26cdc6/download)

**Comment by lunascoop** [comment]
@RLHecht these updates are ready for review

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
Thanks @lunascoop. These pages are reviewed but I am holding off on publishing until the new About COVID-19 vaccines page is published since we link to it from this page.

**Comment by RLHecht** [comment]
The Spanish page is now published. Waiting on 2 translations before we can publish the Tagalog page.
