### ISSUE TITLE
Create prototype for Login.gov Usability test #2

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#30506]
## Issue Description
Create a high-fidelity prototype of the addition of the Login.gov button for the Research Plan outlined by Amanda.

---
## Tasks
- [x] Create desktop prototype
- [ ] Create mobile prototype
- [ ] Generate PNGs (or preferred format) for usage in Optimal*
- [ ] Hook-up first-click testing for desktop prototype work with Amanda for question/tasks
- [ ] Hook-up first-click testing for mobile prototype; work with Amanda for question/tasks

## Acceptance Criteria
- [x] There is a desktop prototype in Figma
- [ ] There is a mobile prototype in Figma
- [ ] The questions/tasks are in place to create the test for Perigean
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
Carries forward to Sprint 62 - Design change is ongoing as are test scenarios.

**Comment by AGarcia-Clarity** [comment]
Confirm with Amanda if we're doing the unmoderated test.

**Comment by AGarcia-Clarity** [comment]
Update. We're moving forward with unmoderated tests broken into 2 sections.  Confirm with Amanda if we're moving in the Collab cycle.
