### ISSUE TITLE
Spouse Income section renders if married false

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30501]
## Issue Description
When asked the question "Are you married?" in the spouse information section, if "No" is selected the spouse income section still renders and should not render

---
## Tasks
- [ ] Verify all spouse sections should be hidden if married false

## Acceptance Criteria
- [ ] All sections related to spouse should be hidden if married false
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
