### ISSUE TITLE
[Datadog] Set up synthetic endpoint monitors for prometheus

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30505]
## Description
We have been periodically seeing crash recoveries happening on the [utility prometheus instance](http://prometheus-utility.vetsgov-internal:9090/).  For visibility sake while prometheus is still around before migrating everything to datadog.  While we are at it, seems to make sense to set this up for all environments.  With that being said I'm not sure this should alert pager duty since the crash recovery is not something we can take action on.

Maybe if the endpoint is reachable and returns "service unavailable" just send slack message. If down completely alert to pagerduty.

![image](https://user-images.githubusercontent.com/76792875/134718268-f2d699bc-dd14-4526-be1e-f37a0b0ff2af.png)

![image](https://user-images.githubusercontent.com/76792875/134713811-e6c8a831-cb86-4470-88f7-2eaaa33393ba.png)

## Background/context 
- https://dsva.slack.com/archives/CBU0KDSB1/p1632498252135700 

---
## Tasks
- [x] set up synthetic monitors in datadog for all prometheus endpoints

## Acceptance Criteria 
- [x] alerts go to on call channel but not to pagerduty?

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
