### ISSUE TITLE
Build and translate new About COVID-19 vaccines child page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30507]
## Issue Description
We have created a new child page in the vaccine mini hub titled [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/). We need to translate this in both Spanish and Tagalog and add or update questions to the chatbot based on this page. 

## Tasks
- [x] Write and build page in Drupal (Danielle)
- [x] Review and publish page (Randi)
- [x] Send content to translators (Randi)
- [ ] Update chatbot with new questions or changes
- [x] Input Spanish translation (Selina)
- [x] Input Tagalog translation (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Alert content localization team that translated pages are live (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] New child page is live on the site
- [x] Translated pages are live on the site
- [ ] Chatbot changes are live

**Comment by RLHecht** [comment]
@adamwhitlock1 This is another new vaccine page that we've created. I just sent the text to the translators so it will be a little while before the page is ready to go live. I can @ you here when we publish. FYSA @SKasimow

**Comment by RLHecht** [comment]
@lunascoop Here is the translated copy ready for you:

[https://app.zenhub.com/files/133843125/129b2bb1-d7d0-48fd-b998-8d8c4f99f27e/download](https://app.zenhub.com/files/133843125/129b2bb1-d7d0-48fd-b998-8d8c4f99f27e/download)
[https://app.zenhub.com/files/133843125/5acff4c9-69c0-457e-836a-5ff0c6bc838f/download](https://app.zenhub.com/files/133843125/5acff4c9-69c0-457e-836a-5ff0c6bc838f/download)

**Comment by RLHecht** [comment]
These pages are reviewed. Just waiting on the missing translation pieces before we can publish.

**Comment by RLHecht** [comment]
The Spanish page is now published using Eunice's translations for the 2 remaining pieces.
