### ISSUE TITLE
Adjust Email Language for 686 Errors

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30518]
## Background
We need to update the language for the 686 silent failure email until we know a little more about why the BDN service fails for everyone (including EVSS/EBN) so that the Veteran can call instead of retrying.

## Tasks
- [ ] Update the text and include:  _"Please try again in 24 hours."_

In total:
Dear `name`
We’re sorry. Something went wrong when we tried to submit your application to add or remove a dependent on your VA benefits (VA Forms 21-686c and 21-674).
Your online application didn’t go through because of a technical problem and we aren’t able to access your application.
If you continue to have issues and/or you have general questions about adding or removing a dependent, you can call Veteran Benefits Assistance at 800-827-1000. We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
We’re sorry for the extra work, but after 24 hours, you may need to go back and apply again at https://www.va.gov/view-change-dependents/add-remove-form-21-686c/.
Thank you for your service,
VA.gov
_Note: This is an automated message sent from an unmonitored email account._

## Acceptance Criteria
- [ ] The email language is updated
- [ ] A PR has been requested for merging
