### ISSUE TITLE
Upgrade Grafana to 8.1+

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#30513]
## Description
Upgrade [Grafana](http://grafana.vfs.va.gov/) from 7.5.10 to 8.1+

## Background/context 
There is a bug in Grafana when adding filters through UI: https://github.com/grafana/grafana/issues/37956
This affects [Confluence examples](https://vfs.atlassian.net/wiki/spaces/OT/pages/619119010/Centralized+Logging+with+Loki+-+User+Guide#Using-LogQL%E2%80%99s-built-in-parsers)
Bug is fixed in [Grafana 8.1+](https://github.com/grafana/grafana/issues/37956#issuecomment-907152919)

---
## Tasks
- [ ] Upgrade Grafana to 8.1+
- [ ] Related work to doc Grafana upgrade process: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17236

## Acceptance Criteria 
- [ ] Grafana is updated to 8.1+
- [ ] UI filter addition is tested

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
According to @dginther - it might be good or necessary to bring up an additional instance of Grafana with the desired version (ie "grafana-test") to de-risk any potential breakage of the existing install. 

Workflow might be: 
- bring up grafana-test w/ a clone of the RDS DB that we use for Grafana
- work through any plugin issues (one thing we're aware of is they no longer allow un-signed plugins by default) 
- work through any schema changes 
- work through any security changes 
- make sure everything is working, etc

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Is this something that we can live with for a few weeks? We can likely start working through soon, but want to do so carefully to minimize any disruption. 

I'm thinking we could start picking it up next sprint?
