### ISSUE TITLE
Refactor MHV linkage on VA.gov

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#30522]
## Issue Description
- Non-VA Patients with a Premium credential logged into VA.gov SSOe, should be able to select My Health to go to My HealtheVet Home page logged in.
- Non-VA Patient is able to sign in to VA.gov with ID.me and MHV credentials. However, when the user attempts to jump over to MHV (using the My Health link or any other link that navigates to MHV) is where VA.gov throws an error as seen below.

---
## Tasks
- [x] Update AuthApp
  - [x] Replace AlertBox component with web component
  - [x] Remove MHV error code 101 from presenting on Vets-Website
- [x] Change My Health link to go to MHV
  - [x] Update in mega-menu.json 
  - [x] Update in Dropdown Personalization menu
- [x] Modify ValidateMHVAccount component to redirect to MHV (just in case it gets landed on, ticket to remove is here https://github.com/department-of-veterans-affairs/va.gov-team/issues/31523)
- [x] Refactor authentication/utilities
  - [x] Add `source` & `redirect` query parameter to track inbound/outbound requests
  - [x] Add a GA event to track inbound/outbound
  - [x] Create reverse MHV url lookup for query params

## Acceptance Criteria
- [ ] When I navigate Inbound (/sign-in/?application=mhv) I am redirected to MHV
- [ ] When I sign into VA.gov and click the My Health link, I am redirected to MHV
- [ ] Using a multiple MHV correlation test account, I do NOT see the Auth error when using Inbound/Outbound
- [ ] I see Google Analytics are tracked on inbound/outbound

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
