### ISSUE TITLE
PagerDuty + Slack Application Deprecation 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30542]
## Description
```
On November 1, 2021, Your current PagerDuty Slack V1 application will be discontinued. We've released the Next Generation PagerDuty Slack V2 application, Details here. Please migrate to ensure you can continue receiving PagerDuty notifications in Slack. Contact support if you have any questions.
```

## Background/context 
https://dsva.slack.com/archives/C30LCU8S3/p1632761346284700 

---
## Tasks
- [ ] PD+Slack app v2 migration

## Acceptance Criteria 
- [ ] No more deprecating PD+Slack app integration alerts in #oncall channel

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
