### ISSUE TITLE
[OS Check] OS-Check Job in Utility Environment Needs Attention

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30540]
## Description
OS-Check job in Utility has been broken quite some time and could use some attention so we can return to paying attention to issues found by this job.

## Background/context 
OS-Check was broken in all environments until recently and was covered in #15954. However, `utility` env has a slew of other issues causing the job to fail unrelated to the changes covered in the referenced ticket. 

---
## Tasks
- [ ] Determine all issues causing os-check to fail in `utility`
- [ ] Fix issues found/observed

## Acceptance Criteria 
- [ ] OS-check job working in `utility` as expected

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
