### ISSUE TITLE
[MDT] Bug - Empty submission error alert isn't displaying

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#30553]
## Issue Description
Steps to recreate this bug: 
1. Sign into test-user-1 
2. Navigate to the MDT ([link](https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/))
3. Submit an order without selecting any items

### Screenshot of bugged UI: 
![Screen Shot 2021-09-27 at 2.06.40 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/c1b0a3ab-31d7-4242-b9a1-b11fba5763e9)

### Screenshot of desired UI:
![image (10).png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/4317acd0-716c-4e49-8ce1-846affc9e7a6)

---
## Tasks
- [ ] Add the desired error alert to the UI for empty order submissions

## Acceptance Criteria
- [ ] The desired error alert displays for empty order submissions 
- [ ] The updated UI has been reviewed by Becca or Riley
