### ISSUE TITLE
Frontend App Architecture — Audit static pages app, iterate, and document best practices

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#30572]
## Problem Statement 
The static pages app is an app in the shared code repository `vets-website` that loads on most static pages of VA.gov (that are not an application — such as the homepage, many app landing pages). It contains a lot of shared code from multiple VFS teams, making it difficult to isolate that code. There is little to no documentation regarding best practices for VFS teams using the static pages app. 

How might we iterate on the static pages app so that it meets the needs of VFS teams without blocking further isolation of `vets-website`?

### Notes
* Lots of widgets
* Start with discovery on what each part of the app is doing and why
* May delegate some separation work to VFS teams. Will likely do some of this ourselves.
* What is this supposed to be doing?

## Hypothesis or Bet
* If we clean up the static pages app, then we can better enable app teams to build and deploy changes to only their applications. 
* If we provide VFS teams with robust documentation on how to use the static pages app, then it will not be an app that blocks further isolation.

## We will know we're done when... ("Definition of Done")
* [ ] Static pages app can be included in autonomous deploys
* [ ] Ownership and best practices are defined and documented

## Known Blockers/Dependencies 
* Will require coordination with VFS teams at minimum, may be dependent on VFS teams completing some of the work

## Projected Launch Date
* Late Q4 2021

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 
   * Platform Objective 2 (KR:  >=1 VFS team can deploy their frontend app code at any time during business hours without manual Platform intervention.)
   * Site performance
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by k80bowman** [comment]
I've created a [Frontend Baseline dashboard](https://app.speedcurve.com/va/va-admin/favorite/?cs=md&d=90&db=840723&dc=2&de=1&df=%7B%7D&ds=1) in Speedcurve to track performance metrics for several pages:
- https://www.va.gov/
- https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
- https://www.va.gov/education/how-to-apply/

**Comment by laineymajor** [comment]
@rmessina1010 are you aware of work currently happening with this?
