### ISSUE TITLE
HLR v2: Remove legacy question from wizard

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30597]
## Description

The Higher-Level Review form v2 will allow adding issues and an additional question regarding opting into the new appeals process, so the question in the wizard blocking Veterans from filing an online Higher-Level Review form needs to be removed.

## Tasks

- [ ] Dynamically remove legacy appeal question from wizard for v2
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
