### ISSUE TITLE
Update to Chapter 33 page about how much of a benefit one qualifies for

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30599]
## Issue Description
On our [Post 9/11 GI Bill Chapter 33 page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) we explain that how much of the benefit a Veteran qualifies for will change after August 1, 2020. We need to update this text to remove this date. We should also consider revising the content so we link to the R&S article [How we determine your percentage of Post-9/11 GI Bill benefits](https://www.va.gov/resources/how-we-determine-your-percentage-of-post-911-gi-bill-benefits/).

![Screen Shot 2021-09-28 at 10.39.56 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d5cadeb5-b435-4d63-8b33-e56b539ad209) 

## Tasks
- [ ] Update content on Chapter 33 page
- [ ] Review and publish

## Acceptance Criteria
- [ ] New content is live on production

**Comment by RLHecht** [comment]
@lunascoop Can you remove the text that is in the screen shot above and replace it with the link text that's in the top of this ticket? Thanks!

**Comment by bethpottsVADEPO** [comment]
@lunascoop Link label should go in the same location as the text you removed and should be: Find out how we determine your percentage of Post-9/11 GI Bill benefits

**Comment by lunascoop** [comment]
@RLHecht this change is ready for review.

Post-9/11 GI Bill (Chapter 33): http://preview-prod.vfs.va.gov/preview?nodeId=935

**Comment by RLHecht** [comment]
@lunascoop Can you please make one other change on this page? We need to change the bulleted list in the featured content box so that we start each bullet with "You" instead of having it at the end of the intro line. We've been updating this throughout the site as we find them on pages we are working on. So it would be like the following:

At least one of these must be true:

- You served at least 90 days on active duty (either all at once or with breaks in service) on or after September 11, 2001, or
- You received a Purple Heart on or after September 11, 2001, and were honorably discharged after any amount of service, or
- You served for at least 30 continuous days (all at once, without a break in service) on or after September 11, 2001, and were honorably discharged with a service-connected disability, or
- You're a dependent child using benefits transferred by a qualifying Veteran or service member

Note that I made the last one You're instead of You are. Thanks!

**Comment by lunascoop** [comment]
@RLHecht the page is updated and ready for review again.

**Comment by RLHecht** [comment]
This page is published. Moving to validate.
