### ISSUE TITLE
[FE] Add e22 test for different Apponment States

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30601]
## User Story

As a veteran, I should see all my appointments for the day I am checking into . 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Add e2e tests to show all the different appointment states

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by julieadair1** [comment]
@jparker0425 what epic should this be attached to?
