### ISSUE TITLE
[Design] My VA Alerts: Incorporate an alerts link into the IA/header

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30615]
## Background
We need to determine how we will incorporate a link to the alerts feature in the IA/header.

## Tasks
- [x] Explore ways to show an Alerts link in the navigation
- [x] Meet with Ryan Thurlwell to review discuss ideas for this
- [x] Include IA in conversations 

## Acceptance Criteria
- [x] Updated designs and accompanying documentation

**Comment by ajakabcin** [comment]
@tressaellen I dropped this into the current sprint since we're meeting with Ryan next week about this. Just needs a point estimate from you when you have a moment. Thanks!

**Comment by tressaellen** [comment]
Met with Ryan to chat through design decisions regarding the new mobile header and how to incorporate an alerts link. This is what we landed on - which could change as we move through the design process. 

![Screen Shot 2021-10-05 at 1.08.54 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/03ff012e-d136-4339-8518-797efb7d097b)

**Comment by tressaellen** [comment]
I think we can close this ticket, and the meeting with IA can be tracked in [#30921](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/30921)
