### ISSUE TITLE
[FE, BE] My VA Alerts: Technical discovery around alerts defined for MVP

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30610]
## Background
Once we define which alerts we want to include in MVP we need to make sure we understand how they currently function.

## Tasks
- [ ] Work with VAnotify and VetText to understand how the current APIs work, how to connect to them and/or if we need to build something new
- [ ] Work with VAnotify and VetText to understand content of each alert
- [ ] Work with Design/PM to outline actionability of each alert - if not, put actionable alerts on My VA

**Comment by ajakabcin** [comment]
Removed from sprint as team is pivoting on this work

**Comment by hdjustice** [comment]
As we have moved forward with prototype development and research sessions, the Frontend Documentation has been an ongoing update.  Now that research is complete, we have several design updates that will be needed, and will impact this documentation.
Moving to next sprint so that we can finalize the design and ensure this document reflects those changes.

**Comment by andaleliz** [comment]
Hi @ajakabcin ! I just saw this in my ready column. Is this something I should plan on completing in the upcoming sprint? It's been pushed back several times. Thanks!

**Comment by ajakabcin** [comment]
Hi @andaleliz! I'm not sure, let me look into it and get back to you :)

**Comment by aagosto90** [comment]
Confirmed with @tmitchellgcio that the frontend design for notifications is matching the mockups and intended functionality. The only outlier is that the close button on the notification is not dismissing it yet, but this is because the frontend and backend are not communicating yet and once that it set up, the notification will dismiss when user clicks the X icon.

**Comment by aagosto90** [comment]
FE documentation has been updated [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend/documentation/README.md). I included the copy documentation here and will likely do that moving forward for FE documentation. I deleted the sections for Notification page and Notifications link in header for now. We can add them back in later if we end up adding those features.
