### ISSUE TITLE
[Kubernetes] Update calico infra repository

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30617]
## Description
Calico infra repository needs GHA to mirror images to ecr and update the manifests repo.

---
## Tasks
- [x] create GHA to mirror images to ecr
- [x] create GHA to update deployment in manifests repo 

## Acceptance Criteria 
- [x] images are mirrored to ecr when versions.json is updated
- [x] GHA automatically updates dev when new images are defined and a manual workflow_dispatch for the rest of the environments

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
GHA have been added to the infra calico repo to allow for mirroring images and deploying to the manifest repo.
