### ISSUE TITLE
Content updates to home loan limits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30614]
## Issue Description
We need to make an update to our [VA home loan limits page](https://www.va.gov/housing-assistance/home-loans/loan-limits/). Currently, at the top of the subway map we have 2020 VA home loan limits. This should be changed to 2021. We also need to change the link text to "Check current loan limits" to avoid sighted language. 

## Tasks
- [x] Change year to 2021
- [x] Change link text

## Acceptance Criteria
- [x] Content updates are live on production

**Comment by lunascoop** [comment]
@RLHecht this change is ready for review.
VA home loan limits: http://preview-prod.vfs.va.gov/preview?nodeId=747

**Comment by lunascoop** [comment]
@RLHecht the page is updated and ready for review again.

**Comment by RLHecht** [comment]
Thanks @lunascoop ! I published the page and will close after validated on the live site.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
