### ISSUE TITLE
[PM] My VA Alerts: Create project outline

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30612]
## Background
As part of the work to scope the MVP we need to consult with other teams to determine what initiatives could/should be included as alerts in our MVP. 

## Tasks
- [ ] Meet with VA Notify and VEText (Maria, Bev, Paras and Shane)
- [ ] Meet with DGIB team to discuss alert-adjacent initiatives
- [ ] Meet with Health care apartment team to discuss alert-adjacent initiatives

## Acceptance Criteria
An outline/documentation exists for initiatives we learn about from our conversations with the groups listed above that includes the following information:
- [ ] basic info about each item - description, points of contact, etc.
- [ ] indicates if its a candidate for MVP
- [ ] documents technical restraints or considerations
