### ISSUE TITLE
Content updates to Veteran-Owned Small Business page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30624]
## Issue Description
Stakeholder Carol Cleveland reached out to inform us there are content changes that need to be made on the [Veteran-Owned Small Business](https://www.va.gov/careers-employment/veteran-owned-business-support/) page. We need to email to find out what these specific changes are and update the page as necessary.

Update: In the accordion "How do I register my VOSB as a SDVOSB?" we need to change the link for "Apply online" to point to this: https://www.vetbiz.va.gov/

## Tasks
- [x] Contact stakeholder to figure out content changes needed
- [x] Update page with changes
- [x] Send preview to stakeholder to review
- [x] Review and publish page

## Acceptance Criteria
- [x] Updated content is live on production

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Get support for your Veteran-Owned Small Business: http://preview-prod.vfs.va.gov/preview?nodeId=722

**Comment by RLHecht** [comment]
Thanks, @lunascoop I published this page.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
