### ISSUE TITLE
[FSR] undefined deductions are being parsed

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30627]
## Issue Description
Payroll deductions were recently changed from a required field to NOT required and is currently allowing undefined values to be parsed

![Financial Status Report  Veterans Affairs 2021-09-28 14-39-56(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/546caa94-a300-41eb-9aad-cea9976dc940)

![Financial Status Report  Veterans Affairs 2021-09-28 12-06-30.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/a3c3499c-60f4-437c-8469-e09b9c12fd72)

---
## Tasks
- [ ] verify undefined vals are filtered from form data

## Acceptance Criteria
- [ ] undefined vals should no longer be parsed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
