### ISSUE TITLE
[FE] Sort Multiple Appointments

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30630]
## User Story

As a veteran, I should see my appointments in the correct order

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Sort the incoming appointments by date time. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] add a sorter to the appointment list
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
