### ISSUE TITLE
Add Additional Dates for MANUAL_VAGOV

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30632]
## Background
In QA for 686, we learned that the created dates and last modified dates need to be included.

## Considerations
- We insert but we don't use "Smart Update" so to have these in place we need to ensure our initial addition takes place.

## Tasks
- [ ] Investigate where to add these dates
- [ ] Add the create date (`CREATD_DT`)
- [ ] Add the modified date (`LAST_MODIFID_DT`)

## Acceptance Criteria
- [ ] These dates are included when submitted

**Comment by jason-gcio** [comment]
![image](https://user-images.githubusercontent.com/53826255/135158865-5c6d1ff5-64ba-47ba-b59a-b8f46c7b431a.png)

**Comment by jason-gcio** [comment]
Existing code....
```
            vnp_proc_type_cd: 'DEPCHG',
            vnp_proc_state_type_cd: proc_state,
            creatd_dt: Time.current.iso8601,
            last_modifd_dt: Time.current.iso8601,
            submtd_dt: Time.current.iso8601
```

**Comment by kathleencrawford** [comment]
Need more clarification on this issue.  Upon investigation, we are sending `created_dt` and `last_modifd_dt` in both `vnp_proc_create` and `vnp_proc_update`.  
(I think when this ticket was written it was assumed we were only sending those dates in the create.)

**Comment by tblackwe** [comment]
Took a look at the code, I believe this issue has been resolved but never closed. Closing now.
