### ISSUE TITLE
[FE] Update Display for upcoming appointment

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30633]
## User Story

As a veteran, I should be able to see when I can check in to an upcoming appointment

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C022AC2STBM/p1632859939183400)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Update the Appointment ACtion Component to display the `checkInWindowStart` time 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update to use new property
- [x] Create unit tests
- [x] Update relevant documentations
  - [x] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [x] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
