### ISSUE TITLE
[PM, Design] My VA Alerts: Determine official name for this feature

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30637]
## Background
As noted in our discovery findings, we need to settle on an official name for this feature.

## Tasks
- [ ] Meet with Mobile team and content team to discuss using "Alert" as the name
- [ ] Decide on the name and document it in the project outline

## Acceptance Criteria
- [ ] We have an official name documented

**Comment by ajakabcin** [comment]
Moving to next sprint as conversations will continue later in the week.

**Comment by ajakabcin** [comment]
Moved to sprint 58 as conversations will continue later in the week
