### ISSUE TITLE
Add Additional Dates for MANUAL_VAGOV

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#30631]
## Background
In QA for 686, we learned that the created dates and last modified dates need to be included.

## Tasks
- [ ] Add the create date (`CREATD_DT`)
- [ ] Add the modified date (`LAST_MODIFID_DT`)

## Acceptance Criteria
- [ ] These dates are included when submitted

**Comment by jason-gcio** [comment]
dupe
