### ISSUE TITLE
[FE] Integrate with v2 API 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30635]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

 Pair with the BE team to ensure everything is working correctly. And address any issues

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Flush out integration points
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Feature is turned on in staging. 
- [ ] Signed off by both BE and FE teams 
- [ ] Deployed to staging.
