### ISSUE TITLE
Update starting date for Vietnam War era on pension and DIC pages and eligibility info on DIC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30653]
## Issue Description
Stakeholder Kelly Wante submitted several content changes to be made on the DIC and pension pages. We need to update the starting date for the Vietnam War era in several places and also update some eligibility information on the DIC page. All changes are listed in these Word docs:

[https://app.zenhub.com/files/133843125/8c328060-a2b8-4db7-aa49-536f5db67b3b/download](https://app.zenhub.com/files/133843125/8c328060-a2b8-4db7-aa49-536f5db67b3b/download)

[https://app.zenhub.com/files/133843125/7ba8ff18-39ec-46b5-a4d6-947fb1cacbd2/download](https://app.zenhub.com/files/133843125/7ba8ff18-39ec-46b5-a4d6-947fb1cacbd2/download)

[https://app.zenhub.com/files/133843125/f9a4fa2e-47ae-44f8-ba66-6644cb6ec0c3/download](https://app.zenhub.com/files/133843125/f9a4fa2e-47ae-44f8-ba66-6644cb6ec0c3/download)

[https://app.zenhub.com/files/133843125/b11fa093-720c-4d77-941b-0e57168fc90f/download](https://app.zenhub.com/files/133843125/b11fa093-720c-4d77-941b-0e57168fc90f/download)

---
## Tasks
- [x] Make date changes (Selina)
- [x] Review and publish (Randi)
- [x] Update note on DIC page (Beth)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Date changes are live on the site
- [x] DIC note change is live on the site

**Comment by RLHecht** [comment]
@lunascoop can you please make all the date changes here? Beth is going to work on the change to the note on the DIC page. Also while you are on the pages, can you also check if we need to update any bulleted lists to the way we are now doing them? Thanks!

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

- VA Survivors Pension: http://preview-prod.vfs.va.gov/preview?nodeId=590
- Eligibility for Veterans Pension: http://preview-prod.vfs.va.gov/preview?nodeId=585
- About VA DIC for spouses, dependents, and parents: http://preview-prod.vfs.va.gov/preview?nodeId=855 changed link in As a surviving parent to "check"

@bethpottsVADEPO I had started thinking about reworking the note on the DIC page before I read Randi's comment above. What about:

**You can still continue to receive compensation if one of these descriptions are true:**
- You remarried on or after December 16, 2003, and you were 57 years of age or older at the time you remarried, **or**
- You remarried on or after January 5, 2021, and you were 55 years of age or older at the time you remarried

**Comment by RLHecht** [comment]
Thanks, Selina! I published all the date change updates and will let the SME know once they're live on prod.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Yes, that's great to break out the bullets like that, but please use this edited language and slight structural change:

**Note:** You can continue to receive compensation if one of these describes you.

**One of these must describe you:**
- use the text you have
- use the text you have

Can you let me know when I can see it in preview to assess if this structure works in a note?

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've made the change. You can view it here:

About VA DIC for spouses, dependents, and parents: http://preview-prod.vfs.va.gov/preview?nodeId=855

**Comment by bethpottsVADEPO** [comment]
Ahhhh, I had a feeling it might be weird within the "Note"

Let's do this instead to replace both the "Note" _and_ bold set up that I'd first suggested:

**And you can continue to receive compensation if one of these describes you:**

**Comment by lunascoop** [comment]
@bethpottsVADEPO I've made the update

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here's my feedback on the SME's feedback!
To note: I highlighted a couple places to indicate edits that wouldn't be visible in track changes. I think it works better to separate out the descriptions for eligibility and evidence that currently live at the top of that accordion. Let me know if that makes sense. The thing I'm not sure about is whether those subheads in the accordion would be H3s or H4s. Is the accordion label considered an H3? 

Let's take a look at it in preview and decide if it needs to go back to SMEs once more or we can move forward with it.
[https://app.zenhub.com/files/133843125/71e97e5c-5794-4547-882c-3ef34f12cc2b/download](https://app.zenhub.com/files/133843125/71e97e5c-5794-4547-882c-3ef34f12cc2b/download)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks good. Can you verify that my edits didn't leave anything out? And that it makes sense overall as edits to their edits--the way I've grouped things? If all seems correct, go ahead and publish and let SMEs know we did some more editing to chunk the content in a way that we think will be easier for Veterans to understand. If they have more tweaks, we can definitely edit further.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
