### ISSUE TITLE
[FE] Clean up Actions

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30656]
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The redux actions have mixed structures, some have `.value` and use `.data` Convert them to be to the same. The actions should use `.payload`

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] convert all `.value` to `.payload`
- [ ] update unit tests

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] merged to master
