### ISSUE TITLE
Swap out videos in stories section of vaccine CLP-HOLD UNTIL WEEK OF 10/11

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30654]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John Scott McAllister

## Tasks
- [x] Replace videos and text (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the site

**Comment by RLHecht** [comment]
I reviewed and published. Moving to validate and will create new ticket for next time.
