### ISSUE TITLE
[Administrative] CAG & Venafi access for Demian Ginther

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30665]
## Description
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices. 

---
## Tasks
- [ ] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi 

## Acceptance Criteria 
- [ ] The team member will be able to do the following: 
  - [ ] Access CAG
  - [ ] Access Venafi
  - [ ] Request SSL certificates

**Comment by dginther** [comment]
While investigating, I discovered that I _do_ have an elevated access, but now will need to figure out how to use that elevated access account.

**Comment by dginther** [comment]
As I am transitioning off this team, I don't think I will need the Venafi access at this point.
