### ISSUE TITLE
[Kubernetes] Write application manifest for vets-api application

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#30668]
## Description
The vets-api application (https://github.com/department-of-veterans-affairs/vets-api) will need an application manifest to be able to run on the new EKS infrastructure.

## Background/context 
There are many configuration options for vets-api that we need to allow for. There are a number of certificates and files that are mounted into the running container, as it currently functions.

Demian has started a branch which begins to address this issue: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/dg/vets-api%2Fadd-vets-api-manifest
So far, it does the following:
- Sets up external-secrets to pull in certificates and secrets from Parameter Store
- Sets up a script to copy the certificates as a lifecycle action as the container starts
- Stubs an init container (missing an init script) to copy template configuration files
- Sets up a number of variables for the running container from the secrets

The biggest part missing here is the settings.local.yml file, which could be done one of two ways. 
- We could use the existing Jinja templates, and use an init container to template the file into an emptyDir: {}
  - This would require the init container script to check out the repo containing the template, and then a script which substituted all the variables from Parameter Store
- We could possibly use ENV vars for all of these, according to Eric Boehs: https://dsva.slack.com/archives/C0276J2FW5P/p1632268898130700?thread_ts=1632262871.128800&cid=C0276J2FW5P
  - This would just require us to use the existing secrets -> env vars patterns we already use, albeit we might need to do some templating: https://github.com/external-secrets/kubernetes-external-secrets#templating

Other things to consider:
- The way we are storing the variables in Parameter Store could be improved to make the recursive loading of all the secrets easier. This would require a lot of tedious refactoring of the variable structure but might be worth the benefit

---
## Tasks
- [x] Write an application that allows vets-API to be deployed to DEV EKS cluster, and does the following: 
  - [x] Map all necessary Rails settings
  - [x] Set up all secrets in Parameter Store and ensure they can be pulled into the deployment 
  - [x] Set up ingress route and expose the service via api-dev.vfs.va.gov
  - [x] Set up DNS entry in Route53 (CNAME to Traefik which then maps URL to service inside of cluster)
  - [x] Set up a service account within the cluster ("dsva-vagov-dev-cluster-vets-api")

## Acceptance Criteria 
- [x] Vets-API can be deployed to DEV EKS with the following: 
  - [x] all Rails settings
  - [x] all secrets stored and pulled from Parameter Store with correct path and location 
  - [x] DNS records that map to the service 
  - [x] service exposed and available via "api-dev.vfs.va.gov"
- [ ] Agreement from BE Tools team that this can be consumed for their current purposes

**Comment by jbritt1** [comment]
This likely needs to be broken down into smaller chunks as there are a lot of moving pieces. In lieu of multiple new tickets, I will try to capture some things here in the comments on this one.

We will also need:
- [ ] All certs and keys moved to parameter store
- [ ] OIDC auth'd service account on the cluster for vets-api pods
- [ ] Discovery around how to "transform" secret and cert values from param store to env vars or a way vets-api can interpret

Will add more as more discovery is made

**Comment by jbritt1** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/30861

**Comment by jhouse-solvd** [comment]
I'm glad you spotted the complexity here. We can talk about how to break it out if that's helpful. My guess is this is probably an epic and we can figure out how to break it out into multiple pieces/issues that others on the team can potentially help own and deliver in collaboration. Woot!

**Comment by jbritt1** [comment]
We likely need to move to a pattern of including the vets-api repo (with some things removed) into the container images: https://dsva.slack.com/archives/C0276J2FW5P/p1633966637291100
