### ISSUE TITLE
Take a "First Pass" at Auditing DevOps GitHub Repository Access

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30660]
## Description
The [devops](https://github.com/department-of-veterans-affairs/devops) repository has not been audited in an unknown amount of time. We need to ensure proper access is given/revoked where applicable.

## Background/context 
We have been leveraging GitHub team membership as the source of truth on access in several places. This includes access to the `devops` repository.  Individuals should no longer be granted access to the repository and users should alternatively receive their access to the `devops` repository by joining their respective GitHub team(s).

---
## Tasks
- [x] Take a quick walkthrough of the current configurations for access to the `devops` repository to gather all individual access setings
- [x] Ensure individuals are part of another GitHub team so they keep current level of access
- [x] Remove individual access 
- [x] Alert oncall/support staff of changes made in case users were missed and lost access due to said changes

## Acceptance Criteria 
- [x] Only GitHub teams show in the access list for the `devops` repository

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CTYQL39FE/p1632922400192000
