### ISSUE TITLE
Update vaccine text messaging short code to new number 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30667]
## Issue Description
Vaccine text messaging now has a new short code, which we need to update in the vaccine mini-hub (all 3 languages) and the chatbot (and anywhere else we may have it). 

The new number is **80728**

## Tasks
- [x] Audit the places we list the vaccine text messaging short code
- [x] Update all instances to new number
- [x] Review and publish pages

## Acceptance Criteria
- [x] New short code is live on production

**Comment by DanielleThierryUSDSVA** [comment]
Hi @batemapf @stephenBarrs. We also need to update the text short code within the KMI sign-up flow:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/898a922b-c190-480d-9ac5-e7499385a896) 

The new code is **80728**.

@miabecker I believe this code is also in the KMI confirmation email. Could your team please update there as well?

Thanks, all!

cc @shanemelliott @lalexanderson-dsva

**Comment by RLHecht** [comment]
@lunascoop I found it on the mini-hub in the second accordion under the "Before you get your vaccine" section. Can you please update there on the 3 versions? Thanks!

**Comment by batemapf** [comment]
Change to vets-website made! https://github.com/department-of-veterans-affairs/vets-website/pull/18917

**Comment by miabecker** [comment]
@DanielleThierryUSDSVA We updated the short code in staging and in production for the COVID KMI Confirmation. Very soon in the future we hope to give folks like you access to the UI so you can update yourself and not have to rely on us : ) Thanks for keeping us in the loop!

**Comment by RLHecht** [comment]
Work is complete now that the translated pages are live. Closing ticket.
