### ISSUE TITLE
[Administrative] CAG & Venafi access for Matt Leclerc

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30666]
## Description
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices. 

---
## Tasks
- [ ] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi 

## Acceptance Criteria 
- [x] The team member will be able to do the following: 
  - [x] Access CAG
  - [x] Access Venafi
  - [ ] Request SSL certificates

**Comment by mleclerc00** [comment]
Just to clarify, I need to contact my COR about getting my PIV card as I have no heard back about that process.

**Comment by mleclerc00** [comment]
cag access acquired, will need to move forward with venafi

**Comment by mleclerc00** [comment]
venafi access completed...closing ticket
