### ISSUE TITLE
[Administrative] CAG & Venafi access for Bill Ryan

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30663]
## Description
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices. 

---
## Tasks
- [ ] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi 

## Acceptance Criteria 
- [ ] The team member will be able to do the following: 
  - [ ] Access CAG
  - [ ] Access Venafi
  - [ ] Request SSL certificates

**Comment by omgitsbillryan** [comment]
SNOW request ticket created `REQ5706236`. Waiting to hear back.

**Comment by omgitsbillryan** [comment]
Status update:

- CAG access restored :tada:
  - had to get a new PIV card (despite old one not being expired yet)
  - had a conflicting email address w/ another "William Ryan" somewhere in VA which caused my account to be disabled multiple times
- Venafi access has been requested & is awaiting COR approval
  - [step #2 here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates#High-level-overview-to-gain-Venafi-access%3A)

**Comment by omgitsbillryan** [comment]
Venafi access granted :tada:
