### ISSUE TITLE
[Administrative] CAG & Venafi access for Srikanth Valluru 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30664]
## Description
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices. 

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG and Venafi 

## Acceptance Criteria 
- [ ] The team member will be able to do the following: 
  - [ ] Access CAG
  - [ ] Access Venafi
  - [ ] Request SSL certificates

**Comment by jhouse-solvd** [comment]
@mydesignrocks - let's sure we get this going as soon as possible as there may be some communication back and forth required. Bill opened a SNOW ticket, so you may be able to refer to him for help if needed.

**Comment by jhouse-solvd** [comment]
@mydesignrocks - Please share the current status as time allows, please.

**Comment by jbritt1** [comment]
This done?

**Comment by jhouse-solvd** [comment]
@mydesignrocks has left the team, and this access is no longer required. We can revisit the issue if needed. 

Closing.
