### ISSUE TITLE
Socialize PLATFORM TOOLS (by 10/1, 10/8)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#30682]
# User story

As a Platform customer, I need to know what tools the VA.gov Platform uses so that I can smoothly start to building my application.

# Tasks

- [ ] Determine what comms channels we should keep / ditch
- [ ] Write & send pre-launch messaging for all the channels that we decide upon
- [ ] Write & send post-launch messaging

# Acceptance criteria

# Reference info
- [This comment with seeds of info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29958#issuecomment-929353067)
- Write copy in [this page](https://vfs.atlassian.net/wiki/spaces/~248103751/pages/1908310116/Socialize+Platform+tools)

**Comment by lianilychee** [comment]
Tues 10/12:
- ToT messaging ready to go
- VFS-all-teams messaging ready to go
