### ISSUE TITLE
validate TOP TASKS

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#30686]
# User story

# Tasks

- [ ] Frame top tasks and draft message to RR
- [ ] Solicit RR's feedback via Slack
- [ ] Solicit feedback from relevant Platform experience teams

Outcome: Content to write

# Acceptance criteria

**Comment by lianilychee** [comment]
9/30 Thurs:
- Today
  - Want to have high-level tasks <- woon't know next steps till I get there.  Maybe restructure xls based on late night thoughts?  TBD!
- Want to have solicited RR's feedback by - will let us know tomorrow morning, but will pre-emptively message RR a status update by EOD today

**Comment by lianilychee** [comment]
10/1 Fri:
- Today
  - I will message Rachael during Ad Hoc VA all hands!  And will have a link for her to view on Monday
  - Continue restructuring

**Comment by lianilychee** [comment]
10/5 Tues:
- thinking I should reset expectations w/ RR and reshare tmr morning?
- thought experiment
  - if shared with RR right now: it would be horrible
  - if shared w RR tmr morning: <--
    - it'd have all the essential info; not all of the indiv bits of detail
  - if shared w RR on Thurs, when we check in with her:
    - would be able to speak to the context and explain the process
  - Decision: Today, punt to tmr.  Tmr, share w/ RR and set expectation that we will go over on Thurs.  On Thurs, go over w/ RR.

**Comment by lianilychee** [comment]
10/7 Thurs:
- to do:
  - summary/writeup, talking points, and potential next steps for context to go along with xls

**Comment by lianilychee** [comment]
10/8 Fri:
- conversation w/ RR went well, but what's the def of done?  I have rec'd next steps
  - an unspoken next-step: synthesizing results <- this would have to be done before we connect w/ other teams to address their gaps
- thought experiment
  - if we were to synthesize now
    - there's stuff we _can_ do w/o checking in with the other teams
    - buuuut we _would_ have more confidence if we have other teams' input (bc that serves as another data point)
    - would be slowed down on ambiguous docs
  - if we were to synthesize in the future (next sprint or indeterminate future):
    - context switching not a huge hurdle
