### ISSUE TITLE
Test the Analytics Training Materials

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30699]
## Issue Description
Gauge the success of our analytics training materials (GA & exploratory analytics)

---
## Tasks
- [x] Give both trainings on the 10/4 design meeting
- [x] Give GA training on 10/7 to a VFS team
- [x] Hold team meeting to synthesize survey results and general impressions from both trainings
- [x] Move survey to Optimal Workshop
- [x] Send out survey while on the call/at the end of the call

## Acceptance Criteria
- [x] Gauge the success of our analytics training materials

## Definition of Done
- [x] Both trainings are "tested"
- [x] Receive feedback from attendees
- [x] Synthesize the feedback for prioritization

**Comment by chloedotbrown** [comment]
Link to the Optimal Workshop version of the survey is available [here](https://ows.io/qs/d0313eoq) – I'll share on Slack as well.

**Comment by chloedotbrown** [comment]
Questions asked at 10/4 presentation to research and design teams:

**GA training**

- What are the most common custom questions asked?

**Exploratory analysis**

- What types of questions do designers & researchers ask the analytics team?
- How do we interpret causation vs correlation with our product decisions?
- How do we share learnings with stakeholders who aren’t as technical?

**Comment by chloedotbrown** [comment]
Closing ticket, since synthesis complete. That said, Lauren, please feel free to make any additions to the [Confluence writeup](https://vfs.atlassian.net/wiki/spaces/AT/pages/1923186758/Debrief+October+2021+Analytics+Trainings) later on.
