### ISSUE TITLE
Deprecate GH markdowns

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30697]
## Issue Description
Analytics should "deprecate" Github markdowns so that VFS teams don't use old or redundant documentation as they build on VA.gov.

There is [documentation](https://vfs.atlassian.net/wiki/spaces/AP/pages/1397194753/Deprecate+a+page+in+GitHub) on how to "deprecate" old docs in GH from the Content & IA team.

---
## Tasks
- [ ] Retrieve previous documentation audits
- [ ] Read the [IA guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1397194753/Deprecate+a+page+in+GitHub)
- [ ] Add redirect links to all Analytics GH pages
- [ ] QA all the links
- [ ] Add any docs that don't have a Platform Website replacement to the audit docs & backlog

## Acceptance Criteria
- [ ] VFS teams should be going to the Platform Website for Analytics resources, and not to Github

## Def od Done
- [ ] All Analytics VFS-facing GH docs are "deprecated"
