### ISSUE TITLE
Performance Dashboard - MVP a Performance Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3069]
## Problem Statement 
It's difficult for VFS teams to understand the baseline performance of their products because the data is missing, not easy to find, or scattered throughout different platforms. It is also difficult for DEPO to understand the overall performance of products to share with stakeholders and help VFS teams, and it's tedious to wrangle that data. 

VSP is unable to easily track & communicate to VFS teams and DEPO the overall trends and impacts of internal and external services on the performance of VA.gov applications and the veteran experience so that they can understand the overall performance of their applications in order to escalate external service issues and debug.

HMW understand what technical quality standards the DEPO platform has for VFSs and automate those standards?

## Hypothesis or Bet
If we add real time system status data then we expect product decision makers to understand if their product the basic level of "healthy" and can use data for higher level product design decisions, easily share and escalate any issues, and quickly debug.

## We will know we're done when... ("Definition of Done")
- [ ] Technical quality standards are identified/validated
- [ ] We understand what it takes to query those quality standards from their corresponding data sources
- [ ] We MVP a performance dashboard

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**:  Analytics Dashboard
* **[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics-dashboard/performance-dashboard-product-outline.md)**
* **[README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/analytics-dashboard)**
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **[Success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/analytics-dashboard/performance-dashboard-product-outline.md#OKRs)**
* **[Release plan](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17623)**

**Comment by joanneesteban** [comment]
Moving to `Future Initiatives` based on Datadog dependency.
