### ISSUE TITLE
Staging Review [Design System Team- Back to top]

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#30709]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [ ] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Update ticket with the product’s launch date after it has gone live.
- [ ] Close ticket when the review is complete and the product has launched.

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- Staging URL:  
  - https://github.com/department-of-veterans-affairs/component-library/pull/171
  - [Back to top button test url](https://60f9b557105290003b387cd5-zkexdpyvrj.chromatic.com/iframe.html?id=components-va-back-to-top--default&viewMode=story)
- Sketch file: https://sketch.com/s/65948b03-95a4-4bf7-b8fa-75caff6bfa4a

- [ ] Product outline - Design System Product Outline https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/designsystem-prod-outline.md
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: Carol Wong
- OCTO-DE Product lead: Ryan Thurlwell 
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Brooks Johnson
- Natalie Hill 

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling

11:30am Tuesday
11:30am Wednesday

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by peggygannon** [comment]
Hi, @caw310 Our Collaboration Cycle staging reviews are scheduled for Thursdays. 

Would Thursday 10/7 at 1:30 p.m. ET work for your team for this review?

**Comment by caw310** [comment]
@peggygannon , Yes I think Thursday at 1:30pm ET should be fine.

**Comment by peggygannon** [comment]
Thanks, @caw310 The staging review has been scheduled for Thursday 10/7 at 1:30 p.m. ET.

**Comment by shiragoodman** [comment]
Actually please give our full team permission @GnatalieH . @allison0034 @rtwell @noahgelman and @joshkimux will all need to review.

**Comment by shiragoodman** [comment]
it works - thanks @GnatalieH !

**Comment by GnatalieH** [comment]
Here is my draft [PR for the Back to top documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/557/files), btw.

**Comment by GnatalieH** [comment]
> @caw310 is there a staging url or link to an instance of this that we can review using a screen reader? 🙏 @AngelaFowler82 for awareness

@bkjohnson can you provide a link for accessibility testing?

**Comment by AngelaFowler82** [comment]
Ok, I see it now. I was fooled by the second URL. When I select the “back to top” button, focus either does not move or moves away and then returns to the same button, I’m not sure which. At any rate it doesn’t take me to the top of the page.

**Comment by allison0034** [comment]
No design feedback. Thank you!

**Comment by GnatalieH** [comment]
@bkjohnson can we use a different type of placeholder content instead of lorem ipsum? I really like [this example that uses English placeholder text](https://codepen.io/matthewcain/pen/ZepbeR). Can we use the same page content with a title/header that says "Back to top component" and the subheader/H2 that says "Scroll down the page"? Thanks.
