### ISSUE TITLE
VA feedback on VA.gov-wide dashboard mockup & tech needs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30700]
## Issue Description
Receive feedback from VA.gov-wide dashboard stakeholders.

Technical discovery: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28364

Mockup: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28941

---
## Tasks
- [ ] Meet with Chris (& maybe Mickin)
- [ ] Reschedule if needed
- [ ] Synthesize notes
- [ ] Prioritize feedback

## Acceptance Criteria
- [ ] We understand what VA wants/needs for a VA.gov-wide dashboard
---
## Def of Done
- [ ] Have synthesized recommendations for moving forward with VA.gov dashboard

**Comment by chloedotbrown** [comment]
Notes from 9/30 feedback session on initial mockup are synthesized [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/1910374485/All-VA+dashboard) on Confluence. Followed up with Mickin about a few suggestions on additional metrics and whether a reorg of layout around available VA Numbers would be good. 

Next steps include (note that build tasks will not start until future sprints):

- [ ] Confirm whether v2 of mockup around VA Numbers is needed
- [ ] Create reorganized mockup
- [ ] Share for feedback from Chris and Mickin
- [ ] Build draft on Domo

**Comment by chloedotbrown** [comment]
With Mickin confirming that the current high-level organization of layout is fine given data gaps, we now have all the info we need to mark this sprint's work as done. 

Next steps for this vertical will be to implement [Chris's feedback](https://vfs.atlassian.net/wiki/spaces/AT/pages/1910374485/All-VA+dashboard) in an actual Domo build of a WIP version of this dashboard. This will also highlight any data availability issues that may not have been surfaced in technical discovery and give us a chance to address them.

For now, closing current ticket as this stage of work is complete.
