### ISSUE TITLE
[Monitoring and Alerting] Set up new workflow for Grafana

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#30716]
## Description
Make sure monitoring and alerting is set up for Grafana using the new workflow (ie Datadog & PagerDuty).

## Background/context 
Alerting guidance documentation [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting)

## Technical notes
Start with: Does this service send its metrics to Datadog? 

---
## Tasks
- [x] Synthetics 
- [x] Determine service-specific metrics 
- [x] Ensure metrics are available in Datadog
- [x] Set up monitors in Datadog
- [x] Test the monitor in Slack 
- [x] Build out alerting thresholds / parameters 
- [x] Integrate w/ on-call channel + PagerDuty 

## Acceptance Criteria 
- [x] There is monitoring and alerting set up for Grafana using Datadog, Slack, and PagerDuty
  - [x] The service is sending metrics to Datadog 
  - [x] Non-critical alerts are going to Slack 
  - [x] Mission-critical alerts are going to PagerDuty

**Comment by jhouse-solvd** [comment]
Passing to @mydesignrocks to begin work on this 12/2

**Comment by mydesignrocks** [comment]
synthetic monitoring is available: https://app.datadoghq.com/synthetics/details/945-wtb-ucb?live=1h
infrastructure monitoring is available: https://app.datadoghq.com/containers?query=grafana&tab=logs
alerting like these are enabled for all pods and is integrated to slack channels: https://app.datadoghq.com/monitors/45201618
verified that following slack channels are receiving them now: #platform-datadog-alerts-test and #platform-pagerduty-alerts-test
Pending: integration to oncall / PD

**Comment by mydesignrocks** [comment]
Also noticed that PD is receiving this synthetic monitoring for grafana: https://dsva.pagerduty.com/alerts/Q2RD97F7TI9DOB and https://dsva.pagerduty.com/alerts/Q2RD97F7TI9DOB/log_entries/R0Y4YT5KK4LHP19A2LQGPU5PIH

**Comment by mydesignrocks** [comment]
all items complete and ready to be reviewed.

**Comment by jhouse-solvd** [comment]
@mydesignrocks - Please check off acceptance criteria as well if you feel like that is met. Thank you!

**Comment by jhouse-solvd** [comment]
@oseasmoran73 - It would be awesome if you could try to understand what was done here and determine if the acceptance criteria have been met. 

This might entail a) asking a lot of questions, b) shoring up documentation to answer those questions, and c) validating whether or not we feel confident that we have good observability/monitoring / alerting in place for Grafana as a service. 

Once you feel the acceptance criteria have been met, you can close out the issue with a comment like "AC met; closing"

**Comment by oseasmoran73** [comment]
I still am reviewing for the time being and trying to understand scope of the story, but there seems to be a discrepancy between notification channels. As part of AC, I would expect notification from [pageduty_test_env](https://dsva.slack.com/archives/C02CDL4TG2H/p1641913748000100) to display in [oncall](https://dsva.slack.com/archives/C30LCU8S3) channel. Time stamp ~0709 PT displayed in test_env, but missing in oncall channel.

It may be simple to change notification channel for above statement, but for myself, trying to understand the following

 > We have solid monitoring and alerting in place for Grafana, and feel confident about our ability to know if anything is happening that affects the running service for our users

**Comment by oseasmoran73** [comment]
Reached out to Sri and hoping to have some time, if not next week to discuss this with him bit more in details

**Comment by jhouse-solvd** [comment]
@mleclerc00 mentioned that there may be Loki endpoint synthetic that is hitting dev and staging, but no other environments. This would be good to look into as well Oseas.

**Comment by jhouse-solvd** [comment]
If additional configuration is needed for monitoring and alerting of Grafana as a service, please create a new issue. 

Closing.
