### ISSUE TITLE
GA4 technical discovery recommendation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30711]
## Issue Description
Develop a technical discovery recommendation for moving forward with a GA4 update. 

Recommendation should include needs for build & impacts on BigQuery & Domo reports.

---
## Tasks
- [x] Determine how the data will be pulled into BigQuery
- [ ] Solicit feedback from Empircal Path, what is best practice for biggest taxonomy
- [ ] Design system feedback on event architecture 
- [ ] Write technical discovery findings (add to Confluence)

## Acceptance Criteria
- [ ] Analytics understands how the GA4 update will be "built" and how it will impact the rest of our reporting structures
---
## Def of Done
- [ ] Written report on technical discovery

**Comment by michelle-dooley** [comment]
This piece of work is complete, we will continue additional discovery and documentation as needed as part of planning.
