### ISSUE TITLE
Review vaccine research page for any outdated information

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30712]
## Issue Description
We haven't made updates to the [volunteer for coronavirus research at VA](https://www.va.gov/coronavirus-research) page in some time. We need to review the page to determine if there is any outdated information or other updates needed.

## Tasks
- [ ] Review page for outdated information (Randi/Selina)
- [ ] Make updates (Danielle/Selina)
- [ ] Review and publish (Randi)

## Acceptance Criteria
- [ ] Live page is current with all outdated information removed

**Comment by RLHecht** [comment]
@lunascoop can you add a link to the main vaccine mini hub page in the helpful links section of this? No other changes are needed.

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Volunteer for coronavirus research at VA: http://preview-prod.vfs.va.gov/preview?nodeId=6785

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published this.
