### ISSUE TITLE
Define event taxonomy

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30713]
## Issue Description
As we start technical discovery, we'll need to define current GA event taxonomy.

---
## Tasks
- [x] Synthesize all current event taxonomy
- [x] Create list of best practices & standards for creating these events
- [x] Create a list of best practices for naming GA4 events
- [x] Collab with the Design System team on their feedback
- [x] Update operational/internal documentation with newly defined event taxonomy
- [x] Get feedback from the rest of the EP team 

## Acceptance Criteria
- [x] Analytics understands what events exists on VA.gov GA

## Definition of Done
- [x] Internal/operational docs are updated with event taxonomy

**Comment by laurensimpson14** [comment]
Linking this Google Sheet that we began a few months ago with GA4 event naming ideas: https://docs.google.com/spreadsheets/d/1Jou9sw-wAp6OCfw_UFH4fl3DaPdBcnpZWiMshA0jqOs/edit?usp=sharing

We can work off of that ⬆️ and build it up.

**Comment by laurensimpson14** [comment]
[Google Sheet](https://docs.google.com/spreadsheets/d/1oi85RaKDAxN141kZoKTOPuQWW_7w1dTc0523ZMPGW2I/edit?usp=sharing) with all current event taxonomy that needs to be mapped to GA4 🗺️
