### ISSUE TITLE
[FE] Add Last updated message and Refresh button 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30729]
## User Story

> these should be why the veteran cares, and the veteran gets out of it.

As a veteran, I should see when my list or appointments was last updated so that I know how stale the data is. 
As a veteran, I should be able to refresh the appointment data without leaving the page. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

They can see the last loaded time and should be able to refresh the data. When clicked, the page will hide the main content and show a spinner while it recalls the API to display the latest data and update the latest time loaded

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Show the latest time loaded
- [ ] Add a refresh link 
- [ ] Record an analytics event when the link is clicked
- [ ] Add a spinner that shows while the page is being loaded. 
- [ ] Be sure the list auto-scrolls to the top of the list 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
