### ISSUE TITLE
Audit & compare GA4 non-production

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#30736]
## Issue Description
To get started on technical discovery for the GA4 update, the Analytics team will need to understand how the test data on the GA4 nonprod update is faring. 

---
## Tasks
- [ ] Audit events changes in GA4 nonprod

## Acceptance Criteria
- [ ] Analytics has an understanding of the changes GA4 made in nonprod

## Def of Done
- [ ] Spreadsheet of GA4 nonprod update audit

**Comment by jennaouellet** [comment]
Working sheet is here: https://docs.google.com/spreadsheets/d/10LQePWExi1SEOmcq4kG1qjNGBPqbKeuzj29dxluQbYk/edit#gid=215461614

This is a repurposed EP GA4 Playbook. In the events tab I've started by listing the GA4 events we are tracking, which is just the out-of-the-box ones right now.

**Comment by laurensimpson14** [comment]
Thanks @jennaouellet! I think we should also fill out the data-in and data-out tabs. I took a stab at that, but I'm not 100% sure on if some of them are applicable or not.
