### ISSUE TITLE
[BE] Investigate on StatsD Metrics in vets-api

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#30742]
## User Story

- Developers can easily monitor check-in experience feature performance in a dashboard

## Description

- vets-api service should have metrics logged in StatsD for monitoring the feature performance in server

## Tasks

> this is a list of technical tasks that need for this ticket
- [ ] Investigate & study StatsD API for metrics logging
- [ ] Identify initial list of metrics to log from vets-api
- [ ] Implement identified metrics in vets-api 
- [ ] Write rspec tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] FE engineering team has signed off on the  feature
