### ISSUE TITLE
[FSR] Bug - Debt resolution page's comp + pen waiver selection shows checkbox for education debts

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#30748]
## Issue Description
When users select 'waiver' on a compensation + pension debt on the debt resolution selection screen, it shows a checkbox related to education benefits being reduced. That checkbox should only appear for education-related debts. 

Note: Staging's login was down when this ticket was created. A screenshot of the tool can be added during backlog grooming.

---
## Tasks
- [ ] Remove the reduced education benefits checkbox for compensation + pension debts' waiver selection 

## Acceptance Criteria
- [ ] When the 'waiver' is selected for compensation + pension debts, the reduced education benefits checkbox no longer appears 
- [ ] The checkbox for reduced education benefits still appears for education debts

**Comment by denisecoveyduc** [comment]
This issue will roll over into Sprint 61 as a result of the caregiver team assistance.
