### ISSUE TITLE
[MDOT] Update AlertBox to use va-alert

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30744]
## Issue Description
The `<AlertBox/>` component has been deprecated so all usage should be replaced using `<va-alert/>`

![Screen Shot 2021-09-30 at 9.33.27 AM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/c9864309-c42d-4d5c-b8f0-7b649df35313)

---
## Tasks
- [ ] Replace all usage of Alertbox with va-alert

## Acceptance Criteria
- [ ] AlertBox component should be removed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
