### ISSUE TITLE
 [MDOT] Remove confirmation email

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30740]
## Issue Description
we are currently asking for a confirmation email and should be removed

![localhost_3001_health-care_order-hearing-aid-batteries-and-accessories_order-form-2346_introduction.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/c08f7d25-7612-4ed9-bb10-ad948d2f43fa)
---
## Tasks
- [ ] remove confirmation email field

## Acceptance Criteria
- [ ] confirmation email field should no longer render
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
