### ISSUE TITLE
Update 2021 automobile allowance rate-HOLD UNTIL 10/1

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30743]
## Issue Description
The yearly automobile allowance rate, which we list on the [2021 VA special benefit allowances rates](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/) page, changes as of October 1. We need to update the page with the new number.

The new number is: $22,355.72.

## Tasks
- [x] Update number for 2021 (Selina)
- [x] Check for sighted language and update (Selina)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that change is made (Randi)

## Acceptance Criteria
- [x] New rate is live on the site

**Comment by lunascoop** [comment]
@RLHecht  These pages are ready for review

2021 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=990
Past rates: 2020 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=11441
Past rates: 2019 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=5035
Past rates: 2018 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=6190

**Comment by RLHecht** [comment]
I reviewed and published this page. Will close once validated on live site.

**Comment by RLHecht** [comment]
This page is now live. Closing ticket. FYSA @bethpottsVADEPO
