### ISSUE TITLE
[FE] Update to new LoROTA struture

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#30741]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1633005657009000)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Update to the new structure to better ready for future work. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update calls to look for an `appointments` key 
- [ ] Create unit tests

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
