### ISSUE TITLE
VAMC Accordion title cuts off at quotation marks

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30776]
## Issue Description
As initially reported by Randi, text visible in Drupal was missing from an accordion when viewed in Preview

- [related CMS URL](preview-prod.vfs.va.gov/preview?nodeId=6785)
- [related VA.gov URL](https://www.va.gov/coronavirus-research)
- [related Prod link](https://prod.cms.va.gov/coronavirus-research)

<details>
<summary> Screenshots </summary>
![image](https://user-images.githubusercontent.com/55411834/135527064-d1cf53b1-349b-470b-9d6b-3c90e08fd0ac.png)

![image](https://user-images.githubusercontent.com/55411834/135527088-19ab1bc9-c7ea-4ed9-b252-3df5d8e9abc0.png)

</details>

This issue was resolved by removing the quotation marks. There is no guard against double quotes in accordion header fields,  so it was determine that this would be considered a FE defect with a workaround.  
This regression may have happened back when accordions switched to using web components.

## Steps to reproduce 
- [ ] Enter an accordion title containing words in quotation marks
- [ ] View the accordion in edit mode
- [ ] View the accordion in preview 
- [ ] Observe the text stops where the quotations begin

[Slack discussion thread](https://dsva.slack.com/archives/C01H29ERVJ7/p1632940252010400)

---
## Tasks
- [x] Discuss library options with VSP/PW team
- [x] Add escape filter to accordion heading 

## Acceptance Criteria
- [x] Accordion headers can contain quotations marks without impacting rendering of full content

**Comment by mpelzsherman** [comment]
Per [discussion](https://dsva.slack.com/archives/C5HP4GN3F/p1634051794180000) with the platform FE team, we should write our own sanitizer function.

**Comment by mpelzsherman** [comment]
Code is live in production

**Comment by mpelzsherman** [comment]
This change caused a side-effect of showing apostrophe as `&quot` in accordion headers. This [PR](https://github.com/department-of-veterans-affairs/content-build/pull/722) fixes it.
