### ISSUE TITLE
Update Facility Locator "Get Directions" accessibility

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30778]
## Issue Description
As a screen reader user, I need to hear a way to get directions to a place that I need to visit physically. When I leave the page, I need to know where I am going because I do not have the visual cues.

During screen reader usability sessions, "Get directions" was not audible or decipherable for (3) JAWS screen reader users. "Get directions" does not provide key information on where directions will be procured from and that it opens a new tab. The latter can be particularly frustrating if unanticipated by assistive tech users.

The following changes were proposed during a collaboration between Nick and Josh. 

### Out of scope: (will be handled in a subsequent issue)
For further accessibility consideration: after opening the link to Google Maps, the back button should return users to the same search results state, if that is not already current behavior.

---
## Tasks
Make changes to Facility Locator search results as indicated in [Nick's UX pin](https://preview.uxpin.com/86d62dbd30d510360fcc3d021544cc24e3422880#/pages/142520031/documentation/no-panels?mode=i)
- [x] Change "Get directions" label to "Directions on Google Maps"
- [x] Change screen reader announcement to "Directions on Google Maps to" + name of location
- [ ] Ensure spacing allows for clear screen reader announcement 
      - JAWS issue has screen reader reading "Get directionsto..."; may need a space after "directions" or before "to"; (maybe double check spacing between "get" and "directions" too)
- [ ] use "aria-describedby" and/or "aria-label" where appropriate 
- [ ] Keep current functionality to open a new tab (for now)

## Acceptance Criteria
- [ ] Link is labeled "Directions on Google maps"
- [ ] Screen reader announcement reads "Directions on Google Maps to" + name of location
---

**Comment by mpelzsherman** [comment]
[Confirmed](https://dsva.slack.com/archives/C0FQSS30V/p1636055699249800?thread_ts=1636055410.249000&cid=C0FQSS30V) by @joshkimux .
