### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on October 6

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30771]
## Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file prior to their upcoming go-live

- [ ] /montana-health-care
- [ ] /cheyenne-health-care/
- [ ] /new-york-harbor-health-care/
- [ ] /augusta-health-care/
- [ ] /columbia-south-carolina-health-care/
- [ ] /charleston-health-care/
- [ ] /west-texas-health-care/
- [ ] /black-hills-health-care/
- [ ] /richmond-health-care/
- [ ] /hampton-health-care/

## Acceptance Criteria
System names are removed from robot.txt file

**Comment by mmiddaugh** [comment]
Merged
