### ISSUE TITLE
[Network / Firewall] Connectivity request (sandbox fwd-proxy to preprod IAM)

### ISSUE THREAD

**Issue by beaugrantham-va** [department-of-veterans-affairs/va.gov-team#30791]
## Description
Need network connectivity established from sandbox fwd-proxy to preprod IAM.

## Background/context 
This is in support of Lighthouse SSOi OAuth. The connectivity is necessary to make /userinfo and /introspect requests with IAM when validating access tokens.

## Technical notes
Source: sandbox fwd-proxy
Destination: preprod.fed.eauth.va.gov:444

This connectivity exists in other environments (e.g., staging fwd-proxy) but does not work in sandbox.

Note that this ticket is not to add a new entry to the fwd-proxy, this is for raw connectivity.

---
## Tasks
- [ ] Establish connectivity.
- [ ] Document as we go 

## Acceptance Criteria 
- [ ] A curl from the sandbox fwd-proxy to https://preprod.fed.eauth.va.gov:444 returns data.
- [ ] High-level process w/ screenshots is documented in Confluence

**Comment by jhouse-solvd** [comment]
@golavarr-va @dbrown-va - The ops team is going to take a look at this and get it worked into the coming sprint. We first need to ensure that this is possible, but we'll reach out if there are any issues or discussions that need to happen. Thanks for the patience. Cheers!

**Comment by beaugrantham-va** [comment]
@omgitsbillryan do you have an update on this?

**Comment by omgitsbillryan** [comment]
ESECC request has been submitted. Waiting ~5 days for approval via email.

**Comment by jhouse-solvd** [comment]
According to @boris-ning-usds - INC13773799 has now been completed. The Ops team will test connectivity and then follow up with @beaugrantham-va and team to see that things are working as expected.

**Comment by omgitsbillryan** [comment]
Looks like connectivity now exists ---
```
# from staging fwdproxy instance

$ curl -I https://preprod.fed.eauth.va.gov:444
HTTP/1.1 200 OK
```

Mind confirming @beaugrantham-va ? If it looks good, it seems like this ticket can be closed:

> Note that this ticket is not to add a new entry to the fwd-proxy, this is for raw connectivity.

**Comment by beaugrantham-va** [comment]
Confirmed. Thanks for the assist!
