### ISSUE TITLE
[Parameter Store / Vets-API] Lighthouse Health FHIR API RSA key installation and configuration

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#30803]
## Description
Installation of an RSA key that will be used when accessing the **sandbox environment** of Lighthouse's Health FHIR API from vets-api.
## Background/context 
The VA Mobile App, via the mobile API, has been approved by Lighthouse to access their Veterans Health API (FHIR) to retrieve immunizations records.

The next step is to generate an RSA key pair that will be used to authenticate with their sandbox authorization server. The private key should be installed and configured in a similar manner as the key for the HealthQuest app (vets-api-server-vagov-sandbox.yml etc).

The public key should be encoded as a JWK and sent to Beau Grantham <beau.grantham@va.gov> and the LH team and they'll provision us a new client for the API.

[This slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1632439082099600) has additional details and the mobile team was advised that they should generate the key pair and deliver it to Ops. The mobile team will also handle the JWK encoding and deliver that to Lighthouse.

[Here's an example PR where this was done before](https://github.com/department-of-veterans-affairs/devops/pull/9096/files)

---
## Tasks
- [ ] Create an IAM group for the VA Mobile team (@kreek, @jperk51)
- [ ] Create a IAM policy to allow this newly created group permission to write to a path in parameter store 
- [ ] Render any assistance needed to ensure that this team can put their key in that path 
- [ ] Operations to modify vets-api deployment to include the key and variables that are in new settings.yaml (similar to what was done in [this pr](PR))

## Acceptance Criteria 
- [ ] The key is installed and API requests to the Lighthouse Health FHIR API are successful (returning 200s)

**Comment by kreek** [comment]
PWK has been sent over to Beau Grantham.

**Comment by mydesignrocks** [comment]
Hello @travis-newby and @patrickvinograd - are you looking to get this updated referring to the right paramstore key (as soon as the paramstore gets updated with the right key)
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-sandbox.yml#L198

**Comment by kreek** [comment]
👋 @mydesignrocks any update on my access? Just checked and I'm still getting the same error.

**Comment by lexicalninja** [comment]
@mydesignrocks @jhouse-solvd  @travis-newby Can someone please take a look at what is going on with Alastair's permissions? Everyone else seems to have been able to add creds and this is slowing down our ability to deliver. 

Please let me know if you need anything else from us or if you need Alastair online to troubleshoot. 

Thanks!

**Comment by mydesignrocks** [comment]
my apologies, @kreek - somehow missed through the cracks

**Comment by mydesignrocks** [comment]
@kreek now has the right access. Please confirm if this can be closed. thanks

**Comment by jhouse-solvd** [comment]
@kreek or @mydesignrocks -Please check off tasks and AC on this ticket as time allows, please. Then I'll review and close this one out. :) Thank you!

**Comment by oseasmoran73** [comment]
Closing ticket as it seems requirements were met and ticket is inactive. Please feel free to reopen if needed!

CC @jhouse-solvd
