### ISSUE TITLE
Staging Review [Authenticated Experience, Notification Preferences]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30802]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Update ticket with the product’s launch date after it has gone live.
- [ ] Close ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Staging: [staging.va.gov/profile/notifications](staging.va.gov/profile/notifications)
- [ ] Test user info
    - [ ] [Staging test-user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md)
    - [ ] [QA version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/notification-preferences-QA-use-cases.md#product-use-cases-notification-preferences)
    - [ ] [Accessible version of test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences-a11y.md) 
- [ ] Product outline - [Notification Preferences (communication permissions) product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md) 
 - [ ] [Notification Preferences Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/release-plan.md)

### Content artifacts 
- [ ] Content source of truth: [Notification Preferences FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend) 
- [ ] Prototypes: [Desktop](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/141756016/simulate/sitemap?mode=i), [Mobile](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/141694444/simulate/sitemap?mode=i), [Interactivity](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140721595/simulate/sitemap?mode=i)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=2157)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/2283) in TestRail with test execution logs 
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/273) 
- \[No Summary (Defects) report -- No defects logged.\*\]

### Accessibility artifacts 
- [ ] [Notification Preferences - Accessibility Staging Review Prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/staging-review/accessibility-test-prep.md#notification-preferences---accessibility-staging-reivew-prep)

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: @ajakabcin 
- OCTO-DE Product lead: @Samara-Strauss 
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members
- @erikphansen 
- @lihanli 
- @andaleliz 

### VFS Attendees
- Content and IA: @DanielleThierryUSDSVA and @mnorthuis 
- Accessibility: @joshkimux and/or @AngelaFowler82 
- QA specialists: @tlei123 

## Scheduling
**Thursday, October 14** at **2:00 pm ET**

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

-----

\* There were Safari & IE11 sign-in issues, but not related to this Feature. \[See test-plan ticket Comments starting with [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29849#issuecomment-932655916).\]

**Comment by peggygannon** [comment]
@ajakabcin Hello, staging review has been scheduled for Thursday 10/14 at 2 p.m. ET.

**Comment by ajakabcin** [comment]
Thank you @peggygannon !

**Comment by tlei123** [comment]
FYI, @pjhill @ddzz , Cypress-TestRail integration's also done.  [Test-results](https://dsvavsp.testrail.io/index.php?/runs/overview/4) pushed to TestRail \[under **Completed** section > **Monday, October 4, 2021**\].

cc @erikphansen

**Comment by ajakabcin** [comment]
Closing this out - the remaining open issue is with Public Websites
