### ISSUE TITLE
[Kubernetes] Add cms-infrastructure project to argo

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#30804]
## Description
The CMS team is looking to start testing their deployments to EKS so this is the first step towards that.  

## Background/context 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/30196

---
## Tasks
- [x] create project/role for cms team that maps back to the cms-infrastructure github team
- [x] redeploy argocd
- [x] add vsp-cms folder to manifests repo

## Acceptance Criteria 
- [ ] cms team can access argocd and can see the apps deployed to cms-infrastructure folder

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
