### ISSUE TITLE
Review Debt Resolution team tools for instances of sighted language

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#30828]
## Issue Description

The sitewide content team is moving away from using sighted language, such as the word 'view', on VA.gov. 

---
## Tasks
Review the following products' staging environments for sighted language: 
- [x] Medical Device Re-ordering tool
- [x] Debt Management Portal
- [x] Financial Status Report 
- [x] Medical Copay Tool
- [x] Document changes for each tool 

## Acceptance Criteria
- [x] Areas including sighted language in each tool have been documented and attached to this ticket
   - [x] Tickets are created for frontend changes as needed 
   - [x] Tickets are created for the sitewide content team as needed

**Comment by rileyorr** [comment]
I audited all the tools and have screenshots + proposed content updates [here](https://governmentcio.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Document.docx?d=wff57feff0de94b0b8b9283d62f59db9b&csf=1&web=1&e=CFgJm1). I'll review them tomorrow morning and make the correlating tickets.
