### ISSUE TITLE
Crosswalk VBA service taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30836]
## Issue Description
To prepare for taxonomy work on Benefit services, we need to match patient friendly language which has already been discovered for Resources and support with the the service descriptions used by VBA. Language used in the Facility Locator service dropdown for benefit facilities may also be helpful. 

The following services were listed as available at Benefit facilities during recent data call
- Applying_for_Benefits 
- Burial_Claim_assistance 
- Disability_Claim_assistance 
- eBenefits_Registration 
- Education_and_Career_Counseling 
- Education_Claim_Assistance 
- Family_Member_Claim_Assistance 
- Homeless_Assistance 
- VA_Home_Loan_Assistance 
- Insurance_Claim_Assistance 
- IDES 
- Pre_Discharge_Claim_Assistance 
- Transition_Assistance 
- Updating_Direct_Deposit_Informa 
- Vocational_Rehabilitation_Emplo 
- Other_Services

[Resources and support](https://www.va.gov/resources/)

<details>
<summary> Screenshot for current Facility Locator dropdown of VBA service types <summary>
![image](https://user-images.githubusercontent.com/55411834/135685680-b8da9602-2149-48f8-affe-1c03b9ac3ba6.png)

</details>

## Tasks
- [ ]  For each of the services listed above, discover Veteran facing language in the Resources and Support hub which aligns. It may not be a 1:1 relationship
- [ ] Discover any additional services which appear to be offered at Benefit locations which could be mapped to "other services"

## Acceptance Criteria
- [ ] Documentation which maps known service data to more Veteran friendly language and plain language descriptions

**Comment by mmiddaugh** [comment]
Facility Locator analytics related to benefits services, 7/1/21 - 9/30/21
<html>
<body>


| facility type  |service type selected | total unique services (%) | 
| --- | --- |--- |
| benefits | (not set) | 135,047 (86.92%) | 
| benefits | ApplyingForBenefits | 5,749 (3.70%) | 
| benefits | DisabilityClaimAssistance | 4,158 (2.68%) | 
| benefits | VAHomeLoanAssistance | 1,649 (1.06%) | 
| benefits | EducationAndCareerCounseling | 1,440 (0.93%) | 
| benefits | EducationClaimAssistance | 1,150 (0.74%) | 
| benefits | FamilyMemberClaimAssistance | 1,039 (0.67%) | 
| benefits | VocationalRehabilitationAndEmploymentAssistance | 1,009 (0.65%) | 
| benefits | BurialClaimAssistance | 943 (0.61%) | 
| benefits | Pensions | 826 (0.53%) | 
| benefits | eBenefitsRegistrationAssistance | 659 (0.42%) |
| benefits | UpdatingDirectDepositInformation | 626 (0.40%) | 
| benefits | HomelessAssistance | 369 (0.24%) | 
| benefits | TransitionAssistance | 202 (0.13%) | 
| benefits | InsuranceClaimAssistanceAndFinancialCounseling | 182 (0.12%) | 
| benefits | PreDischargeClaimAssistance | 178 (0.11%) |
| benefits | IntegratedDisabilityEvaluationSystemAssistance | 144 (0.09%


</body>
</html>
