### ISSUE TITLE
Audit VAMC non-clinical service taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30839]
## Issue Description
We need to identify the areas where non-clinical taxonomy is misaligned on VAMC pages so that we can begin to develop a plan to conduct Veteran research

---
## Tasks
- [x] Review VAMC pages to discover and document non-clinical services, such as 
      - [ ] Top tasks which are also services (medical records, register for care, appointments, etc)
      - [ ] Items in "Prepare for your visit" (such as Chaplain services)
      - [ ] Services listed as health services which might be expected under social services or other services
      - [ ] Services listed as social services or other services which might be expected under health services (Women Veteran care)
      - [ ] Services which might be best classified as Administrative
- [x] Review feedback from Steve Tokar for other areas or reported misalignment

## Acceptance Criteria
- [x] Documentation of non-clinical services offered by VAMCs

## Deliverables
- [x] [Research findings documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/services-taxonomy/taxonomy-research-2021/research-findings.md)
- [x] [Service audit spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/services-taxonomy/taxonomy-research-2021/audit-spreadsheet-vha-health-services-Oct2021.xlsx)

**Comment by lildziner** [comment]
@mmiddaugh where can I find the feedback in regards to this in the AC: "Review feedback from Steve Tokar for other areas or reported misalignment"?
