### ISSUE TITLE
[DL] Add Sentry to Improve Error Reporting

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30849]
## Issue Description
We are currently not throwing errors and only capturing exceptions using google analytics which makes it difficult to troubleshoot any issues in the event of a failed API call so there is a need to add Sentry to Debt Letters improve error reporting.

Example implementation:
```
import Sentry from @sentry/browser

Sentry.withScope(scope => {
Sentry.captureMessage('Validation issue not displayed');
scope.setExtra('prefix', trackingPrefix);
scope.setExtra('inProgressFormId', inProgressFormId);
scope.setExtra('errors', errors);
}); 
```

---
## Tasks
- [ ] failed API calls should throw error payload with details

## Acceptance Criteria
- [ ] failed API calls should throw error payload with details
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
Sentry has been added to MCP and can be used as a guide when implementing for Debt Letters ... https://github.com/department-of-veterans-affairs/vets-website/blob/5d71e433b3cb5a1a9aad6db2f2f634963d4ba183/src/applications/medical-copays/actions/index.js#L21
