### ISSUE TITLE
Google Tag Manager Service - Standardize Google Tag Manager to Design System Components

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3085]
## Problem Statement 
VSP Analytics & Insights needs a more automated way to implement and QA Google Tag Manager so that we can more accurately deliver analytics and also focus efforts on scaling without becoming a blocker to VFS teams who need Google Analytics.

HMW understand where we can more efficiently implement GTM so that we can better scale GTM services?

## Hypothesis/(es)
If we standardize the Google Tag Manager tracking to the VA.gov Design System "components," then we expect to be lower our GTM efforts by implementing fewer custom GTM for VFSs and for VFS teams to have a simpler time requesting GTM and faster results. 

## Definition of Done
We will know we're done when...
- [x] We have standardized processes for at least 50% of the design system components
- [x] Our standardized processes are reflected in an updated GTM request template

### ... tested?

~- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.~
    ~- [ ] ... and issues discovered in usability testing have been addressed.~
    ~* _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._~
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
~- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD~

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
      - [GTM Design System component documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#component-library)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
    - [Google Tag Manager Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/google-tag-manager/google-tag-manager-product-outline.md)
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [x] ... and should be located at `platform/PRODUCT_NAME/README.md`
    - [Google Analytics/Google Tag Manager readme](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics#readme)
~- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative~
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia]
(https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: Google Tag Manager
* **[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/google-tag-manager/google-tag-manager-product-outline.md)**
* **README**: [GA/GTM Readme](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics#readme)
* **User Guide**: [Building & Measuring Events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#component-library)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **[Success metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/google-tag-manager/google-tag-manager-product-outline.md#measuring-success)**
* **Release plan**: [Link](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17621)

**Comment by rroueche** [comment]
@joanneesteban I feel this is more for O3: resiliency of our systems and teams, than O1: delightful customer experience. what are your thoughts?

**Comment by joanneesteban** [comment]
@rroueche I think that makes sense if the focus is on the Google Tag Manager side, which will continue under the GTM super epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/265. I would say that this is more focused on automating that process/reducing time to implement GTM for the clients, which I think falls more under O1 - but happy to change the Objective if we think analytics resiliency is more aligned to this work.

**Comment by KevinMHoffmanUSDS** [comment]
@joanneesteban I'm excited this work has been prioritized for this quarter. One thing I think may be worth considering adding to the definition of done is making sure that analytics instrumentation is accounted for in the creation of new and improved elements of the design  system. I also hypothesize that in this work, we may end up creating standardized approaches for patterns/user flows as much as individual components.

**Comment by joanneesteban** [comment]
Was under the wrong VSP KR. Changing release

**Comment by jonwehausen** [comment]
## Description of Solution Pivot

### Timeline
- This pivot was identified, discussed and introduced on February 12, 2021

Before receiving further guidance from the Design System team, we started out by duplicating the technique used in the Pagination component -- directly writing our Data Layer taxonomy directly into each component.  While this works, it is pretty rigid from a design standpoint. For example, if we want to modify or add to the data layer metadata, we would need to make an update. Also, any other sites or apps within the USDS ecosystem that ever want to use components would be stuck with our Data Layer.

Our solution now is to decouple this -- Instead of writing directly to the Data Layer, each component will trigger a client-side browser Custom Event that includes the metadata we care about (such as `componentName`, `action` (i.e click) and other additional metadata that we want to include that is important drawing insights. The application or website using these components (in our case on VA.gov `vets-website` simply listens for these events, processes them, and writes our taxonomy to the Data Layer to be picked up by GTM and ultimately sent to GA/BigQuery. 

We believe this pivot will accomplish the best of both worlds for our Insights & Analytics goal of standardizing our GTM tracking and the Design System's team of maintaining flexible usability of the component library as they continue to scale their repository of components. 

Slack Thread: https://dsva.slack.com/archives/C01DBGX4P45/p1612980416047700

cc: @joanneesteban
