### ISSUE TITLE
[MCP] Make accessibility design changes for summary page

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#30859]
## Issue Description
During a call with Angela, she noted that there are a few places where the summary screen is a little confusing for screen readers:
- Cards should have one link and the H3 should read "[Amount] for [Reason]"
- Questions about your balance should be reconfigured to show the options as headings with appropriate nesting

---
## Tasks
- [x] Make design changes for both issues above and sync to UXPin
- [x] Create a FE ticket for work (if necessary)

## Acceptance Criteria
- [x] UXPin updated and linked to this ticket
- [x] FE ticket created and linked to this ticket (if necessary)
