### ISSUE TITLE
Update VGLI application PDF on VGLI page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30864]
## Issue Description
Stakeholder Steven Fital asked us to update the VGLI application PDF on our [Veterans' Group Life Insurance page](https://www.va.gov/life-insurance/options-eligibility/vgli/). 

Here is the new PDF: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8714_ed2021-04.pdf

## Tasks
- [x] Update link with new PDF (Selina)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that change is live (Randi)

## Acceptance Criteria
- [x] New PDF is live on the site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Veterans’ Group Life Insurance (VGLI): http://preview-prod.vfs.va.gov/preview?nodeId=769
Updated PDF link and sighted language link beneath accordion tables.

**Comment by RLHecht** [comment]
Thanks @lunascoop. This is reviewed and published. Moving to validate. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
work complete. Closing ticket.
