### ISSUE TITLE
Review and improve user flow of view or change dependents page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30863]
## Issue Description
We need to look at the flow and improve the content of the [View or change dependents on your VA disability benefits](https://www.va.gov/view-change-dependents/) to indicate that you can request approval of school attendance online by clicking the second CTA button—it's not only for adding a dependent.  

Slack thread for background: https://dsva.slack.com/archives/CUB5X5MGF/p1632849162024900

## Tasks
- [ ] Review content on page and provide content updates (Beth)
- [ ] Update page with changes (Selina)
- [ ] Review and publish page (Randi)

## Acceptance Criteria
- [ ] View or change dependents page is live on the site with a better user flow

**Comment by RLHecht** [comment]
Update: This can stay in the backlog for when there is capacity to work on this.
