### ISSUE TITLE
KPI Tracking - Expand Suite of KPI Trainings to Improve KPI Maturity

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3086]
## High Level User Story
As a VFS product manager/owner, I need to better understand data analysis so I can more accurately diagnose my product's health and make better product design decisions.

## Hypothesis/(es)
**If** _we deliver more and better metrics trainings around data interpretation and tracking_ **then** _we expect VFS product owners and managers to more easily make data-informed product design decisions_.

## Assumptions
- VFS teams are willing to work with VSP Analytics & Insights to determine Product Owner and VFS application
- VFS teams are willing to work with VSP Analytics & Insights to draft KPIs in the KPI setting workshops
- We can map VFS teams to VFS applications

## Goals
Improve the maturity of KPIs set and tracked through data research and improved or added metrics workshops for VFS product managers.

## Details & Notes
Improve the KPI maturity model for VFS teams.

### Links
[KPI Tracking Documents](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/kpi-tracking)

### Product Outline
KPI Product Outline TBA
[Product Success Tool Product Outline](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#) (KPI Tracking is in conjunction with the Tool)

### Areas for Discovery
How might we improve KPI setting workshops? How might we improve the process for tracking KPIs and the set of KPI trainings that we offer to VFS teams?

### VSP Objectives
`O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.`

### VSP Key Results
- < 5 VA.gov products have error rate > 10%
- Customers track KPIs for 100% of their products.
- Increase in VA.gov user satisfaction

## KPIs
- VFS product team confidence in data-driven decisions

## How to configure this issue
- [ ] Additional KPI trainings have been mapped out
- [ ] Additional KPI trainings have been outlined & established
- [ ] KPI Maturity Model established & shared

**Comment by joanneesteban** [comment]
Q3 Prioritization - Moving to Future.
