### ISSUE TITLE
Add vets-api service role to dev eks cluster

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30861]
## Description
Vets-api pods will need a service role in order to interact with AWS services (i.e. listing/getting objects from S3)

---
## Tasks
- [x] vets-api service role created for dev eks cluster

## Acceptance Criteria 
- [x] service role created for vets-api pods in dev eks cluster with desired permissions on relevant AWS services

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
