### ISSUE TITLE
Update Configuration for BID Awards Service

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#30877]
## Background
The BID Awards API configuration needs to be updated to include new header information and a new auth token.  Parameters that need to be added to the header are `ExternalUid` and `ExternalKey`.  The new token needs to be generated with an additional `applicationID` parameter.  See emails from Shane with more details.

## Tasks
- [ ] Add the `applicationID` to the token generator
- [ ] Add `ExternalUid` and `ExternalKey` to the request header

## Acceptance Criteria
- [ ] A new auth token has been generated
- [ ] A new request header has been created
- [ ] A PR has been submitted for merging
