### ISSUE TITLE
Update COVID pages and add link to CDC alert about pregnant women and vaccines

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30887]
## Issue Description
We need to update our 2 vaccine pages, chatbot and CLP with info about pregnancy and vaccines. This includes adding a CDC alert and possibly ACOG info and emphasizing "strongly" in our recommendation language.

We also need to look at if we need to add crosslinks from relative on-page COVID banners and women’s health pages to the about COVID vaccines page pregnancy section

## Tasks
- [x] Update pages with new content and alert (Danielle)
- [x] Review and publish (Randi)
- [x] Update chatbot (Selina)
- [x] Send text to translation team
- [x] Update Spanish pages (Selina)
- [x] Update Tagalog pages (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] New pregnancy alert and info are live on the site

**Comment by RLHecht** [comment]
Work complete. Closing ticket again.
