### ISSUE TITLE
Update vaccine pages with new info about boosters and how long they last

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#30891]
## Issue Description
There is new info about boosters and how long they last, which needs to be added to our vaccine pages as well as the CLP and the chatbot's relevant questions. 

## Tasks
- [x] Add new booster content (Danielle)
- [x] Review and publish (Randi)
- [ ] Update chatbot (Selina)
- [x] Send text to translators (Randi)
- [x] Update Spanish pages (Selina)
- [x] Update Tagalog pages (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] Vaccine pages, chatbot and CLP are live with new booster content

**Comment by RLHecht** [comment]
@lunascoop here are the translations back to be input.

[https://app.zenhub.com/files/133843125/ceb64f3f-b05d-4233-a7b4-696c049301ab/download](https://app.zenhub.com/files/133843125/ceb64f3f-b05d-4233-a7b4-696c049301ab/download)

[https://app.zenhub.com/files/133843125/ef324045-36b4-4677-b9ec-6d6437608eb9/download](https://app.zenhub.com/files/133843125/ef324045-36b4-4677-b9ec-6d6437608eb9/download)

**Comment by RLHecht** [comment]
@lunascoop Here are the newer translations back: [https://app.zenhub.com/files/133843125/89a25a3d-be5a-4683-a0fb-be11e252a2cd/download](https://app.zenhub.com/files/133843125/89a25a3d-be5a-4683-a0fb-be11e252a2cd/download)

[https://app.zenhub.com/files/133843125/0443d06f-1635-44e2-97ea-307ce3c5af60/download](https://app.zenhub.com/files/133843125/0443d06f-1635-44e2-97ea-307ce3c5af60/download)

**Comment by RLHecht** [comment]
These updates were made to Spanish and Tagalog pages 10/29 and 11/1. Moving to validate and will close after live on site.

**Comment by RLHecht** [comment]
Work completed. Closing ticket and will reopen if there are changes from volunteer translators.
