### ISSUE TITLE
HLR v2: Update content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30899]
## Description

The Higher-Level Review v2 content changes:
- Wizard change text from "Answer a few questions" to "Answer a question" (https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/52Oj4Mx)
- Rated disability content update to match design (https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/ELbk9k2)
- Update homelessness question to match form 526 (https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/1KvQalO)

## Tasks

- [ ] Update wizard content
- [ ] Update homelessness question content
- [ ] Update rated disability page content

## Definition of done

- [ ] All content updates
- [ ] Pages match the design
- [ ] All tests passing
