### ISSUE TITLE
Add rated disabilities mock data to vets-api-mockdata

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#3089]
## User Story
As a frontend engineer, I want to work with mockdata that reflects real world data in production, so I can build frontend applications that work properly with real data returned from a production API. 

## Considerations
- Right now, it seems as if all rated disabilities data is the same across various users when use data from `vets-api-mockdata`. It'd be beneficial to add data to `vets-api-mockdata` that reflects a real-world response so we can build better products. 

## Tasks
- [x] Add response body below to `vets-api-mockdata`
- [x] PR on `vets-api-mockdata`

## Acceptance Criteria
- [x] New data has been added to `vets-api-mockdata` and can be queried locally from `vets-website`.

**Comment by micahchiang** [comment]
```"fetchRatedDisabilities": "fn()",
  "ratedDisabilities": {
    "ratedDisabilities": [
      {
        "decisionCode": "NOTSVCCON",
        "decisionText": "Not Service Connected",
        "diagnosticCode": 6260,
        "name": "Tinnitus",
        "effectiveDate": null,
        "ratedDisabilityId": "1046370",
        "ratingDecisionId": "134241",
        "ratingPercentage": null,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 5260,
        "name": "Allergies due to Hearing Loss",
        "effectiveDate": "2012-05-01T05:00:00.000+00:00",
        "ratedDisabilityId": "1072414",
        "ratingDecisionId": "134242",
        "ratingPercentage": 10,
        "relatedDisabilityDate": "2018-12-22T02:12:08.000+00:00",
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "NOTSVCCON",
        "decisionText": "Not Service Connected",
        "diagnosticCode": 7913,
        "name": "Diabetes",
        "effectiveDate": null,
        "ratedDisabilityId": "1090859",
        "ratingDecisionId": "134243",
        "ratingPercentage": null,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 6100,
        "name": "Hearing Loss",
        "effectiveDate": "2005-01-01T06:00:00.000+00:00",
        "ratedDisabilityId": "1128271",
        "ratingDecisionId": "134244",
        "ratingPercentage": 100,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[0]"
      },
      {
        "decisionCode": "SVCCONNCTED",
        "decisionText": "Service Connected",
        "diagnosticCode": 8540,
        "name": "Sarcoma Soft-Tissue",
        "effectiveDate": "2018-08-01T05:00:00.000+00:00",
        "ratedDisabilityId": "1124345",
        "ratingDecisionId": "134245",
        "ratingPercentage": 0,
        "relatedDisabilityDate": null,
        "specialIssues": "Array[1]"
      }
    ]
  },
  "user": {
    "login": "Object",
    "profile": "Object"
  },
  "totalDisabilityRating": 80,
  "loading": false,
  "error": false
`}

**Comment by micahchiang** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/106

**Comment by micahchiang** [comment]
PR is still open, pending approval, but the work for this ticket has been completed and tested.
