### ISSUE TITLE
Transition Loki to Leverage Elasticache vs Using Cluster Resources for Memcached

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#30902]
## Description
During our production rollout of Loki, we noticed countless errors reporting `server out of memory` where memcached (specifically the pod for `chunks` at the time, but we later increased resources for all Loki component pods). After multiple long threads and attempts to get things under control, we learned that the memcached component of our Loki deployment will consistently need a high level of memory to work as desired. Due to our findings, we see it best to stand up Elasticache resources within AWS for the memcached component to use rather than greatly increasing the cluster nodes to very costly instance types.

## Background/context 
Some threads for additional visibility:
 - https://dsva.slack.com/archives/CJYRZK2HH/p1633381370328600
 - https://dsva.slack.com/archives/CJYRZK2HH/p1633120182278700
 - https://dsva.slack.com/archives/CJYRZK2HH/p1632937965179100
 - https://dsva.slack.com/archives/CTYQL39FE/p1633361952269000

---
## Tasks
- [ ] Dedicated Elasticache created for memcached component of Loki
- [ ] Memcached component pointed to / configured to use new Elasticache

## Acceptance Criteria 
- [ ] Memcached using newly created Elasticache
- [ ] Things working as desired without "out of memory" errors

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/34424, closing.
