### ISSUE TITLE
HLR v2: Add area of disagreement page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#30900]
## Description

Higher-Level Review v2 will include an area of disagreement page matching the page in the Notice of Disagreement form.

Design: https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/jg0dvl7

## Tasks

- [ ] Discover character limit of the field (look at updated Lighthouse schema when available)
- [ ] Add area of disagreement page to HLR v2
- [ ] Add unit tests
- [ ] Update mock data

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
