### ISSUE TITLE
Remove mock data from FE

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30907]
## Issue Description
In order to streamline the data used for debts we need to remove mock data from Debt Letters for the `/v0/debts` and `/v0/debt_letters` endpoints to receive mocked responses from [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/master/debts/index) which will ensure a consistent data set for all apps (Debt Letters, FSR, etc...) calling the same endpoints

---
## Tasks
- [ ] Configure `/v0/debts` and `/v0/debt_letters` endpoints in Debt Letters to fetch from `vets-api-mockdata`
- [ ] Configure `/v0/debts` endpoint in FSR to fetch from `vets-api-mockdata`

## Acceptance Criteria
- [ ] `/v0/debts` endpoint should be receiving mock data from `vets-api-mockdata`
- [ ] `/v0/debt_letters` endpoint should be receiving mock data from `vets-api-mockdata`

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
@ScottyRJames will open a ticket related to this

**Comment by OptionSelect** [comment]
Repo to use data from here: https://github.com/department-of-veterans-affairs/vets-api-mockdata

**Comment by HeatherRienks** [comment]
Per Backlog Refinement, we need to keep this ticket on the board.

**Comment by HeatherRienks** [comment]
@kjsuarez will create a new ticket (4 pts) for a portion of this work

**Comment by kjsuarez** [comment]
Users with existing mockdata responses for debts:
- vets.gov.user+228@gmail.com
- vets.gov.user+1@gmail.com
- vets.gov.user+81@gmail.com
- vets.gov.user+5@gmail.com
- vets.gov.user+14@gmail.com
- vets.gov.user+42@gmail.com
- vets.gov.user+10@gmail.com
- vets.gov.user+21@gmail.com (Bad Request)
- vets.gov.user+38@gmail.com

**Comment by kjsuarez** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30129)

**Comment by kjsuarez** [comment]
Are you having trouble getting mock debts/copays to show up on local? Maybe [this thread ](https://dsva.slack.com/archives/CSFV4QTKN/p1710963215586649)will help!

**Comment by Dr-Pongo** [comment]
Are you _still_ having trouble getting mock debts/copays to show up on local?
Try the fix from the thread above
``` 
# in settings.local.yml
betamocks:
  cache_dir: /cache 
```

**AND**

1. Update your local `vets-api-mockdata`
2. Run `ruby make_table.rb` in that repo 
3. Followed by `make rebuild`

There's some more in depth and maybe helpful [documentation here for betamocks _stuffs_](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md)
