### ISSUE TITLE
Update Collaboration Cycle overview page (ie homepage)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#30906]
## Issue Description
The Collaboration Cycle overview page on Platform Website (ie the homepage) is lacking. This is the first thing VFS teams see when they click on the "Collaboration Cycle" tile from the Platform Website homepage, and it does not provide a thorough or complete explanation of the Collaboration Cycle. Current page below:
![image](https://user-images.githubusercontent.com/71330581/141143189-bec34c97-e931-41d0-988f-3df4c1c927be.png)

The purpose of this ticket is to 1) expand the content of this page to explain in greater detail what the Collaboration Cycle, how it works and why it exists, and 2) include a diagram of the Collaboration Cycle that is currently only provided in VA.gov Platform - General Orientation. The Collaboration Cycle diagram is a helpful visual aid for VFS teams to understand the steps of the Collaboration Cycle. It would be beneficial for VFS teams to see this visual on Platform Website. 

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/1fdc0539-b741-4adc-9779-24caa9c60ba4)

---
## Tasks
- [ ] Ensure that the visual is accessible (alt text, etc.) (contact @noahgelman for support)

## Acceptance Criteria
- [ ] VFS teams who are familiar with the four-stage iterative UX model can understand how stages of Collaboration Cycle align with that model 
- [ ] It is clear to VFS teams why the CC exists, the reasons it came into being, and why it is valuable for a VFS team
- [ ] VFS teams who aren't as  familiar w/ the model can understand how the steps in CC cycle align with their team's customary workflow

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@noahgelman we requested on Slack that you complete an accessibility review of the diagram @jimuhh added. Please review ASAP so that we can push this to Platform Website and close the ticket. thanks.

**Comment by jimuhh** [comment]
@shiragoodman -- i scaled back the text I was adding and went with a list that mirrors the text in the image. @peggygannon is going to look it over and make any edits if needed. Then we can call this done.

**Comment by shiragoodman** [comment]
sounds good to me @jimuhh!

**Comment by shiragoodman** [comment]
@jimuhh I updated the title of this ticket and expanded on the issue description. I did not change the AC as I think it is still applicable.

**Comment by peggygannon** [comment]
Hi, @shiragoodman and @jimuhh update page is here: 

https://vfs.atlassian.net/wiki/spaces/PPST/pages/1948090436/Collaboration+Cycle+--+DRAFT

**Comment by shiragoodman** [comment]
I commented in the Confluence draft. When the comments are addressed, please review the AC and then the ticket can be closed. FYI @jimuhh

**Comment by peggygannon** [comment]
Thanks, @shiragoodman I've resolved your comments (thank you!). 

@jimuhh do you want to review the page one more time,  and then publish if you have no additional feedback?

**Comment by jimuhh** [comment]
@peggygannon. Sure. I will do that today.

**Comment by jimuhh** [comment]
Page has been reviewed and[ published here](https://vfs.atlassian.net/wiki/spaces/CC/overview)
