### ISSUE TITLE
Configure mock data for debts

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#30912]
## Issue Description
Need to create mock data for the `/v0/debt_letters` endpoint in [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata). We also need to verify the correct data is being returned for calls to the `/v0/debts` endpoint.

Sample response payload for calls to `/v0/debt_letters`

```
[
  {
    "documentId": "{64B0BDC4-D40C-4C54-86E0-104C987B8D8F}",
    "docType": "1213",
    "typeDescription": "DMC - Second Demand Letter",
    "receivedAt": "2020-05-26"
  },
  {
    "documentId": "{70412535-E39E-4202-B24E-2751D9FBC874}",
    "docType": "194",
    "typeDescription": "DMC - First Demand Letter",
    "receivedAt": "2020-05-27"
  },
  {
    "documentId": "{3626D232-98D9-41AB-AA3A-CD2DDF7DA59C}",
    "docType": "194",
    "typeDescription": "DMC - First Demand Letter",
    "receivedAt": "2020-05-28"
  },
  {
    "documentId": "{641D0414-10A9-4246-9AFD-3C0BE2D62B2F}",
    "docType": "1213",
    "typeDescription": "DMC - Second Demand Letter",
    "receivedAt": "2020-05-29"
  }
]
```

---
## Tasks
- [ ] Configure mock debts for the `/v0/debt_letters` endpoint in [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata)
- [ ] Verify the correct mock data is being returned by the `/v0/debts` endpoint

## Acceptance Criteria
- [ ] API calls to `/v0/debt_letters` when `mock: true` should return a response from [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata)
- [ ] Calls to `/v0/debts` and `/v0/debt_letters` endpoints should return the correct mock data

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
