### ISSUE TITLE
Display "walk in availability" based on CMS/Lighthouse data

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#30915]
## Issue Description
Currently, we display "walk in availability" for all facilities returned to COVID-19 vaccine service searches. Walk ins are no longer available at all locations so we need to move to a location specific display. We can use the data which is available in CMS and pushed to Lighthouse to determine the display in Facility Locator. 

During grooming of this issue, we determined that a flag should not be necessary if the data is trusted. If the data indicates a location does not have walk in availability or has not set a value for walk in availability, there will not be a display. We confirmed  data consistency between CMS and Lighthouse before making this determination. 

---
## Tasks
- [ ] Use the value `walk_ins_accepted` in detailed services for COVID-19 vaccines to determine the display of "Walk-ins accepted" 
- [ ] Maintain code for wording of "Or/call to schedule: [phone]" based on status of walk-in availability

## Testing
- Goldsboro VA Clinic can be used to test `walkInsAccepted`= true 
- Brier Creek VA Clinic can be used to test  `walkInsAccepted`= false
- We have two PAOs ( Jason Dominguez - Sacramento and Anthony Rivera) who are willing to assist with testing 

## Acceptance Criteria

When Facility Locator search parameters = VA health + COVID-19 vaccine services
- [ ] If a VAMC has `walk_ins_accepted` = true in CMS, the search result card in Facility Locator includes "Walk-ins accepted" and "Or call to schedule: [phone]"
- [ ] If a VAMC has `walk_ins_accepted` = false or unknown in CMS, the search result card in Facility Locator displays only "Call to schedule: [phone]"
---
- [ ] When Facility Locator search parameters = VA health + all services or any other service,  search result cards in Facility Locator do not include walk-in availability or  "call to schedule" text
