### ISSUE TITLE
Support Request from Sitewide Content regarding IRIS

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30946]
## Issue Description
Content's work managing the changeover from IRIS to Ask VA on October 18, we found some places where there are mentions of IRIS in tools and apps that we can't access. One result that came back is: src/applications/claims-status/components/AskVAQuestions.jsx
Would you or a dev on your team be able to help me learn what the context of the IRIS mention is here so I know what content we should be replacing it with? 
([slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1633465848274400))

---
## Tasks
- [ ] Can we determine context of IRIS mention?

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
