### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#30985]
## Description
Share work accomplished during sprint with PO and other key stakeholders for feedback.

---
## Tasks
- [ ] Schedule and maintain ceremony + pre-sync.
- [ ] Determine what to demo.
- [ ] Add slides to [contract management deck](https://mostudio.box.com/s/k8s5m49nxk59d987qqnb6abv9c4aufiu).
- [ ] Copy edit and final formatting.
- [ ] Conduct Demo Pre-Sync.
- [ ] Conduct demo.
- [ ] Capture action items and put into backlog.
- [ ] Upload deliverables to repo.
