### ISSUE TITLE
Retro

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#30986]
## Description
Reflect on what went well and what to improve, as well as identify action items. 

---
## Tasks
- [ ] Confirm time or reschedule as needed (24 hours in advance).
- [ ] Create retro board (with optional activity).
- [ ] Conduct retro.
- [ ] Add action items into backlog.
