### ISSUE TITLE
Stakeholder Engagement

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#30999]
## Description
Stakeholder engagement is a critical component to this program. It is a complex ecosystem and the Apartment concept requires engagement from many different teams. We'll stay in close alignment on who we engage and how and build lasting, authentic relationships. As we meet new teams, we'll need to learn how our product could impact others and be appropriately disruptive at the right times.

---
## Acceptance Criteria 
- [ ] Stakeholders feel engaged and understand the program.

---
## Tasks
- [ ] Working Group
- [ ] Team of Teams
- [ ] VA.gov Platform and Apps Weekly Design + Content + Research Sync
- [ ] Mobile Auth and DHM

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/30999?planning-poker) with ZenHub @LSiopis @JaredMostudio @nprimak
