### ISSUE TITLE
Apartment Working Group

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31009]
## Issue Description
This is a monthly checkpoint for people and teams working on the health “apartment”<https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/onboarding.md#vision>. The purpose of the meeting is to demo apartment-related development, give feedback, surface problems and ask for help.

---
## Acceptance Criteria 
- [ ] TO BE COMPLETED

---
## Tasks
- [ ] Prepare agenda and materials.
- [ ] Host session.
- [ ] Capture and send action items and key takeaways to all invitees within 24 hours.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31009?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
