### ISSUE TITLE
Health APT proof of concept and MVP weekly check-in

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31008]
## Issue Description
Weekly sync first on POC, then on MVP when we get there.

---
## Acceptance Criteria 
- [ ] TO BE COMPLETED.

---
## Tasks
- [ ] Prepare agenda and questions.
- [ ] Capture and send any action items to invitees within 24 hours.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31008?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
