### ISSUE TITLE
GitHub Repo

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31006]
## Issue Description
Ensure the Apartment GitHub repo is created and add as acceptance criteria to issues in flight as appropriate. The DHM repo uses the pattern most teams use, with the workshops item as an addition >>
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization

---
## Acceptance Criteria 
- [x] Apartment GitHub repo built within the health-care section
- [ ] Periodic review of repo scheduled

---
## Tasks
- [ ] TO BE COMPLETED

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31006?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
