### ISSUE TITLE
Issues created and aligned with stakeholder matrix for governance meetings

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31007]
## Issue Description
There are several key governance meetings in addition to the agile ceremonies of the core team. These should be kept up to date in our Stakeholder Matrix and managed as issues so that attendees and facilitators are prepared for them, actively engaged, and follow up on actions.

---
## Acceptance Criteria 
- [ ] Governance meetings are added as issues. 
- [ ] Stakeholder matrix updated and reviewed with MO leadership.

---
## Tasks
- [ ] TO BE COMPLETED

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31007?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
