### ISSUE TITLE
Team of Teams

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31010]
## Issue Description
Every week, 1 person from the Health APT Team gives an update: what we're working on, progress, desired connections, dependencies, and blockers (see links below for templates and examples). Listen in at meeting and make meaningful connections through follow-ups. Bring relevant information back to the team. Engage on Slack for discussion.

---
## Acceptance Criteria 
- [ ] ToT slide sent to Liz in Slack by 10am on Tuesday.
- [ ] ToT slide uploaded to [Box](https://mostudio.app.box.com/folder/147380247690).

---
## Tasks
- [ ] Prepare slide.
- [ ] Get feedback from team on slide.
- [ ] Present during ToT.
- [ ] Capture any questions or comments for our team.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31010?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
