### ISSUE TITLE
Sprint Acceptance

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31018]
## Issue Description
Ensure team and client are aware of work completed within the sprint. Request acceptance.

---
## Acceptance Criteria 
- [ ] Sprint accepted.

---
## Tasks

- [ ] Update Acceptance Form within monthly PM report (save as a new month if this is the first sprint after the 7th of the month).
- [ ] Package materials or check links and add to email.
- [ ] Submit via email for acceptance.
- [ ] Invoice.
- [ ] Update Accepted Date and Invoiced Date  in Monthly PM report.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31018?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
