### ISSUE TITLE
Monthly Reporting

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31019]
## Description
Ensure submission of monthly report by the 7th of each month. Work with team to populate inputs.

---
## Acceptance Criteria 
- [ ] Monthly Report submitted

---
## Tasks
- [ ] Update on a weekly basis.
- [ ] Within first week of month, begin fleshing out additional details.
- [ ] Leadership review for feedback.
- [ ] Final formatting and copy editing.
- [ ] Submit.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31019?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
