### ISSUE TITLE
VA.gov Platform and Apps Weekly Design + Content + Research Sync

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31013]
## Issue Description
From the meeting invite:
This is a cross-team weekly design meeting for design + content + research + IA + 508 + design system + style guides for VA.gov<https://slack-redir.net/link?url=http%3A%2F%2FVA.gov>. We will use this time to talk through research synthesis, design critiques, connect dots across teams, discuss any gnarly design problems, share design & content updates with each other, and cover any other issues. Anyone is welcome, but designers, researchers, content, and IA folks are strongly encouraged to attend!

Expectations:
Come and be present. This is YOUR time to get feedback from your fellow designers. It’s your time to learn what others are doing that may affect decisions you make in your work. It is your time to get updates about important changes. Join, turn off other distractions for 1 hour a week, listen, participate, and share. You get out of this time together what you put into it.

All updates and changes to this meeting will be maintained here and in #design<https://dsva.slack.com/archives/C0NGDDXME> slack channel.

---
## Acceptance Criteria 
- [ ]  Health-Apartment team represented at meeting
- [ ] Health-Apartment design questions / topics identified and prepared for meeting when needed

---
## Tasks
- [ ] Attend session.
- [ ] Gather PPTs, materials, etc. and store in Box.
- [ ] Share out any relevant takeaways with team.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31013?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
