### ISSUE TITLE
Weekly Report

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31014]
## Issue Description
TO BE COMPLETED

---
## Acceptance Criteria 
- [ ] TO BE COMPLETED

---
## Tasks
- [ ] Provide Input to Weekly Report.
- [ ] Copy edit Weekly Report.
- [ ] Submit Weekly Report by EOD Friday.

**Comment by Paula-G-Mendoza** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Health---Apartment-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/31014?planning-poker) with ZenHub @JaredMostudio @LSiopis @nprimak
