### ISSUE TITLE
[Claim Status Tool] Add confirmation checkbox to Additional Evidence Upload Screen

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3102]
## User Story
As a claimant, I want to ensure the documentation I upload as supporting evidence to an existing claim is reviewed, so that it could potentially aid in getting me the most accurate decision for my claim. 

## Goal
Add a checkbox confirmation to the additional evidence upload screen.

## Tasks
- [x] Identify the direction the content should take - check with Paul Shute
- [x] New design #3455
- [x] Have Peggy review the checkbox wording to ensure optimal verbiage #3456
- [x] Have FEs implement checkbox and wording into the UI 

![Upload Additional Evidence - File Selected - screenshot.png](https://images.zenhubusercontent.com/5d65638e0845ad5f24bada4a/55f99b47-8227-4bf5-8cad-b5114dc03161)

**Comment by YanaRoy** [comment]
@YanaRoy expand on ticket details

**Comment by YanaRoy** [comment]
Yana reached out to Paul for direction the content should take

**Comment by YanaRoy** [comment]
Discussion with Paul:
	- Required by law to review all documentation
	- If they want to submit something, encourage the user to file another claim if needed
	- If not providing evidence in support of their claim, they should file a new claim for the evidence they want to submit
        - Direct them to How to Submit a Claim page or to Decision Review page
