### ISSUE TITLE
Onboarding Contract

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#31021]
## Description
New team members will be required to go through contract onboarding which will have a recurring set of issues captured here.

---
## Acceptance Criteria 
- [ ] Team members onboarded efficiently and feel confident in joining the team with the tools they need.

---
## Tasks
- [ ] Google Analytics
- [ ] Optimal Workshop
- [ ] Mural
- [ ] Box
- [ ] Clockify
- [ ] Zenhub
- [ ] Github
- [ ] Slack
- [ ] Email
- [ ] VA Onboarding (TMS, PIV, fingerprint)
- [ ] Charter
- [ ] Platform Orientations
- [ ] Ceremonies
- [ ] CEDAR IDIQ Onboarding
- [ ] 1:1 Intros
- [ ] MO Onboarding
