### ISSUE TITLE
[Tech-Debt]  Assure that all Programs pages are published and COVID-19 vaccine page are correct [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31041]
## Story
As an editor I need to have my COVID-19 vaccines page correctly placed under Programs and Programs published, so I can associate the page correctly and so the COVID-19 page can be correctly displayed.

## Goal
By publishing the Programs page, not enabling in on Menu unless required, it can have child pages 

## TASKS
Update approximately 22 Program Pages and COVID-19 Vaccine pages:
- [x] Publish Program pages, but only enable menu if PAO requests.  Leave it disabled
- [x] Move COVID-19 vaccine page under Programs in Menu location and rename alias to include Programs correctly.  Publish
- [x] Confirm Menu is updated correctly 

## Acceptance criteria:
- [x] All programs and COVID-19 vaccine pages have been published and menues are correct.

**Comment by ltrombley** [comment]
Task #31041 - Assure that all Programs pages are published and COVID-19 vaccine page are correct [BA]  - is Complete and moved to Validate
