### ISSUE TITLE
[VAMC] Create and present Content presentation for Communities of Practice regarding Active Voice [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31047]
## Story
As an editor I need to better understand how to write using standards from the va.gov contents style guide, so I can better communicate to the Veterans

## Goal
Provide tips and guidance regarding content writing in system pages.

## Tasks
- [ ] Create a content based presentation focused on va-style guide standards
- [ ] Support basic standards to improve the editors writing in VAMC web pages
- [ ] Present this guidance to Communities of Practice 

## Acceptance
- [ ] Presentation is created and available for submission to VAMC SharePoint
- [ ] Present guidance to Editors during COP meeting.
