### ISSUE TITLE
[VAMC] Web Authorization document and web form completed for October 20th Full producction cut over [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31049]
## Story
As an editor I need to know of any additional final clean up items and barriers, and all tech-debt needs to be resolved, so MVP is present and/or I can clean them up prior to Go Live

## Goal
Investigate and fill in data needed for Web Authorization web form that will be submitted to VHA DM for approval

## Resources
[PAO Directory & Training contact list](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FWeb%5FAuthorizations&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## Task
**Prepare the following Systems for Full Production/Redirect from Legacy URL**
- [x] VA Iowa city
- [x] VA Tuscaloosa health care
- [x] VA Bronx
- [x] VA Battle Creek health care
- [x] VA Saginaw health care
- [x] VA Northern Indiana health care
- [x] VA Central Iowa
- [x] VA Detroit
- [x] VA Tampa
- [x] VA Miami
- [x] VA South Texas
- [x] VA Loma Linda
- [ ] VA Dublin health care
- [ ] VA Atlanta health care
- [ ] VA Amarillo health care
- [ ] VA Central Texas health care
- [ ] VA El Paso health care

## Complete the following tasks for all systems listed above:
- [x] Complete Web Authorization data sheet to include two POCs with email, phone, and address.

**Final**
- [x] Submit Data into Web Authorization form, copy image into e-mail to be submitted to VHA for approval
- [x] Send email with images for confirmation

## Acceptance criteria
- [x] Web Authorization sheet is saved in SharePoint Folder with date
- [x] All Systems are submitted into Web Authorization web form
- [x] images are copied into document of email for later submission as required.
