### ISSUE TITLE
[BE] SPIKE - Research System Architecture Design for Pre-Checkin 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#31051]
This item is to determine best go forward architecture solution for Pre-Checkin and create appropriate diagrams for the design.

## How to configure this issue

- [x] Attached to an Epic (what body of work is this a part of?)
- [x] Correctly Labeled
- [x] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [x] Fill in Acceptance Criteria

---

## User Story

> As a Veteran, I want to be able to complete complete pre check-in activities such as confirming contact information so that I can streamline the checkin process. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Write rspec tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Research completed
- [ ] Flow and/or sequence diagrams updated and/or created.

**Comment by dillo** [comment]
![pre-check-in-sequence.png](https://images.zenhubusercontent.com/5f6a6795c344a3ecea8559fe/c2e0cdf4-81c9-4ec5-8ec7-e9e156bbcb33)

Sequence diagram take one.

**Comment by dillo** [comment]
![pre-check-in-happy-path (1).png](https://images.zenhubusercontent.com/5f6a6795c344a3ecea8559fe/8ff79911-1d92-441e-9265-bd487924651b)
