### ISSUE TITLE
[FE] Integrate the Demographics Page into routing

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#31054]
## User Story

> these should be why the veteran cares, and the veteran gets out of it.
As a veteran, I should be able to my current information so that I can confirm it

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the Page component for the new page. This should be behind the feature toggle. This ticket is just for the routing

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create new page  for demographics behind a feature flip
- [x] Integrate into the page routing from the validate page
- [x] Add routing from the to update page (which is also behind a feature flip) 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
