### ISSUE TITLE
[BE] LoROTA Integration to Populate Demographics

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#31050]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- (%FILL IN%)
- (%FILL IN%)

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> Need to surface the demographics from LoROTA that will be populated in the UI for the read-only demographics screen. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Write rspec tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] FE engineering team has signed off on the  feature
