### ISSUE TITLE
Update usability testing plan (pre-check-in)

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31066]
## User Story
- As a Veteran, I want to update my information from the comfort of my home and not be rushed when I arrive at the facility for my appointment.
- As a Veteran, I to reduce my waiting time between checking in and seeing my provider.
- As an MSA, I want to spend less time on pre-registration, so I can focus on other critical tasks. This would improve my job satisfaction.
- As an administrative and clinical staff member, I want to be more prepared for the appointment, have more context around the patient's reason for visit, and understand more about their overall health, which could impact the appointment outcome.
- As a facility administrator, I want an increase in Veteran profile information accuracy.
- As a facility administrator, I want less no shows and surprises, such as Veterans showing up in-person for a virtual appointment, showing up on the wrong day, or showing up at the wrong clinic.
- As a product development team, we want to know if pre-check-in is meeting the needs of Veterans and staff.

## Related Documentation
 - [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover items from [this Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1633010497987/797726a2962d131b23e7126a8d3cbec96306d3fc?sender=uc940f53ad96ac0203d6d3631).
- An earlier draft [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability) were created for pre-check-in, but they need to be updated. We have learned a lot, since the initial plan was crafted.

## Tasks
- [ ] Update the research plan
  - Utilize the new [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) developed by the research ops group.
- [ ] Update the conversation guide

## Acceptance Criteria
- [ ] Review research plan and conversation guide with team (particularly product and UX)
- [ ] Post finalize research plan and conversation guide to [GitHub folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability)

**Comment by kristenmcconnell** [comment]
Research plan and conversation guide sent out for the research plan review and to start recruitment: https://dsva.slack.com/archives/C022AC2STBM/p1634323535010900
