### ISSUE TITLE
[Research] Create Telemedicine Research Plan 

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31072]
## User Story
- As a Veteran, I want to be able to complete Pre-Check-in for virtual visits. 
- As a Veteran, I want to be able to use my mobile phone to check-in for all of my VA appointments that I have within any given day. 
- As a Veteran, I expect to see telemedicine appointments included in the list when checking in. 
- As a product development team, we want to know if including the ability to view and check-in for telehealth appointments when viewing multiple appointments in one day is desired by Veterans.

## Description
- Focus will be on how we can support virtual visits in the Pre-check-in flow
More research is needed to determine if telemedicine appointments should be included or connected to the online check-in experience. When eliciting initial interest in displaying telemedicine appointments within the online check-in experience, there was no consensus among the participants.
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

- This research study should cover understanding all the telemedicine use cases and how they connect to online check-in. 

## Tasks
- [ ] Team discussion around what is needed
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing).
- [ ] Create research plan (might have 2 phases: discovery then user)
  - Utilize the new [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) developed by the research ops group.
- [ ] Create conversation guide [if user facing]
  
## Acceptance Criteria
- [ ] Review research plan with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan to GitHub folder

**Comment by julieadair1** [comment]
@jparker0425 we are pulling this back into the backlog for now.  Do we need to remove the milestone?
