### ISSUE TITLE
Find a VA Form:  Search Landing Page PDF Modal: Update text, add 24 hour cookie

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31081]
## Issue Description
Update the modal text and links to reflect the [content feedback from the Design intent review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-953070611).  

Since we have no way of determining if a user has Adobe Reader DC installed, please add a cookie so that the pop-up only gets displayed one time per day so it doesn't become annoying.

Uses cases are described here.  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md

Specific to this ticket are use cases [S-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-f) and [S-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-g)

---

## Tasks

- [x] Update the text to reflect what content has provided. 
- [ ] Add a cookie to the Search Landing Page so that the PDF modal is displayed once every 24 hours per user
- [ ] Deploy to Staging behind a feature flag

## Acceptance Criteria
- [ ] The modal will reflect the updated text
- [ ] The modal will be displayed the first time someone clicks on a link to download a PDF on the Search landing page
- [ ] The modal on the Search landing page will not display again for the same user until 24 hours have passed.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Moving this to Sprint 59 because we have not gotten analytics feedback.

**Comment by zacharymorel** [comment]
Oh shoot. Nice catch @MarciMcGuireGCIO, there is no cookie in the modal and the text is **NOT** matching the latest  on staging. How would you like to proceed? 

As far as the cookie is concerned, adding that would be an effort level of a 3. 
The logic behind showing the modal based on whether or not there is a cookie will be complex because it and the search result link behavior will be dependant on whether the user has already seen a modal.

**Comment by MarciMcGuireGCIO** [comment]
Thanks! Ok, we have a design intent next Tue for the modal, and I still have to schedule QA, so let's swap this one out for the other stuff related to the modal for this sprint.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel we have [updated copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574) for this now, so please take a look and update your estimate if needed.  Thank you!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Est stays the same. Q though, as far as the download link is concern, the design shows the new link whereas content says "BUTTON". Seen screen shot. Can I get a clarification on that? I assume we are keeping the design and just changing the content copy
<img width="352" alt="Screen Shot 2021-11-03 at 10 58 14 AM" src="https://user-images.githubusercontent.com/26075258/140085412-df8668cf-fc3e-43fc-a29f-a66b6773310a.png">
.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel updated design hot out of the oven -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/32357#issuecomment-959489153 - thanks @callen2563 !! 

![image](https://user-images.githubusercontent.com/73354907/140097456-4c8ac61b-b17c-4822-ab8b-bb60e09d2420.png)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Ryan suggested a button even though it's outside the standard design pattern, and Angela and Mikki agreed it made for better continuity in the user experience.

**Comment by zacharymorel** [comment]
Thank you y'all!

**Comment by MarciMcGuireGCIO** [comment]
This is on staging and working as expected.
