### ISSUE TITLE
Login.gov Failed Identity Proofing Page

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#31094]
## Issue Description
If a user fails identity proofing and is redirected to us, we need to update the error code and error content for the user.  We will redirect a user to this URL https://staging.va.gov/auth/login/callback?type=logingov&auth=fail&code=[some code by BE or Login.gov]

Per https://developers.login.gov/production/
"If this is an IAL2 integration, you must include a Failure to Proof URL. This is the URL users will be sent to if they fail to complete the identity verification process so you can communicate alternative methods of accessing your application."

---
## Tasks
- [x] Work with VSA Public Sites to update content and troubleshooting steps
- [x] AuthApp  component should handle error codes provided by vets-api callback
- [x] Work with John B. or Josh S. to ensure Login.gov error codes are handled
- [x] Update AuthApp error content and troubleshooting steps.

## Acceptance Criteria
- [x] When a user fails identity proofing and lands on VA.gov, provide an error page and troubleshooting steps.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by codyreinold-usds** [comment]
We will not receive information back from Login.gov as to why the user failed identity proofing. As a result, we won't be able to provide an extensive amount of detail.
