### ISSUE TITLE
[Research] User Role Research: Scope existing personas list down for MVP/discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31128]
## Background
Once we have an idea of what documentation already exists and what previous research on this topic may look like we need to scope the list of personas/roles to what would realistically exist on VA.gov

## Tasks
- [x] Review existing documentation
- [x] Refine to propose what should exist on VA.gov

## Acceptance Criteria
- [x] Draft list of proposed roles/personas for VA.gov exist in GH

**Comment by andaleliz** [comment]
_Based on what I know now_ I've put together a list of [possible user roles for an MVP in my phase 1 discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/user-roles/discovery/non-veteran-user-roles-discovery-phase-1.md#4-scope-the-list-of-user-roles-to-a-manageable-list-we-would-actually-build-on-vagov).
