### ISSUE TITLE
[Research] User Roles Research: Identify SMEs at VBA, VHA, NCA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31130]
[Project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/user-roles/project-outline-user-roles-permissions-research.md)

Currently, what defines a “non-Veteran” and their use cases are not well understood across the VA. Each administration—VHA, VBA, and NCA—has their own unique definitions and nuances, which significantly increase the complexity of solving for the “non-Veteran” use case. Delegates, beneficiaries, caregivers, and dependents are a few terms used interchangeably that encompass many different user types relying on many different products and services across VA.

We need to identify SMEs who can help us understand unique definitions and nuances in each administration.

**Tasks**

- [x] Identify VBA SMEs
- [x] Identify VHA SMEs
- [ ] Identify NCA SMEs

**Comment by andaleliz** [comment]
@Samara-Strauss Would it make sense to talk to anyone at VEO as a SME for this? I ask because I found a list of people who worked on that [Veteran Customer Personas PDF I attached in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1633621229005500?thread_ts=1633531860.455600&cid=C909ZG2BB) - Denise Kitts is the only one I can find in the VA address book and it looks like she's still with VEO. Maybe she could be helpful?

**Comment by andaleliz** [comment]
@Samara-Strauss thanks for all your help in identifying these SME's! I really appreciate it. We'll leave this open until we get an NCA contact.

**Comment by Samara-Strauss** [comment]
Sounds good -- Charles said he'd ask around to see if he can find anyone. If we don't get anyone by Tuesday, this is complete as far as I'm concerned for sprint purposes. It's not you're fault we're having trouble tracking down an NCA contact.

**Comment by andaleliz** [comment]
@Samara-Strauss yesterday we discussed that it may not even be worth reaching out to NCA. Did you hear any more thoughts from John/Cody on that?

**Comment by Samara-Strauss** [comment]
@andaleliz yes, I am so sorry I forgot to update you. We determined that we can hold off for now and move forward with the list of people we have.

**Comment by andaleliz** [comment]
No prob! Sounds good, I'll close this out.
