### ISSUE TITLE
Sync (or Walkthrough) Search and Appoint Rep Development with Designs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#31132]
## Considerations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30360#issuecomment-934406027

## Tasks
- [ ] Walkthrough design screens
- [ ] add to the content build rep, before adding to staging (Stretch)
- [ ] Sync with design files (link above) (Stretch)

## Acceptance Criteria
- [ ] Dev has been synced with Design screens
