### ISSUE TITLE
Add new Lighthouse Legacy Appeals endpoint to vets-api

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#31149]
## Issue Description
Lighthouse added a new endpoint:
https://github.com/department-of-veterans-affairs/vets-api/pull/7350

Our vet-website FE lead asked us to just add the legacy_appeals data returned from this new endpoint to the already existing contestable_issues endpoint.  Legacy Appeals are just a special "tag" of contestable issues.

Also, for every Legacy Appeal, there should be a matching Contestable Issue.  However, currently there is no way to pair up the two.  Right now, the FE will just use the existence of any Legacy Appeals Issues that the contestable_issues EP returns to ask the "Legacy Appeals" opt in question on the gui.  If no LAs present for a user, the web page will skip the LA opt in question.  

Just to be clear, the website will not attempt to show any Legacy Appeals on the HLR contestable Issues Page since any LAs will already have a Contestable Issue that already shows.  Ideally, we would like the webpage to indicated what Contestable Issues are Legacy Appeals, but since there is no way to associate LAs with their corresponding CI, we can't at this time.

As of Oct, 6, 2021 no swagger docs on the new endpoint, but it's pending:
The new URL is: https://sandbox-api.va.gov/services/appeals/v2/decision_reviews/legacy_appeals

---
## Tasks
- [x] Add schema to vets-json-schema
- [x] Add new endpoint as a service in vets-api

## Acceptance Criteria

- [x] Existing v1/higher_level_reviews/contestable_issues End point should return both CIs and Legacy Appeals
- [x] Any errors when fetching Legacy Appeals should not cause the CI endpoint to error out

PR to similar jobs, Add lighthouse HLR v2 endpoint to vets-api
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/627
https://github.com/department-of-veterans-affairs/vets-api/pull/7795

**Comment by michelpmcdonald** [comment]
The new endpoint was not working in staging.  Turns out there was no mocked data, I did work the ticket as far as I could without having the endpoint live and working.

But as of 10/28, the LH team added mocked data, so this ticket can now continue to be worked.

**Comment by michelpmcdonald** [comment]
Work complete, wating for PR-Merge before closing

**Comment by michelpmcdonald** [comment]
merged
