### ISSUE TITLE
Create as-is Service Blueprint for Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31153]
## Issue Description
Before work can begin on Phase 1, we must first document the as-is state of Platform Orientation, including VFS tasks, Platform tasks, as well as tools, services and documentation referenced. This will help us have a shared understanding of the current state. When Phase 1 solutions are implemented, we will return to the Service Blueprint and update it to reflect the Phase 1 changes.

---
## Tasks
- [x] Document goals and desired outcome(s) for creating the service blueprint.
- [x] Get approval from PO on the above.
- [x] Create service blueprint
- [x] Review gaps/ opportunities with PO

## Acceptance Criteria
- [x] Product support has reviewed and approved the service blueprint that shows the VFS touchpoints and Platform backstage processes throughout the Orientation process.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rebekahickey** [comment]
- Started a draft service blueprint in Mural: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1634334965737/bf671d055e1072a001d00cd1d6b7dc89b0987bfc?sender=u79256ba52f9221838a435866
- Reviewed blueprint with Platform Orientation team during the standing Friday meeting on 11/5

**Comment by rebekahickey** [comment]
- Reviewed orientation service blueprint with Shira
- Cleaning up blueprint to prep for a final review with team on 11/12

**Comment by jchasia-adhoc** [comment]
@shiragoodman - are we good to close this ticket?

**Comment by jchasia-adhoc** [comment]
Held workshop with Product Owner.

**Comment by shiragoodman** [comment]
sorry @jchasia-adhoc ! Yes, this is/was good to close.
