### ISSUE TITLE
Add PDF link on VGLI life insurance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31165]
## Issue Description
Stakeholder Steven Filal asked us to add text and a link to a PDF about comparing VGLI to whole life insurance coverage to the [VGLI page](https://www.va.gov/life-insurance/options-eligibility/vgli/). 

Under the H2 What life insurance benefits can I get with VGLI? his suggested text is:

You can get $10,000 to $400,000 in term life insurance benefits, based on the amount of SGLI coverage you had when you left the military.  To learn more about the difference between term and whole life coverage, click here.

Link to add: https://www.benefits.va.gov/INSURANCE/docs/VGLI_flyer_FL_GI449_01_r3.pdf

We need to rework the language so it fits VA.gov's voice and style—don't use "click here." 

---
## Tasks
- [x] Add link text
- [x] Review and publish
- [x] Alert stakeholder that changes are live

## Acceptance Criteria
- [x] New linked text is on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO What do you think of adding the link like this? I know it's really long but I think we should have the title of the sheet in it.

You can get $10,000 to $400,000 in term life insurance benefits, based on the amount of SGLI coverage you had when you left the military. 

Learn more about the difference between term and whole life coverage. 
[Download Comparing Veterans’ Group Life Insurance (VGLI) to Whole Life Insurance Coverage (PDF)](https://www.benefits.va.gov/INSURANCE/docs/VGLI_flyer_FL_GI449_01_r3.pdf)

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
