### ISSUE TITLE
[MCP] Designs for HTML statements

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#31161]
## Issue Description
Once initial technical discovery is completed, we need to incorporate HTML statements into the detail pages of MCP.

---
## Tasks
- [x] Create mockups of the new HTML statement designs (detail page, html statement page) and upload to UXPin

## Acceptance Criteria
- [x] Designs uploaded to UXPin
- [x] Designs shared with FE / FE tickets created

**Comment by rebeccawalsh** [comment]
Designs have been uploaded to UXPin:
- [Changes to the debt detail page include updating the h2 and adding statement links](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141834693/simulate/sitemap?mode=i)
- [HTML statement page](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i)

**Comment by rebeccawalsh** [comment]
[FE ticket created!](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/32846)
