### ISSUE TITLE
Create Error Message Code Matrix

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3116]
## Background 
Through our efforts of digging in deeper to understand the Address Validation system operations, we've uncovered a numerous amount of various error codes that can be thrown by the system when a user inputs their mailing address information into the system. We need a single source of truth to document all of the potential error codes that could be seen. Initial links that have been shared with our team can be found here  at this link > [ Address Validation Swagger Link ](https://qa.vet360.va.gov/address-validation/swagger/address-v1-msg-keys.html)

## ScreenShots 
![Screen Shot 2019-11-05 at 10.24.29 AM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/1259448a-7997-4785-bf97-08f366f4f03e)
![Screen Shot 2019-11-05 at 10.25.01 AM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/bdfd3684-cfb5-4534-803c-5b578de2847a)
![Screen Shot 2019-11-05 at 10.25.23 AM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/6fb6b627-c907-4dc4-b719-01473e110be2)
## Goals
Create a single document that houses all of the potential error codes that could be seen. This document should include a) the error code, b) what it means, and c) what we’re doing about it.  

## Tasks
- [x] Create a spreadsheet/matrix that has the error code b) what it means and c) what we’re doing about it.
- [x] Confirm with VetProfile team all error codes are accounted for
- [x] Upload spreadsheet/matrix to Github repository. Can be found here [ CLICK LINK ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/_ErrorCodesForOverride_DRAFT-WithExamples.xlsx ) 

## Acceptance Criteria 
- [x] The spreadsheet/matrix has been created, socialized with team and uploaded to Github repository
- [x] Any necessary additions or revisions have been made
- [x] Close ticket

**Comment by Justin-Pickett** [comment]
Closing Ticket

**Comment by lkoenigsberg** [comment]
Sharing feedback, hoping that many of these things can be incorporated, and completed, in sprint 10.

(1) As the requestor, would have been nice to have gotten a chance to review and give feedback w/out asking :wink:
(2) I'd like a column added that indicates what the VA.gov experience/outcome is given that error
(3) Be clear in the business case column.  Is that the VA Profile (formerly Vet360) business case or VA.gov business case?
(4) Same thing with the error key and text returned.  Be clear if that text is what's returned in a VA Profile API or shown to a user on VA.gov
(5) Not 100% sure on the addresses column since, over time, those addresses might not be valid examples.  Open to thoughts though.
(6) Consider how this matrix might help #1129 get broken down and moved along

**Comment by Justin-Pickett** [comment]
Closing this ticket. Will open a new ticket to incorporate the above suggestions to be tracked during Sprint 10.
