### ISSUE TITLE
[VAMC] Update the Knowledge Base - review "How to" Guide, changes for System health and facility health service KB articles [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31177]
## Story
As a web maintainer/CMS editor, I need to have a knowledge base of "How to" instructions, so I can find answers to my question of how to manage, maintain, and update my system website pages.

## Goal
- Improve the editorial experience for the web maintainer to find their own answers and "How to" instructions.

## Task
Review rewrite of KB articles for System health service and facility health service "How To":
- [ ] Review all Health service Knowledge base articles
- [ ] Pull guides/articles to word document and update article to better fit step by step
- [ ] How to add new VAMC Facility health services
- [ ] How to edit existing VAMC facility health services
- [ ] How to remove an existing VAMC facility health services

## Acceptance Criteria
- [ ] Provide Artifact ( word document) to content team for full cross check. 
- [ ] Any additional editorial recommendations for questions or directions to the editorial experience.
