### ISSUE TITLE
AFS CT Redesign: Redefine Compare Interaction - 1 of 2 Stories

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#31171]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
[Uploading... GIBill-recommendations-2pdf.pdf]Enhance Compare interaction just as medicare.gov does.

Redefine the Compare interaction to be more like medicare.gov. To see this, follow these steps: 

1. Go to https://www.medicare.gov/care-compare/
2. Scroll down and click Hospitals 
(Start here for mimicking of compare functionality)
3. In the Search field, enter a valid search term (in this case Street, ZIP code, city, or state) and click on the correct choice, when prompted
4. Click **Search**

**Then, On the Search results page:**
6. Click **Compare** on any option
7. Validate a blue banner with the selected choice is presented above the list of options / map and remains in place until user is ready to compare the selections.
8. Select two more options - validate each option appears on the blue results banner above

The idea is to mimic the same functionality for GIBCT.
---
## Tasks
_What work is necessary for this story to be completed?_
- [ ] Create Design / Wireframe and share with OCTO for review and approval
- [ ] Remove the "sliding drawer" on the bottom that displays the compare selections
- [ ] Add blue banner on top that displays the compare selections

## Acceptance Criteria
_What will be created or happen as a result of this story?_
- [ ] The drawer at the bottom of the window that slides open/closed is gone
- [ ] When the user selects one or more institutions to compare, the blue banner that shows the compare selections appears  and sticks (does not slide up/down) at the top of the window.
- [ ] When user has selected 3 institutions, the other Compare checkboxes are grayed out
- [ ] Once 3 selections have been made, and then one is removed from the banner, all disabled (grayed-out) checkboxes are re-enabled

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mrblanco1** [comment]
Per EDU - Joe Preisser, this item will remain in the Icebox until further notice. 3/17/2022

**Comment by mrblanco1** [comment]
This work will not be started. AFS HCD submitted recommendation to VA EDU. They will decide how they want to proceed.
