### ISSUE TITLE
[FE] Adjust the UI for cancelled Appointments

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31188]
## User Story
As a Veteran, if I click the pre-check-in or check-in link for an appointment that has been cancelled, I would like to see a message telling me my appointment has been cancelled so that I will know.

## Wireframes
[Wireframes are in this ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/40179)

## Related Documentation
Slack [thread](https://dsva.slack.com/archives/C02U11L00TF/p1650033080189729?thread_ts=1650032406.950339&cid=C02U11L00TF)

## User flow
- When I
    - Click a pre-check-in link for an appointment that has been cancelled
    - Login
- Then I
    - See a message telling me that my appointment was cancelled along with the appointment information

## Tasks
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
This is blocked due to unknown details from downstream systems

**Comment by mdewey** [comment]
**Problem:** 

Currently, these are the only eligibility statuses that are known to the vets-website 

```const ELIGIBILITY = Object.freeze({
  ELIGIBLE: 'ELIGIBLE',
  INELIGIBLE_BAD_STATUS: 'INELIGIBLE_BAD_STATUS',
  INELIGIBLE_TOO_EARLY: 'INELIGIBLE_TOO_EARLY',
  INELIGIBLE_TOO_LATE: 'INELIGIBLE_TOO_LATE',
  INELIGIBLE_UNSUPPORTED_LOCATION: 'INELIGIBLE_UNSUPPORTED_LOCATION',
  INELIGIBLE_UNKNOWN_REASON: 'INELIGIBLE_UNKNOWN_REASON',
  INELIGIBLE_ALREADY_CHECKED_IN: 'INELIGIBLE_ALREADY_CHECKED_IN',
});
```

In the UI there is a card for a canceled appointment. 

**Reason it blocked:** 

CHIP/LoROTA is not supplying a status for a canceled appointment 

**To unblock** 

Decided on what the eligible status will be passed when an appointment is canceled.

**Comment by mdewey** [comment]
cc: @jparker0425 & @julieadair1

**Comment by julieadair1** [comment]
@jparker0425 we should bring this up at our next meeting with the CHIP team so we can get it unblocked.

**Comment by mdewey** [comment]
Questions to answer 

- Are we getting canceled appointments from CHIP (answer from CHIP) 
- If we are, what is the eligibility status for an appointment when an appointment is canceled. (answer from CHIP)
- If we are getting the canceled appointment what should the display look like? (answered from UX) 

cc: @julieadair1 @acrollet @kristenmcconnell @jparker0425

**Comment by kristenmcconnell** [comment]
Slack conversation on what is [the user value to displaying canceled appointments](https://dsva.slack.com/archives/C02GXKL8WM6/p1644598333804489).

**Comment by kristenmcconnell** [comment]
Added #36855 for UX to look into this more and marked it as a dependency.

**Comment by brdunfield** [comment]
@zach-park ready for UX validation!
Telephone appointment:
![Screen Shot 2022-07-06 at 1 17 02 PM](https://user-images.githubusercontent.com/5032149/177874355-24ab0d88-c230-455f-8a71-5547b43e9f57.png)

In-person appointment:
![Screen Shot 2022-07-06 at 1 17 57 PM](https://user-images.githubusercontent.com/5032149/177874544-e9b1ed4a-06f8-4cef-96b9-342820861eb7.png)

**Comment by benbrasso-agile6** [comment]
Yeah, I’m fairly certain that CHIP/VeText catches this before the check-in app for check-in.

**Comment by loripusey** [comment]
Yes, this was just supposed to be for pre-check-in. Hopefully they get notified when an appointment has been cancelled and they don't show up at the facility and attempt to check-in.  I think we were just trying to make sure they knew not to come to the facility because the appointment has been cancelled.

Work looks GTM
