### ISSUE TITLE
[Claim Status Tool] Additional Evidence - Keep file upload on the files tab

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3118]
## User Story
As a Veteran, I want to upload my Additional Evidence files to existing claims found in the Claim Status Tool's file tab so that I am not left feeling confused about where they should be added. 

## Goal

To keep the UI consistent for the additional evidence screen by keeping it on the files tab in the claim status tool - claim detail view.

## Tasks
- [ ] Understand the tech implementations of moving the upload file functionality into the file tab area
- [ ] Create designs for intended solution
- [ ] Work with PM to create necessary tickets for the work to be completed

## Acceptance Criteria
- [ ] The designs for additional evidence upload on the file tab have been created

**Comment by kevinstachura** [comment]
@kevinstachura add screenshot

**Comment by YanaRoy** [comment]
@YanaRoy to work with @kevinstachura to update ticket

**Comment by ndsprinkle** [comment]
Follow-up ticket to handle double messaging: #5603
