### ISSUE TITLE
SD - R&S CMS Meeting / Exploration

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#31203]
## Issue Description
_Resources and Support information gathering with CMS team_

---
## Tasks
- [ ] _Discuss product vision, current state, pain points and wish list_
- [ ] _Document Notes / Action items for potential tickets_
- [ ] _Document findings on product line for future reference_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
**10/12/21 meeting with Kevin Walsh and Mikki**

-   Fall 2019 – design studio for R&S was called Learning Center
    
-   Mural had original design/content spec from Jenn/Ryan
    
-   A lot of rules around what should be on page
    
-   R&S was replacement for IRIS
    
-   A lot of pivots
    
-   Editors from business team would eventually enter content but hasn’t really happened
    
-   CMS never worked on making it work for business teams
    
-   Tech debt, hasn’t been prioritized
    
-   Blockers for Q4: zero time for R&S (small items might be possible)
    
-   Big picture: a lot of content that could be on R&S is on benefits and vice versa 
    
-   R&S doesn’t have a strong content model
    
-   Benefits hubs may be up for a redesign soon
    
-   CMS work to improve for Content team may be small enough for Q4, larger work = Q1
    
-   Benefits hub and R&S content types
    
-   [https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8](https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8)
![Screen Shot 2021-10-12 at 2.18.02 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/c8bf0606-4e00-4b23-9900-a22c64014396)
-   Tier 3: content that is not for veterans
    
-   How can we get content types to be more reusable, this is a long term goal
    
-   Q&A: long term goal to make it more reusable
    
-   Tags: longer term work that Mikki wants to work on
    
-   Homepage is one-off content type
    
-   Required field removal is easy to remove
    
-   CMS – currently, if you can edit, you can publish
    
-   Opening it up to all teams might create another IRIS
