### ISSUE TITLE
[Discovery] 404 page content, accessibility and design 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31208]
## Discription
_In recent reviews of the VA.gov 404 page it was identified that a potential full spectrum rework of content, accessibility and design in order to improve the Veteran experience when VA systems go down and Veterans still require assistance and answers to their questions and problems._

[Slack Tread](https://dsva.slack.com/archives/C52CL1PKQ/p1633618769159100)

### Discover Tasks
- [x] Migrate into Drupal (@swirtSJW to list out some COAs) 
- [ ] Incorporate new search drop down component (Search team)
- [ ] Discovery and how this might fit into our Road map going forward.

**Comment by swirtSJW** [comment]
https://prod.cms.va.gov/centralized-content/404-page-content    

content type: centralized_content
entity id: 36576

It works similar to Benefits detail page (page) content type.   All the available content is in "paragraphs"/components in  "field_content_block"  Do not user values from any other fields like title, those are administrative and not meant for published content.

I put in a react widget component, but did not populate it fully yet as we don't have the component.

**Comment by FranECross** [comment]
@swirtSJW Hi, Steve! Hitting the 'wayback machine' here to delve into your memory. You have a couple of comments on this old epic, and I'm wondering if the epic is even needed anymore? Was the work perhaps tracked/done elsewhere, or maybe the epic is obsolete? No rush, but I'm trying to cleanup the backlog to see what's still relevant/needs to be done and what isn't. TIA!

**Comment by FranECross** [comment]
Closing old ticket as obsolete.
