### ISSUE TITLE
[FE] Create Mock API for Demographics

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31213]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Add the demographics structure supplied by the CHIP team to the API calls for `v2`.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Using the phase-4 mocks, add the demographics data to the mocks
- [ ] Add some demographics generator functions to aid with testing 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Deployed to staging.
- [ ] merged into master
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
API docs from LoROTA, https://github.com/department-of-veterans-affairs/chip
