### ISSUE TITLE
[FE] Create the HTML for the Demographics Page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31220]
## User Story

As a veteran, I should be able to see my demographics, so that I can confirm it. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the semantic and accessible markup and style the demographics page to match the UI. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Cret the HTML and CSS for the demographics page. 
- [x] Update the url be `contact-information`
- [x] Create unit tests
- [x] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by ytsaoca** [comment]
Please check the UI updates that were highlighted with a green block, including content changes and empty status of the data point.![Contact information.jpg](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/80a5cb25-7632-49fb-add3-328027bdd30c)
![See staff.jpg](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/44cac264-c565-473d-9c97-bc93f736df4b)

Thanks

**Comment by ytsaoca** [comment]
@brianseek Looks good. Just a small thing. Do we want to present empty status of any demographics fields? If not, that's fine. 'cc @kristenmcconnell

**Comment by brianseek** [comment]
@ytsaoca here is the empty status:
![Screen Shot 2021-10-14 at 3.16.52 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/0245ef6f-7fa8-4080-b6a5-09e0b7436873)
Also thanks for mentioning the talk-to-staff page because I missed the text updates there. I just updated it and here is the screenshot:
![Screen Shot 2021-10-14 at 3.11.34 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d5621d24-8163-414c-9c40-5672869fadfc)
