### ISSUE TITLE
[FE] Spike Out Pre-Registration

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31221]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Start figuring out what needs done for the pre-reg. 
- Next of Kin
- Demographics page
- Do we need a FE story for mockups for Next of Kin page?

Engineering Qs & notes (these might need to go in a separate ticket.)

- Pre-check-in is similar to the application we're building- it displays demographics, next of kin, etc. Is it a separate application, or the same application? 
- Should we reuse health questionnaires for this?
- Thinking of the long term goal: is it dynamic forms and ability to plug forms into a workflow? What is MVP? Is it hard coding VA form system, or hard coding the forms that we know are needed for pre-check-in? (Can we focus on MVP now?)
- Need to better understand the engineering flow of pre-check-in with architecture diagrams etc. 
- Do we have the option to tell CHIP what the user selects in pre-check-in? If this data is being stored, we need to know that and could potentially call those endpoints.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Find and answer questions about the next phase
- [ ] Update relevant documentation
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Create documentation defining Pre-Registration including diagrams
- [ ] Create any subsequent tickets for work to be done
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
