### ISSUE TITLE
Design intent - Profile - Profile Personal Information Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31237]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/preferred-name-pronouns-gender-sexual-orientation/README.md)

 
- [X] Whiteboard sketch or other lo-fi prototypes or wireframes
   - https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565
- [ ] User flow
- [ ] Any other artifacts you have so far

### Required
- Product Manager: Marci McGuire
- OCTO-DE Product lead: Samara Strauss
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Kevin Hoffman (created mockups)

## Scheduling

**10/15/2021** **2:00 PM**

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Design Intent has been scheduled for 10/11 at 3:30pm ET

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman @allison0034 - I'm updating this to change the requested time to 2:00 next Friday 10/15.  Totally slipped my mind that Monday is Federal Holiday and everyone won't be here.

**Comment by allison0034** [comment]
@MarciMcGuireGCIO thank you. @shiragoodman is OoO today but will update the invite when she is back on Monday. I will post this in the Slack channel for awareness.

**Comment by MarciMcGuireGCIO** [comment]
@KevinMHoffmanUSDS ^ for visibility

**Comment by shiragoodman** [comment]
Design Intent has been moved to Friday 10/15 at 2:00pm ET

**Comment by Samara-Strauss** [comment]
> Edit buttons should reflect style that is currently in Production

Specifically, this is for the contact information page. I want to make sure it's clear that @zacharymorel only needs to create a new page, but he doesn't need to make any other changes to the contact information section.

> Mock up the default unanswered state, including any language such as "Please enter a selection by clicking the Edit button"

Yep! Liz should have some mockups that show how we do this for contact info.

> (My own note) - make it clear that selecting "Other" makes the text field a required field

Yep! This design pattern should exist within the design system, but if needed, Liz can point to examples in the profile.

> Think about recruitment strategy given that this will be LGTBQ+. We will talk with people both within and outside that community for usability testing.

No need to make this a ticket. We can keep this in mind for when we have a designer to do the research.

> If the 25 character limit is a reality due to database constraints, we need to check with content specialists on the language we will provide around that. Edit - here is an example: https://dsva.slack.com/archives/C909ZG2BB/p1633634838024700

Also no need to make a ticket on this one for now. We won't know real character limits until we talk to VA Profile and have better definition on the backend. Perhaps what we need a ticket on, actually, is to ask VA Profile about this later on when we're ready to start working with them.

> We may end up needing to provide some context as to what the VA will do with the information, particularly sexual orientation.

Let's create a ticket to talk about this with Danielle/content.

> We need to look at the current pattern and make sure the behavior matches what happens when you select one item to edit (i.e., do they all become editable, or just the one you've clicked?)

Only one item at a time becomes editable if you click an Edit button. I forget exactly what happens if you have one field open to edit and click an edit button for a different field, so please double check on that. I think the UI tells you you are editing another item and asks if you want to continue or not.

> Preferred name does not affect the MPI-derived name that is show in the nametag at the top of the page.

No immediate action on this for now, but @MarciMcGuireGCIO will you create a post-launch ticket for the backlog to revisit how we want to handle Name and Preferred name in the "nametag" element of the profile/dashboard?

---

These notes are great. Feel free to create tickets for anything that is actionable unless I've mentioned that something doesn't need a ticket. Thank you!!

**Comment by andaleliz** [comment]
There isn't anything documented, unfortunately - most of the discussion has happened during design critiques/reviews between me, Josh, and Angela. I hate to say this, but I tend to stop the convos around it fairly quickly since our meetings are usually focused on something _other_ than that and I want to stay on task so I can accomplish the goals of the meetings. I know it's a big lift to make this change in profile and not something to be casually considered.
