### ISSUE TITLE
[COLLAB CHECKLIST] Auth Profile: Personal Information Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31233]
# Collab Cycle Checklist - Personal Information Revision

## List your team, project contributors, and reviewers
<details>

_Record key players so you can quickly copy/paste into requests and your product documentation as your project progresses_

### Product Team
OCTO-DE Product Lead: Samara Strauss
Product Manager: Marci McGuire
FE Engineer: Zach Morel
BE Engineer: TBD
Designer: Kevin Hoffman - initiated, Christina Gednalske
Researcher: Christina Gednalske
Slack channel: #vsa
GitHub tags: `vsa-authenticated-exp` `profile`

### VFS participants (when applicable):
Design Lead: Ryan Thurwell
Design
Accessibility: Josh Kim, Angela Fowler
Analytics:
IA:
Content: Mikki Northius
QA: Tze-chiu Lei
Privacy & Security: 

</details>

## List project artifacts for requests

<details>

_Link applicable artifacts here so you can quickly copy/paste into requests as your project progresses.  Note that all artifacts may not be needed, depending on nature of the work_
- Project epic #31180
- Product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)) or initiative brief ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/product/initiative-brief-template.md#overview))
- Whiteboard sketch or other lo-fi prototypes or wireframes
- User flows
- Research plan | [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- Conversation guide | **[template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)**
- North Star and KPIs for the product | [How to set](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md)
- Authenticated test-user logins, when applicable. **_Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository_**
- Product URL(s)
- Use cases
- Finalized design prototype or mockup
- Content brief
- Regression test plans
- TestRail test cases/test plans
- Technical diagrams (architecture diagram, sequence diagram)
- Any new publicly-exposed endpoints
- Any new interactions with dependent VA backends
- Release plan
- Product guide for contact center

</details>

## Pre-Launch touchpoints linked to VSP reference info + practice areas involved at each step

<details>

- [x] Collaboration Cycle Kickoff | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D) | [#31098]
- [x]  Design Intent  | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) | [request template](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31577) [#31098] | _Note: PM must invite own team members._

  - Content [Sitewide Content and IA intake request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) [#issuenum]
  - Design
  - OCTO
  - IA  [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) | [#issuenum]
- [ ] Research Plan Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) |  [#issuenum]
  - OCTO
- [ ] Analytics Request | [Overview](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html) | [Analytics playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - OCTO
- [ ] Midpoint Review [Overview ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)| [Midpoint Review request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D) [#issuenum]
  - Accessibility | [How to test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md) |  [#issuenum]
  - Content
  - Design
  - OCTO
  - IA
  - QA
- [ ] Staging Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - Accessibility [Prep Info](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) | [WGAG 2.1 foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Slide-decks:-WCAG-2.1-new-success-criteria-and-testing.1777893393.html) [#issuenum]
  - Content
  - Design
  - OCTO
  - IA
  - QA
- [ ] Privacy and Security Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) |  [#issuenum]
- [ ] Contact Center Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) [#issuenum]
    - Contact Center
 
</details>

## Post-Launch Tasks

<details>

- [ ]  Update [Launch Tracker on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/vsa_launch_tracker.md)
- [ ]  Post @here announcement in your Slack channel after launch
- [ ] Full accessibility and 508 office audit | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=noahgelman%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
   - Accessibility
- [ ] Post-Launch Check-in | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html) |  [#issuenum]
  - Product

</details>

## Other Resources

<details>

- Product Development Checklist https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md

</details>
