### ISSUE TITLE
[FE] Timestamp issue on Appointment Page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31247]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1633701827205900)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

for the time correct time to check-in, CHIP is sending the timezone as well as the date-time already formated. We need to decide the correct course of action for fixing this and then implementing the fix. 

The fix should keep in mind that we are expanding timezones in the near future. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Determine the correct fix for going forward. 
- [ ] implement the fix
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
