### ISSUE TITLE
Changes to improve "Use my location" screen reader experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31259]
## Issue Description
As a Veteran who uses assistive technology, I use my search engine either by dictating or typing in my search parameter to look for a place that I need to visit physically.

Current experience: During research sessions, some users had trouble with location input. Users may have expectations about the location of the label relative to the field. The ‘Use my location’ input may interrupt the expected flow for users. 

In #27448, we worked with the accessibility team to identify opportunities to improve the experience. 

## Tasks

- [ ] Maintain current experience for tab order of "Use my location" button 
- [ ] Align "Use my location" button screen reader text with the input field 
- [ ] Group relevant elements for screen reader context (Consider using <fieldset> and <legend> (Josh referenced this conversation with @mpelzsherman) to group relevant elements for the screen reader.)
- [ ] Adjust screen reader announcement to read "Use my location - city, state, or postal code"  grouped with label 

---
## Acceptance Criteria
- [ ] Current tab order appears ahead of input field
- [ ] "Use my location" button screen reader text is aligned with the input field 
- [ ] Relevant elements are grouped for the screen reader.
- [ ] Screen reader announces "Use my location - city, state, or postal code"  with label

**Comment by laflannery** [comment]
This will all be addressed with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12883 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12882
