### ISSUE TITLE
Feature Request Process: Document instructions for submitting feature requests

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#31266]
## Issue Description
As a VFS team member or Platform stakeholder, I want to be able submit feature requests to the Platform.

User guide: https://vfs.atlassian.net/wiki/spaces/SDT/pages/1938915400/Submitting+a+feature+request

---
## Tasks
- [x] Document customer-facing instructions for submitting feature requests.  
- [x] Get guidance from Content & IA on style
- [x] Test links in doc work for VFS team members
- [x] Publish instructions in the Platform Website.

## Acceptance Criteria
- [x] Users can find instructions for submitting feature requests on the Platform Website and successfully use them to submit feature requests for the Platform to review.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
All documentation is updated in confluence page of Service design team
