### ISSUE TITLE
[Access Requests] Create issue template for AWS requests

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#31272]
## Description
Create a GitHub issue template that allows users to request access to AWS. 

## Background 
- Environment access request template [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/Environment-Access-Request-Template.yml)

## Technical information 
- It would be good to notify the infrastructure team and AWS approvers automatically, if possible 

---
## Tasks
- [x] Create a new issue template so that users can request access to AWS
- [x] Create a new issue template so that users can request access to AWS 
- [x] Update documentation (can work together w/ PM) 
  * https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Toolsoverview
  * https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#When-to-Grant-Access
- [x] Communicate changes w/ VFS and other platform teams 
- [x] Delete the existing Environment Access Request issue template
- [x] Make changes to https://github.com/department-of-veterans-affairs/vtk

## Acceptance Criteria 
- [x] There are separate request templates for AWS & SOCKS 
- [x] Internal-facing Documentation of new process exists in Confluence
- [x] User-facing Documentation of new process exists on the Platform Website 
- [x] `vtk` is updated with correct links

**Comment by jhouse-solvd** [comment]
Assigning to Rebecca. 

@rmtolmach - We probably want this to be one task in a wider epic. Feel free to get started on creating the template. I'll help move tasks into a connected epic so that we can divide and conquer. :)

**Comment by rmtolmach** [comment]
I ended up creating two new documents. An AWS access request and a SOCKS access request. This way, we can merge them without disrupting the original SOCKS/AWS request flow. Once all of the documentation is updated, we 

PR creating new yml files: https://github.com/department-of-veterans-affairs/va.gov-team/pull/38713
PR editing the SOCKS workflow: https://github.com/department-of-veterans-affairs/devops/pull/10932

**Comment by rmtolmach** [comment]
I added a couple more tasks that I thought about as I've been working through this.
1. Update the link to the access request in the `vtk` repo. https://github.com/department-of-veterans-affairs/vtk/blob/master/lib/vtk/commands/socks/setup.rb#L120
2. Make sure the Slack integrations still work so we get notified in the appropriate channels when an AWS or SOCKS request is opened.

I am currently editing the Platform docs here: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2129788946/RT-Request+access+to+tools. I will have someone review those changes before copying them to the _real_ Confluence page.

**Comment by rmtolmach** [comment]
Do I need to update the old docs? https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md

**Comment by rmtolmach** [comment]
Answering my own questions based on team feedback 😃 

> Do I need to update the old docs? 

No. I ended up deleting the content in this page (but I left the link to our new docs).

> I'm assuming I don't need to update the old-old docs 🤞 🤞 

No. If you've gotten to the old-old docs about doing this all manually, you have already most likely already seen the new docs and you are choosing to go into the weeds.

**Comment by rmtolmach** [comment]
Pages for the Platform website are updated and will go live on Tuesday.
https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools
https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Internal+tools+access+via+SOCKS+proxy

**Comment by rmtolmach** [comment]
Issue to address Jesse's ask
> It would be good to notify the infrastructure team and AWS approvers automatically, if possible 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/39182

To validate and close this issue:
1. Check that the Platform website is updated with new information about separate AWS and SOCKS requests: https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html
2. Check that the new AWS and SOCKS requests exist and the old Environment Access Request is deleted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose
3. Verify that a SOCKS action works: https://github.com/department-of-veterans-affairs/devops/actions/workflows/socks-access.yml

**Comment by jbritt1** [comment]
Reviewed and validated. This can be closed in my opinion.
