### ISSUE TITLE
Implement KMS for Lockbox

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#31273]
## Issue Description
After discovery, AWS KMS for secure key management combined with Lockbox was proven to be practical from a security perspective. Some configuration and data migration changes will be needed as the current implementation utilizes the Lockbox master key stored in AWS parameter store. Current records encrypted via the Lockbox key will need to be rotated/re-encrypted with the new kms_key. The documentation for kms_encrypted can be found [here](https://github.com/ankane/kms_encrypted). We will need to also utilize the Lockbox rotation documentation to migrate encrypted records from the Lockbox master key to KMS. 

---
## Tasks
- [ ] Generate a new AWS generated encryption key
      - [ ] Collaborate with Ops as needed for necessary permissions/policies
      - [ ] Set tag (can be used for cost analysis purposes)
      - [ ] Define an alias
- [ ] Define the alias as an ENV var in devops repo (prob need Ops assistance/expertise here)
- [ ] Define kms key in vets-api code
- [ ] Define previous keys for rotation purposes
- [ ] Remove notion of master key (no longer needed)
- [ ] Rotate existing records
- [ ] Set up automatic key rotation
- [ ] Update VSP and VFS facing documentation related to Lockbox and rotation

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
While on the "Rotate existing records" step, I ran into an `invalid byte sequence in UTF-8 (ArgumentError)`. It appears that the attributes are UTF-8 encoded, but have some random extra characters. I have a hunch that this may be due to the Lockbox padding that we have in the initializer and it's not very friendly when re-encrypting via kms. We may need to un-pad the existing records as a first step before we are able to re-encrypt with the KMS key.

**Comment by LindseySaari** [comment]
I created an issue in the gem [here](https://github.com/ankane/kms_encrypted/issues/39). It appears that I could do a monkey patch (or I could be totally missing something also) but I'd like to hear back from the gem maintainer first.

**Comment by LindseySaari** [comment]
Breaking up this criteria to separate tickets since this ticket started to grow too large

- [ ] Rotate existing records
- [ ] Set up automatic key rotation
- [ ] Remove previous_key from the models?
- [ ] Create a job that will run on a yearly basis to rotate records
- [ ] Look into automatic cleanup of old KMS keys
- [ ] Look into how/if old KMS keys can decrypt records during rotation
- [ ] Update VSP and VFS facing documentation related to Lockbox and rotation
- [ ] Remove Slack reminder for manual key rotation
