### ISSUE TITLE
[Tech-Debt] Update current Policies page with New Hardened Policies Page for all remaining Systems and publish [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31274]
## User Story
As a VHA Digital Media web manager, nationalized content should be isolated, so I can focus on local and regional policies and issues.

## Goal
Remove tech-debt for all new hardened policies pages.

## Resources - Tools - Documentation
TBD

## Tasks
Update all remaining systems that still have old policies page with new hardened content page. 
- [X] Copy old data from policy page
- [X] Delete any instance of a "Policies-0" URL
- [X] Create new content page (Content>add content>VAMC Policies page)
- [X] Save new hardened page with content copied from old and it should "Replace" old in list
- [X] Confirm "Policies-REPLACED" is either draft or Archive status

## Acceptance Criteria
- [x] All Policies pages have been updated to hardened page and published.
- [x] Old pages now state Policies - REPLACED
