### ISSUE TITLE
Publish Medallia How-To Documentation on Platform Website

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#31283]
## Issue Description
_This story is to curate existing "how-to" information and documentation for Medallia and publish on the Platform Website_

---
## Tasks
- [x] _Review and edit existing Medallia "how-to" documentation to bring current and make comprehensive_
- [x] _Work with the content team to publish Medallia "how-to" documentation on the Platform Website_

## Acceptance Criteria
- [x] _Current Medallia "how-to" documentation is published on the Platform Website_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
Documentation has been provided and this is in the hands of the Platform Website team now. Will update once publishing is complete.

**Comment by jwoodman5** [comment]
Published [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Platform-data-sources.1797881953.html).
