### ISSUE TITLE
[Parameter Store] Transmit and store keys for the My Education Benefits app (in non-prod environments)

### ISSUE THREAD

**Issue by cesaresantiago** [department-of-veterans-affairs/va.gov-team#31317]
## Description
The new My Education Benefits application will need to communicate with the Digital GI Bill (DGIB) services developed by AFS. These services are hosted outside va.gov and will use JWT tokens to grant access to the vets-api services that will be connecting to them.

We need to transmit the keys to operations via keybase. This ticket will be used to track this work.

Please let myself and @wonhchoi next steps to take.

---
## Tasks
- [ ] Make a path in parameter store
- [ ] Get the keys from them ie (Transmit keys via Keybase)
- [ ] Verify that vets-API can use the keys within it's running context

## Acceptance Criteria 
- [ ] The My Education Benefits API on vets-API must have access to the uploaded JWT keys to generate JWT tokens that will allow communication with the DGIB third-party services.

**Comment by jhouse-solvd** [comment]
@cesaresantiago / @wonhchoi - Please refer to #33162 for when you're ready to do this again in production. 

If at all possible, please let us know a couple of sprints in advance so that we can schedule appropriately. 

Thank you! 

Closing.
