### ISSUE TITLE
Discovery efforts for agility in the Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31315]
## Issue Description
Before implementing a solution to help improve agility in the Collaboration Cycle, we must first have a complete and thorough understanding of the current problems. We will be completing a "5 Whys" exercise to get to the root cause of each problem statement identified in the Initiative Outline. After completion of the "5 Whys" we will prioritize the identified problems. For the top priority problems, we will complete a rapid ideation/rapid prototyping session. The team will vote on which solutions to move forward with in order to make Collaboration Cycle more agile. 

---
## Tasks
- [x] Create MURAL board for 5 Whys workshop
- [x] Schedule 5 Whys workshop and include the following:
- Shira
- Allison
- Peggy
- Peter
- Dariusz
- Noah
- Jim
- Sean
- Olga
- Rachael (optional)
- Andrea (optional)
- Naomi (optional)
- Josh (optional)
- Angela (optional)
 

## Acceptance Criteria
- [x] Team has completed 5 Whys workshop
- [x]  Team has completed a rapid ideation session
- [x]  Team has completed a rapid prototyping session
- [x]  Potential solutions have been validated for scalability and LOE
- [x]  Potential solutions address identified pain points
- [ ] OCTO-DE has approved the proposed solutions 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
[Which ideas address which problems](https://docs.google.com/spreadsheets/d/1ywqcdqQTovePPfEU0mW7wUSxH6F8aWzMhpAvk9GeucA/edit#gid=0) google spreadsheet

**Comment by shiragoodman** [comment]
Recording of rapid prototyping presentation:
https://us06web.zoom.us/rec/share/KSp-I5ya6r06BqbtD4vVC1RGz3lRRMbrTfnOra1QRikiW47OLWxWn562LXnm-P7t.o-499IzVyShFv8o8 
Passcode: p*V4GR4m

**Comment by shiragoodman** [comment]
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1636391901221/b358593b25f6c24460de5cd1187db75acb5bf9e0?sender=u045df875f30f7e9f34339908
Mural boards for "tracking tool" prototype and "pivot process towards products" prototype

**Comment by shiragoodman** [comment]
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1636391689856/05bf7261755aa1b3f1342e87edb14cad6ca990da?sender=peterhill4315
Mural board for "sizing/scaling tool" prototype and "gold card membership" prototype

**Comment by shiragoodman** [comment]
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1636391868018/61137f908ab4d13ac20ef79d0d3f70f55f02d57e?sender=u0574179b1d97118ccc0e3591
Mural board for "custom user flow" prototype and "new products only process" prototype

**Comment by oapolina1** [comment]
@shiragoodman [Link to slide deck for readout](https://docs.google.com/presentation/d/1d_J4Sb_6kHSXxq-vNJwo3vob_-ComqItxZFqJAVzTNc/edit?usp=sharing)
