### ISSUE TITLE
[FE] Trigger Refresh on Appt List

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31319]
## User Story

> these should be why the veteran cares, and the veteran gets out of it.

As a veteran, I should be able to see my latest appointment information, so that I can have an update to list to take actions

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

We need to refresh the appointment list when a user revisits the page. 

**Problem:**  We are now using the demographics page, we need to ensure we are loading the latest appointment information when the appointment list is 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Figure out best ways to address this problem
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
