### ISSUE TITLE
Unmoderated Research Sign-in modal and provider attributes 

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#31325]
## Issue Description
_Unmoderated study conducted via Optimal Workshop with a card sort and first-click test_

---
## Tasks

- [ ] Track participant progress 

- [ ] Daily report of participant codes to Perigean

## Acceptance Criteria
- [ ] 90-180 participants or end of 2 weeks (whichever comes first)
