### ISSUE TITLE
[Cerner Integration] Technical discovery

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#31336]
---

## User Story

As a Veteran, I want to know what is connected to Cerner so that I can understand what is being used to appointment checkins. 

## Description

We need to research these platforms to determine if can we get the info in and out of Cerner that we need to do our job, focusing at first on appointment data.

We also want to answer this question:

How might we abstract the functionality likely to be useful to other apps?:

These might include:

- secure messaging
- pharmacy data

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Links to API documentation provided
- [ ] Available data/methods and how they relate to the data & methods we have available for VistA are documented
- [ ] Summary of findings has been surfaced to project leadership (Stephen)

**Comment by acrollet** [comment]
@stephenBarrs @jparker0425 here's a stub, please feel free to expand/update as you see fit!

**Comment by acrollet** [comment]
@jparker0425 @stephenBarrs I've placed this ticket in validate, the discovery documentation is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/Cerner/integration_discovery.md

**Comment by jparker0425** [comment]
@acrollet this item is complete based on the research and outcome of the Executive Summary. I will move to closed. Again, awesome work on this!
