### ISSUE TITLE
Hypertension Fast Tracker

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#31331]
## Issue Description
Implementation of fast tracker for pilot program

Anna did a quick demo branch for the Fast Tacker Team so they can see exactly where their code could interface with a 526 submission to fast track specific types of claims.  

The Hypertension team is going to take over this branch and implement their code in there or least use the info in the branch to start their work.

---
## Tasks
- [x] Develop and implement demo_POC code to allow for fast tracker routing of hypertension claims. Reference [code Anna started](https://dsva.slack.com/archives/C5AGLBNRK/p1632492523205500). 
- [x] Reach out to [Emily Theis](https://dsva.slack.com/archives/C5AGLBNRK/p1634066717339600) and her team for background and collaboration.  Slack Channel created: https://dsva.slack.com/archives/C01BVF2A3V0

## Acceptance Criteria
- [x] Hypertension team is aware of Anna's work and is going to use that to help them implement their code.
---

**Comment by michelpmcdonald** [comment]
Hypertension team is going to take over Anna's branch and perform the work.
