### ISSUE TITLE
Update link text in Ask VA react widget

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31332]
## Issue Description
Sitewide Content is changing the text for the link we are using in the new Ask VA react widget that is going on the Contact us page and we need a dev from PW to change it for us. We need to replace "Ask us a question online" to:

Contact us online through Ask VA

Background on this effort can be found in tickets #28848 and #30570. 

---
## Tasks
- [x] Update text in react widget
- [x] Notify Sitewide Content when change is made
## Acceptance Criteria
- [ ] React widget contains updated text

**Comment by srsuddath** [comment]
Here is the PR that should fix this issue for you all!
https://github.com/department-of-veterans-affairs/vets-website/pull/19091
