### ISSUE TITLE
Conduct 10/27 Working Group 

### ISSUE THREAD

**Issue by LSiopis** [department-of-veterans-affairs/va.gov-team#31348]
## Epic Description
The working group has been established on a monthly cadence to demo apartment-related development, give feedback, surface problems and ask for help. The first meeting is scheduled for Wed, Oct. 28, 2021. Stakeholders expect / demand us to try doing something like this for cross-collaboration. We will bring best practices in radical collaboration and test, learn, and iterate on our approach.

---
## Acceptance Criteria 
- [ ] Team and leadership know their roles for the working group.
- [ ] Working group conducted.
- [ ] Action items and issues captured.
