### ISSUE TITLE
Create component structure for "View Dependents" screen

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#3134]
## Story
As a front end engineer, I need to build out the basic, parent level components for the "View Dependents" screen so I can break these components out into child components with greater separation of concerns.

## Goal
This is meant to make progress on the "View Dependents" build

## Tasks
- [x] Creating folder structure and files
- [x] Stub out page that runs with basic component structure

## Acceptance Criteria
- [x] Parent level components for `View Dependents` screen are built on local machine
- [x] Parent level components are on in a PR to be merged into staging

**Comment by cohnjesse** [comment]
@sporeboy Can you attach the mockup for this?

**Comment by jason-gcio** [comment]
https://staging.va.gov/disability/view-dependents/
