### ISSUE TITLE
Remove veteran-representative app directory from vets-website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#31344]
## Description
[Veteran Representative](https://github.com/department-of-veterans-affairs/vets-website/blob/c4b97f33c7c18b93d4aaa915109f8cc23cdb045a/src/applications/veteran-representative/manifest.json#L1-L7) is a legacy application that isn't in production nor ever was in production. It's original functionality will be subsumed by the view/search/request rep application the vsa-ebenefits team is currently building. This legacy application should be removed from `vets-website` and from the registry.json entry in content-build.

## Tasks
- [x] Remove app directory from `vets-website`
- [x] Remove registry.json entry from content-build
- [ ] If a schema exists for it in `vets-json-schema`, remove that as well

## Acceptance criteria
- [ ] above tasks have been done and/or,
- [ ] PR(s) have been submitted and/or,
- [x] A path forward has been determined with accountable parties notified

**Comment by jason-gcio** [comment]
Per Jesse: Linting rule that says if there is a missing CSS file it fails the whole build.  Blocking ticket from platform is pending, will note when it becomes available.
