### ISSUE TITLE
Schedule interviews for standardized KPI dashboards research 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#31356]
## Issue Description

We need to schedule interviews for various VFS team members to get feedback on the standardized KPI dashboards and figure out how we want to iterate in the future. 

This is a continuation of the work from ticket #30737.  Documentation of user research sessions and synthesis of findings will occur in a future ticket.

---
## Tasks
- [x] Get sign off from Naomi on research plan (with attendees as part of the research plan)
- [x] Make any necessary changes (delete this item if not relevant)
- [x] Get approval from OCTODE on research plan
- [x] Schedule the interviews 
- [x] Create note taking template
- [x] Schedule the note takers

## Acceptance Criteria
- [x] All interviews are scheduled. 
---

**Comment by chloedotbrown** [comment]
No additional feedback was received from OCTODE on the research plan after demo presentation last Wednesday, so we are moving forward. I've set up a [note-taking template](https://docs.google.com/document/d/1hB4q2zMvwa_VHjb4u8FiEc82_AYz08f5qaReSMCVE0w/edit#heading=h.1aeoqc8oy8j0) and we'll start outreach to schedule tomorrow.

**Comment by chloedotbrown** [comment]
All five* interviews are scheduled and [note-takers](https://docs.google.com/document/d/1hB4q2zMvwa_VHjb4u8FiEc82_AYz08f5qaReSMCVE0w/edit#) have been assigned: 

| Date  | Participant | VFS Team | Dashboard(s) | Note-taker |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
| 11/12, 2pm ET | Michelle Middaugh | Facilities | Content | @pavanhothi  | 
| 11/12, 3pm ET | Brian Lloyd | Public Websites | Content, Search | @jonathan-epstein13 | 
| 11/15, 2pm ET | Ronnie Henry | Claims & Appeals | Forms | @pavanhothi | 
| 11/17, 12pm ET | Marci McGuire | Decision Tools _(formerly)_ | Forms, Search | @jonathan-epstein13 | 
| 11/17, 2:30pm ET | Sharon Kasimow | Content & Localization | Content |@pavanhothi | 

In addition, we have a Pilot Session scheduled for Wednesday, 11/10 4:15pm ET to give everyone a chance to go through the script / process as a dry run. @pavanhothi will be the user demoing the dashboard and @jonathan-epstein13 will take notes. 

_*Denise requested to be left out of this round of user research, given her recent team switch, though she's interested in being included in future rounds, should we do them in the future._
