### ISSUE TITLE
Build VA.gov-wide Dashboard mock-up

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#31359]
## Issue Description

Integrate the [suggested changes](https://vfs.atlassian.net/wiki/spaces/AT/pages/1910374485/All-VA+dashboard) to the initial mockup for VA-wide dashboard from Chris Johnston and Mickin. This ticket continues the work of gathering and synthesizing feedback completed in ticket [#30700](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30700). Work expected to continue into sprint 64.

---
## Tasks

- [x] Make copy of mockup that visualizes intended changes.
- [x] Document any data gaps discovered during build.
- [x] Share V2 mock-up with Chris J/Mickin and integrate feedback

## Acceptance Criteria
- [x] Dashboard mockup is built and ready to share with stakeholders for feedback.

**Comment by chloedotbrown** [comment]
**Spring 64 wrap-up:** Shared [v2 mockup](https://docs.google.com/presentation/d/1o3MHYr2Xpd4wXoXcY-c--wI6qoF1P34iXNzdQIhVJVk/edit?usp=sharing) with Chris and Mickin via Slack. Also, re: point above about user satisfaction data, we were able to connect with the Contact Center team and get access to their manually uploaded Medallia data. We should be able to include highest / lowest ratings in MVP.

**Sprint 65 plan:** We'll start building WIP version of dashboard in Domo aligned with latest mockup.

**Comment by chloedotbrown** [comment]
Have rescoped original ticket to capture Sprint 64 work. Actual build in Domo will be tracked in #32733 .
