### ISSUE TITLE
Public Websites: Sprint 59 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31364]
## Sprint 59 Priorities (VA.gov Mobile Header FE Build / CLP - VHA CLP-COED, CLP-Flu / Outreach & Events Design/Tech Discovery / Tech-debt & In-take Requests / Redirect Requests vetted by IA.  
1.  New VA.gov Mobile Header --> FE build for unauth/auth experience (mobile only), Work a release plan and analytics setup/review 5% production release COAs and VSP Midpoint review (11/5 Async).  
2. Campaign Landing Page --> VHA COED & Flu campaign launches (Support Launch Strategy - validate URLs / Analytics tracking / launch support as needed. 
3. Outreach & Events --> Review design discovery concepts --> work draft mockups / Technical Discovery / Scheduled VSP design intent (10/29 @ 2PM) / begin looking at research actions for User testing with Veterans.   
4. Redirect Requests (earliest) / InTake request -->  Redirects can promote to prod at earliest  opt. 
5. 'Tech-Debt' items as prioritized from backlog grooming --> Mission to clear out tech-debt and mitigate risk
6. HRT: Ensure work is documented in support of shelving actions. 

### Capacity Planning: PTO/Holiday's
Brian: 10/22
Kelson: 0
Trent: 0
Cassandra: 0
Cindy: 0
Dave: 0

### Harassment Reporting Tool (HRT) initiative **(Get Shelf Ready)**
- [ ] [EPIC] ORDMI Online Harassment Reporting Page & Tool MVP #24883
- [ ] HRT Clinician Recruitment #31850
- [ ] Documentation in support of shelving efforts for HRT initiative. 

### New VA.gov Mobile Header [FE Build Elements / Analytics]
Epics: New VA.gov Mobile Header #30623;  PW New VA.gov Mobile Header x Collab Cycle Plan #30625
- [x] [FE - Mobile header] Create Legacy header react widget #31145
- [ ] [FE - Mobile header] Create header V2 react widget #30875
- [x] [FE - Mobile header] Feature Toggle for Header V2 #30876
- [ ] GA Event Tracking Request from IA #31338
- [ ] Midpoint Review [Public Websites, New VA.gov Mobile Header] #31712
- [ ] Staging "Sandbox" environment for Ryan T. to fully review and provide feedback. 
**--> Next Step** - VSP Mid-point Review (Scheduled NOV 5, 2PM). 

### Outreach & Events [Backlog / Discovery] 
EPIC: Outreach & Events Hub - 2021 Enhancements #28918
Discovery/Design Ticket: 
- [x] [Discovery] Design Refactoring for Outreach & Events Hub (Filtering and Recurring Events) #30381
- [x] [Discovery] Technical Analysis for React Widget (Outreach & Events) #29765 **Waiting on Design**
- [ ] CMS to provide list of all events and urls in the system? Determine how many have been cloned [CMS Ticket Pending]
- [ ] [Collab Cycle] Design intent [Public Websites Team - Outreach & Events Enhancements] #31677 
- [ ] Research Discovery: Outreach & Events Initiative #31853

### Campaign Landing Page MVP 1.0
[EPIC] Campaign Landing Page 1.0 Features #25772
- [ ] [Campaign Landing Page Production Launch]- Annual Influenza Vaccination Campaign (VHA) #31510
- [ ] [Campaign Landing Page Production Launch]- Care Optimization in the Emergency Department #31537
- [x] Analytics KPI dashboard request for [Public Websites Team - Campaign Landing Page] #31519
- [ ] Analytics Tracking - Add these to Domo Dashboard for tracking/reporting **(Pending URL finalization)**
- [ ] URL verification and feedback _(Working in request tickets with Mikki)_
- [ ] Updates to User_Form based on feedback from VHA **(Ticket Pending)**
**--> Next Step** - Follow up with VHA on publication of CLP (Pending), work with analytics to add to DOMO dashboard for tracking. 

### Discovery Research 
- [x] Research: Compile VA.gov Home Page Wish List #31855
- [ ] Veteran Crisis Line (VCL) Analytics Research #31851

### Redirect Requests
- [x] Redirect Request for Vet Centers live as of 10/7- FL detail pages, legacy directory location and key staff pages #31222
- [x] Redirect Request for Vet Centers live as of 10/7- FL detail pages, legacy directory location and key staff pages #31553

### Intake Request - Techical Debt
- [x] Update "Ask a question online" on the right rail of the benefit hub landing pages. #31350
- [x] [508-defect-2, SCREENREADER] HTML should use meaningful landmarks #31556
- [x] FE bug: Pagination link should not show when there's only 1 page #18571
- [x] Debt Portal Alert from Debt Resolution Team #31817 **(HOLD - Debt Team will action this ticket directly)**

<details><summary>Collab Cycle Tracking Template</summary>

### 
# Collab Cycle Tasks
After copying this template into your new Sprint Priority issue, keep the Collab Cycle tasks needed for this sprint and delete the rest.
- [VSP Collaboration Cycle Image](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [VSP Collaboration Cycle Requirements/Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
- [Change Release Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/decision-tools/DRAFT_Change_Checklist.md)

## Define
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)

## Discover

- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
### [Submit Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### [Privacy and security review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- [ ] Submit ticket for review: Use Privacy and Security Review template in va.gov-team-sensitive repository 
- [ ] Provide artifacts at least 48 hours prior to the review
- [ ] Schedule/hold Privacy and Security Review
- [ ] Complete any tickets that came out of Privacy/Security review (if any)

### [Submit Analytics **QA** request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### Release Plan
- [ ] Create UAT plan
- [UAT Template](www.google.com)*
- [UAT Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-research-plan-UAT.md)
- [ ] Complete Release Plan 
- [Release Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)

#### QA
- QA Staging review scheduling: Have artifacts in and tag Tze 2 weeks in advance from the Staging Review. This makes it possible for Tze to get to it w/o being rushed. When you schedule the Staging review, also tag Tze in Slack.
- [ ] Create list of staging users
- [ ] Create list of use cases [see [Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)] and submit to Tze so he can create test cases/regression tests
- [ ] Create “Coverage for references report” OR a add a link to the Epic for the product you are releasing  

#### Accessibility
- [ ] Complete the [required accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Complete QA/Accessibility tickets that came out of Staging review prep (if any)

### Conduct Internal QA Session
It is beneficial to conduct an internal QA session prior to actual QA. This consists of the team allocating 1 hour to meet look for bugs and or issues with the product. This is beneficial because the engineers and designers have in-depth knowledge of potential problem areas that QA might not have the time/resources to look into.
- [ ] Internal QA has been conducted

#### List of issues coming out of internal QA session:
- [ ] Issue name #00000
- [ ] All issues that came from internal QA have been completed

### [Request Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Provide all required artifacts in the request
- [ ] Schedule/hold staging review
- [ ] Complete all IA feedback tickets
- [ ] Complete all Accessibility feedback tickets
- [ ] Complete all QA feedback tickets
- [ ] Complete all Content feedback tickets
- [ ] Complete all Design feedback tickets

### [Contact Center review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)
- [ ] Create Product guide
      - [Product Guide example]()
- [ ] Create Product video
- [ ] Submit request for Contact Center Review
- [ ] Complete Contact Center Review

### Analytics follow up on Staging
- [ ] Analytics are complete
- [ ] Frontend has implemented analytics data layer changes
- [ ] Dashboards have been created and link directly to your OKR/KPI's
- [ ] Review dashboard(s) with Analytics team to ensure understanding of all metrics/calculations
- [ ] Dashboards are finalized/work correctly

### Preparing/Updating all necessary supporting documentation for your product
- [ ] API calls and dependent systems [Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account#api-calls-and-dependent-systems)
- [ ] Update product outline with updated release information and links to analytics dashboards [Product Outline Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)

#### Ex:(re-directs, changes to content, changes that affect other teams) 
- [ ] Create issues in Github for changes that will take place, add dates, and tag relevant people/teams (re-directs, content changes, UI changes, etc)
- [ ] Update dates/parties accordingly as launch approaches and dates are finalized

### UAT
- [ ] Conduct UAT Go/No-Go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/uat-go-nogo.md)
- [ ] UAT has been conducted
- [ ] Issues have been logged/added to the Release Plan. [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)
- [ ] Launch-Critical UAT issues have been resolved

### Phased Launch (depends on phases in your launch)*
- [ ] Conduct Launch Go/No-Go meeting
-  [Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md)
- Invite your entire team, analytics, platform team members, etc
- [ ] Resolve any issues (if applicable)
- [ ] Continue with phased launch, resolving issues if they arise, monitoring analytics daily

#### Go-live to 100% of traffic
- [ ] Conduct Go-live go/no go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Launch%20go%20no-go.md)
- [ ] Resolve issues (if applicable)
- [ ] Launch to 100% of users

## Monitoring
- [ ] Monitor analytics daily to ensure there are no abnormalities/errors
- [ ] Resolve any issues (if applicable)

## Post Launch
- [ ] Fill in post-launch metrics in the Release Plan
- [ ] Remove old code (if applicable)

### [Full Accessibility and 508 Office Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#full-accessibility-and-508-office-audit)
- [ ] Request [Full 508/Accessibility Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)
- [ ] Complete required scans/tests
- [ ] Make required changes (if any)

### [Post Launch Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#post-launch-check-in)
- [ ] Update Release Plan with "post-launch questions" completed
- [ ] Schedule/Hold check-in
- [ ] Measure results against OKRs
- [ ] Prepare next steps and potential iterations if applicable

# Feedback from other teams

**Platform feedback:**
- The biggest blocker to a successful launch would be not implementing platform feedback earlier in the process. 
- It would be ideal to implement the feedback prior to the staging review. 
- More frequent communication of changes/issues via the slack channel would be beneficial.

**Accessibility feedback:**
- Include accessibility in design syncs, design-intent review, and anytime large changes are made.
- More frequent communication with Accessibility (ex: Biweekly accessibility meetings)
- For individual meeting/mini reviews use this [GH template](Enter link to template)
- Have an "Engineering intent review" and include accessibility (in addition to design intent review).

**PM Feedback:**
- Update Collaboration Tracker
- Add time estimates maybe
- how to roll this out
- put in epic format?

</details>

<details><summary>Kanban Board Template</summary>

### 
# Kanban Board
_Please select a ticket and include [WIP - [NAME]] next to the ticket that is being worked._  Pick up tickets by priority on the `To Do ` section to begin and move ticket through kanban workflow until `Done`. Please include resolution steps on tickets along with instructions if for some reason you are unable to complete the ticket during this sprint.  
Please tag <PM> on tickets when moved to **Done** section for validation and closeout.  Please connect if you have any questions or concerns in the interim.  Welcome to **VFS team** (for this sprint) we're excited to have the help.  

<details> 

<summary> TO DO </summary>

</details>

<details> 

<summary> ON-GOING </summary>

- [ ] [FE] <Discription> #174XX (WIP - Name)

</details>

<details> 

<summary> DONE </summary>

- [x] [FE]<Discription> #174XX (Validate - Name)

**Comment by brianalloyd** [comment]
Sprint is complete
