### ISSUE TITLE
OAuth Research - Phase 1

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#31380]
**Goal**
Improve the sign-in experience for Flagship mobile 

Phase 1 - Move away from AccessVA page and onto VA.gov sign-on
Phase 2 - Utilize new Oauth solution for ISAM non-sso solutions

**Acceptance Criteria**
- [ ] When a user clicks "Sign in" on the VA mobile app, they see our login page
- [ ] User must be at least IAL2 **or** LOA2 user in order to sign-in to the mobile app
- [ ] IAM should issue Oauth token to the mobile app
- [ ] If IAL1 or >LOA2, user must upgrade before being allowed to login

**Comment by nsoutouras** [comment]
Move middle 3 tickets (Merge, Merge, Use SSOe to Phase 2 Epic)

**Comment by nsoutouras** [comment]
Currently planning to start work on this 11/29.  Significant likelihood that work will continue into January due to slowdown in Nov/Dec and code freezes during those times as well.
