### ISSUE TITLE
NEWSLETTTER PIVOT 3/3: Recruit participants

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#31394]
# User story

As a Platform customer, I want to understand any Platform releases, so that I can build my VA.gov service.

As a Content team member, I want to schedule participants, so that I can execute the research in Spr 64.

# Tasks
- [x] Write recruiting message
- [x] Define participant criteria
- [x] Generate list of potential participants
- [x] Screen and recruit participants 

# Acceptance criteria
- The Content team has a list of 10-12 confirmed research participants that meet the recruitment criteria.

# Reference info
- Research plan: https://vfs.atlassian.net/wiki/spaces/CIT/pages/1927348228/Newsletter+pivot+-+research+plan#Participants-%26-recruiting

**Comment by jchasia-adhoc** [comment]
Closing as there are 12 confirmed research participants.
