### ISSUE TITLE
[FE] Profile: Update alert for when a user hits "cancel" while editing data

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31408]
## Background

9/28 - this ticket is incomplete; buttons for "continue editing" and "cancel" need to follow standards and have the primary button (continue editing) have the blue background)

Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user clicks the cancel button while editing data.

See also #31410 

This ticket is for [**Updates to alerts item 7**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#7-user-hits-cancel-button-while-editing-data-31408) in the supporting documentation.

## Tasks
- [x] Update the alert that appears when a user clicks the cancel button while editing data per the copy and specs below
- [ ] Update the primary and secondary buttons with correct background (dark blue for primary)
- [ ] 

### User hits cancel button while editing data ([#31408](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31408))

- **Impacted sections:** any editable section

- **What's changing**: button styles

- **Placement:** In modal component

- **Alert (pattern, state):** Full width, warning state

- **Include heading:** Yes

- **Button usage:**

  - First button contains the confirming action and has the primary button style
  - Second button (if applicable) contains the cancel action and has the secondary button style

- **Copy:**

  > [heading] Are you sure?
  >
  > [body] You haven't finished editing and saving the changes to your [data]. If you cancel now, we won't save your changes.
  >
  > [button] Continue editing 
  >
  > [button] Cancel

## Acceptance Criteria
- [ ] The alert that appears when a user clicks the cancel button while editing data is updated as indicated in the supporting [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#7-user-hits-cancel-button-while-editing-data-31408)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel can handle making this update

**Comment by andaleliz** [comment]
It might be worthwhile to go through all the tickets AJ created for this and see which were done and which weren't. They're all linked from [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md).

**Comment by Samara-Strauss** [comment]
Sounds good. Idk if any of them have been done; I don't remember. Did you intend to go through that doc, or are you asking Sharon to take a look?

**Comment by Samara-Strauss** [comment]
Yeah, I think it's unlikely any have been done. We intended to start them before the personal info work started in the fall, but then the tickets got deprioritized. I agree it's a good idea for Sharon to review this work. Is all the work still relevant? I am assuming there haven't been changes made since those tickets were created that would render them obsolete or in need of updating, but let me know if that is a safe assumption or not.

**Comment by andaleliz** [comment]
I think it's a safe assumption that they're still relevant. The recommendations were to improve consistency and accessibility/mobile UX.

**Comment by Samara-Strauss** [comment]
@SKasimow doesn't matter to me. If people Mark/Adam are light in the coming sprints, we can assign these then. But people can also pick them up if there is a lull in work.

**Comment by andaleliz** [comment]
@adamwhitlock1 and @SKasimow this still needs to be done; moved specs into this ticket instead of the documentation for clarity

**Comment by tmitchellgcio** [comment]
@MarciMcGuire this is ready for validation

**Comment by Samara-Strauss** [comment]
@tmitchellgcio -- @MarciMcGuire is no longer on the team. This should go to @SKasimow, @andaleliz, or @cgednalske for validation.

**Comment by andaleliz** [comment]
Hi, it looks like the buttons are still swapped. The buttons in the screenshot don't follow our normal pattern (described in the issue description).  Was this issue _just_ for copy updates? If so please feel free to close it again, but if not, we need to update the classes on the buttons too.

**Comment by SKasimow** [comment]
@andaleliz - intent was to update whatever was needed but think the change needed for the buttons wasn't clear.

@tmitchellgcio - is this something you'd be able to update? If not, I'll re-assign to Adam.

**Comment by SKasimow** [comment]
@adamwhitlock1 - assigning this ticket to you for an upcoming sprint. Initially it looked like we just needed to update the buttons:

>Button usage:

> First button contains the confirming action and has the primary button style
> Second button (if applicable) contains the cancel action and has the secondary button style

However I am now seeing a different message:
![Screen Shot 2022-09-09 at 7.11.15 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/9ee6059b-fc37-49ce-82ac-30219b161554)

**Comment by SKasimow** [comment]
But Mitchell recently worked on this ticket and at the time, I saw the update in staging:

![Screen Shot 2022-08-11 at 11 18 37 AM](https://user-images.githubusercontent.com/74627978/184169335-7c89b71c-aec5-4ef0-b465-0eafc0b7dbe5.png)

**Comment by andaleliz** [comment]
@SKasimow there are two different use cases represented in those screenshots.  The alert with one button is what a user sees if they are in edit mode for one section, and click the "edit" button for another section without saving
![Screen Shot 2022-09-09 at 7.11.15 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/9ee6059b-fc37-49ce-82ac-30219b161554)

The alert with two buttons is what a user sees if they have made changes while in edit mode, and click "cancel" instead of "update", which is the alert this ticket is about.

![Screen Shot 2022-08-11 at 11 18 37 AM](https://user-images.githubusercontent.com/74627978/184169335-7c89b71c-aec5-4ef0-b465-0eafc0b7dbe5.png)

**Comment by SKasimow** [comment]
Hi - this is from sprint 82 and I noticed it was still open. Is it on your radar or was it completed??

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - this is from sprint 82 and I noticed it was still open. Is it on your radar or was it completed?

**Comment by adamwhitlock1** [comment]
I am in the middle of this ticket. Can we assign it back to me? It also involves migrating the modal to the Web Component which broke a bunch of tests that I am working on updating.

Branch is open here
https://github.com/department-of-veterans-affairs/vets-website/tree/Profile/31408/update-editing-alert-button-styles

**Comment by Samara-Strauss** [comment]
Added you back as assignee and removed John.

**Comment by adamwhitlock1** [comment]
This can now be validated in staging @SKasimow. I just checked myself and saw updated button styles

![Screen Shot 2022-10-11 at 10.42.15 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/7cdd93e3-5958-4946-85cc-4258a8f71925)
