### ISSUE TITLE
[FE] Profile: Update alert for when a user is editing a section and attempts to edit another section without saving

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31410]
## Background
Per documentation outlined in [25820](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#profile-alert-improvements), we need to update the alert that appears when a user is editing a section and then attempts to edit a different section without saving in the first section.

See also #31408 

This ticket is for [**Updates to alerts item 8**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#8-user-is-editing-a-section-and-attempts-to-edit-another-section-without-saving-31410) in the supporting documentation.

## Tasks
- [x] Update the alert that appears when a user is editing a section and then attempts to edit a different section without saving in the first section per the mocks (specs below)
- [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/waVZjj/a/OmlnPxp)
- [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/pamAp4p/r/bWjPW0)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

**Comment by andaleliz** [comment]
While updating the mock-ups for contact info, I realized the verbiage for this use case that I provided doesn't make sense. This is what I provided, which is more applicable to canceling before saving than trying to edit one section before you've saved or cancelled work in another:

![image](https://user-images.githubusercontent.com/55992116/141849067-dfd5d7bc-537c-4264-b4be-337e80bca5e6.png)


@DanielleThierryUSDSVA I'm not sure we really do need to change the verbiage for this use case. Here's what we have today. What do you think?

![image](https://user-images.githubusercontent.com/55992116/141849017-4986b037-7839-4c32-aca7-80fa11d8884d.png)

**Comment by Samara-Strauss** [comment]
@mdewey I added this to your sprint. Can you review, add an estimate, and then remove the "needs grooming" label? Also, if you have questions, @andaleliz is the right person to ask. She audited the profile alerts a while back and is most familiar with the updates outlined above.

**Comment by Samara-Strauss** [comment]
Moving this back a sprint.

**Comment by SKasimow** [comment]
@mdewey - should we add this to Sprint 77?

**Comment by andaleliz** [comment]
Hi @SKasimow and @adamwhitlock1 this is still valid and I've moved the specs into the issue description for clarity.

**Comment by tmitchellgcio** [comment]
@andaleliz I had to test this first so I know what modal I'm changing and I'm not sure the verbiage makes sense. If we changed it, I'm not sure people would understand they edited another section if it asks `Are you sure?`. You asked @DanielleThierryUSDSVA on Nov 15th if this in the thread above but never got an answer. Should we get clarification on if this should actually be adjusted before we make this official? See your comment above for the screenshots. I think this change will cause confusion personally.

**Comment by andaleliz** [comment]
Hi @tmitchellgcio thanks so much for flagging this! I agree with you. 

@DanielleThierryUSDSVA can you please review [the previous comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31410#issuecomment-969291768 )and advise? Thank you :)

**Comment by andaleliz** [comment]
Hi @tmitchellgcio! I talked to Danielle about this and there is a copy update that needs to be made.  The heading should read:
> Save or cancel your edits to your [section name]

and then the body should say:

> Before you can edit a new section of your profile, you need to save or cancel your edits to your [section name]. If you cancel, we won’t save your in-progress edits.

I haven't had a chance to update the Sketch files yet (Could you make a ticket for this please, @SKasimow? @cgednalske or I can make this update) but wanted to get this to you so I don't hold you up.

**Comment by andaleliz** [comment]
Got the mock-ups updated.

- [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/waVZjj/a/OmlnPxp)
- [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/pamAp4p/r/bWjPW0)

**Comment by SKasimow** [comment]
Thank you! I'll put in backlog for Adam.

**Comment by jcatergovy** [comment]
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/35d7d65d-c043-4b25-a7a6-67258f88cf63)
There's two things that stand out to me that I wanted to check on before I do a PR.  There's only one space before the first word of the second sentence and the "k" in the button is lower case.  I've made these changes but just wanted to double check they were correct before putting in a PR.  @cgednalske @SKasimow

**Comment by Samara-Strauss** [comment]
> There's only one space before the first word of the second sentence

There should only ever be one space between sentences, not two.

> and the "k" in the button is lower case

I would assume the K should be upper case, but will let @cgednalske confirm.

**Comment by SKasimow** [comment]
@jcatergovy - I see it elsewhere as all uppercase "OK"

**Comment by jcatergovy** [comment]
@SKasimow I figured so, but I defaulted to the mocks.  I'll change it to an uppercase "K" and put in a PR

**Comment by cgednalske** [comment]
Just double-checked with Danielle because it's documented both ways in our designs/ticket. She confirmed that it should be all uppercase "OK."

**Comment by SKasimow** [comment]
@jcatergovy  - is this ready for us to test?

**Comment by cgednalske** [comment]
@SKasimow @jcatergovy -- just checked this on staging and it all looks good!

**One note:** when I checked in with Danielle about the uppercase OK, she mentioned that we might want to revisit this button because could be helpful to say more than just OK. Of course this is new work so likely not something we'll do right now, but I wanted to make sure we're all aware of it. cc @andaleliz

**Comment by SKasimow** [comment]
@jcatergovy - can I close this ticket (or you can if it's ready to close). I validated in staging as well.

**Comment by jcatergovy** [comment]
@SKasimow Yes this ticket is ready to be closed

**Comment by jcatergovy** [comment]
@SKasimow Yes this ticket is ready to be closed
