### ISSUE TITLE
Pass MHV-inbound SSO Users with Multiple MHV IDs back to MHV

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#31414]
## Issue Description
vets-api currently screens new logins for the presence of duplicate IDs from a variety of sources (MPI, EDIPI, etc.), and usually prevents a login if duplicates are found. For the full SSO integration with MHV we hope to be able to [call MHV to clean up accounts with multiple MHV ids](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/31160) as part of the login flow, but that work relies upon functionality that does not exist in MHV. In the meantime, we plan to disable the code that prevents a user with two or more MHV IDs from logging in *from MHV only* in order to prevent a disruption to MHV users. All other logins, both inbound and outbound, will be subjected to the same duplicate ID validation rules that currently exist.

---
## Tasks
- [x] Update duplicate MHV ID validator logic to evaluate the final login callback destination
- [x] Disable code that prevents users with duplicate MHV IDs from logging in if their final callback points to MHV
- [x] Ensure existing ID validation behavior remains unchanged, including for MHV IDs when the user does not originate from MHV

## Acceptance Criteria
- [x] Users with 2+ unique MHV IDs that arrive at va.gov's login modal from MHV will be able to successfully authenticate and be returned to MHV
- [x] Users with 2+ unique MHV IDs that arrive at va.gov's login modal from anywhere but MHV will not be able to successfully authenticate
