### ISSUE TITLE
Legacy appeals vs. Decision Reviews

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3141]
## User Story or Problem Statement
As a researcher, I need I need a clear understanding of the differentiation between legacy appeals and decision reviews so I can provide the right recommendation for future design to access the Decision Review page on va.gov.

## Tasks
- [x] Meet with Public Websites team (Jen Lee, Laura Walsh and Peggy Gannon) 11/21 @ 1pm

## Acceptance Criteria
- [x]  Gain an understanding of where the legacy appeal content lives on the website
- [x]  Understand where we can leverage existing flows for the AMA appeals process
- [x]  Determine the feasibility of switching the focus from legacy to AMA process

**Comment by YanaRoy** [comment]
@YanaRoy complete ticket

**Comment by kevinstachura** [comment]
Notes for meeting are located here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/notes/legacy-vs-ama-content.md
