### ISSUE TITLE
Decision Review Analytics 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3142]
## User Story or Problem Statement
As a researcher, I need to be able to see how the Decision Review page is currently accessed by system users so I can provide recommendation on future design for points of entry to the Decision Review page.

## Goal
_Establish understanding of analytics identifying Decision Review access points and frequency_

## Tasks
- [x] Ask analytics team for data on how users access and utilize the decision review page
- [x] Receive data on how users access and utilize the decision review page from analytics team

## Acceptance Criteria
- [x] Gain a solid understanding of the path by which users access the Decision Reviews page
- [x] Determine how many users access the Decision Review page(s) in a given time frame (month)
- [x] Understand areas of 'drop off' where users may have difficulty completing tasks

**Comment by kevinstachura** [comment]
Update: @nedierecel is currently looking into the following for this ticket:

 how veterans enter the page (page entries)
- how veterans currently utilize the page (pageviews/sessions)
- where the friction points are (drop offs, funnel exits)

**Comment by nedierecel** [comment]
@kevinstachura 

[Please see the Google Analytics report filtered down to basic activity for `/decision-reviews`](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D/)

- Pageviews - 22,911
- Sessions - 13,198 (To measure how many sessions viewed this page, we use the `Unique Pageviews` column. This means there were 13K sessions where this page was viewed at least once).

Nuances:
- There is a parameter called `fbclid` which is a Facebook parameter, so a communications team is likely sending traffic there. We can remove this parameter to make the reports cleaner (and in doing so, we can still see what sources of traffic send activity there using other reports)

[Friction Points: This is the flow report that shows where users are coming from and where they go next (or drop off).](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:~2Fdecision-reviews~2Findex.html&navigationsummary-keySelector.searchTerm=decision-reviews/)

- Of the pageviews coming from a previous page, over 1/3 come from `/disability/file-an-appeal/index.html`
- More then 75% are moving onto another page, with `/disability/file-an-appeal/index.html` as the next page viewed
