### ISSUE TITLE
Improve guidance for VFS teams on how to read/interpret a Staging Review issue ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31471]
## Issue Description
In October 2021, the [Anatomy of a Staging Review ticket](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945698334/Anatomy+of+a+Staging+Review+Issue+ticket) was created as Operational documentation for Platform teams. It has been used by QA Standards team when building the Collaboration Cycle dashboard in Domo, and it has been used by Governance team to easily understand the labeling system and how feedback is formatted.

On 2 occasions now, VFS PMs have asked about the layout/structure of a Staging Review issue ticket. Rather that rewrite the document, we can publish the existing Anatomy of a Staging Review ticket to Platform Website for VFS reference. 

In addition, we can link to the Anatomy of a Staging Review documentation  inthe staging review issue tickets. This could/would have to be made in the DraftingTemplate and in the [Collab Cycle feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Staging%2C+collab-cycle-feedback&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29) template. 

### User story

As a VFS team member, I need to know how to interpret a Staging Review issue ticket so that I am able to understand the full details of the ticket and know how to take action.

---
## Tasks
- [x] Publish Anatomy of a Staging Review Issue Ticket as a child page to the [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [x] link anatomy of a staging review ticket guidance in the Collaboration Cycle feedback for staging template
- [x] link anatomy of a staging review ticket guidance in the DraftingTemplate

## Acceptance Criteria
- [x] VFS teams can reference the anatomy of a staging review ticket guidance 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@chaseakirby I'm closing this out, but please remember to link in the sprint report

**Comment by chaseakirby** [comment]
@shiragoodman Thank you for the reminder! It's been added/linked!
