### ISSUE TITLE
Save 526 submission job run history

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#31489]
## Issue Description

`Form526JobStatus` submission are run in a background job and retried a number of times. Currently, we only have the error history for the last retry since each successive resubmit overwrites the previous result. We need to update  the `Form526JobStatus` model to maintain error history for each successive run when retrying form submissions.

---
## Tasks
- [x] Add a new attribute that will accumulate the error for each retry of the background job
- [x] Update the code to use the new attribute
- [x] Fix/update specs as required

## Acceptance Criteria

- [ ] Able to query background job error history of  `Form526JobStatus`
---

## Preliminary notes by @michelpmcdonald 

For 526 (https://www.vba.va.gov/pubs/forms/vba-21-526ez-are.pdf) disability claims, we accept the form data as JSON from the front end, and turn around and submit the claim to a backend system called evss.

We use sidekiq to submit the claim to evss, retry 15 times, exponential backoff up to around 36 hours.

The run results in the form526_job_statuses table, problem is, for error reporting, only one record in the db per 526 submission sidekiq job(3 jobs per submission: submit form, upload supporting files, and cleanup).

[#<Form526JobStatus id: 6660210, form526_submission_id: 880096, job_id: "bd8b06213c4dd8fe80fc6bbc", job_class: "SubmitUploads", status: "success", error_class: nil, error_message: nil, updated_at: "2021-09-28 14:51:45.383902000 +0000">, 
 
#<Form526JobStatus id: 6660188, form526_submission_id: 880096, job_id: "1c70c70218f81aaa2680dd37", job_class: "SubmitForm526Cleanup", status: "success", error_class: nil, error_message: nil, updated_at: "2021-09-28 14:50:31.937973000 +0000">, 

 **#<Form526JobStatus id: 6660186, form526_submission_id: 880096, job_id: "4b04cb951e904f987edc9990", job_class: "SubmitForm526AllClaim", status: "success", error_class: nil, error_message: nil, updated_at: "2021-09-28 14:50:31.908890000 +0000">]**
 
Since there is only one record in the form526_job_statuses per submission(job_class: "SubmitForm526AllClaim"), **the error_message field gets overwritten for each run attempt, so we end up losing run history.**

So, for example, if a given submission is hitting the "PIF in Use" error, the error_message field would be set to "PIF in Use" for runs 1-14, but if on the 15th run, evss is down, we will end up with "EVSS/DisabilityCompensationForm Outage" as the error message even though the underlying issue is "PIF in Use".

To address, I was thinking about either(open to discussion, for sure):
On the last run, if the job fails out with the outage error, re-enqueue the job.  This seems like it might have some issues.....how long should we wait ?  Should we just re-create the job with the original 15 run setting ?  That would just push it out another 36 hours, sometimes we are going to hit another outage on that last run, so that would trigger another 36 hours of tries….

OR

Create multiple records in the form526_job_statuses table, one for each run, so we don't lose run history errors.  I think this will work, in the model that represents 526 claims(Form526Submission) their is a one to many:
has_many :form526_job_statuses, dependent: :destroy

For the multiple record route, Part of this job would involve looking at:

app/workers/evss/disability_compensation_form/job_status.rb look at the Form526JobStatus.upsert’s.  Those would need to change to inserts.  The upserts currently overwrite run history.

Form526Submission.jobs_succeeded and make sure we are grabbing the latest form526JobStatus record.  Just to be clear here, normally there would be one 526JobStatus “SubmitForm526AllClaim” per Form526Submission.  This change would create multiple 526JobStatus per Form526Submission, so the idea is to make sure the current code that uses 526JobStatus always selects the newest 526JobStatus.

Searching the codebase,(including rake tasks) for uses of 526JobStatus and make sure we are selecting the newest 526JobStatus.

Also, might have to consider some unit tests:
unit test for Form526JobStatus:
spec/workers/evss/disability_compensation/*
