### ISSUE TITLE
Cerner scheduling cutover for Columbus

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31487]
## User story
As a Veteran registered for care at a VA Medical system implementing the Cerner portal, I need a seamless top task experience. (For example, when these Veterans click on the links in the "Manage my health online" box, they are connected to the appropriate entry point in the Cerner portal)

## Issue Description
In #31109 we validated areas where the url direction to Cerner is controlled by the FE and implemented a field-based redirect for health systems which have completely cut over. However, Columbus is a one off for scheduling only and will require temporary hard-coded logic. 

This custom logic will be removed in #31488 once Columbus has completely cutover.

**This needs to merge along with #31109** 

---
## Tasks
- [ ] Implement hard-coded logic to redirect scheduling urls to Cerner only for Columbus. 
- [ ] Maintain all other url logic

## Acceptance Criteria
- [ ] If the url is for scheduling and the health system = Columbus, the url is directed to Cerner.
- [ ] If the url is not scheduling and the health system = Columbus, there is no change to the url.

**Comment by mpelzsherman** [comment]
I'm assuming this ticket is blocked - see https://dsva.slack.com/archives/C0FQSS30V/p1635530621135100?thread_ts=1635529663.133000&cid=C0FQSS30V

**Comment by gescobardev** [comment]
@mmiddaugh Since facility pages do not have "Manage health online" section, are we referring to the "make an appointment" blue button? 

If so, when a user clicks that button should they go straight to patientportal.myhealth.va.gov ? The AC is not clear on behavior.

The cerner flag implemented in [this PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31109), is available for health systems only. Per Dave, there needs to be more discussion on Columbus. see: https://dsva.slack.com/archives/C0FQSS30V/p1635438485100800

I know we discussed these topic but I think it would be a good idea to confirm this here. 
Please fill in any other unknowns as well. I'm still not sure if I have the complete picture here.

**Comment by mmiddaugh** [comment]
@gescobardev We've confirmed that this redirect should occur for the entire [Central Ohio health care system](https://www.va.gov/central-ohio-health-care), not just the Columbus VA Clinic, as originally described. This task is now similar to the work for Spokane Cerner, for only the online scheduling links.

**Comment by gescobardev** [comment]
@mmiddaugh New Question:
>  This task is now similar to the work for Spokane Cerner, for only the online scheduling links.

Aside from the "schedule and manage health appointments" link (located within "Manage your health online" section), are we including the "Make an appointment" blue button?
If so, when you click that button, should you be directed straight to patientportal.myhealth.va.gov ?

**Comment by mmiddaugh** [comment]
Good question! No change of current functionality is expected for the "Make an appointment" top task button for Central Ohio (we did not change Spokane >Cerner either). 
Only the "schedule and manage health appointments" link within the  "Manage your health online" section needs to be updated for this system.
