### ISSUE TITLE
[VAMC] Assist in move of Oakland and Twenty first street VA Clinics from N. Cal. to San Francisco VAMC [PM}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31506]
## Tasks
Complete the following for both new facilities.
- [ ]  Facilities added to new system
- [ ]  All Facility Health Services have been moved to new facilities
- [ ]  Section changed
- [ ]  Health services updated
- [ ]  Services published
- [ ]  Request sent to CMS to update URLs in new facility

## Acceptance Criteria
- [ ]  Facilities added to new system
- [ ]  All Facility Health Services have been moved to new facilities
- [ ]  Section changed
- [ ]  Health services updated
- [ ]  Services published
- [ ]  Request sent to CMS to update URLs in new facility
