### ISSUE TITLE
[MCP] Updates to the details page's content

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31517]
## Issue Description
Craig pointed out in [#31341](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/31341) that we need to provide the URLs for the MCP MVP's links on the details page. Upon further investigation, there were some content changes that needed to be incorporated as well. We also noticed that some of the content took into account the combined FSR, but that won't be available for release. 

---
## Tasks
- [x] Add comments to the UXPin prototype with the correct links
- [x] Update the page's content where applicable  

## Acceptance Criteria
- [x] The prototype is updated and linked in this ticket
- [x] A ticket for frontend content changes is created and linked in this ticket
