### ISSUE TITLE
Add reviewer github handles to Staging Review issue tickets (aka feedback)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31524]
## Issue Description
Staging Review issue tickets are created via bulk upload using the DraftingTemplate. 1 person on Product Support runs the bulk upload process, and all of the feedback documented in the DraftingTemplate is transformed into github tickets. The 1 person that runs the process is the "opened by"  person on the github tickets, meaning they are the one who receives notifications if/when a VFS team member comments on the ticket. It would be valuable if the practice area review who documented the feedback is tagged in github so they are aware when new VFS comments come in. 

---
## Tasks
- [ ] Research if there is a way to automatically to add Platform reviewer to their staging issue ticket. 

## Acceptance Criteria
- [ ] Platform reviewer who identified a staging issue is assigned to the staging ticket. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
