### ISSUE TITLE
Turn off Telehealth and home health for Community care searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31520]
## Issue Description
PPMS Endpoints will be soon be updated with Telehealth parameters. Telehealth will default to being "ON" and we will need to pass a new param to turn it "Off"  

We won't know what the param is until they release it to INT on the 25th

---
## Tasks
- [ ] Pass new param (TBD) to turn "Telehealth" Off 
- [ ] Pass new param (TBD) to turn "Home health" Off 
- [ ] Retest /v1.0/PlaceOfServiceLocator 
- [ ] Retest /v1.0/ProviderLocator 

## Acceptance Criteria
- [ ] Community care search functionality is maintained.
