### ISSUE TITLE
Front end to send lat/long for queries (1a)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31527]
## Issue Description
To eliminate the possibility for subtle shifts in the map causing overlapping results, we're converting to sending lat/long for both CCP and VA routes

---
## Tasks
- [ ] Add lat/long (for central point) to queries for CCP and VA routes
- [ ] Remove bounding box and address
- [ ] Confirm this change resolves #30212 / overlapping results set
- [ ] Add a feature toggle for this behavior

## Acceptance Criteria
- [ ] CCP requests use only lat/long
- [ ] VA requests use only lat/long
- [ ] Facility Locator searches still work

**Comment by mpelzsherman** [comment]
FIndings so far:

1. Removing bounding box from the query and switching from "latitude/longitude" to "lat/long" causes the page size to increase dramatically. The query results are un-bounded.

2. The steps listed in #30212  no longer cause overlapping results in production. The only change we’ve made is reducing the page size to 10, but maybe that was enough? Or maybe something changed on the back end?

I'm hoping @darkbushido can help explain what's going on here.

**Comment by mpelzsherman** [comment]
Per @darkbushido - Lighthouse doesn't use the radius parameter.

Per @davidconlon - This UX (unbounded search results) is fine, we can ship with it.

**Comment by mpelzsherman** [comment]
This change introduces a pretty major issue with "Search This Area of the Map". We're getting results back that are not displayed on the map now.

![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/80267/140094187-31fb49ae-94e5-48e2-82f5-a0cf612017cb.png)

**Comment by mmiddaugh** [comment]
Because of usability issues created by this work, the team decided to merge this and leave the functionality turned off - we will return to this effort once Lighthouse has added the ability to limit the set via radius.

**Comment by mpelzsherman** [comment]
Since the code has been merged and verified in staging, I think we can close this.
