### ISSUE TITLE
Expose total number of results to Facility Locator front end (2b)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31521]
## Issue Description
The Facility Locator front end needs to know the total number of search results to restore the Facility Locator result subhead. 

---
## Tasks
- [x] Expose total number of VA facilities search results 
- [x] Expose total number of community care search results 

## Acceptance Criteria
- [ ] Facility Locator subhead can display (total number of ) results for `"facility type"`, `"service type`" near `"geographic parameter"`
---
