### ISSUE TITLE
Remove Validate MHV Account application

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#31523]
## Issue Description
Ticket # effectively deprecates the need to have the Validate MHV Account application in vets-website.  To reduce additional code the entire `aplications/validate-mhv-account` should be deleted.  https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/validate-mhv-account

---
## Tasks
- [x] Remove `src/applications/validate-mhv-account` directory
- [x] Update unit/e2e tests to reflect it

## Acceptance Criteria
- [x] There is no Validate MHV Account application
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
