### ISSUE TITLE
Design Exploration for R&S usability improvements

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#31536]
## Issue Description
_Design exploration for Tier 2 articles layout according to our findings from analytics and stakeholder's feed back_

---
## Tasks
- [x] _Gather redesign areas from analytics findings_
- [x] _Explore CMS capabilities_
- [x] _Create spreadsheet and discovery document_

## Acceptance Criteria
- [x] _Spreadsheet and discovery document created_
- [x] _Better understanding of CMS capabilities_
- [x] _Better understanding of background and previous research of R&S_

**Comment by mgleo** [comment]
[Discovery document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/resources-and-support/discovery.md)
