### ISSUE TITLE
Data Exploration for R&S usability improvements

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#31534]
## Issue Description
_Walk through existing R&S Domo dashboard and GA dashboard with public website team and analytics team _

---
## Tasks
- [x] _Meeting with public website team to learn what tags are tracking what_
- [x] _Meeting with Analytics team to learn more information on current tags and if any changes we can make to improve_
- [x] _Document Notes / Action items for potential tickets_
- [x] _Team debrief_

## Acceptance Criteria
- [x] _Fully understand R&S' DOMO dashboard and GA dashboard_
- [x] _Analytics findings presented in [Discovery Document](https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/31536)_

**Comment by mgleo** [comment]
[Discovery document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/resources-and-support/discovery.md)
