### ISSUE TITLE
Remove Joanne from Collaboration Cycle & Orientation documetation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31549]
## Issue Description
Joanne Esteban left VSP on 10/8. She is currently listed as the POC on most Analytics documentation for the Collaboration Cycle, as well as the lead for Analytics Orientation. We need to remove her name, and potentially update it with another Analytics person.

DO NOT START until 11/1 - New Analytics and Insights PM is starting that day

**Notes**
Pages that Joanne authored:
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586823249/KPI+Dashboard+decision+log
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1601142787/KPI+dashboard+backlog
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1838022683/KPI+dashboard+post-mortems
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587642603/Release+plan+-+standardized+kpi+dashboards+v1+-+June+July+2021
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1904836653/Old+Performance+Dashboard+Product+Outline
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1905000486/Performance+dashboard+design+sprint+findings+solutions+pain+points
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1903919120/Covid+Dashboard+Product+Outline
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1904902182/Analytics+Playbook+Product+Outline
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1905066142/Google+Tag+Manager+product+outline
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1903657071/Data+warehouse+product+outline

---
## Tasks
- [x] Identify all pages, documents, artifacts, etc. where Joanne is mentioned.
- [x] Confirm if the new A&I PM would like to be included in these artifacts.
- [x] Confirm who from A& team would be included as optional attendees in CC Staging Reviews (previously Lauren S. and Joanne. Edited to Lauren and Jenna after Joanne left VSP.)

## Acceptance Criteria
- [x] Joanne has been removed from all operational/internal guidance on Confluence.
- [ ] Joanne has been removed from Collaboration Cycle and Platform Orientation guidance on Platform Website.
- [x] We have confirmed with the A&I PM their preference for being included in Collab Cycle and Orientation documentation. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by seanasewell** [comment]
@shiragoodman 
Joanne's name is nested in a url. Should I replace her name with Michelle's name?
Located on this page...
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1170440248/Platform+newsletter+style+guide#Hyperlinks

**Comment by seanasewell** [comment]
@shiragoodman 
Looks like Joanne was the author of this document. Is there a way to reassign these or should we keep them as-is?
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics

**Comment by shiragoodman** [comment]
> @shiragoodman Joanne's name is nested in a url. Should I replace her name with Michelle's name? Located on this page... https://vfs.atlassian.net/wiki/spaces/PPS/pages/1170440248/Platform+newsletter+style+guide#Hyperlinks

@seanasewell no, that's not necessary. That url is a link to the Analytics teams domo request template. The link still works, so I think it should be ok.

**Comment by shiragoodman** [comment]
> @shiragoodman Looks like Joanne was the author of this document. Is there a way to reassign these or should we keep them as-is? https://vfs.atlassian.net/wiki/spaces/PPS/pages/1587478606/Platform+Analytics

@seanasewell leave as-is. We only need to worry about Joanne's name in anything related to Collaboration Cycle or Platform Orientation. This is outside of that.

**Comment by shiragoodman** [comment]
hey @seanasewell  - Joanne's name is still listed in the [Platform Orientation template. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template) Can you 1) notify Michelle that we will be replacing Joanne's name with hers and 2) edit the template? I imagine this is your first time editing a gh template. @allison0034 can help you out.

**Comment by seanasewell** [comment]
@shiragoodman @allison0034  is setting up some time on my calendar tomorrow (11/16) to walk me through how to edit the GH template. Just wanted to give you a heads-up if you were curious to the status of this. Thanks for calling this out!

**Comment by shiragoodman** [comment]
no problem - thank you both!
