### ISSUE TITLE
[FE] Migrate to Redux Hooks

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31557]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [PR with discussion](https://github.com/department-of-veterans-affairs/vets-website/pull/19096)
- [redux hooks](https://react-redux.js.org/api/hooks) 

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

How we handle data is getting not scalable. We should look at deprecating the current HOCs and moved towards a redux hooks solutions. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Pinpoint the pain points in the current data handling solution
- [ ]  Implement solution
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by julieadair1** [comment]
@mdewey @jparker0425 - is this related to pre-check-in work?
