### ISSUE TITLE
[MCP] MVP UAT research plan

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31566]
## Issue Description
As part of the MCP's release, we'll need to recruit Veterans to sign into the tool so we can validate that the correct data is populating in the UI. 

---
## Tasks
- [x] Write a research plan to recruit Veterans that have medical copay bills
   - Ensure all use cases are considered
- [x] Send the research plan to Lauryl and Kristen for review  

## Acceptance Criteria
- [x] The research plan is uploaded in GH and linked in this ticket

**Comment by rileyorr** [comment]
The research plan has been added to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/uat-nov-2021/research-plan.md))
