### ISSUE TITLE
[MCP] Validate the data is correctly displaying in the UI through UAT

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31569]
## Issue Description
As part of the MCP's release, we'll need to recruit Veterans to sign into the tool so we can validate that the correct data is populating in the UI. 

---
## Tasks
- [x] Set up a spreadsheet to track use cases validated + session notes
- [x] Conduct UAT sessions

## Acceptance Criteria
- [x] The target number of validations for each use case is reached
- [x] The UAT spreadsheet is linked in this ticket after the final session

**Comment by rileyorr** [comment]
We've wrapped up our final UAT session! [The completed spreadsheet can be found here.](https://salientcrgt.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/VHA%20Debt%20Letters%20Improvement/Veteran%20Research/November%202021%20UAT/Session%20Notes.xlsx?d=w720b50db3988452a88a56464aaeac321&csf=1&web=1&e=8mULpY)

**Comment by denisecoveyduc** [comment]
Thanks @rileyorr  for all your hard word during those UAT sessions.. we learned a lot about the product.
