### ISSUE TITLE
[MCP] MVP UAT conversation guide

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31568]
## Issue Description
As part of the MCP's release, we'll need to recruit Veterans to sign into the tool so we can validate that the correct data is populating in the UI.

---
## Tasks
- [x] Draft a conversation guide for UAT capturing the use cases that'll be tested
- [x] Send the conversation guide to Lauryl and Kristen for review 

## Acceptance Criteria
- [x] The conversation guide is uploaded in GH and linked in this ticket

**Comment by rileyorr** [comment]
The conversation guide has been added to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/uat-nov-2021/conversation-guide.md))
