### ISSUE TITLE
[Design][Content] Refreshing Appointment Page Error State on the Next Day

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#31583]
# Description 
Veteran refreshing previously opened appointment page the next day and seeing "Something went wrong" page. This will be blocker for veteran to check-in for new appointments next day if they are trying to refresh the same page.

More details here: https://dsva.slack.com/archives/C02GXKL8WM6/p1634574319222500

This new error state uses the generic "Something went wrong" message. Will this be a completely separate message or does it still need to cover this new use case and all the old generic use cases. Talk to engineering about this.

# Tasks
- [ ] Talk to back-end engineering
- [x] Work with content on wording

# Acceptance Criteria:
- [x] Finalize wording and design 
- [ ] Communicate final solution to engineering

**Approved wireframe:**
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/y5a1wa/a/zx2EEb4/r/w8mpk9/

**Comment by kristenmcconnell** [comment]
Meeting with @kanchanasuriya on Monday, so this might extend past the end of the sprint.

**Comment by zach-park** [comment]
Draft UI: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/v1dlKQ/a/zx2EEb4/r/Yn2Vx0
Cc: @kristenmcconnell @DanielleThierryUSDSVA @jparker0425 @julieadair1

**Comment by DanielleThierryUSDSVA** [comment]
Hi @zach-park! Here's are 2 options for content with edits. 

I think we want to avoid the wording of "check in again" because if they do want to check in at this point, it would be for an appointment they haven't already checked in for.

I do have a question: 
- Is this only displayed if a person refreshes before successfully checking into an appointment? If yes, option #1 is best. 
- Or could this appear after someone successfully checked in and then refreshed the confirmation screen? If this is the case, we may need option #2 for that situation?

## Option 1

**We couldn't check you in**

We're sorry. Your session expired. To check in for an appointment, text **check in** to 53079.


## Option 2

**Your session expired**

To check-in for an appointment, text **check in** to 53079.

**Comment by zach-park** [comment]
Hi @DanielleThierryUSDSVA , I believe that option2 is better aligned with the user scenario. UI mockup is updated. Thank you!

**Comment by zach-park** [comment]
Updated as mentioned above, @DanielleThierryUSDSVA !
