### ISSUE TITLE
[Discovery] Footer links with promo banners design 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31606]
### Status
**[2024-07-12] [Fran]** Added to product sync list asking Michelle if this ticket can be closed.

#### Discovery phase
Review current promo banners and determine how to make links accessible in the footer for users (e.g. accessing links to increase navigation and findability.). This discovery issue is meant to capture design ideas, and to discuss ideas on how to make the promo banners a better marketing tool and keep footer links visible.

#### High-level user story
As a Veteran I to be able to view footer links when the promo banners is present.

### Considerations
- Must work well on mobile and desktop platforms
- Must address accessibility concerns and support for adaptive tech
- Should consider iterative feature development
- Initial design/development must align with current CMS functionality (promo banners marketing concept)

### Tasks
- [ ] Baseline existing features and flows
- [ ] Illustrate use cases via feature flow diagrams
- [ ] Determine new features needed and propose staged deployment of new components
- [ ] Wireframe UI suggestions illustrating features in context

### Acceptance Criteria
- [ ] Brief discovery doc outlining baseline feature flow and functionality created
- [ ] Diagram uses cases and high-level feature flows 
- [ ] Wireframe UI suggestions illustrating features (including date/time filtering) in context created

**Comment by FranECross** [comment]
Added to Prod Sync mtg agenda for 2/12/2024

**Comment by FranECross** [comment]
From 2/12/24 Product Sync - Dave will look into this.

**Comment by jilladams** [comment]
@FranECross you could try publishing a Promo banner in a Tugboat (once Tugboat is back) to verify if this is still an issue. I suspect that this has been long resolved.

**Comment by FranECross** [comment]
Closing as a no op
