### ISSUE TITLE
[Research] User Roles Research: Create (draft) research plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#31616]
## Background
We need to begin developing our research plan for the user roles discovery work.

Goal is to have one general research plan but multiple conversation guides

## Tasks
- [x] Create goals of research 
- [x] Create draft plan
- [x] Review with Samara (and other stakeholders as needed)

**Comment by ajakabcin** [comment]
@andaleliz I think this good to mark as complete based on Monday's meeting, correct?
