### ISSUE TITLE
Update PACT tests

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31624]
## Issue Description
It's been a while since we focused on PACT testing so we need a refresher. 

---
## Tasks
- [ ] Work with engineering team to get refresher on PACT
- [ ] Update existing PACT tests

## Acceptance Criteria
- [ ] Existing tests are up to date with current functionality
---

**Related: #24797**
