### ISSUE TITLE
[Research] Pre-check-in Synthesis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#31639]
## User Story
- As a product team, we want to know the findings from the usability test. 

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/conversation-guide.md)

## Description
Analyzing the videos and notes from the research study on pre-check-in to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [ ] Post synthesis documents to GitHUB
- [ ] Write top-line summary (optional if daily summaries were sent out)

**Comment by niradatta1** [comment]
Link to synthesis documentation here: affinity mapping exercise https://miro.com/app/board/o9J_lv-9YXM=/?moveToWidget=3074457367778216451&cot=10
