### ISSUE TITLE
Rotate/Re-encrypt existing db records

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#31630]
## Issue Description
This issue breaks up #31273. After [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/8173) is merged (which introduces KMS into vets-api) we will need to re-encrypt existing records with the KMS key. There is a rake task that can be run to rotate the records. 

---
## Tasks
- [x] Rotate existing records
- [x] Note any rotation issues
- [x] Create documentation in Confluence

## Acceptance Criteria
- [x] Rotate records in all envs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Update:
- [x] dev, staging and sandbox records are rotated

I added a migration to some of the STI tables related to creating indexes concurrently, but I'm still seeing some issues in PgHero related to slowness. The next step may be to look at some of the db logs to see exactly which queries are being run. It seems that running the rotation in batches of 1000 is slower than it should be. It took nearly 1 minute to rotate ~1000 records. 

Another issue: When running the rotation in the rails console, I hit a session inactivity timeout and was disconnected from the instance. The timeout needs further investigation, and needs to be investigated before auto rotation can be set up. Will be connecting with Ops.

**Comment by LindseySaari** [comment]
It was decided to hand off some of the heavy re-encryption work to Sidekiq. I'll be creating a Sidekiq job that we can run multiple times (probably 5) to re-encrypt the records. With out current calculations, it would take 5.5 straight days to do this work via ssm/rails console, but we were also experiencing ssm timeouts. Sidekiq seems like the best option and if we're able to run 5 jobs, the rotation should take ~1day. While running the jobs, it'll be best practice to monitor Grafana charts for Sidekiq and RDS CPU spikes. Next up: create the Sidekiq job and do some benchmarking for how to split up the tables/records across 5 jobs.

**Comment by LindseySaari** [comment]
Benchmarking/job splitting [here](https://docs.google.com/spreadsheets/d/16HQ91dEWrNr7eIHBaJ1znI0ICCDT_-Crhn7_NCpQ-ng/edit?usp=sharing).
