### ISSUE TITLE
Finalize Implement MVI proxy add endpoint

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3163]
## User Story or Problem Statement
As the Backend Engineer on the Benefits and Memorials team, I need to complete a series of tasks identified during endpoint implementation development so I can establish the implementation and complete the integration with MVI.

## Goal
_Finalize the MVI proxy add endpoint implementation_

## Tasks
- [x] Provider organization section
- [x] Custodian section
- [x] BGS Credentials from MVI

## Acceptance Criteria
- [x]  Response from MVI on dev env

## Original Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2032

**Comment by SMLuthi** [comment]
This ticket has been changed to more properly reflect the MVI testing process. The integration has been completed (barring and changes dues to testing on the upper environments) but responses need to be received on the dev (and staging environment). But to do this, we need to work closer with MVI and hear from them whether our requests are being build correctly. This will be reflected in another ticket.
