### ISSUE TITLE
Address issues from HLR v2 Design Intent

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#31636]
## Issue Description
Address all issues brought forth in the design intent meeting so we have a plan moving forward.

---
## Tasks
- [x] Respond on ticket to what we will do vs. what we must push back on
- [x] Begin work on implementation of changes in HLR 2.0 Design

## Acceptance Criteria
- [x] respond to design intent with agreements / challenges
- [x] Begin work on implementing changes in 2.0 Design
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Portions of this ticket have been completed, but the scope on it has changed. After chatting with members of the design system during their office hours, it was  determined that we will need to look into two specific areas:

1. The contact info update flow
2. Issues eligible for review flow

The first item requires a lot more work because it involves creating a totally new pattern that does not yet exist in the design system library. It will be out of scope for this ticket.

The second item has been taken care of by Ryan T's suggested design. We will be implementing that pattern and whatever small edits come down the line.

We are closing this ticket with our current progress and will open a new ticket with the expanded scope for next sprint.

Ryan's list loop: https://www.sketch.com/s/92b41945-e57a-4eaa-9c66-ea017551f466/a/zxW8JYy

**Comment by kevinstachura** [comment]
The design intent ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31318
