### ISSUE TITLE
POC IA Validation

### ISSUE THREAD

**Issue by LSiopis** [department-of-veterans-affairs/va.gov-team#31647]
## Acceptance Criteria
- [ ] Launch tree test.
- [ ] Launch recruiting. 
- [ ] Conduct research.
- [ ] Update Shannon everyday with codes.
- [ ] Communicate progress and blockers as appropriate.
