### ISSUE TITLE
[Research] Run Pre-check-in Usability Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#31640]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/conversation-guide.md)

## Description
Facilitate User Research Sessions for Pre-check-in Usability Study (appx 20 sessions) with up to five observers from the team per session

## Tasks
- [x] Discuss research session attendance protocol with the whole team
- [x] Complete all research interviews based on [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/conversation-guide.md) and [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-plan.md)

## Acceptance Criteria
After all of the sessions are complete 
- [x] Consolidate Notes from each team member listening on sessions
- [x] Download video of sessions

**Comment by kristenmcconnell** [comment]
Study completed with a total of 11 sessions on Nov. 1.

**Comment by niradatta1** [comment]
Consolidated notes from team members + notetakers; All videos downloaded.
