### ISSUE TITLE
Update content on Contact Us and Ask VA R&S article-HOLD UNTIL BEGINNING OF DECEMBER

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31651]
## Issue Description
Once Ask VA has been up and running for about a month, we need to update the language on our R&S article [Ask VA replaces IRIS and the GI Bill Help Portal](https://www.va.gov/resources/ask-va-replaces-iris-and-the-gi-bill-help-portal/) so that we no longer use the word "new" to describe Ask VA.

Two places to update: 
- [x] Intro
- [x] First Q&A "What’s Ask VA?"

We also need to update the language on our [contact us](https://www.va.gov/contact-us/) page to remove the word "new" from the text under the H2 Contact us online through Ask VA.

And we need to consider if we should add an information alert to the contact us page calling out Resources and Support rather than having it in the section toward the bottom of the page.

## Tasks
- [x] Confirm with Beth that it's time to remove "new" (Randi//Selina)
- [ ] Decide if we should add informational alert to Contact Us page (Beth)
- [x] Remove "new" from intro and first Q&A (Selina)
- [x] Remove "new" from contact us page (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Article and Contact us are updated on live site

**Comment by RLHecht** [comment]
@bethpottsVADEPO Is this something we want to bring into sprint 63 or wait until the new year to update?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Let's bring it into the next sprint! We'll hold off on adding an info alert to the contact us page for now though. We need to flesh out R&S a bit more first.

**Comment by lunascoop** [comment]
@RLHecht I've removed "new" from the page intro in the multiple QA and single QA. I've also updated some of the other single QAs (bolding account types (ID.me, etc.)

- Ask VA replaces IRIS and the GI Bill Help Portal: http://preview-prod.vfs.va.gov/preview?nodeId=34313
- How do I get a verified account to access all the features in Ask VA?: http://preview-prod.vfs.va.gov/preview?nodeId=34513
- What features are available in Ask VA if I’m signed in?: http://preview-prod.vfs.va.gov/preview?nodeId=35507
- What’s Ask VA?: http://preview-prod.vfs.va.gov/preview?nodeId=34310

**Comment by RLHecht** [comment]
@bethpottsVADEPO We made these updates but wanted you to review the intro and the "What's Ask VA" single Q&A because we reworked the sentences a little when we took out the word "new." Can you let us know if this is ready to publish?

**Comment by RLHecht** [comment]
Moving to sprint 64

**Comment by bethpottsVADEPO** [comment]
@RLHecht Looks good, thank you! A couple things...

What’s Ask VA?: http://preview-prod.vfs.va.gov/preview?nodeId=34310
For this Q&A, would you move "online" to the start of the sentence: Ask VA--or AVA--is an online service

Would you please delete the very last Q&A altogether--the one about still being able to access your GI Bill questions? It's no longer relevant since the GI Bill Help Portal has been redirected to our contact us page.

Then go ahead and publish after you take a final look.

**Comment by RLHecht** [comment]
We need to change the action link to go directly to the Ask VA page. @lunascoop

**Comment by bethpottsVADEPO** [comment]
@RLHecht 
That last sentence of the intro will need reworking with the action link change. You can use this: 
Or go to Ask VA now to send us your questions, updates, and documents online.

And change the action link text to what we've been using elsewhere: Contact us online through Ask VA

**Comment by lunascoop** [comment]
@RLHecht these changes are ready for review. 
Ask VA replaces IRIS and the GI Bill Help Portal: http://preview-prod.vfs.va.gov/preview?nodeId=34313

**Comment by RLHecht** [comment]
Thanks! I reviewed and published these new changes

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
