### ISSUE TITLE
[MCP] Update the overview page's facility contact information for proper semantic heading structure

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#31663]
## Issue Description
After incorporating Angela's 508 feedback regarding semantic structure, the design team noticed the 'Questions about your treatment or your charges' section could be simplified from headings to an unordered list. Screen readers will read the facility list out as an x number of items.  

---
## Tasks
- [x] Update the content on the overview page to list the Veterans' facilities in an unordered list 

## Acceptance Criteria
- [x] The updated UXPin has been linked in this ticket
- [x] A ticket for frontend has been created and linked to this ticket
