### ISSUE TITLE
[FE] Auth Profile: Moving exisiting Contact Information form from Personal Information to it's own section

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#31668]
## Issue Description
As shown in the screen shot below, we need to move the Contact Form fields from the personal information section to the new Contact Information section.

![Screen Shot 2021-11-04 at 9 20 52 AM](https://user-images.githubusercontent.com/26075258/140320530-52cc6434-1a13-40a1-91a1-9b976af45ce6.png)
## Tasks
- [ ]  The design pattern and componenets used should follow what is currently in Production for Profile vs.  being based strictly on the mock-ups.   The [initial mockups](https://images.zenhubusercontent.com/5f9095454fbba3b0c3d10cff/447b1d4a-9f44-4f6a-a42a-2f76280d591e) were based off an outdated Sketch file.
- [ ]  The content on this page matches [Contact information documentation on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/contact-info-copy.md).
- [ ] Information available to the user is based on their [Level of Access (LOA).](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile.md)

## Acceptance Criteria
- [ ] All Contact Information fields are now on in the Contact Information section and behind a feature flag.
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
This update is on Staging.

**Comment by zacharymorel** [comment]
Hey Marci, this ticket should still be open and for the next sprint. It is for moving the Contact specific fields to the Contact Information page. The Contact Information has currently just a placeholder.

**Comment by MarciMcGuireGCIO** [comment]
Front end work on another task took longer than anticipated due to learning curve, so #31668 was not completed and moved to Sprint 61

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This can be validated on Staging

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel !  cc @Samara-Strauss @cgednalske @andaleliz

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I was able to successfully update information from the new Contact info page, and I saw the success messages, as well as an error when it had trouble saving an update.  I also got a notification when I attempted to update another field while already having a field open for editing.

**Comment by Samara-Strauss** [comment]
![image](https://user-images.githubusercontent.com/34068740/143900477-de1f5702-9a39-439c-af63-fe2dcf5cdb3f.png)

I was not able to update and got this error ☝️ Can you please look into this?

**Comment by Samara-Strauss** [comment]
Also, this information should be removed from the personal information section as part of this work, and I am still seeing it.

**Comment by Samara-Strauss** [comment]
Update: Contact info is now working for me, so must have been a temporary glitch. However, this information still needs to be removed from the Personal Info section, so please capture that either here or in a separate ticket if one does not already exist.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @Samara-Strauss !  We have issues for adding the new fields & different states to the Personal Info page, but I'll also make note to remove the old fields.
