### ISSUE TITLE
Design intent [Public Websites Team - Outreach & Events Enhancements]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31677]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [X]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [X] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 

## After meeting

**Platform**
- [x] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No (Ryan T. will need to review)

## Artifacts

Provide links or documents for the following: 

- [X] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
- [X] [Product Initiatives Briefing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Initiative%20Briefing.md)

 
 
 
- [X] [Whiteboard sketch or other lo-fi prototypes or wireframes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/design)
- [X] [User flow Outreach & Events MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/o%26e-calendar-feature-baseline.md)
- [X] [COA Use Case Workflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/design/COE_Usecase_Workflows_1.png)
- [X] [Updated Wireframes](https://sketch.com/s/ceaa48f6-88f4-48d1-9578-7f6751a8ab74)

### Required
- Product Manager: Brian Lloyd
- OCTO-DE Product lead: David Conlon
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Cassandra Allen, Designer
- Jim Adams , Designer (Assisting)

### VFS Attendees

- Accessibility: 

## Scheduling

**[10/29/2021]** **[2 PM]**

## Additional information
For the Design Intent, you'll receive feedback from design and IA only. You won't receive feedback from accessibility, content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.
