### ISSUE TITLE
Prevent unintended MPI updates via 10-10ez

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#31683]
## High Level User Story
As a Veteran, I need to avoid inappropriate modifications to MPI so that my data remains accurate.

>If the user is authenticated, we pre-populate some of the fields for them, based on the values in the Master Person Index (MPI). However, these fields are editable, and may be changed by the user.

## Goals
Prevent unintended/inappropriate modifications to MPI when filling out the 10-10ez.

## Discovery
Anticipating short-term and long-term solutions

## Issues within this epic

<details>
<summary> Already created </summary>

- [x] Designs for the new question - @Dene-human #31989
- [x] FE ticket for non-editable fields - @charCodelet #32137
  - Acceptance Criteria:
    - Submission still successful
    - Logs still accurate, etc.
- [x] Eng Discovery - what validation we want/need - @jchilders #32374 
  - TBD: Switch where the data that makes up the payload is coming from—should be 
  - TBD: Verifying no changes made
  - TBD: what data fields are pre-populated/sent along w/ submission?
    - TBD: how do we carve out the locked-down fields (i.e. make them uneditable) vs. everything else that pre-populates 10-10ez now?
</details>

To be created:
- Backend - n/a
- 

### Initiative Brief
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/initiatives/avoid-mpi-changes.md

References
- #26762

**Comment by SKasimow** [comment]
@lzapson per grooming discussion, we can re-visit after you have a chance to review and determine whether it will suffice to just make the fields uneditable or if we also need to pass the auto-populated fields downstream.

cc: @MickinSahni
