### ISSUE TITLE
[FE] Auth Profile: Add New Fields to Personal Information page - Blank State

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#31685]
## Issue Description
As a Veteran I want the ability to see which personal information fields I have not yet filled in, and clear instructions on how to do so, so that I can enter the information if I so choose.

### Tasks
- [x]  The design pattern and componenets should mirror the design pattern currently in use in the VA.gov Profile.  If the Sketch mockups differ, then use the Production pattern.
- [x] Copy should match what is documented in the [front end copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [x] Each question will require a default "blank" state that provides some information advising the user to click edit to provide info.  [See exact copy here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---blank-state).

Please use the below files for reference
- [Blank State Sketch mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2)
- [UXPin Prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

## Acceptance Criteria
- [x] Fields moved to the Contact Info page are removed from Personal Info page
- [x] New Fields are added to Personal Info page
- [x] Features are behind flag to test on staging 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
Thank you @andaleliz !

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel please review the updated tasks and acceptance criteria.  We may need to break this out into separate tickets since there are multiple states.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO It appears we should split it up. This would be wise.

**Comment by MarciMcGuireGCIO** [comment]
Ok; sounds good.   Are you good splitting them, or would you prefer that I do it?

**Comment by zacharymorel** [comment]
Yeah, I think we can split this user story up in to 4 user stories:
This story = "Blank State" - 5 pts
Read State - 3 pts
Edit State - 3 pts
Error State - 3 pts

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel ! I'll make the three new tickets based on this one.

One quick clarification- the fourth state is not an error state.  It's a "required field" state that occurs when a user selects the "other"-type option.  They are then required to add a new value to the text box that appears.

**Comment by zacharymorel** [comment]
> Thanks, @zacharymorel ! I'll make the three new tickets based on this one.
> 
> One quick clarification- the fourth state is not an error state. It's a "required field" state that occurs when a user selects the "other"-type option. They are then required to add a new value to the text box that appears.

Oh, nice catch! Sorry developer jargon there where we refer "require fields" as a component having an error. 
Go about it using the terminology a user would expect. We're on the same page.

**Comment by MarciMcGuireGCIO** [comment]
Thanks for explaining that! :)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Have a look at this on Staging!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel !  Sorry, we've been in calls since 10 AM.  Looking at it now.

**Comment by MarciMcGuireGCIO** [comment]
Hey @zacharymorel !  This page looks great so far!  

Couple of things I saw -- the radio buttons for Gender Identity and Sexual Orientation don't seem to be working for me, and the text boxes are not visible for either of those.  I was using Chrome on Win 10.

![image](https://user-images.githubusercontent.com/73354907/145485512-f814ae66-ee4f-413a-b81d-cc40b3715924.png)
![image](https://user-images.githubusercontent.com/73354907/145485540-dbf4a495-c4ec-428a-a6d6-56886eb22f43.png)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO did you select the text of the radio options?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel , no, I clicked on the radio buttons themselves.  That's what I imagine most users would expect to work.  Is that a limitation of the radio button component?

**Comment by zacharymorel** [comment]
> @zacharymorel , no, I clicked on the radio buttons themselves. That's what I imagine most users would expect to work. Is that a limitation of the radio button component?

Yes, it's a behavior of the VA design libraries radio component.

**Comment by MarciMcGuireGCIO** [comment]
Ok, thank you!

**Comment by MarciMcGuireGCIO** [comment]
Quick update - noticed a minor misspelling.  Should say "Edit your profile to add pronouns"
![image](https://user-images.githubusercontent.com/73354907/145623504-7df58b98-3009-4c40-8a04-2d07b32abc7d.png)

**Comment by MarciMcGuireGCIO** [comment]
^^ @adamwhitlock1 this is the only update needed to close this out.  Thx!! 😃

**Comment by MarciMcGuireGCIO** [comment]
Noting that I deleted a few comments that were left on the wrong ticket to avoid confusion.

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO fix has been deployed to staging if you would like to take a look

![Screen Shot 2021-12-14 at 10 58 31 AM](https://user-images.githubusercontent.com/8332986/146053960-ba6b6540-d44d-47c5-93bb-f5d23186c52a.png)

**Comment by MarciMcGuireGCIO** [comment]
Thanks @adamwhitlock1!

**Comment by MarciMcGuireGCIO** [comment]
Looks great!  Thanks @adamwhitlock1 !  
![image](https://user-images.githubusercontent.com/73354907/146054886-48d10591-12e5-4d62-94f5-604d96a26b58.png)

**Comment by MarciMcGuireGCIO** [comment]
Noting that this will not go to Prod until after user research, possible resulting modifications, testing & Staging review.

**Comment by MarciMcGuireGCIO** [comment]
Re-opening this so that Adam can add unit tests.

**Comment by MarciMcGuireGCIO** [comment]
Closing now that Adam has added tests.
