### ISSUE TITLE
HLR v2: green buttons to action links

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#31699]
## Description

Design intent review feedback recommended to change all green buttons to an action links

## Tasks

- [ ] Change all green buttons to action links

## Definition of done

- [ ] All tasks complete
- [ ] All test passing
