### ISSUE TITLE
Collaboration Cycle - Implement scheduling tool

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31690]
## Problem Statement 
The Collaboration Cycle scheduling process is tedious and complicated. We currently request a date/time from the VFS team, but it is Product Supports responsibility to:

1. Verify the date/time is available
2. Verify the date/time is within the appropriate window
3. Create the meeting invite
4. Invite VFS team members
5. Invite Platform team members
6. Include the github link in the invite
7. Include Zoom information in the invite
8. Ensure that the Platform Collaboration Calendar timeslot is reserved

How might we improve upon the scheduling process to increase efficiency and place accountability with the VFS team?

## Hypothesis or Bet
If we implement a scheduling tool in the Collaboration Cycle, then Platform teams will not be burdened by the scheduling process.

If we implement a scheduling tool in the Collaboration Cycle, the VFS teams will be accountable for scheduling their own reviews.

## We will know we're done when... ("Definition of Done")

- [x] We have completed research and located an appropriate scheduling tool for our needs.
- [x] We have identified how our current process will be impacted by use of the scheduling tool. 
- [x] We have piloted the process with 1 Collaboration Cycle touchpoint.
- [x] VFS teams are able to follow our guidance regarding use of the scheduling tool.
- [x] Platform Website, github tickets and operational docs on Confluence are updated for:
   - [x] Staging Review
   - [x] Midpoint Review
   - [x] Design Intent

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
November 1, 2021

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [x] Usability test (See [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31702)) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching - N/A
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD - N/A

### ... documented?

- [X] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [X] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [X] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [X] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [X] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [X] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings) - **N/A**

### ... measurable

- [X] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. - See [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31702) for success metrics. 
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [X] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. - N/A for a small initiative

### Documentation
* **`PRODUCT_NAME`**: Collaboration Cycle
* **Product Outline**:  [Collaboration Cycle Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748926486/Collaboration+Cycle+Product+Outline)
* **README**: [Collaboration Cycle on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
* **User Guide**: [Collaboration Cycle operational guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: N/A

### Measurement

* **Success metrics**: See Release plan
* **Release plan**: [Collaboration Cycle - Implement scheduling tool: Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31702)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
