### ISSUE TITLE
KMS automatic key rotation and record re-encryption

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#31691]
## Issue Description
KMS keys were created for vets-api with automatic rotation enabled. Although, the keys will rotate automatically, we will still need to re-encrypt the existing data with the new key (on a yearly basis). From the AWS [docs](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) "However, automatic key rotation has no effect on the data that the KMS key protects. It does not rotate the data keys that the KMS key generated or re-encrypt any data protected by the KMS key, and it will not mitigate the effect of a compromised data key." 

A recurring job will need to created and run on the one year mark to re-encrypt the existing data. I believe that the old key will still be able to decrypt the data and we will need to look into some automated cleanup of old keys, as we are charged a fee for each KMS key. See [docs](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) for further info.

---
## Tasks
- [x] Set up automatic key rotation
- [x] Remove previous_key from the models?
- [x] ~~Create a job that will run on a yearly basis to rotate records~~ Job is created but will have to be kicked off manually 
- [x] Look into automatic cleanup of old KMS keys
- [x] Look into how/if old KMS keys can decrypt records during rotation
- [x] Update VSP and VFS facing documentation related to Lockbox and rotation
- [x] Remove Slack reminder for manual key rotation
- [x] Create new slack reminder for the rotation process
