### ISSUE TITLE
HLR v2: Add inline prefilled address, phone and email elements

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#31700]
## Description

Design intent review feedback recommended not using the current profile modals and use inline prefilled address, phone and email form elements

## Tasks

- [ ] Add inline address to contact info page
- [ ] Add inline email to contact info page
- [ ] Add inline phone to contact info page

## Definition of done

- [ ] All tasks complete
- [ ] All test passing

**Comment by Mottie** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/32168 for discovery work using the new list loop method.

**Comment by Mottie** [comment]
Done. Feature flag enabled in staging.
