### ISSUE TITLE
Find a VA Form:  Update modal mock-up with finalized copy

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31708]
# Update modal with finalized copy

## Tasks
- [x] Update the mockup created in #29704 to reflect copy provided by Beth Potts in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30675#issuecomment-945160596) 
- [x]  Post links to Sketch files in this ticket.  

## Acceptance Criteria
- [ ] Sketch mockups for Find a VA Form PDF modal will be updated with final copy
- [ ] Links to sketch mockups will be added to this ticket.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @callen2563!  The link to the Sketch file is saying it's private.  Is there another way to post the link for viewing only?
