### ISSUE TITLE
[EKS] Loki canary for eks clusters

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#31704]
## Description
Install loki canary on our eks clusters to capture performance of loki logging

https://grafana.com/docs/loki/latest/operations/loki-canary/ 

---
## Tasks
- [x] create ecr repository for loki canary image
- [x] create new github repository and github actions for mirroring image and updating manifests 
- [x] deploy loki canary to dev cluster and send metrics to datadog
- [x] deploy to the rest of the clusters if all goes well
- [x] analyze metrics and create monitors/dashboards in datadog if needed
- [x] quick documentation

## Acceptance Criteria 
- [x] Loki canary deployed to all clusters with appropriate metrics and monitors in datadog

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
loki canary now deployed to all clusters 
![image](https://user-images.githubusercontent.com/76792875/140835496-dd2e54a1-7ad2-47cb-bf4e-bc2559d01991.png)

**Comment by mleclerc00** [comment]
Github actions now in place (mirror to ecr and update manifests) to allow both auto updates to dev/staging on merge, and workflow dispatch to update everything else.

https://github.com/department-of-veterans-affairs/vsp-infra-loki-canary/actions

**Comment by mleclerc00** [comment]
Datadog dashboard created https://app.datadoghq.com/dashboard/5v9-bwq-xjk?from_ts=1636588486654&to_ts=1636590286654&live=true

**Comment by mleclerc00** [comment]
Two datadog monitors in place

- Alert on high latency from the amount of time it takes to inject log and then find it
   https://app.datadoghq.com/monitors/54198308
  
- Alert on high percentage of missing logs
  https://app.datadoghq.com/monitors/54198309

**Comment by mleclerc00** [comment]
Confluence page https://vfs.atlassian.net/wiki/spaces/OT/pages/1975353384/Loki+Canary

**Comment by mleclerc00** [comment]
Readme https://github.com/department-of-veterans-affairs/vsp-infra-loki-canary/blob/main/README.md

**Comment by jbritt1** [comment]
Went through both Confluence doc and repo README, all looks great to me. Consider this reviewed. Great work Matt!
