### ISSUE TITLE
Stakeholder introduction

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3170]
# Stakeholder Interviews

### Story
As an Product Manager, I want to be able to conduct stakeholder interviews to define a project road map and create items for the BAM backlog

### Tasks
- Meet with Steve Kovacs to continue current conversations with stakeholders
- Meet with Steve Kovacs and Identify the stakeholders
- Document finding and present to team
- Meet with Kevin L. Quitmeyer Dr of IT at DLC
- Meet with Andrew Fichter Lighthouse

### Acceptance Criteria
- [X] Present to team the VA stakeholder
- [X] Document findings into a research document
- [ ] Add findings to the discovery research presentation for team/stakeholder(s)
- [X] Update conversation guide

#Next Steps
--
- [ ] Set up stakeholder meeting with design team members
- [ ] Set up stakeholder meeting with dev team members

#Blocker
--
N/A
