### ISSUE TITLE
DOCUMENTATION sub-domain usage for translated content

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#31706]
## Description

Document using a sub-domain for translated content in the future.

## Tasks

- [x] What does a sub-domain usage look like?
- [x] What infrastructure is needed?
- [x] How is DNS handled?
- [x] How are users / access managed for this sub-domain?
- [x] Benefits and drawbacks of using a sub-domain

## Acceptance Criteria

- [x] Documentation has been uploaded to repository
