### ISSUE TITLE
[Research] Pre-check-in research report

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#31715]
## User Story
- As a product team, we want to document and share the findings from the usability test on pre-check-in.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-plan.md)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/conversation-guide.md)
- Synthesis for this report completed in ticket [#31639]
(https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31639).

## Description
A research report detailing findings and design recommendations from the usability study on pre-check-in.

## Reference Materials
- Review [Platform research website](https://depo-platform-documentation.scrollhelp.site/research-design/) and [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [x] Update the ~~[research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md) document~~ and [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [x] Create necessary issues/tickets that address findings in coordination with Corey
- Schedule readout sessions with 
  - [x] Stakeholders (talk to Patrick about when to do this)
  - [x] team (either via Slack or Zoom meeting) - include CHIP and VSE GUI representatives
  - [x] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)
- [x] Post appropriate findings for the reusable component to ticket [30373](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30373) for the profile team.

**Comment by kristenmcconnell** [comment]
I confirmed with Naomi that we only need to update the research repo now. The research history file is being sunset.

**Comment by niradatta1** [comment]
Link to markup page:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-findings.md

**Comment by niradatta1** [comment]
Link to PDF of research findings: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/Pre-check-In%20Usability%20Research.pdf

**Comment by niradatta1** [comment]
Scheduled presentation at weekly Design call on December 13th. Reached out to Patrick to confirm stakeholder meeting schedule.
