### ISSUE TITLE
Changes to Facility Locator search results for screen reader accessibility (short term)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#31714]
## Issue Description
During screenreader usability sessions, the meaning of the letter and number combo in search results (representing the map pin and the mileage) was not clear to Veterans. These Veterans were also not able to access the map, which might have provided a small context.

Current experience: When a user selects Facility type = Community Providers (in VA's network), the laundry list of options presented to users is confusing, particularly for those without visual cues.

@nicko-amida worked with the accessibility team on this feedback for Facility Locator search results - from [the comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27452#issuecomment-946825202) in [DESIGN] Screenreader users need context for relative location of FL search results (letter/number combo), #27452

## Quick wins
The following changes could be made in the short term to add value and improve on the existing experience

### Tasks

- [ ] Add an `h2` heading to the map (ie. "Facility locator interactive map" - see map screenshot above); use sr-only to only make it visible to screen readers
- [ ] Add "." and an sr-only class to locations markers (ie. "A.") to introduce an audible pause between the letter and results heading
- [ ] Include pagination as a landmark element (ie. use `nav` or relevant semantic elements to describe it)
- [ ] Remove unnecessary empty `span` classes
- [ ] Ensure pagination controls are in focus order
- [ ] Use aria-labelledby to describe pagination (ie. "Location results pagination")

### Accessibility resources which might be helpful
- [Accessible pagination](https://www.a11ymatters.com/pattern/pagination/)
- [Ally navigation](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination)

Longer term effort/changes will be added to a subsequent issue

**Comment by mmiddaugh** [comment]
@joshkimux @AngelaFowler82 question from grooming this morning
When should the aria-labelledby announce the pagination? (i.e. when it receives focus, before the first search result, another place...?)

**Comment by joshkimux** [comment]
@mmiddaugh `aria-labelledby` is just a label, so there's nothing we need to worry about in terms of timing. Basically, if a screen reader user tabs to/jumps to the pagination, it will read out to them as "Location results pagination" or something along those lines instead of an unlabelled element.

I can't remember the history on the recommendation of `aria-labelledby`, but it doesn't look like there's an actual title on the page that can be linked to it. My gut reaction is to use `aria-label` instead which doesn't depend on a separate, existing element on the page to label it. For example, placing the pagination within a `nav` with an `aria-label="location pagination". When a user lands on it, it will read out as "location pagination, navigation."

**Comment by laflannery** [comment]
Pulled out the relevant items/recommendations for Q2 2023 iteration that is beginning
