### ISSUE TITLE
Move Lengthy 1900 Work to a Job

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#31737]
## Background
This is part of the solutions for epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/8278

The FE request shouldn't take a long time (and even 504 timeout), so we decided we should put work into a background job based on evidence found in grafana charts, specifically for very long BGS response times for finding a Veteran's `va_file_number`

## Tasks
- [x] Move bulky work to a job.

## Acceptance Criteria
- [x] Code and Tests are implemented
- [ ] PR has been approved
