### ISSUE TITLE
[VAMC] Review and validate current active list of all CLC and DOM facilities in all systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31744]
## Resources
[Orphan facilities](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FAnalytics&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91&view=7&q=orphan)
[Production schedule](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FProduction%5FSchedules&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## TASK
Review the CLC/DOM listing and confirm if there are any new facilities, removed facilities.

- [x]  Starting at start of production schedule highlight all systems that have a CLC or DOM
- [x]  Update Orphan list with sites that are closed, still exist and what type, and what is new.

## Acceptance Critriea
- [x] Orphan list is updated with current CLC/DOM listing that can be used to assign or track stories.
