### ISSUE TITLE
Need access to Sentry API from CodeBuild job `developer-portal-deploy`

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/va.gov-team#31757]
## Description
Team Okapi wants to be able to create and finalize releases within Sentry using the `sentry-cli` tool within CodeBuild. My understanding is that this job is in a different VPC than Sentry and doesn't have access for that reason.

## Background/context 
https://vajira.max.gov/browse/API-9999
https://dsva.slack.com/archives/CBU0KDSB1/p1634675740150300

---
## Tasks (one of these should suffice)
- [ ] Move `developer-portal-deploy` to the same VPC as Sentry. 
- OR
- [ ] Provide a method of access between the VPCs that would allow API access. The revproxy doesn't appear to support the releases endpoint.

## Acceptance Criteria 
- [ ] Regardless of the method, the CodeBuild job is able to create and finalize releases over the Sentry API

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
