### ISSUE TITLE
[VAMC] Create Lighthouse API csv file for Post Production Systems that went live on October 27th [BA] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31753]
## Story
As a Veteran looking for VAMC facilities and COVID-19 Vaccines on Facility Locator I need the correct URL link, so it will take me to the new VAMC websites.

## Goal
Create a repeatalbe process of creating the Lighthouse API url csv file that will be loaded to VAMC SharePoint for Lighthouse API

## Resources
[Previous Lighthouse API files](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FLighthouse%5FAPI%5Ffiles&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## TASKS
**Transform all system facilities in Post production**
- [x] Create file with these headers (Facility_ID;URL;COVID-19_Vaccine_URL)
- [x] Load unique facility ID, new VAMC Facility URL, and same System URL for each system that have gone live

## Acceptance Criteria
- [ ] .csv file created with required column headers and facility URL information
- [x] All URLs are tested to make sure they are correct
- [ ] .csv file is loaded to VAMC Sharepoint File (Lighthouse API redirects)
