### ISSUE TITLE
Re-Create the Testing Tools Team Standup

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31763]
# Description
The stand-up meeting invite routes people to a waiting room and has an out of date agenda.

## Tasks
- [ ] Remove the existing stand-up meeting
- [ ] Create a new stand-up meeting on MWF with
  * Update agenda including link to [sprint board](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/board?epics:settings=noEpics&notFullScreen=false&repos=133843125&showPipelineDescriptions=false&showEpics=false)
  * Update agenda to indicate we will walk through the sprint board and review ticket updates
  * Queue up additional work into sprint backlog and assign as needed
- [ ] Ensure the stand-up meeting does not have a waiting room and automatically permits attendees
