### ISSUE TITLE
Look into routing PagerDuty alerts from Sidekiq to the appropriate team

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#31761]
## Issue Description
All PagerDuty alerts get sent to whoever happens to be on-call at that time. However, if an alert is related to a backend issue and the person on-call is a frontend person (or vice-versa), they will likely not be able to resolve the issue and will need someone from the backend to deal with it. Ideally we would like to route specific types of alerts (backend,frontend,etc.) to the appropriate dev/team. This ticket will specifically focus on routing alerts from Sidekiq to the backend team. 

Any changes that are made to alerting will ultimately need to be made by someone on the Devops team.

---
## Tasks
- [ ] Determine the criteria that PagerDuty should use to route a particular type of alert (all Sidekiq alerts go to backend team?)
- [ ] Setup teams within PagerDuty for the purpose of routing alerts

## Acceptance Criteria
- [ ] PagerDuty alerts from Sidekiq are getting routed to the backend team
---

**Comment by thilton-oddball** [comment]
I was going to create a separate ticket to address the issue of adjusting the alert thresholds for the ones that typically resolve themselves within a short amount of time. As far as scoping it down to just Sidekiq alerts, I can certainly make that change, as that seems to be one of the biggest offenders.
