### ISSUE TITLE
Determine Deltas for My Docs (EBN) and CST (VA.gov)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#31773]
## Background
We need to determine what functionality gaps exist between the My Documents feature in eBenefits and the Claim Status Tool in VA.gov so that we can address any outstanding functionality.

## Considerations
- Not every file in the Veteran's eFolder is applicable for the Veteran to view.
- Downloads seems to be the largest issue
- Can we simply mirror the gaps in EBN on to VA.gov?
- Check in with Cameron Testerman on BAM2 to see if they did any work here
- Keep in mind that there is a place for standardized letters from the VA
- Consider the profile as a potential home for the Veterans docs (IA question)

## Tasks
- [x] Review both features
- [x] Document deltas for both
- [x] Share with team
- [ ] (Jason) find a stakeholder
- [x] Check in with Mikki

## Acceptance Criteria
- [x] Results have been shared with the team
- [ ] Mikki's thoughts have been documented, if available

**Comment by sporeboy** [comment]
Draft Github [document available here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-my-documents/research-design/mydocs-feature-comparison.md)

**Comment by sporeboy** [comment]
Feature details and comparison table implemented...

**Comment by sporeboy** [comment]
Github doc [posted on Slack.](https://dsva.slack.com/archives/CLY6Q69RV/p1635884418053300)

**Comment by sporeboy** [comment]
Checked-in with Mikki... No IA to document as yet.

**Comment by sporeboy** [comment]
Quick intro of the feature given to Mikki. She will consider how the various "documents" pages work together. She mentioned something the new Education team is working on. No initial feedback.
