### ISSUE TITLE
[Monitoring] Sidekiq alerting tasks

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#31777]
## Description

- Sideqik alarms are duplicated in both prometheus/alert manager and datadog (though not quite 1:1)
- Oncall is getting pagerduty alerts fired off at undesirable hours for something that is not actionable  

## Background/context 
- https://dsva.slack.com/archives/CJRQ85PQB/p1634736874050000

based on the slack conversation I will be taking the following actions

---
## Tasks
- [x] Remove prometheus/alert manager components and make sure they are all covered in datadog
- [x] Redeploy prometheus
- [x] Stop sending queue alerts to pagerduty (only slack)
- [x] Adjust alert thresholds as needed

## Acceptance Criteria 
- [x] Make sure that the desired messages are being sent to slack/pagerduty as desired

**Comment by dginther** [comment]
verified that we have the proper alerts.
