### ISSUE TITLE
Address UI Tweaks in Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3177]
## Story
As a Veteran using Rated Disabilities, I want to be able to see page information consistently so that information and instruction is as clear as possible.

## Tasks
- **Footer margin:** The last card and the footer feel a little tight.
- **Border on new card sections:** This needs to be removed.
- **H tags** need updating

## Considerations
[Mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/)

## Acceptance Criteria
- [x] An appropriate amount of space has been added between the last card and the footer.
- [x] Dark border is removed.
- [x] H tags are addressed

**Comment by sporeboy** [comment]
Made some revisions to the HTML and CSS classes in the RD JSX files... Pushed branch 3058-rated-disabilities-ui-updates.

- Reconciled typography
- Reduced utility classes
- Light text revisions
- Minor size and spacing fixes
- Addressed responsiveness
- Added placeholder tabindex to cards
- Re-styled cards (left functionality/logic alone)

**Comment by sporeboy** [comment]
[Uploading... Screen Shot 2019-11-08 at 9.56.45 AM.png ]
