### ISSUE TITLE
Put examples in the speakernotes for "Intro to Google Analytics Training Deck" 

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#31786]
## Issue Description
When we're giving the GA training, we want to be able to point to examples so we need them in the speaker notes of the deck.  
---
## Tasks
- [x] Add speaker notes to PPT
- [x] Make sure the internal documentation links to the updates

## Acceptance Criteria
- [x] Examples are included in training deck speaker notes
