### ISSUE TITLE
Implement Design Changes for Rep (Based on FE feedback)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#31787]
## Tasks
- [x] Update workflow to include veteran info and contact info for unauth and summary page
- [x] Update veteran and contact info to use form fields instead of accordions
- [x] Update selector type on search results
- [x] Update chapter titles
- [x] Add summary/confirmation page
- [x] Update with content from Beth

## Acceptance Criteria
- [x] Workflow has been updated
- [x] Selector Type has been updated
- [x] Summary page has been added
- [x] Content has been updated

**Comment by candy-gcio** [comment]
These are part of the same sketch file as the v1 wireframes, but these links will take you directly to the updated v2 versions.

- [workflow](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/L0d9ndD)
- [mockups](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/p/47673127-1304-4E6D-8CBE-C8A160E00A55)
