### ISSUE TITLE
Feature Request Process: Create feature request Github issue form

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#31799]
## Issue Description
Convert the [feature request template](https://vfs.atlassian.net/l/c/Co1fUBRa) in Confluence into a Github issue form.

---
## Tasks
- [x] Copy template content into a markdown file.
- [x] Work w/ Github repo admin to turn the markdown file into a issue template.
- [x] Manual QA to validate form works as expected

## Acceptance Criteria
- [x] Users can submit feature requests to the Platform using a Github issue form.
- [x] Information from each feature request is stored in a feature request ticket.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jchasia-adhoc** [comment]
Confirm this link in user guide open template correctly: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jchasia-adhoc&labels=platform-feature-request&template=platform-feature-request.yml&title=%5BFeature+Request+%5BFeature-Name%5D%3A

**Comment by jchasia-adhoc** [comment]
Feature request issue form: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-feature-request.yml

**Comment by jchasia-adhoc** [comment]
Feature request form template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-feature-request.yml
