### ISSUE TITLE
[FE] No Address Display Bug

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31794]
## User Story

> these should be why the veteran cares, and the veteran gets out of it.

As a veteran,  I should be able to see that I don't have an address. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

For the address field on the demographics (and Next of Kin),  we need to know what is the minimal data for displaying the address vs a `Not Availlible` message.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Figure out minimal data
- [ ] Implement fix
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by kristenmcconnell** [comment]
This makes sense to me. 

I don't know the answer to "do you know if there is a scenario where we will get address fragments that don't contain at least those 4 fields?" The CHIP team would probably know the answer.
