### ISSUE TITLE
[MCP] Draft content for new copay bill notifications

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#31798]
## Issue Description
The release of MCP will be followed up by VANotify notifications when a new copay statement is available on a Veteran's account. 

Considerations:
- Veterans may visit multiple facilities and get multiple statements a month, potentially staggered across the month. Ensure that these statement notifications are not intrusive to the Veteran.
- We may not show much data in the emails
- Evaluate the pathway between the notification(s) and the portal or statement

---
## Tasks
- [x] Draft content for MCP notification(s)
- [x] Open a content review request 

## Acceptance Criteria
- [x] Create draft of content for MCP notification(s) and link to this ticket
- [x] Open a content review request ticket and link to this ticket

**Comment by rileyorr** [comment]
- Drafted content has been added to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/notifications/new-copay-statement.md))
- Content review request has been submitted ([link](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/32315))
