### ISSUE TITLE
[UX] Contact Information Editing Submitted to Experimental Design System

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#31808]
# Description
The ability to editing contact information within a form and have it affect a Veteran's overall profile is something new for the design system. As a result, we need to submit this new pattern to the experimental design system.

This work is dependent upon the final design created in #33148.

# Tasks 
- [x] Complete step 1 & 2 listed on [the "Contributing to Design System" page.](https://design.va.gov/documentation/contributing-to-the-design-system)
- [x] Coordinate submission with @kevinstachura, because Claims and Appeals needs to submit the same pattern. Make sure both use cases are understood in the submission.

# Acceptance Criteria 
- [ ] The Experimental Design System Request ticket is submitted.

**Comment by kristenmcconnell** [comment]
I removed the task list for now from this story, because initial research findings found there was no difference in usability between the form and task list solution. Upon completed synthesis, we may need to add a different story if the findings change.

**Comment by kristenmcconnell** [comment]
@zach-park

**Comment by kristenmcconnell** [comment]
@julieadair1 @jparker0425 Since editing was just de-prioritized, we should move this ticket out of this sprint. It only becomes important when we edit.

**Comment by julieadair1** [comment]
@kristenmcconnell I moved it out of the sprint.  
cc: @jparker0425

**Comment by julieadair1** [comment]
@kristenmcconnell - this one is related to pre-check-in correct?

**Comment by kristenmcconnell** [comment]
@julieadair1 It is.

**Comment by kristenmcconnell** [comment]
Found [an already existing design system ticket on this topic](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/305), so I will add our additional documentation there.

**Comment by kristenmcconnell** [comment]
[Added this documentation to the already existing ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/305):

The Check-in team has been working on a pattern for reviewing, then editing contact information within a workflow/form. We have been syncing with the VA.gov Profile and Claims and Appeals teams throughout our process.

VA.gov Profile completed discovery research on this topic ([research findings link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/discovery/improving-editing-mid-task.md)). Within their research, they found that multiple VA tasks have this need, including
- Managing notification preferences
- Filling out a form (such as notice of disagreement or pre-check in questionnaire)
- Checking in for an appointment at a VAMC
- When scheduling an appointment 

Across numerous user research studies, check-in verified the need to review/update contact information as well as usability tested an editing pattern. 
-  Staff explained that keeping this information up-to-date was important, because it impacts where medications are sent, “patient safety,” accurate beneficiary travel calculations, wellness checks and more.   ([More about the value to staff can be reviewed in this research study.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-UAT/research-findings.md))
- VHA Directive 1604 also exists, which specifies the review and collection of this information frequently.
  - Staff used this to help explain why a review of contact information is currently completed during kiosk and in-person check-ins.
- Veterans also want to edit this information during check-in.
  - 50% of participants wanted to edit in [this research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/mvp-usability/research-findings.md).
  - This was a key finding [within another study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/phase2-usability/research-findings.md): Veterans want to be able to update their contact information with this check-in workflow; however, they accept the current workflow with the question “Do you need to update any information?” and directions to talk to staff to complete updates.
  - We also usability tested a specific editing pattern/design [within this study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/pre-check-in-usability/research-findings.md). Even though the design utilized modals, the pattern tested well.  We had been syncing with the Claims and Appeals team on what the actual pattern looks like.
  
After speaking with @rtwell  and accessibility, we adjusted the design from modals to pages. We also changed the labels (such as Mailing address) on the review page to bold body copy from H3. Accessibility recommended this change, so the review section will be read together for a screenreader. The final design pattern that we are proposing is available for [review on Sketch.](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/5BCAB931-5EBD-4208-BDA4-592B768DE26F)

cc @andaleliz, @kevinstachura, and @chrvalla
@caw310
