### ISSUE TITLE
Feature Request Process: Create Github Project Board for Feature Requests

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#31800]
## Issue Description
As a Platform Crew, VFS, or OCTO-DE team member, I want to view all feature requests submitted to the Platform and their status in a single place. 

---
## Tasks
- [x] Investigate creating Github Projects
- [x] Setup project board
- [x] Manual QA to validate project board works as expected.

## Acceptance Criteria
- [x]  The Platform has a customer-facing kanban board showing status of feature requests.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jchasia-adhoc** [comment]
Feature request project board: https://github.com/department-of-veterans-affairs/va.gov-team/projects/42
