### ISSUE TITLE
Remove vanity phone number from health care page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31801]
## Issue Description
We have a 877-222-VETS phone number listed on the [Where you'll go for care](https://www.va.gov/health-care/about-va-health-benefits/where-you-go-for-care/) page that needs to be changed to our current style with an aria label. 

It's in the accordion "What should I do if I move?"

## Tasks
- [x] Delete vanity number and replace with standard 10 digits within an aria label per stye guide (Selina)
- [ ] Review and publish

## Acceptance Criteria
- [ ] Vanity number no longer on live site

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
