### ISSUE TITLE
[Design] Profile: Personal Info Revision - Update designs to reflect current design pattern

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31810]
## Issue Description
Update Profile Personal Information Revision Mockups to reflect current design patterns.

- Original mockups: https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565
- Latest copy for field labels and options is located in [GitHub product documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- Examples of the current design pattern in production can be seen here:  https://staging.va.gov/profile/personal-information
and [here in Sketch](https://www.sketch.com/s/f7733912-f69e-4fb9-aa95-256f2cce5ce1).
---
## Tasks
- [x] Update mock-ups to reflect current Profile design pattern in production
- [x] Update headers on mockups to match what is currently in production (lighter blue heading with disability rating when applicable).
- [ ] Mock up the mobile versions of these pages
- [x] Make it clear that selecting the "other" option makes the accompanying text input field required  -- see this [mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/MyzeRwb) and this [content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#edit-state---required-other-fields).
- [x] Mock up default unanswered ([blank](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---blank-state)) state that includes "Edit your profile to..." [Examples](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31237#issuecomment-947850140)
- [x] Add "Prefer not to answer" option to Pronouns and Sexual orientation sections
- [x] To prevent confusion for screen reader users, remove the gray "Personal Information" heading that appears immediately below the "Personal Information" H1.  There should be a pattern we can follow for this.

## Acceptance Criteria
- [x] Mockups will reflect current Production design pattern
- [x] Header on mockups will be updated to match what's currently on Production
- [ ] Mobile mockups will be created
- [X] Mockups will have incorporated feedback from design intent

---

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Noting that we are moving this to Sprint 60 and assigning to new Designer, Christina.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske I added a task and acceptance criteria item for updating the header on the mockups.
