### ISSUE TITLE
[FE] Handle Zip Code

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#31811]
## User Story

As a veteran I should see my correct zip code. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The zip code from CHIP is coming back in various formats, we need to display only the first 5 digits of the zip code.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Truncate the zip code to be only the first 5 digits. 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
