### ISSUE TITLE
[Content] Profile: Personal Info Revision - possibly provide info on how VA will use info

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31816]
## Issue Description
In the design intent review, concerns were raised about why the VA would need some of the information. To that end, we want at least one FAQ to address why we ask for this information.  Christina Gednalske - can you and @DanielleThierryUSDSVA work together to determine if we need one FAQ or more than one FAQ?

---
## Tasks
- [ ] Create at least one FAQ addressing why we ask for personal information in the Profile
- [ ] @DanielleThierryUSDSVA and Christina Gednalske work together to figure out if we need one FAQ or more than one FAQ? If we need an FAQ to answer this for each field, we'll have to update how we handle FAQs in the profile because, right now, we only have them applying to whole sections and not individual fields.
## Acceptance Criteria
- [ ] At least one FAQ to address why we need personal information in the profile
- [ ] A determination is made as to whether we need to answer for each field
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Closing this issue and replacing with a Content and IA request specific to FAQs
