### ISSUE TITLE
[Design] Profile: Personal Information Revision - update Prototype and Sketch files labels for limited-character fields

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31815]
## Issue Description
-  Prototype currently references a 25 character limit.  If this turns out to be a different value due to MPI constraints, the Sketch files and prototype needs to be updated accordingly. 
 https://dsva.slack.com/archives/C909ZG2BB/p1633634838024700 

---
## Tasks
- [x] Update Prototype to reflect actual character limits as deemed by MPI
- [x] Update Sketch files to reflect actual character limits

## Acceptance Criteria
- [x] Prototype will show the correct character limit for each text field
- [x] Sketch files will show correct character limit for each text field.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Noting that this will be determined by backend/database constraints.

**Comment by MarciMcGuireGCIO** [comment]
We are meeting to discuss integration with MPI 12/1 and should be able to get field size constraints at that point.

**Comment by MarciMcGuireGCIO** [comment]
Blocked until we get field specs from MPI

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO - this is finished on Sketch files as well as Prototype!

**Comment by MarciMcGuireGCIO** [comment]
Noting that we learned via email that the Preferred Name field has a db limit of 100 char, Gender Identity is 255 and Sexual Orientation is 255.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske -- you already completed this, right?

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO correct! All limited-character fields have been updated.
