### ISSUE TITLE
[Design] Profile - Personal Info Revision: Update mockups to reflect finalized copy and IA feedback

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31822]
## Issue Description
Modify Profile Personal Information Mockups to reflect content changes requested by content team. 

---
## Tasks
- [ ] Update _Read-Only State_ mockup so that the field order and field labels match those listed in the front copy documentation.  

**Read-Only State links**
- [Default state mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/Myd9jnw)
- [Read-Only state copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---read-only-state)

<hr>

- [ ] Update _Blank State_ mockup so that the field order and field labels match those listed in the front end copy documentation.  Blank state reflects what displays when no value for a field currently exists in the Veteran's data
 
**Blank state links**
- [Blank state mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2)
- [Blank state copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---blank-state) 

<hr>
 
- [ ] Update _Edit State_ mockup so that the field order, field labels, edit instructions, and field selection options match those listed in the front end copy documentation.   Work with Danielle Thierry in Content on the order in which the radio button and checkbox selections should be listed.

**Edit state links**
- [Edit state mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw)
- [Edit state copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---edit-state) 

<hr>
  
- [ ] Update _Edit State - Required Other Fields_ mockup so that the field order, field labels, edit instructions, and field selection options match those listed in the front end copy documentation.   Work with Danielle Thierry in Content on the order in which the radio button and checkbox selections should be listed.

**Edit State - Required Other Fields links**
- [Edit State - Required Other Fields mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw)
- [Edit State - Required Other Fields copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#edit-state---required-other-fields) 

## Acceptance Criteria
- [ ] Read-Only State field order and field labels match those listed in the front end copy documentation
- [ ] Blank State field order and field labels match those listed in the front end copy documentation
- [ ] Edit State field order and field order, field labels, edit instructions, and field selection options match those listed in the front end copy documentation.
- [ ] Edit State - Required Other Fields field order, field labels, edit instructions, and ield selection options match those listed in the front end copy documentation.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO There are more changes than I'd expected and want to check in on those. Since Kevin's last mockups, is it correct that there were changes made to content throughout the edits states as well? For example, the entirety of the Gender identity edit state was changed (i.e: Male, Female, Transgender Male, etc. changed to Man, Woman, Transgender Man, etc.) We hadn't directly discussed this, so I want to make sure I'm not undoing older changes.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske Great question!  Kevin did not have bandwidth to make all of the content changes to his original mockups, so any language listed in [front end copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md) that does not match up with the mockups will need to be updated.  Let me know if you have any other questions!

**Comment by cgednalske** [comment]
Ok! Thank you, @MarciMcGuireGCIO! 
One more question regarding this that I've just noticed. In FE copy documentation, some copy for fields in the first state where information has been filled out (_Gender identity: Female_ and _Birth sex: Female_, for example) are different than the editable state (_Gender identity: Man, Woman, Transgender Man_, etc.). Should one of these be altered to match the other?

**Comment by MarciMcGuireGCIO** [comment]
Whew; good catch!  Let me correct that.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske I updated the default state value for Gender identity to "Woman". but did not change the Birth sex value as that currently comes from the MPI database, and I think that Male and Female are the only valid options currently.  We can always update that later once we engage with MPI and find out if that has changed.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske I added a comment on the Edit State and Edit State - Required Other Fields for you to work with Danielle Thierry on the order in which the options should appear.
