### ISSUE TITLE
AFS CT Redesign: Redefine Compare Interaction - 2 of 2 Stories

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#31820]
## Issue Description
Per OCTO Redesign, GIBCT's comparison functionality should mimic the same functionality.

To see an example of how this is done:
1. Go to https://www.medicare.gov/care-compare/
2. Scroll down and click Hospitals
(Start here for mimicking of compare functionality)
3. In the Search field, enter a valid search term (in this case Street, ZIP code, city, or state) and click on the correct city's link when prompted
4. Click **Search**

Then, On the Search results page:

6. Click **Compare** on any option
7. Validate a blue banner with the selected choice is presented above the list of options / map and remains in place until user is ready to compare the selections.
8. Select two more options - validate each option appears on the blue results banner above
9. Validate that all remaining Compares have been disabled when the maximum number of selections is made.
10. Remove one of the selected and validate that the Compares are re-activated. 

Once the maximum number of compare items is selected, all other Compare buttons are grayed out . Scroll down and verify users are not allowed to add more selections [up to 3 only] unless they deselect/remove one or more of the 3.

Select **Compare** in the blue banner at the top to validate a results table (rows and columns) are presented with all 3 selected choices' data

The idea is to mimic the same functionality for GIBCT.

---
## Tasks

- [ ] When clicking Compare, add institution in the Blue Banner (up to 3 ONLY)
- [ ] When fewer than 3 Compare selections have been made, all Compares are active.
- [ ] Deactivate (gray out) all remaining Compares once 3 selections have been made
- [ ] Display results in a table for compare results (up to 3 ONLY)
- [ ] 

## Acceptance Criteria
- [ ] User can select up to 3 institutions to compare
- [ ] User can select and deselect institutions up to a masximum of 3 at a time
- [ ] When user has selected 3 institutions, the other Compares are grayed out
- [ ] Once 3 selections have been made, and user subsequently removes one from the banner, all disabled (grayed-out) Compares are re-enabled
---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontool`, `afs-education`)
- [ ] **Labeled with Practice Area** (`backend`, 'frontend')
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mrblanco1** [comment]
Per Joe, this story should remain in the Icebox until further notice. 3/17/2022

**Comment by mrblanco1** [comment]
This work will not be started. AFS HCD submitted recommendation to VA EDU. They will decide how they want to proceed.
