### ISSUE TITLE
VFS Team Onboarding next steps: VSA Public Websites

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#3183]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [ ] Attend general onboarding meeting
- [ ] Request [Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md)
- [ ] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [ ] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [ ] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [ ] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [ ] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [ ] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [ ] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [ ] Designers: Attend breakout session
- [ ] Engineers: Attend breakout session
- [ ] Full team: Attend the Discovery and Logistics Workshop
- [ ] Front-end Engineers: Attend deep-dive session
- [ ] Back-end Engineers: Attend deep-dive session
- [ ] PM, Designers and Content Writer(s): Request content and IA intro (Contact: Megan Kelley & Mikki Northius, VSP)
- [ ] PM and Front-End Engineers: Request analytics intro (Contact: Joanne Esteban, VSP) 
- [ ] PM Request 508 intro (Contacts: Jennifer Strickland, VSA & Trevor Pierce, VSA)
- [ ] PM and Engineers: Request load testing, privacy, and security intro (Contact: Andrew Gunsch, Engineering Lead VSP)
- [ ] PM and Engineers: Request ATO intro (Contact: not sure)
- [ ] PM, designers, and content writers: Request IA intro (Contact: see above)
- [ ] Content writers: Become familiar with [content resources and best practices](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/content) 
- [ ] Public Website team: Review[ team repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites) and [2020 priorities and strategy deck ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Public-website-2020-priorities-vision-with-Drupal-040220.pdf)

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by Karak888** [comment]
closing this Epic @LouCarlozo63 will be onboarded by GCIO separately

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @lunascoop @stephorkandatx @johnhashva - In the above checklist, could we add 2 items for: 

[ ] Content writers: Become familiar with [content resources and best practices](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/content) 

[ ] Public Website team: Review[ team repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites) and [2020 priorities and strategy deck ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Public-website-2020-priorities-vision-with-Drupal-040220.pdf)

**Comment by jilladams** [comment]
Public Websites team onboarding has changed with transition to Sitewide contract & A6. Closing.

**Comment by FranECross** [comment]
@jilladams @MarciMcGuire @michelle-dooley This epic was closed, but there are still a bunch of its associated tickets open in our backlog. Do you know if those can just be closed, or transferred to a different team? Thanks in advance!

**Comment by jilladams** [comment]
AFAIK those tickets can all be closed. If you look through, they're all noting onboarding resources that the previous Public Websites team should read / review. Our docs are updated for modernity and the notes here are likely long outdated.
