### ISSUE TITLE
[VAMC] Provide regular communication to all Stakeholders through Office Hours, status meetings, an support tickets [VAMC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#31839]
## Story
As a CMS editor I need direction support and status updates, so I can get the training I need, understand the schedule, and prepare the system website for full production.

## TASKS
Provide:
- [X] Weekly office hour meetings
- [X] Weekly training meetings
- [X] Bi Weekly VISN meetings to new VISNs in roadmap
- [X] Daily support for CMS support tickets.

## Acceptance Criteria
- [X]  All meetings, and support calls are presented and responded to during sprint.
