### ISSUE TITLE
[Debt Portal] Create alert for PDF downloads

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#31841]
## Issue Description
DMC is uploading the wrong letters to VBMS so we need an alert informing users of incorrect information about their debts. Implement an alert on the download page for debt letters according to the [mock](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/143143182/comment/sitemap?mode=i)

slack: https://dsva.slack.com/archives/CPE4AJ6Q0/p1634752148495600

![Debt Portal - UXPin Preview 2021-10-21 09-06-35.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/e9dc0dee-c883-48ff-9e45-99952973932e)

---
## Tasks
- [ ] implement alert on debt letter downloads page should match [mock](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/143143182/comment/sitemap?mode=i)

## Acceptance Criteria
- [ ] alert should render on the download page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
