### ISSUE TITLE
Add entry to style guide about bulleted lists containing fragments and sentences

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31856]
## Issue Description
We had a user reach out to the style guide group asking for further guidance on punctuation in bulleted lists. We currently don't explain in the style guide what to do if a bulleted list is made up of both fragments and sentences. 

While lists should be parallel (all fragments or all sentences) there are some instances where we have a fragment in a bullet with a follow-up sentence, requiring a period at the end of the first fragment before starting the second sentence. In these cases the fragments in the other bullets of that list should also have a period at the end. This needs to be noted in the style guide. 

## Tasks
- [x] Update bulleted list entry (Randi)
- [x] Review/merge (Beth/Danielle)

## Acceptance Criteria
- [x] Style guide contains updated guidance on bulleted lists

**Comment by RLHecht** [comment]
Changes are live in the style guide. Closing ticket.
