### ISSUE TITLE
Need Access to Kinesis Data Firehose & CloudWatch Metric Streams in AWS to Import Synthetics Metrics to DataDog

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#31867]
## Description
I am attempting to import AWS CloudWatch Synthetics metrics into DataDog. According to the DataDog documentation (https://www.datadoghq.com/blog/amazon-cloudwatch-metric-streams-datadog/) the workflow involves using AWS Kinesis Firehose to import CloudWatch metrics into Datadog. When following the guide and going to the Amazon Kinesis dashboard, I'm unable to send metrics into Datadog using CloudWatch Metric Streams due to a lack of authorization.

## Background/context 
![image](https://user-images.githubusercontent.com/72466113/138324680-ffd96a31-072a-44f4-8454-a06f79549b67.png)

---
## Tasks
- [ ] _Grant access to Ryan.Johnson for Kinesis Data Firehose_
- [ ] _Grant access to Ryan.Johnson for CloudWatch Metric Stream_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
@rjohnson2011 - Without knowing enough about the goal of what you're trying to accomplish, I wonder if there's any value in (or the possibility of) creating the synthetic monitor directly in Datadog, thereby potentially removing the need for an additional integration to manage? 

Forgive me in advance if I'm not up to speed with what you need to do, but just thinking out loud.

**Comment by jhouse-solvd** [comment]
@JoeTice - Let's close this ticket. We can always re-open it, or re-scope based on refined direction. 

Closing.
