### ISSUE TITLE
Find a VA Form:  Detail Page PDF Modal: Update text, add 24 hour cookie

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31873]
## Issue Description
Update the modal text and links to reflect the [content feedback from the Design intent review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-953070611).  

Since we have no way of determining if a user has Adobe Reader DC installed, please add a cookie so that the pop-up only gets displayed one time per day so it doesn't become annoying.

Uses cases are described here.  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md

Specific to this ticket are use cases [D-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-f) and [D-G.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-g)  

---
## Tasks
- [ ] Update the text to reflect what content has provided.
- [ ] Add a cookie to the Detail page template so that the PDF modal is displayed once every 24 hours per user
- [ ] Deploy to Staging behind a feature flag

## Acceptance Criteria
- [x] The modal will reflect the updated text
- [x] The modal will be displayed the first time someone clicks on a link to download a PDF on a form Detail page
- [x] The PDF modal on form detail pages will not display again for the same user until 24 hours have passed.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel we have [updated copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574) for this now, so please take a look and update your estimate if needed.  Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel updated design hot out of the oven -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/32357#issuecomment-959489153 - thanks @callen2563 !! 

![image](https://user-images.githubusercontent.com/73354907/140097456-4c8ac61b-b17c-4822-ab8b-bb60e09d2420.png)

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Ryan suggested a button even though it's outside the standard design pattern, and Angela and Mikki agreed it made for better continuity in the user experience.

**Comment by MarciMcGuireGCIO** [comment]
This is on Staging and working as expected.
