### ISSUE TITLE
Update numbers on Disability Housing Grants for Veterans for fiscal year 2022

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31875]
## Issue Description
We need to update information on our [Disability Housing Grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/) page so that it represents fiscal year 2022. 

Updates need to be made to the following places:

If you qualify for an SAH grant, you can get up to **$100,896** for FY 2021.
If you qualify for an SHA grant, you can get up to **$20,215** for FY 2021.
If you qualify for an SAH grant, you can get up to **$40,637** through the TRA grant program for FY 2021.
If you qualify for an SHA grant, you can get up to **$7,256** through the TRA grant program for FY 2021.

**New numbers for FY 2022**
If you qualify for an SAH grant, you can get up to $101,754 for FY 2022.
If you qualify for an SHA grant, you can get up to $20,387 for FY 2022.
If you qualify for an SAH grant, you can get up to $40,983 through the TRA grant program for FY 2022.
If you qualify for an SHA grant, you can get up to $7,318 through the TRA grant program for FY 2022.

## Tasks
- [x] Reach out to stakeholders for new numbers (Randi)
- [x] Update page with new FY 2022 numbers (Selina)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] New numbers for FY 2022 are live on the site

**Comment by RLHecht** [comment]
@lunascoop I got the new numbers from Raleigh and put them at the top of this ticket. Could you please put them on the page in Drupal and we can publish? Thanks!

**Comment by lunascoop** [comment]
@RLHecht these updated pages are ready for review.

Disability housing grants for Veterans: http://preview-prod.vfs.va.gov/preview?nodeId=750

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published the page. I also changed "Watch" to "Go to" for the YouTube links at the bottom of the page.

**Comment by RLHecht** [comment]
Updates are live. Closing ticket.
