### ISSUE TITLE
Setup Comparison Testing Survey

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#31886]
## Issue Description
As a Content team member, I want to compare customer's comprehension of newsletter content before and after pair-writing with SMEs.

---
## Tasks
- [x] Create survey in Optimal Workshop 

## Acceptance Criteria
- [x] Content team can send out survey to a sufficient number of VFS team members to conduct A/B testing.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jchasia-adhoc** [comment]
Survey has been sent to 12 VFS team members who have confirmed participation.
