### ISSUE TITLE
[Datadog] Fix haproxy integration

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#31887]
## Description
Datadog is not receiving all of the needed haproxy stats.  
`datadog-agent status` on the fwd proxy instance shows the following error
![image](https://user-images.githubusercontent.com/76792875/138363837-dcaf07a2-862a-42ba-b0c3-a0656c5e2e4a.png)

## Background/context 
- https://dsva.slack.com/archives/CBU0KDSB1/p1634332702036700

## Technical notes
- https://docs.datadoghq.com/integrations/haproxy/?tab=host#configuration
- https://github.com/DataDog/integrations-core/blob/master/haproxy/datadog_checks/haproxy/data/conf.yaml.example

---
## Tasks
- [ ] fix datadog config for haproxy
- [ ] build/deploy manually or wait for auto deploy

## Acceptance Criteria 
- [ ] expected stats for haproxy are being sent to datadog

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
