### ISSUE TITLE
[MCP] Use case: Veteran has a $0 facility balance, but has statements within the past 6 months

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#31894]
## Issue Description
As a Veteran using VA Health Care, I want to be able to see my previous statements at my facility even if I don't owe anything.

---
## Tasks
- [x] Create mockup for use case and upload to UXPin
- [x] Create FE ticket for work

## Acceptance Criteria
- [x] UXPin updated and linked to this ticket
- [x] FE ticket created and linked to this ticket
