### ISSUE TITLE
Prevent unnecessary asset download for content-build local development

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#31898]
When working locally with a deleted .cache directory the build can take over an hour to complete because of the downloading of GBs of images from Drupal.

[Slack thread](https://dsva.slack.com/archives/C01SR56755H/p1634849308002200)

**Questions to answer**
- [] Are these assets a needed locally?
- [] What happens if they aren't downloaded?
- [] Will images render locally w/o SOCKS?

**Tasks**
- [] Improve local engineering experience by safely turning off image downloads
- [] If other teams are needed to complete this, alert them via this ticket

**Comment by laineymajor** [comment]
@timcosgrove do you know if we are able to switch this off? are we blocked? is your team handling this? OR is this ready to close? Thanks!!

**Comment by CBonade** [comment]
Closing as stale.
