### ISSUE TITLE
[Design] Profile: Personal Info Revision: Add Updated Design files to GitHub documentation

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#31903]
## Issue Description

As a Designer I want to add my design files to the project's GitHub documentation so that it can be referenced for other future initiatives.   [Example of populated images folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/images)

---

## Tasks
- [x] After making updates to reflect current design system pattern, add images to [project images folder on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/images) 
## Acceptance Criteria
- [ ] Updated images associated with the Profile Personal Information Revision will be stored in the project documents on GitHub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO When I add my screenshots here, should I also delete Kevin's or leave them to show a record of the changes?

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske Hmmmm.... good question.  I am not sure how that is typically handled on this team.  I guess you can save off a copy now, and when you have a chance to talk to Liz, if you don't need them you can delete them.
