### ISSUE TITLE
Compile collab cycle controlled vocabulary 

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#31908]
## Issue Description
As a new collaboration cycle team member, I need to learn  the team's standard terms for the various things they do and use those terms when communicating with colleagues and VFS stakeholders, so that I can 

- Avoid misunderstandings with my colleagues, and
- Communicate with VFS stakeholders in a way that's consistent with that of my colleagues..
however , currently I don't have one-stop access to our approved terms.

---
## Tasks
- [ ] Create Mural board to document words we do and don't use at different touchpoints
- [ ] Facilitate meeting to elicit terminology from experienced colleagues
- [ ] Turn approved terms into list on our platform product site
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@chaseakirby, again I think it might be best if we break this work out by touchpoint and work it into the 3 initiatives:

1. #39744
2. #39845
3. #40002

FYI @jimuhh

**Comment by chaseakirby** [comment]
@shiragoodman Agreed, I have split it out for each touchpoint and added to the respective Epics. New ticket numbers are below.
FYI @jimuhh 
- Staging Review #42147
- Midpoint Review #42193
- Design Intent #42194
