### ISSUE TITLE
Updates to booster content on main vaccine page and boosters/additional doses page 10/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31922]
## Issue Description
We made updates to the main vaccine mini hub page and additional doses and boosters page based on new FDA guidance for boosters. We need to send this content to the translators to update the Spanish and Tagalog pages. 

## Tasks
- [x] Update content on English pages (Danielle)
- [x] Review and publish English pages (Randi)
- [x] Send content to certified translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish Spanish and Tagalog pages (Randi)
- [x] Send live links to VHA translation team for review (Randi)

## Acceptance Criteria
- [x] Content is live on English page
- [ ] Content is live on Spanish and Tagalog pages

**Comment by RLHecht** [comment]
@lunascoop Here is the content back from the translators. 

[https://app.zenhub.com/files/133843125/d5b401f5-cb80-46b8-8027-714f33553f8c/download](https://app.zenhub.com/files/133843125/d5b401f5-cb80-46b8-8027-714f33553f8c/download)

[https://app.zenhub.com/files/133843125/39499bcb-2e36-4c6a-8440-fdf824adc151/download](https://app.zenhub.com/files/133843125/39499bcb-2e36-4c6a-8440-fdf824adc151/download)

**Comment by lunascoop** [comment]
@RLHecht The Tagalog pages are ready for review

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
  - Google translated this text link: Get answers to more questions about COVID-19 medical debt relief
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394
   Google translated these phrases/sentences:
  - Getting a booster shot
  - Check CDC information about high-risk settings

**Comment by RLHecht** [comment]
Thanks @lunascoop The Spanish and Tagalog pages were both published. Will send Mateo live links.

**Comment by RLHecht** [comment]
Closing ticket and will reopen if there are changes from Mateo.
