### ISSUE TITLE
Swap out videos in vaccine CLP-HOLD FOR WEEK OF 11/8

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31926]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John Scott McAllister

## Tasks
- [x] Replace videos and text (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] New videos and text are on live CLP

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Have questions before you get your COVID-19 vaccine?: http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks! I just published and will open up a new ticket to swap them again in 2 weeks. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
Updates are live and new ticket created. Closing ticket.
