### ISSUE TITLE
Update "Veteran" style guide entry

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31947]
## Issue Description
A user of our style guide reached out about updating our entry in the [word list](https://design.va.gov/content-style-guide/word-list#v) for Veteran. Currently we refer to capitalizing the word as an "awkward style" rather than explaining that we cap it to honor those who served. We need to update this entry with a clearer, more empathetic explanation.  

## Tasks
- [x] Update Veteran entry in word list (Randi)
- [x] Review and merge PR (Danielle/Beth)
- [x] Add addition to What's new section (Randi)

## Acceptance Criteria
- [x] Entry is updated in live style guide

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO I created a PR with these changes: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/568

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
