### ISSUE TITLE
Social security payments should be greater than 0

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#31944]
## Issue Description
Users can enter $0 after saying they receive Social Security payments on the previous page. Validation should be added to the field instructing users to enter a value greater than 0

![Financial Status Report  Veterans Affairs 2021-10-25 16-09-21.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/1d76f033-835a-4e88-9653-6a663c381adf)
---
## Tasks
- [ ] add validation to the field

## Acceptance Criteria
- [ ] validation error should render prompting users to enter a value greater than 0
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
after verifying the issue we learned that some cases should allow 0 amounts but currency vals should be restricted to only allow 0's and positive vals
