### ISSUE TITLE
Users should not be able save empty input fields

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#31955]
## Issue Description
required was previously removed from payroll deductions resulting in users being able to save empty values. Inputs should render an error on save informing the user to input a value

![Financial Status Report  Veterans Affairs 2021-10-25 17-34-59.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/4e7ee126-3db6-481d-b0bc-7b221a28ca0b)

---
## Tasks
- [ ] Users should not be able save empty input fields
- [ ] `AddAnotherButton` should not be clickable if a card is open

## Acceptance Criteria
- [ ] Users should not be able save empty input fields
- [ ] Validation error should be rendered informing user to input a value

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
