### ISSUE TITLE
Design Refactoring for Outreach & Events Hub (Filtering and Recurring Events)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#31957]
### Notes from Outreach & Events Design Sync:
PO/PM sync was scheduled and reviewed on 10/25.  Team reviewed wireframes detailing filtering options, along with recurring events.  Determination was made to move forward with testing side navigational filtering components along with recurring event types with some applied modifications to the discovery wireframes.  Several tasks were derived from the meeting and are annotated below for review and action:

### Tasks
- [x] Update Wireframe UI suggestions illustrating features in context (side nav filtering solution similar to gov.uk)
- [x] Incorporate feedback from PO/PM meeting 10/25 and prepare to present designs in support of scheduled design intent review (10/29) 
- [x] Ensure wireframes and mockups are "Mobile" first
- [x] Mobile considerations: accordion or menu for filters, no images on mobile  (CMS Define)
- [x] filter treatment with ranges of time
- [x] location [online or in person] included in the "where" section
- [x] Include images and consider social media sharing with image placement and size (Define UX mobile impact)
- [x] Validate that "calendar picker" was approved by design council / system
- [x] Mobile considerations: accordion or menu for filters, no images on mobile
- [x] Character count for event detail copy (CMS define)

### Acceptance Criteria
- [x] Update Wireframe UI suggestions illustrating features (including date/time filtering in side nav)
- [x] Update content to reflect actual content a Veteran would recognize per event offering
- [x] Updates are applied and ready for review during scheduled design intent review (10/29)

### Background / References 
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

**Comment by brianalloyd** [comment]
We've cleared design intent and have updated wireframes to reflect desired outcome.  Closing this ticket in support as we move toward high fidelity mocks in support of Veteran user research.
