### ISSUE TITLE
CANCELED**Datadog slack automation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#31954]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
In order to detect service partner changes & outages more rapidly the Identity team plans to update the [existing smoke tests for vets-api](https://github.com/department-of-veterans-affairs/va.gov-sso-smoke-tests) with Rspec system tests to automatically attempt logins across environments and CSPs. These tests are intended to be run multiple times per day to provide a more accurate assessment of the status of our service partners. Failed tests will be logged to Datadog via StatsD, as well as posted to the public `vsp-identity` Slack channel.

---
## Tasks
- [ ] Verify MHV non-LoA1 login test functions correctly on staging environment
- [x] Create Raketask to bundle individual Rspec login tests together
- [ ] Add StatsD & Slack webhooks to Raketask to log test failures
- [x] Update existing Smoke test repo & dockerfile with necessary dependencies and configurations
- [ ] Create a new Datadog dashboard to track updated Smoke test results

## Acceptance Criteria
- [ ] A compilation of individual login tests will automatically be run multiple times per day & attempt logins across both dev and staging for all current CSPs
- [ ]  All test results will be logged in Datadog and viewable through a newly created dashboard
- [ ] In the event of any test failures, the test results will be posted to the `vsp-identity` Slack channel

**Comment by joeniquette** [comment]
Move to ne epic for `datadog slack automation`
