### ISSUE TITLE
Google Analytics: Obtain Google Analytics Data

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31963]
## User Story

_Google Analytics data needs to be collected, stored in a readable/usable fashion in BigQuery (if it's not being done so already), and then connected to Domo so we can create dashboard cards that display data for our products._

## Tasks
- [ ] Verify that all the proper metrics are being tracked
    * Page render speed per-product
    * Most used viewports per-product
    * Unique visitors per application
- [ ] Data should be ingested for all applications in one data set, so a Platform-level overview can be given. There should be a team and application associated with each row, so the charts can be properly filtered down to a single application/team view in Domo.
- [ ] Verify whether or not the metrics we need are being stored in BigQuery. The data should be in a schema that is able to provide all the metrics we need to display in Domo. Analytics may already have this data stored in BQ, in which case we will need to gain access to import this into Domo.
- [ ] If analytics does not have this data in BQ already, create an ingestion mechanism in the `testing-tools-dashboard-data` repo to consume the relevant data from the Google Analytics API and upload the data to BigQuery in a properly formatted schema. This may require an API access key or some other credentials from the analytics team. There is also the possibility the analytics team may prefer to have this data under their control, in which case we should work with them to get the data made available to us as possible.\
- [ ] Once data is available, create a Domo connection that pulls this data from BigQuery to Domo.

## Acceptance Criteria

- [ ] _Properly formatted and complete Google Analytics data is available via a Domo connection to be used to make cards_

**Comment by CBonade** [comment]
Have started entering a few of these queries into Domo

**Comment by CBonade** [comment]
All queries have been entered into Domo and data is being retrieved from the Analytics team
