### ISSUE TITLE
Move Product Development Checklist to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31968]
## Issue Description
The [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md) is currently on Github and needs to be moved to the Platform Website/Collaboration Cycle. 

---
## Tasks
- [ ] Remove references to VSP. Replace with Platform.
- [ ] Update github links to Platform Website Guidance, if applicable (meaning if you know for certain that the github page linked has a valid page on Platform Website)

- [ ] Complete quick content review to ensure everything is up to date and accurate. Make changes where applicable.
- [ ] Determine where in Platform Website/Collaboration Cycle the Product Development Checklist should live. 
- [ ] Deprecate the Product Development Checklist github page once launched on Platform Website. 

## Acceptance Criteria
- [ ] The Product Development Checklist is accessible from Platform Website.
- [ ] The language in the Product Development Checklist is current.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rroueche** [comment]
I think we need another task around pointing teams to VANotify as a part of the checklist, to get the notifications aspect of their work set up. Here are the reference materials for VANotify:

Github - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify
Intake - https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees[…]Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D

**Comment by shiragoodman** [comment]
FYI @rroueche we have moved the VANotify work (per your comment) and the feature toggle work into a [separate ticket ](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32309) so that this ticket can focus on getting the as-is document up on Platform Website. thanks!

**Comment by jimuhh** [comment]
Added links from github checklist and updated platform site redirects to @rroueche 's edited copy.  @shiragoodman or @peggygannon -- if you OK review, I'll close ticket

**Comment by shiragoodman** [comment]
@jimuhh the current checklist looks good. However, the ticket is not ready to be closed. I updated the AC to remove the no-longer-relevant items. We still need to move the draft checklist to it's home on Platform Website. We need to create a new left nav page [here](https://vfs.atlassian.net/wiki/spaces/CC/overview) titled Product Development Checklist and then copy your draft page over.

**Comment by jimuhh** [comment]
@shiragoodman, @rroueche I have [published the checklist  here](https://vfs.atlassian.net/l/c/jhTV4qad).

**Comment by jimuhh** [comment]
This page is live on [VA platform site](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Product-Development-Checklist.1971650643.html)

**Comment by shiragoodman** [comment]
thank you @jimuhh ! Minor request - could you move the PRoduct Development Checklist in the left nav so it is after the Touchpoints? This is currently not an integrated part of the Collab Cycle process, and I don't want teams to be confused by the order of items. Thank you!

**Comment by shiragoodman** [comment]
@jimuhh please review that the AC has been met and then you can close this ticket.
