### ISSUE TITLE
Research VFS team processes for launch readiness

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31969]
## Issue Description
Platform Product Support team to interview and do research with VFS teams to understand how these teams determine when their product is ready for launch. 

## Tasks
- [ ]  Create a research plan and what we want to learn 
- [ ]  Do research with 10 to 15 VFS teams
- [ ]  Document their process and identify gaps 

## Acceptance criteria
- [ ] We have an understanding of how teams define "launch-readiness" 
- [ ] We have an understanding of the processes and tools teams use to determine when their product is ready to launch
- [ ] We understand the each VFS teams role in getting a product ready for launch. 
- [ ] We have identified potential opportunities for improvements to the Product Development Checklist

**Comment by shiragoodman** [comment]
Marci with Decisions Tools team shared this template as a checklist she uses: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31852

**Comment by shiragoodman** [comment]
VFS Research plan: https://docs.google.com/document/d/1SEDvIF9GCFgLTxZxKRtgZS70JcPjFJl9HyspvhNmLuA/edit

**Comment by allison0034** [comment]
@shiragoodman I am getting page not found for the research plan linked above

**Comment by shiragoodman** [comment]
UGH @allison0034 . It's because Olga never moved it to our shared folder and that was saved in her private account. Let me contact Oddball to see if they can help recover it.

**Comment by shiragoodman** [comment]
from Rachael's slide deck re Platform Objectives... VFS core tasks:
![image](https://user-images.githubusercontent.com/71330581/147964712-ac3dbda5-3581-47db-b786-0510239c78bb.png)
