### ISSUE TITLE
Reorganize Sitewide Cotent github files to ensure in right folders

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#31974]
## Issue Description
Currently Sitewide Content's github files are in several places: Public Websites and Sitewide Content's team and product folders. We need to move everything to the right place, ensuring all internal process files are in the SC teams folder and anything outward facing is in our product folder. No content files should still be in the Public Websites repo. 

## Tasks
- [x] Move files to correct repos
- [x] Review with Beth and Danielle if there are any that are unclear

## Acceptance Criteria
- [x] Sitewide Content's files are in the proper repos
- [x] No content files are left in the Public Websites repo

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
