### ISSUE TITLE
FE Unit: Ingest Front-end Unit Test Data Into BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31980]
## User Story

_Unit test data currently is being compiled into a coverage report that is being uploaded to S3. However, this data is not currently being sent to BigQuery. Additionally, it would be nice to generate a Mochawesome report for the unit tests, to have all the same, uniform data available that we do on all the other tests on `vets-website`. Unit test data is currently not being broken up into teams. This will need to be accounted for as we have to be able to show individual product data._

## Tasks
- [x] Create data ingestion mechanism to process the unit test coverage report and upload to BigQuery.
- [x] Data should be ingested for all applications in one data set, so a Platform-level overview can be given. There should be a team and application associated with each row, so the charts can be properly filtered down to a single application/team view in Domo.
- [x] Add the new data ingestion mechanism, as well as mochawesome reporting for unit tests to the GHA CI workflow.
- [ ] Create Domo data connections to BQ that pull these data sets to Domo to be ready for cards.

## Acceptance Criteria

- [x] _CI workflow uploads the unit test coverage data to BigQuery every time it runs._
- [x] _CI workflow generates a Mochawesome report for unit tests and uploads the report to BigQuery every time it runs._
- [x] _Domo has data connections for both the coverage data and Mochawesome data._

**Comment by rjohnson2011** [comment]
Created a ticket with Ops to get the required credentials to transfer the frontend report from a S3 bucket into BigQuery.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32595

**Comment by rjohnson2011** [comment]
Received the credentials from Ops. Creating a BigQuery dataset & destination table to transfer the FE report.

**Comment by pjhill** [comment]
There's some reusable code for this effort --

Mochawesome ingestion mechanism [here](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/blob/master/src/testing-reports/mochawesome.js).

**Comment by rjohnson2011** [comment]
Synced with Peter & Curt to discuss implementations. The following is in progress:
- Extend unit test code in testing reports (https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/tree/master/src/testing-reports)
- Add new function to package.json (https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/blob/master/package.json)
- Create Github action to trigger
- Build out new BigQuery schema to handle FE data

**Comment by rjohnson2011** [comment]
Update: Created the unit test code in testing reports, extended the package.json to handle this function, and built out a new BQ table to store the data.

**Comment by rjohnson2011** [comment]
[Created a branch for](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/compare/fe-unit) `testing-tools-team-dashboard-data` to grab unit test data and trigger via yarn command.

[Created a second branch (WIP)](https://github.com/department-of-veterans-affairs/vets-website/compare/ci-unit-tests) in `vets-website` to modify the CI for taking in unit tests. Currently modifying to pull and populate the BigQuery table.

**Comment by rjohnson2011** [comment]
The new data ingestion mechanism is complete - GHA successfully runs with the new unit tests function.

Continuing work on parsing relevant information from the report and uploading that table to BigQuery.

**Comment by rjohnson2011** [comment]
Made several changes to the above branches - including creating an additional BigQuery table for unit test executions. 

The unit test executions and results tables are populating - starting work on creating a query to populate with the desired mural board metrics. 

There is still a bug dealing with a JSON import that is being simultaneously troubleshooted.

**Comment by rjohnson2011** [comment]
Working on querying the BQ table data to retrieve Pass/Failures for unit test suite. Next will work on Suite Execution Time.

A coverage report will need to be appended to the unit test results table to provide the needed data for Code/Branch Coverage related metrics.

**Comment by rjohnson2011** [comment]
Have queries for Pass/Failures & Suite Execution Time charts, though a JSON unit test import error is preventing all of the records from loading and altering the chart results. Working on resolving the JSON import error.

**Comment by rjohnson2011** [comment]
1 test from the Unit Test Suite is failing and causing the Unit Test Report to not generate. Working on a fix.

**Comment by rjohnson2011** [comment]
FE Test Suite Executions table is up on Domo:
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/4d5fb9dc-8aa4-4d27-bdea-c88b59c007cc)

Working on chart for Pass/Failures/Pending.

**Comment by rjohnson2011** [comment]
There is an issue where if Unit Tests fail, the coverage report does not generate. Attempted to resolve this via adding an `always` conditional to the upload report yet the error is still occurring on occasion.

**Comment by rjohnson2011** [comment]
In attempting to get Pass/Failures/Pending test times for particular app names, it seems there are multiple application names corresponding to each cypressTestSuiteId. 

Attempting to clear up how to retrieve test suites for an individual app.

**Comment by rjohnson2011** [comment]
Drilling down to see what test suites are associated with an application name to average them.

Attempting to generate the coverage report but troubleshooting an import error.
