### ISSUE TITLE
BE Unit: Ingest Back-end Unit Test Data Into BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31986]
## User Story

_Unit test data currently is being compiled into a coverage report that is being uploaded to S3. However, this data is not currently being sent to BigQuery. Additionally, it would be nice to generate a Mochawesome report for the unit tests, to have all the same, uniform data available that we do on all the other tests on `vets-website`. Unit test data is currently not being broken up into teams. This will need to be accounted for as we have to be able to show individual product data._

## Tasks
- [x] Create data ingestion mechanism to process the unit test coverage report and upload to BigQuery.
- [x] Data should be ingested for all applications in one data set, so a Platform-level overview can be given. There should be a team and application associated with each row, so the charts can be properly filtered down to a single application/team view in Domo.
- [x] Add the new data ingestion mechanism to the GHA CI workflow.
- [x] Create Domo data connections to BQ that pull these data sets to Domo to be ready for cards.

## Acceptance Criteria

- [x] _CI workflow uploads the unit test coverage data to BigQuery every time it runs._
- [ ] _Domo has data connections for both the coverage data and Mochawesome data._

**Comment by ddzz** [comment]
Dashboard created: https://va-gov.domo.com/page/2049645635

**Comment by ddzz** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/8433
