### ISSUE TITLE
Contract: Evaluate Ingestion of Contract Test Data Into BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31997]
## User Story

_Contract test data is currently being generated using Mochawesome, and a data set of those results is being pushed to BigQuery. This has served our current, MVP dashboaridng needs. As we expand and build this out to a larger dashboard, we should reevaluate that the shape of the data we are pushing to BigQuery will serve all the metrics we are looking to track. We may need to consider breaking apart the Contract Test data into two separately shaped datasets, depending on the kind of access we need to the data for easier management. It is important to make these determinations ahead of time as we cannot change a BQ schema once it's loaded with data without wiping all the historical data._

## Tasks
- [ ] Evaluate current Contract test data ingestion mechanism to see if changes need to be made to account for metrics we cannot currently track.
- [ ] Data should be ingested for all applications in one data set, so a Platform-level overview can be given. There should be a team and application associated with each row, so the charts can be properly filtered down to a single application/team view in Domo.
- [ ] Adjust BigQuery Schemas and/or create new BigQuery tables as needed to meet the needs of our new metrics.
- [ ] Evaluate our current CI pipeline and make any adjustments necessary to ensure that the data is sent to BigQuery every CI run.
- [ ] Create Domo data connections to BQ that pull these data sets to Domo to be ready for cards.

## Acceptance Criteria

- [ ] _Ingestion mechanism provides all the data we need to produce our desired Contract test metrics in usable formats._
- [ ] _CI workflow updates this data every run._
- [ ] _Domo has data connections for all the Contract test data that can be used by our cards._

**Comment by CBonade** [comment]
All the data we need for the visuals we currently have scoped is being ingested into BQ appropriately and data sets have been pulled into Domo

**Comment by pjhill** [comment]
Yep, looking good!
