### ISSUE TITLE
improve vets-website operations control 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#320]
## Problem
- control points are not obvious / documented in the platform 

## Goal
- something about improving operations control 

## Notes
- some notes about the overall effort of improving visibility and control (some use cases about the future state of deployment and continuous improvement) 

## Tasks 
- #322 - improve feature flagging in vets-website
- #324 -  Determine how to measure the fitness of the platform with respect to how well it prioritizes risk management / mitigation or app stability

**Comment by rianfowler** [comment]
## Problem
- releases are tied to deploys / no runtime feature management 
- features are gated to environments (no production like environment to test on)

## Goal 
- support feature flag driven development, testing in production, percentage based rollouts, a/b testing, continuous improvement, continuous delivery 

## Notes
Operations control of features is an important goal of the VA.gov platform. Currently features can be gated by environment (dev, staging, production). This approach isn't well suited for continuous integration / continuous delivery: 
- there's no way to know what features are gated to an environment without reading the source code (e.g. no audit trail) 
- changes are not validated with post-release telemetry (e.g. a/b testing)
- altering feature flags requires a full build / deploy 

At a high level, we want to have the a couple of classifications of control: 
- platform: mandatory support in every app. anyone in an operations capacity can utilize these flags to manage the general stability of the website without specific business knowledge / context about the app. 
  - shut an app completely off 
  - pause an app / notify of degraded service  
  - rollback an app to a previous version of feature flags 
- application: generally application teams should be able to gate features in the way that best fits their needs. The platform documents and encourages best practices for tgese common use cases of application level feature control: 
  - percentage based rollout 
  - a/b testing js features / content including related analytics (e.g. goal setting / tracking tied to a/b tests)
  - runtime feature flag changes

## COTS / frameworks 
- [launch darkly](https://launchdarkly.com/)
  - high end hosted solution
  - team management 
  - live feature flag updates
  - frameworks / apis 
- [Google optimize ](https://marketingplatform.google.com/about/optimize/)
  - integrated solution for google analytics
  - can get to the variant information but no frameworks built out
  - focused on a/b testing more than general feature flag management 
- [app knobs ](https://appknobs.io/)
 - lower end hosted solution 
- [unleash](https://github.com/Unleash/unleash) 
  - roll your own feature flag api
  - has some dashboards / api server features 
- [Optimizely](https://www.optimizely.com/)
- [Flipper](https://github.com/jnunemaker/flipper/blob/master/docs/api/README.md)
  - maintainer has offered to help us
  
## Tasks 
- [x] PR with launch darkly - [please review](https://github.com/department-of-veterans-affairs/vets-website/pull/10293)
- [x] Organize ticket as an RFC 
- [ ] documented decision record
