### ISSUE TITLE
GitHub: Code Additions/Deletions Over Time

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32008]
## User Story

_Use Github API to pull data related to code additions/deletions over time. To get this data it appears you need to do two requests:
Use /user/:user/repos to get all repositories
Then use /repos/:owner/:repo/stats/contributors to get the contributors (and their additions / deletions) on those repositories._

## Tasks
- [ ] Modify the Github API to collect data relating to trackable repos.
- [ ] Modify the Github API to collect data for contributors related to the repo.
- [ ] Add a BigQuery schema to count this data into Domo-displayable metrics.
- [ ] Create Domo BigQuery connection and visualize into charts.

## Acceptance Criteria

- [ ] _Extend Github API requests to pull contributor info._
- [ ] _Write new BigQuery schema to injest Github addition/deletion data._
- [ ] _Domo chart displays Github commit data._

**Comment by pjhill** [comment]
OBE
