### ISSUE TITLE
GitHub: How Many Defects Associated with Product

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32009]
## User Story

_Particular defects are currently being tagged as ticket labels (defect 1-4). Create a BigQuery query to pull in all labels with the desired defects for a particular product._

## Tasks
- [ ] Add a BigQuery schema to pull in desired defects for a particular product.
- [ ] Create Domo BigQuery connection and visualize into charts.

## Acceptance Criteria

- [ ] _Write new BigQuery schema to injest Github defect data._
- [ ] _Domo chart displays Github project defect data._

**Comment by CBonade** [comment]
Discussing this with Peter, we decided that `defect` here should be defined as a `bug` tag, to differentiate this from a11y defects that are depicted in other charts. 

Here's the card:
https://va-gov.domo.com/page/1950369682/kpis/details/51693824

**Comment by pjhill** [comment]
This is a great visualization that's essential to understanding QA practice. The usefulness of this will expand as we increase the scope and quality of our product mappings.
