### ISSUE TITLE
GitHub: Pull Requests Merged/Currently Open

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32006]
## User Story

_Github closed and open data is available per issue or ticket. This info is currently being track in the existing Github API, however the BigQuery is used to parse info particular to collaboration cycle tickets._

## Tasks
- [ ] Add a BigQuery schema to parse open and closed ticket data related to a project.
- [ ] Create Domo BigQuery connection and visualize into charts.

## Acceptance Criteria

- [ ] _Write new BigQuery schema to injest Github open/closed data._
- [ ] _Domo chart displays Github commit data._

---

# Rate of Changes of Commits to the Product Over Time
## User Story

_Github Commit data is not currently being tracked but is available via the Github API at https://docs.github.com/en/rest/reference/repos#commits. A request to this endpoint will return all individual commits for a repo, the user tied to the commits, and the date of the commit. Completing the ticket will involve creating a function or BigQuery query to count commits according to a specific datetime period (week/sprint/month/quarter)._

## Tasks
- [ ] Modify the Github API to collect data relating to individual repo commits.
- [ ] Add a BigQuery schema to parse this data into Domo-displayable metrics.
- [ ] Create Domo BigQuery connection and visualize into charts.

## Acceptance Criteria

- [ ] _Extend Github API requests to pull commit info._
- [ ] _Write new BigQuery schema to injest Github commit data._
- [ ] _Domo chart displays Github commit data._

**Comment by pjhill** [comment]
OBE
