### ISSUE TITLE
[Platform Website] Iterate on documentation: Storing a secret in Parameter Store

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32016]
## Description
As part of the larger platform initiative to publish content related to common needs for VFS developers, we need to take a look at the current documentation, update it as necessary, and publish it to the Platform Website. 

An inventory and audit have been performed that describe where the documentation currently lives, and what action we need to take next to move towards getting it published on the Platform Website. 

## Background/context 
[[Ops] Content Audit and Inventory for Platform Website](https://docs.google.com/spreadsheets/d/1ZxwcDDX5NDiOGzMdvhzL2CJ3bMgcPgQccu9NUovCxrk/edit#gid=1460577279)
[Storing a secret in Parameter Store](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595172/Store+a+secret+value)
[Credstash / Parameter Store Procedures
](https://vfs.atlassian.net/wiki/spaces/OT/pages/1601503564/Credstash+Parameter+Store+Procedures)
[Additional stats that describe how docs are being consumed in the support context](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) <-- this will be useful in prioritization and action to take (update? refine? etc)

---
## Tasks
- [x] Review the current status of the documentation in question in the linked Audit/Inventory spreadsheet 
- [x] Determine whether or not the existing documentation is accurate 
- [x] Update the documentation to be accurate as needed 
- [x] Update the documentation for additional clarity as needed 
- [x] Share the documentation with the team's product manager, team lead, and product owner to get feedback/approval
- [x] Publish the document on the Platform Website

## Acceptance Criteria 
- [x] Relevant, accurate documentation for the given topic has been published on the platform website

**Comment by rbeckwith-oddball** [comment]
The confluence page can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595172/Store+a+secret+value)

**Comment by jhouse-solvd** [comment]
@rbeckwith-oddball - This is looking good, but if I'm correct, it looks like it hasn't yet been published to the platform website? I can help you with that part.

**Comment by jhouse-solvd** [comment]
@mchelen-gov / @dginther - based on the [current hierarchy,](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1847886026/Infrastructure) I think it makes sense for this doc to be published on the platform website under "Infrastructure".

Can you let me know whether you agree or have a different suggestion? 

Thank you both.

**Comment by jhouse-solvd** [comment]
Also looking to the Content & IA team for guidance in [this thread](https://dsva.slack.com/archives/CL181NRJQ/p1636058883043900)

Will report back in the next few days.

**Comment by jhouse-solvd** [comment]
The document has been published [HERE](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)

Closing.
