### ISSUE TITLE
Functional: Evaluate Ingestion of TestRail Test Management Data

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32014]
## User Story

_We currently have TestRail test management data being ingested into BigQuery and much of what we need exists in the data we have. This data should be evaluated to ensure that we have what we need to be able to track our data points properly, and that the ingestion of this data is being triggered regularly enough to provide us the data we are looking for. The three metrics we'll need to track for individual products are:_

* Number of user stories verified by test cases
* Number of defects created by test run
* Percent of failing test cases
* Top 3 most failed test cases
* Test Suite size

The one unique metric we'll need to track for the platform is:
* Top 3 teams in TestRail (based on quality of test plan execution)

## Tasks
- [ ] Evaluate current TestRail test management data ingestion mechanism to see if changes need to be made to account for metrics we cannot currently track. This is hopefully not the case given the fact that we are currently dumping the data from just about every endpoint available from TestRail's API.
- [ ] Data should be ingested for all applications in one data set, so a Platform-level overview can be given. There should be a team and application associated with each row, so the charts can be properly filtered down to a single application/team view in Domo.
- [ ] Adjust BigQuery Schemas and/or create new BigQuery tables as needed to meet the needs of our new metrics.
- [ ] Evaluate our current trigger that updates this data. If deemed more appropriate, it can be triggered on publishing of a new release or a cron can be set up to ingest this data daily.

## Acceptance Criteria

- [ ] _Ingestion mechanism provides all the data we need to produce our desired TestRail metrics in usable formats._
- [ ] _Data is set up to automatically ingest at an acceptable interval._
- [ ] _Domo has data connections for all the Contract test data that can be used by our cards._

**Comment by pjhill** [comment]
OBE
