### ISSUE TITLE
[Platform Website] Iterate on documentation GitHub Actions usage 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32015]
## Description
As part of the larger platform initiative to publish content related to common needs for VFS developers, we need to take a look at the current documentation, update it as necessary, and publish it to the Platform Website. 

An inventory and audit have been performed that describe where the documentation currently lives, and what action we need to take next to move towards getting it published on the Platform Website. 

## Background/context 
[[Ops] Content Audit and Inventory for Platform Website](https://docs.google.com/spreadsheets/d/1ZxwcDDX5NDiOGzMdvhzL2CJ3bMgcPgQccu9NUovCxrk/edit#gid=1460577279)
[Guidance for Github Actions usage](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595236/Guidance+for+Github+Actions+usage)
[Additional stats that describe how docs are being consumed in the support context](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1571323928/Customer+Support+Dashboard+Reports) <-- this will be useful in prioritization and action to take (update? refine? etc)

---
## Tasks
- [ ] Review the current status of the documentation in question in the linked Audit/Inventory spreadsheet 
- [ ] Determine whether or not the existing documentation is accurate 
- [ ] Update the documentation to be accurate as needed 
- [ ] Update the documentation for additional clarity as needed 
- [ ] Share the documentation with the team's product manager, team lead, and product owner to get feedback/approval
- [ ] Publish the document on the Platform Website

## Acceptance Criteria 
- [ ] Relevant, accurate documentation for the given topic has been published on the platform website

**Comment by jhouse-solvd** [comment]
A common use case lately is setting up an AWS IAM service account like svc-<purpose>-<team or product>... That service account then has access to a specific path in parameter store so that it can store/fetch secrets that can be used in build and deployment pipelines et al. 

e.g. 
- [AWS / IAM] Create service account that can be used with GitHub Actions for VA Virtual Agent #32825
- [GitHub Actions] Design system needs a bot and token for NPM publishing #32892

It would be great to document that use case on the platform website && make a machine-readable template that users can request via support bot or GH.

**Comment by jhouse-solvd** [comment]
We are not yet providing instructions for GitHub actions to VFS developers. This issue can be closed.
