### ISSUE TITLE
QA Dashboard

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#32036]
## Problem Statement 
VFS Teams, VSP Staff and OCTO-DE leadership don’t have a way to easily understand the state of quality on individual products, or across the platform.

How might we develop a solution that allows stakeholders to see QA-related metrics from the product(s) that are relevant to them according to their role?

## Hypothesis or Bet
By providing a dashboard that enables stakeholders to view metrics for how products are doing in following QA processes and ensuring quality on their products, stakeholders will have better insight into the state of quality on the platform and will be able to make better decisions to address any gaps on products or the platform.

NOTE: This will be an extended effort that is likely ongoing into the future, and will contain specific goals for each quarter and what should be accomplished, iterating on the current offerings.

## We will know we're done when... ("Definition of Done")
- [x] We have identified metrics in the existing test methodologies/tools
   - [x] Improved QA Dashboard(s)
   - [x] Improved Collaboration Cycle Dashboard
- [ ] <s> (Stretch) We have identified metrics in the upcoming test methodologies/tools as they are stood-up
   - [ ] ``Contract Testing``
   - [ ] ``Test User Dashboard``
   - [ ] ``Visual Regression Testing`` </s> 
- [x] We understand what it takes to obtain those metrics and they are identified as feasible, or the plan has been updated accordingly to reflect any limitations
- [x] We have an MVP of the dashboard ready for launch
- [x] We have any necessary documentation completed and available for use

## Projected Launch Date
Q4 2021

---
## Tasks
- [x] Tasks are resolved for data ingestion of both the Product & Platform

## Acceptance Criteria
- [x] Tasks are resolved for data ingestion of both the Product & Platform views
- [x] Data that is collected has been double-checked/verified to the best of our ability to ensure accuracy
- [x] Cards and layouts have been created, reviewed, and modified based on feedback
- [x] Dashboards are shareable/viewable by users
- [x] Teams have been notified through all required/optional avenues as necessary

### ... tested?
- [x] Internal tests have been conducted and defects have been logged/resolved as needed.
   - [x] Verify integrity of data vs actuals
   - [x] Verify that visuals are as effective as possible in conveying data
### ... documented?
- [x] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [x] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located on the Platform website
- [x] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it

### ... measurable
- [x] Each area has specific KPIs and supporting data identified and tracked in BigQuery

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: [Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2018017385/QA+Dashboard+Product+Outline)
* **README**: [Link (DRAFT)](https://vfs.atlassian.net/wiki/spaces/TTT/pages/edit-v2/2013200394)
* **User Guide**: [Link (DRAFT)](https://vfs.atlassian.net/wiki/spaces/TTT/pages/edit-v2/2013200394)

### Testing
* **Usability test**: None
* **Manual QA**: Data presented has been spot checked by engineers.
* **Automated tests**: N/A

### Measurement
* **Success metrics**: 
  - [x] Dashboard MVPs are published to DOMO
  - [ ] Dashboard MVPs are in use by stakeholders
* **Release plan**: [Link](https://app.zenhub.com/workspaces/sprint-board-testing-tools-team-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/33891)

**Comment by pjhill** [comment]
This effort while partially completed has been archived in favor of an alternative solution -- Product Quality Assurance Dashboard
