### ISSUE TITLE
Add Document Uploader Error States to COE

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#32046]
## User story
As a Veteran I want to be able to upload the documents that the VA needs for my COE application right from the page that tells me I need to upload documents.

## Background
Now that the designs for COE have been updated to reflect the desired UI for uploading documents on the eligibility app we need to add that functionality in the code. This ticket is for adding the document uploader error states as they are in the mockups.

## Considerations
- BE can pass back a code to show a general error states
- Standalone uploader is sending directly to LGY

## Tasks
- [x] Add error states according to [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140741546/simulate/sitemap)
- [x] Add functionality to list documents that the veteran has sent or received (Static for now but add all components needed)

## Acceptance criteria
- [x] The above changes have been made according to the mockup
- [x] A PR has been submitted for review unless in another PR (for doc uploader)

**Comment by jason-gcio** [comment]
This is for the outstanding doc uploader, not in the form

**Comment by jason-gcio** [comment]
no end point in the BE for this yet

**Comment by jason-gcio** [comment]
Per Kelli: these docs do not need to go to VBMS, just LGY (located in Check Your Status - Pending)
