### ISSUE TITLE
[Epic] HLR: Launch Readiness Checklist

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3204]
[Higher Level Review Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1053)

## Higher Level Review Launch Checklist

- [ ] **[Accessibility / 508 review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Accessibility/508-request-prelaunch-review.md)** #3810

- [ ] **[ATO review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md)** #3821

- [ ] **[Content QA](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-content-qa.md) / review(?)** #3127

- [ ] **[Design QA](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-design-qa.md) / review(?)** https://github.com/department-of-veterans-affairs/va.gov-team/issues/3205

- [ ] **Analytics / Product Health Report review** #3825
*   Establish and Review analytics that will be used to just the product health / success, and making recommendations as appropriate.
- Analytics data initially provided by Nedie in ticket #3142

- [ ] **Release plan review** [HLR Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review)
*   Review release phases and criteria for moving between them. This should include rollout schedule, success/rollback criteria, any pre- and post-launch user testing and monitoring, external documentation and comms.
*  Verify Flipper UI switch to allow rolling out the form in stages.

- [x] **[IA review](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ia-review.md)** #3822
*  Should include review of URLs, navigation hierarchy, crosslinks/redirects, SEO
*  Review events for Google Analytics

- [ ] **Security review** #3821?
*   Review looking for potential technical security issues / vulnerabilities, focusing particularly on frontend-backend interactions, anything involving certificates or cookies, and any new interactions with dependent backends.

- [ ] **Privacy review**
*   Review looking for potential user data issues, including affirming best practices around handling PII.

- [ ] **Production readiness / infrastructure review**
  * [ ] Review of technical architecture, looking for potential scaling concerns, dependency analysis, SLO assessment

- [ ] **Documentation for quickly addressing when things go wrong**
- [ ]   **Contacts for oncall support**: who do we contact if the application is failing? What kinds of failure modes are likely?
    - [ ]  ** Documentation and points of contact for any new backend dependencies**
    - [ ]  ** Links to important dashboards for investigating relevant issues**

- [ ] **No high-severity bugs present**

- [ ] **Testing requirements** #3824
    - [ ]   E2e tests, running in CI/CD, passing on all browsers
    - [ ]   Code coverage requirements
    - [ ]   Load testing
    - [ ]   Downtime notification

- [ ] **Monitoring requirements**
    - [ ]   Contact (mailing list? Slack channel?) for errors to be reported to
    - [ ]   Errors getting sent directly to team

- [ ] **Contact center(s) are prepared for this launch, with updated scripts/documentation as needed**
  - Use`#vsp-contact-center-support` Slack channel
- [ ] **VA web comms team is aware of this launch and has accurate messaging**
- [ ] **[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews) w/critical criteria up-to-date**
- [ ] **Product Guide built**
- [ ] **Tested in prod with VA back-of-house people and systems**
- [ ] **Entrance pages (i.e. supporting static content) in place**
- [ ] **Downtime UX and error messaging documentation complete**
- [ ] **"Learn and Improve" plan written**: KPI measurements, analytics reporting, next phase of features to build

**Comment by luke-gcio** [comment]
This is OBE by collab cycle.
