### ISSUE TITLE
[Kubernetes] Provide cms team with kubectl in dev cluster

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#32042]
## Description
Per a conversation had between ops and cms in a meeting, we have collectively decided to allow the cms team with admin access to the dev cluster in order to fledge out their workflow and test some additional tools.  This was approved by Demian.

The following people will be added
Eric Oliver
Nathan Douglas
Cameron Eagans
Elijah Lynn
Neil Hastings

## Background/context 
- https://dsva.slack.com/archives/CJYRZK2HH/p1635277257125300 

---
## Tasks
- [x] Add these users to https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-dev/eks.tf for transparency.  This terraform does not actually apply the changes due to the flag `apply_config_map_aws_auth = false`.  This is set due to managing user access in terraform does not work all that well and a better solution still needs to be developed.  But in interest of time and helping the cms team migrate we will be doing this for now.
- [x] Manually edit configmap/aws-auth to allow said users

## Acceptance Criteria 
- [ ] added users can access the dev eks cluster

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Has this been completed and verified?

**Comment by dginther** [comment]
Looks complete, I verified the access permissions are present.
