### ISSUE TITLE
Track Null Benefit Claims on Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32054]
## Background
There is a small number of `null - no benefit claims` that begin submitted to RBPS and without a benefit claim ID, RBPS isn't able to queue the application for review.  This is less than ideal because those claims will need to be sent over manually to be manually reviewed.

The owners of the BDN service have been notified by Linda C. at BGS and have so far replied that "_there is no root cause._" Linda is waiting to hear back again from them on any updates.

The recent deployment of Dependency Claims on VA.gov is inheriting this issue in out submissions but it has been indicated that this issue was pre-existing before in eBenefits and the Veteran was given an error notification.

## Story
We need to track this issue so that we can either:
- help update or make changes from the VA.gov side of this, and/or 
- assist in automating the transmittal of the `null- no benefit claim` submissions to the correct org/person (OFO/VSR?).

## Current Hypothesis
EP codes are not updating correctly for some reason as provided by the BDN service.

## Considerations
One possible workaround that has been discussed is to manually increment the EP code in the event of a PIF error.  BGS Team 1 has been asked if there would be a negative impact in forcing the increment.  The working theory would be if we get an error inserting the claim, we would check to see if it is a PIF error.  If it is a PIF error, we could possibly try adding one to the increment and insert the claim with the new EP code.  This would need to be tested in staging to determine whether or not this is a valid workaround (which may be tough to reproduce and might not even be possible).  A long term solution according to Linda and Scott would be to not create PIFs since BDN is no longer being used. 

Linda mentioned that checking with BDN to see about how to test easier in the lower environments.

Codify known risks, mitigations, and plans to implement.

Add stronger language at the top of the silent failure to try again

Can we detect that they have already submitted and let them know to stop and try again?

If SHARE is the only system assigning a PIF already established error (after RBPS), can we talk to someone within that system and make it not do that?

**Current proposal being discussed**
- detect PIF already established / null benefit claim IDs in a job,
- increment the EP code by one, re-attempt until null is not returned (10 times?)
- backup to Central Mail(?)
- more in Comments below

## Tasks
- [ ] Continue to work with partners and stakeholders in uncovering and potentially correcting this issue
- [ ] TBD

## Acceptance Criteria
- [ ] The `null - no benefit claim` issue has either been resolved, or
- [ ] The issue of transmittal of the claims has been decided/implemented, or
- [ ] A path forward has been determined/decided upon

**Comment by jason-gcio** [comment]
**NON-OFFICIAL DRAFT - WIP**
**Issue**
EP codes are being incorrectly indicated when requested by the BDN service, resulting in a "PIF already established" error and a null benefit claim ID on the submission.

**Considerations**
The BDN service in question does not have a resolution date in place as of this writing.
Correct EP codes are required so that the National Work Queue can accept and route the submission properly.  Nulls don't have a pathway.

**Proposed solution**
Within on the of the jobs we use to submit the application, we can run a check to see what the results are:
A) the submission comes back with a claim ID, and the application goes on its way, or;
B) the submission returns the "null  - no benefit claim ID" error where we will:
  1) increment the EP code and;
  2) re-attempt the submission and;
  3) check for the null - no benefit claim ID" error again until;
    a) the EP code is accepted and the submission moves on, or;
    b) the submission still fails after N re-attempts and;
      i) a silent failure email is sent to the Veteran and;
      ii) the null submission is marked for manual transition to OFO

**Risks**
There are three main pathways that this implementation will take:
1) This code fix resolves the issue where EP codes are passed through correctly, resulting in benefit claim IDs being assigned and the application moves on  (KPI: nulls are ~0%; this is good as it shows nulls being converted to regular submissions)
2) This code fix has no impact on the submission itself and the nulls are just as present as they were before (KPI: nulls % have no change; this is not good as it means that we have either not implemented the code correctly, or the EP code incrementation has not behaved as expected)
3) This code fix breaks the submission process completely and zero claims are submitted (KPI: ~0% submissions are sent; this is very bad and should be reversed immediately)

Testing has historically been easiest in LINKTEST which amps to our staging environment (staging.va.gov) but we know PRE-PROD is often an important step.  We would like to make reasonable efforts to test in PRE-PROD but hope that LINKTEST staging will inform us adequately as we develop this solution.

**Mitigations**
We can implement this code fixe behind a feature toggle and only allow a small number of submissions through, first to establish that the code fix does not break the entire submission process, then after opening up to more submissions, detect the number of null claims remaining.

**Comment by steele-lm** [comment]
@data-doge Any idea if this issue still exists or if this was one of the areas you resolved?

**Comment by data-doge** [comment]
@steele-lm I'm not familiar with this issue 🤔. Also not sure if the issue still exists.

**Comment by tblackwe** [comment]
Closing as old issue, we have encompassed the scope of null claims in other tickets
