### ISSUE TITLE
Update R&S TSGLI article contact info to match PDF and remove info from tables

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32072]
## Issue Description
We have an updated TSGLI form that was added to our life insurance pages. Some of the phone numbers and other contact info is different from what is currently in our R&S article [how to find out if you should get a higher TSGLI payment](https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/). We need to compare the 2 and update our article to match this form. 

Updated form: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8600_ed2021-11.pdf

While we are making these changes, we should also remove the information from tables and put them into lists for accessibility reasons. 

## Tasks
- [x] Update R&S article to match info on new form (Selina)
- [x] Change tables to list format (Selina)
- [ ] Review and publish (Randi)

## Acceptance Criteria
- [ ] Article is live with updated contact information in lists

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I've called the numbers for each service branch and listed call center hours where possible. Here are my other notes.

How to find out if you should get a higher TSGLI payment: http://preview-prod.vfs.va.gov/preview?nodeId=15172

Army (Number's different from PDF, but it's the correct one)
Source: https://www.hrc.army.mil/content/TSGLI%20Contact%20Us
Number: 888-276-9472 This is the number currently listed on the TSGLI page, but different from the one in the PDF.

Coast Guard
This number is a direct line to the TSGLI Program Manager and not a call center. I’m unsure of how to specify hours of operation.

Marines
Called both numbers and couldn’t confirm service hours. The first one, 877-216-0825, just kept ringing. And the second one, 703-975-4069, seems like a personal/direct line.

We should let the form manager know that the Army, Marines and Navy websites listed on the form are incorrect/outdated. The listed website address for the Marines actually routes to a sexually explicit website.

**Comment by RLHecht** [comment]
I replaced the PDF above with the newest one, which is now accurate.

**Comment by RLHecht** [comment]
The work in this ticket is complete though the changes aren't live. We are also reworking this page in ticket #32127 so won't publish the updates until that's complete. Closing this one.
