### ISSUE TITLE
[Design] Profile: Organize profile mockups by feature, clean up design specs

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32074]
## Issue Description
As a Designer, I want to organize the profile mockups by creating a Sketch file per profile feature so that they will be easy to identify when needed for future updates. 

There are also discrepancies between what is on staging + profile 2.0 mocks, particular wrt to padding and margins.  Audit + create new mock-ups/spec sheets to provide to FE so they can clean it up and align staging w/ mocks.

---
## Tasks
- [ ] Using the existing [Profile 2.0 Sketch files](https://www.sketch.com/s/adfb3630-7e69-4609-af02-64ab8cf7fe10/a/xrAkAMl), create separate Sketch files for the pages related to the below Profile features:
   - Personal information
   - Contact information
   - Military information
   ~- Direct deposit information~ Christina is tackling this one
   - Account security
   - Connected apps- 
   - table padding on desktop and mobile
  - h1 bottom margin
  - section bottom margin, especially on mobile
  etc - will continue to add more

## Acceptance Criteria
- [ ] There will be a separate Sketch file for each of the areas listed above in Tasks. 
-  [ ] design specs delivered to FE
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Added scope of work from issue #23186 per Liz and increased estimate to 8.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO What were you thinking in terms of a deliverable for design specs for FE? I would think they aren't necessary until Zach needs to actually work on something or make a change. 

I'm not anticipating any necessary dev changes as a result of this work; rather setting a foundation and clean starting point for the new team to help yall get going smoothly.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz I didn't really have any specifics in mind apart from what you outlined when you recommended creating a ticket for this work (organizing by feature). 

We do have some tickets related to Personal Information Revision that may be good for Christina to work on next so Zach has accurate mock-ups to work from.

**Comment by andaleliz** [comment]
That sounds good @MarciMcGuireGCIO, I won't plan on writing up any additional docs outside of the Sketch files.

Also, that sounds good that Christina could tackle the Personal Information revision. I'll create a separate contact info section but leave the Personal Info to her. She's likely more familiar with those changes than I am already anyway, since she had a meeting with Kevin today :D

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @andaleliz !

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz I had a link to the Profile 2.0 Sketch files in a couple tasks for @cgednalske to use as a reference for updating the design for the Personal Information Revision mockups.  The seem to be broken, and I suspect that's related to the re-organization work you are doing.  When you have a chance, can you send us the new links?  Thanks!

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO and @cgednalske can you check and see if [this link ](https://www.sketch.com/s/f7733912-f69e-4fb9-aa95-256f2cce5ce1)works for you? I didn't delete it (that I recall) and I see it in our Sketch for Teams instance

**Comment by MarciMcGuireGCIO** [comment]
Yep!  It works for me.  Thanks!

**Comment by cgednalske** [comment]
Works for me too! And regarding personal information/contact, is it correct that these are the files that came before the Profile 2.1 files Kevin shared with me?

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske glad the link worked!  Re your other question - yes and no.  Kevin's mockups were updated after the 2.0 files, BUT his mockups were based on some older (Pre 2.0) ones that don't match the current design patterns, if that makes sense.   You may want to just ping Kevin and find out if he updated the design patterns, and if so, how far he got with that.

**Comment by andaleliz** [comment]
I have a question about connected apps - the mock-ups show an empty state that includes a list of 3rd party apps a person can connect to their profile, as well as an FAQ:
![image](https://user-images.githubusercontent.com/55992116/141855718-bb7f90ff-7cc8-486e-9e5b-05bf0ebad8bb.png)

However, when I log into staging (user 220 is one example) I see this:
![image](https://user-images.githubusercontent.com/55992116/141855754-b3ff72a0-55eb-41dc-942d-3fdac472d146.png)

I'm not sure if the difference is because of a specific use case that I'm not seeing with the users I'm checking against, or if the design actually changed after these mock-ups were created. I feel like I've seen that third party app list before.

@Samara-Strauss, @tressaellen or @erikphansen any idea? I'm not sure who else would know the answer to this.

**Comment by andaleliz** [comment]
@Samara-Strauss and/or @tressaellen another question - there are 3 mock-ups for the Change Your Address content page among all the profile screens. They show the sign-in alert in various states ([unauth](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/Omlnkaw), [LOA1](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/m1eOab7), and [LOA3](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/DPJ0v4j)).

I'm assuming this page was launched in connection with Profile 2.0, or the alerts were updated, and that's why those files are here. Do we need to update and move them over to the new files? The page looks like the content has been updated quite a bit since these mock-ups were created and I can't think of a reason our team would need a mock-up of this new version.

**Comment by Samara-Strauss** [comment]
> I'm not sure if the difference is because of a specific use case that I'm not seeing with the users I'm checking against, or if the design actually changed after these mock-ups were created. I feel like I've seen that third party app list before.

The design changed. It now links to an app directory.

> I'm assuming this page was launched in connection with Profile 2.0, or the alerts were updated, and that's why those files are here. Do we need to update and move them over to the new files? The page looks like the content has been updated quite a bit since these mock-ups were created and I can't think of a reason our team would need a mock-up of this new version.

Nope, you don't need to modify the mockups of the content page.

**Comment by andaleliz** [comment]
@Samara-Strauss thanks for the information!

@MarciMcGuireGCIO, @zacharymorel and @cgednalske, here are all of the separate Sketch files I created.  
- [Contact information](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655)
- [Military Information](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775)
- [Notification settings](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c)
- [Account Security](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc)
- [Connected apps](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e)

I also [added these links to the product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md#design), since I think it's helpful to have access to the latest and greatest somewhere. I didn't update the mock-ups but can create new screenshots of everything if you want to make a ticket for me.

I also renamed the `Profile library` file to `Authenticated Experience Pattern Library` since it includes the nametag from My VA, and may include other patterns that cross from profile into other parts of the site. [It can be accessed here](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935) if you ever need it.

Lmk if you have any questions!

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @andaleliz !  This will be extremely helpful!

**Comment by andaleliz** [comment]
You're welcome! Once @cgednalske is all done with direct deposit and personal information, I think we should delete the [Profile 2.0 Sketch file](https://www.sketch.com/s/f7733912-f69e-4fb9-aa95-256f2cce5ce1) to minimize confusion. I can only see that confusing people in the future.

**Comment by MarciMcGuireGCIO** [comment]
Good idea!
