### ISSUE TITLE
Staging Review [Debt Resolution- Medical Copays (MCP)]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#32081]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Update ticket with the product’s launch date after it has gone live.
- [ ] Close ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Staging URL and staging test-user information: Found in [MCP Folder in the Team-sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/medical-copays-portal)
Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository. 

Use this accessible staging account template to do so:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md
-->

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Product_Outline_Medical_Copays.md) 

- [ ] [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/release_plan.md) with the "Planning" sections completed 

### Content artifacts 

- [ ] [UXPin Content Details](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141834694/simulate/sitemap?mode=i)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_id=2939&group_order=asc&display_deleted_cases=0)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/2111) in TestRail with test execution logs 
- [x] [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/284) 
- [x] [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/286)

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: Denise Coveyduc
- OCTO-DE Product lead: Matt Self
- OCTO-DE Design lead: Ryan Thurwell

### Team Members

- Scott James
- Craig Wheeler
- Justin Linn
- Riley Orr
- Becca Walsh
- Troy Riser

### VFS Attendees

- Content and IA: 
- Accessibility:  Angela Fowler
- QA specialists: Tze-chiu Lei

## Scheduling

**December 9 - 2:30pm**

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@denisecoveyduc is this ready to schedule?

**Comment by shiragoodman** [comment]
@denisecoveyduc we have reserved the 12/9 1:30pm ET timeslot for this review. Please be sure to update this ticket with the appropriate artifacts and attendee information. Artifacts will need to be shared no later than 12/3 EOD.

**Comment by pjhill** [comment]
@denisecoveyduc , a few clarifying points about the staging test credentials --
* I noticed that you included the reference to the va.gov-team-sensitive repository as a screen shot. It is acceptable to link directly to resources in that repository publicly because only those with access will be able to access the resources stored there.
* The test users list appears to be stored in a GovernmentCIO maintained SharePoint to which we do no have access.
* Is there any way to list those test users out plainly in the va.gov-team-sensitive repository instead?

**Comment by denisecoveyduc** [comment]
Hi Everyone, My apologies I drafted a note yesterday and then went to check on the sharepoint and forgot to send it. Too many plates spinning this week. 

**Staging  URL:** https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/
**Staging Test Users:** You can use User 80 and 81 from the [mvi-staging-users.csv](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L83)

Please let me know if you need anything else and I will be sure to respond quickly. I also updated the info above.
FYI: @pjhill @seanasewell @shiragoodman

**Comment by seanasewell** [comment]
@denisecoveyduc I am having trouble logging in with user 80. I did try user 82 though and it logged me in and is allowing me to review the experience. Is it safe to assume that 82 is a good test account to use?

**Comment by denisecoveyduc** [comment]
@seanasewell Currently only 80 and 81 work. Medical copays aren't currently working for test user 82.

**Comment by seanasewell** [comment]
@denisecoveyduc When I click the staging link and proceed to log in using the test user 80 credentials, I am met with this screen - https://d.pr/i/RI4QJ3 When I use use test user 82 credentials, I can navigate with this screen to view copays - https://d.pr/i/ajbnx3 @pjhill Just to confirm, are you able to log in using test user 80 credentials?

**Comment by jimuhh** [comment]
I tried to log in w/ 80 credentials but no luck.

**Comment by denisecoveyduc** [comment]
Eek.. My apologies as far as I know 80 was working. 
@craigwheeler @LinnJS  Can either of you offer any advice?

**Comment by craigwheeler** [comment]
@denisecoveyduc and @jimuhh just verified on staging that user 81 seems to be working and should have active copay balances let me know if for some reason you're still not able to get in?

**Comment by jimuhh** [comment]
Weird. I just c/pasted those creds in the login but it still threw an error on me.

**Comment by seanasewell** [comment]
@craigwheeler Here is what I am seeing when I use 81 - https://d.pr/i/ZuYY4T Is this what you are seeing? @jimuhh

**Comment by jimuhh** [comment]
@seanasewell I'm not even getting past the login screen.

**Comment by craigwheeler** [comment]
okay and just to verify you're using `vets.gov.user+81@gmail.com` from the list of [staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L83) on line 83 correct?

https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/

**Comment by jimuhh** [comment]
<img width="777" alt="login error screen" src="https://user-images.githubusercontent.com/89798550/145283577-a1118dc8-7293-491e-8139-a95fead82c85.png">
@seanasewell Unfortunately, what I'm seeing is this

**Comment by seanasewell** [comment]
@craigwheeler Ok, I see the confusion. The line number and the email do not match up - https://d.pr/i/rShFRi

**Comment by jimuhh** [comment]
@craigwheeler I'm afraid that I've tried it both ways: line numbers and digits in the test email addresses and neither is working for me.

**Comment by denisecoveyduc** [comment]
@jimuhh How about I set up 15 mins tomorrow to try and resolve the issue. I am not sure what is going on.

**Comment by jimuhh** [comment]
@denisecoveyduc Sounds good. Thanks.

**Comment by tlei123** [comment]
@pjhill @ddzz , one test-case's runs now completed.  QA-artifact links add/updated above in main description.\*

\* I'll replace the currently-partial Summary (Defects) report with final once the other 3 test-cases have been run.  We're still waiting for some Staging API mockdata.

Thanks much!

cc @shiragoodman @denisecoveyduc

**Comment by jimuhh** [comment]
Thanks @denisecoveyduc and @craigwheeler for providing tech support to get me into the copay tool. 

![Homer Simpson saying "D'OH!"](https://user-images.githubusercontent.com/89798550/145430366-ce1033de-df69-4559-9d3c-f85acfe236fd.gif)

**Comment by tlei123** [comment]
@pjhill @ddzz , QA test-runs now all completed.  New Summary (Defects) report link now updated above in main description.

Thanks much!

cc @shiragoodman @denisecoveyduc

**Comment by shiragoodman** [comment]
Zoom recording of Staging review: https://us06web.zoom.us/rec/share/bqSA92C02A6vB6l_rKGXbhRs-aq7bs0ZTwEnlc68LSJZXxsw30LIxlX8xQYff8gW.13dBb2sxZ8XAxzcd 
Passcode: aUz!9=PV
