### ISSUE TITLE
[Monitoring and Alerting] Set up new workflow for <service> 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32087]
## Description
Apply the new workflow developed during the PagerDuty redesign (lessons learned from Loki monitoring tasks) to other Ops-managed services

_note, this can be a placeholder for the next service that we decide_ 

## Background/context 
Alerting guidance documentation [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Platform+Operations+Alerting)

## Technical notes
Start with: Does this service send its metrics to Datadog? 

---
## Tasks
- [ ] Synthetics 
- [ ] Determine service-specific metrics 
- [ ] Ensure metrics are available in Datadog
- [ ] Set up monitors in Datadog
- [ ] Test the monitor in Slack 
- [ ] Build out alerting thresholds / parameters 
- [ ] Integrate w/ on-call channel + PagerDuty 

## Acceptance Criteria 
- [ ] We have solid monitoring and alerting in place for Grafana, and feel confident about our ability to know if anything is happening that affects the running service for our users

**Comment by jhouse-solvd** [comment]
This was a placeholder issue that is no longer needed. Closing.
