### ISSUE TITLE
MAINTENANCE: Publish content principals guidance

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32105]
# User story
As a PW contributor, I need to know what the voice/tone guidance is, so that I can write easy-to-understand customer-facing docs.

# Tasks

- [x] Amy/Gretchen sync to discuss what goes into an outline
- [x] Write outline
- [x] Draft based on outline
- [x] Solicit RR's feedback on draft, to confirm alignment
- [x] Add draft to style guide
- [x] Socialize voice/tone guidance to Platform teams

# Acceptance criteria
- Voice/tone guidance is acknowledged by Platform PMs.

# Reference info
- n/a

**Comment by lianilychee** [comment]
11/1 Mon:
- Fri: was not blocked on Fri
- today: rough draft

**Comment by lianilychee** [comment]
11/02:
- yesterday: 
- today: after verifying the bullets, will turn bullets into prose

**Comment by lianilychee** [comment]
11/03 Weds:
- ready for review today!
  - looking for feedback on intro, as well as general feedback

**Comment by lianilychee** [comment]
11/04 Thurs:
- needs review
- today: 
  - resolve highlighted questions
  - could incorporate timeless docs if we decide to
  - prep for RR convo tomorrow - but need help coming up with talking points that appeal to her

**Comment by lianilychee** [comment]
11/05 Fri:
- nothing blocking yesterday 
- on timeless docs section: will find a way to cite Google; Gretchen to FUP with Amy on `timeless` synonym
- team will help come up with talking points on Monday
