### ISSUE TITLE
PW ANALYTICS: Identify enhancements to make to dashboard

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32111]
# User story

As a Content team member, I need to refine our Domo dashboard so I can evaluate the health of the PW.

# Tasks

- [ ] Tweak data card to be cumulative, or change card title language to incl the word “Unique”
- [ ] Group page views by space?
- [ ] To come based on baseline data

# Acceptance criteria
- Requests have been made to the Analytics team.

# Reference info
- n/a

**Comment by lianilychee** [comment]
11/3 Weds:
- was blocked by time and internal work yesterday
- today: actually want to incorporate the best practices from other reports into our suggestions
- no one to talk to today; but Gretchen tomorrow

**Comment by andreahewitt-odd** [comment]
This will be accomplished in KPI work.
