### ISSUE TITLE
Design to display Vet Center CAP hours on the Locations page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32124]
## Issue Description

On the Locations page, Vet Centers have the option to display designated hours for a Community Access point or direct Veterans to call the main location for information.

The Eugene Reedsport CAP specified displaying weekly Thursday hours but this information does not display on the page.

 ## Steps to reproduce

1. View [node  37311 for the Eugene Vet Center - Reedsport location](https://prod.cms.va.gov/node/37311/edit?destination=/section/veterans-health-administration/vet-centers/eugene-vet-center)
2. Notice the "Provide CAP hours online" box is checked under "How should CAP hours be communicated?" and 10 - 6 on Thursdays is indicated in the table.
3. View the [Eugene Vet Center Locations page](http://preview-prod.vfs.va.gov/preview?nodeId=27751) 
4. Notice no hours are displayed for the Reedsport location.

## Screenshots

 <details>

<summary> Node 37311  </summary>

 

![image](https://user-images.githubusercontent.com/55411834/139156909-0b198736-52e2-4942-8a23-e2c0651b7424.png)

 

 

</details>

 

<details>

<summary> Locations page </summary>

 

![image](https://user-images.githubusercontent.com/55411834/139157012-b0518f79-116c-4c88-b6cb-af2740cfe2d2.png)

 

 

</details>

 

---

## Tasks

- [ ] Ensure preference for displaying hours is respected on front end

 

## Acceptance Criteria
- [x] UX pin specs
- [x] If the "Provide CAP hours online" box is checked and hours are specified in the table, display the hours for the CAP on the Locations page.

- [ ] If the "Call main location" box is checked, [NEED TO GET EXPECTED BEHAVIOR]

**Comment by nicko-amida** [comment]
@mmiddaugh Here's a [UXPin mockup](https://preview.uxpin.com/46fe3a3a3a963877cadf501d6e1886c2a2f5cc48#/pages/144953996/documentation/no-panels?mode=i) for the locations page CAP hours! 

As far as the "Need to get expected behavior" bullet point - will the mockup need to reflect these changes as well? Just let me know and I can make any changes.

**Comment by mmiddaugh** [comment]
@nicko-amida When the "Veterans should call main Vet Center for hours" option is selected in Drupal, I think we should just show a single phone number and add the "Please call the main Vet Center for hours" label

**Comment by nicko-amida** [comment]
@mmiddaugh The UXPin label has been updated to show only the label!

**Comment by nicko-amida** [comment]
@mmiddaugh Here's another [UXPin update for CAP hours](https://preview.uxpin.com/46fe3a3a3a963877cadf501d6e1886c2a2f5cc48#/pages/145796618/documentation/no-panels?mode=i), including comments, and cases for single, and multi-line comments.
