### ISSUE TITLE
Rework TSGLI R&S article to broaden scope

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32127]
## Issue Description
We need to look at the TSGLI article [How to find out if you should get a higher TSGLI payment](https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/) to determine if we need to broader the scope. 

Stakeholder Steve Fital had asked us if we could add a PDF link for TSGLI contact info to the right rail on the life insurance hub landing page. Instead of putting it there, we need to look at the R&S article to determine if we should rework the H1 and intro and add another section with more information about TSGLI. 

PDF to add: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8600_ed2021-10.pdf

Beth's notes from ticket #31891:

I sent an email to Steven Fital to see if he'd like us to proceed with these updates, then circle back to take care of the TSGLI contact info once we have a solution there. We've decided not to link to a PDF from the right rail of hub landing pages as he'd requested, so we're trying to figure out if we 1/ create a new R&S page with TSGLI branch of service phone numbers or 2/ modify an existing R&S article to make the H1 and purpose broader since it already has TSGLI contact info.

## Tasks
- [x] Determine changes to R&S article (Beth)
- [x] Update in Drupal (Selina)
- [x] Rework article (Randi)
- [x] Edit (Patrick)
- [x] Send to Beth for final review in ticket #35702 (Randi)

## Acceptance Criteria
- [x] Page is ready for final review.

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I've called the numbers for each service branch and listed call center hours where possible. Here are my other notes.

How to find out if you should get a higher TSGLI payment: http://preview-prod.vfs.va.gov/preview?nodeId=15172

**Army** (Number's different from PDF, but it's the correct one)
Source: https://www.hrc.army.mil/content/TSGLI%20Contact%20Us
Number: 888-276-9472 This is the number currently listed on the TSGLI page, but different from the one in the PDF.

**Coast Guard** 
This number is a direct line to the TSGLI Program Manager and not a call center. I’m unsure of how to specify hours of operation.

**Marines**
Called both numbers and couldn’t confirm service hours. The first one, 877-216-0825, just kept ringing. And the second one, 703-975-4069, seems like a personal/direct line.

We should let the form manager know that the Army, Marines and Navy websites listed on the form are incorrect/outdated. **The listed website address for the Marines actually routes to a sexually explicit website.**

**Comment by RLHecht** [comment]
Using this ticket to broaden the scope of the R&S article.

Notes from Steve Fital's email:

Her response is that Servicemembers, or those assisting them, should contact the offices for:
Question on filing the claim
Questions on entitlement
Assistance/guidance on obtaining information
Appealing a decision*
She would like to change the question about getting a higher payment to be more broadly stated as appealing the decision so that it covers that question as well as if their claim was denied.
Also, can you add Space Force in the section with Air Force active duty?

**Comment by RLHecht** [comment]
Posting more info from stakeholder here for reference: 

Entitlement here pertains more towards questions about what would result in receipt of the benefit (payment). Example: servicemember lost 3 fingers on one hand, they may call asking if that is sufficient to satisfy the loss to receive the TSGLI payment.

Can you elaborate more on assistance/guidance on obtaining information? Does this mean contacting the office if there are broad questions Veterans may have about TSGLI in general?
This is more covering if the servicemember needs assistance, or guidance, on obtaining information/documentation to satisfy the necessary evidence needed to substantiate the claim.

**Comment by RLHecht** [comment]
@psanders86 Here's a reworked TSGLI article for you to review. Happy to chat with you about this so you have the background if you want. I'm going to redo this ticket to break it up into a few different ones since I don't think final review and publishing would all happen in this sprint. 

[https://app.zenhub.com/files/133843125/3c93241c-f764-4f21-b01c-4a04f8619394/download](https://app.zenhub.com/files/133843125/3c93241c-f764-4f21-b01c-4a04f8619394/download)

**Comment by psanders86** [comment]
@RLHecht My edits are here, thanks! [https://app.zenhub.com/files/133843125/37ec0cae-4c13-407e-8f73-a55eca495bec/download](https://app.zenhub.com/files/133843125/37ec0cae-4c13-407e-8f73-a55eca495bec/download)

**Comment by RLHecht** [comment]
Work in this ticket is completed. I posted the final word doc for Beth in the next ticket.
