### ISSUE TITLE
Update Copy for Dependency Verification

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32129]
## Background
There is a typo on one of the confirmation screens that needs to be corrected.

## Considerations
- Last line of copy should be _"If we need you to give us more information or documents, we’ll contact you **by** mail."_
![Screen-Shot-2021-10-26-at-3.42.57 PM.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/b3e6b3cb-6a72-45cb-8e04-48aae35a0b2a)

## Tasks
- [x] Update the copy on the confirmation page
- [ ] ...

## Acceptance Criteria
- [x] The copy is updated
- [x] A PR has been requested for merging
