### ISSUE TITLE
[Content] Find a VA Form: Update online form URL for 21-674 in CMS

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32128]
## Issue Description
Per a [Slack conversation](https://dsva.slack.com/archives/C52CL1PKQ/p1635179852086400) between @Mottie and @jason-gcio on 10/25/2021, the online form URL for form 21-674 should be changed in the CMS from https://www.va.gov/view-change-dependents/add-remove-form-686c to https://www.va.gov/view-change-dependents/introduction
---
## Tasks
- [x] Change online tool URL for form 21-674 in the CMS from https://www.va.gov/view-change-dependents/add-remove-form-686c to https://www.va.gov/view-change-dependents/introduction - this will have to be done by the Content team or someone else with write access in Drupal.

## Acceptance Criteria
- [x] When a user searches for 21-674 in Find a VA form, the online form option presented in the search results and on the form detail page will link to https://www.va.gov/view-change-dependents/introduction
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Handing this off to you to assess/fix. Thanks!

**Comment by RLHecht** [comment]
@lunascoop could you please made this change and I'll review and publish? Thanks!

**Comment by lunascoop** [comment]
@RLHecht this change is ready for review.

About VA Form 21-674: http://preview-prod.vfs.va.gov/preview?nodeId=5964

**Comment by RLHecht** [comment]
This was reviewed and published. Moving to validate and will close when live.

**Comment by MarciMcGuireGCIO** [comment]
Thank you all! Cc @jason-gcio

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
