### ISSUE TITLE
Content updates to foreign programs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32130]
## Issue Description
Tammy Hurley reached out with changes to the [foreign programs](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/) page. Updates are attached in this word doc:

[https://app.zenhub.com/files/133843125/4b81ad03-178f-4c83-8992-6112a2b54b23/download](https://app.zenhub.com/files/133843125/4b81ad03-178f-4c83-8992-6112a2b54b23/download)

Newest doc shared from stakeholders:

[https://app.zenhub.com/files/133843125/ed6c21c8-2ee9-4a6e-9962-5cc8bd3982ea/download](https://app.zenhub.com/files/133843125/ed6c21c8-2ee9-4a6e-9962-5cc8bd3982ea/download)

## Tasks
- [x] Update content in Drupal (Selina)
- [x] Check for sighted language or updates to bulleted lists (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Updates are live on the site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you make these edits (note that I removed the bullets):

**Before you enroll, make sure we’ve approved your program for education benefits.**

Contact the school or contact us through Ask VA to find out if we’ve approved your program for VA education benefits. 
 [Contact us online through Ask VA]

Or you can send an email to federal.approvals@va.gov to request information about foreign program approval. You'll need to give us the name of the foreign school, the complete address, and the name of the program you want to enroll in. We’ll let you know if your program has already been approved.

If you or your qualified dependent want to enroll in a program that we haven’t approved, you’ll need to ask the school to request approval. We can’t take any action until an official from your school (not you) requests approval. If we don’t approve your program, you’ll have to pay all costs at the school, including tuition and fees.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I made those changes: preview-prod.vfs.va.gov/preview?nodeId=925

Let me know if we should make the other changes with the comparison tool before we send back to Tammy.

**Comment by bethpottsVADEPO** [comment]
Your changes to that node look good. Just add "online" in the first sentence: "...or contact us online through Ask VA.."

Yes, please make the GIBCT changes and then send to Tammy. Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Go ahead and change the number from 90 to 120, and here's the pl text to use for the other addition they sent us:

**Note:** Foreign schools report tuition and fees to us in their local currency. We then convert the tuition amount into U.S. dollars.

Let's also add a set up line before the bullets under "What benefits can I get?":

**You may be able to get these benefits:**

**Comment by RLHecht** [comment]
Stakeholders approved the changes and I published the page. Moving to validate and will close once it's live.
