### ISSUE TITLE
Default sign-in page application

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#32134]
## Issue Description
Set the default sign-in page to have a normal VA.gov flow

---
## Tasks
- [x] Update external redirects to include VA.gov mapping
- [x] Set default if no application found in redirect method

## Acceptance Criteria
- [x] On the /sign-in page I can log into VA.gov when no application is specified
- [x] If no param is specified in the app, we default to vagov.
- [x] if the param is vagov (or whatever you want to name it) we default to vagov
- [x] if the param is garbage/not in our explicit list of apps, we default to vagov
- [x] security requirement: as we parse the param we need to ensure its sanitized and do not execute or store any params directly via input from the URL, all logic redirect must be explicitly created by our parser after sanitization and verification checks.
- this requirement excludes the sub url redirect, which needs to be passed onto the application as is, but still requires sanization. In other words, we need to store it to pass it forward to the app, but we should not look to execute it, and must ensure we sanitize it

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
