### ISSUE TITLE
Fix all named exports from JSON modules

### ISSUE THREAD

**Issue by Rleahy22** [department-of-veterans-affairs/va.gov-team#32131]
## Issue Description
In preparation to upgrade Webpack to version 5. There is a breaking change that needs to be fixed before it can be done. Based on the [Webpack migration guide](https://webpack.js.org/migrate/5/), it is important to fix all [named exports from JSON modules](https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules) because it’s no longer supported. This is a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19142) sample of the changes

slack: https://dsva.slack.com/archives/C5HP4GN3F/p1635428396065100

---
## Tasks
Files that need to be updated:
- [ ] Deterrmine if this ticket is obsolete
  - [ ] If so, close
  - [ ] If not, see tasks and AC below
- [ ] src/applications/static-pages/cta-widget/ctaWidgets.js
- [ ] src/applications/static-pages/widget-creators/createMyVALoginWidget.js

## Acceptance Criteria
- [ ] all named exports from JSON modules should be updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by FranECross** [comment]
Added to Next Refinement to confirm if this is obsolete and can be closed.

**Comment by FranECross** [comment]
@Rleahy22 I'm assuming this old ticket is obsolete, but wanted to check before closing. Thanks in advance!

**Comment by FranECross** [comment]
closing old ticket as obsolete.
