### ISSUE TITLE
Updates to intro and booster question on Coronavirus FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32145]
## Issue Description
We updated the content in our intro, meta description, and booster info on the COVID-19 FAQs page. We need to send this text to the translators (the booster content as already been sent for the main vaccine page, so we can use that). 

---
## Tasks
- [x] Update English page (Danielle)
- [x] Review and publish (Randi)
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] English FAQs page is live with changes
- [x] Translated FAQs pages are live with changes

**Comment by RLHecht** [comment]
@lunascoop here is the Spanish translation. And please see my note above for the booster and meta description. Thanks!
[https://app.zenhub.com/files/133843125/f5d06fbc-789f-4410-8959-ce9c62c53daa/download](https://app.zenhub.com/files/133843125/f5d06fbc-789f-4410-8959-ce9c62c53daa/download)

**Comment by lunascoop** [comment]
@RLHecht I've made the changes to the Spanish pages and completed the more tedious changes for the Tagalog page while waiting for the other translations

**Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580**
Updated top 3 questions

- Can I get a COVID-19 vaccine at VA? (had to google translate Learn more about COVID-19 vaccines at VA link)
- Can I get a booster or additional COVID-19 vaccine dose at VA?
- Is there a cure or any FDA-approved treatments for COVID-19? (Re-added from earlier version of mini vaccine page. Also, added sentence from About Covid vaccine page. Also had to Google translate sentence: If you have questions about a treatment, call or send a secure message to your VA provider.)

- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475

- Still awaiting the page intro and meta description translations
- Updated top 3 questions w/ the same comments noted for the Spanish page

**Comment by RLHecht** [comment]
@lunascoop Here's the Tagalog intro.
[14239_COVID-FAQs-intro-change_Tagalog Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7556217/14239_COVID-FAQs-intro-change_Tagalog.Final.docx)

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published both pages. Moving to validate and will send Mateo the live links later today.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket and will reopen if Mateo has any corrections.
