### ISSUE TITLE
[ArgoCD] Argo Events

### ISSUE THREAD

**Issue by rwilliams-oddball** [department-of-veterans-affairs/va.gov-team#32149]
## Description
Currently, when EKS argocd-events containers scale, containers are destroyed and their images are pulled from quay.io instead of ECR.

---
## Tasks
- [x] Create argocd-events github repo
- [x] Create argocd-events repo in Amazon ECR
- [x] Create Github Action mirror tasks
- [x] Add auto-update for YAML

## Acceptance Criteria 
- [x] argo-events:v1.6.0 is mirrored to ECR using github actions
- [x] auto-update yaml config

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd-events/compare/99c0c6bd8bd292bc939d46802894288ba17386f7...8e3a64e630bf7d0d651f7581e6d9f6f8fff21801

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd-events/compare/99c0c6bd8bd292bc939d46802894288ba17386f7...8e3a64e630bf7d0d651f7581e6d9f6f8fff21801

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commits/main/apps/vsp-operations/argo-events/utility

**Comment by jbritt1** [comment]
Installed on utility eks cluster and pipeline in place to mirror images and update manifests. I held off at this time on figuring out the va certificate piece because I am not currently convinced we need them for this service and I think it would take a bit more digging to resolve as the argo-events container image doesn't seem to actually ship with a shell. So running things like `update-ca-certificates` for example does not currently work. Happy to spin off another separate issue for that or even reopen this one if anyone / the team finds it necessary to continue down this path.
