### ISSUE TITLE
Submit Research Plan for Perigean Engagement

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32140]
## Background
In order to better fulfill our UAT sessions we need more participants so we need to reach out to Perigean and see if we can get some Veterans that meet our specific needs.

## Tasks
- [x] Draft a research plan that includes a conversation guide
- [x] Once the research plan is finalized and dates are entered, submit to Lauren Alexanderson

## Acceptance Criteria
- [x] A research plan has been submitted
- [x] a request for Perigean has moved forward
