### ISSUE TITLE
Design intent - Authenticated Experience, Notifications (on VA.gov)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32154]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Schedule meeting via Calendly with VFS team attendees listed in ticket.
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [X] No (not "officially", though Tressa and AJ have met with Ryan to talk through the designs, as well as Kevin Hoffman)

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications#alerts--notifications-on-vagov)
 
 
 
- [x] [Wireframes](https://app.mural.co/t/vsa8243/m/vsa8243/1634064448225/f9f3bb98da6eadf4a648fb30d17d15560950ceab?sender=tressafurner7646)
- [x] Any other artifacts you have so far:
       -  [Design documentation folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/design/design-documentation)
       - [Technical diagrams](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/technical-diagrams/backend-support-for-notifcations-on-vagov.md#backend-support-for-notifications-on-vagov)

### Required
- Product Manager: @ajakabcin 
- OCTO-DE Product lead: @Samara-Strauss 
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- @tressaellen 

### VFS Attendees

- Content and IA: @mnorthuis 
- Accessibility: @joshkimux and/or @AngelaFowler82 
- QA specialists: @tlei123 

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.
