### ISSUE TITLE
EXTERNAL: GET /api/eligibility/documents/coe/file

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32155]
## Background
Once a status has been determined, we need to create a `GET` to be able to provide the actual COE file itself (if the user has one.  Else they will see the N/A screen.

## Considerations
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- Should this be its own call or ...? **Yes, it should be on its own**
- Pass both pieces of user data `edipi` and `icn`

## Tasks
- [ ] Create a service object method that calls the `GET /api/eligibility/documents/coe/file`

## Acceptance Criteria
- [ ] code and tests have been implemented
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
unplanned went before this: 34388 and 34391
