### ISSUE TITLE
Submit Request to DevOps for Network Config

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32156]
`Can be done ahead of time`

## Background
Part of the groundwork for this integration with LGY involved some network configuration with the DevOps folks

## Tasks
- [x] Set up the forward proxy
- [x] get auth token from LGY for INT env and add to AWS
- [ ] [kathleen] check swagger / health-check

## Acceptance Criteria
- [x] Devops setup is complete in the repo
- [ ] A PR has been requested for merging in the devops repo; needs token to be in place (Stretch)
