### ISSUE TITLE
TUD: Evaluate TUD Data Ingestion

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32153]
## User Story

We need to develop a strategy for ingesting data from Test User Dashboard into BigQuery for use in a DOMO hosted TUD Dashboard.

* Number of TUD Testers
* Number of TUD Testers active each day
* Number of searches per TUD Testers per day
* Number of TUD Accounts Checked In from staging.va.gov Logout
* Number of times Help pages are accessed per day
* Most searched TUD Account criteria
* Number of accounts checked in by TUD maintenance job
* Number of TUD Accounts available

## Tasks
- [x] Evaluate TUD data ingestion and recommend an approach.
- [x] Data should be ingested into a schema in BigQuery that enables visualization of the data in DOMO.
- [x] Recommend a schedule for data ingestion by this mechanism.

## Acceptance Criteria

- [x] _Ingestion mechanism provides all the data we need to produce our desired TUD metrics in usable formats._
- [x] _Data is set up to automatically ingest at an acceptable interval._
- [x] _Domo has data connections for all the TUD data that can be used by our cards._

**Comment by holdenhinkle** [comment]
## VETS-API
Metrics are ready to be dashboarded:
- Number of TUD Accounts Checked In from staging.va.gov Logout
- Number of accounts checked in by TUD maintenance job

---

Create a new Sidekiq job on `vets-api` to track this hourly:
- Number of TUD Accounts that are available

Another way of saying this is:
- The number of TUD accounts that are checked out
- Which TUD accounts are checked out

---

GitHub OAuth is required for this:

Create a `vets-api` Sidekiq job to post TUD Tester authentication and authorization events to BigQuery from which we can derive the following metrics:
- Number of TUD Testers
- Number of TUD Testers active each day

## TUD APP
GitHub OAuth is required for this:

- Number of searches per TUD Tester per day
   - _What is a 'search'? The search string? Or filter selections?_

I'll need to create a new TUD endpoint in `vets-api` to post the user/search query to, which will post the data to BigQuery. `vets-api` needs to handle this because we can't store secrets in the TUD (BigQuery auth secrets).

## GA?
- Most searched TUD Account criteria
   - _What is a 'search'? The search string? Or filter selections?_
- Number of times Help pages are accessed per day
   - Should we just track page views for all pages (not only the help page)?
- Number of searches per TUD Tester per day

### Questions for the Analytics Team:
- Is GA setup for TUD?
- Can GA track search queries?
- Can GA track the filtering of TUD accounts

**Comment by holdenhinkle** [comment]
re: Is GA setup for TUD?
I don't see any GA code on a page, but I see lots of GA cookies:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/e8f760da-a50a-41eb-b2a6-a83f7eb19b1f)

**Comment by holdenhinkle** [comment]
I submitted a support request with Analytics about getting GA setup for TUD - https://dsva.slack.com/archives/CBU0KDSB1/p1636380138389400

**Comment by holdenhinkle** [comment]
I submitted a request to the Analytics team, asking them to setup GA on TUD for us - https://github.com/department-of-veterans-affairs/va.gov-team/issues/32617

**Comment by pjhill** [comment]
We are still waiting on Analytics team efforts wrt setting up GA analysis on TUD.

**Comment by pjhill** [comment]
Perhaps, in the future we can collect from user input the VA.gov product that TUD users are going to be testing with the TUD account that they retrieve?

Alternatives --
* Required dropdown selection of all products
* Optional dropdown selection of all products placed in a visually forward location

**Comment by pjhill** [comment]
Donezo
