### ISSUE TITLE
EXTERNAL: GET /api/eligibility/determination

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32152]
## Background
One of the first steps in setting up the backend for the COE application is a `GET` request to determine the eligibility of the Veteran back from LGY.

## Considerations
- There are 4 possible statuses:
  - Eligible
  - Not eligible
  - Pending
  - Unable to be determined automatically*
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- Pass both pieces of user data `edipi` and `icn`

## Tasks
- [x] Create a service object method that calls the `GET /api/eligibility/determination`

## Acceptance Criteria
- [x] code and tests have been implemented
- [x] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
@kathleencrawford:

@jason-gcio was asking today during SU if this could be closed since it's merged. WAs going to close, but since it's yours, I thought I'd leave to you in case you are keeping it around for a reminder...
