### ISSUE TITLE
Discovery: Add custom routing to the form continue button

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32168]
## Description

A new design pattern for list loops would require the form "Continue" button to jump back to a specific path under specific conditions.

```
    ┌───────────────────────────────────┐
    ▼     Y                             │
Add item ──► Followup question 1 ──► question 2
    │ N
    ▼                                        
```

## Tasks

- [ ] Examine platform code to determine if this is feasible
- [ ] Determine if this redirect can be Implemented
- [ ] Write up discovery findings

## Definition of done

- [ ] Discovery complete
- [ ] Custom redirect determined

**Comment by Mottie** [comment]
So, it looks like this is possible, and doesn't require any changes to the platform form system.

This is how it would work (not all details have been worked out):

```
    ┌───────────────────────────────────┐
    ▼     Add/Edit                      │
Main page ────────► loop first ──► loop second
    │ Continue
    ▼                                        
```

## Main page:

- Add a `<Link>` to start the loop.
  - The `<Link>`'s "to" attribute will point to loop page 1 with an appropriate index, e.g. `/loop-first/1`
  - The index would be array length + 1
- Within each item will be an "edit" button that uses a `<Link>` to `/loop-first/{index}` with the given item index
- Also within each item should be a "remove" button
- A "continue"/"back" button are rendered by the form system

## Loop pages

- Added as a Formulate [`CustomPage`](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform) to prevent adding the form navigation ("continue" and "back") buttons
- To save the changes, add a "submit" type button
- A "cancel" button may be useful, but would require not using the `data` provided to the component, and only updating the actual form data if the page is submitted.
- To use the built-in data update, add a `name` property to the Formix `<Field>` using the index from the URL, e.g. `name={`person[${index}].firstName`}
- In the form config file, set the `depends` function for these pages to **depend on an index** at the end of the url - this prevents the page from showing when the Veteran presses "Continue" on the main page, but see the note below
 
**NOTE**: I still need to work out how to ensure this rerouting works as of this writing, it still tries to go to `/loop-first` (without the index) but fails and is rerouted to the start of the form.
