### ISSUE TITLE
Facility operating status should be consistent across products: icon, color and expandable design 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32167]
## User story 
As a Veteran, I need an easy way to see if the facility I am planning to visit has any change in access or services. 

## Issue Description
Facility operating status is currently inconsistently implemented across the products. 

Page | Implementation
-- | --
[Facility locator search results](https://www.va.gov/find-locations/?address=atlanta&bounds%5B%5D%5B%5D=-77.7866&bounds%5B%5D%5B%5D=38.145&bounds%5B%5D%5B%5D=-76.2866&bounds%5B%5D%5B%5D=39.645&context=Atlanta%2C%20Georgia%2C%20United%20States&facilityType=health&latitude=33.7491&longitude=-84.3902&page=1&radius=43&serviceType&bounds%5B%5D=-85.1402&bounds%5B%5D=32.9991&bounds%5B%5D=-83.6402&bounds%5B%5D=34.4991) |  ![image](https://user-images.githubusercontent.com/55411834/139501570-e9aec8a5-ea13-473f-974e-de5a464a11d9.png)
[Facility locator detail page](https://www.va.gov/find-locations/facility/vha_508GA) |  ![image](https://user-images.githubusercontent.com/55411834/139501655-e4439a45-2e2a-4dd4-a3eb-8b678076edbf.png) |
[Vet Center main page](https://www.va.gov/reno-vet-center/) |  ![image](https://user-images.githubusercontent.com/55411834/139500732-be9a42d7-446f-4be4-8637-ea4617e3b19a.png) |
[Vet Center Locations page](https://www.va.gov/reno-vet-center/locations/) |  ![image](https://user-images.githubusercontent.com/55411834/139501280-82d5ca9d-69f4-4592-adda-84cbdc7dcc4f.png) |
[VAMC facility page](https://www.va.gov/atlanta-health-care/) |  ![image](https://user-images.githubusercontent.com/55411834/139501391-8846c540-96af-470f-95db-99720a893f5b.png) |
[VAMC operating status page](https://www.va.gov/atlanta-health-care/operating-status/) |  ![image](https://user-images.githubusercontent.com/55411834/139501449-0597a978-cb24-402c-8999-34666a58286f.png) |

---
## Tasks
- [ ] Determine the right alert to be used (informational or warning) with regard to icon, color and expandability
- [ ] Determine which implementations need to be changes based on style and which need the expandable alert design
- [ ] Update mobile design spec to include the operating status

## Acceptance Criteria
- [ ] Issue for front engineers lists areas needing change as tasks

**Comment by nicko-amida** [comment]
@mmiddaugh I've added my updates to a [UXPin here](https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/documentation/no-panels?mode=i) and will be running these across design office hours tomorrow as well.

**Comment by mmiddaugh** [comment]
Will async on this with design
