### ISSUE TITLE
Check for existing COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32166]
## Background
Once a status has been determined, we need to check the Veteran's documents on LGY to see if a COE exists already so that the UI can show the correct screen.

## Considerations
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- `GET /api​/eligibility​/documents`

## Tasks
- [x] Create a `GET v0/{something_COE-ish}/coe/file`
- [x] Pass in an identifier info (`user.eidpi` (use for now), and/or `icn` at some point; might as well send both if we can)

## Acceptance Criteria
- [x] code and tests have been implemented
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
FE for this may be done and just need to hook up to it
