### ISSUE TITLE
[Vets-API] Investigate latency spike that occurred Monday 10/25 @ 1804-1812 ET 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32165]
## Description
Lighthouse encountered a latency spike to api.va.gov endpoints (specifically to Lighthouse APIs hosted in vets-API in Production) from around 1810-1815 ET on Monday. 

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1635199904280000

## Technical notes
Things we've looked into so far, but have been inconclusive: 
- [ ] Load Balancer logs - showing a spike in 503 (service not available) during the same time 
- [ ] EC2 instances were being cycled b/c of failed health checks 
- [ ] The new EC2 instances that came up performed as expected 
- [ ] Edison Velez mentioned something about surplus CPU credits (see screenshot in linked thread above) 

Things we'd like to look into, and would like some BE Tools team expertise to help with: 
- [ ] Looking at application-level requests to see if what may have been happening

---
## Tasks
- [ ] Discuss w/ BE Tools team and determine if this warrants further investigation 
- [ ] Make Vets-API infrastructure more robust if necessary, or
- [ ] If related to a specific application, consult w/ engineers accordingly 

## Acceptance Criteria 
- [ ] Root cause has been determined 
- [ ] Additional issues have been created to follow up _(as needed)_

**Comment by jhouse-solvd** [comment]
@f1337 or @dginther  - Can you help us make a good determination here to ensure that we follow up as needed?

**Comment by jhouse-solvd** [comment]
This has become part of a wider discussion and ongoing investigation. Michael Fleet will have more up to date information if anyone needs it. 

Closing.
