### ISSUE TITLE
Fix all named exports from JSON modules

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#32177]
## Issue Description
In preparation to upgrade Webpack to version 5. There is a breaking change that needs to be fixed before it can be done. Based on the [Webpack migration guide](https://webpack.js.org/migrate/5/), it is important to fix all [named exports from JSON modules](https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules) because it’s no longer supported. This is a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19142) sample of the changes

slack: https://dsva.slack.com/archives/CLY6Q69RV/p1635427903022400

---
## Tasks
Files that need to be updated:
- [x] src/applications/static-pages/vre-chapter36/Chapter36CTA.js
- [x] src/applications/static-pages/dependency-verification/tests/dependency-verification.cypress.spec.js

## Acceptance Criteria
- [x] all named exports from JSON modules should be updated
