### ISSUE TITLE
Generate unit tests for infinite loop bug

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#32179]
## Issue Description
This ticket describes the issue that was observed. The thread that speaks more to this can be found here: https://dsva.slack.com/archives/CBU0KDSB1/p1635519420020300?thread_ts=1635364760.385900&cid=CBU0KDSB1

The reality is that we likely will not be able to generate accounts which have never logged into vagov and are verified by MHV or DSLogon in an automated way within any reasonable time period. For now we need to find a way to run unit tests against this situation. This ticket requires that we have regression tests built into vets-website to ensure future changes do not cause this bug to occur again.

## Tasks
- [x] Create unit tests to ensure `setLoginAttempted` is set when clickedEvent is `login-link-clicked-modal || sso-automatic-login`
- [x] Create unit test to ensure `setLoginAttempted` is not set for unified sign in page redirecting to external apps

## Acceptance Criteria
- [x] Create unit tests to safeguard against infinite login loops
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
