### ISSUE TITLE
[FE] Add BTSSS link to appointment confirmation screen

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32174]
## How to configure this issue

- [x] Attached to an Epic (what body of work is this a part of?)
- [x] Correctly Labeled
- [x] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [x] Fill in Acceptance Criteria

---

## User Story

As a veteran I would like to be able to access BTSSS during the check in process so that I can file my claim for travel reimbursement. 

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

We need to add a link to BTSSS to the appointment confirmation screen so that when a veteran gets to that screen they can also click the link to access BTSSS and file their travel claim. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

1. The link to BTSSS is accessible on the appointment confirmation screen.
2. When I click the BTSSS link I am navigated to the BTSSS website. 

Link:
https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by julieadair1** [comment]
duplicate
