### ISSUE TITLE
[Jenkins] Assist FE Tools team w/ disabling {content-build, vets-website} daily deploys 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32170]
## Description
The FE Tools team has been working on a larger initiative this year to transition the daily deploy jobs in Jenkins for the content-build and vets-website to pipelines using GitHub Actions. They are now ready to disable the daily deploy jobs in Jenkins for the aforementioned components and are requesting help from the Platform Operations team to ensure that the transition goes smoothly. 

The FE Tools team will be submitting PRs to modify the Jenkins seed jobs (ie seed_job.groovy or similar). The Platform Operations support engineer will need to apply changes to Jenkins manually _(or otherwise ensure they are applied through a fresh deployment)_. 

The FE Tools team is asking for available Platform Operations support personnel to be available to support with the following modifications at the following dates and times: 

- content-build: Monday,  November 8, 2021 ~330 EST
- vets-website: Thursday, November 4, 2021 ~330 EST

 
## Background/context 
Please see [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24191) and the linked open/draft PRs for add'l context

## Technical notes
Because of how Jenkins deploys work, we may need to manually apply the change to Jenkins and ensure that it's picked up. Several of the Platform Operations team members will be familiar with this process and can provide technical information or instructions. 

---
## Tasks
- [x] Coordinate w/ the FE Tools team to understand the changes prior to the scheduled time
- [x] Approve PRs if necessary, and...
- [x] Apply the changes to Jenkins 
- [x] Verify that the daily deploy jobs for the following have been modified at the date and time listed: 
  - [x] content-build on Monday, November 1, 2021 ~330EST
  - [x] vets-website on Thursday, November 4, 2021 ~330EST

## Acceptance Criteria 
- [ ] Content-build daily deploy job has been disabled according to the schedule above
- [ ] Vets-website daily deploy job has been disabled according to the schedule above
- [ ] FE Tools team validates the changes

**Comment by oseasmoran73** [comment]
Update to ticket:

[PR](https://github.com/department-of-veterans-affairs/devops/pull/10183) for The timeline for `content-build` has changed. Originally scheduled for Monday November 1 has now been postponed to November 8

**Comment by oseasmoran73** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/10215) for tomorrow (Thur Nov 4) for `vets-website`

**Comment by oseasmoran73** [comment]
Closing ticket as `crons` have been disabled in Jenkins and enabled in Github Actions. Huge thanks for helping us Ops!
