### ISSUE TITLE
Link to decision reviews page from the VA.gov landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32178]
## Issue Description

Stakeholder Carolyn Temple reached out with a decision reviews request. Currently there is still important AMA information on https://benefits.va.gov/benefits/appeals.asp and links to all their promotional products. She is asking if we can link to this page from our [decision reviews](https://www.va.gov/decision-reviews/https://www.va.gov/decision-reviews/) hub landing page or bring the content over. Currently the TeamSite page is not searchable and only accessible by going through an intranet link.

Update: We are going to link to https://benefits.va.gov/benefits/appeals.asp from the More information and resources section of our decision reviews landing page. We'll need to write teaser text for this.

## Tasks
- [x] Create teaser text for decision reviews page
- [x] Make updates in Drupal 
- [x] Send changes to stakeholder for review 
- [x] Review and publish 
- [x] Notify stakeholder that changes are live (Beth/Randi)

## Acceptance Criteria
- [x] New link is on live decision reviews landing page

**Comment by RLHecht** [comment]
Pulling this into Sprint 63

**Comment by lunascoop** [comment]
@RLHecht Please review the link and teaser text added to this page. Thanks!

VA decision reviews and appeals: http://preview-prod.vfs.va.gov/preview?nodeId=3071

**Comment by RLHecht** [comment]
@bethpottsVADEPO This is ready for you.

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht Thanks for getting this in drupal. Could you update with this text?:

The Appeals Modernization Act
Learn more about how this law improves the decision review process.

**Comment by lunascoop** [comment]
@RLHecht I updated the link teaser.

**Comment by RLHecht** [comment]
Thanks! @bethpottsVADEPO Let me know if I should send this to the stakeholders to review.

**Comment by RLHecht** [comment]
This is waiting on the stakeholder to confirm if a report we are linking to is 508 compliant.

**Comment by RLHecht** [comment]
Moving to sprint 64

**Comment by RLHecht** [comment]
Waiting for stakeholder approval

**Comment by bethpottsVADEPO** [comment]
I sent an email to the SME so they can have a look at the preview link before we set this to go live.

**Comment by RLHecht** [comment]
Waiting for Tanekwa to make updates that she has for all the benefits.va.gov pages that are linked to off of this page.
