### ISSUE TITLE
[VAMC] Review KB article for Archiving of Facility, format, work flow, and content [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32182]
## Story
As a VAMC editor I need instructions on how to archive a facility that is closing, so I know the proper work flow and communication process.

## TASK
Review KB work flow and documentation, and content and provide back to CMS for input into CMS
- [ ] Review process flow
- [ ] Review KB instructions and standard format
- [ ] Review content for plain language and writing style.

## Acceptance Criteria
- [ ] final draft with mark up document for improvement.
