### ISSUE TITLE
Remove instances of RAMP from VA.gov

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32181]
## Issue Description
Stakeholder Carolyn Temple asked us to remove all mentions of the Rapid Appeals Modernization Program (RAMP) from our pages as the program was sunset more than 2 years ago. 

## Tasks
- [x] Ask Public Websites to do search of Rapid Appeals Modernization Program and RAMP (Selina)
- [x] Remove mentions on Drupal pages (Selina)
- [x] Review and publish (Randi)
- [x] Reach out to authenticated teams for removal in apps and tools (Randi)
- [ ] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Rapid Appeals Modernization Program (RAMP) is no longer mentioned on VA.gov

**Comment by lunascoop** [comment]
@RLHecht here are the instances I've found on VA gov.
https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/ (alert box)
https://www.va.gov/resources/what-your-decision-review-or-appeal-status-means/ (the fourth from the bottom of the Legacy appeal status table)

**Legacy page**
https://benefits.va.gov/benefits/appeals-ramp.asp

**Comment by RLHecht** [comment]
Adding this page too: https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/ (in the alert box)

**Comment by lunascoop** [comment]
@RLHecht the RAMP mentions have been deleted from these pages and are ready for review.

- What your decision review or appeal status means: http://preview-prod.vfs.va.gov/preview?nodeId=9626
- Board hearings with a Veterans Law Judge: http://preview-prod.vfs.va.gov/preview?nodeId=3010
- Board of Veterans' Appeals (BVA) hearing: http://preview-prod.vfs.va.gov/preview?nodeId=902

**Comment by RLHecht** [comment]
These pages have been reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
Page is live. Closing ticket. FYSA @bethpottsVADEPO
