### ISSUE TITLE
[FE] Sunset covid-vaccine-updates-cta page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#32191]
## User Story

The [covid-vaccine-updates-cta](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/static-pages/covid-vaccine-updates-cta) page is no longer in use and should be removed, per @stephenBarrs.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] page has been removed
- [ ] any existing references/usages of the page have been removed
- [ ] Create or update e2e tests

## Acceptance Criteria

> when is the ticket done

- [ ] page has been removed
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
