### ISSUE TITLE
[FE] Replace named exports from JSON modules in covid-vaccine-updates-cta

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#32190]
## Issue Description
In preparation to upgrade Webpack to version 5. There is a breaking change that needs to be fixed before it can be done. Based on the [Webpack migration guide](https://webpack.js.org/migrate/5/), it is important to fix all [named exports from JSON modules](https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules) because it’s no longer supported. This is a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19142) sample of the changes

slack: https://dsva.slack.com/archives/C5HP4GN3F/p1635428396065100

---
## Tasks
Files that need to be updated:
- [ ] `src/applications/static-pages/covid-vaccine-updates-cta/On.jsx`

## Acceptance Criteria
- [ ] all named exports from JSON modules should be updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
