### ISSUE TITLE
Add information about zip codes to addresses entry of style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32208]
## Issue Description
We need to specify in the content style guide when the extra four digits of a zip code are needed. The example we show in the [addresses](https://design.va.gov/content-style-guide/dates-and-numbers#addresses) section uses five digits. But the example we show in the [address block component](https://design.va.gov/components/address-block) has the zip code plus 4 digits. This can be confusing to editors and designers. 

We need to clarify that only five digits are needed when we're asking Veterans for information. The extra four digits are used (but not required) when we list addresses for Veterans to send mail to or for physical office locations.

We should think about using a different example for the address block component so that it doesn't look like the extra four digits are required. 

## Tasks
- [x] Update style guide entry to explain when extra four digits are needed (Randi)
- [x] Change example in address block component (Randi)
- [x] Review and merge PR

## Acceptance Criteria
- [x] New content is in addresses section and in address block component

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO I added the info about the extra four digits to the address section of the style guide. Here's the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/570

**Comment by RLHecht** [comment]
PR was reviewed and merged. Moving to validate and will close once changes are live.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
