### ISSUE TITLE
[VAMC] Create Lighthouse API csv file for Post Production Systems that went live on November 17th [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32227]
## Story
As a Veteran looking for VAMC facilities and COVID-19 Vaccines on Facility Locator I need the correct URL link, so it will take me to the new VAMC websites.

## Goal
Create a repeatalbe process of creating the Lighthouse API url csv file that will be loaded to VAMC SharePoint for Lighthouse API

## Resources
[Previous Lighthouse API files](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FLighthouse%5FAPI%5Ffiles&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## TASKS
**Transform all system facilities in Post production**
- [x] Create file with these headers (Facility_ID;URL;COVID-19_Vaccine_URL)
- [x] Load unique facility ID, new VAMC Facility URL, and same System URL for each system that have gone live
- [x] VISN 12	VA Madison health care	
- [x] VISN 12	VA Milwaukee health care	
- [ ] VISN 12	Lovell Federal Health Care	
- [x] VISN 20	VA Portland health care		X Moved from previous date
- [x] VISN 20	VA Walla Walla health care	
- [x] VISN 22	VA New Mexico health care	
- [x] VISN-7	VA Atlanta health care	
- [x] VISN 1	VA Central Western Massachusetts health care	
- [x] VISN 1	VA Providence health care	
- [x] VISN 1	VA Boston health care	
- [x] VISN 10	VA Central Ohio health care	aka Columbus
- [x] VISN 10	VA Indiana health care	
- [x] VISN 12	VA Hines health care	
- [x] VISN 12	VA Iron Mountain health care	
- [x] VISN 12	VA Chicago health care	
- [x] VISN 15	VA Columbia Missouri health care	
- [x] VISN 15	VA Marion health care	
- [x] VISN 15	VA St Louis health care	
- [x] VISN 17	VA Texas Valley health care	
- [x] VISN 17	VA North Texas health care	
- [x] VISN 17	VA Amarillo health care	
- [x] VISN 17	VA El Paso health care	
- [x] VISN 20	VA Alaska health care	
- [x] VISN 20	VA Southern Oregon health care	
- [x] VISN 22	VA Greater Los Angelos health care	
- [x] VISN 22	VA Phoenix health care	
- [x] VISN 22	VA Northern Arizona health care	
- [x] VISN 8	VA Bay Pines health care	
- [x] VISN 8	VA West Palm Beach	
- [x] VISN 8	VA Caribbean health care	
- [x] VISN 9	VA Mountain Home health care	
- [x] VISN 9	VA Lexington health care	
- [x] VISN 9	VA Louisville health care	
- [x] VISN-7	VA Dublin health care	

## Acceptance Criteria
- [ ] .csv file created with required column headers and facility URL information
- [x] All URLs are tested to make sure they are correct
- [ ] .csv file is loaded to VAMC Sharepoint File (Lighthouse API redirects)

**Comment by ltrombley** [comment]
Task #32227 - Create Lighthouse API csv file for Post Production Systems that went live on November 17th [BA]  - is Complete - PENDING reply to questions on vamc-support channel - moved to BLOCKED

**Comment by ltrombley** [comment]
NOTE: VA Lovell Federal health care cannot be done at this time b/c it is still pending Publishing in Dual-state

**Comment by ltrombley** [comment]
Task #32227 - Create Lighthouse API csv file for Post Production Systems that went live on November 17th [BA] - is Complete and moved to Validate - Updates made per reply from Atlanta.
