### ISSUE TITLE
[VAMC] Web Authorization document and web form completed for November 17th Full producction cut over [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32223]
## Story
As an editor I need to know of any additional final clean up items and barriers, and all tech-debt needs to be resolved, so MVP is present and/or I can clean them up prior to Go Live

## Goal
Investigate and fill in data needed for Web Authorization web form that will be submitted to VHA DM for approval

## Resources
[PAO Directory & Training contact list](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FWeb%5FAuthorizations&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## Task
**Prepare the following Systems for Full Production/Redirect from Legacy URL**
- [x] VISN 12	VA Madison health care	
- [x] VISN 12	VA Milwaukee health care	
- [ ] VISN 12	Lovell Federal Health Care	
- [x] VISN 20	VA Portland health care		X Moved from previous date
- [x] VISN 20	VA Walla Walla health care	
- [x] VISN 22	VA New Mexico health care	
- [x] VISN-7	VA Atlanta health care	
- [x] VISN 1	VA Central Western Massachusetts health care	
- [x] VISN 1	VA Providence health care	
- [x] VISN 1	VA Boston health care	
- [x] VISN 10	VA Central Ohio health care	aka Columbus
- [x] VISN 10	VA Indiana health care	
- [x] VISN 12	VA Hines health care	
- [x] VISN 12	VA Iron Mountain health care	
- [x] VISN 12	VA Chicago health care	
- [x] VISN 15	VA Columbia Missouri health care	
- [x] VISN 15	VA Marion health care	
- [x] VISN 15	VA St Louis health care	
- [x] VISN 17	VA Texas Valley health care	
- [x] VISN 17	VA North Texas health care	
- [x] VISN 17	VA Amarillo health care	
- [x] VISN 17	VA El Paso health care	
- [x] VISN 20	VA Alaska health care	
- [x] VISN 20	VA Southern Oregon health care	
- [x] VISN 22	VA Greater Los Angelos health care	
- [x] VISN 22	VA Phoenix health care	
- [x] VISN 22	VA Northern Arizona health care	
- [x] VISN 8	VA Bay Pines health care	
- [x] VISN 8	VA West Palm Beach	
- [x] VISN 8	VA Caribbean health care	
- [x] VISN 9	VA Mountain Home health care	
- [x] VISN 9	VA Lexington health care	
- [x] VISN 9	VA Louisville health care	
- [x] VISN-7	VA Dublin health care	

_
## Complete the following tasks for all systems listed above:
- [x] Complete Web Authorization data sheet to include two POCs with email, phone, and address.

**Final**
- [x] Submit Data into Web Authorization form, copy image into e-mail to be submitted to VHA for approval
- [x] Send email with images for confirmation

## Acceptance criteria
- [x] Web Authorization sheet is saved in SharePoint Folder with date
- [x] All Systems are submitted into Web Authorization web form
- [x] images are copied into document of email for later submission as required.

**Comment by ltrombley** [comment]
Web Authorization document and web form completed for November 17th Full production cut over [PM]#32223 - is Complete, moved to Validate

**Comment by ltrombley** [comment]
All Systems listed validated.
