### ISSUE TITLE
EXTERNAL: `GET /api/eligibility/application`

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32230]
## Background
One of the first steps in setting up the backend for the COE application is a `GET` request to find out if there is an active application already

## Considerations
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- Pass both pieces of user data `edipi` and `icn`

## Tasks
- [x] Create a service object method that calls the `GET /api/eligibility/application`

## Acceptance Criteria
- [x] code and tests have been implemented
- [x] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
@kathleencrawford:

@jason-gcio was asking today during SU if this could be closed since it's merged. WAs going to close, but since it's yours, I thought I'd leave to you in case you are keeping it around for a reminder...
