### ISSUE TITLE
INTERNAL - `GET v0/coe/download`

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32232]
## Background
Part of COEs ongoing API integration, this returns the COE back if available. 

## Considerations
- ~~stream the file back gross~~, just send a link from the S3 location

## Tasks
- [x] create endpoint to ~~stream file back~~ send a link to client using existing service object method

## Acceptance Criteria
- [x] code and tests have been implemented
- [x] A PR has been requested for merging
