### ISSUE TITLE
INTERNAL - GET `v0/coe/status`

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32231]
## Background
This should pass back the application status, if known, from and to the FE.

## Considerations
- response payload should include:
  - status
  - coe_file_exists (possibly, but FE may derive from status) TBD
  - eligible, ineligible, pending, not able to determine eligibility
  - eligibility determination and application status

## Tasks
- [x] create endpoint to determine eligibility and application status

## Acceptance Criteria
- [x] code and tests have been implemented
- [ ] A PR has been requested for merging
