### ISSUE TITLE
VETS_API_ENDPOINT - POST v0/coe/application

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32234]
## Considerations
- does this need to go in a job? (beware of long response times like VRE/VBMS multipalooza)
- extra exception handling for LGY?

## Tasks
- [ ] create endpoint to submit 26-1880 COE form

## Acceptance Criteria
- [ ] code and tests have been implemented
- [ ] A PR has been requested for merging
