### ISSUE TITLE
EXTERNAL: PUT /api/eligibility/application/{id}

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32233]
## Background
Make service object method that calls LGY API to PUT the submitted form we receive from the FE.

## Considerations
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- Pass both pieces of user data `edipi` and `icn`
- Will we need to manipulate any FE data schema to match the LGY api schema????

## Tasks
- [ ] Create a service object method that calls the `PUT /api/eligibility/application/{id}`

## Acceptance Criteria
- [ ] code and tests have been implemented
- [ ] A PR has been requested for merging

**Comment by alsleaders** [comment]
Work on this was delayed by LGY's backend services being down much of last week.

**Comment by jason-gcio** [comment]
- schema changes needs to be before this ticket, which is before #32234

**Comment by alsleaders** [comment]
Closing this ticket because the PR was merged!
