### ISSUE TITLE
Mental Health Care is not displayed under "Health services offered here" 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32241]
## Issue Description
Portland is missing "Mental Health" from their list of health services on production although "Mental Health" is shown as published in Drupal.

Portland VA Clinic shows as expected in the Mental Health Care accordion on [Portland system health services page](https://www.va.gov/portland-health-care/health-services/) but Mental Health Care is not displayed under "Health services offered here" on the [Portland VA clinic facility page](https://www.va.gov/portland-health-care/locations/portland-va-clinic)

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/139689410-d06bd6c4-491e-4c5d-a6d1-880cde57e7bd.png)

![image](https://user-images.githubusercontent.com/55411834/139689498-b31b1314-cd2d-48ac-9781-ae157e97492c.png)

![image](https://user-images.githubusercontent.com/55411834/139691871-ce973546-6d0d-4c6d-b120-b0cb52120ee3.png)

![image](https://user-images.githubusercontent.com/55411834/139691964-41a66134-1105-4abc-8ab5-a2ef5499c5b4.png)

![image](https://user-images.githubusercontent.com/55411834/139692124-1e37a28b-d34e-4cd8-974b-55d2ec35685b.png)

![image](https://user-images.githubusercontent.com/55411834/139692943-60bc7999-1a15-425b-9727-93039320ce3a.png)

</details>

## Steps to reproduce

1. View [VA Portland health care > Health services ](https://www.va.gov/portland-health-care/health-services/)
2. Scroll down and open Mental health accordion
3. Observe Portland VA Clinic appears on the "Available at these locations" list
4. View [VA Portland health care > Locations > Portland VA Clinic ](https://www.va.gov/portland-health-care/locations/portland-va-clinic/)
5. Observe "Mental health care" is not included in the "Health services offered here" list
6. View Drupal node -observe that Mental health care was published previously and is now in draft mode

---
## Tasks
- [ ] Resolve bug

## Acceptance Criteria
If a health services is published,
- [ ] it should be listed as a "Health services offered here" on the facility page(s) for which it is published
- [ ] the facilities  for which it is published should appear in the "Available at these locations" list within that service accordion on the system page
- [ ] new edits saved in "draft" mode should not change published status of health service

**Comment by mpelzsherman** [comment]
Here is an abriged version of the query we are using to pull the data from Drupal.
Note that only 3 services are listed for this location:
1.  "Homeless Veteran care",
2. "Primary care"
3. "Social work"

These correspond to the services rendered on the page.

<details>
```graphql
fragment healthCareLocalFacilityPage on NodeHealthCareLocalFacility {
  fieldLocalHealthCareService {
    entity {
      ... on NodeHealthCareLocalHealthService {
        status
        fieldBody {
          processed
        }
        fieldRegionalHealthService {
          entity {
            ... on NodeRegionalHealthCareServiceDes {
              status
              entityBundle
              fieldServiceNameAndDescripti {
                entity {
                  ... on TaxonomyTermHealthCareServiceTaxonomy {
                    entityId
                    entityBundle
                    fieldAlsoKnownAs
                    fieldCommonlyTreatedCondition
                    name
                     parent {
                      entity {
                        ... on TaxonomyTermHealthCareServiceTaxonomy {
                          name
                        }
                      }
                    }
                    fieldHealthServiceApiId
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

{
  nodeById(id: "2009") {
    ...healthCareLocalFacilityPage
  }
}
```
</details>

However, when I view https://prod.cms.va.gov/portland-health-care/locations/portland-va-clinic, I do see Mental health care listed.

<details>
![Portland_VA_Clinic___VA_Portland_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/139721216-12fa8646-8ae0-430f-84d2-c41d7b54af72.png)
</details>

Still investigating...

**Comment by mpelzsherman** [comment]
@kevwalsh [says](https://dsva.slack.com/archives/C0FQSS30V/p1635792051165600?thread_ts=1635791969.165500&cid=C0FQSS30V) "yeah it all looks good to me, too, on the data side."

So I'm blocked on this one, sorry.

**Comment by swirtSJW** [comment]
Summarizing from here
https://dsva.slack.com/archives/C0FQSS30V/p1635791969165500

1. Tried re-publishing as there was an odd revision. No success.
2.  Validated that we are not seeing an off-by-one error.
3.  Deleted node/25502 was deleted and /node/37803 was created to replace it 

Waiting for the next content release to see if number 3 fixed it.

**Comment by swirtSJW** [comment]
Recreating solved the issue and we are now good on prod. 
![image](https://user-images.githubusercontent.com/5752113/139947028-2764184a-c3c6-4102-989a-da0eeb4a0345.png)
I am closing this issue.
