### ISSUE TITLE
Fix broken link on CHAMPVA page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32242]
## Issue Description
A SiteImprove report showed we have a broken link on the [CHAMPVA benefits](https://www.va.gov/health-care/family-caregiver-benefits/champva/) page. 

Under the section "What happens after I apply?" the link for "Download application instructions (PDF)" is broken. 

We need to reach out to the business line to update this link on our page. 

## Tasks
- [ ] Get new application link (Randi/Danielle)
- [x] Update link in Drupal (Selina)
- [x] Check for sighted language and bulleted list changes (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Link no longer broken on live page

**Comment by RLHecht** [comment]
@lunascoop Can you just remove the link from this section for now? Thanks!

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

http://preview-prod.vfs.va.gov/preview?nodeId=9

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
