### ISSUE TITLE
Design for Vet Center "official name"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32246]
## Issue Description
In some cases, the "official" (legislative or ceremonial) name of a Vet Center is not how the facility is known locally. Vet Center pages need to display both names to honor the official name while making the page findable and locally recognizable. 
For example,[ "Dr. Cameron K. McKinley Vet Center" is locally known as "Prescott Vet Center"](https://www.va.gov/prescott-vet-center/).

Similar situations exist across VA.gov, particularly in the forms system, where forms are identified by number and the name/purpose of the form. Example: [About VA Form 21-686c](https://www.va.gov/find-forms/about-form-21-686c/) 

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/139705397-950f9b73-4c92-49ec-ab5a-a4faa44afa31.png)

![image](https://user-images.githubusercontent.com/55411834/139706027-be5a335c-43e9-40ad-9c33-f17b564c5262.png)

</details>

**Related issues** 
#31530 added the "Official name" field to the Vet Center front end query 

---
## Tasks
- [x] Review other similar implementations across VA.gov and guidance from Design system
- [x] Create basic engineering spec for front end engineers, including font size and padding for Vet Center main page

## Acceptance Criteria
- [x] Engineers know how to display official name on Vet Center pages
---
[UXPin specs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32246#issue-1041360441) are here! See comments for another example of the subheading in use - Nick O

**Comment by nicko-amida** [comment]
Here's an [example of a sub-heading under an H1](https://www.va.gov/disability/file-disability-claim-form-21-526ez/start), and it includes and existing class for engineering!

**Comment by nicko-amida** [comment]
Some recent feedback from collab cycle office hours: the rule is to use the official name in breadcrumbs and URL, but for now this remains an exception.
