### ISSUE TITLE
[Prod Readiness] 11/01 Production release checklist

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#32250]
## vets-website Checklist
- [ ] Testing passed in Staging

## vets-api Checklist
- [ ] Testing passed in Staging

## CHIP Checklist
- [ ] Testing passed in Staging

## LoROTA Checklist
- [ ] Testing passed in Staging
