### ISSUE TITLE
HLR: move wizard to `/start` in production

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32269]
## Description

Clean up Higher-Level Review code so that the HLR wizard now appears in production. Because of routing issues, a simple feature flag would not work.

## Tasks

- [ ] Remove production environment checks in HLR wizard code
- [ ] Remove production environment checks in router

## Definition of done

- [ ] All production environment checks are removed from HLR wizard & router
- [ ] All tests passing

**Comment by Mottie** [comment]
Verified working in production (sorta, I don't have any contestable issues to start HLR).
