### ISSUE TITLE
Synthesis- Unmoderated Research Sign-in modal and provider attributes

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#32268]
## Issue Description
_UX synthesis for unmoderated study (first click and card sort) for the VA.gov sign-in modal redesign and the sign-in provider attributes._

---
## Tasks
- [x] Closeout studies
- [x] Pull down data from First Click study by segment group
- [x] Pull down data from Card Sort study by segment group
- [x] Highlight top findings
- [x] Review findings

## Acceptance Criteria
- [x] Highlight answers to research questions and hypotheses in read-out to stakeholders

**Comment by Vngpire** [comment]
Card Sort Attribute Research Findings

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login.gov/Login.gov-Sign-In-Attributes-Card-Sort-Research-Findings.md

**Comment by Vngpire** [comment]
Unmoderated Research Sign-in modal and provider attributes data.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login.gov/Login.gov-Sign-In-Attributes-Card-Sort-Data.xlsx

**Comment by APorter-Clarity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login.gov/SignIn%20Redesign-Research-Findings-Synthesis.md

**Comment by allison0034** [comment]
@APorter-Clarity thank you! I see you did research around the buttons being blue and including the logo, but the link provided to us to review is the colored buttons an no logo. Have you tested around that UI?

**Comment by APorter-Clarity** [comment]
@allison0034 the design provided is what came as a result of this study and a previous one. This design revision/solution came as a result of feedback from the VA lead (Cody Reynolds), the design lead (Ryan Thurlwell) and accessibility specialist (Martha Wilkes)
