### ISSUE TITLE
Convert MPI-sourced Attributes to Identity - Part 1

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#32270]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
User attributes are sourced from a combination of the SAML header response from ISAM and a query to MPI - most of this information is duplicated across both sources. We plan to refactor the remaining attributes that are sourced from MPI to come from ISAM so that we can remove that call entirely, which will simplify vets-api's architecture and increase login speeds.

This is the first part of that change. The following user attributes that come from MPI
```
  attribute :home_phone, String
  attribute :address, MviProfileAddress  
	  attribute :street, String
	  attribute :city, String
	  attribute :state, String
	  attribute :postal_code, String
	  attribute :country, String
  attribute :suffix, String
  attribute :vha_facility_ids, Array[String]
  attribute :vha_facility_hash, Hash
  attribute :cerner_id, String
  attribute :cerner_facility_ids, Array[String]
```
are confirmed to currently also be passed to vets-api from ISAM, and should be able to be updated to derive their values from the ISAM headers without any adverse impacts or special considerations.

---
## Tasks
- [x] update the above User attributes to source from ISAM headers instead of MPI
- [x] preserve existing MPI value calls as a backup in the same manner as other User attributes
- [x] update existing unit specs to cover the change in data source

## Acceptance Criteria
- [ ] The above User attributes will have their values set upon login through the User Identity
- [ ] The User model will refer to the User Identity model (Redis) when looking up one of the above attributes
- [ ] The User model will refer to MPI if it does not find one of the above attributes in Redis

**Comment by nsoutouras** [comment]
Nick note: When a user logs in, certain SAML header attributes come from login.   MPI (address, etc...).  This ticket reduces MPI calls and eliminates making duplicate calls.  Improves performance.

**Comment by nsoutouras** [comment]
Waiting for review
