### ISSUE TITLE
[BE] Bug: Potential session conflict when a user is fully authenticated user and also performing check-in

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#32276]
## Description
During Next of Kin testing in production, we noticed an issue when checking in a test user. It gave the generic error when clicking on the check in button: "We couldn't check you in ... please check in with a staff member", even though we had run the same scenario successfully a couple of times. We think the likely cause is that @stephenBarrs who was doing this test logged in to va.gov with a full user which might have overwritten the session cookie.

This is a very rare scenario unlikely to happen as the users who are checking in are not required or expected to log in through va.gov

Question: What percent of users who are using (or will be using) the check-in functionality have the va.gov user account?

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [ ] reproduce the scenario in staging
- [ ] discuss possible root causes and fixes
- [ ] implement fix

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by julieadair1** [comment]
@jparker0425 - how do we handle bugs related to epics?  Do we link them to the original epic?  Create a new one?

**Comment by dillo** [comment]
UI/UX is looking at this as a potential edge case for now. I recommend revisiting this issue in the future when it's more relevant to the user experience.
