### ISSUE TITLE
Remove unusable code and fix format for SubmitSignInForm 

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#32271]
## Issue Description
Verify page has some unnecessary code that is unreachable by passing children into `SubmitSignInForm` which does not render children. 

Also a small spacing fix should be made between `help at <phoneNumber>`

---
## Tasks
- [ ] Remove children being specified in SubmitSignInForm at VerifyApp.jsx
- [ ] Add a space in SubmitSignInForm between copy and phone number

## Acceptance Criteria
- [ ] Useless code removed
- [ ] Spacing corrected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
