### ISSUE TITLE
[Design] Profile: Schedule handoff meeting with Kevin Hoffman

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32284]
## Issue Description
As a new designer, I want to schedule a handoff meeting with Kevin Hoffman so he can give me an overview of the mock-ups he created for Personal Information Revision and where he left off.

---
## Tasks
- [x] Schedule meeting with Kevin Hoffman

## Acceptance Criteria
- [x] Handoff meeting has been held and Christina has familiarity with the mockups
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Christina & Kevin held their handoff meeting; closing ticket.
