### ISSUE TITLE
Collaboration Cycle Dashboard Design Standards Updates

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32283]
# Description
Reference the [Creating dashboards in DOMO](https://vfs.atlassian.net/wiki/spaces/AT/pages/1543602218/Creating+dashboards+in+Domo) and [Data Viz Design Tips for DOMO](https://vfs.atlassian.net/wiki/spaces/AT/pages/1408762356/Data+Viz+Design+Tips+for+Domo) documents that he Analytics team created in order to create a more accessible Collaboration Cycle Dashboard design.

## Tasks
- [x] Consume the best practices and standards documents
- [x] Design a change to the existing dashboard that complies with standards and best practices
- [x] Work with Shira to create additional explanatory text if needed
- [x] Consult Shira regarding design changes

**Comment by rjohnson2011** [comment]
@pjhill @shiragoodman  I’ve made modifications to the Collaboration Cycle Dashboard in accordance to VA’s Domo Design Standards (https://vfs.atlassian.net/wiki/spaces/AT/pages/1408762356/Data+Viz+Design+Tips+for+Domo). 

The following changes have been made:
- Updated Color scheme to include only colors from Design Standard’s Color Palette.
- Modified the Total Issues by Teams chart to be a Horizontal Bar chart in to fulfill the ‘Chart Suggestions’ for many items.
- Team Names must be displayed horizontally as opposed to an angle per “Labels should always be horizontal.” (Team names do not fit horizontally with the Nested Bar Graph chart as well).
- Font size is larger.
- The Donut chart is removed (not a recommended chart) in favor of a Pie chart.

I placed the new charts at the bottom of the Collaboration Cycle page for review and comparison. Please let me know how this looks when you have a free moment. https://va-gov.domo.com/page/1340527018

**Comment by shiragoodman** [comment]
@rjohnson2011 this looks good to me. The only concern I have is that you can't see the total number of issues per team in the first chart. Is there a way to add that? If not, please let me know. It's not a deal breaker, just a nice to have.

**Comment by rjohnson2011** [comment]
Absolutely, just revised the new `Issues by Team Name` chart to include nested metrics. 

Prior charts have been removed.
