### ISSUE TITLE
[PM, Design, FE, BE] On-site Notifications: Define/share high level MVP direction with VA Notify

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32281]
## Background
The team needs to meet with our VA Notify partners to discuss our high-level MVP direction for on-site notifications

## Tasks
- [x] (PM, Design, Devs) Regroup as a team internally to document our thoughts
- [x] (PM) Schedule meeting with VA Notify
- [ ] (PM, Design, Devs) Meet with VA Notify to discuss/share MVP

## Acceptance Criteria
- [x] High level [MVP requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) are documented in GH
- [x] Schedule recurring meetings to continue discussions

**Comment by ajakabcin** [comment]
Removing from sprint as team is pivoting on this work at the moment.

**Comment by hdjustice** [comment]
A Biweekly meeting is scheduled (next is Tues 12/7).  Pending VA Notify contracting issues to be resolved, which is causing a bit of a hold on this work.
