### ISSUE TITLE
Phase 2 -Forms Research

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#32298]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [x] Should 526 (and other lengthy forms) be broken into segments?
- [x] Explore length - Compare with best practices.
- [x] Explore length - Compare with UK.GOV and others.

## Acceptance Criteria
- [x] Documented form improvement research and recommendations. Presentation and formal documentation
---

**Comment by chrvalla** [comment]
Phase 1 completed. Discovery into Form 526 presented in Mural:
https://app.mural.co/t/vsa8243/m/vsa8243/1636749936875/50f454702e8cd9ddf5d4e18b7209a7f6872b51a1?sender=cvalla7693
And best practice and comparison with UK.gov presented in deck:
[https://app.zenhub.com/files/133843125/376c9dc2-ed3c-47da-8fcc-d6e231f81625/download](https://app.zenhub.com/files/133843125/376c9dc2-ed3c-47da-8fcc-d6e231f81625/download)
