### ISSUE TITLE
Create guidance on how Platform defines "resolved"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32295]
## Issue Description
In a recent Staging Review issue ticket, a VFS designer questioned how Platform defines "resolved."

https://github.com/department-of-veterans-affairs/va.gov-team/issues/31443#issuecomment-957911436

---
## Tasks
- [x] Define "resolved"

## Acceptance Criteria
- [x] VFS teams are easily able to locate our definition of "resolved"
- [x] Staging Review feedback template is updated
- [x] Drafting Template is updated

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@peggygannon check out our[ Monthly Team Check in with Rachael note](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1831436289/Monthly+Team+Check-in+with+Rachael)s from 9/2, specifically the proposed solution. This may help in determining how we want to update the ticket template.

**Comment by peggygannon** [comment]
Hi, @shiragoodman, @allison0034 @seanasewell @pjhill @noahgelman @jimuhh 
Could you let me know your thoughts/feedback on the below: 

------

1. Suggested definition of "resolved": 
All issues found at staging review have been fixed and validated with a team’s PO. If a team needs further assistance, they should reach out to subject matter experts (IA, design, content, QA, accessibility).  

2. Recommended update to the staging ticket template checklist:  

- [ ] VFS team closes the ticket when the issue has been resolved or validated by their PO. If a team has additional questions about the issue, please comment in the ticket.

**Comment by allison0034** [comment]
@peggygannon looks good to me. What does PO stand for?

**Comment by peggygannon** [comment]
Thanks, @allison0034 PO is product owner. Do you think we should spell that out?

**Comment by seanasewell** [comment]
@peggygannon I had the same question. I don't think it would hurt to spell it out. Especially, for us newbies!

**Comment by shiragoodman** [comment]
spelling out Product Owner is fine with me.

I do think we should specify that if a team needs Platform help validating that the issue has been resolved, they should comment on the ticket. Maybe work that into the text you have or create a separate checkbox? I just know I've repeated this several times to VFS teams and it would be nice to have it written someplace I can easily reference.

**Comment by peggygannon** [comment]
Hi, @shiragoodman @allison0034 @seanasewell Thanks for your feedback. What do you think of this: 

 - [ ] VFS team closes the ticket when the issue has been resolved or validated by their Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by peggygannon** [comment]
Hi, @shiragoodman the Staging review template has been updated with the below bullet:  

- [ ]  Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by shiragoodman** [comment]
@peggygannon I'm not seeing the updated template. Was this what you updated? https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Staging%2C+collab-cycle-feedback&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29

**Comment by peggygannon** [comment]
Hi, @shiragoodman Do you see it now? It looks like my earlier update didn't go through, but it looks like it's updated now.

**Comment by shiragoodman** [comment]
I see it now. I'll get the DraftingTemplate up to date now. thanks!
