### ISSUE TITLE
[Research] Add Check-in and Health Questionnaires Past Research to Research Repo

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32300]
# Description
Add past check-in and health questionnaires research to the new research repo.

# Tasks
- [ ] Follow [these instructions](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines) and add all research studies to the repo.
- [ ] Kristen will create of all the past studies that need to move

# Acceptance criteria
- [ ] All the studies are moved to the repo

**Comment by julieadair1** [comment]
@kristenmcconnell does this mean the UX research has already been done for including health questionnaires in pre-check-in?
cc: @jparker0425

**Comment by kristenmcconnell** [comment]
@julieadair1 @jparker0425 This ticket is just about adding past research to the new repo, so it is searchable for everyone to find. However, we have done a ton of work on health questionnaires already. @mdewey, @dillo, and I worked on it for a long time before we transitioned to check-in. We should schedule a time to review past work when the time is right.

**Comment by kristenmcconnell** [comment]
Continued @Evafloyd work and added all the health questionnaires studies. You can see them in the repo at https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1?card_filter_query=label%3A%22prdt%3A+health-care-questionnaires%22

**Comment by kristenmcconnell** [comment]
@julieadair1 @jparker0425 I finished this, but I'm not sure what Epic to put it under.
