### ISSUE TITLE
Add VA Notify info and links to checklist

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#32309]
## Issue Description
_Checking that notifications for product are compliant w/ VA notify is another to-do on checklis_

Per Rachael Roueche:

> I think we need another task around pointing teams to VANotify as a part of the checklist, to get the notifications aspect of their work set up. Here are the reference materials for VANotify:
> 
> Github - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify
> Intake - https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees[…]Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D

---
## Tasks
- [ ] _add VA Notify info to checklist _
- [ ] _link to relevant VA Notif docs  per @rroueche _
- [ ] Add item for teams to get Feature Toggles and access set up early-ish. (This is so they have control over turning their feature on/off without the assistance of Platform). Contact @mchelen for review.

## Acceptance Criteria
- [x] _checklist items for VA Notify added to checklist _
- [x] _list contains link to VA.N docs _
- [x] VFS teams have received guidance on getting their feature toggles and access set up.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@jimuhh can you also add the [task item from this ticket](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31968) related to feature toggles to this ticket? and remove it from the ticket I linked? thank you!

**Comment by jimuhh** [comment]
I added a link to VA Notify stuff as a bullet under "findable" [on this draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1960116265/DRAFT+-+Product+development+checklist)

**Comment by jimuhh** [comment]
@shiragoodman -- I went looking for the feature toggle request,  but all the links seem to point to this ticket. Is there something else I should be looking at?

**Comment by shiragoodman** [comment]
Can you contact @mchelen ? He had requested (via discussion with Rachael) that an item for feature toggles be added to the checklist.

**Comment by jimuhh** [comment]
OK. I'll do that on Monday.

**Comment by jimuhh** [comment]
Maria Becker was supposed to meet w/ a UX designer today but they were out sick. She'll get back to me tomw, she says.

**Comment by shiragoodman** [comment]
thanks @jimuhh !

**Comment by peggygannon** [comment]
Hi, @jimuhh this addition looks good too.

**Comment by jimuhh** [comment]
Published and closed. Thanks @peggygannon !
