### ISSUE TITLE
Create content audit and inventory spreadsheet for checklist

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#32302]
## Issue Description
_As we move more of our documentation from Github to the platform website, we'll need to keep track of _

- What's already moved over
- What exists only on Github, and eventually
- What needs to be rewritten, consolidated or removed

---
## Tasks
- [ ] _add content inventory/audit spreadsheet to  google sheets_
- [ ] _Content from existing github checklist page is documented there _

## Acceptance Criteria
- [ ] _Standard inventory/audit spreadsheet is on collab cycle google drive_
- [ ] _Spreadsheet contains inventory of content linked from github  checklist page_---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jimuhh** [comment]
Apparently this was such a good idea that @mnorthuis and @peggygannon did it before I got here.  It's best to have a single source, so let's stick with the original.
Can you guys look at [the version I made for checklist ](https://docs.google.com/spreadsheets/d/1zVAvK8ZlEq8wDSzn67WosSBComFZv3nHZL6GYEJyR6A/edit#gid=0)and tell me how you want to integrate it and if there are any parts you think are worth adding to your version?
