### ISSUE TITLE
Update Welcome Kit page with new PDFs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32316]
## Issue Description
Stakeholder Justin Hoffman uploaded 19 new PDFs to the CMS. We need to replace the current PDFs on our [welcome kit](https://www.va.gov/welcome-kit/) page with these. 

For "Get started with services for Veterans ages 65+" also change the text to "Get started with services for aging Veterans (PDF)"

## Tasks
- [x] Update Welcome Kit with new PDFs uploaded into CMS (Selina)
- [x] Update text for Aging Veterans (Selina)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that page is live (Randi)

## Acceptance Criteria
- [x] New PDFs and text are live on the welcome kit page

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I switched out all PDFs except for the Veteran state PDF. I also updated the sighted language in the housing assistance link teaser (i.e., "see" to "check").

Print out your VA Welcome Kit: http://preview-prod.vfs.va.gov/preview?nodeId=716

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
