### ISSUE TITLE
[UX] Develop final pre-check-in wireframes

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32318]
We need to update the pre-check-in wireframes based on the usability testing. 

For this scope we're not concerned with editing, only read only. 

We'll spin up a separate ticket for the editing piece, which will need to go through collab cycle. 

# Tasks
- [x] Work with content to finalize wording
- [x] Create a complete wireframe set in Sketch
- [x] Work through edge cases

# Acceptance Criteria
- [ ] Have design, product, and VA product owners review the wireframes
- [ ] Review the final wireframes with engineering

**Comment by julieadair1** [comment]
Coordinate with Ryan Thurwell and profile team

**Comment by julieadair1** [comment]
@kristenmcconnell will meet with @rtwell @joshkimux and @AngelaFowler82 to determine editing contact info next steps.
@mdewey we'll be reaching out to you to get a rough effort estimate on making the existing modal into a page.

**Comment by kristenmcconnell** [comment]
@jparker0425 @julieadair1 Katherine Shelor mentioned in ToT that the Next of Kin relationship field is being change into a preset list of 15 items. When is that happening? What are the 15 items?

**Comment by kristenmcconnell** [comment]
Editing capabilities is out of scope for MVP, so will hold off on discussions with @rtwell, @joshkimux, and @AngelaFowler82 for now.

**Comment by niradatta1** [comment]
Here's the link to the final wireframes https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/847B453D-F19E-4D55-9EE6-C523E7408879

Including notes from our accessibility review: 
1) ensure focus element appears on the H1 of each page in the flow (sometimes it can default to the VA banner)
2) here is information about links on the introduction page and the help phones: https://dsva.slack.com/archives/C02GXKL8WM6/p1637245484195200?thread_ts=1637187437.188500&cid=C02GXKL8WM6
3)code the titles in the fields on the demographic page + NOK page (mailing address, home address etc.) as description lists.
4) on the confirmation page, mark the icon in the blue box "notification" or "important" so that the screen reader can tell the users that it is an important information

Link to slack conversation on this for more context here: https://dsva.slack.com/archives/C022AC2STBM/p1637349556003900
