### ISSUE TITLE
[PM] Profile Personal Information Revision: Update front end documentation 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32324]
## Issue Description
As a Product Manager I want to keep our front end documentation updated with any changes as the project progresses so the FE engineer has accurate guidance and so we have our project well documented.

---
## Tasks
- [x] Update Personal Information Revision [FE documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend)

## Acceptance Criteria
- [x] The FE documentation will contain the most up-to-date information about the front end content.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
