### ISSUE TITLE
Analytics Implementation or QA Support for SMS link tracking

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#32330]
# Google Analytics Implementation or QA Request

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32018#issuecomment-956576212

Our current telephone tracking is not tracking "SMS" links.
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - [Insert launch date]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
QA is complete. 
The Outbound Links event is firing on the SMS link in the crisis line modal from the GTM sms link tracking workspace. The action is coming in as intended: "Outbound Link Clicked: sms:838255". 

![image](https://user-images.githubusercontent.com/85642160/140064665-c98873c3-60ca-475d-8cf8-ec600caab790.png)

**Comment by bsmartin-ep** [comment]
Deployed.  Thanks for the QA @jennaouellet.
