### ISSUE TITLE
[VAMC]  build  CLC detail page source of truth using Tampa, FL CLC [BA}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32341]
## Story
As an editor I need to have a CLC designated detail page, so I can align our Veterans to the correct Support location

## Resources
[TBD]
* See Tampa Teamsite information for old CLC information pages in Archive if needed

## TASK
Build new page using design from Facility
- [x]  Build new VAMC Detail page in Tampa - Programs using Facilities/Content final copy.
- [x]  Scaffold data into area from what is found from current Tampa CLC page.  
- [x]  Update address, hours, phone to match facility
- [x]  Move register for care into blue text area.

## Acceptance Criteria
- [x]  Full page has been created with data content provided for Tampa
- [x]  Page is in Draft and available for Content to copy edit prior to publication

**Comment by ltrombley** [comment]
Task #32341 - build CLC detail page source of truth using Tampa, FL CLC [BA} - is Complete and moved to Validate.
