### ISSUE TITLE
[VAMC] Research, design, and create Presentation for Communities of Practice meeting on Nov. 18th, [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32340]
## Story
As an editor I need to understand the design and architecture of a detail page, so I can better understand how to create a page that will work best for Veterans

## TASK
Create a presentation that will address the design and architecture of a VAMC Detail page.
- [ ]  Headers
- [ ]  Hyperlinks on Titles
- [ ] Use of bold, italic, underline
- [ ] Bullet points, and indent
- [ ] Best practices.

## Acceptance Criteria
- [ ] Presentation is created and reviewed 
- [ ] Save presentation in VAMC SharePoint Drive in prep for Nov 18 Meeting.
