### ISSUE TITLE
[VAMC] Review and copy edit new CLC source of truth for Tampa [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32342]
## Story
As an editor I need to have a CLC designated detail page, so I can align our Veterans to the correct Support location

## Resources
[TBD]
* See Tampa Teamsite information for old CLC information pages in Archive if needed

## TASK
Build new page using design from Facility
- [x]  Review page design and data load for content.
- [x]  Content   

## Acceptance Criteria
- [x]  Full page has been reviewed and content is updated in Drupal.
- [x]  Page is in saved as Draft and available for full publication later
