### ISSUE TITLE
 [VAMC] Review and copy edit new DOM source of truth for Tampa [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32345]
## Story
As an editor I need to have a DOM designated detail page, so I can align our Veterans to the correct Support location

## Resources
[TBD]
* See Tampa Teamsite information for old DOM information pages in Archive if needed

## TASK
Build new page using design from Facility
- [ ]  Review page design and data load for content.
- [ ]  Content   

## Acceptance Criteria
- [ ]  Full page has been reviewed and content is updated in Drupal.
- [ ]  Page is in saved as Draft and available for full publication later
