### ISSUE TITLE
[VAMC]  Build and scaffold Source of Truth for Domicilary for Tampa FL [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32343]
## Story
As an editor I need to have a Domiciliary designated detail page, so I can align our Veterans to the correct Support location

## Resources
[Final Reviewed document](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FContent&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)
* See Tampa Teamsite information for old DOM information pages in Archive if needed

## TASK
Build new page using design from Facility
- [x]  Build new VAMC Detail page in Tampa - Programs using Facilities/Content final copy.
- [x]  Scaffold data into area from what is found from current Tampa DOM page.  
- [x]  Update address, hours, phone to match facility
- [x]  Move register for care into blue text area.

## Acceptance Criteria
- [x]  Full page has been created with data content provided for Tampa
- [x]  Page is in Draft and available for Content to copy edit prior to publication

**Comment by ltrombley** [comment]
Task #32343 - Build and scaffold Source of Truth for Domiciliary for Tampa FL [BA] - is Complete and in Review with Content team.
