### ISSUE TITLE
[Design] Find a VA Form PDF Instructions - Update Modal with finalized content

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32357]
## Issue Description

We have [finalized copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574) for the PDF modal that needs to be updated in the mockup.

---

## Tasks
- [x] Update the modal based on the information Beth provided in the comment referenced above.

## Acceptance Criteria
- [x] An updated modal that Zach can use as reference for updating the modal on Staging
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 I am not going to schedule a Sprint planning meeting for this project, but please estimate this issue when you have a chance today. If you are able to work on it right away, that would be awesome, but if not, please let me know.  Thanks!

**Comment by callen2563** [comment]
@MarciMcGuireGCIO Here is the updated modal with shorter copy:


![Modal_desktop](https://user-images.githubusercontent.com/68560244/140093362-5180a9d1-58ae-496f-b824-58c79655505c.png)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 can you shoot me the link to the updated Sketch file for this? Thanks!

**Comment by callen2563** [comment]
Hi @MarciMcGuireGCIO, here is the [Sketch file ](https://www.sketch.com/s/6e7784a1-5b01-4aec-9ec7-4bbf788d08fa)

**Comment by MarciMcGuireGCIO** [comment]
Thank you @callen2563 !!
