### ISSUE TITLE
Document process for maintaining the VA.gov Experience Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32362]
## Issue Description
Product Support launched the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) in July 2021. At the time, the team did not create a maintenance plan, or any internal-facing, operational documentation. This ticket will identify what maintenance items are necessary for the VA.gov Experience Standards, and will also include execution of the required maintenance items. 

So far, the following maintenance needs have been identified:

- Processes for making changes (modifying, adding or deleting) to a VA.gov Experience Standard
- Process for reviewing CCIssue00.00 (these are issues uncovered in Staging Reviews that don’t map back to a specific standards. They should be reviewed on a set cadence so they can be reassigned to the correct standard or the standards can be modified to recognize these type of issues).
- a list of VA.gov Experience Standards artifacts and their purpose, including audience (source sheet, VA.gov Experience Standard page on Platform Website, DraftingTemplate, etc.)

A [page on Confluence in the Platform Products and services space](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1941176380/VA.gov+Experience+Standards) has already been created and will be the future home of this documentation. 

---
## Tasks
- [ ]  Create a document listing the steps/process for updating and maintaining Experience Standards and their supporting artifacts. The document should include:  
- How and where to document proposed changes and updates to the Experience Standards
-  How often PS team will review proposed changes and CCIssue00.00 issues, and the criteria for making updates to the standards
- List of artifacts that support the VA.gov Experience Standards, what each is, where it lives, and when to update to match any changes we make to the Experience Standards. 

## Acceptance Criteria
- [ ] The process we determine is documented in a Product Support Confluence page.
- [ ]  Team knows page exists and what to do with it.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@jimuhh @peggygannon please help define Acceptance Criteria.

**Comment by jimuhh** [comment]
@peggygannon and I added tasks and acceptance criteria

**Comment by shiragoodman** [comment]
Per guidance received from Rachael at the post-launch review of the Update Guidance and Documentation initiative on 11/15, we are putting this effort on hold until the percentage of "Other" issues identified in Staging Reviews passes the 10% threshold (meaning 10% of all tickets are classified as "Other:)
