### ISSUE TITLE
[UNPLANNED] Fix URL for representative type

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#32368]
## Background
There is a typo in the url for the representative type page during the representative search that needs to be corrected.

## Considerations
- Current URL is `/view-change-representative/search/representstive-type`
- URL should be `/view-change-representative/search/representative-type`

## Tasks
- [x] Update the url for the representative type page

## Acceptance Criteria
- [x] The URL is updated
- [x] A PR has been requested for merging
