### ISSUE TITLE
CST - Frontend Assessment Phase 2

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#32365]
## Issue Description
After creating CST in a new template, we should look at the information that's on the page and understand what needs to be updated, removed or added.

New proposed design: https://www.sketch.com/s/64bb337a-e31f-4a21-a92f-d89b50cba668

---
## Tasks
- [x] Assess content in new page layout design
- [x] Determine what should be added/removed

## Acceptance Criteria
- [x] Changes have been made in design
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Here's the design for the new, proposed CST layout:

https://www.sketch.com/s/64bb337a-e31f-4a21-a92f-d89b50cba668

Notes:
- **Feasibility** - from an internal process perspective, it looks like we have permission to  transition to this new template. It's in the experimental design system now and is being used in a few places already on VA.gov. However, being that it is experimental, we need to figure out how we're going to test efficacy moving forward (read bullet point on metrics below)
- **Metrics** - Currently, we only have metrics on the link to ebenefits that shows on the sidebar. In order to test the two versions (current vs. new), we will have to record some interactions and compare performance. @sshein I know you had some thoughts on how we could compare moving forward, so feel free to drop notes here or we could invite you to a meeting where this is discussed.
- **Content** - I recently confirmed with Jim A. that 1.) ebenefits is still up and running, 2.) that checking their disability rating in ebenefits is still better than using our VA.gov disability rating tool, and 3.) the 'my documents' feature is still in ebenfits and will let users see documents they've submitted to the VA.  Therefore we should keep the link to ebenefits on the sidebar for now. Further, I assessed what we could/should do on the cards and after talking to the devs and doing the frontend tech assessment, I don't think there's much else we can pull in the near future. Any additional card info would need to be held for future enhancement. 


**Next steps**
- Hold meeting to discuss analytics
- Engage analytics team to put analytics tracking on current template or new (or both, depending on what we decide) 
- Have FE dev implement analytics tracking on events/interactions we decide upon
- Depending on what course of action we decide (and once GA events implemented), either test current design template or start coding out new template (and potentially test that one)

@vhenry07 let me know if you have any questions on this assessment. 

Thanks everyone!

**Comment by sshein** [comment]
cool! I was mostly thinking we could think about the top tasks people are performing on the claims status tool (or want to perform) - I wonder if the mobile team already determined that - and then think about how we'd measure how well those tasks are working in the current design as a baseline. Then measure on the new design. I'd imagine we'd do some quantitative measurement but then also do a simple usability study.

**Comment by kevinstachura** [comment]
Ok cool, so we're both thinking of some quantitative data points (Google Analytics event tracking, for example) and potentially qualitative (usability study) research too. 

I think for testing out the layout and new functionality of the design, I would be curious to see how often users click on:

- The 'on this page' page jump links
- The content that 'on this page' jumps to (former sidebar content) and the links therein
- The mobile app 'upsell' CTA
- The claim / appeal items (action link, if possible)

We can see what kind of numbers exist for some of these things today (like I said, Robin stated that we do have the event for ebenefits clicks). We probably also have some sort of analytics on the clicks for trying out the mobile app. Those are data points we can compare with the new template, once implemented.

And I think the usability study can of course cover the general usability with tasks pertaining to the sections above.

Thanks Shawna!
