### ISSUE TITLE
526 - Submission Error - Prelim email drafts for PIF in use, file upload errors

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#32361]
## Issue Description
We need to create emails that alert users when their 526 submission was unsuccessful. Here are the errors we plan to address:

- When a user's associated file uploads fail
- When a user's Pending Issue File (PIF) code is in use

---
## Tasks
- [x] Understand both scenarios and how the user is able to remedy
- [x] create proper preliminary copy

## Acceptance Criteria
- [x] Copy has been created and documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Multiple scenarios have been identified as we looked at prelim content for these emails. Here are the scenarios and content:

**PIF error (call center reference):**

>An error occurred with your disability claim application.

>Hello [user],

>Due to a technical error, we couldn’t process your form. This can occur after the form has been submitted on the VA.gov website. Please contact our call center at 800-827-1000 and mention ‘Error: PIF in use’ to the support specialist. We’re available Monday through Friday, 8 a.m. to 5 p.m. EST. We apologize for the inconvenience.


**PIF error (non call center):**

>An error occurred with your disability claim application.

>Hello [user],

>Due to a technical error, we couldn’t process your form. This can occur after the form has been submitted on the VA.gov website. At this time, we advise that you fill out and submit our 526 paper form. 

>Send in your completed form and any evidence in support of your claim to:

>Department of Veterans Affairs 
Evidence Intake Center 
PO Box 4444 
Janesville, WI 53547-4444

>We apologize for the inconvenience.

**File upload error:**

>Hello [user],

>Thank you for submitting your claim for disability compensation on our website. Your form has been submitted. However, we could not process the supporting evidence or documentation you provided as part of your claim, due to a technical error. 

>The simplest way to fix this issue is to access your claim in our Claim and Appeals Status tool. Navigate to the files tab and upload your desired documents. This will attach your documents to your claim.

>Please upload these documents as soon as possible so as to avoid any delays in processing your claim.   If you have any questions or need assistance, please contact our call center at 800-827-1000. We’re available Monday through Friday, 8 a.m. to 5 p.m. EST. We apologize for the inconvenience.

Some notes:

- We may update the 'file upload error' version so as to tell users the exact files/filenames that did not actually upload. Currently we are planning on having that show in the CST, but we need to work on this a bit further. May update the copy based upon the decision there.
