### ISSUE TITLE
Create Betamock Recordings for `findRatingInfoPID`

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3237]
## User Story
As a Veteran using the _"View your VA disability rating"_ tool, I want to be able to view my **Total Combined Disability Rating** so that I can see my status and availability to receive more, or other, benefits I deserve.

## Background
The 'findRatingInfoPID' service has been tough to work with as far as getting access and now that we are successfully able to gain access to it (_thank you Silvio and Mike Walker!_), we need configure a few betamock recordings so that it can be called, tested and integrated further into the tool page.

## Considerations
- From the [vets-api README.md](https://github.com/department-of-veterans-affairs/vets-api) there are [instructions](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md) on how to set up betamocks, if needed.

## Tasks
- Use 5-6 test accounts that have varying information associated in them
- Ensure that header information is passed successfully
- Generate 5-6 `yml` files

## Acceptance Criteria
- [ ] Create 5-6 betamock recordings for the `findRatingInfoPID` service
- [ ] Push the `yml` recordings to the [betamocks repo](https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/master/evss)
- [ ] Document process, variances and findings [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/evss-tcdr/README.md) in GitHub
