### ISSUE TITLE
NOD: Fix issue card margins

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32372]
## Description

Issue cards in the Notice of Disagreement app have the left margin set to zero. I don't know what change happened to cause this, but it makes the `margin-inline-start: 0` override the margin left setting.

![Screen Shot 2021-11-03 at 9 35 48 AM](https://user-images.githubusercontent.com/136959/140096585-22a125c8-21e5-4397-b67a-f133fe1c9a27.png)

## Tasks

- [ ] Fix the issue card left margin
- [ ] Visual test in IE11 & other browsers

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
