### ISSUE TITLE
Discovery: Team structures

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#32379]
Need a good way of talking about teams to provide access. 

If a user needs to be added to a number of services based on their team, ideally you could add them to the team and get them added to those services in one. 

**Task is Done When:**

we have a document in confluence outlining the below:

- [ ] are teams represented programmatically anywhere?
- [ ] how is access managed now for teams?
- [ ] are there any teams that are doing this well right now?

**Comment by ken-non** [comment]
won't do
