### ISSUE TITLE
Finalize responsibilities in our Team Charter

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32370]
## Issue Description
Product Support held a team charter workshop in September 2021. During the workshop, we created a new team mission statement which has been incorporated into our Team Charter. We also brainstormed responsibilities, but never followed through on incorporating our team responsibilities into our Team Charter.

The purpose of this ticket is to review the [MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1630433092173/e295a85b542dbf4ca2f574f0ef1bc1bffc24dd0d?sender=u0574179b1d97118ccc0e3591) where responsibilities were defined (@allison0034 already made an attempt at grouping the responsibilities) and come up with 4-5 responsibilities for the team. The defined responsibilities should be reviewed and approved by the team, as well as OCTO, then published in our Team Charter on the [Product Support Overview page](https://vfs.atlassian.net/wiki/spaces/PPST/overview?homepageId=1392346189). 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Product Support team charter is up to date with team responsibilities.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@seanasewell Can you please archive the [Team Charter ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1888944164/Team+Charter)page since now this information resides in the [Overview page?](https://vfs.atlassian.net/wiki/spaces/PPST/overview?homepageId=1392346189) Also please make sure any links in the Onboarding doc are updated. Any comments still in the Team Charter page, please transfer over to the Overview page, if still valid. thanks! you can close once complete.

**Comment by seanasewell** [comment]
@shiragoodman **Status Update** Comments have been moved over and all links seem to be going to the correct places. I'm going to close this.
