### ISSUE TITLE
Add Page to Account for Search Results Transitioning to From

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32392]
## Story
We need to ensure that the Veteran understands what the search results represent so that the actions taken can be clear and informed.

[updated mockup for page to be added](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/09O8Gr2)

## Considerations
- We need a page that allows Veterans to "confirm" the search results should be moved in to the form.
- The Veteran needs to understand that they need to work with the representative and this is only to result in a filled out PDF to be downloaded
- Content at the bottom of search results will be the majority of the content on this separate page
- Ensure auth and unauth's pages are the same
- [workflow](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/zxpjVva)
- [v2 wireframes](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/l1YzGYK)
- [Content updates from Beth](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31230#issuecomment-950532775)

## Tasks
- [x] Add page after search results to display selected representative
- [x] Include copy that talks about their next steps

## Acceptance Criteria
- [x] A new page exists that shows the Veteran's selection and their next steps (going into the form)
- [x] A PR has been requested for merging

**Comment by candy-gcio** [comment]
@cohnjesse, @jerekshoe - Here's the [transition page](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/09O8Gr2)
