### ISSUE TITLE
526 PDF generation and printing

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#32394]
## Issue Description
Reference Epic [32267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32267)
As a Veteran, I would like to be able to print out a pdf copy of my 526 claim submission.

---
## Tasks
- [x] Parse 526 PDF to get the fields
- [ ] Map the json526 json form data to the PDF fields from task above via ruby code

## Acceptance Criteria
- [ ] Backend code in place to allow producing a pre-filled 562 PDF based on 526 json form data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cnemeth** [comment]
Notes on delayed completion:

1. Self, new to the team and the code base, still onboarding.
1. Spent considerable time researching tools to, at least partially, automate process.
   - `PDFtk` was used to extract the `field names` from the PDF from,
   - no tools found for mapping the `JSON attributes` into the `PDF fields`, this step has to be done manually.
1. One persistent blocker has been the failure to extract the completed JSON form data from the statging. The recommended test user for this task, `vets.gov.user+228@gmail.com`, has consitently resulted in `.... missing your EDIPI number or BIRLS ID.`

**Comment by cnemeth** [comment]
Further notes on causes of delay:

1. There was some confusion regarding the source of the truth of the `526.json` schema definition. Started off with `vets-api/modules/claims_api/config/schemas/526.json`, need to switch to `vets-json-schema/dist/21-526EZ-ALLCLAIMS-schema.json`. The files have some matching sections but otherwise differ significantly in structure and _key_ naming.
2. There is considerable manual work involved in transforming the `526 JSON` definition back to `PDF`. 
  - The `21-526EZ` PDF form itself is 5 pages long (one of the longest forms in our system) and the resulting generated _field names_ file is over _2000 lines_ long. 
  -  Also, the `526.json` definition is nearly _1800 lines_ long.
  -  I have not been able to track down the _PDF-to-JSON_ mapping that was done when the `526.json` was created, which would have been helpful in this reverse operation.
3. There is also considerable ambiguity in matching _json keys_ to the corresponding _PDF questions (fields)_.
  - NOTE: (From last Thursday's _Lighthouse API teams Weekly Standup) _Lighthouse Benefits Claims API team_ might be able to assist with that.]

**Comment by vhenry07** [comment]
Progress made, expect to be completed soon, so rolling to next sprint.

**Comment by cnemeth** [comment]
Lighthouse team is taking over task.
