### ISSUE TITLE
[FSR] Add content to FSR's confirmation page indicating that Veterans will receive an email confirmation

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#32393]
## Issue Description
We're adding an email notification via VANotify that confirms that an FSR has been submitted. We should update the confirmation page to notify Veterans that they will receive a confirmation email so they know to expect it. 

---
## Tasks
- [x] Update the FSR's confirmation page to indicate that the Veteran will receive an email confirmation 

## Acceptance Criteria
- [x] Updated design has been linked in this ticket
- [x] A ticket for frontend implementation is linked in this ticket

**Comment by rileyorr** [comment]
Updated the confirmation page ([UXPin link](https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691671/simulate/sitemap?mode=i)). I slightly adjusted it since I uploaded it and Sketch keeps crashing when I try to export to UXPin, so I'm going to try again tomorrow morning.

**Comment by rileyorr** [comment]
Becca was able to export it for me! I also added a frontend ticket (#32740)
