### ISSUE TITLE
Add LGY Token to AWS Parameter Store

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32396]
`Can be done ahead of time`

## Background
Part of the groundwork for this integration with LGY involved some network configuration with the DevOps folks

## Tasks
- [x] Set up the forward proxy
- [x] get auth token from LGY for INT env and add to AWS
- [ ] [kathleen] check swagger / health-check

## Acceptance Criteria
- [ ] dev env api_key has been added to AWS Management Console - Parameter Store
