### ISSUE TITLE
First Pass of the Specially Adapted Housing Grant Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32409]
## Background
When we initially set up the Specially Adapted Housing Grant feature we did not build out all of the fields for the form. Now that we are farther along we need to add the fields for the form. 

_Note: This is a first pass at building these fields and IF this form includes more complicated UI then we should break that into a separate ticket._

[Mockup](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/qeWPW75)

## Tasks
- [ ] Build out for fields for [Form Name] form in `vets-website`
- [ ] Submit PR to `vets-api` for review

## Acceptance Criteria
- [ ] Form fields in the latest mockup have been added to the [Form Name] form
- [ ] A PR has been submitted to `vets-website` for review
