### ISSUE TITLE
Initial Scaffold for the Specially Adapted Housing Grant Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32408]
## Background
Now that the design of the Specially Adapted Housing Grant feature has been created the next step in building this feature is to build out the initial pages based on the currently designed prototype.

## Considerations
- [Current VA Form 26-4555](https://www.vba.va.gov/pubs/forms/vba-26-4555-are.pdf)
- [Mocks](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/eKJnozj)

## Tasks
- [x] Create the pages for the various screens for Specially Adapted Housing Grant with just enough on them to keep them
- [x] Frame or stub out the component areas
- [x] Create a list of next steps that need to be implemented
- [x] A PR has been submitted for review

## Acceptance Criteria
- [x] The initial pages have been created locally and a quick view has been shared with the team
- [x] A PR has been submitted for review

**Comment by jason-gcio** [comment]
Mislabeled for Sprint 62
