### ISSUE TITLE
Uploads: Verify file extension matches the type

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32402]
## Description

Form 526 file uploads are checked after being uploaded to ensure they the extension matches the file type. Because this form does this asynchronously _after_ form submission, there is no easy way to inform the Veteran that the file was rejected. We discussed ideas where a email could be sent to the Veteran, but it would be better to check this match on the frontend and immediately inform the Veteran of the problem.

- Slack discussion: https://dsva.slack.com/archives/CBU0KDSB1/p1635527915033500?thread_ts=1635522020.025100&cid=CBU0KDSB1
- Code source (use what we need): https://github.com/sindresorhus/file-type

## Tasks

- [ ] Implement file type checking on the front-end
- [ ] Show type mismatch error
- [ ] Add unit tests

## Definition of done

- [ ] File type check implemented
- [ ] All tests passing

**Comment by Mottie** [comment]
Bumping this to 4 story points because this change will require updates to both the platform file upload and the claim status tool upload code.

**Comment by Mottie** [comment]
Done!
