### ISSUE TITLE
Remove "disallow" entries from Robots.txt file on November 3

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32407]
## Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task
Remove the following system names from robot.txt file prior to their upcoming go-live

For 11/3

- [x]  /boise-health-care/
- [x]  /loma-linda-health-care/
- [x]  /spokane-health-care/

For 11/10

- [x]  /beckley-health-care/
- [x]  /central-texas-health-care/
- [x]  /chillicothe-health-care/
- [x]  /clarksburg-health-care/
- [x]  /connecticut-health-care/
- [x]  /dayton-health-care/
- [x]  /eastern-kansas-health-care/
- [x]  /huntington-health-care/
- [x]  /jackson-health-care/
- [x]  /maine-health-care/
- [x]  /manchester-health-care/
- [x]  /memphis-health-care/
- [x]  /nebraska-western-iowa-health-care/
- [x]  /northeast-ohio-health-care/
- [x]  /poplar-bluff-health-care/
- [x]  /roseburg-health-care/
- [x]  /san-diego-health-care/
- [x]  /southern-arizona-health-care/
- [x]  /tennessee-valley-health-care/
- [x]  /tomah-health-care/
- [x]  /washington-dc-health-care/
- [x]  /white-river-junction-health-care/
- [x]  /wichita-health-care/

## Acceptance Criteria
 System names are removed from robot.txt file

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/726 has been merged
