### ISSUE TITLE
[PM] Profile: Update Contact Center Documentation after AJ Updates Notification Info

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32419]
## Issue Description
As a Product Manager, I want to update the documentation for Profile so that the Contact Center has updated information when supporting Veterans and their representatives.   This update needs to occur after AJ has made her updates for Notification Preferences and passed off to the Profile team.

---
## Tasks
- [ ] Update Contact Center Word doc
- [ ] Export PDF
- [ ] Store both docs in Contact Center directory inside project folder on GitHub

## Acceptance Criteria
- [ ] Updated Contact Center Word doc and PDF will be created and stored in GitHub
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
