### ISSUE TITLE
Add Schema for Specially Adapted Housing Grant

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32410]
# Background
Now that we have created all the fields in the Specially Adapted Housing Grant feature we need to copy the schema for those fields into `vets-json-schema`.

## Considerations
- Meet with BE as well

## Tasks
- [ ] Build out for fields for the Specially Adapted Housing Grant feature in `vets-json-schema`
- [ ] Bump version number in package.json in `vets-json-schema`
- [ ] Update commit hash in package.json in `vets-website`
- [ ] change the commit hash in `vets-website`
- [ ] Run `bundle update vets_json_schema` in `vets-api`
- [ ] Submit PR to `vets-api` for review

## Acceptance Criteria
- [ ] The full schema for [Form Name] has been created in the `vets-json-schema` repo
- [ ] The commit hash in `vets-website` has been updated
- [ ] The `vets-api` repo has been updated accordingly
- [ ] PRs have been submitted for review
