### ISSUE TITLE
Establish GA Events for the Specially Adapted Housing Grant Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32411]
## Background
In order to track the success metrics for the Specially Adapted Housing Grant feature form we need to get Google Analytics events set up that speak to those metrics. So that the analytics team has a chance to establish those event names and what they are for we need to meet with them either in person or over Slack.

## Tasks
- [ ] Connect with the GA/Insights Team (over either Slack or Zoom) to share what function and features this product is involved with, and a recommendation for what events they might be interested in tracking.
- [ ] Document what events will be provided by the analytics team

## Acceptance Criteria
- [ ] We have connected with the GA/Insights Team 
- [ ] We have a document (ticket or otherwise) that has all of the GA events needed for the Specially Adapted Housing Grant feature

### Next steps
-  [ ] Code provided by the GA/Insights Team has been inserted into our feature
