### ISSUE TITLE
Feature request process - Update internal-facing user guide

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#32417]
## Issue Description
Refine [instructions](https://vfs.atlassian.net/l/c/1PFPDy9r) for Platform teams and their OCTODE leads based on feedback from go/no go:

https://vfs.atlassian.net/wiki/spaces/AP/pages/1909293082/Feature+request+process+-+User+guide+for+Platform+teams

---
## Tasks
- [x] Update internal-facing guide 
- [x]  Review internal-facing guide w/ product lead
- [x] Move to appropriate Platform space

## Acceptance Criteria
- [x] Approval from PO to launch.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jchasia-adhoc** [comment]
Updated internal-facing guide: [https://vfs.atlassian.net/l/c/HS81xHAj](https://vfs.atlassian.net/l/c/HS81xHAj)

**Comment by jchasia-adhoc** [comment]
Approval from Product lead: https://dsva.slack.com/archives/CPCGRR7F1/p1637700402086600?thread_ts=1637696556.086400&cid=CPCGRR7F1

**Comment by Khyatinp18** [comment]
All work is complete, please refer to this issue:
https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/department-of-veterans-affairs/va.gov-team/35608
