### ISSUE TITLE
SD -  R&S Technical exploration for auto sort articles by popularity 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32428]
## Issue Description
_Technical exploration on how to programmatically order VA knowledge articles in resources and support's browse by topic section._

---
## Tasks
- [ ] _Collabrate with public website team and CMS team to learn how the original articles were sorted and what are our options to change_

## Acceptance Criteria
- [ ] _Know what it takes to programmatically sort VA knowledge articles in resources and support's browse by topic section daily/weekly _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Question for CMS team: Can drupal sort article based on popularity?
Answer: Drupal is not aware of what’s popular on www.va.gov. Nor does it determine the sort (although it does make certain sort criteria, like date, available via the Content API). So this sounds like a 100% FE effort in the current tech stack.

**Comment by srsuddath** [comment]
After discussion with Kelson, any sorting by popularity we wish to do must all be done from the FE, and would likely have to target a small number of articles to boost, rather than maintain a popularity score for each article in the bank.

**Comment by srsuddath** [comment]
After discussion with Kelson, any sorting by popularity we wish to do must all be done from the FE, and would likely have to target a small number of articles to boost, rather than maintain a popularity score for each article in the bank.

**Comment by srsuddath** [comment]
After discussion with Kelson, any sorting by popularity we wish to do must all be done from the FE, and would likely have to target a small number of articles to boost, rather than maintain a popularity score for each article in the bank.

**Comment by srsuddath** [comment]
After discussion with Kelson, any sorting by popularity we wish to do must all be done from the FE, and would likely have to target a small number of articles to boost, rather than maintain a popularity score for each article in the bank.
