### ISSUE TITLE
[Design/Research] User tasks and interaction point to support research 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32436]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- Must work well on mobile and desktop platforms
- Should consider iterative feature development
- Should consider CMS dependency (Initial design/development must align with current CMS functionality)
- Must include date/time filtering concepts 
- Must include **recurring events concepts**

### Tasks
- [x] Determine User tasks and Interaction points to support Round 1 Veteran User Research 
- [x] Review as a team and ensure a plan is in place for next steps 
- [x] Close ticket once completed

**Comment by cindymerrill** [comment]
While thinking about user tasks for O&E usability testing, I drafted this quick interaction flow of screens for the prototype, and list of requirements for usability testing. https://app.mural.co/invitation/mural/vsa8243/1615569664046?sender=ua2ff9f6c0031cb4999ae6676&key=8705eb62-30a8-4fde-b9f1-ff9b93f42bc5
@callen2563  and I discussed met to discuss this and made plans going forward. I'm planning to make a list of dummy events that go on each page of the prototype, and Cassandra is going to work on building the prototype.

**Comment by cindymerrill** [comment]
I'm also going to comment on the content ticket about our proposed wording for describing the cadence of repeating events, if we can extract that programmatically from the event editor tool. Can someone please share a link to the content ticket with me so I can do that? @callen2563 @brianalloyd

**Comment by callen2563** [comment]
@cindymerrill [link to content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32518)

**Comment by cindymerrill** [comment]
Thanks, @callen2563 ! I added a comment to the ticket, as we discussed.

**Comment by cindymerrill** [comment]
Started drafting [list of dummy events for the prototype](https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Public%20Websites%20Team/Outreach%20%26%20Events/Research/Events%20for%20prototype.xlsx?d=w924859093e4c4d67ba98f387f3d0ecb2&csf=1&web=1&e=aXtVf9) and discovered a bug in the design. We can't have options for “Next 7 days”, “Next 30 days”, “Next 60 days”, and “All times” because they'll all show the exact same events at the top, thus confusing users. See slack conversation about this [here](https://dsva.slack.com/archives/C52CL1PKQ/p1636571740483800). @joshkimux, who proposed the dropdown design, confirmed the problem and endorsed the design solution that @callen2563 and I came up with: simplify the date filter dropdown options to the mutually exclusive "Upcoming events" and "Past events". This doesn't add any additional functionality to the current toggle button design with those same phrases, but it does upgrade it to be compatible with the design system and current accessibility standards. Below is what the simplified dropdown options would be: 
![image](https://user-images.githubusercontent.com/69914583/141213053-4cd31bf4-68cf-4f39-b7f3-c873ec3eae6b.png)

**Comment by cindymerrill** [comment]
Drafted a short summary of the issue and list of pros/cons for each of the two designs, and shared with Shawna for feedback. Would like to discuss with Brian tomorrow and maybe Dave, too.

**Comment by cindymerrill** [comment]
In preparation for Monday’s planned sync meeting on the dropdown options, I worked with Josh Kim on a new design proposal that resolves the event list usability issue and also incorporates Dave Conlon’s use case of looking for events on a specific date (or month). This pros/cons document has new sections where I summarized today’s slack discussions with Dave and the current design proposal: Input from Dave, Design Heuristics, and NEW DESIGN PROPOSAL. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vs[…]ic-websites/outreach-and-events/research/date-filter-options.md

**Comment by cindymerrill** [comment]
Following up on our O&E design sync-up meeting today, I’ve updated my design options doc with our decisions. You can see our current design proposal at the top with design notes (from our meeting) about each mockup. Last week’s design work is hidden under an accordion at the bottom of the page. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vs[…]ic-websites/outreach-and-events/research/date-filter-options.md

**Comment by cindymerrill** [comment]
Yesterday I finished putting together a list of event content for Cassandra to include in the prototype: https://governmentcio.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Public%20Websites%20Team/Outreach%20%26%20Events/Research/Events%20for%20prototype.xlsx?d=w924859093e4c4d67ba98f387f3d0ecb2&csf=1&web=1&e=dsDOMk
