### ISSUE TITLE
Mock ups - Outreach & Events 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32433]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- Must work well on mobile and desktop platforms
- Must address accessibility concerns and support for adaptive tech
- Should consider iterative feature development
- Initial design/development must align with current CMS functionality
- Must include date/time filtering concepts 
- Must include **recurring events concepts**

### Tasks
- [x] Design mockups based on O&E wireframes 
- [x] Incorporate all feedback from Design Intent review and ensure mockups can support FE Build
- [x] Review final mockups with team in support of FE build
- [ ] Close out ticket when completed

### Acceptable Criteria
- [ ]  Design mockups based on wires and DI feedback in preparation for prototype build

**Comment by callen2563** [comment]
I'm liking the [Sketch File](https://sketch.com/s/ceaa48f6-88f4-48d1-9578-7f6751a8ab74) here but am still working on mocking up screens in preparation for the prototype build.

**Comment by brianalloyd** [comment]
@callen2563 are mocks complete?

**Comment by brianalloyd** [comment]
Hifi-Mocks are completed and are being used in support of Prototyping that will be used during Veteran research.
