### ISSUE TITLE
[BE] My VA - Payment Information: Catch up on design and technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32444]
## Background
Now that design direction is confirmed, we need to review design with BE (Lihan), validate our understanding of technical requirements and surface any concerns or requirements

## Tasks
- [ ] Review [design ](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=30b328dd-61fa-4e9c-a615-80a4db99566d)with Tressa
- [ ] Validate and confirm technical understanding with Taylor and Tressa
- [ ] Identify backend requirements, if any, and work with Heather to create tickets

## Acceptance Criteria
Identify any backend efforts that are needed to be clarified and completed, to ensure a smooth deployment of the Payments Information feature.

**Comment by hdjustice** [comment]
No backend work needed for the Payment Info initiative.  closing ticket.
