### ISSUE TITLE
SD - R&S 2.0 Content workflow optimization discovery 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32447]
## Issue Description
_Collaborate with CMS team to learn the current workflow to post R&S Tier 2 article in drupal and what needs to be changed if we want to allow VA employees outside of sitewide content team to post articles, learn what are the limitations and what we can do to resolve._

---
## Tasks
- [ ] _Meet with CMS team to learn current workflow to post content in drupal and the limitation and timeline if we want to make changes to the existing workflow_
- [ ] _Discuss findings and potential changes to existing workflow to stakeholders and get feedback
- [ ] _Document Notes and Action items_

## Acceptance Criteria
- [ ] _Fully understand the current workflow to post on content in drupal, what kind of limitation and effort required from CMS team if we want to make changes to existing workflow_
- [ ] _Brianstorm most effective changes to existing workflow and communicate to stakeholders_
- [ ] _Create tickets for Action items from stakeholder's feedback_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Moving this to blocked for now since our priority is defining KPIs for the Product Outline.
