### ISSUE TITLE
[FE] On-site notifications: Investigate how our system handles markdown 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32446]
## Background
Per our conversation with VA Notify and continued technical discovery around on-site notifications, we need to understand how our system currently handles markdown 

## Tasks
- [x] Investigate how our system handles markdown
- [x] Document your findings
- [ ] Share with the rest of the team

**Comment by tmitchellgcio** [comment]
Preliminary findings: So looks like we have a markdown renderer. They had to do it for the coronavirus chatbot. I need to find where that is in the UI and dissect it.

**Comment by tmitchellgcio** [comment]
For this we use MarkdownIt. It seems fairly simple to use. I think it shouldn't be too difficult to manage

https://github.com/department-of-veterans-affairs/vets-website/pull/19321

**Comment by ajakabcin** [comment]
Thanks @tmitchellgcio!
