### ISSUE TITLE
[Vets-API / EKS] Certificate management for integration w/ external services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32448]
## Description
Vets-API needs to be able to communicate with external services. In order to do this, certificates need to be mounted and made available to the running application inside of EKS. 

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Add certificates to SSM Parameter Store
- [x] Configure deployment to use those certs 

## Acceptance Criteria 
- [x] Certs are available in the pod

**Comment by jhouse-solvd** [comment]
For proof of concept:
- one of the Vets-API certificates could be put into parameter store
- The cert could then be used to bake the public key into the build pipeline of Vets-API
- Test with a single certificate to validate that this will be a good path forward 

Tasks: 
- BE Tools will identify a good cert for testing
- Ops will put the cert into parameter store
- BE Tools will pull the cert from the parameter store to bake into the build image

**Comment by mleclerc00** [comment]
Jeremy and I have made some good progress here this week.  We have a vets api pod running in eks and have done some cleanup to the manifests that makes it much more simple to work with.

For some background information, we were looking to implement a similar solution to how Demian deployed revproxy.  This was the path of least resistance and most definitely the cleanest and quickest route to moving vets-api to eks.  This solution includes the following.

- Implement a 1:1 migration of the jinja config files (dev example being [dev-settings.local.yml.j2](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2)).  Where this becomes interesting is that the idea of [referencing secrets from configMaps](https://github.com/kubernetes/kubernetes/issues/79224) in kubernetes really isn't a thing.  However the tool [jinja2-init](https://github.com/department-of-veterans-affairs/vsp-jinja2-init) which is a fork of [jinja-init](https://github.com/ObjectifLibre/jinja-init) was used to accomplish this.  We have built a fork because the original jinja-init only works for individual files whereas the fork allows for multiple templates to be rendered.  More information about this tool can be found in this [blog post](https://www.objectif-libre.com/en/blog/2018/05/11/jinja-init-how-why/).  With this tool in place we were able to define the [configMap](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/k8s/vets_api_manifest/apps/vsp-tools-backend/vets-api/dev/settings-configmap.yaml) and use jinja templating to reference these variables from the [secrets](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/654148d9c5e5b555e2e1875f6f76e610a3173b75/apps/vsp-tools-backend/vets-api/dev/secrets.yaml#L89).  This all comes together as an [init container](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/654148d9c5e5b555e2e1875f6f76e610a3173b75/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L41) that will render the templates and mount in the vets-api pod before said init container kills itself.

- Next we needed to make sure the correct certs/keys were mounted.  This is much more straight forward and looks like [this](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets) in kubernetes.  For our implementation to make things more simple, we have created a [secret](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/654148d9c5e5b555e2e1875f6f76e610a3173b75/apps/vsp-tools-backend/vets-api/dev/secrets.yaml#L5) that corresponds to each directory we are [mounting](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/654148d9c5e5b555e2e1875f6f76e610a3173b75/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L73) the required keys/certs.

With the above done we have a running vets-api pod that we can successfully connect to and attempt to login to id.me using `yarn watch --env api=<url-to-pod>`.  That being said, I'm not sure how we intend to test external certs because id.me automatically redirects to dev.va.gov so there will likely need to be some discussion about possible solutions.

Jeremy and I will also be going over the vets-api manifests more with a fine tooth comb mostly to double check that all values being pulled from parameter store are correct, make sure we aren't missing any configuration files and or certs/keys, and correcting any folder/file permissions that may be off.

**Comment by jhouse-solvd** [comment]
This is done. The certificates are there. They are built into the pod in EKS. 

In order to validate, we will want to complete #35134. Please see that issue and its parent epic for follow-up. 

Closing.
