### ISSUE TITLE
Modify ClaimDocumentsController for SIP to handle 26-1880

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32455]
## Background
When filling out the 26-1880, supporting documents may be required, so we need to save them so that they can be retrieved when submitting the final application to LGY.

## Tasks
- [ ] modify the `ClaimDocumentsController` to something LIKE this:
```
    def klass
      case form_id
      when '21P-527EZ', '21P-530'
        PensionBurial::TagSentry.tag_sentry
        PersistentAttachments::PensionBurial
      when '21-686C', '686C-674'
        PersistentAttachments::DependencyClaim
      when '26-1880'
        PersistentAttachments::LgyClaim
      end
    end
```

## Acceptance Criteria
- [ ] Code has been implemented and tests are passing
- [ ] A PR is open for review

**Comment by alsleaders** [comment]
PR merged!
