### ISSUE TITLE
EXTERNAL: POST to `/api/eligibility/document`

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32456]
## Background
When submitting the final application to LGY (via POST `/api/eligibility/application/{id}`) we will first need to upload any documents that have been saved in the process of filling out the form.

RELATED TICKET FOR INTERNAL ENDPOINT: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32455

## Considerations
- [Swagger docs](https://int.services.lgy.va.gov/eligibility-manager/swagger-ui/index.html?configUrl=/eligibility-manager/v3/api-docs/swagger-config)
- Pass both pieces of user data `edipi` and `icn`
- Will we need to loop through each of the persisted documents and make a separate call for each or can we do one call with all documents?

## Tasks
- [x] Create a service object method that calls `POST to /api/eligibility/document`

## Acceptance Criteria
- [x] code and tests have been implemented
- [x] A PR has been requested for merging
