### ISSUE TITLE
Generate 26-1880 PDF

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#32457]
## Background
At some point we need to fill out the PDF template with the form data from va.gov. This ticket is for that.

## Considerations
- Possibly break out the call to send the PDF to VBMS, into a separate ticket and this ticket just creates the PDF.
- In the PDF there is a note that says additional information may be added with additional pages. If this is the case, we may have to loop through an array and add to the end of the form.

## Tasks
- [x] Create a pdf for this form ([source](https://www.vba.va.gov/pubs/forms/VBA-26-1880-ARE.pdf))
- [ ] ~~Send to LGY (confirm with Kelli) (another ticket)~~
- [ ] ~~and send to VBMS (a known endpoint) (another ticket)~~

## Acceptance Criteria
- [x] A PDF for this form has been generated ~~and sent~~
- [x] A PR has been submitted for review

**Comment by jason-gcio** [comment]
due by march 3
