### ISSUE TITLE
In the spotlight at Detroit health care bumps the side nav

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32451]
## Issue Description
[The Detroit home page](https://staging.va.gov/detroit-health-care/) looks a little weird in staging. The Left Nav appears above all of the content, rather than on the left. 

<details>
<summary> Screenshot from Staging </summary>

![screencapture-staging-va-gov-detroit-health-care-2021-11-04-15_02_16](https://user-images.githubusercontent.com/55411834/140420656-48e3dfac-ff4a-4dc0-a2cb-468850ff1291.png)

</details>

**Other info**
- the page was updated yesterday (November 3, 2021 at 12:45 p.m.
- could be a block-level element somewhere that’s exceeding the width of its container _(later determined to be the 3rd column of links causing the issue)_

<details>
<summary> In the spotlight at VA Detroit health care </summary>

![image](https://user-images.githubusercontent.com/55411834/140420016-47df9c87-da89-41e7-bca9-06bb81beeac2.png)

</details>

---
## Tasks
- [x] Identify root cause
- [x] Resolve bug
- [ ] Communicate any needed changes to CMS _(CMS will limit to 8 links)_

## Acceptance Criteria
- [ ] Detroit home page displays as expected
