### ISSUE TITLE
Product Roadmap 

### ISSUE THREAD

**Issue by Paula-G-Mendoza** [department-of-veterans-affairs/va.gov-team#32488]

**Comment by nprimak** [comment]
- [ ] Begin process of getting authentication working locally
- [ ] Document API calls for 3 major MVP components (Pharmacy, Messages, and Records)
- [ ] Follow up call with Mobile Team with more concrete technical questions
