### ISSUE TITLE
Move CircleCI workflow to GHA for vets-json-schema

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#32509]
## Issue Description
The vets-json-schema repo CI was never moved over to GHA from CircleCI. There was a [security issue](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/docs/adr/0005-use-github-actions-for-vsp-platform-ci.md) found related to CircleCI, and it's best that we move ALL repos over to the GHA CI based on the documented findings. According to the[ product doc](https://docs.google.com/spreadsheets/d/1k_zjWoNx0KxPRMOqqMUdZ4fQblz2gd_lQAWW-ztnm44/edit#gid=0), be-tools has ownership of the vets-json-schema repo

Additionally, we've seen issues lately where the CircleCI runs are "stuck" and cannot be re-triggered without platform intervention due to GH teams based permission errors. 

---
## Tasks
- [ ] Port over the CircleCI workflow to GHA

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
