### ISSUE TITLE
Sentry: Invalid regular expression: missing )

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32508]
## Description

It appears that adding a parenthesis to:
- New disabilities page (http://sentry.vfs.va.gov/organizations/vsp/issues/54794/)
- the treatment center name on Form 526's medical records page (http://sentry.vfs.va.gov/organizations/vsp/issues/54808/)

causes a regular expression error. I believe this might be a single regular expression used to clean up new disabilities names to be used as a key for the list of issues displayed on the treatment center (medical records) page.

## Tasks

- [ ] Check & update regular expression
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
