### ISSUE TITLE
SD - Resources and Support 2.0 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32516]
## Description

As a product team we would like to redesign the Resources and Support too to better meet the needs of veterans and other va.gov users. 

## Tasks

- [ ] Design Exploration 
- [ ] Integrate Global Search elements update thru UI Consistency Discussions 
- [ ] Finalize Design Work 
- [ ] Review Designs with Ryan Thurlwell & Meg Peters from DEPO (TBD)
- [ ] Initiate Collab Cycle with Project Kickoff
- [ ] Implement Design Recommendations 

## Tracking Collab Cycle Events + Status
- [ ] Project Kickoff  
- [ ] Design Intent

***Summary of feedback:***

|Platform Team|GH Issue| Feedback Comments  |

- [ ] IA request
- [ ] Research Plan Review
- [ ] Analytics Request
- [ ] Usability Testing Prep
- [ ] Contact center review
- [ ] Staging review
- [ ] Privacy + Security
- [ ] Target Launch Date
- [ ] Full Accessibility + 508 Office Audit
- [ ] Post Launch Check in

## Definition of Done

- [ ] Designs have been created, defined and are ready for development team implementation
