### ISSUE TITLE
Support, EVSS/Document service down.  All 526 attachment uploads and Claim Status Tool uploads failed

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#32523]
## Issue Description
Support, EVSS/Document service down for 30+ hours.  All 526 attachment uploads and Claim Status Tool uploads failed.

Impact:
For 526 claims that were successfully submitted to evss but had upload attachments fail, the claim is still submitted, it's just the files did not go through and the success email did not go out. So we are going to re-attempt the uploads and send out the success emails.

No emails for CST, but going to re-attempt those file uploads also.

---
## Tasks
- [x] Find and re-run failed 526 upload jobs
- [x] For successful submissions, re-run email success notification jobs
- [x] Rerun 526 cleanup jobs
- [x] ID and re-run Claims status tool upload jobs

## Acceptance Criteria
- [ ] The goal is to make it seem like the upload service was never down, re-attempt the uploads against the now running service and send out the missing 526 submission success emails.  

Some of the uploads are going to fail with the normal issues(file type not supported, file extension does not match file type) those would have failed out even if the service had not been down.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
All file uploads that failed out are accounted for and the files have been uploaded
