### ISSUE TITLE
Adding necessary GIDS users for AFS team

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#32538]
## Issue Description
We would like to add the following users:

adam.freemer@accenturefederal.com
Abelardo.blanco@accenturefederal.com
Eugenia.gina.ronat@accenturefederal.com
patrick.arthur@accenturefederal.com
dan.brooking@accenturefederal.com
d.a.barnes@accenturefederal.com
jacob.finnern@accenturefederal.com
david.rowley@accenturefederal.com
Hocine.halli@accenturefederal.com
nick.barthelemy@accenturefederal.com

---
## Tasks
- [x] add users to gids db

## Acceptance Criteria
- [x] desired users have gids accounts
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
