### ISSUE TITLE
[Research] Review Site Visit Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32548]
# Description
Prepare for St. Louis visit. Update conversation guide. Finalize research goal of St. Louis trip.

# Tasks
- [x] Review [past site visit guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/site-visits/field-convo-guide-v2.md) and make updates as needed.
- [ ] Write research goals/plan

# Acceptance Criteria
- [x] Create research folder in our research section
- [ ] Finalize conversation guide and research plan

* Take notebooks to St. Louis for notes. No recording of interviews.

**Comment by kristenmcconnell** [comment]
Research folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/nov-site-visit
