### ISSUE TITLE
Collaboration Cycle Checklist for #30611 Notifications on VA.gov (on-site notifications) 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#32557]
## Instructions

<details>

Copy/Paste the below into a new issue to create a checklist of required touchpoints for your project after receiving feedback from your Collab Cycle Kickoff.   The checklist and associated teams are current as of **Nov 3, 2021** based on [VSP's Collab Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
- [Platform website Collab Cycle FAQs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/FAQs.1864073263.html)
- [Collab Cycle Change History](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)
  
### [How to Configure This Checklist](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/)
Tag with vsa and team name

</details>

---

# Collab Cycle Checklist for Notifications on VA.gov (on-site notifications) #30611

## List your team, project contributors, and reviewers
<details>

_Record key players so you can quickly copy/paste into requests and your product documentation as your project progresses_

### Product Team
- OCTO-DE Product Lead: @Samara-Strauss 
- Product Manager: @ajakabcin, @hdjustice 
- FE Engineer: @tmitchellgcio 
- BE Engineer: @lihanli 
- Designer: @tressaellen and @andaleliz 
- Researcher: @tressaellen and @andaleliz 
- Slack channel: vsa-authd-exp
- GitHub tag: onsite-notifications

### VFS participants (when applicable):
- Design Lead: Ryan Thurwell
- Design: 
- Accessibility: @joshkimux, @AngelaFowler82 
- Analytics:
- IA: @mnorthuis 
- Content: @mnorthuis 
- QA: @tlei123 
- Privacy & Security:

</details>

## List project artifacts for requests

<details>

_Link applicable artifacts here so you can quickly copy/paste into requests as your project progresses.  Note that all artifacts may not be needed, depending on nature of the work_
- Project epic  #30611
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md)
- [Wireframes/Mockups - Combined with Payment Information mock-ups](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=9447891e-c22c-4863-8217-3a1273c6c95f)
- [Design Documentation Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp/design)
- User flows
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-conversation-guide.md)
- North Star and KPIs for the product | [How to set](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md)
- Authenticated test-user logins, when applicable. **_Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository_**
- Product URL(s)
- [GH Test Cases document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-PaymentInfo.md)
- Finalized design mockup - [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=408509fb-10d1-4b2f-a6f4-2e2ba827f257) and [Sketch](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [UXPIN Prototype](https://preview.uxpin.com/45251888896c8dd47ef62aa20d3a89a334726ac1#/pages/145483168/simulate/no-panels?mode=i)
- Content brief
- Regression test plans
- [TestRail test cases/test plans](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3308&group_order=asc&display_deleted_cases=0)
- Technical diagrams (architecture diagram, sequence diagram)
     - [Frontend documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/documentation)
- Any new publicly-exposed endpoints
- Any new interactions with dependent VA backends
- Release plan
- Product guide for contact center

</details>

## Pre-Launch touchpoints linked to VSP reference info + practice areas involved at each step

<details>

- [x] Collaboration Cycle Kickoff | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) | [#32151 Request and Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32151)

- [x]  Design Intent  | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) | [#32154 Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32154), [#32297 Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32297) | _Note: PM must invite own team members._
    - [x] Redesign to be submitted to Design Intent team for review [ticket #33301](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33301)
  - Content [#34015 Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34015)
  - Design
  - OCTO
  - IA | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) | [#issuenum]

- [x] [Research Plan Review] |  [ticket #64](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/64)
  - OCTO

- [ ] Analytics Request | [Overview](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html) | [Analytics playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - OCTO

- [x] Midpoint Review | [Overview ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)|  [#34621 Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621) 
  - Accessibility |  [#issuenum] - [Feedback comment in Midpoint ticket #34621](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621#issuecomment-1016708550)
  - Content
  - Design - [Feedback Ticket #35739](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35739)
  - OCTO
  - IA - [Feedback ticket #35765](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35765)
  - QA - [No feedback comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621#issuecomment-1018577253) (test cases drafted)

- [ ] Staging Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - Accessibility [Prep Info](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) | [WGAG 2.1 foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Slide-decks:-WCAG-2.1-new-success-criteria-and-testing.1777893393.html) [#issuenum]
  - Content
  - Design
  - OCTO
  - IA
  - QA | [Overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html)

- [ ] Privacy and Security Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) |  [#issuenum]

- [ ] Contact Center Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) [#issuenum]
    - Contact Center
 
</details>

## Post-Launch Tasks

<details>

- [ ]  Update [Launch Tracker on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/vsa_launch_tracker.md)

- [ ]  Post @here announcement in your Slack channel after launch

- [ ] Full accessibility and 508 office audit | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=noahgelman%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
   - Accessibility

- [ ] Post-Launch Check-in | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html) |  [#issuenum]
  - Product

</details>

## Other Resources

<details>

- [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md)

</details>

## Research/Conversation guide Review
<details>

[**Ticket #64**](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/64) submitted and reviewed by Kevin M Hoffman ([Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1641398079273800?thread_ts=1641389581.253900&cid=C909ZG2BB)):
>I've reviewed both the convo. guide and the plan; overall looks great! My only point of feedback is that your main hypothesis isn't worded in a way that it clearly describes the behavior you're looking to observe, but I can see you'll get at those behaviors clearly from the conversation guide "what to watch for" sections. You can modify the hypothesis if you like, I'll submit this study to Perigean to begin recruiting later today.

</details>

## Experimental Design meeting
<details>

Link to [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/product/Mtg%20Notes%201-7-22%20-%20Design%20System%20Council%20(Experimental%20Design%20proposal%20review).md)

**Decision** 
- Want to hear what you learn
     - Especially related to
          - Perceivability
          - Comprehension
          - Trauma triggers

</details>

## Midpoint Review
<details>

### **Design - Allison/Ryan/Sean**
- Design Feedback ticket #35739 

**Should**
- Make alerts more descriptive
- Great work!
- These alerts/notifications were discussed in the DSC meeting on 1/7/2022 and the midpoint review for authenticated experience payments
- What happens if there are multiple notifications at the top? Do they stack? How many could be there?
- Are all of these really "warning" alerts? Our guidance says "Used to warn a user, such as when there are negative consequences, and when something has gone wrong." And if they are warning alerts are they concerned with triggering the user since there could be multiple?
- Will there be problems if they are separated out bc they will need to scroll, especially mobile.
- If you think of colorblind users and remove the color, it is just a bunch of icons and the weight of the alert gets lost. Maybe we need to remove some other icons on the page.

### **IA - Jim**
- IA Feedback ticket #35765
- Piggyback on design
     - Grouping
     - Could be a little intimidating if stacked, gathered up
- I notice that the conversation guide includes:
  - "Do they mention anything about alerts being on top and mixed into sections of the page?"
  - This seems like a very important area of investigation. I've added suggestions for how we might get more IA-specific feedback.
     - Feel free to pull in Jim and Nikki for advisement on next iteration of this design
          - What is the real job to be done here for the end user?

#### **Consider:**
- Adding a question to prototype eval specifically about distribution of alerts throughout the page. 
  - e.g. *"Talk to me about the way alerts are distributed across different sections. How useful do you think a  user like you would  find this?"*  

- Asking the participant to interpret the different calls to action in top-page alerts, service-level alerts and cards, to see if their mental model for display of tasks and obligations fits what's in the design.
(obv. these are just suggestions; researcher should craft their own wording) 

### **QA - Dariusz**
- Test cases drafted, no feedback at this time.

### **Accessibility - Josh/Sarah/Brian** - [Images included in comment linked here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621#issuecomment-1016708550).  Notes copied below.
- No **must** accessibility feedback from my end-- mostly just design to development considerations.

> #### Should:
> - Start thinking ahead of time of a colorblind context for these. What are other ways to quickly show importance to someone scanning a page that doesn't rely on color?
> 
> #### Design to dev considerations
> - Alt text for the "X" icon in dismissible messages
> - Alt text for the "!" icon in dismissible messages (e.g. should it be "Important" vs. "Alert"-- might need some content advice here). I'd recommend thinking ahead of time how these might be reworded based on how important they are
> - DONE - sr-only (screen reader only) headings. Without these headings, screen reader user may interpret these actions as belonging to "Next appointment" instead
> - DONE - aria-label s for links without a visible purpose/target.
> - DONE - Opportunity to reduce the length of some of the headings that include form names by using aria-describedby to link the text above the heading directly to the heading itself

### **Comments** 

Any changes on product, comment on Mid-point ticket [#34621](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34621)

</details>

**Comment by hdjustice** [comment]
Reviewed feedback with Liz, Taylor and Lihan to ensure there are no surprises or concerns.
