### ISSUE TITLE
Add VA health connect phone number to FL search results 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32552]
## Issue Description
VISN 8 is rolling out a new way for Veterans to communicate with VA health. This number needs to be displayed in search results for relevant facilities. The number for VA health connect is the same for all facilities within the VISN and can be hard coded for this implementation. We will likely need to return to this work and implement a number using a data field in the future.

## Data from Lighthouse

```
{
  "data": [
    {
      "id": "vha_688",
      "type": "va_facilities",
      "attributes": {
        "lat": 38.9311137,
        "long": -77.0109110499999,
        "name": "Washington VA Medical Center",
        "visn": "20",
        "hours": {
          "friday": "9AM-5PM",
          "monday": "9AM-5PM",
          "sunday": "Closed",
          "tuesday": "9AM-5PM",
          "saturday": "Closed",
          "thursday": "9AM-5PM",
          "wednesday": "9AM-5PM"
        },
```

![image](https://user-images.githubusercontent.com/55411834/140570738-9e390350-e0f1-4600-a053-62c58bef4e58.png)

---
## Tasks
- [ ] Add "VA health connect" phone number to search results when facility type = VA health and VISN= 8
- [ ] Add flipper to control this display

## Acceptance Criteria
When facility type = VA health and VISN= 8, search result cards will include 
- [x] Main number: (phone)
- [x] VA health connect: 877-741-3400
- [x] Mental health: (phone)
Display of VA connect number can be toggled on/off

**Comment by srsuddath** [comment]
Here is the PR that will accomplish this task. Screenshots are included to show the new number appearing on VISN 8 locations
https://github.com/department-of-veterans-affairs/vets-website/pull/19484

**Comment by srsuddath** [comment]
The PR to add the flipper to vets API is here, it was merged today, so should be live with the deploy on monday.
https://github.com/department-of-veterans-affairs/vets-api/pull/8489

**Comment by mmiddaugh** [comment]
This feature is governed by the facility_locator_show_health_connect_number flag which is turned on in staging (but off in prod)
