### ISSUE TITLE
[Research] Review Health Questionnaire Past Research

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32553]
# Description
We need to understand the work that has been completed on health questionnaires to date.

# Tasks
- [ ] Kristen to send out list of past research
- [ ] Everyone review research
- [ ] Meeting to review past research

# Acceptance Criteria
- [ ] Meeting held

**Comment by kristenmcconnell** [comment]
Move to beginning of next sprint.
