### ISSUE TITLE
[Research] My VA 2.0 enhancements: Payment feature familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#32558]
## Background
As part of our discovery around My VA 2.0 enhancements and the possibility of including a payments section in our next round of enhancements to the dashboard, we need to familiarize ourselves with the payment feature tool.

## Tasks
- [x] Get familiar with the tool on [staging](https://staging.va.gov/va-payment-history/payments/) (leverage test user 36)
- [ ] Consult with eBenefits migration team if you have questions
- [x] Report back/consult with PM(s) and Samara on findings
- [ ] Document recommendations on what we can/should include in a potential payment section on My VA dashboard

**Comment by tressaellen** [comment]
Here is the [synthesis of my discovery findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/payment-discovery-synthesis.md), we'll talk through everything on Monday. 

The full discovery document can be seen [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/payment-history-discovery.md)
