### ISSUE TITLE
[Research] St. Louis Synthesis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32564]
## User Story
- As a product team, we want to know the findings from the St. Louis trip. 

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan and Conversation guide]()

## Description
Analyzing the videos and notes from the trip to St. Louis to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [x] Post synthesis documents to GitHUB
- [x] Write top-line summary (optional if daily summaries were sent out)

**Comment by kristenmcconnell** [comment]
[Synthesis Mural document](https://app.mural.co/t/vfscie8528/m/vfscie8528/1636988669152/a67708f12dcd56035eb5cf12f0e32e414467c399?sender=uc940f53ad96ac0203d6d3631)

**Comment by kristenmcconnell** [comment]
Top findings were sent out via Slack, so going to move directly onto final report (not topline summary).

**Comment by kristenmcconnell** [comment]
Synthesis document posted to GitHUB here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/nov-site-visit/README.md
