### ISSUE TITLE
[Research] St. Louis Research Report

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32568]
## User Story
- As a product team, we want to document and share the findings from the trip to St. Louis.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan and Conversation Guide]()
- Synthesis for this report completed in ticket #32564

## Description
A research report detailing findings and design recommendations from the trip to St. Louis.

## Reference Materials
- Review [Platform research website](https://depo-platform-documentation.scrollhelp.site/research-design/) and [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [x] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [x] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with 
  - [x] Stakeholders (talk to Patrick about when to do this)
  - [x] team (either via Slack or Zoom meeting)
  - [x] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by kristenmcconnell** [comment]
The research report can be found here on GitHUB: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/nov-site-visit/research-findings.md

Originally @julieadair1  was scheduled to present to the stakeholder group on Nov. 22, but the meeting was canceled. Julie will present at a later date.

**Comment by kristenmcconnell** [comment]
@julieadair1 @jparker0425 There are a few topics that we should add to the Trello board or make tickets for within the recommendations section of [this report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/nov-site-visit/research-findings.md). Maybe we can talk about this during our next refinement meeting.

**Comment by kristenmcconnell** [comment]
Messaged Naomi on Nov. 23.

**Comment by kristenmcconnell** [comment]
Tentatively on the calendar to present at the Monday research/design/content sync on Dec. 6. Naomi is going to schedule Julia and me at the same time, since we are covering a similar topic.

**Comment by julieadair1** [comment]
@kristenmcconnell I am out the entire week of Dec. 6 for surgery.

**Comment by kristenmcconnell** [comment]
Added to research repo here: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/37

**Comment by kristenmcconnell** [comment]
@julieadair1 Dec. 6 is the design sync presentation and not the stakeholder meeting. I'll present at the design sync. I don't know when the presentation at the stakeholder meeting is rescheduled for.
