### ISSUE TITLE
[Research] St. Louis Research Report

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#32567]
## User Story
- As a product team, we want to document and share the findings from the trip to St. Louis.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan and Conversation Guide]()
- Synthesis for this report completed in ticket #32564

## Description
A research report detailing findings and design recommendations from the trip to St. Louis.

## Reference Materials
- Review [Platform research website](https://depo-platform-documentation.scrollhelp.site/research-design/) and [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [ ] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)

## Acceptance Criteria
- [ ] Post research report to GitHub as presentation and markup document
- [ ] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [ ] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with 
  - [ ] Stakeholders (talk to Patrick about when to do this)
  - [ ] team (either via Slack or Zoom meeting)
  - [ ] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by kristenmcconnell** [comment]
Not needed. Accidentally created two tickets. The ticket where this work will occur is #32568.
