### ISSUE TITLE
Add VA health connect number to VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32561]
Issue Description
VISN 8 is rolling out a new way for Veterans to communicate with VA health which needs to be displayed under Location and contact information on the relevant facility pages. The number for VA health connect is the same for all facilities within the VISN 

Main and mental health numbers are data and will continue to be displayed. (not replaced)

 Main number: (phone)
 VA health connect: 1-877-741-3400
 Mental health: (phone)

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/140574769-c804965f-045e-401e-9737-9c911ddb028c.png)

![image](https://user-images.githubusercontent.com/55411834/140574803-7f96fb00-3d51-48f6-86da-6aa6c45b01d7.png)

</details>

## Tasks
Add "VA health connect" phone number to the phone number section under Location and contact information for facilities within the following systems

- VA Bay Pines health care
- VA Caribbean health care
- VA Miami health care
- VA North Florida health care
- VA Orlando health care
- VA Tampa health care
- VA West Palm Beach health care

Add flipper to control display of VA connect number

##Acceptance Criteria
- [ ] Veterans viewing the system home page for VISN 8 systems will see the VA health connect phone number displayed within the Locations and contact information for visible facilities 
- [ ] Veterans will see the VA health connect phone number displayed within the Locations and contact information section of facilities pages within VISN 8
- [ ] Display of VA connect number can be toggled on/off

**Comment by gescobardev** [comment]
@mmiddaugh A few questions for you

1. Yesterday you mentioned that there may not be a number "1" at the start of the phone number. Can you confirm the correct number?

2. I added the va connect phone number in the middle of main and mental health number. Is that still what we want?

3. If I'm understanding correctly, the health connect phone number should be added to the following places: 
If we are looking at North Florida health care (visn 8), we should see the number here:

<details>
<summary>north-florida-health-care/</summary>

![Screen Shot 2021-11-09 at 9 50 21 AM](https://user-images.githubusercontent.com/84030819/140947080-045ca235-be3c-4fa4-ab2b-f8f63ee043e3.png)

</details>

<details>
<summary>north-florida-health-care/locations</summary>

![Screen Shot 2021-11-09 at 9 57 37 AM](https://user-images.githubusercontent.com/84030819/140948117-0959faaa-d6a5-43d8-89ea-d2fce065f41c.png)

</details>

And all the facility pages attached to that visn
For example:

<details>
<summary>north-florida-health-care/locations/gainesville-ninety-eighth-street-va-clinic/</summary>

![Screen Shot 2021-11-09 at 10 03 50 AM](https://user-images.githubusercontent.com/84030819/140949159-39ad8408-d5af-4ab7-86d1-e034f818cf52.png)

</details>

I think I captured all the places it should be added. Does this look correct?

**Comment by gescobardev** [comment]
Per Michelle, remove the number 1 from phone number and phone number can be placed between main and mental health.
