### ISSUE TITLE
Login.gov rollout plan

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#32588]
**Launch Checklist**
- [ ] Documentation is ready
- [ ] Unit Tests Ready
- [ ] Security Review
- [ ] Product Owner Sign-off
- [ ] All appropriate parties notified

**Non-Launch Blockers**
- [ ] Auth experience update direct deposit change account to include login.gov IAL2. [Slack Thread](https://dsva.slack.com/archives/C909ZG2BB/p1637183645166300)

**Rollout Plan**
- [ ] Released but hidden for users (live) for testing (phase 1) - _Nov 19 target date_
- [ ] Released as sign-in button (no account creation) (phase 2) - _Dec 8 target date_
- [ ] Add "Create account" button (phase 3) - _Sure would be nice on Dec 8 but not required_

**To-do**
- [ ] Ticket/Epic for Login.gov to be single round-trip (Reducing use of identity attributes at Epic level) (Nick)

**Epic-level A/C**
- [x] login.gov button behind flipper for (MHV) unified sign-in page
- [ ] "Verify" button is in place
- [x] Find and analyze all locations referring to specific CSP's and ensure Login.gov is added (ex: "sign in with your id.me, dslogon, or mhv account" and options are ordered same as sign-in page)

**Goal**
Users can sign-in/create accounts via login.gov at the same level as other CSP's.

**Decision**
Login.gov rollout does not need to solve the single round-trip, that can be handled later.

**Complications**
MHV has no dev resources Nov/Dec so will not accept Login.gov sign-on until Jan.

**Comment by codyreinold-usds** [comment]
As discussed, Login.gov should not be released to MHV and My VA Health on initial release (via /sign-in/).
