### ISSUE TITLE
Move PgHero to K8s (outside of vets-api)

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#32597]
## Issue Description
PgHero currently takes a significant time to compile (bundle install) and adds 1-200MB to our bundle cache. There is a [Docker guide](https://github.com/ankane/pghero/blob/master/guides/Docker.md) for moving PgHero to Docker and additionally a K8 guide. We will want to move this running as it's own k8s deployment for each respective environment. 

---
## Tasks
- [x] Read through documentation
- [x] Define necessary steps to pull PgHero out of vets-api
- [x] Define k8s manifest files (for each env)
- [x] Update infra (vets-api-pghero) infra repo config & Dockerfile
- [x] Add GHA for mirroring images and updating manifest files
- [ ] Remove PgHero from vets-api

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Private repo created [here](https://github.com/department-of-veterans-affairs/vets-hero)

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/vets-api-pghero/pull/2

**Comment by ericboehs** [comment]
Current status: pulling out k8s manifest into another repo; creating a Dockerfile so we can host on ECR (via convos with Lindsey)

**Comment by LindseySaari** [comment]
Update: PgHero is LIVE in the dev environment! YAY! It was decided that we will need to deploy pghero once per env/cluster instead of deploying only once. This is due to security group rules reaching across subnets for RDS connections. For example, the PgHero application living in the dev cluster would have to reach across subnets to the RDS instance, in lets say staging and current security groups/policies DO NOT permit this. [PR here](#242 Add pghero manifests for each env)

Next: work on the vets-api-pghero infra repo GH Actions work for ci and mirroring images.

**Comment by LindseySaari** [comment]
Monday update: PgHero is deployed in all envs! Big thanks for @mleclerc00 🥳  I'm currently working on the GHA workflows for the vets-api-pghero repo to mirror images to ECR and update the deployment manifest on push when a new image is pushed to ECR. DRAFT PR [here](https://github.com/department-of-veterans-affairs/vets-api-pghero/pull/5)
