### ISSUE TITLE
Build feature toggle and entry point for event page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32599]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- Need to consider design specs and CMS dependencies 
- Consider relationship between past events page (might need to hide past events page)
- Consult design and CMS for questions as changes are frequently applied

### Tasks
- [x] Build feature toggle (event page) 
- [x] Build needed entry points for event page 
- [x] Test locally to determine functionality
- [x] Consult a11y team with any questions 
- [x] Consult design on any questions 
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Feature toggle and entry points are in place for event page 
- [x] Local test are completed and show signs of success
- [x] a11y considerations are implemented in support
