### ISSUE TITLE
[Design] Profile: Update navigation on all Sketch files to reflect updates for Personal Info Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32607]
## Issue Description
As a designer, I want to update the navigation in the Profile Sketch files so that they reflect the current state of the product.

---
## Tasks
- [ ] Update the navigation in each section of the Profile Sketch files to show that Contact and Personal Information have been separated.

## Acceptance Criteria
- [ ] Each section of the Profile Sketch files will show Contact and Personal Information have been separated in the navigation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Assigning to Liz per Samara

**Comment by andaleliz** [comment]
@cgednalske are the latest Direct Deposit and Personal Info Sketch files uploaded to Sketch for Teams? If so, I can go ahead and make sure the nav symbol is updated to use the latest one from the library. If not - would you mind updating your local files? Then we can close this out. Thanks!

**Comment by cgednalske** [comment]
@andaleliz they are, but I'm still finishing up the last changes/button updates in Direct Deposit, so they will change again slightly.

**Comment by andaleliz** [comment]
This is complete
