### ISSUE TITLE
Build out events page app 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32600]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- Need to consider design specs and CMS dependencies 
- Consider relationship between past events page (might need to hide past events page)
- Consult design and CMS for questions as changes are frequently applied

### Tasks
- [ ] Build events page app
- [ ] Test locally to determine functionality
- [ ] Consult a11y team with any questions 
- [ ] Consult design on any questions 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] build events page app per design mockups  
- [ ] Local test are completed and show signs of success
- [ ] a11y considerations are implemented in support

**Comment by kelsonic** [comment]
Design: https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19526

**Comment by kelsonic** [comment]
PR merged, will be on staging shortly
