### ISSUE TITLE
Swap out videos in vaccine CLP-HOLD FOR WEEK OF 11/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32604]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John Scott McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [x] New ticket created

**Comment by RLHecht** [comment]
@lunascoop We can swap these out this week and then I'll create a new ticket for 2 weeks from now.

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
I reviewed and published this page. Will create a new ticket for next sprint. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
