### ISSUE TITLE
Update Verify Button Colors To Match New Design

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#32611]
## Issue Description
The "Verify With`Login.gov` and `Id.me`" buttons are currently using the static blue color from previous designs. They need to be updated to match latest design.
---
## Tasks
- [x] Verify with Login.gov button has "red" style
- [x] Verify with ID.me button has "green" style

## Acceptance Criteria
- [x] Verify buttons match latest style colors
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
