### ISSUE TITLE
[PM, Design] On-site Notifications: Determine how to handle the Nametag on child pages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#32618]
## Background
After our discussion with Ryan, Josh & Angela, it was mentioned that we should consider removing the Nametag on the child pages within Notifications.  We need to determine how we want to handle the Nametag section on the pages.

---
## Tasks
- [ ] Talk with team/PO regarding Ryan's suggestion to remove the Name section at the top of the page (aka Nametag)
- [ ] Document decision made by the team/PO
- [ ] Finalize design based on decision
- [ ] Consolidate all design changes to complete Design Intent ticket #32297 

## Acceptance Criteria
- [ ] Finalize decision on Name section (nametag) with /PO
- [ ] Document design decision
---

**Comment by hdjustice** [comment]
Closing ticket - approach is being re-evaluated. Pausing on this effort until further notice.
