### ISSUE TITLE
GIBCT Analytics - Add Analytics - Compare

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#32629]
## Issue Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics. After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics.

This story is to add Analytics to Compare functionality.
### COMPARE
- Compare selections from Name search
- Compare selections from Location search
- Does user select schools to compare
- How many schools are users selecting (1, 2, 3)
- Comparison limit modal displays (too many schools)
- Remove schools from Tray? Remove Schools from Comparison Page?
- User engages with "Highlight differences" checkbox

---
## Tasks
 - [ ] Add GA analytics calls to various points in location search page to trigger necessary events

## Acceptance Criteria
- [ ] GA analytics reporting compare selections from Name search
- [ ] GA analytics reporting if users compare selections from Location search
- [ ] GA analytics reporting if users if user select schools to compare
- [ ] GA analytics reporting how many schools users are selecting (1, 2, 3)
- [ ] GA analytics reporting if comparison limit modal displays (too many schools)
- [ ] GA analytics reporting if users remove schools from tray or remove schools from Comparison Page.
- [ ] GA analytics reporting if users engages with "Highlight differences" checkbox

## Supporting Artifacts:
1. [Originating story]https://github.com/department-of-veterans-affairs/va.gov-team/issues/27074
---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontool')
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`discovery`)

**Comment by dsrr47** [comment]
> User engages with "Back to top" element

This page does not have a"back to top " component.

**Comment by ERRonat0609** [comment]
@dsrr47 Ok, well I did not add these acceptance criteria, so lets find out who did. Maybe @dan-brooking can help. If there is no "back to top" function then we can remove it.

**Comment by dsrr47** [comment]
@ERRonat0609  I set up the acceptance criteria based on [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/analytics.md). I wanted to mention it so we are aware there isn't one on that page. I can remove it from the acceptance criteria if thats find to do.

**Comment by hallihocine** [comment]
Ticket has been validated in staging
Process: Triggered events via UI then validated using ObservePoint TagDebugger chrome extension

**Comment by hallihocine** [comment]
### **Screenshots**

- GA event triggered and reporting if users compare selections from Name search
<img width="859" alt="From nam tab" src="https://user-images.githubusercontent.com/86266024/142480678-fba9c984-ce5f-4a9c-8d23-fb3865559036.png">

- GA event triggered and reporting if users compare selections from Location search
<img width="843" alt="From location tab" src="https://user-images.githubusercontent.com/86266024/142480855-4fc2de9f-46d0-4038-b013-51f5a83ee883.png">

-  GA event triggered and reporting if users select schools to compare
<img width="833" alt="School added 1" src="https://user-images.githubusercontent.com/86266024/142481202-3fdb369d-dc79-43a0-93b1-e082d4075097.png">
<img width="840" alt="School added 2" src="https://user-images.githubusercontent.com/86266024/142481236-5a3420b1-ac8e-40f5-925f-fb6497ab0dfb.png">
<img width="810" alt="School added 3" src="https://user-images.githubusercontent.com/86266024/142481267-6f066f7e-32e3-45b7-a6a6-4c714af0423a.png">

-  GA event triggered and reporting how many schools users are selecting (1, 2, 3)
<img width="820" alt="Reporting number 1" src="https://user-images.githubusercontent.com/86266024/142481383-ccf73711-ba3f-4fad-a9a9-60265943f9dd.png">
<img width="850" alt="Reporting number 2" src="https://user-images.githubusercontent.com/86266024/142481414-5eddd47c-4fe9-4022-a413-76f94fd8591c.png">
<img width="821" alt="Reporting number 3" src="https://user-images.githubusercontent.com/86266024/142481434-29c0a717-6487-4387-a167-726d071345d0.png">

- GA event triggered and reporting if comparison limit modal displays (too many schools: more than 3)
<img width="853" alt="Comarison limit reached" src="https://user-images.githubusercontent.com/86266024/142482679-95b6d6e6-44e4-437e-8c88-e9a96202c4e6.png">

- GA event triggered and reporting if users remove schools from tray or remove schools from Comparison Page
1. Remove schools from comparison drawer: 
<img width="844" alt="school removed from tray" src="https://user-images.githubusercontent.com/86266024/142481910-0813da17-9957-453a-9549-54518464796e.png">
2. Remove schools from compare page: 
<img width="821" alt="School removed from compare page" src="https://user-images.githubusercontent.com/86266024/142482026-8f1ef2da-8752-4f77-96ef-359603a13ba5.png">

- GA event triggered and reporting if users engage with "Highlight differences" checkbox
<img width="732" alt="Highlight diff checked" src="https://user-images.githubusercontent.com/86266024/142482176-1661d17f-1a91-40a6-a4f4-f102559b9dcb.png">

**Comment by hallihocine** [comment]
- Test run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2585&group_by=cases:section_id&group_order=asc&group_id=2922

- Test Script/Steps:
[GIBCT Analytics - Add Analytics - Compare.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7565462/GIBCT.Analytics.-.Add.Analytics.-.Compare.xlsx)
