### ISSUE TITLE
GIBCT Analytics - Add Analytics - Search Results

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#32627]
## Issue Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics. After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics.

This story is to add Analytics to the Search Results.

---
## Tasks
- [ ] Trigger GA event when user opens up warning panel to view more information for schools with cautionary warnings
- [ ] Trigger GA event when user visits profile of school with cautionary warnings

## Acceptance Criteria
- [ ] GA event triggered when user opens up warning panel to view more information for schools with cautionary warnings
- [ ] GA event triggered when user visits profile of school with cautionary warnings

---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontoolp')
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`discovery`)

**Comment by hallihocine** [comment]
Ticket has been validated in staging 
Process: Triggered events via UI then validated using ObservePoint TagDebugger chrome extension

**Comment by hallihocine** [comment]
### **Screenshots**

- GA event triggered when user opens up warning panel to view more information for schools with cautionary warnings
<img width="868" alt="Warning Panel Opened" src="https://user-images.githubusercontent.com/86266024/142277058-73146284-2d9c-4fd0-a7a5-d123eb71a1c5.png">

- GA event triggered when user closes the warning panel
<img width="869" alt="Warning Panel closed" src="https://user-images.githubusercontent.com/86266024/142277184-44c2d4e8-a5bc-4627-a531-255dbbcfc56e.png">

- GA event triggered when user visits profile of school with cautionary warnings
<img width="838" alt="Profile clicked" src="https://user-images.githubusercontent.com/86266024/142277277-27f5727e-be23-412c-9b10-ea147189b386.png">

**Comment by hallihocine** [comment]
- Test run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2581&group_by=cases:section_id&group_order=asc&group_id=2922

- Test Script/Steps:
[GIBCT Analytics - Add Analytics - Search Results.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7557829/GIBCT.Analytics.-.Add.Analytics.-.Search.Results.xlsx)
