### ISSUE TITLE
GIBCT Analytics - Add Analytics - Search Name Page

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#32625]
## Issue Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics.  After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics.

This story is to add Analytics to the Search Name Page.

- Name search executed
- Name Search terms
- User selects from autocomplete results listing
- Name search returns 0 results
- "Tuition housing & estimates" Accordion
  - Accordion opens
  - Update selections inside accordion - which selections
  - "Learn more" selected - which ones?
- "Filter your search" accordion
  - Accordion opens
  - Update selections inside accordion - which selections
  - "Learn more" selected - which ones?

---
## Tasks
- [ ] Add GA analytics calls to various points in name search page to trigger necessary events

## Acceptance Criteria
- [ ] GA event triggered when name search executed
- [ ] GA event triggered logging name search terms
- [ ] GA event triggered when user selects from autocomplete results listing
- [ ] GA event triggered when 0 results
- [ ] GA event triggered when "Tuition housing & estimates" accordion opened/closed
- [ ] GA event triggered when selection changed in "Tuition housing & estimates" accordion
- [ ] GA event triggered when learn more selected under "Tuition housing & estimates" accordion
- [ ] GA event triggered when "Filter your search" accordion opened/closed
- [ ] GA event triggered when selection changed in "Filter your search" accordion
- [ ] GA event triggered when learn more selected under "Filter your search" accordion

---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontool`)
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`discovery`)

**Comment by hallihocine** [comment]
Ticket has been Validated in staging. 
Process: Triggered events via UI then validated using ObservePoint TagDebugger chrome extension

**Comment by hallihocine** [comment]
### Screenshots

- GA event triggered for search results cm41 = number of results, cm42 = total number of pages): 
<img width="875" alt="SearchResults" src="https://user-images.githubusercontent.com/86266024/141158614-8b75edc0-2406-4a4d-aa1f-50dd16549615.png">

- Search Executed and Search Term:
<img width="883" alt="Search Executed and Search term" src="https://user-images.githubusercontent.com/86266024/141161756-f9e80081-c5fe-4a2c-bf13-f42a20982fe8.png">


- GA event triggered when user selects from autocomplete results listing:
<img width="890" alt="Autosuggest" src="https://user-images.githubusercontent.com/86266024/141159287-f19a6f30-ac6d-4ad0-9a5a-06eacc952d18.png">

- GA event triggered when 0 results: 
<img width="886" alt="Zero results" src="https://user-images.githubusercontent.com/86266024/141159446-bf2dcf5f-0a03-401c-9e56-7650093f0461.png">

- GA event triggered when "Tuition housing & estimates" accordion opened: 
<img width="882" alt="Update tuition accordion opened" src="https://user-images.githubusercontent.com/86266024/141159622-9c1029c3-ea29-49aa-85e9-885c437b7f43.png">

- GA event triggered when "Tuition housing & estimates" accordion closed:
<img width="890" alt="Tuition accordion closed" src="https://user-images.githubusercontent.com/86266024/141159721-68db48e0-23bf-4dc0-b69e-780de44e2000.png">

- GA event triggered when selection changed in "Tuition housing & estimates" accordion:
<img width="885" alt="Tuition accordion updated" src="https://user-images.githubusercontent.com/86266024/141159860-0bf118a2-4dad-4627-be3d-347166db8a76.png">

- GA event triggered when learn more selected under "Tuition housing & estimates" accordion:
<img width="888" alt="Learn more link clicked" src="https://user-images.githubusercontent.com/86266024/141160009-dfcd521a-e8f9-40fe-8803-8e13cf9589fb.png">

- GA event triggered when "Filter your search" accordion closed:
<img width="892" alt="Filter accordion closed" src="https://user-images.githubusercontent.com/86266024/141160201-9c1f2eff-b9ac-4406-bacc-15504181a28c.png">

- GA event triggered when selection changed in "Filter your search" accordion: 
<img width="888" alt="Filter Change" src="https://user-images.githubusercontent.com/86266024/141160327-7455c766-6e48-4392-b587-0fa21bf831c3.png">

- GA event triggered when learn more selected under "Filter your search" accordion:
<img width="895" alt="Learn more link clicked 2" src="https://user-images.githubusercontent.com/86266024/141160458-e62089d6-ee66-4ff2-a8be-2bcb384c0c02.png">

**Comment by hallihocine** [comment]
- TestRun in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2561&group_by=cases:section_id&group_order=asc&group_id=2922

- Test Script/Steps:
[Re-geocode in gibct.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7514720/Re-geocode.in.gibct.xlsx)

**Comment by af-manish** [comment]
Passed QA, validate with EDU once all analytics tickets done.

**Comment by mrblanco1** [comment]
Re-opened by mistake. Closing, as it should be.
