### ISSUE TITLE
GIBCT Analytics - Add Analytics - Location Search Page

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#32626]
## Issue Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics. After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics.

This story is to add Analytics to the Location Search Page.

- Location Search tab selection
- Location search executed
- Location Search terms
- User selects from autocomplete results listing
- Location search returns results
- User engages with "Use my current location" to search
- User adjusts radius option
- User engages with map to search
- User engages with markers on map
- "Tuition housing & estimates" Accordion
  - Accordion opens
  - Update selections inside accordion - which selections
  - "Learn more" selected - which ones?
- "Filter your search" accordion
  - Accordion opens
  - Update selections inside accordion - which selections
  - "Learn more" selected - which ones?
---
## Tasks
- [ ] Add GA analytics calls to various points in location search page to trigger necessary events

## Acceptance Criteria
- [ ] GA event triggered when location search tab selected
- [ ] GA event triggered when location search executed
- [ ] GA event triggered logging location search terms
- [ ] GA event triggered when user selects from autocomplete results listing
- [ ] GA event triggered when 0 results
- [ ] GA event triggered when user engages with "Use my current location" to search
- [ ] GA event triggered when user adjusts radius option
- [ ] GA event triggered when user engages with map to search
- [ ] GA event triggered when user engages with markers on map
- [ ]  GA event triggered when "Tuition housing & estimates" accordion opened/closed
- [ ]  GA event triggered when selection changed in "Tuition housing & estimates" accordion
- [ ]  GA event triggered when learn more selected under "Tuition housing & estimates" accordion
 GA event triggered when "Filter your search" accordion opened/closed
 GA event triggered when selection changed in "Filter your search" accordion
 GA event triggered when learn more selected under "Filter your search" accordion
---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontoolp`)
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`discovery`)

**Comment by hallihocine** [comment]
Ticket has been validated in staging
Process: Triggered events via UI then validated using ObservePoint TagDebugger chrome extension

**Comment by hallihocine** [comment]
Screenshots### 

- GA event triggered when location search tab selected
<img width="895" alt="Location tab clicked " src="https://user-images.githubusercontent.com/86266024/142256847-4031b91a-2cbf-4653-9abd-c0693d5902e1.png">

-  GA event triggered when user selects from autocomplete results listing
<img width="866" alt="autosuggestion" src="https://user-images.githubusercontent.com/86266024/142256950-e720a4bd-e3cb-4933-b952-400abd1d46fe.png">

-  GA event triggered when location search executed
<img width="893" alt="Search Executed" src="https://user-images.githubusercontent.com/86266024/142257073-73f06f74-929c-4b8e-8560-42d32f7442a6.png">

-  GA event triggered when user engages with "Use my current location" to search
<img width="896" alt="UseMyLocation clicked" src="https://user-images.githubusercontent.com/86266024/142257273-8a7590ea-8617-4983-ad24-4f2f3ba0cfcd.png">

- GA event triggered when user adjusts radius option
<img width="893" alt="Radius adjusted" src="https://user-images.githubusercontent.com/86266024/142257366-e93b2c69-47ac-43a5-bad4-916e13682fb4.png">

- GA event triggered when user engages with map to search
<img width="890" alt="SearchArea map clicked" src="https://user-images.githubusercontent.com/86266024/142257489-a15b03e8-b2cb-4a92-983f-ed1302556493.png">

- GA event triggered when user engages with markers on map
<img width="894" alt="Map Marker clicked" src="https://user-images.githubusercontent.com/86266024/142257580-84c019d0-dccd-4835-b0df-81db66f1badd.png">

-  GA event triggered when "Tuition housing & estimates" accordion opened
<img width="865" alt="Accordion opened" src="https://user-images.githubusercontent.com/86266024/142257689-cd7daecf-2f1d-4c68-be20-de10a9c9594f.png">

- GA event triggered when selections changed in "Tuition housing & estimates" accordion
<img width="868" alt="Selection updated1" src="https://user-images.githubusercontent.com/86266024/142257915-8e18878c-2116-4311-9031-2adad541d1bc.png">
<img width="886" alt="Selection updated 2" src="https://user-images.githubusercontent.com/86266024/142257941-312dd823-8d1c-494f-be1d-3686829b2a8e.png">
<img width="869" alt="Selection updated3" src="https://user-images.githubusercontent.com/86266024/142257964-b4c97b4e-d706-4f06-951d-f7698b35dd04.png">

-  GA event triggered when learn more selected under "Tuition housing & estimates" accordion
<img width="879" alt="Learn more clicked" src="https://user-images.githubusercontent.com/86266024/142258116-fe4f1bea-fe6c-4909-bfd9-95aeeac59ecc.png">

-  GA event triggered when "Tuition housing & estimates" accordion closed
<img width="872" alt="Accordion closed" src="https://user-images.githubusercontent.com/86266024/142258225-2e785cc5-fe19-483f-8493-a49c80dbbec3.png">

- GA event triggered when "Filter your search" accordion opened
<img width="876" alt="Filter accordion opened" src="https://user-images.githubusercontent.com/86266024/142258340-adcb388b-4617-4641-989d-61b3ae37f114.png">

- GA event triggered when selection changed in "Filter your search" accordion
- 
<img width="872" alt="Filter Updated 1" src="https://user-images.githubusercontent.com/86266024/142258441-abe5c59d-9c2b-45df-8493-1159f9929cca.png">

- GA event triggered when learn more selected under "Filter your search" accordion
<img width="857" alt="Filter learn more clicked" src="https://user-images.githubusercontent.com/86266024/142258528-fe5fc4ec-4aa6-49b2-bad4-af217c925813.png">

- GA event triggered when "Filter your search" accordion closed
<img width="864" alt="Filter accordion closed" src="https://user-images.githubusercontent.com/86266024/142258633-c47fda66-1691-4655-aa1a-377552587963.png">

**Comment by hallihocine** [comment]
- Test run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2579&group_by=cases:section_id&group_order=asc&group_id=2922

- Test Script/Steps:
[GIBCT Analytics - Add Analytics - Location Search Page.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7557024/GIBCT.Analytics.-.Add.Analytics.-.Location.Search.Page.xlsx)
