### ISSUE TITLE
Acquire staging logins for VA.gov orientation user scenarios

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32622]
## Issue Description
We have defined the [VA.gov user scenarios](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31545) we'd like to include in Platform Orientation for VFS teams. We must now reach out to Testing Tools Team and/or Identity team to get staging logins created for the specific scenarios at hand. 

We also need to identify how the owner of the staging logins would like to be identified when/if the login credentials need to be reset. Ideally, it will be the VFS team members responsibility to notify the appropriate party upon the completion of their scenarios to have the logins reset and ready for the next VFS team member.

---
## Tasks
- [ ] Reach out to Testing Tool team and/or Identity team to get staging logins created so team members can complete the user scenario tasks

## Acceptance Criteria
- [ ] Testing tools team and/or Identity will have all the information they need to create logins
- [ ] The staging logins have been created and shared with Platform Product Support
- [ ] Testing tools team and/or Identity team have communicated their preference for resetting the logins

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Test scenarios are documented in [this ticket]( https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31545) 
Also listing them here:  

- [x]  Healthcare
 As a Veteran I want to fill out and submit the 10-10 EZ form so that I can get health care benefits through VA.

- [x]  Education
As a Veteran I want to learn about and compare the education programs and benefits I am eligible for through the GI Bill. 

- [x]  Disability
As a Veteran I want to fill out and submit a Request a Higher-Level Review form to request a review of my disability claim.

- [x] Burials & memorials
As a surviving spouse of a deceased Veteran, I want to fill out and submit the 21P-530 form to apply for burial benefits to pay for a funeral. 

- [x]  My Profile
As a Veteran, I want to add or update my phone number in my profile account. 

- [x]  Facility locator
As a Veteran, I want to find a Vet Center that is closest to me.

- [x] Records
As a Veteran, I want to download documentation that shows my benefits and service history.

- [x]  Caregivers
As a Veteran caregiver, I want to apply for caregiver help or support services. 

-  [x] Find a VA Form Search
As a Veteran, I want to find out what VA forms are available to fill out and submit online on VA.gov.

**Comment by peggygannon** [comment]
@allison0034 
**11/17 update** Send login request to testing tools team via Slack: 

https://dsva.slack.com/archives/D01BT9H13C6/p1637170918000100

**Comment by allison0034** [comment]
Optional tasks

One of the best ways to experience VA.gov as a Veteran is to complete common tasks. We have defined tasks for each area on VA.gov. If you see one that you would like to try you can visit staging.va.gov. Some tasks will need a login ID with specific criteria.

**Comment by shiragoodman** [comment]
in conversation with the Testing Tools Team, the preferred method for sharing staging logins would be the use of TUD - Testing User Dashboard. There are some concerns with TUD and it's current status:

1. TUD has not been released. Anticipated release date is 1-2 sprints (mid December?)
2. TUD will require SOX access. This is a concern because not all VFS team members will have SOX access. This could mean that not all VFS team members will be able to execute the test user scenarios as part of orientation.

Because of this, the team has decided to de-prioritize this work until more is known about TUD. Instead, the team will prioritize the other VA.gov Overview work - adding a VA.gov overview video to orientation materials.
