### ISSUE TITLE
Content and PDF additions to NADL and home loan pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32623]
## Issue Description
Stakeholder Raleigh Contreras asked us to update a few housing pages with new information and links. 

1. Add text along with a link to a new infographic PDF on the NADL page. 

PDF: https://benefits.va.gov/homeloans/documents/docs/NADL_infographic.pdf

Page to add to: 
https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/

2. Add text and a link to a new Veteran Home Loan Guaranty Buyer's Guide to 2 pages. 

PDF: 
https://benefits.va.gov/HOMELOANS/documents/docs/VA_Buyers_Guide.pdf

Pages to add to: 
https://www.va.gov/housing-assistance/ 
https://www.va.gov/housing-assistance/home-loans/loan-types/purchase-loan/

Text suggested: 
Download the Veteran Home Loan Guaranty Buyer’s Guide
Learn how to use the VA-backed home loan to purchase your home—and find out helpful tips for before and after you close on your next loan.

Background from Raleigh: Intent is to direct borrowers to the all-encompassing guide so they have all the info they need before they purchase (something that we have never done before). Also, it gives best practices that we would tell them face-to-face so they can see the entire process before they purchase.

We need to review this to determine if these changes should be made and if the changes are on the proper pages and in the correct format. If the changes are warranted, we need to write the content in VA.gov's voice and style and with plain language standards. 

## Tasks
- [ ] Use assessment criteria to determine changes to be made
- [ ] Write new content
- [ ] Edit content
- [ ] Copy edit content
- [ ] Create ticket for final review

## Acceptance Criteria
- [ ] Content changes are assessed and a final draft is ready to go to Beth

**Comment by lunascoop** [comment]
@RLHecht the changes are ready for your review. cc: @lwalsh617 
Disability housing grants for Veterans: http://preview-prod.vfs.va.gov/preview?nodeId=750

For now, I only added the **What if I have more questions?** section to the NADL page until we've finalized the text. 

I also:

- Removed the in text link for the **A low-interest, 30-year fixed mortgage** bullet point and re-added beneath the bullet point
- Added space between links in step 1
- Added phone number to step 2

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Randi, Selina, and I discussed the buyer's guide and are providing you with the notes and recommendations below. If you'd like to discuss on a call, please let us know.

**Notes and Recommendations for Leveraging the VA Home Loan Guaranty Buyer's Guide**

While we appreciate the significant time and effort stakeholders invested in developing the 51-page Buyer's Guide and their desire to have it posted on va.gov, doing so violates our single-source-of-truth standard.

The guide duplicates much of our tier 1 content. Posting it sets a precedent of inclusion of similar materials by other stakeholders and could lead to an undoing of one of the primary goals of va.gov--to have a single source for accurate benefits information.  

A better use of the guide is to:

- **Create R&S articles based on its content\
**For example, the guide was used as one of the sources in the following R&S articles waiting for SME review:**\
**Entitlement: <http://preview-prod.vfs.va.gov/preview?nodeId=35297>\
VA owned properties: <http://preview-prod.vfs.va.gov/preview?nodeId=35305>\
Appraisals: <http://preview-prod.vfs.va.gov/preview?nodeId=35308>\
VA approved condos: <http://preview-prod.vfs.va.gov/preview?nodeId=35316>

- **Consider creating a new R&S article that mimics the purpose of the guide without duplicating content.**\
The purpose of the guide is defined by stakeholders as giving users the "*info they need before they purchase (something that we have never done before). Also, it gives best practices that we would tell them face-to-face so they can see the entire process before they purchase.*"\
We could create an R&S article that provides users an overview of the home-buying process with links to more detailed content.

- **Review our tier 1 pages against it.**\
For example, there may be value in explaining up front the difference between a guaranty (how most Veterans use the benefit) versus a direct loan (limited to NADL) higher up on the tier 1 pages than we currently do. The user guide refers to this earlier and may be something we want to adopt.

If, as a short-term solution, we do choose to include the guide on VA.gov, we should first review it (ensuring all links are correct and that it doesn't contradict va.gov content). We could then include it on spoke pages where we list additional resources, including:

- Under **Get more information** on https://www.va.gov/housing-assistance/home-loans/eligibility/

- Under **What if I have questions about the loan process** on https://www.va.gov/housing-assistance/home-loans/how-to-apply/

- Under **Visit these online resources** on https://www.va.gov/housing-assistance/home-loans/home-buying-process/

Proposed copy:\
Download the VA Home Loan Guaranty Buyer's Guide (PDF)

**Comment by lunascoop** [comment]
@bethpottsVADEPO For the NADL page, most of the info in the PDF is already on the page. So we decided not to include a link to the PDF, and just add the missing info to the page instead. Here's what we added:

- Under the **Why might I want to get an NADL?** section, a bullet point about the ability to refinance a current NADL
- **What if I have more questions?** section at the bottom of the page that includes the phone number and link to Find your regional VA loan center (we also recommend to add this section to the other loan type pages (Purchase loan, cash-out refinance loan, and Interest rate reduction refinance loan pages))
- Phone number info to step 2

We also changed:

- The in-text link for the **A low-interest, 30-year fixed mortgage** bullet point to a link on a separate line
- The spacing in between the links in step 1

Disability housing grants for Veterans: http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop @lwalsh617 Thanks for this summary! I'll take a look.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop @lwalsh617  
For the NADL page, the messaging you added in 2 places to “call your VA regional loan center” provides the general loan guaranty service phone number. I called that phone number and there's no mention of "regional loan centers"--there's no option to press for this topic. It isn’t accurate to provide that as a way to reach a regional loan center. In fact, there isn’t a phone number to call at any of the regional loan centers—instead they each have an email address (plus physical and mailing addresses) as methods of contact. Any messaging around the phone number should be to the effect of “you can talk to a VA home loan representative.” 

Let's do this:

- In drupal, revert back to what was there before in No. 2 of the subway map.
- Change the first sentence under "What if I have more questions?" to:
"If you have questions, you can call us at 877-827-3702 to talk to a VA home loan representative."
- Then after the hours of operation, on a new line:
"You can also contact your regional loan center directly.
[Find your VA regional loan center]"

Can you update your checklists so that this kind of thing gets caught in the future? 

For the buyer's guide, I agree that we shouldn't be linking to it from VA.gov. We shouldn't be driving the user off our site to a PDF. It should be the other way around. The PDF should drive the user to VA.gov.

@RLHecht since you're already in touch with Raleigh, would you draft a response that explains that to align with our digital modernization principles, we want to have a single source of truth for Veterans. Since we already have most of the information for NADL on the VA.gov page, we'd like to keep the user on the website and simply add a bullet point about refinancing (as that's missing info currently) as well as adding a Q&A at the bottom that would provide the phone number to call for help. You may want to include a screen shot to show these additions. 

The brochure is a similar response: we don't want to drive the user off the site if we can provide the same information with our VA.gov content. And we have articles in progress to cover the information in the brochure. Those are the articles Laura Walsh sent you for review. We can add to those articles if there's anything missing. 

Just ping me with your drafted response and I'll see if I have anything to add. Let's have the response come from you, and I'll get involved if I need to. Thanks!

**Comment by lunascoop** [comment]
@bethpottsVADEPO @RLHecht I've updated the NADL page with the change to the phone number content. I recommend we also change the phone number content on the [How to apply for a VA home loan Certificate of Eligibility](https://www.va.gov/housing-assistance/home-loans/how-to-apply/) and add the **What if I have more questions** section to the other loan type pages.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Yes, please change the content on How to apply. Thanks! We'll have to wait to publish until we hear back from the SME.

**Comment by lunascoop** [comment]
Updated the content on the How to apply for a VA home loan Certificate of Eligibility page. 
http://preview-prod.vfs.va.gov/preview?nodeId=754

**Comment by RLHecht** [comment]
Update: Waiting on response from Raleigh
