### ISSUE TITLE
Remove old 'signup` route

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#32633]
The `vets-api` routing for new account signups has been changed to accommodate both Login.gov & ID.me signups (ticket #32399). Now that the change has gone through the original `signup` route handling can safely be removed. This is tech debt, no change should be apparent for the end user.

---
## Tasks
- [x] Remove the `signup` route & SSO URL generation logic
- [x] Remove/refactor any affected unit tests

## Acceptance Criteria
- [x] A user can sign up for a new Login.gov account through the `logingov_signup` route
- [x] A user can sign up for a new ID.me account through the `idme_signup` route
