### ISSUE TITLE
GIBCT Analytics - Add Analytics - Profile Page

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#32631]
## Issue Description
OCTO reported the GIBCT Redesign is missing critical Google Analytics. After conducting thorough analysis and collaboration with the OCTO team it was determined by OCTO GIBCT Redesign cannot be released to production without Google Analytics.

This story is to add Analytics to the Profile Page.

---
## Tasks
- [ ]  Add GA analytics calls to various points on profile page to trigger necessary events

## Acceptance Criteria
- [ ] GA analytics reporting if users open warning panel to view more information for schools with cautionary warnings.
- [ ] GA analytics reporting if users visit profiles for schools with cautionary warning.
- [ ] GA analytics reportingUser engages with "On this page" jumplinks
- [ ] GA analytics reporting which"Learn more" links were selected.
- [ ] GA analytics reporting if user clicks school's website
- [ ] GA analytics reporting if user engages with Calculate your benefits accordions
    - [ ] Which benefits?
    - [ ] Which adjustments?
- [ ] GA analytics reporting if user engages with content links in Apply for benefits section
- [ ] GA analytics reporting if user engages with "Submit a compliant through our Feedback System"
- [ ] GA analytics reporting if user engages with links to other schools in School locations section
- [ ] GA analytics reporting if user engages with "Back to top" element
- [ ] GA analytics reporting if user exits to About this tool page
- [ ] GA analytics reporting if user downloads data on all schools (Excel download)

---
## How to configure this issue
- [ ] **Labeled with Team** (`afs-edu-comparisontoolp)
- [ ] **Labeled with Practice Area** (`frontend`)
- [ ] **Labeled with Type** (`discovery`)

**Comment by hallihocine** [comment]
Ticket has been validated in staging
Process: Triggered events via UI then validated using ObservePoint TagDebugger chrome extension

**Comment by hallihocine** [comment]
### **Screenshots**

-  GA triggered and reporting if users visit profiles for schools with cautionary warning
<img width="888" alt="Profile link clicked" src="https://user-images.githubusercontent.com/86266024/142458711-7a735c2d-0777-4bb4-a4db-003c65f65822.png">

- GA event triggered and reporting if users open warning panel to view more information for schools with cautionary warnings
<img width="864" alt="Cautionary warning opened" src="https://user-images.githubusercontent.com/86266024/142458859-c4503083-7de9-4667-9609-6a26cd2c1918.png">

- GA triggered and reporting when user engages with "On this page" jumplinks
<img width="877" alt="Jumplink clicked" src="https://user-images.githubusercontent.com/86266024/142459002-2e8bfcb4-a541-48b1-8126-2e80e3ec48fc.png">
<img width="880" alt="Jumplink1" src="https://user-images.githubusercontent.com/86266024/142459151-69cdda05-d879-4df1-b942-18e21596b3fd.png">
<img width="858" alt="Jumplink2" src="https://user-images.githubusercontent.com/86266024/142459171-d0191cf6-8a93-4320-a991-969ec821d0cc.png">
<img width="881" alt="Jumplink3" src="https://user-images.githubusercontent.com/86266024/142459193-a548f7d0-090a-479e-98d1-33d5adcdfa2e.png">
<img width="882" alt="Jumplink4" src="https://user-images.githubusercontent.com/86266024/142459214-53d84f78-c9b5-4dca-9a84-b613e1a1b9e5.png">
<img width="861" alt="jumplink5" src="https://user-images.githubusercontent.com/86266024/142459233-aa15f63d-ac07-42f3-99b7-2944714728ef.png">

- GA event triggered and reporting which"Learn more" links were selected (below some of the Learn more links)
<img width="872" alt="Learn more clicked" src="https://user-images.githubusercontent.com/86266024/142459467-57bc8394-6d75-4642-934a-b773024d90c4.png">
<img width="853" alt="Learn more link 1" src="https://user-images.githubusercontent.com/86266024/142459488-f0432b06-e95e-49d5-ba46-b20ca1131946.png">
<img width="842" alt="Learn more link 2" src="https://user-images.githubusercontent.com/86266024/142459506-226d7aa7-05ec-4a52-af89-37791a10299c.png">
<img width="839" alt="learn more link3" src="https://user-images.githubusercontent.com/86266024/142459541-a32d6dfe-c268-446d-bac6-ec30be28cb7b.png">
<img width="855" alt="learn more link4" src="https://user-images.githubusercontent.com/86266024/142459570-b60688d8-8086-484d-953b-e1578a25ef79.png">
<img width="866" alt="learn more link5" src="https://user-images.githubusercontent.com/86266024/142459612-204dbacd-a3b7-4852-8170-244d7a4fa0cf.png">

- GA event triggered and reporting if user clicks school's website
<img width="894" alt="School website clicked" src="https://user-images.githubusercontent.com/86266024/142459877-3ed3cc26-c024-4421-b5c7-f8a9b50f8a03.png">

- GA event triggered and reporting if user engages with Calculate your benefits accordions:

1.  Which benefits?
<img width="838" alt="Section Updated" src="https://user-images.githubusercontent.com/86266024/142460310-e3cbb8d6-f8c5-44a3-81c9-d6e11b1ec27a.png">
2. Which adjustments?
<img width="846" alt="Section Updated2" src="https://user-images.githubusercontent.com/86266024/142460437-0cf9e229-b840-47d2-b550-09576e79ed91.png">

-  GA event triggered and reporting if user engages with content links in Apply for benefits section
<img width="868" alt="Apply Benefit clicked" src="https://user-images.githubusercontent.com/86266024/142460561-6827b448-41e9-4bc3-a14e-4b6fe2c5c6f7.png">

-  GA event triggered and reporting if user engages with "Submit a compliant through our Feedback System"
<img width="882" alt="Feedback link clicked" src="https://user-images.githubusercontent.com/86266024/142460686-7f770e2a-4a2a-48ac-a786-3d438051ceb0.png">

-  GA analytics reporting if user engages with links to other schools in School locations section
1. View all link:
<img width="883" alt="View all clicked" src="https://user-images.githubusercontent.com/86266024/142460866-046ef805-e780-477a-8ea2-93ded6709c90.png">
2. View less link: 
<img width="885" alt="View less clicked" src="https://user-images.githubusercontent.com/86266024/142460979-5e07d266-ebf5-4f7e-8579-7d1ac2bdebf5.png">

- GA event triggered and reporting if user engages with "Back to top" element
<img width="863" alt="BockToTop clicked" src="https://user-images.githubusercontent.com/86266024/142461134-7aaba88c-cf0b-46ef-a9be-76134072e42a.png">

- GA event triggered and reporting if user exits to About this tool page
<img width="878" alt="About this link clicked" src="https://user-images.githubusercontent.com/86266024/142461276-6d98ee64-d649-4772-95a9-d53b23cdf4c0.png">

- GA event triggered and reporting if user downloads data on all schools (Excel download)
<img width="882" alt="SchoolData link clicked" src="https://user-images.githubusercontent.com/86266024/142461451-9b8be4d7-34c8-4562-b295-85b1cc8c99e2.png">

**Comment by hallihocine** [comment]
- Test run in TestRail:
https://dsvavsp.testrail.io/index.php?/runs/view/2584&group_by=cases:section_id&group_order=asc&group_id=2922

- Test Script/Steps: 
[GIBCT Analytics - Add Analytics - Profile Page.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7564598/GIBCT.Analytics.-.Add.Analytics.-.Profile.Page.xlsx)
