### ISSUE TITLE
[HOLD] Release Support Issue DOMO Dashboard for General Use

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#32637]
## Issue Description
_After a 2 month pilot with 4 platform teams we want to release the Salesforce support issues dashboard in for general use in DOMO_

---
## Tasks
- [x] _Share the (Salesforce) support issue dashboard in DOMO with all platform teams_
- [x] _Communicate new access for platform teams in #vfs-all-teams Slack channel_
- [x] _Link to `How-To` documentation and explain purpose of dashboard_

## Acceptance Criteria
- [x] _Dashboard is shared with all platform teams_
- [x] _Communication about new dashboard access is published in slack_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
We are postponing this release for additional support issue reporting strategy discussion with the analytics team.
