### ISSUE TITLE
Pilot Medallia Dashboard in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#32638]
## Issue Description
_After initial MVP  reviews and discussions with internal teams and VA leadership, we want to pilot this dashboard with several platform teams to gain additional insight and general feedback for enhancements_

---
## Tasks
- [ ] _Communicate with prospective pilot teams/users about the dashboard, intent, and our goals of the pilot_
- [ ] _Share access to the dashboard with selected team_
- [ ] _Communicate follow-up timeline and communication channels

## Acceptance Criteria
- [ ] _Pilot teams/users have a clear understanding of the pilot goals_
- [ ] _Pilot teams/users have access to the dashboard_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
