### ISSUE TITLE
Support Issue Reporting Strategy

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#32639]
## Issue Description
_As general reporting strategy discussions have occurred, the seems to be a need to define our optimal strategy with data versus rushing to release a general dashboard, which we may end up taking away in favor of including more product specific data in product dashboards in DOMO_

---
## Tasks
- [ ] _Meet with the Analytics team and VA leadership to discuss and document strategy_

## Acceptance Criteria
- [ ] _Initial support reporting strategy is discussed and documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
The decision to update the DOMO dashboard to reflect current product status ticket # 76582
