### ISSUE TITLE
[VAMC] Provide carousel images for the remaining 59 Systems on schedule to redirect to Full Production by December 15th [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#32651]
##  Resources
images need to be scaled to 340 x 210 7.0 pixels

## Tasks
- [ ] Capture images from new VAMC websites in dual state that can be used in carousel image, block 2
- [ ] Scale image to sizes above to meet TeamSite requirements

## Acceptance criteria
- [ ] one image is provided to VHA DM for each system remaining on schedule for Full Production.
