### ISSUE TITLE
Midpoint Review Decision Tools: Find a VA Form - PDF Download Instructions

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32650]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Schedule meeting with Collaboration Cycle reviewers and VFS team attendees listed in the ticket. 
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [X] Yes*
- [ ] No

*If yes, please include any relevant content artifacts.
- #30675
- #31832 <-- [final copy found near the end of this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574)

## Artifacts

Provide links or documents for the following: 

- [x] Product outline
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md#find-a-va-form-pdf-download-instructions
 
- [x] Finalized design prototype or mockup  [Sketch](https://www.sketch.com/s/6e7784a1-5b01-4aec-9ec7-4bbf788d08fa) | [PNG](https://user-images.githubusercontent.com/68560244/140093362-5180a9d1-58ae-496f-b824-58c79655505c.png)
- [X] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-plan.md) 
- [X] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/conversation-guide.md) 
- [X] [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/post-mvp-releases/research/research-findings.md)

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- #30675
- #31832 <-- [final copy found near the end of this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31832#issuecomment-954287574)
- Staging links: 
  - https://staging.va.gov/find-forms/?q=10-10ez
  - https://www.va.gov/find-forms/about-form-10-10ez/ - note that you will need to clear cookies to see the modal if you already viewed it within the past 24 hours.
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

_Please note that you must navigate directly to a form detail page for testing the modal.  If you search for a form and then click its detail page link in Staging, it goes to the detail page on Production._

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRail Product)
- [ ] [VSA-QA Test Plan](#31725)
- [X] Link to test cases/test plan in TestRail (draft OK)    https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=824
 - [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md) [S-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-f), [S-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-s-g), [D-F](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-f) and [D-G](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md#use-case-d-g) have been added
 - - Staging links: 
  - https://staging.va.gov/find-forms/?q=10-10ez
  - https://www.va.gov/find-forms/about-form-10-10ez/ - note that you will need to clear cookies to see the modal if you already viewed it within the past 24 hours.

 

### Required* 
\*Only required for synchronous meetings.
- Product Manager:  Marci McGuire, Linda Li (New PM)
- OCTO-DE Product lead: Dave Conlon
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Zach Morel, Sam Suddath (New FE Engineer)
- Cassandra Allen
- Randi Hecht 

### VFS Attendees

- Content and IA: Beth Potts, Peggy Gannon, Jim Ryan
- Accessibility: Josh Kim, Angela Fowler
- QA specialists: Tze-chiu Lei

## Scheduling
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [X] No

**11/16/2021** **11:00 AM ET**

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO Midpoint review scheduled for 11/16 at 11:00am ET

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by allison0034** [comment]
Hi @callen2563, can you show a screen in mobile view with the approved copy please? Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@allison0034

In case @Cassandra is OOO, this is a mobile screenshot from Staging.

![image](https://user-images.githubusercontent.com/73354907/141497365-d5f09a51-9441-48ca-ba8b-bbdf32a17006.png)

**Comment by peggygannon** [comment]
Hello, @MarciMcGuireGCIO 

My only feedback is to remove the word "just" from the last line. So it would read:  If you want to fill out a paper copy, open the PDF in your browser and print it from there.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @peggygannon!

**Comment by MarciMcGuireGCIO** [comment]
@pjhill good catch; thanks! I just updated the link to point to our current test cases in Test Rail, and I've been in contact with Tze and created a request for a test plan.

**Comment by pjhill** [comment]
> @pjhill good catch; thanks! I just updated the link to point to our current test cases in Test Rail, and I've been in contact with Tze and created a request for a test plan.

Great, thanks very much!

**Comment by joshkimux** [comment]
A11y feedback:

- Aim for consistency between download button vs. link styling in the list vs. the modal. Typically, [modals are opened by `buttons`](https://design.va.gov/components/modal) and [pdf downloads are done using links](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download). Effectively, that would mean the modal's download button styling and the list's download link styling should be swapped. That being said, I know there may be some visual challenges with working that out.
-  Consider including file type (e.g. PDF), download size (e.g. 471kb),  and a date/version (if relevant so users know they have the most recent copy) in the actual download text e.g. Download VA Form 10-10EZ (PDF, 471 KB, 2018)

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @joshkimux!   Some background on the link - we settled on that for a couple of reasons -  First, a button doesn't provide right-click, which is required is some browsers in order to download a PDF vs opening it in the browser.   Second, in this particular case, the modal will only appear once in 24 hours (unless the user clears their cookies).   Any other time someone clicks the link, it will download the PDF.    I hope that helps!

Regarding the addition of file type and download size, that is a good recommendation, and we can add that to the backlog as a future enhancement.

**Comment by jimuhh** [comment]
No additional feedback from IA. 
Thanks for answering my questions, @MarciMcGuireGCIO.  You've given me a  better understanding of the project constraints. I think 'the gizmo' delivers the best feasible solution in light of those.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @jimuhh !
