### ISSUE TITLE
R&S Education Crosslinks

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#32669]
**ISSUE**

As we publish more education articles to R&S, we should review current pages to see if newly published crosslinks should be added. Going forward, this will be part of the publishing process for each article. Therefore, this review includes a limited number of pages. 

**TASKS**

- [x] SC to create list of recommendations (LAURA) (See table provided in Slack.)

- [x] SC to review recommendations and approve/not approve (RANDI)

- [x] SC to make approved edits in Drupal  (LAURA)
 
- [x] SC to proof edits and publish (RANDI)

- [ ] SC to created new ticket for DEPO review and close this ticket (LAURA)

**CROSSLINK ADDITIONS TO EDUCATION PAGES**
See table provided in Slack.

**Comment by RLHecht** [comment]
@lwalsh617 Let me know if this works. [rs-linkupdates-04nov2021.xls](https://github.com/department-of-veterans-affairs/va.gov-team/files/7508120/rs-linkupdates-04nov2021.xls)

**Comment by lwalsh617** [comment]
@RLHecht -- ^ That did it! Thank you.

**Comment by RLHecht** [comment]
@lwalsh617 I made comments in the spreadsheet for the pages you had so far. I think there is only one update. Slacked it to you since I keep having issues trying to upload it here.

**Comment by RLHecht** [comment]
I've reviewed all the articles in the spreadsheet and added related links to a few. I think we can close out this ticket now.
