### ISSUE TITLE
Bug: Login.gov SVG is missing

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#32661]
## Issue Description
The SVG for Login.gov is not displaying because of an issue with the S3 bucket issue linking to the **Dev** environment. [Original Slack thread here](https://dsva.slack.com/archives/CBU0KDSB1/p1636477995478700).

---
## Tasks
- [x] Create an inlined version of the SVG so there are no gaps in relative vs absolute paths
- [x] Ensure the SignInButtons & VerifyApp Login.gov changed

## Acceptance Criteria
- [ ] I can see the Login.gov SVG in the Dev environment on SignInButtons
- [ ] I can see the Login.gov SVG in the Dev environment on VerifyApp
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
