### ISSUE TITLE
[Reverse Proxy / EKS] Get a revproxy running in EKS DEV cluster for testing network configuration

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32664]
## Description
In order to be able to test networking configurations for the reverse proxy ("revproxy") in EKS without modifying existing environments, we need to bring up a testing version of the application in the EKS development cluster. 

## Background / Context
There is a test/development revproxy deployment running in the utility cluster that should be cleaned up. Although that task is technically distinct from the specific implementation outlined in this issue, that instance was deployed manually during the development of the proof of concept (POC) deployment for this service. 

## Technical notes
[Repo](https://github.com/department-of-veterans-affairs/vsp-infra-revproxy) that builds the revproxy container and pushes to ECR
[POC application manifest](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/revproxy/dev) that deploys the app through ArgoCD _(note: currently set up for dev, manually added to utility cluster, so needs to be removed and added via IaC)_
Example [Traefik ingress route](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/grafana/templates/ingressroute.yaml)

---
## Tasks
- [x] Remove the revproxy instance running in the EKS utility cluster
- [x] Add POC application manifest to [ArgoCD "app of apps"](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/argocd-apps/dev/main.jsonnet)
- [x] Add Traefik ingress route that points to the service to the manifest "dev.va.gov" & "dev-api.va.gov" _(note: see example in technical notes, above)_

## Acceptance Criteria 
- [x] Revproxy is running in EKS DEV cluster w/ working ingress route for testing purposes 
_Note: in theory, this should enable us to cURL w/ a custom header (or similar) to validate the networking configuration of revproxy behind Traefik_

**Comment by jsgarmon** [comment]
The revproxy service is up in EKS dev cluster, and we are able to hit this service with `curl -vLH "revproxy-eks: true" dev-api.va.gov`.

However, currently the request gets caught in a redirect loop, as it keeps hitting a 301 and redirecting back to itself. This proves we're able to access the revproxy service in EKS, but that service needs some work.

Closing this ticket with the understanding that another one will be opened to fix the redirect issue in revproxy.
