### ISSUE TITLE
Update VCL modal to match red in design system 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32672]
## Issue Description
_It was identified during the build of the new mobile header that the VCL color was not set to match that in the design system.  We want to make an update to match all approved styling for all desktop, tablet and mobile users._

## Tasks 
- [ ] Change the red on production for VCL to `vads-u-background-color--secondary-darkest | #981b1e`

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Product VCL is rendering as intended and matches all style types for desktop, tablet and mobile. 
- [ ] Close ticket once completed

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/741

**Comment by kelsonic** [comment]
Merged, will go out with the daily deploy today
