### ISSUE TITLE
Urgent Care PDF MVP (development)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3268]
**This issue represents one area of the urgent care redesign (MVP)**

## User Story:
- As a Veteran, I need to understand how to access my urgent care benefits so that I can receive care without out of pocket cost.
- As a Veteran, I need access to the benefit PDF so that I can print it in preparation for my urgent care visit.
- As a Veteran, I need access to the benefit PDF so that I can send it to my mobile device in preparation for my urgent care visit.

## Objectives or Key Results this is meant to further
- Improve the Veteran Search Experience (Veterans have the information they need to be prepared for an urgent care visit. )
- Community Care Implementation

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Make PDF downloadable **-x hours**
- [ ] Get facility IDs to call for PDF **- y hours**
   (time estimates to be added once design work in [#4325] is complete)

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Eligibility PDF is present in the urgent care search workflow. 
- [ ] PDF is available for download by the Veteran user. 
- [ ] Veterans using assistive technology can access and download the PDF. 

** This to be completed once wire frames are available** 
[ ] Benefit PDF
[ ] Text to accompany PDF
[ ] Location and method for PDF
[ ] Relevant design details for font, size, color, etc.
[ ] Description of page/modal/component flow
WIP: Need to outline expectations for display for all other facility type search results

**Comment by davidconlon** [comment]
TriWest solves this problem with providing Veterans a PDF with three pages: one for the veteran, one for the urgent care facility, and one for the urgent care pharmacy. (https://www.triwest.com/globalassets/documents/urgent-care/va_urgent_care_tips.pdf)

The TriWest form serves a few purposes:
1. Provides information to Veteran to understand his/her eligibility as well as a phone number to confirm eligibility ("preparing for your visit" sorta stuff) and a phone number in case the veteran has problems.
2. Provides information the the facility to streamline their processes for validating eligibility as well as understanding what the facility needs to do to provide care (e.g. billing, etc). While not veteran focused this (arguably) helps the veteran from being asked questions for which he or she may not have answers. (e.g. billing, mailing, codes etc).  the facility may not be familiar with Mission Act eligibility or their role in it and this speeds the veteran's care at the facility.

We need to understand what the implications are for the Optum facilities when they roll in.

**Comment by davidconlon** [comment]
To add to this, what's MVP and then should we consider some sort of widget that validates an individual veteran's eligibility (auth exp) to say "yes" "no" "maybe"?

**Comment by davidconlon** [comment]
This is blocked until we receive the actual form, but we should think about how we can move this forward as it's critical for the Optum stuff

**Comment by mmiddaugh** [comment]
Will need working workflow with some user feedback
Will need facility IDs for calling PDF (since this is limited to urgent care/community care facilities)
Blocked until final PDF received from Community Care
Blocked pending sign-off from Community Care

Will estimate front end when design is available

**Comment by mmiddaugh** [comment]
**Draft** PDFs available in Drive
https://drive.google.com/file/d/0B7mn2NjHFhwNRGswMmhWTEpLREFMT0lQOHZVWHRvb1F5d2lj/view?usp=sharing

https://drive.google.com/file/d/0B7mn2NjHFhwNeExjSkJQZlNXd3FkQ2N2LXBDZGxRZ3NyZklJ/view?usp=sharing

Note: one is "generic" (TriWest _and_ Optum while the other is TriWest specifically

**Comment by davidconlon** [comment]
@mmiddaugh can you store the PDFs in the issue? Can't access Google drive from GFE

**Comment by mmiddaugh** [comment]
[DRAFT Urgent Care Printable Document_102319.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3995591/DRAFT.Urgent.Care.Printable.Document_102319.docx)

[DRAFT Urgent_Care_Printable_Document_102319_TW_Only_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3995592/DRAFT.Urgent_Care_Printable_Document_102319_TW_Only_v3.docx)

@davidconlon files are attached.

**Comment by davidconlon** [comment]
Updated version of PDF (as of 1/6/2020) attached

[https://app.zenhub.com/files/133843125/29c78cf4-1b29-4b39-8a76-1eefa5356f82/download](https://app.zenhub.com/files/133843125/29c78cf4-1b29-4b39-8a76-1eefa5356f82/download)

**Comment by mmiddaugh** [comment]
Moving the acceptance criteria for this into [#4924] and closing this issue.
