### ISSUE TITLE
Collaboration Cycle - Transition VFS research review/approval activities to Platform

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32698]
## Problem Statement
VFS teams need guidance on how to properly conduct user research and the person currently upholding VA's research requirements is stepping out of her role so Platform needs to figure out how to fill that gap.

How might we seamlessly transition OCTO-DE research responsibilities to Platform without inconveniencing or disturbing the other parties involved in the research?

## Background
VFS Research for VA.gov products and services has historically included 3 primary players - the VFS team performing the research, OCTO-DE, and the Research Ops contractor (currently Perigean). The responsibilities of the OCTO-DE individuals in the current VFS Research process has been very time consuming and demanding. OCTO-DE would like to offload some of their current roles and tasks to Platform so that they have more bandwidth to support other VA.gov activities.

[VFS Research Process MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1644952499693/c2cdabd1a5e3c290b80f56cf75a2aca0251f97b5?sender=u0574179b1d97118ccc0e3591)

## Hypothesis or Bet
If we have a dedicated UX Researcher supporting VFS research initiatives, then VFS teams will be able to complete research initiatives with ease and with minimal support from OCTO-DE.

If we have a dedicated UX Researcher supporting VFS research initiatives, then VFS teams will be able to more consistently and efficiently complete research initiatives.

If we have a dedicated UX Researcher supporting VFS research initiatives, then OCTO-DE researchers are able to focus their time elsewhere and may have more bandwidth.

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

- [x] Platform is able to review research plans and conversation guides
- [x] Platform is able to request changes to the research plan and/or conversation guides
- [x] Platform knows how to escalate concerns with OCTO-DE related to VFS research
- [x] Platform is able to grant approval of research artifacts
- [x] Platform is able to kickoff participant recruitment
- [x] Research as a practice area has been integrated into the relevant Collaboration Cycle touchpoints
- [x] Platform has operational guidance/documentation for supporting the Research Plan Review CC touchpoint

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
March 31, 2022

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by shiragoodman** [comment]
Talking points for 1/24 internal meeting:

- Define tasks, AC, and timeline for ticket #35792
- Update MURAL board for Shane's new research review process
- Links in Research & Design of Platform Website referencing Collaboration Cycle should be looked at as they may be referencing the wrong url/page
- Question for Shane/Kevin: Does the [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) require any updated? Last updated by Lauren Alexanderson in October 2021. What about the [conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)?
- In the [Planning for your research/Prepare your prototype or mockup guidance
](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-1.Planningforresearch), Collaboration Cycle is referenced, however I'm not sure this is in alignment with our current process.

**Comment by shiragoodman** [comment]
@naomimarcussen @allison0034 @claytonzook 
1. Share research review standards document drafted by Lauren
2. Question for Shane/Kevin: Does the Research Plan Template require any updated? Last updated by Lauren Alexanderson in October 2021. What about the conversation guide template?
3. timeline in mind for meeting this acceptance criteria: "Clayton know how to review research plans and conversation guides, knows how to request changes and escalate when necessary, can complete this process on his own and has the full trust of Shane and Kevin."

**Comment by claytonzook** [comment]
1. Document was shared with Naomi and Clayton during meeting with Shane and Kevin 24 Jan - Naomi and Clayton discussed that Clayton should capture important guidance from these slides into a Confluence document.
2. Research templates do not require updating at this time. We may in the future want to add additional guidance or details.
3. Mid-February is the timeline for meeting acceptance criteria described.

**Comment by shiragoodman** [comment]
@claytonzook are you able to share the research review standards doc? Can you link it here?

**Comment by claytonzook** [comment]
Link to the slide deck created by Lauren >> https://dsva.slack.com/files/UHZ9VNBH8/F02VAD77ZDK/reseach_process.pptx

**Comment by chaseakirby** [comment]
There is guidance for logging research into repo but no guidance on performing research aside from templates.
Clayton and Naomi discussed pulling items out of slide deck if possible.

**Comment by claytonzook** [comment]
> Link Edited: https://docs.google.com/presentation/d/12kiliMtHS0EJcmDmJVOrGnUwGZ68-Kvc/edit?usp=sharing&ouid=111310371236275909597&rtpof=true&sd=true

Link for my condensed version of this deck, including a few notes/comments 
https://vfs.atlassian.net/wiki/spaces/~76599512/pages/2065858561/Notes+Folding+Research+Review+into+CC

**Comment by shiragoodman** [comment]
> > Link Edited: https://docs.google.com/presentation/d/12kiliMtHS0EJcmDmJVOrGnUwGZ68-Kvc/edit?usp=sharing&ouid=111310371236275909597&rtpof=true&sd=true
> 
> Link for my condensed version of this deck, including a few notes/comments https://vfs.atlassian.net/wiki/spaces/~76599512/pages/2065858561/Notes+Folding+Research+Review+into+CC

@claytonzook thank you for taking the initiative to convert the deck into a Confluence page. I am going to create a ticket for getting this page cleaned up, and stored in the right place. I'll tag you and you can review/modify.

**Comment by claytonzook** [comment]
> There is guidance for logging research into repo but no guidance on performing research aside from templates. Clayton and Naomi discussed pulling items out of slide deck if possible. Shane and Kevin created mail drop. Switching from slack to email for queue. Clayton may have to wait for VA email. Clayton and Naomi still discussing email versus issue tickets.

Update on this - I found out yesterday that email dropbox is only for teams outside of VSP/VFS or who don't have access to the VA github. A VA admin converts those email requests to tickets on the research repo. Also our teams should now be making their own tickets on the research repo vs initiating a review in slack.

**Comment by shiragoodman** [comment]
@claytonzook @chaseakirby I am closing this initiative out - thank you both!
