### ISSUE TITLE
[FE] Creating the routing for Pre-check-in

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#32693]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Add all the pages to the router. This should be set up in a dynamic way to accommodate a dynamic form. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Added the p[ages as empty components 
- [ ] Add the pages to the router dynamically 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
