### ISSUE TITLE
Decision Log - I18N Base Library

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#32696]
## Description

Create decision Log to compare the various solutions for JavaScript I18N and choose the right one to use for va.gov.

## Story
As an engineer I would like to know the pros and cons of each internationalization library so that I may decide which library is best to use and what integrations are available for each.

## Tasks

- [x] Create document for decision log and document the following libraries: i18next, globalize, polyglot.js, and format.js
- [x] Provide links, statistics, and other data to inform decision
- [x] Document the pros and cons of each library, update frequency, FE integrations, and other notable features
- [x] Propose Solution

## Acceptance Criteria

- [x] Decision log uploaded to repo
- [x] Proposed solution documented

**Comment by adamwhitlock1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/development/Decision-Log-I18N-JS-Libraries.md
