### ISSUE TITLE
[AWS / IAM] Set permission boundary around accounts for @td-usds and @gary-fallon

### ISSUE THREAD

**Issue by td-usds** [department-of-veterans-affairs/va.gov-team#32699]
## Description
Currently, both Gary Fallon @gary-fallon and  Thomas D(@td-usds) have broad privileges in AWS; whereas there is only a need for read-only. Set a permission boundary around the accounts that limit actions read-only operations (GET, HEAD, ...) and prohibits writes. 

## Background/context 
Gary and Thomas were granted `vsp-operations` but that gives said broad privileges - which aren't needed. 

## Technical notes
Both AWS accounts should be put inside a permission boundary that allows read-only. While there is a need to be able to _read_ everything,  there is not a need _change_ anything. 

This is a good opportunity to investigate the broader use of permissions as well -- _Note: see_ [[Access Management] Document and discuss how IAM Groups/Roles/Policies can be managed more effectively](https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/32435)

---
## Tasks
- [ ] Create permission boundary
- [ ] Put Gary Fallon and Thomas D accounts in it

## Acceptance Criteria 
- [ ] @gary-fallon and @td-usds can inspect anything, but cannot change anything

**Comment by jbritt1** [comment]
@td-usds and @gary-fallon, you guys are now readonly across the AWS account.
