### ISSUE TITLE
[Research] Profile Personal Information Revision: Draft Conversation Guide

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32706]
## Issue Description
Research ticket to draft conversation guide to support Personal Information Revision work.   [Conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

## Tasks 
- [x] Begin drafting conversation guide

## Acceptance Criteria
- [x]  Begin drafting conversation guide and store in our [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/research)
- [x] Share with Samara & Marci
- [x] Incorporate feedback

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO I've also estimated 5 here based on feedback from Liz but feel like this may change as well as I go through the process

**Comment by MarciMcGuireGCIO** [comment]
Note - we may need to create another ticket for completing this work in Sprint 62

**Comment by Samara-Strauss** [comment]
Just a reminder that this is not considered done until I sign off on it, and I need enough time to review it, get feedback to you, have you implement that feedback, and then review again to make sure it's ready. So, please get this to me before the 11th hour tomorrow, or it's not going to be considered done for this sprint.

**Comment by cgednalske** [comment]
@Samara-Strauss Hi Samara - this is ready for review and linked above. There are some TBDs to work out with timeline and participation.

**Comment by Samara-Strauss** [comment]
## Feedback

### Warm-up Questions (Optional) - 2 minutes

- What is your objective with these questions? What are you hoping to learn? It is not clear to me from reading them

### Task 1: General Page Impression (Layout/Terminology) - 3 minutes

- This is very nitpicky feedback, but for "Is there anything else you would expect to see on this page? Is there anything you did not expect to see on this page?", I would modify it to "How does this page meet your expectations? How does this page not meet your expectations?" The former allows for them to give a quick yes/no answer without really thinking about things, while the later forces them to think through a response.
- I see you already have this in the "things to watch out for" section, but I would ask an explicit question about "You can see that some of the fields can be edited, and some can not. Why do you think that is?" in case participants don't mention it.

### Task 2: Initial Navigation / Edit State - 2 minutes

- If it is easier for building the protoype, you can pick in which order they should edit their information.
- "(When Edit State appears) And could you tell me your thoughts on what you see here?" -- This is too vague. What are you trying to assess? How can you be more direct without being leading?
- For all of these, you're going to have to explain that answers have been pre-selected because of limitations to the prototype, so figure out how and where you want to do that so it doesn't derail assessing peoples' understanding.

### Task 3: Remaining Edit States (repeat for remaining states) - 15 minutes 

- Again, if it is easier for building the protoype, you can pick in which order they should edit their information.
- "If different than the field that is next on the page -- And why did you choose to update that field next?" -- why is this important? What are you trying to assess?
- Again, "And could you tell me your thoughts on what you see here?" is too vague. What are you trying to assess? How can you be more direct without being leading?
- You have "And could you tell me your thoughts on what you see here?" listed twice, and it's not clear to me if that is intentional or not. Please remove if it's not intentional, or clarify what you are trying to assess if it is.

### Post-Task Interview - 5 minutes

- "Overall, how did you feel about this experience and what you saw today?" What are you trying to assess with this question? Not that we want to ignore people's feelings, but I don't see this as a helpful follow-up unless someone clearly had strong feelings about what they saw. And in that case, I'd address that in the moment and with proper mirroring (eg. "It seems like you're feeling frustrated. Is that accurate? (If yes) Can you tell me more about that?"
- "Or that you particularly liked?" This is not important. We don't care if someone liked the design or not, just that it worked.
- "Did you notice that some fields could not be edited? What were your thoughts on that?" This is important and should be asked way earlier in testing.
- Same with "Did you notice the FAQs pertaining to the information? What were your thoughts on that?" This should be evaluated way earlier in testing and in the context of whether people understand why we are asking for this information. As part of this, you can/should also assess the FAQ content to see if it clarifies things for people.

### General

- Unless I missed it, I also didn't see any questions around assessing whether the order of information on this page makes sense, so you should figure out where and how to evaluate that.
- I could see this testing being more sensitive than other tests we do if some participants get defensive or uncomfortable around unknown terminology, or if they have particular political views on gender and sexual orientation. You should be prepared to field this, and might want to think through how to manage some different scenarios in case they come up. In most cases, I imagine a simple response like "thank you for letting me know" or "Ok, let's continue and move on to the next task" will probably do in most cases if someone starts to complain about these fields. However, if anyone gets particularly offensive or nasty, I'll leave it up to your discretion to politely end a session early if need be. This is very unlikely to happen, but please do so if necessary.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - Christina has incorporated your feedback and @andaleliz and I have reviewed.  We believe this is ready for you to take another look at.  Thanks!

**Comment by Samara-Strauss** [comment]
### Warm-up questions

I saw you took this section out. Did you determine there was nothing you needed to evaluate here?

### Tasks

After having a chance to review this again, the order of this seems off. You start with the high-level overview questions, but that's not the main objective of this research. The main objective is usability testing, so your research should start with sections 2 & 3 evaluating whether they can find/update their information, and then you can move into a discussion on met expectations/questions/points of confusion. This might also mean that some of the questions in the current first section won't be needed if you move the discussion portion to the end, and that's OK. Please edit accordingly and remove anything that is no longer relevant.

You also had a research objective which I didn't see captured in this convo guide, which was to evaluate whether people expected to find this information in their profile. You might want to start them on a page other than the profile (eg. homepage) and ask where they would expect to find this information. Sometimes we evaluate people's expectations on where to find information on actual VA.gov before moving over to staging, so talk to @andaleliz about what might work if that is indeed one of your objectives.

### Post-Task Interview - 5 minutes

> Have you ever made these kinds of changes anywhere else on line?

What are you hoping to learn with this question?

**Comment by andaleliz** [comment]
> Have you ever made these kinds of changes anywhere else on line?

@Samara-Strauss I added that question, because I'm curious to know if this is something they've done before, would expect to find on a profile somewhere, and where else this might be coming up in their online experiences. Definitely not critical but thought it'd be interesting to find out.

>After having a chance to review this again, the order of this seems off. You start with the high-level overview questions, but that's not the main objective of this research. 

I don't want to speak for Christina, but sharing my two cents - this felt OK to start with because it supports the first and third research objectives about terminology and the order of things. It also serves as a warm up to get people talking and comfortable before jumping into tasks.

>You also had a research objective which I didn't see captured in this convo guide, which was to evaluate whether people expected to find this information in their profile.

I totally missed this, good call! I will chat with Christina about how we can update the prototype/convo guide if we do need to keep it as a research objective. I can't imagine any other place it would live on VA.gov so I'm not sure it's worth testing. In both preferred facilites and notification settings studies, people didn't expect to find those in their profile, but that didn't change our plans to put them there.

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss I added that question, because I'm curious to know if this is something they've done before, would expect to find on a profile somewhere, and where else this might be coming up in their online experiences. Definitely not critical but thought it'd be interesting to find out.

Sounds good. Thanks for letting me know.

> I don't want to speak for Christina, but sharing my two cents - this felt OK to start with because it supports the first and third research objectives about terminology and the order of things. It also serves as a warm up to get people talking and comfortable before jumping into tasks.

OK, so I realize we've started usability testing this way in the past, but I don't know that that was the right approach then or now. Someone on the team pointed this out to me a few months ago -- our usability testing should prioritize tasks first, otherwise we aren't doing usability testing if we start by asking peoples' impressions of the page and other thoughts. I think you can evaluate everything - usability, terminology, IA, etc -- by moving tthe section 1 questions to after the usability portion. This isn't about my own personal preference on order, it's that I think we're compromising the ability to adequately evaluate usability by giving people too much time with the design before jumping into tasks. 

> I totally missed this, good call! I will chat with Christina about how we can update the prototype/convo guide if we do need to keep it as a research objective. I can't imagine any other place it would live on VA.gov so I'm not sure it's worth testing. In both preferred facilites and notification settings studies, people didn't expect to find those in their profile, but that didn't change our plans to put them there.

Sounds good re: discussing it. It can't hurt to evaluate whether people expect to find this information here. At best, we confirm that it's in the right place. At worst, we learn it's in the wrong place but also learn more about the veteran mental model (which is ultimately a good thing).

**Comment by cgednalske** [comment]
> ### Warm-up questions
> I saw you took this section out. Did you determine there was nothing you needed to evaluate here?

@Samara-Strauss yes, exactly! They were mostly just fillers to ease into the conversation anyway, not of any real value, so I just removed them. I didn't identify any questions that necessarily _needed_ to be there.

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss yes, exactly! They were mostly just fillers to ease into the conversation anyway, not of any real value, so I just removed them. I didn't identify any questions that necessarily needed to be there.

Sounds good.

**Comment by andaleliz** [comment]
>our usability testing should prioritize tasks first, otherwise we aren't doing usability testing if we start by asking peoples' impressions of the page and other thoughts...This isn't about my own personal preference on order, it's that I think we're compromising the ability to adequately evaluate usability by giving people too much time with the design before jumping into tasks.

That's an interesting perspective. I haven't heard it put that way before, and I can see your point. As I re-read the guide through that lens, I definitely see some opportunities to rearrange those questions. I think it's important understand what a participant thinks the purpose of a page is, or what they would do on the page, before they're exposed to the UI and all the functionality. If we wait until after the tasks to ask, they'll have discovered the answers by though through the test itself.

Also, I added the question "What questions do you have about what you see here?" in the beginning because I'm curious to learn if people understand what each label means before they see the options for them. I have a hypothesis that some of our Veteran population will be less familiar with these terms than others.

Christina and I are going to meet tomorrow afternoon to discuss the discoverability of this section in profile - we'll talk about this section too and update the guide accordingly.

**Comment by Samara-Strauss** [comment]
Thanks for this. Since we're kind of going around in circles, I asked Marci in Slack if we could have a short call tomorrow. Some of this might be easier/faster to talk through IRL. Thanks for your willingness to go back and forth over Github!

**Comment by MarciMcGuireGCIO** [comment]
Just sent out invitations for 1:00 ET tomorrow.

**Comment by Samara-Strauss** [comment]
Thanks! I might be 5 minutes late because I have a standing appointment that ends at 1:00, but I don't think we need to move the timing of the call.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss This has been updated, and is ready for you to take another look at.  Thank you, and let us know if you see something that doesn't align with your expectations. 

Cc @cgednalske @andaleliz

**Comment by Samara-Strauss** [comment]
This is MUCH stronger now that the scope is clear. Great job.

One final thought -- this probably goes without saying, but if usability problems happen to come up naturally, we should investigate them and figure out if there are ways we can improve upon them (eg. if someone says "I find [something about this design] confusing", ask more about it to make sure we fully understand the issue and ask how we could clarify the design to make it less confusing.). Usability testing may not be the objective of this research, but we don't want to miss opportunities for improvement if they come up naturally.

Otherwise, this is good to go!
