### ISSUE TITLE
[Research] Personal Information Revision Research: Draft research plan 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32705]
## Issue Description
As part of the the Personal Information Revision project, we'll need to recruit Veterans to review the personal information mock-ups so we can validate that our user interface is intuitive and useful. 

See [platform research plan reference documents](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/README.md) for guidance

---
## Tasks
- [x] Write a research plan to recruit Veterans to review personal information mock-ups  [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [x] Send the research plan to Samara and Marci for review 
- [x] Implement updates as needed

## Acceptance Criteria
- [x] The research plan is uploaded to our [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/research) in GitHub,  and linked in this ticket

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske when you have a minute, can you pop an estimate on this task?  Thanks!!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO I've estimated 5 for now but having a feeling this could change based on discussions with Liz and unknowns as I get acclimated to the process and guidelines

**Comment by Samara-Strauss** [comment]
Just a reminder that this is not considered done until I sign off on it, and I need enough time to review it, get feedback to you, have you implement that feedback, and then review again to make sure it's ready. So, please get this to me before the 11th hour tomorrow, or it's not going to be considered done for this sprint.

**Comment by cgednalske** [comment]
@Samara-Strauss Hi Samara - this ready for review and linked above, with some TBDs to work out with timeline and participation.

**Comment by Samara-Strauss** [comment]
Got it -- will review shortly. Thanks!

**Comment by Samara-Strauss** [comment]
## Feedback

### Background

- Please go ahead and link to the product brief now so we don't forget to do it before submitting this to recruiting.

### Research goals > Research materials

- Please link these materials now so we don't forget to do it before submitting this to recruiting.

### Recruitment criteria

- This is confusing the way you have it listed. There are three headings that all cover different "Must haves." Can you please consolidate these headings to one heading - "All participants must:", "Recruitment requirements", "Must haves for participants"?
- Re: "have a VA.gov account" -- you need to specify that they need to have an identity-verified, LOA3 account, and that recruiting should confirm this before testing. For more information on what that means, please check in with Marci or Liz.
- In terms of age, I think there might be a difference in how older and younger people perceive these updates, so I would add a requirement to get at least 1 younger and at least 1 older person. I'll leave the exact age ranges up to you.

### Timeline > Team availability

- Please use bullet points to list these so they are easier to scan

### Team roles > Resources

- I would either remove this or go ahead and link up the documents you can link up. But, you already link to the product guide, convo guide, and prototype earlier, and those should be the most important things. No need to list them again.

**Comment by Samara-Strauss** [comment]
## Recruitment criteria

- I can't believe I almost forgot this, but we 100% need people from the LGBTQ community participating in this research given that these fields are meant to inclusively capture how people define themselves. That is an absolute requirement. You may want to up the total number of people from 5 - 7, and please work with Liz to figure out the best way to ask for representatives from different groups. In terms of home many people from the LGBTQ community, it definitely does not and should not be all participants, but probably about 50%.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss. Sounds great! I will take a look at everything you've mentioned above.

Regarding recruitment criteria, to ensure members of the LGBTQ community are included, the two requirements below are currently listed as the main Must-haves (will definitely clarify these headings, by the way). 

- At least 2 people who identify as other than straight or heterosexual
- At least 3 people who identifies as other than cis-gender

When working with Liz on earlier edits, our thought was that this wording would be helpful in screening, as they could easily be converted to screening questions: "Do you identify as other than..." etc. 
Are you thinking that additional criteria should be added to ensure participants from the LGBTQ community? Or that the existing wording should be different?

**Comment by Samara-Strauss** [comment]
Those sound good to me! Thanks for including that, and sorry if I missed it originally.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - Christina has incorporated your research plan feedback and @andaleliz and I have reviewed.  We believe this is ready for you to take another look at.  Thanks!

**Comment by Samara-Strauss** [comment]
### Background

> The Personal Information section of the VA.gov Profile, previously part of the Personal and Contact Information section, was created to mitigate issues around Veterans showing up to health appointments and being addressed improperly, causing distress to both patients and staff who are working with inaccurate and outdated information.

This isn't accurate. We didn't create this section of the profile to mitigate issues around how veterans are addressed. This section already existed. The addition of preferred name/pronouns/gender identity/sexual orientation aims to to mitigate these issues and aims to also allow veterans to more accurately describe themselves within the VA.

## Research Goals

> Veterans expect to find this information in this section of the profile and website

Was there a question about this in the convo guide?

### Recruitment

> Secondary recruitment requirements:

I would re-label this something like "nice to haves" because it sounds like we are requiring that people meet these criteria, and we're not.

### Team Roles

> Observers: Marci, Samara, TBD - (open question for Samara)

Invite anyone on the project as an observer.

**Comment by Samara-Strauss** [comment]
Also, do you need Perigean to take notes? If so, you need to specify that. Sorry if that is in there and I missed it.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss This has been updated, and is ready for you to take another look at.  Thank you, and let us know if you see something that doesn't align with your expectations. 

Cc @cgednalske @andaleliz

**Comment by Samara-Strauss** [comment]
Great job! This is good to go.
