### ISSUE TITLE
Content updates to VR&E pages from stakeholder request

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32708]
## Issue Description
Stakeholder Peter Granato asked us to make some edits to several VR&E pages. He said they recently had a GAO report that asked them to put more of an emphasis on education in their content. The changes are in this Word doc:

[https://app.zenhub.com/files/133843125/45f0109d-5728-4917-ad6a-7fd87c7c7bbc/download](https://app.zenhub.com/files/133843125/45f0109d-5728-4917-ad6a-7fd87c7c7bbc/download)

We need to assess whether these changes should be made and if so, make sure they fit VA.gov's voice and style and plain language standards. 

## Tasks
- [x] Use assessment criteria sheet to determine if changes are warranted 
- [x] Write and edit content 
- [x] Copyedit
- [x] Give to Beth for final review
- [x] Final review
- [x] Publish pages
- [x] Notify stakeholder that changes are made

## Acceptance Criteria
- [x] Content is ready for final review
- [x] New content is live on the site

**Comment by lwalsh617** [comment]
@RLHecht - I made the SME-requested edits to the VR&E pages:
http://preview-prod.vfs.va.gov/preview?nodeId=725 (Veteran Readiness and Employment)
http://preview-prod.vfs.va.gov/preview?nodeId=729 (VR&E support-and-services tracks)
http://preview-prod.vfs.va.gov/preview?nodeId=731 (VR&E Employment through long-term services track)

**Comment by RLHecht** [comment]
@bethpottsVADEPO After reading through the [GAO report](https://www.gao.gov/assets/gao-21-450.pdf) Peter mentioned as well as some other research, we agree with his recommendations of adding "education" to several of the VR&E pages. We think it could be clearer that VR&E benefits will pay for more than vocational training and counseling. 

The updated content is in these preview links:

- http://preview-prod.vfs.va.gov/preview?nodeId=725 (Veteran Readiness and Employment)
- http://preview-prod.vfs.va.gov/preview?nodeId=729 (VR&E support-and-services tracks)
- http://preview-prod.vfs.va.gov/preview?nodeId=731 (VR&E Employment through long-term services track)

**Additional proposed changes and why:**
The GAO report showed that Veterans with a service-connected disability underuse this benefit because of its lack of visibility and an inability to distinguish between the GI Bill and VR&E program. With this in mind we propose:

- Updating teaser text and bullet points
- Updating mention on education eligibility page
- Adding content that shows the difference between VR&E and the GI Bill

**Teaser text and text on other pages:**
We should add "education" to the teaser text where we have VR&E as a related link. 

On benefit detail pages like the [education how to apply page](https://www.va.gov/education/how-to-apply/) and [disability eligibility page](https://www.va.gov/disability/eligibility/):

Veteran Readiness and Employment (VR&E)
If you have a service-connected disability that limits your ability to work or prevents you from working, find out if you can get VR&E benefits and services—like help exploring employment options and getting more education or training if required.

On the [disability hub landing page](https://www.va.gov/disability/):
Veteran Readiness and Employment (VR&E)
Find out if you qualify for help exploring employment options, any education or training you may need, and other VR&E services.

We should add "education" to the bullet point: 
- Post-secondary education and training at a college, vocational, technical, or business school
This is on both the [VR&E eligibility](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) and [IDES](https://www.va.gov/careers-employment/vocational-rehabilitation/ides/) pages.

**Mention on education eligibility page:**
We also suggest changing the H2 on the [education eligibility page](https://www.va.gov/education/eligibility/) that currently reads "Are there any related benefits I may also be able to get?" to "If I have a service-connected disability, are there any related benefits I may also be able to get?" This puts the user in the question like in the questions below such as dishonorable discharge and spouses and dependents. We think this makes it more apparent that VR&E is another education benefit option if you have a service-connected disability.

**Adding new content:**
We suggest adding content in 2 areas:
1. A section on the Long-term services track page similar to what we have on the [Post-9/11 GI Bill page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) in the section under the H2 "What benefits can I get through the Post-9/11 GI Bill (Chapter 33)?" where we give specific benefit information (tuition amount, for how long, etc.) This information is all listed in the GAO report. 
2. A future R&S article showing the difference between VR&E and the GI Bill. This is similar to the chart we have on the survivors and dependents page showing the difference between DEA and the Fry Scholarship. That raises the question of whether this should be in R&S or the new information we would be providing should be on a tier 1 page.

If you agree with this, I can write up what our response to Peter would be.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @lunascoop @RLHecht Looks great! I put my comments in italics above for each section of suggestions you made. I'd like to hold off on the bigger changes, and make sure we fulfill the initial request first. See above. Randi, go ahead and send me your response to the SMEs and I'll look whenever you have it ready. I'll be online briefly on Friday and will make sure I keep this moving.

**Comment by RLHecht** [comment]
@lwalsh617 Can you make the edits in Drupal to the teaser text and the bullet points listed in my comment above? Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - Changes in your comment ^^^ have been made to the following pages:
Education > How to apply: http://preview-prod.vfs.va.gov/preview?nodeId=943
Disability > Eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=871
Disability Hub: http://preview-prod.vfs.va.gov/preview?nodeId=68
VR&E > Eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=726
IDES: http://preview-prod.vfs.va.gov/preview?nodeId=728

**Comment by RLHecht** [comment]
Thanks @lwalsh617 These have all been published as well as the edits to the intros that Peter initially asked for. I'll send him an email letting him know once the changes are all live.

**Comment by RLHecht** [comment]
Closing this ticket as the SME requests are completed. Will open up 2 new tickets for the backlog for adding content to the long-term services track page and possibly creating an R&S article for a comparison between VR&E and the GI Bill.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Is this work complete? Can you close out this ticket?
