### ISSUE TITLE
Staging Review [Identity Team - Sign-in Modal]

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#32717]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
    Sign in page => https://staging.va.gov/sign-in
    Modal => https://staging.va.gov (then Click Sign In button in the header)

- [ ] Product outline 
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: [Insert name here]
- OCTO-DE Product lead: [Insert name here]
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

-Alex Garcia
-Amanda Porter
-Cody Reinold 
-Nick Soutouras

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling

**11/16/2021** **1130**

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Confirming that the Staging Review has been scheduled for 11/16 at 11:30am ET.

**Comment by allison0034** [comment]
@nsoutouras the staging link seems to look the same as production. Can you confirm it is updated? Also can you please attach the product outline?

**Comment by nsoutouras** [comment]
https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/32268

**Comment by nsoutouras** [comment]
> @nsoutouras the staging link seems to look the same as production. Can you confirm it is updated? Also can you please attach the product outline?

We do not currently have a Product Outline.

Changes are visible on dev: http://dev.va.gov/

**Comment by nsoutouras** [comment]
> @nsoutouras the staging link seems to look the same as production. Can you confirm it is updated? Also can you please attach the product outline?

Sorry, slight correction.  

Use this link: http://9c62ce59f963f09385d15281091d2cf7.review.vetsgov-internal/

You'll need to be on socks.  Once on, you can click the sign-in button and see all changes pending approval.

**Comment by allison0034** [comment]
@nsoutouras several of our team members do not hav SOCKS. Can you add a screen shot or other option?

**Comment by nsoutouras** [comment]
Per our designer: 
"They will not be able to see the Sign In Modal because the changes are behind a feature flag. Meaning they will need to sign in with the ID.me accounts we provided and visit the https://staging.va.gov/sign-in page.  And the Sign In Modal will not show for logged in users. (edited) "

**Comment by allison0034** [comment]
@nsoutouras I just tried http://9c62ce59f963f09385d15281091d2cf7.review.vetsgov-internal/ while on the VA network and I am getting page not found.

**Comment by nsoutouras** [comment]
> @nsoutouras I just tried http://9c62ce59f963f09385d15281091d2cf7.review.vetsgov-internal/ while on the VA network and I am getting page not found.

Please see my comment above

**Comment by allison0034** [comment]
@nsoutouras if we sign in we cannot see the sign in page bc we are signed in.

**Comment by nsoutouras** [comment]
Screenshot
![screen](https://user-images.githubusercontent.com/30237585/141805942-959321bb-921b-4381-bf2c-b545ee40b9bb.PNG)

**Comment by shiragoodman** [comment]
@nsoutouras our other reviewers will still need access to staging and will need more than a screenshot to complete their review. Allison makes a good point... if we sign in, we can't see the modal bc it doesn't show for signed-in users. Can you please have someone from your team help us out? We will not be able to hold a Staging Review tomorrow without viewing the modal in Staging.

**Comment by nsoutouras** [comment]
@shiragoodman I was able to access the page above by doing the following:
1.) Log into staging (https://staging.va.gov) using the users listed in my [earlier comment 
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32717#issuecomment-968973876) - Passwords ([Link](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) via ID.me
2.) Go to  https://staging.va.gov/sign-in

New page should show same as image above.

**Comment by pjhill** [comment]
@nsoutouras, 

1. Do you all have a test plan that targets any new functional acceptance criteria associated with the new modal?
2. Are there any Cypress E2E tests that cover this modal? I know of this [one](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/tests/unauthed-flows.cypress.spec.js). Are there any changes that should be made? Spin up a new spec?

**Comment by nsoutouras** [comment]
> @nsoutouras,
> 
> 1. Do you all have a test plan that targets any new functional acceptance criteria associated with the new modal?
> 2. Are there any Cypress E2E tests that cover this modal? I know of this [one](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/tests/unauthed-flows.cypress.spec.js). Are there any changes that should be made? Spin up a new spec?

@AGarcia-Clarity can probably answer this better than I can

**Comment by AGarcia-Clarity** [comment]
@pjhill Updates to the Cypress E2E tests were addressed in the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19306/files

**Comment by noahgelman** [comment]
@nsoutouras No accessibility feedback
