### ISSUE TITLE
[Access Management] Document offboarding process

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#32716]
## Description
Documentation should exist that captures that off-boarding process. 

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Write up Confluence page in the "How To" section
- [x] Update offboarding-request.md

## Acceptance Criteria 
- [x] PR is reviewed and merged.
- [x] Confluence doc has been reviewed. 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
I've started writing up some notes on this.

**Comment by rmtolmach** [comment]
I wrote up documentation that should help someone who is new to the process: https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member

I also added links to the offboarding template to make the process of checking for access quicker. That PR is here: https://github.com/department-of-veterans-affairs/va.gov-team/pull/37512

**Comment by jhouse-solvd** [comment]
@rmtolmach - Are there any other tasks or AC that can be checked off? Is this still in progress, or in review? Thanks for the info.

**Comment by rmtolmach** [comment]
@jhouse-solvd I checked some things off ✔️ . Only thing left to do is review the confluence doc. I'll find someone to do that.

**Comment by rmtolmach** [comment]
I asked Kyle to review the doc. He gave me some feedback and I made the changes. Closing 🎉
