### ISSUE TITLE
[Research] Profile: Personal Information Revision - Kick off recruiting for prototype reviews

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32711]
## Background
Before we go too far in constructing the new Profile Personal Information page, we need to ensure that the language used is acceptable and that the tool is intuitive and easy to use.  Initially we will accomplish this by having users review our prototypes. 

Now that we've completed the UAT research plan and conversation guide, we need our PO to review the documentation and then submit those materials to Lauren Alexanderson.

[Perigean recruiting guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/perigean-recruiting-guidance.md)

## Tasks
- [ ] Samara to review UAT materials 
- [ ] Submit research plan and conversation guide to Lauren Alexanderson (lauren.alexanderson@va.gov; slack: @lalexanderson; github: lalexanderson-dsva) for review and approval
- [ ] Prep all note taking/synthesis materials

**Comment by MarciMcGuireGCIO** [comment]
This work is covered in #33438
