### ISSUE TITLE
MAINTENANCE: Configure linter

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32724]
# User story
As a PW author, I want to more quickly identify (and ideally fix) errors in my writing, so that I can contribute higher quality content.

# Tasks

- [ ] Present to Rachael on 11/18
  - Identify rules based on Atlassian guidelines for collab with team and Rachael
  - Secure approval from Thomas Delrue and Michael Fleet (Liani and Amy)
- [ ] Enable the linter in all the PW spaces
- [ ] Configure the rules in all PW spaces
- stretch - create messaging to teams about linter

We can bring Peggy in on this

# Acceptance criteria
- Linter has X rules configured
  - X = number of rules TBD, pending RR approval in Task 1

# Reference info
- [Linter recommendation](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1961394184/2021-11-10+Should+we+add+the+Scroll+Content+Quality+linter+to+the+Platform+website+WIP), specifically decision and modification requests at end of document

**Comment by amygoldman** [comment]
Initial [linter research and pro/con list](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/1944027159/Scroll+Content+Quality+plug-in)

**Comment by amygoldman** [comment]
[Configuring rules](https://help-cloud.k15t.com/scroll-content-quality/Edit,-Create-and-Configure-Rules.13719568555.html), rule types, etc.

**Comment by amygoldman** [comment]
We'll base rules on the [Platform style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide) and the [word list](https://vfs.atlassian.net/wiki/spaces/AP/pages/622067754/Word+list)

**Comment by lianilychee** [comment]
11/11 Thurs:
- thoughts on collab with peggy:
  - depends on where I (Amy) am next week
  - go thru word list and identify the terms we should create rules around
- Amy getting started on identifying what rules need to be written, before pulling in Peggy

**Comment by lianilychee** [comment]
11/12 Fri:
- Today:
  - have list to share w/ Peggy and everyone else on Mon: Potential rule types, specific rules

**Comment by lianilychee** [comment]
About the ` Present to Rachael on 11/18 > Secure approval from Thomas Delrue and Michael Fleet (Liani and Amy)` task -- [Liani asks for Thomas and Fleet's blessing in this post](https://dsva.slack.com/archives/CJRQ85PQB/p1636752489200300)

**Comment by amygoldman** [comment]
[Spreadsheet ](https://docs.google.com/spreadsheets/d/1_3yCVm01jO6UkHTUkWP6pze78k1MA7AYRczOi-GAdvM/edit#gid=0)

**Comment by lianilychee** [comment]
11/18 Thurs:
- overall impl work:
  - putting each and every item for iteration for each rule type that we'll need to create
    - ex: in the xls there's a tab for each rule type, and we're gonna put an example for each rule type
  - then putting the text editor version of each rule in the next column
- today:
  - resolve the questions in the Conf page
  - fill out the xls but don't know speed of filling in because haven't started
  - Peggy will fill in the rules for the words 
- **check in tomorrow about EOS goal - how should we change it?**

**Comment by lianilychee** [comment]
11/19 Fri:
- Today
  - add Rachael's suggested rules to the table before transferring to Google xls
  - set up another sync with Peggy next week
- By Mon 11/29, hope to: Be able to focus completely on Google xls
