### ISSUE TITLE
FIRST PROJECT: Identify goals of Testing Tools audit

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#32726]
# User story

To come.

# Tasks

- [ ] Identify EOQ goals of audit and implementation
  - How many pages:
    - Have duplicative content?
    - Should be completely overhauled?
    - Are inappropriately stored
    - Have improper naming conventions
    - Are in-compliant re: Formatting, relevancy, and style guide
    - Follow logical structure (ie context up front)
    - Need to be slimmed down
- [ ] Identify interlinking
- Establish working relationship with Testing T
  - [ ] Inform Testing T that we'll be collaborating w/ em this quarter, schedule regular touchpoints with Testing T
  - [ ] Understand how Testing T and their SMEs operate

# Acceptance criteria
- To come.

# Reference info
- To come.

**Comment by lianilychee** [comment]
11/12 Fri: 
- Today: Jessica familiarize self with the testing tools content and write down what to unearth in the audit (assessment)

**Comment by lianilychee** [comment]
11/18 Thurs:
- blocked by:
  - Samara - time
  - Jessica - "Store a secret in parameter store" and will now focus on this :D
- Today will do:
  - Samara, Jessica - short sync w Gretchen
- **tomorrow - check in about EOS goal changes**

**Comment by lianilychee** [comment]
11/19 Fri:
- blocked by: time ie not able to sync up
- also foresee time being a future blocker
- By 11/29 (Mon after Thanksgiving week), hope to have a chunk of the testing content already started
  - Shooting, also, for most of the docs to be started by 12/2
