### ISSUE TITLE
[Debt Management Portal] Replace sighted language

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#32720]
## Issue Description
The sitewide content team is moving away from using sighted language, such as the word 'view', on VA.gov.

This ticket captures the updates to implement into the Debt Management Portal. 

---
## Tasks
- [ ] Update the content in the areas outlined in [the sighted language audit document](https://governmentcio.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Document.docx?d=wff57feff0de94b0b8b9283d62f59db9b&csf=1&web=1&e=vihojA)
   - [ ] 'What if I don't see a debt?' section
   - [ ] Debt letter history section
   - [ ] 'What if I don't see the letter I'm looking for?' section

## Acceptance Criteria
- [ ] The content has been updated in the Debt Management Portal
