### ISSUE TITLE
[Design] Profile: Personal Information Revision - Create Interactive Prototype for User Testing

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32731]
## Background
Now that we have mockups for Personal Information Revision updates, we need them to be in an interactive format that approximate the user experience for user testing.

## Tasks
- [x] Talk with Liz about current approach for prototypes for user testing --- inVision or UXPin
- [x] Build interactive prototype that works in the same manner as the planned application
- [ ] Ensure that the interactivity allows only one Personal Information section (Preferred name, Gender identity, etc.) to be edited when an Edit button is clicked
- [ ] Include all use cases [_Note - check with Liz on how many uses cases are typically tested, and we can edit this list accordingly_]
    - [ ] Clicking info link ("How do I update my...")  to FAQs at top
    - [ ] Add preferred name / Save / Confirm
    - [ ] Add Gender identity / Save / Confirm
    - [ ] Add Pronouns / Save / Confirm
    - [ ]  Add Sexual orientation / Save / Confirm
    - [ ] Edit preferred name / Save / Confirm
    - [ ] Edit Gender identity / Save / Confirm
    - [ ] Edit Pronouns / Save / Confirm
    - [ ] Edit Sexual orientation / Save / Confirm
    - [ ] Add preferred name / Cancel / Confirm
    - [ ] Add Gender identity / Cancel / Confirm
    - [ ] Add Pronouns / Cancel / Confirm
    - [ ] Add Sexual orientation / Cancel / Confirm
    - [ ] Edit preferred name / Cancel / Confirm
    - [ ] Edit Gender identity / Cancel / Confirm
    - [ ] Edit Pronouns / Cancel / Confirm
    - [ ] Edit Sexual orientation / Cancel / Confirm

## Acceptance Criteria
- [x] Determine whether prototype will be created on inVision or UXPin
- [x] Build interactive prototype that approximates the user experience and includes all uses cases listed above.
- [x] Document inVision or UXPin link in this ticket and share with Marci and Samara for review

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO A simple [Personal Information Prototype](https://preview.uxpin.com/3da645f63bd0af429df93e834e287f00acbbbd70#/pages/144795458) is complete with current designs. (Not included the upcoming hint text that will be added to each field, on which I'll need to work with Danielle)
This can be used to understand if it will work without additional capabilities, or if further fields/work is needed. Current prototype allows viewing the edit states and selection options for each field, but no customization is possible. Participants can essentially go in and out of each general edit state in order to tell/show us if the terms listed and order of the fields make sense to them.

**Comment by Samara-Strauss** [comment]
![image](https://user-images.githubusercontent.com/34068740/143889771-a7117edc-b370-4045-8869-07e118bf4570.png)

- The spacing in the nametag area looks off. Can you fix that?
- Also, not sure why is says "chevron right" instead of showing the arrow next to the disability rating.
- I was playing around with the edit state and noticed that after I save, the information I entered *does not* show on the next screen. It's going back to the "add" state. Within reason, we need to make this prototype feel as much like the real experience as possible, recognizing we're not going to be able to make this 100% interactive like it would be online. However, having someone add information and then having it show after it's saved is basic, and we need to make sure that the prototype can at least do that so people don't get confused.

**Comment by cgednalske** [comment]
@Samara-Strauss The "chevron-right" is bizarre! Thank you for pointing that out! I will check on why that might be happening and make sure the symbol is up to date with the pattern library. 
I have similar concerns about the states as well and have been mulling over how to best achieve a more realistic version - without the ability to edit fields directly, my dilemma is that none of the options below seem adequate:

1) Once info is edited, we can return to a page where information has been populated in that field only. In this case, after "editing" each field, it would always return to a page where only that field is edited, but the others have become blank, because it would not be possible to know/save the answers previously changed when using only page to page connections.

2) Another option is to navigate to a page where the information has been edited in every field. In this case, only the very first view would show the "add" states and then from there on the participant would return to a state already showing updated information for all fields, to edit rather than add for the first time.

3) Rather than start on the "add" states, we could start directly on a page showing filler personal information already included, with the goal being to edit the existing information rather than begin from a blank page. In this case the information would always be populated, but at least it would be consistent. (This feels like the least confusing option to me, but it would leave out the initial "add" states from testing)

Thoughts on these options? Or any other suggestions that may be possible with only page to page transitions?
I'm not sure how next sprint is looking, but I'd also like to explore if it's possible within the timeframe to create a more realistic prototype using more of UXPins capabilities. In this case, it does feel like it could be worth it to try and apply more advanced techniques.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske cc @Samara-Strauss - I do think it's important to test the initial "add" state in this scenario.  Since this is a brand new addition that initially won't contain data, we need to make sure that users understand how to populate the new fields.   

@Samara-Strauss  @andaleliz  - I am not familiar with UXPin or how it's typically used in testing, but can we ask users to enter a specific value so that, to Christina's point, we do know what it should display after it has been saved?

**Comment by MarciMcGuireGCIO** [comment]
If @cgednalske is prepared to share her research plan and conversation guide with us @Samara-Strauss ,  she could potentially get recruiting started and spend the interim time next Sprint getting some advanced features added to the prototype.

**Comment by Samara-Strauss** [comment]
This is how I think the prototype should work:

- Add state for all info
- Edit state for one field
- Once saved, new information shows up

Rinse, lather, repeat for each field. So, yes, that means you will have to create screens that show the progressive addition of information for each field.

@andaleliz what do you think of this? Also, could I ask you to be the point person on this and guide Christina through the process?

> If @cgednalske is prepared to share her research plan and conversation guide with us @Samara-Strauss , she could potentially get recruiting started and spend the interim time next Sprint getting some advanced features added to the prototype.

@MarciMcGuireGCIO we can not start recruiting until all three of these things are done, as there have been issues across the contract in the past with inadequate plans/convo guides/prototypes that were not resolved by the time research was scheduled. So, these all need to be 100% done and signed off on by me before they can be submitted for recruiting.

**Comment by cgednalske** [comment]
@Samara-Strauss above certainly makes most sense; however, am I correct that the process outlined above would require the participant to follow through in the exact order listed? 

To test out IA in a natural way without prompting, part of what is currently included in the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/research/researchplan.md) and [conversation guide tasks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/research/conversation-guide.md) (ready for your review with some TBDs to discuss - Liz and I previously reviewed the drafts together before edits) are steps to see if participants are inclined to edit fields in a different order than how we've listed them - to help see if they bring up any issues with the order without prompting.

This could certainly be removed, but then if referring to the ordering of fields, we'd need to rely on asking participants their thoughts directly.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss thank you for clarifying this process.  This is extremely helpful.

**Comment by andaleliz** [comment]
👋  Hi all! Yes, totally happy to be the point person on this and guide Christina through the process.  

Getting UX Pin to reflect back a user's entry in our saved state is fairly complex and time-consuming, based on my understanding of states and data - I think we'd have to create a unique state and logic for every possible combination of checkboxes. But I'll check with a couple of folks who have more UX Pin experience than I do and see if there is a better way to do this.

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss What you're describing is reasonable to do in UXPin.  And, for all of our awareness, it is possible to have people type in a real answer and have that save in UXPin too! We can explore the LOE for that (this is news to me), and go with a pre-populated option if that's faster.  

Christina and I will take it from here 😁

**Comment by Samara-Strauss** [comment]
Sounds great! Thank you, @andaleliz!!

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - do you still have additional work left on this? Thanks!

**Comment by Samara-Strauss** [comment]
I'd like to review the prototype before closing this ticket.

**Comment by MarciMcGuireGCIO** [comment]
> I'd like to review the prototype before closing this ticket.

@Samara-Strauss - here is the updated prototype link -- https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586?mode=i

**Comment by Samara-Strauss** [comment]
Thanks!

**Comment by Samara-Strauss** [comment]
![image](https://user-images.githubusercontent.com/34068740/144278765-b0c8d3cf-d100-4510-99ec-a54c7d1a776d.png)

I only checked "he/him/his" but "they/them/theirs" also showed up. Is the intention to tell the participant to select both?

![image](https://user-images.githubusercontent.com/34068740/144278975-e8d42bf0-aa4a-4dbc-982f-602f04a49544.png)

I also selected "straight or heterosexual" here, and "Lesbian, gay, or homosexual" is what showed up. Is the intention to tell the participant to select "Lesbian, gay, or homosexual"?

Also, I kept having weird issues where the prototype reloaded on its own and would bring me back to the "add" state. Did this happen to anyone else?

**Comment by andaleliz** [comment]
@Samara-Strauss The responses in the prototype are preloaded and won't reflect the actual choices you made. That would take another day to make the prototype intelligent enough to do that. It's something we can explore if you feel it needs to be that sophisticated. 

This is addressed in the conversation guide with this statement before they start making changes:
>Before we move forward, I do want to mention that after you edit and save the information, you will see pre-populated information. So, though you can make different choices, what you see later will not necessarily reflect your choices and will instead show what has already been filled in. Do you have any questions about this?

>Also, I kept having weird issues where the prototype reloaded on its own and would bring me back to the "add" state. Did this happen to anyone else?

This hasn't happened to me or others afaik, but let's keep our eye on it.

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss The responses in the prototype are preloaded and won't reflect the actual choices you made. That would take another day to make the prototype intelligent enough to do that. It's something we can explore if you feel it needs to be that sophisticated.

> This is addressed in the conversation guide with this statement before they start making changes:
> 
> Before we move forward, I do want to mention that after you edit and save the information, you will see pre-populated information. So, though you can make different choices, what you see later will not necessarily reflect your choices and will instead show what has already been filled in. Do you have any questions about this?

Is this confusing to anyone else? I don't think we need to make the prototype 100% fully interactive -- that's not a good use of time -- but I think it'll be confusing if someone chooses one option and then sees another one then they save. Is there a reason you are not telling people what options to select?

**Comment by andaleliz** [comment]
>Is there a reason you are not telling people what options to select?

Generally, we want to encourage people to behave as naturally as possible so I advised Christina to lead them as little as possible. In a way telling people which boxes to check feels like we're guiding them on how to use the form. I haven't heard from anyone else that it's confusing but I'm not sure who else has reviewed it. 

What if we see how this goes during the pilot, and if the participant gets confused, we can update the guide to tell people explicitly which boxes to check.

**Comment by Samara-Strauss** [comment]
> What if we see how this goes during the pilot, and if the participant gets confused, we can update the guide to tell people explicitly which boxes to check.

That sounds reasonable. I definitely don't want to be leading, but I also don't want people to be understandably confused if they choose option A and then option B shows as saved.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss This has been updated, and is ready for you to take another look at.  Thank you, and let us know if you see something that doesn't align with your expectations. 

Cc @cgednalske @andaleliz

**Comment by Samara-Strauss** [comment]
![image](https://user-images.githubusercontent.com/34068740/144662598-394cf7f7-d377-4718-a280-7a4da41d70f6.png)

This weird "chevron right" issue is coming up again. Is that a weird UXPin bug or something? Is it working in your browsers?

Otherwise, my only comment is that pronouns, gender identity, and sexual orientation all have pre-selected answers, and I don't think that's necessary given then scope of research and the conversation guide. Unless you have a reason to keep the pre-selected answer (and please let me know if you feel strongly about this), I think you can take them out and this is probably good to go besides the "chevron right" issue.

**Comment by cgednalske** [comment]
@Samara-Strauss Yes you're right! That's not the correct version. We created an iteration so the link would have changed. 
This should be the new correct link with the fields all returning to the edit state without any pre-filled answers: https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i

**Comment by Samara-Strauss** [comment]
Looks great!! This is good to go!

**Comment by MarciMcGuireGCIO** [comment]
Noting that this needs one quick update to show the FAQ link(s) to Resources & Support at the top, then ready for Midpoint review.  @cgednalske please ping me when that update is complete.  Thx!

**Comment by MarciMcGuireGCIO** [comment]
Prototype has been updated and Christina has submitted her research plan to Lauren for review.
