### ISSUE TITLE
Create VA.gov wide dashboard in Domo

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#32733]
## Issue Description\
Create VA.gov wide dashboard in Domo
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] Build cards
  - [x] Task Completion section
  - [x] Ease of Use section
  - [x] User Satisfaction section
  - [x] Findability section
- [x] Build [data pipelines](https://docs.google.com/spreadsheets/d/1lJ52GHKDrsCp-N7tK5iFe5noWGqg3BX3yDALzkyv7RU/edit#gid=1769550756) in Domo where needed 
- [x] Configure page
- [x] Flag any issues

## Acceptance Criteria
- [x] MVP All VA.gov dashboard built and ready for QA.
---

**Comment by chloedotbrown** [comment]
**Data QA**
To be as thorough as possible for this dashboard, I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1B-U8_35c8CaETxz2iAJ2L-LxawIDXNvajpd9OlEr9GY/edit?usp=sharing) for QA here, which also includes a column to gut-check the business logic. This may be overkill for metrics we've used elsewhere, but for new KPIs and data sources, I want to create an extra step to make sure what we think we're showing matches the actual data. Folks QAing: please reach out with any questions!

**Design QA**
I still need to give this one more pass to make sure the tooltips and directionality of color-coded changes are correct. An example of Design QA can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25871#issuecomment-882869480).

**Comment by chloedotbrown** [comment]
Rescoped ticket to cover build fo MVP in Domo. Data and Design QA work will continue on tickets #33935 and #33937, respectively.
