### ISSUE TITLE
KPI Dashboards User Inteviews

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#32732]
## Issue Description
We need to conduct interviews with VFS teams using standardized dashboards in order to get a better sense of the ways that users understand and interact with their dashboards. Our hypothesis is that if we understand how users are using or expecting to use the Domo dashboards, we can better curate KPIs and target new training resources, which will increase meaningful usage of our data products.

This is a continuation of the work from ticket #31356. Once this ticket has been completed, the work of 1) creating the research readout and 2) combining research synthesis, usage stats, and brainstorms within the Analytics team to inform a plan for redesign will take place on other tickets.

---
## Tasks
- [x] Conduct pilot session 
- [x] Conduct user interviews
  - [x] Michelle Middaugh (11/12)
  - [x] Brian Lloyd (11/15)
  - [x] Ronnie Henry (11/15)
  - [x] Sharon Kasimow (11/17)
  - [x] Marci McGuire (11/18)
- [x] Note-taking and cleanup
  - [x] Michelle Middaugh (11/12)
  - [x] Brian Lloyd (11/15)
  - [x] Ronnie Henry (11/15)
  - [x] Sharon Kasimow (11/17)
  - [x] Marci McGuire (11/18)
- [x] Notes transferred to [MURAL board ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1637099802029/6e3346bb7da074e665cd38e5f6091ab34f2eaebb?sender=uefee97503966efdb24069760)
- [x] Synthesis session complete 

## Acceptance Criteria
- [x] Users interview are complete
- [x] Synthesis is complete

**Comment by chloedotbrown** [comment]
@pavanhothi and @jonathan-epstein13, I've created a [MURAL board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1637099802029/6e3346bb7da074e665cd38e5f6091ab34f2eaebb?sender=uefee97503966efdb24069760) for out synthesis session. As you finish cleaning up notes, please feel free to check of the participant in the ticket above and to start converting your notes to stickies on the MURAL. Stickies should be brief, but give enough info that folks will be able to tell what they're talking about when we later shuffle them away from their questions during Monday's synthesis session.

You should all have edit permissions, but if you have any trouble accessing or questions about what to include, let me know!

**Comment by michelle-dooley** [comment]
All tasks completed. closing ticket.
