### ISSUE TITLE
New sign in design tweaks

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#32737]
## Issue Description
Some suggestions were made to ensure design consistency of the Sketch and live environments (see tasks)

---
## Tasks
**Stylings** 
- [x] Buttons were too big via padding (removed usa-button-big class, added more y-padding)
- [x] Buttons were too long via width (updated the container)
- [x] Locked down character width for the Terms and use content (to match design)
- [x] Ensures `loginGovEnabled` prop is passed down to FedWarning component to enable updated design

**Action links** (Please defer questions/concerns) about this implementation to Ryan Thurwell or Cody Reinold)
- [x] Changes Action links implementation from (button back to an anchor tag)
- [x] Adds `role="link"` so it can be tabbed to in screen readers
- [x] Adds `tabIndex="0"` so it can be tabbed to in screen readers
- [x] Adds the `aria-label` attribute and specifies it will `Open in new window`

## Acceptance Criteria
- [x] Design implementation is signed off by Collab cycle
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Update: Changed the Action links to use the href generated by the sessionTypeUrl

**Comment by AGarcia-Clarity** [comment]
Moved to PM review ready to be closed.
