### ISSUE TITLE
SD -  Strategic Road map exercise prep and debrief 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32746]
## Issue Description
_Preparation and debrief for Resources & Support strategic roadmap exercise_

---
## Tasks
- [x] _Create and confirm meeting agenda_
- [x] _Create Mural board for presentation_
- [x] _Create meeting script and timebox_
- [x] _Schedule practice and debrief session_
- [x] _Document findings and notes_

## Acceptance Criteria
- [x] _Have all necessary data, mockup, agenda and mural board ready to present and discuss with stakeholders_
- [x] _Clearly define goals, metrics and action items_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
[Mural Board](https://app.mural.co/t/vagov6717/m/vagov6717/1636744654505/e4733a01687242944f0904f3544ee73cc0f47435?sender=u1777baa622793bb339be4705)
[Notes](https://governmentcio.sharepoint.com/:w:/s/SearchDiscoveryTeam/Eci6fjxBzV9OuxVnJUgbMq8BJenolqnIw-IknCxqQED2-w?e=0Z6k4z)

**Comment by mgleo** [comment]
Roadmap Session Summary: 

**Common themes** 

- Authoring experience 
- Single source of truth 
- Reusability of content 
- Content consistency and accuracy 
- Sunset of legacy systems 
- Findability of content / Surfacing of the content 
- SEO/findability 
- Veteran satisfaction 
- Design / User experience 
- Decrease in calls 
- Information usefulness 
- Value and purpose 
- Task completion 
- CTA efficacy 

 

**R&S Top Issues** 

1. Value and purpose 
2. Reusability of content 
3. Task Completion 
4. Tie between: 
   - Veteran Satisfaction 
   - Design / User experience 
   - Sunset of legacy systems
