### ISSUE TITLE
Revert merge of Removal of Gating for Original Claims

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3275]
## Problem Statement
Ticket #3157 merged prior to completion of BE work. re-add step 2 with another PR and then recreate the PR removing step 2, but this time not merge it

## Tasks
- [x] Add gating for Original Claims back to production
- [x] Recreate PR to remove the gating without merging it

## Acceptance Criteria
- [x] Work from #3157 reverted
- [x] PR ticket recreated for future merge

**Comment by ndsprinkle** [comment]
@YanaRoy 

The pull request for adding step 2 of the gating back has been created and merged: https://github.com/department-of-veterans-affairs/vets-website/pull/11072

And the pull request for re-removing step 2 of the gating has been created: https://github.com/department-of-veterans-affairs/vets-website/pull/11079
