### ISSUE TITLE
Refactor `verify_url` to use 'type' attribute

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#32757]
## Issue Description
The `verify_url` method that generates verification SAML headers currently relies on the `link_authn_context` attribute to determine which CSP it is creating SAML for. This is an inelegant solution that relies on IAM setting their `authn_context` response to inappropriate strings. The `type` attribute is already passed back in the SAML response for `saml_callback` calls and is accessible for this exact purpose, it should be used instead.

---
## Tasks
- [x] Split the logic for `saml_callback`-derived calls from the logic for user-initiated calls within `verify_url`
- [x] Assign SAML headers for `saml_callback` verify calls based on the `type` attribute that is set and returned with ActiveRelay

## Acceptance Criteria
- [x] No functionality changes - all SAML headers for both types of `verify_url` calls will remain unchanged
- [x] `saml_callback`-derived `verify_url` calls will now generate SAML based on the `type` attribute within `url_service`
