### ISSUE TITLE
[FE] Auth Profile: Add New Fields to Personal Information page - Edit State 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32768]
## Issue Description
As a front end developer, I want to build the Edit state of the VA.gov profile screen so that users will have the ability to edit a field.  

### Tasks
- [x] Remove Contact info fields from Personal information page since they have now been moved to their own page.
- [x]  The design pattern and components should mirror what is currently in Production Pages should be based on the [updated design files](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/design).
- [x] The logic should allow only one section to be edited at a time per the existing design pattern in Production.
- [x] Copy should reflect the [front end copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [x] Each question will require a default "blank" state that provides some information advising the user to click edit to provide info.  [See exact copy here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---blank-state).
- [x] Add "Do not wish to disclose" option to Pronouns and Sexual orientation sections.   [See exact copy here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [x] Selecting the "other" option for Pronouns or Sexual Orientation make that question's accompanying text field required unless if the user attempts to update without typing a value into the text field. 
- [x] Changing Preferred Name will not affect the MPI-derived name shown in the "nametag" at the top of the page.
- [ ] If the MPI-derived value for Preferred Name, Pronouns, Gender Identity or Sexual Orientation are NULL/blank, then the field shall not be flagged as required.  If the MPI-derived value is other than NULL/blank OR the user enters a value and updates, the field shall be flagged as required and cannot be changed to NULL/blank through this UI.

Please use the below files for reference
- [Edit State Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw)
- [UXPin Prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

## Acceptance Criteria
- [x] New Fields are added
- [x] Features are behind flag to test on staging 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
Moving this to Sprint 62 in place of the Read-Only state task #32771

**Comment by MarciMcGuireGCIO** [comment]
Hey @zacharymorel !  This page looks great so far!  

Couple of things I saw -- the radio buttons for Gender Identity and Sexual Orientation don't seem to be working for me, and the text boxes are not visible for either of those.  I was using Chrome on Win 10.

![image](https://user-images.githubusercontent.com/73354907/145485512-f814ae66-ee4f-413a-b81d-cc40b3715924.png)
![image](https://user-images.githubusercontent.com/73354907/145485540-dbf4a495-c4ec-428a-a6d6-56886eb22f43.png)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO did you select the text of the radio options?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - I only clicked the radio buttons themselves.  

Noting for Adam: We've discussed and determined this is either a limitation of the component (although it works correctly in the story book) or could be because the form system library doesn't use the same component shown in the storybook

**Comment by Samara-Strauss** [comment]
+1 re: the radio button issue and the text boxes not showing up when I select "[Field name} not listed here]". Otherwise, this is looking good and exciting to see!

**Comment by MarciMcGuireGCIO** [comment]
Making a note here that @zacharymorel implemented the checkbox group component from the design system.  He said that it works in the Playbook, but it does not work in this page.   The user has to click on the words instead of clicking on the actual checkbox.

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - if you have questions about this, please let me know.  The Staging URL is https://staging.va.gov/profile/personal-information and you can find test users in the [sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/test_users.md).

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 63 since we now know when the open text boxes should become visible.

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - Zach left this comment, I believe after a conversation with someone on the design system team.  It might be worthwhile to reach out to them on Slack to see if they can give you any further guidance on this.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/32768#issuecomment-991200600

**Comment by MarciMcGuireGCIO** [comment]
This has been completed and functions as well as it can given that it is not connected to the API, so cannot call an endpoint to save the value. We will create a separate ticket to validate with the backend once that is completed.  Also creating a new ticket  to work with the design system counsel on determining why the radio button group component does not select a radio button when the button itself is clicked, but does select when the label is clicked.
