### ISSUE TITLE
[FE] Pre-Check-in Create Confirmation Page

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32777]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the confirmation page 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Create the HTML and pull in data from Redux to display the appointments
- [x] Reuse components from introduction page
- [x] Implement logic to show appropriate messages based on user responses
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by dcgoodwin2112** [comment]
Hi all, Question for the FE devs. The sketch file for the pre-check-in confirmation page has an informational alert with an icon, but it appears to be using a component variant that only has a background  color and no icon. Does anyone know if there is a recommended way for handling an icon like this within the design system, or would we need to build something custom for this one?

Sketch:  https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/bgQbOdj

Storybook: https://design.va.gov/storybook/?path=/story/components-va-alert--background-only

cc: @mdewey @brianseek @acrollet

**Comment by brianseek** [comment]
That is a good question @dcgoodwin2112 I would ask the UX team. If you do need to do something custom, I know that font-awesome is included in the project and you can insert icons using font-awesome utility classes.

**Comment by brianseek** [comment]
Screenshot for UX review @ytsaoca :
![localhost_3001_health-care_appointment-pre-check-in_introduction (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/a909d88f-f222-451d-8ae9-70b1bec8b941)

**Comment by ytsaoca** [comment]
@brianseek About the introduction page for multiple appointments, the content should be "Your appointments are on...
<img width="261" alt="Screen Shot 2021-12-08 at 11 40 28 AM" src="https://user-images.githubusercontent.com/90633685/145257436-68294781-4db8-430e-9047-e984b7a6a2dd.png">
"

**Comment by brianseek** [comment]
@ytsaoca Here is a screenshot update of the multi-appointment text on confirmation:
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (4).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/ce885c7b-242e-4a86-9872-cf6cfca0e256)

**Comment by ytsaoca** [comment]
@brianseek  Looks good!
