### ISSUE TITLE
[FE] Auth Profile: Add New Fields to Personal Information page - Edit State - Required Other Fields

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32775]
## Issue Description
As a Veteran, if I select an "other" option for Pronouns or Gender Identity and attempt to update without entering a value into the accompanying text field, I want to see an error message so that I know that entering a value is required.

### Tasks
- [x]  The design pattern and componenets should mirror what is currently in Production for Profile.  [Updated design files](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/design).
- [x] The logic should allow only one section to be edited at a time per the existing design pattern in Production.
- [x] Copy should reflect the [front end copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [ ] Selecting the "other" option for Pronouns will cause its accompanying text field to become required, but the red error state will not be displayed unless the user attempts to update without entering a value into the text field.
- [ ] If the user selects "other" for Pronouns, enters a value into the text field, then subsequently selects one of the pre-listed radio button, the accompanying text field shall be cleared and is no longer required.

Please use the below files for reference
- [Edit State - Required _Other_ Fields Sketch mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/MyzeRwb) - Note this error state is only shown if the user attempts to update without entering a value into the text field after selecting the "other" option for a given field.
- [UXPin Prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

## Acceptance Criteria
- [ ] Edit State - Required Other Field state is added to each applicable field.
- [ ] Features are behind flag to test on staging 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass

**Comment by zacharymorel** [comment]
@tmitchellgcio 

Here is an example in the vets-website repo of conditionally hiding inputs based on values from another input (in our case the check mark/ radio). https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/996/pages/areaOfDisagreement.js#L54-L77

Here are the docs on conditionally rendering fields. 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/form-tutorial-intermediate

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 64.

**Comment by adamwhitlock1** [comment]
I'd like to discuss this further. 

I think making the text field required when the 'other' radio is selected is a pretty easy ask, but clearing out the text field when a different radio is selected presents some challenges that I've kind of run into a wall on.

I wonder if conditionally hiding the field is completely off the table, because if we could conditionally hide the field, then we wouldn't have to really clear the field and could instead ignore its value when sending the data to the server when needed.

It seems like conditionally showing fields is really quite a common pattern in the forms library, so I'm wondering why we have been told explicitly not to on this work. There is even this section in the docs that speaks to the conditional showing of groups of fields

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms#conditionally-hiding-a-group-of-fields

**Comment by MarciMcGuireGCIO** [comment]
Makes sense. I will schedule a meeting with Platform so we can discuss.

**Comment by MarciMcGuireGCIO** [comment]
Updating this to note that we met with the Design System team, agreed on a design for the radio button groups and the checkbox groups that keeps the text field visible at all times, but also provides a visual connection between the text field and the "other" option.   I have entered a request for this for the Design System, but depending on their backlog and priorities, we may have to move forward with the design as @adamwhitlock1 has coded on Staging.

**Comment by MarciMcGuireGCIO** [comment]
Removed the `blocked` label and moved to Ready since the error state can be coded now that we've agreed on a design pattern.
