### ISSUE TITLE
[FE] Pre-Check-in - Create Demographics Page 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32774]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create the HTML
- [ ] pull data from redux 
- [ ] Save data to redux
- [ ] reuse what is possible from day of experience 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
@ytsaoca @niradatta1 @kristenmcconnell Here is a screen shot of the demographics page for review.
![localhost_3001_health-care_appointment-pre-check-in_ (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/41ae6243-5825-4eab-aab2-b5212aa790ab)

**Comment by brianseek** [comment]
Updated screenshot with new label style for review.
![localhost_3001_health-care_appointment-pre-check-in_next-of-kin (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/f3006808-a902-46f2-b0b1-8b48e854fd66)

**Comment by ytsaoca** [comment]
@brianseek  Looks good. Thanks!
'cc @niradatta1 @kristenmcconnell
