### ISSUE TITLE
[FE] Pre-Check-in - Create NOK Page 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32776]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Implement the Next of Kin Page

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create the HTML
- [ ] pull data from redux 
- [ ] Save data to redux
- [ ] reuse what is possible from day of experience 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Here are screen shots for review of the Next of kin page. **Note**: the `Start again` link is for local development only and won't show in production.
cc @ytsaoca @zach-park @niradatta1 
![localhost_3001_health-care_appointment-pre-check-in_next-of-kin.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/9218d2af-94e0-482f-8838-f1bee8d9cf3d)

**Comment by ytsaoca** [comment]
@brianseek  Looks good. Thanks!
'cc @niradatta1 @kristenmcconnell
