### ISSUE TITLE
[FE] Pre-Check-in - Create Intro Page 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32773]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

As a veteran pre-checking in for appointments, I want to land on a page that explains the pre-checkin process.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/847B453D-F19E-4D55-9EE6-C523E7408879)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the HTML, CSS, and content on the Introduction page. 

## Tasks

> this is a list of technical tasks that need for this ticket
- [ ] HTML
- [ ] Functionality 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Can visit the introduction page at the route /introduction
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
@ytsaoca @niradatta1 @kristenmcconnell Here are some screen shots of the intro page for review.
A couple of things to note:

- The blue box note has different padding and list spacing. This is using the web-component `va-featured-content` and the styling is out of the box for this component. Is this okay or should I override to match mocks.
- Similar to the featured content, the Accordions are using a web-component and I notice the line height of the button heading is a bit tighter by default. Should we override here?

![localhost_3001_health-care_appointment-pre-check-in_.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/fc5edd33-808e-401c-8ccd-e79743f7fe5f)
![localhost_3001_health-care_appointment-pre-check-in_ (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d78f2af9-66c1-4749-a716-11da468a5d42)

**Comment by ytsaoca** [comment]
@brianseek  Hi, thanks for the explanation. Please follow the design system. 
I'll double check the padding guidelines in the design system again.

BTW, we noticed that there is a "start gain" like at the bottom. Should we remove this? or what's your consideration to add this function? Thanks!


'cc @niradatta1 @kristenmcconnell

**Comment by brianseek** [comment]
@ytsaoca oh sorry I forgot to mention that part about `Start again` that is a local development only button that doesn't show on production. It's just a little helper for us in testing and development.
