### ISSUE TITLE
[FE] Auth Profile: Add New Fields to Personal Information page - Read-Only State 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32771]
## Issue Description
As a front end developer, I want to build the Read-Only state of the VA.gov profile screen so that users have the ability to view data retrieved from the MPI database, including personal information they have already entered into a field.   

### Tasks
- [x]  The design pattern and componenets should mirror what is currently in Production for Profile vs.  the styles shown in the mock-ups as those were based off an outdated Sketch file.  Pages should be based on the [updated design files](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/design).
- [x] The logic should allow only one section to be edited at a time per the existing design pattern in Production.
- [x] Copy should reflect the [front end copy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [x] Each question will require a default "blank" state that provides some information advising the user to click edit to provide info.  [See exact copy here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md#personal-information-page---blank-state).
- [x] Add "Do not wish to disclose" option to Pronouns and Sexual orientation sections.   [See exact copy here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md).
- [ ] Selecting the "other" option for Pronouns or Sexual Orientation will make that question's accompanying text field required if the user attempts to update.
- [x] Changing Preferred Name will not affect the MPI-derived name shown in the "nametag" at the top of the page.

Please use the below files for visual reference
- [Read-Only State](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/Myd9jnw)
- [UXPin Prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

## Acceptance Criteria
- [x] New Fields are added
- [x] Features are behind flag to test on staging 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
Moving this back to Ready; Zach is going to try to complete the Edit state #32775 instead since he has not yet created the test data.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Have a look at this on Staging!

**Comment by MarciMcGuireGCIO** [comment]
Making a note that Christina, Adam and I discussed and all agree that Read-Only would show the text that the user entered as the "other" value, but we would not show the "other not listed" info.   We would also transform any abbreviated/obscure values that are returned from MPI when we read in the data.

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO I completed this and have it deployed to staging. The only kicker is that we can't really test this in staging since we don't have the back end setup to provide responses yet, soooo I have e2e tests built to simulate the server response and have tested it locally as best I can.

**Comment by MarciMcGuireGCIO** [comment]
Ok, thank you!
