### ISSUE TITLE
[FE] Pre-Check-in - Create Validate Page

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32772]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the page, do the POST for validation, hitting the same endpoints

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Reuse and implement the same functionality from day of experience
- [x] This only focuses on the validation API calls and validate page mock ups
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Screenshot for review @ytsaoca:
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/5c79a7ef-136a-4455-ad81-4270a1daf0cb)

**Comment by ytsaoca** [comment]
@brianseek  
Looks good!
