### ISSUE TITLE
[FE] Pre-Check-in - Integrate with Mock API 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32781]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

This ticket is o track the integration of redux, the API, and components. 

## Tasks

> this is a list of technical tasks that need for this ticket

### First PR

- [x] using the id in the URL, check for sessions on the landing page load
- [x] if valid, load data and store it into redux
- [x] save to session storage
- [x] if already auth, redirect to the intro page
- [x] if invalid, redirect to the error page

### Second PR

- [x] POST token on validate page
- [x] add error handling on failure

### Second.5 PR

- [ ] Figure out when to load payload data flow

### Third PR

- [ ] Save data on the yes/no click demographics
- [ ] Save data on the yes/no click NoK

### Fourth PR

- POST data after saving data on NoK

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Also adding in https://github.com/department-of-veterans-affairs/va.gov-team/issues/33195 to this work as well
