### ISSUE TITLE
[FE] Pre-Check-in - Error Page

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#32780]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

The error page should be created. We have two error states

- Failed API Calls
- Failed Validation 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Reuse the day of check in error page, moved to shared folder
- [x] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Screenshot for review:
![localhost_3001_health-care_appointment-pre-check-in_ (3).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/9baa70a8-b09b-467a-b0df-7f7d6e71eca5)
