### ISSUE TITLE
Add number of results to header for Community care providers and pharmacies 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32811]
## Issue Description
During validation of [Add # of results to FL results header (3b) #11149](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11149), the number of total results for community providers and pharmacies increased as the page changed. As a result, we suppressed the number of results for all community care searches until the issue could be resolved. 

## Tasks
- [x]  Add the number of results to the header for community providers and pharmacies
- [x]  Update existing tests as needed

## Acceptance Criteria

- [ ] For results of ten or less, the header can say "Showing 1-x results for ..."
- [ ] When the user goes to different page of results, the display number updates
- [ ] If the user initiates a new search, the display number updates
- [ ] Veterans using screen readers understand the context of the search results list
- [ ] Tests have been updated/added

The following existing functionality is maintained

- [ ] Heading includes user search criteria (Search results for near "location parameters")
- [ ]  Heading updates with new search criteria if new search is initiated
- [ ]  Only the standard error displays if no search results are found (no heading displays)
- [ ]  Results summary header displays when search results are returned.
- [ ]  Results summary header does not prematurely load (No heading is seen while a search is in progress)
- [ ]  Heading levels do not skip
- [ ]  Ensure focus goes to results summary header consistent with user flow
