### ISSUE TITLE
Research plan to discover Veteran facing labels for VBA services 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32819]
## Issue description 
A recent data call was done to collect the list of services available at each benefit facility and/or delivery location. This list of services was crosswalked with the list of VBA services available in the Facility Locator with the [Resources and Support area](https://www.va.gov/resources/) to find services for which Veteran facing labels may have already been discovered (#30836). 
[The results of this crosswalk is available here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/discovery-sprints/taxonomy/VBA-services-discovery.md)

**VBA services available at Benefit facilities as collected during recent data call**

- Applying_for_Benefits
- Burial_Claim_assistance
- Disability_Claim_assistance
- eBenefits_Registration
- Education_and_Career_Counseling
- Education_Claim_Assistance
- Family_Member_Claim_Assistance
- Homeless_Assistance
- VA_Home_Loan_Assistance
- Insurance_Claim_Assistance
- IDES
- Pre_Discharge_Claim_Assistance
- Transition_Assistance
- Updating_Direct_Deposit_Informa
- Vocational_Rehabilitation_Emplo

We need to discover Veteran facing labels for the named services and understand what might be under the general "Other" category so that we can make searching for theses services more intuitive on Facility Locator. 

It's important to note that these "benefit" services can be offered at benefit facilities but also by VBA representatives working on VA Medical center campuses or within Vet Centers. We should take care not to limit our discovery to benefit facilities only. 

## Other background info

IDES - more info available at https://benefits.va.gov/PREDISCHARGE/ides.asp

----
 
It may help to look at how some benefit services are represented on va.gov home page and subsequent pages

---

The following areas were discovered in an audit of Contact Call Center data regarding the most commonly asked questions

- File a claim, check my claim status
- Request or help with Benefit letters
- Add a dependent
- Report a death, First Notice   of Death (FNOD)
- Request information, get help with Freedom of Information, Privacy Act (FOIA)
- Get disability pay
- Apply for GI Bill, education benefits
- Get help with payment and debt questions
- Update my bank account information

The following resources may be useful in determining scenarios/tasks

- [Disability benefits](https://www.va.gov/disability)
- [Education benefits](https://www.va.gov/education)
- [Housing assistance](https://www.va.gov/housing-assistance/)
- [Careers and employment assistance](https://www.va.gov/careers-employment)
- [Life insurance benefits](https://www.va.gov/life-insurance)
- [Pension benefis](https://www.va.gov/life-insurance)
- [Burials and memorials](https://www.va.gov/life-insurance)
- [Benefits for spouses, dependents, survivors, and family caregivers](https://www.va.gov/family-member-benefits)

---

Relevant "Associated VA services"  as listed on the [Veteran journey](https://www.blogs.va.gov/VAntage/wp-content/uploads/2020/02/Veteran-Journey-Map.pdf) - may be useful
<details> 
<summary> Associated VA services </summary>
- GI Bill
- VA Home Loan
- Life insurance
- Disability Health Condition
- Compensation & Pension Exam
- Pre-discharge Program (Disability Compensation)
- Healthcare
- Vocational Rehab & Employment
- Career Center
- Vet Center
- VA Health Care
- MyHealtheVet
- Post-Deployment Clinic
- Psychosocial Rehabilitation & Recovery Services
- Skills Translator
- Career Center
- Resume Builder
- Educational & Vocational Counseling
- Disability Compensation
- Veterans Job Bank
- Resume Builder
- VA Employment
- VA Veteran’s Pension
- Burial Benefits
- Burial Allowance
- Survivor’s Benefits
</details>

---

For what it's worth, this list of services is available on [benefits.gov once VA has been selected](https://www.benefits.gov/agencies/U.S.%20Department%20of%20Veterans%20Affairs)
<details> 
<summary> Screenshot of dropdown </summary> 
![image](https://user-images.githubusercontent.com/55411834/141534029-c80ce2df-8fca-47ed-86a0-cf90532d37cc.png)

</details>

## Goals

- [ ] Gain understanding about Veteran mental models for the identification/organization/classification of VBA services
- [ ] Answer questions such as
       - What tasks do Veterans do at benefit facilities? What are the words they use to describe them? 
       - How do Veterans categorize these services? 
       - How do Veterans search for benefit-related services and the locations where they can receive them? 
       - What other personas (caregivers? beneficiaries?) should be considered for this taxonomy?

## Tasks
- [ ] Identify the appropriate method for seeking input on VBA services _(update: given limits on the number of research participants, we determined a set of SME interviews may be a good first step for this)_

## Acceptance Criteria
- [ ] Research plan for review/feedback by research/design team peers

**Comment by mmiddaugh** [comment]
[Research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/research-plan-benefits-taxonomy-SME-interviews.md)
Convo guide to be created in #33440
