### ISSUE TITLE
Create 2022 DIC rates page for spouses and dependents

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32826]
## Issue Description
DIC rates change for 2022 as of December 1, 2021. We need to create a new page in Drupal with the 2022 rates for spouses and children. When we do this we also need to make the 2021 page a past rates page. 

Here is the rates information to input:

[https://app.zenhub.com/files/133843125/2353d9f6-3d0e-4209-8001-deef832f5457/download](https://app.zenhub.com/files/133843125/2353d9f6-3d0e-4209-8001-deef832f5457/download)

## Tasks
- [x] Create 2022 rates page (Selina)
- [x] Check numbers against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review 2021 past rates page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] 2022 DIC rates page for spouses and dependents is live on the site
- [x] 2021 past DIC rates page for spouses and dependents is live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

2022 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=1012
Past rates: 2021 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=38663
Past rates: 2020 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=11018
Past rates: 2019 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=6799

**Comment by RLHecht** [comment]
These pages have all been reviewed. Will publish with the rest of the rates.

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
