### ISSUE TITLE
Create Document for Adding GIDS users 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#32822]
## Issue Description
As an Operations team member, I want to know how to add users to the GIDS database(s).

---
## Tasks
- [x] Publish doc to Confluence outlining this process

## Acceptance Criteria
- [x] Document exists in Confluence clearly illustrating the steps for adding GIDS users to the GIDS database(s)
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Doc published: https://vfs.atlassian.net/wiki/spaces/OT/pages/1976205313/Add+GIDS+Users
