### ISSUE TITLE
[AWS / IAM] Create service account that can be used with GitHub Actions for VA Virtual Agent

### ISSUE THREAD

**Issue by rwilliams-oddball** [department-of-veterans-affairs/va.gov-team#32825]
## Description
The VA virtual agent team is looking to move secrets from the [va-virtual-agent repo](https://github.com/department-of-veterans-affairs/va-virtual-agent) in Github to AWS.  The team needs an AWS service account that can be used in connection with GitHub Actions. 

## Background/context 

- https://dsva.slack.com/archives/CBU0KDSB1/p1616537670033400?thread_ts=1616535951.030400&cid=CBU0KDSB1
- The pattern commonly in use is "svc-gha-<teamname>" or similar. 
- The bot uses a Q&A maker, grabs the files, and then publishes them through a pipeline 
- It gets deployed using Microsoft GCC - a no-code implementation 
- The secrets are only used during the CI portion of the pipeline using GitHub Actions 

## Technical Information 
- Example [GHA snippet ](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/aws-test-frontend-role.yml#L16-L27)

---
## Tasks
- [x] Create AWS service account for this team/repo 
- [x] Securely download or document AWS secret key and access key 
- [x] Provide the keys to the va-virtual-agent team so that they can add them to their GH action 
- [x] Configure permissions for this service account to a path in parameter store 

## Acceptance Criteria 
- [x] Service account can securely connect to AWS parameter store 
- [x] Set up process is documented in Confluence

**Comment by jhouse-solvd** [comment]
@jgacek - It appears that there might be open environment access requests for some developers on your team. That access will be needed in order to manage values in Parameter Store. 

So that we can support you appropriately, can you also let us know what is your ideal timeline for getting this functionality set up, ie what is the level of urgency? 

Typically, for a new setup/configuration such as this, the process is to prioritize issues based on need and urgency, and then work them into an upcoming sprint. We are currently in the middle of a sprint now, and coming up on planning next week.

Let us know what you need and we'll be happy to help.

**Comment by jgacek** [comment]
This isnt so urgent that we would need it immediately but it would be nice to get done sooner rather than later. If you dont have the bandwidth to spare in your next sprint we could wait a sprint

**Comment by jhouse-solvd** [comment]
@jgacek - Okay, that's super helpful. We'll discuss as a team next week during sprint planning so that we can give you an ETA.

**Comment by jhouse-solvd** [comment]
@jgacek - We've got a pretty full load for the sprint that runs from Nov25 - Dec7, but will pick this up in the next.

**Comment by jgacek** [comment]
@mydesignrocks Has there been movement on this issue?

**Comment by jhouse-solvd** [comment]
@jgacek - Sorry for the delay here. Sri has been out this week and the Ops team has been a high volume of support needs. Alina and I chatted and I've set a reminder for us to jump on this on Monday. Thank you for your patience, and we'll follow up then.

**Comment by jhouse-solvd** [comment]
Discussion w/ Jacob in [this thread](https://dsva.slack.com/archives/CJYRZK2HH/p1640110554061300)

**Comment by jhouse-solvd** [comment]
We spoke with the team today to clarify the requirements. @mydesignrocks - please configure as time allows and communicate with the team through this issue wherever possible.

**Comment by mydesignrocks** [comment]
This is now complete and should be available for use with github action (I will include the details in the issue as well)
service account: svc-gha-va-virtual-agent-user
paramstore details for aws access and secret keys:

**Comment by mydesignrocks** [comment]
![image](https://user-images.githubusercontent.com/69813558/147274916-6eb953d3-9bf5-41ae-bc8f-f1f2fe18026e.png)

**Comment by jhouse-solvd** [comment]
@mydesignrocks - Please check off tasks and acceptance criteria (you can re-write them for accuracy as needed).

**Comment by jhouse-solvd** [comment]
@jgacek @khathuynh-tw @justin-trieu - Please confirm if this is working as expected and meets your needs. Thank you!

**Comment by jgacek** [comment]
@jhouse-solvd Hi we've been on break but we're all back now we'll check today if its working

**Comment by jbritt1** [comment]
@jgacek, this working as expected?

**Comment by jgacek** [comment]
What we are waiting for are the AWS_SECRET_ACCESS_KEY & AWS_SECRET_ACCESS_KEY to store as secrets in our repo so we can use them in the github actions. After we have that and we confirm they work as intended this should be done

**Comment by jbritt1** [comment]
> What we are waiting for are the AWS_SECRET_ACCESS_KEY & AWS_SECRET_ACCESS_KEY to store as secrets in our repo so we can use them in the github actions. After we have that and we confirm they work as intended this should be done

Can you add the @department-of-veterans-affairs/vsp-operations team as admins on the repository so I can add those as time allows please?

**Comment by jgacek** [comment]
> > What we are waiting for are the AWS_SECRET_ACCESS_KEY & AWS_SECRET_ACCESS_KEY to store as secrets in our repo so we can use them in the github actions. After we have that and we confirm they work as intended this should be done
> 
> Can you add the @department-of-veterans-affairs/vsp-operations team as admins on the repository so I can add those as time allows please?

I've added vsp-operations as admins

**Comment by jbritt1** [comment]
Added: 
![image](https://user-images.githubusercontent.com/56260532/150210555-7529d678-4582-4bc9-8973-d8fa01f95e39.png)

**Comment by jgacek** [comment]
Thanks @jbritt1 we'll go ahead and test and we'll come back with whether we are successful or not

**Comment by jgacek** [comment]
@jbritt1 we were able to use the keys to grab a secret we created on the path `dsva-vagov/va-virtual-agent/*`

**Comment by jbritt1** [comment]
Thanks to @jgacek confirming things are working as intended at this time, closing. Please reopen if any issues arise.
