### ISSUE TITLE
Create 2022 DIC rates page for parents

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32828]
## Issue Description
The 2022 DIC rates for parents take effect December 1, 2021. We need to create a new page in Drupal with the information. We also need to change the 2021 page into a past rates page. 

Here is the new rate information:

[https://app.zenhub.com/files/133843125/b2799812-063c-4658-83d1-a5637fe75828/download](https://app.zenhub.com/files/133843125/b2799812-063c-4658-83d1-a5637fe75828/download)

## Tasks
- [x] Create 2022 Parents DIC rates page (Selina)
- [x] Check numbers against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] 2022 DIC rates page for parents is live on the site
- [x] 2021 DIC past rates page for parents is live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

2022 VA DIC rates for parents: http://preview-prod.vfs.va.gov/preview?nodeId=1013
Past rates: 2021 VA DIC rates for parents: http://preview-prod.vfs.va.gov/preview?nodeId=39130
Past rates: 2020 VA DIC rates for parents: http://preview-prod.vfs.va.gov/preview?nodeId=11013
Past rates: 2019 VA DIC rates for parents: http://preview-prod.vfs.va.gov/preview?nodeId=6797

**Comment by RLHecht** [comment]
These pages are all checked and reviewed. Will publish with rest of the rates pages.

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
