### ISSUE TITLE
Create 2022 Veterans Pension rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32830]
## Issue Description
The 2022 rates for Veterans Pension go into effect December 1, 2021. We need to create a new 2022 Veterans Pension rates page and turn the 2021 Veterans Pension rates page into a past rates page. 

2022 rates info:
[https://app.zenhub.com/files/133843125/4207e01a-ccae-47e6-ba3b-f3621bfe23ec/download](https://app.zenhub.com/files/133843125/4207e01a-ccae-47e6-ba3b-f3621bfe23ec/download)

## Tasks
- [x] Create 2022 Veterans Pension rates page (Selina)
- [x] Check numbers against doc provided and review page (Randi)
- [x] Create 2021 Veterans Pension past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that pages are live (Randi)

## Acceptance Criteria
- [x] 2022 Veterans Pension rates page is live on the site
- [x] 2021 Veterans Pension past rates page is live on the site

**Comment by RLHecht** [comment]
I've reviewed 2022 and all past rates pages. Waiting to publish with the other rates pages.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
