### ISSUE TITLE
Create 2022 Survivors Pension rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32832]
## Issue Description
The 2022 rates for the Survivors Pension go into effect December 1, 2021. We need to create a new page in Drupal for the 2022 rates and turn the 2021 rates into a past rates page. 

New info for the 2022 rates:
[https://app.zenhub.com/files/133843125/a5c9d630-f8ce-4f3b-8409-346148f8b18f/download](https://app.zenhub.com/files/133843125/a5c9d630-f8ce-4f3b-8409-346148f8b18f/download)

## Tasks
- [x] Create 2022 Survivors Pension rates page (Selina)
- [x] Check numbers against doc provided and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] 2022 Survivors Pension rates page is live on the site
- [x] 2021 Survivors Pension past rates page is live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

2022 VA Survivors Pension benefit rates: http://preview-prod.vfs.va.gov/preview?nodeId=589
Past rates: 2021 VA Survivors Pension benefit rates: http://preview-prod.vfs.va.gov/preview?nodeId=39304
Past rates: 2020 VA Survivors Pension benefit rates: http://preview-prod.vfs.va.gov/preview?nodeId=11020
Past rates: 2019 VA Survivors Pension benefit rates: http://preview-prod.vfs.va.gov/preview?nodeId=6861

**Comment by RLHecht** [comment]
These pages are all reviewed. Will publish with the rest of the rates pages.

**Comment by RLHecht** [comment]
@lunascoop Here is the new document with updates highlighted in yellow from the stakeholder. [https://app.zenhub.com/files/133843125/c9802f33-dc55-4a00-9fd2-3e5178fad0e7/download](https://app.zenhub.com/files/133843125/c9802f33-dc55-4a00-9fd2-3e5178fad0e7/download)

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
