### ISSUE TITLE
[BE] Profile: Personal Information Revision - Update Personal Information to include demographics

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#32848]
## Issue Description
As a Backend engineer I want to update the Personal Information controller and Swagger docs to include demographic data (pronouns, gender identity, preferred name, sexual orientation) in the response.

---
## Tasks
- [ ] Update PersonalInformationController#show to include PI data
- [ ] Update PersonalInformationController#show Swagger docs
- [ ] Create spec to ensure PI data is included in response

## Acceptance Criteria
- [ ] Create spec to ensure PI data is included in response
- [ ] Test Review Instance to ensure PI data is included in response

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
Blocked until we have specs from MPI

**Comment by Samara-Strauss** [comment]
Removing @lihanli from this work, as he will be focusing on the on-site notifications integration. Tom can own this now, though he shouldn't hesitate to ask Lihan questions as needed.

**Comment by tpharrison** [comment]
This ticket is being zeroed out and closed since it is being decomposed into a set of smaller, more manageable tickets.
