### ISSUE TITLE
[MCP] Create HTML statements page

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#32846]
## Issue Description
Because the PDF statements are inaccessible, we've created HTML versions of the statements. 

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/f0abcdd1-6df2-4a05-bbe7-3337fe775b3f)

---
## Tasks
- [ ] Update detail pages to include the H2 of "Your statements" and subsequent links found [here](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa?_gl=1*rkal90*_gcl_aw*R0NMLjE2NDMwMzc3MjYuQ2owS0NRaUF1Ym1QQmhDeUFSSXNBSldOcGlNMVo1NGR3LW9ZQnBONHktQTBuVHlyVW1MS3RscWZxRldaMmd1ZG0wcmFqSWp0OVl1NjZIQWFBc0NvRUFMd193Y0I.#/pages/146746515/simulate/sitemap?mode=i)
- [ ] Create HTML statement page found [here](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i)
- [ ] Review pages with design for QA

## Acceptance Criteria
- [ ] Detail pages updated 
- [ ] HTML statement page created
- [ ] UI reviewed by design
