### ISSUE TITLE
Top tasks for Indiana health care system VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#32844]
## Issue Description
The Indiana health care system does not offer the online scheduling available in most other VAMC systems. They may be using a completely different system - or none at all. 

This means top tasks for "make an appointment" are either directed to the wrong url or completely irrelevant to the Veterans receiving care in this system. 

---
## Tasks
- [ ] Work with Stan and/or SME for health care system to understand what options are available
- [ ] Determine best "top task" options for Veterans in this system and associated links

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by mmiddaugh** [comment]
no longer needed
