### ISSUE TITLE
Update asynch midpoint review request to reflect the review could be changed to synchronous

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#32845]
## Issue Description
Sometimes asynch midpoint reviews are too complicated or need to have a discussion around them. The collab cycle team should be able to request a team to change to synchronous. We need to update documentation with details like timing and how to request the change

---
## Tasks
- [ ] Add some text to the "asynch" request option stating that Collab Cycle team has the right to request a synchronous review if the subject matter is overly complicated and/or sufficient documentation is not provided in the GH ticket and external documentation. 
- [ ] Update internal documentation with the process to request the change

## Acceptance Criteria
- [ ] VFS PM will know that an asynch midpoint review may change to synchronous
- [ ] The external documentation is updated 
- [ ] Product support will know how to request the change
- [ ] Product support will know when to request the change
- [ ] The internal documentation is updated
- [ ] It has been communicated (through the appropriate channels) to VFS teams that Platform has the right to request a synch review. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jimuhh** [comment]
@shiragoodman I wrote this up on [this draft page. ](https://vfs.atlassian.net/l/c/prcaYiTg) LMK what you think

**Comment by shiragoodman** [comment]
@jimuhh I reviewed the draft doc and it looks great! I made a couple minor changes (modified wording and changed the note to have the purple background similar to other notes on the page).

Could we also update the Midpoint Review gh template to include a similar message? You can create a PR and assign me as an approver.

In addition, a recent request came through to modify some of our guidance around the "Objective" in the Midpoint Review document. Since you already have a draft available, could you take a look at  ticket #33952 to see if you could make the changes requested? Please let me know if you have questions.

**Comment by jimuhh** [comment]
Sure. I'll have a look at both.
