### ISSUE TITLE
Objective: Improving the Legal Representative Experience

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#32852]
## User Story

As a legal representative of a veteran I would like to know which files I should, and should not, upload to prove I have the ability to make healthcare decisions on behalf of a veteran. 

## Expected Behavior

- Decreased form drop off at file upload
- Minimization of incorrect form(s) uploaded

### What must be true in order for you to consider this epic complete? 
- [x] Research usability & Content Comprehension
- [x] Design 
- [x] Improvements added to 10-10CG
- [x] Staging review completed and approved
- [x] ES accepts 10-10CG submissions 

### Tickets to be created/groomed:
- [x] Feature turned on in Staging, Prod 
- [x] Collab Cycle request (PM)
- [x] Analytics 
  - [ ] Update tags 
  - [ ] Validate data flow 
- [x] QA (Collab Cycle)
  - [ ] Generate use cases (Engs)
  - [ ] Write test cases (QA)
  - [ ] Release plan complete
- [x] Go/No-Go
  - [ ] Logging
