### ISSUE TITLE
[UNPLANNED] Search Rep (No Results page)

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#32857]
## Story
If the veterans' search doesn't provide any results, we need to be able to inform them of this and provide them with a way to restart their search

## Considerations
[Mockup](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/09Ov7OA)
* Redux is not yet fully implemented for these pages

## Tasks
- [x] Make any needed changes to redux
- [x] Implement design features from provided mockup

## Acceptance Criteria
- [x] Redux has been adjusted
- [x] The Veteran has a notification or some mechanism to take another action
- [x] A PR has been requested for merging
