### ISSUE TITLE
Implement LGY text changes to COE prototype

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#32853]
### Background
VA Policy Leadership has completed their review of the Certificate of Eligibility prototype. There are some revisions needed; generally they include:
- Change lingering instances of "apply" to "request" throughout
- Move Native American Direct Loan (NADL) line to last on the public landing pages
- Remove mentions of "letters in the mail" from Your COE screen

### Tasks
- [x] Revise text per LGY-provided PDF
- [x] Notify Content team that "final" text is available for review

### Acceptance criteria
- [x] Text revisions implemented in COE prototype

**Comment by sporeboy** [comment]
Text revisions implemented in COE UXP prototype [starting here.](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312)
