### ISSUE TITLE
Migrate ProgressBar

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32868]
## Description

Dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/32867

Once the migration script is available for `<ProgressBar>`, it needs to be run in the following `vets-website` directories:

- `src/platform/forms-system`
- `src/applications/claims-status`

![image](https://user-images.githubusercontent.com/2008881/141847446-daab13a0-c85b-4b8f-a675-12dc06040631.png)

## Tasks

- [ ] Run migration script in `src/platform/forms-system`
- [ ] Open PR to merge forms changes
- [ ] Run migration script in `src/applications/claims-status`
- [ ] Open PR to merge claims-status changes

**Comment by k80bowman** [comment]
For the PR for claims-status, I would recommend reaching out to the team who owns that code to ask if they would prefer handling the migration or if they would prefer that we handle it. If we handle it, we will need to make sure to run the application and test that the progress bar is working in their application the way that it should.
