### ISSUE TITLE
Develop Progress Bar Web Component

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32866]
## Description

We currently have [`<ProgressBar>`](https://github.com/department-of-veterans-affairs/component-library/blob/996d31551d9c628c9b78794e33d8a1d50548d82c/packages/react-components/src/components/ProgressBar/ProgressBar.jsx#L5) which is used in two files:

![image](https://user-images.githubusercontent.com/2008881/141846734-5afdd8dd-6ed9-4059-b0b6-379381448eeb.png)

We should have a `<va-progress-bar>` replacement.

## Tasks

- [ ] `<va-progress-bar>` is written
- [ ] E2E tests are written
- [ ] Storybook is updated

**Comment by andresriveratoro** [comment]
React Component that accepts 3 props:

percent: number (required)
label: string - default: ‘Working'
enableAnalytics: boolean

Each time the component re-renders, it checks to see if analytics are enabled

If analytics are enabled, then it checks if the percent is 0 or 100, if it is, it dispatches an analytics event

Styling:
classNames
dynamic styling applied to the bar’s width based on percent prop
