### ISSUE TITLE
Migrate SegmentedProgressBar

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32864]
## Description

Dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/32862

Once the migration script is available for `<SegmentedProgressBar>`, it needs to be run in the following `vets-website` directories:

- `src/platform/forms`
- `src/applications/letters`

![image](https://user-images.githubusercontent.com/2008881/141845973-e0c6b056-e856-4842-813f-b8b1f142ca88.png)

## Tasks

- [ ] Run migration script in `src/platform/forms`
- [ ] Open PR to merge forms changes
- [ ] Run migration script in `src/applications/letters`
- [ ] Open PR to merge letters changes

**Comment by pdavies88** [comment]
Draft Message: https://dsva.slack.com/archives/G01BJ3ESXL4/p1639503689394800

**Comment by k80bowman** [comment]
I would recommend reaching out to the team who owns the letters application to ask if they would prefer handling the migration or if they would prefer that we handle it. If we handle it, we will need to make sure to run the application and test that the progress bar is working in their application the way that it should.

**Comment by pdavies88** [comment]
Talked with Robin on the vsa-claims-appeals team and I will be handling the migration for them for the `SegmentedProgressBar` in `applications/letters`

**Comment by pdavies88** [comment]
Corresponding PR for Documentation Update: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/713
