### ISSUE TITLE
Migrate CollapsiblePanel to accordion Web Component

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32872]
## Issue Description

`<CollapsiblePanel>` is still used in a few places in `vets-website`, and we have the `<va-accordion>` replacement available.

![image](https://user-images.githubusercontent.com/2008881/141849176-f43727ba-4fcf-45ff-8387-0763cca30929.png)

We had a [previous ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22945) for this migration, and we ended up not building the automated component migration script to work for accordions. This is because the Web Component version is a composed component: a `<va-accordion>` wrapper with one or more `<va-accordion-item>` children. The `<va-accordion-item>` is what `<CollapsiblePanel>` represents.

Completing this migration will allow `<CollapsiblePanel>` to be removed, and the teams will get some accessibility enhancements along with any future upgrades that are made to the web component, since development on the deprecated `CollapsiblePanel` is halted.

---
## Tasks
- [ ] Migrate `claims-status` app
- [ ] Migrate 526EZ form app
- [ ] Migrate `letters` app
- [ ] Migrate "My Health Account Validation" app

**Comment by k80bowman** [comment]
Ideally we will be able to work with the relevant teams and get them to complete this work. This ticket is more about coordinating with those teams than completing the work ourselves.

**Comment by bkjohnson** [comment]
The "My Health Account Validation" app has [been removed](https://github.com/department-of-veterans-affairs/vets-website/pull/19343), so it no longer needs to be migrated.

**Comment by bkjohnson** [comment]
There is an old [draft PR for `letters`](https://github.com/department-of-veterans-affairs/vets-website/pull/17562) which handles the migration. I used this for some early testing.

**Comment by caw310** [comment]
Moving to Reviewed/Needs prioritizing as we have paused building web components for now.

**Comment by pdavies88** [comment]
@k80bowman Talking points for Monday:
- Created a manual migration guide: https://vfs.atlassian.net/wiki/spaces/DST/pages/2127527996/Manual+Component+Migration+Guide
- CollapsiblePanel is built slightly differently than `va-accordion-item` specifically it is bordered by default and has the option to be borderless via a prop. However `va-accordion-item` is borderless by default and needs a parent component to determine if it should be bordered
- We do not currently have `va-accordion-item` broken out into its own story and we may want to do that for this use case to help surface props and direct implementers to a specific location
- We currently have 2 ways to set the headline and level on `va-accordion-item` this may lead to confusion with implementers and we may want to choose just 1

**Comment by pdavies88** [comment]
Per conversation migration should `va-accordion` not `va-accordion-item` also going to leave the 2 ways to do the headline to provide support to legacy code
