### ISSUE TITLE
[BE] Pre check-in: Implement GET method to show the demographics information to users

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#32875]
## Description
As a veteran, I want to see my demographics information when I go through the Pre check-in steps

## Tasks
Vets-api should query LoROTA with a minimally authenticated user's UUID and return the Pre-Check-In data for an appointment group

- [ ] Implement the GET route `/check_in/v2/pre_check_in/<:uuid>`
- [ ] Implement a LoROTA service method to fetch demographics data
- [ ] Use an existing serializer or create a new one to handle the demographics data and return
- [ ] Implement a model layer as necessary to handle the Pre-Check-in response
- [ ] Add statsd metrics
- [ ] Add or modify swagger docs

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by randomsync** [comment]
See relevant discussion here: https://dsva.slack.com/archives/C02G6AB3ZRS/p1637265983426700
