### ISSUE TITLE
[BE] Pre check-in: Implement the POST method for users to confirm their demographics data

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#32876]
## Description
As a veteran, I want to be able to confirm that the demographics data during pre check-in is correct and doesn't need to be updated.

## Tasks
- [x] Implement the create method for PreCheckIns controller `/check_in/v2/pre_check_in/<uuid>`
- [x] Implement a CHIP service (new or existing) method to POST Pre-Checkin status for an appointment group
- [x] Handle the response
- [x] Add or modify swagger docs
- [x] Add statsd metrics

## Acceptance Criteria
- [ ] Deployed and tested on staging.

**Comment by randomsync** [comment]
Per discussion with Stephen, the responses to Next of Kin and Demographics will need to be captured separately by vets-website and passed to vets-api. vets-api will make a single call to the CHIP endpoint to confirm.

**Comment by randomsync** [comment]
See relevant discussion here: https://dsva.slack.com/archives/C02G6AB3ZRS/p1637265983426700
