### ISSUE TITLE
Research synthesis and reporting: Outreach & Events (Filtering/Recurring Events)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32885]
## Description 
Conduct post research synthesis reporting for Outreach and Events filtering and recurring events research.

## Tasks 
- [x] Clean up notes spreadsheet 
- [x] Write topline summary and share out with team **(Determine Stretch Goal)**
- [x] Do data analysis/synthesis of data collected from research  
- [x] Write research report

**Comment by cindymerrill** [comment]
Finished drafting the topline summary. Waiting for @brianalloyd to review it before sharing with the team and Dave Conlon.

**Comment by cindymerrill** [comment]
Revised my topline summary per feedback from Brian and posted it on slack: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/topline.md

Started working on full report and data synthesis. Drafted enough to discuss preliminary recommendations with the team tomorrow (Tue).

**Comment by cindymerrill** [comment]
Discussed recommendations for MVP with team, made decisions about what will be implemented, and added notes about this in the report.

**Comment by cindymerrill** [comment]
Done writing research report, which I'll share on Slack tomorrow morning: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/research-findings.md
