### ISSUE TITLE
Determine Product Use/Test Cases for Outreach & Events (Filtering/Recurring Events)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32889]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Tasks
- [x] FE/Product work on developing baseline use/test cases to pass to CMS
- [x] Document [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Product%20Use%20Cases.md)
- [x] PM send to CMS team, along with QA team for review/Action.

**Comment by brianalloyd** [comment]
Completed Product use cases, and plan to complete test cases in separate ticket in support.  Close out now.
