### ISSUE TITLE
Conduct Research: Outreach & Events (Filtering/Recurring Events) 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32883]
## Description 
Conduct research with Veterans and caregivers for outreach and events (filtering/recurring events) 

## Tasks 
- [x] Print conversation guide
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Post debrief/updates on slack
- [x] Debrief research sessions into note-taking spreadsheet
- [x] Download recordings
- [x] Download notes from Perigean and remove PII
- [x] Download final participant list from Perigean
- [x] Change display name of Perigean Zoom account back to what it was (DSVA)
- [x] Change "hide profile pictures" setting back to OFF
- [x] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Today I had one research participant and 2 no-shows

**Comment by cindymerrill** [comment]
Moderated 8 research sessions. Moving on to writing a topline summary and will close this ticket.
