### ISSUE TITLE
Move dashboard-cli repo into component-library monorepo

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32890]
## Description

The Design System team has the [`design-system-dashboard-cli` repo](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli) which is responsible for counting instances of our React components and Web Components in `vets-website` and `content-build`. We have decided to move this into the `component-library` monorepo in order to consolidate and have less repos to manage. We will also be able to benefit from existing CI for tests (related ticket https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/620).

---
## Tasks
- [ ] Create new package in [`component-library` monorepo](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages)
  - [ ] New package should be `private` in order to not interfere with automated publishing
- [ ] Code is copied from [`design-system-dashboard-cli`](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli) repo into new package directory
  - Preserving git history is not required
- [ ] [`design-system-dashboard-cli`](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli) repo is archived
