### ISSUE TITLE
Collect customer satisfaction ratings - Launch Q4 Platform Satisfaction Survey

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#32897]
## Issue Description
Launch the Platform satisfaction survey to VFS team members so we can measure Q4 customer satisfaction and gather feedback to inform quarterly planning.

[Instructions](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)

---
## Tasks
- [x] Setup study in optimal workshop
- [x] Announce in Slack
- [x] Recruit respondents in Team of Teams and other channels

## Acceptance Criteria
- [x] We have a survey response rate ~20%. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jchasia-adhoc** [comment]
Survey complete
