### ISSUE TITLE
[GitHub Actions] Design system needs a bot and token for NPM publishing

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#32892]
## Description

The Design System team is publishing `@department-of-veterans-affairs/component-library` to npm in a [GitHub action when a release gets tagged](https://github.com/department-of-veterans-affairs/component-library/blob/996d31551d9c628c9b78794e33d8a1d50548d82c/.github/workflows/publish.yml#L25-L27). We are currently using one of my personal tokens to do this.

We would like to have a token provided by the platform for this kind of automation.

## Background/context 

A [support request](https://dsva.slack.com/archives/CBU0KDSB1/p1635291434341900) was created in Slack for this.

Here is [documentation on npm](https://docs.npmjs.com/creating-and-viewing-access-tokens) related to creating a token.

---
## Tasks
- [x] A bot account is created for the platform
- [x] Account is added to the `@department-of-veterans-affairs` npm org
- [x] Ops creates an `automation` token for Design System team that can be used in CI
- [x] Token is made available to Design System team through GitHub secrets
    - This can be at the org level or the repo level

## Acceptance Criteria 
- [ ] `@department-of-veterans-affairs/component-library` can be published in the GH action using the token provided by Ops

**Comment by k80bowman** [comment]
[Conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1638379796037400) between @bkjohnson and @bjmccotter7192 about managing package publishing.

**Comment by jhouse-solvd** [comment]
@k80bowman - Can you help us understand if there's any urgency around this request? Looking at our plans for the end of the year and need to know whether this can wait until Q1. thank you!

**Comment by k80bowman** [comment]
@jhouse-solvd - We'd love if this could get resolved sooner rather than later, but if it needs to wait until Q1 I understand. If so, could it be done earlier in Q1?

**Comment by jhouse-solvd** [comment]
> @jhouse-solvd - We'd love if this could get resolved sooner rather than later, but if it needs to wait until Q1 I understand. If so, could it be done earlier in Q1?

Thanks for the info. This can likely be done in the 1st or 2nd sprint of 2022 if that works for your team.

**Comment by jhouse-solvd** [comment]
@k80bowman - If you can also share which initiative this may tie to, that will be helpful.

**Comment by k80bowman** [comment]
@jhouse-solvd this one would fall under our Design System Tech Debt initiative. I've added the epic to this card, in case that's helpful. Thank you!

**Comment by jhouse-solvd** [comment]
@k80bowman - I think it sounds like we might want Ops to create an AWS IAM service account that has access to Parameter Store for storing/fetching secrets. Those secrets can then be used in GitHub Actions, ie an NPM token tied to a platform-wide user account. 

I'm not yet clear on where to sign up and create the token, but I think it might be this: https://www.npmjs.com/signup 

Can you confirm and/or clarify? Thank you in advance! 

cc: @bkjohnson @caw310

**Comment by k80bowman** [comment]
@jhouse-solvd yes that is where we would need to create the token. Thank you!

**Comment by jhouse-solvd** [comment]
@mchelen-gov (not urgent): The Design system is (_already_) publishing the component library to NPM in a GitHub Action. But, they are currently using a team member’s personal token. They would like to use a token provided by the platform for this automation. 

Off the top of my head, I believe what is needed from a technical standpoint is: 
- Use a platform service account (email address) to sign up for an account at [NPM website](https://www.npmjs.com/signup)
- Get a token from the NPM account 
- Create a path in parameter store for the Design System Team (if it doesn't exist)
- Store the token from the NPM account in Parameter Store under the path assigned to the Design System Team
- _Potential:_ Set up a group/role/policy etc in AWS IAM for the Design System to be able to manage this path so that they can update the keys in Parameter Store directly 
- _Potential:_ Share the credentials for the platform-level NPM account so they can fetch new tokens and manage them 

**Do you have any questions about what's needed? Do you need any information before this is scheduled for an upcoming sprint?** 

_Note: Separately, an [initiative was created to explore how we can "service-ify" access to paths in Parameter Store](https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/35418). This type of request is coming up regularly, and it's a great candidate for the Infrastructure service catalog._

**Comment by oseasmoran73** [comment]
Hi @k80bowman @bkjohnson 😄 

I have a couple of questions for you all:
1. Just to clarify, the personal token that brooks is using is from NPM side, and not Github, correct?
2. Are you owners of `@department-of-veterans-affairs` via npm org -- To coordinate once BOT has been created

**Comment by bkjohnson** [comment]
1. It's an npm token, but we're using Github secrets to provide it.
2. Yes, we are both owners on the npm org.

**Comment by oseasmoran73** [comment]
Your Github Action should now be able to access SSM store to pull from NPM token.

Token has not been generated yet. Will update to coordinate adding into org once account is created!

**Comment by oseasmoran73** [comment]
@mchelen @jhouse-solvd I would like your input on the following:

We need to create an NPM account (unless there is one already for platform) for DST. That being said, we need to provide email/password. Is there credentials we can use to create this account? If not, who can we talk to to get email/password?

It was mentioned that in the past we used vagovdevops@va.gov, but not properly maintained. I believe the majority (if not all) team no longer has access to this account.

**Comment by mchelen-gov** [comment]
Hi all, what is the viability of using Github Packages for this purpose rather than NPM? This would decrease the complexity of user account and permission management.

- https://github.com/features/packages
- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by bkjohnson** [comment]
Publishing to Github's package registry looks pretty similar, but any consumers of the component library would have to make changes to install from the new registry as well. `vets-website` is the obvious one, but there's also [`developer-portal`](https://github.com/department-of-veterans-affairs/developer-portal/blob/631f94a079c33bc8d3d06cde576fa09cd49d8201/package.json#L24), and possibly others. It looks like Github requires an access token to install, not just publish, so updating scripts and making sure that local installs don't break might be a bit of work.

**Comment by mchelen-gov** [comment]
@bkjohnson That is definitely true about having to update dependencies. Not sure why public packages would require authentication, asking here: https://dsva.slack.com/archives/CU1E4CX9U/p1643317108020619

If that is the case it would be a real downside, so we will proceed with recovery of the vagovdevops@va.gov email for token creation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36118

**Comment by oseasmoran73** [comment]
Hey everyone!

Wanted to give a quick update as it has been a bit silent on our end. We are waiting for email to come in from npmjs. There have been a couple of permission settings that have arose with the email used. They are currently being worked on and once resolved, I will continue to move forward with this.

Let me know if you have any questions or need clarification!

**Comment by k80bowman** [comment]
Thank you @oseasmoran73!! I created a ticket to get this updated, I'll add it to our upcoming sprint so we can get this done.

**Comment by jhouse-solvd** [comment]
@k80bowman - It sounds like we can possibly close this issue, and either re-open or create a new one if anything additional is needed. Does that sound okay to you?

**Comment by k80bowman** [comment]
@jhouse-solvd that sounds fine. Thank you!

**Comment by jhouse-solvd** [comment]
Closing.

**Comment by oseasmoran73** [comment]
Was successfully able to add `va_vsp_bot_npm` onto the design system organization in NPM

Confirmation in Brooks [PR](https://github.com/department-of-veterans-affairs/component-library/pull/302#pullrequestreview-896780013).

Closing ticket as criteria has been met. Please feel free to re-open as needed!
