### ISSUE TITLE
UX Pin Prototype: Outreach & Events (Filtering/Recurring Events) 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#32891]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- Must work well on mobile and desktop platforms
- Must address accessibility concerns and support for adaptive tech
- Should consider iterative feature development
- Initial design/development must align with current CMS functionality
- Must include date/time filtering concepts 
- Must include **recurring events concepts**

### Tasks
- [x] Design Prototype based on mockups/[design feedback document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/date-filter-options.md)
- [x] Incorporate all feedback from Design Intent review and ensure prototype can support research effort
- [x] Review prototype with researcher and determine best fit for research plan conversation guide
- [ ] Close out ticket when completed

### Acceptable Criteria
- [x]  Design prototypes based on mockups design feedback in preparation for user research with Veterans. 
- [x] This needs to be completed NLT 11/19/2021 in order to meet research timeline. 
- [x] PM/PO/Researcher validate prototype for use and close ticket in support.

**Comment by cindymerrill** [comment]
Added user interactions needed for each research task into Cassandra's Mural with design screens for the prototype: https://app.mural.co/t/vsa8243/m/vsa8243/1634651992163/439beeb6c6f54295c81a2b62d2d4c766f6b23205?sender=ua2ff9f6c0031cb4999ae6676

**Comment by cindymerrill** [comment]
Hoping to sync with Jim Adams tomorrow (Tue 11/23) about work on the prototype--user interactions needed, and the timeline. Need to launch recruiting tomorrow if want to test as planned Wed Dec 1.

**Comment by cindymerrill** [comment]
Jim is hard at work on the prototype. I've seen a bit of it and hope to see the rest right before the pilot on Monday.

**Comment by brianalloyd** [comment]
@callen2563 @cindymerrill closing out this ticket in support of prototype build and Veteran Research.  Let me know what questions remain and we can reopen if needed.
