### ISSUE TITLE
Edits and Documentation of Authenticated Info List Pattern

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#32902]
## Issue Description
We need to get the authenticated info list pattern ready for consideration into the experimental design system and make necessary changes.

---
## Tasks
- [x] Address feedback from accessibility team
- [x] Document the pattern per the design system's request

## Acceptance Criteria
- [x] Designs have been changed per accessibility's feedback and uploaded to GH
- [x] Pattern has been documented in GH and updated design examples have been uploaded
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
This has been completed and can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/experimental-design-drafts/authenticated-info-list.md
