### ISSUE TITLE
Document internal guidance for inputting Staging Review feedback manually

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#32906]
## Issue Description
The Platform Product Support team uses the DraftingTemplate and bulk upload process to create issue tickets for Collaboration Cycle Staging Reviews. However, if a team member misses the deadline for adding feedback to the DraftingTemplate and the bulk upload process has already been executed, the team member will need to input their feedback manually using the [Collab Cycle for Staging template. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Staging%2C+collab-cycle-feedback&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29) There are currently no instructions or guidance for how to complete the gh ticket template. This ticket will be to expand the instructions within the template itself, as well as reference the template in the Collab Cycle space on Confluence. 

Note 1/4/2022: There are instructions in the template however they could be expanded upon for clarity.

---
## Tasks
- [x] Edit the Collaboration Cycle for Staging gh template to include specific instructions
- [x] Update the documentation on How to provide feedback for Staging Review

## Acceptance Criteria
- [x] Platform Product Support is able to successfully complete the Collab Cycle for Staging ticket without assistance.
- [x] Operational instructions are updated to reference the Collab Cycle for Stating gh ticket

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@shiragoodman @chase this is ready for your review. I tried to add more without adding too much.
[Staging feedback GH ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/36408/files?short_path=68ffcc7#diff-68ffcc77368204f2b5924d0fee08f6b9d151cdcdba01f5f6d3ede195483cc9ca)
[How to provide feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2077982738/Allison+Copy+of+How+to+provide+feedback+for+Staging+Review)

**Comment by shiragoodman** [comment]
hey @allison0034 - apolgies for the delayed response. the Staging feedback GH ticket looks good. However the "How to provide feedback for Staging review" is an archived page. Not sure if that was intended. Could you please also comment within the ticket where you changed things? It's hard to see in the draft copy.

**Comment by allison0034** [comment]
@shiragoodman it is archived because I moved the changes over already. Summary of changes:

- Removed reference to Wednesday since we have staging reviews on other days now
- Expanded on instance number
- Linked the [Collab Cycle Feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=Staging%2C+collab-cycle-feedback&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29)

**Comment by shiragoodman** [comment]
@allison0034 the changes look good to me. You can merge the PR for the gh template. I think this can be closed - FYI @chaseakirby
