### ISSUE TITLE
[FE] Notification Preferences: Remove feature flag code for Notification Preferences

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#32917]
## Background
As part of the code cleanup of Notification Preferences (#32915) post launch to 100%, we need to remove the feature flag code and clean up anything else, since it's available to all users.

We should do this mid-sprint after Notification Preferences has been live to all users for a few days so that we can make sure there isn't a reason to roll back.

## Tasks
- [ ] Remove feature flag code
- [ ] Update/cleanup Cypress tests
- [ ] Review code for any other cleanup opportunities
- [ ] Test

## Acceptance Criteria
- [ ] Cleanup completed on Notification Preferences code

**Comment by hdjustice** [comment]
@Samara-Strauss Marci is not tracking this, per her slack response.  I plan to check with Taylor through out this week, in case he has any bandwidth to take on this effort.

**Comment by Samara-Strauss** [comment]
Got it. OK, thanks for letting me know. If there's anything left for this team that AJ created for this project, let's move it over to Marci's backlog for easier tracking.

**Comment by hdjustice** [comment]
@tmitchellgcio Who would normally validate something like this?  I am not entirely sure who could help support us in this case.

**Comment by Samara-Strauss** [comment]
I don't think there is a way for us to validate this from the frontend, but Taylor should confirm. If there's not, this is good to go as long as the PR has been approved.

**Comment by tmitchellgcio** [comment]
The only way to validate it is just to smoke test the notifications and be sure they show up and are working properly, though we also have tests to verify that aspect. There isn't anything else we can do to validate the ticket as far as I know since everyone sees the feature.

**Comment by Samara-Strauss** [comment]
Notification preferences show and and work in prod, so we're good to go on this.
