### ISSUE TITLE
Login.gov Minor FE Oversights

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#32928]
## Issue Description
Couple of small tweaks to fix the success event for logingov, as well as the verify page header copy

---
## Tasks
- [ ] add Login.gov to the switch statement on AuthApp
- [ ] add Login.gov copy to the verify page

## Acceptance Criteria
- [ ] `login-success-logingov` fires appropriately
- [ ] Verify page says `Signed in with Login.gov` appropriately
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
