### ISSUE TITLE
Set up drupal install for multilingual module discovery

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#32937]
We need a basic installation of drupal that can have the multilingual modules installed and activated.

## Tasks

- [x] Set up vanilla drupal instance
- [x] Create a basic page with some placeholder content
- [x] Install multilingual modules

**Comment by adamwhitlock1** [comment]
I have created a basic demo vanilla install and will be documenting in further tickets the XLIFF workflow / translation management system.

![Screen Shot 2021-11-17 at 8.48.40 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/98cf83ab-82f7-4591-8df2-fa8e84cf566d)
