### ISSUE TITLE
Update Product Directory

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32941]
## Background
Platform is tracking all the products across the board and needs the latest and greatest updates from our team so that awareness is shared about what is being worked on.

## Considerations and Changes
- Can the products/features on the page be numbered for easier findability or reference?
- Voc Rehab & Employment Benefits Application (VAF 28-1900): Should be renamed to **Veteran Readiness and Employment Application (VAF 28-1900)** in the **Benefits** hub by the **eBenefits Migration Team**, status is **Live** as of **May 10, 2021** and the parent product is **VR&E** ([link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start))
- Voc Rehab & Employment Counseling Application (VAF 28-8832): Should be renamed to Personalized Career Planning & Guidance Application (VAF 28-8832) in the **Benefits** hub by the **eBenefits Migration Team**, status is **Live** as of **May 10, 2021** and the parent product is **PCPG** ([Link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction))
- Dependent Benefits Application and Modification (21-686c): Is in the **Disability** hub, built by the **eBenefits Migration Team**, status is **Live** as of **August 23, 2021** ([Link](https://www.va.gov/view-change-dependents))
- Personal Career Planning and Growth (Ch. 36): Duplicate for the VAF 28-8832, **can probably be removed**
- Payment History: Parent is **Compensation**, in the **Disability** hub, built by the **eBenefits Migration Team**, status is **Live** as of **Jan 8, 2021**, **Steve Kovacs/Matt Self** as PO ([Link](https://www.va.gov/va-payment-history/))

## Tasks
- [x] Notify Product Support about the list of changes shown in Considerations

## Acceptance Criteria
- [x] Updates have been shared
- [x] Acknowledgement has been received

**Comment by shiragoodman** [comment]
@jason-gcio all updates made excluding: _Can the products/features on the page be numbered for easier findability or reference?_

The VA.gov Product Directory has actually been moved off Platform Website and is now strictly accessible via Confluence. Here's the link: https://vfs.atlassian.net/wiki/spaces/VAProducts/overview

In addition, OCTO Platform folks and OCTO Product owners will be responsible for maintaining the doc moving forward. I have shared your request to add row numbers for easily findability/reference.
