### ISSUE TITLE
[FE] Create Footer for Pre-Check-In

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#32949]
## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Create the footer for the new for app

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Create the new footer as a component 
- [ ] Implement where needed. 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Screenshot with footer in action for review. 
cc @ytsaoca @zach-park @niradatta1 @kristenmcconnell 
![localhost_3001_health-care_appointment-pre-check-in_next-of-kin (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/1b818300-a47b-46b9-b417-355fabbd35ee)

**Comment by ytsaoca** [comment]
@brianseek Looks good. Thanks!
'cc @niradatta1 @kristenmcconnell
