### ISSUE TITLE
Create 2022 special monthly compensation rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32944]
## Issue Description
2022 special monthly compensation rates go into effect December 1, 2021. We need to create a 2022 page with the new information and turn the 2021 page into a past rates page. 

Information to work off of emailed on 11/16. 

## Tasks
- [x] Create 2022 rates page (Selina)
- [x] Check numbers against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] 2022 rates page is live on the site
- [x] 2021 past rates page is live on the site

**Comment by lunascoop** [comment]
@RLHecht  these pages are ready for review.

2022 VA special monthly compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=991
Past rates: 2021 VA special monthly compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=39332
Past rates: 2020 VA special monthly compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=11080
Past rates: 2019 VA special monthly compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=4917

**Comment by RLHecht** [comment]
These pages have all been checked and reviewed. Will publish with the rest of the rates.

**Comment by RLHecht** [comment]
Pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
