### ISSUE TITLE
[BE] Pre Check-in Identify & Implement Metrics for Pre Check-In in vets-api

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#32945]
## Description
Based on discussion in [slack](https://dsva.slack.com/archives/C022AC2STBM/p1636731000399600), identify the list of metrics that can be reported from vets-api for Pre Check-in and log metrics using StatsD for creating Datadog dashboard

## Tasks
- [ ] Identify list of metrics
- [ ] Modify vets-api code for logging identified metrics

## Acceptance Criteria
- [ ] Deployed and tested on staging.

**Comment by kanchanasuriya** [comment]
After discussing with the team, instead of using vets-api/backend to handle scenarios on emitting metrics at user level with manipulation at different layers, front end would the best place to emit user-level metrics for precheck-in workflow.
