### ISSUE TITLE
Create 2022 special benefit allowance rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32947]
## Issue Description
The 2022 rates for clothing allowance and Medal of Honor pension go into effect December 1, 2021. We need to create a new 2022 rates page and turn the 2021 page into a past rates page. 

The information for the new page was emailed on 11/16.

## Tasks
- [x] Create 2022 rates page (Selina)
- [x] Check numbers again doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] 2022 rates page live on the site
- [x] 2021 past rates page live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

2022 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=990
Past rates: 2021 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=36401
Past rates: 2020 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=11441
Past rates: 2019 VA special benefit allowances rates: http://preview-prod.vfs.va.gov/preview?nodeId=5035

**Comment by RLHecht** [comment]
These pages have been reviewed. Will wait to publish with the rest of the rates pages.

**Comment by RLHecht** [comment]
Pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
