### ISSUE TITLE
Create 2022 disability compensation rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32942]
## Issue Description
2022 Disability compensation rates go into effect on December 1, 2021. We need to create a new rates page with the new information and turn the 2021 page into a past rates page. 

Information for new page

---
## Tasks
- [x] Create 2022 page (Selina)
- [x] Check numbers against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that pages are live (Randi)

## Acceptance Criteria
- [x] 2022 disability compensation rates page is live
- [x] 2021 disability compensation past rates page is live

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Current VA disability compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=989
2022 Veterans disability compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=986
Past rates: 2021 Veterans disability compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=39312
Past rates: 2020 Veterans disability compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=11075
Past rates: 2019 Veterans disability compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=4714

**Comment by RLHecht** [comment]
These pages are all checked and reviewed. Will publish with the rest of the rates pages.

**Comment by RLHecht** [comment]
These pages are all published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
