### ISSUE TITLE
[BE] Pre-Check-in Finish CHIP service layer refactor

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#32959]
## Description
AS a User of va.gov
I want the CHIP service layer refactored completed before implementing the new Pre-Checkin BE code
SO that I can continue to receive new features and updates quickly

## Tasks
- [ ] Add a new redis-client to handle storing and retrieving data for the CHIP service layer(see LoROTA service)
- [ ] Wire the new CHIP client and redis-client to the existing patient_check_ins controller(see LoROTA service)
- [ ] Ensure 90% spec coverage

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by dillo** [comment]
Git branch: 32959_finish_chip_refactor @randomsync @kanchanasuriya
