### ISSUE TITLE
[BE] Pre-Check-in Modify GET/POST Sessions Controller logging Pre-Check In metrics

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#32955]
## Description
Based on Pre Check-in architecture discussion, team decided on using existing day of check-in GET/POST session controller for pre check-in as well. As part of this story, existing GET/POST session controller should be modified to verify pre check-in flag from front end and log metrics using StatsD

## Tasks
- [ ] Modify GET Session controller to log pre check-in metrics behind pre check-in feature flag
- [ ] Modify POST Session controller to log pre check-in metrics behind pre check-in feature flag
- [ ] Add specs for GET/POST session controller changes

## Acceptance Criteria

- [ ] Deployed and tested on staging.
