### ISSUE TITLE
SD - Define and confirm R&S 2.0 Metrics 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#32950]
## Issue Description
Define goals and measure of success for R&S 2.0 per comments from stakeholders [Here](https://app.mural.co/t/vagov6717/m/vagov6717/1636744654505/e4733a01687242944f0904f3544ee73cc0f47435?sender=u1777baa622793bb339be4705)

---
## Tasks
- [x] _Review metrics in the measurable list and come up with top-five success metrics that is the most appropriate_
- [x] _Clearly identify how to measure the top five(or ten) KPIs_
- [x] _Create Metrics and Baseline list, include the most effective measurable KPIs_
- [x] _Discuss Metrics and Baseline list with PO and get approval_

## Acceptance Criteria
- [x] _Identify the most appropriate success metrics for R&S and how to track and measure them_
- [x] _Finalized and approved metrics and baseline list_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
List of metrics highlighted in yellow: [Analytics Spreadsheet](https://governmentcio.sharepoint.com/:x:/s/SearchDiscoveryTeam/EaK84Ve3NKtMtRB6ZM3ZWr4BE5WizM2HsjsVGUJ1BIdb0w?e=WmsgCP)
