### ISSUE TITLE
[FE] Integate with Vets API 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#32953]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.
 
Integrate with the vets-api 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] being able to communicate with VETS-API either locally or in staging
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by julieadair1** [comment]
@mdewey what epic should this be linked to?  Is this part of the pre-check-in work? 
cc: @jparker0425

**Comment by jparker0425** [comment]
@julieadair1 this would be part of the Pre-Check-in work. This is the integration piece needed for Vets API to wire everything up from the FE to BE .

**Comment by julieadair1** [comment]
@jparker0425, thanks.  I've labeled with the appropriate epic
