### ISSUE TITLE
Create 2022 birth defects rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32952]
## Issue Description
The 2022 birth defect rates go into effect on December 1, 2021. We need to create a 2022 rates page with the new information and turn the 2021 page into a past rates page. 

Information for new rates was emailed 11/16. 

## Tasks
- [x] Create 2022 rates page (Selina)
- [x] Check numbers against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish pages (Randi)
- [x] Update left nav (Randi)
- [x] Notify stakeholder that pages are live (Randi)

## Acceptance Criteria
- [x] 2022 rates page live on the site
- [x] 2021 past rates page live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review

2022 birth defect compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=993
Past rates: 2021 birth defect compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=39423
Past rates: 2020 birth defect compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=11440
Past rates: 2019 VA birth defect compensation rates: http://preview-prod.vfs.va.gov/preview?nodeId=5062

**Comment by RLHecht** [comment]
These pages are all reviewed. @lunascoop will add the "Want to check current rates info?" to the 2021 page. Will wait to publish these with the rest of the rates pages.

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
