### ISSUE TITLE
[Debt Portal] Update status cards with feedback from SMEs

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#32967]
## Issue Description
Jill provided some feedback on the redesigned status cards for Debt Portal, we need to update our mocks and prepare the feature for development.

---
## Tasks
- [x] **Update 681/682:** Fix spelling error ![image001.jpg](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/1610e965-7a6e-46f2-9532-8f16ef52b378)
- [x] **Update 600/601:** "If they are making payments, they shouldn’t need to call, they know what they have paid.  This only seems appropriate if we are offsetting" ![image002.jpg](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/d25f7eae-80f6-4a39-beae-f4ec321f8945)
- [x] **Update 815:** "Do we want it to say – one time payment or something to mean it can’t be installments or partial payments?"

## Acceptance Criteria
- [x] Status cards updated with new content

**Comment by rileyorr** [comment]
I incorporated Jill's feedback and updated the cards on our [UXPin prototype](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57#/pages/142818160/simulate/sitemap?mode=i). I had to spend some extra time fixing layers in the Sketch file - I think the UXPin plug-in was duplicating layers and stripping elements out as it exported. 

I need to clarify one thing about Jill's feedback for 600/601. I've sent her an email and will finalize this work once she gets back to me!

**Comment by rileyorr** [comment]
@denisecoveyduc I moved this over to blocked until Jill can get back to us!

**Comment by rileyorr** [comment]
Incorporated Jill's feedback for 600/601. [The updated status cards can be found here!](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57?_gl=1*1m9uxro*_gcl_aw*R0NMLjE2NDE1ODY0NjEuQ2p3S0NBaUE1dC1PQmhCeUVpd0FoUi1obTg1M1F3aFRjbmhBdmMxVDZldGFIblVZNWdJNmhScFNGa3J3dEJON1BBODJLazBFdW15S09ob0M5cGNRQXZEX0J3RQ..#/pages/145870940/simulate/no-panels?mode=i)

**Comment by denisecoveyduc** [comment]
Awesome! Do we already have a ticket for FE implementation? @rileyorr
