### ISSUE TITLE
HLR v2: Add issue list loop

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32964]
## Description

Design intent review feedback recommended we change the list loop pattern to jump to and return to a main page:

```
    ┌────────────────────────────────┐
    ▼            Add/Edit            │
All issues page ──────────► Add/edit name & date 
    │ Continue
    ▼
Area of disagreement
```

- Review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31318
- Design: https://www.sketch.com/s/6ad12bd0-214d-40bf-90d7-d0562010181e/a/KvDWpdD

## Tasks

- [ ] Add list loop method to HLR v2 behind a feature flag
- [ ] Add unit tests
- [ ] Add e2e tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
I did not start implementation of this work as the design was completed this sprint. We will push this work to the next sprint.
