### ISSUE TITLE
Expand accordion when ID matches the URL hash

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#32966]
## Description

The new `va-accordion-item` web component replaced the previous React component, but content implementation to expand the React component was not adapted to support the web component. After several interactions, it was determined to internalize this behavior within the web component.

- Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28658
- Related work: https://github.com/department-of-veterans-affairs/content-build/pull/764

## Tasks

- [ ] Modify `va-accordion-item` to open when the applied ID matches the URL hash
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
This work has been completed, but is still being evaluated by the design system team. Some testing needs to be fixed before this work can be merged.
