### ISSUE TITLE
CT Redesign - Create new User Guide

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#32975]
## Issue Description
Contact Center/EDU needs a new user guide for the CT redesign that will be released soon. 

---
## Tasks
- [ ] Work with OIT contact to draft a new user guide
- [ ] Approve final draft
- [ ] Create Content Center review request ticket
- [ ] Submit draft to Contact Center via the CC review request ticket

## Acceptance Criteria
- [ ] User guide is ready to submit to Contact Center.
- [ ] CC review request ticket has been created
- [ ] User guide is attached to the CC review ticket
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ERRonat0609** [comment]
This work has been completed and forwarded to the Contact Center reviewer
