### ISSUE TITLE
Add R&S link to Post-9/11 GI Bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#32971]
## Issue Description
We need to add a link to a new R&S article on the Post-9/11 GI Bill page. 

Link to add: 
https://www.va.gov/resources/how-we-determine-your-post-911-gi-bill-coverage/

This should be added under the H2 "What benefits can I get through the Post-9/11 GI Bill (Chapter 33)?" underneath the current R&S link. 

Proposed copy:
Find out how we determine your Post-9/11 GI Bill coverage

## Tasks
- [x] Add link (Laura)
- [x] Review and publish (Randi)
- [x] Let Beth know link is live (Randi)

## Acceptance Criteria
- [x] New link is on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lwalsh617** [comment]
@RLHecht - This is ready for you to review and publish. http://preview-prod.vfs.va.gov/preview?nodeId=935

**Comment by RLHecht** [comment]
Thanks @lwalsh617. Just published. Moving to validate and will let Beth know once the page is live.

**Comment by RLHecht** [comment]
This work is complete and the link is live on the Post 9/11 GI Bill page. FYSA @bethpottsVADEPO Closing ticket.
