### ISSUE TITLE
Investigation into Summary Email Job Snag

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#32972]
## Background
An issue has popped up with the Summary email for the VR&E folks, and we are working to get to the bottom of it.

## Tasks
- [ ] Check Sentry
- [ ] Check RO Lookup
- [ ] Attempt to reproduce

## Acceptance Criteria
- [ ] A path forward has been determined 
- [ ] A solution has been implemented (stretch)
- [ ] A PR has been requested for merging
