### ISSUE TITLE
Discovery Form 526. Length & abandonment Phase 2

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#32983]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [x] Explore how Form 526 can be modeled after a "task list approach" used by UK.gov
- [x] Explore how Form 526 can be reorganized into numbered/prioritized sections. Strive towards a "streak effect".
- [x] Explore if we can use a "milestone submission approach" (used by UK.gov). Users can submit a form when they have entered to absolute necessary info and add more info later.
- [x] Explore other ways to shorten and simplify Form 526

## Acceptance Criteria
- [x] Documented form improvement research and recommendations. Presentation and formal documentation

**Comment by chrvalla** [comment]
This project will reach into the next sprint. Ticket is moved to next sprint.
