### ISSUE TITLE
526 Errors - Design for Saved Claims in CST

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#33011]
## Issue Description
In attempting to address 526 errors, we determined that it was possible to preserve the form submissions that did not make it to EVSS. We could do this via PDF generation. Therefore we want to explore what that preserved claim (and PDF form) might look like in the CST. 

We also determined that we could identify which files did not get uploaded for a particular claim. We would like to explore what it may look like if we had a claim in the CST that was submitted, but the associated files (supporting evidence or documentation) did not submit.

---
## Tasks
- [x] Create a design for hypothetical 'saved but not submitted' claim
- [x] Create a design for a hypothetical 'form submitted successfully but not all files/evidence made it' claim

## Acceptance Criteria
- [x] Prelim designs have been created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
These prelim designs have been created and can be found here:

https://www.sketch.com/s/1cce0882-8ade-49cc-80e8-74cb3ea6131f
