### ISSUE TITLE
Reach Out to POC for SAHG

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33018]
## Background
As a Veteran I need the ability to easily submit a Specially Adapted Housing or Special Home Adaptation claim on Vets.gov so that all required, relevant details can be entered online which will expedite it through the proper channels, ultimately resulting in potential compensation for my claim.

We need a POC to ask some specific questions around this work

## Tasks
- [x] Circle back via email with the potential POC's for SAHG

## Acceptance Criteria
- [x] Gain acknowledgement of communication
- [ ] Schedule a meeting (stretch)
