### ISSUE TITLE
[Research] Profile Personal Information Revision: Finish drafting Conversation Guide

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33016]
## Issue Description
Research ticket to finish drafting conversation guide started in Sprint 61 (#32706)  to support Personal Information Revision work.   [Conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

## Tasks 
- [ ] Complete conversation guide draft
- [ ] Share both with Marci, Samara
- [ ] Incorporate all feedback 

## Acceptance Criteria
- [ ]  Finalize conversation guide and store in our [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/research)

**Comment by MarciMcGuireGCIO** [comment]
Broke this apart from #32706 so it could be worked on over two sprints.  Took the original estimate of 5 and put 3 in sprint 61 and 2 in sprint 62.

**Comment by MarciMcGuireGCIO** [comment]
Closing; this will be completed in a single task.
