### ISSUE TITLE
Investigate Missing 1900s

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33029]
Latest missing submissions: ([365 version](https://governmentcio-my.sharepoint.com/:x:/g/personal/kevin_musiorski_gcio_com/Ef-hV4PWe7dGrbv2L2FJBIMBG_nKfB1Ns1N6MayHsp2Piw?e=3I6Yxg))
PID: 3017862 Sun 10/03/2021 1:14 PM (Arizona time from when Robert got email?)
PID: 39397005 Sun 10/03/2021 3:07 PM (Arizona time from when Robert got email?)
PID 54696527, 10/3/2021, Salt Lake City, 20:56:16 UTC
PID 31283514, 10/3/2021, Salt Lake City, 21:50:53 UTC
PID 56605446. 56605446, 10/10/2021 1:48 PM (Arizona time from when Robert got email?)
PID 53923347, 11/3/21, Salt Lake City, 18:39:49 UTC (matches with `pdf doesn't exist error`)
PID 42237572, 11/15/2021, no regional office / timestamp yet

## Considerations
- Add logging
- Adjust job
- A PDF file not found and maybe we can do something similar in rails with a root/rejoin method
- PID ending 3347 has a direct error in Sentry (http://sentry.vfs.va.gov/organizations/vsp/issues/45826/events/cfc67bcacb614f179b8361c2ba1fc6e2/?end=2021-11-03T23%3A59%3A59&environment=production&project=3&start=2021-11-03T00%3A00%3A00&utc=true
)

## Tasks
- [ ] Investigate Sentry for these time periods
- [ ] Check DataDog/Grafana
- [ ] Check for returning customers 
- [x] #33383

## Acceptance Criteria
- [x] A reason has been determined or hypothesized.
- [ ] A fix has been implemented (stretch)
- [ ] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
Just a heads up on this, I merged in one PR that may fix the one error we were able to link up to one of the missing PDF's. 

@jason-gcio not sure if you want to close this or keep it open since we have not found any evidence for the other missing PDF's.
