### ISSUE TITLE
COE Punchlist

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33024]
## Considerations
1. Establish copy freeze with Kelli
2. Call out and compile changes for FE (w/ Jerek)

## Tasks
- [x] Review and sync [prototype](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design) with staging
- [ ] TBD

## Acceptance Criteria
- [ ] A punchlist has been drafted in GH and shared with the team
- [ ] A PR has been requested for merging, if applicable

**Comment by sporeboy** [comment]
Review of COE form intro states is done. The punchlist is here: [(Link to Github page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/coe-design-punchlist.md)

More to come!

**Comment by sporeboy** [comment]
"Your COE" screen state items added to punchlist.

**Comment by sporeboy** [comment]
Form elements were reviewed and items added to punchlist.
