### ISSUE TITLE
[FE] Implement feature flag check within forms system

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#33023]
## User Story

 As an engineer I would like to conditionally display i18n features on a form (1010CG as first experimental form)

## Description

Feature toggle `formI18n` will be used to show internationalization features on forms, and the first step is to show UI conditionally within the form based on this feature toggle. The toggle has been added to vets-api and vets-website configs, and now just needs to be prototyped within the usage of a form.

## Tasks

- [x] Add conditional check for language switcher component
- [x] Evaluate if there is a way to pull in the feature toggle into other form system components
- [x] Add conditional check to custom component usage
- [x] Update relevant documentations for standardization of the process

## Acceptance Criteria

- [x] Language Switcher component displays on dev domain / locally based on feature toggle
- [x] Custom component displays on dev / local

**Comment by adamwhitlock1** [comment]
The feature flag toggle check is implemented in this branch and works locally.

https://github.com/department-of-veterans-affairs/vets-website/tree/33023-toggle-check-in-form-i18n

If we are going to support i18n in the legacy form system then this branch could be used for subsequent work, but if we are looking to start implementing i18n in Formation, then a new ticket should be made for that integration groundwork.
