### ISSUE TITLE
Removal of PTSD questions in Form 526

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#33038]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [x] Explore how we can remove questions (that is triggering for many veterans) about PTSD in Form 526 
- [x] Work with Paul Shute on identifying the legal language we need to use for this project. 
- [x] Design pages where the veteran is asked about "fear of hostile military or terrorist activity".

## Acceptance Criteria
- [x] Documented form improvement research and recommendations. Presentation and formal documentation

**Comment by chrvalla** [comment]
This project will reach into the next sprint. Ticket is moved to next sprint.

**Comment by chrvalla** [comment]
Page with additional question will be added to Form 526 (approved by Paul Shute). Content review Dec16,2021. Ticket closed. Project will continue as phase 2 next sprint.
Mural board:
https://app.mural.co/t/vsa8243/m/vsa8243/1638999373388/4dd450f76ceaa66dc01e552599f3b3811d047262?sender=cvalla7693

**Comment by chrvalla** [comment]
Page with additional question will be added to Form 526 (approved by Paul Shute). Content review Dec16,2021. Ticket closed. Project will continue as phase 2 next sprint.
Mural board:
https://app.mural.co/t/vsa8243/m/vsa8243/1638999373388/4dd450f76ceaa66dc01e552599f3b3811d047262?sender=cvalla7693
