### ISSUE TITLE
[FSR] Submit transformer calc incorrect values

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33039]
## Issue Description
Verify field values for 13 - 17 | SECTION II - INCOME under Spouse should not be generating NaN values. Values calculated in the submit transformer are incorrect and passing the value of NaN. Paper form can be found here for reference: https://www.va.gov/vaforms/va/pdf/va5655.pdf

![thumbnail_image001.jpeg](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/18b440d6-7005-46b4-8137-9edb928a7982)

![thumbnail_image002.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/1a07b2bd-f145-436c-810d-e0ccde671898)

---
## Tasks
- [ ] Verify values are calculated correctly on form submit

## Acceptance Criteria
- [ ] Values should be calculated correctly on form submit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
Waiting for validation from the DMC that the issue has been resolved
