### ISSUE TITLE
Plain language updates to Post-9/11 GI Bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33033]
## Issue Description
There's one question on The [Post-9/11 GI Bill page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) which needs updates for plain language. 

 Here are the changes we need to make:

Update the language in this H2: What is the Location-Based Housing Allowance (Section 107)? 
1/ Make the following plain language: previously / advantageous / educational institution / operationally / geographically.
2/ Remove italics.
3/ Consider reworking the text so that the current info is first and the "how it used to be" language is in a note following how it is now. (Beth will have to run this past SMEs).
4/ Consider retaining bolding of the key point about MHA being where the student attends the majority of their classes. But rework it so what's bolded matches our style (here it is the last half of the sentence, which isn't our style).
5/ Change "VA's" to "our"

## Tasks
- [x] Make plain language edits (Selina)
- [x] Edit (Patrick)
- [x] Copyedit (Randi)
- [x] Send to Beth for final review (Randi)

## Acceptance Criteria
- [x] Page is ready for final review

**Comment by RLHecht** [comment]
Updating tasks and acceptance criteria of this ticket and will create a new ticket for the next sprint for incorporating stakeholder feedback, final copyedit, and publishing.

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO the plain language updates are ready for review in Drupal. I did expand the scope of the Q&A since location-based housing allowance seems to be one of a few factors that determines the monthly housing allowance. 

Post-9/11 GI Bill (Chapter 33): http://preview-prod.vfs.va.gov/preview?nodeId=935

**Here are my sources:**

- https://www.benefits.va.gov/gibill/docs/FGIB_comms_toolkit.pdf (the current text for this Q&A comes from the PDF verbatim)
- https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080121.asp#HOUSING
- https://www.benefits.va.gov/GIBILL/docs/presentations/SCO_Webinar_01_09_2019.pdf
- https://www.benefits.va.gov/gibill/docs/fgib/campus_Definition.pdf
- https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/

**Comment by batemapf** [comment]
👋 hey not sure if im the right person here?

**Comment by lunascoop** [comment]
Sorry @batemapf. Thanks for letting me know

**Comment by lunascoop** [comment]
I believe @RLHecht did a final copy edit for this. If so, @bethpottsVADEPO this is ready for your review.

**Comment by psanders86** [comment]
@RLHecht Please give this a final look. I made substantial changes to the first bullet.

**Comment by RLHecht** [comment]
I copyedited this. Will let Beth know it's ready for final review in ticket #34462.
