### ISSUE TITLE
[FSR] Repeated values are being generated on PDF

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33043]
## Issue Description
When a user selects the same value for multiple debts the value is repeated. Values should be filtered and only render a single instance if the same value is selected multiple times.

![thumbnail_image005.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/27771299-54ce-47d8-9c8b-39e9e0b97082)

![thumbnail_image004.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/da647b8a-ade4-401a-af23-4d163b49b5f4)

---
## Tasks
- [ ] only one instance of the selected value should be submitted

## Acceptance Criteria
- [ ] verify payload transmits a single instance
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
Waiting for validation from the DMC that the issue has been resolved
