### ISSUE TITLE
Implement "official name" display on Vet Center front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33053]
## Issue Description
In some cases, the "official" (legislative or ceremonial) name of a Vet Center is not how the facility is known locally. Vet Center pages needs to display both names to honor the official name while making the page findable and locally recognizable.
For example, "Dr. Cameron K. McKinley Vet Center" is locally known as "Prescott Vet Center".

See this example: https://www.va.gov/disability/file-disability-claim-form-21-526ez/start

**Where name appears**

Main page
- [x] Breadcrumb
- [x] H1 title
- [x] "In the spotlight" (and jump link)
- [x] "View other locations" link to Locations page

<details>
<summary>Screenshot </summary>

![main page name](https://user-images.githubusercontent.com/55411834/144477298-1ac8c961-5f64-4beb-8856-cbfdde8567d6.png)
</details>

Locations page
- [x] Breadcrumb
- [x] H1 title
- [x] Text under Satellite locations
- [x] CAP naming convention
- [x] Mobile Vet Center name

<details>
<summary> Location page </summary>

![locations page  name](https://user-images.githubusercontent.com/55411834/144477286-894371d2-ae45-4317-a7d9-b51bd2064ad2.png)

</details>

**Field names**

- Common name = title (the node title)
- Official name from VAST = Name of Vet Center (field label in CMS) = field_official_name 
- Common name (node title) only shows for Vet Center editors if it’s different than Official name from VAST

## Tasks

Add logic to determine which name is used on Vet Center pages
- When the common name field is populated, 
   - use the common name for the H1 and all other places in the template. 
   - the field_official_name should appear below the H1 according to [Nick's UX Pin spec for the display of Unofficial and common names for facilities](https://preview.uxpin.com/f04f4c248729227d98bda373259007badfe9bed6#/pages/144328365/documentation/no-panels?mode=i) Specs:
     - line-height: 30px
     - font-family: Source Sans Pro
     - font-size: 20px
     - font-weight: bold
     - spacing above: 8px
     - spacing below: 20px
- When the common name field is not populated, the field_official_name is used for the H1 and all other name fields throughout the template (current experience is maintained)
- Accessibility note: <h1 aria-describedby="unique-id">Prescott Vet Center</h1><p id="unique-id">Dr. Cameron K. McKinley Vet Center</p>

## Acceptance Criteria
- [x]  The value stored in field_official_name (comes from VAST) is shown as the H1 on Vet Center pages unless the common name is populated. 
- [x] The value in common name is used as the H1 and all other name references thoughout the page
- [x] When the common name is used as the H1, the field_official_name appears in the sub header

**Comment by mmiddaugh** [comment]
@joshkimux, @RLHecht and content team, 

We're hoping to get a quick gut check from you on this one. 

**Scenario**
In some cases, the "official" (legislative or ceremonial) name of a Vet Center is not how the facility is known locally. For example, "Dr. Cameron K. McKinley Vet Center" is locally known as "Prescott Vet Center".

We're making a change to use the "common" name for all places on Vet Center pages where the name is referenced to make it findable and locally recognizable. We will honor the official name in a sub header below the H1. Visually, it will just display the name but we think we'll need the screen reader to announce it with some context. Will something like "also known as" be appropriate? 

**Example** 
Visually: 
H1: Prescott Vet Center
subheader: Dr. Cameron K. McKinley Vet Center

**Comment by joshkimux** [comment]
@mmiddaugh You wouldn't need to append any extra information that a sighted person wouldn't have access to either 😄 
I'd recommend just linking these up using `aria-describedby`

**Comment by bethpottsVADEPO** [comment]
@mmiddaugh @RLHecht 
UX Pin is showing "Commonly called"--I'd just like to simplify that to "Also called" like this:

H1: Prescott Vet Center
subheader: Also called the Dr. Cameron K. McKinley Vet Center
