### ISSUE TITLE
[FE] Profile - Login.gov - Implement copy updates for MHV/DS logon users

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33064]
MPM 12/8/2021 - Corrected issue description to correctly reflect copy changes.

## Issue Description

As a MHV/DS log on user, I need to be alerted that login.gov is now a valid credential to use for logging into VA.gov so that I don't waste time creating a separate log in or logging in with a different account.

The existing alert should be updated as follows (copy/pasted from https://github.com/department-of-veterans-affairs/va.gov-team/issues/33065#issuecomment-984773234):

Heading
You’ll need to verify your identity with Login.gov or ID.me to update your direct deposit information online.

Body
We require this to protect your bank account information and prevent fraud. If you have a verified Login.gov or ID.me account, you can sign out and sign back in with that account. Then you can update your direct deposit information online. If you don't have one of these accounts, you can create one now.

[Create a Login.gov account]
[Create an ID.me account]

Note: If you need help updating your direct deposit information, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

### Mockups
[Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/v/8zklAO/a/paW24nG/)

[Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/dlQWx99)

---
## Tasks

- [ ] Implement alert we show MHV/DS Logon users to let them know Login.gov is an acceptable credential in addition to ID.me

## Acceptance Criteria

- [ ] Implement alert we show MHV/DS Logon users to let them know Login.gov is an acceptable credential in addition to ID.me
- [ ] Test!
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen do you anticipate being able to complete this ticket before Friday?  If not, are there any tips/pointers you can share that would be helpful to Zach?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 62 since we are just now learning how to log in using Login.gov today.

**Comment by MarciMcGuireGCIO** [comment]
Copy update for implementation is complete - please see #33065

**Comment by erikphansen** [comment]
This can be validated on staging. If you sign in with a DSLogon or MHV test user you should see the updated copy. Keep in mind that the updated alert does _not_ show [the very latest copy revision](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33065#issuecomment-984773234). A new FE ticket should be created to make those copy changes.

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen since this ticket is still open and it hasn't been validated, let's just keep working off this one.   If you need to add another point for the update, please do.  Thanks!

**Comment by erikphansen** [comment]
At this point I think Taylor should take it over. He reviewed the PR that has the now outdated copy so he should be able to easily update the copy to the latest and greatest copy.

**Comment by MarciMcGuireGCIO** [comment]
Sounds like a plan, @erikphansen.

@tmitchellgcio - you good to jump on this?

**Comment by tmitchellgcio** [comment]
yep not a problem

**Comment by tmitchellgcio** [comment]
PR up but it won't let me tag it. https://github.com/department-of-veterans-affairs/vets-website/pull/19603

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @tmitchellgcio.  Does that mean you can't tag someone to review?  Thx!

**Comment by andaleliz** [comment]
I'm having issues with the [accounts listed in our direct deposit user doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md) ([posted here in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1638894688091800?thread_ts=1638548706.003600&cid=C909ZG2BB)) and am not able to validate this at the moment. I'll come back to this when I'm back from PTO next week; if it's urgent perhaps someone else can give it a try?

**Comment by MarciMcGuireGCIO** [comment]
Tested with user 36 and seeing the below message instead of the correct one.  
![image](https://user-images.githubusercontent.com/73354907/145117897-2f5dde01-8f38-48b4-83f6-71ea8e3b3fae.png)

**Comment by MarciMcGuireGCIO** [comment]
^^ @Samara-Strauss for visibility.  Liz and I both encountered issues trying to validate Taylor's changes today.  May be account related... stay tuned.

**Comment by Samara-Strauss** [comment]
> FYI, I tested on Staging with user 36 & 204; seeing the below message instead of the one you updated.

This needs to be tested with an MHV or DS Logon user since this copy only shows to them.

**Comment by MarciMcGuireGCIO** [comment]
Oh! Thank you! I'll check now.

**Comment by Samara-Strauss** [comment]
Logging in with DS Logon doesn't always work, so I would use an MHV user. [You can find that staging info here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mhv-lower-env-test-accounts.md). I believe you need to use someone who is marked as "Advanced" or "Premium" since that's the equivalent of identity verified.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @Samara-Strauss !  I thought since it was Login.gov it meant we had to test by logging in through Login.gov.  🤦🏻‍♀️

**Comment by Samara-Strauss** [comment]
Got it. Sorry for the confusion. This particular task only affects DS Logon and MHV users -- we need to let them know Login.gov is now an option in addition to ID.me.

**Comment by MarciMcGuireGCIO** [comment]
So, this happens when I try to use MHV:

![image](https://user-images.githubusercontent.com/73354907/145236235-49be871b-d5d8-432d-baa0-8ad70c14b796.png)

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO you have to be on the VA network to use MHV staging :/

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz DOH!!!  LOL So many things! 🤣

**Comment by Samara-Strauss** [comment]
Oh right, I completely forgot that since I'm always on the VA network. Yes, you have to be on the VA network to validate. Sorry this is a mess.

**Comment by MarciMcGuireGCIO** [comment]
Ok, so with a DSLogon User, I am seeing this message, which does not seem to match the language listed above.  

![image](https://user-images.githubusercontent.com/73354907/145237562-3ec042c1-9ff8-4443-a3c2-0eb446dc735c.png)

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - no need to apologize.  You guys didn't create the mess.  I'm sure this is all documented and I forgot.

**Comment by Samara-Strauss** [comment]
I was about to say I also validated with an MHV user and see the same thing you do -- it mentions Login.gov, but the copy is different than what is shown in the initial message of this post. @MarciMcGuireGCIO [per Erik's message in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33064#issuecomment-984853006) it sounds like the copy wasn't updated to what @andaleliz outlined. Not sure why. We should still make that update.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @tmitchellgcio! I'll update the task to reference the updated copy from the other.  Sorry for the confusion!!

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio your original changes did, in fact, accurately reflect the final content change that Danielle made in the related Design ticket.   I have updated the information at the top of this ticket with the correct spec info.   

Looks great!  

cc @Samara-Strauss @andaleliz

**Comment by Samara-Strauss** [comment]
Ah, sorry for the confusion -- looks like we were validating against an old screenshot. Thanks for updating that screenshot, Marci. Given that we've both validated this in staging, this should be good to close!
