### ISSUE TITLE
[Design] Profile - Login.gov - Update alert copy MHV/DS logon users

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33065]
## Issue Description
Update copy for the alert we show MHV/DS Logon (see below) users to let them know Login.gov is an acceptable credential in addition to ID.me

![image](https://user-images.githubusercontent.com/73354907/142500520-65748a95-f8c5-474d-9aff-4050fbdc23cf.png)

---
## Tasks
- [ ] Update copy for the alert we show MHV/DS Logon users to let them know Login.gov is an acceptable credential in addition to ID.me

## Acceptance Criteria
- [ ] Update copy for the alert we show MHV/DS Logon users to let them know Login.gov is an acceptable credential in addition to ID.me
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO is it possible to add a screenshot of the current alert on the page it appears? I'm not sure exactly what this alert is.

**Comment by MarciMcGuireGCIO** [comment]
@Liz I scheduled a meeting at 2 ET today to get a little more info from Samara and can add a screen shot after. I  created this strictly from yesterday's Slack thread and not sure where that resides either. 🙂

**Comment by andaleliz** [comment]
The content team is tracking their work in #30279; we can use the language from those updates in our alert so we're talking about things in the same way.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA we have an alert we need to update that appears in the direct deposit section for MHV/DS Logon users, since they're blocked from editing direct deposit info online (originally created in #28986 if that's helpful).  Now we need to update it to reflect the login.gov info.  The current alert is in the description, and here's what I'm proposing.  What do you think?
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/c008f389-91e8-444b-920c-45ab6715142f)

Heading
**You’ll need to verify your identity with ID.me or Login.gov to update your direct deposit information online.**

Body
We require this to protect your bank account information and prevent fraud.

**Get help updating your direct deposit information.** You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Sign in with a verified ID.me or Login.gov account.** You can create a verified account on [ID.me] or [Login.gov]. Or, if you already have one, please sign out and sign back in using your existing verified account. Then you'll be able to update your direct deposit information online.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz you beat me to it adding the screen shot!  I stuck it in a the top also.

**Comment by andaleliz** [comment]
![Screen Shot 2021-11-22 at 12.32.40 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/87d7fe82-8851-4227-bbf5-267ae67c383a)

@MarciMcGuireGCIO I reviewed with Danielle and got approval on the copy shown in the mock-up (above) and copy (below). Ready for a FE ticket.

Heading
You’ll need to verify your identity with Login.gov or ID.me to update your direct deposit information online.

Body
We require this to protect your bank account information and prevent fraud.

Get help updating your direct deposit information. You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

Sign in with a verified ID.me or Login.gov account. You can create a verified account on [Login.gov] or [ID.me]. Or, if you already have one, please sign out and sign back in using your existing verified account. Then you can update your direct deposit information online.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @andaleliz! I'll get the FE ticket ready ASAP.

**Comment by erikphansen** [comment]
@DanielleThierryUSDSVA @andaleliz just a heads up that I'm going to use the new content that has been provided, but I suspect our a11y friends might have an issue with the `login.gov` and `ID.me` links. I think it's generally better for links to be a little more descriptive, so something like `create a verified account on ID.me` and `create a verified account on Login.gov` would be better (although clearly more verbose)

**Comment by erikphansen** [comment]
I also noticed that the order of the sign in providers flip-flops in the copy, with ID.me being listed first some times and Login.gov being listed first other times.

**Comment by andaleliz** [comment]
> just a heads up that I'm going to use the new content that has been provided, but I suspect our a11y friends might have an issue with the login.gov and ID.me links. I think it's generally better for links to be a little more descriptive, so something like create a verified account on ID.me and create a verified account on Login.gov would be better (although clearly more verbose)

I'll chat with Danielle about this in office hours today

>I also noticed that the order of the sign in providers flip-flops in the copy, with ID.me being listed first some times and Login.gov being listed first other times.

Our alert follows the ordering we'll have in content on other areas of the site.

**Comment by andaleliz** [comment]
@erikphansen do the links in the alert take people to the homepage or the exact page where they can start the account creation process?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, descriptive links with target and purpose are best. In this case, the target and purpose are in the sentence so it's probably okay, but our style is more creating separate links on new lines wherever possible so let's do that here. I'm also looking at this and wondering if we should move the "get help" content down to Refer to below for thoughts. And then we'd followed up on order and decided to go with Login.gov first throughout. 

**Note:** Worked through this more with Liz in office hours so we're both good with this version below.

Heading
You’ll need to verify your identity with Login.gov or ID.me to update your direct deposit information online.

Body
We require this to protect your bank account information and prevent fraud. If you have a verified Login.gov or ID.me account, you can sign out and sign back in with that account. Then you can update your direct deposit information online. If you don't have one of these accounts, you can create one now.

[Create a Login.gov account]
[Create an ID.me account] 

**Note:** If you need help updating your direct deposit information, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO can you make a 1 point ticket for me (or Christina) to update the mock-ups to reflect this copy change? I don't think Erik needs them to complete FE but we should keep the mock ups up to date.

**Comment by MarciMcGuireGCIO** [comment]
Sure can; thanks!

**Comment by andaleliz** [comment]
Wait, @MarciMcGuireGCIO, I just realized this ticket as been reopened. I can just use this one. I thought I had closed it out.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz Yeah, it's confusing when changes happen after a ticket is closed.  We can continue working with this one, and I'll make note that it's being re-opened.  Just re-estimate if you need to.

**Comment by MarciMcGuireGCIO** [comment]
Noting that questions about the copy came up after the ticket was closed, and this was re-opened after sprint 61 ended.  Moving to Sprint 62.

**Comment by erikphansen** [comment]
I have already merged in the PR that included the copy from Nov 22. Marci, you'll need to make a new FE ticket to update the alert to the newly revised copy.

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen thanks.  On it.  I'll post the new ticket # in Slack shortly...
