### ISSUE TITLE
[FE] VA.gov Profile - Update "sign-in email address" link copy and destination to account for login.gov credential

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33066]
## User Story

As a login.gov credential holder, I want the link under the "Sign-in email address" to account for Login.gov. 

## Tasks

**Personal Information > Email address > Sign-in email address**

- [x] Change the copy of the link for Login.gov users ("Update sign-in email address on Login.gov") 
- [x] Link to the correct page within login.gov for users to manage their credentials.

**Account security > Sign-in email address**

- [x] Change the copy of the link for Login.gov users ("Update sign-in email address on Login.gov") 
- [x] Link to the correct page within login.gov for users to manage their credentials.

## Acceptance Criteria

- [x] Change the copy of the link for Login.gov users ("Update sign-in email address on Login.gov") 
- [x] Link to the correct page within login.gov for users to manage their credentials.

## Update 12/6/2021 - This appears to be being handled in https://github.com/department-of-veterans-affairs/vets-website/pull/19516.  We are simply  going to validate and close the ticket once we confirm it works as intended.

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen do you anticipate being able to complete this ticket before Friday?  If not, are there any tips/pointers you can share that would be helpful to Zach?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 62 since we are just now learning how to log in using Login.gov today.

**Comment by erikphansen** [comment]
It looks like this work is actually getting handled as part of https://github.com/department-of-veterans-affairs/vets-website/pull/19516

**Comment by MarciMcGuireGCIO** [comment]
Thanks; @erikphansen!

**Comment by MarciMcGuireGCIO** [comment]
@Erik- we are good to close this ticket?

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio We will still monitor, but I was advised to close since another team is handling.

**Comment by Samara-Strauss** [comment]
Reopening since we haven't been able to validate this. Tickets should only be closed if the work is validated and complete on staging, and I just confirmed that we are still having issues where the "sign in email address" link copy and destination is not working.

**Comment by MarciMcGuireGCIO** [comment]
Ok, thank you. Yana asked me to close it Friday since we are not actually doing the work.

**Comment by Samara-Strauss** [comment]
> Ok, thank you. Yana asked me to close it Friday since we are not actually doing the work.

Thank you for letting me know, and I understand that our team did what we were supposed to do and that validating this ticket is blocked for legitimate reasons, but if this ticket gets closed, what is the plan for following up and validating the work? How and when do we plan to confirm the functionality actually works to determine whether things are actually done? I'd personally rather this ticket remain open, add a "blocked" label, and we can validate when the identity team has made the necessary changes. I guess we could open a new ticket, but that seems like extra work and also harder to track than just leaving this ticket open and validating when we actually can validate.

**Comment by MarciMcGuireGCIO** [comment]
Putting a block on this pending Identity completion of #32643, which has a [pull request pending review.](https://github.com/department-of-veterans-affairs/vets-website/pull/19516)

**Comment by MarciMcGuireGCIO** [comment]
Continuing to monitor #32643, which should close this ticket.

**Comment by MarciMcGuireGCIO** [comment]
Confirmed that the above changes have been completed on Staging and show Login.gov content for users who are logged in with that credential.
