### ISSUE TITLE
[FE] Profile - Login.gov  - Allow login.gov users to access direct deposit

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33062]
## Issue Description
Login.gov is being added as an acceptable credential in addition to ID.me.  Allow login.gov users to access direct deposit

---
## Tasks
- [x] Allow login.gov users to access direct deposit

## Acceptance Criteria
- [x] Allow login.gov users to access direct deposit
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen do you anticipate being able to complete this ticket before Friday?  If not, are there any tips/pointers you can share that would be helpful to Zach?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 62 since we are just now learning how to log in using Login.gov today.

**Comment by erikphansen** [comment]
This is ready to validate on staging. After signing in with a Login.gov user, you can navigate to the Profile to see that the Direct Deposit section will be shown only if the user is eligible to see it. Login.gov users should no longer see an alert saying that they need to use a verified ID.me account to access Direct Deposit.

**Comment by erikphansen** [comment]
This is currently not working because the `multifactor` flag for Login.gov users is coming back as `false` when it should always be `true` for loa3 Login.gov users. The `false` value also results in us telling users they need to set up 2FA on the Account Security page.

<img width="905" alt="Screen Shot 2021-12-03 at 8 45 05 AM" src="https://user-images.githubusercontent.com/20728956/144648220-bc2bbd6f-2aae-454d-8fa1-27e48190c8e8.png">

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO you said in Slack this is ready to validate but it looks like Erik's last comment stated it's not working. Do you know if this is actually ready for staging review?

**Comment by MarciMcGuireGCIO** [comment]
Oh good catch. I'll move that back to Current Sprint .  Sorry about that. I was just looking at the Validate column.

**Comment by andaleliz** [comment]
If this is ready, is there anyone else who can check it? I've spent most of the morning trying to validate tickets and haven't had a chance to work on any of my own yet.

**Comment by MarciMcGuireGCIO** [comment]
I'll review and also ask @Samara-Strauss to.  With AJ out and Erik gone, we're a little short of people who are familiar with how it's meant to work.

**Comment by andaleliz** [comment]
I think we have about the same level of familiarity. If it's higher priority for me to validate than complete my own sprint work I'll be glad to jump in. Hopefully the behavior is documented somewhere that anyone can jump in and follow along.

**Comment by MarciMcGuireGCIO** [comment]
Ah ok; thanks for the clarification.  I'm happy to track down documentation and validate.  I don't think it's more important than your own work, and I am sorry for the confusion!

**Comment by Samara-Strauss** [comment]
Something is not working. This message is showing when I sign in with user 36 via Login.gov, which means that direct deposit isn't loading. We know this user has direct deposit access via ID.me, so something is definitely wrong.

![image](https://user-images.githubusercontent.com/34068740/145101189-1801dbf0-808d-450a-b476-33b1a15f14d1.png)

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss I noticed that as well when I logged in a few min ago.  @tmitchellgcio @zacharymorel can you both take a look at anything you've recently moved to Staging and confirm that there isn't something going on in the FE code preventing profile info from loading fully?  Thx!

**Comment by MarciMcGuireGCIO** [comment]
Noting that whatever was causing the issue above now seems to be resolved & profile info is loading

**Comment by Samara-Strauss** [comment]
Ah -- nvm, it's working now! I can see and load the direct deposit section and update my info

![image](https://user-images.githubusercontent.com/34068740/145103314-a73cd167-2c45-41fa-8875-a07e6954db8c.png)

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio I've also confirmed that I can log in with test user 201 via Login.gov and access Direct Deposit info.   Can this be promoted now, or does it need to wait until Login.gov goes live?  Thx!

**Comment by Samara-Strauss** [comment]
This needs to be gated with the other login.gov updates and should go to prod when login.gov is ready.
