### ISSUE TITLE
SD - R&S-Set up GA/Domo dashboard for new metrics tracking

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33073]
## Issue Description
_Once metrics are confirmed we will review all events being tracked,  add new events requires being tracked _

---
## Tasks
- [x] _Create a list of items/events that we are not currently tracking or not tracking properly_
- [x] _Find the right tracking links for all items_

## Acceptance Criteria
- [x] _a list of items/events we wish to track properly_
- [x] _all highlighted Metrics have tracking links_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
List of metrics highlighted in yellow: [Analytics Spreadsheet](https://governmentcio.sharepoint.com/:x:/s/SearchDiscoveryTeam/EaK84Ve3NKtMtRB6ZM3ZWr4BE5WizM2HsjsVGUJ1BIdb0w?e=WmsgCP)
