### ISSUE TITLE
[VAMC] Provide daily support to VAMC web maintainers to include office hours, meetings, support ticket responses, and guidance [VAMC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33070]
## Story
As a new VAMC editor I need support to better understand all of my pages, so I can create a better Veteran experience

## Tasks
- [ ] Provide office hour meetings on Tuesdays and Thursdays for presenting changes and answering questions
- [ ] Respond to VAMC support tickets generated out of CMS support desk
- [ ] Monitor and support correction and training from broken links created by editors
- [ ] develop presentations and kb articles if needed from those presentations for editors

## Acceptance criteria
* Provide office hour meetings on Tuesdays and Thursdays for presenting changes and answering questions
* Respond to VAMC support tickets generated out of CMS support desk
* Monitor and support correction and training from broken links created by editors
*  develop presentations and kb articles if needed from those presentations for editors
