### ISSUE TITLE
SD - Update typeahead 2.0 cypress tests

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33084]
## Issue Description
_Update our typeahead 2.0 cypress tests to use the page object_

---
## Tasks
- [x] _Determine whether or not the existing cypress tests are a valid use case of the page object_
- [x] _Replace existing cypress e2e tests with tests using the page object_

## Acceptance Criteria
- [x] _All typeahead functionality is tested and passes
- [x] _Automated testrail run has been completed to update artifacts_
---
## Relevant info
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32142

**Comment by LindaLi123** [comment]
Reprioritized to complete [#33343](https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/33343), pulling into next sprint
