### ISSUE TITLE
SD - Form detail page background exploration

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33085]
## Issue Description
_Research to answer PO's questions regarding form detail page_

How do we measure success?
Why do not all veteran-facing forms have custom pages?
What other things need to happen? Or it fine the way it is?

---
## Tasks
- [x] _Research all historical documents related to form detail page_
- [x] _Connect with Decisions Tool's team and Analytics team for additional information needed_

## Acceptance Criteria
- [x] _Able to provide answers to the three questions_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
**Why do not all veteran-facing forms have custom pages?**
[Publishing a new form detail landing page.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/form-detail-landing-pages/Publishing%20a%20new%20form%20detail%20landing%20page.pdf) details the process of creating a detail page for a form.

**Basic detail pages:**
- When a forms manager adds a new form to the VA's forms database, a basic detail page automatically gets created (But does not always get published)
- Every form, except a few internal forms that were already in the system before Find a VA Form existed gets at least a *basic* detail page.

**Customized detail pages:**
In order for a detail page to be a customized detail page it needs to at least contain descriptive text for the "When to Use" section. 

The process to create a customized detail page:
- The additional metadata for the top 100 forms (minus the 35-40 that already had custom pages) would be drafted by Content. The list of forms needing content was broken into 3 batches.
- PO would send the draft for each batch to the VA stakeholders for them to make any corrections or changes
- That draft would be given back to Content so they could polish it and make sure if follows plain language conventions
- Those updates would be sent BACK to the VA for final approval
- PO would enter the meta data for that batch into the CMS and publish


**What other things need to happen? Or it fine the way it is?**
From Marci: "Ideally each form page would contain information on how to complete the form, and where and how to submit it.  Unfortunately, that information doesn't appear on every PDF form, and we would need someone at the VA to provide that info, and someone in Content to review and make sure it is worded according to VA web content standards."

**How do we measure success?**
Hypothesis: Form Detail Pages increase SEO and in turn increase visits and form submissions. Custom Form Detail Pages have additional information such as "When to use this form" that further increase SEO and help Veterans complete the correct form. 
Every Form Detail Page has a history in the CMS showing when it was created and published. We could possibly measure visits and submission rate before and after Form Detail Page updates.

Additional information: 
[Linda's Form Detail Pages meeting notes with Marci](https://dsva.slack.com/archives/C011K1VSTC3/p1637257295099500?thread_ts=1637245174.097500&cid=C011K1VSTC3)

[Answers from Marci on Slack](https://dsva.slack.com/archives/CUB5X5MGF/p1637695127036500?thread_ts=1637692885.035900&cid=CUB5X5MGF)

[Mini-product outline for form detail landing pages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/form-detail-landing-pages/form-detail-product-outline.md)

[Find a Form DOMO dashboard](https://va-gov.domo.com/page/447193050)
