### ISSUE TITLE
Monitoring: Datadog for VFS Teams 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33081]
## Problem Statement 
The platform's legacy monitoring solution lacks features desired by developers. Getting access to the platform's monitoring tools is a cumbersome process. The approval process can involve long delays. It's difficult to know how an app is performing without these tools. 

## Background 

- Datadog provides improved monitoring, alerting, and visualization features when compared with existing tools (Grafana and Prometheus)
- VFS developers can access Datadog directly through a web browser, without SOCKS
- Accessing Grafana through SOCKS requires setup on a user's computer 
- Metrics retained by Prometheus are limited to two weeks
- Some use cases captured [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1984790533/Monitoring+use+cases)
- _Note: for improved platform security there will be limited access to the AWS console in the future_

## Resources
Platform Website: [Platform tools page ](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-tools.1872855066.html)
Overview of [Datadog capabilities](https://www.datadoghq.com/product/)

---
## How might we? 

...make it easier for VFS Teams to use the platform's monitoring tools? 
...provide better tools for monitoring, alerting, and visualization of VFS products? 
...reduce the administrative overhead involved in providing access to tools for VFS Teams? 

## Hypothesis or Bet

- If we make it easier for VFS developers to access the platform's monitoring tools, they will enjoy a more seamless onboarding experience. 
- Providing Datadog to VFS teams will facilitate the monitoring, alerting, and visualization of VFS products.
- This will increase the quality, reliability, and understanding of VFS products. 

## We will know we're done when... ("Definition of Done")

- Datadog onboarding & offboarding process established for VFS users
- Datadog usage & guidelines published on the Platform Website

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
_TBD_

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by mchelen-gov** [comment]
Additional notes:

_Background_
- DD provides monitoring, alerting, and visualization features unavailable in existing monitoring tools

_Hypothesis or bet_
- Providing DD features to VFS teams will facilitate the monitoring, alerting, and visualization of VFS products
- This will increase the quality, reliability, and understanding of VFS products

_AC_
- onboarding & offboarding process for DD VFS users
- platform website documentation for VFS DD usage & guidelines

**Comment by ElijahLynn** [comment]
Per discussion with @jhouse-solvd here, posting our use case. 

The VFS-CMS team needs read only access to the CMS Dashboards here > https://vagov.ddog-gov.com/dashboard/lists?q=cms, so they can have similar access as to what they had with Grafana.

**Comment by jhouse-solvd** [comment]
Follow up to @ElijahLynn comment above [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9709#issuecomment-1207076855)

It might be good to evaluate if VFS teams can get access to Datadog without the Platform Infrastructure team being a blocker. @mchelen-gov may have guidance for use cases where this would make sense.

**Comment by jhouse-solvd** [comment]
Discovery around VFS user cases should be undertaken to understand which features and data they need access to. It would be good to engage Platform research experts to help gather that information.

**Comment by tpharrison** [comment]
Hi @jhouse-solvd. In May/June, my team (auth exp) started using Datadog to monitor activity related to our vets-api endpoints and alert us of any unusual activity.  

In July, we lost access when the switch was made to the GovCloud account. Our team has left [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43996) open which outlines our request for Datadog access. 

Just following up to find out if/when we can get access.  Thanks!

**Comment by jhouse-solvd** [comment]
@tpharrison - Hi Tom! Thanks for the nudge and your patience. We're looking into this and should have more info to share soon. We want to understand how teams use Datadog to ensure we have it set up correctly.

**Comment by tpharrison** [comment]
@jhouse-solvd Thanks for the quick response!  Any idea on how long the review will take?  Just looking for a rough timeframe to help with team planning.

**Comment by jhouse-solvd** [comment]
**UPDATE 11/7/22**

We aim to provide an excellent for teams using the platform's monitoring tools. To do this, we're working w/ the Platform Service Design team to understand the monitoring needs of VFS developers (and use cases). 

The Service Design team will help us to perform discovery research that we hope will provide valuable insights. From there, we'll look to onboard select users to Datadog and collect their feedback. We're not yet sure about the timeline, but we should know more in the coming weeks. 

For VFS teams that want to use Datadog…(inc. those that previously requested access), stay tuned as we'll follow up with you to learn more soon!

**Comment by TheBoatyMcBoatFace** [comment]
Hi @jhouse-solvd -

I'm the new PM for Platform CMS DevOps and looking for access to Datadog. I'd like insight into the my team's infrastructure and a sandbox board to build out/finetune some visualizations.

I've worked with Domo, Sentry, Elastic, & Grafana, but never Datadog. I'd be glad to provide feedback/beta test features/functionality if needed.

**Comment by cferris32** [comment]
Hi there, I'm a vets-api developer for the VAOS team and we leverage Datadog as one of our health monitoring tools. Currently I have read-only access but would like to upgrade my account so I can enhance our monitoring as needed, especially since we have a big release coming soon. Let me know as soon as this would be feasible and I'm happy to provide credentials and take any extra steps needed on my end. Thanks so much!

**Comment by ksk385** [comment]
Hi, I am from the Chatbot team and we would like to test out DataDog for our monitoring/alerting needs. How can we get accounts for my team to try it out? Thanks!

**Comment by TheBoatyMcBoatFace** [comment]
> Hi @jhouse-solvd -
> 
> I'm the new PM for Platform CMS DevOps and looking for access to Datadog. I'd like insight into the my team's infrastructure and a sandbox board to build out/finetune some visualizations.
> 
> I've worked with Domo, Sentry, Elastic, & Grafana, but never Datadog. I'd be glad to provide feedback/beta test features/functionality if needed.
> 

**Following up on my Datadog request** - lack of access has become a blocker for some of my projects, so I'm trying, if possible, to get this resolved sooner rather than later.

If there is anything I can do to help the process along, please let me know.

**Comment by oseasmoran73** [comment]
![image](https://user-images.githubusercontent.com/10648480/208526353-7ad2ed18-4d8c-4695-9798-07854dd504b8.png)

FYI, you can set perms boundary. It is not a single team, but rather a list

**Comment by jhouse-solvd** [comment]
@tpharrison @cferris32 @ksk385 @cohnjesse @vhenry07 @kjduensing 

You previously requested or expressed interest in access to Datadog. If you have a few minutes, we'd love to get your input on this survey: https://ows.io/qs/ns7w5ro0

We want to understand various use cases to ensure that tools, documentation, and resources are available to support your needs properly. Your input will help us prepare for release. ☺️

**Comment by chrisj-usds** [comment]
> @tpharrison @cferris32 @ksk385 @cohnjesse @vhenry07 @kjduensing
> 
> You previously requested or expressed interest in access to Datadog. If you have a few minutes, we'd love to get your input on this survey: https://ows.io/qs/ns7w5ro0
> 
> We want to understand various use cases to ensure that tools, documentation, and resources are available to support your needs properly. Your input will help us prepare for release. ☺️

Tagging @batemapf and @klawyer who are interested in getting onboard with DD asap

**Comment by batemapf** [comment]
thanks @chrisj-usds. filled out survey.

**Comment by jhouse-solvd** [comment]
_A question came up in Slack:_ 

> Any idea if the platform team will be the ones making requests to the DOTS team for access on behalf of VFS teams, or if VFS teams should just go ahead and request access directly from the DOTS team? or does the platform team have direct administrative control over [vagov.dd-gov.com](http://vagov.dd-gov.com/)? 

We're considering options and hope to minimize onboarding friction for VFS teams.

**Background**
- DOTS has full administrative control vagov Datadog
- DOTS must provision Okta and Datadog accounts 
- Platform can manage users and roles _once they are in Datadog_
- Once a VFS team member has a Datadog account, the Platform needs to ensure that the team member is assigned a role with permission to needed features and resources 

**Options**
1. VFS Teams request access directly from DOTS 
2. Platform requests access from DOTS on behalf of VFS Teams

What do you think would work best?

**Comment by batemapf** [comment]
how about:

  1.   ask DOTS to grant all platform users who currently have access to grafana access to datadog, with read only perms
  2.  figure out some criteria for granting write perms
  3.  use that criteria to change perms of previously created read only accounts to read and write, since this can be done without involvement of DOTS

then you’ll need to incorporate a version on this into the onboarding process im guessing
________________________________
From: Jesse House ***@***.***>
Sent: Wednesday, January 4, 2023 3:55:01 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Patrick Bateman ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Monitoring: Datadog for VFS Teams (Issue #33081)


A question came up in Slack:

Any idea if the platform team will be the ones making requests to the DOTS team for access on behalf of VFS teams, or if VFS teams should just go ahead and request access directly from the DOTS team? or does the platform team have direct administrative control over vagov.dd-gov.com<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fvagov.dd-gov.com%2F&data=05%7C01%7C%7C84566785388345d805ed08daee95f675%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638084625095152224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7MIb7mxZiQASApMMqLITzzuBrFAOzQV5jRH3sqrLSPg%3D&reserved=0>?

We're considering options and hope to minimize onboarding friction for VFS teams.

Background

  *   DOTS has full administrative control vagov Datadog
  *   DOTS must provision Okta and Datadog accounts
  *   Platform can manage users and roles once they are in Datadog
  *   Once a VFS team member has a Datadog account, the Platform needs to ensure that the team member is assigned a role with permission to needed features and resources

Options

  1.  VFS Teams request access directly from DOTS
  2.  Platform requests access from DOTS on behalf of VFS Teams

What do you think would work best?

**Comment by jhouse-solvd** [comment]
@batemapf - This is a great idea. 

Regarding number 1, _(I believe)_ the only challenge to that workflow would be setting up users in Okta: 

Currently, users have to log in to Datadog via Okta. When speaking w/ DOTS previously, a user account has to be provisioned in Okta, and each user has 24 hours to respond to the invite. Once the user has accepted the Okta invite, DOTS can add Datadog as an application to be launched from Okta. 

Regarding numbers 2 and 3, I think that's spot on. We're hoping to define those criteria soon, and we're looking to VFS teams to help us understand which features and resources they need access to within Datadog.

**Comment by tpharrison** [comment]
Hi Jesse

On 1/4, I was asked to fill out this survey (https://ows.io/qs/ns7w5ro0)
but I think I filled it out a couple of weeks ago.  I was wondering if you
can confirm.

Thanks.

**Comment by cferris32** [comment]
> @tpharrison @cferris32 @ksk385 @cohnjesse @vhenry07 @kjduensing
> 
> You previously requested or expressed interest in access to Datadog. If you have a few minutes, we'd love to get your input on this survey: https://ows.io/qs/ns7w5ro0
> 
> We want to understand various use cases to ensure that tools, documentation, and resources are available to support your needs properly. Your input will help us prepare for release. ☺️

Hello, I've filled out the survey and am still in need of write-access in Datadog from my original comment. Please let me know if there's anything else I can do to help make this happen. Thanks so much!

**Comment by jhouse-solvd** [comment]
Hi @cferris32 - Thanks so much for filling out the survey. We'll be reviewing and synthesizing feedback soon. 

Before providing write access to Datadog, the Platform needs to develop roles and permissions for VFS teams (See #47066) and publish documentation on the Platform Website (_along with a few other tasks_). The information you've provided will be instrumental in making those things happen. 

We're meeting with leadership tomorrow to discuss the next steps and hope to provide you with more information - including the release plan and schedule - in the coming weeks. 

We appreciate your patience while we work to provide this solution. If this presents any blockers for your team, please escalate to your VA product owner to aid with prioritization. 

cc: @mchelen-gov

**Comment by jhouse-solvd** [comment]
UPDATE 1/31 (also shared during weekly Team of Teams meeting)

**Monitoring for VFS teams: Read-only (RO) access to Datadog - beginning February 21** 

We’re excited to announce the upcoming release of Read-only (RO) access to Datadog for VFS Teams beginning February 21, 2023!

**What’s included in the upcoming release?** 

- VFS Team members will be able to access Datadog and view dashboards and monitors. 
- Documentation will be made available on the Platform Website covering the following topics: 
  - Datadog overview - Welcome, here’s what to expect
  - Dashboards and monitors - a list of pre-configured dashboards with health and performance data for major backend applications (ie Vets-API and related services) with accompanying explainer info!
  - How to request access to Datadog (for new VFS Team members, post-release) 

**How will VFS teams get access?** 
- As part of this release, we plan to invite existing VFS team members in bulk. 
  - VFS team members can expect to receive an invite to Okta from DOTS the week of 2/21
  - VFS team members will launch Datadog from DOTS Okta 
  - Note: DOTS Okta is the single-sign-on solution used to access tools provided by DOTS
- After this release, new VFS team members will request access to Datadog through the Platform Website or through #vfs-platform-support

**What do VFS teams need to do before then?** 
- Nothing at this time. :) However, please let us know of any issues or concerns through this issue. 
- Stay tuned for additional updates in upcoming Team of Teams meetings and Slack!

cc: @mchelen-gov

**Comment by nanotone** [comment]
As requested by @jhouse-solvd, I'm adding a note here to describe a use case that the Benefits fast-track team is looking for (including a few steps that are already done).

- [x] I added two new StatsD metrics in vets-api to track successes and failures of one particular external API call: department-of-veterans-affairs/vets-api#12021
- [x] After this PR ☝️ was merged and deployed, I confirmed that the new metrics are visible in the Datadog Metrics Explorer (see screenshot below)
- [ ] I'd like to set up one or more monitors in Datadog to post an alert to a specific Slack channel whenever something looks off with this API call. Two possible queries might be:
  - Percentage of failing API calls exceeds some threshold -- say, 5%?
  - Number of successful API calls is very low, compared to historical trends
- [ ] These monitors may need tweaking in order to provide good signal. For example, the team may decide that outages occurring over weekends are not actionable, and can be ignored.

At time of writing, the vets-api code posts a message to one Slack channel for every success, and another channel for every failure; our current process is just to manually check these channels once a day for abnormalities. This is workable because failed API calls, while not ideal, are not catastrophic for any Veteran. We'd just like the process to be more automated.

<img width="455" alt="Screen Shot 2023-03-15 at 13 47 49" src="https://user-images.githubusercontent.com/282869/225412913-1706995c-5373-4195-acdc-69d815952a77.png">

**Comment by mchelen-gov** [comment]
@nanotone Thanks for the description! It sounds like write access to the monitors/alerts would satisfy the 2nd two boxes.

**Comment by ElijahLynn** [comment]
Now that VFS teams have access, can we get https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+Access+to+Datadog updated? It currently says:

> NOTE: Datadog is not currently supported for VFS teams. However, support for VFS teams will be addressed as part of this initiative: [[Datadog] Monitoring for VFS Teams #33081](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/33081)
