### ISSUE TITLE
[FE] My VA 2.0 Enhancements: Technical discovery on surfacing Claims' status requiring evidence upload

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33089]
## Background

Per [Slack Thread](https://dsva.slack.com/archives/C909ZG2BB/p1637251243195700), we would like to have some technical discovery performed on whether we can surface the claims' status of uploading evidence.  If we could do this, it would help elevate action items for the veteran on the dashboard.
Tressa shared [this spreadsheet ](https://docs.google.com/spreadsheets/d/15_KjIF68VmxzjJcBDOQUOMkrgj1UplkvFI6AwS-uU0M/edit#gid=871749236) on some of the statuses researched initially (in early My VA days).

## Tasks

- [ ] Perform technical discovery and document findings in GH
- [ ] Review with the team

## Acceptance Criteria

- [ ] Complete a technical review of the possibility and effort to elevate/highlight claims' status requiring evidence uploads

**Comment by tmitchellgcio** [comment]
Unfortunately, the team responsible for this is new-ish and may not have all the answers on the claim status tool quite yet. However, you can still try to talk to them -- #benefits-team-1 is currently responsible for the claim status tool.

**Comment by tmitchellgcio** [comment]
From Sade Ragsdale: Our team is in the process of designing the digital experience for Supplemental Claims, so the ideal moment to remind a Veteran to upload evidence is WIP, if you will.
Here is a [Process Flow Diagram](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1654096034291/25f4086b638b48828941c4d6aa330f1df1c9527a?sender=u0d70ac6e87daa7c066838517) for Supplemental Claims
Here is a [Form / Journey Breakdown](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1653490344368/8a035f7639e54b70edb4dc7002cae95967c36d1a?invited=true&sender=u0d70ac6e87daa7c066838517) for Supplemental Claims

**Comment by tmitchellgcio** [comment]
Without an API there isn't a lot to work on in terms of technical discovery and they stated it's still a WIP. This should likely go back into the current sprint once the team has a a place for us to gather the information from for their apis
