### ISSUE TITLE
Update Collaboration Cycle Dashboard for Education teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33096]
## Issue Description
The Collaboration Cycle Dashboard currently includes the Education Application (BAH) team (github label `bah-edu`). This team rolled off of VA.gov in September 2021. They were replaced by 2 teams:

1. My Education Benefits (github label `afs-dgib`)
2. AFS Education (github labels `afs-education`)

---
## Tasks

- [x] Remove Education Application (BAH) from the Total Issues by Team chart, however please keep their tickets included in the count for the Total Issues by Status chart.
- [x] Add the My Education Benefits team to the Total Issues by Team chart (there currently should be 0 tickets logged for this team)
- [x] Add the AFS Education team to the Total Issues by Team chart (there should be 16 currently)

## Acceptance Criteria
- [x] The Collaboration Cycle Dashboard correctly reports issues from the My Education Benefits and AFS Education team.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rjohnson2011** [comment]
Updated the above BigQuery & corresponding Domo chart. Recording 0/16 for the new teams as mentioned above. Tagging @shiragoodman for review.

**Comment by shiragoodman** [comment]
This looks good to me. Thank you!
