### ISSUE TITLE
Create new card for category

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33099]
## User Story
As a Platform OCTO lead, I want to see how many Staging Review issues fall into the different categories so that I understand where VFS teams are having trouble adhering to standards.

Assignee: @it-harrison 
Peer Reviewer: @sterkenburgsara 

## Description
~~At the 11/15 Post-launch review of the Update Guidance and Documentation initiative, Product Owner Rachael Roueche communicated that she'd prefer Product Support to not review staging review issues that have the VA.gov Experience Standard category of "Other" until the percentage of issues classified as "Other" exceeds 10% of all issues logged. As of 11/15, the current percentage of "Other" tickets was 4.67% (see [Post Launch Review](https://docs.google.com/presentation/d/1oD0sw9odYmDGFepWdT-P_k2O_k14epnizv8Uji6kfPY/edit#slide=id.gfd4ca99aba_0_7), slide 4). This metric was manually calculated using github queries.~~

~~In order to more efficiently recognize when the "Other" category exceeds 10%, Platform Product Support would like to request an additional chart be added to the Collaboration Cycle Dashboard. The chart should be a pie chart and mimic the chart shared in the presentation linked above. An appropriate title would be "Total issues by VA.gov Experience Standard category."~~

Note: the above is no longer true, however Governance team believes there would still be value in showing how Staging Review issues are dispersed by category as it was listed within our[ Collab Cycle Dashboard metrics.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2365063202/Collab+Cycle+Dashboard+metrics)

Criteria for category "Other":
- `CC-Dashboard` label
- `CCIssue00.00` label

Criteria for category "Overall user experience":
- `CC-Dashboard` label
- `CCIssue01.01` OR `CCIssue01.02` label

Criteria for category "Content organization":
- `CC-Dashboard` label
- `CCIssue02.01` OR `CCIssue02.02` OR  `CCIssue02.03` OR `CCIssue02.04` OR `CCIssue02.05` OR `CCIssue02.06` OR  `CCIssue02.07` label

Criteria for category "User flows and navigating":
- `CC-Dashboard` label
- `CCIssue03.01` OR `CCIssue03.02` OR  `CCIssue03.03` OR `CCIssue03.04` OR `CCIssue03.05` OR `CCIssue03.06` OR  `CCIssue03.07` OR `CCIssue03.08` OR `CCIssue03.09` OR  `CCIssue03.10` OR `CCIssue03.11` label

Criteria for category "Components and pattern standards":
- `CC-Dashboard` label
- `CCIssue04.01` OR `CCIssue04.02` OR  `CCIssue04.03` OR `CCIssue04.04` OR `CCIssue04.05` OR `CCIssue04.06` OR  `CCIssue04.07` OR `CCIssue04.08` OR `CCIssue04.09` OR  `CCIssue04.10` OR `CCIssue04.11`  OR `CCIssue04.12` label

Criteria for category "Content styleguide":
- `CC-Dashboard` label
- `CCIssue05.01` OR `CCIssue05.02` OR  `CCIssue05.03` OR `CCIssue05.04` OR `CCIssue05.05` OR `CCIssue05.06` OR  `CCIssue05.07` OR `CCIssue05.08` OR `CCIssue05.09` OR  `CCIssue05.10` OR `CCIssue05.11` label

Criteria for category "Color, typography and visual elements":
- `CC-Dashboard` label
- `CCIssue06.01` OR `CCIssue06.02` OR  `CCIssue06.03` label

Criteria for category "URL standards":
- `CC-Dashboard` label
- `CCIssue07.01` OR `CCIssue07.02` OR  `CCIssue07.03` OR `CCIssue07.04` OR `CCIssue07.05` label

Criteria for category "Links and button labels":
- `CC-Dashboard` label
- `CCIssue08.01` OR `CCIssue08.02` OR  `CCIssue08.03` label

Criteria for category "Markup and meta data":
- `CC-Dashboard` label
- `CCIssue09.01` OR `CCIssue09.02` OR  `CCIssue09.03` OR `CCIssue09.04` OR `CCIssue09.05` OR `CCIssue09.06` label

Criteria for category "Non-text content and media":
- `CC-Dashboard` label
- `CCIssue10.01` OR `CCIssue10.02` OR  `CCIssue10.03` OR `CCIssue10.04` OR `CCIssue10.05` OR `CCIssue10.06` OR `CCIssue10.07` label

Criteria for category "Assistive tech and device support":
- `CC-Dashboard` label
- `CCIssue11.01` OR `CCIssue11.02` OR  `CCIssue11.03` OR `CCIssue11.04` OR `CCIssue11.05` OR `CCIssue11.06` OR  `CCIssue11.07` OR `CCIssue11.08` OR `CCIssue11.09` OR  `CCIssue11.10` OR `CCIssue11.11` OR `CCIssue11.12` OR `CCIssue11.13` OR `CCIssue11.14` OR `CCIssue11.15` OR `CCIssue11.16` OR `CCIssue11.17`  OR `CCIssue11.18` OR `CCIssue11.19` OR `CCIssue11.20` OR `CCIssue11.21` OR `CCIssue11.22` label

**Note:** The above labels may not be inclusive of every issue as this ticket was created in November 2021 and there have been additions/changes to the VA.gov Experience Standards since then. Please check the[ VA.gov Experience Standards on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) to verify all issues within each category are accounted for.

## Tasks
- [x] Using the existing data set of Staging Review issue tickets (currently being utilized in the existing Collab Cycle dashboard cards), create a new card showing distribution of all issue ticket by VA.gov Experience Standard category
   - A pie chart may make the most sense as it shows the percentage of the whole, however feel free to experiment and try different things.
 -  [x] Share chart with Shira and Ray via #platform-governance-team channel for review and feedback (no need to share with Shira first before Ray)
- [x] Make any requested changes.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Collaboration Cycle Dashboard shows how all Staging Review issue tickets are dispersed by VA.gov Exp Std category

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
CC dashboard link: https://va-gov.domo.com/page/1340527018?userId=1646566899

**Comment by sterkenburgsara** [comment]
@it-harrison when you get to this one, can we possibly do this together so I can see how it's done / work through it with you?

**Comment by it-harrison** [comment]
@sterkenburgsara sure, I will ping you.

**Comment by shiragoodman** [comment]
New "Counts of tickets by Experience Standard Category" card has been added to [dashboard. ](https://va-gov.domo.com/page/1340527018?userId=1646566899)
