### ISSUE TITLE
[Design] Profile - Login.gov - Add link to Resources & Support page from FAQs for LOA1 users

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33094]
## Issue Description
Login.gov is being added as an acceptable credential to VA.gov.   There is a non-verified level for login.gov in addition to the verified level.  For all LOA1 users, the FAQ page shown below needs a link to the [verification Resources and Support page](https://staging.va.gov/resources/verifying-your-identity-on-vagov/) to the FAQ shown below to mention Login.gov in addition to ID.me.

![image](https://user-images.githubusercontent.com/73354907/142501334-2cbc7e9c-2d2d-428d-b7a3-cc410b489ba0.png)

---
## Tasks
- [ ] For all LOA1 users, the FAQ page will display a link to the [verification Resources and Support page](https://staging.va.gov/resources/verifying-your-identity-on-vagov/) 

## Acceptance Criteria
- [ ] For all LOA1 users, the FAQ page will display a link to the [verification Resources and Support page](https://staging.va.gov/resources/verifying-your-identity-on-vagov/) 

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen do you anticipate being able to complete this ticket before Friday?  If not, are there any tips/pointers you can share that would be helpful to Zach?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Moving to Sprint 62 since we are just now learning how to log in using Login.gov today.

**Comment by andaleliz** [comment]
Sharing an update - I've created the mock-up with the link, but want to confirm that the page we link to will be updated in time. There hasn't been activity on the related content ticket #30279 for 24 days so figured I should double check.  

If it's won't updated when we launch our changes, we can update the FAQ content in the interim. The FAQ currently duplicates copy on that content page so I figure I should use whatever updates they're proposing for that too.  However, I can't access the updates because they're on the VA Sharepoint instance and I'm having PIV access issues that ESD couldn't help with.  SO:

I will drop into content office hours today to:
- have Danielle review the proposed link copy in my mock-up
- get an update on timing for their page update
- ask her to provide copy for the FAQ that mirrors whatever they're putting on their page if the update update timing doesn't work out.

Hope to be able to close this out today.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for keeping this moving, @andaleliz!

**Comment by andaleliz** [comment]
Reviewed with Danielle, and she confirmed they'll time the update of their page with the launch of login.gov, so we can move forward with a link.  Here's a mock-up displaying the link copy:

Learn how to verify your identity on VA.gov 

![image](https://user-images.githubusercontent.com/55992116/144468881-91f522f8-7f83-413e-b16c-3e420ee83361.png)

Link should point to `/resources/verifying-your-identity-on-vagov/`

Ready for FE 🎉

**Comment by MarciMcGuireGCIO** [comment]
@erikphansen and @tmitchellgcio - FYI -- this is ready for you now!

**Comment by Samara-Strauss** [comment]
Is there a frontend ticket for this? This is not on staging, and it is unclear whether Erik or Taylor ever actually saw this or did anything with it if there wasn't a frontend ticket.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss checking...

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss I believe it's this ticket - #33066.  It was assigned to Erik originally, but he did not get a chance to work on it last week.  I just assigned to @tmitchellgcio.  Please let me know if this is not the correct task.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I don't think that's the correct ticket. The FE work for this ticket would be to replace the `how will VA verify my identity` FAQ that appears for LOA1 users with the link as shown in [this screenshot](https://user-images.githubusercontent.com/55992116/144468881-91f522f8-7f83-413e-b16c-3e420ee83361.png)

**Comment by MarciMcGuireGCIO** [comment]
My mistake; I apparently got things mixed up from this [Slack thread ](https://dsva.slack.com/archives/C909ZG2BB/p1637186225180400)where everything started popping.  I should gotten clarification.  I'll create a ticket for this now.  I'm sorry for the confusion.

**Comment by MarciMcGuireGCIO** [comment]
FE ticket here #33624; I will let Taylor know and add to the Sprint.

**Comment by Samara-Strauss** [comment]
Thanks!
