### ISSUE TITLE
Create post mortem document for Login bug on 11/16

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33090]
## Issue Description
Create a post mortem document for the login bug that occurred on 11/16 ([LINK](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/359/files))

---
## Tasks
- [x] Create documentation around the issue, how it arose, and how it can be caught in the future

## Acceptance Criteria
- [x] Document created
- [x] Meetings scheduled to discuss
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kwoly** [comment]
PR here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/359
