### ISSUE TITLE
SD - Explore design system Process to add type ahead 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33106]
## Issue Description
_Explore the design system process and discover what steps are necessary to get a component added to the design system_

---
## Tasks
- [ ] _Collaborate with Design system team_

## Acceptance Criteria
- [ ] _Understand all necessary steps to get a component added to the design system_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Official instructions on contributing to the Design System: [https://design.va.gov/documentation/contributing-to-the-design-system](https://design.va.gov/documentation/contributing-to-the-design-system)

**Experimental Design:** 
The [experimental design](https://design.va.gov/experimental-design/) section is for experimental patterns/components. It can be moved out of the experimental section once the conditions are met according to Kevin H.:
- It has been in production for 3 mos without issue
- There is evidence that we have seen an improvement in desired outcomes/data

**Steps to adding a component/pattern to the [Experimental Design System](https://design.va.gov/experimental-design/):** 

- Create an Experimental Design System Request from [this template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=caw310&labels=vsp-design-system-team&template=experimental_design_request.md&title=). Here is an [example](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/503) from Search UI.
- Create visual of component/pattern with callouts from [Anatomy callouts Sketch library template](https://www.sketch.com/s/aaa5c25f-6991-4aac-a6ed-d378bdff7727).
- Code is welcome but not required
- If an experimental component or pattern sits on design.va.gov for 6 months with no validation documented, it will be removed by the design system team.


**Adding a component/pattern to the [Official Design System](https://design.va.gov/)**
- See **6** on [https://design.va.gov/documentation/contributing-to-the-design-system](https://design.va.gov/documentation/contributing-to-the-design-system)
- Create a Documentation Request [from this template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=&template=documentation_template.md) 
- Include research validating the usefulness 
- Include Sketch files
- Include code: [Instructions for contributing code](https://design.va.gov/documentation/developers#contributing-experimental-design-code) to the design system.
