### ISSUE TITLE
Update label for Debt Resolution team in Collaboration Cycle Dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33108]
## Issue Description
It appears that the Debt Resolution team has recently updated their label to` vsa-debt`. The Platform Collaboration Cycle Point tracker has been updated to reflect the change in label. The Collaboration Cycle Dashboard will also need to be updated.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] The Collaboration Cycle Dashboard references the correct github label for Debt Resolution team.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rjohnson2011** [comment]
Updated the query & Domo chart - 0 results today. Let me know if this looks good to close @shiragoodman

**Comment by shiragoodman** [comment]
@rjohnson2011 this looks good to me! Although I can't actually see what label you're using for each team. Is there a way to see that in DOmo?

**Comment by rjohnson2011** [comment]
Yes, the search terms are visible [here](https://va-gov.domo.com/datasources/42fed405-0f59-4835-821f-5e95f759f4e8/details/settings) under the `Details -> Query` section.

**Comment by shiragoodman** [comment]
@rjohnson2011 I see this message when I click that link:
![image](https://user-images.githubusercontent.com/71330581/144127176-25152855-1d56-44ab-afe1-a0463f918a5b.png)

**Comment by rjohnson2011** [comment]
An account with Admin privileges would need to grant permissions for you to see page. Do you know who created your account? They may be able to help.

**Comment by shiragoodman** [comment]
thanks! I think it was Brian. I'll open an Analytics support ticket.
