### ISSUE TITLE
Create Calendly guide for Platform use

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33116]
## Issue Description
There is currently no documentation on how Calendly is used in the Collaboration Cycle. We need to create some so that if someone needs to take over Calendly, they have a basic understanding of how it works

---
## Tasks
- [x] Document how Calendly works with the design intent/midpoint and staging reviews (how it links to the Collab Cycle calendar, we have variables set up to show information in the invite, we have criteria around how close to the invite date VFS can book a meeting)
- [x] Create a new document on product support

## Acceptance Criteria
- [x] There is a page in Confluence/Platform Products & Services/Collaboration Cycle with Calendly documentation 
- [x] Anyone on Product Support could read this documentation and have a basic understanding of how Calendly is used within Collab Cycle
- [x] Users with Calendly access know how to change settings for Collab Cycle meetings (Michael Fleet, Naomi Marcussen & Shira Goodman)
- [x] Non-Product Support Platform Users will have a basic idea of how they might be able to use Calendly
- [x] Reserved timeslots for Calendly Collaboration Cycle reviews are visible in the Calendly guide

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 I made a couple minor changes to the AC, but otherwise looks good - thanks!

**Comment by shiragoodman** [comment]
@allison0034 in this doc, can you be sure to list the timeslots we have reserved for Design Intent, Midpoint and Staging? Since we no longer have the Review Blocks included in the Platform Collaboration Calendar, I feel like they should be listed _somewhere_ outside of Calendly.

**Comment by allison0034** [comment]
@shiragoodman can you provide me with the settings we currently have for Calendly?

**Comment by shiragoodman** [comment]
@allison0034 here's some screenshots of the Design Intent/Midpoint settings
![image](https://user-images.githubusercontent.com/71330581/144924481-d306040a-f1f0-4d9e-b886-c65630937511.png)
![image](https://user-images.githubusercontent.com/71330581/144924531-cadb665d-67b8-468e-8a0b-6bb7c37c69fd.png)
![image](https://user-images.githubusercontent.com/71330581/144924598-86d6dd94-37f8-4475-ba60-38e84aac8e2f.png)
![image](https://user-images.githubusercontent.com/71330581/144924659-1501b984-8f86-43e0-b3ce-fcf891db206a.png)
![image](https://user-images.githubusercontent.com/71330581/144924702-1f865e96-4a84-4572-a84b-94f80f623f99.png)
![image](https://user-images.githubusercontent.com/71330581/144924761-23f9487d-4fa9-4afd-b42d-3d5bd10e9208.png)
![image](https://user-images.githubusercontent.com/71330581/144924813-1f9f1cbc-deea-4fec-86ba-b04d1b43ac5d.png)
![image](https://user-images.githubusercontent.com/71330581/144924870-acdc0b15-345f-4ed3-b90c-40d8356b2fac.png)

**Comment by allison0034** [comment]
@shiragoodman I made the changes you requested in the comments and this is ready for a final review. https://vfs.atlassian.net/wiki/spaces/PPST/pages/2017034292/Allison+-+Calendly+guide

**Comment by shiragoodman** [comment]
@allison0034 approved!
