### ISSUE TITLE
User stuck in auth loop

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33111]
## Issue Description
User reported error, and logs identified a possible edge case for auth to loop forever. For this particular user, logs reported successful login attempt 2 times per minute.

This has not been reproducible by Identity team

Type: dslogon custom

### Original Description
Original Issue - https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team-sensitive/358

I was able to confirm that the user did in fact loop hundreds of times on 11/12 and 10/31. They all appear to be successful logins without any errors being returned to indicate why this is occuring.

Trevor checked the accounts table and didnt find any issues with this users account (confirmed there is an idme uuid for them).

Damien from IAM also checked in MPI and confirmed nothing is wrong with the users identity.

The current hunch is that this may be a frontend bug, potentially already resolved, but until we can confirm the bug is resolved Kyle will be looking into this.
---
## Tasks
- [x] Determine if/where this is an edge case in logic that could cause this behavior

## Acceptance Criteria
- [x] User is able to successfully authenticate
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kwoly** [comment]
Setting this aside for now. I have verified that SSO works in the following cases:

1. Login into VA directly, and navigate around the site successfully calls the keepAlive checks
2. Logging into another platform with ID.me -> Navigating to VA -> SSO Auto authenticates based on existing session

It is possible this has corrected itself, or could be related to an adblocker, or a browser such as Brave that can block setting localstorage

Setting this down for now

**Comment by AGarcia-Clarity** [comment]
Couldn't find anything in the logs for the user flow of what could cause this and couldn't replicate the bug.  Recommend pushing to the backlog until we can gather more information.

**Comment by Kwoly** [comment]
Adding onto what @AGarcia-Clarity has said. I have been unable to replicate and have tried:
- Disabling all cookies
- Disabling 3rd party cookies
- Using security focused browser such as Brave
- Using Ad Blockers such as Ublock/AdBlocker
- Using Internet Explorer

**Comment by AGarcia-Clarity** [comment]
@nsoutouras @joeniquette This particular ticket can be closed however another ticket should be created to address the inconsistency of system time.

**Comment by nsoutouras** [comment]
New ticket: #[34052](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/34052)
