### ISSUE TITLE
Establish Initial Handshake with LGY's API

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33119]
## Background
We want to establish a connection point with the LGY LoB and now that they have implemented a fix, we can proceed.

## Tasks
- [x] Establish a connection or handshake between VA.gov and LGY API
- [x] Note any issues that might need to be revisited by either team

## Acceptance Criteria
- [x] A successful connection has been made
- [x] Any notes have been codified for later use.
