### ISSUE TITLE
update "disallow" robot file for VAMC upgrades

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33112]
## Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task

For 11/29
Remove the following:

- [x] /providence-health-care/
- [x] /alaska-health-care/
- [x] /madison-health-care/
- [x] /milwaukee-health-care/
- [x] /hines-health-care/
- [x] /iron-mountain-health-care/
- [x] /chicago-health-care/
- [x] /southern-oregon-health-care/
- [x] /new-mexico-health-care/
- [x] /bay-pines-health-care/
- [x] /west-palm-beach-health-care/
- [x] /atlanta-health-care/
- [x] /lexington-health-care/
- [x]  /dublin-health-care/

For 12/1
Remove the following:

- [x] /central-western-massachusetts-health-care/
- [x] /central-ohio-health-care/
- [x] /columbia-missouri-health-care/
- [x] /northern-arizona-health-care/
- [x] /mountain-home-health-care/
- [x] /st-louis-health-care/
- [x] /marion-health-care/
- [x] /north-texas-health-care/
- [x] /amarillo-health-care/
- [x] /el-paso-health-care/
- [x] /texas-valley-health-care/
- [x] /greater-los-angeles-health-care/
- [x] /phoenix-health-care/
- [x] /louisville-health-care/

## Acceptance Criteria
Only the system names above remain in the robot.txt file

**Comment by mmiddaugh** [comment]
merged
