### ISSUE TITLE
Content updates to SGLI and FSGLI pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33127]
## Issue Description
Stakeholder Steve Fital reached out with changes that he'd like made to the [SGLI ](https://www.va.gov/life-insurance/options-eligibility/sgli/)and [FSGLI](https://www.va.gov/life-insurance/options-eligibility/fsgli/) pages. The Public Health Service is now using the SOES system so there are related changes that need to be made to both pages.

Changes to be made:
[https://app.zenhub.com/files/133843125/443b2ee7-4d8b-41c0-9951-bce1a9914d56/download](https://app.zenhub.com/files/133843125/443b2ee7-4d8b-41c0-9951-bce1a9914d56/download)

We need to assess these changes and show a final draft to Beth before publishing.

## Tasks
- [x] Use assessment criteria to determine changes to be made
- [x] Update content in Drupal
- [x] Copyedit (Randi)
- [x] Final review (Beth)
- [x] Publish (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Content ready for a final review
- [x] Updated content is live on the site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Servicemembers’ Group Life Insurance (SGLI): http://preview-prod.vfs.va.gov/preview?nodeId=767
Family Servicemembers’ Group Life Insurance (FSGLI): http://preview-prod.vfs.va.gov/preview?nodeId=765

**Comment by RLHecht** [comment]
Thanks, @lunascoop These updates look good to me. I also removed the Internet Explorer references on both pages and will ask the stakeholder about them before publishing. @bethpottsVADEPO this is ready for your final review.

**Comment by bethpottsVADEPO** [comment]
@RLHecht It looks like the content you landed on is slightly different from what the stakeholder requested, so you should probably share the preview links before publishing.

**Comment by RLHecht** [comment]
Stakeholder approved and I published the page. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
