### ISSUE TITLE
Standardized Forms KPIs: Replacement time to complete ETL

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#33120]
## Issue Description
Problems with the methodology used to calculate our "Average Time to Complete" metric on the Standardized Forms KPI dashboard have been identified by VFS teams, who note that the number is much lower than they'd expect based on Grafana data and user research. Analytics confirmed that metric was being calculated by session through technical discovery in ticket #31789. More details from that process can be found in comments.

New dataflow will need to be constructed, test card QA'ed, and then new dataflow will be connected to the existing card. _(Note: Do not replace existing card, as this will throw off tracking Object IDs in our Activity Logs.)_

---
## Tasks
- [x] Create copy of current [ETL](https://va-gov.domo.com/datacenter/dataflows/139/details#datasets) connected to new beta [output dataset](https://va-gov.domo.com/datasources/3aa4d5fe-db25-40e1-b98c-f58a53d6900b/details/overview)
- [x] Create test copy of avg. time [card](https://va-gov.domo.com/page/1800029966/kpis/details/661656013) to connect to beta output dataset
- [x] Edit new ETL to meet the following requirements:
  - [x] Time to complete is NOT grouped by `session`
  - [x] Time to complete is only calculated for users who completed the form.
  - [ ] Additional steps added to ensure that users who successfully submitted the same form more than once do not receive disproportionately long "Time to Complete" totals
- [ ] QA new dataset when ready
- [ ] Connect dataset to current card

## Acceptance Criteria
- [ ] All "Time to complete" cards and dashboard definitions have been updated to reflect the proper calculation methodology.

**Comment by jonathan-epstein13** [comment]
Trying to remove 'session' column from dataset, take out '0.00' and/or blank to account for those 'Time to complete is only calculated for users who completed the form'.

Additional steps added to ensure that users who successfully submitted the same form more than once do not receive disproportionately long "Time to Complete" totals- Will see if there is a way to see the user has submitted the forms once.

**Comment by chloedotbrown** [comment]
Hi Jonathan - I dig some digging into this one today, and I think it might actually require some upstream solutions instead of ETL changes alone, so I'm tagging @obrienjulie and @bsmartin-ep. 

I took a couple passes at [ new ETL](https://va-gov.domo.com/datacenter/dataflows/145/details#datasets) strategies, but even the approaches the ones that seem like they should, if anything, _overestimate_  the time spent on each form don't move the needle on "avg. time to complete" that much. And they don't really make sense compared to the avg. number of sessions per form (screenshot below). 
<img width="560" alt="Screen Shot 2021-11-29 at 4 04 38 PM" src="https://user-images.githubusercontent.com/45518242/143976233-aa7d97c5-1b98-438a-ba41-d7ce8c7eb01c.png">

Plus, when you do a count of [submissions per form per user](https://va-gov.domo.com/datasources/faa70b93-489a-444b-8820-49447d9b0ac8/details/data/table), there's a weird right tail of very high numbers. While I'm sure that some users do submit more than one 526EZ, it seems unlikely that anyone's actually done so 200+ times. 

I'm wondering if we might want to put fresh eyes on how and where we're calculating this metrics. Is this something we could move upstream and do in its own view in BigQuery? Does 51:53 in the [forms_funnel view](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&d=vsp_sites&p=vsp-analytics-and-insights&t=vw_forms_funnels&page=table&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_forms_funnels) still look like it's set up to capture what we thought it would? What should we try next?

**Comment by chloedotbrown** [comment]
Jonathan, Julie, Brian, and I discussed this issue today (12/2). Next steps will be testing some strategies in BigQuery view. Because the solution is outside the scope of an ETL and this ticket, closing here. Work to continue on #31789.
