### ISSUE TITLE
[Design] Update all Profile mockups to remove breadcrumbs

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33122]
## Background

Breadcrumbs were removed from Profile in #31229.  The Sketch pattern library and all the files that use it (all of the Profile mockups) need to be updated to remove the breadcrumbs.

## Tasks

- [ ] Remove breadcrumbs from Sketch pattern library
- [ ] Remove breadcrumbs from all Profile mockups

## Acceptance Criteria

- [ ] Sketch pattern library no longer shows breadcrumbs
- [ ] Profile mockups no longer show breadcrumbs

**Comment by MarciMcGuireGCIO** [comment]
Closing this ticket; this has already been completed.
