### ISSUE TITLE
[Design] My VA: Update components and files to reflect the removal of breadcrumbs

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33124]
## Background

Breadcrumbs were removed from My VA.  As a result, the Sketch pattern library component, and files that use it, need to be updated to reflect the change across all My VA mock-ups.

## Tasks

- [ ] Update Sketch pattern library component
- [ ] Update Files using component

## Acceptance Criteria

- [ ] All Sketch component, files and mock-ups are updated to reflect the removal of breadcrumbs in My VA.
