### ISSUE TITLE
Make access to RDS available to Backend Tools Team

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#33129]
## Description
Backend Tools needs the ability to quickly restore a production vets-api RDS snapshot to a running instance.

## Background/context 
During a key rotation, one of the records was not re-encrypted properly and a need arose to pull from a previous RDS snapshot. No one on BE Tools currently has access to RDS and the ops person on duty wasn't able to provide the data.

## Technical notes
The RDS CLI tools have a `rds-restore-db-instance-from-db-snapshot` command which can be issued with the DB and Snapshot identifier. Restoration can also be done via the RDS Web UI.

Once a new RDS instance, based on the snapshot, is stood up, either production or a production-like-Rails-instance would be pointed at it for complete db replacement or data extraction, respectively.

---

## Tasks

- [ ] A process for quick restoration of data from an RDS snapshot is available for use (e.g. RDS access is granted, a runbook is defined, or a script/button can be run/pressed for temporary access).

## Acceptance Criteria

- [ ] Backend Tools is able to quickly restore data from a snapshot in the event of a similar DB failure/corruption issue.

---

### Reminders

- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
