### ISSUE TITLE
Add VALI information to life insurance hub landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33121]
## Issue Description
Stakeholder Steve Fital asked us to put a link to their VALI page on the life insurance hub landing page because there are now communications pieces that are sending users to our page to find out info about the new program that starts in January 2023. 

Link to VALI page: https://www.benefits.va.gov/insurance/VALI.asp

## Tasks
- [x] Determine where on page we should put link (Beth/Randi)
- [x] Send suggestion and text to stakeholder (Randi)
- [x] Update text in Drupal (Randi)
- [x] Review and publish page (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] VALI text and link are live on the site

**Comment by RLHecht** [comment]
Here's the suggested text we sent to Steve:

[Veterans Affairs Life Insurance (VALI)](https://www.benefits.va.gov/insurance/VALI.asp)
Learn about VALI, our new life insurance program for Veterans with service-connected disabilities that takes effect January 1, 2023.

**Comment by RLHecht** [comment]
Steve approved the language to put into the promo spot. The page is published and changes are live. Closing ticket.
