### ISSUE TITLE
SD - R&S Create Excel file for good and bad articles 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33139]
## Issue Description
_Create an excel file for R&S article ratings in aggregate view _

---
## Tasks
- [x] _Sam collaborate with the Analytics team to set up the file_

## Acceptance Criteria
- [x] _an Excel file let us review articles rated good or bad in multi dimensions_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by srsuddath** [comment]
This ticket can be closed! We can take and upload the excel data file to the S&D folder to save it for sharing

**Comment by srsuddath** [comment]
[https://app.zenhub.com/files/133843125/2b288ca6-13b2-4092-aea3-0bd6c4f1326c/download](https://app.zenhub.com/files/133843125/2b288ca6-13b2-4092-aea3-0bd6c4f1326c/download)
