### ISSUE TITLE
Update VGLI application deadline alerts and other content for December 11

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33135]
## Issue Description
After December 11, 2021, there will no longer be an extended deadline for signing up for VGLI. Starting on December 12, it goes back to the normal 240 days to apply without medical and 1 year and 120 days with medical. 

Currently, we have an alert about the extended deadline on the life insurance [options and eligibility](https://www.va.gov/life-insurance/options-eligibility/), [VGLI](https://www.va.gov/life-insurance/options-eligibility/vgli/), and [SGLI](https://www.va.gov/life-insurance/options-eligibility/sgli/) pages. We also have content about this on the [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#claims-and-applications) page in the question "Can I have more time to apply for Veterans' Group Life Insurance (VGLI) after separation?"

We need to remove these alerts and remove the accordion on the FAQs page.  We can't publish these changes until 12/11/21.

## Tasks
- [x] Remove alerts on life insurance pages
- [x] Remove question from FAQs page 
- [x] Check if mentioned in chatbot and remove
- [x] Review and publish (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] VGLI deadline extension is no longer mentioned on live site

**Comment by RLHecht** [comment]
Email Steve to see if we can do this on the 10th since the 11th is Saturday.

**Comment by RLHecht** [comment]
@lunascoop The stakeholder said we can remove these Monday morning

**Comment by lunascoop** [comment]
@RLHecht these pages have been updated and are ready for review. Also removed question from chatbot. The PR is ready for your review.

- About VA insurance options and eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=764
- Veterans’ Group Life Insurance (VGLI): http://preview-prod.vfs.va.gov/preview?nodeId=769
- Servicemembers’ Group Life Insurance (SGLI): http://preview-prod.vfs.va.gov/preview?nodeId=767
- Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580
- Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475

**Comment by RLHecht** [comment]
Thanks @lunascoop ! These have all been published. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Pages are live. Closing ticket.
