### ISSUE TITLE
[UNPLANNED] Move Search and Appoint Rep to Staging

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33131]
## Background
We need to move the search and appoint rep portions of the Representative feature into staging so that we can validate what is left to be built.

## Tasks
- [x] Move the local feature to staging for:
  - Search: https://staging.va.gov/view-change-representative/search/
  - Appoint`*`: https://staging.va.gov/view-change-representative/appoint/

`*` - this url might change to something like `update` or `request`

## Acceptance Criteria
- [x] Search Rep is requested to be moved to staging
- [x] Appoint Rep is requested to be moved to staging

**Comment by jason-gcio** [comment]
@candy-gcio: Appoint will come in a later ticket as it gets developed
