### ISSUE TITLE
COVID booster content updates to 2 pages on 11/19

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33144]
## Issue Description
We made updates about booster content to the main COVID vaccine mini hub page and the boosters and additional doses page. We need to also send this text out for translation. 

## Tasks
- [x] Update English pages (Danielle)
- [x] Review and publish (Randi)
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translators (Randi)

## Acceptance Criteria
- [x] English pages have new content live on site
- [x] Translated pages have new content live on site

**Comment by RLHecht** [comment]
@lunascoop Here is the content for the Spanish and Tagalog pages. 

[https://app.zenhub.com/files/133843125/cf5c2167-03d5-414e-af72-4658307c38f0/download](https://app.zenhub.com/files/133843125/cf5c2167-03d5-414e-af72-4658307c38f0/download)

[https://app.zenhub.com/files/133843125/923a009d-dc93-4496-b18e-f445c2989cab/download](https://app.zenhub.com/files/133843125/923a009d-dc93-4496-b18e-f445c2989cab/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394

**Comment by RLHecht** [comment]
I reviewed and published these pages. Will send live links to Mateo.

**Comment by RLHecht** [comment]
Pages are live. Closing ticket and will reopen if Mateo's team has any changes.
