### ISSUE TITLE
Modify availability for Collaboration Cycle Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33153]
## Issue Description
Earlier this year, Product Support limited the available weekly timeslots for Collaboration Cycle Staging Review to 2 timeslots on Thursday. This change was made so that Product Support could:

1. Better manage workload 
   - 2 maximum Staging Reviews per week opposed to 6 maximum previously.
2. Better manage schedule
   - With the reviews being only on Thursday, the team was able to start the week knowing what staging reviews were planned, and knew to verify that all artifacts were complete and available each Monday morning.

Since the launch of the new process in July, there have been several instances where teams did not provide complete artifacts by Monday morning. If/when this occurred, Product Support would notify the team that artifacts were not provided on time so their Staging Review would have to be postponed. Instead of postponing to the next day or the next Collaboration Cycle timeslot, the review would be delayed to the next Staging Review timeslot... AKA the following Thursday, a full week later.

Also since launch, there have been a few instances of teams asking for a non-Thursday Staging Review timeslots for several reasons including, 1) ability to complete staging before close of sprint, 2) to meet stakeholder deadlines or 3) because the Thursday timeslot they'd like is already fully booked. 

The purpose of this ticket is to modify the available timeslots for Collaboration Cycle Staging Review to allow for more flexibility with VFS teams.

---
## Tasks
- [x] PS team to determine how much to increase Staging Review timeslots each week, while still allowing CC reviewers enough time to adequately complete reviews. 

## Acceptance Criteria
- [x] Solution has been reviewed and approved by Product Support team members 
- [x] OCTO has given their approval on the change to Staging Review availability
- [x] More Staging Review timeslots are available to VFS teams
- [x] VFS teams are aware of the new Staging Review timeslots (Announcement in ToT, #vfs-all-teams on Slack and Change history post)
- [x] PS documentation is updated reflecting new Staging review timeslots (on the Calendly guide page @allison0034 or elsewhere)
- [x] Calendly settings are updated for Staging Review 
- [x] Confirm that Calendly Design Intents and Midpoint Reviews are not impacted by the Calendly Staging Review changes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@peggygannon Can you please attempt to complete the AC? thanks!

**Comment by peggygannon** [comment]
Hi, @shiragoodman I added some AC. Let me know what you think!

**Comment by peggygannon** [comment]
Hi, @shiragoodman Here is our recommendation for adding more Staging reviews slots: 

We recommend adding a slot: 
1 on Tuesday
1 on Friday

We recommend a Tuesday and Friday slot: 
- To allow PS team enough time to communicate with the VFS team ahead of the meeting (and not having days prior to meeting fall during the weekend). 
- To allow enough time to run the bulk upload. 

We don't recommend adding a slot on Monday, to avoid having the days prior to a staging review span over the weekend.

**Comment by shiragoodman** [comment]
Thanks @peggygannon . Would the Tuesday and Friday timeslots overlap with the existing timeslots or would they be new?

**Comment by peggygannon** [comment]
@shiragoodman We were thinking they overlap, so PS reviewers still maintain a manageable number of reviews each week.

**Comment by shiragoodman** [comment]
Ok that sounds good to me. We can discuss at Standup today and get the teams opinions.

**Comment by shiragoodman** [comment]
sorry, I have some additional questions. @jimuhh @peggygannon 

1. Which timeslot on Tuesday? 11:00 or 11:30 am ET? or both?
2. Would the new timeslots for staging (Tuesday and Friday) still be available for Midpoint and/or Design Intent? Assuming yes, based on your original comment, but please confirm.
3. If we're allowing the Tuesday and Friday timeslots to be for any review type, we now have 4 available timeslots a week for Design Intent and/or Midpoint and 4 or 5 timeslots a week available for Staging (depending on your response to question 1 above). My (minor) concern is that if a team books the Friday timeslot for Staging, and another team _requests_ (not schedules) a Midpoint or Design Intent on a Monday or Tuesday, they won't be able to meet with the team for another week (since we still ask for 2 days lead time). Could we add another timeslot at the end of the week for Design Intent and/or Midpoint. Maybe on Friday? Or Wednesday?

**Comment by jimuhh** [comment]
@shiragoodman Those are all good questions. Since these issues are going to affect the whole team, I would like to set up a one-hour Lean UX-style working session where we could go collaborate our way through them. I'm fine in condensing and documenting whatever we come up with but frankly don't feel that with Peggy leaving, I'm in a position to drafting policies for the team without hearing from more experienced colleagues.

**Comment by shiragoodman** [comment]
@jimuhh sorry, just seeing this comment now. did you still want to move forward with setting up a working session or was the discussion at standup sufficient? Please let me know.

**Comment by jimuhh** [comment]
@shiragoodman -- I think the standup was sufficient, so if there's no objection, I'm going to go ahead and put a draft of the availability proposal in the "Ideas" section of Platform Product Support confluence site.

**Comment by shiragoodman** [comment]
awesome! Thank you @jimuhh !

**Comment by shiragoodman** [comment]
@jimuhh @peggygannon Rachael approves the new timeslots! Please move forward with the remaining tasks. I will work with @allison0034 to get Calendly updated.

**Comment by shiragoodman** [comment]
@allison0034 I added the new dates to Calendly and it's live now.

**Comment by jimuhh** [comment]
acceptance criteria met. Closing issue
