### ISSUE TITLE
Create 2022 protected disability and death pension rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33163]
## Issue Description
Rates for protected disability and death pension change on December 1, 2021. We need to update our current page with the 2022 rates and turn the 2021 page into a past rates page.  

Here are the 2022 rates:
[https://app.zenhub.com/files/133843125/88f8c1ec-b200-49b4-bc63-8ae48e70789a/download](https://app.zenhub.com/files/133843125/88f8c1ec-b200-49b4-bc63-8ae48e70789a/download)

## Tasks
- [x] Create 2022 rates page (Selina)
- [x] Check rates against doc and review page (Randi)
- [x] Create 2021 past rates page (Selina)
- [x] Review page (Randi)
- [x] Publish all pages (Randi)
- [x] Set up left nav (Randi)
- [x] Alert stakeholder that rates are live (Randi)

## Acceptance Criteria
- [x] 2022 rates page is live
- [x] 2021 rates live as a past rates page

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

2022 VA protected disability and death pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=5090
Past rates: 2021 VA protected disability and death pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=39641
Past rates: 2020 VA protected disability and death pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=11021
Past rates: 2019 VA protected disability and death pension rates: http://preview-prod.vfs.va.gov/preview?nodeId=6925

**Comment by RLHecht** [comment]
These pages have all been checked and reviewed. Will publish with the rest of the rates pages.

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
