### ISSUE TITLE
[Parameter Store] Transmit and store keys for the My Education Benefits app (in production)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33162]
## Description
The new My Education Benefits app will need to communicate with the Digital GI Bill (DGIB) services developed by AFS. These services are hosted outside VA.gov and will use JWT tokens to grant access to the Vets-API services that connect to them.

## Background / Context 

- This was already done for non-prod environments (see #31317)
- @cesaresantiago and @wonhchoi will transmit the keys to operations via Keybase when they are ready to get this going in production

---
## Tasks
- [ ] Make a path in parameter store
- [ ] Get the keys from them ie (Transmit keys via Keybase)
- [ ] Verify that Vets-API can use the keys in prod

## Acceptance Criteria 
- [ ] The My Education Benefits API on vets-API must have access to the uploaded JWT keys to generate JWT tokens that will allow communication with the DGIB third-party services in production

**Comment by jhouse-solvd** [comment]
@cesaresantiago & @wonhchoi - Do you have a provisional timeline for getting this up in production?

**Comment by jhouse-solvd** [comment]
Closing. Please re-open if this is still needed.
