### ISSUE TITLE
Configure LGY in Staging

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#33172]
## Background
Part of the groundwork for this integration with LGY involved some network configuration with the DevOps folks

## Tasks
- [x] Set up the forward proxy
- [x] Get auth token from LGY for SQA env and add to AWS

## Acceptance Criteria
- [x] Api Key has been added to AWS param store
- [x] A PR has been requested for merging in the devops repo
