### ISSUE TITLE
[UX] Research -Look into recommended frequency to prompt for demographic updates

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33186]
## Use Cases
1. As a veteran I only want to be asked to update my demographic information at certain intervals so that I don't have to go through it at every single appointment. 

## Description
While we cannot actually make the decision on how often a veteran should be prompted to update his/her demographic information, we CAN provide a recommendation for best practice based on research.  We need to determine the ideal frequency for programmatically determining when to ask the veteran for demographic updates. 

## Tasks
- [x] Do competitive analysis (Cerner, Epic, Phressia)
    - [x] Can we find out what Cerner does?
       - [x] Talk to Shane, Shawn, Stephen, Adrian, or Patrick to find out who to talk to.
- [ ] Look into VetLink data (Talk to Shawn Adams)
- [x] Discuss with check-in team and maybe doing a mapping exercise

## Acceptance Criteria
- [ ] Document UX audit

**Comment by Evafloyd** [comment]
@kristenmcconnell How do you define demographic information? I'm thinking mailing address vs emergency contact might have a different frequency

**Comment by Evafloyd** [comment]
Or purely traditional demographics; such as age, gender, race and ethnicity

**Comment by kristenmcconnell** [comment]
I think our current scope is all the different addresses, email, phone numbers, next of kin, and emergency contact information.

**Comment by Evafloyd** [comment]
Update: we've learned there is a directive to the staff to inquire about changes in address, next of kin, emergency contact with every visit.

**Comment by Evafloyd** [comment]
Lauren Alexanderson also helped us: Spokane confirmed that they check demographics every time a veteran comes in.

**Comment by Evafloyd** [comment]
I've created a page in GitHub documenting current landscape research https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/frequency-demographic-updates.md
