### ISSUE TITLE
Create "New VFS team" ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33198]
## Issue Description
When a new VFS team begins building on VA.gov, we need to ensure that the team is added to the VFS Roster. 

The VFS Roster is a valuable resource for Platform teams. Use cases:

1. Analytics team...?
2. Platform research initiatives.
3. reference for Collaboration Cycle

However the process for getting a new team added to the VFS Roster is non-existent. Product Support is proposing creating a "New VFS Team" github ticket template that can be accessed from the Platform Orientation page on Platform Website. The ticket would be created by the Product Manager or Product Owner. The ticket template would ask the PM/PO to complete/fill in the following fields:

1. Team Name
2. OCTO-DE Product Owner
3. VA Business Owner
4. Crew
5. Github team label
6. Team launch date
7. Public slack channel
8. Other team names

The ticket template will include actions for the new VFS team/ PM/PO:

1. Ensure all team members assign themselves and complete the Platform Orientation ticket (link to Platform Website Platform Orientation page not the gh template)
2. Schedule ATO Orientation with Faith Owusu-Sekyere. This is required for all new VFS teams. DM Faith via Slack to schedule.
3. Review VA.gov product directory. Submit request to add products owned by team if not listed.

The ticket template will include actions for Platform:

1. Add field input information to VFS Team Roster

---
## Tasks
- [ ] Create template in directory
- [ ] Create "sandbox" spreadsheet where PM/POs can update team info
- [x] Create checklist including PM/PO information and ticket instructions
- [x] Include completion signoff for PM/PO in checklist

## Acceptance Criteria
- [ ] Template exists in directory and has clear, intuitive name
- [ ] Template checklist outlines what information PM/PO needs to enter where to complete ticket requirements
- [ ] Template checklist includes completion sign-off and heads-up from PM/PO
- [ ] Template contains the fields listed at start of this document. 
- [ ] A small informational paragraph is available for teams

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
hey @jimuhh and @Saraharaba8  - I _may_ have an additional piece of information that will be included in this ticket - ATO orientation. However I need to check with leadership first. I will follow up.

**Comment by Saraharaba8** [comment]
Sounds good! > hey @jimuhh and @Saraharaba8  - I _may_ have an additional piece of information that will be included in this ticket - ATO orientation. However I need to check with leadership first. I will follow up.

**Comment by shiragoodman** [comment]
ok I updated the "actions for the new VFS team/ PM/PO:" section. If you have questions, please let me know.

**Comment by jimuhh** [comment]
I changed acceptance criteria to clarify that all info will be entered into the new template.

**Comment by jimuhh** [comment]
Hi @shiragoodman and @Saraharaba8 -- I have a [draft of the new team ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md) for you to review. LMK how it looks and if it's OK, I'll remove the "WIP" text.

**Comment by Saraharaba8** [comment]
@jimuhh Hi Jim. No feedback on my end. Everything looks good.

**Comment by jimuhh** [comment]
Hi @chaseakirby -- this ticket is complete. @shiragoodman did want a brief blurb about the process on the [platform orientation part ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams)of platform products and services site but that ask wasn't captured in this ticket. That page is what I'm working on next.

**Comment by chaseakirby** [comment]
@jimuhh Great, I'll go ahead and check those boxes as complete and move this to done. 
I created [#35510](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/35510) for the operational guidance blurb of the process that Shira asked for. We can use that ticket to track it and discuss the operational guidance. I also linked that ticket to this one in case we needed to refer back to it.

**Comment by chaseakirby** [comment]
@jimuhh Also, I see that your PR in GitHub is approved but not merged back into the master. Can you do that before I close this out fully? Here's a [link to the steps for Merging back to master](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#Merging-the-changes-with-the-master-GitHub-issue-template) if you need them.

**Comment by jimuhh** [comment]
@chaseakirby -- I "squashed and merged" the PR. LMK if that's correct.

**Comment by chaseakirby** [comment]
@jimuhh Looks good to me! Thank you! I'll close this ticket and we can work off the other one for the guidance.
