### ISSUE TITLE
Reorganize/reformat the VFS Team Roster

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33199]
## Issue Description
The current organization of the VFS Team Roster is not ideal. There are tabs that do not have a logical order, and information is duplicated across tabs. There is also not a consistent format for logging VFS team information, and VFS team member information. 

We would like to reorganize the VFS team roster to include 2 tabs. The first tab will be "VFS Teams" and will include the following information:

1. Team Name
2. OCTO-DE Product Owner
3. VA Business Owner
4. Crew
5. Github team label
6. Team launch date (if known)
7. Public slack channel

The second tab will be "VFS Team Members" and will include the following information:

1. Name
2. Role
3. Email
4. Github handle
5. Start date (if known)
6. VFS Team (populated via lookup from "VFS Team" tab)

---
## Tasks
- [x] Create the 2 new tabs in the VFS Roster
- [x] Move existing team member information from the machine-readable tab to the new VFS Team Members tab
   - if information is missing, no need to search Slack. Add only what is available.
- [x] Refer to the VSA Roster to ensure the VFS Teams and VFS Team Members tabs are accurate (see image below)
- [x] Notify Analytics team on their Slack channel of new tabs (no longer using machine-readable tab). CC Shira on message
- [x] After receiving approval from Shira, delete the old tabs

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/b08bba7e-7b7e-4c90-81b9-7230c0279fff)

## Acceptance Criteria
- [x] The VFS Roster is appropriately organized
- [x] The entire VFS Roster is machine readable in a form that will enable easy searching and filtering by whatever system we end up using to display it. 
- [x] The VFS Roster is set up for easy addition of new team members and deletion of old team members
- [ ] The new VFS Roster has been shared on #platform-team channel -  Note 1/11: No need to share as the new format will not impact platform teams.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by seanasewell** [comment]
@shiragoodman Can you provide the link to the VFS team roster? I am having troubles finding it.

**Comment by shiragoodman** [comment]
VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=877379155

**Comment by jimuhh** [comment]
I added an acceptance criteria to make this entire document machine readable so that wherever it ends up, sorting, filtering and searching will work seamlessly.

**Comment by jimuhh** [comment]
The "sandbox" version of the VFS roster [is here](https://docs.google.com/spreadsheets/d/149iiJ28cb2gYTHCfwNSpRbDcipE3drElWy9WqNYRjdk/edit#gid=1313704819). Please review.

**Comment by shiragoodman** [comment]
@jimuhh thank you! Here are my thoughts:

- Rename "VFS Table V2" to "VFS Individuals"
- Rename "VFS Teams V2" to "VFS Teams"
- Delete tabs, "VSA Leadership" "VFS teams (machine readable)" "VSA teams" and ALL other tabs (both hidden and non-hidden)
- use the same formatting for "VFS Individuals" and "VFS Teams" tabs
- freeze header row of both tabs/tables

Let me know when you make these changes :)

**Comment by jimuhh** [comment]
Changes made. Renamed file to [VFS Team Roster 2022](https://docs.google.com/spreadsheets/d/149iiJ28cb2gYTHCfwNSpRbDcipE3drElWy9WqNYRjdk/edit#gid=1250715584)
For some reason the alternate row shading didn't work on VFS Teams tab. Any ideas how to fix?

**Comment by shiragoodman** [comment]
@jimuhh i unfroze and unfiltered the table and got  the alternate row shading to work - thanks!

I am going to move these tabs into the live VFS Team Roster and delete the existing tabs (I plan on saving a copy externally in case we need to reference it). Once I'm done with that, would you be able to do 1 last peer review and then we can validate the acceptance criteria?

**Comment by jimuhh** [comment]
@shiragoodman Sure. Let me know when that's in and I'll snag somebody.

**Comment by shiragoodman** [comment]
@jimuhh ok it's ready for you! The [VFS Team Roster ](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)is updated. the "machine readable" tab has not been deleted yet - waiting on the OK from Analytics Team.

**Comment by jimuhh** [comment]
@shiragoodman -- Cool. Just so they know: all the tabs are now machine readable.

**Comment by jimuhh** [comment]
@shiragoodman -- I'm ready to share w/ Platform teams channel. Good to go?

**Comment by shiragoodman** [comment]
Actually @jimuhh, I think we should remove that from the AC. I am concerned that sharing it will only draw attention to the fact that it's in Google Sheets. I don't want to put us in a position where we're forced to take it down without having a better solution in place.
