### ISSUE TITLE
Modify Platform Orientation ticket to have actions for new VFS team member and Platform

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33197]
## Issue Description
The Platform Orientation template has been a list of tasks that the new VFS team member should complete to be successfully oriented to VA.gov Platform. Historically, Platform team members assigned this ticket to new folks, however in ticket #29919, new guidance was added on Platform Website to direct new VFS team members to self-assign themselves this ticket. In order to encourage VFS teams to self-assign themselves this ticket, it would be beneficial to share with VFS teams the goals of the Platform Orientation template:

1. A checklist for new VFS team members to complete so that they may be successfully onboarded to VA.gov Platform.
2. An intake for Platform so that new VFS team members are added to the VFS Team Roster (and potentially other future needs).

In order to achieve goal # 2, the Platform Orientation template will need to be updated/restructured to request the appropriate VFS Roster information. The template will also need to be updated so that Platform is notified when action is necessary (ie what is the trigger for Platform to add folks to the roster? Will we have a default assignee? Will we ask the new VFS team member to share this ticket on #vfs-platform-support? If so, what team will they tag?)

---
## Tasks

- [x] Redesign the [Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template) so there are:
 1. Fields to be completed by new VFS team member:
  - Name
  - Role
  - Email
  - Github handle
  - Start date
  - VFS Team 
 2. Actions to be completed by new VFS team member:
   - (see current Onboarding Checklist)
 3. Actions to be completed by Platform
   - Add new VFS team member to VFS Team Roster
 4. Welcome message stating purpose of template (see [VSA Onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=onboarding&template=VSA-Onboarding.md&title=VSA+Onboarding+-+%5Bname%5D) for reference)

- [x] Determine which github labels should be included in the ticket
- Note: vsp-product-support label automatically added per template <br />
- [x] Update the [Platform Orientation page](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html):
- Update header from "New Hires" to "New VFS Team Members"
- Update Platform Orientation Template link (url has changed since label was added)   

## Acceptance Criteria
- [x] VFS team members are incentivized to self-assign themselves the Platform Orientation template
- [x] VFS team members are able to add the requested info to the template
- [x] VFS team members understand the purpose of the template
- [x] There is clearly documented and actionable Acceptance Criteria within the template
- [x] The Platform Orientation page has been updated with the new Platform Orientation template link

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@jimuhh i reviewed your changes to the template and made some additional changes (updated links, added acceptance criteria). Tasks 1, 2, and 3 above, however please verify that task 4 is complete. The updated template has been published and can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=vsp-product-support&template=orientation-epic.md&title=Platform+Orientation+Template

**Comment by jimuhh** [comment]
![UI of Github template](https://images.zenhubusercontent.com/61534d745b131645912bb60a/5aaa8084-db1b-442a-8c23-83f3f0ace26d) So I update this one w/ pull request?

**Comment by shiragoodman** [comment]
@jimuhh I am adding a new task/AC because the link on Platform Website will need to be updated (since we are adding a label to the template). Let me know if you have any questions.

**Comment by shiragoodman** [comment]
@seanasewell I've updated this ticket to reflect what still needs to be completed. Also [here is the PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/34709) @jimuhh created. I have since merged his changes and made a few other, minor updates. Please let me know if you have any questions still - thanks!

**Comment by shiragoodman** [comment]
hey @seanasewell. Right now when you go to Platform website and click the Platform Orientation link [you see this. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template) However, our team label has been added to the ticket so the new url [needs to lead here. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=vsp-product-support&template=orientation-epic.md&title=Platform+Orientation+Template) Do you see the difference? I got the latter link by going to the [GH issues page](https://github.com/department-of-veterans-affairs/va.gov-team/issues), selecting [New Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) and then choosing my correct template. This is always where you'll find the most current templates as links cannot be trusted :)

**Comment by jimuhh** [comment]
**Dang.** Complex much? Hey @shiragoodman can you remind me of where the staging space for Platform pages is again? I couldn't find it among my many confluence bookmarks.

**Comment by shiragoodman** [comment]
also @seanasewell I see the Platform Website page has been updated to "New Team Members" - can we please change to "New VFS Team Members" ? Sorry this was a last minute change from yesterday. Thanks!

**Comment by jimuhh** [comment]
@shiragoodman is that the place where we make edits to content we want to go live on the va.gov platform site?

**Comment by shiragoodman** [comment]
@jimuhh correct!

**Comment by shiragoodman** [comment]
the page I linked above it for Collaboration Cycle. Since this is an Orientation ticket, you'll need to update the Getting Started space: https://vfs.atlassian.net/wiki/spaces/GS/overview

**Comment by jimuhh** [comment]
Got it. Thanks!

**Comment by jimuhh** [comment]
Great. I edited the link for that template on the Getting Started/Orientation page and published.

**Comment by shiragoodman** [comment]
thanks @jimuhh. Did you publish to Platform Website too? using scroll viewport?

**Comment by jimuhh** [comment]
[It's in there](https://vfs.atlassian.net/wiki/plugins/servlet/ac/com.k15t.scroll.scroll-viewport/k15t-vpc-overview-page), but I don't seem to have publish permissions

**Comment by shiragoodman** [comment]
@jimuhh let's find time in the morning and I can walk you through it. You should have permission

**Comment by jimuhh** [comment]
Published

**Comment by jimuhh** [comment]
Checked off the two remaining tasks.  I would call this done.

**Comment by shiragoodman** [comment]
yay! thanks @jimuhh .

@chaseakirby did you create a second ticket for creating the operational guidance? If so, I think so of the AC items here need to be moved over (or deleted if they already were moved). This is good to close :)

**Comment by chaseakirby** [comment]
@shiragoodman Yep! This ticket [35127](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/35127) has the tasks for creating the operational guidance. I copied over one AC and copying over another that I think makes sense. I think all the rest make sense to stay in this ticket as they are for the VFS team interacting with the updated ticket.
