### ISSUE TITLE
[Platform Infrastructure] Implement scheduling to optimize effectiveness of "Office Hours" meetings

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33208]
## Description
Based on feedback from the Operations team and Ops Office Hours (OOH) attendees, it would be good to schedule meeting attendees and topics. This would help ensure the right Ops personnel is available to consult. 

If there are no planned attendees, the time can be used for internal team discussions or freed up as focus time for team members.

## Background/context 
OOH schedule is M/W/F @ 1300 ET

## Technical notes
PM and TL will implement Calendly or similar 

---
## Tasks
- [ ] Implement scheduling for OOH
- [ ] Communicate changes with VFS and Platform crew teams

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
@oseasmoran73 is adding a recurring reminder that requests teams to add agenda items 

we will communicate that change once implemented

**Comment by oseasmoran73** [comment]
Notification will go out at 930AM M/W/F. See bot [reminder](https://dsva.slack.com/archives/CJYRZK2HH/p1653331471036179)

**Comment by oseasmoran73** [comment]
@jhouse-solvd I am in favoring of closing this ticket, seeing if bot helps & iterating accordingly. Thoughts?

**Comment by oseasmoran73** [comment]
Bot is now announcing office hours thread prior to meeting. Closing ticket as criteria has been met initially and iterate accordingly
