### ISSUE TITLE
[Design]- Profile - Personal Information Revision - design help text near each personal info field

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33209]
## Background
As a Veteran, I want to understand why the VA is asking for highly sensitive personal information on the Personal Information page so that I don't feel hesitant or fearful about providing it.  

This ticket was spawned from [a comment in another related ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32327#issuecomment-971975617).  

## Tasks
- [ ] Create a new mockup showing what it might look like to have some info with notes below each field on the Personal Information page as Danielle suggested near the end of the above-referenced comment.  Use placeholder text until Danielle can assist with the language.
- [ ] Add mockup to this ticket
- [ ] @ Danielle in this ticket or schedule time with her to discuss
- [ ] Update the mockup with recommended changes
- [ ] Ensure that the changes are reflected in prototype being built for upcoming user research (this will be detailed in a separate ticket)

## Acceptance Criteria
- [ ] Mockup include Content-approved language near each field to explain what each piece of information is used for.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - circling back re: one FAQ vs. info within each personal info section - I created a task for this last week after Danielle's feedback on the initial content request.  

Hopefully we can decide on a direction for the prototype before Sprint planning (or possibly make that decision after user testing).  LMK if you want to chat. Thanks!

**Comment by Samara-Strauss** [comment]
Thanks, @MarciMcGuireGCIO! Based on [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32327#issuecomment-971975617), it sounds to me like Danielle recommends one FAQ re: "why do we ask for this?" and not multiple FAQs. So, I don't think we have any issues here.

What do we need to wrap up this ticket? Anything else?

**Comment by MarciMcGuireGCIO** [comment]
Thank you @Samara-Strauss. I think we are good to go.
