### ISSUE TITLE
[Slack] Update ops-managed channels from "vsp-" to "platform-"

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33207]
## Description
The platform is moving away from the usage of the term "VSP". The channels that the Operations team manages in DSVA Slack need to have their name changed to "platform-<channel-name>". 

## Background/context 
The Operations team manages the following channels in DSVA Slack: 
- vsp-operations
- vsp-operations-internal

## Technical notes
Need to consider the impact on any automation that relies on specific channel names. 
May need to engage DSVA Slack admins in order to make the change. 

---
## Tasks
- [ ] Document automation that relies on specific channel names
- [ ] Update Slack channel names
  - [ ] vsp-operations
  - [ ] vsp-operations-internal 
- [ ] Update documentation in Confluence (search and replace) 
- [ ] Update documentation in GitHub 
- [ ] Update Team of Team slides (PM to do)

## Acceptance Criteria 
- [ ] The Slack channel names for the Operations team have been updated to use "platform-"
- [ ] Documentation that references Slack channels for the Operations team has been updated

**Comment by jhouse-solvd** [comment]
See #36097. This will be addressed as part of that larger issue. 

Closing.
