### ISSUE TITLE
[FE] Release to 50% Users - Mobile Header V2 on 12/14

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33219]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need an optimized mobile experience so I can complete tier 1 benefit actions while on the mobile platform. 

## Related Documentation
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Release%20Plan%20Mobile%20Header.md)

## Description
- In support of our phased release plan for the new mobile header V2 we need to release to 50% of users on 12/7. 

## Tasks
- [ ] Release to 50% of Users
- [ ] Monitor environment to ensure stability
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] Mobile Header is now released to 50% of users

**Comment by brianalloyd** [comment]
@kelsonic we are ready to jump to 50% now.

**Comment by kelsonic** [comment]
Bumped to 50%
