### ISSUE TITLE
[FE] Release to 25% Users - Mobile Header V2 on 12/7

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33218]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need an optimized mobile experience so I can complete tier 1 benefit actions while on the mobile platform. 

## Related Documentation
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Release%20Plan%20Mobile%20Header.md)

## Description
- In support of our phased release plan for the new mobile header V2 we need to release to 25% of users on 11/30. 

## Tasks
- [ ] Release to 25% of Users
- [ ] Monitor environment to ensure stability
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] Mobile Header is now released to 25% of users

**Comment by brianalloyd** [comment]
@kelsonic we're going to hold on this until we can get GA tracking to make a data informed decision on moving this to 25% of users.  I've reset the DTG to 12/7 for jump, and also looped you into the analytics ticket for needed FE implementation before we can get GA tracking on board.

**Comment by brianalloyd** [comment]
@kelsonic we're good to jump this to 25% of users tomorrow.  Let me know if you have any questions, thanks.

**Comment by kelsonic** [comment]
Ready to bump to 25%?

**Comment by kelsonic** [comment]
Now set to 25% of auth users
