### ISSUE TITLE
Midpoint Review [Public Websites, Outreach & Events Enhancement MVP]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33223]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [X]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [X]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Schedule meeting with Collaboration Cycle reviewers and VFS team attendees listed in the ticket. 
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [x] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [X] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

Content Ticket #32518 

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
- [ ] [Product Initiative Briefing MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Initiative%20Briefing.md)
 
- [ ] [Finalized design prototype or mockup](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/design)
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/research) 

 
- [ ] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/outreach-and-events/research) 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

### Required* 
\*Only required for synchronous meetings.
- Product Manager: Brian Lloyd
- OCTO-DE Product lead: David Conlon
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Kelson Adams (FE Engineer)
- Cassandra Allen (Designer)
- Cindy Merrill (Researcher)

### VFS Attendees

- Content and IA: 
- Accessibility: 

## Scheduling
Would you like this review to be asynchronous? Yes

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [X] Yes
- [ ] No

**[12/7]** **[11AM]**

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
The async Midpoint review has been scheduled for 12/7, meaning you will receive feedback by EOD. No meeting will be held.

**Comment by brianalloyd** [comment]
@shiragoodman after looking at our initiative timing in planning we're looking to push this Mid-point review out a week to the right, is that possible?

**Comment by shiragoodman** [comment]
Sure @brianalloyd - would 12/14 work ok?

**Comment by brianalloyd** [comment]
Works perfectly, thanks @shiragoodman for the assist and support.

**Comment by allison0034** [comment]
Hi @brianalloyd I see several comps on the link, should we be reviewing the UXpin prototype?

**Comment by allison0034** [comment]
@brianalloyd do you have a desktop version?

**Comment by brianalloyd** [comment]
@allison0034 sorry for the delayed response.  Yes, please review the prototype its the latest version we have in regards to design.  A desktop version exists [here](https://www.sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1) and are labeled as desktop in the sketch thumbnails. Let me know if any additional questions exist, happy to help and support.

**Comment by jimuhh** [comment]
**Hi everyone.** 
I appreciate the attention @cindymerrill and the rest of your team have given to IA concerns in the research plan and would love to see the findings when you have them. 
No IA feedback from me at this time. Thanks!

**Comment by cindymerrill** [comment]
@callen2563 What is the "Check other times" button that @joshkimux is referring to? Is it the "Show more times" button in the mobile prototype? I think "Show" is a more accurate verb than "Check".

**Comment by brianalloyd** [comment]
@jimuhh happy to share those with you when complete.

**Comment by callen2563** [comment]
@cindymerrill The "check other times" copy came from content so I'm not sure we should change that to "show" but I can run it by them to see.

**Comment by joshkimux** [comment]
@callen2563 , I'd trust content's suggestions! The feedback was meant to be more of a question on whether or not it is a link or a button in terms of behavior (e.g. is it navigating to a new page? or is it conducting an action on the same page like expanding the amount of results?)

**Comment by callen2563** [comment]
@joshkimux Thank you so much for the quick turn around on your recommendations! 

Couple things:

"Disabled" text must still meet contrast requirements ( I will fix this issue )

Revisiting the placement of the desktop actions "add to calendar... share on fb..." 
( for MVP we are only adding the two new features: reoccurring events and filter by date so we aren't changing things like this that are in production but will take note for future iterations )

Designing error states; it could help with figuring out the right language ahead of time ( this one can be done do you have any special requirements for errors states? )

Placing the date before the day of the week within the "find other times..." accordion. Having a repeating list starting with "Tues" every time could risk users seeing this as one full chunk/block as opposed to uniquely separate dates.
( The date format is already in production and won't be changed for MVP but will take note for future iterations )

@brianalloyd

**Comment by callen2563** [comment]
I have updated the [Sketch file](https://sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1) with suggested edits from the team.

**Comment by brianalloyd** [comment]
Updates have been applied, going to close ticket in support.
