### ISSUE TITLE
[Design] Profile - Personal Information Revision - refine protype based on content/design clarifications

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33225]
## Background 
There are a couple of areas that could impact the prototype used for Personal Information Revision research:

1) Whether the text field and label below radio buttons should be visible before the user selects the "other" option
2) Language to be used near each field to explaining why we ask for that information. 

## Tasks
- [x] Talk with Kevin about the intent behind the original designs - was it intentional that the text fields and labels under a list of radio buttons was shown by default, or was he simply trying to capture the before/after state as quickly as possible (see screen shot below)
![image](https://user-images.githubusercontent.com/73354907/143118538-62bbfae1-0b9c-4086-8896-c85216a6d6df.png)
- [x] Update prototype based on the answer to the above question
- [x] Update prototype to reflect the language decided upon in #33209 

## Acceptance criteria
- [ ] The prototype will reflect the true intended states of the questions that have "other" options
- [ ] The prototype will display the language that addresses why we ask for the information in each section.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske I am so sorry; it's been a nutty day.  Is this ticket complete?  I am trying to catch up.  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO yes, this is complete!

**Comment by MarciMcGuireGCIO** [comment]
Great!!! Thank you!!
