### ISSUE TITLE
[FE] Release to 100% Users - Mobile Header V2 on 12/21

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33220]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need an optimized mobile experience so I can complete tier 1 benefit actions while on the mobile platform. 

## Related Documentation
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Release%20Plan%20Mobile%20Header.md)

## Description
- In support of our phased release plan for the new mobile header V2 we need to release to 100% of users on 12/14. 

## Tasks
- [ ] Release to 100% of Users
- [ ] Monitor environment to ensure stability
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] Mobile Header is now released to 100% of users
