### ISSUE TITLE
[PM] Profile: Login.gov testing 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33229]
## Overview
As a member of the Profile team, I want to ensure that I test logging in with login.gov credentials so that I can verify that it works as intended.

## Tasks 
- [ ] Write test cases for each login.gov level of access
- [ ] Provide info on accounts to use - see this thread https://dsva.slack.com/archives/CSFV4QTKN/p1637702433249300 and this thread https://dsva.slack.com/archives/CE4304QPK/p1637702651186000?thread_ts=1637701760.184400&cid=CE4304QPK
- [ ] Document in GitHub
- [ ] Ask Liz to check the designs on Staging

## Acceptance criteria
- [ ] Test cases specific to login.gov credentials are created and documented

**Comment by MarciMcGuireGCIO** [comment]
Samara and I have both tested and confirmed that everything appears to be working on Staging.
