### ISSUE TITLE
Bug: The redirect URL is not being remembered in Session Storage

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#33228]
## Issue Description
There is a bug in the `redirect` method for the `authentication/utilities.js`.  Currently, the `returnUrl` is only looking at the origin instead of the whole URL (aka dev.va.gov/some-place always resolves to dev.va.gov/).

---
## Tasks
- [ ] Fix the return `returnUrl` to ensure that the entire location is returned instead of just the origin

## Acceptance Criteria
- [ ] On a different page (`/education/how-to-apply`), when I authenticate I am navigated back to that same page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
