### ISSUE TITLE
Display wait time data on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33233]
## Issue Description
In #32569 we audited wait time data for 5 VAMCs from different VISNs as it is displayed on the Facility Locator detail pages and in VAMC health service accordions

**Summary of findings**
- Data "as of date" is the same for FL and VAMC pages
- Mental health data is missing from the VAMC pages of all 5 systems audited
- New patient wait time on VAMC pages differs from wait time on FL detail pages for all specialties except Primary Care
- For all specialties except Primary care, the wait time for new patients and the wait time for existing patients is identical on FL detail pages
- Most locations have more specialties with wait times on FL detail page than their VAMC pages
- Satisfaction scores match between the two pages except for "as of date"

<details>
<summary> Related screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/140577060-12d1fdaf-7239-44a3-94a7-3e489f14074d.png)

![image](https://user-images.githubusercontent.com/55411834/140576379-69c203a0-ac73-438d-8317-26a8935a1a8a.png)

![image](https://user-images.githubusercontent.com/55411834/143135265-264cc2ae-72c9-4388-b44f-0d179744af3c.png)

</details>
 
**Because the VAMC page roll-out will be complete in the next two weeks, we will focus our efforts on the information displayed on the VAMC pages.** 

---
## Tasks
- [x] Confirm endpoint for wait time is correct 
- [ ] Ensure that data displayed within the VAMC service accordion for a given specialty at a given location matches the data available in the API for that service and location related to the following
      - Existing patient wait time
      - New patient wait time
      - As of date
 
## Acceptance Criteria
- [x] For a given facility, each service included on the VAMC page with corresponding available new or existing patient wait time data will display that data within the service accordion. 
- [x] Data values displayed on VAMC pages match API data

**Comment by mmiddaugh** [comment]
@gescobardev I confirmed the following services have wait time data

- Primary care
- Mental health
- Women's health
- Audiology
- Cardiology
- Dermatology
- Gastroenterology
- Gynecology
- Ophthalmology
- Optometry
- Orthopedics
- Urology Clinic

**Comment by gescobardev** [comment]
@mmiddaugh
> I confirmed the following services have wait time data

Am I correct in saying that these services have wait time data and facilities can have all or some of these services?

I went over the list and only found wait time issues with mental health and womens health.

**Mental Health issue:**

The reason why we don't see the wait time widget for mental health is because the service name is spelled differently in 2 areas.

The data we get from cms to render the accordions contains a field - `fieldHealthServiceApiId` that gets used in the widget. For mental health it equals to `fieldHealthServiceApiId: "mentalHealth"` (see screenshot below) 

<details>
<summary>cms/drupal data</summary>

![Screen Shot 2021-12-01 at 7 39 32 PM](https://user-images.githubusercontent.com/84030819/144360825-eb2b608e-4ad8-42bd-a5a8-2c62a54160e1.png)


</details>

The data we get from LH that contains the wait times has a field - `service` that is used with the above field -`fieldHealthServiceApiId` , to identify which service we are looking at. For mental health it equals `service : "MentalHealthCare"` (see screenshot below) 

<details>
<summary>LH</summary>

![Screen Shot 2021-12-01 at 10 26 42 PM](https://user-images.githubusercontent.com/84030819/144360763-39369ad7-d80c-45eb-917d-6168f3d10caf.png)

</details>

Because these 2 strings don't equal each other, no wait time widget is shown for mental health. (Please ignore the capitalization, thats not important bc we work around that). 

We have 2 options to resolve this:

1. I can remove the "Care" at the end of "MentalHealthCare" to make the wait time widget show up. Simple fix but not ideal bc it's just putting a bandaid on it.
2. Data needs to be updated somewhere to be consistent. 

**Womens Health Issue:** 

Before I get too far with this one, you mentioned we have wait times for Womens Health. 
Does that mean we should be seeing the wait time widget within the Women's _Veteran_ Health accordion?
I just want to confirm that that is true.

<img width="749" alt="Screen Shot 2021-12-02 at 9 06 57 AM" src="https://user-images.githubusercontent.com/84030819/144437574-7710740b-0775-4941-a768-37f545497d1f.png">

**Comment by gescobardev** [comment]
@mmiddaugh 
See thread for more info - https://dsva.slack.com/archives/C0FQSS30V/p1638452921407200

Per Dave, `WomensHealth` and `Womens Veteran Care` are not the same thing but they can be if that is what is decided. For now, `WomensHealth` service is not a wait time issue.

Dave also mentioned that we can possibly go with option 2 and update `fieldHealthServiceApiId` on the drupal side to equal `mentalHealthCare`.

If thats the case, then I don't need to make any changes to the wait time widget and it should just work as expected.
