### ISSUE TITLE
Synthesize feedback from Platform satisfaction survey

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#33230]
## Issue Description
Synthesize results from the Platform satisfaction survey and prepare the readout so we can share the findings with stakeholders to inform quarterly planning.

---
## Tasks
- [x] Calculate satisfaction score
- [x] Copy survey feedback into mural board
- [x] Group feedback into categories/themes
- [x] Define feedback themes and select representative quotes
- [x] Complete Q4 2021 customer insights deck
- [x] Present deck in end of sprint demo and post in platform-team channel

## Acceptance Criteria
- Platform teams and OCTODE are using survey findings to define/refine initiatives and OKRs.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
