### ISSUE TITLE
Implement CSAT on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33236]
## Issue Description
We need to implement the Teamsite version of Foresee/CSAT on VAMC pages so that we can compare the satisfaction scores between new/old pages

---
## Tasks
- [ ] Implement CSAT snippet only on VAMC pages on VA.gov 
- [ ] create JS variable needs to be created and set its value set to “mcenter”.  
- [ ] Add  standard <script> command to the ForeSee software
 
```
<script type="text/javascript">
   var vaSurvey = 'mcenter';
</script>
<script type="text/javascript" src="/va_files/foresee/foresee-trigger.js"></script>
```
      
-[ ] use the `header.html` component on content-build to limit pages (per Jason)

## Acceptance Criteria
- [ ] Teamsite CSAT implementation is applied to VAMC pages on VA.gov _**and nowhere else**_

**Comment by mmiddaugh** [comment]
Unanswered questions (need more info before estimating)

- is foresee already implemented on these pages?
- should script tag be placed in header.html?
- how is variable used?

**Comment by gescobardev** [comment]
https://developer.foresee.com/docs/testing-web-sdk
