### ISSUE TITLE
Swap out videos in vaccine CLP-HOLD FOR WEEK OF 12/6

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33247]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John Scott McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x]  Review and publish (Randi)
- [x]  Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [x] New ticket created

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Have questions before you get your COVID-19 vaccine?: http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Published and created new ticket. Will close once live on site.

**Comment by RLHecht** [comment]
Work complete. Closing ticket. FYSA @DanielleThierryUSDSVA
