### ISSUE TITLE
SD - Explore Medallia Survey to add survey questions to R&S articles and confirm roll out strategy

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33248]
## Issue Description
_Explore Medallia Survey options to add survey questions to R&S articles and explore ways to do AB testing with selected articles_
[instructions for Medallia](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ffa39f3ba55f3f9e35289c1bad7490f3ada0b6f4/teams/vsp/teams/contact-center/medallia-implementation-how-to.md) and a [list of approved questions](https://docs.google.com/spreadsheets/d/1gkjignCqZV8qTYentLHvh9sZLy_Cnjj1eGodT6-pPzY/edit#gid=782170026).

## The questions we used for the Search Results page were:

- Did you find what you were looking for today?
- What were you unable to find during your visit today?
- What is your overall satisfaction with this site?

---
## Tasks
- [ ] _Understand what pre-approved questions are in Medallia Survey for Va.gov_
- [ ] _Understand how to add and customize Medallia Survey questions to R&S_
- [ ] _Confirm roll out strategy_
- [ ] _Select the articles to add Medallia survey questions and select the comparing articles_

## Acceptance Criteria
- [ ] _Finalize Approved survey questions_
- [ ] _Successfully add Medallia survey questions to selected articles_
- [ ] _Set up comparison tracking on GA dashboard_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Decided not to pursue Medallia Survey. Closing ticket
