### ISSUE TITLE
SD - Create an experimental Design System Request for Typeahead 2.0

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33251]
## Issue Description
_Create an experimental Design System Request for typeahead 2.0_

---
## Tasks
- [ ] _Create an Experimental Design System Request for typeahead 2.0 from this [template_](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=caw310&labels=vsp-design-system-team&template=experimental_design_request.md&title=)

Reference [33106](https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/33106)

## Acceptance Criteria
- [ ] _Sucessfully create and send Experimental Design system Request for typeahead 2.0 to the Design Council_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Blocked by analytics issue

**Comment by LindaLi123** [comment]
Blocked by Analytics and Migration IT for missing data

**Comment by LindaLi123** [comment]
Pulling into Sprint 63

**Comment by nicole-leonard** [comment]
This is blocked by analytics as of 12/29/2021

**Comment by nicole-leonard** [comment]
@bsmartin-ep Can you please provide an update on this?

**Comment by bsmartin-ep** [comment]
Hi @nicole-leonard - what is the analytics blocker with this one? 

And should I be assigned to this issue?

**Comment by nicole-leonard** [comment]
@mgleo can you please place the blocker comments here for Brian?

**Comment by mgleo** [comment]
@bsmartin-ep @nicole-leonard 
Found the ticket for the bug: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34014

The [Typeahead Dashboard](https://va-gov.domo.com/page/439942537) still looks like it stops on August.

I see these links on the bug ticket but it says I either don't have permission or they don't exist:
- [Monthly](https://va-gov.domo.com/datasources/382bb814-3590-4ee6-9859-a914c86e2620/details/settings) dataset
- [Daily](https://va-gov.domo.com/datasources/7766ccbf-a30a-4ff7-90f6-906ec9773059/details/settings) dataset
