### ISSUE TITLE
GA4:  Get feedback from VA teams, plan and prioritize events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#33250]
## Issue Description

---
## Tasks
- [x] Get feedback from VA platform teams on naming conventions/terminology 
- [ ] Outline plan and prioritization for events to get rolled out in phases (form actions, control actions, etc)
- [ ] Decide which parameters will be visualized in GA (vs Domo)

**Comment by michelle-dooley** [comment]
Working session planned for 1/25

**Comment by michelle-dooley** [comment]
Closing this ticket.  This work will be completed as part of #30711
