### ISSUE TITLE
[PM] My VA: Functionality testing using login.gov credentials

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33261]
## Background
The Identity team will be launching Login.gov as a CSP in the coming weeks (Live 12/8/2021).  Here is the official guidance from the Identity Team as it relates to other teams:

- **Login.gov Back-end Impacts:**
     - We don't anticipate the addition of Login.gov as a CSP to require any major changes on the part of other teams.  However, from a back-end perspective, areas utilizing uuid may be impacted as the past assumption was that this was equivalent to idme_uuid. Now, user_uuid may be idme_uuid or logingov_uuid .
     - Given this, it would be good for teams that work with these parameters to ensure queries for user's account data from Accounts now search for either for a matching idme_uuid or logingov_uuid
     - Best practice moving forward is for teams to use "@current_user.uuid" in place of account_id

- **Login.gov Front-end Impacts:** 
     - Any content or features which is CSP-specific should be re-evaluated. (edited)
     - Before launch, It is advisable that all teams perform basic functionality testing of any potentially impacted features in staging before we launch (currently anticipating 12/8).
     - After launch, all teams should plan to test any new features with login.gov.

Related Slack threads:
- https://dsva.slack.com/archives/C909ZG2BB/p1637183645166300
- https://dsva.slack.com/archives/C909ZG2BB/p1637186225180400
- https://dsva.slack.com/archives/CE4304QPK/p1637701647184100

**Credentials update**
Per Identity team, the new login credentials are available on the [Staging user document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

---
## Tasks
- [x] Perform functional testing of logging into My VA, using login.gov credentials
- [x] Validate that the My VA page loads as expected
- [x] Validate that the My VA page includes the expected sections (per credential access in staging)

## Acceptance Criteria
- [x] Using login.gov to log into My VA does not impact the page loading, content or functionality, creating a seamless experience for the user.
---

**Comment by hdjustice** [comment]
Validated My VA loading and content with each of the 10 IDs provided by the Identity team in the Staging environment.  The My VA page loads as expected, and content is consistent with logged in users (comparison with ID.me and Login.gov)
