### ISSUE TITLE
SD - Create visual of component/pattern with callouts for Typeahead 2.0

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33260]
## Issue Description
_Create visual of component/pattern with callouts for typeahead 2.0_

---
## Tasks
- [ ] _Create visual of component/pattern with callouts from [Anatomy callouts Sketch library template](https://www.sketch.com/s/aaa5c25f-6991-4aac-a6ed-d378bdff7727) for typeahead 2.0_

Reference [33106](https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/33106)

## Acceptance Criteria
- [ ] _Sucessfully create  visual of component/pattern with callouts for typeahead 2.0_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
![typeahead-anatomy.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/1f49e121-4e96-4c1f-b3eb-206e62707deb)

1. **Search input field**: Where users enter their search query.
2. **Typeahead suggestions**: Sorted by descending character count. Suggestions in bold. If suggestions appear after the user’s text, the suggestion should appear in bold. If user’s text appears anywhere within the suggestions, the user’s text should appear in bold. 
3. **Selected typeahead suggestion**: Highlighted on hover, clicking/tapping on suggestion automatically searches for the suggestion.
