### ISSUE TITLE
[VAMC] Resolve LBGT pages that should be updated to LGBTQ+ pages and work with CMS to resolve URL change [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33263]
## Story
As a Veteran I need to see the correct title and URL for the LGBTQ+ Veteran care page, so I know I have the latest and up to date information.

## Tasks
- [x] Work with CMS to identify list of pages that still have LGBT in title and URL
- [x] Update titles to these pages and list pages that will have to have URLs updated
- [x] Provide list of original URLs (https://www.va.gov/[system name]/health-services/   (lgbt-veteran-care  | redirect to new lgbtq-veteran-care  urls.

## Acceptance Criteria
* All page titles are updated
* URLs are listed and provides to they can be submitted to IA for redirects

**Comment by ltrombley** [comment]
Task #33263 - Resolve LBGT pages that should be updated to LGBTQ+ pages and work with CMS to resolve URL change [BA]  - is Complete and moved to Validate.
