### ISSUE TITLE
[PM, Design] My VA - Payment Info: Discuss approach for adding medical copay information

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33267]
## Background
Now that Veterans are able to log into VA.gov and review and pay their medical copays, we need to discuss an approach for pulling that information into My VA. (Slack announcement below)

> [Denise Coveyduc](https://app.slack.com/team/U01C9JD9NAY)  [3:34 PM](https://dsva.slack.com/archives/CPE4AJ6Q0/p1642106065048100)
:mega: Veterans are now able to log in and review their medical copay statements on [va.gov](http://va.gov/) :tada: 
This new experience makes it simple for Veterans to understand and either pay or request financial help for copay charges they receive from their VA health care facilities.
Once an authenticated Veteran navigates to https://www.va.gov/health-care/pay-copay-bill/, they can view a list of individual cards with each representing a VA health care facility they've both visited and received a copay statement from. Each card shows the most recent statement's balance and due date. Additionally, Veterans can click on the link 'Check details and resolve this bill' to learn how to either pay their full balance or request help as well as download their statements from the last 6 months.

### Below are some questions to consider:
  -  Are we adding this to Benefit payments & debts, or health care?
  -  Does this need separate user research?
  -  Is this more of an enhancement or small, separate project? 
  -  [Link to medical copay content page](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)
  - [Link to detail page showing list of copays and detailed information](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)

## Tasks
- [ ] Meet to discuss approach for adding medical copay information
- [ ] Create tickets for discovery and design efforts

## Acceptance Criteria
- A general approach decision has been agreed upon and tickets have been created to start the work.

**Comment by hdjustice** [comment]
Feb 14, 2022 | [Copays - Discuss approach to include on My VA]
Attendees: Angela, Liz, Samara, Heather

Notes:

- Goal of this meeting is to determine the effort
     - Not a full project
     - Full collab cycle may not but needed
     - Looking at a 1 month delivery - smaller effort
     - Heather will talk with Shira and submit CC kickoff 
     - May have a reduced CC engagement
- User research was split, but both sections were acceptable
- A/B test - health care vs BP&D? 
     - May reduce user/usability testing efforts
     - No formal ability to do AB testing, but could try it out
          - 1 week deploy to one section
          - Another week deploy to the other section
          - Discuss with Taylor on feasibility
     - Cannot test concurrently - no capability
- UAT - Screenshot to share and gain feedback
     - Question added at the end of UAT session
- Will need to consider where and how to display
     - Info currently resides under Health care
     - Does not need to live under Health care on My VA
     - Create some mockups on what this might look like - 

Action items
- [ ] Liz - Add as part of UAT questions/Research plan/Conversation guide
- [ ] Angela - Mock-ups for possible designs
- [ ] Heather - Complete Collab Cycle kickoff and talk with Shira
- [ ] Heather - Close out discussion ticket & additional tickets will be created for next sprint
     - Discovery
     - Design iterations
