### ISSUE TITLE
User testing of POC designs

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#33279]
## Issue Description
We need to conduct user research on our three POC wireframe proposals

---
## Tasks
- [ ] Two rounds of user testing on each of the three POC wireframes
- [ ] Synthesize research findings and implement then into iterations of POC designs
- [ ] Use research to decide on a single design moving forward

## Acceptance Criteria
- [ ] _Presented test findings in a mid-sprint review_
- [ ] _Implemented findings into design iterations_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
