### ISSUE TITLE
vets-api-pghero service account

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#33289]
## Description
A new [vets-api-pghero repo](https://github.com/department-of-veterans-affairs/vets-api-pghero) was created to extract pghero out of vets-api to run on Kubernetes. A service account is needed for this repo to be able to utilize secrets stored within AWS parameter store.  

## Background/context 
Additional Info in [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1638204543088400)
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32597

## Technical notes
[Pull request to run pghero locally on k8s](https://github.com/department-of-veterans-affairs/vets-api-pghero/pull/2)

- [x] ~~Additionally: Waiting on write access for `department-of-veterans-affairs/backend-review-group` for the `vets-api-pghero` repo. Thread started [here](https://dsva.slack.com/archives/CU1E4CX9U/p1638204886208500)~~

---
## Tasks
- [ ] Create vets-api-pghero service account

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
@LindseySaari, was this resolved?

**Comment by LindseySaari** [comment]
@jbritt1 Yes, closing it now! Thanks
