### ISSUE TITLE
[BE] On-site Notifications: Determine next steps for backend build

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33303]
## Background
Now that the [On-site Notification MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) has been determined as an Outstanding Debt notification, we need to determine the next steps on how we will receive the required data from VA Notify and communicating that information to the Frontend

## Tasks
- [ ] Determine how we will receive the required data from VA Notify.
- [ ] Determine how this information will be communicated by the Backend to the Frontend
- [ ] Work with PM [Heather] on additional tickets, if needed

## Acceptance Criteria
- [ ]  Determine and document what steps are required for the Backend build for the On-site Notifications MVP.

**Comment by hdjustice** [comment]
The team met to discuss the functionality to dismiss the notification, as well as meeting with VA Notify to discuss needs from both teams, and timelines.  At this time, the VA Notify team would not be able to be engaged on this effort until Mid-Feb to March.  Lihan has a good idea on what we need from VA Notify.  Until we can get their engagement, Lihan will work on what he can.  Closing this ticket.
