### ISSUE TITLE
[BE] Emergency Contact - Read Only

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33302]
## Description
BE ticket to allow the data to be sent to the front end (if required)

CHIP will need to show the Emergency Contact in the current payload. Emergency Contact data is already in the payload CHIP receives from Vista.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- Slack thread [https://dsva.slack.com/archives/C02G6AB3ZRS/p1633714946221600?thread_ts=1633703022.208100&cid=C02G6AB3ZRS(url)

## Tasks
- [x] Research regarding how to pull the data. 
- [x] Data will need to be stored in LoROTA  
- [x] Collaborate with appropriate teams (CHIP, etc.) 
- [x] Sync with UX and FE 
- [x] Implement `check_in_experience_emergency_contact_enabled` feature toggle
- [x] Vets API code implemented 

## Acceptance Criteria
- [x] Swagger documentation 
- [x] Feature Flag implemented 
- [x] Sequence diagrams created 
- [x] Staging implementation 
- [ ] Release ticket created 
- [ ] Product sign-off

**Comment by jparker0425** [comment]
Corey to sync with CHIP about getting Emergency Contact data added to LoROTA.

**Comment by dillo** [comment]
Associated CHIP issue: https://github.com/department-of-veterans-affairs/chip/issues/277

**Comment by dillo** [comment]
Sample Emergency Contact data pulled from Vista:
```
"nextOfKin1": {
            "name": "VETERAN,BROTHER",
            "relationship": "",
            "phone": "",
            "workPhone": "",
            "address": {
                "street1": "",
                "street2": "",
                "street3": "",
                "city": "",
                "county": null,
                "state": "",
                "zip": "",
                "zip4": null,
                "country": null
            }
        },
        "nextOfKin2": {
            "name": "",
            "relationship": "",
            "phone": "",
            "workPhone": "",
            "address": {
                "street1": "",
                "street2": "",
                "street3": "",
                "city": "",
                "county": null,
                "state": "",
                "zip": "",
                "zip4": null,
                "country": null
            }
        },
        "emergencyContact": {
            "name": "",
            "relationship": null,
            "phone": "",
            "workPhone": "",
            "address": {
                "street1": "",
                "street2": "",
                "street3": "",
                "city": "",
                "county": null,
                "state": "",
                "zip": "",
                "zip4": "",
                "country": ""
            }
        },
```
