### ISSUE TITLE
[Design] On-site Notifications: Follow-up with Design Intent tickets

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33301]
## Background
Now that the [On-site Notification MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) has been determined, we need to follow up on the outstanding Design Intent changes and inform the Platform support team.

- [Project outline from discovery](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/action-items-discovery#readme) for reference. 
- Discovery epic: #25886 

## Tasks
- [x] Determine if any outstanding Design Intent suggested changes are still needed
- [ ] Complete the outstanding Design Intent suggested changes that are needed
- [x] Follow-up with Platform support - Design Intent on our scope pivot and current MVP
- [x] Confirm with Platform support - Design Intent of any outstanding Design Intent suggested changes that are no longer needed

## Acceptance Criteria
- [ ]  Follow up with Design Intent on MVP pivot and outstanding Design Intent changes from initial review.

**Comment by tressaellen** [comment]
Everything is done here - we're just waiting for VFS to close the design intent ticket. so I think we're good to close this.
