### ISSUE TITLE
[PM, Design, FE, BE] On-site Notifications: Work with VA Notify to define needs and delivery timeline for MVP

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33300]
## Background
The team needs to meet with our VA Notify partners to discuss our high-level requirements for on-site notifications MVP

## Tasks
- [x] (PM, Design, Devs) Continue to meet with VA Notify to discuss requirements for MVP

## Acceptance Criteria
- [x] High level [MVP requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) are documented in GH
- [x] Continue to meet with VA Notify in next sprint with BE (Lihan) present to discuss technical details and clarify questions

**Comment by hdjustice** [comment]
Created new ticket [[34282](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34282)] for next sprint for continued discussions with VA Notify.  Our meeting this sprint went well, however there are some backend technical details that need to be confirmed and thought through with Lihan, after the holidays.  The next meeting is January 4th (sprint 64)
