### ISSUE TITLE
Collaboration Cycle Checklist for 10-10EZ American Indian question  

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#33311]
## Instructions

<details>

Copy/Paste the below into a new issue to create a checklist of required touchpoints for your project after receiving feedback from your Collab Cycle Kickoff.   The checklist and associated teams are current as of **Nov 3, 2021** based on [VSP's Collab Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
- [Platform website Collab Cycle FAQs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/FAQs.1864073263.html)
- [Collab Cycle Change History](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)
  
### How to Configure This Checklist
Tag with vsa and team name

</details>

---

# Collab Cycle Checklist for 10-10EZ American Indian question

## List your team, project contributors, and reviewers
<details>

_Record key players so you can quickly copy/paste into requests and your product documentation as your project progresses_

### Product Team
- OCTO-DE Product Lead: Lauren Alexanderson
- Product Manager: Heather Justice/Mark Fallows
- FE Engineer: Lisa Zapson
- BE Engineer: Lihan Li
- Designer: Dene' Gabaldon
- Researcher: Dene' Gabaldon
- Slack channel: #1010-health-apps
- GitHub tag: American Indian

### VFS participants (when applicable):
- Design Lead: Ryan Thurwell
- Design
- Accessibility:
- Analytics:
- IA:
- Content:
- QA:
- Privacy & Security:

</details>

## List project artifacts for requests

<details>

_Link applicable artifacts here so you can quickly copy/paste into requests as your project progresses.  Note that all artifacts may not be needed, depending on nature of the work_
- [Project epic #28973](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28973)
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/American%20Indian%20question) 
- Authenticated test-user logins, when applicable. **_Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository_**
- Product URL for the [American Indian question](https://staging.va.gov/health-care/apply/application/veteran-information/american-indian)
- [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/American%20Indian%20question/product/american-indian-question%20Use%20Cases.md) and [Ticket #33516](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/33516)
- [Finalized design - Sketch](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgWK7GD)
- Content brief (see Finalized Design)
- Regression test plans
- TestRail [test cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
- TestRail [test plans](https://dsvavsp.testrail.io/index.php?/plans/view/2751)
- Accessibility testing [Ticket #33524](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33524)
- Technical diagrams (architecture diagram, sequence diagram)
- Release plan [Ticket #33514](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33514)
- Product guide for contact center [Ticket #33525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33525)

</details>

## Pre-Launch touchpoints linked to VSP reference info + practice areas involved at each step

<details>

- [x] Collaboration Cycle Kickoff | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D) | [#issuenum]

- [x]  Design Intent  | [#34581] | 
  - Content 
  - Design
  - OCTO
  - IA 

- [N/A] Research Plan Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) |  [#issuenum]
  - OCTO

- [x] Analytics Request | [Overview](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html) | [Analytics playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - OCTO

- [N/A] Midpoint Review 
  - Accessibility
  - Content
  - Design
  - OCTO
  - IA
  - QA

- [N/A] Staging Review 
  - Content
  - Design
  - OCTO
  - IA
  - QA 

- [x] Privacy and Security Review |  [#523](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/523)

- [ ] Contact Center Review | [#33525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33525)
    - Contact Center
 
</details>

## Post-Launch Tasks

<details>

- [ ]  Update [Launch Tracker on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/vsa_launch_tracker.md)

- [ ]  Post @here announcement in your Slack channel after launch

- [ ] Post-Launch Check-in | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html) |  [#issuenum]
  - Product

</details>

## Other Resources

<details>

- [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md)

</details>

**Comment by hdjustice** [comment]
Launched 25% on 9/26
