### ISSUE TITLE
Compare both versions of health care tool pages for content differences

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33313]
## Issue Description
Currently our health care tool pages are in react apps except for the H1 and intro text. This was done as a time-saving measure when we first reworked them for Cerner. It's possible that not all of this content needs to be in the react widget and we can bring some of it back into Drupal. 

To do this, we need to ask the PW team for the github pages to compare the 2 versions of each tool landing page to see what content is the same vs. different. If there is a lot of the same content, we should be able to move that back into Drupal and set up the react widget to only pull the content that's different for each.

If we move content into Drupal, we need to coordinate publishing the update pages with when the new react widgets are deployed.

The pages to review are:
- [Refill and track prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)
- [VA secure messaging]()https://www.va.gov/health-care/secure-messaging/
- [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments/)
- [View lab and test results](https://www.va.gov/health-care/view-test-and-lab-results/)

## Tasks
- [ ] Ask Kelson for GH versions of both pages to review (Selina)
- [ ] Do a comparison and note what is different in the 2 pages (Selina)
- [ ] Update Drupal page with content that can be added (Selina)
- [ ] Work with Kelson to update react widget with only content that is different (Selina)
- [ ] Review updated pages (Randi)
- [ ] Publish pages (Randi)

## Acceptance Criteria
- [ ] Appropriate amount of content is in react widgets

**Comment by lunascoop** [comment]
Adding **Get your VA medical records online** to the list: http://preview-prod.vfs.va.gov/preview?nodeId=33

**Comment by lunascoop** [comment]
(Added authenticated/unauthenticated GH files to ticket description)
In comparing the auth/unauthenticated pages, here are my findings:

### [Get your VA medical records online](https://www.va.gov/health-care/get-medical-records/)
**The Veterans Health Information Exchange** content can be moved out of the react widget

The notification content would have to be added to the react widget


### [Refill and track VA prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)
None of the content can be removed out of the react widget. My VA health content is included in most questions.

The notification content would have to be added to the react widget

### [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments/)
I don’t think that the content can be moved out of the react widget at this time. 

The content is the same in auth/unauth for these questions:
* Can I schedule appointments through VA secure messaging?
* Will my personal health information be protected?

If we were to pull the two questions out of the react widget, we would have to add another widget for the My VA Health content in the **What if I have more questions?** section.

The reminder content would have to be added to the react widget

### [VA secure messaging](https://www.va.gov/health-care/secure-messaging/)

Content before **Will my personal health information be protected?** can be moved out of the react widget. But, we’d have to add another widget for these questions:
* Will my personal health information be protected?
* What if I have more questions?

### [View your VA lab and test results online](https://www.va.gov/health-care/view-test-and-lab-results/)
None of this content can be moved out of the react widget right now.

**Comment by RLHecht** [comment]
Changed the criteria in this ticket to reflect that this is only the comparison work. We determined the content needs to stay in the react widget but we are using a new ticket the next sprint to update the content pattern. This is ticket #34123

**Comment by RLHecht** [comment]
@wesrowe @jilladams This is an old ticket of ours but we are trying to review the GH files that are listed above, which are our health care tool landing pages. The links are no longer working. Would you be able to send us updated links for these files? We specifically need the medical records page now but will need access to the others for a future sprint. Thank you@ FYSA @aliyahblackmore

**Comment by wesrowe** [comment]
@RLHecht, are these the two links you're trying to track down? – 
medical records page:
auth - [https://github.com/department-of-veterans-affairs/vets-website/blob/268c942ea6be51[…]nefits/get-medical-records-page/components/AuthContent/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/268c942ea6be51%5B%E2%80%A6%5Dnefits/get-medical-records-page/components/AuthContent/index.js)
unauth - [https://github.com/department-of-veterans-affairs/vets-website/blob/1c7b6529cb568e[…]fits/get-medical-records-page/components/UnauthContent/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/1c7b6529cb568e%5B%E2%80%A6%5Dfits/get-medical-records-page/components/UnauthContent/index.js)

**Comment by RLHecht** [comment]
@wesrowe Yep, those are them. We need to see the authenticated content for the medical records page. We can see the unauthenticated on the live site so don't really need that second one actually.

**Comment by wesrowe** [comment]
@RLHecht, I actually don't quite understand _which_ text you want to see. If it's the text that's displayed to a logged-in user... Would it work to log in as a test user on staging to see the content? 

I.e., 

- here's the un-authenticated widget:  <img width="479" alt="image" src="https://user-images.githubusercontent.com/4054752/170592215-c789b7c2-41b8-472e-9b6c-23923f31d48b.png">
- Here's what it looks like for a non-Cerner logged in user: <img width="419" alt="image" src="https://user-images.githubusercontent.com/4054752/170592425-d6faeae1-491b-42b7-befb-76764bf5f7e2.png">
- Here's the Cerner user: 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/4054752/170592476-1bb085d5-bc66-45a0-b693-fe0badf67a42.png">

If any of this is useful, I documented the widget flows in a [mural board](https://app.mural.co/invitation/mural/vagov6717/1651166973924?sender=u907f83e01e35bb04de6f8139&key=1a1e030f-8c9f-4b94-9960-b0a45b04a511).

**Comment by RLHecht** [comment]
Thanks @wesrowe We can log in as test users. The majority of the content on these pages is in a react widget (not just the alert). We are going to have changes in a future sprint that we'll need PW to update for us since we can't do it in Drupal. We wanted to make sure that the authenticated version of this page doesn't have text different from the unauthenticated that we aren't aware of when making these edits.

**Comment by wesrowe** [comment]
@RLHecht, per slack thread, here's where we think the file is that you requested: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js

Allison made a pdf of the new locations of all 10 files fitting this pattern

**Comment by wesrowe** [comment]
@laurwill, sorry about that, that was careless of me. They're the same except for the specific action. I just updated the images above to be consistently records-focused.

**Comment by laurwill** [comment]
Hi @wesrowe  no problem at all! And thanks so much for updating, this is very helpful.
