### ISSUE TITLE
526 - Failed Submission - List of attached files / filenames printed onto PDF

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#33314]
## Issue Description
In attempting to address 526 errors, we determined that it was possible to preserve the form submissions that did not make it to EVSS. We could do this via PDF generation. Therefore we want to explore what that preserved claim (and PDF form) might look like.

We discussed the possibility of also preserving the supporting evidence files the user has uploaded. At this time, we do not have a way to retrieve those. However, we wanted to look into the possibility of at least preserving the names of the supporting evidence files and potentially printing those somewhere on the PDF form.

This ticket is to look into the feasibility of printing the filenames onto the 526 PDF (if a section exists for it).

---
## Tasks
- [ ] Determine a spot on the PDF form where we can print the supporting evidence file names
- [ ] Understand the technical feasibility to print the file names on the generated 526 PDF form

## Acceptance Criteria
- [ ] Spot on PDF form has been identified, feasibility has also been understood
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
This work will be dependent upon outcome of pdf generation done by Lighthouse/EVSS (and that Csaba started)

**Comment by michelpmcdonald** [comment]
A little background on the current state.

Currently, as it stands today with evss's 526 PDF generation, when evss generates the 526 PDF(Only for claims that they were able to successfully establish), vets-api has not uploaded any files, so at the time evss generates the PDF, they don't have any files associated with the claim.

The initial call vets-api makes to evss to establish a new 526 is not the same call vets-api makes to evss to upload attached files.

Vets-api only makes subsequent calls to the evss claim upload service if the initial 526 create claim call from vets-api to evss was successful and returns a new claim ID to vets-api.

To upload, vets-api sends the claim ID and the file to the evss upload endpoint.

At this point, evss seems willing to look into providing a stand alone 526 PDF endpoint, the idea being that we provide the 526 claim "form" data and evss returns a 526 PDF filled in with the form data we send them.

Two options here, i guess:
1. Have evss accept a list of files as part of the 526 form data we send to their possibly upcoming 526 generation endpoint and add the files to the PDF.  I think this is unlikely to fly with them.  They are looking into breaking out their existing 526 PDF generation code out of the 526 submission process and making that functionality avail in a stand alone endpoint that does nothing but generate a 526 PDF from data we send them.  I don't think they are going to have time to alter their 526 PDF generation code to deal with listing files...but we could ask..

2. Vets-api could look into adding an extra page onto the end of the PDF that evss gives us.  That would be research we could undertake ourselves.
