### ISSUE TITLE
Move and Improve Instance Cycle Alerting

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#33325]
## Description
We should move and improve our current instance cycling alert like the ones observed [here](https://dsva.slack.com/archives/C24RH0W11/p1638196663173600). In the event that caused [this postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021/2021-11-29-autoscale-group-asg-cycle.md#illustrations), we did not see this alert until almost a full hour into troubleshooting the issue.

## Background/context 
As part of our lift and shift to Datadog from Prometheus, this one should flow naturally with the rest of our efforts in this space.

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Instance cycle warning alert moved to Datadog
- [ ] Instance cycle warning alert improved upon so it does not take an hour to reach the Ops team
- [ ] PagerDuty integration for production related instance cycles would also likely be a good to have here

## Acceptance Criteria 
- [ ] Alert moved from Prometheus to Datadog
- [ ] More rapid feedback from said alert 
- [ ] Integrated with oncall configurations for production at the least

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@ph-One This may be interesting to tackle as part of #47025

Or, @npeterson54 as part of #46778

Let me know your thoughts?
