### ISSUE TITLE
Sync 'Available' page for COE eligibility app with designs

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#33332]
## Background
Now that we are farther along on the Certificate of Eligibility app we need to make sure that all the required states for eligibility match what is in design. It was noticed that we do not have a state for `available` and we need to add it per the [mockup](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139512694/simulate/sitemap)

## Tasks
- [ ] Add state for `available` in the COE app
- [ ] Create a PR for review

## Acceptance criteria
- [ ] A page for the `available` state has been created on COE
- [ ] A PR has been created for review
