### ISSUE TITLE
Update Vets Json Schema with new 526 Special Issue RRD

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#33334]
## Issue Description
Vets-json-schema needs to be updated so 526 submissions with the new RRD special issue are considered valid json for the existing 526 json schema 

---
## Tasks
- [x] Update vets-json-schema 526 to include new RRD Special Issue(https://github.com/department-of-veterans-affairs/vets-json-schema/pull/664)

## Acceptance Criteria
- [x] 526 form submission with a special issue of RRD will no longer fail json schema validation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
Code complete, waiting for PR approval

**Comment by michelpmcdonald** [comment]
Merged into vets-json-schema, vets-website and vets-api vets-json-schema updated to latest version...all done
