### ISSUE TITLE
Add notification content to relevant pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33349]
## Issue Description
The authenticated experience team has launched text and email notifications that we can add to certain health care and appeals pages. 

Background info and a list of possible pages can be found in ticket #29582.

We need to create Q&A content for each page with appropriate links. We can reach out to Liz Lantz if we need more info or guidance. 

Update: The pages we are currently adding this Q&A to are all ones that have text in a react widget. We will post the final copy in this ticket for Danielle to approve and use ticket #34123 to add the text to the react widget. 

## Tasks
- [x] Add Q&A content to pages (Selina)
- [x] Review (Randi)
- [ ] Final review (Danielle)

## Acceptance Criteria
- [ ] Notification text is approved and ready to be added to react widgets

**Comment by lunascoop** [comment]
@RLHecht The content I added to these pages are ready for review. Please keep in mind that I'm also working w/Kelson in ticket #33313 to remove content from the react widget. So, right now the page will appear to have duplicative content. The added questions are in the second version (towards the end of the page).

- Refill and track VA prescriptions: http://preview-prod.vfs.va.gov/preview?nodeId=27 (How do I sign up to get shipment notifications?)
- Schedule and manage health appointments: http://preview-prod.vfs.va.gov/preview?nodeId=37 (Can I get appointment reminders?)
- Get your VA medical records online: http://preview-prod.vfs.va.gov/preview?nodeId=33 (Can I get medical images and report notifications?) <--I added this to the list since you can get email notifications through MHV like the prescriptions page.

**Comment by RLHecht** [comment]
@lunascoop I reviewed all of these and tweaked the appointments page by adding some h3s. Let me know what you think. I can't decide if I made the answer too long this way but I thought it was an easier way to distinguish between text and email.

**Comment by RLHecht** [comment]
@andaleliz Can you please review the above copy to make sure what we have is accurate? Danielle is still reviewing our language so it's not quite ready to go on the pages yet. Thanks!

**Comment by andaleliz** [comment]
The refill/tracking prescription is tricky - you can get text notifications for those, but only at 2 VAMCs as far as I know (Denver and Asheville). It feels overly complicated to write logic to try to conditionally display that here, so I think it's fine as-is until those notifications are rolled out across all VAMCs.

The other 2 look great! Thanks.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @lunascoop. Thank you! Here's the content with my edits. Reasons for edits and a question below:
- Gave questions a little more context for clarity
- Broke up some sentences to keep sentence length short
- Reframed this note so that it's framed in the positive: **Note:** You can get notifications with a Basic or Premium **My HealtheVet** account. 
- Made the button names on MHV sentence case. I'm assuming you had them title case because that's how they appear on MHV. Randi, you're the copy editor - if you think that's best, to match rather than use our style, I'm good with it!
- Question: The one for prescriptions is framed as "How can I get..." and the others are "Can I get..." Is this intentional because of surrounding content on the page? If yes, that's great. If not, let's revisit to make consistent.

## [Refill and track VA prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)

### H2: How do I sign up to get shipment notifications?

You can sign up to get notifications by email on the **My HealtheVet** website. 
**Note:** You can get notifications with a Basic or Premium **My HealtheVet** account. 

**If you’re signing up for a My HealtheVet account,** go to “Notifications and Settings” on the registration page and select **On** for “Rx refill shipment notification." 
[Sign up for an account on the My HealtheVet website ](https://www.myhealth.va.gov/mhv-portal-web/user-registration/)

**If you already have a My HealtheVet account,** go to your profile page to update your notification settings. 
[Sign in to your account on the My HealtheVet website](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/user-login?redirect=/mhv-portal-web/user-registration/user-login)

## [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments/)

### H2: Can I get appointment reminders? 
Yes. You can sign up to get appointment reminders by text message or email. 

#### H3: For reminders by text message
Update your notification settings in your VA.gov profile. 
[Sign in to VA.gov ](https://www.va.gov/?next=/profile/)
**Note:** Your wireless service provider may charge messaging and data rates for any messages sent to you from us and to us from you.  
[Read our terms and conditions for messaging rates](http://preview-prod.vfs.va.gov/privacy-policy/digital-notifications-terms-and-conditions)

#### H3: For reminders by email
Sign up on the **My HealtheVet** website. 
**Note:** You can get reminders with a Basic or Premium **My HealtheVet** account 

**If you’re signing up for a My HealtheVet account,** go to “Notifications and Settings” on the registration page. Select **On** for “VA appointment reminder.” 
[Sign up for an account on the My HealtheVet website ](https://www.myhealth.va.gov/mhv-portal-web/user-registration/)

**If you already have a My HealtheVet account,** go to your profile page to update your notification settings. 
[Sign in to your account on the My HealtheVet website](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/user-login?redirect=/mhv-portal-web/user-registration/user-login)

## [Get your VA medical records online](https://www.va.gov/health-care/get-medical-records/)

#### H3: Can I get notifications when my medical images and reports are ready? 
Yes. You can sign up to get notifications by email on the **My HealtheVet** website.
 **Note:** You can get notifications with a Basic or Premium **My HealtheVet** account. 

**If you’re signing up for a My HealtheVet account,** go to "Notifications and Settings" on the registration page. Select **On** for "VA medical images and report available notification." 
[Sign up for an account on the My HealtheVet website ](https://www.myhealth.va.gov/mhv-portal-web/user-registration/)

**If you already have a My HealtheVet account,** go to your profile page to update your notification settings. 
[Sign in to your account on the My HealtheVet website](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/user-login?redirect=/mhv-portal-web/user-registration/user-login)

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA thanks for your edits and feedback.

The reason why I framed the refill prescriptions question "How can I get..." vs. "Can I get..." because there's a bullet point in the **How can VA’s prescription tool help me manage my health care?** section that already tells users that they can get email notifications about when to expect your prescription.

**Comment by DanielleThierryUSDSVA** [comment]
Ah, that makes sense - thanks, @lunascoop!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @lunascoop. Adding this as a reminder for us to discuss when we all get back from the holidays: My HealtheVet vs. My VA (Cerner) portals in the different views and how this notifications content needs to work into that.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I'll look at your calendar and set something up for the three of us in the next few days.

**Comment by RLHecht** [comment]
This work is blocked until we also update the health care tool landing pages since these pages will require Public Websites help because the pages aren't in Drupal. We want to do all the work at the same time.

**Comment by SgardnerPMP** [comment]
Added dependency to Ticket #34123.

**Comment by andaleliz** [comment]
Hi all! Just checking in on this to see if there is an ETA on when this may get completed. Thanks!

**Comment by andaleliz** [comment]
Hi! Just checking in to see if there are any updates available since we last chatted. Thanks :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz! @RLHecht is out this afternoon so I'll answer. The medical records page updates are complete, but we're holding for a final sign off from DoD. Should launch soon!

**Comment by RLHecht** [comment]
@andaleliz Wanted to let you know that our updated [medical records page](https://www.va.gov/health-care/get-medical-records/) is finally published! This also incorporates the notification updates we had discussed. We are still working through the other health care pages and I'll let you know when those are complete.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
