### ISSUE TITLE
[VAMC] Lovell Federal health care  - Create and consolidate primary pages as "one-off" Shared DoD and VA pages [VAMC/Facilities]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33356]
## VAMC - Product Outline
[VAMC-upgrade Product Outline 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2021.md)

## High Level User Story/ies
**Solution Goals**

Provide to Veterans accessing the VAMC websites a user experience that provides solutions to key touch points in the end-to-end Veteran healthcare journey. Utilizing the Pilot website as a basis on which to improve and foster a better user experience for each of the VAMC websites.
**User Goals**

Provide a straight to the point navigation that will allow the Veteran to quickly find and complete their journey on the VAMC website and utilized the website as their reference site to satisfy all their online goals.

## Legacy Site
[Google Drive locations for VISN-8](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)

## TASKS
See below associated tasks which should include, but are not limited to:
- [ ] Determine shared pages
- [ ] Design new shared experience for Veterans and active duty DOD web users
- [ ] Determine if pull information or redirects should be used for DoD facilities
- [ ] Design and create new DoD Facility pages (How to best link them in Locations?)
- [ ] Initiate Veteran and active DoD research to validate pages are helpful and support needs of both users in this area
- [ ] Document special requirements 
- [ ] Implement inputs from research
- [ ] Publish new pages in Dual state
- [ ] Set production go live date and work with PAO to launch

## Acceptance criteria
- [ ] New pages have been designed and created
- [ ] Pages have gone through QA, Platform, design and content reviews
- [ ] New VAMC/DoD website is published in Dual state for validation

**Comment by mmiddaugh** [comment]
This will be addressed as part of the https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9655
