### ISSUE TITLE
SD - Define goals and metrics for Form detail page 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#33357]
## Issue Description
Define goals and metrics for For form detail page 

Research to answer PO's questions regarding form detail page

How do we measure success?
Why do not all veteran-facing forms have custom pages?
What other things need to happen? Or it fine the way it is?

Background:
Why do not all veteran-facing forms have custom pages?
Publishing a new form detail landing page.pdf details the process of creating a detail page for a form.

Basic detail pages:

When a forms manager adds a new form to the VA's forms database, a basic detail page automatically gets created (But does not always get published)
Every form, except a few internal forms that were already in the system before Find a VA Form existed gets at least a basic detail page.
Customized detail pages:
In order for a detail page to be a customized detail page it needs to at least contain descriptive text for the "When to Use" section.

The process to create a customized detail page:

The additional metadata for the top 100 forms (minus the 35-40 that already had custom pages) would be drafted by Content. The list of forms needing content was broken into 3 batches.
PO would send the draft for each batch to the VA stakeholders for them to make any corrections or changes
That draft would be given back to Content so they could polish it and make sure if follows plain language conventions
Those updates would be sent BACK to the VA for final approval
PO would enter the meta data for that batch into the CMS and publish
What other things need to happen? Or it fine the way it is?
From Marci: "Ideally each form page would contain information on how to complete the form, and where and how to submit it. Unfortunately, that information doesn't appear on every PDF form, and we would need someone at the VA to provide that info, and someone in Content to review and make sure it is worded according to VA web content standards."

How do we measure success?
Hypothesis: Form Detail Pages increase SEO and in turn increase visits and form submissions. Custom Form Detail Pages have additional information such as "When to use this form" that further increase SEO and help Veterans complete the correct form.
Every Form Detail Page has a history in the CMS showing when it was created and published. We could possibly measure visits and submission rate before and after Form Detail Page updates. This is dependent on the CMS history details being specific enough to determine the changes made.

Additional information:
Linda's Form Detail Pages meeting notes with Marci

Answers from Marci on Slack

Mini-product outline for form detail landing pages

Find a Form DOMO dashboard
Reference [33085](https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/33085)

---
## Tasks
- [ ] _Review background discovery findings for form detail page_
- [ ] _Clearly identify how to measure the top KPIs_
- [ ] _Create Metrics and Baseline list, include the most effective measurable KPIs_
- [ ] _Discuss Metrics and Baseline list with PO and get approval_

## Acceptance Criteria
- [ ] _Identify the most appropriate success metrics for Form detail page and how to track and measure them_
- [ ] _Finalized and approved metrics and baseline list_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindaLi123** [comment]
Blocked waiting for PO's response

**Comment by nicole-leonard** [comment]
I have uncovered many issues regarding forms/finding forms and will be opening separate tickets to address them. We will need to fix issues before we can determine metrics.
