### ISSUE TITLE
Provide edited content for unsubscribe page to VANotify team

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33361]
## Issue Description
The VANotify team opened intent request ticket #32980 asking for content support for new unsubscribe pages. 

We need to review the mockups provided and rework for plain language and to ensure it meets VA.gov's voice and style standards. 

We should use this ticket for the work and the provide our final edits in the content request ticket mentioned above.

## Tasks
- [ ] Rework content (Selina)
- [ ] Review/copy edit (Randi)
- [ ] Final review (Danielle)

## Acceptance Criteria
- [ ] Final content is ready to be shared with VANotify team

**Comment by lunascoop** [comment]
Suggest moving to the backlog until the mockups are finalized. 
Last week, we met w/ the team and Mikki to review the mockups. Here are some notes:

- They won't be adding feedback features (i.e., "If you have a moment, please let us know why you unsubscribed:") for MVP
- They still need to develop the Resubscribe page
- They'll be doing user interviews to get feedback about the workflow and other recommendations

**Comment by RLHecht** [comment]
Moving to blocked as a new team is picking up this work and they'll let us know when they're ready to start working on it again.
