### ISSUE TITLE
Write Documentation for Creating TUD User

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#33363]
## Issue Description
Write documentation for the manual process for creating new Test Users with external service providers.

---
## Tasks
- [x] TUD `readme.md` is updated

## Acceptance Criteria
- [x] `readme.md` clearly describes about to add a new test user account to TUD
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR updating `readme.md` - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/95
