### ISSUE TITLE
Create feature toggle for health apartment experiments

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33387]
## Description
As Product, I would like a feature toggle so that I can manage any proof of concept and experimentation work separate from any actual health apartment work.

## Tasks
- [x] Create backend toggle
- [x] Create frontend toggle and selector

_Suggested naming convention: va_online_scheduling_poc_health_apt_

## Definition of Done
- [x] All tasks are complete
- [x] Name of toggle is noted in this ticket
- [x] (Product) documents in [feature toggle documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md)

**Comment by jenniemc** [comment]
feature toggle name `va_online_scheduling_poc_health_apt` added to vets-api backend

**Comment by laurenernest** [comment]
Toggle is in admin. Closing ticket.
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/2d6b2e15-1c8f-4ba7-9b61-8054348dd589)
