### ISSUE TITLE
Pivot from Newsletter - Run communications roundup experiment

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#33390]
## Issue Description
Run an experiment posting digests of Platform changes and informational announcements on a regular cadence on Platform website and Slack #vfs-all-teams channels.

Purpose: Train VFS team members to expect to hear news about Platform on a regular cadence in #vfs-all-teams and on the Platform website. Provide timely, relevant notifications to VFS teams about changes that will impact their workflows.

Measuring success: https://vfs.atlassian.net/l/c/vWnPoDVD

---
## Tasks
- [ ] Determine experiment details - answer questions listed here: https://vfs.atlassian.net/l/c/mjCJe8X0
- [ ] Create a sample ToT announcements page
- [ ] Add examples from recent ToTs

## Acceptance Criteria
- [ ] We have determined if the communications roundup experiment has meet the success criteria.
- [ ] We have determined if the communications roundup should be an ongoing service provided by the Platform.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
2/16/2022:
Closing this for now since it is not prioritized.
