### ISSUE TITLE
[VAMC] Validate Lighthouse API redirects for all systems released to full production {BA}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33409]
## Story
As a Veteran looking for VAMC facilities and COVID-19 Vaccines on Facility Locator I need the correct URL link, so it will take me to the new VAMC websites.

## Goal
Create a repeatalbe process of creating the Lighthouse API url csv file that will be loaded to VAMC SharePoint for Lighthouse API

## Resources
[Previous Lighthouse API files](https://governmentcio.sharepoint.com/sites/VSATeam/Shared%20Documents/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FVSATeam%2FShared%20Documents&viewpath=%2Fsites%2FVSATeam%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FVSATeam%2FShared%20Documents%2FVAMC%2DWeb%5FModernization%2FFull%5FProduction%5FPrep%5FFiles%2FLighthouse%5FAPI%5Ffiles&viewid=0df60f54%2Ddd97%2D4321%2Da9e5%2D9c92d607ae91)

## TASKS
**Transform all system facilities in Post production**
- [x] Review Systems listed in csv files for systems that were deployed to full production
- [x] Confirm all systems and facilities have been redirected within lighthouse API
- [x] Any systems not in listing must be added to final .csv file for lighthouse API

## Acceptance criteria
- [x] All systems are reviewed
- [x] any systems found not to be redirected are now in final csv files.

**Comment by ltrombley** [comment]
Task #33409 - Validate Lighthouse API redirects for all systems released to full production {BA}  - is Complete and moved to Validate.
