### ISSUE TITLE
[VAMC] Groom data and content within VAMC - Upgrade SharePoint site for training, resources and tools [ BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33410]
## Story
As a VAMC web maintainer I need to have access to tools, presentations, and documentation supporting the VAMC product, so I can continue to maintain my web pages.

## resources
TBD

## Tasks
Organize all data and tools within VAMC Upgrade SharePoint
- [ } Sort data into useful folders
- [x] Archive production documents separately
- [x] Review and rename videos with descriptive names
- [ ] 

## Acceptance Criteria
- [x] VAMC-Sharepoint is updated with useful folders
- [x] product creation artifacts are archived separately
