### ISSUE TITLE
Review What's New entry to style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33414]
## Issue Description
We updated three things recently in the style guide (Veteran, zip code, apostrophes and quotation marks) so we should account for them in the What's New section of the style guide. 

This PR shows the work completed: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/590

## Tasks
- [x] Review additions (Beth/Danielle)
- [x] Merge PR (Beth/Danielle)

## Acceptance Criteria
- [x] Content is updated in style guide

**Comment by RLHecht** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA Could one of you review this for this sprint? I added the items we updated in the style guide to the What's New section.

**Comment by RLHecht** [comment]
Beth reviewed and I merged the PR. Will close the ticket once it's live.

**Comment by RLHecht** [comment]
This is live. Closing ticket.
