### ISSUE TITLE
Setup Datadog dashboard to track MCP metrics

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#33415]
## Issue Description
StatsD calls have been added to track policy success/failure and VBS success/failure for MCP and we need a Datadog dashboard/graphs in place to track these counts and ratios.

---
## Tasks
- [ ] Create new dashboard
- [ ] Graphs to track success & error

## Acceptance Criteria
- [ ] KPIs are able to be seen within Datadog
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Awaiting on platform to be ready for data dog
