### ISSUE TITLE
Staging Review [Design System Team- Progress Bar & Segmented Progress web component]

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33418]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [ ] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [ ] Schedule meeting with Platform reviewers and VFS team attendees listed in ticket. 
- [ ] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Progress bar https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/32866
- [ ] Segmented progress bar  https://60f9b557105290003b387cd5-aaohbcufhp.chromatic.com

- [ ] Product outline  - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: Carol Wong
- OCTO-DE Product lead: Ryan Thurlwell
- OCTO-DE Design lead: Ryan Thurlwell

### Team Members

- Andres Rivera
- Katy Bowman
- Brooks Johnson
- Preston Davies
- Courtney Chambers
- Natalie Hill (optional)

### VFS Attendees

- Content and IA: 
- Accessibility: 
- QA specialists: 

## Scheduling

Thursday, Dec. 9 at 1:30pm ET

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@caw310 we can't do Thursday at 1:30. Would Friday 12/10 at 2:00pm ET work?

**Comment by caw310** [comment]
@shiragoodman , we could do Friday 12/10 at 2pm ET. Oddball folks can miss the first part of the holiday party.

**Comment by shiragoodman** [comment]
oh no! I didn't realize it was the holiday party. How about Tuesday 12/7 instead? we have 11am ET and 11:30am ET available.

**Comment by caw310** [comment]
Let's do 11am on 12/7 then.

**Comment by shiragoodman** [comment]
scheduled for 12/7 at 11am

**Comment by allison0034** [comment]
No design feedback

**Comment by jimuhh** [comment]
Looks good, and I'm all for a consistent experience across products. So, no IA feedback at this time.
