### ISSUE TITLE
[Design] Auth Profile: Update Personal Info Sketch files & Prototype to link "why we ask for this" to R&S article

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33420]
## Background
Based on [this conversation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32327#issuecomment-983767025), the "Why we ask for this" copy at the top of the Personal Info page will likely be linked to a Resources & Support article.

## Tasks
- [x] Update Sketch files to show "why we ask for this" text as a link to an R&S article instead of an expandable info box.
- [x] Update Personal Info prototype to show the same change.

## Acceptance Criteria
- [x] Sketch files show "why we ask for this" text as a link to an R&S article instead of an expandable info box.
- [x] Update Personal Info prototype to show the same change.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske getting caught up.  Is this ticket complete?  Thank you!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO yes! All updated to reflect our current content.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @cgednalske!
