### ISSUE TITLE
[Design/Research] Auth Profile - Update research plan to include LGBTQ+ recruitment language based on Cindy's example

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33424]
## Background
Cindy Merrill on the Public Websites team previously compiled [an approved research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/research-plan.md)that included language for requesting participants in the LGBTQ+ community from Perigean.  Please review the recruitment portion of that plan and use as an example for updating the Personal Info research plan.

## Tasks
- [x] Review recruitment info in Cindy's above-linked research plan
- [x] Craft similar language to include in the Personal Info research plan
- [ ] Ask Cindy to review and make any recommendations
- [x] Send to Liz & Marci  for review
- [x] Once all reviews/edits are complete, send to Samara for her review/recommendations
- [x] Incorporate any changes requested by Samara
- [x] Return to Samara for final sign-off 

## Acceptance Criteria
- [ ] Language for recruiting members of the LGBTQ+ community has been added to the reserach plan based on Cindy's approved example.

**Comment by cindymerrill** [comment]
@MarciMcGuireGCIO To clarify, my research plan was approved by my team and PO (Dave Conlon) but _not_ by Lauren Alexanderson because I didn't launch recruiting. However, I did exchange slack messages with Lauren about what I wanted to do and how, but I don't think she saw my final wording.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for that clarification, @cindymerrill !

**Comment by cindymerrill** [comment]
@cgednalske shared her research plan with me in Slack, and I replied with a bunch of comments about participant recruiting, which I hope will be addressed before recruiting is launched. Looking forward to hearing how recruiting goes! @MarciMcGuireGCIO

**Comment by cgednalske** [comment]
@cindymerrill provided some fantastic feedback clarifying/enhancing the screening questions and recruitment criteria! I will incorporate this feedback and confirm the changes shortly.

**Comment by MarciMcGuireGCIO** [comment]
This language has been added to the recruitment guide.
