### ISSUE TITLE
[Design/Research] Auth Profile - Update research plan to include LGBTQ+ recruitment language based on Cindy's example

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33425]
## Background
Cindy Merrill on the Public Websites team previously compiled [an approved research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/research-plan.md)that included language for requesting participants in the LGBTQ+ community from Perigean.  Please review the recruitment portion of that plan and use as an example for updating the Personal Info research plan.

## Tasks
- [ ] Review recruitment info in Cindy's above-linked research plan
- [ ] Craft similar language to include in the Personal Info research plan
- [ ] Ask Cindy to review and make any recommendations
- [ ] Send to Liz & Marci  for review
- [ ] Once all reviews/edits are complete, send to Samara for her review/recommendations
- [ ] Incorporate any changes requested by Samara
- [ ] Return to Samara for final sign-off 

## Acceptance Criteria
- [ ] Language for recruiting members of the LGBTQ+ community has been added to the reserach plan based on Cindy's approved example.

**Comment by MarciMcGuireGCIO** [comment]
Duplicate due to ZenHub error
