### ISSUE TITLE
[Design] Research pattern for indicating required fields, apply to Personal Information page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33426]
## Background
There are already patterns for indicating when a field is required .  In the case of the new Personal Information fields, we need to understand if:
1) All new fields are required from the outset
2) When someone selects the "other" option for a given section, does the accompanying text field immediately need to indicate that it is now required?
3) Is the required error state ONLY displayed on text fields if the user selects "other", fails to enter a value in the accompanying text box, and then attempts to save?

## Tasks
- [ ] Research the above questions and document the answers in this issue and in the design specs in GitHub
- [x] Update the Sketch files to reflect the correct behavior
- [x] Update the prototype to reflect the correct behavior

## Acceptance Criteria
- [ ] Questions listed in Background section above are answered and recorded in the design specs in GitHub and this ticket
- [x] Sketch files are updated to reflect the correct behavior
- [x] Prototype is updated to reflect the correct behavior

**Comment by cgednalske** [comment]
(*Required) does not appear in Personal Information edit states as it does in the Contact Information and Direct Deposit, for example:
<img width="392" alt="Direct Deposit - Required" src="https://user-images.githubusercontent.com/79372956/144458591-81982135-5cb7-4f44-b207-caac909dd957.png">
<img width="568" alt="Contact Information - Required" src="https://user-images.githubusercontent.com/79372956/144458606-5ba3f6a3-478e-41b5-bf79-1fda26355cc7.png">

**For review and confirmation:**
(*Required) added to edit states to make it clear that a choice must be made in order to save. Question - should the exception to this be the Preferred Name edit state, where we do not have a "Prefer not to answer" option?
<img width="414" alt="Personal Information - Required" src="https://user-images.githubusercontent.com/79372956/144458799-ba95d8b7-188f-40a6-adf4-a4a93a685e83.png">

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @cgednalske.   I think I need to try to clarify the questions I asked at the top.

The first question was about the new Personal Info fields themselves vs. the text fields used to provide "other" options.     @Samara-Strauss  - do you happen to know if users will be required to fill the new Personal Info fields?

The second and third question was intended to identify the event that triggers the display of the "required" message next to those "other" text fields.  Does that occur immediately when the user selects the "other" option, or when they try to save their changes after selecting "other" and leaving the text field blank?

It may be worthwhile to check the [design system](https://design.va.gov/) to see if there are already existing patterns.  If not, it might be good to attend design open office hours to ask.  Liz can probably give you some pointers on that.  

I hope that helps!

**Comment by cgednalske** [comment]
Thanks, @Marci! I can clarify my response as it relates to the other points. I did not find discrepancies there from what Kevin included and what is in the design system.

> The first question was about the new Personal Info fields themselves vs. the text fields used to provide "other" options. @Samara-Strauss - do you happen to know if users will be required to fill the new Personal Info fields?

Yes the "other" option currently does require the user to fill in the input, and Kevin's used the error state already in the design system to show that. 


<img width="556" alt="Error State - Gender Identity" src="https://user-images.githubusercontent.com/79372956/144472754-a88c0799-7f98-4f44-a3a9-971a9773a4f5.png">

> The second and third question was intended to identify the event that triggers the display of the "required" message next to those "other" text fields. Does that occur immediately when the user selects the "other" option, or when they try to save their changes after selecting "other" and leaving the text field blank?

The error states are triggered when they try and save and move on from the page after selecting "other" and leaving the text field blank. And before that, the regular input field is display on the initial edit state.

I found all of these elements in the design system, and was able to determine that the only thing still missing was the (*Required) text seen elsewhere on Profile for similar items. So I believe the only design element still in question is to make sure we are ok with adding this as I have shown above.

Thanks! Sorry that I was not clear on all that before!
