### ISSUE TITLE
[FE] Update verb and noun language for pre-check-in

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#33434]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/847B453D-F19E-4D55-9EE6-C523E7408879)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1638304489117400)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

From @ytsaoca on slack:
According to Danielle, we confirm the terms: 

- Check in for verb
- Check-in for noun
- Pre-check in (verb) and pre-check-in (noun)

I updated the mockups. (mainly the changes are the title, for example, Start pre-check-in, Answer pre-check-in questions, and You’ve completed pre-check-in, and a sentence on the Verify Identity page) Please help update the screen. Thanks!

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update pre-check-in text where needed
- [ ] Create or update unit tests
- [ ] Create or update e2e tests

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Screenshots for review @ytsaoca:
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d66021a1-e7d6-45a9-8c3b-c43ccdde8a28)
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (2).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/3f2d9039-8f29-44f2-aa59-52fe6195e4c0)

**Comment by ytsaoca** [comment]
@brianseek  About the introduction page for multiple appointments, the content should be "Your appointments are on..."
<img width="261" alt="Screen Shot 2021-12-08 at 11 40 28 AM" src="https://user-images.githubusercontent.com/90633685/145257190-d790788d-bc5d-4fc5-97f8-aaff91ce5a4b.png">

**Comment by ytsaoca** [comment]
@brianseek  And verb and noun language looks good :)

**Comment by brianseek** [comment]
@ytsaoca Here is a screenshot update for the multi-appointment text:
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (3).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/24c69f9f-18c1-4d93-b9cc-7478cb9eaa29)

**Comment by acrollet** [comment]
@ytsaoca we believe this has been reviewed, if not will you please re-open? Thanks!
