### ISSUE TITLE
Address Redirect Issue for Search Rep

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33437]
## Background
When browsing to `/view-change-representative/search/representative-type/` it is redirecting back to the `/introduction/` page on staging

## Considerations
https://user-images.githubusercontent.com/53826255/144294413-67c731da-7fae-4e19-b106-0cb4c5f450dc.mp4

## Tasks
- [ ] Reach out to Platform support
- [ ] Go down that rabbit hole
- [ ] Document procedures to address this issue into GH, share with team

## Acceptance Criteria
- [ ] The cause is determined
- [ ] Fix is in place, if possible (stretch)
