### ISSUE TITLE
Content updates to C&P exam page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33431]
## Issue Description
Stakeholders reached out to our team saying that wording we have on our [VA claim exam](https://www.va.gov/disability/va-claim-exam/) page is confusing and needs to be updated. 

Under the H2 "How to schedule your VA claim exam," the question "How will you contact me to schedule the exam?" is misleading because Veterans can't schedule exams. This is what the stakeholders explained:

VBA claims processors use a tool to request C&P exams. It is up to the contractor (or, on the rare occasion, a VHA facility) to schedule a C&P exam. It’s at that point that the contractor notifies the Veteran of the appointment. It’s only at this point that the Veteran has any say in when the appointment will happen. Contractors are supposed to work with the Veteran to resolve any conflicts or to discuss a more convenient place and/or time. “How to schedule your VA claim exam” should say, instead, “Who will schedule my VA claim exam?” There should also be a brief explanation of how this really works, to provide clarity and to be transparent about what happens and what to expect next.

The stakeholders are going to provide us with new content for this Q&A, which we will need to edit for plain language and to make sure it matches our voice and style. Once we do our edits, we will send to Beth for a final review and then to the stakeholders for approval before publishing. 

Update: Here's language that stakeholder Bryan Lett sent from a C&P exam communications plan:

Q: How is the VA claim exam or C&P exam scheduled?
A: VA or a VA contract examiner will either mail you a letter or call you with your appointment date and time. If you are receiving treatment at a VA medical center, make sure the facility has your current address, phone number and email information. The wrong information could cause your appointment letter to be delayed and not reach you in time. You can request the specific sex of your medical provider for gynecological, breast, anal/rectal and mental health exams during the scheduling process. Also, if your claim is related to a mental or physical health condition resulting from Military Sexual Trauma (MST), the law permits that you may choose the sex of your examiner. Please notify your scheduler if you have a preference for the sex of your examiner. Prior to your exam, contact the VA or contracted examiner to confirm your exam date, time and location. If you don’t show up to your exam, it may delay your claim. Additionally, your claim may be decided based on the evidence of record.

There is also this fact sheet that may have helpful info: https://www.benefits.va.gov/COMPENSATION/docs/claimexam-faq.pdf

## Tasks
- [x] Edit content for plain language, voice, and style
- [x] Copy edit
- [x] Final review (Beth)
- [x] Send to stakeholders (Beth/Randi)
- [x] Review and publish
- [x] Notify stakeholder changes are live

## Acceptance Criteria
- [x] New content is live on C&P exam page

**Comment by RLHecht** [comment]
@lunascoop I updated the top of this ticket with new info that the stakeholders provided.

**Comment by lunascoop** [comment]
@RLHecht The pages is ready for review. I made changes per the stakeholder request and for sighted language.
VA claim exam (C&P exam): http://preview-prod.vfs.va.gov/preview?nodeId=914

**Comment by lunascoop** [comment]
@bethpottsVADEPO this page is ready for your review.

VA claim exam (C&P exam): http://preview-prod.vfs.va.gov/preview?nodeId=914

Some notes:

- Changed misleading header to "Before your VA claim." This is in flow with the next two headers **What to expect at your VA claim exam** and **After your VA claim exam**
- Changed first accordion question to **"Who will schedule my claim exam?"** (per the stakeholders request)
- **Possible question for stakeholders:** In the first accordion's first sentence, we weren't sure if we should change **"The staff at your local VA medical center or a local doctor’s office"** to **"VA or a VA contract examiner..."** per the information the stakeholder provided. We're not sure what if they have the same meaning or we should reach out to the stakeholder's for clarification. We left it as is for now because we thought it was a more plain language version of what they provided.
- For the second accordion, I added content for rescheduling their exam. Also added content for requesting your doctor's gender, and changed "gynecological" to "reproductive health". We weren't sure if that was more plain language. We looked at the women's health page for guidance but there wasn't anything that specific.
- For the third accordion, added content to let us know 48 hours in advance per the fact sheet the stakeholders provided. Also added content for what happens if they don't show up to their appointment.

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht 
Your H2 needs to capture that this section is specifically about scheduling:
**How we schedule your claim exam**

Since we'll make the "who" clear in the H2 (above), let's keep the first accordion label as is. "How will you contact me..."

Additional updates to improve the page: Please set apart this section where the H2s aren't questions because all the accordion labels are. Place a horizontal line above this H2 and another one following the last grouping of accordions on the page. I'd also like to take out "VA" from the other 2 H2s: What to expect at your claim exam / After your claim exam. It starts to feel like overkill on this page to use it in every H2. 

We need to revise the text for that first accordion to account for the fact that the stakeholder indicated that it's rarely a VHA facility that reaches out. So this is misleading: "The staff at your local VA medical center or a local doctor’s office that we partner with." Let's keep it general as "we" (I don't think it's particularly relevant for Veterans to know that it's a contractor or examiner who will contact them): 

We'll mail you a letter or call you with the date and time of your exam.

Make sure both the VA regional office and the VA medical center nearest you have your up-to-date address, phone number, and email address so you get your exam notice in time.

For the second accordion, I like that you added the info from the fact sheet about the option to request the gender of your doctor. But the first paragraph of text there needs to be reworked a bit more. It doesn't make sense what's on the live site right now. The accordion label/question indicates that you may get a phone call. Unless this is an automated call (which we should inquire about--Randi would you include this in your note to the stakeholders?), it wouldn't make sense to "call the number provided" if you're already on a call. If it's an automated call, we'll have to rewrite again... but for now, we can edit this text to say: 

Please confirm the time and location of your exam. If you received a letter, call the number we provided to confirm your exam. It’s important not to miss your scheduled exam, so you’ll want to double check that you have the right place and time.

During scheduling, you can also request the gender of your doctor in these situations:
- If you're having a reproductive health, breast, rectal, or mental health exam, **or**
- If your claim is related to a mental or physical health condition related to Military Sexual Trauma (MST)

Changing the phrasing to "reproductive health" is definitely more PL, so that's good (and aligns with VAMC text). I'm not sure about rectal vs anal exam--did you look that one up already? Just from a quick google search, I'm seeing rectal is the more common way to phrase it. Would you double check? This we can always change later, after we clear the rest of this request with the stakeholder. So don't let it hold things up.

I agree with adding the 48 hours in advance text. Thank you!

Would you make these changes in drupal, then ping me before going to stakeholders?

**Comment by lunascoop** [comment]
@bethpottsVADEPO Thanks for the feedback! I've made the changes you requested to the page. I also had some follow-up questions.
VA claim exam (C&P exam): http://preview-prod.vfs.va.gov/preview?nodeId=914

- Is changing the first accordion question back to what's currently live on the site misleading (**How will you contact me to schedule the exam?**)? From what I gathered, the exam is already scheduled, we're just notifying them that it's been scheduled. Would it be better to say something like: **How will you contact me about my scheduled exam?**
- For the second accordion, should we include the sentence about rescheduling your exam? According to the info the stakeholders provided, this is the stage where they can reschedule their exam. Also, is saying "During scheduling,..." misleading? Technically, they're just confirming the appointment (unless they're rescheduling it).
- If we decide to leave the rescheduling part out from the second accordion, we should also remove that tidbit from the third accordion too, right?
Thanks!

**Comment by bethpottsVADEPO** [comment]
I made some more edits directly in the file. @RLHecht @lunascoop please take a look to make sure I've covered everything. 

- It's a little complicated, I think, because, yes, it's already scheduled, but then it sounds like VA thinks of the confirmation part of that process as scheduling too. But I reworded it to try to be more clear. I also added a "Note" in that first accordion text to drive home what seems to be the misunderstanding/pain point for VA about who initiates the scheduling. 
- Yes, I added rescheduling back in. And I got more specific with the wording ("when you confirm your appointment"), even though VA does seem to consider the confirmation step part of the scheduling process overall. 
- I edited the 3rd accordion label and the first sentence of text since "can't make it" is an idiom. 

Let me know if you think there's anymore to discuss or if it's ready for SMEs to review.

**Comment by RLHecht** [comment]
These changes look good to me, @bethpottsVADEPO. I just made a few copyedits. Here's the email I was going to send Bryan. Let me know if this looks good:

Good morning, Bryan. We wanted to share the preview link of the revised claim exam page: http://preview-prod.vfs.va.gov/preview?nodeId=914 You must be on the VA network for the link to work.

You’ll see that we used the information you provided in the fact sheet to make things clearer. We also made sure everything was written in VA.gov’s voice and style as well as met our plain language standards.

One question we had for you was if the phone call Veterans get when their exam is being scheduled is automated or with a real person. We wrote these responses with the assumption it is a person they can talk to and discuss changing the appointment as well as requesting the gender of the doctor, but if we need to rework this, please let us know.

If these changes look good to you we can have this live on the site later today.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Your email to SMEs looks good. Would you just add a paragraph to the explanation? Add this following the paragraph where you provide the preview link: 

"We edited the text in that first grouping of 3 accordion links. The subhead there now indicates that VA, not the Veteran, schedules the appointment: **How we schedule and confirm your claim exam**. And we also added a note within the text of the first link that explicitly says that Veterans can't start the scheduling process."

Thanks for communicating all this to the stakeholders!

**Comment by RLHecht** [comment]
Here's the Word doc with edits back from the stakeholder. @lunascoop and I will put our edits in this for @bethpottsVADEPO to review and then we can put in Drupal to send to the stakeholder for another review.

[https://app.zenhub.com/files/133843125/04c5ff1e-f958-4b38-9947-32300227375c/download](https://app.zenhub.com/files/133843125/04c5ff1e-f958-4b38-9947-32300227375c/download)

**Comment by lunascoop** [comment]
@RLHecht here are my edits to the word doc. Let me know if you have any questions.
[VA Claim edits- SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7694350/VA.Claim.edits-.SC.docx)

**Comment by RLHecht** [comment]
Thanks @lunascoop I just added in a few comments for the stakeholders to know why we didn't accept some of their changes.  @bethpottsVADEPO This is ready for you to take a look at. Selina has a note in there about the difference between VA and the contract vendor. Let us know what you think.
[VA.Claim.edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7694707/VA.Claim.edits.docx)

**Comment by bethpottsVADEPO** [comment]
@RLHecht I also wanted to mention, we may not need to show all the PL edits for all the additional accordions the SME submitted changes for. If we can reduce the feedback that we'll send back to them where we generally agree with their input with just minor edits, that may simplify and speed up the process of getting these edits live. Maybe only call out in the Word doc where we want to revert back to something we edited previously or if we disagree with their edits. I don't think there are too many of those. We can step through each bit of text if you want clarification on this.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I reworked our edits in the doc. Can you please take a look? I didn't make some of the plain language edits we did in our original version. Let me know if you think this is good to send to the stakeholders.
[VA claim exam (CP exam)-edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7713052/VA.claim.exam.CP.exam.-edits.docx)

**Comment by bethpottsVADEPO** [comment]
[https://app.zenhub.com/files/133843125/c513bb68-372d-4f58-9140-7e62f637e21d/download](https://app.zenhub.com/files/133843125/c513bb68-372d-4f58-9140-7e62f637e21d/download)

@RLHecht Here are my additional edits/approach to providing feedback to SMEs. Thanks for the convo about this today, and let me know if you have any questions.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the revised word doc with new screenshots and cleaned up comments. I was going to also say in the email we send that we made some small plain language updates throughout and give one example so they are aware of why we made some of the other edits. If this looks good I'll send it off
[VA claim exam (CP exam)-edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7720733/VA.claim.exam.CP.exam.-edits.docx)
!

**Comment by bethpottsVADEPO** [comment]
Thank you for all the changes you made. I still see the hours without the zeros though--could you add those in? And there's a typo in one comment, under "Will I get my exam results at the VA claim exam?" --We ~Will~ simplified this language to align with our plain language standards.

In the email you write up, it'll be important to have a collaborative tone ("thanks so much for working with us to get this language accurate and easy for Veterans to understand") and ask if they have any questions as we usually do. Include the preview link, etc. Thanks!

**Comment by RLHecht** [comment]
@lunascoop The stakeholders came back with just 2 changes we need to make before publishing:

1. Change "health care provider" throughout to "provider."
2. In the "What else do I need to do to prepare for my exam" answer, change "exams" to "examines" in the last sentence.

Let me know when these are done and I'll do a final review and publish!

**Comment by lunascoop** [comment]
@RLHecht I have made the changes and also changed other instances of "doctor" to "provider." The page is ready for review.
http://preview-prod.vfs.va.gov/preview?nodeId=914

**Comment by RLHecht** [comment]
Thanks @lunascoop ! I reviewed and published this. Moving to validate and will close once it's live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
