### ISSUE TITLE
Auth Profile: Sprint 62

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33435]
## PTO/OOO/Unavailable
- Lihan: Dec 10-23  **[8 avail]**
- Liz: Dec 3, Dec 8 1/2 day, Dec 9-13 **[3.5 avail]**
- Christina; Dec 3 **[9 avail]**
- Tressa: Dec 6  **[9 avail]**
- Erik: Dec 6-14 **[2 avail]**
- Zach: Dec 13-14 **[ 6 avail]**  - Note  - Zach power outage starting at 3 PM ET on Mon 12/6

## Sprint Objectives
- Anything unfinished from Sprint 61

<hr>

### Marci

- [x] [Marci] Scope/prioritize #30112

### Liz
- [ ] [Liz] #33007 (update VHA first if we haven't heard from VBA)

### Taylor
- [x] [FE] - Taylor - #31407 `rolled from Sprint 61`
- [x] [FE] - Taylor - #31406 `rolled from Sprint 61`
- [x] [FE] - Taylor/Zach - #33790

<hr>

## Direct Deposit/Login.gov

- [x] FE - Taylor #33062 -  `rolled from Erik Sprint 61`
  
- [x] [FE - Erik/Taylor] #33064 -  `rolled from Erik; Sprint 61`
- [ ] [FE - Erik/Taylor] #33066 -  `rolled from Erik; Sprint 61`
  - Monitoring [Pull request #19516](https://github.com/department-of-veterans-affairs/vets-website/pull/19516)- last update was waiting on new content from Cody.  Draft PR.
- [x] [Design - Liz] #33094 -  `rolled from Sprint 61`

<hr>

## Notification Preferences

- [ ] [PM - Marci - ~~Submit for 508 review - still have 4 outstanding issues~~
- [ ] [Design - Liz] #29582 - `rolled from Sprint 61 - Content work; Liz is monitoring`

<hr>

### Marci
- [X] [PM - Marci] - #33566 -  - `rolled from Sprint 61` Midpoint review ticket: #33630  

### Christina
- [x] [Design - Christina] - #32705  - `rolled from Sprint 61`
- [x]  [Design - Christina] - #32706 `rolled from Sprint 61`
- [x]  [Design - Christina] - #32731 `rolled from Sprint 61`
- [x] [Design - Christina] - #33420 `unplanned; Christina had capacity due to blockers`
- [x] [Design - Christina] - #33225 `unplanned; Christina had capacity due to blockers`

### Zach
- [x] [FE - Zach] - #31405 - `rolled from Sprint 61`
- [x] [FE - Zach] #31685 - `Adam is looking at`
- [ ] [FE - Zach] #32768 

## Unplanned 
- [x] BE - Lihan - `unplanned` - #33956
- [x] FE - Taylor -`unplanned` - #33955 
- [x] FE - Taylor - 'unplanned' - #33932

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss I included the mock test in the ticket for user testing prep.  Are you asking about an issue for actual user testing?

**Comment by Samara-Strauss** [comment]
> Are you asking about an issue for actual user testing?

Yes, there should be a ticket for actual user testing depending on what the start date is for testing. I think Christina planned to start earlier than the last day of this sprint, so we'll want to track that work.

Also, all of the tickets from last sprint that were not finished and are planned to continue in this sprint should be part of this epic. There are a lot of open tickets still in #32701, and it's unclear whether everything that should have been moved over has been moved over. For example, I don't see Christina's research tickets that carried over in this sprint, and they should be since they were not complete by the end of last sprint.

**Comment by MarciMcGuireGCIO** [comment]
I believe I moved everything over that was left -- https://github.com/department-of-veterans-affairs/va.gov-team/milestone/815

**Comment by MarciMcGuireGCIO** [comment]
User testing ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33620

**Comment by Samara-Strauss** [comment]
> I believe I moved everything over that was left 

Got it. I understand you may have changed the milestone within the ticket, but all of those tickets should be listed in this epic as well so we don't lose track of them, and not all of them are.

**Comment by MarciMcGuireGCIO** [comment]
Ok. I'll get them added.
