### ISSUE TITLE
Update Mockups for SAHG

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33433]
## Background
We need to update the mockups

## Considerations
blank page, patterns for address + drop downs, etc
- mocks: https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/eKJnozj
- Oscar availability on 12/02 09:30 – 12:00 and 12/03 11:00 – 3:00

## Tasks
- [x] update the patterns for address
- [x] adjust the header text in the confirmation box
- [x] reflect the drop down portions for some yes/no questions

## Acceptance Criteria
- [x] address patterns are addressed
- [x] header text is adjusted
- [x] drop down portion re shown in mockups
- [x] FE has been sent the mockups (or shared in a comment in this ticket)

**Comment by candy-gcio** [comment]
Updated wireframes and started change log:

- [wireframes](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/p/5C807B24-B423-4109-9BC4-7230F0E21AEB)
- [hub page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-apply-SAHG/research-design)
