### ISSUE TITLE
Form 526 Concept: Task list approach, milestone submission

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#33439]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [x] Explore how we implement a task list approach in Form 526
- [x] Explore how we can reorganize and reduce the length of Form 526. 
- [x] Explore if we can use a milestone submission approach.  

## Acceptance Criteria
- [x] Documented form improvement research and recommendations. Presentation and formal documentation.

**Comment by chrvalla** [comment]
Phase one complete. Link to research below. Research continues in Phase 2. 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/Nov-2021/Discovery%20Form%20526.pdf
