### ISSUE TITLE
Explore page load speeds related to Header V2 Implementation [Platform - PW Team]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33447]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need an optimized mobile experience so I can complete tier 1 benefit actions while on the mobile platform, which involved a quick, efficient load speeds for VA.gov mobile header.

https://user-images.githubusercontent.com/12773166/144299554-364ef5ea-2e20-4098-a7b1-494b30a826dc.mov

## Related Documentation
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/new-mobile-header/Release%20Plan%20Mobile%20Header.md)

## Description
- Need to work with Platform to determine best path for improving load speeds for the newly implemented header V2 react app.  

## Tasks
- [ ] Determine best approach for load speeds for header v2
- [ ] Start a slack thread and collaborate with VSP Platform team in finding workable solution
- [ ] Present findings to PW team 
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] Mobile Header load speeds are improved for visitors and long term solution is implemented on prod envo.

**Comment by kelsonic** [comment]
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19561 removed the lazy loading from the header v2 app but it didn't seem to improve the time to render the header v2 app at all 🤔 CC @theodur @timwright12 do either of you have any ideas how we could improve the time to render for site-wide react apps?

**Comment by kelsonic** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1638386501294500

Very long thread ^ but tldr; only way to prevent the flicker for header v2 and eventually events v2 is to not have them in react atm. Long-term VSP is working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/32785, which should reduce time to render by a lot but won't be finished until end of Q1 or even Q2 2022

**Comment by kelsonic** [comment]
Closing as there's no other action items we can do on our end here @brianalloyd
