### ISSUE TITLE
Add a one-time modal notification at the landing page for Comparison tool redesign release

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#33452]
## Issue Description

- When the CT redesign is launched, users will need to be presented with a notification that the Comparison tool is a new version. This notification should appear only once: the first time they access the new CT. Once users dismiss it by either clicking the button at the bottom or the "X" icon in the upper right corner, it will not be displayed again on that device. 

## Assumptions:
- Team will use the modal design component as recommended by platform design team
- All accessibility/508 requirements are built into the modal component.
- Wording for the modal has been approved by platform content. 
---
## Tasks
- [ ] Create modal using design component on design.va.gov/modal
- [ ] ??
- [ ] ?? 

## Acceptance Criteria
- [ ] Upon accessing the Comparison tool, a modal is displayed over the landing page notifying the user that it is a new version, using text as stated below.
- [ ] User can click the button at the bottom of the modal or the "X" icon in the upper right corner of the modal to dismiss it.
- [ ] When modal is dismissed, it will not display again on the device and browser
- [ ] When user switches to a different device/browser, modal displays again.
- [ ] Modal displays correctly on mobile devices

Example of modal:
![image (1)](https://user-images.githubusercontent.com/85580424/144299478-5fada97a-8909-447f-bcc5-0bdc1b0768c5.png)

However, the text for modal should be as follows:

**We’ve launched a new version of the GI Bill Comparison Tool**
With this new version you can:

- Search by location with a new map view
- Compare up to 3 schools side-by-side
- View your benefits with more streamlined displays

{button} Go to the GI Bill Comparison Tool

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by af-manish** [comment]
Storybook for modals: https://design.va.gov/components/modal

**Comment by af-manish** [comment]
Not needed anymore
