### ISSUE TITLE
[Design] Update Desktop Design for Outreach & Events MVP

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33457]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to easily explore and navigate the outreach and events page and require a way to filter events and identify recurring events going forward. 

## Related Documentation 
[Design Folder](

## Description
- In support of FE build, we'll need to clean up both DT and Mobile design specs to reflect current design recommendations. 

## Tasks
- [x] Update O&E MVP designs 
- [x] Validate designs for both DT and Mobile are clear to review and implement
- [x] Share with FE Devs for review
- [x] Close ticket when completed 

## Acceptance Criteria
- [x] Update O&E MVP designs and ensure they are ready for FE implementation.

**Comment by brianalloyd** [comment]
@callen2563 could you provide an update for this ticket? TIA.

**Comment by callen2563** [comment]
@brianalloyd @kelsonic Desktop designs can be seen here [sketch updates here](https://sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1).
