### ISSUE TITLE
[FE] Remove left nav on outreach-and-events/events page and subpages

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33451]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to easily explore and navigate the outreach and events page. 

## Related Screen Shots 
Remove side nav from Events Materials sub page.
![Screen Shot 2021-12-01 at 12 18 35 PM](https://user-images.githubusercontent.com/70410912/144299306-aec6b7bf-ac51-4146-9cb4-7900015e5b8f.png)

Remove the side nav from the Events sub page. 
![Screen Shot 2021-12-01 at 12 18 42 PM](https://user-images.githubusercontent.com/70410912/144299415-8af7e11c-a0d4-4329-9e2b-90380be070f4.png)

Remove side nave from Events Details Page.
![Screen Shot 2021-12-01 at 12 20 46 PM](https://user-images.githubusercontent.com/70410912/144299615-b5b8b5fa-551d-4ad7-be4d-53f52e6e2882.png)

## Description
- Remove left nav on outreach-and-events/events page and subpages to make it easier for users to navigate on both desktop and mobile.   

## Tasks
- [x] Remove side nav as indicated above from these sections 
- [x] Test and validate function is working properly with no side affects 
- [x] Close Ticket when completed 

## Acceptance Criteria
- [x] Remove left nav on outreach-and-events/events page and subpages to make it easier for users to navigate on both desktop and mobile.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/806

**Comment by kelsonic** [comment]
PR merged, will go out with daily today

**Comment by brianalloyd** [comment]
Work is completed, AC has been accomplished.  Closing ticket in support.
