### ISSUE TITLE
[Design] Remove left nav on O&E events pages subpages and Event details page 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33454]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to easily explore and navigate the outreach and events page. 

## Related Screen Shots 
Remove side nav from Events Materials sub page.
![Screen Shot 2021-12-01 at 12 18 35 PM](https://user-images.githubusercontent.com/70410912/144299306-aec6b7bf-ac51-4146-9cb4-7900015e5b8f.png)

Remove the side nav from the Events sub page. 
![Screen Shot 2021-12-01 at 12 18 42 PM](https://user-images.githubusercontent.com/70410912/144299415-8af7e11c-a0d4-4329-9e2b-90380be070f4.png)

Remove side nave from Events Details Page.
![Screen Shot 2021-12-01 at 12 20 46 PM](https://user-images.githubusercontent.com/70410912/144299615-b5b8b5fa-551d-4ad7-be4d-53f52e6e2882.png)

## Description
- Remove left nav on outreach-and-events/events page and subpages to make it easier for users to navigate on both desktop and mobile.   Update designs and share with development team for implementation. 

## Tasks
- [x] Remove side nav as indicated above from these sections 
- [x] Validate designs for both DT and Mobile are clear to review and implement
- [x] Share with FE Devs for review
- [ ] Close ticket when completed 

## Acceptance Criteria
- [x] Remove left nav on outreach-and-events/events page and subpages to make it easier for users to navigate on both desktop and mobile design versions.

**Comment by brianalloyd** [comment]
@callen2563 can you give an update on ticket for this workflow?  Thanks.

**Comment by callen2563** [comment]
@brianalloyd @kelsonic I have removed the side nav you can see the [sketch updates here](https://sketch.com/s/8ec18b80-a905-47fb-a217-5720450befa1).
