### ISSUE TITLE
[Design] FE Audit and Answer Engineering Questions - Emergency Contact (Read-only)

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#33462]
Description: 
UX reviews FE tickets, reviews staging or screenshots, and answers engineering questions.

**Tasks:**
- [x] Document what we review in Design Audit section in Sketch and any changes
- [x] Post a link in FE tickets to the Sketch section

**Acceptance Criteria:**
- [ ] Everything is reviewed and gaps are communicated with engineering
- [ ] Answering engineerings questions

**FE Audit for**
Emergency contact (Mobile): 
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/Gm5VG7w
Emergency contact (Desktop): 
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/09qbzk0

**Comment by zach-park** [comment]
FE Audit document (with UX comments) is ready now. Links are reattached to the story (above).
@acrollet @mdewey @brianseek @dcgoodwin2112 @jparker0425 @julieadair1

**Comment by jparker0425** [comment]
Reviewed items and recommendations. FE tickets being created.
