### ISSUE TITLE
Update PDF link on TSGLI benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33461]
## Issue Description
We have a new version of the Application for TSGLI benefits PDF that needs to be updated on the [TSGLI benefits detail page](https://www.va.gov/life-insurance/options-eligibility/tsgli/)

PDF: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8600_ed2021-11.pdf

This replaces the PDF in the link under the H2 How do I get these benefits?

## Tasks
- [x] Update PDF link (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that change is live (Randi)

## Acceptance Criteria
- [x] New PDF is live on the page

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

- Servicemembers’ Group Life Insurance (SGLI): http://preview-prod.vfs.va.gov/preview?nodeId=767
- Traumatic Injury Protection (TSGLI): http://preview-prod.vfs.va.gov/preview?nodeId=768

**Comment by RLHecht** [comment]
Thanks! I published these and will close once they're live.

**Comment by RLHecht** [comment]
These are live. Closing ticket.
