### ISSUE TITLE
Reduce amount of "magic strings" on FE

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33472]
## Issue Description
There are numerous areas in the Identity code space where non `const` strings are used as arguments for logic. These should be updated as much as possible to use values stored in a `constants` file.

This will reduce the likelihood of typo based bugs

---
## Tasks
- [ ] Find areas where "magic strings" are used most frequently
- [ ] Update these occurrences with constants

## Acceptance Criteria
- [ ] Constantification of as many logic based strings as possible
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
Nick: By reducing strings/logic, we reduce complexity and potential bugs.
