### ISSUE TITLE
[FE] Create a content build template for Promo Banner (wrap w/ build type doesn't equal prod)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33475]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be informed of upcoming information while browsing VA.gov. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1638212515248700)

```graphql
{
  nodeQuery(limit: 10000, offset: 0, filter: {conditions: [{ field: "type", value: ["promo_banner"] }] }) {
    entities {
      ... on NodePromoBanner {
        entityId
        title
        fieldLink {
          url {
            path
            routed
          }
          title
        }
        fieldPromoType
        fieldTargetPaths
      }
    }
  }
}
```

## Description
- We need to migrate "promo" banners content from Vets-website into CMS for content maintenance. After a mock graphql query is created, we need to create a content build template for Promo Banner migration process. 

## Tasks
- [ ] Create a content build template for Promo Banner
- [ ] Ensure change is functional and tested local/staging env.
- [ ] Coordinate release timing with CMS Team (Stretch goal - Zero down time)
- [ ] Close ticket when completed 

## Acceptance Criteria
- [ ] Content build template is built for Promo Banners and CMS coordination and timing has been established for implementation. **Do NOT deploy with out coordinating with CMS**

**Comment by kelsonic** [comment]
PR merged, will go out with daily today

**Comment by brianalloyd** [comment]
Validated, closing ticket in support.
