### ISSUE TITLE
Remove `login_old_design` flag and code

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33471]
## Issue Description
Old sign in styles can now be removed completely

---
## Tasks
- [ ] Remove `login_old_design` from flipper & documentation
- [ ] Remove `login_old_design` FE selectors
- [ ] Remove old design components and clean up/refactor authentication components

## Acceptance Criteria
- [x] Old sign in experience is stripped out of vets-website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
