### ISSUE TITLE
Create a Mock GraphQL query for Promo Banner

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33473]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be informed of upcoming information while browsing VA.gov. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1638212515248700)

## Description
- We need to migrate "promo" banners content from Vets-website into CMS for content maintenance. Creating a mock graphql query for that initiative will be the first step in support of the migration process. 

## Tasks
- [ ] Create a mock graphql query for Promo Banners
- [ ] Ensure change is functional and tested local/staging env.
- [ ] Review any connected tickets and collaborate with CMS in support
- [ ] Close ticket when completed 

## Acceptance Criteria
- [ ] Create a mock graphql query for Promo Banner Migration.

**Comment by kelsonic** [comment]
```graphql
{
  nodeQuery(limit: 10000, offset: 0, filter: {conditions: [{ field: "type", value: ["promo_banner"] }] }) {
    entities {
      ... on NodePromoBanner {
        entityId
        title
        fieldLink {
          url {
            path
            routed
          }
          title
        }
        fieldPromoType
        fieldTargetPaths
      }
    }
  }
}
```
