### ISSUE TITLE
Unit test authentication button clicks

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33470]
## Issue Description
Currently, we unit test that the `login()` function works correctly when passed proper params. We should take this a step further and mount the SignInButtons in order to unit test clicking the buttons properly provides params to `login()` function

---
## Tasks
- [ ] Create unit tests that mount and simulate clicks on SignInButtons
- [ ] Verify that params being passed to `login()` work correctly

## Acceptance Criteria
- [ ] Unit tests pass/fail appropriately
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
