### ISSUE TITLE
[FE] Remove Promo Banner from Vets Website

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33476]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be informed of upcoming information while browsing VA.gov. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1638212515248700)

## Description
- We need to migrate "promo" banners content from Vets-website into CMS for content maintenance. This ticket should be implemented after we've created a content build template for Promo Banner and discussed implementation timeline with CMS for this migration effort. 

## Tasks
- [ ] Remove Promo Banner from Vets Website
- [ ] Ensure change is functional and tested local/staging env.
- [ ] Coordinate release timing with CMS Team (Stretch goal - Zero down time)
- [ ] Close ticket when completed 

## Acceptance Criteria
- [ ] Remove promo banners from Vets Website  **This should be done post implementation of content build template**

**Comment by kelsonic** [comment]
This is on production! 🎉
