### ISSUE TITLE
Convert Keycloak test install to visible install

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#33478]
Until now, there was not a persistent configuration for keycloak, what we has was a test instance. To use Keycloak for access management we need to convert keycloak install to be persistent.

**Context: MiTM / TIC / VAEC**
If user is in VA network, and accesses github for example it returns a certificate, the VA replaces that certificate at their firewall and the certificate you expect is not the one you get. 
Tools in the network will give you an error or won't make the connection because the certificate was unexpected and cannot be verified. 

To fix this, the container needs to trust the VA certificate. So we need to build a custom Keycloak container. (other options have been tested, this was determined to be the best path forward)

**Task is Done When:**

- [ ] create a github repo for docker file
- [ ] automation for certificate
- [ ] create ECR (elastic container registry) Repository 
- [ ] Create github service account
- [ ] Add AWS policy to service account to allow it to push to ECR
- [ ] Create automation to build and push container for keycloak to repo
