### ISSUE TITLE
Design intent - Authenticated Experience, My VA Enhancements - Payment Information

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33477]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [ ] Yes
- [ ] No

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md)
  
- [x] [Whiteboard sketch or other lo-fi prototypes or wireframes](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=u5ad49c107baa41137f271007)
- [ ] User flow
- [x] Any other artifacts you have so far - [Discovery & Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/discovery-and-research)

### Required
- Product Manager: Heather Justice @hdjustice 
- OCTO-DE Product lead: Samara Strauss @Samara-Strauss 
- OCTO-DE Design lead: Ryan Thurlwell

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@hdjustice this is scheduled for 12/13/21 at 3:30

**Comment by hdjustice** [comment]
Thanks @allison0034 !

**Comment by jimuhh** [comment]
Thanks @hdjustice and @tressaellen. It looks like you have the IA concerns well-integrated into your design and research plans, so I have no other feedback. Great work!

**Comment by mnorthuis** [comment]
@hdjustice @tressaellen When you are ready, you can [open a Sitewide Content and IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).  Some things I'd love to continue to talk about:
- Labeling for the section as multiple teams continue to figure out this idea of "financial things being together"
- Placement of travel reimbursement and copays
- How/if this payment section evolves when Education section is created
