### ISSUE TITLE
526 unsuccessful claims in CST - Timeline for keeping claims

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#33488]
## Issue Description
We've created a design for the 526 errored claims in CST:

https://www.sketch.com/s/1cce0882-8ade-49cc-80e8-74cb3ea6131f

However, we still have some questions that need answering as we move forward with this approach:

1. How long do we keep these unsuccessful claims in the CST? We cannot associate the failed submission with the mailed in version, so it can't stay forever.

2. How do we convey in the email that the unsuccessful claims will expire?

3. As we fast approach this option, should we explore what it looks like outside of the CST?

---
## Tasks
- [x] Determine how long the unsuccessful claim should show in CST
- [x] Rewrite email to include the expiration of the claim in CST
- [x] Document exploration of alternate options

## Acceptance Criteria
- [x] All above tasks have been documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Here is the proposed content for the updated email:

Hello [user],

Due to a technical error, we couldn’t process your form. This can occur after the form has been submitted on the VA.gov website. At this time, we advise that you submit your claim via U.S. mail.

We've saved the data you previously entered into your 526 disability form. It's available for you to download as a PDF. To access it, please log into your account on VA.gov and navigate to the Claims and Appeals Status Tool. Your claim will be listed there. Select it and click the link to download your saved form. **Your errored claim details will be available to you for 60 days.**

Send in your completed form and any evidence in support of your claim to:

Department of Veterans Affairs 
Evidence Intake Center 
PO Box 4444 
Janesville, WI 53547-4444

If you're in need of assistance, please contact our call center at 800-827-1000. We’re available Monday through Friday, 8 a.m. to 5 p.m. EST. 

We apologize for the inconvenience.

**Comment by kevinstachura** [comment]
Here is the user journey that we have proposed: https://app.mural.co/t/vsa8243/m/vsa8243/1638802878137/9893dbd47184397f34eb3feb37dc0a6f6c1aba5d?sender=kstachura1551

Here is the design:

https://www.sketch.com/s/1cce0882-8ade-49cc-80e8-74cb3ea6131f
