### ISSUE TITLE
[VBA Debt Portal] Bug - The 'Your debt letters' table isn't the full column width

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#33498]
## Issue Description
The 'Your debt letters' table on the ['Download debt letters'](https://staging.va.gov/manage-va-debt/your-debt/debt-letters) screen's width is compressed. To increase visual legibility and create consistency with the components in the tool, the table's width should fit in the full column. 

**How to recreate the bug**
1. Sign into [the Debt Portal](https://staging.va.gov/manage-va-debt) with test user 228 
2. Navigate to the 'Your debt letters' table 

**Screenshot of the bug:**
![Screen Shot 2021-12-02 at 10.47.20 AM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/239baf92-8670-42bc-bd98-b798404881ca)

**Solution:**
- The table's width should match the column width (should be the same width as the alert in the above screenshot)

---
## Tasks
- [ ] The table's width has been updated to match the column width 

## Acceptance Criteria
- [ ] The component has been updated in staging
- [ ] Ping Riley to double-check staging's UI

**Comment by craigwheeler** [comment]
The current custom table should be replaced with the design system component for [Table](https://design.va.gov/components/tables)
