### ISSUE TITLE
Final Disallows for VAMC rollouts

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33496]
### Issue description
As a VAMC system administrator, I need the disallow of my site to be removed from Robot.txt file, so that the browsers and crawlers can see the site prior to redirect from Web Operations.

## Goal
Remove disallow so crawlers and browsers will have access directly to site and when redirect is engaged

## Task

Per Lisa Trombley, the following have already gone live and can be removed 

- [x] /birmingham-health-care/ 
- [x] /caribbean-health-care/ 
- [x] /central-alabama-health-care/ 
- [x] /clarksburg-health-care/
- [x] /puget-sound-health-care/ 
- [x]  /san-francisco-health-care/ 

The following are going live this week and can be removed
- [x] /boston-health-care/ 
- [x] /indiana-health-care/ 
- [x] /wallawalla-health-care/  (Note: Confirmed name is Walla Walla)

## Acceptance Criteria
Only the system names above remain in the robot.txt file
