### ISSUE TITLE
[FE] Add  'Header V2' for product description event parameters (Analytics)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33508]
## User Story
- As a product team I want to be able to track users behaviors related to new product releases. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C021ZGX7TUP/p1638462269000100)

## Description
-  We need to that to create our segments.  The good news is we should be able to retroactively segment these users (as long as we keep the date range of the experiment in mind). The product-description event parameter is fed into the event action and is what we can use to differentiate. By all means - make that value whatever is most useful to your team.

## Tasks
- [x] Add 'Header V2' for product description event parameters 
- [x] collaborate with insights team to ensure proper tracking is implemented 
- [x] Close ticket when completed 

## Acceptance Criteria
- [x]  'Header V2' for product description event parameters is in place for insights team to create segments for GA tracking perimeters per PW team request.

**Comment by kelsonic** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19574

**Comment by kelsonic** [comment]
PR merged, will go out with daily today

**Comment by brianalloyd** [comment]
Work completed, closing ticket in support.
