### ISSUE TITLE
(Discovery) Platform website — Audit testing tool content

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33511]
## Problem Statement 

In 2021 Q2, the Service Design and Content/IA teams took a snapshot of customers' [engineering top tasks](https://docs.google.com/spreadsheets/d/1FFm6C-R6-CVEO6P4Q738zbSfn1nMDRiJ/edit#gid=1056045499).  Through that research, we learned that customers frequently referenced information regarding Platform testing tools.  However, because of our democratized publishing workflow, all information - incl. testing tools info - delivers an inconsistent reading experience.

_HMW transform testing tool content to be more actionable, less duplicative and error-free, and have greater consistency?_

## Hypothesis or Bet
If we conduct an audit of the testing tool content, we can then (a) identify how and where to transform the testing tool content, in order to (b) in 2022 Q1, transform the testing tool content to afford a better reading experience.

## We will know we're done with this discovery when... ("Definition of Done")
* Content audit goals have been identified
* Audit has been conducted
* Possible remediations have been
  * Listed and published
  * Prioritized for end-of-Q1 completion
  * Shared with Testing tools, Rachael Roueche, Andrea Hewitt, and Naomi

## Known Blockers/Dependencies 
* Might need to consult with SMEs on the Testing tools team

## Projected Launch Date
End of 2021 Q4

## Launch Checklist

<details>

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my VSP initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given VSP initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

</details>

## Required Artifacts
<details>

### Documentation
* **`PRODUCT_NAME`**: Platform website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)
* **Product Outline**:  Platform website [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/platform-website/platform-website-product-outline.md)
* **README & User guide**: [Contributing to the Platform website guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)

### Testing

n/a - this is a discovery initiative

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
  * n/a - this is a discovery initiative
* **Release plan**: _link to Release Plan ticket_
</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
