### ISSUE TITLE
[MCP] Updates to breadcrumbs / IA structure

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#33523]
## Issue Description
Mikki left us some [comments in a previous ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32652#issuecomment-977167630) that we need to address for MCP's IA. We need to adjust our documentation for intended IA, update prototypes, and ensure FE is aware of the change or tickets are made.

---
## Tasks
- [x] Make the changes Mikki outlined in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32652)
- [x] Ensure FE is aware of the change or tickets are made

## Acceptance Criteria
- [x] Changes reflected in UXPin and linked to this ticket

**Comment by rileyorr** [comment]
All recommended changes have been incorporated into our prototype! I've posted the changes in Mikki's IA request ticket. I also noticed that Danielle's latest draft of MCP's content page has an H1 that differs from our design, so I'll update that once the content page is finalized. 

Added [a ticket for frontend implementation ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/33578)
