### ISSUE TITLE
Input Spanish translations on COVID pages from volunteer translation team

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33521]
## Issue Description
We recently got back translations from our volunteer translation team for several COVID pages that we sent to them in November. There were no changes needed for Tagalog pages but there are a few updates to the Spanish pages. 

Translation doc: [https://app.zenhub.com/files/133843125/93d31b29-2e5b-4fcd-a200-efb199847661/download](https://app.zenhub.com/files/133843125/93d31b29-2e5b-4fcd-a200-efb199847661/download)

## Tasks
- [x] Update pages with translated copy (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Changes are on the live site

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

- Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
I published all these pages. Moving to validate.

**Comment by RLHecht** [comment]
Changes live. Closing ticket.
