### ISSUE TITLE
Define problem statement for improved Collaboration Cycle tracking

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33542]
## Issue Description
The current tools that Collaboration Cycle uses for tracking support of VFS teams and products include github and Google Sheets in the form of our Platform Collaboration Point Tracker. 

---
## Tasks
- [ ] Schedule team workshop 

## Acceptance Criteria
- [ ] We have mapped the current tracking (Service Blueprint?) 
- [ ] We have defined the top problems with the current tracking tools
- [ ] We have defined the desirable characteristics of the current tracking tools
- [ ] We have defined our goals and objectives (north star) for a new tracking tool
- [ ] We have identified what features we'd like our new tracking tool to posses
- [ ] We have identified several "low hanging fruit" ideas for improving our tracking
- [ ] We have defined potentials metrics and/or KPIs for measuring success of the new tool

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
