### ISSUE TITLE
[FE] - Update Need help section (footer component)

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#33555]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/eK98P42)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
-[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1638481313115000)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

See Slack thread for needed changes to footer component and intro page.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update footer component to take a custom body
- [ ] Update intro page to use custom footer body and any other changes needed from new sketch mock
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Screenshot for UX review ![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/aa22e855-6ca0-4129-8b29-618e0b45d929)
@ytsaoca

**Comment by ytsaoca** [comment]
<img width="573" alt="Screen Shot 2021-12-06 at 12 10 16 PM" src="https://user-images.githubusercontent.com/90633685/144890733-866359d5-e139-46b5-857e-1f5edec778e9.png">
@brianseek  Please use lowercase here. Thanks

**Comment by brianseek** [comment]
@ytsaoca Updated screenshots:
![localhost_3001_health-care_appointment-pre-check-in_introduction (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/0a696fb4-1f3e-4e1a-9ea1-608c1a64fca0)

**Comment by ytsaoca** [comment]
Looks good! @brianseek
