### ISSUE TITLE
Sync 'Your COE' pages with latest designs

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#33554]
## Background
Based on the latest updates from the Design side of the house, we need to update the 'Your COE' pages with what they have.

## Mockups
[available](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139512694/specification/sitemap)
[denied](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140537807/specification/sitemap)
[eligible](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139511607/specification/sitemap)
[ineligible](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140811192/specification/sitemap)
[pending](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139575305/specification/sitemap)

## Tasks
- [ ] Review the changelog and address items
- [ ] Update copy to match mockups

## Acceptance Criteria
- [ ] The 'Your COE' pages in staging is as updated as possible per the design files
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
last ticket in this area will most likely be this one: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28009
