### ISSUE TITLE
[MCP] Resolved copay balance detail page

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33558]
## Issue Description
update balance detail page to reflect zero balance details refer to [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141466617/simulate/sitemap?mode=i)

## Resolved copay balance detail page

- [x] Facility name isn’t displaying
- [x] Date isn’t displaying ‘Updated on Invalid date’ 
- [x] The information alert ‘You don’t need to make aa payment at this time’ isn’t displaying 
- [x] PDF statement has an invalid date 
- [x] PDF statement cannot be downloaded
- [x] Option 4: facility address isn’t displaying 
- [x] Questions about your treatment or your charges - facility contact information isn’t populating 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
account number to be addressed on BE [[MCP] 33565: Derive StatementId for FE](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/33565)
