### ISSUE TITLE
[MCP] Overview page edits

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33559]
## Issue Description
edits to the copay overview page

- [ ] Heads up: we’re currently chatting with Mikki about breadcrumb adjustments so stay tuned!
- [ ] Update subhead text to “Check the balance of VA health care and prescription charges from each of your facilities. Find out how to make payments or request financial help.”
- [ ] Should also be using the intro text styling - refer to [the debt portal](https://staging.va.gov/manage-va-debt/) for styling 
- [ ] Contact information for your VA health care facilities: The second facility doesn’t have a contact number

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
