### ISSUE TITLE
Bad URL for default og:image meta tag

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#33552]
@msbtterswrth commented on [Thu Dec 02 2021](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7141)

## Describe the defect
It looks like frontend is pulling a bad url for og:image meta tag `<meta property="og:image" content="https://www.va.govhttps://www.va.gov/img/design/logo/va-og-image.png">` 

## To Reproduce
1. Go to https://www.va.gov/disability/how-to-file-claim/
2. View source in your browser tools 
3. Find the og:image meta tag 
4. See `<meta property="og:image" content="https://www.va.govhttps://www.va.gov/img/design/logo/va-og-image.png">`  instead of `<meta property="og:image" content="https://www.va.gov/img/design/logo/va-og-image.png">` 
5. Confirm through a testing tool (https://www.opengraph.xyz/url/https%3A%2F%2Fwww.va.gov%2Fdisability%2Fhow-to-file-claim%2F/) the image is not loading.

## Expected behavior
A default image should load in the preview cards (twitter/facebook/slack)

## Screenshots 
![image.png](https://images.zenhubusercontent.com/61671a60c72e6d0337fd8bcd/c5a77822-8173-4ed2-98c8-88252c6dbc75)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

---

@swirtSJW commented on [Thu Dec 02 2021](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7141#issuecomment-985038109)

CMS data is correct.   Looks like some bad string concat on the frontend
![image](https://user-images.githubusercontent.com/5752113/144510483-aec4cb4b-0255-46aa-9993-5032f3ee6d50.png)

**Comment by swirtSJW** [comment]
@brianalloyd   Lynn discovered this while auditing metatags in the CMS.   Turns out its a FE issue.

**Comment by brianalloyd** [comment]
Thanks @swirtSJW PW team will scrub into the issue.  Thanks.

**Comment by brianalloyd** [comment]
@tmac9494 can you provide a status update on this ticket.  Let me know if any blockers to closing out this sprint, thanks.

**Comment by brianalloyd** [comment]
@tmac9494 what's the current status of this ticket?

**Comment by tmac9494** [comment]
pushing out today

**Comment by tmac9494** [comment]
@swirtSJW @brianalloyd before pushing I noticed that the url seems to be fixed in prod and staging. When I reverted to and updated the master branch the url was correct in my local build as well. Can someone confirm if this issue was resolved already
![og-image](https://user-images.githubusercontent.com/17556493/151414944-88ef60bd-a8fe-4be6-9455-ee10c0255cc0.PNG)
?

**Comment by brianalloyd** [comment]
Looks like this has been resolved, closing in support.

**Comment by kevwalsh** [comment]
> @swirtSJW @brianalloyd before pushing I noticed that the url seems to be fixed in prod and staging. When I reverted to and updated the master branch the url was correct in my local build as well. Can someone confirm if this issue was resolved already ![og-image](https://user-images.githubusercontent.com/17556493/151414944-88ef60bd-a8fe-4be6-9455-ee10c0255cc0.PNG) ?

Looks like this is the homepage. 

The defect is on a number of other templates, like the one used for the link in the issue description.
