### ISSUE TITLE
[FE] Building new promo-banners React component in vets-website

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33563]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be informed of upcoming information while browsing VA.gov. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1638544455339000?thread_ts=1638543792.338900&cid=C52CL1PKQ)

## Description
- We need to migrate "promo" banners content from Vets-website into CMS for content maintenance. In support of this initiative we'll need to build out a new promo-banner react component in vets-website.  **NOTE** don't merge until CMS is able to merge in PromoBanners to production environment.

## Tasks
- [ ] Build a new promo-banner react component in vets-website 
- [ ] Ensure change is functional and tested local/staging env.
- [ ] Coordinate release timing with CMS Team (**NOTE** don't merge until CMS is able to merge in PromoBanners to production environment.)
- [ ] Close ticket when completed 

## Acceptance Criteria
- [ ] New promo-banners react component is available on vets-website in support of content migration to CMS. ****NOTE** don't merge until CMS is able to merge in PromoBanners to production environment.**

```graphql
{
  "data": {
    "nodeQuery": {
      "entities": [
        {
          "entityId": "40046",
          "title": "Help for Afghanistan Veterans and families",
          "fieldLink": {
            "url": {
              "path": "https://blogs.va.gov/VAntage/help-for-afghanistan-veterans-families/",
              "routed": false
            },
            "title": ""
          },
          "fieldPromoType": "announcements",
          "fieldTargetPaths": [
            "*"
          ]
        }
      ]
    }
  }
}
```

**Comment by kelsonic** [comment]
This is on production 🎉
