### ISSUE TITLE
[MCP] Overview page edits

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33560]
## Issue Description
edits to the copay overview page

~~Heads up: we’re currently chatting with Mikki about breadcrumb adjustments so stay tuned!~~
- [x] Update subhead text “Check the balance of VA health care and prescription charges from each of your facilities. Find out how to make payments or request financial help.”
- [x] Should also be using the intro text styling - refer to [the debt portal](https://staging.va.gov/manage-va-debt/) for styling 
~~Contact information for your VA health care facilities: The second facility doesn’t have a contact number~~

---
## Tasks
- [x]  all points in the bulleted list should be addressed

## Acceptance Criteria
- [x] all values on the overview page should render correctly according to the outlined list
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LinnJS** [comment]
Will breakout breadcrumbs into another ticket to keep this ticket internal to our team.

**Comment by denisecoveyduc** [comment]
This is 2/3 done will roll over into Sprint 63 for completion

**Comment by LinnJS** [comment]
Removing facility phone number bug from ticket so it does not hold up other changes. This ticket is a little complexed since it deals with global utilities.


[Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/34562)

**Comment by LinnJS** [comment]
Work is merged
