### ISSUE TITLE
Create schema for SAHG

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#33574]
## Background
Take the schema created by the generator and add it to `vets-json-schema` repo.

## Considerations
This must be done before a PR for `vets-website` can be merged

## Tasks
- [ ] Create `26-4555/schema.js` file in `vets-json-schema`
- [ ] Migrate newly created schema from `vets-website` to `vets-json-schema`
- [ ] Bump minor version of `vets-json-schema` in `package.json`

## Acceptance Criteria
- [ ] Schema has been added to `vets-json-schema`
