### ISSUE TITLE
[MCP] Page H1 and breadcrumb adjustments 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#33578]
## Issue Description
Mikki left us some comments in [a previous ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32652) that we need to address for MCP's IA. 

**The changes:**
- Remove 'your' from all of the H1's and breadcrumbs
- Remove the location from the final H1, and put it in a subtitle instead)

**Example:**

We'd go from:
Home > Manage your VA copay bills > Your current copay balances > Your copay bill for James A. Haley Veterans' Hospital > Your June 3 statement for James A. Haley Veterans' Hospital

To the shortened version:
Home > Manage your VA copay bills > Current copay balances > Copay bill for James A. Haley Veterans' Hospital > June 3 Statement

All changes can be referenced in [the tool's UXPin prototype](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141834693/simulate/sitemap?mode=i) 

---
## Tasks
- [ ] Remove 'your' from all of the H1's and breadcrumbs
- [ ] Remove the location from the final H1, and put it in a subtitle instead)

## Acceptance Criteria
- [ ] The H1's and breadcrumbs have been updated and align with the provided UXPin prototype
