### ISSUE TITLE
Letters Accessibility Issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#33575]
## Issue Description
Support request from Mobile App team related to [this ticket. ](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1584)
Recorded example: https://dsva.slack.com/files/U02EZS279D1/F02PA2CQXSA/1584_ios.mp4

---
## Tasks
- [x] Research issue and determine if this is something our team can address. Communicate results to Meko Hong, Mobile App PM

## Acceptance Criteria
- [ ] Determination made, additional tickets created if necessary. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alsleaders** [comment]
After looking into this I can confirm that a screen reader is not reading the bulleted list at the bottom of downloaded letters as a bulleted list.  After researching and discussing with my team, I've found that this letter is generated by an upstream service, and I am not able to fix this display problem.
