### ISSUE TITLE
VAOS Stakeholder Epic

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#33573]
# Stakeholder input
## High Level User Need / Problem / Opportunity
As a Veteran, I need an approved referral or consult so I can schedule the respective appointment.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## Outcomes / how will we define success
_Measurable benefit in addressing the request / problem / opportunity_
_What outcome(s) do we want to see?_ 
A Veteran understands the status of their referral or consult and can schedule the appointment.

## Supporting data we should consider (feedback, analytics)
_Add any supporting qualitative or quantitative data to support this need/opportunity_

## Stakeholder AC Checklist:
- [ ] Does this ask make it easier for a Veteran to schedule an appointment regardless of which electronic health record their facility or provider uses? 
- [ ] Does this ask make it easier for a Veteran to access care when and where they need it? (community care, telehealth) 
- [ ] Is this ask directly contributing to scheduling an appointment? 
- Maybe. We don't want Veterans to think they can schedule their referral or consult appointment online only to be told to call the facility.
- [ ] Does this feature solve a current and persistent problem for the user? 
- [ ] Does this feature have downstream impacts on schedulers & providers, where fixing it delivers a better user experience to Veterans, without exposing the guts of the system to them? 
- [ ] What is the urgency and why? 
- [ ] Who wants this feature and why?
- Adding to backlog at request of Lauren Alexanderson. TBD stakeholders involved in discussion.

---
# Next iteration of Epic after initial Stakeholder input:
## Create & link to Product Outline (if applicable)
- _You can find the outline template [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
- If no discovery needed, break epic into corresponding stories and tasks
```

## How to configure this issue
- [ ] **Labeled with `roadmapVAOSR` and `vaos`**
- [ ] **Add Epic to VAOS-R Roadmap Project in Github - must do this in GH, not Zenhub**
