### ISSUE TITLE
[BE] Bug: Error during Pre Check-in when refreshing the appointments page or navigating back

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#33583]
## Description
During pre check-in scenario, if the user refreshes the appointments page or navigates back to the screen, an error is shown:

![image.png](https://images.zenhubusercontent.com/6144cadc6adfc5af245df200/dc10ad6f-1be4-436b-ab94-f9792cf076eb)

This is happening because we're reusing the existing `check_in_data` method in Lorota service object, which calls CHIP to refresh appointments if the user has previously seen the appointments. For pre check-in, we're not sure how "refresh appointments" should behave, or how CHIP handles refreshing appointments for pre check-in.

Currently, we should not attempt to refresh the appointments for pre check-in scenario.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [x] Update the code, specs to fix the issue
- [x] test locally
- [x] integration test in staging

## Acceptance Criteria
- [ ] Deployed and tested on staging.
