### ISSUE TITLE
Document BGS Endpoints for Submit 686/674 Form(s)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3359]
## Story
As an eBenefits Team member, I want to be able to define what endpoints are being used within the Modify 686 portion so I can send them to the frontend so we can connect them.

## Considerations
- There are two endpoints: `View dependents` and `Update dependents`, but here we will focus on the `Update dependents`
  - **Check source code in Rational for current implementation and see what BGS endpoints are being called**  

~[Link to rainbows doc](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Declare%20Dependent%20686/Discovery/bgs-sample-requests/Benefits%20Gateway%20Services%20(BGS)%20Web%20Services.doc)~
- Discuss with other engineers about documentation

## Tasks
- [x] Identify the service or stack (or streams) that may house the endpoints for updating dependents
- [x] Document those endpoints and discuss with other team members

## Acceptance Criteria
- [x] Document the endpoints in GitHub and share with team

## Note
~~Following up with ESCP for getting into BGS~~ 
- Checking with current source code to see how it was implemented, per BGS.
- Once the new endpoint is determined, a placeholder API might not be necessary.

**Comment by kathleencrawford** [comment]
Still a WIP, but the documentation for the BGS calls can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-evss-submission-steps.md
