### ISSUE TITLE
KmsEncryptionVerification job

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#33617]
## Issue Description
Since moving to KMS (from Lockbox) as our key store for vets-api encrypted attributes, we need a way to verify that records have been re-encrypted properly with the kms key. Initial runs of the job have thrown various errors, [see PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/8571) so this ticket is needed for tracking purposes, since this work is taking more effort than originally thought. 

### Background 
We were made aware of some decryption issues from a vfs team member referencing two `AppealsApi::HigherLevelReview` records. These records were still encrypted via Lockbox and were not rotated properly during the kms rotation. The records had an `encrypted_kms_key` attribute, but were throwing errors when being decrypted. Our theory is that the job to rotate may have been killed/restarted after the deploy and the records were in the middle of being rotated, causing incomplete rotation. After reverting the [PR to remove previous_version lockbox defaults ](https://github.com/department-of-veterans-affairs/vets-api/pull/8499), the records decrypted via Lockbox properly and further recovery efforts were not needed. 

---
## Tasks
- [ ] Run jobs via Sidekiq perform_async (in batches, split evenly)
- [ ] Monitor jobs for error
- [ ] If errors, investigate corrupted records
- [ ] Once investigation completes, remove the lockbox previous_key and defaults 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Tables/models were split up to be relatively equal (in terms of total records) across the running jobs in [this spreadsheet](https://docs.google.com/spreadsheets/d/16HQ91dEWrNr7eIHBaJ1znI0ICCDT_-Crhn7_NCpQ-ng/edit#gid=2090441295).

SupportingEvidenceAttachment and CovidVaccine::V0::RegistrationSubmission have already successfully completed. SavedClaim::DisabilityCompensation::Form526AllClaim is in progress.

**Comment by LindseySaari** [comment]
Monday update: Running the jobs as I can in between other tasks. `InProgressForm` and  `Form526Submission` have also passed. The following tables/models are in progress:

```
job_5_models = [
  'SavedClaim::CaregiversAssistanceClaim',
  'SavedClaim::Ask',
  'VIC::SupportingDocumentationAttachment',
  'VIC::ProfilePhotoAttachment',
  'AsyncTransaction::Vet360::PermissionTransaction',
  'AsyncTransaction::VAProfile::PermissionTransaction',
  'ClaimsApi::SupportingDocument',
  'AppealsApi::SupplementalClaim',
  'DecisionReviewEvidenceAttachment',
  'HealthQuest::QuestionnaireResponse',
  'SavedClaim::DependencyVerificationClaim',
  'SavedClaim::EducationBenefits::VA0993',
  'AppealsApi::NoticeOfDisagreement',
  'Form1010cg::Attachment',
  'SavedClaim::EducationBenefits::VA1990n',
  'SavedClaim::EducationCareerCounselingClaim',
  'AsyncTransaction::Vet360::AddressTransaction',
  'AsyncTransaction::Vet360::EmailTransaction'
]

**Comment by LindseySaari** [comment]
There were some issues surrounding the spool file job and claims that have already been processed. Thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1639762159212100). It's believed that by updating the `verified_decryptable_at` field it may have marked the saved claim for reprocesseing., We most need to take a different approach to verify the decryption rather than saving the `verified_decryptable_at` field on the saved_claim records.
