### ISSUE TITLE
STEM Standalone - SPIKE: Turn off Automated Decision

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#33621]
## Issue Description
As a developer I need to determine what the effort would be to turn off the Automated Decision process for the STEM form (22-10203) on a temporary basis so that users are not incorrectly receiving denial emails. Once the issue has been fixed in the form, the Automatic Decision functionality would be turned back on. 

Information on STEM form automated decision can be found in GitHub here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem/stem-standalone-10203/automated-decision

---
## Tasks
- [ ] Determine what needs to be done to turn functionality off temporarily.
- [ ] Determine how long that would take to complete.

## Acceptance Criteria
- [ ] All tasks above are complete 
- [ ] Details are submitted to team leads. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AdamFreemer** [comment]
I dug in a bit, started on the vets-website form and followed down to the vets-api backend and hit a point where it's calling an external service, where the actual determination seems to be happening.

```
def request_decision(claim_id)
  post 'vbaClaimStatusService/set5103Waiver', {
    claimId: claim_id,
    systemName: SYSTEM_NAME
  }.to_json
end
```

https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/products/claim-appeal-status/claim-status-api/discovery/technical-discovery.md#get-claim-detail

Then there's a denial email `(StemApplicantDenialMailerPreview)` sent from the vets-api app depending on the status returned from that external service on an automated recurring job:.

```
EducationForm::Create10203ApplicantDecisionLetters:
cron: "45 4 * * MON-FRI America/New_York"
description: "Send 10203 applicant decision letters to applicants"
```

If the goal is to just stop the denial emails, I think we can just shut them off directly by disabling the mailer (which will stop ALL denial emails), without getting too deep into disrupting the entire submit process. I would throw maybe a 3 at this even though the code change might be small, testing and confirming everything would add to complexity.

If the goal is to actually stop a denial decision from occurring, that would be more complicated as the determination is not happening in the vets-api, but in this external service mentioned above:

http://vaausessapp800.aac.va.gov
which I'm not sure whom has ownership.

**Comment by mrblanco1** [comment]
Gina to try find documentation on how this functionality used to work before the automated process.

**Comment by mrblanco1** [comment]
BAH provided feedback with links to code related to this functionality.

**Comment by AdamFreemer** [comment]
Based on the response from Booz Allen Hamilton, it seems I misunderstood the external EVSS system as the automated process that resides in the vets-api codebase:

```
    def process_submission(submission, user_has_poa)
      status = if more_than_six_months?(submission.education_stem_automated_decision&.remaining_entitlement)
                 EducationStemAutomatedDecision::DENIED
               else
                 EducationStemAutomatedDecision::PROCESSED
               end
      update_automated_decision(submission, status, user_has_poa)
    end
```
https://github.com/department-of-veterans-affairs/vets-api/blob/420e9e864f8287dcf771788d412f13898c41662f/app/workers/education_form/process10203_submissions.rb#L153

Code could be temporarily changed to not set claims to a DENIED state in this file with what appears to be a relatively small level of effort, beyond updating specs that would have to be updated with this code change. Depending on the extensiveness of the spec changes, I'd give this a level of effort between a 3 and 5.

**Comment by af-manish** [comment]
Spike completed, confirmed we can turn this off.
