### ISSUE TITLE
[FE] Auth Profile: Login.gov - Replace the FAQ for LOA1 users with new link

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33624]
## Background
Login.gov is being added as an acceptable credential to VA.gov. There is a non-verified level for login.gov in addition to the verified level. For all LOA1 users, the FAQ page shown below needs to be changed to instead be a link to the verification [Resources and Support page](https://staging.va.gov/resources/verifying-your-identity-on-vagov/).

![image](https://user-images.githubusercontent.com/73354907/144893715-9b8cb423-1b58-4edf-91f6-3d851376c847.png)

## Tasks
- [x]  Replace the `how will VA verify my identity` FAQ that appears for LOA1 users (shown in the issue description) with the link as shown in this screenshot

![image](https://user-images.githubusercontent.com/73354907/144894139-fe529999-f480-405c-b145-aa64eecc0593.png)

## Acceptance Criteria
- [x] FAQ link described above is replaced with a link to the Resources and Support page described above.
- [x] Update is tested on Staging

**Comment by tmitchellgcio** [comment]
A few questions I have on this @andaleliz. The first screenshot and the second are very different, but the task seems to point only to the link. The alert at the top is currently a warning, not a success message like the second screenshot. Am I making that adjustment? Also the Sign-In Email address never shows all 3 links. It seems it checks the sign in service and shows only the one link from the sign in service. Is this changing and if it is, is that within this ticket?

**Comment by andaleliz** [comment]
Hi @tmitchellgcio - this task is only for removing the FAQ and replacing it with a link.

>The alert at the top is currently a warning, not a success message like the second screenshot. Am I making that adjustment? 

I haven't made any changes for the alert that I can recall so I'm not sure about that. That is definitely not part of this specific ticket.

>Also the Sign-In Email address never shows all 3 links. It seems it checks the sign in service and shows only the one link from the sign in service. Is this changing and if it is, is that within this ticket?

That is the expected behavior of the sign-in email address and that is not changing with this ticket.  There are some improvements that need to be made to that but it's a separate thing from this issue.

**Comment by tmitchellgcio** [comment]
Ok just wanted to be sure as the two screenshots seemed to be very different. Thanks for clarifying

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio Just updating this to confirm that this looks good!  This should be good to go.

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio but I am not sure on the timing for actually promoting to Prod.  Do you know if this is one that can go in before Login.gov goes live, or does it need to wait? Thx!

**Comment by Samara-Strauss** [comment]
Verified on staging! This looks good to me!

![image](https://user-images.githubusercontent.com/34068740/145605383-0b715554-7cb0-401a-af4a-74c65169d0c6.png)

**Comment by Samara-Strauss** [comment]
Given that this update actually ended up not being login.gov specific, this can go to prod any time.

**Comment by MarciMcGuireGCIO** [comment]
@tmitchellgcio - this can be deployed if you have not already begun that process.
