### ISSUE TITLE
[Design] Personal Info Revision - User testing

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33620]
## Description 
Conduct Personal Information Revision user testing with Veterans

## Tasks 
- [ ] Download final participant list from Perigean
- [ ] Print conversation guide
- [ ] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [ ] Conduct scheduled research sessions
- [ ] Debrief research sessions w/team
- [ ] Post debrief/updates on slack
- [ ] Debrief research sessions into note-taking spreadsheet
- [ ] Download recordings
- [ ] Download notes from Perigean
- [ ] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by MarciMcGuireGCIO** [comment]
This is currently blocked due to the Perigean contract ending

**Comment by MarciMcGuireGCIO** [comment]
Perigean contract renewed 12/13/2021

**Comment by MarciMcGuireGCIO** [comment]
Cannot start until we have research candidates lined up and sessions scheduled.

**Comment by andaleliz** [comment]
Final session completed today!
