### ISSUE TITLE
Midpoint Review Auth Profile - Personal Information Revision

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33630]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [ ] Notify the Collaboration Cycle team of this ticket with scheduled date/time in the in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [X] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md)
 
- [x] Finalized [design prototype](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i) or mockup
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/research/conversation-guide.md) 

 
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/research/conversation-guide.md) 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth  N/A

- [x] Name of content of truth - [UXPin Prototypes](https://preview.uxpin.com/82e734535b0ab60a1567348b1234e43b5318ad3a#/pages/144815586/simulate/no-panels?mode=i)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
- [ ] #31186
- [ ] #32327
- [ ] #31819  - placeholder to capture required update; Content request has not yet been opened
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct) - [Test Rail Regression Tests](https://dsvavsp.testrail.io/index.php?/cases/view/386&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=63) - will need to be updated
- [x] Link to test cases/test plan in TestRail (draft OK)  [Test cases in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md)

### Required* 
\*Only required for synchronous meetings.
- Product Manager: Marci McGuire
- OCTO-DE Product lead: Samara Strauss
- OCTO-DE Design lead: Ryan Thurlwell

## Asynchronous review option
Would you like this review to be asynchronous?  

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by MarciMcGuireGCIO** [comment]
Midpoint review scheduled for 11:30 AM ET on Friday, Dec 10

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO thanks for adding the date above! Confirmed that 12/10 at 11:30am ET is correct :)

**Comment by andaleliz** [comment]
👋 Hi! I noticed in the [midpoint review objective section](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html), it states

>To confirm your prototype or mockup aligns with existing VA.gov patterns and standards and to ensure your product is ready for successful usability testing.

Our research isn't usability testing- rather it's an interview to evaluate how people understand the terminology and IA of the page.  Does the midpoint review still apply in that case?  If so, perhaps the review objective needs to be updated?

**Comment by shiragoodman** [comment]
> 👋 Hi! I noticed in the [midpoint review objective section](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html), it states
> 
> > To confirm your prototype or mockup aligns with existing VA.gov patterns and standards and to ensure your product is ready for successful usability testing.
> 
> Our research isn't usability testing- rather it's an interview to evaluate how people understand the terminology and IA of the page. Does the midpoint review still apply in that case? If so, perhaps the review objective needs to be updated?

thanks for the question @andaleliz ! Midpoint Review is still applicable since you'll be putting _something_ in front of veterans to respond to... whether that be an actual working prototype that they interact with, or an interview to evaluate people's understanding of the terminology and IA. We want to ensure that what you're researching with Veterans is as close to the VA.gov standards as possible so your research results are valid. If you have a glaring standard issue in your research materials, it could invalidate the research results. 

I will take an action to get our Midpoint Review objective section updated. Thank you for bringing to our attention!

**Comment by jimuhh** [comment]
@andaleliz Speaking strictly for myself as the resident IA person, I'm thrilled to see you taking that approach. And I found the research plan and conversation guide very thoughtful and thorough. Kudos!

**Comment by allison0034** [comment]
No design feedback, thank you!

**Comment by jimuhh** [comment]
No IA feedback, thanks.

**Comment by andaleliz** [comment]
>Speaking strictly for myself as the resident IA person, I'm thrilled to see you taking that approach. And I found the research plan and conversation guide very thoughtful and thorough. Kudos!

Yay, I'm glad our approach has your stamp of approval. @cgednalske did the bulk of the work, kudos to her as well! 👏 🎉

**Comment by joshkimux** [comment]
No major feedback from accessibility! We recommend engineers and designers to start planning for:
- how to provide specific labels to the edit buttons (we usually use `aria-label`s)
- how to code the list of items (either as an unordered list `ul` of headings or a description list `dl`)

We're more than happy to help answer those questions!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @joshkimux! This is great info to have!

Cc @adamwhitlock1
