### ISSUE TITLE
Add a "null" alt value to remove WAVE error for Veteran Crisis Line button 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33650]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need to be able to use screenreader technology when attempting to click and use the VCL button. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C8E985R32/p1638566761034300)

## Description
- Adding a null ("") alt value should remove it from being flagged in Wave (See Slack Thread for more details).

## Tasks
- [x] Adding a null ("") alt value should remove it from being flagged in Wave.
- [x] Ensure change is functional and tested local/staging env.
- [x] Close ticket when completed 

## Acceptance Criteria
- [x] Wave is no longer hitting an error state when using screen reader for the Veteran Crisis Line.

**Comment by brianalloyd** [comment]
@tmac9494 can you take this ticket.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/847

**Comment by kelsonic** [comment]
PR is merged, will go out with the daily tomorrow

**Comment by brianalloyd** [comment]
Completed, closing ticket in support.
