### ISSUE TITLE
Feature Request Process - Confirm VFS can submit feature requests

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#33657]
## Issue Description
Confirm VFS team members can use the Github issue form to submit feature requests to the Platform.

---
## Tasks
- [x] Recruit VFS team member to test form
- [x] Send tester [user guide](https://vfs.atlassian.net/l/c/wJB09iNE)
- [x] Have tester confirm links to project board and issue form are accessible
- [x] Have tester submit test feature request

## Acceptance Criteria
- [ ] Ticket submitted by VFS tester appears on the project board.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
- VFS team member was able to access [user guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1938915400/Submitting+a+feature+request)
- VFS team member confirmed they can access the project board and issue form 
- VFS team member submitted the request ([for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33731))
