### ISSUE TITLE
Create Internal Report Usage Dashboard in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#33697]
## Issue Description
_We have two comprehensive dashboards in DOMO for two of our products and we want to monitor usage to help identify opportunities_

---
## Tasks
- [ ] _Create dashboard in DOMO to report on usage for our Salesforce Support Issue Dashboard and our Medallia Survey Dashboard_

## Acceptance Criteria
- [ ] _Usage data for our reports (support & surveys) in DOMO is viewable in a separate, internal only dashboard_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
The [dashboard](https://va-gov.domo.com/page/1949678928) has been created.

It tracks total users, views, and user types. If you want anything else added to it or discuss the current data, let me know @jwoodman5
