### ISSUE TITLE
Collaboration Cycle Kickoff/Design Intent - [Facilities team, Facility operating status displays]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33696]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [ ] Answer the questions below and attach any artifacts you have available.
- [ ] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Facility operating alerts are currently in production with a range of implementations on various pages documented in the table below. We performed an audit to find where and how these implementations differed [(#32167)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32167) and made [recommendations (UX pin)](https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/documentation/no-panels?mode=i)  to provide a consistent experience within and across products. 

<details>
<summary> Table of pages </summary>

| Page | Implementation
-- | --
[Facility locator search results](https://www.va.gov/find-locations/?address=atlanta&bounds%5B%5D%5B%5D=-77.7866&bounds%5B%5D%5B%5D=38.145&bounds%5B%5D%5B%5D=-76.2866&bounds%5B%5D%5B%5D=39.645&context=Atlanta%2C%20Georgia%2C%20United%20States&facilityType=health&latitude=33.7491&longitude=-84.3902&page=1&radius=43&serviceType&bounds%5B%5D=-85.1402&bounds%5B%5D=32.9991&bounds%5B%5D=-83.6402&bounds%5B%5D=34.4991) |  ![image](https://user-images.githubusercontent.com/55411834/139501570-e9aec8a5-ea13-473f-974e-de5a464a11d9.png)
[Facility locator detail page](https://www.va.gov/find-locations/facility/vha_508GA) |  ![image](https://user-images.githubusercontent.com/55411834/139501655-e4439a45-2e2a-4dd4-a3eb-8b678076edbf.png) |
[Vet Center main page](https://www.va.gov/reno-vet-center/) |  ![image](https://user-images.githubusercontent.com/55411834/139500732-be9a42d7-446f-4be4-8637-ea4617e3b19a.png) |
[Vet Center Locations page](https://www.va.gov/reno-vet-center/locations/) |  ![image](https://user-images.githubusercontent.com/55411834/139501280-82d5ca9d-69f4-4592-adda-84cbdc7dcc4f.png) |
[VAMC facility page](https://www.va.gov/atlanta-health-care/) |  ![image](https://user-images.githubusercontent.com/55411834/139501391-8846c540-96af-470f-95db-99720a893f5b.png) |
[VAMC operating status page](https://www.va.gov/atlanta-health-care/operating-status/) |  ![image](https://user-images.githubusercontent.com/55411834/139501449-0597a978-cb24-402c-8999-34666a58286f.png) |

</details>

Note: The detail page examples on FL are being replaced by the new products, but the same experience applies to Cemeteries and Benefits offices that will have detail pages for the forseeable future.

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes _We're proposing a move to use the alert icon rather than the info icon for the yellow Limited services and hours status and implementation of the expandable alert in all uses everywhere except in FLocator search results._ 
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Operating status displays on Facility Locator search results and detail pages, VAMC pages,  and Vet Center pages

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

### 6. Will your work involve changes to: (select all that apply)

- [x] Tools and applications*
- [x] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [x] Changes to existing content

### 8. Are you making a change to the user flow?
- [ ] Yes
- [x] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [x] Yes.  _#vsa-facilities_

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [x] VACO (Veterans Affairs Central Office) - _Dave Conlon_
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @mmiddaugh. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)

- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)

- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)

- [Privacy and Security Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.

Please reach out to Dave Conlon to let him know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by mmiddaugh** [comment]
Scheduled via Calendly for Tuesday, January 4, 2022, 9:30am - 10:00am, Mountain Time

**Comment by shiragoodman** [comment]
hey @mmiddaugh  - I apologize, but could we move to Monday 1/3 or Friday 1/7? We have a conflict at 11:30am ET and I hadn't gotten around to updating Calendly for availability yet.

**Comment by shiragoodman** [comment]
@mmiddaugh as stated in the Design Intent meeting, I think we can skip the Midpoint review, however please let us know what solution you move forward with so that we are aware for the Staging Review. Thank you!

**Comment by jimuhh** [comment]
@mmiddaugh -- Thanks for the thorough presentation. No formal feedback here. 
The info icon for a time-sensitive alert always made me go "hmmm," so this change makes lots of intuitive sense to me. Still, I would be curious to learn how you decide to test its relative effectiveness.  Again, great work.

**Comment by shiragoodman** [comment]
Zoom recording: https://us06web.zoom.us/rec/share/WWCLUdJlsh95ZaAYYYw8bY0CNQ2P2gvmVF-MlsWvtv4Cry9BuBERaJW7ZSt79b0q.JwZk7tUmpjF2T4LK 
Passcode: zbk9?r8!

**Comment by mmiddaugh** [comment]
Takeaways from meeting
- Limited services and hours should use a yellow background with a warning alert icon
- Square corners should be used since rounded = interactive and we have a mix 
- Need to get accessibility input on active link/underline
- The chevron for "Locations" can be dropped if text acts as a link. 

Takeaways from conversation with Angela
- Placement under the name gives enough context
- operating status display should be coded as a link if it is intended to take the user somewhere. Clicking on it should open in the same tab (user will need a way to get back via back button or breadcrumb. Focus should move to pertinent area on the new screen. 
- Facility Locator is not currently announcing the operating status to screen readers. 
- Consider aria live region so details are announced (may want to also consider polite)
- Difference in urgency level (informational vs alert) can be included in screen reader announcement

We should inform group of design designs in advance of staging review.

**Comment by mmiddaugh** [comment]
feedback in Facility operating status design iteration #34761
