### ISSUE TITLE
Testing Tools Team Q4 2021 Tech Debt

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#33718]
_NOTE - Tickets for the subtasks are still being detailed_

## Problem Statement 
In the course of developing MVPs throughout the year, solutions are developed that leave unrefined technical solutions in place.

How might we identify and prioritize technical debt solutions that can be improved during this extended sprint?

## Hypothesis or Bet
*How will this initiative impact the quality of VFS or VSP teams' work?*
*How will this initiative be easy for VFS or VSP teams? Or how will it be easier than what they did before?*

## What we'll do... ("Definition of Done")
- [x] Review backlog for possible tech debt tasks
- [x] Ask the team for suggestions on tech debt tasks
- [x] Review and prioritize tech debt tasks within this epic
- [ ] Complete the work
- [ ] Document & release updates as needed

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*
