### ISSUE TITLE
Staging Review [Design System Team - Telephone Web Component]

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33714]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [ ]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [ ]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [ ] Staging URL - https://wc-telephone--60f9b557105290003b387cd5.chromatic.com/?path=/docs/components-va-telephone--default 

- [ ] Product outline -  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

### Required
- Product Manager: Carol Wong
- OCTO-DE Product lead: Ryan Thurlwell
- OCTO-DE Design lead: Ryan Thurlwell
- Engineer: Brooks Johnson
- DST Tech Lead: Katy Bowman
- Engineer: Andres Rivera (optional)
- Engineer: Preston Davies (optional)
- Accessibility Specialist: Courtney Chambers
- Designer: Natalie Hill (optional) 

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Staging Review scheduled for 12/16 at 1:30pm ET

**Comment by jimuhh** [comment]
Hi @caw310 ! I was wondering about the decision not to use the [North American Numbering Plan](https://en.wikipedia.org/wiki/North_American_Numbering_Plan) which calls for three-digit area codes to be put in parentheses, a format that users have come to expect and that is also recommended in [Google's dev style guide.](https://developers.google.com/style/phone-numbers)

**Comment by caw310** [comment]
@jimuhh We are following the Content guidelines for telephone format. 
https://design.va.gov/content-style-guide/dates-and-numbers

**Comment by jimuhh** [comment]
@caw310 OK thanks. No  IA feedback.

**Comment by seanasewell** [comment]
No design feedback. Good work!

**Comment by noahgelman** [comment]
No accessibility feedback
