### ISSUE TITLE
[FE] Update pre check-in to handle when vets-api returns a HTTP 200 but with error status in body

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#33725]
## How to configure this issue

- [x] Attached to an Epic (what body of work is this a part of?)
- [x] Correctly Labeled
- [x] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story
As a veteran, I want to see the correct status of pre check-in (whether it succeeded or failed) when I submit the pre check-in.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description
Currently for day of check-in, if there's any error in downstream services, api returns a HTTP 200 with the error message in the body. vets-website correctly handles it by checking the body and showing an error. For pre check-in however, it is not showing an error in this case. 

We discussed the correct approach for handling this and agreed that currently, we'd have the same behavior for pre check-in and will have future work to update api to return correct HTTP status code in case of downstream failures.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
