### ISSUE TITLE
Update enrollment alert on Post-9/11 GI Bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33724]
## Issue Description
Currently we have an alert on the [Post-9/11 GI Bill page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) about needing to verify enrollment each month. If you're at an institution of higher learning this starts for terms that start after December 17, 2021. We also have language in the alert that says to "check back here soon when this new requirement starts for you." 

We need to reach out to stakeholders and determine if this needs to be updated after December 17 and make the updates in Drupal. 

## Tasks
- [x] Add content to Drupal
- [x] Send to stakeholders for approval
- [x] Review and publish

## Acceptance Criteria
- [x] Updated alert live on the site

**Comment by RLHecht** [comment]
@bethpottsVADEPO This is the language Selina and I came up with for this updated alert. If this looks good, do we need to email it to the stakeholder before we publish?

H2: New requirement to verify your enrollment

If you get monthly housing allowance (MHA) and/or college fund (called “kicker”) payments under the Post-9/11 GI Bill, you must verify your enrollment each month if one of these applies to you:

•	You’re in a non-college degree program, **or**
•	You’re at an institution of higher learning

**Note:** If you’re at an institution of higher learning and your term begins between December 17, 2021, and December 31, 2021, you’ll automatically be verified for the month.

If neither of these apply to you, check back here soon to find out when this new requirement will start.

[Learn more about verifying your enrollment](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp)

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht This actually isn't quite accurate. The monthly housing allowance (MHA) and/or college fund (called “kicker”) payments under the Post-9/11 GI Bill connects only to people who are in a non-college degree program. It's not applicable for people who are at an institution of higher learning. 

Can you try reworking it to reflect this?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you for pointing me to where this is explained. I misunderstood, and you are correct!

Couple edits (can you show me the preview when it's ready, then we'll send to SMEs?):
**H2: New requirement to verify your enrollment**

**If you get monthly housing allowance (MHA) and/or college fund (called “kicker”) payments** under the Post-9/11 GI Bill, you must verify your enrollment each month if you're at one of these types of facilities:

• A non-college degree facility, **or**
• An institution of higher learning (if your term begins between December 17, 2021, and December 31, 2021, we'll automatically verify your enrollment for the month)

**If you don't get monthly housing allowance (MHA) and/or kicker payments,** check back here soon to find out when this new requirement will start for you.

Learn more about verifying your enrollment

**Comment by lunascoop** [comment]
@bethpottsVADEPO I'd have to publish the alert for the updates to show. Is that ok?

**Comment by bethpottsVADEPO** [comment]
@lunascoop I'm going to try to shorten it a bit, then Randi can send it to stakeholders to make sure it's accurate before we publish tomorrow. I'll just edit directly in drupal. I'll ping you here in the ticket when I'm done.

**Comment by bethpottsVADEPO** [comment]
I see what you're saying about alerts now that I went to the file. So just posting the shortened language here for Randi to run past SMEs:

**New requirement to verify your enrollment**

**If you get monthly housing allowance (MHA) and/or college fund (called “kicker”) payments,** you must verify your enrollment each month if you're at:

• A non-college degree facility, or
• An institution of higher learning (if your term begins between December 17, 2021, and December 31, 2021, we'll automatically verify your enrollment for the month)

**If you don't get monthly housing allowance (MHA) and/or kicker payments,** check back here soon to find out when this new requirement will start for you.

Learn more about verifying your enrollment

**Comment by bethpottsVADEPO** [comment]
If this ends up being way too long after we publish, we could put it in an additional info component like we have on this page: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

**Comment by RLHecht** [comment]
I published this page this morning. @bethpottsVADEPO you can see how long it is in the preview link. I think it's OK as is. preview-prod.vfs.va.gov/preview?nodeId=935

**Comment by bethpottsVADEPO** [comment]
It's a little long I think. Would you put it in an additional info components as on the vet tech page? And please tweak the first line to eliminate "and/or," to change "called" to "or," and to add back some of the text I had before since length isn't as much of a concern with using the additional info approach:

**If you get monthly housing allowance (MHA), college fund (or "kicker") payments, or both,** you must verify your enrollment each month if you're at one of these types of schools:

**Comment by RLHecht** [comment]
I just updated this and will check once it's live.

**Comment by RLHecht** [comment]
The alert as the expanded text is now live. https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ Closing ticket.
