### ISSUE TITLE
Hardcode "In the spotlight" title for common links on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33727]
## Issue Description
Currently it is possible for content editors to change the title of the "In the spotlight" blue box containing common links on VAMC system pages but is intended to be standardized as "In the spotlight at [system name] health care"

This component appears on system and facility page templates

![image](https://user-images.githubusercontent.com/55411834/145087144-6370b13b-52b3-48d4-87a3-6bf55d262826.png)

We can hardcode this title to prevent editors from changing it. CMS will take #7096 when it can, which has a small FE aspect. 

This box is optional, so we should ensure the title does not appear unless there is content to display

Dependency: need field name for use in this title (assuming `title`)

---
## Tasks
- [ ] Hardcode the "In the spotlight at VA [system name]" H2 

## Acceptance Criteria
On both system and facility level VAMC pages
- [ ] If link teasers are populated, the title should be "In the spotlight at VA [system name] health care"
- [ ] If no teasers are available, the box and title should not appear visually or to assistive tech (no tags)
