### ISSUE TITLE
Remove address blocks from CRSC article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33729]
## Issue Description
We currently use the address block component within the accordions of the [Combat-Related Special Compensation](https://www.va.gov/resources/combat-related-special-compensation-crsc/) article. Because these are not in a long chunk of running text, this component isn't needed to separate out the address from any other content. 

## Tasks
- [x] Remove address block component from page (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Content is no longer in address blocks on the live site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review. I thought it was in this sprint and I missed it, but guess not.

Combat-Related Special Compensation (CRSC): http://preview-prod.vfs.va.gov/preview?nodeId=18658

**Comment by RLHecht** [comment]
@lunascoop I realized that I didn't specify above that we are only going to take the address blocks out of the first set of accordions where there isn't running text and it's clear we are showing an address. Could you please put them back in to the accordions that are farther down the page? Thanks!

**Comment by lunascoop** [comment]
Done

**Comment by RLHecht** [comment]
Thanks! Just published and will close when live.

**Comment by RLHecht** [comment]
This page is live. @bethpottsVADEPO This is now published if you want to show to the design council as we were discussing yesterday.
