### ISSUE TITLE
[Design] Auth Profile - Address Change Messaging - Wireframe possible solutions

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33734]
## Issue Description

_See #30112 for more background and discussion from meeting with stakeholder team_

As a Veteran, I need to be aware that if I modify my home address that I also need to confirm my mailing address so I can make sure that I continue to receive correspondence and/or prescriptions from the VA.   

Today, there is a message in the Home address section, but it is not clear to the end user what exactly will occur if they click that box (it copies the existing mailing address to the home address fields, but the user may actually want the opposite to happen).  

It is also not immediately apparent in the Addresses section that the mailing address is the one used for VA correspondence and prescriptions, although it is mentioned in the very last bullet if the user expands the `Which benefits and services does VA use this contact information for?` info component.

---
## Tasks
- [x] Look for possible existing metrics to use for baseline. Here is some GA data on how often addresses are changed. Don't know about the checkbox, but there should be an action we can track. https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/
- [x] Create wireframes showing possible ways to improving the user experience when a Veteran updates their VA.gov Profile home or mailing address.
- [x] Review wireframes with the team
- [x] Review and discuss next steps with PO

## Acceptance Criteria
- [x] Low-fidelity wireframes have been created
- [x] Team has meet to look at the wireframes and discuss
- [x] PO has reviewed the wireframes and discussed next steps

**Comment by andaleliz** [comment]
@tmitchellgcio when I check out the current feature on staging, it seems like there is some check being performed to compare the home and mailing addresses.  I'm assuming this based on:
1. I go to home address and check the "my home address is the same as my mailing address box" and click save.
2. I click edit on home address again, and the box is still checked. I click cancel.
3. I click edit on the mailing address and save.
4. I go back to home address, and the box is unchecked.

Can you tell me more about exactly what check is being done? I'm wondering if we already have the ability to display a message based on a couple conditions:
1. user updates home address
2. After user saves home address, the mailing address doesn't match.

Thanks!

**Comment by tmitchellgcio** [comment]
I believe there is a function to copy the address and compare them when that checkbox is clicked. I will have to dive in the code, but we have the ability to display messages in both of those scenarios.

**Comment by andaleliz** [comment]
Thanks @tmitchellgcio - there's definitely a function to copy the address from mailing to home. But it would be great to learn more about the comparison functionality we have. Since this ticket is just for wire-framing possible solutions, I don't think you need to spend time digging into the code just yet. We can open a FE ticket for that work when we get there. I appreciate the info!

**Comment by andaleliz** [comment]
I've put together [a Mural board with some possible solutions](https://app.mural.co/t/vsa8243/m/vsa8243/1639511492636/a7d05e80d5289ba70da1cd6f7b99fb8f7bf3276f?sender=lizlantz1528), and will review w/ Danielle tomorrow (office hours are cancelled today).

**Comment by andaleliz** [comment]
@Samara-Strauss out of curiosity, do you have any background info on this functionality? I'm curious why this checkbox exists in the home address but there isn't an equivalent in the mailing address, and also about the decision to have the blue background behind the checkbox. I imagine the latter is to separate it from the second checkbox but am not sure. Tressa wasn't sure either.

**Comment by Samara-Strauss** [comment]
For most of your questions, tbh, I'm not sure. These decisions were made years ago, and I don't even think I was the person who made them at the time. So I'm sorry to not be more helpful, but I don't have any background context here.

>  I'm curious why this checkbox exists in the home address but there isn't an equivalent in the mailing address

I'm not sure this is the reason, but if I had to hypothesize, it's because the mailing address is seen as far more important than home address at the VA since all correspondence goes to whatever is listed as the mailing address. It's the primary address in the eyes of the VA, so my guess is that's why we care if the home address is the same as the mailing address but not the other way around. I'm not saying that's the greatest or best thinking, just that it's my best guess on a rationale for this design.

**Comment by andaleliz** [comment]
I reviewed these with Samara and Danielle, and we are good to go with these solutions. I'd like to evaluate the proposal in a task at the end of the Personal Information research, just to validate that this approach will indeed work for Veterans. It will also be helpful to get confirmation about the technical feasibility of this, so I will set up a meeting to review. @MarciMcGuireGCIO is Adam the dev I should review these with?

**Comment by Samara-Strauss** [comment]
Yep! Adam is the FE dev working on profile currently.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz thank you! Adam doesn’t yet have any context for this work, so maybe we should schedule a meeting with Christina and Adam after we get back from the holiday break.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO Adam and I have some time set up on Monday to meet and I'll use part of that time to introduce the problem and what I'm thinking of. We can go from there :)

**Comment by andaleliz** [comment]
Reviewed [this prototype ](https://preview.uxpin.com/e21218c405e4475d518bc209ffd66405a9633080#/pages/145359491/simulate/no-panels?mode=i) with Adam and Christina today. Closing out!
