### ISSUE TITLE
[EPIC] Auth Profile - Address Change Messaging

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33732]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I need to be aware that if I modify my home address that I also need to confirm my mailing address so I can make sure that I continue to receive correspondence and/or prescriptions from the VA.

## Hypothesis or Bet
**If** _we make the messaging more intuitive when Veterans update an address in their VA.gov profile_ **then** _we expect that fewer will assume that changing one address automatically changes the other, and will update both addresses if needed_.

## OKR
_Which Objective / Key Result does this epic push forward?_  Ease of Use

Key results: Fewer Veterans will overlook updating their mailing address when updating their home address and vice-versa.

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*
- [ ] Wireframe potential solutions #33734 
- [ ] Review potential solutions with team -  included in #33734 
- [ ] Get content input on copy  #33737 
- [ ] Select solution(s) to create high fidelity mockup - included in #33734 
- [ ] Test with users 
- [x] #33772
- [x] #33773
- [x] #33774
- [ ] Test - included in #33774
- [ ] Validate - included in #33774
- [ ] Deploy - included in #33774

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
