### ISSUE TITLE
[Design] Auth Profile - Address Change Messaging - Attend office hours for content recommendations

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33737]
## Issue Description
Attend Content office hours to request feedback on the language to use in the wireframes for Address Change Messaging.

---
## Tasks
- [x] Attend Content office hours to present low-fi wireframes
- [x] Incorporate Content feedback into wireframes

## Acceptance Criteria
- [x] Lo-fi mockups have been presented during Content office hours
- [x] Feedback has been incorporated into wireframes.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
Completed on 12/17
