### ISSUE TITLE
Cross Reference Support Templates with KM Articles

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#33747]
## Issue Description
_We want to cross-reference support response templates with applicable KM articles_

---
## Tasks
- [ ] _cross-reference support response templates with applicable KM articles_

## Acceptance Criteria
- [ ] _Applicable KM articles are cross-referenced in support response templates_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
