### ISSUE TITLE
Add Support Response Templates to AVA

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#33745]
## Issue Description
_Now that we are handling support issues in AVA, we want to add our response templates there for more efficient handing of cases_

---
## Tasks
- [ ] _Add support response template to AVA backend_

## Acceptance Criteria
- [ ] _All applicable support templates have been added to AVA_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Now that we're getting more of the team involved in AVA, I'm going to revisit whether it's worth adding the response templates to AVA's template response feature. I may move this up to the sprint ending 11/4.

**Comment by starlow00** [comment]
To better facilitate John and Megan's work in AVA, will begin adding response templates to AVA once the AVA classifications have been added/sorted.

**Comment by starlow00** [comment]
Will work on this the week of 11/13.

**Comment by starlow00** [comment]
Completed, info shared with team. Will conduct related training next sprint.
