### ISSUE TITLE
Add Cerner link to hardened Medical Records page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33741]
## Issue Description
The current VA blue button medical records widget will not provide the best experience for Veterans receiving care at Cerner facilities. Until we can provide a more elegant solution, we can replace the widget for a simple link [to view clinical notes via the patient portal](https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes).

### Other relevant work
- #31109 added redirects to the a general login page for the Cerner portal from within the "Manage your health online" box based on a Cerner flag in CMS identifying systems which have cutover. 
- #33740 will update the general links with task-specific deep links.

**This work will block the release of the hardened medical records page.** 

### Current experience

Example page: [Spokane Medical records](https://www.va.gov/spokane-health-care/medical-records-office/)
![image](https://user-images.githubusercontent.com/55411834/146585204-f145570b-1d52-4ff3-acfd-827a979eadb2.png)

### Expected experience
![image](https://user-images.githubusercontent.com/55411834/146585141-6f36f973-a661-43b9-95db-90383d48aab3.png)

[CMS mural for this work](https://app.mural.co/t/vagov6717/m/vagov6717/1639530168395/b114bb336a1db8c0a571272b10a230e1360d2775?sender=michellemiddaugh9063

---

## Tasks
- [ ] Based on Cerner flag (based on CMS flag: `field name vamc_ehr_system`), replace VA blue button widget with "Get your records online" link (as shown above)
- [ ] Ensure link directs users to https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes

## Acceptance criteria
- [ ] When field name=`vamc_ehr_system`, no VA blue button widget is seen on the Medical records page for that health care system. 
- [ ] When field name=`vamc_ehr_system`, Veterans can click on a link on that health care system's Medical records page to be directed to the health record portion of the Cerner portal. 
- [ ] When field name does not = `vamc_ehr_system`, the existing functionality is maintained.

**Comment by mmiddaugh** [comment]
closing as a duplicate to #35947
