### ISSUE TITLE
Identify sources of traffic pointed to old endpoint

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33743]
## Issue Description
We've identified traffic on our old endpoint with "static page" and "dashboard" headers. We need to find the owners/sources of this traffic so they can update their endpoint appropriately and we can deprecate the old endpoint. 

---
## Tasks 
(as determined during conversation with Megan Kelley. Tim Wright may also be able to help)
- [ ] Determine which traffic belongs to the Facilities team based on VAMC and Vet Center pages
- [ ] Review static page directory for other possible sources
- [ ] Review [Static page app audit](https://vfs.atlassian.net/wiki/spaces/FTT/pages/1906671617/Static+Pages+app+audit) 
- [ ] Review [Static pages architecture investigation and recommendation](https://vfs.atlassian.net/wiki/spaces/FTT/pages/1937014880/Static+pages+architecture+investigation+and+recommendation)
- [ ] Contact identified teams to make them aware of change in endpoint and plans to deprecate
- [ ] Monitor traffic
