### ISSUE TITLE
Restore pagination for community care providers and pharmacies

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#33753]
## Issue Description

Addition of # of results in header is a separate effort 

## Tasks
- [ ] Remove hard coding to suppress pagination
- [ ] Page and per page will be available for pagination of following searches
      - [ ] community care providers
      - [ ] community pharmacies
- [ ] Include in original toggle 
- [ ] Update/add tests as needed 

## Acceptance Criteria
- [ ]  Veterans can see search results expressed 10 per page (as appropriate) for the following searches
      - [ ] community care providers
      - [ ] community pharmacies
- [ ] Pagination can be toggled

**Comment by gescobardev** [comment]
I realized we don't need this ticket because we can turn on pagination [here](https://api.va.gov/flipper/features) `facility_locator_restore_community_care_pagination `
This is currently turned on in staging, we can turn this on in prod.
