### ISSUE TITLE
[FE]  Auth Profile: Update Personal Info page to link to "why we ask for this" to R&S article

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33757]
## Background
Based on [this conversation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32327#issuecomment-983767025), the "Why we ask for this" copy at the top of the Personal Info page will be changed to a link to a Resources & Support article. [URL TBD]  Please refer to mockup: https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/zx0GAGa

## Tasks
- [ ] Change Personal info page `Why we ask for this` info component to a link
- [ ] Link `Why we ask for this` link to R&S article [URL TBD]
- [ ] Complete all unit testing
- [ ] Deploy to Staging behind feature flag
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production

## Acceptance Criteria
- [ ] Personal info page `Why we ask for this` info component is changed to a link
- [ ] `Why we ask for this` link links to R&S article [URL TBD]
- [ ] All testing has been completed
- [ ] Changes have been deployed to Staging behind feature flag
- [ ] Team has been notified that the change is ready to be validated on Staging
- [ ] Any changes resulting from Staging has been incorporated & re-tested
- [ ] Change has been deployed to Production

**Comment by Samara-Strauss** [comment]
@MarciMcGuireGCIO I am referring to the first question in this screenshot which clarifies why we are asking for preferred name/pronouns/gender identity/sexual orientation. 

The question that is blocked by VBA is the second one -- how do I update my name/birth date/birth sex?

![image](https://user-images.githubusercontent.com/34068740/149390465-5911e4e7-5b78-470e-934c-c97b8c33f384.png)

**Comment by MarciMcGuireGCIO** [comment]
Got it; thank you for clarifying.

**Comment by MarciMcGuireGCIO** [comment]
Consolidated these tasks into ticket #36006
