### ISSUE TITLE
Auth Profile: Test VA.gov Profile on Staging after VA Profile migrates to new API 12/17

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33754]
## Background
The VA Profile team is migrating to a new API on Staging on 12/17 and we need to test VA.gov Profile to be sure that data is loading correctly.

## Tasks
- [x] Test logging into VA.gov profile on Staging
- [x] Test Personal & Contact Info
- [x] Test Military Info
- [x] Test Direct deposit info
- [x] Test Notification settings
- [x] Test Account security
- [x] Test Connected apps

## Acceptance Criteria
- [x] Logging into VA.gov profile on Staging has been tested
- [x] Personal & Contact Info has been tested
- [x] Military Info has been tested
- [x] Direct deposit info has been tested
- [x] Notification settings has been tested
- [x] Account security has been tested
- [x] Connected apps has been tested
- [x] VA Profile team is notified that testing was completed; any issues are reported.

**Comment by MarciMcGuireGCIO** [comment]
Tested Profile on Staging and found no issues.
