### ISSUE TITLE
Add LGY Guaranteed Remittance to the vagov staging fwdproxy

### ISSUE THREAD

**Issue by christineyost** [department-of-veterans-affairs/va.gov-team#33759]
## Description
Add LGY Guaranteed Remittance to the vagov staging fwdproxy so that it is accessible through the staging Lighthouse API gateway. The LGY Guaranteed Remittance SQB environment needs to be mapped to the Lighthouse staging environment.

## Background/context 
* The ticket tracking this work is [here](https://vajira.max.gov/browse/API-11392)

## Technical notes
* I created a [PR](https://github.com/department-of-veterans-affairs/devops/pull/10395) that I believe should make the required change. If this is all that needs to happen I'm happy to merge this PR in, but I'm not familiar with what needs to happen in order to get this change deployed once its merged.
* I was able to test the specified healthcheck in CAG and got back a 200. Not sure if anything else needs to be tested.

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] The Lighthouse staging gateway can forward requests to the LGY SQB environment

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
I believe this is working. Please see [this](https://dsva.slack.com/archives/CJYRZK2HH/p1639604753008200?thread_ts=1639172917.415700&cid=CJYRZK2HH) thread in DSVA Slack for confirmation from the requester.

**Comment by jhouse-solvd** [comment]
Closing.
