### ISSUE TITLE
[Design] Auth Profile: Notification Prefs: Mock up Josh Kim's suggestion for resolving a11y issue #31446

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33752]
## Issue Description
A 508 defect-3 issue (#31446) from the Notification Preferences Staging review needs a designer to review recommendation from the Accessibility team and mock up their recommended solution.

---
## Tasks
- [ ] Mock up [Josh Kim's suggested modifications from related FE a11y ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31446#issuecomment-983767663)
- [ ] Review with Josh to confirm the change satisfies the accessibility requirement
- [ ] Update PM so that FE ticket can be unblocked
- [ ] Update related Sketch file

## Acceptance Criteria
- [ ] Josh has confirmed the mocked-up change satisfies the accessibility requirement
- [ ] PM has been notified that design change is approved by accessibility so the related FE issue can be unblocked
- [ ] Related Sketch file is updated to reflect design change

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
Hi @MarciMcGuireGCIO - I took a look at Josh's ticket, and I'm not sure design work is necessary here. The [suggestions in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31446#issuecomment-983767663) are exactly what I'd recommend and will resolve the a11y issue, without changing the design at all.   FE would just need to make a couple of small tweaks to the code.

**Comment by MarciMcGuireGCIO** [comment]
Ok; sounds good. Thank you! I'll close this out and link over to your comment.  Gracias, senora!  (helping you practice for PR)

**Comment by MarciMcGuireGCIO** [comment]
Closing this per above comments and removing as a blocker for 31446
