### ISSUE TITLE
[Research] Draft Research Plan - HRT Static Content Landing Page 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33756]
## High Level User Story/ies
As a Veteran or VA employee, I need a way to report an incident of workplace harassment or assault which takes place at a VA facility so I can be assured that there is investigation and remediation.

[Product Outline for Reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/read-me.md)

##  Tasks 
- [x] Draft research plan 
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback 
- [x] Work with PM to build research tickets to account for work and support

## Acceptance Criteria 
- [x] Initial research plan drafted by Dec 17 with gaps  highlighted
- [x] After Brian reviews initial research plan, share with Dave and Danielle in preparation for discussion on Jan 3
- [x] Draft research plan available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
Drafted [initial research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-plan.md) with unknowns noted, shared with Brian for feedback, made a few revisions, and then shared with Dave and Danielle in preparation for our meeting on Jan 3.

**Comment by brianalloyd** [comment]
Thanks @cindymerrill research draft looks good.  Team plans to meet on Jan 3rd to review research KPIs and define success factors for research efforts.

**Comment by cindymerrill** [comment]
Meeting postponed to Jan 5.

**Comment by cindymerrill** [comment]
Discussed first part of research plan with Dave and Danielle--a very productive meeting but didn't finish, so scheduled a continuation for tomorrow (Jan 6). Will incorporate my notes from the meeting into the research plan.

**Comment by cindymerrill** [comment]
Continued research plan discussion with Dave and Danielle, and revised the research plan afterwards: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-plan.md
Plan to work more on it before sharing it again with them.

**Comment by brianalloyd** [comment]
I discussed the feasibility of placing the HRT static landing page in a Staging environment in support of HRT research efforts and it does appear to be feasible.  We've created a walkthrough video for future devs which minimizes risk factors.

**Comment by cindymerrill** [comment]
Great, @brianalloyd ! I'll incorporate that into the research plan--that we'll be putting the HRT static landing page on Staging instead of building a prototype in UXPin. FYI @callen2563 .

**Comment by cindymerrill** [comment]
Got good info from Dave Conlon this morning. I'll update the research plan tomorrow and work on it more, and then I'll share it with Dave, Danielle, and Brian for review in advance of a meeting on Jan 13.

**Comment by brianalloyd** [comment]
Shifting to next sprint.

**Comment by cindymerrill** [comment]
Revised research plan with more feedback from Dave Conlon yesterday and a slack conversation with him and Danielle today. Shared with UX team for feedback. Tomorrow I'll share with Dave, Danielle, and Brian for review before our meeting on Thursday.

**Comment by cindymerrill** [comment]
Made revisions to my [HRT research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-plan.md) based on the meeting today with Dave, Danielle, and Brian, and also moved the conversation guide ideas section to a new skeletal [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/conversation-guide.md). 

Reached out to Danielle to get her input on the Veteran-facing wording in both documents, especially the following sections:

1. Additional questions to ask in the screener (research plan)
2. Warm-up questions (conversation guide)
3. Post-Task Interview (conversation guide)

**Comment by cindymerrill** [comment]
Incorporated text revisions from Danielle into the section of additional screening questions for Perigean to ask potential research participants.

**Comment by cindymerrill** [comment]
Not moving forward to share with Shane and then launch recruiting because waiting for Dave Conlon's OK from stakeholders first. @brianalloyd

**Comment by brianalloyd** [comment]
@cindymerrill shifting this to S66 based on the pending Stakeholder feedback.

**Comment by cindymerrill** [comment]
Made a few more revisions per feedback from Danielle.

**Comment by brianalloyd** [comment]
Thanks @cindymerrill is this at the point we can present the research plan and Convo guide to stakeholders?  We have a hard date of 2/9 to have them packaged (draft form is okay) in order to review with stakeholders.

**Comment by cindymerrill** [comment]
Incorporated a few more wording revisions from Danielle into the research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/research-plan.md

**Comment by cindymerrill** [comment]
Yes, @brianalloyd. The research plan and convo guide are ready to present to stakeholders. 

Let me know if you need anything else from me in preparation for the stakeholder meeting (besides reviewing the static landing page on Staging, which I still haven't seen yet).

**Comment by brianalloyd** [comment]
Connecting this to the finalization ticket created as a follow on #36366, close out this ticket based on completion of the draft research plan.
