### ISSUE TITLE
LINTER: Validate linter

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33762]
# User story

As a Content team member, I need to test the linter with a Platform website contributor, so that I can refine the linter user experience.

# Tasks

- [ ] Identify/schedule 1-2 willing participants to use the linter
- [ ] Identify modifications to make to linter
- [ ] Modify linter given participants' feedback

# Acceptance criteria
- Particpants have tried the linter

# Reference info
- [Content linter rules](https://docs.google.com/spreadsheets/d/1_3yCVm01jO6UkHTUkWP6pze78k1MA7AYRczOi-GAdvM/edit#gid=0) spreadsheet
- [Noodling space](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/2006908946/Noodling+space+for+content+linter+rules) for the linter rules suggested by Rachael
- [Example of code comment block](https://software-solutions-online.com/wp-content/uploads/2020/07/comments-01-comment-block-example.png)

**Comment by lianilychee** [comment]
let's hold off on testing till the year rolls, so (a) we can really spend time on getting the linter config right (b) can't schedule with people if they're all OOO
