### ISSUE TITLE
PUBLISHING WORKFLOW: Implement 2nd iteration of publishing workflow

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33763]
# User story

As a Platform website contributor, I need a way to "stage" what I've written so that it can be checked by the linter, in ultimately deliver high-quality content and a good customer experience.

# Tasks

- [ ] Create "drafts" space in Platform website
- [ ] Modify [Organization](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) page
- [ ] Identify 1-2 participants for lightweight user testing of iterated publishing workflow

To be handled in XXX:
- Modify [Publishing workflow](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579803/Publishing+workflow) page
- Remove the existing [Contributing to the Platform website | Publishing workflow](https://studio.youtube.com/video/gyZFlXo8Rik/edit) YouTube video
- Other?

# Acceptance criteria
- Particpant(s) understand how to use the "drafts" space

# Reference info
- n/a

**Comment by lianilychee** [comment]
12/9 Thurs:
- will start document today!

**Comment by lianilychee** [comment]
12/13 Mon:
- Going to have to work on tomorrow because working on editorial bar task

**Comment by lianilychee** [comment]
12/14 Tues:
- happening as part of meeting w/ Samara

**Comment by lianilychee** [comment]
12/15 Weds:
- I'm working on that today!! Was focused on Testing tools stuff yesterday
- Done: 
  - The drafts space exists - `Platform website drafts` <- name can be changed if we like
- Today: 
  - Some doc ducks in a row.  Want to ground myself in the problems
  - Wondering: Are we measuring the success of the changes?
    - How do ppl feel?
    - Are we improving the quality

**Comment by lianilychee** [comment]
12/16 Thurs:
- I _kind of_ feel more grounded.  My footing is shaky re: Obj 1.  Want to get clarity on:
  - Are we setting objectives that are tightly aligned by building the Console?
  - Do we prioritize cleaning up the mess that are there, or establishing processes for net new content that's written?  (Teams are not gonna have the bandwidth to clean stuff up)

**Comment by lianilychee** [comment]
12/17 Fri:
- wrote grounding: https://vfs.atlassian.net/wiki/spaces/~369451595/pages/2017100089/2022+Q1+Platform+website+publishing+workflow+updates?atlOrigin=eyJpIjoiNzQ4YzQ3ODIzMjJlNDU2N2I4NzZlODZiN2M1NzVkOTgiLCJwIjoiYyJ9
- today:
  - roughing out publishing workflow diagram and how it would change

**Comment by lianilychee** [comment]
1/5 Weds:
- Blockers/thoughts
  - Have names, but they might not have content ready to push thru.  Perhaps they can just go thru the sandbox?
  - Is there a way we can flag that someone is working on a new doc?  Maybe monitoring via Slack
