### ISSUE TITLE
LINTER: Configure linter

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#33761]
# User story

As a Platform website contributor, I need to know how to improve what I've written so, that I can deliver high-quality content and a good customer experience.

# Tasks

- [ ] Put rules into spreadsheet
- [ ] Prioritize/identify the quality checks that can fit into a "comprehensive" linter for end-of-year (EOY) release
- [ ] Configure the spreadsheet for easy copy/pasting into the text editor
  - All chosen quality checks should have:
    - Rule as it's written
    - YAML
    - Comment or comment block description
- [ ] Populate the text editor with the selected quality checks

# Acceptance criteria
- Quality violations, such as (TBD), are identified by the linter.

# Reference info
- [Content linter rules](https://docs.google.com/spreadsheets/d/1_3yCVm01jO6UkHTUkWP6pze78k1MA7AYRczOi-GAdvM/edit#gid=0) spreadsheet
- [Noodling space](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/2006908946/Noodling+space+for+content+linter+rules) for the linter rules suggested by Rachael
- [Example of code comment block](https://software-solutions-online.com/wp-content/uploads/2020/07/comments-01-comment-block-example.png)

**Comment by lianilychee** [comment]
12/9 Thurs: 
- summary: took care of macros and page elements, 8 sections left
- today: 
  - will have questions for Gretchen and Liani during SU tmr
  - Amy will let Samara and Liani know if there are plug and chug things to do

**Comment by lianilychee** [comment]
12/13 Mon:
- Burning question: What's next to do?
- Today: answering that^^ and putting together a list of next steps for end of year

**Comment by lianilychee** [comment]
12/15 Weds:
- finishing up the rules based on what we talked about on Monday!
- hope tmr SU - will have a good idea of how long will go into writing the YAML
- before Liani and Gretchen OOO - review plan for looping in Samara
  - Amy's initial thoughts: help on typos, setup for YAML formatting

**Comment by lianilychee** [comment]
12/16:
- got sucked by into insurance 😅 
- today: 
  - style guide review, see if anything is missing
  - could use 1:1 on YAML, also sent backup event for tmr
  - want to talk to Samara abt how we're collaborating, dpeends on Liani:Amy

**Comment by lianilychee** [comment]
12/17 Fri:
- no blockers
- today: want to start writing the rules for anything that doesn't have the rules written out
- at start of 2022: test with people to confirm if the rule is clear
-

**Comment by lianilychee** [comment]
Tues 1/4:
- it's configured!!!
- today:
  - review for QA (make sure I didn't miss anything)

**Comment by lianilychee** [comment]
Weds 1/5:
- Blocked: Have to figure out why certain rules weren't appearing when the linter was run on page with said errors. I think it was the way I coded the linter
- Will reach out if can't figure out today
- Commitment for next sprint: If troubleshooting extends past this week, we'll have to scale down our sprint commitments
