### ISSUE TITLE
[Formulate]: Provide `updatePage` all the time

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#33797]
## Description

I'm using [`CustomPage` ](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform/) in a list-loop, so I can't use the built-in method of updating the form data since it doesn't currently work with arrays - i.e. the `name` prop doesn't allow for indexes (`form.data.<name[index]>`). Instead I'm using `<VaTextInput>` along with `<SimpleDate>` and React hooks, but the `updatePage` function is undefined when `CustomPage` is rendered within the form (not on the review page). I have to pull in the `setData` action - this works, but it isn't as convenient.

## Tasks

- [ ] Provide `updatePage` function to `CustomPage` within the form flow
- [ ] Add tests

## Acceptance Criteria

- [ ] All tasks complete
- [ ] All tests passing

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
