### ISSUE TITLE
Sentry Usability Updates

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#338]
## High Level User Story
As a member of VSP, I need Sentry to be an organized, usable tool so that I can monitor and respond to issues in a timely manner.

## Hypothesis/(es)
**If** we establish organizational processes and features in Sentry **then** we will be able to catch errors in a more timely manner.

## Goals
- Sentry errors are readable
- Sentry backlog does not contain anything older than 3 months

## Acceptance Criteria
- ⚠️ Write specs first, before changing any code
- [ ] Decide where Sentry module should be included
- [ ] Sentry log level can easily be changed for a given transaction response
- [ ] Extract `tag_sentry` module method from `vic/pension_burial` so it can be used other places w/ dep. injec. (lookup valid tags_contexts and build struct/dry-type)
- [ ] Explore doing project-based switching? [See](https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/sentry/client.rb#L33)
- [ ] 📔 Documentation:
    - [ ] Audit/improve VSP, onboarding process docs related to using Sentry
        - Address the perspective of a VFS developer needing to add Sentry to their transactions
        - [ ] How are log levels used in regards to Sentry?
        - [ ] How can a developer override the default log level?
    - [ ] How to utilize Sentry logging in:
        - [ ] controllers
        - [ ] service classes
        - [ ] workers

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Automation + Instrumentation`, `Support`)

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**
