### ISSUE TITLE
Deprecate Jenkins in vets-website and content-build except for review instances

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#33802]
## Description

As we have migrated away from Jenkins and now are using Github Actions, we should deprecate Jenkins with the exception of review Instances

## Task
- [x] `content-build` deprecate Jenkins, with exception of RI
- [x] `vets-website` deprecate Jenkins, with exception of RI

**Comment by oseasmoran73** [comment]
content-build [PR](https://github.com/department-of-veterans-affairs/content-build/pull/509)
vets-website [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/18516)

**Comment by oseasmoran73** [comment]
Review instance to work in Github Action [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21750)

**Comment by oseasmoran73** [comment]
Closing ticket as PR has been merged

**Comment by oseasmoran73** [comment]
Re-opening ticket as we still want to clean up `Jenkins.groovy`

## Task

- [ ] `content-build` cleanup of `jenkins.groovy` where applicable (be mindful of [Jenkinsfile.content](https://github.com/department-of-veterans-affairs/content-build/blob/master/Jenkinsfile.content) to not interrupt flow)
- [ ] `vets-website` cleanup of `jenkins.groovy` where applicable

**Comment by oseasmoran73** [comment]
Closing ticket as recent PRs have been merged
