### ISSUE TITLE
[VAMC] Update all Drupal Detail page URL alias to remove the "va-" and update to match standards [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#33806]
## User Story
As a VHA Digital Media web manager, the URL alias pages must not have va- prior to any page name, so a urls meet standards and do not cause any issues in cookies or redirects. 

## Goal
Remove tech-debt for all VAMC web pages

## Resources - Tools - Documentation
TBD

## Tasks
- [x] Remove all alias instances of "va-" from original naming inheritance.
- [x] If the pages are key health services or top task, you must inform PM prior to publishing so he may submit any redirects needed.
- [x] Confirm menu selections do not reference the "va-" from the alias.

## Acceptance Criteria
- [x] All va- are removed and do not show up in alias view.

**Comment by ltrombley** [comment]
Task #33806 - Update all Drupal Detail page URL alias to remove the "va-" and update to match standards [BA]  - is Complete and moved to Validate.
