### ISSUE TITLE
[FE] Enable BTSSS Link in production

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#33808]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

Enable existing BTSSS link on produciton.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Remove conditional statement that hides BTSSS link in production
- [x] Enable skipped tests for BTSSS Link

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
