### ISSUE TITLE
Remove content build fixtures tests and all instances of <fieldAdminstration>

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33811]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be able to filter events offered by the VA and distinguish between which are static and which are recurring events. 

## Related Information 
[Pull Request](https://github.com/department-of-veterans-affairs/content-build/pull/828) 

## Description
- We need to remove content build fixtures tests along with all instances of `fieldAdministration` in support of the Outreach and Events MVP work being preformed.  

## Tasks
- [x] We need to remove content build fixtures tests along with all instances of `fieldAdministration`. 
- [x] Ensure change is functional and tested local/staging env.
- [x] Coordinate with CMS Team on change management
- [x] Close ticket when completed 

## Acceptance Criteria
- [ ]Content build fixtures tests along with all instances of `fieldAdministration` are removed.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/842

**Comment by kelsonic** [comment]
PR merged, will go out with daily on Monday

**Comment by brianalloyd** [comment]
Closing this ticket out in support.
