### ISSUE TITLE
VA Payment History Does Not render on Timeout

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33813]
## Issue Description
The `https://www.va.gov/va-payment-history/payments/` page does not render and throws an error when `https://api.va.gov/v0/profile/payment_history` times out.

We need to add another set of checks to see if the `payments` value is undefined, and if so, display an error message to the user.

---
## Tasks
- [ ] ViewPaymentsList.jsx handles payment fetching timout gracefully
- [ ] User is presented a friendly error alert when something goes wrong

## Acceptance Criteria
- [ ] ViewPaymentsList.jsx does not error when payments api times out
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@alyssagallion This can be removed as not completing.  Not our field.
