### ISSUE TITLE
Update labels for Midpoint Review and Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33818]
## Issue Description
The Design Intent gh template and the Midpoint Review gh template have incorrect labels.

---
## Tasks
- [x] Add the `design-intent` label to the [Design Intent github template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman%2C+allison0034&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)
- [x] Add the `midpoint-review` label to the [Midpoint Review github template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D)
- [x] Remove the `content-ia-team` label from the Midpoint Review gh template
- [x] Update the Design Intent url link on the following pages:
   - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html
   - https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities
- [x] Update the Midpoint Review url link on the following pages:
   - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html
   - https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities

## Acceptance Criteria
- [x] VFS teams draft Design Intent and Midpoint Review requests with the correct labels

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chaseakirby** [comment]
Created pull requests and draft updated Platform Website pages ready for new link when PRs approved.

**Comment by shiragoodman** [comment]
reopening this bc the links on Platform Website did not get updated.

**Comment by chaseakirby** [comment]
Thanks Shira! Updated links are live on Platform Website per AC.

**Comment by chaseakirby** [comment]
@shiragoodman Would you mind checking out the Midpoint Review template?
Here is the current template and the label appears correct. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/midpoint-review.md
Here is the new link with midpoint review in the url but it doesn't populate in the list of labels. https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+midpoint-review%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D
Do you see anything that I may have missed?

**Comment by shiragoodman** [comment]
@chaseakirby I think the issue was that the 'midpoint-review' label did not yet exist in GitHub, so I can to create it. The link should be working now: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+collab-cycle-review%2C+midpoint-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D

**Comment by chaseakirby** [comment]
Confirmed the link now works as expected. Closing ticket as AC are met.
