### ISSUE TITLE
[Onboarding / AWS Access] Update AWS approval process to use GitHub or Slack group names 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#33823]
## Description
The AWS approval process current tags a single person (Mike Chelen) and creates a potential bottleneck and/or reduced visibility. This process should be modified to use GitHub or Slack group names instead. 

## Background/context 
[Onboarding process](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools) documentation (with links to other useful resources)
[Approve AWS access](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access) documentation

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Update [Onboarding process](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools) with new GH team group @department-of-veterans-affairs/operations-aws-approvers 
- [x] Update [When to grant access](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#When-to-Grant-Access) to include info about AWS admin
- [x] Update [Approval process](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access#Approval-process) OCTO-DE doc with guidelines for AWS admin

## Acceptance Criteria 
- [ ] Updates have been performed and communicated to Operations and OCTO-DE staff
