### ISSUE TITLE
[Design] My VA - Payment Information: Implement design considerations and finalize

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33827]
## Background
After completing our design intent we need to finalize design details for our MVP
Link to Design Intent Feedback - TBD

## Tasks
- [x] Follow up with Design stakeholders on [design feedback - ticket 34047](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34047)
- [x] Follow up with a11y stakeholders on design feedback
- [x] Finalize design details for MVP 
- [x] Transfer documentation to GH

## AC
- [x] Finalized MVP designs and FE documentation exist in GH

**Comment by andaleliz** [comment]
putting a 5 on this since I have no idea how much work/feedback will come out of the design intent

**Comment by hdjustice** [comment]
@andaleliz - Ticket #34047 was created for the feedback.  There wasn't much, but Tressa does have meetings with content/IA and Platform to discuss the design options.

**Comment by tressaellen** [comment]
@andaleliz - there are meetings with platform and accessibility this coming week (you should have the invites). Likely this will just result in us submitting an experimental design ticket.

**Comment by tressaellen** [comment]
The sketch file has been updated and the [documentation is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md). I didn't put screenshots in since there are so many parts that are in flux.
