### ISSUE TITLE
Create new Collaboration Cycle Calendar with an Oddball domain

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33821]
## Issue Description
The current Collaboration Cycle Calendar is owned by Adhoc. The Product Support PM needs to work with Adhoc anytime the calendar settings and/or permissions need updated. The team would like to create an Oddball calendar instead so maintenance is simplified.

---
## Tasks
- [x] Create new calendar
- [x] Transfer events from Adhoc to Oddball calendar
- [x] Update Calendly settings to use Oddball calendar
- [x] Update Platform Website Resources page
- [x] Contact Analytics & Insights team about transferring their office hour events
- [x] Review internal guidance and ensure all references to the adhoc calendar are replaced with the oddball calendar

## Acceptance Criteria
- [x] We successfully transition to the new oddball calendar
- [x] There are no disruptions for VFS teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@seanasewell contact Michael Fleet for support.

**Comment by f1337** [comment]
Turns out, I had created the calendar some time ago. I added @seanasewell to the list of folks who can manage it. We should probably put this link somewhere for future posterity:

https://calendar.google.com/calendar/u/0?cid=Y183aXVyc3QybWszaGRoZnV0bzV1N2xlbWdia0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by shiragoodman** [comment]
hey @f1337  - did you also add me as one of the folks who can manage it? Looks like I can make changes.

**Comment by shiragoodman** [comment]
@michelle-dooley this is a reminder to please share the Analytics office hours with the new calendar. See this thread in Slack for more details: https://dsva.slack.com/archives/CJRQ85PQB/p1642115737094500
