### ISSUE TITLE
Swap out videos in vaccine CLP-HOLD FOR WEEK OF 12/20

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33832]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Robert Bonner
Ronald Pipkins

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [x] New ticket created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks @lunascoop I published and will create a new ticket for two weeks now.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
