### ISSUE TITLE
[Design] My VA - Payments Information: Work with Content on Payment Information section on va.gov

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33839]
## Background
With the Design Intent completed, we should start working with Content on getting things reviewed and approved.

## Tasks
- [x] Submit Content tickets as needed for review - Ticket [#34015 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34015)submitted
- [x] Update designs based on Content feedback
- [ ] Create/update copy documentation, if needed

## Acceptance Criteria
- [ ] Content feedback is implemented across initiative documentation in GH

**Comment by andaleliz** [comment]
We discussed this in office hours and decided on the following changes, which are now all reflected in [the Sketch files](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6) (I have not updated the mural board yet).

- Update **Payment information** heading to **Benefit payments and debts**
- Update the alert copy from a single link to improve clarity about where the user would go if they clicked the link, and to align with other similar CTAs on VA.gov. The new copy is: You have 3 outstanding debt. [Manage your VA debt]
- Update the card copy to use active voice. It now reads: We deposited [$$] in your account ending in [acct] on [date].

@hdjustice can you make a separate ticket for the copy documentation please, since I'm out for the rest of this sprint and won't get to it today? There can be one ticket for this and onsite notifications. Thank you!

**Comment by hdjustice** [comment]
@andaleliz @Samara-Strauss I just had a thought as I was creating test cases.  Since the "Claims & appeals" section uses an ampersand ("&"), should we include that in the new name of "Benefit payments and debts" (Benefit payments & debts)?  This would keep the page consistent, in my thought.

**Comment by tressaellen** [comment]
Sorry - I know this is closed - but I wanted to post this here while I'm thinking about it. Do we need to work with content on the 'You have 2 new messages' alert now as well to be plain text + a link? It seems like all of the alerts should be consistent structure-wise.![Screen Shot 2021-12-28 at 1.26.25 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/bf1e0b38-390f-48c3-9d84-734abd79a4f9)

**Comment by andaleliz** [comment]
@tressaellen and @hdjustice yes! I think so in both cases.

@DanielleThierryUSDSVA, two questions for you:

1. Do you agree that the `You have two unread messages` link in Tressa's screenshot above should now read: "You have 2 unread messages. [Read your messages on My HealtheVet]" to improve clarity about where users are going?

2. Should we use an ampersand in "Benefit payments & debts" or should we update the claims section to remove the ampersand and instead say "Claims & appeals"?  I'm going to guess the word `and` is more plain language than the symbol `&`.

Thanks!

**Comment by hdjustice** [comment]
Adding to the 2 questions above:

1. What is the best language to use for when the user has not received payments in the last 30 days (line of text in place of payment info block)?
      - Suggestion "You have not received payments in the last 30 days"

@tressaellen @andaleliz - Tressa will be so kind to attend Content office hours on Thurs morning 1/6.

**Comment by DanielleThierryUSDSVA** [comment]
For above:

You haven't received any payments in the past 30 days.

**Comment by hdjustice** [comment]
Great! thank you so much @DanielleThierryUSDSVA !

**Comment by tressaellen** [comment]
@DanielleThierryUSDSVA was also super helpful and clarified the following questions. 

> 1. Do you agree that the `[You have two unread messages]` link in Tressa's screenshot above should now read: `You have 2 unread messages. [Read your messages on My HealtheVet]` to improve clarity about where users are going?
2. Should we use an ampersand in "Benefit payments & debts" or should we update the claims section to remove the ampersand and instead say "Claims & appeals"?  I'm going to guess the word `and` is more plain language than the symbol `&`.

1. The messages link needs to be updated to 'You have 2 unread messages. [View your messages]'
2. We should not use an ampersand, so it should read 'Benefit payments and debts'. I'm assuming this should then also update the 'Claims & appeals' to 'Claims and appeals'. Is this correct @DanielleThierryUSDSVA ? 


Thanks again for all your help!

I'll add these updates to the documentation.

**Comment by andaleliz** [comment]
@tressaellen I know you said you were going to add these updates to the documentation, but actually both of these last changes aren't part of the payment or notification work, since they're updates to existing sections of my VA. I don't think it makes sense to capture them in the https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md. Is there another doc you had in mind?

The changes are so small I also think they could be captured in the issue description for the FE work itself.

I'll finish updating sketch files tomorrow.

**Comment by tressaellen** [comment]
I think we're fine to just capture them in FE tickets since they are so small!

**Comment by andaleliz** [comment]
@hdjustice are you ok with that? If so, we can close this out.

**Comment by hdjustice** [comment]
@liz Yes, totally fine with me!  Thanks!
