### ISSUE TITLE
[PM] My VA - Payments Information: Create test cases in TestRail

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33834]
## Background
With design finalized and use cases/rules documented, a list of test cases needs to be created.
Reference [My VA 2.0 Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md) for examples
Reference [Getting Started](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/getting-started.md) for TestRail access

## Tasks
- [x] Create test cases based on use cases

## Acceptance Criteria
- [x] Use cases will be created - [Link to Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-PaymentInfo.md)
- [x] TestRail test cases created - [Link to TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3308&group_order=asc&display_deleted_cases=0)

**Comment by hdjustice** [comment]
@tressaellen @andaleliz - I created this **[Use Case document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-PaymentInfo.md)**, using the old My VA 2.0 test case document as a reference (most of the use cases were already basically there).  Whenever there is a moment (not necessarily today even), please take a look and let me know your thoughts.  I tried to think of the various scenarios and what we would be linking to, based on the **[Round 4 design and list of use cases in the Mural board.](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=u5ad49c107baa41137f271007)**

**Comment by andaleliz** [comment]
Hey Heather - thanks for sharing this with me. Generally, it looks like the appropriate level of detail but I have _no idea_ if any of these are correct/valid for this work or what the expected outcome should be.  E.g. - no clue what happens in My VA for LOA1 users. This makes me realize I have a lot of gaps to fill before Tressa's departure! I'll follow along closely so I can learn.

@tressaellen if you need help creating mock-ups for these, just lmk. Happy to jump in.

**Comment by tressaellen** [comment]
Sorry @hdjustice I still haven't had a second to look at this - I'll take a look this afternoon!

**Comment by hdjustice** [comment]
No Worries!  I will be looking for actual users today and plug them in where it makes sense for testing.

**Comment by tressaellen** [comment]
- If a user is LOA1 then we will handle it the same as the previous test case - we won't show the payment information section. So it should show the screenshot that is already linked. 
- We need to add a test case for the 'Request travel reimbursement' link since it's a new link - even though it's in the health care section. 
- For 'User has payments made to them, but there have been no payments in more than 30 days' - We need to still show the section here and just state that there are no upcoming payments in the next 30 days. The exact copy will be figured out with content. 
<img width="1019" alt="Screen Shot 2021-12-21 at 1 50 21 PM" src="https://user-images.githubusercontent.com/58752772/146995882-aeb2149e-f02d-406f-8e42-4044ac21b9be.png">
- I'm still trying to figure out if it's possible for users to have debt and no payments - so I will keep you posted on that because that will change a few of these!
<img width="1019" alt="Screen Shot 2021-12-21 at 1 50 21 PM" src="https://user-images.githubusercontent.com/58752772/146995882-aeb2149e-f02d-406f-8e42-4044ac21b9be.png">

Otherwise it looks great to me! Awesome work Heather! These are really hard to put together!

**Comment by hdjustice** [comment]
Thanks @tressaellen !!  I made some updates to align with your feedback.  The only question I have is on the item below: 

>For 'User has payments made to them, but there have been no payments in more than 30 days' - We need to still show the section here and just state that there are no upcoming payments in the next 30 days

I know you stated we would figure out the exact copy, but I want to make sure we are consistently talking about Payments made or Payments upcoming. 
- If we are going to show Payments Made to the user, but they do not have any made to them recently, then maybe we should say something like You have no recent payments, or You have not received any payments in the last 31 days.  
- If we are making this statement about Upcoming Payments, then they payment details we show should be for upcoming to be consistent with the messaging.. 

unless I am completely misunderstanding (which is totally possible).

**Comment by hdjustice** [comment]
Follow up questions: 
- If a user has NEVER had payments made to them, then we will not show the section?  
- If a user has had payments made to them, but perhaps it has been a year since the last one, do we show the section?
     - Is there a cut-off for the last payment made, that would determine whether we show that section?

**Comment by tressaellen** [comment]
> I know you stated we would figure out the exact copy, but I want to make sure we are consistently talking about Payments made or Payments upcoming.

@hdjustice very great point - I'll pass this along to Liz who is working on content. 

> Is there a cut-off for the last payment made, that would determine whether we show that section?

Totally - I'm kind of assuming it'll be like a one year cut off, but it's definitely something we could include in research. @andaleliz do you mind adding a question about this when we start on the conversation guide?

**Comment by andaleliz** [comment]
Absolutely - I have this in one of the tasks in the guide. It may come up organically, so this an "if needed" reminder to myself to ask about it:

>I'm curious about timing for financial information. How long after a payment is made to you or a debt is added do you need to see that information? For example, say you used your education benefits ago and the last payment you received was in January 2021. Would you still want to see that?

**Comment by hdjustice** [comment]
Draft Use cases and Test cases created in preparation for Midpoint review

**Comment by Samara-Strauss** [comment]
Let's leave this as done, but I do need to review this to make sure we're good to go. That'll have to wait until next week.

**Comment by hdjustice** [comment]
Thank you @Samara-Strauss !  There is a question or two that I am not clear on, so I would definitely appreciate the feedback when you review.  I didn't think to leave the ticket open until after you reviewed. I apologize and will remember that next time.

**Comment by Samara-Strauss** [comment]
### Test cases for "LOA1 user"

- For LOA1 use cases, Tze can just create a user and not verify their identity, or use an existing LOA1 user he has already created.

### Test cases for "Benefit payments and debts"

> NOT SURE ON THIS ONE User DOES have outstanding debt, AND DOES NOT have a payment made to them in the last 31 days

You can take this out. This can't happen. People can only have debts if they receive payments from the VA. Debts are a result of over payments.

As for users, you can probably start filling in some of these. Let me know when the users are updated!

**Comment by andaleliz** [comment]
>People can only have debts if they receive payments from the VA. Debts are a result of over payments.

That makes sense to me, but couldn't a person owe the VA money for a more than 31 day period of time after their payments have stopped?

**Comment by hdjustice** [comment]
@Samara-Strauss I updated the **[test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-PaymentInfo.md)**  with users now.  Finally got a user with debt, WOOT!  
I did take that one test case out (no payments, outstanding debt), however Liz does make an interesting case for a possible scenario.  Let us know your thoughts.  Thanks!

**Comment by Samara-Strauss** [comment]
Awesome, this is great! Really excited to see this stuff once it's on staging :D

**Comment by Samara-Strauss** [comment]
> That makes sense to me, but couldn't a person owe the VA money for a more than 31 day period of time after their payments have stopped?

This is a good point, and I don't know that we have accounted for this in the designs. Can you check in with @tressaellen about this?

**Comment by hdjustice** [comment]
@Samara-Strauss This [**sketch file**](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6/a/JnqdWY9) accounts for the situation.

**Comment by Samara-Strauss** [comment]
> This sketch file accounts for the situation.

Thank you for this! Looks good to me.

Can someone refresh my memory on what triggers this section? I thought it was if someone had received a payment in the last 30 days. Is it that OR if someone has an outstanding debt? Or is it something else?

> I believe we would need to have a staging user set up with this scenario.

You are right, and sorry for the error on my part yesterday.

> I suggest something like "You have not received any payments in the last 30 days".

I agree -- the payment shown is reflecting a recent payment, not a payment that is going to happen in the future AFAIK.

**Comment by hdjustice** [comment]
>Can someone refresh my memory on what triggers this section? I thought it was if someone had received a payment in the last 30 days. Is it that OR if someone has an outstanding debt? Or is it something else?

It was my understanding that if we are able to pull a payment history for the user, the section will display.
There was mention (early on) that if there have not been any payments for over 30 days, then do not display the section.  I believe the possibility of having debt without recent payments had us re-thinking that and aged payment limit.  @tressaellen or @andaleliz might have a different insight.

**Comment by tressaellen** [comment]
Hello! Yes - @hdjustice is correct. If we can pull a payment history AT ALL for the user the section will display. Currently a users cannot have debt unless they've received edu or comp & pen payments (all within payment history), so that should work for both the use case of a recent payment and if a user has debt. 

cc/ @Samara-Strauss @andaleliz

**Comment by Samara-Strauss** [comment]
Got it. So this section shows if someone has ever received payments from the VA, and we might revisit that logic once copays is live. Thank you for clarifying!
