### ISSUE TITLE
Remove SSO Modal From Announcements

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33831]
## Issue Description
Remove SingleSignOnInfoModal.js and all all relative code from Announcements

---
## Tasks
- [ ] Remove SSO Modal From Announcements

## Acceptance Criteria
- [ ] SSO Modal No Long Exists
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
