### ISSUE TITLE
Update PDF link on TSGLI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#33849]
## Issue Description
Currently we have a broken link on the [TSGLI](https://www.va.gov/life-insurance/options-eligibility/tsgli/) benefits page for Appeal Form SGLV 8600A. Stakeholder Steve Fital sent us the new PDF to update the link with.

New PDF: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8600A_ed2021-11.pdf

## Tasks
- [x] Update link on TSGLI page (Selina)
- [x] Review and publish (Randi)
- [x] Alert stakeholder that change is live (Randi)

## Acceptance Criteria
- [x] Link no longer broken on live site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.
Traumatic Injury Protection (TSGLI): http://preview-prod.vfs.va.gov/preview?nodeId=768

**Comment by RLHecht** [comment]
Thanks, @lunascoop I published this. Moving to validate.
