### ISSUE TITLE
Auth Profile: Sprint 63

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#33860]
# Auth Profile: Sprint 63 Dec 15-28

## PTO/OOO/Unavailable
Samara: 12/23-24; 12/29-31
Heather: 12/23-24; 12/31
Marci: 12/23-27; 12/30-31
Tressa: 12/24; 12/29-31
Liz: 12/24-31
Christina: 12/23-31
Taylor: 12/24; 12/31
Lihan: 12/10-12/25
Tom: 12/27-31
Adam: 12/27-28

## Onboarding

- [x] Tom - #34115

### PM - Marci
- [x] #33754

### BE - Lihan
- [x] #34250

### PM - Marci - Tickets to Create
- [ ] #34247 (Content request) `unplanned - getting a jump on things` - ticket created
- [ ] #34290 (Public Websites request) `unplanned - getting a jump on things` ticket created 
- [ ] #34242 (ticket created for launch) `unplanned - getting a jump on things` ticket created 

### Design - Christina
- [x]  #33438 
- [x]  #34187 
- [x]  #34185
     - [Checkbox group ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/604)
     - [Radio button group ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/605)

### FE - Adam
- [x] #31685
- [x] #32768
- [x] #32771
- [ ] #32775 - Moving to Sprint 64 but may need to wait for BE work

### Content Requests - Liz monitoring
- [ ] #33007

<hr>

### PM - Marci
- [ ] [FE] #33066 -  `rolled from Erik; Sprint 61`  - Monitoring [Pull request #19516](https://github.com/department-of-veterans-affairs/vets-website/pull/19516) before validating.  If this issue does not close this ticket, we will need our own FE ticket to handle.

<hr>

### Design - Liz
- [x] #33737
- [x] #33734

<hr>

### PM - Marci 
- [ ] ~~Submit for 508 review~~ - `blocked` still have 4 outstanding 508 issues

### Design -  Liz
- [ ] [Design] #29582 - `Blocked - Content work; Liz is monitoring`

### Backend - Trevor Bosaw
- [x] #34382
### Backend - Lihan 
- [x] #34403

**Comment by Samara-Strauss** [comment]
@MarciMcGuireGCIO 

- #34242 does not need to be in this list/checked off since it is a ticket you created for later.
- Is #34247 done or not?
- #34290 should also not be checked off since it's not done, but you can move it to next sprint since it of course couldn't be finished because of the code freeze.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss I listed these as tasks for me to create the tickets so I had a place to keep track this sprint .  The check mark was only intended to note that I created the tickets, not that the work requested in the tickets had been completed.  

I didn’t list these on the Sprint report because they are not being worked on yet.
