### ISSUE TITLE
Show only unique facilities for zero debt balances

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#33868]
## Issue Description
If a user has a facility listed twice within their profile we are passing back zero debt statements for each time listed

---
## Tasks
- [ ] Uniquely fetch zero balance facilities by id

## Acceptance Criteria
- [ ] Only one zero balance for each facility
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
