### ISSUE TITLE
Use only treatment facilities for vista account id

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#33874]
## Issue Description
Using extra facilities that aren't treatment and it's breaking our vista account calculation

---
## Tasks
- [ ] Check facilities in `vha_facility_hash` against treatment facility range

## Acceptance Criteria
- [ ] Only treatment facilities are calculated for vista account ids
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
