### ISSUE TITLE
Adjust COE Breadcrumbs and Their URLs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#33901]
## Background
We need to ensure that the breadcrumbs are updated so that Veterans can have a better idea as to where they are in the process .

## Considerations
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

NOTE: This will require creating a new application in vets-website for the status page to live in

## Tasks
- [x] Update the breadcrumb text and urls

## Acceptance Criteria
- [x] Breadcrumbs are updated
- [x] A PR has been requested for merging
