### ISSUE TITLE
[BE] Add team members to the features toggle admin list

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#33919]
## Description
Add Check-in experience team members(if access is necessary) to the features toggle list in staging and production environments.

## Tasks
- [ ] Add emails to the settings.yml file in the feature toggles section
- [ ] Get users verified with ID.me

## Acceptance Criteria
- [ ] Team members are able to turn features on and off in the desired environments

**Comment by randomsync** [comment]
please add `ggupta@kindsys.us`

**Comment by dcgoodwin2112** [comment]
please add `dan.goodwin@civicactions.com`. Thanks!

**Comment by acrollet** [comment]
Please add `adrian.rollett@agile6.com` - thanks!
