### ISSUE TITLE
All-VA Dashboard - Data QA

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#33935]
## Issue Description
As we roll out an MVP All-VA dashboard, we need to make sure that our data is accurate and trustworthy. 

---
## Resources
- [WIP All-VA Dashboard](https://va-gov.domo.com/page/1030131175)
- [All-VA Dashboard: Data QA Cheat Sheet](https://docs.google.com/spreadsheets/d/1B-U8_35c8CaETxz2iAJ2L-LxawIDXNvajpd9OlEr9GY/edit?usp=sharing)

## Tasks
- [x] Verify that data formats are correct
- [x] Confirm the data is what is expected (does the info collected measure what it's supposed to measure?)
- [x] Identify & document invalid values

## Acceptance Criteria
- [x] The production All-VA Dashboard in Domo has accurate and trustworthy data and is ready to be shared with stakeholders.
---

**Comment by jennaouellet** [comment]
Data QA for the VA.gov wide dashboard is complete! No issues were found other than line #31 which has since been corrected. QA sheet has been updated.

**Comment by chloedotbrown** [comment]
Hi @jennaouellet – sorry this took a minute! Is it possible to re-QA lines 30 and 31 on the [spreadsheet](https://docs.google.com/spreadsheets/d/1B-U8_35c8CaETxz2iAJ2L-LxawIDXNvajpd9OlEr9GY/edit#gid=874229076)? I worked with Brian to create a [new datasource](https://va-gov.domo.com/datasources/42d302a8-0483-4e6d-a868-fcf28e8c92f5/details/overview) for this that's scoped by user instead of hit, and that uses a url rather than event for managing claims, since it looks like the one we were using was sort of new.

Let me know if you have any questions and thanks again!

**Comment by jennaouellet** [comment]
@chloedotbrown No problem, happy to help! I did another pass on those last two and all looks good in BQ/GA. let me know if any other changes are made and I'll hop back in again.

**Comment by chloedotbrown** [comment]
Amazing, thank you @jennaouellet! No other changes pending, so I'll go ahead and move this back over to "Done."
