### ISSUE TITLE
[BE] vets-api CheckIn: Simplify Serializer

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#33936]
## Description
The current AppointmentDataSerializer has become quite large and at least a common address object can be extracted out and serialized separately. 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [ ] update code, specs
- [ ] test locally with vets-website

## Acceptance Criteria

- [ ] Deployed and tested on staging.
