### ISSUE TITLE
All-VA Dashboard - Design QA

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#33937]
## Issue Description
As we roll out an MVP All-VA dashboard, we need to make sure that our dashboards are usable.

---
## Resources
- [WIP All-VA Dashboard](https://va-gov.domo.com/page/1030131175)
- Past example tickets – recommend reading through comments:
  - [Design QA for Forms KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24202)
  - [Design QA for Search KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25870)
  - [Design QA for Content KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25871)

## Tasks
Use the `Participant Tester` account in Domo to QA for the following:
- [x] All links should be clickable and correct
- [x] All tooltips are consistently formatted and accurately describe their metric
- [x] Directionality of change arrow/colors is correct for the metric
- [x] All titles and text fully visible in the dashboard layout
- [x] Filters should work properly
- [x] Any feedback is documented

## Acceptance Criteria
- [x] The production All-VA Dashboard in Domo is usable and follows the design as close as possible
---

**Comment by jonathan-epstein13** [comment]
### Jonathan QA

Test | Expected Behavior | Actual Behavior | Pass/Fail
-- | -- | -- | --
Dashboard title | Text fully readable, without errors | Text fully readable, without errors | Pass ✅
Date filter | Every chart gets filtered for date and group by settings are changed | Avg Satisfaction score, Total Logged in users, percent logged in,forms available online, Form comp rate,VAOS user comp rate,Successful VAOS submissions by type, highest/lowest ratings,search refinements by session,search clicks by position, percent of users who logged in,doesn’t change for Month, Quarter and Year. | Fail ❌
Section titles | Every section title & subtitle are spelled correctly | Every section title & subtitle are spelled correctly | Pass ✅
Chart titles | Every chart title is fully readable, without errors, relevant to chart | Facility Detailed Views->Facility detailed views | Fail ❌
Chart descriptions | All chart descriptions are disabled, so nothing appears when hovering over title | Card titles appear when hovering over them. | Fail ❌
Hover text | All hover text "makes sense" and is spelled correctly | When you filter, some hover text might be confusing when it says “….during most recent month” because you can filter by quarter and year. | Fail ❌
Annotations | Every annotation "makes sense," is free of errors, and visible within text box | Search click thru rate->Search click-thru rate. | Fail ❌
Text box formatting | Every annotation and section title box shows all text, does not generate scroll bar | Every annotation and section title box shows all text, does not generate scroll bar | Pass ✅
Card interactions – filters | Clicking data point does not filter other cards | Clicking any graphic visual, populates a filter above next to “filter views” not affecting any visual, but might cause confusion. | Fail ❌
Card interactions – card detail | Clicking chart title opens card in new tab | "Total profiles saves" opens up to a new tab, but not in a new window. | Fail ❌
Display settings – multi-value gauges | Date grouping ("by month") appears under each title | Date grouping ("by month") appears under each title, except titles mentioned above in “Date filter” | Fail ❌
Display settings – summary numbers | All tables, bar charts, and filled gauges show date range | “Bar” charts in task completion section,Facility Detail Views, Resource and support pageviews, manage all claims and appeals views, individual claim status views-don’t have date range. | Fail ❌
Related cards | In card detail view, all related card previews have been deleted | Can see “Data Set Name”, “updated…” Page “last synced…”, the owner, # of views, # of people with access, 0 people added this to favorites. | Fail ❌
Appendix | No charts or notecards appear in appendix below dashboard | No charts or notecards appear in appendix below dashboard/there is no appendix section | Pass ✅


</body>
</html>

**Comment by jonathan-epstein13** [comment]
@chloedotbrown the above QA is what I was able to do, but based on my initial interpretation, so their might not be this many "Fails" with most of these. Just did my best to thoroughly go through the WIP - OCTO-DE Numbers Dashboard.

**Comment by pavanhothi** [comment]
<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pavan QA</h3>

Test | Expected Behavior | Actual Behavior | Pass/Fail
-- | -- | -- | --
Dashboard title | Text fully readable, without errors | Text fully readable, without errors | Pass ✅
Date filter | Every chart gets filtered for date and group by settings are changed | Every chart gets filtered for date and group by settings are changed | Pass ✅
Section titles | Every section title & subtitle are spelled correctly | Every section title & subtitle are spelled correctly | Pass ✅
Chart titles | Every chart title is fully readable, without errors, relevant to chart | Every chart title is fully readable, without errors, relevant to chart | Pass ✅
Chart descriptions | All chart descriptions are disabled, so nothing appears when hovering over title | Card titles appear when hovering over them | Fail ❌
Hover text | All hover text "makes sense" and is spelled correctly | Some hover text may be confusing when it says “….during most recent month” when filtered by quarter or year, otherwise looks good | Fail ❌
Annotations | Every annotation "makes sense," is free of errors, and visible within text box | Every annotation "makes sense," is free of errors, and visible within text box | Pass ✅
Text box formatting | Every annotation and section title box shows all text, does not generate scroll bar | Every annotation and section title box shows all text, does not generate scroll bar | Pass ✅
Card interactions – filters | Clicking data point does not filter other cards | Clicking data point does not filter other cards | Pass ✅
Card interactions – card detail | Clicking chart title opens card in new tab | "Total profiles saves" opens up in the current tab as opposed to in a new tab | Fail ❌
Display settings – multi-value gauges | Date grouping ("by month") appears under each title | Date grouping ("by month") does not appear under the following: Avg. Satisfaction score, forms available online, Form completion rate, VAOS user completion rate, Successful VAOS submissions by type, Highest experience ratings, Lowest experience ratings, Search refinements by session, Search clicks by position, Percent of users who logged in, Users managing their claims and appeals, Users viewing individual claims | Fail ❌
Display settings – summary numbers | All tables, bar charts, and filled gauges show date range | Bar charts in Task Completion section, Facility Detail Views, Resource and support pageviews, Users managing their claims and appeals, Users viewing individual claims do not show date range | Fail ❌
Related cards | In card detail view, all related card previews have been deleted | In card detail view, all related card previews have been deleted | Pass ✅
Appendix | No charts or notecards appear in appendix below dashboard | No charts or notecards appear in appendix below dashboard | Pass ✅


</body>
</html>

**Comment by chloedotbrown** [comment]
@jonathan-epstein13 and @pavanhothi – big thanks to you both for such a thorough review! I've added my notes below for changes made, limitations, and places where the issue was an acceptance criteria I should have written more clearly. Please look over and let me know if you have any questions. If at least one of you is able to re-QA the places where changes were made so we can get to an official clean bill of design-health, that'd be great!

### Changes made
🔁 _Please re-QA (at least 1 person)_

- **Date filter:** "Graph by" functionality for quarter and year settings. 
  - Added aggregation to pre-computed fields so that they'll calculate correctly when date units are changed: 
    - Total logged in users (both versions), Percent logged in (both versions)
  - Removed `month_name` from Tooltip fields for all line and bar charts with date axis, since it was keeping unit changes from re-calculating correctly. This wasn't flagged in QA, but discovered it when testing other changes.
- **Chart titles:** Corrected "Facility detail pageviews" capitalization. 
- **Hover text:** This is a good point – I wrote the hover text (and % change suffix) on the multi-value gauges to support a month-only view, since that's probably the way it will be viewed most often. But we should keep it flexible to support quarter/year comparisons, especially since the "Graph by" feature can't be disabled. I've updated hover text and period-over-period comparison wording throughout.
- **Annotations:** Added hyphen.
- **Card interactions - card detail:** Corrected interaction setting for "Total profile saves."

### Domo limitation
⚠️ _No known solution within Domo, but will add it to our list of BI tool limitations_ 
- **Card interactions - filters:** I share this concern about potential confusion – unfortunately, I'm not seeing anything in Domo help or forums about how to completely disable it beyond what we've already done. It may not be possible (though if either of you can find anything out, please let me know!).

### AC issue
✍️ _No updates needed to dashboard, but will edit acceptance criteria for Design QA to be clearer in the future._

- **Date filter:** No changes – cards not supposed to change when "Graph by" units change because they do not include a date grouping component (will modify AC in "expected behavior" for future QAs): 
  - Avg. satisfaction score, Forms available online, Form comp rate, VAOS user comp rate, Successful VAOS submissions by type, highest/lowest ratings, Search refinements by session, Search clicks by position
- **Chart descriptions:** This is my fault, I wrote the AC incorrectly! Acceptable state should be showing chart title when hovering, but no different text. Here's a screenshot of what it looks like when there's something written in the description section (either in Card Detail view or Analyzer):
     <img width="400" alt="Screen Shot 2021-12-21 at 3 21 59 PM" src="https://user-images.githubusercontent.com/45518242/147010590-71e026fb-1116-4372-a48a-d3e8c47229aa.png">
- **Display setttings - multi-value gauges:** I'm seeing the "by Month" for the gauge card types here (Total logged in users x2, Percent logged in). Are those not appearing in your view? The other cards aren't multi-value gauges, so thats alright that they don't have this feature – they don't use a date grouping in the visualization.
- **Display setttings - summary numbers:** This is another AC I should have written better... because the bar charts listed have a date X-axis, they are alright without the date range in the summary number. We do add this though for the bar charts without date ranges (i.e. VAOS by appt type, Search refinements by session, etc.)

**Comment by pavanhothi** [comment]
@chloedotbrown just got done doing the QA of the areas where changes were made, and all looks great! Didn't find anything that was off or confusing or shouldn't be there. Also, I checked again and confirmed that I am seeing the "by Month" for the gauge card types (Total logged in users x2, Percent logged in).

**Comment by chloedotbrown** [comment]
Awesome, thank you @pavanhothi! I'll go ahead and close this ticket then - but if anything else comes up, we can always reopen.
