### ISSUE TITLE
Benefits and Memorials Discovery Epic Template

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3395]
# Discovery Epic Template

### Issue Title: Medical Device Tool

- Discovery -  [Medical Device Too](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool)

### Issue Description:

- **Problem Statement:** Millions of Veterans depend upon the VA for disability-related medical devices and their accessories. Today, Veterans are able to order prosthetic socks and hearing aid batteries, the two most commonly-ordered medical device accessories, through their respective VA forms (Form 2345 & 2346). There are a number of ways to request these medical devices today, through several different mediums and platforms, providing a disparate experience for Veterans. With the expected sunsetting of eBenefits, BAM2 seeks to match and expand the functionality of the platform on the VA.gov website.

- **Product Outline:** [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md)

Definition of done: 
- [x] Refined and documented understanding of the problem
- [ ] Documented takeaways
- [ ] Documented business goals
- [ ] Documented user goals
- [ ] Documented KPIs
- [ ] Documented MVP approach
- [ ] Documented high level requirements / constraints
- [ ] Readout and product kickoff occurred

Other Acceptance Criteria
- [ ] Discovery artifacts (personas, journey maps, synthesis, etc) complete and in GH
- [ ] Initial technical review and commentary filled out in GH
- [ ] Research, IA, and Content consultation complete
- [ ] Initial functional specs complete and in GH
- [ ] Product Outline filled out in GH
- [ ] Discovery readout presentation complete and in GH
- [ ] Charter circulated and in GH

Types of issues to consider including
- [ ] Document tech research
- [ ]  Create collateral to validate assumptions
- [ ] Recruit for user research
- [ ] Create user research brief / conversation guide(s)
- [ ]  Conduct user research sessions
- [ ]  Create research read-out
- [ ]  Document competitive analysis
- [ ]  Conduct stakeholder interviews and document meeting notes
- [ ]  Create Discovery readout and present to larger group
- [ ]  Start docs for business, product, tech requirements and constraints (specs)
- [ ]  Update Product Overview with status and new details## Suggested issues for consideration

**Planning activities**
- [ ]  Set up product folder in GitHub
- [ ]  Create launch checklist
- [ ]  Create Product Outline
- [ ]  Define problem, assumed user and business goals, and other assumptions (Product Outline)
- [ ]  Determine POCs, stakeholders, and implementation team (Product Outline)
- [ ]  Determine Discovery methods needed
- [ ] Determine user research methods needed
- [ ]  Determine what APIs and/or systems to investigate
- [ ]  Recruit for stakeholder research
- [ ] Recruit for user research
- [ ]  Determine ideal Discovery outputs and artifacts

**Discovery activities**
- [ ]  Conduct user research
- [ ]  Create stakeholder research guide
- [ ]  Conduct stakeholder research
- [ ]  Conduct API and/or systems reviews
- [ ]  Determine solution approach (collab with Content, IA, Research, Engineering, Design, Business, Product)
- [ ]  Conduct any other Discovery activities
- [ ]  Evaluate integration agreements/SLAs

**Output activities**
- Synthesize findings
- Update Product Folder name(s) and/or or IA (if necessary)
- Fill out known info in technical discovery guide
- Create functional specs skeleton w/known information and questions for further research
- Finish any other artifacts and store in GitHub
- Fill out initial info in Product Outline
- Create Discovery readout
- Schedule and present Discovery readout
- Create and send out Charter
