### ISSUE TITLE
[FE] Create liquid filter for array or object format of `fieldDateTimeRangeTimezone`

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#33951]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to be informed of upcoming information while browsing VA.gov. 

## Related Information 
[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1639140996475000)

![image](https://user-images.githubusercontent.com/12773166/145606358-a3c3075b-0608-4885-a3f4-99825b6e4efa.png)

![image](https://user-images.githubusercontent.com/12773166/145606368-eb01e54f-9cb6-488b-81b8-6505ea872f31.png)

## Description
- We need to migrate "promo" banners content from Vets-website into CMS for content maintenance. In support of this PW team needs to enable recurring data functionality on the FE to support CMS data structure.   

## Approach to Implement 
1. Create a liquid filter on the FE that supports BOTH the array and object format of `fieldDatetimeRangeTimezone `
2. CMS tests out this change in a review environment when switching to only array format of `fieldDatetimeRangeTimezone`
3. CMS merges in PR
4. Next content-build deploy would have the changes

## Tasks
- [x] Create liquid filter for `<fieldDateTimeRangeTimezone>` or `<fieldDates>`
- [x] Ensure change is functional and tested local/staging env.
- [x] Coordinate with CMS Team on implementation steps
- [x] Close ticket when completed 

## Acceptance Criteria
- [x] Filter is created and CMS is able to test properly in order to support recurring event content model  **This should be done post implementation of content build template**

**Comment by kelsonic** [comment]
Bumping to a 5 since it affects so many files

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/844 it's a dangerous one so i'm going to let it bake over the weekend and continue testing

**Comment by kelsonic** [comment]
PR merged, will go out with daily tomorrow

**Comment by brianalloyd** [comment]
Test, merged and validated. Closing ticket in support.
