### ISSUE TITLE
Update Midpoint Review guidance 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#33952]
## Issue Description
> 👋 Hi! I noticed in the [midpoint review objective section](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html), it states
> 
> > To confirm your prototype or mockup aligns with existing VA.gov patterns and standards and to ensure your product is ready for successful usability testing.
> 
> Our research isn't usability testing- rather it's an interview to evaluate how people understand the terminology and IA of the page. Does the midpoint review still apply in that case? If so, perhaps the review objective needs to be updated?

thanks for the question @andaleliz ! Midpoint Review is still applicable since you'll be putting _something_ in front of veterans to respond to... whether that be an actual working prototype that they interact with, or an interview to evaluate people's understanding of the terminology and IA. We want to ensure that what you're researching with Veterans is as close to the VA.gov standards as possible so your research results are valid. If you have a glaring standard issue in your research materials, it could invalidate the research results. 

I will take an action to get our Midpoint Review objective section updated. Thank you for bringing to our attention!

_Originally posted by @shiragoodman in https://github.com/department-of-veterans-affairs/va.gov-team/issues/33630#issuecomment-990166059_

## Tasks
- [x] Create a draft page under Documentation Drafts
- [x] Update the Midpoint Review Objective guidance on Platform Website to be inclusive of research beyond usability testing
- [x] Peer review with a Product Support teammate
- [ ] Update Midpoint Review Moderator script

## Acceptance Criteria
- [x] Platform Website guidance has been updated
- [x] Team has reviewed/approved the changes
- [ ] Moderator script is updated for future touchpoints

**Comment by andaleliz** [comment]
Thanks for your attention to this @shiragoodman! ❤️

**Comment by briandeconinck** [comment]
Note: Updated tasks in the issue description for consistency with #34616. Just want to keep myself honest!

**Comment by briandeconinck** [comment]
Proposed updated guidance [ready in a draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2041446457/Brian+-+Copy+of+Midpoint+review).

**Comment by briandeconinck** [comment]
[Draft update](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2062352416/Brian+-+Copy+of+Midpoint+Review+-+Moderator+Responsibilities) to the Midpoint Review moderator script ready. @shiragoodman this mainly impacts you since you're the one saying the words out loud!

**Comment by shiragoodman** [comment]
@briandeconinck I made 1 small comment (per your comment) and the rest looks good! 

FYI in the future, you don't need to create a "draft" copy since this is an internal doc.
