### ISSUE TITLE
[VSA / Ebenefits] connecting to LGY from staging-api.va.gov

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#33969]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We recently deployed code to staging that hits LGY's `sqa.services.lgy.va.gov:443`. Currently staging-api.va.gov is responding to our vets-website with a 503. This is the same problem we ran into on a Review Instance, and locally (when going through the staging fwdproxy). We were able to determine the local issue as a self-signed SSL cert problem:

```
log/development.log:5690205:2021-12-09 17:55:47.116275 E [11159:puma server threadpool 001 sentry_logging.rb:57] [[]] Rails -- SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate).
```

I opened a [platform support request ](https://dsva.slack.com/archives/CBU0KDSB1/p1639159467291300)and Demian suggested:
> ah, ok. that’s good to know. likely that cert will need to be added to the fwdproxy configuration then. I would put in an issue in the va.gov-team repo with the ops issue template, or contact @ Jesse House for some assistance in getting that into the Ops team workload, as it might not be an issue that the on-call support person would be able to handle in a short amount of time.

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 
Here's an error in Sentry if it helps: http://sentry.vfs.va.gov/organizations/vsp/issues/60009/events/6d206fc342564eada611993be012ac04/?environment=staging&project=3&statsPeriod=14d

---
## Tasks
- [x] We need help understanding what the problem is and possibly doing what Demian suggested in the PS request:
> you may need to get a public key or signing cert that allows fwdproxy to trust the cert that lgy is presenting

## Acceptance Criteria 
- [x] A signed in user on staging.va.gov can successfully get a 200 from this endpoint: (GET) https://staging-api.va.gov/v0/coe/status

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@RudyOnRails - Thanks for creating this. In order to properly prioritize the work that's needed, can you let us know what the current impact is? And/or what the sense of urgency is for getting this resolved? 

Also tagging the Operations team product owner @mchelen who may have add’l questions and guidance.

**Comment by RudyOnRails** [comment]
> @RudyOnRails - Thanks for creating this. In order to properly prioritize the work that's needed, can you let us know what the current impact is? And/or what the sense of urgency is for getting this resolved?
> 
> Also tagging the Operations team product owner @mchelen who may have add’l questions and guidance.

You're welcome Jesse.

The current impact is that the "Loan Guaranty - Certificate of Eligibility" end-to-end testing is blocked -- LGY had plans to have testers begin testing today.

**Comment by RudyOnRails** [comment]
I may not have shared the sense of urgency, but as far as LGY is concerned, it's urgent because they have a testing schedule with people prepared.

**Comment by jhouse-solvd** [comment]
@RudyOnRails - Thank you for the information. Will follow up with our product owner and team lead.

**Comment by jhouse-solvd** [comment]
@RudyOnRails - The Platform Operations team will discuss to define and prioritize. We may reach out with questions to clarify requirements. The issue has been added to the team's backlog and will be scheduled for an upcoming sprint. Once scheduled, we'll be able to provide an ETA. 

Thank you, and let us know if you have any questions.

**Comment by RudyOnRails** [comment]
Thanks @jhouse-solvd. Since LGY has scheduled testing phases, and our new development work also depends on how testing goes, is there a chance that a (short) spike can be done sooner so we all can understand what is needed? If it is something on LGY's side, then they have the bandwidth and urgency to start that work immediately.

Thanks again,
Kevin

**Comment by RudyOnRails** [comment]
@jhouse-solvd reason I ask is because I am curious if this can be resolved by LGY using a CA signed cert instead of a self-signed.

**Comment by RudyOnRails** [comment]
Hi @jhouse-solvd . I met with my team and we have a thought. Is there a chance we could speak to you or someone on your team for 5-10min so we can have a basic understanding of the issue? This would allow us to confidently go into meetings with the stakeholder and be able to answer their logistical and technical questions.

Thanks for your attention!
Kevin

**Comment by jhouse-solvd** [comment]
@kathleencrawford - submitted [this PR](https://github.com/department-of-veterans-affairs/devops/pull/10206) which was approved and merged by the Ops team. Jeremy Britt then applied the terraform and @RudyOnRails verified that the integration is working in staging. :) 

more info in [this Slack thread](https://dsva.slack.com/archives/CJYRZK2HH/p1639428629441700)

**Comment by jhouse-solvd** [comment]
@RudyOnRails - External services are documented on the platform website

[Developer docs > Integrations > External Integrations](https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html)

_As the integration goes live_, you'll want to work w/ your PM or PO to get this documented. It may already be part of the "launch checklist" for your team, but I'm unclear on that part. 

Also, important: **Please reach out in advance when planning to test or go live in production**. This will help to ensure you have the support that you need. :)
