### ISSUE TITLE
[FE] My VA: Update "VA Benefits you might be interested in" section to show the Education benefit block persistently

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33976]
### Background

Most of the failures for the direct deposit for edu endpoint (production issue) come from My VA (https://www.va.gov/my-va), not the profile (https://www.va.gov/profile/direct-deposit). We use this endpoint to determine whether we show the "education" block to users on My VA under the "benefits you might be interested in" section.

![image](https://user-images.githubusercontent.com/34068740/145631782-e211fb9c-b09f-45ab-9a08-4f8b44e3333a.png)

We want to temporarily remove the conditional coding for the education block, so that the information shows all the time, regardless of whether the logged-in user has Education direct deposit or not.

### Tasks

- [ ] Remove/Comment out the conditional code for the education block within the "VA Benefits you might be interested in" section 
- [ ] Validate that the education block appears on My VA for all logged-in users
- [ ] Validate that there is no My VA code calling the endpoint for edu direct deposit

### AC

- [ ] The Education block within the "VA Benefits you might be interested in" section should be present all the time, regardless of existing benefits used by the logged-in user

**Comment by Samara-Strauss** [comment]
To clarify a few things that came up in Slack:

- **Please do not make any changes to the profile**. This update has nothing to do with the profile. It applies to My VA only .
- There is a section on My VA (https://www.va.gov/my-va) that shows conditionally based on what we get back from the direct deposit for edu endpoint. This update would make it so we don't call that endpoint **from My VA only**. The education block shown in the screenshot above should show no matter what, and we should remove the conditional logic around it.

Please let me know if you have any questions, and please do not touch any of the profile code as part of this update.

**Comment by Samara-Strauss** [comment]
Validated! I validated this with staging user 378, who is the only staging user who already has direct deposit for edu setup. For this user, I am now seeing the education prompt on My VA, which is the new + desired functionality.

![image](https://user-images.githubusercontent.com/34068740/145853745-4fcd91c0-5bca-4e85-8832-b6449a6950e2.png)


I have also confirmed that nothing affected the profile -- direct deposit for edu appears, and I can still update this information.

**This is good to go to production in today's deploy**. Thank you!

**Comment by hdjustice** [comment]
Code change was deployed to production, however the system still seems to be calling the endpoint for Edu Direct deposit.  Reopening ticket for continued work.

**Comment by Samara-Strauss** [comment]
OK, so as best as I could, I validated that we are not calling the CH33 endpoint in the network tab with My VA on staging. This should be good to go.
<img width="563" alt="Screen Shot 2021-12-14 at 9 34 00 AM" src="https://user-images.githubusercontent.com/34068740/146019567-66b9bcb3-71b9-439a-a693-0e8f0341b842.png">
<img width="559" alt="Screen Shot 2021-12-14 at 9 34 37 AM" src="https://user-images.githubusercontent.com/34068740/146019569-ffab3db8-1e31-4ff2-b25a-939d1d770c5e.png">
<img width="565" alt="Screen Shot 2021-12-14 at 9 34 46 AM" src="https://user-images.githubusercontent.com/34068740/146019572-1dc240a0-5358-48c3-9cac-3f30e27ef70a.png">
<img width="558" alt="Screen Shot 2021-12-14 at 9 34 58 AM" src="https://user-images.githubusercontent.com/34068740/146019573-a2579b2d-6faf-43cf-8c7f-2fc8ecc45687.png">
<img width="569" alt="Screen Shot 2021-12-14 at 9 35 07 AM" src="https://user-images.githubusercontent.com/34068740/146019576-e76e3998-7663-4c1a-8a66-e7583657b6cd.png">
<img width="566" alt="Screen Shot 2021-12-14 at 9 35 18 AM" src="https://user-images.githubusercontent.com/34068740/146019577-c208be88-ffc9-42b5-b6aa-3bb4512dd560.png">
<img width="562" alt="Screen Shot 2021-12-14 at 9 35 27 AM" src="https://user-images.githubusercontent.com/34068740/146019579-036a4165-3649-46f1-948a-fea5af34c0fa.png">
<img width="562" alt="Screen Shot 2021-12-14 at 9 35 37 AM" src="https://user-images.githubusercontent.com/34068740/146019582-1d07dda6-ec0c-4974-98f6-3daecee0b454.png">
<img width="568" alt="Screen Shot 2021-12-14 at 9 35 49 AM" src="https://user-images.githubusercontent.com/34068740/146019583-1d7498a0-ef2d-4986-b803-268a2cd485d3.png">

**Comment by hdjustice** [comment]
As confirmed via Slack message, Samara provided this update:   **Update: The My VA loading issue due to the CH33 endpoint has been resolved and confirmed to be working as expected in prod.**
