### ISSUE TITLE
[MCP] Balance cards should render most recent copay for each facility

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#33980]
## Issue Description
Verify statements are grouped by facility and filtered to return the most recent date for each facility. Rendered copay balance cards should be the most recent statement date for each facility.

![Medical Copays  Veterans Affairs 2021-12-10 14-32-57.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/613d098b-7142-4c39-91fd-f1ee2709ba2b)

---
## Tasks
- [x] `pHCernerAccountNumber` -> `pHAccountNumber`
- [x] Group all statements by facility then filter by most recent date
- [x] Sort download statement links

## Acceptance Criteria
- [ ] Cards should render the most recent statement date for each individual facility
- [ ] Download statement links should be sorted in descending order from the most recent statement date
- [ ] Account number should display

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
