### ISSUE TITLE
Remove "Back to top" files from formation

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#33995]
## Issue Description

Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/31200

`formation` has JS & CSS dedicated to the old "Back to top" button. Now that we have replaced the old button with `<va-back-to-top>`, we no longer need those files in formation.

---
## Tasks
- [ ] Remove JS from `formation` specific to "Back to top" button
- [ ] Rremove CSS from `formation` specific to "Back to top" button

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pdavies88** [comment]
@mendacitees can you link the PR to this ticket

**Comment by pdavies88** [comment]
@mendacitees is there a related PR in Component Library that removes the old Storybook mdx file?

**Comment by pdavies88** [comment]
@bkjohnson do we also need to remove this from https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/style.scss#L20

**Comment by bkjohnson** [comment]
Oh yes, that would be good.

**Comment by pdavies88** [comment]
PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/761

**Comment by mendacitees** [comment]
Additional pull request created for removal of style on vets website:  [https://github.com/department-of-veterans-affairs/vets-website/pull/20332](https://github.com/department-of-veterans-affairs/vets-website/pull/20332)
