### ISSUE TITLE
[FE] Profile - Determine how to keep profile loading from hanging due to direct deposit for edu API call 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34004]
## Background
The VA.gov profile fails to fully load when the call to a BGS API endpoint for direct deposit for EDU benefits takes too long to respond.  There have been occasions when this endpoint takes 3 minutes to return a response, so the code needs to be modified so that loading the rest of the profile is not dependent upon this response.  In addition, an appropriate error message should be displayed if the response is not received in a timely manner, fails or times out.

## Tasks
- [ ] Review the VA.gov profile code structure to determine why it hangs when the BGS API response is not returned quickly
- [ ] Update the code so that the rest of the profile is not dependent on the successful return of a response from the BGS API
- [ ] Build in a timeout that will display an error message if a response is not received within 30 seconds.
- [ ] Retry the call in the background 1-2 times (or whatever best practices dictate).

## Acceptance Criteria
- [ ] Engineer has good understanding of how the VA.gov profile loading sequences fire
- [ ] The VA.gov loading sequence is updated so that the successful return of a response from the BGS API is not required to successfully load the remainder of the profile
- [ ] A timer is built around the API call so that an error message is displayed when the call does not return a response within 30 seconds
- [ ] The BGS call is retried again 1-2 more times (or whatever best practices dictate)
- [ ] The changes are deployed to staging behind a feature flag
- [ ] Test/validate
- [ ] Deploy

**Comment by MarciMcGuireGCIO** [comment]
Closing this ticket since the ball is currently in Operations court.  If they discover something that needs to change about our logging, we will then open a new ticket.
