### ISSUE TITLE
[PM] Auth Profile - Personal Info Revision - Add test cases to Test Rail

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34008]
## Background
[Test cases have been written for Personal Info Revision](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md).  Once finalized, those test cases need to be added to Test Rail so they can be run for QA testing prior to Staging review.

## Tasks
- [ ] Enter finalized test cases for Personal Info Revision into Test Rail
- [ ] Run tests to verify they work as intended
- [ ] Notify Tze-Chiu Lei that the tests are ready for QA

## Acceptance Criteria
- [ ] Enter finalized test cases for Personal Info Revision into Test Rail
- [ ] Run tests to verify they work as intended
- [ ] Notify Tze-Chiu Lei that the tests are ready for QA

**Comment by SKasimow** [comment]
Closing as completed.
