### ISSUE TITLE
[Design] My VA: Revisit design for "VA Benefits you might be interested in" section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34003]
## Background

Rethink the "Benefits you might be interested in" section
- The endpoint we are using to determine whether we show education benefits or not has been acting unreliably and affecting loading of this whole section.
- I also think some people who could apply for health care aren't seeing the prompt.
- How can we update this section? 
     - Show all three blocks? 
     - Remove this section altogether and add prompts to healthcare/disability/education elsewhere?
     - What else can we think of? (May refer to Liz's recent research on [Best Practices](https://salientcrgt.sharepoint.com/:p:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B06FE2B5D-F09F-46B6-8E26-9DAA297AF425%7D&file=auth-exp-comparative-analysis.pptx&action=edit&mobileredirect=true))

## Tasks

- [ ] Review current design and consider changes to the section that may improve loading and dependencies on other services (i.e. called to endpoints outside of our control)
- [ ] Present proposal(s) to PO and team

## Acceptance Criteria

- [ ] Validate that thoughtful proposals are presented to the team for consideration of future implementation

**Comment by andaleliz** [comment]
@hdjustice, @tressaellen  and @Samara-Strauss, I have a few questions as I familiarize myself with this. Not sure who exactly to direct these two, so bringing you all in :) 

> The endpoint we are using to determine whether we show education benefits or not has been acting unreliably and affecting loading of this whole section.

Are more specifics available? How is the reliability endpoint affecting the loading of the whole section, other than I'm assuming maybe the edu section doesn't show?

> I also think some people who could apply for health care aren't seeing the prompt.

Are you saying they're not seeing it because it's not loading, or you don't think they're cognitively acknowledging it? What is making you think that? I took a peek at analytics to see if there might be a way to compare how often a section is displayed with how often someone engages with it, but I don't think there is a "load" event for the section. Please correct me if I'm wrong.

I'm also curious if there are any KPIs for this section, and if not, do we plan on adding some? I don't see any in [the product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#measuring-success), but possible I'm not looking in the right place.

I'm assuming this [state documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md#states) is still correct, but if it isn't, please lmk.

And last but not least, are we aware of any other tools on VA.gov that include recommendations like this? I'll do some digging too but thought I may as well ask while I'm writing a novel of questions :)

Thanks!

**Comment by Samara-Strauss** [comment]
> Are more specifics available? How is the reliability endpoint affecting the loading of the whole section, other than I'm assuming maybe the edu section doesn't show?

This is the ongoing issue with the direct deposit for edu endpoint that has been down for days (though randomly working today). It's been especially a mess in the last few days ([Slack channel](https://join.slack.com/share/enQtMjg0MjMzNzMzNjU5OS00ZWM1ZjNiOTJmZWExNDYxMDE4NDY5ZGYwODZiOWEwNWJlOTJhNGI1NjJiZDRiMDQ1ZDk5YjQ5ZjAzMTlmZThj) if you really want to follow along), but [you can see that this endpoint has been failing spectacularly on My VA for months](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last7days&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&_r.drilldown=analytics.eventAction:Profile%20-%20EDU%20Direct%20Deposit%20Retrieval%20Failed/). For My VA specifically, I think the failures are related to the DS Logon/MHV gating you all put in place while I was on maternity leave. Idk whether My VA was considered at that time, but if it wasn't, then we may have been trying to load this endpoint for months for DS Logon/MHV users without any error handling/graceful degradation of this endpoint for those users.

The TL;DR on this is that even if we had some sort of way to properly degrade how we handle this endpoint in the "Benefits you might be interested in section" for MHV/DS Logon users, the endpoint has been so unreliable as of late that I don't think this LOE is worth it. If there are questions, let's meet to discuss since there's been sooooo much that has happened this week alone. 

> Are you saying they're not seeing it because it's not loading, or you don't think they're cognitively acknowledging it? What is making you think that? I took a peek at analytics to see if there might be a way to compare how often a section is displayed with how often someone engages with it, but I don't think there is a "load" event for the section. Please correct me if I'm wrong.

This is also a little complicated. For the "Apply for health care" recommendation under "Benefits you might be interested in", we show it to anyone who is detected to **not** be in the VA health care system. But, anyone who has ever been to a VA facility for anything will show up in the health care system and be returned by the endpoint, so you can actually show as in the VA health care system without actually having VA health care, eg. an employee who is not a veteran but has a health record at the VA (like me), or a service member who received care at a VA facility one time but isn't a veteran receiving health care.

Because of this, I'm worried that there are people transitioning out of service who may have received care at a VA facility while in the service and therefore show as in the VA health care system based on the data we get back from the endpoint, but they don't actually have VA health care. 

[You can see in this report that the prompt to apply for health care (# 40) gets many fewer clicks than the prompt for disability (# 18) or education (# 8)](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20210701&_u.date01=20211216&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=50&_r.drilldown=analytics.pagePath:www.va.gov~2Fmy-va~2F,analytics.eventCategory:Interactions/), yet health care is more widely received than education AFAIK. So, it could either be that people aren't seeing the link, or so many people already have health care that they don't need to apply. TBH, I'm not sure.

> I'm also curious if there are any KPIs for this section, and if not, do we plan on adding some? I don't see any in the product outline, but possible I'm not looking in the right place.

Nope, none and I don't plan on adding any right now. But we could talk about this as part of revisiting this section.

> I'm assuming this state documentation is still correct, but if it isn't, please lmk.

It is not. As of this week, we show the education prompt at all times because of the direct deposit for edu endpoint issue mentioned above.

> And last but not least, are we aware of any other tools on VA.gov that include recommendations like this? I'll do some digging too but thought I may as well ask while I'm writing a novel of questions :)

I am not aware of any.

**Comment by andaleliz** [comment]
Thank you so much @Samara-Strauss! This is very helpful, and wow, complicated. I don't have any questions about the failing end point, but do have a comment:

>Idk whether My VA was considered at that time

I do not recall anyone bringing up My VA during the discussions around the problem and proposed solutions 😞 

 And I have just one question one about health:
>I'm worried that there are people transitioning out of service who may have received care at a VA facility while in the service and therefore show as in the VA health care system based on the data we get back from the endpoint, but they don't actually have VA health care.

Do you know if there any other data points we can cross-reference, such as last appointment? I am 99% sure there aren't.  If not, I'm really sure what else we can do other than just show it to everyone. I'll mull this over during the weekend and see what else comes to me.

**Comment by Samara-Strauss** [comment]
> Do you know if there any other data points we can cross-reference, such as last appointment? I am 99% sure there aren't.

Not that I know of without making things overly complex and potentially not reliable.

> If not, I'm really sure what else we can do other than just show it to everyone. I'll mull this over during the weekend and see what else comes to me. Your concerns and use cases you brought up are totally valid, and I can see why we'd want to encourage them to apply.

I agree. I think we should show the link to everyone.

I had another thought on this which I should have shared sooner but didn't because my brain was totally occupied by the direct deposit issue last week. If we are going to show the links for health care, disability compensation, and education at all times regardless of if people have the benefit or not, we should we stop framing this section as "benefits your might be interested in." This could be as simple as a copy change (eg. changing the title of that heading to something like "Benefits offered by the VA") or something more complex that I haven't thought of.

**Comment by andaleliz** [comment]
> we should we stop framing this section as "benefits your might be interested in." This could be as simple as a copy change (eg. changing the title of that heading to something like "Benefits offered by the VA")

This occurred to me over the weekend as well. If you are happy with the level of interaction you're seeing with the edu and disability sections, then I don't think it needs to be more complex than updating the logic and changing the heading. I can take that to content office hours this week.

**Comment by Samara-Strauss** [comment]
That works for me!

**Comment by andaleliz** [comment]
@Samara-Strauss one other thing occurred to me -  It feels like it makes sense to hide the "learn how to apply" CTA if there is an existing application in progress. So we could show these sections to everyone _unless_ they have an application in progress.  Do you think the endpoints are reliable enough to handle that?

**Comment by Samara-Strauss** [comment]
> Do you think the endpoints are reliable enough to handle that?

Yes, this should be much easier to do, and I think we are already doing it. Worth confirming.

**Comment by andaleliz** [comment]
Okay, it seems like that logic is in place for the health care section, but not for disability compensation. I logged in with user 100, and saw this (disability comp application in progress, and CTA at the bottom):
![Screen Shot 2021-12-21 at 3.33.53 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/2c8b4a0c-fe3d-4368-95ae-2be705c1fbb5)

and then started a health care application. When I returned to My VA, I could see the health care app in progress and the health CTA was gone:

![Screen Shot 2021-12-21 at 3.34.49 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/5a9c6d65-6007-4e6e-b87e-5ceaf8ec5907)

I'm not sure if that means there is a bug because the disability comp CTA was showing with an app in progress or not.

Either way, I have two options I can share with Danielle:
1. Stick with the hierarchy we have with a change to the copy. 
![Screen Shot 2021-12-21 at 3.32.28 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/4e0756d5-a519-4dfb-8922-fbe20ecdb290)

2. Update the headings so VA benefits and health care is no longer tied to the applications in progress section. 
![Screen Shot 2021-12-21 at 3.32.32 PM.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/a4f9ee8a-a158-4b92-80b6-fc101bff7fb8)
I'm not sure if there is any specific reason to keep the hierarchy as it is - if so, let me know and I can just review option one with her.

**Comment by Samara-Strauss** [comment]
I've been staring at this for like 20 minutes and I'm still not sure which way I want to go. I'm gonna sleep on it and get back to you tomorrow.

**Comment by andaleliz** [comment]
That's totally fine! It may also be worth sharing both with Danielle to see if one is more aligned with other content strategies than other.

**Comment by Samara-Strauss** [comment]
> I'm not sure if that means there is a bug because the disability comp CTA was showing with an app in progress or not.

I don't think there is a bug with the disability CTA. People can file multiple claims at once (though IDK how common this is), so that makes sense to not hide it if someone has a claim in process. On the contrary, someone can *not* have two health care  or education applications at the same time.

As for the designs, I think # 1 makes the most sense. Since the CTAs are to learn how to apply and not to the hub landing pages, I think it makes the most sense to keep this section under the larger "Applications in progress" heading. However, is there any way we can change the subheading -- "VA benefits and health care" -- to something that ties it in better with this section? I know we already discussed why "Benefits you might be interested" doesn't work anymore, but "VA benefits and health care" feels almost too neutral and like it has nothing to do with applying. If we can't think of something that meets the content guidelines, that's totally fine, but just wanted to throw that thought out there to see what you think.

**Comment by andaleliz** [comment]
Ah, that makes sense about disability. And I'm good to go with #1! Thanks for weighing in on that.

> However, is there any way we can change the subheading -- "VA benefits and health care" -- to something that ties it in better with this section? 

Yes, I'm sure there is! I really struggled to come up with something in the appropriate active voice that wasn't along the same lines as "Benefits you might be interested in", so I will need to brainstorm with Danielle about what else might work.

**Comment by andaleliz** [comment]
I reviewed this with Danielle and she suggested "Explore VA benefits and health care".

We can update this across all Sketch files as part of #34155; in the meantime [here's a mock-up](https://www.sketch.com/s/19703066-4d7c-4c29-841c-cacffa8f49ae/a/Gmr4AAE).

This is ready for a FE implementation ticket.

**Comment by hdjustice** [comment]
@andaleliz @Samara-Strauss - Did we decide to update the logic to show all sections to all veterans all the time?  There was a little back & forth in the comments above, and the Health care application CTA seems to have accurate logic.   What was our final decision on the logic?
cc @tmitchellgcio

**Comment by andaleliz** [comment]
Yes, my understanding was that we decided we would show all sections to all Veterans all the time. @Samara-Strauss should confirm though.

**Comment by Samara-Strauss** [comment]
Yes, that is correct.
