### ISSUE TITLE
[PM] Auth Profile - Personal Information Revision - Update TestRail regression tests

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34001]
## Background
The Profile regression tests in TestRail will fail due to the changes be made to separate Personal information from Contact information.  Additional testing also needs to be added for the new fields.  Related Midpoint Review feedback from QA: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33949

## Tasks
- [x] Update existing tests to account for navigation changes, new Contact info page, and division of Personal vs. Contact info fields
- [x] Add testing for new Personal Info fields

## Acceptance Criteria
- [ ] Regression tests account for navigation changes, new Contact Info page and division of Personal vs. Contact info fields
- [ ] New regression tests are added for new Personal info fields

**Comment by MarciMcGuireGCIO** [comment]
Moving this to Sprint 65 since we are still not 100% locked on some of the components.

**Comment by SKasimow** [comment]
Parts of staging down; wasn't able to get all screenshots needed.

**Comment by SKasimow** [comment]
Closing - all screenshots provided to QA.
