### ISSUE TITLE
[Research] My VA - Payments Information & On-site Notifications: Kick off recruiting for usability on both Payment Information and On-site Notification

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34005]
## Background

Design, Research plan and Conversation guides are now complete and we are ready to show veterans the proposed Payments Information section and On-site Notification on My VA and obtain feedback.

## Tasks

- [x] Submit to Perigean
- [x] Coordinate scheduling/recruiting as needed

## Acceptance Criteria

- [x] Recruiting veterans has begun and sessions are being scheduled to review the proposed addition of the Payments Information section and On-site Notification on My VA
