### ISSUE TITLE
Lighthouse 503 HTTP Status Codes

### ISSUE THREAD

**Issue by rbeckwith-oddball** [department-of-veterans-affairs/va.gov-team#34016]
## Description
503 errors being encountered by lighthouse and vets-api with error "backend server at capacity"

## Background/context 
[Issue submitted here](https://dsva.slack.com/archives/CBU0KDSB1/p1639414750405400)
![http_503_elb](https://user-images.githubusercontent.com/89401043/145862282-dabb702e-cea8-4762-8821-a8281d0d8b07.png)

## Technical notes
[Slack Thread](https://dsva.slack.com/archives/CTYQL39FE/p1639415267415000)

---
## Tasks
- [ ] The problem appears to have corrected itself, but further research would likely help prevent this issue from occurring in the future.

## Acceptance Criteria 
- [ ] Identify the underlying cause of the spike in traffic that caused 4 of the 6 hosts to be flagged as "unhealthy" in ELB

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Closing. Please re-open or create a new issue if this is still needed.
