### ISSUE TITLE
Setup Node Express App for TUD GitHub OAuth

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#34021]
## Description
Referencing [ticket #33416](https://app.zenhub.com/workspaces/planning-board-testing-tools-team-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/33416)

Can you please setup this simple [Gatekeeper](https://github.com/prose/gatekeeper) Node Express app for TUD? Gatekeeper acts as a proxy between the TUD app and this GitHub OAuth endpoint which can't be hit by a client (only a server) - `https://github.com/login/oauth/access_token`

Here's the repo for the app - https://github.com/department-of-veterans-affairs/tud-github-oauth-proxy I gave ' vsp-operations' admin access to it.

We'll need to set two secrets which are referenced by the `config.json` file:
- `GITHUB_APPLICATION_CLIENT_ID`
- `GITHUB_APPLICATION_CLIENT_SECRET`

## Background/context 
This PR to add client-side GitHub OAuth to the TUD (Test User Dashboard) required a proxy, like Gatekeeper, to make the request to GitHub - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/98

[GitHub](https://github.com/octokit/octokit.js#app-server):
> We are working on @octokit/auth-oauth-user-client to provide a simple API for all methods related to OAuth user tokens.

---
## Tasks
- [ ] Setup the Gatekeeper Node app
- [ ] Inform Holden Hinkle where to set the secrets for this app

## Acceptance Criteria 
- [ ] The Gatekeeper app will be setup to work with TUD
- [ ] Holden knows where to set the secrets for this app

**Comment by pjhill** [comment]
Ryan, still battling infrastructure to get SSL going.

**Comment by pjhill** [comment]
Notes from Holden, Ryan, and Peter meeting --
* The SSL portion wasn't really part of the original request. The app itself doesn't seem to be capable of handling SSL connections, so I'm trying to figure out how Heroku did id (that's how Holden said he had SSL working). It may need Nginx or something as a proxy in front of it to handle the SSL and send it back to gatekeeper.
* Essentially make automated for EKS (once we have the correct configuration setup for it)

**Comment by rbeckwith-oddball** [comment]
Nginx has been setup and awaits SSL at this point. The domain can only be reached through the SOCKS proxy. The SSL issue is likely not as important as getting the automation / deployment setup since the environments that were modified were/are all managed via terraform or similar.

**Comment by rbeckwith-oddball** [comment]
Regarding the SSL:
1. I did find a wildcard SSL, but I don't want to use it if doing so causes confusion to any other entities using the certificate and it feels like breaking more of the process by finding a private key to use as well
2. The other option is to have one specifically for the domain

Either way, the domain is still locked down to SOCKS access only.

**Comment by holdenhinkle** [comment]
@rbeckwith-oddball You mentioned this is locked down to SOCKS... Will the app still be able to receive the response from requests it send to GitHub? Just checking.

**Comment by pjhill** [comment]
The need for a stand alone Gatekeeper proxy to handle the traffic is OBE. Holden integrated the proxy functionality into `vets-api`.
