### ISSUE TITLE
Design for VAMC Lovell "Manage your health online"/top tasks

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34026]
## Issue Description
The Captain James A. Lovell Federal Health Care Center has a combined mission to serve active duty military, their family members, military retirees and Veterans. The center also cares for an estimated 40,000 Navy recruits who prepare for military service at Recruit Training Command at Naval Station Great Lakes. 

As a Veteran, active duty service member or family member receiving care at Lovell Federal Health Care, I need a seamless top task experience. (For example, when these personas click on the links in the "Manage my health online" box, they are connected to the appropriate entry point.)

Based on locations, we will need 
 - a system home page serving Veterans and service members 
 - a facility home page for the main location serving Veterans and service members 
 - facility home pages for locations serving service members only
 - facility home pages for locations serving Veterans only - no design needed - this is current VAMC experience
 
### Current teamsite experience
[Existing Lovell pages](https://www.lovell.fhcc.va.gov/)

---
[Appointment page](https://www.lovell.fhcc.va.gov/patients/appointments.asp)

![image](https://user-images.githubusercontent.com/55411834/145874853-32b971cc-7e25-4b22-97f3-aca3d43e44d5.png)

---

[Prescriptions](https://www.lovell.fhcc.va.gov/services/pharmacy.asp)

---

### Current VAMC experience

[New modernized pages for Lovell ](https://www.va.gov/lovell-federal-health-care/)

---

**System home page - "Manage your health online"** 
- Refill and track your prescriptions 
- Send a secure message to your health care team 
- Schedule and manage health appointments 
- Download your VA medical records (Blue Button) 
- View your lab and test results 
- Order hearing aid batteries and accessories 

**System home page - top tasks**
- Make an appointment
- Register for care
- Pharmacy

**Facility home page - top tasks**
- Make an appointment
- Register for care
- Pharmacy

## Tasks
- [ ] Work with VAMC upgrade team and existing teamsite pages to determine relevance of each task in "Manage your health online" and top task buttons for DoD population
- [ ] Design a system home page top task experience for either population (if relevant to DoD) 
- [ ] Design a system home page "Manage your health online tasks for either population (if relevant to DoD) 
 - [ ] Design a facility home page "Manage your health online tasks for either population (if relevant to DoD)
 - [ ] Design a facility home page top task experience for either population (main location) (if relevant to DoD) 
 - [ ] Design a facility home page top task experience  for active duty only  (if relevant to DoD) 

### Acceptance criteria
Design for top tasks and "manage your health online" at Lovell health care system locations

**Comment by mmiddaugh** [comment]
[UX Pin](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/145465352/simulate/no-panels?mode=i)
