### ISSUE TITLE
Claim Status Tool - Upload Issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34034]
## Issue Description
As a Veteran, I would like to be able to upload documents/evidence in connection with my claim. 

---
## Tasks
- [ ] Investigate error uncovered during research. Veterans click on "upload documents" and nothing happens

## Acceptance Criteria
- [ ] Issue documented and resolution plan developed. Create additional tickets as needed for resolution tasks.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sortizsh** [comment]
Can you edit this ticket to be the work that you will complete in this sprint Michel? In the course of addressing this, can you create tickets and add them to the Backlog? Or slack them to Sarah and she can help write tickets.

**Comment by michelpmcdonald** [comment]
Changing to a FE ticket, if the user clicks the upload button, the file dialog should appear and allow the user to select a file.

The BE does not come into play until after the user has selected a file to upload.

**Comment by jacobworrell** [comment]
@michelpmcdonald can you provide steps to reproduce the error?

**Comment by michelpmcdonald** [comment]
@jacobworrell - no way I know of to force the issue to happen.  I've personally hit it once incidentally on staging by trying to upload files using cst.
