### ISSUE TITLE
Claim Status Tool - Decision Letters

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34040]
## Issue Description
As a Veteran, I would like to be able to view and download decision letters. 

---
## Tasks
- [ ] Investigate how to allow viewing/download of decision letters.

## Acceptance Criteria
- [ ] Process/ technical investigation results documented. Create additional tickets as needed for technical implementation. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/29082
