### ISSUE TITLE
Finalize & implement IRIS and Salesforce formal issue tracking

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3404]
## User Story or Problem Statement
How might we finalize and implement formal issue tracking process for IRIS and Salesforce issues so that data collection for call center report and escalations is more accurate and streamlined

## Goal
Finalize formal issue tracking process for IRIS and Salesforce issues.

## Acceptance Criteria
- [X ] Set up shared folder on VA.gov network
- [ ] Finalize tracking spreadsheet for IRIS and SF issues
- [ ] Document process in github
- [ ] Share final issue tracking process with team

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@Kimberley2019 work with @clantosswett on issue documentation.

**Comment by Kimberley2019** [comment]
Access has now been given to a shared drive that will enable the Call Center team to be able to compile data in one centralized location.
This shared drive will allow the Call Center team team to gather review and reply to issues independently but gather and input data into the same spreadsheet.
The folder is located on the O drive on the VA Network and @Kimberley2019 is the owner of the folder.

**Comment by Kimberley2019** [comment]
#IRIS and SalesForce Tracking

##Current State

There are multiple spreadsheets that are being used by both Call Center Leads in order to gather issues from SalesForce and IRIS.  This causes issues when attempting to compile data for tracking and reporting purposes.  Although issues are being gathered from two seperate systems, the criteria is the similar. 

Upon final determination of which master spreadsheet will be utilized for compiling data, the following process will be used for tracking issues from IRIS and SalesForce.

Call Center Leads will gather issues on a daily basis from IRIS and SalesForce and enter into the master spreadsheet located on the O drive of the VA Network.  

#The information that will be collected:

- Ticket numbers
- Origination ticket date
- System (i.e. IRIS or Salesforce)
- Name of employee handling issue
- Status
- Users last name
- Description/Case notes 
- Topic
- Subtopic


Once the information is entered into the master spreadsheet it will be the responsibility of the Call Center Leads to follow the escalation process in order to advise the appropriate teams of known issues.
