### ISSUE TITLE
[BE] Deprecate v0 endpoints

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#34057]
## Description
Remove unused v0 PatientCheckIns endpoint from vets-api

## Tasks
- [ ] Identify & remove service layer code used by v0 endpoints
- [ ] Identify & remove model code used by v0 endpoints
- [ ] Remove v0 swagger docs

## Acceptance Criteria

- [ ] Deployed and tested on staging.
