### ISSUE TITLE
Revisions to AooA dashboard

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#34053]
## Issue Description
Improvements to AooA dashboard to make WoW comparisons easier so the Analytics team can better understand how our users are interacting with our data products. In addition, revisions should make metrics easier for the Analytics team to report up to OCTO-DE.

---
## Tasks
- [x] **KR1:** Switch "Decision-making" section to so metrics are computed by VFS teams/products eligible for a dashboard, instead of all existing.
  - [x] Add card(s) to show teams/products not eligible for standardized dashboards to provide context for newly filtered section.
- [x] **KR2:** Reconfigure/create new cards in "VFS team engagement" section to prioritize highlighting percentage of views by VFS teams.
- [x] Add new "Highlights section at top for Q1 KRs (will update for Q2 or remove if appropriate) 
- [x] Audit team names in Dashboard Backlog vs. VFS roster for more effective joins.
- [x] Reorder sections to match priorities.
- [x] Beast Mode to facilitate rolling WoW comparisons for data sources with daily updates
  - [x] Update all multi-value gauges for grouping
  - [x] Strategy (filters, ETL, etc) to support rolling WoW comparisons when data for periods does not exist
- [x] Add total value (in addition to percentage) in hover text for teams who have a dashboard, share metrics in ToT, or attend office hours.
- [x] Replace velocity card with one JUST for standardized dashboards, switch data source to manual tracker
- [x] Add text boxes to clarify update cadences for cards with different data sources / refresh schedules. (n/a)

## Acceptance Criteria
- [x] AooA dashboard is streamlined, easier to gain user insights from, and supports our own reporting on our products to stakeholders.

**Comment by chloedotbrown** [comment]
12/22 - updated scope above to reflect Q1 KRs and challenges surfaced for gauges.

**Comment by chloedotbrown** [comment]
Hey @michelle-dooley – the new draft of our [dashboard about our dashboards](https://va-gov.domo.com/page/514439234) (and associated support) is done! I've broken it up into the following new sections:

- **2022 Q1 KRs**
- **Coverage & eligibility**
  -  By team: breakdown of which teams are eligible (or eligible for more than they've opted in for), as well as any changes in eligibility and coverage to make reporting easier.
  - By product: breakdown of coverage and eligibility at the product level
- **Dashboard usage**
  - VFS views by week, broken down by standardized vs. other content. You can also filter this to only see usage by teams who are eligible for at least 1 dashboard.
  - How frequently teams with dashboards are actually viewing them.
  - Team of Teams shares (metrics and Domo) before and after standardized launch.
- **Documentation & support** 
  - Office hours participation by question topic and team
  - Engagement with dashboard resources on Platform website
- **Delivery time**
  - How quickly we're turning standardized dashboards around after they're pulled into the sprint.  

Moving this to the internal QA column so you have a chance to review before we mark this as done. In addition to the standard "anything you'd want added or changed?" questions, I'm also specifically interested in whether the filters feel right for KR2, both in the Q1 and Dashboard Usage sections. Right now, these both default to activity from ALL VFS team members (regardless of dashboard status) but exclude COVID dashboards, the eligibility dashboard, dashboards made by other Platform teams, and automatically generated Domo pages (Overview, Favorites, etc.). 

If you think any of the team or content exclusions should be adjusted, just let me know!

**Comment by michelle-dooley** [comment]
@chloedotbrown I love it, looks great!!  My only question is on the KR2 for the Q1 section, should we base the % on only those with std dashboards?  So it would match the dashboard usage stat filter "has standardized dashboard"?  I love having the filter option on dashboard usage so you can see across all but feel like the KR should be measured on those that have one otherwise it will always be low, teams that don't have one are likely not looking at others.  Hopefully as we get more on these numbers will get closer.  Thoughts?

**Comment by chloedotbrown** [comment]
@michelle-dooley Makes sense to me! I've updated the KR2 card and the annotation on the [dashboard](https://va-gov.domo.com/page/514439234) so it's clear which user behavior and content is being filtered. Closing this ticket, but if there are any other edits you'd like to see in the future, just let me know! Happy to do more revisions any time.

<img width="300" alt="Screen Shot 2022-01-24 at 9 50 58 AM" src="https://user-images.githubusercontent.com/45518242/150837181-5a30ccd6-adfd-4198-aeb8-e856d4e39d02.png">
