### ISSUE TITLE
[VAMC] Review and list all Pages with DoD shared and independent pages for Lovell Federal health care [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34070]
## Story
As a Veteran and DoD active duty I need to know the correct web pages for my support, so I can find the health service support I need, whether it is VA health or TriCare support.

## Task
Create a artifact that documents all shared resources utilized on Lovell Federal health care
- [x] Document each web page on site that has shared with VA and DoD resources
- [x] Document each web page that is DoD only/specific to DoD
- [x] Document Top Tasks resources that are shared between VA and DoD
- [x] Document the URL links for the resources of DoD sides of the pages

## Acceptance Criteria
- [x] An artifact/document that provides detail pages and information listed above.

**Comment by ltrombley** [comment]
Task #34070 - Review and list all Pages with DoD shared and independent pages for Lovell Federal health care [BA]  - is Complete and moved to Validate
