### ISSUE TITLE
[MCP] render statements 6 months from the current date

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#34075]
## Issue Description
copay balance cards should only render statements within the last 6 months from the current date otherwise a no history alert should display

![Medical Copays  Veterans Affairs 2021-12-14 09-31-41(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/3ef4dfa5-b6bf-4a29-89f6-200fb8dcd105)

---
## Tasks
- [ ] filter statements to only render items within the last 6 months
- [ ] render no history alert if all items are more than 6 months

## Acceptance Criteria
- [ ] all copay balance cards rendered should be within the last 6 months from the current date
- [ ] no history alert should display if all statements are older than 6 months
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
decided this should be handled on BE closing ticket
