### ISSUE TITLE
Hypertension Fast Track Support

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#34072]
## Issue Description
The Hypertension Fast track teams need support to help integrate their new hypertension fast track workflow into the 526 submission process.  They are providing rapid processing for single issue hypertension claims that already have the needed medical reports available.  

The fast track team has limited access staging\review instances and needs help deploying, running and debugging their new code. 

All items were completed, however an issue was discovered with evss when submitting fast track claims.  Evss is going to fix the issue, and we will need to retest the process again.

---
## Tasks
- [x] Provide programming support by reviewing the fast track code and adding their code to the current 526 workflow
- [x] Isolate any fast track processing errors to insure any errors that are hit do not impact the 526 claim processing.  The idea is that if the fast track code hits an error of any kind, the claim still will be submitted to evss without a fast track status applied.  This was done with try-catch blocks and Sidekiqs onSuccess and exhausted handlers and sequencing the 526 batch jobs properly.
- [x] Test the above error handling by modifying the fast track code to force errors and test their error handling in various scenarios to ensure that fast track errors do not impact the claim from being submitted
- [x] Join the fast track work sessions, run their code on staging-review-instances by creating 526 eligible fast track claims      
- [x] Monitor the back end systems and pull data during testing to ensure the fast track code is modifying the claim properly(adding "RRD" to the claim's special issues) and the fast track processing PDF is properly attached to the 526 claim and uploaded to evss during the 526 workflow
- [x] Join the fast track meetings with evss to discuss issues, mitigation strategies and deployment schedules
   
## Acceptance Criteria
- [x] Fast Track code is deployed(behind feature flags) to staging and or review instances.
- [x] Testing Fast track claims are detected, properly designated and submitted to evss 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
Support and testing was done during this spring.
An issue was uncovered during testing, evss was not accepting the RRD special issue in the hypertension claim.  Evss is going to correct, and the hypertension will re-test.

**Comment by michelpmcdonald** [comment]
Closing this sprints hypertension support
