### ISSUE TITLE
[Design] My VA - Payments Information: Kick-off Experimental Design process for action link/alert style on My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34095]
## Background

After Design Intent review, [we were advised that there are no approved active link styles that have background colors](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34047), which would allow us to call out action items on the My VA dashboard (example: "You have 2 new messages" or "You have 2 outstanding debts").  Due to the lack of approved active link styles, we need to submit a proposal through the Experimental Design Process, so that it can be reviewed and evaluated as a potential addition to current styles.  
This was briefly discussed during the Design Intent review meeting.

## Tasks

- [x] Submit proposal through the [Experimental design process](https://design.va.gov/documentation/contributing-to-the-design-system)
- [ ] Post in the #vsp-design-system slack channel and tag Carol Wong to alert the team that you have filled out a ticket and would like to get on the council’s agenda.

## Acceptance Criteria

- [x] New Action Link Style proposal is submitted through the Experimental Design process

**Comment by tressaellen** [comment]
Set up meeting with platform on Friday 12/15.

**Comment by tressaellen** [comment]
I've submitted [this ticket to platform](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/606)

**Comment by hdjustice** [comment]
Fabulous!!

**Comment by tressaellen** [comment]
Carol let me know they will discuss this 1/7 in the design system council meeting. So I think we're good to close this ticket.
