### ISSUE TITLE
Improve Awareness of Upstream Service Statuses

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#341]
## High Level User Story
As a VSP team member, I need to know the real-time status of the upstream services we use so that I can anticipate and troubleshoot triage issues.

## Hypothesis/(es)
**If** we have a usable way to monitor the status of our upstream services in real time, or as close to real-time as possible, **then** we expect to be able to anticipate issues that may affect our developers and end users, which allows us to respond more efficiently.

## Goals
- We have timely awareness of changes to our 3rd party services (perhaps we have a regular cadence for testing our upstream services?)
- A single place that shows the statuses of our upstream services
- Better relationships with our upstream service partners as part of this effort

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Automation + Instrumentation`, `Support`)

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**

**Comment by minafarzad** [comment]
check in with @lihanli to see if the e2e work he's doing incorporates any of this
