### ISSUE TITLE
Staging Review [Virtual Agent Chatbot - Pilot Release]

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#34106]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [X] Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [X] Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [x] Update Staging Review ticket with the product’s launch date after it has gone live.
- [x] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
  - https://staging.va.gov/virtual-agent-study/ 
  - Experience is unauthenticated so no test users required

- [x] Product outline 
  - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/Virtual_Agent_Product_Outline_Phase2.pdf
 
  

- [x] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [X] Content brief (if applicable) and your product’s content source of truth 

  - The content for the chatbot consists of the responses it provides to users, and for that, the content source of truth will live within a number of parts of Microsoft infrastructure (PVA and QnA maker). Please reach out to the team if you'd like us to walk you through these systems.
  - Phase 1 Content Management Process - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/product/virtual_agent_content_management_process.pdf
  - Phase 2 Automated Content - This [CSV file](https://github.com/department-of-veterans-affairs/va-virtual-agent/blob/master/automated-content/automatedDrupalContent.csv) manages the VA.gov Drupal articles and sections from which the chatbot pulls responses from, given a user's specific utterance
  - Phase 2 Manual Content - For system messages like greetings, crisis management, and other generic responses, that content is contained within a QnA file managed in GitHub

- [X] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/33905 

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test cases/test plan in TestRail with test execution logs 
  - Test cases :  https://dsvavsp.testrail.io/index.php?/suites/view/652&group_by=cases:section_id&group_order=asc&display_deleted_cases=0
  - Test Runs and Results : https://dsvavsp.testrail.io/index.php?/suites/view/652&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [x] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 
- [x] [Supported Browsers](https://github.com/department-of-veterans-affairs/vets-website#supported-browsers)

### Accessibility artifacts 

- [x] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 
- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- [X] List of known issues
  - Accessibility issues identified from Phase 1 Staging Review #25113
  
## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by ianpsant** [comment]
For reference, this is the Phase 1 Staging Review ticket #24884

**Comment by shiragoodman** [comment]
Staging Review has been scheduled for 1/6/2022 at 2:00pm ET

@ianpsant please be sure to add your team members. I only see you on the invite so far.

**Comment by shiragoodman** [comment]
Zoom recording of Staging review: https://us06web.zoom.us/rec/share/dGBKPXsvhU37AoHykQmiemEBYPNJGPE-m6TijesidCs9Ag15tpRlZHzVeaIjlqcp.SJLuaunQXm-3DkL6 
Passcode: f6!B#42C

**Comment by ianpsant** [comment]
Launched March 2nd, with follow up launch on May 2nd.
