### ISSUE TITLE
Phase 2 - Form 526 PTSD added question

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#34100]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [ ] Explore how we can remove questions (that is triggering for many veterans) about PTSD in Form 526 
- [ ] Work with Paul Shute on identifying the legal language we need to use for this project. 
- [ ] Design pages where the veteran is asked about "fear of hostile military or terrorist activity".

## Acceptance Criteria
- [ ] Documented form improvement research and recommendations. Presentation and formal documentation

**Comment by chrvalla** [comment]
Closing ticket. Design mockups approved by Paul Shute. Moving to phase 3 - creating designs in Sketch for design review and final approval and implementation into Form 526. 
https://app.mural.co/t/vsa8243/m/vsa8243/1638999373388/4dd450f76ceaa66dc01e552599f3b3811d047262?sender=cvalla7693
