### ISSUE TITLE
Frontend Sentry Review

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34110]
## Issue Description
Review sentry errors for frontend

---
## Tasks
- [ ] Review & resolve sentry errors

## Acceptance Criteria
- [ ] Issues resolved
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
