### ISSUE TITLE
[FE][BUG] Complete page refresh

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34114]
## User Story

As a user if I re-visit the complete page, the app crashes

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The app shouldn't crash when the user revisits the complete page after a successful pre-check-in.(ie: page refresh, or navigate back to it)

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Fix the problem
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by julieadair1** [comment]
@jparker0425 this looks like something we should probably pull in.  Thoughts?
