### ISSUE TITLE
Rework health care tool pages with new content pattern and add notification Q&A to relevant pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34123]
## Issue Description
We have a new content pattern that we need to apply to our health care tool pages. We also need to add the notification Q&A to the appointments and prescriptions pages. Currently the health care tool pages are all in react widgets, so this work needs to be done in Word docs rather than in Drupal. 

The medical records page is already being reworked in a separate ticket. This ticket is for:

- [ ] [Refill and track VA prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)
- [ ] [VA secure messaging](https://www.va.gov/health-care/secure-messaging/)
- [ ] [Schedule and manage health appointments](https://www.va.gov/health-care/schedule-view-va-appointments/)
- [ ] [View your VA lab and test results online](https://www.va.gov/health-care/view-test-and-lab-results/)

Just like with the medical records pages, we'll need to look at both authenticated and unauthenticated content for each page when making updates and provide PW with both versions. [This ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/33313) has links to both versions of the content in GH.

There is also notification text that needs to be incorporated to the updated pages. The approved text can be found in ticket #33349.

## Tasks
- [x] Danielle, Selina, and Randi to meet to discuss new content pattern
- [x] Review authenticated and unauthenticated pages
- [x] Rework prescription page (Aliyah)
- [x] Rework secure messaging page (Aliyah)
- [x] Rework appointments page (Katherine)
- [x] Rework lab and test results page (Katherine)
- [ ] Edit prescription page (Laura)
- [ ] Edit secure messaging page (Laura)
- [ ] Edit appointments page (Laura)
- [ ] Edit lab and test results page (Laura)
- [ ] Copyedit prescription page (Megan)
- [ ] Copyedit secure messaging page (Megan)
- [ ] Copyedit appointments page (Megan)
- [ ] Copyedit lab and test results page (Megan)
- [ ] Give final copy to Danielle in ticket # for final review

## Acceptance Criteria
- [ ] Health care tool pages are ready for OCTO-DE review

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Will add an example of new pattern to ticket for team to work off of. Moving to next sprint.

**Comment by SgardnerPMP** [comment]
This page is required and creates a dependency to Ticket #33349.   Please associate both and complete at the same time.

**Comment by aliyahblackmore** [comment]
Updating here: tbd, Katherine and Aliyah will likely split these pages!

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I'm posting the drafts for the "Schedule your appointments" and "Check your lab results" pages here. 

Schedule your appointments:
non-Cerner [https://app.zenhub.com/files/133843125/869ff161-f822-4e97-8a40-f40d11646ad1/download](https://app.zenhub.com/files/133843125/869ff161-f822-4e97-8a40-f40d11646ad1/download)

Cerner 
[https://app.zenhub.com/files/133843125/e822eaa9-431e-41f0-9986-859b38cd776b/download](https://app.zenhub.com/files/133843125/e822eaa9-431e-41f0-9986-859b38cd776b/download)

Check your lab results: 

non-Cerner [https://app.zenhub.com/files/133843125/df36dd85-ccf1-44e5-b81f-f6faebcccb1c/download](https://app.zenhub.com/files/133843125/df36dd85-ccf1-44e5-b81f-f6faebcccb1c/download)

Cerner 
[https://app.zenhub.com/files/133843125/64f835c1-0d9f-4839-93dc-2984ca3cd1a4/download](https://app.zenhub.com/files/133843125/64f835c1-0d9f-4839-93dc-2984ca3cd1a4/download)

**Comment by aliyahblackmore** [comment]
Update: I'm digging  through some Secure Messaging resources and I'm almost at the end of this page. I'll continue tomorrow and then take a look at the Cerner version and add notes on that doc!

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! Here is the drafted secure messaging page. I've included a few comments and questions in the non-cerner  and cerner versions of the page. 

[VA Secure Messaging Non Cerner Version _AB_7.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9234713/VA.Secure.Messaging.Non.Cerner.Version._AB_7.22.docx)
[VA Secure Messaging Cerner Version_AB_7.26.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9234714/VA.Secure.Messaging.Cerner.Version_AB_7.26.docx)

**Comment by aliyahblackmore** [comment]
Update: Finished the full draft of the non Cerner Refill and track prescription page. Will done a read through tomorrow morning and then make changes to the Cerner version!

**Comment by aliyahblackmore** [comment]
Hi @laurwill the prescription tool page is ready for you! I've included a few comments and questions in the Non-Cerner and Cerner versions of the page.

**Non Cerner version**
[Refill and Track Prescriptions Non Cerner Version _AB_8.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9266293/Refill.and.Track.Prescriptions.Non.Cerner.Version._AB_8.1.docx)

**Cerner version**
[Refill and Track Prescriptions Cerner Version_AB_8.4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9266296/Refill.and.Track.Prescriptions.Cerner.Version_AB_8.4.docx)

**Comment by RLHecht** [comment]
I created separate tickets for each of these pages to make them easier to track. Going to close this.
