### ISSUE TITLE
526 - Task List Pattern - Phase 1

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#34120]
## Issue Description
In our efforts to shorten the length of the 526 form, we have decided to pursue a new pattern called the 'task list pattern'. A similar concept would be the pattern found on [gov.uk](https://design-system.service.gov.uk/patterns/task-list-pages/). 

---
## Tasks
- [x] Create a design for the 'table of contents' or 'intro' page for the task list pattern

## Acceptance Criteria
- [x] Design has been created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
A preliminary design for the task list pattern's table of contents has been created:

https://www.sketch.com/s/be3ed2e2-a355-41e7-a1ce-a80779594fc5

We still have a handful of questions to work through, and after discussing it with design leadership and with Christian, we have decided to 'zoom out' and focus on more general tasks initially, so we can create a pattern that takes global considerations into effect. 

However, the acceptance criteria of this ticket has been satisfied, so will be closing this ticket.
