### ISSUE TITLE
Get stakeholder approval and publish 3 education R&S articles

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34121]
## Issue Description
We sent stakeholders 3 new education R&S articles to review on 12/14. Once they are approved, we need to publish these.

The articles are:
- Will I have to pay back the GI Bill benefits I used if I fail a class? http://preview-prod.vfs.va.gov/preview?nodeId=37410
-  Getting a GI Bill extension http://preview-prod.vfs.va.gov/preview?nodeId=41926
 - Montgomery GI Bill refunds http://preview-prod.vfs.va.gov/preview?nodeId=37333

## Tasks
- [x] Make any edits from stakeholders (Laura)
- [x] Final copy edit and review checklist (Randi)
- [x] Publish articles (Randi)
- [x] Complete post-publishing items from checklist (Randi)
- [x] Notify stakeholders that articles are live (Beth/Randi)

## Acceptance Criteria
- [x] Articles are live on site

**Comment by bethpottsVADEPO** [comment]
@RLHecht Since this one got approved, go ahead and run through the pre-pub checklist and we can get it live today: Will I have to pay back the GI Bill benefits I used if I fail a class? http://preview-prod.vfs.va.gov/preview?nodeId=37410

Then for this one, would you create an additional single Q&A to add to this larger article under "Can I get a Montgomery GI Bill refund?:
Will I have to pay back the GI Bill benefits I used if I fail a class? http://preview-prod.vfs.va.gov/preview?nodeId=37410

H1: What if I transferred my Post-9/11 GI Bill benefits to my dependent?

If you transferred your Post-9/11 GI Bill benefits to your dependent and they used up all of your entitlement, you don't qualify for the MGIB refund. But if your dependent used only some of your entitlement, and you were the last one to use the benefit, you may be eligible for the refund.

I will have to work on the last paragraph's edits for the refund page after an upcoming meeting I have! Will post here shortly.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Here's what you can add to the last paragraph. Just a "note" under the text that's already there. You're cc'd on the email to SMEs where I ask which phone number to use for this, so just plug it in when Myriah responds:

**Note:** If you believe you should have received a refund but didn’t, please call us at XXX-XXX-XXXX

**Comment by bethpottsVADEPO** [comment]
@RLHecht I just reviewed the last of these 3 articles (extension) and swapped the years as the SME indicated. I don't think it works to put the note in the intro, so I'm adding a a bit to the first sentence. Please copyedit, and thank you!

**Comment by RLHecht** [comment]
These articles are all published. Waiting until they are live to add them to our master list in Github.

**Comment by RLHecht** [comment]
These are all live and the stakeholders notified. Closing ticket.
