### ISSUE TITLE
[VAMC] Research best software to utilize for PAO CoP Forum [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34131]
## Story
As a VAMC editor I need to have a place to submit questions to the community of practice, so I can quickly get answers from team members that have already experienced or resolved similar issues.

## TASKS
- [ ] Research whether Teams or SharePoint can house a CoP Forum
- [ ] Test Teams forum settings and see if it will provide files, threads, or other features
- [ ] Test SharePoint Forum settings and see if it will provide files, threads, or other features.

## Acceptance criteria
* Artifact that provides best recommendation for VHA DM to proceed with a CoP Forum set up.

**Comment by SgardnerPMP** [comment]
Teams will be the easiest to change ownership, but SharePoint does have an add on app to create a blog, that can be shared.  Unfortunately, that will require a lot of administration.  A new forum or forum like discussion in Teams will be the easiest to create with VHA.
