### ISSUE TITLE
[VAMC] Full Production/Go Live Pre and launch for December 8th th for System going into Full production [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34132]
## Story
As an editor I need to know of any additional final clean up items and barriers, and all tech-debt needs to be resolved, so MVP is present and/or I can clean them up prior to Go Live

## Goal
Prepare the site for Full Production, update tech-debt and record areas that need updating by the PAO.  Make recommendation to VHA for production, submit request for web approval, and redirect via Web Ops

## Task
**Prepare the following Systems for Full Production/Redirect from Legacy URL**

- [x] Create file with these headers (Facility_ID;URL;COVID-19_Vaccine_URL)
- [x] VISN 15	VA St Louis health care
- [x] VISN 22	VA Greater Los Angelos health care
- [x] VISN 22	VA Northern Arizona health care
- [x] VISN 15	VA Eastern Kansas health care

## Acceptance criteria
- [x] Recommendation sent to VHA digital media
- [x] All areas above are complete and/or reported for correction to PAO
- [x] Launch blockers are reported and system is removed from Go Live if blocker is not removed prior to cut over.
