### ISSUE TITLE
Draft or Initialize the Prototype For View -> Appoint Process

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34135]
## Background
We need to start the prototyping process for this feature so that we can take it to Veterans and have them validate that it meets their needs

## Considerations
- This is a start; full completion might not occur in this ticket
- Mobile along side would be great, but not NEEDED yet
- Prototype will ultimately need authenticated and unauthenticated flows

## Tasks
- [x] Take a look at Jim's template, see if it helps jump start
- [x] Review an unauthenticated workflow requirements
- [x] Draft the prototype for this process within this feature

## Acceptance Criteria
- [x] A prototype source file has been created

**Comment by sporeboy** [comment]
Initial draft of prototype follows an unauthenticated workflow. The UXPin screens begin here: https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145370991
