### ISSUE TITLE
[Quality Assurance Audit] Post Production Audit Part 2 of VAMC VA Columbia, SC for content, plain language standards, formatting.[CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34149]
## User Story
As a VHA Digital Media web manager, the system websites need to be audited for standardization and mistakes, so websites can be updated an corrected to meet design standards.

## Goal
Remove deviations from standards. 

## Resources - Tools - Documentation
[Audit Part 1 checklist](https://salientcrgt.sharepoint.com/sites/VSATeam/SitePages/Home.aspx)

## Tasks
Using the audit Part 1 check list, review all pages that appear to be written or added after dual-state publishing. Use input from BA team to determine pages that need most attention. (Pass or Fail) web pages and provide notes:

**PART TWO**
- [ ] Review all pages for content and plain language standards
- [ ] Add Content to word document to track changes and use as document to train customer.
**Focus on new pages, or pages that were changed/created**

## Acceptance Criteria
- [ ] Rename the file with new Date/ audit final [date] and save in:
[QA_Documents folder]
- [ ] Content has completed review of new/changed pages
- [ ] Word Document(s) with corrections/proposed changes is saved in QA Documents folder
