### ISSUE TITLE
User wireframes and user flow for Submit Feedback Tool

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34152]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
Right now, the rating system only captures if the user rates the page as either 'good' or 'bad'. This update will collect additional feedback if a user selects 'bad'. If they select 'bad', another option will appear that will allow them to select a problem on the page, such as 'broken link'.

![Screen Shot 2021-12-15 at 9.37.07 AM.png](https://images.zenhubusercontent.com/61b2600c16c9626a4c0b07c6/03cdf1a2-e209-4193-80eb-8ce44df80bab)

Additionally we need to research to determine what selections we would like to present to the Veterans when selecting Bad.

Question: Should we also present for Good? 

## OKR
_Which Objective / Key Result does this epic push forward?_

## Tasks
- [x] _Create wireframes for submit feedback tool 2.0_
- [x] _Create user flow for submit feedback tool 2.0_

## Acceptance Criteria
- [x] _Initial wireframes and user flow for submit feedback tool are complete_
---
## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mgleo** [comment]
Consideration: Elsewhere on VA.gov, users are asked for feedback using this blue feedback button. Consider utilizing the blue feedback button for style consistency and to prevent pushing content further down the page.
![Screen Shot 2021-12-28 at 2.53.54 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/1f51585c-8434-4508-96cb-2c0ddae7ca67)



Wireframes/ User flow: 
![submit-feedback-userflow-wireframes.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/23dc819a-ebf4-4129-9c33-b477b663aae8)
