### ISSUE TITLE
[Design] Cross Site Linking for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3415]
## Story
As a Veteran using VA.gov, I want to be able to easily go between the Rated Disabilities Tool page and the VA Combined Disability Rating Calculator so I can test different ratings for myself and take action where needed in order to get the most benefits I deserve.

## Tasks
- [x] Mockup a link to the [VA Combined Disability Rating Calculator](https://www.va.gov/disability/about-disability-ratings/)
  - [x] Establish any language that needs to help describe what the Veteran is looking at 
- [x] Check in with Shawna
- [x] Check in with Content Team  (Peggy)
- [x] Check in with IA Team (Mikki)

## Acceptance Criteria
- [x] Create a mockup to share with FEs and other reviewers

**Comment by sporeboy** [comment]
Preliminary mockup here: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/1d4fafce-8d16-4a89-a14b-97d795772b74/RD-Screen-Tool-2ALT

**Comment by sporeboy** [comment]
Link to Disability Ratings Calculator page added to new Rated Disabilities screen: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/1d4fafce-8d16-4a89-a14b-97d795772b74/RD-Screen-Tool-2ALT

**Removed:** "What if I don't see the disability rating I was expecting" section. Some of this copy was moved to intro text.

**Added:** "Learn about VA disability Ratings" section with new copy and a link to the Disability Ratings Calculator page: https://www.va.gov/disability/about-disability-ratings/

Input/review/feedback welcome @peggygannon @mnorthuis
