### ISSUE TITLE
[Design] My VA: Review and update/cleanup Sketch files for My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34155]
## Background

This is a ticket for My VA Sketch file clean-up efforts. 

## Tasks

- [ ] Update artboards to use pattern library symbols (VA.gov pattern library and Auth exp library) wherever possible. 
    - For sure the header and nametags need to be updated to use the symbol from the Auth library
    - Footer and instances of the additional info component likely need to be updated to use the symbol from the VA.gov library
    - probably other things as needed
- [ ] Align spacing and layout with what is on staging (e.g. columns should be 460px instead of 478)
- [ ] Apply for benefit section needs updates to match staging (add health care benefit block + update verbiage for heading above)
- [ ] Any other improvements you notice

## Acceptance Criteria

- [ ] All Sketch files are reviewed and cleaned up, so that they are inline with our current work and direction

**Comment by tressaellen** [comment]
Here's the [sketch file we'll be working on.](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9)

**Comment by andaleliz** [comment]
@tressaellen you haven't completed this, correct? I have not started, so I think we need to move this into the next sprint.

**Comment by tressaellen** [comment]
It's like half way done, but I don't think i'll have time to finish it today. @hdjustice this will need to be in next sprint.

**Comment by hdjustice** [comment]
@andaleliz @tressaellen Moved to next sprint.  Thanks!

**Comment by andaleliz** [comment]
@hdjustice and @Samara-Strauss, @aagosto90  is going to take this on. It's a good way for her to get familiar with My VA and our Sketch files.

Angela, I will add the payment info artboards to the doc as soon as I'm done cleaning up the icon issue I mentioned, and add an error state. I don't think you need to wait for me to get started though.

**Comment by aagosto90** [comment]
@tmitchellgcio I'm comparing the MyVA Sketch file to staging and seeing a discrepancy in one of the heading styles between what we have in staging, in Sketch, and in the VA pattern library. It's for our H3 style, used for subheadings like  "Applications in progress" and "Explore VA benefits and health care." It's currently Source Sans Pro 17px (700 weight) in staging. It's 18px in my Sketch file and I think what it should really be is 16px because that's what I'm seeing in the VA pattern library and elsewhere on the site. Is that an easy fix to make the H3 style 16px instead of 17? I think that's the only change needed. 

Of course if this was a conscious decision made before my time, let me know and I'll just match the Sketch file to staging. Thanks!

**Comment by tmitchellgcio** [comment]
I think we can do that. No worries. It's the same font size as an H4, but I don't know if it was a conscious decision as it was before my time I believe

**Comment by aagosto90** [comment]
Done updating Sketch file as of 2/18 and will give @andaleliz a quick overview on 2/23. Closing this issue.
