### ISSUE TITLE
[VAMC] Draft and outline "how to" artifact for pulling legacy content and transforming that content to new page {CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34150]
## Story
As a VA web content writer I need to best understand how to transform my site, so I can utilize plain language, va.gov design content, and how to write in general terms that will best support a Veteran centric web site.

## Audience
This document will help support future editors and transformation of a legacy website.

## TASKS
- [x] Start by framing out steps to begin pulling, reviewing, and translating content.
- [x] Outline steps in a "How to" format, keeping consideration of both singular/local and multiple site options that may require using general terms.
- [ ] Document all steps in Mural form sheet.

## Acceptance criteria
- [ ] Draft artifact created that provides steps, guidelines, and tips to translate content from legacy to new format
*  Utilize Mural collaboration, and save for future stories and tasks
