### ISSUE TITLE
[FE] Add Link to Disability Calculator on Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3417]
## Story
We need a design for where this link will be placed, what it is supposed to look like on desktop and mobile. We will also need the content that will surround the link. We can start building this before we have the design but we at least need a basic outline of what we are doing.

As a Veteran using VA.gov, I want to be able to easily go between the Rated Disabilities Tool page and the VA Combined Disability Rating Calculator so I can test different ratings for myself and take action where needed in order to get the most benefits I deserve.

## Considerations
- [Mockup for this](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/1d4fafce-8d16-4a89-a14b-97d795772b74/RD-Screen-Tool-2ALT)

## Tasks
- [x] Code a new content block inside the right rail for the Combined Disability Rating Calculator
- [x] Add a link to the [VA Combined Disability Rating Calculator](https://www.va.gov/disability/about-disability-ratings/) to the new content block
- [ ] Cross team coordination with Analytics for event tracking
- [x] Remember, there is a change in the intro block

## Acceptance Criteria
- [x] Publish link and language in proper component
