### ISSUE TITLE
[FE] Remove unused `fieldOwner` fields for CLP in favor of `fieldRelatedOffice`

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34188]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to easily explore and navigate the outreach and events page. 

## Description
- As a result of our CMS discussion it was determined that we need to remove unused `fieldOwner` fields for CLP in favor of `fieldRelatedOffice`.   

## Tasks
- [ ] Remove unused `fieldOwner` fields for CLP in favor of `fieldRelatedOffice`
- [ ] Test and validate function is working properly with no side affects | Collaborate with CMS
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [x] Remove unused `fieldOwner` fields for CLP in favor of `fieldRelatedOffice`.

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy today
