### ISSUE TITLE
[MCP] Create an alternative facility detail page for if the most recent statement is past the payment due date

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#34181]
## Issue Description
If the Veteran has neither paid their copay/prescription charges balance nor requested financial help within the due date, we should display an alert that indicates they should contact HRC immediately to resolve the balance. 

---
## Tasks
- [x] Create an alert directing Veterans to contact HRC immediately if the current date is past their due date 
- [x] Present the design to the team to validate that the alert works with the backend data
- [x] Set up time to present the approved designs to Jill + VA team 

## Acceptance Criteria
- [x] The UXPin has been linked to this ticket

**Comment by rileyorr** [comment]
@denisecoveyduc I added the designs to UXPin:
- [Overview page](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/145208033/simulate/sitemap?mode=i)
- [Detail page](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/145208032/simulate/sitemap?mode=i) 

I'm going to attend this afternoon's content office hours to review the content prior to our meeting with Jill and Matt. I'll also drop this into our slack channel in case our team wants to take a look before I get the content reviewed :)

**Comment by rileyorr** [comment]
Met with Beth and incorporated her content feedback. We should be good share this design with our stakeholders!

**Comment by rileyorr** [comment]
Presented to Jill + Matt! @denisecoveyduc would you like to send the approved designs to the VHA folks or would you like me to?

**Comment by rileyorr** [comment]
Sent the designs to Thuy, Daniel, and Brandon for review

**Comment by rileyorr** [comment]
The VHA team requested a meeting in the new year to discuss the designs - considering this ticket completed and will open a new one if there are any edits once that meeting happens
