### ISSUE TITLE
[Design] Personal Info Revision - Update Sketch files to reflect new open text/required field business requirements

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34187]
## Background

[Related Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1639587317423200)
Update Sketch files to reflect recent revelation that MPI cannot currently support an open text field for Gender Identity

## Tasks
- [x] Update Sketch files for Personal Info Revision to remove open text field from Gender Identity section
- [x] Update Sketch files to show how the Preferred Name field will be shown as required IF a value already exists.  In other words, once a user enters and saves a value in this field, it becomes required from then on.  They cannot clear out this field.

## Acceptance Criteria
- [x] Sketch files for Personal Info Revision are updated to remove open text field from Gender Identity section
- [x] Sketch files for Personal Info Revision show how the Preferred Name field will be shown as required IF a value already exists.  In other words, once a user enters and saves a value in this field, it becomes required from then on.  They cannot clear out this field.

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO - Should the second task be for Preferred name rather than Gender Identity? Sketch files have been updated with both the removal of open text field/error message for Gender identity and the addition of the requirement error for Preferred name (if user tries to remove the value without entering a new one once an initial value has been entered). 

Updated Sketch Files: https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske yes, thank you! I just updated it to say Preferred Name.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - I am so sorry I am just now getting a chance to review this.  

This really looks good!  I found just a few minor things in the Sketch files: 

- Page 6 - Pronouns - the word 'preferred' is spelled incorrectly in the list of options. 
- Page  6 - Pronouns shows 25 characters maximum above text field
- Page 6 & 7 - Pronouns -  Page 6 has "Use my preffered name' for the 5th option and Page 7 has "Patient name".  Content suggested that we have "Use my preferred name".
- Page 10 for Sexual orientation shows 25 characters maximum above the text field 

The prototype looks great!!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Thanks for pointing those out! I'm going to look into if there is a spellcheck plugin for Sketch to help avoid those little errors. 
Everything you mentioned has been corrected!

**Comment by MarciMcGuireGCIO** [comment]
Awesome!! That was super-fast! Thank you!
