### ISSUE TITLE
HLR: JS error with missing mobile phone

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34182]
## Description

A JavaScript error occurs on the Higher-Level Review contact information page when a Veteran doesn't have a mobile phone number in the system.

## Tasks
- [ ] Prevent JS error
- [ ] Add tests

## Definition of ddnoe
- [ ] All tasks complete
- [ ] All tests passing
