### ISSUE TITLE
Replace all `AdditionalInfo` components in our apps with va-additional-info components

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#34194]
## Background
The VSP team has published a new version of the component library where they have replaced the React `AdditionalInfo` component with a `va-additional-info` web component. We will need to go through our apps and replace these with the new web components otherwise our tests will start failing builds.

## Considerations
[Slack conversation about this](https://dsva.slack.com/archives/C5HP4GN3F/p1639521879222800)

### Apps we own
- [x] `src/applications/disability-benefits/686c-674`
- [x] `src/applications/disability-benefits/view-payments`
- [x] `src/applications/lgy/coe`
- [x] `src/applications/personalization/rated-disabilites`
- [x] `src/applications/personalization/view-dependents`
- [x] `src/applications/personalization/view-representative`
- [x] `src/applications/vre/28-1900`
- [x] `src/applications/vre/28-8832`

## Tasks 
- [x] Search through our apps for `AdditionalInfo` components and replace them with the `va-additional-info` component
- [x] Make sure all unit and end to end tests still pass
- [x] Create a PR for review

## Acceptance Criteria
- [x] All components are switched over
- [x] A PR has been requested for merging  (or multiples as needed `dealers-choice`)
