### ISSUE TITLE
Update VRRAP page with 2 new list of schools PDFs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34197]
## Issue Description
Stakeholder Terry Warren provided us with new PDFs for participating schools to be put on the [Veteran Rapid Retraining Assistance Program page](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/). 

These PDFs are divided alphabetically by state: Arizona to Kansas and Kentucky to Wyoming, and will replace the one big PDF that is currently there with the link "Check the list of schools participating in VRRAP (PDF)." 

PDFs: https://benefits.va.gov/gibill/docs/ApprovedVRRAPSchools_Part_I_AZ-KS.pdf
https://benefits.va.gov/gibill/docs/ApprovedVRRAPSchools_Part_II_KS-WY.pdf
 
---
## Tasks
- [x] Update links with new language on page (Selina)
- [x] Copyedit (Randi)
- [x] Final review (Beth)
- [x] Publish (Randi)
- [x] Notify stakeholder changes are live (Randi)

## Acceptance Criteria
- [x] New PDFs are on live VRRAP page

**Comment by lunascoop** [comment]
@RLHecht I updated the links and bulleted list formatting in the eligibility section.

Veteran Rapid Retraining Assistance Program (VRRAP): http://preview-prod.vfs.va.gov/preview?nodeId=17942

**Comment by RLHecht** [comment]
Thanks, @lunascoop. I reviewed and added a sentence above the links about how we list these alphabetically. @bethpottsVADEPO This is ready for you to review.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop The first PDF starts with Alabama and includes Arkansas but Terry's PDF at the top says, "Approved VRRAP Schools Part I, AZ - KS (so it doesn't indicate that Alabama and Arkansas are included--and it needs to change to reflect that). This first PDF also goes through Indiana (but tacks on 2 KS schools). 

Questions for you/Terry: Are there really only 2 KS schools? Those are included in the first PDF. Could Kansas schools be moved over to the second PDF so that we aren't splitting up the K states into 2 PDFs? I just think this will be easier for Veterans to find what they need.

And then ask if he would please change the little header at the top of his first PDF to say: Part I, AL - IN (or AL - KS if we have to keep KS for some reason on the first PDF). And then similar changes at the top of the second PDF according to whatever's decided as far as where Kansas belongs.

Then the content team should make that corresponding change in our text. And here are some edits I have too (we need to account for the fact that there are 2 lists now, and I think we should stress the states being grouped alphabetically--rather than the schools--since that's the first narrowing Veterans will need to do to decide which PDF to open):

**For Veterans:** Find participating schools listed in these 2 PDFs. We grouped the schools by the state where they're located and split the states into 2 alphabetical lists. The first PDF has Alabama through Indiana. The second PDF has Kansas through Wyoming. We'll update these lists as schools sign up.
- Find participating schools in states that begin with the letters A - I (Alabama through Indiana) (PDF)
- Find participating schools in states that begin with the letters K - W (Kansas through Wyoming) (PDF)

---------------
Note for Randi: If the link text is too long above once you get it in Drupal, we can look at shortening.

**Comment by RLHecht** [comment]
@lunascoop Here are the updated PDFs. Could you please update the page and I'll review?

https://benefits.va.gov/gibill/docs/ApprovedVRRAPSchools_Part_I_AL-IN.pdf
https://benefits.va.gov/gibill/docs/ApprovedVRRAPSchools_Part_II_KS-WY.pdf

**Comment by lunascoop** [comment]
@RLHecht I updated this page

Veteran Rapid Retraining Assistance Program (VRRAP): http://preview-prod.vfs.va.gov/preview?nodeId=17942

**Comment by RLHecht** [comment]
I published this page. Will close and notify the stakeholder when changes are live.

**Comment by RLHecht** [comment]
Page is live. Closing ticket.
