### ISSUE TITLE
Clean up ccp route

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34208]
## Issue Description
Now that we have fully moved to the rails engine and confirmed no other traffic is pointed to the endpoint, we can clean up uneeded code for the ccp route. 

---
## Tasks
- [ ] Remove unneeded code supporting the deprecated ccp route

## Acceptance Criteria
- [ ] Facility Locator functionality is maintained
- [ ] Unneeded code supporting the ccp route is no longer present
