### ISSUE TITLE
[VAMC] Validate VAMC web pages that are showing as duplicate or obsoltete w/o parrent [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34201]
## Resources
Listingfrom CMS

## TASKS
Review pages provided by CMS team that do not have parent menu link and are not published.
- [x] Validate that the page does not have a parent menu item, determine if it is obsolete, a duplicate, or possibly in development.
- [x] Delete duplicates or obsolete pages
- [x] List all pages that maybe in development or need attention

## Acceptance Criteria
- [x] All obsolete pages are deleted and documented as such on list
- [x] Highlight pages that need further investigation

**Comment by ltrombley** [comment]
Task #34201 - Validate VAMC web pages that are showing as duplicate or obsolete w/o parent [BA]  - is Complete and moved to Validate.
