### ISSUE TITLE
[FE] Pre-check-in Confirmation Page Updates

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#34210]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

- Change the word "Pre check-in" to "Pre-check-in" in h1 on the confirmation page
- Add information icon to alert message on confirmation page

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/bgQbOdj)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

Update h1 text and add icon to alert box on pre-check-in confirmation page

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update h1 on confirmation page
- [ ] add icon to alert
- [ ] update unit and e2e tests that check confirmation page title

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
