### ISSUE TITLE
[FE][SPIKE] Modal Edit button

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34218]
## User Story

A veteran should be able to edit a value in a modal that pops up 

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Can we display a button next to a field that shows a modal
- [ ] Can take the new input field data and put int redux
- [ ] make this reusable 
- [ ] Make an API when done editing a field 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by jparker0425** [comment]
Hey @brianseek ! Would you mind adding what the dependency is for this item when you get chance?

**Comment by brianseek** [comment]
thanks for the reminder @jparker0425! This is blocked by new UX that may not include a modal: https://dsva.slack.com/archives/C02G6AB3ZRS/p1639763573409800
