### ISSUE TITLE
COE | Error Handling

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34212]
## Background
For statuses that might not exist or instances of client side failure, or server side failures, we need to ensure we have error handling in place so that a Veteran can see when errors occur to try again later.

## Considerations
- ~~FE will do placeholders for now until updated content is in place~~ [Status locations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36022#issuecomment-1032928314) and a nice linked version: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/146308490/simulate/sitemap
- Might be in three distinct locations
- intro page (status check)
- eligibility determination page
- docs list

## Tasks
- [x] Ensure that there are error messages for instances where there are issues client side (4XX errors)
- [x] Ensure that there are error messages for instances where there are issues server side (5XX errors)

## Acceptance Criteria
- [x] Error handling for client side is in place
- [x] Error handling for server side is in place
- [x] A PR has been requested for merging

**Comment by tblackwe** [comment]
@DLarson-Oddball Can you please take a look at this issue, determine if it is still relevant, and if so, size the effort to resolve?

**Comment by tblackwe** [comment]
The blocking issue is closed, and everything is checked off in tasks. hoping we can close this out.

**Comment by steele-lm** [comment]
Ticket current blocked. There is [a code change](https://github.com/department-of-veterans-affairs/vets-website/pull/20738) that is currently closed, but still relevant. Dakota connecting with Eugene to better understand the work necessary in revitalizing that closed PR.
