### ISSUE TITLE
[Research] Martinsburg Research Plan

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34221]
Description: Since we are expanding to 4-5 clinics in hematology and oncology, we want to gather Veteran and staff at the new locations after it goes live.

**What functionality does the Veteran need at launch?**
- To be able to check in to appointments and receive care. 
- Ability to check in easily if blind/visually impaired. Alternative to poster? (Team agreed we value ensuring our product is accessible to vision-impaired folks.)
- Reassurance that the process worked, and assurance that the staff won't ask them for the same info on appointment day.
- Assurance that their information gets updated across the VA.

**What do the MSAs need at launch?**
- An easy way to see pre-check in status.
- An easy way to know if they need to review contact or insurance information.
- Confidence that no Veterans will slip through the cracks.

**What must be true within the product ecosystem?**
- Clinic has sufficient wif/phone coverage to use mobile check-in.

**Related Documentation**
[- Team North Star Vision for MVP
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/decisions/DecisionRegister.md)

**Tasks**
- [x] Create new folder for this specific test in this overall research folder. 
- [x] Create research plan
- [x] Utilize the new research plan template developed by the research ops group.
- [x] Create conversation guide

**Acceptance Criteria**
- [ ] Review draft research plan and conversation guide with team
- [ ] Submit to Lauren Alexanderson and cc Kevin Hoffman and Shane Strassberg 
- [x] Plan posted to GitHub

**Comment by Evafloyd** [comment]
We're switching to staff feedback intake due to Omicron and expectations that we won't be able to conduct the research in person. Let's consider using https://www.optimalworkshop.com/questions/ to question intake.

**Comment by Evafloyd** [comment]
Building a page here https://github.com/department-of-veterans-affairs/va.gov-team/new/master/products/health-care/checkin/research/veteran-facing

**Comment by kristenmcconnell** [comment]
Research folder with research plan and conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/Martinsburg-Staff-Moderated

**Comment by kristenmcconnell** [comment]
Research repo ticket: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/68#issuecomment-1007702644

**Comment by kristenmcconnell** [comment]
Research was approved by platform via Slack. ![Screen Shot 2022-01-10 at 1.01.46 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/99835fb7-f24a-43cd-863d-576d80d68297)

**Comment by kristenmcconnell** [comment]
The research plan has been updated to address @sstrassberg's comments in the research repo ticket. Will be creating a new ticket to finalize the Optimal Workshop survey and Interactive PDF.

**Comment by kristenmcconnell** [comment]
New ticket for Optimal Workshop survey and Interactive PDF is https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/35057
