### ISSUE TITLE
Replace all `LoadingIndicator` components in our apps with `va-loading-indicator` components

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#34222]
## Background
The VSP team has published a new version of the component library where they have replaced the React `LoadingIndicator` component with a `va-loading-indicator` web component. We will need to go through our apps and replace these with the new web components otherwise our tests will start failing builds.

### Apps we own
- [x] `src/applications/disability-benefits/686c-674`
- [x] `src/applications/disability-benefits/view-payments`
- [x] `src/applications/lgy/coe`
- [x] `src/applications/personalization/rated-disabilites`
- [x] `src/applications/personalization/view-dependents`
- [x] `src/applications/personalization/view-representative`
- [x] `src/applications/vre/28-1900`
- [x] `src/applications/vre/28-8832`

## Tasks 
- [x] Search through our apps for `LoadingIndicator` components and replace them with the `va-loading-indicator` component
- [x] Make sure all unit and end to end tests still pass
- [x] Create a PR for review

## Acceptance Criteria
- [x] All components are switched over
- [ ] A PR has been requested for merging  (or multiples as needed `dealers-choice`)
