### ISSUE TITLE
[Design] FE Design Audit for Pre-check-in

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34225]
Description: 
UX reviews FE tickets, reviews staging or screenshots, and answers engineering questions.

**Tasks:**
- [ ] Document what we review in Design Audit section in Sketch and any changes
- [ ] Post a link in FE tickets to the Sketch section
- [ ] Review mobile and desktop

**Acceptance Criteria:**
- [ ] Everything is reviewed and gaps are communicated with engineering
- [ ] Answering engineerings questions

[FE Audit Emergency contact (Mobile) Example]
(https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/Gm5VG7w)

**Comment by kristenmcconnell** [comment]
Patrick noticed a lot of UX behavior items and documented them in this [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1639593586309500).

**Comment by kristenmcconnell** [comment]
Upon review by @niradatta1 and @ytsaoca, the following items from Patrick's review will be added to the scope of this ticket...

- test different browser options
- recommendations for sticky footer (though, would this involve another team? do we "own" the decision on what to do with that banner?)

**Comment by kristenmcconnell** [comment]
@jparker0425 is going to help get you access to URL and test users.

**Comment by julieadair1** [comment]
@kristenmcconnell @ytsaoca - should we go ahead and close this ticket since all of the recommendations from the audit have associated tickets now?  
cc: @jparker0425

**Comment by kristenmcconnell** [comment]
I think we should close it out since the audit has been turned into new tickets. I think we need a new ticket though for Nira and Ya-ching to review the implementation of said new tickets.

I will defer to @ytsaoca and @niradatta1 though.

**Comment by jparker0425** [comment]
I agree this ticket should be closed at this point. If there are any subsequent tickets that are needed they can be created. @kristenmcconnell @julieadair1 @ytsaoca @niradatta1 

I am going to go ahead and close this out. Please let me or @julieadair1 know if there is additional work needed out of this and we will assist with those items.

**Comment by kristenmcconnell** [comment]
The above mentioned ticket is where @niradatta1 and @ytsaoca can review the implementation of the items that came out of this audit.
