### ISSUE TITLE
API Migration

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34231]
## Issue Description

Document plan for api migration from EVSS to Lighthouse
Link to [slack thread](https://dsva.slack.com/archives/C02G07X54C8/p1639604879053600). 

---
## Tasks
- [ ] Document migration tasks
- [ ] Document implementation plan
(create new epic)

## Acceptance Criteria
- [ ] Plans documented, new tickets created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cnemeth** [comment]
This ticket seems to be included in [ticket #35202, Claim Status Tool Migration - Phase 1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35202). 

According to Kayla Watanabe, the migration planning and implementation is/will be preformed by the Lighthouse and Claims API teams, respectively.
