### ISSUE TITLE
[FE] Personal Information Revision: Update Notification Preferences to point to new contact page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34241]
## Background

On the Notification Preferences page, we show a prompt to add a mobile phone number if people do not have one in their profiles. Right now, this link goes to www.va.gov/profile/personal-information/ , which is where contact information currently lives. However, once we launch the personal information updates, contact information will live on www.va.gov/profile/contact-information/. So, we should update that link accordingly, push that update to staging, but gate the update so it does not go to prod until all of the personal information changes go out. 

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/13f51c03-a6a3-40b5-86bf-3ec84021d738)

## Tasks

- [x] Change URL for `Add a mobile phone number to your profile` link on Notification Preferences page from www.va.gov/profile/personal-information/ to www.va.gov/profile/contact-information/
- [x] Deploy update to Staging behind a feature flag
- [x] Test
- [x] Validate with PO/PM

## Acceptance Criteria

- [ ] URL for `Add a mobile phone number to your profile` link on Notification Preferences page has been changed from www.va.gov/profile/personal-information/ to www.va.gov/profile/contact-information/
- [ ] Update is deployed to Staging behind a feature flag
- [ ] Updated is tested
- [ ] Updated is validated with PM and PO

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO I have this up and ready for review in staging if you would like to take a look

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - I am encountering an error this morning when attempting to access Notification Settings on staging. 

![image](https://user-images.githubusercontent.com/73354907/148557030-84c65ff7-c5d5-4124-98ba-ced54d00608e.png)

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - I was able to test this with user 75 per your note in Slack.  Looks great!  Thanks!
