### ISSUE TITLE
[BE] On-site Notifications: Catch up on design and VA Notify discussion

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34246]
## Background
Now that design direction is confirmed, we need to review design with BE - Lihan, validate our understanding of technical requirements and surface any concerns or requirements

## Tasks
- [ ] Review [designs ](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=30b328dd-61fa-4e9c-a615-80a4db99566d)with Tressa/Liz
- [ ] Meet with Heather to discuss latest meeting with VA Notify

## Acceptance Criteria
- [ ] Catch up on the latest information and prep to meet with VA Notify on next bi-weekly sync (1/4)

**Comment by hdjustice** [comment]
The team met to discuss the functionality to dismiss the notification, as well as meeting with VA Notify to discuss needs from both teams, and timelines.  At this time, the VA Notify team would not be able to be engaged on this effort until Mid-Feb to March.  Until then, Lihan will work on what he can.  Closing this ticket.
