### ISSUE TITLE
Staging Review Claims & Appeals - HLR v2

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34244]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
[Staging Review link](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/)
[Test user Info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/higher-level-review-testusers.md)

- [x] [Product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/Higher%20Level%20Review%20v2.md)
 
  

- [x] Release plan with the "Planning" sections completed 

[HLR v2 Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/HLR%20v2_release_plan.md)
 

### Content artifacts 

- [x] Content brief (if applicable) and your product’s content source of truth 

- [Mockups"]([link here](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6))

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test [cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/HLR%20vs%20Use%20Cases.md)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/2485) in TestRail with test execution logs 
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/276) 
- [x] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/288) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [x] Document in your product folder that indicates all required checks from the [accessibility staging review prep]
[HLR v2 Accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/accessbility.md)

- [ ] List of known issues

•	Issue 1

•	Issue 2

•	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @vhenry07  - is this ticket ready? our team didn't see the post on #vfs-platform-support

**Comment by vhenry07** [comment]
Knew I forgot something. Thanks @shiragoodman. posting now.

**Comment by shiragoodman** [comment]
@vhenry07 thanks! confirming that you're scheduled for 1/6 at 1:30pm ET.

Please be sure to add your own team to the invite - this is something that we no longer do for you. Thanks!

**Comment by tlei123** [comment]
@pjhill @ddzz , 2nd round of test-runs now completed, and QA-artifact links all updated above in main description.

Thanks much!

cc @shiragoodman @vhenry07

**Comment by shiragoodman** [comment]
Zoom recording of Staging Review: https://us06web.zoom.us/rec/share/yne-IAM0qt3AbE8azLn3RkCjWC_rQh47ufWdDzRAsQ_mB8SaU2iy0sJyFMBKjSw.ERzrECjgjr-P5W3u 
Passcode: ihn0*^P5

**Comment by vhenry07** [comment]
Issues completed.
