### ISSUE TITLE
UI Consistency for R&S Article Pages

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34256]
## Issue Description
Create design comps for [R&S Article pages](https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/) to align with the rest of VA.gov.
'Related information', 'VA Benefits', 'Need more help?' section styling should align with the rest of VA.gov.

---
## Tasks
- [x] _Research available guidance for styles and existing styles on VA.gov_
- [x] _Create high fidelity design comps for 'Related information', 'VA Benefits', 'Need more help?' section of [R&S Article pages](https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/)_

## Acceptance Criteria
- [x] _High fidelity design comps for 'Related information', 'VA Benefits', 'Need more help?' section of [R&S Article pages](https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/)_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Style guidance from VA.gov Pattern Library Sketch file:
![styles-sketch-template.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/32a307fd-d5b7-478b-9ca3-1dcc1f3c5be5)

**Comment by mgleo** [comment]
![rs-ui-article.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/3a1b2a12-31e5-4385-8e44-dd9dbd336644)

Updated sections styles:

**Related information:** 
Using the style, "Related Links, for navigating to related information outside a content section". 
While most links are within Resources and Support, there are times where from outside R&S are used. There could be an argument to use the "Major Links" section if links were restricted to only R&S links.

_Considerations:_ Link descriptions are needed for this style. There is a space for content editors to enter short link descriptions within the CMS that appears to not be utilized. Alternatively, text could be pulled in and truncated from the metadata description from those linked pages but would need more time for dev exploration. 

Used elsewhere: [Pay your VA copay bill](https://www.va.gov/health-care/pay-copay-bill/), [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

**VA benefits:** 
Using the style, "Quick Links, for navigating to related topics located outside of a section". Link descriptions are not used within this style. 

**Need help?:** 
Using the style, "Quick Links, for navigating to related topics located outside of a section". Update header from "Need more help?" to "Need help?"

Used elsewhere: [Apply for burial benefits](https://www.va.gov/burials-and-memorials/application/530/introduction)
