### ISSUE TITLE
[BE] Review and Verify API endpoints for Integration Experience team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34250]
## Background
The Integration Experience team is requesting verification of some API endpoint ownership. https://dsva.slack.com/archives/CE4304QPK/p1639581752304000

## Tasks

- [ ] Review [Endpoint Ownership Inventory spreadsheet](https://docs.google.com/spreadsheets/d/1Aze2OD1X_kbzVTV-sWBYI-pyLCY_kImheuW4Qo6_qvA/edit#gid=1584543895)
- [ ] Confirm the information for the endpoints for our team is correct
- [ ] Add any additional information as needed for any of our endpoints, including adding anything that's not already listed if there are endpoints missing

## Acceptance Criteria
- [ ] Endpoint spreadsheet has been reviewed
- [ ] Information for the endpoints for our team is correct
- [ ] Any additional information as needed for any of our endpoints, including adding anything that's not already listed if there are endpoints missing has been added

**Comment by MarciMcGuireGCIO** [comment]
@hdjustice for visibility.

**Comment by hdjustice** [comment]
@MarciMcGuireGCIO Thanks! Should we have a separate ticket for My VA? or since Lihan would be reviewing the list for Profile, might as well include looking for My VA and just have this one ticket?  Either way is fine with me.

**Comment by MarciMcGuireGCIO** [comment]
One ticket should work! 🙂

**Comment by MarciMcGuireGCIO** [comment]
@lihanli - will you have a chance to review this today or should I move to Sprint 64?  Thanks!

**Comment by lihanli** [comment]
@MarciMcGuireGCIO i can review it today

**Comment by MarciMcGuireGCIO** [comment]
That’s great; thank you! The sprint report got moved from Wed end of day to Tue end of day, so I’m trying to fill out as much as I can.

**Comment by lihanli** [comment]
i reviewed the spreadsheet and the endpoints are accurate, also the `/v0/notifications` endpoint is owned by our team

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@lihanli - did you update the spreadsheet to add the /v0/notifications endpoint?  Thx!

**Comment by lihanli** [comment]
@MarciMcGuireGCIO yes the endpoint is in the spreadsheet

**Comment by MarciMcGuireGCIO** [comment]
Thank you @lihanli !
