### ISSUE TITLE
Discovery: Synthesize User Interview Findings

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3425]
## User Story or Problem Statement
As a UX Designer, I need to synthesize gathered data from interview sessions so I can discover common themes among interviewed Veterans.

## Goal
_A document containing data from interview sessions that has been organized into common themes_

## Objectives or Key Results this is meant to further
- _Discovery sprint_
- _Finding pain points in the ordering process_
- _Discovering improvements to the ordering process_
- _The form's flow and design_

## Tasks
- [x] Create spreadsheet and organize data from interview sessions (8-12 hours for each designer)
- [x] Create themes (document already created in ticket #3424)_ (8-12 hours for each designer)

## Acceptance Criteria
- [x] Create Miro board

## Next Steps
- Create research artifacts (personas, user journeys)

## Blockers 
- None

**Comment by wygonikGCIO** [comment]
Riley/Becca can "Task" and "Next Step"s be added to this ticket.  The team is also looking at adding "Hours" to each Task. Please ball park the hours.  (i.e. Task: interviews: 10 hours)

**Comment by rileyorr** [comment]
@wygonikGCIO Our synthesis can be viewed here: https://miro.com/welcomeonboard/2iapiLjAIxEYf4gZo8PQERDx47gOJ3XJEWJ2QAHzI93nyvh0BN0Yw50oVd34PqS8
