### ISSUE TITLE
HLR v2: A11y review & fix issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34266]
## Description

Perform a11y review of Higher-Level Review v2 and fix any problems

## Tasks

- [ ] Perform these [a11y checks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/accessbility.md)
- [ ] Fix any issues that  are found
- [ ] Add unit tests (if needed)

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
