### ISSUE TITLE
Prefill for COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34265]
## Background
Kelli has indicated that she thinks it would be a good idea to prefill info for the COE form.  in fact, we should pre-fill as much as we can.

## Considerations
- Prefill guidance [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/prefill_setup.md)

## Tasks
- [ ] Add the prefill information so that it appears on the form

## Acceptance Criteria
- [ ] The fields are prefilling from the profile object
- [ ] A PR has been requested for merging

**Comment by alsleaders** [comment]
Closing this because I merged the PR
