### ISSUE TITLE
Fix create release & tag failures

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#34274]
## Description

I suspect is because we have `wait-for-deploy` step, at the time of creation run, new tag, and release, the flow waiting does not have that information of version bump recently created in `content-build`

See [slack](https://dsva.slack.com/archives/C0MQ281DJ/p1639686459121600) 

## Task
- [x] Ensure workflow works as intended for single flow
- [x] Ensure workflow updates correctly for waiting flow
- [x] Flow works as intended for daily-deploy
- [x] Flow works as intended for content-release

**Comment by oseasmoran73** [comment]
Made a syntax fix for daily deploy https://github.com/department-of-veterans-affairs/content-build/pull/860

**Comment by oseasmoran73** [comment]
[Slack](https://dsva.slack.com/archives/GLDNCMRSP/p1641494510013200) convo to ask FE Tools on support during holiday if any issue has arisen before holiday freeze up until now. Seems to be very stable! Closing out ticket
