### ISSUE TITLE
[RDS Maintenance] Investigate purpose of "dsva-vagov-statping-utility-db" 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#34272]
## Description
It's possible that the "dsva-vagov-statping-utility-db" database instance is no longer used. If this is not needed, let's take a final snapshot, and decommission the instance. 

## Background/context 
It would appear that there have been 0 connections over the past 2 weeks. (see image below) ![Screen Shot 2021-12-16 at 13.36.12.png](https://images.zenhubusercontent.com/5f5a5f39c4fbcc3da3615466/2ab9975c-64a7-4056-91fc-cc82215bd440)

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Figure out if this is needed
- [ ] If not needed, backup and decommission the instance

## Acceptance Criteria 
- [ ] Determination has been made as to whether or not this is needed
- [ ] If not needed, the instance and data have been backed up and the machine has been decommissioned

**Comment by jhouse-solvd** [comment]
Jeremy suggests removing security groups to deny connection, leave for a few days, and then delete later. 

This might be a graceful approach... :)

**Comment by oseasmoran73** [comment]
Changed the security policy to `demian-test-github-action` to see if it will break & complain from other teams

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/search?q=statping&type=code

Did a bit more digging. Looks like there may be reference in lighthouse. Under commits, there is also commit that removed from our folder path.
