### ISSUE TITLE
Adjust Claim Labels for 686c/674 Submissions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34271]
## Background
Changing the label for dependents that get removed so that the OBI line of business can track removals a little better.

## Considerations
- `130SSRDPMC` 
PMC - Self Service - Removal of Dependent (Pension)
- `130SSRD`
Self Service - Removal of Dependent (Compensation)
- There might be more than one job to check
- Are there any removals in a 674? Prolly not...but let's be sure.
- Exceptions if RBPS rejects? they will 

## Tasks
- [x] List all use cases or workflows that a dependent that can be removed
- [x] Identify or check if we are removing a dependent. and if its comp or pen
- [x] If so, insert the appropriate claim label

## Acceptance Criteria
- [x] Dependents that set to be removed pass along the appropriate claim label
- [x] A PR has been requested for merging, if applicable

**Comment by jason-gcio** [comment]
This is due in March
