### ISSUE TITLE
Remove assignees from Collaboration Cycle templates in github

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34283]
## Issue Description
On the Collaboration Cycle Kickoff, Design Intent, Midpoint Review, Staging Review and Full Accessibility & 508 Office Audit ticket templates in github, we have assignees. It is very common for VFS folks to submit the ticket and not follow through with the instructions in the ticket asking they post on #vfs-platform-support notifying the Collaboration Cycle team of the ticket. We are assuming that since there is an assignee from the Collaboration Cycle team on the ticket, that they think that they can just submit the ticket and be done.

This ticket will remove the assignee from the gh template, hopefully forcing the VFS team member to post on #vfs-platform-support for their request to be received. 

---
## Tasks
- [x] Update the gh templates for:
   - [x] Collaboration Cycle Kickoff
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review
   - [x] Full Accessibility & 508 Office Audit
- [x] Peer review with another team member
- [x] Once published, update the url links on Platform website in the Touchpoint pages
- [x] Add Chase and Shira as FYI (similar to offboarding)

## Acceptance Criteria
- [x] Github Template links available on Platform Website and Confluence
- [x] Templates do not have assignees and Chase/Shira are set as FYI
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@chaseakirby I was thinking it might be nice to have our teams github group tagged in this ticket as an FYI. What are your thoughts? It would be like the Offboarding ticket where everyone in the group gets an email.

**Comment by chaseakirby** [comment]
@shiragoodman I tried adding the FYI label for only me and you. I think we should try it for these before extending that change to the other touchpoints since we were unsure how tagging works on an individual basis versus group.

**Comment by shiragoodman** [comment]
i saw! i just approved the PRs. go ahead and merge and we can run a test between you and I. You open a ticket and I'll let you know if I get an email

**Comment by chaseakirby** [comment]
Created ticket [35267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35267) for our test.

**Comment by shiragoodman** [comment]
i did NOT get the email. and I'm noticing that the CC doesn't quite look the same as it does in the offboarding tickets. for example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34781 this one is bold and clickable.

Maybe try updating to just our gh handles? No more "@department-of-veterans-affairs/"

**Comment by chaseakirby** [comment]
I believe you are right, since we are individual users I changed the test ticket and it now shows links/says that I am mentioned in the ticket.

**Comment by shiragoodman** [comment]
@chaseakirby yup that one worked! Thank you. You can update the other tickets without a PR since it's a pretty straight forward fix.
