### ISSUE TITLE
[PM, Design, FE, BE] On-site Notifications: Continue to work with VA Notify to define needs and delivery timeline for MVP

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34282]
## Background
The team needs to meet with our VA Notify partners to discuss our high-level requirements for on-site notifications MVP

## Tasks
- [x] Continue to meet with VA Notify to discuss requirements for MVP
- [x] Confirm the type of debt related notifications VA Notify currently has
- [x] Validate what data can be sent to AE My VA from VA Notify to trigger an On-site Notification
- [x] Validate how AE My VA can receive the data from VA Notify
- [x] Confirm timeline for any changes needed by VA Notify (if applicable)

## Acceptance Criteria
- [ ] High level [MVP requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) are documented in GH
- [ ] AE and VA Notify teams have a shared understanding of MVP requirements
- [ ] VA Notify has communicated a timeline for delivery of any changes (if applicable)

**Comment by hdjustice** [comment]
[**Meeting Notes for 1/10/22 discussion** ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/product/Mtg%20Notes%201-10-21%20-%20VA%20Notify-AE%20My%20VA%20-%20Bi-weekly%20Sync.md)with VA Notify.  The team has other priorities it is working on now, and may be able to pick up this initiative in Mid-Feb to March.  I will continue to work with them to monitor timelines and efforts.  In the meantime, Lihan will continue working on Backend development, completing what he can without VA Notify.
