### ISSUE TITLE
STEM Standalone Form: Turn off Auto-decision process

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34287]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The auto-decision process for form 22-10203 is incorrectly sending out auto-deny emails up to 50% of the time, according to statements from Kyle Pietrosanto of the Buffalo RPO. They want the process turned off until we can get it fixed. 

Based on the results of spike ticket ##33621 it is possible for our team to turn this off. Please see this ticket for additional information, if needed. 

Based on discussion with both Kyle and Cinda Quattrini (VACO) , they have approved the automated decision process being turned off temporarily until it can be fixed. For information on where to find this process in the code, see the 

NOTE: A separate ticket will be created to investigate the cause of this problem and fix it. This ticket is only to turn off/deactivate the process on a temporary basis. 

--- 
## Assumptions:
1. This work is completed behind a prod flag.
2. The form can be found here: [Staging Form](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)
---
## Tasks
- [ ] Deactivate the auto-decision process in the code  
- [ ] Route STEM applications to be processed manually.

---
## Acceptance Criteria
- [ ] The auto-decision process does not initiate.
- [ ] Auto-deny emails are not sent

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ERRonat0609** [comment]
@af-manish @AdamFreemer @mrblanco1 In going through some older issues, I found a reference to a feature flag that was used to hide this functionality and then flipped to turn it on in prod, BUT -- according to issue #[10812 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10812)- the flag was never removed from production. It was created as part of user story #13829, which is linked to the issue 10812. Please review this documentation before beginning this work. If the feature flag is still there, I should think we could just flip that flag and turn off the process.

**Comment by hallihocine** [comment]
Ticket has been validated in staging.
Validation Process:  different Rogers STEM scholarship applications were submitted using a different test user accounts, all of the applications were successfully submitted and a submission confirmation was sent to the provided emails.  No auto-deny emails were received. Some regression tests were done and all items work as expected.

**Comment by hallihocine** [comment]
- Test run in Test Rail
https://dsvavsp.testrail.io/index.php?/runs/view/2748&group_by=cases:section_id&group_order=asc&group_id=3251
- Test Steps/Script:
[STEM Standalone Form Turn off Auto-decision process.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7770120/STEM.Standalone.Form.Turn.off.Auto-decision.process.xlsx)
