### ISSUE TITLE
Content update on disabilities that appear within 1 year after discharge page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34297]
## Issue Description
Stakeholder Tanekwa Bournes shared that we need to fix a CFR reference we have 4 times on the [disabilities that appear within 1 year after discharge](https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/) page. 

Wherever we have 3.09(a) we need to change it to: 3.309(a).

It's shown twice in the featured content box and twice under the question "How do I get these benefits?"

While doing this work we should check for sighted language. And it looks like the header heirarchy is not correct. The H3s on the page should be H2s. 

## Tasks
- [x] Update CFR number throughout page (Selina)
- [x] Updated sighted language and other accessibility elements (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Correct number is live on the site

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Disabilities that appear within 1 year after discharge: http://preview-prod.vfs.va.gov/preview?nodeId=890

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
