### ISSUE TITLE
[UNPLANNED] Payment History Latency Issues

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34300]
## Story
As a Veteran, I want to be able to quickly and easily view an accurate history of my payment records between me and the VA so that I can make financial decisions and know that the compensation I receive is what it should be.

## Issue Description
The eBenefits Team was notified that payment history was not loading quickly or at all in some cases on VA.gov.  This presented similarly with other features on VA.gov and had a common element to them; using a BGS service.

## Considerations
- Page loads fine but data within the dynamic content spins and sometimes fails to load.

## Tasks
- [x] Identify each e2e step in the process 
- [x] Isolate potential timeout areas and share with the larger task force
- [x] Determine a plan for resolution
- [x] Collaborate with platform support in determining a root cause issue
- [x] Contribute to a solution as applicable
- [ ] TBD, edit these as needed

## Acceptance Criteria
- [x] A root cause, or hypothesis, has been identified: **logging pipeline was getting clogged**
- [x] A path forward has been determined: **testing error levels (Jan '22)**
- [ ] A plan for resolution has been agreed upon, tested or vetted, if applicable
- [ ] A solution has been implemented, if applicable
- [ ] A PR has been requested for merging, if applicable

**Comment by jason-gcio** [comment]
The outcomes from this ticket will most likely create other tickets
