### ISSUE TITLE
[UNPLANNED] Latency Issues for Direct Deposit for EDU (CH33)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34317]
## Story
As a Veteran, I want to be able to quickly and easily adjust my direct deposit information for education payments so that I can ensure that funds are being sent to the appropriate place.

## Issue Description
The Profile Team was notified that the profile page was not loading quickly or at all in some cases on VA.gov.  This presented similarly with other features on VA.gov and had a common element to them; using a BGS service.

## Considerations
- `service.claims.send(:request, :find_ch33_dd_eft, fileNumber: @user.ssn)`
- `service.ddeft.find_bank_name_by_routng_trnsit_nbr(routing_number)`
- `ch33_bank_accounts`
- workaround was to modify the code so that loading the VA.gov profile did not depend on retrieving Ch 33 data

## Tasks
- [ ] Identify each e2e step in the process 
- [ ] Isolate potential timeout areas and share with the larger task force
- [ ] Determine a plan for resolution
- [ ] Collaborate with platform support in determining a root cause issue
- [ ] Contribute to a solution as applicable
- [ ] TBD, edit these as needed

## Acceptance Criteria
- [ ] A root cause has been identified
- [ ] A path forward has been determined
- [ ] A plan for resolution has been agreed upon, tested or vetted
- [ ] A solution has been implemented, if applicable
- [ ] A PR has been requested for merging, if applicable

**Comment by Samara-Strauss** [comment]
Latest status - it sounds like this may have been an issue that resulted from how we process logging. [Highlights from Slack](https://dsva.slack.com/archives/C02Q9FL124F/p1639766106299600):

From Dror:

> - We are quite convinced, though not sure it's not BGS specific.
> - No matter what, we need to improve our logging, which is the main action item.
> - We think it might be a logging issue, but won't know until we run into the issue again. When it does, we have a logging mitigation (change INFO to ERROR, only log errors), which should tell us if our theory is right.

From Joe Niquette:

> I think we can actually determine this was a logging issue by lining up logs
> the only thing this would leave us with is why these particular services were impacted and not others...but based on Bills graph here, it points to lots of things taking way too long..so maybe this is all we need?

A few takeaways:

- It sounds like there may have been latency issues with other non-BGS endpoints, but I don't know that it ever got as bad as things entirely not loading. I'm unsure, but I didn't hear other reports of that in Slack. If this is the case, we could be more sure that BGS is not the issue.
- The reason this issue seemingly resolved overnight without any changes from us is because of 1) a reduction in traffic and 2) the logs catching up (perhaps due to the reduction in traffic). Since the logs caught up, the backlog was no longer stalling things.
- There's not much we can do besides wait to see if this happens again. At that point, we can see if the changes the ops team has made re: the logs was the culprit, or if there is something else contributing to this issue. In theory, if the logs were the problem, this *shouldn't* happen again now that updates have been made to logging.

**Comment by Samara-Strauss** [comment]
It appears we are having latency issues again, though as of now, the feature is not entirely down.

Bill Ryan put together [this Grafana chart](http://grafana.vfs.va.gov/d/000000017/vets-api?editPanel=10&orgId=1&from=now-1h&to=now) which shows us max/avg load times for the endpoint.

Joe says that the semantic logging is backing up again, so this is likely a logging issue. Conversation/work is continuing in Slack.

**Comment by MarciMcGuireGCIO** [comment]
Trevor Bowsaw discovered on 12/20 that there is a second call to the BGS service that occurs even if the first call does not return bank account information.  [Full Slack thread](https://dsva.slack.com/archives/C02Q9FL124F/p1639786132335600)

>Yeah, I just  #confirmed now the reason there's a stack trace with most of the ch33 calls:
When we make a call to get_ch33_dd_eft_info from the BGS service, we first make a call to generally get user's bank account information, find_ch33_dd_eft. We then make a second call for find_bank_name_by_routng_trnsit_nbr. The problem, we assume that the routing number is nil on the original call if the user has no bank account info. In fact, the routing number appears to be set to 0 with no bank info set up, so right now we consider that valid and pass it along to the second call

He made the following change and confirmed on Staging that no stack trace error occurs.

>This PR adds a check for ch33 bank accounts implementation so that when the routing number for a find_ch33_dd_eft call is 0 or nil, we don't make a follow up call to get the bank name from routing number.

This change has been merged and should go out with this afternoon's deploy to Prod.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss - This ticket will need to move to Sprint 64 since code freeze is starting and won't end until after this sprint is over.  We still don't 100% know the root cause.

**Comment by Samara-Strauss** [comment]
@MarciMcGuireGCIO totally fine. I think I actually expected it to be for sprint 64 since Lihan isn't back until next week.

**Comment by RudyOnRails** [comment]
Just came across this ticket from the Latency epic. Can this one be closed since we are not seeing this anymore?

**Comment by MarciMcGuireGCIO** [comment]
@RudyOnRails I believe so, since the changes seem to have worked.  @Samara-Strauss - what do you think?

**Comment by Samara-Strauss** [comment]
Yep! I think this is good to close. Fixes have been implemented in other tickets.
