### ISSUE TITLE
Adjusts Error Handling Notifications

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34319]
## Background
As a VFS Team, we need to be notified faster and more directly of issues as they occur so that we can have a faster response and awareness to issues.

## Considerations
- There are several tools we should able able to use and get notifications in either our Slack channel or in a dedicated channel we can easily get to.

## Tasks
- [ ] Identify which tools should be used to meet our objective
- [ ] Implement those tools so that the affected team is notified as soon as possible
- [ ] Test this notification process with the team

## Acceptance Criteria
- [ ] A mechanism for better awareness has been produced and tested

**Comment by RudyOnRails** [comment]
Great idea @jason-gcio. According to Bill Riley it is much easier to use DataDog for alerts than Grafana, and according to Platform, DD is the future, and Prometheus will be deprecated at some point.

We should all start adding our ideas to this ticket as far as:
- What the monitor should track/monitor (e.g. view-payments average request duration over a 5min period)
- What the warning threshold should be (e.g. greater than 5sec)
- What the alert threshold should be (e.g. greater than 10sec)
- What the message should look like (e.g. "View-Payments Request Duration Monitor")
- Where the message should be sent (i.e. specific emails, or slack channels)

CC: @kathleencrawford

**Comment by RudyOnRails** [comment]
@jason-gcio can this one be closed now that we made the dashboard? Or is this more for creating a one-and-done Datadog monitor that tracks all our teams endpoints?

**Comment by RudyOnRails** [comment]
@jason-gcio came across this as I was comparing ebenefits number of epics to 1010's number of epics. 

Closing since this was completed in the DD dashboard.
