### ISSUE TITLE
Front end implementation of CAP hours

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34316]
## Issue description
Currently, hours of operations specified in Drupal for Community access points are not being reflected on the front end. 

Vet Center editors may choose to display specified hours or direct Veterans to call the main Vet Center - **for each Community access point** associated with the Vet Center. 

Vet Centers may have zero, one or multiple Community access points at any given time (they can be added or removed)

Cap hours may be expressed as from/to times with or without comments by the day of the week. 

<details>
<summary> Screenshots from Drupal </summary>

![image](https://user-images.githubusercontent.com/55411834/146589687-39f82632-c317-4d6a-8216-23e5c7f1a10e.png)

---

![image](https://user-images.githubusercontent.com/55411834/146589654-42902290-ef86-474c-a630-5a6a00fe335b.png)

---

![image](https://user-images.githubusercontent.com/55411834/146589900-13028841-2bf6-4c94-bfe9-42e76135e5b4.png)

</details>

### Grooming notes

Will create separate issues to 

- add hours for outstations and main Vet Center (#34423)
- add map slice (#34427)

**Need to get field names** 

## Tasks
- Add CAP hours of operation to front end query for Vet Center Locations page
- If CAP hours are specified in Drupal, display hours below the phone number as specified in [UX pin](https://preview.uxpin.com/46fe3a3a3a963877cadf501d6e1886c2a2f5cc48#/pages/144953996/documentation/no-panels?mode=i)
- If "Veterans should call main Vet Center for hours" option is selected in Drupal, display "Please call the main Vet Center for hours"  below the hours heading

## Acceptance criteria
- [ ]  When CAP hours are specified in Drupal, hours are displayed below the phone number as specified - for example, in the Reedsport example 

> **Hours**
> Mon: Closed
> Tue: Closed
> Wed: Closed
> Thu: 10:00 a.m. - 6:00 p.m. Weekly
> Fri: Closed
> Sat: Closed
> Sun: Closed

- [ ] If "Veterans should call main Vet Center for hours" option is selected in Drupal, "Please call the main Vet Center for hours" appears below the hours heading
- [ ] In the event that neither is checked, "Please call the main Vet Center for hours" appears below the hours heading
- [ ] If **neither** to/from hours **nor** comment field for a given day is not populated, assume "Closed".

**Comment by mmiddaugh** [comment]
Subsequent issue for fine-tuning: #35744 35744
