### ISSUE TITLE
[FE] Combine API mocks and calls into one API mock and call

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34323]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

We want to take both the `api` directories and combine in to a root level `api`. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] refactor API
- [ ] OTHER THINGS TO FILL IN
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Merged to master
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
