### ISSUE TITLE
[Loki] Investigate ways to improve performance 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#34320]
## Description
Specific queries or a high volume of I/O can cause issues for Loki. This results in inconsistent behavior or degraded performance. There are ways to improve Loki's configuration and infrastructure to provide consistent performance. 

## Background/context 

- Large in this context means queries with lots of data, ie a longer time window or high number of events
- Errors are seen for Memcached with large queries or during times of high volume
- Recent Slack in #vsp-operations-internal [thread](https://dsva.slack.com/archives/CTYQL39FE/p1639765705169000?thread_ts=1639758429.146100&cid=CTYQL39FE)
- Loki launch thread when [Demian first spotted that Memcached was running out of memory](https://dsva.slack.com/archives/CJYRZK2HH/p1633115811249600?thread_ts=1632937965.179100&cid=CJYRZK2HH)
- Later in the same thread when [Demian mentioned the correlation between query cache and poor performance](https://dsva.slack.com/archives/CJYRZK2HH/p1633362577302400?thread_ts=1632937965.179100&cid=CJYRZK2HH) for incoming logs

## Technical notes
Technical information about the Loki distributor: https://grafana.com/docs/loki/latest/fundamentals/architecture/distributor/

---
## Tasks
- [ ] Identify spikes or outages in Memcached monitors & logs
- [ ] Attempt to reproduce

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mchelen-gov** [comment]
slack thread: https://dsva.slack.com/archives/CTYQL39FE/p1639758429146100

**Comment by mchelen-gov** [comment]
memcache prod memory usage: https://app.datadoghq.com/monitors/58408512?live=1w&q=cluster_name%3Adsva-vagov-prod-cluster

**Comment by mchelen-gov** [comment]
example test query: http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-60d%22,%22now-30d%22,%22Loki%20(Prod)%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%20%7C%3D%20%5C%22payment_history%5C%22%20%7C%20regexp%20%5C%22(%3FP%3Ctime%3E%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd)%20(%3FP%3Cprocess_name%3E%5C%5C%5C%5Cw%2B.%5C%5C%5C%5Cd)%20%5C%5C%5C%5Cs%2B%20(%5C%5C%5C%5C%7C)%20(%3FP%3Cjson%3E.%2B)%5C%22%20%7C%20line_format%20%5C%22%7B%7B.json%7D%7D%5C%22%20%7C%20json%20%7C%20duration_ms%20%3E%2060_000%22%7D%5D

**Comment by mleclerc00** [comment]
I am still seeing some `failed to put to memchached i/o` errors with the following query so it seems to be unrelated to memory usage.  Will be investigating this further.

http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22loki-distributed%5C%22%7D%20%7C%3D%20%5C%22fail%5C%22%22%7D%5D

**Comment by jhouse-solvd** [comment]
interesting thread on tuning loki performance:

https://community.grafana.com/t/how-to-improve-loki-performance/42800/6

**Comment by jhouse-solvd** [comment]
To understand how different Loki components are involved in processing a query, it could be useful to use logcli directly w/ the --stats option. This would take Grafana out of the equation and produce interesting data.

https://grafana.com/docs/loki/latest/getting-started/logcli/#logcli-command-reference

For example:
Ingester.TotalReached 12
Ingester.TotalChunksMatched 72
Ingester.TotalBatches 0
Ingester.TotalLinesSent 0
Ingester.HeadChunkBytes 923 kB
Ingester.HeadChunkLines 755
Ingester.DecompressedBytes 85 MB
Ingester.DecompressedLines 63807
Ingester.CompressedBytes 14 MB
Ingester.TotalDuplicates 0
Store.TotalChunksRef 8144
Store.TotalChunksDownloaded 8144
Store.ChunksDownloadTime 8m38.330467263s
Store.HeadChunkBytes 0 B
Store.HeadChunkLines 0
Store.DecompressedBytes 59 GB
Store.DecompressedLines 44850257
Store.CompressedBytes 9.6 GB
Store.TotalDuplicates 0
Summary.BytesProcessedPerSecond 375 MB
Summary.LinesProcessedPerSecond 285792
Summary.TotalBytesProcessed 59 GB
Summary.TotalLinesProcessed 44914819
Summary.ExecTime 2m37.158656521s

real 2m37.267s
user 0m0.119s
sys 0m0.016s

**Comment by mchelen-gov** [comment]
updated query for "failed to put to memcached": http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22loki-distributed%5C%22%7D%20%7C%3D%20%5C%22failed%20to%20put%20to%20memcached%5C%22%22%7D%5D

**Comment by mleclerc00** [comment]
Turning my attention away from loki and trying to figure out the actual root cause for semantic logger being backed up I came across the following information

Looking at the semantic logger logs, it states its falling behind by x seconds and has a queue size of x

ex.
`Async: Appender thread has fallen behind by 5858.35666882 seconds with 109013 messages queued up. Consider 
reducing the log level or changing the appenders`

looking at the semantic logger in vets-api it is being sent to stdout
https://github.com/department-of-veterans-affairs/vets-api/blob/2726fd8494d9f56d9910ca2fbcbf598e8bcd6589/config/environments/production.rb#L69

from the documentation in semantic logger this states
https://www.rubydoc.info/gems/semantic_logger/SemanticLogger.queue_size
`When this number grows it is because the logging appender thread is not able to write to the appenders fast enough. Either reduce the amount of logging, increase the log level, reduce the number of appenders, or look into speeding up the appenders themselves`

most notably since stdout is our only appender or look into speeding up the appenders themselves
but how does one speed up stdout?  This kind of indicates some sort of limitation on disk i/o and or stdout buffer maybe?

it makes me want to think overall i/o or performance since these puma errors show in the same time period the most notable thing being block in `handle_request` `with_force_shutdown` `block in spawn_thread`

http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-6M%22,%22now%22,%22Loki%20(Prod)%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%20%7C%3D%20%5C%22semantic%5C%22%22%7D%5D

More poking around shows we are using the docker plugin to send all docker logs to loki.
https://grafana.com/docs/loki/latest/clients/docker-driver/

install
https://github.com/department-of-veterans-affairs/devops/blob/6f31cd30f1d7091bcd12[…]48559023745cb5/ansible/build/roles/common/docker/tasks/main.yml

and docker options to point to said driver
https://github.com/department-of-veterans-affairs/devops/blob/ac949bb2433dafd18bfd[…]f70d0a2/ansible/deployment/config/vets-api-server-vagov-dev.yml

the following statement about the loki driver seems ominous
`The driver keeps all logs in memory and will drop log entries if Loki is not reachable and if the quantity of max_retries has been exceeded.`

which could theoretically lead to resource starvation but its hard to directly pin that as the root cause without seeing it in action.

Also from looking at loki logs quite a bit today, I’m not entirely sure that loki has actually gone unreachable for any extended period of time to correspond to that.  I do think that there are some issues when it comes to running queries that span long periods of time.  But in the same breath the query that was failing for us over 30 days was working today and I’m not sure I can pinpoint the issue there quite yet.

in order to view the logs for the loki logging driver plugin  we can do something like this 
https://forums.docker.com/t/how-to-find-logs-of-a-plugin-in-new-docker-plugin-management-system/32635/4
which could lead us to any errors between the promtail docker logging driver and loki to rule that out

That being said I don’t see any output from the loki plugin (both stderr/stdout) so it might be difficult to figure out what is going on without the issue currently present.

Wondering if we can enable info level logging on a single vets-api server in prod to see if we can replicate semantic logger backing to give us the ability to troubleshoot in realtime.
Or at least try to simulate it in a lower environment in some way shape or form.

**Comment by mleclerc00** [comment]
Loki memcached instances have been migrated to aws elasticache.  Have been keeping an eye on it and haven't seen any memcached related errors since.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/34424

**Comment by jhouse-solvd** [comment]
One of the things that we were seeing is that the semantic logger was getting backed up with log messages on a vets-API server container because the Loki driver could not send logs quickly enough to the distributor

`loki-prod.vfs.va.gov/api/v1/push - which resides on the Loki distributor. 
`
To combat this, we've increased the number of replicas and removed resource limits for the distributor, ingester, and queried. 

We are not monitoring the situation to see if that helps to stabilize Loki.

**Comment by jhouse-solvd** [comment]
Some initial work has been done. Moving this to review. 

The Infrastructure can make decisions around what additional investigation may be needed at this time.

**Comment by jbritt1** [comment]
A lot of work was done to get Loki stable and usable as one can see in the linked pull requests / additional bodies of work. Our current intent is to look into leveraging Datadog for logs instead of Loki altogether. Further optimizations and enhancements are highly unlikely to be prioritized or even completed for Loki for the foreseeable future, closing.
