### ISSUE TITLE
COVID updates for CDC recommending Pfizer/Moderna boosters

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34349]
## Issue Description
We need to make updates to our COVID vaccine pages with the new information that the CDC recommends the Pfizer and Moderna boosters.

## Tasks
- [x] Update pages (Danielle)
- [x] Copyedit (Randi)
- [x] Send out for approval (Danielle)
- [x] Publish (Randi)
- [x] Send to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send to volunteer translators (Randi)

## Acceptance Criteria
- [x] New content is live on English pages
- [x] New content is live on translated pages

**Comment by RLHecht** [comment]
These changes were sent to translators on 12/20.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back.
[https://app.zenhub.com/files/133843125/ffb090fc-8451-4ae5-9321-3e3fb89d81e6/download](https://app.zenhub.com/files/133843125/ffb090fc-8451-4ae5-9321-3e3fb89d81e6/download)

[https://app.zenhub.com/files/133843125/415066a8-184a-4fe1-a931-131a5741cae0/download](https://app.zenhub.com/files/133843125/415066a8-184a-4fe1-a931-131a5741cae0/download)

**Comment by lunascoop** [comment]
@RLHecht most of the updates have been made. See my notes below.

- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394 Had to piece together this sentence under "Which vaccine to get for your booster:" Teens ages 16 and 17 can only get the Pfizer-BioNTech vaccine for their booster dose.

I assume we're awaiting translations for Omicron variant content. Didn't update those yet. And the "Not all VA health facilities may offer vaccines to teens under age 18" sentence.

**Comment by RLHecht** [comment]
Thanks @lunascoop I published these minus the part of the featured content box that still needs the omicron info. I emailed them again to ask about the status.

**Comment by RLHecht** [comment]
These are now live and I sent the text to Mateo for his team to review. I'll reopen if he has changes.
