### ISSUE TITLE
526: Fix undefined error seen in Sentry

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34350]
## Description

A Sentry error `Cannot read properties of undefined (reading 'view:livesOnMilitaryBase')` occurred after the page failed to load the save-in-progress data. Add checks to prevent this error

- http://sentry.vfs.va.gov/organizations/vsp/issues/59999
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34110

## Tasks

- [ ] Add checks to prevent `view:livesOnMilitaryBase` error
- [ ] Add unit tests

## Definition of done

- [ ] All tasks done
- [ ] All tests passing
