### ISSUE TITLE
[Design] Discovery: Good/Bad Rating on Benefit Hubs 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34366]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I want to provide feedback to the VA concerning my experiences while on VA.gov. 

## Documentation
- Current Design on VA.gov
![Screen Shot 2021-12-20 at 8 50 54 AM](https://user-images.githubusercontent.com/70410912/146795062-e0a06cb6-1a52-41f3-9b06-51eddf1738e7.png)

## Description
- The good/bad feedback component was created by the PW team and implemented on the Resources and Support library and has shown signs of success for Veterans to provide feedback.  The search and discovery team is working some iterative improvements to this component in addition to adding it to the design system.  The PW would like do some discovery to see how this component could be implemented in the benefit hubs.  

### Considerations
- Must work well on mobile and desktop platforms
- Must address accessibility concerns and support for adaptive tech
- Should consider iterative feature development
- Initial design/determine what S&D iterative updates are and how they apply
- Must not change current design as it's being added to the design council 

### Tasks
- [ ] Baseline existing features and flows
- [ ] Identify use cases for rating in benefit hubs
- [ ] Illustrate use cases via feature flow diagrams
- [ ] Wireframe UI suggestions illustrating features in context

### Acceptance Criteria
- [ ] Brief discovery doc outlining baseline feature flow and functionality created
- [ ] Diagram uses cases and high-level feature flows 
- [ ] Wireframe UI suggestions illustrating features (including date/time filtering) in context created

**Comment by callen2563** [comment]
@mgleo Hi Megan, I know you are currently working on page rating for the Recourses and Support page. I have a couple questions: Have you done any discovery research for page rating on Recourses and Support yet? Is there any discovery work you can share with us? Thanks!

**Comment by callen2563** [comment]
After chatting with Megan on the Search team I think it would make sense to wait until they have finished conducting discovery research as well as gaining approval for this rating component from the design system council about adding it to the experimental design system. Once we have approval to use this rating component this would be a dev task to simply add that rating component to the benefit pages to the specified bottom area of the page based on the component specs. @brianalloyd let me know your thoughts.

**Comment by mgleo** [comment]
No plans as far as I am aware for the experimental design system. 
Here is the preliminary user flow for the submit feedback tool: https://app.zenhub.com/workspaces/vsa---search--discovery-61538bc5cf1e54001a350379/issues/department-of-veterans-affairs/va.gov-team/34152#issuecomment-1002288391
@callen2563 @brianalloyd

**Comment by FranECross** [comment]
Closing old, obsolete ticket.
