### ISSUE TITLE
Public Websites: Sprint 64 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34368]
## **Sprint 64 Priorities: Dec 29- Jan 11 , 2022** 

VA.gov Mobile Header launch strategy close-out | Outreach & Events, Post Research actions, FE build, Collab Cycle for Launch Readiness |  Tech-debt & In-take Requests | Redirect Requests vetted by IA. 
 
1.  Outreach & Events -->  FE Build actions, Internal UAT, VSP Staging Review, Launch Readiness.  
2. HRT --> Conduct KPI Planning Session, Finalize Research and Conversation guide.
3. Quarterly Planning --> Determine next quarter initiatives. 
4. FE Process | Best Practices Documentation
4. 'Tech-Debt' items as prioritized from backlog grooming --> Mission to clear out tech-debt and mitigate risk

### Capacity Planning: PTO/Holiday's
Brian: 12/30-31
Kelson: 12/31
Trent: 12/31
Cassandra: 12/31, 1/10-11
Mimi: 12/30-31
Cindy: 12/30-31
Dave: 12/30-31

### **Code Freeze Schedule 2021: Important Dates for Reference** 
- 12/23 - 1/2/2022 - Winter holiday freeze (note: seven business days, weekends included for clarity)
- ADHOC/GCIO HOliday's 12/24, 12/31

Discussion Points: How do we handle Intake / Redirects that come in during Code Freeze?

### Outreach & Events [Finalize Design/Research/FE Build] 
EPIC: Outreach & Events Hub - 2021 Enhancements #28918 / PW Outreach & Events Enhancements MVP x Collab Cycle Plan #33221
- [x] [FE] Build out event page app #32601
- [ ] [Research] Post Research Tasks: Outreach & Events MVP Research #33373
- [ ] [Design | Content] Content Review for Outreach & Events MVP from Public Websites Team #34253
- [ ] [PM] Finalize Release Plan / Artifacts for staging review
- [ ] [QA] [Outreach & Events MVP/Filtering, Recurring Events Enhancement] VSA-QA Test Plan #33513
- [x] [IA] Recurring Events URL structure for Outreach & Events from Public Websites Team #33953
- [x] [FE] Create new URL structure for event detail page #34556
- [ ] [PM] Staging Review [Public Websites - Outreach & Events MVP] #34622
- [ ] [PM/FE]Analytics Implementation or QA Support for [Public Websites - Outreach & Events MVP] #34675
- [ ] [PM] Coordinate with CMS training and determine training update / timing for roll out with Tim/Editors. (Thread started, requires followup). Dep strategy for legacy elements (CMS/PW Team). 

Discussion Points: Next steps for Design --> **Timezone Discussion / Decision Point.** 
- VSP Collab Cycle next steps --> Staging review, discuss timing for ticketing and review. 
- Release to all pages (Outreach and VAMC) need to discuss with Stan, Michelle and CMS change management component (follow up). 
- Utilize the dates / times supplied by CMS. 

### HRT 
- [ ] [Research] Draft Research Plan - HRT Static Content Landing Page #33756
- [ ] [Research] Draft Conversation Plan - HRT Static Content Landing Page #34579
- [ ] Collaboration Meeting to review research KPIs | Success Factors. 

Discussion Points: Create a split, start a draft that identifies the gaps. Circulate internally (Dave & Danielle) for review.  Setup a meeting for Jan 3rd to review research goals. Sprint 64 --> Finalize research plan, tentative plan would be recruit during S65, Research conducted in S66 as a baseline for research. 

### Intake Request - Techical Debt
- [x] Redirect Request - GI Bill Comparison Tool URL Change #34480
- [x] Vanity URL Request - Hazardous exposure PSA - JAN 3, 2022 #32655
- [ ] [FE] Minor inconsistency in the VA.gov site header #34364
- [x] [FE] Remove <class="vads-u-font-size--h3"> Q&A Content Blocks #34362
- [ ] [Discovery] Migrate VA.gov megamenu items to Drupal #32681
- [ ] [FE] Create | Modify e2e tests to ensure proxy rewrite header/footer code is working as expected #33078
- [ ] [BUG] Google Analytics opt-out component #32587
- [ ] 508-defect-1 ❗ Launchblocker [COGNITION, SCREEN READER]: ID in ARIA and labels must be unique #34252
- [ ] Button URL change request from Auth-Profile #34290 (Pending - GreenLight)
- [ ] Bad URL for default og:image meta tag #33552
- [ ] [Code Pairing] Good | Bad Rating Component #34626
- [ ] [FE] Mobile Header V2 Clean Up and Review (Post 100% Launch) #34646
- [x] Redirect Request for Vet Centers live as of 12/30: FL detail pages, legacy directory location and key staff pages #34661

<details><summary>Collab Cycle Tracking Template</summary>

### 
# Collab Cycle Tasks
After copying this template into your new Sprint Priority issue, keep the Collab Cycle tasks needed for this sprint and delete the rest.
- [VSP Collaboration Cycle Image](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [VSP Collaboration Cycle Requirements/Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)
- [Change Release Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/decision-tools/DRAFT_Change_Checklist.md)

## Define
- [ ] **[Define] Kickoff-Intent** - #(ticket)
- [ ] **[Define] Design intent** - #(ticket)

## Discover

- [ ] **[Discover] Usability Testing Prep** - #(ticket)
- [ ] **[Discover] Research Plan Review** - #(ticket)
- [ ]  **[Discover] IA Request** - #(ticket)
### [Submit Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### [Privacy and security review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review)
- [ ] Submit ticket for review: Use Privacy and Security Review template in va.gov-team-sensitive repository 
- [ ] Provide artifacts at least 48 hours prior to the review
- [ ] Schedule/hold Privacy and Security Review
- [ ] Complete any tickets that came out of Privacy/Security review (if any)

### [Submit Analytics **QA** request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request)
- [ ] [Analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban%2C+bsmartin-ep%2C+jonwehausen%2C+bmcgrady-ep&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) has been submitted and finalized

### Release Plan
- [ ] Create UAT plan
- [UAT Template](www.google.com)*
- [UAT Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-research-plan-UAT.md)
- [ ] Complete Release Plan 
- [Release Plan Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)

#### QA
- QA Staging review scheduling: Have artifacts in and tag Tze 2 weeks in advance from the Staging Review. This makes it possible for Tze to get to it w/o being rushed. When you schedule the Staging review, also tag Tze in Slack.
- [ ] Create list of staging users
- [ ] Create list of use cases [see [Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)] and submit to Tze so he can create test cases/regression tests
- [ ] Create “Coverage for references report” OR a add a link to the Epic for the product you are releasing  

#### Accessibility
- [ ] Complete the [required accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Complete QA/Accessibility tickets that came out of Staging review prep (if any)

### Conduct Internal QA Session
It is beneficial to conduct an internal QA session prior to actual QA. This consists of the team allocating 1 hour to meet look for bugs and or issues with the product. This is beneficial because the engineers and designers have in-depth knowledge of potential problem areas that QA might not have the time/resources to look into.
- [ ] Internal QA has been conducted

#### List of issues coming out of internal QA session:
- [ ] Issue name #00000
- [ ] All issues that came from internal QA have been completed

### [Request Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- [ ] Provide all required artifacts in the request
- [ ] Schedule/hold staging review
- [ ] Complete all IA feedback tickets
- [ ] Complete all Accessibility feedback tickets
- [ ] Complete all QA feedback tickets
- [ ] Complete all Content feedback tickets
- [ ] Complete all Design feedback tickets

### [Contact Center review]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)
- [ ] Create Product guide
      - [Product Guide example]()
- [ ] Create Product video
- [ ] Submit request for Contact Center Review
- [ ] Complete Contact Center Review

### Analytics follow up on Staging
- [ ] Analytics are complete
- [ ] Frontend has implemented analytics data layer changes
- [ ] Dashboards have been created and link directly to your OKR/KPI's
- [ ] Review dashboard(s) with Analytics team to ensure understanding of all metrics/calculations
- [ ] Dashboards are finalized/work correctly

### Preparing/Updating all necessary supporting documentation for your product
- [ ] API calls and dependent systems [Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account#api-calls-and-dependent-systems)
- [ ] Update product outline with updated release information and links to analytics dashboards [Product Outline Example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)

#### Ex:(re-directs, changes to content, changes that affect other teams) 
- [ ] Create issues in Github for changes that will take place, add dates, and tag relevant people/teams (re-directs, content changes, UI changes, etc)
- [ ] Update dates/parties accordingly as launch approaches and dates are finalized

### UAT
- [ ] Conduct UAT Go/No-Go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/uat-go-nogo.md)
- [ ] UAT has been conducted
- [ ] Issues have been logged/added to the Release Plan. [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)
- [ ] Launch-Critical UAT issues have been resolved

### Phased Launch (depends on phases in your launch)*
- [ ] Conduct Launch Go/No-Go meeting
-  [Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md)
- Invite your entire team, analytics, platform team members, etc
- [ ] Resolve any issues (if applicable)
- [ ] Continue with phased launch, resolving issues if they arise, monitoring analytics daily

#### Go-live to 100% of traffic
- [ ] Conduct Go-live go/no go meeting 
- [Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Launch%20go%20no-go.md)
- [ ] Resolve issues (if applicable)
- [ ] Launch to 100% of users

## Monitoring
- [ ] Monitor analytics daily to ensure there are no abnormalities/errors
- [ ] Resolve any issues (if applicable)

## Post Launch
- [ ] Fill in post-launch metrics in the Release Plan
- [ ] Remove old code (if applicable)

### [Full Accessibility and 508 Office Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#full-accessibility-and-508-office-audit)
- [ ] Request [Full 508/Accessibility Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)
- [ ] Complete required scans/tests
- [ ] Make required changes (if any)

### [Post Launch Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#post-launch-check-in)
- [ ] Update Release Plan with "post-launch questions" completed
- [ ] Schedule/Hold check-in
- [ ] Measure results against OKRs
- [ ] Prepare next steps and potential iterations if applicable

# Feedback from other teams

**Platform feedback:**
- The biggest blocker to a successful launch would be not implementing platform feedback earlier in the process. 
- It would be ideal to implement the feedback prior to the staging review. 
- More frequent communication of changes/issues via the slack channel would be beneficial.

**Accessibility feedback:**
- Include accessibility in design syncs, design-intent review, and anytime large changes are made.
- More frequent communication with Accessibility (ex: Biweekly accessibility meetings)
- For individual meeting/mini reviews use this [GH template](Enter link to template)
- Have an "Engineering intent review" and include accessibility (in addition to design intent review).

**PM Feedback:**
- Update Collaboration Tracker
- Add time estimates maybe
- how to roll this out
- put in epic format?

</details>

<details><summary>Kanban Board Template</summary>

### 
# Kanban Board
_Please select a ticket and include [WIP - [NAME]] next to the ticket that is being worked._  Pick up tickets by priority on the `To Do ` section to begin and move ticket through kanban workflow until `Done`. Please include resolution steps on tickets along with instructions if for some reason you are unable to complete the ticket during this sprint.  
Please tag <PM> on tickets when moved to **Done** section for validation and closeout.  Please connect if you have any questions or concerns in the interim.  Welcome to **VFS team** (for this sprint) we're excited to have the help.  

<details> 

<summary> TO DO </summary>

</details>

<details> 

<summary> ON-GOING </summary>

- [ ] [FE] <Discription> #174XX (WIP - Name)

</details>

<details> 

<summary> DONE </summary>

- [x] [FE]<Discription> #174XX (Validate - Name)
