### ISSUE TITLE
[FE] Remove <class="vads-u-font-size--h3"> Q&A Content Blocks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34362]
## User Story
- As a content editor on VA.gov I need headings to render properly in order to have a clearly communicated content for Veterans, caregivers and others visiting VA.gov. 

## Related Documentation
- [Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1639769532151300)

## Description
- The ticket you worked on for making featured content Q&As H2s has them still looking like H3s even though they are coded correctly. Since this didn't change just Q&As in the featured content blocks but also in the main content area of the page, could we change this to have them look like H2s? Noticing on some pages that are made up of both Q&A content blocks and rich text fields the header sizes look like they go back and forth when they should all appear as H2s.

## Tasks
- [ ] Remove <class="vads-u-font-size--h3"> Q&A Content Blocks
- [ ] Monitor environment to ensure stability
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] content Q&As H2s are rendering as intended.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/content-build/pull/869

**Comment by kelsonic** [comment]
PR merged

**Comment by brianalloyd** [comment]
Validated and closing.
