### ISSUE TITLE
[FE] Minor inconsistency in the VA.gov site header

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34364]
## User Story
- As a Veteran, Caregiver and user of VA.gov, I need an optimized experience so I can complete tier 1 benefit actions while visiting VA.gov. 

## Related Documentation
- [Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639692573182100)

## Description
- Padding around the My VA link when the page is active (user is on the page) and the user hovers over the link. No L / R padding is displayed, inconsistent with the non-active behavior..

- Hover: page not active
<img width="802" alt="Screen Shot 2021-12-20 at 8 41 38 AM" src="https://user-images.githubusercontent.com/70410912/146793826-1f1621a5-344d-4b89-a57a-2f614188a835.png">

- Hover: page active
<img width="809" alt="Screen Shot 2021-12-20 at 8 41 55 AM" src="https://user-images.githubusercontent.com/70410912/146793858-cc8c81f3-f802-4c76-8c8d-cacec6f6d8da.png">

## Tasks
- [ ] Fix inconsistency in the VA.gov site header
- [ ] Monitor environment to ensure stability
- [ ] Close Ticket when completed 

## Acceptance Criteria
- [ ] VA.gov header is rendering and acting as intended.

**Comment by brianalloyd** [comment]
@tmac9494 can you scrub into this ticket?

**Comment by brianalloyd** [comment]
Completed, issue resolved, closing ticket in support.
