### ISSUE TITLE
[BE] Auth Profile - Knowledge transfer on Ch33 Logging issues and any changes made

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34370]
## Background
There have been ongoing latency issues when calling the BGS service for edu direct deposit info.  This latency was impacting our ability to load the VA.gov profile in a timeline manner. 

This ticket is to capture time for Lihan to give Tom a summary of the issue, technical findings, and any backend changes that were made to improve performance.

Related issues:
- #34365
- #34369

## Tasks
- [x] Schedule a meeting where you two can discuss what transpired, the root cause, and any changes made to the VA.gov Profile backend as a result.

## Acceptance Criteria
- [x] Knowledge transfer meeting has occurred
- [x] Tom has a good understanding of what caused the latency issues and what (if anything) that Lihan changed on the back end to help mitigate the issues.

**Comment by lihanli** [comment]
i talked with tom today about this issue, the platform team mentioned yesterday that they are handling the logging problem, so there is nothing for our team to do for now.
