### ISSUE TITLE
[BE] Auth Profile: Determine how team can be automatically alerted of latency issues impacting VA.gov Profile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34371]
## Background
There have been ongoing latency issues when calling the BGS service for edu direct deposit info.  This latency was impacting our ability to load the VA.gov profile in a timeline manner, but the only way we were aware of it is if someone on the team noticed it, or if a Veteran or other use let us know. 

We need to determine if there is a better/easier way we can be alerted to backend issues like this without us having to wait on veterans to report the issues.  Ideally, there would have been some sort of flag/alert that let us know the direct deposit endpoint wasn't loading or was performing poorly without Joe Niquette having to let us know.

## Tasks
-  [ ] Determine if there if changes can be made in the application to send a notification in the event the edu direct deposit API is slow to load or times out.  
- [ ] Work with the PO and PM to determine the best medium for receiving that alert (team slack channel? email?)
- [ ] Implement the alerting and test on Staging

**Comment by Samara-Strauss** [comment]
It looks like Kevin Musiorski already has some automated alerts set up in [bgs-direct-deposit-payment-info-debugging](https://dsva.slack.com/archives/C02Q9FL124F). Should we have those alerts come into the auth experience channels? And should we have similar alerts for other endpoints in the VA.gov profile?

**Comment by lihanli** [comment]
i added two alerts to the #vsa-authd-exp-alerts channel, one of them sends a slack message when the average latency of the edu direct deposit API is over 30 seconds, and another alerts when the average latency of comp & pen direct deposit is over 30 seconds. alerts for other endpoints can be added as needed

**Comment by MarciMcGuireGCIO** [comment]
Thanks @lihanli ! Will those both land in the auth team channel?

**Comment by lihanli** [comment]
@MarciMcGuireGCIO they're currently sending to the #vsa-authd-exp-alerts channel but i could change it to another channel

**Comment by MarciMcGuireGCIO** [comment]
If there is already a designated alerts channel, that’s probably the place they should go.  I’ll subscribe.  Thanks again!

**Comment by Samara-Strauss** [comment]
> If there is already a designated alerts channel, that’s probably the place they should go. I’ll subscribe. Thanks again!

There's not. Thanks for creating  #vsa-authd-exp-alerts.

@lihanli do you think we need anything like this for the contact information or notification preferences endpoints?

**Comment by lihanli** [comment]
@Samara-Strauss it would be useful to be alerted for those endpoints too, i can work on adding that

**Comment by Samara-Strauss** [comment]
Great, thank you!  Those can also feed into the #vsa-authd-exp-alerts channel Marci set up. After you do that, will you post a list in this thread of all the endpoints for which you've set up alerts so we know what to maybe look out for?

**Comment by MarciMcGuireGCIO** [comment]
Just to clarify - Lihan set up the alerts channel.  Didn't want to steal his thunder!

**Comment by Samara-Strauss** [comment]
Ah, well thank you, @lihanli! I think you invited me, @MarciMcGuireGCIO, which is why I assume you created it. Great idea, @lihanli! I really appreciate it!

**Comment by lihanli** [comment]
**list of alerts in #vsa-authd-exp-alerts**
will trigger if average latency per api call in a 12 hour period is over 30 seconds

ppiu (direct deposit comp & pen)
ch33 direct deposit
notification preferences
all va profile contact information apis & address validation api
connected applications
service histories
full names
personal informations

**Comment by Samara-Strauss** [comment]
Thank you, @lihanli! I believe this is good to close.
