### ISSUE TITLE
[UNPLANNED] LGY Determination NOT_ELIGIBLE

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#34388]
## Background
During testing, it was reported that the NOT_ELIGIBLE scenario is not currently working in staging.

## Tasks
- [x] Determine why the NOT_ELIGIBLE scenario is not displaying properly

## Acceptance Criteria
- [x] Code and tests have been implemented
- [x] A PR has been requested for merging
