### ISSUE TITLE
Get SME input on back pay article for disability comp and pension benefits (IRIS rewrite)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34385]
## Issue Description
Stakeholders provided feedback on our back pay article and are sending us new information to add. Once they do, we need to rewrite in plain language and send back the final article to them for approval.

Preview link here:  http://preview-prod.vfs.va.gov/preview?nodeId=36481

We also want to look at whether we should change the H1.

## Tasks
- [ ] Incorporate new stakeholder info into article
- [ ] Copyedit
- [ ] Send to stakeholder for approval
- [ ] Review and use pre-publish checklist
- [ ] Publish
- [ ] Notify stakeholders that page is live

## Acceptance Criteria
- [ ] Back pay article live on the site

**Comment by bethpottsVADEPO** [comment]
Here's feedback from pension SMEs on back pay for that business line. We'll need to look at reworking the structure of this article and also making this content plain language:

**Can my Pension benefits be paid retroactively?**

In general, the effective date of a Veterans Pension award is the date the Department of Veterans Affairs received the claim. 
 
Veterans Pension may be awarded retroactive for up to one year prior to the date of receipt of claim if the Veteran met any of the following criteria continuously from September 17, 2001 until the date of claim;
- age 65,
- found disabled by SSA, or
- a patient in a nursing home for long term care because of disability
 
To qualify for a retroactive pension award under 38 CFR 3.400(b)(1)(ii)(B), the claimed disability must be so incapacitating that it reasonably could have prevented the Veteran from filing an application for pension. A disability will generally meet this requirement when it
 
~is so severe as to normally require hospitalization and intensive treatment;~
- was so incapacitating that it prevented the Veteran from filing an application from the date he/she first became permanently and totally disabled, and
- continues for a period of at least 30 consecutive days.

**Comment by lunascoop** [comment]
Hi @psanders86 I've reworked the SME feedback from Beth's comment above into the existing back pay article. The problem is that the existing back pay article uses a Single Q&A template, with an 1000 character count limit. The current verbiage is over by 146 characters with the info the SME provided. 

Since I can't save my changes to the article, I'll post my rewrite below. I've also created a new version of the article using the resources and support detail page template, which isn't limited by character count.

- What is VA back pay?: http://preview-prod.vfs.va.gov/preview?nodeId=36481 (Single Q&A article template and over by 146 characters)
- VA back pay: http://preview-prod.vfs.va.gov/preview?nodeId=42979

### Here's my rewrite

**H1: Can I get VA back pay for a disability or pension claim?**

Yes. You may be able to get back pay, or retroactive benefits, for your claim in a single, lump-sum payment.

**For disability compensation**, we calculate the amount of back pay you'll receive based on your start date for benefits (also called “effective date”) and your disability rating. 

[Learn about how we determine your effective date](link)

[Learn about how we determine your disability rating](link)

**For pension**, you may receive up to 1 year of back pay from the date we received your claim (also called “effective date”) for one of these reasons:

- Since September 17, 2001, one of these is true for you:
   - You’re at least 65 years old, **or**
   - You’re a patient in a nursing home for long-term care because of a disability, **or**
   - You were determined disabled by the Social Security Administration (SSA)

**Or**

- You have a permanent and total disability that prevented you from filing a claim for at least the first 30 days you became disabled (under 38 CFR 3.400(b)(1)(ii)(B)). This physical or mental disability can’t be due to misconduct.

   **Note:** You have 1 year from the date you became permanently and totally disabled to file a claim.

[Find out what evidence you need to file a pension claim](link to evidence needed article in the works)

-------

At first, I had wrote for the first bullet: You were eligible for pension benefits since September 17, 2001, **or**
This was based on SME's feedback that the Veteran had to be age 65, found disabled by SSA, or
a patient in a nursing home for long term care because of disability. But that's technically not correct since it leaves out the bullet (You have a permanent and total disability, or) on the [eligibility for pension](https://www.va.gov/pension/eligibility/) page. Plus that bullet point is covered in the other reason a Veteran can receive back payments.

Let me know if you want to sync on this.

Sources:
https://www.va.gov/pension/eligibility/
https://www.law.cornell.edu/cfr/text/38/3.400#b_1_ii_B
https://www.va.gov/disability/how-to-file-claim/evidence-needed/

**Comment by psanders86** [comment]
Thanks! I'll review this today.

**Comment by lunascoop** [comment]
@psanders86 I made additional edits to remove the sub-bullets. It's ready for your review.

VA back pay: http://preview-prod.vfs.va.gov/preview?nodeId=42979

**Comment by lunascoop** [comment]
@psanders86 I posted the article with the changes to the pension content. Basically, I separated how the back pay is determined for permanent and total disability (38 CFR 3.400(b)(1)(ii)(B)) based on this source: https://www.law.cornell.edu/cfr/text/38/3.400#b_1_ii_B

# H1: VA back pay
Page intro: Back pay, or retroactive benefits, is compensation we owe you for a disability or pension claim. We'll pay you the amount you're due in in a single, lump-sum payment. Find out if you can get back pay for your disability.

**CTA 1:** Learn about disability effective dates
**CTA 2:**  Apply for Veterans Pension benefits

## H2: How we determine your back pay
### H3: For disability compensation
We calculate the amount of back pay you'll receive based on your start date for benefits (also called “effective date”) and your disability rating. 

[Learn about how we determine your effective date]
[Learn about how we determine your disability rating]

### H3: For pension 
You may receive up to 1 year of back pay from the date we received your claim (also called “effective date”) if since September 17, 2001 one of these is true for you:

- You’re at least 65 years old, **or**
- You’re a patient in a nursing home for long-term care because of a disability, **or**
- You were determined disabled by the Social Security Administration (SSA)

**Or**
You may receive back pay due to a permanent and total disability (38 CFR 3.400(b)(1)(ii)(B)). The amount of back pay you'llreceive is based on your effective date or the date you became permanently and totally disabled, whichever date is earlier. To be eligible, both of these must be true for you:

- Your permanent and total disability prevented you from filing a claim for at least the first 30 days you became disabled, **and**
- Your physical or mental disability isn’t due to misconduct

**Note:** You have 1 year from the date you became permanently and totally disabled to file a claim.

[Find out what evidence you need to file a pension claim]

**Comment by RLHecht** [comment]
@bethpottsVADEPO This is now ready for you.

**Comment by RLHecht** [comment]
Update: This is staying in backlog until Beth has time to review. Then we'll need to send to stakeholders for approval before publishing.

**Comment by RLHecht** [comment]
Note to Laura: Look at page views from the Iris spreadsheet. Also review if this pertains to other benefits too.

**Comment by laurwill** [comment]
Documenting here that there were 974 page views for an IRIS FAQ with this question: Can I get back compensation payments?

**Comment by laurwill** [comment]
Hi @katherine-fung ! Thanks for jumping in to help with research here. 
We currently have a draft page about back pay for pension and disability benefits — now we need to confirm whether a concept of "back pay" exists for other types of benefits as well. 
Could you:
- Search in Github for any old tickets that mention back pay work for other benefit types?
- Search in Google for other types of VA benefits (like education payments, life insurance, etc) and terms "back pay" "retroactive pay" "retroactive benefits" and see if anything comes up?
Let me know if you have any questions. Here's the current page draft for context. Thanks!

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I found a few other mentions of back pay/retroactive pay/retroactive benefits for the following programs: 

**Life insurance:** 
- TSGLI: "You may be able to get retroactive TSGLI (meaning that it takes effect starting from a date in the past) if you were injured between October 7, 2001, and November 30, 2005, and you meet all of the TSGLI qualifications listed above." 

Source: https://www.va.gov/life-insurance/options-eligibility/tsgli/ 

**Housing:** 
- Funding fee: You can get a refund of the VA funding fee for a VA home if you're later found to have a service-connected disability

Source: https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/ 

- Housing grants: VA expanded eligibility for housing grants. These changes were announced in fall 2021, and they're retroactive to 2020. 

Source: https://www.military.com/benefits/veteran-benefits/disability/2021/10/07/expanded-housing-grants-disabled-veterans-now-available.html 

**Education:** 
- DEA: We discussed adding new information about retroactive benefits for DEA in this ticket [https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26625]. The ticket is currently blocked. 

[**Veteran Rapid Retraining Assistance Program (VRRAP)**](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/): 

"Will VRRAP backdate the payment of T&F (tuition and fees) and MHA until the enactment date of March 11, 2021?
Yes. Benefits may be paid retroactively for pursuit beginning on/after date of enactment by an eligible individual in a covered program of education." 

Source: https://benefits.va.gov/gibill/docs/VRRAP_FAQs.pdf 

I'm unsure if these next ones count under what we're looking for but including them here: 

Veteran Readiness and Employment program (VR&E): 
"If you’ve used benefits under any other VA education program and then you use VR&E benefits, we’ll have to deduct from your remaining VR&E entitlement the amount of time used under the other VA education program. 

But if you already used other VA education benefits and we determine that you’re eligible for VR&E, we may retroactively approve your previous months of entitlement and return them to the other VA education program. This is called 'retroactive induction.' Ask your VRC if you meet the eligibility criteria for a retroactive induction."

Source: https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/ (also in lay terms: https://www.militarytimes.com/education-transition/2021/04/12/change-allows-extra-gi-bill-benefits-for-some-disabled-vets/) 

- MHA under GI Bill: in several places online, VA addresses back pay for MHA due to changes made in 2018/2019. I'm not sure if this information is still relevant. 

https://www.va.gov/opa/pressrel/pressrelease.cfm?id=5151

https://www.va.gov/opa/pressrel/pressrelease.cfm?id=5154

**Comment by bethpottsVADEPO** [comment]
@RLHecht @laurwill I wanted to note here that if this R&S article expands to include other benefits than just disability comp and pension, we'll want to add the information from this education Q&A (that's blocked/was in draft but is now removed from the DEA node until SMEs respond to questions. And then if we add it to the broader R&S article, we'll also want to add it to the list of future COPE content that we're tracking for when expanded functionality for COPE arrives.

Here's the ticket for future COPE content: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/49711
