### ISSUE TITLE
[BE] Check routing number is nil or 0 and prevent the get_bank_info_from_rounting_number

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34382]
## Background
It has been determined that a call to `get_bank_info_from_rounting_number`  should not be made unless a valid routing number is returned from `find_ch33_dd_eft` .  Calling `get_bank_info_from_rounting_number` with an invalid number (ex `0`) results in stack trace errors, which could be slowing down ch33.

## Tasks
- [x] Modify logic in call to `get_ch33_dd_eft_info` from BGS service so that if the call to `find_ch33_dd_eft` returns `0` or `nil`, we do NOT follow that up with a call to `find_bank_name_by_routng_trnsit_nbr`.  
- [x] Test this hypothesis in Staging
- [x] If this hypothesis proves to be correct, conduct required testing and preparation to promote to Production

## Acceptance Criteria
- [x] Logic in call to `get_ch33_dd_eft_info` from BGS service has been modified so that if the call to `find_ch33_dd_eft` returns `0` or `nil`, we do NOT follow that up with a call to `find_bank_name_by_routng_trnsit_nbr`.  
- [x] Hypothesis has been tested in Staging
- [x] If this hypothesis proved to be correct, the required testing and preparation to promote to Production has been conducted.

**Comment by MarciMcGuireGCIO** [comment]
@bosawt - I only have visibility to front end deployments dashboard.  Can you confirm that this change is in Prod?  Thanks! 😄

**Comment by bosawt** [comment]
> @bosawt - I only have visibility to front end deployments dashboard. Can you confirm that this change is in Prod? Thanks! 😄

Yes, I can confirm from this log: http://sentry.vfs.va.gov/organizations/vsp/issues/44528/?environment=production&project=3&query=is%3Aunresolved+ch33&statsPeriod=14d
That we were seeing the `DdeftWebServiceBean-->findBankNameByRoutngTrnsitNbr-->routngTrnsitNbr is invalid` error before, but we are no longer seeing it after yesterday's deploy

**Comment by MarciMcGuireGCIO** [comment]
Awesome; thanks @bosawt !
