### ISSUE TITLE
[UNPLANNED] LGY Determination PENDING

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#34391]
## Background
The PENDING status for LGY's get COE feature needs to be implemented.

## Tasks
- [x] Determine which combination of responses for `\determination` and `\application` should display PENDING
- [x] Make sure the appropriate response is being sent to the FE

## Acceptance Criteria
- [x] Code and tests have been implemented
- [x] A PR has been requested for merging

**Comment by kathleencrawford** [comment]
We had a group discussion about this today and plan on following up tomorrow.  We also need to confirm with Kelli for some of the unknown use cases.

But for now, the Pending and Pending Upload statuses have been submitted in this PR for merging.  We will need another PR to make additional changes for other Pending scenarios not included here.
