### ISSUE TITLE
Discovery: Create Discovery Readout Documents

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3439]
## User Story or Problem Statement
As a UX designer participating in a discovery sprint, I need to create a discovery readout so I can the team, team leads, and future teams can learn about the completed work, concerns, opportunities, findings, and recommendations.

## Tasks (Hours)
- [x] Create markdown outline and content for GH (2 days)
- [x] Fill out the discovery sprint readout [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/discovery-sprints/End%20of%20Discovery%20Readout%20Template.pptx) with the findings from the user interview sessions (2 days)

## Acceptance Criteria
- [x] Discovery findings markdown document completed
- [x] Discovery sprint readout completed

## Next Steps
- Presenting our findings to the team and team leads
- Influences ideation/whiteboarding sessions and the form flow

**Comment by rileyorr** [comment]
@wygonikGCIO @rebeccawalsh The markdown file can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/discovery-nov19/discovery-readout.md). I will add another comment once the presentation deck is complete.

**Comment by rileyorr** [comment]
[20191227 MDT Discovery Research Readout.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4011005/20191227.MDT.Discovery.Research.Readout.pdf)
I've attached the discovery research deck and have linked it in the BaM2 channel. I will upload it to GitHub once any edits from the team have been incorporated.
