### ISSUE TITLE
[FE] Auth Profile: Address Change Messaging: Initial FE DIscovery

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34395]
## Issue Description

_See #30112 for more background and discussion from meeting with stakeholder team_

As a Veteran, I need to be aware that if I modify my home address that I also need to confirm my mailing address so I can make sure that I continue to receive correspondence and/or prescriptions from the VA.   

Today, there is a message in the Home address section, but it is not clear to the end user what exactly will occur if they click that box (it copies the existing mailing address to the home address fields, but the user may actually want the opposite to happen).  

It is also not immediately apparent in the Addresses section that the mailing address is the one used for VA correspondence and prescriptions, although it is mentioned in the very last bullet if the user expands the `Which benefits and services does VA use this contact information for?` info component.

## Tasks
- [x]  Determine feasibility of [solution Liz has mocked up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F33734%23event-5795066208&data=04%7C01%7Cmarci.mcguire%40gcio.com%7C53c98401b1ed4abada8d08d9c3f6ad70%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637756286524850335%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E36ZWOI09cJ0CRrVxC20bWyQPfgm%2B%2FUYGH6NE1ctwTA%3D&reserved=0)
- [x] Create tickets for tasks required to implement the proposed solution (or work with PM to create)
- [x] Estimate level of effort for each ticket

## Acceptance Criteria
- [ ] Feasibility of solution Liz has mocked up has been determined
- [ ] Tasks to implement the solution on the front-end have been identified
- [ ] Tickets have been created for the tasks and estimated

**Comment by adamwhitlock1** [comment]
After evaluating the current state of the contact information code and the design work here is what I have worked up:

# Discovery for Address Change Messaging

### Feasibility
The modal component looks to have the necessary functionality available to allow us to wire up the address change actions to display more information.

Modal component storybook: https://design.va.gov/storybook/?path=/docs/components-modal--default

Design docs for modal: https://design.va.gov/components/modal

Changing the Home and Mailing address and posting both of those updates at the 'same' time (aka when the modal 'yes' button is clicked) may present some interesting challenges.

- We are basically presenting one modal after another. Are their any accessibility/usability concerns to this type of flow?
- Wiring up the successive API calls will require some new implementations and testing around. Should a loading indicator appear at some point during these api calls to handle response latency?
- Handling the failure of one or both updates may create some confusion, especially is one address update call succeeds and one fails.
- At this point the notification that shows up below the address sections once the address is updated is limited to showing one at a time, and we would need the ability to display 2 notifications at the same time (one below mailing and one below home)

### Implementation Tasks

- Foundational Work (5 points-ish)
	- Adding feature flag for the scope of this work
	- Address comparison logic to prompt with modal / hooking into existing comparison logic
	- Adding modal component and content
	- Adding secondary modal after primary modal.

- Secondary work (5 points-ish)
	- Implement api calls and error handling logic where needed to handle one or both updates failing
	- Displaying errors or update confirmation
	- Enabling 2 notifications at once on the profile fields

- Final work (3 points)
	- Addressing accessibility
	- Building testing for all these additions

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @adamwhitlock1 !  I'll get tickets created for these.

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - Are each of the sub-bullets in your list of tasks a discrete issue? Thanks!

**Comment by adamwhitlock1** [comment]
I'd say each main bullet (foundationation, secondary, and final work) are each an issue with the sub-bullets the tasks for those issues. So 3 issues total

**Comment by andaleliz** [comment]
👀  hi! I'm lurking around tickets and noticed that you have addressing a11y as a final task. Curious what it might take to have accessibility addressed as an initial/foundational step in the dev process? It's so critical and I would love to learn more about what we can change in our processes to prioritize that and not leave it for last tasks.
