### ISSUE TITLE
Iterate on About VA disability rating page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34394]
## Issue Description
We need to review the [About VA disability ratings](https://www.va.gov/disability/about-disability-ratings/) page to determine if some content should change. Specifically, should the info in the second paragraph of the intro come down to where the disability calculator is? And should the calculator be housed within its own H2 with that info?

## Tasks
- [ ] Review current content on page
- [ ] Make updates in Drupal
- [ ] Review content
- [ ] Publish

## Acceptance Criteria
- [ ] Updated content live on site
