### ISSUE TITLE
[BE] Auth Profile: Send links to relevant Grafana & Sentry dashboards

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34403]
## Background
There have been some performance issues while loading the VA.gov profile and MyVA.  We would like to have links to all dashboards/monitoring for all Profile products.  

## Tasks
- [ ] Locate links to all Grafana and Sentry dashboards/monitoring visualization pages for all Profile products
   - Personal/Contact Info
   - Military Info
   - Direct deposit info (Edu & Disability Comp & Pension)
   - Notification settings
   - Account security
   - Connected apps
- [ ] Provide links to Samara and Marci via email or Slack.

## Acceptance Criteria
- [ ] Links to all Grafana and Sentry dashboards/monitoring pages for above-listed Profile products have been sent to Samara and Marci.

**Comment by lihanli** [comment]
i need to make a new grafana dashboard to show profile apis latency, the one that currently exists includes every single backend api

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @lihanli.  Is that something that can be completed today, or will it take longer?

**Comment by lihanli** [comment]
@MarciMcGuireGCIO i can complete it today

**Comment by MarciMcGuireGCIO** [comment]
Awesome! Thanks, @lihanli !

**Comment by lihanli** [comment]
@MarciMcGuireGCIO @Samara-Strauss 

Grafana: http://grafana.vfs.va.gov/d/lmh-7kA7k/va-gov-profile-apis?orgId=1

Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=level%3Aerror+controller_name%3A%5Baddresses%2Cch33_bank_accounts%2Cppiu%2Cpayment_history%2Cvalid_va_file_numbers%2Cpersons%2Cemail_addresses%2Cconnected_applications%2Ctransactions%2Ctelephones%2Ccommunication_preferences%2Cemail_addresses%2Cservice_histories%2Caddress_validation%2Cpersonal_informations%2Cfull_names%2Cnotifications%5D&statsPeriod=14d

**Comment by MarciMcGuireGCIO** [comment]
Thank you so much!
