### ISSUE TITLE
Establish and test new Mapbox dev API key

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34413]
### Issue Description
#33890 documents the report of a pay-per-use abuse vulnerability related to the unrestricted Mapbox token in va.gov/find-locations.  The researcher found a pay-per-user abuse on va.gov where any attacker can make unrestricted requests to the Mapbox API using the va.gov access token that can result in high cost for API usage.

We will begin our mitigation by following Mapbox's documentation for enabling URL restrictions. <span> </span><a href="https://docs.mapbox.com/help/troubleshooting/how-to-use-mapbox-securely/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">"How to use Mapbox securely"</a></p>

We have confirmed that the existing key is set to default and is currently unrestricted. Due to holidays and associate code freeze, we will not make any changes to keys until the new year. 

In #34412 we determine desired settings for new keys (secret scopes/default features) 

## Tasks
- [ ] Work with Nancy to establish new dev key with url restrictions 3 pts
- [ ] Implement new dev key and test

## Acceptance criteria
- [ ] New dev API key is available and has been tested to validate appropriate settings

**Comment by mmiddaugh** [comment]
We've learned the environment is not set up for dynamic keys - testing the new Mapbox dev key is blocked pending resolution.

**Comment by mmiddaugh** [comment]
Please see [Conversion Proposal](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2139783260/MapboxToken+Conversion+Guide+Proposal+draft)
