### ISSUE TITLE
[EKS] Create elasticache instances for loki

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#34424]
## Description
The goal is to extract memcached from the eks clusters as it is a stateful set and should be treated like other stateful components (i.e. postgres databases).  We can use a dedicated elasticache instance for this.  This alleviates the need to manage larger instances in the clusters themselves and dealing with any affinity conflicts when deploying the memcached pods.  It will also eliminate the need to deal with any oddities that come with provisioning a single larger instance in the eks clusters as it pertains to the eks rolling update (cycling eks nodes) which could result in unwanted downtime.

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1639758429146100
also questionable as to if the following threads are related but will include it for transparency
https://dsva.slack.com/archives/C02Q9FL124F/p1640017127356200
https://dsva.slack.com/archives/C02Q9FL124F/p1640109619405100

## Technical notes
https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/loki

---
## Tasks
- [ ] spin up elasticache instance in for loki dev
- [ ] make the appropriate changes (point to external memcached for `chunks` `frontend` `index-queries` `index-writes` and disable stateful sets for said components) in the loki distributed helm chart values.yaml file for dev.  
- [ ] confirm that loki is still logging correctly in grafana
- [ ] repeat in all environments

## Acceptance Criteria 
- [ ] loki is using external elasticache (memcached) instances for all environments and is still logging as expected

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Important note to make this work.  The memcached_client `host` parameter needed to be changed to `addresses` in the manifests

ex. https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/40ed3e6945555d42df9e353e1c78dd1a72face8d/apps/vsp-operations/loki/values-dev.yaml#L125

https://github.com/cortexproject/cortex/issues/1505#issuecomment-808428354

**Comment by mleclerc00** [comment]
Loki dev was running into the error `SERVER_ERROR object too large for cache` which was remedied by increasing the `max_item_size` from ~1MB to ~10MB

All seems well now and there are no immediate concerns searching through the loki-distributed logs looking for any keywords such as `error` `fatal` `memcached` etc

I will keep an eye on it and will be moving onto setting up staging

**Comment by mleclerc00** [comment]
Loki staging is now pointing at elasticache memcached instances

**Comment by mleclerc00** [comment]
Loki sandbox/utility are now pointing at elasticache memcached instances.  Will be waiting until next week to roll out prod.

**Comment by mleclerc00** [comment]
Loki prod is now pointing at elasticache memcached instances

**Comment by mleclerc00** [comment]
https://app.datadoghq.com/dashboard/33k-mvc-q33?tpl_var_env=%2A&tpl_var_environment=dev&from_ts=1640639846169&to_ts=1640641646169&live=true

datadog dashboard for loki memcached

**Comment by mleclerc00** [comment]
https://app.datadoghq.com/monitors/58934395

datadog monitor updated to alert on low memcached memory coming from elasticache

**Comment by mchelen-gov** [comment]
@mleclerc00 nice! can you document the dashboard & monitor in our confluence internal docs?

**Comment by mleclerc00** [comment]
Will do, we are reworking the monitor at the moment since it doesn't seem like alerting on unused memory is a reliable metric based on how memcached works.  But will get both added to confluence.
