### ISSUE TITLE
Add hours of operation to Vet Center Locations page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34423]
## Issue description
The Vet Center location page includes the name, address and phone number for the main Vet Center and any associated outstations 
and community access points (if any). Hours of operation data for the main Vet Center and outstation comes from VAST.

### Current experience
Hours of operation are shown only for the main Vet Center and only on the main page.

<details>
<summary> Screenshots </summary>

Main page display for main Vet Center
![image](https://user-images.githubusercontent.com/55411834/146981967-f35100dd-8fa0-4bf6-826e-1d0c058022be.png)

---
Locations page 

![screencapture-va-gov-nashville-vet-center-locations-2021-12-21-11_43_56](https://user-images.githubusercontent.com/55411834/146982017-8433e3d1-e4a3-42b3-a3f0-7743920f16f3.png)

</details>

### Desired experience
The Locations page displays hours of operation for the main Vet Center, associated outstations and community access points. 

### Out of scope 
- Location displays for associated mobile Vet Centers and other listed nearby Vet Centers
- The display for Community access point hours of operation is in a separate issue #34316. 

### Grooming notes
- **Need to get field names** 

## Tasks
- Add hours of operation for main Vet Center and any outstations to front end query of Vet Center locations page template. 

## Acceptance criteria
- [ ] Vet Center Locations page displays hours of operation for main Vet Center, consistent with the style displayed on the main page. 
- [ ] Vet Center Locations page displays hours of operation for any associated outstations, consistent with the style displayed on the main page.
- [ ] Displayed hours are consistent with VAST data for the relevant location.

**Comment by mmiddaugh** [comment]
This work has been completed during  #34316
