### ISSUE TITLE
[Design] HLR Informal Conference section on Review Page

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3443]
## User Story or Problem Statement
As a claimant, I need to review and submit my HLR form so I can ensure all of the information I provided is accurate and submit my form.

## Goal
_Create a user friendly view of information specific to Informal Conference to be reviewed and submitted_

## Tasks
- [x] Include Informal Conference details on review page
- [x] Request content review #3567 
- [x] Request design review #3566
- [x] Provide InVision link on FE ticket #3444 

## Acceptance Criteria
Scenario: System user wants to review and submit their HLR form
- GIVEN the HLR review form has been completed by a user_
- WHEN the user reviews their provided form responses_
*and* confirms their responses are accurate
*and* selects to submit their application
- THEN the system submits their HLR form

**Comment by kevinstachura** [comment]
Invision design: https://vsateams.invisionapp.com/share/BKUTWR2T457#/393337658_Review_Application_-_Expanded_-_Informal_Conference_-_Representative

**Comment by YanaRoy** [comment]
@rileyorr this ticket should cover the review screen for the Informal Review section when a user chose to "contact me"

**Comment by rileyorr** [comment]
@YanaRoy I have added a screen for the "contact me" review screen: https://vsateams.invisionapp.com/share/BKUTWR2T457#/393337658_Review_Application_-_Expanded_-_Informal_Conference_-_Representative
Do you need me to create the content/design review tickets?
