### ISSUE TITLE
EducationBenefitClaim/Spool file record cleanup

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#34448]
## Issue Description
On 12/17 & 12/20, the `KmsEncryptionVerificationJob` was run to verify that encrypted records were able to be decrypted by the new kms key (so that we could remove the lockbox key). While the Kms job was running, the job marked some of the EducationBenefitClaim records for re-processing again. What happened is that there's a [job](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/delete_old_applications.rb#L13-L19) that cleans up records older than 2 months. When we ran the `KmsEncryptionVerificationJob` to update the `verified_decryptable_at` date, it recreated a SavedClaim::EducationBenefits record when this [validation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/education_benefits.rb#L25) ran. The newly created record had a `processed_at` date of nil, which is what caused the [CreateDailySpoolFiles job](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/create_daily_spool_files.rb) to pick it up and process it.

---
## Additional Info
[Slack thread with EDU team](https://dsva.slack.com/archives/CBU0KDSB1/p1639762159212100)
[VSP internal discussion](https://dsva.slack.com/archives/CBU0KDSB1/p1640097269325600)

- We are currently waiting to hear back from the EDU team to verify that TIMS has received the spool files for 12/17 & 12/20
- The current design around the SavedClaims/EducationBenefitClaim records is a bit hard to follow, so a redesign follow-up may be needed in the future. 
- The #vsa-education-logs slack channel shows that the [files were created.](https://dsva.slack.com/archives/C01T05TPTQQ/p1640121550006200)

## Tasks
- [x] Debug/cleanup spool file records for 12/17 & 12/20
- [x] Re-run separate spool file jobs for 12/17 & 12/20
- [ ] Verify with EDU/TIMS that they've received the spool files

## Acceptance Criteria
- [ ] TIMS has received the spool files for 12/17 & 12/20
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
