### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 1/3

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34452]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John Scott McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [x] New ticket created

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks. I published and created a new ticket.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
