### ISSUE TITLE
Backend Onboarding: Postman

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34459]
## Background
When a new member joins VSA, there are a number of different milestones that are needed.  Some need simple knowledge transfer, others require more in-depth assistance to get set up.

## Tasks
- [ ] Postman has been introduced
- [ ] A practice scenario has been created/simulated
- [ ] Any necessary tests have been drafted and reviewed

## Acceptance Criteria
- [ ] New team mate is comfortable with Postman

**Comment by alsleaders** [comment]
I have completed Postman set up so I'm closing this ticket.
