### ISSUE TITLE
[Design] Updated Address Editing Patterns Based on Profile Team's Findings

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34454]
# Description: 
We made the decision to utilize the same pattern that profile is currently using for ["your mailing address and home address are the same."](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/m1yqZxg). The profile team is running a user research study during the first week in January 2022 to test an improved design on how to denote that a Veteran's home and mailing address are the same. Depending upon the outcome of the study, we should adjust our editing pattern for addresses (and also denoting that emergency contact and next of kin are the same).

## Background Info

# Tasks:
- [x] Meet with profile (Christina Gednalske) to understand the outcome of their research study.
- [ ] Decide if any changes from profile teams final designs need to be made for check-in's use case
- [ ] Update the mailing/home address being the same pattern as well as emergency contact/next of kin being the same within the pre-check-in UXUI Sketch file.

# Acceptance Criteria:
- [ ] Send out revised pre-check-in wireframes for team to review.
- [ ] Wireframes are created based on the profile team's findings:
        Reminder - Step 1: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/ELMOrgO
        Reminder - Step 2: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/1KMa1K4

# UX side note for consideration:
- The UX work is complete. But while reviewing/discussing the profile team's address editing UX pattern, we have identified some areas that needed additional clarification. This could potentially result in redoing the UX work that could impact FE also. That being said, I would like to recommend that further UX exploration/investigation is performed. @kristenmcconnell @loripusey 

**Areas of clarification:** 
- The design intent and user insights for setting the 'My home address is the same as my mailing address'. 
- The reminder modal has a secondary option that leads to a follow-up modal that needs to be clarified
- Possibility of adding the 'My mailing address is the same as my home address.' checkbox in the mailing address edit page.

**Comment by kristenmcconnell** [comment]
Here is profile confirmation that mailing and home addresses having been updated: https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/L02Y9j3

**Comment by kristenmcconnell** [comment]
More information from Christine with their latest design: https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/My2J4Zb/

"We've finished the changes for the address update modal. Here's a link to the mobile sketch files. The error alert wasn't working within the modal, so there will be a separate error modal instead (similar to the success modal)."

**Comment by zach-park** [comment]
Here is the update and  expected behavior based on VA Profile UX:
- Earlier on, before research, the checkbox content was changed from "My home address is the same as my mailing address" to "Use my mailing address for my home address."
- Content changes were made within the modal to clarify information - definitely noted
- Hint text was added to both Mailing and home fields
- The recent switch to the error alert modal for mailing address update failure (instead of the in-line alert within the modal)

**Comment by zach-park** [comment]
Hi @loripusey , here is the ticket I mentioned today during the 'Review Items from Eng Refinement' meeting. This ticket would require a follow-up ticket in the next sprint. Thank you! Cc: @kristenmcconnell

**Comment by kristenmcconnell** [comment]
Further work to be completed in 38836.
