### ISSUE TITLE
Backend Onboarding: Access and Authentication

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34458]
## Background
When a new member joins VSA, there are a number of different points of access that are needed.  Some need simple knowledge transfer, others require more in-depth assistance to get set up.

## Tasks
- [x] Reach out to Program or Operations Manager to start the PIV process
- [x] Access to relevant Slack channels are obtained: #vsa-ebenefits-migration, evss-dev, evss-prod, backend-dev, vfs-platform-support, etc
- [x] VA network (CAG, VPN, SSH)
- [x] GitHub
- [x] VSP Orientation
- [x] SOCKS

## Acceptance Criteria
- [x] New team mate has a PIV card or has started the process
- [x] New team mate has access to correct Slack channels, GH
- [x] New team mate has attended an orientation applicable to their practice
