### ISSUE TITLE
Backend Onboarding: Creating and Sending a PDF

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34469]
## Background
This ticket is intended to represent the efforts taken in learning how to generate and populate (and maybe send?) a PDF on VA.gov

## Considerations
[Documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/PDF-generation.721780786.html) 

## Tasks
- [ ] Walkthrough documentation, if any
- [ ] Test procedures

## Acceptance Criteria
- [ ] New BE has an understanding of how PDFs live 'round here
- [ ] A PR has been requested for merging, if applicable
