### ISSUE TITLE
Backend Onboarding: Feature Toggles

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34463]
## Background
When a new member joins VSA, there are a number of different milestones that are needed.  Some need simple knowledge transfer, others require more in-depth assistance to get set up.

## Tasks
- [ ] Read or attend an orientation on Feature Toggles (Flipper) to get a baseline for what is involved in creating a feature toggle
- [ ] Test the feature toggle

## Acceptance Criteria
- [ ] New team mate is comfortable with Feature Toggles

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/adding_email_to_a_feature_toggle.md
