### ISSUE TITLE
Review and edit failed 526 form submission email

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34460]
## Issue Description
Sitewide content needs to review email copy for the 526 form when there is a failed submission. We need to edit this to meet plain language standards and to ensure it matches VA.gov's voice and style. Once we are finished with our review we will send to Beth for review and then post final language in ticket #34119.

Content to review:

Subject: An error occurred with your disability claim application on VA.gov.

Hello [user],

Due to a technical error, we couldn’t process your form. This can occur after the form has been submitted on the VA.gov website. At this time, we advise that you [fill out and submit our 526 paper form].

Send in your completed form and any evidence in support of your claim to:

Department of Veterans Affairs
Evidence Intake Center
PO Box 4444
Janesville, WI 53547-4444

Alternatively, you can bring your application to a [VA regional office near you] and submit in person.

We apologize for the inconvenience.

## Tasks
- [x] Edit and review (Selina)
- [x] Copy edit (Randi)
- [x] Send to Beth for final draft (Randi)
- [ ] Post final copy in intake request ticket (Randi)

## Acceptance Criteria
- [ ] Content is approved to go to 526 team

**Comment by lunascoop** [comment]
@RLHecht here are my revisions to the email. Let me know your thoughts.

Subject: We couldn’t process your claim application

Hello [user],

We’re sorry. Your application didn’t go through. This can happen after submitting your application using our online tool. 

Please fill out an application and submit it to us by mail or in person.
[Download VA Form 21-526EZ (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf)

**To submit by mail,** send your completed application and supporting documents to:

Department of Veterans Affairs
 Evidence Intake Center 
PO Box 4444 
Janesville, WI 53547-4444

**To submit in person,** bring your completed application and supporting documents to your nearest VA regional office.
[Find a VA regional office near you](https://www.va.gov/find-locations/?facilityType=benefits)

Thank you.



**A couple of notes:**

The last sentence of the first paragraph can also read: We’re working to fix the problem, but it may take us a while.
I don’t know which is more reassuring.

Also need to confirm it’s Evidence Intake Center and not Claims Intake Center (like on our [How to file a claim](https://www.va.gov/disability/how-to-file-claim/) page)

**Comment by RLHecht** [comment]
Here are the edits from our slack convo:

Subject: We couldn’t process your claim application

Hello [user],

We’re sorry. Your application didn’t go through. Something went wrong on our end, but we’re working to fix the problem.

Please fill out a new application and submit it to us by mail or in person.
[Download VA Form 21-526EZ (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf)

**To submit your application by mail,** send your completed form and supporting documents to:

Department of Veterans Affairs
 Evidence Intake Center 
PO Box 4444 
Janesville, WI 53547-4444

**To submit your application in person,** bring your completed form and supporting documents to your nearest VA regional office.
[Find a VA regional office near you](https://www.va.gov/find-locations/?facilityType=benefits)

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here are our edits to the 526 email. Please let us know when we can put the final copy in their intake request ticket.

**Comment by bethpottsVADEPO** [comment]
@lunascoop @RLHecht 
Thank you, this is much improved. Here are some suggestions I have (and I don't need to see it again--you can update the intake request and send it off to that team!):
1/ Subject line: We couldn't process your VA.gov disability claim application
2/ I think you should take out "but we're working to fix the problem" because that doesn't matter for someone we're telling needs to fill out a paper form now. 
3/ Put (evidence) after "supporting documents"
4/ Add back in a last line, but make it less formal than "We apologize for the inconvenience.": We apologize for the extra work this causes for you.

**Comment by RLHecht** [comment]
Thanks @bethpottsVADEPO Sent Kevin the revised content in the other ticket. Closing this one.
