### ISSUE TITLE
Backend Onboarding: Monitoring and Error Handling

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34470]
## Goals
For  backend engineers, they should have access to the proper tools, and the ability to set up monitoring for errors across different features so that we can respond quickly and efficiently in diagnosing and resolving issues.  We should not hear about errors or issues via Twitter :upside_down_face:

## Considerations
- Grafana + DataDog
- integrations into #vsa-ebn-alerts (Slack)
- a version that shows **totals** vs **successful** vs **failed** submissions would be helpful for KPIs and other success metrics, not just red alerts

## Tasks
- [x] Request accounts and/or access to DataDog and/or Grafana
- [x] Setup an initial dashboard and test it
- [ ] Integrate monitoring into Slack for awareness (#vsa-ebn-alerts)
- [ ] Share outcomes with EBN Team
- [x] If able, steps have been shared to create other dashboards for other features

## Acceptance Criteria
- [x] Access has been requested
- [x] A dashboard for at least one feature is stood up
- [ ] Error messaging is found in the correct Slack channel, as needed
