### ISSUE TITLE
Update number of days to complete disability related claims for February

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34474]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [ ] Most current number of days is on live site.

**Comment by RLHecht** [comment]
Tanekwa emailed with February's number: 162.4. I'll update and have Patrick review before publishing.

**Comment by RLHecht** [comment]
@psanders86 Since Selina is out today, could you please review the changes I made on these 2 pages so I can publish these? It's just the number of days to complete claims and the month that where changed. Thanks!

**Comment by psanders86** [comment]
This is good to go, thank you @RLHecht

**Comment by RLHecht** [comment]
Thanks @psanders86 I just published. Moving to validate.
