### ISSUE TITLE
Update bold text page in style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34471]
## Issue Description
We need to add a new bullet to the [bold text page](https://design.va.gov/content-style-guide/bold-text) in the content style guide explaining when text should be styled as an H3 or H4 subhead instead of being bolded. 

The bullet should be in the "Don't use bold in these cases section."

Here's a ticket for background on why headers can work better than bold in certain situations: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19301

Additional info:

Use semantic markup to properly announce style changes to all users. Bold and italics are often used to highlight words or phrases in a paragraph of text. The Strong tag and the Emphasis tag are considered Semantic Markup that allows for added meaning to your content. It serves as an indication to the screen reader (SR) of how something should be understood. When using bolded in a piece of text using the b tag, it will be of no benefit to screen reader users. This is especially critical when the tag helps to convey special meaning for the words or phrases being highlighted. Content editors may be using the bold tags (b) in place of a heading tag (h1) thinking it will be conveyed to all users. But as we have identified, bold tags are not announced to screen reader users. Additionally, heading tags are an essential way for screen reader users to scan a page. Using short-cut keys, the screen reader would read all the headings on the page so that the user can navigate quickly to areas of need or interest. Avoid from using style tags such as b and i. Use semantic tags strong and em (italics). Use heading levels to break up content and make it more scannable.

## Tasks
- [x] Write entry to style guide (Randi)
- [x] Review (Beth)
- [x] Notify design system council that we are making a change (Randi)
- [x] Merge PR (Beth/Randi)

## Acceptance Criteria
- [x] New entry is live in style guide

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the PR for the bullet I added. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/617

**Comment by RLHecht** [comment]
@GnatalieH We added the bullet to the style guide and it will go live in the next deploy. For your awareness for crosslinking with your entry in the design system.

**Comment by RLHecht** [comment]
This is now live. Closing ticket.
