### ISSUE TITLE
Update number of days to complete disability related claims for June

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34476]
## Issue Description
We need to update the number of days it takes to complete disability related claims and change the month to June. Sitewide content needs to email Tanekwa Bournes on the second of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and update month on both Drupal pages 
- [x] Review and publish (Megan)

## Acceptance Criteria
- [x] Most current number of days and most recent month is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore Just heard back from Tanekwa. The number for June should be: 132.7
Can you please update the two pages with this new number and change the month to June? Thanks!

**Comment by aliyahblackmore** [comment]
Hey @megzehn these are ready for you! 

Preview link 1: http://preview-prod.vfs.va.gov/preview?nodeId=870
Preview link 2: http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by RLHecht** [comment]
I published both of these pages. Moving to validate and will close and email Tanekwa once I see the changes are live.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket!
