### ISSUE TITLE
Update number of days to complete disability related claims for September

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34477]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Aliyah)
- [x] Review and publish

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore I just got September's info. Could you please update the 2 pages? The new number should be 106.4

Thanks!

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht ! These are both ready for you.

The VA claim process after you file your claim: http://preview-prod.vfs.va.gov/preview?nodeId=870
How to file a disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by RLHecht** [comment]
Thanks, Aliyah. I reviewed and published these. Will close once live.

**Comment by RLHecht** [comment]
Pages are live. Closing ticket.
