### ISSUE TITLE
Update number of days to complete disability related claims for August

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34479]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Aliyah)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore I emailed Tanekwa this morning to get the most recent numbers. I'll post here once I have them for you to update the pages. Thanks!

**Comment by aliyahblackmore** [comment]
Thanks, Randi! 
Hi @megzehn these two pages are ready for you!


Preview links: 
http://preview-prod.vfs.va.gov/preview?nodeId=870
http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by RLHecht** [comment]
I reviewed and published these changes. Moving to validate and will close once it's live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
