### ISSUE TITLE
Update number of days to complete related claims for July

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34478]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Aliyah)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore Tanekwa reached out and she's going to send us July's information tomorrow (8/2) so we can make the updates.

**Comment by RLHecht** [comment]
@aliyahblackmore Tanekwa wrote back with the number: 125.3

Thanks!

**Comment by aliyahblackmore** [comment]
Hi @megzehn - these pages are ready for you! 

The VA claim process after you file your claim
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=870

How to file a VA disability claim
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by megzehn** [comment]
Thanks @aliyahblackmore! I reviewed and published these pages. 

CC @RLHecht

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
