### ISSUE TITLE
Update number of days to complete disability-related claims for October

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34481]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number into both Drupal pages (Aliyah)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore could you make these updates? The number for October 2022 should be 102.4.  Thank you!

**Comment by aliyahblackmore** [comment]
Thanks, Randi! This is ready for you.


**The VA claim process after you file your claim**: http://preview-prod.vfs.va.gov/preview?nodeId=870
This page was impacted by the linkies so I did a revert to the last published version.

**How to file a VA disability claim:** http://preview-prod.vfs.va.gov/preview?nodeId=905
I made the changes to the 10/25/2022 - 9:27am version

**Comment by RLHecht** [comment]
Thanks, @aliyahblackmore These pages are both published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
