### ISSUE TITLE
[Research] Plan Appointment Notifications Study with VAOS

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34484]
# Description: 
VAOS (Peter Russo) and Check-in are going to pair up to run a study that was already in the [VAOS backlog](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/appointments/research/2021-10%20Notifications%20service%20map%20workshop) on appointment notifications. Their study plan will also help check-in understand the appointment notification landscape, in order to make sure pre-check-in is successful.

# Tasks:
- [ ] Met with Peter to discuss participant recruitment, review facilitation strategy, and plan when we hope to start the sessions. Discuss if the study needs to go through any approvals or if VAOS already did that. (Meeting tentatively scheduled for Jan. 4)
- [ ] Create a list of staff to recruitment.
- [ ] If necessary, update the research plan.

# Acceptance Criteria:
- [ ] Reach out to at least one VA facility to start scheduling a research session.
