### ISSUE TITLE
Design intent [Facilities Team - Lovell Federal Health care]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34483]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [x] Yes - for the product, yes - for the iteration, no
- [ ] No

## Artifacts

Provide links or documents for the following: 

- [x] [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell-initiative-brief.md)
- [x] Relevant issues
       - Epic: Lovell VAMC pages #34022
       - Design for VAMC Lovell "Manage your health online"/top tasks #34026 
- [x] Design mockups
       -  [UX Pin for facility page](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/145465352/simulate/no-panels?mode=i)
       - [UX Pin with modal options](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/145465846/simulate/no-panels?mode=i)
- [ ] User flow

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event - _scheduled for 2:00pm - 2:30pm, Friday, January 7, 2022_

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
@mmiddaugh this is confirmed for 1/7/22 at 2pm ET

**Comment by shiragoodman** [comment]
@mmiddaugh did you submit a Collab Cycle kickoff for this work? I'm not able to find the ticket.

**Comment by mmiddaugh** [comment]
@shiragoodman I did not submit a kickoff issue since this work is an iteration of the VAMC modernization (ie: Pittsburgh pages)

**Comment by mmiddaugh** [comment]
Context for @AngelaFowler82 

This work iterates on the VAMC pages already in production - you might be familiar with them as the "Pittsburgh VAMC pages". 

An example system level home page on Production is https://www.va.gov/lovell-federal-health-care/ 
On this page we will focus on two areas: 
1. the three top task buttons labeled Make an appointment, View all health services, and Register for care
2. the manage your health online area which features six links: Refill and track your prescriptions, Send a secure message to your health care team, Schedule and manage health appointments, Download your VA medical records (Blue Button), View your lab and test results and Order hearing aid batteries and accessories

An example system level home page on Production is https://www.va.gov/lovell-federal-health-care/locations/captain-james-a-lovell-federal-health-care-center/ 
On this page we will focus on two areas: 
1. the three top task buttons labeled Make an appointment, Register for care , and Pharmacy
2. the manage your health online area which features six links: Refill and track your prescriptions, Send a secure message to your health care team, Schedule and manage health appointments, Download your VA medical records (Blue Button), View your lab and test results and Order hearing aid batteries and accessories

The problem to solve is how to have the user identify themselves as a Veteran or active duty service member so that we can direct them to the correct portal for the task. 
Additional wrinkles include: 
1. In some cases, the facility serves Veterans and active duty service members but a task on the page may apply to only one of the populations 
2. In some cases the facility only serves Veterans or active duty service members - but not both

Josh has reviewed the UXPins and provided feedback.

**Comment by jimuhh** [comment]
@mmiddaugh Do you have any prior _discovery_ user research we can look at on this? Us folks on the Collaboration Cycle team are not the end users of this product, so it would be very helpful for us to hear from the people who are when evaluating a design direction. 
Thanks!

**Comment by jimuhh** [comment]
@mmiddaugh Would it be possible to revise the [initiative brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell-initiative-brief.md)to fit the customary [problem statement](https://medium.com/@MattPLavoie/what-s-your-problem-e45b31bf08dd) format? I have found the template on the linked page very helpful in doing this. 

We'd like to gain a more comprehensive view of the problem to be solved before evaluating a proposed solution. The "additional wrinkle" you mentioned in your last comment seems significant. Would it be possible to explore that more fully using the problem statement template linked above? 
Thanks!

**Comment by mmiddaugh** [comment]
Closing this as we are requesting a follow-up design intent for the latest iteration, informed by additional input. 
Design intent [Facilities Team - Lovell federal health care page iteration] #38196
