### ISSUE TITLE
[PM] On-site Notification: Create test cases in TestRail

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34485]
## Background
With design finalized and use cases/rules documented, a list of test cases needs to be created.
Reference [My VA 2.0 Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md) for examples
Reference [Getting Started](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/getting-started.md) for TestRail access

## Tasks
- [x] Create test cases based on use cases

## Acceptance Criteria
- [x] Use cases will be created - [Link to Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Onsite-Notification.md)
- [x] TestRail test cases created - [Link to TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3308&group_order=asc&display_deleted_cases=0)

**Comment by hdjustice** [comment]
Draft Use cases and Test cases created in preparation for Midpoint review

**Comment by hdjustice** [comment]
@Samara-Strauss I created some test cases for On-site Notifications as well.  I am not sure what user we will use yet, but I tried to think of all the scenarios.
cc @andaleliz for awareness
