### ISSUE TITLE
Page last updated audit for health care

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#34493]
## Issue description

As part of our work to create a more robust editorial calendar and regular content auditing, we need to assess when each of the pages within the VA.gov health care hub was last updated and whether there's any information on the page that always changes at a specific time (like rates that change annually or a new law that's set to change on a certain date). We'll then work with our VHA partners to determine the best SME to connect with to review each page and prioritize those reviews on a rolling, annual or semiannual basis.

## Tasks for this issue

- [x] Fill in the last-updated date for each page in the attached spreadsheet
- [x] Add a column to the spreadsheet to capture notes on any pages that will need updates at a specific time

## Acceptance criteria

- [x] Spreadsheet has last updated date for all pages and timely updates notes for relevant pages

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the issue and spreadsheet for the last updated audit we briefly talked about for this sprint. Just let me know if you have any questions, thanks!

[VA health care hub audit_12.15.21](https://app.zenhub.com/files/133843125/08d7a56a-1ad0-40de-82ea-6dc4ec3b414b/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here is the spreadsheet with all the last updated dates and a few notes. Except for the dental insurance one, none have a specific time for an update. I did note the pages we have the alert for payment collection starting again on 10/1/21 since I think we will eventually want to remove that. 

[https://app.zenhub.com/files/133843125/392cdc66-c3ae-4da2-98e9-0d7cf397b353/download](https://app.zenhub.com/files/133843125/392cdc66-c3ae-4da2-98e9-0d7cf397b353/download)
