### ISSUE TITLE
Kick off Identity focused initiative

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#3449]
- [x] Figure out teaming
- [ ] Collab w/other programs (VSA, VA Startup SSO) to understand overlap / responsibilities
- [ ] Hand off to PM to drive discovery, roadmap, bets, measurements, implementation etc

## Objective
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

**Comment by rroueche** [comment]
Status: have identified desired eng talent to lead this initiative
Need to start supporting the SSO team that's moving fwd on a solution

**Comment by rroueche** [comment]
- Sprint 13: chat w/Anna and Patrick, continue hiring
- Sprint 14: strategy talks continue w/ Andrew

**Comment by rroueche** [comment]
## Teaming on Platform side:
- 

## Roadmap

In terms of roadmap, there are 2 possible routes, the priority of which has not yet been decided by DEPO:

1) Collaboration with the Caregiver Team to enhance the current version of login to allow Caregivers to also log in (and track the status of their applications, etc). Note: in order for a Caregiver to submit an application, they do not necessarily need log in, so this may not be the highest priority enhancement to work on next wrt Identity.

2) Collaboration with the eBenefits migration team(s) to enhance the current version of identity management to allow delegated persons to log in and take action on behalf of a Veteran.
