### ISSUE TITLE
 'View your disability rating' feature migrating into VA.gov

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3451]
## High Level User Story
As a Veteran with a rated disability (or multiple rated disabilities), I need an easy way to see my combined VA rating and know that I can do this online, instead of calling VA or looking for my VA letters.

This feature displays the Veteran's total VA combined rating + list of all of their disabilities that are rated.

## Purpose of this epic
**Add a new static 'tool' landing page where ppl can sign into see their rating** 
**ETA: tool launch late Nov/early Dec, per Steve Kovacs, so static content should try to correspond closely with tool launch whether at launch or right after.

## Tasks
**Content:**
- [ ] Revise and write new additional copy for the static landing page. See mockup from apps team. 
- [ ] Incorporate into nav
- [ ] Update existing disability hub and detail pages as appropriate.
- [ ] Loop in Peggy Gannon to review close-to-final content and incorporate feedback.
- [ ] Work with Disability stakeholder to verify content with SMEs and gather relevant feedback. (Paul Shute is our Disability stakeholder lead, but he may need to loop in technical or business SMES to review.)
- [ ] Send Steve Kovacs and Disability stakeholder final preview page before go-live. 
- [ ] Let Steve Kovacs and Disability stakeholder know when updates are published.

**FE engineering:**
- [ ] Build REACT widget on relevant pages and locations; and coordinate with Drupal author for preview and go-live. 

**Analytics:**
- [ ] Add tracking to new landing page.

## Details
**URL of new static landing page:**
www.va.gov/disability/view-disability-rating/ 
[Confirmed w/Mikki on call w/Peggy, 11/13/2019  ]

**Benefit hub:** Disability
**Nav link location:** Under Manage benefits spoke > After/below “Check claim or appeal status” link
**Hub landing page location:** Same as nav location.

**Update existing page:**
About VA disability ratings https://www.va.gov/disability/about-disability-ratings/  
- Add the REACT VIEW RATING tool on this page after/below the calculator (w/appropriate header text IF NEEDED)

## Content notes for assigned web content person
[disability-view-rating-static-landing-pg-ticket-content-notes-111319.docx](https://app.zenhub.com/files/133843125/3ba1b04c-80c8-4346-a592-d0b21e680738/download)

## For reference
**Mockup with DRAFT content here:**
https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/  

OLD ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2244
IA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2584

**Comment by Karak888** [comment]
@jenniferlee-dsva I am closing this as it wasn't created as a true epic and wanted to be sure we had one to associate for REACT, content, analytics, and redirect tickets.  I have copied everything from this ticket over but it's now an Epic.
