### ISSUE TITLE
Create vets-api Slack Service module

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#34516]
## Issue Description
`vets-api` currently leverages a Ruby gem called [Slack Notify](https://github.com/sosedoff/slack-notify) to handle most of its Slack notifications, this gem is largely unsupported at this point and does not allow for rich text formatting via Slacks [Block Kit](https://api.slack.com/block-kit) framework - only plain text messages can be sent. In addition to this gem, the Appeals API has created [their own Slack notification module](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/appeals_api/app/services/appeals_api/slack) that allows for more robust features. This module replicates much of the Slack Notify features, but still does not allow for Slack blocks and rich text formatting. Both of these implementations should ideally be replaced by a common service designed for use across vets-api and able to interpret more complex message types.

This issue ticket covers the initial creation of a "Slack Service", conversion of existing Slack messaging within vets-api to this service (including necessary feature improvements to ensure no existing functionality is lost) will be covered in subsequent tickets.

---
## Tasks
- [x] Create a new `Slack Service` within vets-api's `lib`, available to all parts of the application
- [x] Enable the Slack Service to send plaintext notifications
- [x] Enable the Slack Service to send Slack `section` blocks with Markdown text formatting
- [x] Enable the Slack Service to post to a variety of Slack webhooks, enabling to feature to function across any number of Slack bots
- [x] Add unit test coverage to the Slack Service

## Acceptance Criteria
- [x]  the Slack Service is able to be imported and used throughout vets-api to automatically send Slack notifications through any `Digital Service @ VA` webhooks
