### ISSUE TITLE
Move PgHero query stat capture and cleanup jobs to K8s

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#34520]
## Issue Description
We most likely still want to have have some sort of historical query stats for PgHero. By removing pghero from vets-api, we will no longer have the historical query stat OR cleanup jobs running on a schedule via Sidekiq. https://github.com/department-of-veterans-affairs/vets-api/pull/8757/files.

Additionally, we will want the cleanup job that runs daily to clean up old historical query stat data. 

Since PgHero is now running as it's own K8s app, we most likely want to move the capture and cleanup over unless we are ok with only seeing one day of query stats. If we want to run the jobs with our current K8s offering, we will need access to Sidekiq to run these jobs on a daily schedule OR we could find a custom solution to allow these jobs to run some other way

---
## Tasks
- [x] Figure out if we want query stats greater than 24 hours
- [ ] If so, figure out how to integrate the capture and cleanup jobs into our PgHero K8s offering
- [ ] Should we integrate Sidekiq w/ our PgHero offering or just set up a cronjob  job to run these jobs on a schedule via a rake task?
- [ ] Capture historical space stats as seen in the [docs](https://github.com/ankane/pghero/blob/master/guides/Rails.md#historical-space-stats)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
See [docker solution here](https://github.com/ankane/pghero/blob/master/guides/Docker.md#historical-query-stats)

**Comment by LindseySaari** [comment]
PR to add these two jobs via the K8s CronJob resource here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/249

**Comment by LindseySaari** [comment]
PR for the Staging, Sandbox and Prod envs https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/250

**Comment by LindseySaari** [comment]
PR to create the space stat related table in postgres here: https://github.com/department-of-veterans-affairs/vets-api/pull/8799

**Comment by LindseySaari** [comment]
[Space stats CronJob(s) for Staging, Sandbox and Prod](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/262)
