### ISSUE TITLE
[Design] Content/Accessibility Review of Editing Demographics and Next of Kin

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34525]
# Description: 
A complete draft of editing demographics and next of kin information within the pre-check-in experience was completed within ticket #34087. The designs were not reviewed with content and accessibility. During 34087, it was determined that we do not know what fields are required when editing next of kin. We need to more information about the required fields.

# Tasks:
- [x] Review the following [wireframes](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/5BCAB931-5EBD-4208-BDA4-592B768DE26F) with accessibility
- [x] Review the wireframes with content
- [ ] Look into what fields are actually required when editing next of kin.
- [x] Incorporate any feedback into the editing wireframes

# Acceptance Criteria
- [x] Review updates with product and UX
- [x] Share updates with engineering

**Comment by kristenmcconnell** [comment]
Since next of kin is out of scope for now, let's close this ticket.
