### ISSUE TITLE
[Design] Update Mailing/Home Addresses are the Same Pattern

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34526]
# Description:
We made the decision to utilize the same pattern that profile is currently using for ["your mailing address and home address are the same."](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/m1yqZxg) Profile is actively improving this design and has a user study planned for the first week in January 2022. Based upon profile's findings, we should revisit this pattern and improve it. 

# Tasks:
- [ ] Meet with Liz Lantz and review profile's research findings
- [ ] Decide how to improve this pattern for check-in
- [ ] Update wireframes in Sketch with the new design

# Acceptance Criteria:
- [ ] Review the new pattern with accessibility
- [ ] Review the new pattern with content
- [ ] Review the new pattern with product and check-in UX team
