### ISSUE TITLE
Midpoint Review [Authenticated Experience, Payment Information]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34549]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md)
- [x] [Finalized design prototype or mockup](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-conversation-guide.md)

### Content artifacts 

- [x] Content brief (if applicable) and your product’s content source of truth 

- ["Sketch File"](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=u5ad49c107baa41137f271007)

- [x] Github [ticket #34015 submitted to Content for review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34015)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [x] [Link to test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3308&group_order=asc&display_deleted_cases=0) (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by allison0034** [comment]
This is confirmed for 1/11/22 at 11am ET

**Comment by andaleliz** [comment]
@allison0034 Tressa is leaving the contract a few days 😢  and I'll be taking over for this work and welcome early feedback. Thanks in advance!

**Comment by hdjustice** [comment]
@allison0034 That is my doing.  I missed adding the Mural board, which is a bit more narrowed down.  Also, we have ticket #34621 for the On-Site Notifications Midpoint, if you would rather keep the feedback in one place.

**Comment by ajakabcin** [comment]
Closing - all reported issues/findings are closed
