### ISSUE TITLE
[PM] On-site Notification: Determine the QA/testing strategy to trigger the notification on My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34543]
## Background

MVP - The on-site notification will only appear when a new debt notice has been sent to the veteran through VA Notify (This is for a new debt incurred by Veteran. Will not show for any other notices sent to veteran).  When VA Notify sends a message to the veteran, they should also communicate to My VA that the notice has gone out to that person.  My VA will receive this information, and display a notification on the My VA dashboard when that specific user logs in and visits the My VA page.

We need to coordinate this triggering of the notification between the Debt Resolution team, VA Notify and My VA.

![image](https://user-images.githubusercontent.com/92328831/161136058-4b9ca2ad-6d47-4d04-bdae-fd0e78b685eb.png)

**Questions we need answered for QA strategy:**
1. When will our work be done?
2. When will VA Notify's work be done?
3. Does VANotify need to be part of this? If so, who on their team should participate?
4. Does Tze need to be part of this? If so, what does he need to do? Or can he just take a look at things once the notification has already been sent?
5. What use cases do we need to test (single notification, multiple notifications, etc)? We'll want this so we can make sure the backend team sends us exactly what they need.

(POC on VA Notify - Melanie Jones)

## Tasks
- [x] ~Meet with Leah, Denise and Beverly/PM to outline a testing strategy (scheduled for 4/20)~
- [x] Get answers on questions outlined above (coordinate with Melanie on VA Notify team where needed) and document in github (document started [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/qa/onsite-notifications-qa-strategy.md))
- [x] Document strategy/plan for how we'll test (see above)
- [ ] Coordinate with DMC team on QA strategy

## Acceptance Criteria
- [ ] A clear understanding of how the testing (QA and UAT) will be completed and timeline will be outlined and shared.

**Comment by hdjustice** [comment]
@Samara-Strauss Maria pinged me yesterday that she did not feel comfortable discussing this yet, since they do not have the bandwidth to dig into it.  I plan to put this ticket into the next sprint 65, and keep working with VA Notify on narrowing down the timeline and getting this strategy in place.

**Comment by Samara-Strauss** [comment]
@hdjustice thanks for letting me know! Yes, we can push this down the road as needed depending on VANotify bandwidth.

**Comment by ajakabcin** [comment]
Moving to next sprint

**Comment by hdjustice** [comment]
My notes from our first meeting with VA Notify and Debt Resolution team:

## Apr 20, 2022 - My VA Onsite Notification - QA/UAT Strategy
     Attendees: Heather, AJ, Denise, Riley, Kyle, Jake, Zack, Samara, Em, Taylor, Angela

#### Notes:
- Debt  Management Center (DMC) API triggers notification, not the Debt Resolution team
     - Debt team receives data, and does not send trigger
     - VA Notify sends notifications/email 
     - My VA would be dependent on Template ID for new debt
     - VA Notify confirmed that we would only want to receive Template ID for new debt
          - Other use cases are out of scope of MVP
     - How responsive are DMC folks?
          - Pretty responsive, there are 2 contacts we can use
     - **Question to ask DMC**: What is the timeframe between Debt being incurred and the notification/email being sent to the Veteran?
     - What is timeframe between letter being shown and debt showing up in VA.gov?
          - Debt updates shortly after notification is sent to Veteran (diary code/status code is changed)
     - Still pending what UAT might look like
          - Not sure how to validate in production
          - Debt team worked with Jill Anderson 
               - She has a pool of Veterans with certain types of debt
               - Might be able to leverage

#### Next Step:
- My VA team reach out to DMC contacts to discuss My VA feature and what is needed from DMC for QA efforts

#### Action Items:
- [ ] Denise will provide names of DMC contacts

**Comment by ajakabcin** [comment]
Posting the [use case doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Onsite-Notification.md) Heather shared with me here for reference as well

**Comment by ajakabcin** [comment]
Moving to next sprint - we're in communication with contacts from DMC to help us coordinate a testing plan.

**Comment by ajakabcin** [comment]
Latest from DMC team: they have prioritized this initiative for their next sprint which begins 5/25 and ends 6/8.

**Comment by Samara-Strauss** [comment]
Cross-posting from Slack. We need to figure out the following so we can get back to the DMC team with some dates and times for testing:

1. When will our work be done?
2. When will VA Notify's work be done?
3. Does VANotify need to be part of this? If so, who on their team should participate?
4. Does Tze need to be part of this? If so, what does he need to do? Or can he just take a look at things once the notification has already been sent?
5. What use cases do we need to test (single notification, multiple notifications, etc)? We'll want this so we can make sure the backend team sends us exactly what they need.

**Comment by Samara-Strauss** [comment]
[From Melanie in Slack](https://dsva.slack.com/archives/C010R6AUPHT/p1652822881309269?thread_ts=1652818448.416599&cid=C010R6AUPHT):

> Hey all! Sorry I was on a meeting. So we're wrapping up work this sprint (ending 5/27). We're pretty close to being done our engineering work and are working through internal testing. We can't do the connectivity test with your API until your engineering team whitelists the public key and finishes related security updates for that connection. Tom has that info. Do you know when you're targeting that for completion?

>Our QA person is [@Jake Uhteg](https://dsva.slack.com/team/U03A85BL3BL) so I'd love to loop him into those E2E testing conversations, which I would join as well.

> I think we could start talking through the test plan over the next week and then target integrated testing to begin in Staging early June.

**Comment by ajakabcin** [comment]
Documenting questions, points of contact, timelines, etc in [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/qa/onsite-notifications-qa-strategy.md)
cc @Samara-Strauss  @ericasauv09

**Comment by Samara-Strauss** [comment]
**Update from today's VANotify sync**

- Taylor is done with the FE work, though we can't validate it yet without the backend pieces in place. We don't normally do this, but given the circumstances, we'll have to validate his work through QA.
- Tom is done with his piece of the backend work, and he's coordinating with devops on a ticket that needs to happen for the backend to be officially done.
- VANotify is wrapping up their work this week. They said we should be able to do some testing before our QA with DMC in order to make sure the backend is looking good and VA.gov is able to receive information from them. Assuming everyone is ready, our teams will coordinate next week on this.
- We are targeting our sprint starting 6/15 for the end-to-end QA with DMC, VANotify, and VA.gov.

**Comment by ajakabcin** [comment]
Update from today's meeting with Tze: we would prefer to set up a series of test users (~12) with debt notifications so that he can complete QA on the feature without needing to bother the DMC team to reset users/perform QA testing live. We'll need to run this by DMC and see how this will work with their processes. Next step will be to schedule a meeting with VA Notify and DMC folks just to get on the same page.

**Comment by ajakabcin** [comment]
This will continue into next sprint - as noted above next step is to set up a convo with us, VA Notify and DMC.

**Comment by Samara-Strauss** [comment]
### Setting a date for testing

We are just about ready to set a QA date. As far as I know, the following is true:

- Frontend is done.
- Backend is done.
- VANotify has completed their work.
- The backend team (DMC) is on board for testing. They needs "file number" (SSN) for staging users to add new debts.
- Tze is on board. He needs notifications added for 13 users total (12 with 1; one with multiple).

The following is still outstanding:

- VANotify needs to complete some backend testing. They were going to do this yesterday, but there was a delay due to some MPI issues [Slack](https://dsva.slack.com/archives/C010R6AUPHT/p1654279285783319?thread_ts=1654100949.743599&cid=C010R6AUPHT).

Once VANotify completes testing and determines everything is looking good as far as they can tell, I think we are good to set a date for testing.

### Testing prep

We need to:

- Figure out which users we want to use for testing, and [document them here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-onsite-notification.md).
- Set date and send invitation for testing.
- Share test users with DMC the night before. **We need to make it clear that they should not add debts for these users until we are on the call**.

### Testing protocol

- Send test users to DMC.
- Have them add debts for one user.
- Confirm the debt notification shows up for that user.
  - If not, troubleshoot as needed.
- If debt is successfully added for the one user, have them add debts for other users.
- Confirm the debt notifications show up.

No other testing needs to be done while we are on the call. Tze can complete QA any time after the end-to-end testing.

**Comment by Samara-Strauss** [comment]
We've set 6/28 @ 3:30 ET for end-to-end testing. However, there is a chance we may not need to old the call. This is the current plan:

- Once VANotify has completed their backend testing, we will ask DMC to add the test data for a subset of staging users. If we can then validate that on-site notifications showed up in those accounts as expected, there is no need to hold an e2e call, and we can cancel it.
- However, if we ask DMC to add debts and no on-site notification shows up, we should hold a call to troubleshoot the issue.

I'm closing this since I don't think there are any more planning-related tasks.

**Comment by ajakabcin** [comment]
Updated our notes doc in GH with the schedule as well
