### ISSUE TITLE
[FE] My VA - Payment Information and On-site Notification: Begin build for prototype of the new Benefit Payments and Debts section and Notification

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34545]
## Background

For a clear, accurate experience, we would like to build a prototype in the staging environment to be used during usability testing with veterans.  This will help us obtain feedback about the functionality and expectations, without too many limitations.

## Reference Materials

- [Sketch File](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=408509fb-10d1-4b2f-a6f4-2e2ba827f257)
- Test Cases
     - [Payment Info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-PaymentInfo.md)
     - [On-site Notification](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Onsite-Notification.md)
- Product Outline
     - [Payment Info](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
     - [On-Site Notification](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications)
- [Research Plan (combined)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)

## Tasks

- [ ] Build a working prototype for new "Benefit payments and debts" section on My VA, so that it can be used during usability testing
- [ ] Build a working prototype for a new On-site Notification for debt updates on My VA, so that it can be used during usability testing

## Acceptance Criteria

- [ ] A working prototype of the new Benefit payments and debts section will appear on My VA
- [ ] A working prototype of the On-site Notification for debt updates will appear on My VA

**Comment by hdjustice** [comment]
Updated to current sprint (sprint 63) as unplanned work

**Comment by tmitchellgcio** [comment]
![Screenshot 2021-12-29 111057.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/01c81475-b0c3-4071-941d-b6fd7fa795d6)
![Screenshot 2021-12-29 111120.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/266dc880-f949-436c-831f-f72da205cea9)

**Comment by hdjustice** [comment]
Prototype is complete.  Usability testing will begin tomorrow.  Any changes that result from testing and decided as must-have for MVP will be addressed in new tickets.
