### ISSUE TITLE
Form 22-10203 STEM application: Turn off auto-decision process

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34554]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The auto-decision process, which was released earlier this year, appears to be incorrectly auto-denying applications. Of those that have been auto-denied, up to 50% have been determined by the RPO as incorrect denials.  Therefore, the Buffalo RPO (via Kyle Pietrosanto), who processes these applications, has asked us to turn off the auto-decision process temporarily. 

Currently, AFS team has turned off the auto-denial emails so that vets are not incorrectly receiving a denial email, but the process continues to function. 

---
## Tasks
- [ ] Determine how to turn the process off in the code
- [ ] Turn it off
- [ ] Notify EDU/BUFF RPO that this has been done.

## Acceptance Criteria
- [ ] Auto-decision process does not initiate.
- [ ] All STEM applications are sent to the RPO for manual processing until solution has been implemented. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AdamFreemer** [comment]
PR for testing in Staging: https://github.com/department-of-veterans-affairs/vets-api/pull/8805/files

**Comment by mrblanco1** [comment]
This was released to prod 1/05/2022.
