### ISSUE TITLE
CC DOMO Documentation

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#34553]
## Issue Description
Document the various data sources and dashboard currently available to the VSP Contact Center team. The goal is share this document with teams who are interested in what data can be made available and to document and prioritize next steps.

---
## Tasks
- [x] Create a confluence document
- [x] Review with Jason
- [x] Add to Contact Center confluence space

## Acceptance Criteria
- [ ] The document contains links to all DOMO dashboards
- [ ] The document contains descriptions of what data sources and fields are currently housed in DOMO
- [ ] The document outlines proposed next steps for DOMO reporting
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 [here's the document I created for DOMO](https://vfs.atlassian.net/wiki/spaces/~403774134/pages/2015133780/Contact+Center+DOMO+Documentation). I'll also review with Chloe when I return next week.
