### ISSUE TITLE
Form 22-10203 STEM application: Determine what is causing incorrect auto-denials 

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34555]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
AFS team needs to investigate why the auto-denay process is incorrectly denying some applications that should be processed as eligible applications. 

---
## Tasks
- [ ] Get a list of denied applicant names from Buffalo RPO
- [ ] Query the database table in TIMS to get information on the denied applications
- [ ] Determine reason for incorrect application denials

## Acceptance Criteria
- [ ] determination has been made as to the reason why some applications are being denied when the applicant should be eligible.
- [ ] Path forward to fix this issue has been determined.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AdamFreemer** [comment]
Even though we're still waiting for Kyle to return example data for the automated denial system bug investigation, there's another matter to discuss. Of the current 4 possibilities:

1. Issue is back-end automation process related (least likely)
2. Issue is back-end / front-end related (api call, etc) (more likely)
3. Issue is front-end (more likely)
4. There is no issue, it's disgruntled users not understanding the process and/or incorrect evaluation of the problem (more likely)

The bottom line is: if it's 2-4, just having the back-end data isn't really going to help us figure out what the problem is. What we really needed from Kyle was actual user experience data (what they clicked on for options, was there errors, issues during the process, etc) which he probably can't provide.

QA set up testing I believe for when we shut off the emailer. I'm not sure if it's automated, but I think debugging the problem requires having the problem manifest itself, whatever it is, in some sort of testing process, if that's possible (again, I'm still of the opinion there might not be a problem at all). I know the focus right now is tomorrow, but if we could maybe have a discussion on this soon it would be helpful.

**Comment by AdamFreemer** [comment]
This PR sets production to 'offline' for auto-denial. Currently active in Stage only. https://github.com/department-of-veterans-affairs/vets-api/pull/8817

**Comment by AdamFreemer** [comment]
[1/7/22 11:18 AM] Freemer, Adam [Seneca Resources, LLP]
Blanco, Abe - Mann, Dwight So I think the first step in evaluating the automation tool denial issue is as follows:1. Currently the emailer job is set to disabled. Since we've confirmed via the spool file that there are no new denials I believe, we can safely re-active the emailer job (via code or the sidekiq console, point of discussion Shah, M. C. [Seneca Resources, LLP]). 2. QA comes up with perhaps a testing strategy of perhaps a couple dozen positive (should not be denied) and negative (should be denied) user accounts with emails we can use to confirm denial letters, and fake social security numbers (and names) to be able to trace back on staging for later evaluation if need be.3. After running these tests, we will then either have some false denials to then evaluate further on Staging, or if there are no errors, have data to go back to the VA with making the case this might not be a bug.

[1/7/22 11:18 AM] Freemer, Adam 
So I think the first step in evaluating the automation tool denial issue is as follows:

1. Currently the emailer job is set to disabled. Since we've confirmed via the spool file that there are no new denials I believe, we can safely re-active the emailer job (via code or the sidekiq console, point of discussion Shah, M. C. [Seneca Resources, LLP]). 

2. QA comes up with perhaps a testing strategy of perhaps a couple dozen positive (should not be denied) and negative (should be denied) user accounts with emails we can use to confirm denial letters, and fake social security numbers (and names) to be able to trace back on staging for later evaluation if need be.

3. After running these tests, we will then either have some false denials to then evaluate further on Staging, or if there are no errors, have data to go back to the VA with making the case this might not be a bug.

**Comment by AdamFreemer** [comment]
Created a back-end logging PR to be able to evaluate data being returned (or possibly not being returned) from EVSS for the 10203 auto-denial system. https://github.com/department-of-veterans-affairs/vets-api/pull/8918

**Comment by AdamFreemer** [comment]
The front-end api call for pre-flight evaluation of a logged in user to EVSS seems to be broken (returning 403s). There's a PR to evaluate front-end EVSS data but further analysis needs to be done on why this api call is failing. https://github.com/department-of-veterans-affairs/vets-website/pull/19963 (endpoint: `/v0/post911_gi_bill_status`)

**Comment by AdamFreemer** [comment]
To further evaluate the EVSS api call from `vets-api`, back-end logging was added with this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/8937

**Comment by mrblanco1** [comment]
Moved this ticket to the icebox since we are still trying to find out where does this logic resides. Matt Self is going to try to reach out Will (ex-BAH) to see if he recalls where does auto-denial logic outside CT is and/or who can assist us or might know.
