### ISSUE TITLE
[Design] Add confirmation checkbox to Additional Evidence Upload Screen in Claim Status Tool

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3455]
## User Story or Problem Statement
As a claimant, I need proper instruction on where I can upload evidence so I can ensure that I am providing in the proper location for review.

## Goal
- Design best way to display where a user can upload documentation, either as additional evidence to an existing, open claim, as a new disability claim or as a decision review_
- Provide user with a method of acknowledgement (checkbox?) that they understand that the Additional Evidence Upload is specific to the existing claim they have open.

## Tasks
- [x] Review design files to ensure consistency with design system
- [x] Request Content Review - tag Peggy in #3456 

## Acceptance Criteria
- [x] _Design mocked up_

## Background info
#3102 
Discussion with Paul:
- Required by law to review all documentation
- If they want to submit something, encourage the user to file another claim if needed
- If not providing evidence in support of their claim, they should file a new claim for the evidence they want to submit
- Direct them to How to Submit a Claim page or to Decision Review page

**Comment by YanaRoy** [comment]
@kevinstachura to complete Tasks @YanaRoy to complete AC

**Comment by kevinstachura** [comment]
This has been designed and sent to content team for review per #3456 - design is located here:

https://vsateams.invisionapp.com/share/S2U2NQZZ76A#/394760072_Upload_Additional_Evidence_-_Checkbox_-_Revised

Closing this ticket.
