### ISSUE TITLE
Form 22-10203 STEM application: Fix auto-denial functionality

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34557]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The auto-denial function is not working properly, per the Buffalo RPO (via Kyle Pietrosanto), so they requested that the functionality be temporarily turned off/disabled until a fix could be implemented. 
Per the investigation completed in ticket #34555, a path forward to fix this issue was determined. Therefore, this ticket is to fix the issue. 
---
## Tasks
- [ ] TBD
- [ ] TBD
- [ ] TBD

## Acceptance Criteria
- [ ] TBD
- [ ] TBD
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
