### ISSUE TITLE
[VAMC] Review and standardize all H1 Naming conventions for VAMC Campus map pages [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34578]
## Story
As a Veteran I need to have a clear understanding of what and where the VAMC campus map is viewings, so I can better navigate the buildings and campus in my health care journey

## Resources
[VAMC Page intent guide](https://salientcrgt.sharepoint.com/:w:/s/VSATeam/Ebq-Z0LhK7JLmJB-cnTKzvAByzi0F3ldKSopUJ2jPZXEEw?e=tH6CX6)

## Tasks
Review all VAMC Campus map VAMC detail pages and assure that the H1 meets the standard naming convention of the Main facility campus map.  If more than one main facility, then there should be a campus map for each related medical facility.
- [x] Review all VAMC detail pages "Campus Map"
- [x] Document all that are out of compliance and verify if url alias needs to be fixed as well.
- [x] Update H1 so that it meets compliance, report URLs that need changing so that a redirect can be submitted before changing.

## Acceptance Criteria
- [x] All non conforming pages with H1 are updated to correct naming 
- [x] List of pages and URL Alias that need adjustment is attached to this ticket or listed in VAMC Share for upcoming stories.

**Comment by ltrombley** [comment]
Task #34578 - Review and standardize all H1 Naming conventions for VAMC Campus map pages [BA] - is Complete and moved to Validate

**Comment by ltrombley** [comment]
NOTE: URL re-directs are pending - Stan G. working on getting these done.
