### ISSUE TITLE
[Research] Draft Conversation Plan - HRT Static Content Landing Page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34579]
## High Level User Story/ies
As a Veteran or VA employee, I need a way to report an incident of workplace harassment or assault which takes place at a VA facility so I can be assured that there is investigation and remediation.

[Product Outline for Reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/read-me.md)

##  Tasks 
- [x] Draft Conversation plan 
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback 
- [ ] Discuss recruiting and launch with Shane via new process in research repo
- [ ] Start collaboration with VSP (if needed)
- [ ] Work with PM to build research tickets to account for work and support

## Acceptable Criteria 
- [ ] Initial Conversation plan drafted by Jan 11 in support of recruiting efforts
- [ ] Finalize research/conversation plan by Jan 11
- [ ] Draft research plan available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
Started working on a new conversation guide but didn't get very far. Will work more tomorrow...

**Comment by cindymerrill** [comment]
Drafted rest of conversation guide, shared it with the UX team for feedback, and extracted Veteran-facing text sections into a shared Word document for Danielle to review.

**Comment by cindymerrill** [comment]
Incorporated revisions from UX team members, and then shared the updated text with Danielle to review.

**Comment by cindymerrill** [comment]
Incorporated revisions from a third UX team member, and then shared the updated text with Danielle to review. Not sure when she will have time to take a look.

**Comment by cindymerrill** [comment]
Shared draft conversation guide with @brianalloyd  and Dave so they could see how I mention VCL at the end and advise me on who from VCL to potentially reach out to. Still waiting for more feedback on wording from Danielle.

**Comment by cindymerrill** [comment]
Made a LOT more revisions per feedback from Danielle. There's just one minor revision left to confirm.

Danielle said that she wants to help connect me with the Office of Mental Health and Suicide Prevention because she recommends running the VCL content by that office, too.

**Comment by brianalloyd** [comment]
@cindymerrill what are the primary things we are trying to learn from a VCL and OMHSP link up?  I'm wondering if we can close out these tickets and create follow on tickets in support of `"finalizing"` the research and conversation guides?  Thoughts?

**Comment by cindymerrill** [comment]
The [HRT conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/conversation-guide.md) is now ready for wider review, since Danielle provided a LOT of super helpful feedback on the Veteran-facing language and protocols, which I’ve incorporated. Note the action items at the top of the document that I need help with:

- Reach out to the mental health group and Veteran Crisis Line (VCL) about how we're sharing VCL info because they’re sensitive about their info and how it’s used/presented (according to Danielle Thierry)

  - Brian/Dave can help with VCL contact

  - Danielle can help with the Office of Mental Health and Suicide Prevention

- Get an appropriate phone number for reporting harassment for the end of the session and on the poster
- Review landing page on Staging & get URL that works on desktop and mobile

**Comment by cindymerrill** [comment]
@brianalloyd We want to get feedback from VCL and from OMHSP on how we're sharing VCL info with Veterans during our research sessions. There's wording about VCL in the conversation guide in 2 sections: 

1. Protocol for Recognizing & Handling Trauma-Triggering 
2. Thank You and Closing

I'm fine with you closing out these 2 tickets and creating new ones for finalizing them AND launching recruiting (which are unfinished tasks in both tickets).

**Comment by brianalloyd** [comment]
Thanks @cindymerrill this is exactly what I was thinking, glad we are aligned.  Thanks for the update, we'll get you a contact for VCL when I'm back in the office. Free free to reach out to Dave directly in my absence.

**Comment by cindymerrill** [comment]
@brianalloyd I think I'll wait until you get back and after Dave talks with the stakeholders, in case anything about our approach needs to change.

**Comment by brianalloyd** [comment]
Connecting this to the finalization ticket created as a follow on #36366, close out this ticket based on completion of the draft conversation guide.
