### ISSUE TITLE
Form 526 reduction - task list approach

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34575]
## Issue Description
Continue work on 526 user experience/form reduction & enhancement

---
## Tasks
- [x] Define user journey

## Acceptance Criteria
- [x] Artifacts completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
@chrvalla and I have put together a document outlining the user journey (and showing what it might look like if we add the task list pattern). You can see the document here:

https://app.mural.co/t/vsa8243/m/vsa8243/1641488746534/1608f3de219f97b54f31ba352abca2074adcfb4c?sender=kstachura1551
