### ISSUE TITLE
[VAMC]  Reassociate VAMC Detail pages to correct Parent Menu items both on page and in Menu [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34584]
## Story
As a Veteran I need to be able to find the additional programs, research, internships, and other VAMC detail pages under the correct Parent menu, so I can better understand the additional information and pages that relate to my local VAMC.

## Resources
TBD

## Task
Review all the pages that may have been saved under the incorrect Menu Parent prior to the hardening of the menu drop down.  Move pages to either, Programs, Research Doing business with us, or Internship and Fellowship menu parents.
- [x] Locate VAMC detail pages that are not under the correct parent menu and document.
- [ ] Request redirects for what the new pages will  be once they are moved under the correct Menu item (Document)
- [ ] Once redirect is submitted, move the pages to the new URL
- [ ] Update Menu to reflect the same if they do not correct automatically

## Acceptance Criteria
- [x] Document all pages that will need to move, add what the new URL alias will be for submission to IA for redirect to be issued.
- [ ] Once redirect is in place, return and move pages to new URL and update Menu.

**Comment by ltrombley** [comment]
Task #34584 - Re-associate VAMC Detail pages to correct Parent Menu items both on page and in Menu [BA] - Part 1 is complete:   Locate VAMC detail pages that are not under the correct parent menu and document.
