### ISSUE TITLE
Phase 3 - Added question PTSD flow Form 526

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#34583]
## Issue Description
Explore how we can improve the Veteran experience with our online forms

---
## Tasks
- [x] Design pages where the veteran is asked about "fear of hostile military or terrorist activity".
- [ ] Finish pages in Sketch, send out for approval. (Does one page require the whole review process?)

## Acceptance Criteria
- [ ] Documented form improvement research and recommendations. Presentation and formal documentation
