### ISSUE TITLE
[VAMC]  Review Lovell Federal health care - DoD pages with Facillities team for design [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34597]
## Story
As a active DoD and Veteran I need to understand my choices on the Lovell Federal health care system, so I better know my health care choices.

## Tasks
- [x] Review DoD shared pages and details with Facilities team
- [x] Discuss Input from VAMC
- [x] Discuss notes from DoD and VAMC

## Acceptance Criteria
- [ ] Meeting with Facilities and support design and research
