### ISSUE TITLE
[VAMC] Test Teams Forum/Blog with VHA resource [VAMC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34595]
## Story 
As a VAMC editor, I need to be able to reach out to a Community of practice via a Teams Forum, so I can get feedback from my peers and VHA regarding any issues I am experiencing.

## Tasks
Set up Teams Meeting and set up meeting as Forum discussion site:
- [ ] Work with VHA Digital media to set up Communities of Practice via Teams for 2022
- [ ] Load all tools and documents needed so they can be shared
- [ ] Review community with VHA DM and start responding via posts.

## Acceptance Criteria
* VHA DM assigns at least one resource to set up the Teams
* Teams meeting is set up for Thursdays every week
* Files are loaded to Teams and
