### ISSUE TITLE
[Content:] Update Higher-Level Review static landing page

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#3460]
## User Story or Problem Statement
Higher-Level Review static landing page needs to be updated to support launch of Higher-Level Review form

link to WIP invision mockup

https://vsateams.invisionapp.com/share/5RUP8V2TSHD#/screens

## Acceptance Criteria
- [ ] Add green CTA button to take users to the HLR form
- [ ] Add left nav to page (to be approved by @mnorthuis) **[EDIT: @Karak888 pls break out left nav work as a separate ticket per call, to be worked on after Kevin S's user research learnings; also note in that ticket that the nav would need to be added to ALL decision review pages, not just this one. / jen]**
- [ ] Additional content updates to address that only pension and compensation claims can file for HLR online (all other claims still need to be filed via mail, fax, in person)
- [ ] Heroku preview shared with SMEs and changes factually validated and approved (iterate if needed)
- [ ] Reviewed by Peggy Gannon in Platform
- [ ] Copy edited by Randi Hecht
- [ ] Email SMEs when change live

Related widget ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4139

Related nav ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4141

**Comment by peggygannon** [comment]
adding @YanaRoy and @Mottie for visibility

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - here is the HLR static landing page tool entry/access copy updates that were used in Carola and Steve's tool POC. 

[https://app.zenhub.com/files/133843125/dff04895-d5d3-462f-b535-9ee1da7af940/download](https://app.zenhub.com/files/133843125/dff04895-d5d3-462f-b535-9ee1da7af940/download)

Per call: This page is not in Drupal but Github.  For this ticket, please focus on just adding the tool - don't want to change too much content or layout here - AMA content extremely sensitive. Let's keep things simple and surgical. 

When you're ready to share the Heroku preview with stakeholders, let's sync. 

Removing Peggy assignment but def should loop her in later  for final review, so unauth and auth content align.

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - RE the accordions of addresses in this mockup: 

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/385333421

We can't add accordions inside subway maps (content anomaly that's already there, so let's avoid adding MORE anomalies). Suggestion: pull out address info from subway and make it its own H3 section right after subway.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva I am making changes in GitHub, but thought it would be helpful to shoot you the attached Word doc. I used track changes so you can quickly see what I'm changing. 
[hlr-static-content-page_lw_updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3989708/hlr-static-content-page_lw_updates.docx)

**Comment by lwalsh617** [comment]
@jenniferlee-dsva -- I made the changes in GH with help from @RLHecht. 
@RLHecht -- Questions for you:
How do you force a line break in Markdown? For example, I noticed that there was no line break between "4-5 months" and "VA's goal...," so keep trying to add one by putting in p'graph return to no avail. 
Also, I risked cutting an pasting all the addresses. Goal is to get that addresses accordion out of the subway map and below it instead. I don't seem to have screwed anything up, but wanted to flag it! Thank you!
@kelsonic - I dropped in the copy for the react widget. Look under H2 "How do I request a Higher-Level Review" and then H3 "Online".  You'll see the following widget copy:
**Please sign in to request a Higher-Level Review online**
Try signing in with your DS Logon, My HealtheVet, or ID.me account. If you don't have any of those accounts, you can create one.
Sign in or create an account >
Thank you, Kelson!
Page URL:  https://github.com/department-of-veterans-affairs/vagov-content/blob/wip-decision-reviews-hlr/pages/decision-reviews/higher-level-review.md
Branch I created: wip-decision-reviews-HLR

**Comment by jenniferlee-dsva** [comment]
Hi @lwalsh617 - Uploading your copy doc with a few minor notes (promise - minor). Should have looked at the gh instance instead? 
[hlr-static-content-page_lw_updates-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3989865/hlr-static-content-page_lw_updates-jl.docx)

**Comment by lwalsh617** [comment]
Hi @jenniferlee-dsva - I made your edits. Here's the Heroku link:  https://vagov-content-pr-610.herokuapp.com/decision-reviews/higher-level-review/

**Comment by Mottie** [comment]
> How do you force a line break in Markdown?

You can add HTML:

* Add one or more `<br/>` to force the line break,
* or wrap the content inside of a set of paragraph tags (`<p>...</p>`)

**Comment by jenniferlee-dsva** [comment]
I'm closing this duplicate ticket. It keeps getting confused with/for #4139. 
FYSA @MickinSahni @peggygannon @lwalsh617 

See and/or comment in #4139 going forward.
