### ISSUE TITLE
Add the Authenticated View to the Prototype (Rep)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34619]
## Background
We need to include the authenticated version, which will be mostly a mirror.  There isn't a great way to switch gears in the middle of the form.

## Considerations
[Prototype](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145482056/simulate/sitemap)

## Tasks
- [x] Add the authenticated view to the prototype
- [ ] TBD, if needed

## Acceptance Criteria
- [x] The prototype has an authenticated version, link shared in this ticket's comments

**Comment by sporeboy** [comment]
Worked on authenticated flow for find/appoint rep. There are several questions currently unresolved in the prototype:

- If this will be all one form (Find AND Appoint) should H1 be the same throughout?
- (If this will be all one form) Can we show/hide the form number in the find section?
- Stepper reflects all steps; can we make increased steps conditional on continuing with "Continuing" with filling-out PDF?
- Can we dynamically indicate which of the two forms was filled-out on the confirmation page (based on rep-type chosen)?

Note: Content will undoubtedly change (Likely minor revisions)

**Comment by sporeboy** [comment]
The prototype now has two flows: authenticated and unauth'd. Functionality is click-through only at this point. Form elements are interactive but not rigged.

Another question regarding form system:
- We will need to show the sign-in widget (current thinking is below the subway map)

**Comment by sporeboy** [comment]
Prototype is set with click-through functionality for both auth'd and unauth'd flows. Here are consolidated notes/questions:

**Technical (form) questions**
- If this will be all one form (Find AND Appoint) should H1 be the same throughout? Can we change the H1 at the mid-point?
- (If this will be all one form) Can we show/hide the form number in the find section? So the user would *not* see a form number in the search section?
- We'll need to include the sign-in widget on the intro
- Stepper reflects all steps; can we make increased steps conditional on continuing with "Continuing" with filling-out PDF?
- Can we dynamically indicate which of the two forms was filled-out on the confirmation page (based on rep-type chosen)?

**Design**
- Should "selecting" a card be an action link?
- We have boilerplate copy about wrong info, and address changes; need to be sure these are the current solution
- Need to determine the pattern for displaying the selected rep info in the review
- We need to confirm the pattern for downloading the partial PDF
- Review accordions are only stubbed--they either don't work or they're inaccurate

**Content**
- We may need to provide clarification as to the steps in the subway map
- Might need to let users know "exact" spelling will matter
- We may need to let the user know that they *are* authorizing record disclosure along with the opt-in on protected records
