### ISSUE TITLE
[VAMC] Develop VAMC report of pages and nodes that are not being used as assumed and categorize them [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34611]
## Story
As a VAMC editor I need to know the correct usage of the VAMC pages, so I can better manage the intent of pages.

## Task
- [ ] Review all pages that are not being utilized correctly
- [ ] Categorize causes of the miss use
- [ ] Provide full report of all the categories and URL examples

## Acceptance Criteria
* Artifact in report format is provided to VHA DM
