### ISSUE TITLE
Fill in Appoint Rep with Fields

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34624]
## Background
Now that the pages are in place, we want to complete the fields for the form system for this feature

## Considerations
- link to prototype: https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145482056/simulate/sitemap

## Tasks
- [ ] Add content to the remaining pages in the 21-22/a
- [ ] Add fields to the remaining pages in the 21-22/a

## Acceptance Criteria
- [ ] Content from the mockups are in place
- [ ] Fields from the mockups are in place

**Comment by jason-gcio** [comment]
dupe

**Comment by jason-gcio** [comment]
duplicate
