### ISSUE TITLE
Follow up on IA Things

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34623]
## Background
Need responses from a few different folks

## Tasks
- [x] Follow up with Mikki, set up a time to chat if possible
- [x] Follow up with Nathan Kroes, set up a time to chat if possible (e2e check in)
- [x] Follow up with Melissa Rebstock, set up a time to chat if possible (e2e check in)

## Acceptance Criteria
- [x] Start an email with Mikki, set up a time to chat if possible
- [ ] Start an email with Nathan Kroes, set up a time to chat if possible
- [x] Start an email with Melissa Rebstock, set up a time to chat if possible

**Comment by candy-gcio** [comment]
- Met with Mikki on Thursday, Jan 6
- Met with Nathan on Friday, Jan 7
- Meeting with Melissa is scheduled for Wednesday, Jan 12
