### ISSUE TITLE
Address Error Handling for COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34627]
### Background
For statuses that might not exist or instances of client side failure, or server side failures, we need to ensure we have error handling in place so that a Veteran can see when errors occur to try again later.

### Considerations
- FE will do placeholders for now until updated content is in place
- [4XX errors](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/338e991f-d104-4bf4-b040-ced7f18617a0/)
- [5XX errors](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/b605cd69-728a-4b12-988b-558dc734375c/)
- Status is checked on form intro page
- Status is checked on MyCOE screen
- Upload errors may occur on MyCOE upload screen
- Documents list may produce errors
- eligibility determination page (??)

### Tasks
- [x] Map-out user-displayed error instances in product flow diagrams
- [x] List error messages for instances where there are issues client side (4XX errors)
- [x] List error messages for instances where there are issues server side (5XX errors)

## Acceptance Criteria
- [x] Prototype shows client-side error states 
- [x] Prototype shows server-side error states

**Comment by sporeboy** [comment]
I have client- and server-side error states for:
- Form intro screen
- Your COE screen
- Your COE letters

Basic error patterns are used for the Your COE uploader.

Text is preliminary and subject to revision. [Link to UXPin error section](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/146308490)

**Comment by sporeboy** [comment]
There is a "no alert" option for the form intro in the case of a 400-error... This is kind of a "low-heat" option vs, the alert box.

{Link to UXPin prototype screen](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/146308671)

**Comment by jason-gcio** [comment]
@jerekshoe & @cohnjesse - FYA
