### ISSUE TITLE
Midpoint Review [Authenticated Experience, On-site Notifications]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34621]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [x] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/README.md)
- [x] Finalized design prototype or mockup [Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=30b328dd-61fa-4e9c-a615-80a4db99566d) and [Sketch File](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/payment-information-conversation-guide.md)

### Content artifacts 

- [x] Content brief (if applicable) and your product’s content source of truth 

- ["Sketch File"](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
- [Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=u5ad49c107baa41137f271007)

- [x] Github [ticket #34015 submitted to Content for review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34015)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [x] [Link to test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=3308&group_order=asc&display_deleted_cases=0) (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Confirmed that this Midpoint Review is scheduled for 1/14 at 11:30am ET

**Comment by shiragoodman** [comment]
Review has been rescheduled for 1/21 at 11:30am ET

**Comment by allison0034** [comment]
@andaleliz I am not seeing any UI issues. I will do a more thorough review next week but no early design feedback : )

**Comment by joshkimux** [comment]
No **must** accessibility feedback from my end-- mostly just design to development considerations.

## Should
- Start thinking ahead of time of a colorblind context for these. What are other ways to quickly show importance to someone scanning a page that doesn't rely on color?

<img width="946" alt="Screen Shot 2022-01-19 at 12 37 41 PM" src="https://user-images.githubusercontent.com/14154792/150184626-a37fdb1d-6822-44eb-9a77-02a4bac5e863.png">

## Design to dev considerations
- Alt text for the "X" icon in dismissable messages

- Alt text for the "!" icon in dismissable messages (e.g. should it be "Important" vs. "Alert"-- might need some content advice here). I'd recommend thinking ahead of time how these might be reworded based on how important they are

- `sr-only` (screen reader only) headings. Without these headings, screen reader user may interpret these actions as belonging to "Next appointment" instead

<img width="781" alt="Screen Shot 2022-01-19 at 11 31 05 AM" src="https://user-images.githubusercontent.com/14154792/150174047-fe1e16ed-c357-42db-9d8f-b9b2991515a1.png">

- `aria-label` s for links without a visible purpose/target. 

<img width="742" alt="Screen Shot 2022-01-19 at 11 38 24 AM" src="https://user-images.githubusercontent.com/14154792/150174910-93323008-af08-4c6b-a6e1-044d2c8758a7.png">

- Opportunity to reduce the length of some of the headings that include form names by using `aria-describedby` to link the text _above_ the heading directly to the heading itself

<img width="556" alt="Screen Shot 2022-01-19 at 11 36 14 AM" src="https://user-images.githubusercontent.com/14154792/150174417-6def2743-8d3f-4cfa-9724-080e3812b7ce.png">

**Comment by ddzz** [comment]
Thanks for using TestRail! No QA feedback at this point since the test cases are still a work in progress.

**Comment by andaleliz** [comment]
@joshkimux thanks for the feedback! I've updated the icons in the specs in [the Sketch file](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6/v/9Zdzwp/a/rbyv1Dd/r/YvRrqM) to provide another cue for the color we're trying to communicate with the significance. I'm still noodling over other ideas but I think this would be a step in the right direction. What do you think?

**Comment by joshkimux** [comment]
@andaleliz Definitely a step in the right direction!

**Comment by hdjustice** [comment]
@joshkimux @Saraharaba8 - FYI Tickets created per feedback received.
#36182 - Alert message box designs considerations
#36216 - Adding Alt Text
#34432 - Adding sr-only headers
#36218 - Adding Aria labels

As we work through these, we will share and ensure we are on the right track.  Please let us know if there are any questions or additional comments.  Thanks!

**Comment by hdjustice** [comment]
Commenting here for historical purposes - we have only 1 of the 4 tickets remaining open (alt text for the Onsite Notification alert).

**Comment by tmitchellgcio** [comment]
@joshkimux Hello. I'm realizing we can't add alt-text for the icons or dismissible close icon. Those are all handled by the VA Alert component. The close icon in the new alert component does have an aria-label of "Close Notification" which should suffice for that, however the icons before each do not have anything for screen readers. In fact, the icons themselves are using aria-hidden so they don't actually even show up for the screen readers. All of these alerts are using the new alert system va-alert. I don't think they were modifiable in the old system either but maybe the new alert system implemented these aria changes?

**Comment by joshkimux** [comment]
Update: @tmitchellgcio and I synced on this and talked about exploring `sr-only` `spans` as an alternative 😄
