### ISSUE TITLE
Staging Review [Public Websites - Outreach & Events MVP]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34622]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [X]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic (if no feedback, please comment stating that). 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] [Staging URL](https://staging.va.gov/outreach-and-events/events/)

- [X] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
 
  

- [X] [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/Artifacts/Release%20Plan%20O&E%20Enhancements.md)

 

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [X] Product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=3088)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/2639) in TestRail with test execution logs [interim\*] 
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/289) 
- [x] [Summary(Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/290) [interim\*]
\*Recurring events case is not QA-ready yet, pending Drupal-environment/API-data setup.

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [ ] List of known issues

•	Issue 1: [FE] Past events ordering need to match production logic (reverse chronological order) #34766

•	Issue 2: [FE] Custom Date Range Filter not rendering results [BUG] #34767

•	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Confirming that the meeting is scheduled for 1/13 at 2:00pm ET

**Comment by jimuhh** [comment]
Hi @brianalloyd Is there a staging URL available for this? Thanks!

**Comment by brianalloyd** [comment]
Yes, staging.va.gov/outreach-and-events/events/

**Comment by jimuhh** [comment]
Thanks @brianalloyd!

**Comment by jimuhh** [comment]
@brianalloyd  -- Oh, would you also be able to link the **"Staging URL"** checkbox up under "Artifacts" to that site? Thanks!

**Comment by AngelaFowler82** [comment]
Are we reviewing the individual linked events, or just the page on which they're listed?

**Comment by brianalloyd** [comment]
@AngelaFowler82 MVP is to support filtering capabilities (added feature) and recurring events.  Let me know if that helps with the review question.

**Comment by AngelaFowler82** [comment]
It does, thanks. When I look at the upcoming events, there is an event scheduled for today, 1/5. When I filter for 1/5 it shows no results. Is it still looking at 2021?

**Comment by brianalloyd** [comment]
@AngelaFowler82 a bug has been identified with this functionality during QA testing #34762 we are actively trying to resolve the issue.

**Comment by AngelaFowler82** [comment]
Awesome. What should I expect to see in regard to recurring events? It may be lack of coffee, but I don’t see anything.

**Comment by brianalloyd** [comment]
@AngelaFowler82 probably not for lack of coffee, we're actually waiting on CMS to import more recurring events into "tugboat" environment so we can test, this is expected to happen today and will follow up once we have data set for testing.

**Comment by tlei123** [comment]
@pjhill @ddzz , all MVP test-runs EXCEPT Recurring events are now completed, and QA-artifact links updated above in main description.

Once I've completed Recurring events test-runs, I'll update the Summary (Defects) report link up there.

cc @brianalloyd @kelsonic

**Comment by mnorthuis** [comment]
@brianalloyd Just a heads up that the breadcrumb is not correct once you leave the main outreach and events page - the home link no longer appears.  This will need to be corrected.

**Comment by brianalloyd** [comment]
Thanks @tlei123 for the update, understand, working with CMS to get the recurring events on tugboat so we can test accordingly.  I'll follow up on that this AM.

**Comment by brianalloyd** [comment]
@mnorthuis thanks for the details on the breadcrumb issue, that was unknown and am creating a ticket to address the issue now.

**Comment by shiragoodman** [comment]
The staging Review has been rescheduled to Thursday 1/13 at 1:30 pm ET

**Comment by brianalloyd** [comment]
@mnorthuis just wanted to link the breadcrumb issue that we resolved [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34931) for tracking.

**Comment by tlei123** [comment]
@ddzz , Recurring-events test-runs completed on Drupal-dev [Mac Chrome & Firefox only due to SOCKS-proxy requirement], and Summary (Defects) report link updated above in main description.

cc @brianalloyd
