### ISSUE TITLE
Good | Bad Rating Component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34626]
#### High-level user story
As a Veteran I want to provide feedback in relation to my experience on VA.gov.  I want to express both positive and negative feedback in order to inform future updates to suggested pages, articles and app components.

### Background
[Current design](https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/)
Proposed design: 
![Screen Shot 2021-12-29 at 11 57 05 AM](https://user-images.githubusercontent.com/70410912/147694618-2a987329-f77d-4e6a-9862-af0362e45082.png)

[Current location of how do you rate component](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/includes/how-do-you-rate.drupal.liquid)

### Considerations
We need to modify the how-do-you-rate.drupal.liquid file to include only <div data-widget-type="how-do-you-rate"></div> where that div will be the mounting point for the static-page react app in vets-website. 

### Tasks
- [ ] Modify how-do-you-rate.drupal.liquid to include only <div data-widget-type="how-do-you-rate"></div>
- [ ] Ensure static-page react app mounts to the data-widget-type of how-do-you-rate

### Acceptable Criteria 
- [ ] Ensure static-page react app mounts to the data-widget-type of how-do-you-rate
- [ ] Do not build out the React app fully, that will be done as a follow-up ticket, this ticket should just be used for the boilerplate of how to set up that connection for a static-page React app between vets-website and content-build

**Comment by kelsonic** [comment]
Bumping to a 5, the PW work is a 3 and search + discovery work I'd imagine is also a 3, but feel free to adjust if need be 🙂

**Comment by kelsonic** [comment]
Plan is to knock this out on our cross-team call tomorrow 🙂 Exciting!

**Comment by kelsonic** [comment]
2 PRs are up for the how do you rate component, they're both in draft mode since @srsuddath and @TSimmz will still have to work off them.

Feel free to delete branches + create your own branches too, whatever you need to do 💯 

https://github.com/department-of-veterans-affairs/vets-website/pull/19800
https://github.com/department-of-veterans-affairs/content-build/pull/882

**Comment by brianalloyd** [comment]
@srsuddath @TSimmz it looks like PW work is done here, what I would like to do is close this ticket out and have a new ticket created that accounts for S+D work.  Thoughts?

**Comment by brianalloyd** [comment]
Cleared PW Milestones as well.  @nicole-leonard feel free to pull this into your backlog as appropriate, and please reach out if you have any questions.

**Comment by srsuddath** [comment]
Adding these wireframes here from @mgleo to help bring everything together

Consideration: Elsewhere on VA.gov, users are asked for feedback using this blue feedback button. Consider utilizing the blue feedback button for style consistency and to prevent pushing content further down the page.
![Screen Shot 2021-12-28 at 2.53.54 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/1f51585c-8434-4508-96cb-2c0ddae7ca67)



Wireframes/ User flow: 
![submit-feedback-userflow-wireframes.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/72755662-c420-44b9-b3eb-c7d7bd848bcf)

**Comment by srsuddath** [comment]
Most of the work for this ticket has been accomplished, but due to higher priority items this will need to roll over into next sprint / be reprioritized

**Comment by nicole-leonard** [comment]
Meeting with Michelle 1/13/22 to discuss how to get the kickoff set for this ticket.

**Comment by leahkeeler** [comment]
Moving to backlog for new teams
