### ISSUE TITLE
Update 22-1990S VRRAP: Design work

### ISSUE THREAD

**Issue by ERRonat0609** [department-of-veterans-affairs/va.gov-team#34639]
As a veteran filling out the VRRAP form, I want to select a high demand occupation from a list of HDO's so that I can complete my online form correctly. 
--
The ask is to add this information to the form in a way that the veteran can simply select from a list to enter the correct HDO number and program he/she wishes to pursue.

Per Rodney Hopkins (Education Services VRRAP team) some additional information has been requested to be added to the form. This information relates specifically to the high-demand occupations that are available to the veteran.

Currently, there is a PDF document that lists all of the high-demand occupations that are eligible for VRRAP, but this information is not included in the VRRAP form. EDU would like this information to be included when the user answers "Yes" to the question "Do you know which program you would like to enroll in?"  

Link to list of High-demand occupations: https://benefits.va.gov/GIBILL/docs/vrrap-high-demand-occupation-list.pdf

PDF form Section II, as received from EDU VRRAP team:
![VRRAP-Part2](https://user-images.githubusercontent.com/85580424/147707526-d7c6714e-f6d8-4b8a-9d3d-ba96fa1fdacf.png)

Screenshot of current electronic 1990S VRRAP form, Program Information section:

![image](https://user-images.githubusercontent.com/85580424/147706949-2dbb2a60-7292-40d6-92cb-33da7cd395f7.png)
--
## Tasks
- [ ] Work with designer and submit to Collaboration Cycle for review and determine the steps they require for approval. 
- [ ] Get design approval from platform to proceed with dev work

--
## Acceptance Criteria
- [ ] Designs have been created and submitted to Collaboration team.
- [ ] Designs have been approved to begin dev work.

**Comment by ERRonat0609** [comment]
Fore questions or assistance from EDU VRRAP team, please work with Rodney Hopkins.

**Comment by ERRonat0609** [comment]
Note that this option is the "long" version of accomplishing this task and will need to involve the Collaboration cycle and a lot of design work since there will be a lot of information being added to the form. 

The second option, however, is a simpler plan of action that could be accomplished in a shorter span of time, would likely not require a lot of change, and may only need a simple platform design review, since it would be to just add a link to the list of HDO's (the pdf is already available on VA.gov). There are around 230 different HDOs to choose from and if we just added a link to the list, which would allow the veteran to search for their HDO, then we would have to add only one field: the HDO number, in which the user could enter themselves. That will need to be discussed with the VRRAP team to see what they are okay with doing. https://benefits.va.gov/GIBILL/docs/vrrap-high-demand-occupation-list.pdf

**Comment by ERRonat0609** [comment]
Note that this option is the "long" version of accomplishing this task and will need to involve the Collaboration cycle and a lot of design work since there will be a lot of information being added to the form. 

The second option, however, is a simpler plan of action that could be accomplished in a shorter span of time, would likely not require a lot of change, and may only need a simple platform design review, since it would be to just add a link to the list of HDO's (the pdf is already available on VA.gov). There are around 230 different HDOs to choose from and if we just added a link to the list, which would allow the veteran to search for their HDO, then we would have to add only one field: the HDO number, in which the user could enter themselves. That will need to be discussed with the VRRAP team to see what they are okay with doing. https://benefits.va.gov/GIBILL/docs/vrrap-high-demand-occupation-list.pdf

**Comment by mrblanco1** [comment]
Cinda is investigating if this effort is worth moving forward with. She will keep us posted. This is on hold for now.

**Comment by mrblanco1** [comment]
Final wireframe was presented to EDU and they approved. Moving forward with development.
