### ISSUE TITLE
Right Rail Fixes

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34634]
## Issue Description
![right rail fix.png](https://images.zenhubusercontent.com/61b2600c16c9626a4c0b07c6/c610fed9-04c6-43fe-b5b5-b9bee081b147)
- “Look up Board of Veterans' Appeals (BVA) decisions” link on  changed to https://search.usa.gov/search?affiliate=bvadecisions
- The “Search VA reference materials (WARMS)” option on https://www.va.gov/search/ should be removed
---
## Tasks
Update and remove the required links

## Acceptance Criteria
- [x] BVA link has been changed
- [x] WARMS link has been removed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
