### ISSUE TITLE
[VAMC] Submit Redirects for System Campus Maps - Due to name change updates [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#34640]
## Task
- [ ] Compile and submit redirect request to IA 
- [ ] Reply to any issues that may arise from redirect request

## Acceptance Criteria
- [ ] GitHub Redirect request submitted with required information to take action
