### ISSUE TITLE
Form Requirements Inventory

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3464]
## User Story or Problem Statement
As a UX designer, I need to create a form requirements inventory so I can have a document containing all the required pieces for VA form 2345 (prosthetic socks) and VA form 2346 (hearing aid batteries). 

## Task
- [x] Create a list end points items. (base requirements)
- [x] meet with design team a review similar items from each order method. 
- [x] GH list 
- [ ] share with DLC

## Goal
_A document containing an inventory of both VA form 2345 and 2346_

## Objectives or Key Results this is meant to further
- _Ensures that all required pieces are included in the form's design_

## Acceptance Criteria
- [x] _Create a document (most likely a Mural) containing an inventory for VA form 2345 & 2346_
- [x] _Share document with development team_
- [x] _Share the document's link in the comments section of this ticket_

**Comment by rebeccawalsh** [comment]
We might need a little more information on this task, we weren't entirely sure what the result was intended to be since it's prior to ideation and design work being done. There's a good amount of conjecture in this document, but we've uploaded it to GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/content-inventory.md
