### ISSUE TITLE
[FE] Update contact is to be screen readable

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34649]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX Feedback](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141) 

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Ensure the list of data we are verifying is able to be read by a screen reader. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Lists should be tabable
- [ ] Information should be read by a screen reader
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by jparker0425** [comment]
Will be reaching out to Accessibility regarding this item to get recommendations. Will call out in post-launch review Collab Cycle.

**Comment by acrollet** [comment]
Closing as this is edit-related.
