### ISSUE TITLE
[FE] Remove Covid Sticky Banner

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34650]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX Review Doc](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141) 

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The COVID banner should not show on the pre check in page or the check in pages. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Work the correct teams to get the banner hidden
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
https://dsva.slack.com/archives/CT4GZBM8F/p1641325178367900

**Comment by mdewey** [comment]
No longer showing in Production
