### ISSUE TITLE
[FE][SPIKE] See if we can remove the sticky footer

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34651]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX Review](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141) 

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

This is a spike to see if we can remove the sticky footer from the pre-check-in experience. 

UX to provide screenshot of what the footer is. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Figure out what the sticky footer is
- [ ] Work with Public Websites on removing
- [ ] See if we can hide for our app. 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Report findings to team on banner configurations
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by ytsaoca** [comment]
![File (3)](https://user-images.githubusercontent.com/90633685/148122289-9dc4dcef-e029-44a1-bcd8-ff8c5a09f6ef.jpg)

**Comment by brianseek** [comment]
Added request to site-wide-content team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34913

**Comment by brianseek** [comment]
slack thread: https://dsva.slack.com/archives/C01K37HRUAH/p1641506514009800

**Comment by brianseek** [comment]
@ytsaoca This has been reported to be removed on prod and is ready for validation

**Comment by sarahknoppA6** [comment]
@niradatta1 and @zach-park to validate in a review session on thurs/fri with multiple validate tix. @brianseek to set up test appt

**Comment by zach-park** [comment]
Validated. @niradatta1 @brianseek
