### ISSUE TITLE
[FE] Safari and Icons

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34654]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX review](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Investigate and fix the icon alignment issues in Safari

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Investigate and fix the icon alignment issues in Safari
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by ytsaoca** [comment]
![safari](https://user-images.githubusercontent.com/90633685/148122147-be94509e-5799-49fc-a862-798e35f6f8bf.png)
