### ISSUE TITLE
[FE] Update content for Pre-check-in

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34653]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX review](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141)
 
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Update the content per Design

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Login page - "Replace "" we need some information to verify..."" with ""We need to verify your identity so you can start pre-check-in"""
- [x] Error message - Recieve an error message for DAY of check-in. This should be replaced with the message for pre-check-in. 
- [x] For content after "call your VA health care team", default to friendly name; if not available then use clinic name as fall back
- [ ] 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
These changes should be in staging and need validated

**Comment by niradatta1** [comment]
@mdewey We've validate the first two tasks. The following look good: 
-  Login page 
-  Error message 

But we still need to get through to the confirmation page to validate the last task listed in this ticket. Working with @acrollet to resend the link so we can validate that soon. Will update here.  'cc @ytsaoca

**Comment by niradatta1** [comment]
@mdewey I noticed the "We'd welcome your feedback!" modal with a link to a survey pops up on the login page and sometimes mid flow. Are we able to disable that? It may be distracting for a user who is trying to pre-check-in, which is a different use case vs. someone browsing the VA site. Will attach screen shot.

**Comment by niradatta1** [comment]
@mdewey We reviewed the confirmation page for the last task listed here. It's good to go. 'cc @ytsaoca

**Comment by mdewey** [comment]
Thanks for the review. I will close this and open a new ticket to track that feedback modal (which should be disabled already)
