### ISSUE TITLE
[FE] Move Emergency Contact Page

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34655]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX Review](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

This page should be displayed after contact info but before next of kin. 

Recommendation came from FE audit as well as usability sessions with Veterans. Higher value is placed on seeing the Emergency Contact over NOK. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Move the emergency contact page for pre-check-in
- [ ] Move the emergency contact for check-in as well 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
UX review: https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/Gm5VG7w

**Comment by mdewey** [comment]
Merged in master, should be deployed this morning.

**Comment by mdewey** [comment]
This is in staging and needs to be reviewed by the UX team 

CC: @niradatta1 @kristenmcconnell @ytsaoca @zach-park

**Comment by zach-park** [comment]
Validated the UI workflow: 
The emergency contact page appears before the current NOK page (but follow the current contact info page). 
Cc: @julieadair1 @mdewey @niradatta1 @ytsaoca @kristenmcconnell
