### ISSUE TITLE
[FE][SPIKE] Add Timezones to appointment times

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34652]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [UX review](https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1782768141)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Figure out how to add timezones of the facility to the appointment time. Timezones with the VA are traditionally handled by the timezone of the facility, not the user. This needs to be revisited to see what the best way forward is. 

Slack [thread](https://dsva.slack.com/archives/C022AC2STBM/p1641312696070800)

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Figure out the best way to add timezones. 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Necessary tickets have been identified. Work with Product to create those tickets.

**Comment by brianseek** [comment]
Looking into options Adrian is going to ask in CHIP scrum, then will make more recommendations based on that conversation. Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1641496105034200

**Comment by brianseek** [comment]
Spike to get timezone in LoROTA: https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/399

**Comment by brianseek** [comment]
Blocked until we get details from ticket above to make frontend tickets.
