### ISSUE TITLE
Review Load Tests and Create Confluence Doc of Status

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#34665]
## Issue Description
Load Tests were last run and reports generated approximately 1 year ago (PR here - https://github.com/department-of-veterans-affairs/devops/pull/8432).

As a tech debt review, evaluate the current state of the load tests and offer a recommendation of whether updates to the load tests suite is needed.

---
## Tasks
- [x] Update to most recent version of Locust (1.4 -> 2.5.1).
- [x] Rerun and generate recent (1/2022) sample reports.
- [x] Create a Confluence doc to evaluate status for the load testing suite.

## Acceptance Criteria
- [x] Create a Confluence Doc on the status of load tests & offer an assessment based on the results of the sample load test and evaluate whether a rerun of the load test suite is necessary.

**Comment by rjohnson2011** [comment]
WIP PR here -> https://github.com/department-of-veterans-affairs/devops/pull/10517

- Load test dependencies (Locust) have been updated to the most stable version: 1.4 -> 2.51
- In the process of rerunning load tests.

Running a sample loadtest in the `covid_chatbot` directory produced the following report:

```
Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,Failures/s,50%,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
GET,/coronavirus-chatbot/,135584,672,310.0,851.781957480772,130.62869500001284,21201.12402800001,45686.43474156243,450.75480323779163,2.2340927231516696,310,370,430,520,1800,4100,6300,8300,14000,19000,21000
,Aggregated,135584,672,310.0,851.781957480772,130.62869500001284,21201.12402800001,45686.43474156243,450.75480323779163,2.2340927231516696,310,370,430,520,1800,4100,6300,8300,14000,19000,21000
```

Compared to the last report run in 1/2020:
```
Type,Name,Request Count,Failure Count,Median Response Time,Average Response Time,Min Response Time,Max Response Time,Average Content Size,Requests/s,Failures/s,50%,66%,75%,80%,90%,95%,98%,99%,99.9%,99.99%,100%
GET,/coronavirus-chatbot/,158541,265,560.0,646.3149019287188,145.25123900000003,10109.674520999988,62703.01693568225,526.1953136360522,0.8795312134624724,560,630,690,750,960,1100,1300,2000,5800,8100,10000
,Aggregated,158541,265,560.0,646.3149019287188,145.25123900000003,10109.674520999988,62703.01693568225,526.1953136360522,0.8795312134624724,560,630,690,750,960,1100,1300,2000,5800,8100,10000
```

### Takeaways
There is a 17% decrease in the number of requests and a 253% increase in failure count from the load test report. Keep in mind, this is still a small number of failures (less than half of 1%).

### ToDo
Generate more reports and add to the PR.

**Comment by rjohnson2011** [comment]
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2037710967/Tech+Debt+Initiative+-+Load+Tests+Update+2022

**Comment by rjohnson2011** [comment]
PR ready for review with Locust updates & 2022 generated reports -> department-of-veterans-affairs/devops#10517
