### ISSUE TITLE
Replace external imports in our applications

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#34663]
## Background
Our application on VFS has very long build times with lots of flakey unit tests that fail in builds often, this is mostly due to the fact that when a build is run all of the apps have to built at the same time. To combat this the VSP team has undertaken an initiative to break the apps up and isolate them so that each app can be built independently. To do our part we need to get our apps ready for this new build process. To do this, we need to ensure that our apps aren't importing files from other applications.

## Considerations
**NOTE:** imported from refers to other applications importing this apps files, imported to refers to applications that are importing files from other applications

### Apps we own
- [x] `src/applications/personalization/rated-disabilites` * (imported from)
- [ ] `src/applications/personalization/view-dependents` * (importing to) (dependency-verification)
- [ ] `src/applications/static-pages/dependency-verification` * (imported from) (view-dependents)
- [ ] `src/applications/vre/28-1900` * (importing to)
- [ ] `src/applications/vre/28-8832` * (importing to)

## Tasks
- [ ] Ensure that all external imports are addressed

## Acceptance Criteria
- [ ] All external imports from our applications are addressed
- [ ] A PR is in place for review

**Comment by cohnjesse** [comment]
@saderagsdale Here is one of the tech debt tickets we will be working on during this time
