### ISSUE TITLE
Replace manifest.json imports with `getAppUrl`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#34660]
## Background
Our application on VFS has very long build times with lots of flakey unit tests that fail in builds often, this is mostly due to the fact that when a build is run all of the apps have to built at the same time. To combat this the VSP team has undertaken an initiative to break the apps up and isolate them so that each app can be built independently. To do our part we need to get our apps ready for this new build process. To do this, we need to utilize the `getAppUrl` registry helper to remove any import to `manifest.json` in our apps.

## Considerations
**NOTE:** imported from refers to other applications importing this apps files, imported to refers to applications that are importing files from other applications

### Apps we own
- [x] `src/applications/disability-benefits/686c-674`
- [x] `src/applications/disability-benefits/view-payments`
- [x] `src/applications/lgy/coe`
- [x] `src/applications/personalization/rated-disabilites` * (imported from)
- [x] `src/applications/personalization/view-dependents` * (importing to) (dependency-verification)
- [x] `src/applications/personalization/view-representative`
- [x] `src/applications/static-pages/dependency-verification` * (imported from) (view-dependents)
- [x] `src/applications/vre/28-1900` * (importing to)
- [x] `src/applications/vre/28-8832` * (importing to)

## Tasks
- [x] Search for all `manifest.json` imports from other apps in our apps and replace them using `getAppUrl`

## Acceptance Criteria
- [x] All imports of other applications `manifest.json` file should be replaced with `getAppUrl`
- [x] A PR is in place for review
