### ISSUE TITLE
Identity Broker (IdB) AXE

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#34688]
# Overview
Based on the [decision doc](https://vfs.atlassian.net/wiki/spaces/AMT/pages/1959067732/Identity+Broker+Decision) we will set up the chosen Identity Broker to facilitate Access Management. 

The **Identity Broker** (IdB) is a web application that acts as a "broker" for authentication between users and their configured Identity Provider: it can process authentication requests by means of external authentication endpoints.

Deploying the IdB will be the starting point for our Access Management solution. It will allow us to integrate apps and identity providers. It will allow us to integrate and deploy other solutions in a standardized way. 

We will also deploy a Infrastructure as code configuration (likely [Terraform](https://www.terraform.io/) to facilitate deployment of the IdB

**Comment by kjduensing** [comment]
adding pre-stories here:

Epic: Deploy IdB
- [ ] Make IdB decision
- [ ] Configure Cognito via Terraform (maybe manually at first)
- [ ] Login test page: Can log in
- [ ] Login test page: Can log out
- [ ] Login test page: Displays claims when logged in
- [ ] Login test page: Log in denied for a user

Standalone stories:
- [ ] Start list of roles/permissions/membership/etc for console (this is ongoing, not sure how to ticket-ize this)
- [ ] Gather info on users/roles for
  - [ ] Grafana
  - [ ] Datadog
  - [ ] ArgoCD
- [ ] Devise testing plan
