### ISSUE TITLE
Fix jump links on 2 health care pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34682]
## Issue Description
We currently have 2 pages with jump links that aren't working. 

1. On [Your health care costs page](https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/) the fourth link on the page "View more services we provide at no cost" should link to the "Services that don't require a copay" section of our [copay rates page](https://www.va.gov/health-care/copay-rates/). 

2. On [Dispute your VA copay charges](https://www.va.gov/health-care/pay-copay-bill/dispute-charges/) the link "Learn more about the collection process" should jump to "What happens if I don't pay my copay bill" on our [Pay your VA copay bill](https://www.va.gov/health-care/pay-copay-bill/#collection) page.

We will also need to review both pages for sighted language. There are a few instances of "view" throughout both pages.  

## Tasks
- [x] Update jump links (Selina)
- [x] Update sighted language on pages (Selina)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] Jump links working
- [x] No more sighted language on pages

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.
Your health care costs: http://preview-prod.vfs.va.gov/preview?nodeId=672
Dispute your VA copay charges: http://preview-prod.vfs.va.gov/preview?nodeId=705

**Comment by RLHecht** [comment]
Thanks @lunascoop Just published these. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
