### ISSUE TITLE
Content updates to vaccine records translation pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34686]
## Issue Description
We made changes to the English vaccine records page with  information about the new VA Health and Benefits app. We need to add this content to the translated pages.

## Tasks
- [x] Send content to translation team (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish (Randi)
- [x] Send to volunteer translators (Randi)

## Acceptance Criteria
- [x] Translated content on live pages

**Comment by RLHecht** [comment]
@lunascoop Here are the translated pages:

[https://app.zenhub.com/files/133843125/8d0669c4-76ef-40f3-8d88-96f439aaa5eb/download](https://app.zenhub.com/files/133843125/8d0669c4-76ef-40f3-8d88-96f439aaa5eb/download)

[https://app.zenhub.com/files/133843125/855a81e0-c825-4963-bde8-2f4affca88b5/download](https://app.zenhub.com/files/133843125/855a81e0-c825-4963-bde8-2f4affca88b5/download)

**Comment by RLHecht** [comment]
Live pages sent to Mateo. Closing ticket.
