### ISSUE TITLE
Q2 [Carryover] Autonomous Deployment: Release frontend autonomous deployment for allowed apps 

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34687]
## Problem Statement 
*Currently, all VFS teams use the same shared code repository vets-website for frontend apps. Although the apps are separated within the repo, changes to one app must be built and deployed along with the entire site. This slows down development, and creates unnecessary risk and overhead for VFS teams. Furthermore, scheduled deploys of the repo happen only 1x/day — any bug fixes or feature changes that VFS teams want to deploy outside of the scheduled daily deploy must be approved by Platform’s OCTODE leadership (and only critical bug fixes are approved). 

How might we allow those same single or grouped apps on the allowlist to deploy at any time without Platform intervention? *

## Hypothesis or Bet
*If we allow VFS teams to deploy at any time, they will develop more iteratively.* 
*If we allow VFS teams to deploy at any time, they will be less dependent on Platform and customer support requests will decrease while VFS satisfaction increases. (This allows us to support more VFS teams!)*
*If we allow VFS teams to deploy at any time, there will be a reduction in out of band deployments.*

## We will know we're done when... ("Definition of Done")
*Changes to apps on the [allowlist](https://github.com/department-of-veterans-affairs/vets-website/blob/main/config/changed-apps-build.json) are automatically deployed to production when merged into the `main` branch of the `vets-website` repository, upon the successful completion of the CI workflow*

**Question: Can we move forward with calling this continuous deployment, rather than autonomous deployment? Continuous deployment, we think, will be more clear for our end users as this is the industry standard term.**

## Known Blockers/Dependencies 
*Dependent on OCTODE sign off of solution approach*
*Go/No-go on August 9

## Projected Launch Date
Middle of Q3

Solution approach context in this MURAL board

Part 3 Question 1 shows that Pritchard & Chelen agreed on a continuous deployment approach — all successful commits to main (master) branch in vets-website will automatically deploy. The first step in this initiative is to write a proposal (an RFC? an ADR?) and present that, to socialize the use of continuous deployment for allowed frontend apps, before implementing

Consider pasting the notes from “What does this actually entail” here into a comment on ZenHub so that these notes aren’t lost

Could link to the (very rough/out of date) app deployment platform product outline as a holdover until product suite is defined and new product outlines are created

### ... tested?

- [x] [Usability test](https://docs.google.com/spreadsheets/d/1Lz3cfJhs_oorT8mk5yEMwcpEZWPToFsCQZgChGH31DE/edit#gid=0) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. ([Tested in lower environments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29142))
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD
      *NA

### ... documented?

- [x] New [documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2308178101?draftShareId=f203c955-7fb9-4855-b056-f85003582c58) is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)
   *NA

### ... measurable

- [ ] Reduced number of out of band deploy requests.
- [ ] Increase in VFS satisfaction (collected from survey)

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by laineymajor** [comment]
Feedback about CD - https://miro.com/app/board/uXjVPaiU6m8=/?share_link_id=797519873753

**Comment by laineymajor** [comment]
This initiative is complete. As you can, @mchelen-gov can you please add to the "done" column of the Product Board? Thank you!
