### ISSUE TITLE
Adjust width on "Apply Filters" component on Events Details Page 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34689]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Tasks
- [ ] Adjust width on "Apply Filters" component on Events Details Page 
- [ ] Collaborate with designer to ensure elements are aligned with design system
- [ ] Consult a11y team with any questions 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Adjust width on "Apply Filters" component on Events Details Page  
- [ ] Review on Staging / Ensure design has validated 
- [ ] a11y considerations are implemented in support

**Comment by brianalloyd** [comment]
@kelsonic ticket to capture the work effort on "apply filters" element.

**Comment by kelsonic** [comment]
PR merged: https://github.com/department-of-veterans-affairs/vets-website/pull/19789
