### ISSUE TITLE
HLR: replace `LoadingIndicator` with web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34698]
## Description

All instances of `LoadingIndicator` need to be replaced with `<va-loading-indicator>` web component.

## Tasks

- [ ] Replace React `LoadingIndicator` component with `va-loading-indicator` web component
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
