### ISSUE TITLE
Update endpoint listing to include endpoint and controller action

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#34691]
## Issue Description
_Update endpoint listing to include endpoint and controller action. When identifying endpoints to target for future efforts, it will be useful to develop protocol for call path tracing in order to isolate common code paths._

---
## Tasks
- [ ] _Update endpoint listing to include endpoint and controller action._
- [ ] _Develop strategy for splitting endpoints into functional groups and begin investigation into call path analysis._

## Acceptance Criteria
- [ ] _Endpoint listing is updated to include endpoint and controller._
- [ ] _Relevant call path tracing is incorporated into the endpoint listing_

**Comment by ewilson-adhoc** [comment]
The requested information endpoints was added to the endpoints document. The call path analysis was outside the scope of that sprint. Recommend closing this ticket and reopening a new one with that work if required.
