### ISSUE TITLE
Update Documentation with New Team Name

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#34700]
## Issue Description
The recent Platform team reorg has been designed to reduce cross functional team dependencies as well as create more accurate team names aligning to the products they support and own.
Our team name has changed from Product Support to Governance Team, this will need to be updated in our documentation.

---
## Tasks
- [x] Rename Confluence Space from "Platform Product Support Team" to "Governance Team" (Confluence should automatically update links)
- [x] Rename "Platform Support" to "Governance Team" on Confluence pages
- [x] Update Platform Website
  - [x] CC Homepage image
  - [x] VA.gov experience standard intro
  - [x] Midpoint Review Touchpoint
- [x] Update Orientation materials/PowerPoints
- [x] Update slack channel name. (OCTO-DE)
  - [x] Need to determine new slack channel name
- [x] Update Slack Collab Cycle group name from "vsp-product-support-members" (SRE Team)
- [x] Github team label from `vsp-product-support` to `governance-team`
- [x] Update Github templates with new label
- [x] Github Product Support team rename to Governance team
- [x] Update Zenhub board name
- [x] Uncover other places/spaces where Product Support team name would be listed.
- [x] Update Roadmap/Vision (Shira, please verify if this is needed)
- [x] Team member Slack profiles
  - [x] Chase
  - [x] Shira
  - [x] Allison
  - [x] Sean
  - [x] Clayton
  - [x] Jim
  - [x] Brian
  - [x] Sarah

Some items pulled from list located in this [Team Restructure document by Andrea ](https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1920434211/Potential+VSP+Tech+Teams+Restructure)in Step 4.

## Acceptance Criteria
- [x] Documentation will refer to team as Governance Team
- [x] Teams are able to reach out to Governance Team through slack and slackbot.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@jimuhh please update your DSVA Slack profile to include the following info: Program/Team - Role [Company]

**Comment by chaseakirby** [comment]
@shiragoodman I couldn't recall our exact discussion about the homepage image but I created a version of the homepage image with Governance Team rather than Product Support. I wasn't sure of the font so I used one that looked similar. We can use another font that may fit better or if we have another source image we want to start with.
![collaboration-cycle-diagram](https://user-images.githubusercontent.com/94856753/151229645-7abe489e-64dc-40de-adf8-60b64be9f724.png)

**Comment by shiragoodman** [comment]
let me look around... I think I _may_ have a copy somewhere.

**Comment by shiragoodman** [comment]
we're also going to have to update this image again once Sitewide Content joins so I think for now this is good enough. You can upload to Platform Website and we can close this out!

**Comment by chaseakirby** [comment]
Uploaded to Platform Website! I have marked that as complete. 
The only other task is Orientation decks, is that ready to be marked as done?

**Comment by shiragoodman** [comment]
oh darn. I missed that one. Maybe we could walk thru it in the morning? I know it needs the updated image of Collab Cycle. probably more.

**Comment by chaseakirby** [comment]
Sure thing!
