### ISSUE TITLE
[BE, FE] On-site Notification: Technical discovery for error states

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34708]
## Background

Per our **[discussion](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/product/Meeting%20Notes%20-%20On-site%20Notification%20working%20session%20for%20dismissable%20alert.md)**, we need to find out what kind of failures may occur when receiving a new Debt notice to display a notification on My VA.
We also need to find out what kind of data is available if/when these errors occur.  This will help us determine what kind of messaging we can show on My VA.

## Tasks

- [x] Meet with VA Notify to discuss what data and how we will receive from VA Notify
- [x] Discuss what kind of failures they see on their side and how that would transmit to My VA
- [x] Meet with our team and discuss recommendations on how to handle the failures

## Acceptance Criteria

- Obtain a clear understanding of failures may cause the on-site notification to not load properly on My VA
- Meet with our team and determine steps to handle the errors and/or data we receive

**Comment by lihanli** [comment]
based on our meeting with va notify there isn't going to be any partial error data available, so i don't think there will be any more error states to handle
