### ISSUE TITLE
Fix GH runner Packer build

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#34702]
## Description
Jobs for the [Packer build of GH runners](https://github.com/department-of-veterans-affairs/devops/actions/workflows/packer-build-runner.yml) are failing due to a swift install error.

## Tasks
- [x] fix swift install (seems site has changes, can't easily pull version number)
- [x] ensure rest of build tasks also pass, so that the AMI is successfully built

## Acceptance Criteria 
- [x] Get GH workflow working again

**Comment by jsgarmon** [comment]
[Run from PR branch](https://github.com/department-of-veterans-affairs/devops/actions/runs/1652085697) was successful.
