### ISSUE TITLE
[FE] My VA - Payment Information: Technical discovery for error states

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34704]
## Background

Per our **[discussion](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/Meeting%20Notes%20-%20Payment%20info%20Q&A,%20Age%20of%20payment,%20Error%20states.md)**, we need to find out what kind of failures may occur when pulling Debt or Payment information to display on My VA.
We also need to find out what kind of data is available if/when these errors occur.  This will help us determine what kind of messaging we can show on My VA.

## Tasks

- [x] Review error models used for the Health Care section and whether that could be used for payment info section
- [x] Discuss with Debt (Craig Wheeler) and Payment (Jason Wolf) teams to understand what kind of failures they see and what info could be available
- [x] Meet with our team and discuss recommendations on how to handle the failures

## Acceptance Criteria

- Obtain a clear understanding of failures may cause data to not load properly on My VA
- Meet with our team to determine steps to handle the errors and/or reduced data we receive

**Comment by hdjustice** [comment]
Moving to next sprint - development focus on other tickets, this technical discovery was not completed.  This effort should not take long, so looking to have it completed in the first few days of next sprint.

**Comment by tmitchellgcio** [comment]
They handle generic errors it being unavailable or anything like that. It goes all in the same bucket as unavailable. There isn't really specific errors other than that

**Comment by tmitchellgcio** [comment]
This really only has one error message that's needed. The error message for Health will likely work, but I don't think it's in the new format so the format will likely need to change for both healthcare and payment info.

**Comment by hdjustice** [comment]
Thank you @tmitchellgcio - Let's use a bit of time after DSU on Monday to talk through this with Liz, so that the design direction can be clear.

**Comment by hdjustice** [comment]
Met with the team and quickly reviewed the need for an error message to display when we are not able to retrieve information (server is down, etc).  Ticket already created to address the design efforts.  Thanks Taylor!
