### ISSUE TITLE
NOD: replace `AdditionalInfo` with web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34707]
## Description

All instances of `AdditionalInfo` need to be replaced with `<va-additional-info>` web component.

## Tasks

- [ ] Replace React `AdditionalInfo` component with `va-additional-info` web component
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
