### ISSUE TITLE
[MCP] Remove the VA health care facility's contact number from designs 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#34729]
## Issue Description
We received feedback from stakeholders that Veterans should contact the HRC for all questions. This will improve the Veteran's experience and reduce confusion about which number to call depending on the question. 

---
## Tasks
- [x] Update the UXPin prototypes to remove the VA health care facility phone number(s)

## Acceptance Criteria
- [x] UXPin prototypes have been updated and linked in this ticket
- [x] A ticket for frontend implementation has been created and linked in this ticket
