### ISSUE TITLE
Determine Product Labels from each team

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#34735]
## Issue Description
To move towards product-focused tracking and visibility, we will need to determine product labels that each team uses.

---
## Tasks
- [x] cross reference Platform Collaboration Cycle Point tracker against the VA.gov Product Directory. Put together a list of products we need to determine gh product labels for.
   - create a google sheets folder/file here: https://drive.google.com/drive/folders/1do66VEGQUkRJu1bO3LQA3E8E-XZDL1yV
   - goal is to only find labels for products we know we've worked with or have the potential to work with (for example, not lighthouse APIs)
- [x] Check in with Shira
- [x] determine if a gh label already exists for the product
   - check tracker
   - check gh labels 
   - assumed vs. known
- [x] put together list of recommended labels
- [x] Contact each team and request product labels that they currently use:

> Hello Product Owner. Platform Governance team is planning to pivot tracking of Collaboration Cycle support towards the VA.gov product in addition to team tracking, which is already in place. We are starting by reviewing the VA.gov Products pages in Confluence that was shared with PMs and POs in fall of 2021. For each product listed, we are attempting to locate a GitHub label that is currently in use for the product. If a label does not exist, we plan on creating one with collaboration from you/your team. Below are the products where you're listed as the OCTO-DE lead:

> These are the labels we propose for those products.

  - [x] Need to determine process if team does not have product labels
- [x] Need to determine how to store list of responses
- [x] Have PO confirm that this is their complete list of products (ie validation of the [VA.gov Products page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview))

## Acceptance Criteria
- [x] Each team has responded with product labels they are using
- [x] A process has been documented how we receive notification of new product labels

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by seanasewell** [comment]
Current product label google sheet https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0

**Comment by seanasewell** [comment]
@shiragoodman We added a team column. Next step is recommending product labels. How should we go about doing that? Is there a specific format we should follow when thinking about what we should call these?

**Comment by briandeconinck** [comment]
Posting here for future reference -- QA team's MVP for a [product directory](https://github.com/department-of-veterans-affairs/product-directory/blob/master/CSVs/CombinedProducts.csv)

**Comment by shiragoodman** [comment]
@seanasewell looking at the labels that already exist, it seems like the gh label and the product name are usually the same. Keep in mind that this is just a recommendation... the Product Owners and Product Managers have final say over what they want their label to be. I would advise creating a new column called "Recommended Github Product Label" - if the PO/PM approves, we can move it to the "Github Product Label" column. If they don't, they can propose what label they'd like instead.

**Comment by seanasewell** [comment]
@shiragoodman @briandeconinck I added a "Recommended Product Label" column. I didn't really follow a format. I just moved over what the product name was. I also added a "Team Proposed Product Label" column. We can add the team's proposed product labels here as to not confuse us on which one's still need team feedback. We can also use it as a "final" list. A couple of questions around formatting...

- Do we need to add team name to the product label (some have the team name as part of the product label)?

- Will there ever be a scenario where two separate teams are working on projects with a similar name and use the same product label? In this scenario, the team name in the product label might help to differentiate the two products. Especially if a team name Github label isn't used on the project. If this scenario won't exist, do we need to require a team label be used or just rely on the Github ticket name to fill in the gaps?

- Some labels have hyphens and some don't. Some use capitalization and some don't. Should we create a format now ahead of reaching out to teams to ensure that they are following some guidance around this? For example: 

All product labels should start with the team name and be followed by the product name. All words within the label should be lower case with each word separated by a hyphen. Please include the full name of the product including words like "and" and "or". Obviously, I am not suggesting this format, only providing an example of information that might be relevant to the teams who will decide what the product labels will be.

Format template: [Team Name][Product Name] 
Example using format template: benefits-delivery-hypertenstion-fast-tracker-pilot

**Comment by shiragoodman** [comment]
> @shiragoodman @briandeconinck I added a "Recommended Product Label" column. I didn't really follow a format. I just moved over what the product name was. I also added a "Team Proposed Product Label" column. We can add the team's proposed product labels here as to not confuse us on which one's still need team feedback. We can also use it as a "final" list. A couple of questions around formatting...
> 
> * Do we need to add team name to the product label (some have the team name as part of the product label)?

No. If the team is already using a product label that has their team name in it, that's ok. We can change it later if needed. But don't propose any labels with the team name in it. Products can sometimes switch ownership so it's helpful to have the product and the team label separate.
> * Will there ever be a scenario where two separate teams are working on projects with a similar name and use the same product label? In this scenario, the team name in the product label might help to differentiate the two products. Especially if a team name Github label isn't used on the project. If this scenario won't exist, do we need to require a team label be used or just rely on the Github ticket name to fill in the gaps?

This should not happen. If they're working on products with similar names, we want to make sure the products have 2 distinct labels. In time, we will likely require team labels to be used in conjunction with the product label. Right now we're just using the team label.
> * Some labels have hyphens and some don't. Some use capitalization and some don't. Should we create a format now ahead of reaching out to teams to ensure that they are following some guidance around this? For example:
> 
> All product labels should start with the team name and be followed by the product name. All words within the label should be lower case with each word separated by a hyphen. Please include the full name of the product including words like "and" and "or". Obviously, I am not suggesting this format, only providing an example of information that might be relevant to the teams who will decide what the product labels will be.

I like the idea of establishing guidance, but I don't want our guidance to include the team name in the product label. Hyphens are okay. preferably lower case. If you'd like to draft a basic guidance for how we came up with our recommended labels, that would be fantastic.
> 
> Format template: [Team Name][Product Name] Example using format template: benefits-delivery-hypertenstion-fast-tracker-pilot

I'd also advise that words like "pilot" "mvp" and "1.0" and "2.0" not be included in the labels. For example, Typeahead. The product is Typeahead. 1.0 and 2.0 imply different versions of it but it's still the same product. If the team wants to use "Typeahead2.0" label in addition to the "Typeahead" label, that's ok. As long as we know the _product_ label. Keep in mind that this effort to establish labels is for _our_ benefit and _our_ means of tracking products. They're free to use the labels on their own tickets too, but we just need to ensure our Collab Cycle tickets have a consistent approach to labeling.

**Comment by seanasewell** [comment]
@shiragoodman @briandeconinck I revised the recommended label column. Let me know your thoughts and if we can move on to contacting teams. Thanks!

**Comment by shiragoodman** [comment]
hey @seanasewell and @briandeconinck - I made a few small changes:

1. Renamed "VSP Team" column to "VFS Team"
2. Caregivers is now called 10-10 so I updated the VFS Team column 
3. Made each column filterable/sortable

Could we set up some time to review this together? There's a lot I want to share and I think saying in person might be better than trying to fit it all here.

**Comment by briandeconinck** [comment]
@seanasewell Filled in a few more gaps! Still plenty of empty cells though.

**Comment by seanasewell** [comment]
@briandeconinck Thanks! @shiragoodman Feel free to get your eyes on this whenever you get a chance :)

**Comment by shiragoodman** [comment]
@seanasewell @briandeconinck thank you so much for reorganizing this. It makes much more sense and while there are still many blanks, I think setting up 15 minute syncs with the PMs will help clean it up. I'm going to create a new ticket for that work, and I'll take responsibility for organizing the meetings. Thank you for your hard work!
