### ISSUE TITLE
Create 1 core Collaboration Cycle github ticket per product/feature cycle

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#34737]
## Issue Description
In ticket #34724, a first draft of the Core Collaboration Cycle GitHub ticket template was created. The purpose of this ticket is to iterate on the draft to ensure it meets all criteria necessary for the Collaboration Cycle, with emphasis on the touchpoints owned by Governance team (Collaboration Cycle Kickoff, Design Intent, Midpoint Review, and Staging Review)*. 

*The Full Accessibility & 508 Office Audit will potentially be retired, pending approval from the VA 508 Office. Although that hasn't occurred yet, we are moving forward with the assumption that it will be retired so we will NOT include that touchpoint in the Core template.

---
## Tasks
- [x] Review [prototype created by Shira](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp-collaboration-cycle/core-collaboration-cycle-ticket.md)
- [x] Add CC Kickoff to draft template
- [x] Review and update Artifacts section
- [x] Add Analytics team section
- [x] Add Security review section
- [x] Add Sitewide Content and IA Intake section (their process is changing, placeholder section)

## Acceptance Criteria
- [x] Core CC template meets the criteria of the Collaboration Cycle Kickoff
- [x] Core CC template meets the criteria of the Design Intent
- [x] Core CC template meets the criteria of the Midpoint Review
- [x] Core CC template meets the criteria of the Staging Review
- [x] Core CC template includes a section for referencing and attaching the tickets for the other Collab Cycle touchpoints:
   - [x] Research Plan Review (check with Clayton on what should/could be linked here)
   - [x] Analytics Request
   - [x] Contact Center Review
   - [x] Privacy, Security and infrastructure readiness review
   - [x] Sitewide Content and IA Intake Request (this is new - see ticket #35673 for reference)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by briandeconinck** [comment]
Some quick notes on using yaml:
- Supported field types are: `input` (single line of text), `textarea` (plaintext paragraph free response), `dropdown` (single-option select from a static list of options), and `checkboxes` (multi-option select from a static list of options)
- Any field type can be made required. The button to create the issue is disabled if all required fields aren't completed.
- Once the form is completed and the issue is created, the issue itself is markdown generated from the responses. So after the initial ticket creation, no form fields. Any subsequent updates to the issue would be just like with any normal issue.

So for the core CC issue template, the VFS product info and kickoff questions could be done using a form built with yaml. But updates after that (adding artifacts, all of the touchpoints) wouldn't be form-y, just standard markdown. I can put together a simple proof-of-concept for what that might look like.

**Comment by shiragoodman** [comment]
thanks for this, @briandeconinck ! I recall someone saying the other day that Service Design has a template in use that utilizes yaml. Also, Chelen told us yesterday that it's really easy to convert an existing markdown template to yaml. Maybe you could try and find that template for reference? I'd start by asking Jonathan Nelson.

Some random comments:

- LOVE that dropdown lists are an option. That could REALLY help us when it comes to ensuring teams use consistent team names and product names.
- also super happy to hear that fields can be made required. Again, that should really help us out when it comes to ensuring teams complete the form fully.
- understanding able that once the form is created it converts to md.

Would love to see your proof-of-concept!

**Comment by briandeconinck** [comment]
@seanasewell whenever you've got time to review...

- [Draft core CC ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/briandeconinck-core-cc-ticket/products/platform/vsp-collaboration-cycle/core-collaboration-cycle-ticket.md#vfs-product-information) with every touchpoint included. Some notes: 
    - This is on the `briandeconinck-core-cc-ticket` branch, but we can merge into the main branch whenever we want
    - The kickoff questions section is currently open by default. My thought is that once touchpoints are determined and added to the ticket we can make them open/closed by default based on what's most relevant to the VFS team at the moment. Super simple code implementation: `<details>` is closed by default, `<details open>` is open by default.
    - Assistive technology support for the `<details>`/`<summary>` pattern is good-ish. If we decide we like that pattern I'll need to do some extra testing to see if there's anything else we need to do to make it a bit better.
    - Sitewide Content and IA Intake Request section is just a placeholder, since I don't think there's any information about that process yet. (@shiragoodman?)
    - Research Plan Review section, next step will be to follow up with Clayton for changes/improvements
- [Draft Yaml-ified version of the ticket](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=cc-test.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) (just kickoff questions and initial artifacts)
    - You only get the form view from the yml file if you've created an issue template on a live repo. For testing purposes, I've done that on [briandeconinck/cc-test](https://github.com/briandeconinck/cc-test). Create as many test issues as you want, no one will be bothered with emails except me.
    - We don't have much control over the formatting of the [ticket generated from the yml form](https://github.com/briandeconinck/cc-test/issues/2). If we want the CC ticket to look like the Markdown template when VFS teams are going through all the touchpoints, it's going to be extra work for us to re-format their responses generated from the yml form. Not sure if the effort required is worth the benefit from the yml form, so that's something worth testing.

Give them a look, and please feel free to make changes or give feedback!

**Comment by seanasewell** [comment]
@briandeconinck Looking really good. I like that there can be some logic around the accordions so it's not information overload. I made a small text change. I updated "reviewed" to "review" here https://d.pr/i/a82i9h. While I do really like that there are actual input fields, I can understand the re-formatting being an issue. @shiragoodman What are your thoughts?

**Comment by shiragoodman** [comment]
@briandeconinck @seanasewell I really like what you've put together so far. Some general comments:

- some of the fields in "VFS product information" are to be completed post launch, so 1) might want to state that somehwere in the ticket, and 2) remove the asterisk* indicating it's required from the YAML version. The post launch fields are: Feature launch date,  Production URL, and Front-end information. 
- We'll want to follow up with the Platform teams on the "front-end information" - can one of you create a ticket for the backlog?
- the "VA 508 Office audit request ticket number" can be removed as this may soon be longer relevant
- For the non-Governance team owned touchpoints (Analytics Request, Contact Center, and Privacy & Security), it would be nice to have it as a checklist item for the VFS team to complete. For example, "Analytics & Insights request ticket has been linked below"
- re the formatting of the ticket generated from the YML form, I think it would be a good idea to test this out. If we get an overwhelmingly positive response from PMs, we may want to move that direction and determine how to make it easiest for us to update. 

I think writing our operational docs and VFS-facing guidance will inform us what's missing and what could be included. Also, testing will be very helpful.

Great job! Let me know if you need anything else from me.

**Comment by seanasewell** [comment]
@shiragoodman Still reviewing some of your feedback above but created a backlog ticket for "front-end information". I might need some assistance filling out the acceptance criteria for that one. https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/37345

cc: @briandeconinck

**Comment by shiragoodman** [comment]
@seanasewell thank you, and don't worry about the context of the ticket. We'll get to it later, I just wanted to make sure we had a placeholder for completing that work.

**Comment by briandeconinck** [comment]
Have updated both the markdown and Yaml versions based on Shira's feedback:
- Fixed the erroneously required fields, added some simple draft instructions to the VFS product info section of the Yaml version.
- Removed "VA 508 Office audit request ticket number" from both versions
- In the markdown template, reformatted touchpoints owned by other teams to follow the checklist format for VFS teams.

I think that should put us in a good place for coming up with a testing plan!
