### ISSUE TITLE
Get stakeholder approval and publish Section 702 R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34743]
## Issue Description
We need to send stakeholders the R&S article [In-state tuition rates under the Veterans Choice Act](http://preview-prod.vfs.va.gov/preview?nodeId=37717) and once approved publish to prod. Before we publish we need to go through the pre-publishing checklist.

Note that we should link to this article from a few places:
[How we determine your GI Bill coverage](https://www.va.gov/resources/how-we-determine-your-post-911-gi-bill-coverage/)
[Post-9/11 GI Bill page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/#what-benefits-can-i-get-throug)

## Tasks
- [x] Send article to stakeholders (Beth)
- [x] Implement any stakeholder changes (Beth)
- [x] Review with pre-publishing checklist (Randi)
- [x] Publish (Randi)
- [x] Notify stakeholders that page is live (Beth/Randi)

## Acceptance Criteria
- [x] New article is live on prod

**Comment by bethpottsVADEPO** [comment]
I just sent the article to SMEs for their review. @RLHecht would you take a look at my latest 2 edits saved in the file?
http://preview-prod.vfs.va.gov/preview?nodeId=37717

**Comment by RLHecht** [comment]
@bethpottsVADEPO Have you heard back from the stakeholders on this? Going to move this to the blocked column for now.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you for moving this to blocked. I'll ping them again this week and prompt them for feedback.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I've implemented the stakeholder feedback into the drupal file. Would you compare what I've done to the Word doc they sent and make sure I've deleted and revised according to what's in there? Thanks! (you could also upload the Word doc into this ticket for tracking purposes--you're cc'd on what they sent back)

I have one more email queued up to send them once you're finished with your pass, so let me know, then we can go live either tomorrow or Friday, whenever you can fit it in.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Your changes look good. Here's the word doc from the stakeholder:
[in-state tuition article stakeholder requested revisions 2-8 cq.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8035471/in-state.tuition.article.stakeholder.requested.revisions.2-8.cq.docx)

**Comment by RLHecht** [comment]
I did the final review and published this page.

**Comment by RLHecht** [comment]
@bethpottsVADEPO I added links to this article on the following pages. Can you please review and let me know if these are good to publish?

preview-prod.vfs.va.gov/preview?nodeId=935
preview-prod.vfs.va.gov/preview?nodeId=35367

I didn't think there was a logical place to add this to the MGIB-AD page or VR&E but let me know if you think we should put it on them.

**Comment by bethpottsVADEPO** [comment]
@RLHecht For the first crosslink (node 935), we'll want to be clear that we're saying you may be able to get in-state tuition even if you're an out-of-state student, since not everyone will know the significance of the Veterans Choice Act.

Link text: Find out if you can get in-state tuition rates as an out-of-state student

The crosslink text for node 35367 looks good!

These two pages makes sense to me for now. We'll have to keep reassessing as we go with new content.
