### ISSUE TITLE
Update URLs for GI Bill Comparison Tool on Drupal Pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34753]
## Issue Description
Now that the GI Bill Comparison Tool's URL changed, there are several broken links on Drupal pages that need to be updated. 

The new URL is: https://www.va.gov/education/gi-bill-comparison-tool/

Here is a list of the pages where links need to be updated:

[https://app.zenhub.com/files/133843125/88365c6c-c184-4221-9cba-889e22a41a84/download](https://app.zenhub.com/files/133843125/88365c6c-c184-4221-9cba-889e22a41a84/download)

## Tasks
- [x] Update links in Drupal (Selina)
- [x] Review and publish (Randi)
- [x] Notify GI Bill Comparison Tool team that URLS are fixed (Randi)

## Acceptance Criteria
- [x] URLs are updated on live pages

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. Here are my notes:

**GI Bill comparison tool link not on these pages**

- After you apply for education benefits:  http://preview-prod.vfs.va.gov/preview?nodeId=937
- Change your GI Bill school or program: http://preview-prod.vfs.va.gov/preview?nodeId=939
**- VA education benefits for survivors and dependents:  http://preview-prod.vfs.va.gov/preview?nodeId=984 (Updated sighted language and bulleted list formatting)**
- Transfer your Post-9/11 GI Bill benefits: http://preview-prod.vfs.va.gov/preview?nodeId=952
- Post-9/11 GI Bill Statement of Benefits: http://preview-prod.vfs.va.gov/preview?nodeId=3007
- https://prod.cms.va.gov/school-administrators (page not found in CMS)

**Updated link on these pages**

- VA education and training benefits: http://preview-prod.vfs.va.gov/preview?nodeId=71
- Foreign programs: http://preview-prod.vfs.va.gov/preview?nodeId=925
- Montgomery GI Bill Active Duty (MGIB-AD): http://preview-prod.vfs.va.gov/preview?nodeId=932
- Montgomery GI Bill Selected Reserve (MGIB-SR): http://preview-prod.vfs.va.gov/preview?nodeId=934
- Post-9/11 GI Bill (Chapter 33): http://preview-prod.vfs.va.gov/preview?nodeId=935
- CareerScope assessment: http://preview-prod.vfs.va.gov/preview?nodeId=718
- Other VA education benefits: http://preview-prod.vfs.va.gov/preview?nodeId=945
- Post-9/11 GI Bill and other VA education benefit rates: http://preview-prod.vfs.va.gov/preview?nodeId=938

**Comment by RLHecht** [comment]
@timcosgrove Can you take a look at the comment above? This are a few pages that you gave us that don't have the GIBCT link on the page. Thoughts of why those would show up with broken links? Nothing is showing a broken link when I open the Drupal page.

**Comment by RLHecht** [comment]
Thanks @lunascoop I published all the pages with mentions. I will notify the folks who own the school administrators page for them to update as well since that page isn't in Drupal.

**Comment by RLHecht** [comment]
@lunascoop Here are more that Tim found. They might not all have the link on there but please check and update any that do. Thanks!

https://prod.cms.va.gov/education/about-gi-bill-benefits/
https://prod.cms.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/
https://prod.cms.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/
https://prod.cms.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
https://prod.cms.va.gov/education/choosing-a-school/
https://prod.cms.va.gov/education/choosing-a-school/principles-of-excellence/
https://prod.cms.va.gov/education/eligibility/
https://prod.cms.va.gov/education/how-to-apply/
https://prod.cms.va.gov/education/opt-out-information-sharing/
https://prod.cms.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
https://prod.cms.va.gov/education/survivor-dependent-benefits/fry-scholarship/
https://prod.cms.va.gov/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/

**Comment by lunascoop** [comment]
@RLHecht I updated the links on the pages above except for:

https://prod.cms.va.gov/education/opt-out-information-sharing/
https://prod.cms.va.gov/education/eligibility/

We already published the change in the first batch:
https://prod.cms.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/

**Comment by RLHecht** [comment]
Update: All our pages are published. I emailed stakeholders about the school administrators page but still waiting to hear back. May need to move this to next sprint for that final piece.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Unless something on the drupal end is still outstanding, you can close this ticket. Tammy said she is all set for that one school admin page. She just needed to find someone to approve her PR. I bet it'll go live today.
