### ISSUE TITLE
[Epic] Launch 8940 and 4192 Forms 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3475]
## High Level User Story
As a veteran I need to use the online claims tool to share information about my unemployability so that VA can have everything needed to review my claim.

## Hypothesis/(es)
**If** _the forms are launched as a subset of the digital 526 Disability Compensation form_ **then** _then the user can continue to complete their online submission process without being directed to print, fill out and snail mail the current PDF versions of these forms_.

## Goals
_Confirm code accuracy and launch 8940 and 4192_ 

## Tasks
- [x] Technical discovery
- Booz Allen folder in GH
- [x] Check code to make sure it's running/working
- [x] Identify how to incorporate code into the main flow
- [x] Make sure back-end is working and connects to the right places
- [x] Ability to generate PDF 
- [x] Research done; FE to be tested

*the process for these forms would be the same as 781*

## Links to PDFs
[Form 21-8940 Veteran's Application for Increased Compensation Based on Unemployability](https://www.vba.va.gov/pubs/forms/VBA-21-8940-ARE.pdf)
[Form 21-4192 Request for Employment Information in Connection with Claim for Disability Benefits](https://www.vba.va.gov/pubs/forms/VBA-21-4192-ARE.pdf)

**Comment by chrvalla** [comment]
Paper Forms were compared with what we have in staging and found identical. Ticket closed.

**Comment by saderagsdale** [comment]
@Mottie Hey! looking for some context on what this epic of work is? Looks like the previous PM removed us.

**Comment by Mottie** [comment]
We want to get these 526 sub-forms into production. Forms 8940 & 4192 have been verified by our previous researcher to still match the paper forms. They are ready to go, and are hidden behind a feature flag.

From my research, these forms are the only way some Veterans can get disability compensation (total disability rating based on individual unemployability, or TDIU rating). So, I think this is an important form to get online. Honestly, I wish it was split out from 526, so the form could be filled out separately from 526, but this is how it's set up right now.

**Comment by saderagsdale** [comment]
@Mottie I'll talk to Matt about releasing these and see what he says. Maybe it slipped through the cracks.

**Comment by saderagsdale** [comment]
Pinged Matt on 6/7.

**Comment by saderagsdale** [comment]
@mattpointzxer0 Sharing an update:

We discussed this in refinement today. Design and product would like to demo this internally with @Mottie to understand what these forms are, if their designs align with current standards, and if there are any risks to releasing these items since they were built so long ago.
