### ISSUE TITLE
Cypress a11y updates for `expandAccordions`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#34752]
## Description

The [Cypress command `expandAccordions`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/testing/e2e/cypress/support/commands/expandAccordions.js#L8) was generalized to target `button[aria-expanded=false]`. This works well for the React `CollapsiblePanel` (accordion; almost completely replaced) and `AdditionalInfo` components. But we transitioning to use `va-accordion-item` and `va-additional-info` web components, both of which have the `button[aria-expanded]` contained within their shadow DOM. This results in the Cypress tests now expanding these web components before running axe tests.

A fix would require the [Cypress command `expandAccordions` to target both the React button and the Web Component button within the shadow DOM.

## Tasks
- [ ] Update the Cypress `expandAccordion` to target both React and Web Components
- [ ] Verify accordion & additional info blocks expand

## Definition of done
- [ ] All tasks complete
- [ ] All tests passing

**Comment by pdavies88** [comment]
Merged via: https://github.com/department-of-veterans-affairs/vets-website/pull/20051
