### ISSUE TITLE
Include radius parameter in Lighthouse queries (front end)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34765]
## Issue Description
When we updated our Facility Locator queries to Lighthouse to use lat/long rather than bounding box, we lost the ability to limit the data set. This  resulted in a data which includes all facilities, displayed in descending order. Lighthouse has added the ability to send a radius parameter. 
This change will impact searches for Facility type = VA health, VA benefits, Cemeteries and Vet Centers.

Community care queries currently use radius (such as Facility type = Community provider). [Example search](https://www.va.gov/find-locations/?page=1&address=Cheyenne%2C%20Wyoming%2082007%2C%20United%20States&facilityType=provider&serviceType=213E00000X&latitude=41.12&longitude=-104.84&radius=33&bounds%5B%5D=-105.59&bounds%5B%5D=40.37&bounds%5B%5D=-104.09&bounds%5B%5D=41.87&context=Cheyenne%2C%20Wyoming%2082007%2C%20United%20States)

---
## Tasks
- [ ] Rather than bounding box, send lat/long and radius parameter in Lighthouse queries (VA locations) 
- [ ] Clean up any references to bounding box
- [ ] Add/update any unit tests

## Acceptance Criteria
- [ ] VA location search results will now include only those locations found within the bounding box
- [ ] If the Veteran changes zoom level of the map, the query will include the new radius and lat/long
- [ ] If the Veteran moves the map, the query will include the lat/long and radius

This will unblock merge/sort

**Comment by mmiddaugh** [comment]
@mdewey [these technical diagrams](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/issue-response.md) should help.

**Comment by mdewey** [comment]
Quick update. 


## Today
- Removed bounds from API call
- The calls were already using radius/lat/long, but were not being used. They are now being used since the bounding box was removed
- Bounds were removed from the API code. 
- Create draft PR

## Next

- Continue testing for regression
- Update Unit test/e2e tests

**Comment by mmiddaugh** [comment]
Initial results from testing in review instance compared to staging

Observations so far
- Mixed results for Urgent care + all in-network - need to do more testing
- Fewer locations are returned for most searches in review instance but locations and map representation is accurate

### 20422 (entered as postal code = Washington DC, high volume location)
Facility type | Staging | Closest location (miles) | Farthest location (miles) | Review instance | Closest location (miles) | Farthest location (miles)
-- | -- | -- | -- | -- | -- | --
VA health | 19 on 2 pages | 0.1 | 33.4 | 3 results | 0.1 | 7
VA health + cardiology | 2 results | 0.1 | 32.3 | 1 result | 0.1 | n/a
VA benefits | 17 results on 2 pages | 2.6 | 54.8 | 5 results | 2.6 | 6.7
VA benefits + Applying for benefits | 7 results | 2.6 | 33 | 2 results | 2.6 | 2.9
VA cemeteries | 11 results on 2 pages | 3.7 | 37.6 | 2 results | 3.7 | 9.2
Vet Centers | 7 results | 1.3 | 36.1 | 2 results | 1.3 | 6.4
Urgent care + all in-network | 1 page - 10 community care, 1 VA | 0.1 | 54.2 | 1 page - 11 community care | 0.1 | 0.2
Urgent care + VA urgent care | 1 result | 54.2 | n/a | no results | n/a | n/a
Urgent care + community care | 1 page - 11 community care | 0.1 | 0.2 | 1 page - 11 community care | 0.1 | 0.2
Emergency care + all in-network | 13 results - 1 page | 0.1 | 32.3 | 1 page - 11 community care | 0.1 | 7.1
Emergency care + VA urgent care | 3 results | 0.1 | 32.3 | 1 result | 0.1 | n/a
Emergency care + community care | 13 results on 2 pages | 0.1 | 9 | 13 results on 2 pages | 0.1 | 9
Community providers - Chiropractor | 318 on 10+ pages | 2.2 | n/a | 318 on 10+ pages | 2.2 | n/a
Community pharmacies | 395 on 10+ pages | 0.1 | n/a | 395 on 10+ pages | 0.1 | n/a

### 59860 (entered as postal code, rural location)
Facility type | Staging | Closest location (miles) | Farthest location (miles) | Review instance | Closest location (miles) | Farthest location (miles)
-- | -- | -- | -- | -- | -- | --
VA health | 1 result | 37 | n/a | no results | n/a | n/a
VA health + cardiology | no results | n/a | n/a | no results | n/a | n/a
VA benefits | no results | n/a | n/a | no results | n/a | n/a
VA benefits + Applying for benefits | no results | n/a | n/a | no results | n/a | n/a
VA cemeteries | 1  result | 46.6 | n/a | no results | n/a | n/a
Vet Centers | 2  result | 36.6 | n/a | no results | n/a | n/a
Urgent care + all in-network | no results | n/a | n/a | no results | n/a | n/a
Urgent care + VA urgent care | no results | n/a | n/a | no results | n/a | n/a
Urgent care + community care | no results | n/a | n/a | no results | n/a | n/a
Emergency care + all in-network | 3 results - all community care | 0.8 | 11.3 | 3 results - all community care | 0.8 | 11.3
Emergency care + VA urgent care | no results | n/a | n/a | no results | n/a | n/a
Emergency care + community care | 3 results - all community care | 0.8 | 11.3 | 3 results - all community care | 0.8 | 11.3
Community providers - Chiropractor | 8 results | 0.2 | 27.1 | 8 results | 0.2 | 26.4
Community pharmacies | 11 results on 2 pages | 0.3 | 22.9 | 11 results on 2 pages | 0.3 | 22.9


### Indianapolis (entered as city)
| Facility type | # of results in Staging | Closest location (miles) | Farthest location (miles) | # of results in Review instance | Closest location (miles) | Farthest location (miles)
-- | -- | -- | -- | -- | -- | --
VA health | 13 results | 0.6 | 46.9 | 9 results | 0.6 | 28.8
VA benefits | 3 results | 0.5 | 38.2 | 2 results | 0.5 | 28.8
VA cemeteries | 3 results | 3.5 | 62 | 2 results | 3.5 | 4.1
Vet Centers | 1 result | 9.9 | n/a | 1 result | 9.9 | n/a
Urgent care + all in-network | 11 results (10 community care + 1 VA) | 0 | 1.7 | 11 results (10 community care + 1 VA) | 0 | 1.7
Urgent care + VA urgent care | 1 result | 1.7 | n/a | 1 result | 1.7 | n/a
Urgent care + community care | 10 results | 0 | 0.4 | 10 results | 0 | 0.4
Emergency care + all in-network | 11 results (10 community care + 1 VA) | 1.1 | 11.2 | 11 results (10 community care + 1 VA) | 1.1 | n/a
Emergency care + VA urgent care | 1 result | 1.7 | n/a | 1 result | 1.7 | n/a
Emergency care + community care | 4 pages | 1.1 | 33.9 | 4 pages | 1.1 | 33.9
Community providers - Chiropractor | 276 on 10+ pages | 5.2 | n/a | 276 on 10+ pages | 5.2 | n/a
Community pharmacies | 430 on 10+ pages | 0.4 | n/a  | 430 on 10+ pages | 0.4 | n/a

**Comment by mmiddaugh** [comment]
I've tested every type of search in Des Moines, Sarasota, and Albuquerque, in addition to the previous locations. Searches return fewer results compared to current functionality but the results are accurate and all of the searches seem to be working.

**Comment by mmiddaugh** [comment]
this work was reverted in [#20742 Revert "Facility/feature/34765/api parameters"](https://github.com/department-of-veterans-affairs/vets-website/pull/20742) following complaints from users. Some searches are not returning any results without multiple zoom-outs
