### ISSUE TITLE
Add Amanda to Prod Email Distribution Lists

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#34768]
## Background
For Chapter 31, we are sent a daily report that is also emailed to the Regional Offices.
For Dependents Applications (686/674) we receive an email notification every time there is a "silent failure".

We should add Amanda to the email distribution list for these emails.

## Considerations
- Please be sure to use Amanda's VA email and not Amanda's GCIO email as some of this information is sensitive.

## Tasks
- [x] Update the Chapter 31 report mailer and add Amanda's email to the list
- [x] Update the 686/674 silent failure notification and add Amanda's email to the list
- [x] *Stretch goal*: remove staging email notifications from the Chapter 31 report
- [x] Update any corresponding specs

## Acceptance Criteria
- [x] Code and tests have been implemented
- [x] A PR has been requested for merging
