### ISSUE TITLE
[FE] Custom Date Range Filter not rendering results [BUG] 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34767]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Overview
Custom date range filter doesn’t work as intended.  When filtering for events from Jan 1-16, it finds nothing, even though the All upcoming view shows events for Jan 5, 6, 11, and 12. 

### Tasks
- [ ] Review "custom date range" filtering and validate results are yielding as intended
- [ ] Test locally to determine functionality
- [ ] Consult a11y team with any questions 
- [ ] Consult design on any questions 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Custom date range filtering rendering results as intended
- [ ] Close ticket when completed

**Comment by kelsonic** [comment]
PR merged + on staging, moving to closed
