### ISSUE TITLE
[BE] Modify AppointmentIdentifiersSerializer for refreshing pre-check-in data

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#34764]
## Description
vets-api/check-in module currently have `AppointmentIdentifiersSerializer` implemented for getting single `stationNo` & `patientDFN` to call CHIP/refresh-appointment endpoint.

For pre-check-in data refresh, CHIP/initiate-precheckin requires payload with all stationNo and appointmentIENs ([Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1641315257054400?thread_ts=1641315252.054300&cid=C02G6AB3ZRS) for reference)

## Tasks
- [ ] Modify `AppointmentIdentifiersSerializer` for getting all stationNo, appointmentIENs and patientDFN
- [ ] Modify CHIP service layer refresh_appointments method to get first stationNo & patientDFN from serializer

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by kanchanasuriya** [comment]
Existing endpoint in CHIP expects lastName & last4 to be sent in payload and the controller in vets-api receiving request from frontend for pre-check-in refresh doesn't have access to lastName & last4.  Implementation blocked until new pre-check-in refresh endpoint available in CHIP.

**Comment by sarahknoppA6** [comment]
Sarah to talk to Katie about the UUID endpoint ticket, and once that's available this ticket will also become unblocked

**Comment by kanchanasuriya** [comment]
Serialization changes not needed anymore
