### ISSUE TITLE
[FE] Past events ordering need to match production logic (reverse chronological order)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34766]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Overview
In review of O&E MVP it was identified that ordering of the event listing in Past events filter because it doesn’t seem to be in reverse chronological order as Production.

<img width="392" alt="Screen Shot 2022-01-04 at 5 13 45 PM" src="https://user-images.githubusercontent.com/70410912/148140957-3572dca2-9101-47ec-be77-0fedf6fac013.png">

### Tasks
- [ ] Ordering should match current production logic
- [ ] Test locally to determine functionality
- [ ] Consult a11y team with any questions 
- [ ] Consult design on any questions 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Ordering matches production logic (reverse chronological order)
- [ ] Close ticket when completed

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19810

**Comment by kelsonic** [comment]
Implemented + merged
