### ISSUE TITLE
[PM] My VA: Create error message matrix to track the various errors that occur on My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34772]
## Background
Sitewide Content team is working on the [Error Message dictionary ](https://design.va.gov/patterns/messaging-dictionary)and is requesting a list of errors for all VA applications.
We need to create an error message matrix for My VA (not including profile).

[Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1641331976245700)
[My VA Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md)
[Old Profile error matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/error-messaging/error-code-matrix.md) (for reference only)

## Tasks
- [x] Gather all known error messages coded for My VA
- [x] Create [error message matrix and store in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/error-messaging/error-message-matrix.md)
- [x] Provide to Randi Hecht via the [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1641331976245700)

## Acceptance Criteria
- Complete [list of error messages ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/error-messaging/error-message-matrix.md)coded for My VA is created and provided to Sitewide Content team

**Comment by hdjustice** [comment]
@tressaellen and @tmitchellgcio Hello there!  I created this **[error message matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/error-messaging/error-message-matrix.md)** from the My VA product guide.  I logged in to several staging users, but couldn't force any other error messages to appear (that were not environment related).  Can you take a peek and see if anything sticks out to you as missing or incorrect?
