### ISSUE TITLE
Update Research plan review page on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34782]
## Issue Description
The [Research plan review page on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) provides basic instructions and information to VFS teams who need to request a Research Plan review with OCTO-DE. Shane Strassberg with OCTO-DE has since taken over the process from Lauren Alexanderson. The page must be updated to include Shane's name, remove Lauren's name, and also reflect the new process outlined by Shane via Slack on 1/4/2022:

> If you didn’t know, I am taking over as research plan and convo guide approver for @ Lalexanderson (health care, she/her). I’m going to post and pin below a new process for VFS teams to submit their plans/guides to streamline and integrate with the existing research repo board. I understand that if you are not a VFS team and don’t have access to Github, you can still slack or email myself or Kevin Hoffman, your plans/guides for feedback and approval. This is a first pass at this process, so please let me know what works or doesn’t for you. Cheers!

> **New Process for VFS teams submitting research plan and convo guide.**

> 1. Researcher creates issue in new Proposed column in Research Repo Board.
> 2. Researcher adds research folder link to issue card, and summary of proposed research.
> 3. Researcher slacks link to issue to @ Shane Strassberg (if he’s out, then @ Kevin M. Hoffman.
> 4. Shane or Kevin goes to research folder and reviews research plan and convo guide.
> 5. Shane or Kevin edits the file to leave feedback in bold, makes a pull request and adds the researcher as a reviewer.
> 6. Researcher incorporates feedback, deletes comments and merges file back to master.
> 7. Researcher slacks Shane or Kevin that they have made changes and merged, so they can make approval.
> 8. Researcher then moves issue card to Current column on repo board.
> 9. After completing research, researcher adds key findings and moves issue card to Complete column.

> Note: If you don’t have access to Github or Slack, you can email your plan/guide to Shane or Kevin

In addition, the [Research and Design section of Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) provides additional guidance and directions to VFS teams on how to undergo veteran research. It would be beneficial to VFS teams if the Research Plan Review touchpoint page on Platform Website linked to the different pages of the Research and Design pages on Platform Website where appropriate. This ticket will include syncing with @naomimarcussen for guidance on what Research and Design pages on Platform Website should be referenced.

---
## Tasks
- [x] Create a copy of the page in Documentation Drafts
- [x] Update the Research Plan Review touchpoint page to reflect Shane's new process
- [x] Remove Lauren's name, add Shane's name (possibly Kevin too)
- [x] Link Research and Design page to Research Plan Review Touchpoint page (sync with Naomi on what should link where)

## Acceptance Criteria
- [x] Shane Strassberg with OCTO-DE has reviewed and approved of the proposed changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by naomimarcussen** [comment]
@allison0034 In case we don't have an opportunity to sync, I'll leave my thoughts here. 
As far as other documentation to update with the latest info, you'll want to take a read through these docs and update anything that refers to these things that are changing.

[Research overview](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html)
[Research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

**Comment by naomimarcussen** [comment]
Here's the [VFS research process](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1635982647504/55fa21c511278746380673529b6db66447b3fb0d?sender=naomimarcussen8901) that we mapped out for reference. :)

**Comment by shiragoodman** [comment]
hey @naomimarcussen - this ticket is just to update the collab cycle touchpoint page for the Research Plan review AND possibly link to the Research & Design section of Platform Website (because I noticed we don't do that currently and it could be very helpful for VFS). @allison0034 will not actually be making changes to the Research & Design section of Platform Website. If that needs to be done, we can help take on that work but it will have to wait til next sprint. Let me know and we can get a ticket open. Thanks!

**Comment by naomimarcussen** [comment]
@shiragoodman No worries. I'll update the docs myself.

**Comment by shiragoodman** [comment]
@allison0034 the acceptance criteria is not complete so I reopened this ticket.

**Comment by allison0034** [comment]
I will add some, thank you
