### ISSUE TITLE
Remove "cloth" from mask references on COVID pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34788]
## Issue Description
Now that the CDC is recommending using K95 and N95 masks we need to remove the word "cloth" anywhere on our pages where we are talking about masks and face coverings. We also need to check the chatbot for any references.

## Tasks
- [x] Remove "cloth" from COVID pages (Selina)
- [x] Remove "cloth" form chatbot (Selina)
- [x] Review and publish Drupal pages (Randi)
- [x] Review chatbot (Randi)

## Acceptance Criteria
- [x] All live pages are updated
- [x] Chatbot is updated

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.
**Removed the holiday sentences**
Have questions before you get your COVID-19 vaccine?: http://preview-prod.vfs.va.gov/preview?nodeId=19578
About COVID-19 vaccines: http://preview-prod.vfs.va.gov/preview?nodeId=34627

**Removed cloth from Covid pages**
Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014
Mga karaniwang katanungan tungkol sa Coronavirus: Detalye na kailangan malaman ng mga Beterano: http://preview-prod.vfs.va.gov/preview?nodeId=16475
Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
These pages are all reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
