### ISSUE TITLE
[FE, Research] My VA - Payment Information and On-site Notification: Conduct research/usability testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34800]
## Background
We now have a good design and a functional prototype to use in the production environment for our VA users (will be turned on for the user's session only).  We need to conduct our research sessions to determine the usability of the functionality, as well as the value of the information in My VA.

## Tasks
- [ ] Conduct research/usability sessions with VA users, provided by Perigean
- [ ] Confirm feature flip is on for each user before their session
- [ ] Confirm feature flip is off for each user after their session
- [ ] Consolidate notes for each session

## Acceptance Criteria
- Research/usability sessions are completed with all attending users within the prototype
- Comprehensive research notes are captured for each session

**Comment by andaleliz** [comment]
Sessions completed on 1/14
