### ISSUE TITLE
[PM, Design] My VA - Payment Information: Update all documentation to include error states

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34809]
## Background

Technical discovery has been completed and shared for the Payment information section and On-site Notifications.  The team has agreed on the error states.  The design, FE documentation, test cases (and any other docs) need to be updated with this information.

**Note**: For On-site Notifications, we will not receive errors from VA Notify.  When there is an error, we will not receive anything to let us know there is an error for the user (we may receive the error but no user information).  In this case, we will simply not display any on-site notifications, as we will have not received any information, and no errors will be displayed.

## Tasks

**On-site Notification**
- [ ] Update any FE documentation to include statement that there will not be any errors displayed for On-site notification

**Payment Information section**
- [ ] Update any design documents to include error states for payment information section
- [ ] Update any FE documentation to include error states for payment information section
- [ ] Update test cases to include error states for payment information section

## Acceptance Criteria

- All documentation has been updated to include error state information on both Payment Information and On-site Notification

**Comment by andaleliz** [comment]
@hdjustice where can I see the error states that were identified in technical discovery? That'll help me estimate how much work there is to do here.

**Comment by andaleliz** [comment]
Also, am I just updating the designs, and FE is updating their own documentation? Or am I doing both? Thanks!

**Comment by hdjustice** [comment]
@andaleliz The tech discovery for payment info error states was not completed, so that is still pending.  I will move this ticket out to the next sprint.  We can move it up if it gets done quick and we have time to update designs.  I think FE can update FE Documentation.  I can always help with that too.

**Comment by andaleliz** [comment]
@hdjustice and @tmitchellgcio  I saw the info above RE errors for onsite notifications; how about the "you have 3 outstanding debts" notifications? Is it possible that we'd be able to get that debt info and not the recent payment? And vice versa?

I put this together, which assumes if one fails, they both fail:

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/204a42fe-bbc5-4b49-aca3-58a5609a04cb)

**Comment by tmitchellgcio** [comment]
@andaleliz yep it's possible one might fail and not the other. They are different calls

**Comment by andaleliz** [comment]
Yes @hdjustice those are the scenarios that occurred to me too.  Since we are showing a $0 balance debt message to _all_ users, and many may have never had a debt, I don't want to cause false alarm. I'm proposing that we say "We're sorry. We can't access some of your financial information right now. We're working to fix this problem. Please check back later." instead of specifically saying "we can't load your debt information".   I can totally see that statement triggering people to be like "my debt information?! I don't have any debt! what do they mean?"

Here's a mock-up of that scenario (debt API fails):
![image](https://user-images.githubusercontent.com/55992116/152584552-c870d5af-d589-4ce5-905e-eca4259cbf1b.png)

and then here's one if the payment fails:
![image](https://user-images.githubusercontent.com/55992116/152585483-b5d09b13-e605-49fd-aba6-1816f222bb92.png)

I'll put all of this in the docs too.

**Comment by hdjustice** [comment]
@andaleliz  I see that the text line for debt is different, reading "Your total VA debt balance is $0".  Did we get feedback on that?  Just curious, since it is way different from what we were thinking originally.  Thanks!

**Comment by andaleliz** [comment]
Yes, it is different - this is what Danielle and I landed on in office hours yesterday. I also [ran my approach to the debt failure error message by her](https://dsva.slack.com/archives/C01K37HRUAH/p1644000481838559), and she agrees with my approach.

**Comment by hdjustice** [comment]
Validated with Samara, all looks great!!
