### ISSUE TITLE
[AWS / IAM] Parameter store access for Team Orchid (Virtual Agent) for secrets management

### ISSUE THREAD

**Issue by jgacek** [department-of-veterans-affairs/va.gov-team#34804]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Team Orchid (Virtual Agent) are looking to maintain their own secrets on Parameter store. We would need an IAM group created for the team and for each of the developers on the team to get added to this group. The devs on the team who need to be added are
- @jgacek 
- @justin-trieu 
- @khathuynh-tw 
- @joehall-tw

The IAM group should have access to creating and modifying secrets in the parameter store with the following path
`/dsva-vagov/svc-gha-va-virtual-agent-user/`

## Background/context 
https://dsva.slack.com/archives/CJYRZK2HH/p1641333046151800?thread_ts=1640110554.061300&cid=CJYRZK2HH

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] create team for virtual agent 
- [x] create role for virtual agent team 
- [x] add team members to role/team 

## Acceptance Criteria 
- [x] Team Orchid can create and modify their own secrets within the above mentioned path

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@jgacek - A new path has been created in Parameter Store. A group was created for your team with access to that path. For now, only your user account has been added to that group. 

The path is: `/dsva-gov/vfs-virtual-agent/`

Please test to verify that you can manage secrets in that path. Then, we will add the other team members.

**Comment by jgacek** [comment]
When trying to create a new secret in parameter store I received this error
<img width="1207" alt="Screen Shot 2022-01-18 at 4 18 48 PM" src="https://user-images.githubusercontent.com/9095250/150028379-e1192ca5-2434-4499-9169-be70ac313ece.png">
<img width="894" alt="Screen Shot 2022-01-18 at 4 18 57 PM" src="https://user-images.githubusercontent.com/9095250/150028392-6c11e0c5-27a8-412c-a866-14fb401e9f2b.png">

**Comment by jbritt1** [comment]
> When trying to create a new secret in parameter store I received this error <img alt="Screen Shot 2022-01-18 at 4 18 48 PM" width="1207" src="https://user-images.githubusercontent.com/9095250/150028379-e1192ca5-2434-4499-9169-be70ac313ece.png"> <img alt="Screen Shot 2022-01-18 at 4 18 57 PM" width="894" src="https://user-images.githubusercontent.com/9095250/150028392-6c11e0c5-27a8-412c-a866-14fb401e9f2b.png">

Please use the following path instead:
`"Resource": "arn:aws-us-gov:ssm:us-gov-west-1:008577686731:parameter/dsva-vagov/va-virtual-agent/*"`

**Comment by jsgarmon** [comment]
noticed you're using `dsva-gov` instead of `dsva-vagov`

**Comment by jgacek** [comment]
Using `/dsva-vagov/va-virtual-agent/*` worked. Please ignore the error on my last comment

**Comment by jbritt1** [comment]
Does @joehall-tw have an AWS account yet? Not finding him anywhere.

**Comment by jbritt1** [comment]
> Does @joehall-tw have an AWS account yet? Not finding him anywhere.

Nevermind, I see it was approved but not yet granted. Will add that to my open pull request: https://github.com/department-of-veterans-affairs/devops/pull/10589

**Comment by jbritt1** [comment]
@jgacek has confirmed his new group memberships/permissions allows proper creation/deletion/updating of parameter store secrets in the prescribed path above, I have delivered AWS credentials to Joseph Hall who was the only member on the list that did not yet have AWS access (was approved in the referenced issue above), and have ensured all requested users have the same permissions. Closing. Please reopen if any issues arise or feel free to reach out in the #vfs-platform-support channel in the DSVA Slack workspace.
