### ISSUE TITLE
Add mobile immunization endpoint to nginx components 

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va.gov-team#34814]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Mobile team is looking to create a data metric for a specific endpoint mobile/V0/health/immunizations. Currently all of mobile/V0/health is lumped into one category. 

This will be used to derive the percentage of calls made to the lighthouse health immunization service that come back with no date or cvx code. A Datadog dashboard will be created using this data.

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

Suggested solution: In ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2 add 

`location ~ ^/mobile/v0/health/({{ api_mobile_health_components|join('|') }}) {
  set $application api;
  set $component mobile_health_$1;
  proxy_pass {{ nginx_config_plat_api_url }}$request_uri;
}`

and in ansible/deployment/config/revproxy-vagov/vars/nginx_components.yml add 

`api_mobile_health_components:`
`  - immunizations`

I Initially tried to just add health/immunizations to api_mobile_components but that did not work.
see previous PR: https://github.com/department-of-veterans-affairs/devops/pull/10508

---
## Tasks
- [ ] Add mobile/V0/health/immunizations endpoint to nginx component

## Acceptance Criteria 
- [ ] See mobile/V0/health/immunizations metric in Datadog

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by aherzberg** [comment]
Yes, this is complete. Sorry about that. closing.

**Comment by jbritt1** [comment]
> Yes, this is complete. Sorry about that. closing.

No worries at all, just was making sure before I closed inadvertently.
