### ISSUE TITLE
KPI Dashboards:   Adoption Campaign (Marketing Outreach/Promotion, Ongoing Training & Support Documentation Enhancements)

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#34822]
## Problem Statement 
Only about 1/2 of VFS teams with elligible products are on standardized dashboards and those that are are frequently unaware of the capabilities within the dashboards and the online "How To" documentation there to support them.  We need to get all elligible teams on and engaged with the dashboards and ensure they have the proper training and resource documentation to support their needs.  Many VFS teams are unclear on the value proposition of the dashboards and continue to create one off custom reports to support their needs.    

How might we get 100% of elligible teams on the dashboards, increase their engagement with the dashboards and provide easy to find supporting documentation and training resources?

## Hypothesis or Bet
If we better market the standardized dashboards by working directly VFS teams on access support, conduct additional and on-going  training sessions and make it easier to find online supporting documentation then we can expect to see more teams on the standardized dashboards and more engagement/frequency of use of the dashboards, resulting in more reports outs from the dashboards and less edge case/custom requests.  

## We will know we're done when... ("Definition of Done")
- [x] We have synced with each elligible team not currently on standard dashboards to assist in getting their product(s) added. 
- [x] We have completed additional training sessions and developed a cadence for ongoing support and training opportunities. 
- [x] We have implemented a process to keep documentation up to date and teams aware of updates/changes accordingly.
 
## Known Blockers/Dependencies 
- VFS teams engagement

## Projected Launch Date
- Q1 2022

## Launch Checklist
- [x] VFS team outreach to those that are not currently on the dashboards
- [x] Online training documentation updated and easier to find/access.
- [x]  Data dictionary
- [x] Training session(s) completed
- [x] Ongoing support defined
- [ ] Document difference between data sources and metrics reported (example GA vs Grafana)

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**
https://va-gov.domo.com/page/514439234

* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
