### ISSUE TITLE
KPI Dashboards:  MVP Enhancements for Standardized Product Level Dashboards

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#34821]
## Problem Statement 
Platform Analytics has built a scalable MVP v1 for KPI dashboards for VFS teams with Forms, Content, and Search VFS products. The current data on the KPI dashboards does not tell the entire user journey (due to, but not limited to, the dashboard only containing Google Analytics and customer satisfaction data). Many KPI dashboard customers are also looking at the dashboards once a month, and some are not coming back to their dashboards more than once a month or sharing data directly from their dashboards in stakeholder meetings.  Many are taking data from standardized dashboards and adding with other datasets to create their own custom reports that provides all the data needed for key decision making.  

How might we iterate on the KPI dashboards MVP v2 so that more VFS teams are incentivized to use their dashboards for VA.gov product decision making more often?

## Hypothesis or Bet
If we iterate on our KPI dashboards using insights from our backlog, feature requests, and user research, then we expect to be alleviate customer pain points with incomplete data on their KPI dashboards and more VFS teams will request access to and engage more frequently with dashboards, minimizing the need to create custom reporting.  

## We will know we're done when... ("Definition of Done")
We completed a gap analysis of current standardized dashboards vs. edge case/custom dashboard requests to identify and prioritize new metrics and datasets and the dashboards have been updated to include some of the results of this research and the user research findings.   

## Known Blockers/Dependencies 
- Inability to standardize more complex data
- BI Tooling limitations

## Projected Launch Date
Ongoing throughout 2022

## Launch Checklist
- [x] Complete standard vs edge case gap analysis to identify new metrics and data sources
- [ ] At least 1 new data source has been added
- [ ] New metrics have been added 
- [x] Revised formatting and other feedback from user research has been completed
- [ ] Additional training and online documentation has been completed

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [N/A] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * KPI Dashboards
- [ ] Internal-facing: there's a updated [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: an updated [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [N/A ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch.  _- not changing front end code, will go through a separate QA process and testing before release_

### Documentation
* **`PRODUCT_NAME`**: KPI Dashboards
* **Product Outline**: [KPI Dashboard Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1586724953/KPI+Dashboard+Product+Outline)
* **User Guide**: [How to use VA.gov KPI Dashboards](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/How-to-use-VA.gov-KPI-dashboards.1521647678.html)
* **Read Me:  [KPI Dashboards Readme](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/KPI-Dashboards-Readme.1657995529.html)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: N/A

### Measurement

* **Success metrics**
[Standardized Dashboard KPIs](https://va-gov.domo.com/page/514439234)

* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by michelle-dooley** [comment]
Closing this Q2 epic, dashboard work will be completed as part of the ongoing services epic in Q3.
