### ISSUE TITLE
Dataset Optimization:  Discovery for Restructuring and Streamlining Domo & GA Datasets

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#34826]
## Problem Statement 
There are over 100 DOMO Datasets that are currently in use. This makes it difficult to troubleshoot, identify and manage the main datasets that are tied to critical dashboards. We need to streamline these datasets to either remove what is currently not in use or combine them where applicable. We will need a discovery phase to identify all of the datasets and determine which ones are critical and which ones can be discontinued. We need to also identify a better way to identify when a dataset has not been updated and/or missing data.  We need to explore if we can convert that the datasets to be parameterized or use a federated dataset from Domo.

How might we restructure or current datasets to be optimized, removed what is no longer in use and improve efficiency to allow opportunity to add more datasets/metrics to support continued iteration on the standardized dashboards.

## Hypothesis or Bet
If we clean up/restructure/optimize our current datasets we will become more efficient in managing our data, trouble shooting issues and adding new data to our dashboards to further engage VFS teams in their use.

## We will know we're done when... ("Definition of Done")
We have completed discovery around current datasets to identify and prioritize optimization opportunities.  Things to consider as part of this discovery include but are not limited to:
- [ ] Investigate federated data in Domo
- [ ] More streamlined/cleaner data sets
- [ ] Restructure Domo datasets to allow orchestration
- [ ] Create GA bulk hit dataset for teams
- [ ] Programmatically centralize GA events

## Projected Launch Date
Discovery to be completed in the first quarter with potential to implement some changes as such.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**
https://va-gov.domo.com/page/514439234

* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by obrienjulie** [comment]
Here's the problem statement...I couldn't update the main ticket.

There are over 100 DOMO Datasets that are currently in use.  This makes it difficult to troubleshoot, identify and manage the main datasets that are tied to critical dashboards.  We need to streamline these datasets to either remove what is currently in use, combine them where applicable or remove them.  We will need a discovery phase to identify all of the datasets and determine which ones are critical and which ones can be discontinued.  We need to also identify a better way to identify when a dataset has not been updated and/or missing data.  Can we convert the datasets to be parameterized or use a federated dataset from Domo?

**Comment by michelle-dooley** [comment]
Remaining work will be completed as part of KPI MVP Enhancements in Q2 2022
