### ISSUE TITLE
MHV Inherited Proofing (Main)

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#34838]
# Description
One of our long-term goals has been to migrate users to Login.gov from legacy CSP's.  Our initial pass will involve transitioning MHV users to Login.gov

# User Story (End-user)
**As a** user of government services
**I want** to utilize a modern, secure credential
**So that** I can safely access government services

# User Experience
## Acceptance Criteria (Eligible User)
- [ ] On login, check user for eligibility
- [ ] If user is eligible account is flagged as Eligible
- [ ] On next login, user is presented a [page/modal] indicating eligibility and can proceed or decline
- [ ] On decline, user is taken back to previous location
- [ ] On accept, user is presented with page explaining what will happen
- [ ] User is taken to Login.gov to create/sign-in with their account
- [ ] User is returned to VA.gov on a page explaining they have now linked their Login.gov account
- [ ] If user tries to login with MHV later, they are prompted to use Login.gov

## Acceptance Criteria (Ineligible User)

# Technical
## Acceptance Criteria
- [ ] All tasks in Frontend Epic completed
- [ ] All tasks in Backend Epic completed
- [ ] All tasks in Security Epic completed
- [ ] DAST Scan

# Documentation
## Diagrams
[Engineering](https://lucid.app/lucidchart/22532e14-fce5-438a-b309-70c17de6f3c4/edit?invitationId=inv_06c65a3e-b1e1-4303-8400-0d4ec0c4624a&page=~WnOTMH95Wx_#?referringapp=slack&login=slack)
[Front-End/Design](https://www.figma.com/file/mD5xNQCLBbsDC22LsHv8PP/MHV-Account-Transition-(Copy)?node-id=0%3A1)

**Comment by nsoutouras** [comment]
![va_inherited_proofing_20210817.png](https://images.zenhubusercontent.com/609e8d5b852e7429aab750c8/4d6c105e-e74e-44a8-9af8-4fa4b016a347)

**Comment by nsoutouras** [comment]
https://lucid.app/lucidchart/22532e14-fce5-438a-b309-70c17de6f3c4/edit?from_internal=true

**Comment by nsoutouras** [comment]
**question to login.gov:** what does login.gov need from va.gov when we send a verified user to login.gov
**question to MHV:** how do we call the API (need connection details, certs, schema, any other pertinent information)
**assumption:** login will still flow through ISAM after transition process is completed
**requirement:** va.gov will need to send PII to login.gov - what data does login.gov require
**assumption:** access to mhv api will be in place to obtain verification information
**requirement:** va/gov need to create an api, establish token system, for login.gov to use to obtain the PII they require
Should do: attempt to establish oauth for api to share data (may not be oauth at all)
**requirement:** need a redirect from login.gov back to va.gov upon success and failure and indicate that it was a success or failure.
requirement: Ops will help with establish secure network path for "login.gov inherit proofing"
**requirement:** va.gov to create isolated service for login.gov to call for user attributes - requirement of help from ops: implies proxy and load balance setup
**requirement:** va.gov to create entry in redis user model for the mhv verified response, not store in accounts table
**requirement:** va.gov will not block on frontend if backend call to mhv doesnt work
**question to @codyreinold-usds Cody:** if login with mhv but not eligible for login.gov inherited proofing, do we provide them with modal which then can show wizard?
       a. recommend: show modal to every LOA2 mhv user will allow user to dismiss modal but need the ability to re-prompt users
