### ISSUE TITLE
Fix link and outdated rate on birth defects and clothing allowance pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34832]
## Issue Description
We have a link and an outdated rate on 2 disability pages that need updating. 

At the bottom of the [birth defects page](https://www.va.gov/disability/eligibility/special-claims/birth-defects/), we have a link "View the current payment rates" but it is linking to an old legacy page. We need to change it to link to our current rates page. 

On the [VA clothing allowance page](https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/) we list the current rate as $841.36 but when you click the link to the special allowance page the number is different. We need to update the rate on the clothing allowance page to the 2022 rate of $891.00

We should also change any sighted language on either of these pages.

## Tasks
- [x] Update birth defects page (Selina)
- [x] Update clothing allowance page (Selina)
- [x] Review and publish pages (Randi)

## Acceptance Criteria
- [x] Current link and info are on live pages

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

VA clothing allowance: http://preview-prod.vfs.va.gov/preview?nodeId=895
Birth defects linked to Agent Orange: http://preview-prod.vfs.va.gov/preview?nodeId=894

**Comment by RLHecht** [comment]
Thanks @lunascoop. I published these pages. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
