### ISSUE TITLE
Map Medalllia Directories & Subdirectories to Products

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#34833]
## Issue Description
Utilize request documentation to build an ETL that maps directories and subdirectories to products in DOMO. These products will then be used as filters

---
## Tasks
- [ ] Obtain directories and subdirectories from survey requests from @jwoodman5 
- [ ] Create a product column in DOMO for Medallia, populate the product column based on URLs
- [ ] Add Product as a filter on the Medallia MVP

## Acceptance Criteria
- [ ] Product column has been added and populated
- [ ] Product has been added as a filter option to the DOMO Medaliia MVP
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Medallia survey implementation spreadsheet](https://docs.google.com/spreadsheets/d/1t8nOLU9Ej7OUo2N3JzaoGI_LDWn8iUTrTS2b-ADVtpw/edit#gid=231611291)

**Comment by jwoodman5** [comment]
@ianMcCullough-ob Since this ticket is still open, I'll add this update. Can you please map the following URLs (if not already) to `Content & Localization` ? 

https://www.va.gov/health-care/covid-19-vaccine-esp/
https://www.va.gov/health-care/covid-19-vaccine-esp/booster-shots-and-additional-doses-esp/ 
https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/
http://va.gov/asistencia-y-recursos-en-espanol  
www.va.gov/health-care/covid-19-vaccine-esp/vaccine-record-esp/
https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine-esp/  
https://www.va.gov/health-care/covid-19-vaccine-esp/about-covid-19-vaccine-esp/
https://www.va.gov/health-care/covid-19-vaccine-tag/
https://www.va.gov/health-care/covid-19-vaccine-tag/booster-shots-and-additional-doses-tag/   
https://www.va.gov/coronavirus-veteran-frequently-asked-questions-tag/
https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong 
https://www.va.gov/health-care/covid-19-vaccine-tag/vaccine-record-tag/
https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine-tag/  
https://www.va.gov/health-care/covid-19-vaccine-tag/about-covid-19-vaccine-tag/
https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/
