### ISSUE TITLE
Streamline Medallia Exports for DOMO

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#34830]
## Issue Description
Prepare developer desktop with documentation provided by Sarkis to be positioned to access the Amazon S3 bucket.

---
## Tasks
- [x] Open Your IT ticket
- [x] Obtain S3 login access from Sarkis
- [x] Request weekly export from Sarkis
- [x] Test and document the data append process

## Acceptance Criteria
- [x] Dev desktop has Python installed
- [x] S3 login credentials provided
- [x] DOMO Data append process is determined
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Per Amber, 3:00 PM, 2/16/2022
Requested! RITM 6351085

**Comment by ianMcCullough-ob** [comment]
GFE has been obtained, working on getting certs in order to pull from S3 bucket.

**Comment by ianMcCullough-ob** [comment]
Need to open a VA ticket to get AWS CLI installed, unable to install that myself on my GFE, need higher permissions.

**Comment by ianMcCullough-ob** [comment]
S3 access has been tested and works. Will export on Monday, July 25

**Comment by jwoodman5** [comment]
@ianMcCullough-ob I think this is complete. If you agree, you can close it. Thanks.
