### ISSUE TITLE
Setup financial status reports submission notification trigger

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#34843]
## Issue Description
When a veteran submits their financial status report they should receive an email notification confirming it's submission success.

---
## Tasks
- [ ] Create worker to build VA Notify email alert
- [ ] Initiate worker upon FSR submission

## Acceptance Criteria
- [ ] Veteran receives an email after successful FSR submission 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
