### ISSUE TITLE
Add configuration for FSR email notification

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#34844]
## Issue Description
Add the necessary configuration to be able to setup notification trigger and be able to turn feature on/off.

---
## Tasks
- [ ] Add VA Notify template reference to settings
- [ ] Add feature flipper for sending FSR notifications

## Acceptance Criteria
- [ ] Configuration for FSR notifications is in place
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
