### ISSUE TITLE
Implement Updates to Reflect QA Standards

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34851]
## Issue Description
Update Product Dashboard visuals to reflect the QA Standards

---
## Tasks
- [x] Experiment with visual designs for reflecting standards
- [x] Incorporate visual indicator on existing metric cards as appropriate
- [x] Incorporate standards compliance card (optional)
- [x] Update documentation to reflect changes

## Acceptance Criteria
- [x] Visual indicators are effective and accessible
- [x] Documentation has been updated to reflect new visuals and standards

**Comment by CBonade** [comment]
Documentation was updated today and the standards compliance card has been added to all dashboards. The compliance status is checked and recalculated every day at midnight EST on a schedule, and then is re-imported into Domo at 7am EST to ensure each work day starts with updated information.
