### ISSUE TITLE
[Design, FE] My VA: Update copy on My VA to align with Content direction

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34862]
## Background

Per comment on [ticket #33839](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33839), we should align better with the advisement from our Content partners.

- We need to update the header for "Claims & Appeals" to replace the ampersand
- We need to update the Health Care section for unread messages to reword and move the URL to different text

## Tasks

**Design changes**
- [ ] Update design documentation to reflect the changes needed
     - Update header "Claims & appeals" to read "**Claims and appeals**"
     - Update Health care section on the messages text
          - Replace [You have n unread messages] with new verbiage "**You have n unread messages. [Read your messages on My HealtheVet].**"

**Frontend changes**

- [ ] Update header "Claims & appeals" to read "**Claims and appeals**"
- [ ] Update Health care section on the messages text
     - Replace [You have n unread messages] with new verbiage "**You have n unread messages. [Read your messages on My HealtheVet].**"
     - The same URL used today will remain, but will only be linked with "**Read your messages on My HealtheVet.**" text part of the message

## Acceptance Criteria

- Design documentation is updated in accordance with Content advisement
- My VA page reflects the updates in accordance with Content advisement

**Comment by hdjustice** [comment]
Moving to next sprint - work is complete, pending Pull Request and approvals.  This will not be done before the end of the day (1/25)

**Comment by hdjustice** [comment]
Validated that the 2 updates outlined have been made (Claims and Appeals, and Health care messages verbiage)
![image](https://user-images.githubusercontent.com/92328831/151209888-7027d426-cf47-4ce8-92b3-e8f7c09491b5.png)

**Comment by hdjustice** [comment]
Revised ticket, since we are not yet ready to deploy the Health care section changes.  "Claims and appeals" is validated.  Thank you @tmitchellgcio !!
Health Care change is now captured in [Ticket #36076](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36076)
