### ISSUE TITLE
How to use the QA Dashboard

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#34860]
# Tasks
- [ ] Getting access
- [ ] Getting around the dashboard
- [ ] Reporting a problem with data
- [ ] Getting general help

**Comment by CBonade** [comment]
Have added sections to our existing QA Dashboard Documentation for:

- How to access the QA Dashboard
- Getting around the QA Dashboard
- Reporting a problem with data
- Getting general help

**Comment by pjhill** [comment]
This is available on the Platform website here -- https://depo-platform-documentation.scrollhelp.site/developer-docs/QA-Dashboard-Documentation.2013200394.html
