### ISSUE TITLE
Research & Implement QA standards KR Tracking

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#34887]
## Issue Description
In order to track how effectively we are progressing toward the completion of launching QA standards, we will be attempting to track the KR measurements that have been identified below:

---
## Tasks
- [ ] Research how we can measure KR1 - "findings from post-launch usability studies indicate > 70% comprehension of QA standards"
- [ ] Implement tracking for KR1
- [ ] Research how we can measure KR2 - "> 75% of VFS products are assessed against quality standards"
- [ ] Implement tracking for KR2

## Acceptance Criteria
- [ ] We've identified achievable methods for tracking these measurements
- [ ] We've implemented these tracking methods and are getting the expected data
    - [ ] OR we have adjusted/removed the planned KRs to account for issues we didn't anticipate

**Comment by JoeTice** [comment]
This ticket and related metrics are no longer valid or a priority - closing this ticket
