### ISSUE TITLE
[Loki] Increase the size of memcached instance in production 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#34886]
## Description
Loki is suffering from degraded performance in production. One of the causes appears to be limited available memory resources. It would be good to experiment with a single large memory pool to try and address this. 

## Background/context 
Please see [parent epic](https://app.zenhub.com/workspaces/platform-operations-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/34320) for additional background and context. 

## Technical notes
Machine type recommendation: cache.r5.4xl - 100GB RAM 

---
## Tasks
- [x] Bring up a new cluster alongside the current one instead of trying to change the sizes of the instances currently in use 
- [x] Point Loki at this new cluster 

## Acceptance Criteria 
- [x] Loki can utilize the new instance for Memcached in production 
- [x] And potentially: Memcached "out of memory" errors are no longer seen in production

**Comment by jbritt1** [comment]
Think we can consider this one done at this time if @mleclerc00 agrees.

**Comment by mleclerc00** [comment]
I think that was the general consensus for the time being.  The overall setup should be more stable having dedicated instances in elasticache as well as larger instances so they don't run out of memory and cause a cascading effect.

**Comment by jbritt1** [comment]
> I think that was the general consensus for the time being. The overall setup should be more stable having dedicated instances in elasticache along with being larger so they don't run out of memory and cause a cascading effect.

I know we aren’t totally out of the woods on Loki errors as a whole, but do you think we could close this one considering the scope / intention of this ticket in particular?

**Comment by jhouse-solvd** [comment]
There may be other things to do to optimize performance. Please see parent epic. 

The scope of this issue has been achieved. Closing.
