### ISSUE TITLE
[Loki] Increase the size of memcached instance in production 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#34885]
## Description
It would be good to experiment with a single large memory pool to try and address the degraded performance of Loki in production. 

## Background/context 
_Attach other relevant tickets_ 

## Technical notes
Machine type recommendation: cache.r5.4xl - 100GB RAM 

---
## Tasks
- [ ] Bring up a new cluster alongside current one instead of trying to change the sizes of the instances currently in use 
- [ ] Point Loki at this new cluster 

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
This is a duplicate. 

Please see #34886 (or [HERE](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/34886) in ZenHub)

Closing.
