### ISSUE TITLE
[FE] Profile: Update Staging to reflect radio/checkbox text solution discussed with Design System team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34890]
## Background
We met with the Design System team and Angela Fowler to brainstorm ideas for how the open text field should work in the checkbox and radio button groups for Sexual Orientation and Pronouns.  

The consensus is that the open text field and its label should be present by default, and for the benefit of users with cognitive issues or low threshold for tech frustration, we will add a visual cue that shows it is associated with the last radio button or checkbox in the list.

This would be accomplished by following nearly the same pattern in Kevin's original error state mockup, except that the line to the left would be in blue, and the error message would not yet be displayed.  That is also similar to the pattern shown in the Storybook for a Radio Button option with expanded content.
Since this would be a change to the Design System, Christina will mock up in Sketch and Adam will put it on Staging so that Angela can confirm it is accessible to screen reader users.

The updated edit state would follow the below pattern in both the radio button and checkbox button group components.
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/2f608d45-86d9-4bde-9655-d0659f34c8af)

And the error state would follow this pattern: 
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/1393fae1-73a0-4a0d-a02d-565ef1746383)

## Tasks
- [ ] Update the Personal Info states on Staging so that they follow the above mockups as closely as possible given any technical limitations.  
- [ ] Update the team when the changes are ready for review so that they can also be shared with Angela for accessibility review.

## Acceptance criteria 
- [ ] Personal Info states on Staging so that they follow the above mockups as closely as possible given any technical limitations.  
- [ ] Team is notified that the changes are ready to be reviewed

**Comment by MarciMcGuireGCIO** [comment]
I see this has been merged and is now on Staging.  Looks great, @adamwhitlock1 !!
