### ISSUE TITLE
Inject Optimize Script into a Test Feature 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34893]
## Hypothesis
Injecting Google Optimize script into a feature (rated disabilities: do Veterans want to use sorting) will cause some untenable flickering.

## Considerations
- Sitewide loading from the header will most likely not cause flickering
- There is a manual way to do this
- There is a way to test with tag managers as well

## Tasks
- [x] Obtain Optimize script from the Analytics folks
- [ ] Inject script into the feature in staging and detect the results (flickering or not)
- [ ] Document where this script should live i na GH document

## Acceptance Criteria
- [x] It has been determined that the script loading will or will not cause flickering on page load.
- [x] Details and instructions are codified in our GH folder

**Next steps**
- If flickering is not an issue, write a ticket for the actual sorting code
- If it does flicker, test sitewide implementation or another testing method (manual, GTM, etc)

**Comment by jason-gcio** [comment]
If flicker occurs on staging, it will (most likely) happen on prod...if not, still need to test

**Comment by drorva** [comment]
Please lmk when this is available on staging. I'd like to take a look at it.

**Comment by cohnjesse** [comment]
@drorva yep we will let you know as soon as it is on staging 😁

**Comment by jason-gcio** [comment]
@drorva - its in staging now, we can have some more convos on this....after planning
