### ISSUE TITLE
Create the Ineligible Login.gov Upgrade page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34900]
## Issue Description
This will be a dedicated page solely for My HealtheVet (MHV) users that are not eligible to transition to Login.gov seamlessly.  The eligibility standards are that they need to have Identity Proofed via the [outlined requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Design%20Documents/MHV%20Account%20Transition.md).

Create a Form Wizard to inform the Non-Eligible User on how to verify (Identity Proof) and other information about Verifying (Identity Proofing their account).

---
## Tasks
- [ ] Create a workflow (form wizard) to suggested which service provider the user should sign up with
- [ ] Add content to step through the Identity-proofing workflow
- [ ] Add content about Identity proofing and its workflow

## Acceptance Criteria
- [ ] As an (ineligible) MHV user, I can complete a workflow that will suggest the Login.gov service provider credential
- [ ] As an (ineligible) MHV user, I can complete a workflow that will suggest the ID.me service provider credential
- [ ] As an (eligible) MHV user, I am automatically rerouted to the Eligible Login.gov Account transition/consent page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras this can and should probably be closed as a duplicate.  Reason: We merged the Ineligible & Eligible into a single page that will conditionally render information based on their eligibility.
