### ISSUE TITLE
[FE] Migrate Containers to the shared location

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34901]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
-[SPIKE ticket] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/31475)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.
Combine the HOCs in the containers folder into the same location where applicable 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] MIgrate and combine the containers folders to the shared level 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Just to note: It's looking like this will not be straightforward as first thought. I am breaking this down into multiple PRs for organizational purposes.

**Comment by mdewey** [comment]
Changing the estimate form 3 to 4
