### ISSUE TITLE
[FE] Refactor sessions

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34902]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Parent Spike] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/31475)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Ensure that both experiences are using the same logic (educers, HOCs, etc) for a handling session. When a decepency appears, favor the `pre-check-in` work. 

Refactor all of the separate demographics dispatches into one on day-of matching pre-check-in.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] refactor code to use the code peices
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
