### ISSUE TITLE
Create the MHV Account Transition Mockup

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34906]
## Issue Description
This ticket will track the Figma prototype that will need to be created for the MHV Account Transition.  Refer to the [diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Design%20Documents/MHV%20Account%20Transition.md) on

---
## Tasks (Screens to create)
- [ ] ~~Communications email to VA.gov page~~
- [x] Signed into VA.gov with MHV account
- [x] Modal (Eligible)
- [x] Modal (Ineligible)
- [x] Dedicated consent page to Login.gov (eligible to transition)
- [x] Login.gov Sign in/Create an account
- [ ] ~~Login.gov Verification process~~
- [x] Dedicated information page for identity proofing (not eligible for transition)
- [x] Success/fail page for the new Login.gov page
- [x] Nick review and update content

## Acceptance Criteria
- [x] I can see the Figma prototype to each of the screens outlined above
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
This will be blocked until the team can figure out a cohesive workflow

**Comment by AGarcia-Clarity** [comment]
Low fidelity/wireframes and workflow created, pushing to Amanda & Sam for review/changes.

**Comment by AGarcia-Clarity** [comment]
Cody requested some initial feedback with the wireframes.

- Wizard questions updated
- Content is updated (in place of skeleton content)
- Workflows are updated

**Comment by AGarcia-Clarity** [comment]
Placing this ticket in Review & Monitoring.  Creating a new ticket to reflect the changes requested by Cody & John R. for content/layout (FYI @nsoutouras )
