### ISSUE TITLE
Outreach & Events - Custom Date Range - Current time today instead of 12:01AM

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34912]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Overview
O&E data range filter issue in which you get NO results if the start date is today, needs to start date is today and filter using the current time from users 'today' instead of 12:01 am. If this use case isn't technically feasible, we'll need to start date to tomorrow as the primary option.

### Tasks
- [ ] Update custom date range to start with current time "today"
- [ ] Test locally to determine functionality
- [ ] Consult a11y team with any questions 
- [ ] Consult design on any questions 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Custom date range is rendering current events when "today" is selected 
- [ ] Close ticket when completed

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/19827

**Comment by kelsonic** [comment]
PR merged, going out to staging now
