### ISSUE TITLE
Increase Nearby Vet Center default radius

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34914]
## Issue Description
In #27870, we automated the listing of "Nearby" Vet Centers to 80 miles by default. Based on feedback from the field, this radius isn't large enough for some rural catchment areas. Until we are able to allow Vet Centers to customize this radius, we can at least increase the default so it serves more Vet Centers (and Veterans). 

## Current experience
![image](https://user-images.githubusercontent.com/55411834/148463391-2eab8cf3-1ab3-47b7-8ef1-8dbd161fccea.png)

---
## Tasks
- [ ] Increase default radius to 120 miles
- [ ] Add/update existing unit tests

## Acceptance Criteria

- [ ] Up to 5 nearby Vet Center locations within 120 mile radius will be displayed, in ascending order
- [ ] Vet Center locations are not duplicated.
- [ ] The generated "Nearby Vet Center" list should not include locations which are already associated with the location (such as outstations, Mobile Vet Centers or Community Access Points)
- [ ] If the VC’s specified in Drupal aren’t included in the Lighthouse search, we will not display them
- [ ] In the case where there are no locations at that radius, do not show the header
- [ ] Do not generate empty <img> tags for Vet Centers fetched from Lighthouse.
