### ISSUE TITLE
Home link breadcrumb missing on Event Pages

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34931]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Description
The breadcrumb is not correct once you leave the main outreach and events page - the home link no longer appears.  We'll need to add that breadcrumb and test in staging that it's applying the appropriate navigational experience back to home. 

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Tasks
- [ ] Home link add to event pages - ensure breadcrumb is present and working properly
- [ ] Test locally to determine functionality
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Event page breadcrumb to home link is working as intended 
- [ ] Local test are completed and show signs of success

**Comment by brianalloyd** [comment]
@kelsonic would this be something we can tackle today as well?  Would like to close out before EoS.  Thanks.

**Comment by kelsonic** [comment]
This has been resolved afaik ✅ 🙂  https://staging.va.gov/outreach-and-events/events/maintaining-balance-online-yoga-for-caregivers-0/
