### ISSUE TITLE
Create a Notifications Modal for MHV Transition

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34939]
## Issue Description
After a user signs in with the MHV service provider a Notification Modal will do provide information that is conditional on if the user is eligible to transition or not.

Eligible users: 
- Content relating to being eligible to transition to a Login.gov as they have been previously identity proofed
- A button that takes them to the Login.gov Transition page where they can consent

Ineligible users:
- Content relating to them not being eligible to transition to a Login.gov account but they should upgrade at some point because MHV is going away
- A button that takes them to the (dedicated) information page on how to verify their account, and other information about verifying

---
## Tasks
- [ ] Create a notification modal that only shows up if a user logins in with the My HealtheVet SP
- [ ] Conditionalize the notification modal to show the eligible & ineligible information to the user
- [ ] Conditionalize the notification modal to show the eligible & ineligible links for the user
- [ ] Ensure a11y and write unit tests

## Acceptance Criteria
- [ ] As a MHV user (eligible), I see the notification modal after signing in, with Login.gov information and a link to consent
- [ ] As a MHV user (ineligible), I see the notification modal after signing in, with information about why I'm not eligible and a link to more information
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
