### ISSUE TITLE
Platform website — Define intake and go-live processes for info on the Platform Website

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#34933]
## Problem Statement 

Since early 2021, the Platform Website publishing has been democratized — anyone on the Platform Crew can publish at any time, without any content or editorial support.  Democratized publishing succeeded in quickly populating the Platform Website with content, but contributors desire more editorial support, and customers have indicated dissatisfaction with docs.

_HMW modify the intake and publication process to provide:_
- _Platform Website contributors with more writing support?_
- _Customers with a more error-free, consistent UX?_

## User stories

As a Platform team, I want to get support from the Platform Content team so that I can publish good quality docs.

As a Platform Content team member, I want to know what Platform teams want support with.

## Hypothesis or Bet
IF writers collaborate more w/ Platform crew members while creating docs for VFS core tasks, THEN Platform website docs will have better context, organization, and demonstrate clearer alignment with said core tasks.

If we incorporate editorial oversight as products for core VFS tasks are being developed, then we will be able to both:
- relieve SMEs from also being a page's primary author.
- enable customers to extract info more quickly.

## We will know we're done with this discovery when... ("Definition of Done")
* Intake: There is a process defined for Content to intake support requests wrt to Platform website content
* Go-live: There is a process defined for Content to deploy the Platform website

## Known Blockers/Dependencies 
* Will need to validate process with a few Platform crew members
  * Validate = sentiment gut checking to make sure we're not creating a convoluted process
  * Platform crew members = selecting from those who often write/publish docs

## Projected Launch Date
Q3 -- Just need to complete Q3 - Task: Release activities 

## Launch Checklist

<details>

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. - **THIS IS BEING PLANNED FOR NEXT Q4, AS DISCUSSED WITH PO DURING CHECK-IN: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2085093522/Content+Mike+Chelen+running+notes**
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD - **NOT APPLICABLE**

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0) - **OUTDATED LIST - SHOULD OUR SERVICE PRODUCT BE INCLUDED IN THIS AT ALL?**
    * _List the existing product that this initiative fits within, or add a new product to this list._

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. - **THIS IS BEING PLANNED AS A SEPARATE INITIATIVE FOR Q3**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). - **THIS IS BEING PLANNED AS A SEPARATE INITIATIVE FOR Q3**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

</details>

### **DEFINITION OF DONE/ACCEPTANCE CRITERIA FOR Q3:**

**Completed during Q2**

- [x] Product repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website
- [x] Actual establishment of the processes of how our team supports other teams with content requests (just not documented)
- [x] Product outline for the Platform website, as a product: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2064613465/Platform+website+product+outline
- [x] A styleguide: https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide
- [x] User guide/"how-to" documentation of the process for platform publishing guidelines: https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines

**Completed during Q3**

- [x] DONE - Product outline for our team's content support services, as a product
- [x] DONE - User guides/"how-to" documentation of the process to request content support services from our team
- [x] DONE - Communications plan for content support services: Team of Teams updates, Demos, User Guides

**Other items**

- **PLANNED FOR Q4** - Usability testing for the process to request content support services
- **PLANNED FOR Q4** - End to end manual QA or UAT for the process to request content support services
- **ACCOUNTED FOR IN Q3** - Clearly defined success metrics
- **NOT APPLICABLE** - Automated testing running in CI/CD
- Not added to the list of VSP products (QA has new list)**: https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0
- Go/no-go with leadership

## Required Artifacts
<details>

### Documentation

* **`PRODUCT_NAME`**:

Platform website [repo directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website)

* **Product Outline**: 

- Platform website: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2064613465/Platform+website+product+outline
- Platform content support services: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2261155943/Product+outline+-+content+support+services

* **User guides**:
- General support: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2262794259/Request+Platform+website+content+support
- Support to deploy: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2263187457/Submit+content+edits+on+the+Platform+to+be+deployed

**Comment by vbellissimo** [comment]
Closing this roll-over initiative per conversation with PO (Mike Chelen) during sync on 7/27/22; Also presented this review as part of Go/No-Go on 7/19/22.
