### ISSUE TITLE
Create the information page for Login.gov (Eligible/Ineligible)

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34945]
## Issue Description
This will be a dedicated page solely for My HealtheVet (MHV) users that **are eligible** to transition to Login.gov seamlessly.  The eligibility standards are that they need to have Identity Proofed via the [outlined requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Design%20Documents/MHV%20Account%20Transition.md).

---
## Tasks
- [x] Conditionally render content based on eligibility
  - [x] **Eligible** Update CTA based on Figma wireframes & allow transition process with other information
  - [x] **Ineligible** Update CTA based on Figma wireframes & add signups to Login.gov & ID.me
- [x] Add Identity provider wizard
- [x] Ensure buttons navigate user to proper place
  - [x] Transition (verify with BE team to see if we need another route for this?)
  - [x] Dismiss (should allow a user to go back to where they were originally *maybe History API?)
  - [x] Login.gov/ID.me buttons (should use the `signup`, verify w/ BE on what should happen if they are already logged in)
- [x] Add the breadcrumbs to allow users to escape early
- [x] Grab data User model (`v0/user`) to ensure eligibility

## Acceptance Criteria
- [ ] As an (eligible) MHV user, I can read more information and start the Login.gov transition process
- [ ] As an (ineligible) MHV user, I can read more information about creating a new account (ID.me/Login.gov), use a wizard to find out which trusted partner to use

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
