### ISSUE TITLE
Update AuthApp for Login.gov Account Transition failures

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#34948]
## Issue Description
For an eligible MHV user, after going through the 'Create an Account' workflow on Login.gov, on failure (needs more definition/clarity) this page should provide more information on why the process failed, provide support, etc using the existing AuthApp page.

---
## Tasks
- [ ] Work with BE engineers to come up with appropriate error codes to be used
- [ ] Add appropriate error codes on FE (after verifying above) to the AuthApp
- [ ] Add content and troubleshooting steps for the Login.gov process failed

## Acceptance Criteria
- [ ] As an (eligible) MHV user, when I fail the 'Create an Account' workflow, I am dropped back on VA.gov with an appropriate auth failure and error code with troubleshooting steps
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
Closing until we have MHVIP go-live date
