### ISSUE TITLE
Create flipper features for Login.gov Account Transition

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34959]
## Issue Description
The new functionality of MHV Account Transition to Login.gov should be gated behind flipper feature flags and enabled/disabled so they can be tested thoroughly before rolling out the new feature.

List of items to be feature gated
- Dedicated Consent (sending data from VA.gov/Login.gov) for eligible MHV users
- Dedicated Identity proof information page for ineligible MHV users
- Notifications modal that provides informational content and links to above
- Dedicated Successfully transitioned to using Login.gov account page
---
## Tasks
- [x] Create a new flipper feature flag in vets-api and vets-website
- [x] Feature gate the above items

## Acceptance Criteria
- [ ] As a developer, I can enable/disable a feature flag to allow the MHV Account Transition (listed items) to be available to users
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kwoly** [comment]
PR in review: Identity owned flags documentation updated here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Identity%20Team%20Responsibilities/Flipper_features.md

**Comment by nsoutouras** [comment]
This was just adding to vets API, no content gated behind flippers at this time.
