### ISSUE TITLE
Create and update Login.gov Account Transition metrics

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#34954]
## Issue Description
We want to collect metrics and statistics using available tooling (Google Analytics, Statsd, Datadog, etc.) on when eligible MHV users make it through the Login.gov account transition workflow.  Additionally, there should be other metrics to determine various data related to the Login.gov account transition workflow

---
## Tasks
- [ ] Add track events to how many eligible MHV users dismissed the notification (Notification modal/eligible) [FE]
- [ ] Add track events to how many eligible MHV users clicked to transition their account to Login.gov (Notification modal/eligible) [FE]
- [ ] Add track events on how many eligible MHV users clicked the 'Send Data to Login.gov' button (Eligible Login.gov Account Transition page/Consent page) [FE & BE]
- [ ] Add track events on how many eligible MHV users successfully upgraded their account to Login.gov (Login.gov Successful Creation page) [FE & BE]
- [ ] Add track events on how many eligible MHV users failed to upgrade their account (AuthApp page with specific error codes & criteria) [FE & BE] *should track in Google Analytics AND Sentry

## Acceptance Criteria
- [ ] The above tracked events are being logged in Google Analytics
- [ ] BE team creates new StatsD work
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@Kwoly Correct me if I'm wrong but don't we have this already in Google Analytics? Do we have a dashboard for this specific information?

**Comment by asg5704** [comment]
No longer required.
