### ISSUE TITLE
Create the Login.gov Account Transition success page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#34961]
## Issue Description
Create a dedicated page for MHV users who successfully transitioned to a Login.gov account.  This page should show relevant content on what can be done with the new account, other places it can be used (USAJOBs, etc), etc.

---
## Tasks
- [x] Create a dedicated MHV to Login.gov Account Transition (success) page
- [x] Update content on what can be done with the new account

## Acceptance Criteria
- [x] As an eligible MHV user, after completing the Login.gov signup flow successfully I can see a Success page that gives me information on what I can do with the new Login.gov account
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
