### ISSUE TITLE
[FE] Good | Bad Rating Component (Collaboration)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#34963]
#### High-level user story
As a Veteran I want to provide feedback in relation to my experience on VA.gov.  I want to express both positive and negative feedback in order to inform future updates to suggested pages, articles and app components.

### Background
[Current design](https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/)
Proposed design: 
![Screen Shot 2021-12-29 at 11 57 05 AM](https://user-images.githubusercontent.com/70410912/147694618-2a987329-f77d-4e6a-9862-af0362e45082.png)

[Current location of how do you rate component](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/includes/how-do-you-rate.drupal.liquid)

### Considerations
We need to modify the how-do-you-rate.drupal.liquid file to include only <div data-widget-type="how-do-you-rate"></div> where that div will be the mounting point for the static-page react app in vets-website. 

### Tasks
- [x] Modify how-do-you-rate.drupal.liquid to include only <div data-widget-type="how-do-you-rate"></div>
- [x] Ensure static-page react app mounts to the data-widget-type of how-do-you-rate

### Acceptable Criteria 
- [x] PW portion of the work is completed and handed off to Search + Discovery Team for action
- [x] Ticket is updated to support. 
- [x] Conduct a knowledge transfer with Search + Discovery Team for implementation actions

**Comment by brianalloyd** [comment]
@kelsonic created this ticket to account for the work done in support of the Good/Bad component and knowledge transfer.  Closing in support.
