### ISSUE TITLE
[UI] Error Message Design and Content for Invalid/expired Short URL

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#34960]
# Description
As a Veteran, I want to be notified that I can't check-in online if I click on an invalid/expired URL.

# Tasks
- [ ] Review other error messages to see if any can apply to this scenario as well. 
- [ ] Document or create wording and styling for this error state 
- [ ] Talk to Kristen, who is working on check-in text messages/error message source of truth
- [ ] Review with content (if necessary)

# Acceptance Criteria
- [ ] Add scenario and final wording/styling to source of truth
- [ ] Share with product, UX, and engineering teams
- [ ] Make sure the final wording/styling are in a FE ticket

**Comment by julieadair1** [comment]
1. If link is expired, they'll be redirected to a va.gov page - Question: Do we have an error message when this occurs?

**Comment by kristenmcconnell** [comment]
Need to update this ticket to cover all error messages/experiences when the Veteran will receive a URL, but shouldn't really continue on in the check-in experience. Connect to #32782 (FE ticket).

**Comment by julieadair1** [comment]
Will need a resource from BE to assist with this.

**Comment by jparker0425** [comment]
@kristenmcconnell... added Slack thread to the description where the decision was made to create a single page with general content to cover any of the discussed use cases.

**Comment by julieadair1** [comment]
![image](https://user-images.githubusercontent.com/90644663/153593785-e656b531-958f-4b59-b6d2-962236071633.png)

**Comment by julieadair1** [comment]
![image](https://user-images.githubusercontent.com/90644663/153593874-302b07f3-f414-4aad-97fd-75a0ad3d9924.png)

**Comment by julieadair1** [comment]
@kristenmcconnell  - you are referring to this error message ^^^ correct?
If so, this is what we should use for all use cases.  I can open the FE ticket.  
cc: @jparker0425

**Comment by kristenmcconnell** [comment]
We also have [this design](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/zx2EEb4), which wasn't implemented. This ticket is to think through which message should be used. Is the one that you showed only when something fails past the URL part?

**Comment by kristenmcconnell** [comment]
The difference is the actions that the user should take. If they click an old URL, do we want to direct them to try again or just send them to a staff member?

**Comment by ytsaoca** [comment]
Content brainstorming
@niradatta1 ![Screen Shot 2022-02-15 at 10.25.12 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/8fdb8e30-dc64-4eea-9d60-6d404019d361)

**Comment by niradatta1** [comment]
@ytsaoca I made a new  content suggestion in the Sketch file (link below),  based on a plain language assessment. I was unable to attend content office hours, so feel free to update and run it by Danielle if we need to. Otherwise, I think we may be able to convert this into an FE ticket, if all of UX is aligned. Thanks! https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/oYE7lex
'cc @kristenmcconnell

**Comment by ytsaoca** [comment]
Updated:
![Link Expired_1 4](https://user-images.githubusercontent.com/90633685/154995456-166ba359-ea52-4a9a-b879-eafea8ac74f2.jpg)

**Comment by ytsaoca** [comment]
1. if the veteran revisits the URL on the same day : appointment details page without the "back" link: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/rbmZLbD
2. if the veteran revisits the URL after that time, all we know is that the short URL doesn’t exist: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/GyWWJL/a/oYE7lex
