### ISSUE TITLE
[FE] [BUG] back button breaks dynamic routing

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34965]
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

When the clicks the back or back in the browser, the dynamic routing gets lost and the application breaks. 

This for both day of and pre-check

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Update the back button to update the form routing
- [ ] Address using the browser back button
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
