### ISSUE TITLE
Update COVID pages with newest booster content 1/7

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34979]
## Issue Description
We updated content on our [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) and [boosters and additional doses](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) pages with the newest information on 1/7. We also need to get this text translated and update the chatbot.

## Tasks
- [x] Input new booster content (Danielle)
- [x] Review and publish (Randi)
- [x] Send text to translators (Randi)
- [x] Update chatbot (Selina)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish translated pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] English page with updates is live
- [x] Translated pages with updates are live

**Comment by RLHecht** [comment]
@lunascoop I also just published Danielle's most recent changes to the vaccines and booster pages with updates to 5 months. Can you please take a look if we can update these pages without resending to the translators? I think we should be able to. We'll also need to update the chatbot.

**Comment by RLHecht** [comment]
@lunascoop here are the newest translations.

[https://app.zenhub.com/files/133843125/81f7bca8-da3c-435d-b6f3-b894dbf3ed15/download](https://app.zenhub.com/files/133843125/81f7bca8-da3c-435d-b6f3-b894dbf3ed15/download)

[https://app.zenhub.com/files/133843125/e82f69bb-47d7-46ad-9f02-79de17a768bd/download](https://app.zenhub.com/files/133843125/e82f69bb-47d7-46ad-9f02-79de17a768bd/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

- Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
- Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394
- Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
- Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408

**Comment by RLHecht** [comment]
Thanks @lunascoop I published all of these. Moving to validate.

**Comment by RLHecht** [comment]
Pages are live and I sent the translations to Mateo's team. I'll open a new ticket if there are changes to be made.
