### ISSUE TITLE
Assess SME request and write content for indigent Veterans and unclaimed remains information

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34971]
## Issue Description

Stakeholder Tanekwa Bournes asked the sitewide content team to review a document to determine if the content should be added to our VA.gov pages. 

Document to review:
[https://app.zenhub.com/files/133843125/7ed99fae-bbea-4909-89c7-c000c59dff67/download](https://app.zenhub.com/files/133843125/7ed99fae-bbea-4909-89c7-c000c59dff67/download)

First we need to do an audit of our Burials and Memorials pages (as well as Resources and Support) to see where we address unclaimed remains. Then we should use our process for assessing stakeholder requests to determine how to proceed with the document. If we find that we should add this content to our pages, we need to determine where it should live and write the content in VA.gov's voice and style and following our plain language standards. 

## Tasks
- [x] Audit burial and memorial and R&S pages (Selina)
- [x] Assess word doc (Selina)
- [x] Write content to be added (Selina)
- [x] Review and edit (Patrick)
- [x] Copy edit (Randi)
- [x] Send to Beth for final review

## Acceptance Criteria
- [x] Content is in final draft to submit to Beth for review

**Comment by lunascoop** [comment]
@psanders86 I have written the content and updated related Drupal pages. They are ready for review.

**How to apply for a Veterans burial allowance:** http://preview-prod.vfs.va.gov/preview?nodeId=864
What I added: 
Expanded information block in What kind of burial benefits can I get? section and "at a VA national cemetery" to third bullet
Note to how to apply section
Link after note in What are the burial allowance amounts for a non-service-connected death if the Veteran was hospitalized by VA at the time of their death? section

**Schedule a burial for a Veteran or family member:** http://preview-prod.vfs.va.gov/preview?nodeId=861
Updated in-text links 
Added: Who schedule’s a burial for an indigent or unclaimed Veteran? Q&A
The information the stakeholder provided had little info about indigent Veterans. The minimal info that I added was gathered was from various resources. Some of the resources mentioned indigent and homeless Veterans together, but it seems there's a difference between the two.

Here are some sources:

- https://www.dignitymemorial.com/plan-funeral-cremation/veterans/homeless-veterans-program
- https://www.cga.ct.gov/2002/rpt/2002-R-0328.htm
- https://www.sci-corp.com/about/responsibility/military
- https://www.coshoctoncounty.net/veterans/indigent-burial/
- https://www.military.com/benefits/burial-and-memorial/will-va-pay-your-funeral-answer-may-surprise-you.html
- http://www.ongov.net/veterans/documents/2021VeteranIndigentBurialApplicationFillable.pdf
- https://www.google.com/search?q=under+authorized+VA+admission&sxsrf=AOaemvLiJxC01CERz8HDcjFv5_PG1skxlA%3A1643105785807&source=hp&ei=-c3vYbvWLfmgptQPt6euqAg&iflsig=ALs-wAMAAAAAYe_cCRYKmx_iZKpRwN7aiZ63XBrJtMVZ&ved=0ahUKEwj7tsCF1sz1AhV5kIkEHbeTC4UQ4dUDCAk&uact=5&oq=under+authorized+VA+admission&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEKABEIsDUABYAGDGAmgAcAB4AIABcogBcpIBAzAuMZgBAKABAqABAbgBAQ&sclient=gws-wiz (resource for what under authorized VA admission means)

**Comment by psanders86** [comment]
I made edits for style for to the unclaimed Veterans section. @RLHecht Please give this a final copy edit, thank you!

**Comment by RLHecht** [comment]
I copyedited both of these pages. Just noting again that there are changes to the burial allowance page that can't be published yet so if this is ready to go before then we'll have to take them out of Drupal before publishing.
