### ISSUE TITLE
[Debt Portal] Content spot-check for redesigned status cards

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#34989]
## Issue Description
We consolidated designs for the status cards in debt portal to mimic the cards created for MCP - we also incorporated payment plan information into these new cards. The cards have been reviewed by the DMC team for accuracy. We'd like a content spot-check to ensure that the content meets plain language standards. 

[The status cards can be found in this UXPin prototype.](https://preview.uxpin.com/b52fd08cb24226745f9d97041910a46c984ddc57?_gl=1*1m9uxro*_gcl_aw*R0NMLjE2NDE1ODY0NjEuQ2p3S0NBaUE1dC1PQmhCeUVpd0FoUi1obTg1M1F3aFRjbmhBdmMxVDZldGFIblVZNWdJNmhScFNGa3J3dEJON1BBODJLazBFdW15S09ob0M5cGNRQXZEX0J3RQ..#/pages/145870940/simulate/no-panels?mode=i) Please reach out to Riley if reviewing in a spreadsheet format would ease the review process. 

---
## Tasks
- [ ] Review the status cards in the provided UXPin prototype for plain language compliance 
- [ ] Comment on any status cards that need adjusted content

## Acceptance Criteria
- [ ] The status cards have been reviewed 
- [ ] Tag Riley on this ticket as a comment if any adjustments need to be made

**Comment by rileyorr** [comment]
@denisecoveyduc should we close this ticket since Troy isn't on the team anymore?

**Comment by denisecoveyduc** [comment]
@rileyorr Yep, let's close this one and just hand it over to the content team. If memory serves we were hoping Troy could take a quick look to catch anything in advance to speed up the review process for the content team.
