### ISSUE TITLE
[FE] remove the isEmergencyContact Flip

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#34994]
## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Remove the toggle for Emergency Contract feature toggle

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Remove from using the toggle
- [ ] remove from the FE code base
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
This is in staging and needs to be reviewed by the UX team 

CC: @niradatta1 @kristenmcconnell @ytsaoca @zach-park
