### ISSUE TITLE
Deploying Identity Broker AXE

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#34999]
## Problem Statement 
The tools that teams across the VA use facilitate every part of the development process. Managing tool access causes both frustration to individual customers and exposure as an organization to security vulnerabilities.

**How might we centralize identity verification while allowing customers easy access to the platform?**

## Hypothesis
A consolidated authentication point for the Platform to **manage access to tools** will improve security and simplify identity management.

## Definition of Done
We have chosen, validated, and deployed an Identity Broker (IdB) for use across our initial cohort of tools.

## Projected Launch Date
14 March 2022

## Launch Checklist
- [ ] 3rd party IdB options have been weighed
- [ ] IdB chosen
- [ ] IdB tested
- [ ] Reporting tools set up
- [ ] Go approval

#### Testing
- [ ] Sandbox app testing
- [ ] User validation

### Documentation
 - [**Outline**](https://vfs.atlassian.net/wiki/spaces/AMT/overview?homepageId=1911062699)
 - [**Discovery**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/1925283849/Discovery)
 - [**Decisions**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2022244361/Decisions)
 - [**Testing Plan**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2037022723/Testing+Rollout+Plan) 

#### Diagram
![IdB](https://images.zenhubusercontent.com/60099ba779174e24ae511332/d23b000e-992c-4b4d-b13d-a6d8590ac57c)

#### Measurement

- **Tool 1: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----

- **Tool 2: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----
- **Tool 3: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----
- **Tool 4: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution
