### ISSUE TITLE
Platform Console - Discovery/Research: Realign Testing Resources to Support Platform Console

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#34997]
NOTE - Due to the early stages of development on the Platform Console in Q1 2022, Mike Chelen recommended we make this assessment less focused on the platform console, and more focused on assessing the state of the products that we own as a whole.

## Problem Statement 
Currently we do not understand how the creation and adoption of a Platform Console in support of Platform Strategic Objectives will affect the various Testing Tools, Resources and Practices. Understanding these implications will have a major impact on how we setup our team's testing infrastructure and tools to support and achieve platform objectives.

How might we better understand the requirements and features of the Platform Console in order to better understand how to align our tools to most effectively support the Platform Console and achieve platform objectives?

## Hypothesis or Bet
We believe that by conducting discovery efforts and research efforts early in 2022, we can be in a better position to support platform objectives to get features into the Platform Console throughout the year.

## We will know we're done when... ("Definition of Done")
- We have an understanding of the business goals and anticipated technical implementation of the Platform Console
- We have an understanding of how we can align our team resources to support and integrate our tools and processes into the Platform Console
- We have an understanding of whether any major pain points can be resolved as part of this migration

## Known Blockers/Dependencies 
* Platform technical implementation

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

### ... documented?
- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
