### ISSUE TITLE
Remove references to "content brief" in Collab Cycle documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34993]
## Issue Description
The Sitewide Content team has requested that all references to "content brief" be removed from the Collaboration Cycle templates in github and on the touchpoint pages of Platform Website. The Sitewide Content team is undergoing personnel changes and currently does not have the capacity to create these artifacts for VFS teams. 

---
## Tasks
- [x] Review the following github templates for references to "content brief"
   - Design Intent
   - Midpoint Review
   - Staging Review
- [x] If "content brief" is found in any of the above templates, edit the document, delete "content brief" and submit the changes as a PR for someone on the team to review
- [ ] Once changes are approved, merge the PR to master
- [x] Review the following Platform Website touchpoint pages for references to "content brief"
   - Design Intent
   - Midpoint Review
   - Staging Review
- [x] If "content brief" is found in any of the above pages, create a copy of the document in Documentation Drafts, delete "content brief" and request a review from someone on the team
- [ ] Once changes are approved, edit the live touchpoint page and publish changes using scroll viewport
- [x] Identify if there are other references to "content brief" in any internal Collaboration Cycle documentation on Confluence

## Acceptance Criteria
- [ ] All references to "content brief" have been removed from Collaboration Cycle documentation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@chaseakirby can you please review the following pages. There should be no reference to content brief. Once you approve I can move live.
[Staging review GH ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/36382)
[Midpoint review GH ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/36381)
[Platform website midpoint review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2077524016/Allison+-+Copy+of+Midpoint+review)
[Platform website staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2077524032/Allison+Copy+of+Staging+review)

**Comment by chaseakirby** [comment]
@allison0034 The Platform Website pages look good!
I added one comment to the PRs, just asking if we should also remove the sub-bullet underneath the one that we are removing since it references the content of truth from line we are removing.

**Comment by shiragoodman** [comment]
hey there - I'm not sure where we landed, but the "content source of truth" artifact request should not have been removed from the Staging Review template. Sometimes teams don't update their designs for content, so our content specialist will need to see the source of truth for correct content if not all of it is visible in staging. Please also update to "content _source_ of truth" not "content of truth"

**Comment by allison0034** [comment]
@shiragoodman is [this](https://github.com/department-of-veterans-affairs/va.gov-team/pull/36544) correct? If so, should the midpoint match?

**Comment by shiragoodman** [comment]
@allison0034 i replied in the PR.
