### ISSUE TITLE
VBA taxonomy inventory

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#34998]
## Issue Description
To support Veteran VBA taxonomy research conversations, we need to have an understanding of the available VBA services mapped to (assumed) plain language label and associated tasks. 

---
## Tasks
- [ ] Create a table containing VBA services, plain language names and tasks. 
- [ ] Validate list and tasks with Alexis Bravo. 

## Acceptance Criteria
- [ ] We are able to use plain language terms and task-based scenarios when talking to Veterans about VBA services. 

---

VBA service | Plain language | Tasks
-- | -- | --
Applying for benefits |   | apply for health care, apply for dental care, apply for life insuance, request documents, apply for education benefits
Burial claim help |   | decide how and where to be memorialized, schedule and plan funeral/burial arrangments, apply for pre-need determination eligibility, learn about survivor benefits, get financial assistance for burial services, apply for a headstone, marker or medallion, apply for a presidential memorial certificate, apply for a burial flag
Disability claim help |   | apply for a disability rating, check the status of a claim, file a supplemental claim, request a higher level review, appeal to the board
eBenefits registration help |   | sign up for MyHealtheVet, sign up for eBenefits
Education and career counseling |   | apply for benefits, get educational and career counseling, choose how to use education benefits, get help finding a job, put military skills to use, get small business support, learn about VA work study, learn about on-the-job training and apprecenticeships, find Technology education courses
Education claim help |   | check the status of a claim, transfer benefits to dependents
Family member claim help |   | learn about survivors pension, learn about survivor/dependent compensation, learn about survivor education benefits
Help for homeless Veterans |   | find rent support, find housing options
VA home loan help |   | become a home owner, find accessible housing, refinance exising home loans, find housing options
Insurance claim help and financial counseling |   | plan for financial future, apply for life insurance
Integrated Disability Evaluation System assistance (IDES) |   | apply for a disability rating, check the status of a claim, file a supplemental claim, request a higher level review, appeal to the board
Pensions |   | apply for a pension, apply for supplemental income, learn about aid and attendance allowance, learn about homebound benefits
Pre-discharge claim help |   | apply for a disability rating, check the status of a claim, file a supplemental claim, request a higher level review, appeal to the board
Transition help |   | apply for SGLI Traumatic injury protection,
Updating direct deposit information help |   | sign up for direct deposit
Vocational rehabilitation and employment help |   | get help finding a job that suits a disability, get credentialing for employment, train for a new opportunity
  |   | find legal help
