### ISSUE TITLE
Expand instructions for "How to reassign tickets, or close invalid or duplicate staging review tickets"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34996]
## Issue Description
At the Collaboration Cycle staging review, issue tickets are opened for the team/product. However, it's possible that the issue found is not the responsibility of the VFS team it was assigned to.

Examples:
- issue tickets have been opened that should be reassigned to the Design System team (because the issue at hand was relevant to a Design System pattern or component) [Example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34872#issuecomment-1007795751)
- issue tickets have been opened that should be reassigned to Sitewide Content (because the issue at hand was relevant to  the site header) [Example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34874)

The [How to reassign tickets, or close invalid or duplicate staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1862139961/How+to+reassign+tickets+or+close+invalid+or+duplicate+staging+review+tickets) document already exists, however it should be expanded upon for clearer directions. In short, if it is determined that the VFS team who is originally assigned the issue is not responsible for the issue, the following should occur:
1. Remove the VFS team label from the ticket
2. Add the label of the VFS team responsible
3. @ mention the Product Manager of that team in the ticket and say:
> This Staging Review issue ticket has been reassigned to _______(insert team name) as your team has been identified as the owner of this component/product/piece of VA.gov. Please do not close this ticket until the issue has been resolved. If you have questions, please comment on this ticket. Thanks!
4. If the product label has also been applied to the ticket (currently not in place for most Collab Cycle reviews), remove the product label as well.

---
## Tasks
- [x] Add instructions to mention relevant Product Manager and inform of the ticket

## Acceptance Criteria
- [x] Governance Team members should understand the steps to reassign tickets to other teams
- [x] Other teams understand the origin of the ticket and the found issue
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 the changes look good. Please publish to the Platform Products and Services Confluence space and we should be good to go! FYI @chaseakirby
