### ISSUE TITLE
Create content and add virtual agent chatbot alert on contact us page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34990]
## Issue Description
The Virtual Agent Chatbot team needs to put an alert on the [Contact Us](https://www.va.gov/contact-us/) page as an entry point for the chatbot. We need to create the content for this and then add it to the page when they are ready for it to go to prod. Note that this alert will not be visible to all site users, so we will need to work with an engineer to create a react widget. Once we do, we need to create a new ticket to add the widget to the page.

See #33905 for the initial intake request.
Slack thread about react widget: https://dsva.slack.com/archives/C52CL1PKQ/p1641586927091000

## Tasks
- [x] Create content for alert
- [x] Create ticket for PW to create react widget
- [x] Create new ticket for adding react widget to page

## Acceptance Criteria
- [x] Content is ready to be placed in a react widget and new tickets created

**Comment by bethpottsVADEPO** [comment]
@RLHecht @SgardnerPMP Let's add this to the next sprint.

**Comment by lunascoop** [comment]
@psanders86 here's the draft alert. It's somewhat modeled after the coronavirus chatbot alert on the [coronavirus FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/).

**VA virtual agent chatbot**
You can also type any question into our VA virtual agent chatbot to get answers about VA benefits and services.
[Go to the chatbot]

I didn't want the alert to be confused w/ AskVA so I opted against using "ask" in the header (especially since the alert will likely be placed above the AskVA Q&A). And for the additional text, I added the "type any question type any question into our VA virtual agent chatbot" to also distinguish it from the AskVA tool.

**Comment by psanders86** [comment]
I'm good with this as written. Thank you!

**Comment by RLHecht** [comment]
One small edit:

VA virtual agent chatbot
You can also type any question into our virtual agent chatbot to get answers about VA benefits and services.

@bethpottsVADEPO This is ready for you. Once it's approved we can open a PW intake request for a react widget.
