### ISSUE TITLE
Cohort 1 Service Integration

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35000]
## Problem Statement 
The tools that teams across the VA use facilitate every part of the development process. Managing tool access causes both frustration to individual customers and exposure as an organization to security vulnerabilities.

**How might we integrate a secure and easy to use access management solution with existing tools without sacrificing security?

## Hypothesis
Deploying our centralized access management solution will provide a simple method for accessing tools without compromising security.

## Definition of Done
We have deployed our access management solution for between 1 and 4 services in our initial cohort.

## Projected Launch Date
14 March 2022

## Launch Checklist
- [ ] IdB deployed
- [ ] IdP deployed
Per Tool:
- [ ] Users & Roles defined
- [ ] Test with user pool completed
- [ ] Tool updated with access management solution

#### Testing
- [ ] Test user pool defined
- [ ] Test with user pool
- [ ] Feedback from user pool integrated
