### ISSUE TITLE
EXTERNAL: GET `/api/eligibility/documents`

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#35005]
## Background
We need to call the LGY `/documents` endpoint to get a list of documents associated with the Veteran (if they exist).

## Considerations
- May need to check with Kelli to see if this endpoint is ready for testing and if they have any test users who have docs associated.

## Tasks
- [x] Create a service object method that calls the `GET /api/eligibility/documents`
- [x] Add spec tests as needed

## Acceptance Criteria
- [x] Code and tests have been implemented
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
due by 3/3

**Comment by alsleaders** [comment]
Closing because PR is merged!
