### ISSUE TITLE
Configure Identity Provider AXE

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35002]
## Problem Statement 
The tools that teams across the VA use facilitate every part of the development process. Managing tool access causes both frustration to individual customers and exposure as an organization to security vulnerabilities.

**How might we allow users easy access to the platform while centralizing identity verification ?

## Hypothesis
A consolidated log in experience providing a high level of identity assurance for the Platform will **simplify account access** and improve identity management without compromising security.

## Definition of Done
We have chosen, validated, and deployed an Identity Provider (IdP) for use across our initial cohort of tools.

## Projected Launch Date
14 March 2022

## Launch Checklist
- [ ] Internal and external IdP options have been weighed
- [ ] IdP chosen
- [ ] IdP tested
- [ ] Go approval

#### Testing
- [ ] Usability with test users
- [ ] User validation

### Documentation
 - [**Outline**](https://vfs.atlassian.net/wiki/spaces/AMT/overview?homepageId=1911062699)
 - [**Discovery**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/1925283849/Discovery)
 - [**Decisions**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2022244361/Decisions)
 - [**Testing Plan**](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2037022723/Testing+Rollout+Plan) 

#### Diagram
![IdP](https://images.zenhubusercontent.com/60099ba779174e24ae511332/c7304003-0f7a-4537-bd32-1a2735f579b6)

#### Measurement

- **Tool 1: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----

- **Tool 2: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----
- **Tool 3: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution

-----
- **Tool 4: TBD**
	- [ ] Integrated with our Access Management solution
	- [ ] All permission boundaries are migrated to the Access Management Solution
