### ISSUE TITLE
[Discovery] Explore benefits & work involved in providing system notifications at platform level

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#35006]
## Issue Description

All modern browsers are able to display [notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) that are integrated at the system level, whether the device is a laptop, a mobile phone, or a desktop. Most browsers can even [push notifications to the system](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) even if the site isn't currently loaded. It may be worth exploring this as an option for `vets-website`.

Here is a page with working demos and linked code samples:
https://web-push-book.gauntface.com/demos/notification-examples/

Here are some questions we may want to answer for the discovery:

- What kind of benefits would this bring to va.gov users
- What technical work would be required in order to make it happen
- Are there any considerations to be made for different browsers and/or versions
    - Could we degrade gracefully if a feature wasn't supported in a specific browser or version
- (possibly after research) Do Veterans find this feature intuitive

In order to conduct user research we may need a simple app deployed to staging that can send out a few different notifications representing information that might be in a real notification.

**Note:** The `backend` label is on here since backend work would be required if we wanted to push notifications from a server. No backend work is required to send a notification from the frontend.

---
## Tasks
- [ ] _(optional)_ Demo app deployed to staging for delivering sample notifications

## Acceptance Criteria
- [ ] List of advantages/disadvantages is compiled
- [ ] Work estimate is provided for an MVP

**Comment by caw310** [comment]
Follow up from DSC meeting on 1/21. 
Demo in Monday design meeting - show how this would work on Windows or Mac
Demo to VA staff - Kevin and Brooks to discuss.
