### ISSUE TITLE
Console "Operation Docs" Documentation

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#35015]
## Problem Statement 

VSP/VFS teams have difficulty with support and deployment with the VSP platform. Deployment is complex; access to tools for deployment to environments are cumbersome, testing before deployment is limited, and applications are interdependent and grouped so deployment takes longer than usual. In order to have a system to develop this future console on, we must setup and build the foundational system, integrate user login and consult on the implementation of at least one feature, including design.

In order to ingrate features for developer customers, there will need to be operation docs to communicate governance, integration how-to's 

## Hypothesis or Bet
By creating an MVP it allows the Console UI and other teams to integrate features, including simplified deployment + other self-service features, VSP + VFS teams will improve speed to completion on tasks and increase satisfaction in working with the VSP Platform.

## We will know we're done when... ("Definition of Done")
When an MVP has an authenticated login experience for one user role, has one feature integrated and passes the <70% user satisfaction metric for end users.

## Known Blockers/Dependencies 
Limited budget, compliance issues like ATO and TRM that could delay decision making. Authenticated login could fail. Feature implementation could be delayed by another team

## Projected Launch Date
We expect the MVP of the Platform Console to launch the last week in March (end of the 1st quarter).

## Launch Checklist
[Requirements for MVP are here](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2042232849/Requirements+Gathering+for+MVP+-+Console+UI)

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`CONSOLE UI`**: [Currently on Confluence](https://vfs.atlassian.net/wiki/spaces/CUI/overview?homepageId=2019885206)
* **Product Outline**: [Product Discovery on Confluence] (https://vfs.atlassian.net/wiki/spaces/CUI/pages/1982922830/Discovery+-+Console+UI)
* **User Guide**: Draft Knowledegbase will be on Confluence

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _TBD_

### Measurement

* **Success metrics**: [Console MVP Metrics](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2028568705/Roadmap+OKRs+-+Console+UI)
* **Release plan**: _TBD_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by lhelmer** [comment]
Dupe

**Comment by lhelmer** [comment]
Dupe
