### ISSUE TITLE
Ad Hoc Messaging Solution + Use Cases [VA Notify Transition]

### ISSUE THREAD

**Issue by pcshah1026** [department-of-veterans-affairs/va.gov-team#35025]
- [ ] COVID-19 Informational Messages
- [ ] Flu Shot Reminders
- [ ] Women’s Health Messages
- [ ] Veteran Retention Messages (for PC & MH)
- [ ] Telehealth Check-In
- [ ] Mental Health/High-Risk Check-In
- [ ] Blood Pressure Check
