### ISSUE TITLE
Application Hosting and Deployment: Make Vets-API operational on the platform's new delivery infrastructure (EKS) in DEV 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35039]
## Problem Statement 
It is hard to decouple (and scale) Vets-API and related backend services that are deployed through the platform's legacy delivery infrastructure. And, developing and maintaining two delivery systems is hard. Also, Vets-API must migrate away from BRD before sunsetting the platform's legacy delivery systems. 

## Background / Context 
We believe that the platform's console vision is dependent upon a deployment API that the platform's new infrastructure delivery system gives us (ie Container Orchestration with EKS). 

Some great headway was made during November and December of 2021 through the Infrastructure and Console Services teams working closely together. There is already a basic "proof-of-concept" of the Vets-API application running in the EKS environment alongside the reverse proxy. The next major step is to work through security and integration aspects that would move toward the service toward being operational. 

## How might we... 
...transition Vets-API away from the legacy infrastructure? 
...make it easier to deploy Vets-API? 
...make it easier to manage changes to Vets-API? 
...make it easier to scale Vets-API? (ie more responsive to traffic demand) 
...support the platform's move to a micro-services architecture (for backend services)?  

## Hypothesis or Bet
We believe that this will:
...support the eventual sunset of the legacy BRD system
...make it easier to scale Vets-API
...support the platform's move toward a micro-services architecture for backend services
...make teams more autonomous in deploying Vets-API

## We will know we're done when... ("Definition of Done")

- [x] The build and deployment of Vets-API is automated with CI/CD 
- [x] Vets-API backend application is running in EKS in DEV
- [x] Public traffic to Vets-API in DEV is going to this application 
- [x] Vets-API is successfully connecting with external integrations (see #41253 for validation)
- [x] Vets-API logs being captured (Loki/Grafana)
- [x] Vets-API metrics are being captured (Datadog) 
- [x] Vets-API is stable and performant (ie able to handle expected traffic volume without service degradation)
- [x] Platform Architecture documentation is updated  (see #42075)
- [x] Platform Support documentation is updated (see #42075) 
- _Potential: Relevant updates to ATO_

## Known Blockers/Dependencies 
- Dedicated engineering resources from developers/maintainers of the Vets-API application. 

## Projected Launch Date
Q2 2022

### ... tested?

- [x] ~~Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.~~
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [x] ~~_(if applicable)_ New functionality has thorough, automated tests running in CI/CD~~

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] ~External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool~ NOTE: this product is only available to platform crew teams at this time 

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/35041).

### When you're ready to launch...
- [x] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. _(scheduled for 6/14 [link](https://vfs.atlassian.net/wiki/spaces/AP/pages/1951858742/Office+Hours+Agendas+and+Notes#6%2F14%2F22))_

### Documentation
* **`PRODUCT_NAME`**: Application Hosting and Deployment using Container Orchestration (EKS)
* **Product Outline**: [Application Hosting and Deployment using Container Orchestration (EKS)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: The Vets-API application behavior from the user perspective did not change as part of this initiative. 
* **Manual QA**: Able to reach the application via cURL; Verify successful deployment through ArgoCD [(details)](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/devops/11174)
* **Automated tests**: "N/A"

### Measurement [(details)](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/devops/11174)
- [x] There is an API available for deployment
- [x] Vets-API deployments are successful 
- [x] Vets-API is serving traffic 
- [x] Vets-API mimics the behavior seen in BRD 
- [x] Vets-API and ClamAV can be scaled independently of one another
- [x] Vets-API request latency is the same or better on the new infrastructure

* **Release plan**: [Platform Infrastructure: Make Vets-API operational on EKS: Release Plan](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/35041)

**Comment by jhouse-solvd** [comment]
Various next tasks were added today. Working with @ph-One to craft epics from those tasks. Expect updates soon.

**Comment by jhouse-solvd** [comment]
What are the next major milestones? or stages? phases? 

- [Vets-API/EKS] Establish a migration plan with stakeholders (in progress) 
- [Vets-API/EKS] Optimize the deployment for stability, resiliency  
  - #39681
  - #39679
  - #39685
  - #39683
  - #39681
  - #39691
- [Vets-API/EKS] Secure Kubernetes network to ensure appropriate isolation
  - #39688
  - _TBD_

**Comment by jhouse-solvd** [comment]
Good diagram provided by @madebydna 

> note: "it will be outdated soon once we remove the file provider and change our routing, but for now it should depict the status quo"


![api-routes.png](https://images.zenhubusercontent.com/5f5a5f39c4fbcc3da3615466/d08c23c4-cef3-4ae1-8bc8-9c40eb9f49b3)

**Comment by jhouse-solvd** [comment]
Closing.
