### ISSUE TITLE
[Research] Analyze Analytics on Demographic Reviews Impact

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35031]
# Description: 
Once pre-check-in has been released for awhile, look into what analytics we need/have that could help us determine if we lengthen the demographic review (to say every 1 month or every 2 weeks)? Then, do the analysis.

Prior desktop research ([report here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/frequency-demographic-updates.md)) showed that most places had patients reviewing information at every encounter. However, one article did state that "some patients really resent being interviewed over and over." The recommendation at the end of that research was to leave our 24 hour check (only reviewing demographic info once in a 24 hour period) for now, but to look at the analytics of how often this basic demographic information changes for Veterans. It could be that anything more than weekly, or monthly, would be unlikely to lead to additional changes to their information.

Patrick Bateman also suggested via [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1641826072083000)...
"I think there is another potential metric to look at as well: returned / undelivered mail. facilities are so concerned with making sure contact info is correct because they deal with a lot of delivery failures of postal communications and medicine shipments. probably really hard to study / track, but if we could demonstrate that asking for updates, say, every 1 month has no impact of delivery failures, i think we could make a compelling case to ask far less frequently."

# Tasks
- [ ] Create a list of analytics that would help answer the above questions.
- [ ] Determine if those analytics exist or not.
- [ ] Gather existing analytic information.
- [ ] Write up what we need for analytics that don't exist.

# Acceptance Criteria
- [ ] Have copies of existing analytic information ready for analysis. 
- [ ] Have a complete plan with criteria on what analytic information needs to be created with next steps on how to start making them a reality

**Comment by benbrasso-agile6** [comment]
@loripusey this is an interesting ticket. Not harm in leaving it here, but could toss it out if we're never going to get to this and it's value is no longer relevant.

**Comment by loripusey** [comment]
I feel like it is a higher-lever business decision to ask for review of demographics less frequently. Since this ticket is almost 2 years old, I am closing it.

**Comment by kristenmcconnell** [comment]
@klawyer I added this to our UAE Mural as an unprioritized item.
