### ISSUE TITLE
Add additional error codes for the AuthApp

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35052]
## Description
OCTO has asked that we present users with an error page explaining why their sign-in failed.  New UserAttributeError codes have not been accounted for in the FE (AuthApp) to display to the user with troubleshooting content.

## User Story
**As a** VA.gov user
**I want** to know why my sign-in failed
**So that** VA.gov Help Desk/Customer Support staff can troubleshoot my issues more readily

## Technical Description
When users fail to sign in with the following codes we should provide troubleshooting content to the AuthApp
UUID_MISSING_CODE = '104'
MULTPLE_CORP_IDS_CODE = '106'

## Tasks
- [x] Add troubleshooting steps for the above error codes
- [x] Create an additional component that renders auth errors (general refactor) for AuthApp usage
- [x] Clean up the renderError method (constants, etc.)

## Acceptance Criteria
- [x] I can see the error for code 104 (Missing UUID code) with troubleshooting steps
- [x] I can see the error for code 106 (Multiple Corp IDs code) with troubleshooting steps
- [x] An additional RenderAuthError component is created to handle errors

**Comment by codyreinold-usds** [comment]
The Veteran-facing page need not provide a descriptive error message, as we do not want to openly disclose exploitable information. However, we should have unique error messages to ensure that it is easily identifiable why the sign in was declined.
