### ISSUE TITLE
526ez | Evaluate analytics events for `va-additional-info`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35050]
## Description

The `va-additional-info` web components were recently added to replace the React component. The web component has analytics built-in, but form 526 included many unique events, so the `VaAdditionalInfo` react binding was used to continue using the possibly unique events.

Now we need to evaluate if these analytic events are indeed unique. If no additional event data is missing, compared to the built-in analytics, then the react binding can be removed and the `va-additional-info` web component may be used instead.

## Tasks

- [ ] Evaluate all `VaAdditionalInfo` react bindings in form 526 and switch to `va-additional-info` web component if the analytics are the same
- [ ] Manually check `window.dataLayer` for changes

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
After investigating, it was found that the `va-additional-info` web component did not include bindings to log analytic events. A ticket (#35769) for the design system team was opened

**Comment by Mottie** [comment]
Delaying this work until the design system team has the `va-additional-info` web component analytics working.

**Comment by Mottie** [comment]
We're still awaiting the work of adding analytics to the `va-additional-info` web component to get done.

**Comment by saderagsdale** [comment]
@Mottie is this still a valid ticket?

**Comment by Mottie** [comment]
I need to check... on my to-do list for today.

**Comment by Mottie** [comment]
Checked several 526 `va-additional-info` analytics events and found that:
- A total of 9 unique Google analytics events are being added
- Some events need to include specific form choices - form 781 vs 781a being filled, so these can not be removed
- These 9 unique events should be maintained (IMHO), so as to not interrupt any existing monitoring that our team may not be aware of.

Closing this ticket as done. No action required.
