### ISSUE TITLE
[Research] Create Optimal Workshop and Interactive PDF for MSA Moderated Study

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35057]
## User Story
- As an MSA, I want to be able to submit feedback on check-in from Veterans.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Creation of an Optimal Sort survey and Interactive PDF that includes the questions from this [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/Martinsburg-Staff-Moderated/conversation-guide.md). 

Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/Martinsburg-Staff-Moderated/Research-Plan.md) for this study as well.

## Tasks
- [x] Create the Optimal Workshop survey
- [x] Create the Interactive PDF
- [ ] Add assets to the specific test folder and conversation guide

## Acceptance Criteria
- [ ] Review assets with the team (particularly product)
- [ ] Talk to product about when to talk to pilot sites about this research

**Comment by kristenmcconnell** [comment]
[Draft Optimal Sort Survey](https://adhoc.optimalworkshop.com/questions/va0gv5g4)

We will need a separate survey for each clinic.

**Comment by kristenmcconnell** [comment]
[Draft PDF for review](https://app.zenhub.com/files/133843125/123caa2b-3252-41dd-9393-e70e74c6be98/download)

**Comment by kristenmcconnell** [comment]
Send to the team to review via [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1642446566014900).

**Comment by kristenmcconnell** [comment]
Updated [Optimal Sort](https://adhoc.optimalworkshop.com/questions/va0gv5g4) and [interactive PDF](https://app.zenhub.com/files/133843125/6e445f06-0fe1-4ab2-b2ce-6861d75aa064/download)based upon team feedback in Slack thread listed above.

**Comment by kristenmcconnell** [comment]
Moved the [Optimal Sort survey](https://g7cq2wku.optimalworkshop.com/questions/v76u41tu) to a new CivicAction account for now.

**Comment by kristenmcconnell** [comment]
Final launched survey URL: https://ows.io/qs/6t86mt8w. Do not click on the link, because it will capture your findings as a participant entry. But, this is the link that we can send to staff.
