### ISSUE TITLE
Revise data dictionaries to match dashboard redesign

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#35060]
## Issue Description
All data dictionaries supporting the  standardized dashboards need to be edited to reflect recent changes implemented in #33939.

#### Other tickets:
- Related to initiative work outlined in #34822

---
## Tasks
- [x] Revise [Forms](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Data-dictionary:-VA.gov-Forms-KPIs.1549009005.html) data dictionary
- [x] Revise [Search](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Data-dictionary:-VA.gov-Search-KPIs.1582727211.html) data dictionary
- [x] Revise [Content](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Data-dictionary:-VA.gov-Content-KPIs.1651867793.html) data dictionary
- [x] Proof revisions for clarity, readability, etc.

---
## Acceptance Criteria
- [x] All data dictionaries reflect the order and calculation of KPIs used on the newly revised standardized dashboards.
- [x] All definitions are clear and comprehensible for both technical and non-technical readers.

**Comment by chloedotbrown** [comment]
@pavanhothi I've completed changes on Confluence and pushed to the Platform website. Let me know if you have edits or catch any errors! Acceptance criteria is above, but feel free to reach out with questions as well.

**Comment by pavanhothi** [comment]
@chloedotbrown I've finished going through the data dictionaries and proofing the revisions. All data dictionaries reflect the new correct order and calculation of KPIs. The definitions are also all clear and understandable for technical and non-technical readers. Looks great and didn't catch any errors!
