### ISSUE TITLE
[Design] Optimize Low Vision Poster for different Sizes

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35062]
# Description
We previously created a poster to kickoff the check-in process that was optimized for low vision users. However, we only created it at [24"X36"](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/a/7yK5JgZ). Due to the space that certain waiting rooms have to hang posters, we also need 8.5" x 11" and 11" x 17" sizes.

# Tasks
- [x] Create 8.5"X11" poster in Sketch. Add it to this [section of this Sketch file](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/p/4E6A93C4-6C93-4AF6-A616-5B040D1F9BC5).
- [x] Create 11"X17" poster in Sketch. Add it to this [section of this Sketch file](https://www.sketch.com/s/478fdefa-c340-45e3-a3ae-738046eab97e/p/4E6A93C4-6C93-4AF6-A616-5B040D1F9BC5).
- [x] Export each poster as a PDF. 
  - Name the 8.5X11 file: letter-lowvision-poster.pdf
  - Name the 11X17 file: tabloid-lowvision-poster.pdf
- [x] Post the PDF files to [GitHUB](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral) and link them appropriately on that page.
- [x] Review the posters with Kristen.

**Comment by zach-park** [comment]
Please allow for the bleeding area (bottom edge: 1/2" and top, left, right edge: 1/4").

**Comment by nicko-amida** [comment]
The 8.5x11 and 11x7 low vision PDF posters are now [linked in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral).
