### ISSUE TITLE
Fix Form 686 Schema to Match Data Submitted by Form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#3506]
## Story
As a frontend engineer, I want to get the Dependents form submitted data structure to match in order for the previous teams work to function properly.

## Considerations
- In order to get the form 686 work from the Rainbows team working on staging we need to fix the form's submitted data structure so that it both matches the shape of the JSON schema for the back end AND is valid for the VA form system. This validity is determined by our schema object rules found [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects). 
- When submitting the rainbows team form 686 there is a validation error at the end of the form shown in the Redux form state object. This error is not coming from the validation of the data entered into the form but rather from the shape of the data structure in comparison to the shape of the JSON schema for the form. We need to determine where the inconsistencies are, aided by notes from the previous front end engineer on the project Erik Hansen, so that we can determine a path forward to fixing them.
  - [Notes from Erik Hansen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/NotesFromErikHansen.md)
- This ticket was amended to incorporate the investigative work in [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3505) ticket.

## Goal
- To be able to submit data without a validation error on the form 686 on staging
- Get us closer to a working form 686 on staging

## Tasks
- [x] Compare data structures
- [x] Document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/3506-summary.md) in GitHub inconsistencies between the form submission data shape and the shape of the JSON schema for the form.

## Acceptance Criteria
- [ ] The shape of the form data on submission matches the shape of the JSON schema object for the back end
- [ ] No schema invalidations errors get thrown when clicking the submit button

### Next steps
Connect with backend, test for staging

**Comment by micahchiang** [comment]
This is a link to the JSON Schema docs - https://json-schema.org/understanding-json-schema/reference/object.html#properties

Putting it here so it's easier to reference. Should come in handy, since more and more it seems we're going to be rebuilding the specific part of the 686c schema concerning location.

**Comment by jason-gcio** [comment]
Merged this into #4494 before closing
