### ISSUE TITLE
Communicate and meet with stakeholders about new education rates pages and process

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35075]
## Issue Description

Now that we are revisiting building the education rates pages on VA.gov like we have with disability and pension rates, we need to communicate this to stakeholders. We need to give them background on how we created modernized rates pages for disability, pension and health care already and that the education pages will look similar. We also need to communicate that once our pages are live, their rates pages will be redirected.

## Tasks
- [x] Email stakeholders to introduce idea of moving rates pages to VA.gov (Randi)
- [x] Meet with stakeholders to walk them through our process and what the pages will look like (Randi)

## Acceptance Criteria
- [x] Stakeholders are aware of the new rates pages and process.

**Comment by RLHecht** [comment]
Discussed the new rates pages in Beth's standing VBA meeting. Tammy is aware and we work with her once we have completed, approved rates pages to share. Closing ticket.
