### ISSUE TITLE
Staging test - 526 failed submission email

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35072]
## Issue Description
We are ready to implement the 526 failed submission email via NA Notify but first, need to test it in staging, 

---
## Tasks
- [ ] Using method outlined [in this thread](https://dsva.slack.com/archives/C5AGLBNRK/p1641840600018800), set up and complete test. 
- [ ] Reference [ticket with VA Notify team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30005#issuecomment-1009367295) to add utm code to link

Here is your template in prod for when you are ready and like Bev mentioned above don't forget to add in the UTM info to the link: https://notifications.va.gov/service/5bda137e-689e-4532-b3d2-2c81c0324331/templates/7e7719cb-f2c8-4856-9733-825e25f39dd8

## Acceptance Criteria
- [ ] Testing complete. Google Analytics info added to link.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
I was able to gain access to the VA notify Service.
I found the email template and was able to test it in staging from the rails console, here is the code:

```
nc = VaNotify::Service.new(Settings.vanotify.services.va_gov.api_key)
nc.send_email( email_address: 'michel.mcdonald@adhocteam.us', template_id: '7efb8dfc-f30c-4072-b900-ae393aa1114b', personalisation: {'first_name': 'Michel'})
=> #<Notifications::Client::ResponseNotification:0x00005577dd7c81c0 @id="82bc6100-d5a8-4094-b412-63e88bc18066", @reference=nil, @content={"body"=>"Dear Michel,\n\nWe’re sorry. Your Application for Disability Compensation and Related Compensation Benefits (VA Form 21-526EZ) didn’t go through. Something went wrong on our end.\n\nPlease fill out a new application and submit it to us by mail or in person.\n[Download VA Form 21-526EZ (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf)\n\n__To submit your application by mail,__ send your completed form and supporting documents (evidence) to:\n\nDepartment of Veterans Affairs\nEvidence Intake Center\nPO Box 4444\nJanesville, WI 53547-4444\n\n__To submit your application in person,__ bring your completed form and supporting documents (evidence) to your nearest VA regional office.\n[Find a VA regional office near you](https://www.va.gov/find-locations/?facilityType=benefits)\n\nWe apologize for the extra work this causes for you.", "subject"=>"We couldn’t process your VA.gov disability claim application"}, @template={"id"=>"7efb8dfc-f30c-4072-b900-ae393aa1114b", "uri"=>"https://staging.api.notifications.va.gov/services/5e5cded3-3c76-46a3-9eef-cb63589e76be/templates/7efb8dfc-f30c-4072-b900-ae393aa1114b", "version"=>2}, @uri="https://staging.api.notifications.va.gov/v2/notifications/82bc6100-d5a8-4094-b412-63e88bc18066">
```

Testing worked, so closing this ticket
