### ISSUE TITLE
[VAMC]  Research and update all Campus map locations for UR and naming [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#35079]
## Story
As a Veteran I need to have Campus map direct under the facility, so I can easily find it in the system and utilize the correct bread crumbs to return.

## Resources
CMS - Report area

## Tasks
After confirming with IA and PO update all Campus Maps under each main facility and update the name and Meta data to comply.
- [x] Determine page locations and if they will need redirects
- [x] Update page name to Campus map, and meta description to -System Name - Campus map
- [x] Upon approval and comms to Stakeholder, move campus map to new Parent Link

## Acceptance Criteria

**Comment by ltrombley** [comment]
Task #35079 - Research and update all Campus map locations for UR and naming - is Complete and moved to Validate
