### ISSUE TITLE
[Research] Pre-check-in for All Appointments for the Day at One Time - Research Plan and Conversation Guide 

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35109]
# User Story
As a Veteran, I want to be able to pre-check-in for all of my appointments at once that I have on a given day.

# Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

# Description
[Suggestion from site sent to UX by Stephen Barrs via Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1641844650048500).
"There was a suggestion that Veterans see VA as one thing, and that having multiple SMS and multiple workflow events for pre check in would not be the best experience for Veterans. It sounded like the idea was that there would be one pre check in workflow for all appointments in a day where all shared data (demographics, NOK, etc) would be collected once and then appointment specific data (mental health questionnaire, pulmonology questionnaires, etc) collected either with a series of pages or maybe sub-forms or some other novel way.  Have we asked Veterans how this might work best for them?  There are many complex challenges with combining pre check in into a single workflow per day.  I think if Veterans would really benefit from this we could figure out the tech challenges.     This is not a suggestion that we implement this, but an ask for your expert thoughts around the idea."

Create a research plan, list of outstanding questions, and conversation guide to validate this idea.

Initial list of outstanding questions
- What is the implications to appointment notifications?
- How would a Veteran navigate through all these different tasks? Should we look into uk.gov's task list again?

# Tasks
- [ ] Create a list of outstanding and research questions
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create research plan (template in research checklist above)
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan and conversation guide to GitHub folder
