### ISSUE TITLE
[FE] On-site Notification: Create a separate feature flag for On-site Notification

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35108]
## Background
Currently, both the On-site Notification and Payment Information are associated with the same feature flag to turn it on & off for specific users.
We need to create a new feature flag and associate it with the On-site Notification feature code, separating it from the Payment Info feature code.  This will allow us to deliver them separately in the future, if both initiatives are not ready for testing or production at the same time.

## Tasks
- [ ] Create new feature flag 
- [ ] Associate it with the On-site Notification feature code
- [ ] Ensure that both the On-site Notification and Payment Info features and be managed separately, independent of one another (being able to 'flip' each feature on and off separately)

## Acceptance Critiera
- A separate feature flag will be created and associated with the On-site Notification feature code, so that both initiatives (On-site Notification and Payment Info) can be managed separately.

**Comment by hdjustice** [comment]
Moving ticket to next sprint due to a failing Pull Request, Taylor is working through this, but it will not be done before the end of the day (1/25)

**Comment by tmitchellgcio** [comment]
PR now works, just waiting on approval
