### ISSUE TITLE
Prepare Columbus (FAC ID 757) for Cerner Launch

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35105]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)
Timeline for launch: Testing the month of Feb (possibly including last week of Jan)
Go live stuff: April 29 cutover for April 30th Go-Live

- Facility ID's: 
Columbus (a.k.a. Central Ohio health care) facilities
Zanesville VA Clinic - vha_757GA
Daniel L. Kinnard VA Clinic - vha_757GD
Marion VA Clinic - vha_757GC
Grove City VA Clinic - vha_757GB
Chalmers P. Wylie Veterans Outpatient Clinic - vha_757
Columbus VA Clinic - vha_757QC
Columbus 1 VA Mobile Clinic (archived node) - vha_757QA
North James Road 2 VA Mobile Clinic (archived node) - vha_757Q

### Considerations
- Follow the Cerner Runbook and prepare Columbus Facility for Cerner launch  
- This will need deploy to staging initially in order to be tested by the facility and our team
- Once fully tested and validated in staging, we'll prepare to deploy in production per runbook guidance

### Tasks
- [x] Follow the Cerner Runbook and prepare Columbus Facility for Cerner launch 
- [x] Test locally and setup a staging test environment so Facility admins can test.
- [x] Once validated in staging deploy to Prod per the runbook guidance 
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Work with VA Testing team to validate testing accounts 
- [x] Local test are completed and show signs of success
- [x] a11y considerations are implemented in support

**Comment by brianalloyd** [comment]
Closing out this ticket and linking to follow on tickets that are needed based on recent sync with the VA testing and evaluation team #35889 1. Creating a Feature flag for testing in staging 1. go-live support ticket when it gets closer to launch (April 30th is current projection) #35893
