### ISSUE TITLE
Create Operation Guidance for Platform Orientation - New Team Members

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#35127]
## Issue Description
Create detailed operational guidance for [ticket #33197](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/33197)

---
## Tasks
- [x] Create operational/internal guidance for Platform Products & Services/ Platform Orientation space on Confluence under the [New VFS Team Members](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members)
 - How to add people to roster and check off Acceptance Criteria in ticket, what the purpose of the ticket is, how do we intake these tickets
 - Who closes out the ticket - VFS team member or Platform?
 - How would the responsible person know the ticket can be closed
Are there other factors to consider?

## Acceptance Criteria
- [x] Platform (team tbd) is informed of the intake request and able to take appropriate action
- [x] Platform is able to follow guidance for responding to new Platform Orientation tickets
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Saraharaba8** [comment]
@chaseakirby Hi Chase. I need admin permission to edit on Confluence. Could you or @shiragoodman assist?

**Comment by shiragoodman** [comment]
@Saraharaba8 just to clarify, you aren't able to hit the edit button here and make changes to the page?
![image](https://user-images.githubusercontent.com/71330581/150419943-a8a27b72-728f-44ba-bde3-6a19c38f4857.png)

**Comment by Saraharaba8** [comment]
@shiragoodman Hi Shira. I actually don't have the icon at all at the top
![BC88B654-7473-4E6E-BF3B-65FDF0B6425D](https://user-images.githubusercontent.com/95157695/150422975-6af520b3-fa50-439c-83c7-f508a35e185a.jpeg)

**Comment by shiragoodman** [comment]
eek ok! I'll tag you in a post on Slack. another team has to give you access.

**Comment by shiragoodman** [comment]
@jimuhh that's a good question. Right now, because the ticket has our `governance-team` label, it shows up in our backlog. I've been reviewing the backlog once a week to check for new tickets. When I see one, I update the roster and check the box in the ticket.

**Comment by jimuhh** [comment]
Maybe we should add another custom label for these tickets and create a filter in Zenhub to surface them without scanning thru the backlog?

**Comment by shiragoodman** [comment]
@jimuhh I'd like to eventually transition this work over to another Platform team, so right now I am ok with the current process. however @chaseakirby let me know what you think as you should have a say as this involves intake.

**Comment by chaseakirby** [comment]
@shiragoodman @jimuhh I think that since there has been discussions around moving it to another team that it would be best to keep it simple. We can also currently perform a search by "Platform Orientation Template" and see all of them in the backlog. I think your idea Jim would be great to talk about it does end up staying with our team but if it is transitioned to another team they may have processes already built out that they would want to integrate it into.

**Comment by jimuhh** [comment]
ok. Sounds good. I will document as-is.

**Comment by jimuhh** [comment]
OK. More questions: 

1. Let's say we see a completed platform orientation ticket with a new user's info on it and we enter that into the VFS roster. **What is that information used for?** What do we (or anyone else) actually  _do_ with it?
2. If we receive a new team member's ticket before the new team leader adds their new team ticket, do we enter their info into roster assuming that whatever they are calling their VFS team is correct?

**Comment by shiragoodman** [comment]
Dang @jimuhh  - you're full of good questions.

1. The information is currently used for a few reasons. Analytics team uses it to track who accesses domo dashboard and other analytics info (that's why it was machine-readable in the first place), Service Design has used it to reach out to VFS team members for research initiatives. Other Platform teams have also used it to track down roles because not everyone puts their info in their Slack profile. 
2. It seems highly unlikely, but still possible. I think we should probably have a process defined for follow up. For example, we could comment on the ticket stating, 

> "Thanks for completing the Platform Orientation template. However, we are unfamiliar with the VFS team you specified you're a member of. Please have your PM or PO complete the New VFS Team ticket (with link) so we can update our records appropriately." 

What do you think?

**Comment by jimuhh** [comment]
@shiragoodman I like it. Thanks!

**Comment by jimuhh** [comment]
Hi @shiragoodman -- Here's a [working draft of the new team members page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members) in confluence.

**Comment by shiragoodman** [comment]
@jimuhh apologies for the delay, but I just provided feedback in the Confluence page. Please make the requested changes and let me know when it's ready for re-review.

**Comment by Saraharaba8** [comment]
> @jimuhh apologies for the delay, but I just provided feedback in the Confluence page. Please make the requested changes and let me know when it's ready for re-review.

Hi Shira thanks for your feedback. Making changes to my portion now

**Comment by shiragoodman** [comment]
@jimuhh @Saraharaba8 the page looks good to me. Please be sure to review the tasks and AC above. If you feel like the AC has been met, check them off and this ticket can be closed. FYI @chaseakirby

**Comment by Saraharaba8** [comment]
> @jimuhh @Saraharaba8 the page looks good to me. Please be sure to review the tasks and AC above. If you feel like the AC has been met, check them off and this ticket can be closed. FYI @chaseakirby 

Thanks Shira!
