### ISSUE TITLE
How can we define a product?

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35124]
# Description
In order to provide a dashboard that is tailored to a given product. First, we need to understand what a product is on VA.gov.

## Tasks
- [x] What is the definition of a product?
- [x] Are there different types of products?
- [x] Can we define a product in a way that we can automate?
- [x] Is this [product directory](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) useful?
- [x] Can we crowd-source the collection of products into a parse-able format?

**Comment by rjohnson2011** [comment]
Working on condensing all the tasks from above into a Confluence doc. Adding the points made from the team's Mural board discussion yesterday.

**Comment by rjohnson2011** [comment]
Still determining the proper definition of a product using the `vets-website` directory structure compared with the products list at https://vfs.atlassian.net/wiki/spaces/VAProducts/overview

**Comment by rjohnson2011** [comment]
Above questions have been answered in the following Confluence doc - https://vfs.atlassian.net/wiki/spaces/TTT/pages/2051178573/2022+Q1+-+Product+Documentation

Also contains links to all notes from QA team meetings regarding defining products.
