### ISSUE TITLE
EVSS Validation Review

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35135]
## Issue Description
Ensure useful UX for Veterans that run into errors with our products. 

---
## Tasks
- [x] Review [validation document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/Form526%20Validation%20Rules%20v1.2.docx)
- [x] Do we already handle these validations on the frontend? If not, should we?
- [x] Are we handling correctly, the errors that EVSS (and eventually lighthouse), throw?

## Acceptance Criteria
- [ ] Recommendations on UX changes we should implement.
---

**Comment by Mottie** [comment]
Here is a Google doc of the same PDF but with comments from both FE & BE developers

https://docs.google.com/document/d/141qH9dh5M6C_JxRxkSdS8hygxzi46LlqZh9scOgS5sA/edit

**Comment by vhenry07** [comment]
Document complete and linked. Additional documentation will likely transition to Lighthouse.
