### ISSUE TITLE
[Reverse Proxy] Route requests from dev-api.va.gov to Vets-API in EKS dev

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35134]
## Description
The reverse proxy needs to be configured so that it can send requests to Vets-API in EKS dev. This will allow for the testing and validation of the deployment configuration of Vets-API in that cluster. 

NOTE: **BEFORE this can be done**, it needs to be planned and announced to Platform Crew and VFS developers. 

## Background/context 
- There is a "proof-of-concept" version of Vets-API deployed to the EKS dev environment 
- The login flow for Vets-API depends on connecting to an external service (ID.me) that routes back through the existing reverse proxy in dev
- The idea is to configure the reverse proxy in dev to forward requests to Vets-API in EKS dev to allow testing and validation in dev before moving on to deploying Vets-API to other environments 

---
## Tasks
- [x] Plan a maintenance window for making this change 
- [x] Announcement to Platform Crew teams and VFS developers 
- [x] Update the [dev reverse proxy config ](https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-dev.yml) to point to the ALB created in #[35345](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35345)
- [x] Update network policies/security groups so that the Vets-API in EKS dev can forward requests back through the forward proxy in BRD (EC2 instances)  

## Acceptance Criteria 
- [x] Ability to log in to Vets-API in dev through ID.me

**Comment by jhouse-solvd** [comment]
It would be good to understand which webhooks are routing through the dev environment so that we know what the impact will be if those were to break. This information could be found in the devops repo, in the reverse proxy configuration. 

We might decide to break that investigation into its own issue. Discussing with the infrastructure team on the 1/13 daily mob session.

**Comment by jhouse-solvd** [comment]
The Infrastructure Team proposes to make this change on Wednesday. First, we will engage members of the Platform team to provide feedback and address any concerns. 

If this goes forward, there will first be an announcement to Platform Crew and VFS development teams. 

Will share a link to a thread in DSVA slack later today.

**Comment by jhouse-solvd** [comment]
The current reverse proxy configuration pointing to the Vets-API load balancer in dev is: 

`nginx_config_plat_api_url: http://internal-dsva-vagov-dev-vets-api-elb-172229860.us-gov-west-1.elb.amazonaws.com:3004`

The Infrastructure Team is proposing to change this to: 

`nginx_config_plat_api_url: http://internal-dsva-vagov-dev-vets-api-eks-alb-609678171.us-gov-west-1.elb.amazonaws.com:3004`

This will effectively **update the reverse proxy to send traffic for Vets-API in dev to the newly created load balancer** (ALB) in dev. This will in turn route traffic to the Traefik ingress in the EKS dev cluster. 

Note: The exact configuration line in the OpenResty configuration can be found [HERE](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-dev.yml#L17)

**Comment by jhouse-solvd** [comment]
This is planned for tomorrow, January 26, 2022. More information to follow.

**Comment by jhouse-solvd** [comment]
This is working. We'll follow up on any technical issues in #35618 as needed. But there are not any at the time of writing. 

Please see parent epic for continued work on testing and validation of this deployment configuration (security, load testing, etc)

Closing.
