### ISSUE TITLE
Adjust Stepchild Parent Question on 686c

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35141]
## Background
It was unclear, at the time of first development, whether the VA was specifically asking if the stepchild was the biological child of the spouse of the Veteran and we found edge cases where a stepchild might NOT be the biological spouse of the child but still entering into the Veterans household, thus potentially becoming a dependent.  They have provided us with guidance to perfect this question.

## Considerations
The Compensation line of business has clarified how they would like this portion of the form to work:

1. The term "Biological" should be added before "Parent" on each line that appears after "stepchild" is selected
2. We say "Date stepchild became your dependent" but what the business asks for on the form, is when the stepchild came into the household, and those dates could be different.  Became a dependent, as in you are paying for them but they have yet to move in.
3. We need to ensure that the box gets checked for "Yes" if the stepchild is indicated to be a biological child
4. While we are in there, we should double check that the field validation is working as expected.
5. [Mockup](https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/978172b0-e41d-4fdf-9c69-900043ad3e39)

<details>

<Summary>VA.gov form</Summary>

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/6a956cf6-0557-48ba-b9a2-f5f6b10c13bd)

</details>
<details>

<Summary>21-686c</Summary>

![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/449591f8-614f-4436-8033-34272e7bd9e8)

</details>

<details>

<Summary>FE example</Summary>

![image](https://user-images.githubusercontent.com/53826255/150191885-032f39bc-478f-457c-96ad-691471516fe3.png)

</details>

## Tasks
- [ ] Adjust the language for biological
- [ ] Adjust the language for when the stepchild entered into the Veteran's household: **"Date stepchild entered into the Veteran's home"**
- [ ] Ensure the box is being checked
- [ ] Field validation is behaving as expected.

## Acceptance Criteria
- [ ] TBD

FE 
- [ ] Language for biological is adjusted
- [ ] Language for when step child entered household is adjusted
- [ ] Field validation is behaving as expected

BE
- [ ] Box is being checked

**Comment by jason-gcio** [comment]
we may need to talk to Larry more on this: There is no rule in RBPS for this question

**Comment by sortizsh** [comment]
closing, duplicate
