### ISSUE TITLE
Auth Profile: Sprint 65 (Jan 12 - Jan 25)

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35151]
# Auth Profile: Sprint 65 (Jan 12 - Jan 25)

## PTO/OOO/Unavailable
- MLK Holiday - Jan 17 (Adam, Christina, Samara, Marci)
- Tom - OOO 1/19 for PIV card
- Christina - 1/12 & 1/13 helping My VA with research sessions for a couple hours
- Adam - Localization work - ~3 points
- Adam - 1/13 & 1/14 - attending research sessions for my VA in Taylor's absence

## Sprint Objectives
- Test Login.gov credentials
- Complete Personal Info Revision research report 
- Whatever progress can be made on FE/BE for Personal Information

### PM
- [ ] #33007 (still monitoring for feedback from VBA; took over from Liz; Jeremy responded but still doesn't have final info.
### Design - Christina (if time allows)
- [ ] #27979 - MM 1/20 put back into backlog
- [ ] #11053 - MM 1/20 put back into backlog

### FE - Adam (if time allows)
- [x] #31442 
- [x] #31446
- [ ] #19618

<hr>

### PM 
- [x] Complete any new prep steps for collab cycle (no ticket req'd for standard PM work)
- [ ] #35208 - 1/20 move to Sprint 67
- [X] Update bug reports for Radio Button Group and Checkbox Button Group - In the design system workspace,  [#604](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/604) and Radio Buttons [#605](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/605)  - NOTE - we are meeting with Design Council 1/22
### Design/Research - Christina
- [x] #34923
- [ ] #35219

### Design/Research - Liz
- [x] #35058

### FE - Adam
- FE work currently blocked by research synthesis, backend & VA Profile

### BE - Tom 
- [ ] #32847 - blocked pending specs
- [ ] #32848 - blocked pending specs

<hr>

### Design - Christina 
- [x] #35232 (NECESSARY?) [UXPin demo](https://preview.uxpin.com/e21218c405e4475d518bc209ffd66405a9633080#/pages/145359491/simulate/no-panels?mode=i)
### FE  - #35176

<hr>

### PM / PO
- [x]  #35216  - have some questions answered; Samara may need to shake the trees for more.

### BE - Tom
-  [x] #35211 - Can't access without PIV card; getting late day 1/20/2022

<hr>

### PM
- [x] #33229

<hr>

### FE - Adam
- [X] #35443 - Adam resolved an issue we previously thought was a problem w/design system component
