### ISSUE TITLE
[PM, FE] My VA - Payment Info: Capture any development changes resulting from usability testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35160]
## Background
We are conducting usability testing/research with veterans during this sprint.  If any suggestions result in changes to be made to the feature code, we will track them in this ticket.  We will create more tickets to implement the actual changes, as needed.

### Reference 
- [Front End documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)

## Updates that will be needed - Tickets to be created
- [ ] Complete development on changes that result from usability testing (additional details TBD)
- [x] Update logic for Benefit payments and debts section [(#35483)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35483)
- Only display section to user if **ANY** payments have ever been received by the user
     -  If user has **NEVER** received a payment from VA, we will not display any portion of this section (logic may be revisited in a future iteration)
- [x] Update Benefit payments and debts section - URLs on links, as described below (screenshot in Details) [(#35484)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35484)
- For Benefit payments and debts section
     - Within Payment details block, "View your payment history" link should be https://www.va.gov/va-payment-history/payments
     - Within in-line Outstanding Debt notification, "Manage your VA debt" link should be https://www.va.gov/manage-va-debt/your-debt 
<details>

![image](https://user-images.githubusercontent.com/92328831/149207417-46de1ac8-11a3-49c1-89fd-9f59b7ade933.png)

![image](https://user-images.githubusercontent.com/92328831/149207452-f728429d-1fe2-4fff-916e-cf48002c36bc.png)

</details>

- [x] Update On-site Notification - Debt notification - URL on link, as described below (screenshot in Details) [(#35485)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35485)
     - Within the On-site Notification - Debt notification (top of the page), "Manage your VA debt" link should be https://www.va.gov/manage-va-debt/your-debt
<details>

![image](https://user-images.githubusercontent.com/92328831/149207349-9352e889-43c4-45e5-a65e-fc8db174c7c2.png)

</details>

## Acceptance Criteria
- All changes, resulting from usability testing and are decided as a must-have for MVP, are captured and implementation will be scheduled.

**Comment by hdjustice** [comment]
Tickets created for changes that need to be done for URLs and display logic.  As we continue through the research synthesis, additional tickets may be created.  Closing this ticket.
