### ISSUE TITLE
Drupal work on Evidence Needed R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35175]
## Issue Description
As part of the work we are doing to add evidence, standard claim, and FDC information to our site that's missing for pension, DIC, and accrued benefits, we need to do do more work on our [Evidence needed your VA pension or DIC claim](http://preview-prod.vfs.va.gov/preview?nodeId=27770) before it's ready for stakeholders.

We will need to add more content to the Drupal page and take screen shots so that stakeholders can see the crosslinking we will do from the tier 1 page to the article.

## Tasks
- [x] Add content to Drupal page that Beth will provide (Selina)
[https://app.zenhub.com/files/133843125/63af1ecb-7f04-4367-8a90-3d874bee41d0/download](https://app.zenhub.com/files/133843125/63af1ecb-7f04-4367-8a90-3d874bee41d0/download)
- [x] Review (Patrick)
- [x] Copy edit (Randi))
- [ ] Take screen shots (Selina)

## Acceptance Criteria
- [ ] Page and screen shots are ready for Beth to share with stakeholders

**Comment by bethpottsVADEPO** [comment]
@lunascoop I uploaded to this ticket, above, the Word doc that I'm using for some of the text. Would you add the DIC content into that section of the drupal file? Follow the approach I used for the first section, Veterans Pension, by creating 7 accordions for the different scenarios someone may be filing for DIC. You can cut these words from the accordion labels: "To support a claim for"

Also, please apply our plain language standards. I'm working on the other text for this page incrementally, so leave the other sections as is for now. I'm drawing from other Word docs SMEs gave us, so that's why, for instance, the Survivors Pension section has different text from what's in this Word doc. Just leave those alone and focus on the DIC content. Thanks!

**Comment by lunascoop** [comment]
@bethpottsVADEPO I'm just about done my edits to the DIC accordions. I'll do another pass in the morning. Should Patrick and Randi review the pages first before your review? I wasn't sure if I should add them to the ticket.

Putting my notes and sources here for the time being.

**Question on last accordion:** Should the voc rehab reference change to VR&E? For now, I matched it to what's on the title 38 page.

### Sources

**Medical** 

- https://www.cancer.gov/publications/dictionaries/cancer-terms/def/cerebrovascular-accident
- https://www.google.com/search?q=acute+myocardial+infarction
- https://www.google.com/search?q=cardiac+arrest

**Active duty for training**

- https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=38-USC-384672575-746307973&term_occur=999&term_src=

**Inactive duty training**

- https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=38-USC-644511727-746307972&term_occur=999&term_src= 

**VA.gov sources and plain language references**

- https://www.va.gov/disability/eligibility/
- https://www.va.gov/disability/eligibility/special-claims/unemployability/
- https://www.va.gov/disability/how-to-file-claim/evidence-needed/
- https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/
- https://www.va.gov/disability/eligibility/special-claims/1151-claims-title-38/

**Comment by lunascoop** [comment]
@psanders86 the DIC accordions are ready for review. You can refer to my notes in my previous comment.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thanks for this work and for passing to @psanders86 for a substantive edit!

**Comment by bethpottsVADEPO** [comment]
@psanders86 @lunascoop I see a structural improvement I'd love for you to address in the first DIC accordion. This isn't something in the style guide (so wouldn't have expected you to be aware of it). That being said, since it's a direction Danielle and I have been moving in over the last couple years, we should add guidance about it to our bulleted list style guide entry. After that long wind-up, here it is: **avoid sub-bullets**. There's usually a way to write around it. I'll point you to 2 places where we've restructured content to avoid sub-bullets:
- In this article we're working on here, see the first accordion under Veterans Pension evidence needed. Instead of setting this section of content up with 3 main bullets and sub-bullets under the second main bullet, I used H3s for the 3 main requirements, then the second requirement has the bulleted list. 
- In https://www.va.gov/resources/combat-related-special-compensation-crsc/, I took a different approach with an H3 ("Details about your retirement eligibility requirement") that drilled down in more detail about the first of 3 main bullets above it. 

Happy to talk through the best approach or brainstorm @psanders86 if you'd like. I'm available today until 4:30 ET when I have a meeting. We could also chat about this first thing in the morning. Or if you feel like the above page examples are enough guidance, that's fine too.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you open a ticket to address this style guide entry? Thanks!

**Comment by psanders86** [comment]
@bethpottsVADEPO I think that makes sense, those are two good approaches. We'll make some changes to avoid those sub-bullets

**Comment by psanders86** [comment]
@RLHecht Please give this a copy edit. Thank you!

**Comment by RLHecht** [comment]
I copyedited the DIC accordion content. @bethpottsVADEPO These are now ready for you again.

**Comment by bethpottsVADEPO** [comment]
Thanks, @RLHecht and @psanders86! I'll make some final edits then will pass to stakeholders. Randi, you can create a ticket now for the stakeholder approval step for me. I think it makes sense for there to be a separate one for copyediting and publishing. You'll need to copyedit the full article still, since I think you only worked on the DIC section so far. But wait until I get it back from stakeholders...

**Comment by bethpottsVADEPO** [comment]
@RLHecht @psanders86 @lunascoop @SgardnerPMP I want to make sure we have the opportunity to talk as a team about quality improvements, and for you to ask questions specifically about the changes I made on the DIC part of this page after you turned in your work. The content feedback loop is transparent in that you can always see my drupal edits. And I think it would be helpful for you to take the next step of considering what the content team could do differently with the next project to improve quality before content reaches an OCTO content lead. The goal being fewer edits needed by the OCTO content lead. 

Would you go through the changes I made in drupal in the DIC section and bullet out in this ticket the types of changes you see? Then note how you could adjust your process or responsibilities by role to address these types of edits with future work before the OCTO content lead review. I want to call out that each of us will edit content slightly differently, so I want to be clear that I don't expect you to write and edit exactly as I do. You don't need to analyze and make notes on each edit, but note the obvious ones that reflect our basic standards--the items that are on your check lists and are baseline expectations to align content with our VA.gov style, voice, and plain language standards (like accuracy, short sentences, or simple PL word choice). After you've done this, let's talk through what could improve quality. And I can take questions from you about anything I did in the file.

Here's an example:

- Accuracy: In the first DIC accordion under "What the evidence must show," you changed the label.

**From:** "To support a claim for Dependency and Indemnity Compensation (DIC) based on a service-connected disability the evidence must show"

**To:** "If the Veteran died from a service-connected disability" 

But the third bullet contradicted the language you wrote for the accordion label. It said, "The Veteran died from a non-service connected injury or disease"

Screen shot: 

![image.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/5fa9e9e9-438b-4bc4-a563-8a2c24ca738c)

@DanielleThierryUSDSVA for awareness

**Comment by lunascoop** [comment]
Here's my review of the changes that @bethpottsVADEPO made to the DIC accordions.

Review of DIC accordion edits

* Added CTA sentence to section intro.
* Changed the meaning of the headers
* Changed text to avoid sub-bullets (see first accordion) **Note:** Perhaps add a note in style guide about sub-bullets and examples on how to rewrite to avoid using them
* For the second and combined accordion, moved content about needing evidence from a health care provider or layperson to a note section.
* In the header where active-duty training was mentioned, changed headers back to original wording (active-duty training) vs. "training during active duty" (but this wasn’t changed for the training during inactive duty accordion for service members). **Note:** Need more clarification for that bc it also wasn’t changed for the combined accordion. And the language isn’t consistent w/in the accordion text
* For the title 38 accordion:
  * Changed "added" to "additional." Need more guidance for this. This was based on verbiage from the [Increased disability rating](https://www.va.gov/disability/eligibility/special-claims/temporary-increase-for-time-in-hospital/) and [Title 38](https://www.va.gov/disability/eligibility/special-claims/1151-claims-title-38/) page
  * Removed title 38 from accordion header. Need guidance if legislation references should be included in content in general. It's included on some VA pages including the title 38 page.
  * Changed “at a VA facility” to “through VA”
  * Deleted “health” from VA health exam. This can be perceived as changing the original meaning of the text provided. Need more guidance for this. This was taken from the Title 38 page, as was the use of “carelessness or negligence”

**Recommendation for process improvement:** Before a writer starts on the content, they'll discuss the strategy with the team and review an outline to make sure the content provided/research is interpreted accurately.

**Comment by RLHecht** [comment]
My notes as well:

- Changed "disease" to "illness." This is in the style guide and should have been changed throughout, not just in a few instances
- Changed H3 in accordion from question to statement
- Shortened sentences to make more plain language
- Removed em dashes. This is for better readability; style guide says not to overuse. 

**Recommendation for process improvement:** I need to take more time to do a thorough copy edit to confirm the text meets our style standards; refer to the style guide more for word choice and plain language guidance; continue to look at other VA.gov pages for prior examples; consistently use the pre-publishing checklist.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop Thank you for your notes and thoughts on process improvements. We'll talk about how to improve quality in our quarterly planning meeting since that's a goal for Q1. Doing an exercise like this--looking closely at edits at every step in the content creation process--should be one way you as a team improve as you're working on each ticket. You can decide how best to take this step, whether it's a separate QA assessment ticket ("How'd we do with our QA?") or simply a step you each take with your work that's a task in each ticket (Review edits and document takeaways for team quality improvements).

A couple years ago, I had suggested using some form of the content components checklist that I shared. Laura had incorporated that into her work on IRIS articles. You'll probably want to leverage that plus the pre-pub checklist to come up with a checklist for each of the roles on the team.

**Comment by bethpottsVADEPO** [comment]
Closing this ticket as this work is done.
