### ISSUE TITLE
Create ID Validation Error Log Sentry Report

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#35170]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
`vets-api` currently runs duplicate ID checks for all of the major services it interacts with, some of these prevent logins and log the error, others only log a warning. `IEN`, `corpid`, and `edipi` all prevent logins, in order to help clean up the corrupted data the relevant IDs will be added to their respective error logs in Sentry. Once that is complete the IDs must be pulled out into a report for analysis and cleanup.

---
## Tasks
- [ ] Create a Sentry report that will pull out `ICN`s from the MHV ICN Mismatch error logs
- [ ] Create a Sentry report that will pull out `ICN` & `EDIPI`s from the Duplicate EDIPIs error logs
- [ ] Create a Sentry report that will pull out `ICN` & `CORP ID`s from the Duplicate CORP IDs error logs
- [ ] Add documentation for how to run the newly added reports

## Acceptance Criteria
- [ ] An Identity Team member will be able to query for a list of user IDs that are encountering duplicate ID errors

**Comment by joeniquette** [comment]
@bramleyjl if you can get Sentry to create these types of reports (I believe you need to make the attributes indexable) then awesome. However we have never been able to use it like that before and I wouldn't spend a lot of time doing it. Generating rails logs and pulling them from Loki like I do with the direct deposit reports today will suffice.

**Comment by bramleyjl** [comment]
Will revisit this once SiS duplicate IDs error handling is added.

**Comment by bramleyjl** [comment]
Will revisit this once SiS duplicate IDs error handling is added.

**Comment by bramleyjl** [comment]
After consulting with @joeniquette he has confirmed that no further action to create ID Validation Error reporting is required at this time
