### ISSUE TITLE
Request support for help debugging issue between the fwdproxy and IAM

### ISSUE THREAD

**Issue by travis-newby** [department-of-veterans-affairs/va.gov-team#35179]
## Description
Over the last 2 months, the mobile app has experienced periodic authentication issues. The issues appear to stem from connectivity drops between vets-api and IAM's introspect service. Introspect is an important part of every backend call; it's how we check the validity of the auth token we receive from the app. 

The issue normally starts on Saturdays around noon and continues until Monday - Wednesday. It varies in impact. Sometimes it only slows down introspect calls, but from Jan 8 - 10 almost all users were fully impacted for the duration of the event. (From Jan 8 - 10, 65k Veterans opened the app. The issue didn't occur all day on the Jan 8 or Jan 10, but based on the time frame we can reasonably assume a large fraction (between 1/2 and 2/3) of those 65k Veterans _were_ impacted during that time.)

Sat Nov 6th (~12PM EST) - Tues 9th (~12PM EST) 
Sat Nov 27 (~12PM EST) - Mon 29th (~12PM EST)
Sat Dec 4th (~12PM EST) - Tues 7th (~12PM EST)
Fri Dec 10th (~10AM EST) - Wed 15th (~11AM EST)
Sat Dec 25th (~11AM EST) - Wed 29th (~11AM EST) ** VERY BAD **
Sat Jan 1st (~10AM EST) - Wed 5th (~9AM EST)
Sat Jan 8th (~11AM EST) - Mon 10th (~3PM EST) ** VERY BAD **
Sat Jan 15 (~1030AM EST) - Tues 18 (1130AM EST)

Our team does not have access to the fwdproxy to help debug or resolve the issue.

## Technical notes
Fwdproxy reporting is showing massive swings in availability for iam_ssoe_oauth_back. This is causing large scale failures for the mobile apps authentication, specifically our introspect call to IAM. The flow for this call is something like vets-api -> load balancer -> fwdproxy -> AWS Transit Gateway -> VA Network -> Azure Gateway -> IAM F5 -> IAM OAuth servers. 

IAM (Damien) checked their metrics and they're seeing the inbound traffic bouncing up and down, but have no evidence of any downtime on their side. In fwdproxy, we're seeing a health check fail and 503s.

Our working hypothesis is that the issue lies somewhere between fwdproxy and IAM, but without looking into fwdproxy we're stuck.

[Health check showing IAM SSOe Issues](https://app.datadoghq.com/s/l8nm6eiir4c6z6f5/z8p-5ss-6px)
[Mobile API Dashboard](https://app.datadoghq.com/dashboard/9nz-cn7-ws6/mobile-api-dashboard?fullscreen_end_t%5B…%5Dent=prod&from_ts=1642542980083&to_ts=1642546580083&live=true)

## Tasks
- [ ] Help, please!

## Acceptance Criteria 
- [ ] Errors are resolved.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mchelen-gov** [comment]
Hi @travis-newby ! Can you please logs or reference for:
- issue normally starts on Saturdays around noon and continues until Monday - Wednesday
- availability for iam_ssoe_oauth_back
- fwdproxy, we're seeing a health check fail and 503s.

**Comment by travis-newby** [comment]
Here's a longer term graph showing lack of availability. 

![Mobile API Errors](https://user-images.githubusercontent.com/83976412/149188574-ee52abf6-d712-41ce-81dc-801973be1434.png)

I only have access to grafana for the fwdproxy stuff, so I can't pull back very far. But here's the last event.

<img width="915" alt="iam_ssoe_oauthe_back" src="https://user-images.githubusercontent.com/83976412/149188830-bf17a673-c8a1-4e32-a0c3-ae5b9f8ca746.png">

Reference for [health checks](https://dsva.slack.com/archives/C02THDWQAER/p1641939724016700) and [503s](https://dsva.slack.com/archives/CSFV4QTKN/p1641830005019700?thread_ts=1641825424.017800&cid=CSFV4QTKN).

**Comment by travis-newby** [comment]
And a bit more flavor, which I'll add to the slack channel too. Lighthouse SSOi OAuth looks like it's struggling during that period too.

<img width="932" alt="lighthouse ssoi auth back" src="https://user-images.githubusercontent.com/83976412/149189676-163c116a-5a2d-4f55-a8c6-86e035432657.png">

**Comment by mchelen-gov** [comment]
@travis-newby Ok cool, can you add links to those charts in the main issue body?
Followup item needed from your team is:
- list of access types being requested

**Comment by travis-newby** [comment]
@mchelen-gov will do. Just to be explicit about our plan, we're focused on doing two things, in this order:

1. Trying to fix the symptoms so a good portion of our users aren't getting served a ton of errors over weekends
2. Looking for and correcting the root cause

Right now we're focused on trying to get 1 into place. Boris put in a PR – and I believe it's already been approved by ops – to swap our health checks from HTTP to TCP. We'll have to wait for the weekend to see if that helps our health check's stability.

**Comment by travis-newby** [comment]
To prepare for the weekend, we'll want to make sure these tools are in place on staging and in prod:

* nc (netcat)
* traceroute
* curl
* dig
* openssl

(We think they may already be in place. @boris-ning-usds do we need anything else?)

In terms of access, @jperk51 and @kreek will need the ability to SSM into the staging and production haproxy instances and run those tools. They'll also need to be able to view logs.

**Comment by mchelen-gov** [comment]
@travis-newby 
> In terms of access, @jperk51 and @kreek will need the ability to SSM into the staging and production haproxy instances and run those tools. 

Ok for staging & prod SSM on haproxy (is that forward proxy or rev proxy?) please open [access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=Environment-Access-Request-Template.yml&title=Access+for+%5Bindividual%5D) issues so we can get started processing those.

> They'll also need to be able to view logs.
Can you confirm if they are currently able to view the necessary logs in Loki and if not clarify what logs (`vets-api`, `revproxy` etc) cannot be accessed?

**Comment by travis-newby** [comment]
fwdproxy

**Comment by jhouse-solvd** [comment]
@travis-newby - Can you provide a summary of where this is now, and what additional support your team may need?

**Comment by jbritt1** [comment]
I will let @travis-newby fill in the rest, but I know there is another meeting scheduled from 10am-12pm on Monday 3/7 at this current time.

**Comment by travis-newby** [comment]
This week – with the help of Jeremy – we were able to get _healthy_ packet captures from 3 systems (vets-api, network ops, and IAM). The next time this issue occurs we need to get _unhealthy_ packet captures for comparison. To get those, I'll need help from ops to whittle staging down to a single forward proxy instance and perform the packet capture.

Like Jeremy said, the session to get those captures is scheduled for Monday; if the issue doesn't occur this weekend, I'll reschedule it for the following Monday.

So to sum: 

* Need ops support for changing the forward proxy config and getting packet captures (probably an hour total on Monday)
* May need some help from any expert on your team actually going through those caps and figuring out what's happening
* We have no idea what we may need beyond that. It depends on what those captures show us.

**Comment by travis-newby** [comment]
Thanks to all your help, we were able to narrow down the issue to an IAM system. IAM is going to attempt to resolve this internally, and – if that doesn't work – through a ticket with IBM. We shouldn't need any more support, but if we do we'll let you know.

**Comment by mchelen-gov** [comment]
It's great that you were able to isolate the issue, thank you everyone for the work investigating this! Please reopen if additional action is needed.
