### ISSUE TITLE
[FE] Auth Profile : Address Change Messaging: Implement API calls, error handling and enable notifications

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35178]
## Background

The modal component looks to have the necessary functionality available to allow us to wire up the address change actions to display more information.

Modal component storybook: https://design.va.gov/storybook/?path=/docs/components-modal--default

Design docs for modal: https://design.va.gov/components/modal

Changing the Home and Mailing address and posting both of those updates at the 'same' time (aka when the modal 'yes' button is clicked) may present some interesting challenges.

We are basically presenting one modal after another. Are their any accessibility/usability concerns to this type of flow?
Wiring up the successive API calls will require some new implementations and testing around. Should a loading indicator appear at some point during these api calls to handle response latency?
Handling the failure of one or both updates may create some confusion, especially is one address update call succeeds and one fails.
At this point the notification that shows up below the address sections once the address is updated is limited to showing one at a time, and we would need the ability to display 2 notifications at the same time (one below mailing and one below home)
## Tasks
- [x] Implement api calls and error handling logic where needed to handle one or both updates failing
- [x] Display errors or update confirmation
- [ ] Enable 2 notifications at once on the profile fields
- [x] Complete testing

## Acceptance Criteria
- [x] API calls and error handling logic is implemented where needed to handle one or both updates failing
- [x] Display errors or update confirmation are being displayed
- [ ] Enable 2 notifications at once on the profile fields
- [x] All unit testing is complete
- [ ] Updated is deployed to staging and reviewed by PO and PM

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - will this task need to be completed after the FE build?  (pardon my ignorance!! ) 😄

**Comment by adamwhitlock1** [comment]
I think after the front end build is done will be best, as after the modals are complete then we can wire up the calls and error handling.

**Comment by adamwhitlock1** [comment]
I merged the PR for this issue, but in staging it is failing when requesting a status update on the 'transaction', and I will have to investigate since this is a different failure than a regular server failure. Its difficult to simulate within our local dev environment.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for the update!

**Comment by MarciMcGuireGCIO** [comment]
Hey Adam - I am not sure if this is the same issue you mentioned, but I just banged around on it in Staging, and everything works great, except when I overrode an address validation suggestion, then it threw an error when it tried to update the mailing address.   It worked fine when I took the suggested address, though. 

![image](https://user-images.githubusercontent.com/73354907/161288023-646eea54-42aa-4703-98f2-687484fe8a2a.png)

**Comment by adamwhitlock1** [comment]
![Screen Shot 2022-04-01 at 10.18.59 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/631e5afc-e343-4d70-b4d0-25a58f6b0642)

Here is the error that I am getting when the address is overridden.


Do we have documentation specific to the address update API that I could look into further?

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - there's a directory from 2 years ago with [address validation documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-validation).  The [error-code-matrix ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-validation/error-code-matrix.md)may be what you're looking for.   There's also some [tasty info and links to the API ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-validation/README.md#api-calls-and-dependent-systems)at the end of the README.md

Might be a good idea to check with Samara/stakeholders about that confidence score.  Based on my 7 years as a GIS analyst, scores below 80 can return some whack results.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss, From our conversation yesterday during standup, then we should be able to test and validate this to work as expected. The only edge case where we will see the error modal for sure is when a completely made up address is used (1234 somewhere rd) and the confidence score is too low.

We had spoke about using the validationKey from the home address validation to override the mailing address validation error but decided that would not be a good solution and to instead show the error if the update fails for that case.

You should be able to use the user 36 to update the home address and validate the display of modal and address does indeed update for both home and mailing.

**Comment by Samara-Strauss** [comment]
Validated the following flows:

- Updated home address and did NOT save as mailing address.
- Updated home address and DID also save as mailing address.
- Updated home address and then X'd out of the modal. Home address saved; mailing address did not.
- Updated home address to something totally bogus. Was able to override the address validation for home address, but not for mailing address. Mailing address failed as expected.
- Updated home address to be the same as the existing mailing address. The modal did not appear (as expected).

This should be good to go!

**Comment by adamwhitlock1** [comment]
Thank you @Samara-Strauss for taking a look!
