### ISSUE TITLE
Review R&S CTAs and update as buttons or action links

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35174]
## Issue Description
Now that we can use both action links and buttons on our R&S articles, we need to go back through all our published articles to determine which CTAs should use which styling. 

Need to add info here on when to use which. Talk with Natalie on the design system team for a better understanding.

## Tasks
- [x] Audit articles and note button or action link
- [ ] Update pages in Drupal
- [ ] Review and publish

## Acceptance Criteria
- [x] Articles have correct CTA styling

**Comment by RLHecht** [comment]
Randi to add link to design system guidance.

**Comment by GnatalieH** [comment]
@RLHecht I've been working on this [Links documentation (PR)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/165c9e775518d94664e61cde6057e6fe1f2d6ce7/src/_components/links.md) which has some info on when to use links vs. buttons vs. action links. 

The main bits of guidance I can think of are:

- Buttons do things, like submit a form or make a state change (from view to edit mode, for example). 
- Links go places, either within the same content area, to another content area on va.gov, or to an external site.
- Action links draw attention to important CTAs, such as kicking off a form application workflow. Action links are ideal when a text link isn't noticeable enough.

If you'd like me to look at some instances of R&S pages and give recommendations, I'm happy to do so! :)

**Comment by RLHecht** [comment]
This is really helpful, @GnatalieH thank you! Once we do an audit of our pages we can give you a few with our guidance just to make sure we're on the right track. I have a feeling most of our CTAs will be action links based on this info but there may be a few that we can put back into buttons.

**Comment by RLHecht** [comment]
After Selina and I reviewed the CTAs, all of these work as action links still since none are being used to "do" things as described above. This ticket is good to close out.
