### ISSUE TITLE
Create tool landing page for find and view representatives

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35191]
## Issue Description
We need to create a landing page for the new find and view representatives tool. This page will live at the root level and will redirect the following pages to to this:
https://www.va.gov/disability/get-help-filing-claim/
https://www.va.gov/decision-reviews/get-help-with-review-request/

To create this page, we need to follow the new tool landing page guidance that Danielle is working on. An example should be found in ticket #34123. We should also take a look at other existing tool landing pages for reference. 

See ticket 31320 for more information on the tool itself.

## Tasks
- [x] Create page
- [x] Edit page
- [x] Copy edit page
- [x] Send final version to Beth for review

## Acceptance Criteria
- [x] Page is ready for final review

**Comment by mnorthuis** [comment]
Here is the IA information that includes details for this new landing page: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23490

**Comment by RLHecht** [comment]
Here's the final doc for Beth's review: [https://app.zenhub.com/files/133843125/a01422dd-cdc4-44d6-9ceb-a58c1eb6c0d6/download](https://app.zenhub.com/files/133843125/a01422dd-cdc4-44d6-9ceb-a58c1eb6c0d6/download)
