### ISSUE TITLE
[PM] Auth Profile: Plan personal Information Revision: Contact Center Documentation

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35208]
## Background

The Profile documentation for the VA Contact Center needs to be updated to include changes that occurred during this project.

## Tasks
- [x] Determine approach for updating the Contact Center documentation
- [x] Communicate this information to Design and new PM

## Acceptance Criteria
- [x] Determine approach for updating the Contact Center documentation
- [x] Communicate this information to Design and new PM

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
Completing the Contact Center documentation is captured in #38961.   Links to directories are also located in that ticket.
