### ISSUE TITLE
CST - Frontend assessment - Get decision letter on page

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#35204]
## Issue Description
We've created designs to illustrate how the decision letter could be put on the page; now we need to understand how we can leverage current systems to make that work. 

---
## Tasks
- [x] Assess the feasibility of getting the letter PDF link in the CST
- [x] Determine a means by which this can be accomplished

## Acceptance Criteria
- [x] Findings have been documented and conveyed to team/devs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have made a design for the first version of this initiative:

https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3

**Notes**

1. The design will need to be checked by our content experts.
2.  Spoke with Jim Adams about the pre-existing text of sending users to ebenefits to check their ratings there...confirmed that the tool in ebennies still exists and is functional. Also confirmed that there is still a latency from our va.gov disability ratings tool in grabbing the data (so the user is still better off checking in ebenefits). We should keep that content as is for now.
3. Michel is still doing technical research on how to map decision letters to particular claims. As we learn more (about what data we have, how it looks, etc), it's probably going to change the design as we go.
