### ISSUE TITLE
526 enhancements - Reordering screens to fit sections

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#35203]
## Issue Description
In preparation for our shift to a task list pattern, we want to reorder screens/sections of the 526 form so they fit more appropriately into different sections that could be shown on the 526 task list 'table of contents'. This should not only make the form simpler to understand, but it should also help provide a streak effect to users who are going through it.

---
## Tasks
- [x] Assess screens and determine what sections they should be in
- [ ] Determine the best ordering of sections for user experience

## Acceptance Criteria
- [x] Screen reordering has been documented for FE devs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
Mural board made for this:
https://app.mural.co/t/vsa8243/m/vsa8243/1639070794497/b605ba85a76c75be7d195bd4090286b6e8061453?sender=cvalla7693
