### ISSUE TITLE
526 Fast Tracker

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35201]
## Issue Description
Continue to assist in development and troubleshooting efforts
---
## Tasks
- [ ] Assist with outstanding troubleshooting.

## Acceptance Criteria
- [ ] Claims & Appeals portion of solution complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
On the morning of 01/19/2022 I noticed failed 526 fast track jobs in sidekiq:
"ArgumentError: no ICN passed in for LH API request."

I assisted the Hypertension team for around ~8 hours with debugging, fixing and testing the issue.

**Comment by michelpmcdonald** [comment]
Spent another 2 hours in meeting

**Comment by michelpmcdonald** [comment]
Going to close this, will create a new support ticket in next sprint if support comes up.
