### ISSUE TITLE
[Research] Check-in UX to be Participants in Appointment Notification Service Blueprint

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35206]
# Description
The check-in team has learned a lot about certain appointment notifications already, such as VeText. We also some about the pre-appointment, during an appointment, and post appointment landscape. This information will be beneficial to the appointment notification service blueprint study.

Therefore, the check-in designers will serve as study participants and fill out the appointment notification service blueprint.

# Tasks
- [x] Meet w/ Peter
- [x] Schedule a time to fill out the blueprint. Invite @outerpress to session.
- [ ] Make a copy of this [Mural]( https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1636756044351/5d79820e2ca9ec0cb48b5bea4e300d777a155b6d?sender=ub08ff1d80ee7bd38d6c02354) for us to fill out.
- [ ] Hold research session with the team and fill out the Mural together.

# Acceptance Criteria
- [ ] The Mural is fill out during our research session.
