### ISSUE TITLE
[BE] Auth Profile: Bad Address Indicator: Review Swagger docs

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35211]
# Authorized Experience Profile Standard Issue Template

## Background
In preparation for displaying a notification when a user has a bad address, please review the [Swagger documentation] (
https://qa.vaprofile.va.gov:7005/contact-information-hub/swagger-ui/index.html?configUrl=/contact-information-hub/v3/api-docs/swagger-config#/) for the VA Profile Contact Information data source. 

## Tasks
- [x] Review VA Profile Contact Information data source Swagger documentation
- [x] Compile any questions for the VA Profile team

## Acceptance Criteria
- [x] VA Profile Contact Information data source Swagger documentation has been reviewed
- [x] Any questions for the VA Profile team have been compiled

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
- Add a prefix to the title indicating practice area, e.g., [FE], [BE], [Design], [PM]

**Comment by tpharrison** [comment]
I spent time reviewing the swagger docs and vets-api calls to the contact-information API.  I may have some technical questions as I get into the work, but I don’t have any questions related to the API at this point.
