### ISSUE TITLE
[Design] Auth Profile: Personal Information Revision: Complete Design Changes Resulting from Research Study

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35219]
## Background
A research study was recently completed for changes to the VA.gov Profile to add Personal Information fields.  This issue is to update Sketch files to reflect the design changes resulting from that study and subsequent meetings with Lexi and VA Profile.  [Notes on current changes are here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/meeting-notes/2022-01-25-design-changes.md).   

Note that this ticket is ONLY to update the design, but does not include final copy changes as those are dependent on Content.  A new ticket will be created to cover subsequent content updates. 

## Tasks
- [x] Remove Sex Assigned at Birth from all mockups
- [x] Alphabetize the options listed for Pronouns, Gender Identity and Sexual Orientation, with the exception of the "do not wish to answer" and  "other" options, which will remain at the bottom.
- [ ] Add a comment to this ticket with a link to the updated Sketch files.
- [ ] Add link to mockups to related content request (ticket # TBD)

## Acceptance Criteria
- [ ] Sketch files have been updated to reflect any changes arising from Personal Info Revision research study
- [ ] A link to the updated Sketch files has been added to the comments of this ticket.

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO -- The task to **Update to add a link to a Resources & Support page that provides more detailed info** is not complete, but this might need to move into #36240 - the ticket holding the items we're working with Danielle on. I think placement of this link would depend on content changes.

**Comment by MarciMcGuireGCIO** [comment]
Thanks!  I'll move that task to the other ticket and close this one.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske if you can drop the link to the Sketch files here, that would be great.  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO absolutely! Here's a [link to the Sketch files](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)

**Comment by MarciMcGuireGCIO** [comment]
Thank you!!

**Comment by Samara-Strauss** [comment]
Idk if we still need these mocks, but it looks like fields weren't alphabetized [on this mock](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw) and [this mock](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/MyzeRwb). Sorry to be so nitpicky -- the first one just so happens to be linked to from the FE documentation, which is why I noticed. I'm normally not this micromanage-y :) Otherwise, looks good!

**Comment by cgednalske** [comment]
@Samara-Strauss No problem! Once the hint text place holders are complete, I was planning to create new components for each field that would update automatically in these two mockups, so I can avoid having to update each field for every change we have. 

If it helps, I can move these mocks to a different Sketch page in the meantime so as to not cause any confusion.

**Comment by Samara-Strauss** [comment]
Ah, that makes sense, @cgednalske. No need to do anything now, then. Thanks for letting me know. Just wanted to point it out so FE doesn't get confused.
