### ISSUE TITLE
FE Audit and Answer Engineering Questions - Outcomes Items from Earlier Pre-check-in Audit

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35210]
# Description:
UX completed a full design audit of pre-check-in within #34225. During that review, they identify numerous items for engineering to address. This ticket will allow UX to review the new FE tickets, review staging or screenshots, and answer engineering questions.

# Tasks:
- [ ] Document what we review in Design Audit section in Sketch and any changes
- [ ] Post a link in FE tickets and this ticket to the Sketch section

# Acceptance Criteria:
- [ ] Everything is reviewed and gaps are communicated with engineering
- [ ] Answering engineerings questions

**Comment by kristenmcconnell** [comment]
FE tickets to review: 
- #34655
- #34670
- #34669
- #34668
- #34731

**Comment by kristenmcconnell** [comment]
The time on the appointments page will also be changing for 10 to 5 minutes within [this.](https://github.com/department-of-veterans-affairs/vets-website/pull/19895)

**Comment by niradatta1** [comment]
UX has reviewed and approved above tasks for pre-check-in only. 
We  got an error message for day-of (see screenshot). 
Once we get a new link for day-of, we can complete this ticket. 
<img width="290" alt="Screen Shot 2022-01-21 at 8 56 42 AM" src="https://user-images.githubusercontent.com/65250279/150568720-b7d07420-891c-4b39-af89-eecad00dde99.png">

**Comment by dcgoodwin2112** [comment]
Screenshots of Day-of validation 

(cc: @niradatta1 @zach-park @ytsaoca)

Step 1
![1-day-of-validate](https://user-images.githubusercontent.com/4554388/150853435-454fea2f-f949-4d51-a605-1b9ba73c5166.png)

Step 2
![2-day-of-demographics](https://user-images.githubusercontent.com/4554388/150853533-abb102e6-98c6-4273-b9c0-d72a3c48a3f2.png)

Step 3
![3-day-of-emergency-contact](https://user-images.githubusercontent.com/4554388/150853559-577c4a9b-ae48-40e8-810c-b570bfad7f43.png)

Step 4
![4-day-of-NOK](https://user-images.githubusercontent.com/4554388/150853569-5141096d-56a8-40de-9f69-61a9bcb42a0c.png)

Step 5
![5-day-of-appointments](https://user-images.githubusercontent.com/4554388/150853589-8d85be4a-11fa-4bfd-b873-e521ec1d7f81.png)
![5-2-day-of-appointments](https://user-images.githubusercontent.com/4554388/150853603-e34909ab-4086-4c7d-ae72-be9207110410.png)

Step 6
![6-day-of-complete](https://user-images.githubusercontent.com/4554388/150853636-80c1e761-dc80-4e1c-b342-2fef5a8b999e.png)

**Comment by ytsaoca** [comment]
@dcgoodwin2112 Thanks. Looks good.
'cc @niradatta1 @zach-park
