### ISSUE TITLE
Complete Confirmation/Download Page for Rep

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35228]
## Background
Now that we have the appoint representative pages closer to being done we need to update the confirmation page for appoint rep so that it has the static content showing a download link for a PDF like in the mockups.

## Considerations
https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145605203/simulate/sitemap

## Tasks
- [x] Adjust confirmation page content to match mockup
- [x] A PR has been requested for merging
- [x] Check for any missing pages (e2e review)

## Acceptance Criteria
- [x] Adjust confirmation page content to match mockup
- [x] A PR has been requested for merging
