### ISSUE TITLE
Add Static Bio Page for Auth Rep Flow

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35221]
## Background
Now that we have the pages for appoint rep set up we need to create a different page for the veteran information based on if they are logged in. If they are logged in we only want to show them a static card of the information we have on file since they cannot use this form to change that information.

## Considerations
[The mockup when user is signed in](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145599859/simulate/sitemap)

[Here is how we accomplish this on other forms](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/disability-benefits/686c-674/config/chapters/veteran-information/veteran-information)

[We then conditionally render the logged in or not logged in page using this](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms#conditionally-including-a-page)

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/selectors.js

## Tasks
- [x] If possible, set up a conditional page that has static veteran information card
- [x] Establish contact with Platform on this issue on what gets displayed `auth` vs `unauth`

## Acceptance Criteria
- [x] Contact with Platform on this issue on what gets displayed `auth` vs `unauth` has been made
- [x] A conditional page has been initialized
- [x] Submit a PR for review, or have one in draft, if applicable
