### ISSUE TITLE
Prepare Walla Walla (FAC ID 687) for Cerner Launch

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35227]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)
Timeline for launch: Testing the month of Feb (possibly including last week of Jan)
Go live stuff: March 25th cutover for March 26th Go-Live

- Facility ID's: Walla Walla health care facilities
Richland VA Clinic - vha_687GA
Lewiston VA Clinic - vha_687GB
La Grande VA Clinic - vha_687GC
Jonathan M. Wainwright Memorial VA Medical Center - vha_687
Yakima VA Clinic - vha_687HA
Wallowa County VA Clinic - vha_687QC
Morrow County VA Clinic - vha_687QB

### Considerations
- Follow the Cerner Runbook and prepare Walla Walla Facility for Cerner launch  
- This will need deploy to staging initially in order to be tested by the facility and our team
- Once fully tested and validated in staging, we'll prepare to deploy in production per runbook guidance

### Tasks
- [x] Follow the Cerner Runbook and prepare Walla Facility for Cerner launch 
- [x] Test locally and setup a staging test environment so Facility admins can test.
- [x] Once validated in staging deploy to Prod per the runbook guidance 
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Local test are completed and show signs of success
- [x] a11y considerations are implemented in support

**Comment by brianalloyd** [comment]
No actions needed for Walla Walla as its now prepare for testing as validated by VA Testing & Evaluation team.  Closing out this ticket and linking to new implementation ticket for "go-live" support.
