### ISSUE TITLE
Design card display in form summary 

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#35238]
### Background
In the Find and Appoint Form, the summary page is currently displaying all of the search page selections in the "Your selected representative" accordion but this might need to be better adjusted for eventual FE implementation. 

### Tasks
- [x] Determine what should be displayed
- [x] Update Sketch file
- [x] Update uxpin prototype

### Acceptance Criteria
- [x] UX Pin has been updated
- [x] Sketch has been updated
- [x] Share results with team (comment links here in this ticket)

**Comment by sporeboy** [comment]
I have the initial screen showing an open Selected Representative Info accordion. [Link to UXPin prototype screen.](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/146446995)

This was built out of borrowed pieces, so ignore the "flash" when the words change on open/close.

**Comment by sporeboy** [comment]
The info displayed is pulled from the selected rep here: [UXPin prototype screen.](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145744933)

**Comment by candy-gcio** [comment]
Same page in [sketch](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/Axk4l51)
