### ISSUE TITLE
[Datadog] Fix DNS synthetic monitors more permanently 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#35234]
## Description
@mchelen-gov noticed a DNS synthetic monitor we have in Datadog was broken for some time

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1641939008153000

## Technical notes
What fixed it most recently was running a test to see what responses the check actually got and updating the A name records with current reverse proxy elastic network interface IP addresses.

====

There are two of them that seem to be querying different DNS servers but I’m not quite sure that is doing anything because the private location where it runs lives inside of kubernetes.  I am pretty sure the only DNS server it has access to in the case of EKS is 172.20.0.10 or 10.100.0.10 

![image](https://user-images.githubusercontent.com/76792875/157498989-57573dab-82d7-4167-a9f3-82a6ba1676d8.png)

https://app.datadoghq.com/synthetics/details/fmj-eim-u8t?live=1h
https://app.datadoghq.com/synthetics/details/ucu-y35-yva?live=1h

What I think is happening based on the datadog documentation, it’s failing to resolve the records from either of those DNS servers (along with google and cloudflare) and eventually falling back to the kubernetes DNS.  (https://docs.datadoghq.com/synthetics/api_tests/dns_tests/)

`Specify the DNS Server to use (optional), it can be a domain name or an IP address. If not specified, your DNS test performs resolution using 8.8.8.8, with a fallback on 1.1.1.1 and an internal AWS DNS server. `

Either way I think we can trim this down to a single DNS test assuming that the only private location we are using lives in kubernetes.  Last thing to note is that it does seem like the A records (IP addresses) for the revproxy load balancer network interfaces have changed though I am not quite sure if that is expected.  If it is going to change often then I agree with Jeremy’s comments that maybe we should remove the A records completely.

---
## Tasks
- [x] Do some monitoring to see if this is a one-off or if the ENI IP addresses continually get rotated in a way that we can't depend on them for this check
- [x] Remove the expected A name record results from the check entirely if they are going to always rotate in a non-predictable manner
- [x] Manage it in Terraform (currently has the `ManagedBy:Terraform` tag, but is nowhere to be found in our Terraform code)

## Acceptance Criteria 
- [ ] Check is working reliably and consistently for the foreseeable future

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
https://app.datadoghq.com/synthetics/details/yig-e85-325?live=1h

**Comment by mleclerc00** [comment]
As stated in the above PR, my assumptions about kubernetes DNS was incorrect.  The private location can indeed resolve the internal VA DNS servers.  So I have added tests to make sure that both are aligned with our revproxy CNAMEs for both the frontend and api urls in all environments.

**Comment by jhouse-solvd** [comment]
Great work here @mleclerc00 - I'll leave it to you and the team to close. Thanks for the investigation and effort here!!
