### ISSUE TITLE
Update View, Find, Appoint Rep prototype for test functionality

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#35240]
### Background
The View, Find and Appoint representative features are ready for usability testing and the initial prototype has been completed. To support usability testing, we need to add functionality to the prototype.

### Tasks
- [x] Add pagination to search results
- [x] Add variable function to allow user to "select" a representative and see selection later

### Acceptance Criteria
 - [x] UXPin prototype is updated to reflect implemented research recommendations

**Comment by sporeboy** [comment]
Variables and pagination added to prototype [(Link to UXPin prototype)](https://preview.uxpin.com/123ff026cdc405f517913514fd1a0da167d94b54#/pages/146744034).

Variables added for:
- City, State, ZIP
- Organization name
- Representative type

Pagination set for three pages of six cards each; regular show/hide functionality with "Scroll-to" interaction.

**Comment by sporeboy** [comment]
Prototype moved to Yana workspace; ready for inputting details and testing.
