### ISSUE TITLE
[FE] Re-evaluate when back button should be shown

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#35247]
## Related Documentation
> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1641934262123000) 

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

The back button should not always be shown. Figure that tout and implement it 

Things to consider: 
- Hide back button when the user has not seen the demographics checks
- Can we look at the forms pages and show based on that

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Review thread
- [ ] Work with UX to determine best course of action
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
Need to set up test appointments and validate with UX. Nira and Zach to validate on thurs or fri. @brianseek can you set up test scenarios for this?
