### ISSUE TITLE
[Discovery] Design Refactoring for Outreach & Events Hub (Plain Text Search UX)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35242]
#### Discovery phase
Review current page and determine how to make the Outreach Events Calendar page more "refine-able" for users (e.g. how to conduct a "plain text search"). This discovery issue is meant to capture design ideas presented in the Product Outline, and to discuss ideas on how to make the Outreach Hub more relevant and useful based on recent release of Outreach & Events MVP (Recurring Events and Filtering).

#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive plain text search functionality, so that can quickly find VA events based on relevant keywords search i.e. Zumba, PTSD, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Research Report - O&E Enhancement MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/research-findings.md)

### Considerations
- Must work well on mobile and desktop platforms
- Must address accessibility concerns and support for adaptive tech
- Should consider iterative feature development
- Initial design/development must align with current CMS functionality
- Must include "plain text" search concepts 
- Must NOT include **Location search** as that will be separate design iteration

### Tasks
- [ ] Baseline existing features and flows
- [ ] Identify use cases for plain text search
- [ ] Illustrate use cases via feature flow diagrams
- [ ] Determine new features needed and propose staged deployment of new components
- [ ] Wireframe UI suggestions illustrating features in context

### Acceptance Criteria
- [ ] Brief discovery doc outlining baseline feature flow and functionality created
- [ ] Diagram uses cases and high-level feature flows 
- [ ] Wireframe UI suggestions illustrating features (including date/time filtering) in context created

**Comment by callen2563** [comment]
I put together an initial Mural board but it's at the beginning stages:
[Mural Board for Use Cases & Flows](https://app.mural.co/t/vsa8243/m/vsa8243/1634651992163/439beeb6c6f54295c81a2b62d2d4c766f6b23205?sender=u7ad68f2a3a694c00d8a38130)

**Comment by cindymerrill** [comment]
Worked with Cassandra on design ideas for adding a keyword search feature.

**Comment by callen2563** [comment]
I have updated the [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1634651992163/439beeb6c6f54295c81a2b62d2d4c766f6b23205?sender=u7ad68f2a3a694c00d8a38130) with new thoughts. Josh Kim left his comments in green stickies. I am working on wires.

**Comment by cindymerrill** [comment]
I've added a few purple stickies to the Mural board with my comments.

**Comment by callen2563** [comment]
@brianalloyd I have attached the wireframes here:
![O E Wireframes V2](https://user-images.githubusercontent.com/68560244/150880132-8637cddb-5952-4feb-95a4-13fb383c41ff.png)
