### ISSUE TITLE
[FE][SPIKE] Determine how to handle the routing issue

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#35249]
## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C022AC2STBM/p1641933943122000)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Problem: (from slack) 

Made appointment in VistA within time guardrails.  Text "check in".  Receive and select link.  Authenticate with name/ssn.  See demographics page but do nothing on the page (i.e. no review response made).
At this point, close the tab/page entirely so there's no open tabs.
Select link again.  Browser opens directly to appointment screen.  Demographics page is skipped entirely.  Expectation would be to start from the page the user last completed (i.e. authentication) and taken back into the workflow where they last stopped (i.e. demographics page).
I don't think it's actually satisfying the demographics review because if I make another appointment, text check-in, click link, it'll require me to authenticate and then show me the demographics page. (edited) 

Possible Solution(s):
- update the routing to look at the needsToUpdateXXXXX fields and never on the API permissions.
- Figure out if/when we need/can refresh the demographics check

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create dev work ticket to do the work
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by mdewey** [comment]
Blocked until engineering can sync up on solutions/asks, See thread for more detail

**Comment by sarahknoppA6** [comment]
per @mdewey's suggestion, a sync should be held to try to reproduce this on friday after @niradatta1 and @zach-park sync. @brianseek to set up another appt

**Comment by brianseek** [comment]
Next steps, create e2e tests that refresh app. To debug further.

**Comment by mdewey** [comment]
Looks like this was addressed when we moved to use the demographics flags for routing issues.
