### ISSUE TITLE
Adjust LGY Service to Store COE File in S3

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35245]
## Background
We have already coded the external call to get the `applicatoin/octet-stream` back from LGY; now we need to store that in S3 and return the URL to the controller.

## Considerations
- expiration time on s3 file
- security/signature - make sure no one can publicly see file

## Tasks
- [x] Amend service specs to ensure an s3 url is returned
- [x] Make tests pass

## Acceptance Criteria
- [x] A PR has been requested for merging
