### ISSUE TITLE
Collab Cycle

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#35265]
## Issue Description
[Collab Cycle- How it works](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html)

Gain feedback for the following issue for the collab cycle:
Use [collab cycle template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/eeb72044555397338942517d559aa64f09a01382/.github/ISSUE_TEMPLATE/collab-cycle-initiative.md) to request review for 

- [UI Consistency for R&S Article Pages](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34256)

- [User wireframes and user flow for Submit Feedback Tool](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34152)

---
## Tasks
- [ ] _Create collab cycle kickoff ticket for UI Consistency for R&S Article Pages_

- [ ] _Create collab cycle kickoff ticket for User wireframes and user flow for Submit Feedback Tool_

## Acceptance Criteria
- [ ] _Collab cycle process has begun_

**Comment by nicole-leonard** [comment]
Meeting with Michelle 1/13/22 to discuss how to get the kickoff set for this ticket.

**Comment by nicole-leonard** [comment]
Dave reviewing the intiative brief for UI Consistency for R&S Article Pages.

Nicole and Megan to meet with Dave on User wireframes and user flow for Submit Feedback Tool after we discuss the path forward with good/bad vs. Medallia

**Comment by nicole-leonard** [comment]
Initiative brief done and with Dave for review. Once review is.Complete I will put in the Collab Cycle Kick off request and add the ticket for it.
