### ISSUE TITLE
Continue Research Plan draft

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#35263]
## Issue Description
Continue work on [Research Plan draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/resources-and-support/research/usability-study-1.0/research-plan.md) for Submit Feedback Tool and R&S Article Pages

---
## Tasks
- [ ] _Where did the name "Resources and support" come from?_
- [ ] _Submit feedback tool- finalize questions with the help of Content Team_
- [ ] _Feedback from UX team member_

## Acceptance Criteria
- [ ] _More defined research plan_
