### ISSUE TITLE
Segmented Reporting for Medallia

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#35275]
## Issue Description
Provide DOMO users with the ability to segment Medallia data by modernized and non-modernized sites.

---
## Tasks
- [x] Create a field in the Medallia data set for modernized vs nonmodernized
- [x] Assign values to that column based on the form
- [x] Create a default filter based on that field

## Acceptance Criteria
- [x] Field has been created in the ETL
- [x] Correct values have been mapped to that field
- [x] A filter has been added to the Medallia MVP
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 It seems like the best way to create and map a modernization field is using the Form field in the Medallia exports. Here are the 5 options:

- External Website Survey
- Internal Website Survey
- VA.gov A11 Questionnaire
- VA.gov VFS - Search Questionnaire
- VA.gov VFS Questionnaire 

Do just the first 2 map to nonmodernized? Should I include all 5 forms in the MVP after the filter has been set up?
