### ISSUE TITLE
End to End Testing With Rachael

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35282]
## Issue Description

Setup and conduct end-to-end user acceptance testing with Platform crew chief Rachael Roueche so we can validate the process internally before launch.

---
## Tasks
- [x]  Document test plan
- [x] Fix the Github project board to issue automation
- [x]  Figure out where it will live on Platform Website 
- [x]  Publish to the Platform Website 
- [x] Conduct test
- [x] Get feedback from Rachael
- [x] Document results in release plan with changes suggested by Rachael

## Acceptance Criteria
- [x] Feedback tells us whether the process enables Platform teams to review and prioritize feature requests.

**Comment by Khyatinp18** [comment]
Notes from 1/12 Stand up:
- Work with Gretchen to figure out where this will live on Platform website
- Resolve Project board - issue automation break
- Andrea suggested link both "Scoring Guide" and "Value Matrix" to PM facing

**Comment by Khyatinp18** [comment]
1/13
Jonathan is working with Gretchen for placement of Feature request on Platform website

**Comment by jonathanjnelson** [comment]
Content and SD recommends that [Submitting a feature request](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1938915400/Submitting+a+feature+request) document is published to the Support section of the [Platform website ](https://depo-platform-documentation.scrollhelp.site/index.html)
