### ISSUE TITLE
Limit Zip Code Fields all across CT to accept 5 digits only

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35309]
## Issue Description
Currently zip code fields accept more than 5 digits. This request is to accept only 5.

---
## Tasks
 - [ ] Limit Zip Code Fields all across CT to accept 5 digits only

## Acceptance Criteria
- [ ]  All zip code fields in CT should only accept 5 digits and not more
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mrblanco1** [comment]
Per OCTO, there are Veterans living outside the US with >5 digit?? Adam reaching out to design to verify if this is true.

**Comment by AdamFreemer** [comment]
As per discussions with platform, the consensus was the current validation place is effective at providing the user enough feedback on correct postal code entry. There is also the consideration of 6 digit possible addresses in this calculus. https://dsva.slack.com/archives/CBU0KDSB1/p1642185804399600

**Comment by mrblanco1** [comment]
To be demoed tomorrow 1/20/2022.

**Comment by mrblanco1** [comment]
Closing this story since users can only enter 5 digit zip codes. If they enter 6 digits the system will throw an alert. If they enter a 5 digit zip code followed by a dash and four number (9 digit zip) they are allowed to. If they enter an address with 5+ digits they will be allowed as well.
1/21/2022 - Abe B.
