### ISSUE TITLE
[Research] Create Presentations/Research Findings Summaries for Accessibility Mapping

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35311]
## User Story
- As a product team, we want to document and share the findings from our accessibility mapping work.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Add links to accessibility map Mural and prioritization spreadsheet]()

## Description
A research report detailing findings and design recommendations from accessibility mapping work.

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks

- [ ] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup) - maybe just posting presentation(s) to GitHub. Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md
)

## Acceptance Criteria

- [ ] Post research report to GitHub as presentation and markup document

Schedule readout sessions with
- [ ] Stakeholders (talk to Patrick about when to do this)
- [ ] team (either via Slack or Zoom meeting)
- [ ] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by kristenmcconnell** [comment]
Duplicate to #36145. Closing.
