### ISSUE TITLE
Fixing broken link to Form 21P-530EZ on burials and memorials pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35315]
## Issue Description
We currently have a broken link to 21P-530EZ on our [Burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page. The form was recently change to 21P-530EZ. 

We need to update this link, adding the EZ to the end. We also need to check if this form is linked from any other pages and correct those as well.  

## Tasks
- [x] Fix broken link (Selina)
- [x] Check for link on other pages and update (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholders that change is live

## Acceptance Criteria
- [x] Link to Form 21P-530EZ working on live site

**Comment by RLHecht** [comment]
Page is reviewed and published and we found no other links to the form from other pages. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
