### ISSUE TITLE
[Research] Plan How to Get Feedback from St. Louis MSAs on Pilot

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35317]
# Description
We have a plan to get feedback from Veterans at St. Louis, but could we have a more structured time to get feedback from MSAs on their experience. Create a research plan for potentially take over an office hours with them. Are we setting up office hours?

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Tasks

- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria

- [x] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan and conversation guide to GitHub folder

**Comment by kristenmcconnell** [comment]
Research folder for this new research: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback

**Comment by kristenmcconnell** [comment]
Draft [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/conversation-guide.md) and [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/research-plan.md) for review.

**Comment by kristenmcconnell** [comment]
The drafts conversation guide and research plan was sent out for review via [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1642452936018800).

**Comment by kristenmcconnell** [comment]
Updated [Optimal Sort](https://adhoc.optimalworkshop.com/questions/va0gv5g4) based upon team feedback in Slack thread listed above.

**Comment by kristenmcconnell** [comment]
Sent to Shane Strassberg for final research ops approval via [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1642713463027200).

**Comment by kristenmcconnell** [comment]
Plan approved by Shane.
