### ISSUE TITLE
Update content in HLR staging following review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3532]
## User Story or Problem Statement
As a Front-end Engineer on the Benefits and Memorials team, I need to update all of the Higher Level Review content in staging so it can be finalized and ready for the final content review in staging.

## Goal
_All content reflects changes identified in the mockups_

## Tasks
- [ ] Update Step 1 (veteran details) page content.
- [ ] Update Step 2 (contested issues) page content.
- [ ] Update Step 3 (informal conference) page content.
- [ ] Update review and apply page content.
- [ ] Update Confirmation Page content.

## Acceptance Criteria
- [ ] _The content has been updated in staging_
