### ISSUE TITLE
[EPIC] Outreach & Events Hub - Free text search functionality

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35324]
## Product Outline
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)

## High Level User Story/ies
As a VA digital comms lead and user of the VA.gov CMS, I need new capabilities and features as a publisher in the Outreach & Events hub, so I can provide information more effectively to my Veteran and caretaker audience.

## Hypothesis or Bet
If we make improvement and enhancements to improve the authoring experience and to enhance the feature set, the result will be (a) more efficient publishing times, resulting in higher customer satisfaction scores (b) and higher consumption of the content, as measured by page views.

## OKR
These changes will improve user experience and findability for events offered by the VA in support of Veterans.  

## Requested Changes & Enhancements
- Enhance search component so Veterans and users can use a free text field to find Events they are looking to attend. 

### UX Feature & CMS Authoring Enhancements:

- [ ] Ability to `free text search` for events. As a first option, next phase would be to integrate a `search by location` component once CMS has technical feasibility ISO integration. 
- [ ] Ability to search by location for events near Veterans. (Phase II)

## Next steps
- [ ] Design concepts for review (determine path forward)
- [ ] Collaborate with CMS on Implementation timeline 
- [ ] Point the priorities by team.

## Definition of done

- [ ] Work with the CMS team to assess and determine the value and LOE of the requested changes (if needed, validate assumptions with the VA stakeholders) 
- [ ] Ability to search in event detail pages in support of specific Events offered by the VA. 
- [ ] Communicate the timeline of delivery to VA stakeholders (e.g. manage expectations)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jilladams** [comment]
Per 6/10 Events backlog scrub with Dave Conlon: 

Free text events search is still an open ask, though not prioritized.
Search experience is likely to tie back to location-based search

**Comment by jilladams** [comment]
Because Zenhub is likely going away, Sitewide may hit our Github Projects issue cap (1200), and may not be able to port all our issues in right away, logging which issues in this ZH epic are still open, so we can later build parent/child relationships in GHP as needed:
