### ISSUE TITLE
[SW-Content] Audit benefit hub pages for header bugs and fix [CW]

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#35326]
## User story

As a Veteran or family member, and particularly as a person who is using a screen reader, I need properly structured headers so I can navigate content on VA.gov.

## Tasks
- [x] Review approximately 75 benefit hub pages
- [x] Document the pages that have the bug and if it is a small or big lift 
- [x] Fix the header issue on the page and save to published.

## Details

Some of our pages have issues with headers, such as the following examples. These are not the only instances of these issues, so we'll need to audit all benefit hub pages to find and fix.

### [Get support for your Veteran-Owned Small Business](https://www.va.gov/careers-employment/veteran-owned-business-support/)

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/bbd13bf0-e559-4c7e-9434-ab4414c290cc)

Issue: No header above accordions.

### [Veterans’ Educational Assistance Program (VEAP)](https://www.va.gov/education/other-va-education-benefits/veap/)

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/e5c78aee-905b-4dbf-b60b-7f08e08b609c)

Issue: Multiple H2s in a row. This should be an H2 with H3s or accordions beneath.

**Comment by DanielleThierryUSDSVA** [comment]
Another page with heading order issues: https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/

@SgardnerPMP @RLHecht 2 things:

1) Were the 2 pages I identified specifically above when I opened this ticket fixed? If not, can the team please fix the pages identified asap?
2) Let's connect on the broader audit in our content planning call today.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA These pages are all fixed and we are completing the audit of the rest of the site. Putting my note from Slack in here too. Dave already reached out to PW so they are opening a ticket to figure out a FE fix though we will still update pages manually so they can be corrected sooner.

I think I figured out what the issue is. These pages all use the Q&A component and have a section header as well. They are all showing as H2s instead of the Q&As automatically becoming H3s when there is a section header. We can manually fix these by taking them out of the Q&A component and putting them into rich text fields, but we should have PW fix this so that new pages that are created can use the Q&A component. I'll note this in the ticket too.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome, @RLHecht! Thank you so much for fixing these pages and even more for digging into this and figuring out the broader issue for this important accessibility issue.

**Comment by RLHecht** [comment]
@lunascoop Here are the pages we need to fix from the hubs I audited:

**Pages  that have the Q&A component:**
https://www.va.gov/health-care/health-needs-conditions/mental-health/suicide-prevention/
https://www.va.gov/housing-assistance/disability-housing-grants/
https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/ (also need guidance on accordions)

**Other pages with header issues:**
https://www.va.gov/health-care/about-va-health-benefits/cost-of-care/  (I updated this one but can you please check it before we publish? And we will still need guidance on the accordions)
https://www.va.gov/health-care/family-caregiver-benefits/
https://www.va.gov/health-care/order-prosthetic-socks/
https://www.va.gov/health-care/health-needs-conditions/
https://www.va.gov/health-care/health-needs-conditions/substance-use-problems/
https://www.va.gov/health-care/health-needs-conditions/chemical-hazardous-materials-exposure/
https://www.va.gov/health-care/health-needs-conditions/womens-health-needs/
https://www.va.gov/records/discharge-documents/

Pages with accordions that we need further guidance on:
https://www.va.gov/health-care/eligibility/active-duty/ 
https://www.va.gov/health-care/eligibility/priority-groups/ 
https://www.va.gov/health-care/family-caregiver-benefits/champva/ 
https://www.va.gov/health-care/health-needs-conditions/mental-health/ 
https://www.va.gov/housing-assistance/home-loans/eligibility/
https://www.va.gov/housing-assistance/home-loans/how-to-apply/ 
https://www.va.gov/housing-assistance/home-loans/loan-limits/
https://www.va.gov/records/get-veteran-id-cards/

**Comment by lunascoop** [comment]
Posting the results of my audit of the disability, education, pension and life insurance hubs here.

### Straightforward changes

- Servicemembers’ Group Life Insurance (SGLI)
- Totally disabled or terminally ill policyholders
- Transfer your Post-9/11 GI Bill benefits
- Exposure to hazardous chemicals and materials
- Birth defects linked to Agent Orange
- Current VA disability compensation rates
- Ionizing radiation exposure
- About VA disability rating

**Headers for link teasers**

- Exposure to hazardous chemicals and materials
- Special claims


### Pages with tables that we need further guidance on

- 2022 Veterans disability compensation rates
- 2022 VA DIC rates for spouses and dependents
- 2022 VA DIC rates for parents
- File additional forms for your disability claim
- Servicemembers’ Group Life Insurance (SGLI)
- Family Servicemembers’ Group Life Insurance (FSGLI)
- Veterans’ Group Life Insurance (VGLI)

2022 VA protected disability and death pension rates
(Perhaps an example on how to format headers for rates pages)


### Accordion headers that we need further guidance on

- Evidence needed for your disability claim
- Pre-discharge claim
- Totally disabled or terminally ill policyholders
- Montgomery GI Bill Selected Reserve (MGIB-SR)
- Accelerated payments for high-technology programs


### Other notes and possible changes

- Where did we land on the WEAMS link in the left nav of the education hub? Here’s the related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13480

**Fix bulleted list**

- Fully developed claim for a VA pension
- Camp Lejeune water contamination health issues (bulleted lists)
- Independent and distance learning (sighted language)
- Agent Orange exposure and VA disability compensation (bulleted lists)
- Ionizing radiation exposure: (changes were already made to bulleted lists. need to publish)
- Agent Orange exposure and VA disability compensation: (changes were already made. need to publish)
- Camp Lejeune water contamination health issues:  (changes were already made to bulleted lists. need to publish)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop Posting thoughts as I can...

cc @bethpottsVADEPO 

## Headers for link teasers

### Exposure to hazardous chemicals and materials
- Recommend adding H2 of "Types of exposures" (or something like that) above the link list.
- These are some of the links that I think you noted in slack don't have target and purpose. I agree. And we had also talked at some point about how we should likely change these to this design style:
[h3: Type of exposure]
[descriptive text]
[link: Learn more about disability compensation based on [type of exposure]
- When I went into this page, I also noticed that the intro spoke about "illnesses or conditions listed below." But that's not right. The list is about exposures, not illnesses/conditions. So I replaced the intro with the meta description. http://preview-prod.vfs.va.gov/preview?nodeId=873

### Special claims
- I think you could do the same thing here with an H2 of something like, "Types of special claims"
- Let's also consider the style of h3, descriptive text, target-and-purpose link here

## Pages with tables that we need further guidance on
- Per slack, Randi is following up on the captions question.
- Another question that I have: Are some of the tables ones that we actually want to convert to lists? I know that's a separate effort, so just thinking about what to prioritize in terms of making each of these tables accessible: using the captions vs. making them lists instead.


### Accelerated payments for high-technology programs

## Other notes and possible changes
Where did we land on the WEAMS link in the left nav of the education hub? Here’s the related ticket: #13480
Fix bulleted list

Fully developed claim for a VA pension
Camp Lejeune water contamination health issues (bulleted lists)
Independent and distance learning (sighted language)
Agent Orange exposure and VA disability compensation (bulleted lists)
Ionizing radiation exposure: (changes were already made to bulleted lists. need to publish)
Agent Orange exposure and VA disability compensation: (changes were already made. need to publish)
Camp Lejeune water contamination health issues:  (changes were already made to bulleted lists. need to publish)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @bethpottsVADEPO  We updated the exposure to hazardous materials page like you suggested. We wanted to just get your OK before we made similar updates to other pages with the same structure. We didn't delete the old link list from the Drupal page yet in case we needed to go back to it. Could you take a look and let us know what you think? http://preview-prod.vfs.va.gov/preview?nodeId=873 Thanks!

**Comment by RLHecht** [comment]
@psanders86 When you get a chance can you please review these 2 pages? 
 http://preview-prod.vfs.va.gov/preview?nodeId=26
http://preview-prod.vfs.va.gov/preview?nodeId=19 

These 2 pages had sub bullets we needed to get rid of and we want to confirm that the approach works. If they are good you can publish them. I've already done a copyedit.

**Comment by RLHecht** [comment]
@lunascoop I just found a sighted language instance on this page. When you have a chance can you update and I'll publish? https://www.va.gov/disability/upload-supporting-evidence (In the section Any additional forms needed to support your claim). Thanks!

**Comment by lunascoop** [comment]
@RLHecht I updated the page and it's ready for review.

Upload evidence to support your disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=913

**Comment by psanders86** [comment]
@RLHecht I'm good with the changes to those pages, but question if we need to make another adjustment to http://preview-prod.vfs.va.gov/preview?nodeId=26

There is a reference to a new program announced 5 years ago that VA would begin rolling out soon. If that program is up and running, we should considering changing the copy block. If it's still in the launch phase, we should leave it alone.

[https://app.zenhub.com/files/133843125/53a26926-33bf-4841-9e3f-4137188c88cf/download](https://app.zenhub.com/files/133843125/53a26926-33bf-4841-9e3f-4137188c88cf/download)

**Comment by psanders86** [comment]
@RLHecht We're going to open a new ticket to handle the update to this page at some point. All other changes are good to make as previously indicated. Thanks!

**Comment by psanders86** [comment]
Will do, thanks!


[cid:df9833f6-57b2-431c-82ea-0405e8ec4cc7]

Patrick Sanders

Content Writer



M:  240-444-6116


About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>

Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.­

________________________________

**Comment by psanders86** [comment]
After a discussion with the team, we decided to use "Types of health care programs" for the H2, based on the guidance that we've gotten previously on such pages, such as http://preview-prod.vfs.va.gov/preview?nodeId=873

The Github ticket with that guidance is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35326#issuecomment-1030415752

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @lunascoop @psanders86 I think the changes to the "Types of exposures" pages work well and the links now have target and purpose. @bethpotts let us know if you want to review too since these are disability pages. Thanks!

**Comment by RLHecht** [comment]
Moving this to blocked until we can do the table headers with help from Public Websites.

**Comment by SgardnerPMP** [comment]
@RLHecht  to reach out to Kevin Walsh to get insight on if this is backend or fronted work to complete Table headers have to be resolved at the same time.  See platform or Public websites for update.

**Comment by RLHecht** [comment]
@kevwalsh We should have headers attached to all our tables to make it easier for screen readers. But the current table component doesn't allow for the header to be different sizes. If we wanted to be able to change the size depending on the page, is that something Public Websites would handle?

**Comment by FranECross** [comment]
@RLHecht Is this still something we want to pursue (based on your last comment). Thanks in advance!

**Comment by FranECross** [comment]
Closing old ticket with the assumption that a new one will be created in the future for any changes needed.
