### ISSUE TITLE
526: Stop contestable issue override in non-production

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35335]
## Description

When using the [save-in-progress menu](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress-menu) in form 526, the rated disability list added via the menu is automatically overridden by the current user's rated disabilities provided by the API. This makes it difficult to test data in a local & staging environment. We will need to update both the frontend & backend code to accomplish this:

- backend: Do not modify the `returnUrl` when in-progress data doesn't match the rated disabilities, but only in a **non-production** environment
- frontend: Ignore `updatedDisabilities` provided by the backend save-in-progress data. This is used for comparison & updating of the rated disabilities

## Tasks

- [ ] Backend doesn't modify the `returnUrl` in non-production environments
- [x] Frontend doesn't modify the `ratedDisabilities` when the backend returns `updatedRatedDisabilities`
- [ ] Add tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing

**Comment by Mottie** [comment]
Backend work will be tied to a separate ticket
