### ISSUE TITLE
[ALB / Vets-API] Set up ALB for testing connections to Vets-API in EKS dev 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35344]
## Description
The classic ELB cannot be pointed at a target group (ie we can't send traffic from the classic ELB to Traefik). A new load balancer (ALB) should be created that allows for testing the routing of connections to the Vets-API in EKS dev. 

## Background/context 
See parent epic 

---
## Tasks
- [ ] Create an ALB in the dev VPC (using infrastructure as code; ie Terraform) 
- [ ] Point this ALB to Traefik target group in EKS dev 

## Acceptance Criteria 
- [ ] The reverse proxy in dev can be configured to use this new ALB

**Comment by jhouse-solvd** [comment]
This is a duplicate. Please see #35354

Closing.
