### ISSUE TITLE
[Vets-API] Set up ALB for testing connections in EKS dev 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35345]
## Description
The classic ELB cannot be pointed at a target group (ie we can't send traffic from the classic ELB to Traefik). A new load balancer (ALB) should be created that allows for testing the routing of connections to the Vets-API in EKS dev. 

## Background/context 
See parent epic 

---
## Tasks
- [x] Create an ALB in the dev VPC (using infrastructure as code; ie Terraform) 
- [x] Point this ALB to Traefik target group in EKS dev 

## Acceptance Criteria 
- [x] The reverse proxy in dev can be configured to use this new ALB

**Comment by jsgarmon** [comment]
Created a new ALB in dev with listener on port 3004 that forwards traffic to the Traefik target group (EKS). Verified that we can `curl` the load balancer from a revproxy instance and see the request in Traefik logs (404, since path not pointed to anything yet).
