### ISSUE TITLE
Request provisioning of Elasticache instance (Redis)

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#35354]
## Issue Description
The new platform-console application will need to have an Elasticache (Redis) instance provisioned in AWS. A ticket will most likely need to also be created with the VSP infrastructure team. We will most likely use Redis for Sidekiq and other app caching needs. 

---
## Tasks
- [x] Open ticket with the Infrastructure team
- [x] Elasticache instance is provisioned

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Infrastructure ticket created here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35394

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CTYQL39FE/p1644248605774289
