### ISSUE TITLE
Update "Getting Started" page name to "Collaboration Cycle Kickoff"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35350]
## Issue Description
OCTO-DE Platform Lead Rachael Roueche shared that the name of the[ Getting Started page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) within the Collaboration Cycle section of Platform Website is confusing because there is a [Getting Started section](https://depo-platform-documentation.scrollhelp.site/getting-started/index.html) on Platform Website. She advised that we rename this section, "Collaboration Cycle Kickoff" as that is a more transparent and appropriate title. 

---
## Tasks
- [x] Rename the Getting Start page as specified above

## Acceptance Criteria
- [x] There are no longer 2 "Getting Started" pages/sections within Platform Website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chaseakirby** [comment]
@shiragoodman Is this ticket still needed? I think this was an update that we did while on our 1:1 call. ![image.png](https://images.zenhubusercontent.com/619d1b3396a3389c5e2dd17f/bc69e1c0-102a-4eb2-90d1-eb04cb9008ed)

**Comment by shiragoodman** [comment]
closing!
