### ISSUE TITLE
Start tracking mentions of pain points during sprint demo

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35361]
## Issue Description
As a service design team member I want to start tracking mentions of pain points solved by platform teams work during Demo so that VFS team can know their voice is being heard

---
## Tasks
- [x] Team meeting with Andrea on Tuesday 1/18/2022 to discuss details
- [x] Create an artifact for tracking and decide where it should live
- [x] Start tracking the pain points from 1/19/2022 Demo 

## Acceptance Criteria
- [x] We have an artifact in easy to find place and continuous tracking pain points 
       Link to the tracing document: 
       https://vfs.atlassian.net/wiki/spaces/SDT/pages/2056552466/Metric+Tracking
---
## How to configure this issue

- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)

**Comment by Khyatinp18** [comment]
1/19:
Andrea created a tracking document on Confluence and Taylor will start tracking it from today.
