### ISSUE TITLE
Create a draft to track research  where customers don't feel like their voices are heard

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35365]
## Issue Description
As a service design team member I want to start tracking  research where customers don't feel like their voices are heard so that platform teams and leadership can be aware of what pain points needs to be resolved  

---
## Tasks
- [x] Team meeting with Andrea on Tuesday 1/18/2022 to discuss details
- [x] Collect customer data from historical research
- [x] Create a draft of artifact for tracking research and decide where it should live ([draft here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2066677817/Customer+Insight+Tracking))

## Acceptance Criteria
- [x] We have an artifact in easy to find place and continuous tracking research 
---
## How to configure this issue

- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)

**Comment by tayism** [comment]
Collected many customer mentions from quarterly surveys. Started creating the artifact in Confluence [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2064744606/Customer+key+mentions).
