### ISSUE TITLE
Determine K8s permissions model for pod command execution

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35369]
Status: Jul 19, Waiting on Infra

Blocked by #35395

## Issue Description
Developers will need the ability to access K8s pods/containers for debugging and other development purposes. Developers don't currently have a way to access the running pods/containers for shell access, etc. We will need to define a permissions model for platform and vfs members to provide the ability to access to their K8s resources. We may want to start with access to the development environment.

Background: When debugging a configuration issue for the PgHero deployment, we needed shell access to a container running on a pod. We did not have this access, so it made it incredibly difficult to debug. 

---
## Tasks
- [ ] Open a ticket with the platform infrastructure team

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
