### ISSUE TITLE
Create content for mobile app alert on VA letters page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35360]
## Issue Description
The VA Mobile team would like to post an alert on the [Download VA benefit letters](https://staging.va.gov/records/download-va-letters/) page to make users aware they can use the mobile app to download VA letters. The content should be similar to what is currently on the Claim Status Tool:

![Screen Shot 2022-01-13 at 2.19.57 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/9477dd9c-e635-4244-969b-c92d6ae1e6e2)

Once the content is created we need Public Websites to create a react widget for us to place on the letters page since it will display different text depending on what system the user is on. 

Intake request ticket #33200 for background.

## Tasks
- [x] Write content for alert
- [x] Review content
- [ ] Send text to Public Websites
- [ ] Add react widget to letters page
- [ ] Review and publish page
- [ ] Notify product team that alert is live

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Here's the proposed text for the new alert:

H2: Download your VA letters on your mobile device
You can use our new mobile app to download your VA letters on your mobile device. Download the **VA: Health and Benefits** mobile app to get started.

Download the app from the App Store
Download the app from Google Play

And since there will be 2 alerts in a row, here's the proposed H2 to put above the second one:
H2: How to access your VA letters and documents online

**Comment by RLHecht** [comment]
@SgardnerPMP This is a ticket that can be broken out into more. This current ticket is complete once Beth signs off. We then need to open an intake request with PW for them to create the widget. The next ticket for us would be to put the react widget on the page and make any other content changes around it in Drupal and then publish.

**Comment by bethpottsVADEPO** [comment]
@RLHecht First thing I'd like to verify is that it works ok to download letters to mobile devices. @MarciMcGuireGCIO did research on downloading PDF forms to mobile devices. I'd like to make sure that the problems Veterans were encountering had to do only with fillable PDFs not functioning on mobile--and that downloading a letter isn't a problem. @MarciMcGuireGCIO would you mind weighing in here?

Since the process list on the vaccine records page is a different use case for the mobile app info than this request for an info alert, I'd say no process list needed at this point. 

For the content, we'll be overusing "get" if it's in both H2s and the first word of the link text for both links. I'd recommend:
Download your VA letters on your mobile device / Download your VA letters online

This text is also tricky because the user needs to first download the app, then they can download letters. Two things to download. I moved "to get started" to the front of the second sentence to try to make that less confusing. 

H2: Download your VA letters on your mobile device
You can use our new mobile app to download your VA letters on your mobile device. To get started, download the **VA: Health and Benefits** mobile app.

Get the VA Health and Benefits app from the Apple app store
Get the VA Health and Benefits app from the Google Play store

**Comment by MarciMcGuireGCIO** [comment]
Hi @bethpottsVADEPO and @RLHecht I have been OOO, so I am sorry for not responding sooner.  Indeed, the problem with the PDFs I reviewed was related to fillable forms. I didn’t observe any problems with read-only documents.

**Comment by RLHecht** [comment]
Thanks! 

@SgardnerPMP Here is the finalized content to go into the react widget. We will need Public Websites to create this so we need to open an intake request:

H2: Download your VA letters on your mobile device
You can use our new mobile app to download your VA letters on your mobile device. To get started, download the **VA: Health and Benefits** mobile app.

[Get the VA: Health and Benefits app from the Apple app store](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596)
[Get the VA: Health and Benefits app from the Google Play store](https://play.google.com/store/apps/details?id=gov.va.mobileapp)

**Comment by RLHecht** [comment]
Posted content in the PW ticket #35382 for them to create widget.
