### ISSUE TITLE
HLR v2: Show opt-in legacy appeals page dynamically

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35366]
## Description

Currently (in staging, behind a feature flag), the opt-in legacy appeals checkbox page is always shown. The Higher-Level Review for contestable issues endpoint now includes data reporting legacy issues, and we can use that to dynamically show the opt-in page.

## Tasks

- [ ] Dynamically show the legacy opt-in page based on data from the legacy API
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
