### ISSUE TITLE
Auth Profile - Personal Info Revision - Update 'Why do we ask for this" FAQ

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35374]
## Background
Since we are now asking for new personal information (including information that is highly sensitive), we need to provide assurance that this information is being collected solely to provide better service and care to the Veteran.

## Tasks
- [ ] Request copy to describe how this information will be used
- [ ] Create Design ticket to add this information to the Sketch files
- [ ] Create FE ticket to add this information to the Personal Information page

## Acceptance Criteria
- [ ] Content request has been opened
- [ ] Design ticket has been created
- [ ] FE ticket has been created

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
