### ISSUE TITLE
[Debt Letters] Refactor alerts to use va-alert

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35399]
## Issue Description

The majority of alerts used by Debt Letters are custom components and should be refactored to use [va-alert](https://design.va.gov/components/alertboxes) to ensure consistency throughout the portal

---
## Tasks
- [ ] Refactor all alerts to use the `va-alert` design system component
- [ ] Consider rendering alerts using [dot notation](https://reactjs.org/docs/jsx-in-depth.html#using-dot-notation-for-jsx-type) `<Alerts.Error />` refer to MCP for details

## Acceptance Criteria
- [ ] All alerts should render using `va-alert`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
