### ISSUE TITLE
Platform Infrastructure: Make 'access to Parameter Store' a service that is offered by the platform  

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35418]
## Problem Statement 
Development teams need the ability to manage secrets in Parameter Store (PS). The capability exists the process is cumbersome. This acts as a blocker and creates overhead for the development teams (DT) and the Infrastructure Team (IT) because there are many manual steps. 

## Background / Context 
The pattern that is currently followed is something like this: 
- DT wants to store secrets that can be consumed by an application for use in automation (ie CI/CD, etc) 
- DT creates a GH issue (examples linked below) 
- IT creates a dedicated path in PS for DT
- IT retrieves the secret from DT via Keybase (or another secure channel)
- IT creates an AWS IAM service account, _ie <svc-gha-development-team-name>_ 
- IT writes the secret to a path in PS
- IT givers permission to <svc-gha-development-team-name> for fetching/writing to the PS path
- Optional: IT sets up AWS IAM permissions for DT to manage the PS path directly 

## How might we...
...might we codify this as a service? 
...make it easier for developers to set up secure secrets for the application? 
...make setup and management of this access less cumbersome? 
...automate aspects of this process to make it more efficient for end-users? 
...automate aspects of this process to make it more efficient for system administrators? 

## Hypothesis or Bet
We believe this will make it easier for VFS teams to use secrets in their application. 
We believe this will allow VFS and Platform Crew development teams to set up secrets for an application more quickly. 
We believe this will reduce the support burden for offering this functionality to end-users. 

## We will know we're done when... ("Definition of Done")
The following exists: 
- the service is listed on the platform website
- developer-oriented documentation for the service exists on the platform website
- there is internal documentation (such as a playbook) for platform support personnel
- there are machine-readable GitHub issue templates (ie with boilerplate text, fields, choices; pre-defined by YAML; w/ limited free-form input)
- Developers are able to use the service 
- Future: developers that have used the service have provided feedback so that we can iterate on it

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
TBD

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by oseasmoran73** [comment]
Putting my thought on here. May not be valid, but a thought came to mind:

We can potentially have a Github Action that works similar to SOCKS. We can potentially have dropdown in issue statement of team to have a table to properly append.

Again just a thought. Not saying this is the approach we want to take :)
