### ISSUE TITLE
[Internal] Transition to Figma

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#35415]
VAOS design team is moving from Sketch cloud to Figma. 

### Tasks

**Add/convert VA design system to Figma**
- [x] Convert color styles - @Cieramaddox 
- [x] Convert text styles - @Cieramaddox 
- [x] Convert grids - @Cieramaddox 
- [x] Convert icons - @Cieramaddox 
- [x] Convert buttons - @Cieramaddox 
- [x] Convert form controls - @Cieramaddox 
- [x] Update VA headers and footers - @Cieramaddox 

**Add VAOS styles to Figma**
- [x] Convert VAOS Templates and Styles - @outerpress 

**Move Sketch files to Figma**

- [x] Historic VAOS Sketch files
- [x] Current files/in progress work

**Create links/pointers to new Figma projects**

- [x] From Sketch project
- [x] From VAOS design Github readme: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/README.md

**Relink old Sketch links**
- [x] Update any links in current tickets to point to new Figma files
