### ISSUE TITLE
Create documentation around static vs. tool pages for VFS teams

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35429]
## Issue Description
Shira Goodman let us know that VFS teams don't have a great understanding of what qualifies as a "static page" and what is actually a tool/service. She asked for us to provide documentation they can link to so that teams are more aware of the difference.

## Tasks
- [x] Create Github doc about what static pages are (Randi)
- [x] Send to Beth to review (Randi)
- [x] Incorporate feedback (Randi)
- [x] Send to Platform team (Randi)

## Acceptance Criteria
- [x] Github doc on static pages created and shared with VFS teams

**Comment by RLHecht** [comment]
@bethpottsVADEPO I created a github doc for this in our teams folder: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md

Please let me know if you have any edits. Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht I edited this and I'd love for a PW FE to take a look to make sure we're talking about dynamic pages in the right way. Also would be great to have Shira take a look and see if this is what she was envisioning. The only thing you might want to add first is a specific section or a call-out somewhere about the content team's role in product work as far as the entry point edits we make to static pages. 

@brianalloyd could you work an accuracy review of this documentation into one of your sprints? Specifically the short section called "What's a dynamic page?" The purpose of this is to help VSA teams understand content's involvement in product work.

**Comment by brianalloyd** [comment]
Absolutely, we've lost some domain knowledge with our FE turn over and we'll need to lean heavy on our documentation in support. I have this slotted for this sprint for action.

**Comment by RLHecht** [comment]
Moving to blocked until PW finished with their part.

**Comment by bethpottsVADEPO** [comment]
@RLHecht You could go ahead and send to Shira and PW will take a look when they can work it in. PW has a lot going on, and with their recent departures this definitely won't be a priority. I don't think we need to wait for their review. Thanks!

**Comment by shiragoodman** [comment]
thank you @RLHecht ! This is super helpful. Would it be okay if we linked it in our Collab Cycle Kickoff documentation?

**Comment by RLHecht** [comment]
Yep, not a problem! And if you're finding that teams still have questions or any of this is unclear, please let us know so that we can update it and make it as helpful as possible.
