### ISSUE TITLE
Original Claims 526 - PIF in use error resolution tasks

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35420]
## Issue Description
In an effort to address the PIF in use error, one of the things we need to do is ensure the claim-id is included in a successful submission. This will also help with migrating away from using SSN when troubleshooting claims issues.

---
## Tasks
- [x] Investigate how to Include claim id in form 526 successful submission email

## Acceptance Criteria
- [ ] Email template updated. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cnemeth** [comment]
NOTE: We already seem to include `claim_id` in the confirmation email:

1. `Form526Submission#send_form526_confirmation_email#submitted_claim_id`
2. `Form526ConfirmationEmailJob#perform#claim_id`

**Comment by cnemeth** [comment]
Closing ticket. We already include `claim_id` in `form526_confirmation_email#personalization_params`. The email is generated by `notification-service` so updating the relevant email template is outside of our area of responsibility.
