### ISSUE TITLE
526: Add PTSD bypass question to flow

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35437]
## Description

A Veteran with PTSD should not be asked detailed questions that could be triggering. To accomplish this, we are adding the following question:

<details><summary>Combat question</summary>

<img width="708" alt="Is your PTSD related to a situation where you feared hostile military or trerrorist activity during your active military service?" src="https://user-images.githubusercontent.com/136959/149575235-907459e0-262b-4a49-acfb-52e88e98dd60.png"></details>

<details><summary>Non-combat question</summary>

<img width="675" alt="Screen Shot 2022-01-14 at 4 06 48 PM" src="https://user-images.githubusercontent.com/136959/149591645-6ad257ca-77e1-4b79-af63-3f440368b73f.png"></details>

When the Veteran chooses "Yes" we will bypass all form 781 questions and take them to the supporting evidence page

- Design: https://www.sketch.com/s/a8ee3307-72ec-40a6-968a-4d92477894e5/a/eKGJOEp
- Overall flow: https://app.mural.co/t/vsa8243/m/vsa8243/1639070794497/b605ba85a76c75be7d195bd4090286b6e8061453?sender=kstachura1551
- Flow if both combat & non-combat are chosen: https://app.mural.co/t/vsa8243/m/vsa8243/1642194148215/88c543c0856829df990f81edfb9e01c6a73473a6?sender=kstachura1551
- Discovery work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32237

## Tasks
- [ ] Add PTSD combat & non-combat questions
- [ ] Conditionally show form 781a questions based on the new question answer
- [ ] Add unit tests
- [ ] Update mock data for e2e tests
- [ ] Reorder pages as needed (more pages will be reordered later)

## Definition of done
- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
These changes are available in staging

**Comment by Mottie** [comment]
Missed adding data to PTSD entry indicating the form was skipped due to feared hostile or terrorist activity.
