### ISSUE TITLE
[UI] Edits to Editing based upon Design Council Feedback

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35447]
# Description
The editing design pattern went before the design council on Friday, January 14th. Our experiment was approved. However, they had some feedback on the pattern. We need to make the following changes before we implement editing:

- Correct title and buttons. 
  - Option 1: "Review and update your contact information" with "Continue" button
  - Option 2: "Is this your current contact information?" with "Yes" button.
- Add annotations for the edit links ARIA labels, so we "Edit Mailing Address" and "Edit Work Phone."
- Do we get leave in the blue bar or change it out for the horizontal rules pattern that matches closer to check [answers pattern on uk.gov](https://design-system.service.gov.uk/patterns/check-answers/)/[this version that Ryan created](https://www.sketch.com/s/bd82a1fb-3fcc-47a2-829e-bd2fdca8d66e/a/v8JwZz1)?
- Cut long titles down to a max. of 4 lines when at a modal screen size.
- Draw out the entire pre-check-in workflow and not just the editing parts (so we don't miss another button situation)

# Tasks
- [x] Update Sketch wireframes

# Acceptance Criteria
- [x] Review designs with UX, product, Patrick/Stephen, and engineering
- [x] Update Sketch link with the design doc (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md).

**Comment by kristenmcconnell** [comment]
Profile also has the ability to "Remove." See this [wireframe](https://preview.uxpin.com/e21218c405e4475d518bc209ffd66405a9633080#/pages/145359491/simulate/no-panels?mode=i). Should we have "Remove" as well?

**Comment by kristenmcconnell** [comment]
Decision: Use horizontal rules and "Edit."

**Comment by kristenmcconnell** [comment]
Decision: Don't deal with "Remove" for now.

**Comment by kristenmcconnell** [comment]
We should have a primary button (unless the use case doesn't call for it).

**Comment by kristenmcconnell** [comment]
Interactive Sketch prototype: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/PGzGPJr/play

**Comment by kristenmcconnell** [comment]
@zach-park Interactive prototype link added to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md.

**Comment by zach-park** [comment]
Hi @julieadair1 @jparker0425 , the editing pre-check-in UI is ready for review:
[Sketch - Editing wireframes](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/56D56797-C485-4B53-95E7-36EBF66B6698/canvas)
[Interactive Sketch prototype](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/PGzGPJr/play)
Cc: @kristenmcconnell @niradatta1 @ytsaoca @stephenBarrs @acrollet @dcgoodwin2112 @brianseek @mdewey

**Comment by jparker0425** [comment]
Discussed with UX and this item is complete
