### ISSUE TITLE
Add style guide entry about time zones for individual actions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35445]
## Issue Description
Currently our style guide entry on [time zones ](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones) says to always used ET. This is the case when we are publishing times for VA offices across the country. However, the entry doesn't take into account users saving work in a tool or completing an application in a different time zone. It could be confusing to a user to see a time stamp in a different time zone than the one they are currently in.

We need to update our entry to include these use cases. If a user is working on an application or tool and there is a time stamp for work saved or in progress, this should be shown in their local time zone.

## Tasks
- [x] Update style guide entry (Randi)
- [x] Review (Beth)
- [x] Publish (Randi)
- [x] Let design system team know change was made (Randi)

## Acceptance Criteria
- [x] Style guide contains updated time zone entry

**Comment by RLHecht** [comment]
@bethpottsVADEPO Just assigned you as a reviewer to the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/631
