### ISSUE TITLE
AVA Phase III Notetaking Prep

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#35451]
## Issue Description
Build a notetaking document to use during the AVA Phase III usability sessions

---
## Tasks
- [x] Build a spreadsheet
- [x] Test the spreadsheet during the pilot session

## Acceptance Criteria
- [x] The doc has been built
- [x] The doc has been tested
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Notetaking doc](https://docs.google.com/spreadsheets/d/1rbVr0FnRiWc8FgymamzGfUYfF4LweIV6v-0nWlb48gE/edit#gid=520106127)
