### ISSUE TITLE
Use alert web component in facility status template

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#35460]
## Issue Description

The [`health_care_facility_status`](https://github.com/department-of-veterans-affairs/content-build/blob/dc7607118085d0615dd2958004efa9d9ca4d2a0c/src/site/layouts/health_care_facility_status.drupal.liquid#L22-L39) liquid template has 3 instances of the older HTML/CSS `usa-alert` combination. Here's an [example](https://staging.va.gov/boise-health-care/status/index.html) of the success alert:

![image](https://user-images.githubusercontent.com/2008881/149815812-3d9ec290-bd75-475e-a16a-91ea7b5b926b.png)

The goal is to have the template use the `<va-alert background-only show-icon>` Web Component.

---
## Tasks
- [ ] Use `<va-alert status="info">` web component for normal facility status
- [ ] Use `<va-alert status="warning">` web component for limited facility status
- [ ] Use `<va-alert status="error">` web component for closed facility status

## Acceptance Criteria
- [ ] `usa-alert` CSS class is no longer used in `health_care_facility_status` template
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
usa-alert is still present on VAMC pages - [example ](https://www.va.gov/boise-health-care/status)
![image](https://user-images.githubusercontent.com/55411834/184218296-d7fad27a-bfca-4856-937b-1377e125506a.png)

**Comment by caw310** [comment]
Closing as this is old and the VADS components have been updated ad the template should be using the new comopnent. If you are still seeing the issue with the new components, file a new bug.
