### ISSUE TITLE
[Administrative] CAG & Venafi access for Oseas Moran

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35466]
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices.

### Tasks
- [x] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG 
- [x] Get access to Venafi - documentation [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)

### Acceptance Criteria
The team member will be able to do the following:

  - [x] Access CAG
  - [x] Access [Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)
  - [x] Request SSL certificates

**Comment by oseasmoran73** [comment]
Submitted EPAS request. Emailed CORS rep to approve request and will continue to move forward with the doc

**Comment by oseasmoran73** [comment]
EPAS has now synced with Venafi and able to create certs per documentation. Closing ticket.
