### ISSUE TITLE
[Administrative] CAG & Venafi access for Rebecca Tolmach

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#35467]
In order to ensure that our team members can adequately support the platform's infrastructure, we need to ensure that all those eligible are able to access the VA's Citrix Access Gateway (remote access) as well as the Venafi portal. This access allows them to do important things such as request the renewal of SSL certificates that are needed on various machines and devices.

### Tasks
- [x] Contact COR and Enterprise Service Desk (ESD) as needed to get access to CAG 
- [x] Get access to Venafi - documentation [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)

### Acceptance Criteria
The team member will be able to do the following:

  - [x] Access CAG
  - [x] Access [Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)

**Comment by rmtolmach** [comment]
Blocked until background check goes through. Submitted documents and got fingerprinted 1/14.

**Comment by rmtolmach** [comment]
Update: I submitted the e-QIP questionnaire on 1/24 and it was released to the Defense Counterintelligence and Security Agency (DCSA) today.

**Comment by rmtolmach** [comment]
Update: I have CAG access. Now working through the Venafi access instructions.

**Comment by rmtolmach** [comment]
I have access to Venafi and I updated the documentation https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates

**Comment by jhouse-solvd** [comment]
I deleted the last AC as it was duplicative and inaccurate. I think you can close this one out!

**Comment by rmtolmach** [comment]
Awesome, thanks! Was just about to ask about that, Jesse. Closing... :tada:
