### ISSUE TITLE
Add Slack Webhooks to SSO Smoke Tests

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#35465]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The VSP Identity Team is creating a series of [SSO Smoke Tests](https://github.com/department-of-veterans-affairs/va.gov-sso-smoke-tests) to automatically cover the entire VA.gov login workflow with a variety of CSPs and accounts. These tests will be run once every 30 minutes & the results should be publicly announced in the `va-identity-alerts` Slack channel in order to notify Identity team members of any test failures. This story covers the integration of the Slack reporting into the smoke tests' Github actions workflow.

---
## Tasks
- [x] Parse the XML test results artifact to make the overall test results (tests attempted, test failures, test errors) available within the github actions pipeline
- [x] Add a Slack webhook to post each [Identity Integration Test](https://github.com/department-of-veterans-affairs/va.gov-sso-smoke-tests/actions/workflows/main.yml) run's results to `va-identity-alerts` via the VSP Identity Bot Slackbot 

## Acceptance Criteria
- [ ] Every run of the Identity Integration Test will report its results to the `va-identity-alerts` channel, with a link that can be followed back to the test run details on Github

**Comment by nsoutouras** [comment]
Waiting on new fork repo as of 1/24/22

**Comment by nsoutouras** [comment]
@bramleyjl please add description
