### ISSUE TITLE
Add VA health connect number to Facility Locator search results for next roll-out 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35477]
## Issue Description
VA health connect, a new phone method for Veterans to communicate with VA health, is being rolled out VISN by VISN. When a VISN rolls out, the region specific number needs to be displayed in search results for relevant facilities. The number for VA health connect is the same for all facilities within the VISN and can be hard coded for this implementation. We will likely need to return to this work and implement a number using a data field in the future.

The work to implement VISN 8 (in #32552) should be a pattern which can be followed for future implementations. 

```
renderResultItems(query, results) {
    return results.map((result, index) => {
      let item;
      const services = result?.attributes?.detailedServices;
      const walkInsAccepted = Array.isArray(services)
        ? services[0]?.walkInsAccepted
        : 'false';

      const showHealthConnectNumber =
        result?.attributes?.visn === '8' &&
        query?.facilityType === 'health' &&
        this.props.facilityLocatorShowHealthConnectNumber;

```

## Data from Lighthouse
We're using the VISN to hard code the display of the VA health connect phone number until Lighthouse can send this field and value from CMS. 

<details>
<summary> We are able to identify the VISN from data supplied by Lighthouse. </summary>

```
{
  "data": [
    {
      "id": "vha_688",
      "type": "va_facilities",
      "attributes": {
        "lat": 38.9311137,
        "long": -77.0109110499999,
        "name": "Washington VA Medical Center",
        "visn": "20",
        "hours": {
          "friday": "9AM-5PM",
          "monday": "9AM-5PM",
          "sunday": "Closed",
          "tuesday": "9AM-5PM",
          "saturday": "Closed",
          "thursday": "9AM-5PM",
          "wednesday": "9AM-5PM"
        },
```
</details>

<details>
<summary> Screenshots before and after VISN 8 implementation </summary>

![image](https://user-images.githubusercontent.com/55411834/140570738-9e390350-e0f1-4600-a053-62c58bef4e58.png)

![image](https://user-images.githubusercontent.com/55411834/149843988-7f18f7b5-2b9b-4ba9-bf6e-772947605451.png)

</details>

---
## Tasks
- [ ] Add hard coded "VA health connect" phone number to search results when facility type = VA health and VISN= 2 or 17
- [ ] When VISN= 2, the VA health connect number = 800-877-6976
- [ ] When VISN = 17,  the VA health connect number = 833-284-7212

## Testing
For VISN 2, this work can be validated with the following facilities (one for each health care system in the VISN)

- [ ] VA Albany: Catskill VA Clinic in Catskill, NY 
- [ ] VA Bronx: Yonkers VA Clinic in Yonkers, NY
- [ ] VA Finger Lakes: Coudersport VA Clinic in Coudersport, PA
- [ ] VA Hudson Valley: Castle Point VA Medical Center in Wappingers Falls, NY 
- [ ] VA New Jersey: Morristown VA Clinic in Morristown, NJ
- [ ] VA New York Harbor: Brooklyn VA Clinic in Brooklyn, NY
- [ ] VA Northport: East Meadow VA Clinic in East Meadow, NY
- [ ] VA Syracuse: Erie East VA Clinic in Syracuse, NY
- [ ] VA Western New York: Buffalo VA Medical Center in Buffalo, NY

For VISN 17, this work can be validated with the following facilities (one for each health care system in the VISN)

- [ ] VA Amarillo: Clovis VA Clinic in Clovis, NM
- [ ] VA Central Texas: Austin VA Clinic in Austin, TX
- [ ] VA El Paso: El Paso South Central VA Clinic in El Paso, TX
- [ ] VA North Texas: Garland VA Medical Center in Garland, TX
- [ ] VA South Texas: Frank M. Tejeda Department of Veterans Affairs Outpatient Clinic in San Antonio, TX
- [ ] VA Texas Valley: Old Brownsville VA Clinic in Corpus Christi, TX
- [ ] VA West Texas: Wilson and Young Medal of Honor VA Clinic in Odessa, TX 

## Acceptance Criteria
When facility type = VA health and VISN= 2, search result cards include 
- [ ] Main number: (phone)
- [ ] VA health connect: 800-877-6976
- [ ] Mental health: (phone)

When facility type = VA health and VISN= 17, search result cards include 
- [ ] Main number: (phone)
- [ ] VA health connect: 833-284-7212
- [ ] Mental health: (phone)

**Comment by mmiddaugh** [comment]
![va health connect roll-out schedule](https://user-images.githubusercontent.com/55411834/150576025-f47fc460-d3e8-4a46-a8a5-7b3c3eef4f14.PNG)

**Comment by mmiddaugh** [comment]
Validated with VISN 2 and 17 locations, confirmed functionality for VISN 8 and maintained functionality for other locaitons
