### ISSUE TITLE
Add VA health connect number to VAMC pages for next roll-out

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35476]
## Issue Description
VA health connect, a new phone method for Veterans to communicate with VA health, is being rolled out VISN by VISN. When a VISN rolls out, the region specific number needs to be displayed under Location and contact information on the relevant system, facility, and Locations pages. The number for VA health connect is the same for all facilities within the VISN.  

Main and mental health numbers are data and will continue to be displayed. (not replaced)

This was hardcoded into the front end for VISN 8. Since then, CMS has added a field `field_va_health_connect_phone` to capture this information. This field lives at the system level so to list it for the facility, it has to be retrieved via each  VAMC facility’s `field_region_page`

<details>
<summary> Current behavior for VA health locations (which have not rolled out VA health connect) </summary>

**System page:** 
![image](https://user-images.githubusercontent.com/55411834/149843121-4188c882-9159-4756-9022-38765f2421ba.png)

**Facility page:** 
![image](https://user-images.githubusercontent.com/55411834/149842670-0203f1b5-9620-48b3-abe3-5221a2f02170.png)

**Locations page:** 
![image](https://user-images.githubusercontent.com/55411834/149843037-1debca4b-5c2b-4814-b5fa-3b49d93f091b.png)

</details>

<details>
<summary> Expected behavior for VA health locations which have rolled out VA health connect </summary>

**System home page:** 

![image](https://user-images.githubusercontent.com/55411834/149842845-8ea53be7-03ea-4279-9987-8a60c9efbe7d.png)

**Facility page:** 

![image](https://user-images.githubusercontent.com/55411834/149842437-c3e6fd02-19a2-42aa-b523-cdc5489f3022.png)

**Locations page:** 

![image](https://user-images.githubusercontent.com/55411834/149842968-750bc1ad-0d58-4c49-af71-e36a04d93e3f.png)

</details>

## Tasks

- [ ] Add `field_va_health_connect_phone` to liquid template - must be retrieved via each  VAMC facility’s `field_region_page` for facilities
- [ ] Add the value to the phone number section under Location and contact information, consistent with this format

> Main number: (phone)
> VA health connect: x-xxx-xxx-xxxx (based on field value)
> Mental health: (phone)

- [ ] Remove code for hardcoded value for VISN 8
- [ ] Add flipper to control display of VA connect number

**For testing purposes**, the VA health connect  number is populated for VA Orlando health care, so the number should be available via `field_region_page:field_va_health_connect_phone` for each of the following facilities in that system:

- Orlando VA Medical Center
- Clermont VA Clinic
- Deltona VA Clinic
- Kissimmee VA Clinic
- Lake Baldwin VA Clinic
- Palm Bay VA Clinic
- Port Orange VA Clinic
- Tavares VA Clinic
- Viera VA Clinic
- Westside Pavilion VA Clinic
- William V. Chappell, Jr. Veterans' Outpatient Clinic

## Acceptance Criteria
Assuming the phone number is present in CMS and the VISN has rolled out, 
- [ ] Veterans viewing the system home page will see the VA health connect phone number displayed within the Locations and contact information for visible facilities 
- [ ] Veterans will see the VA health connect phone number displayed within the Locations and contact information section of facilities pages
- [ ] If the VA health connect number field is null, no label will be displayed. 
- [ ] Main phone number and mental health numbers are still present, whether or not the VA health connect number is present
- [ ] Display of VA connect number can be toggled on/off

**Comment by mmiddaugh** [comment]
![va health connect roll-out schedule](https://user-images.githubusercontent.com/55411834/150575893-2cec54c5-519d-451b-8abd-d5a0c2db7c2c.PNG)

**Comment by GcioNapoleon** [comment]
closed by accident

**Comment by mmiddaugh** [comment]
a fake health connect number (123-456-7890) has been added to [Mountain Home] (https://main-r1q3cbg0fgwgnmlnkoxsoxcsc37hwmrh.demo.cms.va.gov/node/14993/edit) but it is not being displayed on the front end. 

![image](https://user-images.githubusercontent.com/55411834/153508587-f54a1259-d228-48e8-b014-120d644c268c.png)

![image](https://user-images.githubusercontent.com/55411834/153508499-db8d153b-1af9-468a-976e-d164a7928bec.png)

**Comment by GcioNapoleon** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8094
[#8094 multiple Tugboat demo environments showing 504 Gateway Time-out error](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8094)

**Comment by mmiddaugh** [comment]
@GcioNapoleon 
## Testing in Tugboat

**Montana health care**

- Jane entered 987-654-3210 as the VA health connect number for this system.
- The VA health connect number is 987-654-3210 on the Montana health care [system home page](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/montana-health-care/)
- It is displayed as 877-741-3400 on the [locations page](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/montana-health-care/locations/). 
- No health connect number is shown at all on the [facility home page](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/montana-health-care/locations/benjamin-charles-steele-va-clinic/). 


<details>
<summary> Tugboat screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/156271513-a94062cc-ce79-4f18-a97c-0cb23c000919.png)![image](https://user-images.githubusercontent.com/55411834/156274138-be2eec66-91be-4337-b966-53e39d6f61ac.png)
![image](https://user-images.githubusercontent.com/55411834/156271186-875431b4-12b1-4d5c-a647-ed8e6031c5b7.png)
![image](https://user-images.githubusercontent.com/55411834/156271298-6d1fecff-6834-4a15-b898-3c65fdc9111d.png)
</details>

**Walla Walla health care**

- Jane entered 000-000-0000 as the VA health connect number for this system. 
- The [main system page](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/walla-walla-health-care/) displays VA health connect: 000-000-0000 for Jonathan M. Wainwright Memorial VA Medical Center but displays 877-741-3400 for the same facility on the [locations page](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/walla-walla-health-care/locations/). 
- No VA health connect number is displayed for the facility on the [facility home page.](https://web-ooot367gu64zfxir7f3r5y8sfv9tmvqd.demo.cms.va.gov/walla-walla-health-care/locations/jonathan-m-wainwright-memorial-va-medical-center/)

<details>
<summary> Tugboat screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/156272249-f1cb96ad-e178-4995-91fd-8eab428ae29b.png)
![image](https://user-images.githubusercontent.com/55411834/156273069-945ac876-1bdd-4949-bc61-cf14c9b4ab48.png)
![image](https://user-images.githubusercontent.com/55411834/156272928-21785113-bd95-4017-b88c-d4219fde84c7.png)
![image](https://user-images.githubusercontent.com/55411834/156273755-8dbed521-5368-4826-a847-b4d9304471de.png)
</details>

**Comment by mmiddaugh** [comment]
@GcioNapoleon 
## Next round of testing in Tugboat
CMS side: https://cms-b3facikpoltuklqcnqwilcehrc8lxaja.demo.cms.va.gov/user/1

**Cheyenne health care**

- Jane entered 111-111-1111 as the VA health connect number for this system.

Working as expected
- Main system page (/cheyenne-health-care) displays correct VA health number. 
- Locations page (/cheyenne-health-care/locations) shows correct VA health connect number for all facilities listed

Not working as expected
- VA health connect number does not display on facility page (i.e. /cheyenne-health-care/locations/cheyenne-va-medical-clinic)

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/157065910-d9463c0b-af8f-4d31-890f-6f7f72e1286c.png)
![image](https://user-images.githubusercontent.com/55411834/157072570-2f58216b-a1b8-4606-a866-5f14a85ff3a2.png)
![image](https://user-images.githubusercontent.com/55411834/157072889-59b0662a-85de-4a44-a073-5b5efa80f95e.png)


</details>

**Tomah health care**

- Jane entered 999-999-9999 as the VA health connect number for this system.
- Same as Cheyenne - correct VA health connect number is displayed for main system page and locations page but not on individual facility pages.

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/157065730-cb535f40-8b33-4759-ac67-c6408737ddc3.png)
![image](https://user-images.githubusercontent.com/55411834/157073491-2e4df604-d7d6-4889-81c7-53750f0288fb.png)
![image](https://user-images.githubusercontent.com/55411834/157073544-e26d998b-8921-4800-b4ee-a6fc64da9ee2.png)
![image](https://user-images.githubusercontent.com/55411834/157073625-4d4c31c7-679c-4d19-9130-8f42bf4e2659.png)

</details>

**Maine health care**

- Jane entered 555-555-5555 as the VA health connect number for this system.
- Same as above - correct VA health connect number is displayed for main system page and locations page but not on individual facility pages.

Also confirmed that Bay Pines health care no longer displays the hard coded VA health connect phone number. There is no associated VA health connect number for Bay Pines in this environment so it is expected that this page would not show the number. This is behaving as expected on system home page, individual facility pages, and locations page.

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/157074443-f85023f9-7620-4609-994d-acba6c2f1ef4.png)
![image](https://user-images.githubusercontent.com/55411834/157074519-ffdef995-9ca2-4206-bc0d-66db04046397.png)
</details>

**Comment by mmiddaugh** [comment]
Will create a separate issue to pull the VA health connect number through to individual facility pages.

**Comment by mmiddaugh** [comment]
Currently, Orlando is the only system with VA health connect in place in CMS. I've filed a request with the CMS support team to add the VA health connect number to the remaining VISN 8 locations: [VAHELP-3676](https://va-gov.atlassian.net/servicedesk/customer/portal/3/VAHELP-3676). @GcioNapoleon we'll need to wait for this to be complete before we merge this issue and #38077, fyi

**Comment by mmiddaugh** [comment]
@GcioNapoleon This can be merged with #38077 on Monday.
