### ISSUE TITLE
[DISCOVERY] Lighthouse Facilities API v1 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35478]
## Issue description
The Lighthouse Facilities API is being redesigned to incorporate new features, including health services data from CMS. The Facilities team will need to keep pace with the changes to the existing V0 API and plan for the transition to V1 so that we can maintain functionality and leverage the new available data.

[Facilities.API.v1.Endpoint.Design (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7884976/Facilities.API.v1.Endpoint.Design.1.docx)
See [annotated.Facilities.API.v1.Endpoint.Design (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7890984/annotated.Facilities.API.v1.Endpoint.Design.1.docx) for comments/questions discussed during grooming

## Tasks
- [ ] Review current functionality - Lighthouse  Facilities API and Facility Locator
- [ ] Review attached documentation to confirm it can serve as transition documentation for this work and could be understood by someone relatively new to this application

## Acceptance criteria
- [ ] Attached documentation has been reviewed  
- [ ] Any additional comments needed for understanding are added to the document or to this issue

**Comment by mdewey** [comment]
# Notes

## Major

- Multiple calls instead of one call. This is a big architectural change.
- it's going to be n+1 calls, where n is the number of facilities. This could very well be a place for optimizing or progressive painting of data
- The services and the facilities will have to be matched up by comparing IDs
- This could change the UX (not necessarily a bad thing, but calling it out) 

## Minor

- `active_status` does not appear to be used, So the removal won't affect the appear

## Next steps

- Create a new Facility Component that loads calls the service API when rendered
- Monitor for performance issues
- Work with a designer to figure out progress painting UX
- Explore the possibility of using the vets-api as a caching layer/data aggregation layer
