### ISSUE TITLE
Implement Facility operating status design iteration on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35479]
## Issue Description
Facility operating alerts are currently in production with a range of implementations on various pages documented in the table below. After an audit to find where and how these implementations differed and a design intent to get approval on design iteration, we are ready to implement Nick's design recommendations to provide a consistent experience within and across products

| Page | Current behavior | Expected behavior | Difference |
| ----- | ---- | ----- | ----- |
| Facility Locator search results | ![image](https://user-images.githubusercontent.com/55411834/149845710-6fd1f07e-6d4f-4d29-8114-9adb15b6c219.png) |  ![image](https://user-images.githubusercontent.com/55411834/149845763-5a2db66b-e677-4d93-8657-a87b76edb155.png) | Limited status should use yellow color and alert icon, add screenreader announcement |
|  Facility Locator details page |  ![image](https://user-images.githubusercontent.com/55411834/149845806-10c57565-3cc4-41fd-a194-b1bf478179da.png) |  ![image](https://user-images.githubusercontent.com/55411834/149845889-a7650a7a-76c5-44b6-ba61-5402588a6381.png) | Limited status should use use full-width yellow color and alert icon, add screenreader announcement |

## Design system references
- [Background Only With Icon](https://design.va.gov/storybook/iframe.html?id=components-va-alert--background-only-with-icon&viewMode=docs#background-only-with-icon)

---
## Tasks
Implement design found in [UX Pin], which includes
(https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/specification/no-panels?mode=i)

**Search results**
- [x] When facility operating status = "Limited services and hours", use the yellow, full-background-with-icon alert
- [x] Facility locator alerts appear underneath location name link
- [x] For accessibility: screen readers should treat static alerts as readable text: "Limited services and hours" (in the current experience, screen readers are ignoring facility locator alerts)
- [x] Alert should get focus in tab order, following the facility name
- [x] Static alerts do not have rounded borders
- [x] Maintain existing style for "Normal", "Facility Notice" and "Closed" statuses 

**Facility Detail page**
- [ ] When facility operating status = "Limited services and hours", use full-width yellow alert style
- [ ] For accessibility: screen readers should treat static alerts as readable text: "Limited services and hours" 
- [ ] Static alerts do not have rounded borders
- [ ] Maintain existing style for "Normal", "Facility Notice" and "Closed" statuses 

## Acceptance Criteria
- [ ] Regardless of status, facility operating status should receive focus and be announced to screen readers as readable text
- [ ] When facility operating status = "Limited services and hours"
      - the yellow, full-background-with-icon alert displays beneath the location name in Facility Locator search results
      - the full-width yellow alert style is displayed on Facility Locator detail pages

**Comment by mmiddaugh** [comment]
@mdewey the following locations have operating status = "Limited services and hours", at least as of this morning

- Columbus Vet Center 
  - Search location = Columbus, OH and facility type = Vet Center 
  - Detail page = /find-locations/facility/vc_0221V
- Atlanta Vet Center 
  - Search location = Atlanta, GA and facility type = Vet Center 
  - Detail page = /find-locations/facility/vc_0304V

The following locations can be used to validate that behavior is maintained for other alert statuses

**Normal status - no alert is expected to display**
- Marietta Vet Center
  - Search location = Marietta, GA and facility type = Vet Center 
  - Detail page = /find-locations/facility/vc_0342V

**Closed status**
- Atlanta VA Regional Benefit Office
  - Search location = Atlanta, GA and facility type = VA benefits
  - Detail page = /find-locations/facility/vba_316

**Comment by mmiddaugh** [comment]
One note: the icon for "closed" is now red based on an update to the design system. 
![image](https://user-images.githubusercontent.com/55411834/162013346-bfe3a582-d24b-4cbe-bc17-2fdb6174834e.png)
