### ISSUE TITLE
Remove progress-bar sass module

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#35482]
## Issue Description

The `<ProgressBar>` and `<SegmentedProgressBar>` React components have been replaced with web components and are [removed from the component library](https://github.com/department-of-veterans-affairs/component-library/pull/263). They relied on [styles from formation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/709690c0678775139fd091fb982ced92bc603ec0/packages/formation/sass/modules/_m-progress-bar.scss#L1) and application code is still importing these now-unused styles.

The goal with this ticket is to remove this import from the 32 application SASS files:

```scss
@import "~@department-of-veterans-affairs/formation/sass/modules/m-progress-bar";
```

Once this file is no longer imported we can delete it from `formation`.

---
## Tasks
- [ ] Remove import in [`my-education-benefits`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/my-education-benefits/sass/my-education-benefits.scss#L4)
- [ ] Remove import in [`pre-need`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/pre-need/sass/pre-need.scss#L4)
- [ ] Remove import in [`edu-benefits`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/edu-benefits/sass/edu-benefits.scss#L6)
- [ ] Remove import in [`veteran-representative`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/veteran-representative/sass/veteran-representative.scss#L4)
- [ ] Remove import in [`pensions`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/pensions/sass/pensions.scss#L6)
- [ ] Remove import in [`vre`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/vre/sass/vre.scss#L4)
- [ ] Remove import in [`hca`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/hca/sass/hca.scss#L6)
- [ ] Remove import in [`financial-status-report`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/financial-status-report/sass/financial-status-report.scss#L4)
- [ ] Remove import in [`burials`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/burials/sass/burials.scss#L4)
- [ ] Remove import in [`letters`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/letters/sass/letters.scss#L3)
- [ ] Remove import in [`claims-status`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/claims-status/sass/claims-status.scss#L5)
- [ ] Remove import in [`coronavirus-vaccination-expansion`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/coronavirus-vaccination-expansion/sass/covid-vaccine.scss#L4)
- [ ] Remove import in [`ask-a-question`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/ask-a-question/styles/ask-a-question.scss#L4)
- [ ] Remove import in [`caregivers`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/caregivers/sass/caregivers.scss#L4)
- [ ] Remove import in [`disability-benefits/686c-674`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/disability-benefits/686c-674/sass/new-686.scss#L4)
- [ ] Remove import in [`disability-benefits/996`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/disability-benefits/996/sass/0996-higher-level-review.scss#L4)
- [ ] Remove import in [`disability-benefits/all-claims`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/disability-benefits/all-claims/sass/disability-benefits.scss#L6)
- [ ] Remove import in [`disability-benefits/2346`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/disability-benefits/2346/sass/form-2346.scss#L4)
- [ ] Remove import in [`appeals`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/appeals/10182/sass/10182-nod.scss#L4)
- [ ] Remove import in [`edu-benefits/1990s`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/edu-benefits/1990s/sass/1990s.scss#L4)
- [ ] Remove import in [`edu-benefits/10203`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/edu-benefits/10203/sass/10203_stem.scss#L6)
- [ ] Remove import in [`personalization`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/personalization/search-representative/sass/search-representative.scss#L4)
- [ ] Remove import in [`health-care-questionnaire/.../review`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/health-care-questionnaire/questionnaire/sass/review.scss#L4)
- [ ] Remove import in [`health-care-questionnaire/.../questionnaire`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/health-care-questionnaire/questionnaire/sass/questionnaire.scss#L4)
- [ ] Remove import in [`health-care-questionnaire/.../footer`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/health-care-questionnaire/questionnaire/sass/footer.scss#L4)
- [ ] Remove import in [`health-care-questionnaire/.../confirm`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/health-care-questionnaire/questionnaire/sass/confirm.scss#L4)
- [ ] Remove import in [`sah`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/sah/sahg/sass/sahg.scss#L4)
- [ ] Remove import in [`coronavirus-research`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/coronavirus-research/sign-up/sass/covid-research-volunteer.scss#L4)
- [ ] Remove import in [`vre/28-8832`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/vre/28-8832/sass/28-8832-planning-and-career-guidance.scss#L4)
- [ ] Remove import in [`vre/28-1900`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/vre/28-1900/sass/28-1900-chapter-31.scss#L4)
- [ ] Remove import in [`lgy`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/lgy/coe/form/sass/coe.scss#L6)
- [ ] Remove import in [`coronavirus-research/update`](https://github.com/department-of-veterans-affairs/vets-website/blob/c5e4f22bde62316194cbba0895c6db81e4f1b9a0/src/applications/coronavirus-research/update/sass/covid-research-volunteer.scss#L4)
- [ ] Remove SASS module in `formation` package
- [ ] Publish new `formation` version

## Acceptance Criteria
- [ ] `progress-bar` SASS module is no longer imported
- [ ] `progress-bar` SASS module is removed from `formation` npm package
