### ISSUE TITLE
Implement Facility operating status design iteration on Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35481]
## Issue Description
Facility operating alerts are currently in production with a range of implementations on various pages documented in the table below. After an audit to find where and how these implementations differed and a design intent to get approval on design iteration, we are ready to implement Nick's design recommendations to provide a consistent experience within and across products. 

## Example pages
- [Reno Vet Center main page](https://www.va.gov/reno-vet-center/)
- [Reno Vet Center locations page](https://www.va.gov/reno-vet-center/locations/)

| Page | Current behavior | Expected behavior | Difference |
| ----- | ---- | ----- | ----- |
| Main | ![image](https://user-images.githubusercontent.com/55411834/149848276-b99340e2-a63c-41d0-944b-d8bacded6feb.png) |  ![image](https://user-images.githubusercontent.com/55411834/149848915-ed39752f-b5d5-43cc-99a1-4353c6295881.png) | Limited status should use yellow color and alert icon |
| Locations  |  ![image](https://user-images.githubusercontent.com/55411834/149848352-89e01cdb-3128-4684-ab31-966e20288166.png) |  ![image](https://user-images.githubusercontent.com/55411834/149848915-ed39752f-b5d5-43cc-99a1-4353c6295881.png) | Limited status should use yellow color and alert icon |

## Design system references
- [Background Only With Icon](https://design.va.gov/storybook/iframe.html?id=components-va-alert--background-only-with-icon&viewMode=docs#background-only-with-icon)
- [Warning alert](https://design.va.gov/storybook/iframe.html?id=components-va-alert--warning&viewMode=docs#warning)

## Tasks
For Vet Center Main and Location pages
- [ ] Maintain existing expandable alert style found in [UX Pin](https://preview.uxpin.com/ad1daf77e161cbde903ca3cbe0b65177a7e7bdf2#/pages/144397776/specification/no-panels?mode=i), which includes
- [ ] When facility operating status = "Limited services and hours", use yellow full-background-with-icon expandable alert with 5px border radius

## Acceptance Criteria
- [ ] Regardless of status, facility operating status should be announced to screen readers 
- [ ] When facility operating status = "Limited services and hours", the alert uses the yellow full-background-with-icon expandable alert with 5px border radius
- [ ] Ensure alerts are announced to screen readers (we believe this is already happening)

**Comment by mmiddaugh** [comment]
Verified on Facility Locator and [Laredo Vet Center](https://www.va.gov/laredo-vet-center/) that the inconsistency is still present: 
![image](https://user-images.githubusercontent.com/55411834/184216352-d7596610-deb4-4cb0-9e33-dea38c2dddb7.png)
![image](https://user-images.githubusercontent.com/55411834/184216402-a8d7cea2-7ba6-4fa4-930c-b9d10572deac.png)
