### ISSUE TITLE
Updates to pages about choosing between urgent and emergency care

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35495]
## Issue Description
We added more information about mental health emergencies and made minor changes to several pages about choosing between urgent and emergency care. We need to review and publish these updates.

**Pages updated:**

**Urgent vs. emergency care R&S article with updates:** http://preview-prod.vfs.va.gov/preview?nodeId=37196
**About VA health benefits page with minor updates:** http://preview-prod.vfs.va.gov/preview?nodeId=29
**Where you’ll go for care page with minor updates:** http://preview-prod.vfs.va.gov/preview?nodeId=7

## Tasks
- [ ] Update pages (Danielle)
- [ ] Copy edit pages (Randi)
- [ ] Publish (Randi)

## Acceptance Criteria
- [ ] Changes are live

**Comment by RLHecht** [comment]
Waiting on approval to publish

**Comment by SgardnerPMP** [comment]
@SgardnerPMP to create review and publish ticket for DT and move this to Validate.
