### ISSUE TITLE
Create and publish COVID-19 testing R&S page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35492]
## Issue Description
In order to provide Veterans with the most up-to-date information about COVID tests, we need to create an R&S article providing them with information about where to get tests, how to get test results and next steps.

## Tasks
- [x] Create article (Danielle)
- [x] Copy edit (Randi)
- [x] Get approval (Danielle)
- [x] Review and publish (Randi)

## Acceptance Criteria
- [x] New COVID testing article is live on the site

**Comment by RLHecht** [comment]
Page was approved with no changes and Danielle published. Moving to validate.

**Comment by RLHecht** [comment]
Page is live.
