### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 1/31

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35491]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [ ] New ticket created
