### ISSUE TITLE
Spike: How to Integrate Service Principals

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#35504]
Services need to be able to interact with other services in a ZTA environment. This spike will test if this is possible in our current configuration.

**Tasks**
- [x] Create two microservices 
  - Microservice A needs to be authenticated through keycloak
  - Microservice B needs to be able to authenticate incoming requests
- [x] Appropriate Roles & Permissions
  - A can have them assigned
  - B has a concept of what they are
- [x] Use keycloak as IdP for service principals
- [x] Make sure it runs through keycloak locally
- [x] Set up Microservice C to test if it can interact with Microservice B with different roles and permissions

**Output of Spike**
Documentation on how to create and authenticate / authorize service principles using our solution.

**Comment by kjduensing** [comment]
Did not need to actually set up microservices to prove this out, but we can do that if it makes sense.
