### ISSUE TITLE
Create Operational Guidance - Role-Based Orientations

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#35519]
## Issue Description
Create detailed operational guidance for the role-based orientations for Platform Orientation. See [ticket #29920](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29920) for additional information.

---
## Tasks
- [x] Create operational/internal Platform guidance for Platform Products & Services/ Platform Orientation space on Confluence under the [Orientation Sessions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions). This guidance is available for all Platform teams.
- [x] Peer Review changes with a Governance teammate
- [x] Share changes with Session Owners. Ask for their review and confirmation of roles/responsibilities 

## Acceptance Criteria
- [ ] Platform teams involved in orientation are aware of their roles and responsibilities
   - [x] Release Tools (FE)
   - [x] Console Services (BE)
   - [x] Analytics & Insights (analytics)
   - [x] QA Standards (QA and accessibility)
   - [x] Platform Design Lead (design/research)
   - [x] Infrastructure (ATO)
- [x] All of Platform has knowledge of the Platform Orientation sessions and session-specific details

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@chaseakirby Could you please review the new [Platform Orientation/ Orientation Sessions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) I drafted and let me know if you have any comments or concerns? Thanks!

**Comment by chaseakirby** [comment]
@shiragoodman I have reviewed the page. I did make one comment related to the Front End Tools Team/Release Tools Team where their google doc links back to their Front End Tools Team Confluence space.
Otherwise all the information looks good and well organized. All links worked as expected, I checked that the zoom links were unique but didn't click them as I didn't want to join a meeting by accident.
