### ISSUE TITLE
Allow app to link to GitHub repo

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#35512]
## Purpose
Allow apps to access workflows in github actions, commit history, PR's, issues.

**Comment by rileyanderson** [comment]
- [ ] Add octokit.rb gem 
- [ ] Generate access keys and tokens on `vsp-bot` user
- [ ] Get all repositories from organization
- [ ] Allow user to pick a repository 
- [ ] Get commit history for given repository
- [ ] List out actions/workflows on the repository
- [ ] Start a workflow/action
- [ ] Get and display logs from workflows
- [ ] Workflow status
