### ISSUE TITLE
Create Operational Guidance for Platform Orientation - New VFS Team

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#35510]
## Issue Description
Create detailed operational guidance for [ticket #33198](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/33198).

---
## Tasks
- [x] Create operational/internal Platform guidance for Platform Products & Services/ Platform Orientation space on Confluence on the [New VFS Teams](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams). This guidance is available for all Platform teams.
- [x] Peer Review changes with a Governance teammate

## Acceptance Criteria
- [x] Platform is informed of intake request and are able to take appropriate action.
- [x] Platform is able to follow guidance for responding to new Platform Orientation tickets
- [x] Governance team is able to follow guidance for team specific action items

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@jimuhh @Saraharaba8 the new page looks good to me. Please review the AC and tasks above. If you feel like they've been met, please check them off and close the ticket. FYI @chaseakirby
