### ISSUE TITLE
Expand/redesign the Platform Orientation page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35523]
## User Stories
As a new VFS team member, I need to be able to easily and intuitively access Platform Orientation information on Platform Website so that I can complete the orientation process and be ready to support my team.

As an existing VFS team member, I need to be able to easily sign up for Platform Orientation sessions without opening a Platform Orientation template ticket so that I can get a refresher on Platform processes and expectations if/when I need it.

As an OCTO platform lead, I want to make sure that the Platform Orientation process is clearly defined and outlined for VFS teams so that I can confidently direct my OCTO peers and VFS product owners to the process on Platform Website.

As a Governance team member, I want to ensure that the Platform Orientation process outlined on Platform Website is clear and easy to follow/understand so that VFS teams do not have trouble completing the steps.

## Issue Description
The Platform Orientation page on Platform Website is very brief and does not provide VFS teams and/or OCTO-DE of an overview of expectations and process. The purpose of this ticket is to update the Platform Orientation page to give clear guidance to VFS/OCTO-DE of the Platform Orientation process, actions necessary for them to take, and direct links to the Calendly orientation sessions.

More than 1 Platform Orientation page will be necessary, so this ticket will focus on redesigning the existing content and incorporating the new content.

What should be included in the Platform Orientation page(s):

- Overview of Platform Orientation
   - include user flow, high level description of what it is and why it's necessary, etc.
   - give clear guidance on the process
- Orientation materials
   - this content is already live on Platform Website. No need to edit, just potentially relocate
- Calendly orientation sessions 
   - include Calendly sign-up links for all recurring Orientation sessions (aka not ATO). 
   - possibly include brief overview of each session. See [this page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) for details. 
- Guidance to new VFS team members
   -  this content is already live on Platform Website. No need to edit, just potentially relocate
- Guidance to new VFS teams
   - this content is already live on Platform Website. No need to edit, just potentially relocate

## Artifacts to be updated

- [Platform Website: Platform Orientation page](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
-  Mural board [mind map](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1645125241724/048dab5e846b790949b590bf4b46392aebe60543?sender=uba3f5a2a4086a2599c206260)
- [Document draft ](https://vfs.atlassian.net/l/c/x11uNuk9)of new platform orientation page

Additional pages may need to be created, dependent on proposed design/solution

## Tasks
- [x] Document a proposed design/solution of the pages (use MURAL) [LINK HERE](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1645125241724/048dab5e846b790949b590bf4b46392aebe60543?sender=uba3f5a2a4086a2599c206260)
- [x] Review proposed design/solution with Shira/Chase
- [x] Create documentation drafts of existing [Platform Website: Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) page to be edited
- [x] Create documentation draft of new pages
- [x] When complete, comment on this ticket for Peer Review

## Acceptance Criteria
- [x] [Platform Orientation on Platform Website](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation)
- [x] New Pages on Platform Website has been [created per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#6.-Creating-new-Platform-Website-documentation)
- [x] User stories have been fulfilled
- [x] Updates have been peer reviewed and approved by Governance team member(s)

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@shiragoodman Here are our 3 pages for review: [Orientation Outline](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2104197133/Orientation+outline)
[New VFS teams and team members](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2117009628/Chase+-+New+VFS+Team+and+Team+Members)
[Orientation sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2117272123/Chase+-+Calendly+Orientation+Sessions+Platform+Website)
The outline is intended to be the main page, and the other 2 are child pages to the main page.

**Comment by chaseakirby** [comment]
Pages have been created and updated on Platform Website.
All issues redirect to within Platform Website besides [Front-end Orientation Materials](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html#CalendlyOrientationSessions-Front-endOrientation)
[Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
 - [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html)
 - [Calendly Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html)
