### ISSUE TITLE
Add Design System/Forms Library orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35522]
## Issue Description
The Design System team (DST) and Forms Library team (FLT) believe it would be valuable for new front-end developers/engineers to have an orientation session aimed at introduction to the Design System and Forms Library. DST and FLT will be responsible for creating the slide deck, storing it in the right folder location, and hosting the meeting once a month, however Governance team has tasks for updating all VFS-facing guidance.

---
## Tasks
- [X] Contact DST and FLT to determine what day and time each month they can host the orientation session
   **2nd Friday of the month at 3:00pm ET**
- [x] Create a Calendly event for the new orientation session (Shira)
- [x] Obtain zoom information from DST and/or FLT to add to the events 
- [x] Add Zoom info to the Calendly event
- [x] Ask DST and/or FLT (whoever is the host) to sign up for the event for the next 1 year (12 events in total)
- [x] Update the Platform Orientation template to include the new Calendly sign-up link
   - Link should be referenced in the Front-end developers section
- [x] [Orientation Sessions page on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) is updated with DST/FLT session
- [x] [Calendly Orientation Sessions page on Platform Website](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html) is updated with DST/FLT session
- [x] The meeting hosts have read, understand and sign off on the [Roles and Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Roles-and-Responsibilities) of hosting Platform orientation sessions
   - [x] @k80bowman 
   - [x] @micahchiang 

## Acceptance Criteria
- [x] Design System/ Forms Library orientation session has been added to the Platform Orientation materials
- [x] Front end developers are asked to attend the Design System/ Forms Library orientation session 
- [x] The Design System/ Forms Library orientation session is held once a month 
- [x] The hosts of the DST/FLT orientation session understand their roles and responsibilities
- [x] The new Design System/ Forms Library orientation session has been communicated to VFS teams per the Platform communication playbook.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
FYI @k80bowman

**Comment by k80bowman** [comment]
@shiragoodman Micah (@micahchiang) and I have put together our slides for the orientation. What do we need to do next?

**Comment by shiragoodman** [comment]
@micahchiang @k80bowman any update? Please let me know if you'd like to schedule a quick meeting (15 min) to discuss.

**Comment by micahchiang** [comment]
Hey @shiragoodman - @k80bowman and I looked at Calendly and think the 2nd Friday of every month at 3pm ET is good for both of us. 

Neither of us has a professional zoom account so we wouldn't be able to have meetings longer than 40 minutes. What would you recommend? We could host on google meet if that works. 

This meeting should be for frontend engineers, and optional for everyone else.

**Comment by k80bowman** [comment]
@shiragoodman I just uploaded the Design System orientation slides to the Google drive folder, so they should both be there now.

**Comment by shiragoodman** [comment]
Thanks @micahchiang and @k80bowman .

@k80bowman the Adhoc team members on my team have professional Zoom accounts. Do you think this is something you could look into? 

If Zoom is not an option, we can use Google meet. However it would need to be the same link to join for each month. Can Google meet do that?

2nd Friday of the month at 3:00pm works well!

I will work with my team to get this ticket completed and will follow up when it's ready for your review.

**Comment by caw310** [comment]
@k80bowman , you can use my zoom account. I can hop on initially then make you host.

**Comment by k80bowman** [comment]
Thank you @caw310! I'm going ahead and requesting an account, so let's see if I can get one so you don't have to worry about hopping on.

**Comment by k80bowman** [comment]
@shiragoodman I was able to get a Zoom account. I will DM you the meeting details.

**Comment by shiragoodman** [comment]
@k80bowman @micahchiang I will be announcing the new orientation session at today's Team of Teams meeting. First session is scheduled to take place May 13th - I will keep you updated!

**Comment by micahchiang** [comment]
Sounds good, thanks @shiragoodman! I don't see anything on my calendar for the 13th yet, just thought I'd let you know.

**Comment by k80bowman** [comment]
Fantastic, thank you @shiragoodman!

**Comment by shiragoodman** [comment]
@micahchiang @k80bowman the [Design System/Forms Library Orientation for VA.gov Calendly event](https://calendly.com/collaboration-cycle/design-system-forms-library-orientation) has been created with Katy's Zoom information. Please review the description and let me know if you'd like to make any changes. Then, as the hosts of this meeting, please sign up for every Calendly event from May through December (events for 2023 haven't been refined yet). Please let me know if you have any questions.

**Comment by k80bowman** [comment]
Thank you @shiragoodman! I'll get signed up. I am unfortunately out on the 13th, but I will get a teammate to sign up in my place (my zoom meeting will still work, we checked it)

**Comment by shiragoodman** [comment]
thanks for letting me know @k80bowman . That is item # 4 on the [Roles and Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Roles-and-Responsibilities) list on the Orientation Sessions page. I will make a note to update it to reflect if you (the individual/host) will be out on the day of the session. I see no problem with having an alternate host, as long as there's no conflicts with Zoom. Thanks for letting me know!

PS - reviewing the Roles and Responsibilities is one of the tasks/AC on this ticket. You and @micahchiang should review the section and select your name above once complete. thanks!

**Comment by shiragoodman** [comment]
@micahchiang @k80bowman everything has been updated in Confluence and Github, and the Platform Website changes are scheduled to publish tomorrow at 12 noon. 

I am OOO tomorrow and Friday, but when I return, I plan on announcing the changes on the #vfs-all-teams channel. When I do that, did you want me to make a call out to all FE devs (whether they're new or not) and invite them to the first session? Or would you prefer if only new FE folks joined via the Platform Orientation process? Please let me know!

**Comment by k80bowman** [comment]
@shiragoodman anyone who wants to attend would be welcome. Thank you!

**Comment by shiragoodman** [comment]
@micahchiang Gentle nudge to agree to the roles and responsibilities above. ty!

**Comment by micahchiang** [comment]
@shiragoodman - Done! Sorry for the delay.

**Comment by shiragoodman** [comment]
Thank you @k80bowman and @micahchiang for your support in getting this ticket completed. I will be announcing in ToT today. Closing out!
