### ISSUE TITLE
Import React bindings directly from component-library

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#35528]
## Issue Description

Currently we have a [babel alias](https://github.com/department-of-veterans-affairs/vets-website/blob/b504408c08178e024df79ace101f7e0be2ab169d/.babelrc#L63) that's allowing teams to import from `web-components/react-bindings` which was the typical import before we began using the version of `component-library` which had web components integrated (https://github.com/department-of-veterans-affairs/vets-website/pull/19184). As part of that process, we added some aliases [in order to avoid making changes to app code](https://github.com/department-of-veterans-affairs/vets-website/pull/19184#discussion_r736019056).

Now that we are beginning to count React bindings in our component usage report, it will make things simpler if all imports are using the same pattern to import the bindings from the `component-library` directly:

```js
import { VaAlert } from '@department-of-veterans-affairs/component-library/dist/react-bindings';
```

While we're at it, we may also want to put some automation in place to direct people to import from `component-library` in the future rather than the `web-components` package. Even though it isn't deprecated, we could add some configuration to the `deprecate/import` rule to achieve that effect:

![image](https://user-images.githubusercontent.com/2008881/150005588-7b5f4bd2-c8c9-4485-87cb-c02ae58a073a.png)

![image](https://user-images.githubusercontent.com/2008881/150005532-7d6da06e-1cd0-4b5c-93c5-4535f49895d3.png)

---
## Tasks
- [x] (optional) Add ESLint config to warn when importing from `@department-of-veterans-affairs/web-components/react-bindings`

- [x] Update all binding imports in vets-website

## Acceptance Criteria
- [x] All React bindings are imported from `'@department-of-veterans-affairs/component-library/dist/react-bindings'`
- [x] Babel alias is removed

**Comment by andresriveratoro** [comment]
Create a PR to revert changes from https://github.com/department-of-veterans-affairs/vets-website/pull/21137 after it and https://github.com/department-of-veterans-affairs/vets-website/pull/21127 have been merged
