### ISSUE TITLE
Remove Ryan Thurlwell from Collaboration Cycle guidance/documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35539]
## Issue Description
January 31 will be Ryan Thurlwell's last day with OCTO-DE. He will need to be removed from all Collaboration Cycle guidance and documentation.

---
## Tasks
- [x] Review Collaboration Cycle guidance in Platform Website, Confluence and github issue template and identify where Ryan is mentioned by name. Create a list of places that will need to be updated.
  - [x] Group email for design intent and midpoint review
  - [x] Design intent internal documentation
- [x] Review script for OCTO Design Lead/Ryan role. Rewrite if needed
- [x] Review objectives for OCTO Design Lead/Ryan role. Rewrite if needed
- [x] Remove question asking if Ryan has reviewed product on Design Intent

## Acceptance Criteria
- [x] VSP PMs will not expect Ryan to review their products
- [x] VSP PMs are aware other OCTODE people may be on the Zoom
- [x] Ryan's name is no longer on collab cycle documentation
- [x] Ryan does not receive invites to the reviews
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by allison0034** [comment]
@shiragoodman I requested a review for the design intent GH ticket. I did not remove the question about OCTO reviewing it. I think that could be valuable if Kevin or Martha or some other OCTO person is working with them. I reworked the question to remove the design lead part and asked them to name the OCTO person

**Comment by allison0034** [comment]
@shiragoodman this ticket is ready for your review. The changes are on the...
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Platform Website - Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
[Design Intent GH Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+collab-cycle-review%2C+design-intent&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)
