### ISSUE TITLE
White Space- Find a Form

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#35537]
## Issue Description
_When conducting search for a form and results appear there is a large white block after the initial details. 

As the Veteran, after I conduct a search the white block makes me believe that is the end of the results. I have no idea or indication that I need to scroll further to see the rest of the results. _

<img width="1370" alt="Screen Shot 2022-01-19 at 10 21 49 AM" src="https://user-images.githubusercontent.com/95870427/150160679-a0ab5b92-85e1-482c-ba8d-fc8a761da2ad.png">

---
## Tasks
- [x] _The white block should be removed_

## Acceptance Criteria
- [x] _When scrolling after search the user should see the results and then frequently used VA Forms without having to scroll further. _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nicole-leonard** [comment]
@srsuddath Did you ever have a chance to look into this? If not cool. Just don't want to send Tyler on a goose chase.

**Comment by nicole-leonard** [comment]
Complete
