### ISSUE TITLE
Find a Form returns info when noting is entered

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#35540]
## Issue Description
_When in Find a form at https://www.va.gov/find-forms/ and no search criteria is entered and search is selected then all forms are returned. _

<img width="1370" alt="Screen Shot 2022-01-19 at 10 39 57 AM" src="https://user-images.githubusercontent.com/95870427/150164443-fb092a36-2e46-4097-a880-1ddfe8691660.png">

---
## Tasks
- [ ] _Implement rules to prevent search less than 2 characters. _ [ ] _ Implement error message @mgleo to research 

## Acceptance Criteria
- [ ] _Veterans will need to put in at least 2 characters for information to be returned on a search. _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nicole-leonard** [comment]
https://www.cnn.com/2022/02/08/investing/cryptocurrency-laundering/index.html

**Comment by nicole-leonard** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1642528897477100

**Comment by mgleo** [comment]
Find a form should follow the **Errors on text inputs** pattern: https://design.va.gov/patterns/form-feedback

This also need to be updated on R&S, Josh created a ticket here: #36671

**Comment by mgleo** [comment]
Hi @joshkimux,
@TSimmz is implementing [Error on text inputs](https://design.va.gov/patterns/form-feedback) on [Find a form](https://www.va.gov/find-forms/) when nothing is entered in the search input field. 

When a user:
1. Focuses on the the search input field
2. Does not click on the search button 
3. Focuses on something else on the page

Can you confirm that this is the correct behavior for the error state:
- The error would appear if the user has focused on search input field even if the user hasn't clicked the search button
- The error would stay on the screen even after focus has shifted to somewhere else on the page

**Comment by joshkimux** [comment]
One minor fixes here for that first bullet point!
- The error would appear only _after_ the user has clicked the search button. It would not appear unless triggered by a button.

Once the error appears (after the user has pressed the search button), it will stay there until something is input into the field.

**Comment by mgleo** [comment]
Perfect, thanks for clarifying!

**Comment by TSimmz** [comment]
Thanks for looking into this @mgleo! 😄

**Comment by nicole-leonard** [comment]
Complete

**Comment by mgleo** [comment]
@joshkimux Error on the search input is up on FaF. Does it look ok to you? https://www.va.gov/find-forms/

**Comment by joshkimux** [comment]
This is awesome! Thanks for the click turn around y'all 🙏 
<img width="889" alt="Screen Shot 2022-02-23 at 5 05 05 PM" src="https://user-images.githubusercontent.com/14154792/155416978-f2769f88-4fe6-4916-8768-e6399cf60b03.png">
