### ISSUE TITLE
[UX] Research - "Remove" button in editing demographics

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#35543]
## Description

We need to determine if there is a use case for including a "remove" button on each editable field in the patient demographics section.  

[Findings]

"Remove" button functionality would require the following enablers:
- Having a tertiary style button (Prerequisite)
- UI interaction pattern alignment with VA profile on CTA UI interaction including post-state of CTA action such as confirmation modal, blank state placeholder text label, and the "Remove" button state.

[Reference] 

[1] Remove mailing address: 
- [Slack discussion](https://dsva.slack.com/archives/C022AC2STBM/p1646079228079819)
- [Screenshot: 2 remove mailing address.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/1208706e-075b-4fee-9150-8f63e3d29b26)

[2] Complete VA Profile UI:
- [Video capture](https://images.zenhubusercontent.com/133843125/8a59f1df-3cf5-4bf6-925b-29c331dd2281/va_gov_profile_s_current_behavior_for__mailing_address__required.mp4)
(Remove functionality will be worked on via another [ticket #35543](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/35543).)

# Tasks
- [ ] Create new content and designs in Sketch
- [ ] Review with content

# Acceptance Criteria
- [ ] Review final designs with product and UX
- [ ] Create FE ticket
