### ISSUE TITLE
Audit for links to Get help filing your claim or appeal and Get help with your decision review request pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35545]
## Issue Description
As part of the work for creating a new tool page for VSO/accreditor rep search, we need to do an audit of our pages to find where we link to the following pages:

https://www.va.gov/disability/get-help-filing-claim/
https://www.va.gov/decision-reviews/get-help-with-review-request/

Once we have our new tool page, these pages will be retired and redirected there. So we need to create a list of all the pages we will eventually need to update.  

## Tasks
- [x] Reach out to Public Websites to do a search
- [x] Audit pages for links to Get help filing your claim or appeal
- [x] Audit pages for links to Get help with your decision review request

## Acceptance Criteria
- [x] Audit of 2 pages complete

**Comment by RLHecht** [comment]
@brianalloyd would your team be able to help us with this? We need to do a search for all links on our site that currently go go these 2 pages:

https://www.va.gov/disability/get-help-filing-claim/
https://www.va.gov/decision-reviews/get-help-with-review-request/

These pages will eventually be redirected with the launch of the accredited rep tool so we will want to update any links that are pointing to them. Thanks!
