### ISSUE TITLE
Outreach - meet with VFS Teams not currently on Std KPD Dashboards

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#35555]
## Issue Description
Currently on 62% of VFS teams are on the Standardize KPI Dashboards. Our objective for Q1-2022 is to get 100% of VFS on the dashboards.  In an effort to do so we will reach out to each team individually to find out why they have not yet requested a dashboard, answer any questions they may have about the benefit of the dashboards and offer support/guidance in getting them set up on the applicable dashboards.

---
## Tasks
Meet with each of the following teams:
- [x] eBenefits
- [x] Healthcare Experience
- [x] Sitewide Content
- [x] VAMC Web Modernization
- [x] Virtual Agent/Chatbot

## Acceptance Criteria
- [x] We have met with each team
- [ ] We have completed the dashboard for their product.

**Comment by michelle-dooley** [comment]
Virtual Agent/Chatbot:  request submitted and in que
eBenefits:  Reached out on 2/7 - waiting for ticket submission - will follow up
Healthcare Experience:  Reached out on 2/1 - waiting for ticket submission - will follow up

**Comment by michelle-dooley** [comment]
Virtual Agent/Chatbot:  dashboard complete, waiting for product to launch so we can QA data.
eBenefits:  waiting on submission, f/u sent on 2/15
Healthcare Experience:  waiting on submission, f/u sent on 2/10
Sitewide Content:  reached out on 2/10, waiting on ticket submission
VAMC:  reached out on 2/10, waiting on ticket submission

**Comment by michelle-dooley** [comment]
4 remaining VFS teams to onboard.  Will continue that work and adding of more products to existing VFS dashboards as part of the KPI Dashboards:  MVP Enhancements moving into Q2.
