### ISSUE TITLE
QAST CONTENT: Understand QA team's content set

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#35561]
# Outcome
Have some sub-tasks mapped out to current documentation.  (Core VFS task: Testing and QAing products)

# Tasks

- [x] Change terminology in yellow boxes to action phrases
- [x] Reconcile yellow boxes and Col C w/ QAST
- [x] Pick three yellow boxes of whatever list comes out of Step (1)
- [ ] Transform the underlying lavender docs. 
  - Liani thinks "transform" = adding context, changing titles to be more action prhases, making the individual steps less verbose, writing assuming baseline-but-not-rudimentary domain knowledge

# Acceptance criteria
- A doc has been transformed following the how-to template.

# Reference info
- [Transform QAST content - Split up tasks](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1642697222660/e2e61518d667d557343cadb589059f56c5fec9b4?sender=ua8f37bacb65e882c26c56415)

**Comment by lianilychee** [comment]
flesh out during 1/20 Thurs SU

**Comment by lianilychee** [comment]
1/20 Thurs:
- don't rly understand the assignment

**Comment by lianilychee** [comment]
Mon 1/24:
- Samara and Jill sync'd this morning
- Way forward:
  - Going to review MURAL board, make sure we understand the documents for "Performing QA testing" content since that is what Peter suggested we start with
  - Consider utilizing the How-to template, try plugging in QAST's content into the How-to template and see how it works
  - For Thurs, we're thinking of presenting something to Peter and Joe
    - Show SMEs a converted doc
    - Ask SMEs for info for intros

- Tomorrow
  - Of the 15 docs under "Performing QA testing," identified which docs are good candidates for fitting into the how-to template


- Question: Why did we select "Performing QA testing?"
  - Based on SME response, "Performing QA testing" is a core subtask within Testing and QA'ing products.  This allows us to create supplemental docs based on core subtask.

**Comment by lianilychee** [comment]
Tues 1/25:
- today:
  - **review QAST's documentation set to identify what is a good candidate for fitting into "how-to" and "overview" template**
  - **message SMEs to verify what goes into the "Performing QA tests" category**
    - J+S clean up what to send, draft a message
    - L review message
    - J+S send to #platform-qast-documents
    - (this task involves getting familiar w Google Sheets)

- three categories the SMEs have given us:
  - (1) Performing QA testing
  - (2) Performing end-to-end testing
  - (3) Creating and executing accessibility tests

- terminology

**Comment by lianilychee** [comment]
1/26 Weds:
- yesterday 
  - tweaked spreadsheet:
    - went thru ~2/3 of the doc set and identified the docs that were candidates for the "how-to" and "overview" templates
- today
  - going thru the remainder ~1/3 of the doc set to ID docs that fit within the templates
  - send out the ask to SMEs

**Comment by lianilychee** [comment]
Thurs 1/27:
- today:
  - Jill
    - deep diving into "Performing QA testing" docs
    - finish determining what docs fit into "how-to" and "overview" templates
    - initial thoughts re: divvy with Samara - go thru a couple of docs together to make sure aligned

**Comment by lianilychee** [comment]
Fri 1/28:
- yesterday:
  - Jill: tied up with TMS
  - Samara: sync'd with Jill, knocked out some reviews
- today:
  - Jill: identify which docs need extensive work 
  - Samara: reviewing docs in row 36-67
- Monday SU: share findings from reviewing some of the docs

**Comment by lianilychee** [comment]
Mon 1/31
- Friday:
  - sync'd with Amy on working in Confl
  - Q: guidance around editing a live document.  A: make a copy of the live doc into a page in the drafts space
  - findings:
    - docs are well written but most choppy (no flow)
    - think a lot of content can be combined
    - perhaps recategorize docs to improve flow
- today:
  - select one of the docs from the "Performing QA testing" category
  - start transformation in drafts space, with application of how-to template

**Comment by lianilychee** [comment]
Tues 2/1:
- no blockers yesterday
- today: continue working on the quality docs in the drafts space today per content reviews

**Comment by lianilychee** [comment]
Weds 2/2:
* no blockers yest
* today:
  * Continue working on QAST docs in drafts space
  * no scope changes
  * would like content review
