### ISSUE TITLE
[FE] Error Logging to Sentry 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#35568]
## Description 
FE currently only logs in GA but there is a potential way to handle error logging in Sentry. This story is for FE Engineers to meet/discuss/brainstorm possibilities of how logging can be loaded to Sentry. 

## Tasks
- [ ] Corey to set FE Engineering meeting 
   - [ ] Include Dillo for BE 
- [ ] Possible solutions discussed and documented

## Acceptance Criteria 
- [ ] Decision has been made on how to handle Sentry logging for FE
- [ ] FE logs can now be viewed in Sentry

**Comment by sarahknoppA6** [comment]
@mdewey still working on validation

**Comment by sarahknoppA6** [comment]
@mdewey does this need to be reopened per the info above? Discussed at validate meeting, next steps unclear.

**Comment by sarahknoppA6** [comment]
will be covered at sentry working session- Sarah to schedule

**Comment by sarahknoppA6** [comment]
@mdewey team is unsure if these are ready to close

**Comment by mdewey** [comment]
@sarahknoppA6 Team was given an overview, this is good to close
