### ISSUE TITLE
QA CONTENT: Set up usability tests

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#35562]
# User story

As a Content team member or QAST member, I need to understand VFS sentiment before and after transformation so that we know we're creating valuable content. 

# Tasks

- [x] Establish responsibility between QAST and Content Team
- [ ] Draft research plan
- [ ] Draft recruiting plan
 
# Acceptance criteria
- Be setup to execute research studies

# Reference info
- [Transformation sentiment tracking](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2042003632/Transformation+sentiment+tracking)
- If we don't have basic background knowledge up-front of our users, then we can't make meaningful progress on improving UX.  We can make structural changes but the actual info _on_ the pages won't actually change.

**Comment by lianilychee** [comment]
Ticket not filled in because assignee was OOO during sprint planning.

**Comment by lianilychee** [comment]
Fri 1/28:
- want to have a rsch plan drafted today
  - possibly pending goals feedback from QAST and participants xls from SD
- SU Monday: want to have rsch plan ready for review & (stretch) prospective particpants

**Comment by lianilychee** [comment]
Mon 1/29:
- notes
  - looked thru the 3 categories:
    - the docs are written for engineers focused on QA, or QA ppl - designers aren't going to be going into TestRail
    - we should ask the non-engs "do you participate in QA activities, and what do you need to know"
    - QA has different definitions - formal QA activities vs reviewing
- today: touch base with Rachael

**Comment by lianilychee** [comment]
Tues 2/1:
- today: finish research plan and picked out participants
- tmr: validate rsch plan with Naomi, start recruiting/scheduling

**Comment by gmaciolek** [comment]
Tues recap:
- Research plan: 90% completed
- Recruiting plan: blocked a bit--need more help than I thought I did

Wed 2/2:
- Review research plan with Naomi and finalize
- Get Naomi's help with my recruitment questions to choose potential participants

**Comment by lianilychee** [comment]
- we _could_ do have the sessions earlier next week but want to be conservative for making/testing convo guide
- scheduling sessions for EOD Tues onwards, so we can hit OCTO-DE office hrs on 15th
- question for the future: not sure who to pilot with
