### ISSUE TITLE
Add content of FSR email template to VA Notify Portal

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#35579]
## Issue Description
Take content of FSR email template and add to staging.notifications.va.gov notifications.va.gov (Prod)

---
## Tasks
- [ ] Login to portal over VA network and add email copy

## Acceptance Criteria
- [ ] Email copy and uuid is available through VA Notify
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
