### ISSUE TITLE
Set up example repo for integration

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#35577]
Others need to be able to integrate their apps with our access management solution easily - an example repo is the first step for this.

**Tasks**
- [ ] Create a repo
- [ ] Create directories that map to programming languages
   - (tbd)
- [ ] Clean up any examples and add helpful comments
- [ ] Create an informative readme file

**Done when**
Example repo is ready and all tasks are done

**Comment by calquisola** [comment]
repo created. https://github.com/department-of-veterans-affairs/pst-amt-keycloak-examples-integration
