### ISSUE TITLE
Add FSR email notification uuid to API settings

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#35581]
## Issue Description
UUID from FSR email template needs to be added to API so notification events can be triggered 

---
## Tasks
- [ ] Take uuid from created template on VA Notify portal and add to settings

## Acceptance Criteria
- [ ] Template uuid is accessible from global Settings object
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
