### ISSUE TITLE
Auth Profile: Address Notification: Update modal reminder mock ups based on design feedback

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35582]
## Background

We presented the mockups as the design open office hours.... Based on design feedback, short-term changes to content/IA within the modals will allow us to move forward with these modal reminders.

## Tasks
- [x] Update content/IA within modals based on design feedback to meet suggestions conveyed in design office hours
- [x] Present mockups to team in workshop #35985

## Acceptance Criteria
- [x] Modals are updated based on design feedback
- [x] Mockups have been presented to team in workshop
- [x] Check in with Liz for modal feedback

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
Closing this issue; it's a duplicate.

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I just added some additional info to the description here before seeing that you are going to close this. Which ticket is this a duplicate with? I don't see another that addresses the short-term content changes within the modals, just the long-term discovery. But I certainly could be missing it!

**Comment by MarciMcGuireGCIO** [comment]
This needs to be updated after the workshop meeting to discuss possible solutions

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I have updated the two tickets surrounding address change mockup updates to reflect the two different phases of the design work.

This one - Modal work: changes to the modal content/bringing these designs to our workshop/feedback from Liz. This is all done, but please let me know if I am missing any tasks. This would then lead into the content/verbiage ticket #35987 
[Link to Sketch file showing design](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/zk8pbe/a/EL2Kvm2)

#35585: Mockups for displaying in-line alerts and other items discussed in our workshop (wider in scope), referring to items beyond the modal content/IA

**Comment by cgednalske** [comment]
These updates where made. [Sketch files](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2)

**Comment by cgednalske** [comment]
Updates were made to the modal content/IA: [Sketch files](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2)

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !
