### ISSUE TITLE
[Design][Discovery] Auth Profile:  Address Change Messaging: Discovery for in-line alerts and other address update changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35585]
## Background

Based on design feedback from office hours, solutions for Content/IA changes address change modals were updated to meet suggestions that will allow us to move forward with modal solution. Their suggestions included changes to modal content/IA, as well as other questions to address surrounding the entire address update flow. _In addition, a one-per-page solution was suggestion, which we will not be exploring for Profile at this time._

Our team then held a workshop/brainstorming session to discuss the following:
1) proposed modal mockups with updates to content/IA (see [#35582](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35582))
2) our additional questions surrounding the entire address update process on the Contact information page: user flow, multiple alerts, edge cases -- see [#35985](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35985). 

Based on this group discussion, the modal content/IA was then updated and reviewed by Danielle (see [#35987](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35987)). The resulting modal solution ([Sketch file](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2)) clears the concerns proposed at office hours and follows all design system guidance.

This ticket is a follow-up task addressing point 2 above -- to answer questions our team had that were separate from the modal content/IA. This includes questions regarding the "Use mailing address for home address" checkbox, how to handle multiple in line alerts, and other possible changes discussed during the session.  

## Tasks
- [x] Review any existing guidance in design system
- [x] Review options discussed with team
- [x] Schedule a review meeting with Samara, Marci, Adam, Tom

## Acceptance Criteria
- [x] Review any existing guidance in design system
- [x] Review options discussed with team
- [x] Schedule a review meeting with Samara, Marci, Adam, Tom

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO [This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35232) includes the information on feedback for the short-term and long-term changes needed -- located in the comments.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - I was just reviewing our Sprint Objectives and noticed we already had this task in the backlog for the current sprint.

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Can we move this to next sprint? This was the one that - based on the workshop - needed to have details defined and represents more of the "longer term" things brought up at office hours that we explored looking at the user scenarios (other than the content in the modal), and for which I'll now work on different solutions.

**Comment by MarciMcGuireGCIO** [comment]
Moving to next sprint

**Comment by cgednalske** [comment]
Thank you @MarciMcGuireGCIO!

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I have updated the information above with the process of how we got to this ticket. I hope it helps clarify the many overlapping parts with these changes and discovery. Let me know there are questions anywhere and if there's anything I should clarify further!

**Comment by cgednalske** [comment]
Link to [discovery documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/discovery/documentation.md) for Address Change Messaging

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske!
