### ISSUE TITLE
Brainstorming and research handoff

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35596]
## Issue Description

As a SD researcher I want to go through brainstorming session with my team so we can have multiple ideas to choose from before creating the pain point artifact
---
## Tasks
- [x]  Schedule session
- [x] Collaborative document ([Mural Board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1642744076645/0372bdf2b4166cc10b87d80bea9b3b145d33a635?sender=u9ea6bd3ca12795949b606150))
- [x] Facilitate session

## Acceptance Criteria
- [x] Team comes up with  multiple ideas to choose from ([Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643051633337/3f7f61ba85f8cc2f56fb4f20d99c45a17b825d8f?sender=u9ea6bd3ca12795949b606150))
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tayism** [comment]
Scheduled session for 1/21/22.

**Comment by tayism** [comment]
Ran successful session. Design brainstorm with the team (Jonathan to lead) 1/24.

**Comment by tayism** [comment]
Design brainstorm on 1/24 led to several design options. We are iterating on these today.
