### ISSUE TITLE
Domo Datasets - Identify and Document

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#35597]
## Issue Description
There are over 100 Domo datasets that are currently in use.  Making it difficult to troubleshoot, identify and manage the main datasets that are tied to active dashboards.  We need to clean up these datasets

---
## Tasks
- [x] Identify all Domo datasets
- [x] Document which datasets are actively being used and by what dashboard/team
- [x] Document what datasets are not currently in use/connected to active dashboards.

## Acceptance Criteria
- [x] All Domo datasets have been identified and documented so we can plan a strategy for updating, streamlining and/or removing.

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 added some more details around this work as discussed.  Please let me know if you want to discuss.

**Comment by jonathan-epstein13** [comment]
Have already tagged the DOMO datasets with the `clean/delete` tag. Cross checking with the spreadsheet mentioned above to make sure all possible datasets are tagged appropriately.

**Comment by jonathan-epstein13** [comment]
[Domo Dashboard Tracking](https://va-gov.domo.com/page/-100000/kpis/details/1774897923) 
[Domo Dataset Tracking](https://va-gov.domo.com/page/-100000/kpis/details/1750539515)
These are the _Beta_ cards created.

Thank you @chloedotbrown for your help and let me know what you all think of these so far.

**Comment by chloedotbrown** [comment]
Hey @jonathan-epstein13 - thanks for setting these up! I think it looks like a great start. Some things to consider:

- **Dashboard tracking**: The color rule we set this morning is hard-coded and set kind of arbitrarily. Should it be further back? More recent (i.e. only 2-3 months with no views)? Once you have a sense of what cutoff seems most useful, it might be worth creating a beast mode to connect the color rule to instead, in case we want to use these cards in the future.
- **Dataset tracking**: Wonder if highlighting the most recent run date is as useful for some of these? It the dataset is configured to update daily/weekly/monthly, it could no longer be in use, but still be updating regularly. I'm curious whether it might be helpful to change the datasource for this card to the [Datasets + Tags Output dataset](https://va-gov.domo.com/datasources/32326605-41ef-4cc2-8610-d3b6eb07b6b8/details/data/table) you recently shared. It could also be interesting to join on User ID with the People report so you're able to see who owns each one. These are just suggestions, so YMMV!

**Comment by jonathan-epstein13** [comment]
Updated the [Domo Dashboard Tracking](https://va-gov.domo.com/page/-100000/kpis/details/1774897923) and updated the [Domo Dataset Tracking](https://va-gov.domo.com/page/-100000/kpis/details/565265462) @chloedotbrown @michelle-dooley - Let me know what you both think and if we can mark this ticket as done and move on to the _strategy for updating, streamlining and/or removing._

**Comment by jonathan-epstein13** [comment]
Updated [Domo Dashboard Spreadsheet](https://docs.google.com/spreadsheets/d/1Y_PLJaBwkz6vaQSg0I1lFt7PCwws8bDuNeMPUpajlXY/edit#gid=0) with some of my notes for each dashboard straight from DOMO and _not_ from the cards mentioned above. I've marked down the distinct cards within each dashboard from DOMO that aren't up to date.

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 thank you so much!!  Yes I think we are good to mark this as done and move to the next step.
