### ISSUE TITLE
[UNPLANNED] Request COE URL

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35595]
Based on status (available and eligible), if a COE is determined to be ready to go, then FE needs to make a request for the url to the COE file.

## Considerations
- Mockup: [Review and download your COE](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139512694/simulate/sitemap)

## Tasks
- [ ] if status is `available` or `eligible`, request COE url from BE
- [ ] if there is an error with the request, show alert from mockups

## Acceptance Criteria
- [ ] The FE can support the URL request for the COE file
- [ ] PR is in place for review
