### ISSUE TITLE
Edge Cases - Discovery 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#35594]
## Issue Description
We continue to get dashboard requests that end up being edge cases.  Need to identify what types of data is needed that makes it an edge case and if there is an opportunity to include in existing dashboards or create a new standard dashboard that provides the additional detail need.

---
## Tasks
- [x] Review current edge case requests
- [x] Identify metrics and/or data sources that make them an edge cases
- [x] Reach out to teams to confirm metrics are still relevant and meet their needs - @michelle-dooley and @jonathan-epstein13 
- [x] Determine if there is an opportunity to add to existing or create new dashboards to support - @jonathan-epstein13 and @pavanhothi 
- [ ] Design new dashboard if applicable - @pavanhothi 

## Acceptance Criteria
- [x] We have a better understanding of the edge cases and how we can update/add/create new to minimize the need for edge cases.
---

**Comment by jonathan-epstein13** [comment]
Marked down the possible repositories to start looking into for the edge cases from the https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=1660978947[VFS KPI Standardization Backlog](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=1660978947)

**Comment by jonathan-epstein13** [comment]
Marked down the possible repositories to start looking into for the edge cases in the [VFS KPI Standardization Backlog](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=1660978947).

**Comment by chloedotbrown** [comment]
Hi all! I've added some additional notes to the Product Info, Metrics, and Why columns (C:E) for all edge case products on the [spreadsheet](https://docs.google.com/spreadsheets/d/1DFz37RiMxOG61ofBn8CJ3LeYJGLhSweLzKeE4EEnhpU/edit#gid=1799318623). I've also clarified the title for column D, so that it's clearer that these are existing metrics found in repos, rather than the ones we plan to include on a potential dashboard. These are a great place to start, but I imagine in most cases, we'll need to look to our [Analytics Playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) and see what other types of KPIs may be missing (or a better fit).

**Comment by chloedotbrown** [comment]
Also added links to 1st gen Analytics KPI dashboards, where they exist.

**Comment by chloedotbrown** [comment]
Hi all! I've created a [temporary dashboard](https://va-gov.domo.com/page/895399882) for us to visualize usage of 1st generation dashboards for our edge case products. 

Because we only started tracking VFS team statuses + activity log data after the standardized dashboards launched, I'm only able to filter for VFS activity only for 6/30/21 and beyond. I've also included a second card further back, but be aware that this may include activity from other Platform teams, VSA leadership, or VA stakeholders, in addition to the VFS teams who owned these products. 

Between the two of them though, I think we'll be able to answer basic questions about which dashboards are getting use!

**Comment by chloedotbrown** [comment]
I've added a new sheet to our [Edge Case Discovery workbook](https://docs.google.com/spreadsheets/d/1DFz37RiMxOG61ofBn8CJ3LeYJGLhSweLzKeE4EEnhpU/edit#gid=861385271) – this should help us start to go through the potential KPIs listed in column D of the "Initial Research" sheet to see if there's enough overlap to justify a potential 4th standardized dashboard.

@pavanhothi and @jonathan-epstein13 I filled out a row as an example, but let me know if you have any questions about how to fill out! Hopefully between the three of us, we'll be able to go through the metrics we found in Github and on older dashboards.

**Comment by michelle-dooley** [comment]
Reached out to each team, waiting to hear their feedback.

**Comment by michelle-dooley** [comment]
Added notes in workbook for Facilities and VAOS.

**Comment by michelle-dooley** [comment]
Added notes for Education& Benefits.

**Comment by michelle-dooley** [comment]
Per meeting on 3/1 @pavanhothi looking at data and feasibility of 4th dashboard with Profile and MyVA as test cases.  Also looking to see if any metrics could be addition to current dashboard.

**Comment by pavanhothi** [comment]
•	Added additional missing metrics to [Edge Case Discovery worksheet](https://docs.google.com/spreadsheets/d/1DFz37RiMxOG61ofBn8CJ3LeYJGLhSweLzKeE4EEnhpU/edit#gid=861385271)

•	Determined the few metrics which have potential to be included in our current standardized dashboards; checked those boxes on Edge Case Discovery worksheet under “Potential to include in current standardized” column

•	After looking into the data, metrics, previous dashboards, tickets etc. for MyVA and Profile, I found it is feasible for us to create a new dashboard with these two products; there are definitely a great deal more metrics to consider and track for MyVA, though the few metrics to be tracked for Profile have enough overlap with some of the MyVA metrics that it would be possible and make sense to create a new dashboard for these two products 

•	The payment/financial data for MyVA are newer metrics they wanted tracked after MyVA user feedback; this is where I found there to be a great deal of overlap in the metrics to be tracked for the Profile Direct Deposit feature

•	The payment/financial metrics for MyVA are primarily to track clicks and searches for things such as payments, debts, direct deposit etc. which ties in well with the metrics to track for the Direct Deposit feature of Profile

•	I’ve created and shared a new [Google Worksheet](https://docs.google.com/spreadsheets/d/1y87EkiITPaxOToDj5EH2qwVDVy0PRJtJsROwF7nNwYk/edit#gid=0) which includes all the known metrics for MyVA and Profile, and linked GA reports/dashboards to where those metrics are found and come from; I also added a checkbox column (Overlap) which is checked for those metrics where there is that overlap; I felt it would be a good idea to have all the metrics and links to data for both products in one place as we proceed forward with next steps

**Comment by michelle-dooley** [comment]
@pavanhothi @jonathan-epstein13 @chloedotbrown - thanks Pavan!!  Just scheduled a meeting for us to discuss.

**Comment by michelle-dooley** [comment]
Discovery phase complete.    Will create new ticket for design/development work if/when we decide to move forward on implementation.
