### ISSUE TITLE
Update builds to download VA-Internal certs from GitHub

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#35602]
## Description
Builds that depend on certificates from http://crl.pki.va.gov/PKI/AIA/VA/ often fail because that site is intermittently down. Demian set up a new [certificate repo](https://github.com/department-of-veterans-affairs/platform-va-ca-certificate) to have a more stable place from which we can download these certs.

Some projects that will need to be updated:
- vets-website
- content-build
- va.gov-cms

## Background/context 
https://dsva.slack.com/archives/CU1E4CX9U/p1642179992019100
https://dsva.slack.com/archives/CJYRZK2HH/p1642621456059600

---
## Tasks
Projects that use the crl.pki.va.gov should update their build files to point to the Github repo. This is essentially replacing all instances of `http://crl.pki.va.gov/PKI/AIA/VA` OR `http://aia.pki.va.gov/PKI/AIA/VA` with `https://raw.githubusercontent.com/department-of-veterans-affairs/platform-va-ca-certificate/main`

Devops repo should update:
- [x] `packer/eks-custom-ami/scripts/al2/install-va-certs.sh`
- [x] `packer/gha-runner/scripts/installers/install-va-certs.sh`

## Acceptance Criteria 
- [ ] jobs are successfully pulling certs from the GitHub repo

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/platform-va-ca-certificate/pull/2

**Comment by oseasmoran73** [comment]
Looks like the updated action gets latest certs if there have been changes. Closing out this ticket
