### ISSUE TITLE
Feature Request Process: Launch and Monitor

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35608]
## Issue Description
As a DS team member I want to launch and monitor the Feature request process so that VFS teams and OctoDE can start submitting new ideas to contribute to Va.gov  

---
## Tasks
- [x] Launch on [(1/24/2022) in VFS all teams channel, Platform channel
- [x] Target Audience VFS teams, leadership, Platform teams
- [x]  share the feature request [intake guidelines]   
       Canned response) to SREs and Oncall support Engineers
- [x]  PMs, Leadership, OCTODE - share the [internal user guide] and ask them to the 
       follow 
       instructions (In Platform channel)
- [x] Share the message to Andrea for the reminder to PM in Platform team channel
- [x] Answer any follow up questions from VFS and platform teams after launch 
- [x] Create confluence space to track feature request metrics 

## Acceptance Criteria
- [x] We will launch the Feature Request process and answer any follow up question from 
       VFS and Platform teams to assure they are being able to use this process successfully
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Feature request metrics tracking page ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2062844230/Feature+request+reports)

[Launch communications](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2067136555/Launch+communications+feature+request+process)
