### ISSUE TITLE
Create an initial draft  for pain point artifact

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35600]
## Issue Description
As a SD designer I want to create a rough draft to show leadership what can be the possibilities and get their feedback so that we can narrow down the scope for final draft 

---
## Tasks
- [x] Crazy 8 workshop
- [x] Synthesize the brainstorm ideas
- [x] Create a rough draft

## Acceptance Criteria
- [x] We will have a rough draft to show it to the leadership to ask for their feedback 
       https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643051633337/3f7f61ba85f8cc2f56fb4f20d99c45a17b825d8f?sender=jonathannelson8855
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Crazy 8s session ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643051633337/3f7f61ba85f8cc2f56fb4f20d99c45a17b825d8f?sender=jonathannelson8855)

**Comment by jonathanjnelson** [comment]
[Working document for pain point deliverable (some options)](https://vfs.atlassian.net/wiki/spaces/~849473557/pages/2062614723/Pain+point+deliverable+working+doc)

**Comment by jonathanjnelson** [comment]
[Rough draft of spread sheet ](https://docs.google.com/spreadsheets/d/1K3lIpECP2lKNYRc8dTPUXCck1VM1vAZaNi2C0w-yqDA/edit#gid=0)

**Comment by Khyatinp18** [comment]
@jonathanjnelson  Thank you so much, appreciate it!
I will close the issue now:)
