### ISSUE TITLE
VCL Modal broken link on va.gov 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35612]
### High-level user story
As a Veteran using VA.gov I need to be able to click on VCL modal in order to gain access to the Veteran Crisis Line in time of need.  

### Background
The following issue was identified as part of a post launch optimization, of which application insights are checked to make sure that no other pages are failing to direct. A broken link was found that is universal on va.gov that needs to be addressed by the owners.  The issue and temporary fix is explained below as well as suggested fix which needs to be completed by the owner of va.gov site.  

### The initial issue: 
- The original link on VA websites (https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat) directed to https://www.veteranscrisisline.net/get-help/chat. We had a redirect in place to the new URL, but it was getting stuck at /ChatTermsOfService.aspx?account=Veterans%20Chat and not directing users to the new site.

![Unknown](https://user-images.githubusercontent.com/70410912/150219727-8ca6bc14-f4be-4dff-885f-223e14166af4.jpeg)

### Temporary Solution
- Our temporary solution: Implemented a redirect directly from ChatTermsOfService.aspx?account=Veterans%20Chat to the redesigned site.

### Next Steps 
- We recommend that the owner update the old URL to https://www.veteranscrisisline.net/get-help-now/chat/ to avoid redirecting all together as part of web best practices.

### Tasks
- [x] Update the old URL to https://www.veteranscrisisline.net/get-help-now/chat/ to avoid redirecting all together as part of web best practices.
- [x] Test locally and validate fix is working in staging before push to production
- [x] Once validated in staging deploy to Prod  
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] VCL Modal is no causing broken links and suggested fix is validated in prod
- [x] VCL Modal is working as intended

**Comment by brianalloyd** [comment]
Validated on Prod, closing ticket in support.
