### ISSUE TITLE
Create a modal component that shows eligible or ineligible message

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35631]
## Issue Description
---
Creates an Info Modal component that will display on the second time a user signs into VA.gov with an MHV account.  The Info Modal will conditionally render content based on the the eligibility in the User Model.

## Tasks
- [ ] Create an info modal for the Account Transition
  - [ ] **Eligible** content
  - [ ] **Ineligible** content

## Acceptance Criteria
- [ ] 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Duplicate of https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/34939. @nsoutouras this can be closed.
