### ISSUE TITLE
Claim Status Tool - Contact Center Communication

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35643]
## Issue Description
In order to aid our troubleshooting efforts, we need to develop a template to provide to the Contact Center that outlines the data we need.

---
## Tasks
- [ ] Document the information we will need to successfully troubleshoot. i.e. What claims are missing? When was is submitted? Differentiate between claims & appeals (develop template for them)

## Acceptance Criteria
- [ ] Template developed and submitted to the Contact Center
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
