### ISSUE TITLE
[vamc] Research and resolve Orphaned Facilities that have not been associated to systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#35646]
## Story
As a Veteran I need to have accurate representation of facilities at my VAMC System, so I can best determine the facility that has the services I need on my health care journey.

## Resources
CMS - Top level parent listing of facilities.

## Task
- [x] Research all orphaned facilities and determine their associated system.
- [x] Move Facilities into the correct system and determine the following:
- [x] If mobile or old and not under use, archive the facility and update the POC
- [x] If active and correct, save as Draft and contact the POC to tell them they have a new facility from VAST and it needs Facility health services attached before it is published.

## Acceptance Criteria
- [x] Document or artifact showing the facilities and the outcome of the resolution. (Archive or Draft)

**Comment by ltrombley** [comment]
Task #35646 - Research and resolve Orphaned Facilities that have not been associated to systems - is Complete and moved to Validate
