### ISSUE TITLE
AutoSSO bug that has skip_dupe appended to the AuthnContext

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#35647]
## Issue Description
The `?skip_dupe=mhv` query parameter is used on the Unified Sign In page to allow a passthrough for MHV sign in flow (MHV -> VA.gov -> MHV) to let vets-api know to not fail auth if the user has multiple MHV IDs.

The appended `?skip_dupe=mhv` query parameter that is passed in the `authncontextclassref` headers needs to be removed before passing the `authn` context to the API.

---
## Tasks
- [ ] The skip_dupe query parameter will be removed

## Acceptance Criteria
- [ ] Sentry will not report an authn context mismatch
- [ ] vets-api will not panic because of an authn context mismatch
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
Tested and working
