### ISSUE TITLE
[Launch on 1/29] Redirect from facility detail pages to new VAMC Pittsburgh pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3564]
## Requested By
Facility Locator Team
Contacts: Michelle Middaugh (AdHoc), Dave Conlon (VA)

## Implementation Date
Date new URL(s) will be live: 1/29/2020

## Please indicate when the redirect(s) needs to be implemented

 [X] On the same date the new URLs launch

## Background
When a Veteran selects a facility from the Facility Locator search results, that location's facility detail page is displayed. 

![facility detail page.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9806acaa-9551-43ce-9463-ebf4873c09e3)

Facility pages for the Pittsburgh health care system have being redesigned and will be launched December 1. 
When these new pages are rolled out, the existing Facility Detail pages for the specific Pittsburgh systems locations will be archived

**Task**
- The existing (about to be retired) Facility detail page should redirect to the new facility detail pages. 
- Although the page will no longer be part of the workflow for the locations in the Pittsburgh system, this redirect is intended to assist visitors who may arrive to the page via outside links. 

**Acceptance Criteria:**
- When the Pittsburgh VAMC pages go live, the facility detail pages within Facility Locator will need to redirect to the new Facility pages. 

**Facilities to be changed**
 - University Drive: https://www.va.gov/find-locations/facility/vha_646 -> https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

- H. John Heinz III: https://www.va.gov/find-locations/facility/vha_646A4 -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

- Beaver County Clinic: https://www.va.gov/find-locations/facility/vha_646GC -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

- Belmont County Clinic: https://www.va.gov/find-locations/facility/vha_646GA -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

- Fayette County Clinic: https://www.va.gov/find-locations/facility/vha_646GE -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

- Washington County Clinic: https://www.va.gov/find-locations/facility/vha_646GD -> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

- Westmoreland County Clinic: https://www.va.gov/find-locations/facility/vha_646GB -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by davidconlon** [comment]
**Launch of Pittsburgh is TBD**

The website link on the existing (about to be retired) Facility detail page needs to redirect to the new facility detail pages.

_Note: this should be done automatically when Facilities/Vets API updates but we should verify_

Although the page will no longer be part of the workflow for the locations in the Pittsburgh system, this redirect is intended to assist visitors who may arrive to the page via outside

_Note: I'm not sure if this is the responsibility of our team or the content team.  Additional information is necessary.

**Comment by davidconlon** [comment]
We should look to make this a sustainable solution ongoing and, if possible, driven by the changes from Facilities API.

Assumption: none of the existing URLs for Facilities are www.va.gov but instead are SUBDOMAIN.va.gov

So we can do something like "if the URL for the facility is not www.va.gov, then use the facility ID and send users to the facility detail page, otherwise use the URL in the search results to bypass the facility detail page and send users to the facility page.

**Comment by mmiddaugh** [comment]
This should be addressed in the logic change for [#3385]. Need to include in QA effort.

**Comment by tlei123** [comment]
@mmiddaugh, is **Belmont County Clinic** really being redirected as part of this Pittsburgh ticket?  This clinic appears to be in Ohio.

I searched Pittsburgh, PA facilities on Staging and found no such result.  When I clicked the Details-page link listed above \[under __Facilities to be changed__ section], the address on the prod page shows **St. Clairsville, OH**.

![Screen Shot 2019-12-05 at 6 23 05 PM](https://user-images.githubusercontent.com/587583/70287664-05999400-178d-11ea-8290-8b8eefe5a22b.png)

Please let me know.  Thanks much!

**Comment by davidconlon** [comment]
@tlei123  Thanks for asking--this one surprised me as well and I had to hunt a bit.  I guess it's close enough to the PA border to be part of the VA Pittsburgh health system.  Once the official cutover happens the official page will be https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/ and the FL Detail page will be unnecessary/redundant.

**Comment by tlei123** [comment]
Thx, @davidconlon ^ !  All good here now.  :)

**Comment by mmiddaugh** [comment]
Closing as duplicate

**Comment by mnorthuis** [comment]
@mmiddaugh @davidconlon Can you provide/add the following info to the top of the request?  This will help the implementation team prioritize the work. 

## Redirect Request

### Requested By
*Indicate what team and who the primary contact on that team is*

### Implementation Date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch 
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes**

### Steps to complete
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mmiddaugh** [comment]
@mnorthuis  I've added the additional details at the top of the request.
Thanks!

**Comment by mnorthuis** [comment]
The URLs listed have been verified and are ready for redirect based on the date indicated in the request.   @mmiddaugh your team is responsible for ensuring all appropriate stakeholders are aware of the upcoming redirects and any changes to dates or the above info need to be communicated to those on this issue asap.  

Assigning to public websites team for implementation.

**Comment by Karak888** [comment]
Moving to ready and @ncksllvn will implement this has already been vetted.
