### ISSUE TITLE
Decision Review Analytics - Synthesis

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#3565]
## User Story or Problem Statement
As a researcher, I need to be able to see how the Decision Review page is currently accessed by system users so I can provide recommendation on future design for points of entry to the Decision Review page.

## Goal
_Gain deeper understanding of analytics provided by analytics team._

## Tasks
- [x] Meet with Nedie and delve further into analytics
- [x] Create report or readout based on information provided by Nedie

## Acceptance Criteria
- [x] Gained a solid understanding of the path by which users access the Decision Reviews page

## Details
- Analytics data initially provided by Nedie in ticket #3142

**Comment by kevinstachura** [comment]
Original analytics from Nedie:

[Please see the Google Analytics report filtered down to basic activity for `/decision-reviews`](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D/)

- Pageviews - 22,911
- Sessions - 13,198 (To measure how many sessions viewed this page, we use the `Unique Pageviews` column. This means there were 13K sessions where this page was viewed at least once).

Nuances:
- There is a parameter called `fbclid` which is a Facebook parameter, so a communications team is likely sending traffic there. We can remove this parameter to make the reports cleaner (and in doing so, we can still see what sources of traffic send activity there using other reports)

[Friction Points: This is the flow report that shows where users are coming from and where they go next (or drop off).](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-table.filter=~2Fdecision-reviews~2Findex.html&explorer-table.plotKeys=%5B%5D&_r.tabId=navigationsummary&_r.drilldown=analytics.pagePath:~2Fdecision-reviews~2Findex.html&navigationsummary-keySelector.searchTerm=decision-reviews/)

- Of the pageviews coming from a previous page, over 1/3 come from `/disability/file-an-appeal/index.html`
- More then 75% are moving onto another page, with `/disability/file-an-appeal/index.html` as the next page viewed

**Comment by kevinstachura** [comment]
Meeting with Nedie scheduled for Tuesday, December 3rd at 10:30am.

**Comment by kevinstachura** [comment]
Analytics Readout has been completed and translated to GH format here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/decision-review-va-gov-website-analytics.md
