### ISSUE TITLE
Research: Investigate how to speed up Cypress forms tests

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#35669]
## Issue Description
Currently the longest-running Cypress tests take several minutes to execute. All of these tests involve interactions with the forms system and use the Cypress form tester. This task is investigate thee root cause of this slow test performance and identify how to reduce test execution times.

---
## Tasks
- [ ] Investigate inefficiencies in the forms system.
- [ ] Investigate possible improvements to the Cypress form tester.
- [ ] Investigate resource starvation as a potential root cause.

## Acceptance Criteria
- [ ] Forms tests execute significantly faster on GitHub Actions (exact metrics TBD).

**Comment by pjhill** [comment]
* Find and document self-hosted runner resources
  * Are there any bottlenecks?

**Comment by ddzz** [comment]
Based on local testing, it appears that CPU load could be a bottleneck in CI. I've created a ticket with the Infrastructure team to create a larger EC2 instance that we can for testing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36972

**Comment by ddzz** [comment]
Tasks completed so far:
* Investigated dependency upgrades used by the forms system. No updates are needed there.
* Looked into forms system code to identify possible inefficiencies. The forms system primarily uses ReactJS code that does not appear to need any optimization.
* Made minor improvements to the form tester in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19938
* Monitored resource usage while running Cypress tests. CPU load appears to be a bottleneck.

EC2 instances used in `vets-website` will be upgraded to larger instances by EOD today. More testing will be done after that upgrade.

**Comment by ddzz** [comment]
On Friday I tested running Cypress tests without Docker in CI to see if Docker could be causing any performance issues. There was no significant performance difference without Docker.

**Comment by pjhill** [comment]
@ddzz -- Please add some comments about the methods you've tried and the results.

**Comment by ddzz** [comment]
On Friday I tested out running tests using Node v16 instead of Node v14 and saw no performance difference.

**Comment by pjhill** [comment]
- [ ] Schedule a brainstorming session with SMEs to come up with some additional ideas

**Comment by ddzz** [comment]
Today I merged a PR that speeds up typing commands in Cypress tests, which should speed up CI by a small amount. Also, I tested disabling certain features in Chrome. This did not have any effect on test times.

**Comment by pjhill** [comment]
Ideas about teams to consult for brainstorming --
* Forms Spike Team
* Release Tools
* Design System

**Comment by pjhill** [comment]
We still want to conduct a brainstorming session. Additionally, a mob session with the Forms Spike Team to figure out the issue with the particularly slow form implementation uncovered during this effort should be queued up.
