### ISSUE TITLE
Login.gov Inherited Proofing - vets-api service Pt. 1

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#35662]
## Issue Description
Create a new service to interact directly with Login.gov for the MHV inherited proofing flow. This service will generate an auth code to be sent with the user to login.gov and then when login.gov calls this service with the auth code we will respond with user attributes. This PR covers the first half of this flow, the authentication request with a unique `auth_code`.

---
## Tasks
- [x] create & save an `auth_code` in Redis with a 90 minute timeout
- [x] create `inherited_proofing/auth` route & controller method within the v1/sessions_controller
- [x] create `inherited_proofing/logingov` service to interface with Login.gov for inherited proofing
- [x] append generated auth code as `inherited_proofing_auth` URL parameter to a new OAuth authentication call to Login.gov

## Acceptance Criteria
- [x] vets-api can generate an auth_code and save it to Redis along with the user's uuid
- [x] vets-api can append the auth_code to a Login.gov authentication request

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
