### ISSUE TITLE
Update Survivor DIC rates page with information about the phaseout of the SPB-DIC offset

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35676]
## Issue Description
A stakeholder reached out that we need to add information to our [survivor DIC rates page](https://www.va.gov/disability/survivor-dic-rates/) about the phaseout of the SPB-DIC offset.

The bold part of this section needs to be updated:

H2: What happens if I’m receiving SBP or RCSBP payments and then qualify for DIC—but the exception above doesn’t apply to me?

The Defense Finance and Accounting Service will reduce your SBP or RCSBP **by the amount of your DIC payment**. If your DIC payment is greater than your total SBP or RCSBP payment, the Defense Finance and Accounting Service will stop your SBP or RCSBP payments. This is called the “SBP/DIC offset.”

The new information provided: 

In 2021 the offset was 2/3 of DIC, In 2022 it is 1/3 DIC.  The offset is totally eliminated in 2023. 

We need to update this page to reflect this year's change and also make a change to our 2021 past rates page. We should consider if we need to note that this will be eliminated for 2023. 

They are also asking if we can include a link to the page about the phaseout: https://www.dfas.mil/RetiredMilitary/survivors/SBP-DIC-News/

We need to assess the ask and then implement the changes. Once this work is complete, we should post the changes for Beth to review in the publishing ticket #35678. 

## Tasks
- [x] Assess stakeholder request (Selina)
- [x] Rework pages with updates (Selina)
- [x] Review (Patrick)
- [x] Copy edit (Randi)
- [x] Send to Beth for final review (Selina)

## Acceptance Criteria
- [x] Content is ready for final review

**Comment by lunascoop** [comment]
@psanders86 My edits to the 2022 page per the stakeholder's request are ready for your review. Once the language is approved, I'll make the same updates to the 2021 page, only replacing 1/3 with 2/3. 

I did decide to include a link to the page the stakeholder recommended as it does provide some helpful info. I chose this over adding the content to our current page, which is already pretty content heavy.

Something else to consider: Should the Note and link be added to all the past rates pages (including 2020 and 2019)? 

Here's what changed: The first paragraph was broken out into bullets since the new info only applies to SBP payments. I also added the Note and link to the article.

2022 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=1012

### What happens if I’m receiving SBP or RCSBP payments and then qualify for DIC—but the exception above doesn’t apply to me?

This depends on the type of payments you're currently receiving.

- **If you’re receiving SBP payments,** the Defense Finance and Accounting Service will reduce that amount by one-third of your DIC payment. 
- **If you’re receiving RCSBP payments,** the Defense Finance and Accounting Service will reduce that amount by the amount of your DIC payment. 

If your DIC payment is greater than your total SBP or RCSBP payment, the Defense Finance and Accounting Service will stop your SBP or RCSBP payments. This is called the “SBP/DIC offset.”

If the Defense Finance and Accounting Service pays you more than the offset amount in SBP or RCSBP payments after you begin receiving DIC payments, they’ll consider this amount an overpayment. This means you’ll have to pay the money back.

Be sure to notify the Defense Finance and Accounting Service as soon as you qualify for DIC so they can reduce your SBP or RCSBP payment amount and you can avoid owing money. You’ll need to send them a copy of your VA DIC award letter. You can call the Defense Finance and Accounting Service at 800-321-1080, Monday through Friday, 8:00 a.m. to 5:00 p.m. ET.

**Note:** Starting on January 1, 2023, the Defense Finance and Accounting Service will no longer reduce your SBP payments if you also qualify for DIC. You can receive full benefits through both programs at the same time. This plan to eliminate the SBP/DIC offset began on January 1, 2021.

[Learn more about the SBP/DIC offset elimination on the Defense Finance and Accounting Service website](https://www.dfas.mil/retiredmilitary/survivors/SBP-DIC-News/#FAQs)

**Comment by psanders86** [comment]
I do recommend the note be added to older pages! There are also some minor style issues on the older pages that I think we can fix (mostly in numerals).

**Comment by RLHecht** [comment]
@lunascoop @psanders86 Here is the word doc I just posted about in slack.

[https://app.zenhub.com/files/133843125/6e57e2ad-c39e-444d-a06a-60c6c4c81b08/download](https://app.zenhub.com/files/133843125/6e57e2ad-c39e-444d-a06a-60c6c4c81b08/download)

**Comment by psanders86** [comment]
We need to sync with the stakeholder on a couple of issues. We need clarity if the offset applies also to RCSBP payments, and we need to discuss their edits. Moving this to blocked until we can have that conversation.

**Comment by bethpottsVADEPO** [comment]
@psanders86 Let's chat about next steps. I'm free the rest of today, or tomorrow 10:00 to 11:00 a.m. ET or 1:00 to 2:30. Do any of those times work?

**Comment by psanders86** [comment]
I'm open free from 1 to 2:30 p.m. ET today to chat, thanks!

**Comment by RLHecht** [comment]
@lunascoop @psanders86 The stakeholder answered our question and it does in fact also affect RCSBP. Here's the response and a fact sheet they sent:

RCSBP and SBP are both affected by the SBP/DIC offset. RCSBP is essentially an annuity designed for survivors of individuals that served in the Reserve Component. I have attached a fact sheet that further explains RCSBP entitlement. Please note, page 6 of this fact sheet explains the offset of RCSBP based on DIC entitlement and also refers to the phase-out elimination of the SBP/DIC offset.

[https://app.zenhub.com/files/133843125/7c3e8dce-a8ea-4be4-be10-b5d511e313e8/download](https://app.zenhub.com/files/133843125/7c3e8dce-a8ea-4be4-be10-b5d511e313e8/download)

**Comment by psanders86** [comment]
Made some tweaks to this after reviewing stakeholder feedback and moving it to validate.

**Comment by lunascoop** [comment]
@psanders86 I combined the first part of the What happens if I’m receiving SBP or RCSBP payments and then qualify for DIC—but the exception above doesn’t apply to me? Q&A based on the stakeholder feedback. That change is ready for your review.

 http://preview-prod.vfs.va.gov/preview?nodeId=1012

**Comment by psanders86** [comment]
OK, thank you! I have a meeting at 11 a.m. and will review afterward.


[cid:7629bde2-17d5-4d93-b716-0b31284b4a0f]

Patrick Sanders

Content Writer



M:  240-444-6116


About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>

Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.­

________________________________

**Comment by psanders86** [comment]
@RLHecht This is ready to move on to the next step. Thank you, @lunascoop!

**Comment by RLHecht** [comment]
Just reviewed and all good. I'll post the preview link for Beth in the next ticket.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I reviewed and made some edits. This is ready for you to follow up with stakeholders for review. I'll let you close this ticket.

**Comment by lunascoop** [comment]
@RLHecht I made these changes to the past rates pages and they're ready for review.

- 2022 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=1012
- Past rates: 2021 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=38663
- Past rates: 2020 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=11018
- Past rates: 2019 VA DIC rates for spouses and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=6799

**Comment by bethpottsVADEPO** [comment]
@RLHecht I just edited the 3 Q&As in question following my conversation with Angie. Ready for you to copyedit again. Let me know if you make any changes so I can ratake screen shots if necessary.

**Comment by RLHecht** [comment]
@bethpottsVADEPO This looks good. I made one small change. I added a "the" before DFAS in the second sentence of the second paragraph here.

<img width="846" alt="Screen Shot 2022-02-14 at 3 55 59 PM" src="https://user-images.githubusercontent.com/48728214/153945107-1b19808b-05d3-4951-a588-08d577954228.png">
