### ISSUE TITLE
Add guidance about avoiding sub bullets to bulleted list entry in style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35671]
## Issue Description
We need to add guidance to our style guide entry on [bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists) about avoiding sub bullets. The writer should rework the content instead so that the sub bullets aren't needed.

## Tasks
- [ ] Write entry (Randi)
- [ ] Review (Beth)
- [ ] Publish (Randi)
- [ ] Notify design system team (Randi)

## Acceptance Criteria
- [ ] New guidance is live on the style guide

**Comment by RLHecht** [comment]
Update: This can be worked on at any time and pulled out of the backlog when there is time.

**Comment by laurenvocke-va** [comment]
We added this to the style guide in June 2025. Closing this ticket.
