### ISSUE TITLE
Map is not uploading when changing locations (Mobile)

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#35672]
## Issue Description
On mobile, I noticed that while the search list refreshes when changing locations, the map does not load.  For example, searching one city initially will load the map, but if I search a different city, the list will update but the map is blank.  This is mitigated if I hit refresh, however.  The map will load after refresh.

---
## Tasks
- [ ]  Dev
- [ ]  QA
- [ ] UAT

## Acceptance Criteria
- [ ]  Map on mobile devices should refresh when changing locations.
- [ ]  Make sure this change does not affect CT App. (not mobile)
- [ ]  QA: Make sure to test all supported mobile devices and CT Map on "desktop" app
---
## How to configure this issue
- [ ] **Labeled with Team** (`product support`)
- [ ] **Labeled with Practice Area** (`mobile functionality in CT`)
- [ ] **Labeled with Type** (`Defect`, `afs-education`, `afs-edu-comparisontool')

**Comment by hallihocine** [comment]
Ticket has been validated in staging: The Map on mobile devices refreshes when changing the search locations. See below: 

https://user-images.githubusercontent.com/86266024/151872396-f581e255-f76a-41fe-b415-a5534d153ad8.mp4

**Comment by hallihocine** [comment]
- Test Run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/2882&group_by=cases:section_id&group_order=asc&group_id=3598
- Test Script/Steps: 
[Map is not uploading when changing locations (Mobile).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7974236/Map.is.not.uploading.when.changing.locations.Mobile.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 2/3/2022.
