### ISSUE TITLE
Publish changes to Survivor DIC rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35678]
## Issue Description
We need to do a final review of the work completed in ticket #35676, send to stakeholders for any feedback and publish the changes. 

## Tasks
- [x] Final review of updated content (Beth)
- [x] Send to stakeholders for approval (Randi)
- [ ] Incorporate any changes (Selina)
- [x] Copy edit and publish (Randi)
- [x] Notify stakeholders that changes are live (Randi)

## Acceptance Criteria
- [x] Changes to page are live on the site

**Comment by SgardnerPMP** [comment]
Pushed to Sprint 66,  Final approval, crosscheck and publish outstanding.

**Comment by RLHecht** [comment]
@bethpottsVADEPO This page is now ready for your review. We only made changes to the 2022 rates page until you approve them. Then we would add the note to the past rates pages as well. preview-prod.vfs.va.gov/preview?nodeId=1012

**Comment by bethpottsVADEPO** [comment]
@RLHecht I reviewed and made edits. Ready for you to run it all past stakeholders.

**Comment by RLHecht** [comment]
Stakeholders approved content and I reviewed and published the pages. Moving this to validate and will let stakeholders know once the pages are live.

**Comment by RLHecht** [comment]
Update: We published the new changes to the 2022 page and are awaiting the stakeholder's approval to also publish them for the 2021 page. Patrick reviewed my other changes to the 2019 and 2020 pages based off the updates to the 2022 page and those were published as well.

**Comment by RLHecht** [comment]
Update: Angie OK'ed the changes for 2021. These were input and published. Once they are live this ticket can be closed.
