### ISSUE TITLE
Assess QA Products: GitHub Issues

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#35699]
## Issue Description

In preparation to support the 2022 platform objective of migrating services to be operated within a Platform Console, we’ll conduct an assessment of team services, products and resources to identify what information we need to know in order to properly, and to determine what potential improvements could be made to that component, either prior to the migration, during the migration, or after the migration.

---
## Tasks
- [ ] Review the component: GitHub Issues processes, tools and outputs
- [ ] Compile a list of questions that we need to have answers to in order to be prepared to migrate to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen prior to or during the migration to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen after the migration to the Platform Console
## Acceptance Criteria
- [ ] Complete assessment of the specified component and record findings in Confluence page
- [ ] Review findings with team leadership and ensure any modifications are incorporated

**Comment by noahgelman** [comment]
Confluence has been updated with [questions/estimates](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2057502870/Assess+QA+Standards+Products+for+Integration+with+Platform+Console). This would be a multi-step process of testing a new alternative (like Jira) for a small team and then, migrating the whole system if approved

**Comment by pjhill** [comment]
Assessment completed -- from here we need to distill and create work items.
