### ISSUE TITLE
Assess QA Products: GitHub Actions Workflows

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#35698]
## Issue Description

In preparation to support the 2022 platform objective of migrating services to be operated within a Platform Console, we’ll conduct an assessment of team services, products and resources to identify what information we need to know in order to properly, and to determine what potential improvements could be made to that component, either prior to the migration, during the migration, or after the migration.

Fun prompts --

* Can we trigger a parameterized workflow from Platform Console?
  * For example, a user checks off a few tests and clicks execute. We feed that list of tests into the workflow, and it executes just those.
  * Alternatively, a user picks a test environment to target from a dropdown. We feed that target environment into the workflow, and it executes all tests in that environment.

---
## Tasks
- [ ] Review the component: GitHub Actions Workflows processes, tools and outputs
- [ ] Compile a list of questions that we need to have answers to in order to be prepared to migrate to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen prior to or during the migration to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen after the migration to the Platform Console
## Acceptance Criteria
- [ ] Complete assessment of the specified component and record findings in Confluence page
- [ ] Review findings with team leadership and ensure any modifications are incorporated

**Comment by rbeckwith-oddball** [comment]
### Parameterized workflow
  - Are we wanting to _actually_ trigger the workflow *from* the console, or *for* the console (upon PR, Pull, etc.)
  - Personally, I feel like having environmnets configured in github will make conditional workflows easier in the long run
    - This would allow specific tests to be run on certain environments
    - Some tests are more beneficial to run early on, whereas having the same tests run in other environments can also be superfluous

### Component Review
After having searched through several of our repos and their associated workflows,
the most common uses of github actions is:
1. Building and running a security scan engine (i.e. trivyscan)
2. CodeQL building and testing
3. Pull AWS SSM Secrets into specific configurations
4. Automatically tagging and releasing the newest merge to master
  a. Which automatically updates associated manifests
5. Install jsonnet (specific to vsp-infra-application-manifests and devops)
6. The devops repo has the most extensive github actions setup
  a. Not all of the workflows are triggered by PR
  b. Several are run on schedules
7. Some functionality that platform console may use (from devops)
  a. Rolling updates
  b. AWS EC2 (and other resource) management
  c. Cleaning up old / stale github runners
  d. Notify slack of success / failure
  e. EBS snapshot tagging (for billing and inventory management)

#### Questions:
1. What components are going to be incorporated into the platform console
  a. i.e. backend, frontend, databsae, etc.
2. What tests are we wanting to run against the platform console
  a. Syntax checks
  b. traefik lint (if traefik gets used in Platform Console)
  c. unit tests
  d. load tests
3. How fault-tolerant do we intend to make the tests
4. What team's functionality / workflows would like to utilize in Platform Console

**Comment by pjhill** [comment]
Thanks for colleting your analysis and questions!
