### ISSUE TITLE
Assess QA Products: Smoke Testing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#35691]
## Issue Description

In preparation to support the 2022 platform objective of migrating services to be operated within a Platform Console, we’ll conduct an assessment of team services, products and resources to identify what information we need to know in order to properly, and to determine what potential improvements could be made to that component, either prior to the migration, during the migration, or after the migration.

---
## Tasks
- [ ] Review the component: Smoke Testing processes, tools and outputs
  - [ ] Review the related sub-components that related to this area: Puppeteer, AWS Canary, PagerDuty
- [ ] Compile a list of questions that we need to have answers to in order to be prepared to migrate to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen prior to or during the migration to the Platform Console
- [ ] Compile a list of potential modifications to the component that should happen after the migration to the Platform Console
## Acceptance Criteria
- [x] Complete assessment of the specified component and record findings in Confluence page
- [x] Review findings with team leadership and ensure any modifications are incorporated

**Comment by pjhill** [comment]
Compiling a set of questions is totally a good output from this. You can add the questions to the Confluence document where we are collecting other feedback.

**Comment by pjhill** [comment]
Thanks for adding your analysis to the Confluence doc.
