### ISSUE TITLE
[UNPLANNED] LGY Display Application Date

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#35700]
## Background
When displaying a Pending application for LGY, we need to display the application date from LGY (currently we are just showing a static placeholder).

## Considerations
- Is this only for Pending applications?
  - For now I included the date for `pending` and `pending-upload`
- Do we need another ticket for the FE work?
  - I just used one ticket here for both FE and BE pulls (-Kevin)

## Tasks
- [x] Retrieve the application date from LGY and return it in the payload to the FE
- [x] Update specs if needed

## Acceptance Criteria
- [x] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
Thanks @kathleencrawford

**Comment by kathleencrawford** [comment]
You're welcome!  @RudyOnRails I did not point it though...will leave that up to you and Jason
