### ISSUE TITLE
[UNPLANNED] LGY Application Documents Required

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#35701]
## Background
Display the appropriate screen for LGY when additional documentation is required (Eligibility Determination = Pending, Application Status = Returned).

## Considerations
- We will also need a corresponding FE ticket 

## Tasks
- [ ] Check for the appropriate values and return `documents-required` to the FE
- [ ] Make sure FE has a corresponding value
- [ ] Add or update test specs

## Acceptance Criteria
- [ ] A PR has been requested for merging

**Comment by RudyOnRails** [comment]
@kathleencrawford we have a condition for this already I think:
```
      elsif get_determination.body['status'] == 'PENDING' && get_application.body['status'] == 'RETURNED'
        'pending-upload'
```

These are the statuses I see on the FE:
```
export const COE_ELIGIBILITY_STATUS = {
  available: 'available',
  denied: 'denied',
  eligible: 'eligible',
  ineligible: 'ineligible',
  unableToDetermine: 'unable-to-determine-eligibility',
  pending: 'pending',
  pendingUpload: 'pending-upload',
};
```

Sounds like BE work is done and this can be a FE ticket?

**Comment by jason-gcio** [comment]
This should be in place already, will confirm

**Comment by kathleencrawford** [comment]
I believe Jerek fixed this or at least knew what the issue was and how to resolve it.
