### ISSUE TITLE
Publish revised TSGLI R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35702]
## Issue Description
Now that we've broadened the scope of the [TSGLI article](https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/) we currently have in R&S, we need to do a final review, send to stakeholders for approval, and publish the new content. 

The initial work for this ticket was completed in ticket #32127

We also need to determine if we need a redirect with a new H1 and set up a redirect ticket if necessary.

## Tasks
- [ ] Final review of article (Beth)
- [ ] Build page in Drupal (Randi)
- [ ] Ask Mikki if need redirect if H1 changes (Randi)
- [ ] Create redirect ticket if needed (Selina)
- [ ] Send to stakeholder for approval (Beth/Randi)
- [ ] Incorporate stakeholder feedback (Randi)
- [ ] Review and publish (Randi)
- [ ] Notify stakeholder that change is live (Beth/Randi)

## Acceptance Criteria
- [ ] Updated TSGLI article live on the site

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here is the updated article. I put it in a Word doc rather than reworking the Drupal page for now, but let me know if you'd rather I flow it into there. I didn't list out the contact info again because it's all in the current article but now that the page is longer I think we should put them into accordions.
[37ec0cae-4c13-407e-8f73-a55eca495bec.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7936182/37ec0cae-4c13-407e-8f73-a55eca495bec.docx)

**Comment by RLHecht** [comment]
Update: This ticket is awaiting Beth's final review before moving forward. All the tasks at the top of the ticket are still accurate. Once ready for stakeholders, send it to Steve Fital at VA.

**Comment by RLHecht** [comment]
The PDF that is referred to in the ticket for the initial work has been updated. This is it: https://www.benefits.va.gov/INSURANCE/forms/SGLV_8600_ed2021-11.pdf

**Comment by laurwill** [comment]
Hi @megzehn ,
I reviewed the background of this ticket, put the draft content updates in Drupal, and made some additional copy and formatting tweaks (including putting the contact info for each branch back into accordions). 

Here's the preview link ready for your copy edit: http://preview-prod.vfs.va.gov/preview?nodeId=15172

One note: [Previous content team had added ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32127#issuecomment-956566982)some hours and dialing info for the phone contacts that wasn't included in the PDF — they had the "select" instructions on the same line with the phone number, but I did a soft return there instead. See what you think of that formatting!

**Comment by mnorthuis** [comment]
Hi @laurwill!  Let me pull some data on this page and get back to you...

**Comment by mnorthuis** [comment]
Hi @laurwill!   The H1 change on this is pretty drastic - can someone looking to get a higher TSGLI payment find that explicit answer on this page?  If yes, the title of the page is not reflecting that there may be more information than just contact numbers.  If no, then this may not be an appropriate redirect and where would one find that answer? 

Also, I took a look at analytics for this page, which are pretty low.  We can use this info in conjunction to the answer to the above question to determine if a redirect is needed. 
- 190 page views in 6 months
- 51 (27%) of the page views were visitors entering the site on that page
- 107 (56%) of the page views were visitors coming from another page in resources and support
- 21 (11%) of the page views were visitors coming from the life ins hub or a life ins page in ebenefits

**Comment by laurwill** [comment]
Thanks @mnorthuis ! Your response made me go back and look more closely at how this page fits in with other TSGLI content on the site, and that raised a couple new issues — so I'm going to take this back for another look. And as we chatted, I'll also start a convo about H1 change considerations in our Monday content meeting.

@bethpottsVADEPO I found some related content on other TSGLI pages that I have questions about, and I think it's easier over zoom — I'll find a time for us to chat early next week!

**Comment by laurwill** [comment]
Hello! Several updates to note here:
- Per a chat with Mikki, we won't do a 1:1 redirect here—instead, we'll redirect the original URL to the R&S landing page
- I considered keeping this H1 a bit closer to the original (something referencing payments, claims, etc) but the use case is wider here so sticking with "Contacting your TSGLI office"
- After poking around all of the TSGLI-related pages on the site, I'm recommending some small related updates to the main TSGLI page and this [File a TSGLI Appeal ](https://www.va.gov/life-insurance/file-appeal-for-tsgli/)page as well 
- Steve (life insurance stakeholder) just let us know that they've updated the TSGLI application form again, but the link to the form is currently broken — since that form is our source for the contact info on this page, I think we should hold on copyedit here until we have the correct form to check against

I'll post back when we have the correct form link and all 3 pages are ready for copyedit!

And also noting that after we publish the updated R&S page, we'll want to update the Change your address on file with VA page to link here as well.
