### ISSUE TITLE
Research how to modify the form system to allow for us to hide the continue button on the search representative results page

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#35713]
# Background
For the front end for search rep on the search results page we need to hide the "continue" button as the design calls for it. The thinking is that we want the user to choose a representative by clicking the "Select this representative" link on the card for the representative they want. We don't want the user to be able to continue forward without selecting a representative. 

[Sketch Mockup](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/paW4KWA)

[UX Pin rototype](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145470467/simulate/sitemap)

Currently the form system does not allow us to hide the continue button on a page. We need to do some research to find out what level of effort is involved with possibly hiding the continue button on a single page and if this is even possible.

## Tasks
- [ ] Research if the code of the form system can be modified to allow us to hide the continue button on a single page
- [ ] Create a ticket for a path forward

## Acceptance criteria
- [ ] Research into the viability of hiding the continue button on a form system page has been conducted
- [ ] A ticket with a path forward has been created

**Comment by jason-gcio** [comment]
Maybe need to go back to the drawing board (Design)
