### ISSUE TITLE
HIde all fields from search on the review page for search and appoint representative

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#35714]
# Background
Now that we have the appoint rep pages in the search and appoint rep form we need to hide the information from the search rep sections of the form in the review page. The design calls for all of these sections except for the "chosen representative" to be hidden. We don't have a design yet for what the "chosen representative" information should look like but we can leave that information on the review page and change the way it is presented once we have a design.

[UX Pin Prototype](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145370925/simulate/sitemap)

## Tasks
- [ ] Hide all information from the search portion of the search and appoint rep form besides the "chosen representative" from the review page
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] All information on the review page for the search portion of the search and appoint rep has been hidden aside from the. "chosen representative"
- [ ] A PR has been submitted for review

**Comment by jason-gcio** [comment]
To do: another ticket for adjusting how the results look
