### ISSUE TITLE
Validate FSR payload properties for request being sent to DMC service 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#35719]
## Issue Description
Need to validate the properties of the payload of the request that we're sending to the DMC endpoint to match their documentation. This is being matched against on the FE but should also have the extra layer to be matched against on the BE.

JSON Schema API validation [example](https://github.com/department-of-veterans-affairs/vets-api/blob/6c092f37c2d317479cd82c1741a78bae81f797a7/app/models/saved_claim/education_benefits/va_1990s.rb#L10-12)

---

## Tasks
- [ ] Use schema from vets-json-schema to validate request properties

## Acceptance Criteria
- [ ] Request being sent to DMC endpoint has been validated against JSON defined schema 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
