### ISSUE TITLE
Create a List of Console Customer Type

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#35725]
## Issue Description
As a OTODE I want to see a list of console customer types so that new console can be developed targeting this console personas   

---
## Tasks
- [ ] First meet with Naomi to define scope 
- [ ] Schedule meeting with Naomi and Rachael
- [ ] Facilitate meeting to come up with a list

## Acceptance Criteria
- [ ] Validate list is created and uploaded in the confluence
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
