### ISSUE TITLE
[AWS] Clean up secrets path in SSM Param

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#35738]
## Description

It was noticed there is inconsistency on how secrets are being stored in param store. For example:

Teams have certain permission for read/write in SSM Param store. In some cases `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are accessible to developers which should only pertain to Ops.

An audit most likely need to occur for others that we want only Ops to have.

## Background/context 

It was noticed in a AWS SSM Param Store that users can view certain secrets. For certain secrets, we want Ops to own and only be visible by us.

## Technical notes

- A standardization needs to be set in place moving forward as teams are growing
  - A thought that was discussed in a huddle was `/ops/service_account/service_account_name/secret_to_store`

---
## Tasks
- [ ] Audit SSM Param store and determine which secrets need to be only seen by Ops
- [ ] Migrate audited secrets for Ops only to see (per suggestion or different route)

## Acceptance Criteria 
- [ ] Workflow is not interrupted for teams trying to access secrets

**Comment by jhouse-solvd** [comment]
This relates to #32435
