### ISSUE TITLE
Fix terraform plan github action

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#35732]
## Description
Currently, `global` status is so large and has so many outputs the GHA for Terraform planning breaks due to "argument list too long"

## Technical notes
We could potentially try planning to an output file and then running a terraform show on the file so it would not include the outputs

---
## Tasks
- [x] Fix tf gha for global env

## Acceptance Criteria 
- [x] Tf gha commenting with valid plan on pull requests and not erroring out

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
@jsgarmon did great work on this and I think we can close at this time. Always here to reopen (or we can make a new ticket) if any new issues arise.
