### ISSUE TITLE
[MCP] remove 'Copay balance for' from the copay overview page's facility cards

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35749]
## Issue Description
We received feedback during MCP's staging review that we should remove 'Copay balance for' from the copay overview page's facility cards. [View the feedback ticket here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34172)

**Reasons behind this decision:**
- Headings are no longer links, so they no longer need to include purpose + target in an isolated context
- The h1 and the title (which are announced when user's navigate to the page) both explicitly state this is for copay balances specifically
- Removing "Copay balance for..." accomplishes @jimuhh 's goal of reducing complex sections of content

---
## Tasks
- [ ] Update the copay overview page's facility cards to remove 'Copay balance for'

## Acceptance Criteria
- [ ] The UXPin prototype has been updated and linked in this ticket
- [ ] A frontend ticket has been created and linked in this ticket

**Comment by rileyorr** [comment]
I've updated the designs ([view on UXPin](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142712285/simulate/sitemap?mode=i)) and opened a frontend ticket ([#35745](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/35745))
