### ISSUE TITLE
Fine tune implementation of Vet Center hours display

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35744]
## Issue Description
In #34316, hours of operation were added to Vet Center locations displayed on the Locations page. 

We need to do some stylistic fine-tuning to ensure 
- hours are accurately displayed (see Shreveport for an example)
- padding between days and hours is correct, according to design and comments are easily seen and understood
- Heading levels are correct and do not skip
- All Main Vet Centers, Outstations and Community Access Points with hours available display their hours on the Locations page (This does not include "Nearby Vet Centers")
  - Outstation on [Nashville Vet Center locations page](https://www.va.gov/nashville-vet-center/locations/) does not show hours - this data comes from VAST and should be available the same as the main Vet Center
  - Cape Cod Main Vet Center has hours on Main page but displays the default CAP statement on [Cape Cod Vet Center locations page](https://www.va.gov/cape-cod-vet-center/locations/)
  - Only the first Cape Cod CAP includes hours treatment 

Shreveport preview = preview-prod.vfs.va.gov/preview?nodeID=3857
[Eugene Vet Center Locations page](https://www.va.gov/eugene-vet-center/locations/)

<details>
<summary> Seen on Shreveport Vet Center </summary>
Data:

![image](https://user-images.githubusercontent.com/55411834/150583739-45890958-c258-4035-a8e5-e2058be42ac6.png)

preview page (location is not yet published)

![image](https://user-images.githubusercontent.com/55411834/150583784-ab490670-144c-4aa6-b2d6-ed32ad8417bb.png)
</details>
---

<details>
<summary> Seen on Eugene Vet Center locations page </summary>

![image](https://user-images.githubusercontent.com/55411834/151012261-869c6e4c-cf7f-4606-b001-8fcc1b55452c.png)

</details>
---

<details>
<summary> Seen on Nashville Vet Center </summary>
![image](https://user-images.githubusercontent.com/55411834/151225149-8582f5e1-90a5-4726-b81c-cef0b7d61d56.png)

![image](https://user-images.githubusercontent.com/55411834/151225581-a520ce08-def8-49cc-8546-78f00a8aafb5.png)

</details>

<details>
<summary> Seen on Cape Cod Vet Center </summary>
![image](https://user-images.githubusercontent.com/55411834/151412924-b614bc73-4ee5-41f6-9c61-7df7bede8afb.png)

![image](https://user-images.githubusercontent.com/55411834/151413044-1b0d56a8-5a91-4ee0-88f9-011e4752c62c.png)

![image](https://user-images.githubusercontent.com/55411834/151412995-54e91a2f-41b1-4bc6-a5ea-3cfaad58c751.png)

</details>

---
## Tasks
- [ ] Ensure hours block is aligned according to design
- [ ] Ensure data is rendered correctly for each Main and satellite location
- [ ] Ensure comments are closely aligned with hours and days

**Comment by GcioNapoleon** [comment]
Ticket needed substantially more work than originally expected. We were able to verify that everything is now working correctly.

![Screen Shot 2022-02-11 at 11 36 20 AM](https://user-images.githubusercontent.com/95312667/154727755-558843c6-e7f8-46aa-8dd4-774f08f37399.png)
