### ISSUE TITLE
SIP on Your COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35748]
## Background
Currently if you have a form in progress for COE there is a check on the status page for that form in progress. If you do have a form in progress we don't render anything on the status app due to that check. We need to remove that check as it is not relevant for the status app.

## Tasks
- [ ] Remove the form in progress check
- [ ] Submit a PR for review

## Acceptance Criteria
- [ ] The content on the status app renders when you have a COE form in progress
- [ ] A PR has been requested for merging
