### ISSUE TITLE
[PM] Onboard Angela to Authenticated Experience team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35750]
Angela Agosto is joining the Authenticated Experience team as Designer.  Below are tasks for PM to ensure a smooth transition to the team.
VSA Onboarding ticket #35720

## Tasks
- [x] Send Intro Comms to New Hire
- [x] Conduct Intro Meeting with New Hire
- [x] Add New Hire to Product team meetings
