### ISSUE TITLE
Add all WC to the component library analytics

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35769]
## Description

The [`component-library-analytics-setup.js` file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/component-library-analytics-setup.js) is missing some of the newer web-components, e.g. `va-additional-info` expand event in particular.

## Tasks

- [ ] Add missing WC to setup file
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Also, regarding this comment - https://github.com/department-of-veterans-affairs/va.gov-team/issues/33086#issuecomment-984854366 - do you think we could add a prop to the WC to add more analytics details, something like:

```html
<va-additional-info
  trigger="blah"
  analytics-detail="some analytic detail to include"
>
  ...
</va-additional-info>
```

**Comment by k80bowman** [comment]
Components that need to be added:
- va-accordion
- va-additional-info
- va-alert
- va-breadcrumbs
- va-checkbox-group
- va-loading-indicator
- va-progress-bar
- va-radio
- va-segmented-progress-bar
- va-select
- va-telephone

For more information on how to add these to the analytics setup, see this [documentation](https://vfs.atlassian.net/wiki/spaces/DST/pages/2079817745/Component+development+process#Analytics%5BinlineExtension%5D).

**Comment by caw310** [comment]
Contact @bsmartin-ep  from Analytics teams when you work on this ticket.

**Comment by pdavies88** [comment]
List of All Current Analytics Events:
* va-accordion
**COMPONENT NAME NEEDS TO BE FIXED**
```
      const detail = {
        componentName: 'Accordion',
        action: prevAttr ? 'collapse' : 'expand',
        details: {
          header: headerText || clickedItem.header,
          subheader: clickedItem.subheader,
          level: headerLevel || clickedItem.level,
          sectionHeading: this.sectionHeading,
        },
      };
      this.componentLibraryAnalytics.emit(detail);
```
* va-additional-info
```
      this.componentLibraryAnalytics.emit({
        componentName: 'va-additional-info',
        action: !this.open ? 'expand' : 'collapse',
        details: {
          triggerText: this.trigger,
        },
      });
```
* va-alert
```
        const detail = {
          componentName: 'va-alert',
          action: 'linkClick',
          details: {
            clickLabel: target.innerText,
            headline: headlineText,
            status: this.status,
            backgroundOnly: this.backgroundOnly,
            closeable: this.closeable,
          },
        };
        this.componentLibraryAnalytics.emit(detail);
```
* va-breadcrumbs
```
        const details = {
          componentName: 'va-breadcrumbs',
          action: 'linkClick',
          details: {
            clickLabel: target.innerText.trim(),
            clickLevel: this.getClickLevel(target),
            totalLevels: this.breadcrumbs.length,
          },
        };
        this.componentLibraryAnalytics.emit(details);
```
* va-banner
```
        const detail = {
          componentName: 'va-banner',
          action: 'close',
          details: {
            headline: this.headline,
          },
        };
        this.componentLibraryAnalytics.emit(detail);
```
* va-checkbox
```
    this.componentLibraryAnalytics.emit({
      componentName: 'va-checkbox',
      action: 'change',
      details: {
        label: this.label,
        description,
        required: this.required,
        checked: this.checked
      },
    });
```
* va-checkbox-group
```
    this.componentLibraryAnalytics.emit({
      componentName: 'va-checkbox-group',
      action: 'change',
      details: {
        label: this.label,
        optionLabel,
        required: this.required,
      },
    });
```

**Comment by pdavies88** [comment]
**NOTE**
On vets-website Analytics can be check if they are firing properly by running `monitorEvents(document.body, 'component-library-analytics');` in your browser console

If testing on Storybook this can be done by querying for the IFrame inside of the body

**Comment by bkjohnson** [comment]
In progress PR for `<va-select>`: https://github.com/department-of-veterans-affairs/vets-website/pull/19724

**Comment by pdavies88** [comment]
Support Ticket: https://dsva.slack.com/archives/CBU0KDSB1/p1646057560227489
