### ISSUE TITLE
Add link to medical copay tool on COVID-19 debt relief R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35768]
## Issue Description
Now that the medical copay tool has launched we need to add a link to it from the [VA COVID-19 debt relief options for Veterans and dependents](https://www.va.gov/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents/) in the accordion: How do I get help for a medical care or pharmacy services copayment debt?

We should use the same language that is in the expanded information alert on the [Manage VA debt](https://www.va.gov/manage-va-debt/) page.

## Tasks
- [x] Add text and link to page
- [x] Review and publish

## Acceptance Criteria
- [x] Link and new content is live on the page

**Comment by RLHecht** [comment]
@denisecoveyduc Just letting you know we also added a link to the tool on this resources and support page. We used the same language Danielle wrote up for the manage VA debt page.

**Comment by denisecoveyduc** [comment]
@RLHecht Great! I will share that with Jill (DMC) as well as she is interested in all routes to the page. Thanks for the heads up!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
