### ISSUE TITLE
IA Feedback - Midpoint Review - Authenticated Experience, On-site Notifications

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#35765]
## VFS acceptance criteria

- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions

- I notice that the conversation guide includes:
  - "Do they mention anything about alerts being on top and mixed into sections of the page?"
  - This seems like a very important area of investigation. I've added suggestions for how we might get more IA-specific feedback.

LMK if you have any questions! Thanks!

## Feedback

- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

- Adding a question to prototype eval specifically about distribution of alerts throughout the page. 
  - e.g. *"Talk to me about the way alerts are distributed across different sections. How useful do you think a  user like you would  find this?"*  

- Asking the participant to interpret the different calls to action in top-page alerts, service-level alerts and cards, to see if their mental model for display of tasks and obligations fits what's in the design.
(obv. these are just suggestions; researcher should craft their own wording) 

## Platform directions

- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)
