### ISSUE TITLE
Update Pre-Need eligibility submission URL

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35776]
## Issue Description
Product Owner request: Update Pre-Need eligibility submission URL
Reference this ticket that outlines task: [35771](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/35771)

Currently, Pre-Need submissions are being sent to EOAS at https://eoas.cem.va.gov/eoas_SOA/PreNeedApplicationPort. EOAS is going through a system upgrade, which includes a migration to the AWS cloud.

In preparation for the migration which is currently scheduled for a March production deployment, the team would like to conduct coordinated testing with VA.gov in the lower environments.

The URL of the new EOAS endpoint should be: https://dev.cem.vaec.va.gov/eoas_App/faces/login.xhtml

The EOAS development team would like to interact directly w/the engineer(s) assigned to this ticket, to verify a handshake and conduct testing.
---
## Tasks
- [ ] Coordinate with EAOS development team to implement and test change

## Acceptance Criteria
- [ ] Required update and testing complete.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
@cnemeth Contacts: craig.harris2@va.gov and arul.palani@va.gov

**Comment by vhenry07** [comment]
Closing, still awaiting stakeholder response. Will continue work in a new ticket if needed.
