### ISSUE TITLE
Translation work for COVID-19 testing FAQ question

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35779]
## Issue Description
We updated the COVID-19 testing accordion on our [FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) with new information that we need to get translated in both Spanish and Tagalog. 

It's the Can I be tested for COVID-19 at a VA health care facility? accordion. 

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Selina)
- [x] Update Tagalog page (Selina)
- [x] Review and publish pages (Randi)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] New content is live on translated pages

**Comment by RLHecht** [comment]
@lunascoop We just got back the translations:

[https://app.zenhub.com/files/133843125/af39446a-5f49-4d6f-86a6-1f07cade619f/download](https://app.zenhub.com/files/133843125/af39446a-5f49-4d6f-86a6-1f07cade619f/download)

[https://app.zenhub.com/files/133843125/406479bf-af90-4515-8074-f3f4bd860f74/download](https://app.zenhub.com/files/133843125/406479bf-af90-4515-8074-f3f4bd860f74/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review. I also made a tweak to the English page. My notes are below.

**For the Spanish translations:** There weren't any translations for this link: "Request a primary care test appointment online" They accidentally duplicated the translations for the sentence above the link. I Google translated for now.

**For both the Spanish and Tagalog pages:** This sentence needed to be translated: "You can request an appointment in any of these 3 ways:" We didn't highlight it to show that it needed to be translated.

**For the English page:** Adjusted header sizing before the _More coronavirus-specific concerns_ section

- Coronavirus FAQs: What Veterans need to know: http://preview-prod.vfs.va.gov/preview?nodeId=3014 
- Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos: http://preview-prod.vfs.va.gov/preview?nodeId=14580
- Mga karaniwang katanungan tungkol sa Coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=16475

**Comment by RLHecht** [comment]
I reviewed and published all these pages. I'll send Mateo the live links tomorrow and then move to validate.
