### ISSUE TITLE
NOD: Use list loop pattern for adding new issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35798]
## Description

Currently, the Notice of Disagreement form has in-line adding & editing of issues to-be-added. We need to utilize the new list loop pattern used in the Higher-Level Review form to make it a better user experience.

## Tasks

- [ ] Implement add issue list loop pattern
- [ ] Add tests
- [ ] Update e2e tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
