### ISSUE TITLE
Learn and shadow VFS Research review/approval process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35792]
## Issue Description
In order to support research as a practice area within the Collaboration Cycle and to provide VFS teams with much needed support and guidance as they take on research initiatives with veterans, the UX Researcher on the Governance team, @claytonzook , must become familiar with the roles and responsibilities currently performed by OCTO-DE.

In short, this ticket is not focused on changing the process or making improvements, instead it is focused on ensuring that Clayton is able to perform the same duties that Kevin and Shane currently perform (specifically the acceptance criteria detailed below). 

Goal is to complete this ticket by mid-February.

---
## Tasks
- [x] Shadow Shane for research plan review
- [x] Submit a research plan feedback for Shane to review
- [x] Begin posting research plan feedback as a secondary reviewer
- [x] Train with Shane on initiating Perigean recruitment
- [x] Get credentials for Perigean 
- [x] Shane:Clayton discuss research review escalation process
- [x] Shane:Clayton discuss how to share duties on Perigean kickoff 

## Acceptance Criteria
- [x] Clayton knows how and is able to review research plans and conversation guides for VFS teams
- [x] Clayton knows how to request changes to the research plan and/or conversation guide with the VFS team (aka providing feedback)
- [x] Clayton knows when and how to escalate concerns with OCTO-DE related to the research plan and/or conversation guide
- [x] Clayton is able to grant approval of a research plan and/or conversation guide
- [x] Clayton is able to kickoff participant recruitment
- [x] Clayton has the full trust of Shane and Kevin
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@claytonzook FYI. I'll be reviewing this with Naomi today and we'll make updates together. I would also like to share with Shane and Kevin to make sure they're on board with the acceptance criteria. If you have specifics you'd like to add, please feel free!

**Comment by shiragoodman** [comment]
@claytonzook Naomi and I reviewed today and made a couple minor changes. Could you please look over and let me know if you approve? Next step will be to send to Shane and Kevin.

**Comment by claytonzook** [comment]
@shiragoodman This makes sense to me. I have nothing to change or add

**Comment by sstrassberg** [comment]
@shiragoodman I second @claytonzook. This is good to go!

**Comment by claytonzook** [comment]
I've added some of the tasks I've been working on that relate to this ticket. Even though I haven't been marking off any AC in a while, this ticket has still been moving forward.

**Comment by claytonzook** [comment]
@shiragoodman @chaseakirby Now that Shane and I have discussed plans around escalation and shared duties for reviews/kickoff, it seems reasonable to write up that guidance - I'm not sure where, maybe in the [Research Plan Review guidance?](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2068119555/Research+Plan+Review)
Unless drafting the above is a new task on this ticket, I'm currently considering the items I can do on this ticket complete. The last AC is not one I feel like I should or can check off myself.

**Comment by chaseakirby** [comment]
@claytonzook I agree that sounds like great guidance to write up. And I think it would make sense to be in the Research Plan Review guidance under a new child page titled something like "Shared Responsibilities and Escalation Procedures".
I think that it would make sense to make this the final task on this ticket as a capstone of sorts for the initiative.
I also agree that the last AC should be the result of the meeting that is going to be (or already has) been scheduled.
