### ISSUE TITLE
Fix SSO unit tests

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#35790]
## Issue Description
Because some SSO Unit tests are failing a decision was made to skip them in the CI/CD pipeline.  This ticket is to track the work to get the flaky unit tests working so we do not have to skip them in Ci/CD.

---
## Tasks
- [ ] Update the flaky sso unit tests `sso.unit.js`

## Acceptance Criteria
- [ ] The SSO unit tests pass
- [ ] SSO unit tests are ran successfully in CI/CD
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
