### ISSUE TITLE
Add Sentry to FSR

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35797]
## Issue Description
There is a need to add Sentry to all FSR endpoint calls by including additional information about the error to improve troubleshooting failed API calls. Refer to the example below which should include `Sentry.withScope` with properties similar to how errors are being [handled with MCP](https://github.com/department-of-veterans-affairs/vets-website/blob/b902a644bd713636536038c9f43599b2b53609b0/src/applications/medical-copays/actions/index.js#L21)

example:
```

import * as Sentry from '@sentry/browser';

Sentry.withScope(scope => {
Sentry.captureMessage(`in_progress_forms/5655 failed: ${error.detail}`);
scope.setExtra('prefix', trackingPrefix);
scope.setExtra('inProgressFormId', inProgressFormId);
scope.setExtra('error', error);
}); 

```

---
## Tasks
- [ ] The following API calls (possibly more) should have Sentry with scope added:
1. [fetchFormStatus](https://github.com/department-of-veterans-affairs/vets-website/blob/651190fbf40038a4ce85d8e152bfdcce7f16e615/src/applications/financial-status-report/actions/index.js#L43)
2. [fetchDebts](https://github.com/department-of-veterans-affairs/vets-website/blob/651190fbf40038a4ce85d8e152bfdcce7f16e615/src/applications/financial-status-report/actions/index.js#L90)
3. [downloadPDF](https://github.com/department-of-veterans-affairs/vets-website/blob/651190fbf40038a4ce85d8e152bfdcce7f16e615/src/applications/financial-status-report/actions/index.js#L113)

## Acceptance Criteria
- [ ] Failed API calls should include more information about FSR errors which should help with troubleshooting
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
