### ISSUE TITLE
Fix GIBCT Deployments

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#35791]
## Description
GIBCT team has noticed a revert that happens to the production database routinely.

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1642518257443400
https://dsva.slack.com/archives/CBU0KDSB1/p1642703108065800
https://dsva.slack.com/archives/CBU0KDSB1/p1641997771298900
https://dsva.slack.com/archives/CBU0KDSB1/p1641315526276900

Another great summary on the issue(s) observed:

```
The only reason the refresh was pushing old code to prod and other environments is that there were no tags being created in the gibct-data-service repository.
The flow that was causing this to happen is the following
someone would push the new code manually from the deploy job in jenkins from the latest ref on master
then the refresh job would go in and deploy the latest tag on that repo, which before we went in to look at it was pointing to this ref 133671823773080e4806ce95d23669c902aac056
I think the refresh job was put in place initially so that there wouldn’t be long lived instances if the code base was not touched for long periods of time.  So the refresh job would go in and rebuild the instance ami with the latest os packages etc but still grab the latest tag.
Regardless with the changes made, it will follow the same flow as the other daily deploys so a new tag will be created daily in the event that new code is committed to master.  So even with the refresh job still enabled this should prevent any stale code from ever being deployed
```

---
## Tasks
- [x] Fix broken deployments

## Acceptance Criteria 
- [x] GIBCT deployed in regular cadence without reverting the database

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Changes made that will be reflected in future deployments:

- dev/staging deployments will still happen on merge to master branch in accordance with the repo's existing Jenkinsfile: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/Jenkinsfile (remaining unaffected by our changes)
- production deploys will now happen on a daily cadence in the same manner that vets-api currently does
    - cutoff for code changes at 2pm eastern, 60 minute hold time in case daily deploy needs to be cancelled, actual production deploy at 3pm eastern (monday - friday)
- corrected release naming convention from old name of `gi-bill-data-service` to `gibct-data-service` because in our troubleshooting it was observed that Jenkins relied on these to be the same and match the actual name of the repository
