### ISSUE TITLE
NOD: Use list loop pattern for contact info page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#35796]
## Description

Currently, the Notice of Disagreement form has in-line editing of profile contact info in place. We want to switch this to the new list loop pattern used by the Higher-Level Review form

## Tasks

- [ ] Implement contact info list loop pattern
- [ ] Add tests
- [ ] Update e2e tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
