### ISSUE TITLE
Update breadcrumbs component documentation on design.va.gov

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#35805]
## Issue Description
Our documentation on design.va.gov for Breadcrumbs component needs to be updated to point to the new `va-breadcrumbs` web component Storybook story and remove the mobile story.

---
## Tasks
- [ ] Update desktop story to point to `va-breadcrumbs` story
- [ ] Remove mobile story

## Acceptance Criteria
- [ ] Update Breadcrumbs component documentation on design.va.gov to point to va-breadcrumbs story and remove mobile story
---

**Comment by k80bowman** [comment]
Closed as duplicate of #35806
