### ISSUE TITLE
Update breadcrumbs component documentation on design.va.gov

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#35806]
## Issue Description
Our documentation on design.va.gov for Breadcrumbs component needs to be updated to point to the new `va-breadcrumbs` web component Storybook story and remove the mobile story.

---
## Tasks
- [x] Update desktop story to point to `va-breadcrumbs` story
- [x] Remove mobile story

## Acceptance Criteria
- [x] Update Breadcrumbs component documentation on design.va.gov to point to va-breadcrumbs story and remove mobile story
---

**Comment by andresriveratoro** [comment]
It seems we have another ticket about updating the mobile story, but this current ticket is about removing it.
@k80bowman @caw310 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/40186

**Comment by humancompanion-usds** [comment]
Yeah, I'm not sure why we're removing this. Is the thought that folks just have to resize to see how it behaves rather than being able to see that explicitly depicted? If so, I'm okay with that, just want to understand.

**Comment by k80bowman** [comment]
The React Breadcrumbs component has a mobile-first prop that displays the breadcrumbs differently. The va-breadcrumbs web component is built to be responsive, so there is no need for a mobile-first prop. So, yes, the thought is that, since a separate prop is no longer needed for mobile-friendly display, folks can resize to see how the component behaves.
