### ISSUE TITLE
[BUG] VA Facilities Alert Banner not dismissible on Homepage 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35816]
### High-level user story
As a Veteran using VA.gov I need to be able to click on the dismissible tab in order to close out alerts and messages from the VA that have already been read and acknowledged. 

### Background
The following issue was identified when visiting VA.gov, as the primary VA Facilities Alert banner is not dismissible as intended.  The modal is not working on both `Staging` and `Prod` environments.  

![Screen Shot 2022-01-24 at 10 34 50 AM](https://user-images.githubusercontent.com/70410912/150834789-b15ed639-435d-4d3d-8424-1dec0ff2ceed.png)

### Next Steps 
- We need to fix the dismissible modal to ensure it can be dismissed by visitors coming to VA.gov

### Tasks
- [ ] Fix alert banner to ensure it's dismissible as intended 
- [ ] Test locally and validate fix is working in staging before push to production
- [ ] Once validated in staging deploy to Prod  
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Dismissible functionality is restored to alert banner, validate analytics tracking is still maintained as a result. 
- [ ] Alert banner is able to be dismissed as intended

**Comment by srsuddath** [comment]
This ticket will likely be closed by this ticket:
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/35822

**Comment by brianalloyd** [comment]
Related ticket is closed, validated and closing this tracking ticket.
