### ISSUE TITLE
[Combined Debt Portal] Wireflows

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35820]
## Issue Description
Veterans expect to find all money they owe to VA in one location on the site. Additionally, Congress has mandated that we provide a way for Veterans to access all their debts in one spot. As a result, we need to create wireflows of the combined VBA + VHA debt portal. 

---
## Tasks
- [x] Create wireflows of the combined VHA + VBA debt portal 

## Acceptance Criteria
- [ ] The designs have been presented to the team 
- [x] An IA ticket has been opened and linked in this ticket

**Comment by rileyorr** [comment]
Update on this work: 
- Played around with a potential flow for how we can keep the existing 'Pay your VA copay bill' pages that live within the Health Care hub while moving MCP into the debt portal ([UXPin](https://preview.uxpin.com/32e8ac818076b3dc502846e0b13356fa40779575?_gl=1*15ys2up*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/147178588/simulate/no-panels?mode=i))
   - Unsure how feasible this is with the site's IA, but I figured it's a good place to start as we collaborate with Mikki. I opened a sitewide content + IA request ticket so we can meet soon ([#36306](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/36306))
- Created a small flow diagram of a new 'VA debt overview' page that lets Veterans see the debts/bills they have with VA at a higher level and provides a way to drill into the specific debts ([UXPin](https://preview.uxpin.com/32e8ac818076b3dc502846e0b13356fa40779575?_gl=1*15ys2up*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/147412544/simulate/sitemap?mode=i))
- Added higher fidelity pages as talking points for meeting with IA 
- Presented this work to Denise

**Comment by rileyorr** [comment]
Added a couple more concepts and created a [combined wireflow artboard](https://preview.uxpin.com/32e8ac818076b3dc502846e0b13356fa40779575#/pages/147589342/simulate/sitemap?mode=i) for when we meet with Mikki! 

@denisecoveyduc are we going to set up a different product folder in GH for the combined portal?

**Comment by denisecoveyduc** [comment]
@rileyorr Short answer is yes.. I will ping you and we can discuss.

**Comment by denisecoveyduc** [comment]
For tracking purposes.. dropping a link to our new folder here. **[combined_va_debt_portal](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_va_debt_portal)**
