### ISSUE TITLE
[UNPLANNED] 'Logs4Days' postmortem

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#35835]
## Background
This ticket is intended to track the draft of the post mortem around the logging issue earlier in January.

## Considerations 
https://dsva.slack.com/archives/C02Q9FL124F/p1642775998003500

## Tasks
 - [x] Draft notes of the incidence(s)
 - [x] Collaborate with other team members (both internal and external) to ensure issue and solution are codified.

## Acceptance Criteria
- [x] Contributions made to the larger post-mortem
