### ISSUE TITLE
[Platform Console API] Onboarding to Kubernetes (EKS)

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#35833]
## Description of your application
_Name_: [Platform console](https://github.com/department-of-veterans-affairs/platform-console)
_Functionality_: The Platform Console: for creating and deploying applications on the VA Platform.
_Language/Stack_: Ruby on Rails
_Ports/Networking needed_:
_Other infrastructure needed e.g. Database, redis, etc_: RDS, Elasticache and an [ECR repo](https://github.com/department-of-veterans-affairs/devops/pull/10611)
_Anything else we need to know?_:

## Background/Context/Resources
[Platform Console Repo](https://github.com/department-of-veterans-affairs/platform-console)
[Provision RDS Instance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35353)
[Provision Elasticache Instance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35354)
[Create Platform Console ECR Repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35355)

## Technical Notes
_Any addition technical notes that can be provided_

## Checklist of Items needed for onboarding (Responsible parties in parentheses)
- [x] Your application! (Your team)
    Your application should conform to the 12 factor app methodology (https://12factor.net/)
- [x] A Github Repository for your application (Operations or your team)
- [x] A Dockerfile for your application (Your team, Operations can assist if needed)
- [x] DONE! PR CREATED! [Elastic Container Registry Repository for your application](https://github.com/department-of-veterans-affairs/devops/pull/10611) (Operations, PRs are welcome: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)
- [x] Automation to "Release" and "Tag" the application Github Repository with a semantic version number. (Your team, Operations can assist if needed)
- [x] Automation to push the built Docker container to the ECR Repository and tag it with the semantic version number. (Your team, Operations can assist if needed)
    Please do not use 'latest' tags
- [x] Kubernetes Application Manifest in YAML, jsonnet, or Helm Chart (Operations and your team)
    YAML and jsonnet are highly preferred, Helm charts are discouraged
- [x] Automation to update the Kubernetes Application Manifest when a new version of your application container is pushed to ECR (Operations and your team)
- [ ] AWS Service account for your team or application (Operations)
- [ ] Path/s in AWS SSM Parameter Store created for your team or application (Operations)
- [ ] AWS IAM Permissions applied to your team members to allow read/write access to AWS SSM Parameter Store path/s for your application/team (Operations)
- [ ] AWS IAM Permissions applied to the service account to allow read access to AWS SSM Parameter Store path/s for your application/team (Operations)
- [x] Secrets and Parameters needed for your application stored in AWS Systems Manager Parameter Store (Your team)

**Comment by LindseySaari** [comment]
I can help to work on the GHA and the K8s manifest pieces!

**Comment by jhouse-solvd** [comment]
@LindseySaari @ericboehs @npeterson54 

_With respect to naming conventions:_ 
The Console Services team is planning to develop and deploy the **"platform console API"**. Is that correct? 

There's a simultaneous effort to develop and deploy a **"platform console UI"** (see #35784) which sounds like a separate frontend app (looks like maybe backstage)? Does that mesh with your understanding as well? 

Also, as a bonus Q: **How does this relate to** #36033 and the goal to spin up a "hello world" app for the IET team?

**Comment by jhouse-solvd** [comment]
@LindseySaari - I noticed that this issue was closed. Does that mean that your team has everything it needs to get the platform console API up and running in Kubernetes? 

Thank you for the info.

**Comment by jhouse-solvd** [comment]
Hi @LindseySaari - I saw the comment from Jeremy Britt on Slack [here](https://dsva.slack.com/archives/CTYQL39FE/p1644248605774289)

Please disregard my previous note. ☺️
