### ISSUE TITLE
FE implementation for health service design iteration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35845]
## Issue Description 
VA health and non-clinical services may be offered at more than one location for a given health system. Editors can indicate if the main address should appear or a specified address should be used. We needed a way to account for the combinations of locations which could be present in a given service and make each visually distinct and understandable for Veterans. The design iteration was done in #34635. 

**Scenarios to consider**

- Service is offered at a single location which uses the facility address (displaying only a wing/room/suite)
- Service is offered at a single location which does not use the facility address (displaying a full address, including - possibly- another city)
- Service is offered at multiple locations, each of which may or may not use the facility address

<details>
<summary> Problems to solve </summary> 

- Service locations (for both health services and non-clinical services) render in interesting ways when no name is provided, particularly when multiple service locations exist at a single facility.
- Multiple services locations are not visually separated, making information such as hours appear to be a continuation of a previous location (probably also causing accessibility issues for those using assistive tech)
- In some cases, the editor may not specify wing/floor/room info which results in no address display.
- The absence of a name heading impacts heading hierarchy
</details>

<details>
<summary> Drupal editorial experience </summary>

![image](https://user-images.githubusercontent.com/55411834/148834008-0f4a8a30-4f4c-4df0-bab5-526133f07405.png)

![image](https://user-images.githubusercontent.com/55411834/148834080-f928fffa-ceab-4664-abac-9a465a0f0b4b.png)

![image](https://user-images.githubusercontent.com/55411834/148834223-0c273431-52d3-4f49-900c-dd26b35a09cc.png)

</details>

---
## Tasks
Ensure the expected behavior occurs, consistent with [Nick's UX Pin](https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/146478035/documentation/no-panels?mode=i)

When a service is offered at a single location, the heading hierarchy follows the following pattern for each service accordion
- [ ] H3 is used for main content sections, including:
       - Contact information
       -  Care we provide at VA [system name] health care
- [ ] H4 is used for facility names
       - example: Beaver County VA Clinic [name]
- [ ]  H5 is used for facility sub-headings, including:
       - Appointments
       - Hours
       - Phone
- [ ]  Any labels appearing under H5 headings use bold text
---

- [ ] When "use the facility's street address" is checked in Drupal:, the name of the facility should be included at top of address block. 
       -  if the name and/or sub-location address is left empty, the heading defaults to the main location name and the address defaults to the main location address

---

- [ ] When "use the facility's street address" is not checked in Drupal, location name should appear at top of address block (See "Alley Medical" example in issue). 
       - If name is not specified, display "Service location" as default name and maintain heading hierarchy 
---

When more than one location appears in a service accordion
- [ ] add "This service is offered at multiple locations" under the contact information header
- [ ] Accessibility: screen readers should read "this service is offered at multiple locations" in appropriate tab order along with other readable elements

 ## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by mmiddaugh** [comment]
If anything, this effort should start over with [[DISCOVERY] for multiple VAMC health service locations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36934)
