### ISSUE TITLE
[Combined debt portal] Usability study research plan

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35844]
## Issue Description
Veterans expect to find all money they owe to VA in one location on the site. Additionally, Congress has mandated that we provide a way for Veterans to access all their debts in one spot.

We need to validate the combined VBA + VHA debt portal design with Veterans to ensure it meets our users' needs.

---
## Tasks
- [ ] Draft the usability study research plan

## Acceptance Criteria
- [ ] The research plan has been linked to this ticket 
- [ ] This document along with the conversation guide is sent out for review

**Comment by rileyorr** [comment]
I've added the research plan's draft to GH ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-plan.md))
