### ISSUE TITLE
[Combined Debt Portal] Usability sessions

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35850]
## Issue Description
Veterans expect to find all money they owe to VA in one location on the site. Additionally, Congress has mandated that we provide a way for Veterans to access all their debts in one spot.

We need to validate the combined VBA + VHA debt portal design with Veterans to ensure it meets our users' needs.

---
## Tasks
- [x] Conduct the usability sessions

## Acceptance Criteria
- [x] Sessions are complete 
- [x] The usability study's notes document is linked in this ticket 
- [x] The topline summary is linked in this ticket and shared out to the team

**Comment by mgleo** [comment]
[Observer notes spreadsheet](https://docs.google.com/spreadsheets/d/1gK6ICNRwK7usi-kfnrr4arZKQls5RPQQty7wHREteUQ/edit?usp=sharing)

[Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/topline-summary.md)
