### ISSUE TITLE
[VAMC] Menu Maintenance to move all Level 5 & 6 Menu items to Level 4 (work with VHA DM on Comm) [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#35869]
## STORY
As a Veteran I need all web pages to be easily searchable on the left Nav, so I do not have to click through more than four depths to find the page I need.

## RESOURCES
TBD

## TASKS
- [x] Review and document all menu items that exceed 5 to 6 levels on the menu
- [x] Document the corresponding bread crumb path (URL) and the proposed new URL that needs to be used when moved.
- [x] Work with PM to send out communications that Depths will be changing.
- [ ] Work with IA to submit redirect URLs
- [ ] Once redirects are in place move all of the menu items to correct 4 th level.

## ACCEPTANCE CRITERIA
- [x] Document is created so Redirects can be submitted (Separate Issue)

-
