### ISSUE TITLE
[MCP] HTML Statement - Statement Address

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35877]
## Issue Description

Add **Statement address** section to the  HTML statement page. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i) for details

![MCP Desktop - UXPin Preview 2022-01-25 10-01-54.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/fd24cf00-c23a-4130-b323-48998792caa4)

---
## Tasks
- [ ] Add Statement address section to the HTML statement page

## Acceptance Criteria
- [ ] Statement address section should render
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
