### ISSUE TITLE
[Design] Create Pre-check-in User Flow Documentation

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35879]
# Description
We have a user flow document for [check-in](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm). However, we do not have this documentation for pre-check-in. We need to create a user flow document within Sketch for Pre-check-in. Scope: pre-check-in with editing.

# Tasks
- [x] Create a User Flow Document within our [Pre-check-in Sketch file](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e)
- [x] Update the [text/error message source of truth documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md)

# Acceptance Criteria
- [x] Review with internal team (product, UX, and engineering)
- [x] Add link to this user flow in the editing [design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md)
- [x] Share Sketch and GitHib [source of truth]https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) with larger check-in team via Slack
- [x] Also create a flow for 'Read-Only' user flow

**Comment by kristenmcconnell** [comment]
Needs to be a word document for the call center.

**Comment by kristenmcconnell** [comment]
[Day of check-in user flow diagram](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) to use as a guide for this documentation

**Comment by zach-park** [comment]
@jparker0425 @kristenmcconnell The user flow for both Editing and Read-only are complete. The sketch links are attached to the Design Doc on GitHub.
