### ISSUE TITLE
Console UI Prototype

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#35870]
**Console UI Prototype**
Platform Console: In Q1 2022, we are attempting to launch an MVP version of the Console that will enable certain FE VFS developers to log in and manage their FE deployments. 

### SEE TICKETS IN THIS EPIC FOR CURRENT STATUS

[**MVP:**
](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2042232849/Requirements+Gathering+MoSCoW+for+MVP+-+Console+UI)
- ATO, TRM, Authentication, Authorization
- Ability to log in (initial UI by CONSOLE UI , functionality and complete UI by ACCESS MANAGEMENT)
- **Deployment mgmt feature RELEASE TOOLS TEAM**
- **Enabled to add a feature via conversation with Console UI engineers RELEASE TOOLS & CONSOLE UI**
- Have the ability to add a feature through  x method (shown in a service blueprint)
- Have documentation on the Console CONSOLE UI? 
- **Have documentation on deployment mgmt feature RELEASE TOOLS TEAM**

**General approach**

- [x] GHA API discovery (GH API?)
- [x] Spec out prototype to show commits and end points
- [x] Take what's in FE dashboard, filter by team, and visualize read only when/why something fails
- [x] Prototype should be VERY flexible; there will be multiple iterations (no API yet)

**Previously completed in this epic (see tickets in this epic for additional work)**
- [x] Show app-level lighthouse/frontend performance information ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.4yrcj890r3nz))
- [x] Show recent commits by team ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.h020g6odi5b0))
- [x] Show recent GHA runs by team ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.8ax45tktvf0e))
- [x] Get workflow status ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.7h6qh2wimqr2))
- [x] Manually trigger a workflow ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.hwy3rcbtf3j0))
- [x] Re-run a workflow ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.egmstkon6jgi))
- [x] Get logs for a workflow ([details](https://docs.google.com/document/d/1c6trSUJL8M5xzSkMi4P3r7g-pu7sFLh14syVAi_UzIk/edit#heading=h.s8je1r6aek8j))
- [x] Integrate with Backstage

**Questions**
- Does GH allow us to pass username and return emails they are attached to? Would this give us a list of commits?
- Design for the interface? After we understand the info we can get, THEN we will get a UX person involved.

**Notes**
- react app
- Utilize resources from GHA (deployment status in FE dashboard; code owner teams; recent commits; fails)
- not yet triggering any actions; strictly read-only
- think microservice (but in the future)
- prioritized [VFS tasks](https://vfs.atlassian.net/wiki/spaces/AP/pages/2036301898/VFS+Tasks)

**Comment by alexandec** [comment]
Additional tickets:

- [#36407](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/36407) Create prototype Release Tools console UI React app
- [#36517](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/36517) Add GitHub API request to Console UI app

**Comment by laineymajor** [comment]
@alexandec should we close this? what do you think?

**Comment by alexandec** [comment]
@laineymajor sure, I'll close it. We've have a working plugin with more features than what we originally specified. We can reference [#42817](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/42817) for future work.
