### ISSUE TITLE
[MCP] HTML Statement - Statement Charges Table

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35875]
## Issue Description

Add **Statement charges** table component to the  HTML statement page. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i) for details

![MCP Desktop - UXPin Preview 2022-01-25 09-58-37.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/ae06800f-66bb-4572-a6f9-dcaabf2fbe73)

---
## Tasks
- [ ] Create statement charges table using the design system [`<Table />`](https://design.va.gov/components/tables) component
- [ ] Add download your statement links below the table

## Acceptance Criteria
- [ ] Statement charges table should render on the HTML statement page
- [ ] Download your statement links should render below the table

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
