### ISSUE TITLE
[MCP] HTML Statement - On This Page Component

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35873]
## Issue Description
Add **On this page** component to the  HTML statement page. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i) for details

![MCP Desktop - UXPin Preview 2022-01-25 09-41-05(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/98a882af-a00d-4a03-91d6-f8e13a6a96c3)

---
## Tasks
- [ ] Add [va-on-this-page](https://design.va.gov/components/on-this-page-jump-links) component to the  HTML statement page

## Acceptance Criteria
- [ ] The [va-on-this-page](https://design.va.gov/components/on-this-page-jump-links) component should render on the  HTML statement page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
