### ISSUE TITLE
[MCP] HTML Statement - Balance Questions

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35878]
## Issue Description

Add **What if I have questions about my statement?** section to the  HTML statement page. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i) for details

![MCP Desktop - UXPin Preview 2022-01-25 10-03-53.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/a4510b99-b62f-4770-88bc-3ddec2ed3f96)

---
## Tasks
- [ ] Add **What if I have questions about my statement?** section to the  HTML statement page. 

## Acceptance Criteria
- [ ] **What if I have questions about my statement?** section should render on the  HTML statement page. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
