### ISSUE TITLE
[MCP] HTML Statement - Account Summary

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35874]
## Issue Description

Add **Account summary** section to the  HTML statement page. Refer to the [mock](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/144326848/simulate/sitemap?mode=i) for details

![MCP Desktop - UXPin Preview 2022-01-25 09-52-54(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/85fd4a58-c779-44f4-81ca-7854ba123fc6)

---
## Tasks
- [ ] Create Account summary section

## Acceptance Criteria
- [ ] Account summary should render balance activity

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
