### ISSUE TITLE
[Research] Meet with San Diego Staff for Appointment Notifications Study

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35888]
# Description
Meet with San Diego staff to complete the appointment notification service blueprint. Use [VAOS's conversation guide](https://docs.google.com/document/d/1DWE2QdxR_WW-GapCdYJpkbB8SoxVlOimYmgC-FDgY2Q/edit#heading=h.8scnnixlz5v1) and [research plan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/appointments/research/2021-10%20Notifications%20service%20map%20workshop/research-plan.md#hypothesis).

[VAOS's old service blueprint research plan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/appointments/research/2021-10%20Notifications%20service%20map%20workshop).

# Tasks
- [x] Meet with staff
- [x] Collect all sessions notes, clean up the notes, and post the notes to GitHub

# Acceptance Criteria
- [x] Meet with staff complete and feedback gathered
- [x] Session notes posted to GitHub

**Comment by kristenmcconnell** [comment]
VAOS will be posting the [Google doc notes](https://docs.google.com/document/d/1C0FPlUG_WxjKvk7xSNALepdQzGJMwfl87b2YZkWzVsc/edit?usp=sharing) to GitHub, so I'm going to close this.
