### ISSUE TITLE
[Research] St. Louis Pilot Veteran & Staff Research Synthesis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35886]
## User Story
- As a product team, we want to know the findings from Veteran's & Staff feedback on the pilot at St. Louis.

## Assumptions
Does not include making a report

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Veteran Research plan and Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback)
- [Staff Research plan and Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback)

## Description
Analyzing the notes from the site visit to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.) Are we also writing two different reports (Veteran and staff) or combining them into one report?
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all notes
- [x] Do analysis

## Acceptance Criteria
- [x] Post synthesis documents to GitHUB
- [x] Post session notes to GitHub

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback
