### ISSUE TITLE
[Research] Met with St. Louis Staff to Gather Their Feedback on the Pilot

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35883]
# Description
We are looking to get feedback on the pilot release from staff, so we created a [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback). Now, we need to actually meet with staff to gather their feedback.

# Tasks
- [ ] Coordinate with product on when UX can take over an office hour session to run our conversation guide.
- [ ] Coordinate which UXer will moderate and who the notetaker will be. 
- [ ] Meet with staff
- [ ] Collect all sessions notes, clean up the notes, and post the notes to GitHub

# Acceptance Criteria
- [ ] Meet with staff complete and feedback gathered
- [ ] Session notes posted to GitHub

**Comment by kristenmcconnell** [comment]
We accidentally created a new ticket on this same thing, #37593.
