### ISSUE TITLE
[FSR] list loop edit view styling issue

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35887]
## Issue Description
There appears to be some kind of padding issue with the edit view on the list loop component and should be updated. Styling also seems to be affected for available-debts refer to mock [here](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021788/simulate/sitemap?mode=i)

List Loop
![Financial Status Report  Veterans Affairs 2022-01-25 10-59-55(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/d2ae9fca-8dae-43b1-8283-ccfa3a884698)

Available Debts
![Financial Status Report  Veterans Affairs 2022-01-26 10-41-59.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/b6fde058-1bb3-4553-ac1e-9cb9a5320db6)

---
## Tasks
- [ ] Verify this isn't a platform issue and add the proper padding if necessary to the list loop component edit view

## Acceptance Criteria
- [ ] Edit view should render the proper padding according to UI and design specifications
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
