### ISSUE TITLE
[Research] Coordinate Veteran Pilot Feedback/Train MSAs

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35885]
# Description
We want to get feedback from Veterans at the St. Louis pilot, so we created this [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/Martinsburg-Staff-Moderated). We will be using staff members (MSAs) to help us gather this feedback. Therefore, we need to train the MSAs on what we want to gather and send them the assets (Optimal Sort link and Interactive PDF) to effectively collect said feedback.

# Tasks
- [ ] Meet with MSAs to review expectations on gathering feedback, then answer any questions.
- [ ] Send the MSAs the final survey link and PDF

# Acceptance Criteria
- [ ] MSAs at pilot clinics are ready to go and collect feedback
