### ISSUE TITLE
Update how to apply links on VGLI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#35882]
## Issue Description
Stakeholder Steve Fital asked us to change the how to apply links on the [VGLI life insurance page](https://www.va.gov/life-insurance/options-eligibility/vgli/).

1. For the **Apply online through OSGLI** the link should change to this url: 

https://ssologin.prudential.com/app/giosgli/Login.fcc?TYPE=33554433&REALMOID=06-0004c6f9-19f6-1e08-a6d4-051430fc0000&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=giosglirba&TARGET=-SM-HTTPS%3a%2f%2fgiosgli.prudential.com%2fosgli%2fController%2flogin%3faction%3dreturn

2. We should also remove the link to **apply online through eBenefits**

## Tasks
- [x] Update links (Selina)
- [x] Review and publish (Randi)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Updates to page are live

**Comment by RLHecht** [comment]
Thanks @lunascoop I confirmed with Jason that it was OK to remove that ebenefits link and I published the page. Will let the stakheolder know once the page is live.

**Comment by RLHecht** [comment]
Notified Steve that page is live with changes. Moving to validate.
