### ISSUE TITLE
[Design] Update Text/Error Message Source of Truth

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#35880]
# Description
After #35840 is complete, update the text/error message source of truth documentation to include the va.gov error states. The source of truth only includes CHIP messaging right now.

# Tasks
- [x] Review the user flow document after #35840 is complete.
- [x] Update whatever is determined to be the source of truth

# Acceptance Criteria
- [x] Share the update source of truth via Slack with the larger check-in team, so it can be shared with staff

**Comment by kristenmcconnell** [comment]
[Sketch file](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) has been updated based upon discusses with va.gov engineering, CHIP, and VeText.

**Comment by kristenmcconnell** [comment]
The GItHub source of truth page has been updated to reflect the most up-to-date error messaging for va.gov, CHIP, and VeText. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md

**Comment by kristenmcconnell** [comment]
[Shared this updated documentation on Slack.](https://dsva.slack.com/archives/C022AC2STBM/p1643901413673009)

**Comment by kristenmcconnell** [comment]
The staff documentation will be a product guide word document. It will actually be created in #36343.
