### ISSUE TITLE
Feature Flag for Columbus (FAC ID 757) for Cerner Launch

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35889]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)
Timeline for launch: Plan to test closer to launch date in staging.
Go live stuff: April 29 cutover for April 30th Go-Live

- Facility ID's: 
Columbus (a.k.a. Central Ohio health care) facilities
Zanesville VA Clinic - vha_757GA
Daniel L. Kinnard VA Clinic - vha_757GD
Marion VA Clinic - vha_757GC
Grove City VA Clinic - vha_757GB
Chalmers P. Wylie Veterans Outpatient Clinic - vha_757
Columbus VA Clinic - vha_757QC
Columbus 1 VA Mobile Clinic (archived node) - vha_757QA
North James Road 2 VA Mobile Clinic (archived node) - vha_757Q

### Considerations
- We'll need to create a feature flag to support testing in staging based on recent discussion with VA testing team  
- This will need deploy to staging initially in order to be tested by the facility and our team

### Tasks
- [ ] Create a feature flag for Columbus facility so testing team can test in staging 
- [ ] Test locally and setup a staging test environment so Facility admins can test.
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Columbus has a feature flag to support staging testing 
- [ ] Validate with Tony that the Testing team is able to test in staging

**Comment by srsuddath** [comment]
this ticket will be closed by this PR
https://github.com/department-of-veterans-affairs/vets-website/pull/20157
