### ISSUE TITLE
Auth Profile [Determine Accessibility Preference for Conditional or Non-Conditional Reveal]

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#35897]
## Background
After receiving guidance for accessibility best practices, our team has been working on a design for a text input box non-conditional reveal when connected to a radio button or checkbox. This solution was created through a discussion with the Design system team and presented at Design Council Meeting, where we learned that other teams received guidance that conditional reveal is ok for accessibility. This issue is to determine the preferred approach: conditional or non-conditional reveal.

[Resource from gov.uk](https://accessibility.blog.gov.uk/2021/09/21/an-update-on-the-accessibility-of-conditionally-revealed-questions/)

## Tasks
- [x] Facilitate a meeting with Rob Garrison and Angela Fowler so Rob can demo their component and Angela can try it out in Staging to determine if it is accessible
- [x] Determine preferred method for accessibility best practices
- [ ] Document and share results

## Acceptance Criteria
- [ ] Completed meeting with Rob and Angela
- [ ] Determined preferred method for accessibility best practices
- [ ] Documented and shared results

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Adding an update here so we can close this now that we have the new tickets for this and next sprint! The larger issue of conditional reveal or not can now go to the accessibility specialists to discuss together.

Marci and I met with Angela Fowler, Josh Kim, Kevin Hoffman, and Robin Garrison to discuss accessibility questions around the text input box. Here is Marci's quick summary from our meeting: 

> ...believe that another approach may remove some of the issues discussed to date. This approach would display the text field with its own separate label (e.g., "Provide a pronoun not listed above") below the list of checkboxes rather than having it connected to an "other" checkbox in the list. The text field would always be displayed, which would eliminate the show/reveal concern.

A new ticket has been created to complete these updates #36352
