### ISSUE TITLE
[Design Review] Design Refactoring for Outreach & Events Hub (Plain Text Search UX)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35895]
#### Discovery phase
Review current page and determine how to make the Outreach Events Calendar page more "refine-able" for users (e.g. how to conduct a "plain text search"). This discovery issue is meant to capture design ideas presented in the Product Outline, and to discuss ideas on how to make the Outreach Hub more relevant and useful based on recent release of Outreach & Events MVP (Recurring Events and Filtering).

#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive plain text search functionality, so that can quickly find VA events based on relevant keywords search i.e. Zumba, PTSD, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Research Report - O&E Enhancement MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/outreach-and-events/research/research-findings.md)

### Considerations
- Linked to Discovery Ticket #35242

### Tasks
- [x] Validate design elements and incorporate any feedback from review 
- [x] Close ticket once updates have been applied 

### Acceptance Criteria
- [x] Brief discovery doc outlining baseline feature flow and functionality created
- [x] Diagram uses cases and high-level feature flows 
- [x] Design is ready to work mock ups ISO design review

**Comment by cindymerrill** [comment]
I have a lot of feedback on @callen2563 's wireframes and am happy to discuss any or all of it:
1. Need to be able to specify whether to include online events in the location filter. Maybe add a checkbox?
2. The results of filtering should be events shown that satisfy ALL of the filters selected, not just one of them. So change the word "or" to "and" above the search results. And the results shown in the wireframes should match the filters, which they currently don't.
3. I'm confused about the 2 CTAs: the magnifying glass next to search box and the "Show filtered results" button. What happens if they click the magnifying glass? Does it only search for whatever's been entered in the search box, or also for whatever filters have been selected below?
4. Maybe rename "Show filtered results" to "Apply filter(s)" because this worked so well in usability testing
5. Under Custom date range filter, shorten the prompt from "Please enter a start date" to "Start date" (and same for "end date")
6. Change "Events filtering" to make an active verb: "Filter events"
7. FYI: Dave Conlon asked for separate designs for keyword search and for location search so he could choose to implement one or the other. He didn't want to have to separate out the two designs. I know that you're thinking about the design holistically, but he didn't want to see them together, so you might want to make separate versions before showing them to him.
@brianalloyd

**Comment by callen2563** [comment]
> I have a lot of feedback on @callen2563 's wireframes and am happy to discuss any or all of it:

**So @Brian I think it would help to have a meeting with the team to walk through my initial wires which are still being thought through. I’d like to include Sam and Trent to get early thoughts on functionality.** 
> 
> 1. Need to be able to specify whether to include online events in the location filter. Maybe add a checkbox?

**So I’m still noodling on this. My original thinking was to have a filter where the user can select “online” or “in person” and then if the user selects “in person” the State and City drop downs would appear below. Is this what you were thinking as well?**

> 2. The results of filtering should be events shown that satisfy ALL of the filters selected, not just one of them. So change the word "or" to "and" above the search results. And the results shown in the wireframes should match the filters, which they currently don't.

**I’m planning on following what [gov.uk](https://www.gov.uk/search/all?keywords=passport&order=relevance) does for filtering labels see example. I would like to get thoughts from dev or CMS on what is possible here. I will be updating the wires to match this just haven’t finished all the details.** 
<img width="658" alt="Screen Shot 2022-01-26 at 12 09 43 PM" src="https://user-images.githubusercontent.com/68560244/151218312-d4c22fc0-611a-4bd0-b63c-2e5c2d3bdfad.png">


> 3. I'm confused about the 2 CTAs: the magnifying glass next to search box and the "Show filtered results" button. What happens if they click the magnifying glass? Does it only search for whatever's been entered in the search box, or also for whatever filters have been selected below?

**Search is a separate function from filter similar to [gov.uk](https://www.gov.uk/search/all?keywords=passport&order=relevance)**

> 4. Maybe rename "Show filtered results" to "Apply filter(s)" because this worked so well in usability testing

**I originally had "apply filters" but then changed it once I saw what gov.uk was using "show search results". I think once we move to design intent we can get some thoughts from content on wording.**
<img width="508" alt="Screen Shot 2022-01-26 at 12 14 38 PM" src="https://user-images.githubusercontent.com/68560244/151218590-2acaaed4-d73a-4b6c-88b9-963b1c0301cd.png">

> 5. Under Custom date range filter, shorten the prompt from "Please enter a start date" to "Start date" (and same for "end date")

**This was a staging review update. We need to match the wording in the style guide for accessibility reasons. See attached example:** 
<img width="379" alt="Screen Shot 2022-01-14 at 4 57 10 PM" src="https://user-images.githubusercontent.com/68560244/151218942-e2585074-b46c-4452-b73f-8257bf9eada1.png">


> 6. Change "Events filtering" to make an active verb: "Filter events"

**Yeah I will change that I just realized events filtering was left over from the V1 wires which sounds wierd.**

> 7. FYI: Dave Conlon asked for separate designs for keyword search and for location search so he could choose to implement one or the other. He didn't want to have to separate out the two designs. I know that you're thinking about the design holistically, but he didn't want to see them together, so you might want to make separate versions before showing them to him.

**I think I missed this requirement because I wasn’t in the sprint meeting where Dave was talking about this so I will separate them out while also keeping the combined version as an example.**

>    @brianalloyd

**Comment by cindymerrill** [comment]
@callen2563 Here are my responses to yours:

1. I wasn't envisioning specific UI elements, but what you proposed makes sense to me.
2. To find events, I don't think it makes sense to **OR** the filters together from a user point of view, unless you can select more than one option for a filter (e.g., City = Washington, D.C. **OR** Bethesda, MD). I think you want to **AND** together the filter selections to find events (i.e., search for yoga **AND** during May 1-31 **AND** in Chicago, IL).
3. OK. Let's plan to assess with user research whether it's intuitive or confusing.
4. I don't think you can use "Show search results" if you have a separate search magnifying glass above, and the button is to make the filters below work. And I don't see where "Show search results" is used on uk.gov; it looks like it filters immediately without needing a button click like we have for accessibility.
5. There isn't room on the left side for long prompts. Is there a shortened style in the style guide for those (vs. fields in a full-page width form)? The other filters you have are short (State, City), and date prompts should match those.

**Comment by cindymerrill** [comment]
@callen2563 Here's more feedback from our wireframe walkthrough meeting this morning:
6. I think we should talk with Josh Kim about how to include an "Apply filter" button within the Filters panel so that selecting a timeframe option works for accessibility.
7. For location, I think that default filters should be State and City unspecified, and both online and in-person events included.
8. City shouldn't be a dropdown, unless we we're able to show a list of all cities with events in the already-selected State (not sure if this is implementable). Autocompletion would be great for both this list and also for State.

**Comment by callen2563** [comment]
**Updated wireframes with design options:**

![O E Wireframes V2](https://user-images.githubusercontent.com/68560244/151472729-dee7c43e-873e-4ed8-ba53-bd6c1899efdc.png)

**Comment by callen2563** [comment]
@brianalloyd So Cindy and I met with Josh today to get some initial feed back on some of the wireframes. I was presenting so I didn't capture notes so @cindymerrill if you have any notes if you could post them here that would be super helpful. As a next step I'm going to mock up some more wireframe options based on the feedback from Josh and then stress test them with the design system team and Angela. This is a design challenge that has site wide global implications so we need time to explore all options. I think it would be helpful (once I have some more wireframes) to set up the design intent to start the ball rolling on feedback.

**Comment by cindymerrill** [comment]
@callen2563 Here are some notes from our meeting with Josh, in which we showed Cassandra's mockups for adding a keyword search and location filtering.

1. After searching, focus will move to the line "Showing 300 results" and would skip the filter button shown in the mockups. This is standard behavior on VA.gov. To address this issue, there are several options:
- Move the filter button down to below "Showing 300 results"
- Merge the filter and search with one CTA (but that might get too long if there are multiple filters)
- Open filters in a modal like gov.uk does on mobile
- Change focus management so it doesn't move down to the results. This would require discussion with Kevin, Ryan, and someone from the Search team. Might rely on Aria Live polite announcements instead, but this isn't a good experience for screen reader users.

2. To save clicks, could replace the Filters button with the accordions for "Filter by location" and "Filter by timeframe", since all the button does it to show the accordions. This might look bad if there are a lot of filters, especially on mobile. This is why gov.uk opted for a modal instead--you have to interact with it, click the apply button, and then the page refreshes.
3. Hiding filters under a filters button might not be good for users--since they can't see them, they might not think to click on the button to see what's there and try them.
4. Can't use a left nav for the filters without design discussions and needing to add the pattern to the experimental design system. Dom order is relevant here (the order in which things are coded) because that's the order in which screen readers read out the page.
5. There's no one best solution for both sighted and screen reader users. The easiest balance might be to use a modal on both desktop and mobile so you'll always be able to see the first search result. In the modal, you'll have room for an Apply Filter button (for accessibility), flexibility for future additional filters, and a consistent design across mobile and desktop. One issue is for sighted users--if they can't see what the filters are, they might not think to try them (a user research question to investigate). Could change the "Filter" button to "Filter by time and location", for example, to reflect the filters included, which might help.
6. Note that the user interaction in these wireframes is different from what's currently being implemented with timeframe filtering only, in that the user must search first, and second use filters.
7. Josh recommends sketching out a number of different variations and see how the user interaction would work--a design exploration to get feedback on. Cassandra could invite another designer to help, and including Angela would be helpful for accessibility issues, especially if Josh isn't available.

**Comment by callen2563** [comment]
This is what was shown to Angela yesterday to get feedback on. She wants time to think about the best solution and will circle up with Josh.

![O E Wireframes V2 - Search with Filter](https://user-images.githubusercontent.com/68560244/152413292-3fe3e9bf-848b-4eb1-a4e4-bedee1d44863.png)

**Comment by callen2563** [comment]
After collaborating with Angela, Josh and Cindy this these are the design options that are ready for review with Dave and for Design Intent:

![O E Wireframes V2 - Search with Filter](https://user-images.githubusercontent.com/68560244/153264304-c7fea969-a08a-4e65-a6a5-4c76dd0f15bf.png)

**Comment by brianalloyd** [comment]
Closing out this ticket, final artifact lives here: https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/YZj40

**Comment by cindymerrill** [comment]
I can't access the designs in Sketch. Can anyone else after Cassandra departs? @brianalloyd
