### ISSUE TITLE
Troubleshooting Form-10-10cg Upload Issues

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#35909]
## Description
Issues observed in lower environments as well as production where uploaded documents for Form-10-10cg applications timed out and gave error messages to the user. In some/most cases, the file was actually making it to the upload destination (S3), but the error would leave a user to believe it failed entirely.

## Background/context 
https://dsva.slack.com/archives/CBU0KDSB1/p1643052924190500

## Technical notes
After a good bit of troubleshooting, we found the issue to very likely be a `proxy_read_timeout` setting in nginx/openresty (default is 60 seconds)

---
## Tasks
- [ ] Update nginx/openresty configurations to allow for longer proxy read timeout

## Acceptance Criteria 
- [ ] Code updated with necessary configuration change so future deployments allow the user to upload a document with a Form-10-10cg application

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
CC @dillo for transparency. 

Dillo and I tested the change in staging this morning, then Dillo also tested and verified things in working order in production as well once the change was merged and deployed.
