### ISSUE TITLE
Investigate `react-router v5` Upgrade

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#35917]
## Background
We need to determine what steps are needed to get our teams apps ready for the upgrade to react router v5. There is a thread [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34572#issuecomment-1016643583) describing what needs to be done to our applications to get us ready for this transition.

## Considerations
- Because several of our apps are labeled as OLD-FORM in platforms classification table, we have determined that we should wait until they make the needed changes on their end before we proceed
- [Discussion Link](https://dsva.slack.com/archives/C5HP4GN3F/p1643137773032800)

## Tasks
- [x] Discuss with platform about some of the procedures
- [ ] Update our apps to get ready for transition, if applicable

## Acceptance Criteria
- [ ] A path forward has been established (assisting platform in developing procedures)

**Next steps**
- [ ] eBenefits apps are ready for upgrade to react-router v5, or prepped
- [ ] A PR has been requested for merging, if applicable
