### ISSUE TITLE
Reevaluate invitees at Collaboration Cycle Reviews

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35910]
## Issue Description
Currently, there is not consistency in which OCTO leads and/or other team members are invited to which Collaboration Cycle touchpoints (including only Design Intent, Midpoint Review and Staging Review). The purpose of this ticket is to evaluate currently who is invited to which reviews, confirm that information with the individual, and update invites per their request. Individuals to include:

- Martha Wilkes
- Beth Potts
- Danielle Thierry
- Mikki Northuis
- Randi Hecht
- Shawna Hein (VSA only)
- Kevin Hoffman (since he's Ryan's backfill, for now)
- Rachael Roueche 
- Naomi Marcussen

#### Group email current members:
  -  allison.christman@oddball.io
  -  brian.deconinck@adhocteam.us
  -  chase.kirby@oddball.io
  -  clayton.zook@oddball.io
  -  jim.ryan@adhocteam.us
  -  mikki@adhocteam.us
  -  naomi.marcussen@oddball.io
  -  randi.hecht@gcio.com
  -  sarah.koomson@oddball.io
  -  sean.sewell@oddball.io
  -  shira.goodman@oddball.io
#### Non group current members:
  -  danielle.thierry ​(optional)
  -  bethpotts25 optional (optional)
  -  Shawna(optional - if VSA team)
  -  Josh Kim (optional - if VSA team)
  -  Angela Fowler (optional - if VSA team)
#### Group email current members:
  -  allison.christman@oddball.io
  -  brian.deconinck@adhocteam.us
  -  chase.kirby@oddball.io
  -  clayton.zook@oddball.io
  -  dariusz.dzien@adhocteam.us
  -  jim.ryan@adhocteam.us
  -  naomi.marcussen@oddball.io
  -  sarah.koomson@oddball.io
  -   sean.sewell@oddball.io
  -  shira.goodman@oddball.io
#### Non group current members:
  -  Rachael Roueche (optional)
  -  martha.wilkes (optional)
  -  Shawna(optional - if VSA team)
  -  Josh Kim (optional - if VSA team)
  -  Angela Fowler (optional - if VSA team)

#### Group email current members:
  -  allison.christman@oddball.io
  - brian.deconinck@adhocteam.us
  - chase.kirby@oddball.io
  - dariusz.dzien@adhocteam.us
  - jim.ryan@adhocteam.us
  - naomi.marcussen@oddball.io
  - sarah.koomson@oddball.io
  - sean.sewell@oddball.io
  - shira.goodman@oddball.io
#### Non group current members:
  -  Rachael Roueche (optional)
  -  martha.wilkes (optional)
  -  Michelle Dooley (optional)
  -  Lauren Simpson  (optional)
  -  Mikki Northuis (optional)
  -  Josh Kim (optional - if VSA team)
  -  Angela Fowler (optional - if VSA team)
  -  Tze Lei (optional - if VSA team)

---
## Tasks
- [x] Confirm which events the above folks are currently invited to.
- [x] Message them via Slack stating that these are the events they're currently included in and ask if they'd like to keep it as is, remove touchpoints and/or add touchpoints
- [x] update the moderator responsibilities docs for Design Intent, Midpoint Review and Staging Review to reflect the changes
   - potentially add certain folks to the distribution lists?

## Acceptance Criteria
- [x] Platform includes the right individuals at the appropriate Collaboration Cycle touchpoint meetings. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
FYI @chaseakirby @allison0034

**Comment by allison0034** [comment]
For design intent, I think we should just add all invitees to the group email except the VSA team. 

Group email:
allison.christman@oddball.io
brian.deconinck@adhocteam.us
chase.kirby@oddball.io
clayton.zook@oddball.io
jim.ryan@adhocteam.us
mikki@adhocteam.us
naomi.marcussen@oddball.io
randi.hecht@gcio.com
sarah.koomson@oddball.io
sean.sewell@oddball.io
shira.goodman@oddball.io
danielle.thierry ​
bethpotts25 
Kevin Hoffman

Non group email:
Shawna(optional - if VSA team)
Josh Kim (optional - if VSA team)
Angela Fowler (optional - if VSA team)

**Comment by allison0034** [comment]
For staging, I think we should just add all invitees to the group email except the VSA team. Note: adding Kevin, removing Ryan and Noah

Group email:
allison.christman@oddball.io
brian.deconinck@adhocteam.us
chase.kirby@oddball.io
clayton.zook@oddball.io
jim.ryan@adhocteam.us
mikki@adhocteam.us
naomi.marcussen@oddball.io
sarah.koomson@oddball.io
sean.sewell@oddball.io
shira.goodman@oddball.io
Kevin Hoffman
Lauren (change email to lauren.simpson@searchdiscovery.com)
Michelle Dooley 

Non group email:
Shawna(optional - if VSA team)
Josh Kim (optional - if VSA team)
Angela Fowler (optional - if VSA team)

**Comment by allison0034** [comment]
@chase are you ok with the suggestions? I have confirmed with who wants to be on or off the email.

**Comment by chaseakirby** [comment]
@allison0034 I was looking through the slack threads and just wanted to check in case I missed it but did Michelle Dooley respond? I don't see any reactions from her or reply in the threads.
That than that, I think it looks good!

**Comment by allison0034** [comment]
@chaseakirby I had to DM her, she wasn't in that channel.

**Comment by chaseakirby** [comment]
@allison0034 Gotcha. I think it looks good otherwise and I agree with adding them to the email group since they know they are optional.

**Comment by allison0034** [comment]
@chaseakirby please check the following pages/emails:
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)
va.gov-staging-review@oddball.io
va.gov-design-intent@oddball.io
va.gov-midpoint-review@oddball.io

**Comment by chaseakirby** [comment]
@allison0034 All pages and email groups look good to me! 
It looks like all Tasks and AC have been met so this can be closed.

**Comment by shiragoodman** [comment]
adding Michelle to the Collab Cycle slack channel - thanks!
