### ISSUE TITLE
[Design] Onboarding: Liz to assist in onboarding Angela to the AE - My VA team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#35918]
Angela Agosto will be onboarding our team, starting Monday 1/31.  
Liz will be assisting her by sharing documentation, experiences and advisement on the team's processes and projects.

## Tasks
- [ ] Walkthru documentation (i.e. folder locations) with Angela on current projects (FYI, PM shared links in Angela's ticket)
- [ ] Walkthru applications used by the team to create and edit designs for My VA
- [ ] Advise on team processes, Collab cycle involvement and demos
- [ ] ...

**Comment by hdjustice** [comment]
Ticket was not completed, as there is more support needed to onboard Angela.  This will move on to the next sprint.

**Comment by andaleliz** [comment]
Angela and I have gone through all the formal onboarding activities we can at this point. Moving forward I'll continue to support her as a teammate and be available to answer any questions.
