### ISSUE TITLE
HLR v2 Usability Phase 1 - Create Research Plan

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#35926]
## Issue Description
Conduct usability study for new version of HLR

---
## Tasks
- [x] Create research plan
- [x] Create conversation guide

## Acceptance Criteria
- [ ] Research plan and conversation guide complete. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
