### ISSUE TITLE
Auth Profile: Sprint 66 (Jan 26 - Feb 8)

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35922]
# Auth Profile: Sprint 66 (Jan 26 - Feb 8)

## PTO/OOO/Unavailable
- Adam - Tech Training 1/31 - 2/4 12-5 ET daily; will be available 2-3 hours per day plus before/after training

# Sprint Objectives
### PM
- [x] Review team plan for the next few months
- [x] #33007 (still monitoring for feedback from VBA; took over from Liz; Jeremy responded but still doesn't have final info.

### FE -  Adam
- [x] #35975 
- [x] #35981
- [ ] #19618 - move to next sprint; more complex than originally believed

### BE - Tom
- [x] #35977

<hr>

### FE, Design, BE, PM
- [x] #35985

### Design - need to clarify long/short term tasks
- [ ] #35585 - moving to next sprint
- [x] #35582
- [x] #35987

### PM
- [x] Tickets to remove Gender from BE call (no ticket; standard PM task)
- [x] Remove Gender/sex assigned at birth from our content requests (no ticket; standard PM task)

### Design - Christina
- [x] Complete Design Changes Resulting from Research Study #35219
- [ ] Add "why do we ask for this?" information next to each field, and make it clear these fields are optional #36240 - moving to next sprint

### FE - Adam
- [x] #36009 - done and ready to validate on Staging

- [ ] #36006 - if mockups/content done - not done; possibly next sprint

### BE - Tom

- [x] #36011

<hr>

### PM - Marci

- [x] Continue discovery
- [x] Product outline (Samara can hopefully do this)
- [x] Project kickoff (schedule towards end of the sprint)

## Unplanned work

**Design**

- [x] Personal information revisions: Update Gender identity and Sexual orientation in mocks so they are multiselect #36165
- [x] Personal information revisions: Remove "prefer not to answer" from pronoun field in mockups #36173
- [x] #36361 
- [X] #36352

**FE**

- [x] Personal information revisions: Change character limit from 100 to 25 characters for preferred name #36078
- [ ]  Personal information revisions: Update Gender identity and Sexual orientation so they are multiselect #36168
- [ ]  Personal information revisions: Remove "prefer not to answer" from pronoun field #36174

**BE**
- [x] #36364
