### ISSUE TITLE
[EHRM Statements] Review SME interview and draft additional questions

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#35921]
## Issue Description
We met with Thuy to start learning about if and how Cerner statements may impact MCP's UX. We need to review the interview and document outstanding questions to dictate an additional interview

---
## Tasks
- [x] Review [the interview transcript](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/VHA%20Debt%20Letters%20Improvement/EHRC%20Statements/Research/Discovery%20questions.docx?d=w638ed7066e3b458898168b2300e75cd7&csf=1&web=1&e=zfdw6U)
- [x] Adjust interview guide with remaining questions

## Acceptance Criteria
- [x] The discovery document has been linked to this ticket after being reviewed and adjusted

**Comment by rileyorr** [comment]
Finished reviewing [the transcript](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Medical%20Copay%20Tool/EHRC%20Statements/Research/Discovery%20questions.docx?d=w638ed7066e3b458898168b2300e75cd7&csf=1&web=1&e=TBhPT5) and documented my outstanding questions towards the bottom. 

# Additional Questions 

**New statement**

- Can we get a mock Cerner statement? 
- Have the notification letters regarding the Cerner transition been sent to all Veterans or just Veterans who go to Spokane?  
   - Can we get a mock letter? 
- When these new statements for Spokane go out, will all the accumulated charges between Oct 2021 – [Launch Date] be listed on one statement? 

**Legacy accounts**

- What's an example of a scenario in which a Veteran would still have a legacy account when Spokane statements go live? Won't 120 days have passed before go-live at Spokane after collection resumption? 
- What will the separate statement for legacy accounts look like? i.e., will it be the same statement as before? 
   - If they’re different, can we see a mock statement? 

# Next steps 

- Follow-up with Thuy to see if we can get mock statements/letters outlined above 
   - Denise is amazing and has already emailed Thuy!
