### ISSUE TITLE
Add Sentry logging to failing VBMS calls

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#35935]
## Issue Description
VBMS is frequently down for maintenance so we need to aggregate these failures via Sentry

---
## Tasks
- [ ] Add `log_exception_to_sentry` call upon VBMS request failure

## Acceptance Criteria
- [ ] When VBMS requests fail we are notified with more detailed info on Sentry
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
