### ISSUE TITLE
[FSR] Eslint accessibility errors

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#35949]
## Issue Description
VSP is trying to turn on `jsx/a11y` linting rules, but they’ve been off for so long that it looks like over 200 misc errors have cropped up and have asked us to lend a hand to update our own applications. Related slack convo: https://dsva.slack.com/archives/C5HP4GN3F/p1643135144032200

Receiving the the following error for FSR:

```
Static HTML elements with event handlers require a role
```

Steps to find errors:
1. Pull latest vets-website
2. Open /.eslintrc.js
3. Search for jsx/a11y properties and update the following values to see errors
-- jsx-a11y/control-has-associated-label
-- jsx-a11y/no-static-element-interactions
6. If the rule is set to 0, set it to 2 (ignore href-no-hash as it has been deprecated)
7. Run yarn lint:js
8. View errors

![craigwheeler@MacBook-Pro~codegovernmentcioVAvets-website 2022-01-25 17-19-51(1).png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/7b7b4db3-d42b-4cce-8334-613931e8a0f7)

---
## Tasks
- [ ] verify all errors owned by the debt res team pass a11y testing and update any failing tests

## Acceptance Criteria
- [ ] verify all a11y tests owned by the debt res are team passing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
These errors are the result of choosing `a` tags instead of `button` tags. After speaking with @rileyorr we have decided to revert these links to buttons for now which will be a temporary solution in preparation of the upcoming list loop redesign work

![Financial Status Report  Veterans Affairs 2022-01-28 11-24-42.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/0987a58d-181b-46e3-94f1-d8ee2b5601e3)
