### ISSUE TITLE
Front end implementation of Cerner Medical records link

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#35947]
## Issue Description
The current VA blue button medical records widget will not provide the best experience for Veterans receiving care at Cerner facilities. Until we can provide a more elegant solution, we can replace the widget for a simple link [to view clinical notes via the patient portal](https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes).

### Other relevant work
- #31109 added redirects to the a general login page for the Cerner portal from within the "Manage your health online" box based on a Cerner flag in CMS identifying systems which have cutover. 
- #33740 will update the general links with task-specific deep links.

**This work will block the release of the hardened medical records page.** 

**This implementation should only appear when indicated based on the CMS flag for Cerner locations**

### Current experience

Example page: [Spokane Medical records](https://www.va.gov/spokane-health-care/medical-records-office/)

<details>
<summary> Screenshot from Spokane </summary>

![image](https://user-images.githubusercontent.com/55411834/146585204-f145570b-1d52-4ff3-acfd-827a979eadb2.png)

</details>

## Tasks
- [ ] **Based on the Cerner flag from CMS**, replace existing VA Blue Button sign in alert on Medical Records page with primary action link according to Nick's design ([UX Pin] (https://preview.uxpin.com/42f2f277005d817321187dda7b843618aa2b09aa#/pages/146742657/documentation/no-panels?mode=i)), , including
    - 16px spacing on the left of link (or equivalent)
    - Specs for primary call to action link based on [Storybook link](https://design.va.gov/storybook/?path=/docs/components-action-link--primary-)
    - Link directs Cerner patients [to their relevant portal](https://patientportal.myhealth.va.gov/pages/health_record/clinical_documents/open_notes?pagelet=https%3A%2F%2Fportal.myhealth.va.gov%2Fperson%2F1056308125V679416%2Fhealth-record%2Fopen-notes) to request medical records 

## Acceptance criteria
- [ ] Link to Cerner portal renders only when indicated based on the CMS Cerner flag
- [ ] Link to Cerner portal renders according to Nick's design spec
- [ ] When the Cerner flag is not indicated, the existing experience should be maintained
- [ ] Link directs Cerner patients to their portal

**Comment by jilladams** [comment]
These links will change with MyHealtheVet on VA.gov this will go away.
