### ISSUE TITLE
[VAMC] Menu clean up Part 2 - Document suggested correct Menu Parent items for pages incorrectly saved in Menu admin [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#35953]
## STORY
As a Veteran I need to have a simple and standardized location for all VAMC web pages, so I can quickly find and locate my VAMC information.

## RESOURCES
TBD

## TASKS
- [x] Identify and document all VAMC pages that are not aligned under the correct parent page or section.
- [x] Determine correct parent page and new URL and bread crumb of page for relocation
- [x] Work with PM to send out communication that pages will be updated to new location

## ACCEPTANCE CRITERIA
- [ ] Artifact document for original and new URL locations of menu items that need to be moved.

**Comment by ltrombley** [comment]
Task #35953 - Menu clean up Part 2 - Document suggested correct Menu Parent items for pages incorrectly saved in Menu admin - is Complete and moved to Validate. (PENDING communications sent to PAO/POCs)
