### ISSUE TITLE
Pre-Call Center Prep (Video)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3595]
## Story
As a Call Center team member helping Veterans with the Rated Disabilities tool, I want to be able to view a video that shows how to operate the feature so that I can be better informed in how to help as well as be able to share widely on YouTube.

## Tasks
- [x] Write a short script that discusses logging in, using the tool and navigating the Rated Disabilities tool.
- [x] Create a short video, with a voiceover, explaining how to use the Rated Disabilities page

## Acceptance Criteria
- [x] A video has been created and ready to be uploaded to YouTube where a link will be shared with the Call Center.

**Comment by jason-gcio** [comment]
Video is in slack, ready for upload.
