### ISSUE TITLE
Pre-Call Center Prep (FAQs)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3596]
## Story
As a Call Center team member helping Veterans with the Rated Disabilities tool, I want to be able to view a list of FAQs that answers common questions on a variety of topics so that I can be better informed in how to help users that call in.

## Tasks
- [ ] Write a list of commonly asked questions and answers with as much detail and context as possible.
- [ ] Write a list of imagined questions and answers that could be asked with as much detail and context as possible.

## Acceptance Criteria
- [ ] A list of FAQs has been created and ready to be shared with the Call Center.
