### ISSUE TITLE
[BE] Auth Profile: Remove Fax Number from backend call on Profile contact info page.

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35977]
## Background
VA Profile is working to remove the Fax number from their data source and need to coordinate with the VA.gov Profile team so that the Contact Information page no longer collects or passes Fax Number, nor displays that field on the page.  We are currently in the midst of separating the Personal Info/Contact Info page that exists in Prod into two different pages, so this change will need to apply to both versions.    We will coordinate with the VA Profile team when our change is in so that they can make plans to promote their changes.

## Tasks
- [ ] Create a feature flag to keep change on Staging until VA Profile team is ready to coordinate a joint update.  
- [ ] Update the backend code for the combined Personal Info/Contact Info page on Production so that it no longer requests or returns Fax Number data from/to VA Profile
- [ ] Complete testing and peer review
- [ ] Notify PM when the update is ready to be reviewed on Staging.

## Acceptance Criteria
- [ ] Feature flag to keep change on Staging until VA Profile team is ready to coordinate a joint update has been created.  
- [ ] Backend code for the combined Personal Info/Contact Info page on Production has been updated so that it no longer requests or returns Fax Number data from/to VA Profile
- [ ] Testing and peer review completed
- [ ] PM has reviewed on Staging

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
**Note from 1/29 chat**: Before this goes live, we need to coordinate with the mobile app team on removal of this field from their app.

**Comment by Samara-Strauss** [comment]
Update after talking to mobile team: **We should put backend removal on hold**. According to @travis-newby [via Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1643399917956909?thread_ts=1643395405.843779&cid=C018V2JCWRJ):

> Generally speaking, mobile apps are sensitive to backend changes because we have to support multiple versions of the app in the wild at the same time. Because we don't force upgrades, and few apps do, we'll likely have Veterans using versions of the app that require the gender field for quite some time. So before we make changes to a mobile app service, or even an upstream service, we have to account for all those old versions of the app.

So the mobile team needs time to figure out how to remove this field from their app given people may be using old versions of the app that still show the field.

So, Adam can still go forward any time with removing Fax from the UI, but let's hold off on the backend removal until Mobile has time to figure out a plan. Going to pull this work out of this sprint as a result.

cc/ @MarciMcGuireGCIO for awareness whenever you are back.

**Comment by Samara-Strauss** [comment]
ANOTHER UPDATE!!

According to Alastair [via Slack](), it sounds like we might be able to make some progress on the backend, but I don't understand enough about how the code works to be able to advise on exact steps. @tpharrison, can you please coordinate with @kreek and @travis-newby as necessary, and pull in Lihan if needed? And when you have a plan, please post in this ticket what next steps have been agreed on by all parties? Thank you!

cc/ @MarciMcGuireGCIO for awareness. I'll pull the ticket back into this sprint.

**Comment by tpharrison** [comment]
UPDATE...

The decision has been made to hold off on any backend changes related to fax number at this time. @lihanli has suggested that any teams referencing the fax number should file an issue and wait for the removal of all client references to the fax number field before proceeding with any backend changes. As @travis-newby and @kreek mentioned, the best practice recommendation for removing any part of an API is to up-version the API before doing so. We can discuss this further as a team when the time comes.

**Comment by Samara-Strauss** [comment]
Thanks, Tom! 

Given this, I'm actually going to close out this ticket. I know the scope changed from remove the endpoint to investigating next steps and coordinating with other teams, but that's OK. Given that we determined now is not the time for this work, we can close this ticket and open a new one when we're actually ready to remove the endpoint.

**Comment by MarciMcGuireGCIO** [comment]
Wow, there was lots of breaking news on this one.  Thank you both, @Samara-Strauss and @tpharrison for keeping track of things.
