### ISSUE TITLE
[FE] Auth Profile:  Remove Fax number from Contact Information

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35975]
## Background
VA Profile is working to remove the Fax number from their data source and need to coordinate with the VA.gov Profile team so that the Contact Information page no longer contains a field for fax number.

## Tasks
- [x] Create a feature flag that is distinct from the flags being used for Address Change, Personal Info Revision, etc.  
- [x] Update the combined Address/Contact page that is in Production so that it no longer contains the Fax Number field
- [x] Complete testing
- [x] Notify PM when the update is ready to be reviewed on Staging.

## Acceptance Criteria
- [x] Feature flag that is distinct from the flags being used for Address Change, Personal Info Revision, etc. has been created
- [x] Combined Address/Contact page that is in Production is updated so that it no longer contains the Fax Number field
- [x] Testing completed
- [x] PM has reviewed on Staging

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
**Note from 1/29 chat**: Before this goes live, we need to coordinate with the mobile app team on removal of this field from their app.

**Comment by Samara-Strauss** [comment]
Update after talking to mobile team: **We should put backend removal on hold**. According to @travis-newby [via Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1643399917956909?thread_ts=1643395405.843779&cid=C018V2JCWRJ):

> Generally speaking, mobile apps are sensitive to backend changes because we have to support multiple versions of the app in the wild at the same time. Because we don't force upgrades, and few apps do, we'll likely have Veterans using versions of the app that require the gender field for quite some time. So before we make changes to a mobile app service, or even an upstream service, we have to account for all those old versions of the app.

So the mobile team needs time to figure out how to remove this field from their app given people may be using old versions of the app that still show the field.

So, Adam -- you can still go forward any time with removing Fax from the UI, but we need to hold off on the backend removal until Mobile has time to figure out a plan. 

cc/ @MarciMcGuireGCIO for awareness whenever you are back.

**Comment by Samara-Strauss** [comment]
ANOTHER UPDATE!!

According to Alastair [via Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1643405460345419?thread_ts=1643395405.843779&cid=C018V2JCWRJ), it sounds like we might be able to make some progress on the backend, but I don't understand enough about how the code works to be able to advise on exact steps. @tpharrison will be coordinating with the mobile folks to figure out what to do from here, and will post an update in his ticket when he has it.

However, it might not make a different either way what the backend does if we want to go ahead and remove this field from the frontend. Does that sound OK to you all? I don't want to do that if it might cause problems I am unaware of, so please do raise concerns if you have them given I am not a code expert and may have blind spots.

cc/ @MarciMcGuireGCIO for awareness.

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO and @Samara-Strauss The fax field has been removed from stagings and can be validated now. Thanks!

**Comment by Samara-Strauss** [comment]
Validated. Looks great! Will this go into prod tomorrow? If so, let me know so I can update the VA Profile team.

**Comment by adamwhitlock1** [comment]
yep, so after tomorrow's daily deploy, it will be behind the feature toggle, so that means it will be shown until we want to pull the trigger and remove it.

**Comment by Samara-Strauss** [comment]
We can go ahead and remove it with today's deploy. No need to wait :D

**Comment by MarciMcGuireGCIO** [comment]
This is excellent!  Thank you so much for getting this done so quickly!

**Comment by adamwhitlock1** [comment]
Production now has the fax field removed, and I think this issue can be closed @MarciMcGuireGCIO

**Comment by MarciMcGuireGCIO** [comment]
Awesome! Looks great! Thank you @adamwhitlock1 ! Cc @Samara-Strauss
