### ISSUE TITLE
Update MURAL board per Shane's new process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35978]
## Issue Description
Shane Strassberg took over as the OCTO-DE Research lead and introduced a new process for submitting the research plan and conversation guide for OCTO-DE review and approval. This ticket will be to update the [MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1635982647504/55fa21c511278746380673529b6db66447b3fb0d?sender=u0574179b1d97118ccc0e3591) documented by @naomimarcussen in November of 2021 to reflect Shane's new process.

Ideally we will NOT update the Current State section of the board, but instead relabel that section to, "Status November 2021" or something similar, and create a new view for status as of January 2021 which reflects Shane's process.

---
## Tasks
- [x] Update MURAL board to reflect the new process as of January 2021
- [x] Review updated board with @naomimarcussen for approval

## Acceptance Criteria
- [x] The VFS Research MURAL board reflects the current process for submitting the research plan and conversation guide for OCTO-DE review and approval

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
@allison0034 could you merge @naomimarcussen's board (tagged in the description) with your board so the different flows of the research review process can all be seen in 1 board? I think it'll be easier moving forward to only have to reference 1 board.

**Comment by allison0034** [comment]
@shiragoodman I was unable to extend the board. @naomimarcussen did you ever figure out how to get that board bigger?

**Comment by allison0034** [comment]
@shiragoodman I think I was able to copy Naomi's into my [new Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643299702632/9e19d2558718ae9f685cc7f1fbe92b496c7c6a20?sender=u045df875f30f7e9f34339908).

**Comment by shiragoodman** [comment]
@allison0034 Right now it looks like 2 mural boards smushed together instead of one cohesive board. Can you rename "Current state" to November 2021, then put your new January board to the right of it and then future state to the right of that? See image: 
![image](https://user-images.githubusercontent.com/71330581/153881585-d5692b6b-b3d4-4cfe-a318-25c4fd06c300.png) Also please remove "Naomi's original mural" and add the correct title back in. 

We will most likely be presenting this in demo soon so we want it to be an artifact people can reference on their own and see the trends over time. If you want to chat further, please let me know.

**Comment by allison0034** [comment]
@shiragoodman those changes have been made to the [VFS Research Process](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643299702632/9e19d2558718ae9f685cc7f1fbe92b496c7c6a20?sender=u045df875f30f7e9f34339908)

**Comment by shiragoodman** [comment]
looks great @allison0034 ! thank you. could you please make sure it's saved in the [Product Support room](https://app.mural.co/t/adhocvetsgov9623/r/1621540286136) on MURAL?

@naomimarcussen now that this board is in place, I think it could replace the one you had created previously. Could you delete your board or potentially add a redirect link to Allison's board? Whatever you prefer. Thanks!

**Comment by shiragoodman** [comment]
thanks @allison0034 ! I linked it to the initiative so we should be good. This can be closed.
