### ISSUE TITLE
Adjust COE Request Date

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#35989]
## Background
The date on the intro page is currently mocked but we should be able to to get this switched over to a live date.

## Considerations
![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/a6798ece-0a60-4750-848f-a15f73543931)

## Tasks
- [ ] Swap out the mocked date for the live one
- [ ] 

## Acceptance Criteria
- [ ] The date has been made live from LGY data
- [ ] A PR has been requested for merging
