### ISSUE TITLE
Review Collab Cycle references/links in Research & Design section of Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#35982]
## User Story
As a VFS team, I want clear links to Collaboration Cycle in the Research & Design section of Platform Website so that I can easily navigate to related Collaboration Cycle pages.

---
## Issue Description
The[ Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) section of Platform Website provides guidance to VFS teams on how to meet Platform expectations related to research, design, content, IA and accessibility. There are at least 2 (potentially more) references to the Collaboration Cycle in this section that link to the wrong Collaboration Cycle urls. The purpose of this ticket is to fix the known links so they direct VFS teams to the right Collaboration Cycle page, and to review the full Research and design section to confirm there aren't any other issues re: references to the Collaboration Cycle.

Known issues:

1. https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html
2. https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html

---
## Tasks
- [x] Update the urls for the known issues above to the main Overview page of the Collaboration Cycle on Platform Website: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html
- [x] Review the remaining pages of the [Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) section of Platform Website and identify any other areas where Collaboration Cycle is mentioned.
   - [x] If found, update the url per the guidance above.
   - [x] If not found, no changes necessary.

## Acceptance Criteria
- [x] The [Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) section of Platform Website correctly references the Collaboration Cycle
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby the only 2 pages that have Collaboration Cycle are the [Research Checklist](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2098397354/Allison+Copy+of+Research+Checklist) and the [Research Overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2098462838/Allison+Copy+of+Research+Overview). Please review the changes and let me know when approved to go live.

**Comment by chaseakirby** [comment]
@allison0034 I have reviewed and I have no issues. I think the main CC page and the "Getting Started" pages make sense where they are linked.

**Comment by shiragoodman** [comment]
I agree with Chase. Feel free to move forward @allison0034 !
