### ISSUE TITLE
[FE][Design][BE][PM]  Auth Profile - Address Messaging - Activity diagram, solution options

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35985]
## Background
During open office hours last sprint, Christina presented a possible design for the address change messaging.  There were a lot of questions, as well as questions Adam thought of as he prepared for the front end work.  

## Tasks
- [x] Workshop meeting to map out activity
- [x] Team discusses potential solutions that can be mocked up in a separate task.

## Acceptance Criteria
- [x] Workshop meeting has been held
- [x] Team has discussed and documented potential solutions for mockups

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
Adding link to Mural board: https://app.mural.co/invitation/mural/vsa8243/1643216182753?sender=ubc7e3ad210f2b3eb28e46170&key=02fb350d-95fc-4a3e-b31b-ac182fc8f8d6

Adam is going to work on mapping out additional scenarios, and Christina is going to start a mockup based on Iteration 2 in her low-fi mockups.

**Comment by cgednalske** [comment]
Hi all! Met with Liz for a design feedback session and we're still a go for Iteration 2. Here are the [sketch files of some hi-fi mockups](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2) based on our discussion, with small changes to help define hierarchy and highlight the questions and addresses. We also discussed the content and Liz thought that was pretty in line with Danielle's preferred language, but I will also check with her to see if any changes are needed per #35987

Please let me know if there are any questions or further thoughts!

**Comment by andaleliz** [comment]
👋 Lurking on this and have an additional comment to add to something from the Mural board. I don't think Mural sends notifications if someone comments, so thought it'd be better to add here.

>Furthermore, we're not actually sure how big this problem is that led to this request (it may be very small), but it was only due to mailing addresses not being updated to match home that this request was made - not necessarily vice versa. So we may want to consider focusing only on mailing address if it becomes too complicated to go beyond that right away.

Since we don't know how big this problem actually is, it'll be helpful to bake in some analytics around this, with whatever solution yall move forward with, so we can start measuring things to help us understand the scope of this problem moving forward and can iterate accordingly..

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @andaleliz !
