### ISSUE TITLE
[Design] Auth Profile: Address Change Messaging: Work with Content on modal verbiage

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35987]
## Background

The team held a workshop to diagram and discuss potential options (see #35985) and the mockups updated based on that discussion and workshop (see #35585).   This task is to work with Danielle on crafting the content for the modal(s) so that they are clear and user-friendly.

## Tasks
- [x] Contact Danielle to give high-level description
- [x] Find out if we need to submit a ticket for her
- [x] Create a content request if needed that describes the content needed

## Acceptance Criteria
- [x] Contact Danielle to give high-level description
- [x] Find out if we need to submit a ticket for her
- [x] Create a content request if needed that describes the content needed

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
Hi @cgednalske, can you please put an estimate on this issue when you have a minute?  Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !

**Comment by MarciMcGuireGCIO** [comment]
^^ @Samara-Strauss FYI
