### ISSUE TITLE
[FE] [Discovery] Auth Profile: Determine changes needed for React-router update 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35981]
## Background

Per this [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1643145582323400), the Release Tools team is upgrading `react-router` from v3 to v5.1.2.   They need application owners to make appropriate fixes according to [their list of deprecated router usage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34572#issuecomment-1016643583).   The Slack thread contains info on guidance, overview and how to request support.

## Tasks
- [ ] Review the Slack thread referenced above and the list of deprecated router usage
- [ ] Add a comment to this ticket listing the apps and changes that will be required
- [ ] Provide a high-level estimate for each change

## Acceptance Criteria
- [ ] Slack thread referenced above and the list of deprecated router usage has been reviewed
- [ ] Add a comment to this ticket listing the apps and changes that will be required
- [ ] Provide a high-level estimate for each change

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by MarciMcGuireGCIO** [comment]
@adam, would you please pop an estimate on this task when you have a chance?  Thanks!

**Comment by adamwhitlock1** [comment]
Overall it looks pretty straightforward to update the personalization/profile app since it is shown as using the 'NEW' component routing configuration, so minimal changes should be needed. 

There is a note showing that the profile is using an 'Old Import,' so that will likely be needing an update task, but probably just 2 points with the criteria of: 

- updating the import to new import path
- fix any breaking changes that could occur
- verify that tests pass and update any tests if needed

@MarciMcGuireGCIO Should I also evaluate the LOE for personalization/rated-disabilities, personalization/search-representative, personalization/view-dependents, and personalization/view-representative? Since I haven't worked in those apps I might not be too sure on their scope, but can take a stab at it.

**Comment by MarciMcGuireGCIO** [comment]
@hdjustice - at the end of Adam's comment [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35981#issuecomment-1031842201), he lists what needs to be updated for the React-router updates.   Are those part of My VA?  If so, should we have Taylor estimate that work since he may be more familiar?  Thanks!  cc @adamwhitlock1
