### ISSUE TITLE
[PM] Auth Profile: Personal Info Revision: Work with Lexi on FAQs

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#35992]
## Background

Our research found that most users had reservations about how the information being collected would be kept private and how it would be used.  To that end, we want to work with Lexi, who is our POC at LGBTQ Health Services, so that we can get basic info about how this information is protected and how it's intended to provide better service to Veterans.

## Tasks
- [ ] Contact Lexi with our assumptions for the FAQ
- [ ] Get Lexi's feedback
- [ ] Create a content request for Danielle to help craft the content in the correct voice and using the correct guidelines

## Acceptance Criteria
- [ ] Contact Lexi with our assumptions for the FAQ
- [ ] Get Lexi's feedback
- [ ] Create a content request for Danielle to help craft the content in the correct voice and using the correct guidelines

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
Closing, this is a duplicate of #36240, which I created to account for content & design updates.
