### ISSUE TITLE
[Page Update] Please remove duplicate page link, "How to File a Death Claim"  [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36008]
## Story
As a Veteran, caregiver, and family member I need precise web pages with no duplicates, so I can quickly find the end of my web support journey.

## Resources
[Life Insurance web page]( https://www.va.gov/life-insurance/)
[Change the link for File a claim for insurance benefits to:](https://www.benefits.va.gov/INSURANCE/file_death_claim.asp)
- Link url:  https://www.benefits.va.gov/INSURANCE/file_death_claim.asp

## TASK
- [x] Review and research type of duplicate page and/or link
- [x] Resolve issues and save page to published.
- [x] Confirm link/duplicate page is resolved after content release
- [x] Have Customer "Steve Fital Management & Program Analyst Steven.Fital@va.gov"  Confirm

## Acceptance Criteria
- [x] Page is updated and links are working as requested
- [x] Update is sent to customer for review

**Comment by lunascoop** [comment]
@RLHecht I updated the link and the page is ready for review.

VA life insurance: http://preview-prod.vfs.va.gov/preview?nodeId=77

**Comment by RLHecht** [comment]
I reviewed and published. I'll wait till the page is live to let Steve know it's updated.

**Comment by RLHecht** [comment]
Emailed Steve to let him know page is live. Moving to validate.
