### ISSUE TITLE
[FE] Personal Information: Remove "gender" field from existing combined personal/contact information page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36009]
## Background

User research found that people who identify as transgender may be triggered or offended if their gender/sex assigned at birth is displayed on their VA Profile.   This will need to be coordinated with Tom since the call to retrieve this data also needs to be removed from the BE.

## Tasks
- [x] Create a feature flag to keep this on Staging until it is ready for Prod
- [x] Remove gender from existing combined personal/contact information page in VA.gov Profile
- [x] Test and peer review
- [x] Update PM once it's merged and ready for validation on Staging.

## Acceptance Criteria
- [x] Create a feature flag to keep this on Staging until it is ready for Prod
- [x] Remove gender from existing combined personal/contact information page in VA.gov Profile
- [x] Test and peer review
- [x] Update PM once it's merged and ready for validation on Staging.

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
**Note from 1/29 chat**: Before this goes live, we need to coordinate with the mobile app team on removal of this field from their app.

**Comment by Samara-Strauss** [comment]
Update after talking to mobile team: **We should put backend removal on hold**. According to @travis-newby [via Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1643399917956909?thread_ts=1643395405.843779&cid=C018V2JCWRJ):

> Generally speaking, mobile apps are sensitive to backend changes because we have to support multiple versions of the app in the wild at the same time. Because we don't force upgrades, and few apps do, we'll likely have Veterans using versions of the app that require the gender field for quite some time. So before we make changes to a mobile app service, or even an upstream service, we have to account for all those old versions of the app.

So the mobile team needs time to figure out how to remove this field from their app given people may be using old versions of the app that still show the field.

So, Adam can still go forward any time with removing Gender from the UI, but let's hold off on the backend removal until Mobile has time to figure out a plan.

cc/ @MarciMcGuireGCIO for awareness whenever you are back.

**Comment by Samara-Strauss** [comment]
ANOTHER UPDATE!!

According to Alastair [via Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1643405460345419?thread_ts=1643395405.843779&cid=C018V2JCWRJ), it sounds like we might be able to make some progress on the backend, but I don't understand enough about how the code works to be able to advise on exact steps. @tpharrison will be coordinating with the mobile folks to figure out what to do from here, and will post an update in his ticket when he has it.

However, it might not make a different either way what the backend does if we want to go ahead and remove this field from the frontend. Does that sound OK to you all? I don't want to do that if it might cause problems I am unaware of, so please do raise concerns if you have them given I am not a code expert and may have blind spots.

cc/ @MarciMcGuireGCIO for awareness.

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO and @Samara-Strauss In the acceptance criteria it shows a feature flag being used, and if we are just removing it from the UI, then I'm not sure it is needed. What do yall think? 

Do you think I could just remove this from the UI without having to add another feature flag to the mix? The only reason I ask is that it adds more code that has to be removed down the road from the backend and the frontend once we decide we no longer need the feature flag.

**Comment by adamwhitlock1** [comment]
I can remove the field and demonstrate its layout in a 'review instance' which is a url that is temporary for previewing changes on a PR if that would help do some pre-deployment validation.

**Comment by MarciMcGuireGCIO** [comment]
Review instance requires SOCKS, right?  I have that, but I don't think Samara is able to get that up and running on her machine

**Comment by Samara-Strauss** [comment]
Re: the feature flag -- Obviously the removal from the backend is no longer an issue, so a feature flag is no longer required for that coordination. However, I want to make sure we have time to review all changes we make before they go into prod, so if the flag is needed for that, we should keep it.

And no, I don't have SOCKS access if that's necessary for the review instance.

**Comment by Samara-Strauss** [comment]
Validated this on staging -- is this going out with today's deploy?

**Comment by adamwhitlock1** [comment]
yes! The feature toggle is currently set to show the gender field on prod, but once today's deploy goes out I will verify the functionality and flip the toggle to hide it.

**Comment by Samara-Strauss** [comment]
YAY! Fantastic!! We should be good to close this, then.

**Comment by MarciMcGuireGCIO** [comment]
Awesome; thank you @adamwhitlock1 !
