### ISSUE TITLE
[Design] Auth Profile: Personal Information Revision - Update mockups to reflect final copy changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36002]
## Background

There were several requests for changes to content that came out of the research study and subsequent meetings.  This issue is update the mockups with the final content as provided by Danielle.

## Tasks
- [x] Update Sketch files to replace placeholder hint text with actual verbiage provided by Danielle
- [x] Remove "Please" from any options if recommended by Danielle
- [x] Remove "preferred" from in front of Pronouns.
- [x] Change Preferred Name field label to 25 characters max vs 100
- [ ] Determine if "first" should be added to preferred name based on user feedback and Danielle's recommendations.
- [ ] Update language around "If not listed, please provide your ___" based on Danielle's recommendations
- [ ] Update language around "(unchecks other boxes)" and additional multi-select instructions based on Danielle's recommendations
- [ ] In read-only state, the commas between values should be changed to semicolons -- see screen shot below.
- [ ] Add comment and @ Marci and Adam so the dependent FE ticket can be unblocked.

![image](https://user-images.githubusercontent.com/73354907/157089221-0292fe2e-93b9-45fe-a186-549ee4c7e8aa.png)

## Acceptance Criteria
- [x] Update Sketch files to replace placeholder hint text with actual verbiage provided by Danielle
- [x] Remove "Please" from any options if recommended by Danielle
- [x] Remove "preferred" from in front of Pronouns.
- [x] Change Preferred Name field label to 25 characters max vs 100
- [ ] Determine if "first" should be added to preferred name based on user feedback.
- [ ] Update language around "If not listed, please provide your ___" based on Danielle's recommendations
- [ ] Update language around "(unchecks other boxes)" and additional multi-select instructions based on Danielle's recommendations
- [ ] In read-only state, the commas between values should be changed to semicolons.
- [ ] Add comment and @ Marci and Adam so the dependent FE ticket can be unblocked.

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO -- I popped into content office hours today to talk with Danielle about small content items from this sprint. She gave the go-ahead on a few things - like removing "please" from our text - but would like us to add some of the other items to our content ticket to discuss further. Here are my notes on what we discussed:

1. Language around "If not listed, please provide your ____." 
    - I can go ahead and remove "please" - also helpful in any future translation context, as the use of please can read oddly in some languages
    - **Add to ticket** - Wants to look into other language options for this sentence, such as not using "provide" and maybe exploring "self describe." 

2. Language around "Prefer not to answer" selection logic. Danielle would like to talk through the instructions for the checkboxes. 
    - **Add to ticket** - She likes that we are including (unchecks other boxes), but wants to explore "choices" or "selections" instead of "boxes." She is also wondering how we can include additional instructions above the list of options to help clarify multiple selections can be made.

3. Preferred name - do we add "first"? 
    - **Add to ticket** - Danielle has been working on something similar with Dené on this so wants to look at what they've already worked through and see how that can apply. 

4. Pronouns
    - The change we made to "Edit your profile to add pronouns" is good ("a pronoun" changed to "pronouns"). No need to include "your."

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! Want to double check that you saw the information above with Danielle's items to add to the content ticket - and also that I put it this all in the right place. Let me know if you'd like me to include it somewhere else instead. Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Good morning! I did, and it looks great! Thank you!

**Comment by MarciMcGuireGCIO** [comment]
I will add them to her Content ticket when I add new tickets after my 1:1 with Samara this afternoon

**Comment by MarciMcGuireGCIO** [comment]
Moving this to Sprint 68; could not complete all items due to dependency on Content.

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO -- I added two tasks to this ticket so it now includes all three of the new content items Danielle will address.

**Comment by MarciMcGuireGCIO** [comment]
Moving remaining copy-related tasks to ticket #38126
