### ISSUE TITLE
[FE] Auth Profile - Personal Info Revision: Update UI to reflect final content changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36006]
## Background

These are the final content changes that need to be updated on Staging. 

## Tasks
- [x] Update [FAQ 1](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4aqKkWz) and [FAQ 2](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/OmjMy8G)
- [x] Add hint text to fields ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/eKYxzDm))
Preferred Name - regular hint text 
Gender identity - additional information component dropdown & expanded text
- [x] Change the order of selections in Gender identity edit state ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/JnVgyK0))
- [x] Add (*Required) in edit states for both Preferred name ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ZODxpjY)) and Gender identity ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/JnVgyK0))

## Acceptance Criteria
- [x] Make updates
- [x] Let PM know once changes are on Staging for review

**Comment by Samara-Strauss** [comment]
Just noting that this will likely need to go into sprint 68 depending on when all copy updates are finalized.

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 - I've updated this ticket to consolidate all the outstanding content-related tasks, so please review and estimate based on these changes.  Thank you!

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 I added this to sprint 71, but it looks like the main description in this ticket needs to be updated with the actual content updates. Marci's description is now out of date. I don't have time to do this before planning, but we'll get it done before you tackle the ticket.

@cgednalske can you please outline here what content updates @adamwhitlock1 needs to make now that content is complete? I can update the description based on that.

**Comment by cgednalske** [comment]
@Samara-Strauss @adamwhitlock1 should the content updates I list here be for the initial fields of Preferred name and Gender identity only or all fields?

**Comment by cgednalske** [comment]
@adamwhitlock1 @Samara-Strauss  Most of the changes above are outdated. For the initial fields of Preferred name and Gender identity, here are the updates I see:
- Update [FAQ 1](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4aqKkWz) and [FAQ 2](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/OmjMy8G)

- Add hint text to fields ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/eKYxzDm))
Preferred Name - regular hint text 
Gender identity - additional information component dropdown & expanded text

- Change the order of selections in Gender identity edit state ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/JnVgyK0))

- Looks like (*Required) should also be added in edit states for both Preferred name ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ZODxpjY)) and Gender identity ([Sketch file](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/JnVgyK0))

Everything else looks good!

**Comment by adamwhitlock1** [comment]
> @Samara-Strauss @adamwhitlock1 should the content updates I list here be for the initial fields of Preferred name and Gender identity only or all fields?

I'd say starting with the Preferred Name and Gender Identity is fine, and once we have approval for the other two, then we can double check them.

**Comment by Samara-Strauss** [comment]
I updated the first comment in the ticket to reflect the needed content updates. Thanks for outlining this, @cgednalske.

**Comment by adamwhitlock1** [comment]
@SKasimow I have finished this work and it is available on staging for validation. The only thing that wouldn't be available to validate is the *Required on the field due to data not being present from the api at this time. I do have E2E tests built to validate that functionality.

**Comment by Samara-Strauss** [comment]
@cgednalske can you actually validate this ticket for @adamwhitlock1 since @SKasimow is likely not familiar with what the copy should be? Thank you!

**Comment by cgednalske** [comment]
@adamwhitlock1 Just two little things with the copy. Otherwise looks great! 👏   And I'm not at all minding the new dropdown component. It looks clean with the line underneath and not too close to the sidebar.

- In the first FAQ dropdown, it says _you_ instead of _your_ in "If you’ve changed _YOUR_ legal name, you’ll need to tell us so we can change your name in our records." 

- The Preferred name hint text on staging says "when you come in to _THE_ VA." and Danielle's says "when you come in to VA." Not sure if this matters or not. @Samara-Strauss and @SKasimow I was wondering about this overall as well because I've seen it both ways...should it be THE VA, just VA, or are they both used?

**Comment by Samara-Strauss** [comment]
>  I was wondering about this overall as well because I've seen it both ways...should it be THE VA, just VA, or are they both used?

This is a great question -- for any website content, it should just be "VA" with no "the." This is because VA, obviously, stands for "Veterans Affairs", so it doesn't make sense to say something like "When you come in to THE Veterans Affairs...".  Now, of course, we colloquially say "the VA" all the time, and I'm not policing what anyone says on the team in conversation or in Slack. But, in terms of website content, "VA" is correct and "the VA" is not.

**Comment by SKasimow** [comment]
Good catches @cgednalske!

@adamwhitlock1 - I noticed one of the left-side margins seems to be longer than others:

[Screen Shot 2022-04-15 .pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8496391/Screen.Shot.2022-04-15.pdf)

**Comment by adamwhitlock1** [comment]
The changes that were requested have been deployed to staging. @cgednalske let me know if you see anything else that I should change.

**Comment by Samara-Strauss** [comment]
Just validated this since Christina is out. This is good to close.
