### ISSUE TITLE
[Documentation] Procedures should include how to deal with access request expiration dates

### ISSUE THREAD

**Issue by td-usds** [department-of-veterans-affairs/va.gov-team#36004]
## Description
Our docs and procedures should reflect how we ensure that timed access requests are revoked at the right time.

## Background/context 
Our Environment Access Request issue template will start asking requestors to enter a sunsetting date for their access requests. This sunsetting date needs to be incorporated into our SOPs.

---
## Tasks
- [x] Come up with how ops wants to deal with this extra field
- [x] Update documentation on how ops will deal with this extra information
- [x] Ensure new SOP is implemented

## Acceptance Criteria 
- [x] Time-scoped access requests are filed with sunsetting dates provided and the granted access is revoked by the Ops team upon hitting that date (start of provided date) without any other entities needing to prod ops.

**Comment by oseasmoran73** [comment]
With the new [AWS Access Request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/aws-access-request.yml) there is a section for `Access Expiration`.

Access request will follow standard procedure (requiring approval from the security team)

Infrastructure will revoke access on date provided and the procedure is documented in the following places:

- [Onboard New Team Members (Granting Access to Internal Tools)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#Access-Expiration)
- [Approve AWS Access](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access#Access-Expiration)

Relevant tickets pertaining to new AWS request template can be found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/31272

@td-usds Closing out this ticket as requirements have been met. Feel free to reopen or ask questions!

CC @jhouse-solvd
