### ISSUE TITLE
[BE] Auth Profile: Remove call to retrieve gender from Personal/Contact information page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36011]
## Background

User research found that people who identify as transgender may be triggered or offended if their gender/sex assigned at birth is displayed on their VA Profile.   This will need to be coordinated with Adam since the field also needs to be removed from the UI on the front end.

## Tasks
- [ ] Create a feature flag to keep this on Staging until it is ready for Prod
- [ ] Remove gender from existing combined personal/contact information page in VA.gov Profile
- [ ] Test and peer review
- [ ] Update PM once it's merged and ready for validation on Staging.

## Acceptance Criteria
- [ ] Create a feature flag to keep this on Staging until it is ready for Prod
- [ ] Remove gender from existing combined personal/contact information page in VA.gov Profile
- [ ] Test and peer review
- [ ] Update PM once it's merged and ready for validation on Staging.

## How to configure this issue
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
**Note from 1/29 chat**: Before this goes live, we need to coordinate with the mobile app team on removal of this field from their app.

**Comment by Samara-Strauss** [comment]
ANOTHER UPDATE!!

According to Alastair [via Slack](), it sounds like we might be able to make some progress on the backend, but I don't understand enough about how the code works to be able to advise on exact steps. @tpharrison, can you please coordinate with @kreek and @travis-newby as necessary, and pull in Lihan if needed? And when you have a plan, please post in this ticket what next steps have been agreed on by all parties? Thank you!

cc/ @MarciMcGuireGCIO for awareness. I'll pull the ticket back into this sprint.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @tpharrison !

**Comment by Samara-Strauss** [comment]
Thank you, @tpharrison! I am going to close this ticket and consider it complete for the sprint even though our scope changed. Thanks for leading this discussion!
