### ISSUE TITLE
VSA Technical Orientation Doc Updates

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36010]
## Issue Description

In preparation for the newly hired developers the VSA Technical Orientation [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/onboarding/VSA%20Technical%20Orientation.md) used for onboarding should be updated using current information.

---
## Tasks
- [ ] correct any outdated information

## Acceptance Criteria
- [ ] all information presented should be current and correct

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
