### ISSUE TITLE
526: Reorder pages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36028]
## Description

Move a few pages within Form 526 around to organize the flow a bit more.

- Flow diagram: https://app.mural.co/t/vsa8243/m/vsa8243/1639070794497/b605ba85a76c75be7d195bd4090286b6e8061453?sender=kstachura1551

## Tasks

- [ ] Reorder 526 page to match design
- [ ] Ensure page dependencies don't break, i.e. one page _must_ come before another

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
This work was not done this sprint. We need to discuss the flow changes and if they need to be behind a feature flag. Putting the changes behind a feature will increase the amount of changes required to finish this work.

**Comment by saderagsdale** [comment]
- Previous team thought we could optimize the form, but this is just a hypothesis. 
- Needs research and design focus.
- Place on hold and attached to any related investigations.
