### ISSUE TITLE
Test FSR notification sending on staging environment

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#36021]
## Issue Description
Once the template has been created and uuid has been added to settings we need to run through staging to test the process works as desired.

---
## Tasks
- [ ] Use dev user account to test FSR submission and view email

## Acceptance Criteria
- [ ] As a user, once my FSR has been submitted on staging I have received an email
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
