### ISSUE TITLE
VRE: Find out why VBMS requests fail and Look into rescheduling VBMS uploads

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36036]
## Background
Since VR&E informed us that some PDF's they do not see in CMP, see if we can reschedule the VMBS/1900 job (3 hours later for starters) if VBMS is down for maint, or it's just down. But if there's a legit error, we need to handle that.

## Tasks
- [x] Investigate a potential cause for VBMS being down
- [x] Establish what changes might need to be implemented (in a list)

## Acceptance Criteria
- [ ] A cause has been identified, or
- [x] Next steps have been established in either GH or tickets

**Comment by jason-gcio** [comment]
Next steps
1) address the CMP
2) Improve VBMS conversion (downtime check)
