### ISSUE TITLE
Pre-need Burials Support Request

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36030]
## Issue Description

Update from @megansiddle 7/24/22:  I couldn't tell from reading the details if the form still does get submitted or if it never does? We were going to be working on the 40-10007 form next and I typically utilize the submission page for the forms to help build the content for the email. I get that error message that says the form can't be submitted at this time. I'm wondering if we should not be working on this form until that bug is resolved. OR would it be helpful to actually do the email confirmation so the user is aware the form did work?

Veterans are experiencing issues with the pre-need burials application
![image (15)](https://user-images.githubusercontent.com/10838260/181013676-f264072b-7e3f-42db-9c4f-84d6e841020b.png)

---
## Tasks
- [ ] Troubleshoot 2 issues:

1. Claimants submitting requests through VA.gov are not receiving the receipt notifications and in turn, are calling to ensure requests are received. Also, as a result of the auto receipt message not being delivered, claimants are submitting multiple requests. In some cases we are receiving 5 to 10 duplicate requests, due to customers continuously clicking submit, not knowing if the request went through.
 
2. Extremely large number of requests submitted via VA.gov, that do not have documents attached. Upon the employee being assigned the case in EOAS, they are noticing that no documents are attached.

## Acceptance Criteria
- [ ] Issues resolved and @megansiddle notified. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
On a quick run through of the form on staging, I encountered a few issues:

- https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/
  - Respondent burden text shown throughout the form - this should be part of the OMB info component showing the time, OMB control number, expiration date and privacy act statement info
- https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/burial-benefits:
  - I couldn't add a VA national cemetery. It's not required.
  - Adding one, even prefilled from pasting in data from the save-in-progress menu, shows an error "Please select an option from the suggestions"
  - The auto-suggest isn't working, but maybe it's just not working in the staging environment.
- https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/supporting-documents
  - File uploads take a significant amount of time (~140kb PDF took over 1.5 minutes)
- https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-contact-information
  - The street address is limited to 20 characters. The prefilled address was longer, so I had to delete some of it to progress
  - Telephone & email was not prefilled
- https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/review-and-submit
  - Supporting documents accordion/additional info style is broken
  - I was not able to submit the form in staging. A 500 (internal server error) was returned from the process

**Comment by Mottie** [comment]
I checked in production on my personal account:
- The VA national cemetery autocomplete does work
- The file upload was much quicker (same ~140kb PDF took 9 seconds)

**Comment by michelpmcdonald** [comment]
I've been working with eoas on the large number of burial requests that don't have any documents attached.

I could not find an vets-api(backend) obvious issue that would result in vets successfully attaching documents to in-progress burial requests(vets-website) and vets-api sending the request to eoas without the expected documents attached.

The burial request call to eoas is a multipart soap call that includes the form data and the attached documents.  The documents are saved in s3 while the vet is creating the burial request on the website.  Once the vet hits the submit button on the website, vets-api build a soap packet using the form data AND pulls the attached files from s3 and adds the file data to the soap request.  The code looks like it is structured so that any errors encountered while building the soap packet would result in the code terminating and the actual call to eoas would not be sent.  So, for example, if an error was hit trying to read the attached file(s) from s3 while building the soap message, vets-api would log the error and terminate, no call to eoas and the vet would see an error on the website indicating that their request hit an error.

So far, I've been unable to see anything on my end that indicates there is a problem of vet-api failing to attach files that vets were able to successfully attach to their burial requests using the va.gov website.  

The real answer to this question would be to capture the raw outgoing soap message from vets-api to eoas and see if the soap packet has empty file sections.  I've reached out to support, and they currently don't have any packet capture solutions avail on production.  I'm thinking of tools like wireshark or tcpdump.  Support is looking into getting my request approved, but no ETA or even guarantee it will be approved.

I could add additional logging in the code.

The issue could be on the web side also, errors on the web side when attaching files **might** not make it to the backend, so vets-api would not necessary be aware of vets being unable to attach files using the website.

**Comment by Mottie** [comment]
I just realized that this ticket doesn't specific if the problem is with the pre-needs (Form 40-10007) or burial (Form 21-530EZ). Both allow uploading of supporting documents. I don't think we thought to check the burial form.

**Comment by MichelleDieudonne** [comment]
@vhenry07 Can we please get this GitHub closed.  This item has been fixed and here is the associated GitHub item: https://github.com/department-of-veterans-affairs/vets-website/pull/23809. Thank you!

**Comment by Mottie** [comment]
Veronica is no longer on this contract. Please feel free to close issues if you feel that they have been overridden by another ticket, or resolved.
