### ISSUE TITLE
Integration Experience Team access issue in Zenhub

### ISSUE THREAD

**Issue by CosmicSyntax** [department-of-veterans-affairs/va.gov-team#36031]
## Description
On Zenhub, a number of our team members do not have the proper access in github / zenhub to be about to create issues and add labels directly in zenhub. Team members affected and need access:
1. @CosmicSyntax 
2. @rogersarkis 
3. @considerable 
## Background/context 
Each team member of integration experience all have different permission. We would like all team members to have the same access to @ewilson-adhoc 
## Technical notes
N/A
---
## Tasks
- [ ] Each user mentioned in 'Description' have the same access as the user mentioned in 'Background.'
## Acceptance Criteria 
- [ ] See Task
---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
