### ISSUE TITLE
[BE] vets-api check-in: Remove unneeded feature flags

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#36057]
## Description
There are a few feature flags that are no longer needed and can be removed. We still need to be validate and confirm with FE and Product team. Here's a candidate list:
* `check_in_experience_chip_service_nok_confirmation_update_enabled`
* `check_in_experience_demographics_confirmation_enabled`
* `check_in_experience_emergency_contact_enabled`

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [ ] work with FE and PO team to confirm that those flags are no longer needed
- [ ] update code and remove those flags

## Acceptance Criteria

- [ ] Deployed and tested on staging.
