### ISSUE TITLE
[Page Update] Update Post 9/11 GI Bill Education page for verfication [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36056]
## Story
As a Veteran, caregiver, and family member I need updated information regarding me education enrollment, so I will have the most relevant information when submitting my information.

## Resources
[Post 9/11 GI BIll Page](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fva.gov%2Feducation%2Fabout-gi-bill-benefits%2Fpost-9-11%2F&data=04%7C01%7Cstan.gardner%40gcio.com%7C5a6466b9a8bd4878676108d9e110b2aa%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637788284142298307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gcExbRGtx2jXETKGwffV9lxnREd8l1i68VhCOEdch0g%3D&reserved=0)
- See original email text below.

## TASK
- [ ] Review and research changes to original page
- [ ] Make updates and save page to published.
- [ ] Have Customer confirm changes.

## Acceptance Criteria
- [ ] Page is updated and there are no broken links or errors.  
- [ ] Update is sent to customer for review

**Comment by SgardnerPMP** [comment]
See customer request attached   ![SWC_36056.png](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/eb04f32c-1756-466f-a31e-a4b16df9af82)
