### ISSUE TITLE
Letters: Fix linting issue

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36053]
## Description

Accessibility linting rules are being enabled, and two linting errors popped up within the letters app

In `/src/applications/letters/containers/VeteranBenefitSummaryLetter.jsx`
- 94:15  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
- 137:13  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control

## Tasks

- [ ] Fix a11y linting errors in the claim status tool
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
So the problem is that a table is being displayed. The checkbox itself is in the left column and the associated label text is in the right column

<img width="737" alt="rendered table row & HTML showing 2 labels for one input" src="https://user-images.githubusercontent.com/136959/152234427-bc4a6f08-c52d-456d-9a9c-d12e9727cc44.png">

The first label is necessary to rendered the stylized checkbox, the second associates the text with the input. Both labels are clickable.

We need to determine how to optimize this pattern so it works with screenreaders.
