### ISSUE TITLE
NOD: Hide WIP alert while loading feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36068]
## Description

When loading feature flags, the Notice of Disagreement work-in-progress alert is shown instead of a loading indicator.

## Tasks

- [ ] Show loading indicator while feature flags are being loaded
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
