### ISSUE TITLE
Backend Onboarding: Monitoring and Error Handling

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36069]
## Issue Description
For backend engineers, they should have access to the proper tools, and the ability to set up monitoring for errors across different features so that we can respond quickly and efficiently in diagnosing and resolving issues. We should not hear about errors or issues via Twitter 🙃

Considerations
Grafana + DataDog
integrations into #vsa-claimsandappeals-alerts (Slack)
a version that shows totals vs successful vs failed submissions would be helpful for KPIs and other success metrics, not just red alerts

---
## Tasks

- [ ] Request accounts and/or access to DataDog and/or Grafana
- [ ]  Setup an initial dashboard and test it
- [ ]  Integrate monitoring into Slack for awareness (#vsa-claimsandappeals-alerts)
- [ ]  Share outcomes with Claims & Appeals team
- [ ]  If able, steps have been shared to create other dashboards for other features

## Acceptance Criteria

- [ ] Access has been requested
- [ ]  A dashboard for at least one feature is stood up
- [ ]  Error messaging is found in the correct Slack channel, as needed
