### ISSUE TITLE
[FE] Store Current App in Redux 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36063]
## How to configure this issue

- [x] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Add the app type to the reducer and update everywhere where isPreCheckin is used to use this value instead of a passed static value.

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] On app load store which app is loaded 
- [ ] Refactor the code to use the redux value instead of hardcoded values 
- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
Going to close this one because no issues have been reported.
