### ISSUE TITLE
Schedule Pain Point Artifact Workshops with Platform Teams PMS

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36079]
## Issue Description
  As a SD team PM I want to schedule workshops with Platform teams PMS so our team 
  can do feasibility and usability testing to come up with Final draft for Pain point 
  artifact.

---
## Tasks
- [x] Schedule workshop meeting with all 15 platform teams PMS

## Acceptance [Criteria]
- [x] workshop meeting invites are sent to all 15 platform teams PMS
             Link to [Workshop planning](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2068676654/Pain+Point+Tracker+Artifact+Workshop+Planning+1+27+22) 
       
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
