### ISSUE TITLE
Work with Platform Content Team to find an appropriate place on Platform Website  for these artifacts to live

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36080]
## Issue Description
 As a SD team member I want work with Content Team to find out an appropriate place for   Pain point artifact so that everyone on VA can easily access it

---
## Tasks
- [ ] Reach out to content team for help
- [ ] Get approval from Content Team
- [ ] Get approval from Thomas and Andrea

## Acceptance Criteria
- [ ] Artifact place is decided and approved by Thomas
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
3/11/2022
We had a leadership alignment meeting with the team on 3/9/2022 regarding the scope change and the decision was made not to continue with the above initiative and instead apply learning from it to develop a roadmap for Q2 2022.
