### ISSUE TITLE
Collect customer satisfaction ratings - Launch Q1 2022 Platform Satisfaction Survey

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36087]
## Issue Description
Launch the Platform satisfaction survey to VFS team members so we can measure Q1 2022 customer satisfaction and gather feedback to inform quarterly planning

[Instructions](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)

---
## Tasks
- [ ] Setup study in optimal workshop
- [ ] Announce in Slack
- [ ] Recruit respondents in Team of Teams and other channels

## Acceptance Criteria
- [ ] We have a survey response rate ~20%. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
2/7:
Jonathan and Marissa launched the Survey for Q1 2022

**Comment by Khyatinp18** [comment]
2/8:
Taylor will explore what other channels we can follow up and when for Survey before closing the survey

**Comment by Khyatinp18** [comment]
2/9:
We will close survey on 2/15 on Tuesday. 
I will remind in TOTs - Khyati
We will follow up with reminders in other slack channels

**Comment by tayism** [comment]
I will post reminders on Thursday and Monday in these channels:
#vfs-all-teams
#design
#vfs-analytics
#vfs-backend
#vfs-benefits
#vfs-frontend
#health-care-products-all-teams

**Comment by tayism** [comment]
Average time to complete the survey is 2 1/2 minutes. I will update messaging to reflect this to teams.

**Comment by tayism** [comment]
Sent final Slack channel reminders yesterday and today. Khyati also mentioned in ToT + direct support from Rachael (PO)

**Comment by tayism** [comment]
We need ~46 responses to reach our 20% response rate goal.
