### ISSUE TITLE
Facilitate workshops with Platform teams to fill out current work that's addressing customer pain points

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36082]
## Issue Description
  As a SD team member I want to conduct work shops with Platform teams so that I can 
  research or discover (and document) what initiatives Platform teams are working on and 
  why it's being prioritized (i.e. Quarterly insights)

## Tasks
- [x] Planning: Taylor, Marissa, Jonathan
- [x] Creating Mural (Team will use during sessions) - Jonathan
- [x] Prep work before working session (DM groups before sessions) - Taylor, Marissa
- [x] Notetaking - Taylor
- [x] Facilitating - Jonathan
- [x] Troubleshooting/Mural board/Deciphering/Documenting/Parking Lot - Screenshots - Marissa
- [x] Workshop debrief - 15 mins after meetings or by EOD - Marissa will schedule

## Acceptance Criteria
- [x] Validate that Service Design team has proper feedback from platform teams so that next sprint team can start synthesizing and iterating on the deliverable 
 [Link to Documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/edit-v2/2068676654)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
2/4:
Marissa, Taylor and Jonathan working on the Mural (Used during Sessions)

**Comment by Khyatinp18** [comment]
2/7:
Marissa will sent out DM to all 5 groups before working session with Jonathan's help

**Comment by Khyatinp18** [comment]
2/8:
Team will finalize the Mural board during design sync

**Comment by Khyatinp18** [comment]
2/9:
Conducted Group 1 working session

**Comment by tayism** [comment]
Updated tasks list to reflect our current work
