### ISSUE TITLE
Draft guidance for VFS teams on Core CC template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#36085]
## User Story
As a VFS team, I want clear guidance provided on the Core Collaboration Cycle ticket process so that I understand the changes and my responsibilities.

*This ticket and ticket #36086 should be worked on together.

- Intended Audience: VFS Teams
- Desired Outcome:  
  - VFS Team guidance documentation details actions and information for each relevant touchpoint
  - VFS Team understands Platform's role and expectations
- Due Date: Drafted pages by 4/26 research readout

## Description
With the switch to the new Core Collaboration Cycle ticket template in GitHub, VFS teams are going to need guidance on how the Core CC template works in comparison to the old process. In addition to updating the Platform Website touchpoint pages that impact the request process, VFS teams will need guidance detailing the new process. Ideally, this can be the Collaboration Cycle Kickoff page as this is the first interaction point in the Collaboration Cycle.

The updated Collaboration Cycle kickoff page should continue to have the necessary kickoff questions, but also explain the purpose, value and benefits of the Core CC template, how requesting reviews will work, how labels will work, the Outcome of each review (AKA feedback...this can point to the specific touchpoint pages), closing/tracking the ticket, and any other information VFS teams will need related to the Core CC template and the Collaboration Cycle.

Note: Do not publish any of the modified pages when this ticket is complete. The documentation impacted by this ticket will be used in usability testing of the Core CC template with VFS Product Managers (and potentially POs and/or Designers).

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Tasks
- [ ] Refer to ticket #36086 with tasks necessary for this ticket

## Acceptance Criteria
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@allison0034 @CherylEvans @jimuhh  - @chaseakirby and I spoke and decided to merge this ticket with #36086. Please only refer to ticket #36086 for updating operation and VFS-facing guidance.
