### ISSUE TITLE
Update form routers to be compatible with v5

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36088]
## Description

Platform is planning on updating react router to v5+, and [incompatibilities need to be addressed within the forms we support](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34572#issuecomment-1016643583):

 | Done?  | App              | Route definitions | Additional deprecations |
 |---| -----------------| ----------------- | ----------------------- |
 | ❌ | appeals/10182 | OLD-FORM | indexRoute, childRoutes, withRouter, old import | 
 | ❌ | burials | OLD-FORM | indexRoute, childRoutes |
 | ☑️ | claims-status | NEW | IndexRedirect, IndexLink, nested child routes, withRouter, old import |
 | ❌ | disability-benefits/996 | OLD-FORM | indexRoute, childRoutes, old import |
 | ❌ | disability-benefits/all-claims | OLD-FORM | indexRoute, childRoutes, old import |
 | ☑️ | letters | NEW | IndexRedirect, nested child routes, old import |
 | ❌ | pre-need | OLD-FORM | indexRoute, childRoutes |

Note:
- Apps marked as OLD-FORM use deprecated route definitions generated by the forms library. These apps cannot be updated to use the new react-router until the Design System team modifies the forms library route generation logic. **This [Design System support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469) covers the required updates.**
- Apps marked as NEW already define their routes using the new component approach. They do not require route definition changes.

## Tasks

- [ ] Update "OLD-FORM" forms once the Design System Team has completed their update
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by sortizsh** [comment]
@Mottie  based on comment above Squad 1 will wait for further direction.

**Comment by Mottie** [comment]
Squad 2 is waiting as well

**Comment by saderagsdale** [comment]
@sortizsh @Mottie moving this to the product backlog. If we're unable to action on tickets and it isn't mission-critical work let's not keep it in the blocked swimlane.

**Comment by AlexanderSherrow** [comment]
Was this story ever addressed or still in the backlog? @Mottie @saderagsdale

**Comment by Mottie** [comment]
It's still in the backlog. The team that was working on migration didn't have enough time before their contract ran out. So it's now sort of in limbo. We're currently stuck with these versions:

>  "react-router": "3",
>  "react-router-dom": "^5.3.0",
>  "react-router-dom-v5-compat": "^6.3.0",
>  "react-router-last-location": "^2.0.1",

**Comment by AlexanderSherrow** [comment]
@Mottie @taylorkaren So for my understanding based upon the prior comments above, the React Router upgrade from v3 to v5 is unnecessary as the pages that involve router v3 are going to be rewritten anyways?(Do we have a time frame on that process?) Apologies, I do not have access to the confluence pages.

**Comment by MichelleDieudonne** [comment]
Memorials Self-Service Jira Work Item - https://jira.devops.va.gov/browse/MBMS-38244

**Comment by MichelleDieudonne** [comment]
Closed based on answers given from the Platform team in this thread.  https://dsva.slack.com/archives/CBU0KDSB1/p1679493582438199
