### ISSUE TITLE
Synthesize feedback from Q1 2022 Platform satisfaction survey

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36089]
## Issue Description
Synthesize results from Q1 2022 Platform satisfaction survey and prepare the readout so we can share the findings with stakeholders to inform quarterly planning.

---
## Tasks
- [ ] Calculate satisfaction score
- [ ] Copy survey feedback into mural board
- [ ] Group feedback into categories/themes
- [ ] Define feedback themes and select representative quotes
- [ ] Complete Q1 2022 customer insights deck
- [ ] Present deck in end of sprint demo and post in platform-team channel

## Acceptance Criteria
- Platform teams and OCTODE are using survey findings to define/refine initiatives and OKRs.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tayism** [comment]
Working on mural board for group synthesis. Group Synthesis workshop on Wednesday.

**Comment by tayism** [comment]
Synthesis is complete and key themes have been established. This information has been transferred to the [2022 Feedback Themes Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1645655432415/26f1766bc490b410bff347eb2d97e4904d090f79?sender=u9ea6bd3ca12795949b606150)
