### ISSUE TITLE
Create process for Platform teams to digest this artifact (update quarterly planning playbook)

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#36081]
## Issue Description
As a SD team member I want to create a process for Platform teams so that they can keep this artifact updated
---
## Tasks
- [ ] Define the process for Platform PMs
- [ ] Document the process which is easy to to find and follow
## Acceptance Criteria
- [ ] Validate process is created and documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
3/11/2022
We had a leadership alignment meeting with the team on 3/9/2022 regarding the scope change and the decision was made not to continue with the above initiative and instead apply learning from it to develop a roadmap for Q2 2022.
