### ISSUE TITLE
GIBCT Database Reversions 

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#36091]
## Description
Issue has been observed in which something is causing the GIBCT production database to be reverted routinely

## Background/context 
- https://dsva.slack.com/archives/CBU0KDSB1/p1642703108065800
- https://dsva.slack.com/archives/CBU0KDSB1/p1643296340610549
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/35791

## Technical notes
Please provide number of users and level of impact:

---
## Tasks
- [ ] Figure out what is causing the database to be reverted
- [ ] Remove / resolve / mitigate thing that is causing the database to be reverted

## Acceptance Criteria 
- [ ] GIBCT deployments in full working order without unintended database reversions 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Current production deployment details:

![image](https://user-images.githubusercontent.com/56260532/151408801-a249633d-944f-4539-970b-8b0aaf42e7fc.png)

**Comment by RileyRPM** [comment]
Thanks @jbritt1 ... Tracking

**Comment by rileyanderson** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36095

**Comment by jbritt1** [comment]
If I understand https://dsva.slack.com/archives/CBU0KDSB1/p1643303778203149 correctly, it brings up some questions in my mind....

 - Why is there a dashboard button somewhere that has the power to revert a production database?
 - How can we be sure someone isn't clicking that button after every time we run the scripts that fix the issue?
 - Are there any controls or auditing capabilities on this button to see if it is being pressed and by who?

**Comment by mrblanco1** [comment]
Hi @jbritt1: EDU is the only entity that uses this functionality/button. Your questions are great questions, I am sure Joe Preisser and/or Brian Grubb can answer them since they are the only two people I know of using this "button". I do not think they are part of GitHub in case you would like to reach out to them.

**Comment by mrblanco1** [comment]
> I think this is resolved at this time. Agreed @mrblanco1 ?

Yes, this issue has been resolved.  Thank you!
