### ISSUE TITLE
Remove login_old_design flipper feature

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#36099]
## Issue Description
Since the new login design has been validated in production, we should remove any related code to the `login_old_design` feature flag. 
## Tasks
- [ ] Ensure `vets-website` has no dependent code on `login_old_design`
- [ ] Remove `login_old_design` from `vets-api` features

## Acceptance Criteria
- [x] login_old_design is no longer a flipper option
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
