### ISSUE TITLE
[Infrastructure Team] Update assets and communications channels with new team name

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#36097]
## Issue Description
The recent Platform team reorg has been designed to reduce cross-functional team dependencies as well as create more accurate team names aligning to the products they support and own.

The team name has changed from Operations to Infrastructure Team, this will need to be updated in our documentation.

---
## Tasks
- [x] Rename Confluence Space from "Operations Team" to "Infrastructure Team" (Confluence should automatically update links)
- [x] Rename "Operations Team" to "Infrastructure Team" on Confluence pages
- [ ] Update Platform Website (as needed)
- [ ] Update Orientation materials/PowerPoints
- [ ] Update Slack channel names (OCTO-DE) from vsp-operations{,-internal} to ??? 
  - [ ] Need to determine new slack channel name(s)
  - [x] open channel - #platform-infrastructure
  - [ ] team channel - _#todiscuss_
    - [ ] May need to reconfigure bots
- [ ] Update Support Slackbot team name #38352
- [ ] GitHub 
  - [ ] Team label from `operations` to `infrastructure`
  - [ ] Update GitHub templates with new label
  - [ ] GitHub Operations team rename to Infrastructure team
- [x] Update Zenhub board name to "Platform Infrastructure Team" 
- [ ] Uncover other places/spaces where Operations team name would be listed.
- [x] Update Roadmap/Vision (Jesse, please verify if this is needed)
- [ ] Team member Slack profiles 
Format: [Crew name] / [team] - Role [Org Name]
Example: Platform / Product Support - Product Manager [Oddball]
  - [x] Rebecca @rmtolmach 
  - [x] Oseas @oseasmoran73 
  - [x] John @jsgarmon 
  - [x] Jeremy @jbritt1 
  - [ ] Matt @mleclerc00 
  - [x] Kyle @ph-One 
  - [x] Jesse @jhouse-solvd 

Some items pulled from the list located in this [Team Restructure document by Andrea ](https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1920434211/Potential+VSP+Tech+Teams+Restructure)in Step 4.

## Acceptance Criteria
- [ ] Documentation will refer to the team as Infrastructure Team
- [ ] Teams are able to reach out to Infrastructure Team through slack and slack bot

**Comment by jhouse-solvd** [comment]
Updating Support Slackbot team name in #38352
