### ISSUE TITLE
Refactor the keepAliveSSO

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#36113]
## Issue Description
After a discussion with the IAM team, we are shifting away from using the `authncontextclassref` headers as the definitive source of truth.  The FE will use the following exposed headers to generate and pass into the `auth` context during AutoSSO:

1. `csp_method`
2. One of `aal`, `ial`, or `loa`

---
## Tasks
- [ ] Refactor the `authn` lookup in the `keepAliveSSO` to not use the `authncontextclassref` for ID.me or Login.gov
- [ ] Talk with BE members to see what they expect for each `authn` context
- [ ] Generate `authn` based on the above headers
- [ ] Update unit tests if required

## Acceptance Criteria
- [ ] As a user when signing in on Login.gov, navigating to VA.gov, I am automatically signed in
- [ ] As a user when signing into eauth/accessva's VHIC with ID.me, and navigating to VA.gov, I am automatically signed in
- [ ] As a user when signing into eBenefits (DS Logon), navigating to VA.gov, I am automatically signed in
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras work is already completed. Closing.
