### ISSUE TITLE
[] UX QA Process

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36115]
# Description
Zach to sync with Tze-chiu Lei to understand currently available QA processes and tools.

# Tasks
- [ ] Meet with Tze
- [ ] Think through if any current tools or process could help check-in

# Acceptance Criteria
- [ ] Have a list of options/a proposal

**Comment by loripusey** [comment]
Met with Tze on 10/6/2022 and talked through the Shared-Support-QA team's process.
- They are in the process of documenting the [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/README.md).
- This is the Test Rail [project ](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)that contains the test cases originally created for our team by Tze. FYI, Tze is in the process of renaming everything that had "PTEMS" in the name.
- There is a channel in the AdHoc Slack space called #va-applications-shared-support-team that is currently being used by the Shared-Support-QA team. Tze is going to get me access to that.
- There is an [org chart](![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/ffdfaeb0-bcf0-4e48-889b-78f1a6c599c5)url) that Tze mentioned for roles for each team. Tze mentioned that our team needs to get him a list of these roles for our team so that he can add them to the org chart. I requested access to the org chart.
- Our team's next step to get prepared for Staging Review for Travel Reimbursement - MVP is to 
    - Update our test cases
    - Create a Shared-Support-QA ticket so that Tze can create the TestRail test cases for us (we need to do this at least 2 sprints before Staging Review)

I propose we take the following actions:
    - Do a one-time effort to update our test cases to match what is in production and what we have planned for travel MVP (Lori will do)
    - Create a Shared-Support-QA team ticket once test cases are up-to-date (Lori will do)
    - Create a new template for this effort to be done for every Epic (unless not needed) - DONE [new template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/check-in-experience-development-update-test-cases.md)

**Comment by loripusey** [comment]
Met with Tze on 10/6/2022 and talked through the Shared-Support-QA team's process.
- They are in the process of documenting the [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/README.md).
- This is the Test Rail [project ](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)that contains the test cases originally created for our team by Tze. FYI, Tze is in the process of renaming everything that had "PTEMS" in the name.
- There is a channel in the AdHoc Slack space called #va-applications-shared-support-team that is currently being used by the Shared-Support-QA team. Tze is going to get me access to that.
- There is an [org chart](![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/ffdfaeb0-bcf0-4e48-889b-78f1a6c599c5)url) that Tze mentioned for roles for each team. Tze mentioned that our team needs to get him a list of these roles for our team so that he can add them to the org chart. I requested access to the org chart.
- Our team's next step to get prepared for Staging Review for Travel Reimbursement - MVP is to 
    - Update our test cases
    - Create a Shared-Support-QA ticket so that Tze can create the TestRail test cases for us (we need to do this at least 2 sprints before Staging Review)

I propose we take the following actions:
    - Do a one-time effort to update our test cases to match what is in production and what we have planned for travel MVP (Lori will do)
    - Create a Shared-Support-QA team ticket once test cases are up-to-date (Lori will do)
    - Create a new template for this effort to be done for every Epic (unless not needed) - DONE [new template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/check-in-experience-development-update-test-cases.md)

**Comment by loripusey** [comment]
@kristenmcconnell @benbrasso-agile6 please validate

**Comment by kristenmcconnell** [comment]
> There is a channel in the AdHoc Slack space called #va-applications-shared-support-team that is currently being used by the Shared-Support-QA team. Tze is going to get me access to that.

I saw Tze's request for your access to this in the AdHoc Slack space. I'm messaging with him about it. I'm not sure what the contract boundaries are, but we are looking into it. I could make sure things are taken care of if worse comes to worse, since I'm on the same contract as him.

**Comment by kristenmcconnell** [comment]
Otherwise, the plan looks good.

**Comment by loripusey** [comment]
I think this channel should be moved to (or re-created in) the VA slack space. I asked him about that and he said the team is just getting started and that is probably what they will do.

**Comment by kristenmcconnell** [comment]
I agree.

**Comment by kristenmcconnell** [comment]
But, I'm glad that group can help and we are connected to them.
