### ISSUE TITLE
INTERNAL: POST `v0/coe/document_upload` (standalone uploader)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36129]
## Background
Once the `EXTERNAL: POST to /api/eligibility/document` work is complete, we will need to do an internal version.

## Considerations
The [EXTERNAL: POST](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32456) is being used behind the scenes on the form submission (to upload all the SIP form documents) but when the Veteran is on another page with another uploader, that is on its own like on the Your COE page, that needs to hit an internal endpoint to upload documents individually.

## Tasks
- [x] Create an internal endpoint to upload documents individually
- [x] TBD

## Acceptance Criteria
- [x] The other uploader has an internal endpoint to submit to for uploading docs individually.
- [x] A PR has been requested for merging

**Comment by alsleaders** [comment]
Per my conversation with Kathleen, this ticket is for the stand alone document uploader, not the one inside the COE form.
