### ISSUE TITLE
Service Account for PST-AMT team

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#36125]
## Description
Hi! We need a service account that has access to to dynamoDB.

## Background/context 
We are developing a post auth service that needs dynamoDB as a datastore. 

## Technical notes

---
## Tasks
- [ ] Have a service account created
- [ ] Give it permissions to perform CRUD operations in dynamoDB

## Acceptance Criteria 
- [ ] Application can perform CRUD operations on dynamoDB with the given service account credentials. 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by dginther** [comment]
It seems like this could be added to the existing service account?

**Comment by jsgarmon** [comment]
The service account user `svc-gha-pst-amt-user` now has full DynamoDB access to tables named `pst-amt*`.
