### ISSUE TITLE
Eligibility Determination `DENIED` && `SUBMITTED`

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36127]
## Background
Some of the COE statuses need some adjustment from the backend

## Considerations
This may be a combo of `GET determination = DENIED; GET Application = SUBMITTED` and needs to include the application date in the payload.

```
      elsif get_determination.body['status'] == 'DENIED' && get_application.body['status'] == 'SUBMITTED'
        { status: 'denied', application_create_date: get_application.body['create_date'] }
```

Originally, the term `RETURNED` was used instead of `SUBMITTED` but that might need to be confirmed, as it was from an old PowerPoint.

## Tasks
- [ ] Confirm the term submitted vs returned with Kelli
- [ ] Make appropriate adjustments to account for these considerations

## Acceptance Criteria
- [ ] The correct term has been confirmed
- [ ] Code has been adjusted 
- [ ] A PR has been requested for merging

**Comment by jason-gcio** [comment]
check for deltas: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36629

**Comment by jason-gcio** [comment]
just check for denied and make sure FE has the two distinct screens

**Comment by alsleaders** [comment]
Closing because PR is merged
