### ISSUE TITLE
Examine contents of outgoing soap call

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#36123]
## Description
I have a soap call for preneeds burial:
https://github.com/department-of-veterans-affairs/vets-api/blob/ddb7a57f72929934454b92f789b788bbfb406932/lib/preneeds/service.rb#L39

The call is made up of formdata and attached supporting evidence files that the vets upload.

The eoas(target endpoint)  team says that agents are complaining about missing attached files, and I'm trying to confirm if we are in fact sending them files in the raw soap call that goes from vets-api to the eoas endpoint.

Any way I can find-view a few of these calls raw soap in production ?  I'd like to view the raw soap and make sure some of them have file data in the outgoing call

That would help us narrow down the problem...

## Technical notes
As best as I can tell, the production url should be:
https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4439/eoas_SOA/PreNeedApplicationPort/receive_pre_need_application

---
## Tasks
- [ ] Not quite sure, but capture and save the soap message in outgoing calls to the above url for a day or so

## Acceptance Criteria 
- [ ] I'd like to view, or have someone view, the soap message, some of the messages should have one or more raw file data sections

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by zachclarity** [comment]
Does this provide enough info ?

19:25:41 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:41.050730Z","level":"error","level_index":4,"pid":51,"thread":"puma srv tp 003","file":"/srv/vets-api/src/app/serializers/evss_claim_base_serializer.rb","line":109,"named_tags":{"request_id":"44f9bfdc-a523-46e4-90aa-8e284f65a868","remote_ip":"72.186.125.167","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"lEtPunmuP/8PQQA3h2B38EZMC9QoSBjoBmJYdX0LVAg9ClljbpvxWPikYh7O3FUidjLWAZbscyn/YScy2S7E8g=="},"name":"Rails","message":"Expected EVSS [\"claim_phase_dates\", \"latest_phase_type\"] to be a phase. Got ''."}
19:25:41 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:41.048340Z","level":"info","level_index":2,"pid":87,"thread":"puma srv tp 008","duration_ms":90.53667999978643,"duration":"90.5ms","named_tags":{"request_id":"9e6450c2-9dd7-434f-94c4-4ae4aea97e75","remote_ip":"2603:8080:1905:f380:29a0:aca9:414d:6ed4","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.69","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"4eZQhxE+ZFTVcfOWbgAISCNKA1/iLMX77PaGSkeR7MgMbsBN6nuxrm2q+LU8QQHB1KM4X518eHYiJJseZGX/OQ=="},"name":"V0::FeatureTogglesController","message":"Completed #index","payload":{"controller":"V0::FeatureTogglesController","action":"index","params":{"cookie_id":"FILTERED"},"format":"JSON","method":"GET","path":"/v0/feature_toggles","status":200,"view_runtime":4.36,"db_runtime":0.0,"allocations":33384,"status_message":"OK"}}
19:25:41 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:41.047809Z","level":"info","level_index":2,"pid":87,"thread":"puma srv tp 008","named_tags":{"request_id":"9e6450c2-9dd7-434f-94c4-4ae4aea97e75","remote_ip":"2603:8080:1905:f380:29a0:aca9:414d:6ed4","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.69","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"4eZQhxE+ZFTVcfOWbgAISCNKA1/iLMX77PaGSkeR7MgMbsBN6nuxrm2q+LU8QQHB1KM4X518eHYiJJseZGX/OQ=="},"name":"Rails","message":"Rendered ActiveModel::Serializer::Null with Hash (3.97ms)"}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.769177Z","level":"info","level_index":2,"pid":87,"thread":"puma srv tp 008","duration_ms":31310.15201099217,"duration":"31.310s","named_tags":{"request_id":"bf75a611-4f82-4265-934c-20c2220784df","remote_ip":"2600:1700:9155:4890:edd5:fcf8:fdae:7db7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"Y6qTPJ2RYIhH7rDXoInYoleriLhDwibb9odlZMwx0yQVzmljchWjL9w0MXyhlQH1Ew08A7WWeT13nFxYMN6bFg=="},"name":"V0::Preneeds::BurialFormsController","message":"Completed #create","payload":{"controller":"V0::Preneeds::BurialFormsController","action":"create","params":{"application":{"claimant":{"name":{"first":"FILTERED","last":"FILTERED"},"ssn":"FILTERED","date_of_birth":"FILTERED","relationship_to_vet":"FILTERED","address":{"street":"FILTERED","city":"FILTERED","country":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"phone_number":"FILTERED","email":"FILTERED","desired_cemetery":"FILTERED"},"veteran":{"military_service_number":"FILTERED","place_of_birth":"FILTERED","gender":"FILTERED","race":{"is_white":true},"marital_status":"FILTERED","military_status":"FILTERED","service_name":{"first":"FILTERED","middle":"FILTERED","last":"FILTERED"},"service_records":[{"date_range":{"from":"FILTERED","to":"FILTERED"},"service_branch":"FILTERED","discharge_type":"FILTERED","highest_rank":"FILTERED"}],"current_name":{"first":"FILTERED","last":"FILTERED"},"address":{"country":"FILTERED","street":"FILTERED","city":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"date_of_birth":"FILTERED","ssn":"FILTERED","is_deceased":"FILTERED"},"applicant":{"applicant_relationship_to_claimant":"FILTERED","mailing_address":{"street":"FILTERED","city":"FILTERED","country":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"name":{"first":"FILTERED","last":"FILTERED"},"applicant_email":"FILTERED","applicant_phone_number":"FILTERED"},"preneed_attachments":[{"name":"FILTERED","confirmation_code":"FILTERED","is_encrypted":false,"attachment_id":"FILTERED"}],"has_currently_buried":"FILTERED"},"burial_form":{"application":{"claimant":{"name":{"first":"FILTERED","last":"FILTERED"},"ssn":"FILTERED","date_of_birth":"FILTERED","relationship_to_vet":"FILTERED","address":{"street":"FILTERED","city":"FILTERED","country":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"phone_number":"FILTERED","email":"FILTERED","desired_cemetery":"FILTERED"},"veteran":{"military_service_number":"FILTERED","place_of_birth":"FILTERED","gender":"FILTERED","race":{"is_white":true},"marital_status":"FILTERED","military_status":"FILTERED","service_name":{"first":"FILTERED","middle":"FILTERED","last":"FILTERED"},"service_records":[{"date_range":{"from":"FILTERED","to":"FILTERED"},"service_branch":"FILTERED","discharge_type":"FILTERED","highest_rank":"FILTERED"}],"current_name":{"first":"FILTERED","last":"FILTERED"},"address":{"country":"FILTERED","street":"FILTERED","city":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"date_of_birth":"FILTERED","ssn":"FILTERED","is_deceased":"FILTERED"},"applicant":{"applicant_relationship_to_claimant":"FILTERED","mailing_address":{"street":"FILTERED","city":"FILTERED","country":"FILTERED","state":"FILTERED","postal_code":"FILTERED"},"name":{"first":"FILTERED","last":"FILTERED"},"applicant_email":"FILTERED","applicant_phone_number":"FILTERED"},"preneed_attachments":[{"name":"FILTERED","confirmation_code":"FILTERED","is_encrypted":false,"attachment_id":"FILTERED"}],"has_currently_buried":"FILTERED"}}},"format":"JSON","method":"POST","path":"/v0/preneeds/burial_forms","status":504,"view_runtime":0.56,"db_runtime":2.16,"session":"f70df31872bdd132e7941","allocations":2264687,"status_message":"Gateway Timeout"}}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.771950Z","level":"info","level_index":2,"pid":51,"thread":"puma srv tp 008","duration_ms":3.948490004404448,"duration":"3.948ms","named_tags":{"request_id":"6a2f7a5d-0d25-482d-9ee0-83f82fb774fe","remote_ip":"10.247.44.40","user_agent":"lua-resty-http/0.14 (Lua) ngx_lua/10015","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","consumer_id":"e182f270-2c55-4bdd-8e18-c6cebbf2b56e","consumer_username":"argonaut_validation"},"name":"OpenidAuth::V2::ValidationController","message":"Completed #index","payload":{"controller":"OpenidAuth::V2::ValidationController","action":"index","params":{"aud":["FILTERED","FILTERED","FILTERED"],"strict":"FILTERED"},"format":"JSON","method":"POST","path":"/internal/auth/v2/validation","status":200,"view_runtime":0.78,"db_runtime":0.0,"session":"d55551f2db9339e4aa970","user_uuid":"6a127712a1854ff38a8ae0ae4ec3993a","allocations":1873,"status_message":"OK"}}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.768946Z","level":"info","level_index":2,"pid":87,"thread":"puma srv tp 008","named_tags":{"request_id":"bf75a611-4f82-4265-934c-20c2220784df","remote_ip":"2600:1700:9155:4890:edd5:fcf8:fdae:7db7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"Y6qTPJ2RYIhH7rDXoInYoleriLhDwibb9odlZMwx0yQVzmljchWjL9w0MXyhlQH1Ew08A7WWeT13nFxYMN6bFg=="},"name":"Rails","message":"Rendered ActiveModel::Serializer::Null with Hash (0.11ms)"}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.771713Z","level":"info","level_index":2,"pid":51,"thread":"puma srv tp 008","named_tags":{"request_id":"6a2f7a5d-0d25-482d-9ee0-83f82fb774fe","remote_ip":"10.247.44.40","user_agent":"lua-resty-http/0.14 (Lua) ngx_lua/10015","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","consumer_id":"e182f270-2c55-4bdd-8e18-c6cebbf2b56e","consumer_username":"argonaut_validation"},"name":"Rails","message":"Rendered OpenidAuth::ValidationSerializerV2 with ActiveModelSerializers::Adapter::JsonApi (0.51ms)"}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.767837Z","level":"error","level_index":4,"pid":87,"thread":"puma srv tp 008","file":"/srv/vets-api/src/lib/sentry_logging.rb","line":57,"named_tags":{"request_id":"bf75a611-4f82-4265-934c-20c2220784df","remote_ip":"2600:1700:9155:4890:edd5:fcf8:fdae:7db7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"Y6qTPJ2RYIhH7rDXoInYoleriLhDwibb9odlZMwx0yQVzmljchWjL9w0MXyhlQH1Ew08A7WWeT13nFxYMN6bFg=="},"name":"Rails","message":"/srv/vets-api/src/lib/common/client/base.rb:114:in `rescue in request'\n/srv/vets-api/src/lib/common/client/base.rb:100:in `request'\n/srv/vets-api/src/lib/common/client/base.rb:145:in `post'\n/srv/vets-api/src/lib/common/client/base.rb:97:in `perform'\n/srv/vets-api/src/lib/preneeds/service.rb:50:in `block in receive_pre_need_application'\n/srv/vets-api/src/lib/common/client/concerns/monitoring.rb:11:in `with_monitoring'\n/srv/vets-api/src/lib/preneeds/service.rb:50:in `receive_pre_need_application'\n/srv/vets-api/src/app/controllers/v0/preneeds/burial_forms_controller.rb:14:in `create'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/abstract_controller/base.rb:228:in `process_action'\n/usr/local/bundle/gems/ddtrace-0.54.2/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb:127:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'\n/usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:126:in `instance_exec'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:137:in `run_callbacks'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `block in instrument'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `instrument'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/instrumentation.rb:33:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'\n/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/abstract_controller/base.rb:165:in `process'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal.rb:190:in `dispatch'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_controller/metal.rb:254:in `dispatch'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:33:in `serve'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:32:in `each'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:32:in `serve'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:842:in `call'\n/usr/local/bundle/gems/rack-attack-6.5.0/lib/rack/attack.rb:99:in `call'\n/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'\n/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'\n/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/cookies.rb:689:in `call'\n/usr/local/bundle/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'\n/srv/vets-api/src/lib/statsd_middleware.rb:105:in `call'\n/usr/local/bundle/gems/olive_branch-4.0.1/lib/olive_branch/middleware.rb:64:in `call'\n/srv/vets-api/src/lib/olive_branch_patch.rb:9:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'\n/usr/local/bundle/gems/ddtrace-0.54.2/lib/ddtrace/contrib/rails/middlewares.rb:18:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\n/usr/local/bundle/gems/rails_semantic_logger-4.9.0/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'\n/usr/local/bundle/gems/rails_semantic_logger-4.9.0/lib/rails_semantic_logger/rack/logger.rb:26:in `block in call'\n/usr/local/bundle/gems/semantic_logger-4.9.0/lib/semantic_logger/semantic_logger.rb:395:in `named_tagged'\n/usr/local/bundle/gems/semantic_logger-4.9.0/lib/semantic_logger/base.rb:196:in `tagged'\n/usr/local/bundle/gems/rails_semantic_logger-4.9.0/lib/rails_semantic_logger/rack/logger.rb:26:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\n/usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'\n/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'\n/usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'\n/usr/local/bundle/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/host_authorization.rb:113:in `call'\n/usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'\n/srv/vets-api/src/lib/http_method_not_allowed.rb:13:in `call'\n/usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'\n/usr/local/bundle/gems/utf8-cleaner-1.0.0/lib/utf8-cleaner/middleware.rb:21:in `call'\n/usr/local/bundle/gems/ddtrace-0.54.2/lib/ddtrace/contrib/rack/middlewares.rb:88:in `call'\n/usr/local/bundle/gems/railties-6.1.4.4/lib/rails/engine.rb:539:in `call'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/configuration.rb:252:in `call'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/request.rb:72:in `block in handle_request'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/thread_pool.rb:340:in `with_force_shutdown'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/request.rb:71:in `handle_request'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/server.rb:441:in `process_client'\n/usr/local/bundle/gems/puma-5.6.0/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.770768Z","level":"info","level_index":2,"pid":51,"thread":"puma srv tp 008","named_tags":{"request_id":"6a2f7a5d-0d25-482d-9ee0-83f82fb774fe","remote_ip":"10.247.44.40","user_agent":"lua-resty-http/0.14 (Lua) ngx_lua/10015","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","consumer_id":"e182f270-2c55-4bdd-8e18-c6cebbf2b56e","consumer_username":"argonaut_validation"},"name":"Rails","message":"Logged in user with id 6a127712a1854ff38a8ae0ae4ec3993a, token 9497e71eb771272e133c4"}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.767688Z","level":"error","level_index":4,"pid":87,"thread":"puma srv tp 008","file":"/srv/vets-api/src/lib/sentry_logging.rb","line":57,"named_tags":{"request_id":"bf75a611-4f82-4265-934c-20c2220784df","remote_ip":"2600:1700:9155:4890:edd5:fcf8:fdae:7db7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"Y6qTPJ2RYIhH7rDXoInYoleriLhDwibb9odlZMwx0yQVzmljchWjL9w0MXyhlQH1Ew08A7WWeT13nFxYMN6bFg=="},"name":"Rails","message":"Gateway timeout."}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.725140Z","level":"warn","level_index":3,"pid":87,"thread":"puma srv tp 008","named_tags":{"request_id":"bf75a611-4f82-4265-934c-20c2220784df","remote_ip":"2600:1700:9155:4890:edd5:fcf8:fdae:7db7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","csrf_token":"Y6qTPJ2RYIhH7rDXoInYoleriLhDwibb9odlZMwx0yQVzmljchWjL9w0MXyhlQH1Ew08A7WWeT13nFxYMN6bFg=="},"name":"Rails","payload":{"msg":"Breakers failed request","service":"Preneeds","url":"https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4439/eoas_SOA/PreNeedApplicationPort","error":"Faraday::TimeoutError - Net::ReadTimeout with #<TCPSocket:(closed)>"}}
19:25:40 web.1       | {"host":"d1897583c70f","application":"vets-api-server","environment":"production","timestamp":"2022-01-27T19:25:40.681320Z","level":"info","level_index":2,"pid":51,"thread":"puma srv tp 008","duration_ms":3.976877997047268,"duration":"3.977ms","named_tags":{"request_id":"2ac7771b-d09a-49e2-86b1-204f8248d099","remote_ip":"10.247.44.215","user_agent":"lua-resty-http/0.14 (Lua) ngx_lua/10015","ref":"c6bfa717cfe9532cbc29925587cb9c0106edd68a","consumer_id":"e182f270-2c55-4bdd-8e18-c6cebbf2b56e","consumer_username":"argonaut_validation"},"name":"OpenidAuth::V2::ValidationController","message":"Completed #index","payload":{"controller":"OpenidAuth::V2::ValidationController","action":"index","params":{"aud":["FILTERED","FILTERED","FILTERED"],"strict":"FILTERED"},"format":"JSON","method":"POST","path":"/internal/auth/v2/validation","status":200,"view_runtime":0.84,"db_runtime":0.0,"session":"dd294203914a180923c41","user_uuid":"acff709798834abaa4497eff35140fd7",

**Comment by zachclarity** [comment]
unsure if this is the error you are seeing.

name":"Rails","payload":{"msg":"Breakers failed 
 ... 1.elb.amazonaws.com:4439/eoas_SOA/PreNeedApplicationPort","error":"Faraday::TimeoutError - Net::ReadTimeout with #TCPSocket:(closed)"}}

**Comment by zachclarity** [comment]
I ran this query:
{app="vets-api-server"} |~ "(fail|error|fatal)" |~ "eoas_SOA"

in Loki

http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C~%20%5C%22(fail%7Cerror%7Cfatal)%5C%22%20%7C~%20%5C%22eoas_SOA%5C%22%5Cn%22%7D%5D

**Comment by michelpmcdonald** [comment]
I'm not necessary interested in errors, I'm interested in seeing the outgoing(from vets-api to eoas) call's soap:Envelope, I don't care if it errors out.  I just need to make sure we are sending files(multipart soap message) to eoas.

I don't think we log out this data by default.....so it's not going to be in loki.

The data that is visible above:
```
"preneed_attachments":[{"name":"FILTERED","confirmation_code":"FILTERED","is_encrypted":false,"attachment_id":"FILTERED"}]
```
Is the data that vet-website sends to <vets-api>/v0/preneeds/preneed_attachments.

Vets-api takes the incoming data, builds a soap packet from it, and makes a call to eoas_SOA/PreNeedApplicationPort/receive_pre_need_application with the soap packet.

I'd like to catch that outgoing call and look at the outgoing soap packet to make sure we attached the files that we were supposed to attach.

**Comment by michelpmcdonald** [comment]
Just got an email from eoas, we ARE sending files over in some cases, so they confirmed what I was try to find out by capturing the outbound soap packet.

**Comment by michelpmcdonald** [comment]
I'm going to close this part of my investigation.

Eoas figured out in some cases we are attaching the files, and it is entirely possible that in some cases the user did not attach files to their claim, so there are no files to send eoas.
