### ISSUE TITLE
Certificate of Eligibility | Add Eligibility-Determination Date

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36128]
## Value Statement
**_As a_** user
**_I want to_** get accurate status information regarding my application
**_So that_** I know when my application has been submitted.

## Background Context
This backend ticket is meant to address the scenario where there might be a pending status with no application - but for testing, we should have a use case for this.

```
elsif get_determination.body['status'] == 'PENDING' && get_application.status == 404
 # Kelli said we'll never having a pending status w/o an application, but LGY sqa data is getting hand crafted
 { status: 'pending', application_create_date: get_determination.body['determination_date'] }
```
## Acceptance Criteria
- Users only see pending statuses if an application has been submitted. 
- If no application is submitted, the user is made aware. 

## Tasks
- [ ] Address the above code to account for the scenario of having a pending status with no application
- [ ] Reach out to LGY to confirm that there is no possibility to receive a pending status without an application

## Definition of Ready
- [x] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [x] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jason-gcio** [comment]
Consider closing

**Comment by saderagsdale** [comment]
- Sade to find LGY contact.

**Comment by jacobworrell** [comment]
@saderagsdale we should connect about this ticket, I'm confused what the next steps are.

**Comment by jacobworrell** [comment]
@saderagsdale ok that clears things up. the ticket language is super vague unless you've been involved in previous conversations. We've talked about this as a team a few sprints ago and nobody could decipher it. I think if the ticket is updated with clear language that assumes someone is viewing this issue for the first time, we can action against it.

**Comment by saderagsdale** [comment]
@scottymeyers I think we've confirmed that we don't need to accommodate this use case because we will not get a status without an application. Can you also confirm that is the case, or should we double check again with Kelli first?
