### ISSUE TITLE
Combined VA Debt Portal

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#36131]
## Epic
As a Veteran I want the ability to see all my VA debts, debt letters and payments in one dashboard.

The veteran will be able to see their debts and in (the future) select options to manage them such as a waiver, dispute, compromise and they would be routed to VBA and/or VHA. Allow Veterans to view ALL VA debts online and decrease time to resolution while meeting congressional mandates

## KPIs
- Total page views on debt portal

### Collab Cycle Touchpoints
- [ ] Kickoff [#37730](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/37730)
- [ ] Design Intent [#37887](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37887)
- [ ] Information Architecture (IA) Request 
- [ ] Research Plan Review 
- [ ] Analytics Request
- [ ] Midpoint Review 
- [ ] Contact Center Review 
- [ ] Staging Review 
- [ ] Privacy and Security Review

**Post Launch:**
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in
