### ISSUE TITLE
Discovery - Front end confirming Schematic Diagram

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3613]
# User Story:
As a Front-end developer I need to better document the Front-end calls and end points of the Medical procurement devices tools so that I can ensure that the Front-end will be able to build a modern tool to help increase usability for Veterans.

# Acceptance Criteria:
The requirements that must be met in order to mark this user story as completed
- [ ] Confirm diagram is correct with the Stakeholders

# Problem:
Determine what gaps need to be filled in the Schematic Design.

 A Schematic Design document that follows precedence to other teams
Share with VA stakeholders to confirm diagram.

# Tasks:
The steps that must be done by the team to complete the acceptance criteria
- [ ] Contact Ebenfits team to gather past discovery items
- [ ] Reach out to VA platform team to gather more information about each systems
- [ ] Confirm diagram is correct with the Stakeholders

# Configuration:
- [ ] Attached to a Milestone : Benefits and Memorial 2 Sprint 9
- [ ] Attached to an Epic 
- [ ] Labeled with Team: tools-improvements
- [ ] Labeled with Practice Area: frontend
- [ ] Labeled with Type: discovery, documentation

# Next Steps:
Create a mock up of the tool

# Blockers:
TBD
