### ISSUE TITLE
Need access to configure reverse proxy for VAOS application

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#36132]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The VAOS team needs access (or someone) to configure the reverse proxy configuration file to meet the requirements listed below.
 
## Background/context 
The VAOS application has the following requirements:

Scenario 1*
Given user is not logged in
When user directly enters the VAOS homepage (/health-care/schedule-view-va-appointments/appointments/)
And successfully authenticates
Then redirect user to the static landing page (/health-care/schedule-view-va-appointments/)

Scenario 2
Given user is logged in
When user directly enters the VAOS homepage (/health-care/schedule-view-va-appointments/appointments/)
Then redirect user to the static landing page (/health-care/schedule-view-va-appointments/)

Scenario 3
Given user is logged in
When user navigates to the VAOS homepage (/health-care/schedule-view-va-appointments/appointments/) from another VA.gov page
Then load the VAOS homepage

Original ticket #35231

## Technical notes
It was suggested to use a reverse proxy.

## Tasks
- [x] Need access to modify [react_routes.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml) or someone to do it for the VAOS team to meet the requirements listed above
- [ ] Need help with this task since no one on our team has experience with this

## Acceptance Criteria 
- [ ] All requirements listed above are met
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
@vbahinwillit : if you know what changes need to be made, feel free to put in a pull request to change [the redirects file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml). We can always deploy dev revproxy from your branch to test. I'm not sure off-hand how one would use the revproxy to determine if a user is logged in or not.

**Comment by jbritt1** [comment]
Think this can be closed as any member of the [vfs-vaos](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-vaos) GitHub team can submit pull requests to the `devops` repository.

**Comment by jhouse-solvd** [comment]
@jbritt1 - Thank you. Agreed. 

Closing.
