### ISSUE TITLE
Create Platform Website documentation for New VFS Teams

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#36148]
## Description
Create guidance on Platform Website for New VFS Teams created in ticket [#33198](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/33198)
Guidance should model "New VFS Team Members" section and include link as well as steps for PO/PM to complete.

---

## Artifacts
[Platform Orientation Platform Website](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)
- [ ] This ticket includes updates to Platform Website documentation. Reference the [Update existing Platform Website documentation guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation) in Governance Team Confluence for guidance on how to make the necessary changes.

---
## Tasks
- [ ] Add "New VFS Team" section
- [ ] List required pre-requisite access to Platform repos
- [ ] List steps PO/PM will need to perform

---

## Acceptance Criteria
- [ ] Platform Orientation on Platform Website has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member or OCTO (guidance to be created)

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance)
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces)
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space)
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization)

---
## How to configure this issue
- [ ] **Ticket Type is labeled** ('tech-debt', 'collaboration-cycle')
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`governance-team`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
