### ISSUE TITLE
Discovery Mock up of Medical Device Tool

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3614]
# User Story or Problem Statement:
As a Front-end Developer, I need to build a mock up of the future medial procurement tool to so that I can better understand the steps need to completely build a modern Medical Procurement Device tool  that address the needs of the Veterans.

# Goal:
To create a mock up and have the DLC stakeholder review the mock to augment gaps in our understanding of the medical procurement device tool systems

# Tasks:
The steps that must be done by the team to complete the acceptance criteria

> Create Transaction IDs
>  Log Transaction IDs on va.gov
>  Identify what is needed from EVSS to pass along the the Transaction IDs
>  Create Issue(s) for additional work needed
> Acceptance Criteria
> Scenario: A user submits information but the system returns either a FE or BE error that is not traceable.
> GIVEN that a user wants to submit information to VA
> WHEN an error occurs
> THEN the system identifies the error
> and records a Transaction ID

# Acceptance Criteria:
The requirements that must be met in order to mark this user story as completed
- [x] _Build interactive mock up_
- [x] integrating mock up into the VA code base
- [x] _Complete tutorial for creating new forms listed [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/form-tutorial-basic/)_
- [x] _Set up JSON schema to match form 2346 fields  and the VA standards listed [here](https://github.com/department-of-veterans-affairs/react-jsonschema-form)_
- [ ] _Implement error-handling widgets using the standards [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/errorablecheckbox/)_
- [ ] _Ensure form features meet the standards listed [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines/)_
- [ ] _Create unit tests to provide assurance that we are reproducing what the user experiences_ 

 Testable Outcome the flow is clickable.
 Testable Outcome users is able to fill out data.
 Testable Outcome Mock up is able to be presented. 

# Configuration:
Attached to a Milestone: Benefits and Memorial 2 Sprint 9
Attached to an Epic: N/A
Labeled with Team: tools-improvements
Labeled with Practice Area: back-end, research , accessibility
Labeled with Type: discovery, documentation

# Next Steps:
- [ ] Create a ticket to updated Mock from Stakeholders input. 
- [ ] Document and create a content inventory of the flow. 

# Blockers:
- Ticket 3072

**Comment by mojaray2k** [comment]
Adding @MRosari0 as a participant

**Comment by mr0sari0** [comment]
@wygonikGCIO This ticket needs to be changed to an epic.
