### ISSUE TITLE
NOD/HLR v2: Always show input associate with radio button

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36150]
## Description

On both the Notice of Disagreement and Higher-Level Review v2 area of disagreement pages, when the Veteran chooses "Something else", a input appears below the radio button and focus is shifted to the input. For a better accessibility experience, it was recommended to not shift focus and instead keep the input visible at all times, but disable it when the "Something else" option is not selected.
![Screen Shot 2022-01-28 at 11 16 32 AM](https://user-images.githubusercontent.com/136959/151592676-64dba377-b965-4196-b9fa-c84cf67071c5.png)

## Tasks

- [ ] Make explanation input always visible, but disable it when "Something else" isn't selected
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
