### ISSUE TITLE
[Design] Personal information revisions: Update Gender identity and Sexual orientation in mocks so they are multiselect

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#36165]
### Background

Related FE ticket #36168

According to Lexi, some of the health systems support multiselect for gender identity and sexual orientation, so we should update our designs to make these fields multiselect.

### Tasks

- [x] Update mockups so Gender identity is multiselect
- [x] Update mockups so Sexual orientation is multiselect
- [x] Update relevant frontend documentation for Adam

**Comment by cgednalske** [comment]
This is completed in the mockups and updated in the [FE Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/frontend/personal-info-copy.md)

**Comment by Samara-Strauss** [comment]
I clicked through the sketch file and saw that the mocks had been changed, but [the Personal Information Page - Desktop Edit state link](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/52OvGWw) under the "Personal Information Page - Edit State" heading is still linking to a mock that shows gender and sexual identity as single select. Just FYI!

**Comment by MarciMcGuireGCIO** [comment]
Hi @cgednalske - just wanted to confirm that you saw Samara's reply about this update.  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO yes I did! Answered elsewhere where we had the same question that related to a few tickets, but can definitely add it here too so we have it on record:

I am creating new symbols/components for each field that will update automatically in these two mockups, so I can avoid having to update each field for every change we have. They will go in once the hint text place holders are complete (nearly there). Those two mockups have been causing updates to be done multiple times, so working to streamline moving forward.

**Comment by MarciMcGuireGCIO** [comment]
Awesome!  Thanks, @cgednalske !  I'll close this ticket then.

**Comment by Samara-Strauss** [comment]
Just confirming that Christina and I talked about this in other tickets, and everything is good to go on this!!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @Samara-Strauss !
