### ISSUE TITLE
Midpoint Review [cedar-1095b, Form 1095-B]

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#36172]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [x] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [x] Product outline [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/1095B-Tax-Form-Product-Outline.md)

- [x] Finalized design prototype or mockup [Here in Mural](https://app.mural.co/invitation/mural/innovationboards1199/1644011260898?sender=ucbf569a3d5c571f73bec2539&key=5edcb01e-0b93-4e91-b5eb-453019bdff46)
- [x] Research plan [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/researchplan.md)

- [x] Conversation guide  [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/conversation-guide.md)

### Content artifacts 

- [ ] Content brief (if applicable) and your product’s content source of truth 

- [name of content of truth, for example, "Invision Prototypes"](link here)

- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct) [Here](https://dsvavsp.testrail.io/index.php?/suites/view/1082&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
- [x] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
Review has been scheduled for March 4th at 2:00 PM ET. Please add any applicable "Finalized design prototype or mockup" artifacts and forward to any other attendees if needed.

**Comment by jimuhh** [comment]
@JordanSWhite Can you re-link conversation guide? I'm getting a 404 on it. Thanks!

**Comment by briandeconinck** [comment]
No accessibility feedback, looks good! Thank you!

**Comment by ashleycastillo** [comment]
@jimuhh conversation guide link updated - it is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/conversation-guide.md

**Comment by jimuhh** [comment]
Thanks @ashleycastillo!

**Comment by jimuhh** [comment]
No additional feedback. Looks good. Thanks!

**Comment by claytonzook** [comment]
No research feedback. Looks good!

**Comment by ashleycastillo** [comment]
Thanks, Jim and Clayton! Is there any more feedback for our team from Midpoint Review?

**Comment by chaseakirby** [comment]
Hi @ashleycastillo , accessibility had no feedback as well per Brian's comment.
Design, Content, and QA attached child tickets with their feedback to this ticket so all of our team has now responded. 
Please let us know if you have any questions when reviewing the practice area feedbacks!

**Comment by ashleycastillo** [comment]
Thank you all for your feedback!

**Comment by kit-casey** [comment]
Also, just an update for the VFS team on this thread, via the Content & IA team, we received guidance on the H1/URL/breadcrumb/left nav resulting in: “Download your IRS 1095-B tax form” (updates are using “IRS” and changing “document” to “form”).

Note: We had a conversation on “document” vs. “form” in terms of VA context, but the team feels strongly about using "**form**" because that’s what it's called even when filled in and in consideration of SEO. (Internally, we also revisited our comparative work, and “**form**” is the consistent word used for the 1095-B across all experiences: United Health Care, Cigna, Medicare, Blue Cross Blue Shield Illinois, PreferredOne.) 

[Link to Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37639#issuecomment-1061259726).
