### ISSUE TITLE
[Design, FE] On-site Notification: Discuss consolidating multiple alerts and conditional verbiage

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36184]
## Background
Per research findings and previous conversations, we are looking to see how consolidating multiple notifications would work (if we receive multiple triggers from VA Notify for the same person) and what kind of verbiage would be used in those instances.

## Tasks
- [x] Discuss use cases for the various scenarios that would cause more than one on-site notification to be triggered and viewed on the page
- [x] Discuss the effort to consolidate multiple notifications
- [ ] Discuss the verbiage for a limited set of scenarios (in an attempt to limit the conditional coding)
- [ ] Share details with the team

## Acceptance Criteria
- A summary is outlined on how we might handle multiple on-site notifications

**Comment by andaleliz** [comment]
@hdjustice I need some clarification before I estimate this ticket:

>Determination is finalized on how to handle multiple on-site notifications and **what that will look like on My VA**

Is design part of this effort too, or will that be a separate task, after we have this discussion?

**Comment by hdjustice** [comment]
No, we would not need design for this.  I re-worded it so that we might have a summary/outline of how we might address the multiple on-site notifications and removed that last part.  Is that better?

**Comment by andaleliz** [comment]
For sure! Just wanted to make sure I estimated accurately.

**Comment by andaleliz** [comment]
@hdjustice should this ticket still be open? My memory is not serving me well regarding what this is, even after reading the description. Womp womp.

**Comment by hdjustice** [comment]
Hey there @andaleliz and @tmitchellgcio 
This ticket is for a discussion around On-site notifications, with topics coming from the [usability sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/findings.md#next-steps), [brief convo with Samara on 1/28](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34802#issuecomment-1024697467), as well as [IA feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35765):
- What would this look like if there were multiple notifications of new debts?
     - Consolidated?
     - Separated?
     - What might the copy say/look like?
     - Should we include the number of new debts in our debt alert?
- Keeping in mind that we want to keep this as simple as possible - limited scenarios, broad scope
- Keeping in mind that we will look at this Notifications section as a whole when we think about reorganizing My VA.

**Comment by tmitchellgcio** [comment]
I think they should not be consolidated since we are dismissing them. If they are consolidated we would have to batch dismiss them which is possible but what if they want one dismissed and not another?

**Comment by aagosto90** [comment]
@tmitchellgcio That's a fair point for sure. We can discuss more in-depth when we meet tomorrow but my opinion is while we don't have any additional detail about the notification besides you have a new debt, there wouldn't be much of a use case for a veteran wanting to dismiss one notification but not another since on My VA, visually they will all be the same and take the user to the same link. There will be no way for them to tell which debt the notification refers to if they dismiss one and leave another. I'm definitely aiming to make this an easy to implement update since we plan to have more detailed notifications and a dedicated notifications page in the future that will be a better solve for the multiple notifications scenario.

**Comment by aagosto90** [comment]
The team met on 4/28 and discussed two potential approaches:
1. Show multiple debt notifications with the current content and add a time stamp to them so there is some differentiation between notifications that will have the same content. This approach does a good job of considering our future vision for notifications where we will likely present them in chronological order.
2. Put a quantity on the debt notification and consolidate multiple into one. i.e. "You have 2 new debts. Manage your VA debt" This approach seems the most clear while debt is the only type of notification we have, but will likely not be the approach we would take once we add more notifications to this section and eventually a separate notifications page.

Taylor said they will likely be about the same engineering effort and neither is particularly difficult to implement. We had a couple questions for the debt team coming out of this meeting.

Guidance from Riley on our debt questions:
**Are there still 3 different kinds of debt?**
Veterans can incur the following debt types:
CH 33 (Post-9/11 GI Bill)
CH 34
CH 35 (Dependents and Survivors*)
Compensation & Pension
**Can you only have one debt for each type? Or could have you multiple debts for each kind of debt?**
A Veteran can only have one debt for each type at a time. For example, a Veteran could have a $200 Compensation & Pension debt due to an overpayment. Let's say they receive another overpayment of $50. That $50 is added as a 'debt increase' to the $200 for a total of $250 rather than a separate $50 Compensation & Pension debt being created.
An exception to this is: if a Veteran incurs a Post-9/11 GI Bill Debt (CH 33), that debt is split into 3 separate debts. These debts are:
Post-9/11 GI Bill debt for books & supplies
Post-9/11 GI Bill debt for housing allowance
Post-9/11 GI Bill debt for tuition and fees
**Is there any data about how many veterans have multiple different debts?**
I don't have access to that kind of data, but our main stakeholder at the Debt Management Center, Jill, may be able to provide that information when your team connects with her!
However, it's going to be a relatively common use case anyway since Post-9/11 GI Bill debts are split into 3 separate debts.

Important takeaway from above is that multiple debts is not necessarily an edge case, but there will likely never be more than 3 presented on My VA since veterans will have a balance for each type of debt.

**We can move forward with the decision to present multiple notifications when necessary and add a time stamp. @ajakabcin @ericasauv09 Can you create additional tickets for design and engineering to execute that please?**

CC: @Samara-Strauss @tmitchellgcio

**Comment by Samara-Strauss** [comment]
@aagosto90 thank you! This is super helpful. I've added this info to [a doc in our project folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/product/how-debts-work.md) so this valuable knowledge doesn't get lost in this ticket.
