### ISSUE TITLE
[Design] My VA - Payment info & On-site Notifications: Consider alert design to improve usability for people with low vision.

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36182]
## Background
During our research sessions with Veterans for the **Benefit payments and debts**, and **On-site Notifications** features, we received feedback around the background color of our alerts, and how it may not be suitable (not standing out enough, or not readable).
We need to revisit the alert design to ensure we are using the right combination of color, icon and text formatting that will not exclude users who may be color-blind, have low-vision, or other impairments.  We will also need to be cognizant of triggering colors or formats that may cause undue stress to veterans who might suffer from PTSD or other conditions.

### Resources
Research findings
- Color of the alert
          - [Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/findings.md#33-multiple-participants-commented-that-the-light-yellow-color-for-the-alert-did-not-stand-out-to-them-and-one-participant-stated-it-made-the-text-very-difficult-to-read)
          - [Recommendations item #7](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/user-research/findings.md#recommendations)
[Sketch file](https://www.sketch.com/s/418ca6f6-cc24-4496-82aa-9deda03b08f6)
[Design System page](https://design.va.gov/design/)

## Tasks
- [ ] Review research findings, sketch file and VSA design system
- [ ] Determine alternatives that fit our goal to accommodate low-vision Veterans, while keeping other conditions in mind
- [ ] Share recommendations with the team (you can reach out to Heather to set up a meeting)

## Acceptance Criteria
- Design alternatives for alerts (on-site and in-line) have been presented to the team for discussion

**NOTE** Once the design style has been decided, we may need to submit to the Experimental Design team for approvals.  We can determine that if we decide to use something that does not currently exist in the design system.

**Comment by hdjustice** [comment]
Ticket was not completed, as this was pulled in as unplanned work to start, and will have continuing conversations.  This will move on to a future sprint.

**Comment by aagosto90** [comment]
@Samara-Strauss :
@hdjustice , @andaleliz and I met today to discuss design options for the alerts. I walked them through a design exploration I did that evaluated the issues with the current alert design and what options we have to correct visibility and urgency concerns that came up in research.

Ultimately we would recommend using the contextual alert style instead of the background only style we showed in usability testing. Here's a [link to the Sketch artboard](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/L02Rv3L) where I detailed how this would solve urgency and visibility concerns.

If the governance team does not approve this option due to the fact that an error has not occurred, then we will have research to support that there are no appropriate solutions in the pattern library and experimental design is needed. In that case we might suggest an alert option with a solid background as shown in Option 4 in the Sketch file.
![Screen Shot 2022-02-09 at 12 22 50 PM](https://user-images.githubusercontent.com/97965610/153255438-7615ad3b-a86d-46f9-b19b-90616ffef0d7.png)

**Comment by Samara-Strauss** [comment]
Hey @aagosto90 @andaleliz @hdjustice! Thank you for the update. This exploration is great.

I understand why moving forward with option 3 right now makes the most sense, and I think that is an OK path to pursue. However, I do worry that this mostly gray box then doesn't stand out enough in comparison to the other gray boxes (eg. the claim status update, next appointment, most recent payment, applications in progress), especially when the notification is directly above the gray box. I think we'll be able to validate this in testing, and ultimately, I'm hoping we can move away from all-gray-all-the-time. But, I do think this is OK to move forward with for now/for UAT/launch, and we can make moves to evolve the design if we hear from users that it's not really effective given how much we already use gray boxes on this page. And of course, if users love it, then forget everything I said :)

**Comment by hdjustice** [comment]
closing ticket - implementing design for UAT and gain feedback.
