### ISSUE TITLE
[Design] My VA - Payment Info: Create a design to add an information box when there are no debts

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36188]
## Background
As per research findings on the Benefit payments and debts section, quite a few participants expressed the desire for a information line of text stating that there is no debt open for the person.
We need to create a design that includes an information line stating that there is no open debt for the user.  The format can mimic the pattern used for the Health care section - messages box (when there are no messages).

Currently, when there are no messages to display in the Health care section, the copy changes to **"You have 0 unread messages"**  (Screenshot from Staging environment below)
![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/bdd1d440-db7c-40bf-8dc6-6540cd4505fe)

## Tasks
- [ ] Confirm current health care messages design in Production
- [ ] Update design for Benefit payments and debts to include a 'zero' state for users with no outstanding debt
- [ ] Determine if this info box should also display when users have never had debt
- [ ] Share design recommendation with the team

## Acceptance Criteria
- Benefit payments and debts design updated with information box for a "no debt" scenario

**Comment by andaleliz** [comment]
Hi @hdjustice thanks so much for creating this for me! I need to consider this task as I work through the FE documentation ticket, so I moved this into the current sprint.

**Comment by andaleliz** [comment]
@Samara-Strauss and @hdjustice, after exploring a few different options, I landed on a simple approach to letting users know they don't have debt, using the same approach we're using when they don't have any recent payments. Here are the mobile (left) and desktop (versions)

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/8a3a46a8-2d48-4a1f-983b-eb9e896fa9fe)

It didn't seem to make sense to use exactly the same approach we have for health care; the "You have 0 unread messages" text links to secure messaging which makes sense to me. But, I don't think it makes sense to link the text stating "You have no outstanding debt with VA" to the debt management page. 

Instead, I think we can put a "learn about VA debt" link to help educate users about debt when this message is displayed. If they have debt, they get the "Manage your VA debt" link instead.

It seems as if we can't access payment history, so we basically just need to show this debt content based on if someone has ever had payments. which I think is ok.  If a Veteran receives payments, they could conceivably go into debt, so this is a step toward making it it easier for them to learn about debt, even if they've never had it or aren't sure what it is.

Thoughts?

**Comment by hdjustice** [comment]
@andaleliz I think this is good.  I like the Learn about link, I think that would help clear up any doubts and confusion.  At this point, we would only display the whole section if the Veteran had ever received payments, so it would be a matter of either showing this line of text or showing the number of outstanding debts.  
Have you gotten to the view of how this message would display if they do have a recent payment?

**Comment by Samara-Strauss** [comment]
TBH, I do kind of worry that most people won't think anything about VA debt if we don't mention it, and people in user testing probably did think about it/want to see more info because we brought it up in the first place. I'll be interested to see how people without debt react to this over time, but I do think we should continue with this approach and see how it goes once this is live and in the wild.

One question -- how would this work if someone did have a recent payment but no debt. Would we still show the no debt messaging or not?

**Comment by andaleliz** [comment]
Yes, I think we should, based on the feedback we got from people who had never had debt, and wanted to have the confirmation that they didn't have any.

So that the text isn't overshadowed by the card on desktop, I think we should put it above the payment card. 
<img width="851" src="https://user-images.githubusercontent.com/55992116/152235243-5b5b3efc-4045-4b10-b860-7bd1f313c0b2.png">

**Comment by Samara-Strauss** [comment]
Got it, thanks! Looks good to me.

**Comment by hdjustice** [comment]
I love it!  simple and sleek!

**Comment by andaleliz** [comment]
Wonderful! I'll close this out and add to the docs via #33993. Thank you!

**Comment by hdjustice** [comment]
@andaleliz I just thought of something, should the Learn about VA debt link persist always? or should it only appear when there is no debt, and we display the text line.

**Comment by andaleliz** [comment]
I was thinking it would only appear when there is no debt. When people do have debt, the manage link is much more important and shares a lot of (if not all of) the same information.

**Comment by hdjustice** [comment]
I totally agree, and wanted to hear your perspective as well.  Thank you!

**Comment by andaleliz** [comment]
Ultimately, the [FE documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md) should be used as the source of truth for content.

**Comment by Samara-Strauss** [comment]
+1 -- please make sure the FE documentation is always updated. It's OK to put copy in a ticket so someone doesn't have to go digging for it, but updates should always be in the FE documentation.

**Comment by hdjustice** [comment]
Agreed.  I wanted to document that the verbiage was updated and reviewed with content.  I assumed we would have a finalized source for everything.  Thanks!
