### ISSUE TITLE
[Design] Tertiary Button Style Ideations

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36197]
# Description
We have an edge case where a Veterans need to be able to refresh a page ([Sketch with the refresh at the bottom of the page](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/WKwqxkk)). This refresh action should only be used limitedly. It is not the most important action on the page. According to the design system, the refresh actions should be a button, in order to be materially honest. Our current button styling are very visually prominent. As a result, we would like to create a tertiary button styling, then submit it to the design system. Within this ticket, we will ideation on what the tertiary style should look like.

# Tasks
- [ ] Check the [backlog](https://design.va.gov/documentation/backlog) to see if this idea has already been suggested. Take a look at the “proposed” category.
- [ ] Post in design Slack channel to see if anyone explored this concept before.
- [ ] Look at tertiary style that exist in other design systems
- [ ] Ideation on UI patterns within Sketch
- [ ] Review the ideations with accessibility and check-in UX teams
- [ ] List out the reason(s) about when to use this pattern

# Acceptance Criteria
- [ ] Have a finalized UI design proposed along with reasoning when to use this component, so we can be ready to submit an experimental design ticket.

**Comment by kristenmcconnell** [comment]
[Tertiary styles explored by the profile team for their "Remove" functionality.](https://dsva.slack.com/archives/C02EDKYGHV0/p1643735873384069)
