### ISSUE TITLE
[FE] My VA - Payment Info: Add an information box to show there are no debts

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36190]
## Background
As per research findings on the Benefit payments and debts section, quite a few participants expressed the desire for a information line of text stating that there is no debt open for the person.
We need to implement a condition that will display an information line of text stating that there is no open debt for the user.   This condition will also cause a link to display in the link list, that will redirect the user to the VA debt management page.

Reference **[Frontend document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)**.

## Tasks
- [ ] Update code for Benefit payments and debts section to include a 'zero' state information text for users with no outstanding debt, line of text will read "Your total VA debt balance is $0"
- [ ] This info text should _also_ display when users have **never** had debt
- [ ] Add a link to the Benefit payments and debts section stating "Learn about VA debt"
     - This link should only appear when the 'zero' state text is displayed (no debt). 
     - The URL is  [https://www.va.gov/resources/va-debt-management/](https://www.google.com/url?q=https://www.va.gov/resources/va-debt-management/&sa=D&source=docs&ust=1643904440722023&usg=AOvVaw07WHN0k2Drl5JPSPR8_c93)

## Acceptance Criteria
- Benefit payments and debts section is updated with information text for a "no debt" scenario, and a new link added.

**Comment by hdjustice** [comment]
FYI - @tmitchellgcio Liz has just about completed this work, having screenshots in **[Ticket #36188](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36188)** for the design layout.  She is working on updating the FE documentation to include this as well.
