### ISSUE TITLE
[Development] Testing in MVI Development Environment

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#3619]
## User Story or Problem Statement
As the Backend Engineer on the Benefits and Memorials team, I need to complete a series of tasks identified during endpoint implementation development so I can establish the implementation and complete the integration with MVI.

## Goal
_Test the MVI proxy add endpoint implementation in the dev env_

## Tasks
- [ ] Move integration on to a dev box
- [ ] Login as user and make proxy add calls using the new service
- [ ] Setup vcr recording on dev box and record cassette(s)
- [ ] Use cassettes to finish unit tests for integration

## Acceptance Criteria
- [ ]  Finish integration with testing infrastructure

**Comment by YanaRoy** [comment]
MVI is trying to figure out why we don't have access privileges for the add profile end point. Currently debugging all connections. Once that is done, we can move forward with the env testing.
