### ISSUE TITLE
Request for self-hosted runners for Github Actions workflow content-build/content-release.yml

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#36192]
## Description
We would like to modify the [content-build/content-release.yml](https://github.com/department-of-veterans-affairs/content-build/actions/workflows/content-release.yml) workflow to fully use self-hosted runners. 

This job handles building and moving content from the CMS to VA.gov several times a day. It is crucial for our VA content editors and for veterans that the content goes out in a predictable and timely manner.

We are seeing significant intermittent delays in the pickup of jobs within this workflow by Github Action's runners, which is causing the workflow time-to-complete to be longer than expected and to vary widely. We are are hoping self-hosted runners may help stabilize the workflow runs and make them predictable.

## Background/context 
This workflow already uses an on-demand self-hosted runner for jobs that require behind-the-firewall access. This runner is spun up here: https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L31

One significant problem is that **[the job that spins up the self-hosted runner is itself a Github Actions runner](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L31)**. Even if we moved every other job in the workflow to use the self-hosted runner we have, it would still be subject to unacceptable delays if it was dependent on this job being run by Github Actions. There needs to be some sort of persistent self-hosted runner to provision the on demand runner. 

Another thing to note is that [the self-hosted runner that is provisioned in this job is quite large](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L37). This particular runner is probably overkill for most of the jobs in this workflow. It is possible that a pool of small persistent runners would be sufficient to run most of these jobs, or else that we should provision and later tear down a second smaller instance to run these jobs.

The initial reporting of this issue to Github support is in this Slack thread, along with subsequent discussion: https://dsva.slack.com/archives/CU1E4CX9U/p1642797085041400

Of note, from that thread:

* Github states that this behavior - jobs being queued and potentially taking some time before they begin to run - is currently expected behavior, due to the amount of activity GHA generates and the Azure resources GHA has available to handle that activity. They do not guarantee timely running of jobs with Github Actions runners.
* Github's first suggestion was to move our scheduled job away from 00 (top of the hour) to an off time, because there is a global rush of cron activity which overwhelms GHA at the top of the hour. [We moved the start of the hourly job to :54 minutes  after the hour](https://github.com/department-of-veterans-affairs/content-build/commit/9998279db757bd20dca000b4b70dfc126729f67d), but we have not seen a significant difference in speed.
* We sometimes see the bulk of the delay at the beginning of the workflow - that is, there is significant delay before the first job in the workflow runs, and then everything runs as expected without interruption. However, sometimes the delays occur in the middle of the workflow, with several of the jobs having wait times of 5-10 minutes before they begin running, even though they are eligible to run.

These runs are visible in Datadog's CI overview. All content-release pipeline runs: https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?start=1642802652552&end=1643407452552

Examples:

* [This is a 'normal' run with no significant delay introduced by Github Actions](https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?query=env%3Anone%20%40git.repository.id%3A%22github.com%2Fdepartment-of-veterans-affairs%2Fcontent-build%22%20%40ci.pipeline.name%3A%22Content%20Release%22%20%40ci.provider.instance%3Agithub-actions%20%40git.branch%3Amaster&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5D&index=cipipeline&spanID=1798038184213190681&trace=AQAAAX6dosQI8OxKaQAAAABBWDZkb3NRSUFBRExEQ2JrZlctRHpUdVk&start=1642802652552&end=1643407452552&paused=false).
* [This is a recent run with all the delay front-loaded](https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?query=env%3Anone%20%40git.repository.id%3A%22github.com%2Fdepartment-of-veterans-affairs%2Fcontent-build%22%20%40ci.pipeline.name%3A%22Content%20Release%22%20%40ci.provider.instance%3Agithub-actions%20%40git.branch%3Amaster&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5D&index=cipipeline&spanID=1727060881367279164&trace=AQAAAX6ircQgRyRKaAAAAABBWDZpcmNRZ0FBRE5oaklrU3h1ZWZxcGM&start=1642802652552&end=1643407452552&paused=false)
* [This is a recent run with multiple delays within the workflow.](https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?query=env%3Anone%20%40git.repository.id%3A%22github.com%2Fdepartment-of-veterans-affairs%2Fcontent-build%22%20%40ci.pipeline.name%3A%22Content%20Release%22%20%40ci.provider.instance%3Agithub-actions%20%40git.branch%3Amaster&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5D&index=cipipeline&spanID=13582755290341826431&trace=AQAAAX6XTcN49L5KaAAAAABBWDZYVGNONEFBRHp5T1B4bDlmaXl3amY&start=1642802652552&end=1643407452552&paused=false)

---
## Tasks
- [ ] A persistent self-hosted runner exists that can be used to provision the larger self-hosted runner that is currently used for behind-the-firewall tasks within content-release.yml
- [ ] Guidance from Ops as to whether we should provision a smaller self-hosted runner to work on smaller jobs, or if the persistent runners are suitable for these jobs

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_ (NB. leaving this for Ops to craft.)

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@timcosgrove - Can you give us a sense of urgency or desired time to complete this request? ie - What's the severity of the current impact? 

cc: @mchelen

**Comment by jhouse-solvd** [comment]
With respect to a pool of available self-hosted runners:

One potential solution is "on-demand self-hosted runners" which are essentially EC2 instances that get automatically created and destroyed. There is some documentation about those [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114812/On-Demand+Github+Self-Hosted+Runners). 

I'd like to discuss w/ the Infrastructure Team to get our recommended best practice based on recent experiences with the content-build pipelines:  

@oseasmoran73 - In your experience, have the on-demand self-hosted runners been a stable, reliable, and performant solution for the content-build or other FE build pipelines?

**Comment by jhouse-solvd** [comment]
There can also be "dedicated self-hosted runners" and there is documentation about those [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners). 

@timcosgrove - Before your team starts down a specific path, we'd like to provide guidance and identify which tasks are needed for the Infrastructure Team to properly support the recommended path. ☺️

**Comment by timcosgrove** [comment]
To clarify, we do use an on-demand self-hosted runner already. We use it currently for jobs which require behind-the-firewall access.

The problem with the way that we are being instructed to spin up on-demand self-hosted runners is this:
```
jobs:
  start-runner:
    runs-on: ubuntu-latest # Github Actions runner
```
The job that provisions the on-demand self-hosted runner is itself run by a Github Actions runner. This job often sits idle for 25 minutes before a Github Actions runner picks it up.

So, even if we go this route and move all jobs in the workflow to an on-demand self-hosted runner, that first job is still a bottleneck and will continue to cause problems for us.

**Comment by jhouse-solvd** [comment]
@oseasmoran73 please disregard the previous comment. I did not understand the request fully.

**Comment by timcosgrove** [comment]
This is a run where the workflow sat idle for 30 minutes before a GHA runner picked up the first job: 

* [In Github](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1763590864/attempts/1)
* [In Datadog (flame graph, easier to understand view)](https://app.datadoghq.com/ci/pipelines/lco-5czptsAY/Content%20Release/none/master?query=env%3Anone%20%40git.repository.id%3A%22github.com%2Fdepartment-of-veterans-affairs%2Fcontent-build%22%20%40ci.pipeline.name%3A%22Content%20Release%22%20%40ci.provider.instance%3Agithub-actions%20%40git.branch%3Amaster&colorBy=meta%5B%27ci.stage.name%27%5D&colorByAttr=meta%5B%27ci.stage.name%27%5D&index=cipipeline&spanID=1727060881367279164&trace=AQAAAX6ircQgRyRKaAAAAABBWDZpcmNRZ0FBRE5oaklrU3h1ZWZxcGM&start=1642802652552&end=1643407452552&paused=false)

Even if every other job were run by a self-hosted on demand runner, they wouldn't begin running until that first job provisioned the on-demand runner, so there would still be a 30 minute delay before the job started.

**Comment by jhouse-solvd** [comment]
@timcosgrove - I believe I understand now that you're hoping to leverage some "dedicated self-hosted runners" (rather than on-demand) that are not reliant on GitHub cloud runners. Is that correct? 

[This](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474595213/Self-Hosted+Runners) is an Infrastructure Team -facing document that explains how we've set these up in the past. It may provide an overview of the architecture and support this conversation.

**Comment by timcosgrove** [comment]
@jhouse-solvd I believe it would be sufficient for the initial job to be run by something 'dedicated'. Everything else could be run by one on-demand self-hosted runner and torn down; or, it could be two, one large and small, if that makes more sense from a cost/infrastructure perspective.

It's that first job that's can't be run by an on-demand runner.

**Comment by timcosgrove** [comment]
> Github Actions will fail a job which requires a self-hosted runner if there are no runners available, so scaling to 0 runners is not really possible. There is a workaround which involves keeping an “offline” runner in the list, however, it will be automatically culled every 30 days so we would need to create automation to create an offline runner when it disappeared.

> Github Actions will not run multiple parallel jobs on a self-hosted runner, unless you write your job to BE parallel natively, i.e.: using multiple threads. If you set up multiple jobs in GHA to run in parallel, but you only have one runner, it will run each job in sequence on that one runner.

The first paragraph says to me that we would need a single dedicated runner for the initial job, in order to ensure it does not fail due to failing to find a runner. We do not allow simultaneous Content Release jobs, so one should be sufficient, though I very much appreciate Ops' advice here.

Re: the second paragraph: that is largely fine. We do not run parallel jobs in this workflow that are of substantial length. If the jobs that are currently able to run in parallel are forced to run sequentially, it should not adversely affect run time, and the stability & consistency gains would be worth it.

**Comment by jhouse-solvd** [comment]
Oseas to consult with the team during an in-person meeting today (2/2/222)

**Comment by oseasmoran73** [comment]
Action items from meeting: Transition from `ubuntu-latest` to `self-hosted` runners. [PR](https://github.com/department-of-veterans-affairs/content-build/pull/949/files)

Moving ticket to review to away metrics from Tim C.

**Comment by oseasmoran73** [comment]
Adding couple of PRs to this ticket for tracking:
- https://github.com/department-of-veterans-affairs/content-build/pull/951
- https://github.com/department-of-veterans-affairs/content-build/pull/952

**Comment by oseasmoran73** [comment]
Adding [slack](https://dsva.slack.com/archives/C01512KN35G/p1643912776356499) of outcome

**Comment by cweagans** [comment]
I think we can close this. We're now using self hosted runners for the content release job.

**Comment by oseasmoran73** [comment]
@cweagans I am all in favor as I think requirements have been met! I will let @timcosgrove close the ticket as it was requested by your team initially.

I have removed Infra label to ticket. Please feel free to re-add us if ticket has not been met.

**Comment by cweagans** [comment]
Closing - plz reopen if you disagree @timcosgrove
