### ISSUE TITLE
[Research] Planning Pre-check-in and Check-in Content Review Research Study

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36201]
## User Story
- As a Veteran, I want the content presented to me particularly in non-happy path scenarios to make sense.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover the edge cases and error states within pre-check-in and day of check-in. This study should be content focused.

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create research plan (template in research checklist above)
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan and conversation guide with team (particularly product, UX, and Stephen)
- [ ] Post finalize research plan and conversation guide to GitHub folder
