### ISSUE TITLE
[UX] FE Support

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36200]
# Description
The purpose of this ticket is to designate UX time to support engineering with questions or reviews that pop up throughout the sprint. If too many items come in from engineering or a bigger topic is identified, it will be broken out into additional tickets. 

# Tasks
- [ ] Answer engineering questions and complete any necessary work, in order to answer their questions
- [ ] Review FE implementation

# Acceptance Criteria
- [ ] Questions answered
- [ ] FE implementation reviewed

**Comment by kristenmcconnell** [comment]
The other way around. This is to set aside some of UX's time to review FE implementation and answer engineering's questions. We experimented with having a ticket each sprint for this. Alternatively, we could figure this into our capacities.

**Comment by kristenmcconnell** [comment]
Makes sense to me.
