### ISSUE TITLE
[UX] Prep for Editing Pre-check-in UAT: Create Test Cases

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36202]
# Description
Once pre-check-in editing is implement, UX will conduct UAT testing on the feature. In order to prepare for this UAT testing, the UX team needs to prepare test cases to review. They should expand upon the initial test cases listed within the [editing design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md).

# Tasks
- [x] Review [editing design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md) and review @zach-park's [edge case list](https://docs.google.com/document/d/10QlMsv_OLJQ9BoIhNgCkDfDQuWYzPuyrR_F6fya2Yto/edit#).
- [x] Check with engineering on how they capture test cases for their testing. This may result in changes to the next task item.
- [x] Create spreadsheet with testing cases for UAT. This spreadsheet will be utilize to make sure all test cases are covered during UAT testing.

# Acceptance Criteria
- [x] Spreadsheet with test case is prepped and ready for when UAT begins.

**Comment by kristenmcconnell** [comment]
@kristenmcconnell Add old test case document to this story.

**Comment by benbrasso-agile6** [comment]
Draft Google doc - https://docs.google.com/document/d/12xDl6M5fNtKEE9hMWLyPUuKq-RLxx_bWyIp05gRybcg/edit?usp=sharing

Would like to review with @zach-park and @kristenmcconnell. May need to run by Adrian as well.

**Comment by benbrasso-agile6** [comment]
Ticket is complete. However, the test cases will need to be revisited as design and implementation progress. 

E.g., there are ongoing changes to authentication method, introduction of use case for pre check in expiration vs. appointment time has began, adding a clear function on forms with additional validation requirements, etc. 

Suggest revisiting test cases before production push.
