### ISSUE TITLE
[FSR] write unit tests for fetch actions

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36217]
## Issue Description
There is a need to write unit tests for the following fetch actions:
- fetchFormStatus
- fetchDebts

---
## Tasks
- [ ] write unit tests for fetch actions

## Acceptance Criteria
- [ ] unit tests should be passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
