### ISSUE TITLE
[Discovery] BDD Claims Submission Process

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3621]
## User Story or Problem Statement
As a researcher/designer on the Benefits and Memorials team, I need to understand how the current Benefits Delivery at Discharge Claims submission process works so I can incorporate the findings in my research.

## Goal
_Identify current BDD process via conversations with BDD SMEs_

## Tasks
- [x] Meet with BDD SMEs (scheduled for 11/25)
- [x] Record findings in GH [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd)
- [x] _include additional tasks here_

## Acceptance Criteria
- [x] Met with BDD SMEs
- [x] Scheduled follow up discussion(s) 
- [x] Documented findings in GH

**Comment by kevinstachura** [comment]
Notes for the BDD initial meeting can be found [here.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd)

**Comment by YanaRoy** [comment]
@chrvalla - the link to Kevin's findings are above
