### ISSUE TITLE
[Research] Draft Research Plan - Veteran Top Tasks 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36219]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will help identify what Veteran top tasks are for use in future user research and product design on VA.gov. 

### Considerations
- The upcoming homepage redesign effort might change if/how top tasks are represented on the home page
- This should be focused on Top Tasks only 
- Possible card sort as an option (initial discussion point)

##  Tasks 
- [x] Draft research plan 
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback 
- [x] Draft recruitment emails for unmoderated card sort

## Acceptance Criteria 
- [x] Initial research plan drafted 
- [x] Share with PM/PO for review 
- [x] Draft research plan available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
Started working on research plan.

**Comment by cindymerrill** [comment]
Solicited tasks on Slack and received a LOT. Will need to sift through them and remove duplicates.

Asked questions on #research-ops re how to ask Perigean to recruit for an unmoderated card sort, and received some answers but not everything I wanted to know.

**Comment by cindymerrill** [comment]
Finished first draft of research plan (without any dates yet) and shared with Shawna and other UX designer for feedback.-

**Comment by cindymerrill** [comment]
Incorporated feedback from Shawna on my research plan. Will be talking with Shane Strassberg tomorrow about my recruiting specifications for the unmoderated card sort.

Drafted recruitment emails and shared with Shawna and Liz Lantz for feedback.

**Comment by cindymerrill** [comment]
I just split my research plan into two--one for the moderated part, and one for the unmoderated part. I had a great talk with Shane Strassberg this morning, and he said I need to do that for Perigean recruiting purposes. Plus, I’ve decided to do the moderated part first with fewer participants (5) to serve as an extended pilot of the card sort--to check on the intuitiveness of the cards, categories, and instructions before launching unmoderated to a large group of people.

I’m also waiting to hear back from Shane about the logistics of the card sort. He found a loophole that might enable us to have all unmoderated responses in the same card sort, as opposed to a separate (identical) copy of the card sort for each cohort with data that I'd then need to merge and analyze manually, but he needs to consult Lauren Alexanderson and Kevin Hoffman on this.

**Comment by cindymerrill** [comment]
UPDATE: Today I got clearance from Shane Strassberg at the VA to have ALL respondents in a single Optimal Sort card sort study as long as they’re kept separate as distinct cohorts within the study. To do this, you add a cohort-specific token to the activity link to specify which cohort as Optimal Workshop describes [here](https://support.optimalworkshop.com/en/articles/4529593-merge-data-from-more-than-one-study) and [here](https://support.optimalworkshop.com/en/articles/2626893-integrate-with-a-participant-recruitment-panel), so the URL will be slightly different for each. By doing this, I will be able to use Optimal Sort’s automatic data summary for ALL participants at once (and also subdivide by cohort, if I want)--saving me time manually downloading into a separate spreadsheet.

**Comment by cindymerrill** [comment]
I've incorporated feedback from another UX team member (Liz Lantz), and now I'm ready to share my research plans with our team. Would you be able to review them, @brianalloyd, before I share them with Dave for approval? Here are links to the two research plans: 

1. [Moderated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/research-plan.md)
2. [Unmoderated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-plan.md)

**Comment by brianalloyd** [comment]
Thanks @cindymerrill reviewing them now.

**Comment by brianalloyd** [comment]
Some feedback:
1. Only thing I noticed was OCTO and the Official term is OCTODE recommend changing when mentioned in the document. 
2. Card sort recruitment is 60, any evidence from previous card sorts on how accurate the rule of 50% is in these type of requests? I.e are we okay if we get all 60 or less then 30?

**Comment by cindymerrill** [comment]
Thanks for your feedback, @brianalloyd ! Here are my responses:

1. OCTO is used in the research plan template from Platform, and the link goes to [this page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/strategy#readme), which shows North Stars for OCTO, and that's what I'm specifying, not for OCTO-DE.
2. The recommendation for unmoderated recruiting from Platform is to recruit for double the number of participants you want. I'm fine with 60 participants (which is super unlikely), but if we get fewer than 30, I'll ask Perigean to try to recruit more people and keep the study open for longer.

Is this all of your feedback on both research plans, or should I expect more? Wondering when it's OK to share with Dave for approval, or whether I should wait until I have the task list finalized and the card sort built.

**Comment by cindymerrill** [comment]
Posted a research overview on slack here: https://dsva.slack.com/archives/C52CL1PKQ/p1645121414903169

**Comment by cindymerrill** [comment]
Shared my draft task list with Mikki Northuis for feedback. Currently have 43 tasks, which I'd ideally like to get down to 30 tasks for the card sort to decrease the cognitive load (per advice from Platform [here](https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html)).

**Comment by cindymerrill** [comment]
Revised top tasks list based on feedback from Shawna and Mikki. Hoping to talk with Mikki about her feedback and ideas for prioritizing which tasks to put into the card sort. 

Tomorrow I have a meeting scheduled with Meg Peters and Tracey Mulrooney (who works with Meg) to talk about the top tasks.

**Comment by cindymerrill** [comment]
Haven't received any feedback on my research plans from Dave Conlon. @brianalloyd Do you know if he's generally OK with my approach?

I'm planning to give an overview of my research plans tomorrow when I meet with Meg Peters and Tracey Mulrooney (who works with Meg) to talk about top tasks. 

I'll start planning the timeframe for each phase because Yana said I should be getting an Optimal Workshop login today (didn't happen, though), and I want to finish everything by April.

**Comment by cindymerrill** [comment]
Revised both [Moderated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/research-plan.md and [Unmoderated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-plan.md) research plans. Shared with Michelle and Dave S. for feedback, and plan to share with Dave C soon.

**Comment by cindymerrill** [comment]
Also updated the [outreach emails](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/outreach-emails.md) for the unmoderated research.

**Comment by cindymerrill** [comment]
Last Friday, Dave Conlon approved phase 1 research plan (moderated research), so I plan to launch recruiting today.
Dave asked for revisions to the participant recruiting cohorts in the phase 2 research plan (unmoderated research).

**Comment by cindymerrill** [comment]
Recruiting for phase 1 launched, and Perigean has scheduled most of the sessions already. 

Updated the cohorts for phase 2 and shared in slack for Dave Conlon's feedback.

FYI @michelle as standup updates

**Comment by cindymerrill** [comment]
Updated unmoderated research plan, task list, and survey based on learnings from the moderated research findings. Ready for Dave Conlon's approval so I can launch recruiting. @mmiddaugh @davidconlon

**Comment by davidconlon** [comment]
@cindymerrill Approved.
Thanks for your work on this!
