### ISSUE TITLE
[MCP] eslint (import/order)

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36220]
## Issue Description
Receiving following eslint warnings:

component-library import should occur before import of custom component - eslint ([import/order](https://github.com/import-js/eslint-plugin-import/blob/v2.24.2/docs/rules/order.md))

![Screen Shot 2022-01-31 at 12.36.05 PM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/18d3f71e-2402-4301-b9f3-3b93e8a53751)

Due a recent change by platform to enable some linting rules these warnings have been surfaced and should be addressed to ensure we adhere to best practices in our code.

---
## Tasks
- [ ] verify sort order for all MCP imports

## Acceptance Criteria
- [ ] warnings should be cleared
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per FE sync, this ticket can be closed- we have been addressing errors on a regular basis.
