### ISSUE TITLE
[MCP] eslint (react/jsx-no-bind)

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36224]
## Issue Description
Receiving following eslint warnings:

JSX props should not use arrow functions eslint ([react/jsx-no-bind](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md))

![Screen Shot 2022-01-31 at 12.59.44 PM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/96b02986-c758-4b78-b8d7-baea8a920ea1)

Due a recent change by platform to enable some linting rules these warnings have been surfaced and should be addressed to ensure we adhere to best practices in our code.

---
## Tasks
- [ ] verify changes required to clear warnings

## Acceptance Criteria
- [ ] warnings should be cleared
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
This warning has been disabled, but it is something we will consider moving forward.
