### ISSUE TITLE
eslint (react/prop-types)

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36223]
## Issue Description
Receiving the following eslint warnings for `react/prop-types` which is enabled [here](https://github.com/department-of-veterans-affairs/vets-website/blob/f9cb813c31b8965a929da329b878abffcd5cbc09/.eslintrc.js#L140)

'alertType' is missing in props validation eslint ([react/prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md))

![Screen Shot 2022-01-31 at 12.51.14 PM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/681e64f7-0b7d-4a2c-9ea2-c4a5632a2703)

Due a recent change by platform to enable some linting rules these warnings have been surfaced and should be addressed to ensure we adhere to best practices in our code.

---
## Tasks
- [ ] verify all components include propTypes

## Acceptance Criteria
- [ ] warnings should be cleared
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
