### ISSUE TITLE
NOD/HLR v2: Add content for empty lists

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36229]
## Description

If a Veteran does not have any contestable issues in the data from the API, a message "Sorry, we couldn't find any eligible issues", but no next steps are included. We need to add a paragraph below stating "If you'd like to add an issue for review, please select 'add a new issue' to get started."

![Screen Shot 2022-01-28 at 3 12 19 PM](https://user-images.githubusercontent.com/136959/151855520-a3ff6b23-dad8-4ca2-95b1-ed964b58d250.png)

## Tasks

- [ ] Add paragraph below no issues header
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
