### ISSUE TITLE
[MCP] eslint (react/jsx-one-expression-per-line)

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#36226]
## Issue Description
Receiving the following eslint warnings for `jsx-one-expression-per-line` which is enabled [here](https://github.com/department-of-veterans-affairs/vets-website/blob/2643d6eb138520746b67c8c45e455dd338902229/.eslintrc.js#L138)

`{data}` must be placed on a new line eslint ([react/jsx-one-expression-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-one-expression-per-line.md))

![Screen Shot 2022-01-31 at 1.29.57 PM.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/9191ce5b-386d-429c-baef-211aa6ba8d8b)

Due a recent change by platform to enable some linting rules these warnings have been surfaced and should be addressed to ensure we adhere to best practices in our code.

---
## Tasks
- [ ]  clear warnings for FSR, MCP and Debt Letters components

## Acceptance Criteria
- [ ] warnings should be cleared
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Has been addressed over time
