### ISSUE TITLE
CT - Add High Schools to the Type of Institutions filter

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#36247]
## Issue Description
EDU requested adding High Schools as part of the Type of institutions filter.

---
## Tasks
- [ ] Dev to add High Schools as part of the Type of institutions filter
- [ ] QA to validate High Schools are located at the bottom of the list, below Correspondence
- [ ] QA must validate High Schools is unchecked by default
- [ ] QA must validate the checkbox works and updates are made in real time when a Veteran selects it

## Acceptance Criteria
- [ ]  High Schools must be unchecked by default
---
## How to configure this issue
- [ ] **Labeled with Type** (`request`)

![image.png](https://images.zenhubusercontent.com/60e78c6b02152f0a04637267/4e752622-841d-4d43-932c-54103f0cab96)

**Comment by dsrr47** [comment]
Is the option "high school" supported by the vets-API? Is there a backend lift here as well?

**Comment by AdamFreemer** [comment]
I've been working the filter redesign and you might want to look here on GIDS: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/dc019114165e5ad94d9204ae05426a761022f231/app/models/institution.rb

The filter information passes through vets-api to the GIDS app where it seems to be correlated to the csv files they upload. I think you might want to check if this type of attribute is available first in the data they're working with and what field it would correlate to.

**Comment by dsrr47** [comment]
So it seems we need to add a new type for high schools in GIDS. Right now high schools exist in the search by they don't have a special type they are all just typed as "public".  Do you know who I need to talk with about changing this?

**Comment by dsrr47** [comment]
There are 6 institution types defined and searchable and isn't an Institution type for "High School" isn't one of them. It looks like high schools for the most part are labeled as "Public" institution types. 

In order to be able to search or filter high schools they will need to be defined in the search Params from GIDS [here](https://github.com/department-of-veterans-affairs/gibct-data-service/blob/dc019114165e5ad94d9204ae05426a761022f231/app/models/institution.rb) and maybe other areas of the vets-api but also where ever the actual raw data lives will need to be updated. Adam mentioned above it may be a CSV file and if thats the case that would also need to be updated to have all the high schools have an institution type of high school added to its attributes.

**Comment by dsrr47** [comment]
The best way to identify a high school is to look at the second number of the institution ID if the second number is a 7 then the institution is a high school. We will need to create a weams filter that filters high schools using this method and then add UI on the front end to make the filter accessible.

**Comment by AdamFreemer** [comment]
@dsrr47 Could you give me a bit more specifics on what Institution ID you are referring to? I'll assume you're referring to the Institution model object for GIDS? There's a lot of fields. Here's the fields on the Institution model in GIDS:

```
  create_table "institutions", id: :serial, force: :cascade do |t|
    t.integer "version"
    t.string "institution_type_name"
    t.string "facility_code"
    t.string "institution"
    t.string "city"
    t.string "state"
    t.string "zip"
    t.string "country"
    t.boolean "flight"
    t.boolean "correspondence"
    t.float "bah"
    t.string "cross"
    t.string "ope"
    t.string "ope6"
    t.string "insturl"
    t.string "vet_tuition_policy_url"
    t.integer "pred_degree_awarded"
    t.integer "locale"
    t.integer "gibill"
    t.integer "undergrad_enrollment"
    t.boolean "yr"
    t.boolean "student_veteran"
    t.string "student_veteran_link"
    t.boolean "poe"
    t.boolean "eight_keys"
    t.boolean "dodmou"
    t.boolean "sec_702"
    t.string "vetsuccess_name"
    t.string "vetsuccess_email"
    t.boolean "credit_for_mil_training"
    t.boolean "vet_poc"
    t.boolean "student_vet_grp_ipeds"
    t.boolean "soc_member"
    t.string "va_highest_degree_offered"
    t.float "retention_rate_veteran_ba"
    t.float "retention_all_students_ba"
    t.float "retention_rate_veteran_otb"
    t.float "retention_all_students_otb"
    t.float "persistance_rate_veteran_ba"
    t.float "persistance_rate_veteran_otb"
    t.float "graduation_rate_veteran"
    t.float "graduation_rate_all_students"
    t.float "transfer_out_rate_veteran"
    t.float "transfer_out_rate_all_students"
    t.float "salary_all_students"
    t.float "repayment_rate_all_students"
    t.float "avg_stu_loan_debt"
    t.string "calendar"
    t.integer "tuition_in_state"
    t.integer "tuition_out_of_state"
    t.integer "books"
    t.boolean "online_all"
    t.float "p911_tuition_fees"
    t.integer "p911_recipients"
    t.float "p911_yellow_ribbon"
    t.integer "p911_yr_recipients"
    t.boolean "accredited"
    t.string "accreditation_type"
    t.string "accreditation_status"
    t.boolean "caution_flag"
    t.string "caution_flag_reason"
    t.integer "complaints_facility_code"
    t.integer "complaints_financial_by_fac_code"
    t.integer "complaints_quality_by_fac_code"
    t.integer "complaints_refund_by_fac_code"
    t.integer "complaints_marketing_by_fac_code"
    t.integer "complaints_accreditation_by_fac_code"
    t.integer "complaints_degree_requirements_by_fac_code"
    t.integer "complaints_student_loans_by_fac_code"
    t.integer "complaints_grades_by_fac_code"
    t.integer "complaints_credit_transfer_by_fac_code"
    t.integer "complaints_credit_job_by_fac_code"
    t.integer "complaints_job_by_fac_code"
    t.integer "complaints_transcript_by_fac_code"
    t.integer "complaints_other_by_fac_code"
    t.integer "complaints_main_campus_roll_up"
    t.integer "complaints_financial_by_ope_id_do_not_sum"
    t.integer "complaints_quality_by_ope_id_do_not_sum"
    t.integer "complaints_refund_by_ope_id_do_not_sum"
    t.integer "complaints_marketing_by_ope_id_do_not_sum"
    t.integer "complaints_accreditation_by_ope_id_do_not_sum"
    t.integer "complaints_degree_requirements_by_ope_id_do_not_sum"
    t.integer "complaints_student_loans_by_ope_id_do_not_sum"
    t.integer "complaints_grades_by_ope_id_do_not_sum"
    t.integer "complaints_credit_transfer_by_ope_id_do_not_sum"
    t.integer "complaints_jobs_by_ope_id_do_not_sum"
    t.integer "complaints_transcript_by_ope_id_do_not_sum"
    t.integer "complaints_other_by_ope_id_do_not_sum"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "f1sysnam"
    t.integer "f1syscod"
    t.string "ialias"
    t.string "approval_status"
    t.boolean "school_closing", default: false
    t.date "school_closing_on"
    t.string "school_closing_message"
    t.boolean "stem_offered", default: false
    t.boolean "priority_enrollment"
    t.boolean "online_only"
    t.boolean "independent_study"
    t.boolean "distance_learning"
    t.string "address_1"
    t.string "address_2"
    t.string "address_3"
    t.string "physical_address_1"
    t.string "physical_address_2"
    t.string "physical_address_3"
    t.string "physical_city"
    t.string "physical_state"
    t.string "physical_zip"
    t.string "physical_country"
    t.integer "dod_bah"
    t.boolean "approved", default: false
    t.boolean "vet_tec_provider", default: false
    t.boolean "closure109"
    t.boolean "preferred_provider", default: false
    t.boolean "stem_indicator", default: false
    t.string "campus_type"
    t.string "parent_facility_code_id"
    t.bigint "version_id"
    t.boolean "complies_with_sec_103"
    t.boolean "solely_requires_coe"
    t.boolean "requires_coe_and_criteria"
    t.integer "count_of_caution_flags", default: 0
    t.string "section_103_message"
    t.string "poo_status"
    t.integer "hbcu"
    t.integer "hcm2"
    t.integer "menonly"
    t.float "pctfloan"
    t.integer "relaffil"
    t.integer "womenonly"
    t.string "institution_search"
    t.integer "rating_count", default: 0
    t.float "rating_average"
    t.float "latitude"
    t.float "longitude"
    t.boolean "employer_provider"
    t.boolean "school_provider"
    t.string "in_state_tuition_information"
    t.boolean "vrrap"
```

**Comment by AdamFreemer** [comment]
@AdamFreemer Here's an example Institution record for reference if it helps: 
```
Institution Load (1.3ms)  SELECT "institutions".* FROM "institutions" ORDER BY "institutions"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<Institution id: 1, version: 1, institution_type_name: "OJT", facility_code: "00000146", institution: "ASSOCIATION OF COMMUNICATIONS & ELECTRONICS", city: "VIRGINIA BEACH", state: "VA", zip: "23462", country: "USA", flight: false, correspondence: false, bah: 1733.0, cross: nil, ope: nil, ope6: nil, insturl: nil, vet_tuition_policy_url: nil, pred_degree_awarded: nil, locale: nil, gibill: nil, undergrad_enrollment: nil, yr: false, student_veteran: nil, student_veteran_link: nil, poe: nil, eight_keys: nil, dodmou: nil, sec_702: nil, vetsuccess_name: nil, vetsuccess_email: nil, credit_for_mil_training: nil, vet_poc: nil, student_vet_grp_ipeds: nil, soc_member: nil, va_highest_degree_offered: nil, retention_rate_veteran_ba: nil, retention_all_students_ba: nil, retention_rate_veteran_otb: nil, retention_all_students_otb: nil, persistance_rate_veteran_ba: nil, persistance_rate_veteran_otb: nil, graduation_rate_veteran: nil, graduation_rate_all_students: nil, transfer_out_rate_veteran: nil, transfer_out_rate_all_students: nil, salary_all_students: nil, repayment_rate_all_students: nil, avg_stu_loan_debt: nil, calendar: nil, tuition_in_state: nil, tuition_out_of_state: nil, books: nil, online_all: nil, p911_tuition_fees: nil, p911_recipients: nil, p911_yellow_ribbon: nil, p911_yr_recipients: nil, accredited: nil, accreditation_type: nil, accreditation_status: nil, caution_flag: nil, caution_flag_reason: nil, complaints_facility_code: nil, complaints_financial_by_fac_code: nil, complaints_quality_by_fac_code: nil, complaints_refund_by_fac_code: nil, complaints_marketing_by_fac_code: nil, complaints_accreditation_by_fac_code: nil, complaints_degree_requirements_by_fac_code: nil, complaints_student_loans_by_fac_code: nil, complaints_grades_by_fac_code: nil, complaints_credit_transfer_by_fac_code: nil, complaints_credit_job_by_fac_code: nil, complaints_job_by_fac_code: nil, complaints_transcript_by_fac_code: nil, complaints_other_by_fac_code: nil, complaints_main_campus_roll_up: nil, complaints_financial_by_ope_id_do_not_sum: nil, complaints_quality_by_ope_id_do_not_sum: nil, complaints_refund_by_ope_id_do_not_sum: nil, complaints_marketing_by_ope_id_do_not_sum: nil, complaints_accreditation_by_ope_id_do_not_sum: nil, complaints_degree_requirements_by_ope_id_do_not_sum: nil, complaints_student_loans_by_ope_id_do_not_sum: nil, complaints_grades_by_ope_id_do_not_sum: nil, complaints_credit_transfer_by_ope_id_do_not_sum: nil, complaints_jobs_by_ope_id_do_not_sum: nil, complaints_transcript_by_ope_id_do_not_sum: nil, complaints_other_by_ope_id_do_not_sum: nil, created_at: "2021-10-21 18:09:34", updated_at: "2021-10-21 18:09:34", f1sysnam: nil, f1syscod: nil, ialias: nil, approval_status: nil, school_closing: false, school_closing_on: nil, school_closing_message: nil, stem_offered: false, priority_enrollment: nil, online_only: nil, independent_study: nil, distance_learning: nil, address_1: "5241 Princess Anne Road", address_2: "Suite 110", address_3: nil, physical_address_1: "5241 Princess Anne Road", physical_address_2: "Suite 110", physical_address_3: nil, physical_city: "VIRGINIA BEACH", physical_state: "VA", physical_zip: "23462", physical_country: "USA", dod_bah: 1641, approved: false, vet_tec_provider: false, closure109: nil, preferred_provider: false, stem_indicator: false, campus_type: "Y", parent_facility_code_id: nil, version_id: 1, complies_with_sec_103: nil, solely_requires_coe: nil, requires_coe_and_criteria: nil, count_of_caution_flags: 0, section_103_message: nil, poo_status: nil, hbcu: nil, hcm2: nil, menonly: nil, pctfloan: nil, relaffil: nil, womenonly: nil, institution_search: "ASSOCIATION  COMMUNICATIONS  ELECTRONICS", rating_count: 0, rating_average: nil, latitude: nil, longitude: nil, employer_provider: true, school_provider: false, in_state_tuition_information: nil, vrrap: nil, distance: nil>
```

**Comment by dsrr47** [comment]
Yeah I think you're in the right place. When we talked he showed me his CSV file that he said he uses for GIDS. He had an institution id there but I don't it here.

**Comment by AdamFreemer** [comment]
I'm not sure if this is truly delineating high schools. I grabbed all facility_codes with 2nd digit 7 and found many questionable institutions.
```
[["facility_code", "17833338"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Institution id: 26510, version: 1, institution_type_name: "PUBLIC", facility_code: "17833338", institution: "INTERMEDIATE UNIT ONE", city: "COAL CENTER", state: "PA", zip: "15423", country: "USA", flight: false, correspondence: false, bah: 1922.0, cross: "465733", ope: "00337912", ope6: "03379", insturl: nil, vet_tuition_policy_url: nil,



[["facility_code", "17178040"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Institution id: 26399, version: 1, institution_type_name: "PUBLIC", facility_code: "17178040", institution: "EDGEFIELD ADULT EDUCATION/JOHNSTON LEARNING CENTER",



[["facility_code", "17165940"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Institution id: 26386, version: 1, institution_type_name: "PUBLIC", facility_code: "17165940", institution: "ROCK HILL DISTRICT 3 ADULT EDUCATION", city: "ROC



Institution Load (0.5ms) SELECT "institutions".* FROM "institutions" WHERE "institutions"."facility_code" = $1 LIMIT $2 [["facility_code", "17526201"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Institution id: 26429, version: 1, institution_type_name: "PUBLIC", facility_code: "17526201", institution: "CHATTAHOOCHEE VALLEY COMMUNITY COLLEGE-ADULT EDUCA...", city: "PHENIX CITY", state: "AL", zip: "36869", country: "USA", flight: false, correspondence: false, bah: 1304.0, cross: "101028", ope: "01218200", ope6: "12182", insturl: "www.cv.edu", vet_tuition_policy_url: nil, pred_degree_awarded: 2, locale: 41, gibill: nil, undergrad_enrollment: 1446, yr: false, student_veteran: nil, student_veteran_link: nil, poe: false, eight_keys: nil, dodmou: true, sec_702: true, vetsuccess_name: nil, vetsuccess_email: nil, credit_for_mil_tr



[["facility_code", "57000451"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Institution id: 69327, version: 1, institution_type_name: "PRIVATE", facility_code: "57000451", institution: "GRADUATE MANAGEMENT ADMISSION COUNCIL", city: "MCLEAN", state: "VA", zip: "22102", country: "USA", flight: false, correspondence: false, bah: 2444.0, cross: nil, ope: nil, ope6: nil, insturl: nil, vet_tuition_policy_url: nil, pred_degree_awarded: nil, locale: nil, gibill: nil, undergrad_enrollment: nil, yr: false, student_veteran: nil, student_veteran_link: nil, poe: nil, eight_keys: nil, dodmou: nil, sec_702:
```


![Screen Shot 2022-02-17 at 9.28.46 AM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/2fd43e27-96eb-4de2-9bff-d1e8d36aa30c)

**Comment by AdamFreemer** [comment]
Awaiting more info on how to explicitly determine high schools from the Institution table in the GIDS database. 

Possibly analysts on the VA side reaching out to https://nces.ed.gov/globallocator/ or Department of Education / https://www2.ed.gov/rschstat/landing.jhtml?src=pn as a possiibilty?

**Comment by AdamFreemer** [comment]
Meeting today with Brian from VA should provide additional information on needed data to determine high school status of institutions.

**Comment by AdamFreemer** [comment]
As per discussion with Brian today, facility code second digit '7' was incorrect for filtering High Schools. '5' is the correct digit as per documentation: https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001048/content/554400000080120/Part-9:-Chapter-8---Records,-Files,-and-Reports

Note: above table must be viewed through VA intranet. 

![Screen Shot 2022-02-25 at 3.29.13 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/406a176d-63e8-436e-aa31-63ba47bce0a5)

**Comment by AdamFreemer** [comment]
"5" is not an exclusive High School selection according to documentation, but a "non-college Degree School" which Brian stated will work for their needs. So requirement now for this task will be filtering facility code 2nd digit by code 5 and displaying results when new "High School" checkbox is checked. @daltonatkins @mrblanco1

**Comment by AdamFreemer** [comment]
FYI - On staging, this query is operating correctly per spec: https://staging.va.gov/education/gi-bill-comparison-tool/?search=name&name=high%20school&excludedSchoolTypes%5B%5D=PUBLIC&excludedSchoolTypes%5B%5D=FOR%20PROFIT&excludedSchoolTypes%5B%5D=PRIVATE&excludedSchoolTypes%5B%5D=FOREIGN&excludedSchoolTypes%5B%5D=FLIGHT&excludedSchoolTypes%5B%5D=CORRESPONDENCE

We are only filtering schools with a 5, second digit facility code.

**Comment by jfinnern** [comment]
Validated in staging
Test run: https://dsvavsp.testrail.io/index.php?/runs/view/3084&group_by=cases:section_id&group_order=asc
Test case: [CT - Add High Schools to the Type of Institutions filter.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8262504/CT.-.Add.High.Schools.to.the.Type.of.Institutions.filter.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT Passed 3/17/2022.
