### ISSUE TITLE
Create Facility Locator Errors Training Module for Tier 1

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36257]
## Issue Description
_In an going effort to provide more training for Tier 1 to better help Veterans, we are creating training modules for key areas of consistent support requests_

---
## Tasks
- [x] _Create Facility Locator Errors training module_
- [x] _Deliver Facility Locator Errors training module to VEO_

## Acceptance Criteria
- [x] _Facility Locator Errors training module is created_
- [x] _Facility Locator Errors training module is delivered to VEO_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
[FacilitiesLocator_errors_presentation_012022.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7990349/FacilitiesLocator_errors_presentation_012022.pptx)

**Comment by jwoodman5** [comment]
Delivered to VEO.
