### ISSUE TITLE
Support Reporting - Product Category Mapping in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36252]
## Issue Description
_To make our Salesforce support data more usable by our primary users, VFS teams, we need to make the data easier to understand and segment by product. This effort is to map existing Salesforce categories and sub-categories to known products_

---
## Tasks
- [x] _Create filter table for product names_
- [x] _Map existing Salesforce categories and sub-categories to know products where possible_
- [x] _Publish (above) in DOMO_

## Acceptance Criteria
- [x] _DOMO users can select a product filter in the Contact Center Data dashboard_
- [x] _DOMO users can filter contact center data by product name_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[VA Products Confluence Page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview)
