### ISSUE TITLE
New Medallia Survey Questions - Approval Process Discovery

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36259]
## Issue Description
_We currently have a couple of different teams interested in using questions, which are not on our PRA approved list, on Medallia custom surveys. We need to explore the feasibility and process for making modifications to existing questions (if possible) and/or initiating a new PRA approval process for these questions._

---
## Tasks
- [ ] _Discover and document if there is any flexibility with already (PRA) approved Medallia survey questions_
- [ ] _Discover and document general PRA approval process for Medallia survey questions_

## Acceptance Criteria
- [ ] _Flexibility, if any, for modifying existing PRA approved M ] edallia survey questions is documented in Confluence_
- [ ] _PRA approval process is generally documented with any relevant resource links in Confluence_
- [ ] _Interested teams are updated with possibilities, process, and timeline information_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
