### ISSUE TITLE
Medallia Reporting Dashboard Focus Group

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36253]
## Issue Description
_Now that our Medallia reporting dashboard has been live in DOMO for nearly a month, we want to host a focus group to gather feedback from our most frequent users, so that we can make improvements_

---
## Tasks
- [x] _Host Medallia reporting dashboard focus group_
- [x] _Document findings in Confluence_

## Acceptance Criteria
- [x] _Medallia reporting dashboard focus group is held and findings are documented in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
