### ISSUE TITLE
Create EVSS Module for Tier 1 Training

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36256]
## Issue Description
_In an going effort to provide more training for Tier 1 to better help Veterans, we are creating training modules for key areas of consistent support requests_

---
## Tasks
- [x] _Create EVSS training module_
- [x] _Deliver EVSS training module to VEO_

## Acceptance Criteria
- [x] _EVSS training module is created_
- [x] _EVSS training module is delivered to VEO_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
[EVSS_errors_presentation_v3_011922_.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7990405/EVSS_errors_presentation_v3_011922_.pptx)
