### ISSUE TITLE
Update Medallia Dashboard Segmenting - Modernized/Non-Modernized

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36258]
## Issue Description
_After implementing a POC for segmenting the Medallia reporting dashboard for modernized and non-modernized VA.gov, we are already receiving feedback minor updates. After a focus group already planned for 2/3, we will make updates to improve usability for this new segmenting options_

---
## Tasks
- [ ] _Update the Medallia reporting dashboard in DOMO to reflect feedback on modernized/non-modernize VA.gov segmenting_
- [ ] _TBD_

## Acceptance Criteria
- [ ] _TBD_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
