### ISSUE TITLE
[4 hours] Spike on Updating Performance Dashboard to Medallia CSAT

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#36255]
## Issue Description
_The VA.gov performance dashboard has historically reported on ForeSee satisfaction scores because ForeSee was the historical survey provider on VA.gov. With our transition to Medallia surveys and plans to sunset ForeSee this year, we need to convert the scoring model and data source to utilize Medallia satisfaction scores. This effort represents a spike to better understand key technical considerations and help us plan the work more accurately_

---
## Tasks
- [x] _Get Historical overview (from @jwoodman5) of VA.gov satisfaction scoring and reporting_
- [x] _Inspect satisfaction scoring code on the [VA.gov Performance Dashboard](https://www.va.gov/performance-dashboard/)_
- [x] _Investigate data ingestion options for the VA.gov performance dashboard_
- [x] _Investigate Medallia data source availability_ 
- [ ] _Document findings and technical recommendations in Confluence_

## Acceptance Criteria
- [ ] _Technical abilities and constraints for updating the VA.gov Performance Dashboard are documented in Confluence_
- [ ] _Plan of action for updating the VA.gov Performance Dashboard is documented in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@aubreyarcangel Feel free to do the honors of checking these last few boxes and closing it out. Thanks.
