### ISSUE TITLE
Datadog Access Request

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36260]
## Description
The Claims & Appeals team owns a product portfolio of seven VA.gov applications. and would like access to Datadog in order to aid our troubleshooting efforts. 

## Background/context 
Two of our products are among the most visited on VA.gov (original claims and the claim status tool). As such, we garner a significant number of support tickets and would like to be able to use the latest tools to help us resolve issues more quickly. A demonstration of Datadog showed us information not readily or as easily available in our other tools.

---
## Tasks
- [ ] We'd like to request Datadog access for Backend Engineers: Michel McDonald (michel.mcdonald@adhocteam.us) and Csaba Nèmeth (csaba.nemeth@gcio.com). If PM's are also allowed access: ronnie.henry@gcio.com

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by zachclarity** [comment]
I am working with admins to get the process moving.

**Comment by zachclarity** [comment]
@vhenry07 We currently are defining a process for providing access to Datadog for VFS teams.  Access is not given at this time and this issue will be addressed after we define our process.   We are working to enhance the troubleshooting guidance to help with the core need.

**Comment by jhouse-solvd** [comment]
@vhenry07 - I've added your request to an initiative that is being planned around providing VFS teams with access to Datadog. We'll be discussing this as part of quarterly planning. We'll be able to provide more information then. 

Thank you for your patience while we evaluate this.

**Comment by rmtolmach** [comment]
Hey @jhouse-solvd, any update on this?

**Comment by tpharrison** [comment]
Hi @jhouse-solvd - here is our [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43996) outlining our request for Datadog access.  Let me know if you need anything else.  Thanks!

**Comment by jhouse-solvd** [comment]
@rmtolmach - This request can be fulfilled once Datadog is made available to VFS teams as part of #33081.
