### ISSUE TITLE
Update Test Results Ingestion Mechanism to include Product ID assignment to test results

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#36275]
## Issue Description
Our current ingestion mechanism for test results applies an application name to our test results in-flight and then uploads the results to BigQuery. This is powered by an application list, generated during `vets-website` CI GHA workflow, that currently ingests the name from the manifest and it's slug styled name. We need to alter this to allow for matching with routes to tests, and associating these with product IDs instead of names, that will be used to match to our master product directory.

---
## Tasks
- [x]  Update product list generation on `vets-website` to include file paths of manifests
- [x]  Update dashboard data repo to read file paths and match based on the spec file path living in the same directory as the manifest file, in place of the current method.
- [x]  Update the BigQuery Schema for the app list to account for a file path being uploaded.

Once manifests are updated with IDs:
- [x]  Update the BigQuery Schema for test results to account for an added-on product ID of a yet undetermined name
- [x]  Update the ingestion mechanism to target the ID in place of the name from the manifests.
- [x]  Update product list generation on `vets-website` to include the IDs from the manifests.

## Acceptance Criteria
- [x]  Our test results being uploaded to BigQuery contain a product ID on any results that are from specs that have a manifest in the same directory.
- [x]  Our app list from vets-website contains file paths and IDs.

**Comment by CBonade** [comment]
The app list generation script on `vets-website` has had proper alterations made to it and it has been merged in. The file paths of the manifests are being attached and made a part of the app list. The app list is uploaded to BigQuery and the file path column has been added to the existing table `vfs_products` to hold that data.

The `testing-tools-team-dashboard-data` ingestion mechanism for results assigns a product name to each test result. The matching algorithm for this has been changed to source off the newly added manifest file paths and is compared to the file path of the test spec in question. 

Once the manifests and product list are updated with IDs for each product, the ID can be added to the app list in vets-website, and then the name assignment in the dashboard-data repo can be switched to attach this ID to the rest results. The ID column will need to be added to the test results in BigQuery as well.

**Comment by CBonade** [comment]
This is working properly for contract tests, but there's an unrelated problem with Cypress tests that are stopping the results from being inserted into BigQuery. Will diagnose this further on Monday. https://github.com/department-of-veterans-affairs/vets-website/pull/20132 PR is open for this update awaiting review.

**Comment by pjhill** [comment]
Oh my, already 41000 rows with `product_id`s in the Cypress test results table. Nice
