### ISSUE TITLE
Create Dashboards for 10 Selected Products

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#36288]
# Description
Once we have a list of 10 products that would be a good fit for our QA Product Dashboard, we need to first create a POC for a single product. Next, we work out any issues with the POC. Lastly, we use the POC to guide the creation of the remaining 9 QA Product dashboards.

## Tasks
- [x] Create a POC QA Product Dashboard using VAOS as an example
- [x] Have the team dogfood the dashboard to uncover issues
- [x] Resolve any issues and refine the visualizations on the POC dashboard
- [x] Show the POC dashboard to the VFS team (VAOS) and collect feedback
- [x] Triage feedback and address any important issues
- [x] Use the POC to guide the creation of the remaining 9 product dashboards

## Acceptance Criteria
- [x] 10 QA Product Dashboards are available in Domo for use by the VFS teams that own those products

**Comment by pjhill** [comment]
Let's hold off on this effort until we have finalized the POC for VAOS.

**Comment by CBonade** [comment]
These 9 dashboards are created. They're all linked from the main QA Dashboard page. Doing some refinement to them but in general they are operable.

**Comment by pjhill** [comment]
The MVP of these 10 product dashboards has been completed.
