### ISSUE TITLE
Standardize, Streamline & Visualize Dashboard Request Process

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36294]
## Issue Description

PMs have had challenges with the current Github ticket and spreadsheet templates for Std  Dashboard Requests.  Information is often missing or not completed correctly.  As part of ongoing training and onboarding we want to make this process easier so there is less back and forth between teams needed.  We also feel the current process may be a barrier for some product requests.  In addition we are beginning to get requests for product changes to existing standardized dashboards, we need to create a process for those requests so we can easily track and complete.
---
## Tasks
- [x] Github ticket template is updated so it is easier to understand and complete @jonathan-epstein13 
- [x] Spreadsheet template is revised so it is easier to understand and provide required information @pavanhothi 
- [x] Create a Github template for changes/updates to current standardized dashboards @jonathan-epstein13 
- [x] Create a flowchart slide to illustrate process flow and how to know if you qualify for a standardized dashboard @chloedotbrown 
- [x] Update team page on platform website and confluence as applicable @jonathan-epstein13 
- [x] Present changes in ToTs and End of Sprint Demo @michelle-dooley 

## Acceptance Criteria
- [x] The above tasks have been completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Assigned ownership of specific tasks, see above.

**Comment by jonathan-epstein13** [comment]
Created drafts for the assigned Github Template Changes and will create a shorter version of current template for Updated KPI Dashboard Requests.

**Comment by jonathan-epstein13** [comment]
[[BETA] GITHUB TEMPLATE CHANGES](https://docs.google.com/document/d/1UQQoSU8o2mwUZZYwdeG7UOho63UvcEE8LJV7s3-3c3Q/edit)

Let me know what you all think. I have added some things, removed some, made comments, and suggestions. Open to discuss. Working on a shorter version for a `Update KPI Standard Dashboards` Github template

**Comment by chloedotbrown** [comment]
Hi all! I've added suggestions and comments on the Github templates for [new dashboards](https://docs.google.com/document/d/1UQQoSU8o2mwUZZYwdeG7UOho63UvcEE8LJV7s3-3c3Q/edit) and [dashboard updates](https://docs.google.com/document/d/1cjc2GD0EmhlLhvlP1vDSSGHCsZY6p3YvErrEQWb7jmo/edit). If folks have any questions about the changes, feel free to reach out!

**Comment by jonathan-epstein13** [comment]
Thank you @chloedotbrown I appreciate your comments and suggestions. I'll look them all over and respond back. So far, they look great! Always good to have a fresh pair of eyes. 👍

**Comment by pavanhothi** [comment]
Linked below are the updated versions of the spreadsheet templates for standard KPI dashboard requests, and for edge case KPI dashboard requests. Also attached is a document with notes on the updates/changes made. Please let me know what you think and any ideas on possible additional changes. 

https://docs.google.com/spreadsheets/d/10MkG6sR46Vbs6vdOmuElRS4p2U7F8L6kKtAfONyUJd0/edit#gid=0

https://docs.google.com/spreadsheets/d/11in9XPXO4N023W-16OnlPLezTWiuQQNCN5Hm_AA_-JE/edit#gid=0

[Dashboard request spreadsheet templates updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8073366/Dashboard.request.spreadsheet.templates.updates.docx)

**Comment by chloedotbrown** [comment]
Here's the [dashboard request flowchart](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p) - I'll be creating the edge case template and adding the link later this afternoon my time, but wanted to share before other people's Tuesdays wrapped up!

I think this could be a useful tool to embed somewhere in our [Customer Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo), drop in the #vfs-analytics Slack channel, or embed in other slide presentations. Let me know if you have any questions or edits!

**Comment by michelle-dooley** [comment]
Love the visualization!!

I'm going to schedule a quick meeting to review template changes (new requests, changes requests and excel spreadsheet).  Just want to make sure we covered all our bases and are all aligned on the changes before we publish.

**Comment by jonathan-epstein13** [comment]
Attached are the [Corrected New KPI Dashboard Request Template](https://docs.google.com/document/d/1dSgt-VWUvtvFclHm67ic_FfLyFr_idHNzf87_Nv68Zk/edit) and [Corrected Update KPI Dashboard Request Template](https://docs.google.com/document/d/1VNw3f-_tL9_NBAZeDzywhfF824rcpKWwYjAlenuqy9w/edit). Let me know if there are other changes that can be made. Looking forward to our discussion to finalize the changes!

**Comment by jonathan-epstein13** [comment]
[VSP Analytics & Insights Acceptance Criteria](https://docs.google.com/document/d/1CkKNzoM9N6jlU0ekQnLKsa91lk3POHCWt0VAooVrBSE/edit) To be added to our confluence page.

**Comment by pavanhothi** [comment]
Made changes to both spreadsheet templates based off what we discussed in our meeting today:
- Moved instructions to separate tab
- Eased away from the great deal of bold text and borders
- Changed highlighted fill color to more subdued yellow
- Removed unnecessary instructions/info from Forms and Content tabs, and added to instructions tab as needed

Here are the links again to the templates:
[KPI Dashboard Template](https://docs.google.com/spreadsheets/d/10MkG6sR46Vbs6vdOmuElRS4p2U7F8L6kKtAfONyUJd0/edit#gid=1281179530) 
[Edge Case KPI Dashboard Template](https://docs.google.com/spreadsheets/d/11in9XPXO4N023W-16OnlPLezTWiuQQNCN5Hm_AA_-JE/edit#gid=1428771308)

Also drafted up a Google Forms version of the KPI Dashboard Template in case we do choose to go down that route if it works as well if not better for our needs than the spreadsheet templates. Here is a link to the [Form](https://forms.gle/iGArfBfjuTm2jm386). I've also added everyone on this ticket as collaborators to the form just in case. Any feedback/ideas/suggestions would be greatly appreciated!

**Comment by michelle-dooley** [comment]
@pavanhothi @jonathan-epstein13 and @chloedotbrown I've been thinking about this process and have made some revisions to how I think we can consolidate.  I think we only need one worksheet template for standard and edge case requests.  We cam add the edge case specific questions in the edge case worksheet template to the edge case github ticket instead.  Then we only have one version of the worksheet.  I also played with the worksheet a bit based on this.  Based on this worksheet I think we may be able to remove some of the checkboxes in the github ticket but let's discuss.  I will get some time on our calendars Monday to discuss.  I would like to finalize and share in ToTs and/or Demo day next week.  Thanks for all your work on this!!

https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988

**Comment by michelle-dooley** [comment]
@chloedotbrown did you create a new edge case dashboard as mentioned above?  If not, @jonathan-epstein13 can you work on creating based on the changes we made to the standard. The additional information we will need added to the edge case github template is:
- What does your team consider a completed task? (example:  clicking submit button)
- Who is your product's main user base?
- Why does your product require an edge case? (example:  form funnel uses combination of pages and events)
- Does this product currently have a Domo dashboard?  If yes please add link.

**Comment by chloedotbrown** [comment]
@michelle-dooley + team - I've added the product questions above to the [Edge Case Request ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-edge-case-dashboard.md). Feel free to edit/refine as needed!

**Comment by jonathan-epstein13** [comment]
GitHub Templates are updated, but still waiting on the access to be able to edit the platform page via the #vsp-confluence channel. Posted my question about how to edit in the channel and waiting on confirmation. Will update the templates when complete.

**Comment by jonathan-epstein13** [comment]
3/3: Confluence is updated with the [GitHub Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D), excel spreadsheet, and the [google doc](https://docs.google.com/spreadsheets/d/1dIh-MVmVYCc2mZ_b_8y-cPVZB5-8RIShuOP_ng9uqAA/edit#gid=1796144149) in their respective places. Waiting on approval to have the new platform page go live. Will update once live on the platform site.

**Comment by michelle-dooley** [comment]
Final  update to Platform website complete.  Closing ticket.
