### ISSUE TITLE
Identify/Review "Other" (legacy) Dashboards still in use that have/can have Std Dashboards to replace

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36298]
## Issue Description

There are still a large % of teams viewing/utilizing legacy/custom dashboards.  In an effort to move as many dashboard views as possible to the standardized dashboards we need to identify/review those most frequently viewed , determine if they can be replaced by a standardized dashboard and identify common metrics for possible MVP enhancements.    

## Tasks
- [ ] Identify what "other" dashboards are still in frequent use
- [ ] Can a standardized dashboard replace
- [ ] Identify common metrics for MVP enhancements

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnny-jesensky-adhoc** [comment]
Possibly consider in the future -- closing this out.
