### ISSUE TITLE
Plan Office Hours Lightning Talk Series

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36296]
## Issue Description
User research unveiled that many PMs are still struggling with the capabilities of the Domo dashboards and are often pulling specific data points out, tracking and creating their own custom reports.  We would like to introduce lightning talks as part of standard office hours to address some the training challenges we heard as part of our user research.
---
## Tasks
- [x] Brainstorm on potential topics to explain or demo
- [x] Create training materials for each topic (as applicable)
- [x] Create training schedule
- [x] Publish and promote in #vfs-analytics channel, #vfs-all-teams and ToTs

## Acceptance Criteria
- [x] Lightning Talk Series has been published.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Questions by topic card to help prioritize.
[https://va-gov.domo.com/page/514439234/kpis/details/1758142802]

**Comment by michelle-dooley** [comment]
Created EasyRetro board for brainstorming topics.
https://easyretro.io/board/221fae79-c237-4ed7-acd9-23af2adc2543/999bacd3-169e-407c-9df4-042f4bc68868Easy
