### ISSUE TITLE
Add product association to lighthouse data ingestion mechanism

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#36305]
## Issue Description
As our lighthouse data has a url for each page tested, we should be able to align some, or all of this data to products and where they exist. The manifest files currently have a front end url as a part of them. This could be matched to the url scanned by lighthouse to then associate it to a product ID through the app list.

---
## Tasks
- [ ] Add front end urls from the manifests to the app list generated in the `vets-website` GHA CI workflow
- [ ] Add logic to the lighthouse ingestion mechanism to pull front end urls from the application list, match them to the lighthouse urls, and add the corresponding product IDs from the application list to the lighthouse table in BigQuery.
- [ ] Add a field in BigQuery's lighthouse data storage for the product ID.

## Acceptance Criteria
- [x] Lighthouse data should be labeled with a product ID in BigQuery
- [x] Lighthouse data should be able to be silo'd off by product in Domo.

**Comment by CBonade** [comment]
I've altered the ingestion mechanism for this to account for a manifest property of our choosing to be attached to the results data. Once IDs are added to the manifest this will be a quick conversion. PR is awaiting review currently.

**Comment by CBonade** [comment]
Completed these changes and my test branch run resulted in product IDs appearing in BigQuery. It's submitted for PR review currently here: https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/106

**Comment by pjhill** [comment]
Hooray for Lighthouse data -- I think teams are going to like this metric.
