### ISSUE TITLE
[SW-Content] - Intake - Combined VBA + VHA debt portal from The Debt Resolution Team

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#36306]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [X] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [X] IA support
  
Based on our meeting with Jill from a couple weeks ago, our team is moving towards combining the VBA Debt Portal and Medical Copay Tool into one VA Debt Portal. We've previously discussed IA constraints that prevented us from releasing a combined portal as part of the MVP, so I'd like to brainstorm how we can combine these tools. 
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: 
- Link to or attach user flows: [Early ideation for the combined portal](https://preview.uxpin.com/9e0ac1c9c2556db7bc3ba7dd9ad5605ef2a00b7e?_gl=1*1sp3x2k*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/147208059/simulate/sitemap?mode=i), [Our previously discussed designs](https://miro.com/app/board/o9J_lFg6K9s=/?moveToWidget=3074457359122655402&cot=14) 
- Link to prototype or mockups: Mockups can be found in the early ideation UXPin
- Link to any epics/issues that may be helpful: [Medical copayment IA/content strategy,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27780) [IA Request Debt Resolution Team, Medical Copayments Tool (MCP)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25663)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: March 2022
- Estimated staging review date: ~End of February 2022
- Content and IA work needed by: ASAP

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: The Debt Resolution Team
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @denisecoveyduc 
-	Designer: @rileyorr 
-	FE engineer: @craigwheeler 
-	Product/team Slack channel: #vsa-debt

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by SgardnerPMP** [comment]
Per discussion on 2/11/22, turning this into Epic for Sitewide Content, with first initial issue "Phase 1 Understanding Design teams approach to accomplish goals, road map, and level of effort for IA and Content team to support completion"   - Estimated Product completion, End of March 2022.
