### ISSUE TITLE
Update the `startReactApp` function to not make assumptions about DOM Injection

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#36314]
## Issue Description
Created via the post mortem in regards to a recent sign in page bug where a site wide widget was overriding the `LoginContainer`. This led to the page's final paint, not rendering the `LoginContainer`, but instead the `MobileMenuButton`.

Why it happened:
- When `startReactApp` is called for the `MobileMenuButton` it is instructed to inject this widget into the `div#va-nav-controls` element.
- On staging+ environments, that elements does not exist due to a flipper feature that removes it
- When `startReactApp` determines that that element is `undefined` it defaults to placing the widget in the `div#react-root`

I don't think it is safe behavior to make default assumptions when injecting widgets. If the widgets is given a specific element to inject into, we should only render that widget if the required parent element exists.

This will require precise investigation to ensure we do not break anything that relies on default injection to `div#react-root`

---
## Tasks
- [x] Update the `startReactApp` function to allow a widget to be discarded if it's parent element does not exist on a page
- [x] Create Unit tests to ensure this functionality works as expected 

## Acceptance Criteria
- [x] `startReactApp` function does not unintentionally inject elements into `div#react-root`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
