### ISSUE TITLE
[BE] URL Shortener - Metrics and Reporting 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36323]
## Description 
Based on a discussion around the URL Shortener work, it was determined monitoring/alerting would be needed. This ticket is to add monitoring around the below metrics for the URL Shortener. 

## Tasks 
Create reporting metrics for the following:
- [ ] api request volume
- [ ] latency/time to complete api requests
- [ ] error reporting
- [ ] 404s for end users
- [ ] number of active short urls
- [ ] number of short urls expired

## Acceptance Criteria 
- [ ] The above metrics are being captured and viewable on dashboard for reporting

**Comment by loripusey** [comment]
@acrollet Do we still need this ticket?
cc: @sarahknoppA6

**Comment by acrollet** [comment]
@loripusey We can obtain this information from logs as needed so I think it's a product/prioritization question. The error & 404 reporting would be the most important in my opinion to help identify problems, especially after #37983 is complete.
