### ISSUE TITLE
[Design] My VA: Review various alerts and errors on My VA for consistency

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36340]
## Background
During a discussion on error states for the new Benefit payments and debts section, it was mentioned that the current alert/error message style being used was not the same as the latest style that should be used.  
We need to review what styles and patterns are being used, and ensure they are the most up-to-date and consistent throughout My VA.

## Tasks

- [ ] PM to gather screenshots of error messages and alerts from My VA staging environment
- [ ] Compare screenshots against the latest style and patterns 
- [ ] Update design documents to include all error messages and alerts on My VA in the most up-to-date style
- [ ] Ensure that the error messages and alerts on My VA are consistent, showing the same pattern throughout the page

## Acceptance Criteria
- Designs are updated with the latest, up-to-date style and pattern for error messages and alerts on My VA

**Comment by hdjustice** [comment]
[**GH Document** ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/error-messaging/My%20VA%20Error%20Messages%20images%202-2022.md)created to include screenshots of all current error messages that appear on VA.gov/my-va page.

**Comment by aagosto90** [comment]
I updated the design so I wouldn't block this ticket but I do have a couple observations/questions. [Here's a link to the Sketch file with the updated Cerner alert.](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/KLE1Ve/a/nRE5MA4/)

The Sketch file wasn't up to date with staging and had something that looks more like this:
![Screen Shot 2022-03-22 at 5 49 09 PM](https://user-images.githubusercontent.com/97965610/159582034-a89eb3c6-72b4-4d0c-ade9-205208da6a3e.png)
which I think is great and has very clear call to action buttons but I'm just wondering where and why along the line we ended up with a more plain text and text links Cerner alert so I can update the Sketch file to match staging. I don't see a component that looks like this screenshot in the VA pattern library so I'm thinking maybe it didn't get approved and we had to stick with something more plain...but just a theory on why there's a discrepancy here. Does anyone have any insight into this? 

@Samara-Strauss @andaleliz @hdjustice @tmitchellgcio

**Comment by hdjustice** [comment]
Hi @aagosto90 - I found an old ticket for the Cerner alert where the current design was decided.  In case you wanted some background - [Ticket #28575](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28575)

**Comment by aagosto90** [comment]
Guidance from Natalie Hill: 

> I recommend the Warning alert -- either the standard full-width style or the background only style -- for the scenario you are describing. We can also talk about making it dismissible if you'd like that option.

According to this guidance, we would need to update the alerts for the following scenarios:

- Unable to load claims or appeals with no known resolution time
- Unable to load claims or appeals with known resolution time (i.e. planned downtime)
- Unable to access health care information
- Unable to connect to appointments endpoint
- Unable to load Payment information (cannot determine if user has payment history) - May be updated once the product has launched

**Comment by aagosto90** [comment]
@Samara-Strauss 

- Absolutely agree on your first point and the fact that we're using that type of alert for notifications has literally been keeping me up at night. This is something I'd love to address in our roadmap in the near future if you agree because I think we all viewed changing the notifications to that style as a band-aid and not the ultimate solution. Now we're seeing yet another reason why we probably shouldn't use the warning style alerts for notifications. Maybe we should address this before working on updating these alerts.
- Also agreed that they don't need to be dismissible; I let Natalie know that wasn't necessary.

**Comment by Samara-Strauss** [comment]
> Now we're seeing yet another reason why we probably shouldn't use the warning style alerts for notifications. Maybe we should address this before working on updating these alerts.

Agree. Can you work with @hdjustice to get this into the backlog?

> Also agreed that they don't need to be dismissible; I let Natalie know that wasn't necessary.

Great! Thank you for confirming.

**Comment by hdjustice** [comment]
Ticket #39090 created with these feedback items.  @aagosto90 Feel free to edit/add/remove info from the ticket, or let me know what you need there.  Thanks!
