### ISSUE TITLE
Support Q&A Repository

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36341]
## Issue Description

We have multiple resources who manage support weekly and other team members that backfill when those team members are out.  Would be helpful to have a repository of the most frequently asked questions and answers so the member on support can easily reference if they are unclear and to assure we are consistent in our responses.  This should speed the response time and reduce the support time for the responsible team members.  It also allows for easier onboarding when new members join the team and can also help feed our training and orientation decks.

---
## Tasks
- [x] Identify the most commonly asked questions and answers
- [x] Create google sheet with questions categories and specific questions and answers
- [x] Research ability to create chatbot response to the most basic responses (i.e. KPI requests would auto generate a link to the platform website request process)

## Acceptance Criteria
- [ ] The repository is created and the above tasks have been completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laurensimpson14** [comment]
@jennaouellet and I are working off [this Google Sheet](https://docs.google.com/spreadsheets/d/1ZUX-lZIskGsHzYBfNEe7Giy7nK2wNrWvGNf4Gjml56g/edit?usp=sharing)

**Comment by jennaouellet** [comment]
Created [confluence page](https://vfs.atlassian.net/wiki/spaces/AT/pages/2098495548/WIP+-+FAQ) to begin loading the new questions along with the existing ones.

**Comment by jennaouellet** [comment]
Next steps are to get feedback on the new questions in confluence, publish to platform website, then research the potential chatbot responses

**Comment by jennaouellet** [comment]
Changes to the FAQ doc have been published and a knowledge base of common Slack support replies has been compiled
