### ISSUE TITLE
[UX] - Pre-check-in User Guide

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#36342]
## Description
** Blocked by 35879**
As a staff member or contact center rep, I want to understand the possible outcomes a veteran could encounter during pre-check-in.

Notes
We need a comprehensive user guide that can be shared with clinics in order to help them understand and troubleshoot pre-check-in activities.  This should outline the different possible workflows in pre-check-in and include screenshots for each step. 

Link to [pre-check-in prototype here](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/PGzGPJr/play)

# Tasks
- [ ] Obtain screenshots of the application
- [ ] Should include happy path as well as known edge cases

# Acceptance Criteria
- [ ] Completed new version of guide to give to staff members/contact center. Content includes happy path, edge cases, and troubleshooting tips with screenshots.
- [ ] Obtain Stephen's sign-off and confirm it does not need any other approvals before distribution.

**Comment by kristenmcconnell** [comment]
When I created the original MVP guide, I was told the call center needs a Word document.

**Comment by kristenmcconnell** [comment]
[Current draft of day of check-in, which can be used as a guide](https://app.zenhub.com/files/133843125/2fc1dc53-33b2-42af-b10a-71e771b41045/download)

**Comment by niradatta1** [comment]
First draft is complete here.  @zach-park to add the user flow diagram, and will update here. https://docs.google.com/document/d/1FnRnbI2CbdsbtPvGmc2kmGzHz2GuySO5/edit#heading=h.r87qh0iihfrg

**Comment by zach-park** [comment]
@niradatta1 the user flow diagram is inserted. I've also attached the diagram below: 
![Pre-check-in user flow (Read-only) for user guide](https://user-images.githubusercontent.com/91493630/155206287-759eb342-d521-4d41-98ea-d25e54701a24.png)
