### ISSUE TITLE
[UX] Design Page/Content for Veteran Revisiting Expired Shortened Link 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36346]
## Description 
Based on a discussion around the URL Shortener work, it was determined a page and content would be needed for when a Veteran visits a shortened link that is not found (would usually be if the veteran visited an old check-in link that had expired, but could be a mis-typed url, mistake in the url that was sent, etc.)

## Tasks
- [ ] Design has been determined
- [ ] Content determined
- [ ] Reviewed with appropriate team members, such as Product, etc. 

## Acceptance Criteria 
- [ ] Wireframe has been produced containing approved design/content and ready to be handed off to FE.

**Comment by jparker0425** [comment]
Closing because it is a duplicate of 34960.
