### ISSUE TITLE
[Design] Auth Profile: Review updated checkbox group/text field approach with Design Council

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36359]
## Background

Describe the issue background and scope

## Tasks
- [x] Attend Design office hours to review updated approach with "other" option removed and text field separated
- [x] Invite Martha Wilkes to attend if possible to review for usability

## Acceptance Criteria
- [x] Approach has been reviewed by Design Council and Platform usability expert
- [ ] Feedback and any additional tasks resulting from the review have been documented

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
- Associate with an Epic if applicable

**Comment by cgednalske** [comment]
Documenting the new solution for text input field that was approved at office hours. [Sketch files](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ygWOEPy)
<img width="446" alt="Checkbox removed_no conditional reveal" src="https://user-images.githubusercontent.com/79372956/153294967-44d9465c-899a-4322-b28f-48ef2c394ea9.png">
