### ISSUE TITLE
[FE] Auth Profile: Personal Information Revision: Remove "other" option from Pronouns, Sexual Orientation separate text field

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36354]
## Background

Christina, Adam and Marci met with Josh Kim, Angela Fowler, Kevin Hoffman and Rob Garrison on 2/2/2022 to discuss ongoing concerns about the behavior of the text box in conjunction with a list of checkboxes.  In that meeting, it was proposed by Josh to have the text field below the list of checkboxes with its own label, and remove the "other" option from the list.    Furthermore, the field would behave in the following manner:

- The text input field would always be visible and editable. 
- An "required" error message will be displayed if the user attempts to save their edit without selecting one of the provided options OR entering their own value into the text field
- This approach would apply to Pronouns and Sexual Orientation fields.

## Tasks
- [x] Update Staging to remove "Pronouns not listed here" option from the Pronouns section
- [x] Update Staging to remove "A sexual orientation not listed here" from the Sexual Orientation section

## Acceptance Criteria
- [x] Front End reflects new approach for providing an option not already listed.
- [x] Tag PM in a comment to this ticket when ready to review on Staging

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO this ticket is ready to review in staging. The 'other' checkboxes have been removed.

One thing that I will still need to update is removing the colored border style input box that is on the pronouns field and restoring it to a plain input box like the sexual orientation.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @adamwhitlock1!  This looks great!  cc @Samara-Strauss @cgednalske @tpharrison
