### ISSUE TITLE
[BE] Auth Profile: Work with Lihan on monitoring for Ch33

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36364]
## Background
Alerts were created during the latency problems in Dec 2021, and those notifications appeared in a troubleshooting channel in Slack.  Now that the issue has subsided, we need someone in our area to monitor and determine if they should be diverted elsewhere.  See related Slack thread: https://dsva.slack.com/archives/C02Q9FL124F/p1643238564218749

## Tasks
- [ ] Determine what alerts need to be diverted to our alert channel (#authd-exp-alerts)
- [ ] Advise Kevin Musiorski of those changes

## Acceptance Criteria
- [ ] Determination has been made on which alerts need to be diverted from #bgs-direct-deposit-info-debugging to #authd-exp-alerts
- [ ] Kevin Musiorski has been updated so that he can make that change.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
- Associate with an Epic if applicable

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison - I talked to Heather, and she said that Lihan has time to work on this during this sprint.

**Comment by tpharrison** [comment]
Thanks @MarciMcGuireGCIO!  I'll reach out to him.

**Comment by lihanli** [comment]
we already have latency alerts in grafana for the direct deposit apis so i don't think the datadog alerts need to be moved over since they would be redundant

**Comment by tpharrison** [comment]
@lihanli - I'll look through what's already in place and reach out to you if I have any questions.

**Comment by tpharrison** [comment]
@lihanli create these alerts in Grafana - http://grafana.vfs.va.gov/d/lmh-7kA7k/va-gov-profile-apis.

Kevin Musiorski will remove the alert from Datadog.
