### ISSUE TITLE
[Design] Auth Profile: Personal Info Revision: Mock up hint text with placeholder copy

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36361]
## Background

During user testing, it was determined that users are more apt to see "why we ask for this information" if it is provided in close proximity to the question it pertains to.   This issues is to mock up what that might look like using placeholder text so that Danielle has an opportunity to see it in context before providing content recommendations.

## Tasks
- [x] Update Personal Information mockups to show hint text next to each of the personal information questions
- [x] Review with Danielle so that she has context for the related content request.

## Acceptance Criteria
- [x] Personal Information mockups have been updated to show hint text next to each of the personal information questions
- [x] Mockups have been reviewed with Danielle so that she has context for the related content request.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
- Associate with an Epic if applicable

**Comment by MarciMcGuireGCIO** [comment]
Christina has reviewed with Danielle.

**Comment by cgednalske** [comment]
Reopening because this got mixed up with the address modal ticket. I am still working on these hint text placeholders.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske are you still working on the hint text placeholders?  It looked like they were all there, but maybe that was just Desktop?  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO nope! Everything's done with the hint text placeholders for both mobile and desktop.

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske whoo hoo!  Thank you! 🥳
