### ISSUE TITLE
[Research] Finalize Research Plan and Conversation Guide - HRT Static Content Landing Page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36366]
## High Level User Story/ies
As a Veteran or VA employee, I need a way to report an incident of workplace harassment or assault which takes place at a VA facility so I can be assured that there is investigation and remediation.

[Product Outline for Reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/read-me.md)

##  Tasks 
- [x] Revise per Dave's review with stakeholders
- [x] Work with Danielle Thierry to reach out to the Office of Mental Health and Suicide Prevention to check the VCL wording in the HRT conversation guide
- [x] Work with Brian Lloyd to reach out to someone at VCL to check the VCL wording in the HRT conversation guide
- [x] Reach out to volunteer social workers about observing sessions
- [x] Launch recruiting with Shane via new process in research repo
- [x] Work with PM to build research tickets to account for work and support

## Acceptable Criteria 
- [ ] Research plan and Conversation guide are prepared for recruiting efforts 
- [ ] Finalize research/conversation by defined timeline 
- [ ] Final research plan and conversation guide available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
On Slack, pinged [@Danielle Thierry](https://dsva.slack.com/team/U01135ZL4KY) to reach out to the Office of Mental Health and Suicide Prevention and [@Brian Lloyd](https://dsva.slack.com/team/U01AHH156QY) to reach out to someone at VCL to check the VCL wording in the [HRT conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/conversation-guide.md).

**Comment by cindymerrill** [comment]
@brianalloyd I'm assuming that no changes need to be made to the research plan or conversation guide per Dave's meetings with the stakeholders, so I'll check off that task in this ticket.

**Comment by cindymerrill** [comment]
Danielle reached out to the VCL today, and she'll let me know if that results in any changes to the landing page or conversation guide.

**Comment by brianalloyd** [comment]
@cindymerrill is this ready to be closed?

**Comment by cindymerrill** [comment]
Yes!
