### ISSUE TITLE
Letters: Fix a11y issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36370]
## Description

While fixing linting issues, a bunch of a11y issues popped up, including:

- Header order problems
- Table header without tbody displayed
- Inappropriate use of `autocomplete` on checkbox

This is because the axe check isn't set up to expand the HTML (non-component) accordions.

## Tasks

- [ ] Fix page headings
- [ ] Hide tables with no content
- [ ] Remove `autocomplete` settings on checkbox input
- [ ] Replace accordion HTML with web component
- [ ] Check that accordions expand in e2e tests & axe checks are run

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
