### ISSUE TITLE
Align unit test coverage data to products

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#36378]
## Issue Description
The unit test coverage data currently does not contain a file path that can be used to align our test data to products. We can, however, use the `entryName` from the manifests, which is what is currently being used to label the unit test coverage report. This `entryName` should be added to the app list that is generated in vets-website CI, and then attached to our unit test coverage results before sending them to BigQuery.

---
## Tasks
- [x] Add the manifest `entryName` to the `vets-website` app list that is generated in the GHA CI workflow.
- [x] Use the new app list to associate an product name/id with the coverage report lines in the ingestion mechanism. This will require writing a new helper function as the current one is based solely on URL matching.
- [x] Add a new column to the BigQuery schema for unit test coverage storage to hold the product name/id.

## Acceptance Criteria
- [x] BigQuery's unit test coverage data has a link to our product list stored in it.
- [x] The vets-website application list has a linking field for the unit test coverage report
---

**Comment by CBonade** [comment]
I've altered the ingestion mechanism for this to account for a manifest property of our choosing to be attached to the results data. Once IDs are added to the manifest this will be a quick conversion.

**Comment by CBonade** [comment]
Completed these changes and my test branch run resulted in product IDs appearing in BigQuery. It's submitted for PR review currently here: https://github.com/department-of-veterans-affairs/vets-website/pull/20132

**Comment by pjhill** [comment]
Hooray for getting the `productId` link in there.
