### ISSUE TITLE
Add balance to comp & pen debt for user 228

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#36388]
## Issue Description
To test a use case we need a user to have current comp & pen debt
---
## Tasks
- [ ] Update current balance for this debt to have some remaining

## Acceptance Criteria
- [ ] When user 228 logs in they can see an outstanding balance for comp and pen
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
