### ISSUE TITLE
Claim Status Tool Technical Discovery

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36383]
## Issue Description
In order to document and prioritize backend development work for the Claim Status Tool, we need to understand what the existing technical issues are. 

---
## Tasks
- [x] Work with Christian to review research findings
- [x] Ask Amanda about list of CST support issues she's worked
- [x] Review Sentry / Grafana / Loki / Datadog analytics (engage engineering peers for assistance as needed. Meeting with Dillo being scheduled also.)
- [x] Document known errors in Github tickets 

## Acceptance Criteria
- [x] Documented list of errors and tickets that we will begin working on for CST
---

**Comment by alsleaders** [comment]
I've worked on one [CST support ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34384) along with @michelpmcdonald and he added a comment to it explaining what we learned about the CST error messages while we were researching.

**Comment by cnemeth** [comment]
# Claim Status Tool Technical Discovery

## Review Research Findings by Christian Valla

* [Repo containing CST Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research)
* Files from [Slack](https://dsva.slack.com/archives/G016CG5FT6Z/p1644944943169249)
  - `claims-list-claims-unavailable-error.png`
  - `claims-list-no-claims-no-appeals.png`
  - `claims-list-no-claims.png`
  - `claim status feedback errors.docx`
  - `error.codes.and.explanations.pdf`
  - `file for disability compensation more information needed fill in or mismatch evss.PNG`
  - `intent to file error message.png`
  - `longer than expected to submit claim.jpg`
  - `Screenshot (4).png`

## Support Issues

* Develop template for use by Contact Center for reporting issues. (Ref.: [Ticket #35643](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35643))
* [[Tier 3] Claim submission issue - SF 06228145 #34002](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34002)
* [[Tier 3] Claim Status not showing - SF 06259690 #34051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34051)
* [[Tier 3] Claim Status Issue - SF 06191619 #34384](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34384)

## Errors form Logs (Sentry/Grafana/Loki/Datadog)

### Grafana/Loki(Prod) - last 7 day

* HTTP status code 400 - Bad Request (3)
```
# example from logs
2022-02-16 11:27:34	
2601:4a:8102:6420:4eb:410f:82a6:32c2 - - [16/Feb/2022:19:27:34 +0000] "POST /js-report/api/0/envelope/?sentry_key=faker&sentry_version=7 HTTP/1.1" 400 5 "https://www.va.gov/?next=%2Ftrack-claims%2F&postLogin=true" www.va.gov - "Mozilla/5.0 (iPhone; CPU iPhone OS 15_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1" "2601:4a:8102:6420:4eb:410f:82a6:32c2, 10.238.28.71"
```
* HTTP status code 401 - Unauthorized (2)
```
# example from logs
2022-02-16 11:27:26	
2601:4a:8102:6420:4eb:410f:82a6:32c2 - - [16/Feb/2022:19:27:26 +0000] "GET /v0/user HTTP/1.1" 401 93 "https://www.va.gov/track-claims/your-claims" api.va.gov - "Mozilla/5.0 (iPhone; CPU iPhone OS 15_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Safari/604.1" "2601:4a:8102:6420:4eb:410f:82a6:32c2, 10.239.28.71"
```
* HTTP status code 499 - Client Closed Request (14)
```
# example from logs
2022-02-16 11:27:37	
2600:1700:5ac0:65f0:3541:3692:2a23:1ab5 - - [16/Feb/2022:19:27:37 +0000] "GET /v0/feature_toggles?&cookie_id=zuancqngb4bnpm50hyr2q HTTP/1.1" 499 0 "https://www.va.gov/track-claims/your-claims" api.va.gov - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36" "2600:1700:5ac0:65f0:3541:3692:2a23:1ab5, 10.236.28.71"
```

## Know Issues and Errors Documented in Github Tickets

* Fix outdated decision-review language (Ref.: [Ticket #16199](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16199))
* Revert changes, updated response actions increase the polling time for vets-website (Ref.: [Ticket #3009](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3009))
* SMs still can’t see their claim in the claims status tool on VA.gov when the EP is 336 – Pre-Discharge Excluded (BDD shows up, not 336). Therefore, they can’t upload any documents to their claim (i.e. STRs) after they submit the claim. (Ref.: [Ticket #36931](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36931))
* Failing document uploads (Ref.: [Ticket #1339](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1339))
* Error uploading supporting documentation/evidence for claims. (Ref.: [Ticket #34034](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34034))
* In the Claim Status Tool listing, the lightly colored dots are not in alignment with accessibility standards. (Ref.: [Ticket #36832](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36832))
* Fix incorrect labels. (Ref. [Ticket #29078](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29078))
* Improve status reporting (EVSS). (Ref.: [Ticket #36393](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36393)) 
* Update list of Staging users for Caseflow/Appeals users in staging. (Ref.: [Ticket #13406](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13406))
* Fix active users are being logged out after viewing eBenefits. (Ref.: [Ticket #21207](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21207))

## New Feature and Updates

* Veteran would like to receive text messages when claim status is updated. (Ref.: [Ticket #36433](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36433))
* Timely updates of claim status. (Ref.: [Ticket #35642](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35642))
* Update <Telephone> React component to the new <va-telephone> web component in the Claims Status Tool. (Ref.: [Ticket #36944](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36944))
* [FE] Claim Status Tool React App Build (Sitewide Team), (Ref.: [Ticket #35382](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35382))
* Improved error/warning messaging for CST appeals, (Ref.: [Ticket #30030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30030))

## Testing

* Claim Status Tool User Acceptance Testing, (Ref.: [Ticket #28850](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28850))
* Claim Status Tool Usability Testing, (Ref.: [Ticket #28841](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28841), [Ticket #28849](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28849))

**Comment by cnemeth** [comment]
## Current list of Github tickets active in the system related to `CST`

### Icebox

1. [Review decision review copy in claim status tool #16199](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16199)
1. [Claims Status Tool #27127](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27127)
1. [Full redesign - Claim Status Tool #29077](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29077)
1. [Claim Status Tool - Business Process Documentation #30229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30229)
1. [[Tier 3] Claim submission issue - SF 06228145 #34002](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34002)
1. [[Tier 3] Claim Status not showing - SF 06259690 #34051](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34051)

### Epics

1. [Claim Status Tool v2 #28836](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28836)
1. [[Collab Cycle] Claim and Appeal Status Tool #8340](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8340)
1. [[Epic] Claim Status Tool: Discovery and Implementation of Claim Status API #3735](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3735) # => High level user story and tracking CST porgress (openned by Yana Roy)
1. [[Development] Claims Status: Discovery for Engineering Deep Dive #7775](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7775)
1. [[Design/Discovery] Claims Status: Review Appeals Flow Provided by Fred Somers #11817](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11817)
1. [Make small enhancements to Claims Status Tool (from mobile month) #14486](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14486)
1. [Understand Claims Status Tool Upload Issues #20466](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20466)
1. [[Metrics] Claims Status: Get Metrics for Average Number of Claims, Type of Claims for CST #12256](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12256)
1. [[Development] Claims Status: Investigate Possible Values and "Algorithm" for Claims Status Timing Message #10014](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10014)
1. [Claims Status Tool - API Discovery #20467](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20467)
1. [Claim Status Tool - Evaluate all Functionality #20469](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20469)
1. [[Development] Claims Status: Do We Still Have Upload Issues #11865](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11865)

### Backlog

1. [BDD - EP 336 Pre-Discharge Excluded Claims not showing in Claim Status Tool #36931](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36931)
1. [Claim Status Tool Accessibility Issue #36832](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36832)
1. [Investigate technical and process feasibility of Claim Status Tool text notifications #36433](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36433)
1. [Claim Status Tool - Contact Center Communication #35643](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35643)
1. [How much detail can we provide about claim status in the Claim Status Tool #35642](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35642)
1. [Communicate Claim Status Tool Functionality #34038](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34038)
1. [Claim Status - Details #34037](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34037)
1. [Claim Status Tool - Upload Issue #34034](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34034)
1. [Claim Status Tool Label update #29078](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29078)
1. [Reexamine eBenefits links in Claim Status Tool. #21207](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21207)
1. [Claim Status Tool User Acceptance Testing #28849](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28849)
1. [Claim Status Tool Usability Testing #28841](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28841)
1. [Claim Status Tool User Acceptance Testing #28850](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28850)
1. [Claims Status Tool - Initial Research #26720](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26720)
1. [Update list of Staging users for Caseflow/Appeals users in staging #13406](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13406)
1. [Claims Status Tool Discovery #17044](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17044)
1. [Research possible Claim Status Tool codes #36393](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36393)

### Ready

1. [CST: Update to telephone web component #36944](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36944)
1. [[Tier 3] Claim Status Issue - SF 06191619 #34384](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34384)
1. [[FE] Claim Status Tool React App Build (Sitewide Team) #35382](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35382)
1. [Improved error/warning messaging for CST appeals #30030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30030)
1. [security - DocumentUpload arguments #30414](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30414)
1. [Claim Status Tool Technical Discovery #36383](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36383) # => this ticket
1. [[Tier 3] Disability Claim Issue with Application ID number (3611501) #29941](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29941)
1. [[Tier 3] Disability Claim Application Issue with Application ID number (3489590) #29182](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29182)
1. [[Tier 3] Disability Claim Issue with Application ID number (3537038) #29944](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29944)
1. [[Tier 3] Disability Claim Application Issue with Application ID number 3550591 #29935](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29935)

### Current Sprint

1. [Claim Status Tool Technical Discovery #36383](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36383) # => this ticket
1. [CST Frontend Assessment - Follow-up on template implementation #36569](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36569)

### In Progress

1. [Update claims time (Content update request) #8501](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8501) # => this ticket from `2/1/2018` is still `in progres`, has an attached _PR_ [Error when fetching scheduling configurations, PR #7204, closed](https://github.com/department-of-veterans-affairs/vets-api/pull/7204)

### Validate

1. [Change IRIS and GI Bill Help Portal content and links to Ask VA in claim status tool #31723](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31723)
1. [CST: Use Ask VA links #19221](https://github.com/department-of-veterans-affairs/vets-website/pull/19221) # => closed, linked to [ticket #31723](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31723)
