### ISSUE TITLE
[DISCOVERY] Research how to trigger events from VBS with SQS and SNS

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#36390]
## Issue Description
We need to use SNS and SQS to be able to tell when a new medical copay statement is made available. Since this is available from a downstream service (VBS), we'll need to have a line of communication to be notified of this event. 

---
## Tasks
- [ ] Research how we can use SQS and SNS to connect with VBS to be notified of this new statement.

## Acceptance Criteria
- [ ] We have documentation in place for how we can use these services to connect with VBS for event triggering
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
Discussed in backlog grooming that we're no longer going the SQS and SNS route, so this ticket is no longer applicable
