### ISSUE TITLE
[UX] Pre-check-in when veteran has already completed PCI but clicks link again

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#36414]
https://dsva.slack.com/archives/C02G6AB3ZRS/p1643895198813739

## Description
Currently when a veteran clicks the pre-check -in link again (and it is still valid AND pci is already completed) they are prompted to go through the entire pci workflow again where they receive an error message at the end.  
Desired behavior would be to show the veteran that they have already completed pre check in early in the workflow (immediately after clicking the link). 

## Tasks 
- [ ] Understand the use case and scenario
- [ ] Talk to engineering about the feasibility of this.
- [ ] Work with content on wording for error state.
- [ ] Create wireframe of the final flow/design.

## Acceptance Criteria
- [ ] Add final design/flow to the error message source of truth, user flow, Zach's edge case doc.
- [ ] Make sure that a FE ticket is written to implement this.

**Comment by stephenBarrs** [comment]
There was a question from Shawn Adams on if we might show the Veteran that they have completed pre check in, but also provide a way for them to update their answers if they want to.  Thoughts on that?

**Comment by kristenmcconnell** [comment]
@loripusey See Stephen's comment above for future roadmap item.
