### ISSUE TITLE
TUD - NGINX redirect

### ISSUE THREAD

**Issue by rbeckwith-oddball** [department-of-veterans-affairs/va.gov-team#36417]
## Issue Description
Update the set up of TUD to properly utilize NGINX

---
## Tasks
- [x] Revert the changes that were made to dev that caused all the web requests to 404 (`vsp-infra-application-manifests/apps/vsp-identity/test-user-dashboard/dev`)
- [ ] Update `vsp-test-user-dashboard/nginx/tud.conf` to properly redirect 

## Acceptance Criteria
- [ ] The test user dashboard will no longer erroneously redirect the browser to external port 9000 (which is not exposed publicly)

**Comment by rbeckwith-oddball** [comment]
1. First step will be to revert the changes that were made to `traefik` on dev. This will put it back to the same state that `utility` / `staging` is in
2. After several different methods were attempted with `traefik`, we've narrowed down the culprit to `nginx`
  a. Having `traefik` with an SSL and redirection caused 404 for all resources
  b. This was occurring because `nginx` had been removed from the equation
3. We believe that the issue exists in the configuration file found in `vsp-test-user-dashboard/nginx/tud.conf`
  a. Specifically targeting:
    * try_files (different settings and locations within the conf file)
    * proxy pass through `nginx` to port 9000 instead of externally

Since the new method only deals with `test-user-dashboard` and no longer needs `traefik`, there *shouldn't* be any reason that our tests would have any impact on the rest of the services.

**Comment by rbeckwith-oddball** [comment]
First, I reverted the `dev` environment back to it's state prior to testing. I had tried a few different changes to the configuration settings of `nginx`.

While watching the logs for insight, I noticed:
```
{
    "time_local":"07/Feb/2022:20:39:54 +0000", "remote_addr":"192.168.87.76", "remote_user":"tudadmin", "request":"GET /page-data/app-data.json HTTP/1.1", "status": "200", "body_bytes_sent":"81", "request_time":"0.000", "http_referrer":"http://tud-dev.vfs.va.gov/?page=1", "http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
  }
{
    "time_local":"07/Feb/2022:20:39:54 +0000", "remote_addr":"192.168.129.142", "remote_user":"tudadmin", "request":"GET /page-data/index/page-data.json HTTP/1.1", "status": "200", "body_bytes_sent":"151", "request_time":"0.000", "http_referrer":"http://tud-dev.vfs.va.gov/?page=1", "http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
  }
```
The `http_referrer` and `page-data/app-data.json` indicated that the redirect was occurring within the front-end of the application.

* I then `grep`ed through all the files looking for anything matching `status:\s*30[12]`
* This lead me to `vsp-test-user-dashboard/public/page-data/`
  * This then lead me to the handlers for the pages
* All of that lead me to see that when the front-end redirected us, the code would insert a slash after whatever the page name was.
  * To avoid _that_ we had to modify our callback URL to use the exact syntax necessary to avoid the `gatsby` code from redirecting us further.

@holdenhinkle and myself were able to  create the PR and verify that the TUD redirect to port 9000 was no longer occurring.

### Remaining issues
1. Going to pages that don't exist, etc. will result in being redirected to port 9000 instead of being presented with an error page or something that would be more informative to the user.
2. tud-gateway.vfs.va.gov is using a self-signed certificate. If a user does not accept the self-signed certificate prior to using the dashboard, it will not function properly.
  a. Holden's PR to use vets-api instead of a call to tud-gateway should rectify the issue

**Comment by rbeckwith-oddball** [comment]
Now, anyone visiting the `login` page will be required to use SSL. Accepting the self-signed certificate isn't the greatest, but if we want a valid certificate, we'd likely need a different ticket (and possibly traefik modifications).
