### ISSUE TITLE
Implement GitHub OAuth for TUD

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#36423]
## Issue Description
Based on requests from stakeholders, implementing GitHub OAuth is a feature that will improve the overall user experience and is being prioritized. 

_**DEVELOPMENT NOTE** - This decision was made in Q4 2021 and has continued into Q1 2022. The situation has become complicated, so we are creating this epic to group tickets related to this effort_

---
## Tasks
- [ ] Implement GitHub OAuth with TUD
- [ ] Complete a WASA scan

## Acceptance Criteria
- [ ] TUD Functions correctly with GitHub OAuth in place
- [ ] Usage tracking is in place with GitHub OAuth
- [ ] Security scan has been completed with no issues
