### ISSUE TITLE
Investigate technical and process feasibility of Claim Status Tool text notifications

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36433]
## Issue Description
As a Veteran, I would like to receive text messages when my claim status is updated.

---
## Tasks
- [ ] Investigate possibility of adding text notifications when claim status is updated. Reference [this thread](https://www.reddit.com/r/VeteransBenefits/comments/sjm8wu/va_text_alerts_idea/). 

## Acceptance Criteria
- [ ] Documented decision
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
Va does supply a notification service itself, we currently utilize it to send out emails to vets when they file claims.  I'm not sure if VA notify supports text notifications, but I assume if we are going to send out claims status notifications, we would target both texts and\or emails.  There might be some kind of preference the vet already sets up indicating their preferred notification method, not sure why I think that...

So for the actual "sending" of claim status notification updates, once we have identified a notification needs to be sent to the vet, I think the VA Notify Service would be the first service to research for possible use.

However, the heavy lifting of detecting claim status changes and calling the VA notification status notification changes would fall entirely on our team to implement.  As far as I know, the VA does not offer push notifications to vets-api, so other than an endpoint to fetch all the claims for a given vet, I don't think there is anything pre-existing the VA systems in this area.

I would like to point out that Lighthouse kind of does something similar for HRL\NOD submissions.  They push those claims in via central mail(I'm not sure if that is the same thing as VA notify or not), but it's just a one way push, and there is a delay between when they push, and when the claim gets established.  The VA does not actively notify lighthouse when a claim that LH pushed gets established with the VA.  So they have a cron job 

At it's simplest, we would have to implement some kind of system that periodically polls all claims from VA systems of record, looks for status changes(since the last notification) and sends out the notifications.  Even if we limit it to open claims only(can closed claims have a status change?), I'm going to guess it could be a scale problem...dare I say million(s) of open claims ?  Vets-api itself does seem to have the concept of CRON jobs and job schedules, so there is support for that in place and I think there are some current CRON type of jobs(error reports, data cleanup) that use vets-api CRON...Sidekiq might also be in the CRON job mix.

In addition to the polling of claims, I think we would have to persist some kind of information, perhaps on a per claim level, that captures the last status update sent.  My initial guess is a new table in our current postgres database.  If we have the last date-time a notification went out, we would look for status changes after the last notification went out.  I *think* the claims we fetch have status changes by date, but we would need to understand this aspect further, that would be one of the first research items to undertake, the pure logic we could use to id claims that have had a status change and require a notification.

Infrastructure wise, we could leverage the existing Sidekiq work queue system to scale out this potentially large scale task.  Nice that Sidekiq is avail, that allows us to work more on the specific task logic work.
