### ISSUE TITLE
Collaboration Cycle Checklist for Auth Profile - Bad Address Indicator

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36436]
# Collab Cycle Checklist for Bad Address Indicator

## List project artifacts for requests

<details>

_Link applicable artifacts here so you can quickly copy/paste into requests as your project progresses.  Note that all artifacts may not be needed, depending on nature of the work_
- [x] Project epic #35244
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator) 
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] User flows
- [x] Research plan | [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [x] Conversation guide | **[template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)**
- [ ]  KPIs for the product | [How to set](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md)
- [x] Authenticated test-user logins, when applicable. **_Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository_**
- [ ] ~Product URL(s):  https://www.va.gov/profile/contact-information~
- [x] Use cases (need to be updated per research recommendations)
- [ ] Finalized design prototype or mockup (updates #45002 and [sketch file](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/p/B84818F9-2AB7-42E8-BFFD-0C0949B020A3/canvas) )
- [ ] Content brief
- [ ] Regression test plans
- [x] TestRail test cases/test plans
- [ ] Documentation: Technical diagrams (architecture diagram, sequence diagram)
- [ ] Documentation: Any new publicly-exposed endpoints
- [ ] Any new interactions with dependent VA backends
- [ ] Release plan (draft #44739)
- [ ] Product guide for contact center (draft #44330)
- [ ] Go/No Go 

</details>

## Pre-Launch touchpoints linked to VSP reference info + practice areas involved at each step

<details>

- [x] Collaboration Cycle Kickoff | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D) | [#issuenum]

- [ ] Design Intent  | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) | [request template](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31577) [#issuenum] | _Note: PM must invite own team members._
- [ ] Content [Sitewide Content and IA intake request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) [#issuenum]
    - IA | [Request template if needed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) | [#issuenum]
- [x] Research Plan Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) |  [#issuenum]
- [x] Analytics Request | [Overview](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html) | [Analytics playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
- [x] Midpoint Review | [Overview ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)| [Midpoint Review request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D) [#issuenum]
  - Accessibility | [How to test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md) |  [#issuenum]
 
- [ ] Staging Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) | [#42706]
  - Accessibility [Prep Info](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) | [WGAG 2.1 foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Slide-decks:-WCAG-2.1-new-success-criteria-and-testing.1777893393.html) [#issuenum]
  
  - QA | [Overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html)

- [ ] Privacy and Security Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) |  [#44712]

- [ ] Contact Center Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) [#44330]
     
</details>

## Post-Launch Tasks

<details>

- [ ]  Post @here announcement in your Slack channel after launch

- [ ] Full accessibility and 508 office audit if needed | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=noahgelman%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]

- [ ] Create tickets for documentation updates

</details>

## Other Resources

<details>

- [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md)

</details>
