### ISSUE TITLE
[SW-Content] Research and write content on Virtual Agent Landing Page [SWC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36442]
## Story 
As a Veteran I need precise information on the Virtual Agent Chatbot landing page, so I will know my next steps, what I can perform, and how to complete my request.

## Resources:
See #33905 for the initial intake request.
See #34990 for chatbot work.

## Tasks
- [ ] Review data from intake request and previous issues to set up content for landing page in support of the VA virtual chatbot.
- [ ] Compose content and design for chatbot landing page.
- [ ] Content is saved in Draft in Drupal or provided in MS word for crosscheck and review by ME and CE.

## Acceptance Criteria: 
- [ ] Content is reviewed/cross checked by SW Content Managing Editor
- [ ] Content is reviewed by Copy Editor
- [ ] Content is placed in Drupal page and saved in Draft

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
