### ISSUE TITLE
[SW-Content] Research and write content on Virtual Agent Landing Page [SWC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36443]
## Story 
As a Veteran I need precise information on the Virtual Agent Chatbot landing page, so I will know my next steps, what I can perform, and how to complete my request.

## Resources:
See #33905 for the initial intake request.
See #34990 for chatbot work.

## Tasks
- [x] Review data from intake request and previous issues to set up content for landing page in support of the VA virtual chatbot.
- [x] Compose content and design for chatbot landing page.
- [x] Content is saved in Draft in Drupal or provided in MS word for crosscheck and review by ME and CE.

## Acceptance Criteria: 
- [x] Content is reviewed/cross checked by SW Content Managing Editor
- [x] Content is reviewed by Copy Editor
- [ ] Content is placed in Drupal page and saved in Draft

**Comment by lunascoop** [comment]
@RLHecht I have made my content changes to the page and they're ready for your review. Let me know if you want to chat about it.
[Virtual agent copy.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8004725/Virtual.agent.copy.docx)

**Comment by RLHecht** [comment]
Since Patrick is out this week I made my edits first, but I should probably look again after Patrick makes any edits too. Here you go. Let me know if you have any questions. I do think they need the disclaimer for legal purposes but you can check with their team to be sure.
[Virtual.agent.copy.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8005816/Virtual.agent.copy.docx)

**Comment by psanders86** [comment]
Hello @RLHecht and @lunascoop -- I made some suggestions and comments. Let's circle up after you have a chance to review, please. Thanks![https://app.zenhub.com/files/133843125/e35d4ddb-dc39-452a-8e9d-24a2bcce97f7/download](https://app.zenhub.com/files/133843125/e35d4ddb-dc39-452a-8e9d-24a2bcce97f7/download)

**Comment by LucianaAlexanderMorais** [comment]
@ianpsant @psanders86 The draft is looking great!

To answer your question:

"Disclaimer Section (current alert box)

Comment: Is this first screen as the virtual agent entry point necessary now that this is no longer a study? "

No - we don't need additional information on the disclaimer. Everything above this comment is looking great. We also added the disclaimer directly into the bot. 

Thank you!!

**Comment by psanders86** [comment]
[https://app.zenhub.com/files/133843125/e718f4ff-554a-447e-b5e2-75de2f5b9d85/download](https://app.zenhub.com/files/133843125/e718f4ff-554a-447e-b5e2-75de2f5b9d85/download)

This final version is good to be reviewed and/or put into Drupal

**Comment by ianpsant** [comment]
Hi @psanders86 @RLHecht @lunascoop We've reviewed the final version doc and it looks good to us.  One note is that especially in the small window of the chatbot, we may need to make some edits for brevity so that it all fits in that real estate. We control the content on the chatbot page and the chatbot itself so we can make these edits ourselves. We can make those changes and then show them to you in staging, noting any edits we've made, if you want to guide this all the way to completion. Or if you're fine with any changes we make as long as it's in the spirit of the final version, we could close this ticket. Let us know how you'd like to proceed.

**Comment by bethpottsVADEPO** [comment]
@ianpsant Yes, please post in this ticket a link to staging when it's ready so we can make sure the text aligns with our VA.gov voice, style, and plain language standards. Thanks!

**Comment by RLHecht** [comment]
@ianpsant Here is the final text for the chatbot page. Please let us know if you have any questions. Thanks!

[https://app.zenhub.com/files/133843125/bc16d1f7-cd07-41ea-9ad5-6850aba60398/download](https://app.zenhub.com/files/133843125/bc16d1f7-cd07-41ea-9ad5-6850aba60398/download)

**Comment by ianpsant** [comment]
Thanks, we should be able to turn this around fairly quickly and we'd like
to schedule a desk check with everyone involved in order to review, gather
feedback, and get any of our questions answered.

**Comment by ianpsant** [comment]
FYI, the content / styling changes we talked about are on https://staging.va.gov/virtual-agent-study/ for review. Luciana's reached out to an OCTO legal contact about "Disclaimer".

**Comment by bethpottsVADEPO** [comment]
@RLHecht I don't need to review again. I think the work in this ticket is complete?
