### ISSUE TITLE
[GitHub] Investigate PAT usage

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#36451]
## Description
Investigate our usage of Personal Access Tokens (PATs) for bot users.

## Background/context 
See Epic
Part of this task will be determining how access should be split up/shared among bots. By team? By application? By action?

---
## Tasks
- [ ] Look in repo settings (that we have admin access to) for any bots (listed under "Secrets").
- [ ] Look in parameter store for bots starting with `VA_VSP_BOT` and `VA_VFS_BOT`

## Acceptance Criteria 
- [ ] Comment in issue with a full list of GitHub repos (that we have access to) and which repo is using which bot.

**Comment by oseasmoran73** [comment]
[VA_VSP_BOT_GITHUB_TOKEN](https://github.com/search?q=VA_VSP_BOT_GITHUB_TOKEN+user%3Adepartment-of-veterans-affairs&type=Code)

[VA_VFS_BOT_GITHUB_TOKEN](https://github.com/search?q=VA_VFS_BOT_GITHUB_TOKEN+user%3Adepartment-of-veterans-affairs&type=Code)

**Comment by oseasmoran73** [comment]
[Datadog API Quota](https://app.datadoghq.com/dashboard/c9c-2ki-yf4/github-api-quotas-for-bot-users?from_ts=1644854696017&to_ts=1644858296017&live=true)

**Comment by oseasmoran73** [comment]
Matt gave some insight as towards why the rate limits were being hit previously. There was a kubernetes dashboard previously that was using a lot of the rates. It was removed and the bug should have been resolved, but Infra team never got around to re-enable and test if rate issues was resolved.

**Comment by oseasmoran73** [comment]
va.gov repo uses `BOT_GITHUB_TOKEN` and stored in secret. There is no method for us to review logs or audit what it is used for (only found in a gha workflow file)

**Comment by rmtolmach** [comment]
The [Datadog API Quota](https://app.datadoghq.com/dashboard/c9c-2ki-yf4/github-api-quotas-for-bot-users?from_ts=1644854696017&to_ts=1644858296017&live=true) that Oseas linked above shows the _remaining_ quota. When I first saw it, I thought it we were pushing up on the 5k limit and it was making me nervous! In the last four months, neither the VA-VFS-BOT nor the VA-VSP-BOT have made > 1k requests in an hour.

**Comment by jhouse-solvd** [comment]
We've discussed as a team and may want to change our approach here. Moving to review.
