### ISSUE TITLE
SUPPORT - Overhaul and align "Support Overview" page with other Platform work PT 1 (Shiba M)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36458]
# User story

As a VFS team member, I need to clearly understand the updated process of soliciting help, so that I can 

(a) quickly solicit help
(b) reconcile this new support process with previous understanding of the Platform's offerings.  

Both these points allow me to more quickly build a higher-quality Veteran-facing product.

# Tasks

- [x] Review whole page for clarity, ease of understanding, determine what needs to be removed and/or reorganized
- [x] Review added section for clarity, ease of understanding
- [x] Consult with leadership and other teams
  - Design system team abt "master branch" naming
  - Michael Fleet and/or Mike Chelen about other changes
  - other?
- [x] Secure final approval from Michael Fleet + Mike Chelen

# Acceptance criteria

- Secure PO and SME approval for the page's edits
- When I read the Support Overview page, then I shouldn't find any contradictions between the policies outlined and my understanding of Platform's offerings.

# Reference info
- [Support overview](https://vfs.atlassian.net/wiki/spaces/SUP/pages/604012552/Support+overview) page

**Comment by amygoldman** [comment]
Update: Jill and I reviewed the [Support overview page](https://vfs.atlassian.net/wiki/spaces/SUP/pages/604012552/Support+overview) and left comments and questions for discussion

**Comment by lianilychee** [comment]
Next steps
- Amy send a slack message
  - #platform-team with Tim Wright, Zach Lewis, Andrea Hewitt
  - screenshot the comment
  - Say, along these lines “hey tim has this question.  can you all clarify"
- Amy tackle as much of the “things we can fix ourselves” as she can

Things we can fix ourselves:
- Header
- Moving the blue box
- improve ~10 sentences (plain language, less clunky)
- Make 1 section more plain language
- link to a thing
- broken link
- determine how to handle content of “is my issue critical”
- determine scope of document
- grab industry precedents of support overview pages (technical products, platforms)
- —
- quick fixes
- longer fixes

Things we need SMEs to quickly answer:
- support request overview
- how is escalation determined
- master branch
- binary rollbacks
- small glossary
- roles and responsibilities
- — 
- SME quick answer:
- SME longer convo:

**Comment by amygoldman** [comment]
Update: [message sent to Tim Wright, Zachary Lewis, and Andrea Hewitt](https://dsva.slack.com/archives/CJRQ85PQB/p1647448747541329)

**Comment by lianilychee** [comment]
Thoughts for the future - Amy said: We'll want to have explicit discussions for the more complex challenges (IA, hairier SME collab, etc)

**Comment by lianilychee** [comment]
- **Independent size XS fix **
  - remove "Is my issue critical?" section

- **SME size XS convo:**
  - how is escalation determined

- **SME size S convo:**
  - "Is my issue critical?" section
  - master branch - Naomi
  - binary rollbacks - technical accuracy check from SME

- independent size L work:**
  - grab industry precedents of support overview pages (technical products, platforms)

- **SME size XL convo:**
  - scope of doc needs to be with leadership: What's the diff between support and something that we must do for them (like spinning up a dashboard)
    - If leadership agrees that there is a difference betw the two, then we can remove sections of this page and decide next steps for addtl into (ex: describe VFS/Platform roles and responsibilities)



Hold on these pieces of work:
  - roles and responsibilities
  -   - small glossary - leadership/SRE - this work may still carry thru if we change 
  - Things we need SMEs to answer:
  - support request overview

**Comment by amygoldman** [comment]
Updates:

- Made a [copy in the drafts space](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2128183578/Support+overview+revision+draft+notes)
- Deleted most of the comments on this page and added them to the bottom of the copy in the drafts space
- Q: Does this wording work for the support request response time?
- - We'll acknowledge that we’ve received your support request within 3 business hours. Resolving your request may take longer. 
- Q: How should we direct people to use the support bot instead of directly messaging people on Slack in support channel?
- -  Should we link to this? https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html 
- Q: The [link at the top of the page](https://vfs.atlassian.net/wiki/spaces/SUP/pages/604012552/Support+overview#Support-Slack-channel) is just a link to this same page. Is that an error/should we make a suggestion?

**Comment by lianilychee** [comment]
Thurs 3/24:
- today
  - still need to reach out to Tim and Eric Boehs about how one escalates
  - hopefully get a chance to speak with Naomi
  -

**Comment by amygoldman** [comment]
Update: sync scheduled with Naomi for Fri (3/25)

**Comment by amygoldman** [comment]
Update: asked Tim & Eric about escalation

**Comment by lianilychee** [comment]
Fri 3/27:
- today
  - meeting with Naomi to make edits
  - remind Gretchen for links on precedents
  - articulating how the point of our current suport overview doc (will be in personal space)
    - blurb about apparent purpose of current doc
    - bullets outlining what content of page doesn't align with purpose

**Comment by amygoldman** [comment]
Update:

- synced with Naomi about replacing `master branch` with `main branch` & she suggested reaching out to Lainey
- [sent Lainey a message](https://dsva.slack.com/archives/CL181NRJQ/p1648230192543089) asking for her feedback & she responded that she'd like to talk to her team about this on Monday (they've been using both terms)
