### ISSUE TITLE
[BE] Implement new controller in vets-api for demographics confirmation

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#36469]
## Description
Create a new endpoint in vets-api for getting demographics confirmation from front end to call CHIP demographics confirmation endpoint for updating in VisTA

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [ ] Create Demographics endpoint that can be used for editing demographic in future
- [ ] Structure input parameters to accept demographic confirmation payload as optional
- [ ] Integrate with CHIP service layer
- [ ] Enable Logging
- [ ] Enable statsd metrics

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by kanchanasuriya** [comment]
@sarahknoppA6 Ticket waiting for verifying changes in Prod
