### ISSUE TITLE
[VAMC] Review and archive all Duplicate pages with "-0" and remove duplicates from Menu [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36463]
## Story
As a Veteran I need to have clear page and menus, so I do not get confused by duplicate pages or information on Menus

## TASK
- [x] Review and determine the actual duplicate page
- [x]  Update and archive the detail page
- [x] Remove duplicate entry from Menu

## Acceptance Criteria
- [x] All duplicate pages are archived
- [x] menus are updated.

**Comment by ltrombley** [comment]
Task #36463 = Review and archive all Duplicate pages with "-0" and remove duplicates from Menu - is Complete and moved to Validate.
