### ISSUE TITLE
[BE] Service layer changes for CHIP Demographics confirmation endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#36470]
## Description
Make changes in vets-api chip service layer to integrate with new demographics endpoint in CHIP

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Tasks
- [ ] Integrate with CHIP demographics confirmation endpoint
- [ ] Enable statsd metrics

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by sarahknoppA6** [comment]
@dillo can you review this PR?
