### ISSUE TITLE
[FE] Reset Validation Attempts in Session Storage

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#36483]
## User Story

As a user, my validate attempts in session storage should reset each time a new UUID is set for the session.

My validate attempts should also reset after a successful login on the Validate page.

## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

Update the useSessionStorage hook to be able to reset validateAttempts and reset them after a successful validate attempt and when a new UUID is set.

## Tasks

- [ ] Update useSessionStorage to include a reset for validate attempts
- [ ] Reset validation attempts after a successful validation
- [ ] Reset validation attempts when a new UUID is set
- [ ] Create or update unit tests
- [ ] Create or update e2e tests

## Acceptance Criteria

> when is the ticket done

- [ ] Error pages only show a visually red box for validation errors, and not for other errors (currently there is a bug where other errors can be displayed in the red box if the app is still in a maxValidationAttempts state)
- [ ] Users can no longer log in when the app is in a maxValidationAttempts state for a specific UUID (i.e. if you reload the page with the same UUID, it will not allow login with successful credentials)
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by loripusey** [comment]
@dcgoodwin2112 Can you verify if this is still needed

**Comment by acrollet** [comment]
@loripusey fysa we're pulling this into the current sprint since we're running low on work and it has potential veteran impact.

**Comment by brianseek** [comment]
FE only validation, will validate on stage tomorrow.
