### ISSUE TITLE
[FE][SPIKE] Reduce our Speed Curve Time

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#36482]
## User Story

As a veteran, the first meaningful paint for the screen should be under 3s

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Speed test results](https://app.speedcurve.com/va/va-check-in/test/220207_2Z_0d8949a6883fc144f34350aa19fba602/)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Spike and research ways to create a faster experience. 

This could be fake or real improvements. Off the top of my head, we could combine the landing and verify pages. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Proof of concept how to get this under 3s. 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
