### ISSUE TITLE
[Platform Console UI] Application onboarding infrastructure request

### ISSUE THREAD

**Issue by jchapin** [department-of-veterans-affairs/va.gov-team#36494]
## Summary
The purpose of this template is to capture requirements for onboarding a software application to the Platform's delivery infrastructure. 

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application

The Platform Console UI is to become a "single-pane-of-glass" system that brings all of the VA Platform resources together so that Platform Engineers can assist VFS Developers in developing functionality for VA customers.

This deployment is for one of our prototype systems Backstage.

### Basic info:
**Team Name:**   

Console UI Team @jchapin and @lhelmer points of contact.

**Application Name:**  

Platform Console UI

**Functionality:**  

The web-based user interface for the Platform Console.

We will also need an RDS PostgreSQL instance for data.

**Language/Stack:**  

TypeScript/Node.js

**Ports/Networking needed:**

80, 443, 5432

**Other infrastructure needed:**  

RDS, PostgreSQL

### Background/Context/Resources

https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP

### Technical Notes

The system needs to be able to network with the Access Management Keycloak instance. @ken-non and @kjduensing's responsibility.
The ability to contact RDS...

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] https://github.com/department-of-veterans-affairs/backstage-test
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team; Infrastructure Team can assist_  
- [x] https://raw.githubusercontent.com/department-of-veterans-affairs/backstage-test/main/packages/backend/Dockerfile
- [x] Platform PST Console UI

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions** Don't have one. Need One?
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:** Don't know yet
- [x] **Automation to release and tag the app's GitHub repo with a semantic version number** | @ericvoshall looking into this.
- [x] **Automation to push the app's container to ECR with a semantic version number** | Nothing yet, @ericvoshall is working on this with @dginther's advice.
- [x] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** in `vsp-infra-application-manifests` | TBD (ArgoCD)
- [x] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR | TBD

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** ie `/dsva-vagov/team-name/` | None at the moment, currently investigating AWS access and what we would store in SSM.
---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

https://github.com/department-of-veterans-affairs/va.gov-team/issues/35784 <- Initial ticket that we started to get this/these system(s) up.

**Comment by jhouse-solvd** [comment]
@jchapin - This is a fantastic start. Thank you! 

I believe the app will need an AWS service account for use with GitHub actions & a path in AWS parameter store where credentials can be stored. 

We are crafting a new template for each of those types of requests and will link them here. We'll follow up tomorrow.

**Comment by ericvoshall** [comment]
@jhouse-solvd Is Parameter Store something our team should request access to in AWS?

**Comment by jhouse-solvd** [comment]
@ericvoshall @jchapin - Please have your team fill the following: [Repository service account request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=infrastructure-request%2Caws%2Cgithub-actions&template=repository-service-account.yml&title=%5BAWS%2FGitHub%5D%3A+Repository+service+account+for+TEAM)

_This will help satisfy the first item under "Application delivery pipeline"_

**Comment by ericvoshall** [comment]
@jhouse-solvd @jsgarmon At the Ops office hours yesterday, I believe someone mentioned that our RDS instance was set up. Is that accurate? If so, how can I get the URL / port for that?

**Comment by jsgarmon** [comment]
The RDS instance in the dev environment is accessible from within EKS at `dsva-vagov-platform-console-ui-dev.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com`. The db password is stored in parameter store at `/dsva-vagov/platform-console-ui/dev/db_password`. Some specs:
![image](https://user-images.githubusercontent.com/47490730/154094389-d17cd34c-d962-423f-b110-2d10166bff66.png)

**Comment by ericvoshall** [comment]
Thanks @jsgarmon.

A few more questions:
- It looks like Parameter Store is set up for us now as well - are we good to go ahead and request access to that in AWS?
- Should the username our application uses to connect to the RDS instance be the "Master username" from the above screenshot?
- Should I be able to view information about the RDS instance on AWS? I get this error when I try to list RDS databases from the RDS Console: 
`User: arn:aws-us-gov:iam::008577686731:user/Eric.Voshall is not authorized to perform: rds:DescribeDBInstances on resource: arn:aws-us-gov:rds:us-gov-west-1:008577686731:db:* because no identity-based policy allows the rds:DescribeDBInstances action User: arn:aws-us-gov:iam::008577686731:user/Eric.Voshall is not authorized to perform: rds:DescribeDBClusters on resource: arn:aws-us-gov:rds:us-gov-west-1:*:cluster:* because no identity-based policy allows the rds:DescribeDBClusters action User: arn:aws-us-gov:iam::008577686731:user/Eric.Voshall is not authorized to perform: rds:DescribeGlobalClusters on resource: arn:aws:rds::008577686731:global-cluster:* because no identity-based policy allows the rds:DescribeGlobalClusters action`

**Comment by ericvoshall** [comment]
@jhouse-solvd @jsgarmon Is there a place to request a Github access token to be added to Parameter Store? 

We want to make use of the [upload-to-ecr](https://github.com/department-of-veterans-affairs/vsp-github-actions/tree/main/upload-to-ecr) Github Action which requires a Github access token in Parameter Store.

**Comment by ericvoshall** [comment]
I think we would also need a AWS KMS key for that action.

**Comment by jsgarmon** [comment]
Your service account has access to `/devops/VA_VSP_BOT_GITHUB_TOKEN` and `/devops/VA_VFS_BOT_GITHUB_TOKEN` in parameter store, which your Github actions can use if they need a token.

We will look into adding KMS permissions to this service account.

**Comment by ericvoshall** [comment]
@jhouse-solvd @jsgarmon Any update on a KMS key?

**Comment by jhouse-solvd** [comment]
@ericvoshall - The aws-kms-key requirement is new to me. Though it appears related to the work @dginther was doing recently for container scanning. 

Demian, is an aws-kms-key required when using [this](https://github.com/department-of-veterans-affairs/vsp-github-actions/tree/main/upload-to-ecr) action?  

cc: @jsgarmon

**Comment by ericvoshall** [comment]
We have updated our [CICD workflow](https://github.com/department-of-veterans-affairs/backstage-test/blob/main/.github/workflows/ci.yml) to close off the last few things on the checklist (tagging our repo with the version number, tagging the image on ECR with the SHA, and automatically updating the application manifest when our CICD workflow pushes a new image to ECR.

@jhouse-solvd @jsgarmon I think the last thing we may need your help with is the certificate for our application - we get the following error when navigating to our URL.

![image](https://user-images.githubusercontent.com/6836155/155009303-bef37e2a-e0d6-4b3b-8b15-7beb574ff322.png)

**Comment by jsgarmon** [comment]
This is an issue for all `*.vfs.va.gov` sites, since the VA-Internal-S2-ICA4 cert is not recognized (no certificate authority). Users can add this cert manually to allow browsers to trust it, but that's probably not a great long-term solution.
![image](https://user-images.githubusercontent.com/47490730/155029296-06928b30-8811-47c3-81e6-c73572eea433.png)

**Comment by jhouse-solvd** [comment]
@ericvoshall - To add to what @jsgarmon mentioned above:

The platform needs a solution for exposing this app (and others) on a public URL that can have a dedicated SSL certificate. 

For now, your team (or others needing to visit the URL) can click "Advanced" -> "Proceed to platform-console-ui-dev.vfs.va.gov (unsafe)"

We can discuss how to improve this experience before the tool goes live with VFS teams.

**Comment by jchapin** [comment]
@jhouse-solvd, @jsgarmon, @ericvoshall. Given the SSL situation described above and our ability to work around the certificate chain verification by adding those certificates to those which Node should allow... **I think we can probably close this issue now** that our dev system is up at https://platform-console-ui-dev.vfs.va.gov.

The communication between https://platform-console-ui-dev.vfs.va.gov and https://keycloak-dev.vfs.va.gov was a minor speed bump at the end, but we've addressed it.

We'll document the entire process from our perspective, compare some notes with IET, and then send our feedback to your team.

Thank you very much for all of your help in this process!

**Comment by jhouse-solvd** [comment]
@jchapin - This is awesome. Thanks for the extra info above. We'll be eager to receive your feedback. 

Based on the above, we'll close this issue. If there are additional needs from the team, we can scope new requests accordingly. ☺️ 

Closing.
