### ISSUE TITLE
[PM, Design] My VA - Payment Info: Update Contact Center guide to include the new section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36495]
## Background
The Contact Center guide needs to be updated with the new Benefit payments and debts section.  
The Contact Center guide may need additional updates, such as removing the breadcrumbs and updating the "Benfits you might be interested in" section with the new renaming and display logic.

#### Reference
- Current **[Contact Center Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md)**

NOTE: Heather has made some updates to **[this copy](https://docs.google.com/document/d/1PQesXzT3WIMrUWA4HXVnKyI3kEn9izuIM2XPJy_vUdc/edit?usp=sharing)**, housed within Google docs

## Tasks
- [x] Update Contact Center guide with new Benefit payments and debts section
- [x] Update Contact Center guide with changes made to 
     - Benefits you might be interested in
     - Breadcrumbs
     - Health care - unread messages
     - Any other changes not updated on the guide yet

## Acceptance Criteria
- [x] Contact Center guide will be updated with all changes made since last July, and the anticipated changes in relation to the new Benefit payments and debts release.

**Comment by hdjustice** [comment]
added the link.. sorry, i should have done that to begin with.

**Comment by andaleliz** [comment]
@hdjustice I see your note in the description, that you made edits in a copy. Should I start in [this Google doc](https://docs.google.com/document/d/1PQesXzT3WIMrUWA4HXVnKyI3kEn9izuIM2XPJy_vUdc/edit) (same as the one you linked above)?

**Comment by hdjustice** [comment]
Yes, If it helps you. I did a bunch of updates, like replacing a few images that had breadcrumbs, the new Claims **and** appeals verbiage, so the only items with comments left are the ones i think we need to address.  Everything else seems good to me.
I know it might be weird coming in with my half-way work.. I don't want to make this harder for you

**Comment by andaleliz** [comment]
@hdjustice I resolved all comments, added images, updated images, and updated figure numbers. I also added the error states for the new section and reviewed for any other updates I'm aware of since last July. 

If you can give this a once over when you're back, and then close it out when you're done, that'd be great! Thank you.

**Comment by hdjustice** [comment]
Reviewed updated contact center guide.
@Samara-Strauss - Would you like to review the document?  I have uploaded it to our **[payment info folder,](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/documentation)** and we can replace the old guide when we are ready for the Contact Center guide.

**Comment by Samara-Strauss** [comment]
This is great! I had some *very* minor typo edits I fixed, changes attached. Otherwise, this looks great and is ready to submit

[My.VA.2.0.Product-Guide.Version.3.dateTBD_SS edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8119902/My.VA.2.0.Product-Guide.Version.3.dateTBD_SS.edits.docx)
.

**Comment by hdjustice** [comment]
awesome!  Does this mean we submit for a contact center review per Collab Cycle?  If so, It said something about a video too, would I be the one to work on that?
