### ISSUE TITLE
[SW-Content] Update VA Home Loan rates - Product request: NADL rate increase [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36500]
## STORY
As a Veteran, I need to have access to the correct rates and interest information, for use in VA Home Loan Rates to assure correct information in my benefits journey.

## Resources
Raleigh Contreras, VBAVACO  Request
* I just got an update from my front office.  The NADL rate is increasing from 2.75 to 3.25%.  Could you change this on the NADL website?
[housing assistance home loan information](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Fhousing-assistance%2Fhome-loans%2Floan-types%2Fnative-american-direct-loan%2F&data=04%7C01%7Cstan.gardner%40gcio.com%7Ca68293197e534bc42b9608d9ea617624%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637798526605195951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bz2mizNSnfNu7RDFj3VTfny7g3rkM9x6hORlqZoAkSI%3D&reserved=0)

## TASK
- [x] Review page for listing of NADL rates 
- [x] Validate accuracy and update page
- [x] Submit for cross check

## Acceptance Criteria
- [x] All areas for NADL interest rates have been updated correctly to new percentage.
- [x] Stakeholder has received updated page for review and approval.

**Comment by lunascoop** [comment]
@RLHecht this page has been updated and is ready for review.

Native American Direct Loan: http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by RLHecht** [comment]
I copyedited and published this page. I let Raleigh know the changes are live. This is good to close.
