### ISSUE TITLE
[VBA Debt Portal] Bug - The existing empty state UI doesn't align with the intended experience

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#36502]
### Bug explanation

The VBA debt portal's empty state doesn't match the intended UI. When signed into test-user-40, there's a card at the top of the screen stating the Veteran doesn't have any current debts, however lower on the page there's an error about being unable to access current debt information. I've attached a screenshot below: 

![staging.va.gov_manage-va-debt_your-debt_.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/e3fc032f-ef15-4449-93ac-0264363d62a6)

### Intended experience

The empty state card shouldn't be above the 'On this page' component. It should display under the 'Current debts' header. [Please refer to this UXPin prototype for the intended UI.](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263630/simulate/no-panels?mode=i) 

---
## Tasks
- [ ] Update the UI to align with the provided UXPin prototype

## Acceptance Criteria
- [ ] The UI has been updated 
- [ ] Please tag @rileyorr in this ticket to review the updates

**Comment by denisecoveyduc** [comment]
Debt 2.0 will address this, confirm as this is implemented.

**Comment by OptionSelect** [comment]
Data has been fixed causing incorrect state to no longer be reached. User should not have data and we display as such in the CDP.

![image.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/01d5beff-4dbd-4949-9418-ed60c9ca99f0)
