### ISSUE TITLE
[UX] [Design] Update Poster to Include Android QR Code Information 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36507]
## User Story 
As a Veteran, I want to know if there are any recommendations for my Android device so that I can use the QR code to complete check-in effectively.

## Description 
Research was completed around how to modify the check-in poster to include recommendations for QR code scanning using an Android device. 

There were intermittent issues with Android devices and it was discovered this was due to device versions and QR code scanning supportability. 

Link to [research ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/35930) for this.

## Tasks 
- [x] Content for poster has been determined/reviewed/approved. 
- [x] Content added to poster 

## Acceptance Criteria
- [x] Poster includes new content regrading Android devices 
- [x] The posters have been uploaded to [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral) repo

Updated low vision poster is uploaded here:
https://github.com/department-of-veterans-affairs/va.gov-team/files/8090427/24x36-lowvision-v1.4a.pdf

**Comment by kristenmcconnell** [comment]
- Do these updates to the low vision poster.

**Comment by sarahknoppA6** [comment]
@niradatta1 and @zach-park currently validating

**Comment by zach-park** [comment]
@jparker0425, the revised lo vision poster is ready for PO review now:
https://github.com/department-of-veterans-affairs/va.gov-team/files/8090427/24x36-lowvision-v1.4a.pdf
Cc: @kristenmcconnell @niradatta1

**Comment by jparker0425** [comment]
@zach-park low vision poster looks good. I like keeping the question about QR scanning generic. Have these changes been applied to the other two sizes of the low vision poster as well ?
@kristenmcconnell @niradatta1

**Comment by jparker0425** [comment]
@zach-park , sure thing. I say this ticket can be closed and I will create a ticket for the other sizes.

**Comment by kristenmcconnell** [comment]
@jparker0425 Ticket already exists: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/35062
