### ISSUE TITLE
Auth Profile: Sprint 67 (Feb 9 - Feb 22) 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36509]
# Auth Profile: Sprint 66 (Jan 26 - Feb 8)

## PTO/OOO/Unavailable
- Marci 2/18
- President's Day 2/21 (VA, GCIO holiday)

# Priorities

1. Personal information Revision
2. Bad address indicator
3. All other (Address change messaging, general)

<hr>

### PM
- [ ] Determine when we will be ready for QA (assuming BE development starts on time)
- [ ] Update FE documentation with final copy & design info

### Design - Christina
- [ ] #36240
- [ ] Finish all design updates (pending dependency on all of our partners)
- [ ] Update interaction design for text box input ("A [field] not listed here" options)

### FE - Adam
- [ ] #36006
- [ ] Implement any design updates that are ready

### BE - Tom - VA Profile is tarteting 2/14 for being ready for us
- [ ] #32847
- [ ] #32848

<hr>

### Design - need to clarify long/short term tasks
- [ ] #35585 - moving to next sprint
- [ ] Meet with Marci/Samara to go over work
- [ ] Start design discovery
   - Understand the problem/background
   - Figure out what questions you have. Some questions I have:
       - When someone is on VA.gov, when can we detect that they have a bad address?
         Can we proactively email all people who have the bad address indicator to log into VA.gov and update their address? How would this work?
   - Get answers to those question

### BE - Tom
- [ ] #33582

<hr>

### Design
- [ ] Finish all design updates (pending dependency on all of our partners)
- [ ] Update interaction design for text box input ("A [field] not listed here" options)

**FE**

- [ ]  Personal information revisions: Update Gender identity and Sexual orientation so they are multiselect #36168
- [ ]  Personal information revisions: Remove "prefer not to answer" from pronoun field #36174

<hr>

### PM
- [ ] #33007 (still monitoring for feedback from VBA; took over from Liz; Jeremy responded but still doesn't have final info.

### FE -  Adam
- [ ] #35981
- [ ] #19618 

<hr>
