### ISSUE TITLE
[BE] | test new Direct-To-Salesforce STAGING connection (on Gov Cloud Plus)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36508]
## Description

Salesforce (which the CARMA app sits behind) will be migrating from Gov Cloud to Gov Cloud Plus around Feb 26th.

In support of this testing effort, we will need to point our staging env at their new GC+ env and conduct testing to ensure that everything works as expected.

Once our staging direct connection to Saleforce is tested on their new GC+ env, then we can toggle the 1010CG client back to Mulesoft and continue testing Mulesoft staging which will be pointed at (the old) Salesforce staging.

## Tasks

- [ ] Point staging environment to GC+ (GovCloudPlus) instance 
  - [x] New credentials (provided by Shirley) need to be put into AWS parameter store
  - [x] Create a devops PR to point to new credentials in AWS parameter store
  - [ ] Deployment of staging instance using the new credentials that devops repo gets from AWS parameter store

## Acceptance Criteria

- [ ] Successfully tested in staging 
- [ ] Successful production between MS and prod Vets-API

Q: Do we know if we need to revert the staging instance back (check with Shirley)

**Comment by RudyOnRails** [comment]
<img width="897" alt="Screen Shot 2022-02-07 at 2 40 21 PM" src="https://user-images.githubusercontent.com/1021154/152868502-f1524c33-6e90-4230-b9df-80a4ad936b32.png">

**Comment by SKasimow** [comment]
Hi @RudyOnRails - I cleaned up this ticket; please check/edit as needed. Also how many points should we put on this?

Thanks,

-S

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---10-10-Team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/36508?planning-poker) with ZenHub @RudyOnRails

**Comment by RudyOnRails** [comment]
@SKasimow are you ok with me making this a mini epic? So we can break down tickets and observe the high-level epic?

**Comment by SKasimow** [comment]
@RudyOnRails for sure! If you want to outline/slack me how to structure the tickets, happy to set them up (or feel free if easier to do yourself - just lmk if I can help) :)

**Comment by RudyOnRails** [comment]
Connection test from staging to SF GovCloudPlus was successful.

https://dsva.slack.com/archives/C02MJCT59S7/p1644523305101639
