### ISSUE TITLE
Auth Profile [Issue Name]

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36514]
## Background
In ticket #35981 Adam evaluated changes required to support the React-router update and determined the following:

> Overall it looks pretty straightforward to update the personalization/profile app since it is shown as using the 'NEW' component routing configuration, so minimal changes should be needed.

>There is a note showing that the profile is using an 'Old Import,' so that will likely be needing an update task, but probably just 2 points with the criteria of:

>updating the import to new import path
fix any breaking changes that could occur
verify that tests pass and update any tests if needed

## Tasks
- [ ] Update the import to new import path
- [ ] Fix any breaking changes 
- [ ] Verify that tests pass and update any tests if needed

## Acceptance Criteria
- [ ] Update the import to new import path
- [ ] Fix any breaking changes 
- [ ] Verify that tests pass and update any tests if needed

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Add label for practice area (frontend, backend, design)
- Assign to a Profile team member
- Associate with an Epic if applicable

**Comment by adamwhitlock1** [comment]
This article may be helpful for me as I go through the changes required.

https://medium.com/@apaar256/migrating-react-v15-5-to-v16-8-and-react-router-v3-to-v5-b9426aa7c305

**Comment by adamwhitlock1** [comment]
@MarciMcGuireGCIO This ticket should be good to go. Have checked in staging and prod and all profile routes are loading as expected.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @adamwhitlock1 ! Nice work! 🥳 

cc @Samara-Strauss
