### ISSUE TITLE
Forms Dashboard:  Exclude/Remove Internal form URLs

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36515]
## Issue Description
The Forms Dashboard "previous page" table includes a lot of internal form URLs.  Can we exclude those in BQ?
---
## Tasks
- [ ] Update BQ to remove internal form URLs from "previous page" table

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by obrienjulie** [comment]
BQ view has been updated to exclude the internal Forms URLS.
