### ISSUE TITLE
Access to Sentry alerts regarding Form 526 submissions

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/va.gov-team#36519]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

My team and I would like to access Sentry alerts resulting from errors raised [here in our prototype](https://github.com/department-of-veterans-affairs/vets-api/blob/434177d0be24f2c4c58ec31b8d2d83879f35d4e0/app/workers/fast_track/disability_compensation_job.rb#L51).
I have access to Sentry, but it's unclear which [Sentry team](http://sentry.vfs.va.gov/settings/vsp/teams/) or [Sentry project](http://sentry.vfs.va.gov/settings/vsp/projects/)) I should join to see those alerts, or if a new team needs to be created for us.

Any assistance or instruction is appreciated.

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

[Support request submitted to #vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1644265146748199)

Our prototype is Rapid Ready for Decision (RRD), currently fast tracking hypertension claims for Form 526. Our team is led by Zach Goldfine.

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] _What things need to happen?_
   - Either add me (and my teammates) to an existing Sentry team,
   - Or create a new Sentry team for us.
   - If this is not self-service (i.e., if I can't join the team myself), then my other teammates will also need to be added to the same team(s). I can provide their names or VA.gov email addresses if needed.

## Acceptance Criteria 
- [x] _What are the specific things that must be true in order for this to be accepted?_
   -  access Sentry alerts resulting from errors raised [here in our prototype](https://github.com/department-of-veterans-affairs/vets-api/blob/434177d0be24f2c4c58ec31b8d2d83879f35d4e0/app/workers/fast_track/disability_compensation_job.rb#L51)

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by zachclarity** [comment]
Checking on this again thanks.

**Comment by jbritt1** [comment]
Created team, added requested members, made Yoom an admin of the team to give the ability to add future users

**Comment by yoomlam** [comment]
After @jbritt1 added project 'platform-api' to our new team, I confirmed that I can see our errors!
