### ISSUE TITLE
Data Dictionary:  Add New Chatbot Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36513]
## Issue Description
Need to add new chatbot events to the data dictionary

---
## Tasks
- [ ] Update data dictionary with new chatbot events

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bsmartin-ep** [comment]
Published....

https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Chatbot-Events.2082406604.html
