### ISSUE TITLE
Research and Decide how to handle items that are not managed by Terraform or are Legacy 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36523]
## Description
There are AWS items that were created outside of Terraform which may need to be managed and supported. see this thread as an example.  https://dsva.slack.com/archives/CJYRZK2HH/p1644268833859759

## Tasks
- [ ]  List of AWS resources that are not managed by terraform or legacy 
- [ ] A process and decision on how to support this items.

## Acceptance Criteria 
- [ ] A decision and plan with a process on how to handle these items.

**Comment by little-oddball** [comment]
Not sure why SRE would be responsible for this. Closing based on OBE.
