### ISSUE TITLE
[Debt Letters] eslint (depricate/import) - LoadingIndicator

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#36526]
## Issue Description
Platform deprecated `<LoadingIndicator>`, suggesting we use `<va-loading-indicator>` instead.

---
## Screenshot
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/9ec04021-88ac-409b-8521-51333bf2f8e5)

---
## Tasks
- [x] Replace `<LoadingIndicator>` with new `<va-loading-indicator>`

## Acceptance Criteria
- [x] Should render `<va-loading-indicator>` instead
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Closing this one as #36222 will cover all apps
