### ISSUE TITLE
SUPPORT: Transform Contact Center team's content

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36532]
# User story

As a Contact Center team member, I need my content to follow the "how to" and "overview" templates, so that (a) VFS teams can quickly understand how to perform contact center related tasks (b) my info is in line with Platform website content norms.

As a VFS team member, I need to clearly understand and perform contact center related tasks, so that I can iterate on my contact center processes to serve Veterans.

# Tasks

- [ ] Lightweight kickoff between Contact Center and Content teams
  - This session clarifies what we need from each other + expected publication date
- [ ] Establish recurring similar to current QAST <> Content collaboration
- [ ] Compare GH page and Platform website page to determine what’s redundant
- [ ] Transform the pages
- [ ] Secure SME and final approval
- [ ] Publish pages to Platform website

# Acceptance criteria

# Reference info
- n/a

**Comment by lianilychee** [comment]
We are either publishing as-is, or improving and publishing.

If the former, then Lauren will shadow Amy.  If the latter, then... we'll decide how to handle the improvement when we get there.

**Comment by lianilychee** [comment]
3/8 Tues:
- Today:
  - Would like to transform at least one of the doc, possible can do the last two
  - draft message to Jason
    - "we've looked at your docs, they're overall good, This is our recommendation ___, and we're going to go ahead and transform and work with you to publish if we don't hear back by X date." <-- send this draft to #content-chats

**Comment by amygoldman** [comment]
Link to [the parent page for all the drafts](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2115207418/Contact+center+docs) in the drafts space

**Comment by amygoldman** [comment]
Hi Jason!

We finished reviewing the Contact Center docs you shared with us. We made copies in the drafts space and edited the docs from there. Here are the edited versions of the docs:
- Link
- Link
- Link

Let us know what you think of these recommendations. We’ll transform the docs in your team space and work with you to publish them if we don't hear back by [date].

FYI, I accidentally directly edited the existing “How to use Medallia Data in DOMO” doc in your team’s space instead of the copy in the drafts space. Sorry for the confusion! 

Thanks!

**Comment by amygoldman** [comment]
Update:

- Finished editing all 3 docs
- Left a few questions for Jason or SME as comments
- [Sent Jason the message](https://dsva.slack.com/archives/CL181NRJQ/p1647008471741119)
- Will update based on feedback to questions

**Comment by amygoldman** [comment]
Update:

- Jason provided feedback and approval
- I made his recommended edits
- [Shared docs in Slack](https://thesocompany.slack.com/archives/C02LYB7QXS5/p1647034822572869) for team to pub on Mon

**Comment by lianilychee** [comment]
3/14 Mon:
- samara cross-referenced documents with style guide
- liani review samara's comments and publish the pages
