### ISSUE TITLE
SSL problem when attempting to connect from `vets-api` staging to Mulesoft staging

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#36543]
## Description
This is a continuation of the Platform Support Request at https://dsva.slack.com/archives/CBU0KDSB1/p1643811953261089. 

@zachclarity suggested we open an Ops Issue ticket and add context here.

## Background/context 
This is related to the Salesforce/Mulesoft testing on staging (which some of you may know already about) for the 10-10CG form to make it to CARMA. The old way 1010CG's got to CARMA were through Salesforce directly; that connection works ok. The problem we are having is with connecting to Salesforce's new Mulesoft service.

## Technical notes
When we try to cURL from a staging `vets-api` (or a staging fwdproxy) instance using `curl -I "https://stage.vapi.va.gov"` we receive the following error:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

---
## Tasks
- [ ] I'm not sure to be honest, I am not a pro at SSL certificates.

## Acceptance Criteria 
- [ ] With the `caregiver_mulesoft` feature toggle enabled and SSL enabled in staging, successfully submit a 1010CG to CARMA.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@RudyOnRails - Would you know who configures and/or maintains the Mulesoft endpoint in question, "stage.vapi.va.gov"? Were you given instructions for setting up a secure connection to that endpoint? 

Without knowing how to connect to the Mulesoft endpoint, or what the desired configuration is, it can be hard to troubleshoot. We are happy to help but are unfamiliar with the integration that you are configuring. However, it's possible that you'll need to specify a certificate when connecting to "https://stage.vapi.va.gov". 

Before the integration goes live in staging, you'll also need to configure a service on the forward proxy. That is where you can define a certificate to be used when connecting to Mulesoft. 

If you take a look at [this configuration file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml), you'll notice that there are other integrations configured. Many of them are using certificates when reaching out to external providers.  

cc: @mchelen @dillo @SKasimow

**Comment by RudyOnRails** [comment]
@jhouse-solvd Thank you for your time and the thorough response.

> Would you know who configures and/or maintains the Mulesoft endpoint in question, "stage.vapi.va.gov"?
Great question - I'm not sure. We are working with Salesforce but it's a va.gov domain so I'm confused.

> Were you given instructions for setting up a secure connection to that endpoint?
I was brought on to the team to pick up where Dillo left off, so I am not 100% sure. I will ask the Salesforce team and comment back here.

I decided to read the **Adding a new External Service Integration** docu and it says I [_should_](https://depo-platform-documentation.scrollhelp.site/developer-docs/Adding-a-new-External-Service-Integration.1884586162.html#:~:text=Anything%20over%20port%20443%20should%20work) be able to cURL the endpoint from the fwdproxy, but I am still getting the SSL error from the staging fwdproxy. Does that give you a clue as to what may be the problem? Is there a CA cert that needs to be added to `/etc/pki/tls/certs/ca-bundle.crt`?

```
[dsva@ip-10-247-34-182 ~]$ curl -v https://stage.vapi.va.gov
* Rebuilt URL to: https://stage.vapi.va.gov/
*   Trying 15.200.118.105...
* TCP_NODELAY set
* Connected to stage.vapi.va.gov (15.200.118.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by RudyOnRails** [comment]
@jhouse-solvd - Morning. I asked Salesforce these questions and they replied with:
> The VA DTC (Digital Transformation Center).  They configured the VA Internal SSL certificate. 

> Or directed it - NetOps may have configured the actual proxy server

Also, Lance helped me run this to see the "certificate chain". Thought I'd include here just in case it helps.

```
[dsva@ip-10-247-34-200 ~]$ openssl s_client -connect stage.vapi.va.gov:443
CONNECTED(00000003)
depth=0 C = US, ST = DC, L = Washington, O = Veterans Affairs, CN = stage.vapi.va.gov, emailAddress = satish.mamindla@va.gov
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = DC, L = Washington, O = Veterans Affairs, CN = stage.vapi.va.gov, emailAddress = satish.mamindla@va.gov
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=US/ST=DC/L=Washington/O=Veterans Affairs/CN=stage.vapi.va.gov/emailAddress=satish.mamindla@va.gov
   i:/DC=gov/DC=va/CN=VA-Internal-S2-ICA4
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFQTCCBCmgAwIBAgIHPQAAAAAi3zANBgkqhkiG9w0BAQsFADBHMRMwEQYKCZIm
iZPyLGQBGRYDZ292MRIwEAYKCZImiZPyLGQBGRYCdmExHDAaBgNVBAMTE1ZBLUlu
dGVybmFsLVMyLUlDQTQwHhcNMjEwNTE3MTExODAwWhcNMjIwNjEwMTExODAwWjCB
jTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkRDMRMwEQYDVQQHEwpXYXNoaW5ndG9u
MRkwFwYDVQQKExBWZXRlcmFucyBBZmZhaXJzMRowGAYDVQQDExFzdGFnZS52YXBp
LnZhLmdvdjElMCMGCSqGSIb3DQEJARYWc2F0aXNoLm1hbWluZGxhQHZhLmdvdjCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMRg/aJ4zBdVqafnf3IFYS5Y
6vXOcOyUI26JPHZ224CTJ6IhSq8QRxJepDFwk4g3VXBibOmjSKJoD0UxGtbPaez2
G8C81VfiMi03+b9tPjcYr4v/EbvBH+5fbA+IB6ct3BYUKpRgEsCyrXuPBX0mxHGV
gZtxsDWlDR/UlBtDd4FHNF8HRoNEwdUGW4+Rta4fM16SU3Cw1iXWZJFqK2r9cvyF
m4GLMivc3JZobaM000LVpEQFob/FJZ/aQRMnxW4SAbQOuIlEf7LXqFow5c31BcKL
Yw08CGw2rQay85le43kug2M/mFm+nM30gOd11O8rEirvP5JFikaP6ljWLbtVSc0C
AwEAAaOCAekwggHlMB0GA1UdDgQWBBReS/97vvcwUmUdqN1b2i6rR4bGLjAMBgNV
HRMBAf8EAjAAMAsGA1UdDwQEAwIE8DA/BgNVHREEODA2gg9kZXYudmFwaS52YS5n
b3aCEHRlc3QudmFwaS52YS5nb3aCEXN0YWdlLnZhcGkudmEuZ292MB8GA1UdIwQY
MBaAFGi3comeQurkUUUfWKIKJw9zYECjMEYGA1UdHwQ/MD0wO6A5oDeGNWh0dHA6
Ly9jcmwucGtpLnZhLmdvdi9wa2kvY3JsL1ZBLUludGVybmFsLVMyLUlDQTQuY3Js
MHgGCCsGAQUFBwEBBGwwajBEBggrBgEFBQcwAoY4aHR0cDovL2FpYS5wa2kudmEu
Z292L3BraS9haWEvdmEvVkEtSW50ZXJuYWwtUzItSUNBNC5jZXIwIgYIKwYBBQUH
MAGGFmh0dHA6Ly9vY3NwLnBraS52YS5nb3YwPQYJKwYBBAGCNxUHBDAwLgYmKwYB
BAGCNxUIgcjDM4H58AaBpZ8NhOCBCIXCqksGgtrLEYHR8FYCAWQCASswHQYDVR0l
BBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYB
BQUHAwIwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAIzqOcW3Vj4ow9xZ
rhJ3EKL/hDGqX0Cz/cKTmjvMj6c92hMGkXkCZAkFN2+2RhIh8EPv157ezBt6ViD5
939HlFXn7KhsjTaUKlM6HqYWXEPT6f5lCDaUksARWQiIUHyBv9gs2O5bKlw0GfO1
0smBgBsEFZRaUEtyyeqVG6GYM+wUYnXaTCvATTOUMWuVb4zXc0+0sE4QT3jK4zwu
EHHiKyIzGFncLsBeuy6AMdoejPfEKv5htTclxL2l9a17/fmBoax3sou0RolvCIXK
Ns7Bg0s5aui1mVQvyQH09LeaFox7Z6CkKGxkYfJzsvPwn1UcdB9pmi+pSQqVAM8F
prNclqc=
-----END CERTIFICATE-----
subject=/C=US/ST=DC/L=Washington/O=Veterans Affairs/CN=stage.vapi.va.gov/emailAddress=satish.mamindla@va.gov
issuer=/DC=gov/DC=va/CN=VA-Internal-S2-ICA4
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1861 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: E9672D5A64ECBA74D5B6CB8E20B142479E7836EE416D56866A5E9DB2E1D8A51A
    Session-ID-ctx:
    Master-Key: 95040787C504278246A933ED50EE4CCDB037ABB58CB19A59B1C5E2F74AD6EAE8F5113A2A7DB8DDF347F3989248100089
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1644504025
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
```

**Comment by RudyOnRails** [comment]
> [@Kevin Musiorski (MOO-SHORE-SKI)](https://dsva.slack.com/team/U024YSK7796) you can start with Vivek ([Vivek.Lakamanayakanpatti@b3groupinc.com](mailto:Vivek.Lakamanayakanpatti@b3groupinc.com)) he should be able to provide guidance (he's the Lead Mule architect on the DTC)

**Comment by RudyOnRails** [comment]
Sorry, my authoring of messages sucks. @jhouse-solvd please see above answer ☝️  that I got from Salesforce team.

**Comment by jhouse-solvd** [comment]
@RudyOnRails - I'm following up w/ the team today to see if there are any troubleshooting recommendations.

**Comment by RudyOnRails** [comment]
@jhouse-solvd thanks. I am also trying a troubleshooting step myself that I saw Jeremy Britt run on a different ticket. Basically running a curl but specifying the cert and key. Not sure if the cert and key already exist but 🤞 .

Also, we have a technical call at 2pm today with Salesforce. Would you or anyone on your team be able to join for a few and maybe get the info you need?

**Comment by jhouse-solvd** [comment]
@RudyOnRails - It's likely that you would need a client certificate "in hand" (aka on the machine that you are connecting _from_) in order to test this connection. And, unless you are on the forward proxy (fwdproxy) directly, you would have to designate a fwdproxy endpoint to be used when connecting to the remote endpoint.

Our recommendation is to set up the fwdproxy configuration now. It will ultimately be necessary for this connection to work. Other forms of testing - without setting up this configuration - may provide unexpected results. 

Please see [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml) for example fwdproxy configuration. 

Please see [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594279/Forward+Proxy) for additional details on configuration. There's a lot of great information that should be useful. 

Let us know if you have any questions.

**Comment by RudyOnRails** [comment]
Yeah, sorry @jhouse-solvd , that's what I was talking about, but didn't use words correctly and completely omitted the word fwdproxy.

I'm testing it now.

**Comment by RudyOnRails** [comment]
@jhouse-solvd Is there someone on your team that I can pair with for 10 minutes today and 10 minutes tomorrow? I am an amateur in the arts of SSL certs and really could use some help to set this up. I'm glad to learn, but I need an expert who _understands_ SSL certificates and chains. I am not saying I won't learn new things, but this is a lot to understand and I don't have much time.

I'm studying and reading as much as I can, but am worried I will not be able to do this myself. I may get it figured out, but would love if you or someone on your team could give me 10, even 5 minutes of their time either today or tomorrow, even Thurs if I don't have it figured out yet.

Thanks,
Kevin

**Comment by jhouse-solvd** [comment]
@RudyOnRails - The Infrastructure Team has office hours M/W/F @ 1300 ET. That meeting is a great place to bring requests such as these. We're happy to provide guidance and take a look with you. The link to the meeting can be found in the #vsp-operations channel description in DSVA Slack. 

We hope to see you there!

**Comment by jbritt1** [comment]
If we were to generate an entirely new certificate for this connection, do we know what the upstream has whitelisted? I believe we typically leverage client-tls-dns, meaning they would likely have to whitelist an agreed upon common name (CN) for the connection to work once there is a certificate in the connection.

**Comment by jhouse-solvd** [comment]
To summarize: 

technical points: 
- It's possible that what's needed in this scenario is for a new "client TLS DNS" certificate to be created in Venafi. 
- Then, that certificate and its private key would need to be installed on the forward proxy. 
- Then, the common name of the certificate (which usually corresponds to a DNS hostname) would need to be whitelisted with the external services provider. 

roles and support points: 
- This can be done by any team/engineer that has access to Venafi
- If the team does not have the access/expertise to do this, then the Infrastructure team can assist, though we would need to create a new request and schedule for an upcoming sprint 
- If this is what's needed, expectations for the implementation timeline will need to be reset accordingly

@mchelen - for your awareness; it may be helpful to communicate with this team's product owner to ensure alignment

**Comment by jhouse-solvd** [comment]
This ticket is related to #34690

**Comment by RudyOnRails** [comment]
@jhouse-solvd There is a Salesforce project call scheduled for tomorrow at 11:30am Eastern, regarding this work. Would someone on your team please be willing to join and help us out / back us up?

**Comment by jbritt1** [comment]
Relevant Slack thread: https://dsva.slack.com/archives/CJYRZK2HH/p1645114846649099

**Comment by RudyOnRails** [comment]
@jbritt1 I have asked SF to whitelist the CN's:
> [@Aaron Sudholt](https://dsva.slack.com/team/U010RL5CNKZ) [@Paul Kuprionas](https://dsva.slack.com/team/U01SBM6KW90) [@Igor Khurgin](https://dsva.slack.com/team/U01RX1W5H0F) [va.gov](http://va.gov/) Infra/Platform is asking the SF side to whitelist several agreed upon CN’s (Common Names) of the TLS connections. (I.e. form1010cg-dev.va.gov, form1010cg-staging.va.gov, form1010cg-prod.va.gov)

**Comment by jbritt1** [comment]
> @jbritt1 I have asked SF to whitelist the CN's:
> 
> > [@Aaron Sudholt](https://dsva.slack.com/team/U010RL5CNKZ) [@Paul Kuprionas](https://dsva.slack.com/team/U01SBM6KW90) [@Igor Khurgin](https://dsva.slack.com/team/U01RX1W5H0F) [va.gov](http://va.gov/) Infra/Platform is asking the SF side to whitelist several agreed upon CN’s (Common Names) of the TLS connections. (I.e. form1010cg-dev.va.gov, form1010cg-staging.va.gov, form1010cg-prod.va.gov)

Roger, let us know what they say once you get some correspondence.

**Comment by RudyOnRails** [comment]
> 

They are saying this is not a connectivity issue and that is what whitelisting is for, and typically IP's....here's verbatim...

```
[Ranganathan Balasubramanian](https://app.slack.com/team/U01SQ94PTUZ)  [1 hour ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645134685102679?thread_ts=1645132316.566309&cid=C02MJCT59S7)
I don't think we can whitleist CNs for Salesforce e as that's is mostly an instance level update but wondering what we are trying to achieve here as the issue is with vets-api talking to mule gov cloud




[Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [1 hour ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645134691945599?thread_ts=1645132316.566309&cid=C02MJCT59S7)
Salesforce only whitelists ip’s

[Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [1 hour ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645134766526519?thread_ts=1645132316.566309&cid=C02MJCT59S7)
I am not sure I fully understand the need here. Why we go from configuring root CA on the [Va.gov](http://va.gov/) platform to whitelisting common names. I don’t think we have a connectivity issue which is typically what requires whitelisting….
```

**Comment by RudyOnRails** [comment]
@jbritt1 and team:

> [Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [< 1 minute ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645138177402439?thread_ts=1645132316.566309&cid=C02MJCT59S7)
[@Kevin Musiorski (MOO-SHORE-SKI)](https://dsva.slack.com/team/U024YSK7796) I think we need a meeting with your DevOps team to better understand your needs. I am not sure I follow why [VA.gov](http://va.gov/) platform can’t use the Mulesoft certificate signed by VA CA I also don’t understand why Salesforce needs to whiltelist anything. I know the existing integration between VA,gov and Salesforce in production did not require any whitelisting. Embedding a Mule proxy means that communication to Salesforce is shielded from [VA.Gov](http://va.gov/) platform. We also have another application that consumes a different CARMA API hosted on Mulesoft and we did not have any certificate related issues.

**Comment by jbritt1** [comment]
Then I am all out of ideas /shrug

**Comment by jbritt1** [comment]
Pulling the cert and using it in a curl command proved to not work in the slightest.

**Comment by RudyOnRails** [comment]
We will figure it out @jbritt1. I hope this isn't making your day worse - I really do appreciate your assistance with this.

I have asked them to add you to the salesforce/dsva slack channel vecms-carma_vadotgov_development_external. Hope you (and @jhouse-solvd) are ok with this. I don't mean to be cutting in line or taking you away from your sprint work.

**Comment by jbritt1** [comment]
Further proof:

```
[root@ip-10-247-32-252 ~]# openssl s_client -connect stage.vapi.va.gov:443 -showcerts 2>/dev/null </dev/null | openssl x509 -outform pem > filename.pem
[root@ip-10-247-32-252 ~]# ls -al
-rw-r--r--  1 root root    1883 Feb 17 23:05 filename.pem
[root@ip-10-247-32-252 ~]# mv filename.pem /etc/pki/ca-trust/
ca-legacy.conf  extracted/      README          source/
[root@ip-10-247-32-252 ~]# mv filename.pem /etc/pki/ca-trust/source/anchors/
DigiCertGlobalCAG2.crt.pem           Federal_Common_Policy_CA.pem         self.crt                             VA-Internal-S2-ICA2-v1.pem           va.pem
DigiCertTLSRSASHA2562020CA1.crt.pem  forward-proxy.crt                    VA-Internal-S2-ICA1-v1.pem           VA-Internal-S2-RCA-v1.pem            Verizon_SSP_CA_A2.pem
[root@ip-10-247-32-252 ~]# mv filename.pem /etc/pki/ca-trust/source/anchors/
[root@ip-10-247-32-252 ~]# ls -al /etc/pki/ca-trust/source/anchors/
total 52
drwxr-xr-x 2 root root 4096 Feb 17 23:06 .
drwxr-xr-x 4 root root 4096 Feb 14 10:04 ..
-rw-r--r-- 1 root root 1635 Feb 17 21:01 DigiCertGlobalCAG2.crt.pem
-rw-r--r-- 1 root root 1738 Feb 17 21:01 DigiCertTLSRSASHA2562020CA1.crt.pem
-rw------- 1 root root 1578 Feb 17 21:15 Federal_Common_Policy_CA.pem
-rw-r--r-- 1 root root 1883 Feb 17 23:05 filename.pem
-rw------- 1 root root 1448 Feb 17 21:15 forward-proxy.crt
-rw------- 1 root root 1448 Feb 17 21:15 self.crt
-rw-r--r-- 1 root root 1690 Feb 17 21:01 VA-Internal-S2-ICA1-v1.pem
-rw-r--r-- 1 root root 1663 Feb 17 21:01 VA-Internal-S2-ICA2-v1.pem
-rw-r--r-- 1 root root 1306 Feb 17 21:01 VA-Internal-S2-RCA-v1.pem
-rw-r--r-- 1 root root 3363 Feb 17 21:01 va.pem
-rw------- 1 root root 1740 Feb 17 21:15 Verizon_SSP_CA_A2.pem
[root@ip-10-247-32-252 ~]# update-ca-trust
p11-kit: duplicate '*.us-gov-west-1.elb.amazonaws.com' certificate found in: forward-proxy.crt
p11-kit: duplicate '*.us-gov-west-1.elb.amazonaws.com' certificate found in: forward-proxy.crt
p11-kit: duplicate '*.us-gov-west-1.elb.amazonaws.com' certificate found in: forward-proxy.crt
p11-kit: duplicate '*.us-gov-west-1.elb.amazonaws.com' certificate found in: forward-proxy.crt
p11-kit: duplicate '*.us-gov-west-1.elb.amazonaws.com' certificate found in: forward-proxy.crt
[root@ip-10-247-32-252 ~]# curl -vvv https://stage.vapi.va.gov
* Rebuilt URL to: https://stage.vapi.va.gov/
*   Trying 15.200.118.105...
* TCP_NODELAY set
* Connected to stage.vapi.va.gov (15.200.118.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by RudyOnRails** [comment]
[Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [3 minutes ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645139788000679?thread_ts=1645132316.566309&cid=C02MJCT59S7)
If your team needs a CA cert we can provide it for you. I checked the cert in chrome browser on the GFE and the. cert. looks good.

![image (3)](https://user-images.githubusercontent.com/1021154/154588097-68a5b4d2-1265-4175-9d73-6f2d6b5d3940.png)

**Comment by RudyOnRails** [comment]
> [Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [3 minutes ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645139866867579?thread_ts=1645132316.566309&cid=C02MJCT59S7)
> The DNS name matches the name on the cert. I also validated that the CA cert. is installed into the browser by VA IT and i don’t get any errors with cert validation
> 
> 
> 
> 
> [Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [1 minute ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645139976540539?thread_ts=1645132316.566309&cid=C02MJCT59S7)
> I can provide the CA cert fo you if you would like. I can extract it from certmgr on GFE

**Comment by jbritt1** [comment]
That certificate already lives on the forward proxy boxes and has for a long time.

**Comment by jbritt1** [comment]
That certificate is already installed on our forward proxy instances and has been for quite some time:

```
[root@ip-10-247-32-252 ~]# ls -al /etc/pki/ca-trust/source/anchors/
total 52
drwxr-xr-x 2 root root 4096 Feb 17 23:06 .
drwxr-xr-x 4 root root 4096 Feb 14 10:04 ..
-rw-r--r-- 1 root root 1635 Feb 17 21:01 DigiCertGlobalCAG2.crt.pem
-rw-r--r-- 1 root root 1738 Feb 17 21:01 DigiCertTLSRSASHA2562020CA1.crt.pem
-rw------- 1 root root 1578 Feb 17 21:15 Federal_Common_Policy_CA.pem
-rw-r--r-- 1 root root 1883 Feb 17 23:05 filename.pem
-rw------- 1 root root 1448 Feb 17 21:15 forward-proxy.crt
-rw------- 1 root root 1448 Feb 17 21:15 self.crt
-rw-r--r-- 1 root root 1690 Feb 17 21:01 VA-Internal-S2-ICA1-v1.pem
-rw-r--r-- 1 root root 1663 Feb 17 21:01 VA-Internal-S2-ICA2-v1.pem
-rw-r--r-- 1 root root 1306 Feb 17 21:01 VA-Internal-S2-RCA-v1.pem
-rw-r--r-- 1 root root 3363 Feb 17 21:01 va.pem
-rw------- 1 root root 1740 Feb 17 21:15 Verizon_SSP_CA_A2.pem

**Comment by jbritt1** [comment]
Oh actually, we have ICA1 and ICA2 but not this ICA4

**Comment by RudyOnRails** [comment]
🍿

**Comment by RudyOnRails** [comment]
@jbritt1

> [Igor Khurgin](https://app.slack.com/team/U01RX1W5H0F)  [< 1 minute ago](https://dsva.slack.com/archives/C02MJCT59S7/p1645140691710329?thread_ts=1645132316.566309&cid=C02MJCT59S7)
so do you need ICA4? I just extracted it on my GFE  and saved it in DER format

**Comment by jbritt1** [comment]
We need it in the pem format I believe. One that starts with `-----BEGIN CERTIFICATE-----` like so: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/trusted-certs/files/VA-Internal-S2-ICA1-v1.pem

**Comment by RudyOnRails** [comment]
Ok, I'm having him send. I also shared this with him: https://knowledge.digicert.com/solution/SO26449.html#:~:text=out%20certificatename.der-,Convert%20DER%20to%20PEM,-openssl%20x509%20%2Dinform

**Comment by jbritt1** [comment]
> Igor sent it to me on va Teams, and I also exported from the VA network using Edge.
> 
> Shall I PR into https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/roles/trusted-certs/files ?

Yes please!

**Comment by jbritt1** [comment]
Oh dang, just realized we already have this one here: https://github.com/department-of-veterans-affairs/platform-va-ca-certificate

**Comment by jbritt1** [comment]
Deepest apologies Kevin! Been a long week...

**Comment by RudyOnRails** [comment]
> No worries at all and please do not apologize

**Comment by RudyOnRails** [comment]
I have so many (technical, devops) questions, but it's late, so let's pick back up tomorrow and know it's going to be a great friday sir.

**Comment by jbritt1** [comment]
> I have so many (technical, devops) questions, but it's late, so let's pick back up tomorrow and know it's going to be a great friday sir.

Sounds good, give me a ping in the morning when you are up and rolling and let's try to sort out what we can.

**Comment by jbritt1** [comment]
Gosh, they were right. I am deeply sorry. I manually added it to a machine and tried the curl again in which I now get a 403 (likely due to needing more credentials passed) and no longer see the SSL certificate issue. 

Deeply apologize that I was so off the mark. We haven't used that `*ICA4*` cert in the two years I have been here so I honestly just did not think it could be part of the equation...

**Comment by RudyOnRails** [comment]
No worries at all @jbritt1. Happens to the best of us. I know your team is often under pressure from different angles so it's absolutely understandable. Hope you can R&R a little bit tonight or soon enough.

I am going to start on the staging-fwdproxy & staging settings PR and some other PR's to turn SSL back on in preparation for UAT tomorrow.

**Comment by jbritt1** [comment]
Yep, that was it... I merged the pull request above, built a new AMI for forward proxy and deployed to staging and the result of the curl now gives:

```[root@ip-10-247-35-70 ~]# curl -vvv https://stage.vapi.va.gov
* Rebuilt URL to: https://stage.vapi.va.gov/
*   Trying 15.200.118.105...
* TCP_NODELAY set
* Connected to stage.vapi.va.gov (15.200.118.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Next protocol (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=DC; L=Washington; O=Veterans Affairs; CN=stage.vapi.va.gov; emailAddress=satish.mamindla@va.gov
*  start date: May 17 11:18:00 2021 GMT
*  expire date: Jun 10 11:18:00 2022 GMT
*  subjectAltName: host "stage.vapi.va.gov" matched cert's "stage.vapi.va.gov"
*  issuer: DC=gov; DC=va; CN=VA-Internal-S2-ICA4
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: stage.vapi.va.gov
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Fri, 18 Feb 2022 01:32:11 GMT
< Content-Type: text/html
< Content-Length: 118
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubdomains;
<
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
* Connection #0 to host stage.vapi.va.gov left intact

**Comment by RudyOnRails** [comment]
@jbritt1 as always, thank you so much for you honesty and hard work. Closing this issue OUT!

**Comment by RudyOnRails** [comment]
I also have a request in for the Mulesoft team to make us a health_check endpoint.

**Comment by RudyOnRails** [comment]
Thanks for doing that, will ✅  it off the list!
