### ISSUE TITLE
Move Platform Support Documentation to SRE Team.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36547]
## Description
Currently the Platform Support Documentation is on the Platform Team How to and we need to move the https://vfs.atlassian.net/wiki/spaces/AP/pages/1466826783/Platform+support+in+Slack to the Platform SRE team area.

Also these should be reviewed and updated if needed:  https://vfs.atlassian.net/wiki/spaces/SUP/overview?homepageId=973897997
and verify this:
https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html

## Background/context 
The Platform SRE team is new and some tasks/documentation are now going to be handled by it instead of other teams.

## Tasks
- [x] Determine where the documentation should be moved
- [ ] Detemine what needs to be updated 
- [ ] Move the documentation to the new area - https://vfs.atlassian.net/wiki/spaces/AP/pages/1466826783/Platform+support+in+Slack

## Acceptance Criteria 
- [ ] Document for VFS Platform support is moved and managed by the SRE team.
