### ISSUE TITLE
Implement design iteration for multiple VAMC health service locations

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36566]
## Issue Description
VA health and non-clinical services may be offered at more than one location for a given health system. Service locations can use the same address as the main facility, another location on the campus or an offsite location. 

## Problems to be solved by this design iteration
Separate locations should be visually distinct without relying on additional data from the field
Location name and address already present on the screen should not be duplicated
Heading level hierarchy should be maintained (although can be overridden for visual styles, if needed)

## Current behavior
Style appears to be overriding the heading level
`<h4 class="force-small-header" data-template="paragraphs/service_location">Hours</h4> `

Layout: 
```
<!--
  layout: health_care_local_facility.drupal.liquid
  path: pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive
  entityId: 84
-->
```
## This work will be done in a series of issues
1. Maintaining heading level and style #36933
2. Discovery for multiple locations #36934
3. This issue: Implementation of design for multiple locations 

## Example

This example was crated in Tugboat for Columbia County VA Clinic Laboratory and pathology. I've created three locations for this service:

1. Location A does not use facility address, is at 301 West Third Street, and is named Alley Medical Center. Hours are specified and the facility phone should be used. 
2. Location B uses facility address + Suite 123. Should use facility hours and phone. 
3. Location C does not use facility address, is at 123 Main Street, and is unnamed. No hours are specified and a new phone number with an Appointments label has been defined. 

<details>
<summary> Example locations created in Tugboat </summary>

![image](https://user-images.githubusercontent.com/55411834/153051271-c5e19e55-461a-41b3-94cd-1b2a322a9d6d.png)

![image](https://user-images.githubusercontent.com/55411834/153051358-881ab732-1dc2-419d-9bd6-e8c56918c7c7.png)

![image](https://user-images.githubusercontent.com/55411834/153051421-13dc0efe-0e62-4626-8b1f-47b0f3ed5799.png)

</details>

<details>
<summary>Expected behavior for this example </summary>

### Contact information (H4)
This service is offered at multiple locations

_Location B is listed 1st because it uses facility address - no name is supplied because it uses the facility address and should not be duplicated_

Suite 123 

#### Hours (H5)
Hours as defined

#### Phone (H5)
facility phone

### Alley Medical Center  (H4) 
_Location A is listed 2nd because it does not use facility address but is named_

301 West Third Street address

#### Hours (H5)
Hours as defined

#### Phone (H5)
facility phone

### Service location 1 (H4) 
_Location C is listed 3rd because it does not use facility address and is unnamed_

123 Main Street address

#### Phone (H5)
phone as defined with "Appointments" label
</details>

---
## Tasks
Reference Nick's [UX Pin design](https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/147451739/documentation/no-panels?mode=i)
**Ensure the following heading levels for location and contact information within a health service accordion**
- [ ] "Contact information" is always H4
- [ ] Facility names, either automatically generated, or manually provided in Drupal, are always H4 
- [ ] "Hours" is always H5, even if no name is provided
- [ ] "Phone" is always H5
(3)
---

Discovery (2/3)

- Is everything already in graphql?
- What parameters/variables are needed/missing?
- Identify whether or not the location uses facility street address

---

Implementation (blocked by discovery)
**New features for use when multiple locations are available within a service**
- [ ] add "This service is offered at multiple locations" under Contact information heading
- [ ] add a new H4 heading "Additional service locations" to be used when location does not use facility street address and is unnamed 
- [ ] add new "Service location + incrementing number" label for unnamed service locations which do not use facility address (increments for each facility where "Use the facility's street address" is ​not​ checked, ​and​ no name is provided)
- [ ] Implement Multiple location list order logic as follows
> Contact information heading
> "This service is offered at multiple locations" 
> Locations using facility address appear first
> Named locations not using facility address appear next
> "Additional service locations"
> Unnamed locations not using the facility address (using the new "Service location + incrementing number" label) appear last

## Acceptance Criteria
- [ ] "Contact information" is always H4
- [ ] "Hours" is always H5, even if no name is provided
- [ ] "Phone" is always H5
- [ ] Facility names, either automatically generated, or manually provided in Drupal, are always H4 
- [ ] New context "This service is offered at multiple locations" is included when more than one service location is displayed. 
- [ ] Service locations using the facility address appear first in a list of multiple locations
- [ ] Named service locations not using the facility address follow locations which use the facility address
- [ ] Unnamed locations appear under  "Additional service locations" "Service location" + incrementing number

**Comment by davidmpickett** [comment]
Closing as not planned. Any updates to the FE will be based on a new design for multiple Service Locations. A new implementation ticket can be created based on that design https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10687
