### ISSUE TITLE
Submit Typeahead to Design System

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#36574]
## Issue Description
Typeahead was submitted and approved to be featured on the [Design System ](https://design.va.gov/)

---
## Tasks
- [x] _Complete ticket with evidence that it meets the needs of users_ [#637](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/637)
- [x] _Present Typeahead to Design System Council on 2/4/2022_

## Acceptance Criteria
- [x] _Typeahead was submitted and approved and will be featured on the Design System_
