### ISSUE TITLE
Research and Document the impact of all the planned Changes by Ops K8, Secrets Management, etc.. For 1st and 2nd Qtr 2022

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36579]
## Description
The SRE team needs to understand all the impacts of changes being made to move to K8, Secrets Management, and any Ops changes that could affect the reliability and availability of systems/apps.  This will be limited to Ops changes planned for the 1st and 2nd qtr 2022

## Background/context 
There is a migration in places for some of the Ops Services and we need to make sure we plan for support requests related to these changes.  These items are in the POC phase so we will limit this to the changes in the first and second quarter of 2022

## Tasks
- [ ] Identify the All the changes planned by Ops for K8 transition.
- [ ] Identify any other Ops changes that could impact service and cause a support requests.

## Acceptance Criteria 
- [ ] Document with the list of Ops services being changed, with before and future goal state.
- [ ] Document support requests response playbooks for the Ops changes

**Comment by little-oddball** [comment]
Determined OBE being in the 1st quarter 2023
