### ISSUE TITLE
Update keepalive on FE

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#36575]
## Issue Description
In reference to [Zenhub ticket #36565](https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/36565) eAuth/IAM is requesting that the `authncontextclassref` headers not be used for Login.gov like it was for ID.me.  Instead IAM is passing along additional headers that we can pass to the backend.

---
## Tasks
- [ ] Update the `keepAliveSSO` file to ensure the updated `authn` is passed when /keepalive is called
- [ ] Update unit tests to ensure proper testing of new functionality

## Acceptance Criteria
- [ ] No impact with signing into VA.gov with Login.gov works (Outbound)
- [ ] Signing in on AccessVA (VHIC) with a Login.gov credential and navigating to Dev.VA.gov works (Inbound)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
