### ISSUE TITLE
Create new housing COE static page: Check COE status

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#36571]
## Issue Description
When we launch the housing COE application, we'll need to create a new unauthenticated page for checking your COE status. This is a new static page supporting the authenticated tool to check the status and download a COE.
This page is only displayed for unauthenticated users.

See IA recommendations for more context: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

---
## Tasks
- [x] Create new tier 1 page based on the screen called "Check COE Status Landing Page in https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap

## Acceptance Criteria
- [x] New page created in drupal CMS
- [ ] New page goes live with launch of COE application
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lunascoop** [comment]
@psanders86 I completed the draft content for this page. I'd like to set aside some time to discuss this page, and possible updates to related pages, with you and @RLHecht.

[Check the status of your VA home loan COE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8088865/Check.the.status.of.your.VA.home.loan.COE.docx)

**Comment by psanders86** [comment]
Hello @lunascoop please review my edits to this content block. Thanks!

[https://app.zenhub.com/files/133843125/ee2ebe58-4652-4569-bd59-ea2183f36394/download](https://app.zenhub.com/files/133843125/ee2ebe58-4652-4569-bd59-ea2183f36394/download)

**Comment by psanders86** [comment]
Hello @RLHecht this is ready for a copy edit. Please get rid of the track changes before you send it on the next step. Thanks! 

[https://app.zenhub.com/files/133843125/f4527906-2c73-4c9a-a99b-08ea7f7ffe73/download](https://app.zenhub.com/files/133843125/f4527906-2c73-4c9a-a99b-08ea7f7ffe73/download)

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the drupal preview page for this. 

preview-prod.vfs.va.gov/preview?nodeId=44020

And here's the text for the react widget that would need to be placed below the intro for sign-in. The text for that is the following:

H2: Please sign in to download or check the status of your COE
Sign in with your existing **ID.me,** **DS Logon,** or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **ID.me** account now.

[Sign in or create an account]

**Comment by RLHecht** [comment]
@bethpottsVADEPO I reviewed your changes and all looks good. I just need to add in the react widget once it's created.

**Comment by RLHecht** [comment]
@bethpottsVADEPO The react widget is now also on the page and ready to go: preview-prod.vfs.va.gov/preview?nodeId=44020
