### ISSUE TITLE
Notice of Disagreement - Frontend Text Modification

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36589]
## Issue Description
Stakeholder request to alter frontend text.

---
## Tasks
- [ ] Change "date of decision" to "date of notification of the decision"

## Acceptance Criteria
- [ ] Change text on impacted screens.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
