### ISSUE TITLE
NOD: Fix linting issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36584]
## Description

Some JS lint rules have been enabled & most need to be addressed

## Tasks

- [ ] Fix lint warnings in the Notice of Disagreement form
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
