### ISSUE TITLE
Dashboard Queries - Retroactively Exclude Opted-out User Data

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36585]
## Issue Description
We should update our KPI dashboard queries (and others?) to retro-actively excluded opted-out user data so their data from before and after they opted out is not included in metrics.

---
## Tasks
- [ ] Update queries to retroactively exclude opted-out user data.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bsmartin-ep** [comment]
I did create a PR in the `vagov-content` to try to address this. It pushes in an additional opt-out **without the user dimension** so that is recorded in our Views before all traffic is excluded.

https://github.com/department-of-veterans-affairs/vagov-content/pull/825

You should be able to create a user ID table of users with this event:

```js
recordEvent({ event: 'analytics-opt-out');
```

..and filter all their activity.

Michelle - I would work with the Content team to get this tested and deployed.

cc @obrienjulie @michelle-dooley
