### ISSUE TITLE
Add feature request info to Platform Orientation materials

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#36594]
## User Story
As a new VFS team member, I want to be made aware of the "Platform feature request" so that I can submit a feature request for improvements/ideas for the VA.gov Platform.

---

## Description
The Service Design team launched a new process recently for VFS teams to submit feature requests to Platform. This means that if a VFS team member has an idea for how Platform could improve an existing process, reduce time to complete a task, or has an idea for a new product altogether, they now have the option to let Platform know easily. The Service Design team launched the [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html) page on Platform Website and have asked that Governance team integrate it into the Platform Orientation Materials.

---

## Artifacts
[Platform Orientation gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)
[General Orientation slide deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.gf08689d579_0_71)

---
## Tasks
- [x] Add a checklist item to the Platform Orientation template under General for the reviewing the Submitting a Feature Request page
- [x] Add a slide to the General Orientation slide deck (work with Shira) communicating to VFS teams that they have the opportunity to submit feature requests to Platform team.

## Acceptance Criteria
- [x] Platform Orientation gh template has been updated per the criteria specified above
- [x] General Orientation slide deck has been updated to reference the feature request
- [x] Updates have been Peer Reviewed by Governance Team member or OCTO (guidance to be created)

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ticket Type is labeled** ('tech-debt', 'collaboration-cycle')
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)

**Comment by shiragoodman** [comment]
@allison0034 is there a PR for the updated GH template?

**Comment by allison0034** [comment]
@shiragoodman yes, it is under "Linked pull requests" on the right. How do you want to go about making the slide?

**Comment by shiragoodman** [comment]
@allison0034 [here](https://drive.google.com/drive/folders/1F0dPvQk1UKqOZl0BgZmtbsQaU5GB1sC9) is where the General Orientation deck is saved. Could you create a copy (for review purposes only) and add a slide under the Communication norms and escalation paths section... maybe after slide 26? I almost edited this deck last week, but I couldn't figure out how I wanted to communicate to VFS teams that Platform has this option. If you could get it started and put your thoughts down, that might help me a bit.

**Comment by shiragoodman** [comment]
@allison0034 I added one additional line, but looks good. Thanks! You can copy the slide into the original deck now. :)
