### ISSUE TITLE
[FE] Pre-Check-in and Check-in Editing Feature Flip 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36599]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- (%FILL IN%)
- (%FILL IN%)

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

This ticket to create the feature flip for editing capabilities in both Pre-Check-in and Check-in experiences. 

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Add both flips to vets-api
- [x] Add both flips to the FE
- [x] Add both flips to mock API 
- [x] Create or update unit tests
- [x] Update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] Feature flips for both Check-in and Pre-Check-in are in prod and set to FALSE
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
FE peer review confirmed this can be closed.
