### ISSUE TITLE
Build technical flow chart diagram for debt portal & fsr service connections

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#36597]
## Issue Description
To better understand and communicate the technical part of what services are used for what and how they're connected we should generate a flowchart diagram displaying these details.

---
## Tasks
- [ ] Build flow chart to demonstrate request and response values and how services are connected

## Acceptance Criteria
- [ ] We have a chart to help understand our external services and how the data flows through them.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
