### ISSUE TITLE
[SPIKE] Engineering Architecture Design - authentication

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#36602]
## Description
Create an Engineering Architecture Document around the authentication requirements for the Pre-Check-In demographics editing so that we can begin to identify and create the engineering stories necessary to implement the requirements of the feature.

## Tasks
- [x] Create an MD(readme) file in the [va-gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/architecture-docs) repo
- [x] Create general sections in the document for `Table of contents`, `Slack channels`, `Team members` etc.
- [ ] Create engineering sections for UX, Vets-website and Vets-API to explore the demographics edit authentication requirements.

## Acceptance Criteria
- [ ] An Architecture Document outlining the specific solutions needed for authentication during the Pre-Check-In demographics editing workflow is created.
- [ ] Stories are written against relevant epics in the backlog for the frontend(UI) and backend(vets-api) development teams.

**Comment by julieadair1** [comment]
## Description
We need to set up the meeting in order to achieve:
1. Engineering Design Doc
2. Engineering Stories
