### ISSUE TITLE
[FE] [SPIKE] Demographics editing navigation and routing discovery

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#36606]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

As a veteran, I want to easily go to a screen where I may edit my demographics information and then seamlessly return to the same place in the application flow, so that I may keep my demographics information up to date.

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/56D56797-C485-4B53-95E7-36EBF66B6698/canvas)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

The scope of this ticket is to discover and document the best method to provide a flexible and reusable component to take the veteran to the demographics editing page and then return them to their original workflow. Additionally, the routing method for showing the demographics editing page should be defined and documented.
 
## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update relevant documentation:
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

- [ ] technical approach has been agreed on, prototyped if necessary, and documented
- [ ] documentation has been linked on any editing implementation tickets
- [ ] documentation has been linked from https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in/edit_demographics.md

**Comment by sarahknoppA6** [comment]
@mdewey could you update when you return?
