### ISSUE TITLE
[Combined debt portal] UI updates to the VBA Debt designs to align with MCP

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#36600]
## Issue Description
As we move closer towards combining the VBA debt portal with MCP, we need to make sure both experiences follow the same UI patterns.

---
## Tasks
- [x] Review the VBA debt portal and identify discrepancies between it and MCP
- [x] Create an updated UXPin for the VBA debt overview + details pages as necessary

## Acceptance Criteria
- [x] The designs have been updated and linked in this ticket

**Comment by rileyorr** [comment]
The updated UI can be found [here](https://preview.uxpin.com/53bf4de7cd95501214aafee8c7c7a0a6052c53c7?_gl=1*1f25v79*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/147814779/simulate/sitemap?mode=i)! These designs will be utilized in the combined portal prototype once we have a finalized path forward with Mikki's IA feedback.
