### ISSUE TITLE
[Research] Create online survey - Veteran Top Tasks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36617]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will help identify what Veteran top tasks are for use in future user research and product design on VA.gov. 

### Considerations
- The upcoming homepage redesign effort might change if/how top tasks are represented on the home page
- This should be focused on Top Tasks only 
- 
##  Tasks 
- [x] Get license for Optimal Workshop
- [x] Create online card sort w/list of top tasks
- [x] Test card sort 
- [x] Share card sort with other UX team members, PM, PO, and incorporate their feedback 

## Acceptance Criteria 
- [x] Online cord sort has been created and prepared for research 
- [ ] Share with PM/PO for review 
- [x] Card sort available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
Created survey in Optimal Workshop. Preview it here: https://p3y41d84.optimalworkshop.com/questions/pnrzx6eu

**Comment by cindymerrill** [comment]
Made a few wording changes to survey and launched it in preparation for pilot testing this week.

**Comment by cindymerrill** [comment]
Revised survey after pilot #1 and then again after pilot #2 so now ready for moderated research sessions. Planning another revision after the moderated research and before the unmoderated research.

**Comment by cindymerrill** [comment]
Survey revised per moderated research findings and all ready to be launched with unmoderated research study.
