### ISSUE TITLE
[Research] Compile list of tasks for card sort -Veteran Top Tasks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36618]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will help identify what Veteran top tasks are for use in future user research and product design on VA.gov. 

### Considerations
- Connected card sort ticket #36617 

##  Tasks 
- [ ] (List tasks here @cindymerrill) 

## Acceptance Criteria 
- [ ] Compiled list is completed and card sort is ready for research actions 
- [ ] Share with PM/PO for review

**Comment by cindymerrill** [comment]
Started going through the long list of tasks

**Comment by cindymerrill** [comment]
Analyzed all Veteran tasks in list and synthesized into a shorter list. Pinged a few people for clarification on some of them. Plan to share with Mikki for feedback tomorrow.

**Comment by cindymerrill** [comment]
Shared my draft task list with Mikki Northuis for feedback. Currently have 43 tasks, which I'd ideally like to get down to 30 tasks for the card sort to decrease the cognitive load (per advice from Platform [here](https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html)).

**Comment by cindymerrill** [comment]
Mikki's not going to have time to review the list until next week, so I'm going to share it out for review with @brianalloyd before posting it on slack.

**Comment by cindymerrill** [comment]
Mikki gave me a lot of feedback, which I incorporated. Revised list can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/Veteran-tasks-Feb17-EOD.xlsx

I may make more changes tomorrow. Shawna Hein and Meg Peters also review the tasks.

**Comment by cindymerrill** [comment]
Revised top tasks list based on feedback from Shawna and Mikki. Hoping to talk with Mikki about her feedback and ideas for prioritizing which tasks to put into the card sort.

Tomorrow I have a meeting scheduled with Meg Peters and Tracey Mulrooney (who works with Meg) to talk about the top tasks.

**Comment by cindymerrill** [comment]
Because this project was de-prioritized, I cancelled my meeting today with Meg Peters and Tracey Mulrooney, but I'm going to go ahead meeting with Mikki tomorrow to discuss her feedback on my task list so I'll be in better shape to pick up the project later if there's time.

**Comment by cindymerrill** [comment]
Today shared [revised task list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/Task%20List%20for%20Veteran%20Top%20Task%20Research.xlsx) per work with @mmiddaugh yesterday with Mikki, Meg, Tracey Mulrooney, Danielle, Beth, and Shawna. Requested feedback by this Friday (May 6) if possible.

**Comment by cindymerrill** [comment]
Revised task list with feedback received so far and reshared it again for input: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/Task%20List%20for%20Veteran%20Top%20Task%20Research.xlsx

Still need to drop 1 task in order to comply with the limit of 40 cards in our Optimal Workshop license.

**Comment by cindymerrill** [comment]
Updated task list with feedback, and reposted on github and in group DM chat: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/Task%20List%20for%20Veteran%20Top%20Task%20Research.xlsx

**Comment by cindymerrill** [comment]
The plan now is for tasks to be presented in an online survey instead of a card sort because the cognitive load for participants would be a lot lower.

**Comment by cindymerrill** [comment]
Also shared with Dave Conlon for feedback. FYI @mmiddaugh
