### ISSUE TITLE
 Add COE Reference Number to Introduction and Status Pages

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36627]
## Background
The backend will pass a reference number to the frontend where it needs to reside on a few select pages: Introduction and Status pages.

## Considerations
- Jim's recent ticket on these locations is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36022) and in the [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36022#issuecomment-1032928314)
- BE's PR: https://github.com/department-of-veterans-affairs/vets-api/pull/9168

## Tasks
- [x] Implement the reference number the above locations
- [x] Test the presence of these numbers on the frontend
- [x] Hook this up to the Redux store

## Acceptance Criteria
- [x] The reference number is now located in the appropriate places.
- [x] A PR has been requested for merging, if applicable

**Comment by jason-gcio** [comment]
Q: On Confirmation page, how do we get the reference number back?
A: it should be in the backend
Amanda: I am passing in the created date and status
Jerek: we need a way to get it passed to us
Amanda + Kathleen we need to make a ticket to do this

**Comment by kathleencrawford** [comment]
I double checked and when we submit an application to LGY, they are not returning a reference number in the response.  @jerekshoe @jason-gcio

**Comment by jason-gcio** [comment]
The reference number is coming back from the eligibility request and is based on the status AND the Veteran....meaning that new applications get the same ref number

**Comment by jason-gcio** [comment]
Kathleen posed the idea that if that were the case, then it could simply be sent to us instead of us digging for it
