### ISSUE TITLE
Correct `DENIED` Status Results

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36629]
## Background
It seems as though the incorrect status is being returned when a Veteran has submitted and has been denied.

## Considerations
It should look like this:
![image.png](https://images.zenhubusercontent.com/5d4d9fbb3dcb5944ddb12282/a73c92df-4cc2-41fe-803e-11c7de1268ee)

## Tasks
- [x] Adjust the status results to the correct error notifications
- [x] Confirmed screens and statuses with FE

## Acceptance Criteria
- [x] The correct notification appears when an applicant is denied.
- [x] A PR has been requested for merging, if applicable

**Comment by jason-gcio** [comment]
this may be covered in #36127

**Comment by alsleaders** [comment]
Closing because [PR for](https://github.com/department-of-veterans-affairs/vets-api/pull/9125) #36127 has been merged
