### ISSUE TITLE
Set Up Feature Toggle (A/B Test Rated Disabilities)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36621]
## Background
One of the functions within Rated Disabilities is the display of individual ratings and this part of the total combined disability ratings can be confusing around which of these contributes to the TCDR.  We would like to test the efficacy of 

## Considerations
- We want to see if there is any interest in changing how the data is displayed today: however it is stored in CorpDB **vs** sorted by percentage in descending order (largest individual rating on top)
- Is it worth it to ask the Veteran once the sort has occurred: "Was this helpful?"

## Tasks
- [ ] Implement a feature toggle within Rated Disabilities
- [ ] ...

## Acceptance Criteria
- [x] A feature toggle has been established on RD
- [x] A PR has been requested for merging
