### ISSUE TITLE
Add COE Reference Number to `v0/coe/status` Payload

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36626]
## Background
When the backend gets the COE reference number back in its response, it should be passed to the frontend, for future display to the Veteran.

## Considerations
- This was referenced recently in Jim's ticket to add these reference numbers

## Tasks
- [x] Add reference number to the status being sent to the front end 
- [x] Update specs accordingly

## Acceptance Criteria
- [x] A PR has been requested for merging, if applicable

NOTE: this was a duplicate of 36625

**Comment by alsleaders** [comment]
I'm closing this because the PR was merged.
