### ISSUE TITLE
Implement Code to be Tested (A/B Test Rated Disabilities)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36622]
## Background
When the new feature to be tested is presented to the Veteran, we need to have the data displayed in a different way to see if its better: that's this part.

## Considerations
- sort by descending % - largest individual rating on top

## Tasks
- [ ] Implement sorting around the data on this feature to be sorted in descending order so that the largest percentage is at the top.
- [ ] ...

## Acceptance Criteria
- [ ] There is a version of this feature that includes some sorting functions.
- [ ] A PR has been requested for merging, if applicable
