### ISSUE TITLE
[VET] VET - CENTER - RAMP UP - Review and prep [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36630]
## Resources
[Vet Center Run Book](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B3DC2EBB5-0A7C-4FA9-BE30-7DF11C055845%7D&file=Vet%20Center%20Content%20Workbook%20December%202021%20(1).docx&action=default&mobileredirect=true)

## Task
- [x]  Review run book and attend office hours
- [x]  Review sites listing (complete, in progress, kick off schedule, not started)
- [x]  Set up schedule to transfer workload over to team

## Acceptance Criteria
- [x] Team has reviewed and asked questions regarding the product and run book
