### ISSUE TITLE
[Content-Review-Cross Check] Review VET Center Run book content and Proof read & provide recommendations for correct plain language and design style guide [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36632]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my VET center web applications and tools, so I can use the VET center web pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing and review

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_

## Resources - Tools - Documentation
[VET Center Run Book](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7BDF055241-0796-4F2B-ABA3-FDF6EB97497D%7D&file=Vet%20Center%20Content%20Workbook_Draft_For_Review.docx&action=default&mobileredirect=true)

## Tasks
- [ ] Read through VET Center run book with track changes
- [ ] Review changes and accept good input
- [ ] Compose content with input from track changes for final draft.

## Acceptance Criteria
* Fully reviewed document is saved to Content folder in VAMC content files.
