### ISSUE TITLE
Null Benefit Claim ID Feature Toggle

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36631]
## Background
We are going to  setup a feature toggle around this work so that we can control who it impacts initially.

## Considerations
- This going to use Flipper?
- Refer to #34463

## Tasks
- [ ] Add the feature toggle on the job that would ask the submission to check for codes
- [ ] TBD

## Acceptance Criteria
- [ ] There is a functioning feature toggle in place
- [ ] A PR has been requested for merging, if applicable

**Comment by tblackwe** [comment]
closing this, we are woking on null claims in several other tickets
