### ISSUE TITLE
[VAMC] Menu clean up Part 3 - Inform Editors of Menu Parent item corrections, and submit changes  [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36646]
## STORY
As a Veteran I need to have a simple and standardized location for all VAMC web pages, so I can quickly find and locate my VAMC information.

## RESOURCES
[Documented issues with Parents]

## TASKS
- [x] Communicate with PAO/Stakeholders of menu changes 
- [x] Update VHA DM of menu changes and upcoming redirects
- [ ] Wait for submission of redirects for all appropriate pages.
- [ ] Update pages and test links to make sure all links are working correctly.

## ACCEPTANCE CRITERIA
- [ ] Artifact document for original and new URL locations of menu items that need to be moved.

**Comment by SgardnerPMP** [comment]
Moved information to Sprint 68
