### ISSUE TITLE
[VAMC] Menu Maintenance Part 2 to move all Level 5 & 6 Menu items to Level 4 (Working with Editors/PAOs) [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36645]
## STORY
As a Veteran I need all web pages to be easily searchable on the left Nav, so I do not have to click through more than four depths to find the page I need.

## RESOURCES
TBD

## TASKS
- [ ] Work with IA to submit redirect URLs
- [ ] Once redirects are in place move all of the menu items to correct 4th level.

## Acceptance Criteria
- [ ] Communications are sent out to effected stakeholders
- [ ] Document final URLs for archive.
