### ISSUE TITLE
[SPIKE] Engineering Architecture Design - Handling Edit Data Submission

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#36650]
## Description
Create an Engineering Architecture Document around handling updated demographics information requirements for the Pre-Check-In workflow so that we can begin to identify and create the engineering stories necessary to implement the feature.(Vets-website and Vets-API)

## Tasks
- [x] Create an MD(readme) file in the [va-gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/architecture-docs) repo
- [x] Create general sections in the document for `Table of contents`, `Slack channels`, `Team members` etc.
- [ ] Create engineering sections for UX, Vets-website and Vets-API to explore handling demographics updates for Vets-website and Vets-API.

## Acceptance Criteria
- [ ] An Architecture Document outlining the specific solutions needed for handling updated demographics during the Pre-Check-In demographics editing workflow is created.
- [ ] Stories are written against relevant epics in the backlog for the frontend(UI) and backend(vets-api) development teams.

**Comment by dillo** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/demographics_edit_data_flow.md
