### ISSUE TITLE
Pre-need: Replace `AdditionalInfo` with `va-additional-info`

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36659]
## Description

The pre-need form still includes the deprecated `AdditionalInfo` component. It needs to be updated to use the `va-additional-info` web component.

## Tasks

- [ ] Replace `AdditionalInfo` with `va-additional-info`
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
