### ISSUE TITLE
[Design] Auth Profile - Personal Info Revision - Finish all design updates

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36653]
## Background

Finish all outstanding design mockup changes (pending dependency on our partners).

## Tasks
- [x] Update interaction design for text box input ("A [field] not listed here" options
- [x]  Post link in a comment and tag Marci, Samara and Adam when complete

## Acceptance Criteria
- [x] Update interaction design for text box input ("A [field] not listed here" options
- [x] Post link in a comment and tag Marci, Samara and Adam when complete

**Comment by MarciMcGuireGCIO** [comment]
Hi @cgednalske ! I saw this ticket that Samara created for FE, and figured the same changes should be done to the mock-ups.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/36078

**Comment by cgednalske** [comment]
Link to updated [Personal information Sketch files](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
