### ISSUE TITLE
[FE] - Auth Profile - Personal Info Revision -  Update UI to reflect remaining UI/UX changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36655]
## Background

There have been some changes since the Personal Info page initial design was deployed to Staging.  Once Christina finalizes the mockups, the UI will need to be updated so that it mirrors the changes shown in the mockups.

## Tasks
- [ ] Update UI to match the functionality shown in the completed mockups linked in #36653
- [ ] Drop a comment and @ Marci and Christina when ready for validation on Staging

## Acceptance Criteria
- [ ] Update UI to match the functionality shown in the completed mockups
- [ ] Drop a comment and @ Marci and Christina when ready for validation on Staging

**Comment by MarciMcGuireGCIO** [comment]
Consolidating these UI tasks with finalizing copy changes
