### ISSUE TITLE
[Design] - Auth Profile - Bad Address Indicator - Start Design Discovery

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36654]
## Background
See [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator) for overview.  

This task is to understand the problem/background, formulate questions and get those questions answered.  Some questions to start with:
- When someone is on VA.gov, when can we detect that they have a bad address?
- Can we proactively email all people who have the bad address indicator to log into VA.gov and update their address? How would this work?
   
## Tasks
- [x] Understand the problem/background
- [x]  Figure out what questions you have. 
- [x] Get those questions answered
- [x] Document in the project folder
- [x] Link to document in comment and tag Marci & Samara for feedback

## Acceptance Criteria
- [x] Understand the problem/background
- [x]  Figure out what questions you have. 
- [x] Get those questions answered
- [x] Document in the project folder
- [x] Link to document in comment and tag Marci & Samara for feedback

**Comment by cgednalske** [comment]
Link to Bad Address Indicator [discovery documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/discovery/documentation.md)

**Comment by MarciMcGuireGCIO** [comment]
Thanks @cgednalske; looks great!!
