### ISSUE TITLE
EHRM (Cerner) Statement Integration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#36663]
## Description
Integrate EHRM (Cerner) Statements 

## High Level User Story/ies
As a Veteran I want to receive copay statements from EHRM in the medical copay portal. 

## Definition of done

- [ ] EHRM Statements are available in the medical copay experience on va.gov

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
