### ISSUE TITLE
[Research] Prep Tasks  -Veteran Top Tasks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36676]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will help identify what Veteran top tasks are for use in future user research and product design on VA.gov. 

##  Tasks 
- [x] Share research plan and conversation guide with Shane for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots 
- [x] Send thank you notes to pilot participants
- [x] Revise conversation guide
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [x] Other tasks as needed 

## Acceptance Criteria 
- [ ] Completed prep tasks in support of research actions

**Comment by cindymerrill** [comment]
Found and scheduled a pilot participant for Wed, did prep tasks so now all ready for pilot test.

FYI @michelle as standup updates

**Comment by cindymerrill** [comment]
Conducted first pilot and debriefed with @mmiddaugh. Then made changes to survey and conversation guide so ready for the second pilot tomorrow.

**Comment by cindymerrill** [comment]
All set for research to begin.
