### ISSUE TITLE
Resolved/Referred Copay Debt

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#36677]
## Issue Description
When a debt is resolved (paid off or closed), it currently will not reflect in the Debt Portal UI because the data has not been available from the DMC. We believe this data may exist - potentially in the CDW.  

## Acceptance Criteria
- [ ] When a Veteran has resolved their copay debt or that debt has been referred to treasury they are able to review the status on VA.gov through the Medical Copay Portal

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per conversation with @denisecoveyduc and @Tom-Davis, closing this epic and will use "Payment History" epic #18859 moving history
