### ISSUE TITLE
[Research] My VA - Payment Info: Submit Research plan and Conversation guide for review & approval (NEW PROCESS)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36679]
## Background
Now that designs, development and QA is complete, we are ready to begin UAT on our new functionality.  
The UAT Research plan and Conversation guide are ready for review and approval.

**PLEASE NOTE**: There is a NEW process for research reviews and approvals.
- Governance **[Research page](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-2.Researchreview)**
     - **[Adding research to Repo board for approvals](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines#how-to-add-new-research-for-approval-to-the-repo-board)** (expand details below for quick reference and checklist)

<Details>

**How to add new research for approval to the repo board.**
- [ ] Go to the **[repo board](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)**. If you need access to the repo board, slack [Shane Strassberg](https://dsva.slack.com/team/U01RMUH860G) with your github @handle.
- [ ] Create a **_note_** in the **Proposed** column by clicking the little plus button on the top right corner of the column. Add the title of your research.
- [ ] Convert the note to an **_issue_** by clicking the "more" three dots in the upper right corner of the card, then select convert to issue.
- [ ] Give your issue card a proper title.
- [ ] Add your Research folder link to the body of the issue card. Use this markdown language to create hyperlink: [Research Folder](your research folder URL) 
- [ ] Add brief summary of research to the body of the issue card.
- [ ] Click "Convert to issue" button.
- [ ] Click your new issue card to open it in the right side-nav, then _**assign yourself and other people**_ who will conduct the research. (This will help if another researcher has specific questions about your research.)
- Note: There is no need to add a milestone.
- [ ] Add up to 15 labels that describe what **_product_** it was for, who **_participated_** (Vets, caregivers, dependents), was it with a _**specific group**_ (PTSD, Blind/Visually impaired, etc), **_hardware, software,_** type of **_research method_**, design system **_components_** and/or **_patterns_**, and if applicable what specific part of the **_Veteran Journey._**
- [ ] Do a happy dance because you did it!

**How to get research approved to kickoff participant recruitment**
- [ ] Send slack message with link to issue to [Shane Strassberg](https://dsva.slack.com/team/U01RMUH860G) (if he’s not available, then slack [Kevin Hoffman](https://dsva.slack.com/team/UHZ9VNBH8))
- Shane or Kevin goes to research folder and reviews research plan and conversation guide.
- If needed, Shane or Kevin will leave feedback in **_bold italics_** as a comment on the issue card below your research summary.
- [ ] You make edits to research plan based on feedback.
- [ ] Slack Shane or Kevin (or email if not on Slack) that you made changes so they can approve.
- [ ] Once approved, move issue card to Current column on repo board.

**What to do when you complete your research.**
- [ ] Click and drag your issue card from **Current** to **Complete**.
- [ ] Click the "Go to issue for full details" button at the bottom of the right-side nav.
- [ ] Click the little three dots and then click edit in the top comment box.
- [ ] Copy/paste markdown code for **_key findings_** and **_details of findings_** from your research report under your original summary of the issue. (**Note**: You **_must click edit_** in your research report to be able to copy markdown code.)
- [ ] Click the green "Update comment" button so your findings are saved to the issue card.
- [ ] Add or remove any other labels up to 15. (This limit helps to make filtering cards easier)
- [ ] Feel pride in helping build the research repository for future VA.gov teams that will appreciate being able to quickly search and learn from your past work!

**Note**
Leave the issue **OPEN** since it has no affect to how we are using this tool.

</Details>

## Tasks
- [ ] Submit both Research Plan and Conversation Guide for review and approval (See Note and Details above)

## Acceptance Criteria
- A Conversation guide and Research plan are submitted for review and approval

**Comment by andaleliz** [comment]
I think this is a duplicate of #36690 - not sure if you want to close one in favor of the other?

**Comment by hdjustice** [comment]
That is really weird... i did not realize the duplication.. I will close this one.  Thank you @andaleliz !
