### ISSUE TITLE
[Debt Portal] Provide a way for Veterans to email DMC with technical concerns 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#36680]
## Issue Description
Currently, DMC receives calls from Veterans experiencing issues from the Debt Portal and are experiencing issues assisting them, tracking the issue, and forwarding the issues to our team when applicable. We're exploring implementing AVA, but in the meantime want to update the contact information to include an email address for technical concerns. 

---
## Tasks
- [ ] Reach out to Jill to determine when a Veteran should reach out to DMC; set up a call as needed 
- [ ] Review the Debt Portal's contact information + error messaging to determine areas that could benefit from adding DMC's email address
- [ ] Update designs 

## Acceptance Criteria
- [ ] Designs have been updated and linked in this ticket
- [ ] Designs have been sent to Jill for review

**Comment by rileyorr** [comment]
Updates:
- I added comments to both the [Debt Portal](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263496/comment/no-panels?mode=i) and [FSR](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701779/comment/no-panels?mode=i) prototypes where I think it may make sense to direct Veterans to DMC's operations mailbox
- I reached out to Jill + Nicole to set up a call so we can go over the potential areas and determine when we should direct Veterans to email vs call

**Comment by rileyorr** [comment]
Per our call with the DMC team a few weeks ago, our stakeholders are most comfortable displaying the DMC's email address in 404 alerts. 

@ScottyRJames if the Debt Portal, FSR, or Medical Copay Tool returns a 404, what does that look like on our end? I thought I'd heard those issues would be logged in Sentry. If that's true, does Sentry notify you in some way that there's an error (ex. email notification)? 

I'm asking because if we're already being notified, I'm wondering if we should suggest that Veterans should reach out to DMC if the issue persists rather than by default. 

Screenshot for reference ([Also added to the UXPin prototype](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/148632100/simulate/no-panels?mode=i)):  
![Screen Shot 2022-03-17 at 12.52.36 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/c5b301c0-da06-4357-b990-bbddc21de9a8)

**Comment by ScottyRJames** [comment]
@rileyorr Any code faults that happen within our API or even in downstream services that produce some kind of error code will be logged in Sentry. Sentry doesn't push notifications for any error to me right now but I do check a few times a few week to see if there's anything out of the ordinary occurring in our application. 

We have alerts setup within a slack channel to ping us if the amount of errors reach a certain threshold within a window of time but that's usually stemming from VBMS downtime.

**Comment by rileyorr** [comment]
Thank you @ScottyRJames - that's great info to know! 

I've sent the content over to Jill and also included some information about Sentry so she has more context about how error tracking works on our end.

**Comment by rileyorr** [comment]
I've incorporated Jill's feedback and opened the following tickets:
- [Frontend implementation](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/38754)
- [Follow-up design ticket to add back the sentence notifying Veterans that their letters may still be available for download](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/38755)
   - This ticket is blocked until letters sent after December 9th, 2021 are available within the portal
   - @denisecoveyduc this ticket should be attached to any development ticket(s) related to that issue; I'm unsure if any currently exist

**Comment by denisecoveyduc** [comment]
@rileyorr Added this to GH#38770 so we can track the progress and update when letters are available again.
