### ISSUE TITLE
Content Updates for SAHG

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36685]
## Considerations
draft cover, create ticket for content team

## Tasks
- [x] draft content for intro page
- [x] draft subway map steps
- [x] create a ticket for Sitewide Content team to review
- [x] review with Beth during office hours

## Acceptance Criteria
- [x] Wireframes have been updated
- [x] Content review ticket has been created

**Comment by candy-gcio** [comment]
Content ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36978

**Comment by candy-gcio** [comment]
Beth was out unexpectedly this week, but we have slacked about the content ticket and will meet as soon as she is available.
