### ISSUE TITLE
Implement Representative Punchlist Items

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36698]
## Considerations
[Punch List](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Search-Appoint-PunchList.md)

## Tasks
- [ ] Review list of punchlist items for rep (noted above) and 
- [ ] implement those changes 

## Acceptance Criteria
- [ ] Punch list items have been addressed
- [ ] A PR has been requested for merging, if applicable
