### ISSUE TITLE
[Research, FE] My VA - Payment Info: Conduct UAT sessions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36693]
## Background
We are now ready to begin UAT with participating Veterans.  These sessions will provide us with feedback on the design and development we have finalized.

## Tasks
- [x] Conduct UAT sessions with VA users, provided by Perigean
- [x] Confirm feature flip is on for each user before their session
- [x] Confirm feature flip is off for each user after their session
- [x] Consolidate notes for each session

## Acceptance Criteria
- UAT sessions are completed with all attending users
- Comprehensive research notes are captured for each session

**Comment by andaleliz** [comment]
Updating assignee; @aagosto90 feel free to revise the estimate if needed.

**Comment by aagosto90** [comment]
Concluded sessions on 4/15. On that day we had P10 not able to see the section and we weren't able to determine why, and then two no-shows, so we tested with two internal veterans on 4/18 and both were able to see the section as intended.
