### ISSUE TITLE
NOD: Make opt-in page visible with legacy appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36699]
## Description

The Notice of Disagreement opt-in page should be made optionally visible based on two things:
1) If any legacy appeals have been included when eligible issues are obtained from the API
2) If the Veteran adds any additional issues to the request

We can not cross-reference eligible issues or added issues with any of included legacy issues since only a description is provided, so visibility of the opt-in page is generalized.

## Tasks

- [ ] Wait for backend to include legacy issues with the eligible issue endpoint
- [ ] Optionally show the opt-in page as described above
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by vhenry07** [comment]
closing. this design has been changed.
