### ISSUE TITLE
[ENGINEERING] Review Drupal Assets and files, and test accounts and creation of pre-production pages [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#3671]
## User Story 
As a Drupal Engineer, I need to test and review the create of a new Pre-Production Drupal Web Site/Page , so I can repeat the website template creation process for each of the VISN 4 websites.

## Goal
_Review Repo, global files, images, media, and API assets, needed in create of Medical Center Drupal Site_

## Objectives or Key Results (OKR) this is meant to further
- _Determine Scalability of upgrade process_
- _Determine Blockers that can be overcome in future deployments_
- _Determine areas for efficiency improvements and added issues_ 

## Task 
_Steps that need to be complete in order to move to acceptance criteria-validate_
- [x] Document the location of files, images, media assets
- [x] Set up Detail pages required for Lebanon, PA (VISN 4 Stack)
- [x] Review and document Content types
- [x] Review banners, alerts, and priority pages/link set up
- [x] Create Menu required for Lebanon, PA
- [x] Document steps so this can be recreated for all future Systems (VISN 4)

## Acceptance Criteria
_Items that are required to meet acceptance_
* Working Menu following standard Template in proper order
* All "REQUIRED" Detail Pages have been created and confirmed (Does NOT require Content)
* Image location has been verified or created for This System
* Banners and Alerts are available for the Required pages
* Organizational status page has been created for System
