### ISSUE TITLE
[VRE] Improve 28-1900 Submission to CMP

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36744]
``` diff
- let's check in with them BEFORE deployment
```

## Background
VR&E is having a tough time matching some claims in CMP and they are not found - some are found in SHARE(?)

## Considerations
The fastest way to ensure this issue is resolved and submissions aren't orphaned

## Tasks
- [x] Fix bug
- [x] Determine or test if this works (write specs to repro Sentry exceptions)

## Acceptance Criteria
- [x] Tests have been written that fail, and code has been implemented to make them pass
- [x] A PR has been requested for merging, if applicable

-----------------
### Context:
Sentry Issue: [PLATFORM-API-7KS](http://sentry.vfs.va.gov/organizations/vsp/issues/49373/?referrer=github_integration)

```
NoMethodError: undefined method `[]' for nil:NilClass
  app/workers/central_mail/submit_saved_claim_job.rb:97:in `generate_metadata'
    'veteranFirstName' => veteran_full_name['first'],
  app/workers/central_mail/submit_saved_claim_job.rb:46:in `create_request_body'
    'metadata' => generate_metadata.to_json
  app/workers/central_mail/submit_saved_claim_job.rb:29:in `perform'
    response = CentralMail::Service.new.upload(create_request_body)
  lib/sidekiq/error_tag.rb:10:in `call'
    yield
  lib/sidekiq/retry_monitoring.rb:10:in `call'
    yield
...
(56 additional frame(s) were not displayed)

NoMethodError: undefined method `central_mail_submission' for #<SavedClaim::VeteranReadinessEmploymentClaim:0x00007ff00e032ef0>
  app/workers/central_mail/submit_saved_claim_job.rb:59:in `update_submission'
    @claim.central_mail_submission.update!(state: state)
  app/workers/central_mail/submit_saved_claim_job.rb:40:in `rescue in perform'
    update_submission('failed')
  app/workers/central_mail/submit_saved_claim_job.rb:20:in `perform'
    def perform(saved_claim_id)
  lib/sidekiq/error_tag.rb:10:in `call'
    yield
  lib/sidekiq/retry_monitoring.rb:10:in `call'
    yield
...
(57 additional frame(s) were not displayed)

undefined method `central_mail_submission' for #<SavedClaim::VeteranReadinessEmploymentClaim:0x00007ff00e032ef0>
```
