### ISSUE TITLE
[UX] Accessibility/Product Workshop 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#36747]
## Task
- [ ] Hold the initial workshop with Product and determine prioritization 
- [ ] If needed, schedule additional workshop session(s)
- [ ] Additional teams have been identified and documented

## Acceptance Criteria 
- [ ] Initial workshop call took place
- [ ] Prioritized items have been documented in the Mural board
- [ ] Additional teams added to Mural board
- [ ] If needed, additional UX tickets have been discussed and documented

**Comment by kristenmcconnell** [comment]
@julieadair1 To schedule the meeting. Ya-ching is out starting next Wednesday - Friday.

**Comment by julieadair1** [comment]
Scheduled for Monday, February 14.
