### ISSUE TITLE
Forms Detail Pages 

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#36759]
## Issue Description
_There are numerous forms that do not have a forms details page. This ticket is to research and determine which forms that are missing forms detail pages need to have one added._

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What forms should have detail pages_
- [ ] Which forms had detail pages and they disappeared
- [ ] Which name should actually be used? ie title or form name
- [ ] Which one should be mapping to Drupal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
