### ISSUE TITLE
[PM][Design][FE][BE] - Auth Profile - Address Change Messaging - Regroup to review mockups

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36752]
## Background
We mapped out some workflows in [Mural](https://app.mural.co/t/vsa8243/m/vsa8243/1643216182753/9108ac7e5e7743179212669d1af1c2dd27ab98f4?sender=ubc7e3ad210f2b3eb28e46170), some draft mockups were created in #35585, and a discovery review was held.  This task is to review the output from those activities before moving forward with implementing them on the Front End.

## Tasks
- [x] Meet to review mockups that reflect decisions made in a [discovery review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-change-messaging/meeting-notes/discovery_review_2022-02-16.md)
- [x] Go/No-Go decision on whether to move forward with implementing design or if further changes are needed.

## Acceptance Criteria
- [x] Meet to review Address Change Messaging mockups
- [x] Go/No-Go Decision

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske do you mind taking a look at this ticket and make sure it includes the info you expect?  Thanks!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO I will also first need to make the (minor) updates to the mockups to show the decisions from our discovery review. Should we put something in this ticket for that or will there be a separate tickets? Should be a small task so I'm good with it just being added here if that works.
