### ISSUE TITLE
R&S Tags Next Steps

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#36761]
Creating sitemap for R&S Tags/Topics
---
## Tasks
- [x] _Create sitemap draft_

## Acceptance Criteria
- [x] _[Draft created](https://miro.com/app/board/uXjVOMoEp0U=/?invite_link_id=503523755171)_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Sitemap https://miro.com/app/board/uXjVOMoEp0U=/?invite_link_id=503523755171
