### ISSUE TITLE
Twice-weekly Platform website deploy (M 3)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36765]
# User story

As a Platform customer, I need to view up-to-date info on the Platform website so that I don't run into roadblocks when building my VFS app.

As a Platform team member, I need the Content team to regularly publish any/all changes to the Platform website so that I can trust that info about my Platform product/service is available to customers.

# Tasks

- Use SVP to publish on:
  - [x] 1st Thurs of spr
  - [x] 1st Tues of spr
  - [x] 2nd Thurs of spr
  - [x] 2nd Tues of spr
  - We will not be reviewing for style guide compliance.  We will simply be pressing "publish"

# Acceptance criteria
- Platform website has been "deployed" four times

# Reference info
- Overall guidance - [Updating the "go live" process for the Platform website](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2096660936/Updating+the+go+live+process+for+the+Platform+website )
- How to go-live with Scroll Viewport -- follow [instructions in Step 5](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Step-5%3A-Update-the-Platform-website)

**Comment by lianilychee** [comment]
We will hold this for Spr 74.  We don't want to take on deploying without communicating that the live content sources contain info that is ready to go.
