### ISSUE TITLE
Update configuration of FSR confirmation email to send from DMC service

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#36771]
## Issue Description
To separate out teams from having access to all email templates VA Notify has sectioned off templates by team and this template has been allocated to the DMC team

---
## Tasks
- [ ] Receive API key from VA Notify team over keybase
- [ ] Add key to AWS param store and devops repo
- [ ] Update config to have entry way for VA Notify using key
- [ ] Update code to initialize notification service with new dmc key

## Acceptance Criteria
- [ ] The template is being sent out from VA Notify via DMC connection
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
