### ISSUE TITLE
[Research] Talk to Analytics Team

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36787]
# Description
UX wants to review the metrics for pre-check-in and check-in as they align to outcomes. We want to understand how to set up/implement Google Analytics so we can see this information. We also want to know more about how to see general analytics information in VA's GA account.

- Question for the analytics team [in this doc](https://docs.google.com/document/d/12lWfL7P6zDAzplTLcz0BvHiZ96FazbQ_pEMsodvSg3E/edit#)  

## Tasks
- [ ] Meet with analytics team (to understand GA and what is their process)

## Acceptance Criteria
- [ ] Meeting complete
- [ ] Questions addressed and documented (in Google document)
- [ ] We will have a list of next steps (what do we need to adjust on check-in's/ pre-check-in's dashboard).
- [ ] Meet with UX team to share what was learned in meeting with analytics team

**Comment by kristenmcconnell** [comment]
@zach-park @kristenmcconnell To review the questions document before 2/17/2022's meeting with analytics.
