### ISSUE TITLE
Analytics Implementation or QA Support for YouTube Video Tracking

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#3678]
# Analytics Implementation or QA Request
As a content producer, I want to understand the engagement of YouTube hosted videos that appear on the va.gov domain.

## Description
- Is this request for Google Analytics implementation or QA?
Implementation

- Who is this request for?
David Watson at MHV

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
MHV
    
- Provide the Domain where Google Analytics needs to be implemented
    Across Modernized and legacy content [Use WBC and Modernized Google Tag Manager containers]
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
Please publish by 12/3/2019

- Typical Website Interactions to Track:

 - Video Plays, Pause, and Stops
 - Percentage watched

## Acceptance Criteria
- [ ] Implement within modernized and WBC containers
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@jonwehausen This is the request that David Watson from MHV asked for. The time sensitivity is before his 12/4 campaign launch, so publishing on 12/3 is ideal. Let me know if you need a GTM recipe.

**Comment by jonwehausen** [comment]
Hi @nedierecel , 

Here's a summary of is what I have for this implementation: 
- Event will fire under these conditions: 
   - Initial Start
   - Pause
   - 25/50/75/100 progress
- Push the video title into a custom dimension

Let me know your feedback. 

### Start Video
![image](https://user-images.githubusercontent.com/48527022/69967313-1ffe1400-14e6-11ea-94ef-f3e266741c89.png)

### Pause Video
![image](https://user-images.githubusercontent.com/48527022/69967688-f42f5e00-14e6-11ea-96f4-e0a6e95f4ff7.png)

### Progress Percentage
![image](https://user-images.githubusercontent.com/48527022/69967845-335daf00-14e7-11ea-918e-a09e04b20a4c.png)

### Completion 
![image](https://user-images.githubusercontent.com/48527022/69967957-6ef87900-14e7-11ea-947f-2f53cfe754f5.png)

**Comment by nedierecel** [comment]
@jonwehausen Thanks for wiring this--to stay within our naming conventions, can we alter to the following:

Event Category: Interactions
Event Action: `Start` OR `Pause - <Insert Duration it was paused here>` OR `Reached XX%` (instead of Progress) OR `Stop` OR `Completed`
Event Label: Use the built-in GTM event

I see it also brings in the video name into CD 61. Thanks for adding that as well!

**Comment by jonwehausen** [comment]
@nedierecel Thanks for your comments here -- much appreciated. 

I've since updated to correlate with your recommendations above. 

To effectively output the Event Action labels you requested, see [LUT - Video Tracking - Event Action Label](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/107/variables/34). This takes each OOB GTM video status and outputs to a friendlier name. 

One other use-case this captures is skips....this is captured as OOB GTM video status 'seek'. In these instances, we're am capturing whether the user chose to skip forward or skip back and the timestamp they landed on. 

### Skip Forward
![image](https://user-images.githubusercontent.com/48527022/69992363-7df71f80-1517-11ea-8cf0-77d650eadfb4.png)


### Skip Back
![image](https://user-images.githubusercontent.com/48527022/69992340-7172c700-1517-11ea-87e9-97772dfe24ee.png)

### Pause 
![image](https://user-images.githubusercontent.com/48527022/69992574-f4941d00-1517-11ea-83bf-4c3c18c59719.png)

### Percentage
![image](https://user-images.githubusercontent.com/48527022/69992626-1ab9bd00-1518-11ea-9832-b884480484a7.png)

### Unexpected Buffering
![image](https://user-images.githubusercontent.com/48527022/69993068-0de99900-1519-11ea-9909-43f27b0a9263.png)


### Completed
![image](https://user-images.githubusercontent.com/48527022/69992694-4341b700-1518-11ea-823b-9e5195d945c9.png)

**Comment by nedierecel** [comment]
Thanks @jonwehausen for the Pause, Buffering, and Skipped Back to - can you add a label to indicate that this is the timestamp where the user paused, buffered, or skipped back? The numbers might be fuzzy to someone reviewing the report.

**Comment by jonwehausen** [comment]
Hi @nedierecel ,

Thanks for your comments. Here's the latest QA screenshots: 

### Skip Ahead
![image](https://user-images.githubusercontent.com/48527022/70066485-cfa4b600-15ba-11ea-95d4-086f6386b184.png)

### Skip Back 
![image](https://user-images.githubusercontent.com/48527022/70066570-ec40ee00-15ba-11ea-83b4-ad3b2cf0b764.png)

### Paused
![image](https://user-images.githubusercontent.com/48527022/70066613-f95ddd00-15ba-11ea-9c8f-e2bcda6365db.png)

### Buffering
![image](https://user-images.githubusercontent.com/48527022/70066776-3f1aa580-15bb-11ea-8555-50b02d307130.png)

**Comment by nedierecel** [comment]
Thanks @jonwehausen The new Action values look better. Can you publish and then send a note to David W. that this should be live? 

To confirm, will this also be in the Modernized container?

**Comment by nedierecel** [comment]
@jonwehausen I see the event in the Modernized container. I also added a "s" to the end of Interaction to align it with our Event Category naming.

**Comment by jonwehausen** [comment]
Hi @nedierecel 

Thanks for gut-checking. 

Functionality is now live in both containers and custom dimension 61 is allocated towards "Video Title" in non-prod and prod properties.
