### ISSUE TITLE
VBMS Letters not appearing in Debt Portal

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#36788]
## Issue Description
DMC has discovered that as of December 22, 2022 VBMS letters are not appearing in the portal. However we can tell from google analytics that Veterans have been able to download letters since that date.  The date of those letters is unknown.

---
## Tasks
- [ ] Investigate VBMS data schema - is date field available?
- [ ] Reach out to VBMS, are they incorrectly applying attributes to the letters?

## Acceptance Criteria
- [ ] Solution has been identify and letters are once again appearing in the debt portal correctly.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by craigwheeler** [comment]
Looking into this issue and it appears that the `letter-received-date` is being passed to GA [here](https://github.com/department-of-veterans-affairs/vets-website/blob/f04254ca5f450919a632c89c8e1bcb9460b0ba8c/src/applications/debt-letters/components/DebtLettersTable.jsx#L16) which has the value of `debt.receivedAt`. Will need to dig into this further to determine why the `letter-received-date` value is not showing in the reports?

**Comment by craigwheeler** [comment]
We have determined that Dec 9th is the most recent `letter-received-date` showing in GA and were also showing downloads of previous debt letters being downloaded as of today's date

![Analytics 360 2022-02-15 16-17-55.png](https://images.zenhubusercontent.com/5f355b2a6fe9a1b76ba980d4/22ef1e8e-e983-40f3-8c69-c834409bd244)

**Comment by denisecoveyduc** [comment]
Since Veterans are currently unable to download recent letters (Dec 9 to present), created issue to add a pop up alert to notify them in the event they are trying to download a recent letter. #37032

**Comment by denisecoveyduc** [comment]
#37678 notification will address the VBMS letters not being downloadable.
