### ISSUE TITLE
Outreach and Events V2 "Go Live" [FEB 15]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36786]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Tasks
- [x] Publish outreach and events V2 to Production
- [x] Test locally to determine functionality
- [x] Ensure push was successful (not bugs) 
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Events V2 and Recurring events is live and working as intended   
- [x] Local test are completed and show signs of success
- [x] PM/PO reviewed and validated

**Comment by brianalloyd** [comment]
@tmac9494 Staging looks good, can you deploy to production?

**Comment by brianalloyd** [comment]
Updates have been applied, closing ticket in support.

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/20308

**Comment by tmac9494** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/984
