### ISSUE TITLE
[AWS / IAM] Define standard permissions for platform team DevOps engineers

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#36791]
## Description

With reorganization of teams and being cross-functional, permissions for devops within teams should be defined to allow access to unblock their respective teams

## Background/context 

[Slack](https://dsva.slack.com/archives/CTYQL39FE/p1644443388523749)

---
## Tasks
- [x] Defined permissions for devops engineers
- [x] Establish a permission for devops engineer as code

## Acceptance Criteria 
- [x] Permission for devops engineer defined and created

**Comment by oseasmoran73** [comment]
Relates to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37685)

**Comment by oseasmoran73** [comment]
Adding [slack](https://dsva.slack.com/archives/CTYQL39FE/p1646405439308839) convo to this ticket

**Comment by jbritt1** [comment]
ADR created: https://vfs.atlassian.net/wiki/spaces/ECP/pages/2110029855/Grant+Resource-Scoped+Administrator+Permissions+to+Non-Infrastructure+Platform-Team-Attached+DevOps+Engineers

**Comment by jhouse-solvd** [comment]
@jbritt1 @oseasmoran73 - Based on the attached ADR, I think this can be closed. 

If you agree, can you please drop a note and close this out?

**Comment by oseasmoran73** [comment]
I am in favor of closing

**Comment by jbritt1** [comment]
Agreed, same, closing.
