### ISSUE TITLE
Update Opening Text Block of Product View Dashboard

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#36797]
## Issue Description
Review and modify the opening text block to better fit a Product-focused Dashboard

---
## Tasks
- [x] Review current text and determine what should be updated
- [ ] Research if Dashboard title text can be dynamically generated according to the Dashboard title for the different product dashboards
- [x] Update overview text
- [x] Update documentation link
- [x] Update feedback survey link

## Acceptance Criteria
- [ ] Text has been reviewed and approved

**Comment by pjhill** [comment]
@JoeTice 
- [ ] Review opening text and provide feedback

**Comment by CBonade** [comment]
Completed this today after receiving updated approved language. I was unable to find a way to dynamically insert a page title as a text card. We can use calculated values from data sets but there didn't appear to be a way I could find to access page properties.
