### ISSUE TITLE
Validate Data in Dashboard Cards

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#36799]
## Issue Description
Review the numbers displayed in the product dashboard proof of concept (VAOS Dashboard) to verify that the numbers shown match the actual data.
---
## Tasks
- [ ] Review the numbers in the cards and compare with the actual results in the test data available for the POC

## Acceptance Criteria
- [ ] TestRail measurements in Dashboard align with data in TestRail
- [ ] E2E measurements in Dashboard align with data available in spot-checked Mochawesome reports
- [ ] Contract test measurements in Dashboard align with data available in spot-checked Mochawesome reports
- [ ] FE Unit test measurements in Dashboard align with data available in spot-checked Mochawesome reports

**Comment by CBonade** [comment]
All date ranges on all cards have been confirmed as set correct. A brief summary of my logic that I used to determine date ranges:

- Any cards that represent execution time of some sort should be a one-week timeframe. This will 1) only spotlight problems that are currently here and 2) avoid artificially clogging the data with outdated problems that may no longer exist
- Cards that represent coverage should show a 30 day history. I think coverage is something that won't change much short-term, as tests are added slowly over time. A 30-day average will show how the app is slowly improving or declining, where a one week snapshot would likely just be a flat line most of the time
- Cards that represent failures and/or flakiness should be a short time period, like maybe 3-4 days at most? If a test is flaky or failing over longer than that, it's likely made it to a support request and we're aware of it. Also, if we dilute it over a longer time period, 1 failure in a sea of passes would likely be overlooked.
- Other cards I think are ok for a 30 day history, as mostly they're just showing progress of an application over time

During my initial review pass, I noticed that E2E flakiness was missing a date parameter in the actual data to make the data respond to the date range. I corrected this and have verified the data is now correct for the timeframe.

Additionally, I discovered the coverage data was including a lot of zeroes. After discussing this with Release Tools, I was informed that unit tests have test selection happening, but they didn't know why that would result in zeroes. Typically, when E2E or unit tests run and a test is not included via test selection, there would not be a result at all. Because the unit test coverage report is generated as a custom report, using the manifest list to loop through and then finding the matching values....if there is no matching value, the line just reports zero. So, I have adjusted the queries to only include results that have a number greater than zero and the dashboard now seems to match in all 4 of these cards.

I will continue exploration on this tomorrow.

**Comment by CBonade** [comment]
To the best of my ability to spot check, the current data is correct. That said, the chart that depicts average pass/pending/failure, to me, doesn't really make sense the way we're displaying it. I'm going to work on converting this to a total instead of an average.

**Comment by CBonade** [comment]
I have rebuilt the Pass/Fail card to a total over a 3-day period, which should alert to recent issues. I've also reworked the data, as it was applying suite-level data to the individual test specs. It appears to be correct to the best of my ability to check now. 

I believe this finalizes what I feel like was the last piece of data that was not correct.

**Comment by pjhill** [comment]
Thanks for quality checking this -- I don't see anything jumping out as irrational to me. I spot checked a few datapoints as well.
