### ISSUE TITLE
[UX] Review va.gov profile's behavior for "Mailing address" required

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36794]
# Description
Review the current behavior related to mailing address being required on the VA.gov profile sectino.

# Tasks
- [x] Log into staging and look at va.gov profile
- [x] Document current behavior
- [x] Update sketch 

# Acceptance Criteria
- [x] [Sketch link](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/v/15dwW8/a/4an9O8A/r/jem750)
- [x] Communicate changes to FE, so they can write a ticket

**Comment by zach-park** [comment]
Current VA Profile bevaviors:
They are fairly consistent in the exception of two areas:

Button vs Back navigation interaction: https://dsva.slack.com/archives/C022AC2STBM/p1646079114089819
Remove mailing address: https://dsva.slack.com/archives/C022AC2STBM/p1646079228079819

@kristenmcconnell @ytsaoca @niradatta1 @jparker0425

**Comment by zach-park** [comment]
Browser Back button navigation and Edit Cancel button wireframe are ready. The link is attached to the ticket's AC. 
@kristenmcconnell @ytsaoca @niradatta1 @jparker0425 @acrollet @brianseek @dcgoodwin2112 @mdewey
