### ISSUE TITLE
Funnel Changes - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#36807]
## Issue Description
Products and their funnels are not static, they can change as needed over time to best service our Veterans.  We need to establish a process for how to address changes to the funnel and the impact they have on our dashboards.

---
## Tasks
- [x] Research how to address these changes so we are accurately reporting the status based on the funnel in place at the time of submission.
- [x] Review/explore VAOS as use case for these types of changes.

## Acceptance Criteria
- [x] Best practices doc defining types of funnel changes and how to handle/manage each.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Meeting on 2/15 with Michelle, Julie, Chloe & Brian

Brian to complete documentation on types of funnel changes and best practices for how to handle/manage each.

**Comment by bsmartin-ep** [comment]
@obrienjulie -

For the actual funnel versioning, I think you just need to update all the forms views to `BETWEEN` the hit's timestamp...

```sql
INNER JOIN `vsp-analytics-and-insights.vsp_sites.forms` AS f ON
  hits.page.pagePath LIKE CONCAT(f.step_link, '%')
  AND f.active = true
  AND visitStartTime + (hits.time / 1000) BETWEEN f.active_start AND f.active_end  
```

And - of course - the Domo dashboards will need to be modified to handle multiple funnels with something like...

![image](https://user-images.githubusercontent.com/62304138/165984997-9aed4dd7-5a67-4b33-bbf1-b48b20ce92c2.png)

**Comment by obrienjulie** [comment]
There is a new view in BigQuery to test out these changes - [vsp_sites.vw_forms_funnels_testing](https://console.cloud.google.com/bigquery?pli=1&project=vsp-analytics-and-insights&ws=!1m14!1m3!8m2!1s86772881199!2sfe4eac5fc9704c79ab7b64b13d8ebc6e!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_forms_funnels_testing!1m4!1m3!1svsp-analytics-and-insights!2sbquxjob_4a43e7ba_180b391c270!3sUS).  This is just filtered to show January - March 2022 data for the 10-10CG Form. All of January reflects the current form steps and February - March shows the new steps.  There is a new field called Parent_Form that says 10-10CG and the form name has been modified to reflect the break in forms.  

There is a DOMO dataset with this view - [Form Funnel Testing](https://va-gov.domo.com/datasources/d6a6864e-b43d-4441-aa9d-7862eb4075cd/details/overview).

@chloedotbrown, @pavanhothi  - Please review and let me know if everything looks good to you. Once you're good with it, I'll make the adjustments to our standard form funnel changes.

**Comment by chloedotbrown** [comment]
Hey @obrienjulie - I think this is really close! The data structure fix I'd ask for before implementing this in the standard forms funnel dataset would be to change how we're doing the hierarchy, so that instead of creating a new overarching field, we're creating a new sub-field for versions. 

**Current version**
|Parent_form|form_name|
|:---|:----|
|Form 10-10CG | Form 10-10CG - Caregivers Application|
|Form 10-10CG | Form 10-10CG - Caregivers Application - Update|

**New version**
|form_name|version|
|:---|:----|
|Form 10-10CG - Caregivers Application | v1|
|Form 10-10CG - Caregivers Application | v2 - updated 2/1/2022|

This will be more intuitive for users and will work better with Domo's filter functionality. Since `form_name` is our dashboard-wide filter across several datasets, we need the field name and all available values to be the same across them all. It will also accommodate multiple versions more easily, if team's make more than one update to their form's logic. This way, we can simply add a filter card above the funnel and exit rate card and will only affect them.

From the data content side, this looks good! Funnel totals for the old version by step here seem to match our current funnels totals for Jan. 2022, so I don't imagine we'll get bogged down in QA with the switch. And before adding this into the main dataset, it does look like the [forms_definition table](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2sanalytics_testing!3sforms_definitions) might have an extra 5655 entry in row 2?

Anyway, let me know if you have any other questions and when the new data structure is ready!

**Comment by obrienjulie** [comment]
Hi @chloedotbrown  - Thanks for the suggestion on adding in a version instead of a parent_form.  I've made the changes and [DOMO](https://va-gov.domo.com/datasources/d6a6864e-b43d-4441-aa9d-7862eb4075cd/details/overview) has been updated.  If everything looks good to you, I'll write up the new process and update our standard BQ views.

**Comment by chloedotbrown** [comment]
Awesome @obrienjulie - this looks great! I'd say we're good to go. Once the backfill is updated, let me know and I'll set up the new filter cards on the Forms dashboard. Thanks!

**Comment by obrienjulie** [comment]
@chloedotbrown  - The [Standard Forms Funnel](https://va-gov.domo.com/datasources/432a85a7-5581-4e80-8601-dc13c9654436/details/cards) dataset has been backfilled in DOMO. The new funnel steps for 10-10CG are in DOMO.

**Comment by chloedotbrown** [comment]
Thanks, @obrienjulie! This is great. Only edit I'd make is to `version` field. I need the output to read just "V1" for all initial versions so that I can set this as the default view across all forms. That way, we avoid any potential situation where folks with multiple versions see a table that includes both and get confused. However, having some V1s with a date included throws this off. 

For the meantime, I've created a beast mode to get the output I need. But for next backfill, would be great to change the rule in line 102-3 to something like:

```     
case when forms.version = 'V1' then forms.version
        else concat(forms.version,' - Updated ',forms.active_start) end as version,
```
I've added these filter cards to the [Forms dashboard ](https://va-gov.domo.com/page/447193050)and pre-set them to "v1" in the default view. Flagging for @michelle-dooley - once time-to-complete cards are ready, the Exit section layout will need some edits so that it's visually clear which cards these filters impact.

**Comment by obrienjulie** [comment]
I updated the views to show just V1 for the original version with a date attached to it. I went ahead and backfilled DOMO so @chloedotbrown  will see this now.

**Comment by chloedotbrown** [comment]
Amazing! Thank you so much, @obrienjulie!

I've reconfigured the [dashboard](https://va-gov.domo.com/page/447193050) cards, deleted the beast mode, and tested to make sure everything's still working. I also added a note near the first version filter explaining what it does.

Whenever documentation is good, I think we should be able to close this one out! 🤞🏻

**Comment by obrienjulie** [comment]
Updated documentation is complete and can be found [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/2201321491/Forms+KPIs+Funnel+Logic).

@chloedotbrown / @michelle-dooley  - Please review and let me know if any edits are neded.
