### ISSUE TITLE
Investigate and Fix TestRail Ingestion Breakage

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#36802]
## Issue Description
Investigate the issue that we're seeing with TestRail ingestion and resolve.

_**UPDATE**_ We now know that the issue was caused by an update created by Gurock to our cloud instance of TestRail. We do not have the capability to roll back to a previous version. We have contacted Gurock support. They pushed an update that supposedly fixed it, but it did not. We complained to support again. We are now in a holding pattern waiting for a patch from Gurock that fixes the issue.

---
## Tasks
- [x] Discover the root cause of the failure to ingest TestRail data into BigQuery
- [x] Contact Gurock support if needed
- [x] Monitor Gurock releases for an update that resolves the issue
- [x] If necessary make changes to the TestRail data ingest

## Acceptance Criteria
- [x] TestRail data ingest updates BigQuery

**Comment by holdenhinkle** [comment]
It seems there's an error with TestRail api that started 3 days ago:

`message: { error: 'Undefined property: stdClass::$sso_enabled' },`

Peter found a thread about it in the TestRail forum - https://discuss.gurock.com/t/testrail-api-returned-http-500-in-get-user-by-email/20757

I'll keep an eye on this. There's nothing i can do until it gets resolved.

**Comment by pjhill** [comment]
@pjhill -- Need to formally log a bug about this with TestRail.  Perusing their forums, it looks like at least one other user has complained about a similar issue.

**Comment by holdenhinkle** [comment]
The TestRail api is still broken. We can't connect to it:

Beginning of response:
```
{
  message: { error: 'Undefined property: stdClass::$sso_enabled' },
  response: <ref *1> IncomingMessage {
```

Logging from the ingest app:
```
√ testing-tools-team-dashboard-testrail-data % yarn testrail-to-bigquery
yarn run v1.22.17
$ node src/testrail/
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
Error: 'Timeout'
^C
?130 testing-tools-team-dashboard-testrail-data % 
```

**Comment by holdenhinkle** [comment]
I emailed support:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/d78bae44-8050-4b8b-ac5a-7350009f11bd)

**Comment by holdenhinkle** [comment]
They just responded:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/65adfe04-5650-40d1-a47d-836d93eb8cc4)

**Comment by holdenhinkle** [comment]
I just confirmed that the TestRail api issue has not been fixed yet.:

```
{
  message: { error: 'Undefined property: stdClass::$sso_enabled' },
```

**Comment by pjhill** [comment]
We are waiting on the TestRail fix to go live. The investigation is complete.

**Comment by holdenhinkle** [comment]
This work was completed under this ticket - https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/43071

**Comment by pjhill** [comment]
Wow this hid in `review` for a while. As indicated this was fixed in a different ticket, so this is kind of a dupe.
