### ISSUE TITLE
[VAMC] Test and list all Facility locator links that do not work correctly and need updated redirect [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36813]
## Story
As a Veteran, I need an accurate link to all facilities from facility locator, so I can quickly find my medical facility.

## Resources
[VAST] - 

## TASK  Audit systems until one is found to fail, then deep dive that System for more information
- [x] Review systems from June 2021 until September
- [x] Review Systems from September until December
- [x] Document all facilities that fail redirect in Facility locator

## Acceptance Criteria
- [ ] New csv document for Lighthouse API posted and slacked for Lighthouse to take action.

**Comment by ltrombley** [comment]
Task #36813 - Test and list all Facility locator links that do not work correctly and need updated redirect - is Complete and Pending move to Validate once CSV file is complete
