### ISSUE TITLE
[vets-api-sidekiq-ui]  Application onboarding infrastructure request

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#36811]
## Summary
The purpose of this template is to capture requirements for onboarding a software application to the Platform's delivery infrastructure. 

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application
The purpose of this app is to monitor sidekiq. 

### Basic info:
**Team Name:**   
_"Integration Experience - Platform Spike Team"_  
**Application Name:**  
_"SideKiq UI of VETS-API"_  
**Functionality:**  
_"Sidekiq UI (aka Sidekiq Web aka Sidekiq Monitoring) is a web application that can display the current state of Sidekiq’s queues"_  
**Language/Stack:**  
_"Ruby Rack Application"_  
**Ports/Networking needed:**  
_"Port 3002 for standard plain HTTP"_    
**Other infrastructure needed:**  
_"VETS-API Redis on port 6379, i.e. redis URL shall point to DEV namespace of VETS-API"_  
Would like to connect to existing redis for Vets-API. 

### Background/Context/Resources
_Please link to an initiative or supporting documentation that desribes the need and purpose of the application_
https://vfs.atlassian.net/wiki/spaces/IET/pages/2008580174/Roadmap+-+IET

### Technical Notes
_Additional technical info that describes the desired setup and configuration_
"The ability to contact development redis"

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** _link to repo [here](https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui)_  
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team; Infrastructure Team can assist_  
- [x] **Dockerfile:** _provide link to Dockerfile here_ | [Example](https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/app/Dockerfile) | [Docs](https://docs.docker.com/engine/reference/builder/)  
_Requesting team; Infrastructure Team can assist_  

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions**,   | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:**   
_Infrastructure Team_ | [PRs welcome](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)  
- [X] **Automation to release and tag the app's GitHub repo with a semantic version number** | (DONE) [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation. 
_Requesting team; Infrastructure Team can assist_  
- [x] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** in `vsp-infra-application-manifests` | (PR Open: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/341) [Example](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps) | [Docs](https://argo-cd.readthedocs.io/en/stable/)  
Note: must be compatible with ArgoCD  
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR (IN PROGRESS, can test once we've been added to the repo) | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml)  
_Requesting team; Infrastructure Team can assist_

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** | None yet, need to create request.  [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** We will need to access REDIS_URL which represents the redis instance development sidekiq is running in.  [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by jhouse-solvd** [comment]
@considerable - Thanks for submitting. We'll get started on this and will respond with any questions and next steps.

**Comment by jhouse-solvd** [comment]
@considerable @ewilson-adhoc -- 

In order for the Infrastructure Team to add the AWS/GitHub service account credentials to the repo provided above:

**Please grant admin access on the repo to [VSP Operations team** - @department-of-veterans-affairs/vsp-operations](https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations)

**Comment by jsgarmon** [comment]
ECR repo and service account is created with API key. As soon as we get admin access to the repo, I'll add secrets for GitHub Actions to use.

**Comment by ewilson-adhoc** [comment]
@jsgarmon this has been done, let me know if there are any problems.

**Comment by ericboehs** [comment]
This should probably be named "vets-api-sidekiq-ui" as this will be the future place for the Sidekiq UI for Vets API.

I'd be afraid to put a spike team name as the name of an app as we may delete apps associated with the spike team when the team goes away.

This is definitely a Vets API related service and should be namespaced accordingly.

**Comment by ewilson-adhoc** [comment]
> This should probably be named "vets-api-sidekiq-ui" as this will be the future place for the Sidekiq UI for Vets API.
> 
> I'd be afraid to put a spike team name as the name of an app as we may delete apps associated with the spike team when the team goes away.
> 
> This is definitely a Vets API related service and should be namespaced accordingly.

Chatting with the rest of the team about what naming conventions we want to standardize on. We'll go ahead and open a PR if we decide to change the name. Do you think it would make sense to namespace pghero in a similar way?

**Comment by ericboehs** [comment]
> Do you think it would make sense to namespace pghero in a similar way?

Yes I do. We've had the repo namespaced that way since we created it.

If someone else wanted to stand up a pghero instance for their PG database, we'd have a naming conflict without a namespace.

**Comment by ewilson-adhoc** [comment]
After discussing namespacing with Eric and some of the long-term goals of the console team, we decided to rename the repository to vets-api-sidekiq-ui. Please let us know if this will cause any problems.

**Comment by jsgarmon** [comment]
No problem, I'll update the name today.

**Comment by ewilson-adhoc** [comment]
@considerable opened https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/341 yesterday, crosslinking here for ease of reference

**Comment by oseasmoran73** [comment]
sidekiq-ui issue from docker. see [slack](https://dsva.slack.com/archives/CJYRZK2HH/p1645488451148339) thread for more details

**Comment by ewilson-adhoc** [comment]
We've completed all of the major action items for this! We're going to tie up a few loose ends and clean up the documentation, but once that is done we can close this epic out.

**Comment by ewilson-adhoc** [comment]
Closing. No additional work is needed from infrastructure on this issue at this time.

**Comment by jsgarmon** [comment]
I'm guessing this is for OAuth, yes? Do you have values for these, or do you need help creating them?

**Comment by ewilson-adhoc** [comment]
> I'm guessing this is for OAuth, yes? Do you have values for these, or do you need help creating them?

Correct, I have them already set up -- I just need to populate them for the app.

**Comment by jsgarmon** [comment]
You should now have the ability to create parameters under the `/dsva-vagov/vets-api-sidekiq-ui` path.

**Comment by ewilson-adhoc** [comment]
> You should now have the ability to create parameters under the `/dsva-vagov/vets-api-sidekiq-ui` path.

Is this something that I should do via the aws CLI, or is there other infrastructure/tooling that I should be using to do this (it doesn't seem like I have access to do this via the console)?

**Comment by ewilson-adhoc** [comment]
When I try to access parameter store I see the following error and no option to add a new parameter. 

User: (my ARN( is not authorized to perform: ssm:DescribeParameters on resource: arn:aws-us-gov:ssm:us-gov-west-1:IDNUMBER:* because no identity-based policy allows the ssm:DescribeParameters action

**Comment by jsgarmon** [comment]
You should be good to go now, if you'll try again.

**Comment by ewilson-adhoc** [comment]
Awesome, all set now, thanks!
