### ISSUE TITLE
Refactor COE 1/n

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#36821]
# Background
During the last round of syncing design updates with the front end on COE it was discovered that much of the COE application could be refactored to make it both easier to maintain and more performant. This refactor was done in a PR however this PR is too large to meet VA.gov standards for PR lengths and needs to be broken up into multiple PRs before they can get approved and merged.

## Tasks
- [ ] Review PR with other front end engineers
- [ ] Determine the best strategy to break PR apart
- [ ] Break PR into multiple PRs for review
- [ ] Submit PRs for review

## Acceptance criteria
- [ ] The main COE refactor PR has been broken into multiple PRs for review
- [ ] PRs have been submitted for review
