### ISSUE TITLE
Content and layout updates to MHV Inherited Proofing wireframes

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#36838]
## Issue Description
This ticket is created to track the body of work of modifying the wireframes from feedback gathered during the UX/FE/VA leads discussion about the MHV account transition.  Requested changes will be outlined in the tasks below:

---
## Tasks
- [x] **Eligible**
  - [x] (Modal) Update content for MHV credentials (stricter reqm'ts portion) to talk about MHV credentials rather than MHV
  - [x] Update all dates in content to reflect a past date
  - [x] Combine the Consent page and informational page
  - [x] Remove the MHV number from the Consent callout
  - [x] Eligible page, make action call out more prominent, CTA up-front, add Consent to this page for Authentication

- [x] **Not Eligible**
  - [x] (Modal) Update content to verify your account
  - [x] Wizard - Change Other: Passport to go to ID.me
  - [x] Update flow to send user to Dynamic consent page rather than informational (Verify your identity page)
  - [x] Remove the can't automatically transition paragraph
  - [x] Add CTA for secure-sign in, sign up for an account **
  - [x] Create a more prominent experience between actions & information

- [x] **General**
  - [x] Add Modal to say that you have a Login.gov account, you should use this account moving forward. (Acknowledgement that they successfully logged in)
  - [ ] ~~Create additional Login.gov screens for the Inherited Proofing portion with accompanying user workflows~~

## Acceptance Criteria
- [x] The wireframes are signed off by UX team and ready for Collab Cycle review

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
