### ISSUE TITLE
ICONs missing on VA.gov Homepage | Hub Pages

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#36830]
#### High-level user story
As a Veteran VA.gov is my source of truth and should have a comfortable and aligned style.

### Background
![Screen Shot 2022-02-11 at 7 38 04 AM](https://user-images.githubusercontent.com/70410912/153611628-8b4d99e9-0a11-48fe-bb00-2c1b9770a02d.png)

It looks like they may be missing from the Hub Pages too:
https://www.va.gov/family-member-benefits/
https://www.va.gov/service-member-benefits/
Compared to:
https://www.va.gov/burials-memorials/

### Tasks
- [ ] Determine issue cause and revert icons back to original state on both home page and hub pages.
- [ ] Test locally to determine functionality
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] ICONS on homepage and hub pages are rendering as intended
- [ ] Local test are completed and show signs of success
- [ ] a11y considerations are implemented in support

**Comment by tmac9494** [comment]
somewhere the style that targets ".merger .hub-icon-family-member" and ".merger .hub-icon-service-member" have been removed.

It looks like the color rules are still there for these two specific icons but lower in the file where these icons are being implemented, these two icons are missing now. I'm not sure where this generated file lives/configs so I can't move past this point without some direction.

Tracked it down to the generated files: 
 - vets-website/build/localhost/generated/styleConsolidated.css 
 - vets-website/build/localhost/generated/style.css

**Comment by brianalloyd** [comment]
Platform team found the issue and will merge today during daily deployment.

**Comment by brianalloyd** [comment]
Issue resolved, closing ticket in support.
