### ISSUE TITLE
Relocate widgets and listeners

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#36845]
### Description
In accordance with the discovery findings of [32793](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/32793) all widgets are to be moved to a new folder `src/widgets`.
A widget is defined as any react application that is added to a page by a means _other_ than mounting a `div#react-root` element.  (Usually this means mounting an element that has a data attribute of `data-widget-type="{<your-widget-type>}"`)

The only exceptions to the above are the widgets which currently live in `src/platform` and the following widgets which will be moved to `src/platform`:
* [i18Select](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/i18Select/I18Select.js)
* [wizard](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/wizard/index.js)

### Todo

- [] create `src/widgets` folder
- [] move widgets to `src/widgets`
- []  move widgets to `src/platform`
- [] create `src/widgets/listeners` folder
- [] move listeners to `src/widgets/listeners`
- [] create a `widgetsInit.js` file in `src/widgets` that initializes the widgets and listeners
- [] call `widgetInit.js` in `src/static-pages/static-pages-entry.js`
- [ ] update documentation
- [ ] notify teams of change

### Testing
- [ ] verify that all widgets and listeners load and function correctly

**Comment by timwright12** [comment]
@it-harrison can you update this info just so we know where we left off?

**Comment by it-harrison** [comment]
> @it-harrison can you update this info just so we know where we left off?

will do

**Comment by CBonade** [comment]
Issue stale. Closing
