### ISSUE TITLE
[SW-Content] Research and develop Quality composition check list and process flow to improve overall content quality and accuracy [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36841]
## Story
As a Veteran I need reliable and quality, relevant, and quality information, so I can make complex and basic decisions based off of the information provided on my VA.gov content pages.

## Resources
[Content Assessment Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/assessment-criteria-for-SME-requests.md)

## Tasks
- [ ] Research and determine all the needed points of review and tools needed to improve quality
- [ ] Develop Templates and/or checklist for content writers and editors
- [ ] Review and outline process with SW-Content team
- [ ] Discuss and determine how to measure improvement

## Acceptance 
- [ ] Provide full conceptual flow to PM to create content flow chart for tracking
- [ ] Create and save template/guideline document as artifact

**Comment by psanders86** [comment]
# Checklist for VSA content writers/editors for new and updated content

This artifact memorializes procedures we have in place to produce content in the appropriate voice, style and tone to publish on VA.gov. The work product is the result of best practices and workflows used by content writers and editors on the Sitewide Content team.

There are 3 types of content:

**Content updates after an audit.** This can include reworking headers, links, and other changes to make sure the language and formatting is consistent across VA.gov pages and tools. 
**Recurring updates to an existing page.** This can range from simple updates —swapping out videos on a landing page bi-weekly— to more complicated updates like annual updates to rate pages.
**ME/product team requests.** This can include adding content and/or links to a page. 

Publishing new or updated content is a 9-step process:

**Intake:** Receiving and logging the request
**Intake review:** Assessing the request
**Assignment:** Assigning the request to a content writer
**Discovery:** Researching what needs to be done and the best approach
**Writing:** Creating the content
**Review:** Managing editor takes a first pass at the content
**Copyedit:** Copy editor takes a final pass at the content
**Submission:** Work is submitted to product owners and SMEs/product teams
**Publication:** Content is pushed live and published

## Intake
Intake tasks are requests for new or updated content to be produced by the sitewide content team. The product manager manages the intake flow.

Content requests can come from 3 sources:
1.	Intake requests from VSA teams that that are routed to the project manager
2.	Requests generated by the product owner
3.	Requests from external stakeholders that are emailed directly to the product owner and relayed to the PM.

### Intake tasks to complete
- [ ] Create a ticket for each content request.
- [ ] Put the ticket on the team’s Zenhub board.

## Intake review
The intake review is the process of assessing content requests to determine if they should be accepted or rejected. This discussion is led by the product manager at Sprint planning or team standup ceremonies.

**Note:** Urgent requests can be brought to the team right away for discussion and assignment instead of waiting for a planning/standup ceremony.

### Intake review tasks to complete:
- [ ] Determine the reason for the request. What problem are we trying to solve?
- [ ] Verify that the request is Veteran facing.
- [ ] Verify that 1 of the following are true
*	The update helps Veterans understand their benefits better.
*	The update helps Veterans find and apply for benefits and services available to them.
*	The update improves the positive experience on VA.gov.
- [ ] Determine if the request duplicates content on another VA.gov page. We wouldn’t add information on a page then link to something that repeats the same information.
- [ ] Update the ticket with the answers to the above questions. If we determine the content request does not meet our criteria, then document why we are declining the request and notify the SME/product team.

## Assignment
After the content request is accepted and placed in the Sprint workflow, it is assigned to a content writer or editor. This is done can be done by the project manager or the managing editor.

### Assignment asks to complete
- [ ] Assign a content writer, the managing editor and the copy editor to the ticket.
- [ ] Estimate the effort required to complete the work and document it on the ticket.

## Discovery
Discovery is the task of researching the scope of the work to determine the best path forward. This work is done by the content writer.

### Discovery tasks to complete
- [ ] Review the request so you understand the problem that we are trying to solve.
- [ ] Review any documentation and suggested language provided by the SME/product team.
- [ ] Research related content already published on VA.gov.
- [ ] Research external sources, if needed, if you have additional questions about the problem we are trying to solve.
- [ ] Determine if the webpage where the SME/product team requested the change or addition is the best place, or if it makes more sense to update a different webpage, or create a new page.
- [ ] If the change will be made to an existing page, determine where on the page the updated information will appear.
- [ ] Review with the managing editor to get alignment with your plan. Depending on the scope of the work, we may also update the product owner at this point.
- [ ] Determine if we need to change an H1 or URL. If so, reach out to the product owner and IA, as such changes would require redirects and other possible updates.
- [ ] Meet with the product team to review the request and outline our plan to update the page and get alignment. Note: If request came from an VA stakeholder, then let the managing editor know and they’ll set up the meeting.
- [ ] Document that meeting and decisions made in the Zenhub ticket.

## Writing
At this point, the content writer is ready to start producing content. If an existing page is getting updated or edited, this work can be done in Drupal and saved in “draft” status. If you are creating a new page or rewriting a large section of an existing page, then do the work in a Word document.

As a reminder, VA.gov content is written in an intentional way to support Veterans’ needs and improve their experience on our site. Our goal is to create consistent, clear, and customer-centered content. Our text is consistent, conversational, clear and helpful, and empathetic.

### Writing tasks to complete
- [ ] Review previous VA.gov pages and the VA.gov content style guide to ensure your word choices are in alignment with VA.gov style and previously published work.
- [ ] Use sentences in active voice.
- [ ] Use contractions.
- [ ] Use short sentences and avoid compound sentences when possible.
- [ ] Document your source material in the Word document or the Zenhub ticket.

### Accessibility tasks to complete
- [ ] Confirm all links contain a purpose and a target. A user should be able to tell from just the link text what the link does and where it is sending them. [Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)
- [ ] If your link will take the user off VA.gov, tell them where they'll land: Make sure the words in the text link, action link, or button indicate to the user that they're leaving VA.gov and where they're going. The text link above is an example of this.
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the heirarchy of headings is correct (H1 to H2 to H3—levels shouldn't be skipped). [Read WCAG documentation](https://www.w3.org/WAI/tutorials/page-structure/headings/)
### Link tasks to complete
- [ ] Confirm that links work (aren't broken--no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to does not live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md)
### Resources and Support article tasks to complete
- [ ] Character limit for subheads: Confirm H2s, H3s, and H4s are within the 70-character limit.
- [ ] Related links: Confirm that you've added appropriate related links to the file (they should truly be related to the article—rather than “something the reader may also be interested in”).
- [ ] Cross linking: Determine if this new article should be added as a related link on any live articles. (Do you want to drive users to this page from elsewhere on VA.gov?)
- [ ] Call to action (CTA): When considering the wording for your CTA text, check to see if a label is already in use for this CTA on VA.gov. [Check the master list of labels for buttons and action links](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/resources-and-support/rs-cta-button-audit.md)
- [ ] Alternative text ("alt text") for any screen shots on the page: Confirm that screen shots or other images have alt text that describes the image. Screen readers will read this text to the user, and search engines use it to assess the purpose of the page. [Learn how to write alt text on WebAIM](https://webaim.org/techniques/alttext/)
### Drupal tasks to complete
- [ ] Correct primary article category and additional article categories.
- [ ] Correct benefit hub contacts.
- [ ] Appropriate audience and topic tags.
- [ ] "Repeat CTA buttons" box if it's a long article (to display the action link(s) at both the top and bottom of the page).
- [ ] If you want a single Q&A to appear as a stand-alone article and not just as part of a multiple FAQ, click "Enable standalone Resources and support page for this Q&A."

## Review
The review is conducted by the managing editor to make sure the content meets VA.gov style and fulfills the request made by the SME/product team. Depending on the scope of work, the managing editor may send the content back to the content writer for discussion and revisions.

### Review tasks to complete:
- [ ] Review the request so you understand the problem that we are trying to solve.
- [ ] Review any documentation and suggested language provided by the SME/product team.
- [ ] Review the artifacts in the ticket, including notes of the content writer’s alignment meeting with the SME/product team.
- [ ] Review the content block and edit according to VA.gov content principles and style.
- [ ] Confirm sentences are in active voice.
- [ ] Use contractions.
- [ ] Confirm sentences are kept short. We should avoid compound sentences when possible. Break them up into 2 sentences.
- [ ] Confirm that content setups are consistent with already published VA pages. We should phrase information the same across all pages.
- [ ] Do a copyedit of a full page, even if updates are to a particular part (some pages have not been touched in a while and can have outdated style rules).
- [ ] Factcheck when necessary. Review the source material and other VA.gov pages.
- [ ] Review changes with the content writer.

## Copyedit
The copy editor is responsible for giving a final review to the content to ensure that nothing has been overlooked.

### Copyedit tasks to complete:
- [ ] Review the request so you understand the problem that we are trying to solve.
- [ ] Review any documentation and suggested language provided by the SME/product team.
- [ ] Review the artifacts in the ticket, including notes of the content writer’s alignment meeting with the SME/product team.
- [ ] Call phone numbers to confirm it’s the right office and the hours are correct.
- [ ] Click links to ensure they go to the right website (not just that they are working).
- [ ] Confirm sentences are in active voice.
- [ ] Use contractions.
- [ ] Confirm sentences are kept short. We should avoid compound sentences when possible. Break them up into 2 sentences.
- [ ] Check that content matches rules in style guide (items on word list, components, etc.).
- [ ] Confirm that content setups are consistent with already published VA pages. We should phrase information the same across all pages.
- [ ] Confirm header levels and bolding are correct throughout.
- [ ] Do a copyedit of a full page, even if updates are to a particular part (some pages have not been touched in a while and can have outdated style rules).
- [ ] Factcheck when necessary. Review the source material and other VA.gov pages.

## Submission
After the copy editor’s final check, the content is submitted to the product owner for validation.

### Submission tasks to complete:
- [ ] Move the Zenhub ticket to validate.
- [ ] The project manager creates and assigns a ticket to the product owner to review the work with appropriate documentation.
- [ ] After the product owner’s approval, the managing editor or project manager provides the final content block to the SME/product team for review.

## Publication
Only after the team’s work is approved by the product owner and the SME/product team can it be published.

### Publication tasks to complete:
- [ ] If the content block was reviewed in Drupal, the copy editor changes the status from draft to publish.
- [ ] If the content block was reviewed in Word, the content writer inputs the text into Drupal, where it is reviewed by the copy editor before publication.

## A note about translations 
We currently provide most of our COVID-19-related in Tagalog or Spanish. Use these tips when updating these pages—especially if you don’t speak either languages.
* Always have the current live version of the English open in a browser tab. This will help you easily find the part of the page that needs to be updated on the translated version.
* Have two browser tabs open for Google Translate. Use one tab to paste in the translated content to get the English version. This can also help you find the part of the page that needs to be updated faster or determine if the translations are wrong. Use the other browser tab to type in English content that needs to be translated. This is usually the case if the translators forgot to translate part of the content. If this happens, include it in your write-up so that the content can later be properly translated. 
* Keep a list of missing translations or other observations when updating the page in Drupal. Add your notes in the GitHub ticket during hand-off to the copy editor for review and publishing
