### ISSUE TITLE
[BE] Call CHIP endpoint to initiate pre check-in when the pre check-in session is started

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#36847]
## Description
Currently, the `pre-check-in-started` status is set in `initiatePreCheckin` lambda when VeText call it. This is creating a false impression that a lot of pre check-ins are started and not completed, while in reality a lot of the text messages are never clicked on. 

To fix this, when the Sessions#Get is called for pre check-in scenario (which vets-website calls when the Veterans click on the link in the text message), a call needs to be made a CHIP endpoint which sets the status. 

## Related Documentation
- [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1644584548482759)

## Tasks
- [x] add feature flag
- [x] Add the new method to call CHIP endpoint in CHIP Client class
- [x] Add the service layer
- [x] Update the SessionsController to make this call for pre check-ins.

## Acceptance Criteria

- [ ] Deployed and tested on staging.
