### ISSUE TITLE
[SW-Content] Phase 1: Debt portal content and IA strategy

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36844]
## Story
As a Veteran I need to have a single portal to view and fins all of my debt management tools, so I can better understand my debts and obligations.

## Resources
TBD

## Tasks
- [ ] Meet with Debt resolution team to support determination and understanding of design 
- [ ] Determine tasks for IA and Content team to support Epic goal of single debt portal for VBA and VHA

## Acceptance Criteria
- [ ] Roadmap for Product has been determined
- [ ] Support tasks for Phase II have been outlined and documented.

**Comment by rileyorr** [comment]
Hi @mnorthuis! Here's the research I mentioned during today's meeting:

**VBA Debt Portal usability study**
- The research readout can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/usability-july20/usability-readout.md#usability-key-takeaways-in-depth). Areas of interest from an IA-perspective include:
   - Finding 1. Veterans had different strategies for locating VA debt information online
   - Finding 3. Participants quickly found the content about the types of debt included in the tool, but also expected all VA debts to be included

**Medical Copay Tool discovery research** 
- The research readout can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/readout.md). Some areas of interest from an IA-perspective:
   - [Where Veteran's expected to find copay information starting from VA.gov ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/readout.md#when-searching-vagov-for-information-about-money-owed-to-va-veterans-often-search-within-the-lens-of-the-hub-theyre-dealing-with)
   - [Keyboards Veterans looked for when searching for a pathway to copayment information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/readout.md#veterans-looked-for-a-variety-of-keywords-when-searching-for-a-pathway-to-copayment-information-but-primarily-looked-for-bill) 

Let me know if you have any questions!

**Comment by mnorthuis** [comment]
Notes from meeting with Denise and Riley on 2/14/2022
- Discussed [high level mocks and various options documented in UX Pin](https://preview.uxpin.com/32e8ac818076b3dc502846e0b13356fa40779575#/pages/147178588/comment/sitemap?mode=i)
  - The "minimal" approach satisfies short term goals and congressional mandates, with minimal  impact to the individual tools and their current structure and functionality
  - Meets timelines and sets us up to continue to evaluate and evolve
- Discussed major considerations from IA standpoint:   
  - How might we maintain specific links for specific tasks that lead to this new combined experience?
  - How do we ensure we do not create a more challenging navigational/click path to complete individual tasks despite a combined experience?
- Conversation notes
  - Users currently click contextual links and land on specific content/tool pages (i.e. "Pay your copay bill takes the user to a page about paying your copay bill).  With this change, the content page is non-specific, as all debt and payment related tools will be combined.  
  - Need to evaluate optimal user flows for entry points - currently all roads lead to static page, once signed in you return to that static page, this experience should be smarter and able to take users directly to their specific task so we can maintain relationship between what you clicked and where you land. 
  - Need to identify what key tasks are that users need to find easily and complete with minimal clicks and potentially bubble them up in the experience for quick access. I.e. Pay your copay is external task, users shouldn't need to log into va.gov and drill down to get to that task.
  - Making sure secondary tasks (i.e. hardship/FSR) are also not buried too deep.
  - Some content may  move to R&S.
  - Crosslinking to related content/data where appropriate (i.e. debt info linking to payment history)
- Discussed the new landing page and terminology
  - Riley has some research findings pertaining to the word "bills" as how research participants framed up this type of content/functionality.  
  - The current Manage your VA debt static page would require some restructuring and change to accommodate more related tools (i.e. copays in near term).  
  - This work will likely result in a change to H1 and URL that possibly eliminates the word "debt". Need to make sure Jill is aware of this.

Next steps:
- Mikki to document entry point flows showing optimal experience for unauth and auth, expectation is to share this with Jill
- Mikki to bring Danielle up to speed on content work and timeline and determine impacts to content
  - retirement of singular landing page
  - creation of new "financial" landing page
  - content that is candidate for R&S
- Riley to continue to refine wireframes
- Denise to set up follow up convo with Danielle and Mikki to regroup prior to presenting approach to Jill

**Comment by mnorthuis** [comment]
Initial flows for discussion

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/1f3149de-8948-4510-afd2-4c2cb6a94101)

**Comment by rileyorr** [comment]
Good morning @mnorthuis! [Here's the user flow diagram](https://app.mural.co/invitation/mural/vsa8243/1645453970389?sender=riley5075&key=b9051645-ff1a-4307-a1df-bd9622b9ca31) for Friday's meeting with Jill in case you'd like to take a look before our sync today.

**Comment by mnorthuis** [comment]
This is fantastic @rileyorr!

**Comment by mnorthuis** [comment]
2/25/22 - Reviewed approach with Jill
- Jill requested that users be able to see the grand total of the debts/copay balances on the summary page in addition to the number of debts/copay bills and indicated that is what congress is looking for, i.e. you owe $350 in debt and $75 in copays; the long-term goal is that they are all managed and paid in one place, single statement
- For auth users, since they bypass the summary and go straight to either the copay or debt pages, we need a way to alert them to the other type of debt/bill they have, i.e. if they are on the copay page, they should be informed if they also have a debt
- We should plan to test for terminology and user flow; for auth users we need to know if they understand the context of where they are when they bypass the summary
- There was some conversation about bookmarking the old experience and circumventing the new experience; we will need to discuss URL and redirect strategies once labeling is determined and experience is fully designed

Next steps will be to iterate on design, more detail, and research plan.

**Comment by rileyorr** [comment]
Hi @mnorthuis! I hopped into @DanielleThierryUSDSVA's content office hours last Thursday to share the second iteration designs before presenting to Jill. I'm circling back to see what our next steps are from a content/IA strategy perspective. Should the three of us and @denisecoveyduc meet to review how the designs have evolved ([UXPin prototype for reference](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1bq0f96*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/148519709/simulate/sitemap?mode=i)) and discuss strategy for the combined portal's content page?

**Comment by rileyorr** [comment]
Hi @mnorthuis and @DanielleThierryUSDSVA! I'm following up to see if you're both available to sync this week concerning labeling and next steps regarding updates to the content page as my team ramps up development efforts. If this week works for y'all, here's some times I'm available:

Wednesday 3/30:
- 11:00 AM - 2:00 PM ET 

Thursday 3/31: 
- 12:30 PM - 3:00 PM ET 

Friday 4/1: 
- 11:30 AM - 4:00 PM ET 

cc @denisecoveyduc @SgardnerPMP

**Comment by mnorthuis** [comment]
Thank you for the reminder ping @rileyorr!  I can make time on Wednesday or Thursday.

**Comment by mnorthuis** [comment]
Any of the times you suggested for Wed or Thurs works for me, so schedule away!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rileyorr! I just put a hold on my calendar for tomorrow from 2 - 3 p.m. ET. If that works (either half hour or hour), feel free to send an invite. Thanks!

**Comment by mnorthuis** [comment]
Strategy work complete, design work continuing in  https://github.com/department-of-veterans-affairs/va.gov-team/issues/39294
