### ISSUE TITLE
Create Playbook for troubleshooting vets-api support requests

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36843]
## Description
Create a detailed playbook for troubleshooting vets-api support requests.

## Background/context 
The SRE team receives support request related to vets-api issues.  This playbook will list troubleshooting tips and guidance on how to handle those requests.

---
## Tasks
- [ ] Identify the categories of vets-api support requests 
- [ ] Create documentation with the process and steps to follow when a vets-api requests is submitted.
- [ ] Identify support requests categories and types that can be supported by an automated bot.

## Acceptance Criteria 
- [ ] Playbook created.

**Comment by rmtolmach** [comment]
We've started https://vfs.atlassian.net/wiki/spaces/PTST/pages/2599289071/Backend+how-to and https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities also exists. But maybe there can be more?
