### ISSUE TITLE
Determine owners of VA developed GEM Dependencies in Vets-API

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36842]
## Description

vets-api has a number of internally developed Ruby GEM dependencies like connect_vbms that need to be maintained and reviewed .  We needed to create a list of the owners , the PR change process for each of these VA developed GEMs.

## Background/context 
This [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1644440425723029) provides background on the need.  

---
## Tasks
- [ ] Review the current dependencies in the [vets-api Gemfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Gemfile)
- [ ] Create a playbook with the owners and how PRs or changes a handled.

## Acceptance Criteria 
- [ ] A new playbook with the process is created and accessible on the SRE support page.

**Comment by rmtolmach** [comment]
The `blame` functionality in github can be used to discover ownership. [GitHub blame for Gemfile](https://github.com/department-of-veterans-affairs/vets-api/blame/master/Gemfile). Completing this task would be more work than it's worth.
