### ISSUE TITLE
Create Datadog Dashboard for vets-api identification of issues and troubleshooting

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36851]
## Description

Datadog dashboards allow for enhancing vets-api identification of issues and troubleshooting of issues.

The dashboard should provide a detail view of all the observable potentials  points of failure.

## Background/context 

This is a proactive view of supporting vets-api.

---
## Tasks
- [ ] Identify the observable points of failure for vets-api in staging in datadog currently.
- [ ] Identify the observable points of failure for vets-api in production in datadog currently.
- [ ] Identify opportunities for adding datadog integrations to enhance the observability
- [ ] Create a dashboard with the observable points of failure for vets-api in staging in datadog currently.
- [ ] Create a dashboard with the observable points of failure for vets-api in production in datadog currently.
 

## Acceptance Criteria 
- [ ] A new vets-api troubleshooting dashboard
