### ISSUE TITLE
[Platform Infrastructure] Document support guidance 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#36852]
## Description
There is conflicting or unclear guidance for how the infrastructure team should respond to requests for support. One example is the ops onboarding template. Let's document this and make sure it's updated in all the right places. 

## Background/context 
Example here: https://github.com/department-of-veterans-affairs/va.gov-team/pull/35915

---
## Tasks
- [ ] Document support guidance
- [ ] Share with the team

## Acceptance Criteria 
- [ ] Support guidance is linked to the team charter 
- [ ] Support guidance is linked to the ops onboarding template

**Comment by jhouse-solvd** [comment]
relates to #37352, #37527
