### ISSUE TITLE
Create POC Support Request Auto Answer Services

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#36853]
## Description
Create a web service/api that will take support questions and return answers for the future integration into the Slack support bot.

## Background/context 

One of the SRE team goals is to look for opportunities to automate responses to issues like support requests.

---
## Tasks
- [x] Create an AWS Lambda Base Function that takes in text and return text. POC
- [x] Create list of key words and phrases to be used by the NLP process to determine context for responses.
- [x] Create a list of links to documentation related to the context of a few common support request .

## Acceptance Criteria 
- [ ] A working AWS Lambda service that responds to a few key phrases in support requests.

**Comment by powellkerry** [comment]
## 1st iteration Test Plan

### What Changed:

- A new sheet was added to the Platform Responses Google Doc. The sheet contains 2 columns for "TopicId" and "Link" and will be a mapping for support request topics and links that will be used by the auto responder.
- A new environment variable was added to the application as a reference to the new sheet
- Logic was written to check if there are entries in the sheet associated with the support request topic. If there are, a threaded response will be sent to the slack message listing the documentation that was associated with the topic
- Currently there are 20 links associated with 11 of the topics. This list can be update to remove/add links when necessary.

### Test Cases:
_The updates have been deployed to the test environment and can be accessed via slack in the va-support-slackbot-test org and vsp-platform-support channel_
- Use the /support slack command to submit a ticket using a topic with auto-answer links defined (PR Review, App Setup, Environments, etc) 
-- A ticket should be created as usual, after the ticket is posted a threaded reply should show up listing the associated documentation
- Use the /support slack command to submit a ticket using a topic without auto-answer links defined (Something Else)
-- A ticket is created as usual, with no threaded response

**Comment by powellkerry** [comment]
Auto answer functionality was deployed 8/8/2022
