### ISSUE TITLE
Show file size for uploaded files

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36861]
## Description

To allow Veterans to better differentiate uploaded files, we want to add the file size adjacent to the file name.

This has already been implemented within the claim status tool file upload code.

![CST upload](https://user-images.githubusercontent.com/136959/153669552-e42d66b5-7307-4232-87c9-e9c25f453a05.png)

This should be included in the platform file upload code

## Tasks

- [ ] Add file size below the file name
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
