### ISSUE TITLE
[GovCloudPlus] Test 1010CG via direct-to-SF after SF's GovCloudPlus production launch

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#36864]
## Description
Salesforce (which the CARMA app sits behind) will be migrating from Gov Cloud to Gov Cloud Plus, on Feb 25 11pm to Feb 26 3am Eastern.

After Salesforce confirms their production env has been migrated from GovCloud to GovCloudPlus, we should do an end to end test.

## Tasks
- [ ] using one of the 3 MPI test accounts that were created for prod testing (help from David Wald), submit 1010CG form in production
- [ ] confirm submission was received in CARMA prod

## Acceptance Criteria
- [ ] Successfully tested in production

**Comment by RudyOnRails** [comment]
@SKasimow This one, surprisingly, isn't Mulesoft related (it's confusing), and won't be needed until sprint 68. I should've mentioned - I searched for a Sprint 68 label but didn't see one and didn't want to make one and step on toes, so I just put it in the Feb 28 - March 23 sprint.

**Comment by SKasimow** [comment]
Thanks @RudyOnRails - I changed the labels and added Sprint 68 and took off MS.

**Comment by RudyOnRails** [comment]
@SKasimow we weren't able to perform a prod connectivity test ourselves since those prod MPI profiles didn't work, but it wasn't necessary as we've had 100's of 10-10CG applications successfully submitted since the GovCloudPlus migration Sat morning so David and I agreed that this test would be redundant and the troubleshooting of the test profiles not being found in MPI prod would take time away from Mulesoft work.

Going to close this and then close out the epic. If you want to add anything or reopen, please feel free to.
