### ISSUE TITLE
Remove resources managed by appeals from devops terraform state, code

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#36876]
## Description
There are at least a few resources managed by both appeals and the platform infrastructure team. For example, the `efolder_express` IAM role appears in 2 state files and 2 repos:
https://github.com/department-of-veterans-affairs/appeals-terraform/blob/master/modules/iam_users_groups/roles.tf#L108
https://github.com/department-of-veterans-affairs/devops/blob/b3c3565beb9cec7411d3adc0b6ac55162c394e69/terraform/environments/global/iam_roles.tf#L353

## Background/context 
Seeing conflicts as each repo tries to undo the changes made by the other.

---
## Tasks
- [ ] Identify duplicated resources
- [ ] remove resources managed by appeals from the infrastructure team's devops repo

## Acceptance Criteria 
- [ ] No more duplicated resources

**Comment by jhouse-solvd** [comment]
@jsgarmon - I noticed a linked PR. Are there other follow-up tasks needed?

**Comment by jsgarmon** [comment]
It's probably worth some time to go through their code to see what other things overlap. The change needed in the linked PR was only apparent because the code was slightly different between the 2 repos, causing the resource to vacillate between two states.

**Comment by jsgarmon** [comment]
I haven't been able to find other examples of overlapping Terraform, so closing.
