### ISSUE TITLE
Give performance dashboard AWS creds to access github_actions_slack_bot_user_token

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#36874]
## Description
The performance-dashboard would like to send slack notifications. as such we need our role to have access to /devops/github_actions_slack_bot_user_token
We already have AWS credentials and store other stuff in /dsva-vagov/performance_dashboard/

## Background/context 
We would like this in order to connect our github actions to notify slack.

## Technical notes
We have put in some changes to make this work in this workflow:
https://github.com/department-of-veterans-affairs/performance-dashboard/blob/development/.github/workflows/data-update.yml

It currently fails b/c the AWS credentials given to performance-dashboard don't have the rights to read the devops/github actions slack bot user token.

We think the AWS credentials are these ones:
`data "aws_iam_policy_document" "performance_dashboard_sa" `

---
## Tasks
- [ ] Update the policy for performance_dashboard to add ability to access the devops slack token. (I think?)

## Acceptance Criteria 
- [ ] Ideally the workflow here: https://github.com/department-of-veterans-affairs/performance-dashboard/blob/development/.github/workflows/data-update.yml should pass (though there may be other bugs)

---
### Reminders
- [ ] Issue: https://github.com/department-of-veterans-affairs/performance-dashboard/issues/4054

**Comment by karlbrown-va** [comment]
tested and working. thanks.
