### ISSUE TITLE
Define Researcher role in the Collaboration Cycle: Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#36887]
## User Stories
As a UX Researcher supporting the Governance team, I want to define my role for the Design Intent so that I know how to contribute to future Collaboration Cycle Design Intents with VFS teams.

As a VFS team, I need to know what is expected of me/my team with regards to research at Design Intent so that I can ensure my team is prepared and able to meet Platform expectations.

## Description
We have worked to establish the UX Researcher role in the Research Plan Review, but we still need to define how research as a practice area will be supported in the other Governance-owned Collaboration Cycle touchpoints, specifically Design Intent, Midpoint Review and/or Staging Review. The scope of this ticket is specifically for Design Intent.

## Artifacts potentially needing updates
[Platform Website: Collaboration Cycle/Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
[Platform Website: Collaboration Cycle/Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
[Confluence: Collaboration Cycle/Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Confluence: Collaboration Cycle/How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[GitHub template: Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+collab-cycle-review%2C+design-intent&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)
[GitHub template: Collab Cycle Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collaboration-cycle%2C+collab-cycle-feedback&template=collab-cycle-feedback.md&title=Practice+Area+Feedback+-+Name+of+Collab+Touchpoint+-+Name+of+Project)
New 2/21: [Confluence: Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Before you begin any editing of guidance, answer the following questions:
   - Should Collab Cycle team member (aka the UX Researcher) be required to provide feedback tickets on the research practice area at Design Intent?
        _A. No. Research may not be ready at this point, and research feedback makes sense to go on the Research Repo ticket anyway._
   - Will we need to request any research artifacts from the VFS team?
        _A. Not required, but teams may include if they are prepared, we can add a bullet on the ticket as a prompt_
   - What role should research play this early in the design process?
        _A. Fluid, questioning if any prior research is being used to guide design plans, guiding by pointing out related previous research, encouraging teams to consider best research practices and how those relate to their current product, methodologies, and areas of the design for focused testing_
   - How does the timeline for research align with the timeline for Design Intent?
        _A. Many teams may not be prepared for research at this touch point, may not have even thought about research at this point, we feel that DI will be early on in research process for many teams_
   - Should the agenda and/or objective of Design Intent be impacted by the addition of research as a practice area?
        _A. Not necessarily. We do want teams thinking about research this early, but we don't want to bog them down at this point or make DI feel overwhelming. We do want time during DI for at least a quick discussion on research, and some cursory feedback will likely be appropriate in most cases_
   - Will we want to request additional attendees from the VFS team and/or OCTO? for example, Shane?
        _A. The focus of DI is primarily on the intended design and user flows and time during this touchpoint is already pressed, although we want to encourage teams to start thinking about research at this point. We think Shane should be invited for Midpoint, a time when most teams have prepared for research, but not DI. We should have a conversation with Shane to confirm_
   - Will the outcome of Design Intent be impacted by the addition of research as a practice area?
        _A. The outcome for the team could be impacted in that they may reconsider their approach, but we don't see research being a gatekeeper at this stage. If this is concerning the DI Outcome as listed on the [DI Platform page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html#Designintent-Outcome), we may want to update to state that reseaech may offer preliminary guidance or feedback_
   - How do we intend to update the DI script to include research?
        _A. Not the intro script, only in ensuring research gets a callout when calling on each practice area during DI_
- [x] Create Documentation Drafts of the pages to be edited
- [x] Update the pages as you see fit based off your responses to the above questions
   - ensure you are updating the pages consistently
- [x] when updates are complete, comment on this ticket requesting a peer review

## Acceptance Criteria
- [x] GitHub template: Collab Cycle Feedback has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#1.-Updating-existing-GitHub-issue-templates), if applicable 
- [x] GitHub template: Design Intent has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#1.-Updating-existing-GitHub-issue-templates)
- [x] Platform Website: Collaboration Cycle/Touchpoints has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation)
- [x] Platform Website: Collaboration Cycle/Design Intent has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation)
- [x] Confluence: Collaboration Cycle/Design Intent - Moderator Responsibilities has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#3.-Updating-existing-Confluence-documentation)
- [x] Confluence: Collaboration Cycle/How to provide feedback for a Design Intent [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#3.-Updating-existing-Confluence-documentation)
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@allison0034 @claytonzook - I just drafted this ticket today. Please review the user stories and description. This could potentially be a lot of work with many impacted artifacts. I would like to split it into smaller pieces of work. Allison, I'd like you involved bc you have familiarity and experience with the Design Intent, Midpoint and Staging - do you think it would make sense to split this into 3 tickets... 1 for each touchpoint? Keep in mind we'll need to update our Operational guidance and VFS-facing guidance.

**Comment by shiragoodman** [comment]
@claytonzook @allison0034 I'm realizing now that technically, Collab Cycle Kickoff is the first touchpoint, so it would've made sense to start there opposed to the Design Intent. On the bright side, there aren't many docs/guidance associated with the kickoff so I don't anticipate many changes.

I'm editing the ticket above to include the "Collaboration Cycle Kickoff - Moderator Responsibilities" doc as an additional artifact you all should take a look at. My assumption is that there will only be very minor changes to that doc.

Please let me know if you have any questions. Thanks!

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby cc @claytonzook here are the pages that need to be reviewed:
[Platform Website: Collaboration Cycle/Touchpoints](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096431486/Allison+Copy+of+Touchpoints)
[Platform Website: Collaboration Cycle/Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096431470/Allison+Copy+of+Design+intent)
[Confluence: Collaboration Cycle/Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096432128/Allison2+Copy+of+Design+Intent+-+Moderator+Responsibilities)
[Confluence: Collaboration Cycle/How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096267756/Allison+Copy+of+How+to+provide+feedback+for+a+Design+Intent)
[GitHub template: Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+collab-cycle-review%2C+design-intent&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D)
[Confluence: Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2097512633/Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

Once you approve I will move the drafts over.

**Comment by shiragoodman** [comment]
@allison0034 @claytonzook I made some comments in the docs. If I didn't make a comment in the doc, consider it approved. 

I did notice that the new artifact ([Confluence: Collaboration Cycle/How to complete a Design Intent Review: Research](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2090172529/How+to+complete+a+Design+Intent+review+Research)) was not included. Are you still working on this?

**Comment by chaseakirby** [comment]
@allison0034 @claytonzook I echo a lot of Shira's comments. One additional comment I had was I think the [GitHub template: Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+collab-cycle-review%2C+design-intent&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D) Artifacts section should reflect any updates you make [here related to Shira's comment](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096431470/Allison+Copy+of+Design+intent?focusedCommentId=2098790506#comment-2098790506).

**Comment by claytonzook** [comment]
@shiragoodman cc @allison0034  We decided that a new document just for research wasn't needed here. Instead, research is being added to the existing document, draft version linked below. If I find it untenable to follow everyone else's workflow on this, we'll iterate on the process for me/research. https://vfs.atlassian.net/wiki/spaces/PPST/pages/2096267756/Allison+Copy+of+How+to+provide+feedback+for+a+Design+Intent

**Comment by allison0034** [comment]
@shiragoodman I updated per your comments. I did not see the addition of Confluence: Collaboration Cycle/How to complete a Design Intent Review: Research, but I did see Confluence: Collaboration Cycle Kickoff - Moderator Responsibilities. 

I think writing documentation Confluence: Collaboration Cycle/How to complete a Design Intent Review: Research should probably be its own ticket. We currently do not have any documentation on specific practice area feedback, I know that is in another ticket. I think Clayton will have to think about this for a bit, and maybe we start with a practice area like design or accessibility so Clayton has something to reference. What do you think?

**Comment by chaseakirby** [comment]
Moved Research Specific guidance task into ticket [#37772](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/37772).
