### ISSUE TITLE
[Research] My VA - Copays: Discovery on adding copays to My VA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36899]
## Background
As discussed in **[ticket #33267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33267)**, we would like to begin some discovery on adding copay information as part of My VA.  This discovery will surface the information important to Veterans, and how they use the info today on VA.gov.  We also need to determine if we have enough information to move forward with adding it, or if further research is needed.

#### Resources
- GH Folder
- [Link to medical copay content page](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)
- [Link to detail page showing list of copays and detailed information](https://staging.va.gov/health-care/pay-copay-bill/your-current-balances/)

## Tasks
- [ ] Consider feedback from recent research participants
- [ ] Meet with Debt resolution team (Denise Coveyduc [PM] and Riley Orr [Design/Research])
- [ ] Compile discovery findings in [GH Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/Copays)

## Acceptance Criteria
- Complete discovery on copays and considerations on adding that information to My VA
