### ISSUE TITLE
Adjust COE Dropdown

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#36896]
## Background
For COE testing, we are going to need to get the dropdown list situated.

## Considerations
Values for Military Branch are: [ARMY, NAVY, MARINES, AIR_FORCE, COAST_GUARD, OTHER]

We are capitalizing and adding an underscore on the BE so you don't have to change those if you don't want to reformat, but the other values should be removed from the dropdown options.

We may want/need to keep the "Reserve" options. For example, Coast Guard and Coast Guard Reserve are currently both options. I think we may have to pass Coast Guard and then in a separate item pass in Reserve, but I'm not sure about this item yet. LGY has a "character of service field" which takes [ ACTIVE_DUTY, RESERVE_NATIONAL_GUARD ]. - KC

## Tasks
- [x] Military branch needs to be updated (list from KC)

## Acceptance Criteria
- [x] The list in the drop down matches the above
- [x] A PR has been requested for merging

### Next steps
FE
- Further adjust previously submitted tickets (Kathleen)

**Comment by kathleencrawford** [comment]
Values for Military Branch are: [ARMY, NAVY, MARINES, AIR_FORCE, COAST_GUARD, OTHER]

We are capitalizing and adding an underscore on the BE so you don't *have* to change those if you don't want to reformat, but the other values should be removed from the dropdown options.

We may want/need to keep the "Reserve" options.  For example, Coast Guard and Coast Guard Reserve are currently both options.  I think we may have to pass Coast Guard and then in a separate item pass in Reserve, but i'm not sure about this item yet.  LGY has a "character of service field" which takes [ ACTIVE_DUTY, RESERVE_NATIONAL_GUARD ].

**Comment by kathleencrawford** [comment]
This is going to end up being both a FE change and a BE change.

For FE, please remove:
`NOAA` and `Public Health Service` and replace them with `OTHER`

**Comment by kathleencrawford** [comment]
For BE, we need to do some data manipulation to handle the rest of the options.

For example, if `Army National Guard` is passed in from the form, we need to pass `Army` in the `militaryBranch` field and `RESERVE_NATIONAL_GUARD` in the `serviceType` field.

If `Army` is passed in from the form, then we should pass `ACTIVE_DUTY` in the `serviceType` field.

We'll need to do this for all the following: 
```
                  'Air Force',
                  'Air Force Reserve',
                  'Air National Guard',
                  'Army',
                  'Army National Guard',
                  'Army Reserve',
                  'Coast Guard',
                  'Coast Guard Reserve',
                  'Marine Corps',
                  'Marine Corps Reserve',
                  'Navy',
                  'Navy Reserve'
```
