### ISSUE TITLE
Update content security policy on VA.gov

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#36894]
## Description
[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36623)

In order to use Google Optimize to run A/B tests on VA.gov we need to change the content security policy on VA.gov. These policies are used to whitelist certain URLs to access the front end of VA.gov apps and since Google Optimize can change elements on a page it needs to be whitelisted and added to our content security policy. 

[Here is an article on Google](https://support.google.com/optimize/answer/7388531) that has more information about content security policies and how they relate to Google Optimize

## Background/context 

Our team has had lots of discussions about how we perform research for VA.gov and although we believe moderated research with Veterans is very valuable we also recognize that it can't tell us everything. For some questions to be answered we need unmoderated research by A/B testing on our apps. We intend to develop a system that allows us to not only A/B test on VA.gov but provides a framework that other app teams can use to perform their own A/B tests as well. To begin developing this system we need to get the basic infrastructure in place to run A/B tests and then run a pilot test on one of our apps.

We decided on running a test on our Rated Disabilities app because we got a suggestion from design a while back that we add a sorting feature to allow Veterans to sort the disabilities table by various data points. We were not convinced that Veterans would find it useful so we decided to A/B test it as our pilot.

## Technical notes

The article linked above from Google should have the technical details of making the update

---
## Tasks
- [ ] Update the content security policy to include Google Optimize
- [ ] Submit a PR for review and merge

## Acceptance Criteria 
- [ ] The content security policy has been updated on VA.gov to include Google Optimize

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Can you help us determine which team might be able to assist?

**Comment by jhouse-solvd** [comment]
@cohnjesse - Is this request still needed? Thank you!
