### ISSUE TITLE
NOD: Update tech documentation

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36890]
## Description

- Document what a new team member would want to know about this app
- What were some choices that were made that might require explanation?
- What are some things we'd make better if we had more time?
- If something went wrong how might we investigate?
- Is there anything we should update in our product outline?
- What are good staging test users?

## Tasks

- [ ] Write engineering documentation for the Notice of Disagreement form, including the key points above
- [ ] Get team members to review

## Definition of done

- [ ] All tasks complete

**Comment by Mottie** [comment]
Added here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement/engineering
