### ISSUE TITLE
[SW-Content]  Update rate on  eduction - "About GI Bill benefit" Rate [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#36893]
## Resources
Customer: Tammy Hurley
[Education rate  page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/)
## Tasks
- [x] Update customer page with requested changes. 
- [x] Validate changes are within SW-Content guidelines
- [x] Submit changes for review by stakeholder

![image.png](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/9c2bb831-1188-41b5-8d2a-bd01f7f31251)

## Acceptance Criteria
- [x] Updates are submitted to customer/stakeholder
- [x] Upon approval, changes are published.

**Comment by SgardnerPMP** [comment]
Updated with correct request.  Thank you.
