### ISSUE TITLE
Need Personal Access Token for va-bot account

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/va.gov-team#36901]
## Description
Team Okapi on Lighthouse is working on an updated auto deploy structure that includes a manual approval step in the middle. Currently this is in early testing and as such is using a PAT from my GitHub account. To ensure this process outlives my tenure on Lighthouse we need to move token used to create and search the maintenance requests to an established bot user, namely `va-bot`.

## Background/context 
https://vajira.max.gov/browse/API-12829 Ticket with the overall work needed to get auto-deploys back online. They were previously fully automated but that was disabled when a manual approval was added.

## Technical notes
[This PR](https://github.com/department-of-veterans-affairs/developer-portal/pull/972) talks through the process of how the flow works but in short a GitHub Actions job will create the maintenance request ticket and if that is labeled as approved at the requested go live date then a second job will perform a few checks and then deploy the code to production based on that approved MR's information.

---
## Tasks
- [ ] Gain access to the va-bot account
- [ ] Generate a Personal Access Token

## Acceptance Criteria 
- [ ] Token has the following permissions
  - [ ] `repo (all)`
  - [ ] `workflow`
  - [ ] `admin:org (only needs read:org)`
- [ ] Token is provided to the team via a secure method

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by gileswells** [comment]
Ideally the token would have no expiration but if a shorter duration for the token is required then the AC should also contain information on the best path / procedure to refresh the token in the future.

**Comment by jsgarmon** [comment]
@gileswells : Just so I'm clear, you're asking for an existing personal access token to be switched out for a bot token? What repo is this for?

**Comment by gileswells** [comment]
@jsgarmon Short version, that's exactly correct.

Currently I have my PAT working to support automatic deployments through human approval of MR requests of `developer-portal`. These requests are made to the `lighthouse-devops-support` repository. The goal here would be to change the automated opening of the MR and the automated reporting of success to be made through `va-bot`'s PAT or another bot user's PAT if a better one fits the bill.

The short version of the deploy process:

1. 3pm weekdays an MR is generated if there is new code to go to prod (opened with this new PAT)
2. Gabriel, or another approver, would add a `status: approved` label to the MR.
3. 10am the following day the MR would be deployed and the [build status](https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/1172#issuecomment-1046971691) would be updated (comment made with this new PAT)

**Comment by jsgarmon** [comment]
Does the PAT live in the developer-portal repo or the lighthouse-devops-support repo? I don't have admin access to either to change secrets.

**Comment by jsgarmon** [comment]
I've created a new va-bot token with the above specs, and updated `GIT_AUTO_DEPLOY_TOKEN` with this new token. Please test and close this issue if all looks good.

**Comment by gileswells** [comment]
That didn't work but I suspect it's because `va-bot` might not have access to view/create issues in the `lighthouse-devops-support` repo. I'm asking Gabriel to confirm. (that is unless you have access and could check)

**Comment by jsgarmon** [comment]
I can confirm va-bot does _not_ have access to that repo

**Comment by gileswells** [comment]
@jsgarmon I believe if you add `va-bot` as a either a traige or write access member of the repo that should solve the issue of being able to read and create issues.

**Comment by jsgarmon** [comment]
I also do not have access to the lighthouse-devops-support repo

**Comment by gileswells** [comment]
@golavarr-va was able to add `va-bot` to the repo and now all appears to be working as intended. Thank you.
