### ISSUE TITLE
Conduct Brainstorming Session for QA Standards

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#36900]
# Description
In order to understand what Quality Assurance practice standards we can assess products against, we need to come up with a list of standards that apply to products hosted on VA.gov and a system for reporting and enforcing performance against those standards for each product hosted on VA.gov. We should collect the brainstorming results into a central document / artifact in Mural.

## Tasks
- [x] Create a Mural where we can collect the brainstormed ideas - [Created a Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1646058007444/f3eef8f28b71d670650df02ac79d29ea4bb62ad9?sender=peterhill4315)
- [x] Brainstorm a list of standards that we can measure and enforce against individual products given the tools and processes we have in place on VA.gov.
- [ ] Brainstorm a standards system of measurement and enforcement. Should there be different categories of standards? Some standards are applied against one enforcement system and other standards are applied against a difference enforcement system?
* For example --
    * Below this threshold your team is warned. Below this threshold your team is warned that the product will be removed from VA.gov.
    * You are required to participate / comply with this standard 100% in order to continue on the platform.
- [ ] Brainstorm a minimum standard for each QA standard that we brainstormed previously.

## Acceptance Criteria
- [x] We have a list of potential standards that apply to test methodologies supported by the VA.gov Platform
- [ ] We have a proposed standards system. 
- [ ] We have proposed minimum levels of performance for each standard

**Comment by JoeTice** [comment]
We conducted a team brainstorming session and follow-up discussions [in Mural here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1646058007444/f3eef8f28b71d670650df02ac79d29ea4bb62ad9?sender=uc4d00ea50beebdfad05a4846)

**Comment by JoeTice** [comment]
Initial Set of Recommended Standards Include:
- Blocking: If no E2E Tests exist for a product
- Warning: For E2E Test flakiness
- Warning: Unit Test coverage
- Warning: E2E Test coverage
- Warning: Lighthouse Accessibility Rating

**Comment by pjhill** [comment]
Joe's Confluence document with a summary of brainstormed QA standards for MVP --https://vfs.atlassian.net/wiki/spaces/TTT/pages/2126544949/QA+Standards+Team+-+Draft+Development+Standards

**Comment by pjhill** [comment]
Brainstorming has been completed. The next steps are to shop around the proposed standards to refine them or get input.
