### ISSUE TITLE
QAST DOCS: Incorporate rsch findings into Manual Functional Testing document (L5)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36917]
# User story

As a VFS team member, I need docs that directly provide info that I'm seeking so that I can efficiently build my VFS app.

As a Content team member, I need to incorporate VFS' pain points from usability sessions into the transformed QAST docs, so that the docs directly provide info that the reader is seeking.

# Tasks
- [ ] Gretchen provide feedback in document
- [ ] Jill review feedback
- [ ] Collaborate with QA team to fill in missing information
- [ ] Jill update doc based on feedback
- [ ] editorial review
- [ ] SME review

# Acceptance criteria
- Liani to fill in

# Reference info
- [QA docs wayfinding and usability research report](https://vfs.atlassian.net/l/c/4BUiVudj)

**Comment by lianilychee** [comment]
closing;from the research we determiined that we should propose a rearranged IA for "performing QA testing" core subtask
