### ISSUE TITLE
GO-LIVE PROCESS: Write Platform-facing guidance for going live (M 3)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#36921]
# User story

As a Platform crew member, I need to clearly understand Content's new twice-weekly deploy policy so that I can appropriately time my documentation updates.

# Tasks

- [ ] Assess/copy existing current instructions
- [ ] Define deployment cadence, escalation procedures (consider notes from table) https://github.com/department-of-veterans-affairs/va.gov-team/issues/36920 
- [ ] Update customer-facing documentation
- [ ] Rewrite Platform-facing guidance

# Acceptance criteria

- Twice-weekly deploy guidance is ready to be broadcast as part of larger socialization plan.
- Old go-live guidance is ready to be deprecated.

# Reference info

**Comment by gmaciolek** [comment]
Today:
- copy current guidance to create draft pages
- start roughing in updated guidance
