### ISSUE TITLE
PagerDuty: downtime for CARMA/10-10CG (Feb25@11pmET-Feb26@3amET)

### ISSUE THREAD

**Issue by RudyOnRails** [department-of-veterans-affairs/va.gov-team#36923]
## Description
Salesforce (which CARMA runs on) is planning a downtime in production around late Feb for a few hours overnight (11pm-3am ET, to be confirmed) where the 10-10CG downstream service will be unavailable.

~~We would like to know the "SOP" for when a service is down and how to gracefully inform the user on the front-end. What utilities are in place to do so already etc.? (show an alert on the 10-10CG form on the frontend.) After reading some older tickets, I see that maintenance windows are entered into PagerDuty, so I am assuming I need to get permission to PagerDuty~~

## Background/context

Original platform request: https://dsva.slack.com/archives/CBU0KDSB1/p1644899024861899

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] I need to understand what is required in order to gracefully show a "downtime" alert on the 10-10CG front end application while Salesforce is down.

## Acceptance Criteria 
- [x] Kevin Musiorski has been informed of the steps to achieve the goal above on both production and staging (we'd like to test).
- [ ] Kevin Musiorski has been given access to the tools to accomplish the steps required to achieve the goal.

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by RudyOnRails** [comment]
@gperlangeli Any help you can provide on next steps for this?

**Comment by SKasimow** [comment]
@RudyOnRails are you able to put points on this ticket?

**Comment by RudyOnRails** [comment]
@SKasimow Unfortunately I can't b/c I don't know what needs to be done. It's a ticket that I was told to create from a Platform Support [request](https://dsva.slack.com/archives/CBU0KDSB1/p1644899024861899) so that they could help us.

@jsgarmon is this something that is easy to do? Create a maintenance window for some planned downtime...

**Comment by jsgarmon** [comment]
@RudyOnRails : is there a Pagerduty alert set up that you know about? I'm not seeing anything specific to 10-10cg or salesforce. I'm not sure what other apps have done, but if you're worried about false alarms, I'd reach out the the console services team. If you're worried about front-end errors for end users, I'd reach out the release tools team.

**Comment by RudyOnRails** [comment]
@jsgarmon I'm new to PagerDuty, don't have access, so not sure. 

We are looking to prepare the va.gov FE for a planned downtime coming to the 10-10CG form because of a salesforce env migration. I thought we would do that through PagerDuty but I must be incorrect in my assumption?

> If you're worried about front-end errors for end users, I'd reach out the release tools team.

This is what we're concerned about. We'd like to get ahead of the problem and try and put the form in sort of a maintenance mode. Should I reach out by opening a Platform Support request on Slack and assign to that team? I don't see a Release Tools team. Sorry for all the newb questions.
<img width="184" alt="Screen Shot 2022-02-23 at 4 39 58 PM" src="https://user-images.githubusercontent.com/1021154/155421479-5fddba8f-1d74-4b1d-975e-9b9d219f0590.png">

**Comment by RudyOnRails** [comment]
@jsgarmon aaaaha, I think I found it. `carma` is the service...

https://github.com/department-of-veterans-affairs/vets-api/blob/9cc3d213e0a8c33bee2e098d9a084f4117ef8784/config/settings.yml#L734

**Comment by jsgarmon** [comment]
Cool, yeah, we can put in a maintenance window for Carma. The Release Tools team is formerly called the Frontend Tools team, so yeah, I think a support request to them would be the next step (they may refer you to the backend tools team/console services, but they're going to know better than I do).

**Comment by RudyOnRails** [comment]
Ok cool, thanks John. i have re-assigned the original Platform Support [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1644899024861899) and will chat with related team.

Sorry to bug ya! (I removed your team's labels too, if I missed any, feel free to clean up).

**Comment by zachclarity** [comment]
@RudyOnRails I added labels to ticket and will see if the BE team can get you access to PagerDuty for an outage window.  @LindseySaari  Do you know how to setup a PagerDuty maintenance window for an existing external service that is already tied into the frontend app’s form config (carma) ?

**Comment by zachclarity** [comment]
@jsgarmon  Do we need another ticket for BE team.  Can they use this one ?

**Comment by zachclarity** [comment]
@LindseySaari  I am unsure if we need a new ticket or we can use this one for approvals.  It seems @jsgarmon  stated we may need a PR to change a setting file .  Let me know what else we need to do in the comments for this ticket.

**Comment by RudyOnRails** [comment]
>  It seems @jsgarmon stated we may need a PR to change a setting file 

@zachclarity can you quote here where you saw this? My understanding is that there should be no PR needed, the pipeline is laid, we just need to add the window to PagerDuty.

@LindseySaari 

### Also, I just received the window for production:
25-Feb-2022 @ 11PM Eastern to 26-Feb-2022 @ 3AM Eastern

Can we also do a staging test of what it would look like?

**Comment by RudyOnRails** [comment]
@SKasimow staging window has been setup for today Feb24, from 3-315pm Eastern so you can test what it looks like.

**Comment by SKasimow** [comment]
@RudyOnRails awesome - I will make a calendar entry to check

**Comment by RudyOnRails** [comment]
Adding John's screenshot from slack thread, for record here
![image (4)](https://user-images.githubusercontent.com/1021154/155560465-7ed193f0-298f-4e6b-bf20-21bd6272b0f2.png)
:

**Comment by RudyOnRails** [comment]
Seeing the test maint. window in staging now: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
![Screen Shot 2022-02-24 at 11 11 00 AM](https://user-images.githubusercontent.com/1021154/155598920-afdf90fc-9c3d-432c-8baa-c99407208702.png)


Closing...
