### ISSUE TITLE
VAMC service location headings

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36933]
## Issue Description
VA health and non-clinical services may be offered at more than one location for a given health system. Service locations can use the same address as the main facility, another location on the campus or an offsite location. 

## Problems to be solved by this design iteration
Separate locations should be visually distinct without relying on additional data from the field
Location name and address already present on the screen should not be duplicated
Heading level hierarchy should be maintained (although can be overridden for visual styles, if needed)

## This work will be done in a series of issues
1. This issue - for maintaining heading level and style
2. Discovery for multiple locations #36934
3. Implementation of design for multiple locations - #36566

## Current behavior
Style appears to be overriding the heading level
`<h4 class="force-small-header" data-template="paragraphs/service_location">Hours</h4> `

Layout: 
```
<!--
  layout: health_care_local_facility.drupal.liquid
  path: pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive
  entityId: 84
-->
```

## Tasks
Reference Nick's [UX Pin design](https://preview.uxpin.com/c53f89d47dcf140eac97df4e70896be4f40877c2#/pages/147451739/documentation/no-panels?mode=i)
**Ensure the following heading levels for location and contact information within a health service accordion**
- [ ] "Contact information" is always H4
- [ ] Facility names, either automatically generated, or manually provided in Drupal, are always H4 
- [ ] "Hours" is always H5, even if no name is provided
- [ ] "Phone" is always H5

## Acceptance Criteria
- [ ] "Contact information" is always H4
- [ ] "Hours" is always H5, even if no name is provided
- [ ] "Phone" is always H5
- [ ] Facility names, either automatically generated, or manually provided in Drupal, are always H4

**Comment by mmiddaugh** [comment]
If anything, this effort should start over with [[DISCOVERY] for multiple VAMC health service locations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36934)
