### ISSUE TITLE
NOD: Update to telephone web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36941]
## Description

Update `<Telephone>` React component to the new `<va-telephone>` web component in the Notice of Disagreement form

## Tasks

- [ ] Replace React component with web component
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
