### ISSUE TITLE
Remove aria-hidden label from VAMC accordions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36947]
## Issue Description
- Content in accordions is invisible to screen readers due to the `aria-hidden=“true”` label. Only phone numbers are announced. This was found in facility level service accordions, specifically. Example page: [Pittsburgh University Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
```
- <!--
  layout: health_care_local_facility.drupal.liquid
  path: pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive
  entityId: 84
-->
```
- Accordion headings are currently H2. This has been observed on facility level, system level and health service pages. 
- Examples 
- Pittsburgh University Drive](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
```
- <!--
  layout: health_care_local_facility.drupal.liquid
  path: pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive
  entityId: 84
-->
```
https://www.va.gov/pittsburgh-health-care/health-services/
```
<!--
  layout: health_services_listing.drupal.liquid
  path: pittsburgh-health-care/health-services
  entityId: 2803
-->
```
https://www.va.gov/pittsburgh-health-care/
```
System level
<!--
  layout: health_care_region_page.drupal.liquid
  path: pittsburgh-health-care
  entityId: 318
-->
```

#### The aria label

For example, the aria label in the [Addiction and substance abuse care](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/) in the Pittsburgh health care system (screenshot below):
<img width="591" alt="image" src="https://user-images.githubusercontent.com/81988788/154345623-cf4f22ab-bbf1-4671-8833-598d3ead87f0.png">

#### The heading wrapping accordions

For example, the H2 around the [Addiction and substance abuse care](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/) accordion in the Pittsburgh health care system (screenshot below):
<img width="587" alt="image" src="https://user-images.githubusercontent.com/81988788/154347070-94fc82fc-fdb8-4feb-9f6c-50ef7d81d3cf.png">

---
## Tasks
- [ ] Remove `aria-hidden=“true”` from accordion components
- [ ] Update accordion heading wrapper to H3
- [ ] Include Josh Kim and Nick in validation of this work

## Acceptance Criteria
- [ ] All content is available to Veterans using screen readers.
- [ ] Content follows consistent heading hierarchy 
- [ ] Once in staging, include Angela in validation

**Comment by joshkimux** [comment]
Confirming that I've validated @GcioNapoleon 's work to remove the `aria-hidden` attribute 👍
