### ISSUE TITLE
NOD/HLR: Prevent JS error

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#36948]
## Description

While testing in staging, a mock user without any address, phone or email will have the value set to `null`. The contact info pages for NOD & HLR both set default parameters which are only assigned when a parameter is `undefined`. Having the value as `null` leads to a JS error and the page not properly rendering

## Tasks

- [ ] Don't use default parameters for contact info data
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
