### ISSUE TITLE
Define Researcher role in the Collaboration Cycle: Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#36956]
## User Stories
As a UX Researcher supporting the Governance team, I want to define my role for the Midpoint Review so that I know how to contribute to future Collaboration Cycle Midpoint Reviews with VFS teams.

As a UX Researcher supporting the Governance team, I want to define dependencies between the Research Plan Review and the Midpoint Review so that I can support VFS teams appropriately and inform the OCTO Research Lead of any concerns.

As a VFS team, I need to know what is expected of me/my team with regards to research at Midpoint Review so that I can ensure my team is prepared and able to meet Platform expectations.

---

## Description
We have worked to establish the UX Researcher role in the Research Plan Review, but we still need to define how research as a practice area will be supported in the other Governance-owned Collaboration Cycle touchpoints, specifically Design Intent, Midpoint Review and/or Staging Review. The scope of this ticket is specifically for the Midpoint Review. The Collaboration Cycle Design Intent and Staging Review will be addressed in other tickets. 

---

## Artifacts Needing Updates
[Platform Website: Collaboration Cycle/Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
[Confluence: Collaboration Cycle/Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Confluence: Collaboration Cycle/How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[GitHub template: Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team%2C+midpoint-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D)

---
## Tasks
- [x] Before you begin any editing of guidance, answer the following questions (copied from [DI ticket](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/36887) and changed for Midpoint Review):
   - Should Collab Cycle team member (aka the UX Researcher) be required to provide feedback tickets on the research practice area at Midpoint Review?
        _A. Yes. If no feedback then mark that on Midpoint review ticket. If new feedback then mark feedback on Research Repo ticket and link it in comment on Midpoint Review ticket_
   - Will we need to request any research artifacts from the VFS team?
        _A. No, teams should already be linking all needed artifacts_
   - What role should research play at this point in the design process?
        _A. If research artifacts haven't been reviewed, now will be the time. If research has been reviewed, look at any changes or if anything additional needs to be brought up_
   - How does the timeline for research align with the timeline for Midpoint Review?
        _A. At this point in the process teams should have research planned, and artifacts ready for review. Some teams may have already gone through the Research Plan Review touchpoint_
   - Should the agenda and/or objective of Midpoint Review be impacted by the addition of research as a practice area?
        _A. A couple of minutes added for any needed research discussion_
   - Will we want to request additional attendees from the VFS team and/or OCTO? for example, Shane?
        _A. Shane agrees to be an optional attendee for MPR_
        _Note from DI ticket: We think Shane should be invited for Midpoint, a time when most teams have prepared for research, but not DI. We should have a conversation with Shane to confirm_
   - Will the outcome of Midpoint Review be impacted by the addition of research as a practice area?
        _A. No. Research Plan Review is a separate touch point, so research is not likely to be a gate for MPR_
   - How do we intend to update the Midpoint Review script to include research?
        _A. Simply adding in that research may provide feedback_
- [x] Create Documentation Drafts of the pages to be edited
- [x] Update the pages as you see fit based off your responses to the above questions
 - ensure you are updating the pages consistently
- [x] When updates are complete, comment on this ticket requesting a peer review

---

## Acceptance Criteria
- [x] GitHub template: Midpoint Review has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#1.-Updating-existing-GitHub-issue-templates)
- [x] Platform Website: Collaboration Cycle/Midpoint Review has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation)
- [x] Confluence: Collaboration Cycle/Midpoint Review - Moderator Responsibilities has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#3.-Updating-existing-Confluence-documentation)
- [x] Confluence: Collaboration Cycle/How to provide feedback for a Midpoint Review [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#3.-Updating-existing-Confluence-documentation)
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@allison0034 Hey Allison, I've added in the artifacts and tasks/AC that I can think of. I copied the majority of the formatting from the Design Intent ticket with some notes where applicable. Let me know if anything doesn't make sense or you need anything else!

**Comment by chaseakirby** [comment]
Moved the Research specific guidance for Midpoint Review into ticket [#37774](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/37774).

**Comment by claytonzook** [comment]
@allison0034 I've updated the questions in the Task section with the answers we discussed. Awaiting confirmation from Shane on his involvement.

**Comment by claytonzook** [comment]
@allison0034 ticket updated with Shane's response. All questions should now be answered.

**Comment by allison0034** [comment]
@chaseakirby @shiragoodman @claytonzook I have updated the following pages to reflect the Midpoint review documentation. Please let me know when this is approved so I can move it live. I will also be adding Shane to the Midpoint review group email.

[Platform Website: Collaboration Cycle/Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2117861379/Allison+-+Copy+of+Midpoint+review2)
[Confluence: Collaboration Cycle/Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2116715171/Allison+-+Copy+of+Midpoint+Review+-+Moderator+Responsibilities)
[Confluence: Collaboration Cycle/How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2116682509/Allison+-+Copy+of+How+to+provide+feedback+for+a+Midpoint+Review)

No updates needed for the GitHub template: Midpoint Review

**Comment by claytonzook** [comment]
Thanks for modifying these documents. Looks good to me!

**Comment by chaseakirby** [comment]
@allison0034 I have reviewed and they look good to me as well!
