### ISSUE TITLE
Notice of Disagreement - Pre-launch modifications

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#36953]
## Issue Description
The Board of appeals has shared feedback based on the most recent demo.

---
## Tasks
- [ ] Remove opt-in checkbox
- [ ] Move data
![Screen Shot 2022-02-15 at 2.17.56 PM.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/9c3cd15b-2b65-4f79-83c9-37a389f2700d)

- [ ] Remove timeframes from Board Review Options Page
![Screen Shot 2022-02-15 at 2.18.19 PM.png](https://images.zenhubusercontent.com/5ffca1cc8ef760e3db881927/670ce13e-9064-4a79-aa4e-3d6a560bf3e5)

## Acceptance Criteria
- [ ] Both changes implemented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
