### ISSUE TITLE
[BE] Return a 401 Unauthorized to the caller if LoROTA returns unauthorized error 

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#36957]
## Description
Currently we don't have a mapping for the 401 Unauthorized returned from LoROTA and hence return a generic 400 error back to frontend. This story will add a mapping to return a 401 unauthorized instead, so that front-end can allow the user to retry or show an appropriate error message.

This error is returned when either the UUID is not found, or the last name or SSN doesn't match the records:
```
:body: '{"error":"lastName does not match with current record"}'
:body: '{"error":"SSN4 does not match with current record"}'
:body: '{"error":"UUID not found"}'
```

## Related Documentation

- Related Spike: #36032

## Tasks
- [x] add a feature flag
- [x] work with product, ux and fe teams to create common understanding
- [x] add mapping in `modules/check_in/config/locales/exceptions.en.yml`
- [x] test locally, codespaces, validate in staging

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by randomsync** [comment]
Wrapped this change behind a feature flag. Here's the response from vets-api when it gets a LoROTA 401 error:

```
{
	"errors": [
		{
			"title": "Authentication Error",
			"detail": "Authentication Error",
			"code": "LOROTA-MAPPED-API_401",
			"status": "401"
		}
	]
}
```
