### ISSUE TITLE
Collaboration Cycle Checklist for Authenticated Experience (My VA) for #31611 My VA Enhancements - Copays

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36963]
## Instructions

<details>

Copy/Paste the below into a new issue to create a checklist of required touchpoints for your project after receiving feedback from your Collab Cycle Kickoff.   The checklist and associated teams are current as of **Nov 3, 2021** based on [VSP's Collab Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
- [Platform website Collab Cycle FAQs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/FAQs.1864073263.html)
- [Collab Cycle Change History](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)
  
### How to Configure This Checklist
Tag with vsa and team name

</details>

---

# Collab Cycle Checklist for My VA Enhancements - Copays

## List your team, project contributors, and reviewers
<details>

_Record key players so you can quickly copy/paste into requests and your product documentation as your project progresses_

### Product Team
- OCTO-DE Product Lead: Samara Strauss
- Product Manager: Heather Justice
- FE Engineer: Taylor Mitchell
- BE Engineer: Lihan Li
- Designer: Angela Agosto
- Researcher: Angela Agosto
- Slack channel: vsa-authd-exp
- GitHub tag: myva-copays

### VFS participants (when applicable):
- Design Lead: Ryan Thurwell
- Design
- Accessibility:
- Analytics:
- IA:
- Content:
- QA:
- Privacy & Security:

</details>

## List project artifacts for requests

<details>

_Link applicable artifacts here so you can quickly copy/paste into requests as your project progresses.  Note that all artifacts may not be needed, depending on nature of the work_
- Project epic #31611
- [Project Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/Copays)
- Product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)) or initiative brief ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/product/initiative-brief-template.md#overview))
- Whiteboard sketch or other lo-fi prototypes or wireframes
- User flows
- Research plan | [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- Conversation guide | **[template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)**
- North Star and KPIs for the product | [How to set](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-protocol.md)
- Authenticated test-user logins, when applicable. **_Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository_**
- Product URL(s)
- Use cases
- Finalized design prototype or mockup
- Content brief
- Regression test plans
- TestRail test cases/test plans
- Technical diagrams (architecture diagram, sequence diagram)
- Any new publicly-exposed endpoints
- Any new interactions with dependent VA backends
- Release plan
- Product guide for contact center

</details>

## Pre-Launch touchpoints linked to VSP reference info + practice areas involved at each step

<details>

- [X] Collaboration Cycle Kickoff  | [#38006](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38006)

- [ ]  Design Intent  | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) | [request template](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/31577) [#issuenum] | _Note: PM must invite own team members._
  - Content [Sitewide Content and IA intake request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) [#issuenum]
  - Design
  - OCTO
  - IA | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) | [#issuenum]

- [ ] Research Plan Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) |  [#issuenum]
  - OCTO

- [ ] Analytics Request | [Overview](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Getting-started-with-Platform-Analytics-&-Insights.1771864128.html) | [Analytics playbook](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-Playbook.1689223169.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - OCTO

- [ ] Midpoint Review | [Overview ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)| [Midpoint Review request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D) [#issuenum]
  - Accessibility | [How to test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md) |  [#issuenum]
  - Content
  - Design
  - OCTO
  - IA
  - QA

- [ ] Staging Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
  - Accessibility [Prep Info](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) | [WGAG 2.1 foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/Slide-decks:-WCAG-2.1-new-success-criteria-and-testing.1777893393.html) [#issuenum]
  - Content
  - Design
  - OCTO
  - IA
  - QA | [Overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-(QA)-testing.1241579982.html)

- [ ] Privacy and Security Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D) |  [#issuenum]

- [ ] Contact Center Review | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) [#issuenum]
    - Contact Center
 
</details>

## Post-Launch Tasks

<details>

- [ ]  Update [Launch Tracker on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/vsa_launch_tracker.md)

- [ ]  Post @here announcement in your Slack channel after launch

- [ ] Full accessibility and 508 office audit | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html) | [Request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=noahgelman%2C+shiragoodman&labels=508%2FAccessibility%2C+vsp-product-support%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D) | [#issuenum]
   - Accessibility

- [ ] Post-Launch Check-in | [Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html) |  [#issuenum]
  - Product

</details>

## Other Resources

<details>

- [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md)

</details>

## Summary of change
<details>
This enhancement to My VA is quite small, however we would like to have support for design and research.  We will be happy to go through any reviews recommended, which should be pretty quick and easy.

- With medical copays information now being available on VA.gov, we would like to pull that information into the My VA dashboard.
- We do not want to create a new section, however we are in the process of determining whether it should be included under the Health care or Benefit payments and debts sections.
- We are also working to determine how much information to display, along with a link to the copays management page, such as:
     - number of copays due
     - amount of copays due
     - simple message of having outstanding copays (no count or amount)

- We are working through discovery now, and plan to start designs in this sprint as well (2/23-3/8)
- [Project folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/Copays) (nothing in there just yet)

</details>

### Kickoff

<details>

Hi @hdjustice. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) 
- [Research plan review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) 
- [Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) 
- [Contact center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) 
- [Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) 
- [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) 

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product
- Research

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the Collaboration Cycle [Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

</details>

# NOTE
- Due to scope reduction - The Collab Cycle will not be required for this change.  This will be a copy change only, and will not require additional governance.

**Comment by hdjustice** [comment]
Due to scope reduction - The Collab Cycle will not be required for this change. This will be a copy change only, and will not require additional governance.
