### ISSUE TITLE
[BE] Return a 403 Forbidden to the caller if LoROTA returns Forbidden error 

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#36971]
## Description
Currently we don't have a mapping for the 403 Forbidden returned from LoROTA and hence return a generic 400 error back to frontend. This story will add a mapping to return a 403 Forbidden instead, so that front-end can allow the user to retry or show an appropriate error message.

This error is returned when data is expired in LoROTA
```
:body: '{"error":"data has expired"}'
```

## Related Documentation

- Related Spike: #36032

## Tasks
- [ ] add a feature flag
- [ ] work with product, ux and fe teams to create common understanding
- [ ] add mapping in `modules/check_in/config/locales/exceptions.en.yml`
- [ ] test locally, codespaces, validate in staging

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by loripusey** [comment]
too old, closing
