### ISSUE TITLE
Rx Shipment Tracking - (613) Martinsburg, WV

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#36976]
- [ ] Confirm facility POC - Sarah Mickanis

- [x] Confirm site uses Endicia or has tracking information in VistA - Endicia

- [ ] Advertise Upcoming Feature

- [ ] Confirm Go-Live Date - 03/01/22

- [ ] Configure/Deploy

- [ ] Training Provided
