### ISSUE TITLE
Content and IA for SAHG from eBenefits

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#36978]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
The Specially Adapted Housing Grant [VA Form 26-4555](https://www.vba.va.gov/pubs/forms/VBA-26-4555-ARE.pdf) allows Veterans with special needs around the home to receive grant money for changes that need to be made. This form needs to be brought into the VA.gov digital experience and be made available quickly and easily.

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-apply-SAHG)
- Link to or attach user flows: [flow](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/GmGW8y7)
- Link to prototype or mockups: [sketch](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/p/5C807B24-B423-4109-9BC4-7230F0E21AEB)
- Link to any epics/issues that may be helpful: [epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/32376)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Jason Wolf
-	Designer: Candy Clark
-	FE engineer: Jerek Shoemaker and Jesse Cohn
-	Product/team Slack channel: [#vsa-ebn-migration](https://dsva.slack.com/archives/CLY6Q69RV)

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
@SgardnerPMP @candy-gcio FYI, this work will require IA as well.

**Comment by mnorthuis** [comment]
@candy-gcio Can you provide some information on timing on this work?  Has it been kicked off with the collaboration cycle, or are you looking to collab prior to that process?

**Comment by candy-gcio** [comment]
Hi, @mnorthuis, we don't have an estimated release date. It has been through design intent, but not midpoint review. I would like to be able to update the wireframes before 4/7 - at least with the suggested content that we want usability tested.

**Comment by bethpottsVADEPO** [comment]
@candy-gcio I will review this tomorrow if I'm not too late already?? Will you have time to make edits?

**Comment by candy-gcio** [comment]
If it's short, I can squeeze them in. :) Either way, I can add a comment to the wireframes so that whoever picks this up can find this ticket!

**Comment by bethpottsVADEPO** [comment]
@candy-gcio I'll try to get you edits only to the intro to the form (the subway map). If I don't get it to you in time, I will handle with the next team.

**Comment by bethpottsVADEPO** [comment]
@candy-gcio I'm going to just turn to this with the next team. No need to be on the edge of your seat today. It was so great working with you!

**Comment by candy-gcio** [comment]
@bethpottsVADEPO Sounds good! I added a comment on the content page wireframe that points to this ticket. It was great working with you, too!
