### ISSUE TITLE
Accessibility Production Review [Facilities Team - VAMC pages]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#36974]
# Steps to complete review

## Before meeting

**VFS Product Manager**
- [x]  ~Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).~
- [x]  ~Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide]~(https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [ ] ~Add the Platform reviewers to scheduled meeting~
- [ ] ~Add Zoom information to scheduled meeting~
- [ ] ~Create feedback tickets and link them to the Staging Review epic~ 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [ ] [~Update Platform Collaboration Point Tracker~](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information

     The Facilities team is requesting accessibility reviews of two pages which can be checked in 
     Production. These pages went through staging reviews prior to release but may have drifted 
     since then. We recently became aware of an accessibility defect (#36947) and decided to make 
     this request to proactively find any other issues of concern. 

     No staging credentials are needed. These pages are unauthenticated. 

     I'm supplying several examples of the two pages, knowing the experience on one location's 
     page may not represent the experience on the same page for another system or facility. 

     **VAMC Facility page**
        - Representative pages are [H. John Heinz III Department of Veterans Affairs Medical Center](https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/) and [Tampa Health services](https://www.va.gov/tampa-health-care/health-services/)

    **VAMC system level pages**
       - Representative pages are [Pittsburgh Health services](https://www.va.gov/pittsburgh-health-care/health-services/), [Bruce B. Downs Boulevard VA Clinic](https://www.va.gov/tampa-health-care/locations/bruce-b-downs-boulevard-va-clinic/) and [Zephyrhills VA Clinic](https://www.va.gov/tampa-health-care/locations/zephyrhills-va-clinic/)

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/front-end-product-brief.md) 
 
  

- [ ] ~Release plan with the "Planning" sections completed~ (_these pages are, and have been, on Production._)

 

### Content artifacts 

- [x] The source of truth for this product is CMS/Drupal.

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [x] List of known issues

• Remove aria-hidden label from VAMC accordions #36947 _This issue needs to be resolved prior to this review. It currently blocks content from being available to screen readers and will be prioritized in the next sprint._ 

## ~Scheduling~

- ~Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)~
- ~Select a date and time and click “Confirm”~
- ~Add your name and email~
- ~Click "Add Guests" and enter the VFS meeting attendees email addresses.~ 
- ~Click Schedule Event~

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by mmiddaugh** [comment]
@joshkimux @AngelaFowler82 we've completed and merged [Remove aria-hidden label from VAMC accordions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36947#) so there shouldn't be a blocker to assessing these pages, when you are able. I will not attach Test rail artifacts unless you need them for this review.
