### ISSUE TITLE
[02/17/22] Add VEText Rx Tracking Promotional Material to Sharepoint

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#36975]
Many users are asking for prescription tracking promotional material as they look to launch the feature for their site. To better serve our users, having pre-existing promotional material Dr. Major has helped craft should be put on our Sharepoint site so it is easily obtained. 

- [ ] Download promotional material from this card
- [ ] Determine a good place for this material to exist for users to download
- [ ] Publish materials to Sharepoint.

![iMessage_iphonesered_portrait.png](https://images.zenhubusercontent.com/613a5fe6c2664a3a7db92373/8a94c019-d17a-4964-98b3-919711467f51)

![2x3 Card-Sticker.png](https://images.zenhubusercontent.com/613a5fe6c2664a3a7db92373/ade60484-d888-4bf5-ab71-d596ada0b018)

https://drive.google.com/file/d/1qY5I3glGf5EPkVzy5NYM-oG2wwS8_oqg/view?usp=sharing

**Comment by lindsay-insco** [comment]
@jwowk uploaded to SP
