### ISSUE TITLE
Create communication plan for VFS Product Owners re: Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#36984]
## User Story
As a Governance team member, I want to ensure that the product owners of VFS teams are made aware of the Platform Orientation process so that new VFS team members can be onboarded/oriented consistently to Platform.

As a Platform OCTO-DE lead, I want to be able to easily communicate to the product owners of VFS teams the importance of Platform Orientation so that new VFS team members can be onboarded/oriented consistently to Platform.

## Description
Governance team has been asked to write a 3-5 sentence blurb that OCTO-DE Platform leadership can share with VFS Product Owners to communicate the importance of Platform Orientation. We are asking for their help to ensure that new VFS team members are following a consistent process.

## Artifacts Needing Updates
N/A

---
## Tasks
- [x] Create 3-5 sentence blurb for Platform OCTO-DE leadership to share with VFS POs

---

## Acceptance Criteria
- [x] User Story need has been fulfilled
- [x] Platform OCTO-DE lead has approved of the proposed blurb
- [ ] Platform OCTO-DE lead/leadership has shared the blurb with VFS Product owners

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [X] **Ensure that story is attached to appropriate Initiative (if not tech debt)** (what body of work is this a part of?)
- [x] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [x] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [x] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
Shared with @mchelen via Slack on 2/15:

> We are asking for OCTO-DE Product Owner assistance in ensuring the [Platform Orientation page of Platform Website](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) is reviewed by new teams and new team members. Platform uses the Platform Orientation process to ensure that new VFS teams/team members are made aware of Platform products, processes, services, standards and expectations so that VFS teams can easily build and maintain products on [VA.gov](http://va.gov/). When VFS team members engage in the Platform Orientation process, they receive proper training on working with Platform and are better prepared to support their own team. In return, Platform is able to capture team information, team member information, and product information so that Platform is better equipped to support the VFS team. As an OCTO-DE Product Owner, please communicate to your teams (and future teams) the Platform Orientation process so that we may continue to orient and onboard new team members consistently.

**Comment by shiragoodman** [comment]
Updated messaging can be found on Confluence: https://vfs.atlassian.net/wiki/spaces/PPST/pages/2106032148/Communication+Plan+for+VFS+POs+re+Platform+Orientation

@mchelen-gov is this ready to close? I am unsure how/where/when you plan to share the messaging with the VFS POs.

**Comment by chaseakirby** [comment]
Closing ticket as message to VFS POs has been created.
