### ISSUE TITLE
BE - Auth Profile - Bad Address Indicator - BE Discovery - Review messaging API documents, estimate effort

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37000]
## Background
As part of the Bad Address Indicator enhancement to the VA.gov Profile, we want to proactively send email notifications to Veterans whose current mailing address has been flagged as being invalid for that individual.   This email is meant to notify them about their address and direct them to the VA.gov web site to log in and update their address.

The [VA Notify](https://dsva.slack.com/archives/C010R6AUPHT/p1644945119279509) team has an API for sending bulk emails, and the Swagger documentation is located at [https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml)  Additional information may be found at [https://github.com/department-of-veterans-affairs/notification-api/blob/master/README.md](https://github.com/department-of-veterans-affairs/notification-api/blob/master/README.md)

## Tasks
- [x] Review the VA Notify API Documentation
- [ ] Determine the process/format for adding the following pieces of information to an email: 
   - [x] Veteran's name (First and Last)
   - [ ] URL for logging into VA.gov Profile
   - [ ] Email subject line (including whether we are able to include the recipient's name)
   - [ ] Email body content (including whether we are able to use variables to insert recipient details within the body)
- [ ] Determine any API batch parameters we need to set (number of messages per batch, hour, etc.)
- [ ] Determine any limits we need to adhere to (x messages per hour, day, etc.)

## Acceptance Criteria
- [x] Review VA Notify API documentation
- [ ] Determine answers to above items
- [ ] Document answers to above items as part of technical documentation

**Comment by tpharrison** [comment]
Discussion and Questions:

- https://dsva.slack.com/archives/C010R6AUPHT/p1644945119279509
- Will the system be passing in a list of email addresses or, profile ids for us to get the email address from VA Profile?
- Exactly what can we pass from VA Profile --> VANotify to let them know to whom a bad address email should be sent?

**Comment by MarciMcGuireGCIO** [comment]
Noting that Melanie Jones will be granting us access to the UI for VA Notify.  [GitHub ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-infra/336) (in Infrastructure workspace)

**Comment by MarciMcGuireGCIO** [comment]
Thanks @tpharrison !

**Comment by SKasimow** [comment]
Per discussion with @tpharrison , closing this and consolidating with ticket #38583
