### ISSUE TITLE
[SW-Content] Update 2 links on Fry Scholarship page [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37008]
## Story
As a f

## Resources
[Fry Scholarship page](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/)

## Task
- [x] Update "Read about DIC" ULR/Links to the modern page. 

## Acceptance Criteria
- [x] Links are updated and tested.  
- [x] Stakeholder has approved for publishing

**Comment by RLHecht** [comment]
@lunascoop This one is an easy one. The 2 links in the featured content box that are talking about DIC should go directly to our page instead of being redirected there.

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Fry Scholarships: http://preview-prod.vfs.va.gov/preview?nodeId=951

**Comment by RLHecht** [comment]
Thanks, @lunascoop ! I reviewed and published this. Moving to validate.
