### ISSUE TITLE
Migrate from Vets API to Facilities API

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3702]
## User Story:
As the Facility Locator team, we want to migrate from the Vets API to the Facilities API so that we can ensure timely and accurate data is available to our users. 

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Zero loss of data when compared to Vets-API
- [ ] Zero latency issues when compared to Vets-API

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Migrate VHA facility data - w hour(s) - Owner
- [ ] Migrate VBA facility data - x hour(s) - Owner
- [ ] Migrate NCA facility data- y hour(s) - Owner
- [ ] Migrate Vet Center data - z hours - Owner

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
