### ISSUE TITLE
vets-api k8s db migrations

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#37026]
## Description

This ticket provides details that we will need to add initContainers to the specification to run database migrations for the vets-api k8s offering. Currently, the k8s offering AND the current BRD/EC2 offering both use the same db instance. We will want to think about adding the db migration task to initContainers once we fully switch over to the k8s offering. We need to run migrations as part of the k8s deployment process to ensure that the db is up to date.

## Tasks 
- [x] Discover any overlap between the BRD and K8s deployments 
- [x] Compare the to Databases
- [x] Write the k8s specifications for the migrations 

### Other notes:

- Discussed during the meeting on 6/10, we may be able to run migrations via a sidecar strategy.
- ArgoCD uses Presync jobs to run schema migrations. This replaces the need to use initContainers. https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/
- Helm charts use pre-install jobs to run commands on pods before new application version is install in the new pods. https://helm.sh/docs/topics/charts_hooks/
- Migrations are rarely needed. It the past, there have been only around 2 migrations per month. Throughout AB testing, when a migration needs to be ran, the PR will be merged during low traffic times. This will allow the migration to be ran concurrently in both setups to prevent any migration errors. 

## Definition of Done
- [x] Define an initiContainers or a preSync job spec to run migrations in the k8s deployment manifest - [PreSync Hook PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/792) 
- [ ] Create Github tag to prevent migrations from merging into master until traffic is at an all time low.
- [x] Verify that migrations run successfully in k8s

**Comment by LindseySaari** [comment]
Note for whoever does work on this later:

We kept getting an error
```
40
Errno::EISDIR: Is a directory @ io_fread - /app/config/settings.local.yml
```

[This line](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L32-L33) sets config to an {} empty dir

We may need to do something like the following to resolve the directory error:
```
            - name: settings-configmap
              mountPath: /config_src
            # target directory mount point; the final config file will be created here
            - name: config
              mountPath: /config
            - name: config
              mountPath: /app/config/settings.local.yml
              subPath: settings.local.yml
```

**Comment by jhouse-solvd** [comment]
@LindseySaari & @jbritt1 - Do either of you know if this is a blocker to completing the initiative to make Vets-API operational in EKS dev?

**Comment by jbritt1** [comment]
It is definitely something that needs to get figured out sooner than later in my opinion. So with that, I would almost treat it as a blocker even if it doesn't fit the traditional definition of one.

**Comment by jhouse-solvd** [comment]
As Lindsey noted above, we recently discussed the need for this capability and plan to develop a solution in the near future. 

However, I'm detaching this from the initiative to 'make Vets-API operational in EKS dev' as that initiative relates to infrastructure operations only.

**Comment by npeterson54** [comment]
We may  need to add https://github.com/ankane/strong_migrations

**Comment by RachalCassity** [comment]
https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/

**Comment by RachalCassity** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/2146140164/Keep+EKS-Deployed+Vets-API+Up+to+Date+with+BRD-Deployed+Vets-API
