### ISSUE TITLE
FE - Auth Profile - Personal Information Revision - Revise Read-Only State for mutliselects

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37040]
## Background

We need to update the data to display all the multiselect options appropriately

## Tasks
- [x] Reformat from single item to multi-item with commas as needed when displaying in UI

## Acceptance Criteria
- [x] Reformat from single item to multi-item with commas as needed when displaying in UI
- [x] Update End to End test to validate

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
I updated the code to reflect the multi-select data now for all these fields. We can't really validate per say on staging since the api is not ready to give us this data, but I do have local mock data that is provided to simulate multiple answers, so this is what the read only state looks like for gender identity as an example.

![Screen Shot 2022-02-22 at 2 02 00 PM](https://user-images.githubusercontent.com/8332986/155219064-7548ce28-20cd-4f85-bf03-281d39546ab0.png)

@MarciMcGuireGCIO not sure if that would be good enough to validate on your end, or if you would like some other way to validate the UI appearance.

**Comment by adamwhitlock1** [comment]
I did realize that I do still slightly need to reformat the 'prefer not to answer' to display without the (unchecks other options) during the read only state, so this will need a little additional work.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @adamwhitlock1!  Looks good to me formatting-wise.  We'll have other opportunities to review the data once the BE is hooked up, so this looks ready to close to me.  cc @Samara-Strauss @tpharrison @cgednalske

**Comment by Samara-Strauss** [comment]
I have a small request -- can we use a semicolon between list options instead of a comma? Or would that be annoying/not within the style guidelines? It would make the separation between answers clearer.

Not a requirement, just a request. Let me know if you plan to move forward with this or not. If not, feel free to close again.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss seems reasonable.   @adamwhitlock1 - do you mind making that change when you are able?  Thanks!

**Comment by adamwhitlock1** [comment]
Yes, @Samara-Strauss I can totally make that change. I'll put together a PR for that here shortly

**Comment by Samara-Strauss** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 once you've made that change, can you please drop another screen shot in here w/the semicolon change?  Once we have a peek at that we'll be ready to close this out.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
It's beautiful! 😭 Thank you, @adamwhitlock1 !  @Samara-Strauss LMK when you've had a chance to review and I'll close out this ticket.  @adamwhitlock1  - good point - I'll add that to the "add final content to mockups" ticket.

**Comment by Samara-Strauss** [comment]
Great! Feel free to close.
