### ISSUE TITLE
Add Global Comparions to Medallia Dashboard

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#37048]
## Issue Description
To help product owners better understand how their products are performing, we wish to add a "global VA" segment to benchmark products against.

---
## Tasks
- [ ] Create a Global VA segment for task completion percentage
- [ ] Create a Global VA segment for satisfaction (feedback)
- [ ] Create a Global VA segment for satisfaction (A11)

## Acceptance Criteria
- [ ] Have all the above segments been created?
- [ ] Do all the above segments filter properly?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
