### ISSUE TITLE
FE [Discovery] - Auth Profile - Determine tasks needed to complete 508 issue #19618

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37041]
## Background
#19618 is a 508 issue found in Staging review for Notification Preferences.  This issue needs to be evaluated and broken into further tasks for remediation

## Tasks
- [ ] Review #19618 and determine tasks needed to remediate
- [ ] Work with PM to create new issues and estimate

## Acceptance Criteria
- [ ] Review #19618 and determine tasks needed to remediate
- [ ] Work with PM to create new issues and estimate

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
[Adam's ideas for next steps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/engineering-docs/19618-ProfileInfoTable-sematic-list-layout-notes.md)

Approach has not been decided, but potential work for this could go three sprints (not entirely full time) as follows:

- Sprint 1: Roll the update out to one section of the profile; Validate with accessibility; Address concerns
- Sprint 2: Roll out to other sections of the profile
- Sprint 3: Code cleanup; Any bug fixes; Remove feature toggle(s)

Adam will meet with Allison soon to finalize approach. Once you all decide on approach, let's start creating tickets so we can get work ready to go for next sprint (Sprint 4: 2/15/23).

**Comment by adamwhitlock1** [comment]
I created 3 tickets for the initial work on this. After meeting with Allison, we decided to migrate to a new component over time, and a first MVP could be created for one of the more minor sections that displays just info, like the direct deposit page's payment history section.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/53630

https://github.com/department-of-veterans-affairs/va.gov-team/issues/53631

https://github.com/department-of-veterans-affairs/va.gov-team/issues/53632

These tickets can be refined further, and expanded upon, but the core acceptance criteria and basic descriptions are ready for grooming.
