### ISSUE TITLE
NOD:  Update contact info Cypress test

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37050]
## Description

The Notice of Disagreement form contact info page utilizes a list loop pattern with the profile team's inline editing component. The Cypress e2e test specifically for this page only tests the "Cancel" button function and needs to be updated to test the "Update" button functionality. Multiple mock API calls will need to be included

## Tasks

- [ ] Add Cypress e2e tests for contact info phone, email and address updating

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
- [ ] Notify QA of this update
