### ISSUE TITLE
(Samara) Draft instructions for FAQs (it’s in the template, but should be captured in style guide)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#37064]
### User Story
As a Platform team member,
I need to understand how to format FAQs in Confluence,
so that I can write content that follows the Platform website best practices and is easy for VFS team members to understand.

As a Platform content team member,
I need to understand how to guide other Platform teams to format Frequently Asked Questions (FAQs) in Confluence,
so that I can document this in the existing Platform website style guide.

### Examples
Existing pages with FAQs:
- https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval
- https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list
- https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs

### Tasks

- [x] Research the Confluence formatting used n the pages above for FAQs
- [x] Share the information with the rest of the team
- [x] Document steps to format FAQs for the style guide

**Comment by andreahewitt-odd** [comment]
@vbellissimo dig a bit deeper into this

**Comment by SSimmorins** [comment]
The goal of this ticket is to draft up instructions on how to include the FAQ macro.
