### ISSUE TITLE
Define pattern for cross-linking to other docs within the Platform website

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#37065]
### User Story
As a Platform team member,
I need to understand how to format cross-linking references in Confluence,
so that I can write content that follows the Platform website best practices and is easy for VFS team members to understand.

As a Platform content team member,
I need to understand how to guide other Platform teams to format cross-linking references within the Platform website,
so that I can document this in the existing Platform website style guide.

### Examples

- Existing page with cross-linking: https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-Pull-Requests-for-VSP-Engineering-Review.655032351.html
- Example from a Google page: https://developers.google.com/style/cross-references

### Tasks

- [ ] Research the Confluence formatting used on the page above for cross-linking
- [ ] Document steps to format cross-linking for the style guide; use the Google instructions as inspiration if needed.
- [ ] Share the information with the rest of the team

### Acceptance Criteria

- [x] All tasks completed

**Comment by andreahewitt-odd** [comment]
Reviewed on 7/21 and decided this is still relevant

**Comment by johnny-jesensky-adhoc** [comment]
As part of the icebox[ audit ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69802) in Sprint 41, moving this from the icebox to the backlog. Needs an additional level of refinement.

**Comment by jknipes** [comment]
@BSmolensky would you agree the most up-to-date information for this is reflected in the current style guide?

**Comment by BSmolensky** [comment]
@jknipes - I would. For reference here in the comments, here is [a link to the cross-reference and links section of our style guide. ](https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Cross-references-and-links)

**Comment by BSmolensky** [comment]
That section of the style guide has been updated several times since this ticket was first created (2022). So, yes, our style guide's Cross referencing and linking section is up-to-date and should provide the ticket originator with the information they require.

**Comment by jknipes** [comment]
@lianilychee please see the previous comments, we are closing this ticket as _Done_
