### ISSUE TITLE
Migrate VHA Facility data endpoint to Facilities API

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3707]
### Problem Statement
How might we migrate the VHA Facility Data Endpoint to the official Lighthouse Facilities API from unofficial beta we currently use on Vets-API?

This may include Vet Center data [#3716]

https://developer.va.gov/explore/facilities/docs/facilities?version=current

## Goal
_What outcome(s) do we want to see?_
- [ ] Utilize the official Lighthouse Facilities API for VHA Facilities in Facility Locator
- [ ] Zero loss of front-end display data
- [ ] At least status-quo on performance if not improvement on performance for searches

## Objectives or Key Results this is meant to further
- Utilize official Lighthouse API system rather than unofficial, not enhance-able API.

## Tasks
[ ] Document data currently available via Vets api to establish baseline
[ ] Document data available using Facilities API to anticipate differences
[ ] Front end api key tasks needed to switch over to Lighthouse
[ ] Work with Lighthouse API team to identify method for rerunning job

## Acceptance Criteria
[ ]  Facility Locator uses Lighthouse API, rather than vets API to return VHA data from wds

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@darkbushido @davidconlon please help me to outline the tasks related to this work
Lance, please estimate the hours needed for each task and any other teams that we will need to coordinate this switch

**Comment by mmiddaugh** [comment]
@darkbushido note: Vet Centers are under the VHA umbrella and **may** be included in the VHA API. #3716 can be used as the issue for Vet Center migration if they need to be done separately.

**Comment by mmiddaugh** [comment]
Discovery showed this is front end effort only.

**Comment by mmiddaugh** [comment]
Will be addressed by [#8721] and [#8720]
