### ISSUE TITLE
eGain Accessibility Audit

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37074]
## Issue Description
Collaboration Cycle team has been asked to complete an accessibility audit for the eGain live chat product owned by VHA. They would like to make eGain available through the VA.gov 10-10EZ application. Before eGain can be integrated into VA.gov, we must determine if it meets the standards of VA.gov as defined by the [VA.gov Experience Standards. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

---
## Tasks
- [ ] Complete accessibility audit
- [ ] Log all launch-blocking issues identified
- [ ] Stop audit if launch-blocking issues exceed 5 issues

## Acceptance Criteria
- [ ] OCTO-DE has enough data to communicate to VHA if eGain meets or does not meet the accessibility standards for VA.gov

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by artsymartha68** [comment]
Wondering if it's safe to close/archive all these issues...? Since I don't think we'll be addressing them anytime and they add 8 open defects to the pending a11y work.

**Comment by shiragoodman** [comment]
@artsymartha68 I think it's safe to close. It has the eGain label, as well as our team's labels and the collab cycle label, so we should be able to find again if needed.

Closing now!
