### ISSUE TITLE
Investigate/Fix Innocuous Warning messages for Local Vets-Api Setup

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#37081]
## Issue Description
When you running Vets-API locally we get sidekiq innocuous warning messages.   A description is found here.  https://stackoverflow.com/questions/70983620/redis-gem-4-6-0-multi-pipeline-commands-warnings-in-sidekiq-logs

---
## Tasks
- [ ] Investigate how to stop the warnings if possible
- [ ] Fix issue or update Readme documentation with explanation

## Acceptance Criteria
- [ ] Warning messages removed or documentation added to Readme to ignore.

**Comment by zachclarity** [comment]
@LindseySaari  --- Full log. note the warning repeats:

make up
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Creating vets-api_vets-api_run ... done
No credentials found to install Sidekiq Enterprise. This is fine for local development but you may not check in this Gemfile.lock with any Sidekiq gems removed. The README file in this directory contains more information.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
The Gemfile's dependencies are satisfied
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/config/initializers/01_redis.rb:29:in `<main>')
[DEPRECATION] Rack::Attack.throttled_response is deprecated. Please use Rack::Attack.throttled_responder instead
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
Running via Spring preloader in process 46
Database 'vets_api_development' already exists
Database 'vets_api_test' already exists
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Creating vets-api_vets-api_run ... done
No credentials found to install Sidekiq Enterprise. This is fine for local development but you may not check in this Gemfile.lock with any Sidekiq gems removed. The README file in this directory contains more information.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
The Gemfile's dependencies are satisfied
18:58:21 web.1       | started with pid 11
18:58:21 job.1       | started with pid 12
18:58:25 web.1       | Puma starting in single mode...
18:58:25 web.1       | * Puma version: 5.6.0 (ruby 2.7.4-p191) ("Birdie's Version")
18:58:25 web.1       | *  Min threads: 16
18:58:25 web.1       | *  Max threads: 16
18:58:25 web.1       | *  Environment: development
18:58:25 web.1       | *          PID: 11
18:58:26 web.1       | No credentials found to install Sidekiq Enterprise. This is fine for local development but you may not check in this Gemfile.lock with any Sidekiq gems removed. The README file in this directory contains more information.
18:58:26 job.1       | No credentials found to install Sidekiq Enterprise. This is fine for local development but you may not check in this Gemfile.lock with any Sidekiq gems removed. The README file in this directory contains more information.
18:58:27 web.1       | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
18:58:27 job.1       | The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
18:59:03 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/config/initializers/01_redis.rb:29:in `<main>')
18:59:03 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/config/initializers/01_redis.rb:29:in `<main>')
18:59:04 web.1       | [DEPRECATION] Rack::Attack.throttled_response is deprecated. Please use Rack::Attack.throttled_responder instead
18:59:04 job.1       | [DEPRECATION] Rack::Attack.throttled_response is deprecated. Please use Rack::Attack.throttled_responder instead
18:59:06 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:06 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:13 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:13 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:16 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:16 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:17 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:17 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:17 web.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:17 job.1       | `Redis.current=` is deprecated and will be removed in 5.0. (called from: /srv/vets-api/src/lib/common/models/redis_store.rb:21:in `redis_store')
18:59:18 web.1       | * Listening on http://0.0.0.0:3000
18:59:19 web.1       | Use Ctrl-C to stop
18:59:19 job.1       | Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
18:59:19 job.1       | 
18:59:19 job.1       | redis.pipelined do
18:59:19 job.1       |   redis.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | should be replaced by
18:59:19 job.1       | 
18:59:19 job.1       | redis.pipelined do |pipeline|
18:59:19 job.1       |   pipeline.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | (called from /usr/local/bundle/gems/sidekiq-scheduler-3.1.1/lib/sidekiq-scheduler/redis_manager.rb:140:in `block in register_job_instance'}
18:59:19 job.1       | Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
18:59:19 job.1       | 
18:59:19 job.1       | redis.pipelined do
18:59:19 job.1       |   redis.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | should be replaced by
18:59:19 job.1       | 
18:59:19 job.1       | redis.pipelined do |pipeline|
18:59:19 job.1       |   pipeline.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | (called from /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:192:in `block in raw_push'}
18:59:19 job.1       | Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
18:59:19 job.1       | 
18:59:19 job.1       | redis.multi do
18:59:19 job.1       |   redis.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | should be replaced by
18:59:19 job.1       | 
18:59:19 job.1       | redis.multi do |pipeline|
18:59:19 job.1       |   pipeline.get("key")
18:59:19 job.1       | end
18:59:19 job.1       | 
18:59:19 job.1       | (called from /usr/local/bundle/gems/sidekiq-6.4.0/lib/sidekiq/lau

**Comment by LindseySaari** [comment]
It also appears that Redis.current is being deprecated. Some [solutions are offered here](https://github.com/redis/redis-rb/issues/1064) but there isn't an accepted solution at the moment

**Comment by thilton-oddball** [comment]
Sidekiq has been updated and any of the messages related to that should no longer be an issue.
