### ISSUE TITLE
Setup Aha! - Github integration

### ISSUE THREAD

**Issue by deirdreclarke** [department-of-veterans-affairs/va.gov-team#37090]
## Description
I am trialing a new roadmapping tool (Aha!) with Leanna Miller for the Flagship Mobile product. We would like to setup an integration between Aha! and the Github repo that the Mobile team uses. 

## Background/context 
Aha security is all documented here: https://www.aha.io/legal/security

## Technical notes
You can read more about the integration here: https://www.aha.io/product/integrations/github
We would need an integration setup between Aha! and this repository: https://github.com/department-of-veterans-affairs/va-mobile-app

---
## Tasks
- [ ] You need to be a workspace owner in Aha! and have the ability to create records in the GitHub project you want to integrate with. (Let us know who that would be and we can add that person to Aha! with the right permissions)
- [ ] There are two key steps to set up an integration. First, you will need to authenticate your GitHub account in Aha! and configure your mappings. Then, you will need to add a webhook in GitHub. For more detailed instructions, read our [support documentation](https://www.aha.io/support/roadmaps/integrations/github). 

## Acceptance Criteria 
- [ ] We can access the Mobile app Github repository from Aha! such that the data for issues can flow two-way.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by little-oddball** [comment]
Determined STALE request from 9 months ago.
