### ISSUE TITLE
Analytics Team Roadmap

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#371]
## High Level User Story
As a VSP stakeholder, I need to understand the Analytics & Insights team's priorities for planning purposes.

## Goals
Roadmap created with high-level operations tasks, including VFS team analytics support, dashboard MVP, call center data aggregation, and a prioritization between them.

## Objectives
* Enable agile VFS Team delivery of performant applications

## AC
- [x] Prioritization Presentation Created
- [x] Prioritization Workshop Conducted
- [x] Roadmap with Themes Created
- [x] Priorization shared with VSP

## Definition of Done
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Epic`**

**Comment by joanneesteban** [comment]
All AC met. Insights roadmap was created and shared.
