### ISSUE TITLE
Migrate Vet Center Facilities data endpoint to Facilities API

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#3716]
### Problem Statement
How might we migrate the Vet Center Facilities Data Endpoint to the official Lighthouse Facilities API from unofficial beta we currently use on Vets-API?

This work may be done with VHA effort in [#3707]

https://developer.va.gov/explore/facilities/docs/facilities?version=current

## Goal
_What outcome(s) do we want to see?_
- [ ] Utilize the official Lighthouse Facilities API for Vet Center Facilities in Facility Locator
- [ ] Zero loss of front-end display data
- [ ] At least status-quo on performance if not improvement on performance for searches

## Objectives or Key Results this is meant to further
- Utilize official Lighthouse API system rather than unofficial, not enhance-able API.

## Tasks
[ ] TBD: front end api key

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@mmiddaugh to add tasks based on [#3707]

**Comment by mmiddaugh** [comment]
Discovery [#6497] showed this is front end effort only since both Vets API and Facilities API use same end point and data source. This work now will be done from the front end api key.

From Patrick Vinograd

> Right now VA is collectively maintaining two similar facilities APIs - so there’s duplicated effort, risk of them getting out of sync, etc. By VA.gov using the lighthouse facilities API, VA can collectively consolidate down to one and reduce maintenance effort.
> They never really should have been forked from one another, it was an expedience that was done at the outset of the lighthouse program to minimize disruption to the (then) Vets.gov project

Returning this issue to the backlog for re-prioritization

**Comment by mmiddaugh** [comment]
Will be addressed by [#8721] and [#8720]
