### ISSUE TITLE
Claims & Appeals Documentation

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#37209]
# VSA Claims & Appeals product transition doc

<br>

>**Team transition document | March 2022**
>
> The purpose of this transition document is to outline the current state of Claims & Appeals product development. It serves as a "front door" to documentation and resources collected during the course of product design and development. Included are links to more specific transition hubs where you can find direct links to resources and references used during design and development.

<br>

## Table of Contents
[Product context (PM)](#product-context)

[Product portfolio (PM)](#product-portfolio)

[Product approach (Team)](#product-approach)

[VA relationships (Team)](#va-relationships)

## Product context 
As a Veteran, I want to easily discover, apply for, track, and manage my disability compensation claims on va.gov so that I can have a personalized, guided experiences that provides me access to vital information about VA benefits and services I deserve.

### Artifacts
- [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/README.md)
- [Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/product-roadmap.md)
- [Weekly Meeting Minutes](https://salientcrgt-my.sharepoint.com/:w:/r/personal/ronnie_henry_gcio_com/_layouts/15/Doc.aspx?sourcedoc=%7B244AA365-EE2F-31D9-CF65-E9176D42F70F%7D&file=Claims%20%26%20Appeals%20Weekly%20Product%20Sync.docx&action=default&mobileredirect=true&cid=fdd2aa58-c8f4-4a63-8908-d8152ded4e80)

### Research and design
- [Research and design hub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/design/readme.md)

### Engineering
- [Frontend Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/team-transition-document-03-2022.md)
- [526 Product Flowchart](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34819)
- [Documentation]()

<br>

## Product portfolio

<br>

### Original Claims 526
This product allows Veterans to file original disability claims

- [[Product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez)]
- [[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/21-526ez.md)]
- [Analytics dashboard]() ([Domo](https://va-gov.domo.com/page/447193050) or [Google Analytics](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210201&_u.date01=20210228&explorer-table.filter=www.va.gov~2Fdisability~2Ffile-disability-claim-form-21-526ez&explorer-table.plotKeys=%5B%5D/))
- [[Staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-claims.md) ]

#### Now/Next/Later Roadmap
Product was originally developed 3 years ago. Several iterations have been completed. Summary of direction:
Claims (Stakeholders: Paul Shute / Alejandro Mendioaflores)
- [ ] [Original Claims - Form 526EZ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez)

- Update to new web component ([#36943](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36943))
- Item index ([#13642](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13642))
- Failed submission PDF generation - after EVSS implementation ([#33314](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33314))
- Incorporate additional flashes ([#30920](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30920))
- Date of birth error messaging ([#27909](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27909))
- Page reorder ([#36028](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36028))

- [ ] [Benefits Delivery at Discharge](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd) (sub-form of 526, [Meeting Minutes)](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B730BEEE0-79BC-4550-8805-22EFD1EA8253%7D&file=BDD%20Bi-Weekly%20Check-in.docx&action=default&mobileredirect=true&cid=b3b77ed6-6e74-48f4-a45a-ffde8410d8df)

### Claim Status
- [ ] [Claim Status Tool](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/README.md)
- Full product redesign was planned
- Implementation & Review of all in this ticket ([#36383](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36383))

### Decision Reviews
- [ ] [Notice of Disagreement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md) - Stakeholder: Board of Appeals, 
- Awaiting go-no go decision for launch

- [ ] [Higher Level Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/README.md) - Stakeholder: Lauren Sylvia
- Phased launch complete at 100% 2-24-22
- Usability testing for v2 ([#36572](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36572) 
- VSO question implementation ([#36135](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36135))
- [ ] Supplemental Claims (Not Developed)
- Plan was to begin research and development during Quarter 2

### Others (Not under active development)
- [ ] [Letters](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/benefit-letters)
- Technical Discovery ([#28846](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28846))
- [ ] [Pre-Need Burial](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/burials-memorials/pre-need) 
- Privacy modal ([#27577](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27577))
- 
<br>

### Contacts

- Matt Self | matthew.self2@va.gov -- Product owner
- Paul Shute | paul.shute@va.gov -- Stakeholder: 526, BDD, CST
- Alejandro Mendiolaflores | alejandro.mendiolaflores@va.gov -- Stakeholder (Paul Shute backup)
- Nina Tann | nina.tann@va.gov -- Stakeholder: Notice of Disagreement
- Lauren Sylvia | lauren.sylvia@va.gov -- Stakeholder: Higher Level Review

### Meetings

- Daily Stand-up / Slack-up
   - Daily checkin
   - Zoom M & F, Slack T-TH
- [BDD Checkin](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B730BEEE0-79BC-4550-8805-22EFD1EA8253%7D&file=BDD%20Bi-Weekly%20Check-in.docx&action=default&mobileredirect=true&cid=b3b77ed6-6e74-48f4-a45a-ffde8410d8df)
   - Discuss issues relating to Benefits Delivery at Discharge
   - bi-weekly
- Lighthouse Check in (led by Kelly Lein: kelly.lein@va.gov)
   - Discuss backend & endpoint issues
   - bi-weekly

---

**Comment by Mottie** [comment]
Here is my front end to-do list for the new owners. It's still a work-in-progress and I may get to some items before the contract ends:

## Claims

- [ ] 526 - release subforms 8940 & 4192 once ready (`subform_8940_4192` feature)
- [ ] 526 - update code & remove `evss_upload_limit_150mb` feature flag
- [ ] 526 - update code & remove `show526_wizard` feature (moves wizard from
      intro page to `/start`)
- [ ] 526 - Look into lots of "Tier 3" issues in va.gov-team repo
- [ ] 526 - Fix typo in schema across 2 repos (#29394)

- [ ] CST: Fix linting issues (#36054) - remaining linting issues require
      design/UX review since they are links that should be buttons; but we can't
      view all those pages without an appropriate test user, nor can we add a
      link style to a button (no longer allowed)
- [ ] CST: Remove eBenefit links? (#21207)

## Decision reviews

- [ ] HLR - move entire app to `src/applications/appeals` folder, since it's an
      appeal and doesn't belong in `disability-benefits`
- [ ] HLR - create `minimal-test-v2.json` for e2e testing
- [ ] HLR - remove v1 code, data and `hlr_v2` feature flag (once HLR v2 is at 100%)
- [ ] HLR - add all benefit types (#37470)
- [ ] HLR & NOD - Update `hlr-contact-loop.cypress.spec.js` and
     `10182-contact-loop.cypress.spec.js` so contact "update"
      test works (coordinate with authenticated experience team) - see
      [tech docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_details.md#contact-loop-testing)
- [ ] HLR & NOD - Update area of disagreement page to be a custom page and use
      the checkbox group component - see [tech docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_details.md#area-of-disagreement-grouped-checkboxes)

- [ ] NOD - release NOD when Board is ready (`form10182_nod` feature)

## Others

- [ ] Pre-need: Use OMB info on intro page (related #27577)
- [ ] Pre-need: Update content in privacy statment modal (#27577)
- [ ] Pre-need: Make cemetary autocomplete work locally & in staging
- [ ] Pre-need: Prefill telephone & email
- [ ] Pre-need: Fix review & submit accordion style
- [ ] Pre-need: Follow up support https://github.com/department-of-veterans-affairs/va.gov-team/issues/36030
- [ ] Letters: Not enough info (#21066)

**Comment by Mottie** [comment]
Added the template to our team folder: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials/team-transition-document-03-2022.md
