### ISSUE TITLE
Access to staging test user data file in GitHub

### ISSUE THREAD

**Issue by its-mwalker** [department-of-veterans-affairs/va.gov-team#37210]
## Description
I am the lead for EVSS integrating with VA.gov to share the sign-in page. In order to test this I need access to the staging test users found at https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv.

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 
EVSS is adopting the VA.gov sign in page as part of alarger effort to enable single sign on and consistent login options across VA applications. We  have been working with Cody Reinold on this and are ready for testing in staging. To support this we need working ID.me test users ( and other credentials as well.)

## Technical notes
EVSS sign in page has been created at https://XXX.va.gov/sign-in/?application=ebenefits&to=profilepostauth for dev, staging and Production. EVSS will point to this and validate user login and single sign on functionaltiy.

---
## Tasks
- [ ]  Grant github user "its-mwalker" access to the restricted resource found at https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv.

## Acceptance Criteria 
- [ ] User has access to this specified document in GitHub.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@zachclarity - Please contact #github-admins in DSVA Slack to request that the user be added to the va gov team sensitive repo.

**Comment by little-oddball** [comment]
Determined STALE request from 9 months ago. Please re-open and update if still needed.
