### ISSUE TITLE
Retry VRE/1900 jobs that fail due to VBMS (trying to avoid CMP)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37217]
``` diff
- be sure to check in with them BEFORE deployment
```

## Background
We need to be able to determine when there is an issue with VBMS so that we can give its submission another chance.

VRE would prefer the 29-1900 submissions to not land in Central Mail as often, so when VBMS returns an error due to their infrastructure being unstable, retry the job a few times before sending to Central Mail (right away).

## Considerations
- Let's check and see if there is a **maintenance error** and/or a **bad gateway** and if there is, we give it some time, like 3 hours.
- Lets see if we can infer what their down time is
- Ask VBMs what their downtime is (Jason to ask Liz)
**Nevermind: Downtime is all over the place**

## Tasks
- [x] Allow the main 1900 job to retry if VBMS raises errors

## Acceptance Criteria
- [x] The main 1900 job retries in a few different ways before sending to CMP
- [x] A PR has been requested for merging

**Comment by jason-gcio** [comment]
@lihanli - here is the ticket for what Kevin was working on, thanks for helping with this.  It should be pretty straightforward.

**Comment by RudyOnRails** [comment]
@lihanli Hey Lihan. I think I finished it, but if you could take a look and bring it home that would be great. I'll be around still if you want to communicate. I have all GH comms going to my personal email address now.

Draft PR is at: https://github.com/department-of-veterans-affairs/vets-api/pull/9561

Thanks again for your help,
Kevin

**Comment by RudyOnRails** [comment]
@jason-gcio I set the number of retries to 14. The following table explains the amount of time ≈ associated with the amount of retries:

```
 # | Next retry backoff | Total waiting time
 -------------------------------------------
 1 |     0d  0h  0m 30s |     0d  0h  0m 30s
 2 |     0d  0h  0m 46s |     0d  0h  1m 16s
 3 |     0d  0h  1m 16s |     0d  0h  2m 32s
 4 |     0d  0h  2m 36s |     0d  0h  5m  8s
 5 |     0d  0h  5m 46s |     0d  0h 10m 54s
 6 |     0d  0h 12m 10s |     0d  0h 23m  4s
 7 |     0d  0h 23m 36s |     0d  0h 46m 40s
 8 |     0d  0h 42m 16s |     0d  1h 28m 56s
 9 |     0d  1h 10m 46s |     0d  2h 39m 42s
10 |     0d  1h 52m  6s |     0d  4h 31m 48s
11 |     0d  2h 49m 40s |     0d  7h 21m 28s
12 |     0d  4h  7m 16s |     0d 11h 28m 44s
13 |     0d  5h 49m  6s |     0d 17h 17m 50s
14 |     0d  7h 59m 46s |     1d  1h 17m 36s
15 |     0d 10h 44m 16s |     1d 12h  1m 52s
16 |     0d 14h  8m  0s |     2d  2h  9m 52s
17 |     0d 18h 16m 46s |     2d 20h 26m 38s
18 |     0d 23h 16m 46s |     3d 19h 43m 24s
19 |     1d  5h 14m 36s |     5d  0h 58m  0s
20 |     1d 12h 17m 16s |     6d 13h 15m 16s
21 |     1d 20h 32m 10s |     8d  9h 47m 26s
22 |     2d  6h  7m  6s |    10d 15h 54m 32s
23 |     2d 17h 10m 16s |    13d  9h  4m 48s
24 |     3d  5h 50m 16s |    16d 14h 55m  4s
25 |     3d 20h 16m  6s |    20d 11h 11m 10s
```

14 is about `1d  1h 17m 36s` so maybe y'all want something like 12 in case it's down for a maintenance period and you catch it in the beginning etc.

Cheers
