### ISSUE TITLE
TUD: research why there are 2 more users on the test_users.csv file than there are in TUD.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#37286]
## Issue Description
TUD: research why there are 2 more users on the test_users.csv file than there are in TUD.

Either there are problems with two users and they can't be added to TUD or there is some issue with duplicate users.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Root cause of the issue has been determined.
- [ ] The missing accounts have been re-added if required.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
It turns out there were two users with the same email values.

They shared the same email, pass, etc. but had different names and DOBs.

I removed the duplicates from the list, merged a PR to remove them from the `test_users.csv`, and reset the accounts on staging.

PR - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/413

**Comment by pjhill** [comment]
De-dupes, yay!
