### ISSUE TITLE
Analytics 9 Blocker and Roadmap

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#373]
## User Story
As a VSP stakeholder, I need to see the Insights roadmap so I can understand their priorities for planning purposes.

## Goal
Use the 9 block prioritization tool to prioritize epics and create an Insights roadmap

## Acceptance Criteria
- [x] Synthesize workshop data
- [x] Map epics on 9 block chart
- [x] Insights roadmap created and mapped to VSP themes
- [x] Shared with VSP

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Roadmap incorporated in VSP materials.
