### ISSUE TITLE
Update Accessibility Tools/Processes to support WCAG 2,2

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37316]
## Issue Description
WCAG 2.2 Standards for Accessibility were released in June 2021. In order to stay current, we will need to assess these revised standards, adopt the necessary changes to support those standards and update our documentation to communicate those changes to VFS and platform teams, in order to ensure that we're consistently adhering to industry best practice for accessibility.

---
## Tasks
- [ ] We have discussed our approach as a team and accounted for every aspect involved
- [ ] Tickets have been created and fully detailed to support the work
- [ ] Tickets have been reviewed, and received story point estimates and are ready to be worked

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
