### ISSUE TITLE
Conduct a detailed assessment of updated WCAG 2.2 standards

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37320]
## Issue Description
Review the latest WCAG 2.2 guidelines and determine what changes need to be made to how we approach accessibility in order to stay in compliance with these standards.

**Reference Document**: https://w3c.github.io/wcag/guidelines/22/#comparison-with-wcag-2-1

---
## Tasks
- [ ] Assess each specific new standard and document the answers of the following questions:
    - [ ] Will this change in standards have an impact on how VFS or platform teams currently design/build their products?
    - [ ] Will this have an impact on the tests we currently run to assure accessibility compliance?
    - [ ] What tasks need to be done to implement the change?
    - [ ] What is the level of effort in implementing this change?

## Acceptance Criteria
- [ ] All standards have assessed, and answers to specified questions have been documented
- [ ] We have discussed with design system and governance teams and are agreed on the path forward on each task
