### ISSUE TITLE
[Research] Metrics Sync with CHIP

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37337]
# Description 
CHIP and check-in UX have both been working to understand the metrics and monitoring needed/already set up for check-in. We don't want to duplicate efforts, so the CHIP and check-in teams need to met and review each other's plans.

# Tasks
- [x] Attend CHIP's demo, because they will be reviewing some of their metrics and monitoring efforts
- [x] Meet with CHIP, particularly Chris Horton, to sync

# Acceptance Criteria
- [x] Meetings completed
- [x] Plan of next steps for either team created
