### ISSUE TITLE
[Content][SMS}[APP]Revisions to "Too Late" or "Too Early" check-in status Wording for SMS Messages

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37338]
## Background
This was a recommendation that came out of the [Bay Pines research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/check-in-release-notes.md).

# Description
Improve "too late" and "too early" messaging. User research showed Veterans were unclear why they were seeing this page. 

# Tasks 
- [ ] Create new wording 
    - Maybe modify H1 or body to make it clear why they are seeing this error. 
    - Include the appointment time in the message? 
        - LP: can we do this based on PHI rules? 
        - Do we need to check if the Vet has signed up for getting PHI in SMS messages?
- [ ] Review wording options with content (Danielle)
- [ ] Communicate necessary changes to the CHIP team so they can create work tickets
- [ ] If there are PCI changes, create a ticket for the frontend work for our team
- [ ] Add new content to translation spreadsheet
