### ISSUE TITLE
Review Assessment Findings w/ Design System & Governance Teams

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37332]
## Issue Description
Review the findings of our assessment with other relevant teams to ensure we're in agreement on how each change should be handled.

---
## Tasks
- [ ] Schedule meeting w/ teams
- [ ] Conduct meeting w/ teams

## Acceptance Criteria
- [ ] Decisions are made against each standard

**Comment by JoeTice** [comment]
Things to look at for each component:
- Do the components need to change?
- Does our documented standard need to change?
- Do our tests that scan for the compliance of the standard need to change?
