### ISSUE TITLE
[BE] | Back-end Tools & Dashboards for 10-10 Apps

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#37335]
## Description

We'd like to ensure that we have both the 10-10CG and the 10-10EZ app implemented on the appropriate back-end tools so that we have ready visibility to any potential failure points.

On 2/22/22 Kevin, Lihan and I met to review what tools should be leveraged and set up an automated dashboard any team member can access and add alerting capabilities to notify us when there is a production issue.

At a high level:

- Loki is a log aggregation system designed to store and query logs from all our applications 
- Grafana queries Loki to provide dashboards and alerting capabilities 
- Data Dog is used tp aggregate metrics and events 

(SK: Why do we use both Grafana and Data Dog when the have seemingly similar capabilities?)

The objective of this "super epic is to:

- [ ] Understand what tools are in place today for both 10-10CG and 10-10EZ and what data is being captured
- [ ] Identify and recommend what is needed to provide a robust monitoring, alerting and dashboard experience for these apps
- [ ] Create detailed ticket to capture integration work
- [ ] Create tickets for Dashboard data and identify thresholds for Alerts

## Product goals:
- Stakeholder insight into product health
- Automate running daily/weekly/monthly reports
- Enable individuals run the report themselves wiithout undertaking complicated steps?

## What do we want to know:
- By any given set of dates:
     - How many attempted submissions
     - How many went through to CARMA (successes)
     - How many were blocked by MPI (failures)
     - How many were blocked by other types of errors (failures)
     - PDF Uploads
- What kinds of errors are people running into? (error code groupings)
- Trends over time

**Comment by lihanli** [comment]
1010 team monitors: https://app.datadoghq.com/monitors/manage?q=tag%3A%22team%3Avsa1010%22
