### ISSUE TITLE
[SPIKE] Migrate from using Division to PhysicalLocation from VistA Clinic

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#37339]
## Timebox
2-3 hours

## Description 
There is an issue ongoing with Mobile app and VAOS where appointment location is not being displayed appropriately as to where the appointment will actually take place. This is due to the VistA Clinic object **Division** field being used to display the location, but the Division is often set to the main VAMC facility and not necessarily an accurate physical location of the clinic, with the unfortunate result that Veterans may think they have an appointment at a VAMC main facility when it is really at a CBOC. Because we use the Division field from VistA Clinic, this issue will likely impact us as well.   There is an initiative to populate the VistA Clinic **PhysicalLocation** field in a standard way across all VistA clinics; if that succeeds it should help resolve this issue, and we would want to migrate to use that field. 

Link to [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1645215874724259) thread. 

## Tasks 
- [ ] Invoke use of PhysicalLocation from VistA Clinic 
- [ ] Ensure Devision is no linger in use
- [ ] Testing/confirmation in appropriate environment(s) has taken place 
      - [ ] Staging and Prod 

## Acceptance Criteria 
- [ ] PhysicalLocation from VistA Clinic has been implemented

**Comment by stephenBarrs** [comment]
This work is dependent on Clinical Practice Management (CPM) group ensuring the `physicalLocation` field is updated for all clinics.  There may also be an initiative to ensure the `Division` field is set correctly to reflect if the clinic is located at a CBOC, VAMC or other VHA facility.  We will not be able to do any work on this until CPM completes one of those tasks.
