### ISSUE TITLE
Follow up with the Platform teams on the "front-end information" for core CC ticket

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#37345]
## User Story
_"As a (persona), I (want to), (so that)."_

- Intended Audience: 
- Desired Outcome: 
- Due Date: 

## Description
From comments on ticket [#34737](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34737). 
Some of the fields in "VFS product information" are to be completed post launch, so 1) might want to state that somewhere in the ticket, and 2) remove the asterisk* indicating it's required from the YAML version. The post launch fields are: Feature launch date, Production URL, and Front-end information.
We'll want to follow up with the Platform teams on the "front-end information" - can one of you create a ticket for the backlog?

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Tasks
- [ ] _Placeholder task_

## Acceptance Criteria
- [ ] "Insert Page Name" Confluence document has been updated per guidance
- [ ] "Insert Page Name" Confluence document has been created per guidance
- [ ] "Insert GitHub template" GitHub template has been created per guidance
- [ ] "Insert GitHub template" GitHub template has been updated per guidance
- [ ] "Insert Platform Website Page" on Platform Website has been updated per guidance
- [ ] "Insert Platform Website Page" on Platform Website has been created per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
Closing this ticket as the work is not necessary for this initiative.
