### ISSUE TITLE
[FSR] Replace Deprecated LoadingIndicator

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#37346]
## Issue Description
Platform deprecated `<LoadingIndicator>`, suggesting we use `<va-loading-indicator>` instead.

---
## Tasks
- [ ] Replace `<LoadingIndicator>` with new `<va-loading-indicator>` in FSR. 

## Acceptance Criteria
- [ ] Should render `<va-loading-indicator>` instead in FSR
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
