### ISSUE TITLE
Verify Domo queries referencing VFS teams in Collab Cycle dashboard are correct

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37354]
## User Story
As a Governance team member supporting the Collaboration Cycle dashboard in Domo, I want to verify that the queries for pulling in VFS teams (via github labels) are accurate so that the Collaboration Cycle dashboard in Domo correctly represents VFS teams

## Background
The QA Standards team maintained the Collaboration Cycle Dashboard in Domo for a long time as the Governance team did not have resources on the team who could support Domo. As of 2022, Platform teams must be self-sufficient, so Governance team has taken over as the new owner of the Collaboration Cycle Dashboard in Domo.

## Description
One of the things that needs to be upkept in Domo is VFS team labels. If a VFS team changes their label in the va.gov-team repo (for example, the Caregivers team recently was renamed to the 10-10 team so they changed their label in github from `vsa-caregivers` to `vsa-10-10`), then the query in Domo (or BigQuery) will also have to be updated.

The purpose of this ticket is to verify the VFS team labels are correct based off labels in the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2444951), add the teams in the Roster to the Dashboard that are not currently represented, and lastly, alphabetize the list of teams in the "Total Issues by team" bar chart.

In addition, the Design System team sometimes is the accountable team for fixing issues identified in Staging review. As such, their label gets added to the issue ticket. Even though they are not in the VFS Team Roster, they should be represented in the "Total Issues by team" bar chart.

## Artifacts Needing Updates
N/A

## Tasks
- [ ] _Placeholder task_
- [ ] _Placeholder task_
- [ ] _Placeholder task_

---

## Acceptance Criteria
- [ ] All VFS teams (per the VFS Team Roster) are represented in the "Total Issues by team", including Design System team
- [ ] The Collab Cycle Dashboard references the correct VFS team github label
- [ ] The "Total Issues by team" chart lists teams alphabetically
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
closing as the "Total issues by team" card has been deleted. FYI @chaseakirby
