### ISSUE TITLE
Implement hardened Medical Records page design

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37365]
## Issue description
We need to doublecheck the newly hardened Medical records page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)
- Medical records page needs to account for padding around either VA blue button widget or Cerner medical records link

Medical records
- [Content model mural - Medical records](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595862359396/4d517fc3ffe0e6e9ec9fb81ff4325a4d7d1946d4)
- Example [Medical records page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/medical-records-office/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152041575-75944bda-2664-43f4-9552-fde87487ce07.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152041852-652a0cee-8688-418c-8e46-dd3cc331ff8e.png)

</details>

## Template
```
<!--
  layout: health_care_region_detail_page.drupal.liquid
  path: spokane-health-care/medical-records-office
  entityId: 26942
-->
```

## Related issue
New Medical records link for Cerner is in #35947

## Tasks
Implement [UXPin design](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147616704/documentation/no-panels?mode=i) for Medical records office pages in three parts-

- [ ] Heading levels in #37398
- [ ] Hours and phone styles in #37399
- [ ] Logic for the order of locations in #37400

## Acceptance Criteria
Medical records page is designed consistent with UX Pin spec, including
 - [ ] "Release of information office locations" is an H3
- [ ] The name of each facility is an H4
 - [ ] A Veteran can click on the name of the facility from the medical records page and view the facility main page
 - [ ] Phone labels are consistent with CMS data and appear above the phone number
 - [ ] The Hours heading is displayed above the hours listed by day, according to the data in CMS
 - [ ] "Mail your signed form to" is an H3
 - [ ] "Fax your signed form to" in an H3
- [ ]  General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] When more than one Locations is displayed, the Main Medical Center will be listed first, followed by any additional locations
- [ ]  Campus map and directions link will not be needed, per Dave C. 
- [ ] Deployment is coordinated with CMS team

**Comment by mmiddaugh** [comment]
Completed in VAVSA-37365: Update med records tpl to include design changes. #1085
