### ISSUE TITLE
Add "Work in Progress" notification to Product Development Checklist

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37362]
## User Story
As a VFS team member, I was to know what pages are under construction so that I know the guidance may not be 100% reliable.

As a Governance team member, I want to ensure that the Product Development Checklist page is marked as "Work in Progress" so that VFS team members know that the guidance is not 100% reliable.

## Description
The Product Development Checklist is live on Platform Website however it is not fully in use and/or up to date. Because of this, we want to add  "Work in progress" note to the top of the page so that VFS teams are aware.

In addition, Martha noticed that the “Everything is 508 Accessible and there are no Sev 1 accessibility bugs ” item links to an old branch. This should be updated to link to master.

## Artifacts Needing Updates
[Platform Website: Collaboration Cycle/Product Development Checklist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Product-Development-Checklist.1971650643.html)

## Tasks
- Add "Work in Progress" to the top of the page (reached out on #vsp-confluence Slack channel for guidance on how this should be done)
- Update 508 accessible link to master branch

## Acceptance Criteria
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled
- [ ] 508 accessible link is correct
- [ ] VFS teams are able to see that the page is a work in progress

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket
