### ISSUE TITLE
Iterate Lovell design for dual eligible flow

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37369]
## Issue description 
The Captain James A. Lovell Federal Health Care Center has a combined mission to serve active duty military, their family members, military retirees and Veterans. The center also cares for an estimated 40,000 Navy recruits who prepare for military service at Recruit Training Command at Naval Station Great Lakes.

Primary question to solve - as a DoD or VA person, can I complete my top tasks and identify the information which is relevant to me. 

During conversations with stakeholders, we've learned that some individuals cared for by Lovell may have the option to use either VA or DoD/Tricare benefits (such as retired military personnel). We need to ensure that the user flow includes a method for an individual who has chosen one persona to view information relevant to the other. (ie - viewing the page as a Veteran but needs to see pharmacy DoD/Tricare benefit information 

## Tasks
- [ ] Learn at which points in the user flow this option will be needed
- [ ] Design user flow for this scenario
 
## Acceptance Criteria
- [ ]  Based on feedback from peers and other stakeholders, make design recommendations for Lovell Federal health user flow

#### UXPin design update
Here's the current [iteration update UXPin](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/147178609/simulate/sitemap?mode=i), with VA and DoD flows, a link to return to the beginning of the flow, and a specific page switch to the equivalent page in the opposite flow (Nick O)

**Comment by nicko-amida** [comment]
Here's the current [iteration update UXPin](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/147178609/simulate/sitemap?mode=i), with VA and DoD flows, a link to return to the beginning of the flow, and a specific page switch to the equivalent page in the opposite flow.
