### ISSUE TITLE
Implement front end design for hardened Billing and insurance pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37366]
## Issue description
We need to doublecheck the newly hardened Billing and insurance page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

Billing and insurance
- [Billing and insurance content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595854648224/23c83ef3ccbbd06cd4d5afd59db5ddfa5688a8e1)
- Example [Billing and insurance page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/billing-and-insurance/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/billing-and-insurance
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/billing-and-insurance

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058238-3389f707-79af-4a62-a131-10642979d00d.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057908-b4bf4e85-4ea8-4926-aa36-9f3fe381493f.png)

</details>

## Related issues
The implementation of  [UXPin design](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147616704/documentation/no-panels?mode=i) for Billing and insurance pages will be done in three parts-
- Heading levels in #37598
- Hours and phone styles in #37601
- Replacing alert in #37612

## Tasks

Implement [UXPin design](https://preview.uxpin.com/16d44a03330afdb07cf7baa572b1bb6c95cb9077#/pages/147796626/documentation/no-panels?mode=i) for Billing and insurance pages, including the following

- [ ] Add a new H2 heading for "Questions about copay balance" 
- [ ] The name of each facility is an H4, linked to that VAMC page.
- [ ] Phone labels and numbers follow an update design pattern.
- [ ] Hours follows an updated design pattern
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Replace existing VA Blue Button sign in alert on with primary action link according to Nick's design ([UX Pin](https://preview.uxpin.com/16d44a03330afdb07cf7baa572b1bb6c95cb9077#/pages/147888051/documentation/no-panels?mode=i) when flag from CMS (field name `vamc_ehr_system`)** indicates Cerner
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production

## Acceptance Criteria
Billing and insurance page is designed consistent with UX Pin spec, including
- [ ] "Questions about copay balance" is available by jumplink
- [ ] "Questions about copay balance" is displayed as an H2
- [ ] The name of each facility is an H4
- [ ] A Veteran can click on the name of the facility from the medical records page and view the facility main page
- [ ] Phone labels are consistent with CMS data and appear above the phone number
- [ ] The Hours heading is displayed above the hours listed by day, according to the data in CMS
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] When flag from CMS (field name `vamc_ehr_system`)** indicates Cerner, primary action link is displayed according to Nick's design
- [ ] Link to Cerner portal renders only when indicated based on the CMS Cerner flag (field name `vamc_ehr_system`)
- [ ]  When field name=`vamc_ehr_system`, Veterans can click on a link on that health care system's Medical records page to be directed to the health record portion of the Cerner portal.
- [ ] When field name does not = `vamc_ehr_system`, the existing functionality is maintained.
- [ ] 
- [ ] Deployment is coordinated with CMS team

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1088
