### ISSUE TITLE
Implement front end for newly hardened Register for care pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37367]
## Issue description
We need to doublecheck the newly hardened Register for care pages to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

Register for care
- [Register for care content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b)
- Example [Register for care page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/register-for-care/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care 

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058075-2c8c27b2-76c1-42d7-9ee3-0f1dfce87e53.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057591-5838d977-3723-4aed-b16f-335ecb166e35.png)

</details>

Template

## Related issues
The implementation of the [UXPin design](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147616704/documentation/no-panels?mode=i) for Medical records office pages will be done in three parts-
- Heading levels in #37627
- Hours and phone styles in #37630
- Logic for the order of locations in #37631

## Tasks
Implement [UXPin design](https://preview.uxpin.com/640e3b5894ed7cdf5c5d3342b119badd012ec5a5#/pages/147812897/documentation/no-panels?mode=i) for Register for care pages, including the following
- [ ] Add new Q2 heading for "Patient registration (admissions)"
- [ ] Add new Q2 heading for "Not yet enrolled in VA health care?"
- [ ] Ensure new Q2 headings are available by jumplink
- [ ] The name of each facility is an H4, linked to that VAMC page.
- [ ] Phone labels and numbers follow an update design pattern.
- [ ] Hours follows an updated design pattern
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Style "Apply online, by mail or phone" as action link and ensure it takes users to an intermediary page. 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production

## Acceptance Criteria
Register for care page is designed consistent with UX Pin spec, including

- [ ] When viewing health care Register for care page, Veteran sees "Patient registration (admissions)" heading
- [ ] When viewing health care Register for care page, Veteran sees "Not yet enrolled in VA health care?" heading
- [ ] Veteran can view "Patient registration (admissions)" content by clicking on jumplink
- [ ] Veteran can view "Not yet enrolled in VA health care?" content by clicking on jumplink
- [ ] The name of each facility is an H4
 - [ ] A Veteran can click on the name of the facility from the medical records page and view the facility main page
- [ ] Phone labels are consistent with CMS data and appear above the phone number
- [ ] "Apply online, by mail or phone" is styled as action link and ensure it takes users to an intermediary page. 
- [ ] The Hours heading is displayed above the hours listed by day, according to the data in CMS
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Deployment is coordinated with CMS team

**Comment by mmiddaugh** [comment]
completed in https://github.com/department-of-veterans-affairs/content-build/pull/1082
