### ISSUE TITLE
[SW-Content] Swap out videos in COVID CLP - Hold to publish until week of 2/14 [Reoccurring]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37374]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page
- [ ] New ticket created

**Comment by RLHecht** [comment]
This work is complete. Moving to validate.
