### ISSUE TITLE
Update "Total Issues by team" view of Collaboration Cycle Dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37372]
## User Stories
As a VFS team member, I want to be able to view the "Total Issues by team" view of the Collaboration Cycle Dashboard to see if my team has any open tickets so that I can follow up and ensure my team addresses them. 

As an OCTO-DE lead, I want to be able to view a non-cluttered version of the "Total Issues by team" view of the Collaboration Cycle Dashboard so that I can easily see at a glance which teams have open issues.

As a Governance team member, I want to clean up the "Total Issues by team" view of the Collaboration Cycle Dashboard to only include teams with open issues so that teams we don't work with often (for example: CTO team, VAMC, VAOS) aren't consistently showing up on the dashboard with 0 issues.

## Description
The [Collaboration Cycle Dashboard](https://va-gov.domo.com/page/1340527018?userId=1646566899) currently has 2 views:

1. Total issues by team (bar graph)
2. Total issues by status (pie chart)

The Total issues by team view is consistently challenging to read because all teams that the Collaboration Cycle could potentially work with are represented. However, Collaboration Cycle isn't currently supporting many of the teams shown. In the graph, those teams show up with 0 issues identified week after week, month after month. The Total issues by team view should only include teams that have open issues. If a team doesn't have an open issue, it's should not be included in the graph.

*If this task is too challenging to complete, please let Shira know. We'd like to be able to share a streamlined version of Total issues by team, however if it is more hassle than it's worth, it's no big deal and this ticket can be deprioritized.

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/6f1ab207-0840-4564-84ee-422ae74d9829)

## Tasks
- Update the Total issues by team chart/view as specified above
- Review with Shira for feedback

## Acceptance Criteria

- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
closing as this view/card is no longer necessary. FYI @chaseakirby
