### ISSUE TITLE
[Combined Debt Portal] User flows 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#37371]
## Issue Description
Now that we've decided a path forward with the combined portal's IA structure, we need to create a visual diagram to present to the DMC stakeholders. This will help them understand how our users will interact with the portal depending on their needs as well as the site's navigational structure. 

---
## Tasks
- [x] Create low fidelity wireframes for the key touchpoints in the combined portal's experience
- [x] Create user flows based on IA's provided diagram 

## Acceptance Criteria
- [x] The first iteration user flows have been created and linked in this document

**Comment by rileyorr** [comment]
[The user flows can be found in this Mural board](https://app.mural.co/invitation/mural/vsa8243/1645453970389?sender=riley5075&key=b9051645-ff1a-4307-a1df-bd9622b9ca31).

**Comment by denisecoveyduc** [comment]
@rileyorr Oh my goodness look at those beautiful user flows! LOVE! Our stakeholder is going to have no problem wrapping her mind around this! Well Done!!
