### ISSUE TITLE
[S3] New bucket for storing data from form 1095-B in DEV

### ISSUE THREAD

**Issue by stephte** [department-of-veterans-affairs/va.gov-team#37391]
## Description
Need access to an AWS S3 bucket to store files containing tax form 1095-B data. The S3 bucket will receive the files from the VA Enrollment System, and our Ruby script (in the Vets-API) will check the bucket, grab the files, and store the data in the Vets-API database. The data will ultimately be used to generate 1095-B tax forms that the Veteran can download from the VA website when needed.

---
## Tasks
- [ ] Create an S3 bucket in dev 
- [ ] Give the user access to read/write to the S3 bucket 

## Acceptance Criteria 
- [ ] The user is able to upload files to the S3 bucket in dev

**Comment by jsgarmon** [comment]
@stephte : typically we add new infrastructure to our code and give any applications access to it. Is there a reason a human needs to read from and write to the bucket? Is there currently an application or pipeline that will read from the files in this bucket?

**Comment by stephte** [comment]
There is a program/script that will be reading the files from this bucket, it is a part of the Vets-API additions that we are currently developing. We only want human read/write for the development version of the bucket (where we would be using fake data) so that we can test and finish building out the script that will read from it. We do not need human read/write access for the production version.

**Comment by jsgarmon** [comment]
@jhouse-solvd : I'll wait for your go-ahead for this. My main question is: who is now signing off on new infrastructure/architecture? Are there ATO implications? We'll probably want to clarify the approval process as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/37352.

**Comment by jhouse-solvd** [comment]
@stephte - I have a couple of questions: 

- Do members of your team already have access to AWS? This may _not_ be necessary, but could be for the configuration of environment variables for the application. 
- I noticed you mention that this is an application that you are currently developing... Is there a parent epic or initiative that you can link to so that we can understand more? 

Our intake process involves creating the issue/request (which you've done, thank you!) and then prioritizing requests for new infrastructure with our product owner @mchelen. From there, the issue can be planned for an upcoming sprint. 

I'm not sure if you've had the opportunity to discuss this with Mike yet. His input will be helpful in moving this request forward.

**Comment by stephte** [comment]
- No other members of my team have AWS access yet.
- here is a link: https://app.zenhub.com/workspaces/1095b-tax-form-61e19735167b2500170b2146/issues/department-of-veterans-affairs/va.gov-team/37024

**Comment by jhouse-solvd** [comment]
Hi @stephte - The Infrastructure team is discussing your request with our product owner. ☺️ 

1. Can you please provide the name of your application team? 
2. We'd like to start by provisioning the bucket in dev. Will that work for you? 
3. We also wanted to make sure that you are aware that storing PHI/PII is prohibited. 

Thank you!

**Comment by stephte** [comment]
1. Application team is MOVE
2. A DEV bucket would be just fine for now

**Comment by jhouse-solvd** [comment]
@JordanSWhite - verify that the data in DEV is testing data; and where we are storing the data for the document (database?)

**Comment by stephte** [comment]
We are storing the document data in the Vets-API database. 

Here is a sample test file I am going to use, all the test data going into the dev bucket is just going to be stuff I make up based off this file format.
[MEC_DataExtract_O_2021_V_2021123016452.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/8155772/MEC_DataExtract_O_2021_V_2021123016452.txt)

**Comment by jsgarmon** [comment]
@stephte: this bucket is created, named [dsva-vagov-dev-1095b-form-uploads](https://console.amazonaws-us-gov.com/s3/buckets/dsva-vagov-dev-1095b-form-uploads?region=us-gov-west-1). Please verify that you can read and write to it and close this issue if there is nothing else to do for this issue.

Please create a new issue when you're ready for staging/production buckets to be created.

**Comment by stephte** [comment]
read/write confirmed, thank you!
