### ISSUE TITLE
Implement phone and hours display for hardened VAMC Medical records page (2 of 3)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37399]
### Issue description
We need to doublecheck the newly hardened Medical records page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved
- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Following the hardening work on top task pages, we need to make some adjustments to style locations like service locations, including the presentation of hours by day
-  We need to maintain correct heading levels and style padding 

## References for Medical records
- [Content model mural - Medical records](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595862359396/4d517fc3ffe0e6e9ec9fb81ff4325a4d7d1946d4)
- Example [Medical records page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/medical-records-office/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/medical-records-office

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152041575-75944bda-2664-43f4-9552-fde87487ce07.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152041852-652a0cee-8688-418c-8e46-dd3cc331ff8e.png)

</details>

## Related issue
- New Medical records link for Cerner is in #35947
- This issue is one of 3 to complete this design implementation
     - Hours and phone styles will be completed in this issue
     - Heading levels will be done in #37398
     - Logic for the order of locations will be completed in #37400
 
##  Dev notes
**Template**
The newly hardened pages use this template
```
<!--
  layout: vamc_system_medical_records_offi.drupal.liquid
  path: preview
  entityId: N/A
-->
```
The following systems have data in this new hardened template and can be used for validation:

- VA Western Colorado health care
- VA Cheyenne health care
- VA Eastern Oklahoma health care  
- VA Sheridan health care

- Campus map and directions link will not be needed, per Dave C. 

## Tasks
Implement [UXPin design](https://preview.uxpin.com/2e7af3cf44ec68fd41899e7ddb6071ea3bb2b61b#/pages/147616704/documentation/no-panels?mode=i) for Medical records office pages, for the following
- [ ] Phone labels and numbers follow an update design pattern. 
- [ ] Hours follows an updated design pattern
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them)

## Acceptance Criteria
Medical records page is designed consistent with UX Pin spec, for the following
- [ ] Phone labels are consistent with CMS data and appear above the phone number
- [ ] The Hours heading is displayed above the hours listed by day, according to the data in CMS
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Steps taken to test these changes and their results are documented in this issue

**Comment by mmiddaugh** [comment]
Completed in VAVSA-37365: Update med records tpl to include design changes. #1085
