### ISSUE TITLE
Logic for displaying featured stories on VAMC home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37396]
## Issue Description
The logic for displaying featured stories on VAMC pages is confusing for editors. 

## Current behavior
The editorial experience currently allows an editor to mark a story for featuring and specifying the position (1st or 2nd).

**Problems to be solved:**

- More than one story can be marked for a given position. 
- A story can be marked as featured in the 2nd position, even if there is no story marked for 1st position. 
- A story can be marked for featuring without a specified position and vice versa. 

## Expected behavior (based on conversation with Dave Conlon on 2/28)

Regarding stories displayed in the home page spotlight 
- If desired, a VAMC health care system can choose _not_ to feature stories on its home page. 
- If desired, a VAMC health care system home page can feature _up to_ two stories.
- In the event that more than one story is marked for featuring in the same position, the most recent story marked for featuring in that position will be displayed. 
- Stories should not be displayed unless it has been marked as featured
- Behavior on the Stories listing page will be determined separately

## Dev Notes

Template:
```
<!--
  layout: health_care_region_page.drupal.liquid
  path: salt-lake-city-health-care
  entityId: 6300
-->
```

<details>
<summary> Object details </summary>
```
Object
alert: {entities: Array(47)}
allEventTeasers: {entities: Array(0)}
allNewsStoryTeasers: {entities: Array(0)}
allPressReleaseTeasers: {entities: Array(0)}
bannerAlert: {entities: Array(304)}
banners: {entities: Array(2)}
debug: null
entityBundle: "health_care_region_page"
entityId: "6300"
entityMetatags: (14) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
entityPublished: true
entityUrl: {breadcrumb: Array(2), path: '/salt-lake-city-health-care'}
eventTeasers: {entities: Array(0)}
eventTeasersAll: {entities: Array(1)}
eventTeasersFeatured: {entities: Array(1)}
facilitySidebar: {name: 'VA Salt Lake City health care', description: 'VISN 19 | va.gov/saltlakecity-health-care', links: Array(1)}
fieldClinicalHealthServices: {entities: Array(26)}
fieldFacebook: {title: 'VA Salt Lake City Healthcare System Facebook page', uri: 'https://www.facebook.com/vasaltlakecity'}
fieldFlickr: null
fieldGovdeliveryIdEmerg: "USVHA_476"
fieldGovdeliveryIdNews: "USVHA_86"
fieldInstagram: {title: 'VA Salt Lake City healthcare system', uri: 'https://www.flickr.com/vasaltlakecity/albums/'}
fieldIntroText: "At the VA Salt Lake City Healthcare System, our expert health care teams focus on your needs and the needs of other Veterans, your families, and caregivers. Find a health care facility near you and manage your health online. Sign up for community events and updates, and learn what’s new at your local VA medical center and clinics."
fieldMedia: {entity: {…}}
fieldOperatingStatus: {url: {…}, title: 'Operating status | VA Salt Lake City health care'}
fieldOtherVaLocations: (7) ['vc_0531V', 'vc_5141OS', 'vc_0532V', 'vc_0540V', 'vc_0514V', 'nca_888', 'vba_341']
fieldRelatedLinks: {entity: {…}}
fieldTwitter: {title: 'VA Salt Lake City Healthcare System', uri: 'https://twitter.com/vasaltlakecity'}
fieldVamcEhrSystem: "vista"
mainFacilities: {entities: Array(1)}
mobileFacilities: {entities: Array(0)}
newsStoryTeasers: {entities: Array(0)}
newsStoryTeasersFeatured: {entities: Array(1)}
otherFacilities: {entities: Array(10)}
outreachSidebar: {name: 'Outreach and events', description: '', links: Array(1)}
pid: 6300
promoBanners: {entities: Array(0)}
reverseFieldRegionPageNode: {entities: Array(11)}
title: "VA Salt Lake City health care"
vid: 610903
[[Prototype]]: Object
```
</details>

---
## Tasks
- [ ] Ensure the logic for displaying featured stories on VAMC pages includes the following
       - Up to 2 stories can be displayed 
       - To be displayed, the editor must have checked the box indicating the story should be featured
       -  In the event that more than one story is marked for featuring in the same position, the most recent story marked for featuring in that position will be displayed
- [ ] Validate behavior in tugboat using several different health care systems
- [ ] Request validation from PM/PO before merging       

## Acceptance Criteria
- [ ] If no stories are marked for featuring, no stories will be displayed on the VAMC home page spotlight
- [ ] Only stories checked as "featured" should be displayed on the VAMC home page spotlight
- [ ] If more than two stories have been checked to be featured in the same position, the most recent story will be displayed in that position
- [ ] If a more recent story is available but has not been checked to be featured, it will not display.
- [ ] If only one story is checked to be featured, only that story displays

**Comment by davidmpickett** [comment]
Closing as duplicate/ not planned as the direction has shifted since this ticket was first created. New short term goal is to get the Featured functionality working with limiting to 1 per VAMC system

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13687
