### ISSUE TITLE
[FE] Update Pre-Check-in Capture from 24 Hours to 3 Days 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#37408]
## Description 
Currently, if Pre-Check-in is completed within 24 hours before appointmentTime, the pages that are confirmed will be hidden on day-of check-in experience. This time parameter needs to be updated from 24 hours to 3 days prior to appointment day. 

## Tasks
- [ ] Create function to calculate days rather than hours 
- [ ] Update time variable to use days instead of hours 
- [ ] Create/update mocks and tests
- [ ] Sync with Alex (CHIP) to write different timestamps to database for validation 

## Acceptance Criteria 
- [ ] Pre-check-in confirmation pages are hidden on day-of check-in experience 
- [ ] Check day-of responses for 4 days and confirm screens come back on day 4

**Comment by brianseek** [comment]
Confirmed functionality on staging with Alex from the CHIP team writing to the DB
