### ISSUE TITLE
[SW-Content] Swap out videos in COVID CLP - Hold to publish until week of 2/28 [Reoccurring]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37409]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John McAllister

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [ ] New videos and text are live on the page
- [ ] New ticket created

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review and publishing.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published this. Moving to validate.
