### ISSUE TITLE
Verify github product labels with VFS Product Managers

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37411]
## User Story
As a Governance team member, I want to verify with VFS PMS that the github labels in use and/or proposed for VA.gov products are correct so that Collaboration Cycle can report issues at the product level.

## Description
In ticket #34735, Governance team attempted to categorize and define github labels for the VA.gov products that have been brought through the Collaboration Cycle. The purpose of this ticket is to verify the proposed labels and address any gaps with the VFS PMs so that we may then apply these labels to existing Collaboration Cycle issue tickets.

## Artifacts Needing Updates
[VA.gov Product Labels](https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0) spreadsheet

---
## Tasks
- [x] Draft message to send to PMs via Slack

> Hi there, VFS PMs. As mentioned in ToT, Governance team needs your help verifying the labels you use in the va.gov-team repo for your VA.gov products. Please [visit Calendly](https://calendly.com/collaboration-cycle/va-gov-product-label-sync?month=2022-02) and schedule a 15 minute meeting with Shira to review your product, github labels and potentially proposed labels. Thank you very much for your help and support! Feel free to thread any comments or questions. 

- [x] Set up Calendly sign-up for PMs to pick time to meet
- [x] Reach out to the following Product Managers and share Slack message and Calendly sign-up:
   - [x] Sharon Kasimow (10-10 team, Content & Localization)
   - [x] Heather Justice (Authenticated Experience)
   - [x] Ronnie Henry (Claims & Appeals)
   - [x] Denise Coveyduc (Debt Resolution)
   - [x] Marci McGuire (Decision Tools, Profile)
   - [ ] Abe Blanco (Education)
   - [x] Cesar Santiago (DGIB)
   - [x] Jason Wolf (eBenefits)
   - [x] Michelle Middaugh (Facilities)
   - [ ] Jordan White (Health Apartment)
   - [x] Nick Soutouras (Identity)
   - [ ] Corey Parker (Modernized Check-in)
   - [x] Brian Lloyd (Public Websites)
   - [x] Nicole Leonard (Search & Discovery)
   - [x] Jeff Roof (VAOS)
   - [x] Melanie Jones (VANotify)
   - [x] Ian Santarinala (Virtual Agent)
   - [x] Ashley Castillo (1095B)
   - [x] Jason Woodman (Contact Center)
   - [x] Leah Keeler
  
- [x] Verify the relevant products and proposed product labels with each PM
- [x] Make changes if requested

## Acceptance Criteria
- [x] Every VA.gov product has an agreed upon github product label
- [x] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby I am closing this out. Please let me know if you have any questions.
