### ISSUE TITLE
[Research] My VA - Payment info: Add details to UAT research plan

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#37429]
The UAT Research plan is just about finished - we need to fill in the scheduling portion with availability (dates + times), and pilot session info. We also need to confirm whether or not we want to include co-pay questions - Samara didn't comment either way on that when she gave feedback for the UAT draft.

We also need to determine whether or not we want to record the session, and update the conversation guide accordingly.

**Tasks**

- [x]  Complete date/time availability for UAT sessions
- [x]  Find pilot participant (can be anyone internal but bonus points if it is a Veteran who is not familiar with the feature)
- [x] Add pilot session info to research plan
- [x] Confirm whether or not we need to include co-pay questions and edit accordingly
- [x] Remove action item language from research plan

**Comment by andaleliz** [comment]
FYI @Samara-Strauss, I added Christina as an observer to the UAT sessions. She won't attend all but this is a good opportunity to intro her to how we run UAT.

**Comment by hdjustice** [comment]
@aagosto90 - Confirmed with Samara that we will want to add the question about copays to the conversation guide/research plan.
Also, Samara confirmed that recording the sessions is fine, no concerns there.
@andaleliz for awareness

**Comment by aagosto90** [comment]
@hdjustice @Samara-Strauss When I was running through this with Liz and added the question about copays at the end, then we were discussing my recent conversations with @rileyorr and @andaleliz brought up a good point. In considering whether to add copays to Healthcare or Benefit Payments & Debts, since the debt resolution team is actively working on combining copays and debts into the same location, not only would it make sense to show them in the same section of MyVA, but it's also an accessibility no-no to have multiple links on the page with different text that go to the same place. We could still ask the question in UAT to verify people aren't overwhelming associating copays with healthcare but this is a strong case for putting copays under Benefit Payments & Debts.

**Comment by Samara-Strauss** [comment]
This is a great point! Do we know on what timeline they plan to combine debts and copays?

**Comment by aagosto90** [comment]
@Samara-Strauss They plan to launch it in late March/early April so it definitely makes sense to consider this in our design. Looking forward to chatting more about the implications of this with you on Friday!

**Comment by Samara-Strauss** [comment]
Oh that's great! Yes, we should definitely coordinate closely. Looking forward to catching up on Friday to discuss.

**Comment by aagosto90** [comment]
After unsuccessfully trying to find a internal veteran to do a test pilot with and since we have pretty specific criteria for this UAT, we decided to go forward with submission and use the first participant Perigean gives us as the test pilot. Closing this ticket and preparing for submission.
