### ISSUE TITLE
[AVA] Discovery 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#37420]
## Issue Description
Given the number of technical issues Veterans are contacting DMC about, our team is going to begin discovery on how to get on the Ask VA's backlog to redirect Veterans to their tool 

---
## Tasks
- [ ] Document questions for both DMC and Ask VA 
- [ ] Reach out to the Ask VA team to learn more about their timeline and process 

## Acceptance Criteria
- [ ] Discovery questions are documented and linked in this ticket

**Comment by HeatherRienks** [comment]
Per conversation with @denisecoveyduc and @Tom-Davis, closing this ticket - OCTO now has a team spun up to address this issue
