### ISSUE TITLE
Veteran Image shift on VA.gov Homepage ONLY (Behind a Feature Flag) 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37435]
#### High-level user story
As a Veteran I want to visit VA.gov and quickly find the information and support I need in support of obtaining the benefits they deserve.

### Background 
I a recent VA.gov Way-finding research, some high-level preliminary recommendations were to consider design changes to increase visibility of some tools on the home page and sitewide navigation.   Participants during the study often confused the Veteran images under the "Top Four" boxes as the end of the page and would stop scrolling, data confirms this as most users stop scrolling past this element.  We're now at the phase where we want to test some of these hypothesis and plan to shift the Veteran Images to the footer behind a feature flag to be released on a future date.  

### Desired Affect
- Take the Veteran images and place them just above the VA.gov Footer.
![Screen Shot 2022-02-22 at 4 25 55 PM](https://user-images.githubusercontent.com/70410912/155238780-61ef4e7e-30b7-4f4b-aeb4-c711e5d5ce3f.png)
- Place the Veteran images just above the VA.gov footer on the homepage `ONLY`.  **This initial release behind a feature flag for future implementation.** 
![Screen Shot 2022-02-22 at 4 26 07 PM](https://user-images.githubusercontent.com/70410912/155238926-82b68b0d-fab9-41b7-adae-60ba4b6b963e.png)

### Tasks
- [ ] Shift Veteran images as outlined, ensuring visual affects remain. 
- [ ] Ensure update is on VA.gov Homepage ONLY
- [ ] Ensure this release is for 0% of authenticated users (behind a feature flag to be implimentated in future).
- [ ] Validate with Insights and Analytics team to ensure tracking is in place for this component.  
- [ ] Test locally to determine functionality / Validate in Staging before deploying to Prod.
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Home page images are updated as intended on VA.gov homepage only for 20% of authenticated users
- [ ] Analytics are in place to monitor impact (Connected ticket)
- [ ] Local test are completed and show signs of success
- [ ] a11y considerations are implemented in support

**Comment by longmd** [comment]
@brianalloyd , as we discussed this morning, there is absolutely a path forward to create a widget with a feature toggle to control the placement of this image. Here is how I see this working

- The created widget would duplicate the markup used to render the image so we can use this in the alternative location.
- The current markup stays is place and is hidden by default
- When the widget mounts, if it detects the feature toggle, it activates the mark up we give it
- If no feature toggle is present, we tell the original image placement mark-up to show

This will be a very quick and minimal lift to accomplish.
