### ISSUE TITLE
Promo Banner Footer Spacing on VA.gov Homepage | Sub Pages

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37430]
#### High-level user story
As a Veteran I need to have access to footer links when promo banner is present on the page.

### Background
![Screen Shot 2022-02-22 at 3 03 48 PM](https://user-images.githubusercontent.com/70410912/155236266-3661c641-7a6c-4f4e-a0fd-41df890ab7d8.png)

### Desired Affect
- Users need to be able to click items in the footer when promo banners is present on the page.  Likely need to add a footer padding to ensure banner is not encroaching on footer links. 

### Tasks
- [x] Determine case and implement a footer padding from the promo banner to ensure links can be clicked as intended. 
- [x] Test locally to determine functionality / Validate in Staging before deploying to Prod.
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Home page footer links are clickable when promo banner is present on page. 
- [x] Local test are completed and show signs of success
- [x] a11y considerations are implemented in support

**Comment by longmd** [comment]
@brianalloyd , Is there a specific page this banner is on that I can see and inspect its placement to plan for the desired padding. Ideally... I would like to check out this template and then modify the component itself to add a class to the body to only have that padding in place when that component is active and have the normal padding in place when it is not active.

**Comment by brianalloyd** [comment]
@longmd its on the homepage and all subpages of VA.gov. Let me know if that helps or if you would like me to post some links. Thanks.

**Comment by brianalloyd** [comment]
Tested in Dev and this looks great.  Closing in support.
