### ISSUE TITLE
Create Transition Doc for Rated Disabilities

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#37442]
## Background
As this contract term comes to an end, we want to create a transition document to define the latest status of this feature, major decisions that led to the current status, next steps, and links to background material.

## Considerations
1. Rated Disabilities has launched, but there have been design system updates since and a punch list and wireframes were created for updates.
2. VSA leadership is working on a transition template

## Tasks
- [x] Create a transition doc for this feature
- [ ] Document research and design status, relevant decisions, next steps, and links to background material

## Acceptance Criteria
- [x] Transition document has been created
- [x] Transition document is shared with team and linked from [Sunset Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/sunset-strategy.md) (or other consolidated source TBD)

**Comment by sporeboy** [comment]
Initial commit of transition doc is here: [(Github link)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/rated-disabilities-transition.md)

**Comment by sporeboy** [comment]
Transition doc revised...
