### ISSUE TITLE
Create Transition Doc for Chapter 36

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#37445]
## Background
As this contract term comes to an end, we want to create a transition document to define the latest status of this feature, major decisions that led to the current status, next steps, and links to background material.

## Considerations
1. Chapter 36 has launched
1. [Template](https://docs.google.com/document/d/1N4Z9Dj5Qyp2uX5MlSWBN2p7bADnE2ee2hbvG3VBSP58/edit#)

## Tasks
- [x] Create a transition doc for this feature
- [x] Document research and design status, relevant decisions, next steps, and links to background material

## Acceptance Criteria
- [x] Transition document has been created
- [x] Transition document is shared with team and linked from [Sunset Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/sunset-strategy.md) (or other consolidated source TBD)
