### ISSUE TITLE
Configure local machines to connect to EVSS dev directly

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#3744]
## Story
As an engineer, I want to be able to have direct access to EVSS dev env as opposed to the local environment to better simulate the environment and be notified sooner of issues as I develop features.

## Goal
Currently the frontend for rated disabilities is querying data from `vets-api-mockdata`. To better reflect receiving data from a production environment, and to prepare for shipping to production, testing should be conducted against deployed virtual machine in AWS.

## Considerations
- AWS access is required

## Tasks
- [ ] Configure local dev environments to pull data from the AWS / VA dev environment.

## Acceptance Criteria 
- [ ] Local frontend pulls data from **AWS** instead of `vets-api-mockdata`. 
- [ ] Define and document for other teams to benefit from this process
