### ISSUE TITLE
[VAMC]  VET Center Run Book - Part 2 of 11 - Vet Center locations and contact -Review, compose, and update section of VET center run book [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37449]
## Story
As a Veteran, my VET center operations support personnel should have a updated run book to administer the VET center website, so I can find the most relevant and up to date information.

## Resources
[VET Center Run Book](https://salientcrgt.sharepoint.com/:w:/s/VSATeam/EUFSBd-WBytPq6P99uuXSX0BrJI0dh_oUT9R99DkP9Halw?e=Ve64Em)

## TASKS
Part 1 Section - Vet Center locations and contact
- [ ] Review section and flow
- [ ] Compose and write changes
- [ ] Save section to Content folder for cross check review

## Acceptance Criteria
- [ ] Final review is saved to word document
- [ ] If there is a kb article it is referenced
