### ISSUE TITLE
2/24/22 Prescription Tracking Training - Aurora, CO

### ISSUE THREAD

**Issue by djfredvs** [department-of-veterans-affairs/va.gov-team#37463]
## Description
Train Prescription Tracking Program - Aurora, CO
---

## Acceptance Criteria
Acceptance criteria are pre-defined requirements that must be met to mark a task as complete. What needs to be done to mark this task as complete?

- [X] Training email sent
- [X] Training Date Established 2/24  2 pm est
- [ ] Get reports-level access list to @chancetheoriginal
- [x] Conduct Training
- [x] Send follow-up resource email 
---
