### ISSUE TITLE
[Design] Wording explaining VAOS link

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37466]
# Description
From Stephen Barrs, "There was some confusion as to what the VAOS link was there for and if Veterans would know what to expect when tapping it.  Suggestion was to add some shorty preamble text before the link.  This is not a suggestion that we do that, but an ask for your expert thoughts around that idea, and if there has been any veteran feedback on the VAOS link.
([Original Slack message](https://dsva.slack.com/archives/C02GXKL8WM6/p1641844626048000))

# Tasks
- [x] Determine if we need another wording
- [x] Create wording options
- [x] Review with content

# Acceptance Criteria
- [x] Updated Sketch with final wording
- [x] Create FE ticket

**Comment by kristenmcconnell** [comment]
@loripusey - @niradatta1 and I actually talked through this with Danielle Thierry as part of the telephone changes. We are going to change the link to "Sign in to manage your appointment." [Wireframe](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/oYo79K2). This wording improves the Veterans expectations for having to sign in when they click on it. We also analyzed the features available on VAOS and the wording VAOS uses to explain themselves. We had many versions with "Sign in to add to your calendar, etc." However, we ultimately decided against wording, such as that, because of where the link actually lands. The user would still have to take a step or two to get to those features. As a result, we are going with the wording VAOS uses, which is "manage your appointment."

We would also like the link to land on the VAOS appointment list. We think the like currently landed the user here: https://www.va.gov/health-care/schedule-view-va-appointments/, which is really for unauth users. I will confirm in staging. 

Should we pull this ticket into this sprint, since it is almost done. I'll just confirm in staging, then it would be complete. We hope to present it as part of the telephone appointment changes scope to engineering.

**Comment by kristenmcconnell** [comment]
Completed review in staging and couldn't confirm. The link resulted in an error message. I tried it multiple times. @acrollet @brianseek Could you confirm that the "Go to another appointment" link on the check-in confirmation page goes to https://www.va.gov/health-care/schedule-view-va-appointments/ right now? Or do we skip that page and to go the appointment list within VAOS (after the Veterans authenticates)?

**Comment by brianseek** [comment]
@kristenmcconnell the way its coded, its supposed to go back to the appointments list still in the check-in app. There was an issue when we were testing at one point. There was going to be a follow up ticket but not sure if it ever got made.

https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/32784

**Comment by loripusey** [comment]
I don't think we should add a follow-up ticket if we don't know if there is a problem. We have a lot on our plate right now and a ticket will just get lost in the backlog as this is not in our priority list.

**Comment by kristenmcconnell** [comment]
@brianseek You are 100% right. UX also talked about a link to VAOS. I asked you about the wrong link. @loripusey I agree too.

**Comment by kristenmcconnell** [comment]
We will test this VAOS link within the upcoming telephone appointment usability study.

**Comment by kristenmcconnell** [comment]
@loripusey created the FE ticket.
