### ISSUE TITLE
Design - Auth Profile - Personal Info Revision - Verify Field-Level Hint Text Design & Accessibility

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37475]
## Background
Currently there exists no pattern for showing two distinct pieces of hint text together inline with a label, as shown in [this mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/3O1QmZD).

## Tasks
- [x] Meet with Shawna to discuss any options they already considered when adding field- hint text component to the [experimental design system](https://design.va.gov/experimental-design/hint-text).
- [x] Meet with Angela to discuss [subtext beneath the label](https://design.va.gov/experimental-design/hint-text#as-subtext-beneath-the-label) vs. [within an Additional Info component](https://design.va.gov/experimental-design/hint-text#within-an-additional-info-component), noting that Danielle and Samara would prefer the text be on page rather than linking to an R&S article due to the sensitive nature of the fields and Veterans' reluctance to share this information.  Having this info readily available could make or break someone's decision to provide this information.
- [x] Get feedback from Josh on accessibility concerns for different format options
- [x] Create a new mockup based on the above recommendations
- [x] Review new mockup with Samara and Marci

## Acceptance Criteria
- [x] Meet with Shawna to discuss any options they already considered when adding the hint text component to the design system.
- [x] Meet with Angela re: subtext vs. Additional Info component
- [x] Get feedback from Josh on accessibility concerns 
- [x] Create a new mockup
- [x] Review new mockup with Samara and Marci

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske when you have time before our 1 ET sprint planning, can you please make any necessary tweaks to this ticket and add an estimate?  Thank you!

**Comment by cgednalske** [comment]
Noting that we met to go over possible directions for hint text and decided on the same page layout, but with changes to the information included within the regular hint text vs. additional info components in order to reduce the amount of visible copy - which was particularly overwhelming on mobile. ([Marci's notes from the meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/meeting-notes/hint-text-review.md))

We're working with Danielle over in [#36862](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36862) to solidify final copy and placement. I will update this comment with the Sketch files once the newest changes have been confirmed and applied.

**Comment by cgednalske** [comment]
Noting that our decision was to add "Remove" buttons to each field and remove "This field is optional" from Gender identity and Sexual orientation, for the following in each field. Preferred name and Pronouns will include regular hint text only, whereas Gender identity and Sexual orientation will include an additional info dropdown component only.

<img width="674" alt="Screen Shot 2022-03-04 at 10 01 13 AM" src="https://user-images.githubusercontent.com/79372956/156806892-da276c06-be81-4c8c-807b-69d1d2a2fd8f.png">

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske.  If we learn this is still technically feasible, I'll include a task for determining whether we use "Delete" or "Remove" in the comprehensive ticket for updating the designs based on the MPI pivot.
