### ISSUE TITLE
[discovery] HLR: Update benefit type selection

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37470]
## Description

Phase 1 of the Higher-Level Review form only allowed for "compensation" type appeals to be submitted. Lighthouse has since removed the gating and all the following benefit types can now be submitted:

- Compensation
- Pension & Survivor's Benefits
- Fiduciary
- Insurance
- Education
- Veterans Readiness and Employment
- Loan Guaranty
- Veterans Health Administration
- National Cemetery Administration

Implement design from #37469 (https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/agPKR5D)

<img width="651" alt="Screen Shot 2022-02-28 at 2 21 19 PM" src="https://user-images.githubusercontent.com/136959/156053063-250a54a0-da2d-4ce3-b966-4f843f927b2c.png">

## Tasks

- [ ] Remove HLR v1 code, including `hlr_v2` feature flag
- [ ] Add new benefits type selection page to HLR to form flow immediately before contestable issues page
- [ ] Remove HLR wizard
- [ ] Add benefit type to contestable issues page title
- [ ] Add unit tests
- [ ] Update e2e test
- [ ] Update mock data

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
This work will be more extensive than planned. We need to ensure HLR v2 is stable before removing all v1 code and the wizard.

**Comment by saderagsdale** [comment]
@thehastingsp See if we can make this an enhancement. If it requires a lot of effort, hit pause.

**Comment by thehastingsp** [comment]
@saderagsdale this needs more time to understand how each of the benefits play out from a UX flow perspective.

**Comment by thehastingsp** [comment]
Recommend discovery to determine if all the flows and use cases surrounding the various benefit options are considered and supported.

**Comment by thehastingsp** [comment]
Adding a note to this ticket that we are working on this pattern for Supplemental Claims. This will be a new pattern that will replace the wizard and has been reviewed by the design system lead. Once we complete the work for Supplemental Claims we will be able to add this pattern to HLR.
