### ISSUE TITLE
[Design] Add user flow to day-of check-in product guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37489]
# Description
It would be helpful for the call center and MSA staff to have a visual representation of the user flow within the product guide. The day of check-in user flow is currently very detailed and needs to be simplified in order to be added to the product guide.

# Tasks
- [x] Create simplified user flow
- [x] Add to day of check-in product guide
- [x] Create a vertical version
- [x] Cross-check content with the product guide

# Acceptance Criteria
- [ ] Review with product, UX, and Stephen
- [ ] Send out Contact Center and MSAs

## Deliverable
- [x] [Abstract link](https://share.goabstract.com/3aa80ed5-fdab-45e2-8a99-3cc2c3664114): https://share.goabstract.com/3aa80ed5-fdab-45e2-8a99-3cc2c3664114
- [x] Vertical version of Check-in user flow for user guide

![Check-in user flow for user guide.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/cdd365c9-8beb-4988-855b-cade6a0e6ed2)

**Comment by zach-park** [comment]
User flow is updated and the vertical version of Check-in user flow for user guide is attached to the ticket. @benbrasso-agile6 @loripusey

**Comment by benbrasso-agile6** [comment]
Thanks. I'll take a look and get it added to guide.

**Comment by benbrasso-agile6** [comment]
@loripusey day of check in product guide is updated with the workflow image. it will be published to Git along with the LoROTA release. Updated files are in Google drive: 

https://drive.google.com/drive/folders/1c59S9fI3j8pW6FIc3GB4fu-poEeLT6sU

@loripusey in looking at the AC of this ticket, do we still feel Stephen and Contact Center should review the workflow file?

**Comment by loripusey** [comment]
I don't think they they need to review
