### ISSUE TITLE
[Discovery] [BE] [FE] Auth Profile - Confirmation Emails | Include Which # was Updated

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37483]
## Background

In a [Slack message](https://dsva.slack.com/archives/C909ZG2BB/p1645557051766679) 2/22/2022, Rob Garrison brought to our attention that when updating a phone number in the VA.gov Profile, the resulting email does not specify which phone number was updated (mobile vs. home).   He suggested that we adjust our email content so that the user gets more specific information about the update they made.
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/c7192ae6-afe4-4478-9ba4-95a6943aa63a)

10/11/22: Additionally when changing an address the confirmation email does not indicate whether home vs mailing was updated.

#![Screen Shot 2022-10-11 at 3.46.08 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/2dcd3c36-39f9-46c3-b755-c7c83339ea98)

## Tasks
- [x] Determine back end tasks needed to make change recommended above
- [x] Determine front end tasks needed to make change recommended above

## Acceptance Criteria
- [x] Determine back end tasks needed to make change recommended above
- [x] Determine front end tasks needed to make change recommended above
- [x] Schedule a joint discovery review meeting to discuss findings
- [x] Work with PM to create new tickets

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - since this is an older ticket, I wanted to test with my prod account before pulling into our backlog. 

I updated both my home and mobile number last night but haven't received any emails confirming the change to date. Wanted to double-check that we are still sending emails, and if so, would you mind changing your phone number on your prod account so we can see if you get the email?

**Comment by SKasimow** [comment]
Will do

**Comment by Samara-Strauss** [comment]
Given that we don't have access to staging emails, I think validating with our prod accounts is an OK way to validate.

**Comment by SKasimow** [comment]
I'm happy to test @tpharrison. Do you just need our emails for the prod accounts to turn on for us?

**Comment by tpharrison** [comment]
Yep.  It's not going to be in prod until later today.  I'll test with mine first and let you know when its ready others to test.

**Comment by SKasimow** [comment]
Sounds good!

**Comment by SKasimow** [comment]
Hi @tpharrison - tested in my prod account and worked like a charm. Changed both mailing address and then work phone # and received emails with these changes noted.

**Comment by tpharrison** [comment]
@SKasimow Any additional testing needed or can I close this out?

**Comment by SKasimow** [comment]
@tpharrison - I think we can close this out and release to production.

**Comment by tpharrison** [comment]
Do you want me to turn on the feature for 100% users now or wait until Monday?

**Comment by SKasimow** [comment]
Ah...good point. We should wait until Monday :)
