### ISSUE TITLE
[BE] - Auth Profile - Personal Info Revision - Complete Website-API integration testing

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37484]
## Background

Once integration with the VA Profile has been completed, testing will be required to confirm that all PI communication between the va.gov website and vets-api is working as expected.

## Tasks

Confirm that the following API actions are available and working properly:
- [ ] Identify staging users for testing functionality
- [ ] Retrieve PI data for a user (pronouns, gender identity, preferred name, sexual orientation)
- [ ] Add/Update/Delete Pronouns
- [ ] Add/Update/Delete Gender Identity
- [ ] Add/Update/Delete Preferred Name
- [ ] Add/Update/Delete Sexual Orientation

## Acceptance Criteria
In the staging environment, ensure that the following actions can be performed and that the data being returned is correct for a staging user:

- [ ] Retrieve PI data for a user (pronouns, gender identity, preferred name, sexual orientation)
- [ ] Add/Update/Delete Pronouns
- [ ] Add/Update/Delete Gender Identity
- [ ] Add/Update/Delete Preferred Name
- [ ] Add/Update/Delete Sexual Orientation

> Note: The VA Profile demographic API does not provide DELETE methods.  Instead, a PUT request that has the `end_date` set to the `current_date` will result in a soft delete of the record.  Subsequent GET requests will not return the record.

**Comment by tpharrison** [comment]
This ticket is being zeroed out and replaced by the following tickets:

- #38791 BE - Auth Profile - Personal Info Revision - Integration Testing for Preferred Name
- #38792 BE - Auth Profile - Personal Info Revision - Integration Testing for Gender Identity
- #38793 - BE - Auth Profile - Personal Info Revision - Integration Testing for Pronoun
- #38794 BE - Auth Profile - Personal Info Revision - Integration Testing for Sexual Orientation

**Comment by MarciMcGuireGCIO** [comment]
Noting that I'm creating FE tickets that correspond to the BE tickets.  Also noting that will will NOT have a delete function since VA Profile is unable to support it for all fields.
