### ISSUE TITLE
[BE] Auth Profile - Personal Info Revision - Estimate remaining BE tasks, duration

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37485]
## Background
In order to plan when we will schedule reviews prior to launching this enhancement, we need an estimate of remaining back-end tasks, as well as an estimate of how long they are expected to take once the API is available to you and can be tested in a lower environment.

## Tasks
- [x] Create list of additional back-end tasks to complete project
- [x] Work with PM to create new tickets and estimate
- [x] Provide a high-level estimate of duration assuming no major blockers

## Acceptance Criteria
- [x] Create list of additional back-end tasks to complete project
- [x] Work with PM to create new tickets and estimate
- [x] Provide a high-level estimate of duration assuming no major blockers

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison when you have a few minutes, can you please take a look at this ticket and drop an estimate on it?  Thank you! :)

**Comment by tpharrison** [comment]
Added/updated PI tickets.
