### ISSUE TITLE
[SW-Content] Review, Update, copy edit and publish changes to R&S decision page [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37491]
##  Story
As a Veteran I need to have full access to decision reviews, so I can download them and/or review as required for my decision review options.

## Resources
[R&S page](https://www.va.gov/resources/choosing-a-decision-review-option/)

## TASKS
- [x] Review, update, and implement decision review PDF language "Download (PDF)" following SW-Content guidelines and standards.
- [x] Have page reviewed by Editor

## Acceptance Criteria
- [x] All links are updated with appropriate language
- [x] Preview link is provided to Product Owner prior to publishing
- [x] Page(s) is published

**Comment by lunascoop** [comment]
Hi @psanders86 this page is ready for review. I updated the pdf and forms links on the page to match our standards and new guidance for linking VA find form pages.

Here's the slack thread related to this work: https://dsva.slack.com/archives/C01K37HRUAH/p1645627302299989

Choosing a decision review option: http://preview-prod.vfs.va.gov/preview?nodeId=23290

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the preview link of the updated links. We also updated the links within the chart so they go to the find forms pages using the new language. http://preview-prod.vfs.va.gov/preview?nodeId=23290

Let me know if this is good to publish.

A question came up during a team discussion about our mention of February 19, 2019, possibly being dated and misleading. It's mentioned on this page, other decision review–related pages, and the new COE work we're doing (including the mock-up screens). For both the Higher-Level Review and the Board Appeal, you have up to one year after VA has made their decision to submit your form. So you wouldn't be able to appeal a VA decision dated before February 19 at this point.

If we should remove this date, we can work up language we would use in its place. For example the intro to this page would be: If you disagree with a VA decision, you may be able to file a Supplemental Review, Higher-Level Review, or Board Appeal. Learn more about the 3 options from our chart.

**Comment by bethpottsVADEPO** [comment]
@RLHecht The stakeholders love mentioning that date! But I agree that it doesn't make sense here. Would you reach out to ask this of Shireen in the email string? You can tell her you noticed this during the final content QA step before publishing the PDFs on this page. Include the part about "you have up to one year after VA has made their decision to submit your form" which makes the date irrelevant in the context of this sentence.

**Comment by RLHecht** [comment]
Update: The stakeholders came back to us and asked us to leave the date in, so publishing the page now and will let them know once it's live.
