### ISSUE TITLE
[Research] - Auth Profile - MHV Profile Research - VA.gov and MHV profile evaluation and comparison

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37495]
## Background
There is a desire to eventually bring My HealtheVet (MHV) into VA.gov and to include profile-related fields in the VA.gov profile.   This issue is to do initiial discovery to evaluate and compare the information available on VA.gov vs. MHV profiles.

## Tasks
- [ ] Review profile info available on MyHealtheVet and VA.gov profile
- [ ] Compile a list or comparison matrix of the fields discovered

## Acceptance Criteria
- [ ] Review profile info available on MyHealtheVet and VA.gov profile
- [ ] Compile a list or comparison matrix of the fields discovered

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
@Samara-Strauss and @MarciMcGuireGCIO just when I thought I wasn't going to finish this in this sprint - I have [an audit report ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/comparison/findings.md)with 3 minutes to spare :)

I'm not sure whether or not you were expecting a report (I wasn't planning on doing this), but I wanted to make things digestible for you both, and for Future Liz as I continue this work.

Please let me know if you have any questions or changes you'd like to see to the doc.

**Comment by MarciMcGuireGCIO** [comment]
Whoo hoo!  Awesome, @andaleliz !

**Comment by Samara-Strauss** [comment]
This is great! I think we just want to make it clear somewhere (doesn't have to be in this write-up) exactly which of the profile fields already exist on VA.gov, which are slated for removal, and which are moving over. I don't think it will be a lot that's moving over, but know what is will help us set up a plan for getting that info into VA.gov and talking about different transition options for retiring the MHV profile.

**Comment by MarciMcGuireGCIO** [comment]
+1. This is fantastic info, @andaleliz!

**Comment by andaleliz** [comment]
Thanks for the feedback, I'm glad it's useful info to you both.

>exactly which of the profile fields already exist on VA.gov, which are slated for removal, and which are moving over.

I have this in the spreadsheet referenced in the doc, but there are several "TBD" items, such as "What is your relationship with VA?" I have a couple of questions though:

>exactly which of the profile fields
Do you literally just mean the fields in the form on the "My Profile" page, or does this apply to all the "things users can do and see" from the Personal Information (our profile equivalent) section of MHV?

>which are moving over.
Moving over to VA.gov at all (including health apartment), or moving over to our VA.gov profile?

When we have the final write-up, I can create a table in the markdown file with that information so it's easy to read. It's an extra step for people to have to download the spreadsheet.

**Comment by Samara-Strauss** [comment]
Liz, I'm so sorry -- I missed the spreadsheet. I'm sorry. It's great and answered all of my questions. Thanks!
