### ISSUE TITLE
Schedule Usability Session for COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37499]
## Goal
As a designer/researcher for the eBenefits Team, I want to be able to understand how a Veteran is currently interacting with this feature holistically so that I can create a more accurate description of what needs to be further developed or iterated upon.

## Considerations
In another ticket:
- Use a conversation guide (convert [this one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-convo-guide.md) to the [new template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))
- Use research plan (convert [this one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-1/coe-usability-1-research-plan.md) to the [new template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md))
- Conduct a usability session that answers pain point questions and informs the team what the best thing to build might be
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)

## Tasks
- [x] Coordinate sessions with user research partner (Perigean), asking them to take notes 
- [x] Review and edit research plan/convo guide as needed
- [x] Use the [research plan](#), and included [conversation guide](#) to conduct sessions, if scheduled

## Acceptance Criteria
- [x] Usability study has been scheduled, and
- [ ] conducted if applicable

**Comment by candy-gcio** [comment]
[Research repo card](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/91)
