### ISSUE TITLE
[FE] [BE] - Auth Profile - Bad Address Indicator - Backend & Frontend collaborate on calling API from FE to see indicator

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37493]
## Background

The bad address indicator exists in a VA Profile API.  The Frontend needs to be able to evaluate this indicator in order to determine whether or not to display a message indicating that the address has been flagged as bad.

## Tasks
- [x] Tom & Adam work together so that Adam has a good understanding of how to evaluate the bad address indicator flag.
- [x] Adam creates list of task(s) required to implement this flag evaluation into the FE

## Acceptance Criteria
- [x] Tom & Adam work together so that Adam has a good understanding of how to evaluate the bad address indicator flag.
- [x] Adam creates list of task(s) required to implement this flag evaluation into the FE

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison @adamwhitlock1 can you both take a peek at this task and pop an estimate on it?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @adamwhitlock1 !  Should I create a ticket for each of those bullet items?

**Comment by tpharrison** [comment]
@adamwhitlock1 - Staging user `vets.gov.user+71@gmail.com` has a BAI of `true`.  I can turn the bad address back on when needed.  Let me know if you have any questions.

cc @MarciMcGuireGCIO

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 - The following staging users have a BAI of _true_:
> 
> * [vets.gov.user+71@gmail.com](mailto:vets.gov.user+71@gmail.com)
> * [vets.gov.user+73@gmail.com](mailto:vets.gov.user+73@gmail.com)
> 
> If you update the address (which will turn BAI off), I can turn it back on when needed. Let me know if you have any questions.
> 
> cc @MarciMcGuireGCIO

Awesome! Thanks @tpharrison sounds good

**Comment by MarciMcGuireGCIO** [comment]
Thank you both, @tpharrison and @adamwhitlock1 !
