### ISSUE TITLE
Adjust COE Dropdown

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37507]
## Background
We need to make some adjustments to the COE dropdowns for military branches

## Considerations
Might be a schema change, and a key might be changed as well; coordinate with Kathleen if needed

## Tasks
- [ ] Remove `NOAA` and `Public Health Service` and replace them with `OTHER`
- [ ] Update schema file

## Acceptance Criteria
- [ ] Branches have been addressed
- [ ] A PR has been requested for merging

**Comment by jerekshoe** [comment]
I think we can close this guy. Looks like a dupe of #37508
