### ISSUE TITLE
Adjust COE Dropdown

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37508]
## Background
We need to make some adjustments to the COE dropdowns for military branches

## Considerations
This is a schema change, so there will be multiple PRs needed. `militaryBranch` will also be changed to `serviceBranch` to comply with the `ServicePeriodView` component provided by the form system

## Tasks
- [x] Remove `NOAA` and `Public Health Service` and replace them with `OTHER`
- [x] Update schema file

## Acceptance Criteria
- [x] Branches have been addressed
- [x] A PR has been requested for merging
