### ISSUE TITLE
Audit inbound Drupal pages to form 26-1880 & Your COE tool

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37504]
### Background
VA Form 26-1880 and the Your COE tool have several public pages that link to them. Extensive content changes have been made to the main COE landing page; these changes will need to be reflected in the other inbound pages.

### Considerations
- Extensive copy changes have been made to the primary landing page; these have been reviewed and approved by LGY
- The landing page for the Your COE tool is new
- Generally all references to "apply" will need to change to "request"--including variations

### Tasks
- [x] Review feature flow and IA recommendations
- [x] Confirm all inbound URLs
- [x] ID content requiring revision
- [x] Make copy revisions as needed
- [ ] Consult with Sitewide Content

### Acceptance Criteria
- [x] Create document with text revisions mapped to inbound screens

**Comment by sporeboy** [comment]
There are five Drupal pages with inbound links to the COE form intro. Three need minor text revisions (Links to VA.gov):
- [Eligibility](https://www.va.gov/housing-assistance/home-loans/eligibility/)
- [Surviving spouse programs](https://www.va.gov/housing-assistance/home-loans/surviving-spouse/)
- [Home-buying process](https://www.va.gov/housing-assistance/home-loans/home-buying-process/)

One Drupal page need significant revisions (Links to UXPin prototype):
- [How to request a COE](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312)

One Drupal page is new (Links to UXPin prototype):
- [Check COE status](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140810030)

**Comment by sporeboy** [comment]
The three pages needing revisions generally need instances (and variations) of "apply" will need to be changed to "request."

Additionally, on the Eligibility screen, the “How do I apply…” section will some design revision as well (remove eBenefits reference, use action link, re-write text, etc.)
