### ISSUE TITLE
Pass CSP_Method to vets-api

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#37511]
## Issue Description
Pass the CSP_METHOD to vets-api to ensure the appropriate CSP Method will be used instead of the authncontextclassref

---
## Tasks
- [x] Modify the keepalive function to pass the CSP_METHOD
- [x] Collaborate with BE Identity team to come up with a plan

## Acceptance Criteria
- [x] CSP_METHOD is passed to the backend

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
