### ISSUE TITLE
[Design] Create Telemedicine User Flow

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37522]
# Description
After creating concept sketches for telemedicine in #37521, then create user flow documents.

# Tasks
- [ ] Create drafts of user flow

# Acceptance Criteria
- [ ] Review user flow document with check-in team (UX, product, engineering)
- [ ] Link to Sketch provided in this ticket and via Slack
