### ISSUE TITLE
[UX] [Design] Prototype for Virtual Visit Content in Pre-Check-in 

### ISSUE THREAD

**Issue by jparker0425** [department-of-veterans-affairs/va.gov-team#37520]
## User Story 
As a Veteran, I want to complete Pre-Check-in for a virtual visit. 

## Description 
To assist in research for adding virtual visits to the Pre-Check-in flow, an interactive prototype is needed to test the proposed design with Veterans. 

## Tasks
- [ ] Create prototype in UXPin

## Acceptance Criteria
- [ ] Review with check-in team (UX and product)
- [ ] Add links to the prototype in the conversation guide
- [ ] If not already done, submit the research plan and conversation guide for review/to begin recruitment.
