### ISSUE TITLE
[Platform Infrastructure] Create default infrastructure request template

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#37527]
## Description
There should be a standardized template for infrastructure requests. There may be _multiple_ templates and requests needed, depending on the type and scope of infrastructure needs. But - for now, at least - there should be a default template for general requests that do not yet have a specific template. 

## Background/context 
- Teams requesting new infrastructure are often unclear on where to begin 
- Requests do not often capture a clear definition and the requirements needed to fulfill the request 
- There is an existing "Ops Issue Template" in use, but...
- That should be deprecated for use outside of the Infrastructure Team in favor of this new template

Related issues: 
- #36852
- #37352

## Technical notes
- Make the template machine-readable if possible

---
## Tasks
- [x] Create a new default template with accurate information

## Acceptance Criteria 
- [x] The updated template is ready to be shared with VFS teams, et al

**Comment by jhouse-solvd** [comment]
Some info that might be useful to capture in the request template: 

- team name 
- application name 
- application repo or code
- product manager 
- product owner 
- infrastructure needed 
- is this a new setup or modification of an existing configuration? 
- if modifying an existing configuration, please provide links to relevant files

**Comment by jsgarmon** [comment]
I would love these kinds of requests to come with a stamp of approval from someone with authority to do so. Mike Chelen had mentioned the Collab Cycle review process. Is there a way we can verify that any new design has been through this?

Slack thread on this:
https://dsva.slack.com/archives/CTYQL39FE/p1645807626801329

I didn't really get a satisfactory answer to "who is gate-keeping this?". It seems it is still up to whatever infra engineer this gets assigned to to determine if these sorts of requests are on the up-and-up or not. My ideal is that these requests come with somebody's thumbs up (product owner? security team?), so that we can safely assume we are good to go.

**Comment by jhouse-solvd** [comment]
> I would love these kinds of requests to come with a stamp of approval from someone with authority to do so. Mike Chelen had mentioned the Collab Cycle review process. Is there a way we can verify that any new design has been through this?
> 
> Slack thread on this: https://dsva.slack.com/archives/CTYQL39FE/p1645807626801329
> 
> I didn't really get a satisfactory answer to "who is gate-keeping this?". It seems it is still up to whatever infra engineer this gets assigned to to determine if these sorts of requests are on the up-and-up or not. My ideal is that these requests come with somebody's thumbs up (product owner? security team?), so that we can safely assume we are good to go.

That's great feedback. I'm not sure what that process might look like at the moment, but @mchelen may have some guidance here.

**Comment by jhouse-solvd** [comment]
As a follow-up item, here's some example documentation that could be created to support an infrastructure request for an S3 bucket: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/38079#issuecomment-1063383935

**Comment by jhouse-solvd** [comment]
Here's an example of the Platform Console UI team using the request: #39431

Looks like it went well. 

We may want to add some default acceptance criteria like: 

- [ ] Create resources 
- [ ] Add permissions to resources
- [ ] Verify user can access resources

**Comment by jhouse-solvd** [comment]
The template exists and AC have been met for this issue. The template is still marked WIP, but that will change once we go live with it. 

We'll want to communicate this change to SRE so that they can refer people to the new template for standard infrastructure requests. 

Closing.
