### ISSUE TITLE
[Design] Create Telemedicine Pre-check-in Concept Sketches

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37521]
# Description
After meeting with the team to understand the telemedicine uses cases, draw out various design concepts for each use case handling telemedicine appointments in pre-check-in.

# Tasks
- [x] Brainstorm ideas
- [x] Sketch out ideas/concepts

# Acceptance Criteria
- [x] Prioritize different ideas
- [x] Decide what options to test

**Comment by kristenmcconnell** [comment]
UX met on March 4 and added our ideas to this Mural: https://app.mural.co/t/vfscie8528/m/vfscie8528/1646416078863/79c62546e237625c7c95cf0dddf0e4f3acbf8d04?sender=niradatta0802

We also listed out our outstanding questions with the document.

Our next steps are to:
- Talk to Stephen Barrs to get some of our scope questions answered.
- Talk to VVC team to understand current workflow
- Talk to VeText on how they handle telemedicine appts.
- Begin to wireframe:
  - changes to the pre-check-in access points (text vs. email)
  - changes to the confirmation page or another solution to help the transition from pre-check-in to check-in for telehealth appointments.
  - we must also take into account all the different telemedicine appointment types
