### ISSUE TITLE
[VAMC] Part 4 - Correct Menu Parent items for pages incorrectly saved in Menu admin & document URL alias [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37538]
## Story
As a Veteran, I should have clear menu locations and links/URLs for additional information and resources, so I can quickly find this information and ignore those that do not pertain to my health care journey.

## TASK
- [ ] Review report to document items that can be changed immediately
- [ ] Discuss with IA the pages that will require redirects and ones that can be changed immediately
- [ ] Submit recommendations for change to the PAOs to change pages if IA agrees.

## Acceptance Criteria
- [ ] Artifact of menu items that will be changed.
- [ ] Communication to VHA DM and PAOs regarding menu change requirements.
