### ISSUE TITLE
[VAMC] Combine Vet Center tracking lists & development chart/graph [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37540]
## Resources
VAMC - Report 

## TASKS
- [x] Combine reports for VET Center tracking
- [x] Develop graph and chart for reporting 

## Acceptance criteria
- [x] Document that has merged data
- [x] Draft Chart that can be used in reporting

**Comment by ltrombley** [comment]
Task #37540 - Vet Center tracking lists & development chart/graph - is Complete and moved to Validate.
