### ISSUE TITLE
[Design] General technical and loading error message

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37543]
# Description
We're solving for two use cases: 
1) When a Veteran is editing their information within pre-check-in AND something went wrong (general error) AND/OR a page-load error, we need to figure out what this error states looks like.

2) When a Veteran has already authenticated and in the middle of completing pre-check-in, AND a general technical error occurs AND/OR page loading error occurs

Two wireframes currently exist:
- [General error wireframe](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbEbLjG)
- [Page load wireframe](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/nRORYAg)
Can either of these designs be used for this use case?

# Tasks
- [ ] Talk to engineering and decide if we're addressing general technical error ONLY or general technical error AND page load error 
- [ ] Create mockups for use case 1
- [ ] Determine if the above designs can be leveraged or updated if needed for use case 2
- [ ] Review with content team and accessibility (if needed or save till a later point)

# Acceptance Criteria
- [ ] Review final designs with product and UX
- [ ] Create FE ticket
- [ ] Update the git-hub error state ['source of truth'](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md)

**Comment by niradatta1** [comment]
@mdewey Confirming that there is an FE ticket to cover this error message use case (generic message for when there's a technical error during pre-check-in). 'cc @jparker0425

**Comment by ytsaoca** [comment]
@kristenmcconnell  
Was the first use case already addressed with [#36793](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36793)?
If not, could you explain more about this use cases? 

And for the Use Cases 2, I think we can use General error wireframe because @mdewey mentioned that  most errors can’t be solved by refreshing.
What do you think?

**Comment by ytsaoca** [comment]
Use this wireframe for pre-check-in general error: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbEbLjG
