### ISSUE TITLE
[Design] Editing Edge Cases: [Update] button in Email address’ edit page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37545]
# Description
An error message appears if something goes wrong when the Veteran hits the [update] button for email address (also for all Update buttons). 

Another warning message is needed once a Veteran returns to the overview page, because the update may not show until the next day. 

So, this ticket will result in two error messages.

# Tasks
- [ ] Create new content and designs in Sketch
- [ ] Review with content

# Acceptance Criteria
- [ ] Review final designs with product and UX
- [ ] Create FE ticket
