### ISSUE TITLE
[Design] Editing Edge Cases: Removing prefilled editing input

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37546]
# Description
If prefilled editing inputs are removed (required vs not required), do we show error messages? If so, how?

# Tasks
- [ ] Create new content and designs in Sketch
- [ ] Review with content

# Acceptance Criteria
- [ ] Review final designs with product and UX
- [ ] Create FE ticket
