### ISSUE TITLE
[Design] Editing Edge Cases: Time expired (after midnight) up until their appointment time with valid link

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37544]
# Description
A Veteran attempts to pre-check-in after 12:00am on the day of their appointment. We need a messaging to let user know that they can no longer complete pre-check-in prior to their appointment. 
- Engineering isn’t track this currently, but they can (per Adrian). If they can, there should be a specific message related to the use case. 

# Tasks
- [ ] Create new content and designs in Sketch
- [ ] Review with content

# Acceptance Criteria
- [ ] Review final designs with product and UX
- [ ] Create FE ticket for this new scenario (i.e. midnight to appointment time on day of appointment)

**Comment by kristenmcconnell** [comment]
A slack thread with some info relate to this topic: https://dsva.slack.com/archives/C02UP02HHGX/p1646230645475379

**Comment by ytsaoca** [comment]
Mockup: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/eKY1pka
