### ISSUE TITLE
[PM] - Auth Profile - Bad Address Indicator - Review VA Notify UI, identify content, design required

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37557]
## Background
We will be triggering a bulk email to all Veterans whose current address is flagged as invalid using VA Notify.   This task is to determine what information we will need to provide in order to generate this email.

VA Notify is accessed using GitHub credentials while logged into the VA Network.
Staging URL: https://staging.notifications.va.gov/
Prod URL: https://notifications.va.gov/

## Tasks
- [x] Review VA Notify UI
- [x] Document fields available
- [x] Identify fields we are likely to use
- [x] Identify any design requirements
- [ ] Review with team

## Acceptance Criteria
- [x] Review VA Notify UI
- [x] Document fields available
- [x] Identify fields we are likely to use
- [x] Identify any design requirements
- [ ] Review with team
