### ISSUE TITLE
New Platform page for research participant safety 

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#37550]
## User Story
_"As a (persona), I (want to), (so that)."_

---

## Description
There is a github page with information that isn't on the Platform site, but is important enough that is should be.

---

## Artifacts Needing Updates

- A new Platform Site page for Participant and Researcher Safety
- [Platform site page](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Participantsafetyandrespondingtoemergenciesduringremoteresearchsessions)where a new Participant Safety page could be link from
- Information for the new Platform page should come from Github [Participant Safety Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/research/safety-protocol.md#creating-a-safe-space-for-participants)
_Please note that other pages may need edits_

---
## Tasks
_Other tasks may be required, please review ticket and add any additional tasks_
- [ ] Create a new Platform site page for Participant Safety and Researcher Safety
- [ ] Add link this new Participant Safety and Researcher Safety page to [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-5.Conductsessions)
- [ ] Add  link this new Participant Safety and Researcher Safety page to [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [ ] Add emergency exit text to the [Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
---

## Acceptance Criteria
_Additional AC may exist, add any additional AC as needed_
- [ ] "Insert Page Name" Confluence document has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#3.-Updating-existing-Confluence-documentation)
- [ ] "Insert Page Name" Confluence document has been [created per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#4.-Creating-new-Confluence-documentation)
- [ ] "Insert GitHub template" GitHub template has been [created per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#2.-Creating-new-GitHub-issue-templates)
- [ ] "Insert GitHub template" GitHub template has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#1.-Updating-existing-GitHub-issue-templates)
- [ ] "Insert Platform Website Page" on Platform Website has been [updated per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#5.-Updating-existing-Platform-Website-documentation)
- [ ] "Insert Platform Website Page" on Platform Website has been [created per guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance#6.-Creating-new-Platform-Website-documentation)
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Governance Team Resources
[Documentation Update Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/WIP+Documentation+Update+Guidance) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@claytonzook I think that you did a great job! I made some changes to the user stories and AC.
- For two of the user stories, I added a 'so that' section in quotation marks to make sure that we have the full intent of these pages down.
- I updated and rearranged the Acceptance Criteria to match the Tasks. 
I think you covered the tasks great and appreciated the background info. And especially adding the tech-debt label, I think this story is good to go!

**Comment by claytonzook** [comment]
@chaseakirby I had indeed missed that. It's now added in [Research Review section](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+Checklist#2.-Research-review) for the next Platform publish. Thanks!
