### ISSUE TITLE
Design intent [My Education Benefits - Authenticated 22-1990e TOE Form Updates]

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#37551]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [ ] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [x] Product outline https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/TOE%2022-1990e%20Updates/TOE%20Product%20Outline.md
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes  https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=cd2025816d4c32b5bce925efad20e08039f6e2105fec73101e0ba541dfcc99a4&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01 
- [x] User flow (Top of Invision board) https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=cd2025816d4c32b5bce925efad20e08039f6e2105fec73101e0ba541dfcc99a4&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- [ ] Research
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by Saraharaba8** [comment]
No accessibility feedback on my end!

**Comment by CherylEvans** [comment]
No Content feedback.  Awesome detail in the Flows/WF!!

**Comment by seanasewell** [comment]
Zoom recording - https://us06web.zoom.us/rec/share/gZ53YA7KIUak7W4yxAzf5ugsRXXFRG2TLSgvnUXsgiIiRIo-95tUT6zfbP5t-cwF.GYeH5dOIjfdfzhwy Passcode: 691jq$n*

**Comment by claytonzook** [comment]
No feedback on research. Just a note that as you plan for it, we love to see research that is iterative, taken in small chunks, and considers inclusivity.

**Comment by shiragoodman** [comment]
hey @alexander-ferzola  - regarding your last comment, please be sure to submit your [research plan review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) request as soon as you're ready. The Research Plan is one of the artifacts we look at for [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html), so it would be great if you'd already started that process and gotten feedback. The only thing we ask if that you try and schedule your Midpoint Review before meeting with Veterans in your research study, not schedule your Midpoint Review before beginning the Research Plan Review process. Hope that makes sense! Please let me know if you have any questions.

**Comment by alexander-ferzola** [comment]
Thank you all for the feedback. Wanted to leave the latest link to our midpoint review ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/39542) before closing this ticket. Reach out if you have any questions!
