### ISSUE TITLE
Create Inventory to Document Current State of Endpoint Environment

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#37569]
https://docs.google.com/spreadsheets/d/14iNeWOyaMe0aqVtgfCqTE7cl3xAfQ7YJDsjRbADOXCk/edit#gid=681198224&fvid=316271190

## Problem Statement

We do not adequately understand the current endpoint environment. We do not know
- Who owns what in the platform
- The traffic flowing through each endpoint
- Which endpoints are platform owned vs VFS owned

## Hypothesis

We believe that creating an inventory that provides clarity for the above items will enable OCTODE in their strategy-making processes thereby ensuring a better informed integration experience roadmap

## Definition of Done

- [ ] Who owns what in the platform
- [ ] The traffic flowing through each endpoint
- [ ] Which endpoints are platform owned vs VFS owned

**Comment by ewilson-adhoc** [comment]
This epic has been completed
