### ISSUE TITLE
FE Unit test for SignInApp

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37566]
## Issue Description
Create a robust unit test for `src/applications/login/containers/SignInApp.jsx`

---
## Tasks
- [ ] Verify LoginContainer renders, and declared props are expected
- [ ] Verify ?app param works as expected, and sets externalApplication prop on LoginContainer
- [ ] Verify ?auth=logged_out works as expected, and sets loggedOut prop on LoginContainer
- [ ] Verify componentDidUpdate logic to ensure verify route is pushed when expected

## Acceptance Criteria
- [ ] Unit tests created for SignInApp
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
