### ISSUE TITLE
[UX] Talk to Profile team to confirm interaction patterns

### ISSUE THREAD

**Issue by niradatta1** [department-of-veterans-affairs/va.gov-team#37576]
We need to confirm how Profile is currently handling the following use cases (listed in our edge case document): 
1) the user accidentally goes back / navigates out of the editing mode 
2) blank field errors for all form pages (included for required and optional)

##Tasks

- [x] Talk to Christina Gednalske
- [x] Document what their current approach is to 1) and 2) above (link to wireframes where applicable)

##Acceptance Criteria
- Decision reached on how to address the edge cases 1 and 2 listed in this ticket
- [x] Back / navigation: Consolidated html modal to be displayed in browser back navigation (as well as edit [Cancel]) 
- [x] Blank field errors for all form pages (included for required and optional). This item is currently work-in-progress. It will likely be needed to carry onto the next sprint as there is a dependency on VA profile's team decision.

If feasible: 
- [x] [Updated wireframe link: Back / navigation](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/v/15dwW8/a/4an9O8A/r/jem750)
- [x] [Updated wireframe link: Blank field errors for all form pages](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/v8nbOo4)
- [x] Create FE tickets
- [x] Update [error state source of truth in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md)

**Comment by zach-park** [comment]
@loripusey @jparker0425 @kristenmcconnell 
The blank error state (form validation) wireframe is ready for review now. 
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/v8nbOo4
Thank you!

**Comment by loripusey** [comment]
@zach-park Can you provide a little more information on this workflow? I like the wireframe but am unsure when we see the required field indicators

**Comment by zach-park** [comment]
Hi @loripusey yes, the validation error shows up when a user deletes existing input data from a required form. For example, if the user deleted the pre-filled Zip code, the validation error appears as shown in the wireframe.

**Comment by loripusey** [comment]
Thanks @zach-park, I get it now.
