### ISSUE TITLE
FE Unit test for LoginHeader

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37575]
## Issue Description
Create a robust unit test for LoginHeader

---
## Tasks
- [ ] Verify Sign In copy is visible
- [ ] Verify LogoutAlert rendered when necessary
- [ ] Verify DowntimeBanners rendered

## Acceptance Criteria
- [ ] Unit test created for LoginHeader
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
