### ISSUE TITLE
FE Unit test for DowntimeBanner

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37579]
## Issue Description
Create a robust unit test for DowntimeBanner

---
## Tasks
- [x] Mock downtime state, and verify appropriate banners are rendered

## Acceptance Criteria
- [x] Unit test created for DowntimeBanner
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
