### ISSUE TITLE
FE unit test for VerifyPage

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37570]
## Issue Description
Create a robust unit test for `src/applications/login/components/VerifyPage.jsx`

---
## Tasks
- [ ] Validate rendered copy
- [ ] Validate click function goes to correct location

## Acceptance Criteria
- [ ] Unit test created for VerifyPage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
