### ISSUE TITLE
FE Unit test for LoginContainer

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37573]
## Issue Description
Create a robust unit test for LoginContainer

---
## Tasks
- [x] Verify VA logo renders as expected
- [x] Verify LoginHeader renders, and declared props are expected
- [ ] Verify LoginActions renders, and declared props are expected
- [ ] Verify LoginInfo Renders, and declared props are expected

## Acceptance Criteria
- [ ] Unit test created for LoginContainer
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
