### ISSUE TITLE
NOD: Update about form page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37583]
## Description

With the impending release of the Notice of Disagreement form, we need to add a form start button to the about form page &ndash; https://www.va.gov/find-forms/about-form-10182/

Also, while searching for the about form page, I entered "NOD" as the search term, but got no results

<img width="746" alt="No results were found for 'NOD' message" src="https://user-images.githubusercontent.com/136959/155574691-9752c71c-878e-4d19-a21c-209ef1c3b06b.png">

## Tasks

- [x] Add "Online tool" section to page
- [x] Add "Go to online tool" action link
- [ ] Include "NOD" as a form search term keyword

## Definition of done

- [x] All tasks complete

**Comment by lunascoop** [comment]
@RLHecht @psanders86 Is the last Task in the description above something we can do (Include "NOD" as a form search term keyword)? Is that work for the VA Forms team or another team?

**Comment by RLHecht** [comment]
Yeah, there's no option for entering key words into the Drupal page, so this is something that the Forms team would need to handle. FYSA @Mottie

**Comment by RLHecht** [comment]
@Mottie Is this something that should be added to the Find Forms page now or it's awaiting the tool launch? If it's waiting for the launch is there a date?

**Comment by Mottie** [comment]
@RLHecht we're still waiting to hear back from the Board about launch. We're ready to go when they give us the go ahead.

**Comment by Mottie** [comment]
cc: @vhenry07

**Comment by RLHecht** [comment]
Sounds good. @lunascoop Do you want to add this to the page and we'll keep in draft until we get the go-ahead? We should make a note in the revision log to not publish until approved.

**Comment by RLHecht** [comment]
Here is an example of another Find Form page with an online tool being used. We can use this same language for NOD: https://www.va.gov/find-forms/about-form-20-0996/

We need to add "When to use this form" as well as the Online tool section with an action link.

**Comment by laurwill** [comment]
Hi @megzehn , tagging you for a copyedit here! I added the online tool option to this page along with a "When to use this form" sentence. http://preview-prod.vfs.va.gov/preview?nodeId=6072

We're planning to publish this page tomorrow June 8 once we've confirmed that the online form is live for 100% of users.

**Comment by RLHecht** [comment]
@megzehn I updated this url like I did on the other pages to make sure it wasn't going to directly to the /introduction page. This can be published!

**Comment by Mottie** [comment]
NOD is set to 100% now!

**Comment by megzehn** [comment]
Thank you @RLHecht for fixing all the links and letting us know!

**Comment by megzehn** [comment]
Published!

**Comment by RLHecht** [comment]
The form page is now live with the online tool linked. @Mottie since our team can't do the keyword task above, can this ticket be closed?

**Comment by Mottie** [comment]
yeah, go ahead and close this ticket. Thanks!
