### ISSUE TITLE
FE unit test for LoginActions

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37581]
## Issue Description
Create a robust unit test for LoginActions

---
## Tasks
- [ ] Verify LoginButton(s) render, and props declared are expected
- [ ] Verify CreateAccountLink(s) render, and props declared are expected

## Acceptance Criteria
- [ ] Unit test created for LoginActions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
@nsoutouras this unit test was already completed.  Closing.
