### ISSUE TITLE
HLR & NOD cleanup

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37587]
## Description

The Higher-Level Review & Notice of Disagreement forms need a bit of code cleanup - remove unused functions and tests.

## Tasks

- [ ] Clean up code in HLR
- [ ] Clean up code in NOD

## Definition of done

- [ ] All tasks complete
- [ ] All test passing
