### ISSUE TITLE
FE unit test for LoginInfo

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37585]
## Issue Description
Create a robust unit test for LoginInfo

---
## Tasks
- [x] Validate copy is visible
- [x] Validate FedWarning is rendered
- [x] Validate link clicks to to expected location

## Acceptance Criteria
- [x] Unit test created for LoginInfo
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
