### ISSUE TITLE
(Q2) File Upload initial prototype

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#37590]
## Problem Statement 
This phase of the project is the technical design and proof of concept implementation of a file uploading microservice that can be used in the future by VFS developers. Developing a new standard to try to consolidate a system that has too many standards is a classic trap, so a key part of this epic will be figuring out a long-term strategy for converting vets-api to use this service. 

For more details see: https://vfs.atlassian.net/wiki/spaces/IET/pages/2108620842/Draft+RFC+File+Upload+Selection

**Initiative:**
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/37567

## Hypothesis or Bet
Developing a minimal viable proof of concept will guide IET towards concrete functional and technical specifications which will enable our team to develop a useful iteration of file upload. 

## We will know we're done when... ("Definition of Done")
- [x] API for this service has been defined. 
- [x] Subsets of Endpoints have been implemented that provide file upload functionality in a development environment (someone outside of the team could use them).  
- [ ] A functional design document is created describing the minimum set of features that must be implemented. 
- [ ] A technical design document is created with the findings of these prototypes that will be used to guide future development.
- [ ] Relevant RFCs and ADRs are made for technical decisions 

**Documentation**
File Upload Confluence space: https://vfs.atlassian.net/wiki/spaces/IET/pages/2053341190/File+Upload

## Known Blockers/Dependencies 
_None currently_

## Projected Launch Date
Features will be deployed to development as they are completed, this work is expected to wrap up on the week of April 24th.

Week of May 10th

## Launch Checklist
_This iteration is an internal proof of concept and will not be launched to wider teams_
_The purpose of this prototype is to answer the questions we will need to answer to actually develop the service._

**Comment by considerable** [comment]
I made this repo as part of the EKS onboarding requirements:
https://github.com/department-of-veterans-affairs/vets-api-file-upload/

**Comment by ewilson-adhoc** [comment]
This prototype has been finished. 
The service can be found on development at http://file-upload-dev.vfs.va.gov/
Documents are available at http://file-upload-dev.vfs.va.gov/api/v1/redoc

The virus scan service can be found on development at  http://virus-scan-dev.vfs.va.gov
Documents available at http://virus-scan-dev.vfs.va.gov/redoc

https://vfs.atlassian.net/wiki/spaces/IET/pages/2053341190/File+Upload
