### ISSUE TITLE
[Research] Run Staff Research with St. Louis

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37593]
# Description
Meet with the MSAs at St. Louis and run [this research protocol](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback).

# Tasks
- [x] Meet with MSAs
- [x] Record session

# Acceptance Criteria
- [x] Download recordings, so synthesis can begin.
- [x] Place notes in the correct spot

**Comment by kristenmcconnell** [comment]
[Notes are now on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/session-notes/Mar9-zoomcall.md).
