### ISSUE TITLE
[Tech Discovery] Cerner Health System Vs Facility Name Feasibility Assessment 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37594]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)

`Email Ask`: Yesterday, someone brought to my attention: On our health tools pages on va.gov (Rx Refill, Secure message, etc.) when we are pointing Veterans to the Cerner portal, we have been using the formal name of the parent facility, versus the name of the health system (VA Spokane health care). When sites move to the new cerner EHR, the entire health care system goes live with it – inclusive of all of the CBOCs and related clinics.
 
With Walla Walla’s ship date around the corner (3/26) I’m wondering if we should be using the health system name instead of the facility name, and if so, how big of a lift is that for the sitewide team? I don’t think a change is needed on the facilities pages, based on my discussions with Sam before he left.
 
So, in the image below, instead of “For Mann-Grandstaff” we would use For “VA Spokane health care”

<img width="545" alt="Screen Shot 2022-02-24 at 10 42 01 AM" src="https://user-images.githubusercontent.com/70410912/155578265-e8719f5d-b556-4d36-9d68-04b23b340818.png">

### Considerations
- Lets determine feasibility of this action, along with risks associated with listing as `health system` vice `facility name`  
- Assume that if we transition to `health system` we'll likely need to udpated past facilities that have launched to Cerner as well.
- Please annotate risks and issues with this approach and provide tech assessment of steps to move forward

### Tasks
- [x] Determine feasibility of transitioning to health system vice facility name that we're currently doing.  
- [x] Provide tech assessment in comment section and list out steps forward 
- [x] Determine code owners of `health tools pages on va.gov` as we'll need to coordinate with them forward
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Tech assessment is provided
- [x] Team reviews assessment and discuss best approach forward 
- [ ] PM/PO update stakeholder on findings

**Comment by brianalloyd** [comment]
@longmd could you provide your tech assessment that you discussed in SU.  Would like to document here and close out ticket in support.  Thanks.

**Comment by longmd** [comment]
**_Background:_** The widget parses an array of strings with the facility names to print prior to the link. This array of strings comes from the Content team based on the information they need to provide. 

**_Potential solutions:_** 
1. Content revises the array to provide the actual names of the locations they want to display. 
2. We create a JSON file that serves as a look-up for the facility names. Maybe each individual center is in an array with the parent key being the system they want to display. If we find the facility in the array we return the parent system back as a string to the widget. Obviously that file could be VERY large and maybe this is a bit taxing, but its an option.

**Comment by brianalloyd** [comment]
Closing out ticket based on completed tech discovery.
