### ISSUE TITLE
[Cerner] Test Walla Walla for full Cerner launch

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37595]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)
Timeline for launch: Testing the month of Feb (possibly including last week of Jan)
Go live Timeline: March 25th cutover for March 26th Go-Live

- Facility ID's: Walla Walla health care facilities
Richland VA Clinic - vha_687GA
Lewiston VA Clinic - vha_687GB
La Grande VA Clinic - vha_687GC
Jonathan M. Wainwright Memorial VA Medical Center - vha_687
Yakima VA Clinic - vha_687HA
Wallowa County VA Clinic - vha_687QC
Morrow County VA Clinic - vha_687QB

### Testing Accounts:
<p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(254, 254, 254); color: rgb(254, 254, 254); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Please find the test credentials below.  As mentioned, we’ll have to do some coordination for Login.gov testing but I was able to set up our Walla Walla account to use backup codes for MFA instead of my number.  Only 10 are given at a time and they’re one-time use codes so I’ve provided 5 below for your use.  Please let me know if you need additional codes for the Walla Walla test account.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(254, 254, 254); color: rgb(254, 254, 254); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"> </span><o:p></o:p></p>

Site | ID.me/MHV/Login.gov Email | Password (ID.me/MHV) | MHV User Name | Login.gov password | Login.gov Back up codes
-- | -- | -- | -- | -- | --
Columbus | ssoissoetesting+spokane1@gmail.com | Cerner123! | CSSspokane1 | n/a | n/a
Columbus | ssoissoetesting+columbus2@gmail.com | Cerner123! | n/a | Cerner12345! | n/a
Walla Walla | ssoissoetesting+wallawalla1@gmail.com | Cerner123! | wallawalla1 | Cerner12345! | 3016HH3DZEA5FMA2MJQF745F8C1GF39XR3SZZZKNTZ2RYY4ZX3HWSMA4Z5RQ

Please find the test credentials below.  As mentioned, we’ll have to do some coordination for Login.gov testing but I was able to set up our Walla Walla account to use backup codes for MFA instead of my number.  Only 10 are given at a time and they’re one-time use codes so I’ve provided 5 below for your use.  Please let me know if you need additional codes for the Walla Walla test account.
 
Site
ID.me/MHV/Login.gov Email
Password (ID.me/MHV)
MHV User Name
Login.gov password
Login.gov Back up codes
Columbus
[ssoissoetesting+spokane1@gmail.com](mailto:ssoissoetesting+spokane1@gmail.com)
Cerner123!
CSSspokane1
n/a
n/a
Columbus
[ssoissoetesting+columbus2@gmail.com](mailto:ssoissoetesting+columbus2@gmail.com)
Cerner123!
n/a
Cerner12345!
n/a
Walla Walla
[ssoissoetesting+wallawalla1@gmail.com](mailto:ssoissoetesting+wallawalla1@gmail.com)
Cerner123!
wallawalla1
Cerner12345!
3016HH3DZEA5
FMA2MJQF745F
8C1GF39XR3SZ
ZZKNTZ2RYY4Z
X3HWSMA4Z5RQ

### Tasks
- [x] Follow the Cerner Runbook and TEST Walla Facility for Cerner launch readiness
- [x] Test locally and setup a staging test environment so Facility admins can test.
- [x] Review and close ticket once work is completed
- [x] **DO NOT LAUNCH UNTIL MARCH 25**

### Acceptable Criteria 
- [x] Walla Walla is fully tested and ready for launch on March 25 
- [x] Local test are completed and show signs of success
- [x] a11y considerations are implemented in support

**Comment by brianalloyd** [comment]
Tests completed, ready to launch on specified DTG.
