### ISSUE TITLE
Modify HLR Contestable issues to consume new LH endpoint

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#37607]
## Issue Description
Currently, HLRs are limited to "compensation" benefits.  We are going to expand HLRs to support all benefit types(compensation, pensionSurvivorsBenefits, fiduciary, lifeInsurance, veteransHealthAdministration, veteranReadinessAndEmployment, loanGuaranty, education, nationalCemeteryAdministration)

The current vets-api decisionReviewV1::Service.get_higher_level_review_contestable_issues consumes lighthouse's appeals/v2/decision_reviews/higher_level_reviews/contestable_issues endpoint.  

The current lighthouse endpoint only supports "compensation" benefit type. Lighthouses contestable_issues endpoint supports multiple benefit types, so change DecisionReviewV1::Service.get_higher_level_review_contestable_issues to consume appeals/v2/decision_reviews/contestable_issues/higher_level_reviews?benefit_type=compensation

---
## Tasks
- [ ] _Modify the service to call the lighthouse contestable issues _

## Acceptance Criteria
- [ ] _Service will provide contestable issues for all benefit types_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
