### ISSUE TITLE
Launch Pain Point Artifact

### ISSUE THREAD

**Issue by Khyatinp18** [department-of-veterans-affairs/va.gov-team#37616]
## Issue Description
As a SD team member I want to Launch the Pain Point artifact so that we can start tracking how and when paint points are being solved by Platform teams

---
## Tasks
- [ ] Present for Go No Go during office hours
- [ ] Make necessary changes based on the feedback from Go No Go
- [ ] Launch the artifact

## Acceptance Criteria
- [ ] Validate Pain Point Artifact is launched
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Khyatinp18** [comment]
3/11/2022
We had a leadership alignment meeting with the team on 3/9/2022 regarding the scope change and the decision was made not to continue with the above initiative and instead apply learning from it to develop a roadmap for Q2 2022.
