### ISSUE TITLE
Replace alert with primary action link on hardened VAMC Billing and insurance page (3 of 3)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37612]
## Issue description
We need to doublecheck the newly hardened Billing and insurance page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

Billing and insurance
- [Billing and insurance content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595854648224/23c83ef3ccbbd06cd4d5afd59db5ddfa5688a8e1)
- Example [Billing and insurance page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/billing-and-insurance/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/billing-and-insurance
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/billing-and-insurance

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058238-3389f707-79af-4a62-a131-10642979d00d.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057908-b4bf4e85-4ea8-4926-aa36-9f3fe381493f.png)

</details>

## Template
The newly hardened pages use this template: 
```
<!--
  layout: vamc_system_billing_insurance.drupal.liquid
  path: preview
  entityId: N/A
-->
```
The following systems have data in this new hardened template and can be used for validation:
- VA Western Colorado health care
- VA Cheyenne health care
- VA Eastern Oklahoma health care  
- VA Sheridan health care

## Related issues
This issue is one of 3 to complete this design implementation

- Hours and phone styles in #37601
- Heading levels will be done in #37598
- Replace existing VA Blue Button sign in alert on with primary action link in this issue

## Tasks

Implement the hours and phone number styles for Billing and insurance pages as shown in the [UXPin design](https://preview.uxpin.com/16d44a03330afdb07cf7baa572b1bb6c95cb9077#/pages/147796626/documentation/no-panels?mode=i) , including the following
- [ ] Replace existing VA Blue Button sign in alert on with primary action link according to Nick's design ([UX Pin](https://preview.uxpin.com/16d44a03330afdb07cf7baa572b1bb6c95cb9077#/pages/147888051/documentation/no-panels?mode=i) when flag from CMS (field name `vamc_ehr_system`)** indicates Cerner
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them)
- [ ] Test this functionality with newly hardened pages in Tugboat
- [ ] Test this functionality with ehr field scenarios in Tugboat
- [ ] Work with Nick to validate style changes
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production

## Acceptance Criteria
Billing and insurance page is designed consistent with UX Pin spec, including
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] When flag from CMS (field name `vamc_ehr_system`)** indicates Cerner, primary action link is displayed according to Nick's design
- [ ] Link to Cerner portal renders only when indicated based on the CMS Cerner flag (field name `vamc_ehr_system`)
- [ ]  When field name=`vamc_ehr_system`, Veterans can click on a link on that health care system's Medical records page to be directed to the health record portion of the Cerner portal.
- [ ] When field name does not = `vamc_ehr_system`, the existing functionality is maintained.
- [ ] Deployment is coordinated with CMS team
- [ ] Steps taken to test these changes and their results are documented in this issue
- [ ] Nick O has signed off on this work in comment on this issue

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1088
