### ISSUE TITLE
Implement heading styles for hardened VAMC Register for care pages (1 of 3) 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37627]
## Issue description
We need to doublecheck the newly hardened Medical records page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

## Register for care resources
- [Register for care content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b)
- Example [Register for care page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/register-for-care/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care 

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058075-2c8c27b2-76c1-42d7-9ee3-0f1dfce87e53.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057591-5838d977-3723-4aed-b16f-335ecb166e35.png)

</details>

## Related issues
This issue is one of 3 to complete this design implementation
- Heading levels will be done in this issue
- Hours and phone styles in #37630
- Replace alert style in #37631

## Template
Newly hardened pages use this template **which has not been rolled to Production yet and needs to be viewed in CMS.** 
```
 <!--
  layout: vamc_system_register_for_care.drupal.liquid
  path: preview
  entityId: N/A
-->
```

<detail>
<summary> note, this is different than the template currently on Prod </summary>
```
<!--
  layout: health_care_region_detail_page.drupal.liquid
  path: western-colorado-health-care/register-for-care
  entityId: 6245
-->
```
</detail>

The following systems have data in this new hardened template and can be used for validation: 

- VA Western Colorado health care  (i.e. http://prod.cms.va.gov/western-colorado-health-care/register-for-care-0)
- VA Cheyenne health care 
- VA Eastern Oklahoma health care  
- VA Sheridan health care

## Tasks
Implement [UXPin design](https://preview.uxpin.com/640e3b5894ed7cdf5c5d3342b119badd012ec5a5#/pages/147812897/documentation/no-panels?mode=i) for Register for care pages, including the following
- [ ] Add new Q2 heading for "Patient registration (admissions)"
- [ ] Add new Q2 heading for "Not yet enrolled in VA health care?"
- [ ] Ensure new Q2 headings are available by jumplink
- [ ] The name of each facility is an H3, linked to that VAMC page. (For example, clicking on Rocky Mountain Regional VA Medical Center from [Eastern Colorado health care register for care page]https://www.va.gov/eastern-colorado-health-care/register-for-care/) leads to [facility page](https://www.va.gov/eastern-colorado-health-care/locations/rocky-mountain-regional-va-medical-center/) _this will not be possible in Preview mode given the single page preview limitation_
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them) 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production
- [ ] Work with Nick O to validate these changes

## Acceptance Criteria
Register for care page is designed consistent with UX Pin spec, including
- [ ] When viewing health care Register for care page, Veteran sees "Patient registration (admissions)" heading
- [ ] When viewing health care Register for care page, Veteran sees "Not yet enrolled in VA health care?" heading
- [ ] Veteran can view "Patient registration (admissions)" content by clicking on jumplink 
- [ ] Veteran can view "Not yet enrolled in VA health care?" content by clicking on jumplink 
- [ ] The name of each facility is an H3
- [ ] A Veteran can click on the name of the facility from the medical records page and view the facility page
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Deployment is coordinated with CMS team
- [ ] Steps taken to test these changes and their results are documented in this issue
- [ ] Nick has signed off on these changes with a comment in this issue
