### ISSUE TITLE
Implement `findDependentsByPtcpntId` API Endpoint from BGS to "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3762]
## Story
As a Veteran, I need to be able to view my dependents so I can better understand who I have available on award (or not) to apply for benefits.

## Goal
- Build an API that communicates with BGS and retrieves the `findDependentsByPtcpntId` endpoint for a Veteran.
- Migrate this functionality from eBenefits to VA.gov so users will no longer have to login to eBenefits to view their dependents.

## Dependencies
- Data recordings: _betamocks does not work directly with BGS services, but we can use the sample response data provided by BGS to generate json files that can then be used in the betamocks repo_
- BGS service is opened to us: _ticket for access has been submitted_

## Tasks
- [x] Consume a web service from BGS that provides the dependents (both on and not on award) as part of the response message
- [x] Build and configure a dependents service within `vets-api` that requests/receives the `findDependentsByPtcpntId` endpoint from BGS
- [x] Implement the controller, route, and serializer for the dependents service

## Acceptance Criteria
- [ ] Successfully receive data back from a call to BGS using the `findDependentsByPtcpntId` API

## Note
~Following up with ESCP for getting into BGS~

## Next Steps
- Consider building out a scaffold until full access has been granted.
- Consider tickets for: BGS Error Handling (Connect with Lighthouse), Update `findDependentsByPtcpntId` API Endpoint Swagger Docs, Unit Tests for `findDependentsByPtcpntId` API Endpoint
