### ISSUE TITLE
Implement action link for hardened VAMC Register for care pages (3 of 3) 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37631]
## Issue description
We need to doublecheck the newly hardened Medical records page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

## Related issues
This issue is one of 3 to complete this design implementation
- Heading levels will be done in #37627
- Hours and phone styles in #37630
- Replace alert style in this issue

## Template
Newly hardened pages use this template: 
```
 <!--
  layout: vamc_system_register_for_care.drupal.liquid
  path: preview
  entityId: N/A
-->
```

The following systems have data in this new hardened template and can be used for validation: 

- VA Western Colorado health care
- VA Cheyenne health care 
- VA Eastern Oklahoma health care  
- VA Sheridan health care

## Register for care resources
- [Register for care content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b)
- Example [Register for care page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/register-for-care/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care 

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058075-2c8c27b2-76c1-42d7-9ee3-0f1dfce87e53.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057591-5838d977-3723-4aed-b16f-335ecb166e35.png)

</details>

## Tasks
Implement [UXPin design](https://preview.uxpin.com/640e3b5894ed7cdf5c5d3342b119badd012ec5a5#/pages/147812897/documentation/no-panels?mode=i) for Register for care pages, including the following
- [ ] Style "Apply online, by mail or phone" as action link 
- [ ] Ensure the action link takes users to [an intermediary page. ](https://www.va.gov/health-care/how-to-apply/)
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them) 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production
- [ ] Work with Nick O to validate these changes

## Acceptance Criteria
Register for care page is designed consistent with UX Pin spec, including
- [ ] "Apply online, by mail or phone" is styled as action link.  
- [ ] Veterans can click on the  "Apply online, by mail or phone"  action link and be taken to [an intermediary page](https://www.va.gov/health-care/how-to-apply/) 
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Deployment is coordinated with CMS team
- [ ] Steps taken to test these changes and their results are documented in this issue
- [ ] Nick has signed off on these changes with a comment in this issue

**Comment by ethanteague** [comment]
@kevwalsh @swirtSJW @msbtterswrth @maxx1128  added `usa-button` class to action link `Apply online, by phone, or by mail` on centralized content node for Register for care pages: https://prod.cms.va.gov/node/33339/edit
Should be available tomorrow afternoon for qa.
![image](https://user-images.githubusercontent.com/2404547/163466245-0d0416d5-04f5-4385-8e06-1518c348d712.png)
![image](https://user-images.githubusercontent.com/2404547/163466268-e481ea86-9fd5-4c08-9bcc-92c9ab028655.png)
