### ISSUE TITLE
FE unit test for SessionTimeoutModal

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37637]
## Issue Description
Create a unit test suite for SessionTimeoutModal
---
## Tasks
- [ ] verify modal opens after session expiration

## Acceptance Criteria
- [ ] Unit test created for SessionTimeoutModal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
