### ISSUE TITLE
Implement hours and phone styles for hardened VAMC Register for care pages (2 of 3) 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#37630]
## Issue description
We need to doublecheck the newly hardened Register for care page to ensure consistency of design now that the new content model has been implemented. 

## Problems to be solved

- Because this top task page exists across the VAMC system, the page don't have facility context so we will need to include hyperlinked name
- Locations should be restyled like service locations, including the presentation of hours by day
- Heading level hierarchy should be maintained 
- Padding between areas of content and around optional "release valve" fields (these are limited rich text - could have bullets but will not have (or need) headers)

## Register for care resources
- [Register for care content model mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1594821112000/9932af464534c2676a2656992de3cf809cfad97b)
- Example [Register for care page from Pittsburgh](https://www.va.gov/pittsburgh-health-care/register-for-care/)
https://pr7705-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care
https://web-6dug5xhx8nbfoodoeepelyhivmuvyree.ci.cms.va.gov/cheyenne-health-care/register-for-care 

## Screenshots 

<details>
<summary> Front end display in hardened version </summary>

![image](https://user-images.githubusercontent.com/55411834/152058075-2c8c27b2-76c1-42d7-9ee3-0f1dfce87e53.png)

</details>

<details>
<summary> Content mural showing areas of focus </summary>

![image](https://user-images.githubusercontent.com/55411834/152057591-5838d977-3723-4aed-b16f-335ecb166e35.png)

</details>

## Related issues
This issue is one of 3 to complete this design implementation
- Heading levels will be done in #37627
- Hours and phone styles in this issue
- Replace alert style in #37631 

## Template
Newly hardened pages use this template **which has not been rolled to Production yet and needs to be viewed in CMS.** 
```
 <!--
  layout: vamc_system_register_for_care.drupal.liquid
  path: preview
  entityId: N/A
-->
```
note, this is different than the template currently on Prod 

```
<!--
  layout: health_care_region_detail_page.drupal.liquid
  path: western-colorado-health-care/register-for-care
  entityId: 6245
-->
```

The following systems have data in this new hardened template and can be used for validation: 

- VA Western Colorado health care  (i.e. http://prod.cms.va.gov/western-colorado-health-care/register-for-care-0)
- VA Cheyenne health care 
- VA Eastern Oklahoma health care  
- VA Sheridan health care

## Tasks
Implement [UXPin design](https://preview.uxpin.com/640e3b5894ed7cdf5c5d3342b119badd012ec5a5#/pages/147812897/documentation/no-panels?mode=i) for Register for care pages, including the following
- [ ] ~Phone labels and numbers follow an update design pattern.~(_moved into#38826_)
- [ ] Hours follows an updated design pattern
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them) 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production
- [ ] Work with Nick O to validate these changes

## Acceptance Criteria
Register for care page is designed consistent with UX Pin spec, including
- [ ] ~Phone labels are consistent with CMS data and appear above the phone number~(_moved into#38826_)
- [ ] The Hours heading is displayed above the hours listed by day, according to the data in CMS
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Deployment is coordinated with CMS team
- [ ] Steps taken to test these changes and their results are documented in this issue
- [ ] Nick has signed off on these changes with a comment in this issue

**Comment by mmiddaugh** [comment]
@GcioNapoleon 
from CMS http://prod.cms.va.gov/western-colorado-health-care/register-for-care-0

![image](https://user-images.githubusercontent.com/55411834/159093674-2d47781d-760e-4b70-9561-68a26e16dc11.png)
![image](https://user-images.githubusercontent.com/55411834/159093701-6d368c33-52da-49c9-a46d-830e2f4aa397.png)

Comapred to Production (which uses the previous (non-hardened) version
https://files.slack.com/files-pri/T03FECE8V-F037KE6RCAJ/image.png

**Comment by mmiddaugh** [comment]
@GcioNapoleon,  this issue is not blocked as this data is within a WYSIWYG. 
Following a conversation this morning with CMS, it was determined that hours should use the data from the new `field_office_hours` data structure. If there is no data present in that table, no hours (or hours heading) should be displayed.

**Comment by mmiddaugh** [comment]
@GcioNapoleon please also make sure that the day of the week is displayed with a colon, as shown in the UX pin.  In some places in the front end, it renders with a period, rather than a colon.

![image](https://user-images.githubusercontent.com/55411834/159291095-50b13df9-2ed7-401b-a7c5-a3cc2d01870e.png)
![image](https://user-images.githubusercontent.com/55411834/159291248-c43f5557-169c-46af-9a66-8db72a20b5e9.png)
