### ISSUE TITLE
FE unit test for AutoSSO

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37643]
## Issue Description
Create unit test suite for AutoSSO

---
## Tasks
- [ ] Validate that it calls checkAutoSession under correct assumptions
- [ ] Validate that checkAutoSession is not called when those assumptions are false
- [ ] Validate that checkKeepAlive is called after checkAutoSession resolves

## Acceptance Criteria
- [ ] Unit test created for AutoSSO
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
