### ISSUE TITLE
FE unit test for RenderErrorContainer

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37641]
## Issue Description
Create unit test suite for RenderErrorContainer

---
## Tasks
- [x] Validate error codes map properly to the rendered content
- [x] Validate link clicks lead to correct locations

## Acceptance Criteria
- [x] Unit test created for RenderErrorContainer
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
