### ISSUE TITLE
<Authenticated 22-1990e TOE Form Updates> from <My Education Benefits>

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#37658]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
The My Education Benefits team will be updating the 22-1990e form for authenticated users applying for Transfer of Entitlement (TOE) benefits. We're requesting a content review of our wireframes while we work through the collaboration cycle. Much of the content & layout of our designs re-use elements from the 22-1990 form that we have already brought through the entirety of the collaboration cycle, so we're hoping this will be a low effort review. Please reach out if you have any questions & Thank You!!
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/TOE%2022-1990e%20Updates/TOE%20Product%20Outline.md
- Link to or attach user flows: https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=06a224645241871fa5475824bd7e4ed97d273fcdf1fcb16d2890ca7d8bc61039&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- Link to prototype or mockups: https://accenturefederal.invisionapp.com/freehand/Design-Intent---User-Flow-TOE-U3BzprxZZ?dsid_h=06a224645241871fa5475824bd7e4ed97d273fcdf1fcb16d2890ca7d8bc61039&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37551

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD
- Estimated staging review date: TBD
- Content and IA work needed by: Friday, March 4th, 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

Team name: My Education Benefits
Leelah Holmes
Gaige Dickerson
Alex Ferzola
Audra Ayotte
OCTO-DE product lead: Matt Self
Product manager: Shamik Desai
OCTO-DE Design Lead: Ryan Thurlwell

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hi @SgardnerPMP and @alexander-ferzola, I'm going to include an IA review in this work as well to ensure we've captured all entry points, flows and scenarios.  Thank you!

**Comment by alexander-ferzola** [comment]
> Hi @SgardnerPMP and @alexander-ferzola, I'm going to include an IA review in this work as well to ensure we've captured all entry points, flows and scenarios. Thank you!

Morning, Mikki - That would be great! The updates live within the 22-1990e form so we didn't anticipate any major IA re-work, but please let us know if you have any recommendations! Thanks again!

**Comment by alexander-ferzola** [comment]
@bethpotts @mnorthuis 
Wanted to bring this thread to the top of your inbox as a reminder. Please let us know if you need any additional resources before diving into our TOE screen updates.

**Comment by mnorthuis** [comment]
Hi @alexander-ferzola, the only feedback I have, is to consider the entry point to the 1990e from the [Transfer your Post-9/11 GI Bill benefits page](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) - that page links directly to the 1990e and doesn't use the wizard. 

@bethpottsVADEPO I also think we should consider adding an entry point to the 1990e from the[ Survivor and dependent benefits page](https://www.va.gov/education/survivor-dependent-benefits/). It's very focused on DEA and Fry, but applying for transferred benefits is another option that should likely be called out.

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola Here are my recommendations for the intro page screens (the sitewide content editor, @RLHecht, will submit plain language and VA.gov voice feedback on the rest of the screens in this ticket as well today):

## Feedback on the Application Instructions screens

### Unauthenticated

It's a little info-alert heavy having 2 on one page. I think you could just have a "Note" at the top rather than an info alert, like this:

**Note:** This application is only for the transfer of entitlement of Post-9/11 GI Bill benefits (Chapter 33). You must be a spouse or child of a service member to use transferred entitlement.

Under "Follow these steps to get started"
**For No. 1**, this application is a little different in that it's not the traditional "eligibility" info that we usually put here. Eligibility has already been established when the service member applies for TOE. I believe at this use-transferred-entitlement stage it's more about the timing of when the family member can use the benefit. So I think the below "header" for No. 1 would be more clear as "Check when you're eligible to use transferred entitlement." 

I've also edited the text throughout the additional info component. I wanted to mention that we stay away from terms like "transferor" because it's jargon that can make it harder for the user to understand the information we're providing--and it doesn't align with our plain language approach. So I've substituted "service member" there. 

It's visually awkward to have 2 "Notes" appearing stacked when the additional info is unfurled. I also don't know that the info in the first note about the Department of Defense deciding the TOE is relevant/appropriate to include in this intro page at all. It's really addressing the service member not the family member. I'd strongly encourage you to remove this. 

For the second note, I think you could keep it where it is if you remove the first note. But would you please ask stakeholders to review this rewrite? I don't think the way it was written was totally clear. It said you can only use one education benefit, but I think the intended messaging would be "only one education benefit at a time" (I rewrote both sentences to clarify):

**Note:** You may be eligible for more than one education benefit program, but you can get payments from only one education benefit at a time. You can't get more than a total of 48 months of education benefits from VA education programs.

**For No. 2**, you can remove "Knowledge of" at the start of the first bullet. And can we get more specific about what this means?: "If you aren't legally an adult..." Here's one approach: "If you aren't legally and adult (at least 18 years old), your parent or guardian must sign your application." 

Here's what I'd recommend for the content under "Follow these steps to get started":

**Follow these steps to get started**

**(1) Check when you're eligible to use transferred entitlement**

Make sure you're eligible to apply at this time. 

[Additional info link] When can I use transferred entitlement?

**If you're a spouse and you've received transferred entitlement:**

- You may use the benefit right away.
- You may use the benefit while the service member's on active duty or after they've separated from service.
- You may use the benefit for up to 15 years after the service member's separation from active duty.
- You don't qualify for the monthly housing allowance while the service member's on active duty.

**If you're a child and you've received transferred entitlement:**

- You may start to use the benefit only after the service member has finished at least 10 years of service.
- You may use the benefit while the service member's on active duty or after they've separated from service.
- You can't use the benefit until the service member has gotten a high school diploma (or a certificate that's equivalent) or has reached 18 years of age.
- You have to use the benefit before you turn 26 years old (but you don't have to use the benefit within 15 years after the service member separates from active duty)
- You qualify for the monthly housing allowance even when the service member's on active duty.

**Note:** You may be eligible for more than one education benefit program, but you can get payments from only one education benefit at a time. You can't get more than a total of 48 months of education benefits from VA education programs.

**(2) Gather your information** 

**Here's what you'll need to apply:**

- Your sponsor's military service history
- Your current address and contact information
- Your bank account direct deposit information

**Note:** If you aren't legally an adult (at least 18 years old), your parent or guardian must sign your application.

**(3) Start your application [no changes/edits to No. 3!]**

### Authenticated

The only change to make to this screen is to change "Begin" to "Start" in the H2 above the action link (we don't vary the way we say this--we always use "start"):
**Start you application for education benefits**

**Comment by RLHecht** [comment]
@alexander-ferzola Here are my plain language edits for the other screens. Please let me know if you have any questions on them or something doesn't make sense. On some of these I noted when to change something on several screens as well. Thanks!

Applicant Info (Default auto filled for info on file)
- Form label should be "Your date of birth" Change on all screens.
- There's no time zone in the green box for when the application was last saved. Fix on all screens.
- Apostrophes in the Need help? section should be curly. Change these on all the pages.

Sponsor information (If one sponsor on file)
- Change sentence to "The DoD decides whether your sponsor can transfer their GI Bill benefits to you." Change this on all screens
- Need an apostrophe in sponsor's information in second sentence in note
- To avoid sighted language, change the sentence to: "If your sponsor's information is incorrect or missing, please tell your sponsor.
- Take out the "th" in the dates. Change on all screens
- Should there be that much space between the form labels and the answers on this screen? If not, change throughout.

Sponsor information (If applicant chooses Someone not listed here)
- Change alert header to: Your sponsor isn't on file
- Apostrophes in all form labels should be curly. Change on all screens.
- Change form label to Sponsor's suffix. Change on all screens.

Sponsor information (If applicant has no sponsor on file)
- Change alert header to "We don't have any sponsor information on file"


Contact info page 1
- To avoid passive voice, change the sentence to "We have this contact information on file for you." 
Add a period to the sentences "This mobile phone number is international." Change on all screens.

Contact info page 2
- To avoid passive voice change the sentence to "We have this mailing address on file for you."
- The "Learn more about military bases" additional info component isn't opened so I can't edit that text.

Contact info page 3
- For the "How should we contact you..." radio buttons, the order of form labels should be: Mail, Email, Home phone, Mobile phone
- In the paragraph under "Choose how you want to get notifications text" to avoid passive voice, change to the following: We recommend that you opt in to text message notifications about your benefits. These notifications can prompt you to verify your enrollment so you'll receive your education payments. You can verify your monthly enrollment easily this way."
- Put periods at the end of the Yes/No radio button text.
- In the alert I'm not sure what "Two messages per month" means. Is it We'll send you 2 messages per month? I think the last sentence should be a link. It should also be sentence cased and to avoid sighted language change to the following "Review our terms and conditions and our privacy policy."
- Make the apostrophe in the alert curly.

Direct deposit input and expanded
- Change to "We make payments only through direct deposit..." (Our style is to use first person instead of VA)
- Change to: "If you don't have a bank account, we'll pay you through..."
- For accessibility link all of this text: Apply for a Direct Express Debit MasterCard at www.usdirectexpress.com"

Application review (default)
- All five bars should be blue (change on all screens)

App review (expanded view applicant under legal age 2 sponsors)
- Remove the comma between month and year

Instant confirmation
- We don't use exclamation points on the site. Change the alert header to: You've been approved for the Transfer of Entitlement for Post-9/11 GI Bill
- For plain language and to avoid passive voice, change to the following: We reviewed your application and have determined that you're entitled to education benefits under the Transfer of Entitlement for Post-9/11 GI Bill (Chapter 33). You can now download your decision letter. We'll also mail a physical copy to your mailing address.
- To avoid sighted language, change the link text to "Go to a statement of your benefits"
- You can remove the register symbol for GI Bill throughout. Our style guide says we only need it on the main GI Bill page.
- In the What happens next section? For accessibility we should make links show both a target and a purpose instead of only linking parts of a sentence so change the following bullets:
[Download a copy of your decision letter]
[Use our GI Bill Comparison Tool to help you decide which education program and school are best for you]
[Review and/or update your direct deposit information on your VA.gov profile]
[Learn more about VA benefits and programs through the Building Your Future with the GI Bill Series]
- Change to "What's a Certificate o Eligibility?" If the rest of the text is changing to decision letter should this as well?

Offramped
- Change text in alert to: Your application requires additional review. Once we've reviewed your application, we'll reach out to notify you about next steps."
- Remove the 1 at the beginning of the non-international number. And add the following as the last sentence: We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.
- Change bullet point answers for "What happens next?: to the following:
We'll review your eligibility for [Benefit Type]
You'll be notified if you're eligible for VA education benefits.
We don't require any further action by you at this time. 
- For accessibility, change the bullets under "What can I do while I wait?"
If you need to submit documentation to us, such as service records, please send this through our Ask VA feature. [Go to Ask VA]
[Review and/or update your direct deposit information on your VA.gov profile]
[Use our GI Bill Comparison Tool to help you decide which education program and school are best for you]
[Learn more about VA benefits and programs through the Building Your Future with the GI Bill Series]
[Measure your interests and skill levels and help figure out your career path with CareerScope]

Instant denial
- Change text in the alert to the following: Unfortunately, based on the information you provided and Department of Defense records, we've determined you're not eligible for the Transfer of Entitlement for Post-9/11 GI Bill (Chapter 33) benefit at this time.
You can now download your decision letter, which explains why you're not eligible. We'll also mail a physical copy to your mailing address.
- In the first bullet for "What happens next?" fix the typo in "education"
- Change second bullet to "We'll notify you if you're eligible for other VA education benefits"
- Change third bullet to "We don't require any further action by you at this time"

**Comment by alexander-ferzola** [comment]
Thanks both for the edits! We'll review feedback and reach back out if we have any questions!!

**Comment by alexander-ferzola** [comment]
Thank you all for your feedback. Before closing this ticket, we would like to recap feedback and update the group with our approach going forward. Please see the design implementation plan below that considers Va.gov recommendations along with our EDU business needs. 

**Note:** The following address recommendations for **designs only.** They do not include specific points about user research or developer implementation during staging. Those points of feedback have been documented and can be addressed in the future. 

Tagging our EDU Product Owners for their awareness on this thread @ericks24 & @TamGIBill 

[TOE Sitewide Content Team Feedback Response.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8507476/TOE.Sitewide.Content.Team.Feedback.Response.pdf)
