### ISSUE TITLE
Migrate “Medical Device Ordering Tool” from eBenefits to VA.gov

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3766]
Medical Device Ordering Tool
Issue brief:  [Link] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-2/issue-briefs/medical-devices.md)  
Product Outline: [Link] (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool)

## Story
As a Veteran, I want to order medical devices (like socks and hearing aid batteries) online in a quick, streamlined and secure environment on a continuous basis so that I can replace them as needed to ensure I am getting the care and benefits I deserve.

## Goal
To enhance, adjust, and modernize the online medical ordering process offered by Denver Logistics Center and house the medical tool under one URL, VA.gov

## Considerations
- There are other parties involved, the Denver Logistics Center, medical professionals, in addition to users, that have requirements that will need to be specified.
- DLC is slated to increase items in their Device Catalogue
- DLC may want to increase items offered on through online channel.
- Ordering could be a single page given the amount of inventory, whereas history of orders might be paginated.
- On eBenefits, a representative might be able to login and order on behalf of the Veteran, but we will not have this ability until VA.gov supports roles and relationships.

## Pilot Tasks
*[Discovery]*
- [ ] Fully understand and document in our team folder in GitHub, how medical devices are ordered today from 1) the user perspective, 2) the DLC, and 3) the medical professionals involved.
- [ ] What is the demographics of our Veterans
- [ ] What are the different metrics of the Medical tool 
- [ ] What is the current process like? [#3220] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3220) [#3221] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3221) [#3199] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3199) [3223] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3223)
- [ ] How do Veterans use this feature today? 
- [ ] What is the turnaround processing time?  (KPI?)
- [ ] What are the baseline metrics?
- [ ] What improvements can be made? [#3425] ( ) [#3421] ( ) [#3222] ( )
- [ ] Create a map or workflow that describes the process.[#3193] ( ) [3079] ( )
- [ ] Investigate what endpoints are involved and what will need to be connected to the API that DLC create.[#3613]

*[Design]*
- [ ] Create and get approval for a research plan and conversation guide to better understand what the pain points are from the users’ perspective. [#3423][#3484]
- [ ] Conduct a usability study and document feedback for synthesis and recommendations[#3425][#3424]
- [ ] Create a new service design based on feedback, the VA Design System and research outcomes [#3472]
- [ ] Share with DLC, solicit feedback[]

*[Engineering]*
- [ ] Investigate and document in GitHub any other similar workflows
- [ ] Investigate and document in GitHub any known service calls
- [ ] Based on mockups from Design, develop a front-end that matches in form and function.
- [ ] Collaborate with back-end engineers and the DLC API to connect and test functionality.
