### ISSUE TITLE
Add Veteran facing alert to notify them of missing letters

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#37678]
## Issue Description
As discovered in #36788, letters are not being sent from VBMS after December 9, 2021. As a result, Veterans are not able to download any letters after that date until the problem has been resolved. DMC has requested that we add an alert to notify Veterans who may be looking to download a letter that was sent after December 9th. This issue is for adding the designed alert to the portal's debt letter download page. An alert currently exists on that page, so this alert will replace it. 

Please reach out to Riley with any questions about this work!

---
## Tasks
- [ ] Update the 'Download debt letters' page's UI to replace the existing alert with the warning alert displayed in [this UXPin prototype
](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4?_gl=1*p5ij5u*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/148133698/simulate/no-panels?mode=i)

## Acceptance Criteria
- [ ] The UI has been updated with the new alert 
- [ ] Please ping @rileyorr and @denisecoveyduc when the alert is in prod so we can notify our stakeholders

**Comment by denisecoveyduc** [comment]
@OptionSelect Just checking, did you let @rileyorr know so we can let our stakeholder know?
