### ISSUE TITLE
QAST DOCS: Propose IA for "Perform QA testing" subtask (M3)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#37689]
# User story

As a Platform customer, I need "Perform QA testing" docs to more easily findable via search and navigation, so that I can find the info I need to build my VFS app.

As a QAST/Content team member, I need to produce a clear hierarchy for the "Perform QA testing" docs, so I know where to focus my transformation efforts.

# Tasks

- [x] Prerequisite: Will need the "Copy of QA subtasks" xls up to date with actions (consolidate, transform, remove)
- [x] Kickoff meeting
- [x] (Gretchen) Propose organization structure
- [x] Validate proposed IA with Peter, Joe for changes and suggestions
- [ ] Doling out chunks of work based on organization, reflected in:
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/37691 
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/37692

# Acceptance criteria

- We have used an artifact (proposed IA + rationale) to secure approval from SMEs and Chelen
- Writing work has been doled out (see tickets listed above)
- We have slacked Mike Chelen to give a heads up of what we're proposing and why

# Reference information

- n/a

**Comment by lianilychee** [comment]
3/3 Thurs:
- today:
  - Focusing on this in the afternoon
  - Capturing current state and noodling on future state
  - Will decide where the artifact will live and how to structure it

**Comment by gmaciolek** [comment]
3/9 Wednesday

Yesterday
- Met with Peter

Today
- Revising based on conversation with Peter
- Sending to Peter for approval
- Scheduling time to meet with Jill and Samara
