### ISSUE TITLE
OAuth Authentication Token Logging

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#37686]
## Issue Description
The Sign in Service needs to have comprehensive logging and error reporting before going live. This ticket will cover the logging required to cover the creation and management of Access and Refresh tokens. Logs should include the following fields (where applicable):

- uuid (access tokens only)
- session_id
- user_id
- csp
- csp id
- LOA/IAL level
- URI (if applicable)
- AT hash
- RT hash
- RT parent hash
- timestamp
- state (from client request parameter)
- event_type (create, revoke, etc)
- event_outcome (success or failure)

---
## Tasks
- [x] log creation of AT
- [x] log creation of RT
- [x] log AT rotation
- [x] log RT rotation
- [x] log encryption of RT fragment
- [x] log decryption of RT fragment
- [x] log encoding of AT
- [x] log decoding of AT
- [x] update AT to create uuid on instantiation
- [x] log initial authorization call
- [x] log authorization callback
- [x] log token request response
- [x] log token refresh

# Acceptance Criteria
- [ ] Logging validated

**Comment by joeniquette** [comment]
Im writing up ideas for requirements around this tasking. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/Log_requirements.md

**Comment by joeniquette** [comment]
List is in a steady state: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/log_requirements.md We can iterate on this @bramleyjl

**Comment by bramleyjl** [comment]
Here is a [working PR](https://github.com/department-of-veterans-affairs/vets-api/pull/9685) for the first logging for SiS, it's missing the following attributes from the original list, either because I was unsure of what exactly was being referred to or unable to obtain the value.
* audit_id - this is supposed to be a uuid for the token that exists when the token is *created* (not logged for the first time)? or is this tied to the logging of the token?
* URI (if applicable)
* state
* first 5 symbols of AT/RT - the first five symbols of the token after it's been hashed?
* client_id
* redirect_uri
* IP address of user
* device fingerprint
