### ISSUE TITLE
Update recommended document list VA loan option

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#37723]
## Background
We need to make some adjustments to the text for the recommended document list on the `upload-supporting-documents` page. If a veteran indicates that they have a prior VA-backed home loan, they are prompted to upload documents that indicate that the loan has been paid in full, but this should not be the case if the loan has not been paid off yet. In order to account for this condition, the text needs to be changed from `Evidence a VA loan was paid in full` -> `Evidence a VA loan was paid in full (if applicable)`

## Tasks
- [x] `Evidence a VA loan was paid in full` is changed to `Evidence a VA loan was paid in full (if applicable)`

## Acceptance Criteria
- [x] `Evidence a VA loan was paid in full` has been changed to `Evidence a VA loan was paid in full (if applicable)`
- [x] A PR has been requested for merging
