### ISSUE TITLE
FE - Auth Profile - [Personal Information] - [Update Field Data via Reference Data endpoint]

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#37725]
## Background

We have been given a ReferenceData endpoint from VA Profile, via there swagger docs, that will provide the possible values for each personal information checkbox group.

The main docs url: https://dev.vaprofile.va.gov:7005/demographics-hub

**Sample data for sexual orientation is as follows**

Request:
https://dev.vaprofile.va.gov:7005/demographics-hub/referencedata/v1/sexual-orientation

Response:

```
{
  "sexualOrientation": [
    {
      "sexualOrientationCode": "LGH",
      "sexualOrientationName": "Lesbian, gay, or homosexual"
    },
    {
      "sexualOrientationCode": "STH",
      "sexualOrientationName": "Straight or heterosexual"
    },
    {
      "sexualOrientationCode": "BIS",
      "sexualOrientationName": "Bisexual"
    },
    {
      "sexualOrientationCode": "QER",
      "sexualOrientationName": "Queer"
    },
    {
      "sexualOrientationCode": "DNK",
      "sexualOrientationName": "Don't know"
    },
    {
      "sexualOrientationCode": "PNTA",
      "sexualOrientationName": "Prefer not to answer"
    },
    {
      "sexualOrientationCode": "NLH",
      "sexualOrientationName": "A sexual orientation not listed here"
    }
  ]
}
```

This data format is what will need to be used on the FE, so that it is consistent with the BE

## Tasks
- [ ] Use new data format to populate checkbox options for sexual orientation
- [ ] Once other reference data endpoints are available, update gender identity and pronoun fieldsets
- [ ] Update tests

## Acceptance Criteria
- [ ] Data structure is updated

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
Closing this ticket, as it is no longer relevant, and values have been coded into Profile as we needed them and keeping them that way ultimately provides further flexibility if we need to change labels.
