### ISSUE TITLE
[FE] Auth Profile - Personal Info Revision -  Add remove/delete buttons, code logical delete with expired date/time

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37747]
## Background
MPI will now be the Authoritative Data Source (ADS) for this work.  If they are able to support a logical delete via sending a date/time stamp equal to the current date/time, remove/delete buttons will need to be added to each Personal Information fields, and logic added to call a method that sends this expired date/time so that the values no longer appear when the page is reloaded.

## Tasks
- [ ] Add remove/delete button to Preferred Name in read-only state -- button label text will be provided by Christina in [mock-ups](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
- [ ] Add remove/delete button to Pronouns in read-only state
- [ ] Add remove/delete button to Gender identity in read-only state
- [ ] Add remove/delete button to Sexual orientation in read-only state
- [ ] Add code required to send expired date/time stamp when calling method to post update.
- [ ] Update PM once merged and ready to review on Staging

## Acceptance Criteria
- [ ] Add remove/delete button to Preferred Name in read-only state -- button label text will be provided by Christina in [mock-ups](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
- [ ] Add remove/delete button to Pronouns in read-only state
- [ ] Add remove/delete button to Gender identity in read-only state
- [ ] Add remove/delete button to Sexual orientation in read-only state
- [ ] Add code required to send expired date/time stamp when calling method to post update.
- [ ] Update PM once merged and ready to review on Staging

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
Need to create corresponding FE and Design tickets for this

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 @tpharrison - can you confirm that this method applies to all of the optional personal information fields?

**Comment by SKasimow** [comment]
@adamwhitlock1 - is this ticket still relevant since we're using VA Profile and not MPI - and not enabling add/delete of personal info fields (if I am understanding this correctly)?

**Comment by adamwhitlock1** [comment]
We can just close this ticket as we are not going to be implementing any delete functionality within personal info
