### ISSUE TITLE
HTML Statement FE Introductory Exploration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#37753]
## Issue Description
Currently the Medical Copay product has pdf statements which are inaccessible. Therefore we need to switch to HTML Statements to meet 508 compliance requirements. 

This Epic ([#32846](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/32846)) was established to do just that and the work has been broken up across the included 6 tickets. 
Since our front end team is new to the team, this ticket is meant for discovery work related to sizing and implementing this epic. 

Adding a feature flag to disable/hide while new HTML page is being built. 

---
## Tasks
- [ ] Adding Feature Flag prior to work start to hide new changes until testing.
- [ ] Review tickets to understand scope
- [ ] Connect with Scott who has a json file related to this work. 

## Acceptance Criteria
- [ ] Frontend team has a good understanding of the work required, is able to size the 6 tickets in this epic and is ready to pull the work into the sprint. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
