### ISSUE TITLE
Explore CI Integration of E2E Code Coverage Within GHA

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#37766]
# Description
Now that the Code Coverage report has been generated locally, go through the Cypress CI documentation - https://docs.cypress.io/guides/continuous-integration/introduction - and explore implementing an E2E Code Coverage generation within Github Actions that triggers on deploys and does not modify production code for instrumentation details.

## Tasks
- [x] Enable the successful run of Cypress Code Coverage within the CI/Github Actions workflow.
- [x] Upload of a code coverage artifact.

## Acceptance Criteria
- [x] Cypress Code Coverage summary is generated within the CI/Github Actions workflow.
- [x] Successful upload of a code coverage artifact.

**Comment by rjohnson2011** [comment]
In progress of going through Cypress documentation to determine the best methodology for implementing E2E code coverage checks on Github Actions on a production level.

**Comment by rjohnson2011** [comment]
Working on editing the Github workflows file according to https://github.com/marketplace/actions/cypress-io#component-tests

Testing out new branch to see if E2E coverage is being triggered by Github Actions.

**Comment by rjohnson2011** [comment]
Adding the following to the Github Actions workflow file:
```
steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn run ci:instrument
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
```

Updating with a link to a new branch coming shortly & then testing the CI pipeline modifications.

**Comment by rjohnson2011** [comment]
Wrapping on commits on a new branch to upload and demo the CI workflow on.

**Comment by rjohnson2011** [comment]
Modified the E2E Github Workflow file to account for instrumenting and running Cypress Code Coverage. 

Branch is at: https://github.com/department-of-veterans-affairs/vets-website/compare/codecov-ci?expand=1

Currently testing the GHA.

**Comment by rjohnson2011** [comment]
Currently making modifications to the build branch and monitoring the results in Github Actions - https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1946115722

Continuing to make progress to trigger the workflow to upload the code coverage artifact.

**Comment by JoeTice** [comment]
@rjohnson2011 - Ryan, can you please outline the remaining tasks on this effort, and think about what a fitting story point estimate is for this? Seems like we're progressing, but also feels like it's taking longer than planned

**Comment by rjohnson2011** [comment]
Added the necessary code to preprocess instrumentation upon running a Cypress test. Made some alterations to the code and running in CI. Once that is confirmed working looking to store the artifact for digestion into BigQuery.

Latest status (debugging a few recent errors):
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/19ccfd75-220d-4ad0-a55f-ebd5c36ad81d)

**Comment by rjohnson2011** [comment]
@JoeTice I revised the estimate for this ticket as the CI process has required more iterations and debugging than anticipated. Right now, the remaining aspects of this ticket are adding instrumentation to the CI pipeline then storing this code-coverage artifact. 

I've been following Cypress's official documentation for CI/Github Actions - https://docs.cypress.io/guides/continuous-integration/github-actions - and installed the necessary code-coverage packages. The added lines to the Cypress preprocessor should enable instrumentation and running the code coverage report upon running the cypress test suite alone. Once this step is working correctly most of the heavy lifting will be done.

**Comment by rjohnson2011** [comment]
Located the source of the bottleneck, the code coverage suite is running into difficulties regarding not finding an `out.json` coverage file.

![Pasted Graphic 2.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/7261b993-b48e-4e7f-bd47-50d10ccc7124)

This file should be created as part of the instrumentation process. I am checking out my prior branch where this was performed locally (and the `out.json` file is in tact) and attempting to recreate the process to assure everything on the CI branch is the same.

**Comment by rjohnson2011** [comment]
Finally sorted the problem out (corrupted dependency file) after checking out a new branch and starting clean. Now the code coverage is successfully running:

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/03b2d889-7cf0-4ccf-aed5-5387c95bd748)

and the code coverage artifact is successfully being successfully uploaded:

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/f1c85100-2463-44cd-9d7d-2edac76f203b)

Ticket is being prepped for review.

**Comment by rjohnson2011** [comment]
PR created: https://github.com/department-of-veterans-affairs/vets-website/pull/20504/
