### ISSUE TITLE
526ez | Transition to Benefits Reference Data in the Lighthouse API

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#37771]
## Issue Description
The Benefits Reference Data API has transitioned from EVSS to Lighthouse. We can begin using the new API.

---
## Tasks
- [ ] Reference [this slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1646062765278359) with Nichole Harris. Update applications to move from EVSS to Lighthouse API. (There are 9 so we will need to prioritize and create tickets for subsequent work in last 2 sprints).

If you have not already requested a key, in order to get started building and testing with this API, [submit a Lighthouse onboarding request](https://developer.va.gov/onboarding) to obtain a sandbox key.

## Acceptance Criteria
- [ ] New API tested and implemented for required products
---

**Comment by cnemeth** [comment]
Currently, we have `EVSS::ReferenceData::Service` endpoints for retrieving collections of
* Counties - Creates an object containing an array of country names
* States - Creates an object containing an array of state names
* Intake sites - Creates an object containing an array of intake site names

which have corresponding _Lighthouse_ endpoints.  

## References

* `vets-api/lib/evss/reference_data/service.rb`
* [Benefits Reference Data API](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current)

**Comment by cnemeth** [comment]
[development branch](https://github.com/department-of-veterans-affairs/vets-api/tree/API-37771/transition_the_benefits_reference_data_api_from_evss_to_lighthouse)

**Comment by NCHLiberty** [comment]
additionally, need to begin refreshing disabilities data used in 526 drop down choices as per this thread https://dsva.slack.com/archives/C5AGLBNRK/p1651168621582479

**Comment by saderagsdale** [comment]
@saderagsdale Ask when EVSS is going to terminate this service.

**Comment by saderagsdale** [comment]
@Mottie @michelpmcdonald this will be multiple tickets. @saderagsdale to make an epic.

**Comment by NCHLiberty** [comment]
> @saderagsdale Ask when EVSS is going to terminate this service.

@saderagsdale Goal is to transition away from all of the evss services this year. You can help set the target date for this one. What works for you?

**Comment by kylesoskin** [comment]
This should not be too difficult from what I can tell. 

- [ ] Need @Mottie to identify which data sets from the BRD we use/need in 526 in the front end (or I COULD do this with some research, but he may know if the top of his head or already have a list)
- [ ] I can write back-end to get them and provide end-points to front-end to consume

**Comment by kylesoskin** [comment]
Gunna just make a generic pass-through end-point

**Comment by saderagsdale** [comment]
@kylesoskin Moving this to the sprint backlog while you're on leave.

**Comment by kylesoskin** [comment]
Awaiting changes from these two PRs to get approved.
- https://github.com/department-of-veterans-affairs/vets-api/pull/10728
- https://github.com/department-of-veterans-affairs/devops/pull/12050

Once merged, backend should be able to get anything from the benefits reference data. @Mottie or other front-end-er will just need to make front-end changes to consume new vets-api back-end endpoint, but backend work should be done for now. 

This probably should have been broken into 2 tickets so that I could close a backend portion ticket.

@saderagsdale

**Comment by kylesoskin** [comment]
this is confirmed working in prod
![image.png](https://images.zenhubusercontent.com/62067253500f33af56810776/e1c3a787-e3f1-43b3-bf54-e5ce439ef2da)

However there is an issue with the apikey being used in dev/standbox/staging.... but that is not an *US* issue. I am going to get it resolved regardless.

**Comment by saderagsdale** [comment]
Booyah!

**Comment by saderagsdale** [comment]
@saderagsdale FE work isn't blocked, move links to the user story.

**Comment by kylesoskin** [comment]
TODO (maintenance task/improvements):

- [ ] request and get dedicated api_key instead of using existing team's key
- [ ] put in MRs to apply new api_key
- [ ] Support multiple api versions
- [ ] Maybe change from benefits_reference_data -> benefits-reference-data ?

**Comment by kylesoskin** [comment]
Code example error in swagger docs, does not happen with a local/newer version of swaggerui. So hoping this is a thing that will eventually just fix itself. Going to ignore for now, unless I can recreate locally.

![Screen Shot 2022-10-18 at 8.21.13 AM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/3c905b5f-92db-4706-bb98-0f9b511e7cf1)
