### ISSUE TITLE
Handle `va-on-this-page` empty hash

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37776]
## Description

When using the `va-on-this-page` web component within a vets-website app, all `h2`'s on the page will be included. The problem is if an `h2` is missing an ID, then the `va-on-this-page` web component will render a link to the section, but the href will include an empty hash (`#`).

![on this page web component showing link and HTML source with a link with href with only a hash](https://user-images.githubusercontent.com/136959/156027675-de9d2954-0142-4059-9dd5-01efff86288d.png)

We could either not include this section (e.g. an alert header), or show a warning so the developer knows to add an ID.

## Tasks

- [ ] Determine how to handle `h2` with a missing ID
- [ ] Implement fix into `va-on-this-page` web component

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
