### ISSUE TITLE
NOD: Set `socOptIn` to `false` for submissions 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37779]
## Description

Per this Slack conversation &ndash; https://dsva.slack.com/archives/CSKKUL36K/p1646066684092459?thread_ts=1645024816.097359&cid=CSKKUL36K &ndash; the `socOptIn` value should be set to `false` upon submission.

## Tasks

- [ ] Set `socOptIn` value to `false` in submit transformer
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
