### ISSUE TITLE
Research for content placement criteria

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#37775]
## High Level User Story
As a Veteran, I want to easily find information to answer my questions about a benefit so I feel confident and able to proceed with applying.  
As a content author, I need clear and helpful criteria so I can determine where content should be placed in the benefit experience.

## Description
Research with Sitewide Content authors to evaluate the placement criteria created to help identify if content should be placed within the benefit hubs or Resources and Support experiences. 

## Tasks to be completed

- [x] Create research plan and conversation guide
- [x] Schedule research session with sitewide content team writers
- [x] Create needed artifacts: spreadsheet of content criteria, content pages to be analyzed
- [x] Conduct research session
- [x] Feedback synthesis and next steps

**Comment by mnorthuis** [comment]
Research session was held on 3/10
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-strategy-ia-collaboration/content-placement-criteria/research-plan-r1.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-strategy-ia-collaboration/content-placement-criteria/research-conversation-guide-r1.md)

**Comment by mnorthuis** [comment]
Draft of findings are documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-strategy-ia-collaboration/content-placement-criteria/research-findings-r1.md

Closing this work out in order to focus on continuing to evolve and use criteria.
