### ISSUE TITLE
Perform Usability Testing for Core GitHub Ticket

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#37788]
## User Story
As a Governance team member, I want to perform usability testing with select teams to receive input on ticket formatting and the process.

- Intended Audience: VFS Teams
- Desired Outcome: Feedback regarding ease of use and recommended changes
- Due Date: TBD

## Description
While creating the core GitHub ticket draft, we determined that we needed to perform usability testing to ensure that this new process is easily understood by VFS teams and the ticket itself provides the information that our team needs.

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Artifacts Potentially / Confirmed Needing Updates
[Draft core CC ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/briandeconinck-core-cc-ticket/products/platform/vsp-collaboration-cycle/core-collaboration-cycle-ticket.md)
[Draft Yaml-ified version of the ticket](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=cc-test.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
[Usability Research Readout Template](https://docs.google.com/presentation/d/1NTLgI0z8CLpPhH4Gfe09-rOtBY4_vjmVMqrMqiavHv8/edit#slide=id.gcd567e2ae4_0_432)

## Tasks
- [x] Set up [Calendly event](https://calendly.com/collaboration-cycle/platform-governance-research-session?month=2022-04) for scheduling research sessions 
- [x] Contact VFS PMs and ask them to sign up for research session. 
   **Prioritized PMs/teams/products:**
   - VA notify form strike team - form still in progress and/or submitted notifications - PM: Megan Siddle
   - DGIB my education benefits - authenticated 22 1990 e form - PM/Designer: Alex Ferzola (reached out to Russell Lyons first and he recommended we reach out to Alex instead)
   - Identity - mhm inherited proofing - PM: Nick Soutouras
   - CMS offices -  office directory - PM: Wes Rowe
   - AFS education - high demand occupation - PM: Abe Blanco
   - Authenticated experience - Myva dashboard - payment information - PM: Heather Justice
   - Debt resolution - medical copays - PM: Denise Coveyduc
   - 10-10 Team - 1010EZ Short Form - PM: Sharon Kasimow*
   _- *We originally had Auth Profile with Marci McGuire as PM, however she will be moving off the team on 4/4 and Sharon is taking over. So even though the 10-10 team will not continue, the PM will._
**Secondary Teams:**
   - Cedar 1095b -  1095B tax form - PM: Jordan White and/or Munish
   - Virtual agent - chatbot - PM: Ian Santarinala
 - Scheduled sessions:
   - Megan Siddle, 4/6 at 1:00pm ET
   - Heather Justice,  4/7 at 10:30am ET
   - Wes Rowe, 4/8 at 1:00pm ET
   - Nick Soutouras, 4/11 at 4:00pm ET
   - Abe Blanco, 4/13 at 10:30am ET
   - Sharon Kasimow, 4/13 at 4:00pm ET
   - Alexander Ferzola, 4/14 at 12:30pm ET

## Acceptance Criteria
- [x] Willing VFS teams have been identified for testing
- [x] Sample tickets and Conversation Guides have been created for each workshop
- [x] Workshops have been held with VFS teams
- [x] Feedback from each research sessions has been recorded 
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@briandeconinck @seanasewell I DM'd the PMs mentioned above (in the prioritized list) and said:

> Platform Governance team is developing a new process for managing our Collaboration Cycle intake and tickets through GitHub. As a VFS PM who engages in this process, we were hoping you'd be able to help us test it. If so, please sign up for one of the research sessions in this Calendly event. If you are unavailable, we understand. Please let us know. Thank you!

Please be sure to check the Collab Cycle Calendar to see who has signed up. I will fill you in when I return on Monday 4/4.

**Comment by shiragoodman** [comment]
@seanasewell @briandeconinck i updated the ticket with the scheduled sessions. So far, we have 6. I nudged Sharon and Denise is OOO. I think 6 should be sufficient, so we don't necessarily need Sharon however she is one of the more senior PMs we've worked with for a while. 

Can one of you please update this ticket to reflect the dry run we did with Allison on Thursday? Thanks.
