### ISSUE TITLE
Assign product labels to existing staging tickets

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#37783]
## User Story
As a Governance team member, I want to add product labels to existing staging review tickets so that my DOMO dashboards pull in all accurate tickets.

- Intended Audience: Governance Team
- Desired Outcome: Properly labelled tickets for DOMO dashboards
- Due Date: TBD

## Description
Currently our staging review tickets include the team labels. With the move to product labels, each staging review ticket will need to have both a product label and a team label (note: sometimes these may be the same). 
For our dashboards to reflect the tickets that we have created prior to the product labels, we will need to go back and add product labels retroactively (approximately 204 tickets).

_Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />_

## Artifacts Needing Updates
[Query of CC-Dashboard Staging Review Tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3ACC-Dashboard)
Staging Reviews:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26697 - `caregivers` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682 - `gi-comparison-tool` label (completed) - Verified
Note:
Added gi-comparison-tool: #29350, #29374
Added CC-Dashboard to: #33879, #29334
IA Feedback tickets here do not have CC-Dashboard label, should they? #29480, #29480, #29485, #29484, #29470, #29479, #29476, #29471, #29474, #29478, #29482)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30802 - `notification-preferences` label (completed) - Verified
Note: GitHub label appears to be 'notifications-preferences'
Note: Marci added CC-Dashboard and other Staging labels to these tickets in Mid March. (#36359, #35975, #34241, #21473, #13625, #12044, #12024, #11938, #10721, #10330, #10055, #9770, #9166)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34244 - `HLR` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32081 - `MCP` label (completed) - Verified. (Added #34176 & #34177 that were removed from Epic and added to MCP Tech Debt)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33134 - `dt-find-va-form` label (completed) - Verified (Added CC-Dashboard #26353)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26298 - `dt-find-va-form` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29805 - `686` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32717 - `sign-in-page` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26972 - `HCE-Checkin` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32646 - no action
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29178 - `HRT` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34622 - `outreach & events` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/31868 - `typeahead` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29933 - `vanotify` label (completed) - Verified
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34106 - `Virtual-Agent` label (this is a case where the team label is the same as the product label, so no action is necessary since this label should already be applied) - Verified

## Tasks
- [x] Add the specified product label to the child tickets of the Staging Reviews listed above
   - [x] It is not necessary to add the label to the QA Feedback ticket as this ticket is not pulled into the Collab Cycle Dashboard dataset in Domo
   - [x] If the label does not exist, you must create the label [on the labels page](https://github.com/department-of-veterans-affairs/va.gov-team/labels)
- [ ] When complete, query all issue tickets that have the `CC-Dashboard` label in Github 
- [ ] Validate that all issue tickets with the `CC-Dashboard` label have a product label
   - [ ] If any do not have a product label, post them via comment below and tag @shiragoodman 

## Acceptance Criteria
- [ ] Staging Review tickets have product labels added to each
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
Staging Reviews:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26697
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28682
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30802
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34244
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32081
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33134
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26298
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29805
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32717
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26972
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32646 - no feedback!
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29178
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34622
https://github.com/department-of-veterans-affairs/va.gov-team/issues/31868
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29933
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34106

**Comment by Saraharaba8** [comment]
@shiragoodman Thank you!!

**Comment by shiragoodman** [comment]
@SarahKay8 please get this completed ASAP.

**Comment by chaseakirby** [comment]
@shiragoodman @SarahKay8 I have reviewed the tickets and added labels to a few (some product labels and some CC-Dashboards. 
Shira, would you mind reviewing the tickets I listed for gi-comparison-tool and notification-preferences?
I saw the bug label on the IA tickets and wasn't sure if it should have CC-Dashboard.
The notifications-preferences tickets didn't have our standard formatting.

**Comment by shiragoodman** [comment]
GI Comparison Tool tickets look good. Notifications preferences tickets are also good - I confirmed with Heather that the label should be `notifications-preferences` so I'll update the label name in the details above.

Closing the ticket.

**Comment by shiragoodman** [comment]
just noticing the comment about Marci. I'll remove CC-dashboard from those tickets.
