### ISSUE TITLE
Platform Support Bot Enhancements

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#37793]
## Issue Description

Redesign the Support Report/Data Analysis Process.

Enhance the Slack bot to add resilience for Slack outages and errors with the Google spreadsheet. 

We should determine how to reduce the size of the google sheet and archive any past data.

NOTE: We may want a use a different data storage method than Google Sheets.  

## Background

The platform support bot has had errors and failures.  There are a few points of failure and support issues with the current design of the support bot process.  

- Google Sheet has limitation of changes to it when the bot is running.
- The Heroku platform is currently outside of our AWS environment and may have issues.
- Slack failures can cause issues with the support bot
- Metrics data can be lost when the support bot is down 
- Changes to the location of the Header will cause issue with the Slack Bot.

---
## Tasks
- [ ] Identify issues with the Slack bot Javascript code that can be enhanced with better error checking
- [ ] Determine if we need to replace the google sheet with another Data storage method.
- [ ] Determine how to handle loss of metrics related for the Support Request Reporting process.

## Acceptance Criteria
- [ ] A Slack Bot Process that is resilient to errors on Slack and the Google Sheet.
- [ ] A method of Archiving Old Months, Sprints of Reporting Data from the google sheet.

**Comment by rmtolmach** [comment]
Related issues:
Slackbot - Set up in EKS https://github.com/department-of-veterans-affairs/va.gov-team/issues/15142
[Support Slackbot] Decommission the Heroku support slackbot https://github.com/department-of-veterans-affairs/va.gov-team/issues/30089
[Support Slackbot] Deploy Support Slackbot to Utility VPC https://github.com/department-of-veterans-affairs/va.gov-team/issues/30090

**Comment by mchelen-gov** [comment]
Please include a "Requesting team" field so that we can track support volume by VFS team.

**Comment by zachclarity** [comment]
@powellkerry   we need to create an offical product document for this.  See template. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md
