### ISSUE TITLE
Add Intercept Survey Decline Rate to Medallia Dashboard

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#37806]
## Issue Description
_To help us and product owners better understand how users are viewing and responding to invitations to leave feedback via the Medallia intercept/satisfaction survey, we want to add _decline rate_ to the Medallia dashboard_

---
## Tasks
- [x] Create a Global VA segment for decline rate

## Acceptance Criteria
- [x] Decline rate segment has been created?
- [x] The decline rate segment filters properly?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Thanks to Brian Martin, got Medallia GTM events in DOMO. Added a decline and acceptance percentage to the MVP.

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 you cool with closing this ticket? I added a disclaimer below the percentages.

**Comment by jwoodman5** [comment]
yeah. sounds good.
