### ISSUE TITLE
[SW-Content] COVID-19 - Translation copy to drupal pages, review and publish [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37814]
## Story
As a Veteran I need current and translated information for COVID-19 vaccines, so I can best understand and find my best health care solution.

## Resources:
http://preview-prod.vfs.va.gov/preview?nodeId=11463

http://preview-prod.vfs.va.gov/preview?nodeId=34627

http://preview-prod.vfs.va.gov/preview?nodeId=34054

## TASKS
- [x] Send content to translators
- [x] Input translated content to drupal pages
- [x] Review and publish pages
- [x] Send live links of pages to double check translations

## Acceptance criteria
* Page content is translated and confirmed by second translation group.
* Pages are published.

**Comment by RLHecht** [comment]
@lunascoop Here are the translations to put in. [https://app.zenhub.com/files/133843125/351bb353-45b8-4d7f-99a5-0140f230ea6a/download](https://app.zenhub.com/files/133843125/351bb353-45b8-4d7f-99a5-0140f230ea6a/download)

[https://app.zenhub.com/files/133843125/47a38c5a-f962-417f-96b1-52e9c831aba7/download](https://app.zenhub.com/files/133843125/47a38c5a-f962-417f-96b1-52e9c831aba7/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Tungkol sa bakuna laban sa COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36427
Booster na iniksyon ng COVID-19 at karagdagang dosis: http://preview-prod.vfs.va.gov/preview?nodeId=34394
Missing translation for If you got the Pfizer-BioNTech or Moderna vaccine (pieced together from existing bullets) and Find out if you can get an additional vaccine dose (Google translated).

Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359
Sobre las vacunas COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36461
Vacunas de refuerzo y dosis adicionales de COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=34408
Missing translation for If you got the Pfizer-BioNTech or Moderna vaccine (pieced together from existing bullets) and Find out if you can get an additional vaccine dose (Google translated).

**Comment by RLHecht** [comment]
Thanks @lunascoop I published all of these and will send to the volunteer translators on Monday once the pages are live.

**Comment by lunascoop** [comment]
@RLHecht page has been updated.
Sobre las vacunas COVID-19: http://preview-prod.vfs.va.gov/preview?nodeId=36461

**Comment by RLHecht** [comment]
Thanks, @lunascoop I reviewed and published this.
