### ISSUE TITLE
Adjust COE Uploaders

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37810]
## Background
For the COE uploaders to work correctly, we need to ensure that they are able to upload multiple documents in the event that the Veteran has multiple files they need to send in to get a Certificate of eligibility.

## Considerations
The functions in the standalone version may differ from the uploader inside the form although only slightly and in how the descriptions are utilized.

## Tasks
- [x] Adjust the uploader in the standalone version to be hooked up to the BE
- [ ] Adjust the uploader in the form version to be hooked up to the BE (stretch)

## Acceptance Criteria
- [x] The standalone version accepts multiple documents (when connected to the BE)
- [ ] The form version no longer has a file type field, if possible
- [x] A PR has been requested for merging

**Next steps**
- BE version of this to hook it up?
