### ISSUE TITLE
Adjust pattern for `SaveInProgressIntro` on Introduction page

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#37812]
## Background
We want to change the pattern we are using for entering the COE form from the introduction page. We will be adding an extra `SaveInProgressIntro` component to the top of the page. This `SaveInProgressIntro` will display an action button if the user hasn't entered the form before, and a notice asking them to continue their request or start a new one if they have an in-progress request. This will alleviate the issue that we currently have where users aren't given a way to enter the form if they have an in-progress form.

## Tasks
- [ ] Add extra `SaveInProgressIntro` to top of introduction page

## Acceptance Criteria
- [ ] extra `SaveInProgressIntro` has been added to top of introduction page
- [ ] A PR has been requested for merging
