### ISSUE TITLE
Update VA Digital Services Handbook - Digital Delivery Guide

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37827]
## User Story
As a VFS team member, I want to ensure that the Platform guidance I am directed to is current and up to date so that I may better support my team and also meet the Platform expectations.

Intended Audience: VFS Teams

## Description
VFS teams are still going to the VA Digital Services Handbook for guidance. The [Digital Delivery Guide](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/index.html) contains many outdated references including the [Onboard team](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/onboard-team) page which has been replaced by Platform Orientation, and the [Research and Discovery](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/research-and-discovery/index.html), [Prototype](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/prototype/index.html) and [Build and Test](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/build-and-test/activities#pre-launch-activities) pages all include outdated guidance that has since been replaced by the Collaboration Cycle.

Per @gmaciolek from the Platform Content team, "Our content ecosystem is fragmented in ways that are not intentional and are confusing to end-users. We should consider how to clean things up and finalize the migration of information to the Platform website which would involve: sunsetting info sources, updating info sources, and documenting the purpose and goals of each info source to make it clear what information goes where and why."

## Tasks
- [ ] _Placeholder task_

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@vbellissimo  Ok, just seeing your label removal from a few months back. Do you think we should escalate this to Platform leadership?

**Comment by vbellissimo** [comment]
@shiragoodman Hi Shira, looking at this ticket again, I think the scope of this might be a lot bigger than this single ticket. Do you know the answer to these questions?
- Outside of Gretchen's comments, how did this ticket originate?
- We don't maintain the VA Digital Service Guide Handbook referenced. Do you know who does? https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/index.html

**Comment by shiragoodman** [comment]
@vbellissimo For question 1, I know Gretchen contacted me via Slack. I don't know who maintained the VA Digital Service Guide Handbook. 

I agree that the scope of this is likely bigger than this single ticket.

**Comment by vbellissimo** [comment]
@shiragoodman My instinct is to close this ticket due to the fact that we've been auditing the website and we also have an upcoming initiative that will attempt to tackle a way to ensure the Platform website is refreshed with the help of content SMEs across Platform teams.

My suggestion would be to close this ticket and simply pose the question to leadership about who maintains the VA Digital Service Guide Handbook? Do VFS team members still use it? Do they think it overlaps with the content on the Platform website?

**Comment by vbellissimo** [comment]
Hi @shiragoodman Yes, I'll ping her on Slack and ask her.

**Comment by vbellissimo** [comment]
@shiragoodman thoughts from Erika are that the decision to retire this site feels like a Governance PO call, which I think is Matt Dingee? She agrees that the site looks like it can be deprecated. Still unsure who actually maintains it though.

**Comment by shiragoodman** [comment]
Thanks @vbellissimo ! I'll fill in @humancompanion-usds . :)

**Comment by humancompanion-usds** [comment]
Oof. I know the people who wrote the Handbook and it would be a shame to deprecate it. There is a ton of content there that bridges the gap between the USDS Playbook and how VA operates on a daily basis. But I don't understand the history of why we let that site rot so happy to hear more about the thoughts behind all of this.

**Comment by shiragoodman** [comment]
@humancompanion-usds Our biggest question right now is... who owns the VA Digital Services Handbook? Is there a process for getting it updated?

**Comment by EWashb** [comment]
I agree with this one too @shiragoodman @jknipes

**Comment by shiragoodman** [comment]
thanks @EWashb ! FYI we had 84 issues on our backlog and 27 of them were items we thought made sense for other teams. I may have a few more to send your way. Keep an eye out!

**Comment by jknipes** [comment]
@shiragoodman and @EWashb Content Team will own this ticket and related discovery. Additional ticket(s) to referenced here.

**Comment by jknipes** [comment]
Related [Discovery Ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/75456)

**Comment by jknipes** [comment]
@shiragoodman and @EWashb we are having trouble finding out who owns VA Digital Services Handbook, but I am wondering if maybe the original issue has been resolved?

The issue, which is from 2022, originates from a [Slack thread](https://dsva.slack.com/archives/CJRQ85PQB/p1645821839402419) where it is stated:
> One of the new VFM PM's shared this link with me earlier today: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html It's the VA Digital Service Handbook and it looks like it references the process that was in place pre-Collaboration Cycle. 

The above **VA.gov experience standards** page on Platform Website now links to the [VA Design System website](https://design.va.gov/about/experience-standards/), instead of VA Digital Services Handbook, which has not been updated since 2018, and is likely not being used.

cc: @CherylEvans

**Comment by shiragoodman** [comment]
@jknipes yea, I think so. If there's no links on Platform Website that point to the VA Digital Services handbook, then I think we're in the clear. Thanks, Joe.
