### ISSUE TITLE
Synthetic Monitors - Migrate synthetic monitors to Datadog

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37848]
## Problem Statement 
Currently, there are Synthetic monitors set up in AWS Cloudwatch that need to be migrated into Datadog.

How might we relocate these synthetic monitors into the new Datadog framework?

## Hypothesis or Bet
By migrating to Datadog we will consolidate our monitoring & alerting solution into one location, leverage Datadog's visualization framework, and feed data about synthetic monitoring into our data warehouse.

## We will know we're done when... ("Definition of Done")
- [x] When all monitors have been migrated over to Datadog and are functioning correctly
- [x] An approach to alerting levels and pathways have been proposed, approved and implemented
- [x] A dashboard to show the status of monitors has been created
- [x] Documentation has been updated to reflect the changes
- [x] Old canaries and documentation has been decommissioned
- [x] The launch/change has been announced to appropriate platform channels

## Known Blockers/Dependencies 
None

## Projected Launch Date
April 2022

### ... tested?
- [x] Monitors have been Peer-reviewed by another team member
- [x] Documentation has been Peer-reviewed by another team member 
- [x] Documentation has been reviewed by the SRE team

### ... documented?
- [x] Playbook document for how to respond when synthetic monitors alert
- [x] Document containing guidelines for how to create/maintain synthetic monitors
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2105246089/Synthetic+Monitors+Product+Outline)
- [x] Announcement text is prepared/reviewed/approved
- [ ] Announcement is made into Platform team
- [ ] Announcement is made into EOS Demo

### ... measurable
- [x] Synthetic monitor output is [tracked here](https://app.datadoghq.com/dashboard/ri4-6ac-h88/vagov-qas-team-synthetic-monitoring?from_ts=1652113686008&to_ts=1652117286008&live=true)

### When you're ready to launch...
- [x] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 
- [x] Announce

### Documentation
* **PRODUCT_NAME**: Synthetic Monitors
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2105246089/Synthetic+Monitors+Product+Outline
* **User Guide**: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2164785226/Synthetic+Monitoring+with+DataDog
* **Playbook**: https://vfs.atlassian.net/wiki/spaces/TTT/pages/1848999954/On-Call+Playbook+for+Synthetic+Monitor+Alerts

### Testing
* **Usability test**: This is an internal tool so no usability testing is being conducted.
* **Manual QA**: We will be using a test plan in TestRail to verify that the monitors in Datadog re-create the same monitoring and alerting as the Canaries in Cloudwatch.
* **Automated tests**: N/A

### Measurement
* **Success metrics**: TBD in Product Outline
* **Release plan**: TBD

**Comment by mchelen-gov** [comment]
For definition of done: synthetic monitors in DD trigger alerts (Slack + Pagerduty)

**Comment by pjhill** [comment]
I added that to definition of done, thanks!
