### ISSUE TITLE
[Content] [SMS]Revisions to "We couldn't find an appointment scheduled for you today" Wording

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37847]
## Background
Shawn Adams brought up this point when reviewing the check-in product guide, "Can you clarify the "veteran has 0 appointments today"?  There's many nuances here and don't appear consistent with the message being returned.  If the patient has appts but the scenario is built around the premise that that none are mobile-enabled or none have a check-in enable status, then saying they have no appointments scheduled today is not correct.  It's specifically that there's nothing we can check you in for which is different than saying there's none today."

Make sure we cover the "invalid" clinic scenario (see https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38060)

Can we reword this text message to be more honest to what is actually occurring?

## Background
[Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653499137753019)

Current message = "We’re sorry. We couldn't find an appointment scheduled for you today. Ask a staff member or call us for help. Find our phone number: https://www.va.gov/find-locations/."

# Tasks
- [x] Create new wording (Consider making CTA only to talk to a staff member.)
- [x] Document wording in Sketch and update user flow document

# Acceptance Criteria
- [x] Share with Chris Horton, so the wording changes can be added to the CHIP backlog. CHIP should be the one to update the error message source of truth

**Comment by kristenmcconnell** [comment]
@sarahknoppA6 @jparker0425 FYI, this was created after reviewing Shawn Adams comments on the check-in product guide. Let me know if you think this should remain a ticket.

**Comment by kristenmcconnell** [comment]
Information from Shawn Adams on this: https://dsva.slack.com/archives/C02UP02HHGX/p1653500818155919?thread_ts=1653488587.597109&cid=C02UP02HHGX

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell @loripusey it looked like Shawn's later message was to audit all of those messages. 

"Can we review all of the messages that are potentially sent to ensure uniformity?  Some of these developed over time and I think now might be a good time to briefly ensure the communication is uniform and providing a good sense of 1) what happened, 2) what is happening now, and 3) what needs to happen next."

https://dsva.slack.com/archives/C02GXKL8WM6/p1653501212665709?thread_ts=1653499137.753019&cid=C02GXKL8WM6

Whenever we refine this, we should refine the scope.

**Comment by loripusey** [comment]
I'll add a ticket for an audit

**Comment by niradatta1** [comment]
@Hortonio Hi Chris, Attaching screenshot of theSMS text content recommendation. This is for the scenario when no appointments can be found.  ![Screen Shot 2022-07-29 at 12.13.17 PM.png](https://images.zenhubusercontent.com/6148aad90fad659c5233b36f/bcf1170e-7b58-4248-9b9b-af8c92008a71)
A few notes on approach: 
- Made the messaging more accurate (per Shawn's notes above). But didn't want to provide so much info regarding the many reasons why this error may be occurring. 
- Focused on what would be most helpful to Veteran, the CTA to talk to staff member. This is consistent how we're handling day of check-in errors in our in-app messaging. 
- Softened the tone to minimize the risk of sounding too alarmist e.g. many Veterans travel pretty far to get to their appointment.

**Comment by Hortonio** [comment]
@niradatta1 Slight variation with a few edits:
"Sorry, we're having trouble finding an appointment to check you into today. Please ask a staff member for help."

- Matching format of the message in ticket [43546](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43546), open with 'Sorry'
- Adding the word 'please' for instruction/command to see staff member

**Comment by niradatta1** [comment]
@Hortonio Thanks!

**Comment by Hortonio** [comment]
@niradatta1 Merely suggestions, edit/modify as you see fit!

**Comment by niradatta1** [comment]
Thanks @Hortonio ! So I'll update our user flows to reflect this new wording. Would you be able to (1) update your source of truth documentation and (2) put this in your backlog as well?

**Comment by Hortonio** [comment]
@niradatta1 sure no problem, we included updating the source of truth as part of the acceptance criteria for implementing the changes, [1086](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/1086)

**Comment by niradatta1** [comment]
Thanks @Hortonio !

@loripusey @kristenmcconnell Merged the finalized user flow to Abstract. @zach-park will update to Sketch Cloud at end of this sprint.
