### ISSUE TITLE
[FE][BUG] appointment pre-checkin complete status not set when confirmation pages are skipped

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#37846]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---

## User Story

- As an MSA, I wish to know when a Veteran has completed pre-check-in, so that I do not have to ask them to confirm demographic data.
- As a Veteran, I wish the MSA to know when I have completed pre-checkin, so that I do not have to re-answer questions.

## Description

While testing the new "set pre-checkin started" functionality with the back end team, we discovered that appointments are not set to "pre check-in complete" if a veteran has recently confirmed their demographics data.

To reproduce:

- complete pre-check-in for one appointment
- complete pre-check-in for a second appointment

You will not see the demographic confirmation screens, and the pre-check-ins endpoint is not called when the pre-check-in complete screen is shown, so the appointment status is not updated.

## Tasks

> this is a list of technical tasks that need for this ticket

- [x] Call pre-checkins endpoint when demographics are up to date.
- [x] Create or update unit tests
- [x] Create or update e2e tests

## Acceptance Criteria

> when is the ticket done

- [x] Appointment status is set to "pre check-in complete" when demographic confirmation screens are not shown
- [x] tests are updated to confirm this use case
- [x] Passes Accessibility checks using axe
- [x] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
Just validated this on staging:

Demographic confirmations were up to date, so all confirmation screens were skipped. The request was sent:

![Screen Shot 2022-03-04 at 9 01 32 AM](https://user-images.githubusercontent.com/101649/156797247-3f960103-7dba-4a91-9abb-df8989f51f44.png)

Confirmed in the cloudwatch logs that the appointment status was set correctly:

![image (24)](https://user-images.githubusercontent.com/101649/156797406-8da5027a-5fa0-420a-8e94-b608e782ee28.png)

**Comment by acrollet** [comment]
production confirmation is being discussed in this slack thread: https://dsva.slack.com/archives/C022AC2STBM/p1647877996490979

**Comment by acrollet** [comment]
This was validated in prod last night with Stephen and Robert Tow. (Pre-check-in completed successfully with all confirmation pages skipped)
