### ISSUE TITLE
Form system: Add `ui:autocomplete` setting

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37849]
## Description

When an `input` has the `autocomplete` property set, it will provide automated assistance in filling out form field values, as well as guidance to the browser as to the type of information expected in the field ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)).

Adding this will make filling out forms that ask for an phone number, email, address and name auto-fill the inputs if there is saved data.

## Tasks

- [ ] Update React-jsonschema-form to accept `ui:autocomplete`
- [ ] Update docs
- [ ] Add tests
- [ ] Update platform definitions to add `autocomplete` properties to uiSchema

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
