### ISSUE TITLE
[Design] Auth Profile - Review text that appears above Edit button throughout VA.gov Profile

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#37845]
## Background
During mockup reviews for Personal Info Revision updates, it was observed that the "Edit your profile to..." content immediately above the Edit buttons in VA.gov profile may not be sufficiently clear and actionable.  This ticket is to take inventory of the various add/update message that appear above Edit buttons and work with Content, IA and Accessibility to make them consistent, easy to understand, and clearly actionable. (e.g., "Click Edit to...") 

We may also consider removing "your profile" to help shorten to one line of text on mobile,.  As is, it looks like there is an orphan word in all of our mobile fields except for Pronouns, and "your profile" doesn't seem to further clarify anything by being there. 

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/4c388ef7-8128-4cca-9e81-c997919adc59)
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/cf8055ad-0e7a-4bd8-bbd3-a65387892255)

## Tasks
- [x] Review and document existing content above each edit button
- [x] Work with content and accessibility to come up with a better message
- [x] Review with PM and PO
- [x] Work with PM to create corresponding FE ticket for updating in FE code.

## Acceptance Criteria
- [x] Review and document existing content above each edit button
- [x] Work with content and accessibility to come up with a better message
- [x] Review with PM and PO
- [x] Work with PM to create corresponding FE ticket for updating in FE code.

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO @Samara-Strauss Noting that we briefly touched on this topic in Danielle's office hours! 

@DanielleThierryUSDSVA's suggestion to explore for use throughout Profile is "Choose edit to add a [preferred name]"

**Comment by Samara-Strauss** [comment]
That sounds great to me!

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss -- working on this ticket for all of Profile, but should I wait to change the phrasing in the Personal information pages for now since that would make the content different in Sketch files and on staging? Or for that reason should I do them first so they can be updated on staging as well before QA? Thanks!

**Comment by Samara-Strauss** [comment]
If Tze is referencing Sketch files for QA, then we can wait until after QA is completed to make this update.

If Tze is not referencing your Sketch file for QA, then you can do this any time. It's a bummer that this will make the contact center guide slightly different from the UI, but I don't know that we need to update all of the screenshots again for this small copy change.

**Comment by cgednalske** [comment]
@Samara-Strauss Yes, Tze is referencing the Sketch files for QA. And that's a great point about the Contact Center Documentation. This change doesn't effect all sections - just Personal information and Contact information, so it's mostly Personal info screenshots and two or three Contact info screenshots that would eventually need to be updated in the documentation. 

If it will throw a few things out of sync, should we instead hold off entirely on this update right now? I'd just be updating Contact information at the moment. I think we had said this change is not necessarily pressing, just helpful to further clarify the instructions. 

Good with either way, so just let me know your preference!

**Comment by Samara-Strauss** [comment]
Will you check in with Tze about this? I think it's OK to update the contact information stuff since that doesn't affect his QA, but Tze can let us know if we're making something out of nothing for you to do the copy update for personal information now before QA is complete.

**Comment by cgednalske** [comment]
Certainly! I'll check with him. 👍 Thanks!

**Comment by cgednalske** [comment]
Noting that this is now on hold for both Contact information and Personal information. Both are included in QA, so changing the Sketch files would somewhat muddle the process.

**Comment by Samara-Strauss** [comment]
Thank you! I think Tze might actually be done with QA, and if not, he will be soon. This can probably be done some time in the sprint that starts tomorrow.

**Comment by cgednalske** [comment]
@Samara-Strauss oh great! That sounds good to me 👍

**Comment by cgednalske** [comment]
This has been updated in Personal information ([Sketch files](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)) and Contact information ([Sketch files](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655))! @SKasimow do we need to set up a corresponding FE ticket?

**Comment by SKasimow** [comment]
@cgednalske - yup, I will create one for this and ping you when I have it drafted

**Comment by SKasimow** [comment]
@cgednalske - FE ticket is #41909
