### ISSUE TITLE
Gather information about existing synthetic monitors in AWS canary

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37850]
## Issue Description
In order to successfully migrate the monitors from AWS Cloudwatch to Datadog, we need to understand the acceptance criteria for each existing monitor and come up with a plan to recreate that acceptance criteria in Datadog.

---
## Tasks
- [x] Understand how many/which synthetic monitors there are
- [x] Understand what they are doing from a business-rule standpoint, and how it notifies when there are issues (reporting to pager duty, etc)

## Acceptance Criteria
- [x] Analysis of existing monitors is in this ticket as a comment

**Comment by rbeckwith-oddball** [comment]
Technically the information gathering phase is complete. Writing up the documentation for the existing synthetic monitors will be updated today.

**Comment by pjhill** [comment]
Is there a list of synthetic monitors compile somewhere that we can review?
Do we have an understanding of the business goals for each synthetic monitor? Even better, do we know what behavior each action in the canary is accomplishing?

**Comment by pjhill** [comment]
@rbeckwith-oddball --
Hey, would you please add a link to the document you produced for this ticket to the ticket? Also, if the tasks are completed and the acceptance criteria are satisfied in your opinion and based on your work, then please tick them off in the body of the ticket.

**Comment by rbeckwith-oddball** [comment]
The analysis of existing canary monitors in AWS that require migration can be found [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2132836394/Synthetic+Monitors+-+AWS+Canaries).

The canary script files are stored in the document as `zip` files that conform to the AWS canary structure.

_**i.e. using vagov-search.zip as an example:**_
```
$ unzip -Z1 vagov-search.zip
nodejs/
nodejs/node_modules/
nodejs/node_modules/vagov-search.js
```
