### ISSUE TITLE
Update Permissions for DevOps Repo

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3786]
## User Story or Problem Statement
As an Infrastructure Engineer, I need to know that the DevOps repo is a secure place, but also not cumbersome to commit too so I can have a smooth working repo for my code.

## Goal
_Have a permissions model for the DevOps repo that makes sense for all the people using it._

## Acceptance Criteria
- [ ] _Discover what type of permissions needs to be set on the repo and come up with recommendations on how and why to set them that way_
- [ ] _Talk with the SRE group about findings some delivery and recommendation that can be taken_
- [ ] _Set the agreed-upon permissions in the repo_
- [ ] _Montior and check back in with the group next SRE and if fine, done. If not then iterate_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@wyattwalter can we close this guy now?
