### ISSUE TITLE
Set up client in Keycloak for Grafana

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37860]
We need to add Grafana's roles / groups to keycloak.
Roles and permissions can be viewed [here](https://docs.google.com/spreadsheets/d/1MDlN36DVuqTVQ2Mn6ZAmbkgk45jMuatJS_O0IU6pVOc/edit#gid=1913326915)

Notes:
 - there are only three roles: `admin`, `editor`, `viewer`.
 - the only way to do this is to send those strings to grafana as part of a group. 
 - can leverage settings from PoC

[Grafana OAuth with Keycloak and how to validate a JWT token
](https://janikvonrotz.ch/2020/08/27/grafana-oauth-with-keycloak-and-how-to-validate-a-jwt-token/)

**Task is done when:**

- [x] Confirm Dev Grafana setup is working
- [x] Client exists in Utility Keycloak
  - [x] Pointing to Login.gov Prod
  - [ ] Created by Terraform
- [x] Roles created in Grafana Client (in Keycloak)

**Comment by sGplkrsh** [comment]
This is for the Utility KC, copying settings from POC? Utility grafana (the official Grafana that the dev are using).
Step 1: Prod Login.gov would be needed - Kevin is working with the Identity team to get this information

**Comment by kjduensing** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Access-Management---Platform-Spike-Team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/37860?planning-poker) with ZenHub @calquisola @iriteshp @kylesoskin

**Comment by calquisola** [comment]
Client and roles done manually.
