### ISSUE TITLE
Read documentation and get familiar with creating monitors in Datadog

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37870]
## Issue Description
Based on what was learned from 'Gather information about synthetic monitors in AWS, research similar setups and functionality in Datadog documentation to help understand how this should be done in Datadog.

---
## Tasks
- [ ] Review findings from [37850](https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/37850)
- [ ] Research the use of Datadog and gain understanding of how to implement required functions in Datadog to support synthetic monitors

## Acceptance Criteria
- [x] Feel we have an adequate understanding of Datadog to successfully create these monitors
