### ISSUE TITLE
DEPRIORITIZED - Create a more reliable experience of review instances

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37873]
# THIS EFFORT WAS DEPRIORITIZED # 

Being moved to Icebox as it may resurface in the future

## Problem Statement 
VFS team use of review instances is low. VFS teams are unsure how to use a review instance and what can be accomplished there as part of their SDLC. Platform does not currently understand why review instance use is low, or what may be missing / unsupported in review instances that might increase VFS team use. Additionally, recent shifts in platform architecture require a new implementation of review instances.

* How might we determine how often and for what reason VFS teams are using review instances?
* How might we determine what capabilities are missing from review instances?
* How might we enhance the capabilities of review instances to increase VFS team use of them?
* Might there be an opportunity to streamline review instance infrastructure?

## Hypothesis or Bet
We believe that if review instances are easy to use and provide the capabilities that VFS teams need to QA and demo their products, then VFS teams will release higher quality more accessible products to QA and resolve quality and accessibility issues more quickly.

We bet that if we make review instances more useful for testing and demoing a VFS team's incremental work that VFS teams will be able to more easily verify their products behaviors and business goals in an integrated environment.

## We will know we're done when... ("Definition of Done")
- [ ] We have an understanding of VFS pain points and of any features that are missing in the existing review instances
- [ ] We have an understanding of key metrics to the current approach to review instances to inform our planning for a new approach
- [ ] A new proposed plan for creating review instances is documented in an RFC and circulated for feedback
- [ ] A refined plan is formalized and documented in an ADR
- [ ] Platform created an on-demand GHA workflow that takes one parameter (a branch name) and creates a review instance of that branch
- [ ] Platform has created at least one test harness to handle on demand build-up of test data on review instances
- [ ] Platform has a basic front-end that allows users to target a vets-website branch and push a button to deploy that branch's code to a review instance
- [ ] At least 4-5 usability tests have been conducted against this proof of concept, and findings have been documented

## Known Blockers/Dependencies 
None

## Projected Launch Date
Aug 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by mchelen-gov** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44486
