### ISSUE TITLE
Decommission the monitors in AWS Canary

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37872]
## Issue Description
Once the Datadog monitors have successfully passed all tests, and documentation is completed and reviewed, decommission the AWS Synthetic monitors

---
## Tasks
- [ ] Collect details of performance comparison based on [37871](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/37871)
- [ ] Review with team PM and TL to verify all details are as expected
- [ ] Decommission the AWS synthetic monitors

## Acceptance Criteria
- [ ] AWS Monitors are turned off and no longer being run

**Comment by rbeckwith-oddball** [comment]
There aren't really any existing canaries aside from the one we manually created while waiting for datadog migration

**Comment by rbeckwith-oddball** [comment]
I have all the resources listed and ready for removal. Just want final approval before deleting them.

**Comment by rbeckwith-oddball** [comment]
[PR #11522](https://github.com/department-of-veterans-affairs/devops/pull/11522) to remove the AWS synthetic monitors from the devops repo.

**Comment by pjhill** [comment]
@rbeckwith-oddball -- Thanks for knocking this out -- hopefully the PR to remove the AWS synthetics is not too stale. Let's get that merged.
