### ISSUE TITLE
Recreate existing suite of monitors in Datadog

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#37871]
## Issue Description
Migrate the 5 current synthetic monitors from AWS to Datadog

---
## Tasks
- [x] Migrate the 4 synthetic monitors to Datadog
   - [ ] ~~Migrate democanary~~
   - [x] Migrate dslogon_status
   - [x] Migrate vagov-heartbeat
   - [x] Migrate data-fetch
   - [x] Migrate va.gov search
- [x] Tests are created to verify the monitors work as intended
- [x] Define an acceptable period to observe behaviors to compare with AWS monitors
- [x] Assemble a dashboard in Datadog that aggregates the status and history of all Datadog hosted synthetic monitors

## Acceptance Criteria
- [x] All synthetic monitors have been created with similar behavior in DataDog
- [x] Monitors alert the same PagerDuty groups as the AWS Cloudwatch versions
- [x] Monitors are integrated with the same Slack channels and notify in the same way as the AWS Cloudwatch versions
- [x] A Datadog hosted dashboard displaying the current status and history of all synthetic monitors
- [x] Observed behaviors of the AWS monitors and Datadog monitors is identical
   - [x] (If applicable) Any discrepancies are examined and explained, and resolved if necessary 
- [x] Monitors owned by our team are tagged with `team:qas`

**Comment by rbeckwith-oddball** [comment]
Building, redeploying, and retesting will be the main time issues

**Comment by rbeckwith-oddball** [comment]
Just a note, *democanary* was built on the same day as `tud-basic-check` and I don't think it ever worked. Nor did the person clean up afterwards.

**Comment by pjhill** [comment]
I tagged these two monitors with `team:qas` --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/b8b91be3-34de-4441-9729-a00c4ed07159)

**Comment by pjhill** [comment]
Let's schedule an internal demo / review of the progress so far to discuss --
1. Status of effort in detail
2. Look at the config a bit
3. Discuss post-MVP enhancements
4. Discuss what kind of dashboard would be useful for these 4-5 monitors
