### ISSUE TITLE
[PM, Design, FE] My VA - Payment info: Executing accessibility tests for Staging review

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#37878]
## Background
To prepare for Staging review of the new Benefit payments and debts section, we must complete accessibility testing, and document it.

### Resources
- [Staging review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [How to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)
- [TestRail Test Plan/Test Runs](https://dsvavsp.testrail.io/index.php?/runs/view/3087&group_by=cases:section_id&group_order=asc)
- [GH Accessibility tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/Staging%20Review/Accessibility%20testing.md) (same as TestRail, just in GH)

## Tasks
- [x] FE - Perform the accessibility tests
- [x] PM - Perform the accessibility tests
- [x] PM to assist in tracking progress in staging review artifact documentation

## Acceptance Criteria
- Accessibility testing is completed and evidence is provided.  Tickets are created for any test defects found.

**Comment by hdjustice** [comment]
Running tests, results can be viewed in either GH or TestRail.
Additional color contrast test run with the WCAG color contrast checker:
![image](https://user-images.githubusercontent.com/92328831/158928690-d07cea38-41d6-4199-8db3-a45f5047e1e9.png)

**Comment by hdjustice** [comment]
All accessibility testing completed except for screenreader, which was advanced but not required foundational.  Staging review scheduled for Friday.  This ticket can be closed
