### ISSUE TITLE
Design intent The Debt Resolution Team - Combined VA Debt Portal

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#37887]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/product_outline.md)
 
- [ ] Wireflow ideation ([UXPin](https://preview.uxpin.com/32e8ac818076b3dc502846e0b13356fa40779575#/pages/147589342/simulate/sitemap?mode=i))
   - These wireflows were used for early IA discussions about the potential flow and entry points depending on the user's goal 
- [ ] User flows containing wireframes ([Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1645453970389/5712442eb61e558df96599ac35c346436aafcc9c?sender=riley5075) | [GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_va_debt_portal/design/user-flows))
   - These were created incorporating IA and stakeholder feedback 
- [ ] [IA strategy ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36844)
- [ ] Research Plan - TBD

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
Hi @rileyorr! The research plan is not required for the Design Intent checkpoint, we have that bullet there for if you do have one you would like to share. Feel free to go ahead and schedule the meeting!

**Comment by allison0034** [comment]
Hi @rileyorr confirming your design intent is scheduled for 3/7 at 3:30 pm ET

**Comment by CherylEvans** [comment]
No Content feedback.  Nice presentation.  Looks great!

**Comment by Saraharaba8** [comment]
No A11y feedback from me. Wireframe was great!

**Comment by jimuhh** [comment]
No IA feedback, thanks.

**Comment by rileyorr** [comment]
Thank you all for the feedback! Just cross referencing the design feedback ticket (#38128) in which the feedback has been incorporated into our prototype.
