### ISSUE TITLE
Collaboration Cycle for Demo Product 1

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#37890]
# Collaboration Cycle for Demo Product 1

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [ ] Complete the **[VFS product information](#vfs-product-information)** and **[kickoff questions](#kickoff-questions)** sections, and attach any **[artifacts](#artifacts)** you have available.

**Platform**

- [ ] Review the responses and update the ticket with recommended touchpoints and practice area involvement.
- [ ] Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

Skip to...
- [VFS product information](#vfs-product-information)
- [Kickoff questions](#kickoff-questions)
- [Artifacts](#artifacts)
- [Collaboration Cycle touchpoints](#collaboration-cycle-touchpoints)

## VFS product information
- **Product Name:** Demo Product 1
- **Feature Name:** N/A            
- **VFS Team Name:** Governance
- **GitHub label for product:** demo-product-1     
- **GitHub label for feature:**     
- **Start date of enhancement:** 3/2/2022
- **Feature launch date:** 3/3/2022
- **Production URL:**
- **Front-end information:**
