### ISSUE TITLE
3/4/2022 Prescription Tracking Training - Hampton, VA

### ISSUE THREAD

**Issue by djfredvs** [department-of-veterans-affairs/va.gov-team#37891]
## Acceptance Criteria
Acceptance criteria are pre-defined requirements that must be met to mark a task as complete. What needs to be done to mark this task as complete?

- [X] Training email sent
- [X] Training Date Established 3/4/2022  2 pm est
- [X] Get reports-level access list to @chancetheoriginal
- [X] Conduct Training
- [X] Send follow-up resource email 
---

**Comment by djfredvs** [comment]
Training Complete
