### ISSUE TITLE
[BE] Setup review environment for the Check-In Experience team

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#37895]
## Problem Statement

Engineers working on the va.gov Check-In project cannot connect to live CHIP and LoROTA services, which are running downstream in a pre-prod(or equivalent) environment in AWS, from their local environment(dev laptops). Development and testing by the FE and BE disciplines can diverge and as a result, lead to undesirable bugs and regressions in our production environment causing an unpleasant user experience.

We plan on leveraging the va.gov review environment as a workaround to address the connectivity problem. The review environments run the FE and the BE code off of topical feature branches(worked on by developers but not yet merged into master), and as a result, can be tested end-to-end on the review environment against a preproduction version of CHIP and LoROTA. Bugs on the feature that's being actively developed can be discovered early and worked on quickly while shortening the feedback loop from UX designers and product managers/owners.

## Questions to Answer
- Do we have a good understanding of how review environments are stood up, run, and torn down as of today?
- Do we have documentation, emails, or slack thread conversations about the topic that we can share with the HCE team?
- How will the connections to LoROTA and CHIP services be set up in the review environment?
- The review environment is stood up on one AWS account, and the CHIP and LoROTA services are set up in a completely separate AWS account. Will there be any issues in communication between the two accounts? What special permissions or privileges do we need first?
- Will there be difficulties with fully authenticated Check-ins on the review environment?
- What support do we need from the Platform team?

## Tasks
- [x] Setup CHIP config in the review environment settings file in the `devops` repository.
- [x] Create AWS param store entries for CHIP staging credentials.
- [x] Setup LoROTA config in the review environment settings file.
- [x] Create AWS param store entries for LoROTA staging credentials.
- [x] Create staging fwdproxy entries for CHIP and LoROTA.
- [x] Setup the appropriate ports in the `main.tf` files.
- [x] Create a Platform ticket to fix an issue where the CHIP and LoROTA hosts are not resolving on the review environment.
- [x] Curate a list of documents about the review environment for the HCE team.
- [x] Work with Platform in getting Terraform changes applied.
- [ ] Conduct preliminary testing of the Check-in feature on the review environment after all the problems and issues have been addressed and fixed.

## Acceptance Criteria
- [ ] Development teams can collaborate and test end-to-end ongoing topical feature branches(FE/BE) on the review environment before merging code into their respective master branches.
- [ ] Non-engineers can expertly pull up and use the review environment to conduct testing to their satisfaction and needs.

**Comment by dillo** [comment]
Initial PR: https://github.com/department-of-veterans-affairs/devops/pull/10825

**Comment by loripusey** [comment]
@dillo where are you with this ticket? Are you ready to demo this new environment and provide access to team members (like myself) who would like to use it?
cc: @sarahknoppA6

**Comment by loripusey** [comment]
Gaurav now owns this and will present to the team, document how to use this environment, and get team members set up to use it that want access

**Comment by sarahknoppA6** [comment]
@randomsync can you provide an update on the status of this ticket, please?

**Comment by randomsync** [comment]
I’m documenting the steps and will work with Dillo to fill some gaps and then publish them.

**Comment by randomsync** [comment]
I've published the notes on how to access review environments here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/review-environments.md.

**Comment by loripusey** [comment]
Walk through with Product & UX scheduled for 4/18.
