### ISSUE TITLE
[PM] On-site Notifications: Regroup with VA Notify

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#37909]
## Background
The team needs to meet with our VA Notify partners to discuss their work effort and timeline for on-site notifications MVP.

### Resources
- High level [MVP requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md)

## Tasks
- [ ] Regroup with VA Notify to discuss their work effort and next steps
- [ ] Confirm timeline for the changes needed by VA Notify
- [ ] Confirm timeline for Frontend Engineer work to connect Frontend to Backend API (check with Taylor)

## Acceptance Criteria
- A timeline for delivery of VA Notify code for our integration has been provided and committed.

**Comment by hdjustice** [comment]
On 3/15 - Met with VA Notify at bi-weekly sync.  Per Melanie (PM), the team will  be researching the swagger doc info from Lihan, and their approach to integrating with My VA to send a flag/alert that a new notification needs to be displayed for a user.  The anticipated timeline to begin the work is currently beginning of April.  We have another meeting on 3/29 and will confirm the VA Notify team's progress.

**Comment by hdjustice** [comment]
Taylor confirmed that the level of effort to complete the connection of Frontend to our API is a significant effort (estimated 5), taking the most of a sprint to complete.
