### ISSUE TITLE
Update 526 tech docs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37908]
## Description

Update and/or check for updates in 526 engineering docs regarding:
- Wizard changes
- Benefits Delivery at Discharge addition
- Review errors
- PTSD bypass questions
- EVSS to Lighthouse move
- EVSS validation rules
- Release plan for 8940/4192
- Past fixes
- future plans

## Tasks

- [ ] Update 526 tech docs
- [ ] Update transition docs

## Definition of done

- [ ] All tasks complete
