### ISSUE TITLE
[Design] Updates to pre-check-in user guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#37900]
# Description
A draft of the pre-check-in product guide was created in #36342. We are now receiving feedback on the guide, so updates need to be made.

# Tasks 
- [x] Update the guide
- [x] Export finalized PDF and Word versions

# Acceptance Criteria
- [x] Upload PDF and Word versions to[ GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md)
- [x] Post announcement of their finalization in Slack

**Comment by kristenmcconnell** [comment]
Location of Google doc working file: https://docs.google.com/document/d/1FnRnbI2CbdsbtPvGmc2kmGzHz2GuySO5/edit?usp=sharing&ouid=106255737927186094724&rtpof=true&sd=true

**Comment by kristenmcconnell** [comment]
Edits from Corey have been incorporated into the document.

**Comment by kristenmcconnell** [comment]
Blocked until Stephen Barrs can review.

**Comment by kristenmcconnell** [comment]
Edits from @stephenBarrs available in [this Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1646255971216129?thread_ts=1645563293.464999&cid=C022AC2STBM). I incorporated all of his feedback and passed a final Word doc to Nira to review the formatting (since I don't have Word). Once she reviews it, I will post to GitHub and close this ticket.

**Comment by niradatta1** [comment]
@kristenmcconnell Latest updates done and linked to in https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/checkin/product/product-guides/README.md. Posting to slack, with a question about next step: what is the process to hand this off to staff so they can start using them?
