### ISSUE TITLE
Send the 1880 to VBMS and LGY

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#37919]
## Background
At some point we need to fill out the PDF template with the form data from va.gov. This ticket is for that.

## Considerations
- Possibly break out the call to send the PDF to VBMS, into a separate ticket and this ticket just creates the PDF.
- In the PDF there is a note that says additional information may be added with additional pages. If this is the case, we may have to loop through an array and add to the end of the form.

## Tasks
- [ ] ~~Create a pdf for this form ([source](https://www.vba.va.gov/pubs/forms/VBA-26-1880-ARE.pdf))~~ (another ticket)
- [ ] Send to LGY (confirm with Kelli) 
- [ ] and send to VBMS (a known endpoint) 

## Acceptance Criteria
- [ ] A PDF for this form has been generated and sent
- [ ] A PR has been submitted for review

**Comment by saderagsdale** [comment]
@scottymeyers @kylesoskin added refinement labels and updated AC. Please review and let me know what you think.

**Comment by scottymeyers** [comment]
Looks good.

**Comment by data-doge** [comment]
_For now, these are notes to myself, but please feel free to weigh in._

## Generating a PDF form

- A  [`SavedClaim::CoeClaim`](https://github.com/department-of-veterans-affairs/vets-api/blob/3cadbdbe48ed45f6be545e83d55f4db872e99f1e/app/models/saved_claim/coe_claim.rb#L5) is created when the front-end POSTs form data to [`/vo/coe/submit_coe_claim`](https://github.com/department-of-veterans-affairs/vets-api/blob/7bccf4358ed19e7b4837da0a6d38b2d457af23e0/app/controllers/v0/coe_controller.rb#L18).
- `SavedClaim::CoeClaim`'s base class is [`SavedClaim`](https://github.com/department-of-veterans-affairs/vets-api/blob/7f060a9c999c35fc84669c53ce8458d3fe45a946/app/models/saved_claim.rb#L17-L18), which contains a  [`to_pdf`](https://github.com/department-of-veterans-affairs/vets-api/blob/7f060a9c999c35fc84669c53ce8458d3fe45a946/app/models/saved_claim.rb#L94) method. This method uses [`PdfFill::Filler#fill_form`](https://github.com/department-of-veterans-affairs/vets-api/blob/965292f24386de5f07ed89bfaba0f9412fd2986e/lib/pdf_fill/filler.rb#L56) and [`PdfFill::Forms::Va261880`](https://github.com/department-of-veterans-affairs/vets-api/blob/f62977ff3c7a7d0d951f1b5156828cf026cd8d4e/lib/pdf_fill/forms/va261880.rb#L2-L3) to [fill a template PDF and save it to a `tmps/pdfs` directory](https://github.com/department-of-veterans-affairs/vets-api/blob/965292f24386de5f07ed89bfaba0f9412fd2986e/lib/pdf_fill/filler.rb#L66-L67).
- So, generating a PDF just requires us to call `.to_pdf` on our `SavedClaim::CoeClaim`, somewhere in [`V0::CoeController::submit_coe_claim`](https://github.com/department-of-veterans-affairs/vets-api/blob/7bccf4358ed19e7b4837da0a6d38b2d457af23e0/app/controllers/v0/coe_controller.rb#L18).

**Questions**

- How are we going to append attachments? Where are these attachments? Are there any existing methods for appending attachments?

## Sending form to LGY

- On submit, [we are already sending the form to LGY](https://github.com/department-of-veterans-affairs/vets-api/blob/7bccf4358ed19e7b4837da0a6d38b2d457af23e0/app/controllers/v0/coe_controller.rb#L27).

**Questions**

- What is LGY and what is the result of sending this form to LGY?

## Sending form to VBMS

- [`ClaimsApi::VBMSUploader`](https://github.com/department-of-veterans-affairs/vets-api/blob/4daaf196c5ca43c58061708202418d0347019d67/modules/claims_api/lib/claims_api/vbms_uploader.rb#L4) is used to upload forms to VBMS, [in `SavedClaim::DependencyClaim`](https://github.com/department-of-veterans-affairs/vets-api/blob/6244cf6e6c51334f143763ef035a72792539a253/app/models/saved_claim/dependency_claim.rb#L98), and [`SavedClaim::VeteranReadinessEmploymentClaim`](https://github.com/department-of-veterans-affairs/vets-api/blob/6937b447d1bed298d67fb141832708d9aa4bc9a8/app/models/saved_claim/veteran_readiness_employment_claim.rb#L139) (`ClaimsApi::VBMSUploader#upload` contains some code specific to `SavedClaim::VeteranReadinessEmploymentClaim`, that should be generalized. 
> When we upload to VBMS we use VA file number and we might not have that (other services that use BGS, we can use their lookup)
- In the two provided examples, if a `file_number` is not present under `veteranInformation`, `file_number` is [defaulted](https://github.com/department-of-veterans-affairs/vets-api/blob/6937b447d1bed298d67fb141832708d9aa4bc9a8/app/models/saved_claim/veteran_readiness_employment_claim.rb#L144) to the user's SSN. Some history on that here: https://github.com/department-of-veterans-affairs/vets-api/pull/6419 ("This PR also prioritizes VAFileNumber as the id to send to VBMS when submitting to eFolder. We were using SSN which would have worked the majority of the time but in those few instances that va file number is diff from SSN VBMS would have looked up a vet by file number with ssn and it would have failed."). See also https://github.com/department-of-veterans-affairs/vets-api/pull/7491.

**Questions**

- Is it okay to rely on `ssn` instead of `file_number`?

## Considering CMP as an alternative

- If it turns out this is necessary, perhaps we can draw inspiration from [`SavedClaim::VeteranReadinessEmploymentClaim#send_to_vre`](https://github.com/department-of-veterans-affairs/vets-api/blob/6937b447d1bed298d67fb141832708d9aa4bc9a8/app/models/saved_claim/veteran_readiness_employment_claim.rb#L113), which calls a `send_to_central_mail!` method if an upload to VBMS fails. However, it's not immediately clear to me how, or whether, this method makes the PDF accessible to the user. 

## Ensuring that PDF is uniquely identifiable

- [`ClaimsApiVBMSUploader#fetch_upload_token`](https://github.com/department-of-veterans-affairs/vets-api/blob/4daaf196c5ca43c58061708202418d0347019d67/modules/claims_api/lib/claims_api/vbms_uploader.rb#L55) suggests that `filename` will always be unique to any other file, as it contains a uuid. Additionally, the filename will contain the `form_id` of the form, if the `form_path` from `PdfFill::Filler#fill_form`.

**Comment by saderagsdale** [comment]
Hey Eugene! @data-doge thank you for adding questions here. Let me see if I can offer any help. See below:

- How are we going to append attachments? Where are these attachments? Are there any existing methods for appending attachments? _I believe the place these are appended is in the Veteran's e-folder in VBMS, to be stored under a unique naming convention so it can be easily surfaced on the frontend later._ 
- What is LGY and what is the result of sending this form to LGY? _LGY (Loan Guaranty) is the backend service responsible for the underlying business logic. Scott had been in close contact with their devs to conduct testing with them in the last two sprints. I can connect you with their team to ask questions if needed._ 
- Is it okay to rely on `ssn` instead of `file_number`? _Previously our PO, Matt Self, stated that the VA wants to step away from relying on SSN, so he can probably clarify this business requirement. I'll ask him._

**Comment by saderagsdale** [comment]
Update on this question @data-doge: Is it okay to rely on ssn instead of file_number?

- Matt can introduce us to an SME to clarify this. That person's name is John Rhaghi. Let me know when you're ready to tee up that conversation.

**Comment by saderagsdale** [comment]
Re-adding the `needs-grooming` label until we get clarification on the ssn/file number requirement.

**Comment by data-doge** [comment]
Thanks @saderagsdale! I'm ready to have that conversation with John whenever he is.

**Comment by saderagsdale** [comment]
@data-doge Cool beans. Waiting for an intro from Matt. He's on PTO.

**Comment by saderagsdale** [comment]
Reminded Matt to introduce us today. Should be completed shortly.

**Comment by saderagsdale** [comment]
@data-doge Answer from John: Best case is to use ICN instead of File_Number or SSN as an identifier.

**Comment by saderagsdale** [comment]
@data-doge to confirm if overflow attachment work is already done.

**Comment by Midge-dev** [comment]
@saderagsdale Hello! Confirming whether or not this work was implemented?

**Comment by saderagsdale** [comment]
@Midge-dev Howdy. It was not completed. (Also worth noting that most of the code was written by another team before us). Let me know if you have other questions.
