### ISSUE TITLE
HLR tier 3 tech support

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37913]
## Description

Contacted by Luke (former PM) to help a Veteran with help for starting the Higher-Level Review form. The Veteran was only seeing a loading spinner on the introduction page. I asked them to try again a week later after HLR v2 was available at 100%.

The next week, the Veteran reported still seeing the loading spinner, so I requested getting their `account_uuid`. Once that is provided, we can get one of our backend engineers to look up their contestable issues and determine why there's a problem with it loading.

## Tasks

- [ ] Obtain `account_uuid` from Luke
- [ ] Check the Veteran's contestable issues
- [ ] Troubleshoot loading issue

## Definition of done

- [ ] All tasks complete
- [ ] Veteran is able to access HLR

**Comment by Mottie** [comment]
We're still awaiting the account UUID for the Veteran. Pushing this work to the next sprint.

This could also be a log in issue.

**Comment by Mottie** [comment]
No followup from Luke as of yet. We will open a new ticket once the account UUID is provided.
