### ISSUE TITLE
Add skip_dupe to MHV and Cerner USiP Authentication

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#37922]
## Issue Description
Append `?skip_dupe=true` to USiP authentication attempts for MHV and Cerner

---
## Tasks
- [ ] skip_dupe=true param is correctly appended

## Acceptance Criteria
- [ ] skip_dupe=true param is appended for MHV and Cerner authentication via USiP
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nsoutouras** [comment]
MSPI: Blocked until we validate API change.
