### ISSUE TITLE
[EKS] Modify Traefik configs to persist forwarded headers and IP addresses

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#37932]
## Description

The problem statement here is the fact that the `x-forwarded-*` headers were not persisting through traefik which meant the client IP would not show correctly in vets-api logs.  

There were two components to this.  First being that our traefik service is configured as a nodePort.  At the kubernetes level we need to set the configuration `externalTrafficPolicy: Local` on the traefik service itself.

https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

Second we also need to tell traefik the IP ranges coming from our load balancers so it will accept and pass along said headers.

https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers

We will want to set this for both web and websecure entrypoints in all environments

https://github.com/department-of-veterans-affairs/va.gov-team/issues/35359

## Tasks

- [x] Set proper configurations in traefik
- [x] Sync traefik deployments in argo

## Acceptance Criteria
- [x] Go to dev-api.va.gov/v0/status with the correct header so you are redirected to eks vets-api
- [x] See client ip as `remote_ip` in loki logs https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-5m%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%20%7C%3D%20%5C%22v0%2Fstatus%5C%22%22%7D%5D
- [x] Working as intended for http & https

**Comment by mleclerc00** [comment]
This has been applied to all environments but utility for the time being.  It had some unforeseen consequences in utility when it comes to logging into tools such as argocd and grafana.

In theory this is because of how setting `externalTrafficPolicy: Local` causes the requests to flow differently 

https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

I _think_ the solution here is to set sticky sessions for said ingresses that will require this but not entirely sure and haven't gotten around to testing 

https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute 

examples can be seen in the link above 

![image](https://user-images.githubusercontent.com/76792875/156656628-5be4c36c-c4f0-4649-8550-586ca5785e10.png)

**Comment by mleclerc00** [comment]
Reverted in all environments aside from dev for the time being, both keycloak and console ui teams have been seeing issues with requests resulting in a 504 with this in place.  We will need to figure out how to remedy this since we will need to persist client IPs in our logs

**Comment by mleclerc00** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38120

closed in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/38120
