### ISSUE TITLE
Give SRE members ability to reset user passwords in DSVA AWS

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#37943]
## Description
The Infrastructure team would like the SRE team to handle password resets moving forward.

---
## Tasks
- [ ] Create a IAM policy for SRE members to change user passwords. Attached this policy to a new SRE user group.
- [ ] Assign current SRE members to the new user group.

## Acceptance Criteria 
- [ ] Current SRE members have the ability to change a user's password in the DSVA AWS account.

**Comment by jsgarmon** [comment]
Zenhub created 2 issues, this one being the duplicate.
