### ISSUE TITLE
Give SRE members ability to reset user passwords in DSVA AWS

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#37942]
## Description
The Infrastructure team would like the SRE team to handle password resets moving forward.

---
## Tasks
- [x] Create a IAM policy for SRE members to change user passwords. Attached this policy to a new SRE user group.
- [x] Assign current SRE members to the new user group.

## Acceptance Criteria 
- [x] Current SRE members have the ability to change a user's password in the DSVA AWS account.

**Comment by jsgarmon** [comment]
Verified with Gino that he can now manage user passwords.
