### ISSUE TITLE
Link guidance to static vs. dynamic in Collab Cycle Kickoff ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#37952]
## User Story
As a VFS team member completing a Collaboration Cycle Kickoff ticket, I want to know and understand the difference between static pages and dynamic pages (ie tools and applications) so that I may answer the kickoff questions correctly.

- Intended Audience: VFS Teams
- Desired Outcome: Updated Collaboration Cycle Kickoff ticket and guidance
_Improved responses and reduced confusion in CC Kickoff ticket_
- Due Date: ?

## Description
In the [Collaboration Cycle Kickoff ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D) and in the [Collaboration Cycle Kickoff page on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Collaboration-Cycle-Kickoff.1760493650.html), VFS teams are asked to identify if their work will involve changes to tools and applications, static pages and/or both. Teams seem to struggle with this question as they don't have a clear understanding of what qualifies as a static page.

The Sitewide Content & IA team put together guidance on [The difference between static and dynamic pages on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) and have given us permission to link it in Collaboration Cycle documentation.

## Artifacts Confirmed Needing Updates
[Collaboration Cycle Kickoff GitHub template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team&template=collab-cycle-kickoff.md&title=Collaboration+Cycle+Kickoff+%5BTeam+Name%2C+Feature+Name%5D)
[Collaboration Cycle Kickoff page on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Collaboration-Cycle-Kickoff.1760493650.html)
[Confluence: Collaboration Cycle Kickoff](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+Cycle+Kickoff)

## Tasks
- [x] Add link to [The difference between static and dynamic pages on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) in GitHub template 
- [x] Add link to [The difference between static and dynamic pages on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) on Platform Website page re: Collab Cycle Kickoff

## Acceptance Criteria
- [ ] Collaboration Cycle Kickoff GitHub template has been updated per guidance
- [x] Collaboration Cycle Kickoff page on Platform Website has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@shiragoodman I added a Desired Outcome in italics that I think may fit better with the user story, feel free to delete if you disagree. 
I also split the task into two so that it was clear both the GitHub template and Platform Website need updates.
Otherwise, I think this is ready.

**Comment by shiragoodman** [comment]
I like the desired outcome you wrote. Thanks, Chase!

**Comment by CherylEvans** [comment]
@shiragoodman I've added the links to both:
https://vfs.atlassian.net/wiki/spaces/PPST/pages/2116714756/Cheryl+-+Collaboration+Cycle+Kickoff
https://github.com/department-of-veterans-affairs/va.gov-team/pull/38314

**Comment by CherylEvans** [comment]
@shiragoodman PR for this issue has been squashed and merged.
