### ISSUE TITLE
Public Websites: Sprint 69 Priorities

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#37951]
## **Sprint 69 Priorities: March 9 - 22 , 2022** 

HRT Static Landing Page Research | Events V2 Updates | In-Take Redirect Requests vetted by IA | Redirects & In-take Requests | Tech-Debt per Velocity | Transition Documentation  
 
1. Research --> HRT static landing page research actions. 
2. Events V2 --> Fix identified bugs/issues --> Turn feature flag back on when tested/validated 
3. Intake | Redirect requests --> Priority tickets from our intake process along with key redirect requests. 
4. Tech Debt --> Mission to clear out tech-debt and mitigate risk
5. [Ongoing] Transition Documentation --> Breadcrumbs for the next team. 

### Capacity Planning: PTO/Holiday's
Brian: Last Day on Contract 3/15.
Trent: 3/11 (half day)
Matt: 0
Cindy: Conference attendance 3/9-11, 3/22.
Dave: 3/14 (3/15-16 limited afternoon availability) 

### Team Transition Documentation 
[Team Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/public-websites/Transition%20Documentation)
- [ ] [Research] Create Transitional Document: Public Websites Team #38091
- [ ] [Product] Create Transitional Document: Public Websites Team #38092
- [ ] [Frontend Development] Create Transitional Document: Public Websites Team #38093

### HRT Research - Static Landing Page Research 
- [ ] [Research] Prep Tasks for Research: Harassment Landing Page & Poster (HRT) #31148
- [ ] [Research] Conduct Research: HRT Static Landing Page #38081
- [ ] [FE] HRT static landing page content updates (Staging) #38202

### Events V2 Bug/Issues 
- [ ] [BUG] O&E - Event-detail page - Custom Date Range not working #38145
- [ ] [Bug] Page Title/h1 and page intro overriding VAMC event calendars h1 #38147
- [ ] [FE] Events V2 UX Enhancement - Error Messaging #38157
- [ ] [FE] Enable Events V2 feature flag #38251 

### Campaign Landing Page (VOTE)
- [ ] [Campaign Landing Page] - VA VOTE #37773
- [ ] Analytics KPI dashboard update request for [Public Websites Team - Campaign Landing Page] #37987

### Home Page Updates  
- [ ] Veteran Image shift on VA.gov Homepage ONLY (Behind a Feature Flag/O% of users) #37435
- [ ] [FE] VA.gov deep link change for lab and test results page #38198

**Discussion** can we make this update but not release?  Basically have available for future release?

#### Priority Tickets - Complete This Sprint
- [ ] [VAMC] Redirect Request - VAMC - left nav - URL depth changes #37094
- [ ] "Request COE" page updates from eBenefits Migration #37424
- [ ] [Bug] Investigate/fix icons not rendering properly for jump links (TOC on hub pages) + breadcrumbs #34502
- [ ] Create | Modify e2e tests to ensure proxy rewrite header/footer code is working as expected #33078
- [ ] Bad URL for default og:image meta tag #33552

### Discussion Topics/Grooming <Team Grooming Items>
- [ ]
