### ISSUE TITLE
Ensure Vets.gov ATO is compliant 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3795]
## User Story or Problem Statement
As a member of the platform, I need have a compliant ATO to work under so VFS teams can keep developing on the platform.

## Goal
_Ensure all items requested below by the VA are met_

## Acceptance Criteria
- [x] _Incidence Response Plan (IRP)_
- [x] _Incident Response Test. (IR Test)_
- [x] _Vets.gov Database scans_
- [x] _Disaster Recover Plan (DRP)_
- [x] _Information System Contingency Plan Test (ISCP Test)_
- [x] _Risk Assessment (RA)_
- [x] _System Security Plan (SSP)_
- [x] _Database scan Findings_
- [x] _Threat Model_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
Still have a few things to clean up before closing this.

**Comment by ricetj** [comment]
Done
