### ISSUE TITLE
Allowlist/Only Changed Apps Documentation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#37963]
Problem:
Documentation is needed for VFS and platform teams to understand what the allowlist is and how to get on the allowlist. 

Definition of Done:
Clear documentation (following documentation standards) has been created for the following

- [ ] Release build of only changed apps in the vets-website main (master) branch #34671
- [ ] Criteria for getting on the allowlist
- [ ] How to get on the allowlist
- [ ] Common cross app imports and how to address them as a VFS team
- [ ] Deployment documentation
