### ISSUE TITLE
[EKS] Disable admin user in argocd

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#37964]
## Description

As suggested by argo documentation, now that we have sso authentication for people to use for argo we can disable the admin user

https://argo-cd.readthedocs.io/en/release-1.8/operator-manual/user-management/#disable-admin-user

---
## Tasks
- [x] Create configmap in the templates directory of the argocd repo https://github.com/department-of-veterans-affairs/vsp-infra-argocd
- [x] redeploy argocd 

## Acceptance Criteria 
- [x] the admin user should be disabled in argocd

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
![image](https://user-images.githubusercontent.com/76792875/156646618-2272708d-897a-4773-916c-67350e6f9e5e.png)
