### ISSUE TITLE
[Platform SRE]: Define how to handle Production Build Related Failures and PR failures  ? 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#37962]
## Description
There have been issues with PRs passing review and still causing errors for other developers like: [Example Slack Threads](https://dsva.slack.com/archives/C02VD909V08/p1646334815874169). and another [Example Slack Thread #2](https://dsva.slack.com/archives/CBU0KDSB1/p1646331794269939)

We should define a process to enhance our checks and the steps to handle these ?

## Tasks
- [ ] Identify the issues and if there is a pattern
- [ ] Determine what type of checks or automation could be added to the process
- [ ] Document a process , workflow for these type of issues with reporting method.

## Acceptance Criteria 
- [ ] A documented process for responding to this issues
