### ISSUE TITLE
Form submitter name not showing on Confirmation Page

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#37968]
## Background
The confirmation page includes an inset that includes information about the form submission such as the name of the submitter, submission date, etc. Currently the name of the submitter does not show because changes to the schema are not reflected in the `ConfirmationPage` component.

## Tasks
- [x] Form submitter name should be shown in primary inset

## Acceptance Criteria
- [x] Submitter name is displayed as expected
- [x] A PR has been requested for merging
