### ISSUE TITLE
[Monitoring] Add loki endpoint synthetic monitor for all environments

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#37970]
## Description
Currently we only have a synthetic monitor that watches the loki endpoint for dev and staging

Circling back to add the same monitor for the remainder of the environments

https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/loki.yaml

---
## Tasks
- [x] Add needed code to terraform to include all environments
- [x] apply terraform

## Acceptance Criteria 
- [x] confirm that there is a endpoint monitor for all environments

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
https://app.datadoghq.com/synthetics/tests?query=loki
