### ISSUE TITLE
Rated Disabilities High-Level Research Summary

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#3798]
### User Story
As a member of the eBenefits team, I need a high-level research summary of Rated Disabilities usability testing, so that I can validate or course-correct my development efforts as necessary.

### Task
Create one-page, high-level summary of usability testing research findings; post in Github as MD doc.

### Acceptance Criteria
- [x] Review usability testing session recordings and notes
- [x] Produce high-level summary of initial findings
- [x] Post findings in Github; tag Andre Zwilling, Shawna Hein

**Comment by sporeboy** [comment]
Work on the research summary has begun here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-summary.md

**Comment by sporeboy** [comment]
Initial Draft of research summary complete and ready for review here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-summary.md

**Comment by sporeboy** [comment]
@azwilling @sshein Initial draft of eBenefits usability testing high-level summary is complete here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-summary.md
