### ISSUE TITLE
(Q2) Harden file upload microservice for external consumption

### ISSUE THREAD

**Issue by rogersarkis** [department-of-veterans-affairs/va.gov-team#37998]
## Problem Statement 
We have a number frontend apps and `vets-api` endpoints that deal with file uploads. Each app & endpoint combo handle uploads as a "one-off" kind of solution. Each unique solution comes with potential tradeoffs involving security vulnerabilities & performance degradation. We want to have some kind of unified / intentional / global rules & restrictions that apply to all uploads so as to protect va.gov as a whole from such performance & security vulnerabilities.

The purpose of this epic is to iterate upon the initial implementation of the file upload microservice and prepare the file upload service for external consumption. 

## Hypothesis or Bet
We will be able to deliver a solution which will identify a solution to unify the file-upload process within vets-api and define the steps that will need to be taken in order to migrate endpoints on vets-api to leverage this service. 

## We will know we're done when... ("Definition of Done")
- [x] API is finalized and documented. 
- [ ] Endpoints that were not implemented in the initial prototype have been implemented. 
- [ ] Performance tests have been performed to verify that the solution meets the required performance benchmarks. 
- [ ] Service is in a state where it could be promoted to a higher environment. 
- [ ] A service design mockup has been created, this should describe how 
- [ ] Design documents are finalized and shared with relevant stakeholders. 

## Known Blockers/Dependencies 
_this work is to be completed after the initial prototype is completed_

## Projected Launch Date
_middle-to-end Q2_

## Launch Checklist
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ]  We have documented the performance and security benefits of leveraging our new file upload service. 
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by ewilson-adhoc** [comment]
One of the early conclusions that came from our review of Q2 goals was the idea that a prototype should not get moved to production, which nullified the purpose of this epic. Cleaning it up now.
