### ISSUE TITLE
Update Ops Docs

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3800]
## User Story or Problem Statement
As a VSP Ops member, I need have up to date docs so that VFS teams can be set up for success.

## Goal
_Update the docs that we maintain and manage_

## Acceptance Criteria
- [ ] _Update IR docs_
- [ ] _Update SOCKS docs_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
Please see #22984 and #22985 for initiatives that will address this later in 2021. 

Closing.
