### ISSUE TITLE
Fix wording on "Apply for Disability Compensation" screen

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3801]
## User Story:
As a claimant, I need clear and concise wording to be displayed while I complete my Disability Compensation claim so that I can follow the direction properly.

## Problem Statement
The language on the 'apply for disability compensation' screen says to go back one screen to add another disability, but if you go back one screen, it takes you to Individual Unemployability. Wording should be fixed.

## Tasks
- [ ] Correct wording to provide accurate communication to claimant
- [ ] Confirm with design

## Acceptance Criteria:
- [ ] Wording matches capability on the 'apply for disability compensation' screen

![Screen Shot 2019-11-26 at 9.29.42 AM.png](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/23d1da6b-33ca-4c63-95ac-76bc153bd7d2)

**Comment by Mottie** [comment]
The context of this ticket makes it seem like changing the wording would be the best way to fix this issue; e.g. "Please go back to the start of step 2 and add it."

But since the step to add a new condition is about 8 steps prior to this page, depending on the choices in-between, I think a better solution would be to add a link that takes the user back to that specific step.

![Screen Shot 2019-12-26 at 4 02 23 PM](https://user-images.githubusercontent.com/136959/71491916-1fad1c00-27f9-11ea-865e-5f5bba922c31.png)

(Link tooltip would read: "Add missing disabilities")

I'm not 100% sure where that link should lead, but probably step 2a, the disability orientation page (URL: `/disability/file-disability-claim-form-21-526ez/disabilities/orientation`)

![Screen Shot 2019-12-26 at 4 13 34 PM](https://user-images.githubusercontent.com/136959/71492152-b29a8600-27fa-11ea-9f1e-e5466c92bde4.png)

because disabilities may be added from:

* Existing rated disabilities
* New disabilities (increase compensation only)
* Add disabilities - for user 228, only this step is visible.

Please let me know if this issue requires only a content change, or if a link is the best solution.

**Comment by AZSchneider** [comment]
This looks like the right place to take the user @Mottie
