### ISSUE TITLE
[FE] Update Error Handling on Validation Pages

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#38018]
---

## User Story

> these should be why the veteran cares, and the veteran gets out of it.

- As a veteran, I should be able to attempt lastName and last4 validation multiple times before being redirected to an error page

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

Update the error handler on the day-of and pre-check-in validation pages to check for the error code and message being sent by vets-api.

Update mock-api and tests to use the new error format.

`{"errors":[{"title":"Authentication Error","detail":"Authentication Error","code":"LOROTA-API_401","status":"401"}]}`

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] Update error handler on Day-Of validate page
- [ ] Update error handler on Pre-Check-In validate page
- [ ] Update mock-api to return new error format
- [ ] Update Error message content to match latest UX mocks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by dcgoodwin2112** [comment]
Related to BE changes here:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/36957

**Comment by dcgoodwin2112** [comment]
Slick thread on error message updates: https://dsva.slack.com/archives/C02GXKL8WM6/p1646843282890739?thread_ts=1646772434.302529&cid=C02GXKL8WM6

**Comment by randomsync** [comment]
Here's the response vets-api will return when it gets a 401 from LoROTA:
```
{
	"errors": [
		{
			"title": "Authentication Error",
			"detail": "Authentication Error",
			"code": "LOROTA-MAPPED-API_401",
			"status": "401"
		}
	]
}
```

**Comment by dcgoodwin2112** [comment]
Validation needed: 

- Enable feature flip in staging. 
- Test validation pages in staging to ensure retry logic is active. 
- Enable feature flip in prod

**Comment by dcgoodwin2112** [comment]
This has been tested on staging
![Screen Shot 2022-03-17 at 6.10.39 PM.png](https://images.zenhubusercontent.com/6144d3396adfc573505df211/740fc452-8427-4f6c-96ce-17f0d9f0f23b)
