### ISSUE TITLE
Update VA.gov Product Directory with GitHub product labels

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38068]
## User Story
As a Governance team member, I want to ensure that the VA.gov product labels used by VFS teams are stored somewhere public so that the labels in use are transparent to all.

As a VFS team member, I want to make sure I can see what labels Platform is using to track my VA.gov product so that I can notify them if changes need to be made.

As an OCTO team member, I want to know what product labels are used by VFS teams for VA.gov products so that I can potentially run my own queries and have clear visibility of the health of VA.gov.

- Intended Audience: Platform, VFS and OCTO
- Desired Outcome: Updated [VA.gov Products page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) that includes va.gov-team repo product labels
- Due Date: 

## Description
We have captured the labels that VFS teams use to track their VA.gov products across the va.gov-team repo. We now must make sure we store and track these labels alongside the correct product so that we have a reliable source of truth for the labels, and so that VFS and OCTO can see what labels are in use for their own queries, etc. and in case the label changes.

The purpose of this ticket is to transfer the labels captured in the[VA.gov Product Labels spreadsheet](https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0), specifically column E "Recommended Product Label", to the [VA.gov Products Page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) in Confluence. A new column will need to be added to the VA.gov Products page table titles, "va.gov-team GitHub label"

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative

## New Artifacts 
N/A

## Artifacts Confirmed Needing Updates
[VA.gov Products](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) page in Confluence

## Tasks
- [x] Create a new column in the VA.gov Products page table titled, "va.gov-team Product label"
- [x] Add the labels from the, "Recommended product label" column of the [VA.gov Product Labels](https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0) spreadsheet to the new va.gov-team GitHub label column, formatted as code
- [ ] Send updated [VA.gov Products](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) page to VFS PMs for their awareness.

## Acceptance Criteria
- [ ] VA.gov Products page Confluence document has been updated per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
hey @mchelen-gov . I have added the va.gov-team product labels captured in the [VA.gov Product Labels spreadsheet](https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0) to the[ VA.gov Products page](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) on Confluence. As you can see, there are still many products on the VA.gov Products page with missing labels. The reverse is also true - there are many products I captured labels for that are not listed in the VA.gov Products page. 

In addition, there were many products that I had challenges with:

- Original Claims (form 526) was identified as a product by the Claims and Appeals PM, but in the VA.gov Products list, it's listed as as Parent Product.
- My Education Benefits had multiple entries in the VA.gov Products list,
- Site Navigation was only represented as Left Navigation in the VA.gov Products List
- VA.gov Products page fails to list the common name of some of these products, so it was challenging to map (for example, Personalized Career Planning & Guidance Application (VAF 28-8832) is commonly referred to as Chapter 36 but there's no reference to that at all)
- Many teams have different interpretations of Product, Parent Product, Hub and (not listed) features of products.

I think it's clear that we need to prioritize creating a product model for VA.gov for VFS teams to follow.

**Comment by shiragoodman** [comment]
@CBonade @JoeTice @holdenhinkle FYI - just wanted to make sure you've seen this ticket and are familiar with the comments I made above before I close. I do not think it will impact your work, however I still wanted to make sure you're aware. Please let me know if you have any questions.
