### ISSUE TITLE
[Design] Improved wording when current appointment is at an invalid clinic

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#38060]
# Description
We need to create improved SMS wording due to the scenario called out within [this Slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1646665478649269). 

# Tasks
- [ ] Create new wording
- [ ] Add it to Sketch

# Acceptance Criteria
- [ ] Remove with UX, product, and CHIP
- [ ] Work with CHIP to get ticket created. CHIP should add this to their messaging source of truth documentation.
