### ISSUE TITLE
Update "Anatomy of a Staging Review Issue ticket" for product labels

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38075]
## User Story
As a VFS team, I want to be able to see how product labels are applied to Staging Review issue tickets so that I can fully understand the issue ticket.

As a Governance team members, I want to make sure the "Anatomy of a Staging Review Issue ticket" guidance is correct and up to date so that I can use it as reference for updating and maintaining the Collaboration Cycle dashboard.

- Intended Audience: VFS teams, Governance team
- Desired Outcome: The "Anatomy of a Staging Review Issue ticket" correctly reflects all labels in use on a Staging Review issue ticket
- Due Date: 

## Description
As we go back and retroactively apply the GitHub product labels to the Staging Review issue tickets from July 2021 onward, we will also need to update the "Anatomy of a Staging Review Issue ticket" guidance on Platform Website, so that VFS teams understand how our labels are applied and used.

The purpose of this ticket is to add a new section titled, "VA.gov Product Labels" and it shall include guidance on how the product label is applied and where the product label list can be found. It should be very similar to how we currently document VFS team labels as seen below:

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/3dabfd63-6008-42cc-80de-f3a749a2408c)

_Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative_

## New Artifacts 
N/A

## Artifacts  Confirmed Needing Updates
[Anatomy of a Staging Review Issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html)

## Tasks
- [x] Add "VA.gov Product Labels" section to [Anatomy of a Staging Review Issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html)
  - [x] Add guidance for how product label is applied
  - [x] Add link to product label list

## Acceptance Criteria
- [x] Anatomy of a Staging Review Issue ticket on Platform Website has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by SarahKay8** [comment]
Hi @shiragoodman 

 @chaseakirby and I drafted this together. Could you review at your earliest? thank you

**Comment by shiragoodman** [comment]
@SarahKay8 I made a small change and now it's ready to be published. Please work 2ith @chaseakirby to publish as we no longer need to publish changes ourselves using Scroll Viewport. Pushes to Platform Website will take place Thursday at 12 pm noon ET

**Comment by SarahKay8** [comment]
@shiragoodman thank you! & will do
