### ISSUE TITLE
VA health connect on VAMC facility pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38077]
## Issue Description
This is a continuation of the work started in #35476. 

## Background
VA health connect, a new phone method for Veterans to communicate with VA health, is being rolled out VISN by VISN. When a VISN rolls out, the region specific number needs to be displayed under Location and contact information on the relevant system, facility, and Locations pages. The number for VA health connect is the same for all facilities within the VISN.  

Main and mental health numbers are data and will continue to be displayed. (not replaced)

This was hardcoded into the front end for VISN 8. Since then, CMS has added a field `field_va_health_connect_phone` to capture this information. This field lives at the system level so to list it for the facility, it has to be retrieved via each  VAMC facility’s `field_region_page`

Following #35476, 

- the hardcoding for VA health connect numbers in VISN 8 had been removed 
- the VA health connect number as defined in `field_va_health_connect_phone` had been successfully added to system and location pages 
- the VA health connect number as defined in `field_va_health_connect_phone` had not been successfully added to individual facility pages. [See comment.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35476#issuecomment-1060875101)

## Tasks

- [ ] Add `field_va_health_connect_phone` to liquid template for individual  VAMC facility’s `field_region_page` 
- [ ] Add the value to the phone number section under Location and contact information, consistent with this format

> Main number: (phone)
> VA health connect: x-xxx-xxx-xxxx (based on field value)
> Mental health: (phone)

## Testing
VA health connect numbers have been populated in the  `field_va_health_connect_phone`  field for VISN 8 facilities. The following locations can be tested:

VA Bay Pines health care (-bay-pines-health-care), including
- North Pinellas VA Clinic (-bay-pines-health-care/locations/palm-harbor-va-clinic)
- St Petersburg VA Clinic (-bay-pines-health-care/locations/st-petersburg-va-clinic) 
- Sarasota VA Clinic (-bay-pines-health-care/locations/sarasota-va-clinic)

VA Orlando health care (-orlando-health-care), including 

- Clermont VA Clinic (-orlando-health-care/locations/clarmont-va-clinic)
- Lake Baldwin VA Clinic (-orlando-health-care/locations/lake-baldwin-va-clinic)
- Tavares Clinic (-orlando-health-care/locations/tavares-va-clinic)

## Acceptance Criteria
Assuming the `field_va_health_connect_phone` has been populated in CMS  
- [ ] Veterans will see the VA health connect phone number displayed within the Locations and contact information section of individual facility pages
- [ ] If the VA health connect number field is null, no label will be displayed. 
- [ ] Main phone number and mental health numbers are still present, whether or not the VA health connect number is present

**Comment by mmiddaugh** [comment]
Validated in [Tugboat](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/)
- West Palm Beach
   - VA health connect shows up on [system main page]https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/west-palm-beach-health-care/)
   - [Locations page](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/west-palm-beach-health-care/locations/)
   - Facility pages like [Port Saint Lucie VA Clinic](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/west-palm-beach-health-care/locations/port-saint-lucie-va-clinic/)
- Validated system, location and facility pages in other VISN 8 health care systems with populated field values: [Orlando](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/orlando-health-care/), [Tampa](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/tampa-health-care/) and [Bay Pines](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/bay-pines-health-care/) health care systems also 
- Validated in [Caribbean health care system](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/caribbean-health-care/) - this is a VISN 8 system which displays VA health connect number using hard coding in [Prod](va.gov/caribbean-health-care/) currently. Field is not populated in CMS so this test validates that the hard coding is removed.  
- Validated in non-VISN 8 health care systems without field values in CMS - expecting no display for VA health connect number. [Memphis](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/memphis-health-care/) and [Battle Creek](https://web-k1ue3sza19nxm4lc7wigg7onepjulwem.demo.cms.va.gov/battle-creek-health-care/) health care systems are behaving as expected. 

🎉 Well done @GcioNapoleon! This can be merged with #35476 on Monday.
