### ISSUE TITLE
Midpoint Review | 1010 EZ | Short Form 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#38070]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

(Listed below)

## Artifacts

Provide links or documents for the following: 

- [x] Product outline
 
- [x] Finalized design prototype or mockup
## Artifacts
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)

## Flow
**NOTE** - please use the prototypes for demo purposes only as they are not final screens, although close.
- [Authenticated clickable prototype](https://preview.uxpin.com/acda277e33e9629a7ab817f6c93c251b4a60ac56#/pages/141488399/simulate/no-panels?mode=i)
- [Unauthenticated clickable prototype](https://preview.uxpin.com/2a1ce93f62d447e101cfce3c803d20941fba7203#/pages/141808810/simulate/no-panels?mode=i)

**Flow charts**
- Authenticated-immediate alert ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/EL9RYvq))
- Authenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgDjqJb))
- Unauthenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dlvDq7j))
- Full application flow/ less than 50% disability rating ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxZzO2l))

## Walk-though of 1010EZ Recording

[here](https://drive.google.com/drive/u/0/folders/16PrClmZOXzlKADP6x9SVB16_Od-c16G6)

## Design
- [Authenticated first alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/px07lr/a/1Kz2Pak/r/2kvkn5)
- Auth & Unauth [accordion alert ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGeGRKd)on every page at top
- Unauth [confirmation page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/YGLwZQO)
- Unauth [Alert of reselection](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nRMkpma) (upon back)
- Unauth [Short form alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bgWPqbz)
- Auth & Unauth [short form review page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbdvz8d)
### Project Overview

- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Research%20Readout_%2010-10EZ%20Short%20form%20usability%20.pdf)

- [x] [Research Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/topline%20summary-%20research%20findings.md)
- [x] [Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Research%20findings.md)
- [x] [Research Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Short%20form%20flow%20research/Research%20Readout_%2010-10EZ%20Short%20form%20usability%20.pdf)

Here are the completed research tickets:

#29089
#29738
#29683
#29684

- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/commit/47cc59fe1085ba97593c50efc2f0a7da6509290a)

### Content artifacts 

- [x] Your product’s content [source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/10-10EZ-application-copy.md)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
Review has been scheduled for March 18th at 2:00 PM ET. Please forward to any other VFS invitees if needed.

**Comment by CherylEvans** [comment]
Requested permissions to view: Walk-though of 1010EZ Recording

**Comment by SKasimow** [comment]
hi @CherylEvans - I am not seeing a permissions settings on this but may just be easier if you go to our vsa 10-10 channel and there you will see the recording is the first pin. Let me know if that doesn't work and I'll spend more time trying to figure out why it's restricting access. Sharon

**Comment by jimuhh** [comment]
No IA feedback at this time. 
Thanks!

**Comment by CherylEvans** [comment]
No Content FB. Appreciate all of the artifacts!

**Comment by claytonzook** [comment]
No research feedback at this time. Thanks for linking the prior research!

**Comment by SKasimow** [comment]
Completed
