### ISSUE TITLE
[Monitoring] Fix loki endpoint syntehtic tests

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#38078]
## Description
Loki endpoint is throwing the occasional synthetic test error and spamming #devops-alerts

Add a buffer in there (something like over the last 10 minutes) to make sure that its not just a flakey failure as they are currently set to alert immediately.

https://dsva.slack.com/archives/C24RH0W11/p1646667973888949

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] add `min_failure_duration` to the `options_list` in https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/loki.yaml for all environments definitions
- [x] apply the terraform

## Acceptance Criteria 
- [x] see that the alert conditions have changed in the datadog UI and the alert is no longer toggling in #devops-alerts

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
