### ISSUE TITLE
[S3]: Create and configure bucket to store 1095-B PDFs

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#38079]
### Team name

1095-B (MO Studio)

### Application name

1095-B

### GitHub repositories

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/1095b-tax-form
- https://github.com/department-of-veterans-affairs/vets-api/tree/1095b

### Product owner

Tracey Mulrooney

### Product manager

Jordan White

### Related issue

https://app.zenhub.com/workspaces/1095b-tax-form-61e19735167b2500170b2146/issues/department-of-veterans-affairs/va.gov-team/37024

### Infrastructure needed

Need access to an s3 prod bucket. Essentially, we're taking data from the enrollment system (a flat file), putting it in this database, and using that to populate/generate the 1095-B PDF.

### Access needed

Nadya.Primak
Teagan.Stephenson
Joshua Faulkner/HEC enrollment system (see this ticket for reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37825#issuecomment-1059458322)

### Tasks 
- [x] Provide examples to team requesting this change 
- [x] Configure resources requested
- [ ] Approve related PRs (if needed)
- [ ] Test functionality (as needed)

### Acceptance Criteria

- [ ] The infrastructure resources requested are working as expected

**Comment by jsgarmon** [comment]
For tracking, this is a follow up to https://github.com/department-of-veterans-affairs/va.gov-team/issues/37391

**Comment by jhouse-solvd** [comment]
@JordanSWhite @nprimak - In the staging and production environments, only applications have access to S3 buckets, not individuals. This is in accordance with the platform's security best practices. 

Typically, this means: 

- Your application needs a service account with credentials to connect to the S3 bucket 
- The service account will be granted read/write access to the S3 bucket 
- The service account can be used by Vets-API (or another application) to interact w/ S3

To help us understand what's needed from the Infrastructure team: 

- Can you link to the application code that will be reading/writing to this bucket? 
- Can you provide an example of this working in the dev environment? 

Also important to know: 

- What is the projected launch date of this service for Veterans? 

cc: @mchelen @jsgarmon

**Comment by ashleycastillo** [comment]
Please see below for answers:

- Can you link to the application code that will be reading/writing to this bucket?
Github branch so far: https://github.com/department-of-veterans-affairs/vets-api/tree/1095b

- Can you provide an example of this working in the dev environment?
We can provide a video or set up time to walk you through it in our dev environment. We also have draft (not finalized) wireframes here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/round2/1095-B%20Prototype_%20User%20testing%20Round2_3.1.2022.pdf

- What is the projected launch date of this service for Veterans?
April 1

**Comment by jhouse-solvd** [comment]
@ashleycastillo - Thanks so much for the additional info. We'll discuss and respond with any questions. We'll get back to you tomorrow (3/8). ☺️ 

cc: @JordanSWhite

**Comment by jhouse-solvd** [comment]
@ashleycastillo & @JordanSWhite 

**Your team needs to configure deployment settings for Vets-API** in the devops repo. We've verified that members of your team can submit pull requests to that repo. 

The settings for Vets-API in dev, staging, and prod can be found in the following location: 
https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/vets-api

**Steps to configure deployment settings:** 
1. Create a new block of code with the deployments settings that your app needs
2. Submit a pull request so that it can be approved by the Infrastructure Team
3. The Infrastructure Team will create parameters that can be accessed by your deployment settings

**Here's an example code snippet:** 
```
<name_of_your_app>:
...
  s3:
    aws_access_key_id: "{{ lookup('aws_ssm_custom', ''/dsva-vagov/vets-api/staging/1095b/aws_access_key_id') }}"
    aws_secret_access_key:"{{ lookup('aws_ssm_custom', '/dsva-vagov/vets-api/staging/1095b/aws_secret_access_key') }}"
    bucket: "{{ lookup('aws_ssm_custom', ''/dsva-vagov/vets-api/staging/1095b/s3_bucket_name') }}"
    enabled: true
    region: 'us-gov-west-1'`
...
```

In the example above, settings are being retrieved by performing a Parameter Store lookup with the AWS Systems Manager (SSM) plugin. There are additional examples for the staging environment in [this file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2).

**Once your PR is approved, you'll be able to test** that the deployment settings are working.

**Comment by jsgarmon** [comment]
@jhouse-solvd : I've modified your code snippet above to make use of the standard `vetsgov-s3-upload-*` user that components tend to use. I don't think creating a new service account is needed, since this user has no explicit permissions, but can access buckets that have bucket policies that allow it.

From the application side, you'll need to make sure you are using the correct credentials by calling the settings file, similar to [the vba_documents code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules%2Fvba_documents%2Flib%2Fvba_documents%2Fobject_store.rb).

**Comment by jsgarmon** [comment]
For tracking, had a conversation with Josh Faulkner yesterday, and I think the need here is simple: they just need the role `arn:aws-us-gov:iam::397582302769:role/project/project-IAMrole-S3-VES` to have read-write access. Note this is a role from a separate AWS account. We tested yesterday and verified their EC2 instance running in vaec-ves can right to the dev bucket.

**Comment by jsgarmon** [comment]
Two buckets now exist that are open to the role above:
- dsva-vagov-dev-1095b-form-uploads
- dsva-vagov-prod-1095b-form-uploads

This should be all that's needed from the DSVA AWS side.

**Comment by khandelwal** [comment]
Hi, we finally got around to testing access in production for Joshua Faulkner, and it looks like the role does not have the correct access to the production bucket. 

$ aws s3 cp test.txt s3://dsva-vagov-prod-1095b-form-uploads/test.txt

upload failed: ./test.txt to s3://dsva-vagov-prod-1095b-form-uploads/test.txt An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

We think the policy on the production bucket needs to be updated.

**Comment by jbritt1** [comment]
This is resolved, confirmed with Joshua Faulkner via Slack huddle. This is a screenshot from his end uploading a `test.txt` file to the prod s3 bucket:

![image](https://user-images.githubusercontent.com/56260532/184008624-1a861855-b045-4ea3-a0c4-14117c824e5e.png)

**Comment by jbritt1** [comment]
Resolution note: the resource ARN for the prod s3 bucket needed to be added to the permission set of the `arn:aws-us-gov:iam::397582302769:role/project/project-IAMrole-S3-VES` role.
