### ISSUE TITLE
Conduct Research: HRT Static Landing Page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38081]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

## Tasks 
- [x] Print conversation guide
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Post debrief/updates on slack
- [x] Debrief research sessions into note-taking spreadsheet
- [x] Download recordings
- [x] Download notes from Perigean
- [x] Download final participant list from Perigean
- [x] Change display name of Perigean Zoom account back to what it was
- [x] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Conducted 1st 3 sessions of 15 scheduled

**Comment by cindymerrill** [comment]
Completed all research sessions today
