### ISSUE TITLE
[Frontend Development] Create Transitional Document: Public Websites Team

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38093]
## Issue Description
The purpose of this transition document is to outline the current state of Public Websites projects . It serves as a "front door" to documentation and resources collected during the course of product design, research and development. Included are links to more specific transition hubs where you can find direct links to resources and references used during design and development.

## Tasks
- [ ] Create Github doc about what static pages: [Development Artifact ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Transition%20Documentation/Development%20Transition%20Doc.md)
- [ ] Ensure document can be reviewed on team repo
- [ ] Review with team as part of the transition plan

## Acceptance Criteria
- [ ] Github doc on research projects and support are available as part of the transition effort
