### ISSUE TITLE
[Research] Create Transitional Document: Public Websites Team 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38091]
## Issue Description
The purpose of this transition document is to outline the current state of Public Websites projects . It serves as a "front door" to documentation and resources collected during the course of product design, research and development. Included are links to more specific transition hubs where you can find direct links to resources and references used during design and development.

## Tasks
- [ ] Create Github doc about what static pages: [Feature Artifact ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Transition%20Documentation/Feature%20Transition%20Doc.md)
- [ ] Ensure document can be reviewed on team repo
- [ ] Review with team as part of the transition plan

## Acceptance Criteria
- [ ] Github doc on research projects and support are available as part of the transition effort

**Comment by cindymerrill** [comment]
@leahkeeler I haven't added in any research links yet, which I plan to do later today after I deliver my harassment research report

**Comment by cindymerrill** [comment]
Where is the transition document that I should add my research links into? @leahkeeler @longmd

**Comment by cindymerrill** [comment]
@longmd shared it with me: https://github.com/department-of-veterans-affairs/va.gov-team/blob/56eb6d051f4d8aafa0289eb7392f7125e0abda0a/teams/vsa/teams/public-websites/Transition%20Documentation/Product%20Transition%20Doc.md

I'll add in my research links now...

**Comment by cindymerrill** [comment]
I've added in my research and design links, so now I'm done! @leahkeeler
