### ISSUE TITLE
Resolve race condition in AuthApp between recordEvent and Redirect

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#38103]
## Issue Description
We are seeing really low numbers of success events when utilizing the USiP for MHV. I think this is not due to auth errors, but rather a race condition that has the user leaving the page before the success event is fully parsed and delivered.

It looks like `window.dataLayer.push` provides us with a callback option that we can utilize to ensure the event is finished delivering before we redirect the user to the external application

## Tasks
- [ ] Implement the callback method for `dataLayer.push` and move the redirect logic into the callback where applicable

## Acceptance Criteria
- [ ] Utilize the dataLayer callback method to ensure user is not redirected before event delivery
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
