### ISSUE TITLE
[Design]10-10CG - Primary/Secondary Caregiver clarification:  Discovery on opportunities

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#38119]
## Background
Over the last 2 years, there has been sporadic feedback reflecting confusion on how to complete the 10-10CG, specifically around the differences between the Primary and Secondary caregiver roles, responsibilities and benefits.
Currently, the form only lists who would be eligible to be a caregiver, but does not provide much guidance on anything else.
Also, we have come to learn of a scenario that causes duplicative efforts for both CSP and the Veteran/Caregiver applicants:
- **Example**: A Veteran wants to add a secondary caregiver.  They complete the application, but includes the existing Primary caregiver in the Primary section, and adds the new Secondary caregiver in the Secondary section.  Because the Primary already exists, this information being on the application causes it to be considered a "Duplicate".  The CSP has to review, and most times, has to contact the Veteran to reapply without the Primary caregiver's information.  

We need to determine the best way to inform applicants of the roles, and provide better guidance on how to complete the form (new or making changes).  This should be a collaboration between Design and Engineers.

### Reference
- [Product Review Deck](https://docs.google.com/presentation/d/1BFVxhVI2gQIJx9xvCAKZi1LbzfDDifC6VcaN13iGOac/edit#slide=id.g33cc3b02a5_0_49)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Primary%20vs%20Secondary%20Clarification)
- #35838 - Discovery
- #22372 - Initial designs (pre-design intent) Note: A few different designs ([Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/15WML8/p/79BDE8AC-21C9-4FEF-B0FB-DA6E0C3990DD)) have been prepared with the intention to be shown at design intent. 

#### Notes on Sketch file (From Dene'):
- V6 is a new, progressive flow depending on if applicant is new to the program or returning to change/add a caregiver (this is my current recommendation) 
- V5 includes the idea of a chart, but if a chart is created, it should likely live on a content page (must consult accessibility) 
- Other versions are intended to give options of elements and content

## Tasks
- [x] Review Reference sources
- [x] Consider opportunities and solutions that will inform, but not overwhelm
- [x] Meet with the team to discuss opportunities

## Acceptance Criteria
- Team will discuss some opportunities to resolve the problem of confusion, uncertainty and duplicative processes

**Comment by davidakennedy** [comment]
Leaving some notes for myself, after talking with the team yesterday:

Two problems:

1. Users are unclear what the Primary and Secondary caregiver roles, responsibilities and benefits are when progressing through the form.
2. In some instances where a person updates the primary or secondary caregiver, they include both, leading to duplicative information.

Questions:

1. Do we need to approach the problems separately?
2. What other opportunities and solutions might exist beyond the previous work done?
3. What questions are we missing?

**Comment by davidakennedy** [comment]
I have a [working doc going in one of our research folders](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Primary%20vs%20Secondary%20Clarification/Discovery_Research/Primary/primary-secondary-caregiver-clarification-opporunities.md) with the work done so far.

**Comment by hdjustice** [comment]
My Thoughts:

> How do we know it's a problem?
>-  Sporadic feedback reflecting confusion on how to complete the 10-10CG, specifically around the differences between the Primary and Secondary caregiver roles, responsibilities and benefits.
> - Feedback from stakeholders that data

The 2nd point seems unfinished?

>Better understanding the user's mental model on the caregiver levels/names : Do Veterans/Caregivers refer to the Primary / Secondary terms or do they think about the caregivers collectively as a team supporting the Veteran? Is the primary/secondary terms more of a program/business requirement?

I LOVE that we are asking this question.  It is common terminology all over www.caregiver.va.gov, but understanding how the Veteran and CGs refer to this process/role would be awesome.

This is a great outline, it confirms a lot of what we have considered and read about in past research.  I haven't witnessed research with the intended audience for this form yet, so I am excited to hear more!

**Comment by jessicastump** [comment]
Thoughts after reviewing the working doc below.

- Side note: content out of order? ideas 4 and 5 should be listed before “what questions are we missing?”

## 

This work really could benefit from some additional exploratory research -

1. Interviews with dyads (Veteran / Caregiver pair) to explore all of these possible directions by asking questions and maybe review content examples 
2. Timing for overall usability/facilities study so we can use those findings to build off of here

## 

> Idea Five: Store Caregiver information in the profile section

Additional questions:
- Would the Veteran have to complete their information on the application still if going this route? 
- Would this be populated since they are authenticated or would it still be manual entry?
- Or would this be a progressive flow in that this can be filled behind the scenes? 
- What about Veteran signing?

## 

Should add below to doc for reference: found at https://www.caregiver.va.gov/support/support_benefits.asp

> What services does this program offer?
> Veterans can designate one (1) Primary Family Caregiver and up to two (2) Secondary Family Caregivers on the application. Secondary Family Caregivers serve as a backup support to the Primary Family Caregiver when needed. Services will depend on whether you are the Primary Family Caregiver or a Secondary Family Caregiver.

> If you are the primary caregiver, you may receive:
> 	•	A monthly stipend (paid directly to you as the caregiver.)
> 	•	Access to health care insurance through Civilian Health and Medical Program of the Department of Veterans Affairs ([CHAMPVA](https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/index.asp)), if you do not already have health insurance.
> 	•	Mental health counseling.
> 	•	Certain beneficiary travel benefits when traveling with the Veteran to appointments. For specific details, please contact your CSP Team.
> 	•	At least 30 days of respite care per year, for the Veteran. Respite is short term relief for someone else to care for the Veteran while you take a break.

> If you are the secondary caregiver, you may receive:
> 	•	Mental health counseling.
> 	•	Certain [beneficiary travel benefits](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) when traveling with the Veteran to appointments. For specific details, please contact your local [CSP Team](https://www.caregiver.va.gov/support/New_CSC_Page.asp).

**Comment by hdjustice** [comment]
Building on Jessica's mention about Idea 5:
- We did learn that an authenticated flow presents a unique challenge in that only the signed in person can digitally 'sign' the application.  This was reviewed by the legal team prior to launch.  
- We also know that if the Veteran was logged in and signed, that Caregiver signatures would still need to be obtained, probably by paper form.  So it doesn't save time, and could potentially introduce complications/frustrations.

**Comment by hdjustice** [comment]
FYI @davidakennedy - here is a screenshot from Domo showing the preceding pages to the application from the past year to date.  I am going to check that top page to see what leads into that.
![image](https://user-images.githubusercontent.com/92328831/225982364-96f5b4f6-0b60-4a54-b5c8-a53a15735c9c.png)

**Comment by hdjustice** [comment]
This is a snapshot of the most accessed previous and next pages for the [page right before our intro page](https://staging.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/)

![image](https://user-images.githubusercontent.com/92328831/225984373-6eb7715e-a00c-4b06-8a7c-c1e85a610926.png)

**Comment by davidakennedy** [comment]
> The 2nd point seems unfinished?

@hdjustice Thanks for catching this! I think I accidentally deleted that text or didn't come back and finish the thought. Fixed now.

**Comment by davidakennedy** [comment]
@jessicastump 

> Side note: content out of order? ideas 4 and 5 should be listed before “what questions are we missing?”

Fixed this, thank you!

> This work really could benefit from some additional exploratory research

Added these to the bottom of the doc.

> Additional questions for idea five

Added these to that idea.

> Should add below to doc for reference

Yes! Added to the bottom of the doc as well.

**Comment by davidakennedy** [comment]
@hdjustice I added your two additional traffic screenshots to the doc.

**Comment by davidakennedy** [comment]
I wanted to follow up here and button up this ticket with next steps:

* In our meeting, the team agreed that exploring the ["one page with the question on the next"](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Primary%20vs%20Secondary%20Clarification/Discovery_Research/Primary/primary-secondary-caregiver-clarification-opporunities.md#idea-full-page-of-info-with-question-on-next-page) recommendation was the right place to start. This puts the information that Veterans haven't understood up front without hiding it in other components.
* The [new, progressive flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Primary%20vs%20Secondary%20Clarification/Discovery_Research/Primary/primary-secondary-caregiver-clarification-opporunities.md#idea-new-progressive-flow-depending-on-if-applicant-is-new-to-the-program-or-returning-to-changeadd-a-caregiver) feels like a good phase two after exploring content in the one page concept.
* Exploring how surfacing primary/secondary caregiver information in the profile might work could be a good phase three, but there are a lot of questions to answer there.
* Next steps: Create a ticket to explore visual concepts for the one page with the question on the next approach.
