### ISSUE TITLE
[EKS] New approach to preserving client IP in kubernetes

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#38120]
## Description

In a previous attempt to preserve client IP addresses in kubernetes, we had taken the approach of setting `externalTrafficPolicy: Local` https://github.com/department-of-veterans-affairs/va.gov-team/issues/37932

The problem with this is that it fundamentally breaks the way we have set up and designed traefik as an ingress controller.  This is because by setting this configuration it changes the network is handled which can be seen by the following.

With `externalTrafficPolicy: Cluster` the following flow will happen.  It hits traefik on a node, and if the pod does not exist on said node, the request will be forwarded to the next (repeat until pod is found) however the forwarded for IP is obfuscated by SNAT which would result in it being replaced by a worker node IP
![image](https://user-images.githubusercontent.com/76792875/157132598-4a973065-c123-4ca7-af1f-2c074c87f46e.png)

With `externalTrafficPolicy: Local` the following flow will happen.  It will hit traefik on a node, and if the pod doesn't exist on this node the request will be dropped.  This can result in multiple requests to the wrong node subsequently and throw a 504 error.
![image](https://user-images.githubusercontent.com/76792875/157133151-680ddcbf-d06a-4df8-8247-dd964e267c45.png)

The next proposed solution is to try and use the Traefik Real IP plugin (https://pilot.traefik.io/plugins/605afbb0a5f67ab9a1b0e520/traefik-real-ip)

In order to accomplish this we need to be on traefik version 2.5 or greater and then manually build said plugin into our docker build.

https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/

---
## Tasks
- [x] Update traefik by making the needed changes in https://github.com/department-of-veterans-affairs/vsp-infra-traefik (will likely require a update to the helm chart version as well)
- [x] Deploy to dev
- [x] If upgrade to traefik goes smoothly, add plugin to docker build following the documentation
- [x] Make needed configuration changes in dev to enable the plugin and test using the middleware on a ingressRoute (probably vets-api)

## Acceptance Criteria 
- [ ] Go to dev-api.va.gov with the required header
- [ ] Should be able to see your IP address in vets-api logs https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-5m%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%22%7D%5D

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
![image](https://user-images.githubusercontent.com/76792875/157351025-f148bcab-d77e-4002-a13a-1ae145bc6b7b.png)

traefik has been updated on all clusters to the latest 2.6.1

**Comment by mleclerc00** [comment]
Running traefik as a daemonset in combination with `externalTrafficPolicy: Local` seems to be the solution we needed all along.  I have this rolled out to dev in order to test vets-api logs (which always shows the client IP now) and utility in order to test issues we were seeing with argo/sentry/grafana when traefik was the type `deployment` and  `externalTrafficPolicy: Local` was set.

**Comment by mleclerc00** [comment]
Traefik is now deployed as a daemonset in all clusters, just looking to clean up a couple more things before calling this complete

- split out values.yaml and chart.yaml into individual folders within the manifests repo for better separation of environments
- clean up github actions and fix to align with the previous bullet point

**Comment by mleclerc00** [comment]
Created a new ticket for the above https://github.com/department-of-veterans-affairs/va.gov-team/issues/38643

moving this to review
