### ISSUE TITLE
[Design] - Auth Profile - Personal Information Revision - Finalize Copy in Mockups

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38126]
## Background

There are a few outstanding copy-related items to be  updated in the mockups once we know whether MPI can support a delete/remove button.  

## Tasks
- [x] Determine if "first" should be added to preferred name based on user feedback.
- [x]  Update language around "If not listed, please provide your ___" based on Danielle's recommendations
- [x] Make it clear all of these fields are optional: delete/remove button or in hint text. 
- [x]  In read-only state, the commas between values should be changed to semicolons. -- see screen shot below.
- [x] Update language around "(unchecks other boxes)" and additional multi-select instructions based on Danielle's recommendations
- [x] If remove/delete button is feasible, work with Content on what the button should say.
- [x] If remove/delete button is NOT feasible, remove from all Personal Info Revision mockups.
- [x] Add a link to a Resources & Support page that provides more detailed info
- [ ] All updates have been reviewed by Christina/Danielle/Marci/Samara

![image](https://user-images.githubusercontent.com/73354907/157240427-2100ef20-81f7-4b5a-9a48-b1a2d1105737.png)

## Acceptance Criteria
- [x] Determine if "first" should be added to preferred name based on user feedback.
- [x]  Update language around "If not listed, please provide your ___" based on Danielle's recommendations
- [x] Make it clear all of these fields are optional: delete/remove button or in hint text. 
- [x]  In read-only state, the commas between values should be changed to semicolons. -- see screen shot below.
- [x] Update language around "(unchecks other boxes)" and additional multi-select instructions based on Danielle's recommendations
- [x] If remove/delete button is feasible, work with Content on what the button should say.
- [x] If remove/delete button is NOT feasible, remove from all Personal Info Revision mockups.
- [ ] Add a link to a Resources & Support page that provides more detailed info
- [ ] All updates have been reviewed by Christina/Danielle/Marci/Samara

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske - I've rolled all copy-related changes into this ticket. Please review and estimate prior to Sprint Planning tomorrow.  Thank you!

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I've put my best guess estimate on this at a 3. Hope that's fairly accurate, but as it's still blocked I'm not sure how much back and forth will be needed.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! Looking at the two different content requests blocking this ticket, I don't think the second one ([Content Request from Auth-Profile team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34247)) is actually blocking this. Should it be [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36862) instead (the few remaining Personal info changes)?

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske you are correct.  I'll update that.   Thank you for catching that.

**Comment by cgednalske** [comment]
Note that mockups have been updated to include content changes and radio buttons in Gender Identity field. ([Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/PGvO0yW) and [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/Gm5g1OD) Sketch files)

We are currently waiting on confirmation for if and where the Remove button can be included, as well as if a text input field can also be added to Gender identity. 

The R&S article will not be added at this time as Danielle and Samara discuss if/how to include that info.

**Comment by MarciMcGuireGCIO** [comment]
Fantastic! Thank you, @cgednalske! Cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Sounds good! Sounds like the remove/delete button is the last thing in question. We're so close to being done!

**Comment by MarciMcGuireGCIO** [comment]
Moving to next sprint;  waiting on spec from VA Profile to confirm UI

**Comment by cgednalske** [comment]
Personal info mockups have been updated to no longer include the Remove button - [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2) and [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/KvxAd9y) Sketch Files - just need to check with Danielle on remaining language questions around fields being optional.

**Comment by MarciMcGuireGCIO** [comment]
Thanks! Looks great, @cgednalske ! 

cc @Samara-Strauss

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @MarciMcGuireGCIO! In @DanielleThierryUSDSVA's office hours today, we talked through the additional info component text in Gender identity and Sexual orientation, and how to help convey the optional nature of the fields now that we don't have the Remove button. 

We landed on changing the text to _What to know before you decide to share your gender identity_, with the addition of "decide to" accentuating that this is a choice. Here are links to the [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2) and [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/KvxAd9y) Sketch files showing those changes. 

Let me know your thoughts and if you feel this will work! After this, I believe we've addressed all Personal information content changes 🎉

**Comment by Samara-Strauss** [comment]
This sounds good to me! Can we more explicitly say this is optional within the FAQ text as well?

**Comment by MarciMcGuireGCIO** [comment]
Somehow I missed this yesterday.  I agree -- that seems completely logical!  Mockups look great!

**Comment by cgednalske** [comment]
Great! @Samara-Strauss @MarciMcGuireGCIO  Below is the text we currently have within the FAQ - do you feel this is clear enough or still in need of something more direct?

Also want to note that - without the R&S article - we don't have anything in this text that clarifies why we ask for Gender identity and Sexual orientation. Double checking we are ok with no mention of that at this point? Here is the link to this [full page mockup](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/AxMjM3y) for reference.

<img width="696" alt="Screen Shot 2022-04-01 at 8 24 49 AM" src="https://user-images.githubusercontent.com/79372956/161294235-b078432b-039f-48d7-813c-85afd8dabb17.png">

**Comment by Samara-Strauss** [comment]
How do we feel about adding something like "Sharing your gender identity with the VA is optional. If you decided to share your gender identity, you should know that we follow strict security..." Something like this would, of course, need to be approved by @DanielleThierryUSDSVA since I do not have the final say on content. I'm also open to not including that if people feel it is too heavy handed.

**Comment by MarciMcGuireGCIO** [comment]
Based on the feedback we got during the research sessions, anything to ease people's anxiety about sharing this info is probably helpful.

**Comment by cgednalske** [comment]
Pending the decision on adding the information above into the dropdown, here are the links for our updated mockups - [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/KvxAd9y)

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA! Do you have any thoughts on including something like Samara's suggestion below in the dropdown to make it extra clear this is optional? We are all ok with going either way, but are wondering if it's helpful to explicitly state this for these more delicate fields. Thanks so much! 

**Suggested addition:**
"Sharing your gender identity with the VA is optional. If you decide to share your gender identity, you should know that we follow strict security..."

**Current text:**
"We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information. 
If you want to share your gender identity in your health records only, talk with your health care team."

**Comment by DanielleThierryUSDSVA** [comment]
Hi @cgednalske! I definitely think it's good to reiterate optional. And I think it's good to share the "why we ask" too. We'd actually had that content as hint text in an earlier version and talked about moving it into the additional info component because hint text was too long. What do you think about adding that back in here?

Here's how it would read:

If you get health care at VA, this information can help your care team better assess your health needs and risks. But you don’t have to share this information in your VA.gov profile. 

We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information.
If you want to share your gender identity in your health records only, talk with your health care team.

**Comment by Samara-Strauss** [comment]
@DanielleThierryUSDSVA I keep re-reading this copy and feel like there is a disconnect between the main idea we are trying to convey in the first and second paragraphs (ie. sharing this is optional, but if you do share it, know that all VA administrations will have access to it), so I wanted to see if you'd be open a slight re-organization of the current draft (below). I tried to keep most of your verbiage as-is and just shuffle things around, so let me know your honest thoughts, or if you'd prefer to go with the original draft:

Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information.

We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.

**Comment by DanielleThierryUSDSVA** [comment]
@Samara-Strauss I **love** it! I think the shifting of the content order works really well and adds clarity. Thank you!!

**Comment by cgednalske** [comment]
🎉  @Samara-Strauss and @DanielleThierryUSDSVA Wonderful! This looks perfect. Thank you both!! 

Here are the revised mockups for the designs!

**All mockups for Personal information**
[Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2) and [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/KvxAd9y) for all fields
[Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlVxdm3) and [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ZODxr23) for initial fields


**Specifically Gender identity - Expanded Info**
[Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/AxMjM3y) and [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/jgEdDkG) for all fields
[Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/eKYxzDm) and [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/GmRgk3O) for initial fields

**Comment by Samara-Strauss** [comment]
Thanks, @cgednalske! This is a lot of copy, but it's not so bad when the FAQ is collapsed. I think this is good to close.
