### ISSUE TITLE
Lovell federal health design iteration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38122]
## Issue description
The Captain James A. Lovell Federal Health Care Center has a combined mission to serve active duty military, their family members, military retirees and Veterans. The center also cares for an estimated 40,000 Navy recruits who prepare for military service at Recruit Training Command at Naval Station Great Lakes.

Primary question to solve - as a DoD or VA person, can I complete my top tasks and identify the information which is relevant to me.

<details>
<summary> Dual eligible info from email 3/7/22 (Nickolas Sanchez) </summary>

Q: We understood that some individuals (such as retired military personnel) have access to both DoD/Tricare and VA benefits and can choose which one to use, depending on the scenario.  

> A: True. They must choose a benefit and once they choose either VA or DoD, they must complete that episode of care using one benefit.  They will not be allowed to go back and forth from VA to DoD or DoD to VA.  Example:  If they chose a VA ortho surgeon using a referral to the network, they must also utilize that VA pharmacy, physical therapy, prosthetics until that episode of care has been completed. From Nick: My understanding is the patients choose which benefits they want to use when scheduling their primary care appointments, and continue down that path with all referrals and prescriptions that follow.

Q: Which facilities serve the dual eligible population? We assume Captain James A. Lovell Federal Health Care Center, Kenosha, McHenry and Evanston VA Clinics, and the Zachary and Elizabeth Fisher Medical and Dental Clinic. Any others?  

> A: Again this depends on which benefit they have chosen.  However, any clinic in RTC or NTC Recruit or Navy Training Commands are for active duty only.  All VA hospitals outside of JALFHCC are considered TRICARE network and will require a NON-MTF Referral in order for TRICARE beneficiaries to receive care if a dual beneficiary choses to use their TRICARE benefits.  From Nick: My understanding of this, is that dual eligible patients would only be seen at the main facility. Fisher, Tranquility, Red Rover, and Osborne are only seeing Active-Duty patients, and the CBOCs in Kenosha, Evanston, and McHenry are only seeing VA patients.

Q: For which tasks is dual eligibility relevant? Consider a scenario where an individual is viewing pages from the Veteran perspective. At which points might they need to view DoD/Tricare details? (or vice versa)

> A: Again this depends on the episode of care and which benefit they chose.  If they have a PCM that is TRICARE in the Medical Home Port most likely they will be utilizing their TRICARE benefits and TRICARE On-Line TRICAREonline.com for messaging and viewing of records.  Under the current TRICARE contract our Managed Care Support Contractor is Humana Military 1-800-444-5445.  [www.HumanaMilitary.com](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.humanamilitary.com%2F&data=04%7C01%7C%7C38d5cba72b3640e10ee508da0054a0d2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822660707445168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rFJOvOLI1LK4KMaDAC6OKf2iJxgomwEZNO08nLcJKjA%3D&reserved=0)

I have included the dual beneficiary enclosure page 3
> 
>  c. Dual Eligibility. Some TRICARE beneficiaries may be eligible for both VA and TRICARE benefits: (1) If a dual-eligible beneficiary is seeking care for a service-connected condition in a VA HCF, the beneficiary must receive care using their Veteran benefit. VA must not bill TRICARE for treatment of a service-connected condition.
> 
> (2) If a dual-eligible beneficiary is seeking care for a nonservice-connected condition in a VA HCF, the beneficiary may elect to receive that care under either the Veteran’s benefits or TRICARE benefits for that episode of care.
> 
> (3) For Reserve Component Service Members serving on orders to active duty for greater than 30 days, DoD eligibility will take precedence over VA eligibility for care and all applicable TRICARE rules will apply.
> 
> (4) During the enrollment (registration) process, VA HCF staff must inform dual-eligible beneficiaries that it is the dual-eligible beneficiary’s responsibility, at each episode of care, to identify which benefit (VA or TRICARE) they intend to use. Non- Medical Care Collections Fund (MCCF) Coordinators or designee must counsel the dual-eligible beneficiary prior to care being received. NOTE: TRICARE Policy and Procedure Guide “VA-TRICARE” Information on Dual Eligible Beneficiaries, can be found at: [https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001031/content/554400000050841/Chapter](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvaww.vrm.km.va.gov%2Fsystem%2Ftemplates%2Fselfservice%2Fva_kanew%2Fhelp%2Fagent%2Flocale%2Fen-US%2Fportal%2F554400000001031%2Fcontent%2F554400000050841%2FChapter&data=04%7C01%7C%7C38d5cba72b3640e10ee508da0054a0d2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822660707445168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hT2ZdwbbzbpwfxjybW0rlkYky6Kz6mDCV3VzMWwKQCk%3D&reserved=0) 1. Job aids are also available on the eBusiness eRevenue Resources SharePoint site, available at: [https://vaww.vashare.vha.va.gov/sites/eRevenueResources/Pages/Non-MCCF](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvaww.vashare.vha.va.gov%2Fsites%2FeRevenueResources%2FPages%2FNon-MCCF&data=04%7C01%7C%7C38d5cba72b3640e10ee508da0054a0d2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637822660707445168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uN4bGlElE%2FpuZhLnCuGof6lcoo3c8jORexESN1yGkJU%3D&reserved=0) Roles.aspx. NOTE: These are internal VA Web sites that are not available to the public.

</details>

## Tasks
 - [ ] Incorporate feedback and input from Lovell SMEs and stakeholders
 - [ ] Incorporate IA feedback from Mikki
 - [ ] Incorporate other design feedback

## Acceptance Criteria
- [ ] UX pin design includes most up to date design recommendations 
- [ ] Open questions and next steps are well documented
