### ISSUE TITLE
[Design] - Auth Profile - Bad Address Indicator- Component Discovery/Incorporate Design Intent feedback

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38139]
## Background
Following the Design Intent meeting, work with Content/IA/Accessibility on UI revisions based on feedback.

@cgednalske - Linking to the feedback from the Design Intent review held yesterday.

- [Design Intent Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38727) 

- [Design Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38886)
- [Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38905)
- [Content & IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38922)

## Tasks
- [ ] Create Content request if needed
- [x] Work with Content on updated copy
- [x] Work with IA on adjustments to user flow
- [x] Work with Accessibility on any issues that need to be addressed
- [x] Update mockups based on above conversations

## Acceptance Criteria
- [ ] Create Content request if needed
- [x] Work with Content on updated copy
- [x] Work with IA on adjustments to user flow
- [x] Work with Accessibility on any issues that need to be addressed
- [x] Update mockups based on above conversations

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske based on the feedback we got yesterday, is 3 still a good estimate for this work?

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO I'd say that's still seems pretty accurate!

**Comment by cgednalske** [comment]
@Samara-Strauss Here are the current Sketch mockups for [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/DPl7w4k) and [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/dlVojr9). Once the content is reviewed (and updated if needed), this ticket can be closed.

**Comment by Samara-Strauss** [comment]
@cgednalske I'm going to move this to sprint 71. Let me know if we can actually close this out instead, but if you're waiting to close out until after a content review (which is fine), we might as well leave this open.

**Comment by cgednalske** [comment]
@Samara-Strauss sounds good 👍 I haven't heard back yet but will let you know when I do. Danielle is mostly reviewing the link in the Personal information alert - changed slightly because Mikki suggested more clearly indicating that the link leads to Contact information page - but she had also wanted to take another look at the mockups overall.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- Here are the links to the Bad address indicator mockups ([Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/DPl7w4k) & [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/dlVojr9))  with the updated content/IA. These start at the Personal information alert, and you can arrow right to see Contact information and error/success states.

Once Danielle has a chance to confirm, this ticket will be complete.

**Comment by SKasimow** [comment]
Hi - @cgednalske @Samara-Strauss question re: the text "If you need to change your address, select Edit. If your address is correct, select Update to confirm". 

I can't tell from the mocks but looks like the user will need to select Edit and then Update to confirm their address is correct. If so, this may be a little nit-picky but wondering if this is intuitive?

**Comment by Samara-Strauss** [comment]
> looks like the user will need to select Edit and then Update to confirm their address is correct

Yes, that's correct. @SKasimow Christina still needs to review the copy with Danielle, so we can see what Danielle has to say about that and further refine the copy from there.

**Comment by cgednalske** [comment]
>  for the successful save and error states, we should use whatever save/error styling we have now in the profile. The styling in the mocks looks like updated styling matching Liz's warning alert (dark vertical line + bold text w/ highlight), but as far as I know, we don't use that pattern for successes/errors (no dark vertical line, just the text highlight, text is not bolded as far as I know). 

@Samara-Strauss Liz's input component does have error and success states set as well that I believe are applied to the Notifications setting page (here's the [Sketch file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P4QlQn) showing the pattern). For consistency with that pattern, the current design uses that error pattern with our usual error text incorporated. 

Definitely see what you mean with this being different than our usual alerts though. Switching back to the normal alerts for error and success but not the warning would stray from the Liz/input pattern, but indeed might better incorporate it into the overall page since, unlike Notification settings, it's the only situation we're using it for. 

But also - if we resort to the usual alerts, is it worth revisiting if the Liz/input component is still best for the warning alert as well?

**Comment by Samara-Strauss** [comment]
@cgednalske thank you so much for all of this background! It is really helpful, and I really appreciate you filling me in. I definitely was not aware that we were using the "Liz" styling for all states in notification settings, but I am glad we are.

> Definitely see what you mean with this being different than our usual alerts though, particularly since on Contact information we're only using the Liz/input component for BAI, unlike Notification settings where it's used throughout. 

Based on this, I am thinking we should only use the Liz input for the alert and use the standard save/error styling for everything else given that that's what we are already using throughout contact information. I'm mostly thinking of this from a code perspective -- I want Adam to have to customize as little as possible. However, we should probably revisit this styling in a separate engagement to determine if we want to or should move to the Liz styling for everything in this section.

What do you think? I am happy to chat if you feel we need to talk this through, so just let me know.

**Comment by cgednalske** [comment]
@Samara-Strauss Here's the [Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1649881541962/008982baf77ae3158ac14ebbfa8cd9e091ee52e1?sender=u28f508d646c449cc1afe4873) with the different alert options discussed today!

I was also able to touch base with Danielle to finesse the instructions above for updating vs. confirming. 🎉  Thank you @SKasimow for bringing that up - definitely helped us to hear from someone with fresh eyes!

Here's the new text I'll add in tomorrow: "To change or confirm your address, select Edit. Once you've changed your address, or if it's already correct, select Update to confirm."

**Comment by Samara-Strauss** [comment]
@cgednalske I think all of these options work from a visual/UX perspective, so that's great. Given that the UX is sound on all of them, I'd probably choose the last one, as I assume that would be easiest from a code perspective. What do you think?

> "To change or confirm your address, select Edit. Once you've changed your address, or if it's already correct, select Update to confirm."

This copy is great!

**Comment by cgednalske** [comment]
@Samara-Strauss I agree. Though it would be great to move the Liz/input component forward, this may not be the place. If we're using some of the standard alerts, it does seem like it makes most sense to use them all. There's also the inline error component already in place in forms (below) to consider, another reason why this might not be the right place to stray from the standard alerts.

<img width="344" alt="Screen Shot 2022-04-14 at 10 57 57 AM" src="https://user-images.githubusercontent.com/79372956/163449565-d976c1da-89cb-4287-8f6b-147b8c2ade61.png">

I know we have questions about how we might incorporate the use of that component in the long run, and I also think that it'd be very helpful to clearly define our various alerts and what they're best used for. I'd love to make that a longer term background project to work on going off of Liz's earlier audit work.

**Comment by Samara-Strauss** [comment]
> There's also the inline error component already in place in forms (below) to consider, another reason why this might not be the right place to stray from the standard alerts.

This is a really good point. Let's stick with the standard alerts for now!

**Comment by cgednalske** [comment]
Here are the finished mockups ([desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/DPl7w4k) and [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/dlVojr9)) with the new content and design changes. Also noting that we likely won't be able to keep the warning alert in the edit state because our usual alert pattern also places the error alert within the same field. I've removed it for now but will double check.

**Comment by SKasimow** [comment]
@Samara-Strauss I will close and put a note on the Sprint 72 epic for @Christina to update the error state for the full fidelity mocks.

**Comment by cgednalske** [comment]
@Samara-Strauss and @SKasimow this is updated in the mid-fi mockups!
