### ISSUE TITLE
[Design] - Auth Profile - Bad Address Indicator - Attend Design Intent

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38138]
## Background
Design intent meeting to review mockups and get feedback for iterating on design

## Tasks
- [x] Attend design intent meeting
- [x] Note feedback from meeting
- [ ] Review feedback in GitHub following meeting

## Acceptance Criteria
- [x] Attend design intent meeting
- [x] Note feedback from meeting
- [ ] Review feedback in GitHub following meeting

**Comment by cgednalske** [comment]
Linking to the [Design Intent notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/meeting-notes/design-intent-2022-03-22.md) from @MarciMcGuireGCIO
