### ISSUE TITLE
[PM] - Auth Profile - Bad Address Indicator -  Determine VANotify dependencies, timeline

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38135]
## Background
We will use VA Notify to send an initial email blast to direct Veterans whose addresses have been flagged as invalid to update their address on VA.gov.  We will also have event-driven emails that will send an email to any new Veterans whose addresses have been flagged as invalid.

## Tasks
- [x] Determine VANotify dependencies & lead time for initial email blast
- [x] Detemine VANotify dependencies for event-driven emails when a new Bad Address Indicator is added.

## Acceptance Criteria
- [ ] Determine VANotify dependencies & lead time for initial email blast
- [ ] Detemine VANotify dependencies for event-driven emails when a new Bad Address Indicator is added.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
I've documented my [discovery findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/discovery/va-notify-discovery.md) in GH and created a technical discovery item for Tom in Sprint 70 for him to determine the technical requirements.

The same underlying process should be able to be used for the initial blast and subsequent emails if we do the latter in a batch (daily, weekly).  

cc @Samara-Strauss
