### ISSUE TITLE
[Design] - Auth Profile - Bad Address Indicator - Work with Content on Email Copy

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38140]
## Background
A draft of the email to be sent to Veterans with bad addresses has been created in the VA Notify UI.  Our alerts also contain some of this copy. If necessary, create a Content request and review this email and alert text with Content for any copy changes needed.

## Tasks
- [x] Create a Content Request if needed
- [x] Review draft email with Content
- [ ] Review alert text with Content
- [ ] Make recommended changes to the copy
- [ ] Update PM when ready to review

## Acceptance Criteria
- [x] Create a Content Request if needed
- [x] Review draft email with Content
- [ ] Review alert text with Content
- [ ] Make recommended changes to the copy
- [ ] Update PM when ready to review

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske I created this yesterday but apparently didn't put you as the assignee.  Can you please review and estimate to the best of your knowledge?  Thank you!

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Added my best guess - hoping this will be around a 2!

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I've also added in "Review alert text" to the tasks and acceptance criteria because the alert text also included in the content ticket for review.
