### ISSUE TITLE
[FE] Events V2 UX Enhancement - Error Messaging 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38157]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Considerations
- improvement UX - Error messaging. In recent tests the "No results found" was perceived as frustrating after filtering because there was no "reset filters" option to "get back" to the search component. In this case we want to update the error messaging specifically for the "Custom Search" element. 
- Suggested Verbiage/Behavior: 
1. No Events listed because not events and/or filters applied (When no selection was imputed in search date range fields)
2. No Events listed because filters are applied that exclude events from view (When no events meet the search criteria). 

### Tasks
- [x] Update error messaging with updated verbiage and behaviors 
- [x] Test locally to determine functionality is as intended 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Error messages are updated to improve UX.  
- [ ] Local test are completed and Staging review is completed

**Comment by jilladams** [comment]
With the relaunch of Events V2, this error text is updated to read: "No events listed because filters are applied that exclude events from view."
![Screen Shot 2022-06-08 at 12 36 37 PM](https://user-images.githubusercontent.com/85581471/172703359-cbee8e97-3b8c-4a3b-9519-6a5445356f9b.png)

However, I'm not sure about :"No Events listed because no events and/or filters applied (When no selection was imputed in search date range fields)".  I'm not clear what that message means  or how you would arrive at that state.
