### ISSUE TITLE
Record Lovell design walk through

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38156]
## Issue description
The Captain James A. Lovell Federal Health Care Center has a combined mission to serve active duty military, their family members, military retirees and Veterans. The center also cares for an estimated 40,000 Navy recruits who prepare for military service at Recruit Training Command at Naval Station Great Lakes.

Primary question to solve - as a DoD or VA person, can I complete my top tasks and identify the information which is relevant to me.

Designs have been created as part of this epic. Feedback from SMES, stakeholders, IA and design teams have been incorporated along the way. This issue is to record a walk through with Dave Conlon and Michelle Middaugh to document status of these design and ensure continuity of this work in the new contract period. 

## Tasks
- [ ] Record Lovell design walkthrough meeting with Dave Conlon and Michelle Middaugh to document 

## Acceptance Criteria
- [ ] Status of these design is documented to ensure continuity of this work in the new contract period
- [ ] Location of this recording is noted in comments below.
