### ISSUE TITLE
Socialize the go-live (M 3)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38152]
# User story

As a Platform team member, I need to absorb the new twice-weekly go-live guidance so that my work can be regularly published to the Platform website.

# Tasks

- Pre-requisite: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38644 
- Run lightweight training session with PMs
  - [x] Schedule time with PMs
  - [x] Prepare for announcement to walk em through updated process
    - Plot outline
    - Anticipate Q&A
  - [x] Tell them where they can find the guidance
- Socialize guidance on Slack
  - [x] Draft message
  - [x] Get peer review on message
  - [x] Post message in #vsp-confluence and pin it
  - [x] Share message in #platform-team

# Acceptance criteria
- We've run a lightweight training session with PMs
- We've posted guidance on Slack

# Reference info
- The schedule: https://vfs.atlassian.net/wiki/spaces/~369451595/pages/2098200622?atlOrigin=eyJpIjoiMjI3ZmVmOTllNmNmNDFmOTk5MzI0ZDc4OWFiZjMzN2IiLCJwIjoiYyJ9

**Comment by lianilychee** [comment]
Weds 3/23:
- gretchen will prepare for session, will probs have talking points to give to amy

**Comment by lianilychee** [comment]
Liani get Amy the recording link today

**Comment by amygoldman** [comment]
Added link to messages
