### ISSUE TITLE
Publish six transformed TestRail docs (XS 1)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38154]
# User story

As a Platform customer, I want to consume clearer TestRail docs so that I can smoothly perform TestRail-related tasks for my VFS app.

# Tasks

- [x] Move embedded videos from Google Drive to YouTube
- For each of the TestRail docs
  - [x] Copy the contents from the Drafts space page into the live space page
  - [x] QA the copied contents for formatting issues
- [x] Inform QAST and Chelen that all the transformed TestRail docs are live on the Platform website
- We do not have to worry about publishing, because the changes will be deployed during the twice-weekly deploy

# Acceptance criteria
- The transformed docs are published on the Platform website

# Reference info
TestRail docs:

1. Creating a project in TestRail <- consolidated to?
2. Creating a test run in TestRail
3. Creating a test case in TestRail
4. Executing tests in TestRail
5. Integrate TestRail with GitHub
6. Reporting results in TestRail

**Comment by lianilychee** [comment]
3/17:
- copy and paste new content for liani to deploy
