### ISSUE TITLE
[FE] Do not allow Veterans to attempt to check in to the same appointment again

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#38166]
## User Story
As a veteran, I do not wish to be presented with a button to check into an appointment that I've already checked into, so that I do not see a confusing error message.

## Description
Slack thread: https://dsva.slack.com/archives/C02GXKL8WM6/p1646764790150259

To reproduce:
- Start day-of check-in
- Confirm demographics
- Press the check-in button
- Go back a page with the browser button
- Press the check-in button again
- Get the “We couldn’t check you in” error page

## Tasks
- [ ] Detect the back and force a refresh
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] "Check In" button is not presented when arriving on the appointment list via the back button
- [ ] The time that the appointment was checked into is shown when arriving on the appointment list via the back button
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
@loripusey did you mean to close this? This is still an issue afaik. Thanks!

**Comment by loripusey** [comment]
I did but I am consolidating all of the tickets from various enhancement epics into a list within the description a single enhancement[ epic](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/38484); I want to take the team through an exercise to prioritize all of the tickets that are out there into must haves, should haves, and nice to haves and only have tickets for the must haves (for now); the tickets are still there and if they are a must have then we will re-open the tickets; it's a technique to get the backlog under control

**Comment by acrollet** [comment]
@loripusey got it, thanks!
