### ISSUE TITLE
[Technical Discovery] Gain understanding of EVSS/va.gov Claim Status API 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3816]
## User Story:
As a back-end engineer, I need to understand what is being consumed by va.gov from the EVSS Claim Status API so that I can document my findings.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Gain understanding of all claims status endpoints and what they are expecting (what headers, http request method, query params).
- [x] Gain and document historical context of claim status API and general overview of the tool

## Acceptance Criteria:
- [x] Clear understanding of what va.gov is getting from the EVSS Claim Status API [documented](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/claim-status-api/discovery/technical-discovery.md)
- [x] Any and all pertinent knowledge gained should be archived.
