### ISSUE TITLE
Loan history list loop not working properly

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#38174]
## Background
The COE form includes a page where the veteran can enter their previous VA-backed home loans. Because the veteran may have had multiple different VA-backed home loans, we are using a list loop. Currently, after entering the information for the first loan and clicking the 'Add another VA-backed loan', there is an error in the console, and the form on the webpage disappears.

## Consideration
This is related to the schema changes that were made previously to change some of the properties used to more closely reflect the payload returned to LGY.

## Tasks
- [x] Fix the `PreviousLoanView` component to use the current property names

## Acceptance Criteria
- [x] `PreviousLoanView` component has been updated
- [x] A PR has been requested for merging
