### ISSUE TITLE
[Design]- Auth Profile - Bad Address Indicator - Write up Front End documentation

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38179]
## Background
Write up FE documentation on when and where the bad address notification will be displayed in the profile and when the email will be sent out (initial blast; whenever a new bad address is added)

## Tasks
- [x] Write up FE documentation on when and where the bad address notification will be displayed in the profile
- [x] Include information about when the initial email blast will be sent out
- [x] Include information about event-triggered emails will be sent out 
- [x] Send info to PM to review, then to PO when you agree it's ready

## Acceptance Criteria
- [x] Write up FE documentation on when and where the bad address notification will be displayed in the profile
- [x] Include information about when the initial email blast will be sent out
- [x] Include information about when event-triggered emails will be sent out 
- [x] Send info to PM to review, then to PO when you agree it's ready

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
@Samara-Strauss -- Here's the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/frontend/FE%20documentation.md) for Bad Address Indicator - of course with upcoming changes very likely! @MarciMcGuireGCIO and @adamwhitlock1 have both taken a look, so this is ready for your review. Thank you!

**Comment by Samara-Strauss** [comment]
Thanks for starting this, @cgednalske! To be clear, @adamwhitlock1 -- this is not ready for you to work off of yet, as the designs are a work in progress. We'll let you know when this is ready for you to dive into via more formal tickets in sprint planning.
