### ISSUE TITLE
Direct VFS teams to submit known issues to VA 508 Office post-staging review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38177]
## User Story
As a VFS team member, I want know when I should engage with the VA 508 Office so that I can communicate known accessibility issues.

As a Governance team member, I want to make sure that VFS teams know when to submit their known accessibility issues to the VA 508 Office post staging review.

- Intended Audience: VFS Teams
- Desired Outcome: VFS teams submit their accessibility issues found at staging review that they do not intend to fix before launch to the VA 508 office.
- Due Date: 

## Description
Ticket #38170 is retiring the Full Accessibility & 508 Office audit touchpoint from the Collaboration Cycle. However, VFS teams are still required to share their known accessibility issues with the VA 508 Office. Previously this was a task in the Full Accessibility & 508 Office Audit and now it will be a task in the Staging Review.

The purpose of this ticket is to add additional guidance in the Staging Review touchpoint to direct VFS teams to submit their known accessibility issues to the VA 508 office via the [VA 508 Office Audit Request process.](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest) 

**What is a known accessibility issue?**
If accessibility issues are found in the Collaboration Cycle Staging Review, issue tickets are documented. If the issue has the label `launch-blocking`, then the VFS team must fix the issue before launch. However if the issue does not have the label `launch-blocking`, or if the issue is labeled '508-defect-3` or `508-defect-4` then the issue does not need to be fixed before launch and can be addressed at a later date. These are the issues that the VFS team would be required to submit to the VA 508 Office via the Audit Request process, aka the known accessibility issues.

## Artifacts Needing Updates

- Platform Website: [Collaboration Cycle Staging Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) 
- GitHub: [Staging Review template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D)
- Confluence: [Staging Review Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#During-Meeting) (script only)
- Platform Website: [Collab Cycle Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) (this should be a summary of this ticket and ticket #38170)

## Tasks
- [x] Create documentation drafts of all Confluence and Platform Website pages needing updating.
- [x] Create pull request for GitHub template. 
   -  Documenting known issues should be an "After Meeting" VFS task
- [x] Make changes to all document drafts and PRs.
- [x] Peer Review with Shira 
- [x] Update Change History log
- [x] Announce change

## Acceptance Criteria
- [x] Staging Review Moderator Responsibilities Confluence document has been updated per guidance
- [x] Staging Review GitHub template has been updated per guidance
- [x] Collab Cycle Change history on Platform Website has been updated per guidance
- [x] Collaboration Cycle Staging Review touchpoint has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Changes for this ticket and #38170 have been shared with VFS teams via the [Platform Communication Playbook Guidelines](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1927675936/Platform+communications+playbook+-+Guidelines)

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by artsymartha68** [comment]
Looks good to me. 

Shall we specify that the report of open issues needs to be submitted in Word or Excel or some format that is not a PDF or an inaccessible web page? Some of the folks in the VA 508 Office are blind and they need an accessible document.

**Comment by shiragoodman** [comment]
If we do want to make that comment, I think we could open another ticket for editing the VA 508 Office Audit Request guidance (https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). With this ticket, we're only pointing people to that guidance, not changing the guidance itself. Let me know if that makes sense.

**Comment by jimuhh** [comment]
@artsymartha68, @shiragoodman -- I don't see any obstacle to just including that in the text we're changing. 
Currently, I'm looking at [this template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md) and was planning to put that info under "Accessibility Artifacts"

**Comment by jimuhh** [comment]
@shiragoodman -- Just want to be sure I understand the cadence of the new process. 
So, the accessibility people on collab cycle team will submit their feedback in the drafting template as before but the VFS teams themselves are responsible for submitting the ID'd issues (now called "Known Issues") to the 508 office for review? 
Do I have that right?

**Comment by shiragoodman** [comment]
@jimuhh not exactly. What you're doing with this ticket is pointing VFS teams POST STAGING REVIEW to communicate what issues they did not fix before launch to the VA 508 Office. The process our team follows re: the Drafting Template, and creating issues does not change.

**Comment by jimuhh** [comment]
@shiragoodman @chaseakirby I rewrote the instructions on this page. @artsymartha68 I'd like to provide a suggested time frame for requesting an accessibility audit (after launch?)

**Comment by jimuhh** [comment]
Added line about needing to document non-launch-blocking 508 staging issues in [moderator's script ](https://vfs.atlassian.net/l/c/kbHp1d5e)for staging review

**Comment by jimuhh** [comment]
Submitted pull request for edits to [Staging Review Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md)

**Comment by shiragoodman** [comment]
@jimuhh yes, I agree with after launch at the latest. This is just an interim solution until the new core template is launched, so I support your decision. 

@chaseakirby can you please review Jim's changes?

**Comment by chaseakirby** [comment]
@shiragoodman Yep! I agree since this is an interim solution. I can approve the PR so you can sign off for your PTO.
@jimuhh You can disregard my comment on the moderator script.

**Comment by jimuhh** [comment]
@chaseakirby Too late. I made the suggested change :wink:

**Comment by chaseakirby** [comment]
@jimuhh Working too fast for me to keep up with! Great job, I think it looks good. I went ahead and approved on the PR too.

**Comment by shiragoodman** [comment]
@chaseakirby Jim already closed this, but the tasks and AC are still unchecked. I'd like to make sure we DON'T do this as there are still things that need to take place that could've been overlooked bc the ticket was closed (for example, posting to the Change History log)

**Comment by shiragoodman** [comment]
im also just noticing that the PR Jim created was never merged
