### ISSUE TITLE
Retire Full Accessibility & 508 Office Audit from Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38170]
## User Story
As a VFS team member, I want to have an updated list of required Collaboration Cycle touchpoints so that I can prepare properly.

As a Governance team member, I want to remove all guidance and references to the Full Accessibility & 508 Office Audit so that VFS teams receive correct and current guidance.

- Intended Audience: VFS Teams
- Desired Outcome: No more Full Accessibility & 508 Office Audit!
- Due Date: 

## Description
Governance team drafted a [Proposal to remove Full Accessibility & 508 Office Audit from the Collaboration Cycle.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2031812634/Proposal+to+remove+Full+Accessibility+508+Office+Audit+from+the+Collaboration+Cycle). The proposal was sent to the VA 508 Office for their review, and the request was approved via Martha Wilkes (OCTO-DE Accessibility Lead) and Pat Sheehan on March 3, 2022.

## Artifacts Needing to be archived
**Platform Website:**
- [Full accessibility & 508 office audit ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html )page
- [How to prepare for an accessibility post-launch audit](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-post-launch-audit.1909063817.html)

**Confluence:**
- [Full accessibility & 508 office audit - Moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1893662799/Full+Accessibility+508+Office+Audit+-+Moderator+Responsibilities)
- [Steps of an accessibility audit](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2002059367/Steps+of+an+Accessibility+Audit)

**GitHub:**
- [Full Accessibility & 508 Office Audit ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=508%2FAccessibility%2C+governance-team%2C+collaboration-cycle%2C+collab-cycle-review&template=full-accessibility-and-508-office-audit.md&title=Full+Accessibility+%26+508+Office+Audit+%5BTeam+Name+-+Feature+Name%5D)github template

## Artifacts Needing Updates
**Platform Website:**
- [Collaboration Cycle overview page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [Collaboration Cycle touchpoints page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
- [How to request support from the VA 508 Office: Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest)

**Confluence:**
- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
- [Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) (Shira will update)

## Tasks
- [x] Update "Artifacts Needing Updates" pages to remove referenced to the Full Accessibility and 508 Office Audit
- [x] Archive all artifacts needing to be archived
   - [x] For the GitHub template, the template can be deleted.
- [x]  For the [How to request support from the VA 508 Office: Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest), remove "In the Collaboration Cycle Full Accessibility and 508 office audit touchpoint". The sentence should start with, "Teams are required..."

## Acceptance Criteria
- [x] "Artifacts Needing to be archived" have all been successfully archived or deleted
- [x] "Artifacts Needing Updates" no longer make any reference to the Full Accessibility & 508 Office Audit

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Initiative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by artsymartha68** [comment]
Looks good to me, thanks for the nitty gritty details!

**Comment by CherylEvans** [comment]
Archived/Updated all pages to reflect removal of all "Full Accessibility & 508 Office Audit" reference.  GH template has been deleted.

**Comment by jimuhh** [comment]
Thanks @CherylEvans

**Comment by CherylEvans** [comment]
You are quite welcome Jim! Please let me know if you have any questions or
concerns regarding the changes/updates I have made.  Thanks!

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

203-580-3529 | ***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by jimuhh** [comment]
Ready to close? If so, I can get on 338177
