### ISSUE TITLE
[BE]- Auth Profile - Bad Address Indicator - Discovery for clearing flag on valid addresses

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38178]
## Background
There may be rare occassions when a Veteran's mailing address has been flagged as invalid by mistake - human error, USPS issues, etc.  We need the ability to allow a Veteran to verify that their address is actually valid and clear the flag without making a change to the mailing address on file.

## Tasks
- [x] Determine from VA Profile if we can clear a bad address flag without updating the address 
- [ ] If some sort of change is required, identify and document strategies for getting the flag cleared while persisting the stored address.

## Acceptance Criteria
- [x] Determine from VA Profile if we can clear a bad address flag without updating the address in their current configuration
- [ ] If the address must be altered, identify and document strategies for getting the flag cleared and restoring the address that was already on file and incorrectly flagged.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@tpharrison - can you please review this issue and estimate to the best of your knowledge?  Thank you!

**Comment by tpharrison** [comment]
@MarciMcGuireGCIO there is really nothing to do here based on Barry's response here - https://dsva.slack.com/archives/C7TE0PFTL/p1646775102156129.  

The functionality should already be in place.  We just want to make sure we test it.  I think we can close this.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @tpharrison!
