### ISSUE TITLE
[Research] - Auth Profile - My HealtheVet Discovery - Plan remainder of research engagement

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38183]
## Background
Complete planning for remaining tasks in MHV research engagement

## Tasks
- [ ] Complete research planning
- [ ] Review plan with PM and PO

## Acceptance Criteria
- [ ] Complete research planning
- [ ] Review plan with PM and PO

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz - Samara had this in Sprint 69 if time allowed.  If you have time, can you add an estimate to this, along with any additional details/AC you might need?  Thanks!

**Comment by andaleliz** [comment]
Oh, I thought I completed the plan in #37646. I'd need more details about what she's looking for to provide an estimate or AC. Do you have any more insight as to what was incomplete from that last ticket? If not, I can ping her.

**Comment by andaleliz** [comment]
Maybe it's to create the research plans for the Veteran and MHV coordinator interviews?

**Comment by Samara-Strauss** [comment]
Yes, the plan is:

- **Sprint 69**: Stakeholder interviews
- **Sprint 70**: User research planning/recruiting
- **Sprint 71**: User research/start summary
- **Sprint 72**: Deliver research summary

This is adjustable, so let me know if it doesn't meet expectations

**Comment by Samara-Strauss** [comment]
This all sounds good to me. I don't think you are missing anything, and I don't think we need to do any additional planning. You can probably close this ticket.
