### ISSUE TITLE
[Technical Discovery] Research archived Claim Status API materials

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3818]
## User Story:
As a back-end engineer, I need to review the formerly used vets.gov-team repo documentation so that I can locate Claim Status API documentation during my technical discovery.

## Tasks
- [x] Start search in [migration spreadsheet](https://docs.google.com/spreadsheets/d/1Y4QvGd_d_PCAb_yO6u2Gxyn9VXqQJ1hGL_DZc5h90so/edit?ts=5db20057#gid=0) that contains title of every document in vets.gov-team repo
- [x] Reach out to vets.gov-team repo SMEs for additional paths to look for archived documentations
- [x] Identify SMEs who are still on the VSA or VSP contracts that worked with the Claim Status API

## Acceptance Criteria:
- [x] Archived documentation has been located
- [x] Archived documentation has been added to va.gov-team repo
- [x] Technical Discovery documentation has been updated based on findings
- [x] Identified and scheduled discussions with vets.gov-team SMEs
- [x] Identified and scheduled discussions with Claim Status API SMEs
