### ISSUE TITLE
Midpoint Review [Identity, Inherited Proofing]

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#38186]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [x] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

PRODUCT OUTLINE: [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/MHV%20Inherited%20Proofing/ProductOutline.md)
WIREFRAME: [LINK](https://www.figma.com/file/8dEEQhOJtzrerb7fnZLoMz/MHV-Account-Transition-Collab-Cycle-and-Content-IA)
RESEARCH PLAN: [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/MHV%20Inherited%20Proofing)
CONVERSATION GUIDE: [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/MHV%20Inherited%20Proofing)

 
- [ ] Conversation guide 

### Content artifacts 

- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [ ] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
Review has been scheduled for March 14th at 3:30 ET. Please forward to anyone else you would like.
I see that you indicated that you have met with the Sitewide Content team, please link the ticket or any content artifacts if they are relevant.

**Comment by allison0034** [comment]
Hi @nsoutouras would it be possible to get a mobile view? If you are short on time I specifically think the modal is the concern.

**Comment by CherylEvans** [comment]
Content FB: Continue to work with Sitewide Content and IA.

**Comment by jimuhh** [comment]
No additional IA feedback at this time, thanks!

**Comment by nsoutouras** [comment]
A couple quick followups to the meeting:

**Mobile**: Our primary focus with this round of research is that users understand what is happening, and grasp the content we are putting in front of them and the process involved.  We aren't really focused on the mobile usability aspect of these wireframes as much as we are that.  Given that, our intention is to use the feedback we garner in this research to inform future, mobile-focused research.  As such, we can create high-fidelity mobile mockups but they will only be available to the Collab Cycle (not go in front of Veterans) as they fall out of scope of our current research plan.

**Wizard**: We've gone ahead and started removing the wizard from our process in followup to Content/IA guidance, however, the design system still seems to point to a wizard as an available pattern.  Is there a timeline on when that intended change will take place?  Having the design system updated would prevent other teams from getting into this scenario in the future.

**Comment by seanasewell** [comment]
I'm going to connect with @allison0034 tomorrow at 10am to discuss some notes I took during the meeting. As a result, design feedback will not be available until early afternoon tomorrow (March 15th). Sorry for the delay!

cc @shiragoodman @chaseakirby @nsoutouras

**Comment by Saraharaba8** [comment]
No further feedback from me

**Comment by claytonzook** [comment]
No further feedback from research. Kudos for linking past research.

**Comment by seanasewell** [comment]
> 

We understand that your primary focus is that users understand what is happening but as @artsymartha68 said in the meeting, 50% of the traffic is going to be on mobile so it should be a priority. There is a lot of content in the modal right now. It makes me curious to how much vertical space that would take up on mobile and if that would create a negative experience for users. Can we at least mock that up so that we can have a better understanding of how that will appear in front of users?

**Comment by seanasewell** [comment]
> A couple quick followups to the meeting:
> 
> **Mobile**: Our primary focus with this round of research is that users understand what is happening, and grasp the content we are putting in front of them and the process involved. We aren't really focused on the mobile usability aspect of these wireframes as much as we are that. Given that, our intention is to use the feedback we garner in this research to inform future, mobile-focused research. As such, we can create high-fidelity mobile mockups but they will only be available to the Collab Cycle (not go in front of Veterans) as they fall out of scope of our current research plan.
> 
> **Wizard**: We've gone ahead and started removing the wizard from our process in followup to Content/IA guidance, however, the design system still seems to point to a wizard as an available pattern. Is there a timeline on when that intended change will take place? Having the design system updated would prevent other teams from getting into this scenario in the future.

We understand that your primary focus is that users understand what is happening but as @artsymartha68 said in the meeting, 50% of the traffic is going to be on mobile so it should be a priority. There is a lot of content in the modal right now. It makes me curious to how much vertical space that would take up on mobile and if that would create a negative experience for users. Can we at least mock that up so that we can have a better understanding of what that will look like?

**Comment by jimuhh** [comment]
There was no IA feedback yesterday because it was understood that this is a work in progress, so the noticeable issues would be resolved upon further consultation w/ IA and Content teams. On consultation w/ team, it was decided that we should go ahead and document those issues in this ticket to inform your team's planned outreach to Content and IA. Look for that by EOD.

**Comment by artsymartha68** [comment]
For something as pervasive as log in, we definitely need to consider the mobile design. One of VA.gov core design principles is Mobile First, Accessibility First.

From https://design.va.gov/design/principles

> Accessibility is core to all design decisions. People with disabilities do not have less needs than anyone else. Everyone should be able to use any tool or application regardless of features or complexity.
> 
> Design mobile first because it surfaces the most important tasks and information in the most constrained context. By considering a smaller form factor before a larger one, it helps you prioritize the information and choices most critical to the user.

**Comment by AGarcia-Clarity** [comment]
One of things I'd like to reiterate is the goal of our research plan is see if the content is understandable and if a Veteran can complete the task of the Inherited Proofing process.  The Identity team **will** be creating the high-fidelity, mobile mockup of the Inherited Proofing process.  However because this is outside of the current scope the mobile mockups will be completed at a later date.  

The Impact & Simplicity in VA's Design Principles:

> **Solve for clarity and consistency first, solve for polish second**.
> Understand the user problem with user flows, sketches, and wireframes before developing high fidelity solutions. Share that work for critique and improvements by looking across the larger ecosystem of VA.gov before getting to the details.

> **The VA.gov customer experience should be consistent across tools, applications, and devices**.
> A Veteran should be able to access the same content and user experience regardless of how they engage with their data.

**Comment by allison0034** [comment]
Hi @AGarcia-Clarity thanks for the explanation, I know working within scope can be hard. I originally asked for a mobile view because I have concerns around the modal and the content. Modals are typically for quick information or decisions. My concern is that some of the content is too long on the modal and testing this in a mobile view would help with your goal. We need to make sure all the content can fit on a mobile screen without scrolling and that it is easily understood.

I think as long as you test with mobile at some it should be fine, but I would recommend starting with mobile due to the content concern.

Also, for any future designs we ask that you design mobile first per our [design principals](https://design.va.gov/design/principles#usable-by-everyone).

**Comment by AGarcia-Clarity** [comment]
@allison0034 I completely agree with you about the current mockup's modal content being too long.  We are actively working with Danielle on the Content/IA team to help remediate the verbose content to something more simple and concise.
