### ISSUE TITLE
[Research] - Auth Profile - My HealtheVet Discovery -  Complete stakeholder interviews & synthesis

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38182]
## Background

 Complete the remaining interviews + note synthesis for bringing MyHealtheVet Profile fields into VA.gov Profile.

## Tasks
- [x] Follow-up interview with MHV Health Apt team
- [x] Interview with Carnetta Scruggs (MHV)
- [x] Interview with Susan Haidary (Coordinator lead)
- [x] Interview with Theresa Hancock (MHV)
- [x] Interview with Patricia Henry (MHV)
- [x] Synthesize research, including notes from team interviews.

## Acceptance Criteria
- [x] Complete remaining stakeholder interviews
- [x] Synthesize research

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz please feel free to add any additional details you need to this ticket.  Thanks!

**Comment by andaleliz** [comment]
[Storing meeting notes here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/mhv-profile-research/meeting-notes); awaiting intro to Patricia Henry to schedule that final interview.

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO I have a [draft ready of the synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/stakeholder-interviews.md); would you mind taking a look and letting me know if any edits are needed? Specifically would love to know if anything is unclear, or if you think there are any major points I'm missing from your recollection of the conversations.

I know for sure I need to add titles for 2 stakeholders listed at the top.

I have a 2 remaining interviews tomorrow. I'll likely add more info after those calls, but I feel like this is in a good spot to get feedback. Thanks!

**Comment by andaleliz** [comment]
@Samara-Strauss and @MarciMcGuireGCIO, I've written up the[ key takeways](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/stakeholder-interviews.md) from all the stakeholder interviews. Please let me know if more details or edits are needed on any of these.

I'm looking forward to supplementing this with input from Veterans! We can circle back to stakeholders if needed after we complete that next phase.

**Comment by Samara-Strauss** [comment]
Fantastic! I am going to read through this tomorrow.

**Comment by MarciMcGuireGCIO** [comment]
Thanks @andaleliz ! It was looking great, and I’ll give it another look with yesterday’s info added.

**Comment by MarciMcGuireGCIO** [comment]
100% agree with @Samara-Strauss, @andaleliz!  This is really informative.  Thank you!
