### ISSUE TITLE
[Design] - Auth Profile - Bad Address Indicator - Modify design to handle valid addresses flagged in error

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38184]
## Background
There exists the possibility that a Veteran's mailing address could be flagged in error in the event of a USPS mistake (sent to wrong address), clerical error, or a scenario where a Veteran moves into/out of/back into the same location where the address is invalid for a short time, but later becomes valid (ex - lived with parents, moved out, moved back in).   

The UI needs to provide affordance for Veterans to confirm a flagged address is valid without actually making any changes to the address on file.

## Tasks
- [x] Update mockups to provide a way for Veterans to validate an address that has been incorrectly flagged as invalid while on the VA Profile page
- [x] Notify PM when ready so we can review with PO and schedule a design intent review

## Acceptance Criteria
- [x] Update mockups to provide a way for Veterans to validate an address that has been incorrectly flagged as invalid while on the VA Profile page
- [x] Notify PM when ready so we can review with PO and schedule a design intent review

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Thanks @MarciMcGuireGCIO! 

Adding a note for reference based on either answer Tom gets back about whether we can clear a bad address flag without changing the address:

If yes, we currently have the placeholder link to confirm (shown below) - though we'll want to finesse that and may need a second step. If no, a more extensive flow would be needed. For both, I think there's a good chance we can utilize some of Liz's earlier audit work for a similar confirmation format. 🤞 
 
<img width="604" alt="Screen Shot 2022-03-08 at 2 43 43 PM" src="https://user-images.githubusercontent.com/79372956/157330447-fe760d00-db1b-4acf-8050-f60d20700bd6.png">

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @cgednalske!  Looks like that is technically feasible based on [Tom's comment here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38178#issuecomment-1062298369).

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Ok great! That makes it simpler.

So all we need to confirm is if we need a separate step after someone clicks the "confirm" link. I believe we do, as I don't think we can directly confirm from a link as if it's a button. 

This discussion actually came up in Platform Design Office Hours for a different reason - whether or not to link directly to an open edit state. Based on that, sounds like we'll need to take the user to a real button of some sort to confirm (I could see this working with a modal that follows the format Liz was working on for the alerts audit - see my example below with placeholder text). 

The alternative is to have a button within the alert, but that goes against design system guidance, so I don't think we can do that.

<img width="777" alt="Screen Shot 2022-03-09 at 8 54 42 AM" src="https://user-images.githubusercontent.com/79372956/157478777-7cb16c01-4a78-44e9-bb95-491d7cb69fc1.png">

**Comment by MarciMcGuireGCIO** [comment]
Making a note that we discussed in sprint planning and are good with this approach.

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO -- Linking the updated sketch files for Bad address indicator here - showing Personal info, Contact info, and Confirmation Modal for both [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/Pn1Woj/a/3OMD28m/r/l8Rw74) and [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WK0EMb0).

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !

**Comment by cgednalske** [comment]
Hi @MarciMcGuireGCIO! I think this can be closed unless there's anything I'm forgetting about.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !
