### ISSUE TITLE
[Epic] Identity for Inherited Proofing

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#38185]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

PRODUCT OUTLINE: [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/MHV%20Inherited%20Proofing/ProductOutline.md)
WIREFRAME: [LINK](https://www.figma.com/file/8dEEQhOJtzrerb7fnZLoMz/MHV-Account-Transition-Collab-Cycle-and-Content-IA)
RESEARCH PLAN: [LINK](https://docs.google.com/document/d/1cw3QhjA6Iha7J5p5AJx_EmyVe-5kOMZTBVi_OIanmT8/edit?usp=sharing)
CONVERSATION GUIDE: [LINK](https://docs.google.com/document/d/1AJFWsYV4Rn2ZhGI7kLKCpS5VnTHAuhI2y0c3Myn1dok/edit?usp=sharing)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: May 2022
- Estimated staging review date: End of April 2022
- Content and IA work needed by:  ASAP

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Identity
-	OCTO-DE product owner: Cody Reinold @codyreinold-usds 
-	Product manager: Nick Soutouras @nsoutouras 
-	Designer: Sam Veng @Vngpire 
-	FE engineer: Alex Garcia @AGarcia-Clarity 
-	Product/team Slack channel: #vsp-identity

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hi @nsoutouras!  I have a few questions/comments for you after reviewing the flows and mock ups.  

1. Specifically when will users who are logging in be intercepted with this modal? Just when prompted from related email communications, or content pages specific to this situation?  We cannot intercept users logging in to complete a task that is unrelated to this event.  It will be confusing, and would take users out of the flow of finishing critical tasks such as completing an application or updating data. 
2. Because this is something that will likely be triggered through email or online content, and not necessarily something users will navigate to in the experience,  you will not need the breadcrumb on the information page. You can remove it for user testing along with the horizontal rule (which we don't have on core content pages).  Resources and support articles will have a breadcrumb per the existing site. 
3. The wizard component is being retired due to a number of usability and accessibility issues.  It looks like the information you have in the wizard should be presented with straight content since it is not part of a form flow. 
4. What page is the user sent to once they complete the Login.gov or ID.me flow?  I see it represented in the flow as having either confirmation or error messaging, but don't see a wireframe for it.  It is also likely that they will be logged out of VA.gov during the process, so the page they return to would not be personalized.
5.  If the process fails, do they continue to get a prompt to try it again?  Or how/where/when do we direct them to try this process up again?

**Comment by mnorthuis** [comment]
Thank you for jumping on a call with me this morning @nsoutouras!   Here are my notes from our discussion related to Sitewide Content and IA needs and timing for this first round of research and Midpoint review.  I will add full meeting notes to my IA issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38416.

Timeline and research:
- Pilot research session to be held on 3/18, research starting on 3/21
- There will be multiple rounds of research
- Launch of this process will likely be around May 1 or potentially later

Next steps for Sitewide Content and IA:
- IA will provide high level feedback to support first round of research by end of day Friday 3/11 
- Content team will review for high level feedback next week - the focus will be on primary content elements such as headings and CTAs and general voice/tone to support your initial research.  Timing around full content work is TBD.

**Comment by SgardnerPMP** [comment]
Possible - content stories include:
*email correspondence
*Landing page
*R&S articles 
Danielle is leading, and effort is moderate to considerable.  6 to seven weeks, but customer wants now.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @nsoutouras. As we've talked about a bit in slack, we need a lot of content work on this effort to align with the VA.gov voice/tone/plain language standards. We also need to address some of the questions and recommendations that @mnorthuis has raised as part of her IA work.

Here's a link to a [work-in-progress draft content doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EXlaeiACcsxKhyw2DFZLMqsBitZUTPFpcP50EZTn_Bkaug?e=fb2NS1). I believe you all have started usability testing, so I think it would be good for all of us to meet and talk through how to proceed before I continue working through this content. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @shiragoodman. Wanted to make sure you're aware of these IA and content reviews for context of collaboration cycle. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @nsoutouras. @mnorthuis mentioned that you all have another round of research coming up soon. We should connect before then re: content and IA to make sure that what you're testing with folks reflects our conversations and recommendations coming out of those. Thanks.

**Comment by nsoutouras** [comment]
@DanielleThierryUSDSVA Is it possible to move that content doc into another space?  Part of the team is unable to access it.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @nsoutouras. I'm attaching the latest version of the doc here for reference. But ideally, we'll want to work in a shared doc. Team members should be able to access it as long as they're on the VA network. Do folks not have access to the network?

[identity content changes_03.30.22](https://app.zenhub.com/files/133843125/c05d0503-3271-492a-bfda-278777cb92fe/download)

**Comment by mnorthuis** [comment]
Per John R - This work will pick back up,  Joe Niquette (Identity Core), Elizabeth Koch, and Tyler Gindraux (Login.gov Adoption Team) are contacts as Nick is no longer with Oddball.
