### ISSUE TITLE
Design intent [Facilities Team - Lovell federal health care page iteration]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38196]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [x] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

### Has your product been reviewed by the OCTO-DE Design Lead?
- [x] Yes - for the product, yes - for the iteration, no
- [ ] No

**This review is requested as a follow-up from the design intent (#34483) on January 7, 2022. Additional input from SMEs, stakeholders, IA, and design peers have been incorporated into this most recent iteration.**

## Artifacts

Provide links or documents for the following: 

- [x] [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell-initiative-brief.md)
- [x] Relevant issues
       - Epic: Lovell VAMC pages #34022
       - Previous design intent #34483
       - IA feedback in #37835
 - [ ] Design mockups
       - [UX Pin for Lovell Federal](https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148479144/simulate/sitemap?mode=i)

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event - _scheduled for 1:30pm - 2:00pm, Mountain time on Monday, March 21, 2022_

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@mmiddaugh we don't typically meet with teams twice for a Design Intent, however we can make an exception due to the timeline of your contract. Please be sure to post on #vfs-platform-support so we can complete scheduling.

**Comment by nicko-amida** [comment]
@mmiddaugh @shiragoodman Here's the [UXPin for Lovell Federal that we'll be taking a look at](https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148479144/simulate/sitemap?mode=i). Navigation is via the sitemap (left side).

**Comment by nicko-amida** [comment]
@shiragoodman This design intent incorporates [feedback we've already received from Mikki - #37835](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37835)

**Comment by CherylEvans** [comment]
No Content Feedback.  Thank you!

**Comment by allison0034** [comment]
Zoom recording
Topic: Design intent [Facilities Team - Lovell federal health care page iteration]
Date: Mar 21, 2022 03:30 PM Eastern Time (US and Canada)

Meeting Recording:
https://us06web.zoom.us/rec/share/2K2z0rgylWF-_1CnFYBQQEyDD3T8ci9tg8zyT--wUrTyQMivqS0ATbIBV1XRmNgt.UbdwQRSBVHQpkr88

Access Passcode: 60C?51+n

**Comment by claytonzook** [comment]
No actionable feedback for research at this point. I will however reiterate the feedback from the meeting. Also let me know if you want to brainstorm anything as you begin planning research.

**Consider research plans that:**
- tests questions you have with any words or wording choices
- includes dual enrolled participants (VA + TRICARE)
- includes mobile users
- includes the assistive tech users you can test with in pre-coding environment (e.g. screen zoom)
- includes under represented user groups

**Comment by allison0034** [comment]
No design feedback other than the few things mentioned during the meeting. Don't forget mobile views and user flows at the midpoint if possible. Great work!

**Comment by Saraharaba8** [comment]
No accessibility feedback! Great job everyone

**Comment by mnorthuis** [comment]
Hi @nicko-amida!  

The product is really shaping up!  I had a few questions/thoughts after looking at the latest iteration.  I put them in our IA ticket so we can keep our conversation going there.   Thank you!

https://github.com/department-of-veterans-affairs/va.gov-team/issues/37835

**Comment by nicko-amida** [comment]
Here's an update for UXPin designs: [Lovell Federal VA and TRICARE](https://preview.uxpin.com/d55fbe11583adc1a1d7b6e2bafde9ef560c7bf36#/pages/148503607/simulate/sitemap?mode=i) are now treated as distinct systems. The [choose either VA/TRICARE page](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/148756398/simulate/sitemap?mode=i) is now deprecated and in a separate UXPin in with older iterations of the design.
