### ISSUE TITLE
Vets - APi Endpoint - Service Object completed

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3819]
##User Story:
As a Back-end developer, I need to supply the Front-end Devs a way to start the service object on a mac book development platform so that our Front-end dev can do the API calls with Mock Data.

## Tasks
The steps that must be done by the team to complete the acceptance criteria
- [ ] Generate service class skeleton code
- [ ] Generate routing and controller code skeleton
- [ ] Use standard JSON serializer Gem
- [ ] Review code with Front-end developers
 
### Service Object
1. - [ ] Service class
2. - [ ] Config class & Faraday connection
3. - [ ] Breakers initializer
4. - [ ] Response class
5. - [ ] `settings.yml`

## Acceptance Criteria:
The requirements that must be met in order to mark this user story as completed
- [ ] Service object skeleton runs on a mac book development platform
- [ ] Front-end dev can do API call with Mock Data

## Next Steps:
- Get code ready for Swagger

##Blockers / Dependencies 
- Front-end API schema ticket []needs to be completed
- Discovery needed to complete API schema agreement

##Configuration
 Attached to a Milestone: 9
 Attached to an Epic (what body of work is this a part of?)
 Labeled with Team: Product support, Tools-improvements
 Labeled with Practice Area: back-end
 Labeled with Type: documentation
