### ISSUE TITLE
[FE] VA.gov deep link change for lab and test results page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38198]
#### High-level user story
The testing tools team has found a VA.gov deep link that needs adjusting for the lab and test results page. 

### How to reproduce the issue
Issue can be reproduced in Prod here -->
1. Sign into VA.gov
2. Select the View lab and test results link
3. Select the Go to My HealtheVet button

Actual: User lands on MHV home page
Expected: User shall land on MHV LABS + TESTS page

### What needs to happen
To address this, we need the URL formatted as [<serverHost>/mhv-portal-web/web/myhealthevet/labs-tests](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsqa.eauth.va.gov%2Fmhv-portal-web%2Fweb%2Fmyhealthevet%2Flabs-tests&data=04%7C01%7Cbrian.lloyd%40govcio.com%7C091108fec4a34f19fbfb08da0150466f%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637823741553788795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kekfZmEdem7XjTwytEiqXzr%2B7VbeecVqfn%2FjOkQpLu0%3D&reserved=0)

Where <serverHost> is the corresponding eauth server environment, which of course changes for each environment (for syst, it’s:  [https://sqa.eauth.va.gov](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsqa.eauth.va.gov%2F&data=04%7C01%7Cbrian.lloyd%40govcio.com%7C091108fec4a34f19fbfb08da0150466f%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637823741553788795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jts5fRwL%2FfGkk0K5eW5qXui52IIMGYU7dLveSE93ZHQ%3D&reserved=0)).

### Tasks
- [ ] Fix deep link issue for /labs-tests part that’s missing or malformed. 
- [ ] Test locally to determine functionality
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Deep link issue is resolved   
- [ ] Local test are completed and show signs of success
- [ ] Stakeholder is updated on status of deep link

**Comment by longmd** [comment]
@brianalloyd , So it looks like we need the deep link name provided to us for this one. It was previously commented as a TODO because that wasn't previously provided.

```
// TODO: Update labs-and-tests route once deep link is provided
const mhvToEauthRoutes = {
  'download-my-data': 'eauth?deeplinking=download_my_data',
  'web/myhealthevet/refill-prescriptions':
    'eauth?deeplinking=prescription_refill',
  'secure-messaging': 'eauth?deeplinking=secure_messaging',
  appointments: 'eauth?deeplinking=appointments',
  home: 'eauth',
  'labs-tests': 'eauth',
};
```

**Comment by longmd** [comment]
@brianalloyd , I think we need to reach out and ask about that deeplink name. The suggested `labs_tests` that we decided to try per the discussion with Dave does not work either. This is available for testing, but does not produce the correct result.

**Comment by brianalloyd** [comment]
@longmd reaching out now.  Thanks for closing the loop.

**Comment by longmd** [comment]
@LindaLi123 , this redirect is now successful with the values provided by the group on the email chain today! We can go ahead and notify them that this is good to go. Closing as complete.
