### ISSUE TITLE
Add Button to Download FSR PDF Back

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#38191]
## Issue Description
FSR PDF downloading has been blocked by this [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402). After updating the credentials on staging this button should be added back. Add button behind feature toggle to assert that we don't add PDF functionality back in prod until ready

---
## Tasks
- [ ] Add feature toggle for pdf generation
- [ ] Add button to download pdf for FSR

## Acceptance Criteria
- [ ] When a veteran submits an FSR they are able to press a button to download their PDF
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
https://preview.uxpin.com/4963ba1575f3616f61f9a1c8e40b66501c9303d0#/pages/139691671/simulate/sitemap?mode=i
