### ISSUE TITLE
[EKS/Datadog] Ensure requests and limits are set on all deployments

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#38201]
## Description

Up to this point, we have not had a good idea what to set for requests and limits. We have previously deployed goldilocks to evaluate this for us. We can now use the recommendations that goldilocks provides to set the appropriate requests and limits for all of our deployments.

However, setting the requests and limits can have adverse effects, as in, cpu throttled or completely terminated for too much memory usage. Because of this, we want to have visibility into any pods that are throttled or terminated. We will want to create monitors in Datadog and alert us in the event either scenario occurs.

## Additional Resources

For more information, see [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29812#issue-992584001) technical notes section

## Task
- [x] Create monitor in Datadog to alert when pods are cpu throttled or terminated due to memory usage
  - [x] Alert should be notified in #devops-alerts
- [x] Makes sure we have appropriate requests and limits for all deployments
  - [x] Use goldilocks dashboard to `Burst QoS`
  - [x] Can add additional resources in addition to golilocks recommendation

## Acceptance Criteria
- [x] Monitoring is created in datadog
- [x] Notification of resource threshold exceeded or terminated be sent to #devops-alert channel

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/401

**Comment by oseasmoran73** [comment]
Was doing some research on CPU throttle and stumbled upon this [thread](https://github.com/robusta-dev/alert-explanations/wiki/CPUThrottlingHigh-(Prometheus-Alert)#recommended-remediation)

**Comment by oseasmoran73** [comment]
@mleclerc00 Alerts have been setup for the following:

- OOM
- CPU
- Pods restarting > 3

Given the convo we had last week with @ph-One , would it make sense to close out this ticket once we revert the PR for upper limits set? I can also update the Acceptance criteria if needed.

**Comment by mleclerc00** [comment]
Yep, I am good with circling back and removing limits again based on the convo

**Comment by oseasmoran73** [comment]
Updated requests for environments for those that I was able to find. Closing ticket
