### ISSUE TITLE
Vets - APi Endpoint - Controller Routes completed

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3820]
##User Story:
As a Back-end Dev, I need to run the Controller, Route & Serializer automatically to invoke the service object so that our Front-end dev can do API call with Mock Data.

## Tasks
The steps that must be done by the team to complete the acceptance criteria
- [x] Generate Controller skeleton code
- [x] Customize routing and controller skeleton
- [ ] Write unit test for JSON serialization of 'get and 'put' API calls.
- [x] Review code with Front-end developers

### Controller, Route & Serializer
- [x] Controller action
- [x] Route
- [x] Serializer

## Acceptance Criteria:
The requirements that must be met in order to mark this user story as completed
- [x] Controller skeleton runs on a mac book development platform
- [x] Route skeleton runs on a mac book development platform
- [x] Serializer skeleton runs on a mac book development platform
- [x] Front-end dev can do 'get and 'put' API calls with Mock Data

## Next Steps:
- Get code ready for Swagger

##Blockers / Dependencies 
- Front-end API schema ticket []needs to be completed
- Discovery needed to complete API schema agreement

##Configuration
 Attached to a Milestone: 9
 Attached to an Epic (what body of work is this a part of?)
 Labeled with Team: Product support, Tools-improvements
 Labeled with Practice Area: back-end
 Labeled with Type: documentation
