### ISSUE TITLE
[FE] Tech Debt - Clean up duplicate actions between day-of and Pre-check-in

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#38238]
## Description
Actions for recording answers to demographics responses are being duplicated in day-of and pre-check-in. These can be moved to the shared actions file to reduce duplication. 

## Tasks
- [x] Move record actions to shared actions file (we have an existing shared file)
- [x] Update import paths
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Code is reviewed and  merged into master
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
