### ISSUE TITLE
[FE] Display Required Field Indicator(s) when User Blanks out a Required Field during Editing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38246]
## User Story
As a Veteran, when I am editing my personal info, I would like to know if I am missing any required information so that I can make sure I have provided the information.

## Related Documentation
TBD

## Description/User Workflow
- Given I
   - Am editing my demographic, NoK, or emergency contact info as part of performing pre-check-in 
- When I
   - Clear or blank out a field that is required
- Then I
   - See a message and visual indicators that tell me that the field is required
  -  Cannot save the information until I have provided the required information

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by loripusey** [comment]
@brianseek validate if we get this for free and if we do then close the ticket

**Comment by zach-park** [comment]
As an additional detail, the ‘mailing address’ form group is only a required group. For any other optional form groups (such as home address), their required forms within each group are can be disregarded by clicking cancel on the edit page.

**Comment by brianseek** [comment]
![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287(Pixel 5) (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/0c752a9a-580a-465a-bba7-29cb55ef9782)
![Screen Shot 2022-03-24 at 4.01.16 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/66707196-9d1b-44a0-857f-7872eff80ae0)

**Comment by brianseek** [comment]
@zach-park this is ready for UX review. I have included some screen shots showing various required error states. The only one that doesn't have a required error state is the Relationship select list, and that is because we don't have a blank option on that field.

**Comment by zach-park** [comment]
@brianseek , here is the recommendation from the UX audit:
[EC Required fields validations](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/A0F45B51-1305-4FEA-9D70-A8201A4E63B0): https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/A0F45B51-1305-4FEA-9D70-A8201A4E63B0
(Cc: @loripusey @kristenmcconnell )

**Comment by brianseek** [comment]
Thanks @zach-park! I'm capturing these notes for when/if we pick back up on edit. One thing to note for future reference, the vertical line on the error fields goes away at mobile screens sizes. That's why it is missing.

**Comment by zach-park** [comment]
Hi @brianseek , just wondering, what resolution was the screen captured at? I was curious because the VA profile staging seems to show in the 320 widths responsive. I'm not sure if this ticket will be parked, but I wanted to mention it so that it can be followed up. Thank you!

**Comment by sarahknoppA6** [comment]
@brianseek is there a way to notate what needs to be fixed, or was the fix completed so this could be potentially picked up later?
