### ISSUE TITLE
[FE] Enable Events V2 feature flag

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38251]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on relevant date, time, keywords, etc.

### Background
[Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md)
[Link to VA.gov page](https://www.va.gov/outreach-and-events/events/)
[Recurring events CMS functionality deck (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/files/7213329/Recurring.events.pdf)

### Tasks
- [x] When tickets #38145, #38147,  #38157 are completed flip feature toggle to "ON"
- [x] Test and validate Events V2 on production env
- [x] Review and close ticket once work is completed

### Acceptable Criteria 
- [x] Events V2 is live with updates applied
