### ISSUE TITLE
[FE] Move Language Toggle on All Check-in & Pre-Check-in Pages 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38260]
## User Story
As a Veteran or Veteran relative whose primary language is Spanish, when I do check-in or do pre-check-in, I would like to have an option to see messages, questions, and prompts in my native language so that I can understand the information.

## Description
- Given I
   - Receive an invitation to perform CI or PCI
- When I
    - Access any of the CI or PCI pages (including login)
    - Choose Spanish as my language 
- Then I
   - See all text in Spanish

## Tasks
- [ ] Move toggle to top of page and adjust to match [this ](https://github.com/department-of-veterans-affairs/vets-website/blob/d5db5ea77bc9a8ca0643a1b091fd00f8017e9018/src/applications/static-pages/i18Select/I18Select.js)
     [Example](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] UI toggle is at the top and matches the wireframe
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
We should ensure that all text used for editing in appConstants is translated as part of this.

**Comment by loripusey** [comment]
@acrollet were these values given to UX to bundle with their submission to the State Deparment?
cc: @kristenmcconnell

**Comment by loripusey** [comment]
we may not need this ticket @acrollet @kristenmcconnell

**Comment by loripusey** [comment]
@brianseek After discussions with UX this morning, it was decided that, since it will take a while to create the new Design System toggle component and get it through a DS & Accessibility review, we will move forward with using the existing DS component (which uses links to toggle) so that we can get this into production as soon as we get the translated content back from the State Department. We will then work on the new component, get it through reviews, and swap out the existing component for the new component. So I believe this ticket is unblocked.
cc: @sarahknoppA6 @kristenmcconnell

**Comment by brianseek** [comment]
Ready for UX review, see screen shots for english and spanish active versions with breadcrumb and no breadcrumb
![Screen Shot 2022-04-28 at 8.33.49 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/58478415-6db8-4666-80e3-1e01e6d0a490)
![Screen Shot 2022-04-28 at 8.33.59 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/3f5c10e0-4ad1-44c1-bb89-75744c104e23)
![Screen Shot 2022-04-28 at 8.34.25 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/a110725f-947b-4622-ab43-57574678d0d1)
![Screen Shot 2022-04-28 at 8.34.36 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/370ce89e-a65e-4c16-a8b3-f2f21fc4a96f)

**Comment by kristenmcconnell** [comment]
@ytsaoca

**Comment by ytsaoca** [comment]
@brianseek Looks great. Thanks!

'cc @kristenmcconnell
