### ISSUE TITLE
Form  2346 Features

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3826]
## User Story:
As a Back-end developer, I need to make sure my forms' features meet the VA standards so that I can follow best practices.

## Tasks
- [ ] The steps that must be done by the team to complete the acceptance criteria.
- [ ] Find form features standardization file on GH

## Acceptance Criteria:
- [ ] The requirements that must be met in order to mark this user story as completed.
- [ ] confirm with team that forms are standardized
- [ ] create documentation on GH

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wygonikGCIO** [comment]
Add @mr0sari0
