### ISSUE TITLE
[Research] - Auth Profile - MyHealtheVet Research - Write research plan for Veteran interviews

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38277]
## Background

 Write research plan for Veteran interviews

## Tasks
- [x]  Write research plan for Veteran interviews
- [x] Get feedback from MHV UX team
- [ ] Get feedback from Health apartment team

## Acceptance Criteria
- [ ] Tasks above are complete

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @andaleliz !

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! I have completed drafts of the [research plan and convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/mhv-profile-research/mhv-user-interviews) for Veteran interviews.

I went ahead and recruited an internal MHV user pilot participant scheduled for late Tuesday afternoon so I can get a more accurate sense of how much time the session will take. Ideally, I'd like to get feedback on VA.gov profile too, but I think it's a lot to ask people to talk through MHV, a card sort + another site. I'm planning on evaluating in the session whether or not a person has energy to do it (and you'll see that in the conversation guide.

Also want to share some of my thinking for the card sort:

- This will help us figure out where to put health items (profile or health apt) more than just asking about it
- I included a mix of obvious profile cards so it doesn't bias them toward a profile or health section one way or the other
- I will want to check w/ Meg's team to see if there's anything missing from their perspective
- Do we want to include something about co-pays here too?

Thanks in advance for your feedback!

**Comment by Samara-Strauss** [comment]
## Research plan

### Recruitment criteria 

> At least 50% must identify as having a cognitive consideration.

I would be clear what you mean by this unless you're sure Perigean will understand what you mean by "cognitive consideration".

> Team roles

You can invite Adam and Tom as optional since they are on the profile team.

Otherwise, this is excellent! Great job!

**Comment by Samara-Strauss** [comment]
## Conversation guide

### Task 2: Review My Profile - 10 minutes

> Talk to me about what you see on this page.

This is really nit-picky, but I'd change this to something like "Tell me about how you use this page." Since we are assuming they are already familiar with this page (or we'll quickly find out if they are not), I don't think first impressions are important to us. I'd rather hear directly how they use this page before going into the specific questions about each field.

> Why are some of the boxes greyed out?

Given that we don't plan to move over any of the greyed out fields, what is the goal in asking this? Is it to confirm with participants that this, in fact, is not helpful information to have?

Otherwise, this is great! Let me know when the card sort is together. I'm curious to see what you include in this. I think we'll get a lot of helpful insights from these interviews, and that they'll resolve the final open questions we have. Nice job!!

**Comment by andaleliz** [comment]
Hi @Samara-Strauss thanks for your feedback! Here's the [link to the card sort](https://p3y41d84.optimalworkshop.com/optimalsort/k3774wsz/sort). I thought I had that in there already, my bad.  As I mentioned, I also run this by the health apt team to be sure it aligns with the items they have questions on.

I'll update the recruiting criteria to be more specific, and include age - that was an oversight. Good catch!

>This is really nit-picky, but I'd change this to something like "Tell me about how you use this page." Since we are assuming they are already familiar with this page (or we'll quickly find out if they are not), I don't think first impressions are important to us. I'd rather hear directly how they use this page before going into the specific questions about each field.

Makes sense to me, happy to make that edit.

>Given that we don't plan to move over any of the greyed out fields, what is the goal in asking this? Is it to confirm with participants that this, in fact, is not helpful information to have?

Some of the greyed out fields are first name and last name, so we will have that information but not in a field format. My goal in asking this is to get feedback on not being able edit something, and if its frustrating that they can't, or if they don't care and understand why they can't edit that kind of information in their profile.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz @Samara-Strauss is this ticket ready to be closed or is it still being worked on?  Thx!

**Comment by andaleliz** [comment]
@Samara-Strauss do you have any updates to the card sort? If not I think we can close this out.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz @Samara-Strauss I am going to close this for now so I can complete the sprint report, but if you determine that it's not complete, LMK

**Comment by Samara-Strauss** [comment]
@andaleliz I am so sorry I missed your comment from a couple days ago!! This was a total oversight on my part. We can totally consider this done, but I do have a couple suggestions:

- Can you change it from "My VA Profile" to "My VA.gov Profile" so it's clearer that this is a website profile section? I am sure you'll explain that, but otherwise it kind of sounds like "My VA Profile" is some file that exists somewhere in the VA.
- Can you change "Your health power of attorney" to "Your power of attorney"? People might be able to have more than one POA across the VA -- I'm not sure -- but I am curious if people automatically associate that with health care or not regardless of the "health" label.

**Comment by andaleliz** [comment]
@Samara-Strauss no worries!  I can make both of these edits, they make sense. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thank you both!!
