### ISSUE TITLE
[Research] - Auth Profile - MyHealtheVet Discovery- Draft Conversation Guide for Veteran interviews

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38273]
## Background

Draft conversation guide for MyHealtheVet/VA.gov Profile research for Veteran interviews

## Tasks
- [ ] Draft conversation guide
- [ ] Review conversation guide with PM
- [ ] After PM review, review w conversation guide with PO

## Acceptance Criteria
- [ ] Draft conversation guide
- [ ] Review conversation guide with PM
- [ ] After PM review, review w conversation guide with PO

**Comment by MarciMcGuireGCIO** [comment]
Conversation draft is written
