### ISSUE TITLE
Include backend unit tests for the two new API calls

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3827]
## User Story:
As a back-end developer I need to create standard Rails test automation to validate the new Controller actions return 200 SUCCES HTTP responses, and a JSON payload.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Use the Rails and RSpec generators to scaffold test cases for each API controller action
- [ ] Add specific test data to the scaffolded test cases
- [ ] Run the cases using the standard Rails Rake test task at the command line

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] verify the tests pass as reported by Rake test:all

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
duplicate ticket contains work
