### ISSUE TITLE
Update Architecture Diagrams for the ATO

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38276]
## Problem Statement
As the VA, we need to generate documentation for our ATO on which Ed Teeple is working, Here is the ask from his email:

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/b428a738-0d79-42d2-abcf-ccec01c307ec)

## Example Diagrams
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/82d2d769-6155-4dd2-a1e4-dcd0e8cd2463)

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/81318ac4-31b7-49e8-9e31-f7e35dd3be09)

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/92fe3b16-1139-4b8f-9159-f328d0153c6b)

## Task
- [ ] Generate Architecture Diagram
- [ ] Generate Network Diagram
- [ ] Generate Data Flow Diagram (can be same as the Network Diagram depending on how the diagrams are done)
- [ ] Generate Environmental Statement

**Acceptance criteria**
- [ ] Architecture Diagram is completed using the above example
- [ ] Network Diagram is completed using the above example 
- [ ] Data Flow Diagram is completed using the above example (may be same as Network Diagram)
- [ ] Environmental Statement is completed using the above exampleprovided
- [ ] All documents are made available and provided to Ed Teeple

**Comment by loripusey** [comment]
Diagrams might be needed for the ATO, @randomsync please touch base with Stephen on requirements.

**Comment by randomsync** [comment]
So far, I have been working on sequence and C4 diagrams because those are most useful to the team to understand the overall context and information flow. Once those are done, I can work on the ATO required diagrams.

@loripusey, should we create a separate ticket for that?

**Comment by loripusey** [comment]
If you can complete all of the diagrams, then I say we add the sequence and C4 diagrams as AC to this ticket. If you will need another sprint then we should create a new ticket for the diagrams you are working on.

**Comment by loripusey** [comment]
@randomsync Based on email from Ed Teeple, it appears that our HW/SW Inventories, scans, and diagrams should be stored on our private GitHub (i.e. NOT public)
cc: @sarahknoppA6 @stephenBarrs

**Comment by loripusey** [comment]
Target is to have all completed diagrams to Ed Teeple no later than April 15, however, please share drafts ahead of time if possible.
cc: @sarahknoppA6 @randomsync @acrollet

**Comment by sarahknoppA6** [comment]
There is an architecture diagram sync meeting this Friday. Please @ me ON SLACK if you need an invite.

**Comment by sarahknoppA6** [comment]
Adrian to add some url shortener stuff in here before ticket is closed.

**Comment by acrollet** [comment]
I added an overview and container diagram [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/README.md#url-shortener) and more detailed documentation with sequence diagrams [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/url-shortener).

**Comment by sarahknoppA6** [comment]
Stephen has reviewed the diagrams and Ed has confirmed he got what he needed. We can close this for now and open a new ticket if needed.
