### ISSUE TITLE
Do first back-end dev walkthrough to familiarize with Access VA

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3828]
## User Story:
As a Back-end Developer, I need to complete an initial walk through of Access VA with John Paul's designated Software Engineer so that I can start getting an understanding of the Access VA feature set and programming procedures.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Set up a meet with John Paul's designated Software Engineer
- [ ] Participate in the engineer's walk through of Access VA

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Complete walk through
- [ ] list salient points in a brief e-mail to our dev team
- [ ] bring initial understanding to team discussions where applicable

## Next Steps:
- N/A

##Blockers / Dependencies 
- Request Meeting with JP's designate

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team**: product support
- [ ] **Labeled with Practice Area**: `backend`,
- [ ] **Labeled with Type**: `discovery`,

**Comment by wygonikGCIO** [comment]
add @mr0sari0  and @mojaray2k
