### ISSUE TITLE
[Product] PM handoff Checklist - Public Websites 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38282]
### Description 
Public Websites team is one of the best teams in VSA, this ticket is to help provide a quick reference checklist in support of PM handoff and team transition.  Items listed below are action items that should be completed NLT 3/14.  Thanks for taking on the team and good luck with close out on 4/7/2022. 

### Checklist Items 
- [x] Set new meeting invites for Team (Stand Up on M, W, T.  Slack up on T, F) (Meet w/Dave Tuesday 5PM EST)
- [x] [ToT slide updates](https://dsva.slack.com/archives/C031S5G29LP/p1646681404047049) (Shared with Search and Discovery.  PW team completes side, passes to S+D for update, posts final to #team-of-teams-slide-collection)
- [ ] Analytics Runbook (Working - Domo and GA links for tracking products)
- [x] Email link-in for Linda on items in-flight (CLP-Vote, Deep Link Issue, Redirects/Intake processes)
- [x] Team Transition Documentation (Working - Tickets are in sprint, intended to bleed over to next sprint in support of team close out actions)
- [x] Set [Sprint69](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37951) and [Sprint70](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38099) Sprint priorities tickets for team planning. 
- [x] [Team grooming document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Grooming.md) ISO grooming session programmed for 3/16/2022.
