### ISSUE TITLE
Add "upload" functionality to COE prototype

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38285]
## Background
To support usability testing of the 26-1880 and "your COE" tools, the UXPin prototype needs simulated upload functionality added.

### Considerations
Existing prototype has various disconnected states and screens.
- [UXPin prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312)

### Tasks
- [x] Add file "upload" functionality to the "Your COE" tool
- [x] Add file "upload" functionality to the 26-1880 form
- [x] Add faux PDFs for COE and LGY letter documents

### Acceptance Criteria
- [x] The COE prototype (UXPin) has limited functionality for the "upload" feature

**Comment by sporeboy** [comment]
Simulated upload functionality is available in COE prototype. Link to in-line uploader: [(UXPin link)](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137651934)
