### ISSUE TITLE
Moderate COE usability testing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38284]
## Background
We'll be conducting usability testing of the LGY Certificate of Eligibility features, 26-1880 and the "your COE" tool. Five sessions are scheduled the weeks of March 7 and March 14, and they'll be conducted remotely via Zoom.

### Considerations
This is the second round of usability testing. The UXPin prototype will be used.
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-2/coe-researchplan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/usability-testing-2/coe-conversationguide.md)

### Tasks
- [x] Add upload "functionality" to the prototype
- [x] Conduct pilot session
- [x] Conduct sessions with Veterans

### Acceptance criteria
- [x] Usability study complete--all sessions conducted or canceled
