### ISSUE TITLE
Add VBA mock debt to MCP user

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#38295]
## Issue Description
As we implement the combined debt portal we will need to have a test user that has both VHA and VBA debt

---
## Tasks
- [ ] Create betamock data file with VBA debt for a medical copay user

## Acceptance Criteria
- [ ] One user can log in and have both VBA and VHA debt
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
