### ISSUE TITLE
Remove Description Dropdown for COE Uploader (in form)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38299]
## Background
Bc this is multiple files, we need to remove the description field bc it doesn't account for more than one doc

## Considerations
Ensure there isn't a large amount of white space where the dropdown was

## Tasks
- [x] remove field form FE
- [x] update schema to match
- [x] go through PR hell to complete
- [x] update the build in `vets-json-schema` and bump the version

## Acceptance Criteria
- [x] no more descriptions needed within the form for multiple docs to be uploaded 
- [x] A PR has been requested for merging, if needed
