### ISSUE TITLE
Complete tutorial on new forms list

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3829]
## User Story:
As a ___Front-end Developer_______, I need ___to complete the turorial on creating new forms_______ so that I can ____my code follows best practice______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Complete tutorial

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Complete tutorial

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wygonikGCIO** [comment]
Amen/Maherial  "Next Step"s be added to this ticket.  The team is also looking at adding "Hours" to each Task. Please ball park the hours.  (i.e. Task: interviews: 10 hours)
