### ISSUE TITLE
Launch FSR Notification Copy in Production

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#38296]
## Issue Description
Once copy for FSR notification submission has been approved we need to update the copy in VA Notify portal and set it up for production

---
## Tasks
- [x] Update template in VA Notify DMC portal
- [ ] Flip the fsr notification feature to on

## Acceptance Criteria
- [ ] When a veteran submits an FSR in production they will receive a notification
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
3/29- Jill has confirmed that the VBA privacy officers are content with the proposed copy for the FSR email notification. This issue is therefore unblocked and ready. cc: @ScottyRJames

**Comment by ScottyRJames** [comment]
Launching live Monday (05/09/2022)
