### ISSUE TITLE
Connect BE Data to Display Various Docs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38293]
## Background
Now that the BE has completed their part, the FE needs to connect some dots to get this onto the page for the Veteran to see.

## Considerations
"The COE documents list"
Might not need redux, but call internally from state

## Tasks
- [x] Jerek and Amanda: controller is setup, 
- [x] resolve 503 errors from the BE
- [x] Share shape of the payload over to Jerek

## Acceptance Criteria
- [x] Documents from LGY are displayed dynamically on the FE for the VA
- [x] A PR has been requested for merging, if needed
