### ISSUE TITLE
Add COE to the Single App Build

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38297]
## Background
This will dramatically increase productivity

## Considerations
May not include ALL of our apps, but focus first on ones that are ready to go (COE)
Req list: https://depo-platform-documentation.scrollhelp.site/developer-docs/Single%2Fgrouped-application-builds.2031484979.html#Single/groupedapplicationbuilds-Addinganapplicationtotheallow-list

## Tasks
- [x] Add COE to the Single App Build
  - [x] run some checks
- [x] reach out to platform to be added (for where to send errors and what app to be added)
  - [x] get on the allow list
  - [x] verify requirements are met
  - [x] pass some tests

## Acceptance Criteria
- [x] COE has been added
- [x] A PR has been requested for merging, if needed
