### ISSUE TITLE
[FE] My VA: Health care - unread msgs vs no messages/never used MHV message center

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38304]
## Background
During our copy and designs style change for the Health care - unread messages box, we found that the conditional display logic may be too complex and can be pared down to a simpler condition.

**Currently in Production**:
- The "Send a secure message to your Health care team" message ONLY appears when the user has never used the messaging tool
- The "You have n unread messages. View your messages"  message appears when the user has sent/received messages in the past.  
     - This **includes** when the user has zero unread messages (You have 0 unread messages. View your messages)

With the recent style change to a warning alert, it does not make sense to be used when there are zero messages.
Also, initially the logic was supposed to have "Send a secure message to your health care team" when there are zero messages.

**Proposal**
We need to review the current conditions in the code, and see if we can simplify it to the following:
- **[Display text message in Link List](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/oYxq8K2)** when there are zero unread messages in the MHV messaging tool (including if the user has never used the messaging tool)
- **[Display the warning alert](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/Vrq10bg)** "You have _n_ unread messages. View your messages" when there are unread messages in the MHV messaging tool.

## Tasks
- [ ] Review current conditions in the codebase for the health care messages
- [ ] Determine what changes can be made without impacting other sections or code functionality
- [ ]  If the effort is small, the changes can be made within the scope of this ticket
     - Code changes can be implemented behind the Payment Info feature flag, and released along with all other related changes when we launch Payment Info.
- [ ] If the effort is significant or the changes will impact other functionality, an additional ticket can be created and scheduled.

## Acceptance Criteria
- Code changes for simplification (less dependencies and conditions) have been determined.

**Comment by hdjustice** [comment]
Validated that the copy has been updated for both users never using messaging tool and zero unread messages "Send a secure message to your health care team". (user 41 & 36)
Pending validation of verbiage change on unread messages (need an account with unread messages)

**Comment by hdjustice** [comment]
No staging users found with unread messages.  Since this is a copy change and the PR reflects the change needed, we will accept and close this ticket.  I will monitor this change during our UAT sessions for the payment info, since the changes will be applied at the same time .
