### ISSUE TITLE
Implementing Error Handling for the table

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3830]
## User Story:
As a  Front-end Developer, I need to implement client side error handling for Form 2346 components so that the Veteran can fix input mistakes made and I can troubleshoot client side problems that arise.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_

**Per Component:**

- [ ] Look up the component that needs error handling on the docs.  Estimated time: 30 min
- [ ] Implement code suggested on the docs.  Estimated time: 1 hour
- [ ] Test that error handling works. Estimated time: 1 hour

## Next Steps

- [ ] Look up the component that needs error handling on the docs
- [ ] Implement code suggested on the docs
- [ ] Test that error handling works

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Run Q&A testing to ensure that the correct error is fired for the correct scenario

## Blockers

- Determine which components will be on Form 2346
- Design mock up of Form 2346

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wygonikGCIO** [comment]
Amen/Maherial can "Task" and "Next Step"s be added to this ticket. The team is also looking at adding "Hours" to each Task. Please ball park the hours. (i.e. Task: interviews: 10 hours)

**Comment by mr0sari0** [comment]
Updated user story, tasks, next steps, blockers, and estimated times of completion.

**Comment by mr0sari0** [comment]
Update blockers to include a design mock up of 2346.
