### ISSUE TITLE
Create Unit testing for the MVP

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3831]
## User Story:
As a ___Front-end developer_______, I need ___to unit test my code_______ so that I can ____ensure me build is compatible and meets expectations______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Defined URL/Router
- [ ] need list of components

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Given that the test results are compliant
- [ ] When errors are displayed when issues accrue
- [ ] Then success will produce no errors when ideal process is conducted

## Next Steps
- Push to stage.

## Blockers
- Components list needs to complete
- Routing needs to be determine (IA)
- Redux state testing.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
