### ISSUE TITLE
HLR: Fix submitted profile data length

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38317]
## Description

The Higher-Level Review form uses the profile email, mobile phone and mailing address. The lengths of these values don't all match the HLR schema ([Sentry error with invalid `addressLine3` length](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:064609d255d9452f8feb2d252ab00c10/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AClient%3A%3AErrors%3A%3AClientError%3A+the+server+responded+with+status+422&project=3&query=issue.id%3A74396&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1))

```js
{
  errors: [{
    code: 142, 
    detail: '***************' did not fit within the defined length limits,
    meta: {
      max_length: 10
    },
    source: {
      pointer: /data/attributes/veteran/address/addressLine3
    }, 
    status: 422, 
    title: Invalid length
  }]
}
```

Because of this inconsistency, changes for all submitted email, phone and address need to be truncated to fit these requirements

## Tasks

- [ ] Truncate profile email, phone and addresses before submitting to Lighthouse to ensure they match the schema
- [ ] All tests passing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
