### ISSUE TITLE
[SW-Content] Review current Sitewide content documentation and artifacts [CE] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38315]
## Story
Process, checklists, intake, and customer request documentation needs to be archived and available in Sitewide content library.

## Task(s)
- [x] Review all current process, checklist, and support documentation that needs to saved in library.
- [x] Document what will or needs updates to bring to current status.
- [x] Create list of gaps in process or documentation.

## Acceptance Criteria
* Current documents are moved to SharePoint or shared folder
* List all needed updates and gaps that need documentation created.

**Comment by RLHecht** [comment]
@bethpottsVADEPO We already have that documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/making-updates-to-welcome-kit.md

But good idea for me to reach out to Justin to make sure that he's reaching out to you going forward. There are a few other stakeholders who sometimes only message me, so I will let them know as well to contact you until there's a group email.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks so much for covering bases, I really appreciate it.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the operations doc we talked about writing up yesterday. Let me know if you think I've missed things. I'll keep adding to it over the course of this sprint as we think of more. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/sitewide-content-team-operations.md

**Comment by bethpottsVADEPO** [comment]
Thank you so much for putting this together, @RLHecht! I'll take a look.

**Comment by RLHecht** [comment]
Also adding here Selina's document for swapping the videos on the COVID CLP: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md
