### ISSUE TITLE
[UNPLANNED] Resolve error from `ServiceProvidersText` component

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#38327]
## Background
When using the `ServiceProvidersText` component, the component emits an error because in React, children within a list must have unique `key` props. We simply need to add a key to the jsx element that needs it.

## Considerations
![image](https://user-images.githubusercontent.com/13838621/157546023-6a4a4995-7377-41f3-84ac-f6d80324397c.png)

## Tasks
- [ ] Update the `ServiceProvidersText component

## Acceptance Criteria
- [ ] `ServiceProvidersText` component no longer emits the key error
- [ ] A PR has been requested for merging, if needed
