### ISSUE TITLE
NOD: Fix submitted profile data length

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38326]
## Description

The Notice of Disagreement form uses the profile email, mobile phone and mailing address. The lengths of these values don't all match the [NOD schema](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/config/schemas/v2/10182.json)

Because of this inconsistency, changes for all submitted email, phone and address need to be truncated to fit these requirements

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38317

## Tasks

- [ ] Truncate profile email, phone and addresses before submitting to Lighthouse to ensure they match the schema
- [ ] All tests passing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
