### ISSUE TITLE
User case for Medical Device

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3832]
## User Story:
As a Back-end Developer, I need to create user case so that I can map out the different use case flows for the Medical device.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Meet UX designer
- [ ] Meet with Front-end developers
- [ ] Determine VA precedence for use case

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Dev team's use case match Design teams work flow
- [ ] Use case documentation is in [GH]   

##Next Steps
- [ ] Document each system needed for each case. 

##Blockers
- [ ] May be scheduling conflicts

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
