### ISSUE TITLE
Use case storyes

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3833]
## User Story:
As a __Front-end Developer________, I need ___to create user cases_______ so that I can ___determine each actor and functionality need for each actor_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Create diagram 1hr
- [ ] Define actors 1hr
- [ ] Determine each Use case story 1hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Documentation in GH

## Next Steps
- Create a content inventory document
- Define requirements
