### ISSUE TITLE
Deleted story

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3834]
## User Story:
As a ___designer_______, I need __to create a persona of my end user________ so that I can ___build empathetic approach to our solution_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Get quantitative data from GA
- [ ] Get quantitative data from DLC systems
- [ ] Hold Veterans interviews to gather qualitative data
- [ ] etc

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Create a person based off of real date about the Veterans using the device
- [ ] 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
redundant  - closing
