### ISSUE TITLE
Reorg Renaming [Release Tools Team]

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#38348]
**Issue Description**
The recent Platform team reorg has been designed to reduce cross-functional team dependencies as well as create more accurate team names aligning to the products they support and own.

The team name has changed from Operations to Infrastructure Team, this will need to be updated in our documentation.

**Tasks**
- [x] Rename Confluence Space  (Confluence should automatically update links)
- [x]  Rename on Confluence pages
- [x] Update Platform Website (as needed)
- [x] Update Orientation materials/PowerPoints
- [x] Update slack channel name. 
- [x] Need to determine new slack channel name (platform-release-tools)
- [ ]  Github team label 
- [ ] Update Github templates with new label
- [ ] Github FE team rename to Release Tools Team
- [x] Update Zenhub board name
- [ ] Uncover other places/spaces where FE team name would be listed.

- [x] Update Roadmap/Vision
- [x] Team member Slack profiles
- [x] Some items pulled from the list located in this Team Restructure document by Andrea in Step 4.

**Acceptance Criteria**
- [ ] Documentation will refer to the team as Release Tools Team
- [x]  Teams are able to reach out to Release Tools Team through slack and slack bot

**Comment by timwright12** [comment]
@laineymajor I updated support bot this morning

**Comment by rmessina1010** [comment]
Completed. Closing
