### ISSUE TITLE
VANotify Edge Case Dashboard - Data QA

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38344]
## Issue Description
As we roll out the VANotify edge case dashboard, we need to make sure that our data is accurate and trustworthy. 

---
## Resources
- [VANotify dashboard draft](https://va-gov.domo.com/page/2040841289)
- [VANotify build & QA tracker](https://docs.google.com/spreadsheets/d/1_rUv2kAsWtfdg-vIJAAHyV8kb5_hAg8GZHK5g_baKmg/edit#gid=0)

---
## Tasks
- [ ] Verify that data formats are correct
- [ ] Validate the data is what is expected (does the info collected measure what it's supposed to measure and does it align with GA?)
- [ ] Identify & document invalid values
---
## Acceptance Criteria
- [ ] The production VANotify Edge Case Dashboard in Domo has accurate and trustworthy data and is ready to be shared with stakeholders.

**Comment by jennaouellet** [comment]
Just waiting on Domo data refresh for the last two items, will update the QA template below once those are confirmed to match GA.


### QA


### Highlights

Chart title | Assets | Pass / Fail
-- | -- | --
Total notifications sent | BigQuery metric - SELECT SUM(SuccessfulEmailAddressRetrieval)| :green_circle: PASS
Notification delivery rate |BigQuery metric - SELECT AVG(CAST(SuccessEmailDeliveryRate as int))|  :green_circle: PASS
Email opens by user | [Custom segment](https://analytics.google.com/analytics/web/template?uid=zuTl_gGdTny17cfpnfYBeg) |   :green_circle: PASS


###Task Completion

Chart title | Assets | Pass / Fail
-- | -- | --
Total notifications sent | BigQuery metric - SELECT SUM(SuccessfulEmailAddressRetrieval)| :green_circle: PASS
Delivery rate by campaign |BigQuery metric - SELECT SUM(SuccessfulEmailDelivery) / SUM (SuccessfulEmailAddressRetrieval), template_name GROUP BY template_name | :green_circle: PASS
Top reasons emails not retrieved| BigQuery metric - SELECT SUM(NotFoundInMPI), SUM(MarkedAsDeceasedInMPI), SUM(NoVAProfileIDInMPI), SUM(NoEmailVaProfile), SUM(NotFoundInVAProfile)| :green_circle: PASS




### Ease of use

Chart title | Assets | Pass / Fail
-- | -- | --
Total users who opened emails| [Custom segment](https://analytics.google.com/analytics/web/template?uid=zuTl_gGdTny17cfpnfYBeg) | :green_circle: PASS
Avg. Campaign opens per user| [Custom segment](https://analytics.google.com/analytics/web/template?uid=zuTl_gGdTny17cfpnfYBeg) / [Filtered report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220220&_u.date01=20220227&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:email,analytics.eventAction:open)| :green_circle: PASS



### Findability

Chart title | Assets | Pass / Fail
-- | -- | --
Claims & Appeals - VANotify users |  [Custom segment](https://analytics.google.com/analytics/web/template?uid=hPkSP-KeQI-fEBLxjhMsrw) | :green_circle: PASS
Manage VA Debt - VANotify users |[Custom segment](https://analytics.google.com/analytics/web/template?uid=goyuGCMjTuC_DegE_Luzvw) | :green_circle: PASS
VA Profile - VANotify users | [Custom segment](https://analytics.google.com/analytics/web/template?uid=ZhMHVJCiRJSW_qyqA4PqBQ) | :green_circle: PASS
Avg. session per user for VANotify source | [Custom segment](https://analytics.google.com/analytics/web/template?uid=yV4VXp1iTRSMiwL6d9UQ0Q) | TBD
Bounce rate for VANotify sessions | [Custom segment](https://analytics.google.com/analytics/web/template?uid=yV4VXp1iTRSMiwL6d9UQ0Q) | TBD

**Comment by jennaouellet** [comment]
Data QA has been complete and everything looks good! Closing this ticket out.
