### ISSUE TITLE
Staging Review [1095-B]

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#38351]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] CMS Preview link

[Here](http://preview-prod.vfs.va.gov/preview?nodeId=44346)

- [x] Product outline 
 
 
[Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/1095B-Tax-Form-Product-Outline.md)

- [x] Release plan with the "Planning" sections completed 
[Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/product/1095b-release-plan.md)

### Content artifacts 

- [x] Your product’s content source of truth
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
- Link to [IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37639)
- Link to [Content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38448#issuecomment-1093084787)
- [Page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/image%20(3).png)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs [Here](https://dsvavsp.testrail.io/index.php?/projects/overview/50) 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [x] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] Document in your product folder that indicates all required checks from the [accessibility staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.

- [x] List of known issues

•	The 1095-B PDF doesn't pass the "regularity" check on Adobe's Accessibility Checker, but it does pass the test in other checkers. 

•	Issue 2

•	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Confirming that the staging review is scheduled for 3/22 at 11:30am ET

**Comment by jimuhh** [comment]
@JordanSWhite , @chaseakirby --  I understand that the site can't go to staging environment without those PRs. Unfortunately I will be OOO the whole week starting Monday, 4/4 so won't be able to attend Friday's staging review or review the site once it's posted there. 
However, I see you have been working closely w/ Mikki N on this, so hopefully she's managed to head off any potential issues in advance. 
Thanks!

**Comment by allison0034** [comment]
@JordanSWhite do you have a link to a login we can use? They staging credentials dont seem to work.

**Comment by shiragoodman** [comment]
FYI the review has been moved to 4/12 at 11am ET. (sorry, meant to post yesterday)

**Comment by ddzz** [comment]
@tameracorson do you have any QA artifacts for this feature?

**Comment by CherylEvans** [comment]
@tameracorson Do you have a Content Source of Truth available?

**Comment by tameracorson** [comment]
redirect above... @JordanSWhite @stephte can you answer @CherylEvans

**Comment by JordanSWhite** [comment]
@CherylEvans By source of truth, are you referring something like a content folder in Github?

**Comment by shiragoodman** [comment]
@JordanSWhite we ask that teams provide a "content source of truth" because a lot of the times, the content isn't up to date in a prototype or flow. If the content is up to date in CMS Preview, please confirm. @CherylEvans can verify the content there.

**Comment by JordanSWhite** [comment]
@allison0034 try it now and let me know if it works.

**Comment by JordanSWhite** [comment]
@CherylEvans Use the first 9 links here as the sources of truth (I hope that's helpful) https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/1095b-tax-form/design/wireframes

**Comment by allison0034** [comment]
@JordanSWhite it is not working. I tried 2 accounts with the CMS link and it does not work, but they work on staging.va.gov

**Comment by JordanSWhite** [comment]
@allison0034 You can use [this link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/image%20(2).png) for the Unauth, and [this link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/03.22.2022_1095-b_Auth%20state_Desktop.jpg) for Auth.

**Comment by briandeconinck** [comment]
@JordanSWhite Like Allison, I'm unable to get any test account credentials to work on the URL provided. For the accessibility review, it's important for me to be able to review the markup and test keyboard and assistive technology interactions with the page. Can't do those things with just the images.

Are there other testing credentials I can use to complete my review?

**Comment by JordanSWhite** [comment]
@DanielleThierryUSDSVA Wanted to loop you in here because others from Collaboration Cycle can't access the preview link. I know that the drupal element won't show up in staging, so we can't use that as a link, but if you have any guidance here, that'd be much appreciated.

**Comment by JordanSWhite** [comment]
@allison0034 The 9 screens I provided Cheryl were all-encompassing, in terms of content that would appear not just on the pages in an ideal state, but also for failure or potential error messages. If those are unnecessary, and the links I provided you work as a content source of truth, then I'm fine with that. We just didn't have a single document with all of our content, so I wanted to make sure I provided everything.

**Comment by allison0034** [comment]
@JordanSWhite ok thank you. We will need to review any new or changed pages so if those 9 pages have changes then we would review them all.

**Comment by briandeconinck** [comment]
@DanielleThierryUSDSVA Speaking for me, the issue is with logging in from that preview page. I can view the page just fine when connected to the network, but I can't log in to review the authenticated experience on the page.

**Comment by JordanSWhite** [comment]
@briandeconinck @allison0034 @DanielleThierryUSDSVA Ah, then I misunderstood the issue. That might be on our end, I'll check with the team.

**Comment by JordanSWhite** [comment]
@allison0034 the only change was made to the unauth page, which can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/image%20(3).png), and instead of using the 9 pages, I would instead use the first four

**Comment by allison0034** [comment]
Hi @JordanSWhite , sorry for all the messages but I want to make sure I am being specific. Below are the 4 pages that have changed correct?

[03.22.2022_1095-b_Auth state_Desktop.jpg](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/03.22.2022_1095-b_Auth%20state_Desktop.jpg)
[03.22.2022_1095-b_No 1095-B Available_Desktop.jpg](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/03.22.2022_1095-b_No%201095-B%20Available_Desktop.jpg)
[03.22.2022_1095-b_Success_Desktop.jpg](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/03.22.2022_1095-b_Success_Desktop.jpg)
[03.22.2022_1095-b_Technical error_Desktop.jpg](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/03.22.2022_1095-b_Technical%20error_Desktop.jpg)

**Comment by JordanSWhite** [comment]
@allison0034 updated in the Content section. Let me know if you need anything else!

**Comment by allison0034** [comment]
No design feedback. Thank you!

**Comment by jimuhh** [comment]
No IA feedback, thanks!

**Comment by shiragoodman** [comment]
Staging Review Zoom recording: https://us06web.zoom.us/rec/share/sGvrPnQ6kBfLSNrl1NAwcJoUiVyuGg6t4DoVGRSrETcVpqL0Q1mRDoaIr-GV7zI7._h_De9kksk9Aw5U5?startTime=1649775768000 (Passcode: s9ckd*h7)

**Comment by JordanSWhite** [comment]
@DanielleThierryUSDSVA I know you've been in contact with Tracey, so I wanted to loop you in here to the feedback tickets we received from Staging review. We've put courses of action for each ticket. Let me know if you have any questions (I've taken care of the first one). 

<div ccp_infra_version='3' ccp_infra_timestamp='1649796953902' ccp_infra_user_hash='3230381080' ccp_infra_copy_id='' data-ccp-timestamp='1649796953902'><html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">



Title | Issue | URL | Date | Resolved? | Action | Note
-- | -- | -- | -- | -- | -- | --
[Other] No VA.gov Experience Standard for the issue found. (00.00.2) | #39857 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39857 | 4/12/2022 | No | Comment on ticket that the decision to use a button vs text link has been confirmed and checked over by content team, not following typical pattern due to technical constraints |  
TTY text is not included in the link text. (00.00.3) | #39856 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39856 | 4/12/2022 | No | Sitewide content team to update | Sitewide content team format recommendation for TTY goes against what's proposed in terms of accessibility
[Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.2) | #39854 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39854 | 4/12/2022 | No | Sitewide content team to update and make plural |  
[Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.3) | #39853 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39853 | 4/12/2022 | TBD |   | "First sentence “profile’s” should be changed to a curly apostrophe, as opposed to a straight apostrophe. VA Style Guide   Please ensure all pages Content have curly apostrophes."
[Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.4) | #39852 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39852 | 4/12/2022 | No | Sitewide content team to add comma after Rhode Island and replace (District of Columbia) with "Washington, D.C." |  
[Content styleguide] Content doesn’t align with VA.gov voice and tone content principles. (05.04.1) | #39851 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39851 | 4/12/2022 | No | Sitewide content to change "All applicable pages: Change “It’s free to download.” to “You can download it for free.” Active voice" |  
[Content styleguide] The content has incorrect information. (05.06.1) | #39849 | https://github.com/department-of-veterans-affairs/va.gov-team/issues/39849 | 4/12/2022 | No | Sitewide content to update | "All applicable pages: Change ACA-also known as the health care law- to “-also known as the comprehensive health care reform law”- This is a more accurate depiction of what it is known as."



</body>

</html>
</div>

**Comment by DanielleThierryUSDSVA** [comment]
Hi @JordanSWhite. We'll review this feedback and determine what to implement. I can tell you, for example, that #39851 is incorrect. The original sentence is active voice and the collab cycle team is closing that ticket. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @JordanSWhite. I've updated the table above with follow-up notes on this. Thanks!

**Comment by tameracorson** [comment]
@shiragoodman I will work with the only remaining designer from the product to ensure we close loop with the individual staging tickets and then close the main staging ticket.   Sorry... 1095-B got pushed aside again.  Thanks for the reminder.

**Comment by tameracorson** [comment]
@here Ticket closed in lieu of new design and widget rebuild to be submitted under new ticket.

**Comment by CherylEvans** [comment]
Yes.  There is no real official definition for SoT available, but to my
understanding, it contains all of the Content for that particular product
touchpoint. If there is no SoT, I generally look for links to static
images, user flows, mockups, and prototypes that are available to review.

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

203-580-3529 | ***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member
