### ISSUE TITLE
HLR/NOD: Fix failed submissions

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38362]
## Description

We found 2 scenarios that need to be fixed:
- Veteran submitted an added issue with the same-day decision date (not sure how this is possible, but a Sentry error reported it)
- ~Veteran included a typographical apostrophe in the area of disagreement text. Lighthouse only accepts ASCII (windows-1252 format) when building the PDF (`pattern: /[^\u0000-\u0255]+/`)~  this will be fixed on the backend or Lighthouse

Slack discussion: https://dsva.slack.com/archives/CKUCFQAHJ/p1646862580567509

## Tasks

- ~Handle conversion of text to ASCII characters~
- [ ] HLR: Check/fix same-day decision date entry
- [ ] NOD: Check/fix same-day decision date entry
- [ ] Add/update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
