### ISSUE TITLE
[FE] C&L React Language Toggle Widget - Create Documentation / How To Guide 

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#38366]
## Description

Create plain language documentation into how to update the C&L language toggle widget for new pages, new languages, and new templates.

## Tasks

- [ ] Create basic overview of the LanguageToggle widget and how it functions.
- [ ] Create documentation for adding pages to the react widget and the workflow steps associated.
- [ ] Create documentation on how to add a new language to the widget and what link to doc on further work that would be required to support other languages.
- [ ] Create documentation on adding the language toggle to new templates and what other considerations would need to be made to support the toggle on these new templates.
  - [ ] Publish documentation to va.gov-team repo
  
## Acceptance Criteria

- [ ] Documentation created, and shared with team
