### ISSUE TITLE
[Console Services] Update assets and communications channels with new team name

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#38363]
## Issue Description
The recent Platform team reorg has been designed to reduce cross-functional team dependencies as well as create more accurate team names aligning to the products they support and own.

The team name has changed from BE-Tools to Console Services, this will need to be updated in our documentation.

---
## Tasks
- [x] Rename Confluence Space from "BE-tools" to "Console Services" (Confluence should automatically update links)
- [x] Rename "BE-Tools" to "Console Services" on Confluence pages
- [x] Update Platform Website (I was unable to find any mention of a BE-tools team)
- [x] Update Orientation materials/PowerPoints **(waiting on Chelen to update the slack channel name before updating the powerpoint, this request was made here: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/2034958373/Slack+Channel+Name+Changes)**
- [x] Update slack channel name. (OCTO-DE) from vsp-tools-be to vsp-console-services (this change request has been added to https://vfs.atlassian.net/wiki/spaces/LEAD/pages/2034958373/Slack+Channel+Name+Changessite per Mike Chelen's request)
- [x] Github 
- [x] tools-be-review updated and associated github action
  - [x] team label from `BE-tools` to `Console-Services`
  - [x] Update Github templates with new label
  - [x] Github BE-Tools team rename to Console-Servicesteam
- [x] Update Zenhub board name
- [x] Uncover other places/spaces where BE-tools team name would be listed.
- [x] Update Roadmap/Vision (If needed)
- [x] Team member Slack profiles
  - [x] Eric
  - [x] Jeremy
  - [x] Lindsey
  - [x] Naoufal
  - [x] Riley
  - [x] Travis
  - [x]  Rachal
  - [x] Nate

Some items pulled from the list located in this [Team Restructure document by Andrea ](https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1920434211/Potential+VSP+Tech+Teams+Restructure)in Step 4.

## Acceptance Criteria
- [x] Documentation will refer to the team as Console Services
- [ ] Teams are able to reach out to Console Services through slack and slack bot **(request to update slackbot has been made here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38352)**
