### ISSUE TITLE
Remove ROT'd docs PT 1

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38370]
# User story

As a VFS team member, I only want to be aware of current Platform offerings, so that I can spend time on my VFS app instead of learning obsolete Platform procedures.

# Tasks
- Concurrently:
  - Prep for removal:
    - [x] Generate list of docs to be removed
    - [x] Align with team on list
    - [x] Solicit SME approval on list
  - Prep for tentacles:
    - [x] For each item on the docs-to-be-removed list, identify traffic rate and course of action
    - [x] Brainstorm courses of action based on traffic rate
- For each doc to be removed:
  - [ ] Remove it
  - [ ] Perform the course of action
- We do not have to worry about publishing, because the changes will be deployed during the twice-weekly deploy

# Acceptance criteria
- ROT'd docs have been removed from live Platform website spaces - just waiting for twice-weekly deploy
- Redirects have been applied for the already-identified pages indicated in the list

# Reference info
- Courses of action:  Remove = Archive or delete?  How are we dealing with redirection for highly-trafficked docs?

**Comment by lianilychee** [comment]
Gretchen brought up during spr planning - will rope people in as learning opportunities re: removal arise

**Comment by gmaciolek** [comment]
Friday 3/25
- today I would like to make it through all of the prep tasks for this ticket
- Assuming I get approval from Peter/Joe on the list today, on Monday I'll do all the removal steps

**Comment by gmaciolek** [comment]
Monday 3/28
- Finalizing this doc that outlines all pages to be removed and any additional actions or questions: https://vfs.atlassian.net/l/c/wXwwCDSu
- Will share with Peter/Joe for approval/feedback when it's done
- Pending approval by end of day/early tomorrow, will set up meeting with Jill and Samara for tomorrow to work on the removal steps

**Comment by lianilychee** [comment]
pending sme response

**Comment by lianilychee** [comment]
the ones that are obsolete have been removed.  there are some that need to be rolled into other docs*, so we're waiting for that incorporation first before closing the ticket.

*Tools and Resources, Overview of QA Process

**Comment by gmaciolek** [comment]
Remaining work: For all the docs listed on the [docs to remove table in Confluence](https://vfs.atlassian.net/l/c/wXwwCDSu) that haven't yet been removed:
- [ ] redirect
- [ ] remove

Note: this work is dependent on publishing the new Process Overview and Tools and Resources page first.
