### ISSUE TITLE
Staging Review Authenticated Experience - Payment Information

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38376]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL - [https://staging.va.gov/my-va](https://staging.va.gov/my-va)
- [x] [Staging test-user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md)

- [x] [Payment Info - Product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md)

- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/product/release-plan.md) with the "Planning" sections completed 

### Content artifacts 

- [x] Your product’s content source of truth - [FE Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)

### QA artifacts

- [x] [Product test [**case**](https://dsvavsp.testrail.io/index.php?/cases/view/14393)/test [**plan**](https://dsvavsp.testrail.io/index.php?/plans/view/2824) in TestRail with test execution logs
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/297) 
- [x] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/296) - NO DEFECTS

### Accessibility artifacts - **We have both TestRail and GH Document results**

- [x] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/runs/view/3087). **(Preferred)** OR, 

- [x] [Accessibility staging review prep document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/Staging%20Review/Accessibility%20testing.md)

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Staging Review scheduled for 3/25 at 11:30am ET

**Comment by jimuhh** [comment]
Hi. Couple of questions. 

- Which ID verification service do I click on the staging site? IDme, Login.gov...?
- Are the different staging logins just for the contexts of use described?
thanks!

**Comment by jimuhh** [comment]
Thanks @hdjustice! 
I'll let you know if I have any questions.

**Comment by hdjustice** [comment]
Hi @allison0034 - It appears that the payment history is down, the actual payment history page isn't returning any information either.  There have been issues on & off for the past 2 weeks, and they have had to restart their server.  I am pinging that team now to see what might be causing this.  I will keep you updated!

**Comment by allison0034** [comment]
@hdjustice are the payments down again?

We can’t access any claims or appeals information right now
We’re sorry. Something went wrong on our end. If you have any claims or appeals, you won’t be able to access your claims or appeals information right now. Please refresh or try again later.

cc @chaseakirby

**Comment by allison0034** [comment]
@hdjustice that is under the notifications section. Are we reviewing that as well or is that a separate staging review?

And just to be clear, that would mean we are only reviewing the content for the Benefit payments and debts section on MyVA correct?

**Comment by hdjustice** [comment]
@allison0034 - It appears that there is an issue pulling claims information, but this does not impact the Benefit payments and debts section.  The Notifications section at the top is a separate feature that is not ready for review.

**Comment by allison0034** [comment]
@hdjustice perfect... thank you!

**Comment by allison0034** [comment]
@hdjustice I just want to say thank you for the easy to follow test account document. It was REALLY helpful!

**Comment by hdjustice** [comment]
@allison0034 You are quite welcome, thank you!

**Comment by joshkimux** [comment]
@hdjustice I've struggled to log in as a LOA1 users-- do you (or anyone else here) have tips or a user/pass combination that works?

**Comment by hdjustice** [comment]
Hi @joshkimux - From the **[staging users document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)**, You can use User 1000, logging in through Login.gov.  That is an LOA1 user and displays the "Verify your identity" alert, as expected.

**Comment by ddzz** [comment]
No QA feedback, looks good!

**Comment by SarahKay8** [comment]
No A11y feedback on my end!

**Comment by allison0034** [comment]
No design feedback, thank you!

**Comment by joshkimux** [comment]
For some reason the user/password doesn't work still for the LOA1  😢 
Based on the mockup, the only feedback I might have is that "Verify your identity" (I believe) is a link and should be styled using the action link. I've left feedback on it before, so it might have already been changed which is why I'll withhold from adding it to a ticket until I can access the LOA1 user 🙏 

https://user-images.githubusercontent.com/14154792/161274097-9ce39801-91ad-4206-93c4-4fd270a81d77.mov

**Comment by ajakabcin** [comment]
Closing - all reported findings/issues are closed
