### ISSUE TITLE
[Debt Portal] Empty state adjustment to provide Veterans a way into MCP's copay overview page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38389]
### The problem

Currently, Veterans who navigate into the VBA debt portal looking for their copay balances (assuming they have no VBA debt), are presented with the following empty state: 

![Screen Shot 2022-03-10 at 3.51.44 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/1dfcb2c5-d19a-4f8e-99b8-b9837b82941d)

The link redirects them to [the 'Review and pay your VA copay bill' content page](https://staging.va.gov/health-care/pay-copay-bill/). 

### The proposed solution

We should adjust the empty state alert to tell Veterans that they can view their copay balances online and learn how to make a payment or request help. [We should also link directly to the copay bill overview page](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142712285/simulate/sitemap?mode=i). 

---
## Tasks
- [x] Mock up an adjusted empty state alert that links to the copay tool 
- [x] Reach out to Mikki about if we can link directly into the copay tool's overview page
- [ ] Send the proposed empty state to Jill and Julie 

## Acceptance Criteria
- [x] Mocked design is linked in this ticket 
- [ ] Frontend ticket is created after approval from DMC stakeholders + Mikki

**Comment by rileyorr** [comment]
[I've added the proposed empty state alert to UXPin ](https://preview.uxpin.com/53bf4de7cd95501214aafee8c7c7a0a6052c53c7?_gl=1*bpwkuu*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/148407578/simulate/no-panels?mode=i)

**Comment by rileyorr** [comment]
I reached out to Mikki about linking directly into the copay overview page and received this feedback: 

> I am open to that, although I wonder if a link to both options would be best - "check your copay balances" and "pay your copay bill"?  That way we don't use the direct link to a task.    I also wonder if this should be removed from the empty state and actually be placed at the bottom of the page as always visible supporting content?   This may also help with our cross-linking between bills/debt in the combined portal.

I've incorporated her feedback into [the empty state prototype](https://preview.uxpin.com/53bf4de7cd95501214aafee8c7c7a0a6052c53c7?_gl=1*plm927*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/148482875/simulate/no-panels?mode=i). I'm going to wait to see if she has any follow-up feedback on this iteration and then I will send it to Jill + Julie tomorrow.

**Comment by rileyorr** [comment]
After our team discussed the LOE from a frontend perspective, we decided to hold off on implementing these changes in favor of focusing frontend efforts on building the combined portal (which will inherently solve this issue)

**Comment by denisecoveyduc** [comment]
Thank you Riley for spending time to dig into this problem and pose the question to the team! Great work!! Excited to implement the combined portal for Veterans which will resolve this issue and add so much more to the Veteran experience. I will let our stakeholder know our decision to hold off on this solution ;)
