### ISSUE TITLE
1095-B Team Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#38387]
## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [x] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
- *Nadya*
- Conduct axe browser scan, and document or address issues found
  - [x] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
- *Nadya*
  - [x] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
- *Design*
  - [x] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
- *Anyone*
  - [x] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
- *Anyone*
  - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- *Anyone*
- [ ] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x] **Attach to Collab Cycle Epic**
- [x] **Labeled with Team**

**Comment by JordanSWhite** [comment]
We'll need to be in staging to do all of these (except, perhaps, color tests and content resize), since we need to test in browser. See the ticket for suggested crew for each test

**Comment by JordanSWhite** [comment]
From engineer: Since axe tests are written into cypress tests, which we're unable to do because you have to create mock API calls (essentially complete fake data, which doesn't work for the PDF because its not data but an actual PDF), we aren't able to do this axe test. However, all code was reviewed and approved.

**Comment by tameracorson** [comment]
@here This ticket is being closed due to product not being sent to production.  New design and build will be placed on separate collab cycle tickets.
