### ISSUE TITLE
Medical Device Tool Usage data

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3839]
## User Story:
As a ___Product manager_______, I need _gather qualitative data regarding how the Medical tool currently used________ so that I can ___build KPI's for the Medical Device tool______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Determine what type of device is used most for ordering items (desktop, mobile) 1.5hr
- [ ] Determine what is the most used browser 1.5hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Documentation is in GH

## Next Steps
- Combine information with qualitative user research conducted by the design team
- Create a persona of the Veterans using the DLC to reorder medical supplies

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wygonikGCIO** [comment]
> UX designer

oduct
