### ISSUE TITLE
[VAMC] Review and update - District 2 + VET Center submitted for review - Process and submit for final review by RCT [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38391]
## Task(s)
* Review, audit, and correct VET center page submitted for review.  Communicate any large changes or errors to the editor if required.  
**Track all reviews of District 2 below**
**District 2**
- [ ] Atlanta Vet Center
- [ ] Augusta Vet Center
- [ ] Bay County Vet Center
- [ ] Birmingham Vet Center
- [ ] Charleston, SC Vet Center
- [x] Chattanooga Vet Center
- [ ] Clearwater Vet Center
- [ ] Clermont Vet Center
- [ ] Columbia, SC Vet Center
- [ ] Columbus, GA Vet Center
- [ ] Daytona Beach Vet Center
- [ ] Fort Lauderdale Vet Center
- [x] Fort Myers Vet Center
- [ ] Gainesville Vet Center
- [ ] Greenville, SC Vet Center
- [ ] Hatillo Vet Center
- [ ] Huntsville Vet Center
- [ ] Jacksonville, FL Vet Center
- [ ] Johnson City Vet Center
- [ ] Jupiter Vet Center
- [ ] Knoxville Vet Center
- [ ] Lakeland Vet Center
- [ ] Lawrenceville Vet Center
- [ ] Lexington Vet Center
- [ ] Louisville Vet Center
- [ ] Macon Vet Center
- [ ] Marietta Vet Center
- [ ] Melbourne Vet Center
- [ ] Memphis Vet Center
- [ ] Miami Vet Center
- [ ] Mobile Vet Center
- [ ] Montgomery Vet Center
- [ ] Myrtle Beach Vet Center
- [ ] Naples Vet Center
- [ ] Nashville Vet Center
- [ ] Ocala Vet Center
- [ ] Okaloosa County Vet Center
- [ ] Orlando Vet Center
- [ ] Palm Beach Vet Center
- [ ] Pasco County Vet Center
- [ ] Pensacola Vet Center
- [ ] Pompano Beach Vet Center
- [ ] Ponce Vet Center
- [ ] San Juan Vet Center
- [ ] Sarasota Vet Center
- [ ] Savannah Vet Center
- [x] St. Petersburg Vet Center
- [ ] Tallahassee Vet Center
- [ ] Tampa Vet Center

** Acceptance Criteria
* System is reviewed, updated in Drupal as required and then sent to Jessica @ RCT for final review and approval for publication.
