### ISSUE TITLE
Quality Assurance Standards Team Rename Team Resources

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38393]
## Description
The recent Platform team reorg resulted in a name change for our team from `Testing Tools Team` to `Quality Assurance Standards` team. As a result, we need to update all team resources to reflect the new name.

---
## Tasks
- [x] Rename Confluence Space
- [x] Rename references to team name in Confluence pages
- [x] Update Platform Website
- [x] Update Orientation materials/PowerPoints
- [ ] Update slack channel name. (OCTO-DE) from #vsp-testing-tools-team to #vsp-qa-standards-team
  - [ ] Need to verify the new name is acceptable per standards regarding naming
- [ ] GitHub 
  - [x] team label from `testing-tools-team` to `qa-standards`
  - [x] Update GitHub templates with new label
  - [x] GitHub rename team to `qa-standards`
- [ ] Update ZenHub board name
- [ ] Uncover other places/spaces rename might be necessary
- [ ] Update Roadmap/Vision
- [ ] Team member Slack profiles
  - [ ] Peter
  - [ ] Joe
  - [ ] Ryan J
  - [ ] Ryan B
  - [ ] Holden
  - [ ] Curt

Some items pulled from the list located in this [Team Restructure document by Andrea ](https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1920434211/Potential+VSP+Tech+Teams+Restructure)in Step 4.

## Acceptance Criteria
- [ ] Documentation will refer to the team as Quality Assurance Standards Team
- [ ] Quality Assurance Standards team is reachable through standard Platform communication methods (Slack, Support Bot, GitHub Tickets)
