### ISSUE TITLE
Medical Device tool qualitative data of Veterian's demographics

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3840]
## User Story:
As a ___Prod manager_______, I need ___gather qualitative data on Veterans_______ so that I can ___KPI's and build a persona_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Meet with DLC to determine what demographic information the have 1.5 hrs
- [ ] Meet with GA team and see what information about Medical tool Device from eBenets 1.5hr

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Documentation is put in GH

##Next Step
- Combine Veteran qualitative date from the design team with veteran and DLC quantitative data gather from this ticket
- Create a persona

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sshein** [comment]
Hi there! I'm starting to look at tickets more on my teams so I can provide more direct feedback.  Sorry to jump in, but just want to make sure we aren't creating personas before we've done qualitative research.  Marketing folks used to create "personas" based just on demographic data but that isn't best practices these days.  I tend to not even use the word "personas" in my design practice and prefer the work "User profiles."  These are done after initial research studies and groups together behaviors that have been culled from the research. That way they are the most useful / realistic views of our users.
