### ISSUE TITLE
Inconsistent, unreliable and outdated Product Lists across VA.gov

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38418]
## Issue Description
There is no reliable source of truth for the complete list of products and services built and managed by VFS teams across VA.gov. Platform teams provide support to the VA.gov products and have had to create their own lists in order to track and manage their support appropriately.

We now have disparate lists maintained by various Platform product teams, including:

- [VA.gov Products](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) on Confluence. This list was initially created by former Platform Lead Rachael Roueche in Google Sheets, but transferred over the Confluence in fall of 2021 by the Platform Governance team. All VFS POs were given edit access to Confluence in order to maintain the list themselves. VFS Product Managers do not have edit access. Platform is aware that there are products missing, and incomplete descriptions.
- [Product List in va.gov-team GitHub repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products). Managed by VFS teams.
- [VA.gov KPI Dashboard Eligibility](https://va-gov.domo.com/page/1550814739?userId=1646566899) in Domo. Managed by the Platform Analytics and Insights team.
- [Salesforce Issues (MVP) ](https://va-gov.domo.com/page/130739792)in Domo. Managed by the Contact Center team.
- [Config file for FE app owners](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json). Managed by Release Tools Team.

In addition, CTO product community of practice lead Lisa Koenigsberg would like to get more information on current product lists and product outlines. Per @mchelen:

> One of the things I'm anxious to create is a product outline/strategy doc for every product we have.  I mostly want to better understand the history and goals of what the platform team calls the "product outline" and engage more deeply in helping to insure all teams have a version of this for their products.
> There's a lot tied up in this at a high level and I don't think we need to solve for all the things to start.  For example..
> - Platform maintains [this list](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) of products/features for [VA.gov](http://va.gov/).  Making sure that everything here has an outline/strategy and new things added to as well
> - There are likely different versions of outline/strategy formats.  That's okay, for now.
> - There are products and features that are not [va.gov](http://va.gov/) but need to be tracked.  I had asked folks to add them to the above list.  Maybe there's a content update that needs to be made to the page to account for the fact that this list includes all OCTO things?
> - We align on what the goal, audience, structure of an outline/strategy doc is - might require better definition of product vs. feature
> - Anyway, lots to talk about and I think the starting point is me and whomever in Platform who can speak best about product outline and this list.

---
## Tasks
- [ ] Schedule meeting time with @lkoenigsberg to, "better understand the history and goals of what the platform team calls the "product outline" and engage more deeply in helping to insure all teams have a version of this for their products"

## Acceptance Criteria
- [ ] Meeting notes have been recorded.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchelen-gov** [comment]
Thanks @shiragoodman! Please add to ticket:
Reference: https://dsva.slack.com/archives/GNF5GSD9N/p1646760991114279
Task: schedule meeting time with @lkoenigsberg to:
> better understand the history and goals of what the platform team calls the "product outline" and engage more deeply in helping to insure all teams have a version of this for their products
AC: meeting notes have been recorded

**Comment by mchelen-gov** [comment]
RTT has also created a config file for FE app owners:
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json

**Comment by shiragoodman** [comment]
closing this ticket as the work has been picked up by QA Standards team. FYI @JoeTice
