### ISSUE TITLE
Discovery: Medical Device Tool Personas

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#3841]
## User Story:
As a  _UX designer_, I need _to create set of initial personas_ so that I can _build interactions that meet the needs and expectations of the Veterans they represent_.

## Tasks
- [ ] Combine data from the interviews and metircs from the DLC to create 4 peronas. 
- [ ] Create documents for each of the 4 personas (5 hours)

## Acceptance Criteria:
The requirements that must be met in order to mark this user story as completed
Given: that qualitative and quantitative research is completed
When: synthesis is complete
Then: Personas can be created

- [ ] Share personas with BAM2 team
- [ ] Document personas in GH

## Next Steps
- Incorporate personas and their insights into user journeys

## Blockers
- [ ] [#3839](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3839)
- [ ] [#3840](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3840)
