### ISSUE TITLE
Facility Locator expected behavior for VBA "all services" searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38433]
## Issue Description
The Facility Locator is designed to return the closest locations which map to the search parameters. However, there may be a disconnect in the "All services" default, particularly for "VA benefit" searches. 

This is well illustrated by this [example search](https://www.va.gov/find-locations/?page=1&address=22903&facilityType=benefits&serviceType&latitude=38.03&longitude=-78.5&radius=19&bounds%5B%5D=-79.25&bounds%5B%5D=37.28&bounds%5B%5D=-77.75&bounds%5B%5D=38.78&context=Charlottesville%2C%20Virginia%2022903%2C%20United%20States)
1. Enter 22903 as zip code
2. Choose VE benefits
3. Choose All VA benefit services
4. Observe single result is returned: [VetSuccess on Campus at Liberty University](https://www.va.gov/find-locations/facility/vba_314k). This location is on a campus and offers a single service: Education and career counseling.

Returning a location offering a single, particular service is not consistent with an "all services" parameter. Should "all services" map to Benefit region offices which actually offer "all services"? How do we best support Veterans, particularly if no benefit region offices exist within the searched geography?

---
## Tasks
- [ ] Determine ideal behavior
- [ ] Determine how best to support Veterans in a variety of possible scenarios

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by davidconlon** [comment]
By default "All benefits services" should show the nearest Regional Office as well as any other facilities that may fall within that range.
This is a bit down-and-dirty, but we know that the hub location for "all services" is the RO even though it's not necessarily 100% the right thing. 
This will improve the Veteran's experience in general by showing them the "main location" and then allow them to filter.
So we'll need to be able to sniff for the facility type
