### ISSUE TITLE
Lovell taxonomy needs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38431]
## Issue Description
Lovell Federal health care system may need health services added to the taxonomy to represent their available services

Input from Email from Trevor Seela on March 9 with responses from Dave Conlon below

### Primary Care
Lovell: We have four separate departments that oversee Primary Care, and our naming conflicts a bit with the existing taxonomy. Veterans are seen in the ‘Veterans Primary Care’ department at our North Chicago facility, or at our VA community clinics in Kenosha/Evanston/McHenry. However, Active Duty and their dependents are seen in departments called Family Practice, Internal Medicine, and Pediatrics. Part of the concern here is that we want to avoid Veterans assuming Internal Medicine is the correct department for them, or Active Duty contacting Primary Care, because of our complicated naming conventions (and we’re probably the only facility that has Pediatrics). 

> VA: This can likely be solved through delivery location (maybe with a slight adjustment) there, i.e.:
> Primary Care
> -	Veterans Primary Care
> Location, Hours Phone
> -	Family Practice for TriCare (Active Duty Service Members?)
> Location, Hours, Phone
> -	Internal Medicine for TriCare (Active Duty Service Members?)
> Location, hours Phone
> 
> “Pediatrics” could be its own category - although it isn't needed across VA locations, it wouldn't be a mandatory service and it's fine to have a service which isn't used by all/most facilities 

### Dental
Lovell: A big difference between us and most VA facilities is that our Dental program is very large. I think we might need to split this up into a few sub-specialties. As an example, Bldg. 152 only works on Prosthodontics, so the typical entry for Dental/oral surgery might be a little misleading to our patients.

> VA: We have Prosthodontics at our other VA locations. We even have a residency program for that at VA Washington DC.
> Can leverage delivery locations - need to understand how much content is needed and if it is possible within an accordion

## Social programs/Other services/additional examples
Lovell: Active Duty Transgender care coordinator (this is separate from the VA LGBTQ+ Care program, specific to people who are transitioning while they are Active Duty)

> VA: This can be a program page linked from the System health services page under LGBTQ+, rather than a unique service

                
Lovell:  Active Duty Case Management 

> VA: This may be its own service. Need to understand potential for overlap with Vet Center or VBA taxonomy.

Lovell: Exceptional Family Member Program (a support program for families with children who have special needs) 

> VA: This is a program. Likely could be linked from a system health service description for “Pediatrics”. 

Lovell: Advice Nurse (we have two separate services, depending on if they are Veterans or Active Duty/Dependents/TRICARE) 

> VA: Can use Two separate delivery points. Need to understand what happens now if a Veteran calls the TriCare Advice nurse or vice versa
>-  Veterans Advice Nurse
> Location, Hours Phone
> - TriCare Advice Nurse
> Location, Hours, Phone

Lovell: Operational Medicine (this area manages DoD-specific exams outside of the scope of a typical Primary Care routine physical, such as oversees suitability screenings, PHAs, etc.)

> VA: This may be a separate taxon, it’s OK to just have one taxon as long as it’s intentional and makes sense to the audience, doesn’t conflict with others.

---
## Tasks
- [ ] Understand Veteran/service member mental model - how will they look for these services?
- [ ] Consider a flag for the delivery location for “audience”

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by davidmpickett** [comment]
@valerierunde @kevwalsh This issue should probably be referenced somewhere in our Lovell epic as it seems to have some important detail about potential Drupal issues
