### ISSUE TITLE
Research industry standards and approaches

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38437]
## Issue Description
Analyze best practices across industry and record learnings in Mural

---
## Tasks
- [x] https://www.nngroup.com/articles/service-design-101/ - Dan
- [x] https://boagworld.com/audio/service-design/#Why_is_Service_Design_a_Thing - Nicole
- [x] https://gds.blog.gov.uk/2016/04/18/what-we-mean-by-service-design/ - Taylor
- [x] https://www.interaction-design.org/literature/topics/service-design - Bryan
- [x] https://uxplanet.org/service-design-is-everywhere-a58fd5901e63 - Dan
- [x] https://careerfoundry.com/en/blog/ux-design/what-is-service-design-how-to-implement-service-design-processes/ - Nicole
- [x] https://cio-wiki.org/wiki/ITIL_Service_Design#:~:text=The%20scope%20of%20Service%20Design,conformance%20to%20standards%20and%20regulations. - Taylor
- [x] https://www.interaction-design.org/literature/article/the-principles-of-service-design-thinking-building-better-services - Bryan
- [x] http://www.practicalservicedesign.com/service-design-101 - Bryan

## Acceptance Criteria
- [ ] Takeaways and learnings recorded in Mural for workshop

## Deadline
- April 6th
