### ISSUE TITLE
Launch Quarterly Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38438]
## Issue Description
Launch Survey in typical manner.

---
## Tasks
- [x] Launch Survey in Optimal Workshop
- [x] Communicate its availability in relevant Slack channels

## Acceptance Criteria
- [x] Survey launched
- [x] Communicate its availability in relevant Slack channels
