### ISSUE TITLE
Research: This is Service Design Doing book and themes

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38441]
## Issue Description
Individuals to read book and draw out applications/learnings for informing SDT mindset, **paying particular attention to learnings that inform Scope and Purpose of SD**.

---
## Tasks
- [x] Read and record learnings for application to SDT - Dan
- [x] Read and record learnings for application to SDT - Nicole
- [x] Read and record learnings for application to SDT - Taylor
- [x] Read and record learnings for application to SDT - Bryan

## Acceptance Criteria
- [ ] Learnings recorded in Mural board

## Deadline
- April 5th
