### ISSUE TITLE
[SW-Content]  Compose and build landing page - for 10950B form - 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38448]
## Resources
#37079
**They have an updated page in a comment in the ticket that you can work from**

## TASK(s)
- [x] Review and build landing page from examples provided in intake document
- [x] Edit and review build for best quality
- [x] Save in Draft for final review

## Acceptance Criteria
* Draft page is saved in Drupal for final review.

**Comment by lunascoop** [comment]
@psanders86 this page is ready for review (minus the react widget). Per Danielle's request, kept it simple like the Home loan COE page.

Download your IRS 1095-B tax form: http://preview-prod.vfs.va.gov/preview?nodeId=44346
Content for react widget (needs to be built by Public Websites)

**Please sign in to download your IRS 1095-B tax form**
Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.
**Sign in or create an account**

**Here are my notes:**

- H1 taken from comments in the IA ticket and [Final IA design file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-1095-b.md)
- Page intro: Simplified and move content about certain states requiring proof of health coverage to separate H2. Also decided to use “most recent tax year” to indicate that users can only download the most recent tax year. I based this from the mockup of the [authenticated landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/3.8.2022_1095-b_Authenticated%20state_Desktop.jpg).
- React widget: Kept it as is in the [mockup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/design/wireframes/3.8.2022_1095-b_Authenticated%20state_Desktop.jpg)
- For **What if I need to correct or update information on my tax form?** and **What if I have trouble opening my tax form?**, made these Q&As using the [Download VA benefit letters](https://www.va.gov/records/download-va-letters/) page as a guide.
- For **What if I need to correct or update information on my tax form?**, changed "enrollment center" in the mockup to "VA health care benefits hotline", per its reference on our [Helpful VA phone numbers](https://www.va.gov/resources/helpful-va-phone-numbers/) page.
- PDF content taken from the [Download VA benefit letters](https://www.va.gov/records/download-va-letters/) page 

Let me know if you have any questions

**Comment by lunascoop** [comment]
The page has been updated per our discussion w/the product team.

Download your IRS 1095-B tax form: http://preview-prod.vfs.va.gov/preview?nodeId=44346

**Comment by tameracorson** [comment]
Team,   Just touched base with Danielle.  Designs are good to go (minus widget).   Are the designs at the [link above](http://preview-prod.vfs.va.gov/preview?nodeId=44346) the ones we are going with @psanders86 @RLHecht ?   We have a meeting with our product and business owner shortly and we are trying to piece together the most mature rendering of work.  I will follow up with our engineer on the widget.

**Comment by tameracorson** [comment]
Thanks for feedback Danielle and Patrick.

**Comment by nprimak** [comment]
Here is a link to the folder in the branch where the widget lives: [https://github.com/department-of-veterans-affairs/vets-website/tree/feature/37015-poc-1095b-page/src/applications/static-pages/download-1095b](https://github.com/department-of-veterans-affairs/vets-website/tree/feature/37015-poc-1095b-page/src/applications/static-pages/download-1095b)

Please advise as soon as possible if you need anything else from me.

**Comment by RLHecht** [comment]
@nprimak Could you let us know what the code is for the react widget? We just need to plug that into Drupal. Or is Public Websites creating it and they'll provide us with the link?

**Comment by nprimak** [comment]
@RLHecht  The shortcode right? It is `download-1095b` . The code for the widget isn't in staging, however so it probably won't work yet.

**Comment by ashleycastillo** [comment]
@RLHecht Can you help us understand if we need to go to staging review for the shortcode to work? We are also working with the Collaboration Cycle team to understand how we go to Staging Review together, given the sitewide content team has made the front end in Drupal

**Comment by RLHecht** [comment]
@longmd Would you be able to answer this? Does the widget need to be in staging or prod in order for it to show when I put the code into Drupal?

**Comment by ashleycastillo** [comment]
@RLHecht Nadya's code is now in staging.  The short code is download-1095b . Can you please confirm if you can pull in the widget today?

**Comment by RLHecht** [comment]
@ashleycastillo I put it into the page but it's not showing the correct text. @longmd Does the widget need to be in prod for this to work or in staging should be fine? This is what it's showing on Drupal:
<img width="811" alt="Screen Shot 2022-03-23 at 12 00 41 PM" src="https://user-images.githubusercontent.com/48728214/159742762-a682c391-41f0-49cf-8e68-061b378da5bc.png">

**Comment by RLHecht** [comment]
@longmd When I uncheck the CTA it searches for a long time and then I get this error message. That's why I thought maybe the CTA should be checked.
 
<img width="856" alt="Screen Shot 2022-03-23 at 2 33 01 PM" src="https://user-images.githubusercontent.com/48728214/159771238-52bcb28a-f47e-4aa9-bbc9-0dcffaab5078.png">

**Comment by ashleycastillo** [comment]
@RLHecht Apologies, looks like we are still waiting for another approval from ‘vsa-public-websites-frontend’ so that's why it's not working yet. We will get back to you when this approval is complete, too!

**Comment by RLHecht** [comment]
@ashleycastillo See Matt's comment above. I think there might be a few more steps needed before the widget is working in Drupal.

**Comment by RLHecht** [comment]
Sounds good! Thanks for letting me know @ashleycastillo

**Comment by ashleycastillo** [comment]
@RLHecht Could you try now? Looks like it has now passed all reviews and has been merged in, so the widget should appear now. (Backend pages are still in review, so the download button may not pull up a PDF but I think the widget on front end should work)

**Comment by RLHecht** [comment]
@ashleycastillo It's still not showing in Drupal.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @psanders86. The 1095-B team came to health content office hours today. They're going to add the info about needing Adobe Reader to the auth content within the react widget, so we no longer need that "How to get your form" section in the Drupal content. Could the team make that update when you have a moment? Thank you!

**Comment by RLHecht** [comment]
@ashleycastillo Success! Though the text isn't correct. That last sentence needs to be deleted.

<img width="876" alt="Screen Shot 2022-03-25 at 10 33 43 AM" src="https://user-images.githubusercontent.com/48728214/160141242-c13bf339-b4b0-4792-bbfc-e7bf6c1f7a04.png">

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I removed the "How to get your form" Q&A from the page.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome. Thanks so much, @RLHecht!

**Comment by tameracorson** [comment]
@DanielleThierryUSDSVA @RLHecht I just pulled a copy from the Preview URL above... is this set and final so I can share with team?

**Comment by stephte** [comment]
Hi @psanders86, the updated widget just got merged into master a little bit ago

**Comment by psanders86** [comment]
Great! We should be able to see those changes soon, then.

**Comment by tameracorson** [comment]
@psanders86 Checked this AM... changes are in for page (woohoo).

**Comment by psanders86** [comment]
@tameracorson Confirmed on this end. Do you need anything else from us?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @tameracorson @tmulrooney-va. Question as I'm incorporating the profile option for changing address on 1095-B.

Do CHAMPVA and/or Foreign Medical Program recipients also receive a 1095-B? I ask because CHAMPVA and FMP are 2 of the programs that are not connected to profile address updates. So those folks would need to contact those programs directly to update their address and other info.

**Comment by tameracorson** [comment]
@DanielleThierryUSDSVA yes, champVA do recieve a 1095-B, thank you for that call out.   Change of address would only address those with VA profiles, correct?   Am I to understand that those categies do not have profile accounts (e.g wife of war deceased)?  If so, we may have to design content around that @CarlDickerson @JordanSWhite

**Comment by DanielleThierryUSDSVA** [comment]
We can reach out to the profile team to ask about the specifics around accounts. But I do know that if you update your address in your profile, that only updates your address across some benefits and programs. CHAMPVA is one of the programs where you have to contact the program directly to change your address (for reference: https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact).

**Comment by tameracorson** [comment]
@DanielleThierryUSDSVA I did my own veteran testing of profile and if we change profile, it will change HEC... and if I change in HEC, it does change my profile... so if the non-veteran has a profile, and HEC, it should communicate.

**Comment by DanielleThierryUSDSVA** [comment]
@tameracorson Okay, so it sounds like even if they're a CHAMPVA recipient, their 1095-B would still come from HEC...so as long as they have a profile, if they update their address there, it would communicate the update to HEC and HEC would then update the 1095-B.

If that's correct, then I think the thing that's important to note is that it does **not** change their address for any CHAMPVA communications (unlike a Veteran with VA health care...changing their address in their profile updates their address for 1095-B **and** prescriptions, etc. for VA health care). Make sense?

**Comment by tameracorson** [comment]
@DanielleThierryUSDSVA @CarlDickerson correct.   Can we alter content on Widget to make that distinction clear?   Or say, "to change your address on your 1095-B click here?

**Comment by DanielleThierryUSDSVA** [comment]
@tameracorson Tracey and I chatted in slack about widget vs. link. For now, I would recommend a link to the change address page rather than a 2nd widget on this page. 

The primary action on this page is the 1095-B so for accessibility reasons, I worry about adding a 2nd widget for a secondary function. We can and should explore iterations on this. For example, we could consider a secondary action link within a react widget. But since my understanding is that this is a quick-turnaround need, let's go simple to start. I'll send over a link to the updated preview soon.

**Comment by CarlDickerson** [comment]
@DanielleThierryUSDSVA I like this approach. Discussing with design team, we had the same concerns about using the 2nd widget. I'll look for your preview. Will we still need to add additional content around ChampVA?

**Comment by CarlDickerson** [comment]
@DanielleThierryUSDSVA  I had a look at the content change. I'm fine with the edits. The only note that I have is that we’re linking to the how to page instead of just the profile which seems like an extra step to me… but I get it

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @CarlDickerson. Right, yes, it's an extra step for now, as we'd talked about above. We can consider other options that still make it clear that changing your address is a secondary option, but we're going for the fastest, simplest solution to meet the immediate need. 

For example, in a future iteration, you all could create a react component with an action link in it that switches from "Sign in to change your address in your VA.gov profile" (unauth) to "Change your address in your VA.gov profile" (auth). 

Thanks!

**Comment by tameracorson** [comment]
@stephte Can you answer @DanielleThierryUSDSVA question above regarding which address is being pulled from HEC... I'd assume mailing but there is home address option as well... just making sure we cross all of our T's.

**Comment by psanders86** [comment]
Yes, we'll do that today, thanks!


[cid:7bc76cfe-2af2-4e39-b362-e31a2066f0cd]

Patrick Sanders

Content Writer



M:  240-444-6116


About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>

Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.­

________________________________

**Comment by bethpottsVADEPO** [comment]
@RLHecht Is this work done?

**Comment by RLHecht** [comment]
Thanks for finding this old ticket! Yep, this can be closed. This page isn't in production at the moment but is in a final state in Drupal. Closing!
