### ISSUE TITLE
Understand state of Project Intake to prepare for potential merge of Feature Request Process into unified backlog(s)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38447]
The new Project Intake process will heavily alter this space.  We will need to look at what adjustments need to be made to documentation and workflows.

Currently, the working goal appears to be a unified backlog that contains both Projects and Feature Requests that are technical in nature.

As Leadership refines their approach, we will make the necessary adjustments.  This information is still To Be Determined...

## Blockers
- Leadership is in the process of refining their intentions
- Once planned approach for Project Intake is in place, SDT can evaluate necessary changes to FRP, as well as recommend any combined workflows.

## Tasks
- [x] Communicate with leadership to understand current state intentions
- [x] Create a workflow that captures current state and posits future state flow

## Acceptance Criteria
- [x] Workflow artifact reflects current understanding of how a Project is captured, considered, and executed

## Continuance
This process will continue into the next quarter

**Comment by annekerr49** [comment]
@steel36  Bryan  we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.
