### ISSUE TITLE
HLR/NOD: Replace typographical quote before submission

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38450]
## Description

A Sentry log reported Higher-Level Review are being rejected because of invalid characters in the submitted form data, specifically in the area of disagreement text. Michel reported that this has happened 126 times since v2 release. Veterans are including typographical apostrophes in the area of disagreement text, likely auto-inserted by the operating system. Lighthouse only accepts ASCII (windows-1252 format) when building the PDF (pattern: /[^\u0000-\u0255]+/), so as a quick-fix for this, we can replace typographical quotes with plain single quotes.

## Tasks

- [ ] Handle conversion of typographical apostrophes to plain single quotes
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complee
- [ ] All tests passing
