### ISSUE TITLE
Add codeowners to product-directory

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#38459]
## Issue Description
The QA Standards team must be designated as codeowners with required approvals for the product directory to ensure the integrity of our product directory ingestion process going forward. 
---
## Tasks
- [x] Add codeowners file
- [x] Change repository rules to require codeowners approval

## Acceptance Criteria
- [x]  When a PR is opened against master in the product-directory repository, it will require a review.
---

**Comment by pjhill** [comment]
Thanks for taking care of this!
