### ISSUE TITLE
[SW-Content] Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 3/14

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38451]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Robert Bonner
Ronald Pipkins

## Tasks
- [x] Replace text and videos (Selina)
- [x] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [ ] New videos and text are live on the page

**Comment by lunascoop** [comment]
@RLHecht the page has been updated and is ready for review and publishing. The Drupal page in edit mode says there's a link to an unpublished page (VHA), but I can't find it on the page. Perhaps that alert has always been there.

Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578
