### ISSUE TITLE
[Platform Content Team] Update assets and communications channels with new team name

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#38469]
## Problem statement
The recent Platform team reorg has been designed to reduce cross-functional team dependencies as well as create more accurate team names aligning to the products they support and own.

The team name has changed from "Content" to "Platform Content," and this will need to be updated in our documentation.

---
## Tasks
- [x] Rename Confluence Space from "Content Team" to "Platform Content Team" (Confluence should automatically update links)
- [x] Rename "Content Team" to "Platform Concent Team" on Confluence pages
- [x] Update slack channel name. (OCTO-DE) from vsp-content-ia to platform-content
  - [x] Need to determine new slack channel name
- [x] Github 
  - [x] team label from "content-ia-team" to "platform-content-team"
  - ~[ ] Update Github templates with new label~ does not apply
  - ~[ ] Github Operations team rename to Infrastructure team~ does not apply
- [x] Update GitHub project board name
- [ ] Uncover other places/spaces where Content & IA team name would be listed.
- [x] Update Roadmap/Vision (Liani, please verify if this is needed)
- Team member VA Slack profiles
  - [x] Liani
  - [x] Gretchen
  - [x] Amy
  - [x] Samara
  - [x] Jill
  - [x] Lauren
  - [Slack profiles naming guidance](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack)

Some items pulled from the list located in this [Team Restructure document by Andrea ](https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1920434211/Potential+VSP+Tech+Teams+Restructure)in Step 4.

## Acceptance Criteria
- [ ] Documentation will refer to the team as Platform Content Team

**Comment by lianilychee** [comment]
4/1 Fri:
- send message to jill samara gretchen lauren to update their va slack profiles with new team name
- begin a list of where content/ia would be written
