### ISSUE TITLE
Design a Platform Quality Assurance Dashboard Mockup

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38477]
## Issue Description
We need to create an initial mockup of the Platform QA Dashboard, designing it as a rollup of the Product QA Dashboards.

---
## Tasks
- [x] Review the Product QA Dashboards and work with team leadership to determine what should carry over (This dashboard is for higher level leadership, so may not need all cards on the base dashboard)
- [x] Mockup layout, review and refine based on feedback

## Acceptance Criteria
- [ ] Mockup has been created and refined

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/1118639976 All set here, complete with drilldowns! Still doing some refinement but ready for a review meeting.

**Comment by pjhill** [comment]
This effort is deprioritized for now. When we spin this initiative back up, we can do user research under a separate ticket now that a prototype / MVP has been created.
