### ISSUE TITLE
[UNPLANNED] Bug Ticket - COE prefill fix

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38487]
## Background
Not all data that should be prefilling on the COE is.  Step 2 works but Step 1 and Step 3 do not.

## Considerations
There will also need to be a FE vets-json-schema ticket to finish fixing step 1.

## Tasks
- [ ] Adjust 26-1880.yml to match properties on FE
- [ ] Adjust spec accordingly

## Acceptance Criteria
- [ ] A PR has been requested for merging, if needed
