### ISSUE TITLE
Update Collaboration Cycle operational guidance per VSA contract ending

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#38485]
## Issue Description
The VSA contract is ending April 7th. Currently we invite specific members to our review meeting if the product is VSA. We need to review our documentation and update it.

---
## Tasks
- [ ] Update the [design intent moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities) document
- [ ] Update the [midpoint moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities) document
- [ ] Update the [staging moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities) document

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chaseakirby** [comment]
New team named Shared Support Team. Will be Angela, Tze, DK, Mikki, Cindy Merrell, one new front end developer, PM - Eli Melon. 
Josh is dedicated specialist for benefits crew. Still trying to find out what his role is.

For this ticket, remove all references to VSA. Remove Tze, Josh, Angela.
In short, if VFS team wants to invite Shared Support team member, they need to invite them.
