### ISSUE TITLE
Product Directory: add Bool uses_authentication attribute

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#38493]
## Issue Description
Add `uses_authentication` attribute (type `boolean`) to the product directory CSV and Big Query schema so products that require authentication can quickly be discovered.

---
## Tasks
- [x] add Bool `uses_authentication` attribute to CSV
- [x] update the product directory table schema in BigQuery
- [x] update data ingestion if necessary

## Acceptance Criteria
- [x] The product directory is capable of determining whether a VA.gov product requires authentication for core user journeys
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by CBonade** [comment]
This was added as "loa" and requires a number designating the authentication level
