### ISSUE TITLE
tune individual vets-api instance settings

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#3849]
## User Story or Problem Statement
During a recent traffic spike on GIDS, it was discovered during investigation that the vets-api instances don't really have enough headroom to take large spikes like this without running into issues with thread capacity. Individual instances are running out of threads in puma long before any system constraint is exhausted. Other problems with this situation is that we're not utilizing hardware that's provisioned and auto-scaling rules are harder to work with when they're looking at things other than resource utilization directly consumable from CloudWatch. How might we tune individual instances to handle higher levels of traffic to better utilize hardware, add some insulation from traffic spikes, and enable easier auto-scaling rules?

## Goal
To ensure better utilization of hardware resources within auto-scaling groups to promote cost-efficiency as well as reduce risk of outage due to a service being overwhelmed and funneling up into other services. 

## Objectives or Key Results this is meant to further
Improved hardware utilization and auto-scaling events for cost-efficiency and outage mitigation.

## Acceptance Criteria
- [x] use locust to re-create / loadtest a simulated scenario like the GIDS-related outage that sparked this task set.
- [x] use finding from loadtest results to gather information to help optimize puma workers / threads.
- [x] conduct live trials with new configurations and monitor closely for hardware usage spikes / anomalies.
- [x] adjust accordingly in conjunction with monitoring findings
- [ ] adjust both puma threads and database pool size to allow an instance to be fully utilized
- [x] ensure auto-scaling rules trigger a scale-up of the cluster when the instances start running out of physical resources

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
I think a good place to start would be to build a locust script to re-create the scenario we saw from the GIDS-related outage to see if we can replicate it (and then prove that we succeeded in avoiding it once we finish this work).

A good example to start with is: https://github.com/department-of-veterans-affairs/devops/blob/master/loadtest/EWIS

The load originated from traffic on the GI Bill Comparison Tool: https://www.va.gov/gi-bill-comparison-tool/

**Comment by jbritt1** [comment]
I think there is possibly one more step in order to close this. @johnpaulashenfelter and I spoke this morning about perhaps lowering the starting number of vets-api-server instances on initial deploy(s).

**Comment by jbritt1** [comment]
To further prove the autoscaling will work as designed, I completed another load test against the staging environment. To be noted, I used a client count that is 10x what would have broken the environment prior to this work.

One can see below the asg monitoring is "in alarm" status.
![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/aa32c924-dedf-49ad-bae6-1ac514ba4507)

Additional node was auto-deployed due to alarm (one can observe today's date during the load test as the launch / creation time of this new instance):
![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/0a4f165b-36b5-4a9b-9286-a9294cb07cba)

**Comment by jbritt1** [comment]
For the scope of the epic, I personally feel we accomplished the increase in resiliency we were seeking. We also saw a small cost reduction by lowering our initial deployment count to prod. In my opinion, further work on this would warrant new tickets (and a new epic if large enough). Closing this one out.
