### ISSUE TITLE
Design intent [VA Notify Forms Strike Team - In Progress Reminders]

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#38501]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Strike/In%20Progress%20Notifications/read.md)
 
 
 
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] [User flow](https://app.mural.co/t/oddball5855/m/oddball5855/1645722089026/e305013d25f92df84c16583b7ae4ea70aa34395c?sender=ian7950)
- [ ] Research Plan
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by seanasewell** [comment]
[Design intent [VA Notify Forms Strike Team - In Progress Reminders]](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38501) has been scheduled for 3/17 at 1:30ET pm

**Comment by allison0034** [comment]
@hubgitian @megansiddle  can you share the comp please?

**Comment by hubgitian** [comment]
<img width="644" alt="Screen Shot 2022-03-17 at 12 17 44 PM" src="https://user-images.githubusercontent.com/10037396/158879109-cb1b5ed5-ddc3-44c5-a41d-cd279ddab84b.png">

**Comment by claytonzook** [comment]
No actionable feedback for research at this point. I will however reiterate the feedback offered in the meeting.

**Consider testing multiple aspects, which could include:** 
- how well does the email notification accomplish the expected action
- what is the best cadence, especially so it's considered a good reminder and not marketing/spam
- what features do application filler outers want in an email reminder

**Consider planning your testing to:**
- consider mobile users
- consider all ability levels
- consider less represented user groups
