### ISSUE TITLE
[Design, FE] My VA - Health Care update: Add new Walla Walla health care system as Cerner in My VA (by 3/26)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38508]
## Background 
Walla Walla, WA health care system will be moved to Cerner as of March 26.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert. 

> **ID 687** Walla Walla - March 26

[There is info in the My VA QA doc on how to log into staging to see/test a Cerner user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#test-cases-for-cerner-users)

![image](https://user-images.githubusercontent.com/92328831/158241648-a9f06fef-53bc-479a-b5f6-fc56d5d1b197.png)

## Tasks
- [x] [Design] Update mockup alert to show new copy change (below)
- [ ] [FE] Add filtering so Cerner alert will now show for Walla Walla, WA. The facility number is 687.
- [ ] [FE] Update the copy in the alert to be a **_static message_**, that will display regardless of which Cerner facility is returned, as follows:

For **VA Spokane health care, VA Walla Walla health care**, or **VA Central Ohio health care**: [Use My VA Health]()

For **any other VA health facility**, use [My HealtheVet]()

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by Samara-Strauss** [comment]
Things we need that I am currently tracking down:

1. The facility number, which I think we need for the code to determine who sees this alert.
2. The facility name. It is most likely not just "Walla Walla, WA"

**Comment by Samara-Strauss** [comment]
Facility code for Walla Walla, WA is 687 [per Slack](https://dsva.slack.com/archives/C02BTDTEPNH/p1647536512867649).

**Comment by lalexanderson-dsva** [comment]
I would recommend the following:

For VA Spokane health care, VA Walla Walla health care, or VA Central Ohio health care: Use My VA Health. 

For any other VA health facility, use My HealtheVet.

**Comment by lalexanderson-dsva** [comment]
cc @DanielleThierryUSDSVA, @davidconlon , or @JRRoof

**Comment by Samara-Strauss** [comment]
Great, thanks, @lalexanderson-dsva!

**Comment by aagosto90** [comment]
I updated the design so I wouldn't block this ticket but I do have a couple observations/questions. [Here's a link to the Sketch file with the updated Cerner alert.](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/KLE1Ve/a/nRE5MA4/)

The Sketch file wasn't up to date with staging and had something that looks more like this:
![Screen Shot 2022-03-22 at 5 49 09 PM](https://user-images.githubusercontent.com/97965610/159582034-a89eb3c6-72b4-4d0c-ade9-205208da6a3e.png)
which I think is great and has very clear call to action buttons but I'm just wondering where and why along the line we ended up with a more plain text and text links Cerner alert so I can update the Sketch file to match staging. I don't see a component that looks like this screenshot in the VA pattern library so I'm thinking maybe it didn't get approved and we had to stick with something more plain...but just a theory on why there's a discrepancy here. Does anyone have any insight into this? 

@Samara-Strauss @andaleliz @hdjustice @tmitchellgcio

**Comment by tmitchellgcio** [comment]
on it now

**Comment by JRRoof** [comment]
The following user is registered for multiple Cerner locations
IdmeLabs Cerner 3 - ***@***.***
[image: image.png]

Jeff Roof

Sr Product Manager

Ad Hoc LLC | adhoc.team

***@***.***

**Comment by tmitchellgcio** [comment]
@JRRoof that is a completely different Cerner modal. That is the Cerner Call To Action found on the health care manage benefits page

**Comment by hdjustice** [comment]
Validated that the copy was updated on the Cerner alert in staging under user 80
![image](https://user-images.githubusercontent.com/92328831/160125989-b296222e-bcdc-4ea2-a188-65628e620541.png)

@Samara-Strauss

**Comment by Samara-Strauss** [comment]
This looks good to me! Great job!

**Comment by JRRoof** [comment]
@hdjustice - Can you share the details of the user account you used in staging for Walla Walla so I can verify that the redirect notifications in VAOS are also working?

**Comment by hdjustice** [comment]
Hi @JRRoof - I used User 80 in this **[test user document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)**
