### ISSUE TITLE
[UNPLANNED] Bug Ticket - COE prefill fix (json-schema)

### ISSUE THREAD

**Issue by alsleaders** [department-of-veterans-affairs/va.gov-team#38509]
## Background
When prefilling the COE request in vets-website, the schema needs to look a certain way for the prefill to work correctly. To prefill the veterans full name, we need to make sure that the fields in the schema are labeled as such:
First name: `first`
Middle name: `middle`
Last name: `last`
Suffix: `suffix`

## Considerations
We will need to make the following adjustments to the `personalInformation.fullName` field in the schema:
`firstName` -> `first`
`middleName` -> `middle`
`lastName` -> `last`
`suffixName` -> `suffix`

## Tasks
- [ ] Adjust json-schema for prefill
- [ ] Adjust spec if needed

## Acceptance Criteria
- [ ] A PR has been requested for merging, if needed
- [ ] Associate vets-website ticket.
