### ISSUE TITLE
[UNPLANNED] Bug Ticket - COE prefill vets-website

### ISSUE THREAD

**Issue by alsleaders** [department-of-veterans-affairs/va.gov-team#38505]
## Background
Not all data that should be prefilling on the COE is.  Step 2 works but Step 1 and Step 3 do not.

## Considerations
This is the FE ticket to finish fixing step 1.

## Tasks
- [x] Adjust FE schema so prefill naming matches properties
- [x] Adjust spec accordingly

## Acceptance Criteria
- [x] A PR has been requested for merging, if needed
- [x] Associate vets-json-schema ticket.
