### ISSUE TITLE
Move Grafana graphs to DataDog

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#38518]
## Problem Statement 
With the move of vets-API to EKS, we will no longer be able to pull graphs out of Grafana due to the fact that Prometheus will no longer be used in the new infrastructure, this will prohibit us from pulling reports like the SLO report and others.

We might be able to address this by analyzing the graphs that we use within Grafana to ensure that they are helpful and then determine if they should be re-created within the new infrastructure (datadog) 

## Hypothesis or Bet
We will be able to determine which graphs we use now that are helpful and we will be able to recreate those within Datadog

## We will know we're done when... ("Definition of Done")
- We have determined which graphs need to be moved over to the new infrastructure 
- Those graphs/reports have been recreated within the new infrastructure 

## Known Blockers/Dependencies 
- None at this time
## Projected Launch Date
- ???

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platforminitiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

First, start with the graphs in the SLO report. These are graphs that are looked at on a monthly basis. 

- [ ] Look up Latency Graphs and latency functions
- [ ] vets-API dashboard
- [ ] Breakers?
- [ ] Backend service report?
- [ ] External service report?
- [ ] Job Queue? 
- [ ] Everything under VSP folder?

**Comment by ericboehs** [comment]
[We're discovering](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39877) which dashboards/graphs we own and which ones make sense to move.

**Comment by RachalCassity** [comment]
One issue is to get all the percentile data correct as seen in graphs, https://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?editPanel=1061&orgId=1&from=now-7d&to=now .


For the SLO reports, the graphs can be placed in a Datadog Notebook. Notebooks can have many metric graphs converted into one PDF.

**Comment by LindseySaari** [comment]
Notes for the SLO report percentiles:

We will most likely want to use [distribution metrics](https://docs.datadoghq.com/metrics/distributions/) to graph percentiles. See [Ruby code examples here.](https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/#code-examples).  DogStatsD will allow us to send distribution type metrics which statsd is unable to process/accept.

Step 1: Add the [config](https://dsva.slack.com/archives/CR838KMV1/p1652890429668339?thread_ts=1652888459.748939&cid=CR838KMV1) to the [docker-agent ansible task](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/datadog/tasks/docker-agent.yml) to enable DogStatsd.
Step 2: [Implement DogStatsd Client](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#install-the-dogstatsd-client)

- [Slack thread with Jeremy here.](https://dsva.slack.com/archives/CR838KMV1/p1652888459748939)
- [Original ticket here](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/21465)
- [See Original Issue](https://vfs.atlassian.net/wiki/spaces/VI/pages/1077412038/DataDog+Latency)

**Comment by LindseySaari** [comment]
I spoke with @mleclerc00 today, and unfortunately, it doesn't appear that there is a 1:1 migration from grafana/prometheus to DataDog in terms of the haproxy metrics. We discussed that we may need to find a different way to visualize that in datadog or explore a more custom solution instead of utilizing the haproxy integration. See [Matt's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42065#issuecomment-1176401259) for further details.

**Comment by npeterson54** [comment]
After speaking with thomas, we have work around for the % based metrics within datadog (these were blocking us).  Since we have these, i'm going to close this out.  This should be marked as done.

**Comment by npeterson54** [comment]
After speaking with thomas, we have work around for the % based metrics within datadog (these were blocking us).  Since we have these, i'm going to close this out.  This should be marked as done.
