### ISSUE TITLE
Define Researcher role in the Collaboration Cycle: Staging Review

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#38510]
## User Story
As a UX Researcher supporting the Governance team, I want to define my role for the Staging Review so that I know how to contribute to future Collaboration Cycle Staging Reviews with VFS teams.

As a UX Researcher supporting the Governance team, I want to define dependencies between the Research Plan Review and the Staging Review so that I can support VFS teams appropriately and inform the OCTO Research Lead of any concerns.

As a VFS team, I need to know what is expected of me/my team with regards to research at Staging Review so that I can ensure my team is prepared and able to meet Platform expectations.

- Intended Audience: VFS Teams/Platform
- Desired Outcome: Shared understanding of Researcher role at Staging Review
- Due Date: 

## Description
We have worked to establish the UX Researcher role in the Research Plan Review, but we still need to define how research as a practice area will be supported in the other Governance-owned Collaboration Cycle touchpoints, specifically Design Intent, Midpoint Review and/or Staging Review. The scope of this ticket is specifically for the Staging Review

## Artifacts Needing Updates
Platform Website: Collaboration Cycle/Staging Review
Confluence: Collaboration Cycle/Staging Review - Moderator Responsibilities
Confluence: Collaboration Cycle/How to provide feedback for a Staging Review
GitHub template: Staging Review

## Tasks
- [ ] Before you begin any editing of guidance, answer the following questions (copied from MPR ticket](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/36956) and changed for Staging Review):
   - Should Collab Cycle team member (aka the UX Researcher) be required to provide feedback tickets on the research practice area at Staging Review?
   - Will we need to request any research artifacts from the VFS team?
   - What role should research play at this point in the design process?
   - How does the timeline for research align with the timeline for Midpoint Review?
   - Should the agenda and/or objective of Midpoint Review be impacted by the addition of research as a practice area?
   - Will we want to request additional attendees from the VFS team and/or OCTO? for example, Shane?
   - Will the outcome of Midpoint Review be impacted by the addition of research as a practice area?
   - How do we intend to update the Midpoint Review script to include research?
- [ ] Create Documentation Drafts of the pages to be edited
- [ ] Update the pages as you see fit based off your responses to the above questions
 - ensure you are updating the pages consistently
- [ ] When updates are complete, comment on this ticket requesting a peer review

## Acceptance Criteria
- [ ] GitHub template: Midpoint Review has been updated per guidance
- [ ] Platform Website: Collaboration Cycle/Midpoint Review has been updated per guidance
- [ ] Confluence: Collaboration Cycle/Midpoint Review - Moderator Responsibilities has been updated per guidance
- [ ] Confluence: Collaboration Cycle/How to provide feedback for a Midpoint Review updated per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
I talked with Allison and Naomi about the relationship to research and Staging review. We decided it would be a good idea for me to first join several Staging Reviews to get a better understanding of this touchpoint and how or if research fits.

**Comment by claytonzook** [comment]
Adding some notes for thus far
- I've reviewed and attended 3-4 Staging Reviews
- of those I've had research feedback for 1, no feedback for the remaining
- the feedback for research was a question for a team about their UAT ticket on the research repo, and my question could potentially have been directed there instead of at the staging review meeting.

**Comment by chaseakirby** [comment]
Pulling issue out of initiative based on meeting with Chelen. Adding Tech-debt and Ready labels.

**Comment by claytonzook** [comment]
@chaseakirby I feel like I've been to enough Staging Reviews at this point and have not seen a need for Research practice area to be required representation at the Staging Review touchpoint.

The biggest items of interest for research at this point would be

- SR as possible contact point to remind teams to update Research Repo ticket with findings
   - Shane periodically sweeps the repo of research in progress so this isn't inherently necessary, nor is research representation at the SR for there to be a reminder about this.
- curiosity about how the design was iterated based on findings
   - research is often presented at the Monday design/research meeting largely satisfying this need
- discussing UAT plans
   - UAT is most often done by VFS teams as a live, limited release vs a usability testing format
   - The couple of teams that do UAT in a usability testing format submit to the Research repo and undergo the Research Review touchpoint, so there is another way for those couple teams to interact about this

**Comment by chaseakirby** [comment]
@claytonzook @shiragoodman I checked what we used for Design Intent regarding QA and Content, we only state that they will not provide feedback in the [Platform Website Design Intent Touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Outcome). We don't state this in the moderator responsibilities or How to provide feedback for Design Intent so I think following the same structure here makes sense. 
I will remove those items if that also makes sense to you both.
