### ISSUE TITLE
Conduct Stakeholder Discussions

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#38520]
## Issue Description
In order to inform good decisions on the Platform View, we will conduct discussions with various stakeholder groups to ensure we have a full understanding if the requirements

---
## Tasks
- [ ] Conduct internal discussion to determine questions list
- [ ] Talk to OCTO/Platform Leadership
   - [ ] Clarify any points from the research
- [ ] Talk to Analytics 
   - [ ] Where is the dashboard located?
   - [ ] Who is authorized to view the dashboard?
   - [ ] How can our teams collaborate to get better and more consistent results?
- [ ] Talk to Contact Center Team
   - [ ] ?

## Acceptance Criteria
- [ ] Discussions have been captured and results recorded in confluence
