### ISSUE TITLE
[SW-Content] Change H1 for existing "How to apply for a COE" page

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38522]
## Story
Prep work for the launch of the home loan COE.

## Resources
[Preview of UXpin](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap)
*Jason Wolf
*Jim Adams
*Mikki

## Task(s)
- [x] Change H1 to "How to request a VA home loan Certificate of Eligibility (COE)"
- [x] Update the breadcrumb on the page, left nav link, and top nav link
- [x] Update the hub page link
- [x] Update the link in the Records top nav (change "learn how to apply for" to "Request"), hub page and left nav

## Acceptance criteria
* H1 and pages and navigation updated
* Customer has link for reviewed and to provided any feedback.

**Comment by lunascoop** [comment]
@RLHecht I updated the H1
preview-prod.vfs.va.gov/preview?nodeId=44020

**Comment by bethpottsVADEPO** [comment]
@lunascoop Can you revert back the H1 change for http://preview-prod.vfs.va.gov/preview?nodeId=44020? The H1 for that page was correct as is. The H1 that needs changing is for this page: https://www.va.gov/housing-assistance/home-loans/how-to-apply/

Thanks!

**Comment by lunascoop** [comment]
@RLHecht I updated the H1 for the correct page
preview-prod.vfs.va.gov/preview?nodeId=754

**Comment by RLHecht** [comment]
@bethpottsVADEPO The meta title is now too long. Can we use COE? So it would be "How To Request A VA Home Loan COE | Veterans Affairs"

**Comment by bethpottsVADEPO** [comment]
@RLHecht Yes, that works, thank you!

**Comment by RLHecht** [comment]
@bethpottsVADEPO Per our slack, I updated the page in a few places where we were saying "apply" and changed them to "request." Let me know if these are OK to publish when I publish the H1 and menu changes. preview-prod.vfs.va.gov/preview?nodeId=754

**Comment by RLHecht** [comment]
I changed the H1 and the links mentioned at the top of the page as well as links in a few other places. We still need to change teaser text and in-page content from "apply" to "request" in the following places (besides the How to request a COE page):

- [Housing hub landing page](https://www.va.gov/housing-assistance/)
- [Records hub landing page](https://www.va.gov/records/)
- [Housing eligibility page](https://www.va.gov/housing-assistance/home-loans/eligibility/)
- [Cash-out refinance loan page](https://www.va.gov/housing-assistance/home-loans/loan-types/cash-out-loan/)
- [NADL page](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/)

Do we also want to change the language from "apply" to "request" when we are talking about COEs for surviving spouses? If so, we want to update the text on the following pages:

- [Funding fees and closing costs page](https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/) 
- [Housing eligibility page](https://www.va.gov/housing-assistance/home-loans/eligibility/)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thank you for identifying all these changes that are needed. Go ahead and make those changes and publish!

**Comment by RLHecht** [comment]
Thanks @bethpottsVADEPO I made all these additional changes and published those pages. Moving this ticket to validate.
