### ISSUE TITLE
[FE, Design] My VA - Health care update: Add new Columbus health system as Cerner to My VA (April 2022)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38551]
## Background 
For My VA, we need to add the Columbus, OH health care system to Cerner in April.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert.  

> **ID 757** - Columbus: Go-live -- 4/30/2022

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for Columbus. The facility number is **757**.
- [x] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket #39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))
- [x] [Design] Update copy for Columbus launch

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by hdjustice** [comment]
FYI list of all facilities moving to Cerner 
>Lauren Alexanderson
>Here are the facility codes for those:
>
>- (668) Mann Grandstaff VAMC   - Already on My VA
>- (687) Walla Walla, WA   - On My VA as of March 26th
>- (757) Columbus, OH - Scheduled for My VA at End of April
>- (463) Alaska VA   
>- (663) Puget Sound (Seattle WA)   
>- (692) White City, OR   
>- (648) Portland, OR    
>- (531) Boise,ID   
>- (653) Roseburg (Roseburg OR)

**Comment by ajakabcin** [comment]
@aagosto90 I believe the copy that needs updating is documented [here](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/nRE5MA4)

**Comment by aagosto90** [comment]
@lalexanderson-dsva @DanielleThierryUSDSVA Do either of you know what copy we should use on the Cerner alert for the Columbus, OH facility? 

For reference the current alert reads: For VA Spokane health care, VA Walla Walla health care, or VA Central Ohio health care: Use My VA Health (opens in new tab)

Thank you!!

[Screen Shot 2022-04-21 at 1.40.22 PM.png](https://images.zenhubusercontent.com/61f2dbbca50e2e3e2b4d0a11/e8188969-b3db-4523-b840-a3522a581ccd)

**Comment by tmitchellgcio** [comment]
I can check that the code is in staging and maybe prod but we won't see this until the 30th so I am not sure we can validate the code is working until then unless me proving the code is in there is enough. @ajakabcin

**Comment by ajakabcin** [comment]
see screenshot in PR for validation
