### ISSUE TITLE
Research synthesis and reporting: HRT Static Landing Page 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38569]
## Description 
Wrap up research study and associated documents/resources

## Tasks 
- [x] Clean up notes spreadsheet 
- [x] Write topline summary and share out with team
- [x] Add participant characteristics into MVS checker (for marginalized groups)--do participant characteristic tallies in the spreadsheet and then put the totals into the report
- [x] Do data analysis/synthesis of data collected from research  
- [x] Write research report

**Comment by cindymerrill** [comment]
Thanks for creating this ticket, @brianalloyd !

**Comment by cindymerrill** [comment]
Drafted topline summary and shared out with team: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/static-landing-page/topline.md

**Comment by cindymerrill** [comment]
Cleaned up notes spreadsheet so ready for synthesis

**Comment by cindymerrill** [comment]
Add participant characteristics into MVS checker (for marginalized groups) and copied summary into report. Got started on data synthesis.

**Comment by cindymerrill** [comment]
Finished drafting research report and shared with Danielle Thierry, Martha Wilkes, and Angela Fowler for feedback on Monday. I plan to share the key findings during Tuesday's Sprint Demo before rolling off this project and contract.
