### ISSUE TITLE
[Research] Create Research Trip Report

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38570]
## User Story
- As a product team, we want to document and share the findings from the site visit to St. Louis where we spoke with Veterans and Staff.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Veteran Research plan and Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback)
- [Staff Research plan and Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback)
- Synthesis for this report completed in #35886.

## Description
A research report detailing findings and design recommendations from the site visit to St. Louis where we spoke with Veterans and Staff.

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md
)
- [x] Conduct the [inclusive design analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/risk-documentation.md)

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [x] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines). The existing repo tickets for this research are:
  - Veteran ([Ticket #68](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/68))
  - Staff ([Ticket #79](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/79))
- [x] Create necessary issues/tickets that address findings in coordination with Lori
- [x] Schedule readout sessions with
  - Stakeholders (talk to Patrick about when to do this)
  - team (either via Slack or Zoom meeting)
  - [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by benbrasso-agile6** [comment]
@ytsaoca here is a link to the Vet presentation I'm working on. It's a work in progress, but wanted to share the link - https://docs.google.com/presentation/d/1kw_cfHkJXzjZ1w8AsnIIEW5Gc9_bygOwxJ71Sn2i6iw/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
Update: 

Have most of Veteran slides finished.
Team has decided to create one presentation. I will work on creating/migrating staff findings into the deck tomorrow. (Ya-ching is working on moving some Mural findings into slides for me to look at.)
Will also need to edit some of the overall organization to make sure it reads well for both Vet and staff research. 

Presentation is located here FYI @sarahknoppA6 @loripusey @kristenmcconnell @zach-park @ytsaoca 

https://docs.google.com/presentation/d/1kw_cfHkJXzjZ1w8AsnIIEW5Gc9_bygOwxJ71Sn2i6iw/edit#slide=id.g892adcb623_0_141

Will provide another update tomorrow.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell @ytsaoca @zach-park Could you guys take a final look at the [presentation](https://docs.google.com/presentation/d/1kw_cfHkJXzjZ1w8AsnIIEW5Gc9_bygOwxJ71Sn2i6iw/edit?usp=sharing)?

**Comment by benbrasso-agile6** [comment]
Still working through these items in the ticket. Got the research findings started for [staff](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/research-findings.md). 

Will need to chat with @loripusey about whether I should continue with wrapping up the St Louis tickets or switch to [40597](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/40597
) and/or [41452](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/41452).

**Comment by benbrasso-agile6** [comment]
Finished staff research report - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback/research-findings.md

**Comment by benbrasso-agile6** [comment]
Moved tickets in research repo to Complete column
