### ISSUE TITLE
[SW-Content] Review, Copy edit and publish updates to COVID-19 Vaccine pages [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38573]
## Story
As a Veteran I need current and updated information for COVID-19 vaccines, so I can  find my best health care solution.

## Resources:

http://preview-prod.vfs.va.gov/preview?nodeId=11463

## Task(s)
- [x] Review and copy edit changes made to COVID-19 Accordion on main page.
- [x] Audit/Update Chatbot/translated pages to align with and match chagnes.
- [x] Publish drupal pages

## Acceptance Criteria
* Pages are updated and published

**Comment by lunascoop** [comment]
@RLHecht here are the translated pages ready for review.

Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413
Vacunas contra COVID-19 en el VA: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published these.
