### ISSUE TITLE
BE - Auth Profile - Bad Address Indicator - BE Discovery - Email Notifications

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38583]
## Background

As part of the Bad Address Indicator enhancement to the VA.gov Profile, we want to proactively send email notifications to Veterans whose current mailing address has been flagged as being invalid for that individual.   This email is meant to notify them about their address and direct them to the VA.gov web site to log in and update their address.

The [VA Notify](https://dsva.slack.com/archives/C010R6AUPHT/p1644945119279509) team has an API for sending bulk emails, and the Swagger documentation is located at [https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml).

 Additional information may be found at [https://github.com/department-of-veterans-affairs/notification-api/blob/master/README.md](https://github.com/department-of-veterans-affairs/notification-api/blob/master/README.md).

We will be calling VA Notify to send email notifications to Veterans informing them that their mailing address has been denoted as invalid and giving them an opportunity to review and update it:

- An initial blast to the ~340k people whose mailing addresses are currently flagged as invalid
- Emails that go out on a schedule (daily? weekly?) to anyone whose mailing address has been flagged as invalid since the last time we checked. 

Ideally the same process would be used to do the initial blast and the subsequent notifications.   

### Resources:

- The [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/meeting-notes/2022-01-25-call-with-barry.md) the PM has gathered to date is located in the project folder.  This includes links to VA Notify's documentation, staging & prod environments, a link to the initial email draft.
- [Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/meeting-notes/2022-01-25-call-with-barry.md) from our January meeting with Barry Wilbanks to discuss the indicator in VA Profile.
- [Scott James](https://governmentcio-fed.slack.com/team/U02F0L54WF5), BE engineer on the Debt Resolution team has recently used VA Notify to create notifications for that team, and has been tagged as a good resource to reach out to. 

## Tasks
- [x] Follow-up meeting with Barry to find out how to access the flag and retrieve the Veteran's ICN and any other fields to be passed to VA Notify
- [ ] Meet with Scott James to get some insight on how to use VA Notify from a BE perspective, as well as any formal review of your solution that may be required
- [x] Review VA Notify's documentation 
- [ ] Determine the process/format for adding the following pieces of information to an email: 
   - [x] Veteran's name (First and Last)
   - [ ] URL for logging into VA.gov Profile
   - [ ] Email subject line (including whether we are able to include the recipient's name)
   - [ ] Email body content (including whether we are able to use variables to insert recipient details within the body)
- [ ] Determine any API batch parameters we need to set (number of messages per batch, hour, etc.)
- [ ] Determine any limits we need to adhere to (x messages per hour, day, etc.)- [ ] Document a high level solution
- [ ] Identity tasks required to retrieve data for all Veterans who currently have mailing addresses flagged as invalid
- [ ] Schedule meeting with the team as needed to discuss API parameters that need additional info/conversation 
- [ ] Review with the team

## Acceptance Criteria
- [x] Follow-up meeting with Barry to find out how to access the flag and retrieve the Veteran's ICN and any other fields to be passed to VA Notify
- [ ] Meet with Scott James to get some insight on how to use VA Notify from a BE perspective, as well as any formal review of your solution that may be required
- [x] Review VA Notify's documentation 
- [ ] Document a high level solution
- [ ] List back-end tasks required to export data from VA Profile API and import into VA Notify API in a reply to this ticket
- [ ] Estimate back end tasks given knowledge at hand in the same reply
- [ ] Review with the team
- [ ] Determine answers to above items
- [ ] Document answers to above items as part of technical documentation

**Comment by SKasimow** [comment]
Consolidated this ticket with #37000.

**Comment by tpharrison** [comment]
@SKasimow  and I met with Barry Wilbanks on Apr 22nd to determine how to access the 360k+ users with bad addresses so that we can send them email notifications.

Barry stated that currently there is no way for us to access this data aside from requesting a report.  To grant us programmatic access to the data, the VA Profile team will need to go through an intake process which will take ~9-10 weeks.

cc/ @Samara-Strauss

**Comment by Samara-Strauss** [comment]
>Barry stated that currently there is no way for us to access this data aside from requesting a report. To grant us programmatic access to the data, the VA Profile team will need to go through an intake process which will take ~9-10 weeks.

This is unfortunate, but it might actually be OK. I don't think we're launching this work any time soon given our other projects. I'll add a request for this in the VA Profile Sharepoint.

**Comment by SKasimow** [comment]
Closing discovery effort
