### ISSUE TITLE
Conduct Research Survey

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#38600]
## Issue Description
In order to enhance the capabilities of Review Instances, we should first understand how they are currently being used by teams. Create a user research survey to get initial insights to help guide our approach.

---
## Tasks
- [x] Collect potential questions for stakeholder discussion
- [ ] Create a survey and send out to teams
- [ ] Follow-up with reminders and notices to help encourage good participation
- [ ] Distill findings and share with leadership

## Acceptance Criteria
- [ ] Survey was conducted and ended successfully
- [ ] Results have been distilled and reported out to leadership

**Comment by JoeTice** [comment]
Survey was created, reviewed and revised - current version is located here: https://adhoc.optimalworkshop.com/questions/oi0c64tv-0
- Reviewed 4/11 - Joe T.
- Reviewed 4/12 - Naomi

Waiting for approval to send this out to teams

**Comment by JoeTice** [comment]
Will need to update the research survey once the research plan is defined.

**Comment by JoeTice** [comment]
Initiative has been deprioritized and is no longer relevant
