### ISSUE TITLE
Research current review instance configuration and how to integrate test data into review instances

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#38611]
## Issue Description
This task is to conduct preliminary research on the larger epic of improving review instance capabilities and creating a test data harness.

---
## Tasks
- [ ] Document current configuration of review instances
- [ ] Determine if there are any metrics available for review instances
- [ ] Identify key stakeholders
- [ ] Prepare questions to survey engineers and stakeholders about review instances
- [ ] TBD

## Acceptance Criteria
- [ ] Current review instance capabilities are documented
- [ ] A survey is prepared or a meeting with stakeholders is scheduled
- [ ] A modified review instance with basic test harness capabilities is created

**Comment by ddzz** [comment]
`vets-website` review instances rely on an `app.json` configuration defined in the repo root. A post-deploy script currently runs after the front-end is built, and we should be able to modify this script for creating test data.

According to the Console Services team, `vets-api` review instances are configured with Ansible. I have not been able to find the exact configuration file for this. This may complicate creating back-end test data.

**Comment by pjhill** [comment]
@ddzz -- 
- [ ] add detailed notes to this ticket
- [ ] define next steps

**Comment by pjhill** [comment]
@ddzz 
- [ ] Create a Google Doc that is a draft of survey questions to ask VFS teams about Review instance use and desired features

**Comment by pjhill** [comment]
Key stakeholders --

1. Infrastructure
2. Console Services
3. QA Standards
4. VFS Teams

**Comment by ddzz** [comment]
Summary of current review instance configuration:

Users must be connected to the SOCKS proxy to access review instances. The primary Ansible devops config is in [this `Jenkinsfile`](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/review_instance_deploy). This file contains configurations for `vets-website`, `vets-api`, and `content-build`.

`vets-website` uses [this Docker configuration](https://github.com/department-of-veterans-affairs/vets-website/blob/master/docker-compose.review.yml) to create review instances. [This script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/review-entrypoint.sh) runs when each review instance spins up. `content-build` is built in this script, which takes some time to be built before the review instance is ready to be used. A test harness would likely be integrated into this script to create test data. The test data itself would likely need to be included in each PR. `content-build` instances are built similarly, but they do not have their own Docker configuration.

`vets-api` has its own [Docker configuration](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docker-compose.review.yml) that starts up `vets-api` itself along with the services it interacts with such as Postgres and Redis. Most likely the Docker configuration would need to be modified along with creating VCR interactions for a back-end test harness.

It's possible to `ssh` into review instances to view logs and interact with them. A SOCKS proxy connection is needed to do this.

**Comment by ddzz** [comment]
Next steps:

- [ ] Brainstorm survey questions
- [ ] Create simplified test harness example
- [ ] Distribute survey and analyze results
- [ ] TBD

**Comment by pjhill** [comment]
Created a survey here -- https://adhoc.optimalworkshop.com/questions/oi0c64tv
