### ISSUE TITLE
QA Dashboards Standardization & Product Definitions

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38626]
## Issue Description
The QA standards teams has created product level QA dashboards.  We would like to explore how we could bring them into our standardized dashboard portfolio and align on product definitions.

QA Dashboard:
https://va-gov.domo.com/page/1950369682

QA Dashboard Documentation:
https://depo-platform-documentation.scrollhelp.site/developer-docs/QA-Dashboard-Documentation.2013200394.html

Product Directory:
https://github.com/department-of-veterans-affairs/product-directory/blob/master/CSVs/CombinedProducts.csv

---
## Tasks
- [x] Review look/feel - how can we standardize to resemble our standardize KPI dashboards
- [x] Identify data sources and determine if there is any other meaningful data we may want to add and how we may want to connect if applicable
- [x] Review product directory and align on product definitions
- [x] How can we link the kpi and qa dashboards for a given product so it is easy to go back and forth easily.  Would it make 

## Acceptance Criteria
- [ ] We have a plan for next steps based on above analysis
---

**Comment by chloedotbrown** [comment]
#### Look & feel
We could easily apply the Analytics team's color palette to the QA dashboards. While the dashboards themselves are separate Domo pages, it seems that all of them share the same cards to which product filters apply. Therefore, in a world where we were pursuing this project in Domo, we would need to recolor all the dashboards and text boxes individually, but should only have to recolor the actual data cards once.

#### Data sources
No, there are not any additional data sources we currently have access to that seem like they make sense to be added to the QA dashboard. Likewise, there are no datasources here I'd recommend we integrate into the current KPI dashboards. Each seems well-scoped for their purpose. However, it may make sense to inter-link the dashboards - possibly a link to the QA [landing page](https://va-gov.domo.com/page/1950369682) on KPI dashboards and a link to the [eligibility dashboard](https://va-gov.domo.com/page/1550814739) on the QA dashboards?

#### Product directory
I'm not sure how this list was created, but I think there's still a good deal of work needed to sync this list and the Governance team's [team list](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2444951). The Product Directory will likely one day be a much more complete accounting of products under development, but I do see a lot of products and teams currently missing in this version. Standardization of team name fields across datasources is especially important, since it's usually what we have to join on to combine Platform data sources.

#### Making available dashboards easier to find
Domo really doesn't have great options for this. Our best bet would be to create a new page with "buttons," similar to the way we linked data dictionaries and how-to docs on the KPI dashboards - possibly assign as the Domo homepage for VFS users.

**Comment by chloedotbrown** [comment]
### April 11th meeting meeting with QA team:

#### Product List + VFS Roster
We discussed need for being able to join [VFS roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) and [Product Directory](https://github.com/department-of-veterans-affairs/product-directory/blob/master/CSVs/CombinedProducts.csv) for Domo tracking of Analytics team products. QA team would like to use Github team label for most accurate joins. This field is not currently on VFS Roster, but it _is_ included in 2nd tab of VFS teams.

Options to leverage:

- Governance team (or team maintaining roster) adds `Github label` column to VFS Roster's sheet of individuals.
- Governance team (or team maintaining roster) commits to maintaining VFS team-level sheet in addition to individuals. QA to ensure that `Team Name` and `VFS Team` options are consistent - possibly add data validation to ensure new entries only pulled from team list.

#### Sharing resources
@michelle-dooley is it worth making a copy for the QA team of our [backlog list](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit#gid=1660978947)? There's fields there they certainly don't need, but it might help them cross-check their current list, and it's possible some of our data may be more current than theirs.

**Comment by michelle-dooley** [comment]
@chloedotbrown yes.  We are going to be in charge of maintaining the VFS roster going forward.  We can discuss more.

**Comment by michelle-dooley** [comment]
Closing this ticket.  Continued work take place on VFS roster ticket and larger Cross Platform Dashboard strategy ticket.
