### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Run and Record Specs in Staging

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38627]
## Background

Once the VA Profile demographics API is ready in the staging environment, PI related specs will need to be run and recorded.

## Tasks
- [ ] Run and record specs for GET demographic
- [ ] Run and record specs for PUT preferred name
- [ ] Run and record specs for PUT gender identity
- [ ] Run and record specs for PUT pronoun
- [ ] Run and record specs for PUT sexual orientation

## Acceptance Criteria
- [ ] Run and record specs for GET demographic
- [ ] Run and record specs for PUT preferred name
- [ ] Run and record specs for PUT gender identity
- [ ] Run and record specs for PUT pronoun
- [ ] Run and record specs for PUT sexual orientation

**Comment by tpharrison** [comment]
This ticket is being zeroed out and replaced by the following tickets:

- #38796 BE - Auth Profile - Personal Info Revision - Record Specs in Staging and open PR for Preferred Name
- #38797 ​​BE - Auth Profile - Personal Info Revision - Record Specs in Staging and open PR for Gender Identity
- #38798 BE - Auth Profile - Personal Info Revision - Record Specs in Staging and open PR for Pronoun
- #38799 BE - Auth Profile - Personal Info Revision - Record Specs in Staging and open PR for Sexual Orientation
-
