### ISSUE TITLE
Grafana Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38621]
## Issue Description
VFS teams have data needs outside of what Google Analytics can provide.  We need access to more back end systems to provide additional details about user behavior.  For example how many people saved a form to complete at a later time.  It is challenging to answer these types of questions with GA data that is not intended for these use cases.  We need to explore Grafana, what data would be meaningful and how we connect to include in Domo dashboards.

---
## Tasks
- [ ] Get access to Grafana
- [ ] Explore data and learn the system
- [ ] Identify data sources of interest
- [ ] Research how we can connect to BQ

## Acceptance Criteria
- [ ] We will add additional Grafana data to our dashboards as applicable.
---

**Comment by jonathan-epstein13** [comment]
Creating a worksheet to see which metrics/dashboards in Grafana would work with any of our standard datasets/dashboards.

**Comment by jonathan-epstein13** [comment]
[Grafana Worksheet](https://docs.google.com/spreadsheets/d/1avazBbXuuubicPCioNxrgwBSQmEUT6jtKTh6PIiOHZs/edit#gid=0) Here is the ongoing worksheet for Grafana discovery.
