### ISSUE TITLE
Define & Document Standardized QA Process 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38628]
## Issue Description
We need to create a defined QA process throughout the data flow (from the beginning of the data pull all the way through to dashboard release).  We spend a lot of time trouble shooting data issues further down the pipeline we could save time if we identify issues before we go too far in the process.  We need to define a standard process and ownership for each step along the way.

For example, possible steps to consider and define QA standards at each 
1) Raw data pulled into BQ
2) Data ETLs
3) BQ/Domo datasets
4) Domo cards

---
## Tasks
- [x] Meet with team to brainstorm on QA best practices
- [x] Define process steps/pipeline and where QA should take place along the way
- [ ] Create check list for each type of QA throughout data pipeline
- [ ] Create list of items to review at each step and ownership of each

## Acceptance Criteria
- [ ] Standardized/Define QA process 
---

**Comment by chloedotbrown** [comment]
Here's a draft of the [Dataset Request Form](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit#gid=0) we discussed in our QA process meeting. I've left off any potential section for "suggested QA," since I think those steps might want more work to identify.

@obrienjulie - tagging you for next steps on moving this piece forward. What's missing here to get you the info you need?

**Comment by chloedotbrown** [comment]
@michelle-dooley I've created a [draft](https://vfs.atlassian.net/wiki/spaces/AT/pages/2161246279/WIP+-+QA+Process+Standardization+Brainstorm) of the synthesis of our QA processes brainstorm session. Let me know if there's anything you'd like to build out further before we start tagging folks to create/document processes. I've also created a high-level [visualization ](https://docs.google.com/presentation/d/1rUBcyUeto_1vibVkUoOGKYe0csX6luz46Hrxo5A0vho/edit#slide=id.g124a410377e_0_0)of QA opportunities and current practices in our data flow - it's saved on the drive, embedded in the Confluence page, and anyone on the team should have edit access to update as we change.
