### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Ability to omit unapproved fields from transactions

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38623]
## Background

The original scope of the Personal Info Revision enhancement included the addition of four new fields:
- Preferred name
- Gender identity
- Pronouns
- Sexual orientation 

We recently learned that Pronouns and Sexual orientation have not yet been approved by OMB, so cannot be visible or otherwise exposed when the MVP goes live.  

Since much of the FE work had already been completed when we learned of this change, the two unapproved fields will be hidden behind a feature flag in Staging and Production so that minimal work is needed to add them later.  Likewise, the backend should contain logic that includes the two unapproved fields, but will keep them hidden in requests/responses so they cannot be found or exploited in the interim.

## Tasks
- [ ] Employ a mechanism that enables the unapproved Pronouns and Sexual orientation fields to included in the BE code along with the approved fields, but omit them from transactions until they have been approved and explicitly made visible by removing the feature flag in the FE.
- [ ] Test to confirm the fields are not part of any request or response in Staging or Production.
- [ ] Document in project folder the process for "activating" the fields once approved.

## Acceptance Criteria
- [ ] Employ a mechanism that will allow the Pronouns and Sexual orientation fields to included in the BE code, but omit them from transactions until they have been approved and explicitly made visible by removing the feature flag in the FE.
- [ ] Test to confirm the fields are not part of any request or response in Staging or Production.
- [ ] Document in project folder the process for "activating" the fields once approved.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Closing; we are not going to add pronouns and sexual orientation until approved.
