### ISSUE TITLE
Implement text changes to "Check the status of your VA home loan COE" landing page in COE prototype

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#38632]
## Background
The "Check the status of your VA home loan COE" page is the entry point to a user's COE status. It's essentially a public landing page with general info about the process and status. There were wholesale revisions to the page's copy to bring the content in line with other VA.gov tool landing pages.

### Considerations
The COE prototype has been in design and development for more than one year. Recent revisions will bring the old page layout into agreement with the latest landing page screen designs.

- [Link to the UXPin prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140810030)

### Tasks
- [x] Implement changes to UXPin screen
- [x] Connect new screen/content to prototype functionality

### Acceptance criteria
- [x] New prototype screen with text and layout revisions in place
- [x] New screen connected to prototype functionality
