### ISSUE TITLE
[FE] Profile: Remove 'address' from home and mailing fields

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#38637]
## Description

To maintain consistency with the other profile fields (phone, email), the address field titles should be Home and Mailing instead of Home address and Mailing address. This does introduce some additional complexity, since the field name is passed to the component, and that makes the title change require some logic to remove the word before rendering the titles.

## Tasks

- [ ] Parse title string before rendering to remove 'address'
- [ ] Make sure button aria label is still correct for edit and remove buttons on these two fields
- [ ] Tests updated

## Acceptance Criteria

- [ ] Address fields in profile do not include 'address' in field titles
- [ ] Notify PM when ready for review on staging

**Comment by Samara-Strauss** [comment]
Before we make this change, can we check on whether accessibility signs off on this? I'm unsure of whether the right move is to remove "address" or to add "phone number" to the phone number fields. I'd like accessibility to weigh in on what is the most friendly to screen reader users. If they are OK with removing "address", then it's OK by me.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss I spoke with @cgednalske about accessibility and verified that we had spoke with Angela about this specifically and that because of the main headings that it would be fine to remove 'address' from the two field titles.

**Comment by adamwhitlock1** [comment]
@SKasimow You can validate this now, as it is live on staging.

![Screen Shot 2022-05-04 at 3.53.28 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/c75a7be6-121f-4aa1-9da7-4bb44163d40e)

**Comment by SKasimow** [comment]
@adamwhitlock1 - just tested with a staging account and am seeing the updates as you show in the screenshot above.

**Comment by Samara-Strauss** [comment]
>  Do you know if it is supposed to be released at 100%?

If this is a question about production, yes, a small update like this can go out to 100% of folks. We don't need to do phased releases for copy changes.

**Comment by SKasimow** [comment]
@adamwhitlock1 - good to go for Monday
