### ISSUE TITLE
[SW-Content] Review Sitewide "BLOCKED" stories and immediate action to take, or request of guidance/next steps [SWC] 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38634]
## Story/Issue
Review all stories that are sitting in Blocked and determine next steps to remove blockers and drop into next sprint for immediate action.  All items that are undetermined or unclear to be brought to OCTO Sitewide PO for direction of next steps.

## Resources
**Stan Gardner to set up collaboration meetings**
Sitewide Content Blocked column

## Tasks
- [ ] Attend review meeting to review and determine actions
- [ ] Document actions to be taken for each BLOCKED story
- [ ] Set up meeting with Sitewide Content POs to review undetermined Blocked stories. (for guidance)  

## Acceptance Criteria
**Blocked stories are moved to Ready, Current Sprint, or Backlog and stakeholders are informed**

**Comment by RLHecht** [comment]
@SgardnerPMP I reviewed all the tickets that are currently in blocked and added comments or asked product teams for further info on the ones that I wasn't sure about.
