### ISSUE TITLE
Update User flow instructions and template link

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#38636]
## User Story
As a governance team reviewer, I want to see granular user flows so that I can better understand user interactions and actions.

- Intended Audience: VFS Teams
- Desired Outcome: Updated user flow diagrams templates
- Due Date: N/A

## Description
During a recent Governance team retrospective, we identified a potential opportunity to add an updated user flow diagram to the design system to encourage VFS teams to provide more granular information on user interactions and actions.

## New Artifacts 
Design System User flow with swimlanes

## Tasks
- [ ] N/A

## Acceptance Criteria
- [x] Reach out to Design System for guidance on providing an updated template
- [ ] Coordinate with Design System to create updated template
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024. This ticket is no longer relevant to Governance team and/or Platform crew.
