### ISSUE TITLE
Tonic API Research & Write-Up

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#38635]
## Issue Description
As a VA Stakeholder, I want information about whether or not the TONIC API would support the current Patient Check-In experience. (sorry this is not from user perspective, don't know enough about it.)
---
## Notes
This is a research task from Stephen- not sure if we will actually use Tonic, but the research write up is required. Would ideally like to have completed by end of week (March 18 COB) if possible. 

It sounds like we don't have much information on Tonic right now, so we need a determination if the value promised (ability to get cerner data and also to connect to VistA) seems to be worthwhile. Perceived value is that it may support appointment info and digital health forms.
---
## Tasks
- [ ] Review the Tonic API endpoint provided by Stephen 
- [ ] Determine if our MVP product will or will not be able to support Tonic
- [ ] Synthesize information and write up a doc that Stephen can reference with supporting information
- [ ] Post document to GitHub and follow up with Stephen

## Acceptance Criteria
- [ ] Output: Gap analysis document created including gaps we see with using Tonic, any perceived value from using Tonic, risks, determination of whether or not our current state MVP would support usage of it. Doc should include recommendation on whether or not to use based on this information.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sarahknoppA6** [comment]
@stephenBarrs Here is the ticket for Tonic research, please feel free to add info and resources!
cc @acrollet @randomsync

**Comment by acrollet** [comment]
@randomsync and I worked on this this afternoon and provided the synthesis to @stephenBarrs. Stephen, will you let us know if you'd like us to post it to the team space on github? Thanks!

**Comment by acrollet** [comment]
Closing this out - @stephenBarrs please let us know if you want the document posted to github and/or need further effort on this. Thanks!
