### ISSUE TITLE
FE - Auth Profile - Personal Info Revision- Add feature flag to hide two unapproved fields

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38639]
## Background

The original scope of the Personal Info Revision enhancement included the addition of four new fields:
- Preferred name
- Gender identity
- Pronouns
- Sexual orientation 

We recently learned that Pronouns and Sexual orientation have not yet been approved by OMB, so cannot be visible or otherwise exposed when the MVP goes live.  

Since much of the FE work had already been completed when we learned of this change, the two unapproved fields will be hidden behind a feature flag in Staging and Production so that minimal work is needed to add them later.  Likewise, the backend should contain logic that includes the two unapproved fields, but will keep them hidden in requests/responses so they cannot be found or exploited in the interim.

## Tasks
- [x] Implement a new feature flag that will allow the Pronouns and Sexual orientation fields to be included in the FE code, but hidden on Staging and Prod until they have been approved and can be used.
- [ ] Test with BE to confirm the fields are not part of any request or response in Staging or Production.
- [ ] Document in project folder the process for "activating" the fields once approved.

## Acceptance Criteria
- [x] Implement a new feature flag that will allow the Pronouns and Sexual orientation fields to be included in the FE code, but hidden on Staging and Prod until they have been approved and can be used.
- [x] Test with BE to confirm the fields are not part of any request or response in Staging or Production.
- [ ] Document in project folder the process for "activating" the fields once approved.

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
This looks perfect @adamwhitlock1!  FYI to @Samara-Strauss - if you open Gender identity, it's still checkboxes (multi-select), but @adamwhitlock1 has a task to change that back to radio buttons (single select)

**Comment by Samara-Strauss** [comment]
Fantastic! This looks great.
