### ISSUE TITLE
[UNPLANNED] Payload Check for LGY

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38641]
## Background
Per Kelli, certain parts of the LGY application are not being passed through to the back end correctly

## Tasks
- [x] Add middle name and suffix
- [x] Add still owned indicator
- [x] Add entitlement inquiry

## Acceptance Criteria
- [x] A PR has been requested for merging, if needed
