### ISSUE TITLE
[EKS] Reorganize traefik deployment for better separation of environments

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#38643]
## Description
Traefik is deployed in eks using the helm chart (https://github.com/traefik/traefik-helm-chart)

However every values file (dev/staging/sandbox/utility/prod) inherits from the same Chart.yaml.  Which is also true for all the deployments we have currently that use helm so this will need to be addressed elsewhere as well.  This means that we are unable to deploy an updated version of the helm chart without it being propagated to all environments.  This becomes a problem because while the helm chart might be backwards compatible, there is alway a possibility that it won't be.  Splitting this out into separate folders with a dedicated Chart.yaml and values.yaml will solve this.

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/traefik

---
## Tasks
- [ ] Create separate folders for each environment and move the values file as well as a copy of the Chart.yaml within them
- [ ] Modify argocd-apps main.jsonnet for each environment to point the traefik deployment at the new folder https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/argocd-apps
- [ ] Update the github actions in the traefik infra repo to reflect these changes https://github.com/department-of-veterans-affairs/vsp-infra-traefik

## Acceptance Criteria 
- [ ] Traefik can be deployed and updated per environment 
- [ ] Github actions reflect the changes that were made in the manifest repo when updating the image reference and chart version

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
This is now complete, traefik environments are properly separated so we can run different helm charts versions for each if needed.

The github actions have also been updated to reflect this.  I will likely take some time to document this setup in confluence and the traefik infra repo before closing this issue out completely
