### ISSUE TITLE
Update API key for forward proxies

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#38647]
## Issue Description
Forward proxies have been setup but an extra layer of security is being added to add back `api_key` to header for requests.

---
## Tasks
- [ ] Update AWS param store with api key
- [ ] Test endpoint with new header 

## Acceptance Criteria
- [ ] VBS endpoints are successfully including api key with requests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Liberty team has just deployed the API Key and therefore this is unblocked now.
