### ISSUE TITLE
Time to Complete Domo Card Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38651]
## Issue Description
Need to update Domo card with the revised time to complete metrics
---
## Tasks
- [ ] data QA from Brian analysis - @jonathan-epstein13 @chloedotbrown 
- [ ] Update the cards
- [ ] QA Domo card design
- [ ] QA Domo data
- [ ] Make sure new and old cards are included in Analytics on our Analytics [object ID list](https://docs.google.com/spreadsheets/d/19cS2nrii95YcMmGcsPQj0RSeSu3Xg6t2ri6KLfJkahw/edit#gid=712826366)

## Acceptance Criteria
- [ ] Time to complete metrics are back on the dashboards.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bsmartin-ep** [comment]
@chloedotbrown / @obrienjulie -

I will need to make the following changes to the `vw_forms_engagement(_last_week)` views for the new time-to-completion metric:

https://github.com/department-of-veterans-affairs/platform-analytics-and-insights/commit/0af5b9478cf1d2d09ffa93a1b08cd46f1c7b714e

We are already hit scoped (with session + hit_number), so I don't anticipate any changes.

Look OK?

**Comment by obrienjulie** [comment]
Changes look good to me.

**Comment by chloedotbrown** [comment]
@bsmartin-ep yep, this looks good to me too!

**Comment by chloedotbrown** [comment]
Thanks for carrying ☝️these over from the other ticket, @jonathan-epstein13 ! Only thing I'd add (and this may have been from a meeting) is that the "Average Minutes to Complete" and "Average Time on Step (Running Total)" cards on the [test dashboard](https://va-gov.domo.com/page/1751626899) need to match each other before being added to the Forms dashboard. 

<img width="1365" alt="TTC cards" src="https://user-images.githubusercontent.com/45518242/165593267-d8f769ed-acd8-4c76-85e9-9b69fa4f83af.png">

**Comment by jonathan-epstein13** [comment]
@chloedotbrown / @obrienjulie / @jonathan-epstein13  -

Primary Redshift ETL for time-to-complete and time-on-step is updated:
[[Redshift] Form Events and Calculated Metrics
](https://va-gov.domo.com/datacenter/dataflows/177/details#data-lineage)

### Output Datasets

[[OUTPUT] Forms Engagement - Time on Step ](https://va-gov.domo.com/datasources/9251be6b-fc95-417b-a971-24024a559033/details/overview)
[[OUTPUT] Forms Engagement - Time to Complete 
](https://va-gov.domo.com/datasources/d8ac9e92-5488-442a-84fc-bc84af3e5880/details/overview)

The only restrictions being applied:

- All hits must be within 30 days of the confirmation timestamp (set in both output ETLs):

```sql
AND ("closest_confirmation_timestamp" - "hit_timestamp") BETWEEN 0 AND 2592000
```

- Next step time is NOT calculated for the Confirmation step.  I think 1. we don't want to count that towards the SUM and 2. we were getting extra large values due to users restarting the same form in the same session.

```sql
    CASE
        WHEN "step_name" != 'Confirmation' THEN
        LEAD("visit_start_time" + ("hit_time" / 1000), 1) OVER (
            PARTITION BY "user",
            "visit_start_time",
            "form_name"
            ORDER BY
                "hit_number" ASC
        )
    END as next_step_timestamp,
```
### Mitigating outliers

We still have a lot of low time-to-completion values.  Especially for the 526EZ form, which I believe is due to a coding error that was fixed a few months ago.  Otherwise, some of these are a natural effect of splitting applications over several GA user IDs.

My suggestion would be to exclude any confirmation timestamps that are less than 3 steps or less than 2 (maybe 3?) minutes while calculating time-to-complete.

_via_ @bsmartin-ep
