### ISSUE TITLE
TUD - Remove Help Pages and Send Users to Platform Website

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38654]
## Issue Description
We do not want to confuse TUD users with two independent sets of help documentation. Let's eliminate the built-in help pages and send users to the Platform Website TUD Documentation instead.

---
## Tasks
- [x] Remove help pages from TUD
- [x] Route users who click on Help to the Platform Website TUD documentation
- [x] Insert any unique information from the TUD help pages into the Platform Website TUD Document

## Acceptance Criteria
- [x] Platform Website TUD documentation is the single source of truth for information about TUD
- [x] TUD's Help link directs the user to the Platform Website TUD [document](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html)

**Comment by holdenhinkle** [comment]
PR - https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/38654

**Comment by holdenhinkle** [comment]
I verified that all of the information in the TUD Help page we're removing is present in the[ Platform Doc page](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-the-Test-User-Dashboard.1910702416.html).

**Comment by holdenhinkle** [comment]
This was merged.

**Comment by pjhill** [comment]
Looks great -- thanks for knocking this out super quickly!
