### ISSUE TITLE
HLR: Prevent non-LOA3 Veteran from starting the form

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38668]
## Description

When a Veteran starts the Higher-Level Review form and isn't verified (LOA 3), the prefill and contestable issues do not properly load and won't be displayed. To prevent this problem, we're preventing all non-LOA 3 Veterans from starting the form.

## Tasks

- [ ] Add verify link to introduction page when not verified
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
