### ISSUE TITLE
[BE] Fix CHIP endpoint in vets-api development environment

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#38675]
## Description
Currently, vets-api uses the wrong path while sending requests to CHIP in the development stage.  Any request made in the vets-api development environment that initiates a call to CHIP fails.  

Modify devops repository with the right CHIP endpoint for the requests to succeed in the vets-api development environment.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria
- [ ] Calls made to CHIP from vets-api development environment should succeed

## Tasks
- [ ] Open a PR in DevOps repository
- [ ] Deploy and test on development.
