### ISSUE TITLE
[BE] Use a custom cookie instead of Session to store the low auth jwt token

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#38679]
## INFO
This ticket is necessary if full authorization is required.
This ticket is a nice-to-have if full authorization is NOT required.

## User Story
As a veteran, I want to be able to seamlessly perform check-in and/or pre check-in tasks even if I have an active fully authenticated session.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria
- [ ] jwt token is stored in a custom cookie instead of session cookie
- [ ] all check-in and pre check-in scenarios work without any issues

## Tasks
- [ ] update code/specs
- [ ] test locally and in review environments
- [ ] Deploy and test on staging.
- [ ] Need thorough testing
- [ ] Make sure the full authorization cookie is not overwritten or destroyed

**Comment by kanchanasuriya** [comment]
**List of Validation Test Scenarios in Staging:**
- Feature flag - Off state
    - Day-of Checkin
    - Precheckin
- Feature flag - On state
    - Day-of Checkin with full auth sign in/out after low auth 
    - Day-of Checkin with full auth sign in before low auth & sign out after low auth
    - Day-of Checkin with full auth session timeout
    - Precheckin with full auth sign in/out after low auth 
    - Precheckin with full auth sign in before low auth & sign out after low auth
    - Precheckin with full auth session timeout

**Comment by loripusey** [comment]
@kanchanasuriya to ask Stephen for a prod validation meeting
