### ISSUE TITLE
Document QA Standards for review

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#38681]
## Issue Description
Based on brainstorming and team discussions, document and formalize a plan for review from OCTO & Platform Leadership

---
## Tasks
- [x] Document recommended approach
- [x] Review with team to ensure details are defined

## Acceptance Criteria
- [x] Standards are documented and ready for review

**Comment by JoeTice** [comment]
Draft standards have been started on[ this page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2126544949/QA+Standards+Team+-+Draft+Development+Standards), need refinement from the team to finalize
