### ISSUE TITLE
Create mobile mockups of the Inherited Proofing page

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#38688]
## Issue Description
As requested by the Collab Cycle this work will create mobile mockups of the MHV Inherited Proofing process.

---
## Tasks
- [x] Convert all Desktop screens to Mobile screens (high-fidelity)
- [x] Ensure functionality remains the same

## Acceptance Criteria
- [x] Mobile mockups will be available to view in Figma by the Collab Cycle
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Separate the Figma MHV inherited proofing page's into separate Figma's.
