### ISSUE TITLE
[SW-Content] Update Translations for COVID-19 Vaccine page updates [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38695]
## Story
As a Veteran I need current and updated information for COVID-19 vaccines, so I can  find my best health care solution.

## Resources:

http://preview-prod.vfs.va.gov/preview?nodeId=11463
#38573

## Task(s)
- [x] Submit changes to Translation team
- [x] Update translations for COVID-19 Vaccine pages
- [x] Publish drupal pages

## Acceptance Criteria
* Pages are updated and published

**Comment by RLHecht** [comment]
Here are the translations back from the translators:

[15487_Vaccine-content-changes_Tagalog Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8288091/15487_Vaccine-content-changes_Tagalog.Final.docx)

[15486_Vaccine-content-changes_Spanish Final.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8288093/15486_Vaccine-content-changes_Spanish.Final.docx)

**Comment by RLHecht** [comment]
Pages have been updated, reviewed and published. Will send live links to the VHA translation team once the page is live.

**Comment by lunascoop** [comment]
@RLHecht I updated some of the content per the document. I didn't implement some of the changes such as italicizing the English words or duplicating some content (english and Tagalog).

Mga bakuna sa COVID-19 sa VA: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published this page.
