### ISSUE TITLE
Document the reverse proxy routing for various requests

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38696]
## Issue Description
In order to properly plan the partitioning and routing of the incoming requests to api.va.gov and the future vets-api specific API URL, we will need to know how the routes work currently.

This is documented in code in the templates for the revproxy, located here: https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/revproxy-vagov/templates which uses the configuration in the following files, per environment:
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-dev.yml
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-staging.yml
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-sandbox.yml
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-prod.yml

It is also possible to get the final templated configuration files from an instance of the revproxy, which might be an easier way to look at the data.

---
## Tasks
- [x] Look at the above configuration files and documentation
- [x] Output templates from jinja templates in the devops repo
- [x] Document how we got the config files from templates/variables into final config files in this ticket (and then move to Confluence)
- [x] Document routes in Confluence or in this ticket (and then move to Confluence)

## Acceptance Criteria
- [x] Documentation of routes for dev/staging/sandbox/prod revproxy is in this ticket (and ready to be moved to Confluence)
- [x] Documentation of the jinja2-init python process for outputting templates to config files is in this ticket (and ready to be moved to Confluence)
- [x] Documentation moved to Confluence

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
The configuration files for the Nginx revproxy currently live as Ansible Jinja2 templates in the [devops](https://github.com/department-of-veterans-affairs/devops) repo under `ansible/deployment/config/revproxy-vagov-{env}.yml`, whereby env is one of `dev`, `prod`, `sandbox`, or `staging`. 

To output the full templates with the environment-specific variables filled in, we can make use of a Python script in the [vsp-jinja2-init](https://github.com/department-of-veterans-affairs/vsp-jinja2-init.git) repo, The steps to produce the files for the `dev` environment are as follows:

```bash
cd /tmp
mkdir output
mkdir vars
git clone https://github.com/department-of-veterans-affairs/devops.git
git clone https://github.com/department-of-veterans-affairs/vsp-jinja2-init.git
pip3 install -r vsp-jinja2-init/requirements.txt
cp devops/ansible/deployment/config/revproxy-vagov-dev.yml vars
cp devops/ansible/deployment/config/revproxy-vagov/vars/* vars
rm vars/nginx_config_vagov-prod.yml
rm vars/nginx_config_vagov-staging.yml
rm vars/nginx_config_vagov-sandbox.yml
export JINJA_TEMPLATES_DIR=/tmp/devops/ansible/deployment/config/revproxy-vagov/templates
export JINJA_VARIABLES_DIR=/tmp/vars
export JINJA_DESTINATION_DIR=/tmp/output/
python3 vsp-jinja2-init/jinja2-init.py
```

This will output the following template files:
```bash
base-redirects.conf
base-shared.conf
enable-auth.conf
nginx.conf
nginx_api_server.conf
nginx_design_server.conf
nginx_developer_server.nginx_revproxy_redirects.nginx_status.conf
nginx_website_server.conf
review_instance_nginx_revproxy.conf
vetsgov-to-vagov-redirects.conf
```

**Comment by madebydna** [comment]
For the purposes of API routing, the relevant Nginx configuration file is `nginx_api_server.conf`. This file sets up the reverse proxy rules for API traffic. 

The configuration settings dictate that requests with the path `/services` and `/internal` will be routed to the Kong API gateway. Essentially all other traffic gets directed to an internal ELB. The ELB may or may not be in an EKS environment, which is checked by the presence of `$http_x_forward_eks_vets_api`, e.g.

```nginx
    location ~ ^/mobile/discovery {
      set $application api;
      set $component mobile_$1;
        
        // EKS proxy pass
        if ($http_x_forward_eks_vets_api) {
        proxy_pass http://internal-dsva-vagov-dev-tools-1729619844.us-gov-west-1.elb.amazonaws.com:80$request_uri;
        }
      
      // default proxy pass, non-EKS
      proxy_pass http://internal-dsva-vagov-dev-vets-api-elb-172229860.us-gov-west-1.elb.amazonaws.com:3004$request_uri;
    }
```

Some special rules exist whereby 
- requests with `^/services_user_content/vba_documents/(.*)` get served directly from an S3 bucket
- requests to `^/vanotify/(.*)` get routed to a notification url
- requests to `^/samlproxy` and `^/oauthproxy` get routed to the SAML/OAuth proxy servers, respectively
- components of the request path get extracted into a nginx variable named `$component`, for instance:
  -  for the pattern `^/(v0|v1)/(address|appeals|beta_registration|burial_claims|claim_attachments|claim_documents|disability_rating|education_benefits_claims|evss_claims|facilities|feedback|gi|health_care_applications|id_card|in_progress_forms|letters|maintenance_windows|messaging|notifications|pension_claims|post911_gi_bill_status|preneeds|prescriptions|profile|search|sessions|status|terms_and_conditions|user|veteran_readiness_employment_claims|vic)`
  - we extract the regex capture after the API version ... `set $component $2;`
