### ISSUE TITLE
Discuss separation with Lighthouse Team

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38697]
## Issue Description
Determine who the stakeholders for the process of isolation are, who the relevant team leads are, and meet to discuss the best way forward, and any technical issues.

Develop a cadence for regular meetings with these stakeholders and team leads, so that we may keep in sync with them over the course of the project.

Use this ticket to document the initial meeting and any questions that come out of that meeting

Questions to ask:
- Where does Kong configuration live?
- Is there documentation for the Kong configuration already?
  - Can we have access to the documentation if there is some?
- SAML Proxy / Oauth Proxy Documentation, any issues that relate to this?

---
## Tasks
- [X] Schedule initial meeting with Lighthouse team
- [x] Schedule followup meetings with a recurring meeting invite
- [ ] Create Confluence template for ongoing meetings to keep track of what is discussed in the future meetings

## Acceptance Criteria
- [x] Recurring meetings are created at a time agreed upon by Lighthouse team and our team
- [ ] Documentation for the initial meeting and follow up meetings is in this ticket or in Confluence

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
Confluence space set up: https://vfs.atlassian.net/wiki/spaces/PST4/pages/2153578668/Lighthouse+Team+Collaboration+Meetings+monthly
