### ISSUE TITLE
[UNPLANNED] Fix 'Print this page' button

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#38706]
## Background
The confirmation page includes a button to print the page. This button doesn't do anything currently.

## Tasks
- [x] Fix the code so that clicking the `Print this page` button brings up the browsers print dialogue

## Acceptance Criteria
- [x] Clicking `Print this page` button bring up browsers print dialogue
- [x] A PR has been requested for merging, if needed
