### ISSUE TITLE
[EKS] Update goldilocks and reorganize deployment

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#38718]
## Description
In the efforts of adding requests and limits to all of our deployments I wanted to upgrade goldilocks
https://www.fairwinds.com/blog/introducing-goldilocks-a-tool-for-recommending-resource-requests

It is currently deployed in our clusters but seems that they have since added support for stateful sets
https://github.com/FairwindsOps/goldilocks/issues/225

While I am in there I wanted to also reorganize the helm deployment for environment separation and in the process improve the github actions

---
## Tasks
- [x] Create separate folders for each environment and move the values file as well as a copy of the Chart.yaml within them https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/goldilocks
- [x] Modify argocd-apps main.jsonnet for each environment to point the goldilocks deployment at the new folder https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/argocd-apps
- [x] Update the github actions in the goldilocks infra repo to reflect these changes https://github.com/department-of-veterans-affairs/vsp-infra-goldilocks

## Acceptance Criteria 
- [x] Goldilocks can be deployed and updated per environment 
- [x] Github actions reflect the changes that were made in the manifest repo when updating the image reference and chart version

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Had to circle back and increase limits on the resources because they were hitting oom and being booted.  Limits cannot be left off currently because the parent chart has them hard coded into the values file.  Could create a PR to change this in the parent chart here https://github.com/FairwindsOps/charts/tree/master/stable/goldilocks

But with time being constrained with the re-compete being my focus, I have just put this in place for now which seems to have fixed the cycling of pods https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/e21dd3a1d156088971465cc7666c58a7ff827ec9

![image.png](https://images.zenhubusercontent.com/6005c75d4d345369546487dc/e7d8a10b-c721-437c-968a-24079053977d)

I think the scope of this ticket has been completed and can be closed.  With goldilocks updated it now picks up on the other pod types that it wasn't previously
