### ISSUE TITLE
Design intent Authenticated Profile - Bad Address Indicator

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38727]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [X] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/README.md)
 
 
 
- [X] Whiteboard sketch or other lo-fi prototypes or wireframes
   - [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/Pn1Woj/a/3OMD28m/r/l8Rw74)
   - [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WK0EMb0)
   - [VA Notify Email Draft](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/38140)
- [ ] User flow
- [ ] Research Plan
- [x] Any other artifacts you have so far
   - [Discovery Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1644526520883/08368c9a6d81a9b02b0caa3f736586539b3d1f20?sender=u28f508d646c449cc1afe4873) (very early in project)
   - [Design exploration Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1645053264056/07893207e0e0b79d3a6d55b0c02541319282f19d?sender=u28f508d646c449cc1afe4873)

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by seanasewell** [comment]
Review has been scheduled for 3/22 at 11:00am ET

**Comment by CherylEvans** [comment]
No Content FB at this stage.  Thank you!

**Comment by seanasewell** [comment]
Here is the recording of today's Design Intent meeting. [Zoom link
](https://us06web.zoom.us/rec/share/Rxv77T62fRK5ZqDKO0PUQfKoCjCArJCpwDz4b8bWG1nA6TeyOO_h33vQd2ZGxF0m.nIyHmznFlXxUiNc0)Passcode: 1#Ew9hSw

**Comment by MarciMcGuireGCIO** [comment]
Thank you @seanasewell !

**Comment by claytonzook** [comment]
No currently actionable feedback for Research. Let me know if you'd like to brainstorm any research ideas as you are drafting plans. I will also reiterate some comments from the meeting that may be useful when planning research:
- Consider including the email notification in the test plan
- If there is a place where you are deciding between two acceptable pattern uses, consider doing an A/B test (test both designs).
- Should test for mobile as well as desktop. This could mean splitting into two studies, one for mobile, one for desktop, to make it easier to manage.
- Consider including assistive tech users you can test with in pre-coding environment (e.g. screen zoom)
- Should plan to include, even oversample, under represented groups

**Comment by SKasimow** [comment]
@cgednalske - checking to see if we can close this? It looks completed to me and think just need Platform to close #38922.

**Comment by SKasimow** [comment]
@cgednalske can we close this one?

**Comment by cgednalske** [comment]
@SKasimow yes I believe we can! Don't see any reason why we'd still need it open.

**Comment by SKasimow** [comment]
@cgednalske -thanks....closing!
