### ISSUE TITLE
[EKS] Enable and integrate vets-api APM through datadog agent

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#38723]
## Description
To connect APM with the datadog agents themselves is going to be using a unix socket which will take some more configuration 

We are currently collecting vets-api statsd via this method using socat-proxy. 

https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=host#socat-proxy

This allows for a volume mount that is shared directly between the agent and vets-api, which will allow vets-api to just send to localhost on the appropriate port for the APM metrics to get captured and sent to datadog

For the helm chart we will want to make sure we enable the appropriate values https://github.com/DataDog/helm-charts/blob/9867710765119c7db862a00598e4673d953e699d/charts/datadog/values.yaml#L271-L298

Will also need to investigate how to open multiple sockets/ports on the same socat-proxy container or create a new container for this socket specifically?  Not sure on the actual solution here but just from initial thoughts

Example for statsd socat proxy container
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/9cf08c8fd46fbd1e7b272ba4a752304c84e9362e/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L183-L192

---
## Tasks
- [ ] Enable APM values in the datadog helm chart so it is using a unix socket through `/var/run/datadog/apm.socket`
- [ ] Modify the args to open up the appropriate port and forward to the new socket

## Acceptance Criteria 
- [ ] APM metrics are being sent to datadog from eks

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Instead of using socat proxy to send apm, we can directly mount the host path to vets-api itself as stated in the datadog docs

https://docs.datadoghq.com/agent/kubernetes/apm/?tab=uds
