### ISSUE TITLE
Change Demographic confirmation duration to 7 days

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#38721]
## Issue Description
We have been asked to change the demographics confirmation duration from 3 days to 7 days.

---
## Tasks
- [ ] Change the demographics confirmation duration to 7 days, it is currently 3 days.

## Acceptance Criteria
- [ ] Demographics confirmation status changed from 3 days to 7 days. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
