### ISSUE TITLE
[UNPLANNED] Gold Sticky for Download Link

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38728]
## Background
We aren't going to be able to complete the download portion of the letters section in COE so lets remove/reference that link within the prototype.

## Considerations
This will be passed on to the future migration team.

## Tasks
- [x] Put a gold sticky note in to the prototype after usability sessions are complete
- [ ] TBD, if needed

## Acceptance Criteria
- [x] There is a note in the prototype that articulates the download link being implemented later.

**Comment by sporeboy** [comment]
Sticky notes were added to the UXPin prototype starting here: [(UXPin link)](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140680778)

**Comment by sporeboy** [comment]
The text of the note is: "Due to time restrictions, the download links are not in the staging or production versions of the 'Your COE' tool. This feature didn't make the MVP, but it's important that these links be added in any  fast-follow iterations."
