### ISSUE TITLE
Implement Salesforce Email Connector

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#38749]
## Issue Description
_As a DOMO support dashboard administrator, I want to to automate data updates, so that I can save time updating data for dashboard users_

---
## Tasks
- [x] _Implement Salesforce email connector in DOMO_
- [x] _Test relevant data updates on the DOMO support dashboard_

## Acceptance Criteria
- [x] _The Salesforce Support Issue Dashboard is successfully and correctly updated via the email connector_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Documentation on how to update the [email dataset](https://vfs.atlassian.net/wiki/spaces/~403774134/pages/2134179987/VA+411+DOMO+Email+Connector).

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 feel free to close this ticket if you see fit.
