### ISSUE TITLE
Update accordion implementation on Vet Center and VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38741]
## Issue Description
A recent accordion component update had to be rolled back due to unexpected behavior on Vet Center and VAMC pages. It was determined that this occurred because of the way the accordions had been implemented on Vet Center and VAMC pages. We need to adjust this implementation so the change to the component can be released. 

Impact observed on [Houston health care health services page](https://www.va.gov/houston-health-care/health-services/), [Michael E Debakey Department of Veterans Affairs Medical Center](https://www.va.gov/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center/) and [Cape Cod Vet Center](https://www.va.gov/cape-cod-vet-center).

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/159034470-55891381-daa0-44bc-b3e6-d3f120befedf.png)
![image](https://user-images.githubusercontent.com/55411834/159034489-f77412a0-868c-4412-a411-c4c354380b9d.png)
![image](https://user-images.githubusercontent.com/55411834/159034532-8db26071-b9d3-4e83-b705-48834b8cd53a.png)
</details>

[Reference this Slack thread for details](https://dsva.slack.com/archives/C02730UEZPS/p1647469887046229).  

## Current experience
The pages have a set of accordion wrappers, each with one item inside.

## Expected experience
Accordion items should be inside one accordion wrapper 

## Dev notes

Templates: 
```
<!--
  layout: health_care_local_facility.drupal.liquid
  path: houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center
  entityId: 1598
-->
```
```
<!--
  layout: health_services_listing.drupal.liquid
  path: houston-health-care/health-services
  entityId: 7712
-->
```
```
<!--
  layout: vet_center.drupal.liquid
  path: cape-cod-vet-center
  entityId: 3632
-->

```

Template structured correctly: 
https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c4804bb887ac150a19f1ffbbb98b48/src/site/layouts/health_care_local_facility.drupal.liquid#L140-L156
```
 <va-accordion section-heading="Prepare for your visit" bordered>
                {% for accordionItem in fieldLocationServices %}
                  {% assign item = accordionItem.entity %}
                  {% comment %}
                    See Google Analytics datalayer handling in src/applications/static-pages/subscribeAccordionEvents.js
                  {% endcomment %}
                  <va-accordion-item
                    header="{{ item.fieldTitle }}"
                    level="3"
                    data-label="{{ item.fieldTitle }}"
                  >
                    <div id="{{ item.entityBundle }}-{{ item.entityId }}">
                      {% include "src/site/paragraphs/wysiwyg.drupal.liquid" entity = item %}
                    </div>
                  </va-accordion-item>
                {% endfor %}
              </va-accordion>
```
An example that would produce the unexpected behavior that we're seeing - the <va-accordion> is being created inside of the loop:
https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c4804bb887ac150a19f1ffbbb98b48/src/site/layouts/vet_center.drupal.liquid#L124-L133
```
 {% for entity in fieldPrepareForVisit %}
                <va-accordion bordered
                              id="prepare-for-your-visit-accordion-{{ entity.entity.fieldHeader }}">
                  <va-accordion-item
                      id="prepare-for-your-visit-accordion-item-{{ entity.entity.fieldHeader }}"
                      header="{{ entity.entity.fieldHeader }}" level="3">
                    {{ entity.entity.fieldRichWysiwyg.processed | drupalToVaPath | phoneLinks }}
                  </va-accordion-item>
                </va-accordion>
              {% endfor %}
```
The issue pertains more towards the code further down on the page: [https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c48[…]98b48/src/site/layouts/health_care_local_facility.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c4804bb887ac150a19f1ffbbb98b48/src/site/layouts/health_care_local_facility.drupal.liquid#L177-L190)
Which then calls on: [https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c48[…]98b48/src/site/facilities/facility_health_service.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/eaf3635b70c4804bb887ac150a19f1ffbbb98b48/src/site/facilities/facility_health_service.drupal.liquid)
So that for loop is generating many accordions which is what we see when we scroll down about half way down the page: https://www.va.gov/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center/

---
## Tasks
- [ ] Update accordion implementation to place accordion items inside accordion wrappers
- [ ] Test change on several examples of health care system health services pages, health care facility pages and Vet Center pages, such as
      - [Houston health care health services page](https://www.va.gov/houston-health-care/health-services/)
      - [ ]  [Michael E Debakey Department of Veterans Affairs Medical Center](https://www.va.gov/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center/) 
      - [ ] [Cape Cod Vet Center](https://www.va.gov/cape-cod-vet-center).
- [ ] Request review from Kay Bowman

## Acceptance Criteria
- [ ] Accordion items are inside accordion wrapper 
- [ ] Veterans viewing accordions in Prepare for your visit sections on VAMC facility or Vet Center pages are able to open accordions to view content 
- [ ] Veterans viewing service accordions on VAMC health care system health service pages, VAMC facility pages or Vet Center pages are able to open accordions to view content. 
- [ ] Front end experience is maintained from Veteran perspective. 
- [ ] Sign off by Katy Bowman
