### ISSUE TITLE
[ArgoCD] Remove workflow deployment from the utility cluster (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#38745]
## Description
Argo workflows are not in use at this time. This was initially deployed to look into how it may function, but is no longer needed and can be removed. 

## Background/context 
Issue where this was initially deployed - [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30085)

---
## Tasks
- [x] Remove the manifests pertaining to this deployment 
- [x] Remove from the "app-of-apps" that defines the app deployments 

## Acceptance Criteria 
- [x] Argo workflows is no longer deployed
- [x] Relevant code has been removed

**Comment by oseasmoran73** [comment]
Closing ticket as PR has removed `argo-workflow` and all relevant code
