### ISSUE TITLE
[VA Debt Portal - VBA Debts] Update the 'Current debts' 404 once letters after 12/9/2021 are available for download

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38755]
## Issue Description
Since letters sent after December 9th are unavailable for download, we removed the CTA to download letters in the debt portal current debt overview's 404. This ticket captures that the sentence should be added back once the issue is resolved and Veterans are able to download all their letters. 

[Refer to this UXPin prototype for the current 404 alert](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/148632100/simulate/no-panels?mode=i)

---
## Tasks
- [ ] The 404 alert's been updated with the appropriate content notifying Veterans that they may still be able to download letters related to their debt

## Acceptance Criteria
- [ ] The alert has been updated and the UXPin has been linked in this ticket
- [ ] A frontend ticket has been created and linked in this ticket

**Comment by denisecoveyduc** [comment]
Closing #40101 as it reflects the same task.

**Comment by denisecoveyduc** [comment]
10/17/22- I spoke with Jill who is checking to see if all letters from VBMS are now available for download or if a subset are still unavailable.

**Comment by HeatherRienks** [comment]
@denisecoveyduc  and @mgleo to follow up on this.

**Comment by denisecoveyduc** [comment]
1/27/23-This is no longer an issue given that VBMS Letters are no longer available for download on the portal.
