### ISSUE TITLE
DOMO Dashboard - VA Virtual Agent Custom Survey

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#38756]
## Issue Description
_As a product manager with a custom Medallia survey for my product, I want a dashboard to view the survey response data in DOMO_

---
## Tasks
- [x] _Create New Medallia survey dashboard in DOMO_
- [x] _Title `VA Virtual Agent Survey Report`_
- [x] _Add cards for each of the 5 questions on the custom VA Virtual Agent survey shown [here](https://www.va.gov/contact-us/virtual-agent/)_
- [x] _Add sample data from survey responses since launch_
- [x] _Validate dashboard displays data correctly_

## Acceptance Criteria
- [x] _New DOMO dashboard displays survey responses in respective cards/charts for the VA Virtual Agent Medallia survey_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
[VA Virtual Agent Survey Report](https://va-gov.domo.com/page/443898686)
