### ISSUE TITLE
[Research] Assets Needed for Research Trip and Small Update to Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#38764]
# Description 
We need a way to easily take notes while at St. Louis. Therefore, we are planning to create a structure print out that can be filled out on-site. 

We also realized that there are a few scenarios that should be added to the Veteran conversation guide.
- If a Veteran already checked in before we could intercept them, what questions can we still ask that Veteran?
- Should we reword our screening questions to more explicitly offer the in-person check-in method?
  - If a Veteran doesn't want to complete check-in on their phone, do we have any follow-up questions about why for them?

# Tasks
- [x] Create print out.
- [x] Update the [Veteran conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback/conversation-guide.md)

# Acceptance Criteria
- [x] Send out the updated GitHub conversation guide via Slack for review by check-in ux, product, and Stephen
- [x] Send out the print out for review by the other team members going on the research trip
- [x] Add a copy of the print out to GitHub within this [folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback).

**Comment by benbrasso-agile6** [comment]
Sent to Zach and Ya-ching for review. Will likely do something similar for the staff conversation guide.

**Comment by benbrasso-agile6** [comment]
Got feedback from Zach and Ya-ching. Will make edits and then need to finish the Staff print out.

**Comment by benbrasso-agile6** [comment]
Word and PDF for staff is located here - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/st-louis/pilot-feedback

Word and PDF for vets is located here - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/StLouis-pilot-feedback

**Comment by benbrasso-agile6** [comment]
@loripusey we'll likely need a new ticket for one of the UXers to print some of these, so we have them onsite to fill in during interviews.
