### ISSUE TITLE
DOMO Email Connector - Medallia VA Virtual Agent Survey

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#38779]
## Issue Description
_As a DOMO dashboard administrator, I want data updates automated so that data can be updated more regularly with less effort_

---
## Tasks
- [x] _Develop email connector for VA Virtual Agent Medallia survey_
- [x] _Implement (above) email connector_
- [x] _Test (above) email connector_

## Acceptance Criteria
- [x] _VA Virtual Agent survey dashboard in DOMO updates successfully and correctly with the (above) email connector_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Medallia ChatBot DataSet](https://va-gov.domo.com/datasources/cbd00b11-1bc1-4f3a-b51d-5469146f14c8/details/overview)
Email address: 3c8ffd501b154b8f952d30803ef0bc98@va-gov.mail.domo.com

**Comment by ianMcCullough-ob** [comment]
[ChatBot Email Connector](https://va-gov.domo.com/datasources/cbd00b11-1bc1-4f3a-b51d-5469146f14c8/details/overview)

**Comment by ianMcCullough-ob** [comment]
This email connector has been tested and working. It feeds into an ETL that removes duplicates and the ETL output is connected to the chatbot dash.

**Comment by jwoodman5** [comment]
I also successfully updated per the provided instructions. Closing.
