### ISSUE TITLE
Track VBMS Endpoint Fix: Debt Letters 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#38770]
## Issue Description
**_There is no development work for Debt Resolution team._** This issue is to track the VBMS fix and any updates we hear along the way.
 VBMS stopped sending letters on December 9, 2021 and therefore they are not available for Veteran's to download through the portal. We have added a pop up alert to notify users and removed the CTA.  

---
## Tasks
- [ ] Monitor status of VBMS fix and capture any updates below for awareness. 
- [ ] Add PDF download functionality back into UI once endpoint fix has been established. #38755

## Acceptance Criteria
- [ ] Debt Letters are being sent from VBMS and are now available in the debt portal for Veterans to download.

---
## ℹ️ Information Log ℹ️
- Archives: VBMS Endpoint first established #9215
- 3/18: Jill Anderson mentioned VBMS timeline is May
- 4/18: Told that the VBMS Endpoint fix is being done by the Liberty team. Denise has reached out to Logan and Mike to get a better understanding on the timing of the fix. 
- 4/19 "VBMS has begun running DMC’s letters again.  They haven’t started 101 and 100B.  They will be sending us a timeline for getting the backlog added (everything from December to today). We can not remove pop up until all letters have been added."
