### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Update Gender Identity

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38788]
## Background

Add a new endpoint to vets-api that allows the user to update their gender identity.  The vets-api will call the VA profile demographic API to handle this.

## Tasks
- [x] Update supporting models
- [x] Add service object methods to call VA Profile API
- [x] Add controller method to update user's gender identity
- [x] Write Service Object Specs
- [x] Write Controller Specs
- [ ]  Submit related PRs by dependency

## Acceptance Criteria
- [x] Calling new controller method (endpoint) updates a user’s gender identity.
- [x] All Service Object Specs pass
- [x] All Controller Specs pass
