### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Return Preferred Name

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38783]
## Background

When the /personal_information endpoint is called, the demographic data returned will contain the user's preferred name.

## Tasks
- [ ] Create supporting models
- [ ] Add service object logic
- [ ] Update PersonalInformation controller to include demographic data with response
- [ ] Write Service Object Specs
- [ ] Write Controller Specs

## Acceptance Criteria
- [ ] Call to /personal_information endpoint includes demographic data with with user's preferred name.
- [ ] All Service Object Specs pass
- [ ] All Controller Specs pass
