### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Return Gender Identity

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38784]
## Background

When the /personal_information endpoint is called, the demographic data returned will contain the user's gender identity.

## Tasks
- [x] Create supporting models
- [x] Add service object logic
- [x] Update PersonalInformation controller to include gender identity with response
- [x] Write Service Object Specs
- [x] Write Controller Specs

## Acceptance Criteria
- [x] Call to /personal_information endpoint includes demographic data with with user's gender identity.
- [x] All Service Object Specs pass
- [x] All Controller Specs pass
