### ISSUE TITLE
Research & document API flows

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#38782]
## Issue Description
Research details and find examples for possible API flows according to the five possibilities listed in the [Explainer doc](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap#Request-Flows).

1. Lighthouse API endpoints that are completely independent of vets-api. Example: [Lighthouse Health API](https://developer.va.gov/explore/health)
2. Lighthouse API endpoints that are implemented in vets-api but don’t have to be since there is no overlap with va.gov implementation (e.g. [Lighthouse Benefits Intake API ](https://developer.va.gov/explore/benefits/docs/benefits?version=current) under `/services/vba_documents/v1/`)
3. Lighthouse API endpoints that share significant backend code with vets-api endpoints. These might have separate endpoints but share a lot of logic, which appears to have been an intentional decision to promote code sharing (e.g. [Lighthouse Claims API](https://developer.va.gov/explore/benefits/docs/claims?version=current) under `/services/claims/v1/claims`)
4. Lighthouse API endpoints that are an upstream dependency to vets-api. These requests loop back from vets-api to the Kong API gateway, unless the Lighthouse API endpoint is one that is implemented in vets-api anyway (case 2) (e.g. [Lighthouse Facilities API](https://developer.va.gov/explore/facilities/docs/facilities?version=current) under `/services/va_facilities/v0/facilities/`). We could put the Lighthouse API behind the forward proxy and use it in the same manner we use other APIs and data sources.
5. API endpoints that are specific to vets-api only (e.g. feature toggles API under `/v0/feature_toggles`)

---
## Tasks
- [x] Document Lighthouse API requests that are routed to vets-api (case 2 and 3)
- [x] Document vets-api endpoints that use Lighthouse as an upstream dependency (case 4)
- [x] Outline options for Lighthouse -> vets-api requests under new architecture (with special consideration of API gateway use case)
- [x] Outline options for vets-api -> Lighthouse under new architecture (with special consideration of API gateway use case)

## Acceptance Criteria
- [x] Documentation and outlines for interdependent requests exists in this ticket and/or Confluence

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
The five identified API flows will be handled in the new architecture as follows:

1. Lighthouse API endpoints that are completely independent of vets-api.
    - These routes will only be accessible via `api.va.gov` and routed to the new API gateway Apigee
    - Examples: LH Health API, LH Address validation API
    - Full list: https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov#3.-Routes-that-will-no-longer-be-served-from-platform-api.va.gov
2. Lighthouse API endpoints that are implemented in vets-api but don't otherwise share backend code.
    - These routes will be accessible with both the existing domain `api.va.gov` (routed via Apigee back to vets-api) as well as the new domain `platform-api.va.gov`
    - These routes might become first candidates for extracting as separate implementations under the purview of Lighthouse
3. Lighthouse API endpoints that share significant backend code with vets-api endpoints.
    - These routes will be accessible with both the existing domain `api.va.gov` (routed via Apigee back to vets-api) as well as the new domain `platform-api.va.gov`
    - Even though these routes will require some hops from GCP/Apigee to DVP and from there back to the `dsvagovcloud` and `vets-api`, the code reuse aspect in might warrant the longer networking path
4. Lighthouse API endpoints that are an upstream dependency to vets-api.
    - Currently these requests rely on the Kong API gateway to be routed to Lighthouse via the forward proxy
    - `vets-api` will need to set up a direct connection to LH via the forward proxy
    - Examples: LH Facilities API, (what are other examples?)
5. `vets-api` only API endpoints
   - These will be solely accessible via the new domain `platform-api.va.gov`
