### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Update Preferred Name

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38787]
## Background

Add a new endpoint to vets-api that allows the user to update their preferred name.  The vets-api will call the VA profile demographic API to handle this.

## Tasks
- [ ] Update supporting models
- [ ] Add service object methods to call VA Profile API
- [ ] Add controller method to update users’ preferred name
- [ ] Write Service Object Specs
- [ ] Write Controller Specs

## Acceptance Criteria
- [ ] Calling new controller method (endpoint) updates a user’s preferred name.
- [ ] All Service Object Specs pass
- [ ] All Controller Specs pass
