### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Return Sexual Orientation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38786]
## Background

When the /personal_information endpoint is called, the demographic data returned will contain the user's sexual orientation.

## Tasks
- [ ] Create supporting models
- [ ] Add service object logic
- [ ] Update PersonalInformation controller to include user's sexual orientation with response
- [ ] Write Service Object Specs
- [ ] Write Controller Specs

## Acceptance Criteria
- [ ] Call to /personal_information endpoint includes demographic data with with user's sexual orientation
- [ ] All Service Object Specs pass
- [ ] All Controller Specs pass
