### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Integration Testing for Gender Identity

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38792]
## Background

Verify that a user can view and update their gender identity from the va.gov profile page in staging.

## Tasks
FE and BE engineer ensure together to:
- [ ] Identify staging users for testing
- [ ] Verify that a user’s gender identity is returned by the API and displayed
- [ ] Verify that a user’s gender identity can be updated

## Acceptance Criteria
In the staging environment, ensure that the following actions can be performed for a staging user:
- [ ] Verify that a user’s gender identity is returned by the API and displayed.
- [ ] Verify that a user’s gender identity can be updated.

**Comment by tpharrison** [comment]
@Samara-Strauss closing this ticket since its already covered by other tickets.  I zeroed out the estimate.
