### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Service Object to return demographics info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38796]
## Background

Build Demographics service object to return data from VA Profile demographics API.  A user's preferred name and gender-identity will be returned.

VA Profile swagger docs for demographics API are located here:
https://qa.vaprofile.va.gov:7005/demographics/swagger-ui/index.html?configUrl=/demographics/v3/api-docs/swagger-config

## Tasks
- [x] Create Demographics Service Class
- [x] Create Config class & Faraday connection
- [x] Create Demographics Response class
- [x] Update settings.yml

## Acceptance Criteria
- [x] Passing service specs for returning demographics data (preferred name and gender-identity)
