### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Update Sexual Orientation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38790]
## Background

Add a new endpoint to vets-api that allows the user to update their sexual orientation.  The vets-api will call the VA profile demographic API to handle this.

## Tasks
- [ ] Update supporting models
- [ ] Add service object methods to call VA Profile API
- [ ] Add controller method to update user’s sexual orientation
- [ ] Write Service Object Specs
- [ ] Write Controller Specs

## Acceptance Criteria
- [ ] Calling new controller method (endpoint) updates a user’s sexual orientation
- [ ] All Service Object Specs pass
- [ ] All Controller Specs pass
