### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Integration Testing for Preferred Name

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38791]
## Background

Verify that a user can view and update their preferred name from the va.gov profile page in staging.

## Tasks
FE and BE engineer ensure together to:
- [ ] Identify staging users for testing
- [ ] Verify that a user’s preferred name is returned by the API and displayed
- [ ] Verify that a user’s preferred name can be updated

## Acceptance Criteria
In the staging environment, ensure that the following actions can be performed for a staging user:
- [ ] Verify that a user’s preferred name is returned by the API and displayed.
- [ ] Verify that a user’s preferred name can be updated.

**Comment by tpharrison** [comment]
@Samara-Strauss closing this ticket since its already covered by other tickets.  I zeroed out the estimate.
