### ISSUE TITLE
BE - Auth Profile - Personal Info Revision - Integration Testing for Sexual Orientation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38794]
## Background

Verify that a user can view and update their sexual orientation from the va.gov profile page in staging.

## Tasks
FE and BE engineer ensure together to:
- [ ] Identify staging users for testing
- [ ] Verify that a user’s sexual orientation is returned by the API and displayed
- [ ] Verify that a user’s sexual orientation can be updated

## Acceptance Criteria
In the staging environment, ensure that the following actions can be performed for a staging user:
- [ ] Verify that a user’s sexual orientation is returned by the API and displayed.
- [ ] Verify that a user’s sexual orientation can be updated.

**Comment by tpharrison** [comment]
Covered by other tickets.  Zero out estimate and closing...
