### ISSUE TITLE
[SW-Content]  Review and publish COVID-19 FAQ and Chatbot updates [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38816]
## Story
As a Veteran I need the latest COVID-19 Vaccine information, so I can assure that I am fully informed about my vaccination options.

## Task(s)
- [x] Review and publish changes to COVID-19 Vaccine page
- [x] Review and update Chatbot on COVID-19 page.
- [x] Send changes to Translators for review and update

## Acceptance Criteria
* Updates are published to Drupal page

**Comment by RLHecht** [comment]
These updates were published, chatbot has been worked on and the translations were sent out. Moving to validate.
