### ISSUE TITLE
[SW-Content]  Send COVID-19 FAQ updates for translations and update translations [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38819]
## Story
As a Veteran I need the latest COVID-19 Vaccine information, so I can assure that I am fully informed about my vaccination options.

## Resources
#38816

## Tasks
- [x] Update COVID-19 vaccine pages with Translated received from Translators
- [x] Publish updated translations
- [x] Have translations double checked for accuracy and content.

## Acceptance Criteria
* Translations are updated and confirmed to match content/page intent

**Comment by RLHecht** [comment]
@lunascoop Here are the translations back from the stakeholders. The last part of each document is for a screening questionnaire for Danielle. I'll put that in a separate document for her. Thanks!

[https://app.zenhub.com/files/133843125/5a16166d-1d11-4e45-a9c4-08964bbaae40/download](https://app.zenhub.com/files/133843125/5a16166d-1d11-4e45-a9c4-08964bbaae40/download)

[https://app.zenhub.com/files/133843125/6ada232c-2edd-4bed-a09a-7d57644c3258/download](https://app.zenhub.com/files/133843125/6ada232c-2edd-4bed-a09a-7d57644c3258/download)

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

Mga karaniwang katanungan tungkol sa Coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=16475
Preguntas frecuentes sobre el coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Comment by RLHecht** [comment]
Thanks @lunascoop I reviewed and published these. Will send to volunteer translators once the pages are live.

**Comment by RLHecht** [comment]
@lunascoop We just got back revisions from Mateo's team:

For the first accordion:   What’s VA’s current policy on masks?(English)

Sumusunod kami sa CDC at sa mga lokal na alituntunin patungkol sa panakip sa ilong at bibig. Ang kaligtasan ninyo ang aming pangunahing prayoridad. 

Narito ang aming pinakabagong patakaran para sa iba’t-ibang lokasyon ng VA:

- Sa mga pangangalagang kalusugan na pasilidad ng VA: Ang sinumang pumapasok sa aming mga ospital, klinika at Sentro ng Vet ay kailangang magsuot ng panakip sa ilong at bibig. Kung kayo ay ganap nang nabakunahan, sasabihin ng aming tauhan sa inyo kung ligtas nang alisin ang inyong panakip habang kayo ay nasa pasilidad.

- Kung nasa loob at sa ibang lokasyon ng VA: **Laayon ng bawat lokasyon ang mga patakaran patungkol sa pagsusuot ng panakip kung kailangan.** Halimbawa, kung ang iyong kondado ay may mataas na antas ng hawaan ng coronavirus, ang lahat ay kailangang magsuot ng panakip.

Please change the statement in bold to:  “Ang bawat lokasyon ay mag-aadjust ng patakaran patungkol sa pagsusuot ng panakip kung kinakailangan.”

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.

Mga karaniwang katanungan tungkol sa Coronavirus: http://preview-prod.vfs.va.gov/preview?nodeId=16475
