### ISSUE TITLE
CST: Remove old feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38829]
## Description

The Claim Status Tool still has a few feature flags in the code that have been at 100%, or already remove, and need to be cleaned up

- `request_locked_pdf_password`
- `evss_upload_limit_150mb`

## Tasks

- [ ] Remove feature flag code in CST
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
