### ISSUE TITLE
Phone display for Register for care pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38826]
## Issue description
This issue breaks the phone number display portion out of #37630, which has additional information if needed.

It is part of Implement front end for newly hardened Register for care pages #37367. 

## Template
Newly hardened pages use this template **which has not been rolled to Production yet and needs to be viewed in CMS.** 
```
 <!--
  layout: vamc_system_register_for_care.drupal.liquid
  path: preview
  entityId: N/A
-->
```
note, this is different than the template currently on Prod 

```
<!--
  layout: health_care_region_detail_page.drupal.liquid
  path: western-colorado-health-care/register-for-care
  entityId: 6245
-->
```

The following systems have data in this new hardened template and can be used for validation: 

- VA Western Colorado health care  (i.e. http://prod.cms.va.gov/western-colorado-health-care/register-for-care-0)
- VA Cheyenne health care 
- VA Eastern Oklahoma health care  
- VA Sheridan health care

## Tasks
Implement [UXPin design](https://preview.uxpin.com/640e3b5894ed7cdf5c5d3342b119badd012ec5a5#/pages/147812897/documentation/no-panels?mode=i) for Register for care pages, including the following
- [ ] Phone labels and numbers follow an update design pattern.
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Campus map and directions link will not be needed, per Dave C. 
- [ ] Validate this work using VAMC systems listed above (Because these newly hardened pages have not been rolled out to all VAMC systems, we need to validate using the systems which have piloted the templates and have data in them) 
- [ ] Work with Steve Wirt and CMS team for deployment of these changes to production
- [ ] Work with Nick O to validate these changes

## Acceptance Criteria
Register for care page is designed consistent with UX Pin spec, including
- [ ] Phone labels are consistent with CMS data and appear above the phone number
- [ ] General margin and padding styling should follow current design system standards (included in UX pin if needed)
- [ ] Deployment is coordinated with CMS team
- [ ] Steps taken to test these changes and their results are documented in this issue
- [ ] Nick has signed off on these changes with a comment in this issue

**Comment by mmiddaugh** [comment]
phone display looks good in tugboat
