### ISSUE TITLE
[Design] Updated Address Editing Patterns Based on Profile Team's Findings - PART 2

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38836]
This is a placeholder story for part 2 of the work from this design ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34454

## Description
We made the decision to utilize the same pattern that profile is currently using for "your mailing address and home address are the same.". The profile team is running a user research study during the first week in January 2022 to test an improved design on how to denote that a Veteran's home and mailing address are the same. Depending upon the outcome of the study, we should adjust our editing pattern for addresses (and also denoting that emergency contact and next of kin are the same).

We have identified some areas that needed additional clarification. This could potentially result in redoing the UX work that could impact FE also. That being said, I would like to recommend that further UX exploration/investigation is performed. @kristenmcconnell @loripusey
Areas of clarification:

The design intent and user insights for setting the 'My home address is the same as my mailing address'.
The reminder modal has a secondary option that leads to a follow-up modal that needs to be clarified
Possibility of adding the 'My mailing address is the same as my home address.' checkbox in the mailing address edit page.

## Tasks
- [x] Collaborate with VA Profile team
- [x] Update wireframes, if necessary
- [ ] Review with team

## Outcome
Met with VA Profile UX to identify the gap and added/updated the following wireframes.

- [x] [Revised wireframe] [Use my mailing address for my home address](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/A8E445BD-7A7D-41DE-A8E6-3E36FCC74DD9)

- [x] [New wireframe] [Error state modal](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/DDACF8AF-1F8A-45F5-BDCE-2D8B8609EF8F)

- [x] [Reference] [Address Update User Flow from VA Profile](https://app.mural.co/t/vsa8243/m/vsa8243/1648492872357/ccc5ced279f2062e7336460965ddc8681e6e9722?sender=u28f508d646c449cc1afe4873)

**Comment by loripusey** [comment]
@loripusey Look for FE ticket to go with this or create one

**Comment by zach-park** [comment]
@loripusey @kristenmcconnell @niradatta1 @ytsaoca @benbrasso-agile6 
Met with VA Profile UX to identify the gap and added and updated the following wireframes. 

[Revised] Use my mailing address for my home address:
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/A8E445BD-7A7D-41DE-A8E6-3E36FCC74DD9

[New wireframe] Error state modal:
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/DDACF8AF-1F8A-45F5-BDCE-2D8B8609EF8F

[Reference: VA Profile User Flow] Address Update UI:
https://app.mural.co/t/vsa8243/m/vsa8243/1648492872357/ccc5ced279f2062e7336460965ddc8681e6e9722?sender=u28f508d646c449cc1afe4873

**Comment by loripusey** [comment]
I've got some questions. After I go to the edit screen for Mailing Address, check the "use my mailing address for my home address" checkbox and then I click Update, you show me this screen which shows me my new home address (which is now the same as the mailing address) and asks me if I want to use it for my Mailing Address. That seems like circular logic and doesn't make sense. I was just editing my Mailing Address and basically copied it over to my Home Address and now you are asking me if I want to copy my Home Address over to my Mailing Address?  I need some clarification of the workflow.

![image](https://user-images.githubusercontent.com/86678742/160689785-8af3faa1-0d9d-466a-a904-1318c495a014.png)

**Comment by kristenmcconnell** [comment]
Question to follow-up on Lori's question:
- Does the below screen only appear if the "Use my mailing address for my home address" isn't checked and there is a mismatch detected after clicking "Update?"
<img width="121" alt="Screen Shot 2022-03-29 at 3 27 17 PM" src="https://user-images.githubusercontent.com/66287082/160691916-9de05313-e471-4c76-9950-d5402d70426f.png">

Is this workflow a double check in case someone doesn't utilize the "Use my mailing address for my home address" feature?

**Comment by kristenmcconnell** [comment]
> As an example, it only appears if a user edits and updates the home address manually when the checkmark is already pre-selected.

Just saw your comment Zach.

**Comment by loripusey** [comment]
@zach-park thanks for the clarification, I understand now.
