### ISSUE TITLE
[RFC] Public URL for platform tools 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#38837]
## Description
There are open questions regarding the **need for a public URL that allows access to platform tools**. Setting up new URLs involves communicating with the VA and updating the platform's ATO. It can be difficult to get the URL provisioned. 

Note: Decisions made as a result of the RFC are beyond the scope of this issue. **This issue is just to track the creation of the RFC**. Add'l issues may be created to track further action. 

## Background/context 

- Recent [thread in DSVA Slack](https://dsva.slack.com/archives/C0229UT3HSR/p1644860688557609)
- Outline of the process can be found in #21026

---
## Tasks
- [x] Create the RFC
- [x] Share with leadership and stakeholders

## Acceptance Criteria 
- [x] The RFC has been written, shared, and [linked](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-comment/2022-03-21-public-url-for-platform-tools.md) to this issue

**Comment by jhouse-solvd** [comment]
Worth a look: 

https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

**Comment by jhouse-solvd** [comment]
PR Merged. Leaving this open until the RFC is shared.

**Comment by jhouse-solvd** [comment]
2022-03-21 [RFC: Public URL for Platform Tools ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-comment/2022-03-21-public-url-for-platform-tools.md)

**Comment by jhouse-solvd** [comment]
To be shared by engineering leadership soon [(thread for details)](https://dsva.slack.com/archives/C0229UT3HSR/p1648653420877189)

This issue can be closed. Follow-up on the RFC will happen separately from this issue.
