### ISSUE TITLE
[SW-Content]  Compose and publish content for Identity team - Inherited Proofing - 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38832]
## Story
As a Veteran or VA.gov user I want to use modern, secure credential service providers, So that I can ensure that my information is safe when accessing VA services.

## Resources
#38185
#38416

## Tasks
- [ ] Compose content for MHV inherited Proofing pages
- [ ] Have pages reviewed by editors
- [ ] Save copy in Draft for final review

## Acceptance Criteria
*  Align with IA design
*  Draft is saved for OCTO and stakeholder review

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
