### ISSUE TITLE
HLR/NOD: Replace Modal with va-modal web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38843]
## Description

Higher-Level Review & Notice of Disagreement forms are still using the React `Modal` component. These need to be replaced by. the `va-modal` web component.

## Tasks

- [ ] Switch to `va-modal`
- [ ] Update tests

## Defintion of done

- [ ] All tasks complete
- [ ] All tests passing
