### ISSUE TITLE
Communicate researcher role in Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38846]
## User Story
As a VFS product manager, I want to know if/when the guidance around a Collaboration Cycle touchpoint changes so that I can ensure my team is prepared. 

As a UX Researcher on Governance team, I want to ensure that VFS teams are aware that research as a practice area has been incorporated into Design Intent and Midpoint Review so that they know to expect feedback from me/research.

- Intended Audience: VFS teams
- Desired Outcome: VFS teams are aware that research is integrated into more of the Collaboration Cycle
- Due Date: 

## Description
In tickets #36887 and #36956, we updated our VFS-facing guidance and documentation on Platform Website to integrate research as a practice area. This means that the Governance team UX researcher will provide feedback where defined, and VFS teams may or may not need to include additional research artifacts.

NOTE: #38510 (Staging Review) has been put on hold until Clayton has attended 6-8 Staging Reviews
The purpose of this ticket it to communicate the change appropriately to the VFS audience. We will follow the guidelines defined in the [Platform communications playbook - Guidelines](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1927675936/Platform+communications+playbook+-+Guidelines) under Communication Type = Change.

_Additional background for [Collaboration Cycle - Transition VFS research activities to Platform](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32698) initiative_

## Artifacts Needing Updates
[Collaboration Cycle Change history log](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)

## Tasks
N/A

## Acceptance Criteria
- [x] Announcements follow Playbook
  - [x] Collab Cycle change history log on Platform Website has been updated per guidance
  - [x] Posted on vfs-all teams ([April 13th](https://dsva.slack.com/archives/CE4304QPK/p1649877742610189))
  - [x] Announced in ToT ([April 5th](https://dsva.slack.com/archives/CE4304QPK/p1649177751962189))
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@shiragoodman I detailed out the communication playbook guidelines in the AC and checked off/linked ones that we have done. Would you mind reviewing this ticket and determining if it can be closed?

**Comment by shiragoodman** [comment]
looks good to me!
