### ISSUE TITLE
Remove references to axe-coconut

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38844]
## User Story
As a VFS team member, I want to view up to date documentation from Platform so that I can trust the guidance and not have to waste time going down dead end paths.

- Intended Audience: VFS teams
- Desired Outcome: no more references to axe-coconut on Platform Website
- Due Date: 

## Description
The chrome extension axe-coconut is no longer available. See ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/38666.

The purpose of this ticket is to remove references to axe-coconut in the [How to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html).

## Artifacts Needing Updates
[How to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)

## Tasks
N/A

## Acceptance Criteria
- [x] "How to prepare for an accessibility staging review" on Platform Website has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@shiragoodman The reference to axe-coconut has been removed from Dev docs 'How to prepare for an accessibility staging review'.  The change was peer-reviewed and approved.  Change is currently in scroll viewport awaiting further action.

**Comment by shiragoodman** [comment]
looks good to me! Closing.
