### ISSUE TITLE
Assess where to put the entry points for the 22-1990e form

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#38853]
## Issue Description
With the 22-1990e online being updated for authenticated users applying for Transfer of Entitlement benefits, Sitewide Content and IA needs to determine on which static page to put the entry point. In ticket #37658, Mikki suggested either the [Transfer your Post-9/11 GI Bill benefits page](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) or the [Survivor and dependent benefits page ](https://www.va.gov/education/survivor-dependent-benefits/).

Once we've determined which page, we need to write the content, which can be done in a separate ticket. 

## Tasks
- [x] Assess the correct entry point page (Beth/Mikki)
- [x] Create new ticket to implement content work

## Acceptance Criteria
- [x] Entry points have been decided

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Putting here a summary of our conversation last week about the approach to entry points and edits to existing pages.

1/ Create a new tier 1 page for family members to learn about using transferred benefits (something like "Transferred entitlement for family members"). This is a change from the currently less-than-ideal state in which 2 audiences are addressed on the existing [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) page. 

2/ Add a Q&A to the existing landing page for Fry and DEA, [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/), that addresses transferred entitlement more prominently (currently there's text about this buried at the bottom of the blue box). Instead we'll add a Q&A to the bottom of the page that briefly addresses transferred benefits and links over to the new tier 1 page. In addition, on this landing page we'll:
- delete the comparison chart that's currently at the bottom of the page since that info will move to a new R&S page--see No. 3 here), and
- Create a new Q&A to house the content currently under "How do I get these benefits?" that outlines the high-level differences between Fry and DEA. So all that will remain under "How do I get these benefits?" will be "You can apply online right now" and a link to the Chapter 35 application. See this preview link with these edits: http://preview-prod.vfs.va.gov/preview?nodeId=984 

3/ Create a new R&S page with all the info from the chart on [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) (Compare DEA and Fry Scholarship benefits).

Next steps:
- The content team will create the 2 new pages. 
- Once the new tier 1 page and the new R&S page are created, we'll need to share all this with stakeholders. Including the newly reframed existing survivor-dependent-benefits page. 
- Update product team on all this.

**Comment by mnorthuis** [comment]
Thank you @bethpottsVADEPO!  When you have a general draft of the new benefit hub page, send me a link and we can establish the URL and appropriate links to be implemented.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Here's the new page in draft form--I'm still working on it and will likely move some of the content around, but we can probably figure out the H1/URL at this point. http://preview-prod.vfs.va.gov/preview?nodeId=44698

**Comment by bethpottsVADEPO** [comment]
@bethpottsVADEPO Noting here so I don't forget to do it: Last remaining update to be made--that isn't implemented yet in drupal...

https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/

I need to update the existing Transfer benefits tool page (above) to account for the fact that some of the content there has been moved to the new tier 1 page about using transferred benefits. Specifically need to address the H2 "When can they use the transferred benefits?" Might want to delete this and instead create a new Q&A for this page that will link over to the new tier 1 page, where that question is answered--there's other info too about dependents using these transferred benefits.

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola We'll need to ask stakeholders to review 2 new pages and edits to an existing page. This work is related to entry points to the 1990e. I can outline this for them in an email and/or set up a meeting with them. It's up to you if you'd like this to be communicated through you or me. I do know the Education Service folks, so I'm happy to handle this separately myself, but I wanted to check with you and see if you'd prefer to drive this stakeholder review. Here's what we need them to review:

1/ New tool landing page, where there will be an entry point to the 1990e (Mikki had initially suggested the entry point be on an existing page, but she and I have discussed this and decided it really requires a new page):
http://preview-prod.vfs.va.gov/preview?nodeId=44698 (you have to been on the VA network for this preview link to work)

2/ On the [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page, add teaser text and a link to the above tool landing page. 
Preview of this: http://preview-prod.vfs.va.gov/preview?nodeId=984 (you have to be on the VA network for this preview link to work)

3/ New resources and support page that has all the info from the comparison chart (this is related work to meet accessibility standards about charts and to shorten the [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page: http://preview-prod.vfs.va.gov/preview?nodeId=44718 (you have to be on the VA network for this preview link to work)

**Comment by alexander-ferzola** [comment]
Hi @bethpottsVADEPO thanks for including us in this thread. We'd defer to your team to take first crack at updating these entry points. Our team will continue to focus on updating other aspects of the application. Please keep us in the loop with your progress!

**Comment by RLHecht** [comment]
We have these entry points being tracked in other tickets for when the tool is launching, so we can close this one out.
