### ISSUE TITLE
[FE] Update demographics API call to not send if all demographics pages have been skipped

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#38856]
## User Story
As a user, my demographics confirmations should not be sent in day-of check-in if all confirmation pages have been skipped

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description
Modify the demographics api call on the day-of confirmation page to not send if no demographics have been seen by the user. 

## Tasks
- [ ] Update demographics api call to not send if no demographics have been confirmed
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by dcgoodwin2112** [comment]
https://dsva.slack.com/archives/C02G6AB3ZRS/p1647884634797039
