### ISSUE TITLE
Add scripts for Design Intent, Midpoint Review and Staging Review to their respective Platform Website pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38850]
## User Story
As a VFS team member, I want to have a clear understanding of what will happen at a Collaboration Cycle review so that I can ensure my team is prepared.

- Intended Audience: VFS teams
- Desired Outcome: Script for each meeting is shared on Platform Website
- Due Date: 

## Description
In order to ensure there is no gap of understanding from the operational side (guidance documented in Confluence for Governance team to follow) to the VFS facing side (Platform Website), we should be as transparent as possible. The script that is read before each Collaboration Cycle Governance-owned touchpoints (Design Intent, Midpoint Review and Staging Review) should be published to Platform Website so it is clear what is expected.

_*Please note that this is a short term fix to address an immediate need. Platform Governance team will be modifying/updating our VFS facing guidance and documentation in a larger initiative._ 

## Artifacts Needing Updates
[Platform Website: Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
[Platform Website: Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
[Platform Website: Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)

## Tasks
- [x] Scripts can be found here:
   - https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities#During-Meeting
   - https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities#During-Synchronous-Meeting
   - https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#During-Meeting

## Acceptance Criteria
- [x] "Platform Website: Design Intent" on Platform Website has been updated per guidance
- [x] "Platform Website: Midpoint Review" on Platform Website has been updated per guidance
- [x] "Platform Website: Staging Review" on Platform Website has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@chaseakirby please review the following docs

[Design intent](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2146435098/Copy+of+Design+intent)
[Midpoint review](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2146435110/Copy+of+Midpoint+review)
[Staging review](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2146304008/Copy+of+Staging+review)

**Comment by chaseakirby** [comment]
@allison0034 Thanks Allison! 
I was wondering if it might make sense to move it up under the "Objective". I could see it being more visible there but also may get confusing since it would be Objective then Moderator Script.

**Comment by allison0034** [comment]
@chaseakirby yes and done! Let me know when I can move it live.

**Comment by chaseakirby** [comment]
@allison0034 Looks good to me!

**Comment by shiragoodman** [comment]
looks good to me! Closing.
