### ISSUE TITLE
Rename the Research Plan Review to Research Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#38851]
## User Story
As a VFS team member, I want to be able to quickly and easily understand the scope/purpose of the Collab Cycle review based on the name so that I don't make any assumptions about what is included or not included in the touchpoint.

As a Governance team member, I want to make sure that the name of the research-focused Collaboration Cycle touchpoint review is clear and easy to understand so that there is no confusion among those involved.

- Intended Audience: VFS and Platform
- Desired Outcome: Research Plan Review is renamed Research Review (or other name. Recommendations @claytonzook ?)
- Due Date: 

## Description
As new UX Researcher Clayton Zook has gotten up to speed on the Research Plan Review, he has commented that the name of the touchpoint is misleading and/or confusing. The Research Plan Review is currently inclusive of 1) support reviewing the research plan, 2) support during the research study, and 3) support post completion of the research. The name "Research Plan Review" implies that support is only provided during that first phase. 

We'd like to change the name of the review to just Research Review, or something similar, to minimize confusion.

_Additional background for [Collaboration Cycle - Transition VFS research activities to Platform](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32698) initiative_

## Artifacts Potentially Needing Updates
[Platform Website: CC Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)
[Platform Website: Research plan review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
[Platform Website: CC Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
[Platform Website: CC Kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Collaboration-Cycle-Kickoff.1760493650.html)
[Confluence: CC kickoff - moderator responsibilites](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Confluence: Research Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2068119555/Research+Review)

Checked but didn't require updates:
[Confluence: Reviewing Research Plan (Moderated and Unmoderated)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2098888756/Reviewing+Research+Plan+Moderated+and+Unmoderated)
[Confluence: Reviewing Conversation Guide (Moderated)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2098823215/Reviewing+Conversation+Guide+Moderated)
[Confluence: Reviewing Study Implement and Intro Email (Unmoderated)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2098790556/Reviewing+Study+Implement+and+Intro+Email+Unmoderated)
[Confluence: Setting Up Recruitment with Perigean (Moderated and Unmoderated)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2099577036/Setting+Up+Recruitment+with+Perigean+Moderated+and+Unmoderated)

## Tasks
- [x] discuss name change with Shane
- [x] Platform website page changes are cued up, in draft version
- [x] Confluence pages reviewed for needed changes

## Acceptance Criteria
- [x] Shane Strassberg has approved name change
- [x] Confluence documents have been updated per guidance
- [x] Platform Website pages have been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Final sign-off on name change from Shane Strassberg
- [x] Teams notified of change in Slack #vfs-all-teams (being addressed in [ticket #38846](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/38846))

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
@shiragoodman Are you doing the all-teams channel announcement on this? I think that the last real item on this ticket.

**Comment by chaseakirby** [comment]
@claytonzook Most of the pages look good to me.
I noticed that the "Research Review" page on [Platform Website: CC Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) navigates to a blank draft Confluence page. I think it should redirect to [Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-review.1781891143.html) or somewhere else within Platform Website.
(It also looks like a couple other pages do the same so those other pages sound like a fine tech-debt ticket)

**Comment by shiragoodman** [comment]
@claytonzook yes, the announcement was made on 4/13.

**Comment by claytonzook** [comment]
@chaseakirby good catch. I'll put in a tech debt ticket for that

**Comment by claytonzook** [comment]
@chaseakirby [ticket 40053](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/40053). Please feel free to go ahead and assign to me once you have a chance to make sure the ticket is ready to go.

**Comment by chaseakirby** [comment]
@claytonzook Thanks for making that ticket Clayton! I think that we can edit that ticket to check for other links like that in Platform Website. We just had a Support ticket come in that directly mentioned those links so I see Shira took care of most of them on the CC Overview page.
We should use this ticket to check for other dead links specifically to the Research Review page since this is the ticket making those changes. (Hopefully that makes sense)

**Comment by shiragoodman** [comment]
@chaseakirby can you close this?

**Comment by chaseakirby** [comment]
@shiragoodman @claytonzook Yep! I checked over the links that Clayton identified as needing updated. All of those work so we can close out this ticket. Clayton, if we find any other broken page links outside of these in this ticket, we can add them to #40053 that you created.
