### ISSUE TITLE
(Q2) Clean up work associated with Sidekiq UI

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#38869]
## Problem Statement 
Sidekiq UI has been stood up in a development environment. Once we have stood up services they can be considered for removal from `vets-api`. 

## Hypothesis or Bet
Removing unused services and code from `vets-api` will help us simply the codebase and help work towards identifying how to organize this code. 

## We will know we're done when... ("Definition of Done")
- [ ] We have determined if we are able to promote Sidekiq UI to staging/production. 
- [x] We have created a test plan for this promotion.
- [ ] We have completed any miscellaneous clean-up tasks needed for Sidekiq UI.

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
_Q2_
