### ISSUE TITLE
[UX] Complete Content Review

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38865]
## Problem Statement
UX needs to complete a content review. Once we complete this ticket, the engineering ticket above, and have all the JSON files, then we can submit to the State Dept.
- We need to review the content to flag possible terms that may cause extra complication for translation e.g. are these ones we should keep in English. 
- Mark when links go to english pages. Danielle has examples of what this looks like.
- Privacy Act Statement will need to have the English note on the link.
- Do we need to add Spanish language assistance information within our check-in experience?

## Tasks
- [x] Tag what words the VA translators need to look at
- [x] Hand off to Danielle in a meeting

## Acceptance Criteria
- [x]  Capture in a word document

**Comment by kristenmcconnell** [comment]
[Final .json files.](https://app.zenhub.com/files/133843125/c9c96683-0711-4d6f-90cd-902c95822b54/download)

We changed the format of the [content review document to a spreadsheet](https://docs.google.com/spreadsheets/d/1xv63kaIR_UMq1bssSleMODXEV14OOGwfcL41rBBWhwk/edit?usp=sharing). 

Nira messaged Danielle via Slack to set up a time to review the spreadsheet. Further work will take place within #39281.

**Comment by kristenmcconnell** [comment]
Adrian made an update to the va.gov .json for translation. The most up-to-date file can be found [here](https://dsva.slack.com/archives/C02G6AB3ZRS/p1648671035690239?thread_ts=1646939732.858079&cid=C02G6AB3ZRS).
