### ISSUE TITLE
Mark TestRail Accounts with >180 Days Inactivity as `Inactive`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#38875]
## Issue Description
There are many inactive users in TestRail. In order to reduce the billing (which is evaluated each month on a per user basis), we need to warn users that inactive accounts will be archived and made inaccessible unless they log on within the next week.

---
## Tasks
- [x] Create a message to send to Slack
- [x] Drop the message into the appropriate Slack channels
- [x] Remind teams during the Team of Teams to log into their accounts to keep them active
- [x] After the waiting period (5 business days) change the accounts with no activity in the past 180 days to `inactive`

## Acceptance Criteria
- [x] TestRail accounts with no activity in the last 180 days have been marked `inactive`
---

**Comment by pjhill** [comment]
Attention:
In an effort to recapture TestRail accounts for reallocation to active teams on the VA.gov Platform, we will be deactivating TestRail accounts that have been inactive for the past 180 days. If you intend to continue your use of TestRail, please log into your account before 3/31/2022. All accounts that have been inactive for >180 days on March 31st, 2022 will be archived.

**Comment by pjhill** [comment]
This was completed. Approximately, 20 users were moved to inactive.
