### ISSUE TITLE
CST: Replace CollapsiblePanel with va-accordion

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#38879]
## Description

The Claim Status Tool uses the deprecated `CollapsiblePanel` React component. The Design System Team has mapped out the steps to a [guide to migrate it to use the `va-accordion`](https://vfs.atlassian.net/wiki/spaces/DST/pages/2127527996/Manual+Component+Migration+Guide#Collapsible-Panel-to-va-accordion%3A)

## Tasks

- [ ] Replace `CollapsiblePanel` with `va-accordion` per guide
- [ ] Update tests

## Definition of done

- [ ] `CollapsiblePanel` components replaced
- [ ] All tests passing
