### ISSUE TITLE
UX research and design process documentation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38896]
## Issue description
VSA UX transition document was created in #38025 as part of the documentation on the status of our products to ensure continuity of work. This issue continues that effort.

## Tasks
- [ ] Complete [Our UX research and design process section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/vsa-ux-transition-doc.md#our-ux-researchdesign-process) of VSA UX Transition document
- [ ] Review and edit other sections of VSA UX Transition document as needed

## Acceptance Criteria
- [ ] Transition document provides a central starting point for links to UX research and design work products produced during design and development.

**Comment by mmiddaugh** [comment]
Complete - [VSA UX Transition document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/product-transition-doc/vsa-ux-transition-doc.md)
