### ISSUE TITLE
Application Hosting and Deployment: Standardize application management for Platform Crew teams (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#38890]
**Note: This initiative began in July '22 and should be in the "Current" column. - @jhouse-solvd 9/14**

## Problem Statement 
The application management experience in EKS is ambiguous and incomplete in places. The processes for onboarding an application, promoting an application to higher environments, and troubleshooting an application deployment are insufficient to support self-service capabilities.

## How might we 
...make the platform's application hosting and deployment solution a self-service product? 
...standardize the packaging format for applications that are deployed to EKS?
...improve the application onboarding experience? 
...define a process for promoting an application from the dev environment to higher environments? 
...promote self-service capabilities for developers that are deploying applications to EKS? 
...provide developers with documentation and examples that allow them to manage their applications effectively? 
...better communicate the status of tasks performed? _(ie blocking tasks that must be performed by the infrastructure team)_ 

## Hypothesis or Bet
Platform teams will be able to deploy applications to EKS independently (ie not blocked on the Platform Infrastructure team)  
Platform teams will know how to deploy applications to EKS. 
Platform teams will be able to deploy new applications faster. 
Application teams will be able to focus on packaging and deploying an application, rather than managing the underlying infrastructure of EKS. 
The Platform Infrastructure team will be able to focus on managing the delivery infrastructure, rather than application delivery. 

## We will know we're done when... ("Definition of Done")
- Standard process for deploying applications to EKS 
- There is one standardized packaging format for developers to use (e.g. Helm)
- Developers have the ability to... 
  - package an application 
  - deploy an application 
  - troubleshoot an application 
  - promote an application to higher environments 
- There is developer documentation that explains how to
  - package an application 
  - deploy an application 
  - troubleshoot an application 
  - promote an application to higher environments 
- There is operational documentation that explains how...
  - the overall delivery system works... 
   - how ArgoCd works 
   - how EKS works 
   - how application delivery infrastructure is tied together end-to-end 
  - to troubleshoot deployments 
- There are issue templates for:
  - Onboarding a team to EKS, (ie access to Clusters, ArgoCD, etc)
  - Onboarding a new application to EKS (MVP exists now)
  - Promoting an application to a higher environment in EKS (this doesn't exist yet) 
- Follow up issues have been created to bring existing applications into the standard packaging format 
- Feedback has been requested from users of this process 
  - create a follow-up item to evaluate feedback after the release 
- Feedback has been requested from the SRE Team (ie, Is the SRE team able to support this service?)
   - create a follow-up item to evaluate feedback after the release 

## Known Blockers/Dependencies 
None

## Projected Launch Date
End of Q3, 2022 

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [x] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Stakeholder-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] Operator-facing
- [x] User-facing:  exists for this product/feature tool
- [ ] _(if applicable)_ Follow the Platform's ["Change Communication Plan"](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647898/Change+Communication+Plan)

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [X] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. _Note: This system was already live when this initiative began. The goal of the initiative was to standardize packaging formats. These were implemented and tested incrementally with live applications that are actively being deployed to multiple environments._ 

### Documentation
* **`PRODUCT_NAME`**: Application Hosting and Deployment using Container Orchestration
* **Product Outline**: [Application Hosting and Deployment using Container Orchestration](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS) 
* **User Guide**: "[Manage applications in EKS](https://vfs.atlassian.net/wiki/spaces/OT/pages/2348909545/Manage+applications+in+EKS)"

### Testing

* **Usability test**: Multiple platform teams are actively using the system to deploy applications to EKS. 
* **Manual QA**: Multiple tests were performed using the user-facing forms and templates
* **Automated tests**: N/A

### Measurement

* **Success metrics**: Successful deployments can be found using ArgoCD. 
* **Release plan**: The app delivery solution is live. This initiative was undertaken to standardize packaging formats. 

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
_Next epics:_

**[Application Hosting and Deployment] Update onboarding template based on Q1 feedback** 
**[Application Hosting and Deployment] Standardize application manifests (EKS + ArgoCD)** 
 **[Application Hosting and Deployment] Update documentation based on Q1 feedback**

**Comment by ericboehs** [comment]
Jesse and I were talking about dropping code into a respective app's repository (e.g. deploy workflow). Riley and Jeremy Wu have got this working as a button in the Platform Console (it will open a PR to add a workflow to the repo). Let's collab on this epic to automate onboarding apps via the Platform Console.

**Comment by jhouse-solvd** [comment]
Additional epics to create: 

**[Application Hosting and Deployment] Provide developers with tools to manage an application in EKS** 
**[Application Hosting and Deployment] Define a process that allows developers to promote applications to higher environments**

**Comment by jhouse-solvd** [comment]
@npeterson54 mentioned that IET might be working on a playbook about 'how to deploy an application to EKS'

**Comment by ericboehs** [comment]
> are we only talking about shell/exec access here?

I think so. I'm sure there will be other things in the future but I believe Argo + exec will give us a majority of what we need.

**Comment by zachclarity** [comment]
The SRE team will need to create FAQs and incident playbooks to support requests after the K8 is on PROD.  We will follow this work.

**Comment by annekerr49** [comment]
@jhouse-solvd Please update this requesed item.

**Comment by jhouse-solvd** [comment]
All epics and issues have been completed. Documentation has been linked to this initiative, and to epics and issues within. 

This initiative can be closed.
