### ISSUE TITLE
Find-forms not returning correct results

### ISSUE THREAD

**Issue by TSimmz** [department-of-veterans-affairs/va.gov-team#38908]
## Issue Description
When using Find VA Forms, if I search "21-22" I should get form 21-22 and 21-22a, but it is only showing 21-22a.

---
## Tasks
- [ ] Investigate and troubleshoot the issue

## Acceptance Criteria
- [ ] Find VA Form will return both forms
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
@TSimmz - is this going to make it into this sprint?

**Comment by leahkeeler** [comment]
@TSimmz - Can you update with what was doen to replicate/research please?

**Comment by TSimmz** [comment]
Initially was able to recreate this, but after coming back to it a few days later, the missing form was there. Could not reproduce after that. We initially thought that the form was mistakenly deleted (archived) in the forms database, then re-added later, but after checking the CMS logs, that was not the case. 

@davidconlon noted that there did seem to be an issue with the `vets-api` that day which may have been the cause.  

This issue may arise again so moving to backlog.
