### ISSUE TITLE
[VAMC-VET center] Provide Office hour support for VET Center development and content [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38914]
## Story
As a VET center editor I need direction support and status updates, so I can get the training I need, understand page intent and what to input in my VET center website.

## TASKS
Provide:
- [x] 2 Weekly office hour meetings
- [x] Daily support for CMS support tickets.

## Acceptance Criteria
- [x]  All meetings, and support calls are presented and responded to during sprint.
