### ISSUE TITLE
Console Services: Platform Console - Provide Deployment Status of applications within the Platform Console

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#38916]
This has been De-Prioritized due to the vets-api to Kubernetes move being a higher priority and team changes/contracts expiring.  

## Problem Statement 
As a VSP developer within the platform console, there is no way for me to be able to see if a deployment of my application is up and running.  

We might be able to address this by completing the integration with the Platform Infrastructure so that we are able to display an applications' deployment status. 

## Hypothesis or Bet
- Once a deployment is made, a VSP developer will be able to see if their deployment was successful or not.  
- Having this information within the Platform Console will allow the users to stay within the Console and not search for this information elsewhere.  

## We will know we're done when... ("Definition of Done")
- Users are able to see the following: 
Sync Status
App Health
Current Commit
Previous Commit
Deploy Times

## Known Blockers/Dependencies 
- In order for us to display an apps deployment status, it first must be added to Argo. 

## Projected Launch Date
April 30, 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by npeterson54** [comment]
We may have a dependency on the AMT team to get ARGO and Keycloak integrated

**Comment by npeterson54** [comment]
Potential stories
-[ ] Make API available 
-[ ] Documentation (started, not complete) 
-[ ] Investigate DEX locally

**Comment by npeterson54** [comment]
This should be moved to the backlog/icebox. It has been de-prioritized.

**Comment by EricaRobbins** [comment]
@raywangoctova - I see this one has been closed in the repository. Can you please check the accuracy on this one?
Is this work still pending? Thanks!

**Comment by EricaRobbins** [comment]
Console work has been on-hold for a long time. Moving this to the backlog, possibly needs a new title.
Still a need. Follow up with Eric and update this card @BillChapmanUSDS

**Comment by annekerr49** [comment]
Assign to Aparna and Jeff reopen

**Comment by annekerr49** [comment]
Aparna to follow up with Nate to see if this is out of date.

**Comment by annekerr49** [comment]
Jennifer and Grace are touching base on this issue and I think they have worked a solution.  I will keep you in the loop if additional help is needed.
I think this is getting deprioritized due to Code.va.gov,
Aparna will check with Nate to see if this is still relevant and if it is blocked or is not relevant any more.

**Comment by EricaRobbins** [comment]
@JeffKeeneVAGov - Either edit card or start new card for Code Owners.

**Comment by EricaRobbins** [comment]
Jeff K. says this is not what Atlas will be doing. Closing this ticket.
