### ISSUE TITLE
Console Services: Team Documentation - Documentation audit and update

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#38917]
## Problem

Since migrating team documentation to Confluence, only cursory updates have been made to both our internal and external documentation. This can make it difficult for VSP and VFS developers to get the right information without reaching out for support.

## Hypothesis

- This will make it easier for VSP and VFS developers to find answers to their questions without having to reach out to a person for support.
- This will make it easier for future onboarding team members to get up to speed faster.

## Acceptance Criteria

- Each document that Console Services owns will have been looked over and updated by two developers.

## List of Documents

Document indexes grouped by their audience:

- Console Services Team (Internal)
    - [Console Services Team (Confluence)](https://vfs.atlassian.net/wiki/spaces/BTT/overview)
- Platform Developers
    - [VSP Internal - Console Services (Confluence)](https://vfs.atlassian.net/wiki/spaces/VI/pages/557416547/Console+Services)
- VFS Developers
    - [Developer docs (Confluence)](https://vfs.atlassian.net/wiki/spaces/pilot/overview)
    - [Getting started (Confluence)](https://vfs.atlassian.net/wiki/spaces/GS/overview)

---

All documents grouped by their audience:

- [x] Console Services Team (Internal)
    - [x] [Console Services Team (Confluence)](https://vfs.atlassian.net/wiki/spaces/BTT/overview)
- [x] Platform Developers
    - [x] VSP Internal - Console Services
        - [x] #42364
            - [x] [Repositories -- Backend](https://vfs.atlassian.net/wiki/spaces/VI/pages/802586647/Repositories+--+Backend)
                - #42724
            - [x] Archive [Initiatives -- Backend Tools](https://vfs.atlassian.net/wiki/spaces/VI/pages/912818201/Initiatives+--+Backend+Tools) - #42380
            - Onboarding & Training Docs
                 - [x] [VFS Orientation](https://vfs.atlassian.net/wiki/spaces/VI/pages/937656409/VFS+Orientation)
                 - [x] [Console Services New Team Member Orientation](https://vfs.atlassian.net/wiki/spaces/VI/pages/975175816/Console+Services+New+Team+Member+Orientation)
            - [x] [Rails Module Generator](https://vfs.atlassian.net/wiki/spaces/VI/pages/807174195/Rails+Module+Generator) - #42218 
            - [x] [Sidekiq Access](https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Access) - #42282
            - [x] [Dangerbot](https://vfs.atlassian.net/wiki/spaces/VI/pages/972292124/Dangerbot)
            - [x] [Tool Logins](https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins) - #42637
                - This feels internal to our team and not for platform developers, move?
            - [x] [Investigate toolkit tracking approaches](https://vfs.atlassian.net/wiki/spaces/VI/pages/1044283450/Investigate+toolkit+tracking+approaches) - #42638 
            - [x] [Datadog Latency](https://vfs.atlassian.net/wiki/spaces/VI/pages/1077412038/DataDog+Latency)
                - Rename to be more apparent
            - [x] [VTK Phase 2 Planning](https://vfs.atlassian.net/wiki/spaces/VI/pages/1099759633/VTK+Phase+2+Planning) - #42402
            - [x] [PgHero](https://vfs.atlassian.net/wiki/spaces/VI/pages/1403322455/PgHero)
            - [x] [Session Key Rotation for Vets API](https://vfs.atlassian.net/wiki/spaces/VI/pages/1766621207/Session+Key+Rotation+for+vets-api) - [#42220](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42220)
                - Rename to use "Vets API" wording
            - Needs further review of their completion
                - [x] [Detaching an instance from an ASG in AWS](https://vfs.atlassian.net/wiki/spaces/VI/pages/1878032385/Detaching+an+instance+from+an+ASG+in+AWS)
                - [x] [Rotating DB records via Sidekiq](https://vfs.atlassian.net/wiki/spaces/VI/pages/1982136325/Rotating+DB+Records+via+Sidekiq)
                - [x] [Adding a user to GIDS dashboard](https://vfs.atlassian.net/wiki/spaces/VI/pages/2089845331/Adding+a+user+to+GIDS+Dashboard)
                - [x] [Running ArgoCd Locally](https://vfs.atlassian.net/wiki/spaces/VI/pages/2121465877/Running+ArgoCd+Locally+for+platform-console-api)
                - [x] [Keylcoak/Argo Integration Local Setup (withouth Dex)](https://vfs.atlassian.net/wiki/spaces/VI/pages/2157183055/Keycloak+Argo+Integration+Local+Setup+without+Dex)
                - [x] [Github Integration](https://vfs.atlassian.net/wiki/spaces/VI/pages/2156953683/GitHub+Integration)
                - [x] [Platform Console API Argo Integration Contingency Plan](https://vfs.atlassian.net/wiki/spaces/VI/pages/2182119552/Platform+Console+API+Argo+Integration+Contingency+Plan)
                - [x] [DataDog APM (Internal)](https://vfs.atlassian.net/wiki/spaces/VI/pages/2184708125/DataDog+APM+Internal)
                - [x] [How to use Datadog for APM](https://vfs.atlassian.net/wiki/spaces/VI/pages/2187264019/How+to+use+DataDog+for+APM)
                - [x] [Rails Console Access](https://vfs.atlassian.net/wiki/spaces/VI/pages/2189623712/Rails+Console+Access)
                - [x] [vets-api Deployment Process](https://vfs.atlassian.net/wiki/spaces/VI/pages/2210136219/vets-api+Deployment+Process) - #42221
                    - Rename to use "Vets API" wording
                - [x] [Detaching an instance from an ASG in AWS](https://vfs.atlassian.net/wiki/spaces/VI/pages/1878032385/Detaching+an+instance+from+an+ASG+in+AWS)
                - [ ] [Keycloak / Platform Console API - OAuth Integration](https://vfs.atlassian.net/wiki/spaces/VI/pages/2213707860/Keycloak+Platform+Console+API+-+OAuth+Integration)
- [x] VFS Developers
    - [x] [Developer docs (Confluence)](https://vfs.atlassian.net/wiki/spaces/pilot/overview) - Lindsey (will be looking at this Tuesday)
        - [x] [Code and build](https://depo-platform-documentation.scrollhelp.site/developer-docs/code-and-build)
            - [x] [How we use GitHub code owners] - #42449 (https://vfs.atlassian.net/wiki/spaces/pilot/pages/655032344/How+we+use+GitHub+code+owners) - #42427
            - [x] [Current:Submitting pull requests for approval](https://vfs.atlassian.net/wiki/spaces/pilot/pages/655032351/Submitting+pull+requests+for+approval) - #42425
            - [x] [Current:Pull request best practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices) - #42473
            - [x] [Current:Personal Identifiable Information (PII) guidelines](https://vfs.atlassian.net/wiki/spaces/pilot/pages/894271679/Personal+Identifiable+Information+PII+guidelines) - #42418
            - [x] [Current:Creating New Github Repositories in VA Github Org](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2113798235/Creating+New+Github+Repositories+in+VA+Github+Org) - #42486
        - [x] [Backend Developer Documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886289964/Backend+developer+documentation)
            - [x] [Backend Architecture](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884520566/Backend+Architecture) - #42372
                - [x] [Authorization Design Doc](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887338517/Authorization+Design+Doc)
                - [x] [Integration Approach](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567946/Integration+Approach)
                - [x] [Overview](https://vfs.atlassian.net/wiki/spaces/pilot/pages/844955712/Overview)
            - [x] [Best Practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/best-practices-1) - #42285
                - [x] [Tutorials](https://depo-platform-documentation.scrollhelp.site/developer-docs/tutorials) - this was removed
                    - [x] [Backend Endpoint Tutorial ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886978053/Backend+Endpoint+Tutorial)
                        - [x] [Supporting Code](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887010852/Supporting+Code)
                            - [x] [Betamocks Config](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887010859/Betamocks+Config)
                            - [x] [Betamocks Mockdata Example](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831242/Betamocks+Mockdata+Example)
                            - [x] [Controller Route Serializer ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814232/Controller+Route+Serializer)
                            - [x] [Match Response Schema Implementation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781452/Match+Response+Schema+Implementation)
                            - [x] [Service Object Implementation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885700252/Service+Object+Implementation)
                            - [x] [Spec File Examples ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885700259/Spec+File+Examples)
                            - [x] [Swagger Implementation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586101/Swagger+Implementation)
                - [x] [Writing Small PRs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798516/Writing+Small+PRs)
            - [x] [Backend Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-standards)
                - [x] [Working with the engineering team](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887141893/Working+with+the+Engineering+Team)
                - [x] [Key Management](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886879804/Key+Management)
                - [x] [Threat Model in Practice](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886879813/Threat+Model+in+Practice)
                - [x] [Vets API database Migrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/689832034/vets-api+database+migrations)
                - [x] [Security Review](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885733207/Security+Review)
                - [x] [How to use encrypted attributes](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1911390216/How+to+use+encrypted+attributes+in+vets-api)
            - [x] [Tools and Debugging](https://depo-platform-documentation.scrollhelp.site/developer-docs/tools-and-debugging)
                - [x] [Triage Tier Definitions ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887272961/Triage+Tier+Definitions)
                - [x] [Set up your AWS account](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account)
                - [x] [StatsD Metrics](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847017/StatsD+Metrics)
                - [x] [Breakers Outages](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887338538/Breakers+Outages)
                - [x] [Triaging API errors](https://vfs.atlassian.net/wiki/spaces/pilot/pages/687931492/Triaging+API+errors)
                - [x] [AWS Shell Access](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586192/AWS+Shell+Access)
                - [x] [Beta Mocs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889796126/Betamocks)
            - [x] [Running Vets API Locally](https://depo-platform-documentation.scrollhelp.site/developer-docs/running-vets-api-locally)
                - [x] [Backend](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567963/Backend)
                - [x] [Base Setup](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887502459/Base+Setup+-+vets-api)
                - [x] [Contributing to VA.gov Projects](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1891500052/Contributing+to+VA.gov+Projects)
                - [x] [Developer Setup](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885635004/Developer+Setup)
                - [x] [Native Setup](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1890254900/Native+Setup+-+vets-api)
                - [x] [Development](https://vfs.atlassian.net/wiki/spaces/pilot/pages/591134721/Development)
                - [x] [Documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721780779/Documentation)
                    - [x] [Onboarding](https://depo-platform-documentation.scrollhelp.site/developer-docs/onboarding) - #43652 
                - [x] [Authentication](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721420316/Authentication)
                - [x] [Authorization](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721387554/Authorization)
                - [x] [Forms](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721453145/Forms)
                - [x] [PDF Generation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721780786/PDF+generation)
                - [x] [Request Processing](https://vfs.atlassian.net/wiki/spaces/pilot/pages/724992009/Request+processing)
                - [x] [Request Serialization](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721420368/Response+serialization)
                - [x] [Service Objects](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721780810/Service+objects)
                - [x] [Vets API endpoint](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590872597/Vets+API+endpoint+punch+list)
                - [x] [Settings](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721616976/Settings)
                - [x] [Running the app with Docker](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1894219804/Running+the+app+with+Docker)
                - [x] [Running the app Natively](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1893793863/Running+the+app+Natively)
            - [x] Backend Workflow
                - [x] [Va.gov Continuous Integration](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887600641/VA.gov+Continuous+Integration+Process)
        - [x] [Integrations](https://depo-platform-documentation.scrollhelp.site/developer-docs/integrations) - Lindsey - #42124 
            - [x] [External Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) - #42124 
                 - [x] [Partner Services (Upstream Services)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services)
                      - [x] [External Services Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) - #42275
                          - [x] [Active Directory Federation Services](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1888485505/Active+Directory+Federation+Services) - #42281
                          - [x] [Appeals/Caseflow](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887502340/Appeals+Caseflow) - #42276
                          - [x] [ArcGIS.com](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814279/ArcGIS.com) - #42274
                          - [x] [Benefits Gateway Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887272987/Benefits+Gateway+Service) - #42327
                          - [x] [CARMA](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781482/CARMA) - #42273 
                          - [x] [Central Mail API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798523/Central+Mail+API) - #42239
                          - [x] [CMS-SSOi](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887600699/CMS-SSOi)
                          - [x] [Coronavirus Chatbot](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814308/Coronavirus+Chatbot)
                          - [x] [DS Logon](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912543/DS+Logon) - #42223
                          - [x] [Debts](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887764481/Debts)
                          - [x] [EMIS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887174669/EMIS) - #42235
                          - [x] [EVSS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240213/EVSS) - #42234
                          - [x] [EWIS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305740/EWIS)
                          - [x] [Enrollment Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601919/Enrollment+Service)
                          - [x] [GSA API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667529/GSA+API)
                          - [x] [GIDS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912583/GIDS)
                          - [x]  [ID.me](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912590/ID.me)  - #42223
                          - [x] [Lighthouse SSOi Oauth](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436803/Lighthouse+SSOi+Oauth)
                          - [x] [MDT - Denver Logistics Center](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798533/MDT+-+Denver+Logistics+Center)
                          - [x] [MVI](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847049/MVI)
                          - [x] [MVI request XML](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567937/MVI+request+XML)
                          - [x] [My Healthe Vet](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667536/My+Healthe+Vet)
                          - [x] [Pre-Needs Burial (EOAS)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305747)
                          - [x] [SSOe OAuth: Token Introspect Service and Secure Token Service (STS)] (https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887698956)
                          - [x] [SSOe](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436810/SSOe)
                          - [x] [Search.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887043657/Search.gov)
                          - [x] [TIMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798540/TIMS)
                          - [x] [VANotify](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885634900/VANotify)
                          - [x] [VBS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2120319089/VBS)
                          - [x] [VHA Access to Care](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240236/VHA+Access+to+Care)
                          - [x] [VONAPP](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240243/VONAPP)
                          - [x] [Template](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567914/Template)
                          - [x] [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service)
                          - [x] [Integration Hub (iHub)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305754)
                          - [x] [VA Profile](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885602002/VA+Profile)
                          - [x] [VR&E CMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885602009)
                          - [x] [Adding a new External Service Integration](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586162/Adding+a+new+External+Service+Integration)
    - [x] [Getting started (Confluence)](https://vfs.atlassian.net/wiki/spaces/GS/overview)

### Other Docs to Consider

- [x] [Migrating Vets-API to EKS + Developer Experience - VSP internal - Confluence](https://vfs.atlassian.net/wiki/spaces/VI/pages/1633648825/Migrating+Vets-API+to+EKS+Developer+Experience) - #42368
- [x] [VA.gov github docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/tools/backend) - #42366 

## Projected Launch Date

June 30, 2022 potentially longer

**Comment by LindseySaari** [comment]
@ericboehs I just started to link the tickets to the completed documents. Anything before now does not have a linked ticket, but if it's checked, it's completed.

**Comment by RachalCassity** [comment]
After Datadog metrics are properly set up, the documents in the External Services Integrations director might have to be updated with the correct metrics. I made an (issue) [https://github.com/department-of-veterans-affairs/va.gov-team/issues/42259] just incase.
