### ISSUE TITLE
Front End - Bad Unit Number 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3891]
This is the ticket for the front end build for the bad/ missing unit number work that needs to be implemented.
  

## User Story: 

As a front end designer, I need implement the copy changes so that I can validate this in staging. 

 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [ ] Implement Copy Changes 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] The copy changes have been made.
- [ ] The copy changes have been validated on staging.

**Comment by Samara-Strauss** [comment]
@bradl3yC copy is ready:

Scenario 1

**Please add a unit number**
It looks like your address is missing a unit number. Please edit your address to add a unit number. If you don't have a unit number and the address you entered below is correct, please select Continue.

![Add missing unit number with override](https://user-images.githubusercontent.com/34068740/70721879-5a289c00-1cc4-11ea-9056-13eeaf6787f3.png)

---

Scenario 2
**Please add a unit number**
We couldn’t verify your address with the U.S. Postal Service because it’s missing a unit number. Please edit your address below to add a unit number.

![Add missing unit number without override](https://user-images.githubusercontent.com/34068740/70721846-4e3cda00-1cc4-11ea-8d34-6563381247c0.png)

----
Scenario 3
**Please update or confirm your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number. If your unit number is already correct, please continue with the address you entered below.

![Edit bad unit number with override](https://user-images.githubusercontent.com/34068740/70721901-63b20400-1cc4-11ea-9d50-af7083797bb3.png)

----

Scenario 4
**Please update your unit number**
We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address below to update the unit number.

![Edit bad unit number without override](https://user-images.githubusercontent.com/34068740/70721929-6b71a880-1cc4-11ea-8636-cfb00b9b00ff.png)

**Comment by Samara-Strauss** [comment]
@bradl3yC can you drop a link to the associated PR here? I'm gonna keep tabs on when this goes out so I can test it out as best I can.
