### ISSUE TITLE
Revised Error Code Matrix with Updates

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3892]
## User Story: 

As a Product Manger, I need revise the error code matrix so that I can update it with the requested changes to be added to it. 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Create a GitHub version of the spreadsheet and have a column added that indicates what the VA.gov 
        experience/outcome is given that error
- [x] Be clear in the business case column. Is that the VA Profile (formerly Vet360) business case or VA.gov business case?
- [x] Same thing with the error key and text returned. Be clear if that text is what's returned in a VA Profile API or shown to a user on VA.gov
- [x] Follow up with VA Profile (Vet360) team for more updates to add to the spreadsheet
- [x] Test sample addresses provided by VA profile team to see what messages are prompted to the user.

- [x] Add Github document to house the sample addresses used in #1129

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_

**Comment by Justin-Pickett** [comment]
@clantosswett  please use this [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/sample-test-%20addresses.md) for adding addresses to this list.

**Comment by clantosswett** [comment]
Tagging @Kimberley2019 for awareness as well. Kimberley, see the above comment from Justin for where to add new addresses that veterans report can't be updated on their VA account profile. Thanks!

**Comment by lkoenigsberg** [comment]
@Justin-Pickett , thanks for sharing the [WIP matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/error-code-matrix.md) with me.  This is coming along nicely and here are some additional comments for consideration:

- Continue to flush out the experience/outcomes column, keeping it updated as changes to error msgs might happen through the course of the project
- Give some natural language explanation of what overridable vs. not overridable means
- Provide some details of who to contact if there are questions

I took a look at the sample address list and I think it's also worth adding some context to that page.  Why are those addresses important, samples of what?

All and all good progress!  Going to ask that @Samara-Strauss also have a look and provide feedback to further define when this ticket can be closed and/or new tickets opened to track continual progress.

**Comment by Samara-Strauss** [comment]
Agreed with @lkoenigsberg ' s feedback. We can consider the goal met for Sprint 10 and continue with implementing Lisa's feedback in Sprint 11.

**Comment by Justin-Pickett** [comment]
@lkoenigsberg  @Samara-Strauss  thanks for the feedback . I will continue building on to this matrix as we continue to uncover more information regarding the various errors related to address validation. I will continue to work with the VA Profile team as well on any critical error changes on their end as well. 

I will begin implementing more updates and revisions to the matrix throughout Sprint 11 coming up as well to the Veteran's sample addresses report log as well.
