### ISSUE TITLE
Create list of all benefits applications 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3893]
Create a list of all benefit applications and where they get address data from — note which are VA Profile (Vet360) and which are not.

## User Story: 

As a designer , I need to create a list of all benefit applications and where they get address data from and note which are VA Profile (Vet360) and which are not. 
  
## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Identify the forms that have an address component. - 3 hours

- [x] confirm  with Backend Eng what forms are running on VA Profile and being pre-filled from users profile. - 1 hour
 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [x] Have a comprehensive list of the forms on VA.gov and have an understanding on how they are being pre-filled. 

## Excel Github File 
- [x] Create list of VA benefit applications lists in Github  [Link to Github lists](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefits-applciations-list.md)

**Comment by Samara-Strauss** [comment]
Where are we with this ticket? I see that there is an excel file linked above, but it looks like there are items listed that don't have a URL or are not separate applications on VA.gov. We only need to concern ourselves with applications that currently live on VA.gov.

Also, can we save this list in the documents folder for this project? Otherwise, the documentation will get lost in this ticket https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/change-address/apo-fpo-dpo

**Comment by Justin-Pickett** [comment]
@artistgreen can you verify that this is ready to be closed. According to the spreadsheet, to my understanding we have accounted for the applications are live on VA.gov. Is this accurate. If so I think this ticket has been satisfied. 

I updated the GitHub link above to link to the repository.

**Comment by artistgreen** [comment]
https://staging.va.gov/records/download-va-letters/letters/confirm-address

**This uses the same component as the /profile mailing address editor, changes to this address will update to /profile and changes from /profile will update here.**

----------------------------
https://staging.va.gov/health-care/apply/application/veteran-information/personal-information
https://staging.va.gov/pension/application/527EZ/applicant/information
https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/burial-benefits

**These use the profile address**

-----------------------------
https://staging.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information

**This uses the profile address and EVSS PCIU address. Profile address has priority but if it's blank then PCIU address will be used.** 


For the forms that do get pre filled profile information, if the user changes their address in the form will that update in their profile?
No, except in the letters url above.

**Comment by artistgreen** [comment]
@Justin-Pickett - yes, we have gathered the list and this can be closed.  I'll update the Github ticket.

**Comment by Samara-Strauss** [comment]
Guys, come on, this is completely unacceptable.

1. That spreadsheet was not updated before it was uploaded. It still has rows for applications that are not on VA.gov (employment). Also, the section re: the disability application is super confusing — I can't tell what needs to be updated here and what does not. We just need to know what is being updated on VA.gov. I shouldn't have to ask for this kind of clarity.
2. Furthermore, I can't tell if [this list in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3893#issuecomment-564291349) is supposed to be the final list or not? If it is, it's different from the spreadsheet. What about the education applications? This is completely unclear and I can't tell what the team should be doing from here.
3. Finally, this spreadsheet was uploaded to the Github documents with a nonsense name. I should not have to do this level of hand-holding: if you upload a document, please make sure it has a descriptive name that tells other people what is in the file. If you update a file and re-upload it, make sure that it has the same name as the original uploaded file so that it replaces the original file instead of creating another file. Otherwise, we'll be left with a bunch of versions of something with no clarity on what is the most up-to-date source.

<img width="1279" alt="Screen Shot 2019-12-11 at 10 48 16 AM" src="https://user-images.githubusercontent.com/34068740/70638379-c80e8e00-1c06-11ea-9379-7b28ef583b78.png">

Please delete the current file and upload a finalized spreadsheet that only has the benefit applications that need to be updated. If you need to coordinate with each other, please do so instead of making assumptions about who should be doing what.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss  I will work with @artistgreen to make sure the corrections are made and the updated spreadsheet is uploaded.

**Comment by Samara-Strauss** [comment]
[Is this list complete](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefits-applciations-list.md)? Are there no education applications that need to be included in this list?

**Comment by Justin-Pickett** [comment]
@artistgreen  let me know when the final list is complete so we can get this closed out. Once you update this ticket, ill get the remaining items uploaded in the github link ---> [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefits-applciations-list.md)

**Comment by artistgreen** [comment]
Forms to add from Education:
22-0994
22-1995
22-1990
22-1990E
22-5495

Exploring these to see if they have an address component:

22-1995
22-5490


We identified pre-eligibility for burial form - adding this form:

21P-530

**Comment by Justin-Pickett** [comment]
@artistgreen thank you for uploading the final list of forms. I have uploaded them to the Github 
repo ----> [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefits-applciations-list.md) for reference. 

I will close this ticket. This sprint 10 objective was met.
