### ISSUE TITLE
Can we and should we move to a unified channel for communication?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#38946]
## Issue Description
Mike Chelen suggested example of team launching Test Console, and announcing it on GH Disc. as the source.  Thomas chimed in and pointed out that it adds another channel to an already considerable list.

**## Some discussion:**
MC:   would be good for the team to test using GH discussions as source of truth for platform announcements 
-and having the other existing comms channels point there as reference

Thomas:  I'm even fine migrating the currently used channels to the GH disc and replacing the old originals with pointers to the new place

**Counterpoint: why not make Slack the default unified comm channel?**
From VA platform orientation:

-A single source of truth, and one more located near the town square, seems preferable to additional channels.  Our team could explore this idea and consider updating the Comm playbook or a new unified Channel.

-Liani pointed to a now-archived channel : #platform-announce.  It was archived due to inactivity, but it may be time to reconsider.

![image.png](https://images.zenhubusercontent.com/610037824c513c8eae9f81c8/6917a038-b4ec-4922-877d-0bd9a47c1468)

-GH discussions is currently a largely unknown tool to Platform teams.  
-Slack is very well known by both Platform and VFS.  The weakness of Slack is that the scroll means announcements roll up and get missed:

Possible solutions: What if a Slackbot or something could collect announcements in some way and post them at a regular interval.  kind of like how i know the sunday paper comes on sunday if i need to find some news.

## Tasks
- [x] Evaluate whether to continue to utilize multiple channels or consolidate (informed by poll & interviews)
- [x] Evaluate where a single source would be be located, if chosen
- [x] Evaluate how best to message this change

## Acceptance Criteria
- [x] A path is chosen and included in workflow 

## Next Steps
Based on the Poll Results and related conversations w/ users:

- overwhelmingly in support of Slack as pathway
- considerable support for a unique "announcements only" channel
- zero votes for Github
        - commentary that they prefer that Github be reserved for actual discussion, and Slack be the source for finalized announcements
- we're seeing some ask for a curated space of sorts, looking for order and consistency.

We found there to be high interest in keeping announcements in Slack, and further interest in a new Announcements Only sort of channel.
- We could name it to reflect that it is for Change Announcemnents
- Users would be directed to post there only in the predetermined format from the Comm. Plan, keeping the format consistent and more easily scannable.
- Conversation would be limited to threads of the original posts only, limiting overall posts and a high level of scroll to get to items of interest.
