### ISSUE TITLE
[FE] Update Unit tests for Address Edit

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#38944]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Slack Thread](https://dsva.slack.com/archives/C02V265VCGH/p1647980519402159)
- [PR that skips the test]() 
## Description
> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

Platform identified 2 failing tests. These tests are failing sometimes. These tests should be updated to not fail. 

## Tasks
- [ ] Fix or update unit tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Tests are passing and merged into master

**Comment by brianseek** [comment]
Spent a bit of time trying to figure out what is going on here. When run in isolation locally, or on a PR build everything works just fine. When run with the same ordering (CHOMA_SEED=5Pb42QNlna) and commit hash locally, I can see some the issues reproduced and also failing tests from other apps.

I tried eliminating the testIds that used lodash camelcase to see if that was an issue. I also tried to mix up the var names of the mock store instances. None of those seemed to be the issue. 

I think it could be related to the useEffect in the component that sets the address fields. Dan is working on Address refactor and updates, so I am going to pause on this for now and see if the issues persist after the next iteration of Address edit.
