### ISSUE TITLE
[Combined Debt Portal] Convert the debt letter download table into a list 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38947]
## Issue Description
We received feedback during the Combined VA Debt Portal's design intent that we should reformat the VBA debt letter download table into an ordered list. This will make downloading letters more accessible, as navigating a table using assistive devices can be challenging. 

Feedback from Angela's office hours:
- Pull everything out of the table
- Headers can be different letter types 
- Include date + download link under headers 

---
## Tasks
- [x] Incorporate Angela's feedback into the redesigned debt letter download page
- [x] Sync with Angela as needed for additional feedback

## Acceptance Criteria
- [x] The design has been added to UXPin and linked in this ticket
- [x] A ticket for frontend implementation has been created, linked, and added to the epic

**Comment by rileyorr** [comment]
I've been playing around with some ideas for how to display the letters as a list rather than table, and think that it makes sense to list the letters in chronological order by date received rather than breaking them up by notification letter type. 

My thinking behind this is that although 'Third debt notifications' are the most urgent within a debt's lifecycle, we're pulling in all letters in the Veteran's VBMS file. As a result, we could potentially display 'Third debt notifications' from resolved debts first rather than active debts which are more urgent. Additionally, if a Veteran has many of one type of notification letter, it could bump a more recently sent letter lower on the page and potentially get lost. It's most likely that Veterans are looking for their most recently received letter when they access this page.

---

I'm going to  get feedback from Angela and the Monday design/research office hours on the following two designs: 

**Option 1: List with pagination**

![Screen Shot 2022-03-25 at 2.23.35 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/9968df3b-b044-42df-9ae8-1e41ad7e0302)

---

**Option 2: List with 'load more' button**

![Screen Shot 2022-03-25 at 2.23.47 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/7d81911a-ca78-4c5d-81ef-60def59499b8)

**Comment by rileyorr** [comment]
Received feedback during today's design/research office hours. Adding the feedback gathered from that meeting below:

- Load more button exists in the CST ([ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778))
- Expand number of letters initially displayed to 12 
- Load additional items and put focus on the first new item that loads
- Peter Russo (VAOS) is working on a 'load more' design for facilities
   -  Experimental design request ([ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/677))
- Header that says “Last 30 days of letters” or “Most recent 12 letters” 
- Button that acts as an accordion:
    - View older letters
    - Hide older letters
- Add content that letters from resolved debts can be downloaded here

**Comment by rileyorr** [comment]
Designs can be found in UXPin here:
- [Default displaying last 4 letters](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1cjwadz*_gcl_aw*R0NMLjE2NDMwMzc3MjYuQ2owS0NRaUF1Ym1QQmhDeUFSSXNBSldOcGlNMVo1NGR3LW9ZQnBONHktQTBuVHlyVW1MS3RscWZxRldaMmd1ZG0wcmFqSWp0OVl1NjZIQWFBc0NvRUFMd193Y0I.#/pages/149089100/simulate/no-panels?mode=i) 
   - [Expanded to show remaining letters ](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1cjwadz*_gcl_aw*R0NMLjE2NDMwMzc3MjYuQ2owS0NRaUF1Ym1QQmhDeUFSSXNBSldOcGlNMVo1NGR3LW9ZQnBONHktQTBuVHlyVW1MS3RscWZxRldaMmd1ZG0wcmFqSWp0OVl1NjZIQWFBc0NvRUFMd193Y0I.#/pages/149089099/simulate/no-panels?mode=i)

I referenced the design that's being implemented in the design system + CST. When I update the frontend ticket I'll link to both that design ticket and Robin's frontend ticket.

**Comment by rileyorr** [comment]
Updated [the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075) with links to the designs, an updated description, and links to tickets related to the new component we should use!
