### ISSUE TITLE
[Combined VA Debt Portal] 404 alerts for the VA debt overview page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38948]
## Issue Description
If the API calls for VHA copay bills or VBA debts returns a 404, we need to display a message on the frontend to alert Veterans and give them actionable next steps 

---
## Tasks
- [x] Create designs for the 3 following use cases:
   - [x] 404 **only** for VHA copay bills 
   - [x] 404 **only** for VBA debts
   - [x] 404 for **both** VHA copay bills and VBA debts 

## Acceptance Criteria
- [x] Designs have been added to UXPin and linked in this ticket
- [x] Ticket(s) for frontend implementation have been created, linked, and added to the epic

**Comment by rileyorr** [comment]
Designs have been added to UXPin: 
- [404 for both VHA and VBA API calls](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*ksqoid*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149503318/simulate/sitemap?mode=i)
- [404 for VBA API call](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*ksqoid*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149503317/simulate/sitemap?mode=i)
- [404 for VHA API call](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*ksqoid*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149503316/simulate/sitemap?mode=i)

@kevinstachura and I are going to meet tomorrow to review the 404s + empty states and finalize our direction

**Comment by rileyorr** [comment]
[Designs have been linked in the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)
