### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/va.gov-team#3894]
## User Story:
As a Front End Developer, I need to implement Google Analytics for our product's websites so that I can track stats about our users.

## Tasks
- [ ] Meet with GA team once websites are set up - 1 hour - Owner
- [ ] Implement GA scripts on websites - y hour(s) - Owner

## Acceptance Criteria:
- [ ] See user stats on Google Tag Manager

## Next Steps
- [ ] Meet with GA team once websites are set up

## Blockers

- Create product websites
- API has to be set up

**Comment by mr0sari0** [comment]
Adding @wygonikGCIO as a participant
