### ISSUE TITLE
Propose solution for how to handle military addresses in benefit applications that use VA Profile data.

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3895]
Propose solution for how to handle military addresses in benefit applications that use VA Profile data.

## User Story: 

As a designer, I need propose a solution for how to handle military addresses in benefit applications that use VA Profile data. 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Technical discovery - Identify which forms will be affected (forms with an address component) #3893

- [x] Design mock ups

- [x] Review with Benefits team

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] Design mock ups

- [ ] Review and approval from Benefits team

**Comment by Samara-Strauss** [comment]
Where are we with this? Also, this ticket needs to be groomed. There is still dummy data in the top issue.

**Comment by artistgreen** [comment]
I added tasks/acceptance criteria.  Finished mock ups - will update ticket shortly with screens.

**Comment by artistgreen** [comment]
We will use the same UX as proposed for editing mailing addresses on the user profile:

- display a checkbox option with label "I live on a United States military base outside of the United States'
- display a helper text drop-down
- disable 'Country' field and display United States within the field
- Change 'City' field label to read 'APO/FPO/DPO' and change input text box to a drop down with the options: APO, FPO and DPO
- Reduce 'State' field options to: AA (Armed Forces Americas), AE (Armed Forces Europe) and AP (Armed Forces Pacific)

**Comment by artistgreen** [comment]
We are using the health care application 10-10EZ form for the template for these mock ups.  All of the forms are in the same step workflow, full page layout.  The only forms that display in a modal are the user profile and address form in the 'Download VA benefit letters' workflow.

Assuming the user is logged in- 

**When the user arrives at the address page and they live on a domestic military base they will see this:**

![Form 10-10EZ - domestic military base address 1](https://user-images.githubusercontent.com/53535009/70589224-361e6b00-1b9d-11ea-9874-de3083136723.png)

Domestic military base addresses use the base name as the 'City' and follow the same pattern as a non-military address by displaying a state.

Same screen with helper text visible:

![Form 10-10EZ - domestic military base address 2](https://user-images.githubusercontent.com/53535009/70589253-43d3f080-1b9d-11ea-8caa-4ba59ba40c8b.png)

When the user arrives at the address page and they live on a US military base outside of the US they will see this:

![Form 10-10EZ - outside US military base address 1](https://user-images.githubusercontent.com/53535009/70589522-e68c6f00-1b9d-11ea-99a0-2c018607e958.png)

Same screen with helper text visible:

![Form 10-10EZ - outside US military base address 2](https://user-images.githubusercontent.com/53535009/70589553-fb690280-1b9d-11ea-8b4a-fb06a40a5b1e.png)

**Comment by artistgreen** [comment]
These step workflow forms have a review step that displays the form information in an accordion layout.

![Form 10-10EZ Review step - accordion closed](https://user-images.githubusercontent.com/53535009/70590330-5e5b9900-1ba0-11ea-8431-9ed9eafc6f1b.png)

When the user opens the Veteran Info section they will see this:

![Review step - accordion veteran info open](https://user-images.githubusercontent.com/53535009/70590365-7501f000-1ba0-11ea-85b7-287ad6fbdca2.png)

When the user clicks the 'Edit' button to edit their address they will see this layout:

![Form 10-10EZ - veteran info edit](https://user-images.githubusercontent.com/53535009/70590410-9fec4400-1ba0-11ea-8bd7-d05230371e74.png)

**Comment by Samara-Strauss** [comment]
This all looks good to me.

**Comment by Samara-Strauss** [comment]
Can I close this?

**Comment by Justin-Pickett** [comment]
@Samara-Strauss ill close it soon today, just going to use to break out the FE ticket that results from this proposed solution. Thank you.

**Comment by Samara-Strauss** [comment]
@Justin-Pickett sounds good. We'll consider this complete for sprint objective purposes. Close whenever you're ready.

**Comment by Justin-Pickett** [comment]
This ticket is ready to be closed. The above information will be moved to a "FE" ticket to prepare for build out of this proposed solution encompassed in this ticket.
