### ISSUE TITLE
[Combined Debt Portal] 404 alerts for VHA 'current copay bills' page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38966]
## Issue Description
If the API call for VBA debts returns a 404 on the 'Current debts' page, we need to display a message on the frontend to alert Veterans and give them actionable next steps

This could occur if the Veteran has the 'Current debts' page bookmarked and they access it while they're authenticated, or they access it from a copay-specific entry point on the site

---
## Tasks
- [x] Create a design with a 404 alert for the VHA 'Current copays' page

## Acceptance Criteria
- [x] Design has been added to UXPin and linked to this ticket
- [x] The epic has been updated with the new designs

**Comment by rileyorr** [comment]
Designs have been added to UXPin:
- [Both VBA and VHA APIs 404](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149423133/simulate/sitemap?mode=i)
- [Only VHA API 404s](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149423132/simulate/sitemap?mode=i)
- [Only VBA API 404s](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149423131/simulate/sitemap?mode=i)

**Comment by rileyorr** [comment]
[Designs have been linked in the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)
