### ISSUE TITLE
VA health connect number for VISN 2 and 17

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#38962]
## Issue Description
The VA health connect number needs to be displayed in search results for facilities in VISN 2 and 17. The number for VA health connect is VISN-specific and is the same for all facilities within the VISN. This number will be available via Lighthouse soon but in the meantime, it needs to be hardcoded. 

## Data from Lighthouse

```
{
  "data": [
    {
      "id": "vha_688",
      "type": "va_facilities",
      "attributes": {
        "lat": 38.9311137,
        "long": -77.0109110499999,
        "name": "Washington VA Medical Center",
        "visn": "20",
        "hours": {
          "friday": "9AM-5PM",
          "monday": "9AM-5PM",
          "sunday": "Closed",
          "tuesday": "9AM-5PM",
          "saturday": "Closed",
          "thursday": "9AM-5PM",
          "wednesday": "9AM-5PM"
        },
```

![image](https://user-images.githubusercontent.com/55411834/140570738-9e390350-e0f1-4600-a053-62c58bef4e58.png)

---
## Tasks
- [ ] Add "VA health connect" phone number to search results when facility type = VA health and VISN=2 or 17
- [ ] Add flipper to control this display

## Acceptance Criteria
When facility type = VA health and VISN= 2, search result cards will include 
- [ ] Main number: (phone)
- [ ] VA health connect: [TBD]
- [ ] Mental health: (phone)
When facility type = VA health and VISN= 17, search result cards will include 
- [ ] Main number: (phone)
- [ ] VA health connect: [TBD]
- [ ] Mental health: (phone)
Display of VA connect number can be toggled on/off
