### ISSUE TITLE
Research/Decision - API gateway software

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38968]
## Issue Description
Essentially an API gateway is just a specific revproxy for APIs, so if we are going to have an additional reverse proxy to build, we might want to use an API gateway instead of using a generic NGINX reverse proxy.

Research some different API gateway software packages, choose from the best ones we find, and compare them with NGINX and each other.

Write up an ADR to describe this process and what our thought process was for the direction we are going.

Questions to consider:
- Do we just duplicate the existing revproxy? What are the pros/cons here?

Possible API gateway software:
- AWS API Gateway
- Tyk
- Kong
- KrakenD
- Others?

---
## Tasks
- [ ] Decide if it would be technically feasible given our research outcomes to use only an ALB with routing to send traffic to vets-api (This will depend on if we need to rewrite or mangle/tweak incoming traffic)
- [ ] If the above is not possible, evaluate a generic reverse proxy and the features it offers against an API gateway specific software package. Refer to RFC comments to inform this decision
- [ ] Generate an Architectural Decision Record to document the decision we make

##Suggestions/Links:
- [] https://hackernoon.com/why-we-switched-from-nginx-is-to-kong-api-gateway
- [] The good part with kong is that, it is built on Nginx. Meaning it already has Nginx functionalities

## Acceptance Criteria
- [ ] Decision is made and documented in an ADR

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
May be needed based on outcome from:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39713

**Comment by alwerner** [comment]
Decided to use Traefik rather than a new API gateway.
