### ISSUE TITLE
Design - Auth Profile - Personal Info Revision - Complete Contact Center Documentation

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38961]
## Background

Once all the UI changes have been updated in mockups and/or FE so that new screen shots can be taken, update the Contact Center documentation to include info the personal info page being split into two pages (personal and contact) and the addition of the new fields.   The latest draft of the Contact Center documentation is linked [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/).  I turned Track Changes off because pretty much the whole doc changed, and it was difficult to read and format.

I have updated all content and screen shots ~**through page 59**~ (**Samara's note: I made a bunch of changes which changed the page number Marci left of on**), which encompasses all the updates to Personal Information and Contact Information.   Beyond that, the main thing that needs to be updated are screen shots so they reflect the current masthead.  ~@SKasimow - just to be safe, I've also uploaded the draft document to [GCIO Sharepoint](https://salientcrgt.sharepoint.com/:w:/s/VSATeam/EQSo_5PsZ55Dk9hdogiXIFUBygfuxVpKFKSJ5QYuopW4TA?e=lvL3gp).~ **Samara's note: @SKasimow -- Don't use the version on the GCIO Sharepoint. I made significant changes to the guide. Please use the version linked on GitHub**.

There is a link on [this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/product-guides.md) that will also need to be updated to denote when the doc is submitted to the Contact Center.

## Tasks
- [x]  Complete Contact Center Documentation
- [x] Review with PO
- [ ] Submit to Contact Center
- [ ] Update [Product Guide page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/product-guides.md) to note date submitted to Contact Center

## Acceptance Criteria
- [x]  Complete Contact Center Documentation
- [x] Review with PO
- [ ] Submit to Contact Center
- [ ] Update [Product Guide page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/product-guides.md) to note date submitted to Contact Center

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss @SKasimow @cgednalske - I updated the description above to note where the draft doc is located, and everything that I updated.

**Comment by MarciMcGuireGCIO** [comment]
Noting that I am going to keep making updates today and will update the description accordingly.

**Comment by MarciMcGuireGCIO** [comment]
@Samara-Strauss @SKasimow @cgednalske 
Last update -- I removed a duplicate, but empty **Military Info** section and updated the headings in the other one to get it to appear in the Table of Contents.  

Screen shots & instructions from page 59 forward should still be reviewed and the TOC re-updated after all changes are made.  Draft has been uploaded to the links provided in the Description above, which are still valid.

**Comment by Samara-Strauss** [comment]
Thanks, Marci!

**Comment by cgednalske** [comment]
🎉 Thank you, @MarciMcGuireGCIO!

**Comment by Samara-Strauss** [comment]
@cgednalske @SKasimow I'm gonna go through and make some edits for the profile guide before I have you all start working on it. I've already started -- most of the edits are small wording changes -- but there is also some redundancy in the guide as a whole that I don't think we need, so I'm going to clean that up. I'll re-post the guide here once I'm done.

**Comment by Samara-Strauss** [comment]
@cgednalske @SKasimow I've made significant changes to the profile guide overall and replaced the version Marci put on GitHub with my version that includes all the edits. [You can download the latest version here to continue working](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/VA.Profile.Product.Guide.version.5.04062022.docx). @cgednalske -- I think the only thing the guide needs now is A LOT of updated screenshots. I've made a comment on all the screenshots that need to be replaced, but if you see any others that you think look sloppy, please feel free to update them so they look cleaner. Let me know if you have any questions! Otherwise, just let me know when you've updated the screenshots and are ready for me to review the guide again. Thanks!

**Comment by cgednalske** [comment]
@Samara-Strauss sounds great! I'll take a look and let you know if I have questions, but it sounds pretty straightforward with the screenshots. Thank you!

**Comment by cgednalske** [comment]
I've updated most everything in our Google doc, but there are some screens I won't be able to confirm and replicate until I can check with Adam/Mark or Liz. And there are a few sections where I'll need to fix the mockups in Sketch to replicate some views and get the screenshots we need.

Beyond this doc, also noting that there are a few areas that need the Sketch files updated to match the latest designs, so I might need to set up some tickets for those at some point. I was still able get screenshots from staging for most of them though, so other than Account security I don't think they're needed for this. 

This is all noted in more detail in the document comments, but here's an idea of what will need some attention:
- _For document_ - Direct deposit error messages - can Adam or Mark check the code to see the exact design and copy?
- _For document_ - Military information - what copy should go in the error alerts?
- _For document_ - Check with Liz for Direct deposit information edit state - update Sketch mockups
- _Additional work_ - Update Address validation in Sketch files (leaving as is for now in the documentation)
- _Additional work_ - Update Account security screens - we have more states for mobile, but most are missing for desktop

**Comment by Samara-Strauss** [comment]
Thanks for all your hard work, @cgednalske. When you get back from your time off, the contact center guide is your top priority to finish. Do whatever you need to do to get the screenshots updated. It looks like only a small handful of things that are outstanding now.

To check copy, yes, Adam or Mark can check the code on the items that we are not able to replicate on staging.

For updating files in general, can you work with @SKasimow to get tickets created to do that and put them in the backlog? Of course, update files now for anything that you need for the contact center guide, but you don't have to update everything immediately if the screens aren't needed for the contact center guide.

**Comment by SKasimow** [comment]
Just a reminder that @Samara-Strauss asked that we hold off on submitting this to the Call Center until we have @andaleliz updates related to direct deposit. 

+ @cgednalske

**Comment by Samara-Strauss** [comment]
To be clear, it is **@cgednalske's top priority when she is back to finish cleaning up the final screen shots for the guide**. I'm just saying we can hold off on submitting the ticket for review from the call center folks until @andaleliz makes the updates related to the direct deposit work that she is starting in the upcoming sprint. **However**, this also assume that @andaleliz is able to make updates to the guide relatively quickly. If those updates aren't ready for a few weeks, we'll probably want to go ahead and submit the guide sooner. Let's me in touch about this, and let me know if you have questions.

**Comment by andaleliz** [comment]
Oh, I didn't realize you'd wait to submit Christina's updates until mine were done. That makes sense, I'm sure it's a lot of effort for the call center team to review the guide. 

I would be surprised if this takes a few weeks but I'll keep everyone posted.

**Comment by Samara-Strauss** [comment]
@andaleliz since @SKasimow has ["Update contact center guide" under your to-dos for next sprint for the direct deposit work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39933), I didn't want us to submit the call center guide this week for personal information revisions only to resubmit it in a sprint or two with new direct deposit updates. However, if we think it would be 3+ sprints until your direct deposit work was ready for the guide, I wouldn't want to wait that long to submit the call center guide for review. So just keep us posted on when you think that work might happen so we can plan accordingly.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow - I've made all updates to the doc except for one screenshot Adam is going to try and grab for me on Monday for a Direct Deposit error alert. If he's not able to replicate it quickly, I will let Liz know so we can determine if one of us can mock it up quickly now or if it fits into the work she is doing for DD (don't want to step on her toes for that).

**Comment by Samara-Strauss** [comment]
Great, thank you, @cgednalske!! Once the final screenshot is in there, we can call your work on this DONE, and we'll update the direct deposit screenshots further as necessary throughout Liz's work.

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow Dare I say it - but I think all updates have been made on my end! 🎉  Let me know if there is anything else, but looks like we've wrapped up all changes.

**Comment by Samara-Strauss** [comment]
YAY! Thank you so much for all your hard work, @cgednalske. The document can hang out until Liz is able to add the direct deposit updates. Otherwise, I think this ticket is safe to close.

**Comment by SKasimow** [comment]
Great job @cgednalske - I know that took quite a bit of work on your part!
