### ISSUE TITLE
[Combined Debt Portal] 404 alerts for VBA 'current debts' page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38960]
## Issue Description
If the API call for VBA debts returns a 404 on the 'Current debts' page, we need to display a message on the frontend to alert Veterans and give them actionable next steps

This could occur if the Veteran has the 'Current debts' page bookmarked and they access it while they're authenticated, or they access it from a debt-specific entry point on the site 

---
## Tasks
- [x] Create a design with a 404 alert for the VBA 'Current debts' page

## Acceptance Criteria
- [x] Design has been added to UXPin and linked to this ticket
- [x] Ticket for frontend implementation has been created, linked, and added to the epic

**Comment by rileyorr** [comment]
Designs added to UXPin:
- [Both APIs return 404](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1u3g4g6*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149376500/simulate/sitemap?mode=i)
- [VBA API returns 404](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1u3g4g6*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149376499/simulate/sitemap?mode=i)
- [VHA API returns 404](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1u3g4g6*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149376498/simulate/sitemap?mode=i)

**Comment by rileyorr** [comment]
[Designs have been linked in the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)
