### ISSUE TITLE
[Combined Debt Portal] Empty state for 'current debt' page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38975]
## Issue Description
If the API call for VBA debts returns null then we need to provide an empty state on the frontend to notify Veterans

This could occur if the Veteran has the 'Current debts' page bookmarked and they access it while they're authenticated, or they access it from a debt-specific entry point on the site

---
## Tasks
- [x] Create a design with an empty state for the following use cases:
   - [x] API call for VHA copay bills returns null
   - [x] API call for VHA copay bills returns copay bill(s)

## Acceptance Criteria
- [x] The designs have been added to UXPin and linked in this ticket
- [x] Ticket(s) for frontend implementation has been created, linked, and added to the epic

**Comment by rileyorr** [comment]
Designs have been added to UXPin:
- [Empty state with copays available](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149482102/simulate/no-panels?mode=i)
- [Empty state with no copays](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149482101/simulate/no-panels?mode=i)

**Comment by rileyorr** [comment]
[Designs have been linked in the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)
