### ISSUE TITLE
Gather necessary AWS Security Group Information

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#38973]
## Issue Description
VBS is putting further security requirements to accept traffic by AWS security groups. We should either hand over the information of the va.gov security groups and account or they can restrict via CIDR blocks

---
## Tasks
- [ ] Connect with platform to discuss security group vs CIDR blocks
- [ ] Pass over the information

## Acceptance Criteria
- [ ] VBS has what they need to fulfill security requirements
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
