### ISSUE TITLE
Create an RFC to determine an internal .vfs.va.gov domain name for the separated vets-api API

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38971]
## Issue Description
In order to work in parallel with the existing system, we will need to bring up our own internally accessible URL in the .vfs.va.gov subdomain so we can test and build the separate vets-api routing. It needs a name. We should consult the product owner and the existing teams to discuss what name we should use, as it will be difficult to change it moving forward.

---
## Tasks
- [x] Create RFC with some suggestions and ideas

## Acceptance Criteria
- [x] RFC is posted in the appropriate place

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
RFC created: https://github.com/department-of-veterans-affairs/va.gov-team/discussions/39068

**Comment by dginther** [comment]
Demian to edit RFC with a more concrete and opinionated plan

**Comment by dginther** [comment]
RFC edited, closing ticket
