### ISSUE TITLE
BE - Auth Profile - Knowledge Transfer

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#38979]
## Background

Lihan is transitioning to the 1010 team.  Meet with him to discuss and understand any existing/past work that needs to be taken over.

## Tasks
- [x] Review Profile Monitoring and Troubleshooting Procedures 
  - [x] Walkthrough monitoring and troubleshooting performance issues.
  - [x] Walkthrough monitoring and troubleshooting application and service errors (including viewing application logs).
  - [x] Identity appropriate groups/channels to notify for different types of issues.
- [x] Review Onsite Notifications
  - [x] Identify supporting code
  - [x] Identify supporting configuration
- [x] Review Contact Feature

## Acceptance Criteria
- [x] Document Profile Monitoring and Troubleshooting Procedures 
  - [x] Document and standardize basic steps for monitoring and troubleshooting performance issues.
  - [x] Document and standardize basic steps for monitoring and troubleshooting application and service errors (including viewing application logs).
  - [x] Document appropriate groups/channels to notify for different types of issues.
- [x] Basic understanding of Onsite Notifications code and configuration
- [x] Understanding of Contact Information feature

**Comment by Samara-Strauss** [comment]
Looks good to me!

**Comment by MarciMcGuireGCIO** [comment]
Agree with @Samara-Strauss, @tpharrison !

**Comment by tpharrison** [comment]
@Samara-Strauss This ticket outlines the work I reviewed with Lihan.  The two major areas we reviewed were onsite notifications and application monitoring.  If you can think of any other important areas to review before Lihan transitions, please let me know.  Thanks!

**Comment by Samara-Strauss** [comment]
Thanks, @tpharrison! You should also talk to Lihan about what you should know re: contact information and direct deposit. Those are the two biggest products in the profile, so we'll need you to be able to manage those things in the event that something goes wrong.

**Comment by tpharrison** [comment]
Thanks @Samara-Strauss!  - I'll meet with Lihan to review these features.
