### ISSUE TITLE
[Combined Debt Portal] Empty states for VA debt overview page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38974]
## Issue Description
If the API calls for VHA copay bills, VBA debts, or both returns null then we need to provide an empty state on the frontend to notify Veterans 

---
## Tasks
- [x] Create designs for the following use cases:
   - [x] Empty state **only** for VHA copay bills
    - [x] Empty state **only** for VBA debts
    - [x] Empty state for both VHA copay bills and VBA debts

## Acceptance Criteria
- [x] Designs have been added to UXPin and linked in this ticket 
- [x] A ticket for frontend implementation has been created, linked, and added to the epic

**Comment by rileyorr** [comment]
Created a first pass at the empty states. Going to chat with @kevinstachura when we collaborate later this week after our VA onboarding is taken care of. Here's the designs: 
- [Empty state for only VHA copays](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149492808/simulate/sitemap?mode=i)
- [Empty state for only VBA debts](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149492807/simulate/no-panels?mode=i)
- [Empty state for both](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1tlqwjy*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149492806/simulate/no-panels?mode=i)

**Comment by rileyorr** [comment]
[Designs have been linked in the epic](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)
