### ISSUE TITLE
[Combined Debt Portal] Empty state for 'current copay bills' page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#38976]
## Issue Description
If the API call for VHA copay bills returns null then we need to provide an empty state on the frontend to notify Veterans

This could occur if the Veteran has the 'Current copay bills' page bookmarked and they access it while they're authenticated, or they access it from a copay-specific entry point on the site

---
## Tasks
- [x] Create a design with an empty state for the following use cases:
   - [x] API call for VBA debts returns null
   - [x] API call for VBA debts returns debt(s)

## Acceptance Criteria
- [x] The designs have been added to UXPin and linked in this ticket
- [x] The designs have been added to the epic

**Comment by rileyorr** [comment]
Designs have been added to UXPin:
- [If the API call for VBA debts returns null](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*16hlo1j*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149285598/simulate/sitemap?mode=i)
- [If the API call for VBA debts returns debt(s)](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*16hlo1j*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149285599/simulate/sitemap?mode=i)
