### ISSUE TITLE
Request WASA scan of new API URL

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38978]
## Issue Description
Once we have brought up, tested, and verified that our routing solution is working as we expect, and we are ready to get a public URL for it, we will need to get a WASA scan of the internal URL, as a pre-requisite to requesting an external URL/DNS entry from the VA.

Documentation for entire process: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

---
## Tasks
- [x] Request WASA scan of internal URL

## Acceptance Criteria
- [x] WASA scan scheduled.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
@madebydna We can repurpose this ticket. Feel free to change as needed.

**Comment by alwerner** [comment]
Added to pipeline. Closing as complete.
