### ISSUE TITLE
Design - Auth Profile - Address Change Messaging- Design for swappable modal

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38988]
## Background

There is an edge case where a Veteran does not have a mailing address stored in their VA.gov Profile. If they update their home address, we would like the modal to be smart enough to display a slightly different message from what is shown below when the mailing address is null/empty.  Currently, the code is not written to allow that text to be conditional. 

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/9c52992d-727d-47b2-8a12-fda4fb01de9f) 

## Tasks
- [x] Create mockup that shows what the language would look like in both scenarios
- [x] Review content with Danielle
- [ ] Update PM when mockup is updated

## Acceptance Criteria
- [x] Create mockup that shows what the language would look like in both scenarios
- [x] Review content with Danielle
- [x] Update PM when mockup is updated

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
Link to desktop mockup:  https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/25K3vb5

**Comment by cgednalske** [comment]
@MarciMcGuireGCIO Here is the link to [mobile mockup](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/09Vb1eV) as well!

**Comment by MarciMcGuireGCIO** [comment]
Thank you @cgednalske !
