### ISSUE TITLE
[SW-Content] Copy Edit and Publish R&S article Check in w/ phone for appointments [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38985]
## Story
We need to copy edit and publish a new R&S article about the new check-in experience. Once the article is copyedited, we need to wait for the go-ahead to publish. 

Article to copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=44490

## Tasks
- [x] Copyedit article (Randi)
- [x] Make final revisions (Danielle)
- [x] Final copy edit with pre-publishing checklist (Megan)
- [x] Publish (Megan)

## Acceptance criteria
- [x] New R&S article is live on the site

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht! I've made the needed update and this is ready for final copy editing: https://prod.cms.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments. I also wonder if we can try to make the image of the poster small? It's super big compared to the other images.

Could we copy edit and publish tomorrow, 5/5? Let me know if you have questions or concerns!

**Comment by DanielleThierryUSDSVA** [comment]
One more note: The second image has a yellow box around the field. I'll try to get another image for that so we can update, but that's not critical for tomorrow's launch.

**Comment by RLHecht** [comment]
This page is live. Closing ticket.
