### ISSUE TITLE
[Design] My VA - Copays: Exploration around showing debt/copay amounts

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38984]
## Background
In an effort to provide details to Veterans based on feedback received during previous research sessions, we want to explore ideas on how we could include debt and/or copay amounts.

This new design would replace our current in-line alert with # of debts and a Manage your VA debt link.

## Tasks
- [x] Review Payment info research for findings from Veterans interviews
- [x] Outline thoughts, ideas and/or lo-fi mockups to show additional debt and copay details
- [x] Share with the team

## Acceptance Criteria
- Thoughts are shared on how we might add a bit of detail to the debts and copays part of the payment info section on My VA.

**Comment by hdjustice** [comment]
Incomplete in Sprint 70- 1st exploration and discussion held, however there are further avenues we want to explore and keep it all in the same ticket - carrying over to sprint 71

**Comment by aagosto90** [comment]
Confirmed in #vsa-debt Slack channel that we can pull the facility name for copay details, but it may have to be in all caps. Their team opened a [ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39954) to look into that issue and see if they can match formatting to the facility ID.

**Comment by aagosto90** [comment]
Going to close this ticket as we've iterated on it internally enough to enter the collab cycle, but I have a recommendation to share with you all that came out of a collab meeting with other debts and copay folks that I'm excited about! I will share it during our sprint/retro meeting today afterwards if we have time, and if not I'll schedule a touchbase for us. @Samara-Strauss @ajakabcin
