### ISSUE TITLE
Relocate UXPin Files

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38987]
## Background
Due to a licensing quirk, many UXPin prototypes were built outside the VSA workspace. The prototypes need to be relocated so future teams will have access. 

### Tasks
- [x] Move COE
- [x] Move Find/Appoint Rep
- [x] Move PCPG
- [x] Move View/Change Rep
- [x] Move DD-EDU
- [x] Move CH31
- [x] Move CH36
- [x] Move Payment History

### Acceptance criteria
- [x] All UXPin prototype files are moved to the VSA UXPin workspace

**Comment by sporeboy** [comment]
All UXPin prototype files have been relocated!
