### ISSUE TITLE
Request new External URL from VA

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#38994]
## Issue Description
Once we have a completed WASA scan of our new internal URL, we will want to get a new External DNS/URL for it from the VA. The process is outlined here: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

---
## Tasks
- [ ] Complete the process outlined in https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

## Acceptance Criteria
- [ ] External URL has been granted by the VA ESECC

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Closing as a duplicate of https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/41515.
