### ISSUE TITLE
Adjust Document Uploader to Not Required

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38992]
## Background
Adjust the COE form so that docs are no longer required in order to submit

## Considerations
Per Kelli (3/23)

## Tasks
- [ ] Adjust the COE form so that docs are no longer required in order to submit

## Acceptance Criteria
- [ ] Form is adjusted
- [ ] A PR has been requested for merging, if needed
