### ISSUE TITLE
Reorder Document Sort Order (Latest at Top)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#38993]
## Background
The document list that is returned from LGY has the documents sorted by id.  In our prototypes, they are sorted by date, with the most recent on top, which allows the veteran to access their most recent information at the top of the list.

## Tasks
- [x] Add sorting by date to the documents call
- [ ] Adjust spec accordingly

## Acceptance Criteria
- [ ] A PR has been requested for merging, if needed
