### ISSUE TITLE
Sprint 10 Objectives 12/4- 12/17

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3899]
### Direct deposit

Goal: Ramp up direct deposit
- [x] Launch direct deposit to 75% and monitor for problems #3964 
- [x] Design and copy for the content page #2903
- [x] Investigate why "flagged for fraud" error rate is so high 
  - [x] #3966 
  - [x] #3981 
  - [x] #3982 
  - [x] #4097
- [x] Get on eBenefits schedule to remove direct deposit from the site in 1/29 release #3967
- [x] Call center guide updates #4002
- [x] Analytics: Answer follow-up questions #3877
- [x] Stretch goal: Launch to 100% if we have no concerns in doing so. **Note: It is OK if this does not happen in Sprint 10  due to legitimate concerns that push things into Sprint 11 instead. We will still consider sprint goals met with ramp up to 75% if the reason we are not ramping up to 100% is because of problems that arise from ramp up to 75%.** #3969
- ~DS logon gate:~ 
  - ~Design and copy for the profile #3763~
  - ~Start frontend setup for profile (final design implementation set for sprint 11) #3900~

### Address validation

 - User testing updates 
   - [x] Copy #3741
   - [x] Frontend implementation #3890
- Bad Unit number
    - [x] Finish design/copy #3660
    - [x] Frontend implementation #3891
- QA (This ticket will be created in Sprint 10, QA will happen in Sprint 11) #3948    
  - [x] Fill out Tze's QA intake form 
  - [ ] Have Tze complete the test plan
- Error Matrix #3892
  - [x] Updates   
  - [x] Follow up with VA Profile (Vet360) team
  - [x] Create a GitHub version of the spreadsheet
  - [x] Add sample addresses to the Github for Chante. 
- APO/FPO/DPO
  - [x] Finalize copy for the profile #3023
  - [x] Create a list of all benefit applications and where they get address data from — note which are VA Profile (Vet360) and which are not. #3893
  - [x] Propose solution for how to handle military addresses in benefit applications that use VA Profile data.#3895

### Monitoring, maintenance, bug fixes, hardening, 508, etc.

No tickets yet

### Additional to-dos post-sprint planning that may or may not get done in Sprint 10

These were not part of the original goals:

Prepare for onboarding new Designer 
- [x] Ticket created for tracking onboarding checklist items for Tressa #4086
- [x] Copy for routing number error #4105

## Capacity 

Brad out 12/13-12/18

![Screen Shot 2019-12-04 at 3.25.47 PM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/5b1c0f72-2226-44e0-b00a-f13ac808b086)

**Comment by Samara-Strauss** [comment]
Sorry, didn't meant to close this issue! Clicked the wrong button. Reopened!
