### ISSUE TITLE
Update documents as part of Sitewide Content and IA team transition

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#39008]
## Issue Description
When the current VSA contract ends on April 7, we need to ensure that other teams and stakeholders know who to reach out to for content support. There are a few documents where we will need to update team member names and points of contact.

## Tasks
- [x] In the [Sitewide Content and IA intake request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md), change Stan's name to Beth's in this section: Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner. (Randi)
- [x] Update team members in [team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/charter.md) (Randi)
- [x] Update content team point of contact in [process for stakeholder requests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/Content-updates-Drupal-editorial-process-032521.docx) (Randi)

## Acceptance Criteria
- [x] All team documentation has new points of contact and updated information

**Comment by RLHecht** [comment]
@bethpottsVADEPO I've updated the POC for the our intake request and put your name in there.

**Comment by RLHecht** [comment]
@bethpottsVADEPO  I updated our documentation for our stakeholder request process to add Laura's name along with mine. I will add it back to the GH folder but should this be emailed out to stakeholders? If so, do you have a list I should send it to?

Here it is if you want to review:[https://app.zenhub.com/files/133843125/2381ab01-c9d3-4fb7-8d90-5551ada2b91b/download](https://app.zenhub.com/files/133843125/2381ab01-c9d3-4fb7-8d90-5551ada2b91b/download)

**Comment by RLHecht** [comment]
closing as completed
