### ISSUE TITLE
[Combined Debt Portal] Set up the transition between design > development

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#39006]
## Issue Description
As development for the Combined Debt Portal ramps up, design needs to set up documentation for the transition from design to development.

---
## Tasks
- [x] Set up an epic containing the available tickets and outstanding use cases to be covered by design 
- [x] Add comments + link interactions to UXPin screens as needed

## Acceptance Criteria
- [x] The epic has been linked to this ticket

**Comment by rileyorr** [comment]
I just chatted with Andrew and he said he and Brandyn are comfortable drafting the frontend tickets based off the epic I make. As a result, I removed the task of drafting all the frontend tickets and lowered the estimate to a 3.

**Comment by rileyorr** [comment]
@denisecoveyduc, @Dr-Pongo, and @OptionSelect [here's the epic's skeleton](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/39075)! This epic only captures UI-related work, so I'm sure there are other frontend tickets related to the combined portal that I didn't include. 

It may look like a long checklist, but once we have the main chunks built out adding things like empty states and 404's will **hopefully** be straightforward. I'll set up time on Tuesday (March 29th) so we can go through it together and I can answer any questions.
