### ISSUE TITLE
Create (or get created) a 'Space' in Confluence for the CIT team

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39019]
## Issue Description
CIT Team needs a Space in Confluence to store team charter, documentation and meeting notes

---
## Tasks
- [x] Figure out how to get a space created and make request

## Acceptance Criteria
- [x] Space in Confluence is created and all team members and PO have write access to it.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
Confluence space is created. https://vfs.atlassian.net/wiki/spaces/PST4/overview
