### ISSUE TITLE
[FE] Make text in all components translatable

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39011]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

We have a [work in progress PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20576) to make all text in day-of and pre-checkin translatable - it should be updated to be mergeable and merged to prevent additional effort keeping it up to date, and make sure we're capturing all UI text for translation.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
