### ISSUE TITLE
[FE] submit PR to allow translating “Required” marker on VA text input design system component

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39012]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

The [va-text-input](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default) component allows marking a field as required, but only shows the "*Required" text marker in English. We should create & submit a PR to allow passing in the text to use as the required marker, so that it can be shown in translation.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Created [PR in the design system](https://github.com/department-of-veterans-affairs/component-library/pull/337) and [support ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/680)

**Comment by acrollet** [comment]
Descoped as the DS team will implement.
