### ISSUE TITLE
Research - Authentication issues

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39027]
## Issue Description

There are many commonalities and differences in how va.gov and Lighthouse handle federated authentication using multiple Identity Providers (IPs). There are also some areas of overlap that might need to be considered when separating out the routing to vets-api from Lighthouse APIs.

The [Explainer doc](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap) mentions the following:

1. Review the incidental dependency of some non-vets-api Lighthouse APIs to perform **OAuth token validation** via an internal endpoint in vets-api. This might be deprecated.

2. Lighthouse uses the user profile page on the va.gov website to allow users to manage the OAuth applications they've granted access to. vets-api uses **Okta API integration** under the hood to perform these CRUD operations.

3.  va.gov, being a web application, mostly uses **cookie-based authentications with a session token**, while Lighthouse serves many internal and external API users and utilizes a combination of **OAuth/Open ID Connect** to authenticate users and system-system approaches like **API keys** or the **client credential grant OAuth flow**. One ramification of this difference is that when VA.gov tries to consume an OAuth-based Lighthouse API as an upstream dependency we need to fall back to system-system auth, which goes against zero trust goals. This is because of the absence of shared tokens and the inability to exchange tokens between the systems.

---
## Tasks
- [x] Review and document OAuth token validation dependency of Lighthouse on vets-api and determine if 
  - new architecture would still allow access
  - it is deprecated and should be removed
- [ ] Review and document if Lighthouse's use of VA.gov user profile page would be maintained under new architecture
- [ ] Review and document if system-system auth of vets-api to Lighthouse API in cases of Lighthouse API being an upstream dependency could be maintained under the new architecture

## Acceptance Criteria
- [ ] Documentation of research outcomes to ensure that authentication/authorization flow will not be disrupted with the new, separate routing architecture
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
Lighthouse team stated that Oauth Proxy and SAML Proxy will still be necessary in the future configuration, but they have no plan to move them from the dsvagovcloud AWS account. This may need a plan for who will manage and/or own these applications moving forward.

We may also need to decide how the routing to these applications will work. It sounded like the Lighthouse plan was to route to these via the *api.va.gov URL, through Apigee, out to the dvp-gov-internal account, and then to the dsvagovcloud account. We should verify this and see if we can optimize this more.

**Comment by madebydna** [comment]
The Lighthouse team specifically mentioned plans to remove the incidental dependency on vets-api for OAuth token validation and migrate that functionality to be under their own control. 

@patrickvinograd, please let us know any insights you might have into authentication flows, or any risks you can identify in that area.

**Comment by madebydna** [comment]
Just wanted to link @patrickvinograd's [document on authentication variations](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2146402532/Explainer+-+Authentication+Variations) for reference here.

Some upfront thoughts I had:

If I understand the doc correctly, the OAuth and Same proxies are exclusively used in the Lighthouse context (authenticating 3rd party applications using LH). Given that, it would make sense to migrate those proxies into an environment that is controlled by LH, which, in this case, would be the `dvp-gov-internal` AWS account. Currently, the revproxy is used to route requests to those proxies. To determine the feasibility of a move, we'd need to compare and contrast:
- LH authentication request flows where proxies remain in the `dsvagovcloud` account
- LH authentication request flows where proxies are migrated into the `dvp-gov-internal` account

Generally, to confirm that authentication/authorization for va.gov and mobile apps is not disrupted, we need to trace and test the following scenarios:
- Unauthenticated website/mobile request with LH API as upstream dependency 
- Unauthenticated website/mobile request with no dependency on LH 
- Authenticated website/mobile request in cases where LH API is upstream dependency
- Authenticated website/mobile request when there is no LH API dependency

**Comment by alwerner** [comment]
Closing as outdated.
