### ISSUE TITLE
Adjust Confirmation Copy for Dependency Claims

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#39026]
## Background
Currently there is copy on the confirmation screen for Dependency Claims that a Veteran can view their application status in MyVA instead of the Claim Status Tool

## Considerations
This content was geared towards an older initiative; it seems as should have been pointed towards the CST.

## Tasks
- [x] Adjust copy in the prototype/mockups
- [ ] Ask FE to adjust the copy

## Acceptance Criteria
- [x] Mockups are updated

**Comment by sporeboy** [comment]
The third section of the subway map on the 686 confirmation page has bee re-written to direct users to the claim status tool: [(Link to XD mockup)](https://xd.adobe.com/view/88794e80-ae26-4f3e-509e-94d09eb571f7-fe48/screen/85157fc6-68fe-4a6b-bc76-b499c56283af/)

**Comment by jason-gcio** [comment]
Thanks @sporeboy - do we have the links as well or can we add them?  Should just be https://www.va.gov/claim-or-appeal-status/ right?

**Comment by sporeboy** [comment]
The "Check your VA claim or appeal status" link in the text goes here: https://www.va.gov/claim-or-appeal-status/

**Comment by jason-gcio** [comment]
We'll wait and see if FE has the capacity to do this before we ask them.
