### ISSUE TITLE
Create RFC for ALB / API Gateway / Nginx decision making

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39028]
## Issue Description
We will need to create an RFC for asking other teams and stakeholders to give us their thoughts about whether we will be able to use just an ALB or an ALB + Nginx or an ALB + API Gateway, and then depending on the outcome of that, we may need to decide what API gateway software to use.

---
## Tasks
- [x] Create RFC

## Acceptance Criteria
- [x] RFC for this conversation is created in Github Conversations

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
RFC created: https://github.com/department-of-veterans-affairs/va.gov-team/discussions/39115
