### ISSUE TITLE
Adjust Email Notifications 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#39021]
## Background
In testing, it was helpful to have some notification emails sent to the team for visibility and resolution

## Considerations
- Dependency Claims email for this: VACOOfficeofAutomatedBenefitsDelivery@va.gov
- VR&E does have a shared email inbox for this type of thing already in place so we can just remove ours.

## Tasks
- [x] Remove any team email addresses
- [x] Share a link or instructions in this ticket in case they need to be adjusted in the future.

## Acceptance Criteria
- [x] Emails are removed
- [x] A PR has been requested for merging, if needed
