### ISSUE TITLE
Research - Document Kong Gateway configuration

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39023]
## Issue Description
Requests to the lighthouse API are routed through a Kong API gateway (and sometimes that routes requests back to vets-api. The configuration for these request routings are in the Kong configuration.

Possibly the lighthouse teams may have this documentation already, so if so, we can just link to that.

---
## Tasks
- [x] Investigate where the Kong configuration lives
- [x] Document routing from those configuration files in this ticket (and then move to Confluence)

## Acceptance Criteria
- [x] Documentation for Kong configuration is in this ticket or in Confluence
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
### Kong resources

Lighthouse Kong API Gateway Overview
[https://app.zenhub.com/files/133843125/e888c5e3-f0a0-4c2b-b130-5d9e3def72b7/download](https://app.zenhub.com/files/133843125/e888c5e3-f0a0-4c2b-b130-5d9e3def72b7/download)

This repository is used to build the Docker image and deploy the Kong API gateway for lighthouse APIs to ECS on Fargate. The README has a Kong architecture diagram: https://github.com/department-of-veterans-affairs/lighthouse-api-gateway#architecture


Kong configs and management by environment:
https://github.com/department-of-veterans-affairs/lighthouse-platform-tools/tree/main/environments

**Comment by madebydna** [comment]
Of the API requests that get routed to Kong (`api.va.gov/services/` or `api.va.gov/internal`), the gateway proceeds to route then to either:
- vets-api
- Lighthouse APIs
- other, internal destinations

Based on the Kong configuration files in [https://github.com/department-of-veterans-affairs/lighthouse-platform-tools/tree/main/environments/prod/config](https://github.com/department-of-veterans-affairs/lighthouse-platform-tools/tree/main/environments/prod/config), the following routing rules exist:

Requests that get routed to the Forward Proxy ELB (i.e. Lighthouse APIs):

```
/services/forward-proxy-elb
/services/fhir/v0
/services/fhir/v0/r4
/services/fhir/v0/argonaut
/services/fhir/v0/dstu2
/services/clinical-fhir/v0
/services/address_validation/docs/v0/api
/services/address_validation/docs/v1/api
/services/address_validation/healthcheck
/services/community-care/v0
/services/loan_guaranty/v1
/services/address_validation/v0
/services/address_validation/v1
/services/address_validation/v2
/services/address_validation/docs/v2/api
/services/loan_guaranty/v1/healthcheck
/services/community-care-vaos/v0
/services/loan_guaranty/docs/v1/api
/services/va_facilities
/services/va_facilities/docs
/services/va_facilities/metadata
/services/va_facilities/v0/.*/cms-overlay
/services/pgd/v0
/services/benefits-reference-data/v1
/services/benefits-reference-data/v1/docs
/services/benefits-reference-data/healthcheck
```

Requests that get routed to vets-api (i.e. Lighthouse APIs that use vets-api):

```
/services/vets-api-elb
/services/apps/metadata
/services/apps/docs/v0
/services/apps/v0
/services/veteran/v0
/services/claims/v0/healthcheck
/services/claims/v0/upstream_healthcheck
/services/claims/docs/v0
/services/claims/v0
/services/appeals/v1/decision_reviews
/services/appeals/v1/healthcheck
/services/appeals/v1/upstream_healthcheck
/services/appeals/v2/decision_reviews
/services/vba_documents/metadata
/services/vba_documents/v1/healthcheck
/services/vba_documents/v1/upstream_healthcheck
/services/vba_documents/docs/v1
/services/vba_documents/v1/uploads
/services/vba_documents/v1/uploads/report
/services/vba_documents/v1
/services/va_forms/metadata
/services/va_forms/v0/healthcheck
/services/va_forms/v0/upstream_healthcheck
/services/va_forms/docs/v0
/services/va_forms/v0
/services/vba_documents/docs/v0
/services/vba_documents/internal/v0
/services/vba_documents/v0/uploads
/services/vba_documents/v0/uploads/report
/services/vba_documents/v0/healthcheck
/services/vba_documents/v0/upstream_healthcheck
/services/veteran_confirmation/metadata
/services/veteran_confirmation/docs/v0/api
/services/veteran_confirmation/v0
/services/claims/v1
/services/claims/metadata
/services/claims/docs/v1
/services/appeals/docs/v0
/services/appeals/appeals_status/metadata
/services/appeals/v0
/services/appeals/v0/healthcheck
/services/appeals/v0/upstream_healthcheck
/services/appeals/docs
/services/appeals/decision_reviews/metadata
/internal/auth/docs/v0
/internal/auth/docs/v1
/internal/auth/docs/v2
/internal/auth/v0
/internal/auth/v1
/internal/auth/v2
/services/meta/v0/version
/services/meta/v0/ping
/services/veteran_verification/docs/v0
/services/veteran_verification/v0
/services/veteran_verification/docs/v1
/services/veteran_verification/v1
```

Requests that get routed to other, internal destinations:

```
/internal/developer-portal/public
/internal/developer-portal/admin
/api_management/consumers
/internal/docs
```
