### ISSUE TITLE
[Design, FE] My VA - Health Care: Revisit Cerner alert content as new health systems are added to Cerner

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39030]
## Background
Per a conversation with Lauren Alexanderson, there are several "health care systems", which hold several facilities, that are moving over to become Cerner facilities.
We updated the Cerner alert to have a static message for a March 26th implementation, due to 5 facilities in the Walla Walla, WA Health care system moving to Cerner.

Per further conversation with Lauren, she stated that all facilities listed with the facility ID and variations given (i.e. 687, 687HA, 687GA, etc) would need to be displayed.  This is not ideal when there are more than 2 or 3, as the alert gets cluttered and long.

We need to revisit the alert content with the Health care products team (#health-care-products-all-teams) and Content team (#va-sitewide-content-ia).  We need to come up with the best way to handle the information.

#### References
- March alert update ticket - Walla Walla #687
- April alert update ticket - Columbus #757

>Lauren Alexanderson
>Here are the facility codes for those:
>
>- (668) Mann Grandstaff VAMC   
>- (463) Alaska VA   
>- (687) Walla Walla, WA   
>- (663) Puget Sound (Seattle WA)   
>- (757) Columbus, OH 
>- (692) White City, OR   
>- (648) Portland, OR    
>- (531) Boise,ID   
>- (653) Roseburg (Roseburg OR)

## Tasks
- [ ] Discuss with Health care products team and Content team on suggested in handling the copy on the Cerner alert
- [ ] Share findings/feedback with the team to decide on a path forward
- [ ] Create and schedule new ticket(s) to update design and/or code with decided changes, if any

## Acceptance Criteria
- Feedback received on content for Cerner alert and shared with the team for discussion
