### ISSUE TITLE
[FSR] Veteran entered compromise amount not seen on DMC Endpoint

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#39033]
## Issue Description
DMC has reported that they are not receiving the dollar amount that Veteran's request when they submit a compromise. 

---
## Tasks
- [x] Troubleshoot error and determine what is needed. 

## Acceptance Criteria
- [x] Either fix or solution has been identified. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Team is troubleshooting to determine route cause of the problem. 

@rileyorr 4/1 stated If the Veteran requests help for more than one debt then we ask them which resolution option they want for each. For example, if the Veteran requests a compromise offer for both a CH 35 education debt and a compensation + pension debt then the Veteran inputs their compromise offer in two different input fields.
I've attached a screenshot from staging. Makes a lot of sense that we'd want those values attached to the individual debts :slightly_smiling_face:

![FSR-resolution-options.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/5624e1dc-a2dd-4444-8538-28f45fe2bb41)


4/4 - @ScottyRJames Is going to see what values are being sent to DMC and where those amounts can be found. Are we sending individual values or are we adding them together for a total value?

**Comment by ScottyRJames** [comment]
@denisecoveyduc @rileyorr These values are captured by the frontend within the form field of `offerToPay` for each debt selected. When transforming the data we combine whatever compromise offer within the fields into one single field `discretionaryIncome` -> `amountCanBePaidTowardDebt`, which is the value that ends up being sent to DMC. 

> Are we sending individual values or are we adding them together for a total value?

Adding them together for a total

**Comment by ScottyRJames** [comment]
Update from Pavan at DMC:

> We only have one field in FSR form 24B, 
> 
![image](https://user-images.githubusercontent.com/20892803/163869346-ceb485ad-b6e0-43cc-9fe4-ba7f31ed94e5.png)

> We have 2 options,
Option1:  Put the total amount here in 24B (as it is today) and send the amounts for each debt in 36 with comment. At end of the comment. [For this Option, No Change required in FSR form and No API code changes] – UI can send debt type and the amount in details for each debt.
Option 2: Change the FSR form to accommodate the amount for each debt –Which need the FSR form changes and API code change and mapping changes.

Jill would like to continue with option 1 to avoid form changes. 

@rileyorr Can you confirm that field 24B in the paper form is correlated with the amount the Veteran is entering for a compromise? I noticed that our language says "What is your offer for a **one time** payment" and 24B says "Amount you can pay on a **monthly basis** toward your debt" but we also have an extended monthly payment option

**Comment by rileyorr** [comment]
@ScottyRJames great question! This came up in the past and there isn't a field in the form for Veterans to write their compromise offer.

**Comment by ScottyRJames** [comment]
DMC has requested we move forward with option #1

> Put the total amount here in 24B (as it is today) and send the amounts for each debt in 36 with comment. At end of the comment. [For this Option, No Change required in FSR form and No API code changes] – UI can send debt type and the amount in details for each debt.

**Comment by ScottyRJames** [comment]
Rolling over due to priority of [#49993](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49993)

**Comment by ScottyRJames** [comment]
Rolling over due to priority of [#49993](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49993)

**Comment by HeatherRienks** [comment]
Per @ScottyRJames , there is a PR open for 39033 as of yesterday...just awaiting approval
