### ISSUE TITLE
Design intent [CMS-Offices team - VA.gov Home Page]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#39038]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x] Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [x] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [x] Product outline – - [Product outline for VA unauthenticated home page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page
 
 
 
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes – see [Sketch file](https://sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857), screen called "VA-home-step-3a"
- [ ] User flow
- [ ] Research Plan
- [ ] Any other artifacts you have so far

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by allison0034** [comment]
Hi @wesrowe confirmed for 3/29 at 11am. Please upload any wireframes or user flows you have 2 days before the meeting. Thank you!

**Comment by artsymartha68** [comment]
Besides truly thinking mobile first/accessibility first, I'm wondering if there's a way to make download weight top priority. I challenge the team to make this the lightest, speediest page on VA.gov!

**Comment by CherylEvans** [comment]
No Content FB at this time.

**Comment by claytonzook** [comment]
No actionable feedback for research at this time, but I will reiterate some comments from the meeting:
- Should test for mobile as well as desktop and seek users with phones that aren't just top of the line
- Should test a coded product with participants who use a variety of assistive tech with various comfort levels.
- Consider participant representation, and even consider over-sampling historically under-represented groups.

**Comment by allison0034** [comment]
[Zoom recording](https://us06web.zoom.us/rec/share/6Z4BOMu7PZeW2Ot7_iaF79zYMXZ1Ljp_C6bAIu_gN0GngHdGYSpyj8dWonc35kyQ.bN60Thz4JK4YYWdj ) and Passcode: Ra#5=#j&
