### ISSUE TITLE
[BE] Fix patientDFN to patientDfn in CHIP/confirmDemographics request

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#39043]
### Description
Modify `CHIP/confirmDemographics` request with `patientDfn` instead of `patientDFN`

### Tasks
- [ ] Modify request parameter key to use patientDfn instead of patientDFN
- [ ] Wrap the changes behind feature flag
- [ ] rspecs

### Acceptance Criteria
- [ ] Deployed and tested in staging
