### ISSUE TITLE
Login.gov Inherited Proofing - vets-api service Pt. 2

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#39040]
## Issue Description
Create a new service to interact directly with Login.gov for the MHV inherited proofing flow. This service will generate an auth code to be sent with the user to login.gov and then when login.gov calls this service with the auth code we will respond with user attributes. This PR covers the second half of this flow, creating a new callback endpoint to serve Login.gov with the required User attributes to create a new account.

---
## Tasks
- [ ] create `logingov_proofing_attributes` route & controller method within the v1/sessions_controller
- [x] `logingov_proofing_attributes` logic within `logingov_inherited_proofing` to validate returned auth_code against vets-api's stored auth_code
- [x] `logingov_proofing_attributes` response with the following user attributes:
* first name
* last name
* address
* phone
* dob
* ssn
* phone (technically optional)
- [x] a valid auth code can only be used to access user attributes once; on a successful call the Redis entry for the stored auth_code & information will be deleted

## Acceptance Criteria
- [x] vets-api `logingov_proofing_attributes` requires an auth_code that is validated against a saved auth_code
- [x] vets-api `logingov_proofing_attributes` returns the user attributes needed for Login.gov to create an IAL2 account

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
