### ISSUE TITLE
Document HW/SW and Run Scans for the ATO

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39057]
## Update
We do not need to complete this ticket. Refer to slack [thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1648649831572869?thread_ts=1648648333.742509&cid=C02G6AB3ZRS)

## Problem Statement
As the VA, we need to generate documentation for our ATO on which Ed Teeple is working, Here is the ask from his email:

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/2b6dbcad-c9cf-4891-b7eb-63b3094c4493)

## Task
- [ ] Gather documentation of software/hardware inventory 
- [ ] Run Fortify and Brakeman scans 

## IMPORTANT
- **Inventories and scans should be stored on our private GitHub (i.e. NOT public)**

**Acceptance criteria**
- [ ] Software inventory documentation is completed and provided
- [ ] Hardware inventory documentation is completed and provided
- [ ] Fortify scans for each API are completed and provided
- [ ] Brakeman scans for each API are completed and provided
- [ ] All documents are made available and provided to Ed Teeple
