### ISSUE TITLE
Add lead time to Midpoint Review and Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39055]
## User Story
As a VFS team member, I want to know how many days in advance I need to schedule a design intent so that I can plan accordingly.

- Intended Audience: VFS teams
- Desired Outcome: Platform Website is updated to specify lead time on Midpoint Review and Staging Review
- Due Date: TBD

## Description
Recently, @allison0034 updated the [Design Intent touchpoint page on Platform Website ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html#Designintent-Timing) to specify that the Design intent requires a 2 day lead time. The lead time information is missing from Midpoint Review and Staging Review. This ticket will be for updating those pages to reflect the lead time.

## Artifacts Needing Updates
[Platform Website: Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
[Platform Website: Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)

## Tasks
- [x] Use the [Design Intent page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) as a reference
- [x] On the Midpoint Review page, under Timing, add the sentence, "Midpoint Review requires a 2 day lead time"
- [x] On the Staging Review page, under Timing, add the sentence, "Staging Review requires a 4 day lead time"

## Acceptance Criteria
- [x] Midpoint Review page on Platform Website has been updated per guidance
- [x] Staging Review page on Platform Website has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@chaseakirby @shiragoodman the pages have been updated.
[Platform Website: Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
[Platform Website: Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)

**Comment by shiragoodman** [comment]
looks good to me - closing! FYI @chaseakirby
