### ISSUE TITLE
[Design] My VA: Review various alerts and errors on My VA for consistency

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#39066]
## Background
In ticket #[36340](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36340), screenshots were gathered of various alerts and errors on My VA and guidance was provided from the platform team on which component should be used across the board. 

Guidance from Natalie Hill:

> I recommend the Warning alert -- either the standard full-width style or the background only style -- for the scenario you are describing. We can also talk about making it dismissible if you'd like that option.

According to this guidance, we would need to update the alerts in the code for the following scenarios:

- Notification dismissal error: Can’t dismiss notification
- Claims API error: We can’t access your claims or appeals information
- Health care appointments API error: We can’t access your appointment information
- Main user call fails but page is able to load (we can't tell if user has VA health care): We can’t access any health care information right now
- Debt or copay API error: We can’t access some of your financial information
- Payment history API error: We can’t access your payment history

_Note: we can only proceed with this once the new notification component is released._
## Tasks
- [x] Update ticket to reflect which states need to be changed in designs and code
- [x] Update documentation and designs to change all error states to the "warning error component"
- [x] Make a note in the FE ticket about which error states need to be updated with which design components (FE ticket is #60329)

**Comment by hdjustice** [comment]
We have decided not to make this change until we have determined a notification style that will work for My VA.  Exploration currently underway.

**Comment by ajakabcin** [comment]
this is dependent on the release of the notification component - once that's out we can update all error states to the "warning error component"

**Comment by aagosto90** [comment]
Updated [Allison's FE ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60329) with a list of alerts to update and added a comment on the ticket for further clarification. I updated use case documentation and FE documentation as part of this ticket.
