### ISSUE TITLE
Go-Live Cerner support Roseburg 

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#39062]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on the relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)
Timeline for launch: Testing the month of May (possibly including last week of April)
Go live stuff: June 13th Go-Live

- Facility ID's: Roseburg health care facilities

### Considerations
- Follow the Cerner Runbook and prepare Roseburg Facility for Cerner launch  
- This will need deploy to staging initially in order to be tested by the facility and our team
- Once fully tested and validated in staging, we'll prepare to deploy in production per runbook guidance

### Tasks
- [ ] Follow the Cerner Runbook and prepare Roseburg for Cerner launch 
- [ ] Test locally and set up a staging test environment so Facility admins can test.
- [ ] Once validated in staging deploy to Prod per the runbook guidance 
- [ ] Review and close ticket once work is completed

### Acceptable Criteria 
- [ ] Roseburg is now launched in Cerner 
- [ ] Local test are completed and show signs of success
- [ ] a11y considerations are implemented in support
