### ISSUE TITLE
Modify operational guidance for Setting Up Recruitment with Perigean 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39065]
## User Story
As a Governance team member, I want to update the Setting Up Recruitment with Perigean operational guidance on Confluence so that I have up to date, correct instructions for how to provide support consistently.

- Intended Audience: Governance team
- Desired Outcome: Setting Up Recruitment with Perigean guidance is up to date.
- Due Date: TBD

## Description
Governance team is now officially sharing responsibility with regards to setting up recruitment with the research operations contractor, Perigean. The Platform/Governance team operational guidance on Confluence will need to be updated to reflect the current practices.

_Additional background for [Collaboration Cycle - Transition VFS research activities to Platform](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32698) initiative_

## Artifacts Needing Updates
[Setting up Recruitment with Perigean (Moderated and Unmoderated)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2099577036/Setting+Up+Recruitment+with+Perigean+Moderated+and+Unmoderated?focusedCommentId=2123792394#comment-2123792394)

## Tasks
N/A

## Acceptance Criteria
- [x] Setting up Recruitment with Perigean (Moderated and Unmoderated) Confluence document has been updated per guidance
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@claytonzook FYI

**Comment by claytonzook** [comment]
@chaseakirby this ticket is brand new yesterday. As I'm starting to work on it today, I realized it didn't have a ready tag. Anything I should wait on before diving in?

**Comment by chaseakirby** [comment]
@claytonzook You can go ahead and work on this! I have mostly been thinking the "Ready" tag for tech-debt work but thanks for checking. We'll probably start using it on these initiative stories too but this one is good to go regardless.

**Comment by claytonzook** [comment]
[Draft copy](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/2139127809?draftShareId=cba7a871-c711-4fb7-a355-510afa883815) is ready for peer review @chaseakirby @shiragoodman

**Comment by claytonzook** [comment]
Document updates have been published in Confluence. Closing ticket.
