### ISSUE TITLE
SiP: Make return URL dynamic

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39070]
## Description

After opening the [save-in-progress menu](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress-menu) and pasting in new form data, the "Return url" does not dynamically update based on the data. So the return url may not exist and cause an issue where pressing back or continue will kick you back to the introduction page.

## Tasks

- [ ] Dynamically update the return url based on the form data in the menu
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
