### ISSUE TITLE
Create a Banner for MHV Inherited Proofing

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#39076]
## Issue Description
This will create a notification Banner on VA.gov to inform users about the upcoming Inherited Proofing and the push for MHV users to migrate to creating a verified account with Login.gov or ID.me

---
## Tasks
- [x] Creates a Notification Banner for the MHV Inherited Proofing
- [x] Adds approved content (Content/IA and OCTO leads approved)
- [x] Enable/disable Notification Banner based on flipper flags

## Acceptance Criteria
- [x] The MHV Inherited Proofing banner can be toggled on/off

**Comment by nsoutouras** [comment]
Banner is cancelled.
