### ISSUE TITLE
Platform Console — Adapt intake process based on Platform website

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39083]
## Problem Statement 

In 2022, the Platform is focusing on iteratively building and releasing the Console.  To provide contributors with editorial support and customers with quality docs, the Platform Content team has created a process to intake ideas for the Platform Website.  

However, no such intake process exists for Console content and copy.  Platform Content team and Console UI team sync weekly, but this is not scalable as more Platform teams contribute to Console.

_HMW we adapt the Platform website intake process and allow us to smoothly intake Console content?_

## Hypothesis or Bet
If we ___, then we will can include Console writing work* into our commitments (a) without disrupting velocity and (b) with optimized skills/needs matching.

Our bet (the blank) depends on the to-be-defined intake process for Platform Website content.  Initiative to define intake process: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34933 

## We will know we're done when... ("Definition of Done")
* We've socialized a process to teams contributing to Console
* We've codified the process in the Platform Content Team space
* Everyone on the Platform Content team knows the role they play in intaking and acting upon submitted Console writing work

## Known Blockers/Dependencies 
* n/a

## Projected Launch Date
End of Spr 77 (May 10)

## Launch Checklist

<details>

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 
</details>

## Required Artifacts

<details>

### Documentation
* **`PRODUCT_NAME`**: Console
* **Product Outline**: https://vfs.atlassian.net/l/c/aP1yWE70
* **User Guide**: yet to be created

### Testing

n/a, since we are proposing a net new process (not iterating on something, or capturing pre/post-launch data)

### Measurement

* **Success metrics**: 
  * How many requests for writing help are made
  * Confidence from requestees that the Platform Content team is adding value
  * Ability of Platform Content team to incorporate requests alongside existing initiative work
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39100
</details>

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by andreahewitt-odd** [comment]
This work is part of https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/43463
