### ISSUE TITLE
Migrate MHV Inherited Proofing Transition page to separate application

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#39080]
## Issue Description
This ticket tracks the work of moving the MHV Inherited Proofing process into a separate application (currently exists within the `login` application) on vets-website

---
## Tasks
- [x] Moves all components belonging to the MHV Inherited Proofing process into a separate application
- [x] Ensures functionality works the same
- [ ] Conditionalizes application creation for Flipper feature as well as only in lower environments

## Acceptance Criteria
- [ ] The MHVIP transition page only is viewable in lower environments
