### ISSUE TITLE
[UNPLANNED] Reference Number on COE

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#39089]
## Background
LGY has requested that we show the reference number for the COE application on the confirmation screen of COE submission.

## Tasks
- [x] Include reference number in success message for application PUT
- [x] Update FE that BE work has been completed

## Acceptance Criteria
- [x] A PR has been requested for merging
