### ISSUE TITLE
va-modal blocks internal components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39081]
## Description

While using the `VaModal` react binding for the `va-modal` web component, any internal form elements do not work as expected.
A [demo setup to use the `VaSelect` internal to the `VaModal`](https://codesandbox.io/s/intelligent-shaw-rk07l1?file=/src/App.js) shows that the select does not respond to any interaction. Remove the modal and the `va-select` will work as expected. This also happens if the `va-select` is replaced with `va-checkbox`

Related: https://dsva.slack.com/archives/CBU0KDSB1/p1648144111629739?thread_ts=1648142617.286119&cid=CBU0KDSB1
cc: @k80bowman 

## Tasks

- [ ] Troubleshoot & fix `va-modal` web component
- [ ] Update unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
After some investigation, it appears that the current version of [focus-trap](https://github.com/focus-trap/focus-trap) library doesn't target the shadow DOM when building the list of tabbable nodes. This has been fixed in `6.8.0-beta.0` (currently `6.8.0-beta.2`), but this beta has not been "officially" released (no tag), but is available in the beta channel.

I tried installing `6.8.0-beta.2` using `yarn add focus-trap@https://github.com/focus-trap/focus-trap#beta`, but that didn't seem to work. I was able to install it using `npm install focus-trap/focus-trap#beta --save`, but even after [adding the `getShadowRoot` option](https://github.com/focus-trap/focus-trap/issues/601#issuecomment-1065698407) to the `createFocusTrap`, it still wasn't working

```diff
--------- packages/web-components/src/components/va-modal/va-modal.tsx ---------
index 69092eb..f79ff4f 100644
@@ -220,8 +220,12 @@ export class VaModal {
         // the close button.
         // If initialFocusSelector is not specified, focus will be received by the close button.
         initialFocus: initialFocus || this.closeButton,
+        tabbableOptions: {
+          getShadowRoot: () => true,
+        },
       },
     );
```

This may have to wait until focus-trap 6.8.0 is officially released.

**Comment by k80bowman** [comment]
@Mottie It looks like v6.8.0 was [released](https://github.com/focus-trap/focus-trap/releases) yesterday!

**Comment by Mottie** [comment]
Hmm, I've updated focus-trap to 6.8.0 and added the `tabbableOptions`, and it's not working as expected. In fact, the focus is now stuck on the close button. I'll keep troubleshooting, but I think I'll go back to copy the method ionic is using instead of relying on a third-party library

**Comment by k80bowman** [comment]
That is frustrating. Thank you for trying it out.
