### ISSUE TITLE
HLR/NOD update verify identity alert content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39109]
## Description

When a Veteran has not verified their identity, the Higher-Level Review and Notice of Disagreement forms both show an alert on the introduction page and are prevented from continuing the form.

>  **Message title:** We need you to verify your identity
>
> You’ll be able to complete this form after your identity is confirmed. This helps us keep your information safe during the application process.
> [Verify your identity](Link)

Related:
- Recommended content: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38849
- Alert added in https://github.com/department-of-veterans-affairs/va.gov-team/issues/38668

## Tasks

- [ ] Update HLR verify identity alert content
- [ ] Update NOD verify identity alert content
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
