### ISSUE TITLE
Create a Support FAQ section for VA Platform Documentation

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#39103]
## Description

We would like to have an FAQ page under Support documentation to provide immediate answers to common questions that are typically submitted to the support bot in Slack.

## Background/context 

Some requests to the support bot are duplicated or can be answered with a documentation link, but there is no central place for the SRE team to store and look up those references easily. There also is no curated place for users of the support bot to look up common recurring requests.

## Technical notes

How to for adding/editing documentation pages: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page

---
## Tasks
- [x] Establish a structure for the documents.
    ```
    VA Platform Documentation
    └── Support
        └── Platform Support FAQs
            ├── Frontend Tools Support FAQs
            ├── Backend Tools Support FAQs
            ├── Infrastructure Support FAQs
            ├── Design System Support FAQs
            ├── Analytics & Insights Support FAQs
            ├── Collab Cycle FAQs
            ├── QA Standards Support FAQs
            └── Platform Security Support FAQs
    ```
- [x] Document how to add to these FAQ pages to ensure consistency.
    https://vfs.atlassian.net/wiki/spaces/SRE/pages/2139062311/How+to+Add+Support+FAQs
- [ ] Review plan with content team to get feedback.
  - **Pending:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/39157 created for content team to review
- [ ] Add draft VA Platform documentation pages.
- [ ] Add initial content.
- [ ] Publish initial FAQ pages.

## Acceptance Criteria 
- [ ] A page structure is established and instructions are created to contribute to the Platform Support FAQ.
- [ ] The initial page structure and content have been added to the VA Platform documentation site.

**Comment by jhouse-solvd** [comment]
@rsmithadhoc - Is there anything needed from the Platform Infrastructure team on this? 

If not, I'd like to remove the "operations" label if that's okay with you.

**Comment by rsmithadhoc** [comment]
> @rsmithadhoc - Is there anything needed from the Platform Infrastructure team on this?
> 
> If not, I'd like to remove the "operations" label if that's okay with you.

@jhouse-solvd Nope, I'm not sure why I added that, I'll remove that.

**Comment by jhouse-solvd** [comment]
@rsmithadhoc - Thank you. 

Side note: I think that label gets auto-added by some issue templates.

**Comment by alyssagallion** [comment]
@rsmithadhoc Can you provide an update on this one?

**Comment by rsmithadhoc** [comment]
@alyssagallion I'll go ahead and close this one since it is so old and not relevant anymore, thanks!
