### ISSUE TITLE
[FE] Demographics Edit - Address Component Refactor

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#39118]
## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description
The Address component for demographics currently has all logic and multiple variations put into a single large component. This can be broken up into smaller and more manageable components with some logic reused between them.

## Tasks
- [ ] Refactor Address component UI
- [ ] Refactor Address component logic
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
