### ISSUE TITLE
[FE] My VA - Health Care update: Add new White City health system as Cerner in My VA (June 2022)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39125]
## Background 
White City health system is being added as a Cerner health system in June.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert. 

> ID 692 - White City: Go-live -- 6/11/2022 

## Tasks
- [ ] [FE] Add filtering so Cerner alert will now show for White City. The facility number is **692**.
- [x] [Design] Confirm with content team what the copy should be 
- [ ] [FE] Update the copy in the alert  (Copy and logic may be revisited before this implementation - [Ticket department-of-veterans-affairs/va.gov-team#39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))
- [ ] [FE] Coordinate with Adam so that he's able to make sure the timed release is functioning properly on the 11th

## Acceptance Criteria
- New Cerner facility is added and message updated on the My VA Cerner alert

**Comment by ajakabcin** [comment]
This issue is on a timed release for 6/11 - waiting for validation until then.

**Comment by ajakabcin** [comment]
Confirmed on staging. For now the copy is going to include the word "or" between facility names. We'll update this with the next facility addition to use commas in between instead.
