### ISSUE TITLE
Create flipper flags on vets-api for MHV inherited proofing

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#39128]
## Issue Description
Create flipper features on vets-api to toggle the following features on vets-website:
- Eligibility Status Banner - `mhv_transition_logingov_banner`
- Eligibility Modal - `mhv_transition_logingov_modal`

---
## Tasks
- [ ] 2 flipper flags created for banner and modal

## Acceptance Criteria
- [ ] 2 flipper flags created for banner and modal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
