### ISSUE TITLE
Add feature flag to the inherited proofing modal

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#39126]
## Issue Description
Currently, the modal lives in code and will open when the desired property on the user model is true. We need to update this to also have a requirement on a flipper feature being active.

---
## Tasks
- [ ] Use `mhv_transition_logingov_modal` flipper to toggle whether modal is active or not

## Acceptance Criteria
- [ ] MHV transition modal will not open unless the feature flag is on
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
