### ISSUE TITLE
Product - Auth Profile - Bad Address Indicator - Send email content to Privacy & Security for sign-off

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39122]
## Background

Before we work with VA Notify to begin sending out emails related to bad addresses, we need to have the content approved by Privacy and Security.

## Tasks
- [ ] Create Privacy and Security request for email content
- [ ] Note in this ticket the issue number for the request in the comments for this ticket. 

## Acceptance Criteria
- [ ] Create Privacy and Security request for email content
- [ ] Note in this ticket the issue number for the request in the comments for this ticket. 

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
Privacy and security ticket (sensitive repo): [#435](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/435)
