### ISSUE TITLE
Letters: Fix unit tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39132]
## Description

While searching for `CollapsiblePanel` I discovered some unit tests within the letters app that were passing, but shouldn't have been given that they were searching for the `CollapsiblePanel` component which has been replaced by `va-accordion`.

## Tasks

- [ ] Fix letter list unit tests

## Defintion of done

- [ ] All tasks complete
- [ ] All tests passing
