### ISSUE TITLE
Discovery: Gather Use Cases & Requirements for a Product List from Stakeholders/Teams

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#39156]
## Issue Description
In planning out an approach to a Product List it will be important to understand what teams and/or people will be stakeholders in this process, and then to understand what their use cases and requirements are for those stakeholders and use cases in order to ensure that those needs can be accounted for and incorporated into the end result.
 
---
## Tasks
- [x] Identify list of potential stakeholders
- [x] Create list of questions for the discovery process
- [x] Create survey in Optimal Workshop
- [x] Launch survey
- [x] Follow-up w/ teams to ensure participation with all stakeholders
- [x] Distill results
- [x] Document results in Confluence
- [x] Report results to leadership

## Acceptance Criteria
- [x] Complete list of stakeholders has been identified
- [x] All stakeholders have provided their input/requirements
- [x] Distilled results have been documented to Confluence
- [x] Readout represents all feedback/input

**Comment by pjhill** [comment]
@CBonade -- Pull whatever data you need out of Joe's personal space version of the doc [here](https://vfs.atlassian.net/wiki/spaces/~750876204/pages/2067333175/Product+List+-+Interested+Parties).

**Comment by pjhill** [comment]
As of 4/5 AM, heard back from --
Console UI (Slack)
Release Tools (Slack + Survey)
Infrastructure (Survey)
Contact Center (Joe has data)

**Comment by pjhill** [comment]
Responses and feedback collected during meetings with teams has been collected into this Mural -- https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1649377300526/ed440220603d6afe04eb9bd7a8b8b8f2addc6a94

**Comment by JoeTice** [comment]
Research readout and approach covered on 5/3/22
