### ISSUE TITLE
Iterate on error message and downtime banner guidelines per VSP findings

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3915]
VSP conducted an audit of downtime banners on VA.gov (#2229) and is bringing the error messaging guidelines into the VSP ecosystem (#1401). 

Based on findings from reviews associated with the above linked epics, we are iterating on error message and downtime banner guidelines in the design system. 

### User Story 
As a content writer for VA.gov, I need to know the best way to convey an error or downtime message to a VA.gov end user, so that I can provide an experience consistent across all of VA.gov. 

### Definition of Done
- [ ] Updates to error messaging and downtime banner guidelines are identified and reviewed by VSA Public Websites 
- [ ] Content style guide is updated
- [ ] Updates are communicated to VFS teams

**Comment by vbellissimo** [comment]
Cancelling/old task.
