### ISSUE TITLE
Q2 2022 QAS - Create VFS Product List - MVP

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#39151]
## Problem Statement 
There is currently no reliable list of the products on the VA.gov platform that suitably addresses the varying use cases of Platform teams. The known use cases require a list that is both human readable, and machine readable, so it can be used by automated tools and processes across the platform. Currently many teams create and maintain their own lists for their specific purposes, it is not uncommon for these lists to become out of sync with the products on va.gov, and to produce lists that do not align with other tools created by other teams, using other lists, this creates confusion for teams and leadership across the platform.

## Hypothesis or Bet
How might we understand the use cases and data requirements for a product list from each team that needs one?
How might we create a new list that addresses those use cases and data requirements?
How might we make it user friendly enough to make it easy to use?
How might we integrate with the Collaboration Cycle to ensure higher awareness and engagement for the list?

We believe that by understanding the specific use cases and requirements for a product list by the teams across the platform, we can design and produce a single list that can address these needs across the platform and eliminate the confusion caused by multiple lists. By doing this, we hope to eliminate the need for multiple unique lists, and the confusion and issues that come along with it.

## We will know we're done when... ("Definition of Done")
- [x] We have received and incorporated input from platform teams on their use cases and data requirements
- [x] We have planned and documented a solution that addresses those use cases and data requirements
- [x] We have prioritized at least 1 machine readable use case, and 1 human readable use case
- [x] We have created the product list and populated it with existing data to support the selected use cases
- [x] We have designed an interaction for updating the list that is easy to use
- [ ] We have documented how to use the list for all MVP use cases and applications
- [ ] We have planned for and documented how this will tie into the Collaboration Cycle and how to foster ongoing engagement
- [ ] The **VFS Product List** is available and ready for use by other teams

## Known Blockers/Dependencies 
* There is currently no clear and universally adopted definition of what is/isn't a product, lack of clarity on this will create challenges during implementation, but we don't anticipate that it would block the effort
* Some data attributes have no defined/existing data source to populate the list from and will need to be researched or developed
* Platform Console development continues to evolve and the parameters of how that might affect a product list change along with it. We will sync with the Platform Console teams on a regular basis in order to stay informed about any requirements we will face for including this product list in the Platform Console

## Projected Launch Date
Jun 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable
- [ ] >90% of teams will be able to use this list to meet their defined needs

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: n/a
* **Product Outline**: [Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2138800169/Product+Directory+Product+Outline)
* **User Guide**: TBD
### Testing
* **Usability test**:
- [ ] Have conducted usability testing with a team that requires a human readable list
- [ ] Have conducted usability testing with a team that requires a machine readable list
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**:
Pre-Initiation
- [ ] Have determined the current number of team lists being used
Post Launch
- [ ] Have verified that these use cases are effectively addressed in the new list

* **Release plan**: [Link](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/39190)

**Comment by JoeTice** [comment]
Governance team is doing some initial work on this [under this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38418)

**Comment by pjhill** [comment]
Per discussion with Mike Chelen,
* One way to swarm this might be to give analysis of each discovered "product list" to an engineer
* Consider iterating through de-duplication of existing "product list"
* Have an engineer conduct a synchronous meeting to gather use cases / requirements

**Comment by mchelen-gov** [comment]
Recommended workflow:
- User inputs data to Github (YAML) issue form
- Data input is parsed by Github Action which updates machine readable data structure (CSV)
- Machine readable data is processed by Github Action to create human readable page (Github Pages)
- Github Page views (customized by use case) are linked as reference from other sources (Confluence)

> We have created the product list and populated it with any existing data
This is too broad, "any existing data" does not need to be included. What needs to be included is any existing data necessary for 1 manual + 1 machine use case.

**Comment by JoeTice** [comment]
A newer Q3 version of this initiative has been created here: https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/43675
