### ISSUE TITLE
[SW-Content] Review and update changes made to Burials and memorial pages [CE]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39160]
## Story
As a Veteran website users I need accurate and up to date information, so I can make the correct decision for my needs.

## Task(s)
- [x] Review changes made to B&M pages
- [x] update any content as required to meet VA.gov design-style guide standards
- [x] Publish page and have stakeholders review changes

## Acceptance Criteria
* Stakeholder has published changes for review and approval.
