### ISSUE TITLE
Design - Auth Profile -Bad Address Indicator - Document Front-End Design

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39161]
## Background

Please create frontend documentation that a FE dev can use to build out the bad address indicator updates. 

## Tasks
- [x] Document Front-End design
- [x] Add link to documentation to [FE build ticket]( #39162)

## Acceptance Criteria
- [x] Document Front-End design
- [x] Add link to documentation to FE build ticket

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss! Here is the [updated FE documentation for Bad Address Indicator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/frontend/FE%20documentation.md). Adam and Mark both looked through and confirmed the format would work well for them.

Any further changes or additions needed before I add this to the FE build ticket? And is this the correct [FE build ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39342)?

**Comment by cgednalske** [comment]
Awesome - thanks, @Samara-Strauss! And great point with the Email section. I'll add the background you mentioned above and make sure it's clear that it doesn't concern FE 👍

**Comment by SKasimow** [comment]
@cgednalske - looks good and like the format. I may have missed this but will we continue to display the alert until the user takes action?

**Comment by SKasimow** [comment]
@cgednalske - ticket #39342 thanks!

**Comment by cgednalske** [comment]
@SKasimow thanks! I've linked the documentation there, so this can be closed.

**Comment by SKasimow** [comment]
@cgednalske thank you!
