### ISSUE TITLE
GitHub action vale as plain language linter

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#3916]
The MVP of vale as a plain language linter adjacent to the CMS user's workflow (#2233) has been deprioritized ([decision documented](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/automated-content-review/decisions.md)) in favor of using the GitHub action as a proof of concept.

_More context: the initial MVP was begun as part of the workflow of content writers using the Drupal CMS. This makes sense in theory, but because access to the Drupal CMS is still incredibly restricted (2-3 content editors, 1 of whom is VSP's content editor), we hypothesize that we won't actually be catching many VFS team members in this location — and those we would catch are content editors and writers who are primarily self-sufficient re: content reviews. Pivoting the implementation to vets-website will allow us to catch enough VFS team members with these content validations to actually validate whether automated content tests are worth investing further in._ 

In this epic we are looking to:

- Implement Vale as a GitHub action in 1 or more appropriate repos (likely `vets-website`) so that content validations are present in the workflow of VFS team members outside of the CMS.
- Explore and implement automated metrics gathering so that we can determine whether to invest more resources in automated content tests

## User Story 
As a VFS team member writing content for VA.gov, I want to see automated content validations, so that I am better able to self-serve and write error-free, plain language content.

## Definition of Done
- [ ] Plain language linter implemented in VFS teams' workflow
- [ ] Automated metrics implemented (for measuring adoption of plain language linting)
- [ ] Synthesis of effort and results so far created and presented to VSP leadership and DEPO, next steps captured as epics and/or stories in ZenHub

**Comment by billfienberg** [comment]
Here is a draft PR to add the `vale-action` to the `vets-website` repo:
https://github.com/department-of-veterans-affairs/vets-website/tree/add-vale-github-action
