### ISSUE TITLE
Product - Auth Profile - Bad Address Indicator - Determine test user info

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39169]
## Background
As a Product Manager I want to know what test user(s) can be used to test on Staging.  _Note - I believe that Tom and Adam may already have gotten this info from Ian on the VA Profile team._  If that is the case, include that in the product documentation.

## Tasks
- [x] Determine which user(s) can be used to test bad address flag on staging
- [ ] Record this information in the product documentation

## Acceptance Criteria
- [ ] Determine which user(s) can be used to test bad address flag on staging
- [ ] Record this information in the product documentation

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @tpharrison - added you to this ticket for creating staging accounts with BAI. As soon as I figure out how many/which ones I'll update the ticket.

**Comment by SKasimow** [comment]
Completed...see #42219
