### ISSUE TITLE
[FE] Update Day-of Check-in to confirm Demographics before check-in complete

### ISSUE THREAD

**Issue by dcgoodwin2112** [department-of-veterans-affairs/va.gov-team#39183]
## User Story
As a veteran, If I confirm all of my demographics, but do not check into an appointment, then I should be able to check in later and not have to confirm my demographics again.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description
Demographics confirmations are currently sent on the check-in confirmation page. These should be moved to the appointments page or after the final confirmation page in the day-of check-in flow. Update the confirmationsSent session key logic to allow confirmations to be sent multiple times. Add a check to make sure the demographics endpoint is not called repeatedly when checking into multiple appointments.

## Tasks
- [ ] Update API call on SeeStaff page to send multiple times
- [ ] Move check-in Confirmation page API call to Appointments page or between demographicsConfirmations and the appointments page
- [ ] Add check to ensure demographics endpoint is not called multiple times when checking into multiple appointments
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by dcgoodwin2112** [comment]
related slack threads:
https://dsva.slack.com/archives/C02GXKL8WM6/p1648235625840749
https://dsva.slack.com/archives/C02G6AB3ZRS/p1648067065876269

**Comment by acrollet** [comment]
One thing I thought of: let's make sure that the call can succeed even if the veteran clicks 'check in' before the call is complete.

**Comment by loripusey** [comment]
@acrollet Can we close this one since it has been validated in prod?

**Comment by acrollet** [comment]
yep!
