### ISSUE TITLE
[Access Requests] Automatically notify reviewers for access request

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#39182]
## Description
In https://github.com/department-of-veterans-affairs/va.gov-team/issues/31272, Jesse mentioned that, "It would be good to notify the infrastructure team and AWS approvers automatically, if possible." When I created the new SOCKS and AWS requests, I added markdown to `cc` github groups, but found in [the documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown) that markdown is not submitted in a YAML github form 😒 .
So even though I have this at the end of the YAML:
```
  - type: markdown
    attributes:
      value: |
        ---
        CC: @department-of-veterans-affairs/vsp-operations
```
It doesn't show up when the issue is submitted. Example (fake) open request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39096

## Background/context 
When any issue with the label `ops-access-request` is opened, a Slack message is sent to #platform-infrastrucure. This means we are notified in Slack about new AWS and SOCKS requests.
Order of operations for SOCKS and AWS requests:
* SOCKS: run an Action that creates a PR, merge PR, close request. This is quick and takes ~5 min. 
* AWS: Notify `@ department-of-veterans-affairs/operations-aws-approvers` and they process the request on their own schedule (usually Thursdays). If approved, relevant changes are made to the devops repo by an Infra team member. Team member sends login info to the user and then the ticket can be closed. 

**Why do we want to do this?**
* It seems like the main reason for this ask is to notify the AWS approvers that there is an open request. If the AWS approvers group is notified automatically upon Issue creation, there would be no reason for an Infrastructure team member to touch the request until it was approved. This would be a small, but nice, time-saver.
* With the SOCKS request, the notification comes to Slack and can quickly be taken care of. It seems like these SOCKS requests don't usually fall through the cracks with our current mode of notification (Slack).

## Technical notes
I asked about this in #github_information ([link to thread](https://dsva.slack.com/archives/CU1E4CX9U/p1648151665569549)) and people offered a couple different solutions. 
1. Include a field that automatically adds the group. I tested that out to see what it would look like by creating a template on my fork. The person filling out the request would see something like this at the bottom of the request:
![image](https://user-images.githubusercontent.com/10993987/160198973-8a6141f1-8de5-47cc-909f-ab3c89978cea.png)
[Link to sample request template](https://github.com/rmtolmach/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D)
Or it could be something a bit nicer:
![image](https://user-images.githubusercontent.com/10993987/160200331-b1a2d87c-2964-47cb-9162-22b51cd74946.png)
A submitted request would look like this: 
https://github.com/rmtolmach/va.gov-team/issues/5
or
https://github.com/rmtolmach/va.gov-team/issues/6
2. Create a github action to look up members of a group and set those members as assignees. This was suggested by Tyler Garner in the Slack thread I linked above. He shares his code in the thread. 
---
## Tasks
- [ ] Decide if we need to notify groups for the SOCKS _and_ AWS requests.

## Acceptance Criteria 
- [ ] Decide what we want to do, if anything.
- [ ] do it.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Closing.
