### ISSUE TITLE
Explore adding the Product QA Dashboard to Platform Console

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#39191]
## Issue Description
Dashboards will be moving into the Platform Console in the future, explore what will be involved in this to determine what preparation can be done in advance and document findings.

---
## Tasks
- [ ] Discuss dashboard needs and plans with Console teams
- [ ] Document findings
- [ ] Create tasks and tickets as needed to support

## Acceptance Criteria
- [ ] We have a good understanding of how dashboards will be handled in the Platform Console
- [ ] Known tasks that can be done in advance are created as Zenhub tickets
