### ISSUE TITLE
[BE] Enhance Authentication Limit to Delete Associated LoROTA Entry when Auth Fails

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39199]
Is this a dependency?
https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/870

## User Story
Authentication attempts are currently limited to 3 tries – enhance this to delete the associated LoROTA entry when auth fails.

## Acceptance Criteria
- [ ] Enhance authentication limit (i.e. 3 tries) to delete the associated LoROTA entry when auth fails.
     - vets-api should store the retries and call the LoROTA delete API endpoint to delete the entry
- [ ] Make the retry limit configurable (1 configuration)

## Notes
- Once their LoROTA entry is gone, to log in again
    - for PCI, they will need to wait for another notification
    - for CI, they will need to text "check in" again

## Tasks
- [ ] Deploy and test on staging.

**Comment by acrollet** [comment]
I believe this could be done entirely in LoROTA.

**Comment by randomsync** [comment]
I'm not sure if we want to implement this functionality in LoROTA if we're considering LoROTA to be a generic purpose low auth cache, because different applications might have different requirements for this limit.

@stephenBarrs @acrollet is that thinking correct? lmk if we should discuss on call?
