### ISSUE TITLE
CHIP ---- [BE] Proactively Remove LoROTA Entries

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39198]
ALL OF THIS IS CHIP WORK - COMMUNICATE WITH CHRIS

## User Story
As the VA, we need to proactively remove LoROTA entries as soon as possible so that the records are more secure.  If the record needs to be retained until the time of the appointment, remove all unneeded PHI/PII. 

## Background Info
Refer to this Slack [thread](https://dsva.slack.com/archives/C022AC2STBM/p1648472805392699)

## Acceptance Criteria
- [ ] Remove all PHI from all LoROTA entries (COVERED UNDER TICKET ???)
       - ID numbers, DOB, last 4, contact info, EC, NOK
- [ ] On pre-check-in complete, remove the PHI from the LoROTA entry (leave the skeleton info) (NEW WORK, USE THIS TICKET)

## Tasks
- [ ] Deploy and test on staging.
