### ISSUE TITLE
Q2 Infrastructure -  Implement a proof of concept branch of the vets-website repo to manage autonomous dependencies.

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#39205]
## Problem Statement 
Create an environment where individual projects (apps) dependencies can be individually managed within our monorepo structure.

- As a VFS engineer, I want apps (and their dependencies) to be more siloed so I can better manage my own dependencies.
- As a VFS engineer,  I want  to be able to perform tasks such as testing and building my app autonomously from  the other apps in the repository.
- As Release tools team engineers, I want to manage a large system of dependencies so we can setup a controlled method of managing team dependencies.

## Hypothesis or Bet
Leveraging Yarn workspaces  allows for mora autonomous management of dependencies and scripts.  
*Setting the ground work for a  autonomous deployment*

## We will know we're done when... ("Definition of Done")
We have :
- [x] Workspaces has been turned on in Platform -> merged to main (production), and made available to teams on the allowlist; other teams can continue without disturbance
- [x] Linting rules for imports in place, suggesting use of @department-of-veteran-afairs/  to aid in team adoption of Yarn Workspaces 
- [x] Following successful beta confirmation, apps will be able to import using the @ department-of-veterans-affairs/platform/[directory]
- [x] node_modules folder to make sore their contents are consistent with the rule’s set up in the app’s package.json
- [x] Application code is siloed which allows for app level scripts/testing to be run

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed - NA*

## Projected Launch Date
**Deploy schedule (hand-off date)**

**BASE**
- [x] Launch July 29 (prior to daily deploy)

**PLATFORM**
- [x] August 3- Landing pages
- [x] August 8 - Start up
- [x] August 11 - Utilities
- [x] August 16 - Polyfills
- [x] August 19 - Static Data

_Test (2 days)to determine if we can do a global _release_ for the remaining_

- [x] August 24 - forms / forms-system [hand-off date]
- [x] August 29 - monitoring [hand-off date]
- [x] September 1 - site-wide [hand-off date]
- [x] September 5 - testing [hand-off date]
- [x] September 7 - user [hand-off date]

**APPS**
*3 beta apps and 1 interested app
*Apps that are already on the allowlist
*Apps that are NEW to the allowlist

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. 
**Test Skipped:** _As the installation of yarn workspaces merely establishes a scaffolding for developers to work within,  the only germane usability test is to ensure that our installation does not affect non-participating apps/teams' current functionality (other than a lint warning, suggesting adoption of the new import methods). [This has been confirmed].  Running a successful test = NO change. RTT does plan monitor beta testing teams, once they start, to make sure everyone's work is not adversely affected during the adoption process._
               - [ ] ... and issues discovered in usability testing have been addressed. _NA_
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching _Tested to ensure these changes do not negatively impact other apps/teams. Running a successful test = NO change._
- [x] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD __Tested to ensure these changes do not negatively impact other apps/teams. Running a successful test = NO change.__

### ... documented?

- [x] New [documentation](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2210988078/Yarn+Workspaces+POC+implementation+procedure) is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2210988078/Yarn+Workspaces+POC+implementation+procedure)
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [x] External-facing: a [User Guide on Platform Website] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)_ exists for this product/feature tool _NA_
- [x] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings) _NA_

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
Given that the generalized purpose for implementing Yarn Workspaces is to provide more autonomy to apps/teams, we plan for tracking two types of metrics: _quantitive and qualitative_:
* The **quantitative** metric will be *(adoption)* the measure of how many apps on the allowlist are utilizing yarn workspaces. 
* There will be two **qualitative** metrics : 
	* *(negative)* the count and weight of any side-effect issues occurring _outside_ the app/workspace. This is defined by a change in a workspace config negatively affecting functionality outside of itself. Example: Adding workspace/package.json to an app caused a different app to fail CI.
	* *(positive)* the count and weight of useful tasks/scripts facilitated by the workspace.  Example: (possible scenario) separating the build process of an app from a (main) full build process.  
* Create schedule/process for how we ensure that NO CHANGE has occurred when an app is added.
* For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). _All information included in this ticket_

### When you're ready to launch...
- [x] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Go/no-go notes

- [x] Uncheck the first testing item and explain why this was not done [explain 'no change' as the testing result and why this is important]
- [x] Success metrics. Include in the epic and product outline. 
We do not yet have quantitative metrics yet as we need app teams to join. We want to have 2 apps running in the workspace and are able to manage dependencies on their own successfully. Qualitative measurement is that after scaffolding has been added, the workspaces remain working (with directory to directory as we can control that). **LT added the metric to the measurement section -> also need to add to the product outline
- [x] Update to user facing documentation; Confirm if there is other user documentation that needs to be updated (on platform website)
- We are trying to get usability research done with this, but have been blocked by no feedback from VFS teams (we have tested internally with platform)
> teams not on the allowlist should not be able to use this
> if the existing install steps still work, then they do not have to change. but we want the user facing doc around guidance explaning what the user files are (directed towards the VFS team engineer)
> we want VFS teams to stay on platform website ---- do NOT direct to 
*Where is the user facing documentation for this work? Confluence -> RTT -> Projects -> Yarn Workspaces
*Need to be added to the platform website once we receive go ahead with go/no-go
*What is the sequence of roll-out? We need to determine the least confusing path forward? We need both the code change and the user-facing doc (platform website). Do we need documentation specific to apps on the allowlist? Is there a section for that on the platform website? We need clarification in the user facing documentation.

### Documentation
* **`Yarn Workspaces`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _[link to User Guide](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2210988078/Yarn+Workspaces+POC+implementation+procedure)_

### Testing

* **Usability test**: _NA; see testing info above_ 
* **Manual QA**: _NA; see testing info above_
* **Automated tests**: _NA; see testing info above_

### Measurement

* **Success metrics**: _Isolated dependencies are siloed to the app in which they are used (success metric to be measured upon app team adoption)_
* **Release plan**: _information included in this initiative ticket

**Comment by laineymajor** [comment]
Previous DoD:
- [ ] ~~A proof of concept repo with a minimum of 2 apps autonomously running in one branch. (MC: implementation of a workspace tooling)~~
- https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/40077
- [ ] A list of critical v non critical dependencies, with their deprecation status
- [ ] An execution of a removal plan for deprecated dependencies
- [ ] Developed automated deprecation tests for the critical dependencies ( confine this to platform code. for RTT)

**Comment by laineymajor** [comment]
@rmessina1010 are all of these tickets complete?

**Comment by laineymajor** [comment]
@rmessina1010 can you double-check to make sure this epic, and all related issues, are up-to-date? Thanks!

**Comment by rmessina1010** [comment]
This epic is complete and yarn Workspaces have been enabled for the repo  and platform. 
Note: Opened a maintenance epic  for adding  workspaces to VFS apps as requests come in [47479](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/47479)
