### ISSUE TITLE
Workshop nature of Research assistance to offer teams

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39209]
## Issue Description
Workshop what level of research assistance should be offered to Platform teams by SDT (Framing out prepared plans, playbooks)

---
## Tasks
- [x] Brainstorm potential options
- [x] Evaluate potential options

## Acceptance Criteria
- [x] [Listing of potential offerings](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1650027471391/1240de3d1ff3d761e3d8ed23485c4b90cf5a44cb?sender=u4397b715dc3690a417b71483) that SDT could provide to guide the Research efforts of Platform teams
