### ISSUE TITLE
Document Shared Responsibilities and Escalations

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39216]
## User Story
_"As an UX Researcher on the Governance team, I want to ensure that shared responsibilities and escalations are documented so that I know the scope of my duties and who to reach out to for assistance.

- Intended Audience: Governance Team
- Desired Outcome: Documented shared responsibilities and escalation procedures
- Due Date: N/A

## Description
Discussion on [Learn and Shadow VFS Research Review/Approval Process](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/35792) led to a plan for reviews and kickoffs. 

Additional background for [Collaboration Cycle - Transition VFS research activities to Platform](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32698) initiative

## New Artifacts 
[Shared Responsibilities and Escalation Procedures](https://vfs.atlassian.net/wiki/spaces/~76599512/pages/2157281418/Draft+-+Shared+Responsibilities+and+Escalation+Procedures)

## Tasks
N/A

## Acceptance Criteria
- [x] Confluence: Shared Responsibilities and Escalation Procedures document has been created.
- [x] Shane has reviewed
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
@chaseakirby Question now that I'm digesting this. This, at least for now, covers the shared responsibility between Shane and myself, plus escalation for research duties? Am I reading this correctly?

**Comment by chaseakirby** [comment]
@claytonzook Good question! I created this ticket from the comment discussion on ticket #35792 where you said "Now that Shane and I have discussed plans around escalation and shared duties for reviews/kickoff, it seems reasonable to write up that guidance - I'm not sure where, maybe in the Research Plan Review guidance?"
And I replied with this. 
"I agree that sounds like great guidance to write up. And I think it would make sense to be in the Research Plan Review guidance under a new child page titled something like "Shared Responsibilities and Escalation Procedures".
I think that it would make sense to make this the final task on this ticket as a capstone of sorts for the initiative."

We can change this ticket to align to whatever you think we should document. but that was the origin of this.

**Comment by claytonzook** [comment]
@chaseakirby Thanks! This all makes sense. I don't think any change is needed to the ticket, I just wanted to make sure I was understanding it.

**Comment by claytonzook** [comment]
@chaseakirby @shiragoodman Shane has reviewed and I have now removed "draft" from the name and moved the document to Platform products and services > Collaboration Cycle > Research Review > [Shared Responsibilities and Escalation Procedures for Research Review touchpoint
](https://vfs.atlassian.net/l/c/PAmeQnr0)

**Comment by shiragoodman** [comment]
@chaseakirby can you work with Clayton to get this closed out?

**Comment by chaseakirby** [comment]
@claytonzook Thanks Clayton! I took a quick look as well and added a couple of comments about links that seemed to redirect back to this same document.
Other than that, I think the content looks fine.

**Comment by claytonzook** [comment]
@chaseakirby I've updated the bad links

**Comment by chaseakirby** [comment]
@claytonzook Links look good! Closing this ticket!
