### ISSUE TITLE
[PM, Design, FE] My VA - Cerner Alert: Updates for long term Cerner facility additions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39218]
## Background
Per a conversation on the `#health-care-products-all-teams` Slack channel regarding the addition of Cerner facilities, Danielle Thierry referenced this **[Cerner document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/cerner.md)** from the `#vsa-public-websites` team.  On this document, we confirmed that the statement below is accurate, and this means that our dependency on the `isCerner` key-value pair is not reliable. 
- **NOTE:** We use this key-value pair today to determine whether or not we need to show the Cerner alert
>In an ideal world, when we fetch facilities that a user belongs to, there should exist a key-value pair on them that is `isCerner: true/false`. However, we have noticed that every facility that has migrated to Cerner is still showing `isCerner: false`, which is incorrect.
>Since that `isCerner` flag is unreliable, we have resorted to maintaining a list of Cerner facility IDs both in `vets-website` as well as on Flipper with `cerner_override_{facilityID}` (to test various environments before launching).

Slack response:
<Details>

>**Dave Conlon  (3/25/22)**
>@ Heather Justice (and @ Trent McDole please correct me if this is wrong) I think that, for at least the moment **that statement is true** *and* that there is the addition of another statement that another "list" of health care systems and their relevant EHRM is maintained in Drupal to facilitate the right experience for the VAMC product.
>We have in our backlog a means by which we would like to change how that key-value pair is managed (Drupal) and eliminate the need for flipper.
>We were unable to execute on this in time for the contract change and the in-flight needs of testing Walla Walla.
>
>**Dave Conlon  (3/28/22)**
>The next facility go-live is April 30 which is completing Columbus, and then June 11 for Roseburg.
>We'll be switching technologies as to how this is managed across the board, so rather than work off of the old, let's concentrate on the new with the new teams.
>
>So we'll want to coordinate, instead, with the CMS team and how we're looking to have Drupal become the SSOT for "what facility uses what EHRM" and there will be different modes for staging/prod. So let's make sure that we connect y'all with the right team.
>In the meantime, @ Linda Li, can we update the runbook for the Cerner Cutover to include coordinating with the MyVA team. We might need to revisit the work they did this past weekend in order to not run into anything too bumpy for Columbus completion.
>cc: @ Kevin Walsh
>
>**Kevin Walsh (3/28/22)**
>The [VA.gov](http://va.gov/) CMS supports 3 different values for each system’s EHRM
>- VistA | vista
>- Converting to Cerner | cerner_staged
>- Cerner |  cerner
>
>Currently, we have 138 VAMCs set to VistA, and two set to Cerner (Walla Walla and Spokane). None are set to “Converting to Cerner”, but we can set that for Columbus and Roseburg.
>Currently, this EHRM data in the CMS is only available via a GraphQL query during a content-build content release.  But we intend to make this available in a json file to other consumers (probably stored at [www.va.gov/cms-data/ehrm.json](http://www.va.gov/cms-data/ehrm.json)), hopefuly in April in time for the rest of Columbus’ launch, but certainly in time for Roseburg. >[Here’s our issue to track that work](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7860).

</Details>

Therefore, we need to coordinate with the Public Websites team - ([Their ticket #7860](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7860)) to update our logic to integrate with their data, so that we can display the Cerner alert appropriately (and dynamically?).  We will also need to revisit the copy to see if we want to display the health system or a list of the facilities within the health system.  

## Tasks
- [x] Coordinate with Public Websites team on facilities logic
- [x] Implement updates to logic per guidance in and in coordination with #7860
- [x] Review/update copy for Cerner facilities as they are added long-term

**Comment by tmitchellgcio** [comment]
The public websites team mainly does not want to release the changes they want to make without making sure we don't need to make changes to our code. They will want all of us to test it thoroughly before it's released. If I understood correctly they are working on a better solution than that js file and they will want to be sure our code won't notice the changes and still work. It also sounded nothing will change on our end unless testing proves otherwise. I will say we should discuss that the flag is reliable thanks to the JS file which is good and might allow this not to be permanently hardcoded in the way it currently is, however our code only shows the location information which isn't part of the facilities call meaning we would likely have to do something similar to their JS file in order to get the location information unless this is something Lihan could add. It would be good in my opinion to only show the facilities they are attached to. They even mentioned in the meeting if we keep it up that is going to be a huge notification which it already is.

**Comment by ajakabcin** [comment]
Scheduled time with folks from Public Websites team for Tuesday 5/3 at 3pm edt to discuss their solution further and nail down a testing strategy.

**Comment by ajakabcin** [comment]
Met with Public Websites team to discuss testing. The process should be fairly straightforward and the PW team will let us know when they're ready for us to test on staging. Timing is tbd, but ideally in time for the next facility onboarding in June ([White City/Roseburg](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39125), and [Roseburg](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40065))
