### ISSUE TITLE
Design | Adjust Copy on 686 Confirmation Screen

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#39225]
## Background
A slight change to the destination of where the Veteran can go to check their claim status has been brought up and it amounts to adjusting some copy on the confirmation screen.

## Considerations
Per https://github.com/department-of-veterans-affairs/va.gov-team/issues/39026

The third section of the subway map on the 686 confirmation page has bee re-written to direct users to the claim status tool: [(Link to XD mockup)](https://xd.adobe.com/view/88794e80-ae26-4f3e-509e-94d09eb571f7-fe48/screen/85157fc6-68fe-4a6b-bc76-b499c56283af/)

The text has been changed to read:

>**Check your VA claim or appeal status**
>
>Sign into VA.gov and click the [Check your VA claim or appeal status](https://www.va.gov/claim-or-appeal-status/) link on the homepage. This will take you to a page that lists all your claims and appeals and shows where we are in processing them.
>
>Please note: Your application status may take some time to appear on our Claim Status Tool. If you don’t see it there right away, please check back later.

## Tasks
- [ ] Adjust copy to the above, with url

## Acceptance Criteria
- [ ] Copy has been adjusted
- [ ] A PR has been requested for merging

**Comment by tblackwe** [comment]
This change was never implemented in front end. Need to discuss with research/design if we should move forward with this change. accepting into backlog for more discussion.

**Comment by sortizsh** [comment]
@juliepedtke  + Daniela can you take a look at this

**Comment by djones2113** [comment]
@jstrothman do you have any insight into how migrating XD files to Sketch has been handled in the past? It looks like the current designs are in XD but assuming that the copy changes need to be made in Sketch, I'm not sure if there is an import process that has been used in the past or if we need to recreate the designs in Sketch. No problem if you don't know--I can do some investigating if not!

**Comment by jstrothman** [comment]
@djones2113 I'm not sure--I'd recommend searching DSVA slack for posts about XD files and then asking in #design

**Comment by djones2113** [comment]
One question that will help me understand the goal of this copy adjustment: What is the perceived benefit of changing the place to check on benefits from the current instructions (my VA) to the claim status tool?

One change that could be helpful (if possible) to the proposed copy is providing a timeline for the second part of the instructions in Step 3:

“Please note: Your application status may take some time to appear on our Claim Status Tool. If you don’t see it there right away, please check back later.”

How long should they wait before assuming that there might be an issue? If the application status doesn’t appear by x amount of time, who should the Veteran contact with questions?

**Comment by djones2113** [comment]
Hi @jstrothman following up on your comment from earlier this week, what are your thoughts on how we should move forward given that it sounds like the change recommended in this ticket is no longer relevant?

**Comment by jstrothman** [comment]
@djones2113 @tblackwe Requests below. 
We're going to follow the pattern of the [Disability > How to file a claim page](https://www.va.gov/disability/how-to-file-claim/) section on after you file a claim.

Mock-up here & in [mock-up in Sketch](https://sketch.com/s/19d4f404-e713-4034-9722-0ab2866e310d), words pasted in below.
<img width="734" alt="Confirmation screen" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1080991/ceb404c2-8e11-4aaf-94f6-02cfe685e9f7">

### Under How can I check the status...

- Replace the process list with the secondary action link to `Check your VA claim status` (link: https://www.va.gov/claim-or-appeal-status/ )
- See the example & link on /disability/how-to-file-a-claim
- The “Please note” text is retained from the current process list.

### Under How will I know if my application...

- This text is edited to add the sentence about downloading the decision letter in the claim status tool, with a new paragraph for `If you check...`

We’ll send you a packet by U.S. mail that includes details of the decision on your claim. You can also download your decision letter in the [claim status tool](https://www.va.gov/claim-or-appeal-status/ ).
If you check your status online and see a decision, please allow 7 to 10 business days for your packet to arrive before contacting a VA call center.

### Under What if I need to add or remove another...
Two changes here:

1. link the word “form” along with the form number
2. Add a comma after the phrase “your family status change”

**Comment by jstrothman** [comment]
We're not certain the letters are available in the claim status tool, so I updated the mock and language changes described above. This is ready for changes to be made on the confirmation screen
