### ISSUE TITLE
Cloud Isolation - Develop required CIT infrastructure

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39235]
## Problem Statement 
Prototyping requires infrastructure support, and infrastructure is in flux as it moves to EKS. Developer support is incomplete due to credentialing and onboarding requirements. Tooling may be need to support development. 

How might we develop the infrastructure required to test and validate our approach while adjacent systems are evolving?

## Hypothesis or Bet
Tracking infrastructure tasks and maintenance will allow us to reach a steady state where developers can be productive.

## We will know we're done when... ("Definition of Done")
- [x] Developers have access to the systems that they need.
- [x] Infrastructure architecture supports CIT prototyping and MVP efforts.

## Known Blockers/Dependencies
NA 

## Projected Launch Date
June 21, 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. **NA. No user-facing features.**
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching. **NA**
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD. **NA**

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide). **NA**
- [x] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0).
    * _List the existing product that this initiative fits within, or add a new product to this list._ **Applicaton Hosting and Deployment using Container Orchestration (EKS), Platform User Credentials, Synthetic Monitors**
- [x] Internal-facing: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool **NA**
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings) **NA**

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. **NA. No measurable metrics.**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). **NA**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: Cloud Isolation Team
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525
* **User Guide**: NA

### Testing

* **Usability test**: NA
* **Manual QA**: NA
* **Automated tests**: NA

### Measurement

* **Success metrics**: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
* **Release plan**: NA

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by alwerner** [comment]
@mchelen-gov Status update: Completed

This initiative was completed in Q2.
