### ISSUE TITLE
Cloud Isolation - Prototype and test POCs in DEV Env

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39234]
## Problem Statement 
Rapid prototyping and testing in the DEV environment will be necessary so that we can validate our POV.

How might we "fail fast" to arrive at an approach for decoupling vets-api and Lighthouse?

## Hypothesis or Bet
Because "spike work is not always a straight line," quick pivots in approach may be necessary to confirm and reinforce theories for developing a full-fledged MVP.

## We will know we're done when... ("Definition of Done")
- [x] Team has centered on an approach that will serve as the basis for an MVP.
- [x] ADR(s) (architectural decision record) has been socialized with appropriate teams. 
- [x] Development timeline is created. 
- [x] Prototype and tests suggest that the routes in the DEV environment exist and are functional.

## Known Blockers/Dependencies 
NA

## Projected Launch Date
June 21, 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. **NA. No user-facing features.**
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching. **NA**
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD. **NA**

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide). **NA**
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0). **NA**
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool. **NA**
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings). **NA**

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. **NA. Research initiative.**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). **NA**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: Cloud Isolation Team
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525
* **User Guide**:
    * [RFCs](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2166751347/RFCs)
    * [ADR - New domain to serve vets-api](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2221572288/2022-06-06+New+domain+to+serve+vets-api)
    * [ADR - Reroute vets-api upstream requests to Lighthouse](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2220785993/2022-06-06+Reroute+vets-api+upstream+requests+to+Lighthouse)

### Testing

* **Usability test**: NA
* **Manual QA**: NA
* **Automated tests**:

    **POC: Single Facility** (vets-api > Kong via fwdProxy)
    Datadog: https://vagov.ddog-gov.com/synthetics/details/p57-srx-nj5
    Route: https://dev-api.va.gov/facilities_api/v1/va/

    **POC: List of All Facilities w/ Location Info** (vets-api > Kong via fwdProxy)
    Datadog: https://vagov.ddog-gov.com/synthetics/details/k6s-exf-asn
    Route: https://dev-api.va.gov/facilities_api/v1/va/vba_354b

### Measurement

* **Success metrics**: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
* **Release plan**: NA

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by alwerner** [comment]
@mchelen-gov Status update: Completed

This initiative was completed in Q2.
