### ISSUE TITLE
Remove deprecated offerings and place elsewhere for historical reference

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39244]
## Issue Description
Products that are no longer offered need to be retained for reference but not presented under current offerings, removing confusion.

---
## Tasks
- [x] Determine where deprecated items should go
- [x] Create appropriate page/section and populate it with current data

## Acceptance Criteria
- [x] An archive of deprecated offerings will exist for reference.
