### ISSUE TITLE
[Combined Debt Portal] Research Plan V2

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#39249]
## Issue Description
The Combined Debt Portal's research plan was reviewed for feedback on the recruitment criteria. This ticket captures the updates to the research plan based on the gathered feedback

---
## Tasks
- [x] Create a diagram of the screener questions so Perigean can visualize what answers lead to different groups
- [x] Update the screener questions based on the diagram 
- [x] Update the primary and secondary demographic criteria 

## Acceptance Criteria
- [x] The research plan has been updated and linked in this ticket

**Comment by rileyorr** [comment]
The feedback has been incorporated into [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-plan.md). 

@denisecoveyduc tagging you as a heads up that I added this ticket to the sprint!
