### ISSUE TITLE
Console UI: Catalog Onboarding of Platform Teams

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#39246]
## Problem Statement 
How might we help Platform Development teams to fill the Console with useful content + functionality so they can increase VFS teams' satisfaction when interacting with the Platform?

## Hypothesis or Bet
By onboarding Platform teams to the Console to increase value + address VFS user pain points through the Console, Platform teams will be better prepared to extend the usefulness of the Console.  This creates a centralized Platform site for VFS users to engage with Platform products in a positive way.

## We will know we're done when... ("Definition of Done")
Catalog Onboarding process documentation, and completed onboarding for at least 5 platform teams by end of Q2.

## Known Blockers/Dependencies 
Platform teams would need to be available to engage with the Console UI onboarding team

## Projected Launch Date
Catalog onboarding process + documentation will be release throughout the quarter, 5 teams should be completed onboarding by June 2022

## Launch Checklist
- [ ] Process documentation from the CUI team for onboarding (1. how to get on to the Console Catalog, 2. users + 3. how to create a plugin if applicable)
- [ ] Onboarding templates: may include questionnaires templates, planning templates, interview artifacts, etc
- [ ] Completed onboarding documents for up to 5 Platform teams
- [ ] Evaluation of 5 onboarded Platform team's readiness to contribute to the Console

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended 
    - [ ] Testing of documentation for how to get on to the Console Catalog
    - [ ] Testing of documentation for users
    - [ ] Testing of documentation for how to create a plugin if applicable
    - [ ] Testing of Onboarding templates

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2161476529/Product+Outline+Console+Catalog+Plugins)
- [ ] Process documentation from the CUI team for onboarding (1. how to get on to the Console Catalog, 2. users + 3. how to create a plugin if applicable)
- [ ] Onboarding templates: may include questionnaires templates, planning templates, interview artifacts, etc

### ... measurable

- [ ] Completion of 5 Platform team's onboarding documentation
- [ ] Catalog entries count before and at the end of Q2
- [ ] User count before and at the end of Q2
- [ ] Plugin count before and at the end of Q2
- [ ] Satisfaction readiness of the 5 platform teams
- [ ] Google Analytics traffic + interaction related metrics

### When you're ready to launch...
- [ ] Publish documentation to Confluence 
-- [ ] Publish + Announce **https://vfs.atlassian.net/wiki/spaces/CUI/pages/2098004015/Logging+into+the+Platform+Console+-+Instructions**
-- [ ] Publish + Announce Process documentation from the CUI team for onboarding (1. how to get on to the Console Catalog, 2. users + 3. how to create a plugin if applicable)
-- [ ] Publish + Announce Onboarding templates: may include questionnaires templates, planning templates, interview artifacts, etc
-- [ ] Publish + Announce Evaluation of 5 onboarded Platform team's readiness to contribute to the Console

### Documentation
* **`Platform Console`**: 
* **Product Outline**: [_link to Product Outline_]()
* **User Guide**: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2035777580/Console+Operational+Product+Documentation
(list all guides for platform developers)

### Testing

* **Usability test**:  Review by each VFS of their own onboarding documentation
* **Manual QA**: Review by a non-author of the documentation for completeness
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: 5 VFS team documentation for onboarding on the console catalog
* **Release plan**:  n/a, published on Confluence
