### ISSUE TITLE
Q2 2022 Console UI: UI Improvements including VA Design System Alignment Research

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#39256]
## Problem Statement 
How might we create a consistent, trustworthy and accessible user experience for VFS users, and build a flexible scalable Console Design System VA Subset + component library to satisfy the needs of platform developers contributing to the Console?

## Hypothesis or Bet
By creating a combined list of Backstage's Material UI design system with a subset of the VA Design System and building custom components specifically for Console users, we can create a Console design system that provides a consistent user experience, increases user trust, and enables developers to build on the Console more easily.

## We will know we're done when... ("Definition of Done")
1. We have documented a list of developer users preferences + needs design system components through secondary research in order to justify use of components and styles
2. We have documented definitions of design system + component recommendations from Material UI, VA Design System and custom components
3. We have documented the process of utilizing the Console's choice of components + styles for platform developer users to build plugins and other contributions to the Console
4. We have a WCAG 2.0 AA accessible site in the dev environment by the end of the quarter, with a continuous automated accessibility report

## Known Blockers/Dependencies 
- Broken components in the VA Design System 
- We may be dependent on Backstage for approval of permanent fixes for accessibility
- Recommendations from Product Leadership and Design System team may not align with our recommendations for Console users + contributors

## Projected Launch Date
All tasks in this initiative to be complete by the end of Q2.

### ... tested?

- Accessibility: WCAG 2.0 AA compliance audit to be completed
- Console Design System VA Subset: Tested utilization of the identified Subset components with platform developer users in the user guide

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] list of developer users preferences + recommendations through UX research
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2170650683/Console+Design+System+VA+Subset+-+Product+Outline)
- [ ] Process of utilization of Console Design System VA Subset  + component library for platform developer users to build plugins and other contributions to the Console (https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2170650683/Console+Design+System+VA+Subset+-+Product+Outline)

### ... measurable

- [ ] Automation in auditing WCAG 2.0 AA compliance

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **Platform Console**: https://github.com/department-of-veterans-affairs/platform-console-ui
* **Product Outline**: [_link to Product Outline_ (https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2170650683/Console+Design+System+VA+Subset+-+Product+Outline)
* **User Guide**: TBD- for the Console Design System VA Subset [_link to User Guide_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2035777580/Console+Operational+Product+Documentation)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**:  Accessibility 

### Measurement

* **Success metrics**:  WCAG 2.0 AA compliance (add report or ticket)
* **Release plan**: _link to Release Plan ticket_

**Comment by mchelen-gov** [comment]
Where are the output artifacts from this Initiative?
