### ISSUE TITLE
Q2 2022 Console UI: Console Feedback, Analytics Planning + Setup (GA, Domo, Medallia)

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#39253]
## Problem Statement 
How might we measure the user activity, identify pain points, and assess the overall usage and user satisfaction of the Console and its functionality? 

## Hypothesis or Bet
By identifying and implementing Google Analytics and Medallia feedback mechanisms that form part of a broader monitoring and evaluation strategy, we hope to assess both Platform and VFS users' satisfaction and pain points in order to improve the use and viability of the Console as a central hub for Platform services + support.

## We will know we're done when... ("Definition of Done")
1. We will have created a list of what we want to collect metrics and feedback on in order to assess user activity, and assess Console usage in it's current state. This list will align with a broader monitoring and evaluation strategy for the Console. 
2. Google Analytics will be installed and a first draft dashboard will display results associated with the analytics plan for the Console. If it is determined that a Domo dashboard is needed, this should be evaluated for date of completion,.
3. Medallia will be installed and a first draft dashboard will display results associated with the feedbacks plan for the Console.

## Known Blockers/Dependencies 
NA

## Projected Launch Date
Implementation of Google Analytics and Medallia and a useful dashboard should be available to the Console UI team by the end of Q2 2022.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* *Platform Console**: 
* **Product Outline**: [_link to Product Outline_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP)
* **User Guide**: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2035777580/Console+Operational+Product+Documentation

### Testing
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to the Console GA dashboard TBD_
* **Release plan**: _link to Release Plan ticket TBD_
