### ISSUE TITLE
Console UI: CLI (Command Line Interface) Prototype

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#39255]
## Problem Statement 
How might we allow platform developers who want to contribute to the Platform Console use a tool to enhance the Console in a fast, efficient manor, rather than use a UI?

## Hypothesis or Bet
By creating a Command Line Interface for the Console, platform developers could easily use scripts and automate batch files, speeding up the completion of their tasks. The speed and efficiency in which a CLI works can improve the Platform Developer's productivity, leaving more time to solve other priority issues for VFS users

## We will know we're done when... ("Definition of Done")
User types are defined and Authorization is complete by Console UI in order for Access Management to complete work for the MVP.

## Known Blockers/Dependencies 
User types must be defined for the CLI (may include UX Research) and a plan for implementation is needed.

## Projected Launch Date
The CLI prototype currently exists, and work will continue in Q2 of 2022. At the end of Q3, Access Management should be completing the MVP.

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **Platform Console**: https://github.com/department-of-veterans-affairs/backstage-test
* **Product Outline**: [_link to Product Outline_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP)
* **User Guide**: [_link to User Guide_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2035777580/Console+Operational+Product+Documentation)

### Testing

* **Usability test**: TBD, repo https://github.com/department-of-veterans-affairs/test-oclif-console-cli
* **Manual QA**: TBD, see [Confluence documentation](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2062483852/CLI+-+Command+Line+Interface+-+Console+UI)
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: TBD, see [Confluence documentation](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2062483852/CLI+-
* **Release plan**: TBD, see [Confluence documentation](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2062483852/CLI+-

## TODOs
- [ ] xxx
