### ISSUE TITLE
Onboarding / Offboarding & Automation

### ISSUE THREAD

**Issue by mb365247** [department-of-veterans-affairs/va.gov-team#39252]
## Problem Statement 
Onboarding and offboarding a new user to a VFS/Platform team involves onboarding them to several different tools. Platform teams have done a good job of streamlining the process of onboarding to specific tools. We feel we could help take this to the next level by centralizing onboarding and offboarding.

**How might we** simplify the onboarding process for a new VFS team member to enable them to focus on the most important parts of their job?

## Hypothesis or Bet
By simplifying and centralizing VFS/Platform user onboarding, we hypothesize that we can reduce the time to first contribution (be it a doc on confluence, a commit to github, etc).

By simplifying and centralizing VFS/Platform user offboarding, we hypothesize we can reduce the time teams spend on manual offboarding tasks.

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
End of Q2

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

**Comment by annekerr49** [comment]
kjduensing - can we get a status update on this issue?  Last update was 5/9/2022

**Comment by annekerr49** [comment]
@kjduensing - Kevin we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues.  Please let me know if you have any questions.

**Comment by annekerr49** [comment]
@raywangoctova @kjduensing @FHiatt @mb365247 -  Platform Crew is having a DE Product Board meeting and I would like to be able to give a status update on the progress the team is making on this item.  Can you help? If not can you direct me to someone who can assist?

**Comment by kjduensing** [comment]
Hello @raywangoctova or @chrisj-gov, could you please clarify why I was recently assigned to this ticket? This was from our work on the Spike Teams initiative a few years ago - the team has since moved onto other projects, but I'm happy to provide any info I can.

**Comment by chrisj-gov** [comment]
> Hello [@raywangoctova](https://github.com/raywangoctova) or [@chrisj-gov](https://github.com/chrisj-gov), could you please clarify why I was recently assigned to this ticket? This was from our work on the Spike Teams initiative a few years ago - the team has since moved onto other projects, but I'm happy to provide any info I can.

Apologies Kevin! That was two people trying to unassign you simultaneously and one voiding the other! We're just doing some card cleanup.

**Comment by raywangoctova** [comment]
Chris and I were in a meeting reviewing old tickets. This one came up, and it was intended to be assigned to me for further review. Matt took your name off at that time, and somehow, Chris added you back by accident I assume. We discussed this as part of the Spike team effort that is no longer active.

**Comment by kjduensing** [comment]
Ah no worries all, just seeing if I could help! Thanks for clarifying
