### ISSUE TITLE
Add VA.gov Overview Video back to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39250]
## User Story
As a VFS team member, I want to watch the VA.gov Overview video as part of Platform Orientation, so that I can better understand the VA.gov landscape.

- Intended Audience: VFS Teams
- Desired Outcome: Va.gov Overview video is available on Platform Website
- Due Date: TBD

## Description
When we launched the new design of Platform Orientation on Platform Website, we accidentally dropped the VA.gov Overview video. The purpose of this ticket is to add the [VA.gov Overview video](https://www.youtube.com/watch?v=0cc-VdfI4Q8) (currently hosted on the Platform YouTube page) back to the Platform Orientation materials on Platform Website. 

_Additional background for [Launch new Platform Orientation](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/13709) initiative <br />_

## Artifacts Needing Updates
[Platform Website: Platform Orientation Purpose](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)
[GitHub: New VFS Team Member Orientation Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)

## Tasks
- [x] Add Video link to Platform Website Orientation Purpose (Instructions sourced from ticket [#29725](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/29725))
  - Go to https://youtu.be/0cc-VdfI4Q8
  - Click "Share"
  - Click embed
  - Click "Copy"
- [x] Update link in New VFS Team Member orientation ticket

## Acceptance Criteria
- [ ] New VFS Team Member GitHub template has been updated
- [ ] Platform Website: Platform Orientation Purpose on Platform Website has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby please update

**Comment by chaseakirby** [comment]
@shiragoodman @CherylEvans 
Hi Shira, Cheryl and I worked through this ticket this morning.
For the Overview Video; we noticed that previously on Platform Website it was only a link but there was discussion around embedding it.
We attempted to embed the video using an iframe (Scroll Viewport says that iframes are supported so we thought we would give it a try), and added a link underneath for if the iframe doesn't load. There's no preview functionality for how Platform Website will generate this so I was planning to check soon after 12 and see what it looks like. 
[Platform Website: Platform Orientation](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)
Cheryl and I also updated the [GitHub template in PR #39733](https://github.com/department-of-veterans-affairs/va.gov-team/pull/39733) that is ready for your review.

**Comment by shiragoodman** [comment]
@CherylEvans this looks good to me. I saw you merged the PR. I'm going to close!

**Comment by CherylEvans** [comment]
Thank you!! :-)

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

203-580-3529 | ***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member
