### ISSUE TITLE
Q2 2022 Console UI: Implement Access Control and establish best practices (AMT Solution)

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#39257]
## Problem Statement 
How might we create security and role-specific permissions for the Console, the Console Catalog and it's plugins.

## Hypothesis or Bet
By implementing the zero-trust-architecture from the Access Management Solution, along with it's framework with plugin-related tools that VFS users would be using with Platform teams' plugins, both Platform + VFS users will have a simple, secure authorization and authentication experience with the Console + it's plugins.

## We will know we're done when... ("Definition of Done")
Users are able to login via Login.gov, see appropriate content + actions as defined by at least 3 user types, and the implemented plugins (number is TBD, dependent on PLatform teams' readiness)

## Known Blockers/Dependencies 
Access Management Team's work

## Projected Launch Date
There is no expected launch date to support, but there may be launch dates for Platform Development teams launching their services to the Console MVP.

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching

### ... documented?

- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)

### ... measurable
- [x] # of users successfully logged in during the quarter on Dev enviro, # of sessions
![Screen Shot 2022-07-14 at 4.55.19 PM.png](https://images.zenhubusercontent.com/6189530b9b3a59065d894c28/2078248c-554e-4a32-a44f-8e7066ee5069)
Number of User sessions via GA4, April 1 through June 30th (2nd quarter), Appendix section
https://vfs.atlassian.net/wiki/spaces/CUI/pages/2239037489/Google+Analytics+Console+Health+Metrics+Data+Studio+Report+-+Console+UI

### When you're ready to launch...
- [x] Conduct a [go/no-go] : This is a pilot in dev + utility, not required

### Documentation
* **Platform Console**: https://github.com/department-of-veterans-affairs/backstage-test
* **Product Outline**: [_link to Product Outline_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP)
* **User Guide**: [_link to User Guide_](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2035777580/Console+Operational+Product+Documentation)

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_ < this feature is dictated by Login.gov and cannot be changed
* **Manual QA**: _link to GitHub issue or documented results_

### Measurement

* **Success metrics**: see "measurable"
