### ISSUE TITLE
Experimental Design Process Final Phase - Feedback Button

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39267]
## Issue Description
_We participated in an experimental design process as part of our effort to move the Medallia Feedback survey button. Post implementation, there is a final phase and closure of this process._

---
## Tasks
- [x] _Verify requirements to complete the final phase of the experimental design process_
- [x] _Complete any outstanding requirements and finalize closure_

## Acceptance Criteria
- [x] _All experimental design process requirements for the feedback button are met and process is closed_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
I confirmed with Naomi that previous research and quantitative data will suffice in closing out the experimental design process.

I'll compile a confluence doc and determine the next steps.

**Comment by ianMcCullough-ob** [comment]
Update: need to fill out this [templated ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_components/experimental-design-template.md) to add the button to the design system. After that will check in with the council.

**Comment by jwoodman5** [comment]
Confluence doc with backing data is [here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2163900472/Medallia+Button+Relocation+Validation?src=mail&src.mail.action=view&src.mail.notification=com.atlassian.confluence.plugins.confluence-notifications-batch-plugin%3Abatching-notification&src.mail.recipient=8a7f80897602a664017619eff0680827&src.mail.timestamp=1650894134337).

**Comment by humancompanion-usds** [comment]
@ianMcCullough-ob - The updated pattern has been deployed: https://design.va.gov/patterns/feedback

The a11y considerations are still a placeholder. You [mentioned](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/892#issue-1241841796) you'd be checking with an engineer. Is that still happening? I'd like to get the a11y considerations added before we can close this out.

**Comment by ianMcCullough-ob** [comment]
@humancompanion-usds thanks for the update! And yes, our FE is working on the accessibility update. I'll get that to you by EOD

**Comment by ianMcCullough-ob** [comment]
@humancompanion-usds, here is content for the accessibility section, provided by @aubreyarcangel. Let me know if you have any questions.  

- Specify `type="button"` for <button>
- Use  `aria-label` to inform assistive technologies about the action of the <button>
- Don’t use `disabled` state for <button>
- Keep <button> labels as short as possible and use words that will describe what will happen when button is clicked
- Testing: spacebar and enter key should be able to trigger clickable action of the <button>

**Comment by ianMcCullough-ob** [comment]
This has been added to the design system: https://design.va.gov/patterns/feedback
