### ISSUE TITLE
[Design] Provide Link to Start Check-in from Pre-Check-in when Accessed on Day of Appointment

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39260]
**LP: I am not sure I understand the use case and workflow for this one**

## User Story
As a Veteran, I want to be able to easily access the check-in experience on the day of my appointment, so that I can check in for my appointment.

## Background
This is closely related to #37544. In a discussion with @stephenBarrs just now, we wondered if it would make sense to show a link/button that will open the SMS client with "check in" pre-filled (same link as the poster QR code) on the page being created in #37544. If/when implemented, the link should also create an analytics event so that we can easily know how often veterans are accessing pre-checkin on the day of their appointment.

## Wireframes
TBD

## Tasks
- [ ] Finalize detailed mockup and callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by ytsaoca** [comment]
Created this Mural for brainstorming: https://app.mural.co/t/vfscie8528/m/vfscie8528/1649366237889/5c7791fe3ad70cccc71db888c26f509b3c03a1c7?sender=u70b8b2930b03d3ef317d2520
