### ISSUE TITLE
DOMO Dashboard - Search Custom Medallia Survey

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39268]
## Issue Description
_We implemented a custom Medallia feedback survey for the search team and now need to build them a dashboard in DOMO to make their survey response data more readily available. Their survey is very similar to the standard feedback survey with only slight wording changes, so we will use the standard dashboard is the model_

---
## Tasks
- [x] _Create a new DOMO dashboard modeled after the Feedback survey section of the standard Medallia dashboard_
- [x] _Import historical data to-date_
- [x] _Verify data completeness and accuracy_

## Acceptance Criteria
- [ ] _A new DOMO dashboard with survey responses for the custom Search feedback survey is accessible in DOMO_
- [ ] _The Search survey DOMO dashboard displays all historical, applicable survey response data_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[DOMO MVP](https://va-gov.domo.com/page/1790948826)
