### ISSUE TITLE
[SW-Content] Create new tier 1 page in drupal for transferred entitlement for family members

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39271]
## Resources
Please review the following work orders and attached word document
#38853
#37658

[https://app.zenhub.com/files/133843125/176771cd-478b-4823-9927-1bb708d2e405/download](https://app.zenhub.com/files/133843125/176771cd-478b-4823-9927-1bb708d2e405/download)

## Tasks
- [x]  Compose Tier 1 Drupal page "Transferred entitlement for family members page
- [x] Place placeholder text where the Apply button will be on the page for now
- [x] Save in Draft in Drupal
- [ ] Submit for content and copy editing review

## Acceptance Criteria
** Final document is available and ready for OCTO review in Drupal

**Comment by bethpottsVADEPO** [comment]
@lunascoop It looks like the Word attachment in Stan's comment here didn't upload, so I uploaded it above under resources.

**Comment by lunascoop** [comment]
@psanders86 a draft version of this page is ready for review.
Transferred entitlement for family members: http://preview-prod.vfs.va.gov/preview?nodeId=44698

**Some notes:**

- Most of the language in the Word doc originally comes from the When can they use the transferred benefits? section on the [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) page. I did tweak it a bit and removed some content. (Ex: I removed "or has reached 18 years of age" from the second bullet in the **If you're a child and you've received transferred entitlement** section. If a dependent child has to wait until after the service member has finished at least 10 years of service to use the benefits, the service member should be well over 18 years old).
- Added page intro: Language like "advance your education and training" was taken from the [How to use your GI Bill benefits](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/) page.
- Added section on what benefits can I get? This section is fairly common in the education hub and I reviewed the form for the content.
- In the eligibility box, changed "(the next section here tells you when you can use transferred benefits)" in the last bullet to an anchor link to that specific section.
- For the How do I apply section: Added link to online tool that can be found on the form detail page. I know the checkbox in the description says it should be placeholder text. Also added content for applying by mail. Formatting taken from [How to apply for burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page. Content taken from form itself.
- Kept H2s as questions vs. statements. I think we're moving away from formatting H2s as questions, but wasn't sure if this should be done for this page. 

Let me know if you want to sync up about this.

**Comment by SgardnerPMP** [comment]
See review Ticket #39626
