### ISSUE TITLE
[UX] Update Release Product Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39279]
## Description
Update various product assets, as necessary, based on changes to the product for the change from using last 4 to DOB. Just this change, no other product features included.

## Tasks
- [ ] Create new Demo video
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [x] Update the Poster
- [x] Update user flow diagrams, as necessary
- [x] Push changes to the appropriate GitHub files
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov
- [x] Notify the Contact Center of the changes (follow this [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))
   - Create demo video & transcript
   - Create the CC GitHub ticket and attach video & transcript & links to guides
- [x] Notify Training of the changes (Shawn Adams, Cheryl Wills, Farah Ford)

## Acceptance Criteria
- [x] Product Guides are up-to-date (content & screenshots)
- [x] Poster is up-to-date
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [ ] R&D articles are up-to-date (mention in this [thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44692#issuecomment-1194265615))
- [x] Contact Center is aware of the changes
- [x] Training is aware of the changes

**Comment by loripusey** [comment]
@benbrasso-agile6 I'm moving this back to Ready for Dev since we are blocked

**Comment by benbrasso-agile6** [comment]
@ytsaoca Can you help update the following user flows? #2 is the one I need the soonest. Thanks. 

1. 
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=4d0369ce-7ad6-47b1-9bc3-c40521fe7ef7&mode=design

Last 4 SSN needs to change to Date of Birth DD/MM/YYYY

Make sure to update, "Sorry, we couldn't find an account that matches your last name or SSN. Please try again." Should update it to, "Sorry, we couldn't find an account that matches your last name or DOB. Please try again." 

2. 
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=6419aab2-c5a1-43ec-b24e-10f95f0be244&mode=design

Same changes as #1. I need a png of this one, when complete. 

3. 
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=2f0e9189-7bf3-445f-b6b6-cea556ed8746&mode=design

Same changes as #1. 

4. 
https://share.goabstract.com/3d58748e-1359-4a5c-afc6-c8514ddc2a73?collectionLayerId=b1a0274d-9416-4fad-a663-882770c0f7af&mode=design

Same changes as #1. Also, needs new screenshot of log in page.

**Comment by benbrasso-agile6** [comment]
Just forgot, Ya-ching is traveling

**Comment by benbrasso-agile6** [comment]
https://drive.google.com/drive/folders/1c59S9fI3j8pW6FIc3GB4fu-poEeLT6sU

**Comment by loripusey** [comment]
Looks good

**Comment by benbrasso-agile6** [comment]
Updated product guides based on Contact Center feedback

**Comment by benbrasso-agile6** [comment]
For Ben: 

* I need to re-replace the pre check in user flow

**Comment by benbrasso-agile6** [comment]
Updated guides

https://drive.google.com/drive/folders/1c59S9fI3j8pW6FIc3GB4fu-poEeLT6sU

**Comment by zach-park** [comment]
User flows for CI & PCI are updated. And the png version is attached:
![Pre-check-in user flow (Read-only) for user guide.png](https://images.zenhubuserconteser flont.com/6155d02ed6dc2cbaa5d23b32/0da0c51e-76bd-4179-8178-5d6b014868ce)
@benbrasso-agile6

**Comment by zach-park** [comment]
![User flows are updated](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/65c2ea24-5a24-45b0-8e51-31a99c8906ec)

**Comment by zach-park** [comment]
User flows are updated: ![Pre-check-in user flow (Read-only) for user guide.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/c3b97ea6-6053-4d19-a4bb-13b2e6d8ec2f)

**Comment by zach-park** [comment]
Merged to the Abstract master branch. Collection links: 

Landscape view version:
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=4d0369ce-7ad6-47b1-9bc3-c40521fe7ef7&mode=design

Portrait view version:
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=6419aab2-c5a1-43ec-b24e-10f95f0be244&mode=design

**Comment by benbrasso-agile6** [comment]
Nice, Zach. Looks perfect.

**Comment by loripusey** [comment]
@kristenmcconnell @benbrasso-agile6 @loripusey Just a reminder for one of us to notify Danielle to update the  ["How to check in with your smartphone"](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) page when we release this and let her know that we are opening it up to more users each day over the course of a week

**Comment by benbrasso-agile6** [comment]
Yes, that's me. In the AC, there's a specific thread I'm communicating with Randi about for this Epic.

**Comment by benbrasso-agile6** [comment]
@benbrasso-agile6 needs to add the updates from telephone and type of care into these updates. Type of care folder is here - https://drive.google.com/drive/folders/18YrEyHu_Fi1C5dKODZJzjmC7CvvjyuX9

**Comment by benbrasso-agile6** [comment]
Product guides are re-upated. I added the updates from type of care & doctor name into the LoROTA produce guides since the contact center made changes to LoROTA. All set to add to git when we merge to main. 

https://drive.google.com/drive/folders/1c59S9fI3j8pW6FIc3GB4fu-poEeLT6sU

**Comment by loripusey** [comment]
I'll record a new demo video after we push to production

**Comment by loripusey** [comment]
Note: I'll create a new demo soon, closing this ticket without it.
