### ISSUE TITLE
[Design] Direct User How to Update their Contact, Emergency Contact, and Next of Kin Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39272]
## User Story
As a Veteran, when I am completing my pre-check-in workflow, if I have some updates to my contact, emergency, and/or next of kin information, I would like to understand how and where I can make those changes so that I will know what the next step is.

## Description
We need wireframes that will:
- Tell the user what to do and where to go to update their contact information
- Tell the user what to do and where to go to update their EC and NOK information
- Tell the user why it's important to have up-to-date information for them
- Tell the user they will need to fully log in if they choose to update their info via their VA Profile

## Workflow
- Given I
    - Am a Veteran who has received a link to complete pre-check-in for an appointment
- When I
    - Complete the pre-check-in process
    - Have answered "No" to one or more of these questions
        - "Is this your current contact information?" 
        - "Is this your current emergency contact?" 
        - "Is this your current next of kin?" 
    - Get to the "you've completed pre-check-in" screen
- Then I
    - See messaging that indicates how to update my information based on to which of the 3 questions I answered "no" 
        - For contact info
             - See messaging that tells me I can either update my info in my VA profile or with a staff member on the day of my appointment
             - See a link to my VA profile
        - For EC info
             - See messaging that tells me I will need to update the information with a staff member on the day of my appointment
        - For NOK info
             - See messaging that tells me I will need to update the information with a staff member on the day of my appointment
      - See messaging telling me why it's important to have up-to-date information for them
      - See messaging telling me that I will need to fully log in if I choose to update their info via their VA Profile

## Tasks
- [x] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] Clean up the wireframes (revert back to the non-editing wireframes)
- [x] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

##UX Delieverable (Sketch)
- [Need to update: Contact Info](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/5DFA07C6-623E-43BE-89F2-91055618C433): 
   (https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/5DFA07C6-623E-43BE-89F2-91055618C433)

- [Need to update: Contact Info (accordion expanded)](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/FFE5D9A7-468A-472E-BFFE-4C3AEC5E03F3):
   (https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/FFE5D9A7-468A-472E-BFFE-4C3AEC5E03F3)

- [Need to update: Contact Info & EC](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/7947FD37-A499-42B1-88C2-DAF7287FA2D6):
   (https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/7947FD37-A499-42B1-88C2-DAF7287FA2D6)

- [Need to update: Contact Info, EC, Kin](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/6A3FE162-1171-4750-B08A-59C756AFBF49):
   (https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/6A3FE162-1171-4750-B08A-59C756AFBF49)

**Comment by zach-park** [comment]
Tagging @niradatta1 for content design collab.

**Comment by niradatta1** [comment]
We've identified 2 to 3 options, which includes feedback from site-wide content team. Next (and last) step is to review with accessibility, scheduled this Wed 04/13.  We'll finalize the mocks after that meeting.

**Comment by niradatta1** [comment]
Based on our accessibility review,  we've reached a decision on the final content that will appear in the pre-check-in confirmation screen. @zach-park Will link to the final wireframe with the annotations for FE here. Will be including this in our translation document.  'cc @goldenmeanie @sarahknoppA6

**Comment by niradatta1** [comment]
@kristenmcconnell We need to confirm a discrepancy regarding the "need help" section of our mocks.

**Comment by zach-park** [comment]
@kristenmcconnell , I send a slack with more details. (cc: @niradatta1 ).
