### ISSUE TITLE
[SW-Content] Update payment amounts in the top row of DEA-Fry Comparison chart [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39296]
## Resource
[Survivor Dependent Benefits](https://www.va.gov/education/survivor-dependent-benefits/)
Beth Potts - if needed for detail information/guidance

## Task
- [x] Update payment amounts under DEA and Fry in the first row of the chart on
- [x] Have editor review updates
- [x] Save in Draft for review

## Acceptance Criteria
* Payment amounts under DEA and FRY in first Row of chart are updated.

**Comment by lunascoop** [comment]
@RLHecht I reverted the changes to the Drupal page and updated the payment amounts. Let me know when you publish so I can re-add Beth's changes.

VA education benefits for survivors and dependents: http://preview-prod.vfs.va.gov/preview?nodeId=984
