### ISSUE TITLE
Update Zoom Info for Future Accessibility Orientations

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39297]
## User Story
As an Accessibility Orientation host, I want a scheduled reoccurring zoom meeting so that I do not need to email participants a new zoom invite.

- Intended Audience: Accessibility Orientation Host
- Desired Outcome: A reoccurring scheduled zoom meeting
- Due Date: N/A

## Description
With the introduction of Calendly and monthly scheduled orientation meetings, we identified that having each host provide their zoom for ease would provide the best experience.
With Noah's departure, we have updated it in the interim with Chase's zoom. This ticket is to update the zoom with a host's information.

## Artifacts Needing Updates
[Confluence: Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions)
[Platform Website: Calendly Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Calendly+Orientation+Sessions)
Calendly

## Tasks
N/A

## Acceptance Criteria
- [ ] Calendly zoom information has been updated (Potentially blocked until Calendly adds functionality, currently in their backlog)
- [ ] Confluence: Orientation Sessions has been updated
- [ ] Platform Website: Calendly Orientation Sessions has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket
