### ISSUE TITLE
[Design] Replace Last 4 with DOB in LoROTA Login

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39308]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Labeled with HCE-Checkin, ux, design
- [ ] Prepend [UI] to the beginning of the ticket title
- [ ] Fill in User Stories
- [ ] Fill in Description
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria
---

## User Story
- As a [role], I want to [what] so that I can [do something].

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
> What will the team get at the end of this ticket?
A wireframes set for [feature name] will be delivered with the technical specifications needed for engineering to implement said feature.

## Tasks
> this is a list of design tasks that are needed for this ticket
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] %Add any additional Tasks%

## Acceptance Criteria
> when is the ticket done
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] %Add any additional Acceptance Criteria%
