### ISSUE TITLE
[Design] Update Wireframes and Messaging for Messaging when Authentication Limit is Reached (before final attempt and at final attempt)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39303]
## User Story
- We need to update the messaging and wireframes for messages for reaching the authentication limit
    - Do they need to call the contact center?
    - Other messaging?

## Tasks
- [x] Need wireframe for CI
- [x] Need wireframe for PCI
- [ ] Check with Content team
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud

## Deliverable
- Wireframes: https://docs.google.com/document/d/1I86koB8XyJv0Vn6Fii316VY3s7A3tYZeA_837sIBTn8/edit

**Comment by zach-park** [comment]
Screenshots attached: 

CI-Error (Acct locked, see staff to check in)
![CI-Error (Acct locked, see staff to check in).png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/e2db94c0-2aff-48bb-af07-ffcce9fd521f)

CI-Verify Identity Error
![CI-Verify Identity Error.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/a597bc84-b641-41c9-a885-35aa9b295036)

PCI-Person-Verify Identity Error_After 3 validation attempts
![PCI-Person-Verify Identity Error_After 3 validation attempts.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/cd2d2bd8-0342-4d53-b060-6890ea20bccd)

PCI-Phone-Verify Identity Error_After 3 validation attempts
![PCI-Phone-Verify Identity Error_After 3 validation attempts.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/bffa8bf3-a9cf-48fb-a2ed-abd6ad117365)

PCI-Phone-Verify Identity Error_First 2 errors
![PCI-Phone-Verify Identity Error_First 2 errors.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/387bbf68-d092-4e84-aca5-4228c53399a5)

**Comment by zach-park** [comment]
@loripusey , this thicket is ready for a FE ticket now. @niradatta1

**Comment by loripusey** [comment]
Thanks @zach-park I put a link to this wireframe ticket in the FE [ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39305)

**Comment by loripusey** [comment]
@zach-park @kristenmcconnell Is all of this content in the Round 2 translations json?

**Comment by kristenmcconnell** [comment]
@niradatta1 I think you might know the answer to Lori's above question.

**Comment by niradatta1** [comment]
@loripusey Yes

**Comment by niradatta1** [comment]
next step is for @zach-park to review this with FE (I've shared this already with @brianseek for feedback on how this works for general FE/UX hand-off)
