### ISSUE TITLE
Add VA.gov email to Slack profile guidance

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39310]
## User Story
As a team member working on or in support of VA.gov, I want to be able to access general profile information including VA.gov email addresses of my colleagues in Slack.

- Intended Audience: OCTO-DE, Platform, VFS Teams
- Desired Outcome: Updated profiles with Va.gov email
- Due Date: N/A

## Description
[Discussion in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1648568310099919) related to adding VA.gov email address to Slack profiles.
Consensus was that VA.gov email address is potentially helpful information and we should add it to our orientation materials.

## Artifacts Needing Updates
[Platform Website: Slack Profile Guidelines](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools#Slack)
[GitHub: Orientation Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)

## Tasks
- [ ] Add VA.gov email to list of information to add to slack profile in GitHub: Orientation ticket - General
- [ ] Add VA.gov email to list of information to add to Slack profile on Platform Website: Slack Profile Guidelines

## Acceptance Criteria
- [ ] GitHub: Orientation Ticket template has been updated
- [ ] Platform Website: Slack Profile Guidelines has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@jwoodman5 this request came from Chelen earlier this year. I have concerns about requiring VFS and Platform teams to include their VA email in their Slack profile. Can we talk about this at our next 1:1?

**Comment by jwoodman5** [comment]
@shiragoodman Absolutely!
