### ISSUE TITLE
Design - Auth Profile - Personal Info Revision - Create UAT Research Plan 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39318]
## Background
As a Designer I want to create a research plan and conversation guide for Personal Information Revision UAT so that I am organized and know what I will ask participants to do.

## Tasks
- [x] Create research plan
- [x] Review with PM
- [x] Share with PO

## Acceptance Criteria
- [x] Create research plan
- [x] Review with PM
- [x] Share with PO

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
If it helps, we can separate this out into two tickets -- one for the UAT plan, and another for the conversation guide. If you want to do that, @cgednalske, can you work with @SKasimow to do so? If not, feel free to leave this ticket as-is.

**Comment by SKasimow** [comment]
@cgednalske @Samara-Strauss Hi - I'll go ahead and create a new ticket so that we have one for UAT and a new one for conversation guide.

**Comment by Samara-Strauss** [comment]
@SKasimow to be clear, it should be:

- One ticket for the UAT research plan
- One ticket for the UAT research guide

If Marci hasn't already created them, we can create tickets for recruiting and actual UAT sessions later.

**Comment by Samara-Strauss** [comment]
Great, thank you!

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow -- this sounds great. Thank you both!

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss --- just realized these tickets say review with PM and then send to PO, so I've asked Sharon if she wants to look over the plan first. But I'm also posting the link here in case we're not following those exact steps since Sharon recently joined the team and you prefer to both take a look simultaneously on Monday.

Here's the [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/uat/research-plan.md). In addition to the primary goal of confirming the functionality, I've also included secondary goals to confirm our changes have addressed some of the concerns we uncovered in our last research study.

**Comment by Samara-Strauss** [comment]
This looks great! I have a few small suggestions.

### Background

Please take out any mention of pronouns or sexual orientation.

### Research Goals

Are we really trying to re-validate all these things, or are there a few specific things you want to look at? I'm OK with us validating a few changes, but just want to be clear that this shouldn't be too focused on usability. 

### Recruitment criteria

What is the difference between "All participants" and "Participant groups"? I understand that "All participants" means the criteria applies to everyone, but it's unclear to me whether "Participant groups" is optional criteria or applies to everyone as well.

Also, because participants can't participate in a study more than once every 6 months (I think), I'm under the impression that the more specific we get with our criteria, the harder it is for Perigean to recruit. I think you can submit this to Perigean and see what they say in terms of how easily they will be able to recruit. But, if they have trouble, this is what I see as the most important for this study:

- LOA3
- Able to screenshare
- Comfortable providing email address
- At least 50% LGBTQ (since this is particularly relevant to this work)
- At least 25% using assistive technology (to make sure code actually works with assistive tech)

Otherwise, I would say all of the rest is a nice to have. IMO, other demographics are less important with UAT than usability testing since we are mostly testing whether all the connections work instead of whether the design serves different groups.

IMO, even though it's optional, you don't need to include the geographic distribution of east coast/midwest/west coast since that should have zero impact on UAT.

**Comment by SKasimow** [comment]
I've read through the research plan and Samara's comments - all looks good from my perspective. Thanks!

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow -- thank you for taking a look!

Making those changing and here are my thoughts on some of the details:

### Research Goals
Good point! I think you're right that a few can come out, such as understanding the terminology, which hasn't changed, as well as the order of fields.

I'd propose the following three are most important to validate, as they relate directly to the new content that we introduced in the hint text/FAQ and our goals for those additions: 
- We would like to evaluate whether or not Veterans understand what this information is and why we are asking for it.
- We would like to validate that Veterans understand it is optional to provide this information. 
- We would like to validate that no major usability hurdles have been introduced during our recent iterations.

### Recruitment criteria
I see what you mean about Participants groups. That section came from another UAT plan I was looking at for reference, but it these should just be under **All Participants**. Removed that to get rid of that redundancy. Thanks!

I'll definitely keep that in mind and resort to those criteria if Perigean has trouble recruiting! I agree they are most important. Would love to initially overshoot since we didn't get as many LGBTQ, non-white, and female-identifying participants in the last study as we would have liked.

**Comment by Samara-Strauss** [comment]
All of this sounds good. Thanks @cgednalske!

**Comment by cgednalske** [comment]
This is all complete as well! I think it can be closed out.

**Comment by SKasimow** [comment]
@cgednalske - ok closing. thanks!
