### ISSUE TITLE
Profile: Sprint 71 (Apr 6 -19) 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39313]
## PTO/OOO/Unavailable

- **Christina**: Apr 18 -19
- **Sharon**:  Apr 7 - 8
- **Tom**: Apr 18
- **Mark**: Apr 14 - 15

# Sprint Priorities

1. Personal information Revision -  Goal: Finish BE  and start connection to the frontend
2. MHV Research - Liz to deliver final report
3. Notification preferences - Review with IA and content, send feedback to VA Profile
4. Address change messaging -  continue work
5. Onboarding -- welcome, Sharon and Mark!
 
### PM - Sharon

- [x] #39204

### FE - Mark
- [x] #39749

### FE - Adam
- [x] #36006 (PR being submitted)
- [x] #38292 (will complete in sprint 71)

### BE - Tom 

- [x] #38787
- [x] #38788 (Check with Tom)
- [x] #39325
- [x] #38796
- [x] #38797 (In progress)
- [x] #40042 (In progress)

## 📩 Bad address indicator

Mostly on hold this sprint in favor of other work. This one ticket is carrying over from sprint 70:

### Design - Christina
- [x] #38139

### FE - Adam
- [x] #35205

### Design - Christina
- [x] #39166
- [x] #39167

- Content and IA request is in [39883](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39883). We should keep an eye on this and make sure we hear back from content/IA soon.

### FE - Adam
- [x] #37842

### Research - Liz
- [x] #39402
- [x] #39323
- [x] #39562

### BE - Tom 

- [x] #38100
- [x] #39642

**Comment by MarciMcGuire** [comment]
oops sorry for closing this; I was showing my colleagues an example of a Sprint Plan.

**Comment by SKasimow** [comment]
Ha- np!

**Comment by Samara-Strauss** [comment]
Let's leave this open through Wednesday morning

**Comment by SKasimow** [comment]
@Samara-Strauss yes sorry - my bad. Didn't mean to close

**Comment by SKasimow** [comment]
All tickets completed - closing
