### ISSUE TITLE
CST: Make older updates button accessible

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39322]
## Description

When a claim has an initial review status, a "see older updates" button was found to be inaccessible. After discussing with the Design System Council a new pattern was established. Additionally, a content review of the page text was performed. Now we need to implement these recommendations

- Accessibility review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778
- Design review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39206
- New design: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39164
- Content review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39170

<details><summary>Design</summary>

<img width="684" alt="latest update header with a single event then a header with older updates and a count of how many followed by a button to show older updates" src="https://user-images.githubusercontent.com/136959/160643170-7b7454fe-8485-4e89-b10c-bb42a0a20fbf.png">

View after activating the "Show older updates" button
<img width="542" alt="After clicking older updates button, the text changes to hide older updates and all events are included below it" src="https://user-images.githubusercontent.com/136959/160643161-b8d1ef86-803d-4197-b1e8-cf55ac830fe5.png"></details>

To get to this page:
1. Log in to ID.me with `vetsgov+test233@id.me` ([get password here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md))
1. Go to https://staging.va.gov/track-claims/your-claims/600219085/status in browser

## Tasks

- [ ] Update button to always be visible
- [ ] Add "Latest update" and "Older updates (#)" headers
- [ ] Make older update button into a toggle
- [ ] Update content
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
