### ISSUE TITLE
BE - Auth Profile - Personal Information - Test CSP Identifier and Assigning Authorities

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#39325]
## Background

When calling the VA Profile demographics API, the CSP ID is used instead of the VA Profile ID (Vet360 ID).

The two assigning authorities MPI requested to use are:
- PN^200IDME^USDVA
- PN^200VLGN^USDVA

## Tasks
- [x] Determine user field of CSP ID.
- [x] Determine user field for assigning authority ID.

## Acceptance Criteria
- [x] Verify with vsp-identity team that the correct attributes are being used for an authenticated user.
- [x] Update service object and specs.

**Comment by tpharrison** [comment]
Slack thread that discusses the use of CSP ID:
- https://dsva.slack.com/archives/C7TE0PFTL/p1645794128256789

**Comment by tpharrison** [comment]
Was able to get answers in the #vsp-identity channel...

https://dsva.slack.com/archives/CSFV4QTKN/p1649692544524819

**Comment by tpharrison** [comment]
Updated service and related specs.
