### ISSUE TITLE
Research - Auth Profile - MHV Research - Complete Synthesis & Deliver Final Report

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39323]
## Background

As a Researcher, I want to synthesize the results from my sessions with Veterans and deliver the final report of my findings so that we can determine the approach to take when migrating MHV profile into VA.gov Profile.

## Tasks
- [x] Synthesize research results
- [x] Compile final report
- [ ] Review final report with PM
- [ ] Deliver final report to PO

## Acceptance Criteria
- [x] Synthesize research results
- [x] Compile final report
- [ ] Review final report with PM
- [ ] Deliver final report to PO

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
@Samara-Strauss is your expectation that we will have a separate report for the Veteran interviews, in addition to the final report summarizing _all_ activities (and including recommendations) when this is complete?

**Comment by Samara-Strauss** [comment]
@andaleliz I think this really depends on what you would find to be most helpful. If it would be helpful for you to put together a formal report of the user interviews before doing the larger recommendations work, that is fine by me. If some sort of less formal write-up, like a top-line summary, would be the most helpful before moving on, that's OK too. Just let me know what you think is the best use of your time.

I do realize now that I did *not* account for a user interview write-up, whether formal or more informal, in planning. I'm OK with changing the expectations for the sprint if you wanted to move back the final recommendations write-up to account for the user interview write-up. Just let me know what you think is reasonable to accommodate.

**Comment by andaleliz** [comment]
@Samara-Strauss I think a topline summary would be sufficient to help us achieve the goals of this research, and then I'll incorporate that into the final synthesis of all activities. I think I can still get that all done by the end of this coming sprint (April 19).

**Comment by Samara-Strauss** [comment]
Sounds good to me! If there's not already a ticket for it, can you work with Heather to create a ticket for the topline summary and make sure it's included in the sprint?

**Comment by andaleliz** [comment]
Sure! Is Heather covering for Marci until Sharon is onboarded?

**Comment by Samara-Strauss** [comment]
🤦 Sorry, I should have said Marci! Good catch :D

**Comment by MarciMcGuireGCIO** [comment]
This ticket has been created -- #39402

**Comment by andaleliz** [comment]
@Samara-Strauss I have [a draft ready to be reviewed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md). Can you give it a once over and let me know how the format/outline aligns with what you hoped for?

If I'm on the right track, I'll get some more eyes on this for clarity/proofreading before I ask you to really dig in. 

Thanks!

**Comment by Samara-Strauss** [comment]
Hey @andaleliz! Just wanted to let you know I didn't get to this today, but will review tomorrow morning. Sorry for the delay!

**Comment by Samara-Strauss** [comment]
Hey @andaleliz!! This is great! Here is my feedback!

ALSO, I only just realized that you said you wanted my thoughts on the structure and that everything was still in draft mode at the end of me writing out the million thoughts I have. SO, here are my million thoughts! I think this is largely great and totally in the right direction. Thank you for the great work!!

## Background

I appreciate you keeping this section short and sweet, but I do think we can pull in a little more info on what we did. How do you feel about adding a list of what we did (profile audit, stakeholder interviews, etc) and linking off to the individual reports for each part of the research? Let me know if you think this is helpful or not.

## Recommendations

Suggestions that you don't have to take,. Let me know what you think of the following:

- Numbering each recommendation, eg "Recommendation #1: Maintain important items..." 
- Order the list of recommendations as follows - What items already exist on VA.gov, What items we plan to not move over, What items we DO plan on moving over
- Given that there is only one item we recommend moving over right now, can we change that heading to be something more generic like "Functionality we plan to incorporate into the VA.gov profile" or something like that?

### Maintain important items that are already consistent between the two profiles.

- There are references to the nametag in here. Given that this basically means nothing to anyone but the people on our team, let's take out that term. For the notes section, I think you can have something like "Read-only; Comes from MPI." or something.
- I'm not sure what "consistent with MHV" is trying to communicate. Personally, I think I get what you're going for, but I'm not 100% sure and I don't think it will be clear to anyone who reads this who is not super familiar with the profile sections of either VA.gov or MHV.

### Email notification settings need to be incorporated into VA.gov profile.

I recommend moving this to the end, calling more attention to it by titling it something like "Functionality that needs to move over from MHV to VA.gov", and expanding this section slightly to talk about a high-level migration plan (we'll need to work in tandem with MHV, VA Profile, and VANotify to make this happen). For the purposes of this report, I don't think you need to include the part about us updating our designs, though you are 100% right. 

### Retire certain items with MHV.

> Generally, we do not recommend moving things that don’t link back to a VA database. 

Again, I really appreciate you being short and sweet here, but I think we can slightly expand this intro section without making it into a whole thesis.  It would be helpful to have 1 or even 2 short paragraphs that give an overview of why we don't think these items should be moved over -- we recommend not moving over anything that is unviewable (eg. SSN) , that we've already retired on VA.gov, anything that had low usage on MHV (as determined by analytics and user testing), and anything that was more of a self-journaling item (and a couple sentences on the confusion that caused in testing). I don't think this needs to be super long, but I do think it will help to give some context to your findings.

> SSN

- Who did we learn from that this was going to be removed? I'd either name that person or generally say "we learned from MHV stakeholders..."

> Gender

For this, let's call out a couple things:

- This is effectively sex assigned at birth
- We are incorporating a gender identity field to launch in June of this year, which is more inclusive

I love the bit about our research, so definitely leave that.

> What is your relationship to VA?

We need to clarify the following:

- That the patient designation is important to stakeholders, but the rest of the self-entered options don't have an impact outside of (I think) what shows in the MHV admin tool.
- We are not suggesting that they do not store who is a patient or that they remove any data, just that they don't need to elevate the patient designation in the VA.gov profile, and we do not need to provide self-entered options that are there for journaling purposes and don't tie back to a VA database.

> How would you like to be addressed?

Given that we are adding preferred name, I am wondering whether this should get moved into the section of "things we already have". It's not an exact 1:1, but it serves a similar enough purpose that I think we're keeping the same basic functionality. What do you think?

> Fax and pager

We can also mention that we removed Fax recently from our profile at the recommendation of VA Profile, who let us know that stakeholders across the VA are not using fax as a means of communication with veterans.

> My VA Treating facilities

- Optional: linking back to our preferred facilities work.
- Again, I think we should mention that if this had an impact on VA records, it might be important, as users assumed this had a larger impact and would switch their records from one VAMC to another. However, since it is really a self-journaling item, it is confusing given that it is has no impact on VA records as veterans assume it does.

> In case of emergency

- I think we should mention that this could be helpful *if* it tied back to a VA database and updated emergency contact/next of kin info within the health care system. However, given that this is another self-journaling entry on MHV, we do not recommend it move over because users assume it updates info across the VA when it does not, and this is confusing.

 ## Additional points to think about

> Self-journaling features are confusing for users.

This is great. Let's call this out before our recommendations on which items to remove. I would also explain what we mean by "self-journaling" and give an example or two, as that might not be clear, even to MHV folks, if they are not familiar with the MHV profile.
 
> We should collaborate with the health apartment team to determine where it makes the most sense to put health-related profile items.

I agree with this finding, but it's confusing given that there are items in the table you included that you just recommended not move over to VA.gov.

> We need further discussions on managing shipping addresses for prescriptions.

Assuming this section is in draft mode, so let me know if you want to talk about it to make sure you're clear on the issue.

**Comment by andaleliz** [comment]
Thanks so much Samara! Writing back to acknowledge that I've seen this - working through the comments and updates this afternoon.

One quick point - I think we should talk about the prescription shipping address point so that I'm clear on the problem. I thought I understood it 🙃  Given it's complexity, perhaps we should start creating some docs around it to document the problem. If those have already been created, perhaps pointing me to them would be a good place for me to start.  Thanks!

**Comment by Samara-Strauss** [comment]
OK, totally up for a quick chat! I don't have much of anything documented because I don't have clear definition of the problem, but I can at least give you an overview in a quick chat.

**Comment by andaleliz** [comment]
> OK, totally up for a quick chat! I don't have much of anything documented because I don't have clear definition of the problem, but I can at least give you an overview in a quick chat.

Sounds good - maybe we can tack this on as a conversation point in our 1:1 tomorrow?

---
**Responding to feedback:**

Thank you so much for reading through everything and providing all this feedback! I agree with almost all of it and have updated the doc accordingly. A few comments below:

The biggest changes were:
- More details in the [background section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md#background)
- More context to the [recommendations to retire fields](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md#2-retire-certain-items-with-mhv), including moving the "self journaling is confusing" point up to this part of the doc.
- Updated the [3rd recommendation about notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md#3-plan-to-incorporate-some-functionality-into-the-vagov-profile) so it reads as a less specific recommendation and includes some next steps

>I'm not sure what "consistent with MHV" is trying to communicate. Personally, I think I get what you're going for, but I'm not 100% sure and I don't think it will be clear to anyone who reads this who is not super familiar with the profile sections of either VA.gov or MHV.

What I meant by that was that "MHV and our profile already have the same functionality for this item".  I rephrased it say "VA.gov profile currently matches functionality on MHV" which is hopefully more clear.

> We should collaborate with the health apartment team to determine where it makes the most sense to put health-related profile items.
> I agree with this finding, but it's confusing given that there are items in the table you included that you just recommended not move over to VA.gov.

I can see how that's confusing! To clarify, I'm not recommend that we move those MHV items _to the profile_ in their current state. I added some clarification in the recommendations for the Health information card and In case of emergency, since those are to two items that appear in the table that users felt belonged in the profile.  The rest of the items in the table either aren't in MHV, or don't belong in the profile from a user perspective.  Is there anything else that comes to mind that might make that more clear in the doc?

I'll update the prescription section once I have a better understanding of the problem.

**Comment by Samara-Strauss** [comment]
Sounds good!

From: Liz Lantz ***@***.***>
Sent: Thursday, April 14, 2022 4:46 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Strauss, Samara ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Research - Auth Profile - MHV Research - Complete Synthesis & Deliver Final Report (Issue #39323)


OK, totally up for a quick chat! I don't have much of anything documented because I don't have clear definition of the problem, but I can at least give you an overview in a quick chat.

Sounds good - maybe we can tack this on as a conversation point in our 1:1 tomorrow?

________________________________

Responding to feedback:

Thank you so much for reading through everything and providing all this feedback! I agree with almost all of it and have updated the doc accordingly. A few comments below:

The biggest changes were:

  *   More details in the background section<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fproducts%2Fidentity-personalization%2Fprofile%2Fmhv-profile-research%2Frecommendations.md%23background&data=04%7C01%7C%7C311043ce703a47a2ceb608da1e57ba9d%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637855659385850119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xp5aDMKmL%2BrcyEGLf078mNzR16F57MSejSuYhNcdVWo%3D&reserved=0>
  *   More context to the recommendations to retire fields<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fproducts%2Fidentity-personalization%2Fprofile%2Fmhv-profile-research%2Frecommendations.md%232-retire-certain-items-with-mhv&data=04%7C01%7C%7C311043ce703a47a2ceb608da1e57ba9d%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637855659386006837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3cpXp6rcn1WS9NXp0E2pWzBVEhre6luMyXTsTlVIrkk%3D&reserved=0>, including moving the "self journaling is confusing" point up to this part of the doc.
  *   Updated the 3rd recommendation about notifications<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fproducts%2Fidentity-personalization%2Fprofile%2Fmhv-profile-research%2Frecommendations.md%233-plan-to-incorporate-some-functionality-into-the-vagov-profile&data=04%7C01%7C%7C311043ce703a47a2ceb608da1e57ba9d%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637855659386006837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GAoWDWzGMeFUOkfHYLWztBGYLFx9uAiPh3umtcHhyrI%3D&reserved=0> so it reads as a less specific recommendation and includes some next steps

I'm not sure what "consistent with MHV" is trying to communicate. Personally, I think I get what you're going for, but I'm not 100% sure and I don't think it will be clear to anyone who reads this who is not super familiar with the profile sections of either VA.gov or MHV.

What I meant by that was that "MHV and our profile already have the same functionality for this item". I rephrased it say "VA.gov profile currently matches functionality on MHV" which is hopefully more clear.

We should collaborate with the health apartment team to determine where it makes the most sense to put health-related profile items.
I agree with this finding, but it's confusing given that there are items in the table you included that you just recommended not move over to VA.gov.

I can see how that's confusing! To clarify, I'm not recommend that we move those MHV items to the profile in their current state. I added some clarification in the recommendations for the Health information card and In case of emergency, since those are to two items that appear in the table that users felt belonged in the profile. The rest of the items in the table either aren't in MHV, or don't belong in the profile from a user perspective. Is there anything else that comes to mind that might make that more clear in the doc?

I'll update the prescription section once I have a better understanding of the problem.

-

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! The [prescription shipping address section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md#we-need-to-learn-more-about-managing-shipping-addresses-for-prescriptions) has now been updated per our earlier conversation. If the doc looks good to you, I think we're ready to close this out and get together w/ the health modernization folks to discuss the best way to socialize this.  Should I put a deck together to present the recommendations to them?

**Comment by Samara-Strauss** [comment]
This is looking great! Really great job. It's super concise and easy to scan while also being thorough. 

One final thing:

> We should collaborate with the health apartment team to determine where it makes the most sense to put health-related profile items.

There are items in this list that we recommend never moving over, like the printable health card. I think it would be confusing to include items like that in this section of the report. What do you think? I think it's OK to include items that we don't recommend moving over if they are self-journaling entries that go nowhere, but would be useful if they actually updated downstream VA records (eg. emergency contact or blood type).

> Should I put a deck together to present the recommendations to them?

This is up to you. I don't think we need a deck to talk to Tracey/Lauren/Meg, but one would probably be helpful for when we eventually talk to MHV stakeholders. Let's maybe talk with Tracey/Lauren/Meg first before making a deck in case they recommend any changes.

**Comment by andaleliz** [comment]
> There are items in this list that we recommend never moving over, like the printable health card. I think it would be confusing to include items like that in this section of the report. What do you think? I think it's OK to include items that we don't recommend moving over if they are self-journaling entries that go nowhere, but would be useful if they actually updated downstream VA records (eg. emergency contact or blood type).

I _think_ the health card is the only one that fits into that category, unless I missing something. I'm ok with taking that out; I was trying to be comprehensive about all the items that our team and/or the health apt team had questions about.  There are also some items that don't exist in MHV that they were wondering where people would place, such as next of kin and the self-entered list of providers and doctors.

I'll hold off on making a deck until we talk to Tracey/Lauren/Meg, great idea!

**Comment by Samara-Strauss** [comment]
You're right -- it's just the printable wallet card. Let's take that out, and I think it's otherwise good to go. I agree that we should keep in items that are up for discussion even if they don't exist or shouldn't move over (because the don't connect to anything meaningful) right now.

I think we're good to go on this ticket!

**Comment by andaleliz** [comment]
🎉  Great! I made that update and will close out this ticket.  @SKasimow will you please include [a link to the doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md) in the invite to Meg, Tracey, and Lauren so they have some context around the meeting? Thank you!

**Comment by SKasimow** [comment]
@andaleliz will do!
