### ISSUE TITLE
Gain clarity of which API routes new domain needs to serve

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#39332]
## Issue Description
As a result of the separation of the Lighthouse (LH) API from the new VA.gov API (vets-api), the new domain will likely serve fewer or different API routes. The purpose of this research ticket is to gain clarity on which routes exactly need to be supported.

The current hypotheses are:
1. API requests that do NOT start with `/services` or `/internal` are and will remain to be processed by the vets-api. They should be accessible by the new `tbd-domain-api.va.gov`.
2. The LH routes that make use of vets-api (start with `/services` or `/internal` but are routed to vets-api by Kong) - should also be served from `tbd-domain-api.va.gov`. Kong appears to be forwarding requests to vets-api without changing the paths.
3. The LH routes that don’t make any use of the vets-api (start with `/services` and `/internal` and are routed to the forward proxy and the DVP account by Kong) do _not_ need to be accessible via `tbd-domain-api.va.gov` but only `api.va.gov` going forward.

---
## Tasks
- [ ] Confirm all three hypotheses with stakeholders
- [ ] Discuss with stakeholders if there are other caveats that are not covered by the three hypotheses
- [ ] Document findings in a Confluence doc that details the purview of the new API domain

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
Your categorization seems correct to me! But of course the more eyes the better. 

Another way of thinking about this is that LH is currently agnostic to where APIs are implemented. So end state is that Apigee gateway will route to many API implementations - and vets-api just happens to be one of those, just as DVP, and VA Profile are. 

**Longer term** the vets-api APIs in category 2 might be good candidates for splitting out into an isolated deployment from the APIs in category 1, as the platform evolves to make that more feasible. That would open the door to things like "lighthouse teams being responsible for operating them" and possibly "rehoming in the DVP environment". Those would be bigger/future steps and getting the API gateway routing right is clearly the first step.

**Comment by madebydna** [comment]
@patrickvinograd, thanks so much for your input! The [explainer doc](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap) lists various cases of code interdependencies between LH and vets-api. For instance, the Benefits Intake API is a LH API that is implemented in vets-api but otherwise pretty standalone in that it doesn't share any code with other vets-api services. That seems like a very good candidate for extraction in the future. 

However, there are also cases where vets-api and LH API share some significant backend code, which according to the doc was a deliberate decision to promote code reuse. Perhaps these types of coupling will be addressed in the long run by splitting up vets-api into microservices.

Anyway, another way I was thinking we could identify the routes that the new domain will support is by simply listing the full list of routes from the vets-api project. I will give the presentation some more thought and then create a doc that people can review and comment on.

**Comment by dginther** [comment]
Related to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38782

**Comment by madebydna** [comment]
I created a Confluence doc that actually enumerates the routes in the different categories: https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov
