### ISSUE TITLE
Coordinate Nginx revproxy migration efforts to K8s with VSP Ops team

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#39335]
## Issue Description
Currently, the VSP Ops team is in the process of migrating the existing version of the revproxy to Kubernetes into the different environments. The version in the dev environment is close to being functional. 

However, the Nginx revproxy might end up being either substantially reconfigured or even replaced as part of the CIT team’s work of separating va.gov from the Lighthouse domain. As such, coordination between teams is needed to avoid duplicate or redundant work.

---
## Tasks
- [ ] Start discussion with the VSP Ops team about the issue at hand
- [ ] Discuss transfer of migration tasks to CIT team

## Acceptance Criteria
- [ ]  Documented plan for who will manage the migration is in Confluence and linked in this issue.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Based on current research, moving the entire revproxy is outside the scope of the CIT team.
