### ISSUE TITLE
FE - Auth Profile - Bad Address Indicator - Create check for BAI in Redux store, display alert

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39347]
## Background
As a FE engineer, I want to create a check that resides in Redux store and display alert based on check so that I can verify that the alert is being displayed under the right conditions.

## Tasks
- [ ] Create a check in Redux store
- [ ] Display alert based on check
- [ ] Test to confirm alert appears under right conditions

## Acceptance Criteria
- [ ] Create a check in Redux store
- [ ] Display alert based on check
- [ ] Test to confirm alert appears under right conditions

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Closing...consolidating with 39342
