### ISSUE TITLE
[Design] My VA - Audit: Review page-level alerts placement

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#39343]
## Background
During testing for the new Benefit payments and debts section, there was an error for the claims and appeals section.  While the page was displaying accurately, it brought to mind that we should address this to ensure page-level alerts are populating as expected.

The **Claims and appeals** alert displays _below_ the Notifications header, when the Notifications header is present.  Otherwise, there is no header for that error.
The **Health care - Cerner** message displays without the Health care header, therefore if the Notifications header were present, it would appear _below_ it. (I do not have a screenshot of the Cerner message and the Notifications feature).  There is a page-level **Health care** alert, however I do not have a staging user with that issue.  You can see it referenced in the Contact Center guide (screenshot below of the guide).
I don't know whether the **Payment info** error displays _above_ or _below_ the Notifications header, when the header is present.  I do not have a screenshot of that. 

<Details>
<Summary>Screenshot of Claims and Appeals error message **with** Notifications header</Summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ed1d5446-3aed-41c6-a32e-6441cc107a3b)

</Details>

<Details>
<Summary>Screenshot of Claims and Appeals error message **without** Notifications header</Summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/e80b31cd-6b44-43d4-868b-74decd1d88eb)

</Details>

<Details>
<Summary>Screenshot of  Health care Cerner message with Claims and appeals (no notification header)</Summary>

![image](https://user-images.githubusercontent.com/92328831/160853921-cfdd376b-09d0-4428-aa24-e0ffa99fec02.png)

</Details>

<Details>
<Summary>Screenshot of  Health care error message from Contact Center guide</Summary>

![image](https://user-images.githubusercontent.com/92328831/160857547-07618800-7bb6-4da8-8fe4-2c37e588d056.png)

</Details>

<Details>
<Summary>Screenshot of Payment info error message **without** Notifications header</Summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/1feba731-cae5-4bb1-9de7-4c2e7a6bfa7c)

</Details>

## Tasks
- [ ] Determine how the page-level alerts should display
     - With Notifications header
     - Without Notifications header
- [ ] Update designs, if needed
- [ ] PM to create tickets for FE efforts, if needed

## Acceptance Criteria
- Page-level alerts are displayed consistently, and with consideration to whether the Notifications header/section is present or not.

**Comment by hdjustice** [comment]
This can be addressed along with the audit findings and team determination on how to simplify and potentially reorganize My VA.

**Comment by ajakabcin** [comment]
Covered in #39285 - closing
