### ISSUE TITLE
FE - Auth Profile - Bad Address Indicator - Build UI for designs within the desired profile views

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39342]
## Background

Build UI for the "bad address" indicator to alert and encourage users to check and/or update their mailing address when they are flagged as such by the BE.

## Tasks
- [x] Create feature toggle
- [x] Build UI for designs within the desired profile views 
- [x] Deploy to Staging
- [x] Conduct all unit and e2e tests
- [x] Create a BAI check in Redux store
- [x] Display alert based on check
- [ ] Test to confirm alert appears under right conditions

## Acceptance Criteria
- [x] Build UI for designs within the desired profile views 
- [x] Unit and e2e successfully completed
- [x] Deploy to Staging
- [ ] Update PM and PO when ready to be reviewed

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
Some notes for Josh on accessibility:

Some things I don't have a good answer to (yet) that I'm thinking about.

Screen reader users may get confused that "Edit your address" will be read out twice in a row (e.g. "Edit your address to update or confirm it, link" then "Edit your address button."

Sending them to "Edit your address" button may have various mileage depending on if their address is actually read out to them when they're navigated to it. Using an aria-describedby to link the address to the button could be an easy, non-intrusive engineering fix to it where the button would read out as "Edit your address, [2912 Bakers Lane...] Button"

Also, one last thing-- you may also want to consider using aria-live="polite" for screen reader users when passing this off to your developer if:

it's important enough that you want to guarantee screen reader users hear it
there aren't any other important alerts on the page that use aria-live="polite" (it can get noisy if there's more than a couple)

**Comment by SKasimow** [comment]
@cgednalske @mdewey - it would be great for the 3 off us to have a quick review. I came into this project mid-flight and didn't write the tickets. So would love to get a little more background; if Mark agrees happy to find 30 min for us.

**Comment by mdewey** [comment]
Note around screen reader: 

Placing the alert above the h1, but removing the heading. It could use aria-live="polite" to announce itself. The main con is that it would lose visual prominence without a heading and may be harder to find if the user fails to hear the initial polite announcement.

**Comment by mdewey** [comment]
Question: Link goes to the mailing address section, with the something in focus

**Comment by mdewey** [comment]
Note: 

On Error of saving information, hide the yellow alert

**Comment by mdewey** [comment]
Note: Only show Alerts on Personal Information and Contact Information pages

**Comment by mdewey** [comment]
Note: Analytics for 

- Big Alerts shown
- Big Alerts clicked

**Comment by SKasimow** [comment]
Sketch files [here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/eKeeAl0)

**Comment by mdewey** [comment]
First pass: Focus on the alert header.

**Comment by SKasimow** [comment]
Hey @mdewey - now thinking I should combine tickets and add the scenarios I wrote for the other ticket with this ticket. Are you ok with that?

**Comment by mdewey** [comment]
@SKasimow and @Samara-Strauss This is now enabled in staging. I have not tested it in staging yet. I waiting for the users to be created. 

- Feature is up and should be working (baring validation) 
- Basic analytics are in place
- It has not been accessibility tested yet.

**Comment by SKasimow** [comment]
Thanks Mark! As soon as Tom has a chance to set up the staging accounts I'll let y'all know.

**Comment by mdewey** [comment]
Closing this ticket. If there is more work, it can be its own ticket.
