### ISSUE TITLE
Generate CSV of Errors from Daily A11y Scan

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39340]
# Description
Per a feature request in this [thread](https://dsva.slack.com/archives/C01RAS1KAQK/p1648642332871699?thread_ts=1648463608.903769&cid=C01RAS1KAQK), generate a CSV of errors resulting from the daily accessibility scan.

# Tasks
- [ ] Modify the daily accessibility scan workflow to generate a CSV of the errors detected during the scan
- [ ] Attach the CSV to the GHA workflow as an artifact so it can be retrieved through GHA API

# Acceptance Criteria
- [ ] CSV artifact is retrievable through the GitHub Actions API

**Comment by ddzz** [comment]
CSV is being generated in this PR: https://github.com/department-of-veterans-affairs/content-build/pull/1086

**Comment by pjhill** [comment]
Bah, merged before I could take a look at the PR, but this looks good!

@ddzz -- To be clear, the intended workflow here is that Slack is notified of the run and failures, the user clicks through the link to the run in Slack, and lastly the user downloads the concatenated CSV from the GHA workflow artifacts collection?

**Comment by ddzz** [comment]
@pjhill Yes, that's the workflow. I've shared these details with the CMS PM.

**Comment by pjhill** [comment]
Perfect, thanks!
