### ISSUE TITLE
[EKS] Migrate external-dns to helm from jsonnet

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#39356]
## Description
In continuing efforts to rid ourself from jsonnet, I am going to pick off external-dns and move it over to deploying via the helm chart.

https://github.com/bitnami/charts/tree/master/bitnami/external-dns

---
## Tasks
- [x] Deploy external dns using the helm chart in staging (less people using this environment currently)
- [x] Update external-dns to the latest version
- [x] Point argo at helm instead of jsonnet https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/argocd-apps/staging/main.jsonnet
- [x] If all goes well deploy to the rest of the clusters 
- [x] Remove jsonnet that is tied to external-dns since it will no longer be needed
- [x] Update github actions and workflows in to align with the new deployment structure https://github.com/department-of-veterans-affairs/vsp-infra-k8s-external-dns

## Acceptance Criteria 
- [x] external dns is deployed to all clusters using the helm chart and the latest version
- [x] github actions in the infra repo is re-organized and updated (building docker container, upload to ecr, update manifest)

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
