### ISSUE TITLE
[SW-Content] Create R&S article comparing DEA to Fry [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39358]
## Story
As a Veteran I need information in an R&S article comparing DEA to Fry, so I can best understand the differences and benefits of each. 

## Resources
See Document attached below

## Task(s)
- [x] Use the content in the attached doc to create the page.
- [x] Save to draft in Drupal
- [ ] Have Full editing review 

## Acceptance Criteria
*  Draft fully edited and processed for OCTO review.

**Comment by lunascoop** [comment]
@psanders86 this page is ready for review.
Compare DEA and Fry Scholarship benefits for family members: http://preview-prod.vfs.va.gov/preview?nodeId=44718

**Some changes I made:**
- I tweaked the header formatting from it's proposed layout in the Word doc because it didn't look that great. You can view the version by selecting an earlier revision in the Drupal node. I opted to bold some text instead.
- Deleted the eligibility section because it was odd to basically have a section that links to another page. Plus the content and link text for the section seemed redundant. Instead, I added a link to eligibility blue box in the How we make payments section.
- Added some bullet intro text as needed. This was based on the revised formatting.I tweaked the header formatting from it's proposed layout in the Word doc because it didn't look that great. You can view the version by selecting an earlier revision in the Drupal node. I opted to bold some text instead.
Deleted the eligibility section because it was odd to basically have a section that links to another page. Plus the content and link text for the section seemed redundant. Instead, I added a link to eligibility blue box in the How we make payments section.
Added some bullet intro text as needed. This was based on the revised formatting.
