### ISSUE TITLE
Update staging FSR template with new copy

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#39363]
## Issue Description
Copy for FSR notification has been approved and should update staging template to reflect prod.

---
## Tasks
- [x] Log into VA Notify portal and update template

## Acceptance Criteria
- [ ] New staging template matches prod template

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Currently blocked due to losing Citrix access so unable to access VA Notify portal
