### ISSUE TITLE
Deploy and validate production API key change

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#39362]
## Issue Description
Plan to deploy on regular devops cycle on Wednesday (4/6) at 4pm ET for API header name change. Validate no issues in prod.

---
## Tasks
- [ ] Sync with liberty team on deployment process
- [ ] Check with sentry over following time period

## Acceptance Criteria
- [ ] API key name has deployed and no issues found.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Blocked due to losing Citrix access and unable to receive API key in VA email

**Comment by ScottyRJames** [comment]
Deployed but showing errors, opened relevant ticket [here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/41214)
