### ISSUE TITLE
[CDP]  Create debt and bill overview sections and card components

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39372]
## Issue Description
Create debt and bill overview sections and card components
[Mockup](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148307609/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/c0d1be9e-712d-4ff1-9c07-ef24cc09d5ba)

---
## Tasks
- [ ] Create card component to display individual debts and bills
- [ ] Create Debt and bill overview section populated by debt/bill card component

## Acceptance Criteria
- [ ]  Debt and bill overview section is created and correctly populated by available debts and bills
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
