### ISSUE TITLE
[CDP] [debt] Add Your other VA bills section to Current VA debt page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39375]
## Issue Description
Add "Your other VA bills section" to Current VA debt page
[mockup](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148307609/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/3efa2a4c-b786-4cd3-9388-d4c6eaab22f1)

---
## Tasks
- [ ] Add copay API call to check for bills/copays
- [ ] Add Your other VA bills section

## Acceptance Criteria
- [ ] Your other VA bills section will appear if there are available copay/bills

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
