### ISSUE TITLE
Twice-weekly Platform website deploy (M)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39371]
# User story

As a Platform customer, I need to view up-to-date info on the Platform website so that I don't run into roadblocks when building my VFS app.

As a Platform team member, I need the Content team to regularly publish any/all changes to the Platform website so that I can trust that info about my Platform product/service is available to customers.

# Tasks

- Use SVP to publish on:
  - [x] 1st Thurs of spr
  - [x] 1st Tues of spr
  - [x] 2nd Thurs of spr
  - [x] 2nd Tues of spr
  - We will not be reviewing for style guide compliance.  We will simply be pressing "publish"

# Acceptance criteria
- Platform website has been "deployed" four times

# Reference info
- Platform website deployment instructions https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+website+deployment+instructions
