### ISSUE TITLE
[CDP] Debt 2.0 Update Current VA Debt page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39383]
## Issue Description
Update Current VA debt page to match new design 
[mockup](https://preview.uxpin.com/53bf4de7cd95501214aafee8c7c7a0a6052c53c7#/pages/147814779/simulate/sitemap?mode=i) 

Include both card and empty state views
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/fc1d1a0e-c6d4-433f-b511-6d517499c97b)

---
## Tasks
- [ ] Current VA debt page matches new design

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
