### ISSUE TITLE
[CDP] Debt 2.0 Debt Detail page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39385]
## Issue Description
Update Debt Detail page to match new design
[mockup](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148307615/simulate/no-panels?mode=i)
Confirm Pay Online information section can be populated appropriately. 

---
## Tasks
- [ ] Update Debt detail page to match new design
- [x] Confirm Pay Online information section can be populated appropriately. 

## Acceptance Criteria
- [ ] Debt Detail page will match new design. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
