### ISSUE TITLE
[Research] Conduct Research Study to Verify Spanish Translations in CI & PCI

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39394]
## User Story
As a Veteran who's native language is Spanish, I want to be able to see the CI and PCI content in Spanish so that I will understand it.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
- List out items...

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create research plan (template in research checklist above)
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan and conversation guide to GitHub folder
