### ISSUE TITLE
[Design] Wireframes for Multi-language Toggle Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39392]
## User Story
As a Veteran who's native language is Spanish or Tagalog, I want to be able to see the CI and PCI content in Spanish so that I will understand it.

## Description
A wireframes set for switching the language of the CI and PCI page/control content to Spanish and Tagalog.

## Tasks
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] Sync with design system (Danielle) on solution (loop them in). Ask if Matt should be looped in from Danielle. 

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] Meet with design system on solution

**Comment by zach-park** [comment]
Tagging @ytsaoca for collab.

**Comment by ytsaoca** [comment]
Toggle ideas

https://drive.google.com/file/d/1-mAhpBIr1mG5tR6eu8NPkQgRGfubLMQc/view?usp=sharing

**Comment by loripusey** [comment]
@ytsaoca I am changing the content of this story to more accurately reflect the work that was done and moving the content to a new story.
cc: @sarahknoppA6 @kristenmcconnell
