### ISSUE TITLE
[Research] Create Conversation Guide for July Research

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39393]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
- List out items...

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)
- [x] Create conversation guide (template in research checklist above)
    - Add some questions about cancelled appointment (look at 36855)

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan and conversation guide to GitHub folder

**Comment by kristenmcconnell** [comment]
Drafts:
- [Veteran Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/corpus-christi-in-person/conversation-guide.md)
- [Staff Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/corpus-christi-in-person/conversation-guide.md)

**Comment by loripusey** [comment]
Look good!

**Comment by kristenmcconnell** [comment]
[Research repo Veteran ticket created](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/153)

**Comment by kristenmcconnell** [comment]
[Research review request](https://dsva.slack.com/archives/C0216PL32HJ/p1657304979571669) sent via Slack to Shane Strassberg.
