### ISSUE TITLE
[Design] Final Wireframes to Include Time Zone with Appointment Times in Check-in & Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39390]
# Problem Statement
As a Veteran who has to travel to a different time zone for my appointments, when I see a list of my appointments, I would like to know what time zone the appointment time is for, so that I will know when to show up.

# CHIP Dependencies
[Spike Ticket](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/399)

## Tasks
- [x] Create final mockups with callouts 
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [x] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## Delivery
PCI/CI wireframes are validated and found that one wireframe was showing the time zone incorrectly in the PCI in-person flows although it isn't shown in the collection. - The wireframe is fixed, and there is no impact on FE engineering.

Collection links:
[Latest CI collection](https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a): **Time zone added to an In-person wireframe**
[Latest PCI collection](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b): No change

**Comment by zach-park** [comment]
@loripusey PCI/CI wireframes are validated and found one wireframe that was showing the time zone incorrectly in the in-person flows (note: it isn't shown in the collection) which is updated now. 
Collection links:
[Latest CI collection](https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a): **Time zone added to an In-person wireframe**
[Latest PCI collection](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b): No change

**Comment by loripusey** [comment]
@zach-park I'm confused, why does the Master copy show time zone when we don't have it in the product yet? I thought Master was supposed to be what is in production?  Also, the DOB fields still show as the old DS control and is not in production yet. Can you clarify for me what is going on?
@kristenmcconnell

**Comment by zach-park** [comment]
Hi @loripusey, I thought they were already implemented. It doesn't seem to be the case, I'll annotate them in the collection as it would be in future releases to avoid any confusion. 
It does not look like the updated DOB fields (i.e., aligned with new DS components) are merged yet. @ytsaoca , can you please confirm if that is true?

**Comment by loripusey** [comment]
@zach-park that is correct, we will push the DOB fields to production at the end of this Sprint.

**Comment by ytsaoca** [comment]
@loripusey The original design included the time zone when it was built for usability testing. But the release of timezone function was postponed because of engineer efforts and we didn't  change the design at that time. I think we need to make it clear about what is the completed design and the current design for development.

**Comment by zach-park** [comment]
@loripusey note is added to the collections. Cc: @ytsaoca @kristenmcconnell
