### ISSUE TITLE
Resolve connection issues with MVI

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3939]
## User Story:
As a Backend Engineer on the Benefits and Memorials team, I need to help MVI identify and resolve connection issues in order to gain access privileges to the add profile end point so that I can move forward with testing between our environments.

## Tasks
- [x] Identify MVI needs
- [x] Provide MVI with needed information and details

## Acceptance Criteria:
- [x] Connection issues have been resolved
- [x] Dev to dev (and other environments) testing can move forward

**Comment by SMLuthi** [comment]
Another set of attempts was made today to try to get a connection but we are still getting back a SERVER ERROR when making an `add_person` response. The results have been sent forward to the MVI team and we are waiting for a response.

**Comment by SMLuthi** [comment]
A successful request has finally been made. Its been done by a payload provided by MVI. I will have to exhaustively compare the two payloads to see why the one we build is failing. Most likely its some kind of minute inconsistency... or a bad user. To be honest, it could be any number of things since the error response does not give an explanation.

**Comment by SMLuthi** [comment]
I have reapplied the `blocked` tag. Dozen of different attempts have been made to their dev environment endpoint to try to get a successful call through but it has not been possible. The only call that has succeeded is the hard coded request payload provided by one of their engineers that, when looking over it, was generated by a XML GUI and does not include some fields that are required for our request. Further assistance is required from MVI.

**Comment by SMLuthi** [comment]
This issue continues to be a debug fest via email. Progress has been made in that we have cured some error responses we've seen. However, currently, we are seeing a very generic `Internal Error (from server)` coming back from MVI. They are looking in to what this could mean (they surmise it has something to do with our XML headers and how they are setup).

I've proposed a debug meeting to them where engineers from both groups could show up and life debug the issue. Hopefully they are receptive to this idea so that we can speed the resolution of this issue along.

**Comment by SMLuthi** [comment]
Update:

Connectivity has been established and requests are passing the MVI VAAFI lair. Another error response has been encountered due to the search token functionality. Apparently some changes need to be made on how we make a `find_profile` call since it returns a search token. But the search itself must contain specific data that will all the `add_person` call to function properly.

A meeting has been proposed next week with Linda to establish these guide lines.

**Comment by SMLuthi** [comment]
The meeting has concluded successfully and we have good connectivity with MVI. Technically this ticket has been completed but it will remain open until the end of the sprint to verify that iDEV testing has concluded successfully as well (though that isnt technically in the scope of this ticket).

**Comment by luke-gcio** [comment]
> (though that isnt technically in the scope of this ticket).

I will close this ticket out and create a new one.  Otherwise we are dragging it around.  This guy has been around long enough!
