### ISSUE TITLE
Traefik and OpenResty comparison

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39404]
## Issue Description
Currently we use OpenResty for a reverse proxy. In the future, we would likely want to use the EKS Ingress controller to perform the same functions as OpenResty, and retire OpenResty. 

The EKS Ingress controller currently in use by the platform is Traefik (traefik.io) Community Edition

We would need to determine if Traefik's middlewares functionality can provide the same functionality we currently have implemented in OpenResty, so that we can know if we can use Traefik as-is to replace the reverse proxy.

---
## Tasks
- [ ] Investigate features we are using in OpenResty
- [ ] Compare those features to features available in the community edition of Traefik
- [ ] Determine if there are any future functionalities that are desired and if Traefik can fulfill those (May not be part of the decision but good to know)

##Suggestions/Links:
- [ ] https://doc.traefik.io/traefik/
- [ ] https://openresty.org/en/

## Acceptance Criteria
- [ ] A determination has been made if Traefik can provide the same functionality as we currently use in OpenResty
- [ ] Documentation of features we currently use in OpenResty and equivalent function/middleware in Traefik is in Confluence

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
Determined that Traefik and middleware/featureset should be able to do everything that OpenResty is currently doing as revproxy. 

This could be documented in the future.

**Comment by alwerner** [comment]
@madebydna Do we still need this ticket?

**Comment by madebydna** [comment]
I think we should close it with a "Won't Do." Creating detailed documentation on the differences between the two technologies is outside of our current limited scope and wouldn't add much value.

**Comment by alwerner** [comment]
Closing as outside of scope.

cc: @madebydna
