### ISSUE TITLE
Determine the traffic flow that vets-api uses to access Lighthouse APIs, and write RFC for the plan to direct this traffic

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39406]
## Issue Description
We need to determine if connections to vets-api endpoints that use Lighthouse APIs as an upstream dependency correctly use the forward proxy to make those connections, or if they are made through Kong directly.

---
## Tasks
- [x] Research all cases in which vets-api makes direct use of Lighthouse APIs
- [x] Investigate the role of Kong in routing requests to the forward proxy (e.g. adding rate limiting)
- [x] Investigate configuration of forward proxy to determine if it adds value/is needed in the new architecture
- [x] Write RFC for how this traffic will get to Lighthouse APIs in the absence of Kong
  

##Suggestions/Links:
- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/fwdproxy-vagov-dev.yml
- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/fwdproxy-vagov-staging.yml
- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/fwdproxy-vagov-prod.yml
- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/fwdproxy-vagov-sandbox.yml

## Acceptance Criteria
- [x] We have determined whether there is a current configuration for FWD Proxy which goes to Kong
- [x] We have documented the forward proxy Kong ports (if any)
- [x] RFC for how vets-api will connect to Lighthouse once Kong is no longer in our environment is written

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
