### ISSUE TITLE
[OBE] HLR: Edit issues on the Review Submission page

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3941]
## User Story:
As a Veteran, I need to be able to edit my issues on the Review Submission page so that I can incorporate updates to sections prior to submitting my Higher-level Review.

## Tasks
- [ ] add contested issues/legacy issues
- [ ] remove contested issues/legacy issues
- [ ] adjust answer to, “Would you like the same office that issued your prior decision to conduct the review?” question
- [ ] adjust answer to, “Please add anything you want the reviewer to consider when going over your request.” question 

## Acceptance Criteria:
- [ ] Contested issues and Legacy issues on the Review Submission page can be edited by the user
- [ ] Conducted peer review

**Comment by YanaRoy** [comment]
@kevinstachura

**Comment by luke-gcio** [comment]
Truly OBE at this point, handled by other HLR work specifically the tickets under the design Epic.
