### ISSUE TITLE
Collaboration Cycle for VA Notify Forms Strike Team - In Progress Reminders

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#39414]
[Note: This issue is for testing purposes and is not a live issue.]

# Collaboration Cycle for VA Notify Forms Strike Team - In Progress Reminders

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Complete the **[VFS product information](#vfs-product-information)** and **[kickoff questions](#kickoff-questions)** sections, and attach any **[artifacts](#artifacts)** you have available.

**Platform**

- [x] Review the responses and update the ticket with recommended touchpoints and practice area involvement.
- [x] Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

Skip to...
- [VFS product information](#vfs-product-information)
- [Kickoff questions](#kickoff-questions)
- [Collaboration Cycle touchpoints](#collaboration-cycle-touchpoints)

## <a id="vfs-product-information">VFS product information</a>
- **Product Name:** VA Notify
- **Feature Name:**             
- **VFS Team Name:** VA Notify Strike Team
- **GitHub label for product:** vanotify     
- **GitHub label for feature:**     
- **Start date of enhancement:** 3/1/2022
- **Feature launch date:**
- **Production URL:**
- **ServiceNow ticket number tracking known accessibility issues:** 

## <a id="kickoff-questions">Kickoff questions</a>
<details>
  <summary>Toggle kickoff questions</summary>
  
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.
  
**1. Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**2. Are you doing research with VA.gov users?**
- [x] Yes
- [ ] No

**3. Will your work involve changes to: (select all that apply)**
- [x] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

  
**4. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [x] Yes
- [ ] No

  
**5. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [ ] Yes
- [x] No

**6. Who is the VA business owner for this product?**
- [x] VHA (Veterans Health Administration)
- [x] VBA (Veterans Benefits Administration)
- [x] NCA (National Cemetery Administration)
- [x] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________
    
</details>

### Kickoff artifacts
  
- [x] [Product outline](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Strike/In%20Progress%20Notifications/read.md)  

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [x] Have Matt Dingee review your proposed designs
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click Schedule Event
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add design artifacts to the [Artifacts section](#design-intent-artifacts) of this ticket at least two days before the scheduled Design Intent
  
##### Platform actions
- [x] Add Platform reviewers to the scheduled Design Intent meeting
- [x] Add Zoom information for the scheduled Design Intent meeting
  
#### Design Intent meeting details
  
- Meeting date/time: 3/17 at 1:30pm ET
- Zoom meeting URL: https://www.google.com/url?q=https://us06web.zoom.us/j/86554073277&sa=D&source=calendar&ust=1649124701088594&usg=AOvVaw3XwgRMhAMSGnn2yDWgui1_
- Zoom password: o^X286bA
- Zoom recording: https://us06web.zoom.us/rec/share/AUqZU8ceYjayKH2trNEs5Zdb2TqOzw1kSov8iPiMhvXs3AaTRj95ftAHAChdeDpr.McJgZYWC9PG5B9ck
  
##### Platform actions

- [x] Create feedback tickets and link to this epic (if no feedback, please comment stating that)
  - [x] Design feedback provided
  - [x] Accessibility feedback provided
  - [x] IA feedback provided
- [x] Update this ticket with the Zoom recording
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061)
  
##### VFS actions

- [x] Respond to feedback tickets

##### Design artifacts

- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] [User flow](https://app.mural.co/t/oddball5855/m/oddball5855/1645722089026/e305013d25f92df84c16583b7ae4ea70aa34395c?sender=ian7950)

##### IA artifacts

- [x] [User flow](https://app.mural.co/t/oddball5855/m/oddball5855/1645722089026/e305013d25f92df84c16583b7ae4ea70aa34395c?sender=ian7950)
  
</details>

### Midpoint Review
<details open>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click Schedule Event
- [x] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add or update all requested artifacts to the [Artifacts section](#midpoint-review-artifacts) of this ticket at least two days before the scheduled Midpoint Review
  
##### Platform actions
- [ ] Add Platform reviewers to the scheduled Midpoint Review meeting
- [ ] Add Zoom information for the scheduled Midpoint Review meeting (if synchronous)

#### Midpoint Review meeting details (if synchronous)

- Meeting date/time:
- Zoom meeting URL:
- Zoom password:
- Zoom recording: 

##### Platform actions

- [ ] Create feedback tickets and link to this epic (if no feedback, please comment stating that)
  - [ ] Design feedback provided
  - [ ] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided
- [ ] Update this ticket with the Zoom recording
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061)
  
##### VFS actions
  
- [x] Respond to feedback tickets
  
##### Design artifacts

- [x] [Finalized design prototype or mockup](github.com)
  
##### Research artifacts

- [x] [Research plan](github.com)
- [x] [Conversation guide](github.com)
  
##### IA artifacts

- [x] [Github ticket for any relevant IA work](github.com)
  
##### Content artifacts
  
- [ ] Name of content of truth, for example, "Invision Prototypes"
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

##### QA artifacts
  
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] [Regression test plans](testrail.com) (if there isn't already a regression test plan for this feature in TestRailProduct)
- [x] Link to test cases/test plan in TestRail (draft OK)
  
</details>
