### ISSUE TITLE
**TIME SENSITIVE** BE - Auth Profile - VA Profile SSL Cert Updates 4/4 - 4/14

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39429]
## Background

See text of email below. 

> From: Richard, Michael R. (GovernmentCIO) <Michael.Richard2@va.gov> 
> Sent: Wednesday, March 30, 2022 4:08 PM
> To: VETSGOV-DEVOPS-MAINTENANCE@listserv.gsa.gov; EPMD VES CMDM Releases <EPMDVESCMDMReleases@va.gov>; VA Profile PROD <VAProfileProd@va.gov>; VA Profile NonPROD <VAProfileNonProd@va.gov>
> Cc: VA Profile OM <VAProfileOM@va.gov>
> Subject: FW: VA Profile Certificate Update - ATTENTION REQUIRED
>  
> VA Profile Partners (Action Required),
>  
> We are reaching out to let you know that we will be updating the following certificates that are set to expire 5/1/22.    Partners may need to update mutual SSL/Truststore with new certificate.   Please ensure this information is shared with the application resources who can make the certificate updates for your application.  
>  
> New certificates are issued by a different Intermediate Certificate Authority (ICA) than the ICA that used to issue the old certificates.
> The new CA is VA-Internal-S2-ICA4.  Here is an example of the certificate path for the new cert:
>  
>  
> The new certificates have been attached to this email including root and new intermediate certificates
>  
> List of the servers with new certs:
>  
>  INT   - Monday 4/4/22 - 5PM ET
> int.vaprofile.va.gov
> int.static.vaprofile.va.gov
> 
> QA   - Wednesday 4/6/22 - 5PM ET
> qa.vaprofile.va.gov
> qa.static.vaprofile.va.gov
>  
> 
> PREPROD   - Monday 4/11/22 - 5PM ET
> ppd.vaprofile.va.gov
> ppd.static.vaprofile.va.gov
>  
> 
> PRODUCTION   - Thursday 4/14/22 - 6PM ET - CHG0265216
> www.vaprofile.va.gov
> prd.vaprofile.va.gov
> www.static.vaprofile.va.gov
> prd.static.vaprofile.va.gov
>  
>  
>  
> We have set up the following meetings from Thursday 4/14/22 6 PM to 8 PM ET, and Friday 4/15/22 8:00 AM to 12:00 PM ET to assist with any issues or questions with implementation of the new certificate.
>  
>  
> Thursday Night partner testing call:
> ________________________________________________________________________________ 
> Join on your computer or mobile app 
> Click here to join the meeting 
> Or call in (audio only) 
> +1 469-551-3381,,333245447#   United States, Dallas 
> Phone Conference ID: 333 245 447# 
> Find a local number | Reset PIN 
> Learn More | Meeting options 
>  
>  
> ________________________________________________________________________________ 
>  
> Friday Morning partner testing call:
> ________________________________________________________________________________ 
> Microsoft Teams meeting 
> Join on your computer or mobile app 
> Click here to join the meeting 
> Or call in (audio only) 
> +1 469-551-3381,,428374647#   United States, Dallas 
> Phone Conference ID: 428 374 647# 
> Find a local number | Reset PIN 
> Learn More | Meeting options 
>  
>  
>  
> If you have any questions or concerns, please contact any or all the following POCs:
> John Nguyen  giang.nguyen1@va.gov
> Reid Bush edward.bush@va.gov
> Saj Shaikh Sajid.Shaikh@va.gov

 

<hr>

## Tasks
- [ ] Determine who will need to replace the certificates and document in this ticket
- [ ] Test on each environment using dates listed above

## Acceptance Criteria
- [ ] Determine who will need to replace the certificates and document in this ticket
- [ ] Test on each environment using dates listed above

**Comment by tpharrison** [comment]
Thanks @MarciMcGuireGCIO!

**Comment by Samara-Strauss** [comment]
So based on #36578 and #37577, it sounds like the certs may have already been updated for the dev environment, but it's not clear to me whether anything was done with staging or prod. I'll raise this to devops now.

**Comment by MarciMcGuireGCIO** [comment]
🥳 Thanks for staying on top of this @Samara-Strauss !
