### ISSUE TITLE
Front-end Accessibility Testing Checklist | Before Staging |

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#39440]
## Front end tasks

- [x] Run axe checks using the Chrome or Firefox browser plugin
- [x] Axe scans included in end-to-end (e2e) tests
- [x] Color tests for proper contrast and colorblindness
- [x] Content zoomed to 200%, 300%, 400%
- [x] Navigate using the keyboard only
 
(Foundational Accessibility Tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html)
