### ISSUE TITLE
Discovery: Stakeholder Interview with DLC Customer Service Lead

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#3944]
## User Story or Problem Statement
As a UX designer, I need to conduct an interview with the CS Lead at the DLC so that we can gain more insights into the problems customer service agents and their customers are experiencing with the current service for use during synthesis.

## Tasks
- [x] Create an agenda with goals and questions
- [x] Schedule interview with Jeff Robillard
- [x] Hold Meeting
- [x] Write up notes and upload to GH

## Acceptance Criteria
- [ ] Agenda completed
- [ ] Meeting occurred
- [ ] Notes are written and uploaded to GH
- [ ] Findings are shared with team via Slack

## Next Steps
- Veteran Interviews
- Synthesis

## Blockers / Dependencies
- Pending meeting availability

**Comment by rebeccawalsh** [comment]
Here are the notes from the meeting in Github: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/meetings/20191206-DALC-customer-service-stakeholder-.md

**Comment by wygonikGCIO** [comment]
Riley/Becca can "Hours" be added to the Task sections. Please ball park the hours.  (i.e. Task: interviews: 10 hours)
