### ISSUE TITLE
HLR v1: Remove API endpoint

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39445]
## Description

Lighthouse is still seeing v1 endpoint calls, and since we have v2 at 100% in production we can remove the v1 endpoint call. All in-progress v1 forms _should_ migrate their data to v2.

We're planning to remove the v1 endpoint call and force data migration to v2.

## Tasks

- [ ] Remove v1 endpoint call
- [ ] Force migration of v1 data to v2
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Deferring this change until the [new benefit types are added to HLR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37470).
