### ISSUE TITLE
[Infrastructure/Terraform] Move Terraform for EKS applications to ./applications folder

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#39453]
## Description
In an effort to adopt a Terraform standard for EKS applications on the platform, we are moving Terraform code out of environment-specific folders and into application specific ones.

## Background/context 
https://vfs.atlassian.net/wiki/spaces/OT/pages/2075721739/Terraform+Standard
https://github.com/department-of-veterans-affairs/va.gov-team/issues/36297

---
## Tasks
For each application in an environment-specific folder, move code to `terraform/applications/<app name>` in the devops repo. Use `terraform import` statements to import already existing resources into a new statefile for each environment. Then use `terraform state rm` commands to remove these resources from the old statefiles without modifying the actual resources.
- [x] loki
- [x] grafana (dev and utility only)
- [x] keycloak (dev and utility only)
- [x] argo (utility only)
- [x] sentry (utility only)
- [x] EKS cluster itself

## Acceptance Criteria 
- [x] All Terraform code for EKS applications has been moved to `terraform/applications/`
- [x] No EKS application remains in the large environment-specific statefiles
