### ISSUE TITLE
FE - Auth Profile - Notification Preferences- Update content for edge cases

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39459]
## Background

There are two edge cases that can occur which need to have content that is applicable:

> The user has the notification set, and their facility has changed to a non-supporting facility.
> 
> The user has the notification set, and they have multiple facilities listed and some facilities do not support the RX tracking notification.
> 
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/38187#issuecomment-1083204300

In a [Slack thread](https://dsva.slack.com/archives/C010R6AUPHT/p1648580313434989?thread_ts=1648478120.717959&cid=C010R6AUPHT), Paras Shah confirmed that the language in a mockup Liz had already created will work in those scenarios.

![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/8c15b57d-029a-41f5-977c-6f0ab511ea67)

## Tasks
- [x] Update the current text to display the following message when either of the above-described edge cases occurs:
"Only available at some VA health facilities. Check with your VA pharmacy first." 
- [x] Deploy to Staging
- [x] Update PM when ready to be validated

## Acceptance Criteria
- [x] Update the current text to display the following message when either of the above-described edge cases occurs:
"Only available at some VA health facilities. Check with your VA pharmacy first." 
- [x] Deploy to Staging
- [x] Update PM when ready to be validated

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 hey!  Can you please pop an estimate on this ticket when you have a chance?  Thx!!

**Comment by adamwhitlock1** [comment]
@Samara-Strauss and @SKasimow I have deployed this to staging, and using test user 36 I am able to see the notification, but since the user doesnt have a mix of supporting facilities in their profile I dont see the help text. 

I also didnt see any test users in our docs that have a mix of facilities, but I did use my devtools in staging to simulate this kind of state and could get the help text to show up, to at least validate visually.

![Screen Shot 2022-04-05 at 9.14.55 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/7ebc726a-3e85-42c0-9ab2-fa4fae4b74ad)

**Comment by Samara-Strauss** [comment]
Great! Looks good to me!
