### ISSUE TITLE
[Design] Create Error Message Wireframe for Blank DOB State

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39468]
## Background Information
When Adrian and I were reviewing the app in Spanish and Taglog, we realized something about the SSN to DOB change that we need to make. We will need the error wording for the blank DOB state. The date picker component allows for variable error state/blank messaging, so we need to determine what wording we want. We need a ticket to create this wording.

## User Story
As a Veteran, when I want to login to do pre-check-in or check-in, if I leave the DOB blank I would like to see an error message telling me that it is required.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
We need a wireframe and wording for the error message for the scenario where the DOB for LoROTA authentication is blank.

## Tasks
> this is a list of design tasks that are needed for this ticket
- [x] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] %Add any additional Tasks%

## Acceptance Criteria
> when is the ticket done
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] %Add any additional Acceptance Criteria%

## UX Deliverable
- The [wireframe](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbPga5K) is ready: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbPga5K

**Comment by zach-park** [comment]
The wireframe is ready for review: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/rbPga5K
@loripusey @niradatta1 @kristenmcconnell @acrollet @brianseek 

Hi @niradatta1 , please let me know what you think from the content pov.

**Comment by loripusey** [comment]
Looks good!
