### ISSUE TITLE
[UX] Update Product Guides for Spanish Translation

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39478]
## Description
We need to update the Product Guides based on our new Spanish Translation feature

## Tasks
- [ ] Update the PCI and CI Product Guides, including content and screenshots
- [ ] Push changes to GitHub files
- [ ] Notify the Contact Center of the changes
- [ ] Notify Training of the changes

## Acceptance Criteria
- [ ] Content has been updated
- [ ] Screenshots have been updated
- [ ] Contact Center is aware of the changes
- [ ] Training is aware of the changes
