### ISSUE TITLE
Reorganize Platform landing pages for "Research and design" and "Collaboration cycle" sections

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#39472]
## User Story
_"As a VSF team member, I want to easily find important Research and Design guidance, so that I'm confident my work follows VA.gov principles and aligns with their standards."_

_"As a VSF team member, I want to easily find important Collaboration Cycle guidance, so that I understand what's expected of me during the process and can find answers to my CC questions."_

_"As a user of the Platform pages, I want the site to have a similar layout across areas, so that I can easily navigate to important information."_

- Intended Audience: VSF teams, all Platform page users
- Desired Outcome: 
- Due Date: 

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The current state of Platform area landing pages:
- 4 of 6 are organized in a similar way, with links to subpages
- The [Platform area landing page for Research and Design](https://depo-platform-documentation.scrollhelp.site/research-design/) and the [Platform area landing page for Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) present information instead of links. While we aren't sure if this poses an issue, nonconformity is a risk factor.
- Additionally the Research and Design left navigation links are focused on research. Since, important sections for Design, Content, IA, Accessibility are well below the fold of this area landing page, and they don't have their own links in the left nav, this may reduce findability 

Additional background for [Launch new Platform Orientation](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/13709) initiative <br />
Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />
Additional background for [Collaboration Cycle - Transition VFS research activities to Platform](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/32698) initiative

## Artifacts Potentially / Confirmed Needing Updates
- [Platform area landing page for Research and Design](https://depo-platform-documentation.scrollhelp.site/research-design/)
   - Changes for which are made on the [Research and Design Confluence page](https://vfs.atlassian.net/wiki/spaces/RD/overview)
- [Platform area landing page for Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
   - Changes for which are made on the [Collaboration Cycle Confluence page](https://vfs.atlassian.net/wiki/spaces/CC/overview)

## Tasks
- [ ] Understand if there is a legitimate need for the Collaboration Cycle and Research and Design area landing pages to be different from the other four
- [ ] Consider what requirements Platform has for page uniformity
- [ ] Discover if there is a difference in findability on the four area landing pages with links compared with the two Governance Team areas that contain information
- [ ] If these two pages are found to need to conform with the other four, modify to conform.
- [ ] Further consider modifications to Research and Design area page and left nav links
- [ ] Conduct a Card Sort and/or other IA exercise to discover the best way to organize the information contained in this area
- [ ] Modify the Research and Design sitemap, left nav, and other components based on the exercise(s)

## Acceptance Criteria
- [ ] "[Platform area landing page for Research and Design](https://depo-platform-documentation.scrollhelp.site/research-design/)" on Platform Website has been updated per guidance
- [ ] "[Platform area landing page for Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)" on Platform Website has been updated per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
After thinking about this more and after talking with the Content/IA team
- I've changed this ticket to focus on the Research and design section and taken out the Collab Cycle section
- Content/IA team verified that there was no present objection with our area pages including content along with the links, differing from the other 4 main area pages that just have links and no content.
- Content/IA team agreed that the next steps for this would be research to further consider and validate best way forward on nav link changes.

**Comment by claytonzook** [comment]
@jimuhh Tagging you here for your expertise on this ticket

**Comment by shiragoodman** [comment]
@naomimarcussen this was in reference to updating the Research and Design landing page on Platform Website. I know you made changes recently... do you think this ticket is still relevant?

**Comment by naomimarcussen** [comment]
@shiragoodman I don't think it's relevant anymore. We updated the [page referenced here](https://depo-platform-documentation.scrollhelp.site/research-design/) which includes a link to learn more about the Collaboration Cycle. I think we can close this.

**Comment by shiragoodman** [comment]
sounds good - thank you!
