### ISSUE TITLE
[SW-Content] Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 5/2

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39484]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Robert Bonner
Ronald Pipkins

## Tasks
- [x] Replace text and videos (Aliyah)
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by RLHecht** [comment]
Update: Pulling this ticket into Sprint 73 with new content team. 

@aliyahblackmore The documentation for how to make these updates is in the comment above. When you're ready to work on this, you can review it and we can either screen share or I can look at the preview after.

**Comment by aliyahblackmore** [comment]
Noting here that the current people on the live page are Patricia Victor and John McAllister. I will swap out these names for Robert Bonner and Ronald Pipkins.

**Comment by aliyahblackmore** [comment]
Hi @megzehn  videos were swapped out (names, images, and videos changed) following the above instructions from Selina. [Preview link](http://preview-prod.vfs.va.gov/preview?nodeId=19578). Note that Patricia Victor and John McAllister were the names previously on the page, so the change actually needed to be made to **Robert Bonner and Ronald Pipkins.**

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
