### ISSUE TITLE
[SW-Content] Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 5/23

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39485]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

Patricia Victor
John McAllister

Documentation for how to swap videos: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [x] Replace text and videos (Aliyah)
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by megzehn** [comment]
Thanks @aliyahblackmore!  Looks good. Just published. 

@RLHecht, could you create a ticket for the next update?

**Comment by RLHecht** [comment]
changes are live. Closing ticket.
