### ISSUE TITLE
[SW-Content] Review and update "Home-loans/eligibility" page [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#39487]
## Story 
As a Veteran I need to have accurate information regarding my home loan eligibility, so I know what is required and how to proceed.

## Resources
[Home loans-eligibility](https://www.va.gov/housing-assistance/home-loans/eligibility/)

[https://app.zenhub.com/files/133843125/b3a1f4fe-b77f-4962-848a-13626e9d4d00/download](https://app.zenhub.com/files/133843125/b3a1f4fe-b77f-4962-848a-13626e9d4d00/download)

## Task(s)
- [x] Review updates to home loans eligibility page
- [x] Submit review and updates to editing
- [x] Publish final updates for stakeholders

## Acceptance Criteria
* Stakeholder has access to review published updates

**Comment by lunascoop** [comment]
@psanders86 this page is ready for review. I made all the changes but reworked the content in parenthesis after the Gulf War. It seemed redundant. And I'm not sure the current version is technically correct. I looked at the content on some of our [Gulf War](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/gulf-war/) pages as an example ([this one too](https://www.va.gov/health-care/eligibility/)). I got the Gulf War end date from the Health care eligibility page.

Changed text to: Between August 2, 1990, and November 11, 1998 (Gulf War), **or**
Between November 12, 1998, and the present (post-Gulf War period)
Eligibility requirements for VA home loan programs: http://preview-prod.vfs.va.gov/preview?nodeId=753

**Comment by psanders86** [comment]
@RLHecht I reviewed and made a tweak here, but it's ready to go. These are relatively minor changes.

I've also suggested that at some point we take the information here in charts and put it in a different format that's better for accessibility, but that won't be addressed right away.

**Comment by RLHecht** [comment]
Thanks, @psanders86 I reviewed and published this. Beth said it was OK to skip her review since the changes were all minor and the language used was already elsewhere on the page. I'll move to validate and let the stakeholder know once the changes are live.

**Comment by RLHecht** [comment]
Work complete on this and page is live. Closing ticket.
