### ISSUE TITLE
[Design] NOD Flow Diagram

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3949]
## User Story:
As a designer on the BaM team, I need to identify the business process and steps taken when a NOD form (10182) is submitted.

## Tasks
- [x] Research and understand process that form undergoes after submission
- [x] Create flow diagram

## Acceptance Criteria:
- [x] Flow diagram created

**Comment by kevinstachura** [comment]
Miro board for the business process flow of NOD can be located here: https://miro.com/app/board/o9J_kvkRLHs=/
