### ISSUE TITLE
Migrate vagov-heartbeat

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39503]
## Issue Description
`vagov-heartbeat` canary needs to move out of AWS Cloudwatch and into Datadog.

---
## Tasks
- [x] Analyze the Cloudwatch version of the synthetic
  * Consider PagerDuty alerts
  * Consider Slack notifications
  * Consider schedule
- [x] Re-create the behavior of the Cloudwatch version in Datadog
- [x] Monitor the new Datadog monitor for any unexpected failures

## Acceptance Criteria
- [x] Datadog synthetic monitor alerts PagerDuty when meeting fail threshold
- [ ] Datadog synthetic monitor is included in a synthetic monitor dashboard
---

**Comment by ddzz** [comment]
We've reached our quota for browser tests in Datadog, so I can't create a new monitor for this canary.

**Comment by ddzz** [comment]
This monitor runs once every five minutes. It is retried once if it fails. #platform-qa-standards will be notified of any failures.
