### ISSUE TITLE
Create a Dashboard to Collect and Display Synthetic Monitors

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39506]
## Issue Description
In order to observe and assess the state of the synthetic monitors hosted in Datadog, we need to create a dashboard displaying their current and historical status.

---
## Tasks
- [ ] Create a dashboard for the purpose of displaying synthetic monitors
- [ ] Include the original set of 4 monitors on the dashboard

## Acceptance Criteria
- [ ] Synthetic Monitor Dashboard exists
- [ ] Users are able to view the current status of all Datadog hosted synthetic monitors on the platform
- [ ] Users are able to interact with a given synthetic monitor and view it's historical status
---

**Comment by pjhill** [comment]
This ticket is a dupe of [39692 ](https://app.zenhub.com/workspaces/planning-board-qa-standards-612411db8ec47700127369e2/issues/department-of-veterans-affairs/va.gov-team/39692)which is in a better state. Closing
