### ISSUE TITLE
Collaborative Notes Spreadsheet for User Interview Sessions

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#3950]
## User Story:
As a UX Designer conducting user research sessions, I need to create a collaborative spreadsheet so that I can have one location where all notes from each user session can live and be categorized by participant and question.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Create a Google Sheet containing questions from the conversation guides associated with each participant- 1-2 hour(s) - Riley
- [x] Add columns for note takers to add their notes corresponding to the appropriate question - 15 min - Riley
- [x] Share the document with the team prior to beginning user interviews -  5 min - Riley

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] The document has been shared with the team prior to beginning user interview sessions

## Blockers/Dependencies
- ~~Perigean needs to provide the design team with a roster of participants so the questions can be formatted to align with their ordering needs~~ Perigean has provided the roster. No blockers remain.

## Next Steps
- Conduct the user interview sessions and update the spreadsheet after each interview

**Comment by rileyorr** [comment]
@wygonikGCIO This ticket can be closed. I've created the document and it is now in the phase of being filled out for synthesis.
