### ISSUE TITLE
Migrate dslogon_status

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39502]
## Issue Description
`dslogon_status` needs to move out of AWS Cloudwatch and into Datadog.

---
## Tasks
- [ ] Analyze the Cloudwatch version of the synthetic
  * Consider PagerDuty alerts
  * Consider Slack notifications
  * Consider schedule
- [ ] Re-create the behavior of the Cloudwatch version in Datadog

## Acceptance Criteria
- [ ] Datadog synthetic monitor alerts PagerDuty when meeting fail threshold
- [ ] Datadog synthetic monitor is included in a synthetic monitor dashboard
---

**Comment by pjhill** [comment]
Business case here TBD. Need to discuss

**Comment by rbeckwith-oddball** [comment]
This monitor has now been implemented [here](https://app.datadoghq.com/monitors/68069410). We can discuss the requirements in the epic ticket.

**Comment by pjhill** [comment]
It looks like this monitor is classified differently than the other synthetics. What's going on with the `Synthetic Test` field and `Message` field here?
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/31796f02-9ee4-4186-988a-d77e74ba3fdd)

**Comment by JoeTice** [comment]
Assigning to @ddzz for review

**Comment by pjhill** [comment]
DS Logon status will not alert PagerDuty because the service is monitored through other means.
