### ISSUE TITLE
Migrate data-fetch

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39504]
## Issue Description
`data-fetch` canary needs to move out of AWS Cloudwatch and into Datadog.

---
## Tasks
- [ ] Analyze the Cloudwatch version of the synthetic
  * Consider PagerDuty alerts
  * Consider Slack notifications
  * Consider schedule
- [ ] Re-create the behavior of the Cloudwatch version in Datadog
- [ ] Monitor the new Datadog monitor for any unexpected failures

## Acceptance Criteria
- [x] Datadog synthetic monitor alerts PagerDuty when meeting fail threshold
- [x] Datadog synthetic monitor is included in a synthetic monitor dashboard
---

**Comment by ddzz** [comment]
Monitor has been created: https://app.datadoghq.com/synthetics/details/znt-vbn-cu8

**Comment by ddzz** [comment]
This monitor runs once every five minutes. It is retried once if it fails. #platform-qa-standards will be notified of any failures. I will monitor this test for the next few days for any unexpected failures.

**Comment by JoeTice** [comment]
Having issues:
- with this monitor failing due to the Foresee survey (occurs about 10% of time)
- requires login, which means it needs to run on staging

Mitigation:
- Continue research on workaround, ask infrastructure team
- Ask Infrastructure about thoughts on whether this has value in its current state on staging

**Comment by ddzz** [comment]
I was able to find a potential workaround for the survey issue without needing to use custom JavaScript. After I have this working I'll let it run for a few hours to see if it still fails.

**Comment by pjhill** [comment]
This monitor was renamed `VA.gov login`. Based on discussion with other stakeholders, the monitor is in place and will not be alerting PD.
