### ISSUE TITLE
Migrate va.gov search

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39505]
## Issue Description
`vagov-search` canary appears to be in an [error state](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#synthetics:canary/detail/vagov-search). Still, let's move this out of AWS Cloudwatch and into Datadog.

---
## Tasks
- [x] Analyze the Cloudwatch version of the synthetic
  * Consider PagerDuty alerts
  * Consider Slack notifications
  * Consider schedule
- [x] Re-create the behavior of the Cloudwatch version in Datadog

## Acceptance Criteria
- [x] Datadog synthetic monitor alerts PagerDuty when meeting fail threshold
- [x] Datadog synthetic monitor is included in a synthetic monitor dashboard
---

**Comment by pjhill** [comment]
Answers to questions around failures and alerting:
1. CloudWatch was setup with the following rule --

> To prevent overly noise errors to PagerDuty, change the Period to ‘15 minutes' then define the alarm condition as Greater/Equal to 2. This means the failure must occur at least twice within a 15 minute period to trigger an alert to team members.

Is a similar behavior possible in DataDog? In other words can we execute the test say every 5 minutes, and if we get two failures in a 15 minute period then we alert?
2. What are the choices? This affects what exactly?
3. #oncall is where CloudWatch was pointed, I believe
  a. The current rules are above -- if we can re-create that then that would be best.

**Comment by ddzz** [comment]
@rbeckwith-oddball the Datadog test does not include any assertions around the search results, but the canary does. Can we add assertions?

**Comment by rbeckwith-oddball** [comment]
Added an assertion for the search results @ddzz

**Comment by pjhill** [comment]
@rbeckwith-oddball -- Couple Q's --
1. How often is this alerting?
2. If it appears to be alerting on the error conditions but nothing requires intervention then we should tune the alerting.
3. Is this connected to PagerDuty?
4. The previous monitors alerted to Slack only via PagerDuty I believe, is that right? These monitors appear to be alerting Slack directly with failures.
