### ISSUE TITLE
Content support for VRRAP High Demand Occupation List page from AFS Comparison Tool

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#39511]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Sitewide Content needs to edit the High Demand Occupation list page for plain language standards. The team needs to review and edit both the paragraphs of text as well as the form labels before this goes to the midpoint review. 
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

The wireframe of the new content: 

https://user-images.githubusercontent.com/86262254/160937512-387b97d7-80f5-4d07-886b-202d2610e037.png

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager:  Abe Blanco
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@RLHecht could you type out in the ticket here the wall of text from the wireframe, under "Instruction"?

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here you go:

**Instruction:** Before completing your VRRAP application, first, please review the available High Demand Occupation (HDO) List on the VA GI Bill Website [Veteran Rapid Retraining Assistance Program (VRRAP) | Veterans Affairs (va.gov)](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/) to choose the name of your High Demand Occupation, the number next to the HDO, and the name of the Program. After you have gathered that information, please return to this electronic VRRAP application to complete it. 

The Veterans Rapid Retraining Assistance Program (VRRAP) provides training towards an Associate's Degree, Non-College Degree, or Certificate that leads to a High Demand Occupation (HDO), as determined by the Department of Labor.

Please provide the information below to indicate the High Demand Occupation and VRRAP program to which you would like to pursue toward achieving your Vocational Objective. Please use the HDO information you have gathered to provide the name of the HDO, the associated number, and name of program below (Example: Degree Program is Associate's Degree, VRRAP HDO is Healthcare Support Occupations - Nursing assistants # 164). Then provide the degree/certificate program and facility information you would like to attend, if known.

**Comment by bethpottsVADEPO** [comment]
Thanks so much @RLHecht !

**Comment by bethpottsVADEPO** [comment]
**Program information**

To complete your VRRAP application, you’ll need to enter the type of high-demand job you want to get training for—and the code for that job. 
[Find the type of high-demand job you want training for]
 
**What type of high-demand job do you want training for?**
 
**What’s the code for that high-demand job?**
Where do I find the code? (additional info componenet)
 
**What type of degree or certificate program do you want to get?**
--Could this be radio buttons?: Associate’s degree / Non-college degree / Certificate program / Other (with a field to type in any type of degree not covered with the radio buttons)
 
**Contact information for the school or training provider** (include the name, full address, and telephone number with area code)
 
**Estimated start date for training (MM/DD/YYYY)**
 
**Is the program in-person, online, or both?**

**Comment by bethpottsVADEPO** [comment]
Update: I sent my rewrite posted in the above comment to stakeholders and am waiting for a thumbs up or other feedback from them.

**Comment by RLHecht** [comment]
pretty sure this can be closed. @bethpottsVADEPO please reopen if I'm wrong!
