### ISSUE TITLE
Create R&S page for VRAAP High Demand Occupation List

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#39513]
## Issue Description
Currently on the [Veteran Rapid Retraining Assistance Program (VRRAP)](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/) page, we have a [link to a PDF of high-demand occupations](https://benefits.va.gov/GIBILL/docs/vrrap-high-demand-occupation-list.pdf). For better accessibility, we need to create an R&S article with all the information that's listed in the PDF (each occupation and the number associated with it). 

A few notes:
- Because users may want to search the page, we should not put them into accordions.
- We need to alphabetize the categories as well as the job titles.
- We need to confirm with the product team that the numbers in the PDF are the numbers that should be used for the VRRAP application.

## Tasks
- [x] Create R&S page with the information listed above (Selina)
- [x] Copy edit (Randi)

## Acceptance Criteria
- [x] New R&S article is created with information from VRRAP PDF

**Comment by bethpottsVADEPO** [comment]
@lunascoop Thank you for jumping on this! For the jobs and codes, you'll want to switch the order of how it is presented for each job, so that the code follows the job. They way the PDF is set up, it's code then job. We want it to be job then code so it's more logical for both sighted users and those using screen readers.

**Comment by lunascoop** [comment]
@RLHecht this draft page is ready for review. I'm still second-guessing the title. I'll sleep on it and come back to it in the morning. Or we can chat about it then.

Find high-demand jobs to get training for with VRRAP: http://preview-prod.vfs.va.gov/preview?nodeId=44840

In the **Life, physical, and social science jobs** category, _soil and plant scientists_ is listed twice in the PDF (71 and 73).  I left both instances in for now. (cc: @bethpottsVADEPO )

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lunascoop Thanks so so much for this 11th hour work. I'm going to go in and edit the H1 and intro paragraph--thanks for writing those. And @RLHecht I don't think it's an issue to keep "all other" because I think that refers to just that one line in each case, not the whole section. I see that several times in some sections. But I'm glad you raised it--I will double check with stakeholders to make sure that interpretation is correct.

I will also ask stakeholders about the repeated "Soil and plant scientists"

**Comment by bethpottsVADEPO** [comment]
Update: Keeping this ticket open and in validate until new content team starts and can create a ticket for final copyedit/prepub checklist/publish. However, we'll be coordinating the timing of publishing with when the update to the form rolls out. So we're awaiting word on that date. 

On 4/11 I sent the preview link for this page to Education Service to review. I attended their team meeting to go over the new R&S page and made some tweaks based on initial feedback. There may be more feedback after they have a chance to review the page in more detail.
