### ISSUE TITLE
Research Alternatives to Staging Environment

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#39530]
## User Story
As a Governance team member, I want to understand other types of environments that I may need to perform reviews in.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
Recently we have seen environments different than our typical staging review environment.
Documentation what these other environments are and any needed tools or access could be beneficial for future reviews.

## Impacted Artifacts
[Confluence: Staging Review Environments](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2342944769/39530+Staging+review+types+-+Allison)

## Alternatives
Review Instances
Drupal Preview - Static Pages?
Authenticated vs. Unauthenticated

## Tasks
- [x] Look into slack conversation (2 to 3 months ago)
- [x] Determine all alternatives
- [x] Add information for Review Instances
  - What access is required?
  - How does it differ from Staging Environment
- [x] Add information for what screenshots we need if we cannot access?

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team has guidance for non-staging environment links

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
I saw today that there are two pages on Platform Website [Review Instances](https://depo-platform-documentation.scrollhelp.site/developer-docs/Review-instances.810385495.html) and [Using review instances to preview changes](https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-review-instances-to-preview-changes.590774288.html) (most likely moving as a child page of Review Instances.

**Comment by chaseakirby** [comment]
Additional note from 10-10 EZ staging review: Review Instance environments expire after about a week

**Comment by allison0034** [comment]
@CherylEvans this is ready for your review. It needs wordsmithing but that will happen in another ticket. I just gathered the info.

**Comment by CherylEvans** [comment]
@allison0034 I have reviewed the Impacted Artifact, and ensured that all links are working, and are directed to the appropriate locations.  I have ensured that the User Story has been satisfied, and the Acceptance Criteria has been met.  Nice job!
