### ISSUE TITLE
Migrate primary branch names in vets-website and content-build to `main`

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#39544]
## Description

Currently the primary branches in vets-website and content-build are set to `master` we want to migrate this label to be `main` for both repositories.

`master` branch should be left active until we are confident that teams and systems have completely migrated over to use `main`.

## Definition of done

- [x] Release plan is created

- [x] Communication plan is created

- [x] Test plan is created 
- [x] Test plan passes
- [x] `main` is set to primary branch in both content-build and vets-website
- [x] Branch protection rules are updated to include `main` in both content-build and vets-website
- [x] Deployments of vets-website are connected to `main` branch
- [x] Deployments of content-build are connected to `main` branch
- [x] All points of documentation referencing `master` in both content-build and vets-website are updated
- [x] Review Instances are updated to use `main` instead of `master`
- [x] Announcement to platform and VFS teams has been made

~~- [ ] Post-merge action is created to keep the new primary branch (`main`) in sync with the old primary branch (`master`)~~

**Comment by timwright12** [comment]
I set up the branch protection rules for `main` to match what is currently in `master` this morning since I was in there

**Comment by theodur** [comment]
Test plan: https://docs.google.com/spreadsheets/d/16WLud7d3n-npOzmTEE2nrCZDERLckvAIbC6jjH6WO9k/edit?usp=sharing

**Comment by theodur** [comment]
Release Plan: https://vfs.atlassian.net/wiki/spaces/FTT/pages/2189623510/Release+Plan

**Comment by theodur** [comment]
As part of this initiative, the default branch in [vagov-content](https://github.com/department-of-veterans-affairs/vagov-content) will also be updated to `main`. [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41657)

**Comment by theodur** [comment]
Closing this ticket, now that `vets-website`, `content-build`, and `vagov-content` default branches have been changed to `main`. All action items have been completed as well.
