### ISSUE TITLE
Midpoint Review [My Education Benefits, Authenticated 22-1990e TOE Form Updates]

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#39542]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [ ] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.
Yes, all content feedback will be incorporated in a future update. Please review the finalized design mockups below. 
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/37658](url)

## Artifacts

Provide links or documents for the following: 

- [x] Product outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/TOE%2022-1990e%20Updates/TOE%20Product%20Outline.md
- [x] Finalized design prototype or mockup
https://accenturefederal.invisionapp.com/freehand/Midpoint-Review---TOE-U3BzprxZZ?dsid_h=fcfbfc46791c1285b8dc0446523a0df596028cef65e5a56f7f9788284167139c&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01
- [ ] Research plan 

 
- [ ] Conversation guide 

### Content artifacts 

- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by chaseakirby** [comment]
The async review has been scheduled for 4/7, meaning you will receive feedback by EOD. No meeting will be held.

**Comment by allison0034** [comment]
@alexander-ferzola the link for the prototype is not working. I am getting...

No results matched your search.

**Comment by allison0034** [comment]
@alexander-ferzola thank you. Can you update the product outline? It is also not working

**Comment by claytonzook** [comment]
@alexander-ferzola I don't see research artifacts linked. What is the team's plan regarding research on this?

**Comment by alexander-ferzola** [comment]
> @alexander-ferzola I don't see research artifacts linked. What is the team's plan regarding research on this?

Hi @claytonzook ! At the moment, we don't have research scheduled for the TOE screens yet. Please drop any best practices or specific points you'd recommend we probe during research. Thank you!

**Comment by claytonzook** [comment]
No actionable feedback at this point for research practice area. 
I will include ideas and suggestions for when your team begins to plan for research.

Suggested research inclusion
- Consider - A/B testing of the "Sponsor Information" page, especially thinking the one with multiple cards/sponsors, especially with mobile
   - Possible research questions to consider: Is having to select an option when scrolled past the supporting information a pain point?; Does having the information paired with the selectable option make a difference for this product?
   - A design would be the current design, as modified after midpoint review
   - B design would include pairing information from cards with the selection box
      - this would necessitate creating an alternative design for this page to test
      - Also of note: making a whole card selectable is not currently in the approved design system.
      
When planning your research
- Should - [test mobile design](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Researchingwithmobileusers) as well as desktop
   - should seek users with phones that aren't just top of the line
- Should - have a coded product so can [test with assistive tech participants](https://depo-platform-documentation.scrollhelp.site/research-design/Tech-set-up-checklist.1622311195.html#Techset-upchecklist-Ifassistivetechisbeingused) who have various comfort levels.
   - if not feasible to usability test with coded product at this point, then should still include users with assistive techs that can be tested on any prototype, like screen zoom
- Should conduct [inclusive research](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html#RecruitingParticipants-Inclusiveresearch) and consider over-sampling historically under-represented groups in our research

**Comment by shiragoodman** [comment]
FYI our Information Architect @jimuhh is out of the office this week so no IA feedback has been provided. If you have questions/concerns, please reach out to @mnorthuis on the Sitewide Content & IA team

**Comment by alexander-ferzola** [comment]
Apologies if this posts twice...

Thank you all for your feedback. Before closing this ticket, we would like to recap feedback and update the group with our approach going forward. Please see the design implementation plan below that considers Va.gov recommendations along with our EDU business needs.

**Note:** The following address recommendations for **designs only.** They do not include specific points about user research or developer implementation during staging. Those points of feedback have been documented and can be addressed in the future.

Tagging our EDU Product Owners for their awareness on this thread @ericks24 & @TamGIBill 
[TOE Midpoint Review Feedback Response.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8513960/TOE.Midpoint.Review.Feedback.Response.pdf)

**Comment by allison0034** [comment]
Hi @alexander-ferzola thank you for this. Can you tell me if you are changing anything on the page that currently has the wizard? I believe it is the How do I apply?

**Comment by alexander-ferzola** [comment]
> 

Hi @allison0034 ! At the moment we're focusing on updating the form itself. In the future, that is an entry point for the applications we would like to see updated. 

Do you have any recommendations on how to improve that page? In the past we've discussed that the wizard will be deprecated but don't think we've had a great idea with what/how to replace it.

**Comment by allison0034** [comment]
We are researching options but currently we are recommending 1 question per page instead of the wizard. Thank you for the update!

**Comment by joshkimux** [comment]
Hi @alexander-ferzola ✨ Checking in on this closed ticket to see if y'all were able to conduct research on mobile or with assistive tech users. I couldn't find anything on the research repo, and was wondering if I may have been searching with the wrong keywords or labels.

Context: we're currently filling out our product a11y health dashboard, and one of our criteria for evaluating health includes said research ✌️

**Comment by joshkimux** [comment]
@artsymartha68 for awareness ✨
