### ISSUE TITLE
[EKS] Migrate cluster-autoscaler to helm from jsonnet

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#39559]
## Description
In continuing efforts to rid ourself from jsonnet, I am going to pick off cluster autoscaler and move it over to deploying via the helm chart.

https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler

---
## Tasks
- [x] Deploy cluster autoscaler using the helm chart in sandbox (less people using this environment currently)
- [x] Use the appropriate version suggested by CA based on our kubernetes version 1.19x https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases
- [x] Point argo at helm instead of jsonnet https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/argocd-apps/sandbox/main.jsonnet
- [x] If all goes well deploy to the rest of the clusters 
- [x] Remove jsonnet that is tied to cluster autoscaler since it will no longer be needed
- [x] Create infra repo for cluster autoscaler since one doesn't currently exist
- [x] Add github actions for building image, uploading to ecr, and updating manifests

## Acceptance Criteria 
- [x] cluster autoscaler is deployed to all clusters using the helm chart and the latest version
- [x] github actions in the infra repo is re-organized and updated (building docker container, upload to ecr, update manifest)

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
