### ISSUE TITLE
[FE] [BUG] Cannot read properties of undefined (reading 'startTime')

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39561]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

## User Story

As a CIE developer, I wish to not receive meaningless alerts, in order to cut down on alert fatigue and help focus time on issues that directly impact the veteran experience.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description
We get the error `Cannot read properties of undefined (reading 'startTime')` logged in Sentry from time to time. 

## Implementation Info

This probably happens when a veteran re-opens their browser after the session has expired.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
This is still occurring, 107 instances over the past 5 days.

**Comment by brianseek** [comment]
Find areas where we are grabbing startTime from an object and check for the object first. Figure out best way to handle throwing error or update screen.

**Comment by brianseek** [comment]
Fix has been merged, will watch Sentry for a week or so to see if errors stop or new ones crop up.

**Comment by sarahknoppA6** [comment]
Brian to validate today

**Comment by brianseek** [comment]
Checked logs, no errors seen since this being merged. Would like to keep an eye on this for another week, then can close if no logs.

**Comment by brianseek** [comment]
The number of these issues have dropped off significantly. There was one report of it since this has been merged. 
This chart shows how the issue dropped off since thins fix:
![Screen Shot 2022-06-14 at 11.08.45 AM.png]
(https://images.zenhubusercontent.com/61523b5b9d354750f04823db/799e3421-8e3f-440a-8a8f-f44bf8334723)
I want to monitor this for another week to see if this crops up again and to see if we need to make another ticket to dig in more.

**Comment by brianseek** [comment]
Spoke with @acrollet on this and we agree to close and double check in a week, but this ticket cleans up the noise.
