### ISSUE TITLE
Translation work for second booster content on 2 COVID-19 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#39560]
## Issue Description
We updated content on both the [COVID-19 vaccine](https://www.va.gov/health-care/covid-19-vaccine/) and the [booster shots and additional doses](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) pages that need to be translated in Spanish and Tagalog. 

Word doc sent to translators: [https://app.zenhub.com/files/133843125/42aa6322-785c-4976-8abc-745e9cb86836/download](https://app.zenhub.com/files/133843125/42aa6322-785c-4976-8abc-745e9cb86836/download)

Once the translators send back the content, we need to update the Spanish and Tagalog pages, review and publish. Then we need to send the live links to the volunteer translation team.

## Tasks
- [ ] Send content to translation team (Randi)
- [ ] Update Spanish pages (Danielle)
- [ ] Update Tagalog pages (Danielle)
- [ ] Review and publish pages
- [ ] Send live links to volunteer translation team for final review (Danielle)

## Acceptance Criteria
- [ ] Spanish and Tagalog pages are live with updated content

**Comment by RLHecht** [comment]
Update: Our previous contacts transitioned off this project, so I emailed the new POC at VA to check the status of this.

**Comment by RLHecht** [comment]
Here are the returned translations.

[https://app.zenhub.com/files/133843125/548cec13-2c33-4a91-969c-70fa19844870/download](https://app.zenhub.com/files/133843125/548cec13-2c33-4a91-969c-70fa19844870/download)

[https://app.zenhub.com/files/133843125/2106824c-90b0-4c9c-8f18-7f26fcb6a983/download](https://app.zenhub.com/files/133843125/2106824c-90b0-4c9c-8f18-7f26fcb6a983/download)

@aliyahblackmore @megzehn here's the documentation for how to handle translations: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/translation-work/covid-translation-work-process.md

Can both of you read through that and then we can meet and screen share today if possible and I can walk you through making these updates?

**Comment by aliyahblackmore** [comment]
Both Tagalog pages have been updated with what was in the translated document! There were a few missing translations and a section that is on the live English page that was not included on the returned document. @RLHecht and @laurawillwerth I have included my notes on [this document](https://docs.google.com/document/d/1S9LmvFroKTKejKazVZl4FCy73Pg-5OPWMJH-NR8ow74/edit#) and happy for us to chat on Monday!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA The translators also sent back the screener content. It's at the bottom of each of the docs I posted in the comment to Aliyah above. Let me know if you need me to pass them to anyone.

**Comment by aliyahblackmore** [comment]
Hi @laurawillwerth - The COVID Vaccines at VA Spanish page has been updated with the new translated content.  [Preview link is here](http://preview-prod.vfs.va.gov/preview?nodeId=16359)! I will have the Spanish booster page ready for you tomorrow.

**Comment by aliyahblackmore** [comment]
Also noting here so that we track the status of tasks -->  following Randi's comments in the Tagalog translation Google Doc, I will just do another quick look at the booster page and then pass it to Laura. Another ticket was created to review the translated pages to see if there are any parts of the translation that are missing. So far, on the Tagalog page, there was a bit of text towards the end of the live English page version that was not included in the Tagalog translation that was returned.

**Comment by aliyahblackmore** [comment]
Hi @laurawillwerth - the Spanish booster page is ready for you in Drupal! Preview page is [here](http://preview-prod.vfs.va.gov/preview?nodeId=34408). Also, like the Tagalog, the Spanish translated page did not include a translation of the following: 

**What to know before you get an additional vaccine dose
Here’s when you should get your additional dose:

- At least 28 days after your second dose of the Pfizer-BioNTech or Moderna vaccine, or

- At least 28 days after your single dose of the Janssen vaccine

You don’t need to get your additional dose at the same facility where you got your other doses. But not all VA health facilities have both Pfizer-BioNTech and Moderna right now. And facilities may offer different vaccines at different times.

Confirm that the facility has the vaccine you want before you schedule an appointment. And bring your vaccine record card with you when you come in so we can record your additional dose.**

As Randi suggested in the notes for the Tagalog page (where the translation was also missing), I am leaving in what already exists on the Spanish Drupal page until we receive the new translated content.  The following is on the current Drupal page (in Spanish):

**Lo que debe saber antes de recibir una tercera dosis de la vacuna

Debe recibir la misma vacuna para las 3 dosis. Debe recibir la tercera dosis al menos 28 días después de la segunda dosis. No es necesario que reciba la tercera dosis en el mismo centro donde recibió las 2 primeras.

No todos los centros de salud de VA cuentan con Pfizer-BioNTech y Moderna en este momento. Los centros pueden ofrecer diferentes vacunas en diferentes momentos. Confirme que el centro tiene la vacuna que desea antes de programar una cita para su tercera dosis. Lleve su tarjeta de registro de vacunas cuando vaya para poder registrar su tercera dosis.**

**Comment by aliyahblackmore** [comment]
Hi @RLHecht passing along a word document with what needs to be translated to Spanish and Tagalog on the[ Booster page](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/#getting-an-additional-vaccine-)!
[To be translated to Tagalog and Spanish.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8681569/To.be.translated.to.Tagalog.and.Spanish.docx)

**Comment by aliyahblackmore** [comment]
Hi @laurawillwerth - the Tagalog booster page is ready in Drupal. Dropping the preview link[ here](http://preview-prod.vfs.va.gov/preview?nodeId=34394)!

**Comment by laurawillwerth** [comment]
Thanks Aliyah! @RLHecht, I reviewed all 4 translated pages and the changes are now published — ready for validation and sending to volunteer translation team.

**Comment by RLHecht** [comment]
I sent Mateo our live links and the new translation forms to fill out. Closing this ticket and will reopen if he has changes that need to be made.
