### ISSUE TITLE
Connect with 686 Stakeholders

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#3958]
## Story
As a designer/researcher (or even team member in general), I want to be able to fully understand the business logic and intent so that I can test my assumptions and ensure I create the right thing during the migration and transformation of this feature.

## Tasks
- [ ] Create a list of assumptions and/or questions about how the 686 (674?) works and should be handled
  - Is it possible to submit a 686 with only something in some sections?
  - Can some fields have their requirements removed allowing for partial or optional sections?
- [x] Establish contact with the appropriate stakeholder
- [x] Document those stakeholders for easier access later
- [x] Schedule a time to meet with those stakeholders

## Acceptance Criteria
- [x] A meeting has been scheduled with the appropriate members

**Comment by steve-gov** [comment]
Had kickoff meeting, will schedule new meetings going forward
