### ISSUE TITLE
[Research] Create Research Study Report, Synthesize, and Make Recommendations for Telephone Appointment Research with Dr. Hsu

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39591]
## User Story
As a product team, we want to report and synthesize the findings from our research into telephone appointments and make some recommendations.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Research plan and Conversation guide]()

## Description
Analyzing the videos and notes from [research study name] to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 1 document needed. Use either [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [ ] Create necessary issues/tickets that address findings in coordination with Lori 
- Schedule readout sessions with
    - [ ] Stakeholders (talk to Patrick about when to do this)
    - [ ] Team (either via Slack or Zoom meeting)
- [ ] Post synthesis documents to GitHUB

**Comment by benbrasso-agile6** [comment]
@loripusey we'd like to discuss modifying this ticket to just include research plan for this sprint

**Comment by benbrasso-agile6** [comment]
[Git folder for staff interview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/telephone-appointments/staff-interviews)

[Interview findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/telephone-appointments/staff-interviews/stakeholder-findings.md)

@niradatta1 Do you want to touch base on what I've created here? Couple things I'm looking for thoughts/feedback on: 

1) Worth or should we share these initial findings with anyone? (Although, we did share at our demo meeting.) 

2) Do we need to flesh out a short vs. long term solution now? I.e., prior to Veteran research. (See 1st bullet under Next Steps.) 

3) How or when should we go about exploring some of the Open Items and Questions? 

4) Are we ready to move forward with [creating the Veteran research plan](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39594)? Let's chat about how to split this work up.

**Comment by niradatta1** [comment]
Here is the link to the Mural synthesis, we can reference after we've completed the Veteran facing study https://app.mural.co/t/civicactions3117/m/civicactions3117/1649777253301/29d43298818ec10044e3334ba33e950edc051be3?sender=niradatta0802

**Comment by benbrasso-agile6** [comment]
@niradatta1 I added the mural into the [interview findings](https://app.mural.co/t/civicactions3117/m/civicactions3117/1649777253301/29d43298818ec10044e3334ba33e950edc051be3?sender=niradatta0802)

Closing this ticket
