### ISSUE TITLE
[Research] Create Research Plan for Telephone Appointments PCI & CI

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39594]
## User Story
- As a Veteran, I want to be able to check in from my mobile device for phone appointments

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan 

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan to GitHub folder

**Comment by benbrasso-agile6** [comment]
[Draft research plan for telephone appointments with Veterans](https://docs.google.com/document/d/1nlC8J4HioUd76ShvSLFOe2fzhtyGsJR-MP1ceB183Ew/edit?usp=sharing) - this needs a review. Probably @niradatta1 and @kristenmcconnell to start. I dropped in a bunch of comments that I'd like to discuss. 

For documentation's sake, here was the [initial draft](https://docs.google.com/document/d/1nqXq6n6JAK9sNCavVb1rWxvfsONszA7ya_xypc4-KEM/edit?usp=sharing) that Nira had shared with me.

**Comment by benbrasso-agile6** [comment]
[There is a folder here for telephone appointments](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/telephone-appointments), FYI. Although, I'd rather wait to add this research plan until it's more ironed out.
