### ISSUE TITLE
Implement initial api call from FE to BE to start transition process

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#39619]
## Issue Description
Implement the `<api>/inherited_proofing/auth` call on the transition page.

---
## Tasks
- [ ] "Start transition now" button leads to API endpoint

## Acceptance Criteria
- [ ] "Start transition now" button calls proper endpoint
- [ ] Said button only appears when the eligible property exists on the user model and
- [ ] proper flipper feature enabled
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
