### ISSUE TITLE
SSL Certificates for mTLS to LGY PINT environment from Lighthouse Sandbox (sandbox-api.va.gov)

### ISSUE THREAD

**Issue by mramirez-va** [department-of-veterans-affairs/va.gov-team#39633]
## Description
Lighthouse is adding a new integration between LGY's PINT environment (`pint.services.lgy.va.gov`) and our Sandbox environment (`sandbox-api.va.gov`). LGY requires client certificates to connect to their service via mutual TLS. We have provisioned the certificates with Venafi and now need them deployed onto the forward proxies in Sandbox.

## Background/context
I am part of the Lighthouse Operations team working with VSP Ops to get this deployed on behalf of the Lighthouse API team that is adding the integration. Their task for this is https://vajira.max.gov/browse/API-10706

## Technical notes
The Lighthouse API team will be submitting the pull request to add the route for this new LGY integration but before that happens we need to have these SSL certificates loaded in so that the connection can actually work when the route is added.

I can send over the certificate data via VA encrypted email or Keybase.
---
## Tasks
- [ ] Add LGY client SSL certificates to Sandbox forward proxy
- [ ] Add LGY SSL client certificate private key to AWS parameter store

## Acceptance Criteria 
- [ ] Sandbox forward proxies have LGY client certificates installed
- [ ] Sandbox forward proxies have LGY client certificate private key installed

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@mramirez-va - Thank you for submitting this request. 

Do you have any hard timelines that you are working towards? Thank you in advance for any info.

**Comment by jsgarmon** [comment]
@mramirez-va : feel free to send these certs to me. My keybase is `jsgarmon`.

**Comment by mramirez-va** [comment]
> @mramirez-va - Thank you for submitting this request.
> 
> Do you have any hard timelines that you are working towards? Thank you in advance for any info.

Within the next week of 04/11 would be our target

**Comment by mramirez-va** [comment]
> @mramirez-va : feel free to send these certs to me. My keybase is `jsgarmon`.

Sent the cert data zip over Keybase. Thanks @jsgarmon!

**Comment by jsgarmon** [comment]
@mramirez-va couple questions:
1. The key file is encrypted with a pass phrase. Can you send that pass phrase to me via Keybase?
2. We can skip health checks for now, but generally we have a health check path. Is that something you know, or do you want to hold off on that?

**Comment by mramirez-va** [comment]
> [fwdproxy/LGY] new config from LGY team department-of-veterans-affairs/devops#11030

Sent in Keybase

**Comment by mramirez-va** [comment]
> @mramirez-va couple questions:
> 
> 1. The key file is encrypted with a pass phrase. Can you send that pass phrase to me via Keybase?
> 2. We can skip health checks for now, but generally we have a health check path. Is that something you know, or do you want to hold off on that?

Sent in Keybase

**Comment by jsgarmon** [comment]
Is there a way to confirm that:
- the CN on this new cert should be `lgy-guaranty-remittance-sandbox.lighthouse.va.gov`
- no auth header is needed

**Comment by jsgarmon** [comment]
@mramirez-va : I'm considering this blocked since I haven't been able to get the certs to work, and there's not much we can do on our end. Let me know if you learn anything.

**Comment by jsgarmon** [comment]
Closing as complete: https://github.com/department-of-veterans-affairs/devops/pull/11030#issuecomment-1115348802
