### ISSUE TITLE
Ramp up direct deposit to 75% and monitor for any issues 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3964]
## User Story: 

As a front end engineer, I need ramp up the user percentage to 75% so I can monitor for any errors or unusual activity happening due to the increased amount of traffic . 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [ ] Need to ramp up the percentage from 50 % to 75% of users 

- [ ] Monitor activity during sprint 10

- [ ] Socialize and discuss with team, make decision to keep it at 75 % or ramp up to 100% in upcoming sprint 11

 
## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] Ramped up to 75% and monitored activity during sprint 10

- [ ] Add two individuals we discussed to the testing group for production environment. [How to documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/feature-toggles.md)

- [ ] Team agrees on decision to continue to ramp up or discuss need to keep it at 75 % and address any issues that arose during the sprint after ramping up to 75%.

**Comment by erikphansen** [comment]
Done 

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/7d63d19d-af50-4f45-a39d-f4d9af508430)
