### ISSUE TITLE
[User Testing] HLR Research Plan

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3965]
## User Story or Problem Statement
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and user testing recruitment needs. 

## Goal
_A completed research plan sent to Perigean for user testing recruitment_

## Objectives or Key Results this is meant to further
- _User testing to validate the Higher Level Review's design and/or uncover gaps, improvements, and pain points_

## Tasks
- [x] _Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)_
- [x] _Review research plan with design team_
- [x] _Obtain approval from Andrea Schneider_
- [x] _Send research plan to Perigean_
- [x] _Add research plan to GH_

## Acceptance Criteria
- [ ] Research plan created and uploaded to GH

**Comment by chrvalla** [comment]
HLR Research plan drafted

**Comment by luke-gcio** [comment]
Completed.
