### ISSUE TITLE
GitHub Actions: Investigate Missing Time in Cypress Execution Step

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39655]
## Issue Description
Sometimes GHA CI Workflows appear to take longer than the sum of the steps. In particular the Cypress execution appears to account for a significant portion of the unlogged time.
Example:
[This run](https://github.com/department-of-veterans-affairs/vets-website/runs/5821947738?check_suite_focus=true) of the workflow in particular is interesting. The 4th parallel Cypress execution step appears to take ~24 minutes, but adding up the actions only comes to ~13 minutes. Why the discrepancy?

---
## Tasks
- [ ] Investigate the time discrepancy in the example workflow
- [ ] Locate other examples of workflows with significant time discrepancies

## Acceptance Criteria
- [ ] A root cause for the discrepancy in time mismatch has been defined
---
