### ISSUE TITLE
Update form generator template

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39668]
## Description

Update vets website form generator to use best practices. Copy [examples from #20709](https://github.com/department-of-veterans-affairs/vets-website/pull/20709)

## Tasks

- [ ] Fix headers (a11y)
- [ ] Use `directDeposit` instead of `bankAccount` definition
- [ ] Use `<va-process-list>` on introduction page
- [ ] Update confirmation page with a print button
- [ ] Switch using `moment` to `date-fns`

## Definition of done

- [ ] All tasks complete
- [ ] Test that generator is working
