### ISSUE TITLE
Investigate why "flagged for fraud" error rate is so high 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3966]
## User Story: 

As the team lead, I need investigate the "flagged for fraud" error rate with EVSS team so that I can make an informed decision with the team on what corrective action we need to take to minimize the flagged for fraud error rates. 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Schedule meeting with EVSS team to discuss the flagged for error rate issues

- [x] Determine next steps to socialize with team

- [ ] Break down tickets for any work that results from these discussions. 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [x] A actionable solution has been determined by team on what needs to happen next.

**Comment by Samara-Strauss** [comment]
Current status: Email sent to EVSS team. I have not heard back but I will follow-up accordingly until we hear back. We should, however, prepare ourselves that they may not be able to help and we may need to go back to the drawing board on how to get answers.

**Comment by Samara-Strauss** [comment]
Talked about this on a call with EVSS team earlier today. Next steps are:

1. Lihan is going to look into records and pull some names that are getting the flagged for for fraud error. Then he's going to check in with Adam Kinder about whether those people are actually flagged for fraud or not.
2. Erik has a question about the two metrics we're using to determine when to raise the "flagged for fraud" error. He's going to follow up with the EVSS team about this.

**Comment by Samara-Strauss** [comment]
BE work is in #3981 and FE work is in #3982.
