### ISSUE TITLE
Get on eBenefits schedule to remove direct deposit from the site in 1/29 release

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3967]
## User Story: 

As a team lead, I need reach out to the eBenefits team  so that I can get on their release schedule to have the direct deposit feature removed from their site on 1/29.

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Reach out to eBenefits team to discuss getting on their releaes schedule to have the direct deposit feature removed from their site on 1/29/2020. 

- [ ] Confirm this removal will happen with their 1/29/2020 release. 

- [ ] Update team on status of this confirmation. 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] The removal of the direct deposit feature on eBenefits has been schedule for the 1/29/2020 release.

**Comment by Samara-Strauss** [comment]
Going to wait to regroup with Erik to discuss the 75% launch/monitor that launch for a couple days before I send this email. I doubt thinks will change at this point, but I want to make sure we're not doing any back tracking if we can avoid it.

**Comment by Samara-Strauss** [comment]
Update: Now that we have successfully investigated the flagged for fraud error (#3966, #3981, #3982) and understand why we were seeing it at such high rates (and that this does not indicate a problem on our end), we are ready to ramp up to 100%. I emailed eBenefits this morning to let them know we'd like to take direct deposit down from eBenefits in the 1/29 release. I am awaiting confirmation before I close this ticket.

**Comment by Samara-Strauss** [comment]
Update: We have an OK on this from the technical side of the house. They just need Melissa Rebstock to give us final approval.

**Comment by Samara-Strauss** [comment]
The latest: Melissa needs to regroup with the following folks before getting us final approval:

> Compensation Service, Pension Service, OBPI and BAS

We'll follow up with her after the holidays if we don't hear back.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss per you comment above, do you want to go ahead and close this ticket out for Sprint 10 objective and just open a follow up ticket to track too for awaiting Melissa's response back to us of approval or not?

**Comment by Samara-Strauss** [comment]
@Justin-Pickett let's leave this open until we have confirmation from Melissa. This is complete for the purposes of sprint objectives as we've reached, heard back, and the only thing we're waiting on is internal conversation on their side of things. But I'd like to leave this open until we have a final 100% acknowledgment from Melissa that DD will be removed from eBenefits on 1/29.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss  okay great. Sounds good!

**Comment by Samara-Strauss** [comment]
Still waiting to hear back. I reached out last week but never heard anything. Going to reach out again today.

**Comment by Samara-Strauss** [comment]
We received confirmation from Melissa Rebstock today that direct deposit will be removed in the 1/29 release. Closing!
