### ISSUE TITLE
[Vets-API/EKS] Unique Readiness and Liveness Probes in Deployment

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39681]
## Description
Vets-API in EKS requires unique readiness and liveness probes. 

## Background/context 
These probes should be different, as they serve different purposes.
Currently they are using the same endpoint, which consumes a Puma thread and can cause contention with client requests.

## Technical notes
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
- https://github.com/department-of-veterans-affairs/vets-api/pull/9565
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L141
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/deployment.yaml#L147 
---
## Tasks
- [x] Have a separate health check endpoint for liveness and readiness probes

## Acceptance Criteria 
- [ ] Vets-API is deployed with both a readiness and liveness probe
- [x] Vets-API has a separate endpoint for each probe
