### ISSUE TITLE
[Vets-API/EKS] Setup and Verify Cluster Autoscaler

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39684]
## Description
Install and configure [to the appropriate AWS autoscaling group] the Kubernetes Cluster Autoscaler

## Background/context 
With the use of horizontal pod autoscaling (HPA), it's important to also allow the cluster to autoscale in the event that resources run low.

## Technical notes
- https://github.com/kubernetes/autoscaler
- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-dev/eks-cluster-autoscaler.tf
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/cluster-autoscaler

---
## Tasks
- [x] Install Cluster-Autoscaler
- [x] Verify Cluster-Autoscaling is configured to the correct autoscaling group
- [x] Verify Cluster-Autoscaling can scale up
- [x] Verify Cluster-Autoscaling can scale down

## Acceptance Criteria 
- [x] The cluster can scale up and down as resources are required and freed-up

**Comment by mleclerc00** [comment]
Cluster autoscaler is indeed deployed to every cluster we currently manage, aside from the code this can also be seen in argocd
https://argocd.vfs.va.gov/applications?search=cluster-autoscaler&proj=&sync=Synced%2COutOfSync&health=Progressing%2CHealthy%2CMissing&namespace=&cluster=&labels=

Each helm deployment points at the unique ASG for each cluster which can be seen in the values yaml file for each environment which also uses tags on the asg instances for autodiscovery for example dev
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/4c1c98082a250a0f7254d4b6ccb3f8af80572229/apps/vsp-operations/cluster-autoscaler/dev/values-dev.yaml#L13-L17

Each cluster can scale up as needed
<img width="597" alt="image" src="https://user-images.githubusercontent.com/76792875/162267527-d4fe9ada-3e9e-452b-a9e9-8ccd3ac1b379.png">

And scale down
<img width="777" alt="image" src="https://user-images.githubusercontent.com/76792875/162268874-1ad92839-d68e-4082-87e7-9f75aa1396b4.png">
