### ISSUE TITLE
[Vets-API/EKS] Configure and Validate HPA

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39683]
## Description
Vets-API needs to have horizontal pod autoscaling (HPA) setup and verified to be working.

## Background/context 
This ultimately takes place/simulates the Autoscaling Groups used by BRD Vets-API on EC2s.

## Technical notes
- https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

---
## Tasks
- [x] Verify HPA is configured
- [x] Verify HPA is working

## Acceptance Criteria 
- [ ] Vets-API can scale horizontally through HPA

**Comment by oseasmoran73** [comment]
It looks like we have an [HPA](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/hpa.yml) already implemented in vets-api. Work was done by Matt.

For my learning purposes, I still would like to stress-test based off documentation provided and see it scale, but I think this work is complete.

Will close after testing is done

**Comment by oseasmoran73** [comment]
Closing out ticket as Kyle has verified it is working as intended. Thank you!
