### ISSUE TITLE
[Vets-API/EKS] Traffic Routing Between EKS and BRD

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39687]
## Description
Traffic needs to be split 80/20 between BRD and EKS.

## Background/context 
- Doing a straight cut-over does not give us room to verify everything is a-okay with Vets-API in EKS
- The split ratio may change based on conversations with stakeholders

## Technical notes
- May need to introduce an ExternalName service to direct traffic from within EKS to use Vets-API BRD
- Ideally we start with an 80/20 traffic ratio, with 80% going to BRD and 20% going to EKS
- https://doc.traefik.io/traefik/routing/services/#weighted-round-robin-service

---
## Tasks
- [ ] Configure the IngressRoute to send 80% of traffic to Vets-API BRD (may require using an ExternalName service)
- [ ] Configure the IngressRoute to send 20% of traffic to Vets-API EKS

## Acceptance Criteria 
- [ ] Vets-API is splitting traffic between BRD and EKS deployments

**Comment by jbritt1** [comment]
### Relations

- https://github.com/department-of-veterans-affairs/devops/pull/10622
- https://github.com/department-of-veterans-affairs/devops/pull/10671
- https://dsva.slack.com/archives/CTYQL39FE/p1643922695904969?thread_ts=1643922199.935069&cid=CTYQL39FE

**Comment by ph-One** [comment]
We did a 100% cut over for dev, and provide a header field that can be used for getting around to BRD if any problems arise during this cut-over.
