### ISSUE TITLE
[Vets-API/EKS] Deploy and Configure Ingress (Traefik)

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39685]
## Description
Expose vets-api through the Kubernetes ingress.

## Background/context 
- We use Traefik
- Should be done through an IngressRoute object (a CRD specific to Traefik)

## Technical notes
- https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute
- `curl -L -H 'Host: dev-api.va.gov' api.va.gov/v0/status` is the current way to reach Vets-API within EKS (using the host header)

---
## Tasks
- [x] Ingress controller is deployed (Traefik)
- [x] Create IngressRoute for vets-api

## Acceptance Criteria 
- [ ] Vets-API is accessible from its public URL / accessible through ingress
