### ISSUE TITLE
Archive Obsolete Synthetic Monitor Documentation

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39680]
# Description
Previous synthetic monitor documentation was aimed at using AWS CloudWatch Canaries to conduct synthetic monitoring of production. After this initiative is complete, they will be hosted in Datadog instead and the old document can be archived.

# Tasks
- [ ] Assess existing documents for archiving
- [ ] Archive any documents that were not adapted and are now out of date

# Acceptance Criteria
- [ ] All outdated synthetic monitoring documents have been archived

**Comment by rbeckwith-oddball** [comment]
Technically already done since no additional actions are necessary
