### ISSUE TITLE
[FSR] Download PDF Error Handling

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39686]
## Issue Description
[Downloading completed FSR](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/financial-status-report/components/DownloadFormPDF.jsx) error handling needs some TLC. 

Currently the button will just silently error out when clicked and no PDF will download. Let's hide the download option if there is an issue. 

---
## Tasks
- [ ] FSR - Fetch PDF on page load and hide download button if there's an error

## Acceptance Criteria
- [ ] Completed FSR Download button is hidden if there's an issue retrieving it from DMC
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
