### ISSUE TITLE
Document these Principles on Confluence

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39698]
## Issue Description
Document the tenets on Confluence (and maybe elsewhere eventually)

---
## Tasks
- [x] Evaluate best space for them on Confluence
- [x] Format and enter copy

## Acceptance Criteria
- [x] Confluence pages updated with data
