### ISSUE TITLE
Define a Solution for Orphaned Products

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39699]
## Issue Description
The platform has a number of products that no longer are owned by a team. This happens in cases where a team develops a product, the product is completed, and the team's contract is then not renewed. This has been happening for years, so we don't have a clear understanding of how many orphaned products exist on the platform. In order to make our product list as complete as possible, we would like to make reasonable attempt to identify that.

**Possible Methods for Identifying Orphaned Products**
* Create an offboarding process for VFS teams that includes marking their products as in `maintenance`, `sustainment`, `inactive`, or whatever the accepted terminology is
* If a directory we know to be a product does not have a `codeowner`
* Looking for the last time a folder we know to be a product was updated. For example, if it has been more than 180 days since a known product foler was updated we can mark that product as `inactive` (heatmap of what areas of code are most updated)

---
## Tasks
- [x] Discuss possible methods for detecting/identifying orphaned products
    - [x] [Create tickets for selected methods]
- [x] Implement defined methods & verify results when possible
- [x] Determine if current plans for how we identify products and incorporate into the Product List will work for orphaned products

## Acceptance Criteria
- [x] We have defined approaches for identifying and incorporating orphaned products into the product list
- [x] Methods have been tried and successful methods have been put in place

**Comment by JoeTice** [comment]
I believe this task is finished

**Comment by pjhill** [comment]
Solution defined!
