### ISSUE TITLE
Create Dashboard of All Synthetic Monitors

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39692]
# Description
In order to observe and assess the state of the synthetic monitors hosted in Datadog, we need to create a dashboard displaying their current and historical status.

# Tasks
- [x] Create a dashboard for the purpose of displaying synthetic monitors
- [x] Add data for all four active synthetic monitors to the dashboard
- [x] Verify access to the dashboard for synthetic monitor stakeholders
- [x] Create a visual displaying the current status for all four synthetic monitors
- [x] Create a visual displaying the historic status for all four synthetic monitors (last 30 days)

# Acceptance Criteria
- [x] Current synthetic monitor status is visualized and easily understandable
- [x] Historical synthetic monitor status is visualized

**Comment by rjohnson2011** [comment]
Currently reviewing the recent synthetic monitoring data within Datadog and researching the Domo -> DataDog connectors.

**Comment by rjohnson2011** [comment]
Continuing looking into the feasibility of bringing historical data into the main Synthetic Monitoring dashboard page. Will potentially reach out to Infrastructure team to question the possibility if this item continues to be a blocker later today.

**Comment by rjohnson2011** [comment]
Reviewed other existing VA dashboards and did not see any widgets containing historical information as desired in the ticket. Scheduled a meeting with Infrastructure team today to look into the issue of adding history logs to the dashboard.

**Comment by rjohnson2011** [comment]
Paired with Infrastructure to investigate the issue of displaying historical logs on dashboard pages. Came to an agreement that limitations of DataDog prevent certain logs & charts from being displayed on dashboard pages. While investigating, came to a next best solution of inserting an iFrame with the drill-down page on the dashboard. While this will involve a small amount of scrolling on the user's part to see historical data, this will prevent a user from having to individually click into all Synthetic monitors to see historical data. In the process of adding these frames to the dashboard and putting the ticket into Review.

**Comment by rjohnson2011** [comment]
Created four widgets with historical data, one for each Synthetic monitor, on the Synthetic Monitoring dashboard - https://app.datadoghq.com/dashboard/ri4-6ac-h88/synthetic-monitoring?from_ts=1649854606215&to_ts=1649858206215&live=true

Styled the dashboard page and placing this ticket into review.

**Comment by pjhill** [comment]
A bit of a weird menu within a menu thing going on here -- 
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/da0188ed-3c9f-48a5-b4cb-558f869a480b)

**Comment by rjohnson2011** [comment]
@pjhill The menu on the side is happening because the widget is an iFrame with the URL of the individual synthetic test. This is a little bit of a workaround since DataDog doesn't appear to have the ability to export or insert historical UX monitoring data into a dashboards with an individual widget. After pairing with Infrastructure on the issue, we determined the closest possible solution to display historical data on the site would be to insert iFrame with links to the individual UX monitoring synthetics, effectively preventing the user from having to drill-down and click on each individual synthetic test to look for historic data. While the iFrame solution results in loading the entire page (left menu included) there doesn't appear to be another solution to load UX historical data as an individual component.

**Comment by pjhill** [comment]
Hey @rjohnson2011 -- per our discussion in the stand-up this morning about the limitations for the historical data and the need to use an iFrame, I think it's best to remove these iFramed detail views from the dashboard. Instead, we can direct the user to select an individual monitor in order to see detailed historical information.

**Comment by rjohnson2011** [comment]
Sounds good. Dashboard is revised, closing out the ticket.

**Comment by JoeTice** [comment]
Reopening based on feedback from Mike Chelen, minor change - he would like this dashboard to be publicly accessible
