### ISSUE TITLE
[FE] Copy Spanish Text to JSON Files

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39696]
## User Story
As a Veteran or Veteran relative whose primary language is Spanish, when I do check-in or do pre-check-in, I would like to have an option to see messages, questions, and prompts in my native language so that I can understand the information.

## Related Documentation
Refer to [documents ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/Translations%20Received%205-4-2022.md )received from the State Department on 5/4/2022

## Description
- Given I
   - Receive an invitation to perform CI or PCI
- When I
    - Access any of the CI or PCI pages (including login)
    - Choose Spanish as my language 
- Then I
   - See all text in Spanish

## Tasks
- [x] Copy Spanish and Tagalog language text received from the State Department and verified by internal VA folks into the appropriate Spanish language json file(s)
- [x] Update label prop on the va-loading-indicator with translated value
- [x] Update label close-button-aria-label on the va-alert component with translated value
- [x] Audit un-used translations and generate a list
- [ ] Audit new items missing translations and generate a list for round 2 of translations
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] All text, that are is not included in a control where translation is handled as part of the control, displays it's Spanish translation when the user has toggled to Spanish
- [ ] All text, that are is not included in a control where translation is handled as part of the control, displays it's English translation when the user has toggled to English
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
This will be validated when the state department validation document is created.
