### ISSUE TITLE
Login.gov Inherited Proofing Devops Config

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#39693]
# Description
Adding configuration settings for Dev/Staging/Review for MHV inherited proofing. Two new config settings need to added to enable vets-api to interact with Login.gov for inherited_proofing purposes.

* oauth_public_key: points to the file that contains Login.gov's public key
*  inherited_proofing_redirect_uri: a slightly different redirect url from the default one to enable automatic user logout and redirect to Login.gov authentication

# Tasks
- [x] Update vets-api's `settings.yml` to include default values for `oauth_public_key` and `inherited_proofing_redirect_uri` underneath the `logingov` settings block
- [x] Update devops repository to include similar settings for dev, staging, and review environments
- [x] Update devops repository to set these values to `false` for production environment.
- [x] Update dev environment configs in the `vsp-infra-application-manifests` repo to match devops configs

**Comment by bramleyjl** [comment]
devops & vsp infra PRs:

https://github.com/department-of-veterans-affairs/devops/pull/11023
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/479

**Comment by ianhundere** [comment]
final PR for changes:
[department-of-veterans-affairs/vsp-infra-application-manifests#490
](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/490)
