### ISSUE TITLE
[Vets-API/EKS] Deployment Requests and Limits

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#39690]
## Description
Evaluate the need for requests and limits for the Vets-API deployment and implement them if necessary.

## Background/context 
- Vets-API is a monolith (and resource-hungry) and care needs to be taken to make sure it has the resources necessary to operate as expected within EKS

## Technical notes
- Goldilocks could be leveraged here
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
- Understanding Kubernetes QoS would be beneficial here as well, https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

---
## Tasks
- [ ] Evaluate the need for requests and limits
- [ ] Implement requests if necessary
- [ ] Implement limits if necessary

## Acceptance Criteria 
- [ ] Vets-API is deployed with appropriate resources based on evaluation

**Comment by jhouse-solvd** [comment]
Duplicate of #39691

Closing

**Comment by jhouse-solvd** [comment]
Duplicate of #39691

Closing
