### ISSUE TITLE
Review SD Mission Statement and Update

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39695]
## Issue Description
Review SD Mission Statement and Update to reflect new scope and purpose

-Idea/brainstorming Mural

-Nicole to also set up a candidate mural

Mission Statement as a result of our Discovery/Research and vision:

**Mission:  Optimize the utility and usability of the Platform by surfacing insights, providing service guidance, and working with teams to create processes that improve the VFS user's journey.**
---
## Tasks
- [x] Prep mural for Workshop
- [x] Team members preload [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1651149322371/c6b12275ed1e394ee2f2bd9cfbfca7c2fd6884a1?sender=u4397b715dc3690a417b71483) with ideas
- [x] [Workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1651166057402/7e29b068733f5870ca93de1e5d01774137b8a748?sender=u4397b715dc3690a417b71483) to discuss
- [x] Generate a candidate statement
- [x] Get signoff on statement from PO
- [x] Get alignment with Product Lead/Research Lead

## Acceptance Criteria
- [x] Finalized Mission Statement will be drafted
- [x] signoff from PO
- [x] Confluence will be updated with mission statement
- [x] ToT slide will be updated with mission statement

**Comment by raywangoctova** [comment]
Mission statement approved.
