### ISSUE TITLE
[UX] Create Research Plan for End-to-End Testing in Prod for PCI and CI with Veterans

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39708]
## Problem Statement
Determine how end-to-end testing can take place in production for pre-check-in and day-of check-in with Veterans.  Ideally, we'd have vets who have upcoming appt. who could potentially do a diary study to share experience from PCI->day of CI. 

## Background Info
We have been hearing some feedback from St. Louis about the confusion between pre-check-in and check-in. We haven’t run an end-to-end study, since the MVPs of both pre-check-in and check-in went live. We will be gathering some feedback when we go on-site at St. Louis. However, that study will not capture feedback as a Veteran is actively engaging with pre-check-in. It will all be after the fact. Nira and I were discussing that a diary study may be a possibility to get feedback as a Veteran is actively completing pre-check-in, then we can follow the diary study all the way through the day of check-in. We discussed when this study would have the most impact from our UX perspective. We thought this might be something to do immediately following the new editing scope and translation work. We would also like to content test some wording within pre-check-in, since pre-check-in was mentioned to be a confusing term too. With our suggested timeline, we might be able to make some changes (if need be) before we are live everywhere.

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create research plan (template in research checklist above)

## Acceptance Criteria
- [ ] Research plan for virtual e2e testing of both PCI and CI.
- [ ] Research plan for in person e2e testing of both PCI and CI.
