### ISSUE TITLE
Conduct a Discussion with Console UI Team

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39700]
## Issue Description
The Console UI Team is doing work that includes the creation of a Product List, we would like to discuss their approach and use case with them, and determine the best way to collaborate going forward.

---
## Tasks
- [x] Discuss product list with Console UI team
   - [x] Identify use case(s)
   - [x] Identify required attributes
   - [x] Identify willingness to collaborate on a unified solution
- [x] Discuss internally to determine how to collaborate in a few ways/contexts:
   - [x] Assess the positives/negatives of their approach and determine if anything they are doing could improve the quality (accuracy/reliability) of our list
   - [x] Add any of their required attributes into our list
   - [x] Record any inputs our outputs that would be required based on their use cases
- [x] Share initial plan for incorporating their use cases into our list to determine if that would be acceptable - _emphasize that this will not be the confirmed approach until we have talked with all stakeholder teams._

## Acceptance Criteria
- [x] We have discussed the team's requirements and have incorporated them into our approach
- [x] We have agreed with the team on a plan to approach/incorporate theirs into our overall list

**Comment by CBonade** [comment]
Updated current status of this based on https://vfs.atlassian.net/wiki/spaces/TTT/pages/2150858889/Sync+Console+UI+--+QA+Standards+Re+Product+List and our subsequent conversation following that meeting

**Comment by JoeTice** [comment]
Based on the discussion with the Console UI team on 4/23, need to discuss and make decisions on:
- Which requested attributes do we feel we can add?
- Which requested attributes does data exist for, and can be populated currently?
- Which do we feel are out of scope of our product list? (if any)

**Comment by CBonade** [comment]
Initial thoughts on the attributes after our call:

Technologies list - this is more applicable to a repository as opposed to a product. For example: Most products inside vets-website would likely have nearly-identical, if not identical technologies lists. This lines up with the way Console UI described it in their explanation as well.

Dependencies (both ways) - we are already planning to track third party dependencies. I'm not sure if we need to add cross-product dependencies to that as well, but it would not be difficult to do as we are already evaluating that in test selection.

Subcomponent Products - Console UI confirmed this is a duplicate of the 'features' we are already tracking.

Relevant links (tools, environment) - I don't believe we currently have plans to duplicate entries on a per-environment basis. Therefore, relevant links to tooling can likely be stored as a part of documentation. I don't believe this needs a new field.

Documentation links - If we don't have this on another list already, we should 100% include this.

So, to take all and apply to the above questions:

1) I think we can add them all, but only should add documentation links and possibly cross-app dependencies.
2) The cross-app dependency information already exists as part of our test-selection process, we'd just need to redirect it. Dependencies and subcomponent products don't currently exist but we already had plans to track this data for this list anyway.
3) I feel expanding out the list to include a separate entry for each environment is out of scope for the goal of our product list.

**Comment by pjhill** [comment]
Meetings and clarifying questions have been asked. All that remains is to synthesize the collected information which is a task that will be worked under a separate ticket.
