### ISSUE TITLE
Need to clearly state and maintain service offerings of SDT in an appropriate page/section

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39704]
## Issue Description
Need to clearly title and state service offerings of SDT in an appropriate page/section

---
## Tasks
- [x] Determine where they should live
- [x] Determine what content should accompany the offerings (products/services)

## Acceptance Criteria
- [x] Page will be set up in Confluence
- [x] Offerings will be formatted and documented
