### ISSUE TITLE
Set up File Provider for Traefik to configure routing to an external service

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39713]
## Issue Description
Traefik can be used as a reverse proxy, so we can potentially route directly from the EKS ingress to vets-api without vets-api being inside EKS, and also without migrating the reverse proxy into EKS.

Discovered that Traefik cannot route to an external service using a K8s CRD, so must use a file provider for the time being.

---
## Tasks
- [x] Create Application Manifests for Traefik
- [x] Create ArgoCD Project for PST-CIT with roles
- [x] Create ArgoCD Application to manage the Traefik configurations in dev

## Acceptance Criteria
- [x] ArgoCD will be deploying the Traefik configurations from the Application Manifests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/43

**Comment by dginther** [comment]
ArgoCD Application and Application Manifests
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/478

**Comment by dginther** [comment]
This ticket is blocked by the Infrastructure team: https://dsva.slack.com/archives/CTYQL39FE/p1649880987821359
