### ISSUE TITLE
Non-authenticated MHV users should not be able to view the transition page

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#39714]
## Issue Description
Anyone not authenticated with MHV attempting the view the transition page should be redirected to the VA home page

---
## Tasks
- [x] Add a redirect to the home page for all non MHV users attempting to view the transition page.

## Acceptance Criteria
- [x] Add a redirect to the home page for all non MHV users attempting to view the transition page.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
