### ISSUE TITLE
[Research] Create Conversation Guide for Telephone Appointments PCI & CI

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39711]
## User Story
- As a Veteran, I want to be able to check in from my mobile device for phone appointments

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the conversation guide 

## Tasks
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize conversation guide to GitHub folder
