### ISSUE TITLE
[User Testing] HLR: Synthesis

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3972]
## User Story or Problem Statement
As a UX Designer, I need to synthesize gathered data from user testing sessions so I can identify successes, gaps, pain points, and improvements to the Higher Level Review design.

## Goal
_A document containing data from user testing sessions that has been organized into common themes and recommendations._

## Objectives or Key Results this is meant to further
- _Finding pain points in the design_
- _Discovering improvements to the design_

## Tasks
- [x] _Synthesis document has been created_
- [x] _Organize data from the interview sessions into themes_
- [x] _Create recommendations based on key themes determined from the usability research_

## Acceptance Criteria
- [x] Key Themes are identified
- [x] Recommendations are created
- [x] Readout is generated
- [x] Meeting held with Andrea and decisions are made on scope and implementation/design expectations

**Comment by kevinstachura** [comment]
Research Readout: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/research/research-summary.md
