### ISSUE TITLE
Collaboration Cycle - Refine operational guidance and clarify VFS expectations for Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39744]
## Problem Statement 
VFS teams can sometimes struggle to know what is expected of them at a Design Intent. They have trouble coming to the touchpoint with the appropriate artifacts, and when they do bring the appropriate artifacts, they may be too far along or non-mobile versions. VFS teams also do not know what to expect from Governance team re: feedback or what the scope or boundaries of our review are. VFS teams also may not know what to expect from the Design Intent meeting itself.

Each Governance team practice area (design, accessibility, content, IA, and research) has their own process and resources for reviewing the materials provided at a Design Intent. However, there is not documentation to guide us internally/operationally. The documentation that does exist is generic for all practice areas. This can be challenging for new people joining the team, especially when there is no shadowing with the departing team member. The lack of practice area specific guidance has exposed gaps in our review process.

How might we improve VFS-facing guidance so that VFS teams are better prepared for the Design Intent?
How might we provide clear, direct guidance to our team members for the Design Intent so that our process is seamless, repeatable and consistent?

## Hypothesis or Bet

1. If we clarify our expectations for Design Intent, then VFS teams will be better prepared for the meeting.
2. If we refine our operational guidance for Design Intent, then Governance team members will take a consistent approach with each product at each Design Intent.
3. If we write specific guidance for each practice area for the Design Intent, then we will address the gaps, overlaps, conflicting feedback that occur in reviews now.
4. If we expand our practice area-specific guidance for Design Intent, then we can onboard Governance team members faster and more efficiently.

 _If we refine our operational guidance, then VFS teams can expect to receive more thorough feedback at the Design Intent._

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*
- [ ] We have refined and/or expanded the Design Intent touchpoint page on Platform Website with clarified expectations
- [ ] We have determined how each practice area handles each requested/provided artifact at Design Intent
- [ ] We have refined our operational guidance so each practice area has their own unique process to follow for Design Intent

## Notes

- We want to make sure we're not creating superfluous guidance
- Recording of a design Intent that went well?
- Want to try and reduce copy/content on the page (make it lean!) yet still explain everything that needs to be explained

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
May 30, 2023

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by shiragoodman** [comment]
@annekerr49 would you like me to add a dependency? We will be completing #39845 before we will begin this effort.

**Comment by annekerr49** [comment]
Yes Please Shria

Thank you
Anne
