### ISSUE TITLE
Unable to Create Additional "Browser Tests" in Datadog

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39745]
# Description
Datadog appears to be limiting the creation of `browser tests` to an upper limit of 50. We have already reached that upper limit. After discussing the issue with Infrastructure and Identity teams, there don't appear to be too many tests that can be cleaned up. We need to contact DOTS and/or Datadog to request the limit be increased.

Here's a screen shot of the error message --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/92946636-382a-47ad-8fbd-5956db562f62)

# Tasks
- [x] Contact DOTS
- [x] Contact Datadog
- [x] Provide any necessary information to DOTS / Datadog in order to obtain the increased limit
- [x] Verify the limit has been increased

# Acceptance Criteria
- [x] Datadog `browser tests` upper limit has been increased to a number sufficient to accomplish the use cases currently required by the Platform

**Comment by pjhill** [comment]
I contacted the Infrastructure team to get their input --
https://dsva.slack.com/archives/CJYRZK2HH/p1649343310944459

**Comment by pjhill** [comment]
Limit increased to 200, and all monitors have been created that we need for this effort.
