### ISSUE TITLE
[FE] Test translated DS components

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39759]
## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

The Design System team has made a pre-release with translation functionality for the text input and date components: https://dsva.slack.com/archives/C01DBGX4P45/p1649281567268609

We should test with our app and ensure it works for us.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Branch created with pre-release
- [ ] Tested with check-in and pre-check-in
- [ ] Feedback provided to DS team
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Tested with lang attribute on Main tag. Text input looks good and can confirm translation. Also regression tested rest of the site.
