### ISSUE TITLE
Tier 3 Process Flow and Efficiencies

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39760]
## Issue Description
_In order to improve our tier 3 issue handling process, we need to better understand the flow so we can identify areas to improve. We also have new (tier 3) teams starting in the coming weeks and we want to train them on the process so we can streamline any fixes they may need to complete for our Veterans_

---
## Tasks
- [x] _Document tier 3 process and iterate with improvement updates_
- [x] _Document plan for training new tier 3 team building on VA.gov_

## Acceptance Criteria
- [x] _Improved tier 3 process is documented_
- [x] _Plan for training new tier 3 teams is documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
1. The documented new process is here: 

https://vfs.atlassian.net/wiki/spaces/Contact/pages/2153742472/Tier+3+2022-2023+Process+Revamp+Draft

**Comment by Kimberley2019** [comment]
@clantosswett @jwoodman5 please review the proposed Tier 3 Revamp process [here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2153742472/Tier+3+2022-2023+Process+Revamp+Draft).

Please provide feedback or feel free to throw some time on our calendars (cc @manalo-soco) to discuss further and finalize.

**Comment by Kimberley2019** [comment]
Reached out to the Identity team on 5/20 to set up a meeting to review new tier 3 process.  
As of today, awaiting a response.

Contacted Sharon K from the Profile team, our original meeting was for 5/25, but will need to be rescheduled until 5/27 or 5/30.

I also provided her with examples of what some of thought to be profile issues but are truly identity issues.  During our meeting we agreed to discuss issues that her team are able to assist with along with details they may need to move forward with research and resolution.

**Comment by jwoodman5** [comment]
@Kimberley2019 I see the requirements of this ticket as `done`. I think we should create separate tickets for the actual training activities, which I will do.
