### ISSUE TITLE
[Build] HLR Legacy Issues: Implement Endpoints, Schemas and New Tests

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3976]
## User Story:
As a Back-end engineer, I need to implement end points, new tests and implement schemas for legacy issues so that legacy issues can be incorporated into HLR.

## Tasks
- [ ] implement end points
- [ ] execute new tests 
- [ ] implement schemas

## Acceptance Criteria:
- [ ] implemented end points
- [ ] executed new tests 
- [ ] implemented schemas
