### ISSUE TITLE
[BE] Contact information: Investigate if there are any backend changes needed for when we no longer require an international postal code

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#39776]
### Background

On 4.7.22, we learned about a veteran who was not able to save their address on VA.gov because they live in a country that does not have postal codes. The VA.gov profile currently requires international postal codes even though they are not required by the VA Profile backend. So, we are removing this requirement from the frontend.

However, we are not sure if any backend changes are required as part of this update. This ticket is to determine whether any backend changes are needed.

**Note: We will still require zip codes for all USA addresses.**

### Tasks

- [x] Determine if we need any backend changes for when we no longer require an international postal code on the frontend for international addresses.
- [x] If changes are needed, scope that work and create a ticket.
- [x] If changes are needed, sync with Mark Dewey. Frontend work happening in #39775.
- [ ] If no changes are needed, let Mark and Samara know and close this ticket.

### Acceptance criteria

- [x] Path forward has been determined and communicated to the team.

**Comment by tpharrison** [comment]
@mdewey In the BE code, for international address types, international post code is a required field.  The change should is pretty straightforward.  Let's discuss tomorrow and then I'll open a ticket for the work.

**Comment by Samara-Strauss** [comment]
cc/ @SKasimow for awareness ☝️ that Tom will need a backend ticket to remove the international postal code requirement from the backend.
