### ISSUE TITLE
Conduct Brainstorming Session

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#39801]
# Description
Schedule a brainstorming session with the team to throw ideas around for identifying abandoned products within the VA.gov repositories. Prefer automated scans for abandoned products, but a manual survey may be good enough.

# Tasks
- [x] Schedule a brainstorming session with the team
- [x] Conduct the brainstorming in Mural
- [x] Synthesize the results of the brainstorming

# Acceptance Criteria
- [x] Brainstorming results have been recorded
- [x] Brainstorming results have been combined and synthesized to create solution for uncovering orphaned products on VA.gov

**Comment by CBonade** [comment]
Holden and I have scheduled to chat tomorrow morning at 9am to brainstorm ideas.

**Comment by pjhill** [comment]
Some brainstorming results here: 
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1649770555617/b180774465d4a1f8bd8501273317ab7c20edbd24?sender=peterhill4315

**Comment by holdenhinkle** [comment]
Not sure where I should be putting this:

I reviewed the code in the directories for manifest.json files that are not yet correlated with a product to make a guesstimate as to whether the code in each directory is a product or a feature.

For each suspected product, I then made note of the last time the code in the directory was updated, and the name of the teams that are listed as codeowners for the directory.

See the suspected products sheet - https://docs.google.com/spreadsheets/d/17SJrLx2OTJrZ52E374zO7vbD1_Qej4CFqfGspb_xDBM/edit#gid=363551978

**Comment by holdenhinkle** [comment]
List of product questions Curt and I brainstormed based on where we're at - https://docs.google.com/document/d/1UOteH52G7G9ZMBaAEURfH3ZSmKRHwKIJvQBcTcK5ntk/edit

**Comment by holdenhinkle** [comment]
Tim Wright told Curt that some products don't have a manifest.json file, which meant they weren't on our radar. So I made a quick pass through all the directories in src/applications and made note of which directories are missing a manifest.json file.

Possible products that don't have a manifest.json file:
- vets-website/src/applications/coronavirus-chatbot/
- vets-website/src/applications/disability-benefits/disability-rating-calculator/
- vets-website/src/applications/find-forms/
- vets-website/src/applications/third-party-app-directory/

**Comment by pjhill** [comment]
Brainstorming conducted and sythesized
