### ISSUE TITLE
Change your address in your profile updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#39804]
## Story

As a Veteran who wants to change my address or other information in my VA.gov profile, I want to be able to quickly sign in and understand clearly which benefits/services get updates from my profile and which don't.

## Tasks

- [ ] Move sign-in widget up and revise h2s and h3s from Qs to phrases
- [ ] 2nd editor review
- [ ] Publish changes
- [ ] Request accessibility audit check
