### ISSUE TITLE
[04/11/22] VEText and AVS ATO Scan Tracker

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#39807]
## Description
Create scan tracking spreadsheet for AVS and VEText ATO with extended information
---

## Acceptance Criteria
- [ ] Review Scan process with Justin & Read SOPs
- [ ] Expand Spreadsheet for AVS and VEText to include detailed Scan information
- [ ] Review with Justin, Paras, and Allison
- [ ] Share with Shane 
- [ ] Begin weekly review process
---

**Comment by lindsay-insco** [comment]
Created
