### ISSUE TITLE
Copy for Profile for APO/FPO/DPO

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3980]
## User Story: 

As a UX designer I need final copy so that I can finalize workflow mockups.

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Acquire copy from Content team - Owner 

- [x] Update mock ups - Owner 

- [x] Review with team - Owner 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_

**Comment by artistgreen** [comment]
Due to the differences in address formats for military bases within the US versus bases outside of the US, the checkbox label should something more descriptive to the effect of:
"I live on a United States military base outside of the United States"

 Edit Mailing Address Overlay.png

Users will select United States for their country if they live on a military base within the US.

When the user checks the box:

The UI will display helper text informing as to why the Country field is greyed out
the Country field will become disabled and default to 'United States'
The City field label will change to APO/FPO/DPO and will become a drop down element (versus an input box)
The State field options will be reduced to just the regions: AA, AE and AP
Military Base checked.png

APO-FPO-DPO dropdown.png

State drop down options.png

**Comment by artistgreen** [comment]
@peggy - we opened a new ticket for copy.

This is your reply regarding copy from #3023 

Hello, please see my content recommendation below. I've also provided some screenshots of form pages where we have used helper text.

{checkbox} I live on a U.S. military base outside of the United States.

{copy} The United States is automatically chosen as your country since you live on a military base outside of the country.

A couple of other tweaks to mention:

What are the red dots in the screenshots? Should these be (*Required) instead?

Labels and buttons should be sentence-cased. Can you update your mockup to have the label Street Address>> Street address

Zip code label should be: Postal code. (I know there is some inconsistency across forms and pages etc. and I'm trying to fix as I see them.)

also, I saw there was question above about helper text in forms. We have used helper text in forms. I've upload a few screenshots as a visual. Let me know if we'll need any additional helper text for this design?

Health care form https://staging.va.gov/health-care/apply/application/insurance-information/va-facility

![image](https://user-images.githubusercontent.com/53535009/70331418-69fc3800-180d-11ea-98bf-c53dfa3d26b3.png)

![image](https://user-images.githubusercontent.com/53535009/70331430-6ff21900-180d-11ea-86d6-2627ec92e13d.png)

**Comment by artistgreen** [comment]
Thank you @peggygannon!  I'm updating the screens and have a quick question regarding helper text.  Exploring the forms, I noticed we use 2 forms of helper text.   
1. The drop down version from your image examples
2. A version that appears after the user clicks a check box (without a drop down element)

Here is an example - the helper text is not displayed until the user clicks the checkbox for 'I don't want to use direct deposit'. 

![Screen Shot 2019-12-02 at 4 59 23 PM](https://user-images.githubusercontent.com/53535009/70331652-dd05ae80-180d-11ea-8847-daf2c11c1292.png)

Are there reasons we would use one versus the other?

Here are my updated screens - if we use the drop down method for helper text, what should the drop down label read?

![APO-FPO-DPO–1](https://user-images.githubusercontent.com/53535009/70332619-06273e80-1810-11ea-8fbe-181b9e7d4a36.png)

![APO-FPO-DPO–2](https://user-images.githubusercontent.com/53535009/70332658-150df100-1810-11ea-9400-8d2bfe346538.png)

**Comment by Samara-Strauss** [comment]
Is this for copy for the profile or for the benefit applications? I thought profile copy was finished in #3023. I want to make sure it's clear what we're tracking here.

**Comment by Justin-Pickett** [comment]
@erikphansen  mentioned in sprint review/refinement noted this may be more than a copy change. Possible grooming need to extend the AC requirements. This may need to break out into another ticket. Will follow up with @artistgreen .

**Comment by Justin-Pickett** [comment]
Closing this ticket. We'll coordinate with @erikphansen and @artistgreen on the next steps with this and determine if more work is needed on the copy and front end.
