### ISSUE TITLE
[FE] Add test case for day-of demographics confirmation timeout

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#39810]
## Description

Slack thread: https://dsva.slack.com/archives/C02UP02HHGX/p1649693182463949?thread_ts=1649687888.495389&cid=C02UP02HHGX

Response: http://sentry.vfs.va.gov/organizations/vsp/issues/63851/events/5bac073cb8344c3fb98a92ef04afdd01/?project=3&statsPeriod=14d

We should have a test case to confirm that the veteran is not presented with an error screen if the demographics confirmation call returns a 500 after a timeout.

[#42561](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42561) adds mocks for this API request to cypress. After that is complete, this ticket can be unblocked. The purpose of this ticket is to add a test that confirms the user is not redirected to an error page if one of those requests errors. We will want to run those requests without the mocks to test.

## Tasks
- [ ] Add error case senario to ApiInitionalizer patch requests (withError) that are created in the other ticket mentioned.
- [ ] Test case has been added 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Testing only, nothing to validate on stage or prod. Closing with code review and merge
