### ISSUE TITLE
[BE] Direct deposit: Pull accounts that are being flagged for fraud and investigate whether they are actually locked or not

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#3981]
## Background

Per our call with the EVSS team and then our team regroup, we have decided to look into some of the accounts that are currently receiving the "flagged for fraud" error when they go to update their direct deposit information. We are going to try to confirm with Adam Kinder's team whether these accounts are indeed locked because of fraud or not.

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [ ] Generate list of people who are receiving the flagged for fraud error on VA.gov.
- [ ] Figure out how to securely get this list to Adam Kinder.
- [ ] Review Adam Kinder's confirmation on whether these account are locked or not.
- [ ] Determine next steps

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] We have determined next steps based on whether all/some/none of these accounts are actually flagged for fraud or not.

**Comment by Samara-Strauss** [comment]
I don't think we need to do this anymore, per conversations with EVSS/BGS/the Fraud team over email on 12/10/19.
