### ISSUE TITLE
[FE] Direct deposit: Reach out to EVSS with questions about "flagged for fraud" error

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#3982]
## Background

This to-do comes out of our call with the EVSS team/our team regroup.

## Tasks 

- [x] Get it touch with EVSS about the two end points that are generating the "flagged for fraud error"
- [x] Determine if showing the "flagged for fraud" error is the correct frontend implementation for both of these error keys. 

## Acceptance Criteria: 

- [x] Determine if showing the "flagged for fraud" error is the correct frontend implementation for both of these error keys.

**Comment by erikphansen** [comment]
I just reached out to the Fraud team to get more info re: the `cnp.payment.routing.number.fraud.message` - `Routing number related to potential fraud` errors we are seeing.

**Comment by Samara-Strauss** [comment]
This is done. Per conversations with EVSS/BGS/the Fraud team over email on 12/10/19, `cnp.payment.routing.number.fraud.message` gets returned when someone uses a routing number that is kept in BGS's FINCL_INSTN_SCRTY_CHECK table of fraudulent routing numbers. These routing numbers were blocked in 2015 because they were being used in large scale fraud ring. These routing numbers actually can be used legitimately, but users who enter one of these routing numbers need to make those updates over the phone, by mail, or in person.

Follow on work is captured in #4109 for this.
