### ISSUE TITLE
New Platform page for trauma-informed research guidance

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#39828]
## User Story
As a researcher, I need to conduct research that is trauma-informed so that I'm not putting participants through any undue triggering or trauma inducing space.

As a researcher, I need to understand best practices and VA guidance around trauma-informed research so that I can prepare myself and create a research environment that takes care of all participants.

As a researcher, I need guidance to know when my research should undergo increased scrutiny, so I know when to implement extra precautions in relation to trauma-informed research.

As a Platform team member, I need to a place with trauma-informed research guidance, so I can link or otherwise point folks with questions to best practices and VA approved guidelines on this important topic

- Intended Audience: 
   - VFS/VSA team members
- Desired Outcome: 
   - New Platform page that includes trauma-informed research best practices and VA guidelines
- Due Date: 

## Description
Discussions in [#research-ops](https://dsva.slack.com/archives/C0216PL32HJ) and in [#inclusive-research](https://dsva.slack.com/archives/C033ZS9E7EW) have highlighted the need for trauma-informed research guidance for our researchers. This is currently an on-going discussion, so this ticket is dependent on the outcome of the discussion. These discussions should end with guidance on this topic. This ticket is specifically to take that guidance and create a place on Platform for that to live.

## New Artifacts 
Platform page for trauma-informed research

## Artifacts Potentially / Confirmed Needing Updates
Platform page: [research overview](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html)
Platform page: [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
Platform page: [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html)

## Tasks
- [ ] Create new page for trauma-informed research
- [ ] Update other pages as needed to include links to this new page

## Acceptance Criteria
- [ ] "Insert Page Name" Confluence document has been updated per guidance
- [ ] "Insert Page Name" Confluence document has been created per guidance
- [ ] "Insert GitHub template" GitHub template has been created per guidance
- [ ] "Insert GitHub template" GitHub template has been updated per guidance
- [ ] "Insert Platform Website Page" on Platform Website has been updated per guidance
- [ ] "Insert Platform Website Page" on Platform Website has been created per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@joshkimux we discussed this ticket at our refinement today and @naomimarcussen mentioned you were working on something similar. Could you let us know the current state?

**Comment by joshkimux** [comment]
@shiragoodman yes! Would love to provide an update.

[We have drafted guidance here](https://docs.google.com/document/d/1bu8wg2_WVFGDwoYK-uSqzapq915FJsvnEpNA_ifr_bU/edit?usp=sharing), including links to all draft templates. Consider this google doc as our operational hub for our new trauma practice.

We're kicking off our first trauma practice sync next Monday to begin reviewing, editing, and adding to guidance. 

Here are the following pages/templates we're hoping to complete and add to platform guidance:

## Guidance (Content)
1. Welcome to our Trauma Practice (welcome and introduction doc to trauma-informed research and trauma practice at the VA) `Final Draft` `Ready to Publish 11/11/22`
2. Checklist for trauma-informed research `Rough Draft` `Blocked`
3. Protocol for Recognizing and Handling Trauma `Rough Draft` `Needs Social Care Worker Review`

## Templates
1. Email outreach template `Not Started`
2. [Research plan template](https://www.google.com/url?q=https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md&sa=D&source=docs&ust=1667571355383976&usg=AOvVaw0yNg6bIGPQq5J8VTZq_trE) `Draft on Github`
3. [Conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md) `Draft on Github`
4. Debrief and presentation template `Not Started`
5. Participant bill of rights `Not Started`
6. Wellness packet `Not Started`

**Comment by shiragoodman** [comment]
Thank you @joshkimux ! this is fantastic! glad to see you're involved with such important work.

@naomimarcussen what are your thoughts on publishing to Platform Website? I realize only the intro guidance is (near) complete, and many of the templates and additional guidance are still in draft. I think, similar to the Inclusive research guidance, we should publish what we have now and make a plan to address the remaining docs once Josh lets us know they're available.

**Comment by joshkimux** [comment]
@shiragoodman and @naomimarcussen update on this! We've learned _alot_ since drafting up this guidance and have since taken up a [community learning model instead](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/trauma) where we share learnings through relational mentoring.

That being said, I'd love for us to explore the possibility of publishing our community page (as opposed to our trauma-informed guidance notes) which would include:
- [Instructions on how to join the VA trauma community](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/trauma#how-do-i-join)
- [Our list of community members and volunteers](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/trauma#participate-and-connect-with-our-community)
- [Facilitation instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/trauma/facilitation-instructions.md)
- [Community guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/trauma/community-guidelines.md)

I'd imagine our bi-weekly notes might be a bit too much (it would need too many updates) 😅 , but I'd love to link out to them.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
