### ISSUE TITLE
Update Platform guidance for unmoderated research

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#39825]
## User Story
As a researcher, I need to know the latest guidance about conducting unmoderated research, so my research sessions can be as successful as possible while following VA guidelines.

As a Platform team member, I need Platform to be updated with the latest guidance so I can offer team members links to the most relevant and updated information when they seek help.

- Intended Audience: 
   - VFS/VSP team members
- Desired Outcome: 
   - Update guidance specific to unmoderated research sessions
- Due Date: 

Assignee: Clayton
Peer Reviewer: Jim

## Description
Recently a VFS team conducted unmoderated research and [presented some best practices](https://dsva.slack.com/archives/C0NGDDXME/p1646677888064789) they found. We want to make sure any relevant guidance on Platform is updated to take into account this work.

## Artifacts Needing Updates
Platform Page: [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html)
Confluence page: [Clayton - Copy of Planning Unmoderated Studies - WIP](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2235990017/Clayton+-+Copy+of+Planning+Unmoderated+Studies+-+WIP)

## Tasks
- [x] Look through the [presentation](https://dsva.slack.com/archives/C0NGDDXME/p1646677888064789) and note any needed updates to current Platform guidance
- [x] draft updates to the Platform Page: [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html)

## Acceptance Criteria
- [x] Platform Page: [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html) has been updated with best practices
- [ ] change has been communicated on the #research-ops slack channel - 7/7: with Clayton OOO, the change will not be communicated via the #research-ops Slack channel
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
Ready for peer review, prior to publish.

**Comment by shiragoodman** [comment]
@jimuhh have you been able to peer review this?

**Comment by shiragoodman** [comment]
@chaseakirby since Clayton is OOO starting today, we need to validate that the changes are published on PW

**Comment by jimuhh** [comment]
@claytonzook completed all the recco'd changes except for the first, which he gave good reasons for not implementing. I changed the subhed title on second para so hopefully we're good to go. [Please confirm](https://vfs.atlassian.net/l/c/7t1E05ed).

**Comment by jimuhh** [comment]
@shiragoodman Draft archived.

**Comment by jimuhh** [comment]
I didn't before but I am now. Looks good so far. The only suggestion so far
is to spell out Paperwork Reduction Act in the subtitle and follow w/
acronym so that page is scannable for people who don't know what PRA is.

**Comment by shiragoodman** [comment]
@jimuhh I think you responded to the wrong ticket. Was this in response to ticket #42503 ? @CherylEvans FYI
