### ISSUE TITLE
Update README and migrate tickets to va.gov-team repo

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39827]
## Issue Description
Platform teams have been asked to use only the va.gov-team repo. This tasks in this ticket are to update the README to point them to the appropriate issue template in the va.gov-team repo
component-library

---
## Tasks
- [ ] Update the README in the component-library repo to point to the issue template in the va.gov-team repo
- [ ] Migrate issues from the component-library repo to the va.gov-team repo

## Acceptance Criteria
- [ ] README in component-library repo points to the issue template in the va.gov-team repo
- [ ] All current issues (about 7) in the component-library repo are moved over to the va.gov-team repo.

**Comment by k80bowman** [comment]
@caw310 can we close this?
