### ISSUE TITLE
Update Platform page for research observer guidance

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#39823]
## User Story
As a first-time research observer, I need to know what procedures I should follow so that I can ensure I'm not being disruptive to the research

As a first-time research observer, my role is a bit different than experienced observers. I need to know the difference so I don't take on responsibility that I'm not prepared for.

- Intended Audience: 
   - New VFS/VSP team members who observe research to get acquainted with our products and process.
- Desired Outcome: 
   - Ensure new team members understand they aren't expected to take on the same responsibilities as an experienced observer.
   - Ensure new team member understands the procedure for setting up a session to observe
- Due Date: 

## Description
The current Platform page with [observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/Observer-guidelines.1622311177.html), explains details and responsibilities that are required of new team members observing for the first time to get acquainted with our work. Also in order to keep the number of observers to a reasonable level to ensure the integrity of research sessions, there is a process that should be followed by new teammates when selecting which sessions to join, and this guidance is not currently on Platform.

## Artifacts Potentially / Confirmed Needing Updates
[Platform page: observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/Observer-guidelines.1622311177.html) 
note: this might require a new page instead of a page update - tbd

## Tasks
- [ ] draft language for new team member observers
- [ ] determine if a new page needs to be created, or if this information can live on the existing observer page

## Acceptance Criteria
- [ ] [Platform page: observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/Observer-guidelines.1622311177.html) has been updated per guidance
- [ ] "New Page" on Platform Website has been created, if required, per guidance
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
