### ISSUE TITLE
Tier 1 / 2 / AVA Ownership and Coverage Plan

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39833]
## Issue Description
_We want to formalize ownership for each of our tiers/classes of support issues we receive along with our plan for coverage when folks are out of office or otherwise unable to handle these issues_

---
## Tasks
- [ ] _Use Sprint 75 grooming session to define and document ownership and coverage for tier 2 / 3/ AVA_
- [ ] _Publish above document in Confluence_

## Acceptance Criteria
- [ ] _Tier 2 / 3/ AVA ownership and coverage plan is documented in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
Duplicate. Closing.
