### ISSUE TITLE
Veteran Support User Journey Map

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39831]
## Issue Description
_We want to identify the most valuable problems we can solve for Veterans in their support request and resolution process. To do this, we are going to develop a comprehensive Veteran support user journey map. This issue is for the planning phase._

---
## Tasks
- [x] _Define plan for approach to developing the Veteran support user journey map_
- [x] _Document the plan and publish in Confluence_

## Acceptance Criteria
- [x] _The plan for developing our Veteran support user journey map is published in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
Draft plan located here: 
https://vfs.atlassian.net/l/c/HpHGpoMM 

Further developing initial approach and requirements

**Comment by manalo-soco** [comment]
Updated Journey is here: https://lucid.app/lucidspark/692d3e56-ca5b-4d5c-8308-9204885bf80a/edit?invitationId=inv_37f0a5e2-1270-412d-b527-2a6e940ad245 

Recommended next steps: 

1. Review with the Contact Center team
2. Scope User Interviews with (Veterans, Tier 1 Call Center teams)
3. Create list of enhancements for current Journey incorporating (2021 OmniChannel research, team review and recommendations, AVA process )

Nice to haves: 
-Review with VEO product owners or working group mentioned in the 2021 OmniChannel research 

-

**Comment by manalo-soco** [comment]
@jwoodman5  Closing this issue. 
Updated Confluence [page here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2162524258/User+Journey+Veteran+Support+DRAFT+Q2+2022)
