### ISSUE TITLE
Cleanup Tier 3 Support Inbox

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#39834]
## Issue Description
_Our tier 2/3 support inbox has grown beyond our ability to handle on a daily basis due to lack of attention. We need to draft and execute a plan to address all emails to-date and implement consistent daily management_

---
## Tasks
- [x] _Draft and align on plan to address all support inbox emails to-date_
- [x] _Draft and align on plan to manage the support inbox on a daily basis_
- [x] _Execute plan to address all support inbox emails to-date_
- [x] _Implement support inbox daily management plan_

## Acceptance Criteria
- [x] _Support inbox is current due to all previously existing emails being addressed_
- [x] _Support inbox (consistent) daily management plan has begun_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@edpearson20 I think this was done. If you agree, feel free to do the honors of checking the boxes and closing out. Thanks.
