### ISSUE TITLE
SSOe WebKit public-facing infomational message

### ISSUE THREAD

**Issue by codyreinold-usds** [department-of-veterans-affairs/va.gov-team#39841]
## Issue Description
SSOe is currently experiencing a major regression that is impacting all WebKit browsers. This includes all browsers on iOS and Safari on Mac.

As a potentially affected user of VA.gov or a related site, I want to see an notice informing me of this concern, and offering guidance on how to proceed. 

The message should be in a blue info box, not a yellow of

==

### You may have trouble signing in right now
We’re sorry. You may have trouble signing in with certain browsers or devices right now. We’re working to fix this problem as fast as we can.

[expandable link] Here’s what you can do now

- Try to sign in from a different browser or device. Use a browser other than Safari (like Edge, Chrome, or Firefox). If you're using an iPhone, iPad, or other Apple device, try a different device (like a laptop or desktop computer).
- If sign in fails, refresh the page in your browser. Refreshing the page may fix the problem.

If you still have trouble signing in, try again later. Or call us at 800-698-2411 (TTY: 711). We’re here 24/7.

==

---
## Tasks
- [ ] Add the notice to the Sign In Modal
- [ ] Add the notice to the Unified Sign In Page
- [ ] Limit showing the message to potentially affected users (only WebKit browsers)

## Acceptance Criteria
- [ ] Message shows exclusively for WebKit browsers
- [ ] Message is shown in a blue `info` box
- [ ] Message is shown on both the Sign In Modal and the Unified Sign In Page
- [ ] Language has been reviewed by implementing team, to ensure it presents as human readable
- [ ] Message has been tested on both desktop and mobile devices

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by codyreinold-usds** [comment]
Slight update in text:

You may have trouble signing in right now
We’re sorry. If you're using the Safari browser or an Apple mobile device, you may have trouble signing in right now. We’re working to fix this problem as fast as we can.
[expandable link] Here’s what you can do now
Try to sign in from a different browser or device. Use a browser like Edge, Chrome, or Firefox. If you're using an iPhone, iPad, or other Apple device, try a different device (like a laptop or desktop computer).
If sign in fails, refresh the page in your browser. Refreshing the page may fix the problem.
If you still have trouble signing in, try again later. Or call us at 800-698-2411 (TTY: 711). We’re here 24/7.
