### ISSUE TITLE
Design - Auth Profile - Personal Info Revision - Create UAT Convo Guide

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#39866]
## Background

As a Designer I want to create a research plan and conversation guide for Personal Information Revision UAT so that I am organized and know what I will ask participants to do.

## Tasks
- [ ] Create conversation guide
- [ ] Review with PM
- [ ] Share with PO

## Acceptance Criteria
- [ ] Create conversation guide
- [ ] Review with PM
- [ ] Share with PO

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - can you point this and adjust the points on [39318](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39318)

Lmk if there is anything else I need to add or adjust - thanks!

**Comment by cgednalske** [comment]
Hi [@SKasimow](https://github.com/SKasimow) and [@Samara-Strauss](https://github.com/Samara-Strauss) --- same as the research plan ticket. I just realized these tickets say to review with PM and then send to PO, so I've asked Sharon if she wants to look over the guide first. However, I'm also posting the link here in case we're not following the same steps for this study since Sharon recently joined the team and you prefer to both take a look simultaneously on Monday. 
 
Here's the[ Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/uat/conversation-guide.md). As I mentioned for the research plan, in addition to the primary goal of confirming the functionality, I've also included questions to help to confirm if our changes have addressed the concerns we uncovered in our last research study - and if they were helpful in making Veterans feel more comfortable about sharing their information.

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss -- no rush on my end, but I want to make sure you saw that the convo guide is also ready for review. My comments here are practically identical to those for the research plan, so I realize they could be easy to mix up. 😄  Thanks!

**Comment by Samara-Strauss** [comment]
I am so sorry, and thanks for the nudge -- I completely missed this yesterday. I'll check it out this morning.

**Comment by Samara-Strauss** [comment]
This looks great!! I think all the UAT tasks look good to me and capture what we need to evaluate. My only feedback is on some of the usability questions:

### Review Personal information section - 5-7 minutes

> What are your thoughts on the information shown here?
> 
> What, if anything, do you find confusing about this?

Do we need to ask these questions again? I don't see how this impacts the study or what we'd do with the results. It's not that we can't take note or ask questions if someone demonstrates something is confusing or concerning -- we absolutely should follow up if someone is clearly confused or expresses concern with what they are looking at -- but this feels like we're trying to re-do the usability testing instead of following up on the few design updates we need to evaluate since the original research.

### 3. Gender identity - 5 minutes

> What are your thoughts on the information shown here?

I understand why you asked this for gender identity given the controversy over it in our original study. However, I still think you can take this out given that people will likely share concerns when you ask whether they would share this information or not with the VA.

I also really appreciate that you are directing people to save Prefer not to answer in case they do not want to disclose their gender identity.

**Comment by cgednalske** [comment]
Thank you @Samara-Strauss! Good point with both sections. I think you're right that if there's any confusion, concerns, or strong opinions, they will probably come out regardless or via other questions - certainly within the Gender identity field.

I'm good with those changes! Will make them shortly and confirm here.

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow those changes have been made! Let me know if anything else comes up, otherwise it sounds like this is set for now.

**Comment by Samara-Strauss** [comment]
Great! Thank you. This should be good to close.
