### ISSUE TITLE
Documentation update: Accordions 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39860]
## Issue Description
Make updates to Accordions on on design.va.gov and Storybook to fix the discrepancies that have been identified. 

Discrepancies
1. Labels are different - Accordion vs va-accordion.  Suggestion we change Storybook to Accordion (web component)
2. Storybook has Change Header Level example. What is the purpose of this? 

Sketch updates needed
1. We only have accordion closed and open for borderless, not bordered. 
2. Borderless open has the wrong drawer icon. 
3. There are only 2 symbols (there should be 4) and they are bordered and collapsed. 

Question: 
- Should add multi-select to keep parity with USWDS?

---
## Tasks
- [x] Add  View guidance for the Accordion component in the Design System subtitle below label for va-accordion in Storybook  (See example on va-modal)
- [x] Change title on design.va.gov to Accordion  (make it singular)
- [x] Add link in Storybook back to Accordion on design.va.gov  https://design.va.gov/components/accordions
- [x] Update link to Storybook on design.va.gov to "View va-accordion in Storybook"
- [x] Update Sketch file with bordered accordion 
- [x] Fix Sketch file Borderless open has the wrong drawer icon. 
- [x] Update Sketch symbols - There are only 2 symbols (there should be 4) and they are bordered and collapsed.

## Acceptance Criteria
- [x] Storybook has “View guidance for Accordion component in the Design System" subtitle 
- [x] Storybook has a link to Accordion on design.va.gov  https://design.va.gov/components/accordions 
- [x] Accordion link to Storybook is labeled "View va-accordion in Storybook"
- [ ] Sketch file has bordered accordions
- [ ] Sketch file has the correct icon
- [ ] Sketch file has 4 symbols for Accordions

---

**Comment by humancompanion-usds** [comment]
For the Sketch symbol naming I'm going with:

> Group (i.e Navigation; optional) > Component name > Viewport (e.g. mobile, desktop, tablet) > Variation > State

Thus for Accordion:
* Accordion > desktop > bordered > open
* Accordion > desktop > bordered > closed
* Accordion > desktop > default > open
* Accordion > desktop > default > closed
* Accordion > mobile > bordered > open
* Accordion > mobile > bordered > closed
* Accordion > mobile > default > open
* Accordion > mobile > default > closed

I've created these and made sure they matched what is in the Design System and Storybook.

**Comment by GnatalieH** [comment]
The Accordion page and its symbols look great to me, @humancompanion-usds!

**Comment by pdavies88** [comment]
Accordions are multi-select by default we might be able to remove the 2 tasks related to that behavior
