### ISSUE TITLE
Update documentation: Address block

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39867]
## Issue Description
There is no guidance on use of Address block. 

There is no Address block component in the Sketch library.

Note: People have requested an example with a 5-digit zipcode as well. This is how we prompt users to enter their own information (contrasted with a 9-digit zipcode, like the Storybook example).

---
## Tasks
- [x] Draft guidance on use of Address block 
- [ ] Share draft with Matt or Natalie
- [x] Update design.va.gov with the guidance on use of Address block (https://design.va.gov/components/address-block) 
- [x] Add Address block to Sketch library

## Acceptance Criteria
- [x] Address block pattern on design.va.gov has guidance on usage https://design.va.gov/components/address-block
- [x] Sketch library has Address block pattern 

---

**Comment by caw310** [comment]
@humancompanion-usds , No Sketch update needed, but could you draft user guidance?

**Comment by humancompanion-usds** [comment]
I took care of the Sketch update. Didn't take long and I wanted to complete the page and have the link to the Sketch page for the component. 

I did not address (ha) issue #243. @bkjohnson and @k80bowman - Do you think we should go the schema.org route with addresses as detailed in #243? It seems like to really make this work we'd have to go the web-component route. Agree?

**Comment by bkjohnson** [comment]
I'm not sure what schema.org thing you're talking about, that issue number links to an issue about telemetry.

**Comment by humancompanion-usds** [comment]
Sorry, @bkjohnson - different repos caused the issue # to get mapped to the wrong repo. I mean issue 243 in our repo: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/243

**Comment by bkjohnson** [comment]
Oh, I see. I agree that in order to enforce something like that the best approach would be a web component with props.
