### ISSUE TITLE
Documentation update: Additional info

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39862]
## Issue Description
Make updates to Additional info on on design.va.gov and Storybook to fix the discrepancies that have been identified.

1. There is no "No border" version on design.va.gov.
2. There is no guidance at all on design.va.gov and thus the only existing guidance is in the Sketch library itself. The guidance is actually in Patterns > Supplemental Content

Guidance in Sketch library that is missing on design.va.gov 
"This component can be used in forms and on static content pages to reveal helpful information that provides contextual details about applications, processes, or steps in a form. In the open state of the component, the use of Headings 4-6, body text, links, ordered lists, and unordered lists is encouraged. Default, hover, and focus states are shown here.
Additional info “closed” symbols. These are responsive for new content as you type, and can be dragged to the desired width while maintaining 8px space between the text and caret:"

"Combine the “open” symbols with the Child content symbol to have a group that is responsive both horizontally and vertically. Note that the caret faces upward in the open state. The Child content symbol is designed with 16px top margin so it can be stacked directly under the open symbol and maintain proper spacing:"

Sketch library
There is no "No border" version in the Sketch Library. 

---
## Tasks
- [X] Add View guidance for the Additional info component in the Design System below label for va-additional-info in Storybook (See example on va-modal)
- [X] Add link in Storybook back to Additional info on design.va.gov  https://design.va.gov/components/additional-info
- [X] Update link to Storybook on design.va.gov to "View va-additional-info in Storybook"
- [X] Add "No border" version of additional info to design.va.gov
- [ ] Add guidance on use of Additional info to design.va.gov. Use the guidance Patterns > Supplemental Content  - See the text above under guidance
- [x] Update Sketch file to include "No border" version in the Sketch library. 

## Acceptance Criteria

- [X] Storybook has link “View guidance for Additional info component in the Design System" 
- [X] Additional info on design.va.gov includes a "No border" version
- [ ] There is guidance on use of Additional info on design.va.gov 
- [X] va-additional-info  in Storybook  includes (Additional Info web component)
- [X] Storybook has link to Additional info on design.va.gov  https://design.va.gov/components/additional-info
- [X] Additional info link to Storybook is labeled "View va-additional-info in Storybook"

---

**Comment by GnatalieH** [comment]
@caw310 I just added the "no border" version of the Additional info component to the Sketch library and checked off the task. FYI.

**Comment by caw310** [comment]
Documentation on when to use and how to use will be in sprint 77. Awaiting audit from Allison before writing up guidance.

**Comment by humancompanion-usds** [comment]
I have the audit from Allison and I have a draft. However, I had not seen the additional issues:

* https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/424
* https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/575
* https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/650

Thus I'll take another pass at this and try to address some of these problems before we send it out into the world.

**Comment by CourtneyChambers77** [comment]
The Additional Info component should be validated to meet the WCAG 2.1 AA accessibility guidelines. 
The Additional Info Notification uses aria-controls and aria-expanded attributes to convey the expand and collapse functionality to assistive technologies.
The Additional Info Notifications use ARIA role="listitem" to convey their semantic meaning to users of assistive technologies.
Pressing the closes the close button to close the Additional Info.
A single notification always needs a minimum of one Heading component as its content.
Heading in a notification should include a maximum of 80 characters.
Paragraph in a notification should include a maximum of 120 characters.

**Comment by humancompanion-usds** [comment]
@CourtneyChambers77 - 

You mentioned "Additional Info Notifications" - Is this the same as an expandable alert? https://design.va.gov/components/alert-expandable If so, I will add it to that page. If not, can you point me to an instance of what you are describing?

Are these for Expandable Alerts as well? If so, it doesn't look like our examples have a heading in their content. Are you recommending that we need to add a header? Is that true for all Additional Info component variations as well? Because currently they do not have headers either.
* "A single notification always needs a minimum of one Heading component as its content.
* Heading in a notification should include a maximum of 80 characters."

**Comment by caw310** [comment]
@SarahKay8 , would you please work with Courtney on this? Thanks!
