### ISSUE TITLE
Update documentation: Button

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39874]
## Issue Description
Make updates to Buttons on on design.va.gov and Storybook to fix the discrepancies that have been identified.

Discrepancies found: 
- Default buttons are consistent across design.va.gov, Storybook, and Sketch. But confusingly there are three types of "Default" labels that are used in the Sketch file:
 - Default (button name), Default size (not Big), and Default state. 
- Wizard button in design.va.gov is called Primary in both Storybook and Sketch.
- Active button in design.va.gov and Storybook doesn't show a focus halo, but Pressed button in Sketch library does show a focus halo.
- Focus halos in Sketch have square corners whereas the focus halos in the developed component are rounded (to match the corner radius of the button).
- ProgressButton and its various stories are not represented in any way on design.va.gov. Only Back/Continue buttons from this category are represented in Sketch under the label "Button pairs".

Storybook 
No guidance on the buttons other than ProgressButton, which has a table with some elements and their descriptions. (What are these elements?)

Sketch Library
The buttons are grouped by "Default size" and "Big button size" and each size has the following labels:

Blue button is called "Default"
Green button is called "Primary"
Blue outlined button is called "Secondary"

Default, Hover, Focus, Pressed, Disabled states are documented for both Default and Big button sizes.

Button pairs:
Confirm/Cancel
Back/Continue

Guidance in Sketch
Button pairs
Use in form flows to present options to proceed forward or go back to the previous form chapter, and to confirm and submit forms."

Notes: 
We should consider something between action link and button. A quieter button ala Adobe's Spectrum. Perhaps an outline button but in gray instead of blue. Also, perhaps we need a button that transitions into an activity icon (also ala Adobe).

Finally, we should consider adding Button Group to keep parity with USWDS and because I bet the mobile app could use a Segmented button.

---
## Tasks
**Everywhere**
- [x] The solid blue button should be renamed Primary.
- [x] The Secondary button name stays the same.
- [x] The green button should be renamed Continue or Action. We are deprecating our Wizard green buttons, and our goal (per Collab Cycle) is to only use the green button when the user has to complete an action (such as login) to continue with a process. I'm open to other name suggestions, but we should avoid the name Wizard.
- [x] Are we using Disabled buttons? I thought we were moving away from disabling form elements for accessibility reasons. We may need to remove Disabled examples everywhere if we aren't recommending this button state. 
- [x] We need to align on what the active button state looks like. I don't understand the use case -- when would this state be triggered? I can force the active state in the inspector for a button on va.gov. However, when I press down using my mouse (which is what I consider a button's active state to actually be), the style is the same as the focus state. @bkjohnson do you have any insight on this?
- [x] Align button label names across Sketch, Storybook, and design.va.gov after we agree on the labels. This goes for individual buttons and button groups.

**Storybook**
- [x] It would be good to show an example of the focus state in Storybook and on design.va.gov for the three main button variations.
- [x] Audit the ProgressButton stories in Storybook. Default story looks just like a regular button. 
- [x] Add the button pair of back/continue
- [x] The Back/Continue button pair I've seen in the wild contains an outlined button (Back) and a solid blue button, (Continue) whereas our Back button example is solid. Is this where we can align with USWDS and their Button Group?
- [x] Relabel the Submit button example in Storybook to say Submit and not Click me!

**Sketch**
- [x] Make focus halos rounded and not square in Sketch library.

**design.va.gov**
- [x] Check to make sure guidance on design.va.gov is still relevant pending the updates.
- [x] Add button pairs example

## Acceptance Criteria
- [x] Focus halo on Active button is in design.va.gov and Storybook
- [x] Title is Button (singlular)
- [x] Progress Button stories are the same in Storybook and design.va.gov 

---

## Mockups

[Here are the Sketch Button mockups](https://www.sketch.com/s/c2d5deb5-dc3a-441c-8369-b3eb140776c9)

**Comment by caw310** [comment]
@humancompanion-usds @GnatalieH , I'm not sure which one of you did the audit for this. It's not completely clear to me what needs to be updated. Would one of you provide more clarification on what needs to be done?

**Comment by GnatalieH** [comment]
@caw310 I'm in the process of listing out the necessary updates for Buttons. I'll update this comment shortly.

**Comment by bkjohnson** [comment]
You're right - the mouse press triggers the active state, and that remains until the user releases the mouse button. It looks like whether or not a button can be active _and_ focused simultaneously [depends on your browser & OS](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus).

The focus and active styles are actually slightly different:

![Zoomed in view of focused and active buttons](https://user-images.githubusercontent.com/2008881/164336569-8e04f4c2-973b-4b24-a2ad-54c94cf464f7.png)

The focused button has `#003e73` for its background color and the active button has `#112e51`. Here's some experimenting I did where I gave active buttons a red background with purple text, and focused buttons a yellow background (sorry :sweat_smile: ). When I click on a button I'm seeing it become active and focused, because the purple color of the active state is coming through and the yellow background of the focus is coming through.

![button being active and focused, but has a conflict over background color](https://user-images.githubusercontent.com/2008881/164338822-f6ec2fc0-05ac-4e72-bf83-5e91216c9cfe.gif)

I think setting the `background-color` on both focus and active states makes it harder to know which one you're in, and I don't know if there's an official way of deciding which one takes priority. That might be browser dependent.

---

Also, we're not seeing any active state on the "primary" button because its styling is overriding the `:active` state with higher specificity. This button is technically active even though it doesn't look any different:

![background-color of active button overridden on primary button](https://user-images.githubusercontent.com/2008881/164338196-78678ead-7acf-44b6-8689-823d36dd7e6c.png)

**Comment by GnatalieH** [comment]
Thanks for that explanation, @bkjohnson! Super thorough. That makes sense. I'm going to take a look at USWDS and other design systems to see how they present Buttons.

**Comment by humancompanion-usds** [comment]
Okay, I reviewed this Sketch file: https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d

* "Press" should be "Active" - I'm pretty sure that's the state we mean.
* I'd remove the "Reverse" button unless you think it really does exist. It isn't here: https://design.va.gov/components/button
* I see ProgressButton mentioned in this issue but I have no idea what that is. I'm familiar with Progress Bars. Where can I see a ProgressButton?
* Can you convert your comment from 8 days ago into a task list, sort it by task area (Sketch, Storybook, Design System) and check off the things you think you've addressed in Sketch? That would help me review this. Thanks.

**Comment by GnatalieH** [comment]
@humancompanion-usds regarding the Press vs. Active state, please see the comment by @bkjohnson in this ticket from 9 days ago. They are actually two different things, and the Active state depends on the browser you are using. I converted things to a task list in my earlier ticket.

**Comment by humancompanion-usds** [comment]
@GnatalieH - Yes, move the Button page and symbols into the library. Please work with an engineer to get the Storybook changes in sync. I will look at the guidance changes that may be necessary however, I think we have a separate issue to deprecate the green button for all but one case so may use that issue to track that work.

**Comment by caw310** [comment]
Design work is done. Need the documentation updates.

**Comment by andresriveratoro** [comment]
@GnatalieH It looks like we may have to update the background color for the `Active` buttons to `#162e51` in Sketch. This is the color that we're using for the `usa-button-active` utility class (same on UWSDS).

**Comment by GnatalieH** [comment]
> @GnatalieH It looks like we may have to update the background color for the `Active` buttons to `#162e51` in Sketch. This is the color that we're using for the `usa-button-active` utility class (same on UWSDS).

@andresriveratoro is this quote referring to just the primary button? I can make this change and also change the secondary active bg color to `#112e51`.

**Comment by andresriveratoro** [comment]
@GnatalieH Correct, that first comment was for the Primary button as seen in Sketch.

**Comment by humancompanion-usds** [comment]
From issue #470, we still need to update the guidance:

* Design.va.gov suggests using an icon on buttons in some cases (second to last bullet [in this section](https://design.va.gov/components/buttons#how-to-use-buttons)), but there aren't any examples of this in the documentation (including storybook) or in Sketch. It'd be helpful to have examples.

Essentially, Liz is asking for the Button Pairs examples that are in Sketch to be in design.va.gov and Storybook as well. I will update the task list in this issue to ensure that gets done.

**Comment by GnatalieH** [comment]
@andresriveratoro I updated the Sketch file to match the specs you provided.

**Comment by andresriveratoro** [comment]
ProgressButton is nested inside Buttons in Storybook. If you go to our Storybook and click on Buttons -> default to see our Button examples, you might easily miss that ProgressButton exists unless you notice it in the side navigation. It's too easy to miss because you can't scroll to it. I understand that it's not on the same page because our buttons are native elements with styling and ProgressButton is a React component with props. 

![Screen Shot 2022-05-10 at 18.05.05.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/68a55267-9582-43f9-b557-8cee597edf4a)

**Why are we trying to combine these 2 together on design.va.gov? The React component has props, so how do we display this on the Buttons page without creating confusion? Our regular buttons will not have these props. Do we want to create a separate page for ProgressButton in both Storybook and design.va.gov?**

---

The ProgressButton examples in [Sketch](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/jgazRMo/) are using Font Awesome icons. Currently, the ProgressButton React component accepts `beforeText` and `afterText` props that accept a string which we're passing in unicode characters in the Storybook examples. **Does Sketch need to be updated to use these unicode characters?**

Sketch:
![Screen Shot 2022-05-10 at 18.36.56.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/47a7a498-0f71-4d57-929f-c6fa9a46c81a)

Storybook:
![Screen Shot 2022-05-10 at 18.39.57.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/690cfeae-2547-465a-9d69-0fd04d01328a)


---

If/when we create a button web component, we should consider how to display the different states in our examples without having to use utility classes. See [Slack discussion](https://dsva.slack.com/archives/G01BJ3ESXL4/p1652207202300519).

---

Our green button has been represented in Storybook using the `va-button-primary` utility class. This green button is currently named `Primary` in Storybook. Sketch was updated to rename the blue button from `Default` to `Primary`, and the green button to `Continue`. This can create confusion when talking about the `Primary` button as Brooks mentions in this [pull request](url). **How do we want to fix this?**

Sketch:
![Screen Shot 2022-05-10 at 18.41.37.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/5708fa91-183f-4cad-b1d1-6874e948ff70)

Storybook:
![Screen Shot 2022-05-10 at 18.30.55.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/6ee1ca47-387e-4b84-bcc3-939b44966ff9)

**Comment by GnatalieH** [comment]
@andresriveratoro can we change the class names to better suit our use cases? I know it's not as easy as it sounds to do that, but the current names are non-intuitive and cause a lot of confusion to folks who are not developers. I don't think we want to call the green button Primary, especially since we're deprecating most use cases other than signing in. And as I mentioned, Default is not a good name for a button because it's a state. I don't see the current class names working for us in the long term, but perhaps @humancompanion-usds has a suggestion. Thanks for your work on this Andrés.

**Comment by caw310** [comment]
Need to identify where green button exists. 
@bkjohnson , please find instances of green button in use. 
@GnatalieH please check with Allison and Sean on uses of green button. 

Note: If we deprecate, the green button should only exist or be used in the one alert that prompts user to sign in or create an account.

**Comment by caw310** [comment]
DST decided to deprecate green button.

**Comment by andresriveratoro** [comment]
Generating React component documentation has been more difficult than anticipated. I've created an [issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/856) for the work required in `component-library`. I'll create another issue to update `vets-design-system-documentation` and update ProgressButton documentation to include the attributes, properties and events. In the meantime, do we want to hard code it for now?
