### ISSUE TITLE
Update documentation: Alert Boxes

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39872]
## Issue Description
Make updates to Alert boxes on on design.va.gov and Storybook to fix the discrepancies that have been identified.

Discrepancies 
1. Labels are different. Alert boxes vs va-alert
2. Examples and stories do not line up well. Specifically, for "Sign in or tool prompt" the example in the Sketch library is much more useful and instructive than what is in the design system. The example in Storybook should be updated to match 
3. There are more stories than examples
4. The background-color examples have a "close-btn-aria-label" but don't need it since there is no close button. Would be good to remove the extraneous attribute.
5. The Design System doesn't show each background color alert and it should follow USWDS.

Sketch library
1. Variation named "Sign in or tool prompt" in Design System looks to be the same as "Continue" in Sketch Library. Use the design system name. 
2. There is a "success-small" variation in Sketch that doesn't exist in the system. It seems similar to the USWDS Alert - Slim variation. 
3. The padding issue mentioned in issue #470 must have been fixed at some point. However, our padding should probably be 16px instead of 20px and our left-border 8px instead of 10px in order to match the USWDS. Also, our icon size is kinda small (16px x 16px) rather than (24px x 24px)

Notes: Our padding should be 16px instead of 20px and our left-border 8px instead of 10px in order to match the USWDS

---
## Tasks
- [X] Add (Alert web component) to the label for va-alert in Storybook 
- [X] Change Alert boxes to Alert
- [X] Make sure examples on design.va.gov and stories are the same
- [X] Remove the "close-btn-aria-label" if it isn't necessary (Decision was to leave close button)
- [X] Check with Matt and/or Natalie on the background color alert which should follow USWDS
- [X] Update the background color per feedback from Matt and/or Natalie
- [ ] Update the "Continue to "Sign in or tool prompt" so it is the same as name in the Design System in Sketch library
- [ ] Remove the "success-small" variation in Sketch library that doesn't exist in the system.
- [ ] Update the padding issue to 16px instead of 20px and our left-border 8px instead of 10px in order to match the USWDS in Sketch library
- [ ] Update icon size to 24px x 24px in Sketch library

## Acceptance Criteria
- [X] va-alert  in Storybook  includes (Alert web component)
- [X] Alert boxes is renamed Alert on design.va.gov
- [X] Storybook has link to Alert  on design.va.gov  https://design.va.gov/components/alert
- [X] Alert link to Storybook is labeled "View va-alert in Storybook"
- [X] Examples of Alert boxes are the same on design.va.gov and Storybook
- [X] The "close-btn-aria-label" has been removed if it is deemed unnecessary (Decision was to leave close button)
- [X] Alert boxes background only story has stacked components of all colors matching USWDS
- [ ] Sketch library has "Sign in or tool prompt" instead of continue
- [ ] Sketch library does not have "success-small" variation
- [ ] Sketch library padding is updated 
- [ ] Sketch library icon size is 24 x 24

---

**Comment by pdavies88** [comment]
@GnatalieH developer work has been completed and merged

**Comment by humancompanion-usds** [comment]
@GnatalieH - This was still assigned to me and I thought there were going to be documentation changes or that we had done the work to bring us inline with the USWDS dimensions but, neither of those happened in this ticket. So I just updated the Sketch symbol names and put them on a page then created a PR to link to them in Sketch. If you could look over the symbol names that would be great.

I'm going to update this bug to reflect what else needs to be done here.

**Comment by humancompanion-usds** [comment]
@caw310 - I've updated the tasks in this ticket to reflect the work remaining to be done. Please file a new issue to update the padding to 16px instead of 20px, our left-border to 8px instead of 10px, and icon size to 24px x 24px in Sketch and the component itself in order to match the USWDS dimensions. Thanks.

**Comment by caw310** [comment]
@humancompanion-usds , I've created a new ticket which we can get in an upcoming sprint. 
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/810

**Comment by GnatalieH** [comment]
@humancompanion-usds the only thing I noticed was that what we have been calling the [full-width alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--fullwidth) isn't represented that I noticed. It has a top border rather than a left-side border. The Alert page looks fantastic in Sketch, thanks!
