### ISSUE TITLE
va-text-input add datalist

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39873]
## Description

The `va-text-input` web component does not currently support the `list` attribute which can be used to provide auto-complete capabilities to the input. Check out the [example of a datalist on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

## Tasks

- [ ] Add datalist to `va-text-input`
- [ ] Add tests
- [ ] Add storybook example

## Definition of done

- [ ] `va-text-input` accepts datalist options
- [ ] All tests passing

**Comment by pdavies88** [comment]
On DSC agenda for 4/22 to chat about work related to the original ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/481

**Comment by Mottie** [comment]
Will not implement. There is no use-case for this addition.
