### ISSUE TITLE
526: Cleanup & improvements

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39884]
## Description

Fix some issues noticed within the 526 form, e.g. excessive spacing & unnecessary fieldset/legend usage.

## Tasks

- [ ] Fix margins at top of form
- [ ] Evaluate & remove (if possible) unnecessary fieldset/legend usage

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
cc: @saderagsdale
