### ISSUE TITLE
Create Mockup(s) Incorporating DSVA Design Feedback

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#3988]
## User Story:
As an eBenefits Team member, I want a revised mockup incorporating design team feedback so that I know how to proceed with iterative development of the VA.gov Rated Disabilities page.

## Tasks
Link to XD posted for review is [here.](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/1d4fafce-8d16-4a89-a14b-97d795772b74/RD-Screen-Tool-2ALT?fullscreen)
- [x] Gather feedback from XD post
- [x] Create initial mockup
- [x] Present to Shawna and DSVA team
- [x] Address any further feedback
- [x] Present finalized mockup to team

## Acceptance Criteria:
- [x] Mockup created and addresses DSVA Design feedback/input

**Comment by sporeboy** [comment]
DSVA Edits made. Revised layout presented to Kevin Hoffman for review and approved 12/9.

XD layout is here: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL
