### ISSUE TITLE
Make updates to 3 static education pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#39894]
## Issue Description
Education Service has gotten feedback that students aren’t aware of how the irrevocable election to use Post-9/11 instead of MGIB works. So Joseph Maltby reached out with edits to several pages to try to address this. 

Pages to edit:
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
https://www.va.gov/education/eligibility/
https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/

---
## Tasks
- [x] Edit 3 pages. Here's the Word doc with tracked changes, as a starting point. We'll apply our plain language standards and style and voice to what stakeholders gave us. 

[https://app.zenhub.com/files/133843125/c4aceffa-d0b2-44a5-aa9d-e1b31420ea4f/download](https://app.zenhub.com/files/133843125/c4aceffa-d0b2-44a5-aa9d-e1b31420ea4f/download)

- [x] Send stakeholders the preview link so they can see the edits we've made in addition to theirs. 
- [ ] Finalize edits (after coming to agreement with stakeholders).

## Acceptance Criteria
- [x] 3 static pages are live with updates.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
I sent an email with the 3 preview links to stakeholders on 4/15. Waiting for either a thumbs up or more feedback. 

Before we publish, we need to copyedit these updates and run through the prepub checklist.

**Comment by bethpottsVADEPO** [comment]
I got approval from the stakeholders, so we published these pages today.

**Comment by RLHecht** [comment]
Closing ticket
