### ISSUE TITLE
Letters: Replace e-benefits link

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#39899]
## Description

If no records are found in the letters app, a link to `ebenefits/download-letters`. Remove this link as the ebenefits destination no longer exists. Additionally, there are 2 links to eBenefits apply for COE and download DD 214 pages that need to be updated.

## Tasks

- [ ] Remove link to ebenefits
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
cc: @saderagsdale

**Comment by Mottie** [comment]
Visually removed the Certification of Eligibility (COE) link based on [content recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39900#issuecomment-1103185741), but will restore the COE link once the form is in production on VA.gov.
