### ISSUE TITLE
Get Console access

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39906]
# Tasks
- Concurrently:
  - [x] Set up SOCKS proxy
  - [ ] Set up login.gov login: [Create "sandbox" login.gov account](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2128380343/Create+a+Sandbox+Login.gov+account)
- [x] Consult with Console UI to understand what deliverable they want and when
- [ ] Assess the content in these two documents: https://platform-console-ui-dev.vfs.va.gov/docs/?filters%5Buser%5D=all
- [ ] ...?

# Reference info
- ➡️ **What is the Console?**
  -  ➡️ [**Here's an explanation**](https://vfs.atlassian.net/wiki/spaces/CUI/pages/2048950331/Product+Outline+-+Console+UI+MVP)
  - Here's the Console itself: https://platform-console-ui-dev.vfs.va.gov/homepage
- What are the document sets that we have to review?
  - See the link in the "Tasks" section of this ticket.
-  ➡️ What exactly are we reviewing for?
   - ➡️ Because "review" is ambiguous, the four of us (Liani Amy Samara Lauren) are going to work together daily to set direction.  
   - ➡️ We are also going to have to touch base with the Console UI team to some degree, so expect future sync-ups with that team, yall taking the initaitive to Slack them, or both.
---
- SOCKS proxy instructions
  - You might think, "How do we access the Console?  When I click on the link right above, I get a 'no internet' error."
    - Yes, we need ~internet~ access to the VA's private network.  There are two ways of getting the internet: SOCKS proxy is the most straightforward way for mac users, and _supposedly_ PIV card is most straightforward way for Windows users, but we can also use SOCKS.
    - [SOCKS setup instructions for mac](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html#InternaltoolsaccessviaSOCKSproxy-ConfiguringaccessonMac) <-- idk if the jumbled instructions were fixed in between last week (when Gretchen and I did this) and now, which is why I want a working session
    - [SOCKS setup instructions for Windows](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html#InternaltoolsaccessviaSOCKSproxy-ConfiguringaccessonWindows) <-- Samara, we will go thru this together on Monday morning.  There is no expectation that you have to battle this before then!

- Slack convos for Liani's reference:
  - [Console UI's ask](https://dsva.slack.com/archives/C02SLSSGSBX/p1649453455024719?thread_ts=1649447321.177429&cid=C02SLSSGSBX)
  - [SOCKS for Windows convo](https://dsva.slack.com/archives/C02SLSSGSBX/p1649875834767729)

**Comment by lianilychee** [comment]
Liani Amy Samara Lauren - Console collab

- Today
  - Samara Amy - create sandbox [login.gov](http://login.gov/) account
  - Lauren - find how to manipulate text in the Console
    - What repo is Console based off of?
      - Ask #platform-console-coordination (Thomas Ferrin, John Chapin) for repo link
      - What is the repo organization - where can we manipulate microcopy vs. long-form text (.md files)?
    - Exposure to ".md syntax"
  - IF WE GET THERE - All - Review Console docs (either together or separately)
    - Click around, explore, generally find things to improve.  Potential structure — Five S, five M, five L remediations
- --
- EOS goal: 
  - Exactly what is TBD, let’s see where we are tomorrow
  - Will def involve:
    - executing change(s) to Console or Console docs
    - something around alternate mac SOCKS proxy instructions

**Comment by amygoldman** [comment]
[Recording of the Console tour](https://drive.google.com/file/d/1V4_aYfzckyRCwfw420JftK_d-YBGyUeJ/view)
