### ISSUE TITLE
Retire Post-Launch Check-In touchpoint from Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39924]
## User Story
As a VFS team member, I want to have an updated list of required Collaboration Cycle touchpoints so that I can prepare properly.

As a Governance team member, I want to remove all guidance and references to the Post-Launch Check-In so that VFS teams receive correct and current guidance.

- Intended Audience: VFS Teams
- Desired Outcome: No references to Post-Launch Check-In
- Due Date: N/A

## Description
We have recommended removing this touchpoint and Chelen has agreed that the Post-Launch Check-In should not be Platform's responsibility to validate that the team's initiative has been completed and closed out. 

## Artifacts Needing Archived
[Platform Website: Post-Launch Check-In](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781956691/Post-launch+check-in)

## Artifacts Needing Updates
[Platform Website: Collaboration Cycle Overview](https://vfs.atlassian.net/wiki/spaces/CC/overview)
[Platform Website: Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) (Shira will update)
[General Orientation Collaboration Cycle Slide](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit)
[Platform Website: Collaboration Cycle Overview Image](https://vfs.atlassian.net/wiki/spaces/CC/overview)

## Tasks
N/A

## Acceptance Criteria
- [x] [Platform Website: Post-Launch Check-In](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781956691/Post-launch+check-in) has been archived
- [x] [Platform Website: Collaboration Cycle Overview](https://vfs.atlassian.net/wiki/spaces/CC/overview) has been updated
- [x] [Platform Website: Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints) has been updated
- [x] [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) has been updated
- [x] [Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow) has been updated
- [x] [General Orientation Collaboration Cycle Slide](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit) has been updated
- [x] [Platform Website: Collaboration Cycle Overview Image](https://vfs.atlassian.net/wiki/spaces/CC/overview) has been updated
- [x] Create Change History post
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Announcement has been shared on #vfs-all-teams

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@shiragoodman  I have archived and updated the target pages.  Changes won't take effect until scroll VP has been run.  Once Custom Tracks Flow is updated, I will complete the remaining tasks within the Acceptance Criteria field.

**Comment by shiragoodman** [comment]
@chaseakirby I just recognized that we'll also need to remove Post Luanch check in from the Platform Orientation general orientation deck. This is also where the image on [Platform Website: Collaboration Cycle Overview](https://vfs.atlassian.net/wiki/spaces/CC/overview) comes from and that will still need to be updated. Can you update the ticket and help Cheryl make these changes?

**Comment by shiragoodman** [comment]
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/9d8e0325-a687-4a75-8784-ae70579d46fb)

**Comment by CherylEvans** [comment]
@shiragoodman @chaseakirby Updated.  Deleted Post Launch check in from the Platform Orientation general orientation slide deck.

**Comment by shiragoodman** [comment]
assigning myself to finish this one out! Thanks, Cheryl :)

**Comment by shiragoodman** [comment]
Custom tracks has been updated. Waiting on Platform Website changes to go live and then ill announce on #vfs-all-teams

**Comment by shiragoodman** [comment]
@chaseakirby I have updated the [Change History post ](https://vfs.atlassian.net/wiki/spaces/CC/pages/1846870032/Change+history)on Platform Website and it is ready to be published tomorrow at the 12 noon scroll viewport publishing. For the post on #vfs-all-teams, please share the following:

> 
Hey VFS team members. I have an update on the Collaboration Cycle. **The Post-Launch Check-in has been retired.** Please refer to our[ Change History log ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) on Platform Website for more information. Thank you!

**Comment by shiragoodman** [comment]
@chaseakirby i think this is ready to close!

**Comment by chaseakirby** [comment]
@shiragoodman Great! Closing it out!
