### ISSUE TITLE
Update Platform Orientation page VA.gov Overview video and add note*

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#39925]
## User Story
As a VFS team member, I want to read welcome text and purpose of Orientation before watching the VA.gov Overview video.

- Intended Audience: VFS Teams
- Desired Outcome: Clear welcome message and better page preview.
Current page preview.![image.png](https://images.zenhubusercontent.com/619d1b3396a3389c5e2dd17f/73d5d696-2cdb-49c0-a4f7-4f39add30788)
- Due Date: N/A

## Description
The VA.gov Overview video needs to be moved lower on the page below the welcome text.
Check with Platform Content team to see if the embedded video can be made larger.
Add a Note stating that the video was recorded in ___ of 2021 and architectural elements of VA.gov may have changed since the video was recorded. 

## Artifacts Needing Updates
[Platform Orientation: Purpose](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)

## Tasks
- [x] Move VA.gov Overview video down the page
- [x] Make VA.gov Overview video larger (if possible)
  - [ ] Check with Platform Content team
- [x] Add note "Video was recorded in __ of 2021 and architectural elements of VA.gov may have changed since the video was recorded."

## Acceptance Criteria
- [ ] [Platform Orientation: Purpose](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)
 has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by jimuhh** [comment]
[Video link](https://www.youtube.com/embed/0cc-VdfI4Q8) is at

**Comment by jimuhh** [comment]
I reached out to the folks # vsp-confluence to see if there are standard CSS classes or size specs for videos that I could apply here.

**Comment by jimuhh** [comment]
I've [embedded the video](https://vfs.atlassian.net/l/c/AgcZxWcG) lower down at the recommended 560 x 315 size.

**Comment by jimuhh** [comment]
Added note about video creation date

**Comment by jimuhh** [comment]
What should Rachel's title be in the caption?

**Comment by shiragoodman** [comment]
@jimuhh The VA.gov Overview video was recorded in November 2021.

In the caption, we can say, "In this video, former OCTO-DE VA.gov Platform lead, Rachael Roueche, provides a 
brief overview of VA.gov."

**Comment by shiragoodman** [comment]
please make the Note the same style as the Note below re: the Welcome page. The Welcome page blurb should NOT be in the note style.

**Comment by jimuhh** [comment]
OK. I've made those changes. [Have a look.](https://vfs.atlassian.net/l/c/otnXP3Ww)

**Comment by shiragoodman** [comment]
@jimuhh looks good. I have 2 minor comments:

1. Please add a comma after "Roueche"
2. Please change "December" to "November"

Great job making the embedded video larger!

**Comment by jimuhh** [comment]
Edits made. Thanks!

**Comment by shiragoodman** [comment]
opening this back up (@chaseakirby and I are the only ones closing tickets at this time). Chase can you work with @jimuhh to make sure all AC is completed? thanks!

**Comment by chaseakirby** [comment]
@shiragoodman Thanks Shira! I have reviewed the AC and those do look good.
@jimuhh I have one comment that I noticed when I went to Platform Website that I think we may want to check out and fix before closing this ticket. When viewing the page on Platform Website, the Platform Crew Logo underneath the video is aligned slightly oddly to the middle right of the page. (But it does have alt text which is great!)
![image](https://user-images.githubusercontent.com/94856753/163869454-088064f3-37c4-4658-ae9a-fd367fc28ae6.png)

**Comment by jimuhh** [comment]
I took out the little icon. Confluence doesn't let me edit the HTML so I can make it display right. So out it goes.

**Comment by chaseakirby** [comment]
Thanks Jim! We can check it out tomorrow when the next Platform Website update happens and then close it out.

**Comment by shiragoodman** [comment]
@jimuhh @chaseakirby so the page looks right on Confluence, but on Platform Website it's not looking so nice. I have contacted Platform Content team via the #platform-confluence channel (https://dsva.slack.com/archives/C01AS05BQ79/p1650634492128089) - hopefully they can help us out!

**Comment by jimuhh** [comment]
@shiragoodman I'll revisit the confluence page and see if changing the way video is embedded would change anything.
