### ISSUE TITLE
Update documentation: Form controls - Text inputs

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39929]
## Issue Description
Make updates to Form Controls on on design.va.gov and Storybook to fix the discrepancies that have been identified. 

Discrepancies
Text inputs
-There is no "Text area" component (Non-Web component example in design.va.gov and Storybook) in Sketch.
-There is no "Success" state in design.va.gov or Storybook (green border on input field). This example only lives in Sketch.
-No "Required" example of text input in design.va.gov but it exists in Storybook.

---
## Tasks
- [ ] Add Text area to Sketch library
- [ ] Add Success state of the text input to design.va.gov  https://design.va.gov/components/form-controls#text-inputs
- [ ] Add Success state of the text input to Storybook https://design.va.gov/storybook/?path=/docs/components-va-text-input--default

- [ ] Add View guidance for the Text Input component in the Design System below label for va-text-input in Storybook  that links back to Text Input on design.va.gov   https://design.va.gov/components/form-controls#text-inputs  (See example on va-modal)
- [ ] Update link to Storybook on design.va.gov to "View va-text-input in Storybook"

##### Storybook
- [x] Add subtitle `Text Input web component` for `va-text-input`
- [x] Add `View guidance for the Text Input component in the Design System` link with an url value of `https://design.va.gov/components/form-controls#text-inputs`
- [x] Add success state example in `va-text-input` story

##### design.va.gov
- [x] Update Storybook preview link text to `View va-text-input in Storybook`
- [x] Add success state Storybook preview

##### Sketch
- [x] Sketch library has Text area mock up for Text inputs

 
---

**Comment by andresriveratoro** [comment]
Do we want to add an error state text input on design.va.gov as well?

**Comment by andresriveratoro** [comment]
Do we want to add a required example on design.va.gov?

**Comment by pdavies88** [comment]
@andresriveratoro so I merged in your work this morning because I was trying to get Number Input set up and some of the Text Input code overlapped. So we'd need to open up a new PR for the answers to your questions, my bad on that. @caw310 any thoughts on adding additional [examples](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default) to design.va.gov for the Text Input component?

Also for the `status` prop on `va-text-input` do we know if we would ever have any other statuses besides success? If not I am think we may want to update from a string to a boolean. We also forgot to add status to `defaultArgs` in Storybook. Once again my bad on not catching that prior to merging, it isn't effecting anything but we should fix it.

**Comment by andresriveratoro** [comment]
@pdavies88 I've made these changes [here](https://github.com/department-of-veterans-affairs/component-library/pull/393). Thanks for the suggestions!
