### ISSUE TITLE
Create pipe delimited CSV version of FSR payload

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#39931]
## Issue Description
VHA handles data in a CSV format. As their infrastructure is not build to handle JSON API requests we will be sending them CSV versions of the FSR requests. Need to create a sample version to pass to them to see what data may look like.

---
## Tasks
- [ ] Create at least one sample CSV file with pipe delimitation separators of the FSR data 

## Acceptance Criteria
- [ ] VHA has received a workable version of FSR CSV data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
