### ISSUE TITLE
[FE] My VA - Payment Info: triage/fix GA issue with view payment history CTAs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#39945]
## Background
From Slack:  need to determine whether we are correctly tracking clicks of the new view payment history CTAs in Google Analytics. Right now, I am seeing link clicks in GA for the debt CTAs come through (both when it shows in the "notification" style and in the link list -- screenshots included)(1) and for the the direct deposit CTA (screenshot included)(2), but I am not seeing link clicks for either the payment link that's part of the "We deposited X into your account..." block or when "view payment history" appears in the link list (if no payments).

**CTA's that need to be investigated as they appear on the frontend:**
- ![image (20)](https://user-images.githubusercontent.com/45603961/163239083-00e9169a-5b50-413b-8161-3af6fbbd9550.png)

- ![image (21)](https://user-images.githubusercontent.com/45603961/163239082-042285f6-ca13-4a5e-af20-60e1878a457e.png)

### Screenshots as referenced above
1. ![image (18)](https://user-images.githubusercontent.com/45603961/163238140-ad5ef067-5e05-4b07-86dc-36c94ce9b618.png)
 
2. ![image (19)](https://user-images.githubusercontent.com/45603961/163238230-1c3aeb16-53ff-484c-9fda-397504be4da1.png)

## Tasks
- [ ] Investigate GA configurations to determine if something isn't working properly
- [ ] Pull-in analytics team if needed (ping AJ to create a request in the platform support channel) 
- [ ] Implement appropriate fix as needed

## Acceptance Criteria
- GA for view payment history CTAs are working properly

**Comment by Samara-Strauss** [comment]
Looks like the issue with "View your payment history" is fixed! This just started to come through in analytics. 

![image](https://user-images.githubusercontent.com/34068740/163854692-96afc511-842c-43c5-934c-4478ffa5b157.png)
