### ISSUE TITLE
[Terraform/AWS][Tech debt] Github Action Runners contain lifecycle ignore

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#39949]
## Description

Recently, I tried to update the `instance_type` for `vets-website` Github Runners and did not have initial success. Upon looking into it with John, we discovered that we are [ignoring changes to instance_type](https://github.com/department-of-veterans-affairs/devops/blob/4ae0f40f115d87e2587dad033b9e39b1d3a05ee3/terraform/environments/dsva-vagov-utility/gha-runners.tf#L151) along with a few other things in terraform.

This may be an intended purpose and if so, we may want to document/comment it's reference somewhere (presumably in the file)

## Background/context 
https://github.com/department-of-veterans-affairs/devops/pull/11056
[Slack](https://dsva.slack.com/archives/CTYQL39FE/p1649797027864919)

## Technical notes
It may be working as intended, but for all intent and purpose, perhaps documentation/comment above line references should be provded

---
## Tasks
- [x] Discover if `ignore_changes` is intended or if we can improve upon it
- [x] Ensure terraform has not drifted
  - [x] If AMI is up to date

## Acceptance Criteria 
- [ ] Code changes (if applicable)
- [ ] Documentation

**Comment by oseasmoran73** [comment]
Given that there are moving pieces, the setup is correct the way it is. Closing
