### ISSUE TITLE
Update documentation: Form controls: Select Box

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39957]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Sketch Library
The Select box is called Dropdown in the Sketch Library, and nowhere else. Also, the Sketch symbol needs to be updated to show the focus halo when the menu is open (to match behavior of coded component).

---
## Tasks
- [ ] Update Sketch file - change Dropdown to Select box
- [ ] Add (Select box web component) to the label for va-select in Storybook 
- [ ] Add link in Storybook back to Select box on design.va.gov  https://design.va.gov/components/form-controls#select-box 
- [ ] Update link to Storybook for Select box on design.va.gov to "View va-select in Storybook"
- [ ] Add the notations in Storybook for the Props and Events on our Components also on design.va.gov for Select box 

## Acceptance Criteria
- [ ] Sketch library name is Select box 
- [ ] va-select name in Storybook  includes (Select box web component)
- [ ] Storybook has link to Selectbox  on design.va.gov  https://design.va.gov/components/form-controls#select-box 
- [ ] Select box link to Storybook is labeled "View va-select in Storybook"
- [ ] Notations in Storybook for Props and Events are on the component page on design.va.gov for Select box. 

---
