### ISSUE TITLE
[Design] Create Lo-fi Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39956]
## User Story
As the VA, we would like to provide a supportive check-in and pre-check-in experience to those that may have PTSD, anxiety, and/or cognitive issues so that they can easily use the features.

## Description
We need wireframes to test our ideas for a better user experience.

## Tasks
- [ ] Create lo-fi wireframes 
- [ ] Schedule and conduct an accessibility review 
- [ ] Review wireframes with product/UX team
