### ISSUE TITLE
[MCP] Discovery - Facility name formatting

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#39954]
## Issue Description
Concerns have been raised that the facility in copay details is in all caps. Manually fomating on the front end probably isn't a great idea since there could be abbreviations and other naming obscurities. 

Helpful links from Scott:

> All medical center names should be pulled from the schema repo using its ID (i.e `657` for James A. Haley hospital). Here’s the [list](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/vaMedicalFacilities.json) of all medical centers and their correlating IDs
> [Here’s the piece of code](https://github.com/department-of-veterans-affairs/vets-website/blob/45b96f22ced21acb54cd4e97fa790700fe50be38/src/applications/medical-copays/components/Balances.jsx#L17-L19) where we’re actually setting what name to use on the card from it’s ID/`facilityNum`

> Seems like it’s possible that the `facilityNum` we’re receiving from VBS isn’t aligning with the actual facility ID in the schema, which would then fall back to the all caps version that we get from the VBS response. Hopefully that helps!

---
## Tasks
- [ ] Investigate if we can fetch the facility name where it may be formatted correctly. 

## Acceptance Criteria
- [ ] Find if there's a formatted data point we can retrieve from -OR- if there's an existing issue
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
https://dsva.slack.com/archives/CPE4AJ6Q0/p1649788971277139 Link to slack thread mentioned

**Comment by denisecoveyduc** [comment]
Changes to the facility names need to come from VBS where data is sourced not work for the team to do
