### ISSUE TITLE
Discuss updated Confluence formatting for product offerings and such

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#39953]
## Issue Description
Cast vision for how our site might differ and what it might contain.  What changes need to be made to allow for a clear display of our offerings?

---
## Tasks
- [x] Discuss concepts for workflow of site, along with content groups

## Acceptance Criteria
- [x] Group alignment on best approach
- [x] Major sections and subsections ready for site updating
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
