### ISSUE TITLE
Update documentation: Modal 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39968]
## Issue Description
Make updates to Modal on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

Update Modal documentation on design.va.gov to point to web component instead of React component.

Sketch symbols do not match the web components:
-Sketch informational is called Default on Storybook
-Info modal in Storybook has no equivalent in Sketch
-Continue modal in web components does not use green button
-No Success modal in Sketch
-No version without buttons in Sketch
-No version without title in Sketch

Sketch symbols should show example with focus on the "x" to close icon, which is the default state after the modal is opened.

---
## Tasks
- [x] Update link to Storybook to the web component version of Modal https://design.va.gov/storybook/?path=/docs/components-va-modal--default
- [x] Add (Modal web component) to the label for va-modal in Storybook 
- [x] Add link in Storybook back to Modal on design.va.gov  https://design.va.gov/components/modal
- [x] Update link to Storybook on design.va.gov to "View va-modal in Storybook"
- [x] Change informational modal name to Default in Sketch
- [x] Add Info modal to Sketch
- [x] Remove  green button from the Continue modal 
- [x] Add Success modal in Sketch
- [x] Add version without buttons in Sketch
- [x] Add version without title in Sketch

## Acceptance Criteria
- [x] va-modal  in Storybook  includes (Modal web component)
- [x] Storybook has link to Modal  on design.va.gov 
- [x] Modal link to Storybook is labeled "View va-modal in Storybook"
- [x] Sketch file updates have been made

**Comment by caw310** [comment]
Links have been updated. Only Sketch file updates are needed now.

**Comment by GnatalieH** [comment]
@caw310 I've updated all of the Sketch modal symbols.
