### ISSUE TITLE
Update documentation: Loading indicator

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39967]
## Issue Description
Make updates to Loading indictor on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

Discrepancies
- Missing documentation other than Storybook preview.

---
## Tasks
- [x] Draft or request documentation on guidance for using loading indicators
- [ ] Get sign off on guidance from Matt and Natalie or Carol
- [X] Add View guidance for the Loading Indicator component in the Design System below label for va-loading-indicator in Storybook (See example on va-modal) and to Loading indicator on design.va.gov  https://design.va.gov/components/loading-indicators 
- [X] Update link to Storybook on design.va.gov to "View va-loading-indicator in Storybook" 
- [ ] Write Accessibility Considerations for this component

## Acceptance Criteria
- [x] Loading indicator has guidance on how and when to use 
- [X] Storybook has link “View guidance for Loading Indicator component in the Design System” 
- [X] Storybook has link to Loading indicators on design.va.gov  
- [X] Loading indicators link to Storybook is labeled "View va-loading-indicators  in Storybook"
- [ ] Write Accessibility Considerations for this component

---

**Comment by caw310** [comment]
@GnatalieH , No Sketch update needed but please draft user guidance.

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is a link to the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/709) I made for this update.

**Comment by GnatalieH** [comment]
@humancompanion-usds [here is a link to the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/709) I made for this update.

**Comment by GnatalieH** [comment]
[Here is a link to the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/709) I made for this update.
