### ISSUE TITLE
Update documentation: Form controls: Checkboxes

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39962]
## Issue Description
Make updates to Form controls: Checkboxes on design.va.gov and Storybook and Sketch. 

Discrepancies
- There is no example of a single checkbox in design.va.gov, only a Checkbox group. Storybook has both.
- Storybook link points to the React version. 

---
## Tasks
- [x] Add a single checkbox as example to desing.va.gov  https://design.va.gov/components/form-controls#checkboxes
- [x] Add a single checkbox as an example to Storybook https://design.va.gov/storybook/?path=/docs/components-checkboxgroup--default
- [x] Add (Checkbox web component) to the label for va-checkbox in Storybook 
- [x] Add link in Storybook back to Checkbox on design.va.gov  https://design.va.gov/components/form-controls#checkboxes 
- [x] Update link to Storybook on design.va.gov to "View va-checkbox in Storybook"

## Acceptance Criteria
- [x] va-checkbox  in Storybook  includes (Checkbox web component)
- [x] Storybook has link to Checkbox  on design.va.gov  https://design.va.gov/components/form-controls#checkboxes 
- [x] Checkbox link to Storybook is labeled "View va-checkbox in Storybook"

---

**Comment by andresriveratoro** [comment]
What should the subtitle be for CheckboxGroup? `CheckboxGroup web component`?

**Comment by caw310** [comment]
Let's make it Checkbox Group web component. Thanks!
