### ISSUE TITLE
[FE] My VA - Payment info: remove 403 error msg when user has no payment history

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#39965]
## Background
We seem to be showing a 403 error when a user has no payment history. 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/45603961/166476968-4b496854-a8f5-4ede-a8e4-7a9a51bf8e92.png">

We shouldn't show anything when that's the case. 

It's possible we may not be able to tell the difference between an error appearing due to connection issues/failed call to the backend vs payment history not existing, and if that's the case we need to come up with a better way to handle this, post launch of the payment and debt feature.
 
## Tasks
- [x] Investigate 403 error to determine why it's showing
- [x] Make appropriate changes so that the error does not appear 

## Acceptance Criteria
- [x] 403 error does not appear when a user does not have payment history

**Comment by tmitchellgcio** [comment]
Once deployed to staging we can validate this using a LOA1 user or someone not in MPI

**Comment by ajakabcin** [comment]
Confirmed on staging with user 39 (who has never had payments made to them) that we are no longer showing the 403 error. The section does not appear at all:

![Screen Shot 2022-05-03 at 10 51 55 AM](https://user-images.githubusercontent.com/45603961/166477700-df463462-9fc7-40cd-96a9-dfd159726db3.png)

**Comment by ajakabcin** [comment]
This issue seems to still be occurring on staging and in prod with LOA3 users. Reopening this issue to continue investigation and work to resolve the issue. cc @tmitchellgcio

**Comment by ericasauv09** [comment]
Taylor will rollback this change which included a requirement for MFA and direct deposit eligibility in order to show the benefit, payment, and debt section.

**Comment by ajakabcin** [comment]
I think can close this again since we're addressing the MFA and DD eligibility check that we're removing in #42763
