### ISSUE TITLE
Modal web component: Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39972]
## Issue Description
Dependent on #35272

Announce the component in the #vfs-frontend and #vfs-engineers channels. Might be worth reaching out to the teams who work on the static page templates as well.

The Modal React component is used in many applications, we could reach out to the teams that manage them and encourage them to migrate.

We also need to add note about the component release to the [What's new?](https://design.va.gov/documentation/whats-new) page.

Sample announcement:

>:wave: The Design System has just published a new version of component-library which includes <va-additional-info>, as well as made it available in vets-website. The migration script is also capable of automatically migrating your directories to this new component.
Why does this matter to me
The new additional info Web Component has a number of  enhancements/fixes:
Keyboard control with space and "Enter" key
Design fix for the blue border when expanded
Improved colors for contrast & consistency
The web component is already loaded into the site, so removing your old AdditionalInfo imports will reduce application bundle size and improve performance.
How do I migrate
First, make sure your branch is using the latest master, and run yarn install.
We have a script that you can use to assist with this process. You pass it two arguments:
--directory - the directory you wish to migrate
--component - the name of the React component to find and transform into a web component
For example, to run this migration in the platform directory, you would run:
yarn migrate-component --dir src/platform --component AdditionalInfo

>---
>*NOTE:* One change with <va-additional-info> is that it no longer exposes onClick for an external analytics event. There is still an internal component-library-analytics event that gets fired which includes the action (expand/collapse) and the trigger text. Just be aware of this so that you don't lose any tracking data that may be used in your dashboards. Reach out to us if you have any questions/concerns about this.

---
## Tasks
- [ ] Craft announcement and post in #vfs-frontend and #vfs-engineers
- [ ] Reach out to frontend teams individually about migration
- [ ] Add note to What's new? page

## Acceptance Criteria
- [ ] Announcement has been posted in #vfs-frontend and #vfs-engineers
- [ ] Relevant teams have been notified about migration
- [ ] What's New? page has been updated

**Comment by andresriveratoro** [comment]
#### Draft
:wave:: The Design System has made the `va-modal` web component available in `vets-website`. We have included an ESLint rule to help with the migration.
:rotating_light: **Please be aware that `primaryButton` and `secondaryButton` props have changed and will need to be updated manually for any instances of Modal using these props.**
Please visit the [Design System Modal component page](https://design.va.gov/components/modal) to learn more about this web component.

**Comment by andresriveratoro** [comment]
Announcement will be made after this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20974) is merged. `va-modal` is already available, but Robin's fixes for the focus trap are in `v9.0.0`.

**Comment by pdavies88** [comment]
@andresriveratoro just merged in the PR

**Comment by andresriveratoro** [comment]
Thanks for the update @pdavies88
