### ISSUE TITLE
Move RFCs to Github PRs, rather than Github Discussions

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#39989]
## Issue Description
The platform has asked that RFCs be created as issues in github, rather than elsewhere (confluence, or GH Discussions)

---
## Tasks
- [x] Move the existing RFCs that have been created in https://github.com/department-of-veterans-affairs/va.gov-team/discussions to be issues instead.

## Acceptance Criteria
- [x] RFCs are moved to issues.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39990
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39991
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39992
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39993

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/39997
https://github.com/department-of-veterans-affairs/va.gov-team/pull/39998
https://github.com/department-of-veterans-affairs/va.gov-team/pull/39999
https://github.com/department-of-veterans-affairs/va.gov-team/pull/40000

**Comment by dginther** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/40000
