### ISSUE TITLE
Add maturity scale to the design system and label each component

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#39995]
## Issue Description
This issue tracks adding and applying a maturity scale to the design system. The maturity scale defines the status or state that a component or pattern can be in and how it moves from status to status, or up and down the scale. The status is then applied to each component or pattern so it can reflect that status to the users of the design system. Our hypothesis is that provided a status or state for each component or pattern will address the following problems in the Experimental process:

1. No defined Life Cycle for a component or pattern
2. No clear path for “graduation” for a component or pattern from Experimental to Approved for use
3. Difficult for users of the system to know if they can and should use a component or pattern

---
## Tasks
- [x] Define a draft of the maturity scale and lifecycle (how a component or pattern moves up or down the maturity scale
- [x] Present maturity scale and lifecycle to Design System Council and collect feedback
- [x] Iterate on the maturity scale and lifecycle
- [x] Add a page in About (was Documentation) for the Maturity Scale detailing the scale and lifecycle
- [x] Link the Maturity Scale page to the Contribution page
- [x] Label each component and pattern on their respective pages and in the side navigation
- [x] Deprecate Wizard pattern and point to patterns that are coming soon
- [x] Add links from Component to github, research, sketch library
- [x] Test changes with designers week of April 25th

## Acceptance Criteria
- [ ] Verify there is a page that details the maturity scale and lifecycle
- [ ] Verify that each component and pattern has a visual and text indicator of where they are in the scale which links to the aforementioned documentation page
- [ ] Verify that the maturity scale and Contribution page link to one another

**Comment by humancompanion-usds** [comment]
Gah - Liz pointed out to me that the white on orange doesn't pass contrast. Need to change the text to black for the Use with caution or pick a darker orange. Also going to pick a darker red that passes at the AAA level.
