### ISSUE TITLE
Disable issue tracker for non va.gov-team repos

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#40004]
## AC
- Issue tracker disabled
- README should have link to an issue template

 - [ ] https://github.com/department-of-veterans-affairs/vets-website/
 - [ ] https://github.com/department-of-veterans-affairs/vets-api
 - [ ] https://github.com/department-of-veterans-affairs/vets-json-schema
 - [ ] https://github.com/department-of-veterans-affairs/content-build

**Comment by andreahewitt-odd** [comment]
Duplicate of the repo guidance ticket because once that is implemented folks will know where to put in tickets for that repo
