### ISSUE TITLE
Collaboration Cycle - Refine operational guidance and clarify VFS expectations for Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40002]
## Problem Statement 
VFS teams can sometimes struggle to know what is expected of them at a Staging Review. They have trouble coming to the touchpoint with the appropriate artifacts, and don't always know how to approach the Staging Review when also in the middle of their research initiatives. VFS teams also do not know what to expect from Governance team re: feedback or what the scope or boundaries of our review are. VFS teams also may not know what to expect from the Staging Review meeting itself.

Each Governance team practice area (design, accessibility, content, IA, and research) has their own process and resources for reviewing the materials provided at a Staging Review. However, there is not documentation to guide us internally/operationally. The documentation that does exist is generic for all practice areas. This can be challenging for new people joining the team, especially when there is no shadowing with the departing team member. The lack of practice area specific guidance has exposed gaps in our review process.

How might we improve VFS-facing guidance so that VFS teams are better prepared for Staging Review?
How might we provide clear, direct guidance to our team members for the Staging Review so that our process is seamless, repeatable and consistent?

## Hypothesis or Bet

- If we clarify our expectations for Staging Review, then VFS teams will be better prepared for the meeting.
- If we clarify our expectations for Staging Review, then VFS teams will have less documented issues at Staging Review.
- If we clarify our expectations for Staging Review, then we'll have less postponed/delayed reviews.
- If we refine our operational guidance for Staging Review, then Governance team members will take a consistent approach with each product at each Staging Review.
- If we write specific guidance for each practice area for the Staging Review, then we will address the gaps that occur in reviews now.
- If we expand our practice area-specific guidance for Staging Review, then we can onboard new employees faster and more efficiently.
- If we refine our operational guidance, then VFS teams can expect to receive more thorough feedback at the Staging Review.

## Prioritized Problem Statements from discovery
Problems prioritized per [MURAL board workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=6550e74b-489e-417b-8fb2-cad201c4eab9)
<img width="760" alt="image" src="https://user-images.githubusercontent.com/71330581/186935877-2ffbef0f-3c1f-4dbf-a53e-66893608269f.png">

1. **B** - I am a Governance team member supporting the Collaboration Cycle trying to complete consistent Staging Reviews for VFS teams but I approach each review differently because there is no standardized guidance specific to my practice area.
- **Complete.** Resolved with tickets #45135, #45136, #45137, #45138, #45839, and #46351
2. **C** - I am a Governance team member supporting the Collaboration Cycle trying to access the VFS teams' pre-production product in order to complete my Staging Review but I don't know the barriers and/or steps to take to access the various pre-production environments because there is no documented guidance for accessing said environments.
- **Complete.** Resolved with tickets #39530 and #46814
3. **P** - I am a VFS team member trying to schedule my team's staging review but I sometimes forget to add a11y/product owners to the invite because I am unclear on who adds those specific people which makes me feel frustrated.
- **Complete.** Resolved with ticket #45754
4. **L1** - I am a Governance team member trying to present my findings at Staging Review but the VFS team has identified that the finding is either not in scope or not their problem because it's not part of the iteration or they are not the team accountable for addressing the issue which makes me feel frustrated and that I've burdened the VFS team.
**L2** - I am a Governance team member trying to document issues I am finding in the Staging Review but I am not sure what's in scope because the VFS team has shared the complete product without specified boundaries which makes me feel confused, unsure, and hesitant.
- **Complete.** Resolved with tickets #45755, #45757, and #46421
5. **M** - I am a Governance team member trying to review the latest artifacts but I am not sure what artifact to provide feedback on because the VFS team has shared extra artifacts which makes me feel confused and annoyed. 
- **Deprioritized.** As of 9/8, the team has decided at this time that Problem statement is not worth prioritization. We will come back to this at a later date.
6. **A** - I am a Governance team member supporting the Collaboration Cycle trying to complete my review of the VFS product but I don't have access to the necessary artifacts because VFS teams don't provide the information I need and/or don't validate access.
- **Complete.** Resolved with tickets #45796 and #46816 
7. **F** - I am a Governance team member supporting the Collaboration Cycle trying to ensure I complete all pre-review steps but sometimes I do not verify everything within a timely manner because I have a hectic schedule that is not well managed.
- **Deprioritized.**  As of 9/8, the team has decided that this problem statement is not worth prioritization. The effort to implement a solution outweighs the benefit. We will come back to this at a later date. 
8. **T** - I am a a VFS team member trying to prepare accessibility artifacts for Staging Review but am having difficulty providing testing artifacts because I do not understand what I need to provide for review which makes me feel unprepared and confused.
- **In Progress.** To be resolved with tickets #47400, #47915, and #47916 
9. **J1** - I am a VFS team member involved in the Collaboration Cycle trying to understand what's required of my team, but am not sure on the exact meanings and implications of the terms used because there is not enough clarification or consistency of usage which makes me feel at a disadvantage. 
**J2** - I am a new Governance team member involved in the Collaboration Cycle trying to understand how to evaluate and provide feedback on VFS team product designs, but am not sure if the vocabulary I've learned as an SME fits with the standard, expected usage for the new team I'm on. because there is no approved language list with definitions which makes me feel inept. 
**J3** - I am a VFS team member involved in the Collaboration Cycle trying to understand how feedback from Gov team relates to actions required from mine, but am not sure that what .they're saying is what I'm understanding because there is no standard for "this means this"  which makes me feel uncertain.
- **In Progress.** To be resolved with tickets #47475, #42147 and TBD.
10. **E** - I am a VFS Product Manager engaging in the Collaboration Cycle Staging Review trying to ensure I complete all necessary steps but sometimes I do not share everything within a timely manner because I likely have too much to do.
- **Deprioritized.** As of 9/22, team agrees that solutions implemented from earlier problem statements will help incentivize VFS teams to share artifacts in a timely manner. 
11. **I1** - I am a VFS team member engaging in the Collaboration Cycle Staging Review trying to prepare for potential feedback from Governance team but the VA.gov Experience Standards don't provide enough detail because the existing VA.gov Experience Standards list is an MVP which makes me feel unprepared, unsure, and anxious.
**I2** - I am a VFS team member involved in the Collaboration Cycle trying to prepare for Gov team feedback but am not sure on what standards the feedback relates to because there is not enough clarification or consistency of usage which makes me feel at a disadvantage.
- **Escalated.** As of 9/22, both I problem statements will be solved as part of a larger initiative, [VA.gov Experience Standards - Expand information available to VFS teams](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45160)
12. **D** - I am a Governance team member supporting the Collaboration Cycle trying to coordinate with my team prior to the Staging Review but conversations can sometimes happen in multiple channels and threads because there is no standardized process for where pre-Staging Review discussions occur.
- **Deprioritized.** As of 10/12, the team agrees that this problem is not worth prioritization at this time. 
13. **N1** - I am a Governance team member trying to verbalize feedback during touchpoints related to my practice area but am unable to provide such feedback because other practice areas take up the majority of the time which makes me feel like my feedback is not as important or impactful as others.
**N2** - I am a VFS Team Designer trying to walk the Gov team through a complex interaction on a redesigned or new website  but can't give more than the most basic overview because I have to allow Gov team SMEs time to ask questions and provide feedback which makes me feel stressed and poorly understood.
- **Escalated.** As of 9/22, Problem Statement  N1 and N2 are more prevalent to Design Intent and Midpoint Review,  not Staging Review, and will not be solved with this initiative. They will be address in initiatives [Collaboration Cycle - Refine operational guidance and clarify VFS expectations for Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39845) and [Collaboration Cycle - Refine operational guidance and clarify VFS expectations for Design Intent.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39744)
14. **G** - I am a Governance team member supporting the Collaboration Cycle trying to complete my review of the VFS product but sometimes I am not prepared for the time commitment because I was not informed of the large size of the final product.
- **Deprioritized.** As of 9/22, the Governance team has decided not to address this problem at this time due to challenges with consistent sizing from VFS teams and also concerns that we'd be over-solutioning the problem. We will put this as a ticket in our backlog and possibly readdress later on.
15. **H** - I am a Governance team member supporting the Collaboration Cycle trying to map identified issues within the VFS product to the VA.gov Experience Standards but sometimes I am not able to find an adequate match because the list of standards is incomplete and/or too niche.
- **Escalated.** As of 9/22, problem statement H will be solved as part of a larger initiative, [VA.gov Experience Standards - Expand information available to VFS teams](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45160)
16. **K1** - I am a Governance team member supporting the Collaboration Cycle trying to provide my feedback for Staging Reviews in the Drafting Template but because it is difficult to add screenshots after an issue is generated, I sometimes add them incorrectly, or I am unable to add them at all, which makes me feel inept, and unprepared.
**K2** - I am a Governance team member supporting the Collaboration Cycle trying to provide my feedback for Staging Reviews in the Drafting Template but it is easy to forget to complete all parts of the Drafting Template because there is a lot going on in the Drafting Template and it can be hard to navigate which makes me feel embarrassed and frustrated.
**K3** - I am a Governance team member involved in the Collaboration Cycle trying to enter my feedback at a staging review but it is hard to read/enter feedback because the layout of the column is narrow and does not have a lot of white space which makes me feel anxious I might miss something.
**K4** - I am a Governance Team member offering feedback for a Staging Review trying to fill out the Drafting Template but automations don't always work because they need to be fixed which makes me feel frustrated.
- **In Progress.** To be resolved with ticket #47417.
17. **Q** - I am an accessibility specialist on the Governance team trying to complete a Staging Review but I am unsure how thoroughly it's already been reviewed for accessibility because it's unclear who has completed reviews prior to Staging and what kind of accessibility knowledge they have which makes me feel like I might be duplicating effort.
- **In Progress.** To be resolved with tickets #47400, #47915, and #47916 
18. **O** - I am a Governance team member trying to verbalize feedback during touchpoints related to my practice area but am reluctant to provide such feedback at times because some VFS Team members question the validity of my FB if the issues I found were not "approved" by Sitewide Content, which makes me feel angry, resentful and sad.
- **Deprioritized.** As of 10/6, the team decided that this is not a problem worth prioritizing. The relationship with Sitewide Content has changed since this problem was identified and no action is needed at this time. 
19. **R** - I am a Governance Team member reviewing artifacts for Staging Review trying to figure out what artifacts I should be looking at and why but I'm not sure what to do with the Release Plan because there are no instructions for what to do with it which makes me feel uncertain and lost.
- **In Progress.** To be resolved with ticket #47917.
20. **S** - I am a Governance team member trying to attend a staging review but I am unable to access the Zoom meeting because the team member that scheduled the meeting is absent which makes me feel confused and unprepared.
- **Deprioritized.** As of 10/6, the team decided that this problem happens so infrequently that the time and effort it would take to introduce and uphold a solution would not be time well spent. The team has decided not to move forward with this problem statement.

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

- [ ] We have determined how each practice area handles each requested/provided artifact at Staging Review
- [ ] We have updated the Staging Review touchpoint page on Platform Website with clarified expectations
- [ ] We have refined our operational guidance  so each practice area has their own unique process to follow for Staging Review.

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
September 30, 2022

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by shiragoodman** [comment]
Other info to capture:

- TUD
- staging environment vs. CMS Preview vs. Review instance vs. feature flag

**Comment by shiragoodman** [comment]
This initiative is complete as of 12/6/2022.
