### ISSUE TITLE
Build sorting functionality for A/B test on Rated Disabilities

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40018]
# Background
For some time now there has been desire to have the ability to A/B test features or tweaks on VA.gov but no defined system for running these tests is in place. We want to set that system up. We already have set up Google Optimize to track the test as well as a feature toggle so that we can build the feature for our first A/B test on Rated Disabilities in production. Now we need to set up the code to test a feature on Rated Disabilities, this is so that we can run a live test and make sure all the pieces work.

The test we will be running is to allow users to sort the table of rated disabilities by rating or by effective date. This sort will be done by a select box above the list with the word "sort" next to it. As this test is only intended as a pilot test we do not require a design for this.

[documentation on feature toggles](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## Considerations
Sorting should be by:
* Disability Rating ASC
* Disability Rating DESC
* Effective Date ASC
* Effective Date DESC

## Tasks
- [x] Pull rated_disabilities_sort_ab_test feature toggle into Rated Disabilities page
- [x] Add sort select box at top of rated disabilities behind feature toggle
- [x] Add functions to sort data
- [x] Submit PR for review

## Acceptance criteria
- [x] Sort functionality has been added behind a feature toggle on Rated Disabilities
- [x] A PR has been submitted for review

**Comment by cohnjesse** [comment]
@saderagsdale Here is the first ticket we will be picking up for the AB testing stuff.
