### ISSUE TITLE
Implement and Test "Forms API" Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40019]
## Issue Description
An API request to `dev-api.va.gov/v0/forms` first hits the vets-api before being forwarded to the `dev-api.va.gov/services/va_forms/v0/` route in Lighthouse. 

The goal of this ticket is to change the setting that the Form API code uses from `dev-api.va.gov` to the forward proxy URL instead. This would, in effect, side step the Kong API gateway and be a more direct route to the source of the data in Lighthouse.

---
## Tasks
- [ ] Change `Settings.forms.url` to point to fwd proxy
- [ ] Test that calling the the original vets-api endpoint `dev-api.va.gov/v0/forms` returns the same data before and after the configuration change

## Acceptance Criteria
- [ ] Settings to LH API route changed to point to fwd proxy instead
- [ ] Return data from the API call did not change as a result of this configuration change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
Upon closer inspection, this API route is _not_ one of those instances in which `vets-api` makes an external client request to Lighthouse. Even though `vets-api`'s route `/v0/forms` does make a client request to `/services/va_forms/v0/forms`, Kong actually redirects this request back to `vets-api` itself. This is an example of a Lighthouse API route being implemented in `vets-api`.
