### ISSUE TITLE
Implement and Test "Address Validation API" Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40021]
## Issue Description
An API request to `dev-api.va.gov/v0/profile/address_validation` first hits the vets-api before being forwarded to the `dev-api.va.gov/services/address_validation/v2/candidate` route in Lighthouse. 

We need to change the setting that the Address Validation code uses from `dev-api.va.gov` to the forward proxy URL instead. This request will be routed like so:

```
vets-api --> fwdproxy:4492 --> Kong --> fwdproxy:4441 --> Lighthouse
```

On the `vets-api` side, the endpoint is authenticated, while on the Lighthouse side, it's an internal API endpoint and not authenticated. As such, the synthetic DD test will test the fwdproxy URL to sidestep the authentication requirement.

:warning: **Complication**:
The setting in vets-api does _not_ include the protocol (`http` vs. `https`). The protocol is hard-coded in the codebase to `https`. In order to be able to use the `http` protocol in DEV, we would need to change the codebase to remove the hard-coded protocol and add it to the settings in _all_ environments.

---
## Tasks
- [x] Create synthetic DD test to validate fwdproxy request URL 
- [ ] Add new API key for DEV environment
- [ ] Change `Settings.va_profile.address_validation.hostname` to point to fwdproxy at port 4492
- [x] Devise manual test to ensure the new vets-api setting works as expected

## Acceptance Criteria
- [ ] Settings to LH API route changed to point to fwd proxy instead
- [ ] Synthetic and manual tests confirm that the change was successful
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Closing as duplicate of #44624.
