### ISSUE TITLE
Implement and Test "PGD (Patient Generated Data) API" Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40024]
## Issue Description
Some API request to vets-api are being forwarded to `dev-api.va.gov/services//pgd/v0/r4` routes (undocumented?) in Lighthouse. 

The goal of this ticket is to find documentation on the PGD LH API, identify which vets-api routes make use of the PGD LH API, and change all the settings that the vets-api code uses from `dev-api.va.gov` to the forward proxy URL instead. This would, in effect, side step the Kong API gateway and be a more direct route to the source of the data in Lighthouse.

---
## Tasks
- [ ] Change `Settings.hqva_mobile.lighthouse.url` to point to fwd proxy (:warning: this is also used in other contexts)
- [ ] Find out which API endpoint(s) in vets-api forwards requests to the `/pgd` endpoint in LH
- [ ] Figure out authentication requirements for requests
- [ ] Check each of the original vets-api endpoints and make sure they return the same response before and after the configuration change

## Acceptance Criteria
- [ ] Settings to LH API route changed to point to fwd proxy instead
- [ ] Test suite confirms that data from the API call did not change as a result of this configuration change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Closing as duplicate of #44660.
