### ISSUE TITLE
Implement and Test "Facilities API" Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40020]
## Issue Description
An API request to `dev-api.va.gov/facilities_api/v1/va` first hits the vets-api before being forwarded to the `dev-api.va.gov/services/va_facilities/v0/facilities/all` route in Lighthouse. 

The goal of this ticket is to change the setting that the Facilities API code uses from `dev-api.va.gov` to the forward proxy URL instead. This would, in effect, side step the Kong API gateway and be a more direct route to the source of the data in Lighthouse.

---
## Tasks
- [x] Change `Settings.lighthouse.facilities.url` to point to fwd proxy
- [x] Test that calling the the original vets-api endpoint `dev-api.va.gov/facilities_api/v1/va` returns the same data before and after the configuration change

## Acceptance Criteria
- [x] Settings to LH API route changed to point to fwd proxy instead
- [x] Return data from the API call did not change as a result of this configuration change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
