### ISSUE TITLE
Launch Collaboration Cycle Request ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40028]
## User Story
As a Governance team member, I want to be sure that VFS teams are informed of the changes in the Collaboration Cycle so that the transition to the new core template is seamless.

As a VFS team member, I want to be made aware of the changes to the Collaboration Cycle so that I can be prepared for any changes in engagement/intake.

- Intended Audience: VFS teams
- Desired Outcome: Changes to the Collaboration cycle re: the new core github ticket have been launched and announced to vfs teams per the Platform Communication playbook guidelines.
- Due Date: 

## Description
We have created a new core github ticket for tracking collaboration cycle touchpoints and managing requests. We have completed research with VFS teams using this template. We have made changes to the template per research findings. We have updated our operational guidance for the Governance team to reflect changes in the process. We have updated VFS facing guidance to reflect changes in the process. Now we must announce the changes to VFS teams per the Platform Communication playbook guidelines.

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Artifacts Needing Updates
- [Platform Website: Change History page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)

## Tasks
- [x] Create draft version of [Change History page ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2203058191/Shira+-+Change+history)
- [x] Send to @mchelen-gov for review and feedback
- [x] Make modifications as requested
- [x] Hold final walkthrough of full Collaboration Cycle ticket process
   - Meeting scheduled 5/23 at 2:00pm ET
- [x] Go/No Go held at Platform Office Hours on 5/24

## Acceptance Criteria
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled
- [x] Change history log post has been created and approved by @mchelen-gov 
- [x] OCTO-DE Platform leadership approval at Go/No Go meeting
- [x] All changes per tickets #41201, #41209, #41211, #41466 and #40040 have been published in production
- [x] Announcement has been posted on #vfs-all-teams per Platform Communication playbook guidelines
- [x] Announcement has been shared at Team of Teams meeting
- [x] Announcement has been posted in the [VA.gov-team announcements as new discussion](https://github.com/department-of-veterans-affairs/va.gov-team/discussions/categories/announcements)

### Github tickets
- [x] [Collaboration Cycle Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) - new
- [x] [Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+design-intent%2C+governance-team&template=design-intent-collaboration.md&title=Design+intent+%5BTeam+Name+-+Feature+Name%5D) - added deprecation message
- [x] [Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team%2C+midpoint-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D) - added deprecation message
- [x] [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team%2C+staging-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) - added deprecation message
- [x] Collaboration Cycle Kickoff - retried
- [x] [Collaboration Cycle Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)  - minor modifications

### Platform Website/Collaboration Cycle pages
- [x] [Collaboration Cycle Kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Collaboration-Cycle-Kickoff.1760493650.html)
- [x] [Collaboration Cycle Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [x] [Design Intent touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
- [x] [Midpoint Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
- [x] [Staging Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [x] [Resources ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Resources.1764491265.html)
- [x] [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html)

### Miscellaneous
- [x] ZenHub Board 
---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby i just created this ticket. Can you please refine?
