### ISSUE TITLE
Implement and Test "Decision Review API" Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40022]
## Issue Description
An API request to `dev-api.va.gov/v0/higher_level_reviews` and `dev-api.va.gov/v0/notice_of_disagreements` first hits the vets-api before being forwarded to `dev-api.va.gov/services/appeals/v2/decision_reviews/*` routes in Lighthouse. 

The goal of this ticket is to change all the settings that the Decision Review API code uses from `dev-api.va.gov` to the forward proxy URL instead. This would, in effect, side step the Kong API gateway and be a more direct route to the source of the data in Lighthouse.

---
## Tasks
- [ ] Change `Settings.decision_review.url`, and `Settings.decision_review.v1.url` to point to fwd proxy
- [ ] Collect full list of vets-api endpoints that fall under the category of "Decision Reviews"
- [ ] Figure out authentication requirements for requests
- [ ] Check each of the original vets-api endpoints and make sure they return the same response before and after the configuration change

## Acceptance Criteria
- [ ] Settings to LH API route changed to point to fwd proxy instead
- [ ] Test suite confirms that data from the API call did not change as a result of this configuration change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Closing as duplicate of #44622.
