### ISSUE TITLE
[508] Burials: a11y fixes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40029]
## Description

The [burials app](https://staging.va.gov/burials-and-memorials/application/530/introduction) needs an a11y review to ensure it passes a11y tests. I noticed incorrect header levels on the introduction page, there are probably more issues within the flow

## Tasks

- [ ] Run Axe within the Burials form flow
- [ ] Document & fix all a11y issues
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
cc: @saderagsdale
