### ISSUE TITLE
[FE] [BUG] Appointment start time interpreted as UTC in < es6 browsers

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#40027]
## Dependency
Waiting on CHIP to complete some work

## User Story

As a Veteran, I wish to see the correct appointment time in PCI & CI, so that I am confident that my check-in was completed correctly.

## Description

A veteran with a 10:30 (CDT) appointment saw the appointment displayed to them as starting at 05:30.

https://dsva.slack.com/archives/C02UP02HHGX/p1649959142167269

## To Reproduce

View check-in in Safari version 9. Appointment times will be shown as if they were converted from UTC to the station's timezone.

## Implementation

See this [stackoverflow post](https://stackoverflow.com/questions/29174810/javascript-date-timezone-issue) for more background and some ideas on resolutions.

Hopefully we can use date-fns to proscriptively interpret the date as we wish in all situations.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Date-fns is used to interpret all dates in CI & PCI
- [ ] Appointment date times are shown correctly in Safari version 9
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
I don't think this can get fixed with confidence until we get station TZ. Blocking on this issue: https://github.com/department-of-veterans-affairs/chip/issues/399
