### ISSUE TITLE
Implement and Test "Appeals Status" API Route Change to Forward Proxy in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#40023]
## Issue Description
An API request to `dev-api.va.gov/v0/appeals` (?) first hits the vets-api before being forwarded to `dev-api.va.gov/services/appeals/v0/appeals*` routes in Lighthouse. 

The goal of this ticket is to change all the settings that the Appeals Status API code uses from `dev-api.va.gov` to the forward proxy URL instead. This would, in effect, side step the Kong API gateway and be a more direct route to the source of the data in Lighthouse.

---
## Tasks
- [ ] Change `Settings.virtual_agent.lighthouse_api_uri` to point to fwd proxy
- [x] Find out which API endpoint in vets-api forwards requests to the appeals status endpoint in LH
- [x] Figure out authentication requirements for requests (LH API call needs `X-VA-SSN` header and `X-VA-User` header)
- [ ] Check each of the original vets-api endpoints and make sure they return the same response before and after the configuration change

## Acceptance Criteria
- [ ] Settings to LH API route changed to point to fwd proxy instead
- [ ] Test suite confirms that data from the API call did not change as a result of this configuration change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
@madebydna Please review before closing.

**Comment by alwerner** [comment]
@madebydna Please review before closing.

**Comment by madebydna** [comment]
The identified setting - `Settings.virtual_agent.lighthouse_api_uri` - no longer exists.
