### ISSUE TITLE
Set up claims & appeals apps for isolated builds

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40030]
## Description

Set up all claims & appeals apps to perform an [isolated application build](https://depo-platform-documentation.scrollhelp.site/developer-docs/Isolated-Application-Builds.2139062326.html) by verifying and adding the app to the allow-list. This will speed up the CI workflow.

## Tasks

- [ ] Set up NOD
- [ ] Set up HLR
- [ ] Set up 526
- [ ] Set up CST
- [ ] Set up Letters
- [ ] Set up Pre-need
- [ ] Set up Burials
- [ ] Verify all apps build in isolation

## Definition of done

- [ ] All tasks complete
- [ ] All test passing
