### ISSUE TITLE
Add field validation to Product CSV

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#40038]
## Issue Description
Currently, there's no field validation for the product `csv` file, so someone can enter incorrect values which can break the ingestion of the `csv` file into BigQuery.

Add field validation to the `csv` file.

---
## Tasks
- [x] Create a GitHub Actions job that runs on each `push` event that evaluates each field in the `csv` file of the current branch. The job will pass if there are no validation errors and will fail if there are validation errors. If there are validation errors, merging will be blocked and a detailed log of the errors will be generated.

## Acceptance Criteria
- [x] Validations for each field successfully catch each incorrect values entered in the `csv`

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/product-directory/pull/5

95% done not including writing tests.

To-do:
- [ ] Finish validation for the different string fields (maybe pair with @CBonade on this to knock it out quickly--I'm guessing he's way more familiar with the expected values for each string type)
- [ ] Write tests

**Comment by holdenhinkle** [comment]
This is done - https://github.com/department-of-veterans-affairs/product-directory/pull/5

**Comment by holdenhinkle** [comment]
Today I wrote validations and tests for the following string field types:

Validates the following fields specifically:
- Path
  - Examples: `src/applications/appeals/10182`
- Root URL
  - Examples: `www.va.gov/decsion-reviews`, `notifications.va.gov`
- Launch Date
  - Examples: `May 2018`, `3/28/2018`, `8/1/2018`, `2018`, `11/2021`

Curt reviewed it and it's good to go. I just need to update the Dashboard Data Repo so it checks-out the correct csv (the product directory csv path has changed). That should just take a minute.

**Comment by pjhill** [comment]
Looks good, thanks for the demo!
