### ISSUE TITLE
Design - Personal Info Revision - Update Sketch File - "Learn More" UI

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40035]
### Background

As we begin to incorporate the new web UI component instead of react, the UI for the "learn more" links are slightly different (see examples below).
This new look should be added to our sketch file as part of our documentation for the design we will use going forward.

(Insert screenshots here)

### Tasks

- [x] Using an example screen, note the differences between the react UI and the web component UI (ie: grey vs green carats)
- [x] Update Sketch file

### Acceptance Criteria

- [x] Sketch file is updated.

**Comment by SKasimow** [comment]
@cgednalske - lmk if this looks ok. I was getting an error message in staging so will try to insert screenshots tomorrow.

**Comment by cgednalske** [comment]
@SKasimow - looks good to me! Thank you!

**Comment by cgednalske** [comment]
I've updated all Profile pages with the newest additional info component (except for Direct Deposit, which Liz is doing):  

[Personal information](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
[Contact information](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655)
[Military information](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775)
Direct deposit information (Liz is working on this)
Notification settings (no updates needed)
Account security (no updates needed)
[Connected apps](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e)

**Comment by SKasimow** [comment]
@cgednalske can we close out?

**Comment by cgednalske** [comment]
@SKasimow yep! Good to go!
