### ISSUE TITLE
Add Collaboration Cycle Zenhub board to operational and VFS-facing guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40040]
## User Story
As a VFS team member, I want to be aware of the Collaboration Cycle Zenhub board so that I can easily see where my products are in their Collab Cycle journey.

As a Governance team members, I need to know how I should moved tickets through the Collab Cycle Zenhub board so that they are accurately represented.

As an OCTO-DE team member, I want to know how to use and understand the Collab Cycle Zenhub board so that I can see where all VFS products are in their Collab Cycle journey.

- Intended Audience: VFS, Governance team, OCTO-DE
- Desired Outcome: Collab Cycle Zenhub board is visible to VFS and OCTO and they understand the various pipelines. Governance team knows how to move tickets through the Zenhub board.
- Due Date: 5/24/2022

## Description
The Collaboration Cycle Zenhub board is a new feature introduced alongside the core collab cycle ticket. This board allows VFS teams to see where they are in their CC journey, and it allows Governance team, OCTO and others to see what products are currently engaged with the Collaboration Cycle and the current status. The board will also help Governance team know how many reviews can be expected at any point in time. 

Since the board will be managed by Governance team, it is important that the operational guidance is updated to reflect when and how tickets should move from one pipeline to another.

**Note: These changes will be published in ticket #40028.** 

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## New Artifacts 
N/A

## Artifacts Potentially Needing Updates
Collab Cycle Kickoff - moderator responsibilities (updated in ticket #41201)
Design Intent - moderator responsibilities (updated in ticket #41209)
Midpoint Review - - moderator responsibilities (updated in ticket #41211)
Staging Review - - moderator responsibilities ((updated in ticket #41466)
[Collaboration Cycle/Resources page on Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Resources.1764491265.html)

## Tasks
- [x] Create draft version of [Collaboration Cycle/Resources page ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2203058177/Shira+-+Resources)
- [x] Modify language for Platform Collaboration Point Tracker to reflect change in purpose
- [x] Add brief description of how the ZenHub board works
- [x] Add definitions of each pipeline in the Collaboration Cycle Reviews ZenHub board
- [x] Remove dummy tickets from Usability Testing research from ZenHub board (@chaseakirby)

## Acceptance Criteria
- [x] VFS teams are aware of the new Collaboration Cycle zenhub board and know how to interpret it
- [x] Governance team members know how to move Collab Cycle tickets through the various pipelines of the Collaboration Cycle Zenhub board
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket
