### ISSUE TITLE
Update Platform links to the newly renamed Research Review page

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40053]
## User Story
As a VSP team member, I want to ensure that broken links are updated so that information can be found.

As a VFS team member, I want all links to work so that I can find information

- Intended Audience: VFS and VSP team members
- Desired Outcome: fix broken links to the [Platform page: Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-review.1781891143.html) within the Collaboration Cycle, Getting Started, or Research and Design sections of Platform Website.
- Due Date: N/A

## Description
After updating the [Platform page: Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-review.1781891143.html), it appears that some links to this page elsewhere on Platform have been broken. We'll want to sweep Platform for these dead links and repair.

## Artifacts Needing Updates
[Platform Website: CC Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) 

## Tasks
- [ ] Look for other broken links to the [Platform page: Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-review.1781891143.html)
- [ ] Repair any broken links
- [ ] Update Design Intent link under "Define" phase to https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html

## Acceptance Criteria
- [ ] Offending Platform Website page links have been updated
- [ ] Links within Platform Website navigate within Platform Website or GitHub
  Note: Any pages navigating to Confluence without a Platform Website page should be noted and reviewed. 

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@naomimarcussen i'm trying to determine whether we can close this ticket. I don't think any of the links are broken still, but I do think that the [Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) page could benefit from some improvements. I'd also like to verify that the links are going to the correct  [Research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va) pages.

Could you take a look and let me know?

**Comment by naomimarcussen** [comment]
Hi! After looking further, I see that we need to implement anchor tags from within Confluence. Therefore everything linking to the [Research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va) just goes to the top, when it is intended to anchor to specific points on the page. I've updated the steps to include anchor tags. Once this is published, I'll update other links going to it.

**Comment by shiragoodman** [comment]
@naomimarcussen sounds good. Let's discuss at our next 1:1 bc I'm not quite sure I'm following with regards to your updates to the ticket.

**Comment by naomimarcussen** [comment]
We can close this ticket now. All links have been fixed and verified that they are going to the correct pages.

**Comment by shiragoodman** [comment]
thanks Naomi!
