### ISSUE TITLE
Create AWS IAM group for PST-CIT team

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#40062]
## Issue Description
PST-CIT team will need an AWS IAM group and associated policies to perform their work.

---
## Tasks
- [x] Edit Terraform in global env to add a group for PST-CIT
- [x] Edit Terraform in global env to add policies for PST-CIT
  - [x] Add Parameter Store paths that the team will need access to (vets-api, pst-cit, etc)
- [x] Once merged, work with Infra team to get TF applied

## Acceptance Criteria
- [ ] Group created in AWS IAM with associated policies
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
