### ISSUE TITLE
[FE] My VA - Health care update: Add new Roseburg health system as Cerner to My VA (June 2022)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#40065]
## Background 
For My VA, we need to add a Roseburg, Oregon health system as Cerner in June.  We will need to add this to the list of Cerner facilities IDs that we have, and update the copy of the Cerner Alert.  
**The facility ID  is 653**

> ID 653 - Roseburg: Go-live -- 6/11/2022 

## Tasks
- [ ] Add Facility in Cerner list on My VA
- [x] [Design] Confirm with content team what the copy should be 
- [ ] Update copy to include Roseburg (Oregon) VA health care system (Copy and logic may be revisited before this implementation - [Ticket department-of-veterans-affairs/va.gov-team#39030](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39030))
- [ ] [FE]  Coordinate with Adam so that he's able to make sure the timed release is functioning properly on the 11th

## Acceptance Criteria
- New Cerner facility is added to My VA Cerner alert.

**Comment by jilladams** [comment]
Apologies - incorrectly moved the issue to wrong repo. ID is updated now that it's back in va.gov-team.

**Comment by aagosto90** [comment]
Copy is updated in [this mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/nRE5MA4)

**Comment by ajakabcin** [comment]
This issue is on a timed release for 6/11 - waiting for validation until then.

**Comment by ajakabcin** [comment]
Confirmed on staging. For now the copy is going to include the word "or" between facility names. We'll update this with the next facility addition to use commas in between instead.
