### ISSUE TITLE
Q3 2022 IET -  [Sidekiq UI Service]: Drive to Production Environment

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#40061]
## Problem Statement
The Sidekiq UI admin tool is currently embedded as an endpoint on vets-api. IET has developed a microservice that hosts this tool in the development environment which can be found at http://sidekiq-ui-dev.vfs.va.gov/. Deploying this tool to higher environments (staging & production) is the next step in breaking it from vets-api and will help allow us to later deprecate /sidekiq endpoint in favor of using the microservice. This will be a learning process that will help us develop a Microservices Deploy Playbook that will provide a step-by-step guidance on how to break out a microservice from Vets-API and will be used to help other engineering teams including Console Services in breaking out microservices.

 
## Hypothesis or Bet
Driving Sidekiq UI to the Production environment is intended to create a pioneering model in breaking out services from Vets-API into microservices. This model should make it easier for other engineering and/or platform teams in breaking out microservices. Additionally, pulling backend tools such as Sidekiq UI from `vets-api` will simplify the code base and allow more granular access control by separating engineering concerns. 

## Definition of Done
- [ ] When the Sidekiq UI is successfully deployed in the Production environment as well as documented and where there are no significant issues. Sidekiq UI will also be handed off formally to the Console Services Team and people will continue to use this tool as they have been using it in the past. Note, the Sidekiq UI microservices is able to run side-by-side with the Vets-API instance of Sidekiq. With that in mind, Console Services will be responsible for deprecation of the Vets-API instance of Sidekiq, when they deem appropriate.

## Known Blockers/Dependencies 
Approval from Platform leadership to allow the IET to deploy Sidekiq UI in the production environment.

## Projected Launch Date
• Q3 2022, Sprint 24

## Desired User Outcomes

- Developers will be able to continue to use sidekiq web UI to triage issues with sidekiq jobs

## Desired Business Outcomes

- Sidekiq UI will prove out the viability of IET's microservices approach in a production environment.

## Undesired Business Outcomes

- IET prioritizes release of services over development of playbook.
- Performance degradation relative to embedded application.

### Objectives and Key results (OKRs)
- Objective:
  - Key result:  Sidekiq UI is deployed in staging environment. 
  - Key result: Sidekiq UI is deployed in production environment.
  - Key result: Sidekiq UI shows no significant errors in deployment to production
  - Key result: Sidekiq UI performance testing shows equal to or better than vets-api service in deployment to production
  - Key result: Sidekiq UI successfully handed-off/transitioned to Console Services

## Assumptions
- We will be able to leverage the same toolings for production that we 
 - Risks: 
  - - IET encounters any substantive differences between staging and production. 
 
### ... tested?
 - [x] Usability test this release introduces no usability changes. 
 - [x] ... and issues discovered in usability testing have been addressed.
 - [x] End-to-end manual QA or UAT is complete, to validate there are no high-severity issues before launching
- [x] (if applicable) New functionality has thorough, automated tests running in CI/CD

### ... documented?
- [x] New documentation is written pursuant to our documentation style guide
- [x] Product is included in the List of VSP Products 
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/IET/pages/2315354142/Product+Outline+-+Sidekiq+UI+Q3+2022)
- [x] To Do External-facing: a User Guide on Platform Website exists for this product/feature tool https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs (need to update this to include new links to service, see https://vfs.atlassian.net/wiki/spaces/AP/pages/2046558209/Edit+Platform+website+documentation)
- [x] (not applicable) Post to #vsp-service-design for external communication about this change (e.g. customer-facing meetings)

### ... measurable
- [x] (if applicable) This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
- [x] This change has an accompanying [VSP Initiative Release Plan}.https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/46139
### When you're ready to launch...
- [x] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [x] [8/23/2022](https://vfs.atlassian.net/wiki/spaces/AP/pages/2334588943/8+23+22+Office+Hours+Agenda+and+Notes) - Conduct a go/no-go when you're almost ready to launch. Feedback was to fill out this initiative checklist and then talk to our PO

### Documentation
*  **`PRODUCT_NAME`**:  Sidekiq UI 
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/IET/pages/2315354142/Product+Outline+-+Sidekiq+UI+Q3+2022
* **User Guide**: https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/blob/main/README.md
 
### Testing
* **Usability test**: Reason for skipping, we are not introducing new functionality in production.
* **Manual QA**: https://dsvavsp.testrail.io/index.php?/projects/overview/55
* **Automated tests**: https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui/actions/workflows/smoke-tests.yml

### Measurement
* **Success metrics**: [link to Product Outline](https://vfs.atlassian.net/wiki/spaces/IET/pages/2315354142/Product+Outline+-+Sidekiq+UI+Q3+2022)
 * **Release plan**: [link to Release Plan ticket(https://github.com/department-of-veterans-affairs/va.gov-team/issues/46139#event-7245076628)

---

### Current Status
- In-progress

### Key Decisions
- Go/No Go Takes
---

#### Communications

- Launch Date : Q3 2022 Sprint 24

- Note the launch for Sidekiq UI is a soft launch. The product will be deployed to production and communicated over the platform-team channel. A meeting will also be held with the Console Services representatives to formally hand off the product.

- Team Name: IET
- GitHub Label: Integration-Experience
- Slack channel: PST-Integration-Experience
- Product POCs: Frank Hiatt (PM), Emily Wilson (TL), Thomas Delrue (PO)
- Stakeholders: 

</details>

#### Team Members

<details>
 
 - DEPO Lead: Thomas Delrue
 - PM: Frank Hiatt
 - Engineering: Emily Wilson, Igor Yegorov, Salvadore Gutierrez, Will Huang
 - Research/Design: 
 
</details>

#### Stakeholders

<details>
Platform Leadership
 
_What offices/departments are critical to make this initiative successful?_
 
- Platform Team
</details>

**Comment by ewilson-adhoc** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40129 for access to sidekiq UI for testing.

**Comment by ewilson-adhoc** [comment]
This work is blocked by this epic, which we will complete first. https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/40468

**Comment by ewilson-adhoc** [comment]
Staged changes to external documentation, they should be deployed tomorrow at 3pm EST

**Comment by ewilson-adhoc** [comment]
This was officially launched on 09/01. Closing.

**Comment by ewilson-adhoc** [comment]
Tests:
https://vagov.ddog-gov.com/synthetics/details/ys6-2ri-2rj
https://vagov.ddog-gov.com/synthetics/details/6ng-ivb-me8
https://vagov.ddog-gov.com/synthetics/details/tgh-f9j-ekx
