### ISSUE TITLE
Add PST-CIT team members to AWS IAM group

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#40063]
## Issue Description
Once #40062 is done, we will need to add the PST-CIT team members to the IAM group created.

---
## Tasks
- [ ] Edit Terraform to add the newly created pst-cit team to the relevant AWS accounts 

## Acceptance Criteria
- [ ] PST-CIT team members with AWS accounts can access relevant resources in AWS
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Blocked pending https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/38669
