### ISSUE TITLE
[HOLD TO PUBLISH UNTIL 4/25] Change NADL rate on static page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40070]
## Issue Description

VA Home Loan Guaranty Service (LGY) increased the interest rate for Native American Direct Loans from 3.25% to 4.5%. This will be effective on April 25, 2022. The LGY business line would like this update go live on that date.

Here's the NADL page where we'll make the change:
https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/

---
## Tasks
- [x] Change the interest rate from 3.25% to 4.5%
- [x] Copyedit
- [x] Publish

## Acceptance Criteria
- [ ] Rate updated and validated as live on the site
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Published.
