### ISSUE TITLE
Add OIC's helpline to our "Helpful VA phone numbers" page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40071]
## Issue Description

The OIC Helpline is an important avenue for Veterans to report instances of Fraud, Waste and Abuse, or other integrity issues, especially where they are personally affected. OIC can route their concerns to the appropriate officials for investigation.

We need to add this helpline to our existing page:

Integrity and Compliance Helpline
(866) 842-4357
Hours: 24/7

---
## Tasks
- [ ] Add the OIC info to our existing page
- [ ] Copyedit
- [ ] Publish
- [ ] Let stakeholder know when it's live

## Acceptance Criteria
- [ ] New info is live
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Confirming the name of the office with stakeholder, but this is ready to publish once I hear back.

**Comment by bethpottsVADEPO** [comment]
Just changed the name per stakeholder and published. Randi will validate that it has gone live, then I'll close this ticket.

**Comment by RLHecht** [comment]
This is complete. Closing ticket.
