### ISSUE TITLE
Make updates to the "File a pre-discharge claim while overseas" page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40073]
## Issue Description
A stakeholder sent a message through VBA Digital Media (Tanekwa) requesting changes to our filing overseas page. She forwarded the request to sitewide content. 

Page to update: https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/

**Original request to assess:**

Remove the info alert.

Add the following bullets to both the “In Germany” and “In Korea” sections, with the site specific [VERA](https://vets.force.com/VAVERA/s/flow/VERA_Start?office=germany_bdd_office) links:
In Germany (Europe, Africa, or the Middle East):
Visitors seeking assistance are encouraged to schedule an appointment through [VERA](https://vets.force.com/VAVERA/s/flow/VERA_Start?office=germany_bdd_office)
In Korea (Pacific Theater countries)
Visitors seeking assistance are encouraged to schedule an appointment through [VERA](https://vets.force.com/VAVERA/s/flow/VERA_Start?office=korea_bdd_office)

Please also add “(Pacific Theater countries)” to the “In Korea” heading.

---
## Tasks (adjusted from what the stakeholder submitted to align with our standards)
- [x] Remove the info alert.
- [x] Edit the text like this:

**In Germany (Europe, Africa, or the Middle East)**

Contact the Landstuhl BDD office in one of these 2 ways:

- (Schedule an appointment through the Visitor Engagement Reporting Application (VERA))
[VERA](https://vets.force.com/VAVERA/s/flow/VERA_Start?office=germany_bdd_office), **or**
- Send us an email at GermanyBDD.vbapit@va.gov

The BDD office is in building 3724 at the Landstuhl Regional Medical Center. We're open Monday through Friday, 9:00 a.m. to 12:00 p.m., and 1:00 p.m. to 3:00 p.m. 

**In Korea (countries in the Pacific Theater)**

Contact the Camp Humphreys office in one of these 3 ways:

- (Schedule an appointment through the Visitor Engagement Reporting Application (VERA))
[VERA](https://vets.force.com/VAVERA/s/flow/VERA_Start?office=korea_bdd_office), **or**
- Send us an email at KoreaBDD.vbapit@va.gov, **or**
- Call us at DSN 757-2914 (or commercial 050-3357-2914)

The Korea BDD office is in the One-Stop Building next to the SFL-TAP office. We're open Monday through Friday, 8:00 a.m. to 12:00 p.m., and 1:00 p.m. to 4:00 p.m.

## Acceptance Criteria
- [ ] Edits and additions to this page are live and validated.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Changes are live. I just notified the SME and comms team that forwarded the request to sitewide content. I asked about the mailing address and whether we should remove it or add context about why we have it there. I'll wait to close this ticket until I hear back and update that part of the page.

**Comment by bethpottsVADEPO** [comment]
Final updates made (removing address block and edits to the text). I published the updates.

**Comment by RLHecht** [comment]
Closing as completed
