### ISSUE TITLE
Update the Post-9/11 GI Bill page to correct one word

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40072]
## Issue Description
On the Post-9/11 GI Bill page, under the header "How much monthly housing allowance (MHA) can I get?" we need to change "more" to "less" in the first bullet that starts "**How much you're attending school.**" The change is to one word in the sentence that follows the bolded line.

---
## Tasks
- [x] Change "more" to "less"

## Acceptance Criteria
- [x] Correction is live on the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
This edit went live on Friday.

**Comment by RLHecht** [comment]
closing as complete
