### ISSUE TITLE
Test VA Gov connection with VHA Server

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40086]
## Issue Description
Within the VA gov app/server, we need to test whether there's an existing connection with the provided Huron/VHA server to transfer FSR files. Otherwise we will need to request an in scope change to allow this connection through the firewall. 

---
## Tasks
- [ ] SSH into VA forward proxy and give knock to the server ip:port

## Acceptance Criteria
- [ ] We know whether we can connect from current VA network configuration with Huron server
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
