### ISSUE TITLE
Research solutions for client-side storage of access tokens (SiS)

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40093]
## Issue Description
This ticket will track the body of work for the research (and documentation) portion of storing and retrieving AT in a secure manner.

---
## Tasks
- [ ] Research cookies, session storage, and local storage with benefits
- [ ] Research alternative methods (service worker)
- [ ] Create a Proof of Concept for SiS securing AT
- [ ] Have Security try to exploit the secure storage and provide analysis

## Acceptance Criteria
- [ ] A PoC for secure storage of AT
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AGarcia-Clarity** [comment]
Already complete
