### ISSUE TITLE
Review the Health Apt designs for medical copays 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40098]
## Issue Description
The health apt team is bringing My HealtheVet over to VA.gov. We previously met with the team and learned that they'll be using the same data source as us for the medical copay section of their tool. We need to review the proof of concept and provide a data dictionary for the team. Additionally, we should sync with IA to discuss the similarities between the two products within the context of VA.gov. 

---
## Tasks
- [x] Review the proof of concept design and mark areas where we don't have access to certain data 

## Acceptance Criteria
- [x] Reviewed proof of concept is added to Mural and linked in this ticket
- [x] Data dictionary and reviewed proof of concept are sent to Meg's team 
- [x] Identify next steps for collaboration with Health Apt team and IA

**Comment by rileyorr** [comment]
Linking data dictionary here for when we send to Meg: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/Docs/PSE-VBS-DataDictionary.docx

**Comment by rileyorr** [comment]
Update regarding this ticket: @kevinstachura, @denisecoveyduc, and I met the other day to discuss product strategy regarding two tools existing on VA.gov that show copay information. Our next step is to loop Mikki in for a larger discussion with the Health Apt team so we can get a better understanding of the impact to the Veteran experience, IA, and SEO.

**Comment by denisecoveyduc** [comment]
Super! FYI set up a touchpoint with Mikki and the Health Apt team for Fri May 6th. If everyone accepts we can discuss at that time.
