### ISSUE TITLE
Profile: Sprint 73 (May 4 - May 17)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40095]
## PTO/OOO/Unavailable

- **Christina**: 
- **Sharon**:  
- **Tom**: 
- **Mark**:  PTO 5/5 (1pm - 5pm)
- **Samara**:
- **Adam**:
- **Liz**: PTO (5/9-5/11)

## Sprint Priorities
1. **Personal information Revision - Be ready for QA by sprint 73 (starts 5/4). Complete front-end work and all QA-related tasks.**## 👥 Personal Information Revision (Top Priority)
2. Complete dev work for Direct Deposit displaying consistently

### PM - Sharon
- [x] #40884 QA Go/No Go
- [x] #40859 Update Use Cases
- [x] #40524 Analytics Request - validation requested
- [x] #40467 Release Plan 
- [x] #41110 Contact Center (Collab)

### QA - Tze

- [x] #40249

### Design, FE, BE

- [x] #40035 Design
- [x] Placeholder to address possible QA tickets

###  BE - Tom

- [x] #40480 Privacy & Security

### FE - Adam

- [x] #41001 Update Error Messaging
- [x] #41067 Analytics - validation requested

### Design - Liz

- [x] #40160

### PM - Sharon

- [x] #40577 Collab Cycle Kick-off ticket

### BE - Tom

- [x] #40479 Discovery (if work carries over from Sprint 72)
- [x] #40761
- [x] #40764

### FE - Mark

- [ ] #40723 - moved to Sprint 74
- [ ] #40722 - moved to Sprint 74

### Design - Liz

- [x] #40862 (Frontend Github doc DD feature)
- [x] #39348

### PM - Sharon 

- [x] #40107 Analytics

### FE - Adam

- [ ] #41066 Analytics (moved to Sprint 74)

### Design - Christina

- [x] #39161
- [x] #40058

### BE - Tom
- [x] #40627 (Alerts -  Discovery ticket first)
- [x] #41124

### FE - Adam

- [ ] #40593 (Accessibility prod issue - screenreader) - putting in backlog pending meeting with Accessibility team

### Design - Christina

- [x] #40035
- [x] #41230

**Comment by SKasimow** [comment]
### PM - Sharon
- [ ] #39380 
- [ ] #39379
- [ ] #39169
- [ ] #39168

### BE - Tom
- [ ] #38583 (Consolidated with #37000)
- [ ] #37000 (moved from Sprint 71)

### Design - Christina
- [ ] #39161
- [ ] #40058

**Note/reminder: @cgednalske** needs to update the error state on the full fidelity mock as noted in this ticket we closed for Sprint 71 #38139

**Comment by Samara-Strauss** [comment]
@SKasimow Let's add changing how the profile menu appears to screen readers to next sprint. [Here is the Slack conversation for background](https://dsva.slack.com/archives/C909ZG2BB/p1651153191682419). This is a frontend ticket and can go to Mark or Adam depending on who has more availability.

**Comment by SKasimow** [comment]
@Samara-Strauss sounds good; I've started drafting a ticket and will add to Sprint 73.

**Comment by Samara-Strauss** [comment]
@SKasimow another addition -- @tpharrison is going to work on adding alerts to our the auth experience alerts channel in Slack that would let us know if we are seeing an increased amount of failed saves for any one of the editable sections of the profile. [Here is the Slack conversation for background](https://dsva.slack.com/archives/C909ZG2BB/p1651165248320439). We should add this work to sprint 73 unless Tom decides to do the work as part of sprint 72. That's up to him and what he has bandwidth for for the remainder of sprint 72.

**Comment by SKasimow** [comment]
@Samara-Strauss - I know @tpharrison was doing some discovery for this so am adding the work here, for Sprint 73.

**Comment by Samara-Strauss** [comment]
@SKasimow sorry for the last minute request -- can you add a ticket for you for personal info revisions to hold a QA go/no-go to make sure we are 100% ready to go to QA? This would be a very short meeting with the team where everyone confirms that the feature is ready for Tze. [Here is a template for the meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/QA/notification-prefs-QA-go-no-go.md). Please save a copy of this in the personal info revisions github folder and update as needed so it applies to this project. Let me know if you have questions!

**Comment by SKasimow** [comment]
@Samara-Strauss - sure thing!

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - just fyi per above ^ requests; tickets are as follows:

1.  Accessibility/screenreader issue [40593](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40593) and assigned to Adam
2. Alerts [40627](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40627) and assigned to Tom (I need to update the ticket to reflect Discovery work)
3. QA Go/NoGo [40884](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40884)
