### ISSUE TITLE
[CDP] Review designs after VBMS endpoint is back up for debt letter downloads

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40101]
## Issue Description
As of December 2021, the VBMS endpoint isn't providing debt notification letters. As a result, links to the debt letter download page have been omitted from the Combined Debt Portal's 404s and empty states. Once the endpoint is working properly again, we need to review the designs to add that content back in. 

---
## Tasks
- [ ] Review the Combined Debt Portal designs for areas that should direct Veterans to the debt letter download page 
- [ ] Adjust designs as needed

## Acceptance Criteria
- [ ] Designs have been reviewed, updated as needed, and linked in this ticket
- [ ] Ticket(s) for frontend implementation have been created and linked in this ticket

**Comment by denisecoveyduc** [comment]
Closing this issue since #38755 captures the same effort.
