### ISSUE TITLE
Provide strategic and editorial feedback on new transferred education benefits page

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40103]
## Issue Description
This is a new tier 1 page associated with the launch of the 1990e. Dependents use this form to apply to use transferred benefits from a Veteran or service member. The IA and I assessed existing education pages and determined that we should create a new tool landing page to house this entry point. 

Note: I need to figure out how to reinstate the green apply button, which seems to have disappeared. The label for that button is all that appears in that location now. 

---
## Tasks
- [ ] Review and edit new tool landing page: http://preview-prod.vfs.va.gov/preview?nodeId=44698

## Acceptance Criteria
- [ ] Feedback provided, ready for content team copyedit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Closing this ticket. We are working on this page in other tickets.
