### ISSUE TITLE
Update design.va.gov sidenav to match the Design System sidenav

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40100]
## Issue Description
Our current sidenav on design.va.gov does not match the [sidenav](https://design.va.gov/storybook/?path=/docs/components-sidenav--default-story) component in the Design System. The sidenav in the Design System also has additional nesting features that we need on design.va.gov to go with the documentation updates we are currently working on.

## Details
The [sidenav](https://design.va.gov/storybook/?path=/docs/components-sidenav--default-story) in the Design System is not currently a React or web component (we will develop it as a web component later), so we just need to adapt the code shown in Storybook in the Jekyll [sidenav component file](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_includes/_side-nav.html).

---
## Tasks
- [ ] Adapt the Design System sidenav component markup in the design.va.gov sidenav component file
- [ ] Test to make sure nested nav items functions correctly

## Acceptance Criteria
- [ ] The sidenav on design.va.gov looks and functions the same as the Design System sidenav component
