### ISSUE TITLE
Documentation Update: Process List

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40111]
## Issue Description
Make updates to Process List on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

Discrepancies
No concept of Content list vs. Dynamic process list in design.va.gov. 

---
## Tasks
- [x] Add View guidance for the Process List component in the Design System below label for va-process-list in Storybook  that links back to Process List on design.va.gov  (See example on va-modal)
- [x] Add link in Storybook back to Process List on design.va.gov  https://design.va.gov/components/process-list
- [x] Update link to Storybook on design.va.gov to "View va-process-list in Storybook"
~~Add Content list and Dynamic process list to design.va.gov (Get mock ups from Natalie or Matt)~~

## Acceptance Criteria
- [x] Storybook has link “View guidance for Process List component in the Design System” 
- [x] Storybook has a link to the Process List component page on design.va.gov  
- [x] XXXX link to Storybook is labeled "View va-process-list  in Storybook"
~~Process List page on design.va.gov includes Content List and Dynamic Process List~~

---

**Comment by andresriveratoro** [comment]
We decided it would be better if we create a variant of `va-process-list` to support the [dynamic process list](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/v8LjoKM) instead of creating a story with styling as this can lead to styling inconsistencies during implementation.

I've created a [ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/804) for this work.
