### ISSUE TITLE
Documentation Update: Back to top

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40110]
## Issue Description
Update documentation for Back to top on design.va.gov, Storybook and Sketch. 

Discrepancies
design.va.gov has a mobile example (icon only) in addition to desktop, but storybook just shows the default, desktop version (label + icon). However, people can use the Canvas tab in Storybook to see different screen sizes.

---
## Tasks
- [x] Add View guidance for the Back to top component in the Design System below label for va-back-to-top in Storybook  that links back to Back to top on design.va.gov  (See example on va-modal)
- [x] Add link in Storybook back to Back to top on design.va.gov  https://design.va.gov/components/back-to-top
- [x] Update link to Storybook on design.va.gov to "View va-back-to-top in Storybook"

## Acceptance Criteria
- [x] Storybook has link “View guidance for Back to top component in the Design System” 
- [x] Storybook has a link to the component page on design.va.gov  https://design.va.gov/components/back-to-top
- [x] Back to top link to Storybook is labeled "View va-back-to-top  in Storybook"

---

**Comment by andresriveratoro** [comment]
Do we want to remove the mobile example on design.va.gov for this component like we did for `va-breadcrumbs`? It's not a different variant, but an example of how the component is responsive and how it looks on mobile.

**Comment by humancompanion-usds** [comment]
Well, I would have said yes because I thought it was possible in Storybook to go to the Canvas tab and change the viewport. But I just went to try to do that in Breadcrumbs and got this:

![Screen Shot 2022-05-02 at 9 55 02 AM](https://user-images.githubusercontent.com/52176351/166245823-0e71f347-5997-4485-9a82-4aff8afb2733.png)

Is this a Storybook bug or our bug? Hold off on removing the mobile variation until we figure out how we're going to provide a responsive view.

**Comment by andresriveratoro** [comment]
This is what I see for `va-breadcrumbs` when in Canvas set to `Small Screen`:

![Screen Shot 2022-05-02 at 09.58.20.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/2fe25c3f-b555-4693-9381-e5199fcf53b8)

**Comment by andresriveratoro** [comment]
If you're having issues with the addons tab blocking the content, you can toggle `Show addons` and `Change addons orientation` when `Show addons` is selected.

![Screen Shot 2022-05-02 at 10.02.29.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/49975c38-f783-40d5-8313-50e0f67ca38f)
