### ISSUE TITLE
Documentation update: Progress Bars

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40112]
## Issue Description
Make updates to Progress Bars on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

Discrepancies
"1. Storybook missing segmented variation
2. Sketch lib doesn't label the variations
3. Sketch has a header which provides the step N of N: title, but we don't show that in the system
4. Sketch library missing a symbol for the Progress bar determinate variation -- only shown as an example in Feedback artboard

---

## Tasks
- [x] Add View guidance for the Progress Bars component in the Design System below label for va-progress-bar in Storybook  that links back to Progress Bars on design.va.gov  (See example on va-modal)
- [x] Add link in Storybook back to Progress Bars on design.va.gov  https://design.va.gov/components/progress-bar 
- [x] Update link to Storybook on design.va.gov to "View va-XXXX in Storybook"
- [x] Add to design.va.gov Step N of N 
- [x] Update Sketch file variations
- [x] Update  Sketch library with a symbol for the Progress bar determinate variation 

## Acceptance Criteria
- [x] Storybook has link “View guidance for Progress Bar component in the Design System” 
- [x] Storybook has a link to the component page on design.va.gov  
- [x] Progress Bar link to Storybook is labeled "View va-progress-bar  in Storybook"
- [x] Update story to include header for `va-segmented-progress-bar`
- [ ] Step N of N added to design.va.gov 
- [ ] Sketch file has variations
- [ ] Sketch library has a symbol for the Progress bar determinate variation

**Comment by caw310** [comment]
See the other info in this ticket. https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/257

**Comment by andresriveratoro** [comment]
> Storybook includes Segmented Section

Does this mean that we want to combine `va-progress-bar` and `va-segmented-progress-bar` into the same story? I know that on design.va.gov they're now under the umbrella of `Progress bar`, but they're different components and not variants.

**Comment by andresriveratoro** [comment]
In the meantime, I've updated `va-segmented-progress-bar` with a subtitle of `Segmented progress bar web component` with a link `View guidance for the Segmented progress bar component in the Design System` in the [draft pull request](https://github.com/department-of-veterans-affairs/component-library/pull/401).

**Comment by humancompanion-usds** [comment]
### Decision Summary
1. We'll split these out onto 2 pages. For now, we're not changing the names. Thus "Progress Bar" will be the activity bar (first example on the current page). Then we'll create a new page "Progress Bar - Segmented" that has the 2nd variation which is a step indicator.
2. Update the "Progress Bar - Segmented" Storybook variation to show a header which should always be present on the page with that component.
