### ISSUE TITLE
10-10 Health Apps: Sprint 72 (4/20 - 5/3)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#40125]
## Priorities/Objectives

- [ ] 1. Complete 1010 Short form Staging review and schedule tickets for any findings
- [ ] 2. New team members start transition activities
- [ ] 3. Team identify existing findings/tickets - Critical, bug, improvement

PTO
- Matt: 4/20-21
- Lisa: 4/22 (half-day), 4/25, 5/2
- Dene': 4/25

----
## Add Short form on 10-10EZ (#27679)

**PM**
- [x] Attend Staging Review
- [ ] #40133 Research products and familiarize with work in progress
- [ ] #40169 1010 Product Deep Dive
- [ ] #40182 Contact Center guide

**Design/Research**
- [ ] ...
- [x] Attend Staging Review
- [ ] #40135 Research products and familiarize with work in progress

**FE**
- [x] Attend Staging Review
- [ ] #39440 Accessibility Testing Checklist | Before Staging
- [ ] #39535 Change Short Form Accordion Alert
- [ ] #39288 Add Message on Short Form Review Page
- [ ] #40039 Marriage Date and Spouse DOB 
- [ ] #40134 Research products and familiarize with work in progress

**BE**
- [x] Attend Staging Review
- [x] #38715 Make isEssentialAcaCoverage required in 1010ez schema 

----
## 10-10EZ: Bugs (#40159)

**BE**
- [ ] #40183 Discovery on errors in Staging 
- [ ] #40184 Discovery on errors in Production 

----
## 10-10CG: Bugs (#40164)

**BE**
- [ ] #40185 Fix 1010cg validation error

----

## General/Other
These are bucket epics to help us organize the tickets that do not have parent epics
- [ ] #40159 Identify 1010EZ Bugs
- [ ] #40162 Identify 1010EZ Improvements
- [ ] #40163 Identify 1010EZ Critical Changes
- [ ] #40164 Identify 1010CG Bugs
- [ ] #40165 Identify 1010CG Improvements
- [ ] #40166 Identify 1010CG Critical Changes
