### ISSUE TITLE
[PM] 10-10 Health Apps: Review all product and transition documentation (Mark)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#40133]
## Background
As a new team member joining the 10-10 Health Apps team, I need to become familiar with the 10-10 products, current designs, workflows, and research.

### Resources

>- [Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/team-charter.md)
>- [10-10 Team ZenHub board](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/board)
>- [10-10 Team Sprint Planning document](https://docs.google.com/presentation/d/1ASalrxCcn-SXoNzz7ueIYQws97O6ROkXZznVch1mF-c/edit)
>- [Spreadsheet with open tickets as of 3/8/22](https://docs.google.com/spreadsheets/d/1S0G0gF1LMoXMmt7Khp6m0zzKtWP_y2ZDTHgq2VTIoU0/edit#gid=1291601289)
>
>**Main Products**
>- 10-10CG - Caregiver support program application
>     - [10-10cg Transition Doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Transition%20hub)
>     - [10-10cg Product Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers)
>     - [Staging Env - CG Form on VA.gov](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)
>- 10-10EZ - Veteran health care application
>     - [10-10ez Transition Doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/Transition%20hub)
>     - [10-10ez Product Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application)
>     - [Staging Env - EZ Form on VA.gov](https://staging.va.gov/health-care/apply/application/introduction)

## Tasks
- [ ] Review transition documents
- [ ] Review the Product Folders
     - Research documents are the best source to see what feedback we got from veterans and caregivers on the application forms
- [ ] Click through each of the forms in the Staging Environment, to become familiar with the layout, content/verbiage, and think of how a veteran or caregiver might experience filling out the form.
- [ ] Reach out to Dene', Lisa or Lihan for questions, if any

## Expected Result
- I will have a base knowledge of the products that the team is responsible for and can start to move forward on the work in progress and up next.
