### ISSUE TITLE
[Vets-API/EKS] Establish migration plan with stakeholders (for DEV)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#40147]
## Description
Work with stakeholders to develop a plan for the migration of Vets-API to EKS DEV so that we can ensure a smooth migration in the near future. 

## Background/context 
_Please see parent initiative_ 

## Resources
- [2022-04-19 Vets-API migration plan for DEV environment](https://vfs.atlassian.net/wiki/spaces/OT/pages/2163703837/2022-04-19+Vets-API+migration+plan+for+DEV+environment)

---
## Tasks
- [x] Write up a migration plan in Confluence
- [x] Share migration plan with key stakeholders and request feedback 

## Acceptance Criteria 
- [x] The migration plan is documented in confluence with information about scheduling, communication, and approach 
- [x] The migration plan has been shared with key stakeholders

**Comment by jhouse-solvd** [comment]
This is done. See linked plan in resources section above. Closing.
