### ISSUE TITLE
Setup analytic tracking for FSR notifications

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40142]
## Issue Description
FSR Notifications are ready to go live in prod but we should have some analytics in place to easily track the amount and success rate of the email delivery. VA Notify already tracks some events by default by we should hook this up with GA and DOMO. 
## Tasks
- [x] Determine what metrics to track for notifications
- [ ] Setup UTM tracker for URL where these emails will be sent from

## Acceptance Criteria
- [ ] We have analytic tracking in place to watch for # and success rate of FSR emails
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
