### ISSUE TITLE
Update AuthApp to handle ineligible message when an ineligible user attempts to start the process

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#40140]
## Issue Description
Before handing the user off to Login.gov to begin the transition, there will be one final eligibility check. This check happens regardless of the eligibility property on the user model, and occurs on the click for "start transition process". 

Should this particular call to the BE return ineligible, we will need to handle it and set a useful message to the user.

error code and copy need to be determined.

---
## Tasks
- [ ] Handle ineligible callback from the BE in the case that the "start" button returns the TBD error code.

## Acceptance Criteria
- [ ] Users who are deemed eligible, but through outside changes, become ineligible get proper/useful error messaging when attempting to start the transition message
- [ ] TBD error code for this case and messaging are added into AuthApp
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
