### ISSUE TITLE
TextArea web component: Documentation and Sketch update

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40157]
## Issue Description
Two things need to happen as part of this ticket:
1. We need to update [design.va.gov](https://design.va.gov/components/form-controls#text-area) to point to the new web component version of the Text Area component and update the documentation there if anything was changed in the conversion to a web component that needs to be noted.
2. We need to check in with @GnatalieH to make sure that any changes that were made are added to Sketch if necessary.

---
## Tasks
- [x] Update design.va.gov
- [x] Check with Natalie on Sketch updates

## Acceptance Criteria
- [x] design.va.gov documentation has been updated for this component
- [x] any necessary Sketch updates have been completed

**Comment by GnatalieH** [comment]
@k80bowman I have added the Text area element to our Sketch library.

**Comment by andresriveratoro** [comment]
@GnatalieH Do we want to create a separate Sketch page for Textarea now that it has been separated from Text inputs on design.va.gov?

**Comment by GnatalieH** [comment]
@andresriveratoro good question. @humancompanion-usds is it OK if I move Text Area to its own page in Sketch? That would allow us to link to it from design.va.gov.

**Comment by GnatalieH** [comment]
@andresriveratoro question: our text input component is called "va-text-input" and I'm wondering if this component should be called "va-text-area" instead of "va-textarea". Thoughts?

**Comment by andresriveratoro** [comment]
@GnatalieH I know it looks a little weird, but that seems to be its name (textarea). 

[Textarea element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) on MDN

**Comment by GnatalieH** [comment]
Closing issue as all tasks have been completed.
