### ISSUE TITLE
TextArea web component: Development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40152]
## Issue Description
Build a web-component version of our [TextArea React component](https://design.va.gov/storybook/?path=/docs/components-textarea--default).

Where possible, use native HTML events.

---
## Tasks
- [ ] Create `va-textarea` component and add to Storyboook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #40155, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

## Acceptance Criteria
- [ ] `va-textarea` is written and added to Storybook
- [ ] Component has been reviewed for accessibility
- [ ] Any comments from the staging review have been addressed
