### ISSUE TITLE
TextArea web component: Accessibility Review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40155]
## Issue Description
We need to conduct a full accessibility review of the new va-text-area web component. The component can be viewed in Storybook here: https://design.va.gov/storybook/?path=/docs/components-va-textarea--default

## Tasks
- [ ] Full accessibility review of the va-text-area component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

## Acceptance Criteria
- [ ] Component has been reviewed for accessibility issues
- [ ] Any accessibility issues have been addressed

**Comment by k80bowman** [comment]
@SarahKay8 could you take a look at this ASAP when you are back please? Thanks!

**Comment by SarahKay8** [comment]
> @SarahKay8 could you take a look at this ASAP when you are back please? Thanks!

Taking a look today. Thanks

**Comment by SarahKay8** [comment]
Hi @k80bowman I have no additional A11y feedback to add!

**Comment by k80bowman** [comment]
Great, thank you @SarahKay8. Closing this out then.
