### ISSUE TITLE
Research - MyHealtheVet - Share Findings with MHV Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40167]
### Description

Schedule meeting with MHV team/stakeholders and include link to report [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md)

### Tasks

- [x] Create deck (Liz)
- [x] Set up 30 min meeting (Sharon)
- [ ] Capture feedback, recommendations and questions and document in Github (Sharon/Liz)

### Acceptance Criteria

- [x] Meeting held with all necessary OCTO people
- [ ] Documentation posted to Github folder

**Comment by SKasimow** [comment]
Hi @andaleliz - I created this and ticket #40160 for research meetings. Please lmk if I should include any other tasks/ac. 

Also, can you send me the names of the MHV folks that should be invited to this meeting?

**Comment by andaleliz** [comment]
Hi Sharon! I think the tasks look good for both tickets; thanks for taking care of scheduling! For MHV, for sure we'll want to include Carnetta Scruggs, and I _think_ Theresa Hancock.  Neither of them are in our Slack instance, so you'll have to look  at their availability via the Outlook calendar on the VA network.

OCTO stakeholders we'll meet with first will also provide guidance about who else should be included.

**Comment by SKasimow** [comment]
Got it - thanks!

**Comment by Samara-Strauss** [comment]
@SKasimow I am moving this back a sprint since we won't be able to meet with OCTO folks until over a week into sprint 72. I'm pretty sure we won't get to regrouping with MHV folks before the end of sprint 72 as a result.

**Comment by andaleliz** [comment]
Increasing estimate because I added the task of creating a deck, which is never super fast.

**Comment by SKasimow** [comment]
@andaleliz - wanted to coordinate with you on timing for deck before I start looking for dates to set up the meeting. What would be a good date to start looking at avails?

**Comment by andaleliz** [comment]
I think anytime Wednesday and beyond next week. Friday, I will be available after 1:30pm EST (I'm OOO the first half of the day).

**Comment by andaleliz** [comment]
@SKasimow the deck is complete ([uploaded PDF here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/mhv-profile-recommendations.pdf)) so you can schedule the meeting for any time that's open on my calendar. Feel free to check w/ me if something is blocked off that works for everyone else.

**Comment by andaleliz** [comment]
moving to sprint 75

**Comment by andaleliz** [comment]
Absolutely! Closing it out.
