### ISSUE TITLE
Research - MyHealtheVet - Share Findings with OCTO

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40160]
### Description

Schedule meeting with OCTO (Lauren, Meg and Tracey) and include link to report [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/recommendations.md)

### Tasks

- [x] Set up 30 min meeting
- [x] Capture feedback, recommendations and questions and document in Github

### Acceptance Criteria

- [x] Meeting held with all necessary OCTO people
- [x] Documentation posted to Github folder

**Comment by andaleliz** [comment]
@SKasimow as PM can you please set up the meeting? Thank you!

**Comment by SKasimow** [comment]
Yes I'm planning to hit that next!

**Comment by SKasimow** [comment]
@Samara-Strauss @andaleliz moving to Sprint 73 since we won't be able to meet sooner.

**Comment by Samara-Strauss** [comment]
This can actually stay in sprint 72, since we should be able to meet with OCTO folks (Lauren/Tracey/Meg) before the last day of the sprint. Can you add this back in to the sprint epic if you've removed it? I've added the milestone back to the ticket. 

Of course, if the only dates people are available ARE in sprint 73, we can move it again, but Tracey said she's back on the 28th, so that gives us a few days of sprint 72 to meet with that team.

**Comment by SKasimow** [comment]
Yes - I have this in the epic for Sprint 72 (fingers-crossed)

**Comment by Samara-Strauss** [comment]
OK, just confirming since you said above that you moved it to sprint 73. Glad this is still in sprint 72 in the epic and milestone.

**Comment by SKasimow** [comment]
I moved around a few times ... but think we are good now :)

**Comment by andaleliz** [comment]
Held meeting today and [posted notes on GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/mhv-profile-research/meeting-notes/health-apt-sync-051322.md). Closing!
