### ISSUE TITLE
Documentation update: Sidenav

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40171]
## Issue Description
Make updates to Sidenav on design.va.gov,  Storybook and Sketch library to fix the discrepancies that have been identified. 

Discrepancies
1. Storybook doesn't have a title on the page nor a variation name
2. The Storybook example is pretty much non-functional.
3. Storybook and DS cannot show mobile variation - it breaks.
4. Storybook doesn't show multiple levels - how deep can the nav go?
5. Symbols in Sketch library need to allow for building a full menu

---
## Tasks
- [ ] Add View guidance for the Sidenav component in the Design System below label for Sidenav in Storybook  that links back to Sidenav on https://design.va.gov/components/sidenav (See example on va-modal)
- [ ] Make update to Symbols in Sketch library to allow for building a full menu
- [ ] Storybook doesn't have a title on the page 
- [ ] Make the Storybook example functional.
- [ ] Make it possible to show mobile variation in Storybook
- [ ] If  possible  show multiple levels in Storybook (is this possible?)
- [ ] Make it possible to show mobile variation in design.va.gov

## Acceptance Criteria
- [ ] Storybook has link “View guidance for Sidenav component in the Design System” 
- [ ] Symbols in Sketch library allow for building a full menu
- [ ] Storybook has a title on the page 
- [ ] Storybook example is functional
- [ ] Show mobile variation in Storybook
- [ ] Show multiple levels in Storybook
- [ ] Show mobile variation in design.va.gov

---
