### ISSUE TITLE
[Design] Adjust the UI for cancelled Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40179]
## User Story
As a Vet, when I click a pre-check-in link for an appointment that has been cancelled. I would like to see a message telling me that my appointment has been cancelled.

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
We need a set of wireframes 

## Tasks
- [x] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [x] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## Screens

**Note on assumptions:**
The majority of veterans proactively canceled their appointments. Veterans may be onsite or at home.

**Telephone canceled appointment**

![telephone.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/ec8088bd-03d4-45cb-81a5-2235251ff425)
[Sketch link](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/0BB5373B-E3A7-4023-9C2C-03DEF052BE68)

**In-person canceled appointment**

![inperson.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/7ad4fa9a-9dae-4c17-bd67-73d89bc1b8b8)
[Sketch link](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/129768A1-25E6-41BB-810E-8533D8D5559F)

**Comment by zach-park** [comment]
@acrollet , some questions for you you. 
Do we know if the veteran will receive this canceled error message on the day of check-in when they are onsite (at the VA facility)? 
Do we know if veterans are onsite when they click on this link for a canceled in-person appt?
Thank you!
Cc: @niradatta1

**Comment by loripusey** [comment]
@zach-park how close are we to having this wireframe ready for development?
cc: @sarahknoppA6

**Comment by zach-park** [comment]
@loripusey, @acrollet @brianseek @brdunfield 
The wireframe is ready for PO review & FE review.

**Comment by loripusey** [comment]
Thanks @zach-park , wireframe looks good! I'll copy over to the ticket.
