### ISSUE TITLE
[Research] Update Telephone Appt Research Plan and Conversation Guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#40172]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan and conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
- UAT of telephone appt. MVP (We will test with a UXPin prototype.)

## Tasks
- [x] Update research plan (template in research checklist above)
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria

- [x] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan and conversation guide to GitHub folder
- [ ] Send research plan and conversation guide to Shane for approval and to begin recruiting

**Comment by kristenmcconnell** [comment]
[Draft research plan](https://docs.google.com/document/d/1nlC8J4HioUd76ShvSLFOe2fzhtyGsJR-MP1ceB183Ew/edit?usp=sharing)

**Comment by kristenmcconnell** [comment]
[Draft conversation guide](https://docs.google.com/document/d/1K-lPdR0LRYcEKEI1tnNKJLaaXp6I-kDTEF18UUZijPg/edit?usp=sharing)

**Comment by niradatta1** [comment]
Shared for review With Lori, Stephen, and Patrick: https://dsva.slack.com/archives/C022AC2STBM/p1651161222386459

**Comment by kristenmcconnell** [comment]
Small changes that @niradatta1 and I completed today:
- Added bullets to the research goals section
- Added questions about phone preferences and what Veteran number providers are actually calling
- Added questions to understand confirmation page information hierarchy
- Added questions to gage if Veterans understand all the different tasks available on the confirmation page. 

cc @stephenBarrs @loripusey
