### ISSUE TITLE
[BE] Pass through Property to Let System Know User has Already Checked in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40175]
## Block By
CHIP [ticket](https://github.com/department-of-veterans-affairs/chip/issues/782)

## User Story
User has already completed check in but is trying to check in again.

## Acceptance Criteria
- [ ] Pass through property 'checkInSteps' to Let System Know User has Already Checked in

## Tasks
- [ ] Create Feature Flag "check_in_experience_user_already_checkin" & use for this work
- [ ] Deploy and test on staging.
