### ISSUE TITLE
Documentation update: Featured Content

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40188]
## Issue Description
The following tasks are to resolve discrepancies in documentation on design.va.gov, Storybook and Sketch. 

---
## Tasks
- [ ]Add Sketch symbol for Featured content.
- [ ] Add View guidance for the Featured Content component in the Design System below label for va-featured-content in Storybook  that links back to https://design.va.gov/components/featured-content  (See example on va-modal)
- [ ] Update link to Storybook on design.va.gov to "View va-featured-content in Storybook"

## Acceptance Criteria
- [ ] Sketch library has symbol for Featured Content
- [ ] Storybook has link “View guidance for Featured Content component in the Design System” 
- [ ] Storybook has a link to the component page on design.va.gov 
- [ ] Featured Content link to Storybook is labeled "View va-featured-content in Storybook"

---

**Comment by GnatalieH** [comment]
@humancompanion-usds can you review my [Featured content work in Sketch](https://www.sketch.com/s/789c144c-98c6-4350-b9d5-9acb6112069d/p/782D90E3-42D8-49EB-98D7-C9A0AA7FE6CB)? I'm not sure how to construct a symbol that matches the developed component's content that is responsive. Including a link in a bullet point is realistic, but it requires some Sketch hacks to make it look similar to the real thing. Are we concerned about Designers detaching this symbol since it's so content-heavy, anyway? Thx.

**Comment by humancompanion-usds** [comment]
Hmm, yeah, I see that the article padding is 0.5em which is 8px so now I'm wondering where we got the 12px from. 304px is correct but it should be 8px on both sides (currently 7px on one and 9px on the other). 

I'm not sure the Storybook example is the best one to follow. I think we'd recommend that link be an action link. Featured content, according to Beth and Danielle, is supposed to be for Eligibility. So I guess I'd prefer we use that as the example: https://www.va.gov/health-care/eligibility/

We have a decision to make here though about whether Featured Content can contain a CTA. If that's the case we need to show that. But if it's not the case and all Featured Content instances that contain CTAs should be Cards then we have a lot of bugs to file to get folks to switch. I'm thinking specifically of the ones you found in your Card audit.

I'm leaning towards saying that they don't contain CTAs or links given that they were intended for eligibility information. Can you check with Beth and Danielle and see if they agree?

**Comment by GnatalieH** [comment]
@humancompanion-usds yes I'll check in with Beth and Danielle. I'm on the fence about Featured content containing a CTA or not. I know they include links that are phone numbers sometimes. I'll change the content to match your linked example, and fix the padding. I'm not sure where we got the 12px, either. I'd hypothesize that it may have come from older Sketch templates/artifacts.
