### ISSUE TITLE
Documentation update: Breadcrumbs

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40186]
## Issue Description
The following tasks are to resolve discrepancies in documentation on design.va.gov, Storybook and Sketch. 

Note:
Fix our mobile implementation. It should not need to hide all but the last section. USWDS uses truncation.

---
## Tasks
- [ ] Add View guidance for the Breadcrumbs component in the Design System below label for Breadcrumbs in Storybook  that links back to Breadcrumbs https://design.va.gov/components/breadcrumbs  (See example on va-modal)
- [ ] Update link to Storybook on design.va.gov to "View Breadcrumbs in Storybook"
- [ ] Fix the mobile implementation so it doesn't hide the last section instead use truncation. 

## Acceptance Criteria
- [ ] Storybook has link “View guidance for Breadcrumbs component in the Design System” 
- [ ] Storybook has a link to the component page on design.va.gov  
- [ ] Mobile implementation doesn't hide the last section 

---

**Comment by humancompanion-usds** [comment]
Sorry, this note "Fix the mobile implementation so it doesn't hide the last section instead use truncation." wasn't a call to action to do it now. It was just a note that we could use a different implementation IMHO. But we'd need a team to test it out.

**Comment by andresriveratoro** [comment]
@humancompanion-usds If fixing the mobile implementation isn't part of this ticket, then this issue can be closed unless we want the example on design.va.gov to say "View Breadcrumbs in Storybook" instead of "View va-breadcrumbs in Storybook". We have been using the `va-` prefix for other web component examples thus far.  

Does the mobile implementation need to be updated?
Does the Storybook example link text on design.va.gov need to be updated to say Breadcrumbs?

**Comment by humancompanion-usds** [comment]
@andresriveratoro - I think this issue was created from the audit and the page has been updated since. The link to Storybook is fine. Mobile implementation does not need to be changed. It reflects how production works. My comment was just that how production works is less than ideal on mobile. 

What does need to be done to finish off Breadcrumb documentation is to move the Sketch examples to their own page and then to link to that page. Can you coordinate with @GnatalieH to create that page and then add the link that she provides? Thanks!

**Comment by GnatalieH** [comment]
@andresriveratoro [here is the link](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/F30D6063-F45E-4AAE-A2F5-A26C3E5EA5A5) to the Sketch mockups.
