### ISSUE TITLE
Documentation update: Banners 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#40187]
## Issue Description
The following tasks are to resolve discrepancies in documentation on design.va.gov, Storybook and Sketch. 

---
## Tasks
- [x] Add View guidance for the Banner component in the Design System below label for va-banner in Storybook  that links back to https://design.va.gov/components/banners (See example on va-modal)
- [x] Update link to Storybook on design.va.gov to "View va-banner in Storybook"
- [x]  Fix the heights of the Storybook previews on the design.va.gov page which are too small and you can't view the entire banner without scrolling within the preview window.
- [ ] Add guidance that says the following that indicates how Banners are different from Alerts: 
1. It's fixed to the top of the screen ABOVE the header (unlike an alert which is in the page).
2. It extends beyond the modernized experience and thus shows up on other va.gov pages (whereas alert cannot).
- [ ] Add Banner to Sketch library
- [x] Remove the extra section with Technical Documentation 

## Acceptance Criteria
- [x] Storybook has link “View guidance for Banner component in the Design System” 
- [x] Storybook has a link to the component page on design.va.gov 
- [x] Banner link to Storybook is labeled "View va-banner  in Storybook"
- [x] Height of the Storybook preview doesn't require scrolling on design.va.gov 
- [ ] Guidance has been updated with text on how Banners are different from Alerts. 
- [ ] Sketch library has banners
- [x] The extra section with Technical Documentation has been removed

---

**Comment by caw310** [comment]
@humancompanion-usds , Please confirm the text is correct for how Banners are different from Alerts.

**Comment by humancompanion-usds** [comment]
@caw310 - Yes, that is the current understanding but Dave Conlon is confirming. I say we draft it up that way and then circle back around with him to see if he has confirmed or not.

**Comment by pdavies88** [comment]
@caw310 we should add to this ticket to remove the extra section I wrote for Technical Documentation since that will be covered now by "Code Usage": design.va.gov/components/banner#technical-documentation-on-va-banner

**Comment by caw310** [comment]
@pdavies88 , Yes. I'll add a task to remove that section. Thanks!
