### ISSUE TITLE
[PM] 10-10EZ Short-Form: Complete updates to Contact Center guide

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#40182]
## Background
In preparation for the 10-10EZ short-form launch, we need to complete the Contact Center guide updates.  This includes content and screenshots.  See ticket #38288 (not yet submitted for guide review)

## Tasks
- [x] Update Contact Center guide with steps, content and screenshots
- [x] Request Dene' to look over prior to submission
- [x] Submit final draft through ticket #38288 for review

## Acceptance Criteria
- Contact Center guide is updated and submitted for review

**Comment by hdjustice** [comment]
[Final draft ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/HCA.Product.Guide.shortform.FinalDraft.docx)submitted to contact center team.  Once feedback is received, we will create a ticket to incorporate any changes.
