### ISSUE TITLE
Design - Profile -  Direct Deposit - Document Front-end Design

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40195]
Background

### Tasks

- [ ]  Document Front-End design
- [ ]  Add link to documentation to FE build ticket

### Acceptance Criteria

- [ ] Document Front-End design
- [ ] Add link to documentation to FE build ticket

**Comment by andaleliz** [comment]
this is a duplicate of 40196
