### ISSUE TITLE
Design - Profile -  Direct Deposit - Document Front-end Design

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40196]
### Background

Document the updated Direct deposit information screens to align with the mockups, including content, form fields, and user interactions.

### Tasks

- [ ]  Document new Front-End design
- [ ]  Add link to documentation to FE build ticket

### Acceptance Criteria

- [ ] Document Front-End design
- [ ] Add link to documentation to FE build ticket

**Comment by andaleliz** [comment]
@Samara-Strauss and @SKasimow I'm not quite sure how to approach this. A few thoughts:

1. The core change we're making is that the section is no longer conditionally displayed. That feels like it should be updated in the product outline and the call center guide, with instructions to do this in a FE ticket ([40722](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/40722)). I don't think that would need to live on forever in a `.md` file for FE documentation once it's implemented.

2. The copy changes could also go in the FE ticket, because once they are implemented, I don't think we'll need to refer back to an `.md` file again.

3. It doesn't seem that we have a centralized place where different use cases are captured for this feature, so I'm going to create a folder for it, and move the [fiduciary blocking flag use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/direct-deposit-comp-pen-fiduciary-blocking.md) in that directory.

Let me know if you feel differently. Otherwise, I'll proceed with adding copy details to FE tickets, and creating a doc for direct deposit use cases.

**Comment by Samara-Strauss** [comment]
Thanks for starting that!

If we want to use this for testing/QA, those changes will eventually need to make their way into the [direct deposit staging user doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md). No need to do that right now, just wanted to point it out in case the intention later on is to document which users apply to which test case. That stuff should all be in the sensitive repo with all staging user docs so it's easy to find (and someday get into the new test user dashboard).

**Comment by Samara-Strauss** [comment]
Sorry, I didn't see your message above the most recent one. Let me respond to that:

Re: frontend documentation -- you raise a good point that there is a difference between the frontend documentation used just for build and documentation on how a feature works that persists and is kept up to date over time. For this ticket, the originally intended purpose was to make sure Mark had the documentation he needed to build out the frontend changes you've made. Personally, I don't care whether that is in a ticket or a github doc as long as the documentation is clear and easy to follow. If the work can clearly be documented in a ticket, great, but if it's too much and too lengthy, we can create a github doc for frontend to guide build similar to what we've done for other projects.

**However**, you are light in the coming sprint, and we do need much better documentation on how this feature works as a whole that we can keep up to date over time. If you were up for it, we could change the scope and estimate of this ticket to include full documentation of the direct deposit feature to be completed in sprint 73. Alternatively, we could keep this ticket to just the FE build documentation and create a separate ticket for documenting the feature as a whole. What do you think? Happy to be flexible here and discuss what approach might make the most sense.

**Comment by Samara-Strauss** [comment]
> I'd love to have a doc convo with you before I jump in fully so I will look on your calendar for availability tomorrow.

Sounds good! My calendar is up to date, so feel free to pick a time that works for you.

**Comment by SKasimow** [comment]
Happy to join as well
