### ISSUE TITLE
[Design] | Profile | Direct Deposit | Update Contact Center Guide

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40197]
Background

Once all the UI changes have been updated in mockups and/or FE so that new screen shots can be taken, update the Contact Center documentation to include the persistent Direct deposit screen (shows for users who don't receive direct deposit payments) and associated alerts/errors created to support this change.

## Tasks

- [ ] Complete Contact Center Documentation
- [ ] Review with PO
- [ ] Submit to Contact Center
- [ ] Update Product Guide page to note date submitted to Contact Center

## Acceptance Criteria

- [ ] Complete Contact Center Documentation
- [ ] Review with PO
- [ ] Submit to Contact Center
- [ ] Update Product Guide page to note date submitted to Contact Center
