### ISSUE TITLE
Design - Direct Deposit - Show Consistently

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40191]
### Description

We want to show the direct deposit section persistently instead of conditionally and need the designs updated to reflect this change.

### Story

1. As a Veteran who does not receive direct deposit payments for compensation and/or pension 
WHEN
viewing my Profile on VA.gov
THEN
I should see the section "Direct deposit information" when viewing the list of categories 

2. As a Veteran who does not receive direct deposit payments for compensation and/or pension and/or education
AND
attempt to view my Profile - Direct deposit information page
THEN
I should see the Direct deposit page and a message stating that we don't detect that they are receiving payments.

3. As a Veteran who does not receive direct deposit payments for compensation and/or pension
AND
I attempt to view my "Profile - Direct deposit information" page
WHEN
there is an outage or some sort of system error that prevents the page from displaying
THEN
I should see an error message within the direct deposit section (vs today where it is seen on Personal + Contact info)

### Tasks

- [x] Create mock-ups for each story. This includes updating mock-ups to reflect EDU DD 
- [x] Review content w/ Danielle
- [ ] Review designs w/ team (PO, PM, and devs)

### Acceptance Criteria

- [ ] Mock-ups approved 
- [ ] Sketch files updated

**Comment by SKasimow** [comment]
Hi @andaleliz - here's a draft; I had some q's we can review tomorrow and then I'll complete.

**Comment by andaleliz** [comment]
@SKasimow 😍 this is so great! I love how you did the stories, that is incredibly helpful. Haven't had that done for me before. Thank you so much.  It won't take long to answer your questions tomorrow.

**Comment by andaleliz** [comment]
I'm having a tough time navigating the docs for direct deposit, I _think_ because they're split between pre and post EDU direct deposit.  A few initial thoughts/questions:

@SKasimow or @Samara-Strauss,  can you help me track down the documentation or a mock-up for user story 3? It sounds like 3 exists and we just need to mock-it up in direct deposit vs on the profile landing page. 
I've checked:
- the Sketch files
- the AdobeXD files I can find linked from the [EDU design documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/README.md) (Sharon, Jim Adams designed the EDU DD screens and used AdobeXD).  
- the contact center guide in the [direct deposit product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit)

For story 4, I would imagine that scenario has already addressed for this feature (and we probably don't need to do it for this round of work) - do either of you know if that's the case?

I came across an [old screenshot of a user who has payments but not 2FA](https://user-images.githubusercontent.com/1915775/58044275-5efde680-7b0d-11e9-9fb1-71e0056ac5d2.png), from Profile 1.0. I can't find a screenshot for how that is handled in 2.0, but I imagine it's already addressed.  [Samara pointed out Slack ](https://dsva.slack.com/archives/C909ZG2BB/p1650474089978999?thread_ts=1650473668.064039&cid=C909ZG2BB) that we probably don't need that gate in the screenshot since DS Logon and MHV users can't access direct deposit but we need to double check.

**Comment by andaleliz** [comment]
@Samara-Strauss another question for you. I saw this in the Medallia feedback:
>Trying to sign up for direct deposit of Widow's Aid In Attendance benefit. It's presently being sent by mail and I wish to have it deposited directly into my bank account. I'm not able to find the suggested link to add my bank to my profile. Would appreciate any help you can give.

Can a person view or update their direct deposit online for any benefit _other_ than edu, comp or pen? I want to make sure I'm accurate in the content I propose. Thanks!

**Comment by Samara-Strauss** [comment]
> can you help me track down the documentation or a mock-up for user story 3? It sounds like 3 exists and we just need to mock-it up in direct deposit vs on the profile landing page.

I'm so sorry, but I can't find a screenshot of this anywhere, which is a real shame because this state has occurred a few times in the last week due to EVSS/BGS issues 🤦‍♀️ If you need exact copy, we might have to get Adam or Mark to pull it from the code. If I happen to see this in the wild in the next few days, I will definitely grab a screenshot and drop it here. 

> I came across an [old screenshot of a user who has payments but not 2FA](https://user-images.githubusercontent.com/1915775/58044275-5efde680-7b0d-11e9-9fb1-71e0056ac5d2.png), from Profile 1.0. I can't find a screenshot for how that is handled in 2.0, but I imagine it's already addressed. [Samara pointed out Slack ](https://dsva.slack.com/archives/C909ZG2BB/p1650474089978999?thread_ts=1650473668.064039&cid=C909ZG2BB)that we probably don't need that gate in the screenshot since DS Logon and MHV users can't access direct deposit but we need to double check. Sharon is going to look into this.

In 2.0, the 2FA alert is the same as 1.0. It shows in the direct deposit section, and users can't see the rest of the feature until they add 2FA.

That being said, I doubt we need that gate anymore, but we need to triple confirm that ID.me and Login.gov users always have 2FA once they've verified their identities. If not, we can not remove that gate and should leave it in place. It's essential for security reasons that everyone accessing direct deposit have 2FA set up.

> Can a person view or update their direct deposit online for any benefit other than edu, comp or pen? I want to make sure I'm accurate in the content I propose. 

Nope, just compensation, pension, and education. I just searched and the [Widow's Aid in Attendance](https://www.va.gov/pension/aid-attendance-housebound/) benefit is a type of pension benefit, so that should be covered under our feature.

This sounds like another case of a person who should be seeing direct deposit in their profile and isn't, which is why I want to persistently show the section so we can figure out what's going on. If people start writing in saying "I receive direct deposit and my bank information isn't showing up", I'm hoping we'll be able to find a way to get in touch with them to figure out what's going on. So this work is a first step in helping us to figure out if there is a bigger problem.

**Comment by andaleliz** [comment]
>I'm so sorry, but I can't find a screenshot of this anywhere, which is a real shame because this state has occurred a few times in the last week due to EVSS/BGS issues 🤦‍♀️ If you need exact copy, we might have to get Adam or Mark to pull it from the code. If I happen to see this in the wild in the next few days, I will definitely grab a screenshot and drop it here.

No prob - that would be great if there is a way to get a screenshot in the next few days. Does it make sense for me to approximate some kind of mock-up to now show this alert in the direct deposit section with a caveat for the devs that says something like "don't pay attention to the copy, just move this error state from `/profile` to the direct deposit page?

Do we know if it's a warning or an error alert? It _should_ be a warning based on the alert audit we did last fall but it's possible it was never updated.

>we need to triple confirm that ID.me and Login.gov users always have 2FA once they've verified their identities.

I'll reach out in #vsp-identity and see what I can learn about this.

>can you help me track down the documentation or a mock-up for user story 3? It sounds like 3 exists and we just need to mock-it up in direct deposit vs on the profile landing page.

I'm so sorry, but I can't find a screenshot of this anywhere, which is a real shame because this state has occurred a few times in the last week due to EVSS/BGS issues 🤦‍♀️ If you need exact copy, we might have to get Adam or Mark to pull it from the code. If I happen to see this in the wild in the next few days, I will definitely grab a screenshot and drop it here.

I came across an [old screenshot of a user who has payments but not 2FA](https://user-images.githubusercontent.com/1915775/58044275-5efde680-7b0d-11e9-9fb1-71e0056ac5d2.png), from Profile 1.0. I can't find a screenshot for how that is handled in 2.0, but I imagine it's already addressed. [Samara pointed out Slack ](https://dsva.slack.com/archives/C909ZG2BB/p1650474089978999?thread_ts=1650473668.064039&cid=C909ZG2BB)that we probably don't need that gate in the screenshot since DS Logon and MHV users can't access direct deposit but we need to double check. Sharon is going to look into this.

In 2.0, the 2FA alert is the same as 1.0. It shows in the direct deposit section, and users can't see the rest of the feature until they add 2FA.

That being said, I doubt we need that gate anymore because we don't let DS Logon or MHV users access this feature anyway, but we need to triple confirm that ID.me and Login.gov users always have 2FA once they've verified their identities. If not, we can not remove that gate and should leave it in place. It's essential for security reasons that everyone accessing direct deposit have 2FA set up. Part of me thinks we should leave the gate just to be sure all our bases are covered.

Can a person view or update their direct deposit online for any benefit other than edu, comp or pen? I want to make sure I'm accurate in the content I propose.

Nope, just compensation, pension, and education. I just searched and the [Widow's Aid in Attendance](https://www.va.gov/pension/aid-attendance-housebound/) benefit is a type of pension benefit, so that should be covered under our feature.

This sounds like another case of a person who should be seeing direct deposit in their profile and isn't, which is why I want to persistently show the section so we can figure out what's going on. If people start writing in saying "I receive direct deposit and my bank information isn't showing up", I'm hoping we'll be able to find a way to get in touch with them to figure out what's going on. So this work is a first step in helping us to figure out if there is a bigger problem.

I know call center data is challenging but I wonder if there is a way we can learn anything more about this problem from that end. Or ask them to start keeping track of it somehow. I know Medallia doesn't always capture info we can follow up on.

**Comment by Samara-Strauss** [comment]
> Does it make sense for me to approximate some kind of mock-up to now show this alert in the direct deposit section with a caveat for the devs that says something like "don't pay attention to the copy, just move this error state from /profile to the direct deposit page?

Yes please.

> Do we know if it's a warning or an error alert? It should be a warning based on the alert audit we did last fall but it's possible it was never updated.

It's the yellow warning alert.

> I'll reach out in #vsp-identity and see what I can learn about this.

Thanks!

> I know call center data is challenging but I wonder if there is a way we can learn anything more about this problem from that end. Or ask them to start keeping track of it somehow. I know Medallia doesn't always capture info we can follow up on.

We probably could work with the call center on this. We can ask that team about it.

**Comment by Samara-Strauss** [comment]
> Since all sections will show no matter what, we should be able to get rid of any alert that displays above the h1 on the main page, correct?

Yes, we can remove that alert on the main page if we persistently show the section! Definite improvement.

> I just met with Danielle to review the content for use case 2, as well as the content page alert updates, and there are just some small tweaks. This work will definitely be completed in this sprint.

Great!!

**Comment by andaleliz** [comment]
Added the content review ticket as a blocker for this work; waiting for Danielle's content updates before I can move forward.

**Comment by andaleliz** [comment]
Sharing an update that I'm still waiting on Danielle to provide her edits. It's on her radar but she has not had time.

**Comment by Samara-Strauss** [comment]
Totally fine, and thanks for the update. 

Given that we want to get Mark working on the direct deposit update in this upcoming sprint, is it safe to assume we can have him start of some of the design updates and get him copy later? I don't want the copy to hold up starting on the frontend work unless we feel it would be pointless for Mark to start without it. It is *totally fine* that Danielle is busy, and there is no rush on the copy, but I just wanted to make sure I explicitly brought this up so we could plan for the frontend build accordingly.

**Comment by andaleliz** [comment]
Yes! Let's have him plan on working on that in the upcoming sprint. I reached out to Danielle this morning and she said she'll get me finalized copy today. We should have the whole package ready for Mark in the next sprint.

The FE changes for the corresponding updates on the content pages are already 100% ready for him (not sure if @SKasimow has created that FE ticket though).

**Comment by SKasimow** [comment]
@andaleliz I've drafted 2 tickets for DD one of which is for the Content pages. Let's get together with Mark and do a walk-through/groom since we want him to start on them for new sprint Wed.

**Comment by andaleliz** [comment]
Sounds good! I'm happy to support if needed when you walk him through the work, but please do let me know if I could've been more clear in the [details I outlined in the comment on my ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40244#issuecomment-1113305692).  My hope is that I leave things in a state that folks can run with it :)

**Comment by SKasimow** [comment]
Thanks - I think it's clear but wanted to walk thru more bc Mark and I are relatively new and want to make sure I've interpreted everything correctly!

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! I heard back from Danielle and have [this mock-up ready for your review.](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/v/jDKVVz/a/OmJpOLG/r/0dmrMV) This is what anyone sees who doesn't have compensation, disability, or edu direct deposit payments. 

[Here's the updated alert](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmvQ3YE) for the incompetent flag as well.

I look forward to your feedback! Once you're good with these, I'll make the mobile versions too.

**Comment by Samara-Strauss** [comment]
Thanks for this! 

- For the general "blank state" mockup, I can't tell whether it might be confusing that we are saying "you don't have direct deposit set up" to people who may just not have this benefit in the first place. Yes, they don't have it set up, but it could be because they receive payments via check OR because they don't receive education benefits at all. Did you and Danielle talk about this?
- For the fiduciary flag, why is the [copy different from what we currently have](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/direct-deposit-comp-pen-fiduciary-blocking.md)?

**Comment by andaleliz** [comment]
>For the general "blank state" mockup, I can't tell whether it might be confusing that we are saying "you don't have direct deposit set up" to people who may just not have this benefit in the first place. Yes, they don't have it set up, but it could be because they receive payments via check OR because they don't receive education benefits at all. Did you and Danielle talk about this?
We did talk about it, and we were both on the fence. We landed on the simpler version earlier today, but I just revisited with her and we landed on this:
>Our records show that you don't receive VA education benefit payments or haven't set up direct deposit payments.

I think that'll minimize confusion and is clearer than the original sentence I had proposed.

>For the fiduciary flag, why is the copy different from what we currently have?
Back in Sept 2021, we audited all the profile alerts to introduce more consistency; as part of that work Danielle and I decided to tone down some of the messaging since they weren't really errors committed by the user or something they could act on in the UI. Some alerts stayed the same but the fiduciary flag alert is one [we recommended changing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/maintenance/front-end/alert-updates-Sept-2021.md#10-user-has-been-flagged-as-incompetent-so-they-cant-access-their-financial-information-32416). The FE work never got completed, but there is a ticket out there for it. My mock-up reflects what the recommendation was from Sept 2021.

**Comment by andaleliz** [comment]
>Would it be possible to use the warning style with the original copy?

Most definitely! I'll ask Danielle to review the original copy in the next office hours, only because I _think_ "You can't..." no longer aligns with our language on VA.gov. If we need to make any tweaks, we can do that as a separate maintenance ticket.

All mobile and desktop screens have been updated in the Sketch file to reflect what we've discussed here. Closing this out with hours to spare in the sprint ;)

**Comment by SKasimow** [comment]
Hi @andaleliz - can you provide the link for sketch file that has the general "blank state" mock-up:

> Our records show that you don't receive VA education benefit payments or haven't set up direct deposit payments.

Same for the fiduciary alert; I need to update the FE ticket with these changes.

**Comment by andaleliz** [comment]
Hi @SKasimow - I added those links to the ticket earlier today, they should be good to go.

**Comment by SKasimow** [comment]
@andaleliz - I see the content updated within in the ticket but thought there was an updated sketch file to go along with the changes. This is just my ignorance but for FE work like this, is the final text embedded in the ticket vs the sketch file?

**Comment by andaleliz** [comment]
@SKasimow, the Sketch files are updated, but the URL should be the same. Here's a screenshot of the latest "blank state" version - lmk if that's not what you're seeing when you click the links from the FE ticket.

![image](https://user-images.githubusercontent.com/55992116/166587294-86af6ee3-4d1d-43b4-906d-ebc301cbaf9a.png)

>This is just my ignorance but for FE work like this, is the final text embedded in the ticket vs the sketch file?
I'm so glad you asked this question. Typically we either embed final text in the FE ticket, or create a separate content doc to make it easy for devs to copy and paste content. Historically, our mock-up platforms have not made it easy to copy/paste text since they're image based.

_HOWEVER_ your question prompted me to check if it's possible to grab copy from Sketch for Teams, and **it seems like it is!** This may mean we no longer need separate docs for content if devs can grab it from the mock-up. I would want to check w/ the devs to make sure it works for them before doing that.  

@Samara-Strauss if devs could copy/paste content directly from the mock-ups, is there a reason you can think of we'd need to have copy separated out?

**Comment by SKasimow** [comment]
@andaleliz thank you Liz!! 

And that would be **great** if we are able to grab both content and mocks from Sketch!

**Comment by Samara-Strauss** [comment]
> if devs could copy/paste content directly from the mock-ups, is there a reason you can think of we'd need to have copy separated out?

THIS IS AMAZING!! No, I don't think there is an addition to need to copy/paste the text if they can get it from the Sketch file, but we should make sure they know that (I see you did in Slack) probably the first few times we do this so they get used to it. But this sounds great to me! It will make things so much easier.
