### ISSUE TITLE
Design - Profile - Direct Deposit - Update Contact Center Guide

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40198]
Background

Once all the UI changes have been updated in mockups and/or FE so that new screen shots can be taken, update the Contact Center documentation to include the persistent Direct deposit screen (shows for users who don't receive direct deposit payments) and associated alerts/errors created to support this change.

## Tasks

- [x] Complete Contact Center Documentation
- [ ] Review with PO
- [ ] Submit to Contact Center
- [ ] Update Product Guide page to note date submitted to Contact Center

## Acceptance Criteria

- [x] Complete Contact Center Documentation
- [ ] Review with PO
- [ ] Submit to Contact Center
- [ ] Update Product Guide page to note date submitted to Contact Center

**Comment by andaleliz** [comment]
Hi @SKasimow! Thanks for creating this ticket. I think we talked about working on these updates together so I added you as an assignee. Feel free to remove yourself if that's incorrect. In the past, I handled the updated screenshots and AJ did the content updates.

**Comment by andaleliz** [comment]
@SKasimow I completed the updates to the guide - do you want to review it before we bring Samara in to get her review?
