### ISSUE TITLE
Support Process - GA Access Requests & Offboarding

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#40209]
## Issue Description

We need to transition GA access and offboarding requests from SDI to other analytics teams members.  

https://vfs.atlassian.net/wiki/spaces/AT/pages/1878065211/WIP+-+Google+Analytics

---
## Tasks
- [ ] Train all team members on process and how to grant access (so everyone can support if needed)
- [ ] Train all team members on offboarding/removing access requests
- [x] Create slack user group to be used on support requests
- [ ] Determine who will manage the process ongoing and update support rotation doc

**Comment by jerinb-sdi** [comment]
**Adding someone to GA w/o a Gmail Account:**

- In GA access the 'Admin' tab
- Under 'View', select 'View Access Management'
- Click the '+' in the upper-right corner and select 'Add Users'
- Add user(s) email address(es) (use commas to separate); be sure 'Notify new users by email' is checked
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- If the email address they’d like to use isn’t linked to Google
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Can you please create a Google account using another email? Click ‘Use my current email address instead’.  https://accounts.google.com/SignUp?hl=en
- Grant them ‘Analyst’ access
- Click 'Add'

**Comment by michelle-dooley** [comment]
Requested slack user group:  platform-analytics-insights-team

**Comment by michelle-dooley** [comment]
Created a page in confluence with steps for reference.  Want to clarify role assignment.
https://vfs.atlassian.net/wiki/spaces/AT/pages/2172157977/How+to+grant+access+to+GA

**Comment by michelle-dooley** [comment]
All steps are documented in Confluence
