### ISSUE TITLE
Uvicorn access logs in Grafana

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#40201]
## Issue Description

FastAPI/Uvicorn access logs are shipped by Loki into Grafana.
While the raw logs can already be seen in Grafana Explore,
a dashboard/visualization to allow search in the log contents
would be next step toward mature Observability. 

---
## Tasks
- [x] Remove Gunicorn layer on top of Uvicorn for simplification
- [x] Explore the data and parse the fields
- [x] Produce a Grafana dashboard/visualization to allow for search in the log contents
- [ ] Document the LogQL query to parse the logs

## Acceptance Criteria
- [ ] Grafana ready for demo
---

**Comment by ewilson-adhoc** [comment]
This ticket has been completed.
