### ISSUE TITLE
[CDP] Usability study conversation guide version 2

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40218]
## Issue Description
Veterans expect to find all money they owe to VA in one location on the site. Additionally, Congress has mandated that we provide a way for Veterans to access all their debts in one spot.

We need to validate the combined VBA + VHA debt portal design with Veterans to ensure it meets our users' needs.

---
## Tasks
- [x] Iterate on [the conversation guide's first daft](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Combined%20VA%20Debt%20Portal/Usability%20April%202022/Conversation%20Guide.docx?d=w2d933505598c478ab8a8c0f66d400ab9&csf=1&web=1&e=EiwFgw) to finalize prior to review

## Acceptance Criteria
- [x] Conversation guide has been added to GH and linked in this ticket
- [x] Conversation guide has been sent out for review 
- [x] Midpoint review ticket has been opened

**Comment by rileyorr** [comment]
Note for myself:
- Sync with Mikki and Danielle once the convo guide is finalized so we can chat about Drupal page support and if this approach captures IA's questions about how Veterans navigate between debts and copays both on the site and within the portal

**Comment by rileyorr** [comment]
Second draft has been added below the first draft in the document linked in this ticket's description. Going to chat with Kevin about it on Monday and iterate before we send it out for review!

**Comment by rileyorr** [comment]
Incorporated Kevin's feedback and added [the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/conversation-guide.md) to GH. Sent to Kristen McConnell for review.

**Comment by rileyorr** [comment]
@denisecoveyduc I opened [the midpoint review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40519) for the collab cycle. It looks like we need to provide regression test plans and test cases/test plan ini TestRail. So we might be blocked from scheduling the meeting until we link those artifacts.

**Comment by denisecoveyduc** [comment]
Great work @rileyorr Can't wait to hear what Veteran's have to say about this feature.. I think it will make a real impact to their overall experience!
