### ISSUE TITLE
Date web component: Migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40212]
## Issue Description
This component is only used three places in `vets-website` and then in the `va-forms-system-core` repo. We probably don't need a migration script, but we should reach out to the teams who are codeowners on these files. If they are not able to prioritize the work, we could offer to migrate the component for them.

---
## Tasks
- [ ] Reach out to app teams using the Date or SimpleDate component about migrating to `va-date`
- [ ] Reach out to the Forms Library Team about migrating to `va-date`

## Acceptance Criteria
- [ ] Teams responsible for code that use the Date or SimpleDate React components have been contacted about migrating to `va-date`.

**Comment by k80bowman** [comment]
I checked the `vets-website` repo and I could not find any references to the Date React component. I also checked with Robin Garrison just to be extra sure, since he was using the Date and SimpleDate components in a couple of places. This migration is no longer necessary and we can go ahead and remove the React Date component from the component library. I'll do that work as part of this ticket.

**Comment by k80bowman** [comment]
Moving this back to Current Sprint until we are ready to also remove the MonthYear and NumberInput React components. We will be ready to do that once [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21329) has been merged.
