### ISSUE TITLE
GTM Implementations

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#40210]
## Issue Description

We need to transition GTM implementations from SDI team.

---
## Tasks
- [ ] Train team on how to complete a GTM implementations
- [ ] Analytics team members shadow/take over process with SDI support as needed

## Acceptance Criteria
- [ ] Analytics teams takes over GTM implementations
---

**Comment by michelle-dooley** [comment]
We completed training still some challenges and gaps in knowledge base for this piece of work.
