### ISSUE TITLE
GA Training Deck 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#40211]
## Issue Description

We need to transition GA training from SDI team.

https://docs.google.com/presentation/d/1VqFTJso8IkatklBSvbW--dc9j51SNLh9nDedoEoTyDU/edit#slide=id.p

---
## Tasks
- [x] SDI team trains analytics team on process/deck (we can record for reference but we will also want a formal recording)
- [x] SDI records a "formal" training session for future use

---
## Acceptance Criteria
- [x] Training has been completed and a recording has been made.

**Comment by michelle-dooley** [comment]
https://ga-dev-tools.web.app/dimensions-metrics-explorer/

**Comment by michelle-dooley** [comment]
Link to recording.  Will also put on share drive. https://oddball-io.zoom.us/rec/share/wDCs1nXNNOAjOP2Vjg6RfmRYAvkc3MeGZq3fOyJAWYUqugcLxb1bTH2h2I4vHRv-._KGTB0OeR4dwu2De?startTime=1650997975000
Passcode: QTcMiV!1
