### ISSUE TITLE
Date web component: Migration and Announcement

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40213]
## Issue Description
This component is only used three places in `vets-website` and then in the `va-forms-system-core` repo. We probably don't need a migration script, but we should reach out to the teams who are codeowners on these files.

We also need to announce the component in Slack and update the [What's new?](https://design.va.gov/documentation/whats-new) page on design.va.gov

---
## Tasks
- [x] Reach out to app teams using the Date or SimpleDate component about migrating to `va-date`
- [x] Reach out to the Forms Library Team about migrating to `va-date`
- [x] Craft announcement and post in #vfs-frontend and #vfs-engineers
- [x] Add note to What's new? page

## Acceptance Criteria
- [x] Announcement has been posted in #vfs-frontend and #vfs-engineers
- [x] Relevant teams have been notified
- [x] What's New? page has been updated

**Comment by pdavies88** [comment]
Manual Migration Docs: https://vfs.atlassian.net/wiki/spaces/DST/pages/2127527996/Manual+Component+Migration+Guide#Date-or-SimpleDate-to-va-date%3A

**Comment by pdavies88** [comment]
Announcement:
:wave: Hi Front End Teams,
I am reaching out today because we on the Design System Team have created a new web component for [Date](https://design.va.gov/components/form/date-input) to replace the old Date React Component. 

We have detailed the steps for migrating to the web component here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2127527996/Manual+Component+Migration+Guide#Date-or-SimpleDate-to-va-date%3A.

If you have questions around this web component or need help with performing a migration for this component please feel free to reach out to me via #platform-design-system, as I am happy to assist.

Thanks!
