### ISSUE TITLE
[DISCOVERY] Research how existing services leverage SFTP 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40228]
## Issue Description
VHA would like to receive CSV files directly to their Huron servers to accommodate for online FSR forms. There exists current services that use SFTP for file transfer including Covid vaccine enrollment and the education 22-1990 forms.  

---
## Tasks
- [x] Look into how these services use SFTP and identify any best practices
- [x] Research what the destination for these files relate to VHA

## Acceptance Criteria
- [ ] We have an understanding of how we can use SFTP with an external server on VA.gov
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
[Discovery documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/sftp/sftp-discovery.md)
