### ISSUE TITLE
[Design] Wireframes for New Design System Language Toggle Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40224]
## User Story
As a Veteran whose native language is Spanish or Tagalog, I want to be able to see the CI and PCI content in Spanish so that I will understand it.

## Description
A wireframe set for switching the new Design System component for the language toggle.

## Tasks
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] Sync with design system (Danielle) on solution (loop them in). Ask if Matt should be looped in from Danielle. 

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] Meet with design system on solution

**Comment by ytsaoca** [comment]
2 design options: (1) [add a subheader with the language toggle](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m123alz), and (2) notification on the top and a language toggle at the bottom - [Version 1](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dlpj8JE) and [Version2](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/zxaK1Le).

**Comment by ytsaoca** [comment]
2 design options: (1) [add a subheader with the language toggle](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/m123alz), and (2) notification on the top and a language toggle at the bottom - [Version 1](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dlpj8JE) and [Version2](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/zxaK1Le).

**Comment by loripusey** [comment]
@ytsaoca Where is the design that contained the drop down?
cc: @kristenmcconnell

**Comment by ytsaoca** [comment]
Final version to test after talking to accessibility team and Danielle
- subheader
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/dl29Z4j
- toggle with notification
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/k5pJzo/a/rbJabL7/r/R3vqGQ 
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/k5pJzo/a/nRjGRYd/r/R3vqGQ
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/k5pJzo/a/QbdobgL/r/R3vqGQ
