### ISSUE TITLE
[DISCOVERY] Research how to move FSR submissions into batch file

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40229]
## Issue Description
VHA would like to receive FSR submissions as a daily job that has a batch of submissions rather than a file every time a Veteran submits a request. We need to identify how feasible this is for our configuration and what this implementation may look like.

---
## Tasks
- [x] Look into how to create a spool file for FSR and group submissions together

## Acceptance Criteria
- [x] We have an understanding of how we will create batch files for FSR bulk requests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
[Batch file discovery docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/sftp/batch-file-discovery.md)
