### ISSUE TITLE
[CDP] Pre-staging review spot-check

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40221]
## Issue Description
Prior to the official staging review and usability study, we need to review the combined debt portal's UI and document any adjustments needed. 

---
## Tasks
- [x] Review the combined debt portal's staging environment
- [x] Document any necessary adjustments needed prior to usability and staging review 

## Acceptance Criteria
- [x] Any changes have been documented in this ticket
- [x] Any changes have been reviewed with the frontend team and subsequent tickets have been created

**Comment by rileyorr** [comment]
How to access CDP in staging:
- Sign in with test user 228
- Access this link: https://staging.va.gov/manage-debt-and-bills/summary

**Comment by rileyorr** [comment]
# Notes from the pre-staging review check

## Your VA debt and bills 

- [ ] H1 ‘Your VA debt and bill’ to ‘Your VA debt and bills’
- [ ] The chevron in the cards differ between ‘Your VA debt and bills’ and ‘Current debts’ 

## Current debts
- [ ] Add periods in the sentences under ‘Pay by phone’ and ‘Pay by mail’ 
- [ ] While on user 80, the debt card should show an empty state. However, it’s currently showing a 404 alert 
- [ ] User 3 (currently not enrolled in health care) is showing a 404 for both copays and debts

## Debt details 
- [ ] Add periods in the sentences under ‘Pay by phone’ and ‘Pay by mail’
- [ ] ‘Debt letter history’ and ‘Download debt letters’ sections are missing under the $227.42 disability compensation and pension debt

## Debt letter download
- [ ] When expanding to view older letters, the letters are indented. They should be flush with the demand letter links under ‘Latest debt letters’ 
- [ ] Question for Scott: Is the VBMS endpoint resolved so we’re receiving all letters again? 

## Current copay balances
- [ ] Remove ‘Account number:’ from ‘Pay by phone’ accordion
- [ ] Change ‘Your account number:’ to ‘Your account number’ under the ‘Pay by mail’ accordion 
- [ ] Remove ‘Account number:’ and ‘Your facility’s address’ from ‘Pay in person’ accordion 

## Statement 
- [ ] The table is populating strange characters, missing billing reference numbers, and incorrectly showing ‘$0.00’ formatting 
    - [ ] Reference downloaded May 4th statement under user 81’s first facility

## Global
- [ ] Wrapping of breadcrumbs makes it challenging to track what page I'm on. Is there a way to make them not wrap, or at least not as much as they are now?
- [ ] Benefit debt overview + details: pay.va.gov should open in a new tab

**Comment by rileyorr** [comment]
# Notes from our sync

> While on user 80, the debt card should show an empty state. However, it’s currently showing a 404 alert

This is an issue on staging - Brandyn and Andrew will sync up with Scott 

> User 3 (currently not enrolled in health care) is showing a 404 for both copays and debts

We decided to move forward with empty state alerts and are not using the previously existing unenrolled in health care alert 

> ‘Debt letter history’ and ‘Download debt letters’ sections are missing under the $227.42 disability compensation and pension debt

Should be visible on user 81 for Post-9/11 GI Bill debt for housing

**Comment by rileyorr** [comment]
@Dr-Pongo and @OptionSelect are going to break this feedback into separate tickets, so this one is good to close!

**Comment by OptionSelect** [comment]
At this point the necessary work for Front End has been captured into tickets and can be closed from our end! I know there's a part of this for Scott so I'm leaving it open as of now!

**Comment by denisecoveyduc** [comment]
@ScottyRJames Did you capture the BE work and break it out into a new ticket?

**Comment by denisecoveyduc** [comment]
@ScottyRJames so.. sounds to me as though you have no reason to keep this one open and we can close it now?
