### ISSUE TITLE
[CDP] Usability prep

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40222]
## Issue Description
This ticket captures the preparation of the notes spreadsheet that will be used to house our sessions' transcripts and themes. This will help streamline synthesis. Additionally, this ticket capture the preparation of the daily debrief session Mural board and scheduling. 

---
## Tasks
- [x] Set up the note-taking spreadsheet 
- [x] Set up the daily debrief Mural board
- [x] Schedule daily 30 min debrief sessions

## Acceptance Criteria
- [x] The [note-taking spreadsheet](https://docs.google.com/spreadsheets/d/1hLH_hKRr_EaO-wvjvIEupUnNnbuhHl2o/edit?usp=sharing&ouid=100649599312437405482&rtpof=true&sd=true) has been linked in this ticket 
- [x] The daily [Debrief Mural board](https://app.mural.co/invitation/mural/vsa8243/1656082359071?sender=u2d05955ffd6072aabd7a3918&key=06d2fa71-2ead-4277-bf5b-0b0a34f32925) has been linked in this ticket

**Comment by rileyorr** [comment]
Based on this morning's standup, this ticket is going to roll over into the next sprint so Megan and Dave can set up the note spreadsheet and daily debriefs how best works for them. Moving this back to 'Ready'

**Comment by denisecoveyduc** [comment]
Will move this one over to Sprint 76 to discuss with Megan once she has access to GH

**Comment by mgleo** [comment]
- [Note taking spreadsheet](https://docs.google.com/spreadsheets/d/1hLH_hKRr_EaO-wvjvIEupUnNnbuhHl2o/edit?usp=sharing&ouid=100649599312437405482&rtpof=true&sd=true)
- [Debrief Mural board](https://app.mural.co/invitation/mural/vsa8243/1656082359071?sender=u2d05955ffd6072aabd7a3918&key=06d2fa71-2ead-4277-bf5b-0b0a34f32925)
