### ISSUE TITLE
Review vaccine scheduling flow and content 

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#40239]
### Problem
Currently the vaccine flow allows Veterans to schedule only their first dose. We want to change this to allow a Veteran to schedule any/all doses.

### Goal
* Review entire vaccine flow to identify content and screens we'll need to update to make this change
* Note any other potential improvements

### Tasks
- [x] Create [feedback document ](https://www.figma.com/file/35ZyqaRRYG0MCP4g1XjWJJ/Vaccine-flow-review?node-id=0%3A1)
- [ ] Capture design/product feedback
- [ ] Capture content team feedback

### Deliverables
- [ ] Document capturing recommendations

**Comment by outerpress** [comment]
Closing, dupe of https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/41256
