### ISSUE TITLE
NOD: content fix

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40245]
## Description

Update Notice of Disagreement content based on stakeholder final review
<img width="419" alt="Screen Shot 2022-04-20 at 1 18 24 PM" src="https://user-images.githubusercontent.com/136959/164305128-6485b7c6-ec96-43e6-86ca-4ea24806d42c.png">

Add "virtual" in front of "tele-hearing"

## Tasks

- [ ] Update content on hearing pages
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
