### ISSUE TITLE
Deprecate the EKS rolling restart python script in favor of AWS instance refresh on the ASG

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#40247]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@github-name

## Description
Python script has been used for updating the instances that serve as our EKS underlying node groups. It has recently seen some issues that would take time to pick through and conduct root-cause analysis. We should likely scrap it and opt for something a bit easier to digest like AWS instance refresh. This has been tested and confirmed by Kyle and team in the below Slack thread.

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1650476820964229

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Remove the previous way of doing this task
- [ ] Implement new way of leveraging instance refresh

## Acceptance Criteria 
- [ ] Old script no longer exists
- [ ] New pattern is implemented and working

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
