### ISSUE TITLE
Remove info alert from DR landing page and move text and link down + addition to left nav

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40242]
## Issue Description
Stakeholder in OAR (Shireen) would like to add a teaser and link to the comparison R&S page on the DR landing page under "More information and resources" (this is currently highlighted in the info alert). Mikki and I discussed this and decided the best approach is to remove the info alert and fulfill this request. Plus add a link in the left nav to the comparison page.

---
## Tasks
- [x] Remove the info alert on this page: https://www.va.gov/decision-reviews/
- [x] Add teaser and link under "More information and resources"
Link label: **Choosing a decision review option** / Teaser: You can choose from 3 decision review options (Supplemental Claim, Higher-Level Review, or Board Appeal) to continue your case. 
- [x] Add link to the left nav under "More resources"--label should match the name of the comparison page: Choosing a decision review option. 

Left nav links should be in this order:
- Choosing a decision review option
- Frequently asked questions
- Get help with your decision review request 

## Acceptance Criteria
- [x] Page has been updated as outlined above and published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I'm going to make these changes and publish today. Let's chat next week about tracking performance after the link to the comparison page moves down lower on the page.

**Comment by bethpottsVADEPO** [comment]
Randi, this is ready to copyedit. Does the top of the page look ok after I removed the info alert?

![remove DR info alert.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/9f1a18d1-8d65-4717-9900-90ec355cbff0)

![Add 2 new teasers under More info on DR landing page.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/c8381c49-c12e-4174-b967-4dfeb5573f8a)

**Comment by bethpottsVADEPO** [comment]
This is live now.
