### ISSUE TITLE
Determine active status of suspected products

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40256]
## Issue Description
We want to collect some more information on the potential orphan products. Particularly, we are interested in if these are still actively displaying on va.gov's front end in any fashion. The list of potential products is on the "Suspected Products" tab of this sheet: https://docs.google.com/spreadsheets/d/17SJrLx2OTJrZ52E374zO7vbD1_Qej4CFqfGspb_xDBM/edit#gid=0

The manifests are all located in the vets-website repository code. Many of these manifests may have a rootUrl field in them that may point you to where this product should reside on va.gov. If not, a second way to try and locate it would be by using the site's search functionality and combinations of different information in the manifest (app name, etc). 

---
## Tasks
- [x] Attempt to track down each of the products that these manifests belong to on va.gov.
- [x] Create a new column on the "Suspected Products" tab, logging the results of whether or not the product is still active on the site.

## Acceptance Criteria
- [ ] A completely filled out column exists on the "Suspected Products" tab of the above linked spreadsheet depicting the active status of each of these suspected products.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rsmithadhoc** [comment]
**To Do**

- [Update Spreadsheet](https://docs.google.com/spreadsheets/d/17SJrLx2OTJrZ52E374zO7vbD1_Qej4CFqfGspb_xDBM/edit#gid=363551978)
  - [x] 7 - 25
  - [ ] 25 - 50

**Comment by rsmithadhoc** [comment]
This has been updated on the [Suspected Products Sheet](https://docs.google.com/spreadsheets/d/17SJrLx2OTJrZ52E374zO7vbD1_Qej4CFqfGspb_xDBM/edit#gid=363551978) and is ready for review.

- Added **Still Active:** y/n.
- Added **Still Active Root URL:** containing a link for that suspected feature.
- Added **Still Active Description:** containing a general description of what the suspected feature does.
- Some comments were added on individual cells with any special notes or disclaimers for that cell.

**Comment by pjhill** [comment]
Thanks for synthesizing this!
