### ISSUE TITLE
[FE] Page title Focus State triggering on page load

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#40259]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [x] Fill in Documentation
- [ ] Fill in Tasks
- [x] Fill in Acceptance Criteria

## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Related Documentation
- Screenshot attached![Screen Shot 2022-04-20 at 3.46.13 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/dc564bc9-7952-4961-b3c4-2aed7fdca25f)

## Description
When loading application pages on my machine, pages initially load with the Page Title (h1) focus state active. Tested in latest version of Chrome and Safari. This does not happen on the error page h1

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Focus state does not appear unless the header is in focus

**Comment by acrollet** [comment]
This is done intentionally due to [feedback from the accessibility team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26325) - if anything, we should probably ensure that it happens on the error page too...

@brdunfield is your concern around the added styling? I had taken this behavior for granted, so I did a bit of looking around. From [Yale's page on Focus & Keyboard Operability](https://usability.yale.edu/web-accessibility/articles/focus-keyboard-operability):

> Particular care should be used when a page is dynamically updated with AJAX, as the element that contains focus may be destroyed while it has focus. This is never acceptable, as there must always be an existing element with visible focus at all times.
>
> For single page apps, place focus on the &lt;h1&gt; of each new page after it has been rendered.

So it looks like that's the motivation behind setting the focus to the h1, and the following is the motivation for the outline:

> Keyboard focus should always be visible and easy to perceive

Does this address the concern for you? I'm glad to have learned why we're doing this, if nothing else :-)

**Comment by brdunfield** [comment]
Makes sense to me! It's just not a typical thing to see on websites (and also not seen on the rest of the VA site) so I wanted to flag it in case it was not intentional.
But I will close this based on the info you provided!
