### ISSUE TITLE
OAuth Authentication Token Logging - Revocation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#40254]
## Issue Description
The Sign in Service needs to have comprehensive logging and error reporting before going live. This ticket will cover the logging required to cover the creation and management of Access and Refresh tokens. Logs should include the following fields (where applicable):

- audit_id (should be inserted/interpreted from every token)
- session_id
- user_id
- csp
- csp id
- LOA/IAL level
- URI (if applicable)
- client_id
- AT hash?
- RT hash?
- RT parent hash?
- timestamp
- state (from token)
- event_type (create, revoke, etc)
- event_outcome (success or failure)
- redirect_uri (uri used for access token)
- IP address of user
- device fingerprint
- first 5 symbols of AT
- first 5 symbols of RT

---
## Tasks
- [ ] log revoke completion in sign_in_controller
- [ ] log RT revoke

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bramleyjl** [comment]
https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/9685
