### ISSUE TITLE
[FE] [BUG] Authentication form should be submitted when pressing return

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#40262]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [x] Fill in Documentation
- [ ] Fill in Tasks
- [x] Fill in Acceptance Criteria

## User Story
> these should be why the veteran cares, and the veteran gets out of it.

## Description
When filling in the initial auth form (name + SSN last 4), pressing return does not submit the form . Tested in latest version of Google Chrome on MacOS.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Form submits when return is pressed if all fields are valid

**Comment by acrollet** [comment]
thanks for logging this! @loripusey I think this is low-impact on mobile, but worth resolving if/when we send out pre-checkin links via email.

@brdunfield I think the `onloadwff.js` console error is perhaps a red herring introduced by LastPass, are you using it? https://stackoverflow.com/questions/23740187/lastpass-chrome-extension-throwing-error-and-preventing-click-events

**Comment by brdunfield** [comment]
Yes I am using LastPass! I can try disabling it when I get a chance later / tomorrow and seeing if I still get the error. I will update once I have that info!

**Comment by brdunfield** [comment]
Update: Disabling lastpass removed the console error. I will update the ticket and remove that part of the description.

**Comment by brianseek** [comment]
Moving to closed since this is a dev ticket validated in code review

**Comment by loripusey** [comment]
@brianseek do this one go straight to production? If so, I want to create a release note for it
cc: @acrollet

**Comment by acrollet** [comment]
@loripusey this is not yet on production, but should go out with this afternoon's deploy. I just verified the functionality on staging on my desktop and verified that there are no regressions on mobile.

**Comment by loripusey** [comment]
Great, I'll create a release note for it.

**Comment by brianseek** [comment]
Thanks @acrollet!
