### ISSUE TITLE
[CDP] Debt and bill overview alert messages

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#40263]
## Issue Description
Create Alert/Error messages for Debt and bill overview section in Combined Debt Portal. Mockup links listed in **Task** section

## Mockup Screenshots
<details><summary>Debt and bill API error (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/1b9cb35d-afe2-4f3a-a9e1-582a493457f9)

</details>

<details><summary>Debt API error (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/051f7e97-c9e6-496f-9947-3b27b6113b26)

</details>

<details><summary>Bill API error (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/44b9af61-c2a3-46bb-84c1-2083b7eeea11)

</details>

<details><summary>Empty state - no debts or bills (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/35712a76-e11b-4bd4-9433-33cdbd4d3cda)

</details>

<details><summary>Bills, no debts (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/69bccd8a-319c-4554-80e1-c3d499d8c3af)

</details>

<details><summary>Debts, no bills (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/96d41f6c-8eaa-4dbd-95f4-657b3a1510bc)

</details>

---
## Tasks
- [ ] [Alert for both debt and bill 404](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149503318/specification/sitemap)
- [ ] [Debt OR bill 404 ](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149503317/specification/sitemap)
- [ ] [Empty state (no debts or bills)](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149492806/specification/sitemap)
- [ ] [Only debts or only bills](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149492807/specification/sitemap)

## Acceptance Criteria
- [ ] Alerts are populating appropriately 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
