### ISSUE TITLE
GA Training

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#40286]
## Issue Description
With the end of the Search Discovery contract we need to transition all of their work to the analytics teams.

---
## Tasks
- [x] Access Requests
- [x] GTM Implementations
- [x] Support Desk
- [x] Applications (GA, GTM, GCP, Google Marketing Cloud Admin, Domo, Firebase)
- [x] GA Training Deckk
- [x] GA4

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---

**Comment by michelle-dooley** [comment]
We have completed each of these training sessions with the SDI team.
