### ISSUE TITLE
[UX] Update Release Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40314]
## Description
Update various product assets, as necessary, based on changes to the product for post-visit activities.

## Tasks
- [x] Create a new demo video
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [x] Update the Poster
- [x] Update user flow diagrams, as necessary
- [x] Push changes to the appropriate [GitHub files](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/README.md)
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov
- [x] Notify the Contact Center of the changes (follow this [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))
- [x] Notify Training of the changes (Shawn Adams, Cheryl Wills, Farah Ford)

## Acceptance Criteria
- [x] Product Guides are up-to-date (content & screenshots)
- [x] Poster is up-to-date
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [x] R&D articles are up-to-date
- [x] Contact Center is aware of the changes
- [x] Training is aware of the changes

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 for this update, don't forget to do track changes, as the contact center prefers that. You can turn off track changes when you're updating the table of contents, for example.

**Comment by benbrasso-agile6** [comment]
Kelly has drafted the product guide update. I'll review tomorrow. 

Still waiting for Zach to do the user flow, so we can add to the guide. Depending on priorities, I could take that task, if needed.

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 we will want to include a video as part of that submission to the contact center. Has anyone worked on that yet?  

Also, have we included the updated workflow diagram in the product guide? https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/47488

**Comment by benbrasso-agile6** [comment]
We have a template for the video. Happy to provide some help.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Ohhh yes! A template would be great! I'll throw something on the calendar for tomorrow or Thursday for us so you can share

**Comment by benbrasso-agile6** [comment]
Also, I believe we have 2-3 error messages associated with travel reimbursement. Can we add those into either section 4 or 5 in the product guide?

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Thank you - these are great!!

**Comment by benbrasso-agile6** [comment]
We will need to submit it as an acceptable video format as well as a transcript of the audio. (Here are some [additional instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/product-management/demo-video-creation-process.md).) I think I'm not understanding how the powerpoint supports these two things. Or, is the powerpoint just serving as the script, and now you're planning to record the demo in zoom? 

Maybe we can connect on this to iron it out.

**Comment by kellysmith1008** [comment]
Hey @benbrasso-agile6 Yep, I'm converting the power point into a .mov video now but it takes awhile to compress. I'll add it here when done. It does include captions with it. If this format doesn't work, I can re-record it in zoom, no problem

**Comment by kellysmith1008** [comment]
This ticket is complete
