### ISSUE TITLE
[UX] Update Release Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40313]
## Description
Update various product assets, as necessary, based on changes to the product for telephone appointments.

## Tasks
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [ ] Update the Poster
- [ ] Update user flow diagrams, as necessary
- [ ] Push changes to the appropriate GitHub files
- [ ] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov
- [ ] Notify the Contact Center of the changes (follow this [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))
- [ ] Notify Training of the changes (Shawn Adams, Cheryl Wills, Farah Ford)

## Acceptance Criteria
- [ ] Product Guides are up-to-date (content & screenshots)
- [ ] Poster is up-to-date
- [ ] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [ ] R&D articles are up-to-date
- [ ] Contact Center is aware of the changes
- [ ] Training is aware of the changes

**Comment by benbrasso-agile6** [comment]
@loripusey what's the general ETA on telephone release ?

**Comment by loripusey** [comment]
I hope to test and release it by the end of the sprint that starts 7/27, pending agreement by the team during Sprint Planning 
@benbrasso-agile6 @acrollet

**Comment by benbrasso-agile6** [comment]
@loripusey I would recommend closing this ticket. We can keep track of these updates in the Type of Care & Doctor Name release artifacts ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42032

Just a bit confusing since they're happening at the same time. 

Although, up to you.

**Comment by loripusey** [comment]
ok, closing.
