### ISSUE TITLE
Swap in the <va-pagination> component on View Payments

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40325]
# Background
Now that the `<va-pagination>` component is being used in production over the `<Pagination>` React component, we need to swap the pagination component out on the View Payments app as the pagination component will be deprecated at some point.

## Tasks
- [x] Swap the `<va-pagination>` component for the `<Pagination>` React component on View Payments
- [x] Ensure all unit and e2e tests still pass
- [x] Submit a PR for review

## Acceptance criteria
- [x] The `<Pagination>` component has been swapped out for the `<va-pagination>` component
- [x] A PR has been submitted for review
