### ISSUE TITLE
Move view payments app to <va-table> component

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40323]
# Background
Now that the `<va-table>` component is being used in providtion over the `<Table>` React component, we need to swap the table component out on the View Payments app as the table component will be deprecated at some point.

## Tasks
- [ ] Swap the `<va-table>` component for the `<Table>` React component on View Payments
- [ ] Ensure all unit and e2e tests still pass
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The `<Table>` component has been swapped out for the `<va-table>` component
- [ ] A PR has been submitted for review

**Comment by jerekshoe** [comment]
We are having issues with getting the `va-table` and `va-pagination` to play nicely together. Until this is resolved, we will need to hold on this

**Comment by jerekshoe** [comment]
This was completed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24622)
