### ISSUE TITLE
[Design] | Auth-Profile | Direct Deposit | Create Reporting Template for Internal UAT

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40334]
### Background

When we conduct internal UAT for initiatives, we should have a template to use to capture findings and issues.

### Tasks

- [x] Draft a template for use with internal UAT
- [ ] Review with Samara and finalize

### Acceptance Criteria

- [ ] Approved template posted in Github
- [ ] Test drive with xx initiative

**Comment by SKasimow** [comment]
@andaleliz  - draft for UAT template. Please send me any questions/feedback and feel free to edit! Thanks!!

**Comment by andaleliz** [comment]
I started a [draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/uat-findings-template.md) and am getting it reviewed by a couple of other UX leads - I think this will be useful for more than just our team. I learned today that Platform is working on adding a UAT section to their research docs, so they can incorporate our template for more consistency across the board.

**Comment by Samara-Strauss** [comment]
This is great!! Thank you, Liz!!

I personally don't need as detailed of a breakdown of the different groups as you have outlined; I just want to see a list of who you talked to, and I would assumed you did not talk to anyone from groups/demographics not included. If you feel strongly about leaving this, that's OK, but I think this would be more useful for generative research or usability testing than UAT given that UAT is more about making sure the backend works correctly than it is about making sure the tool works for different user types.

**Comment by andaleliz** [comment]
Thanks for being flexible about leaving in the participant criteria. There are times where we make design changes post-usability testing, that aren’t validated via another study before launch. UAT is our next opportunity to put it in front of users. While the focus of UAT is certainly to verify functionality, there are times where we have usability points to look out for as a gut check on the things we iterated on between usability and UAT. In those cases, I think it's especially important to capture who we talked to.

Also, in general, the research ops group is making efforts to understand who we are and aren't talking to across the board, so this data will be helpful for that down the road.
