### ISSUE TITLE
Edit/Refine Guidelines

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40348]
## Issue Description
Edit/Refine Guidelines

---
## Tasks
- [x] Edit/Refine Guidelines (Nicole)
- [x] Edit/Refine Guidelines (Taylor)
- [x] Edit/Refine Guidelines (Dan)
- [x] Edit/Refine Guidelines (Bryan)

## Acceptance Criteria
- [ ] Finalized version of Guidelines
- [ ] Finalized version of supporting explanations
