### ISSUE TITLE
Draft SD guidelines

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40345]
## Issue Description
Draft SD guidelines

---
## Tasks
- [x] First draft of SD guidelines (Bryan)
- [x] Edit guidelines (Dan)
- [x] Edit guidelines (Taylor)
- [x] Edit guidelines (Nicole)

## Acceptance Criteria
- [ ] full draft of SD Guidelines
