### ISSUE TITLE
Publicize the Quarterly Customer Satisfaction survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40342]
## Issue Description
Share survey's availability in Slack, ToT, and relevant group discussions.

---
## Tasks
- [x] Share Survey in Slack
- [x] Share Survey in ToT

## Acceptance Criteria
- [x] Survey posted in Slack
- [x] Survey posted in ToT slides for active period
