### ISSUE TITLE
Publicize/socialize guidelines 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40355]
## Issue Description
Publicize/socialize guidelines so that Platform teams are aware and understand this new resource

channels:
Design
Technical facing
Platform

---
## Tasks
- [x] Post guidelines in Slack  (Nicole)
- [x] Publicize guidelines in ToT  (Bryan)

## Acceptance Criteria
- [x] Guidelines posted and discussed in various channels
