### ISSUE TITLE
Q3 Quarterly planning:  Work session to define Objectives

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#40356]
## Issue Description
Q3 Quarterly planning

Brainstorm Objectives for quarter:  https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1654693878439/bb289fef239f43ccd7f1eb23ae0a0438a929f10d?sender=u4397b715dc3690a417b71483

Define next Quarter's intended work using [quarterly planning playbook](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1891303483/Product+Management+on+Platform#Quarterly-Planning-Playbook)

---
## Tasks
- [x] Add objective ideas to mural 
- [x] Team work session to define Objectives for quarter 
- [x] Product Owner approves Objectives.

## Acceptance Criteria
- [x] Objectives set in Mural
