### ISSUE TITLE
SiP menu performance

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40372]
## Description

While testing a form submission with an endpoint that isn't set up locally, the `pageList` passed to the `SaveInProgressDevModal` is an empty array. This currently causes a JS error. While attempting to fix it, it was noted that the `useEffect` would then get called repeatedly since it updates state. A fix would be to memoize the `getAvailablePaths` function, and/or add more restrictions on when it's called.

## Tasks

- [ ] Fix JS error
- [ ] Optimize `getAvailablePaths` calls
- [ ] Add tests

## Definition of done

- [ ] Fix JS error
- [ ] All tests passing
