### ISSUE TITLE
NOD: Fix contact page content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40373]
## Description

The Notice of Disagreement contact information page refers to the Higher-Level Review form. Replace it with "appeal".

## Tasks

- [ ] Fix content
- [ ] Update tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
