### ISSUE TITLE
Add instructions for tracking components or patterns that need to be updated

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#40385]
## User Story
As a Governance team member, I want to be able to know if an experimental design component/pattern is in an upcoming review, so that I can provide accurate feedback.

Assignee: @allison0034 
Peer Reviewer: @sterkenburgsara 

## Description
We would like to be able to track design patterns or components that come up in design intent, midpoint or staging reviews that need to be updated. For example, the Start a new application button in the form system should be a link. After speaking with DSC we need to add labels and assign the ticket to Carol Wong

Add these labels: design-system-update, vsp-design-system-team, component-update, experimental_design
Assign ticket to Carol Wong

## Impacted Artifacts
[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review)

## Tasks

- [x] Confirm with Allison which tickets we'll be adding labels to (experimental_design, design-system-update, vsp-design-design-team, component-update)
- [x] Document instructions for Governance team to follow if/when it is recognized that a design pattern or component is in need of updating. Create draft page.
- [x] Draft is peer reviewed and approved by Governance team member
- [x] Add instructions to [How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent), [How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review) and [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review), where appropriate

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria

- [x] The Governance team will how notify Design System Team when an existing component or pattern needs to be updated
- [x] Governance team will be able to track components or patterns that have these labels

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 I am getting this ticket ready for @seanasewell to work on. Can you please confirm which tickets you think we should be adding the labels (design-system-update, vsp-design-design-team, component-update) to? I'm not sure it makes sense for us to add to the Collab Cycle Request ticket. 

Open to discussing this in person if easier.

**Comment by allison0034** [comment]
@shiragoodman I think in our feedback ticket will be good. Also, can you make a task to double check with Carol if those labels still apply? For some reason I dont think I could find one the last time I had an experimental design in my feedback.

**Comment by shiragoodman** [comment]
Thanks @allison0034 . The feedback ticket at Midpoint or the issue ticket at Staging does make more sense.

@caw310 tagging you in for reference. See Allison's comment above. Are these still the labels you'd like us to use to inform your team of patterns/components in need of an update?

**Comment by caw310** [comment]
@shiragoodman @allison0034 , I would say use these two labels "vsp-design-design-team, component-update" and assign the ticket to me to review and prioritize.  Thanks!

**Comment by shiragoodman** [comment]
thanks @caw310 ! I will update the ticket to reflect your preferred approach.

**Comment by caw310** [comment]
@shiragoodman , no it's "vsp-design-system-team"

**Comment by shiragoodman** [comment]
thats what I thought - thank you!

**Comment by shiragoodman** [comment]
@humancompanion-usds this came up in our Refinement meeting today. Would this still be valuable for you and DST? Let me know if you'd like to discuss further.

**Comment by humancompanion-usds** [comment]
Yes, this would be helpful. While we may not be able to get to some of these requests for a bit until we're through some big initiatives, it is important that we keep the Design and Forms Systems up-to-date and fix discrepancies. Otherwise we rely on the Design System Team to audit for issues like this and that strikes me as perhaps less reliable than catching things as they come through CollabCycle.

**Comment by shiragoodman** [comment]
@allison please take a look. review what you had written previously and fill in the missing fields.

**Comment by allison0034** [comment]
Hi @caw310 , I am revisiting this ticket for tracking experimental design components/patterns that come thru the collab cycle. Can you confirm the following is still correct?

Add these labels: design-system-update, vsp-design-design-team, component-update
Assign ticket to Carol Wong

**Comment by caw310** [comment]
@allison0034 yes, those are the correct labels. If it is an experimental design request that was created in the vets-designs-system-documentation repo, please add the "experimental_design" label as well.  Thanks!

**Comment by allison0034** [comment]
@sterkenburgsara this is a small change in the DI document only. Can you please review and if you approve I will change MP and Staging. Step 5 is new.

[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)

**Comment by sterkenburgsara** [comment]
@allison0034 Two questions: is vsp-design-design-system correct? with the two "design"s in there? Also, how would one know there is an experimental design component at play? Should we include instructions for how to verify that?

**Comment by caw310** [comment]
@sterkenburgsara the correct label for DST is "vsp-design-system-team'.  I'm the PM for DST and that is how tickets will appear on our board and that I will see them. Thanks.

**Comment by sterkenburgsara** [comment]
@allison0034 Carol mentioned above to also add "experimental_design" - I don't see that one as an existing label. Do we need to add? cc @caw310

**Comment by allison0034** [comment]
@sterkenburgsara yes, I updated the draft

**Comment by caw310** [comment]
@sterkenburgsara , here is information on contributing to the design system. https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns
For experimental design requests, use this template - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=vsp-design-system-team%2C+experimental_design&template=3_experimental_design_request.md&title=Experimental+Design+%5Bcomponent+or+pattern+name%5D

That should automatically added the correct labels and assign it to me.

**Comment by sterkenburgsara** [comment]
@allison0034 looks good to me! Go ahead and close.
