### ISSUE TITLE
Create Documentation for the Product List for VFS Teams

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#40382]
## Issue Description
1. Platform will need documentation -- platform-centric overview, how-to use the machine readable to automate, how-to access human-readable version
2. VFS Teams will need documentation to understand the Product List, it's use, and guidelines for how to update.

Joe's deep thoughts that should be in docs --
* Propose a process for schema changes

---
## Tasks
- [x] Block out documentation - @pjhill , @CBonade 
- [x] Outline documentation for review - @CBonade 
- [x] Draft full documentation for review - @rjohnson2011 
- [ ] Solicit feedback - @JoeTice 
- [ ] Revise based on feedback - @rjohnson2011 
- [ ] Publish final document - @rjohnson2011 

## Acceptance Criteria
- [ ] Document is written and has been reviewed and updated based on feedback

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory Outline here for the VSP Product Directory Overview.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/Updating+the+VA.gov+Product+Directory Outline here for the Instructions to make changes to the list.

**Comment by rjohnson2011** [comment]
Touched base with Curt on Friday and received the handoff of the outline documentation. Starting the first pass of the documentation draft today.

**Comment by rjohnson2011** [comment]
Filled out Column Glossary to include the schema, which includes product names, data types, and definitions.

**Comment by rjohnson2011** [comment]
Filled out the section for 'Making Changes to the List' as well as added a table of contents and expanding on the Intro. https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation

Planning on creating a Feature Request Template on Github today, which users can utilize to make changes to the VAPD or request the Human Readable List. Will reach out to the team to request more information about where the Machine & Human Readable lists live.

**Comment by rjohnson2011** [comment]
Created two Github Product Directory templates -
1. Feature Request - Changes
2. Human Readable List
https://github.com/department-of-veterans-affairs/product-directory/pull/40/files

Doing final pass on the draft documentation and will hand that over for review this afternoon.

**Comment by rjohnson2011** [comment]
@JoeTice The Product Directory documentation is ready for review. https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation

Please let me know of any changes to be made for the final draft.

**Comment by JoeTice** [comment]
In reviewing, I believe this version is good, however some larger changes have been made that may require more involved modifications to this documentation. Will review w/ Peter & Curt tomorrow and determine next steps.

**Comment by pjhill** [comment]
We have a newer ticket to review and update the documentation that we already created (probably as part of this ticket). Marking this as closed for the first iteration.
