### ISSUE TITLE
Re-name default branch in Design System Team-owned repos from master to main

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40395]
## Issue Description
We'd like to update our default branches for the component-library and vets-design-system-documentation repositories from `master` to `main`.

### Technical notes
This might be a little tricky to do, especially for the component-library repo as there are several places where the `master` branch is used to direct build and deployment tasks.

---
## Tasks
For each repository:
- [ ] Update default branch to `main`
- [ ] Update any build or deploy tasks that reference the `master` branch by name
- [ ] Update any documentation (READMEs) that reference the `master` branch by name

## Acceptance Criteria
- [ ] The default branch for each repository has been renamed to `main`
- [ ] All documentation has been updated to reference the `main` branch name
- [ ] All build and deploy tasks are functioning correctly
