### ISSUE TITLE
Create Research Readout

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#40409]
## Issue Description
At the request of Mike Chelen, we should create a readout of the research that we conducted in support of the creation of a Product List
---
## Tasks
- [x] Research requirements for research readouts
- [x] Draft research readout
- [x] Have team review and update as needed
- [x] Conduct readout in office hours and/or sprint demo

## Acceptance Criteria
- [x] Conduct readout

**Comment by JoeTice** [comment]
Draft research readout is being prepared at this link: https://docs.google.com/presentation/d/1bv4eO1WhVqo7uPiVpYxG58S-WHUmk8Ahlq5EvjCxe_g/edit#slide=id.g1259ee31656_0_20

**Comment by JoeTice** [comment]
Readout was conducted on 5/3/22
