### ISSUE TITLE
Coordinate Product List meeting w/ Platform CMS team

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#40407]
## Issue Description
We need to coordinate a meeting with the Platform CMS team to discuss and understand their needs so that we can make any required changes to our product list schema.

---
## Tasks
- [x] Schedule a time with Jess Alexander
- [x] Discuss the requests and determine what attributes are within scope/doable

## Acceptance Criteria
- [x] We have agreed which requested attributes will be included in the Product List

**Comment by JoeTice** [comment]
Meeting conducted and questions answer - final results documented here:
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1649377300526/ed440220603d6afe04eb9bd7a8b8b8f2addc6a94?sender=uc4d00ea50beebdfad05a4846
