### ISSUE TITLE
Staging Review | Auth-Profile | Personal Info Revision 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40404]
# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following:
- [x] Staging URL and staging test-user information

- [VA.gov Staging Profile](https://staging.va.gov/profile/personal-information)

Note: If you are testing you can use one of the accounts from the Staging Accounts doc. If you "burn" any staging accounts (make changes and save), please add which account you used to [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile-personal-information.md) so we can keep track.

- [x] Product outline [is here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information)
 
  

- [x] Release plan with the "Planning" sections completed 
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/product/release-plan.md)

 

### Content artifacts 

- [x] Your product’s content source of truth [Use Cases w/ Design links](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/test-accounts-and-test-cases.md)
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
- #34290 and #34247 (will be done post 100% launch)

### QA artifacts

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3196) (with Results)
- Test Cases:
  - [LOA1](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=149)
  - [Personal Information](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=161)
  - [Contact Information](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=4398)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/331) 
- [x] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/333) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [x] List of known issues (Ticket #41526)
     

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Confirming that the Staging Review meeting is scheduled for 5/24 at 11:30am

**Comment by tlei123** [comment]
@ddzz , QA-artifact links now updated/added above, in main description.  cc @SKasimow @shiragoodman

**Comment by CherylEvans** [comment]
No Content FB, although I did have few questions. 
I was reviewing the Content Artifacts > Use Cases w/Design links > Personal Information page > Preferred Name it says: "Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA."  This sentence really is somewhat confusing to me.  It sounds as if the user is physically coming in to the VA.  Is this the case?  Or does it refer to logging into the VA website?  My thought is that it is referring to the former.  
Also, under Content artifacts, these 2 tickets are referenced as having relevant static page updates: #34290  and 34247.  #34290 has a prototype mockup link and on Personal Information page > Preferred Name it says: "Edit your profile to add a preferred name." as opposed to the verbiage I referred to above.  Not sure which of these versions is to be the final version. 
Everything looks quite good!

**Comment by SKasimow** [comment]
Hi @CherylEvans - thanks for your feedback! Responses in-line:

> "Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA." This sentence really is somewhat confusing to me. It sounds as if the user is physically coming in to the VA. Is this the case? Or does it refer to logging into the VA website? My thought is that it is referring to the former.

Yes, it refers to the Veteran going to a VA site/facility. We can test this during our UAT and see if it is causes confusion though.

The staging ticket with links to Sketch files are the final versions. The static page updates are something we plan to do post-launch and just haven't been updated yet. Sorry for the confusion.

Thanks, Sharon

cc: @Samara-Strauss @cgednalske

**Comment by allison0034** [comment]
No design feedback, thank you

**Comment by CherylEvans** [comment]
@SKasimow Thank you so much for your very timely response Sharon. :-)

**Comment by SKasimow** [comment]
Closing
