### ISSUE TITLE
Research testing authenticated API calls from vets-api to Lighthouse

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#40402]
## Issue Description
The setup to test authenticated API calls is more complex, since such calls require an Authorization header with the bearer token of an authenticated user. Obtaining such a token requires manually signing in either from a browser session or from a mobile app, which makes creating an automated test suite quite complicated. 

The goal of this research ticket is to determine the best approach to test these types of authenticated API calls. 

---
## Tasks
- [ ] Research browser-based authentication using VA test user accounts
- [ ] Research mechanism by which the backend vets-api calls to Lighthouse are made (e.g. using client credentials grant)
- [ ] Create test plan to formally test vets-api to LH calls mimicking existing vets-api backend code

## Acceptance Criteria
- [ ] General testability of authenticated vets-api-to-LH API calls is established
- [ ] Testing plan for these calls has been created (this could be a manual testing plan, if other options were discounted)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Closing as out of scope.
