### ISSUE TITLE
Review new Transferred entitlement (TOE) page and other changes with stakeholders

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#40413]
## Issue Description

Met with stakeholders then followed up with this email:

From: Potts, Beth
 Sent: Monday, May 9, 2022 4:44 PM
 To: Hurley, Tammy S. (she/her/hers)(she/they) <tammy.hurley1@va.gov>; Quattrini, Cinda, VBAVACO <cinda.quattrini@va.gov>
 Cc: Laura Willwerth <l.willwerth@bloomworks.digital>; r.hecht@bloomworks.digital
 Subject: 4 webpages to review (connected to the 1990e work)

Hi Tammy and Cinda,
Thanks for the meeting last week! I appreciate all your feedback on that call, and I wanted to summarize here the pages that I’ll need your SME review on. Please forward to any other Education Service SMEs who should have eyes on this too. You’ll need to be on the VA network for these links to work:

1/ Transferred education benefits for family members (This will be a new webpage. It has the entry point to the 1990e under the section called “How do I apply?”)

2/ Transfer your Post-9/11 GI Bill benefits (This shows changes to the existing webpage. Please review the whole page—see bulleted list here for the highlights of what changed.)
- Added a new text link in the blue box taking users to the new page called Transferred education benefits for family members. This link doesn’t work in preview, but it will be functional once the new page mentioned above is live.
- Reordered information on the page to move the section with the main call to action for this page up higher: “How do I transfer my benefits?” And removed the call to action for family members since we’ll have that new text link in the blue box.
- Made plain language improvements to the section called “When can my qualified dependents use the transferred benefits?”
- Added a Q&A for revoking the TOE: “Can I cancel or change my transferred benefits?” (this info is currently buried on the page, and now it has its own Q&A)

3/ VA education benefits for survivors and dependents (This shows changes to the existing webpage. Please review the whole page—see bulleted list here for the highlights of what changed.)
- Revised the intro paragraph so that there’s equal weight given to DEA and Fry.
- Revised the text in the blue box to incorporate info from down lower on the page about DEA and Fry.
- Added a Q&A titled “Can I use both DEA and the Fry Scholarship?” that includes a link over to a new webpage that compares the 2.
- Added a Q&A titled “Can I use transferred benefits?” that includes a link to the new webpage for family members who want to use transferred benefits.
- Removed the chart. This content will become a new webpage (see below, No. 4). The chart was not 508 compliant, so I needed to present it in another way—not in a chart.

4/ Compare DEA and Fry Scholarship benefits for family members (This will be a new webpage. The info came from the existing live page called “VA education benefits for survivors and dependents.”)

Please let me know if you see any factual inaccuracies. You can email me feedback or we could also get on a call and I could take your feedback verbally. Whichever works for you!

Thanks so much for your time,
Beth

---
## Tasks
- [x] Meet with stakeholders to show them the new tool landing page we created so there'd be a logical entry point to direct users to the TOE.
- [x] Explain the related work we did: new R&S page, edits to other pages
- [x] Discuss how much should change with the existing Transfer page we have in tier 1.
- [x] Send summary email to stakeholders.
- [x] Make necessary edits based on stakeholder feedback.
- [x] Respond to their feedback about these 4 pages and ask them to review with preview links again.
- [x] @RLHecht Once we have approval, we'll need tickets for the next steps: One for copyediting and completing the prepub checklist but HOLD until the date when TOE is going live / one for publishing on the right date and implementing the left nav addition.
- [x] Beth to communicate with Alex Ferzola that he can take this new tool landing page to the CC staging review to show the entry point and to get CC accessibility and design feedback. No need for content feedback since Beth created this page and it went through the full sitewide content editorial process. 

## Acceptance Criteria
- [x] Stakeholder sign off of all the above. Then open a ticket to copyedit, run through pre-pub checklist, and publish.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
Uploading the stakeholder feedback here.
[https://app.zenhub.com/files/133843125/60572b59-868e-42e2-b8a9-67466bf0453f/download](https://app.zenhub.com/files/133843125/60572b59-868e-42e2-b8a9-67466bf0453f/download)

[https://app.zenhub.com/files/133843125/f9fe4e65-bd9c-4223-b258-dfc0aae8f6b0/download](https://app.zenhub.com/files/133843125/f9fe4e65-bd9c-4223-b258-dfc0aae8f6b0/download)
