### ISSUE TITLE
[Packer] GHA Runner Conflict with GTK2 vs GTK3

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#40421]
## Description
The GitHub Action Runner is in a situation where it needs libgtk2 but during package upgrades it's upgrading to gtk3 and causes the AMI build to fail

## Background/context 
- This is part of updating the User Data to help mitigate the issue where we had GitHub Action Runners that were not correctly deployed and Vets-API CI/CD stalled.

---
## Tasks
- [ ] Update Packer build
- [ ] Build new GitHub Action Runner for Vets-API

## Acceptance Criteria 
- [ ] AMI tests that previously failed due to missing gtk2 now pass

**Comment by ph-One** [comment]
Closing in favor of https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/40529
