### ISSUE TITLE
Implement JsonAPI in Platform console API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#40448]
**AC**
-----------------
Add JSON::API to platform console API using [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer)

## Tasks
- [ ] Update routes with new version (v1)
- [x] #41271
- [x] #41274
- [ ] Update and add tests

## Resources (`api/v1`)
- [ ]  `/teams`
- [ ]  `/team/apps` 
- [ ]  `/team/deployments`
- [ ]  `/team/app/deploy_pull_requests`
- [ ]  `/team/app/pull_requests`
- [ ]  `/team/app/workflows`
- [ ]  `/team/app/workflow_runs`
- [ ]  `/team/app/workflow_run_jobs`
- [ ]  `/team/app/deploys`
- [ ]  `/team/app/deploy_jobs`
- [ ]  `/team/app/deploy_runs`
- [ ]  `/team/app/deploy_run_jobs`

**How will we know we are done?**
---------------------------------
Each resource returns a JSON::API serialized object.
