### ISSUE TITLE
Erica onboarding: platform and collab cycle familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40445]
## Background

As part of onboarding, Erica should start familiarizing herself with the platform and collaboration cycle.

## Tasks
- [x] Read through [platform background](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) and [orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] Read through [collab cycle documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [x] Attend orientation collab cycle/platform practice area info sessions (or plan to join as schedule permits over next few weeks)
- [x] Shadow AJ on first collab cycle tickets

**Comment by ericasauv09** [comment]
scheduled all of my orientation sessions but will not be able to attend most until June
