### ISSUE TITLE
Add content from NADL PDF to VA.gov pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40466]
## Issue Description
VA stakeholder Raleigh Contreras asked us to add a PDF to our [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. Because PDFs are not accessible and not always mobile-friendly, we try not to link to them and instead incorporate the content onto our pages.

The content team needs to assess the information in this PDF and determine what needs to be added to our pages and where or if a new page needs to be created. Once we've assessed how to proceed we will give Beth our recommendations. Once OK'ed we'll write and edit the content and send Raleigh preview links of the new information or pages before publishing. 

## Tasks
- [ ] Assess stakeholder request and determine next steps
- [ ] Review recommendation (Beth)
- [ ] Create new content
- [ ] Edit (Laura)
- [ ] Final review (Beth)
- [ ] Send to stakeholder for review 
- [ ] Final copyedit and publish

## Acceptance Criteria
- [ ] Content from NADL PDF is live on VA.gov

**Comment by RLHecht** [comment]
Update: Will email Raleigh to follow up.

**Comment by RLHecht** [comment]
Moving to blocked until Raleigh gets back to us.
