### ISSUE TITLE
Integrate Sidekiq UI into the Console UI

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#40468]
## User Story

_As a user of the console I would like to be able to leverage SSO to access debugging applications such as Sidekiq UI or PgHero_

## Expected Behavior

_The precise behavior is yet to be defined by console UI, this ticket is a placeholder for the backend work that will be needed to support the strategy that the console team decides to leverage (see https://github.com/department-of-veterans-affairs/platform-console-ui/issues/201). Currently the services leverages warden to control access to the sidekiq UI, if we decide to go with an authentication mechanism other than GH auth we will need to tweak warden to account for the new auth schema._

## Acceptance Criteria

- [x] _Backend changes required to support SSO are implemented_
- [ ] _Documentation is updated as required._

NOTE: this issue is not blocked by console UI's work per-say, it's more of a mutual dependence. Currently waiting on a the requirements for this integration. Once those have been identified, we may want to consider switching the blocked/blocking relationship.

**Comment by ewilson-adhoc** [comment]
@lhelmer do you have objections to us converting this into an epic which will cover the backend work that we need to go for this integration?

**Comment by jchapin** [comment]
I have added the link to the dev environment alongside the current production installation on the api. host.

![Screen Shot 2022-07-29 at 10 58 31 AM](https://user-images.githubusercontent.com/116142/181787765-7b221944-3c2a-4cf8-b31c-83cbedf6c638.png)

**Comment by jchapin** [comment]
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/10430

This is probably the last item we'll accomplish. The production environment will be Q4 or beyond.
