### ISSUE TITLE
Streamline Qualitative Medallia Data Sharing

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#40474]
## Issue Description
_Due to potential PII/PHI in free form text field responses on Medallia surveys, we cannot display text field responses in DOMO. This makes is hard for us to automate. This effort is to figure out the best near term path to streamline sharing this data and implement it._

---
## Tasks
- [x] _Ideate solutions bases on desired outcome_
- [x] _Document best solution in Confluence_
- [x] _Implement solution_
- [x] _Create training for CC team_

## Acceptance Criteria
- [x] _Sharing qualitative Medallia data is more efficient / streamlined_
- [x] _Training on the (above) process is available to the CC team_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
