### ISSUE TITLE
Error Codes / HRC Help Desk Training Module

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#40476]
## Issue Description
_In an ongoing effort to provide more training for Tier 1 to better help Veterans, we are creating training modules for key areas of consistent support requests_

---
## Tasks
- [ ] _Create error codes / HRC help desk training module_
- [ ] _Deliver error codes / HRC help desk  training module to VEO_

## Acceptance Criteria
- [ ] _Error codes / HRC help desk  training module is created_
- [ ] _Error codes / HRC help desk  training module is delivered to VEO_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
