### ISSUE TITLE
Overdue Case Resolution Swarm

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#40477]
## Issue Description
_With our goal of having zero overdue cases, we have to catch up with a concerted effort to resolve all overdue cases._

---
## Tasks
- [ ] _Focus on overdue cases, primarily tier 3_
- [ ] _Resolve X overdue cases_

## Acceptance Criteria
- [ ] _X overdue cases are resolved and closed_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
plan created, shared with, and approved by JW.

From: Daniels, Kimberley N. 
Sent: Wednesday, July 6, 2022 4:10 PM
To: Woodman, Jason M. (Oddball, Inc.) <Jason.Woodman@va.gov>; jason.woodman@oddball.io
Cc: Pearson, Ervin D. (Oddball, Inc.) <Ervin.Pearson1@va.gov>; Manalo, Michael T. (Oddball, Inc.) <Michael.Manalo@va.gov>; Tarlow, Steven R. (Oddball, Inc.) <Steven.Tarlow@va.gov>; Arcangel, Aubrey C. (Oddball, Inc.) <Aubrey.Arcangel1@va.gov>
Subject: Tier 3 data
Importance: High

Good Afternoon Jason,

Attached is the most up to date case load.  Please review plan and details below and provide your thoughts on how we should move forward/approvals.

ALL suggestions are welcome, I’m pretty sure I didn’t cover everything! 😊

Cases on Sheet 1 tab:

•	First 66 ‘In Progress’ or ‘Follow- up’ status
o	Most are in ZH
•	369 label Tier 3 in some form
o	These have all been spot checked by me for tier 3 routing

Cases on Tier 2 Extra tab:

•	These would need to be reviewed to find their home.
o	Cannot base on case type/category
o	Cannot base on subject line
•	ANY cases mentioning the following is NOT tier 3 (benefits related only):
o	AccessVA
o	Centralized Mail Portal
o	Direct Upload Tool
o	Email issues
o	Errors:
	102
	103
	104
	106
o	Incorrect military information
o	Mismatched information

Proposal:

•	Close all cases on Sheet 1 tab
o	Discuss the ZH cases (not sure if these should be closed or not, leaning towards yes)
	Report would be kept for historical and tracking purposes
•	Send out benefits template to ALL
•	Review all cases on Tier 2 extra tab for appropriate labeling/routing
o	Close and send out template for those cases
•	Any responses will be added to case notes in SF
•	Tier 3 team will be notified
o	Option in SF to notify of case via email
	This may or may not be a viable option
o	Reports could help with this OR be the solution


Things to Note:

•	Should we direct cases to AVA
o	What are the pros/cons
•	Current inbox needs rules established for this set of cases
•	Case owner can be updated in Salesforce 
o	Route to a Tier 3 team member
o	This may cut down on bottlenecking
•	See if there is an option to have ZH tickets created automatically via Salesforce
If we decide against AVA
