### ISSUE TITLE
[BE] | **Discovery** | Profile | Migrate from eMIS  to VA Profile for Military Info

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40479]
### Background

Currently we pull in Military info from eMIS. However, we need to switch over to VA Profile for this information as eMIS will be sunset in the near future.

### Tasks

- [x] Meet with VA Profile to ask following questions:
  - [x] Where does the new Military API endpoint reside?  What is the URL?  Request Swagger Docs.
  - [x] Is the request changing (ie - parameters, path, etc)?
  - [x] Is the response changing (ie - schema, error messages, etc)?
- [x] Create and estimate BE ticket for development

### Acceptance Criteria

- [x] Document new API and any changes from existing (swagger docs).
- [x] Create new BE ticket with estimate

**Comment by SKasimow** [comment]
@tpharrison - I started a ticket for this; could we grab a few minutes to talk through what else should be included? Or if easier, feel free to just add/edit the ticket! Thanks, Sharon

**Comment by tpharrison** [comment]
Hey @SKasimow - let me know when you want to meet to discuss this.

**Comment by Samara-Strauss** [comment]
Great! Wonderful. Sorry my email didn't yield a response. I'm glad Ian was able to help.

**Comment by tpharrison** [comment]
Not your fault that nobody responded - thanks for reaching out multiple times.  Ian has already done some work on the military info so he should be able to answer any questions that come up.

**Comment by tpharrison** [comment]
@SKasimow @Samara-Strauss - Ian from VA Profile has sent me the swagger docs for the military info.  I am reviewing it and will create and estimate tickets for the work that needs to be done.
