### ISSUE TITLE
Determine which pages to add Space Force to 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40484]
## Issue Description
Now that Space Force is a branch of service we need to add it on pages where we list the others. 

According to stakeholder Eric Robinson, Space Force is organized under the Air Force, in the same manner that the Marine Corps in under the Navy. 

The contact info is the same as the Air Force so we don't need to update this information. 

We need to look at everywhere we list Air Force to determine if we should also include Space Force. Before we do the work in Drupal, we'll provide a list to Beth with the pages where we think it should be added. Once she gives us the OK we can do the Drupal work.

This ticket is for reviewing the list and submitting to Beth.

## Tasks
- [x] Ask PW to do a search for pages where service branches are listed (Randi)
- [ ] Determine pages to add Space Force to
- [ ] Send to Beth in new ticket 

## Acceptance Criteria
- [ ] List of pages to add Space Force to is created

**Comment by RLHecht** [comment]
Public Websites came back with the following search for R&S:

- https://www.va.gov/resources/how-do-i-get-college-credits-for-my-military-service/
- https://www.va.gov/resources/combat-related-special-compensation-crsc/
- https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/

**Comment by RLHecht** [comment]
Update: PW is still doing a search for us so we are moving this to Sprint 74.

**Comment by RLHecht** [comment]
Update: Here's the PW list to review:


/life-insurance/options-eligibility/sgli/index.html

/records/get-military-service-records/reconstruct-records/index.html
/records/discharge-documents/index.html

/resources/combat-related-special-compensation-crsc/index.html
/resources/life-insurance/index.html
/resources/how-do-i-get-college-credits-for-my-military-service/index.html
/resources/education-and-training/index.html
/resources/search/articles.json
/resources/disability/index.html
/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/index.html

/education/about-gi-bill-benefits/index.html
/education/about-gi-bill-benefits/montgomery-selected-reserve/index.html
/education/other-va-education-benefits/index.html
/education/other-va-education-benefits/veap/index.html
/education/eligibility/index.html
/education/transfer-post-9-11-gi-bill-benefits/index.html
/housing-assistance/home-loans/eligibility/index.html
/housing-assistance/home-loans/home-buying-process/index.html

/pension/how-to-apply/index.html

/initiatives/have-questions-before-you-get-your-covid-19-vaccine/index.html

/burials-memorials/eligibility/index.html

/disability/survivor-dic-rates/index.html
/disability/survivor-dic-rates/past-rates-2020/index.html
/disability/survivor-dic-rates/past-rates-2018/index.html
/disability/survivor-dic-rates/past-rates-2019/index.html
/disability/survivor-dic-rates/past-rates-2021/index.html
/disability/eligibility/hazardous-materials-exposure/agent-orange/index.html
/disability/how-to-file-claim/evidence-needed/index.html
/disability/how-to-file-claim/evidence-needed/fully-developed-claims/index.html

/careers-employment/family-resources/index.html
/careers-employment/veteran-owned-business-support/index.html

**Comment by RLHecht** [comment]
@katherine-fung Adding here that the stakeholder said that Space Force should be included on the CRSC page.

**Comment by katherine-fung** [comment]
Thanks for getting clarification on that page @bethpottsVADEPO  @RLHecht!

**Comment by bethpottsVADEPO** [comment]
@katherine-fung @RLHecht I answered Katherine's questions inline above and added SME names (Randi you probably already know this info, but just getting it in the ticket in case someone other than you reaches out to SMEs). 

In the first section where you list the pages that need Space Force added, it's probably best to send screen shots where you have a red arrow pointing to the part where you want to add Space Force (or a red box around it) and let them know you are making updates across the site and wanted to make sure it was accurate to add it to these pages. Also include the preview link so they can have the full context of the page. 

Thanks! Let me know if you have any questions about this.

**Comment by katherine-fung** [comment]
@RLHecht - I've attached screenshots of the life insurance pages with the proposed changes in red. 

SMEs: Steve Fital, Lori Hamilton, Kristan Hoffman 

![TSGLI payment .png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/b1a36cbe-f791-4e33-bd07-c4632bc4068e)![SGLI.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/9a70aa51-50ba-4051-a17a-4febb692ad88)

**Comment by katherine-fung** [comment]
@RLHecht Here's an updated TSGLI screenshot for stakeholders: ![TSGLI.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/b5c825dc-c68f-4357-bf24-4ccd3e87481d)

**Comment by katherine-fung** [comment]
Here are the screenshots for the careers/employment pages. 

SME: Carol Cleveland

![veteran-owned business support.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/d9e8d8e8-30a1-4088-86a9-05f454f05fac)

![family resources.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/630e84aa-98b8-4231-b180-4da7a7c911ad)

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - is there guidance for the order in which the various branches should be listed on va.gov pages?

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Good question! I don't think we have that documented. Want to talk with @RLHecht and @megzehn about it and decide if an addition to the style guide is warranted? Another one I'd love for @megzehn to look into a bit that's related and could be

**Comment by katherine-fung** [comment]
@RLHecht - I've attached the education screenshots (#1 through #5). For SME Tammy Hurley
 
#1
![college credits.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/45eda921-c1ab-4b23-bc3d-3d09aa72cf9b)

#2 
![education eligibility.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/b19204c1-8938-48c3-bb96-0e7510713ff1)

#3
![GI bill benefits.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/b04929e4-585d-45de-ac82-d995d41bc4a9)

#4
![montgomery selected reserve.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/d495fee6-a704-4d76-b7af-e9848b0cb1d3)

#5
![other education benefits.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/031cac63-1951-4ffb-a760-e6fcfb687c80)

**Comment by katherine-fung** [comment]
@RLHecht I'm attaching the screenshot for housing loans eligibility page. SME Raleigh 

![home loans eligibility.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/90fe1793-c591-49e0-b354-9c335a9baae4)

**Comment by katherine-fung** [comment]
@RLHecht I'm attaching 2 screenshots for the DIC rates page (we need to ask about 2 different sections of the same page) 

SME: Angie Smith 

#1 
![survivor dic rates.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/b3ea04df-ada1-4fe9-a1cd-2365a53a1a28)

#2
![survivor dic rates 2.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/c357f33b-4ae1-47f8-9588-928756aaad6e)

**Comment by RLHecht** [comment]
@katherine-fung Confirmed that we should add it to the SGLI page.

**Comment by RLHecht** [comment]
@katherine-fung We do not need to add to the housing loans page. 

Here's the stakeholder's response: LGY’s Loan Policy Chief notes: given that Space Force does not have an Academy as of yet, and there are no special roles that confer eligibility that apply uniquely to Space Force, nothing needs to be added for Space Force in the space highlighted in your screen capture below. Further, LGY generally references “Armed Forces,” which as an umbrella term includes Space Force, which should help simplify your effort in adding Space Force.

**Comment by katherine-fung** [comment]
Hi @RLHecht - thanks for reaching out to stakeholders! I'm putting an updated list below of the pages where we do need to add Space Force, and pages we're still waiting for clarification on. 

**Pages where we need to add "Space Force," confirmed by stakeholders:**

/life-insurance/options-eligibility/sgli/index.html
/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/index.html

/resources/combat-related-special-compensation-crsc/index.html


**Pages still awaiting clarification from stakeholders:**  

/careers-employment/family-resources/index.html
/careers-employment/veteran-owned-business-support/index.html
SME: Carol Cleveland

/resources/how-do-i-get-college-credits-for-my-military-service/index.html
/education/eligibility/index.html
/education/about-gi-bill-benefits/index.html
/education/about-gi-bill-benefits/montgomery-selected-reserve/index.html
/education/other-va-education-benefits/index.html
SME: Tammy Hurley

**Comment by katherine-fung** [comment]
Life insurance pages: 
I added "Space Force" to the SGLI page: http://preview-prod.vfs.va.gov/preview?nodeId=767 
Laura is adding "Space Force" to the TSGLI page as part of her work on another ticket 

CRSC page: 
I added "Space Force" to CRSC page: http://preview-prod.vfs.va.gov/preview?nodeId=18658 

@RLHecht - Should we follow up with Carol about the careers and employment pages, and Tammy about the education pages?

**Comment by RLHecht** [comment]
@bethpottsVADEPO is there another stakeholder besides Carol Cleveland I should reach out to about the mentions on careers and employment? I sent her a follow-up email 5/27 but haven't heard back yet. Wondering if I should email again or send to someone else as well. Thanks!

**Comment by RLHecht** [comment]
@katherine-fung Per Terry's email, you can add Space Force to the education R&S article but don't add it to any of the ones regarding MGIB-SR, since there are no Reserve or Guard components to it. Thanks!

**Comment by katherine-fung** [comment]
Thanks @RLHecht! I added "Space Force" to the list of uniformed services on the R&S article.

**Comment by RLHecht** [comment]
@megzehn Can you copyedit and publish the pages that Katherine updated? We can keep this ticket open until we hear from the last stakeholder. Thanks!

**Comment by RLHecht** [comment]
Beth looking for another stakeholder for careers and employment

**Comment by katherine-fung** [comment]
@megzehn - here are the pages for copyedit: 

Life insurance pages:
I added "Space Force" to the SGLI page: http://preview-prod.vfs.va.gov/preview?nodeId=767
Laura is adding "Space Force" to the TSGLI page as part of her work on another ticket

CRSC page:
I added "Space Force" to CRSC page: http://preview-prod.vfs.va.gov/preview?nodeId=18658

Education page: 
Added "Space Force" to R&S article: 
http://preview-prod.vfs.va.gov/preview?nodeId=15126

**Comment by RLHecht** [comment]
Update: I just reached out to a different stakeholder for careers and employment and will post here when I hear back on those 2 pages. @megzehn The rest of the pages Katherine mentioned above are ready to copyedit and publish. Thanks!

**Comment by megzehn** [comment]
Life insurance pages:
- [ ] SGLI page: http://preview-prod.vfs.va.gov/preview?nodeId=767
- [ ] TSGLI page (Laura adding in addition to other edits) 

CRSC page:
- [ ] http://preview-prod.vfs.va.gov/preview?nodeId=18658

Education page:
- [ ] http://preview-prod.vfs.va.gov/preview?nodeId=15126

- [ ] Check for any outstanding ones?

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
