### ISSUE TITLE
Pre Discovery Prep

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4048]
## Problem Statement
Problem description. How might we understand how to effectively conduct a discovery sprint around changes we see would be beneficial to our Infrastructure?

## Goal
_Understand the steps we need to talk during and before our Discovery sprint_

## Acceptance Criteria
- [ ] _Complete all pre-Discovery work below_
- [x] _List known knowns_
- [x] _Create clear Problem statement_
- [x] _List Desired Goals_
- [ ] _Work with Designer/Researcher to create questions_
- [x] _Create Product Outline_
- [x] _Create Discovery outline_
- [x] _Confirm discovery sprint team_
- [x] _Setup Interviews_

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
done
