### ISSUE TITLE
Add 9 new conditions to Exposure to Specific Environmental Hazards page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40507]
## Issue Description
Stakeholder Jacqueline Imboden informed us that there are 9 rare cancers that have been added to the list of conditions due to particulate matter. She asked us to add these along with the 3 conditions already listed (asthma, rhinitis, sinusitis) to the alert on the [Exposure to Specific Environmental Hazards page](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/specific-environmental-hazards/)

Press release with list of new conditions: https://www.va.gov/opa/pressrel/pressrelease.cfm?id=5786

Our team needs to assess the request to determine how to best present the information on the page. Once we do, we should send our recommendation to Beth for her to add to the Drupal page. 

## Tasks
- [x] Assess request and send Beth recommendation (Aliyah/Laura)
- [x] Write new content (Aliyah)
- [x] Edit content (Laura)
- [x] Copy edit (Megan)
- [x] Final review (Beth)
- [x] Update Drupal page (Beth)
- [x] Copy edit (Randi)
- [x] Publish page (Randi)
- [x] Notify stakeholder changes are live (Randi)

## Acceptance Criteria
- [x] New rare cancers are live on VA.gov

**Comment by laurawillwerth** [comment]
Hi @bethpottsVADEPO , we've made the draft changes to this page and they're ready for your review. We did 2 options for the list intros, as discussed. Looking forward to your feedback!

[4_26 - Exposure to specific environmental hazards.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8574966/4_26.-.Exposure.to.specific.environmental.hazards.docx)

**Comment by bethpottsVADEPO** [comment]
@laurawillwerth @RLHecht Thanks for putting this together! This one was so tricky--and felt impossible to imagine without putting it into drupal to see how it would feel. I wasn't sure if length would be an issue, but preview confirmed that it was just too long. Once you all have permissions and can start experimenting with solutions in drupal it'll be much easier.

Anyway, I wanted to show you the alert with the bullets, and then the solution I came up with that splits up the content to shorten the alert.

![9 new presumptive conditions.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/96df9816-5900-46d6-8e82-6c59f264a227)

Here's what I did to shorten:

![9 new conditions edited info alert.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/9e552ce8-8039-46d1-9a2c-aa82a9a21b68)

**Comment by bethpottsVADEPO** [comment]
And then I put the bulleted lists into a new Q&A immediately below the blue box:

![List of presumptive conditions.png](https://images.zenhubusercontent.com/5ecfdfb74c48ee59ad9ae036/441c814e-50d5-4db7-83f1-cc8cb36e1404)

**Comment by RLHecht** [comment]
The stakeholder approved the changes and I reviewed and published the page. Moving to validate and I'll let the stakeholder know when the changes are live.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
