### ISSUE TITLE
Update Platform with guidance for what to do with research findings outside of the Digital Experience

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40501]
## User Story
"As a VFS researcher, I may be have findings that aren't related to the Digital Experience. If there is a pattern and especial if it's data that could improve the veterans' interactions with VA, I want to know how to present these findings to folks who can actually do something with them"

"As the OCTO team, our purview is to enhance the digital experience, so when a VFS research crosses over into areas that are service experience, we want to make sure researchers understand how to properly present those findings"

- Intended Audience: VFS researchers
- Desired Outcome: added guidance on Platform 
- Due Date: tbd

## Description
While VFS researchers should be focused on researching the digital experience for va.gov, occasionally they may uncover important, actionable findings for service design, outside of the purview of OCTO. OCTO would prefer this not be a major part of research presentations made in VFS/VSP meetings, since service experience areas conduct their own research and are the owners of actions taken. At the same time it's important to get this information to the proper channel, so that important modifications that enhance the veteran's non-digital experience can be made by the teams in charge of those.

In a meeting with Kevin, Shane, and Clayton, a preferred outcome is:
- Add guidance to an appropriate Platform research page addressing the following information "When you learn about something that isn't digital experience related, but could improve lives of veterans, share with your PO. If it is actionable and you'd like to present your findings outside of your team or practice area, your PO should first discuss it with their portfolio lead.
- Add a slide to the research findings deck template for non digital experience related findings to make it more clear to researchers presenting that they should focus their energy on digital experience findings

## Artifacts Needing Updates
- Relevant Platfom page
   - A short mention on [section 7 of the checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-7.Shareyourfindingswithcolleagues)
   - [Share your findings section on research overview page](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html#ResearchOverview-Shareyourfindingswithcolleagues)
- Research findings presentation slide deck template
   - [Monday Design and Research Share - Template](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)

## Tasks
- [x] Kevin, Shane, Clayton discuss issue and ideate solution
- [x] Figure out with Platform page(s) should host this information
- [x] Get access to edit relevant slide deck template

## Acceptance Criteria
- [x] Slide deck template: has been updated
- [x] Platform Website: [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-7.Shareyourfindingswithcolleagues) has been updated
- [x] Platform Website: [Research overview page](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html#ResearchOverview-Shareyourfindingswithcolleagues) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Initiative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
RE where to put this info on Platform, I think eventually there should a page dedicated to research synthesis and presentation, but these are good first places to get the info quickly on Platform.

**Comment by chaseakirby** [comment]
@claytonzook Hey Clayton, I have reviewed and the changes to Research Overview Page & Monday Design and Research Share template look good. 
For the "Platform Website: Research Checklist has been updated" short mention in section 7; I see that it links to [this generic slide deck](https://docs.google.com/presentation/d/19l8281cENnUmdz0qIsyPcVIeoyB8uw_kzoHYWbuYlwA/edit#slide=id.g892adcb623_0_422) that doesn't reference Digital Experience vs Non-Digital Experience. I presume this is by design but just wanted to point it out in case this deck needed additional clarity.

**Comment by claytonzook** [comment]
@chaseakirby I asked Naomi about this when I was seeking edit access to these decks. Since it's a more generic slide deck template, not focused on research, she suggested not modifying it. In looking back I do feel it's then better to include the research focused template at that part of the research checklist as well. I reworded the [Share your findings section of the checklist](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+Checklist#7.-Share-your-findings-with-colleagues) checkbox 3 and 4 a bit, it you'll look back over those.

**Comment by chaseakirby** [comment]
@claytonzook Thanks Clayton! I was reading through the "Share your findings section of the checklist" checkbox 3 and I think that we could also add some clarifying text that the generic VA template is recommended for findings outside of Digital Experience. In checkbox 1, we focus on the Digital Experience and link the research findings but we don't say that the generic deck is for non-DE findings. (I also have the assumption that presenters have less experience how to handle non-DE findings since they are not our focus).
