### ISSUE TITLE
Edit and reorganize the  "VFS Team Tasks to Complete" in Staging Review feedback template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40506]
## User Story
As a VFS team member, I want to know what actions to take post Staging Review so that I can ensure I am doing everything that is expected of me.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
At the 10-10EZ Short Form staging Review, there were questions from the VFS teams about the feedback reported by Governance team. Specifically, the VFS team member did not believe the issue documented was the responsibility of her team to fix. 

The purpose of this ticket is to provide additional guidance in the Staging Review feedback template to the VFS team so they know what action to take if they believe the ticket is incorrectly assigned.

The secondary purpose of this ticket is to restructure the _VFS Team Tasks to Complete_ from a checklist to a bulleted list. The heading should also be updated to better reflect what VFS teams need to know, as it is not necessarily a task list for them to take action on.

## Impacted Artifacts 
DraftingTemplate google sheet
Collab Cycle Feedback for Staging Review gh template

## Tasks
**Collab Cycle Feedback for Staging Review gh template:**
- [x] Rename heading from _VFS Team Tasks to Complete_ to _VFS Guidance_
   - Or whatever we think is appropriate. I would just like to emphasize that these aren't required tasks, but steps they should take IF there's uncertainty
- [x] Change check boxes to bullets
- [x] Split, "Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket." into 2 bullets.
- [x] Add a 4th bullet - "If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up."
    - Again, or whatever we think is appropriate. 
- [x] Add a 5th bullet - ~~"Governance team has been advised by our OCTO leadership to flag any issue we find, whether it is in scope for your iteration or not. It is possible that this issue may be out of scope for your iteration, however it is still your responsibility to resolve the issue."~~ Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
   - wordsmith
- [x] All bullets should be written as "you" and not "the VFS team"
- [x] Reorder the bullets as appropriate

**DraftingTemplate google sheet:**
- [ ] The same changes are made to the DraftingTemplate.
Note: Please make changes to the Collab Cycle Feedback for Staging Review gh template first, have them peer reviewed, and then Shira will make the necessary changes to the DraftingTemplate.

## Acceptance Criteria
- [x] VFS teams know how to escalate concerns with the identified Staging Review issue
- [x] VFS teams are no longer asked to check off tasks they have or have not completed

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@CherylEvans the [GH pull request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/30ee0a2666913386856a42e5906145b3e185114e/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md) is ready for your review

**Comment by shiragoodman** [comment]
@allison0034 you linked the actual issue template above, not the[ pull request. ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/47864)

Also, it looks like you already published some of the changes in the issue template. Assuming this was unintentional ?

**Comment by allison0034** [comment]
@shiragoodman it is linked correctly and it has not been committed yet. Here is the [master template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md) and here is [my pull request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/30ee0a2666913386856a42e5906145b3e185114e/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md) with the changes.

**Comment by CherylEvans** [comment]
@allison0034 All of the tasks have been addressed in the PR.  Approved to squash and merge. :-)

**Comment by allison0034** [comment]
@shiragoodman can you update the drafting template? When I squash and merge it will close this ticket : )

**Comment by shiragoodman** [comment]
@allison0034 yup I'll make the changes today. And ignore my previous comment. Sorry, I always frgt to look at the branch. I realize now that it was your pull request, and not the master, linked.

**Comment by shiragoodman** [comment]
@allison0034 I made a couple comments on the PR. take a look and let me know what you think.

**Comment by allison0034** [comment]
@shiragoodman the PR is now updated. Let me know when the drafting template is complete and I will squash and merge. Merging will close this ticket.

**Comment by shiragoodman** [comment]
working on it now @allison0034

**Comment by shiragoodman** [comment]
@allison0034 I edited the DraftingTemplate, [ran a test file ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47931)and this is what it published. I think it looks good but please verify - Feel free to close the test ticket once you're done looking at it. It only has our team label on it so it shouldn't be picked up by domo

**Comment by shiragoodman** [comment]
On 2nd thought, I think we should move the line break bar below Platform Recommendation, instead of above. Thoughts?

**Comment by CherylEvans** [comment]
@allison0034 Is this ticket ready for a complete peer review?  Let me know and I will get on it asap! :-)

**Comment by allison0034** [comment]
@CherylEvans you already peer reviewed it, Shira and I are making some tweaks : )

@shiragoodman done and [here is the PR](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ea2a4d660e1a5dfb83c0469a3df21381b4b1f299/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md)

**Comment by CherylEvans** [comment]
@allison0034 Coolio.  Just making sure it didn't need a last look.  :-)

**Comment by shiragoodman** [comment]
@allison0034 DraftingTemplate is updated.
