### ISSUE TITLE
[BUG] Medallia Survey Modal not Launching

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#40512]
## Issue Description
_The Medallia feedback button at the bottom of main on one of our VA pages/templates is not launching the survey_

---
## Tasks
- [x] _Figure out why the Medallia feedback survey is not launching [this](https://www.va.gov/initiatives/veteran-trust-in-va/) page/template and fix it_

## Acceptance Criteria
- [x] _The Medallia feedback survey launches correctly on this page_ https://www.va.gov/initiatives/veteran-trust-in-va/ 

## Additional Issue
---

The following survey URLs were entered incorrectly and need to be updated per the notes:

---
https://survey.voice.va.gov/?covid-acceptance for COVID-19 Vaccine Acceptance Survey (= needs to be removed at end)

---

https://survey.voice.va.gov/?3oslyv-2fc5exlv7Qgwb12 for Veteran Childcare Survey (replace G with 2 at end)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
For the Medallia button I identified the culprit to be the `recordEvent` function throwing an error, which blocks the function that triggers the Medallia button. 

I documented the bug in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40890)

**Comment by xiongjaneg** [comment]
survey broken links are fixed per editor approval, thank you

**Comment by aubreyarcangel** [comment]
urls to below surveys have been fixed on https://www.va.gov/initiatives/veteran-trust-in-va/
![Screen Shot 2022-05-05 at 11 33 33 AM](https://user-images.githubusercontent.com/11021491/166959273-62af404b-95a8-4d0a-8754-c2baf982c6a0.png)

**Comment by jwoodman5** [comment]
The issues we could fix are resolved and tested. Closing.
