### ISSUE TITLE
Review Console

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#40515]
# User story

As a Platform customer (aka VFS team member) - the Console needs to be clear, easy to understand, and easily navigable - so that I can autonomously use it to build my VFS app.

# Tasks

- [x] Lauren - get MURAL account
- [ ] Amy Samara - contribute to Lauren's brain dump doc
- [ ] Lauren Samara Amy - optional Gretchen Liani - meeting to huddle/muddle thru the "ideas for console" brain dump doc
- Simultaneously
  - [ ] Create recommendation
  - [ ] Sked time with Console UI team - we'll probably want to use the Thurs 5/5 sync OR move it to Mon 5/9
- (stretch) start implementing changs

# Acceptance criteria

- We've created and presented a rec to the Console UI team

# Reference info
- to come

**Comment by lianilychee** [comment]
4/28 Thurs:
- sync today (Amy Lauren Samara) to align on what they came up with, want to show MURAL board to Gretchen and Liani

**Comment by lianilychee** [comment]
5/2 Mon:
- Done: We have a list of questions!
- Today:
  - Someone put document in Slack for Liani Gretchen Jill to answer by EOD
  - Console UI sync 1ET
  - AC might change, depending on how Console UI team answers the questions

**Comment by lianilychee** [comment]
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1651674642636/6647399073c96f6e59f875a2f1d10d4242062e6f?sender=ua8f37bacb65e882c26c56415

**Comment by lianilychee** [comment]
5/4 Weds:
- today:
  - prepping for tomorrow's sync, which is at 1ET:
    - adjusting questions (then send)
    - writing slack message to prep Console UI team (then send)
    - Amy Liani prep for facilitation

**Comment by lianilychee** [comment]
5/5 Thurs:
- already getting answers via Confluence!  Helpful in guiding Amy to facilitate
- will figure next steps after session

**Comment by lianilychee** [comment]
5/6 Fri:
- Yesterday / this morning
  - Made parent page in team's conf space
  - Sent Console UI team platform website organization guidance
- today:
  - all three will listen to recording, and put down questions
  - (stretch) brainstorm possible next steps

**Comment by lianilychee** [comment]
5/9 Mon:
- today:
  - review recording and put thoughts in doc for next steps
  - Amy message Samara and Lauren about putting thoughts in doc, to prep for regroup
