### ISSUE TITLE
[BE] Add ability to return mock responses from LoROTA/CHIP services based on a feature flag

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#40510]
## User Story
To be able to test the vets-api sub-system (or vets-website and vets-api subsystem) for check-in experience, we need to add a way to enable mocks for downstream services like LoROTA and CHIP so that we can isolate the performance for vets-api. 

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria
- [ ] add a feature flag that enables mocks for downstream services
- [ ] add a way to return mock responses
- [ ] add a delay in responses that are returned

## Tasks
- [ ] Deploy and test on staging.
