### ISSUE TITLE
[Packer] Fix GHA runner packer build

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#40529]
## Description
Upon initial investigation, one of the steps in the GHA runner packer build is running a script to test the web browser installs.  This was failing for the chromium browser with the following error

<img width="2201" alt="image" src="https://user-images.githubusercontent.com/76792875/165397178-25967515-e5df-43cf-a92c-c805c802c000.png">

While troubleshooting more, I noticed that the chromium install was looking for extremely out of date packages.  After resolving the above error by installing gtk 2.0 the following error appeared. 

<img width="2521" alt="image" src="https://user-images.githubusercontent.com/76792875/165397393-d24612a6-4652-491d-b74f-86a22f004c1e.png">

This is a result of the fact that the implementation we are using is from the upstream source https://github.com/actions/virtual-environments/tree/main which isn't being synced in any way to our code base.  With that being said, we should likely look at implementing our own image for the GHA runner as this solution is probably overkill.

The problem that is causing the actual failure was fixed by the following commit in the upstream repo https://github.com/actions/virtual-environments/commit/9364605355051aa302a3005ea262de8d8080726c#diff-916fd39493b82d81a0e70d66498637ee0cbf48b442f4ca11ce47a29bf9d75f22R17 which states the following and explains why the old packages were being referenced

```
# Some Google Chrome versions are based on Chromium revisions for which a (usually very old) Chromium release with the same number exist. So far this has heppened with 4 digits long Chromium revisions (1060, 1086).
# Use the previous Chromium release when this happens to avoid downloading and installing very old Chromium releases that would break image build because of incompatibilities.
```

For the time being I am going to patch this in, but longer term as stated we can look at implementing our own image with only the requirements needed.

---
## Tasks
- [ ] patch `google-chrome.sh` with the latest code
- [ ] test the gha to make sure the runner build completes successfully 

## Acceptance Criteria 
- [ ] new image is built and launch templates are updated

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
