### ISSUE TITLE
Add Platform guidance on screening for specific assistive technology users

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40531]
## User Story
"As a VFS researcher, I want to ensure that I get desired participant mix, especially when planning for assistive tech participants"

- Intended Audience: VFS
- Desired Outcome: Understand how to better find assistive tech participants for research
- Due Date: TBD

## Description
The Perigean screener is managed by PRA (Paperwork Reduction Act), and therefore takes a large effort to change. The current screener Perigean uses asks "Do you use any assistive devices, such as screen readers or braille display, to access the internet? (If no, leave blank)" Researchers looking for a specific assistive tech participants, should include an additional screener in their research plan like "Do you regularly use a screen reader while on your computer?"
Since this is not well known or documented, adding this guidance to Platform could reduce frustration associated with not having the desired participants.

## Artifacts Needing Updates
relevant Platform page(s) about research recruiting

## Tasks
- [ ] Figure out which Platform page(s) this information should live on
- [ ] update platform page(s) accordingly

## Acceptance Criteria
- [ ] Platform Website: _Page Name_ has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
Another [recent slack convo](https://dsva.slack.com/archives/C033ZS9E7EW/p1654628377206559) brought to light that this ticket is no longer needed since the recruitment questionnaire was recently changed to split out the types of AT prospective participants use
