### ISSUE TITLE
Fix Text Wrapping for PW Platform Orientation VA.gov Overview video

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40550]
## User Story
As a VFS team member, I want text wrapping around videos so that information is easily readable.

- Intended Audience: VFS Teams
- Desired Outcome: Properly text wrapped page for optimal user experience
- Due Date: N/A

## Description
The Governance Team recently added the VA.gov Overview video to Platform Orientation in Platform Website.
The goal was to have the video embedded so that VFS team members can watch the video without having to navigate to YouTube. 
The video has been embedded in ticket #39925 but is currently having some minor formatting issues with text wrapping around the video embed.

## Artifacts Needing Updates
[Platform Orientation: Purpose](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)

## Tasks
- [x] Governance Team: Reach out to Platform Content team for assistance
  - Requested support in [Slack](https://dsva.slack.com/archives/C01AS05BQ79/p1650634492128089)
- [x] Content Team: Review issue and provide support
- [x] Governance Team: Review recommendations/changes 

## Acceptance Criteria
- [x] VA.gov Overview video and following text displays as expected
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by jimuhh** [comment]
@shiragoodman @chaseakirby 
OK. I changed the embed method of video as per confluence team's instructions. It looks fine on the page and hopefully that formatting will transfer to Platform.

**Comment by shiragoodman** [comment]
I have added the page footer to the [Platform Orientation](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation) page in Confluence and it is scheduled to get published to Platform Website at 12 noon today
