### ISSUE TITLE
Hook up mocked debt letters with VBMS gem

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40553]
## Issue Description
We've created the infrastructure to be able to deliver mocked debt letters but since this data is gathered via an external [library](https://github.com/department-of-veterans-affairs/connect_vbms) we'll need to do further work to leverage this mock data.

---
## Tasks
- [ ] Develop workaround with VBMS data to deliver mock debt letters instead of live staging data.

## Acceptance Criteria
- [ ] The frontend is able to fetch mocked debt letter data 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
11/2/22 awaiting on clarity regarding VBMS

**Comment by denisecoveyduc** [comment]
Since we are no longer using VBMS we are able to close this one
