### ISSUE TITLE
Design intent [Auth Exp My VA, Benefit Payments and Debt version 2]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40551]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [x] Respond to Platform feedback tickets.
- [x] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [ ] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#product-outline-my-va) 
 
 
 
- [ ] Mockups: [desktop - just screen 71](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/52w0YgW), [mobile - just screen 72](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/bgxYo3Z)

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by seanasewell** [comment]
Review has been scheduled for 4/29 at 11:30 AM ET. Please forward the invite to any VFS attendees if needed.

**Comment by ajakabcin** [comment]
Hi @allison0034 I'm sorry you're having trouble with that link. I just double checked and the mobile link should go directly to the screen we're reviewing today - screen 72. Similarly for the desktop link it should go directly to screen we're reviewing today - screen 71. 

This is an update to an existing section on My VA (Benefit Payments and debts/bills) so there isn't an updated user flow - just updates to the section itself.

Hope this helps - apologies for the confusion!

cc @aagosto90

**Comment by CherylEvans** [comment]
No Content FB at this time.  Great job so far, and very nice presentation of the product!!

**Comment by jimuhh** [comment]
I appreciate your attentiveness to the vet's experience. @aagosto90 addressed my concerns about the discoverability of bill/payment content on mobile screens. Nice to know those notifications are on your radar.
No additional IA feedback at this time. Have a great weekend!

**Comment by ajakabcin** [comment]
All feedback is documented in subsequent tickets to be incorporated into research plan or already addressed in our designs. Closing - thanks!
