### ISSUE TITLE
Experiment and discover issues and methods for redirecting from internal api  address to the vets-api API using Traefik file provider

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#40569]
## Issue Description
We have implemented the file provider for Traefik in dev, and now we have issues to work through related to hostnames and redirection.

---
## Tasks
- [ ] Experiment with changing the configuration until we can pass requests from the internal API URL to vets-api

## Acceptance Criteria
- [ ] Requests are passed from http and https internal api address to the vets-api API successfully (200 response)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dginther** [comment]
First attempt with HTTP -> HTTPS redirection middleware resulted in a 421 Misdirected request.
Removed the middleware and redirection, and now receiving a 
```
{"errors":[{"title":"Bad Request","detail":"\"dev-internal-api.vfs.va.gov\" is not a safe host","code":"110","status":"400"}]}
```

Attempting to add the new internal API url to the list of valid virtual hosts

**Comment by dginther** [comment]
Adding the virtual host worked!
https://github.com/department-of-veterans-affairs/devops/pull/11150
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/524

http://dev-internal-api.vfs.va.gov/v0/forms now returns a list of forms! https still gives a 421. will work on that next.

**Comment by dginther** [comment]
Decided to just pass http and not https traffic since the TLS should be terminated at the ELB

**Comment by dginther** [comment]
Closing as we verified that traffic to vets-api works with dev-internal-api.vfs.va.gov
