### ISSUE TITLE
NOD: create a React widget for info page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40568]
## Description

Create a React widget that will be injected into the Drupal page. It will show a link to the Notice of Disagreement page if the user has the feature flag set to make it visible. Otherwise, it will not show anything.

## Tasks

- [ ] Create React widget with dynamic content
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by RLHecht** [comment]
Here's the content that should be placed in the react widget. I marked up the header sizes and noted the action link in the doc. Let me know if you have any questions.
[NOD react widget text.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8575492/NOD.react.widget.text.docx)

**Comment by Mottie** [comment]
@RLHecht The widget has been merged into master. It should get deployed into production today. The ID I used is `form-10182-cta`. Thank you!
