### ISSUE TITLE
[DISCOVERY] Research how feasible it is to upload VHA FSR PDFs to SharePoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40565]
## Issue Description
As an interim solution the VHA would like to receive a PDF copy of the FSR request submissions to be uploaded to SharePoint as we implement the SFTP CSV file transfer in parallel. Will need to see what this would look like programmatically and connect with platform to see how viable it is.

---
## Tasks
- [x] Research implementation details for uploading PDFs to SharePoint
- [x] Discuss with platform about Security & DevOps details

## Acceptance Criteria
- [x] We have an understanding of what PDF upload to SharePoint would look like
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Added research findings to this [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/sftp/sftp-discovery.md)
