### ISSUE TITLE
[GA] Direct Deposit: Add tracking for successful saves for first time users

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4056]
## Description

- **Team**: Authenticated experience
- **Project**: Direct deposit

In PR [11185](https://github.com/department-of-veterans-affairs/vets-website/pull/11185), we added tracking so that we can see when "save" errors happen to users who are signing up for DD for the first time ("enroll) vs. users who are updating their existing bank information ("update"). Previously, we had not been tracking errors by new vs. return users.

This metric gives us some insight into the breakdown of the "flagged-for-fraud-error" by user type. We are seeing an unexpectedly high occurrence of this error and need more information into why it's happening.  This new metric would be even more helpful to us if we could also compare saved *successes* by users who are signing up for DD for the first time vs. users who are updating their existing bank information to make sure this error is happening proportionally by user type.

## Timeframe for Analytics Requested

ASAP, but we understand if it can not be completed this sprint.

## Analytics to Track Down

Per @erikphansen:

> we currently just send this event object when an update succeeds:

```
{
  "event": "profile-transaction",
  "profile-section": "direct-deposit-information"
}
```

> by comparison the event object we send when the update fails is something like:

```
{
  "event": "profile-edit-failure",
  "profile-action": "save-failure",
  "profile-section": "direct-deposit-information",
  "error-key": "flagged-for-fraud-error-enroll"
}
```

## Which Product Questions are you trying to answer?

- Are the flagged for fraud errors happening proportionally by the amount of people enrolling in DD for the first time and the amount of people trying to update their account info?

## Additional Comments

We are hoping to ramp direct deposit up to 100% of VA.gov users soon (currently launched to 75%). This is an organizational (VA) priority because once we are launched to 100% on VA.gov, we can remove the feature from eBenefits. 

However, before we do that, we need to try to figure out what is going on with this flagged for fraud error and why we are seeing it at much higher rates than we should be. Being able to track successful saves by users adding direct deposit info for the first vs. users updating their existing info will help us see if this flagged for fraud error is disproportionately affecting one group over the other, which may help us figure out (and fix) the reason this error is happening at a much higher rate than it should.

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
@nedierecel @jonwehausen @joanneesteban let me know if you have any questions here. I haven't filled out a request like this before, so I may have missed necessary information for you. I'm happy to hop on a call any time to discuss things if you have questions.

If you have questions about integrating with this analytics request with our fronted, those would be best directed to @erikphansen.

**Comment by Samara-Strauss** [comment]
Actually closing this request for now in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/4097. We think the metrics we'll get in that ticket will be more helpful than the ones we were asking for here.
