### ISSUE TITLE
Need an AWS service account for GitHub actions

### ISSUE THREAD

**Issue by MrBilnon** [department-of-veterans-affairs/va.gov-team#40563]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@considerable

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We have an existing service account for our team, _svc-gha-pst-iet_ but not sure if we need a separate service account for each microservice/github repo.  Will need the secrets added to https://github.com/department-of-veterans-affairs/vets-api-virus-scan

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Possibly create a new service account or use the existing service account _svc-gha-pst-iet_
- [x] Add the aws secret and access key to the repo, https://github.com/department-of-veterans-affairs/vets-api-virus-scan

## Acceptance Criteria 
- [x] working service account credentials added to requested repository

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Credentials added to [requested repo secrets](https://github.com/department-of-veterans-affairs/vets-api-virus-scan/settings/secrets/actions)
