### ISSUE TITLE
Update documentation about adding menu items to the left nav include 2 more processes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40576]
## Issue Description

We need to add 2 processes to our [documentation about how to add an item to the left nav](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md):

- How to add a resources and support article
- How to remove a page from the left nav

## Tasks
- [x] Add step-by-step process for adding an R&S page (Randi)
- [x] Add step-by-step process for removing a menu item (Randi)

## Acceptance Criteria
- [x] Documentation is updated

**Comment by RLHecht** [comment]
I've updated the documentation to include these 2 use cases: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md

Closing ticket.
