### ISSUE TITLE
508c bug on the AuthAPP

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40573]
## Issue Description
Fix the heading levels on the AuthApp so that VA.gov is in compliance with accessibility standards as noted by Brooks J. (https://dsva.slack.com/archives/CSFV4QTKN/p1651085727350899)

---
## Tasks
- [ ] Change the h3 tags to h2 tags
- [ ] Run an accessibility test on the AuthApp page

## Acceptance Criteria
- [ ] No accessibility errors exist on the AuthApp page
