### ISSUE TITLE
[FE] Move Sub-Message to Blue Box w/ Info Icon

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40585]
## Wireframes
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/DPz9EGj

## Tasks
- [x] Move all message bodies into a blue box with the information icon (see Wireframes)
    - Anywhere were we have a message with a sub-message, the sub-message should be moved to a blue box with info icon
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [x] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [x] Deployed to staging.
- [x] Designer has signed off on the feature
- [x] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
waiting for translation

**Comment by sarahknoppA6** [comment]
@brdunfield did this and the header tags get merged and deployed to staging yesterday? Just checking since we discussed it at standup

**Comment by brdunfield** [comment]
Yes both were merged yesterday!

**Comment by brdunfield** [comment]
Ready for validation

Screenshots:
![Screen Shot 2022-05-11 at 11.44.22 AM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/cf070fcf-def3-4f2e-b8e6-d7222bc1587c)
![Screen Shot 2022-05-17 at 9.47.37 AM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/0dc94ade-5126-4dd8-a4f5-9f9c66f2d4ca)
![Screen Shot 2022-05-17 at 9.49.26 AM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/3e70e279-9b78-4d79-9f6d-2927bcf3ba18)

**Comment by loripusey** [comment]
Looks good

**Comment by zach-park** [comment]
LGTM. Thank you!! :)
