### ISSUE TITLE
Discover and Add Cerner Test Users to TUD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#40587]
# Description
Teams have a growing interest in test user accounts that are associated with Cerner facilities generally or a specific Cerner facility. We need to discover Cerner facility users in the va.gov-team-sensitive repository and move them into TUD. 

# Tasks
- [ ] Identify existing test user accounts that are associated with Cerner facilities
- [ ] Compile a list of test user accounts to move to TUD
- [ ] Import the test users into TUD

# Acceptance Criteria
- [ ] Test user accounts associated with Cerner facilities have been imported into TUD
