### ISSUE TITLE
[IAM] Cleanup user groups

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#40591]
## Description
User groups in `iam_users.tf` may have duplicates or unused groups. Policies for those groups might also be redundant. If a group has multiple unique policies (no other group has them), it may make sense to combine them into a single policy.

## Tasks
- [x] comb through user groups and look for unused groups (delete), duplicate groups (delete all but one, re-assign members of deleted groups), redundant policies (remove), or other opportunities to make groups "cleaner"
- [x] put devops or other engineers that need elevated permissions in groups scoped to their team. There are currently 14 engineers not on the infra team with full admin access. 

## Acceptance Criteria 
- [x] tasks have been performed by one engineer and approved by another.

**Comment by rmtolmach** [comment]
All work associated with this Issue has been merged. Closing! :tada:
