### ISSUE TITLE
[UX] Update Release Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40597]
## Description
Update various product assets, as necessary, based on changes to the product for post-visit activities.

## Tasks
- [ ] Update the PCI Product Guide, including content and screenshots
- [ ] Update the CI Product Guide, including content and screenshots
- [ ] Update the Poster
- [ ] Update user flow diagrams, as necessary
- [ ] Push changes to the appropriate GitHub files
- [ ] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov
- [ ] Notify the Contact Center of the changes (follow this [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))
- [ ] Notify Training of the changes (Shawn Adams, Cheryl Wills, Farah Ford)

## Acceptance Criteria
- [ ] Product Guides are up-to-date (content & screenshots)
- [ ] Poster is up-to-date
- [ ] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [ ] R&D articles are up-to-date
- [ ] Contact Center is aware of the changes
- [ ] Training is aware of the changes

**Comment by benbrasso-agile6** [comment]
I messaged danielle about the Resources & Support page. That page could be edited. But, up to her if she feels it's necessary. I provided her with some thoughts. https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/

**Comment by benbrasso-agile6** [comment]
@loripusey I updated the [pre check in file product guides in git](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md). I don't see that check-in guides require updates based on the [release notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/detailed-release-notes/update-messaging.md). 

The R&D article doesn't need to be updated based on this release. However, Danielle is working on making an update around "non edit edit," e.g., "sign in to VA to update your contact information online." 

Anything else we need to do?

**Comment by benbrasso-agile6** [comment]
Pre check in product guide with comments for contact center team: 

[Pre Check In Product Guide](https://app.zenhub.com/files/133843125/f36c3236-a99c-4179-a1e9-72c06ff7ce65/download)

Note: This version was NOT posted to git because it has comments in it. 

@loripusey

**Comment by loripusey** [comment]
@benbrasso-agile6 do you want to go ahead and submit the ticket for the Contact Center and attach this product guide?
