### ISSUE TITLE
[Datadog] Implement NPM for eks clusters

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#40590]
## Description
Being that we are using APM in datadog for vets-api, it is also very useful to have the NPM feature to correlate more data to those traces.  We have added this to BRD but also need to make sure this is something enabled in EKS as well.

https://docs.datadoghq.com/network_monitoring/performance/setup/?tab=agentlinux

---
## Tasks
- [ ] Add needed configurations described by the documentation (kubernetes configurations, helm) and deploy to the dev cluster
- [ ] If all goes well, deploy the same configurations to all clusters

## Acceptance Criteria 
- [ ] NPM metrics are being accepted in datadog

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Closing this since it was a misunderstanding on my part.  The only thing that is needed for the helm chart to enable NPM is the following

```
datadog:
  networkMonitoring:
    enabled: true
```

This puts all of the appropriate mounts and configs in place through the helm templates.  As we can see this is working in dev eks

![image](https://user-images.githubusercontent.com/76792875/165801770-cec9e693-a570-4e16-b41a-fc0b7d5f35d7.png)
