### ISSUE TITLE
[EKS] Install Argo Workflows

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#40603]
## Description
In order to use Argo Events, we will need Argo Workflows as a prerequisite based on the documentation

https://argoproj.github.io/argo-events/tutorials/01-introduction/

https://github.com/department-of-veterans-affairs/va.gov-team/issues/32149

---
## Tasks
- [ ] Create argo workflows ecr repository
- [ ] Upload argo workflows image to ECR repository
- [ ] Use the argo workflows helm chart to install on the utility cluster where argo itself lives
- [ ] Create infra repo for argo workflows and set up github actions to build/mirror image and update manifests

## Acceptance Criteria 
- [ ] Argo workflows is install and can be utilized by argo events

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
I am starting to doubt the capability and understanding of how we would use argo workflows.  As of right now it doesn't seem like there is multi cluster support https://github.com/argoproj/argo-workflows/issues/3523 without having all argo components in every cluster?

Not too sure here, will need to investigate and discuss with the team further

**Comment by mleclerc00** [comment]
Closing for now and will revisit if needed
