### ISSUE TITLE
Move iam policies and users out of global envirnoment

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#40617]
## Description
Break iam_users.tf and iam_policies.tf out of the global environment. Determine where they should live. Move resources from old state file to new state file _without destroying any resources_. Once policies are moved, experiment with upgrading the Terraform version on the new location.

## Background/context 

We are working in an old version of Terraform. At the moment, with all users and policies in the `global` env, upgrading would he a huge hassle. Testing the upgrade in a smaller environment will be safer and a positive side effect of splitting out policies/users.

---
## Tasks
- [ ] Determine where iam_users.tf and iam_policies.tf should live and break them out of the global environment.
- [ ] Move resources from old state file to new state file _without destroying any resources_.
- [ ] Once policies are moved, experiment with upgrading the Terraform version on the new location.

## Acceptance Criteria 
- [ ] All tasks completed and testing done.

**Comment by jhouse-solvd** [comment]
From a discussion w/ the Platform Infrastructure: 

- What is our solution for managing users? 
- Is that still Terraform? Or something else? 
- How might we make it easier to manage from the operational perspective? 
- If we stay w/ Terraform, it needs to be upgraded 
- Need to evaluate interdependencies (policies, roles, etc) 

As is, this needs to be broken down. There is some discovery needed before this could be taken on.
