### ISSUE TITLE
Request to change date language on bottom of Privacy Policy page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40614]
## Issue Description

Justin Cooper, the web developer for OPRM asked if we can change the date at the bottom of the [privacy policy page](https://www.va.gov/privacy-policy/) to the following language: Last reviewed on April 28, 2022

The last updated date is automatically generated through Drupal so we need to discuss what other options would be. 

## Tasks
- [ ] Determine how get the last reviewed date onto the page
- [ ] Update Drupal page
- [ ] Review and publish
- [ ] Notify stakeholders that change is live

## Acceptance Criteria
- [ ] The live privacy policy page has a last reviewed on date

**Comment by RLHecht** [comment]
I updated the date that's in the rich text field toward the bottom of the page and changed the language to "Last reviewed on April 28, 2022". This will also update the date at the very bottom of the page. I'll notify the stakeholder once it's live and let them know that the date on the very bottom of the page is auto generated so unless the date in the rich text field is always updated when a change is made, the date on the bottom won't necessarily be accurate.

**Comment by RLHecht** [comment]
Change is live and I notified the stakeholder. Closing ticket.
