### ISSUE TITLE
[IAM] Standardize policies

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#40616]
## Description
Standardizing policies will likely be a messy task. Do we need all of the policies listed in [iam_policies.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_policies.tf)? ideally, we would have templates for teams. (For example, [this](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/base_gha_ecr_policy.tftpl) is the Terraform template we use for github actions.)

Any policy that applies to only one user group, we might want to rename to be team-specific.

## Background/context 
Epic is #40557 

---
## Tasks
- [ ] Analyze current policies in `iam_policies.tf` and determine if any can be deleted/consolidated/added. 
- [ ] Edit `iam_policies.tf` based on determination in previous step.
- [ ] Make templates for teams, if appropriate.

## Acceptance Criteria 
- [ ] All tasks are completed and tested.

**Comment by rmtolmach** [comment]
Progress so far:
Went through iam_policies.tf. This was my "methodology": I started at the bottom of the file where the team policies live. For each `action`, I searched for the first action in the list and found all of the other occurrences. If the other occurrences looked similar, I wrote the action down. Take `kms:Decrypt` for an example of one I _didn't_ write down:
It's used by itself here:
```
    actions = [
      "kms:Decrypt",
    ]
```
But it's with other actions here:
```
    actions = [
      "iam:GetInstanceProfile",
      "iam:ListInstanceProfiles",
      "iam:PassRole",
      "kms:Decrypt",
    ]
```
And even different actions here:
```
    actions = [
      "kms:Encrypt",
      "kms:Decrypt"
    ]
```
None of those match, so I didn't write them down. 
But `eks:ListClusters` was in an action that was duplicated in three different spots, so I wrote that one down.
```
    actions = [
      "eks:ListClusters",
      "eks:DescribeCluster",
    ]
```
Others I jotted down:
s3:getObject, ssm:*Parameter, ecr:GetRegistryPolicy, eksReadOnly, kmsReadOnly, kmsReadOnly2, s3:ListAllMyBuckets, ssm:DescribeParameters, ssm:startSession, kms:ListAliases, es:ListDomainNames, es:DescribeElasticSearchDomains, logs:CreateLogGroup.

Next steps: create templates for some of the actions.

**Comment by rmtolmach** [comment]
What I learned today:
* A policy is a collection of statements. A statement decides who gets to _do_ what (actions) _on_ what (resources).
* `Sid` is an optional string identifier for a policy statement. It's for the humans.
* Resources and conditions can be passed in as parameters when using a templatefile.
* `terraform plan -refresh=false` is much faster than `terraform plan`.
* If a policy document has many `statements`, that policy could be tricky (and maybe not worth it) to parameterize.
* Helpful docs: 
  * https://www.terraform.io/language/functions/templatefile
  * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document 
* I am understanding that this task is more complicated than I originally thought. There are many way to simplify permissions. We can simplify them by refactoring the specific policies in `iam_policies`, but we can also see what group memberships people belong to in `iam_users`. We have some `group` "cocktails" that likely have overlapping permissions. (I see this as a "group cocktail": `group_memberships    = ["dsva-vfs-all", "dsva-vfs-developers", "force-MFA"]` 😂 🍸 )

PR https://github.com/department-of-veterans-affairs/devops/pull/11198 is my attempt to chip away at this work. More refactoring to come.

**Comment by rmtolmach** [comment]
I am closing this issue 🎉. Standardizing policies is something that will be ongoing, but the four PRs (mentioned in this issue) lay the groundwork for reusing and standardizing policies in the future. 

Summary of PRs:
* I ended up using a combination of `templatefile` and `source_police_documents` to standardize policies. 
* I went through iam_users and iam_policies and cleaned things up.
