### ISSUE TITLE
New Datadog private location in DEV environment

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#40623]
## Issue Description
Set up a new private location for the DEV environment in Datadog in order to facilitate internal API calls that go through the forward proxy. The forward proxy address would otherwise not be accessible internally.

---
## Tasks
- [x] Add new location via the Datadog web interface
- [x] Add Kubernetes manifests for the new location in the DEV environment
- [x] Add ArgoCD application
- [x] Add location configuration to the AWS Parameter Store
- [x] Update image version to the latest one (1.22.0)

## Acceptance Criteria
- [x] New private location for the DEV environment is up and running in Datadog 
- [x] Private location works to make API requests directly to the forward proxy address
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
