### ISSUE TITLE
**Discovery** Auth-Profile | Set up Alerts 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40627]
## Background

The Profile team would like to make sure that all errors are being sent to Sentry and add alerts to our [Slack channel](https://dsva.slack.com/archives/C02SYJGH8FJ) when we have an increase in failed saves for any one of the editable sections of the profile.

## Tasks

- [x] Setup a meeting with Elijah Lynn and Eric Oliver from the CMS team to get a better understanding of how they implemented this? Once we have a better idea of what this is going to look like, we can break this up into smaller tickets with better estimates.
- [x] Determine if the Tools team will allow us to begin using Datadog and what the benefits would be.

## Acceptance Criteria

- [ ] Create tickets for adding alerts.

**Comment by SKasimow** [comment]
@adamwhitlock1 @mdewey - is there anything we should add for the front-end? 

I'll let you know what I find out about using Datadog.

**Comment by tpharrison** [comment]
The following query shows the production errors due to a BE bug (Apr 27-28).  This is the type of query I'll start with.  

![image](https://user-images.githubusercontent.com/653787/165957865-d4102af4-dc0e-4328-8c26-f2972f603b7d.png)

If you have access to Sentry, you can view the query results [here](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&end=2022-04-28T23%3A59%3A59&environment=production&field=url&field=issue&field=timestamp.to_hour&field=event.type&field=culprit&name=Errors+by+URL&query=event.type%3Aerror+controller_name%3Aaddresses+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fv0%2Fprofile%2Faddresses&sort=-timestamp.to_hour&start=2022-04-27T00%3A00%3A00&utc=true&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).

In addition to alerting for any 500 errors, an alert can be triggered based on [failure rate](https://docs.sentry.io/product/performance/metrics/#failure-rate) which would catch an issue like this one.

**Comment by tpharrison** [comment]
Opened a support ticket to request access for adding alerts in Sentry.  Other teams have had challenges integrating Slack with Sentry.  Support recommended that we follow up with the CMS team.

Slack convo - https://dsva.slack.com/archives/CTYQL39FE/p1651247200449679

**Comment by tpharrison** [comment]
@SKasimow @Samara-Strauss - I think we need to do more discovery on this before I can estimate.  The CMS team was unable to integrate slack with sentry, but was able to integrate sentry with datadog and pager duty.

Sharon - can we setup a meeting with Elijah Lynn and Eric Oliver from the CMS team to get a better understanding of how they implemented this?  Once we have a better idea of what this is going to look like, we can break this up into smaller tickets with better estimates.

Adam and Mark should probably be in this meeting as well since they're going to be sending data to Sentry from the FE.
