### ISSUE TITLE
Improve the search results "No results" page on design.va.gov

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#40629]
## Description
According to feedback from a user research session with Angela Fowler, we should update the design.va.gov search "No results" page in the following ways:
1. The "No results found" message should be an h2 element
2. We should add details to the page with details on how to improve a user's search (explain that we only search title, intro text).

## Tasks
- [ ] Update "No results found" message to an h2 element
- [ ] Add details for how to improve search to "No results" page

## Acceptance criteria
- [ ] "No results found" is an h2 element
- [ ] The search "No results" page includes details on how to improve a user's search
