### ISSUE TITLE
Design VAOS' documentation space

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#40625]
## Task description
Work with VAOS dev and product to redesign the structure of our GitHub documentation space.

## References
- [VAOS documentation notes](https://docs.google.com/document/d/1tHihdzLKTD333DYKPjaoxE0skaaWRaTPqLASvmJfruE/edit#)
- [Optimal sort workshop results](https://app.optimalworkshop.com/a/dj540s05/optimalsort/results/1a920c40-accf-4693-a836-d22f82e8e4c6#/t/results/overview)

## Acceptance criteria
- [x] Team has reviewed synthesis from card sort exercise
- [x] Team has workshopped new structure
- [x] Team has identified final new structure

**Comment by outerpress** [comment]
* Working on draft of the new github homepage

**Comment by outerpress** [comment]
Breaking this up into separate tickets for the separate spaces.
