### ISSUE TITLE
Create E2E Tests for TUD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#40636]
# Description
We should create end-to-end test specs in order to verify the core user journeys of TUD continue to work without issue when changes are integrated.

# Tasks
- [ ] Add Cypress to TUD repo
- [ ] Write one or more test specs to verify the core user journeys of TUD
  * Authenticate
  * Search
  * Filter
  * Clear filters
  * Expand test account details
- [ ] Add e2e test execution to the TUD CI/CD workflow

# Acceptance Criteria
- [ ] End-to-end test specs verify core user journey of TUD
- [ ] End-to-end test execution is included in the TUD CI/CD
