### ISSUE TITLE
Populate the Repository field on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40649]
## Issue Description
We need to populate the repository field on the product list. Any product that has a manifest will be located in `vets-website`. Some other products, such as VA notify, have their own repository (notifications-ui, in this case). Please fill in what repository the product lives in. Some research may need to be done for outliers to locate them.

Product List: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0
---
## Tasks
- [x] Fill in the repository column on the product list.

## Acceptance Criteria
- [x] The column for repository has a value in all applicable rows.
- [x] Any unknown rows are left as a blank cell.

**Comment by CBonade** [comment]
This is all set as far as my research could take me. There's just a few that I'm really not sure about and we didn't have a solid answer from anyone we asked. These might be a couple we just have to have teams fill in when we make the list public.

**Comment by pjhill** [comment]
~89% populated
