### ISSUE TITLE
Populate Status column on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40658]
## Issue Description
We need to fill in the Status column on the product list. Status refers to the stage that a product is in currently - whether that be that it's Live on production or In Progress of development. There are a few sources that this information may come from such as:

- Governance team's product overview: https://vfs.atlassian.net/wiki/spaces/VAProducts/overview
- Going to the url on va.gov and seeing if the product is live.

If a product is active on va.gov, it should be listed as "Live".
If a product page is not found on va.gov, and we cannot confirm it's still in active development, it would be listed as "Inactive"
If a product is not found but we know it's in active development, it would be listed as "In Progress".

Product List: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

---
## Tasks
- [x] Fill in the status column of the product list with all applicable values based on the sources listed in the description.

## Acceptance Criteria
- [x] Applicable values have been added to the Status column of the product list.
- [ ] Any unknown rows are left blank.
