### ISSUE TITLE
[Access Requests] Add new required fields to access request templates

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#40654]
## Description
We need to add new required fields for PM/PO and email addresses for both to the access request templates in order to better track team membership

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1651245966565119

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] New required fields added to access request templates

## Acceptance Criteria 
- [x] Fields added and actively being required for access requests

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/40827 Fixes this. 

New AWS template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/aws-access-request.yml
New SOCKS template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/socks-access-request.yml

And here is an example of what a SOCKS request looks like once it's filled out:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40844
