### ISSUE TITLE
[Access Requests] Require existence of user in VFS or Platform roster for access

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#40655]
## Description
We need to link the [VFS team roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) and the [Platform Roster](https://vfs.atlassian.net/wiki/x/P4HGcQ) to the access request templates (like we do for the offboarding one) and require existence of the user there before granting access

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1651245966565119

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] link up vfs team roster to access request templates
- [x] start requiring existence of the user in the vfs team roster before granting access
- [x] update internal [documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools)
- [x] Update [Platform website Getting started](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) section to make it clear to the user that they need to do the Platform orientation steps _before_ we grant them SOCKS access. See screenshot of the two sections:
![Screen Shot 2022-04-29 at 3 56 52 PM](https://user-images.githubusercontent.com/10993987/166061762-016eb7b7-0350-4edd-a4ce-9fb7f70e28ac.png)

## Acceptance Criteria 
- [ ] vfs team roster linked to access request templates for easy navigation and verification
- [ ] start requiring user existence within the vfs team roster before granting access 
- [ ] Platform website updated.

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
The [access request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/socks-access-request.yml) is in yaml, which doesn't allow markdown to be submitted with the form. (Super annoying, I know 🙄. I ran into this last month. [link to github docs](https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown).) So unfortunately we can't link the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) in the request form and see it once it's submitted. (If we put it in the yaml, the form _will_ show it as the user is filling out out, but once it's submitted, it's not visible.)

Added updating Platform documentation to this Issue.

**Comment by jbritt1** [comment]
> The [access request template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/socks-access-request.yml) is in yaml, which doesn't allow markdown to be submitted with the form. (Super annoying, I know 🙄. I ran into this last month. [link to github docs](https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown).) So unfortunately we can't link the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) in the request form and see it once it's submitted. (If we put it in the yaml, the form _will_ show it as the user is filling out out, but once it's submitted, it's not visible.)
> 
> Added updating Platform documentation to the tasks.

How about a GitHub action to comment it with a link to it upon open?

**Comment by mchelen-gov** [comment]
you can use raw urls in fields, for example see
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/octo-de-crew-onboarding.yml

**Comment by rmtolmach** [comment]
Thanks for that suggestion, @mchelen-gov! Putting the URLs in the checkbox list ensures they're persisted once the issue is submitted. See example below. The last section is new.
![image](https://user-images.githubusercontent.com/10993987/166551313-d80c817c-ace7-4e8b-ac79-a1ff96bf0078.png)

✅  Issue #40827 adds those links and explains that membership to one of the rosters is required before access can be granted. 

✅  Internal documentation (for Infra team) is updated: https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools

✅  Platform website documentation:
I moved the "Platform Orientation" section to the top
![image](https://user-images.githubusercontent.com/10993987/166559843-3f64ccc4-6a97-4b54-bfb7-52cb68c4ebf4.png)
[link to Confluence Scroll Content space](https://vfs.atlassian.net/wiki/spaces/GS/pages/1255276574/Welcome). Change should go live on Thursday 5/5. I ended up not changing any of the content in "Request access to tools" sections. I thought it might add to the confusion. We can make edits to it later if we feel they're needed.
