### ISSUE TITLE
Populate the Documentation column on our product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40664]
## Issue Description
We need to fill in the documentation column on the product list. This should contain a link to any relevant primary documentation for each product. For many of these products, that will be either the README.md itself, or the link to the documentation will be inside the README.md.

Product list: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

---
## Tasks
- [x] Fill in the Documentation column on the product list.

## Acceptance Criteria
- [x] All applicable rows in the product list have values.
- [x] Any unclear entries have been left blank.
---

**Comment by rjohnson2011** [comment]
Started work on this, about halfway through adding relative paths to the documentation column of the product list.

A couple edge cases are noted, like an example where the readme file for a product exists but is blank.

**Comment by CBonade** [comment]
Couple of bits before you get too far into it:

- please link to the documentation as opposed to putting in a relative path in plain text
- if there is none, please leave the box blank as opposed to filling in a non-value (see acceptance criteria). We want those to hav a null value for querying purposes if necessary

**Comment by rjohnson2011** [comment]
Nearing the end of the process, about 10 more products to go through until completion. Afterwards will do one final pass of missing products through `vets-website` repos for any Readmes while in Review.

**Comment by pjhill** [comment]
This looks good, thanks for getting these squared away!
