### ISSUE TITLE
Fill in the Platform Console Category column on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40679]
## Issue Description
The Console UI team has assigned a category from a list of 5 categories (Content, Forms, Apps, Profile, API & Systems) to each product they have on their list. We want to map as many of these categories as we can from their list to our product list.

Console UI List: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2150334586/VFS+and+Platform+Teams

Product List: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

---
## Tasks
- [ ] The Platform Console Category is filled out appropriately.

## Acceptance Criteria
- [ ] All relevant rows have values for Platform Console Category.
- [ ] Any discrepancies are left blank.
---

**Comment by ddzz** [comment]
The spreadsheet has been updated with categories. There are four products where there is not enough information to determine the category.

**Comment by pjhill** [comment]
Thanks for the summary of empty fields. We expect to have some of the products with empty attributes here and there.
