### ISSUE TITLE
[CDP] Adjustments to the usability research plan

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40682]
## Issue Description
This ticket captures updates to the CDP's usability research plan. Since the portal currently only displays the past 6 months worth of copay bills, we'll want to recruit participants who have received a bill within the past 6 months so their information displays during the session. 

---
## Tasks
- [x] Update the recruitment diagram and replace it on GH
- [x] Update the research plan

## Acceptance Criteria
- [x] Research plan has been updated and linked in this ticket

**Comment by rileyorr** [comment]
@denisecoveyduc FYI I spun up this ticket so the work was captured for the sprint! I needed to adjust the research plan criteria. 

[The updated research plan can be found here!](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-plan.md)
