### ISSUE TITLE
Refactor Vet360 Profile form components to use SchemaForm

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#4068]
## Background

The Vet360 form components, such as `AddressForm`, use an old method to set up the form UI and validation logic. For example it uses `ErrorableTextInput` and `ErrorableSelect` components and defines the validation logic up the component chain in the `AddressField` component, which in turn passes it down to the `Vet360ProfileField` component.

We should modernize these components to use an ad-hoc `SchemaForm` so we can describe the form structure and functionality with the Health Care Application `IDPage` https://github.com/department-of-veterans-affairs/vets-website/blob/358c9d38c39593a64a2bc8c54cd9c5965e34bee5/src/applications/hca/containers/IDPage.jsx#L182-L192

We should then be able to delete the outdated form components, such as `ErrorableSelect` and `ErrorableTextInput` 

## Tasks

- [x] Background research to determine scope #4930
- [x] Refactor address form #5078
- [x] Refactor phone number form #5118
- [x] Refactor email address form #5121
- [x] Refactor direct deposit form #5816
- [x] Profile page scrolls when trying to submit invalid profile data #5458
- [x] Profile edit email modal validations on staging do not match production #5704
- [ ] Release new profile forms to production and remove old legacy code #5817

## Acceptance Criteria

**Comment by Justin-Pickett** [comment]
Revisit this ticket to figure out what the execution of this work would entail. Determine if this needs to be considered an epic or not. Breakdown accordingly.
