### ISSUE TITLE
[FSR] SME meeting prep for FSR content adjustments

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40697]
## Issue Description
There are several places in the current iteration of FSR where language may be specific to benefit debt process. We are going to meet with a VHA SME to confirm the accuracy of the content and discuss the resolution options available for copay bills.

---
## Tasks
- [x] Create a meeting outline / conversation guide for the SME meeting
- [x] Document the changes identified in the meeting 

## Acceptance Criteria
- [x] Notes from the meeting are added to GH and linked in this ticket 
- [x] The content adjustments ticket ([#30698](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/30698)) has been updated with the identified updates

**Comment by rileyorr** [comment]
Started [a conversation guide/outline](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Financial%20Status%20Report%20(FSR)/Iteration%202.0%20VHA%20and%20VBA%20FSR/Document.docx?d=w0cc9f7396a1747f3aa85775d8cb2e60c&csf=1&web=1&e=6Kj7SJ) for tomorrow's meeting. Keeping it brief since we're just doing a 30 min introduction meeting - we'll see how far we get!

**Comment by rileyorr** [comment]
Cleaned up notes can be found [here](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Financial%20Status%20Report%20(FSR)/Iteration%202.0%20VHA%20and%20VBA%20FSR/SME%20Meetings/Notes/05102022%20David%20Adcock%20Meeting.docx?d=w22ada3c081484b62ad8d459c6933b950&csf=1&web=1&e=mhzdGf)! I will also add them to GH so they're accessible to the wider team.

**Comment by rileyorr** [comment]
[Notes and next steps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/sme-interviews/05102022-sme-interview.md) have been added to GH. 

@kevinstachura is continuing conversations with David via email so we get feedback on the FSR's intro page. Not sure if we want to leave this ticket open until we receive that feedback or capture it in another ticket if the work bleeds into next sprint!
