### ISSUE TITLE
Investigate BGS Code from Lighthouse

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4069]
## Story
As a backend engineer I want to understand what code is in place for BGS from the Lighthouse so that when these services become available I can get started with endpoint implementation sooner.

## Considerations
- To go much further, BGS service `ClaimantWebService` will need to be accessible.
- Is there anything that gets generated here that should not be publically available?
  - Notes can go [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/bgs/README.md)

## Tasks
- [x] Meet with Charley for intro to services
- [x] Review LH API with respect to BGS
  - [x] Trace workflow for endpoint implementation

## Acceptance Criteria
- [x] Understand the workflows and BGS code implementation process with respect to Lighthouse
