### ISSUE TITLE
GitHub Ticket Updates - Research Opportunities/Findings

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40707]
## User Story
As a Governance team member, I want to update the core ticket so that VFS PMs can easily fill out the ticket.

- Intended Audience: VFS Teams and PMs
- Desired Outcome: Updated GitHub ticket and documentation
- Due Date: 5/9 (Preparation for launch on 5/10)

## Description
Findings that have been prioritized as needing GitHub template updates from [Research Findings spreadsheet (Pre Launch Improvements tab)](https://docs.google.com/spreadsheets/d/1_EGjrHtr3gEam72K4zEoFMdkQLBIvIjQ_lmes-RgWLw/edit#gid=1309674612).
All Documentation Updates should be made to draft pages in [Documentation Drafts - Core Ticket Guidance 38606](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2165440978/Core+Ticket+guidance+36086)

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Tasks
- [x] Opportunity Statement (OS): Add gray area in order to avoid forcing participants/respondents to select Y/N when they dont have a formed answer. Could introduce measurement error in data. 
  - [x] Identify which questions in core ticket this applies to
  - [x] GitHub: Update YAML template
- [x] OS: If the goal of the question is to understand different opinions we should not only use a gray area point but also s "Not Sure/ Not Applicable" option. This would allow respondents to provide an answer that is true to their experience. 
  - [x] Identify which questions in core ticket this applies to
  - [x] GitHub: Update YAML template with Unsure/NA and gray area.
- [ ] OS: Not making anything required. Governance team can follow-up with PM in Slack if they need additional information. Supply PM with information in the form of where to go if they have questions (Slack channel?).
  - [ ] Evaluate required questions
    - Shira - there should be some that are required and easily able to answer. If the PM can't answer the required questions, then that is a clear indicator that they are not ready to engage in CC.
  - [ ] GitHub: Update YAML template required questions (if changed)
  - [ ] Platform Website-CC Kickoff: Match list of required questions from GitHub
- [x] OS: Right now, helper text that says "Fields marked with an asterisk (*) are required." appears at the bottom of the form next to the "submit" button. We could reposition this helper text before the first form question.
  - [x] GitHub: Add "Fields marked with an asterisk (*) are required." to top of YAML template
- [x] OS: If we remove Zoom information from the core CC ticket (and possibly communicate that via temporary Slack channels instead), PMs will better understand what they're supposed to be filling out.
  - [x] GitHub: Only include Zoom recording link and zoom recording password
  - [x] GitHub: Remove zoom meeting link 
  - [ ] Confluence: Moderator Pages
    - Design Intent Moderator Responsibilities
    - Midpoint Review Moderator Responsibilities
    - Staging Review Moderator Responsibilities
  - [ ] Platform Website: Touchpoint Pages
    - Design Intent
    - Midpoint Review
    - Staging Review
- [x] OS: For markdown, provide PM's with direction of where to specifically provide artifact links. For example under checkbox in design artifacts section provide presecriptive text like "Design artifact link:". Or add helper text within proximity of checkbox that informs PM's that a link needs to be provided. (some PM's didn't provide link but ticked the checkbox)
  - [x] GitHub: Remove checkboxes beside all artifacts
  - [x] GitHub: Add "I have added all relevant artifacts" checkbox underneath each artifacts section

## Acceptance Criteria
- [ ] GitHub template have been updated
- [ ] Document updates have been completed
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
Moved all remaining open items into respective tickets: #41201, #41209, and #41211
