### ISSUE TITLE
[Design] On-site Notifications: Create designs for showing multiple notifications

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40709]
## Background
Per discussion in #36184 we need to create a design that shows how we handle multiple notifications.  For details on decision to show multiple notifications as individual see [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36184#issuecomment-1113324707).  

## Tasks
- [x] Create design for showing multiple notifications as individual on-site notifications with a timestamp
- [x] Review with FE
- [x] Update FE documentation

## Acceptance Criteria
- We have designs that show multiple on-site notifications that include a timestamp.

**Comment by aagosto90** [comment]
Sketch mockup for [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/2lPrLG/a/7y2Wq3Z/r/jQj0oz) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/2lPrLG/a/Gmgamo5/r/jQj0oz)

I'm thinking maybe we should just provide the date and not the time as well because on mobile it would likely go onto two lines. This does mean you could have multiple notifications with the same date but in that scenario, I would hypothesize the user would be seeing both for the first time and it would still look like multiple debts and not a mistake. Let me know if there are any objections to that.

I looked up content guidance for dates and this mockup aligns with that. Adding the time would have to be in the following format and takes up a decent amount of space on mobile: 3:00 p.m. 

Are we okay to move forward with this design @Samara-Strauss?

**Comment by aagosto90** [comment]
After [chatting](https://dsva.slack.com/archives/C909ZG2BB/p1652376128506049) with Angela Fowler, Christina and Liz, we've agreed on this design for [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/ZjgPOJ/a/oY2Y85j/r/l5QaKx) and this design for [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/JnlaE9e). We could consider putting the date on its own line between the notification text and the link, but it gets quite tall on desktop so my preference would be to consider that when we redesign the notifications and will have to incorporate different lengths of notification text. 

@Samara-Strauss What are your thoughts? CC @ajakabcin @ericasauv09 @tmitchellgcio

**Comment by Samara-Strauss** [comment]
Why did you decide to put the date before the action link? That order seems weird to me for both users who do and do not need a screen reader, but I am assuming you would have talked about this with Angela. Can you elaborate on that decision?

**Comment by aagosto90** [comment]
@Samara-Strauss Thank you for reviewing again! That was the original layout I had but since we can't use type any smaller than 16pt (same size as the notification text), in the Slack thread we thought it looked like body copy for the notification. My opinion is that we could go with either for now since we only have one type of notification and we know how much content it has, but it was a good point that if we did have a notification with additional body copy then this treatment wouldn't be ideal. I feel that it's a moot point since we're redesigning this notification anyway but I'm glad Liz and Christina brought it up so I can consider it in the redesign. If we would like to go with date last for now with the understanding that we'll implement a new design before any other notifications go live, I see no issues with it. Angela's only concern was wanting the text "You have a new debt" to be read out before the date.
<img width="920" alt="Screen Shot 2022-05-14 at 12 25 24 PM" src="https://user-images.githubusercontent.com/97965610/168440414-ca1c4201-f9a6-4cc6-9274-ae03529e0ddf.png">

**Comment by Samara-Strauss** [comment]
> If we would like to go with date last for now with the understanding that we'll implement a new design before any other notifications go live, I see no issues with it. Angela's only concern was wanting the text "You have a new debt" to be read out before the date.

I think this design in the screenshot is way stronger and makes more sense in terms of continuity (associating the notification and link before the date) than the one you linked to in sketch. I appreciate you all thinking long term about something scalable, but I do think it's a fair assumption that we'll keep working on this design before new notifications are added, so this works for now.

If possible, could you get feedback on this in your design team meeting today? I'd be interested in other folks' feedback, especially anyone on the design system council and Matt Dingee.

**Comment by Samara-Strauss** [comment]
> Are we good to move forward with this design?

Yes! I think we are.

And noted on the other comments you included. I agree with everything re: the alert style needing to be revisited overall, and this alert style not being perfect for the reasons you listed. We'll address that stuff through time and iteration.

**Comment by aagosto90** [comment]
[FE documentation updated here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend/documentation/README.md)
