### ISSUE TITLE
Populate the Feature Array column on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40700]
## Issue Description
We want to add features in an array to the product list. These should be formatted as valid JSON, so it can be parsed on ingestion to our different processes. The features of a product may be determined by an entry on this document: https://vfs.atlassian.net/wiki/spaces/VAProducts/overview that has a parent listed as one of our product entries, that does not have an entry itself.  Each of these feature objects should contain a feature name, launch date, status, and url.

Product List: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

---
## Tasks
- [x] Fill out the Feature Array column with properly formatted JSON for any relevant features

## Acceptance Criteria
- [ ] The Feature Array column is filled out with properly formatted JSON for any relevant features
- [ ] Any rows that have no features have their entry left blank

**Comment by rsmithadhoc** [comment]
Updated [Product Directory](https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0) with the known features and their metadata (for those features that aren't a product themselves) based on [VA.gov Products](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) Confluence page. 

I have a pending question out with the team on standardizing some data values but otherwise this can be reviewed.

**Comment by pjhill** [comment]
Nice -- that's a lot of populated fields!
