### ISSUE TITLE
Platform Website Updates - Research Opportunities/Findings

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40706]
## User Story
As a Governance team member, I want to update Platform Website to match the GitHub template so that the core ticket is easily navigated by VFS teams.

- Intended Audience: VFS Teams and PMs
- Desired Outcome: Updated GitHub ticket and documentation
- Due Date: 5/9 (Preparation for launch on 5/10)

## Description
Findings that have been prioritized as needing Platform Website & Confluence updates from [Research Findings spreadsheet (Pre Launch Improvements tab)](https://docs.google.com/spreadsheets/d/1_EGjrHtr3gEam72K4zEoFMdkQLBIvIjQ_lmes-RgWLw/edit#gid=1309674612).
All Documentation Updates should be made to draft pages in [Documentation Drafts - Core Ticket Guidance 38606](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2165440978/Core+Ticket+guidance+36086)
These changes will then need to be synced in the GitHub template.

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Tasks
- [ ] Opportunity Statement (OS): Clear documentation about what's needed at each phase of the CC that the PM can reference before getting started.
  - [ ] Platform Website: Update Platform Website to clearly detail needed information before each phase of the CC.
  - [ ] GitHub: Link to Platform Website detailing needed information
- [ ] OS: To best direct and inform teams "who" is responsible to input/attach Artifacts, specific direction should be given in Collaboration Cycle Touchpoint planning documentation.
  - [ ] Platform Website: Add directions detailing who is responsible for attaching artifacts
  - [ ] GitHub: Link to Platform Website
- [ ] OS: To best direct and inform teams how/where to attach Artifacts, more specific verbiage and directions should be put in place within Artifacts section, along with a descriptive of the particular Artifact needed for each PA.
  - [ ] Platform Website: Add helper text and directions to Artifacts section of each touchpoint
  - [ ] GitHub: Link to Platform Website
    - [ ] Evaluate helper text to include in GitHub template

## Acceptance Criteria
- [ ] Document updates have been completed
- [ ] GitHub tickets have been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket
