### ISSUE TITLE
Review RFC #4 and close out in favor of more specific RFC

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#40702]
## Issue Description

The [CIT Team RFC #4](https://github.com/department-of-veterans-affairs/va.gov-team/pull/40000) discusses the challenges and steps required to bypass Kong and route Lighthouse traffic from `vets-api` directly via the forward proxy.

Much of the discussion revolved around whether or not side-stepping Kong, even in the short term and in the dev environment was ok. Another open question is how to obtain a comprehensive list of vets-api routes that make an additional API call to Lighthouse. 

Since we've already started down to road of bypassing Kong in the dev environment, we might want to close out this RFC and create two new ones with a focus on:
1. How to coordinate bypassing Kong in different environments
2. Present current research finding on the list of `vets-api` endpoints that use LH and ask for input on adding to that list. Alternatively we could also open an RFCs for individual groups of LH enpoints, e.g. Health API, Benefits APIs

---
## Tasks
- [ ] Close RFC out with comment
- [ ] Create new RFCs after team discussion

## Acceptance Criteria
- [ ] Current RFC is closed
- [ ] New RFCs are created in its stead if appropriate
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
