### ISSUE TITLE
Audit of alerts on VA.gov

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40703]
## Issue Description

As part of our work for assessing alerts that are currently on VA.gov pages, we need to do an audit to find out the following information:

- Which info alerts are live
- Where they are appearing
- Whether each one is still current and accurate
- Whether any action should be taken: pull it down without incorporating the content onto the page in some other way / pull it down and incorporate the content onto the page / keep the content in the info alert but edit it so it's current and relevant / any other recommendation

We will create a separate ticket for implementing any changes to the alerts. 

## Tasks
- [ ] Reach out to the CMS team for help doing an audit of Drupal pages (Randi)
- [ ] Create document with the above information 

## Acceptance Criteria
- [ ] Alert audit complete

**Comment by RLHecht** [comment]
Lynn is checking to see if there's a report in Drupal that can give us the list of pages live alerts are appearing on.

**Comment by msbtterswrth** [comment]
There are two reports which might be useful: 

- https://prod.cms.va.gov/admin/content/alerts 
- https://prod.cms.va.gov/admin/content/vamc-alerts-and-statuses

I suspect the second will be the more useful of the two. If either of these isn't _quite_ what you need, feel free to reach back out and we can see what else we can create for you!

**Comment by RLHecht** [comment]
@msbtterswrth That would be perfect!

**Comment by RLHecht** [comment]
@EWashb Our team is looking to pick this work back up. Lynn had started on this but we never got a completed list where we could see what specific Drupal nodes these alerts are currently on. Is this something that's possible to give us? Thanks!

**Comment by EWashb** [comment]
Hi @RLHecht! I'll see if there's an easy way to get that link added that you need for that view to be helpful!

@edmund-dunn do you have any idea of the lift on adding the link (sort of like you've done for the PDF audit)?

**Comment by RLHecht** [comment]
@EWashb @edmund-dunn this is a super old ticket of ours, but wondering if there's still a way to add info to the alerts view in Drupal to see what nodes they are on.

**Comment by mnorthuis** [comment]
@RLHecht to open a CMS issue and then close this issue.

**Comment by EWashb** [comment]
Perhaps a view would be useful. There's no easy way to sort these. In the long term (once we figure out a view for these), is this a use case for ECA to sent notifications on a cadence? That would help relieve our manual processes. @gracekretschmer-metrostar fysa
