### ISSUE TITLE
Create Offboarding Instructions for Contractors Page on Platform Website

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40713]
## User Story
As a VFS team lead, I want to submit offboarding requests so that access lists are current.

- Intended Audience: Platform teams
- Desired Outcome: Accurate access lists
- Due Date: N/A

## Description
[Thread from slack](https://dsva.slack.com/archives/CJRQ85PQB/p1651253484070049) detailing situation where an offboarded user had access for 3 months after leaving. 

## New Artifacts 
Platform Website: Offboarding Instructions

## Tasks
- [ ] Review [GitHub document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/contractoroffboarding.md) for necessary updates
- [ ] Replace references of VSP to Platform
- [ ] Add details detailing who has the responsibility to submit the ticket
  - Verify with Chelen that it should be team lead

## Acceptance Criteria
- [ ] Platform Website: Offboarding Instructions has been created
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@shiragoodman I moved the page I created over to the source: https://vfs.atlassian.net/wiki/spaces/GS/pages/2221375655/Offboarding+Instructions+for+Contractors
Once I ensure it's been published on PW, I will link in PO template.  Once that is completed, all tasks will have been completed, and AC/US satisfied.

**Comment by shiragoodman** [comment]
@CherylEvans could you re-title the page to just, "Offboarding" ? I think "instructions for contractors" is unnecessary (and also, 100% clear who it's for as soon as you click on the link). Thank you!

**Comment by CherylEvans** [comment]
@shiragoodman Will do!!
