### ISSUE TITLE
Update Support bot to include Governance team

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#40715]
## User Story
As a VFS team member, I want Collaboration Cycle and Platform Orientation in the support bot so that I can easily assign tickets to the Governance team.

## Description
The support bot for #vfs-platform-support currently looks like this:
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/215ffe09-5e5b-431b-a37d-2f603967e13c)
There are 2 fields: 1) "I need help from" and 2) "What is the nature of the request?"
Under "I need help from", we should remove the "Collab Cycle" option and instead have "Governance team"

## Artifacts Needing Updates
Slack support bot fields
  - [Slack documentation: Viewing and updating support assignments](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2170192022/Viewing+and+Updating+Support+Assignments)

## Tasks
N/A

## Acceptance Criteria
- [ ] Slack support bot fields lists Governance team

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
Notes now that ticket is on hold. Brian requested access to Google Sheets file where support bot entries are stored.
