### ISSUE TITLE
FE | Auth-Profile |  Direct Deposit Feature | Display Consistently

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40722]
### Background

We would like to display the Direct deposit feature consistently so that whether or not a Veteran is receiving direct deposit payments (for disability compensation, pension benefits or education benefits) the direct deposit link and page will be viewable.

### Story

**Scenario 1.** As a Veteran who does not receive direct deposit payments for compensation and/or pension and/or education benefits
WHEN
viewing my Profile on VA.gov
THEN
I should see a link to the "Direct deposit information" page when viewing the list of navigation links

**Scenario 2** As a Veteran who is logged in with MHV or DS Logon 
WHEN
I navigate to the direct deposit page
THEN
I should see an alert message  prompting me to verify my identity

**Scenario 3** As a Veteran who does not receive direct deposit payments for compensation and/or pension and/or education
AND
I navigate to my direct deposit information page
THEN
I should see a message informing me that there is no record of my receiving direct deposit payments.

**Scenario 4.**  As a Veteran who does not receive direct deposit payments for compensation and/or pension and/or education
AND
I navigate to view my Direct deposit information page
WHEN
there is an outage or a system error that prevents the page from displaying, or a user's payment information won't load
THEN
I should see an error message within the direct deposit section (vs today where it is seen on Personal + Contact info)

**Scenario 5.** If a Veteran's account has a fiduciary flag or has been deemed incompetent (a flag will indicates this), they should not be able to view or access direct deposit information online. 
- today we are handling this by showing an alert on the _Personal and Contact information_ section, but we need to move this to the _Direct deposit_ section when the fiduciary flag is present.

### Tasks

- [x] **Scenario 1:** remove logic to display direct deposit conditionally  
    
- [x] **Scenario 2:** display alert to verify identity
     - [mock here](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/paW24nG)
     - the links inside the alert remain the same
     - make sure that all phone numbers are in aria labels. This includes putting "TTY: 711" in an aria label.
     -  [copy  is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/copy-updates-40722.md#verify-identity-alert-copy)
     
- [x] **Scenario 3:** no direct deposit alert messaging
     - [mock here](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/OmJpOLG)
     - [copy for each section is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/copy-updates-40722.md#compensation-and-pension-section)
     - use warning alert w/ no heading
     - make sure that all phone numbers are in aria labels. This including putting "TTY: 711" in an aria label. 
- [x] **Scenario 4:**  move error messaging from the _Personal + Contact_ info to _Direct deposit info_
     - [mock here](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/zxWvzOy)
     - there aren't any copy changes to the alert, but it might need to be updated from the _error alert_ to the [_warning alert style_](https://design.va.gov/components/alert#warning-alert).
- [x] **Scenario 5:** alert for the  fiduciary flag 
     - user should not be able to see anything else on the page besides the alert (the alert currently displays on the personal info page when the flag is detected)
     - [mock here](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmvQ3YE)
     -  there copy changes outlined in the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/copy-updates-40722.md#fiduciary-flag-alert-copy), and the alert needs to be updated from the _error alert_ to the [_warning alert style_](https://design.va.gov/components/alert#warning-alert).
- [ ] Delete the above ^ [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/copy-updates-40722.md#compensation-and-pension-section) once you are done with it in the spirit of decluttering :smile:

### Acceptance Criteria

- [ ] Complete all unit testing
- [ ] Deploy to Staging behind feature flag
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production

**Comment by andaleliz** [comment]
Added a link to the copy doc in the description above

**Comment by SKasimow** [comment]
Hi @mdewey - I cleaned up this ticket a bit but it still covers a lot of scenarios. Let me know if you would prefer that I break this up into multiple tickets.

@andaleliz - would you mind double-checking that I've put the links/content are in the right places? :)

**Comment by andaleliz** [comment]
@SKasimow, you basically got all of it! I made a couple of small clarifications, and moved the copy for scenario 2 into the separate copy doc so it's all in one place. I think that'll be easier for Mark.  Thanks for doing this!

**Comment by SKasimow** [comment]
@andaleliz YAY!!! Thank you for fixing the spacing between Task/Scenarios - I couldn't figure out why it wasn't working for all scenarios. Looks so much better! 👍 

 and THANK YOU for reviewing - I was moving things to and fro and afraid I'd miss something!

**Comment by mdewey** [comment]
QUESTION: For scenario 1 ( showing the DD page for all veterans). 

After looking at the code, I wanted to confirm a few things: 

- There is a flag called `isCNPDirectDepositBlocked` that is blocking the DD page for specific users. Is that going away or staying? 
- Does EDU vs CNP accounts matter? 

I am sure I will have more questions as I go 

cc: @Samara-Strauss @andaleliz  @SKasimow

**Comment by SKasimow** [comment]
@mdewey - I could hazard a guess on your questions but probably best to let @Samara-Strauss advise.
(Good learning for me though :) )

**Comment by Samara-Strauss** [comment]
> There is a flag called `isCNPDirectDepositBlocked` that is blocking the DD page for specific users. Is that going away or staying?

TBH I am not sure because I am unsure on what the flag is meant to do. Is it meant to block the feature for users who do not have direct deposit? Or is it meant to do something else? Can you gather this from the code?

> Does EDU vs CNP accounts matter?

Can you clarify this question? Previously, we showed the direct deposit section as long as users had eligibility for at least ONE type of direct deposit, or if they had eligibility for both. But since I'm not sure what you're asking, I'm not sure if this is the info you're looking for. Let me know what would be helpful.

**Comment by mdewey** [comment]
```
There is a flag called isCNPDirectDepositBlocked that is blocking the DD page for specific users. Is that going away or staying?
```

From what I can gather, this flag is set when:

A veteran is not competent, a veteran has a fiduciary, or when a veteran is deceased.

```
Does EDU vs CNP accounts matter?
```

That's actually exactly what I'm looking for! Thanks!

**Comment by SKasimow** [comment]
Hi @mdewey - for Veterans designated as not competent, has a fiduciary or deceased we will NOT show the DD page. We have this called out in scenario #5. 

>There is a flag called isCNPDirectDepositBlocked that is blocking the DD page for specific users. Is that going away or staying?
From what I can gather, this flag is set when:

A veteran is not competent, a veteran has a fiduciary, or when a veteran is deceased.

**Comment by mdewey** [comment]
Oh perfect! Thanks @SKasimow

**Comment by Samara-Strauss** [comment]
> From what I can gather, this flag is set when:
> 
> A veteran is not competent, a veteran has a fiduciary, or when a veteran is deceased.

To echo what Sharon said, this flag is *absolutely* staying in place, and it's really critical. It's essential that people with fiduciaries or who are incompetent are not be able to access this section. This is something we didn't know in the original implementation, and when VBA found out, we had to shut down this section of the profile immediately in order to implement the fiduciary flag. [Postmortem here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2020-02-21%20Direct%20Deposit%20Fiduciary%20Issue.md). It was really serious, so I can't stress enough that this flag stay in place. Let me know if you have any questions!

**Comment by mdewey** [comment]
Copy that! 

Do we have test users how are those things? I can dig, but I wanted to check before I do thayt

**Comment by mdewey** [comment]
Also, For LOA1 users, are still hiding the direct deposit?

**Comment by Samara-Strauss** [comment]
> Do we have test users how are those things? I can dig, but I wanted to check before I do that

[I noted test users here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/direct-deposit-comp-pen-fiduciary-blocking.md#staging-users), but I am unsure whether all of those users will work any more to validate this. Some of them worked when we put the original gate up a couple years ago, so hopefully at least one can be used to validate now.

> Also, For LOA1 users, are still hiding the direct deposit?

Yes, LOA1 users should only ever see the Account settings section of the profile. They should never see anything else.

**Comment by andaleliz** [comment]
>Hi @mdewey - for Veterans designated as not competent, has a fiduciary or deceased we will NOT show the DD page. We have this called out in scenario # 5.

@mdewey that statement is incorrect. They _**should**_ see the DD page, but only see an alert on the page as [mocked-up here](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmvQ3YE).

**Comment by SKasimow** [comment]
Sorry my comment wasn't clearer

**Comment by Samara-Strauss** [comment]
Yes -- thank you for clarifying Liz. People with fiduciaries can see the section but none of the information in it -- just the alert that says we can't show financial info in their profiles

**Comment by andaleliz** [comment]
@SKasimow it's ok! No need to apologize. I'm sorry if that came off as anything other than objective. It is confusing and I just wanted to ensure we didn't undo any logic that's already in place.

**Comment by mdewey** [comment]
Slack thread for questions answered: https://dsva.slack.com/archives/C909ZG2BB/p1652717313629189

**Comment by mdewey** [comment]
Created PR for component library changes : https://github.com/department-of-veterans-affairs/component-library/pull/434

**Comment by mdewey** [comment]
Hey team, this is now enabled in staging, I tested it my my personal staging account and `user+0`.  

I haven't tried any other users yet, but I am going to work through what I can. 

We should regroup maybe at the 16th minute during stand-up to figure out the next steps. 

cc: @Samara-Strauss @SKasimow @andaleliz

**Comment by SKasimow** [comment]
@mdewey - thanks Mark! I'll test as well

**Comment by Samara-Strauss** [comment]
Thank you! I'll run through a few test cases and let you know if anything looks off.

**Comment by SKasimow** [comment]
@mdewey: for scenario 3/no direct deposit alert messaging, I'm seeing the following text for the education section in staging:

![Screen Shot 2022-05-24 at 2 21 08 PM](https://user-images.githubusercontent.com/74627978/170105901-2fb15792-aaf5-4cbb-9300-9ab9042f192a.png)

But per mocks/copy the text should read:

Our records show that you don't receive VA education benefit payments or haven't set up direct deposit payments.

If you want to set up direct deposit payments, or you think this is an error, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by mdewey** [comment]
Thanks for the review @Samara-Strauss! I will let you know when the fixes are up!

**Comment by Samara-Strauss** [comment]
Everything looks good to me, @mdewey!

|Test case|User|Results|
|----------|-----|--------|
|User with a fiduciary sees the direct deposit section with appropriate error| 61| **Pass!** -- the errors on Personal Info and Contact Info have been removed.|
|MHV user stills sees the alert to sign in with ID.me or Login.gov | MHV test user | **Pass!** -- was able to test today, and everything is working as expected. |

**Comment by mdewey** [comment]
What are the next steps? Do we rollout to production??

**Comment by Samara-Strauss** [comment]
Great question! @SKasimow and I talked about doing an internal UAT with her and me, where we roll the feature out just to us. Since we aren't veterans, we should be able to see the feature in prod but not have access to the bank form. I might, just for good measure, want to get a couple of real veterans on the team to just make sure their information looks good and correct and the section wasn't affected for them (which it shouldn't be since we didn't do any work on the actual form). I see you are out tomorrow and Friday, so let's coordinate on this next week when you are back.
