### ISSUE TITLE
[FE] Customize "How can I update my information" Accordion based on Appointment Type

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#40736]
## User Story
Currently, PCI is only available for in-person appointments. As part of the roll-out to VIZN 8, we are being asked to extend the use of PCI to telephone appointments so that Veterans with telephone appointments can confirm their contact information using the Pre-Check-in feature.

## User Workflow
- Given I
    - Received a pre-check-in link after confirming an appointment (either in-person or telephone)
- When I
    - Click the pre-check-in link    
    - View the "How can I update my information" accordion 
- Then I
    - See accordion content that is based on my appointment type
         - For in-person
              - See the existing message
         - For telephone
               - See wireframe for new message

## Wireframes
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9438e87c-5780-474d-881c-6066ae3abf59)

## Tasks
- [ ] [FE] Display different accordion content based on appointment type
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)_

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
This is ready for UX review, see screenshot:
![Screen Shot 2022-06-13 at 3.07.10 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/0bebe567-b763-4749-a0e5-c6229d88b40a)

**Comment by loripusey** [comment]
To clarify, this only shows for telephone appointments, correct? @brianseek

**Comment by sarahknoppA6** [comment]
@brianseek to re-test today

**Comment by niradatta1** [comment]
@brianseek The above looks good for the telephone appointments scenario.

**Comment by brianseek** [comment]
@loripusey Yes this is the accordion content for phone appointments.

**Comment by brianseek** [comment]
@loripusey Yes this is the accordion content for phone appointments.

**Comment by brianseek** [comment]
Re-opening to add an e2e test for expired appointments
