### ISSUE TITLE
Add research host to Design and Research Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40749]
## User Story
As the UX Researcher on Governance team, I want to have a permanent role in the Design and Research Orientation so that I can meet and greet with new VFS designers, researchers, etc, and communicate best practices for research initiatives on VA.gov.

As a new VFS team member participating in the Design and Research Orientation, I want to know who the Platform Researcher is so that I can hear of research standards and best practices directly from the team/person responsible for enforcing them.

- Intended Audience: VFS and Governance
- Desired Outcome: Clayton is a regular attendee/co-host of the Design and Research Orientation and is familiar with the orientation roles and responsibilities.  
- Due Date: tbd

## Description
Now that there is a dedicated UX Researcher for Platform (@claytonzook), it would be ideal if Clayton participated regularly in co-hosting the Platform Orientation/Design and Research Orientation. The purpose of this ticket will be to ensure Clayton is familiar with the Roles and Responsibilities for hosting an orientation session, ensure our operational materials are up to date, and assess to see if any changes are necessary for Platform Website. 

## Artifacts Needing Updates
[Confluence: Orientation Sessions-Design & Research Orientation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Design-%26-Research-Orientation)

## Tasks
- [x] Clayton has read, understands and signed off on the [Roles and Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Roles-and-Responsibilities) of hosting Platform orientation sessions
- [x] Add Clayton as a cohost to [Confluence: Design & Research Orientation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Design-%26-Research-Orientation)
- [x] Review Research Session section for quick changes
  - Do not add extra content to the deck until entire slide deck is evaluated (potential initiative)

## Acceptance Criteria
- [x] Clayton understands his roles and responsibilities as co-host
- [x] Confluence: Orientation Sessions-Design & Research Orientation has been updated
- [x] Clayton has signed up for (or copied onto his calendar) all orientation sessions through December 2022
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [x] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [x] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby FYI

**Comment by claytonzook** [comment]
On Task 1, I'm not sure sure what it means by "signed off on the Roles and Responsibilities" is there a document to sign that I'm missing? @shiragoodman @chaseakirby

**Comment by shiragoodman** [comment]
@claytonzook i updated the AC to reflect the number of orientation sessions you need to sign up for.

**Comment by shiragoodman** [comment]
@claytonzook  - @chaseakirby is correct. I just need you to verify that you read the Roles & Responsibilities outlined and confirm that you know and understand your role. Checking the box in this ticket is sufficient.

**Comment by claytonzook** [comment]
In that case - this one is ready for peer review!

**Comment by shiragoodman** [comment]
looks good to me. Closing! fyi @chaseakirby
