### ISSUE TITLE
BE - Auth Profile - Military Info - Return service history from VA Profile

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#40758]
## Background

Build service layer to pull Military info from VA Profile instead of eMIS.
Swagger docs [here](https://qa.vaprofile.va.gov:7005/military-personnel)

## Tasks
- [x] Build Service Class
- [x] Build Models
- [x] Update Serializer
- [x] Update specs/VCR cassettes

## Acceptance Criteria
- [x] Military service history returning data from VA Profile
- [x] All existing and new specs passing

**Comment by tpharrison** [comment]
Hi @SKasimow - I need to push this to the next sprint.  The connection to VA Profile is working now, but there were some changes to the calls so I'm still reworking some things.

**Comment by SKasimow** [comment]
got it! thx
