### ISSUE TITLE
Populate Parent Product field on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#40750]
## Issue Description
Some products, may be a standalone product but still exist inside another. One example of this is the profile, which has many other products inside it such as direct deposit or user notification settings. These parent relationships should be noted and logged accordingly where necessary. If a reference document lists a parent as the same product as the product it's referencing, please leave it blank.

Product List: https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit#gid=0

Reference docs for parent relationships:
https://vfs.atlassian.net/wiki/spaces/VAProducts/overview
https://docs.google.com/spreadsheets/d/1szgVPBuBOnDBX6x0WgQFPxT7WMGgxnLXts2xwY4IV9s/edit#gid=0

---
## Tasks
- [x] Fill out the parent product field of the product list accordingly, utilizing the reference docs linked in the description.

## Acceptance Criteria
- [x] The parent product column has a value in all applicable rows.
- [x] Rows without an applicable value, or a value that matches the product name column, are left blank.
---
