### ISSUE TITLE
BE - Auth Profile - Military Info - Remove all unused eMIS code from profile

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#40762]
## Background

The use of the eMIS API is being discontinued and replaced by VA Profile.  Remove all profile service history references to eMIS code.

## Tasks
- [ ] Remove all service history code references to calling eMIS API.
- [ ] Remove all service history configuration related to calling eMIS.

## Acceptance Criteria
- [ ] All unused code and configuration removed related to profile service history.

**Comment by SKasimow** [comment]
Congrats!
