### ISSUE TITLE
Use CMS export in metalsmith

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#4076]
## Task
Substitute the GraphQL `node` query with the `tome-sync` output in the Metalsmith build.

## Goal
The new build process is testable.

## Acceptance Criteria
- [ ] The current build process isn't affected by these changes
- [ ] The CMS export data build process can take the place of the GraphQL query for the nodes when an option is passed to the build command

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
Blech, that didn't take long. Turns out this actually _is_ a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/2706. :man_shrugging:
