### ISSUE TITLE
BE - Auth Profile - Military Info - Update configuration settings

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#40761]
## Background

Update the following configuration files in devops to include VA Profile military info API endpoint.

## Tasks
- [x] Config set in devops/ansible/deployment/config/vets-api/dev-settings.local.yml.j2
- [x] Config set in devops/ansible/deployment/config/vets-api/staging-settings.local.yml.j2
- [x] Config set in devops/ansible/deployment/config/vets-api/prod-settings.local.yml.j2
- [x] Config set in devops/ansible/roles/review-instance-configure/templates/settings.local.yml

## Acceptance Criteria
- [x] Configuration files updated successfully
