### ISSUE TITLE
[Design] Benefits, Payment, and Debts v2 - Design Edits

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#40774]
## Issue Description

We received feedback from our design intent session on the initial Benefits, Payment, and Debts v2 design. We now need to implement that feedback and make edits to the design.

---
## Tasks
- [ ] Incorporate "must" notes from design intent feedback tickets:
    - [ ] Add active links to > as per design team's feedback in #40757 
    - [x] Update color contrasts as per accessibility team's feedback in #40699
    - [ ] Review how the titles for debts, copay, and payment are linked (noted in #40699)
- [ ] Review edits with team

## Acceptance Criteria

Final design edits for Benefits, Payments, and Debts are complete and ready to be reviewed with team.

---

**Comment by aagosto90** [comment]
Updated design for [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/ELmbGe2) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/jg20r4z). 

Added designs for what it would look like if a user has no bills for [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/jg20p1z) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/dl2GMAn).
