### ISSUE TITLE
My VA: Sprint 82 (9/7- 9/20)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40793]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. My VA Redirect - Launch to 100% (9/12), monitor analytics post launch
2. Onsite Notifications - Complete internal UAT
3. Payments V2 - Continue FE dev, submit QA request
4. Audit - start design work for nametag and apply for benefits sections, preliminary discussions on research

PTO
- Erica: Out in Afternoon 9/9
- AJ: 9/12 - 9/16
- Taylor: 9/9
- Samara unavailable: 9/12 afternoon, 9/13 & 9/15

## My VA Redirect (#41223)
**PM**
- [x] #42881
- [x] #46712

**FE**
- [x] #42881 

## On-site Notifications (#30611)
**PM**
- [x] #43278 _from previous sprint_

**Design/Research**
- [x] #45923 _from previous sprint_

## My VA Payment Info V2 (#43332)
**PM**
- [ ] #45929 _from previous sprint_
- [x] #45925 
- [x] #45968

**Research/Design**
- [ ] #45969

**FE**
- [ ] #45861 _from previous sprint_
- [ ] #45864 _from previous sprint_
- [x] #45865 _from previous sprint_
- [ ] #45866 
- [ ] #47288 

## My VA Payment Info MVP (#43337)
**FE**
- [ ] #45453 _from previous sprint_

## My VA Audit UX Improvements (#41934)
**Design/Research**
- [x] #42576
- [x] #41942
- [x] #46714

**Comment by Samara-Strauss** [comment]
For the audit, I had the following:

- Nametag and Apply for Benefits sections
- Preliminary research discussions -- do we want to test in code?

Should I move the nametag and preliminary research discussions back a sprint?

**Comment by ajakabcin** [comment]
I was just discussing that with @aagosto90  and @ericasauv09 - yes we're pulling in the nametag ticket. I was trying to gauge Angela's capacity (having zenhub trouble) to see if she could also take on the research discussions. Also need to figure out when we think we'll be ready for design intent

**Comment by Samara-Strauss** [comment]
OK, keep me posted. I can shuffle things around in long-term planning as needed.
