### ISSUE TITLE
Research and validate access to Kong via forward proxy

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#40799]
## Issue Description
The idea came up to create a new forward proxy port that routes traffic to Kong. This new port could be used by `vets-api` to send any external API request that currently requires Kong to route traffic. Eventually that port could be used to route to the _new_ API gateway.

Adding this new forward proxy port has several advantages:
1. Shorten the path to the API endpoint by side-stepping the current reverse proxy ALB
2. Make the CIT Team's work independent from the timelines of both the LH team that works on the new API gateway, and the Kong team that maintains the current API gateway.
3. Avoid the difficulties of routing API traffic without the intermediary of an API gateway.

This PR aims to research the general feasibility of this approach and determine whether we would need to make any changes to the Kong configuration. 

---
## Tasks
- [ ] Research full request path from revproxy -> vets-api -> Kong 
- [ ] Review current Kong configuration
- [ ] Research feasibility of setting up a forward proxy port to Kong

## Acceptance Criteria
- [ ] Feasibility of this approach is determined
- [ ] Execution and testing plan exists
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
