### ISSUE TITLE
Move VA.gov Experience Standards out of iFrame and into table

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#40810]
## User Story
As a person on the VA Network, I want to be able to read the VA.gov Experience Standards page on Platform Website so that I can be familiar with the standards and know they exist!

- Intended Audience: VFS, OCTO and other VA stakeholders
- Desired Outcome: VA.gov Experience standards are published in a table format
- Due Date: ASAP

## Description
Anyone on the VA network is not able to view the VA.gov Experience Standards because they are in an iFrame using Google Sheets. It is imperative that the business owners of VFS teams (VBA, VHA, etc.), as well as OCTO, have access to these standards as they are a key part of the Collaboration Cycle. 

## Artifacts Needing Updates
[Platform Website: VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
Confluence: [VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) operational guidance

## Tasks
- [x] Create [draft VA.gov Experience Standards page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2179661905/Shira+-+VA.gov+Experience+Standards) in Governance confluence space

## Acceptance Criteria
- [x] Confluence: VA.gov Experience Standards operational guidance has been updated
- [x] Platform Website: VA.gov Experience Standards has been updated to remove the iFrame and use a table instead
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket
