### ISSUE TITLE
Reworking COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40829]
## Issue Description
We have several updates to the [coronavirus FAQs page]https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) that need to be added to Drupal, copyedited and published. 

## Tasks
- [x] Make content changes in Drupal (Danielle)
- [x] Copyedit (Randi)
- [x] Use pre-publishing checklist (Randi)
- [x] Publish (Danielle)
- [x] Set up translation ticket (Randi)

## Acceptance Criteria
- [x] Live page has content updates
- [x] Translation process has started

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA when you make the updates to faqs page, can you note it here? Then we can publish them the same time we publish the symptom tracker link.

**Comment by RLHecht** [comment]
These changes were published today. I sent out the translation and will track that work in a new ticket. Closing this ticket.
