### ISSUE TITLE
Setup new forward proxy port to Kong

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#40826]
## Issue Description
We want to create a new port in the HAProxy (forward proxy) configuration that goes to Kong. This is in order to allow testing the possibility of making use of Kong as an API gateway, while at the same time preparing for a smooth transition to the switchover to Apigee, the new API gateway.

---
## Tasks
- [ ] Set up new forward proxy port and configuration in DEV
- [ ] Alter `vets-api` DEV settings for the Facilities API from the forward proxy port to LH to the new forward proxy port and confirm that Datadog tests are passing
- [ ] Alter Datadog test for Address Validation API (non-LH service) to use new fwdproxy port and confirm it still passes

## Acceptance Criteria
- [ ] New fwdproxy configuration has been set up in DEV
- [ ] Facilities API DD test are passing
- [ ] Address Validation API DD tests are passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
