### ISSUE TITLE
Documentation for Datadog APM for vets-api

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#40830]
We need to provide some documentation on how to setup/maintain this as well as provide a purpose for its existence. DataDog is used for APM for vets-api and platform-console. APM metrics are currently funneling into DataDog via the agent and can be viewed on the dashboard. There’s currently no documentation explaining the purpose or maintenance of DataDog. We should create some documentation to ensure maintainability and standardization.

## Acceptance Criteria 
- [x] APM Documentation is created in Confluence

## Tasks
- [x] Create documentation for internal maintenance
- [x] Discuss if we need a vfs facing doc
