### ISSUE TITLE
[Vets-API / EKS] Feedback and technical issues for migration in DEV

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#40838]
## Description
The Platform Infrastructure team is planning to migrate Vets-API from BRD to EKS. This issue will be used to capture feedback and technical issues that occur during or after testing. 

- Testing to begin May 4th, 2022
- Testing may cause intermittent issues w/ Vets-API in dev
- The Platform Infrastructure team is prepared to roll back changes that create significant blockers
- Comments, links, or other artifacts can be linked to this issue for tracking 
- Feedback and issues will be reviewed by the Platform Infrastructure team 

## Background/context 

- _Please see parent initiative_ #35039
- [Migration plan in Confluence](https://vfs.atlassian.net/wiki/spaces/OT/pages/2163703837/2022-04-19+Vets-API+migration+plan+for+DEV+WIP)

## Technical notes

- For more information about the approach, see #39687

---
## Tasks
- [x] Capture feedback and technical issues related to migration testing beginning May 4th
- [x] Create issues as needed to track action items 

## Acceptance Criteria 
- [x] Technical issues have been recorded
- [x] Action items and/or issues have been created _(as needed)_

**Comment by jhouse-solvd** [comment]
**Add comments, links, conversations, issues, PRs, or other info below to capture feedback and technical issues encountered by developers or end-users.** 

Info shared will be reviewed by the Platform Infrastructure team beginning May 5th, 2022. 

The Platform Infrastructure team will be in contact for clarification and/or as issues are resolved.

**Comment by ph-One** [comment]
![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/38c09ce3-99a7-4c11-9b76-cbee07061b40)

**Comment by madebydna** [comment]
I had set up a DD synthetic API tests for a `vets-api` endpoint in dev, which was working before the move to EKS. Now it's failing with a "Service unavailable" error: https://app.datadoghq.com/synthetics/details/y4q-pin-pez?live=1h. Any ideas what could be causing this?

For some background: it's an endpoint that makes a LH API request and I had changed the `vets-api` setting to use the forward proxy address. Originally we used the C Name ([fwdproxy-dev.vfs.va.gov](http://fwdproxy-dev.vfs.va.gov/) ) but since that was not working we changed that to the AWS internal name [internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com](http://internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com/) . I know the fwdproxy is not in EKS, so perhaps there is some networking issue at play (?)

**Comment by mleclerc00** [comment]
> I had set up a DD synthetic API tests for a `vets-api` endpoint in dev, which was working before the move to EKS. Now it's failing with a "Service unavailable" error: https://app.datadoghq.com/synthetics/details/y4q-pin-pez?live=1h. Any ideas what could be causing this?
> 
> For some background: it's an endpoint that makes a LH API request and I had changed the `vets-api` setting to use the forward proxy address. Originally we used the C Name ([fwdproxy-dev.vfs.va.gov](http://fwdproxy-dev.vfs.va.gov/) ) but since that was not working we changed that to the AWS internal name [internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com](http://internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com/) . I know the fwdproxy is not in EKS, so perhaps there is some networking issue at play (?)

I am able to curl both of these URLs just fine from the datadog agent in dev, are you sure you have the correct port? Otherwise it will hang.
![image](https://user-images.githubusercontent.com/76792875/167683810-f6f5e847-7734-4919-9403-3b4f174272d2.png)

**Comment by mleclerc00** [comment]
Yeah, I was just using a port I pulled at random to make sure it wasnt a connectivity issue between the eks worker nodes and forward proxy which it doesn't seem to be.  I can also curl forward proxy from vets-api in eks since both requests come from the same instances (eks worker nodes)

**Comment by madebydna** [comment]
Hmm, so does an empty reply not usually point to a connectivity issue? Did you try the same request from the worker node with a different port, e.g. 4492?

**Comment by mleclerc00** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/76792875/167703981-764a50ce-8fdd-40af-864d-644886f19315.png">

**Comment by madebydna** [comment]
That's interesting, so the new port 4492 works, but not the one that goes to LH directly (4451)? I'm wondering if that's an TLS issue, since the new port only uses http and has no TLS stuff involved, since it's an internal call and doesn't leave the dsvagovcloud environment? The old port is set up to use https and is an external call.

**Comment by madebydna** [comment]
@mleclerc00 could you try a couple of these additional ports: `4431`, `4448`, `4430`? These are all present in the vets-api dev settings file as fwdproxy urls and they all have TLS settings in the fwdproxy. Just curious if the issue is limited to the `4451` port.

**Comment by mleclerc00** [comment]
All three of those ports also come back with the error

`curl: (52) Empty reply from server`

**Comment by mleclerc00** [comment]
seeing some ssl handshake errors in the fwdproxy logs

<img width="829" alt="image" src="https://user-images.githubusercontent.com/76792875/167730664-be4ef094-3583-4d24-b13e-f3c46da69120.png">

https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-5m%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22fwdproxy%5C%22%7D%20%7C~%20%5C%22handshake%5C%22%22%7D%5D

**Comment by madebydna** [comment]
Okay, so I predict that some paths that use those fwdproxy settings might be broken. To make sure, one would need to dig into which vets-api endpoints use those settings and then check which frontend va.gov site pages use those vets-api endpoints. For my own purposes, I can actually just switch to using the new Kong port in the fwdproxy, but this points to a larger TLS issue.

**Comment by mleclerc00** [comment]
> Okay, so I predict that some paths that use those fwdproxy settings might be broken. To make sure, one would need to dig into which vets-api endpoints use those settings and then check which frontend va.gov site pages use those vets-api endpoints. For my own purposes, I can actually just switch to using the new Kong port in the fwdproxy, but this points to a larger TLS issue.

@madebydna 

I failed to test this on ec2 vets-api yesterday but the tls issue is not exclusive to eks.  This is also happening on our current BRD deployments as well
<img width="787" alt="image" src="https://user-images.githubusercontent.com/76792875/167925720-716efa01-a1ee-4b0a-b8b3-547aea5f338e.png">

**Comment by madebydna** [comment]
That interesting because it points to something like an expired SSL cert? This was definitely working in the recent past. How about those other fwdproxy ports (4431, 4448, 4430)?

**Comment by mleclerc00** [comment]
From dev vets-api ec2 instance 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/76792875/168154528-3c9c8060-6371-430f-9f33-3d5efa3b94b8.png">

Feels like there is something missing here, you say this was working in the recent past.  Do you have an example of a working synthetic on one of these ports?

**Comment by madebydna** [comment]
Yes, in fact I do! Here's an example: https://app.datadoghq.com/synthetics/details/y4q-pin-pez?from_ts=1651053600000&to_ts=1651139940000

It's a bit confusing, because I've been using the same test for validating various changes, so the backend vets-api code was different at that time. At the point of the passing test, it was using port `4451` and passing. Then the move to EKS happened and I noticed that the same test (using the same port) was failing. That's when I _noticed_ the failure, so it could have been independent of the move to EKS. 

Currently, the test is stiff failing but with a different error (authentication issues), because I've now changed the vets-api port to one that doesn't use TLS (4492).

**Comment by madebydna** [comment]
@mleclerc00 are there any updates on the SSL issue? I'm asking because I just realized that I will need to change the new fwdproxy port (4492) to use https after all, but I'm concerned that I'll run into similar problems.

**Comment by mleclerc00** [comment]
> @mleclerc00 are there any updates on the SSL issue? I'm asking because I just realized that I will need to change the new fwdproxy port (4492) to use https after all, but I'm concerned that I'll run into similar problems.

Given that this is not something directly related to the eks implementation, this will probably need a separate ops issue to be filed, scoped out, and prioritized if the infra team is going to dig into it further. 

Tagging @jhouse-solvd here for guidance

**Comment by mleclerc00** [comment]
@madebydna 

Was just looking at this a little more and I am able to hit the health endpoint through forward proxy on the vets-api eks dev instance. 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/76792875/168667914-540992aa-5c71-4fb2-bc30-6e62b46eb88f.png">

**Comment by madebydna** [comment]
Oh you mean curl was using the default `http` when you didn't specify the protocol before? That makes sense. I'm still wondering why this DD test was failing for several days ([between May 5 and 13](https://app.datadoghq.com/synthetics/details/y4q-pin-pez?live=1m)) when the `vets-api` url should have been https and did not get changed? 

Anyway, it doesn't matter as long as it works now! 🙂  I will submit a PR to change the new fwdproxy port to an https one and hope that it will work.

**Comment by jhouse-solvd** [comment]
This issue can be closed.
