### ISSUE TITLE
Write documentation for Console Services team orientation

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#40847]
## Issue Description
The Console Services team needs documentation for orienting new members to the team.

---
## Tasks
- [x] Gather existing orientation documentation
- [x] Create any additional documentation that is needed

## Acceptance Criteria
- [x] Documentation is gathered together/created that covers all essential information a new team member on Console Services should need.
---

**Comment by npeterson54** [comment]
Docs look good to me
