### ISSUE TITLE
The Console UI Needs a Google Analytics Property ID

### ISSUE THREAD

**Issue by jchapin** [department-of-veterans-affairs/va.gov-team#40853]
## Issue Description

The Console UI is a new site for providing access to interactive tools to VFS Engineers and other Platform stakeholders building The VA Platform.

We need to track the usage of the Console UI to determine if and when functionality in the site is being used. The data collected will inform our user experience research and our onboarding/marketing message to improve functionality and bring on as many users as possible.

This Google Analytics ID will be used on all of our environments:

https://platform-console-ui-dev.vfs.va.gov is live.

test, staging, and utility will be available shortly. Their hostnames will be similar to the dev environment above.

---
## Tasks

- [ ] We need a GA4 property ID string for implementation within the Console UI.
- [ ] The property name should just be Console UI for now.

We don't need any implementation help for plugging that ID into our system.

## Acceptance Criteria

- [ ] When given the ID @ericvoshall will be unblocked for this issue: https://github.com/department-of-veterans-affairs/platform-console-ui/issues/373 and will be able to proceed setting up Analytics for our app.

**Comment by obrienjulie** [comment]
Hi @jchapin  - We have the GA property set up and I will slack you the GA ID. We do have a couple of questions regarding this implementation:

	* Do you want anything auto tracked or are is your team handling everything?
	* I noticed you just gave us the dev URL, do you have the production url?  We can have everything push to the same GA ID and we can filter out the environment by hostname and/or URL. 
	
Let us know when you have data and we can turn on the BigQuery export.

**Comment by michelle-dooley** [comment]
We are closing this ticket,  please let us know if you have any further questions for support.
