### ISSUE TITLE
Copy edit 2 Drupal pages about transferred education benefits

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40855]
## Issue Description
Beth created a new tier 1 page about transferred education benefits for family members. As part of that work, she also updated the existing tier 1 page [Transfer your Post-9/11 GI Bill benefit payments](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/). 

Our team needs to do a copy edit of both these pages in Drupal.

Preview links:
New tier 1 page: http://preview-prod.vfs.va.gov/preview?nodeId=44698
Existing tier 1 page: http://preview-prod.vfs.va.gov/preview?nodeId=952

## Tasks
- [x] Copyedit new benefit detail page (Megan)
- [x] Copyedit existing benefit detail page (Megan)

## Acceptance Criteria
- [x] Both pages have been copyedited and ready to pass back to Beth

**Comment by megzehn** [comment]
These are copyedited! I also put some [suggested PL edits at the top of this Google doc](https://docs.google.com/document/u/1/d/1aSrpV-mma_1OWgE10buo5J1s7RwsYzmJjzVY5aCdLtE/edit). @bethpottsVADEPO could you take a look when you get some time?

**Comment by bethpottsVADEPO** [comment]
@megzehn Thanks for these great plain language edits. I will run them by stakeholders. The only edit that I think may have changed the meaning (though I'm not sure because the way it's currently written on the live site is also unclear) is this:
"... or to look up specific questions about services"

I think the original messaging ("service-specific questions") is referring to service in the sense of serving in one of the branches of service (like the Air Force or Army). I'm going to see what stakeholders say about that. Will let you know for awareness.

**Comment by RLHecht** [comment]
Work is complete. Closing ticket.
