### ISSUE TITLE
[Research epic] Veteran Top Task Research (moderated and unmoderated)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#40857]
This research will inform the March 2022 redesign for the VA.gov homepage. It is likely that the findings will be broadly applicable across the ecosystem. 

## Related artifacts
- [Initiative brief for the Homepage iteration - March 2022](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/home-iteration-initiative-mar2022)
- [Baseline Wayfinding Research on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/research#baseline-wayfinding-research-on-vagov--april-2021)

## High Level User Story/ies

- As a Veteran I want to be able to access self-service tools and processes quickly and easily so that I can manage my own VA benefits
- As a Veteran, caregiver or family member, I want to be able to learn about the different benefits available to me so that I can apply to these benefits.

## Tasks
Moderated research
- [x] [Research] Draft Research Plan - Veteran Top Tasks #36219 
- [x] [Research] Draft Conversation Guide - Veteran Top Tasks - #36878 
- [x] [Research] Compile list of tasks for survey -Veteran Top Tasks #36618
- [x] [Research] Prep Tasks -Veteran Top Tasks - #36676
- [x] [Research] Conduct Research - Top Task Moderated sessions #41565 
- [x] [Research] Research synthesis and reporting - Top Task Moderated sessions #41564
- [x] [Research] Post Research Tasks - Top Task Moderated Sessions - #41566 

Unmoderated research
- [x] Create draft research plan - #36219
- [x] Create draft convo guide - _not needed_ 
- [x] Research prep tasks - #36617
- [x] [Research] Monitor unmoderated Top Task participation #41582
- [x] [Research] Research synthesis and reporting - Top Task Unmoderated sessions #41583
- [x] [Research] Post Research Tasks - Top Task Unmoderated Sessions #41585
