### ISSUE TITLE
Update COE loan history date inputs

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#40856]
## Background
When a veteran is entering their VA home loan history, they are presented with inputs to enter the closing date of the loan and the paid-off date of the loan. Both of these inputs currently ask the user to input the month, date, and year, but the prototype only calls for month and year.

## Considerations
This is a schema change, so `vets-website`, `vets-api` and `vets-json-schema` need to be updated.

## Tasks
- [x] Update schema
- [x] Make needed changes to the frontend code (`vets-website` repo)
- [x] Make needed changes to the backend code (`vets-api` repo)

## Acceptance Criteria
- [x] A PR to `vets-json-schema` has been requested for merging
- [x] A PR to `vets-website` has been requested for merging, if applicable 
- [x] A PR to `vets-api` has been requested for merging, if applicable
