### ISSUE TITLE
[Design] - Audit Direct Deposit documentation 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40862]
## Background

We have an opportunity to improve documentation across our team's products and features. We're going to use DD as a pilot for improvements.

We'll start by auditing the docs to create a list of things we need to update and add to make our DD docs more comprehensive, and easier to navigate.

## Tasks

- [ ] Audit direct deposit documentation (add below)
- [ ] Create list of gaps, get feedback from team
- [ ] Share w/ PO, PM

**Comment by andaleliz** [comment]
Hi @mdewey, @tpharrison, @adamwhitlock1, @SKasimow and @cgednalske!  I'd love to get your input on a portion of this audit.

I'm curious to hear how the [current direct deposit docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit) meet your needs as a practitioner on the team, especially in terms of information that might be missing from the docs that help you understand the feature, and do your work.

For example, [this section with backend information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/direct-deposit#backend) _seems_ OK to me, but we'd each use that info in different ways.   

There isn't a "frontend" section - does there need to be?

**Comment by tpharrison** [comment]
Hey @andaleliz - these docs are helpful.  

I'd like add a link to a doc that gives a BE developer a solid technical overview of the solution.

Also, next sprint, I'm working on setting up alerts that trigger based on error rate, so the SLOs you outlined should give me a great target.

Thanks!

**Comment by adamwhitlock1** [comment]
When reviewing the docs I did realize that the Error handling section [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md) actually is FE specific, so maybe that should go under a "Frontend" heading and further documentation/links for any FE specific needs could also go there.

I think the docs cover the overall features and details of what is involved. A general overview of the structure of the FE code would be valuable to me, but I don't see that type of thing really present in other docs, so not sure if that would live here or in a readme of the actual FE app code folder 🤷🏼

**Comment by andaleliz** [comment]
Thanks for the feedback everyone! I have a couple of follow up questions:

1. @tpharrison you said "I'd like add a link to a doc that gives a BE developer a solid technical overview of the solution." That sounds like something that would certainly be valuable. I'm curious if that already exists (do you know?). Adam mentioned a similar thing about FE code in a later comment, but suggested perhaps it would live in the actual FE app code folder.  Is there a best practice for BE docs regarding this kind of thing?

2. @SKasimow I can see how that would be helpful! Have you had this as part of other product documentation you've worked on, or seen examples? If so I'd love to see them in order to get a better idea of the level of detail you're thinking of. Part of me thinks perhaps a Sketch prototype would work to serve that purpose.

3. @adamwhitlock1 you said "maybe that should go under a "Frontend" heading and further documentation/links for any FE specific needs could also go there." Are there other any FE specific docs you can think of that should be here, that aren't?

**Comment by tpharrison** [comment]
@andaleliz - there is BE technical documentation out there, but I want to add documentation that focuses specifically on helping a BE engineer supporting the auth-experience.  For example,  docs that will should which vets-api endpoints and external datasources support the following areas of the app:

- Personal Information
- Contact Information
- Military Information
- Direct Deposit Information
- Notification Settings
- Account Security
- Connected Apps

Also document the BE metrics, logs, and errors for each of the above; where they go, how to query and monitor them. It's a WIP and I'm chipping away at it, but I'd love some feedback from the team as I finish portions of it.

**Comment by andaleliz** [comment]
Oh cool, @tpharrison that sounds super useful! I'd be happy to help with feedback as you finish portions of it.  For now, I'll note this and add a placeholder in the docs. Thank you!

**Comment by SKasimow** [comment]
Hi @andaleliz - here is a link to one of the Sketch flows Dene did for [10-10EZ short form](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/EL9RYvqrl). She also includes notes in some to clarify the flows and changes.

**Comment by andaleliz** [comment]
Thanks @SKasimow and @adamwhitlock1 for the extra info. I can see it def making sense to have a "getting started" section for all of profile.  We'll cast a wider net on docs once we see how the direct deposit docs shake out.

**Comment by andaleliz** [comment]
@Samara-Strauss here's what I'm thinking we can do to improve the current documentation. Let me know if anything needs more clarification or if there's something that needs to be added. I broke it out into things we need to update, and things we need to add.

### Updates
#### Product Outline
- Update to include latest updates to conditional logic

#### All docs
- Clarify abbreviations and add links where it makes sense (e.g. spelling out the full name of a backend service and linking to docs about it)


### Additions
#### Product Outline
- Add a "What to know about the product" section or similar in Feature Overview section; something easily scannable/readable so anyone (esp. people not on our team) can understand what it does.
  - [This is a good example of info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/what-benefits-use-which-direct-deposit.md) I think should be in this type of section
- Any legacy info about the product that might be helpful
- Create a "getting started" BE engineering doc (add a placeholder for now)

#### Use cases
- Document all use cases (not just edge cases)
#### Flow documentation
- Wireflow of feature for visual overview

#### Misc
- Create reference to direct deposit documentation from profile product folder

**Comment by Samara-Strauss** [comment]
This all sounds great! Let me know where I can help in terms of providing information/background/knowledge.

Is it safe to assume that anything not marked "product outline" would be linked to from the product outline? I'm assuming not all of this will be in the actual product outline markdown file itself since it would get too long.

**Comment by andaleliz** [comment]
Oh good! I'm glad this looks good to you. I will certainly be tapping you for info.

>Is it safe to assume that anything not marked "product outline" would be linked to from the product outline? I'm assuming not all of this will be in the actual product outline markdown file itself since it would get too long.

Definitely. 

@SKasimow we'll need to figure out how to break down this work and create issues for the team. Design should definitely do the wireflow updating, which I can do in sprint 74. 

Some of the other updates are product related, and at least 1 engineering doc needs to be created (I think Tom said he's already working on it). Do you have bandwidth to tackle some of the more product specific updates, perhaps the conditional logic updates + the general use cases? So far I've [documented edge cases here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/use-cases), but not the broader use cases.

I'm going to close this out since the tasks for this ticket have been complete.

**Comment by andaleliz** [comment]
If you're OK with it, let's slot it all for me in Sprint 74 and move whatever doesn't get done into Sprint 75.
