### ISSUE TITLE
Tressa's Onboarding Checklist

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4086]
### Get access to tools

[Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)

- [x] Slack
- [x] Github

### Docs to review

- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to learn the syntax for formatting documents in GitHub
- [x] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] PM, designers, and content writers: Request IA intro

### Folks to meet with

- [x] Intro with Dawn (Ad Hoc PM lead)
- [x] Intro with Shawna (Ad Hoc design lead)
- [x] Intro with Samara (VA authenticated experience team lead)
- [x] Intro with Andrea Hewitt with VSP

**Comment by MickinSahni** [comment]
Hey @Justin-Pickett, in terms of helping Tressa on-board from a product perspective, we should also cover 

- the team's charter (mission, vision, etc.)
- any relevant product outlines/briefs/critiques
- our KPIs so they have a better sense of what's important to you, Samara, and the team

**Comment by sshein** [comment]
Hi all - just wanted to say what I'll cover while onboarding Tressa:

**Comment by sshein** [comment]
Hi all - just wanted to say what I'll cover when onboarding Tressa:
- Introducing her to the design team and our weekly

**Comment by sshein** [comment]
Hi all just wanted to say what I'll be doing when onboarding Tressa:
- Introducing her to the design team and inviting her to weeklies
- filling her in on slack norms/expectations
- giving her access to design resources including:
-- VSA onboarding doc with design resources including sketch file, design system, etc
-- VSA expected prod/design workflow 
-- the VSA research process doc 
-- expectations regarding reviews w/ VSP (still in progress)

**Comment by sshein** [comment]
FYI Tressa met with Dawn and myself today

**Comment by Samara-Strauss** [comment]
Just added @tressaellen to this ticket!

**Comment by Justin-Pickett** [comment]
@Samara-Strauss  and @tressaellen There is only a "IA" intro outstanding according to this ticket. So i will close this ticket and consider it done for Sprint 11 and work with VSP and Tressa to be sure she  completes her IA intro.
