### ISSUE TITLE
Update links on the research artifact templates

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40877]
## User Story
As a VFS team member, I want relevant research links so that I can have useful links to additional information.

- Intended Audience: 
- Desired Outcome: 
- Due Date: 

## Description
There are some outdated links on both the Research Plan Template and the Conversation Guide Template - some are dead links, others point to an out of date github page when they should point to Platform.

## Artifacts Needing Updates
- [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

Although not currently in use and still be developed as of this ticket creation, the following will also need to be updated
- [Trauma-Informed Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md)
- [Trauma-Informed Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md)

## Tasks
- [x] Update links on [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [x] Update links on [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
- [x] Update links on [Trauma-Informed Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md)
- [x] Update links on [Trauma-Informed Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md)

Items to update on the Research Plans
  - Method > Add'l resources > Recruitment guidance should be:
https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html
   - Method > Add'l resources > mobile link should be:
https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Researchingwithmobileusers
   - Method > Add'l resources > unmoderated research
https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html
   - Method > research materials > unmoderated testing link should be:
https://depo-platform-documentation.scrollhelp.site/research-design/Planning-Unmoderated-Studies.1904738369.html
   - Also consider adding links to moderated
   - Timeline - consider changing to 10 days so to include review and revision time
   - Timeline > length of session > break rec should up to 30 min

Items to update on the Conversation Guides
   - Moderator logistics > observer instructions link should be:
https://depo-platform-documentation.scrollhelp.site/research-design/Observer-guidelines.1622311177.html
   - Consider linking checklist in same section
https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-5.Conductsessions
   - Sample Conversation Guides > first link is broken

## Acceptance Criteria
- [x] [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) links have been updated
- [x] [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md) links have been updated
- [x] [Trauma-Informed Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md) links have been updated
- [x] [Trauma-Informed Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-conversation-guide-template.md) links have been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by jimuhh** [comment]
@claytonzook I'm seeing the various places where the Research Plan Template links to documentation in GitHub but don't see where the Confluence versions are.

**Comment by claytonzook** [comment]
@jimuhh On this ticket, under "Tasks" the sections "Items to update" should include the platform pages to link instead of the GH pages that are currently linked at each location. I don't think there should be any Confluence docs to link, just Platform pages.

**Comment by jimuhh** [comment]
Ah OK. I see now. Thanks.

**Comment by jimuhh** [comment]
@claytonzook With your permission, I'd like to restructure the first section of [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md) a bit, and add a couple of headers to make it clearer exactly what needs to happen when.

**Comment by claytonzook** [comment]
@jimuhh I'd be interested in that. I think this document could benefit from your IA insight

**Comment by jimuhh** [comment]
Cool. Will do.
