### ISSUE TITLE
Remove references to Lauren Alexanderson as the research reviewer

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40876]
## User Story
As a VFS researcher I want to make sure I contact the correct person so that I can address my needs

As Platform Governance Team, we want to make sure Platform pages we edit have to most updated information so that we don't cause confusion.

- Intended Audience: 
- Desired Outcome: 
- Due Date: 

## Description
Since Lauren Alexanderson has departed from the role of research reviewer or working with Perigean, references to contacting her for these issues should be addressed.

## Artifacts Needing Updates
- [Platform Recruiting Participants page](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html)

## Tasks
- [ ] Check other places where Lauren's name might need to be switched for Shane

## Acceptance Criteria
- [ ] [Platform Recruiting Participants page](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
This should be ready to go now.

After a check on Platform, I didn't find any other instance of Lauren mentioned other than this page. I simply removed references in both of these places to a specific person, since I didn't see it as important to include here. There are other places where it makes more sense to specify a name - when contact is specifically needed.

Note - I did add a couple of links while already editing this page. Two point to the Research Review touchpoint, two other are in the "In-person moderated studies" section.

**Comment by chaseakirby** [comment]
Updates and added links look good! Closing out this ticket.
