### ISSUE TITLE
Move Accessibility focused research guidance and check list to Platform Website

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40879]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

- Intended Audience: VFS teams
- Desired Outcome: Guidance available on Platform Website and deprecation message in GitHub
- Due Date: N/A

## Description
Ticket #41695 has been merged into this ticket.
This ticket is to move the two GitHub pages from GitHub to Platform Website and notify Josh of the new process for updating.

Researching with assistive tech (AT) participants requires different considerations than for participants who don't use AT. There is some [guidance on VA github for researching with AT participants](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech/research-checklist.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

Researching with participants who use screen readers requires different considerations. There is some [guidance on VA github for researching with participants who use screen readers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech/screenreaders.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## New Artifacts 
Child pages under [Conducting Research Sessions](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773061/Conducting+Research+Sessions)
  - New Page for researching with AT participants
  - New Page for researching with participants who use screen readers

## Tasks
- [x] Guidance has been created and maintained by @joshkimux. Notify Josh of the intention to move to Platform Website.
- [x] Verify with @joshkimux that all content within the existing GitHub pages is current and up to date.
- [x] Create guidance as separate child pages under [Conducting Research Sessions](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773061/Conducting+Research+Sessions)
  - [x] Add [Platform Website footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro) to new pages
- [x] Notify Josh how he can suggest changes to the page once on Platform Website using the "Create an issue ticket to suggest changes to this page" bullet in the footer
- [x] Add deprecation message to each GitHub page with link to Platform Website [using this guidance](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1397194753/Deprecate+a+page+in+GitHub)
- [x] Once page is created, update link on [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) under Methods > Add'l Resources
- [x] Once page is created, update link on [Trauma Informed Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/draft-documents/trauma-research-plan-template.md) under Methods > Add'l Resources

## Acceptance Criteria
- [x] Platform Website: Research with Assistive Technology Users has been created
- [x] Platform Website: Screen Reader Checklist has been created
- [x] Platform Website: Disability Etiquette has been created
- [x] Josh understands the new location and how to suggest edits to the pages
- [x] Documents are linked under additional resources in the Research Plan template
- [x] Users are aware that the GitHub pages have been deprecated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by joshkimux** [comment]
Brian reached out to me and I am _super_ excited about this. Thank you so much @claytonzook for pushing this forward. Some comments:

- Content is as up to date as it will be for the time being (for now). There's a version 3 document in the making, but it likely won't be complete until later this fall. 
- Would love to learn how I (and the rest of the folks working on this in the #inclusive-research channel) can write up tickets to suggest changes when we complete version 3.

**Comment by claytonzook** [comment]
@joshkimux I'm excited that we are getting this over to Platform! and grateful to have Brian working on the move. Updating on Platform will add hopefully only a small layer of complication. 

- Each page on Platform should include [a page footer titled Help and Feedback](https://depo-platform-documentation.scrollhelp.site/research-design/research-overview#Pagefooter-Helpandfeedback). 
   - That footer includes a link to submit a ticket, which goes to the Content/IA team. 
   - Since it's a research page they should route it to me, but you could also add me and/or Brian as an assignee or tag us on a comment
- If it's a simpler change, like rewording a sentence or two, should be able to get to it pretty quickly
- Larger changes we may want to consider a process for. We can discuss further when the time comes, like when version 3 is ready, but perhaps updates or documentation from either a GH page or a google doc that could then be copy/pasted over to the Platform page

**Comment by briandeconinck** [comment]
Draft pages created in Confluence for:
- [AT Research Checklist and Disability Etiquette](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242871321/Draft+Brian+-+AT+Research+Checklist+and+Disability+Etiquette)
- [Screen Readers](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242150676/Draft+Brian+-+Screen+Readers)

Once we're happy with these drafts I can move them into the Confluence space that feeds into platform website.

A couple of quick notes:
- I made a handful of very minor edits for formatting. But @joshkimux please review to verify that I didn't substantially change anything!
- Rather than checkboxes, the checklist items are presented as regular unordered lists. Confluence does have an "Action Item" formatting type that would give us checkboxes, but I don't know how that will render when it's processed by Scroll Viewport to publish on the platform website. Are we okay with bullet points, or do the checkboxes add value?
- Do we have any thoughts on page titles? In particular I'm wondering if we want to say something a little more than just "Screen Readers." The "Research Safety and Emergency Exit Strategies" page and the "AT Research Checklist and Disability Etiquette" page each have titles that give a better indication of what's included on the page. Maybe "Working with Screen Reader Users" or similar?

**Comment by claytonzook** [comment]
@briandeconinck I haven't had a chance to look through the drafts, but some preliminary thoughts
- 2 of your quick notes: The Research Checklist page does use the checkbox action item on the [Confluence version](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+Checklist) of the page and it seems to render well on [the published Platform page ](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist). Even though they can't be checked off, I think checkboxes do add a stylistic value (for sighted users). Now though I'm wondering how a screen reader would read off the action items - in the same way as an unordered list?
- 3 of your quick notes: Agree we need a different title! First attempt: "Research and Screen Readers." Also I think that the one titled AT should be spelled out "Assistive Technology Research Checklist"

**Comment by claytonzook** [comment]
@briandeconinck getting a chance to really look through these. It feels strange to have two checklists for what feels like very similar things. I wonder, does it make sense to merge these onto one Research with AT checklist, and that could be page one? Page two could then be something like "instructions for researching with AT" And then the etiquette could go on whichever page makes the most sense, or perhaps even on a 3rd page?

**Comment by briandeconinck** [comment]
Follow-up on checkboxes. Thank you for the example of a page on the platform website using them! The way the checkboxes are rendered is pure CSS, which is mostly good. Each item in the list is still a `li`, and the checkbox is presented using a background image on the `li`.

The reason it's only "mostly good": The default bullet point on each `li` is hidden using `list-style-type: none`. Unlike other screen readers, [VoiceOver on Mac and iOS ignores list semantics when hiding bullet points](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html) via CSS like this. So for VoiceOver users, the checklist gets announced as a single stream of information rather than segmented in a list or announced as "list with X items." For those users there's essentially no list, just a sequence of paragraphs.

There's lots of discussion around this in the accessibility world (see, for example, [the argument that it's not a big deal](https://yatil.net/blog/much-ado-about-no-lists)).

For these pages, I think it comes down to:
- VoiceOver users get a degraded experience when using the checkboxes.
- Other screen reader users get the same experience they would have if it was a regular unordered list with no checkboxes.
- Sighted users get the benefits of a checklist style providing some extra intuition about the intended use of the content.

My gut reaction is... it's not worth it to keep the checkboxes? It's not the worst thing in the world for VoiceOver users though. @claytonzook any strong feelings on this? You know your audience better than I do, so I'll defer to you on how much value the checkboxes add.

**Comment by briandeconinck** [comment]
Follow-up on content organization:

After re-reading these pages, I feel like the [Checklist to prepare for research](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242871321/Draft+Brian+-+AT+Research+Checklist+and+Disability+Etiquette#Checklist-to-prepare-for-research) is not really a checklist, at least not the same way the checklists on the [screen readers](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242150676/Draft+Brian+-+Screen+Readers) page are. The screen readers page items are all steps that relate directly to the interaction with the research participant, while the checklist on the other page is more for session planning. 

They seem like different things? So I don't think combining them on the same page feels right to me. But I do think breaking it up differently into three pages might work better!

Here's my suggestion:
- Page - "Research with Assistive Technology Users" containing:
   - Content from the "Checklist to prepare for research" section
   - A "Research with Screen Reader Users" section, with a short summary plus link to the screen reader page, like "Screen reader users do not navigate in the same way that sighted users do. Typically, they navigate by keyboard using a combination of mainstream key commands and those specific to their screen reader. When working with screen reader users, see the [screen reader checklist](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242150676/Draft+Brian+-+Screen+Readers)."
- Page - "Screen Reader Checklist" containing: 
   - All content on the current Screen Readers page
- Page - "Disability Etiquette" containing:
   - "Do during facilitation"
   - "Don't during facilitation"

Thoughts @claytonzook and @joshkimux?

**Comment by claytonzook** [comment]
@briandeconinck 
RE: checkboxes. This is great info to know, and I'm happy to defer to the accessibility expert for this. I don't think it's worth benefiting sighted users if it does that by making a worse experience for other users. So let's go with a standard list format here. I'll then also ask @chaseakirby to set us up a ticket so we don't lose the work to change the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) page from the checkbox layout to a standard unordered list

I like your page split and the removing and adding "checklist" to the appropriate pages so it's clear which one to go to for the step by step guide.

**Comment by joshkimux** [comment]
> But @joshkimux please review to verify that I didn't substantially change anything!

@Brian DeConinck it looks great! Nothing looks substantially changed. That being said, I'd love to work with y'all to provide more actionable tips for this part of the AT research checklist.

For example, instead of general guidance like, "Schedule a pilot test with an accessibility specialist"; how might we make that more specific and immediately actionable? e.g. "Schedule a pilot test with your team's accessibility specialist (calendly/office hours/etc)"

I can take a first pass at refining some of these if that's alright with y'all, but also wanted to ask:
what's the best way we can collaborate on stuff like this? Should I submit a ticket for suggested changes or should I edit the draft directly?

**Comment by shiragoodman** [comment]
@seanasewell will peer review once the changes have been made FYI

**Comment by briandeconinck** [comment]
These pages have now been created in the Research and design / Conducting Research Sessions section of the platform website Confluence space. However, I missed the Thursday publish deadline so they won't be live on platform website until Tuesday.
- [Research with Assistive Technology Users](https://vfs.atlassian.net/wiki/spaces/RD/pages/2261418013/Research+with+Assistive+Technology+Users)
- [Screen Reader Checklist](https://vfs.atlassian.net/wiki/spaces/RD/pages/2261057560/Screen+Reader+Checklist)
- [Disability Etiquette](https://vfs.atlassian.net/wiki/spaces/RD/pages/2261254165/Disability+Etiquette)

**Comment by shiragoodman** [comment]
@briandeconinck the Platform Content team did an off cycle publishing yesterday (bc the first run was done WAY earlier than 12 ET), so these changes may have been published. Can you please check?

**Comment by briandeconinck** [comment]
Should be ready for review @seanasewell!

**Comment by shiragoodman** [comment]
@briandeconinck i have 1 small edit. Please remove the Table of Contents from the [Screen Reader Checklist page.](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist) Platform Website by default has a right nav where every heading is linked. We don't need to have a TOC within the doc too. 

Other than that, looks great! Thank you for working so hard on this.

**Comment by briandeconinck** [comment]
@shiragoodman Done! And thank you for catching that. The TOC was in Josh's original and I never even thought about it duplicating the right nav.

**Comment by shiragoodman** [comment]
@briandeconinck I'm closing this out. I confirmed that the TOC has been removed from the source of truth page and will get published today.
