### ISSUE TITLE
Create a new Platform page for in-person research guidance

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#40880]
## User Story
As a VFS researcher, I want to have all the guidance I need on in-person research in one place that I know to be source of truth so I don't have to search various places for information, and I know that what I see is correct and updated

As Platform Governance Team, I want to make sure researchers can find all important guidance on Platform, since this should be source of truth

- Intended Audience: VFS researchers
- Desired Outcome: New page, or section of information on Platform, about in-person research
- Due Date: 

## Description
Currently Platform only has a small bit of info regarding [in-person research](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html#RecruitingParticipants-In-personmoderatedstudies). While our focus is on remote sessions, we should expand the guidance on Platform to include important info from [Planning in-person research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/planning-in-person-research.md) and from [Planning On-site Research with Veterans at VA Medical Facilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/process.md)

## New Artifacts 
- either new Platform page, or new section on an existing page

## Tasks
- [ ] Consider where is the best location for this information to live on Platform, an existing page, or a new page. Possible candidate for updated page 
   - [In-person moderated studies](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html#RecruitingParticipants-In-personmoderatedstudies)
   - [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html)

## Acceptance Criteria
- [ ] Platform Website: _Page Name_ has been updated
- [ ] Platform Website: _Page Name_ has been created
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by naomimarcussen** [comment]
Liz Straghalis shared some practices that worked well for their in-person research in her [design meeting research share in the In-person Research set-up section.](https://dsva.slack.com/archives/C0NGDDXME/p1664214984605409?thread_ts=1664197210.052829&cid=C0NGDDXME)

**Comment by naomimarcussen** [comment]
We should also include a section on recording in-person sessions. Sessions can be recorded on a smartphone or laptop and should mirror the guidance for what we do online. Make sure to mention that video must be recorded and stored on a local device, **do not store on a cloud service**

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
