### ISSUE TITLE
[CDP] Your other VA (debt/bills) 404 alert

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#40887]
## Issue Description
Need to include an alert message if the VBA or VHA fetch fails when on the sister page. Can probably make a shared alert and conditional render content. 
- [Debt Mockup](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*4qkxn5*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149376498/simulate/sitemap?mode=i)
- [Copay Mockup](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*4qkxn5*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149423131/simulate/sitemap?mode=i)

<details><summary>Screenshot (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/7db3165c-4317-4573-9295-62e042901160)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/d083812d-dd84-4175-8650-cd19bda8385e)

</details>

---
## Tasks
- [ ] Create new alert
- [ ] Implement new alert on Copays Page if VBA call fails
- [ ] Implement new alert on Debts Page if VHA call fails

## Acceptance Criteria
- [ ] New alert functioning as expected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
