### ISSUE TITLE
[CDP] Debt 2.0 Debt Letter Download

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#40888]
## Issue Description
The redesigned debt letter download page displays the downloadable letters in a list rather than table. Since Veterans are most likely coming to this page to download their most recently received letter(s) we should show the available letters from the last 30 days (or the most recent letter/letters if multiple fall under the same date). Veterans can also click a 'Show older letters' button that acts as an accordion to view the remaining letters. This is a new component being added to the experimental design system. Refer to the following tickets for more info:
- [#38778](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778)
- [#20694](https://github.com/department-of-veterans-affairs/vets-website/pull/20694)
- [#677](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/677)

- Redesigned letter download page - showing letters from the last 30 days ([UXPin prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1wyldjs*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149122561/simulate/sitemap?mode=ihttps://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1wyldjs*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149122561/simulate/sitemap?mode=i))
  - Expanded to show remaining letters ([UXPin prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1wyldjs*_gcl_aw*R0NMLjE2NDM3MzgwNDMuRUFJYUlRb2JDaE1JcElULW5vbmY5UUlWTXRTekNoMk9aQUM4RUFBWUFTQUFFZ0tHQnZEX0J3RQ..#/pages/149089099/simulate/sitemap?mode=i))
  - Example of Post-9/11 GI Bill letters ([UXPin prototype](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01?_gl=1*1cjwadz*_gcl_aw*R0NMLjE2NDMwMzc3MjYuQ2owS0NRaUF1Ym1QQmhDeUFSSXNBSldOcGlNMVo1NGR3LW9ZQnBONHktQTBuVHlyVW1MS3RscWZxRldaMmd1ZG0wcmFqSWp0OVl1NjZIQWFBc0NvRUFMd193Y0I.#/pages/149089100/simulate/no-panels?mode=i))

---
## Tasks
- [ ] Update Debt letters page with new sections
- [ ] Add hide/show functionality for older letters
  - [ ] Sort letters with latest on top

## Acceptance Criteria
- [ ] Debt Letters download page matches new mockup
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
