### ISSUE TITLE
[PM] Profile | Personal Info Revisions | QA Go/No Go

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#40884]
# Description

Prepare and schedule QA Go/No Go call prior to QA starting Personal Info revision testing

# Tasks
- [x] Complete [meeting template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/QA/notification-prefs-QA-go-no-go.md)
- [x] Save a copy of the completed template to the personal info revisions github folder [(template drafted here)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/QA/QA-Go-No-Go.md)
- [x] Update as needed 
- [x] Send out meeting invite

# Acceptance Criteria

- [ ] Tasks above completed
- [ ] Team provides "go" on the Go/No Go call

**Comment by SKasimow** [comment]
Closing as complete; we had a "GO" call today and everyone is ready for QA to begin.
