### ISSUE TITLE
Test uploading files to SharePoint in sandbox environment

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40897]
## Issue Description
Within a sandbox environment, write some sample code and upload test files to a test SharePoint location. This will allow for easy porting and implementation when continuing with FSR PDF uploads for VHA

---
## Tasks
- [x] Create test SharePoint
- [x] Write script to take file and upload

## Acceptance Criteria
- [x] We have sample code to upload files to SharePoint for future use
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
