### ISSUE TITLE
[FE] Discovery - Tech Debt - Deprecate use of isVAProfileServiceConfigured in Profile

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#40898]
## User Story

- As a front-end engineer I should not have to use the `isVAProfileServiceConfigured` function locally to build new features
- As a front-end engineer I should use a mock server either provided through the vets-api repo or through a node based mockeServer implementation, and those route definition should live in the mocks folder of `personalization/profile` directory

## Description

Using the `isVAProfileServiceConfigured`n function does not allow efficient e2e or local developer experience in that network calls are not made, and the function has to be changed/commented out or manipulated when working on new features.

The ideal would be to maintain a source of truth for network requests through the use of a mock api folder or to fully mock out responses through the betamocks in vets-api.

## Tasks

- [x] Evaluate work required to phase out this function's usage throughout codebase
- [x] Evaluate impact to any other apps (if any) that deprecating this function would cause
- [x] Create issues / epics for the work required
- [x] Update relevant documentation

## Acceptance Criteria

- [x] Issues have been created for work

**Comment by adamwhitlock1** [comment]
9 files total are referencing this function in 5 apps plus platform

- **Combined Debt Portal app**
  - `src/applications/combined-debt-portal/combined/actions/debts.js`
  - uses `debtMockResponse`
- **Debt Letters app**
  - `src/applications/debt-letters/actions/index.js`
  - uses `debtMockResponseVBMS` instead of network request
- **Financial Status Report app**
	- `src/applications/financial-status-report/actions/index.js`
	- uses `debtMockResponse`
- **Medical Copays app**
  - `src/applications/medical-copays/containers/OverviewPage.jsx`
  - uses `debtMockResponse`
- **Personalization app**
	- `src/applications/personalization/profile/README.md` just docs mentioning its usage
- **Platform**
	- `src/platform/user/profile/utilities/index.js`
	- `src/platform/user/profile/vap-svc/selectors.js`
	- `src/platform/user/profile/vap-svc/actions/transactions.js`
		- used to potentially mock several parts of transactional flow
			- getting profile/status
			- refreshing a transactions status
			- creating a transaction request
			- address validation requests
	- `src/platform/user/profile/vap-svc/util/local-vapsvc.js`
		- initial function declaration

CONSCLUSION:

Considering that not only is Profile using the function but 4 other apps are using it, then it probably is a good idea to keep it for now and at this point only transactional requests are using it within the profile. Personal information updates are not using it, and notifications are also not using it at this time.

Since no transactional work is being done at this time, then I'd say we hold off on creating any more work around this, and continue to use the mock server that is in place for work going forward and leave this legacy code as is until it is deemed that it needs to be updated specifically.
