### ISSUE TITLE
Research existing Lighthouse API endpoints that we could be using but aren't

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40899]
# Background
In an effort to move VA products and services to the Lighthouse API we need to do a small audit of the services our existing products on the benefits team use as well as what endpoints currently exist in Lighthouse that we can use to hit those services. This ticket is to track that audit.

## Existing products
- [ ] 686c-674
- [ ] View Dependents
- [ ] View Payments
- [ ] Rated Disabilities
- [ ] View Representative
- [ ] Search Representative
- [ ] Chapter 31
- [ ] Chapter 36
- [ ] NOD
- [ ] form 527
- [ ] Claim Status Tool
- [ ] HLR

## Tasks
- [ ] For each of the products above document what services/ endpoints are being used and what data is being received from them
- [ ] for each of the products above document what current Lighthouse endpoints exist that can provide the same fucntionality

**Comment by cohnjesse** [comment]
refer to https://developer.va.gov/
