### ISSUE TITLE
Research PDF Fill library and integrating with 5655 Form

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#40896]
## Issue Description
We may take on the PDF generation and already have some PDF fill functionality. Do some research to see how this library works, test how to run and fill out PDFs locally and give an idea of how to use it with the FSR form.

---
## Tasks
- [x] Deep dive into code and gem for PDF fill library
- [x] Run locally with test form
- [ ] Document it's use case with FSR

## Acceptance Criteria
- [x] We have a time estimate and follow-up steps for producing a 5655 PDF form
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Documented steps for internal PDF generation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/sftp/PDF%20Generation.md)
