### ISSUE TITLE
[CDP] Merge medical-copays under the new combined-debt-portal

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#40891]
## Issue Description
medical-copays needs to move under the new combined-debt-portal application for the new URL structure. While in development and testing the production medical-copays won't change, and updates for the CDP effort will be made in under the combined-debt-portal.

---
## Tasks
- [ ] Merge medical-copays under Combined-debt-portal

## Acceptance Criteria
- [ ] a copy of debt letters will exist within combined-debt-portal and behind the CDP feature flag
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
