### ISSUE TITLE
Need AWS_ACCOUNT_ID added to repo as secret

### ISSUE THREAD

**Issue by MrBilnon** [department-of-veterans-affairs/va.gov-team#40902]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@considerable 

## Description
Add AWS_ACCOUNT_ID to the secrets to repository https://github.com/department-of-veterans-affairs/vets-api-virus-scan

---
## Tasks
- [ ] add AWS_ACCOUNT_ID secret to repository https://github.com/department-of-veterans-affairs/vets-api-virus-scan

## Acceptance Criteria 
- [ ] add AWS_ACCOUNT_ID secret to repository https://github.com/department-of-veterans-affairs/vets-api-virus-scan

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ewilson-adhoc** [comment]
I'm going to put this as blocking for on onboarding task

**Comment by jbritt1** [comment]
Is this the same team that uses the pst-iet service account?

**Comment by jbritt1** [comment]
Looks like these were added 19 days ago, perhaps we just forgot to close this ticket. Closing.

![image](https://user-images.githubusercontent.com/56260532/168620542-f38cc28c-4372-4f59-ba24-0e3a6c78340e.png)
