### ISSUE TITLE
[BE] Parameter Store Configuration for Maximum Auth Limit

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#40907]
## User Story
Create maximum auth limit entries in AWS Parameter Store and add new configuration in settings.yml for reading values from ParamStore for maximum auth limit in development/staging/prod

## Acceptance Criteria
- [x] Create entry in ParamStore for development/staging/prod
- [ ] Modify vets-api settings.yml.
- [ ] Modify devops settings.yml.

## Tasks
- [ ] Deploy and test on staging.
