### ISSUE TITLE
FE unit test for AuthMetrics

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40917]
## Issue Description
Create a unit test suite for AuthMetrics

## Tasks
- [x] verify recordAuthEvents is called correctly with the policy type & service name
- [x] verify reportSentryErrors is called correctly
- [x] verify events occur when a user does not have a session
- [x] verify compareLoginPolicy logs event when called

## Acceptance Criteria
- [x] Unit test created for AuthMetrics
