### ISSUE TITLE
[Access Management] Improve offboarding template Acceptance Criteria

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#40919]
## Description
In the Acceptance criteria section of the [offboarding document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/offboarding-request.md), clarify who owns each task.

**DSVA Slack**: There should be a checkbox for _making_ the `/request` (infra's responsibility) and another checkbox for _actually removing_ the user from Slack.

**Confluence**: I think Infra should check confluence to see if the offboarding user exists. There should be another checkbox for when a confluence admin has removed them. (? just an idea. not sure the best way for this to work)

**Google analytics, and Domo access**: `@department-of-veterans-affairs/vsp-analytics-insights` is responsible for this checkbox. They handle this well, so not sure if we need to split this up.

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1651681596644239

---
## Tasks
- [ ] Update offboarding request
- [ ] ~Tell Slack admins and Confluence admins that they now have to check a box when they remove someone.~ 
- [ ] ~Decide if we want to add/use new labels to identify who needs to look at it.~

## Acceptance Criteria 
- [ ] Tasks are completed

**Comment by rmtolmach** [comment]
I crossed out two of the acceptance criteria. We decided to make the acceptance criteria for the Infrastructure team only. #45596 was merged with these changes.

Based on https://github.com/department-of-veterans-affairs/va.gov-team/issues/43661, it seems like the security team is going to be adding some automation to offboarding in the future.
