### ISSUE TITLE
FE unit test for TransitionAccountSuccess

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40915]
## Issue Description
Create a unit test suite for TransitionAccountSuccess

## Tasks
- [ ] verify content of transferred CSP is one of ID.me or Login.gov
- [ ] verify content cannot be seen for a user who is logged out

## Acceptance Criteria
- [ ] Unit test created for TransitionAccountSuccess
