### ISSUE TITLE
FE unit test for TransitionContainer

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40914]
## Issue Description
Create a unit test suite for TransitionContainer

## Tasks
- [ ] verify content is displayed if a user is both signed in and using  `mhv` as a service provdier
- [ ] verify redirect if user is not signed in with `mhv` or not signed in

## Acceptance Criteria
- [ ] Unit test created for TransitionContainer
