### ISSUE TITLE
FE unit test for TransitionModal

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#40922]
## Issue Description
Create a unit test suite for TransitionModal

## Tasks
- [ ] verify event is recorded based on visibility
- [ ] Verify content is what is expected based on eligibility
- [ ] verify primary action takes a user to `/transfer-account`

## Acceptance Criteria
- [ ] Unit test created for TransitionModal
