### ISSUE TITLE
VAOS edge case dashboard - Data QA

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#40920]
## Issue Description
As we roll out the VAOS edge case dashboard we need to make sure that our data is accurate and trustworthy.

---
### Resources

- [VAOS dashboard](https://va-gov.domo.com/page/202515362)
- [VAOS tracking sheet](https://docs.google.com/spreadsheets/d/1bqmsByCNwx1yXNIiKonun3HfqxgBCKjzw42ZyFFEMhM/edit#gid=0)

---
## Tasks
- [ ] Verify that data formats are correct
- [ ] Validate the data is what is expected (does the info collected measure what it is supposed to measure and does it align with GA?)
- [ ] Identify and document invalid values

## Acceptance Criteria
- [ ] The production VANotify Edge Case Dashboard in Domo has accurate and trustworthy data and is ready to be shared with stakeholders.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Hi @jennaouellet! Here's a link to the [VAOS dashboard build & QA tracking](https://docs.google.com/spreadsheets/d/1bqmsByCNwx1yXNIiKonun3HfqxgBCKjzw42ZyFFEMhM/edit#gid=0) spreadsheet. I've just double-checked the `Definitions (for QA)` in column B, which will hopefully clarify how each card is configured. You'll also find links to each card's `Data source` in column D, in case that's useful to reference.

#### Context

- **Funnel starts**: For the purposes of all cards except future time-to-complete ones, the first step on each of these funnels is the `XXX-path-started` event fire. Steps before the funnels fork, VAOS homepage, the "Type of Care" page, and the schedule appointment click event should not appear, as they come before this point.
-   **Active**: This column in the BQ table is marked "false" for pre-funnel steps. These are not included in the Domo datasources currently.
- **Optional**: This column in the BQ table is marked "true" for steps not all users pass through. These are included in the Domo datasources, but are filtered out of our funnel tables on the dashboard.
- **Supporting resources**: [spreadsheet I made](https://docs.google.com/spreadsheets/d/1dt3Da4zN5xtNckKAGU8-5RDtkZJHiyKusCJJjE8E018/edit#gid=856892027) when QAing the BigQuery table last week (which may be easier to scan than BQ itself) and [thread ](https://adhoc.slack.com/archives/C01EUNU6W1Z/p1651090257805949?thread_ts=1650641949.196769&cid=C01EUNU6W1Z)of what I checked for in most recent data QA conversation.

#### What to QA

- All the great stuff you usually do!
- Dashboard needs to be QA'ed for **ALL 5** of the VAOS products on here: Full Funnel, Appointment Request, Self_Schedule, Vaccine, and Community Care. In the past, we've sometimes found issues that affect just one of these flows. Just because one of them passes QA, there may still be issues in the others.

#### Cards with known issues

- **Avg. minutes to complete (Highlights & Ease of Use)**: Data not yet available – please skip.
- **Avg. minutes on step - running total (Ease of Use)**: Data not yet available – please skip.
- **Top pages viewed before engaging with the scheduler (Findability)**: No values appearing for "Full Funnel" form product – please QA for other 4 filter options. 

Please feel free to ping me with any questions!
