### ISSUE TITLE
[CDP] Sync with accessibility regarding midpoint review feedback

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40927]
## Issue Description
We received feedback in the midpoint review that we need to ensure that the statuses in the debts/copay bills cards are accessible to screen readers. 
Additionally, we received the following feedback on the 'Check details' links:

- On the Current VA Debt page when there are current debts (eg. the No copays on record view), the "Check details" link text for current debts may be a little ambiguous. Two big potential impacts here are screen reader users (harder to differentiate which link goes where) and voice command users (speaking the command `Click check details link `will match with both links). Consider adding some extra text to make the link purpose a little clearer across every possible use case, eg. "Check details" becomes "Check compensation and pension debt details." If that's not a practical option, then when this goes to code we may still need some helping `aria-label` text for screen reader users.

We should sync with Angela F. to identify next steps based on this feedback 

---
## Tasks
- [x] Meet with Angela F., Kevin, Andrew, and Brandyn to review how statuses read in MCP 
- [x] Document the recommended changes to make the statuses more accessible

## Acceptance Criteria
- [x] Accessibility changes have been documented 
- [ ] Followup tickets are created and linked

**Comment by rileyorr** [comment]
Update on this work: just sent out an invite for tomorrow after standup for everyone to discuss the feedback!

**Comment by kevinstachura** [comment]
Blocked until we reschedule our meeting with Angela to discuss accessibility.

**Comment by rileyorr** [comment]
I followed up with Angela and she said she's available to meet tomorrow (May 13th) after standup :metal:

**Comment by rileyorr** [comment]
The team met with Angela to go over the feedback we received. 

## Notes
- Status icons need alternative text 
   - Icons should state level of importance
   - Information, warning, critical alert, important, etc
   - There doesn't appear to be standard messaging for alert alt text 
- Check details aria-label 
    - "Check details and resolve [amount] for [facility name]"

## Next steps
- Angela will sign into the Medical Copay Tool's staging environment to check if the current status icons contain alternative text  and if the 'check details' link has an aria-label
- We will document her findings in this ticket and create follow-on ticket(s) for frontend changes

**Comment by rileyorr** [comment]
The team followed up with Angela again and it seems like the aria tag contains the facility ID, so the screen reader should theoretically read out the facility name. However, it's not working as intended. She said she's reading out to DK and we will all circle up when he's back from PTO

**Comment by rileyorr** [comment]
Angela confirmed during standup that we should use the aria describe by label. This ticket is no longer blocked, as we've received all accessibility feedback!

**Comment by rileyorr** [comment]
[I've added a ticket for frontend implementation](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/42872).
