### ISSUE TITLE
Include Beats agents on all devices to allow for security logs to be sent to CSOC Splunk

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#40935]
## Description
Include Beats agent installation and configuration in baseline images/build for all devices within platform so that all devices can send security logs to CSOC Splunk instance.

This is a high priority, as requirement comes from CIO that all devices report security logs to CSOC Splunk.

## Background/context 
CIO has a requirement that all devices in VA enterprise ship security logs to enterprise Splunk instance.  In order for that to happen, the Beats agent has to be installed and configured on all of our devices.  

ECSO provided [this link](https://github.ec.va.gov/AWS/vaec-cls-beats/tree/master/SSM) to an SSM script for installing and configuring the Beats agents.

Using SSM to install the agents, however, will not suffice in our environment as there would be a gap in log coverage between the time a machine is deployed to when the agent is installed, given that we re-deploy images frequently.  Would need to include the Beats agent installation in the baseline image/build.

## Tasks
- [x] Beats agents need to be included and configured on all platform devices in order to send security logs to CSOC Splunk per CIO requirement.

## Acceptance Criteria 
- [x] Beats agents is included and configured on all platform devices as part of baseline image or build.

## Deployment Tracking

- [x] blackbox-exporter (next run at Tuesday, May 17, 2022 2:00:24 PM UTC)
- [X] cms
- [x] cms-test
- [X] content-preview
- [x] fwdproxy
- [X] gibct-data-service
- [ ] jenkins-master-vetsgov
- [X] jenkins-worker
- [X] jumpbox-vetsgov
- [x] prometheus (next run at Friday, May 13, 2022 3:14:23 PM UTC)
- [X] revproxy-vagov
- [X] sentry10 (Migrated to Kubernetes and is no longer deployed via an AMI)
- [X] unbound
- [X] utility-exporter
- [X] va-socks
- [X] vets-api

**Comment by jhouse-solvd** [comment]
@troymosher - Thanks for submitting this. 

For some reason, the URL https://github.ec.va.gov/AWS/vaec-cls-beats/tree/master/SSM is unreachable for me. 

Also, not that this needs to be included in the issue, but do you have technical details about "where" to send these logs, or would we need to coordinate with CSOC to get that info?

**Comment by troymosher** [comment]
@jhouse-solvd that URL is only accessible from CAG/GFE.  The "where" to send the logs, from how it was explained, is supposed to be within the config they provided.  There is another separate effort that needs to be configured on the AWS account for it all to work properly, I am waiting to hear back the details on that portion and will create a separate issue.

**Comment by ph-One** [comment]
Tracking the deployments in this ticket. See the :x: and :heavy_check_mark: in the "Deployment Tracking" section

**Comment by jhouse-solvd** [comment]
@ph-One - Please provide an update when you can on the status of these deployments. Thank you!

**Comment by jhouse-solvd** [comment]
@oseasmoran73 taking a look

**Comment by ph-One** [comment]
To prevent dragging on this ticket bc of a couple hang-ups, I'm closing this ticket and opening two separate tickets, one for `blackbox-exporter`, and one for `jenkins-master`. These two require more attention than the others.

**Comment by ph-One** [comment]
https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/42653

https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/42654

**Comment by troymosher** [comment]
Ropening ticket.  Several instances appear to not have beats agent installed.  [agent-compliance-2022-07-21.xlsx](https://app.zenhub.com/files/413906181/179c3d65-3687-43c1-a28b-a479383bc3bc/download)

**Comment by ph-One** [comment]
Looks like the `INSTANCE NAME` does not match the `INSTANCE ID`. For example, `i-0502*` is listed as `revproxy`, but in AWS it's a CMS instance. All of the other columns appear accurate, so I'm going to go out on a limb and say that the `INSTANCE ID` is an accurate value that can be used to point to instances needing another look.

**Comment by gary-fallon** [comment]
Apologies, there was a logic bug in the code that has now been [fixed](https://github.com/department-of-veterans-affairs/platform-security/pull/183). The instance_names list could grow larger than the instance_id list; this threw off an index lookup that was performed later in the code.

**Comment by gary-fallon** [comment]
[agent-compliance.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9243561/agent-compliance.xlsx)

**Comment by ph-One** [comment]
All of the `*-gha-runner` instances have beats installed and are running, but a subset of them are getting a `connection reset` error when trying to connect to the CLS endpoint. Do you have any insight into if that endpoint has changed in any way, or was down for maint? 

![image](https://user-images.githubusercontent.com/1580012/182442962-58adf1b7-3553-401b-9af5-73beeb2455b9.png)

**Comment by jhouse-solvd** [comment]
In discussing w/ Kyle, it sounds like the agents are installed, but having trouble connecting to the endpoint to send data. 

We think it might be helpful to create a follow-up ticket to troubleshoot specific agent issues. We'll discuss with the team and follow up.

**Comment by jhouse-solvd** [comment]
@ph-One - Can you create a follow-up issue with what's needed?

**Comment by ph-One** [comment]
Closing, as beats agents are installed. I will create a follow-on to investigate any connectivity issues.
