### ISSUE TITLE
Change VALI to VALife in the Life Insurance Promo and contact info right rail

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#40943]
## Issue Description
Stakeholder Steve Fital informed us that the new program VALI is changing to VALife. We need to update these in 2 places on VA.gov.

The life insurance promo spot:

![Screen Shot 2022-05-05 at 10.52.50 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/03744ecc-e627-4f22-8eef-99eace42795b)

The contact info in the life insurance right rail:

![Screen Shot 2022-05-05 at 10.53.14 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4a75bb79-3c62-461c-b18d-a41d95693d66)

## Tasks
- [ ] Change VALI to VALife (Aliyah)
- [ ] Review changes (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] VALI is now called VALife on live site

**Comment by RLHecht** [comment]
@aliyahblackmore When you're ready to work on this, I can screen share with you since updating the promo and right rail is a little different in Drupal. It's also possible that we won't be able to save as a draft and will just have to publish when we make the change.

**Comment by RLHecht** [comment]
@aliyahblackmore Just confirmed with the stakeholder that we should also change the link in the right rail. It should now be this: https://www.benefits.va.gov/insurance/valife.asp

**Comment by aliyahblackmore** [comment]
@RLHecht At the moment I do not have editing permission for either of these pages. Jane Xiong (from the CMS-support team) shared on Slack that it will take a bit of an investigation but that she will get back to me. I provided their team with links/screen captures of what I am seeing on my Drupal page.

**Comment by aliyahblackmore** [comment]
@RLHecht These are ready to be published. The promo page with link and the right rail have all be updated to "VALife"

**Comment by RLHecht** [comment]
Thanks @aliyahblackmore These are both published. Moving to validate and I'll close once the changes are live.
