### ISSUE TITLE
BDD: Switch to use va-date web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40958]
## Description

In the all-claims wizard Benefits Delivery at Discharge (BDD) path, there is a React Date component being used. We need to switch it to use the new `va-date` web component.

## Tasks

- [ ] Replace React `Date` widget with `va-date`
- [ ] Update tests as need

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
