### ISSUE TITLE
HLR/NOD: Switch to use va-date web component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#40960]
## Description

In both the Higher-Level Review (HLR) and Notice of Disagreement (NOD) forms, the `SimpleDate` React widget is being used on the add issue page. This React widget needs to be replaced with the `va-date` web component.

## Tasks

- [ ] Replace React `Date` widget with `va-date`
- [ ] Update tests as need

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Holding off on this change until `va-date` allows us to include hint text. Once the component library supports hint texts, we can finish this work.

**Comment by Mottie** [comment]
Restarting this work. The `SimpleDate` component is not showing the month names in the select, so we need to switch sooner rather than later. The missing hint text can be moved above the `va-date` web component until hint text is supported.
