### ISSUE TITLE
Develop User Interviews and research plan

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#40968]
## Issue Description
We want to identify the most valuable problems we can solve for Veterans in their support request and resolution process. To do this, we are going to develop a comprehensive Veteran support user journey map. This issue is for the first draft and revisions. 

---
## Tasks
- [x]  _Update Confluence [page here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2162524258/User+Journey+Veteran+Support+DRAFT+Q2+2022) with RP plan updates_
- [x] _[Updated Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/research/Q2-2022/VA_Caller/research-plan.md)_
- [x] _Submitted RP to VA Design Github_
- [x] _Review and comments from VSP Design Team_ 
## Acceptance Criteria
- [x] _Comments and Review for User interviews_ 
- [ ] _Coordinated and conducted draft interview_

**Comment by manalo-soco** [comment]
@jwoodman5  Updated ticket for RP and convo guide here

**Comment by manalo-soco** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/research/Q2-2022/VA_Caller

**Comment by manalo-soco** [comment]
Submission for VA  VSP Design review: 
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/130
