### ISSUE TITLE
Veteran Support User Journey Map - Phase 2

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#40967]
## Issue Description
We want to identify the most valuable problems we can solve for Veterans in their support request and resolution process. To do this, we are going to develop a comprehensive Veteran support user journey map. This issue is for the first draft and revisions. 

---
## Tasks
- [ ] _Update Confluence [page here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2162524258/User+Journey+Veteran+Support+DRAFT+Q2+2022) with updated User Flow
- [ ] #40968
- [ ] _Internal review and comments from Contact Center team
## Acceptance Criteria
- [x] _Reserach plan for User interviews 
- [x] _Updated pain points from trigger incident, to Tier 1 and then to Tier 2 & 3 
- [x] _Incorporate comments from CC team to First Draft

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
@jwoodman5  Here is the ticket for the User Journey next steps.

**Comment by manalo-soco** [comment]
@jwoodman5  
Developed research plan here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/research/Q2-2022/VA_Caller/research-plan.md

Recorded user journey with comments: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/research/Q2-2022/VA_Caller/research-plan.md
