### ISSUE TITLE
[spike] Certificate of Eligibility | Document remaining code tasks

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40981]
## Value Statement
**_As a_** Developer
**_I want to_** define the remaining development work for the Certificate of Eligibility form
**_So that_** I can complete the remaining code tasks. 

## Background Context
The back end for COE was in progress and in a state of development but that state was not documented anywhere. We need to dig into the code and determine what back end end points have been set up vs those that still need to be completed.

## Tasks
- [x] Front end document what API calls are currently fully functional and which ones need to be completed
- [ ] Back end document next steps for finishing/ creating api end points still needed

## Acceptance criteria
- [ ] End points still required to be finished or created for COE are documented
- [ ] Tickets exist for the remaining back end work mentioned above
- [ ] The team is enabled to update Matt on the remainder of the work

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
- Download endpoint needs to be hooked up. Can make a ticket for it. 
- Will update after 6/1 chat with LGY product manager.

**Comment by scottymeyers** [comment]
So yeah, as far as I know what need to be done is:

- **API** need to create the _download_ endpoint
- **UI** will need to add that link for each document

Here's a link to the prototype, which hopefully includes an example for the _UI_ change, I haven't been able to confirm that yet.

**Comment by saderagsdale** [comment]
@scottymeyers looking at the prototype and adding a ticket for the displayed documents now. Remind me, was Kelli suggesting that the actual download of those documents from VBMS was something that could potentially wait until post release?

**Comment by scottymeyers** [comment]
@saderagsdale I don't see that in my notes, but does sound right when you say it. We can focus on the existing issues the previous team created, and then circle back to that one.

**Comment by saderagsdale** [comment]
@scottymeyers I saw that you moved this back to ready. Is this spike not in progress?

**Comment by scottymeyers** [comment]
@saderagsdale my mistake

**Comment by scottymeyers** [comment]
I think we're good to go here on the form. I've just updated the ticket for document type, to additionally include the document description. We'll see if Kelli comes back with anything.
