### ISSUE TITLE
Pull feature toggle into form introduction page and status app for COE

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40983]
# Background
Now that we have the feature toggle set up for COE we need to pull that feature toggle into the form introduction page and the status app so that we can show a message to the users outside of the feature toggle that the feature is still in progress.

## Tasks
- [ ] Work with design to get an alert mocked up for the message that will be shown to users outside the feature toggle
- [ ] Pull the feature toggle into the form introduction page and display the message
- [ ] Pull the feature toggle into the status app and display the message
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] A message for users outside the feature toggle for COE is now visible on the form introduction page and the status app
