### ISSUE TITLE
Move HLR from disability-benefits folder to src/applications/appeals

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40988]
# Background
Since the HLR app is for appeals, not benefits, we should move the app from the `disability-benefits` folder into the `src/applications/appeals` folder. We should do this before more work is done on the HLR app since the more we do before moving it will just make moving it more complicated.

## Tasks
- [ ] Work with VSP platform support to determine steps to move an app
- [ ] Move the app
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The HLR app now is living in `src/applications/appeals`
