### ISSUE TITLE
Build feature toggle for COE

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40982]
# Background
Now that we are feature complete on COE on the front end we need to create a feature toggle so that we can perform a staged release in production. We only need one feature toggle but this feature toggle will be pulled into the introduction page of the form, the status app, and the React widget we use on the static Drupal page.

## Tasks
- [ ] Set up feature toggle according to [documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)
- [ ] Submit PR for review

## Acceptance criteria
- [ ] A feature toggle for COE is available in all environments

**Comment by jerekshoe** [comment]
This is done already. [Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23958). The name of the feature flag is `coe_access`
