### ISSUE TITLE
Build React widget for COE scaled launch

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40985]
# Background
Now that we have the feature toggle created for COE we need to build a feature toggle for the static Drupal page(s) leading to the COE status app and the COE form. This will first need to be run by design and content so that we can assess what pages we need to create React widgets for and what the content will be.

## Tasks
- [ ] Work with design and content to identify which static page(s) lead(s) to both the COE status app and the COE form
- [ ] Work with design and content to get a mockup of what should be shown to users inside the feature toggle as well as outside the feature toggle for the static pages leading to both the COE status app and the COE form
- [ ] Build the React widget(s) needed for the static page(s) leading to the COE status app and COE form
- [ ] Test React widgets locally
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] React widgets have been created and tested for the static pages leading to the COE status app and the COE form
