### ISSUE TITLE
Investigate switching to Datadog for HLR

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40993]
# Background
Sentry is difficult to use so we want to investigate what would be involved in switching to Datadog for logging on HLR

## Tasks
- [ ] Investigate the process to use Datadog with the platform team
- [ ] Document next steps to switch to Datadog

## Acceptace criteria
- [ ] We have a documented understanding of the lift required to move to Datadog for HLR
