### ISSUE TITLE
[platform-support-slackbot] Application onboarding infrastructure request (EKS)

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#40990]
## Summary
Currently the VA Support bot is deployed to Heroku. There are a number of good reasons to have this running on Platform infrastructure.

### Overview
- The Platform leverages container orchestration to host and deploy software applications  
- Container orchestration automates the deployment, scaling, and management of containerized applications
- To learn more, see ["Application Hosting and Deployment using Container Orchestration (EKS)"](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593866/Application+Hosting+and+Deployment+using+Container+Orchestration+EKS)

### Guidance
- Please fill out the sections below with as much info as possible 
- If you don't have info or know the answer to a given prompt, _it's okay to leave it blank_
- The Infrastructure Team will assist you with gathering requirements _and_ performing key setup and configuration tasks 

---

## Description of application
The Platform Support SlackBot is used to manage support requests in the #vfs-platform-support slack channel

### Basic info:
**Team Name:**   
Platform SRE 

**Application Name:**  
Platform Support SlackBot

**Functionality:**  
This app uses websockets to communicate with slack. It specifically uses the /on-support and /support commands as well as onsupport and support shortcuts. Using these commands in slack will allow the user to submit support requests and modify support assignments.

**Language/Stack:**  
NodeJS, BoltJS  
**Ports/Networking needed:**  
80, 443 ?

**Other infrastructure needed:**  
Future iterations will include a database, currently data is stored in Google Sheets 

### Background/Context/Resources
Developer Docs: https://vfs.atlassian.net/wiki/spaces/SRE/pages/1466826783/Platform+support+in+Slack
User Docs: https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html

### Technical Notes
Current implementation is on Heroku, which is not supported and does not use recommended architecture and deployment guidelines. Heroku also has had recent security breaches which are pushing us to move this application. 

The current implementation uses web-sockets but it is possible to update the configuration in the Slack API to use redirectURIs instead. 

This application also has environment variable that need to be defined in order to communicate with Slack, Google Sheets, and PagerDuty

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** https://github.com/department-of-veterans-affairs/platform-support-slackbot 
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   

- [x] **Dockerfile:** https://github.com/department-of-veterans-affairs/platform-support-slackbot/blob/master/Dockerfile

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions**, svc-gha-platform-sre | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=) | https://github.com/department-of-veterans-affairs/va.gov-team/issues/41311  
_Infrastructure Team_
- [x] **AWS Elastic Container Registry (ECR) repository for the app container:** dsva/platform-support-slackbot  
_Infrastructure Team_ | [PRs welcome](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)  
- [x] **Automation to release and tag the app's GitHub repo with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation. 
_Requesting team; Infrastructure Team can assist_  
- [ ] **Kubernetes manifest in YAML, Jsonnet, or Helm Chart** in `vsp-infra-application-manifests` | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps) | [Docs](https://argo-cd.readthedocs.io/en/stable/)  
Note: must be compatible with ArgoCD  
_Requesting team; Infrastructure Team can assist_  
- [ ] **Kubernetes detect and update application** in `vsp-infra-applications-manifests` | [Environments](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-operations/argocd-apps)  
_Requesting team; Infrastructure Team can assist_  
- [x] **Automation to update the Kubernetes manifest** when a new version of the app's container is pushed to ECR | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml)  
_Requesting team; Infrastructure Team can assist_

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** ie `/dsva-vagov/team-name/` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** ie `/dsva-vagov/team-name/env/secret-name` | [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by jhouse-solvd** [comment]
There's an existing issue here: #38455 

I'd recommend reconciling the information and closing that one out in favor of this newer one. :)

**Comment by powellkerry** [comment]
@jhouse-solvd This is blocked due to the need for a public domain for the K8. We need to figure out if Ops can obtain a new public domain or if we can use an existing public domain like va.gov (maybe slack-support.va.gov or something like that)

The support-slackbot needs to be available on a public domain so that it can communicate with slack.

**Comment by jhouse-solvd** [comment]
Moving to review so that we can determine next steps.

**Comment by jhouse-solvd** [comment]
Due to some technical limitations, we are choosing not to follow up on this work at this time. If we decide to take this forward, we'll create a new ticket.
