### ISSUE TITLE
Review Sentry events for HLR to look for potential issues

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#40992]
# Background
Now that HLR has been in production for some time we need to review the Sentry logs to see if there are any potential issues that need to be addressed. The outcome from this ticket will most likely be subsequent tickets.

## Tasks
- [ ] Search Sentry logs for any errors that indicate larger issues
- [ ] Create tickets to document larger issues to be researched further or fixed

## Acceptance criteria
- [ ] Sentry logs for HLR have been checked for indications of larger issues
- [ ] Any possible larger issues have been documented in a ticket

**Comment by saderagsdale** [comment]
- Assign to Scott.

**Comment by gperlangeli** [comment]
I invited you as a member. Although, for if you need admin, for the purposes of your research, then I'll have to get someone to grant those permissions for you.
