### ISSUE TITLE
SideKiq UI Integration

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#41009]
In order to increase the power of the authentication mechanism used on IET's SideKiq UI, we need to integrate SideKiq UI into Keycloak. 

Current state:
* SideKiq UI is using Github OAuth to authorize members of a Github Team.
  * this github team was created only for IET's auth purposes and can be migrated to Keycloak
* SideKiq UI is currently not in production, which makes it a good candidate for integration
* Authorization is probably not needed at this point, just authentication

Definition of done:
- [x] A sidekiq group is created in Keycloak dev
- [x] A sidekiq client is created in Keycloak dev
- [x] Integration has been tested in Dev
