### ISSUE TITLE
Sitewide CMS- Sprint 58

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-team#41003]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

## Transition

- [x] Update labeling in GH

## Features
- [ ] #8299 
- [ ] #8749 (Rachel)

## Design system
- [ ] #8492 
- [ ] #8680
- [ ] #8540 

## Broken Links
- [ ] #8783 (Rach)

## "Was This Helpful?" Widget
- [ ] #8842 (Rachel)
- [x] #5811 (Lynn)

## Change management 
- [x] #8603   
  - [ ] Top task change management efforts (may need a separate ticket) 🥅
  - [ ] recurring events change management efforts (may need a separate ticket) 🥅
  - [ ] #8079 ?

## #8231 Content lifecycle for events
- [ ]  #4214  (stretch)

## Media Upload 
- [ ] #8754 (Ethan)

## Care we provide

- [x] #7657 (Denise, Swirt, Lynn) 🥅  

## #4888 Improve UX for Hours widget  

Via #6931 we got an HTML5 hours editor. 

- [ ] #8474  Rachel  (on hold)
- [ ] Then close this epic

## Dev workflow improvements

- [ ] #8477 (kev to fill this in then handoff/stretch)

## #7490 Lat/long for facilities and events

- [ ] #8776  (stretch)

##  #7963 Phone numbers 

- [ ] #1964 (Tanner- stretch)

**Comment by EWashb** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-cms-team #2](https://github.com/department-of-veterans-affairs/va.gov-cms-team/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by EWashb** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-cms-team #3](https://github.com/department-of-veterans-affairs/va.gov-cms-team/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by EWashb** [comment]
Not sure how I made this ticket in the wrong repository. Closing
