### ISSUE TITLE
Add footer to Platform pages where it's missing

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41010]
## User Story
As a Platform user, I want to use a consistent Confluence footer on all Platform pages so that updates are easily propagated across all pages.

- Intended Audience: VFS teams
- Desired Outcome: page footer added to all Platform Website pages
- Due Date: N/A

## Description
The [Platform Orientation page](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) is missing the footer. A brief look through some other pages, shows that others in the [Getting Started](https://depo-platform-documentation.scrollhelp.site/getting-started/) and [Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/) and [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) sections are also missing [the official footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro).
See more in the [Slack thread](https://dsva.slack.com/archives/C01AS05BQ79/p1651783176447989)

## Artifacts Needing Updates
Several pages across Platform that Governance Team manages 

Getting Started > Plat O > Guidance
Getting Started > Plat O > Calendly

CC > TP > SR > Anatomy
CC > Product Development Checklist
CC > FAQ

R/D > Conducting > Exit
R/D > Recording
~~R/D > Zoom~~ From Platform/IA documentation: "The page footer doesn’t need to be embedded on navigational landing pages."
R/D > Zoom > How to use Zoom
R/D > Zoom > User Testing (also title change from "user" to 'usability")
R/D > Zoom > Tech checklist

## Tasks
- [x] Content audit each page the Governance Team manages to find which ones need the footer added (all of Collaboration Cycle pages, Getting Started/Platform Orientation pages, and some Research & Design pages)
- [ ] [Embed the footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro) on pages as necessary
   - [x] [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) page

## Acceptance Criteria
- [x] Platform Website: Platform Orientation has been updated
- [x] Any other Platform Website pages have been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
@chaseakirby I found that some of our pages have the old style footer, as static text. The Content/IA team's [current guidance is a dynamic footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro). We probably need an audit and to update any pages that don't comply with current footer guidance.

For example, one page that doesn't comply is [CC > Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints)

**Comment by claytonzook** [comment]
@chaseakirby ready for peer review!

**Comment by shiragoodman** [comment]
@claytonzook did you make the changes directly to the Confluence pages or did you create drafts? If the former, do you know if the pages have been updated with scroll viewport yet?

**Comment by claytonzook** [comment]
@shiragoodman Since it was a single item add, I bypassed drafts and put it directly on each Confluence page.
I checked after the Thursday publish announcement and the footer additions appear to be live on these pages now.

**Comment by shiragoodman** [comment]
got it. thanks for confirming. I wasn't sure what pages to peer review. I'm taking a look now and will follow up!

**Comment by claytonzook** [comment]
It'll be the 10 pages under Artifacts to Update. I did use my own shorthand there, but can decrypt any that don't make sense.

**Comment by shiragoodman** [comment]
got it. i looked them over and they all look good!

Thanks, @claytonzook. Closing!

**Comment by shiragoodman** [comment]
one last thing - do you know if a new ticket was opened per your comment above on 6/8?

**Comment by chaseakirby** [comment]
@shiragoodman I just opened (had this on my task list but didn't get to it) #42806 for auditing the pages for old footers. I tried to make it clear that the changes were not intended to be made in this ticket and that we would create additional tickets for updates.
