### ISSUE TITLE
Research necessary steps for creating a human-readable product list export

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41022]
## Issue Description
For our product list, we want to set up a regularly-scheduled export of the CSV out to a human-readable format that gets published to our platform website. We need to do a fair bit of research surrounding the capabilities of confluence, and what technical hurdles we may face in this process. Some areas to think about:

- We may need to transform data in flight before the CSV heads out to Confluence (almost definitely the data that sits in JSON-string formats). We can handle this similarly to how we handle things in the dashboard data repository, with a workflow in the product-directory repository and some scripts that handle the data. Are there any further requirements that we would not be able to handle this way?

- Does confluence have any support for intaking a CSV as-is by default without the need for plugins? If so, what formatting challenges might we face if we just feed it the CSV directly?

- Is there a Confluence plugin already available that may help us with our use case? We had prior found a confluence plugin that would allow an import of a CSV into a table, however if I'm remembering right, it required a manual input of the CSV. Are there API-driven capabilities in a plugin we can use to automate this process? If not, would it be feasible to write our own plugin for Confluence to solve our use case? What level of control would we have over the code in a Confluence Plugin and how would a custom-rolled output be handled by Scroll Viewport? If we roll our own plugin, how would we get it into our org's instance?

- Can we automate publishing of our product list(s) independently of the already automated publishing that is done twice a week by the confluence team?

---
## Tasks
- [x] Investigate if any new methods of data transformation will be necessary.
- [x] Research Confluence's default capabilities for handling a CSV input.
- [x] Research available plugins for Confluence for our use cases and their API capabilities.
- [x] Research writing our own Confluence plugins, how much control it gives us, and how it impacts Scroll Viewport. Also verify if we can get a custom plugin into our org's instance.
- [x] Investigate automated publishing in Confluence to see if we can set up an automated publishing schedule for our app independently of the existing platform-wide one.
- [x] Record the results of the research and proposed strategy for approaching this issue.
- [ ] Create a ticket to implement the agreed upon strategy that comes from the results of this research.

## Acceptance Criteria
- [ ] We have a recorded strategy for the approach to generating a human-readable product list.
- [ ] A detailed ticket to implement the process of creating a human-readable list has been created.
---

**Comment by rsmithadhoc** [comment]
I started a [Confluence page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2186313894/Human+Readable+Product+List+Research) for this research.

**Comment by rsmithadhoc** [comment]
Continued updating the Confluence page but still have some work to do. I am doing a basic test on the options to ensure they will work for our use case and then recapping the final options for the team to look at.

**Comment by pjhill** [comment]
Agreed, this is a nice collection of research. We need to conduct a brainstorming session and try to work out the way forward. We will work and log that effort under a separate ticket. Thanks for the thorough research document!
