### ISSUE TITLE
Make the Unified Sign in Page use JSON configuration

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#41026]
## Issue Description
Creating a standardized implementation of the Unified Sign in Page (USiP) via configuration files will allow the new clients to be onboarded quicker, create a seamless integration experience for developers on the vets-website/vets-api, and allow rapid implementation/iterations.

## Tasks
- [x] Create a JSON config file that implements the different clients of Signed In (MHV, Cerner, VA Mobile, OCC Mobile, and eBenefits)
- [x] Update appropriate unit tests to account for config-based updates
- [x] Consolidate logic where appropriate
- [x] Create an intake process to allow clients to give us their requirements/we give them our requirements, etc

## Acceptance Criteria
- [x] The Unified Sign in Page is configuration based
- [x] Documentation is created (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/485/files#diff-e661d2605b2f57c8f355787c7917ce291f188062a199db66d3b72b598369d66d)
