### ISSUE TITLE
Research and implement solution to automate additional product list fields

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41048]
## Issue Description
A process has been set up to automatically detect dependencies and cross-product imports and opening up pull requests for changes. We would additionally like to add automated scanning for two other fields on the product list:

"contains_tests" - Does the product have E2E, Contract and Unit tests in the code? We want to know true/false for each.  This should run once daily.
"last_updated" - When was the last time the code for this product was updated in GitHub? This should run once weekly.

**Note --**
contains_tests has been split into three fields --

`has_unit_tests`
`has_e2e_tests`
`has_contract_tests`

---
## Tasks
- [x] Add automated scanning for the `contains_tests` and `last_updated` fields on our product list.
- [x] Set up a workflow to scan for changes to `contains_tests` once a day, opens a PR with changes, and notifies slack of the open PR. 
~~- [ ] Set up a workflow to scan for changes to `last_updated` once a week, opens a PR with changes, and notifies slack of the open PR.~~

## Acceptance Criteria
- [x] Our product list has automated scanning for updates to `contains_tests` once a day  with PR and slack notification features.
~~- [ ] Our product list has automated scanning for `last_updated` once a week with PR and slack notification features.~~
---

**Comment by pjhill** [comment]
Note --
`contains_tests` has been split into three fields --

`has_unit_tests`
`has_e2e_tests`
`has_contract_tests`

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/21045

I'm blocked because someone hasn't updated the manifest.json files with each product's UUID.

**Comment by holdenhinkle** [comment]
I'm just about done with the code. I can't run it because ^.

Hopefully the manifests will be updated tomorrow so I can run the code and fix anything that needs to be fixed. I made note about refactoring a section, which won't take long.

Then I need to write tests...

**Comment by holdenhinkle** [comment]
The following fields are now being scanned daily. If there are changes, a PR is submitted to update the `product-directory.csv` in the `product-directory` repo.

- path_to_code
- has_unit_tests
- has_e2e_tests
- has_contract_tests

Updating the `last_updated` is being moved to a new ticket.

This ticket is complete.

**Comment by holdenhinkle** [comment]
The following fields are now being scanned daily. If there are changes, a PR is submitted to update the `product-directory.csv` in the `product-directory` repo.

- path_to_code
- has_unit_tests
- has_e2e_tests
- has_contract_tests

Updating the `last_updated` is being moved to a new ticket.

This ticket is complete.

**Comment by holdenhinkle** [comment]
Branch was merged!

**Comment by pjhill** [comment]
Hooray this is indeed done, and working nicely. Thanks for digging into this!
