### ISSUE TITLE
Conduct Research of OCTO Product List Comparison

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41041]
## Issue Description
OCTO Provided a product list they had compiled by looking at the existing product outlines, we would like to look at this list and determine:
- How much of their list overlaps with our product list?
- How many unique items exist on there list, that may need to be added to ours

A few steps can be taken to accomplish this:

1. Compare product names. Some should exactly match or be close. Those can be matched up first.
2. For the ones that do not match, we can line up the links on the OCTO list to our root urls to possibly find corresponding products that may be named differently across sheets.

---

## Tasks
- [x] Review the OCTO Product List, [located here](https://docs.google.com/spreadsheets/d/1M_VBZ3ob7oc5YfcvzhXxWgaMS5KB68mStezZhx_NErE/edit?usp=sharing)
- [x] Brainstorm approaches to deconflict these lists and document in this ticket (please include both the methods used and the methods not used
- [x] Conduct assessment tasks
- [x] Report on results

## Acceptance Criteria
- [x] We have a good understanding of the overlap of the two lists

**Comment by ddzz** [comment]
The OCTO Product List has been updated with a column that lists whether that product is in the new Product Directory. A large number of these products are not on the new list. There are several different reasons for why they are not on the new list:
* Old feature that no longer exists
* The name is unclear or vague
* The product refers to a function performed by VSP

**Comment by JoeTice** [comment]
Thanks for the input Darius, I'll take this one and follow-up with people on more detail on this

**Comment by JoeTice** [comment]
It doesn't seem like there is much that is applicable or informs our product list initiative at this stage, closing this ticket
