### ISSUE TITLE
Update Manifests to add UUID

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41040]
# Description
Currently, the `productId` key in the `manifest.json` files in each product folder are populated with simple integers. These values need to be changed to UUIDs.

For this task, codeowners can be temporarily borrowed to our team for all manifests on vets-website. Add:

`src/applications/**/manifest.json @department-of-veterans-affairs/qa-standards`

To the bottom of the codeowners file to assume control of all manifests. Additionally, please coordinate with release tools before doing this to ensure they are aware we are making these changes.

# Tasks
- [x] Request authorization to unilaterally update the contents of the `manifest.json` files in `vets-website`
- [x] Update each `manifest.json` file to remove the simple integer `productId` and insert the UUID `productId` from the assembled product list [here](https://docs.google.com/spreadsheets/d/1VaXAZIYj2LdG4H9ZQUbdCGjMk5qQ8Ari2mMySF1oah0/edit?usp=sharing)

# Acceptance Criteria
- [x] All productIds in `vets-website` are using the UUIDs defined in the product list

**Comment by rjohnson2011** [comment]
Picked up this ticket late Friday afternoon. Reviewed this morning, seems like a straightforward addition to `manifest.json` files. I'll start work & reach out to the team for any questions.

**Comment by rjohnson2011** [comment]
PRs created & deployed:
https://github.com/department-of-veterans-affairs/vets-website/pull/21049
https://github.com/department-of-veterans-affairs/vets-website/pull/21048

**Comment by rjohnson2011** [comment]
PR deployed to remove QA Standards from CODEOWNER https://github.com/department-of-veterans-affairs/vets-website/pull/21059
