### ISSUE TITLE
526ez | Update military service options

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41046]
## Description

Lighthouse has a new API that provides a list of service branches (`https://api.va.gov/services/benefits-reference-data/v1/service-branches`). [EVSS now validates from this endpoint, using the `description`](https://dsva.slack.com/archives/C8R3JS8BU/p1649702827450209?thread_ts=1649700446.433219&cid=C8R3JS8BU).

```json
[
  { "code": "AAC", "description": "Army Air Corps or Army Air Force" },
  { "code": "AF ACAD", "description": "Air Force Academy" },
  { "code": "AF", "description": "Air Force" },
  { "code": "AFR", "description": "Air Force Reserves" },
  { "code": "ANG", "description": "Air National Guard" },
  { "code": "AR", "description": "Army Reserves" },
  { "code": "ARMY", "description": "Army" },
  { "code": "ARNG", "description": "Army National Guard" },
  { "code": "CG ACAD", "description": "Coast Guard Academy" },
  { "code": "CG", "description": "Coast Guard" },
  { "code": "CGR", "description": "Coast Guard Reserves" },
  { "code": "MC", "description": "Marine Corps" },
  { "code": "MCR", "description": "Marine Corps Reserves" },
  { "code": "MM", "description": "Merchant Marine" },
  { "code": "N ACAD", "description": "Naval Academy" },
  { "code": "NAVY", "description": "Navy" },
  { "code": "NOAA", "description": "National Oceanic & Atmospheric Administration" },
  { "code": "NR", "description": "Navy Reserves" },
  { "code": "OTH", "description": "Other" },
  { "code": "PHS", "description": "Public Health Service" },
  { "code": "SF", "description": "Space Force" },
  { "code": "USMA", "description": "US Military Academy" },
  { "code": "WAC", "description": "Women's Army Corps" }
]
```

To update Form 526 service history page (`/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history`) to include all branches (e.g. Space Force), we need to update the `vets-json-schema` source and test the results.

We will also need to update logic that differentiates a Reserve and National Guard service from the others. 

> Questions:
> - Do the military academies count as active military service, reserve, or neither?
> - What about the Army Air Corps or Army Air Force?
> - What about Merchant Marines?
>
> ANSWER ([source](https://dsva.slack.com/archives/C1VBAHWQL/p1663275692636159?thread_ts=1663269540.702159&cid=C1VBAHWQL)):
> The EVSS form526 API classifies guard/reserves as any service that contains `RESERVES` or `AIR NATIONAL GUARD` or `ARMY NATIONAL GUARD`. That means the academies are not guard/reserves, so they're treated like any other branch for claims processing.

> ANSWER ([source](https://dsva.slack.com/archives/C1VBAHWQL/p1663272060027269?thread_ts=1663269540.702159&cid=C1VBAHWQL))
> Any branch branch of service (including "other") can be active, but guard/reserves cannot get BDD unless on federal orders. If someone selects "Other", that probably means their branch wasn't listed, so you don't need to ask if they are guard or reserves because they would have picked one of those if needed.

## Acceptance Criteria

- [x] Fields in the 526 that ask about military service branch are using the data from the BRD endpoint
- [x] Unit tests complete (90% coverage)
- [x] E2E tests complete
- [x] Accessibility testing complete
- [x] Reviewed and approved by product and/or design

## Tasks

- [x] Update vets-json-schema repo
- [x] Verify that this change work without changes to the backend
- [x] Update the frontend to differentiate active & reserve/guard service
- [x] Update tests

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [x] Passed E2E testing (90% coverage)
- [x] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Reviewed and approved by product and/or design
---

**Comment by Mottie** [comment]
Before starting this work, we need to figure out what to do with the "Other" choice.
- If the Veteran picks it, will 526 need to ask for a more specific service name? Form 526 is auto-established, so it doesn't need to follow the form exactly - we'll need to discuss this with Lighthouse
- Also, if the "Other" choice is made, we need to ask the Veteran if their service was within the reserves or national guard, because we have additional questions that ask if they were activated to make sure they are eligible to file a claim.

**Comment by Mottie** [comment]
Update:
- The backend is rejecting these options, possibly due to the [`dist` file not yet being updated](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/726):

    <img width="626" alt="form - The property '#/serviceInformation/servicePeriods/0/serviceBranch' value 'Women's Army Corps' did not match one of the following values: Air Force, Air Force Reserve, ..., Public Health Service in schema 517095c7" src="https://user-images.githubusercontent.com/136959/197573615-e0c76264-4730-4637-9382-80e246406d72.png">

- We need to figure out what to do about [`militaryRetiredPayBranch` & `separationPayBranch` values](https://dsva.slack.com/archives/C8R3JS8BU/p1666626201612449)
- Opened a [PR to revert vets-json-schema changes](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/727) until we're ready and can coordinate these changes so as to not break 526 in production

**Comment by Mottie** [comment]
Update: FE changes PR is "essentially complete with these exceptions:

- The `all-claims/tests/schema/schema.unit.spec.js` unit test will continue failing until the vets-json-schema changes have been merged - see [PR #726](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/726)
- Submission from the FE changes (not yet merged) will fail until vets-json-schema is updated
- We as a team need to discuss removing the `enum` values from `militaryRetiredPayBranch` & `separationPayBranch` and replacing them with BRD service branches on the FE
- Fallback BRD data `tests/fixtures/mocks/service-branches.json` has a 24th entry ("Army Nurse Corps") that isn't part of the Lighthouse endpoint. The non-essential `code` within the fallback data is missing. Either way, we will need to adjust this entry based on [Lighthouse's findings](https://dsva.slack.com/archives/CKUCFQAHJ/p1666733364574329?thread_ts=1666708394.250659&cid=CKUCFQAHJ).

**Comment by saderagsdale** [comment]
@data-doge @Mottie I just updated the AC to accommodate [this finding](https://coforma.slack.com/archives/C039EAY655H/p1667235409782859) from last week.

**Comment by data-doge** [comment]
Code merged in https://github.com/department-of-veterans-affairs/vets-website/commit/5e00be935a209e05c813da7566fada3e6ee9a36d.

**Comment by saderagsdale** [comment]
@data-doge I checked off the review AC for product. Are the other items ready to be checked off?

**Comment by Mottie** [comment]
I can only think of checking the separation pay and retired pay dropdowns... then we need to make sure stuff is getting submitted. We can probably check with lighthouse in our touchpoint today to see if there have been any rejections.

**Comment by saderagsdale** [comment]
@Mottie did you get what you needed today from LH?

**Comment by Mottie** [comment]
Yes, I think we can close this.

**Comment by saderagsdale** [comment]
@data-doge I'll let you close if it's good with you (once Josh has confirmed his review).

**Comment by saderagsdale** [comment]
@joshkimux Hey Josh! Can you let us know if this is good to close from an accessibility standpoint?

You can go [here](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) and log in as [vets.gov](http://vets.gov/).[user+0@gmail.com](mailto:user+0@gmail.com). Password for that user is [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

**Comment by joshkimux** [comment]
Thanks so much @saderagsdale ! I'll review this ASAP

**Comment by joshkimux** [comment]
@saderagsdale and @data-doge we can close this out! No new issues from this particular change 🥳 

That being said, while testing, I noticed several other unrelated [accessibility issues which I've documented here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49655). @Mottie we _may_ have tickets already open working on these, so feel free to ignore/check off anything that is already in progress or has been resolved 🙏
