### ISSUE TITLE
[CDP] Review icons in the cards' status sections

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#41049]
## Issue Description
During the Combined Debt Portal's midpoint review, we received feedback that we should review the icons used in the debt and copay bill status cards to make sure they're being properly used within the context of each status. For example, some statuses use a warning icon while others use an informational icon. 

Additionally, we should seek accessibility guidance on alt text or screen reader only text to indicate what's being communicated. 

---
## Tasks
- [x] Review [the iconography used for each debt status](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148550080/simulate/no-panels?mode=i)
- [x] Meet with Angela Fowler to explore the current experience within MCP and gain guidance for alt text or screen reader only text (Add FE to this meeting) 

## Acceptance Criteria
- [x] Debt status icons have been reviewed and updated as needed 
- [x] Guidance from the meeting with Angela is documented in this ticket
- [x] Follow-up tickets are created and linked as needed

**Comment by rileyorr** [comment]
Angela's guidance is as follows:
- The status icons need alternative text based on the icon's level of importance 
- Alert, important, informational, warning etc. 
   - There isn't standard verbiage to follow 

We were unable to review the iconography used for each debt status this sprint, so this ticket will fall into next sprint.

**Comment by rileyorr** [comment]
[The iconography](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148550080/simulate/no-panels?mode=i) has been reviewed and the following statuses have changed to an informational icon: 

- 71
- 655, 817
- 212
- 681, 682
- 600, 601
- 811
- 801, 802, 803, 804, 809, 820
- 822
- 825
- 821

**Comment by rileyorr** [comment]
[Frontend ticket can be found here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/42708).
