### ISSUE TITLE
Update the BigQuery product list ingestion mechanism in the dashboard data repo

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41042]
## Issue Description
We wrote the initial ingestion mechanism for the product list to work off the old schema and old product list file. We need to update both the schema file as well as any list-specific attributes in the ingestion mechanism to match the new list.

---
## Tasks
- [x] Update the product list schema file to the new product list schema
- [x] Update the product list script to ensure everything is compatible with the new list

## Acceptance Criteria
- [x] The product list is being ingested into BigQuery daily in its entirety.

---

**Comment by CBonade** [comment]
After much wrestling with this today, and some changes to how we process CSVs, I have this uploading to BQ in my feature branch. Going to do some code cleanup tomorrow and error handling and it should be ready for merge early tomorrow.

**Comment by CBonade** [comment]
All set here. Added some additional error handling to ensure that the workflow gets failed if something fails to meet our schema and causes the ingestion to fail.
