### ISSUE TITLE
Platform: Fix upload of file names with multiple periods

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41059]
## Description

If a user tries to upload a document on VA.gov and the file name has a period in it (e.g. `document.4`), the user sees the below error message. The reported issue happened in the burial benefits application but we have been testing it across different applications and tools and it seems to be a consistent issue (526, 1010EZ, claim status).

![upload issue error message](https://user-images.githubusercontent.com/136959/167215455-c1991a35-9f2d-4e44-a7de-8121c6a62d67.PNG)

Reference: https://dsva.slack.com/archives/CBU0KDSB1/p1651859386943059
CC: @clantosswett & @Kimberley2019   

## Tasks

- [ ] Troubleshoot & fix code that checks for matching file extension
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
