### ISSUE TITLE
Migrate view-payments app to `va-telephone` web component

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41054]
# Background
Now that the `<va-telephone>` component is being used in favor of the `<Telephone>` React component, we need to swap the `<Telephone>` component out on the View Payments app as the React component will be deprecated at some point.

## Tasks
- [ ] Swap the `<va-telephone>` component for the `<Telephone>` React component on View Payments
- [ ] Ensure all unit and e2e tests still pass
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The `<Telephone>` component has been swapped out for the `<va-telephone>` component
- [ ] A PR has been submitted for review
