### ISSUE TITLE
[FE] [BUG] "Latest Update" date is not correctly translated

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#41064]
## Background

The spanish version of "Latest Update" should keep the same time format and not append the timezone.

![Screen Shot 2022-05-06 at 3.17.46 PM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/1706d5eb-5aca-4553-ab6a-570dd6219135)
![Screen Shot 2022-05-06 at 3.17.33 PM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/fd1797cf-1dde-42dd-8729-1ae9674a44b6)

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
I've looked into this and before I was trying to avoid having to specifically translate this date format using date-fns' localization, but it's not flexible enough for us since it converts to 24h time for spanish time formats. Here are the options we have as I see them:

- Send this "date at time" string in the next translation batch
- Change this format to something like "6/3/2022, 2:53 p.m." or "June 3, 2022, 2:53 p.m." that can be translated using date-fns (maybe? not sure about the phillipines)

Let's chat about this at standup on Monday.

cc @loripusey @niradatta1 @kristenmcconnell

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Do you have any information on how VA wants to handle the internationalization of dates/times? See above.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell I will check into this.

**Comment by loripusey** [comment]
@kristenmcconnell did we ever get any information for this ticket?

**Comment by kristenmcconnell** [comment]
I don't believe that we did. @DanielleThierryUSDSVA Did you ever talk to the State Dept about this? If not, @loripusey could we add this to our questions with some of the things that we found during the Spanish study?

**Comment by loripusey** [comment]
@kristenmcconnell @ytsaoca Do we have a consolidated list of things from the Spanish study that we need to bring to the translators attention?

**Comment by kristenmcconnell** [comment]
@ytsaoca That will be in the PDF that we discussed, correct?

**Comment by loripusey** [comment]
@ytsaoca @kristenmcconnell Can you set up some time for us to review the recommendations from this study? I'd like to submit round 3 to the SD soon and any recommendations from this study need to be a part of that, if applicable.

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @kristenmcconnell. I thought we'd talked with translators about this, but let's follow up as part of the list of questions. Thanks!
