### ISSUE TITLE
Fix linting warnings in view payments app

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41061]
# Background
There are several linting warnings that are occurring in the view payments application. We should clean these up

## Tasks
- [ ] Fix linting warnings in view-payments app
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The view payments application doesn't have linting warnings
- [ ] A PR has been submitted for review
