### ISSUE TITLE
[FE] Don't allow users to attempt check-in after the check-in window has expired

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#41065]
## User Story

As a Veteran, I wish to not be allowed to click the check-in button after the check-in window has expired, so that I will not receive a confusing generic error message.

## Background

Slack discussion: https://dsva.slack.com/archives/C02U11L00TF/p1651853862564099

### Error Scenario
- Veteran starts check-in, perhaps after the appt start time
- Veteran gets to the appointment list before the end of the check-in window (15 minutes after appt start time)
- Veteran taps “check in” after the window ends
- Veteran gets generic error message and we get this error alert, because the LoROTA entry has expired

## Implementation

We discussed auto-updating the appointment list such that the 'Check In' button is hidden as soon as the check-in window expires and the "Your appointment started more than 15 minutes ago. We can’t check you in online. Ask a staff member for help." message is shown.

We should also check the `checkInWindowEnd` time when the button is pressed and log an analytics event if the current time is later so that UX can come up with specific messaging to show if it remains common.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] "Check in now" button is not available immediately at the time the check-in window expires. (Including if the browser is re-opened after having been on another app)
- [ ] Analytics event is logged if "Check in now" is tapped after `checkInWindowEnd`
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by acrollet** [comment]
In code review: https://github.com/department-of-veterans-affairs/vets-website/pull/21096

**Comment by acrollet** [comment]
Merged, should get deployed this afternoon. Will validate on staging this morning.

**Comment by acrollet** [comment]
Just validated this on staging with @stephenBarrs !
