### ISSUE TITLE
Synthetic Monitors - Migrate sythentic monitors to Datadog: Release Plan

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41076]
# To-do List
- [x] Define a better name for heartbeat
- [x] Provide a better description of the monitor formerly known as “heartbeat” in the [playbook](https://vfs.atlassian.net/wiki/spaces/TTT/pages/1848999954/On-Call+Playbook+for+Synthetic+Monitor+Alerts#3.-Production---VA.gov---heartbeat)
- [x] Create a ticket for terraform integration
- [ ] Create a ticket for making the current synthetic monitor dashboard in Datadog publicly available as a dashboard (NOTE: completion of this ticket is not launch blocking)
- [ ] Create a ticket for documenting best practice for VFS teams to create synthetic monitors in Datadog (NOTE: completion of this ticket is not launch blocking)
- [x] Conduct go / no-go at Platform Office Hours
- [x] Contact SRE team to warn about the addition of a new monitor that alerts #oncall
- [ ] Clean up all tickets related to initiative

## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: One week 
- Desired number of users: 3
- The group(s) from which you'll recruit test users: Platform QA Standards Team
- How you'll recruit test users: Team Members who previously interacted with monitor output will be in the pool of users to select from.
- How you'll give test users access to the product: Slack notification channels are open to all and Datadog permissions are already in place for the team.
- What "Success" criteria will you look at before launch? [refer to the desired outcomes and KPIs in your product outline]
  - Datadog monitors create notifications in Slack when failures occur 100% of the time
  - In a one week period, Datadog monitors alert Slack with a false failure 2 or less times
- How you'll measure your "Success" criteria? 
  - Analyze the notifications in our notification Slack channel against 

### Results:

- Number of users: N/A

- Results per your "Success" criteria: N/A

- Number of bugs identified / fixed: N/A

- Any UX changes necessary based on the logs, user feedback, or VA challenges? N/A

### Planning:

- Desired launch date: 5/10/2022
- Post-launch KPI 1:
- Post-launch KPI 2:
- Post-launch KPI 3: 

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by JoeTice** [comment]
Tickets have been created for these items, a scope change was made to this effort, so expanding it into Sprint 2

**Comment by pjhill** [comment]
The release has been completed.
