### ISSUE TITLE
Compare English COVID booster page with Spanish and Tagalog pages to determine new content to be added

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41077]
## Issue Description
In updating the Spanish and Tagalog [COVID booster and additional doses](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) pages with new translations, we learned there is some content that is on the live English page that was never added to the Spanish and Tagalog pages. 

We need to do a comparison on the the live English page with the Spanish and Tagalog versions and create a Word doc of content that needs to be sent to our translation team. Be sure to highlight any content that we need translated.

## Tasks
- [x] Compare live English page with most recent Spanish page (Aliyah)
- [x] Create Word doc of Spanish page to send to translators (Aliyah)
- [x] Compare live English page with most recent Tagalog page (Aliyah)
- [x] Create Word doc of Tagalog page to send to translators (Aliyah)
- [x] Send Word docs to translation team (Randi)

## Acceptance Criteria
- [x] All missing Spanish and Tagalog content has been sent to translators

**Comment by aliyahblackmore** [comment]
Hi @RLHecht - I reviewed the Spanish and Tagalog Booster pages this afternoon to confirm that the "What to know before you get an additional vaccine dose" was the only section that was missing from the translation sent to us. I added the Word document with the content in [ ticket #39560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39560) but placing this here as well.
[To be translated to Tagalog and Spanish.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8682189/To.be.translated.to.Tagalog.and.Spanish.docx)

**Comment by RLHecht** [comment]
Thanks @aliyahblackmore I sent this to the translation team and created ticket #41305 to continue the work when we get the doc back. Closing this ticket.
