### ISSUE TITLE
[Review Instance] Update Review Instances for content-build & vets-website 

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#41079]
## Who is the devops resource on your team?

@mydesignrocks 

## Description

Release Tools is working on changing the default branches in the vets-website and content-build repos from master to main. 

> Part of this will require us to update the review instance configure and clean up jobs. Once we change the default branches in GitHub, and merge our PR in the devops repo for updating the review instance config, I believe we’ll need the seed job deployed in Jenkins so that review instances moving forward will use the main branch for vets-website and content-build.

## Background/context 

https://dsva.slack.com/archives/CJYRZK2HH/p1651862846899359

> We’re planning on making the switch on May 24 at 5 PM EST

---
## Tasks
- [x] PR to update review instance
- [x] Seed_job updated in Jenkins

## Acceptance Criteria 
- [x] Review instances build correctly in `content-build`
- [x] Review instances build correctly in `vets-website`

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/11188

**Comment by oseasmoran73** [comment]
[Slack](https://dsva.slack.com/archives/CJYRZK2HH/p1652821153155979) thread for execution of pipeline update

**Comment by oseasmoran73** [comment]
Closing as it seems to be working as intended. Feel free to reopen as needed!
