### ISSUE TITLE
HLR: Update contacts source

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41086]
## Description

The `va-telephone` contacts are being imported from the old React `Telephone` component, these need to be updated to:

```js
import { CONTACTS } from '@department-of-veterans-affairs/component-library';
```

## Tasks

- [ ] Update `CONTACTS` source
- [ ] Check all tests passing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
