### ISSUE TITLE
Midpoint Review [My Education Benefits, Authenticated 22-5490 Form (Fry/DEA) Updates]

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#41090]
# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [x] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41338

## Artifacts

Provide links or documents for the following: 

- [x] Product outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Form%2022-5490%20Updates/Product%20Outline.md

- [x] Finalized design prototype or mockup (End to End Mobile Flow)
https://accenturefederal.invisionapp.com/freehand/FRYDEA-Target-Designs-WE63OVY4?zoomToItems=Y2wzYWxuZTRpMDBsdDN4NnFiY3J3cjIwNA%3D%3D

- [ ] Research plan 

- [ ] Conversation guide 

### Content artifacts 

- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
**N/A**
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 
**To Be Developed**

## Asynchronous review option
Would you like this review to be asynchronous? 

- [x] Yes
- [ ] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

Additional awareness: @bethpottsVADEPO ,@ericks24 & @TamGIBill

**Comment by chaseakirby** [comment]
The async review has been confirmed for May 20th, 2022, meaning you will receive feedback by EOD. No meeting will be held.

**Comment by claytonzook** [comment]
@alexander-ferzola A reminder that if you can link us to the stakeholder interviews mentioned at the meeting today, but it could certainly be the findings report or even just a top line summary from that, we'd love to look at that in order to get a better understanding of your product and direction.

**Comment by alexander-ferzola** [comment]
> @alexander-ferzola A reminder that if you can link us to the stakeholder interviews mentioned at the meeting today, but it could certainly be the findings report or even just a top line summary from that, we'd love to look at that in order to get a better understanding of your product and direction.

Hi @claytonzook, I'm not able to link everything - but here is an overview of our initial round of research. We use these findings as our guiding principles for all of our My Education Benefits efforts (application forms to be updated and future features). 

[Va.gov Research Report Request.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8756496/Va.gov.Research.Report.Request.pdf)


**Note** Please do not share this information outside of this thread.

**Comment by claytonzook** [comment]
Thanks for these slides! 
No feedback from research practice area.

**Comment by alexander-ferzola** [comment]
Thank you all for your feedback. Before closing this ticket, we would like to recap feedback and update the group with our approach going forward. Please see the design implementation plan below that considers Va.gov recommendations along with our EDU business needs. We look forward to our next round of research as well and will update the group. 

**Note:** The following address recommendations for designs only. They do not include specific points about user research or developer implementation during staging. Those points of feedback have been documented and can be addressed in the future.

Tagging our EDU Product Owners for their awareness on this thread @ericks24 & @TamGIBill

[Fry.DEA Midpoint Review Feedback Response.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8787922/Fry.DEA.Midpoint.Review.Feedback.Response.pdf)

**Comment by allison0034** [comment]
Per the conversation with Matt Self, Matt Dingee, Chris Johnston and Kevin Hoffman this is the approach the team will be taking...

- Input Message Component - will be tested during our next round of usability testing. Per usual, we’ll work with Shane S. to coordinate that effort.

- Wizard Deprecating - Though our team is not ready to lead the discovery effort for this change, and it is not within the application, it is something we will ask during usability testing to gather preliminary research. We look forward to sharing that with the platform.
