### ISSUE TITLE
[FE] Ensure all sentences are translated with single keys

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#41091]
## User Story

Translations should be understandable to veterans.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

Some sentences have interpolated data in the middle of them, such as "We'll come get you at the " CLINIC "waiting room when it's time for your appointment". We should use the `<Trans>` component to translate these with single keys, rather than splitting the message into two separately translated keys. This will improve the accuracy of translations.

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Moving to closed since validated by FE only
