### ISSUE TITLE
Change end dates for conflicts on Veterans health issues related to service history page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41095]
## Issue Description
While working on the [Veterans health issues related to service history](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/index.html) page to fix header levels, we discovered that the end dates to 2 conflicts should be updated. We currently list them as "present" and believe these should have concrete end dates.

The 2 conflicts that need to be updated:

End date for the Afghanistan war: **August 30, 2021**
Sources: CFR timeline, White House press release

End date for the Gulf War: **February 28, 1991**
Sources: History.com, Britannica

We've reached out to Tanekwa Bournes in VBA comms to confirm these dates are correct and are waiting on her response before going forward.

Once we update this page we should also check if these need to be updated elsewhere on VA.gov. 

## Tasks
- [ ] Change end dates on health issues related to service history page 
- [ ] Review and publish (Megan)
- [ ] Search VA.gov for other pages to update
- [ ] Update other needed pages 
- [ ] Review and publish (Megan)

## Acceptance Criteria
- [ ] End dates for 2 conflicts are updated on live pages

**Comment by RLHecht** [comment]
Update: Danielle is reaching out to health care SMEs.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA checking in on this one. Have you heard from health care SMEs on these dates?

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
