### ISSUE TITLE
Letters: Add keyboard navigation e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41106]
## Description

To improve accessibility, we are adding keyboard navigation end-to-end tests to the letters app.

## Tasks

- [ ] Add keyboard e2e test for letters app

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
