### ISSUE TITLE
[FE] Audit app for existing strings that are missing translation, to add to Round 2 of Translation

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41107]
## Related Documentation
[Round 1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/Translations%20Received%205-4-2022.md) translations.

## Description
Before we send out our second batch of translation, we need to audit an up-to-date version of the application to find any strings that have been inserted since the first round was sent out.

## Tasks
- [ ] Audit application and generate list of JSON keys / values that need translation

## Acceptance Criteria
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
