### ISSUE TITLE
HLR: Move source folder

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41101]
## Description

The Higher-Level Review (HLR) is a form for processing claims appeals. It is currently stored in the `disability-benefits` folder along with form 526. It belongs in the `src/applications/appeals` folder along-side the Notice of Disagreement form.

## Tasks

- [ ] Move HLR folder into `src/applicagtions/appeals` folder
- [ ] Verify move didn't break the build process
- [ ] All tests passing
- [ ] Verify the move didn't effect the app in staging/dev/production

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Update now available on staging. I have verified that the HLR form still works after the source folder move. I will test again in the morning.

**Comment by Mottie** [comment]
Verified no issues in prodution
