### ISSUE TITLE
NOD: Add keyboard e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41109]
## Description

To improve accessibility, we need to add keyboard-only navigation of the Notice of Disagreement app end-to-end testing.

## Tasks

- [ ] Add keyboard-only e2e tests on happy path

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
