### ISSUE TITLE
[FE] Show generic error page when pre-checkin is attempted for a canceled appointment

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#41105]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

## User Story

As a Veteran, I do not wish to go through pre-checkin only to see an error message at the end, so that I feel that my time is respected.

## Related Documentation
- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

As a temporary workaround until the parent epic is completed, we should show the generic pre-check-in error page if a Veteran authenticates for pre-checkin and any appointment has been canceled.

Slack thread: https://dsva.slack.com/archives/C02U11L00TF/p1652122257506199?thread_ts=1650032406.950339&cid=C02U11L00TF

Example of canceled appt object: https://dsva.slack.com/archives/C02U11L00TF/p1650033080189729?thread_ts=1650032406.950339&cid=C02U11L00TF

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by sarahknoppA6** [comment]
this is thought to already be in production- Adrian will look at this ticket and see if it can be closed out.
