### ISSUE TITLE
Content changes to Find your VA pension management center page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41116]
## Issue Description
Stakeholder Tanekwa Bournes sent us content changes we need to make on our [Find your VA pension management center](https://www.va.gov/pension/pension-management-centers/) page.

We need to review the Word doc she provided to make sure these changes should be incorporated on the page and also rework them for plain language and to ensure they meet VA.gov's voice and style standards.

These changes need to go live on **June 6**. 

Word doc of changes to make: [https://app.zenhub.com/files/133843125/4e7fd4e1-87d9-466e-9da5-402db536b18a/download](https://app.zenhub.com/files/133843125/4e7fd4e1-87d9-466e-9da5-402db536b18a/download)

Currently on the live page, we list the same address for all the different pension centers. We may be able to rework and condense this page while making the above changes. These changes need to be approved by stakeholder Angie Smith, so we'll need to be sure to send these in enough to time to publish the updated page by June 6. 

## Tasks
- [x] Assess stakeholder request
- [x] Make content updates to existing page 
- [x] Review (Laura)
- [x] Copy edit (Megan)
- [ ] Submit page to Beth for OCTO-DE review (Megan)

## Acceptance Criteria
- [x] Content changes are ready for final review

**Comment by katherine-fung** [comment]
@RLHecht @laurwill - I have some questions about this page for the stakeholder. Let me know if I should tag another team member here, or the best way to get the questions answered.  

1. Since people are no longer mailing the forms directly to the 3 pension management centers, do they still need to know the 3 pension management centers and what each one processes? 

2. If yes, what are other reasons someone would need to find their pension management center? This information will help clarify the purpose of the page. 

In the meantime, here's a draft of the page incorporating the stakeholder's requests and condensing the address where people should send their forms. 

https://docs.google.com/document/d/1IZ13DBuhcV8E2sUfbH7PKCTPLMFF8_Wp/edit#

**Comment by laurwill** [comment]
Thanks @katherine-fung ! Just an update here: Based on your very good questions and after looking at some previous emails about this content, we may suggest retiring this page. 

But first, @RLHecht is reaching out to Public Websites to help us find any pages that link here, as those pages would all need to list the mailing address instead. Stay tuned!

**Comment by RLHecht** [comment]
I created ticket #41820 for PW to do their search. Also linking ticket #21307, which lists other pages where we reference pension management centers. Once we retire the page we can close this ticket and that old one.

**Comment by laurwill** [comment]
Update: We're waiting on approval from Angie Smith to retire this page, so in the meantime, we're making the requested updates with minimal edits for PL and site style. 

I sent suggested changes in the attached word doc to David Coyle and cc'd Tanekwa — will post back when he responds!

[Find your PMC page updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8790016/Find.your.PMC.page.updates.docx)

**Comment by laurwill** [comment]
Update: David approved our changes — we let Angie know we were making these changes as an FYI. We'll plan to push these live tomorrow, ahead of the June 6 deadline.

**Comment by megzehn** [comment]
This is copyedited, and I will plan to publish Monday AM before 9am!

**Comment by megzehn** [comment]
published. Ready for you to verify, @RLHecht!
