### ISSUE TITLE
[BE] Pass uuid or appointmentIEN to CHIP confirm-demographics endpoint

### ISSUE THREAD

**Issue by olamik** [department-of-veterans-affairs/va.gov-team#41113]
## Corresponding CHIP ticket
https://github.com/department-of-veterans-affairs/chip/issues/823

We don't need a feature flag or to coordinate the releases at the same time.

## Issue Description
In order to support reporting in the Executive BI Dashboard of e-checkins that have not been completed due to unconfirmed demographics, the CHIP API needs to be able to associate a demographics confirmation with an appointment during e-checkin where possible.

---
## Tasks
- [ ] Pass either the uuid or appointmentIEN in the request body of the `confirm-demographics` CHIP API call

## Acceptance Criteria
- [ ] `confirm-demographics` endpoint succeeds with new parameters
- [ ] There is no tangible change in the behavior of `confirm-demographics` from a vets-api perspective when passed the new parameters

## Notes
- The `confirm-demographics` endpoint in CHIP will be updated to accept a uuid or appointment IEN value in its request payload, and consumers of the endpoint are asked to pass one or the other if available. This will not have any impact to consumer-facing behavior. To support existing functionality, the endpoint will not fail if these are missing.
- Discussed with Kanchana on 5/9

**Comment by olamik** [comment]
The CHIP-side update to this endpoint has been deployed to preprod

**Comment by olamik** [comment]
The CHIP-side update has been pushed to production.

**Comment by kanchanasuriya** [comment]
The staging environment has issues in initiating check-in for the appointment ([Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1653328271135279))

Currently blocked in verifying the changes against CHIP staging environment
