### ISSUE TITLE
Revise 2 existing education tier 1 pages in prep for TOE launch

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#41111]
## Issue Description
Add crosslinking and make overall improvements to these 2 existing pages in preparation for the TOE tool launch:
[Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
[VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/)

---
## Tasks
- [x] Revisions to [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
- [x] Revisions to [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/)

## Acceptance Criteria
- [x] All relevant pages are updated for TOE launch.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
I sent these revised pages off to stakeholders for review, along with the new comparison page (DEA/Fry) and the new tool page called Transferred education benefits for family members.

**Comment by bethpottsVADEPO** [comment]
Follow up with stakeholders on these additional edits from Megan: https://docs.google.com/document/d/1aSrpV-mma_1OWgE10buo5J1s7RwsYzmJjzVY5aCdLtE/edit

**Comment by bethpottsVADEPO** [comment]
@katherine-fung When you get into updating the 2 pages with stakeholder edits, take a look at these suggestions from Megan too. Then we can decide if we need stakeholders to review a second time or not. 

@RLHecht I'm realizing that this work may need an epic. I don't think there already is one...

**Comment by bethpottsVADEPO** [comment]
@RLHecht Sorry, I see the epic now. Would you just attach the tickets that aren't yet collected together in the epic? Thanks!!

**Comment by katherine-fung** [comment]
Beth and I met with education stakeholders. I made changes to these pages based on their feedback: 

1. Transfer your Post-9/11 GI Bill benefits:
http://preview-prod.vfs.va.gov/preview?nodeId=952 

2. Transferred education benefits for family members:
http://preview-prod.vfs.va.gov/preview?nodeId=44698 

- For the family members page, I added a QA "What happens after I apply to use transferred benefits?" It might not be necessary. 

- I'm also wondering if the QA "What if the service member hasn’t requested a transfer of benefits yet?" is repetitive or redundant and whether we should get rid of it. Or whether we want to have it on the page because this issue is one that people often trip on. 

- Wherever we refer to the Transfer of Education Benefits, I've written out the entire phrase with the acronyms in parentheses. That deviates from usual style, but it felt strange to say just TEB in some places and I wonder if people will just scan to their section and miss the first instance that explains what TEB is. I'm happy to go with whatever is best here. 

- For eligibility requirements, I took out the "if the child gets married..." detail out entirely.

**Comment by katherine-fung** [comment]
I spoke with SMEs about the 2 TOE/TEB pages, and updated the pages accordingly. 

I also took a look at the tool itself, to make sure the static pages sync up with it. There is some language in the tool itself I wonder if we want to make suggestions for. 

For example, the tool says "Your application will be saved on every change." as you make your way through the steps. @bethpottsVADEPO, I think you were working with the Supplemental Claims product team to update similar language, right? 

I've attached a Word doc with the original tool content, and some suggestions for the very first sign-in page. 

[https://app.zenhub.com/files/133843125/7c816e5f-0561-4397-b017-0e40e02db755/download](https://app.zenhub.com/files/133843125/7c816e5f-0561-4397-b017-0e40e02db755/download)

**Comment by katherine-fung** [comment]
@RLHecht - I made the final updates to these pages based on SME feedback. They're ready for final copy editing. cc @bethpottsVADEPO 

Transfer your Post-9/11 GI Bill benefits:
http://preview-prod.vfs.va.gov/preview?nodeId=952

Transferred education benefits for family members:
http://preview-prod.vfs.va.gov/preview?nodeId=44698

**Comment by RLHecht** [comment]
Thanks! Going to close this ticket out. The final copyediting is being tracked in #50830
