### ISSUE TITLE
Update Platform page - Research Checklist

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41122]
## User Story
As a VFS team member, I want to easily find important research guidance, so that I'm confident my work follows VA.gov principles and aligns with their standards.

As a Platform team member, I want to make sure that documentation on Platform is up to date so that I can reference latest guidance to teams.

- Intended Audience: VFS
- Desired Outcome: Updated Platform page
- Due Date: N/A

## Description
Several links are out of date, and some items should be updated to reflect most current guidance. This work has been started in a [Draft - Platform Research Checklist page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2151579662/Clayton+-+Copy+of+Research+Checklist+-+WIP) 

## Artifacts Needing Updates
[Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Tasks
- [x] Review document for out of date links
  - [x] Update invalid links
- [x] Review items for outdated guidance
  - [x] Update with most current guidance

## Acceptance Criteria
- [x] [Platform Website: Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html) has up to date information for VFS teams to confidently use
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
Ready for peer review

**Comment by shiragoodman** [comment]
@claytonzook i added some comments to your draft checklist. Most of my findings were small - this looks good! Please make the changes and answer my questions. You should be good to publish after that.

**Comment by shiragoodman** [comment]
@sstrassberg It looks like Clayton didn't have a chance to review my comments before going OOO. Would you be able to quickly review my non-grammatical-related comments on his [draft Research Checklist page?](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2151579662/Clayton+-+Copy+of+Research+Checklist+-+WIP) I'd rather not wait to publish until he returns.

**Comment by shiragoodman** [comment]
Thanks @sstrassberg ! I will make the changes and we'll publish to the source page today. The changes won't be available on Platform Website until Tuesday 7/12

**Comment by sstrassberg** [comment]
@shiragoodman You can use this link for "Update the research repo board": https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70

But I'm confused about the research-plan and conversation-guide comments. They are linked to the templates. Are you saying they shouldn't?

**Comment by shiragoodman** [comment]
@sstrassberg sorry, I should've clarified. The research plan and conversation guide are linked as templates and should be. However when we give them guidance for how to name their file in github, "research-plan.md" and "conversation-guide.md" text has been autoformatted to a url... similar to the way VA.gov is always autoformatted to be a url. They should be formatted as text.  Hope that clarifies my comments!

**Comment by sstrassberg** [comment]
@shiragoodman Okay, yes that makes sense. Thanks for clarifying.
