### ISSUE TITLE
Complete Research documentation audit

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41125]
## User Story
As a Platform team member I want to make sure that all important documentation has been migrated to Platform

- Intended Audience: Gov Team
- Desired Outcome: all GH documentation on research has tech-debt ticket to be migrated to Platform
- Due Date: 

Assignee: @claytonzook 
Peer reviewer: @chaseakirby 

## Description
An audit was begun by Naomi to ensure that all important documentation from github was transferred over to Platform. Some items of [the audit documentation](https://docs.google.com/spreadsheets/d/1LJRTKRJI84kBhDWYIcTfuG2QsZc06paPV5Difi_cHoI/edit#gid=0) may now be complete but not marked as such on the audit. Additionally some items may not be complete and then need a new tech-debt ticket.

## Artifacts Needing Updates
[Research documentation audit](https://docs.google.com/spreadsheets/d/1LJRTKRJI84kBhDWYIcTfuG2QsZc06paPV5Difi_cHoI/edit#gid=0)

## Tasks
- [x] Create tech-debt tickets as necessary to ensure all the items from the audit are in backlog to be worked on. Tickets should include
   - merging the VSA and Platform GH docs on a topic as needed
   - finding a place for this information to live on Platform (either updating a section/page, or creating a new section/page)
   - marking GH docs as depreciated once the information is on Platform
   - marking the line on the audit doc green once complete

## Acceptance Criteria
- [x] Audit documentation has been updated
- [x] Tech Debt tickets have been created for remaining audit items
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
Still on hold. At research ops meeting there was not enough time to discuss adding SUS to platform. Although after I presented it as a topic of discussion, Martha suggested if we add SUS that we should also ass AUS.

**Comment by claytonzook** [comment]
@shiragoodman The System Usability Scale (SUS) was a suggestion by Kevin, so we really want to figure out if this is something we want to implement for VA research before we undertake building a page for guidance.

**Comment by claytonzook** [comment]
Since the only outstanding item on this audit is not an existing document, but a proposed new document, then I feel like this ticket is complete and ready for peer review @chaseakirby

**Comment by chaseakirby** [comment]
@claytonzook I do have one question about Row 23 regarding [Using Zoom for Research](https://vfs.atlassian.net/wiki/spaces/RD/pages/1622180012), this row is marked as green in column A but yellow for the rest of the row and no ticket linked.
Is there anything that needs done for this one?
Otherwise, I think it looks good ticket wise based on the notes/comments I see.

**Comment by claytonzook** [comment]
@chaseakirby I didn't disrupt the color coding system that was already in place before I started looking at this document, I just layered my own over it. I'm not sure what the yellow stood for, but my color coding was that I marked the first col green after that row was completed (either as a new ticket or previously migrated)

In looking at the Zoom lines on this sheet, all the Zoom info is currently migrated to Platform. I think row 23 may have not been in Github previously, so there was no place to mark deprecation. But it is indeed on Platform [as the individual pages linked on this page](https://depo-platform-documentation.scrollhelp.site/research-design/using-zoom-for-research)

**Comment by chaseakirby** [comment]
@claytonzook Ok great, just wanted to make sure there wasn't an outstanding task that hadn't been addressed yet. 
I agree that this ticket is complete with the new document discussion being outside the scope and we can create a ticket for that if and when that is decided to be added.

**Comment by shiragoodman** [comment]
@chaseakirby @claytonzook i would like to create a ticket for the backlog regarding the System Usability Scale (SUS)... just so it doesn't drop off our radar. Maybe we can propose a later date when this should be readdressed?

**Comment by chaseakirby** [comment]
@shiragoodman @claytonzook I agree Shira. I created a very basic ticket #45118 to investigate the SUS. I added the on-hold label for now. 
Clayton, can we recommend a date to readdress this or should that date be determined with Naomi and others input?
