### ISSUE TITLE
[FE] Display Different Message & Sub Message when Attempting to Pre-Check-in on Day of Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41139]
## Feature Branch
check-in/epic/update-error-messages

## User Story
As a Veteran, when I try to do pre-check-in on the day of appointment up until 15 minutes after my appointment, I want to see a message that more accurately tells me why I cannot do pre-check-in so that I will not be confused.

## User Workflow
- Given I
    - Get a Pre-check-in link after confirming an appointment
- When I
    - Click the link 
- Then 
    - If I clicked on the link from midnight on the day of the appointment to up to 15 minutes after the appointment, I see this message & sub-message
        - Message = "Sorry, pre-check-in is no longer available"
        - Sub-Message = "You can still check-in with your phone once you arrive for your appointment."
    - If I clicked on the link more than 15 minutes after the appointment time, I see this message
        - Message = "Sorry, pre-check-in is no longer available."
        - Sub-Message = NONE
  
## Wireframes
- [Sketch - midnight to 15 minutes after appointment](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/m1l0PA7) 
- [Sketch - more than 15 minutes after appointment](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/QblM3GG)
- NOTE: The following is a screenshot of the Sketch file at the time this ticket was created, if the screenshot differs from the Sketch file when this ticket is worked, please raise the issue with the team during stand up

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/79239c19-2c90-48f2-ac4f-eeb15a31b2bf)

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/0320dc52-bb3f-4801-bfae-ac210e826fb1)

## Tasks
- [ ] [FE] Display different message & sub-message depending on the time the link was clicked
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by sarahknoppA6** [comment]
This is in a feature branch with another work item and is not in prod/hasn't been merged yet.

**Comment by loripusey** [comment]
Looks good @brdunfield ; if this is in a feature branch can you add the branch name in the ticket? thanks.

**Comment by zach-park** [comment]
Hi @brdunfield , they look really good overall. I've captured some additional comments in the annotations (link below): 

[After-midnight until 15 minutes after appointment start time](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/3CDBC56A-DF5A-4761-9859-2B83D912810F): 
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/3CDBC56A-DF5A-4761-9859-2B83D912810F

[15 Minutes or later past appointment start time](https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/C853A978-44D0-48ED-8170-A459CE2AA141): 
https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/C853A978-44D0-48ED-8170-A459CE2AA141

**Comment by brdunfield** [comment]
Will do going forward! Sorry about that

**Comment by zach-park** [comment]
No worries. Thank you!! :D

**Comment by brdunfield** [comment]
@zach-park Content has been updated. See screenshot below!
![Screen Shot 2022-05-17 at 12.42.19 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/c1c09968-0214-4661-bcad-e54ae54e481a)

**Comment by zach-park** [comment]
Thank you!!

**Comment by zach-park** [comment]
LGTM. Thank you!!
