### ISSUE TITLE
[FE] Display New Error Message when Attempt to Pre-Check-in from Midnight to 15 minutes after Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41138]
## User Story
As a Veteran, when I try to do pre-check-in on the day of appointment up until 15 minutes after my appointment, I want to see a message that more accurately tells me why I cannot do pre-check-in so that I will not be confused.

## User Workflow
- Given I
    - Get a Pre-check-in link after confirming an appointment
- When I
    - Click the link 
- Then 
    - If I clicked on the link from midnight on the day of the appointment to 15 minutes after the appointment, I see this message & sub-message
        - Message = "Sorry, pre-check-in is no longer available"
        - Sub-Message = "You can still check-in with your phone once you arrive for your appointment."
    - If I clicked on the link more than 15 minutes after the appointment time, I see this message
        - Message = "Sorry, we can't complete pre-check-in. Your appointment has already occurred."
        - Sub-Message = NONE
  
## Wireframes
- [Sketch](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/m1l0PA7) 
- NOTE: The following is a screenshot of the Sketch file at the time this ticket was created, if the screenshot differs from the Sketch file when this ticket is worked, please raise the issue with the team during stand up

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/288500f9-717a-4c73-8bc1-44edbe5107e1)

## Tasks
- [ ] [FE] Display a different message and sub-message depending on the time (see workflow)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
