### ISSUE TITLE
Review IE team's new tool and SD approach

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#41131]
## Issue Description
Consider IE team's  SD approach for their new tool

https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/38931
---
## Tasks
- [x] Review the Zenhub issue
- [x] Discuss how to respond as a team
- [x] Meet w/ IET to discuss

## Acceptance Criteria
- [x] Meeting held w/ IET  ([notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2194735207/Exploratory+session+w+IET))
