### ISSUE TITLE
[FE] Update / Create developer documentation

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41141]
## User Story
As a FE dev on the check-in experience, I want to have information that I need to run the app documented so that I can onboard more quickly or not need to remember obscure app commands if I have been on vacation

## Tasks
- [ ] Locate existing developer documentation
  - [ ] Determine whether to amend existing documentation or add new
- [ ] Document repos and app commands (and any other information) needed to run the application locally.
- [ ] Document test commands and how to filter to just our application
- [ ] Document local mock API UUIDs and what they do for local testing

## Acceptance Criteria
- [ ] FE-Developers agree all information is accounted for and easily accessible
- [ ] Prod validation:
  - [x] not necessary
