### ISSUE TITLE
Review incident commander documentation - Updates/Tasks 

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41148]
Incident commander document review Changes   based on [Incident Documents Review issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36810)

# Completed

- [X] Will we need to update slack channel names?  No, #platform-support-channel will be used.
- [X] What is the process to update points of contact?  - PageDuty
- [X] What happens if PagerDuty, Internet, or other tools fail?  -  Email/Text/Phone calls using the OnCall persons Number.
- [X] Is there backup phone contact information? - Yes in PagerDuty and main Support Number
- [X] Is the OnCall README accurate and up-to-date? PageDuty updated
- [X] Link fixed "Incident commanders should follow the Basic On Call Procedure" ... that document is deprecated
- [X] How do we get SRE team to receive IC emails or PagerDuty prompts?  Setup in PagerDuty
- [X] Is the Security Incident Response document up to date (SIR)?  - The Incident Commander works with Security and the EMASS VA Policy. 

# TODO
- [ ] Where is the ATO Incident Response Plan that's supposed to be linked from the SIR?  This is a work in process.  
- [ ] Are the contacts up to date in the team-sensitive Administrative README?
- [ ] Do Incident Response personnel need to have a PIV card?
- [ ] How do we clarify the handoff and assumption of responsibilities between oncall and incident commander?
- [ ] Who are VSP DEPO leads and where is that documented?
- [ ] Do we still post a message in #general?
- [ ] Are there other channels?
- [ ] How do we streamline broad notification in DSVA Slack?
- [ ] Is "vsp-leadership" still an active group?
- [ ] Where are the call center points of contact documented?
- [ ] Is the [HRCCMOHDSupervisors@va.gov](mailto:HRCCMOHDSupervisors@va.gov) email list still valid?
- [ ] What is the "Emergency Operating Procedures Incident Response Plan" and where is it documented?
- [ ] What is the "Incident Response Standard Operating Procedures - ATO" and where is it documented?

**Comment by rmtolmach** [comment]
There is likely some overlap between this ticket and the one I just completed:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/41153

As part of that ticket, I updated the following docs:
- https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook
- https://vfs.atlassian.net/wiki/spaces/PTST/pages/2442854463/Incident+Commander
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1066
