### ISSUE TITLE
Additional IAM permission to access AWS resources and workflows

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41140]
## Issue Description
Some additional AWS permissions are required for CIT team users to function effectively. Specifically we need:

- Permission to use SSM (AWS Systems Manager) to securely connect to nodes without SSH
- Permission to view EKS resources in AWS (read-only access required, mostly for informational purposes)

---
## Tasks
- [ ] Add policies to use SSM
- [ ] Add policies to view EKS resources in dev

## Acceptance Criteria
- [ ] CIT Team uses can use SSM
- [ ] CIT Team users can view EKS resources
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
Infra team wants to punt on granting permissions to EKS resources for the time being.
