### ISSUE TITLE
OCTO-DE review and stakeholder feedback for Decision Reviews R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41159]
## Issue Description
The content team reworked the Decision Reviews R&S article Choosing a decision review option to take the content out of a table. This was done in ticket #40464

This ticket is for Beth's review of the content team's work and to track any revisions the stakeholders have. We'll create a follow-up ticket for publishing when ready.

## Tasks
- [ ] Final review (Beth)
- [ ] Send to stakeholders (Beth)
- [ ] Incorporate stakeholder feedback (Beth/Aliyah/Laura)

## Acceptance Criteria
- [ ] Beth and stakeholders have approved content

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the Word doc for you to review:
[40464.-.Choosing.a.decision.review.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8709682/40464.-.Choosing.a.decision.review.docx)

**Comment by bethpottsVADEPO** [comment]
@RLHecht I'm attaching the Word doc the team created that now has my edits tracked. I'd like to be able to send stakeholders a preview link, so go ahead and create a ticket for the drupal work that's needed to get this content in the CMS.

@laurwill Thanks to you and the team for your thoughtful work on this. I like the approach in the 2nd approach you all had in the Word doc, but I kept my edits in approach 1 just because that's where I'd started editing before I noticed there were 2 versions in there. Let's see how it looks in drupal preview, and we can tweak further if we want.

**Comment by bethpottsVADEPO** [comment]
And here's the attachment... 

[https://app.zenhub.com/files/133843125/17f4c321-c0e5-4b7a-bdc6-1eb01e6c5506/download](https://app.zenhub.com/files/133843125/17f4c321-c0e5-4b7a-bdc6-1eb01e6c5506/download)

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht ! Just an update here --> I started to update in Drupal and will continue tomorrow. I added in a new rich text box with these changes and will remove the old one once I am done.

**Comment by aliyahblackmore** [comment]
Hi @laurwill the Drupal page was updated with Beth's changes and is ready for you to copy edit!

**Comment by bethpottsVADEPO** [comment]
@laurwill @megzehn I think you said this was already copyedited, but just making sure. Also, could you drop the preview link in the ticket here? Thanks!

**Comment by megzehn** [comment]
Yes here it is!  

http://preview-prod.vfs.va.gov/preview?nodeId=23290

Could you check to see if the text around the forms is OK? We didn't include information about where and how to send the forms, since that information is all on the child pages. (And the existing "[Choosing a decision review option article](https://www.va.gov/resources/choosing-a-decision-review-option/)" also does not include that information.) But let us know if we should include more in the newer version.

**Comment by bethpottsVADEPO** [comment]
@megzehn Glad you raised that! I agree that we should address this. Let's add jump links going to "How do I file a Supplemental Claim with new evidence?" / "How do I request a Higher-Level Review?" / "How do I request a Board Appeal?" in each H3 section of the first Q&A. Instead of "Learn more about Supplemental Claims" etc., change the label to: "Find out how to submit your application." For HLR, move that link up to immediately follow the PDF link.

Thanks, and let me know if you have questions!

**Comment by bethpottsVADEPO** [comment]
^^ @megzehn and @laurwill I edited the label above to:
Learn more about Supplemental Claims and how to submit your application

It may be too long. Let's see how it looks. Let me know if you have other thoughts.

**Comment by megzehn** [comment]
Hi @bethpottsVADEPO! I added the jump links directing people to "How do I file..." and "How do I request..." per your recommendation. 

Here's the [preview link for your final review](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start). Thank you for your help!

**Comment by bethpottsVADEPO** [comment]
Hi @megzehn I did a little editing. In the end, I think the change I'd recommended to "decision review" in the text links didn't work. It sort of made it sound too broad. I also changed the order of the links under the HLR section. And I've sent it off to stakeholders! You can take one more look to make sure I didn't introduce any typos with my edits. Thanks!
