### ISSUE TITLE
Hide `SubwayMap` on Introduction page for `pending` statuses

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41163]
## Background
The COE mockups call for the `SubwayMap` component to be hidden behind a link when the coe status is `pending` or `pending-upload`.

## Tasks
- [ ] Hide the `SubwayMap` when status is `pending` or `pending-upload`

## Acceptance Criteria
- [ ] `SubwayMap` is hidden when status is `pending` or `pending-upload`
- [ ] A PR is requested for merging

**Comment by saderagsdale** [comment]
@jacobworrell I see that this is assigned to Jerek. Since CoE is now in my team's wheelhouse, do you want to move this to squad 2?

**Comment by jerekshoe** [comment]
I'm mostly finished with this. I'm having issues with zenhub so I can't move tickets to in progress atm.
