### ISSUE TITLE
Twice-weekly deploy

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#41165]
# User story

As a Platform customer, I need to view up-to-date info on the Platform website so that I don't run into roadblocks when building my VFS app.

As a Platform team member, I need the Content team to regularly publish any/all changes to the Platform website so that I can trust that info about my Platform product/service is available to customers.

# Tasks

- Use SVP to publish on:
  - [x] 1st Thurs of spr
  - [x] 1st Tues of spr
  - [ ] 2nd Thurs of spr
  - [x] 2nd Tues of spr
  - We will not be reviewing for style guide compliance.  We will simply be pressing "publish"

# Acceptance criteria
- Platform website has been "deployed" four times

# Reference info
- Platform website deployment instructions https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+website+deployment+instructions

**Comment by lianilychee** [comment]
5/12 Thurs:
- Samara and Gretchen run thru
- Liani send recording

**Comment by lianilychee** [comment]
5/13 Fri:
- deploy went well!
- today: our instructions to ourselves were a bit unclear, so gonna go thru and comment anything else that was unclear (we were doing and commenting at once, so might have missed some things)

**Comment by amygoldman** [comment]
5/16:

- Samara is taking care of it this week
- Question: can someone fill in for extra 2 weeks in June since Samara did 2 weeks this month?
 - she definitely can't do week of 6/23 because graduation, yay!

**Comment by amygoldman** [comment]
5/20

- Samara is doing this today
