### ISSUE TITLE
Review Console

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#41169]
# User story

As a Platform customer (aka VFS team member) - the Console needs to be clear, easy to understand, and easily navigable - so that I can autonomously use it to build my VFS app.

# Tasks

- Review:
  - [x] About page: https://platform-console-ui-dev.vfs.va.gov/about
  - [x] Support page: https://platform-console-ui-dev.vfs.va.gov/support
  - [x] Platform resources page: https://platform-console-ui-dev.vfs.va.gov/platform-resources
  - [x] Home page (logged in): https://platform-console-ui-dev.vfs.va.gov/
  - [x] Home page (not logged in): https://platform-console-ui-dev.vfs.va.gov/

- [ ] ~Determine what happened to the weekly teams' sync -- _they're biweekly_~
- [ ] ~Divvy who is contributing to what list~
- [ ] ~Compile list of terms, to be shared at 5/19 teams' sync~
- [ ] ~Compile list of microcopy, to be shared at 5/26 teams' sync~

# Acceptance criteria

- TBD
- ~Share complete lists of terms and microcopy~

# Reference info
- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2191523859/Next+steps+Lists+for+Console+team

**Comment by lianilychee** [comment]
5/12 Thurs:
- today: 
  - terms list almost ready to share, spending today adding last thoughts
  - watch demo - Thomas Ferrin "anatomy of catalog"

**Comment by amygoldman** [comment]
Here are pages for revising/editing each of the 5 docs the Console team asked us to review:
- [About](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2193260715/About)
- [Support](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2193621107/Support)
- [Platform resources](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2193359027/Platform+resources)
- [Home page (logged in)](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2191786327/Home+page+logged+in)
- [Home page (not logged in)](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2193227915/Home+page+not+logged+in)

**Comment by lianilychee** [comment]
5/13 Fri:
-

**Comment by amygoldman** [comment]
[Lee requested](https://dsva.slack.com/archives/C02SLSSGSBX/p1652464024915129): 

> If you could post here + tag myself, [@Thomas](https://dsva.slack.com/team/U02B3A7KJFK) + [@Eric Murphy](https://dsva.slack.com/team/U031AUJR35Z) designer when it's available, we can review asynchronously. Any larger discussions can happen the week after in our biweekly meeting.

**Comment by amygoldman** [comment]
5/18

- Polishing feedback today to share with Console UI team over Slack tomorrow

**Comment by amygoldman** [comment]
5/20

- [Shared feedback with the Console team](https://dsva.slack.com/archives/C02SLSSGSBX/p1653064957616809)
- Monday: talk about our next steps and what we want to discuss with the Console team during our sync
