### ISSUE TITLE
[FE] Updates for Profile

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4116]
## User Story: 

As a front end engineer, I need implement the front end changes that resulted from copy updates so that I can get this merged into production.. 

## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [ ] Implement copy update changes that were provided by Peggy. 
- [ ] Validate that the intended changes are working as intended. 

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] Tested the changes are active on staging and work as intended. 

## Copy Changes for the profile

**Comment by Justin-Pickett** [comment]
Work already closed out for this ticket. Closing this ticket.
