### ISSUE TITLE
PM | Profile | Direct Deposit - Show Consistently | Launch Readiness

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41173]
### Background

FE work in #40722 

We are launching an update where we will always show the direct deposit section, even to people who do not receive payments. Since this work did not go through the collab cycle, here is how we plan to test it to make sure it's ready for launch:

### Tasks

- [x] Test work in staging
- [x] Once work is validated in staging, conduct UAT with Sharon and Samara by using FF to roll-out to the 2 prod accounts
- [x] As part of UAT, ask ~2 real veterans on the larger team to make sure the direct deposit tool is working as expected for them
- [x] Launch to 25% of users. Observe analytics for a couple days just to make sure we don't see any weird increase in errors.
- [x] Launch to 50%. Observe analytics for a couple days.
- [x] Launch to 100%.

**Comment by SKasimow** [comment]
@Samara-Strauss - that's great! thanks so much for doing this 🥇
