### ISSUE TITLE
[Design] MyHealth - Design inbox list of search results for desktop and mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41179]
## Issue Description
As a secure messaging user, I need a list of message search results on desktop and mobile.

---
## Tasks
- [x] Design search results list for desktop
- [x] Design search results list for mobile
- [x] Drop link to prototypes into a comment on this ticket
- [x] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for a design review with the remaining secure messaging screens.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Desktop: search messages ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/JnlLQvk)

[Mobile: Search messages ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/zxvVwZM)


[Prototype for desktop designs ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ELmVpjd/play)

[Prototype for mobile designs ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Jnlmgje/play)
