### ISSUE TITLE
[Research] MyHealth - Analyze MyHealtheVet on VA.gov mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41187]
## Issue Description
As a researcher, I need to have a solid understanding of how MyHealtheVet works on Mobile so that I can work with the design team on the new secure messaging mobile designs.

---
## Tasks
- [ ] Research MyHealtheVet on mobile
- [ ] Document key features and functionality
- [ ] Store research documentation with product docs on GitHub
- [ ] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Researchers will have a solid understanding of how MyHealtheVet works on mobile
- [ ] Findings are documented in the product folder
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
