### ISSUE TITLE
Update breadcrumbs and title tag for View or change dependents page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41185]
## Issue Description
We need to update the breadcrumbs and title tag for the [View or change your dependents on your VA disability benefits](https://www.va.gov/view-change-dependents) page so that they match the H1 and are consistent with VA.gov standards for IA. 

New breadcrumb: View or change dependents on your VA disability benefits
New title tag: View Or Change Dependents On Your VA Disability Benefits | Veterans Affairs

We don't need to change the H1 or url. 

**Note:** Changes to the breadcrumbs can only be made right before publishing a page so it's best to have Megan screen share with whoever is changing these so that she can confirm the updates are correct.

## Tasks
- [x] Update title tag (Aliyah)
- [x] Update breadcrumbs (Aliyah)
- [x] Confirm changes are correct and publish page (Megan)

## Acceptance Criteria
- [x] Breadcrumbs and title tag on live page match the H1

**Comment by RLHecht** [comment]
@aliyahblackmore @laurwill We can talk about how to do this work since updating breadcrumbs is a little different from other edits in Drupal.

**Comment by aliyahblackmore** [comment]
Hi @mnorthuis! The new meta title tag is longer than the character limit. Could you provide us with a new title tag that that fits the character limit? Right now it's over by 6 characters.  Also noting that we will wait for this change before moving forward with the breadcrumb update (cc: @RLHecht)

**Comment by RLHecht** [comment]
@mnorthuis Yeah, Drupal isn't letting us add more than View Or Change Dependents On Your VA Disability Ben | Veterans Affairs. It cuts off the last word. I don't think that was always the case.

**Comment by RLHecht** [comment]
@cmaeng Please see Mikki's comment above. Is it possible to remove the character limit for meta title tags in Drupal so we can use the H1?

**Comment by cmaeng** [comment]
@RLHecht we can take a look at this and get back to you. how pressing do you need a response by? Also, what would your preferred character limit be?

@kevwalsh @wesrowe @davidconlon fyi, decision needed on whether or not to bump up the character limit for the "Meta title tag" field on Benefits Detail pages. e.g. [here](https://prod.cms.va.gov/view-change-dependents). It looks like Sitewide Content has update that specific one for now.

![image](https://user-images.githubusercontent.com/60702623/170132777-09c224ee-1a30-433f-ab91-329cb91c2a19.png)

**Comment by RLHecht** [comment]
@cmaeng Is it possible to drop the limit altogether so the H1 can always match the title tag?

**Comment by mnorthuis** [comment]
For background - By standard, the breadcrumb segment and the title tags should match the H1. This ensures consistency for accessibility purposes and ideally from a maintenance standpoint as well.   The character limit enforced is a best practice based on what search engines may show for the title tag in search results, however search engines do vary and change.  Our best practice will continue to be max of 72 characters to optimize for search, however, there are times when we may need to go over that max.

**Comment by kevwalsh** [comment]
If the goal is to get meta titles to match the h1, there's no point in changing the character limit, we should just delete that editable field altogether in Drupal, and get the FE to just use the h1 (The page title, not Meta title). 

We are already doing that for most other content types. 

Only certain content types have an extra, editable meta title field because those are the content types that Jen L wanted to ensure that the titles don't get trimmed in search results. I believe best practices changed from 70 to 60 or 65, not long after 70 was chosen by Jen.

**Comment by kevwalsh** [comment]
A few more details: 

* Only Benefits Detail Page and Benefits Hub Landing Pages have an editor-overridable, 70 character limit meta title page. This is specified in the [Content Style guide](https://design.va.gov/content-style-guide/seo#title-tags).

* All other content types have meta titles built with `<h1> | Veterans Affairs`, or `<h1> | Health care system | Veterans Affairs</h1>`

<details><summary>meta title patterns by content type</summary>

<img width="1136" alt="Cursor_and_VA_gov_CMS_content_model_documentation__Bundles_-_Airtable" src="https://user-images.githubusercontent.com/643678/170325872-3a7a3515-612f-421d-a66b-c3c351d0becf.png">


</details>

**Comment by kevwalsh** [comment]
Thinking about this more, maybe we just make the 70 characters a soft limit for Benefits Hub Detail and landing page (your original ask). The system will warn editors if they are going over, but won't prevent them.

**Comment by kevwalsh** [comment]
@mnorthuis Turns out it's not as low effort as i first thought. There's some old tech debt with field. 

We can either
1. Continue down this "soft limit" path for the overrideable Meta title field (needs a DB update to drupal that's non-trivial, and we may not have backend dev capacity for immediately)
2. Remove the custom meta title field altogether and just map h1 to the meta title.  

There's a possible follow-up to the second option, which is to allow content admins (basically, the Sitewide Content team) to override ANY meta tag (or subset of met tags) for ANY page managed in Drupal.  It's not trivial and would require some minor training.

**Comment by DanielleThierryUSDSVA** [comment]
> Remove the custom meta title field altogether and just map h1 to the meta title.

I this we should definitely consider this. 

The content team manages all benefit hub pages and will craft H1s based on our best practice guidelines. And the original guidance that led to the character limit and the initial caps is definitely older and as you noted, SEO will continue to evolve. We can continue to evolve our best practices for H1 with meta titles also in mind.

**Comment by DanielleThierryUSDSVA** [comment]
Yes to managing tech debt and reducing edge cases!

**Comment by RLHecht** [comment]
@kevwalsh Should this be fixed now because the live site is still showing the old breadcrumbs?

**Comment by kevwalsh** [comment]
Breadcrumbs are set by the this menu link title. By default these match the h1, but at some point this was overridden by a content admin.  Only content admins have that ability. 

<img width="1666" alt="Edit_Benefits_Detail_Page_View_or_change_dependents_on_your_VA_disability_benefits___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/171633755-b412c908-73af-4039-a751-6a304280fe3e.png">
 
We diddn't do any engineering in #9242 to touch breadcrumb behavior. 

Here's a screenshot showing that the `<title>` was updated to match the h1. This went live on Tuesday.

<img width="1391" alt="View_Or_Change_Dependents_On_Your_VA_Disability_Benefits___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/171634573-3a3d919c-927c-4b6d-883b-c04e7defe99f.png">

**Comment by kevwalsh** [comment]
@mnorthuis by default they do, but content admins were given the right to override the menu item text, which drives the breadcrumb. It's just a content change to go back to using the h1 in the menu item text and breadcrumb.

**Comment by aliyahblackmore** [comment]
Hey @megzehn!  The title tag (aka "Meta description") and Breadcrumb (aka the "Menu Link Title") have both be updated with the above text! This is ready for you to review and publish.

**Comment by megzehn** [comment]
Reviewed and published!

**Comment by megzehn** [comment]
Moving over to validate, @RLHecht - thanks!

**Comment by RLHecht** [comment]
These changes are now live. Closing ticket.
