### ISSUE TITLE
MyHealth - Design list of sent messages for desktop and mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41180]
## Issue Description
As a secure messaging user, I need a list of sent secure messages on desktop and mobile.

---
## Tasks
- [ ] Design sent message list for desktop
- [ ] Design sent message list for mobile
- [ ] Drop link to prototypes into a comment on this ticket
- [ ] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for a design review with the remaining secure messaging screens.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Desktop sent messages](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/zxv4eQM)

[Mobile sent messages ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ag27xKq)

[Prototype for desktop designs ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ELmVpjd/play)

[Prototype for mobile designs ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Jnlmgje/play)
