### ISSUE TITLE
[Research] My Health - Review legacy secure messaging

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41186]
## Issue Description
As a researcher, I need to familiarize myself with legacy secure messaging so that I am prepared to coordinate with the designers on their prototypes.

---
## Tasks
- [ ] Review and document key design elements and features of legacy design messaging for desktop and mobile
- [ ] Store review documentation in the product folder
- [ ] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Researchers will have a good understanding of how the legacy secure messaging system looks and functions.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
