### ISSUE TITLE
[Design] MyHealth - Design messages landing page (inbox) for desktop and mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41184]
## Issue Description
As a secure messaging user, I need a message landing page that displays my secure messages on desktop and mobile.

---
## Tasks
- [ ] Design inbox message list for desktop
- [ ] Design Inbox message list for mobile
- [ ] Drop link to prototypes into a comment on this ticket
- [ ] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for a design review with the remaining secure messaging screens.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
@MarciMcGuire Please reference [ticket 41178 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41178)

I feel like this ticket is duplicative
