### ISSUE TITLE
Walkthrough Findings - Design Intent

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#41209]
## User Story
As a VFS team member and Governance team member, I want clear and up to date documentation and guidance so that I can easily perform my role in the Collaboration Cycle.

- Intended Audience: VFS Teams and Governance Team
- Desired Outcome: Updated documentation and templates
- Due Date: 

## Description
Tasks listed below are from our [Core CC Walkthrough session notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2183757962/Notes+-+Core+Collaboration+Cycle+ticket+Walk-through)

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Tasks
- [ ] [Platform Website: Design Intent - Request Section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167767138/Cheryl+-+Copy+of+Design+intent#Request)
  - [ ] Add sub bullet linking to [ZenHub Board](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board?repos=133843125)
- [ ] [Design Intent Ticket](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
  - [ ] VFS Actions - "Have Matt Dingee review your proposed designs" change to "Has Matthew Dingee reviewed your proposed designs?"
  - [ ] Fix link in Design artifacts - "Whiteboard sketch or other lo-fi prototypes or wireframes"
  - [ ] Remove practice area labels to match Platform Website
- [ ] [Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274402/Allison+Copy+of+Design+Intent+-+Moderator+Responsibilities)
  - [ ] Schedule
    - [ ] Step 5
      - [ ] Remove Zoom url line
      - [ ] Add meeting Request date
      - [ ] Keep meeting date/time, recording, and password
    - [ ] Step 6 - Replace "comment on the GitHub ticket" with "Comment on the slack post where we are tagged"
  - [ ] Post Meeting
    - [ ] Step 2 - Remove step entirely
    - [ ] Remove GitHub link bullet
- [ ] Feedback Template
  - [ ] Rename so that touchpoint is first then practice area
- [ ] [How to provide Feedback documentation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241701)
  - [ ] Step 3
    - [ ] If no feedback, change guidance - do not comment
      - [ ] Change checkboxes for practice area reviewers in After Meeting > Platform actions to indicate feedback is completed by changing text to "Design feedback completed" or "Design review completed"
    - [ ] If feedback, 

  - [ ] Update links to feedback templates
  - [ ] Discuss adding one click templates that Jim created
- [ ] ZenHub Board
  - [ ] Add Feedback pipeline
    - [ ] Create instructions around this column
    - [ ] Add instructions for reviewers to check that feedback tickets to ensure that they are closed - Need to check this with Clayton
  - [ ] Update pipeline names to match user flow created

## Acceptance Criteria
- [ ] Confluence: _Page Name_ has been updated
- [ ] Confluence: _Page Name_ has been created
- [ ] GitHub Template: _Page Name_ has been created
- [ ] GitHub Template: _Page Name_ has been updated
- [ ] Platform Website: _Page Name_ has been updated
- [ ] Platform Website: _Page Name_ has been created
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@chaseakirby , I am looking at the following tasks:
Artifact Section
 Opportunity Statement: Add directions detailing who is responsible for attaching artifacts
 Opportunity Statement: Add specific directions of how/where to attach artifacts with short descriptors of needed artifacts

I thought we decided that we would just make the artifacts section match what we currently have since there is another ticket to explore how and what artifacts we currently have?

**Comment by allison0034** [comment]
@chaseakirby wont this go to the current template?

If feedback,
 Update links to feedback templates

**Comment by allison0034** [comment]
@seanasewell can you please do a peer review for the documents below? Keep in mind I cannot Update links to feedback templates until the PR is merged.

[Platform Website: Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167767138/Cheryl+-+Copy+of+Design+intent)
[Design Intent Ticket](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
[Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274402/Allison+Copy+of+Design+Intent+-+Moderator+Responsibilities)
[How to provide Feedback documentation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241701)
[Original Design Intent Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/design-intent-collaboration.md)

**Comment by allison0034** [comment]
@claytonzook see above please and thank you!

**Comment by claytonzook** [comment]
@allison0034 I did see a couple minor things I had questions with:

- DI ticket - Fix link in Design artifacts - "Whiteboard sketch or other lo-fi prototypes or wireframes"
I don't see any link on the core ticket at that spot now.

- [How to provide Feedback documentation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241701) - If you have feedback - the "Collaboration Cycle Feedback" Github ticket link is still practice area then touchpoint, but should be in the reverse order.

**Comment by allison0034** [comment]
@claytonzook thank you!

- There are no links on platform website so since we agreed to just keep what we currently have, I removed all links
- Not sure I understand... here is what I have:

If you have feedback

- Create a new “Collaboration Cycle Feedback” GitHub  ticket and link to the Collaboration Cycle ticket.
- Open the Collaboration Cycle ticket. 
- Check the box that says , “[name of your practice area] has completed the review.”

**Comment by allison0034** [comment]
I did add an extra step...

If you have feedback

- Create a new “Collaboration Cycle Feedback” GitHub  ticket and link to the Collaboration Cycle ticket.

- Add your feedback.

- Open the Collaboration Cycle ticket. 

- Check the box that says , “[name of your practice area] has completed the review.”

**Comment by claytonzook** [comment]
That "add your feedback step" might need to be 3rd, after you open the ticket

**Comment by allison0034** [comment]
@claytonzook I am not changing that template, I believe Jim was : )

You would want to create a new feedback ticket, then add you feedback, then go to the core ticket and check your box.

**Comment by shiragoodman** [comment]
[feedback ticket PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/41478)

**Comment by shiragoodman** [comment]
all unchecked items have been added as tickets to initiative #42580
