### ISSUE TITLE
Beats Playbook for Ansible-based AMI builds

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#41217]
## Description
Create Ansible playbook for installing beats agents on Ansible-based AMI builds

---
## Tasks
- [ ] Create Playbook for Installing Beats on Amazon Linux 1
- [ ] Create Playbook for Installing Beats on Amazon Linux 2
- [ ] Create Playbook for Installing Beats on Ubuntu

## Acceptance Criteria 
- [ ] Ansible-based AMI builds install and start the beats services
