### ISSUE TITLE
Fill in "contract_end_date" column on product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41219]
## Issue Description
We need to fill in the end date for contracts as they relate to products on our product list. As we currently do not know where this information will come from, some research will need to be done first to determine what our source is. Once a reliable source is determined, we will need to fill this in using the same valid date format as our Launch Date column. 

---
## Tasks
- [ ] Research where to get the contract end dates reliably.
- [ ] Grab the latest product directory from our "product-directory" GitHub repository
- [ ] Fill in the Contract End Date column on the product list using a valid date format.
- [ ] Open a PR to merge changes to the product directory.

## Acceptance Criteria
- [ ] Our Contract End Date column is filled out on the product list.
- [ ] Any non-applicable rows are left blank.
---

**Comment by CBonade** [comment]
Reached out to Ray Wang about this but no response yet. By slack's activity indicator it appears he may be out today.

**Comment by JoeTice** [comment]
This task is being deprioritized, as it is not related to one of the priority use cases

**Comment by CBonade** [comment]
This work was completed.
