### ISSUE TITLE
[discovery] 526ez | MVI add failure in 526

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41215]
## Description

There are a lot of [`mvi_add_failed` events showing up in our Sentry log for Form 526](http://sentry.vfs.va.gov/organizations/vsp/issues/176/?project=4&query=is%3Aunresolved). A rough count reveals about 100 events per day, with lots of duplicates (the Veteran is probably reloading the page). We need to investigate these events and determine if we can do something to reduce this number of daily events.

### Background

When a Veteran starts form 526, the front-end checks for an "add-person" value appears in their profile services. If it appears, it means that the Veteran has an EDIPI and SSN in the system, but are not yet added to the MPI database. In this case, we need to add them before starting the form.

The front-end calls the `/mvi_users/21-0966` endpoint to add them. If successful, the Veteran can then proceed with filling out form 526. If it fails, a message is shown to the Veteran indicating that we are missing some information and that that need to call the help line.

## Tasks

- [ ] Investigate reason for `mvi_add_failed` calls and if there is something we can do
- [ ] Discuss with stakeholders
- [ ] Document findings
- [ ] Implement fix, if possible

## Definition of done

- [ ] All tasks complete

**Comment by michelpmcdonald** [comment]
Controller for route v0/mvi_users/21-0966
https://github.com/department-of-veterans-affairs/vets-api/blob/6e0347e29508b77aff3adedb0d931a31a50916e8/app/controllers/v0/mpi_users_controller.rb#L8

Loki query({app="vets-api-server"} |= "V0::MPIUsersController") shows that some calls coming back with a status of "Unprocessable Entity":

`2022-05-11 12:12:19	
16:12:19 web.1       | {"host":"4c2dcf6d0e33","application":"vets-api-server","environment":"production","timestamp":"2022-05-11T16:12:18.996578Z","level":"info","level_index":2,"pid":79,"thread":"puma srv tp 004","duration_ms":42.43487899657339,"duration":"42.4ms","named_tags":{"request_id":"5ef5a3d1-7e60-46c2-8324-c9bde8474436","remote_ip":"2600:387:c:6f14::3","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1","ref":"e4727f551db8ebe23d0d9b2d376d7938b9ac6f61","csrf_token":"jM65Ts/zSP53InqfZKTipDWo+GIBdP1lG+8cpQcbIAq0J8FDPSIREQu3i+caVgEAVic3zCenY25yFJOaU60T0Q=="},"name":"V0::MPIUsersController","message":"Completed #submit","payload":{"controller":"V0::MPIUsersController","action":"submit","params":{"id":"21-0966"},"format":"JSON","method":"POST","path":"/v0/mvi_users/21-0966","status":422,"view_runtime":0.43,"db_runtime":0.0,"session":"88308bf15515d530e0ecf","user_uuid":"860c25a8d9994d5f819d4493cab47f5a","allocations":30037,"status_message":"Unprocessable Entity"}}`

**Comment by saderagsdale** [comment]
Is this discovery work in progress? @Mottie @michelpmcdonald
