### ISSUE TITLE
[PM] My VA Redirect: Initiative planning/scoping

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#41212]
## Background
We need to do some initial prep work/project scoping around the My VA redirect initiative. 

## Tasks
- [x] Draft project outline
- [x] Investigate Medallia: we'll need weekly reports once rolled out for feedback
- [x] Determine preliminary launch date 
- [x] Coordinate with necessary teams (figure out which teams we'll need to work with)

**Comment by ajakabcin** [comment]
Initiative brief drafted [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/my-va-redirect-initiative-brief.md#my-va-redirect-initiative-brief)

**Comment by ajakabcin** [comment]
Initial questions have been answered/documented in initiative brief.

**Comment by ajakabcin** [comment]
Re Medallia - reached out to Jason Woodman (PM for contact center manages medallia) and confirmed having medallia on My VA post redirect would not be an issue. We'll submit [this request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+Kimberley2019&labels=medallia%2C+VSP-contact-center&template=analytics-survey-request-template.md&title=User+Survey+Request+for+%5BTeam%5D) as part of our development process.

At this point I think we're looking at the end of June first week in July for this given some team absences and getting the collab cycle started.
