### ISSUE TITLE
Walkthrough Findings - Midpoint Review

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#41211]
## User Story
_"As a VFS team member and Governance team member, I want clear and up to date documentation and guidance so that I can easily perform my role in the Collaboration Cycle.

- Intended Audience: VFS Team and Governance Team
- Desired Outcome: Updated documentation and templates
- Due Date: 

## Description
Tasks listed below are from our [Core CC Walkthrough session notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2183757962/Notes+-+Core+Collaboration+Cycle+ticket+Walk-through)
Remaining open Opportunity statements are also noted. 
[Research Findings spreadsheet (Pre Launch Improvements tab)](https://docs.google.com/spreadsheets/d/1_EGjrHtr3gEam72K4zEoFMdkQLBIvIjQ_lmes-RgWLw/edit#gid=1309674612)

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Artifacts Needing Updates
[Cheryl - Copy of Midpoint review ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167767151)
[Core ticket > MPR section](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
[Allison - Copy of Midpoint Review - Moderator Responsibilities ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274420)
[Jim-How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274376/Jim-How+to+provide+feedback+for+a+Midpoint+Review)
[Original Midpoint Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/midpoint-review.md)

## Tasks
- [x] [Cheryl - Copy of Midpoint review ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167767151)
    - Opportunity Statement: Add documentation detailing needed information before Design Intent (May need to be determined)
    - [x] Request section - ensure consistency with verbiage to the DI
    - [x] Artifacts section
      - [x] Ensure the Midpoint Review page matches GitHub artifacts sections (GitHub ticket source of truth)
      - Opportunity Statement: Add directions detailing who is responsible for attaching artifacts
      - Opportunity Statement: Add specific directions of how/where to attach artifacts with short descriptors of needed artifacts

  - [x] FW: Moderator Script: Add "Welcome to Midpoint Review..." same as Staging.
  - [x] FW: Moderator Script: Add Research to "ensure it meets design..."
  - [x] FW: Request: Ensure formatting matches DI
  - [x] FW: Match Platform Website artifacts to current ticket artifacts formatting

- [x] [Core ticket > MPR section](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
    - [x] Opportunity Statement: Link to Platform Website detailing needed information and updated artifact guidance    
    - [x] Make artifacts section match current Midpoint ticket
    - [x] fix how the IA Github ticket links, “g' is outside of the link
    - [x] Remove zoom url line
    - [x] Place password under recording link
    - [x] Remove platform action "update point tracker" in Midpoint Review section of ticket
   - [x] Modify After Meeting > Platform Actions to match DI

  - [x] FW: VFS Actions: Bold "at least two days before"
  - [x] FW: Remove "Platform guidance on Midpoint Review artifacts"
  - [ ] Post Launch: FW: Look into adding "Platform guidance on Midpoint Review artifacts" to all touchpoint sections
  - [x] FW: Platform Actions: Should match Design Intent section. "Follow Midpoint Review Moderator"
  - [x] FW: Platform Actions: Remove link in "if you have midpoint review feedback..."
  - [x] FW: Platform Actions: Add Research to "practice area has completed review"
  - [x] FW: Platform Actions: Zoom Recording; Recording - Change name of "Recording" to "Recording URL:" (or whatever is decided for DI)
  - [x] FW: Midpoint Review - Platform Actions: Add Meeting date/time (same as DI has)

- [x] [Allison - Copy of Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274420)
  - [x] Scheduling: Sync
    - [x] FW: Step 5 - update to include scheduled date/time made on Calendly (Walkthrough & Opportunity Statement findings)
    - [x] Step 6 -  comment on Slack request NOT GH ticket
  - [x] Scheduling: Async
    - [x] FW:Step 4 - update for scheduled date/time (same as in the sync Step 5)
    - [x] Step 5 - comment on Slack request NOT GH ticket
    - [x] Step 7 - delete all
  - [x] Post Meeting or Review
    - [x] Step 1 - Is no feedback - not commenting on ticket, but confirming that each practice area has checked the appropriate box to indicate their review is completed
    - [x] Step 2 - delete in full
    - [x] Step 34 - rename to step 4
  - [x] Post meeting 
    - [x] step 1 - make match with DI
    - [x] step 2 - fully remove
    - [x] Add to make sure ticket is updated to auto open at MPR and that code is removed for DI section

  - [x] FW: Pre-scheduling: Step 1: Change "template" to "Collaboration Cycle Request".
  - [x] FW: Pre-scheduling: Step 1: Add "Verify Midpoint Review section of Collaboration Cycle Request ticket"
  - [x] FW: Schedule: Step 5: Add "Request"
  - [x] FW: Schedule: Step 5: Add "in the Collaboration Cycle Reviews board"
  - [x] FW: Schedule: Step 7: Change to "#platform-collaboration-cycle
  - [x] FW: Schedule: Step 7: Add Feature/Initiative to "Midpoint Review - Team Name - Product Name"
  - [x] FW: Async Review: Step 2 Add Request to Collaboration Cycle ticket
  - [x] FW: All instances of "Collaboration Cycle ticket" to "Collaboration Cycle Request ticket"
  - [x] FW: Sync and Async steps should be consistent where overlap
  - [x] FW: Async: Step 4: Add "in the Collaboration Cycle Reviews board"
  - [x] FW: During Sync Meeting: Step 2: Remove second team
  - [x] FW: During Sync Meeting: Step 4: Verify script against Midpoint Review touchpoint page (should include welcome and research)
  - [x] FW: During Sync Meeting: Step 5: Remove "Josh and/or Angela may provide accessibility feedback if VSA team."
  - [x] FW: Post Meeting: Step 3: Capital S (See comment)
  - [x] FW: Post Meeting: Step 3: Should be Midpoint Review (removing open) and Staging Review (adding open)
  - [x] FW: Post Meeting: Step 3: Change "Platform Governance team workspace" "in the Collaboration Cycle Reviews board"
  - [x] FW: Moderator Script: Add "Welcome to Midpoint Review..."

- [x] [Jim-How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274376/Jim-How+to+provide+feedback+for+a+Midpoint+Review)
  - [x] Step 2 - last bullet - remove the “as”
  - [x] Step 3
    - [x] first sentence - add period 
    - [x] If you don't have feedback - should match wording from DI
    - [x] If have feedback - add links that Jim made (also make sure touchpoint is listed first, then practice area)
    - [ ] Research feedback - fold in with other practice areas (if card on research repo, then feedback goes there, but a feedback ticket will still be made pointing team to research repo ticket)
  - [x] Step 6 - extra space in this paragraph

  - [x] FW: Step 1: Change "click on the Midpoint Review GitHub link" to "open Collaboration cycle request ticket and go to the Midpoint Review section"
  - [ ] Post Launch: FW: Better communication methods
  - [x] FW: After the meeting or asynchronous review: remove section, no meeting for async meeting
  - [x] FW: Update readymade practice area feedback templates due to link change
  - [x] FW: All instances: Change "vsp-collaboration-cycle" to "platform-collaboration-cycle"
  - [x] FW: Step 5: Change "If you are unable to provide feedback by that time, comment on the Midpoint Review epic ticket and tag the PM." to "If you are unable to provide feedback by that time, be sure to communicate that to the PM."
  - [x] FW: Step 6: Change "ticket" to "feedback ticket"

- [x] [Original Midpoint Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/midpoint-review.md)
  - [x] "### NOTE:
**This template is being deprecated**. If your kickoff meeting took place after [DATE TK], You should use the new template [Link TK] instead. If you are unsure if this applies to you, please reach out to the Governance Team on the **#vfs-platform-support** Slack channel."
      - 5/18 - Changed slack channel to #vfs-platform-support - Chase

## Acceptance Criteria
- [x] [Cheryl - Copy of Midpoint review ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167767151) has been updated
- [ ] [Core ticket > MPR section](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) has been updated
- [x] [Allison - Copy of Midpoint Review - Moderator Responsibilities ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274420) has been updated
- [ ] [Jim-How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274376/Jim-How+to+provide+feedback+for+a+Midpoint+Review) has been updated
- [ ] [Original Midpoint Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/midpoint-review.md) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@jimuhh @CherylEvans Hey Jim and Cheryl! I reviewed the operational docs and they look fine to me! I made a minor update to the Midpoint Review code block in the Kickoff to align to the soon-to-be deprecated ticket and Platform Website page but it should be good to move out of drafts now!

**Comment by CherylEvans** [comment]
Thank you Chase!!  I appreciate all of your continued support and
assistance!!
Cheryl

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by shiragoodman** [comment]
all unchecked items have been added as tickets in initiative #42580
