### ISSUE TITLE
Debug connection to VBS prod endpoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#41214]
## Issue Description
Receiving general error when using new VA network VBS endpoint, working to reproduce in staging environment

http://sentry.vfs.va.gov/organizations/vsp/issues/52655/?end=2022-05-11T13%3A32%3A40&environment=production&project=3&query=is%3Aunresolved+controller_name%3Amedical_copays&start=2022-02-10T12%3A32%3A40&utc=true

---
## Tasks
- [ ] Reproduce bug and find resolution

## Acceptance Criteria
- [ ] Stable deploy in production
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
