### ISSUE TITLE
Fill out the "octo_crew_lead" column on the product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41224]
## Issue Description
We need to fill in the "octo_crew_lead" column on the product list. We have a list of OCTO Crews here: <insert link here when we find it> but we do not have the leads associated with those crews. Once we have those names, we should be able to associate most products with a crew lead.

---
## Tasks
- [ ] Track down the names of the lead of each OCTO Crew.
- [ ] Grab the latest product directory from our "product-directory" GitHub repository
- [ ] Add the appropriate crew lead to each row in the "octo_crew_lead" column.
- [ ] Open a PR to merge changes to the product directory. 

## Acceptance Criteria
- [x] Applicable entries are filled in for the "octo_crew_lead" column.
- [x] Any other entries with no value are left blank.
---

**Comment by CBonade** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1642111298247/504cfa1e56d8b2f8a8802d5fce31ca6385cb403f?sender=laceyhigley6142

**Comment by CBonade** [comment]
Filled out to the extent we can with the information we have. The crews are on a team-basis as opposed to products, so right out of the gate we're limited by the team associations that we know of. Within that set, the health crew does not have a designated crew lead in the doc we were given so I was only able to account for the other 4.

**Comment by pjhill** [comment]
Donezo -- https://github.com/department-of-veterans-affairs/product-directory/pull/46
