### ISSUE TITLE
[Epic] My VA Redirect

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#41223]
## Background
This phase of work is centered around making My VA the logged in homepage for Veterans. We are not intending to eliminate the existing logged in homepage with this work, but rather redirect Veterans to My VA once they are logged in while still having the ability to visit the existing logged in home page.

Project Outline: [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-redirect)

## Collab Cycle - #42582 
- [x] Kickoff 
- [x] Sitewide Content and IA Intake Request
- [x] Contact Center Review
- [x] Staging Review
- [x] Privacy, Security, Infrastructure Readiness Review

**Comment by ajakabcin** [comment]
@Samara-Strauss I think we're good to close out this epic - all work is complete 🎉  (let me know if you would like to keep it open though)
