### ISSUE TITLE
Change instances of Direct Upload to QuickSubmit and update url on all VA.gov pages with mentions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41222]
## Issue Description
Stakeholder Melissa Fiedler reached out to say that on June 30, 2022, VA is launching QuickSubmit, which is the next generation of Direct Upload. We can update the link before June 30 if need be.

The url will be changing to: https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit

We need to search VA.gov for anywhere we link to the old url of https://eauth.va.gov/accessva/?cspSelectFor=dmhs as well as where we mention Direct Upload.

We should put a list in this ticket to ID where we are making these changes so we can validate them once the pages are live.

## Tasks
- [x] Search VA.gov for Direct Upload and Direct Upload url (Aliyah)
- [ ] Update link text and urls on pages found in search (Aliyah)
- [x] [Upload evidence to support your disability claim page](https://www.va.gov/disability/upload-supporting-evidence/)
- [x] [VA Survivors Pension page](https://www.va.gov/pension/survivors-pension/)
- [x] [Veterans headstones, markers, and medallions page](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/)
- [x] [Burial in a private cemetery page](https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/)
- [x] [Presidential memorial certificates page](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/)
- [x] [Survivor and Dependent compensation](https://www.va.gov/disability/dependency-indemnity-compensation/)
- [x] Use pre-publishing checklist (Megan)
- [x] Publish pages (Megan)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] QuickSubmit and the new url are being used on the live site

**Comment by RLHecht** [comment]
@aliyahblackmore I edited the top of this ticket to show that they are launching the new program June 30. The stakeholder said we can publish earlier but this is not a rush so may push this ticket to next sprint if other things take priority.

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht ! I'm working on this at the moment and compiling the pages in a Word doc. If you hear more about another way to collect the pages, let me know!

**Comment by RLHecht** [comment]
@aliyahblackmore Public Websites completed their audit for us. Here's what they found (copying from their ticket, which I also just linked below):

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9219#issuecomment-1150542919

@RLHecht I searched for the phrase "direct upload" and the eauth URL:
grep -Rli "Direct Upload" build/localhost > directupload.txt
grep -Rli "https://eauth.va.gov/accessva/?cspSelectFor=dmhs" build/localhost > ~/Downloads/directupload2.txt

And that returned this set of pages:

/burials-memorials/eligibility/burial-in-private-cemetery/index.html
/burials-memorials/memorial-items/presidential-memorial-certificates/index.html
/burials-memorials/memorial-items/headstones-markers-medallions/index.html
/disability/dependency-indemnity-compensation/index.html
/disability/upload-supporting-evidence/index.html
The only new paths besides the ones you mentioned already are these:

/burials-memorials/memorial-items/presidential-memorial-certificates/index.html
/disability/dependency-indemnity-compensation/index.html
I sanity checked against a Google search, and I do see several additional VBA forms that include the URL in the form itself via google (e.g. https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf). Our audit can't check for contents of files, as far as I know - if those forms are concerns here, let us know and I can see if there is any way to check file contents.

Going to move this back to in progress since we can pick this up again when you're ready.

**Comment by aliyahblackmore** [comment]
Hi @megzehn these are ready for you whenever you have a moment! There was one other page that I found in my initial search that was not included by PW (VA Survivors Pension page); this page is included.  

For the **Veterans headstones, markers, and medallions, Burial in a private cemetery, and  Presidential memorial certificates** pages, each included a set of instructions on how to use direct upload. Flagging that it seems that these instructions are the same for QuickSubmit and I replaced each "direct upload" here. I wonder when it says “select the option that describes you” would the log in options (i.e. with a PIV card or Login.gov) be considered a “describe me” scenario. Should there be any sort of content change here?  Cc: @RLHecht 

Pages and their links are below: 

**Upload evidence to support your disability claim page**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=913 

**VA Survivors pension page** 
Preview link:  http://preview-prod.vfs.va.gov/preview?nodeId=590

**Veterans headstones, markers, and medallions**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=859

**Burial in a private cemetery**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=2346

**Presidential Memorial Certificates** 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=860

**Survivor and Dependent compensation (or About VA DIC for spouses, dependents, and parents)** 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=855

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht !! @megzehn this is ready for you whenever you have a moment.

**Comment by megzehn** [comment]
Adding list below, and will check off as they are published. 

- [ ] Upload evidence to support your disability claim page
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=913

- [ ] VA Survivors pension page
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=590

- [ ] Veterans headstones, markers, and medallions
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=859

- [ ] Burial in a private cemetery
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=2346

- [ ] Presidential Memorial Certificates
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=860

- [ ] Survivor and Dependent compensation (or About VA DIC for spouses, dependents, and parents)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=855

**Comment by laurwill** [comment]
Hi @aliyahblackmore , just popping in on this “select the option that describes you” question — that's referring to options on the AccessVA homepage, but we're not linking to the homepage, we're linking directly to the QuickSubmit login. So I think we need to:
- Remove this text from those 3 pages: "From the Access VA home page, select the button that describes you. Then select the QuickSubmit option."
- Probably also remove this text: "If it’s your first time signing into this tool, you’ll need to register first. After you’ve registered, you can upload your application and documents online." I think this is referring to registering for Direct Upload (or now for QuickSubmit) — but this info doesn't appear on all the pages that mention these tools, and it doesn't seem necessary. The tool itself will prompt people to register if they haven't signed in before.
- Confirm whether all the intended audiences of these 6 pages can actually use QuickSubmit. For example, the [headstones page](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) lists lots of groups who can apply for headstones who don't fall into the categories on the AccessVA homepage. @RLHecht , maybe you know the answer to this, or maybe it's a quick question for the stakeholder? The question is something like... can **anyone** use QuickSubmit, or do people need to fall into one of the categories on the AccessVA homepage in order to use this tool? If only Veterans, family members, VA employees and VA business partners can use the tool, then we'll need to add a note for the "online" option on pages where people outside these groups might be eligible to apply for the benefit.

**Comment by laurwill** [comment]
Hi again @aliyahblackmore , the stakeholder confirmed that people don't need to fall into the categories on the AccessVA homepage in order to use QuickSubmit — so we don't need to add an additional note here.

Can you go ahead and remove only this text from those 3 pages: "From the Access VA home page, select the button that describes you. Then select the QuickSubmit option." 

(I think we can keep the lines about registering if it's the first time you're using the tool — these 3 pages have a wider audience than the others, so it's more likely that people will be unfamiliar with AccessVA.)

Also flagging for @megzehn that I'm seeing "Access VA" with a space on some of these older pages — I think these should all be "AccessVA" with no space.

**Comment by megzehn** [comment]
These are now copyedited and ready to publish on the 30th. 

In "Burial in a private cemetery" there's obscure language around "in their time of need" that we may want to revisit to make more direct. (Flagging here, because we changed similar language on another article, in an effort to make language more direct for translation purposes.)

**Comment by megzehn** [comment]
Confirming these are all published now.

**Comment by megzehn** [comment]
Over to you @RLHecht!

**Comment by RLHecht** [comment]
These changes are all live and I notified the stakeholder. Closing ticket!
