### ISSUE TITLE
[FE] Add a Wrapper or Header component to the app

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41229]
## User Story
As a Developer, I want to minimize duplicate code, and complexity of adding or modifying a page in the application

## Description
The outcome of this ticket would be a new component, as either a wrapper or a Header (similar to the Footer component)
This new component can contain:
- The useEffect() to auto-focus on the first h1 of the page
- The heading itself
- Potentially future:
  - Language switcher
  - Notices of incomplete translation on the page

## Tasks
- [ ] Create the new component
- [ ] Migrate existing pages to use the component
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
