### ISSUE TITLE
Fill in "contract_name" column in product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41221]
## Issue Description
We need to fill in the Contract Name column on our product list as they relate to products. We do not currently have a source for this information, so research will need to be conducted as to where we can find this information reliably. Once a source is located, fill in all applicable entries for each product.

---
## Tasks
- [ ] Research source for Contract Name.
- [ ] Grab the latest product directory from our "product-directory" GitHub repository
- [ ] Fill out our column for Contract Name in the product list
- [ ] Open a PR to merge changes to the product directory.

## Acceptance Criteria
- [ ] The Contract Name column is filled out in the product list.
- [ ] All non-applicable entries are left blank.
---

**Comment by CBonade** [comment]
Reached out to Ray Wang about this but no response yet. By slack's activity indicator it appears he may be out today.

**Comment by JoeTice** [comment]
Deprioritized based on the use case that it belongs to

**Comment by CBonade** [comment]
This work was completed
