### ISSUE TITLE
Fill in the "analytics_category" column in the product list.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41226]
## Issue Description
The Analytics team has a list of categories that they have traditionally applied to classify the products on vets-website. We need to obtain a list from the Analytics team of what products they currently have as well as what categories belong to them and do our best to match them up to the products on our list. These values should go in the "analytics_category" column.

---
## Tasks
- [ ] Obtain list of products and categories from Analytics team.
- [ ] Grab the latest product directory from our "product-directory" GitHub repository
- [ ] Map categories on the Analytics product list to the "analytics_category" column on our product list.
- [ ] Open a PR to merge changes to the product directory.

## Acceptance Criteria
- [ ] The "analytics_category" column has all applicable entries filled out.
- [ ] Any other entries with no value are left blank.
---

**Comment by CBonade** [comment]
https://docs.google.com/spreadsheets/d/1sVVJJqAU4tXVLQ2sVLatHl27XVJyxFhz6pCrQyzdUUQ/edit?usp=sharing

This is the list that the analytics team has that we can use to map some of these. We also may be able to pull some additional team designations from this same list and should tackle that while we do this.

**Comment by CBonade** [comment]
These are filled in for as good as I could match them up. Unfortunately, the team data did not seem to provide us much more than the Governance list already had.

**Comment by pjhill** [comment]
Donezo
