### ISSUE TITLE
[DESIGN] - Auth Profile - Review and Update Spacing in Mockups

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#41230]
## Background

The spacing in some of our Profile mockups does not always align with the spacing on Staging. Desktop and Mobile should be reviewed to make sure spacing is consistent for both.  

## Tasks
- [x] Review spacing in Profile mockups as compared to Staging
- [x] Make changes needed to match mockups to Staging

## Acceptance Criteria
- [x] All Profile mockups have been reviewed
- [x] Profile mockups (desktop and mobile) match Staging for all sections of Profile

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so
