### ISSUE TITLE
Fill in "endpoints_provided" column on product list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41242]
## Issue Description
We need to fill out the "endpoints_provided" column in the product list. Each product should be assessed for any endpoints that it provides access to for use by other entities. This should be filled out in the format of a comma-separated string.

---
## Tasks
- [x] Assess each product for endpoints that they provide for other entities to consume.
- [x] Grab the latest product list from our "product-directory" GitHub repository.
- [x] Fill in values accordingly in the "endpoints_provided" column on the product list.
- [x] Open a PR to merge new changes to the product list.

## Acceptance Criteria
- [x] Our "endpoints_provided" column on the product list is filled out accordingly.
- [x] Any non-applicable entries are left blank.
---

**Comment by JoeTice** [comment]
This task is being deprioritized, as it is not related to one of the priority use cases

**Comment by CBonade** [comment]
This task was completed.
