### ISSUE TITLE
Add content to Survivors' and Dependents' Educational Assistance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41244]
## Issue Description
Stakeholder Cinda Quattrini asked us to add language to the blue featured content box on the [Survivors' and Dependents' Educational Assistance](https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/) page. 

Under the H3 "If you're the spouse of a Veteran or service member" in the second bullet we need to add the words "from active duty" (bolded just to show where in the paragraph it should be--this shouldn't be bolded on the page):

- If we rated the Veteran as permanently and totally disabled, with an effective date that’s 3 years after discharge **from active duty**, you’ll qualify for benefits for 20 years from that effective date. This new policy began on October 10, 2008. We won’t pay benefits for training you started before this date.

Her explanation for the update: The current wording that states ‘3 years after discharge’, which may cause confusion as some consider this to include reserve service.  VA policy determined Public Law 110-389 section 321 to mean discharge from active duty only.

Before we make this change we need to review the page to determine if this language is also elsewhere and needs to be added. 

**Note:** This page in Drupal is currently a draft that can't be published yet. That work is in ticket #26625. I am checking with the stakeholder for her to review those changes. If we don't hear back from her when we are ready to publish this, I can show the team how to revert to a previous version so we can publish these changes and then add the draft text back in if need be. 

## Tasks
- [x] Assess stakeholder request (Laura)
- [x] Add content to page (Randi)
- [x] Review change (Laura)
- [x] Publish page (Randi)

## Acceptance Criteria
- [x] New content is added to live page

**Comment by RLHecht** [comment]
Laura and I did this as a screenshare to show how to take out content that can't be published to make other changes. She reviewed onscreen and we published the page. Moving to validate and will notify the stakeholder once changes are live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
