### ISSUE TITLE
Research "business_owner" category

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41240]
## Issue Description
Currently we only have one entry in the "business_owner" category as that is all that was in the Governance Team's list. We should research if there is anywhere else we can get more of these before we call it done.

---
## Tasks
- [x] Research possibility of more entries for Product's Business owners existing in other data sources outside the Governance Team's list.

If yes: 
- [x] Grab the latest product list from the "product-directory" GitHub repository.
- [x] Add entries to the "business_owner" column accordingly in terms of products
- [x] Open a PR to merge the new entries to the product list.

## Acceptance Criteria
- [ ] Our product list has all applicable entries filled in for the "business_owner" column.
- [ ] Any rows with no value are left blank.
---

**Comment by pjhill** [comment]
Step 1 -- Talk to Shira on Governance team about other potential sources for this

**Comment by pjhill** [comment]
PR looks good. We are left with a lot of blanks to attempt to fill in / crowd source later, but this is just a first pass.

**Comment by pjhill** [comment]
Second thought -- the data has been gathered, but we're amidst a pivot to JSON instead of CSV. We will need to enter this data into the new JSON format again.  For now though, the data has been collected.
