### ISSUE TITLE
[EKS] Verify configs between BRD and EKS vets-api

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#41253]
## Description
Double check that all of the needed configurations and files are put in place for the dev vets-api deployment

in order to do so I will be comparing dev 

BRD (mainly in deployment) - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible
EKS - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-tools-backend/vets-api

to make sure that everything is synced properly so we aren't diving down rabbit holes if anything doesn't work.

## Background/context 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35039

---
## Tasks
- [ ] create a checklist to make sure all files and configurations match between BRD and EKS dev
- [ ] verify that all of the appropriate secrets are also matching between credstash and parameter store

## Acceptance Criteria 
- [ ] all of the files and configurations that exist in BRD are up to date and exist in EKS dev

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by patrickvinograd** [comment]
Re the issue with fwdproxy connection getting an SSL error: 
vets-api BRD instances get the forward proxy's `self.crt` added to their trust store in 
ansible/build/roles/vets-api/tasks/main.yml
```
- name: Copy self signed forward proxy ELB cert (wildcard) to anchors
  copy:
    src: ../deployment/config/fwdproxy/self.crt
    dest: /etc/pki/ca-trust/source/anchors/forward-proxy.crt
    owner: root
    group: root
    mode: 0600
```
and then subsequently `update-ca-trust` and `update-ca-trust-enable` are executed.

I don't know what the equivalent would be for EKS.

**Comment by patrickvinograd** [comment]
I _think_ the right approach would be to add the self.crt to config/ca-certs at Docker image build time. I see the code_checks.yml GHA job is doing this with the VA PKI cert:
`cp /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem config/ca-trust/`

But there's nothing equivalent in the Build & Push to ECR action. Wondering if both self.cert and the above VA cert should be injected there?

**Comment by patrickvinograd** [comment]
Digging further - looks like `VA-Internal-S2-RCA1-v1.cer` gets added to the eks base image (and the gha image) via the packer builds in the devops repo, which is why that is not needed in the Build & Push github action. So figuring out the right place to do likewise for self.crt should address this?

**Comment by mleclerc00** [comment]
Thank you for the comments Patrick

**Comment by mleclerc00** [comment]
as it pertains to the `deployment_files` in BRD land here -> https://github.com/department-of-veterans-affairs/devops/blob/cb4a947401bea743545a64cbc15d1a6d3c895ac5/ansible/deployment/config/vets-api-server-vagov-dev.yml#L113

There are definitely some differences going on which I will work on cleaning up today.

Going to aim at making sure everything is in parameter store at the correct paths and remove all references to credstash for good measure.  It also looks like we missed a directory in the first couple of passes (`/app/secret/pre`)

I used a dumb little "one liner" to capture the files being deployed and output `ls` commands that I can just bulk copy and paste into the terminal to check for them.

`cat vets-api-server-vagov-dev.yml| yq e '.deployment_files[].dest' | sed 's/\/srv\/vets-api/\/app/g';for i in files;do echo "ls $i";done;`

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/76792875/171445294-c790ac57-3a3f-42e7-bf8b-1a9b680df00c.png">

**Comment by oseasmoran73** [comment]
Checked `pki tls private directory` and the values have the correct format

**Comment by oseasmoran73** [comment]
Checked `pki tls certificate directory` and the values have the correct format

**Comment by madebydna** [comment]
@mleclerc00 / @oseasmoran73 Not sure if you guys saw [this vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/9984) but it essentially represents our attempt to ensure that the EKS version of `vets-api` (on the `k8s` branch) also trusts the forward proxy certificate. We haven't gotten much feedback on it, so I was wondering if you could take a quick look (cc @patrickvinograd)?

**Comment by oseasmoran73** [comment]
@madebydna LGTM. Us throwing an approval does not mean much since we are not code owners of `vets-api` repo

**Comment by oseasmoran73** [comment]
EKS & BRD are now aligned. See new screenshot 
![image](https://user-images.githubusercontent.com/10648480/172720580-1b4294ce-5b8c-4e33-aedf-84f725d16eff.png)

**Comment by oseasmoran73** [comment]
Given that there is not much verification aside that is it still working as intended in dev, I feel the requirements have been fulfilled. Closing ticket
