### ISSUE TITLE
Change vets-api's Lighthouse API key in the DEV environment

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41254]
## Issue Description
There is a lack of environmental separation between dev and sandbox for vets-api in terms of Lighthouse API access. It turns out that vets-api is not even set up as a Lighthouse client in the DEV environment.

Originally, vets-api in the **_dev_** environment actually hit the LH Facilities endpoint in _**sandbox**_ using the `sandbox-api.va.gov url`. This worked, because there is a functional key for that environment.

When we originally changed the `vets-api` code so that it used the fwdproxy address to go to LH directly, the call worked because we side-stepped API key checking in Kong.

The most recent change was to go to Kong directly via the fwdproxy, which causes an authentication error, because there is actually no client or API key set up for the dev environment.

The Lighthouse team has added the vets-api client to the **_dev_** environment and will give us an environment-specific API key. We will need to update the AWS secret with the new API key.

---
## Tasks
- [x] Figure out how to change secret in AWS Parameter store and whether or not we have permission to do it ourselves
- [x] Change DEV secret in AWS Parameter Store
- [ ] Change DEV secret in credstash (old secret store?)

## Acceptance Criteria
- [x] AWS DEV secret API key is changed and DD test is passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
