### ISSUE TITLE
[BE] Onsite Notifications: Update Tokens for Vets-API Auth

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#41268]
## Background
The VA Notify team's public key needs to be added to vets-api.

The VA Notify team informed us that our authentication process for onsite notifications needs to include additional fields to the token that is used to authenticate requests to the vets-API.

## Tasks
- [x] Add public key to configuration [here](https://github.com/department-of-veterans-affairs/devops/blob/1fe92b76dd774ccf88429e88f97b1eb264a6c462/ansible/deployment/config/vets-api/staging-settings.local.yml.j2#L419). 
- [x] Update controller code [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/onsite_notifications_controller.rb#L49).
- [x] Add JWT checks for `issued at` and `expiration`

**Comment by tpharrison** [comment]
This [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41750) was opened and assigned to devops for configuring the public key.

**Comment by tpharrison** [comment]
@ajakabcin @ericasauv09 - the development work is done.  I opened a ticket for next sprint to support testing the JWT (we'll need to use VA Notify's private key for that).  Let me know if you have any questions.

cc/ @Samara-Strauss
