### ISSUE TITLE
Create Updated Mockups for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4126]
## Story
As an eBenefits Team member, I need updated View Dependents page mockups so that I know how to proceed with frontend development.

## Considerations
- New View Dependents mockup must incorporate specific styling--particularly "cards" from the [approved Rated Disabilities screen](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL)
- We need to see if the in progress form has an expiration, and if that messaging should be included.
- If API calls are going to be combined, errors may have to reflect that way

## Tasks
- [x] Create a revised mockup of the _happy path_ page layout
- [ ] After coordinating with BE/FE to review and identify which discrete components are applicable, create an _error state_ mockup(s) for both 400 (can't find) and 500 (data broken) errors for each component on the "View Dependents" page

## Acceptance Criteria
- [x] Mockups have been created and shared with the eBenefits Team

### Next steps:
Initiate reviews for Content & IA, then Platform reviews.

**Comment by sporeboy** [comment]
View Dependents mockup revisions in-progress. XD link here: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/61211510-a9de-477c-950c-ae7fe5d2ce65/View-Dependents-2

**Comment by sporeboy** [comment]
Design intent review scheduled per Jennifer Strickland's process outline; issue #4431 generated: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4431
