### ISSUE TITLE
Remove MHV Inherited Proofing Date

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#41278]
## Issue Description
This ticket tracks the work of removing the MHV Inherited Proofing date deadline from `vets-website`.

---
## Tasks
- [x] Modifies existing components that contain the MHV deadline
- [x] Update unit tests as appropriate

## Acceptance Criteria
- [x] The MHV Inherited Proofing deadline is not viewable on `vets-website`
