### ISSUE TITLE
Draft copy of Platform Satisfaction Survey landing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#41272]
## Issue Description
Consider and prepare a proper landing  for linking to VFS Satisfaction Survey info, for use in General Orientation slide deck by Governance.

What should be there?

Request initiated by Andrea via Governance.  From Shira:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/41340

[Landing starting place](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2194964673/Platform+Satisfaction+Survey)
---
## Tasks
- [x] Discuss where this should live and what for it might take
- [x] Prepare the skeleton for landing
- [x] Prepare initial copy content
- [x] Prepare visual aid(s)

## Acceptance Criteria
- [x] Landing site/page is prepared in Confluence
