### ISSUE TITLE
Conduct Platform Design Review of "View Dependents" Mockup

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4127]
## Goal
We need the View Dependents screen layout reviewed and approved by the Platform Design Team so we can proceed with frontend development of a system-compliant page.

## Tasks
- [x] Resolve IA questions on landing page
- [x] Schedule a Platform Design Team review of the "View Dependents" mockup
- [ ] Incorporate feedback/directives from the session
- [ ] Schedule a walkthrough of the changes to the updated mockups BE/FE/PM

## Acceptance Criteria
- [ ] Review scheduled with the Platform Design Team

## Next Steps
- [ ] After incorporating rough feedback, a team walkthrough conducted to discuss changes and next steps.

**Comment by sporeboy** [comment]
Per current Platform design review process, the Platform Design Review may be superseded by Platform Design QA. The Github doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md#designreviews

Latest Platform rules of engagement: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md#designreviews

**Comment by sporeboy** [comment]
Formal review was requested: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5114
