### ISSUE TITLE
[EC2 AMIs] Upgrade base images to latest Amazon Linux 1

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#41289]
## Description
The base image that we are using to build EC2 instances will be deprecated on June 30, 2022. This needs to be updated to the image that will be supported through mid-2024. 

## Technical notes
- Location of configuration files where AMIs are defined [here](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/applications/config)

---
## Tasks
- [x] Update the Ansible-based image builds to use the latest AMI (example [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/applications/config/default.yml#L3))
- [x] Manually trigger build jobs to verify images are built 

## Acceptance Criteria 
- [x] All Ansible-based AMIs are deployed using the new image

**Comment by jbritt1** [comment]
```
❯ for id in $(grep -R bake_ami: | cut -f 3 -d ":" | tr -d " "); do echo $id && aws ec2 describe-images --image-id $id | grep DeprecationTime; done

ami-048d0e3e6869aad8f
"DeprecationTime": "2024-04-29T00:43:52.000Z"

ami-00053c72c33ce3a23
"DeprecationTime": "2024-01-30T20:20:58.000Z"

ami-00053c72c33ce3a23
 "DeprecationTime": "2024-01-30T20:20:58.000Z"

ami-00053c72c33ce3a23
"DeprecationTime": "2024-01-30T20:20:58.000Z"

ami-0f0450d4bd6bc6640
 "DeprecationTime": "2023-10-21T15:33:13.000Z"

ami-098bf51d9a35299f0
"DeprecationTime": "2023-12-01T20:13:31.000Z"

ami-0102351545748ea56
An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-0102351545748ea56]' does not exist

ami-02b48c6842582f942
"DeprecationTime": "2024-02-22T18:46:17.000Z"

ami-0f0450d4bd6bc6640
"DeprecationTime": "2023-10-21T15:33:13.000Z"

ami-098bf51d9a35299f0
"DeprecationTime": "2023-12-01T20:13:31.000Z"

ami-0102351545748ea56
An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-0102351545748ea56]' does not exist
```

The two that do not exist in the list above (actually the same AMI, used in two places) are not found in the Govcloud account. Blackbox lives in the commercial AWS account. The commercial account AMI used also has a further dated deprecation date of February 7th, 2024:

```
❯ aws ec2 describe-images --image-id ami-0102351545748ea56 | grep DeprecationTime
"DeprecationTime": "2024-02-07T19:58:11.000Z"
```
