### ISSUE TITLE
[Vets-API / EKS] Create infrastructure-related performance dashboards in DataDog 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#41293]
## Description
In order to support Vets-API, we need to have monitoring in place to track infrastructure health. There are dashboards in Grafana, but we need comparable dashboards in DataDog. 

## Background/context 

- The platform is migrating to DataDog, with the goal of sunsetting Prometheus in the near future. 
- Grafana dashboards for Vets-API can be found [here](https://grafana.vfs.va.gov/d/000000017/vets-api?editPanel=18&orgId=1)

## Technical notes
We need monitors in place to track the following metrics for Vets-API server

- CPU 
- Network
- Disk 
- Memory 

Note: You should be able to translate the metrics from Prometheus to DataDog by clicking on each widget in Grafana to see the metrics query:

`sum((irate(node_network_receive_bytes{deployment_name="vets-api-server"}[1m]) + irate(node_network_transmit_bytes{deployment_name="vets-api-server"}[1m])) * 8) by (instance) `

---
## Tasks
- [x] Verify that metrics for the above listed components are available in DataDog  
- [x] Create a 'Vets-API Infrastructure' dashboard that displays the metrics listed above using DataDog widgets 

## Acceptance Criteria 
- [x] The Platform Infrastructure team has a dashboard in DataDog that display Vets-API metrics related to: 
  - [ ] CPU (total consumption) 
  - [x] Network throughput 
  - [x] Disk I/O
  - [ ] Memory (total consumption)

**Comment by oseasmoran73** [comment]
Adding [datadog](https://app.datadoghq.com/dashboard/kxm-a4x-cd4/vets-api-dashboards?from_ts=1652380406126&to_ts=1652466806126&live=true) vets-api

**Comment by oseasmoran73** [comment]
[Dashboard](https://app.datadoghq.com/dashboard/ywq-r9g-xia/oseas-eks-test-dashboard?from_ts=1652694756676&to_ts=1652698356676&live=true) with created during testing

**Comment by oseasmoran73** [comment]
CPU & Memory differ from how it is in BRD.

In EKS, it is handled per cluster. We have a dashboard for it in [Kubernetes Nodes Overview](https://app.datadoghq.com/screen/integration/30340/kubernetes-nodes-overview?tpl_var_cluster=dsva-vagov-dev-cluster&from_ts=1653323982749&to_ts=1653324282749&live=true). Do we want to have `Nodes Overview` dashboard?

@ph-One @jhouse-solvd

**Comment by oseasmoran73** [comment]
Added memory and cpu per pod per Kyle's feedback. Got approval that dashboard criteria has been met. Closing
