### ISSUE TITLE
[FSR] Prototype iteration 2.0 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#41290]
## Issue Description
During discussions regarding the combined FSR's scope, it was decided that we should try to minimize pushing for some features for this iteration. This ticket captures reviewing and adjusting the prototype to scale back on features that could be incorporated later on in the roadmap. An example of this would be the question asking if the Veteran wants to waive all their debts. 

---
## Tasks
- [x] Review and update the prototype 
- [x] Schedule time to share the updated prototype to team

## Acceptance Criteria
- [x] The updated prototype is linked in this ticket

**Comment by rileyorr** [comment]
Updated prototype can be found in [this UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/no-panels?mode=i)

**Comment by rileyorr** [comment]
Update on this work: The updated prototype will be shared with the team on Monday, June 13th
