### ISSUE TITLE
Create Code to Process the JSON into HTML

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41296]
# Description
In order to generate a human-readable product list we will need to be able to parse the data stored in the JSON form of the product list into HTML for injection into Confluence via the Confluence API.

# Tasks
- [x] Write code to parse the JSON into human eyeball friendly HTML layout
- [x] Test injection of the HTML into Confluence
- [x] Ensure that the injected HTML displays without anomalies in Scroll viewport

# Acceptance Criteria
- [ ] Product list is formatted in HTML
- [ ] Product list HTML passes A11y evaluation

**Comment by rsmithadhoc** [comment]
- Started a [draft PR](https://github.com/department-of-veterans-affairs/product-directory/pull/32).
- Tried CSV to HTML packages but the resulting HTML would require a lot of post-processing to work with Confluence, I scrapped that idea due to unneeded complexity.
- The current approach is to parse the CSV to a JavaScript object with `papaparse`, which gives an array of each row. Then put those values into an HTML table row. I believe this will be simpler and easier to maintain.

**Comment by rsmithadhoc** [comment]
Continued work on this:

- Converted CSV to an HTML table.
- Working on converting JSON within a field into an HTML list.

After that is wrapped up, I need to send the HTML to Confluence, do some code cleanup, and add tests.

**Comment by rsmithadhoc** [comment]
Shifted focus to getting the API calls working since we are changing from a CSV to a JSON file. The API calls are working with a sample HTML file that will be similar to the final output sent to Confluence.

While waiting on the final JSON format, I am working on:

- Table formatting in Confluence is squished due to the number of columns.
  - I believe I have a workaround that will set column widths but I still have to test and implement that.
- Adding tests.
- Hooking this up to the GitHub action and setting up environment variables.
- Code cleanup.
- Setting up a basic configuration file to allow the addition of pages to be published to.
  - It will only contain governance's use case. It could be expanded to more pages or more settings such as showing/hiding certain columns in the future.

**Comment by rsmithadhoc** [comment]
Worked on converting any CSV code over to the new JSON format. That is in place but need to do testing and fixes on that.

**Comment by rsmithadhoc** [comment]
- I have a [VFS Confluence page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2213216257/Sample+Product+List+Sync) being produced from the JSON product directory and the publishing process.
- The Confluence page is functioning as expected.
- Testing revealed some additional formatting issues, and patching some took longer than expected. What remains is the Features column it produces a list but it doesn't separate features well, links, and potentially standardize how we store lists in the JSON after consulting with the team (see screenshot).
  ![image.png](https://images.zenhubusercontent.com/62222b1c8a8a2d232882a99b/4036d481-081b-488f-9a30-d9f586e9c7a5) 
- A few unit tests to fix, a few to write.

**Comment by rsmithadhoc** [comment]
https://github.com/department-of-veterans-affairs/product-directory/pull/43 out for review

**Comment by rsmithadhoc** [comment]
Code merged, closing this one.
