### ISSUE TITLE
Work with Governance to Verify Use Case and Doc Location

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41297]
# Description
Now that we are ready to automatically generate a human-readable version of the product list, let's confirm the use case that we gathered from Governance team and verify that the use case hasn't changed since we first spoke to them.

Governance Use Case is documented [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1649377300526/ed440220603d6afe04eb9bd7a8b8b8f2addc6a94?wid=46-1649429611611).

# Tasks
- [x] Contact Governance team to discuss our interpretation of their use case
- [x] Make changes to the use case definition if necessary
- [x] Verify the location in Confluence where Governance team wants their human-readable product list

# Acceptance Criteria
- [x] Governance team use case is confirmed
- [x] Governance team list location is defined

**Comment by rsmithadhoc** [comment]
Support request out to governance: https://dsva.slack.com/archives/CBU0KDSB1/p1652456784267839

**Comment by pjhill** [comment]
Looks like we answered all the questions we still had -- thanks for closing this out!
