### ISSUE TITLE
Translation for additional doses content on COVID-19 booster page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41305]
## Issue Description
When inputting new translations to the [COVID-19 booster shots and additional doses](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) page, we discovered we have text on our English page that was never translated into Spanish and Tagalog.

We need to send this content to the translators so we can keep all three pages consistent. 

Word doc to send: [https://app.zenhub.com/files/133843125/d5d61489-4e64-47be-ba67-1aff86089158/download](https://app.zenhub.com/files/133843125/d5d61489-4e64-47be-ba67-1aff86089158/download)

## Tasks

- [ ] Send text to translation team (Randi)
- [ ] Input translated content on Spanish page (Aliyah)
- [ ] Input translated content on Tagalog page (Aliyah)
- [ ] Review changes (Megan)
- [ ] Publish page (Megan)
- [ ] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [ ] Translated content is live on Spanish page
- [ ] Translated content is live on Tagalog page

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the Spanish translation that needs to be input. Thanks![https://app.zenhub.com/files/133843125/55678620-4f7d-4aa4-9b7f-44c402fd8535/download](https://app.zenhub.com/files/133843125/55678620-4f7d-4aa4-9b7f-44c402fd8535/download)

**Comment by aliyahblackmore** [comment]
Great! Getting started on this one today. Thanks Randi

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Spanish page is ready for you! Preview link is [here](http://preview-prod.vfs.va.gov/preview?nodeId=34408)

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Tagalog page is ready for you! Preview link is [here](http://preview-prod.vfs.va.gov/preview?nodeId=34394)

**Comment by megzehn** [comment]
@RLHecht these are published and ready when you are!

https://www.va.gov/health-care/covid-19-vaccine-esp/booster-shots-and-additional-doses-esp/

https://www.va.gov/health-care/covid-19-vaccine-tag/booster-shots-and-additional-doses-tag/

**Comment by RLHecht** [comment]
Thanks, @megzehn! I just validated these and sent the links to the volunteer translators. Closing this ticket and will reopen if he has any changes we need to make.
