### ISSUE TITLE
Translation for additional doses content on COVID-19 booster page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41304]
## Issue Description
When inputting new translations to the [COVID-19 booster shots and additional doses](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) page, we discovered we have text on our English page that was never translated into Spanish and Tagalog.

We need to send this content to the translators so we can keep all three pages consistent. 

## Tasks

- [ ] Send text to translation team (Randi)
- [ ] Input translated content on Spanish page (Aliyah)
- [ ] Input translated content on Tagalog page (Aliyah)
- [ ] Review changes (Megan)
- [ ] Publish page (Megan)
- [ ] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [ ] Translated content is live on Spanish page
- [ ] Translated content is live on Tagalog page

**Comment by RLHecht** [comment]
duplicate. closing.
