### ISSUE TITLE
Fill out yml file for console UI onboarding

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#41315]
## Why are we doing this? 
The console UI team would like us to add the Console API to the Platform Console, we need to fill out this [yaml ](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/docs/catalog/creating-a-catalog-info-file.md)file in order to do this. 

## Tasks 

- [ ] Complete the form

## How do we know we are done? 

- [ ] The form is complete

**Comment by LindseySaari** [comment]
[PR opened here](https://github.com/department-of-veterans-affairs/platform-console-api/pull/242)

**Comment by LindseySaari** [comment]
Merged in the PR and now waiting to get my Login.gov account whitelisted in order to continue the console ui onboarding process. [Ticket opened here](https://github.com/department-of-veterans-affairs/access-management-integration/issues/54)

**Comment by LindseySaari** [comment]
Items still left to complete:
- [ ] Get Login.gov account whitelisted [Ticket here](https://github.com/department-of-veterans-affairs/access-management-integration/issues/54)
- [ ] Import platform-console-api into the catalog. [Step #4 here](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/docs/catalog/creating-a-catalog-info-file.md)

**Comment by LindseySaari** [comment]
I imported the catalog-info.yaml file to the console, but just waiting for it to show up in the list before completion
