### ISSUE TITLE
Research and Implement solution for varying test results structure in reporting

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41313]
## Issue Description
Our test reporting ingestion has worked fairly well with few issues up until recently. We had an issue a few months back where due to the preferential test structure of a particular team, the results of the test were in a structure that was not compatible with our schema for where that data was going to be stored. Our solution at that time, was to request that this team restructure this test to work with our schema, as it was a one-off case. As of now, though, we have two more teams - one of which is in a unit test and one in an e2e test - that also do not work with our schema. As we do not have a strictly prescribed test structure, and doing so goes against team autonomy as a practice, we need to come up with a more flexible solution. This solution needs to be able to account for any level of hierarchical complexity that may arise in our test results.

The ingestion process is handled in our `qa-standards-dashboard-data` repository. The current problem seems to be stemming from fields being set as required and then the data set does not have those fields populated to fill in. This results in the test result being rejected by BigQuery for missing required data. However, that data very well may exist - just not where our schema thinks it does. We need to somehow be able to adapt to any format of results that comes in and make sure the data makes it into BigQuery properly. 

Currently, only the Unit test results and E2E test results are breaking when trying to ingest the results, however other ingest methods are prone to the same problems, therefore all should be addressed. BigQuery is not very receptive to schema changes without deleting and recreating the table. We do have the option to add new columns, but we cannot make changes to old ones easily.

---
## Tasks
- [ ] Research possible approaches to a flexible schema or alternate method of ingestion that will be compatible with any shape of results.
- [ ] Implement a solution that will get our e2e tests and unit tests back up and running without demanding a strict structure for tests to be written in a specific way. 
- [ ] Uncomment the currently commented out workflows in vets-website, and test to ensure they function.
- [ ] Merge the changes to vets-website.

## Acceptance Criteria
- [ ] All test reporting workflows that are currently commented out in vets-website are running again.
- [ ] Our implemented data ingestion solution is future-proof and will work with any test results structure.

---

**Comment by ddzz** [comment]
Unit test reporting failures were caused by one test file containing all of its test in a `beforeEach()` block. Moving these tests out of the block fixed the failures.

**Comment by ddzz** [comment]
The Cypress test causing upload failures has been refactored to work with the existing schema.

**Comment by pjhill** [comment]
Instead of accommodating the unusual test structure, the test was refactored. A solution that allows for more layered test structures will be pursued under a separate ticket in the future. For now, it's great to have Cypress test data flowing into our data warehouse again!
