### ISSUE TITLE
AWS service account for GitHub actions: svc-gha-platform-sre

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#41311]
## Who is the devops resource on your team?
Gino Perlangeli
@gperlangeli 

## Description
We need an AWS service account for github actions so that we can develop a pipeline that will deploy the platform support slackbot to EKS

## Background/context 
Background can be found in this task: https://github.com/department-of-veterans-affairs/va.gov-team/issues/40990

## Technical notes

---
## Tasks
- [ ] Create a svc-gha-platform-sre AWS service account

## Acceptance Criteria 
- [ ] The Platform SRE team has an AWS service account to use for developing GitHub actions
---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
@powellkerry : standard permissions for a service account are to push-pull to-from an ECR repo, and SSM parameter store. Do you need the service account to do anything else? What ECR repo(s) will this account push to?

**Comment by jsgarmon** [comment]
It looks like your CI pipeline is pushing to `dsva/platform-support-slackbot`, correct? Is this where images will be pushed by this new service account?

**Comment by powellkerry** [comment]
That is what the current ci-cd.yaml has. That pipeline has never been used to my knowledge, currently it is a manual push to heroku for deployment. If there is a dsva/platform-support-slackbot ECR I am fine to use it, it was probably an artifact from when someone started moving the application before.

**Comment by jsgarmon** [comment]
`svc-gha-platform-sre` IAM account has been created. Do you want access key/secret for this account to replace what is currently in this platform-support-slackbot repo?

**Comment by powellkerry** [comment]
Yes, we do need that. This app uses some environment variables to hook into slack and google docs

**Comment by jsgarmon** [comment]
This is done. Closing this.
