### ISSUE TITLE
Operations KPI setting and tracking implementation

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4131]
## High Level User Story
As a VSP Operations member, I need to determine KPIs and implement ways to measure them, so that I can make data-driven product decisions.

## Goals 
_VSP Ops determines 2-3 KPIs and determines and/or implements a way to measure them._

## Acceptance Criteria
- [ ] _Conduct KPI workshop_
- [ ] _Determine KPIs_
- [ ] _Implement measurements_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
