### ISSUE TITLE
Add Ian Hundere to  aws-auth ConfigMap for EKS access.

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#41323]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Add me to `aws-auth` ConfigMap for EKS access. PR is below:
https://github.com/department-of-veterans-affairs/devops/pull/11247/files

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

I'm onboarding with the infrastructure team

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

Add to me to `aws-auth` ConfigMap for EKS access in the devops repo.

## Acceptance Criteria 
- [ ] _Approve Ian Hundere to be added to the `aws-auth` ConfigMap_

I'm currently on the infrastructure team for the interim.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
