### ISSUE TITLE
[FE] Display "Page will be in Spanish soon" Disclaimer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41329]
## User Story
As a Veteran who chooses to view the pages in Spanish, if there is any English content on the page, I would like to know that the page will eventually be in all Spanish so that I don't think there is a problem.

## Wireframes
TBD

## Tasks
- [ ] [FE] Display disclaimer on all pages when 
   - Veteran has chosen a language other than English
   - There is some English text still visible anywhere in the application (is this a correct statement?)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
