### ISSUE TITLE
[FE] MyHealth - Migrate My VA dashboard FE to use refactored API endpoints

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41328]
## Issue Description
The API endpoints for secure messaging and prescriptions have been refactored, and the My VA dashboard front end needs to be updated to use the new API endpoints.

## Tasks
- [ ] Update My VA dashboard to use updated secure messaging API endpoint
- [ ] Update My VA dashboard to use updated prescriptions API endpoint
- [ ] Update technical documentation to specify new endpoints
- [ ] Let PO & PM know when task is complete

## Acceptance Criteria
- [ ] Update My VA dashboard to use updated secure messaging API endpoint
- [ ] Update My VA dashboard to use updated prescriptions API endpoint
- [ ] Update technical documentation to specify new endpoints
- [ ] Let PO & PM know when task is complete

**Comment by A6-toma** [comment]
Do we know what the updated SM and Prescriptions endpoints are, as well as their request/response payloads? I don't see details (or links to those details) in this ticket.

**Comment by A6-toma** [comment]
Yep. Still needed?

**Comment by MarciMcGuire** [comment]
I want to say this was one of the clean-up tasks Patrick Vinograd asked me to create for the backlog.

**Comment by A6-toma** [comment]
Closing per Slack conversation with @MarciMcGuire and @ajakabcin.
