### ISSUE TITLE
[product] Supplemental Claims | Identify leading indicators for favorable outcomes

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#41322]
## Value Statement
**_As a_** product manager
**_I want to_** identify the leading indicators that a Veteran will successfully complete a claim process
**_So that_** I can define opportunities and assumptions to test. 

---
## Tasks
- [ ] _List the claims processes I want to collect data for._
- [ ] _Review with Robin or Jesse to confirm if we can pull the data on our own._
- [ ] _If we cannot pull the data on our own, submit a request to Platform Analytics in #vfs-platform-support._
- [ ] _Submit a request to the Contact Center in #vsp-contact-center-support to gather relevant data._

## Acceptance Criteria
- [ ] _I have current data to support why we chose certain opportunity areas in the claims space._
- [ ] _I have identified leading indicators that signal when a Veteran is most likely to successfully complete a claim._
- [ ] _I have drawn relationships between potential assumption tests and the pain points, desires, and unmet needs of Veterans._

## Out of scope
- TBD

## Open questions
- How do we scope the kind of claims in this investigation?

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@cohnjesse This is the ticket I created for what I want to pull in GA. I'll let you know which claims process I want to pull this for.

**Comment by jacobworrell** [comment]
@saderagsdale when you say "complete a claim" do you mean, more specifically "complete claim _submission_"? , not to be confused with "claim is processed and a decision made"?

**Comment by saderagsdale** [comment]
@jacobworrell I want to start with "claim is processed and a decision made" first and if it's too broad then I'd narrow it. That way it captures what happens with claims processors too, not just Veterans.

**Comment by saderagsdale** [comment]
@thehastingsp Thinking about this ticket and how we can get some of these answers through the research on supplemental claims. I think it may be worthwhile to add this ticket to the research epic for supplemental claims. What do you think?
