### ISSUE TITLE
[FE] Clean up deprecated pages / functionality

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41334]
## User Story
As a front-end developer, I want a clean and easy to navigate codebase, to reduce complexity and make delivery quicker. Unused and deprecated pages complicate the codebase.

## List of Deprecated Content
- Edit functionality (Demographics, contact info, emergency contact)
  - `/components/pages/Edit`
    - All components within (Address, Email, index.jsx, Name, PhoneNumber, Relationship)
    - `shared` folder and all components within (Header, UpdateButton, EditLinkText, CancelButton)
-  `day-of/pages/UpdateInformationQuestion.jsx`
- setVeteranDataHandler in check-in only
- Any other unused components / pages that are found while doing this work

## Tasks
- [ ] [FE] Remove unused components / pages and code
- [ ] Remove or update unit tests
- [ ] Remove or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [x] not necessary
  - [ ] scheduled
