### ISSUE TITLE
Add Datadog events to Github Action packer-build-runner.yml. - BUILD_AMI_STARTED BUILD_AMI_FAILED and BUILD_AMI_SUCCESS

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41335]
## Description
Add a data dog events to the following workflows:

- [  ] Build AMI :  This should have both started and completed events sent to Datadog
- [  ] Update Launch Templates : This should have both completed event with the AMI ID and build app name sent to Datadog

[The GitHub action file](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/packer-build-runner.yml)

## Background/context 
The SRE team is starting to track build and images that are built for future metrics related to incidents.

---
## Tasks
- [ ] Create Datadog event for github action task: Build AMI for both started, failed and completed successfully.
``
    title="SRE_Build_AMI_Check_BRD_OK",
    text="SRE BUILD AMI Github { App Name } ",
    tags=[  "sre:buildamicheckgithub" ]
``
  
- [ ] Create Datadog event for github action task: Update Launch Templates for both completed successfully with AMI ID and Build App name.
``
    title="SRE_Build_AMI_Check_BRD_OK",
    text="SRE BUILD AMI Github - { Build AMI ID } - { Build App Name }",
    tags= "sre:buildamicheckgithub" 
``

## Acceptance Criteria 
- [ ] New Events in Datadog for Build AMI and Update Launch Templates.

**Comment by oseasmoran73** [comment]
@zachclarity The tasks that are listed seem achievable by your team. Is there a specific ask/task for Infra?

**Comment by oseasmoran73** [comment]
@zachclarity Bump

If this is no longer applicable or no additional assistance is required from Infra, we can remove it from our board or close this ticket out as a whole

**Comment by oseasmoran73** [comment]
No reply from @zachclarity . Closing this ticket out

CC @jhouse-solvd
