### ISSUE TITLE
[FE] 10-10EZ Use currentlyLoggedIn to Determine Displaying Veteran Name, DOB and SSN using Static Page or Input Page

### ISSUE THREAD

**Issue by lzapson** [department-of-veterans-affairs/va.gov-team#41339]
## Description
Change hasSession to currentlyLoggedIn in form.js depends functions to determine to display static page for authenticated users or input pages for unauthenticated users. 

---
## Tasks
- [x] Create view field for currentlyLoggedIn and set to user.login.currentlyLoggedIn
- [x] replace hasSession() to  view:loggedIn in form.js depends functions

## Acceptance Criteria
- [x] validate static page is displayed for authenticated users and input pages are displayed for unauthenticated users.
- [x] validate unit and e2e tests are passing
