### ISSUE TITLE
Add references to "VFS Satisfaction Survey" to General Orientation for VA.gov Platform slide deck

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41340]
## User Story
As a VFS team member, I want to be made aware of the VFS Satisfaction survey so that I may know of opportunities to communicate my feedback to Platform teams.

As a Platform/Service Design team member, I want to make sure VFS teams are aware of the VFS Satisfaction Survey early on so that we may have higher participation in the survey. 

- Intended Audience: VFS Teams, Platform
- Desired Outcome: reference to  the satisfaction survey is included in the General Orientation slide deck
- Due Date: 

## Description
VA.gov Platform Product lead Andrea Hewitt asked recently if the General Orientation deck made referenced to the VFS Satisfaction survey. Currently, the deck makes a reference to surveys sent to VFS teams from Platform, but it does not specifically call out the satisfaction survey. 
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/acdac8b1-dcfd-4560-8959-f70acbc504db)

## New Artifacts 
N/A

## Artifacts Needing Updates
[General Orientation for VA.gov Platform](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.gf08689d579_0_23) slide deck, slide 19

## Tasks
- [x] Check in with Service Design team to get their preference on how the survey should be communicated, and possibly linked
- [x] Update the slide deck with verbiage and/or link from Service Design team re: Platform Satisfaction Survey
  - https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey
- [x] Update Platform Orientation template with link for Platform Satisfaction Survey and Submitting a feature request

## Acceptance Criteria
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] VFS teams are notified of the Platform Satisfaction Survey in the General Orientation session
- [x] Service Design Team has reviewed and approved of changes to the slide deck

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@steel36 hey Bryan - check out this ticket and let me know what you think. We could set up a few minutes to chat if necessary.

**Comment by steel36** [comment]
@shiragoodman Yeah, this totally makes sense.  Our team will workshop how to best approach it, but at first blush the thinking would be to link out to a page in our Confluence space where we can add some Intro copy and maybe visuals to convey the What and Why behind the survey for the VFS audience.  We can then direct to appropriate follow-up links as needed from there.

**Comment by shiragoodman** [comment]
@steel36 i agree that having a page to link to with information on the survey is a great idea, however I think a better place for the page to live would be Platform Website, as it's used for all VFS-facing communication, whereas Confluence is for internal and operational info for Platform teams. I see you've already been working on this. Please let me know where you're at!

**Comment by steel36** [comment]
Absolutely to the Platform space.  Barring an issue, we expect that space to be live this week, and then I'll share the link w/ you.  Thanks!

**Comment by shiragoodman** [comment]
that's great. Thanks @steel36 !

**Comment by steel36** [comment]
@shiragoodman hey Shira, our new Platform page for the Survey has gone live on the Platform site.

Link: https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey

Our recommendation is to alter the language on the slide that reads "Quarterly satisfaction surveys" to become "Platform Satisfaction Survey" and link the new page.

Thanks so much for the opportunity to increase awareness on this item!

**Comment by shiragoodman** [comment]
this is great, @steel36 ! Thank you for sharing. I will let you know when we make the updates and share with your team. Feel free to make any suggestions for improvement.

**Comment by shiragoodman** [comment]
@CherylEvans and @shiragoodman will collaborate on this since she is making changes to the template per ticket #40713
