### ISSUE TITLE
Notice of Disagreement | V2 endpoint integration 

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#41350]
## Value Statement
**_As a_** Developer
**_I want to_** Research extending the backend to support the Lighthouse V2 endpoints for Notice of Disagreements (NOD)
**_So that_** I understand how to leverage the data available in the new endpoint. 

## Background Context
https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current#operations-tag-Notice_of_Disagreements

## Acceptance Criteria
- [x] add NOD V2 to `vets-json-schema`
- [x] create a new Service in `vets-api`
- [x] create new controllers for interacting w/ the new Service
- [x] add routes for the new controller's actions

## Tasks
- [x] Spend some time with @michelpmcdonald reviewing the existing Notice Of Disagreement (NOD) endpoint code and discussing this new endpoint.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by scottymeyers** [comment]
Bring this up with @saderagsdale as something to focus on in one of the next sprints.

**Comment by saderagsdale** [comment]
Action items:
- Scott to assign to others as needed to pair.

**Comment by scottymeyers** [comment]
I've created 2 new tickets related to discoveries whilst working on this ticket:

1. https://github.com/department-of-veterans-affairs/vets-website/issues/21426
2. https://github.com/department-of-veterans-affairs/vets-website/issues/21428
