### ISSUE TITLE
Migrate call to endpoint /submit from eVSS to lighthouse -526ez

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#41353]
Pending discovery ticket

## Issue Description
Form 526 currently calls EVSS.submit_all_claim endpoint for submitting claims via vets-api. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.

## Need To Know
- [ ] Lighthouse team Dash is working on this and expects to have it ready for integration test by April 2023
- [ ] Team Dash contacts - https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1674666875176/5bffb27d080685913fc74b5e4e2179511e4c2089?sender=ub46ab2ca03c3ddd9a8ac0157

---
## Tasks
- [ ] Technical discovery to understand where the change needs to be made and how it will be tested
- [ ] Update call to LH endpoint
- [ ] Create QA test plan
- [ ] Integrate Testrail if not already integrated?
- [ ] Send executed test scripts to the QA team

## Acceptance Criteria
- [ ] The call to endpoint /submit is migrated to the Lighthouse API
- [ ] /submit functionality does not change (need to understand what part of the submission uses this API and how it functions today)
- [ ] QA completed successfully and artifacts submitted to the QA team (Do we need to integrate with Testrail first?)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@michelpmcdonald Do you know the cutoff date for this switch? If not no worries, can talk to the LH team about it.

**Comment by michelpmcdonald** [comment]
No, I don't recall hearing the cutoff date.  They(EVSS-Lighthouse) seem to be working on the "simpler" services now

**Comment by saderagsdale** [comment]
Michel to talk to LH on 6/23

**Comment by ahay-agile6** [comment]
Notes:
- `settings.yml` has a `lighthouse` configuration section around line 1070.
- add "`form526`" section to `lighthouse` configuration section? this will have the different endpoints mapped out, akin to the `veterans_health` configuration
- need a base `url`, and perhaps other configurations for the different paths, i.e. /getPDF, /submit
-

**Comment by ahay-agile6** [comment]
more notes:
- vets-api submit form api endpoint  https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/postSubmitFormV2
- CST team epic for migrating to LH api: https://github.com/department-of-veterans-affairs/va.gov-team/issues/48118

**Comment by navaeddie** [comment]
Interesting comment I found on Slack thread:

> For the most part, vets-api 526 Submission is a thin wrapper around the much more complex EVSS 526 Submission(where the actual submission is orchestrated over even more systems(VBMS, BGS, etc))

https://dsva.slack.com/archives/C5AGLBNRK/p1659127863764369?thread_ts=1659123235.751139&cid=C5AGLBNRK

**Comment by RakshindaAslam** [comment]
Old ticket. Replaced with a set of Submit migration tickets
