### ISSUE TITLE
BE - Auth Exp - Onsite Notifications - JWT Authentication Updates

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#41357]
## Background
Work with Evan Parish and Kyle MacMillan to configure API keys.

Evan and Kyle (from VA Notify) brought up a valid concern over the authentication process that is currently in place for onsite notifications.

In short, some additional fields need to be added to the token that is used to authenticate requests to the vets-api.

## Tasks
- [ ] Add public key to configuration [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2#L403).
- [ ] Update controller code [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/onsite_notifications_controller.rb#L49).
- [ ] Add JWT checks for `issued at` and `expiration`
- [ ] Update documentation

**Comment by tpharrison** [comment]
Closing out this ticket - didn't realize that Erica already created one - https://github.com/department-of-veterans-affairs/va.gov-team/issues/41268
