### ISSUE TITLE
Update `component-library` imports

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41355]
## Background
Some of our imports to component in the `component-library` package are incorrect. We need to update these imports

## Considerations
* `CONTACTS` import should be  `import { CONTACTS } from @department-of-veterans-affairs/component-library/contacts`
* `react-bindings` imports should be from `@department-of-veterans-affairs/component-library/dist/react-bindings`

## Tasks
- [ ] Update `CONTACTS` imports
- [ ] Update `react-bindings` imports

## Acceptance Criteria
- [ ] A PR has been requested for merging

**Comment by saderagsdale** [comment]
@jacobworrell @jerekshoe is this code work in progress?

**Comment by jerekshoe** [comment]
I started working on this yesterday. I'm currently having issues with zenhub, I'm not currently able to access the VFT workspace so I can only close tickets atm
