### ISSUE TITLE
gibct-data-service repository Ruby and Rails updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4136]
## Background
Historically development of GIDS has been sporadic. As a result, a GemFile dependencies have not been updated with regularity.  Since development has increased in order to support Colmery it now makes more sense to update GIDS repository dependencies.

## Plan
We will communicate and work with our VFS teams to ensure a smooth transition to the newer dependencies.  Here is the high level plan for the transition:

### Priority
- [x] Reorganize & Remove GemFile to have a similar structure to vets-api repository #19577
- [x] Change factory_girl to factory_bot #19576
- [x] Create a process to test as if on staging #19575
- [x] Update Ruby to [vets-api's Ruby version](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.ruby-version) #19606 
- [x] Update Rails to [vets-api's Rails' version](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Gemfile) #19605 & #19615 & #19616

### Nice to haves
- [x] Use property [`StrongMigrations.target_postgresql_version`](https://github.com/ankane/strong_migrations#target-version) with value of `9.2` which is the version of postgresql on Dev/Staging/Production for gibct-data-service. #19601
- [x] Update security rake task to use latest gems and fix issues discovered by task #19786 
- [x] [Change from `=~` to `match?`](https://www.rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Performance/RegexpMatch) #19787
- [x] Switch from PGconn, PGresult, and PGError to PG::Connection, PG::Result, and PG::Error instead, respectively.
- [x]  Update factory_bot to latest version, [requires fixing factories](https://github.com/thoughtbot/factory_bot/commit/50eeb67241ea78a6b138eea694a2a25413052f49) #19788
- [x]  Update `sass-rails` because Ruby Sass has reached end-of-life and should no longer be used #19789
- [x]  Update sentry-raven to same version as vets-api #19790
- [ ]  audit validations.  I mention this because I know that the `Institution` model has the following: `validates :facility_code, uniqueness: true, presence: true`.  This validation will fail every time since it’s not scoped to `version`.
- [x] Audit and remove `rubocop:disable` usages that can be removed without requiring a major refactor of existing code #19791
- [ ] Address rubocop offenses listed here: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/.rubocop_todo.yml #19831 #19833
