### ISSUE TITLE
[FE] View Mixed Language Disclaimer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41374]
## User Story
As a Spanish-speaking Veteran, when I choose to see the Pre-Check-in or Check-in content in Spanish and there is some English content on the page, I would like to see an acknowledgement of the mixed language so that I will not think it is an error.

## Assumptions
We will use 1 feature flag per non-English language to control whether the language contains some English or not

## User Workflow
- Given I
    - Click my Pre-Check-in or Check-in link
- When I
    - View any page
- Then 
    - If I have chosen to view in a language other than English
        - I will see a message, in the language chosen, that indicates that some content may be in English
    - If I have chosen to view in English
        - I will not see this message
  
## Wireframes
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/122a87e4-b6ba-4095-b4ad-ca2281f8f482)

## Tasks
- [x] [FE] Make disclaimer message visible when any page contains mixed language
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [x] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
![Screen Shot 2022-06-08 at 1.25.01 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/8c4f7a02-b20f-40fb-aeda-6749ec0a767b)

**Comment by brdunfield** [comment]
![Screen Shot 2022-06-08 at 1.29.15 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/6fc66c3f-e618-4ace-863d-0a4b1d3bff01)

![Screen Shot 2022-06-08 at 1.28.40 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/3776f8a2-1608-47cf-a50e-a459ead56275)

![Screen Shot 2022-06-08 at 1.28.31 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/884f7410-12e6-4209-b77c-fa9234240c4c)

![Screen Shot 2022-06-08 at 1.28.15 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/889d2335-4329-4f65-b2c1-da22f4e637f2)

**Comment by brdunfield** [comment]
@zach-park I've attached some screenshots above for validation (variety of pages with and without the back button)

**Comment by loripusey** [comment]
@brdunfield Can you replace the Spanish content with the following that came from the round 2 translations?
"Parte del contenido podría estar en inglés."

cc: @kristenmcconnell @acrollet @sarahknoppA6

**Comment by zach-park** [comment]
@brdunfield , they look great. Thank you!

Just some nit-picks (although I don't believe they were part of the scope, I wanted to mention them for possible future work) in some styling items were inconsistent (documented in links below):
- Contact Info: https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/088330DE-0108-4FFF-82C4-056A521C3B34
- Verify ID: https://www.sketch.com/s/5a0f7c7f-df7c-4506-b4f9-c003321595fe/a/uuid/FB072960-76B1-449D-B18A-CE5E3E64247D

**Comment by brdunfield** [comment]
![Screen Shot 2022-06-08 at 2.07.21 PM.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/8f02c0f1-74ca-4812-aee5-58fd402f4ce4)

Repeating here so it's not lost in slack: Content change implemented! For the other comments - I feel those would be best tracked in separate tickets as they don't fall under the scope of this one as far as I can tell.

**Comment by loripusey** [comment]
I'll create tickets for the other changes
