### ISSUE TITLE
[Research] Create Research Plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41380]
## User Story
As a team, we would like to conduct a research study to determine how the Pre-Check-in and Check-in features are being used in the field and how they might be enhanced in the future.

## Related Documentation
- 

## Description
- Create a research plan of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
    - List out items...

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria
- [x] Review research plan with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan to GitHub folder
