### ISSUE TITLE
Add link on VA.gov CRSC page to the Navy CRSC website

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#41385]
## Issue Description
Stakeholder Timothy Sidbury, PM and president of the CRSC Board for the Navy, sent us a link to the Navy page that summarizes Navy CRSC and announces the Navy CRSC mobile app. We need to link to it from our R&S article.

---
## Tasks
- [ ] Add this text link to the [CRSC](https://www.va.gov/resources/combat-related-special-compensation-crsc/) page: 
[Learn more about CRSC and the Navy CRSC mobile app from the Nav website](https://www.secnav.navy.mil/mra/CORB/pages/crscb/default.aspx)

Place it below this address in the last accordion in the first group of accordions on that page, like this (see how we did something similar in the Coast Guard address accordion):
Secretary of the Navy
Council of Review Boards
Attn: Combat Related Special Compensation Branch
720 Kennon Street SE, Suite 309
Washington Navy Yard, DC 20374-5023

[Learn more about CRSC and the Navy CRSC mobile app from the Nav website](https://www.secnav.navy.mil/mra/CORB/pages/crscb/default.aspx)

## Acceptance Criteria
- [ ] New text link is live.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aliyahblackmore** [comment]
As requested, new link was added to the CRSC page under the last accordion in the first group of accordions on that page. @megzehn this is ready for you to review!

**Comment by megzehn** [comment]
Change looks good. I reviewed and published. @RLHecht this is ready for you to close out.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
