### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41391]
## User Story
As a team, we would like to conduct a research study to determine how the Pre-Check-in and Check-in features are being used in the field and how they might be enhanced in the future.

## Related Documentation
- 

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [x] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize conversation guide to GitHub folder

**Comment by benbrasso-agile6** [comment]
https://app.powerbigov.us/groups/me/apps/7b632b7f-6fba-4a5e-8be2-805b999b1a57/reports/648acdf7-00ba-4aa1-9a25-3efd1ad69405/ReportSectionb86d7b406971f678acc4?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&bookmarkGuid=Bookmark3adb2c614c87a8233d21

Add powerbi

**Comment by benbrasso-agile6** [comment]
Update based on Clayton's feedback from platform

**Comment by benbrasso-agile6** [comment]
Finished clayton's updates

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/bay-pines-in-person/conversation-guide.md

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/bay-pines-in-person-uat/conversation-guide.md
