### ISSUE TITLE
[Research] Create Study Report

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41392]
## User Story
- As a product team, we want to document and share the findings from the June 22 study.

## Related Documentation
- 

## Description
A research report detailing findings and design recommendations from the June 22 study.

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [x] Conduct the [inclusive design analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/risk-documentation.md)

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [x] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [x] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with
    - [x] Stakeholders (talk to Patrick about when to do this)
    - [x] Team (either via Slack or Zoom meeting)
    - [x] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by benbrasso-agile6** [comment]
@loripusey I'm going to see if I can grab time with you tomorrow to review this - https://docs.google.com/presentation/d/1Y8JFwpkY85blzt1IvKx-35AZ9FaaYBdoGrFONK-vPfs/edit?usp=sharing

I just have a couple set-up slides that i still need to add. But, feel free to review if you'd like. 

@kristenmcconnell FYI, I made the updates that we discussed

**Comment by benbrasso-agile6** [comment]
Finished these

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/bay-pines-in-person/research-findings.md

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/bay-pines-in-person-uat/research-findings.md

Just need to post to research repo and message lori about change I made to recos, e.g., pre-check-in name change.

**Comment by loripusey** [comment]
**### Co-work with VeText/CHIP:**
- Add a "check in now" message from VeText/CHIP delivered 30 minutes before the appointment.
    - [Deliver "Check-in Now" Message 30 Minutes before Appointment](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44395)
- Explore creating a test to send a pre-check-in reminder text (via VeText/CHIP), if not completed.
- Explore adding appointment time to CHIP response when Veteran is too early for check-in.
    - [Revisions to "Too Late" or "Too Early" check-in status Wording for SMS Messages](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/37338)
- Explore adding information related to being too late for check-in to CHIP response when Veteran is too late for check-in.
    - [Revisions to "Too Late" or "Too Early" check-in status Wording for SMS Messages](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/37338)
- Explore removing, "We're sorry," from CHIP response when a Veteran needs their health insurance reviewed to avoid possible Veteran concern or frustration.
    [Revisions to Message for Health Insurance Review Needed](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44241)

**### Vet-facing Team:**
- Test a stepped form design for check-in with Veterans as a way to better communicate the remaining steps.
    - [Stepped Form Design for Check-in and **Pre-Check-in](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44181)
- Add a link on the pre-check-in confirmation page for Veterans to learn about how to check in on the day of their appointment.
    - [Add Check-in Process Info to Pre-Check-in Confirmation Page](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44392)
- Explore new naming convention for “pre-check-in” that doesn’t include “check-in.” Specifically, draft new ideas and document usage across Veteran and staff-facing applications. Consider how pre-check-in may be perceived by Veterans once new functionality is introduced and considered more valuable compared to current state. E.g., health questionnaires, editing information and medication review.
    - [Explore Clearer Naming for **Pre-Check-in](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44393)
- Research if there’s any known QR code bugs associated with text messages not populating.
    - [[SPIKE] [BUG] Research if there’s any known QR code bugs associated with text messages not populating](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44239)
