### ISSUE TITLE
[BRD] Use Puma vets-api /stats endpoint for healthchecking

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#41406]
## Description
As pertaining to the following PR https://github.com/department-of-veterans-affairs/vets-api/pull/9565

the biggest problem being 

- There is an issue where if puma threads are full, the instance is regarded as unhealthy by the load balancer and recycled by the autoscaling group.

---
## Tasks
- [ ] update vets-api terraform module to point at new port https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vets-api/blob/ffd88e57bf4a05125c781c3c472b222c7f86c881/main.tf#L93-L99
- [ ] open new port in the docker arguments for vets-api in dev https://github.com/department-of-veterans-affairs/devops/blob/280cfe6905f48ec46dc6cd0823eeaf51b98cc820/ansible/deployment/config/vets-api-server-vagov-dev.yml#L70
- [ ] deploy new vets-api configuration to dev
- [ ] update vets-api terraform module in dev and apply https://github.com/department-of-veterans-affairs/devops/blob/280cfe6905f48ec46dc6cd0823eeaf51b98cc820/terraform/environments/dsva-vagov-dev/main.tf#L229
- [ ] if all goes well, repeat for remaining environments

## Acceptance Criteria 
- [ ] vets-api servers are no longer cycling due to failing health checks

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
putting on hold due to concerns from the backend team

**Comment by mleclerc00** [comment]
closing for the time being
