### ISSUE TITLE
Update MHA payments content connected to June 1, 2022, date on 2 pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41405]
## Issue Description

We currently have information on our [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#benefit-payments-claims-claim-) page and our [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) page explaining that if classes were changed to online, Veterans will continue to receive the same monthly housing allowance payments they received for resident training until June 1, 2022, or until their school resumes normal operations.

We need to reach out to stakeholder Louiseza Sanderson, the POC for this request originally to see if there has been an extension. If not, we need to update this language and publish changes on June 2, 2022, so that this information isn't outdated. 

## Tasks
- [x] Reach out to stakeholder about date 
- [x] Update content
- [x] Review changes
- [x] Send to stakeholder for approval 
- [x] Send to Danielle for final review
- [x] Publish content
- [x] For COVID FAQs, set up translation ticket
- [x] Notify stakeholder that changes are live

## Acceptance Criteria
- [x] Content is update on live pages

**Comment by RLHecht** [comment]
Going back through emails from when we first needed to make these updates in December, we had language that the stakeholders had approved to put on the FAQs page. I confirmed that we are still good to use this language with a few adjustments. Here is is:

**If you’re taking online classes**

**If your school or program offers approved online classes or training,** you’ll continue receiving GI Bill benefits automatically. You don’t have to do anything.

**Note:** To help students affected by the COVID-19 pandemic, we paid in-person (called “resident”) monthly housing allowance rates if you were enrolled in online classes from March 1, 2020, to June 1, 2022. As of **June 2, 2022**, your monthly housing allowance payments will change back to the online rate. The online rate is half the national average.

**If your school or program doesn’t offer approved online classes or training,** you’ll need to return to in-person classes to continue receiving GI Bill benefits. This begins on **June 2, 2022**.

We’re working closely with schools to ensure enrollments are accurately certified and processed.


We'll still need to look at the Post-9/11 page to determine the language that needs to be added.

**Comment by katherine-fung** [comment]
@RLHecht I've looked at the post-9/11 page and it does need updated language to reflect changes starting 6/2/2022.

The proposed changes are in bold: 

- If you’re taking online classes. We’ll pay a housing allowance based on 50% of the national average.

**Note: To help students affected by the COVID-19 pandemic, we paid in-person (called “resident”) monthly housing allowance rates if you were enrolled in online classes from March 1, 2020, to June 1, 2022. As of June 2, 2022, your monthly housing allowance payments will change back to the reduced rate for online classes.** 

The campus location where you physically attend most of your classes. We call this a “location-based housing allowance.”
Note: If your school changed to online classes because of COVID-19, **we paid the same MHA payments you received for in-person classes until June 1, 2022. 
If your school or program doesn’t offer approved online classes or training, you’ll need to return to in-person classes to continue receiving GI Bill benefits. This begins on June 2, 2022.**

**Comment by laurwill** [comment]
Thanks @katherine-fung !

For the COVID FAQs page, I made the changes in Drupal and adjusted header levels in that section to make sure it was scannable. I also adjusted the verb tenses from "will change" and "begins" on June 2 to "changed" and "began" since we're publishing this on June 2. Here's the Drupal preview for when we're ready to post these for Danielle. http://preview-prod.vfs.va.gov/preview?nodeId=3014

For the [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) page, I'm suggesting a slight tweak — Danielle clarified that the MHA rate change for online classes only applied to schools that switched to online due to COVID, not to schools that were always online. So I tried a single note under that bulleted list that can apply to both of the last 2 bullets. 

Here's a screenshot since you're not in Drupal yet! See what you think of this approach.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/104158104/170366691-0d651ad2-666a-49c1-a857-019e5b91505a.png">

One remaining question is whether we need to add a note or alert on this page to call out the change as it applies to GI BIll benefits more broadly, not only to MHA payments. Could you take a look at the page as a whole and see if there's a natural place to add a more general note about needing to be in approved online classes or go back to in person? We can also hop on zoom and look together if that's easiest!

**Comment by katherine-fung** [comment]
Thanks @laurwill. I think those tweaks make a lot of sense! 

Looking over the page as a whole, I think it makes sense to have an alert at the top of the Post 9/11 GI Benefits page (before or after the existing alert about verifying enrollment) about the changes taking effect June 2. 

Here's suggested language: 

Special COVID-19 rules for GI Bill benefits expired on June 1, 2022. 

If your school closed, changed to online classes or made certain changes because of COVID-19, you may have been eligible to continue getting certain GI Bill benefits between March 1, 2020 and June 1, 2022. These rules have changed. As of June 2, 2022, you must return to in-person classes if your school or program doesn't offer approved online classes, in order to receive GI Bill benefits.

Learn more about the changes that took effect June 2, 2022 [https://benefits.va.gov/gibill/covid19educationbenefits.asp]

**Comment by laurwill** [comment]
Hi @megzehn , tagging you for a copyedit before we send these updates to stakeholder for approval! Danielle confirmed we can send without her review. 

Also noting here that on delivery we'll ask Louiseza to confirm whether the "If your school is in session, but you can’t attend due to COVID-19" section on the FAQs page applies after June 2.

**Comment by megzehn** [comment]
These look good!  Copyedited. Back to you @laurwill?

**Comment by laurwill** [comment]
Thanks Megan! I sent the preview links to Louiseza for approval before publishing.

**Comment by laurwill** [comment]
Update: Louiseza approved all draft changes and confirmed that "If your school is in session, but you can’t attend due to COVID-19" provision also ended today. 

I updated to reflect that change and sent that update back for an accuracy check — we can plan to publish this for 9a.m. tomorrow, and update quickly again if Louiseza responds after publish with change requests.

**Comment by laurwill** [comment]
Randi copyedited those last changes on the FAQs, and I publish both the FAQs page and the GI Bill page before the 9am release — leaving this open until we hear back from Louiseza.

**Comment by RLHecht** [comment]
These changes are now live and I've set up the translation ticket. Going to close this ticket and if Louiseza has revisions we need to make we can reopen. Thanks for working through all the last-minute changes!
