### ISSUE TITLE
10-10EZ: Improve Household information section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#41403]
## Background
In an effort to improve and optimize the flow of the 10-10EZ form, and address pain-points and drop-off rates, we want to look at reorganizing the 5 parts within the Household section
- Financial Disclosure
- Marital Status
- Spouse's Information & Dependents
- Annual Income
- Deductible Expenses

## Outlines
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Health%20Care%20Application%20-%20Product%20Outline.md)
[Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/ReadMe.md)

## High Level User Story/ies
As a health care applicant, I need to proceed through the application easy and confidently so I will be better prepared to complete the application the first time without interruption or having to save & finish later

## Hypothesis or Bet
**If** _optimize the questions per page and reorganize the question flow _ **then** _we expect applicants will be better prepared to move through the section easily_.

## OKR
Objective: Update the 10-10EZ, so it is easier for applicants to understand and complete without having to exit the application.
**Key Result # 1:** Reduce drop-off/exit rate for the Household section pages by a third.
**Key Result # 2:** Increase application submissions by 4%, and submissions within a single session by 5%
**Key Result # 3:** Veterans feel prepared when they begin the Household section
**Key Result # 4:** Veterans understand what is being asked of them and why, feeling comfortable in providing the information.
**Key Result # 5:** Reduced call center complaints on the Household section of questions

### What must be true in order for you to consider this epic complete? 
The Household section will have a logical flow, a low cognitive load and lowered exit rates on those pages.

# PM Checklist

## List your team, project contributors, and reviewers
<details>

### Product Team
- OCTO-DE Product Lead: Patrick Bateman
- Product Manager: Heather Justice
- FE Engineer: 
- BE Engineer: Lihan Li
- Design/Research: Nick Osmanski, Jessica Stump
- Slack channel: # 1010-health-apps
- GitHub tag: household-info-optimization

</details>

## List of project artifacts for requests

<details>

- Project epic #41403
- [10-10EZ Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Health%20Care%20Application%20-%20Product%20Outline.md)
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/ReadMe.md)
- Whiteboard sketch or other lo-fi prototypes or [wireframes](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/AE225764-D5BB-4CE6-9577-38E8F570392B/canvas)
- [User flows](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas) (same as final design) 
- [Research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Conversation%20Guide.md)
- [North Star and KPIs for the product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Health%20Care%20Application%20-%20Product%20Outline.md#new-okrs-from-2022-workshop)
- Product URL(s) - [Veteran's health care application](va.gov/health-care/apply/application/introduction)
- [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md)
- Finalized design [UXPin prototype](https://preview.uxpin.com/6a98bfd8c3a76816b8695fbdc6883bd477610024#/pages/159024257) or [Sketch mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- Content brief
- TestRail 
     - [Test Cases/Plans](https://dsvavsp.testrail.io/index.php?/runs/view/4540&group_by=cases:section_id&group_order=asc)
     - [Regression test plans](https://dsvavsp.testrail.io/index.php?/runs/view/4303&group_by=cases:section_id&group_order=asc)
     - [Accessibility test plan](https://dsvavsp.testrail.io/index.php?/runs/view/4420&group_by=cases:section_id&group_order=asc)
          - [Accessibility Test results artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58694)
- [End-to-End testing confirmation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/E-2-E%20testing%20confirmation.md)

- [Technical diagrams](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/engineering) (architecture diagram, sequence diagram)
- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Product/Household%20section%20optimization%20-%20Release%20Plan.md)
- Product guide for contact center

</details>
     
## List of process steps

<details>

- [x] Create Initiative Brief with the Problem Statement and as many details known
     - [ ] Update the Initiative Brief after each step with links to the artifacts and more details known
- [x] Discovery
     - [x] What is the problem to be solved
     - [ ] What solutions have been made (internal or external) to resolve this problem
     - [ ] What are the possible solutions
     - [ ] How would they solve the problem
     - [ ] What are the efforts involved (time, design, technical)
     - [ ] What is the ROI potential for each solution
     - [x] Does the solution require engagement with downstream system
          - [n/a] Is there a data change, and can the downstream system accept the data?
- [x] Create Epic and corresponding stories to align with the work needed (start with this list!)
- [x] Initial design
     - [x] Lo-Fi design ideas
     - [x] Presentation and agreement with the team on direction
          - [x] Confirm Frontend and Backend efforts
     - [ ] Presentation to Stakeholders and downstream system representatives
- [x] Submit Collaboration Cycle request ticket
     - [x] Review Collaboration Cycle site
     - [x] Start gathering artifacts (list above)
     - [ ] Maintain this checklist of artifacts, updating as they are shared
- [x] Schedule Design Intent review - Refer back to the initial Collaboration Cycle Request ticket
     - [x] Present design and obtain feedback
- [ ] Sign up for a Product Review session to present the initiative (after Design Intent)
- [x] Request Content & IA review - Refer back to the initial Collaboration Cycle Request ticket
- [x] Finalize design with feedback
     - [x] Present to team, stakeholders and any other interested parties
- [x] Create prototype or basic working functionality in environments
     - [x] The team can determine the best path, used for research
- [x] Create Research Plan and Conversation Guide
- [x] Schedule Midpoint Review - Refer back to the initial [Collaboration Cycle Request ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/47766)
     - [Midpoint Review Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Product/Midpoint%20Review%2011-28-2022.md)
- [x] Request Research Review - Refer back to the initial [Collaboration Cycle Request ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/47766)
- [x] Schedule research sessions with Perigean
- [x] Conduct research sessions
     - [x] Synthesize research findings
     - [x] Review findings with the team
     - [x] Make any necessary tickets/changes for design
- [x] Create Use Cases
     - [x] Identify test users
- [x] Create Release Plan
     - [x] Include E2E test results & signoff
- [x] Complete development
     - [x] Engineers work with Designers on any questions/clarifications
     - [x] Present to team for validation
     - [ ] Present to Stakeholders for validation
- [x] Create [QA ticket](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/51641) and coordinate with the team (based on Dev ETA)
- [x] Engage downstream system team for End-to-End QA coordination
     - [x] Create [E2E use cases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51642)and document results
     - [x] Obtain [signoff from downstream system team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/E-2-E%20testing%20confirmation.md)
- [N/A] Request Analytics review - Refer back to the initial Collaboration Cycle Request ticket
- [x] Complete [QA](https://dsvavsp.testrail.io/index.php?/runs/view/4540), [Regression testing](https://dsvavsp.testrail.io/index.php?/plans/view/4298) and [Accessibility QA](https://dsvavsp.testrail.io/index.php?/plans/view/4419)
     - [x] Complete QA with feature toggle enabled and disabled to confirm toggle effectiveness (Reference [Testing process notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Testing%20with%20the%20Feature%20Toggle.md))
- [x] Request Staging Review - Refer back to the initial Collaboration Cycle Request ticket
     - [x] Review findings with the team
     - [x] Create tickets for work to be completed before launch
- [x] Create Usability and/or UAT research plan and conversation guide
- [x] Request Research Plan review
- [x] Request Platform Security, Privacy and Infrastructure review (template)
- [x] Update Error matrix documentation with any new error states
- [x] Update any FE and/or BE Engineering documentation
- [x] Request Privacy, Security, Infrastructure readiness review - Refer back to the initial Collaboration Cycle Request ticket
- [x] Update Contact Center guide
- [x] Submit Contact Center guide review ticket
- [x] Update Release Plan
     - [x] Include E2E test results & signoff
- [ ] Schedule or close all remaining tickets
     - Some tickets may be backlogged for future work, as they were not required to launch
- [x] Review this checklist for any missing artifacts
- [x] Conduct Launch Go/No Go with the team
     - [x] Review this [checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Product/Launch%20Go_No%20Go.md)
     - [x] Review [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Product/Household%20section%20optimization%20-%20Release%20Plan.md)
- [x] Launch in a phased manner, according to Release Plan
- [x] Continuous check-ins with downstream system
- [x] Conduct Usability/UAT sessions
     - [ ] Review findings with the team
     - [ ] Make any necessary tickets for future design and/or development
- [x] Submit 508 Accessibility Audit request
     - [N/A ] Create tickets to address findings, if any

</details>

**Comment by hdjustice** [comment]
@markfallows - I added the checklist to this epic so we can keep track of where we are in the process

**Comment by hdjustice** [comment]
This feature is complete
