### ISSUE TITLE
Convert fwdproxy port to Kong to HTTPS

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41418]
## Issue Description

Currently, the new fwdproxy port that routes to Kong is configured to use `http`. This was meant as a temporary configuration until we start using Apigee as the backend. However, since `vets-api` sometimes hard-codes the protocol as `https`, it would be better to configure even this temporary port to Kong to use `https`. 

---
## Tasks
- [x] Change fwdproxy port 4492 configuration to use https
- [x] Change vets-api setting that already use the fwdproxy to use https
- [ ] Ensure routes are working

## Acceptance Criteria
- [ ] New fwdproxy configuration changed to https and validated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
Currently there is an issue with the EKS version of `vets-api` in that there is a 503 service unavailable error when curling an endpoint that would make a second API call to LH using a new fwdproxy port that first goes to Kong:

```
Internet —> RevProxy —> vets-api (EKS) —> fwdproxy:4492—> Kong —> fwdproxy:4451 —> Lighthouse
```

Curl command that returns a 503: `curl https://dev-api.va.gov/facilities_api/v1/va/vba_354b`
If we force the traffic to go to the EC2 version of `vets-api` outside of EKS, the call works (well, it doesn’t but the authentication error indicates it reaches Kong):
```
Internet —> RevProxy (w/ x-forward-brd-vets-api header) —> vets-api (non-EKS) —> fwdproxy:4492—> Kong —> fwdproxy:4451 —> Lighthouse
```
This curl returns a 401 but that indicates the call reached it’s destination in Kong: `curl -H 'x-forward-brd-vets-api:true' https://dev-api.va.gov/facilities_api/v1/va/vba_354b`

The new fwdproxy port to reach Kong as a backend has been successfully set up:
`curl -G -s -k --socks5-hostname localhost:2001 'https:/fwdproxy-dev.vfs.va.gov:4492/services/meta/v0/ping'`

The Infra team suggested that the issue is likely differing configurations between the BRD version of vets-api and the one in EKS. Rails logs indicate that the [self-signed cert for the fwdproxy might be the issue](https://app.datadoghq.com/apm/resource/vets-api/rack.request/5618347e925ad52a?query=env%3Adevelopment-k8s%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22FacilitiesApi%3A%3AV1%3A%3AVAController%23show%22&env=development-k8s&event=AgAAAYDib-u48QMHrAAAAAAAAAAYAAAAAEFZRGliX2JOQUFEamRMOUNmM0E2dy1nMQAAACQAAAAAMDE4MGUyNzAtMWE0Mi00OWY1LTkwZDktYmJlMGIzZWY1YmFi&spanID=10955316359070279&timeHint=1653066427320&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&traceID=3884630307102659022&start=1653062832361&end=1653066432361&paused=true). There is an open issue of the infra team #41253 to verify configs between the BRD and EKS versions of vets-api. We will be monitoring the issue and finalize this work once we can confirm equivalent configurations between the two environments.

**Comment by patrickvinograd** [comment]
Wrapping my head around this...the 401 from the dev Kong instance makes sense...because all the vets-api services are configured with *sandbox* Kong API keys - and API keys are per-environment. So that raises the issue that pointing to dev Kong is not equivalent to pointing to sandbox-api.va.gov - it's a totally different environment. 

I was trying to see if I could ping a sandbox-api-gateway.vfs.va.gov endpoint from the dev environment, but it does not respond. I'm not sure if that's a security group or VPC peering issue or what, but I think that would be the more proper equivalent to what the original config was.

**Comment by patrickvinograd** [comment]
Looks like the sandbox API gateway's load balancer has a security group configuration that doesn't allow inbound connections from other VPCs (which makes sense, because typically other VPCs would access via sandbox-api.va.gov, aka via the revproxy).

**Comment by madebydna** [comment]
About the 401 from the dev Kong instance: the `vets-api` config does _not_ use the sandbox address, but the new fwdproxy address that goes to the _dev_ version of Kong. See [vets-api BRD config](https://github.com/department-of-veterans-affairs/devops/blob/ae77ccd50a8146713e75df1c79c0b66b787bf091/ansible/deployment/config/vets-api/dev-settings.local.yml.j2#L626) and [vets-api EKS config](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/1148a1e7cf49a6840678fd33903784d9a559d381/apps/vsp-tools-backend/vets-api/dev/settings-configmap.yaml#L650). Here it gets confusing:

The API key settings in the EKS version of vets-api have been updated to be the API key for the **dev** environment (this actually required setting up vets-api as a client in the dev environment, which is something the LH team helped me with).

The API key setting in the BRD version of vets-api have _not_ been updated. For one, I didn't know how to update the credstash-based configs, and also this is no longer the version that traffic gets directed to by default. I can certainly take care of that, though, just so we have parity.

**Comment by patrickvinograd** [comment]
Got it...I can help update credstash if that's helpful, but also if we do this across more APIs than just facilities, it represents a potential change in expected data for VFS teams, something to be aware of.

**Comment by madebydna** [comment]
> it represents a potential change in expected data for VFS teams
I'm not sure what that means. Could you please explain? 

One thing that became clear is that using the sandbox API client/key in dev is a common pattern and goes beyond just the facilities endpoint. I actually went through the same steps of setting up a DEV client/key for the address validation endpoint. I haven't changed that config yet, but we do have the dev API key now. I asked LH if it's common that APIs are not available in all environments and Dina indicated that it is and that they sometimes don't even know which APIs are available in which environment:
> I think we will eventually need to write a script and figure out what API’s are in what envs since this is always evolving.  This will be a problem as we migrate over to Apigee to know what api’s are where.
https://dsva.slack.com/archives/C013VCQKSE7/p1652810181710729?thread_ts=1652380436.345979&cid=C013VCQKSE7

**Comment by madebydna** [comment]
> I can help update credstash if that's helpful

I'd like to know how that works, too but I can send you the DEV key on Keybase for now.
