### ISSUE TITLE
[Research] Draft research plan - Usability of redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41415]
## Issue description
This research initiative will evaluate the success of the VA.gov homepage redesign toward the following desired user outcomes 
- Veterans, caregivers, family members, survivors and service members are able to access tools and processes quickly and easily to learn about and manage their benefits
- Veterans, caregivers, family members, survivors and service members have increased access to self-service tools through an elevated login funnel

## Background
The current VA.gov website was launched in 2018 but hadn't been the subject of much user research until Baseline Wayfinding Research was conducted in June 2021.  Findings from that research were incorporated into the redesign. 

Research to discover the most important tasks to Veterans, caregivers, family members, survivors and service members will be conducted in the next month. Findings will influence the version used for this usability research. 

## Goal
The goal of this research is to validate that the new design has improved the usability of the homepage. Rather than focusing participant attention on individual homepage components, we will observe which areas they use and how well the homepage supported Veterans, VA beneficiaries and those acting on behalf of Veterans in the process of completing important benefit-related tasks. 

## Research questions 
The following questions will be answered in the context of task-based scenarios which will be informed by findings from Top Task research conducted in May/June 2022:
- Are participants able to easily and quickly initiate tasks from the homepage?
- What part(s) of the homepage do participants use for the task? 
- Does the homepage support participants, including those using assistive tech, in completing their tasks?
- Do the words/labels used on the homepage support participant understanding?
- What do Veterans (and others) expect from various areas of the homepage, including search functionality and VAntage Point blog promo?

## Areas of focus
We are primarily interested in the following areas of the homepage, in context with the header or footer, which may also provide a path for task completion 
- Login/signup CTA
- Common task list
- Search
- Benefit hubs
- VAntage Point blog promo

## Tasks
- [x] Draft research plan
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback

## Acceptance Criteria
- [x] Initial research plan drafted
- [x] Share with PM/PO for review
- [ ] Draft research plan available for review and use in Veteran User Research session for this initiative.

**Comment by cindymerrill** [comment]
Draft research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-plan.md

**Comment by cindymerrill** [comment]
Discussed research plan with @mmiddaugh, made revisions, shared with UX team for someone to take a look this week. I plan to revise it as needed next week since I'm out for PTO for the next 3 days.

**Comment by cindymerrill** [comment]
Research plan revised with feedback from UX team members and some followups from Michelle. Shared draft with Dave Conlon by posting in #sitewide-public-websites and @mentioned him.
