### ISSUE TITLE
Test dev-internal-api.vfs.va.gov from website locally

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41416]
## Issue Description
Using just http, the `dev-internal-api.vfs.va.gov` URL should already be accessible. We want to test it by changing one (or more) of the API urls on the React frontend website (repo name: `vets-website`). 

This would be a proof of concept that the new URL can correctly route traffic to the `vets-api` backend. Because the `dev-internal-api.vfs.va.gov` URL is an internal address, we would need to spin up a local version of the va.gov website and be connected to the SOCKS proxy to perform the test.

---
## Tasks
- [x] Spin up local version of `vets-website`
- [x] Find where backend API URLs are configured and change some to point to `dev-internal-api.vfs.va.gov`
- [x] Ensure data gets correctly returned and document results

## Acceptance Criteria
- [x] Documented test of new, temporary domain working as a backend URL for the va.gov website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
Documentation of local website setup with API URL change: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2238906516/Changing+the+API+URL+in+vets-website+repo+-+Local+setup
