### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41433]
## User Story
As a team, we would like to conduct a research study to determine how the Pre-Check-in and Check-in features are being used in the field and how they might be enhanced in the future.

## Related Documentation
- 

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize conversation guide to GitHub folder

**Comment by ytsaoca** [comment]
Draft: https://docs.google.com/document/d/17Vr8auOBWyWCYtFllmb5Ne5R0g19JoT0XSWAzY628RQ/edit

**Comment by niradatta1** [comment]
Link to conversation guide in git-hub here. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/Spanish/Conversation%20Guide.md. @ytsaoca to update based on recent updates we're making to the conversation guide in google docs (link above) 'cc @kristenmcconnell
