### ISSUE TITLE
[Research] Synthesize Research Findings

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41439]
## User Story
- As a product team, we want to know the findings from the July study.

## Related Documentation
- 

## Description
Analyzing the videos and notes from [research study name] to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Decide on analysis methodology (affinity diagramming, etc.)
- [x] Involve appropriate team members in analysis activity/meetings
- [x] Review all participant session notes and videos
- [x] Do analysis

## Acceptance Criteria
- [ ] Post synthesis documents to GitHUB
- [x] Write top-line summary (optional if daily summaries were sent out)

**Comment by kristenmcconnell** [comment]
[Veteran synthesis](https://app.zenhub.com/files/133843125/c38835c8-ab74-403a-afcc-6c537b3528d3/download)

**Comment by kristenmcconnell** [comment]
Posted to Github [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/corpus-christi-in-person/readme.md) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/staff-facing/corpus-christi-in-person).
