### ISSUE TITLE
[Research] Create Research Plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#41432]
## User Story
As a team, we would like to conduct a research study to determine how the Pre-Check-in and Check-in features are being used in the field and how they might be enhanced in the future.

## Related Documentation
- 

## Description
- Create a research plan of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
    - List out items...

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan to GitHub folder

**Comment by benbrasso-agile6** [comment]
Pulling over to see if I can pull a draft together so we can begin confirming trip with location

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell added plans here

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/corpus-christi-in-person/research-plan.md
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/corpus-christi-in-person/research-plan.md

Take a review before we discuss with Stephen.

Reassigning to Kristen, but I'll continue to support as needed.

**Comment by kristenmcconnell** [comment]
Made final changes to the plans based upon feedback from the check-in UX team. Send plans to Stephen Barrs in [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1656611646343989) to start conversations with the sites.
