### ISSUE TITLE
OCTO-DE final review and publishing of revised TSGLI article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41457]
## Issue Description
The content team reworked the [TSGLI article](https://www.va.gov/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/) in R&S to expand the scope to more than just contact information. That ticket is #35702.

This ticket is for Beth's review of the work and for the content team to send to the stakeholder, copy edit, and publish. 

## Tasks
- [ ] Review revised TSGLI article (Beth)
- [ ] Send to stakeholders (Laura/Randi)
- [ ] Copy edit with pre-publishing checklist (Megan)
- [ ] Publish article (Megan)
- [ ] Notify stakeholder that revised page is live (Laura/Randi)

## Acceptance Criteria
- [ ] Revised TSGLI article is live on the site

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
