### ISSUE TITLE
Walkthrough Findings - Staging Review

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#41466]
## User Story
As a VFS team member and Governance team member, I want clear and up to date documentation and guidance so that I can easily perform my role in the Collaboration Cycle.

- Intended Audience: VFS Team and Governance Team
- Desired Outcome: Updated documentation and templates
- Due Date: 

## Description
Tasks listed below are from our [Core CC Walkthrough session notes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2183757962/Notes+-+Core+Collaboration+Cycle+ticket+Walk-through)
Remaining open Opportunity statements are also noted. 
[Research Findings spreadsheet (Pre Launch Improvements tab)](https://docs.google.com/spreadsheets/d/1_EGjrHtr3gEam72K4zEoFMdkQLBIvIjQ_lmes-RgWLw/edit#gid=1309674612)

Additional background for [Collaboration Cycle - Improve tracking and status visibility of VA.gov products](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/34697) initiative <br />

## Artifacts Needing Updates
[Platform Website: Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167734305)
[Kickoff Ticket Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/briandeconinck-core-cc-ticket/products/platform/vsp-collaboration-cycle/core-collaboration-cycle-ticket.md)
[Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274432)
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241650)
[Original Staging Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md)

## Tasks
- [ ] [Cheryl - Copy of Staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167734305) & [Platform Website: Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) - Clayton
  - [ ] Moderator Script - Update line "if QA does not have feedback to comment", should change to be in alignment with other practice areas. Checkbox confirming completed review in relevant touchpoint
  - [x] Attendees - Add IA to Platform Participants
  - [x] Artifacts
    - [x] Make artifacts match alignment in the ticket. Make match in order/grouping/content
    - [x] "Platform brings..." Remove this line

  - [x] FW: Remove "If QA not have feedback, they will mark the checkbox...."
  - [x] FW: Request: Match DI and MPR
  - [x] FW: Outcome Change "linked to staging review epic" to "Collaboration Cycle Request"

- [ ] [Kickoff Ticket Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/briandeconinck-core-cc-ticket/products/platform/vsp-collaboration-cycle/core-collaboration-cycle-ticket.md) - Chase
    - [x] Opportunity Statement: Link to Platform Website detailing needed information and updated artifact guidance
    - [x] Make artifacts align to documentation on Platform Website (noted above as well)
      - Added Content Artifacts section
      - Updated two outdated GitHub QA artifacts links
  - [ ] Post Meeting section
    - [x] Delete platform action "update platform tracker"
    - [ ] Change VFS action to "comment on this ticket"
    - [x] Need guidance on when VFS closes ticket
      - Do we need to provide extra guidance around this in the ticket? Currently says "Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on this ticket."
    - [ ] Future guidance on when we (Platform) moves card from done to closing
      - From notes: Low priority, not needed for launch. tech-debt

  - [x] FW: Change Click Schedule Event to Click "Schedule Event"
  - [x] FW: Bold "at least four days before"
  - [ ] Post Launch: FW: Opportunity Statement: Add specific verbiage for attaching artifacts only in the Artifacts section
  - [x] FW: Remove "Don't put staging credentials..." duplicate messaging
  - [x] FW: Platform Actions: Update "add platform reviewes..." to "follow moderator..."
  - [x] FW: Platform Actions: Remove "If no feedback...."
  - [x] FW: Zoom REcording to Recording URL
  - [x] FW: VFS Actions: "please comment on this ticket" to "please comment on this issue ticket..."
  - [x] FW: "Update staging review ticket" to "update VFS product information with feature launch date and Prod URL"

- [x] [Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274432) - Chase
  - [x] Pre-sched
    - [x] Step 1 - put period after template, remove everything after that for this step.
      - [x] change “template” to “section” (ensure DI and MPR have similar language changes)
    - [x] Step 2
      - [x] change to - Reply in Slack if it’s not 4 days (not on the GH ticket)
    - [x] Step 3
      - [x] change to - respond in Slack not on GH ticket
  - [ ] Schedule
    - [x] Step 1
      - [x] like DI and MPR - instructions in Calendly will need to change from add that specific ticket to add the core ticket (will be challenging because need to split process while we get through teams currently on the old CC tickets
        - Need to coordinate with Shira
    - [x] Step 4
      - [x] already a tech-debt ticket for removing VSA
    - [ ] Step 5
      - [x] Also change the core ticket so that SR section opens automatically (either here or if it makes sense elsewhere)
        - Added to Midpoint Moderator Post Meeting section
      - [ ] Keep VFS/Platform actions in the same order for each section - tech-debt
      - [x] add spot for date/time of meeting in SR Platform section
      - [x] pipeline name will need to change, but that should be marked elsewhere
    - [x] Step 6
      - [x] Change from comment on GH to respond on the Slack request on the VP support channel
  - [x] Pre-meeting
    - [x] Step 1
      - [x] remove comment on GH ticket, but keep communication channel generic for now (similar to step 2)
    - [x] Step 2
      - [x] update to say “communicate with the VFS PM”
  - [x] Morning of Meeting
    - [x] Step 8 - Change from "Epic of Staging ticket" to "epic of Collaboration Cycle ticket"
  - [x] During Meeting
    - [x] Moderator Script - Remove line "if QA does not have feedback to comment", should change to be in alignment with other practice areas. Checkbox confirming completed review in relevant touchpoint
  - [x] Post Meeting
    - [x] Step 2 - Remove step. No longer need to update tracker
      - [x] Keep consistent with DI and MPR
    - [x] Step 4 - Change to "Collaboration Cycle Reviews ZenHub board"

  - [x] FW: Pre-scheduling: Verify steps align to Design Intent steps
  - [x] FW: Pre-scheduling: Step 3: Delete
  - [x] FW: Schedule: Step 4: Remove "Invite Tze..." and VSA Teams table
  - [x] FW: Schedule: Step 7: Change to platform-collaboration-cycle
  - [x] FW: Morning of Meeting: Step 8: Change to "Add all new issue tickets as child tickets to the Collaboration Cycle Request ticket"
  - [x] FW: During Meeting: Step 4: Delete "If QA does not have feedback..."
  - [x] FW: During Meeting: Step 4: Verify script matches Platform Website
  **Note: Script does not mention research on PW or Operational docs**
  - [x] FW: Post Meeting: Step 3: Add step to remove "automatically open Staging Review section" (like Midpoint Review post meeting steps)

- [x] [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241650) Clayton
  - [ ] Reviewer Responsibilities Pre-Meeting
    - [ ] Step 9 - Edit Drafting template permissions to allow editing Column N (Other references)
    - [x] Step 12 - Add verbiage for "Depends" and reviewer discretion
      - Will handle post MVP launch
    - [x] Step 13 - Remove step

  - [x] FW: Things to keep in mind as a reviewer: Bullet 1: Change to "Go to the Collaboration Cycle Request ticket..." 
  - [ ] Post Launch: FW: Update Collab Cycle Feedback for Staging

- [x] [Original Staging Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md) - Chase
  - [x] "### NOTE:
**This template is being deprecated**. If your kickoff meeting took place after 5/25/2022, You should use the new template [Link TK] instead. If you are unsure if this applies to you, please reach out to the Governance Team on the **#vfs-platform-support** Slack channel."
     - PR #41620 created, waiting link creation

  - [x] FW: Update messaging to match

## Acceptance Criteria
- [ ] [Platform Website: Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2167734305) has been updated
- [ ] [Kickoff Ticket Template](https://github.com/briandeconinck/cc-test/issues/new?assignees=briandeconinck&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team&template=core-collab-cycle-yaml.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) has been updated
- [ ] [Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169274432) has been updated
- [ ] [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2169241650) has been updated
- [ ] [Original Staging Review Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby Here's my comments:

- the "Moderator Script" should be changed on Platform Website: Staging Review AND in the Moderator Responsibilities doc.
- For the Original Staging Review Request Ticket, the Slack channel should refer to #vfs-platform-support

**Comment by chaseakirby** [comment]
@shiragoodman Thanks! Made those changes! I'm going to check the other original tickets as I believe I copied that.

**Comment by claytonzook** [comment]
@chaseakirby the "How to document feedback for Staging Review" step 9 change to allow Row N to be editable, I think is a change on the [drafting template](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit?usp=sharing). I don't seem to have permissions to unprotect, so leaving that one for you.

**Comment by shiragoodman** [comment]
thanks @claytonzook . i don't think the change to Row N in the drafting template is critical for this launch. just leave it unchecked for now and during the final walk through on Monday, we'll take an action to get it updated.

**Comment by chaseakirby** [comment]
Moderator Responsibilities & How to document feedback have been updated on Platform Website. Closing ticket.

**Comment by shiragoodman** [comment]
all unchecked items have been documented as tickets in initiative #42580
