### ISSUE TITLE
[FE] Create Appointment Actions Modal for Staging Appointment App

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41469]
## User Workflow
- Modal for viewing and generating information about appointments that have been booked in the staging UI
  
## ACs

- [ ] Shows appointment date, time and patient
- [ ] Shows "Get Pre-Checkin Link" button if appt starts after today
  - [ ] When clicked: Shows UUID, staging link and text that it will go away
- [ ] Shows "Get Checkin Link" button if appt starts in the next 1/2 hour
  - [ ] When clicked: Shows UUID, staging link and text that it will go away

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
