### ISSUE TITLE
Integrate front end widget with API

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4147]
## User Story:
Currently, the Forms Widget visible at `www.va.gov/find-va-forms-beta` is using a fixed data structure, not connected to an API. However, now that the API is built and visible at `dev-api.va.gov/v0/forms`, we should begin using that API from the Forms widget. We should 

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] From the front-end, use the Platform helper function, `vets-website/src/platform/utilities/api` to fetch data from the `v0/forms` API route to be rendered on `/find-va-forms-beta`.
- [ ] Remove any unneeded code, such as the `.json` file

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] For every search performed, we load results from the API

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
@ncksllvn Do we know what the API key is that we'll be using? Once we know that, I think this ticket is pretty straightforward! :)

**Comment by ncksllvn** [comment]
Not yet but to test locally, you can pull my API branch, `nps-3563`, at https://github.com/department-of-veterans-affairs/vets-api/pull/3616. Then, in your `settings.local.yml`, add a property like this -

```
lighthouse:
  api_key: YOUR_API_KEY
```

**Comment by kelsonic** [comment]
Actually, perhaps `vets-website` won't even need to worry about the API key since it looks like https://dev-api.va.gov/v0/forms doesn't require it :)

**Comment by ncksllvn** [comment]
That's our API!

**Comment by ncksllvn** [comment]
Rephrased this ticket title to `Integrate front end widget with API `

**Comment by ncksllvn** [comment]
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/3700e2b7-4470-4642-8d7e-a9370a748ff7)

Done!
