### ISSUE TITLE
[FE] Create AppointmentListItem Component for Staging Appointment App

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41470]
## Description
This component houses appointments that have or can be booked in the Staging UI
  
## ACs

- [ ] Shows appointment slot time
- [ ] Shows appointment status
- If appointment status is available:
  - [ ] Shows "Book" button - books slot for patient selected on page and brings up details modal
- If appt status is booked:
  - [ ] Shows "Details" button - brings up details modal for that appointment

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
