### ISSUE TITLE
Handling `va-date` web component error messages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41481]
## Description

We have an error message pattern established where we don't show an error message until after a form element is blurred, e.g. error message shown for missing or invalid values.

With the `va-date` component, there are 3 elements (2 selects and 1 input), each of which fires off the `onDateBlur` callback (for the react-binding component) when blurred. This makes it difficult to determine when the combined fields should show an error message. I would have expected the `onDateBlur` to trigger once all 3 fields had been touched.

In our case, the `va-date` WC is being used within Form 526's wizard, and shows additional content below the date section once a complete date is entered, so, the `blur` callback isn't being used.

;tldr `onDateBlur` may work better if it was triggered after all fields have been touched

## Tasks

- [ ] Discuss/research when `onDateBlur` callback is fired

## Definition of done

- [ ] Consensus reached on how to handle `onDateBlur`
- [ ] Documentation of decision
