### ISSUE TITLE
Auth Profile | Sprint 75 | 6/1 - 6/14

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41480]
## PTO/OOO/Unavailable

- **Christina**: 
- **Sharon**:  afternoon of 6/13
- **Tom**: 
- **Mark**: 
- **Samara**: afternoon of 6/14
- **Adam**: 6/10
- **Liz**:  5/31 - 6/7

## Sprint Priorities
1. Personal information: UAT
2. Direct deposit: Testing and launch of latest updates
3. Military information: Testing and privacy review
4. MHV research: Share with stakeholders
5. Bad address indicator: Continued progress

### PM - Sharon

- [x] #42063 UAT Go/No Go meeting
- [x] #41823 Google Analytics widget

### Design - Christina

- [x] #42087 UAT Pilot 
- [x] #42088 UAT Recruiting 
- [x] #42160 UAT Research sessions 
- [x] #42068 Update guide

### FE - Adam
- [x] #41319 error messaging for fields left in blank state
~- [ ] #34242 deploy to 25%~
- [x] #42140 UAT support/participation

### Design - Liz

- [x] #40167 - share finding with stakeholders 

### PM - Sharon

- [x] #41743 - Analytics
~- [ ] Placeholder for Team QA~

### BE - Tom 

- [x] #41136 Privacy & Security

### PM - Sharon

- [x] #39168 Use cases
- [x] #39169 Provide accounts for staging/QA
- [x] #41978 Midpoint review prep and schedule

Stretch goal: Hold midpoint review this sprint

### FE - Mark

- [x] #39344 Verify same address functionality
- [x] #39342 UI build
- [x] #41615 Foundational accessibility
- [x] #42144 Feature Toggle 2x

### BE - Tom

- [x] #39345 Same address functionality

### Design - Christina

- [x] #41175 Finalize Research Plan
- [x] #42335 Update BAI mocks

### PM - Sharon
- [x] #41173 Launch Readiness (in progress)

### FE - Mark
- [x] #40723 content page with id.me - blocked
- [x] #42270 launch to 25% on 6/6
- [x] PLACEHOLDER: launch to 50%

### Design - Liz
- [x] #41527 - update alerts

### PM - Sharon

- [x] #41963 Add GA widget

### FE - Mark

- [ ] Placeholder for diagrams on profile products
- [x] #23312 DD for more specific error logging
- [ ] #38905 older ticket; work when have time

### BE - Tom

- [x] #41176 Alerts

### FE - Adam
- [ ] #40593 (ON HOLD: accessibility prod issue - screenreader) 
- [ ] #41971 Discovery - Library
