### ISSUE TITLE
[FE] On-Site Notifications: Implement Front End Changes for Multiple Notifications

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#41482]
## Background
Angela has completed the design for our first iteration of displaying multiple onsite notifications for debts and payments. We now need to implement the front end changes based on the proposed design.

Design documentation is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend/documentation/README.md
---
## Tasks
- [ ] Complete front end code changes
- [ ] Test

## Acceptance Criteria
- [ ] Front end changes are released matching the designs provided above
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tmitchellgcio** [comment]
Will be validated once the backend work is completed through QA
