### ISSUE TITLE
[CDP] Merge debt-letters under the new combined-debt-portal

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#41483]
## Issue Description
debt-letters needs to move under the new combined-debt-portal application for the new URL structure. While in development and testing the production debt-letters won't change, and updates for the CDP effort will be made in under the combined-debt-portal. 

---
## Tasks
- [x] Merge debt-letters under combined-debt-portal

## Acceptance Criteria
- [x] a copy of debt letters will exist within combined-debt-portal and behind the CDP feature flag
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
