### ISSUE TITLE
Adding self-service content to VHIC page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41485]
## Issue Description
Stakeholder Tarsha Tremble asked the content team to make updates to the [Get a Veteran Health Identification Card](https://www.va.gov/health-care/get-health-id-card/). They've updated the process for how to get new cards and we need to put that information on our page. The page now needs to include information about self-service options.

Here is the info the stakeholder sent: 

Yes, the VHIC program developed a new online self-service option for the Veterans in January of this year.  It is broken down into 2 phases.  The Veteran can log into their authenticated account on - https://eauth.va.gov/accessva/   from there.  The Veteran has the option to go through the process to do a replacement card request or complete a remote proofing card request.  

Please take a look on our training website for the following slides  [Using_VHIC_4.20_Self_Service_New_Card_Request_Processing (va.gov)](https://www.knowva.ebenefits.va.gov/img/hrc/Using_VHIC_4.20_Self_Service_New_Card_Request_Processing.pdf)  it will give you step by step instructions on how to process the self-service request, so that you and your team can get a feel for the process. 

The training slides for Self-Service have been posted on the VHIC KMS site:  [Veteran Health Identification Card HEC](https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-[…]tent/554400000069141/Veteran-Health-Identification-Card-HEC) 

Once we've reviewed this we need to set up a call with Tarsha.

## Tasks
- [x] Reach out to stakeholder for more information
- [x] Rework page (Katherine)
- [x] Review edits (Laura)
- [x] Copy edit (Megan)
- [x] Provide Danielle with edited page in new ticket #41493 (Megan)

## Acceptance Criteria
- [x] VHIC page is ready for Danielle to review

**Comment by RLHecht** [comment]
@laurwill I added all the info from Tarsha's email to the top of this ticket.

**Comment by laurwill** [comment]
Thanks Randi! 

@DanielleThierryUSDSVA , I wanted to run approach by you before we chat with Tarsha. 
- We could model the new self-service information on this [Veteran ID card page](https://www.va.gov/records/get-veteran-id-cards/vic/) — guide users to the AccessVA self-service tool and add a section similar to the "You'll need this information" H2 explaining what info to gather and how to take the photo before they start using the tool.
- I also considered creating a step-by-step R&S page (like [this example](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-benefits/)). But from the [screenshots Tarsha provided](https://www.knowva.ebenefits.va.gov/img/hrc/Using_VHIC_4.20_Self_Service_New_Card_Request_Processing.pdf), it looks like the tool will guide users through a fairly straightforward application process, so I'm not sure we need the step-by-step. (Randi is finding the test user logins so we can confirm how the tool works.) 

Are there criteria you use to decide if a Step-by-step guide is needed to support a tool?

**Comment by katherine-fung** [comment]
Hi @laurwill, here's a draft of the VHIC page with self-service content. I put questions for you and the stakeholder in the comments: 

https://docs.google.com/document/d/1dh0C8tjRKUlrf7YuV2udXNOXXnLuikqRSdpULoOIUvg/edit#

**Comment by laurwill** [comment]
Thanks @katherine-fung ! Nice work on this, and thank you for calling out all those questions in comments. See my edits and responses in the doc — since you're out this week, I'll leave the Google doc as is for your review and move forward with Word and Drupal drafts for further updates.

Randi and I will reach out to Tarsha with our questions. It's turned into quite a list, so collecting them here:
- Is the in-person process still supported equally along with the online option, or are they trying to transition mostly to the online process?
- The in-person instructions mention using a separate document to confirm address if it’s not on your ID — is this an option for the online process?
- What should people do if their card doesn’t arrive in 10 days in the online process? (There's a phone contact listed on the live site, and the Veteran ID Card page mentions logging in to AccessVA to check the status of a card app, so maybe one of those options)
- For the replacement cards, are people locked into the in-person or online option depending on how they applied for their original cards? Or can someone who originally applied online get a replacement card at their local center, and vice versa?
- Is the information about destroying old versions of the card still needed? How can people tell if their card is old vs. new?
- Login.gov isn't currently listed as an option in the AccessVA screen for VHIC — will people be able to use this credential to sign in to the online request tool?

**Comment by laurwill** [comment]
Updates:
- I sent our questions to Tarsha via email and offered to set up a call if she'd rather talk through them
- Randi shared an email chain showing that another stakeholder already flagged the missing Login.gov sign-in option, so we don't need to ask about this now — but we'll follow up about this option before we finalize this content
- Danielle confirmed that we don't use the "Am I eligible?" language on this page because everyone with VA health care needs a VHIC, so it's not a matter of eligibility

Posting the in-process Word doc here for safekeeping, and will update again once we hear back from Tarsha.
[Get a Veteran Health Identification Card page updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8819863/Get.a.Veteran.Health.Identification.Card.page.updates.docx)

**Comment by laurwill** [comment]
Update: Katherine is updating the doc based on these **responses from Tarsha**:
- Both processes (online and in person) are supported equally at the same time by the VHIC field staff.
- The in-person instructions on the live VHIC card mention using a separate document to confirm your address if it’s not on your ID. For the online process the Veterans address has to match what is listed in our Enrollment System.  If the Veteran wants to use a different address than what we have listed in the Enrollment System, then the Veteran has to call and update the address in the system before enter an online card request.
- If they request a card online and it doesn’t arrive in 10 days, they can call the phone contact listed on the live site (877-222-8387). The Veterans don’t have any way to check the status of their card request once they submit it.
- For replacement process, it does not matter how they requested the original card.  Veterans can request a replacement card in person, online or via phone.  They are not locked into one process.
-  Info about destroying old versions of the card is still needed. The new VHIC have the Veterans member ID, card number, branch of service and service connection listed on it.  The old cards do not.

**Comment by katherine-fung** [comment]
Thanks @laurwill! I added 2 new comments in the word doc that we need clarification on. 

[https://app.zenhub.com/files/133843125/8a2957d5-cfb1-4a72-9688-710c3bdf09c3/download]

1. What are people's options for updating their address with VA health care to match their ID? 

It appears there’s a form for updating your address for health benefits (https://www.va.gov/health-care/update-health-information/) but it seems like you can also update your address by changing it in your va.gov profile (https://www.va.gov/change-address/).

2. Tarsha confirmed that anyone can get a replacement card in person, even if they applied for their original card online.

Can we confirm whether people can go to *any* local VA medical center for a replacement, or do they need to go to a. the medical center where they originally got their photo taken, or b. the medical center where they currently receive care?

**Comment by laurwill** [comment]
Thanks so much @katherine-fung ! I tracked some new changes in the doc and added some FYI comments for you in yellow highlight. On Monday, could you give this another read, accept all changes in the document, remove my FYI comments to you, leave my comments to Danielle and Tarsha, and pass the document along to Megan for copyedit? Thanks!
[Get a VHIC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8883928/Get.a.VHIC.docx)

**Comment by katherine-fung** [comment]
I've gone over and accepted the changes in the Word doc, resolved the comments to me, and left the comments for Tarsha and Danielle.  

@megzehn - the attached Word doc is ready for a copyedit 

[https://app.zenhub.com/files/133843125/e19c5e65-07e0-4985-8f56-a4499c11c65b/download](https://app.zenhub.com/files/133843125/e19c5e65-07e0-4985-8f56-a4499c11c65b/download)

**Comment by megzehn** [comment]
Thanks @katherine-fung. This is copyedited, and I moved the doc over to a new ticket for Danielle (#[41493](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41493))

**Comment by RLHecht** [comment]
Thanks all! Closing this ticket.
