### ISSUE TITLE
OCTO-DE review and publishing of VHIC page updates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41493]
## Issue Description
We made edits to the [Get a Veteran Health Identification Card](https://www.va.gov/health-care/get-health-id-card/) page based on a stakeholder request. This work can be found in ticket #41485.

This ticket is for Danielle's final review of our changes as well as our pre-publishing checklist and publishing on the page.

## Tasks
- [x] Final review (Danielle)
- [x] Send to stakeholder for approval (Laura/Randi)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish page (Megan)
- [x] Notify stakeholder that changes are live (Laura/Randi)

## Acceptance Criteria
- [ ] Updated VHIC page is live on the site

**Comment by megzehn** [comment]
Hi @DanielleThierryUSDSVA - could you please review this VHIC content? There are a few questions in there for you and the stakeholder. Let us know if it needs more attention. Thanks! 

[VHIC_card_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8921877/VHIC_card_copyedited.docx)

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , in addition to the Word document above, we also drafted a small related update to the [After you apply for health care benefits](https://www.va.gov/health-care/after-you-apply/) page. We suggest changing step 3 in the subway map to read: 

**Get your Veterans Health Identification Card (VHIC).** This is the card you’ll use for ID and to check in at your VA health care appointments. You can request your card online, or in person at your local VA medical center.
[Learn how to get your VHIC](https://www.va.gov/health-care/get-health-id-card/)

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, all! @laurwill I'm getting an error message when I try to upload my edited word doc. So I'm going to slack it to you now. Above looks good for After you apply page with 2 tweaks:

- Use "nearest" instead of "local" because you use "nearest" on the page
- If Tarsha confirms that it's any VA health facility, make that change here too.

Also, there is [content within Resources and Support around the VHIC](https://www.va.gov/resources/whats-a-veteran-health-id-card-vhic-and-how-do-i-get-one/) because the R&S has its own search and analytics showed that Veterans were searching for this info a lot there. And there's a blurb within the [broader health ID cards page](https://www.va.gov/records/get-veteran-id-cards/). Can we make sure that we make any edits there too? Thank you!

**Comment by laurwill** [comment]
Thanks Danielle! I sent the updated page to Tarsha for review. And thanks for flagging that related R&S content — I don't _think_ these updates will trigger any substantial changes to those, but I'll make sure to assess again when we have final content.

Here's the clean version of the Word doc for reference:
[Get a VHIC_for SME.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9031857/Get.a.VHIC_for.SME.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @laurwill! Have a great holiday weekend!

**Comment by laurwill** [comment]
Update: Tarsha provided minimal feedback in the Word doc, and I hopped on a call with her team to chat through their questions. They've approved the content with one remaining point to confirm before we publish:
- Does changing your address in VA.gov profile update the enrollment system (system AccessVA pulls from)? 

@megzehn , these pages are ready for your final copyedit, but we'll **hold on publishing** until I confirm that point. 
- VHIC page: http://preview-prod.vfs.va.gov/preview?nodeId=488  
- After you apply page (only changed VHIC section in step-by-step): http://preview-prod.vfs.va.gov/preview?nodeId=30

And @RLHecht  noting here 2 related tasks we'll want to open separate tickets for:
- Tarsha said the photo rules on the VIC page should match the rules in this content. We'll need to confirm that and update VIC page.
- Login.gov is slated to start working with AccessVA/VHIC self-service at the end of September. We'll need to update the VHIC page to include that sign-in option.

**Comment by megzehn** [comment]
@RLHecht and @laurwill confirming here that I copyedited these pages, but I didn't publish them yet, per Laura's comment above. Thanks!

**Comment by laurwill** [comment]
Thanks Megan! Just an update here: 
- I was able to confirm with the profile team that changing address in your profile will change it in the system VHIC tool pulls data from, so that's resolved
- We had one remaining question to confirm with Tarsha: Can we link directly to the VHIC sign-in page rather than the AccessVA homepage, to save Veterans 2 clicks? We're meeting on Tuesday with Tarsha's team and the VHIC tool team to discuss this!

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , we just had a call with Tarsha and the VHIC self-service tool product team. That team suggested that instead of linking to the AccessVA sign-in screen, we have people authenticate directly through a sign-in modal on our VA.gov page. They showed us on staging how a user could sign in with ID.me and then go directly into the VHIC tool flow. 

They pointed to the [VIC page](https://www.va.gov/records/get-veteran-id-cards/vic/?next=loginModal)) as a model for this. But although there's a VIC tool on AccessVA, I now see that the VIC va.gov page goes to a separate app after you authenticate, not to AccessVA.

So we wanted to check with you: Would we want to do a sign-in modal on the VHIC page and then link directly into the tool, rather than linking to the AccessVA VHIC sign-in screen?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill. This is a technical question and depends on how the systems can interact. You're spot on that it very much depends on the tool/system. 

We explored this same question recently with the travel reimbursement tool, which also sites behind AccessVA authentication, and it wasn't possible at this time. My instinct is that it's probably a similar case with this tool.

Given all of our many priorities, the urgency of PACT Act work, and the fact that we do have an existing solution for VHIC, I don't think that we can prioritize trying to explore this right now. But we can definitely put it in the backlog to explore as soon as we have capacity. 

If you'd like to pull me in to communicate this to our partners, just let me know. If you're good with communicating, that's fine too! Thank you!

**Comment by laurwill** [comment]
Thanks Danielle! I responded to Tarsha and suggested that we publish with the AccessVA link as planned, then explore replacing it in the future. She's OOO today, but I let her know we can publish on Monday if she's good with this approach.

**Comment by laurwill** [comment]
This is blocked until we get a response from Tarsha.

**Comment by laurwill** [comment]
Updates from email convo with Tarsha and Edward:

**Changes on 2 more related pages**
We'll plan to copyedit/publish updates to these pages when we pub the main page and after you apply page:
- [Types of Veteran ID cards](https://www.va.gov/records/get-veteran-id-cards/) (Preview: http://preview-prod.vfs.va.gov/preview?nodeId=473)
- [What’s a VHIC and how do I get one?](https://www.va.gov/resources/whats-a-veteran-health-id-card-vhic-and-how-do-i-get-one/) (Preview: http://preview-prod.vfs.va.gov/preview?nodeId=36778)

**Verify identity info for Veterans living outside the U.S.** 
Stakeholders asked us to add the info from this Word doc to the VHIC page. Since it's not specific to VHIC, we'll add to the Verifying your identity page instead and consider linking there from VHIC. 

Stakeholders also clarified that Veterans living overseas can use any existing account (Login.gov, ID.me, DS Logon, or MHV) for the self-service portal on AccessVA. These new instructions are mostly relevant for Veterans who don't have an existing sign-in account and have been living overseas for "a long time" (which I think means they have a permanent address/phone number in another country). 

We asked stakeholders if they could provide data/info about how often Veterans living abroad have trouble verifying identity/using AccessVA — we're meeting on 10/20 to talk with them about this issue.

**Comment by laurwill** [comment]
I added a draft single Q&A to the Verifying identity page to use as a visual with stakeholders: http://preview-prod.vfs.va.gov/preview?nodeId=8233 

Since this info is not specific to VHIC, we may want to run this by the identity team and any other relevant stakeholders before publishing. I'd also like to find out if Login.gov has any parallel info for Veterans living outside the U.S.

**Comment by laurwill** [comment]
And more updates! Edward and Tarsha explained that their office is promoting the online option specifically to Veterans who have been living overseas. If these Veterans don't already have a verified account, the only account type they can create with a foreign address is ID.me. 

So we agreed to add a note on the VHIC page noting that if you live outside the U.S. and don't already have one of the sign-in accounts, you'll need to create an account through ID.me. 

We also need to decide if a link is helpful here — options:
- we're planning to add a question to the Verifying your identity page, so we could do a jump link to the H2 above that accordion header
- include the key instruction in the note — select "I don't live in the U.S." on the Verify your identity screen of the ID.me form
- link directly to [this ID.me help page ](https://help.id.me/hc/en-us/articles/4415907236375-What-if-I-don-t-live-in-the-United-States-)about this process

@katherine-fung , want to draft this note with one of those options and we'll chat with Danielle in our meeting today? There's a previous drupal version where I had tried out a similar note — feel free to work from that if it's helpful.

**Comment by laurwill** [comment]
@katherine-fung per chat with Danielle, can you try adding the content from the draft accordion section on the [Verifying page](http://preview-prod.vfs.va.gov/preview?nodeId=8233) to the VHIC page? We may want a jump link from a note just under the AccessVA link — see what you think when you get into Drupal. 

This will be sort of "manual" reusable content, with the expectation that we can eventually add a reusable Q&A element to both pages.

**Comment by katherine-fung** [comment]
@laurwill - per our Slack, I tweaked the QA on the Verifying and the VHIC pages to say "How can I verify my identity if I live outside the U.S.?"

I added the draft QA to the accordion at the bottom of the VHIC page. I also added a note with a jump link to that section under the AccessVA link on the VHIC page.  

Notes
VHIC page
- I made the question the first accordion item on the VHIC page, so it's easy for people to find after clicking the jump link. But maybe the next question ("How long will it take to get my VHIC?") outweighs it in terms of relevance? Let me think if we should re-order them. 
- Just noting the order in which we list the account types on the VHIC page: "You’ll need an ID.me, Login.gov, DS Logon, My HealtheVet, or Department of Defense Common Access Card (CAC) account." I don't think this follows the order on the AccessVA sign-in page (but maybe that's ok because the CAC isn't usually an account we list on pages). Is this ok as is? 

Verifying page
- The "How can I verify my identity if I live outside the U.S.?" QA is nested under "Questions or issues you may have while verifying your identity." Should we move it to the previous section ("How to verify your identity on VA.gov"), or is it ok where it is?

**Comment by laurwill** [comment]
Thanks @katherine-fung! I did some more futzing, see my responses to you in bold above. 

@DanielleThierryUSDSVA , these updates are ready for your review. I'd love a gut check on whether this semi-reusable content approach is working here.

Verifying your identity page: http://preview-prod.vfs.va.gov/preview?nodeId=8233 
- Added new question "How can I verify my identity if I live outside the U.S.?"
- Updated "I don't have a smartphone. How can I verify with ID.me?" to remove the bullet about not accepting international phone numbers. ID.me now allows non-U.S. numbers.

VHIC page: http://preview-prod.vfs.va.gov/preview?nodeId=488 
- Added note in the "Online" H3 about using ID.me if you live outside the U.S. Jump link goes down to "Questions about your VHIC," with this new question listed first. 
- The new accordion section is mostly the same info as the new section on Verifying page, but adjusted the header and added a few lines to fit better in this context. This makes this section less reusable/COPE, but we can't actually reuse the Q&A at this time.

**Comment by laurwill** [comment]
Hi again @DanielleThierryUSDSVA , per our chat today, we'll remove the section on the VHIC page and link over to the Verifying page instead. 

Could you review just the Verifying your identity page changes, and loop in John if needed? Thank you!

http://preview-prod.vfs.va.gov/preview?nodeId=8233
- Added new question "How can I verify my identity if I live outside the U.S.?"
- Updated "I don't have a smartphone. How can I verify with ID.me?" to remove the bullet about not accepting international phone numbers. ID.me now allows non-U.S. numbers.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill. Q&A looks great! The only edit I have is to make sure the link labels have the target for the external site + make the keywords in the second one match the H1 of the destination page a little more.

So something like these (please feel absolutely free to edit these further!):

[Learn more about how to verify your identity if you live outside the U.S. on the ID.me website](https://help.id.me/hc/en-us/articles/4415907236375-What-if-I-don-t-live-in-the-United-States-?_ga=2.119211657.1205746016.1666561000-1811696545.1663154965)

And

[Learn more about primary and secondary identification documents you can use on the ID.me website](https://help.id.me/hc/en-us/articles/360017833054-What-is-a-Primary-or-Secondary-Identification-Document-?_ga=2.119211657.1205746016.1666561000-1811696545.1663154965)

**Comment by laurwill** [comment]
Thanks so much Danielle! As we chatted, I created a single Q&A so we can link to it directly (good workaround to remember when we're having accordion jump link angst).

@jrahaghi1 , would you also like to review this new Q&A about verifying identity? We'll place this in the second accordion section on this [Verifying R&S article](https://www.va.gov/resources/verifying-your-identity-on-vagov/#questions-or-issues-you-may-ha). Thank you!

**Comment by RLHecht** [comment]
@megzehn Danielle got approval from John that these are good to go. Can you please prioritize copyediting these tomorrow morning so we can send back to the stakeholders tomorrow? Thank you!

**Comment by megzehn** [comment]
Hi @RLHecht! These pages are copy edited. 

http://preview-prod.vfs.va.gov/preview?nodeId=488
- New note for Vets outside U.S. on VHIC page, with link to new single Q&A
http://preview-prod.vfs.va.gov/preview?nodeId=50666
- New single Q&A which will appear on [this page](http://preview-prod.vfs.va.gov/preview?nodeId=8233)
And a slight change to a question within the verifying page
    --[ ](https://prod.cms.va.gov/node/8227/revisions)

**Comment by laurwill** [comment]
Thanks Megan! I sent the VHIC page and the single Q&A to stakeholders for approval, and just noted that we'll add that Q&A to the Verifying FAQ as well.

**Comment by laurwill** [comment]
Hi @megzehn ! We got the green light to publish VHIC changes. 

You've already copyedited all 4 of these updated pages, and they're now ready for final prepub/publishing: 
- [ ] VHIC page: http://preview-prod.vfs.va.gov/preview?nodeId=488
- [ ] After you apply page: http://preview-prod.vfs.va.gov/preview?nodeId=30
- [ ] New single Q&A: http://preview-prod.vfs.va.gov/preview?nodeId=50666
- [ ] Verifying page: http://preview-prod.vfs.va.gov/preview?nodeId=8233

And these 2 additional related page updates are ready for copyedit and publishing: 
- [ ] Types of Veteran ID cards: http://preview-prod.vfs.va.gov/preview?nodeId=473
- [ ] What’s a VHIC and how do I get one? http://preview-prod.vfs.va.gov/preview?nodeId=36778

**Comment by RLHecht** [comment]
These are live and Laura notified the stakeholder. Closing ticket!
