### ISSUE TITLE
[CDP] Update URLs and Breadcrumbs

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#41505]
## Issue Description
Update CDP URLs and breadcrumbs to match design and IA specifications. Add the new CDP path to content-build repo so it's accessible for testing!

[Link to IA thread on URLs & Breadcrumbs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39294)

---
## Tasks
- [x] Update CDP URLs
- [x] Update CDP Breadcrumbs
- [x] Update content-build with URLs and specify testing only (hide behind feature flag)

## Acceptance Criteria
- [x] CDP URLs and Breadcrumbs are available
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
