### ISSUE TITLE
Research: Request new public subdomain URLs for vets-api

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#41515]
## Issue Description
The time has come to get the ball rolling on requesting the first external subdomain(s) for the work our team is doing. According to the [RFC on the new domain name](https://github.com/department-of-veterans-affairs/va.gov-team/pull/39999), no major concerns were raised about using the name `[env]-platform-api.va.gov`. However, we should confirm this choice with the product owners. 

The CIT team will request a the first external URL (`dev-platform-api.va.gov`) from the **ESECC team**. The URL will be routed to the `vets-api` website via the EKS Traefik controller. One of the steps in the approval of the new domain is a WASA scan of the `vets-api` site. Since this is an existing resource and was tested for security before, this scan will hopefully not uncover any major issues. 

Another TODO item here is researching the process of setting up proper SSL certificates for the new domain, so it's accessible via https.

Beau Grantham and others on the Lighthouse teams were identified as potential resources in guiding us through this procedure, since they are currently also in the process of setting up new domains in the `va.gov` space.

Process doc: https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

---
## Tasks
- [x] Confirm choice of domain name with the product owner
- [x] Find out who to contact on the ESECC team and gain clarity on the procedure of requesting the DNS
- [x] Contact LH team for advice on the process
- [x] Examine existing ESECC ticket.
- [x] Meet with Infra team to determine load balancer addresses for new subdomain(s).
- [x] Collect documents necessary to be update for "In Scope" change request.
- [x] Meet with Faith Owusu-Sekyere to discuss updates to the ESECC documents.

## Acceptance Criteria
- [x] We have confirmed the choice of domain name
- [x] We have started the process of requesting the chosen domain name for the DEV environment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
@alwerner that's a great question and I had thought about this. The only reason would be that those domains for the other environments would initially be sitting around unused. They wouldn't be functional and we would have no way of testing them. However, we should probably ask if it would make sense to just request them all at once.

**Comment by alwerner** [comment]
Referred to Gabriel Olavarria by Beau Grantham.

**Comment by alwerner** [comment]
@madebydna Meeting set up with Gabriel Olavarria on Tuesday, 5/31 at 2:00 EST.

> This would effectively mean purchasing certificates for a new external domain, opening eseccs for exposing it outside the TIC, and working with the TIC (for external DNS resolution and SSL termination) and with CIS Directory Services for internal DNS resolution.
> 
> Then there would be VSP platform work to also terminate ssl in the revproxies
