### ISSUE TITLE
Meet with DLC obtain, URL and 1 Endpoint

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4151]
## User Story:
As a ____Front-end______I need to meet with DLC _________ so that we can ____complete a post/get call from the DLC API______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Meet with DLC 1 hr
- [ ] Develop a post call VA side
- [ ] Develop a get call on VA side
- [ ] Document DLC's URL, and Restful call
- [ ] Have one endpoint confirmed with DLC

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Add code GH

## Next Steps
-TBD
## Blockers
-DLC creating the URL, RESTful environment

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
