### ISSUE TITLE
Research and document Traefik status quo

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#41517]
## Issue Description

The main goal is to remove the Traefik file provider that we added and reconfigure Traefik to route the `dev-internal-api.vfs.va.gov` URL to the vets-api instances in EKS. A secondary goal is to enable https traffic via that new domain.

Demian had originally attempted to use the Traefik default `IngressRoute`, so [that PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/478) can be used as a reference.

Currently. the Traefik file provider is set up in these files, so that is the work that needs to be reverted:
- ` apps/vsp-operations/traefik/dev/templates/configmap.yaml`
-  some values in `apps/vsp-operations/traefik/dev/values-dev.yaml`

To inform how to configure Traefik to directly route to vets-api in EKS, we can also reference the manifest files for the EKS version of `vets-api` as a guide, e.g.:
- `apps/vsp-tools-backend/vets-api/dev/ingressroute.yaml`
- `apps/vsp-tools-backend/vets-api/dev/external-dns.yaml`
- `apps/vsp-tools-backend/vets-api/dev/service.yaml`

Setting everything up correctly might require an understanding of how traffic for `dev-api.va.gov` is currently routed to the vets-api in EKS. According to Demian, the traffic is routed like so:

```
Internet -> TIC -> Revproxy LB -> Revproxy -> Tools LB -> Traefik TG -> EKS Traefik Service -> EKS vets-api
```

This involves some components _outside_ of the EKS cluster, such as the current revproxy and the "Tools LB." The RevProxy configuration files show that `dev-api.va.gov` traffic gets directed by default to the Tools Load Balancer, unless a special header is present to force traffic to go to the vets-api LB, which is the non-EKS version:

```
if ($http_x_forward_brd_vets_api) {
  proxy_pass http://internal-dsva-vagov-dev-vets-api-elb-172229860.us-gov-west-1.elb.amazonaws.com:3004$request_uri; // non-EKS version
}
proxy_pass http://internal-dsva-vagov-dev-tools-1729619844.us-gov-west-1.elb.amazonaws.com:80$request_uri; // this will end up in EKS
```
The rules in the Tools ALB's rules in AWS indicate that `dev-api.va.gov` and `*.vfs.va.gov` traffic get redirected to the Traefik TG which will eventually route the traffic to vets-api in EKS.

![Screen Shot 2022-05-18 at 3.10.42 PM.png](https://images.zenhubusercontent.com/62323ff15daa6d0eacf73983/c882145e-6984-40c6-b672-c30b90a0f08a)

---
## Tasks
- [x] Research and document how traffic is routed to vets-api in EKS
- [x] Research and document how traffic to internal domain `dev-internal-api.vfs.va.gov` could be routed to vets-api in EKS
- [x] Research SSL configuration options
- [x] Meet with infrastructure team to ask for advice and pointers
- [x] Prepare for making a PR for this change

## Acceptance Criteria
- [x] Developers have a good understanding of the Traefik Ingress and have made a plan to open a PR for these changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
