### ISSUE TITLE
Remove content from tables on housing eligibility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41522]
## Issue Description

As part of our ongoing work to take content out of unneeded tables, we need to rework the content on our [Eligibility requirements for VA home loan programs](https://www.va.gov/housing-assistance/home-loans/eligibility/) page. 

The tables are in each of the accordions directly under the blue featured content box.

We need to rework this content but maintain all the information that's currently in the tables. 

## Tasks
- [ ] Rewrite content that's currently in tables (Katherine)
- [ ] Edit content (Laura)
- [ ] Copyedit (Megan)
- [ ] Send final content to Beth in ticket # (Megan)

## Acceptance Criteria
- [ ] Content removed from tables and ready for Beth's final review

**Comment by laurwill** [comment]
Updates here!
- Katherine and I started reworked this content in a Google doc and previewed new accordions during last week's content meeting with Beth
- Beth updated the accordion approach in Drupal 
- I added the National Guard and Reserves accordions following the new approach
- I'm double checking that the H4 + accordion hierarchy is okay for accessibility — I'll update here if we need to adjust

@megzehn , in the meantime, this is ready for a copyedit! http://preview-prod.vfs.va.gov/preview?nodeId=753

**Comment by megzehn** [comment]
Thanks, @laurwill! FYI, I sent this one over to Beth with a note about a section that I wasn't sure about. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/41524
