### ISSUE TITLE
[Design, PM] My VA Audit: Use Case Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#41520]
## Background
Based on our meeting from 5/17 we want to document use cases for each section of My VA. Feedback was documented in this Slack thread [here](https://dsva.slack.com/archives/C909ZG2BB/p1652809170289799).

> It would be helpful to make a list for each section of all the use cases we want to capture going forward. Some thoughts I have on this:
> 
> - I think we should always show each section in the LOA3 state.
> - We should show error and loading states under each section heading.
> - The LOA1 experience should stay the same as it is now. We include the prompt to verify your identity, and then the Apply for VA benefits section. We should continue to NOT show the other sections.
> - For healthcare, there is way too much nuanced logic around some of the links. We should try to simplify this.
> - Also for health care, we shouldn't show the unread messages prompt in alert style since we want to differentiate that from the on-site notifications work.
> 

## Tasks
- [x] Schedule working session
- [x] Hold working session(s) to document use cases and update test case documentation
- [x] Update mural board with noted recommendations (include error states in-line with each section)
- [x] Share use cases with Samara for review

## Acceptance Criteria
- [ ] Document in GIT that outlines various use cases for each section of My VA

**Comment by aagosto90** [comment]
The [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1648129585496/d22080eb307aac8bda5ba1153e013a386b7f1396?sender=uce014850ef6c5a8303e70396) is updated with error and loading states within each section.
