### ISSUE TITLE
Synthesize findings from SideNav usability tests.

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4152]
## User Story:
As a product team member, I need find out what the learnings are so that I can make an informed decision for next steps.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Actionable tasks are defined
- [ ] Report and share out of findings 
- [ ] Recommendations of UI

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Karak888** [comment]
We will need to create any follow-up tickets - those that are dev can go to FE but will need any info coming out of this to create new tickets to work as needed.  

@KevinMHoffmanUSDS @jenniferlee-dsva @kelsonic @ncksllvn

**Comment by aeltarhoni** [comment]
Design iteration happening with Ryan T for new tickets to be created.
