### ISSUE TITLE
MVP defined

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4153]
## User Story:
As a PM/DSVA, I need _to define the MVP of the medical device tool  so that I can the team has direction and the objectives are tailored to meet the projects goal.

## Tasks
- [ ] meet with Team/DSVA to determine MVP 1hr
- [ ] Update documents PO, RM, Charter
- [ ] Get DLC to sign off on MVP

## Acceptance Criteria:
- [ ] Meeting notes in GH
- [ ] GH docs PO, RM, CH are all up todate

## Next Steps
- wireframe

## Blockers
- DLC signing off on doc. 
- Per team MVP will be finalized after the wire frames are completed
