### ISSUE TITLE
Onboarding checklist and tasks

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41530]
## Issue Description
This ticket will outline some general technical onboarding tasks, and a reading list for getting up to speed on the specifics of this project.

---
### General Onboarding
- [ ] Request SOCKS proxy access (https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose, pick "SOCKS Access Request")
- [ ] Request AWS access (same link as above, pick "AWS Access Request")
- [ ] Request access to DSVA Slack
- [ ] Request access to Confluence
- [ ] Request licenses for Mural and Lucidchart
- [ ] Clone and start exploring useful repos:
    - [ ] [devops repo](https://github.com/department-of-veterans-affairs/devops) ... this has the Ansible and Terraform files for much of the infrastructure)
    - [ ] [vsp-infra-applications-manifest repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) ... this has the Kubernetes manifest files used in the EKS cluster
    - [ ] [vets-api repo](https://github.com/department-of-veterans-affairs/vets-api) ... this is the backend API repo, written in Rails
    - [ ] [vets-website repo](https://github.com/department-of-veterans-affairs/vets-website) ... this is the React frontend code for the va.gov website

### Reading List
- [ ] [Explainer doc](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap) ... this is the original document that gave rise to this working group. It has a lot of historical context and is still a good resource to start with.
- [ ] [Patrick's introduction video to CIT team](https://drive.google.com/file/d/124hETDtAB2HR5FNS2GkngdAOuO_d4ZbU/view?ts=625f307e)
- [ ] Current RFCs (Request for Comments) ... these are somewhat outdated but we're currently trying to close them out and/or update them to reflect the status quo
   - [ ] [ALB / API Gateway / Nginx decision making ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/39997)
   - [ ] [Phased approach to the removal of Kong](https://github.com/department-of-veterans-affairs/va.gov-team/pull/39998)
   - [ ] [Choosing a new domain name](https://github.com/department-of-veterans-affairs/va.gov-team/pull/39999) 
   - [ ] [Bypassing Kong](https://github.com/department-of-veterans-affairs/va.gov-team/pull/40000)
- [ ] All research articles that we have in our own Confluence space. https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2166751336/Discovery
- [ ] [Discovery Readout](https://docs.google.com/presentation/d/1CEG4YIKJGAiXdtN-hUSW0Ah5qGq_oWKyVtqZ-etRcws/edit#slide=id.p1) ... the set of slides we presented to the Platform team 

## Acceptance Criteria
- [ ] Onboarding tasks are accomplished, e.g access was granted to the different resources listed
- [ ] Has a good overview of the purpose and tasks of this team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
Moving this to Confluence/Discovery and closing. cc: @madebydna
