### ISSUE TITLE
Integrate Terraform with Datadog to Publish Monitors

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41549]
# Description
Use existing examples from Infrastructure team to integrate Terraform with Datadog for the purposes of managing synthetic monitors.

Here's an example of a monitor in Terraform --
https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/monitors.tf

# Tasks
- [x] Research existing solutions for Terraform implementations that integrate with Datadog
- [x] Configure Terraform to publish synthetic monitor changes to the corresponding synthetic monitors in Datadog

# Acceptance Criteria
- [ ] Terraform publishes synthetic monitor changes to the suite of synthetic monitors in Datadog

**Comment by rjohnson2011** [comment]
Synced up with Ryan B to discuss the architecture and approach of the Datadog to Terraform conversion. Reviewed existing Terraform directories in the `devops` repo as a basis for the future initiative.

**Comment by rbeckwith-oddball** [comment]
Looking in the `devops` repo `devops/terraform/environments/datadog/README.md` file, It looks like the terraform portion of the code is done manually.

**Comment by rbeckwith-oddball** [comment]
Using [this document](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test) for setting up the tests / steps.

Can also "copy" the steps in the existing test as `JSON` which may make it easier to export the steps.

**Comment by rbeckwith-oddball** [comment]
It's not exactly the terraform format, but it follows the yaml syntax of the devops repo. I think it's a good starting point.
```yaml
%YAML 1.1
---
tud-prod:
  name: TUD - Status
  type: browser
  request_definition:
    method: GET
    url: https://tud.vfs.va.gov
    allow_insecure: true
  status: live
  locations:
    - us-gov-west-1
  tags:
    - env:prod
    - team:qas
    - check_type:browser
    - ManagedBy:Terraform
  device_ids:
    - chrome.laptop_large
    - firefox.laptop_large
    - edge.laptop_large
  message: |
    @slack-vsp-testing-tools-team - there seems to be an issue with https://tud.vfs.va.gov
  options:
    tick_every: 600
    accept_self_signed: true
    retry_count: 1
    retry_interval: 300000
    monitor_name: TUD - Status
    monitor_priority: 3
```

The `copied` test steps look something like this (from tud-status monitor):
```json
[
  {
    "public_id": "pem-pct-p58",
    "name": "Click on link \"Login to TUD\"",
    "noScreenshot": false,
    "allowFailure": false,
    "params": {
      "element": {
        "url": "https://tud.vfs.va.gov/",
        "targetOuterHTML": "<a href=\"/login/\">Login to TUD</a>",
        "multiLocator": {
          "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"main\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"a\"][1]",
          "co": "[{\"text\":\"login to tud\",\"textType\":\"directText\"}]",
          "cl": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" site-l-wrapper \")][2]/*[local-name()=\"div\"][1]/*[local-name()=\"a\"][1]",
          "at": "/descendant::*[@href=\"/login/\"][2]",
          "clt": "/descendant::*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login to tud\"]]",
          "ro": "//*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login to tud\"]]"
        }
      }
    },
    "timeout": null,
    "isCritical": true,
    "position": 0,
    "type": "click",
    "meta": {
      "key": "6239234700113803",
      "isValid": true,
      "isDraft": false,
      "modifications": {},
      "validity": {}
    }
  },
  {
    "public_id": "iu8-xpu-bqq",
    "name": "Click on link \"Login with GitHub\"",
    "noScreenshot": false,
    "allowFailure": false,
    "params": {
      "element": {
        "url": "https://tud.vfs.va.gov/login/",
        "targetOuterHTML": "<a class=\"usa-button\" href=\"https://github.com/login/oauth/authorize?scope=read:user,read:org,repo&amp;client_id=d9cdce0d74f2e4e4eeb4&amp;redirect_uri=https://tud.vfs.va.gov/oauth/&amp;state=5069fcf02",
        "multiLocator": {
          "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"main\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"a\"][1]",
          "co": "[{\"text\":\"login with github\",\"textType\":\"directText\"}]",
          "cl": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" usa-button \")][2]",
          "at": "/*[local-name()=\"html\"]/*[local-name()=\"body\"]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"main\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"a\"][1]",
          "clt": "/descendant::*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login with github\"]]",
          "ro": "//*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login with github\"]]"
        }
      }
    },
    "timeout": null,
    "isCritical": true,
    "position": 1,
    "type": "click",
    "meta": {
      "key": "3046442236180207",
      "isValid": true,
      "isDraft": false,
      "modifications": {},
      "validity": {}
    }
  },
  {
    "public_id": "5je-ady-zam",
    "name": "Click on body \"VA.gov | Test User Dashboard ...\"",
    "noScreenshot": false,
    "allowFailure": false,
    "params": {
      "element": {
        "url": "https://github.com/login?client_id=d9cdce0d74f2e4e4eeb4&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Dd9cdce0d74f2e4e4eeb4%26redirect_uri%3Dhttps%253A%252F%252Ftud.vfs.va.gov%252Foauth%252F%26scope%3Dread%253Auser%252Cread%253Aorg%252Crepo%26state%3De90561f424",
        "targetOuterHTML": "<body class=\"logged-out env-production page-responsive session-authentication\" style=\"word-wrap: break-word;\">\n    \n\n    <div class=\"position-relative js-header-wrapper \">\n      <a href=\"#start-of-con",
        "multiLocator": {
          "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]",
          "co": "",
          "cl": "/*[local-name()=\"html\"]/*[local-name()=\"body\"]",
          "at": "/*[local-name()=\"html\"]/*[local-name()=\"body\"]",
          "clt": "/*[local-name()=\"html\"]/*[local-name()=\"body\"]",
          "ro": "//*[local-name()=\"body\"]"
        }
      }
    },
    "timeout": null,
    "isCritical": true,
    "position": 2,
    "type": "click",
    "meta": {
      "key": "6951882111387193",
      "isValid": true,
      "isDraft": false,
      "modifications": {},
      "validity": {}
    }
  }
]
```

**Comment by rjohnson2011** [comment]
Chatted with Peter & Ryan B regarding the Terraform modifications process. Found a portion of the `devops` README that seems like a good starting point. Followed those steps and set up terraform on my development environment. 

When needing to supply AWS keys through Parameter Store received an error for insufficient permissions. Reaching out to Operations to resolve this and continue the process for modifying terraforms.

**Comment by rjohnson2011** [comment]
Working on building out the terraform file for va-search, but running into significant blocks with credentials for running terraform commands.

**Comment by rbeckwith-oddball** [comment]
[Uploading... synthetics_test.tf]
The exported synthetic tests. You can find specific tests in the list by searching for the `id` of the test.
Opening the test details in DataDog will show you the ID, or you can hover over the link for the test to see it as well.

**Comment by rjohnson2011** [comment]
FYI: `main.tf` was modified to specify a particular version of the DataDog plugin, as required to successfully run the terraform tests.

`terraform apply` was run for all tests by @rbeckwith-oddball as a result of his elevated permissions status.

**Comment by rjohnson2011** [comment]
Working with R2 to finalize approval of his portion of terraform tests. Took his code and created a pull request here - https://github.com/department-of-veterans-affairs/devops/pull/11386

Currently awaiting approval for the PR and plan on collaborating with R2 on documentation for the DD->Terraform process.

**Comment by rjohnson2011** [comment]
Final two tickets are merged here - https://github.com/department-of-veterans-affairs/devops/pull/11386

Synthetic monitor documentation has been updated for Terraform here -> https://vfs.atlassian.net/wiki/spaces/TTT/pages/2164785226/Synthetic+Monitoring+with+DataDog#Exporting-DataDog-Monitor-to-Terraform
