### ISSUE TITLE
[VA Notify Team Inquiry] Chapter 31 Confirmation of submission success and other questions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#41546]
## Value Statement
**_As a_** VA Notify product manager
**_I want to_** understand status changes for successful Chapter 31 (28-1900) application submissions
**_So that_** I can assess how to implement email confirmation notification functionality. 

---
## Background Context
VA Notify Strike team is working on adding email confirmation notifications to Veterans when they have submitted their applications. Matt mentioned Chapter 31 (28-1900) might be a good candidate. We have a few questions for you and your team.

## Open questions
- Our team took a dive into that form and wanted to verify if we have the right status change for successful submissions. Is “upload_to_vbms” the right place to trigger the notification off of?
- Is there a current notification being sent? It looked like there might have been one but we can’t seem to get it to send when testing in staging.
- Is there specific messaging we need to include in the email?
- Were should the user be sent to check the status of their application?
- Is a notification required after the application has been approved?

## Tasks
- [x] _Assign to a backend developer for review_
- [x] _Send an update to Megan Siddle, product manager for the VA Notify team_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@cohnjesse Who previously touched this code and can speak to historical context? Since this item was added to the backlog after refinement and requires investigation, it is not an ideal candidate for sprint #2 planning. Ideally, the investigative details are ironed out before sprint planning to ensure any work meets DoR.

**Comment by cohnjesse** [comment]
@saderagsdale I am the only engineer on this team that has touched this code before, but I worked on the front end only. This is a back end ticket and the back end engineers that worked on it no longer work on this project. The engineer that picks it up will most likely need to do some research to orient themselves to the code so should over point accordingly

**Comment by saderagsdale** [comment]
@megansiddle Hey Megan! We're pulling this into our upcoming sprint, so should have an answer for you shortly. I'll work with @scottymeyers to figure out the answers to your questions above.

**Comment by saderagsdale** [comment]
@cohnjesse @jerekshoe Can you take a look at this ticket and give guidance? @Mottie mentioned that you have the most context on this.

**Comment by cohnjesse** [comment]
@saderagsdale For sure, here are some answers to the open questions called out in the description of the ticket

1. From our side I am not sure there is a good trigger at this point to trigger a notification email. We use a Sidekiq job to send the claim because it can take quite a while for the upstream service to accept the claim and IF the claim fails we retry using the Sidekiq job. I am not sure if we get a "success" back from the service but we can investigate this further.

2. I don't think we are currently sending a notification when the claim is successfully sent, I don't think we ever found a good trigger for it so I don't think we ever got it working. We can do some more digging on this if needed.

3. Probably better for a UX or design person to answer but yes there will definitely be critical info we will need to include in the email.

4. I would think to the CST but I am not sure A. If these types of claims will show up there and B. What the timeline is for when they would show up there if they do

5. Not sure on this one

**Comment by saderagsdale** [comment]
@megansiddle @cohnjesse should we keep this open or close it?

**Comment by megansiddle** [comment]
This can be closed we got the confirmation email to production! Thanks for all your help @cohnjesse and @saderagsdale!
