### ISSUE TITLE
Update Playbook Documentation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41551]
## Issue Description
Based on the renaming of the heartbeat monitor, there will need to be updates made to our documentation. As well, we would like to make a small tweak to the documentation to improve overall quality and consistency of our documentation. Lastly, we would like to cross-link to the User Guide documentation as well, based off of a request that we received in the Go/No-Go

---
## Tasks
- [x] Update all references to the heartbeat monitor to replace them with: "VA.gov - Homepage interaction - Sign in modal"
- [x] Add a 1-2 overview sentence - This page covers... and is intended for...
- [ ] Add a cross link line directly following the overview which points to the [User Guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2164785226/Synthetic+Monitoring+with+DataDog), 'If you would like to know... please refer to the user guide located here...'

## Acceptance Criteria
- [ ] References have been updated and text has been added
- [ ] Document has been peer-reviewed and approved
