### ISSUE TITLE
Rename Heartbeat Synthetic Monitor

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41550]
## Issue Description
There is confusion around the use of the term 'heartbeat', people feel that the term heartbeat implies a certain type of check that is not representative of what this monitor checks for. We would like to select a new name for this monitor, but don't have a good option identified yet.

The name cleared with all involved is -- "VA.gov - Homepage interaction - Sign in modal"

---
## Tasks
- [x] Discuss in the team channel for suggestions on a new name, and work with your PM/TL to select a new name
- [x] Update the synthetic monitor's name

## Acceptance Criteria
- [x] Monitor has been renamed

**Comment by rbeckwith-oddball** [comment]
The monitor now technically does more than a simple heartbeat.

1. Pulls up the page for www.va.gov
2. Simulates clicking the `Sign In` button
3. Verifies that the `Sign in` header is present
![step-2__1652892900797.jpeg](https://images.zenhubusercontent.com/61265d854c842ee6052dd62e/3919ff78-5e08-4fc9-a248-9e3e047b3679)
