### ISSUE TITLE
Remove duplicated external service integration docs

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#41558]
## Description
External service integration documentation was moved to Confluence a while back. No need to continue to house two copies of the same docs.

---
## Tasks
- [x] Ensure a version of the doc exists in Confluence
- [x] Ensure there are no links pointing back to the GitHub version of the docs in https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services
- [x] Remove GitHub version of the doc(s)

## Acceptance Criteria 
- [x] All external service integration documentation is removed from the `devops` repo and exists in Confluence

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
