### ISSUE TITLE
[Research] Conduct research - Usability of redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41569]
## Description
Conduct usability of redesigned home page with Veterans and others

## Tasks
- [x] Print conversation guide
- [x]  Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x]  Conduct scheduled research sessions
- [x]  Debrief research sessions w/team
- [x]  Post debrief/updates on slack
- [x]  Debrief research sessions into note-taking spreadsheet
- [x]  Download recordings
- [x]  Download notes from Perigean
- [x]  Download final participant list from Perigean
- [x]  Change display name of Perigean Zoom account back to what it was
- [x]  Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Research sessions completed
