### ISSUE TITLE
[Research] Research synthesis and reporting - Usability of redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41568]
## Description
The goal of this research is to get feedback from Veterans and others (including Veterans' family members or caregivers, survivors, and service members) on a survey designed to identify Veteran top tasks. We want to get feedback on the tasks, questions, and instructions before launching the unmoderated survey to a large group of Veterans and others to complete independently (without a researcher present).

## Tasks

- [x]  Clean up notes spreadsheet
- [x]  Write topline summary and share out with team
- [x]  Do data analysis/synthesis of data collected from research
- [x]  Write research report

**Comment by cindymerrill** [comment]
Finished [research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-findings.md) and presented a pre-readout review to Ryan Thurlwell and Dave Conlon, plus Michelle, Wes, and Allison.
