### ISSUE TITLE
Wireframe: Battery 

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4156]
## User Story:
As a Veteran I need to be able review my batteries on the VA.gov so that I can choose the battery that is for my hearing aid.

## Tasks
- [ ] Design a screen element that displays the correct battery for that particular veteran
- [ ] Design a screen that enables the veteran to select their battery for reorder.
- [ ] Attend ideation/whiteboard meeting.
- [ ] Meet with the BAM2 Team and/or DLC team to confirm the design address the items in the Content inventory

## Acceptance Criteria:
Given: That enough research has been completed, User process are understood and MVP as been defined, and ideation meeting has been conducted
When: The team is ready to start the design process
Then: A wire-frame can be built

- [ ] A screen displaying all the required elements from the [Content Inventory page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/content-inventory.md).
- [ ]  Confirm design with DLC

## Next Steps
- Create a Lo-Fi Prototype

## Blockers
- Confirming design element with DLC
- Meeting with DLC
