### ISSUE TITLE
[Research] Conduct Research - Top Task Moderated sessions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41565]
## Description
Conduct top task research with Veterans and others

## Tasks 
- [x] Print [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/conversation-guide.md)
- [x]  Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x]  Conduct scheduled research sessions
- [x]  Debrief research sessions w/team
- [x]  Post debrief/updates on slack
- [x]  Debrief research sessions into note-taking spreadsheet
- [x]  Download recordings
- [x]  Download notes from Perigean
- [x]  Download final participant list from Perigean
- [x]  Change display name of Perigean Zoom account back to what it was
- [x]  Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

**Comment by cindymerrill** [comment]
Moderated 1 session today, 2 no-show/cancelled

**Comment by cindymerrill** [comment]
All research sessions completed. 7 of 10 participants scheduled.
