### ISSUE TITLE
[Research epic] Usability of redesigned VA.gov home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41578]
This research will validate the March 2022 redesign for the VA.gov home page.

## Related artifacts
- [Initiative brief for the Homepage iteration - March 2022](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/home-iteration-initiative-mar2022)
- [Baseline Wayfinding Research on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/research#baseline-wayfinding-research-on-vagov--april-2021)

## High Level User Story/ies

- As a Veteran I want to be able to access self-service tools and processes quickly and easily so that I can manage my own VA benefits
- As a Veteran, caregiver or family member, I want to be able to learn about the different benefits available to me so that I can apply to these benefits.

## Tasks
- [ ] Epic - #40857

Moderated research
- [ ] Create draft research plan - #41415
- [ ] Create draft convo guide - #41574
- [ ] Research prep tasks -
- [ ] Conduct research - #41569
- [ ] Research synthesis and reporting - #41568
- [ ] Post Research Tasks - #41567
