### ISSUE TITLE
Draft research convo guide: Usability of redesigned home page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41574]
## Issue Description
Based on the research plan created in #41415, produce a conversation guide in support of the moderated usability of redesigned home page research project

## Tasks
- [ ] Draft research plan
- [ ] Share plan with a UX team member, PM, PO, and incorporate their feedback
- [ ] Draft recruitment emails for unmoderated card sort
- [ ] Share recruitment emails with a UX team member and incorporate their feedback

## Acceptance Criteria
- [ ] Initial research plan drafted
- [ ] Share with PM/PO for review
- [ ] Draft research plan available for review and use in Veteran User Research session for this initiative.
