### ISSUE TITLE
BE - Vets API - Error Monitoring - Investigate Sentry Error: Pundit::NotAuthorizedError

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#41581]
## Background
The purpose of this ticket is to investigate the root cause of an error that has been logged in Sentry 450,000+ times over the past 90 days (as of 05/18/2022) to determine if it is a legitimate error or a common occurrence that is being logged as an error.

The specific error: `Pundit::NotAuthorizedError not allowed to access? this Symbol`

Click [here](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=url&field=count%28%29&field=count_unique%28issue%29&name=Errors+by+URL&query=event.type%3Aerror+has%3Aurl+message%3A%22not+allowed+to+access%3F+this+Symbol%22&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1) to see the report in Sentry.

## Technical Background
The vets-api project uses an authorization library called [Pundit](https://github.com/varvet/pundit). 

Pundit uses policy classes.  A policy class has methods that are called to authorize a user. Policy classes follow a naming convention - they are suffixed with the word `Policy`.  All policy classes are located in the `app/policies` directory.

Controllers can use Pundit methods to check whether a user is authorized to make a request.  The `Pundit::Authorization` module contains these methods and is included in the `ApplicationController` class so that all controllers can call these methods:

```ruby
class ApplicationController < ActionController::API
 include Pundit::Authorization
end
```

Controllers authorize requests by calling the authorize method using the `before_action` filter which will be called before any controller action is called. The `before_action` filter calls the `Authorization::authorize` method which will automatically infer the policy file based on the parameters passed to it.

Here is an example…

```ruby
class PaymentHistoryController < ApplicationController
  before_action { authorize :bgs, :access? }

  # code omitted…
end
```

The `before_action` filter above will then call this code…

```ruby
# app/models/concerns
module Authorization
 extend ActiveSupport::Concern

 def authorize(policy, method)
   Pundit.policy!(self, policy).send(method)
 end
end
```

In this case, the authorize method will call the BGSPolicy.access? method.

```ruby
# app/policies/bgs_policy.rb
BGSPolicy = Struct.new(:user, :bgs) do
 def access?
   accessible = user.icn.present? && user.ssn.present? && user.participant_id.present?
   increment_statsd(accessible) if user.loa3?
   accessible
 end
end
```

## Questions
Pundit does throw `NotAuthorizedError` errors normally, but what does this part of the error mean? - _not allowed to access? this Symbol_.

- Is this error part of the normal authorization flow for all users or is there an error within Pundit that is causing this?  
- If this is part of the normal authorization flow (most likely), then should the event-type be `error` or should the level be changed to something less severe?

## Tasks
- [x] Determine the cause of the error.
- [x] If authorization is working properly, determine if error level/severity needs to be changed.
- [x] If authorization is working properly and no changes are made to the error level, then determine a way to reduce the 'noise'.

## Acceptance Criteria
BE developers work together to...
- [x] Determine the cause of the error.
- [x] If authorization is working properly, determine if error level/severity needs to be changed.
- [x] If authorization is working properly and no changes are made to the error level, then determine a way to reduce the 'noise'.

**Comment by tpharrison** [comment]
@Samara-Strauss It might be easier to work on one error at a time, so this ticket addresses a specific error that occurs with high frequency across many API controllers.  I will start grooming tickets for the next set of errors, and hopefully we can work through these faster as we learn more.

Based on our conversations, I think we should have 3 developers looking into this - myself, Michele McDonald, and maybe Scott James (since he was involved in some earlier discussions).

**Comment by Samara-Strauss** [comment]
All of this sounds good! I DM'd you with some questions. I'd like to make sure everyone involved coordinates on this through either a Slack chat or meeting (or both) so we can work in a coordinated effort. I can set that up once we confirm if anyone else needs to be involved besides Michel and Scott.

**Comment by ScottyRJames** [comment]
For our team's apps we see this error most often within our `medical_copays` controller. The pundit policy requires `edipi` and `icn` to be present, both of which are pulled from the user's MPI profile. I'm not seeing any correlation to a spike on a specific day with these values missing, Tuesdays seems to have a higher occurrence but nothing egregious

**Comment by tpharrison** [comment]
@michelpmcdonald @ScottyRJames - thanks for looking into this.

Authorization is working as intended. Because this is intended behavior, these failed authorization occurrences should not be sent to Sentry.  After discussing this with @cohnjesse, we think the best approach is to leave things as they are for now.  This issue will need to be addressed as part of a larger, more strategic effort.

cc/ @Samara-Strauss @SKasimow @jacobworrell
