### ISSUE TITLE
[Research] Monitor unmoderated Top Task participation

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41582]
## Description
Monitor unmoderated top task research with Veterans and others

## Tasks (WIP)
- [x] Monitor/track cohort participation
- [x] Report participant codes to Perigean daily
- [x] Download data from Optimal workshop
- [x] Download final participant list from Perigean
- [x] Close out Optimal workshop survey
