### ISSUE TITLE
[Research] Research synthesis and reporting - Top Task Unmoderated survey

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41583]
## Description
The goal of this research is to get feedback from Veterans and others (including Veterans' family members or caregivers, survivors, and service members) on a survey designed to identify Veteran top tasks. 

## Tasks
- [x] Enter task data from moderated sessions as a separate cohort
- [x] Download all data from Optimal Workshop
- [x] Add participant characteristics into MVS checker (for marginalized groups)
- [x]  Do data analysis/synthesis of data collected
- [x]  Write research report

**Comment by cindymerrill** [comment]
Entered all survey data from moderated sessions into a separate cohort in the unmoderated survey so the data can be analyzed together.

**Comment by cindymerrill** [comment]
Having difficulty filtering participants to separate out those who don't have VA healthcare. Waiting for chat response from Optimal Workshop.

**Comment by cindymerrill** [comment]
Finished [report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-findings.md), incorporated feedback from Michelle and UX team. Will present to Dave Conlon tomorrow.
