### ISSUE TITLE
 [Research] Prep Tasks - Usability of redesigned VA.gov home page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41595]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will validate the redesigned VA.gov home page

## Tasks

- [ ]  Share research plan and conversation guide with Shane for approval and recruiting
- [ ]  Make note-taking spreadsheet
- [ ]  Schedule pilots
- [ ]  Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [ ]  Run pilots
- [ ]  Debrief pilots
- [ ]  Send thank you notes to pilot participants
- [ ]  Revise conversation guide
- [ ]  Send instructions to observers
- [ ]  Review recruited participant list for requirements met
- [ ]  Make sure all research sessions are in my calendar
- [ ]  Schedule team debrief sessions once a day
- [ ]  Followup with Perigean re participant list
- [ ]  Other tasks as needed

## Acceptance Criteria
- [ ]  Completed prep tasks in support of research actions
