### ISSUE TITLE
Create a Conversation Guide for "View and update my representative" and "View my payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4160]
## Story  
As a design researcher, I want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users I will be communicating with.

## Considerations
Conversation guides are usually incorporated into Research Plans but because they are large enough, we seperate them.  Both are considered deliverables.

## Task
- [ ] Coordinate with Shawna on some of the questions to ask in the conversation guide
- [ ] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [ ] Conversation Guide has been sent to Shawna for review
