### ISSUE TITLE
HLR: Update wizard start page content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41605]
## Description

The first paragraph of the [Higher-Level Review wizard](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start) content needs to be updated to be [more direct & task-focused per a content review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34879#issuecomment-1129110225)

Recommendation:

> revise the first sentence ("Use this form...") like this:
>
> Is this the form I need?
>
> Use this form if you disagree with our decision on your claim and want a senior reviewer to review your case again. You can’t submit any new evidence with a Higher-Level Review.

## Tasks

- [ ] Update HLR wizard content

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
