### ISSUE TITLE
Remove "Calendly" from title of Orientation Sessions page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41617]
## User Story
As a VFS team member, I do not want encounter unfamiliar words in Platform Website title pages so that I can easily find the guidance that I'm looking for.

- Intended Audience: VFS teams
- Desired Outcome: Remove reference to "Calendly" in the Orientation Sessions page
- Due Date: TBD

## Description
It has been reported that the Platform Website page, "Calendly Orientation Sessions" is confusing as not many people know what Calendly is, nor do they need to. The page is a list of the Orientation Sessions (with Calendly being the tool used to sign up) and the intent of the page should be clear from the title.

## Artifacts Needing Updates
[Platform Website: Calendly Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/Calendly-Orientation-Sessions.2133393543.html)

## Tasks
- [ ] Remove Calendly from title of of Orientation Sessions

## Acceptance Criteria
- [ ] Title of "Calendly Orientation Sessions" page has been renamed to "Orientation Sessions" 
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by jimuhh** [comment]
@CherylEvans @shiragoodman I ran an open text search on the linked documents and confirmed that all instances of the word, "calendly" had been removed. Looks good!

**Comment by shiragoodman** [comment]
@jimuhh I think you may have misunderstood the task here. All we want to do in this ticket is remove "Calendly" from the title of the ["Calendly Orientation Sessions" page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) so the page is just tiled, "Orientation Session" - do you follow?

**Comment by CherylEvans** [comment]
@shiragoodman Shira.  I misunderstood.  I will add it back everywhere EXCEPT the title and then submit for peer review.

**Comment by CherylEvans** [comment]
I misunderstood, because the Acceptance Criteria stated, " Calendly events have been updated".

**Comment by CherylEvans** [comment]
@Shira "Calendly" has been removed from the appropriate Platform Orientation [page](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions) in confluence. Published.

**Comment by CherylEvans** [comment]
@shiragoodman @chaseakirby "Calendly" has been removed from title of Orientation Sessions [page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions). Closing ticket, and moving to Closed pipeline.
