### ISSUE TITLE
[BE] Update betamocks to add an optional delay in returning the mocked responses

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#41611]
## User Story
It will be great to optionally allow the responses to be delayed by some configured number of seconds. This will be especially useful in simulating real world delays from downstream services when doing load testing and mocking downstream services.

This could be done by adding a `response_delay` config to the endpoints which, if defined will cause the response to be delayed by that many seconds.

Proposed config example:
```
- :name: "SlowService"
  :base_uri: "..."
  :endpoints:
    - :method: :post:
      ...
      :response_delay: 1
    - :method: :get
      ...
      :response_delay: 5
```

## Tasks
- [x] [BE] Create PR in betamocks repo
- [ ] work with platform for approval and release
- [ ] update vets-api to use the updated betamocks gem

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
