### ISSUE TITLE
[Discovery] Integrate DogStatsd

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#41619]
## Coclusion

Integrating DogStatsd will not generate the HAProxy metrics in Datadog. HAProxy has to be correctly configured in the Devops. This [issue] (https://github.com/department-of-veterans-affairs/vets-api/issues/9838) incorporates the HAProxy data.

### Issue Description

Datadog will be replacing Grafana with the Kubernetes integration. Grafana has the functionality to calculate quantiles, probability distributions, from the data received from Statsd. This functionality is heavily measured in the External Service Performance Indicators Dashboard and the monthly SLO Report. Datadog does not have the builtin functionality to calculate quantiles. In order to measure distributions in Datadog, metrics must be sent to Datadog, as a distribution type, using their metrics aggregation service, DogStatd.

---

### Tasks

  
- [x] (Open a ticket with the devops team) [https://github.com/department-of-veterans-affairs/devops/pull/11282]
- [x] (Add datadog-statsd gem to vets-api repo)[https://github.com/department-of-veterans-affairs/vets-api/pull/9889]
- [ ] Find where the forward proxy data is being sent to datadog.  Determin ewho can do this work once the forward proxy is being sent. (https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/#distribution)

---

### Links

[DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent)
[Grafana Graphs](https://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1)
[Datadog Distribution Metrics](https://docs.datadoghq.com/metrics/types/?tab=distribution#metric-types)
