### ISSUE TITLE
Remove step from Platform Orientation template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41613]
## User Story
As a new VFS team member, I want to not encounter any unobtainable steps in Platform Orientation so that I can easily complete the steps in the Platform Orientation process.

- Intended Audience: VFS teams
- Desired Outcome: Platform Orientation gh template updated
- Due Date: TBD

## Description
In ticket #39321, Governance team added the process of getting added to vets.gov-write GH team to the Platform Orientation process, as opposed to a step that occurs before opening this ticket. There are certain steps that cannot be completed now that vets.gov-write access is now part of this process, including adding GH labels to the ticket. As such, the step, " Add your teams github label under Labels" needs to be removed from the ticket.

## Artifacts Needing Updates
[Platform Orientation Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)

## Tasks
- [x] Remove "How to fill out this ticket - Add your teams github label under Labels"
- [x] Review other steps to determine if any other steps need removed

## Acceptance Criteria
- [ ] GitHub Template: Platform Orientation has been updated
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@chaseakirby I removed "[ ] Add your teams github label under Labels" from the "How to fill out this ticket" section.  Created PR, and will S&M after your review/approval.

**Comment by chaseakirby** [comment]
@CherylEvans I reviewed and approved your PR. You can go ahead and Squash and Merge!

**Comment by CherylEvans** [comment]
@shiragoodman @chaseakirby 
Confirmed: "[ ] Add your teams github label under Labels" from the "How to fill out this ticket" has been removed from the Platform Orientation ticket.  I will close out the ticket and move to pipeline "Closed".
