### ISSUE TITLE
Create must, should, consider guidance for Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41625]
## User Story
As a VFS team, I want to know how to interpret the feedback received at Design Intent and Midpoint Review so that I know how to prioritize appropriately. 

- Intended Audience: VFS Teams
- Desired Outcome: New guidance drafted on must, should, consider
- Due Date: 

## Description
VFS teams may not have a clear understanding of the differences between must, should and consider in the feedback tickets for Design Intent and Midpoint Review. The must, should, consider model is built off of the [MoSCoW prioritization model.](https://www.productplan.com/glossary/moscow-prioritization/)

@shiragoodman has previously explained must should consider as:
must - likely to result in a documented issue ticket referencing the VA.gov Experience standards
should - promotes best practices in the industry, by may or may not result in an issue ticket
consider - while the feature of the product isn't incorrect or wrong, there may be a better way of handling it

## Artifacts Needing Updates
N/A

## Tasks
- [x] Create documentation draft detailing the definitions for Must, Should, and Consider 
   - draft should also include why we use Must, Should and consider at Design Intent and Midpoint Review, but not Staging Review
- [x] Share with Governance team for internal peer review
- [x] Make changes as appropriate
- [x] Share on #platform-collaboration-cycle channel for approval from OCTO Practice area leads

## Acceptance Criteria
- [x] OCTO Practice area leads have approved of the proposed definitions
- [x] Governance team is in alignment on the proposed definitions

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
Not in this ticket. Potential Research on how VFS teams use Must, Should, Consider feedback.

**Comment by shiragoodman** [comment]
@jimuhh i updated the tasks and AC per our discussion yesterday. Please move forward with creating draft documentation focusing on the definitions of must, should and consider. Once the definitions are approved, we'll work on incorporating it into the existing documentation. thanks!

**Comment by jimuhh** [comment]
Will do.

**Comment by jimuhh** [comment]
@shiragoodman OK. Those changes have been made. [Please confirm](https://vfs.atlassian.net/l/c/zPf3vBF9).

**Comment by jimuhh** [comment]
OK. Cheryl's corrections have been made. [Please confirm](https://vfs.atlassian.net/l/c/7t1E05ed)

**Comment by jimuhh** [comment]
@shiragoodman I made all those except for linking to experience standards page which I haven't looked at in a while and whose location I forgot. Can you supply? Thx.

**Comment by jimuhh** [comment]
Changes made. Exp standards link added. Pls confirm
