### ISSUE TITLE
Investigate E2E EAuth issues

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#41626]
## Description
Look into the eAuth issue that is causing E2E Cypress tests to break.

Background information
- https://dsva.slack.com/archives/C02V265VCGH/p1652882476538359

## Tasks
- [x] Investigate what is causing E2E Cypress tests to break
- [x] Implement fixes to ensure .skip is not used in E2E Cypress tests

## Acceptance Criteria
- [x] In CI/CD, E2E Cypress tests pass as normal
