### ISSUE TITLE
Add/clarify observer guidelines on relevant Platform pages

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41630]
## User Story
"As a researcher, I want clear and updated guidance on observers, to keep research participants safe and empowered."

- Intended Audience: VFS
- Desired Outcome: add updated guidance to relevant documentation
- Due Date: 

## Description
We want to clarify guidelines surrounding how many people from the VA side should be in a given session. Observing research is important, so we should also add guidance on the who should join research with the given limits.
As discussed on several occasion, there is broad agreement that the maximum number who join a remote session on VA side should by 5-6. This is already listed on [Platform page for Research Safety and Emergency Exit Strategies](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Safety-and-Emergency-Exit-Strategies.2143649793.html#ResearchSafetyandEmergencyExitStrategies-Creatingasafespaceforparticipants), but may be relevant to add elsewhere.

Part two is to clarify that it's not just for research that requires heightened sensitivity and not just a consideration, but it's official guidance for researchers to hold observers in the waiting room for all research until AFTER the participant agrees to have additional folks join on the VA side.

Part three (TBD) is to add guidance against dialing in additional researchers into a single zoom user window.

see also [this research-ops slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1652889118717619)
see also [this other research-ops slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1648557690447219?thread_ts=1648149659.942869&cid=C0216PL32HJ)

## Artifacts Needing Updates
 [Platform page for Research Safety and Emergency Exit Strategies](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Safety-and-Emergency-Exit-Strategies.2143649793.html#ResearchSafetyandEmergencyExitStrategies-Creatingasafespaceforparticipants)
- [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html#ResearchChecklist-5.Conductsessions)
- [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Observers)
- [Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/Observer-guidelines.1622311177.html)
- [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [convo guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

## Tasks
- [ ] Determine what changes/additions should be made to which pages/templates

## Acceptance Criteria
- [ ] GitHub Template: _Page Name_ has been updated
- [ ] Platform Website: _Page Name_ has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
I think all the pages look good! 
One question, I didn't see anything for "add guidance against dialing in additional researchers into a single zoom user window". 
Are we thinking along the lines of not instructing them either way will result in each observer joining independently?

**Comment by claytonzook** [comment]
@chaseakirby that should be the 3rd H2 heading on [this page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2239791162/Clayton+-+Draft+New+Page+-+Moderator+Guidance+for+Observers+-+WIP)

**Comment by chaseakirby** [comment]
@claytonzook Thanks! Note to self. Scroll further next time before commenting. 
That also looks good so I think the non-ready changes are ready to be published and we can [cut this piece for the next ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2239791162/Clayton+-+Draft+New+Page+-+Moderator+Guidance+for+Observers+-+WIP#Protocol-for-adding-observers-to-a-session) into another place so we don't have comments that will get flagged during publishing.

**Comment by claytonzook** [comment]
Other changes are now staged for the next Platform publish (Tues - 6/28)

**Comment by shiragoodman** [comment]
@claytonzook please confirm publishing to PW, then close ticket

**Comment by shiragoodman** [comment]
I confirmed all updated pages have been published. Closing ticket.
