### ISSUE TITLE
526ez | Create keyboard-only e2e tests

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41632]
## Value Statement
**_As a_ frontend developer**
**_I want to_ ensure that the 526 can be completed with only the keyboard**
**_So that_ veterans that can only use keyboards are able to complete the 526 form** 

---
## Background Context
- All VA form applications are expected to be able to be completed by veterans with disabilities. Some veterans are only able to complete the 526 form via keyboard, so we need to ensure that they are still able to complete the 526 form. 

## Acceptance Criteria
- [ ] Tests are written to ensure that the form can be completed with a keyboard

## Out of scope
- We need to write tests to cover other scenarios in the future, but for now we should at least establish tests for the minimal scenario

## Tasks
- [ ] Determine what the minimal example looks like
- [ ] Write tests
- [ ] Create a PR for merging

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@jaredcunha @rocio-desantiago Can we dupe this ticket and re-estimate only the remaining work? This has been an "8" for over a month now, so I'm having a hard time understanding complexity/what's left.

**Comment by rocio-desantiago** [comment]
@saderagsdale I'd say maybe divvying it into chapters may be more realistic and then estimating the chapters separately now that we have more awareness of the form's length.

**Comment by saderagsdale** [comment]
@saderagsdale @sortizsh split into two smaller tickets for chapters 3 and 4.

**Comment by Mottie** [comment]
I'd say let's pause this work until the new 526 has been implemented.

**Comment by saderagsdale** [comment]
@sortizsh @rocio-desantiago we're going to pause the remaining work on this for now. A new version of the form will come out that will change our E2E testing needs. We'll pivot to the supplemental claims work.

**Comment by saderagsdale** [comment]
Closing this ticket for now.
