### ISSUE TITLE
Update rate on NADL page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41644]
## Issue Description
Stakeholder Eric Jones informed us we need to update the rate on our [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. 

The new rate is **5%**

This appears in the fourth bullet under the H2 Why might I want to get an NADL?

## Tasks
- [x] Update rate in Drupal (Aliyah)
- [x] Review change (Laura)
- [x] Publish page (Laura)
- [x] Notify stakeholder that change has been made (Randi)

## Acceptance Criteria
- [x] Rate is updated on live page

**Comment by aliyahblackmore** [comment]
Rate was updated in Drupal! @laurwill this is ready for you!

**Comment by laurwill** [comment]
Thanks Aliyah! @RLHecht, I published this update

**Comment by RLHecht** [comment]
@aliyahblackmore The stakeholder just emailed to say that this rate goes into effect May 30. Could you please put back the old rate and publish the page and save the new rate in draft form? I'll reach out to him about us publishing on May 31 since the 30th is a holiday.

**Comment by aliyahblackmore** [comment]
@laurwill This was changed back to 4.5% and is ready for you to publish. Once you have published, I will save the new rate (5%) in draft form!

**Comment by laurwill** [comment]
Published!

**Comment by aliyahblackmore** [comment]
Thanks @laurwill ! @RLHecht A new draft has been saved with the 5% rate, to be published on May 30 or 31!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket
