### ISSUE TITLE
Open up RFC Process for SharePoint integration

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#41654]
## Issue Description
We need to work with platform to get feedback on the planned approach for uploading PDFs to SharePoint. We can begin this discussion with starting the [RFC](https://github.com/department-of-veterans-affairs/va.gov-team/discussions/38717) process. 

---
## Tasks
- [x] Fill out RFC template in GitHub discussions with planned implementation and detailed design

## Acceptance Criteria
- [x] We have an open RFC discussion to begin working through SharePoint integration
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
[RFC](https://github.com/department-of-veterans-affairs/va.gov-team/discussions/42648)
