### ISSUE TITLE
Copyedit and publish changes to COVID-19 testing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41662]
## Issue Description
Danielle made changes to our [COVID-19 testing at VA](https://www.va.gov/resources/covid-19-testing-at-va/) page. We need to do a final copyedit with the pre-publishing checklist and publish the page.

She reordered a few sections and added one new section about getting free self-test kits from VA.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=42902

## Tasks
- [ ] Copyedit page (Laura)
- [ ] Use pre-publishing checklist (Laura)
- [ ] Publish page (Laura)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by laurwill** [comment]
Hi @RLHecht — I copyedited, did the checklist, and published. 

Also noting that per a chat with Danielle, I made small tweaks to the content about the COVID.gov test kits and made the same changes in draft form on the COVID FAQs page. Additional updates to that FAQs page are tracking in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/40829
