### ISSUE TITLE
Address having two locations for Zoom use in research

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41669]
## User Story
"As a researcher, I want clear and updated guidance for using Zoom on Platform, so I have a single source of truth"

- Intended Audience: VFS
- Desired Outcome: add updated guidance to Platform
- Due Date:

## Description
There is [a GH page on How To Use Zoom for User Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/during-research/zoom-instructions.md) that hasn't been marked as deprecated. There is also a [Platform page on using Zoom for research](https://depo-platform-documentation.scrollhelp.site/research-design/Using-Zoom-for-research.1622180012.html). Information should be double check to ensure all needed guidance was migrated to Platform, then the GH page should be marked as deprecated.

## Artifacts Needing Updates
[Platform page: Using Zoom for research](https://depo-platform-documentation.scrollhelp.site/research-design/Using-Zoom-for-research.1622180012.html)
[GH page: How To Use Zoom for User Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/during-research/zoom-instructions.md)

## Tasks
- [x] Compare information on the GH and Platform page
- [x] Update the Platform page if any guidance is missing
- [x] Mark the GH page as deprecated

## Acceptance Criteria
- [x] GitHub Template: [GH page: How To Use Zoom for User Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/during-research/zoom-instructions.md) has been marked as deprecated [using this guidance](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1397194753/Deprecate+a+page+in+GitHub)
- [ ] Platform Website: [Platform page: Using Zoom for research](https://depo-platform-documentation.scrollhelp.site/research-design/Using-Zoom-for-research.1622180012.html) has been updated if needed
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@CherylEvans I have reviewed this ticket and confirmed it's ready to be worked on. 

Please comment here when it's ready to be peer reviewed.

**Comment by CherylEvans** [comment]
@shiragoodman Sounds good.  I will update my [Draft Page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2229338113/Cheryl+-+Copy+of+How+To+Use+Zoom+for+User+Research) and Publish to [Source Page](https://vfs.atlassian.net/wiki/spaces/RD/pages/1652392082/How+To+Use+Zoom+for+User+Research).  I will then create another ticket for adding the "Using Assistive Technology in Zoom" link to this page, once it's drafted.

**Comment by CherylEvans** [comment]
@shiragoodman [Ticket 43044](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/43044) has been created to link "Using Assistive Technology in Zoom" to "How To Use Zoom for User Research", once it's been created/published.

**Comment by CherylEvans** [comment]
@shiragoodman Platform page has been updated.  Need to complete "Mark GH page as deprecated."
