### ISSUE TITLE
[Tech Discovery] Analysis of va.gov vs. EVSS endpoint workload

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4166]
## User Story:
As a back-end engineer, I need to understand what is being done on the va.gov end vs. what is being done on the EVSS end so that I can be prepared to identify the work required to be done on our end when connecting to the BIP Claim Status API.

## Tasks
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
- [ ] Work effort identified by responsible parties' API endpoints
