### ISSUE TITLE
Address having two locations for Mobile Research guidance

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41673]
## User Story
"As a researcher, I want clear and updated guidance for Mobile Research on Platform, so I have a single source of truth"

- Intended Audience: VFS
- Desired Outcome: add updated guidance to Platform
- Due Date:

## Description
There is [a GH page on Mobile Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/mobile-research-guidelines.md) that hasn't been marked as deprecated. There is also a [Platform page on Researching with mobile users](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Researchingwithmobileusers). Information should be double check to ensure all needed guidance was migrated to Platform, or if additional guidance needs to be added. Once completed the GH page should be marked as deprecated.

## New Artifacts 
Possibly a new Platform page for mobile research

## Artifacts Needing Updates
[Platform page: Researching with mobile users](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Researchingwithmobileusers)
[GH page: Mobile Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/mobile-research-guidelines.md)

## Tasks
- [ ] Compare information on the GH and Platform page
- [ ] If there is any information missing, decide if there needs to be a new page or if the current section for mobile should be updated
- [ ] Mark the GH page as deprecated

## Acceptance Criteria
- [ ] GitHub Template: [GH page: Mobile Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/mobile-research-guidelines.md) has been marked as deprecated
- [ ] Platform Website: [Platform page: Researching with mobile users](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Researchingwithmobileusers) has been updated if needed
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
