### ISSUE TITLE
Move Research Synthesis guidance to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41696]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

Assignee: @it-harrison 
Peer reviewer: @CherylEvans 

## Description
There is [guidance on Research Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## Impacted Artifacts
[How to: Research Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md)

## Tasks
- [x] Decide where on Platform this information should live - likely a new page (@naomimarcussen can help)
- [x] mark GH page [Research Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md) as deprecated [using this guidance](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1397194753/Deprecate+a+page+in+GitHub)
- [x] Validate that all links on new Platform Website page point to other Platform Website pages (if applicable) and not gh pages
- [x] Validate that all content within guidance is up to date and accurate. For anything that is outdated:
   - [x] if it is a simple fix, work with @naomimarcussen to make the change before publishing.
   - [x] if the fix requires rewriting/reorganizing of the content, create a follow up ticket using the Governance team issue template and document the necessary changes. We will publish the guidance to Platform Website as-is. Work with @naomimarcussen to determine if a, "This guidance may not be up to date" warning message should be added to the Platform Website page.
- [ ] @naomimarcussen - should the new Synthesis page be integrated into the Research Checklist?

## Acceptance Criteria
- [x] VFS teams are able to find guidance on research synthesis on the Platform Website/Research
- [x] VFS teams are redirected to the Platform Website when they encounter deprecated research synthesis guidance on gh
---

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Hi @CherylEvans [here is a draft of this document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2415493233/Research+Synthesis).

**Comment by CherylEvans** [comment]
@it-harrison I am still reviewing your research synthesis Confluence page, but noticed that the Research Synthesis page on GH has not been deprecated.  Will you please update the tasks section with what you have done so far?
Are you wanting me to **only** peer review the [Research Synthesis](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2415493233/Research+Synthesisurl) page you created in Confluence, as opposed to the entire ticket?

**Comment by it-harrison** [comment]
> @it-harrison I am still reviewing your research synthesis Confluence page, but noticed that the Research Synthesis page on GH has not been deprecated. Will you please update the tasks section with what you have done so far? Are you wanting me to **only** peer review the [Research Synthesis](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2415493233/Research+Synthesisurl) page you created in Confluence, as opposed to the entire ticket?

@CherylEvans good point - I was waiting to deprecate until the page was published. I will update the ticket now.

**Comment by CherylEvans** [comment]
@it-harrison You are correct, you don't deprecate until it has been published.  I was under the impression that you had already published it for some reason.  If it's not published, don't deprecate it yet.  I will have my edits done soonest, so you can incorporate.  Sorry about the confusion on my part.

**Comment by CherylEvans** [comment]
@it-harrison Just to confirm, once you add the recommended changes that @naomimarcussen and I have suggested, your draft [Research Synthesis](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2415493233/Research+Synthesisurl) document should be good to publish.  Once published, the rest of the tasks can be completed.  :-)
