### ISSUE TITLE
Move Screen Reader research guidance and check list to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41695]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

- Intended Audience: VFS teams
- Desired Outcome: guidance moved to Platform and marked deprecated in GH 
- Due Date: 

## Description
This ticket and ticket #40879 shall be worked on at the same time.

Researching with participants who use screen readers requires different considerations. There is some [guidance on VA github for researching with participants who use screen readers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech/screenreaders.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## New Artifacts 
- New Page for researching with participants who use screen readers

## Tasks
- [ ] Decide where on Platform this information should live
- [ ] [guidance on VA github for researching with participants who use screen readers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech/screenreaders.md) has been created and maintained by [@joshkimux](https://github.com/joshkimux). Notify Josh of the intention to move to Platform Website.
- [ ] Verify with [@joshkimux](https://github.com/joshkimux) that all content within the existing gh page is current and up to date.

## Acceptance Criteria
- [ ] Platform Website: has been updated with information about Screen Reader participants
- [ ] GH page [Screen Readers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/assistive-tech/screenreaders.md) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@claytonzook is the goal of this ticket (and #40879) to just link to them in the Research Template, or do we want to have the article published on Platform Website (like this [Recruiting Participants](https://depo-platform-documentation.scrollhelp.site/research-design/recruiting-participants) page)?

**Comment by claytonzook** [comment]
@shiragoodman The main idea was to simply publish this content from GH onto a new Platform page. I do think there will be a bit of overlap on these two GH docs, so I think it'll be best for now to combine them onto one Platform page.

But that's a good point about the Research Plan template, there is a link to one of these documents in the [Methods section on the template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md#method) (add'l resources bullet 5) and that should also be updated to point to the brand new Platform page for Assistive Tech (AT) research

**Comment by shiragoodman** [comment]
@claytonzook while I do agree that there is likely overlap, combining onto 1 page may end up being more work and I'm not sure we want to commit to that at this time. I think the goal of both these tickets is to get the content onto Platform Website/Research and Design.

The reason I asked about linking from the Research Template is because you had it documented as AC on ticket #40879 (both the Research Template and Trauma Informed Research Template - I didnt even know the latter existed) BUT you don't have it documented as AC on this ticket. Please confirm if both guidance docs should be referenced in both research templates.

**Comment by shiragoodman** [comment]
ok i'll review what's written in this ticket, get it updated if necessary and share with you for review. thanks, Clayton!

**Comment by chaseakirby** [comment]
Merged into #40879, closing.
