### ISSUE TITLE
Master detail landing pages: implementing SEO

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#4169]
## User Story:
As a veteran performing organic search, I need Va.gov forms at the top of my search results so that I can access the va.gov forms easily.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Record SEO terms on each landing page - 6 hrs
- [x] Adjust copy as needed - 40 hrs
- [x] @jenniferlee-dsva  review the deck - 10 hrs

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [x] Complete copy deck of of all master detail landing pages.

Related to ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2020

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @Karak888 - Hello! Here is the complete copy deck. A few things to note:
- Helpful links section
Jen, per our last phone convo, I customized the "helpful links" by page, using 1-2 highly relevant links rather than the 4 standard ones (which were dwarfing the page content in some cases). There are a few instances in which where there was no highly related link, so I left the 4 standard ones.
- Form 10-0137
Unable to access. Keep getting Adobe error message. Noted in copy deck.
- Form 22-0094 
Neither Selina or I can find it. Noted in copy deck. 
[va-forms-slps-copy-v0.6_12-31-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4012691/va-forms-slps-copy-v0.6_12-31-19.docx)

**Comment by Karak888** [comment]
I am moving this to close for copy deck for Search landing pages.  If new edits are needed we can track/ take care of them at that time.  Thanks

**Comment by jenniferlee-dsva** [comment]
@Karak888 - this ticket has not been completed and should remain open. Laura has been sidetracked to meet HLR and View Disability Ratings static launch pages, but this item is the next priority to finish. You can put it in ready column instead of in progress to better reflect status.

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - doh. Just saw your upload of final deck. Will take a closer look, but on glance wrt the forms you couldn't locate - could you go back to Nedie's Google Analytics (GA) spreadsheet that listed the forms URLs and landing page URLs?  I assume those 2 forms (22-0094 and 10-0137 are included in the copydeck bc they were either on the list of GA top searched forms or are somehow mapped to one of our digital products. 

We can send that page in the copydeck to the form business owner, so they can either provide us correct form link or perhaps they need to update or retire their form. All of these pages are going to be shared with the specific form owners in any case as a FYI, and to give them a chance to validate for accuracy.

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - I located the page and form for 10-0137. It's the health care advance directive/living will form. This form does not get a lot of searches (according to the data Nedie shared with us), so I'm assuming we are including a form landing page for it because it is associated or incorporated into our digital health care benefit application -- is that right? 

Here is the form landing page that includes the form itself. It's from Nedie's original GA spreadsheet:
https://www.va.gov/vaforms/form_detail.asp?formno=0137

**Comment by jenniferlee-dsva** [comment]
Hi @lwalsh617 - I'm reviewing your forms landing page doc, and as I'm checking against our master list of digital products and Selina's forms db spreadsheet, I'm finding several discrepancies, so it's taking me a longer time to validate. This was a level of fact checking I hadn't expected. Let's sync on call, so I can point out some examples -- it would be great if you could go over this again with those problem areas in mind for revising. I'd love to send as clean a deck as possible to SMEs. 

@Karak888 FYSA

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @Karak888 @lunascoop - Attached are my notes from a call I just had with Jen. @lunascoop, if you have bandwidth, would you be up for some QA
[Forms SLPs QA Checklist.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4036512/Forms.SLPs.QA.Checklist.docx)
? Would either be late today or tomorrow morning. Waiting on the spreadsheet Jen is editing so we an work off that.

**Comment by lunascoop** [comment]
@lwalsh617 I'd be happy to assist with that.

**Comment by jenniferlee-dsva** [comment]
GH not letting me upload files. See Slack for doc with comments:  https://dsva.slack.com/archives/C52CL1PKQ/p1578534523074500?thread_ts=1578534186.074000&cid=C52CL1PKQ

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @Karak888 -- The new deck, with revisions based on Jen's feedback, is on Slack: https://dsva.slack.com/archives/C52CL1PKQ/p1578689046263600
Attached is my capture of Jen's feedback along with another change or two I made. All has been completed in the copy deck.
[Forms SLPs QA Checklist.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4047911/Forms.SLPs.QA.Checklist.docx)

**Comment by lwalsh617** [comment]
Trying once more to upload deck here...
[va-forms-slps-copy-v1.0_01-10-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4047912/va-forms-slps-copy-v1.0_01-10-20.docx)

**Comment by lwalsh617** [comment]
@jenniferlee-dsva - The attached version (v1.2) reflects our call today about "related to" fields. After our call, I compared it to VA-forms-mvp-new-db-fields-010620-JL, ensuring that your feedback to Selina's version is incorporated. 
One note on form 21-22, Appointment of Veterans Service Organization as Claimant's Representative. I had included "Pensions" under "related to" in my deck. The spreadsheet did not include "pension" under "related to" and you had not said to add it. I discussed it with Selina, and we both felt it should stay, so she added it to spreadsheet. Let us know if that's incorrect.

**Comment by jenniferlee-dsva** [comment]
Per comment on the corresponding db fields ticket: #4339

@lunascoop and @lwalsh617 to connect on a few discrepancies btn spreadsheet and copydeck.
Per call w/Laura: Confirming yes to remove edu form 28-1990 and 8832 from both copydeck and spreadsheet.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva - The attached version (v1.2) reflects our call today about "related to" fields. After our call, I compared it to VA-forms-mvp-new-db-fields-010620-JL, ensuring that your feedback to Selina's version is incorporated.
One note on form 21-22, Appointment of Veterans Service Organization as Claimant's Representative. I had included "Pensions" under "related to" in my deck. The spreadsheet did not include "pension" under "related to" and you had not said to add it. However, I discussed it with Selina, and we both felt it should stay, so she added it to spreadsheet. Let us know if that's incorrect. Thanks!
[va-forms-slps-copy-v1.2_01-14-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4061203/va-forms-slps-copy-v1.2_01-14-20.docx)

**Comment by lwalsh617** [comment]
[va-forms-slps-copy-v1.2_01-14-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4061217/va-forms-slps-copy-v1.2_01-14-20.docx)
@jenniferlee-dsva - The revised deck attached reflects our phone call today regarding "related to" fields. After our call, I checked the deck against your comments to Selina's spreadsheet. Selina and I chatted to rectify discrepancies. One item to note, we wound up adding "pension" under "related to" in the spreadsheet for Form 21-22, Appointment of Veterans Service Organization as Claimant's Representative. It was in the deck, and we felt it it made sense to keep it. Let us know if that's an error. Thanks!

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - thank you - I've edited and provided a clean document for first round of SME reviews with VHA. This can be closed as validated. 

Final (review) doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages-copydeck-012620.pdf
