### ISSUE TITLE
Product List: Update the automated collection to support JSON

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41702]
## Issue Description
We currently have a number of fields of information that are being collected in an automated fashion for our product directory. These are currently built around adding these values into a CSV once they are determined. We need to alter this script to add the values to a JSON file properly.

---
## Tasks
- [x] Alter the automated data collection script to account for adding the values to a JSON file as opposed to a CSV.

## Acceptance Criteria
- [x] Our automation script correctly updates our JSON-based product directory.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/21223

I should be able to finish this today. I made all the seemingly required changes to the code but haven't run it yet.

TODO:
- debug code
- update tests

**Comment by holdenhinkle** [comment]
This is merged - https://github.com/department-of-veterans-affairs/vets-website/pull/21223
