### ISSUE TITLE
Move Inclusive Research guidance to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#41709]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

- Intended Audience: VFS teams
- Desired Outcome: Inclusive research guidance moved to Platform
- Due Date: 

## Description
There is some [GH guidance on Inclusive Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/readMe.md) and [GH guidance on inclusive recruitment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md#), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## New Artifacts 
- New Platform page for inclusive research

## Tasks
- [ ] Decide where on Platform this information should live
- [ ] mark GH pages as deprecated once info is on Platform
- [ ] check for links to these GH pages and update, some include:
   - [ ] [Platform Page on recruitment](https://depo-platform-documentation.scrollhelp.site/research-design/Recruiting-Participants.1958773044.html#RecruitingParticipants-Inclusiveresearch)
   - [ ] [Research Plan Template]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md#recruitment)

## Acceptance Criteria
- [ ] Platform Website page for inclusive research is created
- [ ] GH page marked deprecated [Inclusive Recruitment Strategies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/recruitment.md)
- [ ] GH page marked deprecated [Inclusive Research Guidelines v2.0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/readMe.md)
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@naomimarcussen @sterkenburgsara @it-harrison  Hi Naomi! :-) I have created drafts of both of these pages. [Guidance on Inclusive Recruitment](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403401835/41709+-+Cheryl+Draft+Cheryl+Draft+Guidance+on+Inclusive+Recruitment) and [Guidance on Inclusive Research](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403500153/41709+-+Cheryl+Draft+Guidance+on+Inclusive+Research) Wanted to reach out and get your input on these docs.  I am definitely not a research expert by any stretch, but do see that some of the content needs reworking.  I don't see anything major, simply edits that will affect readability and flow.  I am going to create a new ticket to address the major changes you recommend, but wanted to get your approval to make the minor edits so it can be published quickly.  The other question I had was with regard to the location of the new documents.  Please let me know your thoughts, and I will work to make sure everything is completed in a timely manner, and in accordance with your guidance/input.  Thanks again!

**Comment by naomimarcussen** [comment]
Thank you for working on this @CherylEvans! I'd say these pages can live in the [Research: Planning and Recruiting section](https://depo-platform-documentation.scrollhelp.site/research-design/research-planning-and-recruiting). 

Also, feel free to add an intro and any other edits to make it flow better. These 2 pages are just a couple in a collection linked to from the [Inclusive Research Guidelines](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403500153/41709+-+Cheryl+Draft+Guidance+on+Inclusive+Research) in another ticket.

**Comment by CherylEvans** [comment]
@naomimarcussen You're quite welcome! :-) I was thinking I would nest them with [Planning and recruiting resources](https://depo-platform-documentation.scrollhelp.site/research-design/research-planning-and-recruiting#Research:Planningandrecruiting-Planningandrecruitingresources), if that's okay with you.  I will write short introductions to both, and once you give the thumbs up on those, I will create the pages, and hopefully they will be published by Thursday. 
FYSA @it-harrison @sterkenburgsara

**Comment by CherylEvans** [comment]
@naomimarcussen I removed all bad links (There is one I left that I made a note on, for your guidance.). I wrote an introduction but need your fb.  [DRAFT](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403401835/41709+-+Cheryl+Draft+Cheryl+Draft+Guidance+on+Inclusive+Recruitment) Thank you!!
FYSA @sterkenburgsara @it-harrison

**Comment by CherylEvans** [comment]
@shiragoodman This ticket is on hold until Josh Kim has updated. Please refer to [thread](https://dsva.slack.com/archives/C046GT0TYDV/p1666108800545589).
FYSA @sterkenburgsara @briandeconinck @it-harrison

**Comment by CherylEvans** [comment]
@shiragoodman Per guidance from @naomimarcussen It was suggested we put this on pause. The documentation is very outdated and she is not she want to tell researchers how to do discovery work, let alone give them outdated information. Per Josh Kim's Slack [link](https://dsva.slack.com/archives/C046GT0TYDV/p1666200772332989), he has a small task force working to update this material.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
