### ISSUE TITLE
Product List: Update ingestion script to support JSON

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41700]
## Issue Description
The ingestion script is currently set to parse a CSV into a JSON object, before chopping it up into rows to be sent to BigQuery. We need to convert this to expect to start with a JSON data set. This may be more of a delete and redirect ticket than creating something new. We should also take a look at the `processJson.js` class that handles this exact use case for test results, as we may be able to reuse it.

---
## Tasks
- [x] Convert ingestion from expecting a CSV to JSON.

## Acceptance Criteria
- [ ] Our ingestion script runs without errors.
- [ ] Our Product Directory data all looks correct in BigQuery.
---

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/137 PR open here for this. Workflow runs with no errors and bigquery data set correctly shows 89 rows of product data.

**Comment by pjhill** [comment]
Looking good!
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/08540691-bce9-459d-994e-88541d39470d)
