### ISSUE TITLE
Product List: Create GHA Workflow to process form

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41710]
## Issue Description
When a new "update" issue is created in the product-directory repository, we want a GitHub actions workflow to kick off that will grab the latest issue, process the input from it and open a pull request to add the changes to the Product Directory.  

---
## Tasks
- [x] Create a workflow that opens a pull request with changes whenever a new issue is opened for a product directory update using the template from ticket #41711.

## Acceptance Criteria
- [x] A pull request opens every time a product directory update issue is submitted using our template.
- [x] The PR uses the template created in #41711.
---

**Comment by pjhill** [comment]
Hooray, this is in place and ready for user testing! Any changes that stem from the user testing will be worked in a separate ticket.
