### ISSUE TITLE
526: Remove extra text

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41723]
## Description

When a logged in user is missing information (some ID?), form 526 will display an alert stating that we need more information. After the TTY number is some text that shouldn't be there

<img width="612" alt="va-t text is seen immediately after the TTY phone number inside an alert on form 526" src="https://user-images.githubusercontent.com/136959/169567237-199bd788-db59-4cab-9652-d984692fcfbc.png">

## Tasks

- [ ] Remove extraneous text

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
