### ISSUE TITLE
Update VAOS templates to match staging

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#41731]
## Task Description

Update VAOS' [templates](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?node-id=0%3A1911) to match the equivalent screen on Staging

## References

- [VAOS Templates](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?node-id=0%3A1911)
- [Staging link](https://staging.va.gov/health-care/schedule-view-va-appointments/)

## Acceptance criteria

All scheduling flow templates match Staging:
Direct Scheduling
- [x] Type of care 
- [x] Select VA facility
- [x] Choose a clinic 
- [x] Preferred date
- [x] Calendar
- [x] Choose a reason 
- [x] Confirm contact info
- [x] Review 

Request
- [x] Calendar
- [x] Choose a type
- [x] Review 

Community Care 
- [x] Select CC provider 
- [x] Closest city 
- [x] Preferred language
