### ISSUE TITLE
Document VAOS user flows

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#41736]
The current user flow diagram is in github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/images/VAOS-User-Flows.png

We can't currently update and track this diagram, and it's difficult to socialize this format with other teams.

## Tasks
- [x] Transfer the information in the current diagram to a Figjam board.
- [x] Add information on error/alert states

## Deliverables
- [x] [Updated user flow diagram](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=0%3A1)
