### ISSUE TITLE
NOD & Letters: Re-enable keyboard-only e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41733]
## Description

The keyboard-only e2e tests for the Notice of Disagreement (NOD) form and letters app were skipped recently due to the tests failing in CI. That problem has since been fixed, so we can now re-enable these tests

## Tasks

- [ ] Enable NOD keyboard-only e2e test
- [ ] Enable Letters keyboard-only e2e test

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Well, re-enabling these tests apparently broke the production build - see https://github.com/department-of-veterans-affairs/vets-website/pull/21156... they pass in CI. Also, the burials keyboard-only e2e test is working without any problems.
