### ISSUE TITLE
Determine and disseminate URL redirects scenarios and workflows

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#4174]
## High Level User Stories

As a VFS team member, I need to know how to redirect a URL or request a URL redirect, so that I can direct Veterans to my modernized tool and/or content as the single source of truth instead of legacy pages. 

## Additional Notes
VSP Content & Information Architecture is involved in fielding and validating URL redirect requests. We need to clarify the redirect scenarios and workflows for each because we need to know who to hand the technical implementation off to once the URL changes have been validated. 

## Definition of Done
- [x] URL redirect request process has been documented and disseminated
- [x] URL redirect technical implementation strategy (current status) has been documented and disseminated
- [x] Action items have been identified and assigned for next steps in improving the redirect technical implementation strategy, as applicable

**Comment by meganhkelley** [comment]
URL Redirect Request: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md

Redirect Implementation Strategy: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md

Next step for technical implementation: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/503
