### ISSUE TITLE
Collaboration Cycle - MHV to VA.gov - Secure Messaging

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41753]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md). https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/product/product-brief.md
- Wireframes, mockups, or prototypes
   - [MHV mobile prototype](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ZOwp2Oa/play) (used in usability study)
   - [MHV desktop prototype](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/jgzLvgz/play) (used in usability study)
- Any other artifacts you have so far
   - [Usability testing report for desktop screens](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/research/Round1_Usability#:~:text=.%E2%80%8A.-,Final_report.md,-Update%20Final_report.md)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [X] New
- [ ] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: ____________

### 4. Are you making changes to the visual design?
- [X] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [X] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [ ] Static pages
- [X] Both

*For tools and applications, take into account if any static page entry points will need updates.<br/>
**For information and examples of Static vs Dynamic pages, review the [Static vs Dynamic guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md).

### 7. Will your work include:  

- [ ] New content
- [X] Changes to existing content

### 8. Are you making a change to the user flow?
- [X] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [X] Yes
- [ ] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [ ] Yes
- [X] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [X] Yes. Please specify: myhealth-groundwork and myhealth-migration (there are two seperate teams working on this -- one is doing designs and helping the other team with onboarding and getting familiar with the Platform.  The other team is doing the actual migration work.

### 13. Who is the VA business owner for this body of work?

- [X] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by MarciMcGuire** [comment]
I believe they were hoping to schedule design intent this week.

**Comment by shiragoodman** [comment]
ok, no worries. I'll respond to this shortly.

**Comment by chaseakirby** [comment]
Hi @MarciMcGuire. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is a new tool and/or application.

So we are recommending the following Collaboration Cycle touchpoints: 
[Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
[Sitewide Content and IA intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
[Research review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
[Analytics request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
[Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
[Contact center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
[Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
[Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams. 
We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.
Please reach out to Dave Conlon to let him know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 
Design
Content
Information Architecture (IA)
Quality Assurance (QA)
Accessibility
Product
Research

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by MarciMcGuire** [comment]
Issues to create

- [ ] [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
- [ ] [Sitewide Content and IA intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] [Research review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
- [ ] [Analytics request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] [Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
- [ ] [Contact center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] [Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [ ] [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

**Comment by MarciMcGuire** [comment]
@bryan-riley-va @alexiawunder moving this collab cycle issue into your team's board.

**Comment by shiragoodman** [comment]
@bryan-riley-va @alexiawunder we actually moved to a new template process on May 26 2022, 3 days after this ticket was opened! If you are still planning to move forward with Collab Cycle, please let me know and I can get this ticket updated to reflect the current process.

**Comment by MarciMcGuire** [comment]
Closing this; Bryan opened a new Collab Cycle ticket
