### ISSUE TITLE
Load Test Services

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4175]
As a developer, I want to load test VAOS services so that I can feel confident releasing the application into the wild and having it perform across a large number of veterans.

AC
- [ ] Bounds are established for each service, based on expected volume of calls
- [ ] Each service / all services together are load tested in a realistic way
- [ ] Services continue working during peak load

## Zenhub link
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5734

**Comment by saneshark** [comment]
I'll work with VAMF and VSP on getting more clarity on how to proceed here this week. (Jan 3 currently)

**Comment by saneshark** [comment]
I think we can probably move this into icebox and evaluate it as part of phased % launch instead. The main reason being we don't have enough test accounts to load test on production, and staging doesn't really provide us a real-world test scenario -- it's not clear what we'd actually be verifying there. 

I do think that the scripts that @kreek worked on could be leveraged in the future so would love to have those merged and documented as available. Could use them for automated regression tests potentially in the future.

**Comment by lenaecb** [comment]
@saneshark - I know we put this in 'icebox' but want to come back and see if we can put to use the load test work now that we are live. Thoughts?

**Comment by saneshark** [comment]
I think we can close this -- we just can't load test on either staging or production per guidance from VAMF.
