### ISSUE TITLE
[Ongoing Service] Support VFS teams with their analytics needs - Q2

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41767]
## User Story
As a VFS team member, I need the following support from the Platform Analytics & Insights team:

- Access to analytics tools (GA & Domo)
- Standardized Domo Dashboards
- Google Tag Manager implementations
- New feature requests
- Answer ongoing data and reporting questions and triaging

 
As a Platform Analytics & Insights team member, I need to provide analytics support to VFS teams to empower them to make more data-informed decisions for better Veteran outcomes

## Artifacts

- [Analytics Access - Google Analytics/Domo - Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bsmartin-ep%2C+jennaouellet%2C+jerinb-sdi&labels=access-request%2C+analytics-insights%2C+analytics-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo)
- [Google Analytics Implementation or QA Support - Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)

- [Analytics Product KPI Dashboard - New Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+for+%5BTeam%5D) - for new dashboard requests
- [Analytics Product KPI Dashboard - Update Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D) - for updates to existing dashboards
- [Analytics Edge Case Dashboard - Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-edge-case-dashboard.md&title=Analytics+edge+case+KPI+dashboard+request+for+%5BTeam%5D) - for products that are not [elligible](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p) for standardized dashboards
- [Analytics Feature Request/Bug Report](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennaouellet&labels=analytics-insights%2C+enhancement&template=analytics-feature-request-bug-report.md&title=Analytics+Feature+Request%2FBug+Report)

## Projected Launch Date
Ongoing service(s)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by michelle-dooley** [comment]
Closing this Q2 epic ongoing services for Q3 will be tracked in that epic.
