### ISSUE TITLE
Translation work for newest COVID FAQs updates (health facility protection levels)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41760]
## Issue Description
We recently made changes to the [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page to include information about health facility protection levels. This was done in ticket #40829. Danielle also reworked the page to remove some questions, add to other questions and move the content around. 

We need to update our translated pages with this same content. 

**Note to the writer working on these edits:** When adding the translated content to the Drupal pages, note that there were some questions there were deleted and others removed so it's not just about adding the new translated sentence into Drupal. Be sure to compare the live English page to the Spanish and Tagalog with the help of Google Translate to make sure everything matches.

## Tasks
- [x] Send text to translation team (Randi)
- [x] Input Spanish changes (Aliyah)
- [x] Input Tagalog changes (Aliyah)
- [x] Review Spanish changes (Megan)
- [x] Review Tagalog changes (Megan)
- [x] Publish Spanish page (Megan)
- [x] Publish Tagalog page (Megan)
- [x] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] Live Spanish page has most recent updates
- [x] Live Tagalog page has most recent updates

**Comment by aliyahblackmore** [comment]
Starting on these pages now! Thanks Randi.

**Comment by aliyahblackmore** [comment]
End of day update: Reviewing the live English page, current Tagalog page, and the Tagalog translation to note what already exists on the Tagalog live page and should be moved around amidst making new additions to the page!

**Comment by aliyahblackmore** [comment]
Continuing to review the live English and Tagalog pages and the new translation to note what exists on the page.  Made notes on the translation doc of content that exists on other VA pages, that is translated and needs to be included here. 

I also updated the page in Drupal alert with the new Tagalog translation. More info on this here: 

- I attempted to edit the current alert and add updated text, however changes would not save in Drupal
- I then removed the old alert box and created a new alert box. I kept the settings the same (Information Alert and Section - Health care benefits hub) but the Block Description needed to be changed. I changed this from "Tagalog if you have questions visit CDC" to "Tagalog health protection levels"
- New alert title and Text were added and saved in Drupal draft - this was noted on Drupal.

**Comment by aliyahblackmore** [comment]
End of day update: Did some more work on the Tagalog page today and will continue on it tomorrow!

**Comment by aliyahblackmore** [comment]
Hi @megzehn that Tagalog page is ready for you copy edit! 

**Some notes:**
There are a few sections that need to be translated and that we are waiting for including some that were sent by Randi today (attaching the doc that Randi sent to the translators below). and the June 2 GI bill content. While we wait for those sections, note that for the full list of symptoms those words were added by me using a Tagalog graphic from the [CDC website](https://www.cdc.gov/coronavirus/2019-ncov/downloads/COVID19-symptoms-Tagalog.pdf) and Google translate. The other Tagalog text that needs to be translated has been left as is.

[Symptoms list for translation 6322.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8846574/Symptoms.list.for.translation.6322.docx)

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Spanish page is ready for you! Again, there is some content that needs to be translated that we are waiting on. Any smaller words/or error (i.e. any small errors in the translation) were made using Google translate and added in!

**Comment by megzehn** [comment]
@RLHecht these pages are ready for the volunteer translation team: 

[Spanish version](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) 

[Tagalog version](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) 

Thank you!!

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the symptoms list as well as the few other pieces of content we needed. Thanks!

[https://app.zenhub.com/files/133843125/44d33b18-df54-48cd-b3c8-52c3c6d13e60/download](https://app.zenhub.com/files/133843125/44d33b18-df54-48cd-b3c8-52c3c6d13e60/download)

[https://app.zenhub.com/files/133843125/54ebb470-9f16-4f45-9b90-c8d4548842c4/download](https://app.zenhub.com/files/133843125/54ebb470-9f16-4f45-9b90-c8d4548842c4/download)

**Comment by aliyahblackmore** [comment]
@megzehn Spanish page is ready for you!
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Note:** The translation for "Shortness of breath or trouble breathing" was "Dificultad para respirar o dificultad para respirar." I pinged Randi on this, but it would likely be read as the same thing vs. statements with two different meanings. I deleted the repetition.

**Comment by megzehn** [comment]
Copyedited and published!  Thank you, Aliyah!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
