### ISSUE TITLE
Create alert for GI Bill Statement of Benefits page about tool not working correctly

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41777]
## Issue Description

Currently the Post-9/11 Gi Bill Statement of Benefits tool is showing some users the wrong information. We need to create an info alert to put on the [Statement of Benefits page](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/) to tell users that the tool isn't working.

When we add the info alert to the Drupal page, we also need to remove the react widget that allows users to sign in. Note that this should be an information alert and not a warning alert.

For the alert text, we can base it off of current error messaging. Here's the [error message dictionary](https://design.va.gov/patterns/messaging-dictionary).

## Tasks
- [ ] Write info alert content
- [ ] Add to Drupal page and remove react widget
- [ ] OCTO-DE review (Beth)
- [ ] Copyedit with pre-publishing checklist (Megan)
- [ ] Publish page (Megan)

## Acceptance Criteria
- [ ] Info alert is live on the site

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO , here's some suggested alert language for your review:

**The Statement of Benefits tool isn’t working right now**

We’re sorry. We’re fixing a problem with this tool. Please check back soon.

If you need to check your GI Bill benefits now, you can call us at 888-442-4551. We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.


Also suggest temporarily removing text just under the react widget: “**Note:** The tool is available Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET.”

And a few questions:
- I added the phone contact option based on the similar [warning alert here](https://design.va.gov/components/alert) — do we want to direct people to call for help while the tool is down? (The live page refers to that number as both "GI Bill Hotline" and the "Education Center" — I went with "us" here.)
- For the alert type, the design system seems to class this as a "warning," but I know we talked about informational — shall we see how it looks as informational vs. warning in Drupal?
- Live page has "GI Bill Benefits" and "GI Bill benefits" — should this be uncapped "benefits" outside of "SOB"? If so we can update when we add the alert.

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO ,

Here's the preview link with the updated alert language from the email chain: preview.prod.vfs.va.gov/preview?nodeId=3007

**Comment by bethpottsVADEPO** [comment]
@laurwill Here's the new language based on stakeholder feedback and my PL edits to that:

**You can't access your Statement of Benefits online right now**

We’re sorry. We’re fixing a problem with this tool. Please check back soon.

If you want to check your GI Bill benefits now or want us to send you a new Statement of Benefits by mail, you can call us at 888-442-4551. We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET. You can also submit a request online through Ask VA.

Contact us online through Ask VA

**Comment by laurwill** [comment]
Thanks @bethpottsVADEPO ! Preview link is now updated: http://preview-prod.vfs.va.gov/preview?nodeId=3007

**Comment by bethpottsVADEPO** [comment]
Thanks @laurwill ! I have this question out to stakeholders to make sure what we're saying is accurate here (or if we need to rephrase):

Re: SOB alert we're working on... Over the phone, could someone find out how much of their GI Bill benefits are left? Or can they only request that another SOB be sent to them?
In other words, would someone fielding a call on the hotline be able to access the Veteran's info and verbally tell them, "You have 14 months of benefits left"--or however that's quantified (credit hours?).

**Comment by bethpottsVADEPO** [comment]
@megzehn @laurwill Would you copyedit this alert once more? I had to do some rewriting because the stakeholder wanted the Ask VA link to come first then the phone number. I also tweaked the alert header... thanks!!!

**Comment by bethpottsVADEPO** [comment]
It's live! I'll let @RLHecht close the ticket in case she needs it open for now to get info for reporting.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!
