### ISSUE TITLE
Create a Cypress Failure Playbook

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#41774]
# Description
Cypress test specs sometimes fail. Sometimes they fail due to a tool implementation issue, and sometimes they fail for legitimate reasons. Platform should provide a playbook for VFS teams to follow in order to take the proper actions for the best outcomes.

Additionally, we need to create a document for Platform that discusses how to deal with VFS teams creating support requests for Cypress failures.

Be sure to use the Confluence "How-To" template for both documents -- https://vfs.atlassian.net/wiki/templates?space=~869849034&template=1477083205

# Tasks
- [x] Identify common causes for Cypress test failures
- [x] Document the most useful method for determining why your Cypress test is failing
- [x] Document the most useful course of action to take for each common Cypress failure cause
- [x] Compiles root causes and appropriate actions into a playbook for publishing to the Platform Website
- [ ] Publicize the release of the playbook to VFS teams and platform

# Acceptance Criteria
- [ ] A Cypress failure playbook is available on the Platform website
- [ ] A support guidance document is available for Platform support personnel

**Comment by ddzz** [comment]
First draft of the playbook: https://vfs.atlassian.net/wiki/spaces/~869849034/pages/2211577867/Cypress+Failure+Playbook

**Comment by pjhill** [comment]
@ddzz -- I left some comments on the draft document. But, to summarize again a bit here:

I forgot that we already had a basic step guide for troubleshooting available [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/resolve-end-to-end-test-failures).

It might benefit us to combine the two sets of recommended steps into the already live page. If there's any opportunity to make it more like a decision tree that leads troubleshooters down one path or another depending on conditions that might be easier for the users.

I think step to is to incorporate the use of this document into our support process. Hopefully the document that we produce will be good enough for us to confidently use it as a first recommendation when teams open support requests for failing test specs.

**Comment by pjhill** [comment]
It might also be neat to have the list of issues and their root causes in a table as an appendix to that document or something.

**Comment by ddzz** [comment]
The playbook has been updated with some of the content from the existing troubleshooting guide.

**Comment by JoeTice** [comment]
Reassigning to @pjhill for review...

**Comment by JoeTice** [comment]
Moving this ticket back to review

**Comment by pjhill** [comment]
A revised version of these documents has been published to the Platform website [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-troubleshoot-a-cypress-failure).
