### ISSUE TITLE
Customer Support - Overhaul React Library

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4177]
### User Story
As a FE engineer on a VFS team, I want a functional react library so that I have the lego pieces to build my product instead of having to start from the ground up.

### Problem Statement
Right now, the react library is unusable as a templated system for VFS teams to use to build off of. 

## VSP Objective (Q1 & Q2 2020)
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)
Increase in customer NPS
Reduction in time it takes to perform a VSP review across 5/10 practice areas
Reduction in volume of "non-human-needed" support requests month over month
VA.gov uptime
Triage volume (monthly)
% customers meeting coding standards

### Assumptions and Hypotheses

We **hypothesize** that  **if** we create a useable React library **then** the time it takes to review FE PRs will go down significantly because we will be giving the teams most of the building blocks they need so we should be used to the code we're seeing.
We **hypothesize** that  **if** we create a useable React library **then** FS teams will be able to snap together a prototype more quickly
We **hypothesize** that  **if** we create a useable React library **then** any errors on VA.gov will be clear (because multiple products will be sharing those components) and more quickly addresesed

## Definition of Done
- [ ] User research with VFS teams to find biggest issues with the React library and what components would be their top priority to build first
- [ ] 508 concerns are layered in with every new component
- [ ] Design concerns are layered in with every new component

**Comment by rroueche** [comment]
@andreahewitt-odd I think the product here is the React Library, not our "Support" service. Open to push back though if you want to make a different case. And I think a more descriptive word than "overhaul" is ideal, perhaps "enact usability improvements for customers" or something -- if I understand this work correctly.

**Comment by 1Copenut** [comment]
@shiragoodman Moving this to close because we now have a design system team.
