### ISSUE TITLE
Use primary action link on 526 form

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#41773]
## Value Statement
**_As a_ frontend developer**
**_I want to_ update the 526 Introduction page to use a primary action link instead of the current button**
**_So that_ we are following the latest guidelines from the design system team and ensuring that the veterans using this form are getting the best experience we can provide** 

---
## Background Context
- The current accepted pattern for presenting the user with the option to enter the form is via a primary action link. The guidelines from the design system state:
> If the page does not have a wizard and you want to direct your user to the application flow, use a primary green action link. This action link is a visually prominent link that will bring the user to another page.
The text the quote above came from can be found [here](https://design.va.gov/patterns/benefit-applications#e-how-to-apply-heading-and-wizard-button-or-action-link)

## Acceptance Criteria
- [x] The 526 form is using the primary action link instead of the button
- [x] The look and feel of the page should be unchanged

## Engineering notes
* The introduction page for the 526 is at: `src/applications/disability-benefits/all-claims/components/IntroductionPage.jsx`.
* We are using the `SaveInProgressIntro` component from `platform/forms/save-in-progress/SaveInProgressIntro` to render the primary action buttons (we include two of them) on the Introduction page currently.
* In order to render a primary action link instead of a button, we need to add the `testActionLink` prop to the `SaveInProgressIntro` component
* `testActionLink` is a boolean attribute; If its value is set to true, a link is rendered instead of a button

## Tasks
- [ ] Update 526 Introduction page to include
- [ ] Make sure that the styling (margins, padding, etc) visually matches the existing look and feel

## Definition of Ready
- [ ] 526 Introduction page is using primary action links instead of buttons
- [ ] A PR is requested for merging

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
