### ISSUE TITLE
Traefik Ingress - remove file provider and add IngressRoute

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#41780]
## Issue Description
We need to remove the File-Provider-based work in Traefik and replace it with an `IngressRoute`. Once the changes are deployed, a curl request to `http://dev-internal-api.vfs.va.gov/v0/status` should be successful:
```
curl -v -k --proxy socks5h://127.0.0.1:2001 http://dev-internal-api.vfs.va.gov/v0/status 
```
---
## Tasks
- [x] PR to remove File Provider and add IngressRoute (WIP: IngressRoute for dev-internal-api.vfs.va.gov)[https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/556] and (Fix typo)[https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/558]
- [x] Confirm full deployment of Kubernetes resources
- [ ] Test route with curl

## Acceptance Criteria
- [ ] Curl request is successful after confirmed deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
