### ISSUE TITLE
Confluence Audit & Updates:  Analytics Team Charter section

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41789]
## Issue Description

As part of the Q2 Platform team objective to ensure all product documentation is up to date and complete we will complete an audit and update of the [Analytics Team Charter](https://vfs.atlassian.net/wiki/spaces/AT/pages/1802993680/Analytics+team+charter) section on Confluence.

---
## Tasks
- [ ] Review all documentation in the team charter section of Confluence
- [ ] Ensure all links are up to date
- [ ] Add new links as applicable
- [ ] Organize content as appropriate
- [ ] Update content that is out of date
- [ ] Add new content that is missing
- [ ] Removed content that is no longer relevant

## Acceptance Criteria
- [ ] When all of the items above have been completed and the section is update to date.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
