### ISSUE TITLE
Update Product Outline Based on New Features

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#41788]
## Issue Description
We will be trying to export the synthetic monitors into code in Terraform based on guidance from our Product Owner.

---
## Tasks
- [x] Review product outline and flag sections for updates
- [x] Update product outline

## Acceptance Criteria
- [x] Outline has been reviewed/approved by TL
- [x] Outline has been reviewed/approved by PM

**Comment by JoeTice** [comment]
Updates have been made by @pjhill on 5/27/22 - and approved

**Comment by pjhill** [comment]
We did it!
