### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 6/6

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41787]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans we previously had:

John McAllister
Patricia Victor

Documentation for how to swap videos: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [x] Replace text and videos (Aliyah)
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you to review and publish!

**Comment by RLHecht** [comment]
@aliyahblackmore I just changed the name of one of the people we need to swap the video to at the top of this ticket. We should have one Air Force and one Marine Corps Veteran rather than both in one branch of service. This was my mistake. Can you make sure Patricia Victor gets put in instead of Ronald Pipkins before Megan publishes? I'll make sure he is put in the next one. Thank you!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
