### ISSUE TITLE
Medical records page changes: rework medical records page and write/edit 3 R&S articles 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41792]
## Issue Description

In order to add information on VA.gov about the different ways to request medical records + how to request DoD medical requests, we need to rework the medical records benefit page and create 3 new R&S articles.

We need to do the following work on the [Get your VA medical records online](https://www.va.gov/health-care/get-medical-records/) page:
- Assess entire page to implement [new tool landing page pattern](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/tool-landing-pages.md) updates from [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34123)
- Remove VHIE information to put in separate R&S article
- Add notification content approved in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33349)
- Link to 2 new R&S articles on DOD and VA records requests 
- **Note:** The medical records content is not in Drupal so we will need to give the content to the Public Websites team to put in Github once it's approved. 

Danielle also noted that we should see if the new content pattern will allow us to take some of the content out of the react widget and put it back into Drupal. Are there sections of content on the page that are the same across both? If so, we can move that all into Drupal and use the react widget for only the parts that are different between the authenticated and unauthenticated pages.

We need to create 3 new R&S pages:
- VHIE (using content from the medical records page)
- How to get VA medical records that aren't in Blue Button
- How to get medical records from DOD

More info about templates and the content to add from stakeholders can be found in the epic #41342

## Tasks
- [x] Rework medical records page (Laura)
- [x] Create draft VHIE R&S page (Aliyah)
- [x] Create draft medical records from VA facility R&S page (Aliyah)
- [x] Create how to get medical records from DOD R&S page (Aliyah)
- [x] Edit medical records page (Laura)
- [x] Edit VHIE R&S page (Laura)
- [x] Edit medical records from VA facility R&S page (Laura)
- [x] Edit how to get medical records from DOD R&S page (Laura)
- [x] Copyedit medical records page (Megan)
- [x] Copyedit VHIE R&S page (Megan)
- [x] Copyedit medical records from VA facility R&S page (Megan)
- [x] Copyedit how to get medical records from DOD R&S page (Megan)
- [x] Post all pages ready for Danielle's review in ticket #41796 (Megan)

## Acceptance Criteria
- [x] Medical records page and 3 new articles are ready for OCTO-DE final review

**Comment by RLHecht** [comment]
@aliyahblackmore [This is the ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34123) I slacked you about where we did a comparison of the 2 versions of the health care tool pages. You'll want to look at this to see if the authenticated content is different from what we see on the live page so you can make those changes as well. When we're ready to give PW content to put in the react widget we'll have to supply them with the 2 separate versions.

**Comment by aliyahblackmore** [comment]
An update here: I am almost done with a draft of the new VHIE page. I need to review the header levels in Drupal by tomorrow morning but wanted to pass along the bulk of it today, @laurwill ! 
[The Veterans Health Information Exchange (VHEI).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8774264/The.Veterans.Health.Information.Exchange.VHEI.docx)

**Comment by aliyahblackmore** [comment]
Noting here: Laura and I just had a call to chat about the VHIE page and there are a few changes that I will now make based on her feedback!

**Comment by aliyahblackmore** [comment]
Hi @laurwill, the VHIE drafted page with changes from today is ready for you! There are a few comments included and changes were added using track changes.
[The Veterans Health Information Exchange (VHIE).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8782962/The.Veterans.Health.Information.Exchange.VHIE.docx)

**Comment by aliyahblackmore** [comment]
Hi @laurwill - the medical records not in blue book R&S page draft is ready for you. There are a few comments and questions included and changes were added using track changes. I based this page on the the [original word document](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41342) (with text from the stakeholder), but did make some changes to their copy and order.  
[How to Request VA Medical Records.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8790000/How.to.Request.VA.Medical.Records.docx)

**Comment by aliyahblackmore** [comment]
Noting here that I started on the DOD medical records R&S page draft and will continue work on this on Tuesday.

**Comment by aliyahblackmore** [comment]
Noting here that I'll be pivoting to translation tickets today and will return to this after.

**Comment by laurwill** [comment]
Thanks @aliyahblackmore ! I've done a first pass at the **VHIE page**. Really nice work thinking through this content — I accepted your changes, tracked some new edits (mostly moving things around), and left you some comments in the doc. Could you look through and see if you have questions? Happy to chat about anything that’s not clear. 

As a next step, let's try putting this page in Drupal to make sure we're following the R&S template that works best — the current Word draft is formatted like a Multiple Q&A, but we could also try a Detail page. We can hop on zoom and look together if that’s easiest! (We may need to adjust or trim content further to fit in the templates, so want to do this before we pass pages to Danielle.)

[The.Veterans.Health.Information.Exchange.VHIE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8824707/The.Veterans.Health.Information.Exchange.VHIE.docx)

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , 
As we chatted, want to check in on the Cerner element on the main "Get your records online" page. Unfortunately, the [Cerner differences](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.js) affect multiple sections spread throughout the page — so I'm not sure that moving content into Drupal will make sense here. 

Before I get too far in adjusting the Cerner version, could you take a look at the draft updates (not yet copyedited!) to the non-Cerner content and see if I'm on the right track? I've attached a Word doc here, with highlight showing the sections that are different in Cerner. 
[Get your VA medical records online_Updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8865410/Get.your.VA.medical.records.online_Updates.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill. Some comments in attached - thanks! 
[Get.your.VA.medical.records.online_Updates_dt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8872772/Get.your.VA.medical.records.online_Updates_dt.docx)

**Comment by laurwill** [comment]
> Hi @laurwill ! The DoD draft is attached for you! A few comments/questions are included in the word doc! [How to get medical records from DOD.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8865164/How.to.get.medical.records.from.DOD.docx)

Thanks Aliyah! Excellent sleuthing on the TRICARE elements — see the version I sent over slack for responses to your Qs. 

@DanielleThierryUSDSVA , I moved this content into a clean Word doc with questions called out for you and for the SMEs (again not copyedited yet, just for preview purposes). We can look at this when we chat shortly!
[How to get your medical records from the Department of Defense.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8873224/How.to.get.your.medical.records.from.the.Department.of.Defense.docx)

**Comment by laurwill** [comment]
Hey @megzehn ! Posting the first of 4 pages here for your copyedit. As we chatted, fine to only edit in Word, and then we'll transfer changes into Drupal.

**DoD R&S page**
- DoD Word doc: 
[How.to.get.your.medical.records.from.DoD.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8874329/How.to.get.your.medical.records.from.DoD.docx)
- DoD Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=46956

**Comment by laurwill** [comment]
Update: Megan copyedited (thank you Megan!), I made teensy drupal updates, and posted all the files for Danielle in her ticket. We'll track this over in that other ticket, so closing this one out!
