### ISSUE TITLE
Final copyedit and publishing of medical records page changes and new R&S articles

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41798]
## Issue Description
This ticket is the final work for the medical records page changes. We need do do a final copyedit with the pre-publishing checklist and publish the pages.

The updated content for the medical records benefit detail page needs to be given to the Public Websites team for them to update the react widget with. Once we've approved their work and they've merged the changes, we may need to republish the Drupal page.

## Tasks
- [ ] Send final content to PW team for medical records page (Megan)
- [ ] Copyedit VHIE article (Megan)
- [ ] Copyedit medical records not in blue button article (Megan)
- [ ] Copyedit medical records from DOD article (Megan)
- [ ] Publish 4 page (Megan)

## Acceptance Criteria
- [ ] New articles and updated medical records page are live on the site

**Comment by RLHecht** [comment]
Closing as duplicate ticket
