### ISSUE TITLE
OCTO-DE review of medical records/R&S pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41795]
## Issue Description
We rewrote and created 3 new R&S pages in support of the stakeholder request for including other ways to get medical records. 

This ticket is for Danielle's review of the content team's work as well as to track sending it to stakeholders for their review.

## Tasks
- [ ] OCTO-DE review of medical records page (Danielle)
- [ ] OCTO-DE review of VHIE R&S article (Danielle)
- [ ] OCTO-DE review of how else to get medical records R&S article (Danielle)
- [ ] OCTO-DE review of how to get DOD medical records R&S article (Danielle)
- [ ] Send articles to stakeholders (Danielle/Laura)

## Acceptance Criteria
- [ ] All content is approved for publishing by OCTO-DE and stakeholders

**Comment by RLHecht** [comment]
Closing as this is a duplicate
