### ISSUE TITLE
OCTO-DE review of medical records/R&S pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41796]
## Issue Description
We rewrote and created 3 new R&S pages in support of the stakeholder request for including other ways to get medical records. 

This ticket is for Danielle's review of the content team's work as well as to track sending it to stakeholders for their review.

## Tasks
- [x] OCTO-DE review of medical records page (Danielle)
- [x] OCTO-DE review of VHIE R&S article (Danielle)
- [x] OCTO-DE review of how else to get medical records R&S article (Danielle)
- [x] OCTO-DE review of how to get DOD medical records R&S article (Danielle)
- [x] Send articles to stakeholders (Danielle/Laura)

## Acceptance Criteria
- [x] All content is approved for publishing by OCTO-DE and stakeholders

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , the medical records pages are ready for your review! 

**Main "Get your records" page**
- Non-Cerner version (the version you already saw, and the one we'll show to SMEs. I left my responses to your comments for now.): [Get your medical records_Non-Cerner version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882616/Get.your.medical.records_Non-Cerner.version.docx)
- Cerner version: [Get your medical records_Cerner version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882619/Get.your.medical.records_Cerner.version.docx)
- Test/dummy Drupal file for the Non-Cerner version of this updated page: http://preview-prod.vfs.va.gov/preview?nodeId=47029

**New VA facility R&S page**
VA facility Word doc: [How to get medical records from your VA health facility.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882598/How.to.get.medical.records.from.your.VA.health.facility.docx)
VA facility Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=47025

**New DoD R&S page**
DoD Word doc: [How to get your medical records from DoD.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882592/How.to.get.your.medical.records.from.DoD.docx)
DoD Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=46956

**New VHIE R&S page**
VHIE Word doc: [Veterans Health Information Exchange VHIE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8882587/Veterans.Health.Information.Exchange.VHIE.docx)
VHIE Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=47014

**Comment by DanielleThierryUSDSVA** [comment]
@laurwill Woohoo! Thank you so much!

**Comment by jilladams** [comment]
@DanielleThierryUSDSVA the Public Websites team has a ticket to implement new copy for the "Get medical records" page, as a sprint goal in our current sprint. I believe the copy from Laura above is what we need - can you confirm status of the review here?

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , just an update here: we had chatted on Friday about proposing a link directly to TRICARE instead of the DoD R&S page. But after looking at the TRICARE pages this morning with fresh eyes, I'm not sure they provide clear enough instructions for Veterans to get their records—at least not for all the use cases in our DoD page.

So I held off on suggesting this to Laquitta and DoD team for now. We're still waiting to hear back about a meeting time to discuss edits with DoD. We can chat more about the TRICARE option and next steps on Monday!

**Comment by laurwill** [comment]
We decided to link directly to TRICARE and got final approval on this content. Pages are now live. Closing this out.
