### ISSUE TITLE
Install agents on all packer-build machines that send security logs to VA CSOC

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#41791]
## Description
Install Beats agents on Packer-based AMIs to meet CSOC requirements

## Background/context 
- This is a CSOC requirement

## Technical notes
- Ansible-based AMI builds have already been done and can be referenced
- https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/beats

---
## Tasks
- [x] Install Beats agents on AMIs built using Packer
  - [x] EKS
    - [x] dev
    - [x] stage
    - [x] prod
    - [x] utility
    - [x] sandbox
  - [x] GitHub Actions
    - [x] vets-website
    - [x] vets-api
    - [x] testing-tools
    - [x] content-build
    - [x] va.gov-sso-smoke-tests (identity)
    - [x] va-virtual-agent

## Acceptance Criteria 
- [x] AMIs are built successfully
  - [x] EKS https://github.com/department-of-veterans-affairs/devops/runs/6813130509?check_suite_focus=true
    - [x] dev
    - [x] stage
    - [x] prod
    - [x] utility
    - [x] sandbox
  - [x] GitHub Actions https://github.com/department-of-veterans-affairs/devops/runs/6816985468?check_suite_focus=true
    - [x] vets-website
    - [x] vets-api
    - [x] testing-tools
    - [x] content-build
    - [x] va.gov-sso-smoke-tests (identity)
    - [x] va-virtual-agent
- [x] Instances are redeployed to use the new AMI
  - [x] EKS
    - [x] dev
    - [x] stage
    - [x] prod
    - [x] utility
    - [x] sandbox
  - [x] GitHub Actions
    - [x] vets-website
    - [x] vets-api
    - [x] testing-tools
    - [x] content-build
    - [x] va.gov-sso-smoke-tests (identity)
    - [x] va-virtual-agent

**Comment by jhouse-solvd** [comment]
@rmtolmach - Can we move this to "In Progress"?

**Comment by ph-One** [comment]
Rolling out EKS instances

**Comment by ph-One** [comment]
Building GitHub Action Runner (takes ~90 minutes)

**Comment by ph-One** [comment]
All EKS environments are now using beats-enabled EC2s

**Comment by ph-One** [comment]
GitHub Action Runners AMI was successfully built.
https://github.com/department-of-veterans-affairs/devops/runs/6816985468?check_suite_focus=true

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/5c5369bd-6d26-40dd-b968-f62082eb7f79)
