### ISSUE TITLE
Define standardized point estimates for each area of analytics work

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41793]
## Issue Description

We need a better way to define how much work each task will take to complete so we can do a better job at sprint planning and ensuring all work is completed within expected SLAs.

---
## Tasks
- [ ] Define each work category (access requests, GTMS, dashboards, etc)
- [ ] Meet with team to discuss how much time each item should take to complete
- [ ] Define standard guidelines for each item (if request falls out of "standard" how does that affect the timeline)
- [ ] Define and document how time (hours of work) equates to point estimates
- [ ] Publish and implement

## Acceptance Criteria
- [ ] When all items above have been completed and we have implemented point estimation as part of our planning process.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
