### ISSUE TITLE
Final copyedit and publishing of medical records page changes and new R&S articles

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41799]
## Issue Description
This ticket is the final work for the medical records page changes. We need do do a final copyedit with the pre-publishing checklist and publish the pages.

The updated content for the medical records benefit detail page needs to be given to the Public Websites team for them to update the react widget with. Once we've approved their work and they've merged the changes, we may need to republish the Drupal page.

## Tasks
- [x] Send final content to PW team for medical records page (Laura)
- [x] Copyedit VHIE article (Megan)
- [x] Copyedit Get records from VA facility article (Megan)
- [x] Publish R&S pages (Megan)
- [x] Publish medical records Drupal page once PW says OK (Megan)

## Acceptance Criteria
- [x] New articles and updated medical records page are live on the site

**Comment by laurwill** [comment]
Hi @megzehn ! 

We're finally (almost) ready to publish these pages, which means they're ready for final copyedit/prepub checklist.
- Public Websites has our final content change and will be posting updated github files for the main page in this ticket: https://github.com/department-of-veterans-affairs/vets-website/pull/21510
- 2 related R&S pages are ready for you in Drupal (we scrapped the 3rd planned R&S):
VHIE page: http://preview-prod.vfs.va.gov/preview?nodeId=47014 
Get records from VA facility page: http://preview-prod.vfs.va.gov/preview?nodeId=47025

We're aiming to publish by the end of next week, but I'll keep you posted on PW's timing with the main page. Thanks!

**Comment by laurwill** [comment]
Pages are live! Closing this out.
