### ISSUE TITLE
(Samara) Add Platforms GitHub issue tracking policy to Platform Orientation materials

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41801]
## User Story
As a VFS team member, I'd like to be informed of Platforms policy on issue tracking so that I know how to best manage tickets for my team/products.

## Description
See thread: https://dsva.slack.com/archives/CJRQ85PQB/p1651777761536489

Policy - Any issue involving Platform Teams or reported to Platform must be tracked using GitHub

**From Mike Chelen in comments below -** 

Here is our guidance:

All Platform issues must use Github.
All artifacts submitted for review to Platform must be stored in Github va.gov-team or va.gov-team-sensitive repos or otherwise publicly accessible.
Platform does not have any requirements for how VFS teams track their internal issues.

## Tasks
- [x] On the Platform Tools page, find an appropriate place to add new guidance
- [x] Test formatting/add the following message to the page around the Communication and Collaboration Tools section

- All Platform issues must use Github.
- All artifacts submitted for review to Platform must be stored in Github va.gov-team or va.gov-team-sensitive repos or otherwise publicly accessible.
- Platform does not have any requirements for how VFS teams track their internal issues.

- [x] Preview or discuss the decided placement of the content with rest of team, if needed.

## Acceptance Criteria
- [x] VFS teams are aware that any issues involving Platform teams or reported to Platform must be tracked using GitHub

**Comment by shiragoodman** [comment]
@mchelen-gov this is something that's been on our backlog for a while now however we're hesitant to move forward until an actual Github issue tracking policy is documented via a Platform Decision doc. I don't think it's wise to just add text without a reference source to the orientation materials.

Would you be able to assist in this? cc @jwoodman5

**Comment by mchelen-gov** [comment]
Here is our current guidance:


> Platform does not have any requirements for how VFS teams track their internal issues.
> All Platform issues must use Github.
> All artifacts submitted for review to Platform must be stored in Github `va.gov-team` or `va.gov-team-sensitive` repos or otherwise publicly accessible.


Any changes or exceptions will be handled on an as-needed basis. 


@shiragoodman Is this sufficient for you to proceed?

**Comment by shiragoodman** [comment]
@mchelen-gov I think that would suit our needs.

@vbellissimo do you know where we could publish this on Platform Website?

**Comment by vbellissimo** [comment]
We could add a reference to this guidance on the Platform tools page within the Communication and Collaboration Tools section here: https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools

And/or create a subpage under "Platform Tools" with the entire guidelines and call it "Managing tickets between VFS and Platform teams" or something like that.

**Comment by shiragoodman** [comment]
I like your first suggestion @vbellissimo . Let us know if you have a preference @mchelen-gov .

**Comment by mchelen-gov** [comment]
> I like your first suggestion @vbellissimo . Let us know if you have a preference @mchelen-gov .

Wherever you both think is best to communicate this is fine by me 👍👍

**Comment by sterkenburgsara** [comment]
@shiragoodman can you provide some clarification? - are we publishing a new page with this guidance and linking to that page from the [Platform tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) page that @vbellissimo suggested? I see the language @mchelen-gov articulated above, but that doesn't currently exist on PW, so I can't just provide a link. It's a lot to add to the [communication and tools table](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools). Would love your thoughts.

**Comment by shiragoodman** [comment]
@vbellissimo my team talked about this a bit at our standup yesterday, and I can understand why clarification was needed. The more I think about this, the more I think about it, that having tools such as Slack, Github, Zenhub, etc. listed under a "Platform Tools"  page just intorduces confusion because they're not owned by Platform. I know we have the blue stars indicating that, but maybe it would make more sense to VFS folks if we created a new page for VA tools (used by both VFS and Platform). What do you think? Do you want to take this back to your team for discussion? I think having the VA tools split out would make it a lot easier for us to share Platform's policy for working with and using the tools. Let me know what you think.

@sterkenburgsara in the interim, I'm moving this ticket to the backlog. 

@humancompanion-usds FYSA

**Comment by allison0034** [comment]
I am closing this ticket as the guidance is already linked on Platform website.

**Comment by vbellissimo** [comment]
@shiragoodman I'd actually ask Naomi her thoughts on this. I'm hesitant to agree to splitting this page because Naomi restructured some of this content recently.

**Comment by shiragoodman** [comment]
Ok no problem. Your team owns the page, so it's up to you on how the content is organized/displayed.

I have talked to my team about this, and even though this ticket was originally assigned to Governance, I'm not sure it's in scope for us. Yes, adding this to Platform Orientation should be on our plate, but ensuring the guidance is available on PW feels like a Platform Content item.

What do you think about picking this up?

**Comment by vbellissimo** [comment]
@shiragoodman @mchelen-gov FYI: The [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) page has been updated to reflect the guidance @mchelen-gov provided on this ticket.
