### ISSUE TITLE
[508-defect-2] CST: Fix on this page navigation and focus

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41812]
## Description

Within the Claim Status Tool, when a link within the "On this page" component is used, the focus is shifted to the breadcrumb instead of the targeted heading.

[On this page links are broken video](https://user-images.githubusercontent.com/14154792/169866030-dc29741a-613d-41ea-95af-b4e92746f64f.MP4)
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/41447 ("Must" fix)

## Tasks

- [ ] Find & fix focus issue
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
