### ISSUE TITLE
CST: Fix card padding for mobile

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41819]
## Description

Mobile card design needs more padding below the action link

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/41447 (Under "Consider" fix)

![Mobile card design needs more padding below the action link](https://user-images.githubusercontent.com/14154792/169866046-1467bf93-bc43-4663-9d2a-7673148012b4.PNG)

## Tasks

- [x] Add bottom padding to card
- [x] Add tests (as needed)

## Definition of done

- [x] All tasks complete
- [x] All tests passing
