### ISSUE TITLE
Design intent - MyHealth - Secure Messaging

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41827]
# Steps to complete Design Intent Collaboration

## Before meeting

**VFS Product Manager or Designer**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x] Add artifacts listed below to the ticket at least 2 days before the scheduled meeting.

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting

## After meeting

**Platform**
- [ ] Create feedback tickets and link to the Design Intent epic (if no feedback, please comment stating that). 
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

**VFS**
- [ ] Respond to Platform feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed. 

## Artifacts

Provide links or documents for the following: 

- [X] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/product/product-brief.md)
 
 
 
- [X] Whiteboard sketch or other lo-fi prototypes or wireframes
     - [Desktop prototype](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ELmVpjd/play)
     - [Mobile prototype](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Jnlmgje/play)
     - Landing page (inbox) list view  [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ELmVpjd) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Jnlmgje)
     -  Inbox message detail [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/v8dzZ14) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/WKye5Kn)
     -  Compose message detail view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/OmpgQWm) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/3OQr3OG)
     - Draft message list view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/dl2RebL) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m12ex58)
     - Edit draft message detail view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/GmaKQnO) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/DPOQ7ya)
     - Sent messages list view [Desktop ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/zxv4eQM)| [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ag27xKq)
     - Sent message detail view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/eK51GbP) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ag2o08p)
     - Search messages list view  [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/JnlLQvk) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/zxvVwZM)
     - Deleted messages list view  [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ZO2EQg3) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Ax4EgyY)
     - Deleted message detail view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/4aQJZED) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Ax43wKm)
     - Reply to message detail view [Desktop](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m127kwP) | [Mobile](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m127L9P)

   
- [X] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653576434058/bccd44ff0c18264f3ed814abd149cbfbe7d01d03?sender=jonathannelson8855)
- [ ] Research
     - [Round 1 MVP design usability testing final report ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/research/Round1_Usability#:~:text=.%E2%80%8A.-,Final_report.md,-Update%20Final_report.md)(desktop)
     - [Round 2 MVP design usability testing final report ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/research/Final_Report)(mobile)
     - [Prior research for secure messaging on MyHealtheVet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/research/SecureMessaging_PriorResearch/MHV_Secure_Messaging_-_User_Feedback_Highlights.pdf)
     - [MyHealtheVet Accessibility Findings - Feb 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/research/mhv-accessibility-findings.md)
     - [Haun et al Secure Messaging Lit review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/research/SecureMessaging_PriorResearch/Haun%20et%20al%20Secure%20Messaging%20Lit%20review.pdf)
- [X] Any other artifacts you have so far
     - [Information Architecture for Health Apartment](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/research/health-apartment-ia) (original working name for what is now MyHealth)
     - [Design considerations based on past research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/design/messages/design-considerations-from-research.md)

## Scheduling

- Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
For the Design Intent, you'll receive feedback from design, accessibility and IA only. You won't receive feedback from content, or QA, as it's too early in the development process.

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Design Intent Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by allison0034** [comment]
@MarciMcGuire confirming this is scheduled for May 27, 2022 at 2 pm ET.

**Comment by allison0034** [comment]
Hi @MarciMcGuire is there a user flow for this we can look at?

**Comment by MarciMcGuire** [comment]
I am checking with the team as they were already working on this when I joined.  If not, I'll get something together or we can walk through at the meeting.

**Comment by allison0034** [comment]
@MarciMcGuire ok thank you. I know there are a lot of artifacts, love the research! The flows help me visually understand the change : )

**Comment by allison0034** [comment]
Thank you!!!

**Comment by allison0034** [comment]
[Zoom link](https://oddball-io.zoom.us/rec/share/9OUnpXJiJJEVhfU1iRtHv1P4RlepkxIWWfxLG3FpyVdqt8rv17QqNQm9XOuYKQ0r.xFQXd_-d9fzs7cJF)
Passcode: 4n^Zpg?U

**Comment by CherylEvans** [comment]
No Content FB at this time.

**Comment by claytonzook** [comment]
No Research feedback at this time
