### ISSUE TITLE
Rewrite 'product-directory' tests and mocks to expect JSON data

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#41828]
## Issue Description
The current suite of unit tests (and corresponding mock data) on the product-directory repository are based around testing a CSV-formatted product directory. We are converting the product directory to JSON data, therefore the tests and mock data must be converted accordingly.

---
## Tasks
- [ ] Convert unit tests to cover JSON-formatted data.
- [ ] Convert existing mock data to JSON data.

## Acceptance Criteria
- [ ] Unit tests run and pass accordingly.
---

**Comment by holdenhinkle** [comment]
PR - https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/41699

This is done.

**Comment by pjhill** [comment]
Thanks!
