### ISSUE TITLE
Education rewrites: Rework Post-9/11 GI Bill Resident Rate Requirements page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41833]
## Issue Description
As part of the effort to migrate education rates pages onto VA.gov, we need to continue work on the page for Post-9/11 GI Bill Resident Rate Requirements. 

This page was previously built in Drupal but will need to be reworked to ensure it meets our current style for benefit detail pages and plain language standards.

Danielle did substantial edits to other rates pages in the epic #9302 that may be helpful to review if there are similar changes that should be made here. 

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=1006
Old ticket with link to legacy page and other info: #8639

## Tasks
- [x] Rework page (Katherine)
- [ ] Edit page (Laura)
- [ ] Copyedit page (Megan)
- [ ] Submit to Beth for final review in ticket #41864 (Megan)

## Acceptance Criteria
- [ ] Rates page is ready for OCTO-DE review

**Comment by RLHecht** [comment]
@katherine-fung Here's the PDF until you're in Drupal:

[https://app.zenhub.com/files/133843125/e654e1a6-9612-4e50-9440-066099bae20d/download](https://app.zenhub.com/files/133843125/e654e1a6-9612-4e50-9440-066099bae20d/download)

**Comment by katherine-fung** [comment]
Per our conversation with Beth today, I'm now adding content re: resident rate requirements to this page: https://www.va.gov/resources/in-state-tuition-rates-under-the-veterans-choice-act/ 

@RLHecht - I'm thinking about adding some information about what happens if you're eligible for in-state rates but your school charges you more. Our page currently advises people to work with their school, or make a complaint to the GI Bill hotline. 

1. Can they also make a complaint online via the GI Bill feedback tool? https://www.va.gov/education/submit-school-feedback/

2. Once someone makes a complaint about not being offered in-state rates, what happens next? Will the VA immediately stop paying the school and disapprove it from the GI Bill program? Or are there steps in between?

**Comment by katherine-fung** [comment]
@laurwill  Here's the page so far: http://preview-prod.vfs.va.gov/preview?nodeId=37717 

The "If your school charges you out-of-state tuition by mistake" is a work in progress, pending more information from the stakeholder. 

Do you have any other questions for the stakeholder, based on the page so far?

**Comment by laurwill** [comment]
Hi @katherine-fung , nice work on this so far, and thanks for raising these questions! Here are my notes and questions based on the current draft and the legacy page:
- Legacy page talks about GI Bill only, but live page also mentions VR&E benefits — does all the information on the legacy page also apply to VR&E?
- Legacy page has an eligibility requirement that doesn't appear on the live site: You need to enroll within 3 years of your discharge from active duty (or the Veteran's discharge whose transferred benefits you're using). Let's also confirm whether this should be listed on this page.
- I think the section you added, "other eligibility requirements," is actually referring to the additional residency requirements listed in the previous section on the live page. Instead of adding this new section, could you incorporate the piece about contacting your school to ask about their specific requirements into that existing section?
- Let's bump "keeping your status" header back up to an H3 — this applies to both Veterans and spouses/children, so I don't think we want to nest it under spouses/children
- From the legacy page, it seems you can use the feedback tool to submit complaints, and it sounds like a complaints team will review them to decide whether to disapprove a school — but we can ask the stakeholder to confirm these details!

**Comment by katherine-fung** [comment]
Thanks @laurwill! I changed the "Keeping your status" header. For the 3rd point, I changed the text to match the GI Bill resident rate requirements for now, until we get confirmation and find out more about in-state rates under VR&E. 

I'm compiling our list of questions for @bethpottsVADEPO and stakeholders here: 

- What are the eligibility requirements for people to receive in-state tuition rates under VR&E?

The live page states that the residency requirements for in-state tuition can vary by state and school. The legacy and Drupal draft state that schools can set their own requirements for in-state tuition. Do the various requirements set by individual schools fall under residency requirements that the live page talks about, or can/do they set requirements outside of residency? 

[Law: (4)
(A)It shall not be grounds to disapprove a course of education under paragraph (1) if a public institution of higher learning requires a covered individual pursuing a course of education at the institution to demonstrate an intent, by means other than satisfying a physical presence requirement, to establish residency in the State in which the institution is located, or to satisfy other requirements not relating to the establishment of residency, in order to be charged tuition and fees for that course at a rate that is equal to or less than the rate the institution charges for tuition and fees for that course for residents of the State.]

- If you're using VR&E benefits and you're not getting in-state rates even if you're eligible, can the school get "disapproved" for VR&E benefits? 

- Can people using VR&E benefits use the online feedback tool to submit a complaint about not getting in-state rates? The legacy page about the GI Bill resident rates mentions the tool, but the live page and the Drupal draft of the GI Bill resident rates don't mention the online tool.

- Once someone makes a complaint about not being offered in-state rates, what happens next? Will the VA immediately stop paying the school and disapprove it from the GI Bill program? What should a student whose school gets disapproved do? i.e. should they change their school? We're hoping to get a clear idea of the process, so we can convey necessary information to someone who is affected. 

- Can we confirm that this is accurate? The requirements vary slightly on the current live page, and the legacy page & older Drupal draft.

**Comment by katherine-fung** [comment]
Beth thinks that the requirement to enroll within 3 years MAY have gone away. For clarity on this question and on VR&E requirements, she's going to send us her communication with SMEs about the existing resources and support page. 

For our other questions, I'm going to highlight the differences on the legacy page and send them on to Beth, to pass onto SMEs.

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
