### ISSUE TITLE
Add touchpoint ownership to Collaboration Cycle touchpoint pages on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#41830]
## User Story
As a VFS team member, I want to know which teams are involved in which Collaboration Cycle touchpoints so it is clear. to me who I'll be receiving support from and who to contact with questions/concerns.

- Intended Audience: VFS teams
- Desired Outcome: Clarity on who owns the various Collab Cycle touchpoints
- Due Date: 

## Description
The [main Collaboration Cycle page ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)on Platform Website includes an image showing the flow of the Collaboration Cycle. There are asterisks on the Governance team touchpoints indicating that those touchpoints are owned/managed by the Platform Governance team. On the [touchpoints page ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)there is a table indicating which practice areas are involved in each Collaboration Cycle review, however there is no distinction from Governance content/IA and Sitewide Content/IA. Lastly on the[ Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-us.1764524036.html) there is a list of all teams involved as well as all team members. 

However, there is NO clear indicator on Platform Website of which touchpoints are managed/owned by which teams. The full Collaboration Cycle process is managed/owned by Governance team, and the Governance team owns all touchpoints excluding the following:

- Sitewide Content and IA Intake Request. Owned by Sitewide Content and IA team.
- Research Review. Owned by OCTO Research lead, Shane Strassberg. (Governance team is involved, but does not own the process)
- Analytics Request. Owned by Analytics and Insights team.
- Contact Center Review. Owned by Contact Center team.
- Privacy, Security, Infrastructure readiness review. Owned by Platform Security.

Note: The [General Orientation slide deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.p1) does specify which teams own which touchpoints. 

How might we make it more clear/transparent which teams own which touchpoints, which practice areas are involved in which touchpoint and improve the Collaboration Cycle flow?

## Tasks
- [x] Create a draft page for each page to be updated and share under Governance Team/Documentation Drafts on Confluence
- [x] Add "Owner" as heading to each of the following touchpoint pages. The body text under owner (aka the team that owns the touchpoint) is as specified below.
   - [x] [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)  - Governance team
   - [x] [Sitewide Content and IA Intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) - Sitewide Content and IA team
   - [x] [Research Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) - Governance team and OCTO research lead
   - [x] [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) - Governance team
   - [x] [Analytics request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/analytics-request) - Analytics & Insights team
   - [x] [Contact center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-center-review) - Contact Center team
   - [x] [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) - Governance team
   - [x] [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) - Platform security
- [x] Assign to @shiragoodman and post comment when it is ready for peer review

## Acceptance Criteria
- [ ] Touchpoint pages have been updated on Platform Website
- [ ] Touchpoint Owners are made aware that their name has been added to the page
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by SarahKay8** [comment]
Ready for peer review. @shiragoodman

**Comment by shiragoodman** [comment]
@SarahKay8 looks good. approved! please double check the Confluence pages when updated so they display correctly. Right now, some of your draft pages say, "Copy to Clipboard" within the heading... we don't want that.
![image](https://user-images.githubusercontent.com/71330581/173384913-51478764-c459-432f-ae33-0374ab028445.png)

**Comment by shiragoodman** [comment]
just publish and Platform Content will run the scroll viewport changes tomorrow during the 1st weekly run

**Comment by SarahKay8** [comment]
> @SarahKay8 looks good. approved! please double check the Confluence pages when updated so they display correctly. Right now, some of your draft pages say, "Copy to Clipboard" within the heading... we don't want that.
> 
> ![image](https://user-images.githubusercontent.com/71330581/173384913-51478764-c459-432f-ae33-0374ab028445.png)
> 
> 

Gotcha! Thanks

**Comment by SarahKay8** [comment]
> @SarahKay8 please get the source pages updated by 12:00 noon ET on Thursday to be included in the Platform Content scroll viewport publishing. thanks.

Gotcha!

**Comment by SarahKay8** [comment]
@shiragoodman Done

**Comment by shiragoodman** [comment]
great! looks like the Platform Content team is running the scroll viewport publishing now. It usually takes a few hours. when the publishing is completed, can you verify the impacted pages are updated on Platform Website? if/when complete, you can close this ticket. thanks!

**Comment by SarahKay8** [comment]
@shiragoodman sure thing!

**Comment by shiragoodman** [comment]
Sarah - I do not see "Owner" on any of the published pages. Did you update the source pages?
