### ISSUE TITLE
OCTO-DE review of Cerner health care tool landing pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41859]
## Issue Description
The content team reworked the Cerner health care tool landing pages so that they follow the new content pattern for these types of pages. 

This ticket is for Danielle's review of the content team's work.

## Tasks
- [ ] OCTO-DE review of refill and track prescriptions
- [ ] OCTO-DE review of secure messaging
- [ ] OCTO-DE review of schedule and manage appointments
- [ ] OCTO-DE review of view lab and test results online

## Acceptance Criteria
- [ ] All pages have been reviewed by OCTO-DE and ready for final copyedit and publishing
