### ISSUE TITLE
BE - Auth Profile - Onsite Notifications - Support VA Notify Testing

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#41857]
## Background

Provide support to the VA Notify team for testing onsite-notifications endpoints to ensure that security is working properly.  

## Tasks
- [ ] Provide necessary support

## Acceptance Criteria
- [ ] Ensure public key is configured correctly
- [ ] Ensure JWT is validated correctly

**Comment by tpharrison** [comment]
@ajakabcin @ericasauv09 - This ticket will be used to cover any support needed by the VA Notify team in Sprint 75.  

I will not be able to test the JWT and public key configuration changes in our staging environment since I don't have access to VA Notify's private key so I just want to have some time allocated in case there are any issues.

**Comment by tpharrison** [comment]
@ajakabcin Kyle MacMillan from the VA Notify team has confirmed that they are able to connect to our onsite notifications endpoint in staging.

cc/ @Samara-Strauss
