### ISSUE TITLE
[FE] Create address checkbox for Caregiver application (10-10CG)

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#41869]
## Description

The 10-10CG requests an address for both the Veteran, and the primary family caregiver. Because many caregivers live with their Veterans, we want to give people the option to pre-fill the primary caregiver's address fields with the previously entered Veteran address information.

**Link to mockup**: [Primary Caregiver applicant information page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wLzGlyq)

Any design questions/concerns:  @nicko-amida 

## Tasks

- [ ] Add contextual content (address, labels, text, etc.) to the Primary Caregiver address page
- [ ] Add checkbox to the 10-10cg Primary Caregiver address page
- [ ] Add checkbox functionality
     - dynamic address field filling/clearing
     - screen reader and accessibility behavior

### Contextual content

<details>
<summary>Content screenshot</summary>
<img width="538" alt="image" src="https://user-images.githubusercontent.com/81988788/170329276-686c1f0f-d8ee-4c4a-8e00-bf34680dee05.png">
</details>

- [ ] The page displays the previously entered Veteran's address

### Checkbox behavior

<details>
<summary>Pre-filled fields screenshot</summary>
<img width="470" alt="image" src="https://user-images.githubusercontent.com/81988788/170329977-83bbe6aa-cb54-4e51-b81e-1a04882728d3.png">
</details>

- [ ] Checking the box clears the fields, then auto populates the Primary Family Caregiver's address fields
- [ ] Unchecking the box (with no field edits) clears the fields
- [ ] Editing the fields unchecks the box (does not clear fields)
- [ ] Unchecking the box (with field edits) does not clear fields

### Accessibility considerations

- [ ] Additional screen reader prompt when checking the box (only when checking the box, not unchecking)
     - "The Veteran address is now in use"

## Acceptance Criteria

- [ ] Checkbox dynamically fills/clears address fields
- [ ] Accessibility behaves as expected

**Comment by longmd** [comment]
@Dene-human / @nicko-amida , I have a quick question on verbiage. For a Secondary Two person... would we have the intro paragraph say `If the Secondary Family Caregiver's (2) address is the same as the Veteran's address, we can fill those fields out for you.` OR `If the Secondary Family Caregiver (2)'s address is the same as the Veteran's address, we can fill those fields out for you.` Both seem awful in this case... HA!

**Comment by nicko-amida** [comment]
@longmd I would go with the first one!

**Comment by Dene-human** [comment]
Agreed- to be consistent with the other fields on the page
![Screen Shot 2022-06-01 at 3 46 13 PM](https://user-images.githubusercontent.com/80857940/171489111-daa93f66-6336-4e2a-baf5-839ed63b83b3.png)

What a strange way to label the whole entity though LOL

**Comment by longmd** [comment]
Use case question... when the user selects the checkbox, should we autofill the form fields and also disable them? Then if they uncheck, the fields are editable again. This could MAYBE help avoid errant editing of the fields? Thoughts?

**Comment by Dene-human** [comment]
Just noodling, but here are some questions:

1. Will checking the box erase what they put in (if they already started filling it in)?
     - Do we need a warning alert?
2. Could the checkbox automatically be unchecked if the user edits in the field?
3. If the fields are "locked" will the screenreader still read them?
4. @nicko-amida Was this discussed in your accessibility chats?

**Comment by nicko-amida** [comment]
Yeah, under "Checkbox behavior" in the issue I tried to include the behavioral cases that would come up: checking the box should erase whatever's in there and replace it with the Veteran's address, and editing the fields unchecks the box.

@longmd Do you mean on the review page exclusively? In that case, I think the functionality should be the same, unless this is to prevent some discrepancy error between the review page info and the original page info - if that's a thing that can happen.

**Comment by longmd** [comment]
That makes sense. I'm talking direct behavior when you're in the form itself. I glossed over the list item of editing a field is meant to uncheck the box. I'm torn on the warning alert for that... part of me says yes, we probably should have one in the case an errant edit is made and the field does become something different from the expected address. But another part of me says no, because this is more of a courtesy to help expedite the user experience and not an actual field that we submit for application consideration. 

Just for my own curiosity, in the case of you select the checkbox and the fields are disabled, is it a detriment that they are ignored by screenreader? This feels very similar to when you're in an e-commerce checkout and you check that your billing address is the same as your shipping address. Just curious on the accessibility feedback on that.

**Comment by nicko-amida** [comment]
Hm, you're right it's not necessarily a detriment - but my thinking was to avoid removing something from the page that they may have already seen (heard). Like we're not explicitly announcing that the fields have been disabled, or announcing that they can be edited again if you uncheck the box, so it might not be apparent to screen reader users what's going on if a field they knew was there suddenly becomes invisible to them. Leaving the fields there at least keeps some screen reader continuity.
