### ISSUE TITLE
Education rewriting: Rework Apply to restore GI Bill benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41862]
## Issue Description

As part of the effort to migrate legacy education pages onto VA.gov, we need to continue work on the page for Apply to restore Gi Bill benefits.

This page was previously built in Drupal but will need to be reworked to ensure it meets our current style for benefit detail pages and plain language standards.

Danielle did substantial edits to other rates pages in the epic #9302 that may be helpful to review if there are similar changes that should be made here.

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5573
Old ticket with link to legacy page and other info: #8641

## Tasks
- [ ] Rework page (Katherine)
- [ ] Edit page (Laura)
- [ ] Copyedit page (Megan)
- [ ] Submit to Beth for final review in ticket # (Megan)

## Acceptance Criteria
- [ ] Rates page is ready for OCTO-DE review

**Comment by RLHecht** [comment]
@katherine-fung Here's a PDF of the page until you're in Drupal: [https://app.zenhub.com/files/133843125/6bc95f23-c05e-4e0e-8f3f-4ddba5eadb0b/download](https://app.zenhub.com/files/133843125/6bc95f23-c05e-4e0e-8f3f-4ddba5eadb0b/download)

**Comment by katherine-fung** [comment]
@RLHecht - 

I have some questions for the stakeholder about getting education benefits restored

1. re: the MHA provision on this page [https://www.benefits.va.gov/GIBILL/FGIB/Restoration.asp]

"I'm using the Post-9/11 GI Bill, will I still get my monthly housing allowance?

MHA will be payable until the end of the term, quarter, or semester that you attended during the program or school permanent closure; or 120 days after the school or program ends (whichever is sooner). There is no entitlement charge for MHA payments made during this time period."

**If someone's school or program closes, do they need to file a benefits restoration claim in order to keep getting MHA payments until the end of the term or for 120 days after school ends, as described above?**

2. Do people need to file a claim to have their benefits restored if their school temporarily closes or suspends their program between 3/1/20 and 6/1/22 due to COVID? 

There are 2 provisions online. Do they conflict, or are they both true? 

a. "What happens if my school is closed temporarily due to COVID-19?
If your school is temporarily closed, VA will continue to pay your benefits through the end of the term or 28 days, whichever is sooner." 

[https://www.benefits.va.gov/GIBILL/FGIB/Restoration.asp]

b. "Use this form to apply for restoration of entitlement for Department of Veterans Affairs (VA) education benefits used at a school that has permanently closed or had its approval to receive VA benefits withdrawn or, _due to COVID-19 and between March 1, 2020 and June 1, 2022 has closed temporarily or suspended your program of study_...
With limited exception, the VA can restore entitlement only for the period of enrollment in which you did not receive credit (or in which you lost
training time). Generally, this means that entitlement can only be restored for the single term you were enrolled in when your program was suspended, your school closed temporarily or permanently, or lost its approval to receive VA benefits, as described above." 

[https://www.vba.va.gov/pubs/forms/VBA-22-0989-ARE.pdf]

**Comment by katherine-fung** [comment]
Hi @laurwill,

I'm in the middle of this rework and I have 3 questions for the stakeholder [above]. Do you want to look over the work so far, and see if you have any other questions for the stakeholder so we can ask them in one email?

This page is about how to get your education benefits restored: 

My draft in Google docs: https://docs.google.com/document/d/1kRzAtFsy_01VbteSRRt1AH-s39mkfzek_KaxeNdMNeQ/edit

Original source page: https://www.benefits.va.gov/gibill/fgib/restoration.asp 

Drupal draft by previous content team: preview-prod.vfs.va.gov/preview?nodeId=5573

**Comment by katherine-fung** [comment]
Questions for Beth and stakeholder: 

For Beth - Should we prioritize SEO keywords in the intros for these education re-writes?

For Beth/stakeholder - can you confirm the requirements for restoring someone's benefits for their entire program if their school closed between 1/1/2015 and 8/16/2015? If they were able to transfer credits to a new school, will the VA still restore their benefits? And is that special provision still in effect?

**Comment by katherine-fung** [comment]
Noting that edu stakeholders let us know that changes are coming to restoration of entitlement 10/1/2023. They will probably update the legacy page (https://www.benefits.va.gov/GIBILL/FGIB/Restoration.asp), which we can reference when we return to this work.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
