### ISSUE TITLE
Request Community Care appointment

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#4186]
As a veteran eligible for community care, I want to be able to request Community Care appointments online the same way that I request VA appointments so that I don't have to waste my time by calling into the VA instead.

AC:
- [ ] Veterans can submit appointment requests for Community Care appointments
- [ ] Veterans who are eligible for Community Care and choose a CC-supported type of care get to choose between CC & VA care
- [ ] Veterans who are not eligible for Community Care don't see any Community Care options in their scheduling flow.

## Zenhub Link
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4186
