### ISSUE TITLE
Add react widget back onto Post-9/11 GI Bill Statement of Benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41868]
## Issue Description

We removed the sign-in react widget and added a warning alert on the [Post-9/11 GI Bill Statement of Benefits](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/) page while the tool wasn't working properly. This work was done in ticket #41777

Once the tool is working again, we need to remove the alert and put the react widget back in. 

The react widget code: post-9-11-gi-bill-status
When adding the widget don't check the box for CTA widget.

## Tasks
- [x] Remove warning alert (Aliyah)
- [x] Add widget (Aliyah)
- [x] Review changes (Megan)
- [x] Publish page (Megan)

## Acceptance Criteria
- [x] Sign-in widget is back on live page

**Comment by RLHecht** [comment]
Update: This product team is most likely turning the tool back on Tuesday 7/1, so we'll need to publish these changes after it's working. They'll give us the go-ahead when it's ready.

It might be the easiest to queue this up ahead of time so that all we have to do is publish when they say so.

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! This is ready for you. I removed the alert and re-added the widget using the code from above (post-9-11-gi-bill-status)!  We won't publish until next week but the draft is ready! 

Preview link: 
http://preview-prod.vfs.va.gov/preview?nodeId=3007

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! 

@RLHecht, I reviewed and published this per your request. It's ready for you to verify. 

https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/
