### ISSUE TITLE
Education rewrite: Rework Compare education benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41877]
## Issue Description

As part of the effort to migrate education rates pages onto VA.gov, we need to continue work on the page for Compare education benefits.

This page was previously built in Drupal but will need to be reworked to ensure it meets our current style for benefit detail pages and plain language standards.

There is also a table on this page that will need to be reworked as part of our effort to remove tables from VA.gov when not needed.

Danielle did substantial edits to other rates pages in the epic #9302 that may be helpful to review if there are similar changes that should be made here.

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5575
Old ticket with link to legacy page and other info: #8640

## Tasks
- [x] Rework page (Katherine)
- [ ] Edit page (Laura)
- [ ] Copyedit page (Megan)
- [ ] Submit to Beth for final review in ticket #41881 (Megan)

## Acceptance Criteria
- [ ] Page is ready for OCTO-DE review

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's a draft of the "Compare education benefits" page. Can you let me know what you think of the approach so far?

[https://app.zenhub.com/files/133843125/b6f19ad6-5cae-4bba-9f62-175fb20c2031/download](https://app.zenhub.com/files/133843125/b6f19ad6-5cae-4bba-9f62-175fb20c2031/download)

- I converted the tables into accordions. There are 3 different options I played around with for the "Compare how you can use your VA education benefits" section. 

- I was confused by the original "What you should know before picking an education benefit program" section at the top of the page. I'm not sure how to re-work this section before getting clarification about giving up benefits, etc.  (see the comments)

**Comment by laurwill** [comment]
Also! Re: which benefits we should be comparing — I looked at the [GI Bill Comparison Tool](https://www.va.gov/education/gi-bill-comparison-tool/), and that compares Post 9/11, MGIB-AD, MGIB-SR, Fry, DEA, and VR&E. I would expect this page to compare the same programs that appear in the tool, but we'll still need to confirm.
<img width="535" alt="Screen Shot 2022-06-22 at 12 09 33 PM" src="https://user-images.githubusercontent.com/104158104/175081545-4b67ea6b-2ad6-476f-8779-e6ab41625dd9.png">

**Comment by katherine-fung** [comment]
@laurwill I'm posting the Word doc with updates. I changed what I could based on your feedback, and left the questions that are still outstanding in the comments. 

I also didn't know what to do about the word "generally" in "...you generally have 15 years to use benefits..." My instinct is we should just take it out -- our other materials on Post 9/11 GI Bill benefits don't delve into the exceptions. But I did find some exceptions in the legislation. I explain in the comment in the doc.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I think the team worked on this before we started reworking charts. Can we look at this page again--get it into an upcoming sprint? @katherine-fung FYI since you worked on this last year... let's check in about it when we get it into a sprint.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I'm noting here for when you turn back to this work that you'll need to add VR&E to this comparison page. 

Another note: When you review this with stakeholders, you'll want to show the other comparison page here, so they understand how we're splitting up the info for Veterans and dependents/survivors: http://preview-prod.vfs.va.gov/preview?nodeId=44718

**Comment by bethpottsVADEPO** [comment]
Some notes for you @katherine-fung so you can edit a bit before we meet about this one:

1/ Intro: Can you make it clear that this page is for Veterans and service members (so that dependents know it's not the page for them--we'll crosslink to that other page)

2/ 1st H2: Can you rework this H2 so the reader knows that the text under it is about what to do if you're eligible for more than 1 education benefit?

3/ I'm not sure we should send the user off this page to go read about the benefits separately, especially toward the top of the page, so I'd unlink those bulleted labels. Want to try something like:
You can use only 1 of these education benefits for a period of service:
- Post-9/11
- MGIB-AD
- etc.

You'll have to choose which education benefit you'd like to use. Once you make this choice...

4/ Did you create the 4th accordion "other eligibility requirements" because there's no way to group the rest of the eligibility requirements? I'm wondering if we need 2 H2s there: "Compare basic eligibility requirements" and "Read about other eligibility requirements by program"

5/ Can we try this under "Compare benefits":
H3: How many months of benefits you can get

Plain text: You can get up to 36 months of benefits for these education programs:
- Post-9/11 GI Bill
- Montgomery GI Bill Active Duty
- Montgomery GI Bill Selected Reserve
- Veterans' Educational Assistance Program

Plain text: You can get up to 48 months of benefits for Veteran Readiness and Employment.

H3: How much time...
I don't see info for MGIB AD and SR. Can you add that in?

H3: How we make payments
H4: Post-9/11 GI Bill
H4: Montgomery GI Bill and VEAP
We'll pay you directly every month if you're getting benefits from these programs: (maybe we abbreviate all these if we've already provided their initialisms)
- Montgomery GI Bill Active Duty
- Montgomery GI Bill Selected Reserve
- Veterans' Educational Assistance Program
H4: Veteran Readiness and Employment

Let's start with that as I'm logging off now. I'll provide more feedback on the rest of the page soon.

**Comment by bethpottsVADEPO** [comment]
Noting here that the rest of my feedback is consolidated in this ticket: #41881

**Comment by RLHecht** [comment]
Going to close this ticket as the rest of the work is carried over in the OCTO one.
