### ISSUE TITLE
Education rates: Rework Compare education benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41876]
## Issue Description

As part of the effort to migrate education rates pages onto VA.gov, we need to continue work on the page for Compare education benefits.

This page was previously built in Drupal but will need to be reworked to ensure it meets our current style for benefit detail pages and plain language standards.

There is also a table on this page that will need to be reworked as part of our effort to remove tables from VA.gov when not needed.

Danielle did substantial edits to other rates pages in the epic #9302 that may be helpful to review if there are similar changes that should be made here.

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5575
Old ticket with link to legacy page and other info: #8640

## Tasks
- [ ] Rework page (Katherine)
- [ ] Edit page (Laura)
- [ ] Copyedit page (Megan)
- [ ] Submit to Beth for final review in ticket # (Megan)

## Acceptance Criteria
- [ ] Page is ready for OCTO-DE review

**Comment by RLHecht** [comment]
Closing this. Zenhub made a duplicate.
