### ISSUE TITLE
[User Testing] Claim Status API: Research Plan

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4188]
## User Story or Problem Statement
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and user testing recruitment needs. 

## Goal
_A completed research plan sent to Perigean for user testing recruitment_

## Objectives or Key Results this is meant to further
- User testing to validate the messaging provided on the Claim Status Tool to users with active claims via the Claim Status API and uncover gaps, improvements, and pain points

## Tasks
- [x] _Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)_
- [x] _Review research plan with design team_
- [x] _Obtain approval from Andrea Schneider_
- [x] _Send research plan to Perigean_
- [x] _Add research plan to GH_

## Acceptance Criteria
- [x] Research plan has been created

**Comment by chrvalla** [comment]
This is completed. 

All documents can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/co-design-usability-June
