### ISSUE TITLE
[Research] MyHealth - Secure Messaging Usability Testing - Conversation Guide

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41886]
## Overview

Create conversation guide for Secure Messaging usability testing

## Tasks
- [ ] Create conversation guide
- [ ] Review with Tracey
- [ ] After Conversation Guide and Research Plan have been approved by Tracey, open a Research Review request with Platform.
