### ISSUE TITLE
Education rates: OCTO-DE review of Compare education benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#41881]
## Issue Description

The content team reworked the Compare education benefits page as part of the effort to migrate education rates pages to VA.gov.

This ticket is for Beth's review and changes the content team will need to make based on feedback.

Drupal page: preview-prod.vfs.va.gov/preview?nodeId=5575

---
## Tasks
- [x] OCTO-DE review (Beth)
- [x] Changes based on feedback (Katherine)

## Acceptance Criteria
- [x] Page is ready to send to stakeholders

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! I'll work on these edits today.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung looking at this page a bit more and have some broader feedback for you to consider.

I think we should eliminate the accordions for eligibility info. We generally use accordions when there's info that doesn't apply to all readers, but all readers would need to know about eligibility requirements. The character of discharge info works as you have it, but I think you could combine the info from the other 2 accordions into one section. I say this because the info in service start dates is really brief, and as you have it now, we're asking the reader to scan those program-name headers twice to find their program for service start dates and then again for how long they served. If you take this approach, you could then link off to "other eligibility requirements" right there for each program rather than having a separate section for that info.

**Comment by bethpottsVADEPO** [comment]
The other broad feedback I have is that this page is really long, and we should consider consolidating info and linking out to existing pages rather than repeating it here. Also, in general, we shouldn't repeat info since we'll then have 2 places to update and those 2 places can get out of sync where one is up to date and the other isn't.

1/ I'm not sure we need the "Ways to get additional payments" section as you could add links to those specific programs in the above section "How we make payments" with a simple text link. So in the Post-9/11 GI Bill payments section, you'd add something like this:
Find out if you can get additional payments through these programs: 
Yellow Ribbon [link]
Tuition Assitance Top-Up [link]

2/ I would get rid of "Option to transfer benefits to dependents" as that info is peripheral. For now, let's link over to the other new comparison page for dependents from "More helpful info"--and we can consider crosslinking from the body copy after you do some more work on this page.

3/ Similarly, since we have a page for how to use benefits, let's not repeat the info here. Delete that section "Compare ways you can use benefits." Instead, link to it from "More helpful info."
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/

**Comment by katherine-fung** [comment]
1/ I tweaked the intro/meta to specify that this page is for comparing education benefits for "Veterans, service members, and members of the National Guard and Reserve." 

2/ In the first section, I updated the header to say: "What to do if you're eligible for more than 1 education benefit" 

The instructions say you can only use 1 benefit per period of service. This doesn't apply to VR&E so I split it out of the bullet list. I added this line about VR&E: 

"If you're eligible for Veteran Readiness and Employment (VR&E or Chapter 31) benefits, you may use those benefits first and then use another education benefit that you're also eligible for." 

Source: https://www.benefits.va.gov/GIBILL/docs/48_Month_Rule_FAQs.pdf 

3/ For the second section, I updated the header to say: "Compare basic eligibility requirements" 

4/ I combined the "Service start date" and "Minimum service" sections into 1 section called "When you served" 

I'm wondering if there's a better way to phrase the content within this section. I don't love saying "You must have..." I tried "This must be true" or "if these are true" but it's tricky with because we talk about at least two requirements for each program (some are: This must be true... and at least one of these must be true). I ruled out "You're eligible if..." since there are other eligibility requirements. 

I'm also going to take this and the "Character of discharge" info out of accordions. 

5/ I  updated the header for the next section to say "Read about other eligibility requirements by program." You're right, I couldn't group these other eligibility requirements in a more specific way because they're so different from each other. i.e. for VEAP, you had to have contributed your own money. For MGIB-AD, you must have a high school diploma or GED to qualify in some situations. 
 
6/ Under the H2 "Compare benefits," I made the suggested changes to "How many months of benefits you can get" and "How much time you have to use benefits." 

7/ I folded the "additional payments" information into the section "How we make payments." Since 4 out of the 5 benefits have info on additional payments, I listed each benefit out here (instead of combining MGIB-AD and VEAP into one header because they both provide "payments directly to you," for example)

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, thanks for reviewing and editing this page. 

If we want to leave the hierarchy as we currently have it, I wonder if we should make the H3 for VR&E "Other requirements for VR&E": http://preview-prod.vfs.va.gov/preview?nodeId=5575 

Another approach I'm thinking about - I know we want to flatten the hierarchy, but I tried adding the program names back here so that the H3 is "Service and other requirements" and the subhead for VR&E becomes an H4 "For VR&E."

https://prod.cms.va.gov/node/5575/revisions/766073/view 

What do you think of this approach? If we don't want H4s, we could consider removing "Basic eligibility requirements" as an H2 and bump "Character of discharge requirements" and "Service and other requirements" up to H2s, and the program names as H3s.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - 

Sending this back to you for review: 
http://preview-prod.vfs.va.gov/preview?nodeId=5575

FYI we don't have a payment rates page for VEAP. In the payments section, I added a jump link to a section of the VEAP program page that says, "The amount of benefits you get (up to 36 months) will depend on how much money you put into your VEAP every month."

For VR&E, we do have a legacy subsistence allowance rates page. But I've added a jump link to a section of the VR&E program page that explains you may be able to choose between the Post-9/11 GI Bill and the VR&E subsistence rates, instead. (we should clarify with stakeholders whether the Post-9/11 GI Bill "subsistence rate" is the MHA).

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thanks for the edits. 

For VEAP payments, since there isn't much to say, let's save the user the need to click and just add this to the Compare page: The amount of benefits you get (up to 36 months) will depend on how much money you put into your VEAP every month. No link.

For the subsistence allowance, I'd link to https://benefits.va.gov/VOCREHAB/VREratesFY23.asp
At some point this year we'll tackle migrating that page into the modern experience. For now, we'll link to the legacy page. I'd also keep the link you already have there, but rephrase the link label so it's clear that we're sending the user to a page where they can find out if they can get paid the GI Bill subsistence rate instead.

In the "How many months of benefits you can get" section: 1/ I consolidated the info about being eligible for more than 1 benefit there, and 2/ I left a note for you in the "Note" about what needs fleshing out. You may need to reach out to SMEs to get some context on that, or maybe you can find out by doing a little research. It's so very confusing. How can we make it less so?

**Comment by katherine-fung** [comment]
@megzehn - this page is ready for copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=5575

**Comment by katherine-fung** [comment]
Thank you @megzehn!! I emailed the preview link to stakeholders cc @beth-wodzinski @RLHecht

**Comment by katherine-fung** [comment]
Noting here that I got feedback from the SMEs, emailed them with suggestsions, and updated the draft per their latest feedback. 

@bethpottsVADEPO, want to take a look at the changes since Jennifer's last email on May 12? She signed off on this sentence: "You can use only 1 of these education benefits for a single period of service. Once you choose a benefit, you can't switch to a different benefit."

https://prod.cms.va.gov/node/5575/revisions/view/772163/773723/visual_inline

**Comment by bethpottsVADEPO** [comment]
@katherine-fung 
1/ With the addition of the GIBCT language and link at the start of the payments section, it’s now more than about “how we make payments” so we’ll need to change that header. I tried going into detail to see what would work, but it gets long. What do you think about making it broader with simply “Payments” to account for how we make payments, what additional payments you may be able to get, and how to compare payment rates using the GIBCT?

2/ A small edit you could make to the GIBCT line you added under "How we make payments": "...to compare payment rates for VA education benefits." (since we're not listing them in a bulleted list there)

3/ I read the SMEs comment as she wants you to tweak what you have there to something more like this (which obviously isn't our voice, so we'd need to think about this one): "Once a period of service is applied to a benefit, it cannot be used again to establish a different benefit."

I'm wondering if it would solve it to repeat the bit about "period of service" in the second sentence: Once you choose a benefit, you can't switch to use a different benefit for that same period of service.

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! 

1/2/3 - These changes work well. I made the changes in Drupal, and followed up with the stakeholders/asked Robyn and Peter if they have feedback.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO! 

I'm incorporating Peter and Robyn's feedback about VR&E into the draft. I want to run 2 things by you: 

1. Re: VR&E payments - Peter and Robyn suggested adding a line, "If eligible you may select payment at the Post-9/11 G.I. Bill BAH rate." I've tweaked this to say: 

![VR&E payments.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/82f97171-affa-42b6-a96e-bb2944076e63)
  
2. Re: how long you can get VR&E benefits -  
- Peter and Robyn suggested breaking "If you're eligible for VR&E and another education benefit" into a separate H3, which I think works. 
- Per their feedback, I added a note to say, "In certain situations, a Vocational Rehabilitation Counselor (VRC) may approve more than 48 months of VR&E benefits."
- They also suggest explaining what happens if you use VR&E first vs if you use other education benefits first. Since we already have this explanation on the VR&E program page, I've linked out to it.  

![VR&E benefits.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/e046cfe9-4e49-4f48-a43f-de6f96622d2f)

**Comment by katherine-fung** [comment]
@RLHecht, this page is ready for copy editing and then publishing. Peter Granato got back to us and said the changes are good to go live. We don't need to send to any other stakeholders. 

http://preview-prod.vfs.va.gov/preview?nodeId=5575

Thanks so much!!

**Comment by RLHecht** [comment]
This is now published. To add this to the R&S landing page we need to remove another education article. @bethpottsVADEPO which one should we take out? Also waiting to add the entry points because Mikki is telling us the order on the hub landing page.

**Comment by RLHecht** [comment]
I'm going to close out this ticket and set up a separate entry points ticket for this.
