### ISSUE TITLE
[tech task] Maintenance | Add a page with keyboard-only e2e test details

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41891]
## Value Statement
**_As a_** frontend developer
**_I want_** documentation that explains the reasoning behind adding keyboard-only end-to-end tests, any limitations, usage and page-specific examples
**_So that_** I can efficiently write tests to provide better accessibility coverage.

## Background Context
The existing [keyboard testing helper functions](https://depo-platform-documentation.scrollhelp.site/developer-docs/Keyboard-testing-helper-functions.1933607071.html) page covers essential information regarding Cypress commands, but doesn't provide "real-world" examples.

This [document about writing keyboard-only e2e tests](https://docs.google.com/document/d/11RYZOM-P8l7nO3PmAr0PDv87c0v1NYGnmnYgSCV848Q) provides the background and examples a frontend developer could use.

## Relevant URLs
- [Keyboard testing helper functions](https://depo-platform-documentation.scrollhelp.site/developer-docs/Keyboard-testing-helper-functions.1933607071.html) 
- [Proposed writing keyboard-only e2e test page](https://docs.google.com/document/d/11RYZOM-P8l7nO3PmAr0PDv87c0v1NYGnmnYgSCV848Q)

## Tasks
- [ ] Task 1
- [ ] Task 2

## Acceptance criteria
- [ ] AC 1
- [ ] AC 2

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@Mottie Can you add this to an epic and move to the backlog?

**Comment by Mottie** [comment]
@saderagsdale This ticket is meant for documentation support, I moved #41348 to the backlog and added an epic. I'll remove our team label from this one.

**Comment by vbellissimo** [comment]
Followed up with Joe Tice and Peter Hill via slack on 6/30/22.

**Comment by pjhill** [comment]
Thanks for the poke!

@Mottie -- this doc is an awesome contribution, thank you!

I'll add this as a stand-alone document under the `End-to-End Testing with Cypress` collection: https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress.

**Comment by vbellissimo** [comment]
@pjhill Hi Peter, just checking to see if this was ever added to the Platform website. If so, please let me know and I will mark this ticket "closed". Thanks!

**Comment by pjhill** [comment]
This has been published to Dev Docs Confluence space. It should be grabbed and automatically published by Scrollviewport in the next day.

**Comment by Mottie** [comment]
🎉 https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-keyboard-only-end-to-end-tests

Thank you!
