### ISSUE TITLE
[Research] MyHealth - Prelim Medical Records research

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41890]
Preliminary research for Medical Records

## Tasks
- [ ] Review research repos
- [ ] Crowdsourcing info from other researchers
- [ ] Determine if Search by Records is important
- [ ] Determine next steps for Medical Records if discovery is needed.
