### ISSUE TITLE
[FE] | Profile | Update text above Edit button 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41909]
## Background
This is the FE work identified in ticket #37845. The "Edit your profile to..." content immediately above the Edit buttons on both the Personal Info page and the Contact page aren't sufficiently clear and actionable. This ticket links to the updated Sketch mock with updated verbiage.

**Scenario 1: Profile Page**

Change the content above the edit button for the Preferred Name field 
From: Edit your profile to add a preferred name.
To: Choose edit to add a preferred name.

Change the content above the edit button for the Gender Identity field 
From: xxx
To: Choose edit to add a gender identity.

[Sketch mock](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/EL4yDV2)

**Scenario 2: Contact Page**
Change the content above the edit button for the phone number fields (work, mobile, home)

From: Edit your profile to add a mobile phone number.
To: Choose edit to add a mobile number.

From: Edit your profile to add a work phone number.
To: Choose edit to add a work number.

From: Edit your profile to add a home phone number.
To: Choose edit to add a home number.

[Sketch mock](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/098x48j): note that the updated text is displayed in work number section.

## Tasks:

- [x] Update the content above the edit button on the Personal Info page and Contact info page

## Acceptance Criteria

- [x] Complete all unit testing
- [ ] Deploy to Staging behind feature flag
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & re-validate
- [x] Deploy changes to Production

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 - can you review and point this ticket? I have it planned for Sprint 76.

**Comment by adamwhitlock1** [comment]
This is ready to be validated @SKasimow
