### ISSUE TITLE
[Design] MyHealth - Design Folders desktop page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#41910]
## Issue Description
As a secure messaging user, I need a folder page so that I can see all the folders I have created in my secure messages

---
## Tasks
- [x] Design folder page for desktop
- [x] Design folder page for mobile
- [x] Drop link to mockups into a comment on this ticket
- [x] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Folder and desktop mockups will be complete and ready for review by PO.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuire** [comment]
Combined mobile & desktop into one ticket.

**Comment by jonathanjnelson** [comment]
[Desktop: folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/v/r5J0aq/a/Jn35bL0/r/k57jjA/)

[Mobile: folders](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/jgLW0w9)
