### ISSUE TITLE
Finalize Dataset Request Process

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41928]
## Issue Description
Finalize the processes and the tools surrounding the first step in our [QA processes](https://docs.google.com/presentation/d/1rUBcyUeto_1vibVkUoOGKYe0csX6luz46Hrxo5A0vho/edit#slide=id.g124a410377e_0_0):  Requesting new data sources

---
## Tasks
- [x] [Request form draft](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit#gid=0) needs to be reviewed and feedback provided (Julie)
- [x] Incorporate any edits from feedback (Chloe)
- [x] Document request process with link to template (Chloe)
- [x] Review document and request form for clarity and provide feedback (Jonathan & Pavan)
- [x] Incorporate any edits to text (Chloe)
- [x] Update QA process [visual](https://docs.google.com/presentation/d/1rUBcyUeto_1vibVkUoOGKYe0csX6luz46Hrxo5A0vho/edit#slide=id.g124a410377e_0_0) to reflect status of 1st step (Chloe)

## Acceptance Criteria
- [x] Everyone on analytics team understands how the new datasets are to be requested and has the tools to do so.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@chloedotbrown - looks good!!  And yes let's include instructions for GH ticket creation, if you could create template for that would be awesome.  I will follow up with @obrienjulie on reviewing and providing feedback on the [request form draft](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit#gid=0)

**Comment by obrienjulie** [comment]
I reviewed the dataset request form. Everything looks good.   I might consider adding in the following checkpoints:
	name of BQ View (after line 12)
	name of DOMO dataset (before row 21)
	If applicable, a link to an existing report and/or dashboard that is currently being used for these metrics. (After row 8).

CC/ @michelle-dooley , @chloedotbrown

**Comment by pavanhothi** [comment]
@chloedotbrown I reviewed the MVP version of the document in Confluence, and it looks great to me! Was very clear and easy to understand. Definitely think someone using this form to submit a request would not have any trouble understanding or using it. I can review it again once the GH ticket creation instructions have also been added to the document.

**Comment by jonathan-epstein13** [comment]
@chloedotbrown The [form ](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit#gid=0) looks great. I was wondering if it would make sense to add a section for [Google Analytics ](https://docs.google.com/spreadsheets/d/1IbwLcVUj5pie7g8zGxk5Ffy4ptt7o1lWPbQ54aELzZY/edit#gid=0)(that would be appropriate for this form) ie; possibly add a GA report/custom metrics that would match up to BQ. Maybe having a GA section we will be able to have it all under one form?

**Comment by chloedotbrown** [comment]
Hey @jonathan-epstein13 - this new form seems redundant to the list of output fields in the current version (starting in row 25). So long as the base data for the request is Google Analytics, that's exactly the kind of information that should go in that section. I can add a new note in row 26 if that helps clarify?

**Comment by chloedotbrown** [comment]
Hi @pavanhothi and @jonathan-epstein13 - ready for a final check! I've created a new [Github ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template), which is linked in [Confluence](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215576075/How+to+request+a+new+dataset), as well as added an instruction line in the [request form](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit#gid=0) per Jonathan's comment above ☝🏻 .

Want to give this another quick look and I can close this ticket out? Thanks so much!

**Comment by pavanhothi** [comment]
@chloedotbrown completed the final check. The new GH ticket template looks great! Very clear and concise. And the new instruction line in the request form looks good as well.

**Comment by michelle-dooley** [comment]
@chloedotbrown - looks great!!  Let's discuss with team during planning this afternoon and then we can close this one and move to the next pieces of work outlined.
