### ISSUE TITLE
[User Testing] Claim Status API: Conduct user testing sessions

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4192]
## User Story or Problem Statement
As a UX designer, I need to test the Claim Status API messaging with real users so I can receive feedback on the messaging and improve it.

## Goal
Collect feedback on the Claim Status API messaging via usability testing

## Objectives or Key Results this is meant to further
- Refinement of design based on human centered design principles.

## Tasks
- [ ] Test the prototype with # users 
- [ ] Create notes and drop scrubbed data into GH
- [ ] Share notes with team

## Acceptance Criteria
- [ ] Testing complete
