### ISSUE TITLE
Begin QA Processes library in Confluence

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41920]
## Issue Description
Build out a library documenting our current and future QA processes in a place that is easy to to find and reference within our Confluence documentation.

---
## Tasks
- [x] Create new "QA Processes" page at the same level as the Team Charter, Google 360, Domo and other main pages/sections of our [Analytics & Insights Team Page]( https://vfs.atlassian.net/wiki/spaces/AT/overview?homepageId=1391854099) 
- [x] Move relevant WIP pages from the "Draft" folder to new section 
- [x] Create new drafter pages in section for areas that need to be built out in the future 

## Acceptance Criteria
- [ ] Analytics team members and VA stakeholders know where to find the information on our QA processes.
- [ ] Analytics team members understand which parts of the QA process require more ideation and documenation.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Hi @michelle-dooley - I've created this section in Confluence. The[ main QA page](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216001587/QA+Processes) just has a menu of the child pages underneath, as well as the embedded slide outlining the current state of formalized processes. As we knock these out, I'll be sure that stays updated. For now, I'm keeping the "Brainstorm" document from our Mural session under this section, but once we're finished with this work, it can probably be archived in the Miscellaneous section for clarity. 

Let me know if there are any pages missing, as far as what we've marked out for future work? If it looks good, we're probably good to close this ticket out!

**Comment by michelle-dooley** [comment]
@chloedotbrown - Love it!!  I will close this ticket, thanks!!
