### ISSUE TITLE
Document Dashboard Design QA Processes

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41931]
## Issue Description
While we do have standard practices that we borrow from and modify there is no central document where analytics team members can refer to for a full view of our Design QA Process.  There is also a good amount of variation between which design QA tables are most appropriate and not easy to determine how these decisions are made.

---
## Tasks
- [x] Create new "Design QA" sub-page under the "QA Processes" page covering current practices, different QA table templates that we have used in GH and guidance for customizing based on QA content (Chloe)
- [ ] Review for clarity/completeness and provide feedback (Jonathan & Pavan)
- [ ] Incorporate edits as applicable (Chloe)

## Acceptance Criteria
- [ ] Everyone on the analytics team understands how to create a Design QA ticket, conduct Design QA on their own and modify table template(s) as appropriate for their specific product/dashboard need.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Hi @jonathan-epstein13 and @pavanhothi  - the [Design QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard) are ready for your review! Please let me know if you have any suggestions (or questions) as you review. Thanks!

**Comment by jonathan-epstein13** [comment]
@chloedotbrown everything looks pretty clear, but just have some slight notes for the following steps:

**1. Log into the _Participant Tester_ account in Domo for all tests.** [Can we link or have a place for the participant tester login info, so it can be easily accessible?]

_**_2. Copy _"Usability checklist" table_ in accordion above._**_ [Maybe how or where to copy the table, so that the `| Test   | Expected Behavior | Actual Behavior | Pass/Fail |` line up in the table accurately, not just in the comment section of the ticket] Much simpler to complete the table in a google sheet/excel when there are notes involved, same can go for the "Usability checklist" table for Data QA  and then copy it to the comment section of the QA ticket.

**Comment by chloedotbrown** [comment]
Thanks for the notes, @jonathan-epstein13 !

**1. Log into the _Participant Tester_ account in Domo for all tests.** - I'm leaving this one up to @michelle-dooley. I know Confluence is visible to Platform team members only, but I still feel iffy leaving password information anywhere in this environment. Where can we put this info where it's both discoverable by our team but also secure?

**2. Copy _"Usability checklist" table_ in accordion above.** - You can't normalize the column widths in the markdown template because the text only wraps when previewed/published. But if you're finding copying from a spreadsheet more useful, that's fine too! I created a [new template spreadsheet](https://docs.google.com/spreadsheets/d/1L8mMVnJMadNgWVnZPwvRnj-WkO5mCpyIQHvCfD2G8ho/edit?usp=sharing) I've linked on the page. Take a look and see if that meets your needs.
