### ISSUE TITLE
Document Dashboard Data QA Processes

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41932]
## Issue Description
There is currently a [draft](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/WIP+-+How+to+QA+Dashboards) of the QA procedures for Domo dashboards in Confluence but it is not fully filled out and may not be totally up to date.  We have discussed building a data QA dashboard using Google Data Studio to make dashboard QA easier to do for future projects.  While building that dashboard in not in the scope of this ticket we should decided whether it is worth doing so as part of this work.

---
## Tasks
- [x] Review current WIP draft of data QA procedures and identify revisions/additions needed (Chloe)
- [x] Complete draft 2 of data QA procedures page (Chloe)
- [ ] Review for clarity/completeness and provide feedback (Jonathan)
- [ ] Incorporate edits (Chloe)

## Acceptance Criteria
- [ ] Everyone on analytics team understands how to create a Data QA ticket, conduct Data QA on their own and modify table template(s) as appropriate for their specific product/dashboard need.
- [ ] Equivalent metrics tables in WIP draft are filled in .
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
@jonathan-epstein13 - The new [Dashboard Data QA page](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/How+to+Data+QA+Domo+dashboards) in Confluence is ready for you to look at! A new issue template is also linked under the "Artifacts" section, so please include that in your review as well.

A couple quick notes:

- I've moved the GA equivalent definitions to its own [subpage](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents), which _**won't**_ be included in this ticket due to the amount of extra time needed to go through and add all of these. Discussed with @michelle-dooley , and we'll create a separate ticket to complete the tables on that page in a future sprint.
- Unlike the Design QA page, I didn't leave specific instructions for the person creating the Data QA ticket. There's a lot more potential for variation in the design QA than in checking the data, so in this case, it seemed less necessary. If you think it'll cause confusion though, let me know!

**Comment by michelle-dooley** [comment]
@chloedotbrown and @jonathan-epstein13 - link to the new [GA Equivalents ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43169).
