### ISSUE TITLE
Urgent Care Providers (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4194]
## User Stories:
- As a urgent care provider, I need to know how to verify that a veteran is eligible to receive urgent care services obtained by veterans so I can determine whether to bill the VA or the ineligible veteran.
-  As a urgent care provider, I need to know how to bill the VA for urgent care services obtained by eligible veterans so I can get paid.

> _Note: This is solving for a business problem but, arguably, these are questions a facility may ask of a veteran for which s/he may not have answers. Providing this information via va.gov (arguably) helps expedite care in a timely fashion while businesses adjust to mission act parameters_
> This was moved from [#3897]

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Testable Outcome Y
- [ ] Testable Outcome Z

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon do we still need this one? And if so, which epic is best?

**Comment by davidconlon** [comment]
Not Veteran Facing.
This is being managed on the Community Care site and may be migrated as tier 2/3 content.
