### ISSUE TITLE
Infrastructure distribution list addition request

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#41941]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@rbeckwith-oddball 

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/41294

I'm reaching out since I was informed that QA Standards might be able to piggyback off of a [shared va.gov email list](https://vfs.atlassian.net/wiki/spaces/OT/pages/2068807800/Infrastructure+distribution+list+for+vagovdevops.gov). Our use case for that is setting up a shared Confluence service account for automatically pushing updates through the Confluence API.
I want to request adding the following emails to that list:
- ryan.smith30@va.gov
- peter.hill@va.gov

---
## Tasks
- [ ] Add ryan.smith30@va.gov, peter.hill@va.gov to the [shared va.gov email list](https://vfs.atlassian.net/wiki/spaces/OT/pages/2068807800/Infrastructure+distribution+list+for+vagovdevops.gov).

## Acceptance Criteria 
- [ ] Emails are added to the list

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@pjhill - Please forgive my belated response: 

Let me check with the team during standup. In the meantime, it looks like Mike Chelen is on that list if you need to do anything immediately. 

I'll follow up tomorrow.

**Comment by jhouse-solvd** [comment]
@pjhill - From a security perspective, it's recommended that a new distribution list be created for your team's purposes. Please reach out to your PO and/or VA IT who can help with this request. 

If you hit any blockers, let us know and we can try to provide additional guidance. 

cc: @td-usds

**Comment by jhouse-solvd** [comment]
Closing. Feel free to re-open if needed.
