### ISSUE TITLE
Monthly VA.gov Dashboard Update

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#41946]
## Issue Description

Per Chris Johnston's request we need to add a new card to the [Monthly VA.gov Summary](https://va-gov.domo.com/page/1314425343) dashboard.  The new card should be for "Unique Logins" similar to what is found on the [Performance Dashboard](https://www.va.gov/performance-dashboard/).  We should also rename the current "Unique Logins" card to "Total Logins" as that more accurately represents that data.

[Slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1651606155489009) for reference.

---
## Tasks
- [ ] Add new "Unique Logins" card (Jonathan)
- [ ] Change name of current "Unique Logins" card to "Total Logins" (Jonathan)
- [ ] QA data (Chloe)

## Acceptance Criteria
- [ ] The new card has been added and the report has been updated with proper naming conventions.
- [ ] The updates are completed for the May report that is distributed 1st week of June.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Closing ticket as it is a duplicate.
