### ISSUE TITLE
[Discovery] BDD: Current Business Process

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4195]
## User Story:
As a researcher on the Benefits and Memorials team, I need to fully understand the current business BDD process so I can document it and apply my findings towards design of the next BDD business process.

## Tasks
- [x] Understand the current business process
- [x] Map out the current business process and/or review

## Acceptance Criteria:
- [x] Current BDD business process has been mapped out and reviewed

[Business Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/bdd/BDD%20Claims%20Process.pdf)

**Comment by luke-gcio** [comment]
Business process linked above from GitHub.
