### ISSUE TITLE
[Discovery] BDD: Current Technical Process

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4196]
## User Story:
As a researcher on the Benefits and Memorials team, I need to fully understand the current technical BDD process so I can document it and apply my findings towards design of the next BDD technical process.

## Tasks
- [ ] Understand the current technical process
- [ ] Map out the current technical process

## Acceptance Criteria:
- [ ] Current BDD technical process has been mapped out

**Comment by luke-gcio** [comment]
I'm closing this as OBE - the technical process documentation is already included in the notes from Barry, etc, and the technical work is captured in the other stories.
