### ISSUE TITLE
[Design] My VA Audit UX Improvements: Updates to Static Healthcare Links

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#41967]
## Background
The conditional logic that drives the static links under the Healthcare Link section in My VA needs to be reevaluated. We decided to always show the static healthcare links.

-  "schedule and view your appointments", and "view your prescriptions" should always be shown as long as the user has healthcare through the VA.
- Consolidate "Get your VA lab results" and "view your lab results" links
- Remove "send a secure message" link

## Tasks
- [x] Update conditional logic and design
- [x] Review with content team
- [x] Review changes with team

## Acceptance Criteria
- [x] Healthcare static link section design is updated

## Resources
- [current test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md)

**Comment by aagosto90** [comment]
@Samara-Strauss @andaleliz @ericasauv09 @ajakabcin @tmitchellgcio 

I met with Danielle at her content office hours today about what to call that health care secondary link so that it's clear Veterans can access medical records as well as lab and test results at that link. She suggested a simple solution of "**Get your VA medical records and lab and test results**" (screenshot below). It looks right to me with the other links because some are about the same length and she said having a comma in the link always looks weird so this eliminates that. We also know from the redirect UAT that Veterans are looking for lab and test results and do not think of that as the same as VA medical records.

Let me know if you have any objections to this language for that link. Thank you!

![Screen Shot 2022-09-01 at 12 06 03 PM](https://user-images.githubusercontent.com/97965610/187962923-f0a8b9a8-62a6-41d0-b9cd-3c2506edc81e.png)

**Comment by Samara-Strauss** [comment]
Looks great to me! Thanks, Angela!
