### ISSUE TITLE
**Discovery** | New Form System

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41971]
### Background:

The Forms Library team has been building a new form system to replace the existing one. Since we are using the existing form system, we'd like to do some exploration on replacing the fields we use on the existing system with the new form library's components and identify any impacts/issues.

### Tasks

- [x] Replace xx field with yy field

### Acceptance Criteria

- [x] Document findings from exploration
- [x] Update team and provide recommendations (if any)

**Comment by SKasimow** [comment]
Thanks @adamwhitlock1

**Comment by adamwhitlock1** [comment]
This should be ready to close out. The plan is to review this during sprint review / planning today, and then we can further plan where to go next with this.

**Comment by SKasimow** [comment]
@adamwhitlock1  can we close now?

**Comment by adamwhitlock1** [comment]
@SKasimow yea I'll close this and I will use this branch for any future POCs or work related to the new form system
