### ISSUE TITLE
HLR: Remove v1 code

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41973]
## Description

As a frontend developer, I need to remove the v1 Lighthouse calls so that Lighthouse can remove their deprecated endpoint.

Lighthouse reported still seeing calls to their Higher-Level Review v1 contestable issues endpoint, but hasn't see any v1 submissions, at least in the past 2 weeks.

## Tasks

Some of these tasks will be pulled from #37470

- [ ] Remove v1 API calls to Lighthouse
- [ ] Remove `hlr_v2` feature flag
- [ ] Update wizard to remove v1 question
- [ ] Update unit tests
- [ ] Update e2e tests

## Definition of done

- [ ] All tasks completed
- [ ] All tests passing
