### ISSUE TITLE
Update vets-api dev/staging RDS instance and storage types

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#41976]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@github-name

## Description
We need to update vets-api dev/staging RDS instance and storage types

## Background/context 
- https://dsva.slack.com/archives/CTYQL39FE/p1653579702206009
- https://dsva.slack.com/archives/CTYQL39FE/p1653588508919799

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] We need to update from old db.m3 instance types and magnetic storage to gp2

## Acceptance Criteria 
- [ ] vets-api-dev RDS instance using newer instance class and gps storage type
- [ ] vets-api-staging RDS instance using newer instance class and gps storage type

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Not RDS, but I did find another that is still using t3. `dsva-vagov-utility-deployment-vagov-utility-utility-exporter-*` ASG. Might want to spin up separate ticket, but adding on here for now before I forget

**Comment by ph-One** [comment]
This should be broken down into separate tickets by environment
