### ISSUE TITLE
[Feature request name]: A publicly available roadmap for developer documentation

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#41979]
### Describe the problem

Engineers often want to either add to or augment the current developer documentation for VA.gov because we don't know what is going to be added, changed, or moved around by the teams responsible for the documentation. It would be very helpful for us to be able to see the roadmap for the developer documentation so we know what is being worked on and what is coming.

### Who will benefit

All engineers on VFS

### Describe your idea

Just a publicly available form of the roadmap for the developer documentation. It can be in whatever form is easier for the platform team, if that's a Zenhub board or a Google sheet, whatever is easiest.

### Provide evidence

Engineers are now taking it upon themselves to write documentation they would like to see added and some of this documentation is probably on the roadmap. I can provide specific documents that were written by engineers for this purpose if needed.

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by vbellissimo** [comment]
Followed up with Jesse Cohn via Slack on 6/30/22.

**Comment by jwoodman5** [comment]
There has been no follow-up from requestor regarding this issue. Due to that, the time since it was submitted, and the low likelihood this would elevate in priority to be done, I recommend closing. cc: @vbellissimo

**Comment by steel36** [comment]
Not sure why this had been moved back to Submitted column.  Returned it to Done due to earlier comment.
