### ISSUE TITLE
[Design] BDD: Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4197]
## High Level User Story
As a researcher/designer on the Benefits and Memorials team, I need to fully understand the current BDD process so I can identify its future state on va.gov.

## Full project epic #1834

- [x] Create research plan & kickoff recruiting #
- [x] Create conversation guide #
- [x] Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- [x] Create report #
- [x] Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
- [x] Work with PM to create tickets

**Comment by luke-gcio** [comment]
Closing - new BDD work will fall under a new Epic (does not exist yet).  No more design for MVP.
