### ISSUE TITLE
Midpoint Review | Profile Team | Bad Address Indicator

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41978]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [X] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/README.md)
- [X] Finalized design prototype or mockup: [Desktop mocks here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/eKeeAl0) and [Mobile mocks here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/wLqqgOp) 
     - Starts out on Personal page and then use right arrow to view additional screens
- [x] Research plan [Ticket #41175](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/41175)

 
- [x] Conversation guide [Ticket #41174](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/41174)

### Content artifacts 

- [X] Your product’s content source of truth: [Sketch file](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Confirming that the Midpoint Review is scheduled for 6/17 at 11:30am ET

**Comment by claytonzook** [comment]
@SKasimow On [this page of the design](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/nRj5oKd#Version) under Mailing header, the link called "edit address" - what happens when that is clicked on?

**Comment by SKasimow** [comment]
Hi @claytonzook - upon clicking "edit address" the user will be shown the screen where they can re-enter their address. Here is a [mock](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/dl71b7E#Version). This isn't the exact screen so Ignore the fact that the edit fields are under "home" and the screen has an error alert. I couldn't find the exact one but this should give you a good idea.

Also, can give you a staging account to look at if you'd like.

cc/ @cgednalske

**Comment by claytonzook** [comment]
Thanks! That clears it up for me. I found it curious that there were "edit" buttons but this "edit address" is a link. Since that one takes the user to a new page, it is indeed a link.

**Comment by cgednalske** [comment]
Hi @allison0034! I happened to see this right away, so I can answer that. No you don't need to review everything. You can start at [this screen for desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/eKeeAl0) and [this screen for mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/wLqqgOp). They start at the alert on Personal information and then move through the Contact information alert and different edit/success/errors states as you arrow right.

**Comment by briandeconinck** [comment]
@SKasimow I think you mentioned that this exists in staging now. Could you share a couple of test users where these indicators will appear?

Thank you!

**Comment by SKasimow** [comment]
@shiragoodman - I've update the links to the Sketch files to take you specifically to the BAI screens :)

**Comment by SKasimow** [comment]
@briandeconinck - sure! You can use users "123" from the list of staging accounts [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

Once you clear the BAI flag, yu can re=set the account to show the BAI flag again by clearing your cache and logging back in.

**Comment by shiragoodman** [comment]
Meeting Recording:
https://oddball-io.zoom.us/rec/share/JGPAD8s1E1xWxDev6ZtVagYntciSVimRiW0fh7zO6Hl7pi-JDy5E-SiZsZXc91bB.KTkJ15fEqF5epdNY
Access Passcode: .Wgu&000

**Comment by jimuhh** [comment]
No IA feedback, thanks.

**Comment by CherylEvans** [comment]
No Content FB at this time.
