### ISSUE TITLE
[Discovery] BDD: Review Barry Cooper's notes

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4198]
## User Story:
As a researcher, I need to understand and fully digest the BDD details provided by the BDD SME, Barry Cooper, so that I can apply the findings toward business and technical process mapping.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Review Barry Cooper's notes 
- [x] Get highlighted 526 form from Paul Shute or Barry Cooper

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [x] Notes from Barry have been reviewed
- [x] Highlighted form has been updated to GH

**Comment by chrvalla** [comment]
Highlighted Form 526 received from Barry and reviewed.

**Comment by chrvalla** [comment]
Highlighted form 526 can be found here: 
[BDD-526EZ (2).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4161591/BDD-526EZ.2.pdf)

**Comment by chrvalla** [comment]
Notes from Barry received and reviewed.
