### ISSUE TITLE
Bug: Required Text on React Components does not display or displays as undefined

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#41999]
## Description
Required Text on React Components does not display or displays as undefined. Each of these are using i18next to wrap "Required" text for multi lingual support.
* https://design.va.gov/storybook/?path=/docs/components-numberinput--aria-describedby
* https://design.va.gov/storybook/?path=/docs/components-textinput--autocomplete
* https://design.va.gov/storybook/?path=/docs/components-select--aria-describedby

## Support Ticket
https://dsva.slack.com/archives/CBU0KDSB1/p1653661915781579

## Tasks
- [ ] Update imports of TextInput and Select React components in vets-website to use named imports
- [ ] Remove internationalization stories for React components in Storybook
- [ ] Update the design system dashboard cli script to look for named imports of React components as well as default imports

## Acceptance Criteria
- [ ] When required prop is set to true on these components the text of "Required" should appear next to an asterisk on VA.gov

**Comment by k80bowman** [comment]
I'm moving this back to the Current Sprint column in case someone else wants to pick it up. I thought it would be a quick thing to fix, but it turns out that the changes caused about 20 tests to fail in vets-website and they need to be fixed (we should not skip them all). This is compounded by the fact that I can't get the unit tests to run locally (I'm working with Release Tools on this). I'll leave my PR open, whoever picks this up next can add on to it.
