### ISSUE TITLE
[FE] Staging Appointment app Error handling

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#41990]
## User Story
As a Team Member, I wish to see an indication of an error in the app so I know what is going on when I attempt an action
  
## Tasks
- [ ] Add a component to display errors
- [ ] Add error handling to API calls to catch and invoke the error component
- [ ] Create and update tests and mocks
- [ ] Update relevant documentations (readme and use cases)
