### ISSUE TITLE
[FSR] Temporary maintenance alert

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#42008]
## Issue Description
On the morning of 5/27, our team learned that the DMC's endpoint is going to be down over the weekend. This work captures the temporary maintenance alert created so that Veterans didn't attempt to submit FSR's. 

---
## Tasks
- [ ] Review the maintenance alert examples in the design system 
- [ ] Design the maintenance alert for the FSR 
- [ ] Work with FE as needed to implement 

## Acceptance Criteria
- [ ] The alert has been created and linked in this ticket
- [ ] A ticket for frontend has been linked in this ticket

**Comment by rileyorr** [comment]
[The design can be found here](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150534573/comment/no-panels?mode=i). 

[The ticket for frontend implementation can be found here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/42009).
