### ISSUE TITLE
[PM] Onsite Notifications: QA Go/No Go

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42005]
## Background
We need to confirm that we are ready to submit the feature forward for formal QA. This can only occur when we have completed end-to-end testing with VA Notify and DMC.

## Tasks
- [x] Ensure feature is done
- [x] Review the feature and functionality
- [x] Complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/qa/onsite-notifications-qa-go-no-go.md) with the team

**Comment by Samara-Strauss** [comment]
I actually think we should move this to next sprint and hole *after* end-to-end testing (note: end-to-end testing with our partners is *not* the same thing as QA).

**Comment by ajakabcin** [comment]
VA Notify discovered a bug on their end of things during initial testing so we've rescheduled end to end testing with VA Notify and DMC for July 11th to allow VA Notify time to resolve the issue.

**Comment by ajakabcin** [comment]
Coordinated with QA and VA Notify to make sure all parties have what they need. VA Notify will be creating a few additional debt notifications in advance, and then during the QA process to assist with test case validation.
