### ISSUE TITLE
Determine the pagination text for the Claim Status tool 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42014]
## Issue Description
Benefits Team 1 asked for content support to determine what the text for pagination should be at the top of a page of listings. 

[See the intake request for more detail and screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41835)

Robin Garrison said: After discussing this with Josh Kim, he recommended we follow the pattern used by the facilities locator team, where a block of text is placed above the list, something like "Showing 11 ‒ 20 of 40 events, page 2 of 4". This pagination detail will then be focused after the page is changed by the pagination web component.

What we need is clarification on the wording, "Showing 11 ‒ 20 of 40 events, page 2 of 4". The facilities locator page shows this without the "page 2 of 4" part. Josh recommended we consult Angela Fowler regarding the use of the en-dash versus actual words, because of how screenreaders would read that sentence.

We should reach out to Angela to ask her about the en dash vs. words when we are doing this work. 

## Tasks
- [x] Determine text to use above page listings
- [x] Review (Laura)
- [x] OCTO-DE review (Beth)
- [x] Post finalized content in intake request ticket for the product team

## Acceptance Criteria
- [x] Content is ready for product team

**Comment by katherine-fung** [comment]
Hi @laurwill, 

As we've discussed, we'll recommend the phrasing: 

"Showing 11 - 20 of 40 events" 

The dash is a hyphen (not an en dash).  

After consulting with Josh, we've determined that the page number shouldn't immediately follow the number of displayed search results. The page numbers for navigation should go at the bottom of the results, and use "aria-current" to help people navigate.

**Comment by laurwill** [comment]
Thanks @katherine-fung ! As we chatted, we're going with no spaces around the hyphen here to align with AP, so "Showing 11-20 of 40 events." 
I believe this is ready to post in the intake ticket — want to post for that team? Then we can close this out.

**Comment by RLHecht** [comment]
Thanks all! I saw Katherine posted the info in the intake ticket so going to close this one out.
