### ISSUE TITLE
Create banner content for IE11 users to switch to different browser

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42019]
## Issue Description
Public Websites asked for content support for the banner that will be published to alert IE11 users that their browser will soon be unsupported and they'll need to switch to a different one. We need to create the content they'll use for this so that it aligns with VA.gov's voice and style and meets our plain language standards. 

[See their intake request ticket for more background](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41914)

Here's a mockup of the banner alert they provided:
![Screen Shot 2022-05-27 at 4.33.19 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/71369fc4-8662-4e72-9317-b85bfdf2415e)

## Tasks
- [x] Create alert content
- [x] Review (Laura)
- [ ] Copyedit (Megan)
- [x] OCTO-DE review (Beth)
- [x] Provide content to product team in intake request ticket #41914

## Acceptance Criteria
- [x] Content is written and approved for product team to use

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO ,
Posting the 2 options we chatted through here, and will also post in the product team ticket.

### Option 1:
**Internet Explorer 11 will retire on June 15, 2022**
You can start using Microsoft Edge with IE mode to access [VA.gov](http://va.gov/). Or try another browser like Google Chrome, Mozilla Firefox, or Apple Safari.

After the 15th:
**Internet Explorer 11 has recently retired**
You can use Microsoft Edge with IE mode to access [VA.gov](http://va.gov/). Or try another browser like Google Chrome, Mozilla Firefox, or Apple Safari.

### Option 2:
**You'll need to use a different web browser**
Internet Explorer 11 will retire on June 15, 2022. To keep using [VA.gov](http://va.gov/), please switch to Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

After the 15th change to:
**You'll need to use a different web browser**
Internet Explorer 11 has recently retired. To keep using [VA.gov](http://va.gov/), please switch to Microsoft Edge, Google Chrome, Mozilla Firefox, or Apple Safari.

And I'll plan to note that we've used the full name of each browser, but could also shorten to Edge, Chrome, Firefox, Safari.

**Comment by RLHecht** [comment]
Can close this one now.
