### ISSUE TITLE
[CDP] Debt letter download page updates due to VBMS endpoint being back up

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#42013]
### The problem
An alert was added to the debt letter download page when the VBMS endpoint wouldn't display notification letters sent after December 2021. 

The alert that currently exists:
![Screen Shot 2022-05-27 at 3.38.03 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/f609f95c-9201-47fe-934d-dfab25216973)

### The solution
We need to remove the alert currently displayed and replace it with the alert notifying Veterans that repayment terms are incorrect in the digital letters. [The updated design can be found in this UXPin](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/150536739/simulate/no-panels?mode=i)

---
## Tasks
- [ ] Remove the existing warning alert (refer to screenshot above)
- [ ] Add the alert about repayment plan terms ([UXPin here](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/150536739/simulate/no-panels?mode=i))

## Acceptance Criteria
- [ ] The UI has been updated 
- [ ] Reach out to Denise so Jill can be notified that the update is live

**Comment by OptionSelect** [comment]
Updated to unblocked and updated due to meeting with Denise and Jill. We will now use new verbage in alert by reverting to previous existing verbiage.
