### ISSUE TITLE
Add new VA.gov Experience Standard re: new component user research

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42011]
## User Story
As an OCTO team member supporting the VA.gov Platform, I want to ensure that any new components being used are researched/tested with Veterans and/or VA.gov users before launch so that we can document and address any usability issues that may come up, especially ones related to accessibility.

- Intended Audience: OCTO, VFS and Governance team
- Desired Outcome: new standard is created and added to the VA.gov Experience Standards lists
- Due Date: TBD

Assignee: @briandeconinck 
Peer Reviewer: @jimuhh 

## Description
VFS teams may need to create new components to solve their products problems because the VA.gov Design System doesn't currently have a component that meets the products needs. This is expected and has occurred with VFS teams previously. However, if the VFS team does create a new component, then they are required to test that component with Veterans and/or VA.gov users during their research sessions in order to document issues, concerns, etc. 

The purpose of this ticket is to document this expected behavior in the form of a VA.gov Experience Standard. Within this ticket, we will document the following:

- Category
- Category Number
- Standard (the expected behavior)
- Issue (the problematic behavior)
- Issue number
- WCAG Reference (if applicable)
- Impacted practice areas (accessibility, content, design, and/or IA)
- Severity (launch-blocking, depends or non-launch-blocking)

## Artifacts Needing Updates
VA.gov Experience Standards (see [VA.gov Experience Standards guidance on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) wrt how to update the actual standards)

## Tasks
- [x] Create a draft page for the proposed new standard
   - [Draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2266365957/Draft+Brian+-+Experience+Standard+for+Component+Research)
- [x] Define the following:
   - Category
   - Category Number
   - Standard (the expected behavior)
   - Issue (the problematic behavior)
   - Issue number
   - WCAG Reference (if applicable)
   - Impacted practice areas (accessibility, content, design, and/or IA)
   - Severity (launch-blocking, depends or non-launch-blocking)
- [x] Share on #platform-governance team channel for peer review from Governance team
- [x] Make modifications/edits if necessary
- [x] Share on #platform-collaboration-cycle channel and ask for OCTO practice area lead review
   - (only the OCTO Practice area leads for the impacted practice areas will need to sign off, however all should see and validate that their practice area is or is not impacted by this new standard)
 - [x] Once approved, make the changes to the VA.gov Experience Standards per the VA.gov Experience Standards guidance on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) 
 - [x] Validate that the changes have been published to Platform Website
 - [x] Validate that the changes have been published to the DraftingTemplate (confirm with @shiragoodman if needed)

## Acceptance Criteria
- [x] A new VA.gov Experience Standard has been added to the VA.gov Experience Standards List
- [x] OCTO Practice Area leads have signed-off on the new VA.gov Experience Standard
- [x] VFS teams have been notified of the new standard per #vfs-all-teams and the Collaboration Cycle Change History log
---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Initiative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@KevinMHoffmanUSDS @humancompanion-usds FYI. Let me know if you have any questions or concerns. We will keep you in the loop when this is picked up.

**Comment by chaseakirby** [comment]
@shiragoodman Can you provide clarity on where the VA.gov Experience Standards are kept?

**Comment by shiragoodman** [comment]
@briandeconinck this ticket is now ready for you to work on. Please read through it and let Chase or I know if there's any questions or concerns.

**Comment by briandeconinck** [comment]
Based on all of the feedback on the [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2266365957/Draft+Brian+-+Experience+Standard+for+Component+Research), I have updated the “Other References” item with links to [Contributing to the design system](https://design.va.gov/about/contributing-to-the-design-system/) and the platform website [Research Overview](https://depo-platform-documentation.scrollhelp.site/research-design/research-overview) section. 

(Note for @shiragoodman , in the DraftingTemplate the [Standards tab](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=765031143) has a column labeled “WCAG Standards (if applicable),” the [Individual Feedback tab](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=34248990) has a column labeled “Other Reference,” and the generated [feedback tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43975) have a section heading “Other References.” I think these are all the same thing, right? This seems like the right place to include these resources but I just want to check in and make sure I’m not coloring too far outside the lines here.)

I agree with everyone else’s thoughts on providing additional guidance – but in a future ticket so we can keep this one moving forward!

@jimuhh could you take one more look at the draft standard? If it looks good to you I'll proceed to the next task, "Share on #platform-collaboration-cycle channel and ask for OCTO practice area lead review." Thanks!

**Comment by jimuhh** [comment]
@briandeconinck I looked it over and like the way you integrated the feedback into the standards format.  I especially like the integration of "other references" to provide context for the decision. IMO this is good to go.

**Comment by shiragoodman** [comment]
@briandeconinck good observation. Yes, they're likely the same columns. I think I had named "Other References" to "WCAG References" since WCAG was typically the only other reference we'd make. I can update it to "Other References" in the drafting tempalte.

**Comment by briandeconinck** [comment]
Following the [VA.gov Experience Standards documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards), I have added the new standard as 04.13 to the source of truth Google Sheet. I have confirmed that the Platform-facing copy and the DraftingTemplate have updated from that edit, although the other resources links don't seem to have populated. (Any thoughts @shiragoodman?)

I've also updated the [Confluence page for Platform website](https://vfs.atlassian.net/wiki/spaces/CC/pages/1683980311/VA.gov+experience+standards). Those edits should go live on Platform website next week.

@jimuhh besides the link issue noted above I think this is ready for peer review!

**Comment by shiragoodman** [comment]
thanks @briandeconinck ! I'll take a look at the DraftingTemplate and make sure the Other Resources links copy over.

**Comment by shiragoodman** [comment]
@briandeconinck I'm assuming the link didn't update in the DraftingTempalte because there's actually 2 links. The WCAG links that exist in the DraftingTemplate now do not publish as links in the gh tickets we create, so I don't consider this a new issue. It's published on Platform Website and that's what matters.

I will be creating a ticket for our backlog to investigate how to get the links to publish as links from the DraftingTemplate to the GH ticket.

**Comment by shiragoodman** [comment]
FYI here is the new Github ticket I created for fixing the links not getting published issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45169
