### ISSUE TITLE
Add guidance for VFS teams to notify Governance of any conflicting feedback between Collaboration Cycle and VA Business Owner

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42012]
## User Story
As a Governance team member, I want to be made aware of any "must" and/or "should" feedback that the VFS team chooses not to implement per decision of their VA Business Owner, so that I may escalate to OCTO leads for action.

As a VFS PM, I want to be aware of my responsibilities to communicate conflicting feedback between the Collaboration Cycle and my VA Business Owner so that conversations between the 2 parties happen earlier in development, potentially saving time and energy.

As an OCTO team member, I want to know when VFS teams are directed to disregard Collaboration Cycle feedback per decision of their VA Business Owner so that I may escalate the concern and communicate the VA.gov Experience Standards for the VA.gov Platform with the VA Business Owner.

- Intended Audience: VFS teams, Governance and OCTO practice area leads
- Desired Outcome: Messaging added/modified in the Collaboration Cycle (at Design Intent and/or Midpoint Review) guidance asking VFS teams to notify us if their VA BO directs them to not implement Collaboration Cycle feedback
- Due Date: TBD

## Description
There are many VFS teams building products on VA.gov that have stakeholders (in the form of a VA Business Owner) outside of OCTO. Typically, the VA Business Owners are either with VHA and/or VBA.

It is possible that "must" or "should" feedback communicated by the Governance team within the Design Intent and/or Midpoint Review touchpoints of the Collaboration Cycle could be seen as not critical for the VA Business Owner. The VA Business Owner may tell their VFS team to not implement and/or address the "must" or "should" feedback. If/when this occurs, Governance team and OCTO would like to be notified ASAP so that OCTO can communicate our concerns with the VA Business Owner and hopefully come to a resolution on the issue. 

The purpose of this ticket is to add and/or modify guidance to the VFS team, instructing them to notify us if the above scenario takes place. 

## New Artifacts 
N/A

## Artifacts Needing Updates
PW: Design Intent touchpoint
PW: Midpoint Review touchpoint
script for Design Intent
script for Midpoint Review
Collaboration Cycle feedback ticket template

## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled
- [ ] VFS teams are notified during the Midpoint Review and/or Design Intent how to handle conflicting feedback from their VA Business Owner
- [ ] VFS teams are able to see on Platform Website how to handle conflicting feedback from their VA Business Owner

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by chaseakirby** [comment]
@shiragoodman Please refine addition to scripts.

**Comment by shiragoodman** [comment]
@chaseakirby script updated. This is ready.

**Comment by shiragoodman** [comment]
@allison0034 please ready through the ticket and let me know if you have any questions before beginning work. thanks!

**Comment by allison0034** [comment]
#42012

**Comment by shiragoodman** [comment]
@allison0034 @chaseakirby unfortunately, I don't approve. Some changes came to light, recently. Typing up a response now....

**Comment by shiragoodman** [comment]
I'm sorry, but we need to make some changes based off a recent conversation we had with Chelen. We no longer want to say, "Lastly, please be sure to communicate with our team if your VA Business owner decides not to act on any of our Collaboration Cycle feedback. In this scenario, we may need to escalate with OCTO in order to determine the best course of action." 

Why don't we want to say this? Let's break it down.

"please be sure to communicate with our team" - we no longer want to say this because we shouldn't be taking any action if they choose not to act on our "must" feedback. If they don't act on "must" feedback, then ok. they accept the risk of being blocked from launch. But it's not our job to escalate or come up with an alternate solution. Communicating to us would result in no action from us, so why ask it in the first place.

"if your VA Business Owner" - we no longer want to say this because it doesn't matter if it's the team themselves or the VA Business owners. no need to call out their VA BO when the team could also be making the decision not to act on "must" feedback.

"we may need to escalate with OCTO" - again, we shouldn't be taking action if they choose to ignore our feedback. OCTO shouldn't have to step in to escalate our concerns either.

"to determine the best course of action." - i feel like you get the point already, but yea... we won't be determining a course of action. if they choose to ignore our feedback then they accept the risks. bottom line. that's all that needs to be said.

In addition, it is not _our responsibility_ to manage requirements for a VFS team. To quote Chelen, "It is the role of VFS to communicate with stakeholders, not Platform Governance." We also don't want to put that on OCTO either.

What we should be saying instead is just emphasizing that must feedback could result in launch-blocking issues at Staging Review. If the team decides not to address "must" feedback, then they need to know that they accept the risk that launch-blocking issues could be identified at Staging Review. That's it. We don't want to open the door for dialogue with the team on how they should move forward if not addressed. We just need to communicate the risk they're choosing to accept and double down on our standards.

This is what I recommend:

"Lastly, please note that  "must" feedback, if not addressed, could result in launch-blocking issues at Staging Review. By not addressing the "must" feedback, your team accepts the risk of being blocked from launch to the VA.gov platform. Please handle accordingly."

**Comment by allison0034** [comment]
@shiragoodman I have a question about a couple of comments...

"But it's not our job to escalate" and "we may need to escalate with OCTO" - again, we shouldn't be taking action if they choose to ignore our feedback. OCTO shouldn't have to step in to escalate our concerns either.

Kevin Hoffman (and Ryan in the past) have always asked that I (we) escalate any concerns about feedback to them.  The PDF list on a recent form is a great example.

**Comment by shiragoodman** [comment]
thanks for letting me know @allison0034 . This may be a conflict in what our OCTO Platform leads want vs. what the OCTO practice area leads want. I'm having a hard time seeing a path forward here that allows both of them to get their way. Our OCTO Platform leadership wants us to enforce the standards and not escalate concerns, whereas our OCTO Practice area leads want us to escalate concerns to them so they may get involved. 

The way I see it Allison, this new messaging doesn't prevent you from escalating concerns about feedback to Matt, etc. You can still do that, and should still do that. We just don't want to communicate to VFS teams that they _should_ escalate their concerns to us. Does that make sense and/or help you out?

**Comment by allison0034** [comment]
@shiragoodman I am assuming we do not want to add a checkbox to the Collaboration Cycle feedback ticket template. I had added....

- [ ] Let Platform know if your VA Business owner decides not to act on any of our Collaboration Cycle feedback

**Comment by shiragoodman** [comment]
correct. No need to change the feedback template. Thanks for checking.

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby ready for your review...

[PW: Design Intent touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent)
[PW: Midpoint Review touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review)
[script for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[script for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)

**Comment by allison0034** [comment]
@shiragoodman this is live, you can close
