### ISSUE TITLE
[FE] Add Physical Location to Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42026]
## User Story
As a Veteran, when I am using Patient Check-in to check-in for my appointment, I would like to see the physical location for my in-person appointments so that I understand where my appointment is and will know that I am in the right place.

## Background info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653665302561659)

## User Workflow
- Given I
    - Have verified my identity in the Check-in application and completed contact confirmation, if applicable
- When I
    - See my list of appointments for today
- Then I
    - See the physical location for each in-person appointment
  
## Wireframes
See screenshots in this [wireframe ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42723)

## Tasks
- [ ] [FE] Display the physical location for each in-person appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
