### ISSUE TITLE
[FE] Add Physical Location to Check-in and Pre-Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42028]
## User Story
As a Veteran, when I am using Patient Pre-Check-in to complete pre-check-in tasks for my appointment, I would like to see the physical location for my in-person appointments so that I understand where my appointment is and will know that I am in the right place.

## Background info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653665302561659)

## User Workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the physical location for each **in-person** appointment if the data is available (if no data is available then the label is also not displayed)
  
## Wireframes
See screenshots in this [wireframe ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42723)

## Tasks
- [ ] Maintain the grid, add Location label and value below Clinic on 4 pages (2 for pre-check-in and 2 for check-in)
- [ ] If Location is blank, do not show the label 
- [ ] [FE] Display the physical location for each in-person appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Verify that Location displays in both Pre-Check-in and Check-in appointment lists
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
Code is merged will be ready to test with BE ticket completion. In the mean time, here are screenshots.![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (26).png](https://ima![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (25).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/f2ea2ce4-4192-4b25-a56b-c8dfcc4aabdf)![localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (3).png](https://ima![localhost_3001_health-care_appointment-check-in_details.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d4753005-5261-4646-96ad-8031c2154c74)ges.zenhubusercontent.com/61523b5b9d354750f04823db/ec70e12d-ea82-4bc0-bca7-6bcea8f378b6)ges.zenhubusercontent.com/61523b5b9d354750f04823db/b86ee6a9-750d-4297-bff4-90ebd8356a7c)

**Comment by loripusey** [comment]
None of the links work

**Comment by brianseek** [comment]
@loripusey yes, that has been addressed in the PR! Closing with validation on zoom

**Comment by benbrasso-agile6** [comment]
![pre intro Screen Shot 2022-07-27 at 4.07.30 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/c36b544a-4e8a-44f4-9b6c-5d847c10bda6)

![pre complete Screen Shot 2022-07-27 at 4.08.06 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/28513aa4-d020-4207-9684-2dc9d8d99231)

For Ben: Grab check-in next week. No more appts left for today.
