### ISSUE TITLE
Translation work for second booster guidance

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42021]
## Issue Description
We made changes to the [COVID-19 main vaccine page](https://www.va.gov/health-care/covid-19-vaccine/) and the [boosters and additional doses page](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) around new guidance for second boosters. 

We need to send these changes to the translators and then update our Spanish and Tagalog pages. 

Please note when the translations come back that we didn't ask them to re-translate sentences that were already on the page but may have been in a different spot. So whoever works on this ticket will need to make sure that the content on the English page matches everything that will be on the new translated page instead of just adding in the translated sentences. 

## Tasks
- [x] Send content to translators (Randi)
- [ ] Update Spanish page 
- [ ] Update Tagalog page
- [ ] Review Spanish page (Megan)
- [ ] Review Tagalog page (Megan)
- [ ] Publish Spanish page (Megan)
- [ ] Publish Tagalog page (Megan)
- [ ] Send live links to volunteer translators

## Acceptance Criteria
- [ ] Spanish and Tagalog pages are live with changes

**Comment by RLHecht** [comment]
Closing as work was completed
