### ISSUE TITLE
[FE] Demographics component

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#42023]
## User Story
As a Team Member, I would like to see demographic status of a test user and also reset the status.
  
## Tasks
- [ ] Add a mock for fetching status
- [ ] Add a mock for reseting status
- [ ] Add a component to display and reset status
- [ ] Create and update tests
- [ ] Update relevant documentations (readme and use cases)
