### ISSUE TITLE
[UX] Update Release Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42032]
## Description
Update various product assets, as necessary, based on changes to the product for this Epic.
 
## Tasks
- [ ] Update the PCI Product Guide, including content and screenshots
- [ ] Update the CI Product Guide, including content and screenshots
- [ ] Update the Poster
- [ ] Update user flow diagrams, as necessary
- [ ] Push changes to the appropriate GitHub files
- [ ] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov
- [ ] Notify the Contact Center of the changes (follow this [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))
    - Create demo video & transcript
    - Create the CC GitHub ticket and attach video & transcript & links to guides
- [ ] Notify Training of the changes (Shawn Adams, Cheryl Wills, Farah Ford)

## Acceptance Criteria
- [ ] Product Guides are up-to-date (content & screenshots)
- [ ] Poster is up-to-date
- [ ] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [ ] R&D articles are up-to-date
- [ ] Contact Center is aware of the changes
- [ ] Training is aware of the changes

**Comment by benbrasso-agile6** [comment]
@loripusey I am a bit behind on these FYI. Working through some of this now. Getting a bit more complicated since we now have specific messaging in a few places for in-person vs. phone.

**Comment by loripusey** [comment]
no problem @benbrasso-agile6, perhaps once I get through these translation workflows I can help with the product guides.

**Comment by benbrasso-agile6** [comment]
@zach-park take a look at the changes I made to the "intro" and the two "completion" steps. I did NOT check these into abstract. You'll need to recreate these. 

![Pre-check-in user flow (Read-only) for user guide.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/7073eae8-5617-4464-ab16-10e073785d42a)

**Comment by benbrasso-agile6** [comment]
![Pre-check-in user flow (Read-only) for user guide.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/f28dceae-b726-4fd4-b6b0-cc67f869d382)

**Comment by benbrasso-agile6** [comment]
@loripusey I am ready to push the product guide updates for Type of Care & Provider and Telephone Appointments to our Git repo. 

How do you want to handle the following: pushing the product guides to Git, creating a ticket for contact center and alerting training team? One thing to note about the contact center is that they've approved the LoROTA changes. But, if we submit these guides to them, all of the LoROTA changes will be missing since we haven't pushed that to main yet. It could be confusing. 

Also, I'd recommend we keep this ticket open so I can evaluate whether Danielle's page needs updating AFTER the LoROTA updates get merged to main. 

Anyways, let's catch up next week. Again, I could push the product guide updates to Git now, which is my recommendation. https://drive.google.com/drive/folders/18YrEyHu_Fi1C5dKODZJzjmC7CvvjyuX9

**Comment by benbrasso-agile6** [comment]
@loripusey did pushing the ABstract branch to main and syncing down updates to Sketch get deleted from the release to production template?

**Comment by loripusey** [comment]
Nope, still there in the template. Maybe it got deleted from the individual ticket.
 ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9b326915-7fc7-44af-9a40-59d0b565d3a4)

**Comment by benbrasso-agile6** [comment]
yeah, I think it's in the Release to Production ticket, which is closed vs. the update release artifacts ticket. I'm not necessarily recommending it should be moved. I'm more just pointing out that distinction for the moment.

**Comment by loripusey** [comment]
I kept them separate to allow the product guides to be done before we go to production

**Comment by benbrasso-agile6** [comment]
Makes sense. I forgot.

**Comment by loripusey** [comment]
Looks good, left one comment (grammatical) on Check-in Word w/ track changes.

**Comment by benbrasso-agile6** [comment]
Pushed updates to [Git](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md)

**Comment by benbrasso-agile6** [comment]
@zach-park there is a task in the comments above for you. It is to update the user flow. Take a look at my notes in the comment above about what should be updated.

**Comment by zach-park** [comment]
@benbrasso-agile6 , could you re-ulpload the attached "Pre-check-in user flow (Read-only) for user guide.png" file? Thank you!

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/42032#issuecomment-1213507812

**Comment by benbrasso-agile6** [comment]
It looks like it’s working. I relinked to the comment above.

**Comment by zach-park** [comment]
Updated and merged to the master branch:

Portrait version: https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=6419aab2-c5a1-43ec-b24e-10f95f0be244&mode=design

Landscape version: https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=4d0369ce-7ad6-47b1-9bc3-c40521fe7ef7&mode=design
