### ISSUE TITLE
[Design] Wireframes for Adding Additional Info to Pre-Check-in and Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42030]
## User Story
As a Veteran, when I am using Patient Check-in to check-in for my appointment, I would like to see the physical location, Doctor's name, and type of appointment for my in-person appointments so that I understand where my appointment is and to whom I will be speaking.

## Background info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653665302561659)
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/3c96cf25-61fc-4f49-8e20-adcd43c3770e)

### Check-in workflow
- Given I
    - Have verified my identity in the Check-in application and completed contact confirmation, if applicable
- When I
    - See my list of appointments for today
- Then I
    - See the physical location, Doctor's name, and type of appointment for each in-person appointment

### Pre-Check-in workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the physical location, Doctor's name, and type of appointment for each in-person appointment

## Tasks
- [ ] Finalize detailed mockup and callouts of this feature 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] Update VA's Sketch cloud

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] VA's Sketch cloud contains the latest sketch files

**Comment by kristenmcconnell** [comment]
Trying to understand what appointments have provider name and type of care even available to display within VAOS's V2 initiative. [Slack thread ](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259)on the topic.

**Comment by kristenmcconnell** [comment]
[Initial check-in wireframe exploration](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/CFA0317F-7DCB-4355-8DD5-1D81B8D67FF3) that I'm going to review with Zach and Ya-ching tomorrow.

**Comment by kristenmcconnell** [comment]
How VAOS is going to display some of this information on their [summary](https://www.figma.com/file/sWiXcrB6sgw1z4F8AtOqfK/VAOS---VA-Design-System?node-id=1331%3A5509) and [details](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?node-id=54%3A11449) pages.

**Comment by kristenmcconnell** [comment]
Here is the appointment information display that the mobile app is moving toward: https://www.sketch.com/s/806417fd-3d64-4da6-9529-0eef4fd48e2e/a/eKeomZa/play

Both VAOS and mobile app are future proofing their designs a little. They are designing so the data can be shown if available. If it's not, they don't display it.

**Comment by kristenmcconnell** [comment]
[Pre-check-in wireframe exploration](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/D549FABD-E652-4241-BFE0-9BCED63DFC01). Will review at UX sync tomorrow.

**Comment by kristenmcconnell** [comment]
Ignore the above comments. I'm going to write all the details of what I did in this comment.

My wireframe explorations (They also list out our outstanding questions):
- [Pre-check-in](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/D549FABD-E652-4241-BFE0-9BCED63DFC01/canvas)
- [Check-in](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/p/CFA0317F-7DCB-4355-8DD5-1D81B8D67FF3/canvas) 

I had conversations with VAOS and the mobile app team when I was completing this ticket, since I know that both teams are completing similar redesigns. The reason for this redesign is due to the V2 database changes that are coming soon. The Slack thread with most of our conversation can be viewed [here](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259). 

Links to VAOS and mobile app's newest designs for available within that Slack thread. Here is a [quick link to VAOS](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=76%3A21478) though.

Here are the appointment data fields that currently exist. There are even more that we could show. The ones we use today are italicized.
- In person vs. telephone, etc.
- _Facility_
- _Time_
- _Clinic_
- Physical location (Floor and Room no.)
- Booking note
- Directions (GPS)
- Add to calendar

Coming with V2
- Type of care
- Provider name

The UX team has multiple questions now, which we discussed at UX sync this morning based upon my explorations. Therefore, we came up with the following next steps:
1. Review and finish the physical location UI work, that I completed, in order to hand off that work off to engineering. @ytsaoca Volunteer to pick up this work where I left off; however, we will need another ticket. @zach-park will support her.
2. We need a design spike to talk to VAOS to better understand the V2 database changes. 
3. We don't have a full understanding on how to prioritize the display of these data fields for Veterans. What combination of data would be good to display on Intro and Confirmation pages within Pre-check-in and Check-in. Therefore, we would like to do the following things:
  - Talk to VAOS and native mobile app about how they tested to get their designs
  - Run a remote 5 sec impression test
  - Card sort study

@benbrasso-agile6 said he could help elaborate the need for these next steps with @loripusey and get tickets created in my absence (since I'll be on vacation).

**Comment by loripusey** [comment]
@kristenmcconnell Can you create follow-up tickets for this? We have a card sort one already but I'm not sure what else based on the above information.
cc: @ytsaoca
