### ISSUE TITLE
[Design] MyHealth - Secure Messages - Design "create folder" desktop & mobile pages

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42035]
## Issue Description
As a secure messaging user, I need a page that allows me to create folders in which to store my secure messages.

---
## Tasks
- [x] Design "create folder" page for desktop
- [x] Design "create folder" page for mobile
- [x] Drop link to mockups into a comment on this ticket
- [x] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for review by PO.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Desktop: 
[Folders](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/v/r5J0aq/a/Jn35bL0/r/JK3bbe), 
[new folder modal](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/v/r5J0aq/a/4a3LGJz)
[folder added](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/v/r5J0aq/a/eKV9O1m/r/JK3bbe)

Mobile: 
[Folder page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/dlpQGR3)
[Create folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/zxa0p44)
[Folder added](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ZOm90EY)
