### ISSUE TITLE
Permission denied error in os-check-utility

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#42033]
## Description
The following error is being seen consistently for `ip-172-31-5-108.us-gov-west-1.compute.internal`:
```
07:00:28  PLAY [Check for common system issues] ******************************************
07:00:28  
07:00:28  TASK [Gathering Facts] *********************************************************
07:00:28  Monday 30 May 2022  11:00:28 +0000 (0:00:00.158)       0:00:00.158 ************ 
07:00:30  ok: [ip-172-31-11-78.us-gov-west-1.compute.internal]
07:00:30  ok: [ip-172-31-0-33.us-gov-west-1.compute.internal]
07:00:30  ok: [ip-172-31-1-68.us-gov-west-1.compute.internal]
07:00:31  ok: [ip-172-31-3-26.us-gov-west-1.compute.internal]
07:00:31  ok: [ip-172-31-3-107.us-gov-west-1.compute.internal]
07:00:31  ok: [ip-172-31-3-98.us-gov-west-1.compute.internal]
07:00:33  [WARNING]: Unhandled error in Python interpreter discovery for host
07:00:33  ip-172-31-5-108.us-gov-west-1.compute.internal: Failed to connect to the host
07:00:33  via ssh: Warning: Permanently added 'ip-172-31-5-108.us-gov-
07:00:33  west-1.compute.internal,172.31.5.108' (ECDSA) to the list of known hosts.
07:00:33  Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
07:00:33  
07:00:33  ok: [ip-172-31-3-28.us-gov-west-1.compute.internal]
07:00:33  ok: [ip-172-31-3-185.us-gov-west-1.compute.internal]
07:00:33  ok: [ip-172-31-1-154.us-gov-west-1.compute.internal]
07:00:33  fatal: [ip-172-31-5-108.us-gov-west-1.compute.internal]: UNREACHABLE! => changed=false 
07:00:33    msg: |-
07:00:33      Data could not be sent to remote host "ip-172-31-5-108.us-gov-west-1.compute.internal". Make sure this host can be reached over ssh: Warning: Permanently added 'ip-172-31-5-108.us-gov-west-1.compute.internal,172.31.5.108' (ECDSA) to the list of known hosts.
07:00:33      Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
07:00:33    unreachable: true
...
```
The "OS check needs attention in utility!" message has come up in #devops-deploys every day for at least one month, but I'm only able to see logs from the last five days. I confirmed that permission denied error for `172-31-5-108` shows up in all of the logs for the past five days.

## Background/context 
[Link to os-check.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/os-check.yml). Although I don't see the "Gathering Facts" task.
Failing logs: http://jenkins.vfs.va.gov/job/utility/job/os-check-utility/1664/console

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Investigate why this is happening
- [ ] Implement fix

## Acceptance Criteria 
- [ ] os-check no longer fails.

---
### Reminders
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Kyle is going to tear down this machine until if/when it is needed again https://dsva.slack.com/archives/C37M86Y8G/p1653994847363669

**Comment by rmtolmach** [comment]
Confirmed that it no longer exists:
![image](https://user-images.githubusercontent.com/10993987/171203121-f1615d3a-75b3-4e9f-a1a5-861cccf6f0d3.png)
