### ISSUE TITLE
Audit of text links in featured content blocks

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42038]
## Issue Description
Beth asked us to look at the site and find examples of text links and clickable phone numbers in the blue featured content blocks on benefit detail pages.

She's more interested in the text links and we only need to show 5-10 examples rather than searching through the whole site.

## Tasks
- [ ] Audit pages for text link/clickable phone numbers in featured content blocks (Megan)
- [ ] Create list in ticket for Beth to review (Megan)

## Acceptance Criteria
- [ ] List of text links/clickable numbers is ready for Beth

**Comment by megzehn** [comment]
Hi! Do these examples work? I didn't find any phone numbers, but I'm happy to keep looking if it would be helpful. 

https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/
https://www.va.gov/health-care/order-prosthetic-socks/
https://www.va.gov/health-care/covid-19-vaccine/
https://www.va.gov/health-care/health-needs-conditions/womens-health-needs/
https://www.va.gov/health-care/health-needs-conditions/
https://www.va.gov/health-care/about-va-health-benefits/
https://www.va.gov/health-care/health-needs-conditions/substance-use-problems/
https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/
https://www.va.gov/housing-assistance/home-loans/loan-types/cash-out-loan/
https://www.va.gov/life-insurance/options-eligibility/s-dvi/

**Comment by megzehn** [comment]
^ @RLHecht flagging that this is validate now!

**Comment by RLHecht** [comment]
@bethpottsVADEPO This is complete and ready for next steps on your part.

**Comment by RLHecht** [comment]
Closing as completed
