### ISSUE TITLE
[Design] MyHealth - Secure Messaging - Design empty folders/inbox desktop page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42042]
## Issue Description
As a secure messaging user, I need a way to empty my inbox and folders. Note: Please confirm the use case for this with the legacy team.  There is not enough context in the PI planning board.  Not sure this is to empty the inbox/folders, or to create a few of what they look like empty (aka with no message).

---
## Tasks
- [x] Design  empty folders/inbox page for desktop
- [x] Design  empty folders/inbox page for mobile
- [x] Drop link to mockups into a comment on this ticket
- [x] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for review by PO.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Desktop: empty landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/nRjzpyk)
[Desktop: empty drafts folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/Qbd5vEY)
[Desktop: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/xrmapJm)
[Desktop: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/EL35bVA)

[Mobile: empty landing page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/3OrEqvm)
[Mobile empty draft page](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/m19dp7L)
[Mobile: empty sent messages folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/DPQ5bpe)
[Mobile: empty deleted messages](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/jgLW0Z7)
