### ISSUE TITLE
Create 2 new hub pages on the Foreign Medical Program

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#42044]
# Story

As a Veteran who lives outside the U.S., I need to know if I'm eligible for care under the Foreign Medical Program. And if I'm currently enrolled in the program, I need to know how to file a claim.

## What's needed

2 new hub pages:

- **Foreign Medical Program:** Overview of what FMP is, eligibility criteria, and how to enroll. 
- **File a Foreign Medical Program claim:** How to file an FMP claim with link to form. 

## Source materials

- [Community care Foreign Medical Program (FMP) page](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp)
- [Community care Foreign Medical Program Benefits and Claims information page](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/fmp_benefits_claims.asp)

### Keyword and search information
- IRIS: Veterans living abroad (423 IRIS views in 1 month - 10/2020)
- site search: Jan - Oct: foreign medical program (706)
- #1 organic search results position for: "va foreign medical program" (msv: 170), "veterans affairs foreign medical program" (msv: 70), "foreign medical program va" (msv: 50), "does va healthcare cover overseas" (msv: 50), and "fmp va" (msv: 50)
- #2 organic search results position for several keywords, including: "germany va hospital" (msv: 210), "va europe" (msv: 70), "fmp hours" (msv: 50), "list of va hospitals overseas" (msv: 90), "fmp military" (msv: 50) 

### Tasks

- [x] Write draft of Foreign Medical Program Overview page 
- [x] Write draft of Foreign Medical Program claim page 
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Submit for Danielle review in ticket #44926

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Added more detail to this ticket for grooming. I'll continue to build out tickets in this epic.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Is there more info you want to put in here for our team to start working on this in the next sprint? Is it migrating the content from the 2 source pages you posted into the 2 new benefit detail pages you describe above?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht.
- Yes, this is migrating the content from the 2 sources pages into the 2 new benefit detail pages. We'll work with @mnorthuis to determine final IA on this.
- As we're creating these pages, we should also identify any content that belongs in R&S rather than benefit hubs. It would be great if you all could use the refined content placement criteria (step 1 of [this process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/resources-and-support-author-pilot/process.md)) to decide this. Feel free, of course, to reach out with questions.
- For the COVID-19 content - some of that appears to be duplicative of general claim content (and can go on claim page). For other COVID-19 content, we can have a note or an alert re: COVID-19 vaccines and link over to the vaccine mini-hub. If there's additional info on COVID-19 vaccines that we might need to surface, we can consider adding it to the vaccine hub.
- If the team thinks that some of the content isn't necessary at all, please flag for consideration to cut.

Thank you!

**Comment by aliyahblackmore** [comment]
Update here that I've started on this ticket! I was working on the claim page, but pivoted to another ticket (Claim Status tool). Will continue on this next week!

**Comment by aliyahblackmore** [comment]
Hi @laurwill a draft of the How to file a FMP claim page is ready for you! Attaching a word document.

One question as I was doing another review:
There are a few documents that outline the claims process ([fact sheet](https://www.va.gov/COMMUNITYCARE/docs/pubfiles/factsheets/FactSheet_04-02.pdf), [guide](https://www.va.gov/COMMUNITYCARE/docs/pubfiles/programguides/FMP_Guide.pdf#), [brochure](https://www.va.gov/COMMUNITYCARE/docs/pubfiles/brochures/FMP_brochure.pdf#), [YouTube video](https://www.youtube.com/watch?v=eY6zyRRhk8E&t=127s)), so I am wondering if we should be referencing one over another, as a sort of source of truth? Some documents provide similar or the same details, as well as further detail and all are included on the FMP legacy page. Noting that the guide, for example, is from 2017 but the brochure is from 2021.

[How to file a FMP claim_New Version_June 21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8954691/How.to.file.a.FMP.claim_New.Version_June.21.docx)

**Comment by laurwill** [comment]
Thanks so much for your thorough work on this, @aliyahblackmore ! I reviewed your updated draft and made some more suggested changes. See comments for you in yellow highlight. Could you clean up the doc, add the contact info to the last section, and pass to Megan for copyedit? Let me know if you have questions or want to chat about anything!
[How.to.file.FMP.claim_LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8992508/How.to.file.FMP.claim_LW.docx)

**Comment by aliyahblackmore** [comment]
Update: Laura is reviewing some more changes to the word document before passing to Megan, as there was some new content added in.

Word document here:
[How.to.file.FMP.claim_AB_June 27.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9001882/How.to.file.FMP.claim_AB_June.27.docx)

**Comment by laurwill** [comment]
Thanks for all your very thoughtful work here, @aliyahblackmore ! I made a few last changes and addressed some additional questions to the SME — could you clean up the doc, remove our internal comment chains in yellow highlight, and pass to Megan for copyedit? Thank you!
[How.to.file.FMP.claim_LW_6.30.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9020133/How.to.file.FMP.claim_LW_6.30.docx)

**Comment by aliyahblackmore** [comment]
Thanks @laurwill ! @megzehn this page is ready for you to copy edit. 

I have a note in there for you (just an FYI) re: how the Australia toll free number is listed.
[How.to.file.FMP.claim_AB_6.30.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9020540/How.to.file.FMP.claim_AB_6.30.docx)

**Comment by aliyahblackmore** [comment]
Hi @laurwill the FMP page draft is ready for you! I've included a few questions!
[Foreign Medical Program_AB_June 30.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9023159/Foreign.Medical.Program_AB_June.30.docx)

**Comment by laurwill** [comment]
Hi @aliyahblackmore — **great job** digging through a huge number of sources to draft this page. What a doozy! This doc is getting a bit complex, so could you please:
- Review and accept my tracked changes (and of course ask any questions that come up!)
- Review my comments to you in blue highlight and remove these (if they're resolved)
- Leave all the questions addressed to Danielle and SMEs
- Add info about dental care to the new accordion section, if you feel we have enough to say there that's specific to FMP
[Foreign.Medical.Program_LW_7.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9072538/Foreign.Medical.Program_LW_7.7.docx)

I also made a few consistency updates to the File a claim page, based on wording decisions in the main page. Can you also accept changes and then repost both docs for Megan to copyedit?
[How.to.file.FMP.claim_LW_7.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9072540/How.to.file.FMP.claim_LW_7.7.docx)

Thank you for all your thoughtful work on these pages!

**Comment by aliyahblackmore** [comment]
Thanks, Laura! I accepted the changes and cleaned up the comments. I also left in the question regarding "companion services" for the time being, but accepted your suggested change. 

Note: As we discussed we'll do another quick review after Megan copy edits, before passing to Danielle. 

@megzehn both of these pages are ready for you to copy edit! Thank you :) 

Foreign Medical Program
[Foreign.Medical.Program_AB_7.8.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9074230/Foreign.Medical.Program_AB_7.8.docx)

Foreign Medical Program Claims 
[How.to.file.FMP.claim_AB_7.8.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9074369/How.to.file.FMP.claim_AB_7.8.docx)

**Comment by megzehn** [comment]
Hi @aliyahblackmore and @laurwill - Great work on these! I just copyedited them and am attaching my minor edits/comments. 

[https://app.zenhub.com/files/133843125/e981b5f5-d5f0-47[https://app.zenhub.com/files/133843125/cb9300e0-b24f-4605-9592-c4d928e4f0bb/download](https://app.zenhub.com/files/133843125/cb9300e0-b24f-4605-9592-c4d928e4f0bb/download)55-ba71-2143e4ef113c/download](https://app.zenhub.com/files/133843125/e981b5f5-d5f0-4755-ba71-2143e4ef113c/download)

**Comment by laurwill** [comment]
Thanks Megan! I've posted for Danielle's review in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44926). Closing this out.
