### ISSUE TITLE
[Design] MyHealth - Design "delete folder" page for desktop and mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42040]
## Issue Description
As a secure messaging user, I need a way to delete secure messages folders I have created.

---
## Tasks
- [x] Design "delete folder" page for desktop
- [x] Design "delete folder" page for mobile
- [x] Drop link to mockups into a comment on this ticket
- [x] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for review by PO.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
[Desktop:delete folder](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/pazJmoG) 
[Desktop: confirm delete](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/YGOb7rm)

[Mobile: delete folder ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/ago5v9z)
[Confirm delete](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/09yqJlW)
