### ISSUE TITLE
Create OAuth logout components in vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42059]
## Issue Description
This will add and fulfill the OAuth `/logout` body of work

## Tasks
- [x] Conditionally call logout based on the Sign in method (OAuth/SAML)
- [x] Create documentation as necessary for Sign in Service (Frontend)
- [x] Create unit tests to verify functionality
- [x] Uses the CSP to determine the logout mechanism (Login.gov is a redirect, rest are a backend request)

## Acceptance Criteria
- [x] I can hit the SiS `/logout` endpoint and I am no longer able to reach restricted endpoints in vets-api
