### ISSUE TITLE
Update Identity-related documentation

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#42056]
## Issue Description
This body of work will be to update Identity-related documentation.

## Tasks
- [ ] Create an archive/deprecated folder of past iterations or outdated information (aka Cognito)
- [ ] Update all documentation to have dates somewhere so we can keep track

## Acceptance Criteria
- [ ] Looking at Identity documentation, I can see a date at the top of the page
- [ ] Looking at Identity documentation, I can see an archived/deprecated folder filled with older/outdated information that is no longer relevant (aka AWS Cognito)

**Comment by bosawt** [comment]
@asg5704 Is this still a ticket we want around?

**Comment by asg5704** [comment]
Close it

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
