### ISSUE TITLE
Add OAuth refresh ability on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42052]
## Issue Description
This will track the body of work for the FE logic surrounding when the `/refresh` endpoint will be triggered.  There will be specific logic to request a new token.

## Tasks
- [x] Ensures AutoSSO is not used when user is signed in with OAuth
- [x] Check to see if the Cookie is passed the current time on the FE
- [x] If session time is past, create a request to hit the `/refresh` endpoint
- [x] If session is not past the time, do not send request

## Acceptance Criteria
- [x] The `/refresh` endpoint is hit if the session is passed its session time (aka TTL is not live)
- [x] Prevent `/keepalive` endpoint from being hit while a user is authenticated with OAuth
