### ISSUE TITLE
Create OAuth callback components on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42054]
## Issue Description
This will add and fulfill the OAuth `/callback` body of work

## Tasks
- [ ] Create & verify the `state` parameter`
  - [ ] Create the `state` using requirements
  - [ ] Store `state` in local/session storage
  - [ ] Verification of the `state` parameter
- [ ] Create documentation as necessary for Sign in Service (Frontend)
- [ ] Create unit tests to verify functionality

## Acceptance Criteria
- [ ] I can hit the SiS `/callback` endpoint and receive back an access token in the headers
