### ISSUE TITLE
Create OAuth authorize components on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42053]
## Issue Description
This will add and fulfill the OAuth `/authorize` body of work for vets-website

## Tasks
- [x] Add an ability to dynamically update the Sign in Buttons to use the Sign in Service URL
- [x] Create an ability for the code challenge & verifier
  - [x] Create the `code_verifier` method and OAuth settings
  - [x] Create a `code_challenge` with requirements
- [x] Generate the SiS endpoint for `/authorize` with the `code_challenge` and `code_challenge_method` query parameters
- [x] Create documentation as necessary for Sign in Service (Frontend)
- [x] Create unit tests to verify functionality

## Acceptance Criteria
- [ ] I can hit the SiS `/authorize` endpoint and receive back an access token in the headers

**Comment by nsoutouras** [comment]
@nsoutouras add new SiS Epic and add this to it.
