### ISSUE TITLE
[A11y Maintenance Audit] Burials

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#42061]
# [A11y Maintenance Audit] Burials

Maintenance audit of burials. A list of issues will be created to be resolved below. More complex tickets that have dependencies or require interdisciplinary work will be converted into individual issue tickets.

## Coverage

This maintenance audit will cover:

- [x] VoiceOver, Safari, iPhone
- [x] VoiceOver, Safari, Macbook Pro
- [x] Chrome, Macbook Pro 

It will follow WCAG 2.1 AA standards with mobile considerations.
- Test user `insert test user` using ID.me [login password here](link to password)
- [Link to Burials page](https://staging.va.gov/burials-and-memorials/application/530/introduction)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements

**Comment by joshkimux** [comment]
<img width="1059" alt="Screen Shot 2022-06-02 at 3 09 30 PM" src="https://user-images.githubusercontent.com/14154792/171718721-7181bd87-2b52-447c-90a9-44c6f501aeb0.png">

@jacobworrell not sure where to place this as it isn't an a11y defect but more of a UX/content issue, any thoughts?
