### ISSUE TITLE
PM | Profile Information Revisions | UAT Go/No Go

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42063]
## Background
Team go/no-go meeting to determine if we are prepared to proceed with UAT for Personal Information revisions (gender identity and preferred name).

## Tasks
- [x] Schedule go/no-go (week of May 30th)
- [x] Execute meeting and complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/revisions-uat-readiness.md)
- [ ] Perform any follow-up action items as needed
