### ISSUE TITLE
Create OAuth token exchange components on vets-website

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42060]
## Issue Description
This will add and fulfill the OAuth `/token` body of work

## Tasks
- [x] Generate the SiS endpoint for `/token` with the `grant_type`, `code`, and `code_verifier` query parameters
  - [x] The `grant_type` should always be `authorization_code`
  - [x] The `code` should be generated using specific requirements outlined in the docs
  - [x] The `code_verifier` should verify the `code` is not malformed
- [x] Create documentation as necessary for Sign in Service (Frontend)
- [x] Create unit tests to verify functionality

## Acceptance Criteria
- [x] I can hit the SiS `/token` endpoint and receive back a refresh token
