### ISSUE TITLE
[DESIGN] Household Information: dependents design

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#42077]
## Background

This issue is based on a high-level [overview of potential design changes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/Household%20info%20design%20discovery.pdf) to the household information section. 

The dependents section of the 10-10EZ household information flow needs to be updated. Currently, adding multiple dependents greatly increases page scroll length, so we need a more user-friendly way to handle this, with 

## Screenshots

<details>
<summary>Single dependent form fields image</summary>
<img width="187" alt="image" src="https://user-images.githubusercontent.com/81988788/172437030-77d1831a-73ad-4ce7-a156-32ec8046fcf9.png">
</details>

## Tasks

- [ ] Mobile-first design of the dependents page
- [x] Accessibility specialist feedback
- [ ] Content specialist feedback (if applicable)
- [ ] Plan for design intent / collab cycle for any new design patterns/components

**Comment by nicko-amida** [comment]
So, the currently in-use [list and loop pattern](https://design.va.gov/patterns/forms/list-and-loop) for forms would work, but I have since learned that this pattern is being discouraged. It is currently in use for the eBenefits flow:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/81988788/176711502-c2645754-1bea-4ac3-9d2c-2b20d408f0ea.png">

**Comment by nicko-amida** [comment]
The [financial status report tool](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022114/simulate/sitemap?mode=i) and another example of a dependents flow, but it doesn't allow for the same kind of input fields as the 1010EZ needs.

**Comment by nicko-amida** [comment]
Previous list loop research and design ([FSR List Loop Redesign #25881](https://www.sketch.com/s/92b41945-e57a-4eaa-9c66-ea017551f466)) suggests the current pattern isn't very effective, and we need some alternative to it.

**Comment by nicko-amida** [comment]
The dependent's flow design was included in the [household wireflow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/eKVZxja), so I'm closing this issue. The specific full mockup for the household flow and dependent's design will be in the same forthcoming issue.
