### ISSUE TITLE
[Vets-API / EKS] Update architecture and support documentation related to deployment in the dev environment 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42075]
## Description
As part of the parent initiative's definition of done (see #35039), architecture and support documentation should be updated with accurate information that describes the deployment of Vets-API to EKS in the dev environment. 

### VFS-facing: 
- [x] [Platform website builds and deploys info ](https://depo-platform-documentation.scrollhelp.site/developer-docs/environments#Environments-Buildsanddeploys) - #42396 

### Platform-facing: 

**Service Docs (operational info):**
  - [x] [Vets-API](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594594/Vets-API) - #42390
  - [x] [Forward Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594279/Forward+Proxy) - #42391
  - [x] [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy) - #42392 

**Support docs (How do I...?):** 
- [x] [Keep EKS-Deployed Vets-API Up to Date with BRD-Deployed Vets-API](https://vfs.atlassian.net/wiki/spaces/OT/pages/2146140164/Keep+EKS-Deployed+Vets-API+Up+to+Date+with+BRD-Deployed+Vets-API) - #42393
- [x] [Perform Off-Cycle Deploy of vets-api](https://vfs.atlassian.net/wiki/spaces/OT/pages/2034204681/Perform+Off-Cycle+Deploy+of+vets-api) - #42394

## Architecture diagrams to update or create 
- [x] **End-to-end request flow** from the user perspective _(see example from Reverse Proxy service doc)_ - #42450
- [x] **EKS infrastructure** specifics _(cluster, node, pod, service, etc)_ - #42453
- [x] General **deployment pipeline overview** that explains GitHub -> ECR -> ArgoCD -> EKS integration _(example [here](https://docs.google.com/presentation/d/1HUPfcybpV4RHnuCUzvNH2UYv8zPPDAJqVFOI0SVqwoU/edit#slide=id.gc88347944a_0_7))_ - #42456

---
## Tasks
- Create subtasks for individual documents or diagrams and link to this epic:
  - [x] Platform Website (doc)
  - [x] Vets-API (doc)
  - [x] Forward Proxy (doc)
  - [x] Reverse Proxy (doc)
  - [x] Configuration sync (BRD / EKS) (doc)
  - [x] Off-Cycle Deployments (doc)
  - [x] End-to-end Request Flow (diagram)
  - [x] EKS Infrastructure (diagram)
  - [x] Deployment Pipeline Overview (diagram)
  - [ ] Create an ADR to reflect the decisions and action occurring now

## Acceptance Criteria 
- [x] Documents and diagrams have been updated with accurate information that describes the deployment of Vets-API to EKS in the development environment

**Comment by jhouse-solvd** [comment]
@jbritt1 - We only need to focus on updating information _related to any changes with how Vets-API is being deployed in the dev environment_ that might be listed in those docs. 

If you can identify specific sections of the Service docs listed above that might need updating, that would be super helpful. If any docs appear to be completely accurate, then we can notate that and move on.

**Comment by mchelen-gov** [comment]
These are some good references, I would suggest adding an ADR to reflect the decisions and action occurring now.

**Comment by jbritt1** [comment]
> These are some good references, I would suggest adding an ADR to reflect the decisions and action occurring now.

Added to sub-tasks and will create a ticket to capture this as well

**Comment by jbritt1** [comment]
Forward Proxy documentation updated and ticket closed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42391#issuecomment-1148708953

**Comment by jbritt1** [comment]
Commented and closed the ticket for reviewing the revproxy service doc: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42392#issuecomment-1148801326

**Comment by jbritt1** [comment]
Commented and closed the ticket for reviewing the configuration sync (BRD/EKS) documentation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42393#issuecomment-1149001529

**Comment by jbritt1** [comment]
Commented and closed the ticket for reviewing/updating the off-cycle deployment documentation for vets-api: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42394#issuecomment-1150024626

**Comment by jbritt1** [comment]
Commented and closed the ticket for reviewing/updating the platform website documentation on vets-api deployments https://github.com/department-of-veterans-affairs/va.gov-team/issues/42396#issuecomment-1152398478

**Comment by jhouse-solvd** [comment]
@mchelen-gov - This issue was to reflect relevant updates to documentation for this initiative only. I'm not sure that an ADR makes sense or is needed, but if it is... Will you create a new issue that reflects what the ADR should be for? 

I'd like to close this issue as all of the documentation has been updated.
