### ISSUE TITLE
[Research] - Auth Profile - Personal Information Revisions - Kick off recruiting for research

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42088]
## Background

After the conversation guide and research plan have been approved, we will need to kick off the recruiting effort for this exercise.

## Tasks
- [x] Add ticket to research repo
- [x] Share research plan and conversation guide with Shane and Clayton for approval and recruiting
- [x] Make any revisions needed to research plan and conversation guide

## Acceptance Criteria
- [x] Ticket has been added to repo
- [x] Research plan and conversation guide has been shared with Shane and Clayton for approval and recruiting
- [x] Any revisions needed have been made to research plan and conversation guide

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member

**Comment by Samara-Strauss** [comment]
Closing!
