### ISSUE TITLE
Audit/Update Domo Dashboard Eligibility Card

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42082]
## Issue Description
We need to audit and update the Domo dashboard [eligibility card](https://va-gov.domo.com/page/1550814739) based on the recent changes to VFS teams (add new teams, remove old teams, etc) as applicabile

---
## Tasks
- [x] Review current eligibility [table](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit?pli=1#gid=1660978947)
- [x] Update VFS teams (add new, remove old, change names, etc) as applicable
- [x] Refresh Domo card data based on table changes

## Acceptance Criteria
- [x] When the above tasks are complete and the table is up to date based on recent changes.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Adding [comparison table](https://docs.google.com/spreadsheets/d/1nFE_iWHB3kdAD0DFIKUBgzGh5J7QgpNDOOnIXI0XHrw/edit#gid=0) for reference.
