### ISSUE TITLE
[Design] | Pilot Research Sessions | Personal Information Revisions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42087]
## Background

Tasks needed in support of upcoming research project.

## Tasks
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Christina (Moderator)"
- [x] Run pilot
- [ ] Debrief pilot
- [x] Revise conversation guide

## Acceptance Criteria
- [x] Pilot complete
- [x] Conversation guide revised as needed
- [ ] Any bugs ironed out before sessions begin
