### ISSUE TITLE
[CDP] Make styling consistent throughout app

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#42092]
## Issue Description
Update the margins/styling across all three CDP apps. Some class name and other stylings are duplicated from the CombinedPortalApp down and we should probably update them to a more manageable state. This should include the loading modals we have sprinkled throughout. 

---
## Tasks
- [x] Loading Modals are rendering in a uniform location
- [x] Margins & Styling are uniform throughout CDP (still matching mock)

## Acceptance Criteria
- [x] CDP has uniformed styling throughout
