### ISSUE TITLE
[CDP] Clean up duplicate code caused by merge

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#42094]
## Issue Description
Some functions were duplicated while developing updates in separate apps. This ticket is meant to capture the effort of removing duplicated code and cleanup messy references that may have been leftover during the merge. 

---
## Tasks
- [ ] Move renderAlert to combined folder
- [ ] Check for other duplicate code caused by merge

## Acceptance Criteria
- [ ] CDP is free of duplicated code caused by merge

**Comment by Dr-Pongo** [comment]
Moving to backlog bc this is low impact and really a tech-debt ticket

**Comment by Tom-Davis** [comment]
Discover any areas where issues exist and document for future corrections.

**Comment by OptionSelect** [comment]
After extensive searching, and this ticket being very old, I can say with confidence that any code remaining from the combination of Debt Letters and Medical Copays to form Combined Debt Portal is unique enough or handling its own data structures separately purposefully.
