### ISSUE TITLE
Check Post-9/11 Chapter 33 dates and rates in Drupal draft

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42096]
## Issue Description
Beth has done a final edit of the Post-9/11 GI Bill (Chapter 33) rates page and updated the rates and the dates for this academic year. We need to check her changes against the legacy source page.

Source page: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080122.asp

Drupal preview link: http://preview-prod.vfs.va.gov/preview?nodeId=1009

We also need to remove the 2019 past rates page and add the 2022 page in the Past rates section at the bottom of the Drupal page. All current rates pages show the past 3 years

## Tasks
- [x] Check dates and rates (Megan)
- [x] Add 2022 legacy rates to Past rates section (Megan)
- [x] Remove 2019 legacy rates from Past rates section (Megan)

## Acceptance Criteria
- [x] Rates and dates are accurate in the Drupal preview

**Comment by megzehn** [comment]
This looks good! The only section I couldn't find and verify on the source page is this one on tutorial assistance and a high-technology program.  

@RLHecht do you know where that might be? Or is this a Beth question? 


![Screen Shot 2022-06-08 at 7.47.17 AM.png](https://images.zenhubusercontent.com/6268142534de80edf577caef/0b5eb938-0506-4675-a694-e2bb10017a64
)

**Comment by megzehn** [comment]
Great. Thanks for flagging this and for checking the years, @RLHecht! Those are now updated.

**Comment by RLHecht** [comment]
Thanks Megan. I'm going to close this ticket out. FYSA @bethpottsVADEPO. I'll create a separate ticket once we're ready to send several of these pages to the stakeholders to track that work.
