### ISSUE TITLE
[FE] Change Text for VAOS Link

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42107]
## Releasing
- We will push this to production as soon as the work is ready
- Ben will do the Product Guide updates to update the screenshots before the end of the sprint

## Approvers
Zach & Lori

## User Story
As a Veteran, I want to understand the VAOS link so that I will know what to expect if I click the link.

## User Workflow
- Given I
    - Click a Pre-Check-in link
- When I
    - Confirm my contact information
- Then I
    - See on the "you've complete pre-check-in" page the text for the "go to appointment details" link now says "Sign in to manage all appointments"

## Technical Note
Make a new key and delete the old keys from the json files
  
## Wireframes
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/f9ffe503-994b-4107-8eae-6a54635d2fdf)

## Tasks
- [ ] [FE] Swap the text for the link
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
FYI we should not merge this until a release date has been set.

cc @loripusey

**Comment by brianseek** [comment]
This is ready for UX review:
![Screen Shot 2022-06-21 at 12.00.40 PM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/c856a9f0-a509-40b1-ad4e-0dd4d68b5815)

**Comment by niradatta1** [comment]
Looks good, approved @brianseek

**Comment by brianseek** [comment]
closing with UX approval!
