### ISSUE TITLE
[UX] Document Next Round of Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42106]
## Tasks
- [ ] Confirm scope of what we want to include in this (may take some time to gather enough content to submit)
- [ ] Create JSON file with new content to be translated
- [x] Look for a comparison tool to use as a final check that all new content has been included (Lori)
    - Looks like http://www.jsondiff.com/ is good to find the property (i.e. key) differences between the json files
    - Prior to submitting to the SD, we should run this tool on the files to ensure we have all of the keys included for which we don't have Spanish or Tagalog translations

NOTE: We are not submitting yet to SD.

## Scope of Content to be Included in the Next Round
- Content related changes that came out of the telephone user research
- Whatever we prioritize from the [content audit](https://docs.google.com/spreadsheets/d/1Z_W57lCBcbFcTCwHkPcg_Ep5emfdm9ywSkyY-i47Nis/edit?pli=1#gid=0).
- Labels from the physical location, doctor's name, and type of care work 
- New VAOS link text

**Comment by acrollet** [comment]
Note that we need to ensure that the "check in" phrase for VEText gets added to the next round if it hasn't already been translated. (in both languages)

**Comment by niradatta1** [comment]
So far, documenting the text needed in this [Google spreadsheet.](https://docs.google.com/spreadsheets/d/1xv63kaIR_UMq1bssSleMODXEV14OOGwfcL41rBBWhwk/edit#gid=14407571) Once we align on the content audit priorities, we can create the json.

**Comment by loripusey** [comment]
@niradatta1 We also need to include:

- The word "check in" that will be sent to VEText to trigger them to send responses in the right language
- Poster content

**Comment by acrollet** [comment]
@niradatta1 I also don't see "In-person appointment" and "Telephone appointment" from https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/39305 in round 2, let me know if I missed it. Thanks!

**Comment by niradatta1** [comment]
@loripusey The word check in listed in the google spreadsheet under the tab "round 3". And the poster content was part of Round 1 translation (except for the word "check in"). @acrollet most of the telephone appointment updates was part of Round 2, but there may have been some labels missed. Reviewing now to double check, and will make sure any gaps are added to the Round 3 submission.

**Comment by niradatta1** [comment]
@loripusey @acrollet FYI, documenting what we have so far for Round 3 translations, which includes 1) sign in label 2) check in 3) some telephone related labels missed in the last round (phone call, in person) 4) there are some things I'm still confirming based on what I'm seeing in the wireframes too, FYI. Capturing this in the Google Sheets (link below) for now, and then we can convert to JSON once we're ready to submit. Thinking we should have enough to submit once we finish up the telephone content related changes. 'cc @kristenmcconnell  https://docs.google.com/spreadsheets/d/1xv63kaIR_UMq1bssSleMODXEV14OOGwfcL41rBBWhwk/edit#gid=14407571

**Comment by niradatta1** [comment]
@loripusey @kristenmcconnell FYI, updated the Round 3 content translation spreadsheet to include the updated SMS text I finalized in this ticket https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/43546

**Comment by niradatta1** [comment]
@loripusey @kristenmcconnell Added the finalized SMS content from [this ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/37847) to the Round 3 content translation spreadsheet.
