### ISSUE TITLE
[FE] Add Type of Care to Pre-Check-in & Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42113]
## User Story
As a Veteran, when I am using Patient Pre-Check-in to complete pre-check-in tasks for my appointment, I would like to see the Type of Care (e.g., primary care or cardiology) for my in-person or phone appointment so that I understand the context of the appointment, particularly when I have multiple and frequent appointments.

## Background info
Refer to [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#9-veterans-suggested-a-variety-of-features-or-appointment-information-to-add-to-the-experience)

From Ya-ching in slack:
![Screen Shot 2022-08-01 at 9.34.19 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/ae0b5089-874b-44ab-9127-b8d0b059a9a0)

Wireframes: 
CI
https://share.goabstract.com/d8c2f34d-dbb1-4991-89d5-06c012ac009c
PCI
https://share.goabstract.com/51258fc0-ccb8-4bd1-903f-fd1981897ce4

## User Workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the name of Type of Care for my in-person or phone appointment
  
## Wireframes
TBD

## Tasks
- [ ] [FE] Display the Type of Care for each in-person or phone appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
Screenshots for UX validation - pre-check-in:
![Pre-check-in--Introduction.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/92ad3ccf-c9c5-45c3-8dd4-bf6b42d1c979)

![Pre-check-in--confirmation-answer-no-to-all.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/f9e64cc8-5db6-449d-8640-77021ec03685)

**Comment by brdunfield** [comment]
Check-in:

![Day-of-check-in--Appointments.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/0fc4d7b3-f236-45d7-be41-e0ed0d199c30)

![Day-of-check-in--Confirmation.png](https://images.zenhubusercontent.com/60d4bcc1cb1e877f2aba6493/1e3bf3b5-40f1-4f79-b081-5d3647592ee3)

**Comment by sarahknoppA6** [comment]
@ytsaoca to validate today

**Comment by sarahknoppA6** [comment]
cc @zach-park

**Comment by loripusey** [comment]
@zach-park @ytsaoca Can we get this validated please?
cc: @sarahknoppA6

**Comment by ytsaoca** [comment]
@loripusey @brdunfield Looks good!
'cc @sarahknoppA6
