### ISSUE TITLE
[FE] Add Doctor's Name to Pre-Check-in & Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42111]
## User Story
As a Veteran, when I am using Patient Pre-Check-in to complete pre-check-in tasks for my appointment, I would like to see the name of the Doctor I will be seeing (or speaking with) for my in-person or phone appointment so that I understand to whom I will be speaking.

## Background info
Refer to [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#9-veterans-suggested-a-variety-of-features-or-appointment-information-to-add-to-the-experience)

From Ya-ching in slack:
![Screen Shot 2022-08-01 at 9.34.19 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/6f454674-9b47-41a9-a174-6f7ae3cbfbb5)

Wireframes: 
CI
https://share.goabstract.com/d8c2f34d-dbb1-4991-89d5-06c012ac009c
PCI
https://share.goabstract.com/51258fc0-ccb8-4bd1-903f-fd1981897ce4

## User Workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the name of the Doctor for my in-person or phone appointment
  
## Wireframes
TBD

## Tasks
- [ ] [FE] Display the Doctor's name for each in-person or phone appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by loripusey** [comment]
@zach-park @ytsaoca Can we get this validated please?
cc: @sarahknoppA6

**Comment by ytsaoca** [comment]
@loripusey @brianseek Validated!
