### ISSUE TITLE
[FE] Add Type of Care to Check-in Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42117]
## User Story
As a Veteran, when I am using Patient Check-in to check in for my appointment, I would like to see the Type of Care (e.g., primary care or cardiology) for my in-person or phone appointment so that I understand the context of the appointment, particularly when I have multiple and frequent appointments.

## Background info
Refer to [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#9-veterans-suggested-a-variety-of-features-or-appointment-information-to-add-to-the-experience)

## User Workflow
- Given I
    - Have verified my identity in the Check-in application and completed contact confirmation, if applicable
- When I
    - See my list of appointments for today
- Then I
    - See the Type of Care for my in-person or phone appointment
  
## Wireframes
TBD

## Tasks
- [ ] [FE] Display the Type of Care for each in-person or phone appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
