### ISSUE TITLE
Reserach appropriate storage option for generated FSR PDFs

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#42132]
## Issue Description
We need a way to save the PDF files we generate for FSRs so they can be fetched 

---
## Tasks
- [x] Look for best storage options or pre-existing file storage solutions

## Acceptance Criteria
- [x] We know where to store FSR PDFs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
PDFs can be stored in S3, other similar features use that for implementation

Future ticket: https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/42884
