### ISSUE TITLE
[Design] Onsite Notification: Design notification component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42137]
## Background
After our initial onsite notification review Angela received feedback from accessibility on a proposed design that will require more iteration. Matt Dingee recommended we work with the platform team to propose a notification component on the VA pattern library.

## Tasks
- [x] Iterate on notification component design
- [x] Review with team
- [ ] Review with accessibility team in Slack
- [x] Review with Matt Dingee

## Acceptance Criteria
- [x] Notification component design is reviewed with appropriate parties and ready to begin collab cycle

## Resources
- [original ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39090)

**Comment by ajakabcin** [comment]
Continuing into next sprint

**Comment by aagosto90** [comment]
I'm going to close this ticket as we have enough iteration and feedback to include this in testing and enter collab cycle. I'm interested in testing both dismissable versions; one with the X and one with the "Dismiss" text, especially if we get anyone who uses assistive tech, but if not we can discuss that in the collab cycle.
