### ISSUE TITLE
[FE] Deprecate check_in_experience_update_information_page_enabled feature flag

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#42133]
## Tasks
- [ ] Remove the feature flag
- [ ] Remove all orphaned code
- [ ] Remove unit tests
- [ ] Update end-to-end tests

**Comment by sarahknoppA6** [comment]
needs catch up from fe folks on how to validate

**Comment by brianseek** [comment]
closing, confirmed flag removed on stage
