### ISSUE TITLE
Add indicator to differentiate between VBA and VHA debts

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#42131]
## Issue Description
Need a method to differentiate between the two different types of debts a Veteran could have and this can be done by adding a new `enum` data point to separate the two or both

---
## Tasks
- [ ] Find appropriate location for data
- [ ] Add static values and field

## Acceptance Criteria
- [ ] We can use the indicator to differentiate between the two debts
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
