### ISSUE TITLE
[Design]Onsite Notifications: Notification Component Design

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42141]
## Background
After our initial onsite notification review Angela received feedback from accessibility on a proposed design that will require more iteration. Matt Dingee recommended we work with the platform team to propose a notification component on the VA pattern library.

## Tasks
- [ ] Iterate on notification component design
- [ ] Review with team
- [ ] Review with accessibility team in Slack
- [ ] Review with Matt Dingee

## Acceptance Criteria
- [ ] Notification component design is complete and reviewed with appropriate parties

## Resources
- [original ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/39090)
