### ISSUE TITLE
Compile Collab Cycle Controlled Vocabulary List

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#42147]
## User Story
As a collaboration cycle team member, I need to learn the team's standard terms for the various things they do and use those terms when communicating with colleagues and VFS stakeholders, so that I can avoid misunderstandings with my colleagues.

As a collaboration cycle team member, I need to learn the team's standard terms for the various things they do and use those terms when communicating with colleagues and VFS stakeholders, so that I can communicate with VFS stakeholders in a way that's consistent with that of my colleagues

Assignee: @jimuhh 
Peer Reviewer: @CherylEvans 

## Description
During the Collaboration Cycle Requests ticket walkthroughs, multiple opportunities were identified where we could clarify our terms and communication to reduce confusion with teams and ensure consistency within the Collaboration Cycle.

## Impacted Artifacts
[Controlled Vocab Capture List](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2251260066/Controlled+Vocabulary+Capture+List)
Mural Board for terminology exercise

## Tasks
- [x] Create Mural board to document various words we use at different touchpoints
- [x] Facilitate meeting to elicit terminology from experienced colleagues
- [x] Streamline and simplify the [capture spreadsheet](https://docs.google.com/spreadsheets/d/1HKO38Y8gohO5pJWoByf5desM4y9Vnwrdv7eGbsTwmVw/edit?usp=sharing)
- [X] ~~Assign team members short vocabulary addition task~~
  - [ ] ~~Shira~~
  - [ ] ~~Cheryl~~
  - [ ] ~~Brian~~
  - [ ] ~~Allison~~
   - This work is being completed in ticket #47475
- [ ] Set up voting for "top 4/5 challenged words"
- [ ] Communicate priority words 
- [ ] Structure prioritized terms into [controlled vocabulary template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/payments-debts-and-bills.md)
- [ ] Add table of terms to [Platform Product Support](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle) site

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] Governance team has prioritized 5 most challenging words
- [ ] Created a draft issue ticket for addressing each challenging word/term

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
after this is complete, we need to comb through all VFS-facing guidance to ensure we're using those teams consistently

**Comment by shiragoodman** [comment]
scope and AC changed. Estimate moved from 5 to 3.

**Comment by jimuhh** [comment]
Working on streamlining capture sheet

**Comment by jimuhh** [comment]
Streamlining complete.

**Comment by shiragoodman** [comment]
This work is partially complete and will be put on hold. The output of this ticket includes the creation of a [MURAL board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1665500955936/2b8194ca7d65654651b03be8c5cbc757728ca74b?sender=u0574179b1d97118ccc0e3591) that ranks all of our confusing terminology by frequency of use and ambiguity. Screenshot of MURAL below for reference.
![image](https://user-images.githubusercontent.com/71330581/197792622-27cc8d4b-d852-452e-843a-0c7c95bd6578.png)
