### ISSUE TITLE
[Design] | Run Research Sessions | Personal Information Revisions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42160]
## Background
Conduct Personal Information Revision user testing with Veterans

## Tasks
- [x] Download final participant list from Perigean
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Download recordings
- [x] Download notes from Perigean
~- [ ] Create topline summary~

## Acceptance Criteria

- [x] Complete research sessions with Veterans
- [x] Complete all tasks
~- [ ] Create short topline summary~

**Comment by cgednalske** [comment]
@SKasimow Sessions were concluded today! Starting work on the topline summary now, which will be part of next sprint as discussed. I know we talked about a ticket for that, but I'm not sure if there is one yet. Let me know if you need me to create one.

**Comment by cgednalske** [comment]
@SKasimow ok great! Thank you 😃

**Comment by cgednalske** [comment]
@SKasimow is it ok to close this ticket? It's done, but it looks like it was automatically added to next sprint.

**Comment by SKasimow** [comment]
Closing...
