### ISSUE TITLE
SF>DOMO Data Pipeline Automation Feasibility

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#42174]
## Issue Description
_In order to update our DOMO dashboard for support related data (from Salesforce) more frequently, we need some level of automation. We will determine feasibility and document our approach, if one is possible._

---
## Tasks
- [x] _Talk to VA Salesforce Admin(s) to determine what can be done and type of service we could potentially to extract data_
- [x] _Determine what we can do to transform and load data to DOMO based on what we learn in first task._
- [x] _Document findings and approach (or lack of feasibility if that is the case)_

## Acceptance Criteria
- [x] _Findings, feasibility and approach are documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Reaching out to Kimberly to get the contact info for the SF technical person.

**Comment by jwoodman5** [comment]
In order to further the conversation of automated SF data > DOMO, we would need to pursue clearance for a Trusted Internet Connection (TIC), which is a fairly technical and arduous process. We do not have the resources to pursue this at this time and feel cost of any effort to do so would be far greater than the value received. Our semi-automated way of updating DOMO now does not take much time. May revisit later, but closing now.
