### ISSUE TITLE
Place Survey landing in Platform draft Confluence space and conduct Viewport review of content

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#42176]
## Issue Description
Create copy of[ landing](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2194964673/Platform+Satisfaction+Survey) and place in new page on Support's Confluence space.  Before publishing, use the viewport tool to review the content quality

How-to links to review:
https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page
https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization

How to start with Scroll Content Quality in a Confluence space: https://help-cloud.k15t.com/scroll-content-quality/get-started

Draft page in holding space for review: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2225045538/Platform+Satisfaction+Survey

From Governance team: #41340
---
## Tasks
- [x] Review and get started with Scroll Content Quality in the SD Confluence space: https://help-cloud.k15t.com/scroll-content-quality/get-started
- [x] Create copy of landing and place in drafts Confluence holding space for review
- [x] Use Viewport tool to review content quality
- [x] Also do the above for the pages linked at the bottom of the landing page (https://vfs.atlassian.net/wiki/spaces/AP/pages/1523580945/Customer+Satisfaction+Survey and https://vfs.atlassian.net/wiki/spaces/SDT/pages/2100953219/Feedback+Themes+Mural+Boards and the child pages of that last) OR delete links if that's more apt
- [x] Reach out to platform-confluence team for more info on where this content should live. The answer to this will determine if we're ready to publish or not.
- [x] Move page to advised space as a final step for publishing

## Acceptance Criteria
- [x] Landing placed as new page in drafts Confluence space
- [x] Landing meets quality standards and is ready to publish 
- [x] Platform site is set up

**Comment by steel36** [comment]
Our team didn't have sufficient permissions to move Draft to final Confluence space under Support.  Platform Content team will handle this.
