### ISSUE TITLE
Update All VA dashboard - Monthly Views Only & Medallia Data

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42178]
## Issue Description
We need to update the [All VA Dashboard](https://va-gov.domo.com/page/1030131175) to only allow views as granular as monthly and work with contact center team to update Medallia data upload (as applicable).  See [slack convo](https://dsva.slack.com/archives/C01S78V4AUA/p1654123843436199?thread_ts=1654117730.492569&cid=C01S78V4AUA) for reference.

---
## Tasks
- [ ] Build ETLS/separate views for All VA dashboard data where needed so by month is the most granular option avaialable
- [x] Add note to dashboard so users know they can only graph by month or higher
- [ ] Work with Contact Center on cadence for manual Medallia uploads for customer satisfaction data (can we assist or take over?) - update data accordingly.
- [ ] QA all data changes (can only view by month, all dates on titles are consistent, data is accurate)
- [ ] Release 

## Acceptance Criteria
- [ ] When all the above tasks are complete and we can publish/release the changes.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Updated both [All VA.gov Dashboard](https://va-gov.domo.com/page/1030131175) and [Monthly VA.gov Summary](https://va-gov.domo.com/page/1314425343) report with datasource that includes both ForeSee and Medallia monthly satisfaction ratings. Verified methodologies for each vendor with Ian from Contact Center team. Added annotations below cards on each graph explaining difference and how to read.

Closing ticket.
