### ISSUE TITLE
[Design] My VA Audit UX Improvements: Update Claims and Appeals Design

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42196]
## Background
Design updates for the Claims and Appeals section of My VA based on our audit feedback. 

## Tasks
- [x] Update design to remove 30 day conditional text
- [x] Add state for when a user has previously filed a claim but has no open claims currently
- [x] Add state for a user who has never filed a claim but is LOA3
- [x] Add state for when a user currently has open claims
- [x] Review with team

## Acceptance Criteria
- [x] Update design for Claims and Appeals section including removing the 30 day conditional text and adding new states as mentioned in the tasks above.

## Resources
- Notes from audit: We want to remove the "updates within the last 30 days" language. Show this section to all LOA3 users regardless of their claim and appeal status.

**Comment by aagosto90** [comment]
@ericasauv09 @ajakabcin 
Question on this because I'm a little confused by the acceptance criteria: Should this ticket be to create a design for the following use cases? Or just to remove the current 30 day logic? 

As a user who has never filed a pension or disability claim, I see
- Guidance text about claims and appeals 
- An action link to file a claim that navigates me to the claim status tool

As a user who has filed a claim before but currently has no open pension or disability claims, I see

- Text stating that I have no open claims
- Guidance/text on how to file a claim
- An action link to file a claim
- A link to “Manage all claims and appeals” that navigates me to the claim status tool

**Comment by ericasauv09** [comment]
@aagosto90 Sorry the AC was not clear on this one - I can update it but I believe we wanted to create tickets to update each section's designs so this ticket should encompass all design updates for the Claims and Appeals section. I think I added those tasks based on a few notes I had from our conversations but this ticket should be design updates for the whole section including 30 day logic and any use case updates.

**Comment by aagosto90** [comment]
Thanks for clarifying @ericasauv09! The change to the AC is perfect!

**Comment by ajakabcin** [comment]
Moving out to sprint 80 to accommodate payment info v2 research sessions
