### ISSUE TITLE
Analytics & Insights (Q3 2022):  GA4 - Configure Custom GTM Events 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42199]
## Problem Statement 
As part of the GA4 migration we need to configure required custom event tags in GTM and configure those custom tags in GA4 to track/report.

As part of the GA4 migration we need to work with VFS teams on their GTM requirements.

## Hypothesis or Bet
If we configure the required custom GTM tags in GA4 and configure (turn those on) in GA4 then we will best support the VFS teams with their GA4 migration and ensure tracking is reported consistently and accurately acrross teams.

## We will know we're done when... ("Definition of Done")
GTM tags have been configured and deployed to GA4.
[GA4 Planning Doc](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=0)

## Known Blockers/Dependencies 
VFS teams capacity to implement the GTM tag code.

## Projected Launch Date
Q3 2022

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by michelle-dooley** [comment]
Configuration and set up is complete.  Testing and validating will be completed in Q1'23.
