### ISSUE TITLE
Develop and document process for creating Experience maps

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#42195]
## Problem Statement
A main mission of the SDT is continued consideration of the user's journey in accessing and utilizing Platform offerings. We believe it to be highly beneficial to explore, review, and maintain these unique journeys in the form of blueprints/user journey maps. The practice of maintaining such living artifacts has not been pursued for some time.

We intend to research, establish, and document a process for creating end-to-end mappings of tasks, product experiences, and services offered across the Platform. 

Operative question:  How might we create an easy to follow, execute, and repeat process for creating mappings of services and experiences?

## Desired Outcome(s)
-any SDT member(s) can use the resultant process to map out an end-to-end experience of performing a VFS user task
-any SDT member(s) can use the resultant process to map out an end-to-end experience of using a Platform product
-pain points for a given process should be easy to identify visually on map
-Where a user engages and disengages from a mapped process is clear

PO's desired outcome: Want to use it to help us better understand internally How We Work, and also to communicate to others How We Work.

## High Level User Stories
As a platform team member, I want an accessible process so that I can map the journey for a user of my product/service

As a platform team member, I want an accessible process so that I can map the services involved for a user of a platform product/service.

As an SDT member, I want to have a specific, repeatable process documented so that I can generate consistent  Maps involving Platform offerings.

As Octo Leadership, I want consistent maps that will allow me to identify gaps, pain points, or overlaps in Platform offerings.

## Bet
By creating a defined process for creating maps, we can map processes consistently, efficiently, and comprehensively

## Definition of Done
- [x] A standardized process will be documented in the form of a Guide
- [x] A standard Template is ready for use
- [x] Location for guide is established for easy access and reference

### Documentation
PRODUCT_NAME: directory name used for your product documentation
Product Outline: link to Product Outline
User Guide: link to User Guide

Measurement
Success metrics: link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping
Release plan: link to Release Plan ticket

**Comment by annekerr49** [comment]
@steel36 Bryan we are trying to increase the information available to those persons who monitor this board. To that end we are asking that open items updated monthly as to any changes. For our interested colleagues. Please let me know if you have any questions.

**Comment by steel36** [comment]
As this is an Epic, the Issues that roll up within it are actually what get updated (within Zenhub).  The Epic itself gets updated once all of its Issues are completed.  Is there an additional type of update that it would be helpful to give?

**Comment by annekerr49** [comment]
@steel36 - Thank you Bryan  I will check into this and let you know.
