### ISSUE TITLE
[Design] My VA Audit UX Improvements: Healthcare Section Design Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42198]
## Background
Design updates for the Healthcare section of My VA based on our audit feedback

## Tasks
- [x] Update inline messaging style 
- [x] Remove "last 30 days" condition and text
- [x] Show state for when a user is enrolled in healthcare but does not have any upcoming appointments (text that indicates I have no upcoming appointments)
- [x] Add a state for a user who is not enrolled in healthcare with a CTA
- [x] Review with team

## Acceptance Criteria
- [x] New design for Healthcare section is complete

## Resources
- notes from audit: Update inline messaging style, simplify use cases. Remove “last 30 day” logic. Show this section to all LOA3 users regardless if they are enrolled or not.

**Comment by ajakabcin** [comment]
Moving out to sprint 80 to accommodate payment info v2 research sessions
