### ISSUE TITLE
Update guidance on preferred/recommended artifacts for Staging Review

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#42213]
## User Story
As a VFS team, I want to understand the preferred artifacts for Staging Review touchpoint so that I can provide relevant artifacts when requested.

As a Governance team, I want to be able to review relevant artifacts from the VFS team for Staging Review so that I can complete my review as quickly and efficiently as possible without follow up.

Assignee:
Peer Reviewer:

## Description
This ticket is to add clarification to the Staging Review touchpoint to ensure it is clear for VFS teams what artifacts are preferred and/or recommended. (Note: be careful about using the word "required").

At this time, this ticket will not include QA artifacts as there will be changes upcoming with regards to VFS expectations for QA.

Accessibility will also not be included in this ticket since we will be addressing a11y artifacts in another ticket (#47400)

See ticket #38067 for historical context of this ticket. 

## Impacted Artifacts
[Confluence: Kickoff Moderator Instructions - Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Platform Website: Staging Review Artifacts](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review#Artifacts)

## Tasks
Note: If the tasks don't make sense, escalate to Shira. 
- [ ] Request input from all practice areas on required and recommended artifacts
  - [ ] Design Response
  - [ ] IA Response
  - [ ] Content Response
  - [ ] A11y Response
- [ ] Update [Confluence: Kickoff Moderator Instructions - Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) to note preferred artifacts
- [ ] Update [Platform Website: Staging Review Artifacts](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review#Artifacts) guidance to align to Staging Review code block

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] Governance team is able to quickly identify preferred artifacts are linked
- [ ] VFS teams are able to identify preferred artifacts and supporting artifacts that may not be necessary

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
the recommended and required artifacts for Staging REview have been updated this year. This ticket is no longer necessary.
