### ISSUE TITLE
Translation work for new Post-9/11 GI Bill COVID-related info on FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42217]
## Issue Description
We made changes to the accordion "What happens to my GI Bill benefits if my school changes to online classes or temporarily closes?" on the [coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page around the rules changes as of June 2, 2022. This work was completed in ticket #41405.

We need to send this updated content to the translators and then input these on the Spanish and Tagalog pages. 

## Tasks
- [x] Send content to translation team (Randi)
- [x] Update Spanish page (Aliyah) 
- [x] Update Tagalog page (Aliyah)
- [x] Review Spanish page (Megan)
- [x] Review Tagalog page (Megan)
- [x] Publish Spanish page (Megan)
- [x] Publish Tagalog page (Megan)
- [ ] Send live links to volunteer translation team (Randi)

## Acceptance Criteria
- [x] New content is on live Spanish and Tagalog pages

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the Tagalog translation for these changes. They're still working on the Spanish one but you can get started on this one.

[https://app.zenhub.com/files/133843125/046c7130-c644-496c-bb59-183eae99aa9c/download](https://app.zenhub.com/files/133843125/046c7130-c644-496c-bb59-183eae99aa9c/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Tagalog page is ready for you to review! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16475#mga-pagbabayad-sa-benepisyo-pa

**One note:** 
The translation returned to us did not include "(Sa English)" after the link "Alamin kung paano magpasa ng kahilingang alisin ito." That was added in, as this is the link ending on the live Tagalog page and it does link to an English page/it seems to be  practice of noting that on translated pages.

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore!  @aliyahblackmore, I think the alert is showing up now, but @RLHecht, feel free to review and make sure I didn't mess anything up. Thanks! 

Tagalog is ready, but I'll stand by for Spanish. 

http://preview-prod.vfs.va.gov/preview?nodeId=16475#mga-pagbabayad-sa-benepisyo-pa

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the Spanish translation for you: [https://app.zenhub.com/files/133843125/d38ec569-098d-4375-a6ed-cee2586e7895/download](https://app.zenhub.com/files/133843125/d38ec569-098d-4375-a6ed-cee2586e7895/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Spanish page is now ready for you! 
Preview link:  https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/#pago-de-beneficios-reclamos-an

**One note:**
The translation returned to us did not include "(en inglés)" after the link "Más información sobre cómo enviar una solicitud de exención.." That was added in, as this is the link ending on the live Spanish page and it does link to an English page.

**Comment by megzehn** [comment]
Reviewed and  published. Thank you!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
