### ISSUE TITLE
[Bug] Fix U.S. addresses erroneously submitted with APO, DPO or FPO

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42216]
## Current behavior
The Pittsburgh Regional Office is currently receiving claims as part of our foreign workload for Veterans/claimants that reside within the United States, but have a(n) APO, DPO, or FPO erroneously listed as their city.

## Expected behavior
RO processing agents receive claim applications from VA.gov that accurately state the address as provided by the Claimant, without adding any erroneous data, such as a foreign address indicator like APO, DPO, or FPO, or anything else.

## Background context

[A Report from the Pittsburgh Regional Office](https://dsva.slack.com/archives/C5AGLBNRK/p1654182876865439) stated:
> Veterans/claimants that reside within the United States are having instances of an APO, DPO, 
or FPO erroneously assigned at the time they submit a claim. Pittsburgh Regional Office conducted a fairly thorough investigation of the issue on their side of the integration: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/assets/False%20Foreign%20White%20Paper_V3.docx

This issue is occurring in forms 21-526EZ, 21-686c, 21-674 (part of 686c), and 26-1880 (COE).

In form 526, when the "I live on a United States military base outside the United States" checkbox is checked:
- The Country select is disabled and set to "USA"
- The City text input is replaced by a select with Air/Army Post Office (APO), Fleet Post Office (FPO), and Diplomatic Post Office (DPO) choices
- And the State select options are replaced with Armed Forces Americas (AA), Armed Forces Europe (AE), and Armed Forces Pacific (AP) choices

**NOTE**: If choices are made, then the "I live on a United States military base outside the United States" is unchecked, the City will remain set to the APO, DPO or FPO value in the text input, and the State select will remain set as AA, AE or AP until the State is unselected and the City is changed

<details><summary>Address UX</summary>

![Clicking 'I live on a U S military base limits the city & state selection, after making selections, unchecking keeps the settings and limits what the user can type](https://user-images.githubusercontent.com/136959/171702229-9c4b5ed9-41a5-4b98-aa87-3cdbd7ce9a84.gif)</details>

## Tasks

- [ ] Discuss UX with specialist and make appropriate changes, e.g. should the Veteran be allowed to enter APO, FPO or DPO into the City without the checkbox being enabled?
- [ ] Implement fix to prevent submitting unintended address changes
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Work for 526 addresses has been completed.

**Comment by Mottie** [comment]
Ok that sounds good. I started working on an update form 686c-674 earlier today, and I'll hopefully have it done tomorrow sometime.

**Comment by saderagsdale** [comment]
Marking as a sev-1 due to executive visibility. @mattpointzxer0 Hey! For your awareness, this is in our current sprint.

**Comment by Mottie** [comment]
Work for 686C-674 merged. Checking COE is all that is left.

**Comment by Mottie** [comment]
Remove sev-1 tag as COE isn't in production

**Comment by Mottie** [comment]
Starting work on COE address changes

**Comment by saderagsdale** [comment]
Check with Matt if this issue is still occurring. Need ICN instead of SSN.

**Comment by michelpmcdonald** [comment]
Reached out to VA employee who provided 4 files numbers for claims with an improper address, asked if ICN could be provided instead.

**Comment by Mottie** [comment]
COE/platform address work is complete. As far as I know, this should fix the problem in all future filings, but it won't fix forms already in progress. So, I think we can close this issue @saderagsdale.

Additionally, I **did not audit** forms that use platform `profileAddress` definition, or copy the platform `profileAddress` definition, AND use the military base outside the U.S. checkbox.

No changes were made to the `address` definition (only the `profileAddress` was updated). This definition does not include a military base outside the U.S. checkbox, but does allow the Veteran to type in `APO` in the city input, which then limits the state selections to military states (AA, AE and AP).

**Comment by michelpmcdonald** [comment]
Got some info from Matt Self regarding 3 users who hit this issue on 3 686c and 1 674 claim(s) submitted on 07/25/2022.( 1 user had 2 claims)

The key question for these 4 claims is if they were started before the FE fix was merged in.
The in-progress-form(IPF) for each of these claims would have the form start date we are after, however, the in-progress-form table is not designed to hold the users historical IPF records, the idea is that IPFs represent the user current started but unsubmitted claim(s).  

When the user submits their IPF, we delete the IPF if the submission is successful and reflect the submitted claim in the saved_claims table.  However, the saved_claim table only has the form submission date, not the creation date, so on successful submission we lose the form start date when the submissions corresponding IPF record is deleted.

At this point, we are going to keep an ear out for more reports of this issue, especially for  claims submitted after 07/25/2022.

**Comment by saderagsdale** [comment]
Same here. @Mottie @michelpmcdonald Do we roll this into the next sprint or take a different action with this ticket?

**Comment by Mottie** [comment]
I vote we close it and reopen if the problem continues.

**Comment by saderagsdale** [comment]
@Mottie I'll let you do the honors lol.
