### ISSUE TITLE
Handle Users Who Aren't in MVI on Rated Disabilities

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#4222]
## Story
As a Veteran, I want to know why I don't have access to the rated disabilities page, so I can make an informed decision of whether or not to contact my nearest VA facility to try and gain the access needed to view my rated disabilities.

## Considerations
- Currently, rated disabilities does not handle scenarios where a user does not exist in MVI. This results in the page not being rendered:
![Screen Shot 2019-12-12 at 2.51.26 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/18a01978-a825-4d84-9944-9bd8531e957b)
- While two separate users can receive an identical 403 error, one who isn't in MVI will result in the blank page, while the other will get handled as expected, and display the proper error message. 
- Difference in user states:![Screen Shot 2019-12-12 at 2.54.11 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/014fc295-ffce-438f-98dc-b41638b7540a)
![Screen Shot 2019-12-12 at 2.54.35 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/daaf94a6-4c39-40ec-abd3-d021fe8213b9)
- Both the Account and Profile pages have ways of handling this scenario:
![Screen Shot 2019-12-12 at 2.10.16 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/d4784140-a5d6-462b-a2c7-8adb053a51b6)
![Screen Shot 2019-12-12 at 2.10.39 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/c913e44a-2f74-4d1f-acba-cf603f8520e8)
- Existing solutions in code are [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/account/components/AccountMain.jsx#L22) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/profile360/components/ProfileView.jsx#L150)

## Tasks
- [ ] Add MVI error handling to rated disabilities so the user is presented with guidance on how to proceed in the event the page is inaccessible to them.

## Acceptance Criteria
- [ ] A PR for this change has been submitted.
- [ ] Test with afflicted account

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11355
