### ISSUE TITLE
Questions for Lighthouse related to upstream data services

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#42225]
## Value Statement
**_As a_** product manager
**_I want to_** generate a list of questions for Lighthouse related to upstream data services and have them answer those questions to help us understand details related to those services
**_So that_** we can better assess and identity opportunities to deliver more useful claims status information and associated action items to veterans checking their claims status.

---
## Background Context
We have heard it mentioned by VA stakeholder, other team members, and read in historical artifacts, that the statuses in the claims status tool could be more specific, but the current data schema doesn't allow for it. We've also heard there is at least one upstream service that actually has relevant information related to claims status that is specific, but we haven't leveraged it. We need to check our assumptions:

- There is an upstream service with claims status data more specific than that currently being used
- Theoretically, Lighthouse could pull that data and create new end points CST can use

## Acceptance Criteria
- [x] _List of questions generated relevant to understanding the problem and opportunity space added to this ticket_
- [x] _All questions answered with the appropriate level of detail_
- [x] _Follow up activities identifid_

## Out of scope
- Only focused on CST

## Questions for Lighthouse

https://docs.google.com/document/d/1PiqkhlKE5jdpaHmoQ7glQS85IBlt0A_RgorSu5t6228/edit

## Tasks
- [x] _Michel generates list of questions_
- [x] _Jacob reviews_
- [x] _Jacob sends to Lighthouse_
- [ ] _Lighthouse responds to questions_
- [ ] _Jacob determines whether follow up conversation is needed_

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
