### ISSUE TITLE
Lighthouse discovery call

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#42226]
## Value Statement
**_As a_** product manager
**_I want to_** have a discovery call (or communicate asynchronously) to get questions related to upstream data services
**_So that_** I can understand opportunities for providing veterans more detailed and useful claims status information. 

---
## Background Context
Michel is generating a list of open questions for Lighthouse.

## Tasks
- [ ] _Michel creates open questions_
- [ ] _Jacob sends Lighthouse open questions to review, assesses need to have a call based on response_
- [ ] _Jacob schedules call_
- [ ] _Michel and Jacob attend call, capture relevant data_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
