### ISSUE TITLE
[Lighthouse team] Investigate if services are currently in use

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#42229]
## Value Statement
**_As the_** Lighthouse product team
**_we want to_** understand if and how several services are being used by others
**_So that_** we can decide upon the best approach to action on those services.

---
## Background Context
- Dana Harris and Premal Shah reached out to Matt Self and Sade Ragsdale on 6/2 with questions about education, PCIU, and rated disabilities services. They need support tracking down answers to the questions below. 

## Open questions
- Education: Does it need to be migrated? Yes
- PCIU: Is anyone at VA.gov using this service actively? Can we put logging in to confirm if anyone is using it? (we think it is a backup to get Veteran info  if they can't find it in VA Profile/Vet360)
- Rated disabilities: Can people current using this switch over to use VA Profile service?

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@mattpointzxer0 Tagging you in the ticket I created.

**Comment by Mottie** [comment]
I feel like I've mentioned this to the Lighthouse team before, but a list of [PCIU Countries and States are included in the vets-json-schema addresses](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/address.js#L2994-L2995). It's not using the service, but maybe it should?

**Comment by saderagsdale** [comment]
@Mottie added some notes from the meeting. Do you think it's possible to get an update to Lighthouse by next Thursday?

**Comment by Mottie** [comment]
An update on all services? Or just what I mentioned here about PCIU?

**Comment by saderagsdale** [comment]
@Mottie on the three services noted above.

**Comment by Mottie** [comment]
I can work with @michelpmcdonald on this if needed. It should be possible to get done before our sync next week, but Michel  may end up doing most of this work.

**Comment by saderagsdale** [comment]
@jacobworrell Flagging this request for squad 1, as it seems that Michel has already been working on it and Matt, Premal, and Dana would like to get an update by next week's Lighthouse sync.

**Comment by saderagsdale** [comment]
@Mottie No action required just yet. I'll work with Jacob on it.

**Comment by jacobworrell** [comment]
OK, we'll put this into our sprint and prioritize @saderagsdale

**Comment by jacobworrell** [comment]
@Mottie There's a lot of info in this ticket, can we be specific about which questions for which Michel needs to track down answers? Is it literally everything in "Open Questions"?

**Comment by jacobworrell** [comment]
@Mottie I understood which Michel you were referring to, just wasn't sure if he had previous context for this work or not.

**Comment by saderagsdale** [comment]
@jacobworrell To answer your question, yes. They would like updates on the items in the "open questions" section.

**Comment by jacobworrell** [comment]
@michelpmcdonald would have to answer that. We had to deprioritize a lot from the previous sprint to account for new requests @saderagsdale .

**Comment by jacobworrell** [comment]
@michelpmcdonald @saderagsdale don't want to leave this blocked indefinitely. Are there next steps for squad 1 here?

**Comment by saderagsdale** [comment]
@jacobworrell I left all the context I had in the Background Context Section. Dana and Premal can explain more.
