### ISSUE TITLE
[FE] Refactor / fix PreCheckinConfirmation test suite

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#42258]
See: https://github.com/department-of-veterans-affairs/vets-website/pull/21242

As of this PR the tests in this file are now being skipped as they do not pass. The goal of this ticket is to have these tests run and pass.

## Tasks
- [ ] update unit tests

## Acceptance Criteria
- [ ] All tests in the PreCheckinConfirmation suite run and pass
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging

- [ ] Prod validation:
  - [x] not necessary
  - [ ] scheduled
