### ISSUE TITLE
Documents that might have to be modified after the Datadog integration is complete.

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#42259]
## Description
The confluence documents listed contain service metrics and Datadog information that might have to be modified after the Datadog integration is complete.

## Tasks
- [ ] [External Services Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations)

## Acceptance Criteria
- [ ] Document is reviewed for correctness
- [ ] Document is updated as necessary
