### ISSUE TITLE
[Infrastructure Request] Access to self-hosted runners for Access Management Team

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#42261]
## Who is the devops resource on your team?
Carl Alquisola (@calquisola ) and Ritesh Patel (@iriteshp )

## Description
AMT needs to use GitHub runners with VA network access. 

## Background/context 
Our Keycloak instances are already running in both dev and utility clusters. 

As part of our automation initiative, we'll be using [this](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs) terraform module.  This module is just a wrapper around a Keycloak HTTP client, so we need to be able to access our Keycloak's rest API. 

## Technical notes
There's a slack thread for [this](https://dsva.slack.com/archives/CJYRZK2HH/p1654187190658819). 

---
## Tasks
- [x] Provide access to self-hosted runners for the Access Management team (AMT) 
- [x] Give AMT's service account access to the shared state file. Related AWS [request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42260). 

## Acceptance Criteria 
- [ ] Able to access our Keycloak rest API with our GitHub actions. 
- [ ] Able to save state in AWS S3

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by calquisola** [comment]
Hi team! We just want to follow up with request. Please let us know if you need additional info. Thank you.

**Comment by jhouse-solvd** [comment]
@calquisola - We'll take a look at this and reach out to clarify requirements as needed. Once the team has had a chance to discuss, we'll schedule for an upcoming sprint and provide an ETA.

**Comment by calquisola** [comment]
Hi @jhouse-solvd,

Any update on our request? Thanks you.

**Comment by calquisola** [comment]
Hi @jhouse-solvd,

Thank for you response. 

We want the ability to use self hosted runners. 

Our terraform files are in the devops [repo.](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/applications/keycloak) 

Best,
Carl

**Comment by rmtolmach** [comment]
@calquisola Where is your GitHub Action going to run? I know you said your terraform code is in the devops repo, but would the workflow be there or in another repo like https://github.com/department-of-veterans-affairs/pst-amt-keycloak?

**Comment by iriteshp** [comment]
@rmtolmach GitHub Action will run on devops repo. We have a workflow for the Keycloak [here](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/keycloak-terraform.yml)

**Comment by calquisola** [comment]
hi @rmtolmach,

Thank you very much! We've a [ticket](https://app.zenhub.com/workspaces/access-management---platform-spike-team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/44693)  for testing self hosted runners. We'll be doing it on our current sprint. 

We'll let you know. 

Best,
Carl

**Comment by iriteshp** [comment]
@rmtolmach the runners seem to be working but I am getting [‘node’: No such file or directory](https://github.com/department-of-veterans-affairs/devops/runs/7456658551?check_suite_focus=true#step:15:18) error. I tried to config the node in the workflow referencing [this](https://github.com/hashicorp/setup-terraform/issues/84) solution but no luck. is there anything I need to be aware of directories? 

also, other popular solution is `ln -s /usr/bin/nodejs /usr/local/bin/node`, is it ok to try this?

thanks!

**Comment by rmtolmach** [comment]
@iriteshp I was looking at some other examples in the devops repo and the path is specified differently (with the leading `./`) like here:
```
        working-directory: ./terraform/environments/dsva-vagov-prod
```
Could that be the issue?

**Comment by iriteshp** [comment]
Unfortunately, that did not work. is it a Linux machine where workflow runs?

**Comment by rmtolmach** [comment]
Yes, it's Linux. 

I will keep investigating as well.

**Comment by rmtolmach** [comment]
@iriteshp A few things to try, if you haven't already. 
This is your tf setup block:
```
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2
```
1. Move that block down, so it's executed right before the terraform commands
2. Change the terraform version. We use `0.13.7`.

I noticed you're using a Makefile.
```
      - name: terraform fmt
        id: fmt-staging
        if: env.KC_ENV == 'staging'
        working-directory: ./terraform/applications/keycloak
        continue-on-error: true
        run: make ENV=staging fmt-check
```
3. Just to rule out any weirdness, try using the tf commands directly. ` run: terraform fmt -check`
4. Try putting the `run` command above the `working-directory` command. I don't think that should matter, but worth a try??

(I'm comparing your action workflow to [terraform.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/terraform.yml#L76-L85))

**Comment by iriteshp** [comment]
@rmtolmach will try these out, thanks!

**Comment by rmtolmach** [comment]
@iriteshp Do you need the node.js environment? Wondering if that action could be the cause. Found this issue in `setup-node`: https://github.com/actions/setup-node/issues/224. You could at least remove it and see if the terraform commands complete.

Like I mentioned in Slack, you can test changes without merging PRs. On your branch, comment out everything in the `on` section at the top and replace it with `on: [push]`. Any time you push to your branch, the workflow will run.

**Comment by iriteshp** [comment]
@rmtolmach I checked the issue related to node and already added it to the workflow but no luck with that either. let me debug now on the branch. it will be faster to test quick things.

**Comment by iriteshp** [comment]
@rmtolmach Actually, I take that back. downgrading the node to v1 did the trick. Thanks for all your help. Closing this issue.

**Comment by rmtolmach** [comment]
Yay! 👏 👏

**Comment by jhouse-solvd** [comment]
@iriteshp - Even though this is closed, would you please click off the Acceptance Criteria if they met your need? Thank you in advance. And let us know if there is anything else needed. :)
