### ISSUE TITLE
Finalize Medallia (S3 Bucket) Data Automation

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#42267]
## Issue Description
_To be able to update our Medallia DOMO dashboard more frequently, we need to automate the ETL process as much as possible. Our most optimal path right now is by utilizing and S3 bucket whereby Medallia data is dumped on a regular bases. We will extract the data from there and utilize an connector in DOMO to automate the load._

---
## Tasks
- [x] _Confirm regular, frequent data dumps in S3 bucket_
- [x] _Access S3 bucket using GFE_
- [x] _Setup ETL from S3 bucket using DOMO connector_
- [x] _Verify data is loading and updates the Medallia dashboard as expected_

## Acceptance Criteria
- [x] _Data from the S3 bucket is loading and updates the Medallia dashboard as expected for frequency and accuracy_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
