### ISSUE TITLE
[FE] | Profile: Direct Deposit | Deploy to 25% of users on 6/6/22

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42270]
## Background
Displaying Direct Deposit consistently has been deployed to Staging behind flags and internal tested. On Monday we want to modify the flag to deploy to 25% of users so that the changes are visible in Production.

## Tasks

- [x] Update feature flags to make Direct Deposit consistent display visible in Production for 25% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [x] Feature flags updated to make DD changes visible in Production for 25% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO
