### ISSUE TITLE
CST: Update upload form elements to use web-components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42283]
## Value Statement

_As a_ frontend developer
_I want to_ switch to use web-components
_So that_ I know the application is using the newest standards

## Background

The Design System Team is continually adding web-components to replace React components. Within the Claim Status Tool (CST), the file upload page is using `TextInput` and `Select` React components which need to be updated to use `va-text-input` and `va-select` web components. The changes will be applied in the `AddFilesForm` component (`src/applications/claims-status/components/AddFilesForm.jsx`)

## Tasks

- [ ] Replace `TextInput` with `va-text-input`
- [ ] Replace `Select` with `va-select`
- [ ] Replace `Modal` with `va-modal`
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by jerekshoe** [comment]
We need to wait for `component-library` version 10.6.2 to be used in package.json. It's currently on 10.6.0.
https://github.com/department-of-veterans-affairs/vets-website/blob/main/package.json#L264
