### ISSUE TITLE
Set up feature toggle for A/B test on Green Action Link

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#42292]
# Background
After discussing the idea of moving from green "start" buttons on the intro pages of our forms to green "action links" from the experimental design system it was decided we should run an A/B test to see how the change affects user behavior. The primary metric we will be tracking is clicks on the button or link as well as a secondary metric of time on page. We are looking for no drop in clicks as well as a similar time on page as either one of these would mean that the user might be having issues finding the green action link. 

The reason we need a feature toggle is so that we can write the code for the green action link without it showing up in production. This feature toggle will need to be disabled for all users until the A/B test is launched.

For reference [here is the link to the documentation for setting up a feature toggle](https://depo-platform-documentation.scrollhelp.site/developer-docs/Feature-toggles.1859780873.html).

## Tasks
- [ ] Set up a feature toggle with the name `green_action_link_ab_test`
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] A feature toggle has been set up for the A/B test
