### ISSUE TITLE
[bug] Higher-Level Review | Vets API HLR Contestable Issue Endpoint returns 404

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#42300]
## Value Statement
**_As a_** system
**_I want to_** display accurate system errors to Veterans 
**_So that_** Veterans aren't misled or confused about the cause of the error. 

---
## Background Context
The vets-api /v0/higher_level_reviews/contestable_issues/compensation endpoint returns a 404 for vets who do not have any Contestable Issues. We don't think 404 is appropriate in this case. Approximately 1,400 out of 13,000 users are experiencing this issue. 

404, i think, means the endpoint is not available, for example vets-api is down and just returns 404 for every request.

So a 404 should indicate the call is unable to be made, and the vets contestable_issues are unknown....could have 0...could have 3000, but we don't know because the fetch itself failed.

In the case where we were able to check, but the vets simply does not have any issue, we should return a 200 and an empty result set.

We are seeing this issue with user on staging using Mark Webb (228).

I have not determined if the 404 vets-api is returning is originating from vets-api itself, or if it's coming from the underlying endpoint that vets-api calls.  If the 404 is coming from the underlying service, might have to contact them and discuss if their 404 means their service was down or if it means the vet does not have any contestable_issues to return.  If it the later, see if they will fix.

## Acceptance Criteria
- [ ] A 404 should indicate the call cannot be made, and the vets contestable_issues are unknown.
- [ ] In the case where we were able to check, but the Veteran does not have any issue, we should return a 200 and an empty result set._

## Tasks
- [ ] @michelpmcdonald to look at LH code to see what it's returning when there are no contestable issues, and to see if the source of the 404 is from LH or Vets API.
- [ ] Look into GA to determine how many users are impacted.
- [ ] Determine where the 404 is coming from.

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [ ] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Next steps:
- @michelpmcdonald to look at LH code to see what it's returning when there are no contestable issues, and to see if the source of the 404 is from LH or Vets API.

**Comment by saderagsdale** [comment]
I added user count (1400) and severity label (sev-1). @rocio-desantiago

**Comment by saderagsdale** [comment]
@Mottie @rocio-desantiago did we determine where the error was coming from?

**Comment by Mottie** [comment]
We still don't know.

**Comment by saderagsdale** [comment]
@Mottie can you add next steps to this ticket? Want to make sure its on a pathway to getting resolved/closed.

**Comment by Mottie** [comment]
For next steps, we could either close this as complete (the frontend is now ignoring the error), or update the backend to pass a successful message with an empty array value - meaning no contestable issues. Ultimately, I think the fix would need to be made by Lighthouse. Our changes on the frontend & backend are merely work arounds.

**Comment by Mottie** [comment]
Closing, as I think Lighthouse will need to address this problem.
