### ISSUE TITLE
configuration profiles for web and mobile

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#42310]
## Description
The SiS configs for each of its three client types: `web`, `mobile`, & `mobile_test` are managed through a series of constants in `app/services/sign_in/constants/client_config.rb`. These should be refactored into config hashes for better clarity and differentiation between client types.

## Tasks
- [x] Refactor the constants in `app/services/sign_in/constants/client_config.rb` into configuration hashes for each of the three client ids. Hashes will have the following attributes:
  * cookie_auth
  * anti_csrf
  * redirect_uri (point to settings.yml path)
  * access_token_duration
  * access_token audience
  * refresh_token_duration
- [x] Update the usage of these configs in the following files:
  - [x]   - LoginRedirectUrlGenerator - case statement for URIs to config object
  - [x]   - access_token - validity_length
  - [x]   - access_token_jwt_encoder - access token audience
  - [x]   - token_serializer - cookie_auth, anti_csrf
  - [x]   - session_creator - refresh token validity_length
  - [x]   - session_refresher - refresh token validity_length, anti_csrf
  - [x]   - session_revoker - anti_csrf
- [x] update affected unit specs
