### ISSUE TITLE
[Design] Payment Info: Investigate Historical Debt Design Options

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42329]
## Background
During the audit we found that it may be useful to show a link for users to view their historical debt. However, we are not sure if it is possible to show historical debt or what a link to historical debt should look like within My VA. We need to investigate the possibility of including historical debt and what that would look like. 

## Tasks
- [x] Research if it is possible to show historical debt
- [ ] If so, determine how to show historical debt on MyVA

## Acceptance Criteria
- [ ] Options for showing historical debt, or not, are determined

**Comment by aagosto90** [comment]
[Discussion Slack thread w/ benefits 2 team](https://dsva.slack.com/archives/CPE4AJ6Q0/p1666282723576959)

[UXPin mockup of debt letters](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149089100/simulate/sitemap?mode=i)

**Comment by ajakabcin** [comment]
Thanks for doing the investigative work on this @aagosto90 ! Going to call this ticket complete and create a separate ticket in the backlog for design "historical debt" in the future.
