### ISSUE TITLE
[Design] 10-10CG - Submission page messaging update

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42322]
## Background
- Update messaging for when the 10-10CG is submitted, regardless of whether it's queued or submitted immediately.
- Per the conversation held with CG stakeholders on 7/5, the decision was to display a single message on the submission page (after submitting) to convey that the application has been submitted.  
- Add a Download link/button for the applicant to download a copy of the application _and_ confirmation page

<details>

<Summary>Screenshot of current messaging in production</Summary>

![image](https://user-images.githubusercontent.com/92328831/178040665-f506a5ce-6527-4bec-b47a-79eec5db591d.png)

</details>

<details><Summary>Content/components updates</summary>

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/be75a4e5-d30c-4138-8352-ff40910aa596)

</details>

**See comments below from 7/5/22 and 7/8/22**

## Tasks
- [ ] Review current messaging & proposal from CG team (screenshot in comments) and work on an updated message that will be displayed to all applicants, regardless of the behind-the-scenes technology processing
- [ ] Present proposed messaging to PO and team
- [ ] Upon approval from PO, present to CG stakeholders

## Acceptance Criteria
- An updated message on the post-submission page is displayed to all applicants

**Comment by markfallows** [comment]
Updated messaging for when the 10-10CG is submitted, regardless of whether it's queued or submitted immediately.

**Comment by hdjustice** [comment]
@nicko-amida - added you to this ticket in regards to the recent conversation with CG team and their desire to have the submission page content updated.  Slack info from Patrick below:

<details>

<Summary>Slack info from Patrick</Summary>

**Patrick Bateman**
i think we all agreed that differential messaging based on whether the submission is in CARMA, mulesoft, or vets-api doesn't make sense. so users who don't encounter a 5xx from vets-api (which would only happen under really bad circumstances) will receive the same message, no matter what happens downstream. so something like, "you submission is pending".

and then we stop with all of the complexity around trying to get mulesoft to communicate back through vets-api to front end.

so basically what is happening now, but more simple. that is the hope at least.

we will have to at least propose some notional language change to the confirmation page. not that it is going to make any difference to the user, but i can sense that the salesforce ppl need to feel like all of this work amounted to something, and the CSP people need to feel like they are being heard about the scrutiny on the program

so paging 
@Nick O
 for some help with that. my first suggestion would be to see if there are other patterns for confirmation language on other VA.gov forms beyond "You’ve successfully submitted your application"

[Slide presentation from Patrick](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Meeting%20Notes/1010cg-submission-options.pptx)

</details>

**Comment by nicko-amida** [comment]
Messaging from 7/8 VA touchbase: ![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/dd2c7064-00c8-4035-9a27-3be560c19a3d)

**Comment by markfallows** [comment]
Content looks mostly good.  May need a little massaging / editing to make sure it fully fits in.

Next step is to start working on a mockup of the page with the new information.

Implementation of downloading application and/or submission page may be done at a separate time.

**Comment by nicko-amida** [comment]
@hdjustice Here's an [updated submission confirmation page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/rbv4gDx). The content suggestions have been included across a couple different components - see the included screenshot above for my updates.

**Comment by hdjustice** [comment]
@nicko-amida - I think this looks awesome!  I did a bit of digging around VA.gov for other forms and their submission pages.  I only got through 3 of them (Education benefit, Disability claim, and Pension benefit).  Two of them have "Print this page" kind of button, but no "Download PDF" option.  The Pension one does not have a print button at all.
I think we might be the first on VA.gov to provide both options, if we can manage it technically!  

One thing, can you update that last lil paragraph at the bottom to say "support" instead of "supports"?  I think that will haunt us forever!

**Comment by nicko-amida** [comment]
@hdjustice Updated! Also, the 10-10CG submission failure alert has a "download" link on it - I'm assuming that already in production, but I wasn't sure. This pattern is in the VA design system, but I'm not sure where else it's used either, if anywhere.
<details><summary>10-10CG submission failure alert</summary>

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/48613c6f-cd40-4aff-b729-3120ec08fd3e)

</details>

**Comment by hdjustice** [comment]
That's right.. so it shouldn't be a problem.. I remember that convo now.  I was just wondering if anyone else had it in their submission pages.  Thanks so much!
