### ISSUE TITLE
[SRE / Infra] Dedicated channel for escalation of platform support issues

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42337]
## Description
To better support the escalation and handoff of platform support issues from the SRE team to the Platform Infrastructure team, it might be useful to have a dedicated Slack channel for this purpose. The SRE team would raise the issue in the channel and the Platform Infrastructure on-call personnel would acknowledge and respond to that issue. 

The recommendation is that we try this for a Sprint or two and measure success based on SRE and Platform Infrastructure team feedback. 

## Background/context 
- See also: [2022-03-03 Proposal for tiered support model (WIP)
](https://vfs.atlassian.net/wiki/spaces/OT/pages/2108588306/2022-03-03+Proposal+for+tiered+support+model+WIP)
- During day-to-day support, the SRE team needs to be able to escalate to the Platform Infrastructure team
- The Platform Infrastructure team has dedicated on-call personnel that can best respond to escalations from SRE 
- Escalations should be responded to in a timely fashion 
- Escalations should be tracked 
- Escalations can be noisy for personnel that are not on-call 

---
## Tasks
- [x] Create a new, temporary channel in Slack like -temp-platform-support-tier2
- [x] Document expectations / guidance ([link](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233499710/Tiered+support+model+Escalation+guidance))
- [x] Measure the number of escalations during the next 2-week sprint 
- [x] Collect feedback from SRE and Platform Infrastructure personnel
- [x] _Identify opportunities for next iteration_

## Acceptance Criteria 
- [x] The SRE and Platform Infrastructure teams have agreed to try this iteration together 
- [x] A Slack channel (-temp-platform-support-tier2) has been created and the SRE and Platform Infrastructure teams are using that channel for Tier 2 support escalations 
- [x] Guidance and expectations around Tier 2 support escalations have been documented in Confluence  ([link](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233499710/Tiered+support+model+Escalation+guidance))
- [x] Feedback has been collected from the SRE and Platform Infrastructure teams 
- [x] Metrics have been captured and shared 
- [x] New issues have been created to capture improvements and ideas for the next iteration

**Comment by oseasmoran73** [comment]
I am all for trying to iterate on this and iterate (or abandoned based off feedback from retro)

Somethings additional thoughts:
- We can have description be of the infra supporting SRE via description. This would be to avoid pinging someone whose rotation has ended (similarly how it is in support channel) 
![image](https://user-images.githubusercontent.com/10648480/171942527-c18f65af-0060-4939-a448-956b085350e1.png) 
- Infra members have the option to leave channel if they are on not on-call to avoid noise 
- If infra needs to pull in additional resources, in my opinion should be asked in internal channel. The on-call person should still be the point of contact

Lets give this a shot 😃 

Thoughts @jhouse-solvd ?

**Comment by jhouse-solvd** [comment]
We can request that the Platform Infrastructure on-call personnel respond within 24 hours to support issues that are escalated in that channel. 

Note: Response does not mean resolution.

**Comment by jhouse-solvd** [comment]
@zachclarity - Can you discuss this w/ the SRE team to get their feedback?

**Comment by jhouse-solvd** [comment]
Metrics to capture: 

- How many issues were escalated? 
- Did the SRE team prefer the new process over the existing one? 
- Did the Platform Infra team prefer the new process over the existing one? 
- How many escalated issues were completed? 
- How many times did completion result in a new GH issue? 
- How many issues referred to existing documentation? 
- How many issues suggest that better documentation is needed?

**Comment by zachclarity** [comment]
@jhouse-solvd  what is the new channel on-call infrastructure ?

**Comment by jhouse-solvd** [comment]
Here's what's needed to kick this off: 

- document guidelines and expectations 
- provide new channel: -temp-platform-support-tier2
- huddle monday w/ gino and infra on-call personnel 
- discuss how to measure success

Develop an escalation template that answers the following: 

- level of urgency 
- requester info (person and team 
- what service does this relate to?  
- what troubleshooting steps have been taken?

**Comment by jhouse-solvd** [comment]
@oseasmoran73 as a first iteration, is there anything else you'd want to see on the "escalation template" (see comment above)

**Comment by oseasmoran73** [comment]
The one snippet that comes to mind is "Once the ticket/request has been resolved, update documentation immediately to future knowledge base"

I know it on a case-by-case basis, but perhaps SRE can take point and Infra can fill as needed. I suggest SRE take point so they can write how they feel best and ask follow up questions afterwards.

Thoughts?

**Comment by jhouse-solvd** [comment]
Let's list out all of the preferred request forms (GitHub issue templates).

**Comment by jhouse-solvd** [comment]
@zachclarity @gperlangeli @jbritt1 - Let's drop feedback related to this process in this issue as we go.

**Comment by jhouse-solvd** [comment]
Some thoughts/questions coming from a conversation w/ @zachclarity: 

- What do we better identify urgency? 
  - How many users are impacted by this issue? 
  - Does this issue impact production now or soon?
  - Will this issue impact a production deployment happening today? 
- How do we clarify requests before they are escalated so that it can be understood by Tier 2 support? 
  - Is this happening in a specific environment?
  - Is this a new feature or does it affect existing functionality? 
- When should #vfs-platform-support issues become GitHub issues? 
  - Anything over ~30 minutes should become a GitHub issue
 - What's our routine for identifying common issues? 
   - Are there gaps in documentation for end-users? 
   - Are there gaps in documentation for SRE engineers? 
   - Does SRE need access to add'l permissions or tools for troubleshooting?

**Comment by jhouse-solvd** [comment]
Follow-up task: 

It may be helpful for the Platform Infrastructure team to get a consolidated list of escalations that happen on a weekly basis  
_(jesse to create a task for this)_ 

And, for the Platform Infrastructure team to analyze those escalations to identify...
- did it need to be escalated? if no, why? 
  - insufficient documentation 
  - insufficient tooling or access 
  - wrong team

From there, we could say "oh look, 25 issues came up about AWS that had insufficient docs and tooling"... let's focus on improving those next week/month/quarter.

**Comment by zachclarity** [comment]
I will add details to the [Document with list of key items that should not be escalated](https://vfs.atlassian.net/wiki/spaces/SRE/pages/2273706783/Operations+Escalation+Process+and+Review+June+2022) and may require access and training.

**Comment by jhouse-solvd** [comment]
Please see ["2022-07-27 Feedback: Dedicated channel for escalation of platform support issues"](https://vfs.atlassian.net/wiki/spaces/OT/pages/2291892307/2022-07-27+Feedback+Dedicated+channel+for+escalation+of+platform+support+issues) for a summary of feedback provide by Platform Infrastructure and SRE team members who have recently participated in this process.

**Comment by jhouse-solvd** [comment]
Please see #44976 for next steps

**Comment by jhouse-solvd** [comment]
Closing this issue.
