### ISSUE TITLE
[Design] | Profile | BAI | Address Validation and Mock-up Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42335]
## Background

Address validation mock-ups document.

## Tasks
- [x] Update the address validation mocks with final UI

## Acceptance Criteria
- [ ] Review with PO and PM
- [x] Add to Sketch section for Contact Information
- [x] Add to product guide

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Mockups are done for this ([Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/rbJ5V77) & [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/4a3Wp3q) Sketch files), along with [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/address-validation/designs/2022-current-alerts) clarifying the situation with the current designs on staging/prod and the new designs that have not yet been implemented. This doc also points to our related documentation for other overlapping features.

**Comment by cgednalske** [comment]
@SKasimow is this ok to close?

**Comment by SKasimow** [comment]
Yup - looks good.
