### ISSUE TITLE
Changing life insurance reference on 2 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42339]
## Issue Description
Stakeholder Steve Fital reached out to ask us to make changes on the [Change your address in your VA.gov profile](https://www.va.gov/change-address/) and [Change your address on file with VA](https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact) pages.

On the first page, he said we need to change the VMLI bulleted item to read: All VA insurance programs, except SGLI, VGLI, and FSGLI”
![Screen Shot 2022-06-03 at 3.52.02 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c336d4c4-268a-4e89-a736-4a1ae71ea927)

On the second page, we need to change the VMLI H3 to read: All VA insurance programs, except SGLI, VGLI, and FSGLI and remove (VMLI) next to the PO Box in the address.

![Screen Shot 2022-06-03 at 3.53.25 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ecb17c89-2d31-4978-ae59-5039ecff68dc)

We need to rework his changes since if we spelled out all the life insurance programs he mentions the bulleted item would be too long. We should consider if we need to make a separate bulleted list underneath for the life insurance programs. 

We will also need to rework the H3 on the second page so it's not too long with the mentions of each of those programs. 

## Tasks
- [x] Rework bulleted list on Change your address in your VA.gov profile (Katherine)
- [x] Rework the H3 on Change your address on file with VA.gov (Katherine)
- [x] Review edits (Laura)
- [x] Copyedit (Megan)
- [x] OCTO-DE review (Beth)
- [x] Send to stakeholder (Randi/Laura)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Changes to both pages are live on the site

**Comment by katherine-fung** [comment]
@RLHecht Can we ask the stakeholder which life insurance programs people would need to contact directly? I'm wondering if it would be better or possible to name the programs in the affirmative (instead of saying "except"), in a bulleted list. 

From what I can tell, the programs would be TSGLI, S-DVI, VMLI and maybe the 4 named here? https://www.benefits.va.gov/insurance/select.asp

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I made a few tweaks to both pages. Take a look and see what you think!
- I removed VALife for the moment, because that program doesn't go live until Jan 1, 2023. @RLHecht , are we tracking on future VALife updates anywhere? We'll need to add VALife to these lists when it's live.
- If I'm understanding Steve's response correctly, TSGLI is lumped in with the "except" programs that get updated with VA.gov profile changes. But @RLHecht , when we send these updates to Steve for approval, could you ask him to confirm that TSGLI, SGLI, VGLI, and FSGLI all update automatically when a user updates their VA.gov profile?
- I went back and forth about including a bold "**Note:** Other VA life insurance programs update your address automatically when you change it in your VA.gov profile." Or something along those lines. You can try adding that if you think it will be more clear. 

If this looks good to you, you can pass both pages along to Megan for copyedit, and then on to Beth for review. Thanks!

**Comment by katherine-fung** [comment]
@megzehn - here are the 2 pages for copyedit: 

[http://preview-prod.vfs.va.gov/preview?nodeId=709]

[http://preview-prod.vfs.va.gov/preview?nodeId=8473]

Thanks, Laura! I left the note about the other VA life insurance programs out. I might take another look at it pending Steve's answer to the question above.

**Comment by megzehn** [comment]
Thanks, @katherine-fung. These 2 pages are copyedited. 

@bethpottsVADEPO, could you review these before they go back to the stakeholder? 

Thank you!

**Comment by bethpottsVADEPO** [comment]
@katherine-fung @RLHecht @megzehn @laurwill 
[http://preview-prod.vfs.va.gov/preview?nodeId=709]
I went back and forth on this, whether to make the H4 an H3 instead, but I left it as is since your logic is sound--that it's a subset of "VA benefits and services." I did edit the H4 to shorten and called out that it was only some life insurance programs with the word "certain." I didn't think we needed to repeat "contact the department directly" because this life ins list was nested. 

[http://preview-prod.vfs.va.gov/preview?nodeId=8473]
Just added "Certain" to the life ins header.

Unless you all have any concerns (always raise them if you do!), we can move forward with this, and it'll be an interesting one to discuss in our next Thursday meeting.

**Comment by laurwill** [comment]
Thanks @bethpottsVADEPO ! 
I think the shorter header and "certain" work great. I've sent this off to Steve for review.

**Comment by bethpottsVADEPO** [comment]
@laurwill, if I'm understanding his last note, you could rearrange the content like this (want to put it in drupal and see how it looks? you might want to place life insurance last after Foreign Medical Program since the Life Ins subsection will be so long...):

**Life insurance benefits** (cut out "certain")

**If you have life insurance through Servicemembers Group Life Insurance (SGLI) or Family SGLI (FSGLI),** you'll need to update your information on milConnect. 
[Update your SGLI or FSGLI information on milConnect]

**If you have Veterans Group Life Insurance (VGLI),** you can update your information in one of these ways:
- [Online through the Prudential website], **or**
- By sending a letter to Prudential

Use this address to send your update to Prudential by mail:
OSGLI
PO Box 41618
Philadelphia, PA 19176-9913

**If you have Servicemembers’ Group Life Insurance Traumatic Injury Protection (TSGLI),** you can find the contact information for your branch of service on the first page of the TSGLI application.
[Find the contact information for your branch of service]

If you have life insurance through one of these VA programs, you can call us or send us a letter to get your information updated:
[bulleted list]

Call our VA Insurance Center...

Or send a signed and dated...

**Comment by bethpottsVADEPO** [comment]
@laurwill I also forgot to say that it would be good to ask him if he has a contact at Prudential or OSGLI who we could show this content to and make sure it's accurate.

**Comment by laurwill** [comment]
Thanks Beth! 
We've updated the [Drupal file](http://preview-prod.vfs.va.gov/preview?nodeId=8473) with the OSGLI information. I ended up using H4s under the life insurance heading, as we chatted last week. I just sent it back to Steve with a request for OSGLI or Prudential review, and also asked him about the links for the TSGLI form (stopped working all of a sudden) and the milConnect portal (to see if we can provide a more direct link). I'll update again when we hear back!

**Comment by laurwill** [comment]
Steve approved the changes and confirmed that he also showed the page to OSGLI contacts for their approval. 

@megzehn, these updated pages are (at long last!) ready for your copyedit:
- http://preview-prod.vfs.va.gov/preview?nodeId=709 (this one essentially went back to how it was before — we had added a list of specific life insurance programs, but now it's back to simply "life insurance benefits" in the bulleted list because they all require direct contact to change address)
- http://preview-prod.vfs.va.gov/preview?nodeId=8473

And calling out a couple style notes here to double check: 
- We have "branch of service" in the TSGLI section, but I've also seen "uniformed service" elsewhere. Do you know if "branch of service" is standard?
- The TSGLI form is a non-VA form, so I've just called it "Form SGLV 8600" here — I think we may also want to confirm how we're treating different types of form names. We can chat about this!

**Comment by megzehn** [comment]
These are now published. Over to you, @RLHecht

**Comment by RLHecht** [comment]
Thanks all! These changes are live. Closing this ticket!
