### ISSUE TITLE
Changing life insurance reference on 2 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42340]
## Issue Description
Stakeholder Steve Fital reached out to ask us to make changes on the [Change your address in your VA.gov profile](https://www.va.gov/change-address/) and [Change your address on file with VA](https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact) pages.

On the first page, he said we need to change the VMLI bulleted item to read: All VA insurance programs, except SGLI, VGLI, and FSGLI”
![Screen Shot 2022-06-03 at 3.52.02 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c336d4c4-268a-4e89-a736-4a1ae71ea927)

On the second page, we need to change the VMLI H3 to read: All VA insurance programs, except SGLI, VGLI, and FSGLI and remove (VMLI) next to the PO Box in the address.

![Screen Shot 2022-06-03 at 3.53.25 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ecb17c89-2d31-4978-ae59-5039ecff68dc)

We need to rework his changes since if we spelled out all the life insurance programs he mentions the bulleted item would be too long. We should consider if we need to make a separate bulleted list underneath for the life insurance programs. 

We will also need to rework the H3 on the second page so it's not too long with the mentions of each of those programs. 

## Tasks
- [ ] Rework bulleted list on Change your address in your VA.gov profile (Katherine)
- [ ] Rework the H3 on Change your address on file with VA.gov (Katherine)
- [ ] Review edits (Laura)
- [ ] Copyedit (Megan)
- [ ] OCTO-DE review (Beth)
- [ ] Send to stakeholder (Randi/Laura)
- [ ] Copyedit with pre-publishing checklist (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Changes to both pages are live on the site

**Comment by RLHecht** [comment]
Closing. Duplicate
