### ISSUE TITLE
[Design] Accordion on Confirmation page for pre-check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42348]
## Description
This is related to pre-check-in. 

On the "confirmation" page, accordions should use the default design component. E.g., the expected result should be that the "expand all" functionality is present. Engineers should ensure that we can still support having an individual accordion expanded on page load while using this component.  

## Tasks
- [ ] Update sketch file for pre-check-in
- [ ] Provide link to sketch file
- [ ] Attach screenshots 

## Acceptance Criteria
- [ ] Sketch file is updated
- [ ] Provide link to sketch file
- [ ] Attach screenshots 
- [ ] Talk to Lori about creating FE ticket

**Comment by loripusey** [comment]
Closing as this was a duplicate of https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42349
