### ISSUE TITLE
Certificate of Eligibility | Ensure we're matching desired Schema

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42357]
## Value Statement

**_As a_** frontend developer
**_I want_** to ensure that the submitted data matches the endpoint limitations
**_So that_** submissions aren't rejected due to invalid data lengths

## Background Context

Validate the schema of the LGY/COE endpoint, once it is obtained, and add data limitations to the date, e.g. the profile address sets most input values to have a max length of 100 characters.

## Tasks

- [ ] Verify API schema and form schema match
- [ ] Add validation & show error messages
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie to review swagger docs.

**Comment by scottymeyers** [comment]
Compare the max-data against the schema in LGY's Swagger documentation for the `PUT` request to `/api/eligibility/application`.
