### ISSUE TITLE
[BE] Appt scheduling staging tool - not seeing "review contact information" in Veteran experience

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#42353]
## User Story
This is related to the appointment scheduling tool on staging. 

When viewing pre-check-in or check-in as a Veteran that has a scheduled appointment, the first question does not appear. E.g., review your contact information. The Veteran sees review emergency contact information first. 

In the admin, we attempted to clear all information and this did not resolve the issue. 

## Tasks
- [ ] [BE] **_insert backend  work_**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
