### ISSUE TITLE
[FE] | Profile | Remove Unused Feature Toggles

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42358]
## Description:

We'd like to remove the older, unused feature flags to keep the feature flag code up-to-date and avoid unintended impacts to our releases.

## Tasks

- [x] Remove the feature flag for fax numbers
- [x] Remove the feature flag for "gender assigned at birth"
- [x] Remove the feature flag for 'direct deposit"
- [x] Remove the feature flag for direct deposit/update content page (#40723)
- [x] Identify any other feature flags for possible removal

## Acceptance Criteria

- [ ] Confirm to PO and PM when removed.

**Comment by SKasimow** [comment]
Hi @adamwhitlock1 @mdewey - I created this ticket to remove the older FF as we discussed. I'll leave here in the backlog until one of you has some bandwidth and can pick-up.

**Comment by SKasimow** [comment]
Hiya @adamwhitlock1 - added in a task to remove the ff for direct deposit.

cc/ @mdewey

**Comment by SKasimow** [comment]
One more related to DD added.

**Comment by adamwhitlock1** [comment]
This should be good to close out. Toggles have been removed in prod now and all functionality seems to be working as expected. @SKasimow
