### ISSUE TITLE
Certificate of Eligibility | Update introduction page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42355]
## Value Statement

**_As a_** frontend engineer
**_I want_** to use the most up-to-date components
**_So that_** I can ensure consistency in quality and design of component across the app

## Background Context

The logged in [Certificate of Eligibility introduction page](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction) is not using the [`va-process-list` web component](https://design.va.gov/storybook/?path=/docs/components-va-process-list--default).

Also, additional margins should be added below the first "Request a Certificate of Eligibility" action link extra margins below the process list should be removed, so that the bottom action link doesn't have so much space above it.

## Tasks

- [x] Switch to use `va-process-list`
- [x] Adjust margins above and below the `va-process-list` as appropriate
- [x] Compare changes with design (if it can be found)

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by scottymeyers** [comment]
Prototype: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/142354839/simulate/sitemap

**Comment by scottymeyers** [comment]
Design: https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/147813365/simulate/sitemap

**Comment by scottymeyers** [comment]
@Mottie should we be concerned about the left-hand padding?

<img width="698" alt="Screen Shot 2022-06-07 at 7 00 45 PM" src="https://user-images.githubusercontent.com/969752/172497095-b7c903ad-50c7-4b81-9adc-e743c36cda6a.png">
<img width="769" alt="Screen Shot 2022-06-07 at 7 00 49 PM" src="https://user-images.githubusercontent.com/969752/172497097-2f9a5480-44a2-4d2d-a881-1f2d7085dc28.png">

**Comment by Mottie** [comment]
I don't we need outer left padding - it's not in the design - but the bullets under step 2 are missing it,

**Comment by scottymeyers** [comment]
So the left padding is part of the web component. After speaking to the other engineers, we've decided to leave it as is and not compensate for it within our application as we'd have to likely come back and undo that work later once the fix is made to the web component itself.
