### ISSUE TITLE
Additional accessibility work on MGIB-AD rates page: TTY numbers and charts

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42374]
## Issue Description
Now that Beth has done her review of the new Montgomery GI Bill Active Duty rates page, there are a few accessibility issues we need to fix before it can move forward.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=5355

1. We need to remove the tables on the page that are only 2 columns and rework the content in a different way. We don't need to do this with the tables that are 4 or 5 columns. 

2. In the how to contact us section, we need to put TTY: 711 in aria labels per the [style guide](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers).

3. We also need to update the rates for 2022, which can be found here: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100121.asp The date for these should read October 1, 2021 not 2022.

## Tasks
- [x] Rework 2-column tables (Katherine)
- [x] Fix TTY number (Katherine)
- [x] Update rates (Katherine)
- [x] Review chart work (Laura)
- [x] OCTO-DE review (Beth)

## Acceptance Criteria
- [x] Page is ready for stakeholder with these accessibility fixes

**Comment by katherine-fung** [comment]
@laurwill - I have a question about the tables in the section "MGIB-AD rates for Vietnam Era Veterans with remaining entitlement." 

This is the preview: http://preview-prod.vfs.va.gov/preview?nodeId=5355 

The 1st and 2nd table in this section are one combined table on the rates page (https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100121.asp). Is it ok to combine them in Drupal? 

The 3rd and 4th table in this section are also one combined table in the rates page (https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100121.asp). Is it ok to combine them in Drupal? 

The 5th table in this section is missing the rate for "each additional dependent," so I'll add that info when I convert the table to rich text. Is that right?

**Comment by katherine-fung** [comment]
@RLHecht 

1. I updated the effective date on this rates page to say 2021, not 2022. Do you know if the intro sentence also needs to be amended?  

"Find out the Montgomery GI Bill Active Duty (MGIB-AD) rates for the 2022 to 2023 academic year." 

Should it say "2021 to 2022 academic year"? 

2. Should we add an aria label to the 888 phone number as well as 711?

**Comment by katherine-fung** [comment]
@laurwill - I have a question about the tables under the "

**Comment by RLHecht** [comment]
Thanks @katherine-fung I'm going to reopen this since we're still working on this.

1. Yes, we should also change the academic year numbers. 
2. Yes, we should have aria labels on all phone numbers if there isn't one here already. You can check if you click on source for the rich text box.

**Comment by katherine-fung** [comment]
FYI I went into this page one more time, to update the style to match the MGIB-SR edits. I changed the style of the fractions (i.e. 1/2-time enrollment) and the time frames for monthly rates (i.e. Months 1 to 6).

**Comment by katherine-fung** [comment]
Updating this ticket to reflect that I conferred with Laura ,and changed the style we use for the timeframes to say "1 to 6 months," "7 to 12 months," etc.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thank you, and I like where you and @laurwill landed with the month range style.

**Comment by RLHecht** [comment]
Going to close this ticket. Creating new ones for doing the final copyedit and publishing once we're ready.
