### ISSUE TITLE
Additional accessibility work on MGIB-AD rates page: TTY numbers and charts

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42375]
## Issue Description
Now that Beth has done her review of the new Montgomery GI Bill Active Duty rates page, there are a few accessibility issues we need to fix before it can move forward.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=5355

1. We need to remove the tables on the page that are only 2 columns and rework the content in a different way. We don't need to do this with the tables that are 4 or 5 columns. 

2. In the how to contact us section, we need to put TTY: 711 in aria labels per the [style guide](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers).

3. We also need to update the rates for 2022, which can be found here: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100121.asp The date for these should read October 1, 2021 not 2022.

## Tasks
- [ ] Rework 2-column tables (Katherine)
- [ ] Fix TTY number (Katherine)
- [ ] Update rates (Katherine)
- [ ] Review chart work (Laura)
- [ ] OCTO-DE review (Beth)

## Acceptance Criteria
- [ ] Page is ready for stakeholder with these accessibility fixes

**Comment by RLHecht** [comment]
Closing this ticket as it's a duplicate.
