### ISSUE TITLE
Adding NOD entry points to several decision reviews pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42389]
## Issue Description
Once the NOD online form launches to 100% of users on June 8, we need to add the link to the tool from several other decision reviews pages. This should be set up as an action link and will involve adding some setup language as well. 

The pages to add the link to:

- [x] [Contested claims](https://www.va.gov/decision-reviews/contested-claims/)
- [x] [Insurance claims](https://www.va.gov/decision-reviews/insurance-claims/)
- [x] [Fiduciary claims](https://www.va.gov/decision-reviews/fiduciary-claims/)

Link to add: [Request a Board Appeal](https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182)

Original intake request ticket: #42379

## Tasks
- [x] Add content and link to 3 pages listed
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] OCTO-DE review (Beth)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish pages (Megan)

## Acceptance Criteria
- [x] New content and links are live on the site

**Comment by RLHecht** [comment]
@laurwill I made the changes to the contested claims page, including removing the link to the PDF form and updating the language in the way Beth mentioned it on our call.

**Comment by laurwill** [comment]
Thanks Randi! I added the entry point to Fiduciary claims, Insurance claims, and Choosing a decision review option. 

@megzehn , these 4 updated pages are ready for you to copyedit and pass to Beth today.
- Contested claims: http://preview-prod.vfs.va.gov/preview?nodeId=3030
- Insurance claims: http://preview-prod.vfs.va.gov/preview?nodeId=3025
- Fiduciary claims: http://preview-prod.vfs.va.gov/preview?nodeId=3016
- Choosing a decision review option: http://preview-prod.vfs.va.gov/preview?nodeId=23290 

And here are some notes:
- The decision review pages are all about to get a full review from Beth, so you can focus on the new updates — we don't need to spend time futzing with existing language on the contested/insurance/fiduciary claims pages.
- Since Insurance and Fiduciary pages describe other claim types, I didn't add the full paper form options (mail/fax/etc) that we're adding to the Board Appeals main page and Contested claims — that would have made the Board Appeal section too different from the other review type sections. 
- On the choosing a decision review page, I left the shortened form name and used a text link for the form entry to match the styling on the Higher-Level review online form link.
- I just realized that I didn't adjust the spacing between paragraphs and link text sentences per our new guidance — could you do that as you edit?

**Comment by RLHecht** [comment]
@laurwill I changed the url for these action links since they were pointing to the form intro page. We are supposed to link just to the form page like this: https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182 and once the user clicks it takes them to that /introduction automatically. 

@megzehn These pages are ready to publish once you've done the once over on them all.

**Comment by megzehn** [comment]
@RLHecht these are all copyedited now and ready for you to publish tomorrow AM. 

@laurwill thank you for the notes and keeping me focused on the new language. I definitely could have spent more time futzing!

**Comment by megzehn** [comment]
@RLHecht these are all copyedited now and ready for you to publish tomorrow AM. 

@laurwill thank you for the notes and keeping me focused on the new language. I definitely could have spent more time futzing!

**Comment by megzehn** [comment]
confirming these are live @RLHecht

**Comment by RLHecht** [comment]
These pages are all live with the changes. Closing ticket!
