### ISSUE TITLE
Review/Update/Verify Accuracy of Document Outlining How to Keep BRD/EKS Synced

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42393]
## Description
Support docs need to be updated to include EKS deployment info

---
## Tasks
- [ ] Review/Update/Verify Accuracy of Document Outlining [How to Keep BRD/EKS Synced](https://vfs.atlassian.net/wiki/spaces/OT/pages/2146140164/Keep+EKS-Deployed+Vets-API+Up+to+Date+with+BRD-Deployed+Vets-API)

## Acceptance Criteria 
- [ ] How Do I... document outlining how we can keep the BRD and EKS deployed versions of vets-api reviewed/updated/verified to include EKS specifics

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
This document is still up-to-date as it is simply a quick mention of the action we have in place to remind users attempting to make a change to the dev-vets-api settings to also make the change in the application-manifests repository so that we can keep BRD and EKS deployed vets-api in sync.
