### ISSUE TITLE
Update Platform Website Build and Deploys Documentation to Include EKS Specifics for Vets-API

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42396]
## Description
Platform website documentation around builds/deploys of vets-api needs to be updated to include EKS deployment info

---
## Tasks
- [x] Review/update/verify accuracy of the [builds/deploys of vets-api platform website documenation](https://depo-platform-documentation.scrollhelp.site/developer-docs/environments#Environments-Buildsanddeploys)

## Acceptance Criteria 
- [x] Platform website documentation around builds/deploys of vets-api reviewed/updated/verified to include EKS specifics

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Published several updates to https://vfs.atlassian.net/wiki/spaces/pilot/pages/603488279/Environments which in turn will update the platform website https://depo-platform-documentation.scrollhelp.site/developer-docs/environments#Environments-Buildsanddeploys during the next publishing cycle (happens on Tuesdays and Thursdays at noon ET if I recall correctly).
