### ISSUE TITLE
Review/Update/Verify Accuracy of Document Outlining How to Perform an Off-Cycle Deploy for Vets-API

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42394]
## Description
Support docs need to be updated to include EKS deployment info

---
## Tasks
- [ ] Review/update/verify accuracy of document outlining [how to perform an off-cycle deploy for vets-api](https://vfs.atlassian.net/wiki/spaces/OT/pages/2034204681/Perform+Off-Cycle+Deploy+of+vets-api)

## Acceptance Criteria 
- [ ] How Do I... document outlining how to perform an off-cycle deployment of vets-api reviewed/updated/verified to include EKS specifics

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Added section explaining how things are auto-deployed to `dev` in EKS today with mentions of how we may tweak that to more of a schedule-based deployment trigger for `prod` once we get there:

![image](https://user-images.githubusercontent.com/56260532/172647503-51db2d08-1048-45e8-b7fb-68555d1d78a7.png)
