### ISSUE TITLE
Update word list entries in style guide so consistent language throughout

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42399]
## Issue Description
Currently the [word list](https://design.va.gov/content-style-guide/word-list) in our style guide has inconsistent language throughout when we are explaining the same thing under different entries. 

For example, we say "don't use," "do not use," "instead use," and "use TK instead." 

We also sometimes say "Capitalize" a specific word in a term and other times "Don't capitalize" or "lowercase" the other part of the term. 

We need to make all of these types of phrasing uniform. Once we determine the phrasing we want to use, we need to comb through the style guide and apply it throughout the word list.

We also should be using contractions throughout so that we are following our own rules within the style guide.

Where to edit the style guide: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/tree/master/src/_content-style-guide

## Tasks
- [x] Update word list for consistent phrasing and contractions (Megan)
- [x] Create PR for Beth to review (Megan)

## Acceptance Criteria
- [x] Word list updates are ready for Beth to review

**Comment by RLHecht** [comment]
@megzehn Once you're ready to start on this for an upcoming sprint, let me know and I'll show you how we work on changes to the style guide since it's in Github and not in Drupal.

**Comment by megzehn** [comment]
Thanks! I incorporated these changes in this PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1617
