### ISSUE TITLE
Update Vets-API Service Doc to Reflect EKS Deployment Differences

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42390]
## Description
Service docs need to be updated to include EKS deployment info

---
## Tasks
- [x] Update [vets-api service doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594594/Vets-API) to include EKS deployment explanation(s)

## Acceptance Criteria 
- [x] Vets-api service doc updated to include EKS specifics

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Updated dependencies and added a section that goes over EKS-based deployment of vets-api in the vets-api service doc:

![image](https://user-images.githubusercontent.com/56260532/172202594-b026f3ae-9557-4334-80f0-37c725ed5c07.png)
