### ISSUE TITLE
Review and Update Forward Proxy Service Doc to Reflect EKS Deployment Differences

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42391]
## Description
Service docs need to be updated to include EKS deployment info

---
## Tasks
- [x] Update [forward proxy service doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594279/Forward+Proxy) to include EKS deployment explanation(s) (if applicable)

## Acceptance Criteria 
- [x] Forward proxy service doc updated to include EKS specifics

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Added multiple notes directing a reader to the vets-api service doc that was updated previously with up-to-date processes when dealing with the dev environment / EKS-deployed vets-api:

![image](https://user-images.githubusercontent.com/56260532/172397745-a03705ad-b18c-4da4-86fc-b70bd830005e.png)
