### ISSUE TITLE
Survey Cypress E2E Test Failures

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#42406]
## Issue Description
There have been an increasing number of Cypress E2E test failures recently. Gut feelings indicate that the increase started happened during Q2 2022. This ticket is intended to be a high level overview of these failures over time, NOT digging into the details of the specific failures. Let's determine if there is a trend up in failures and how big it is first before digging into analysis of _why_ it might be trending up.

---
## Tasks
- [x] Gather raw number of E2E test failures since the start of Q2
- [x] Gather raw number of support requests related to E2E test failures
- [x] Partition data by week and look for trends
- [x] Summarize the results

## Acceptance Criteria
- [x] We know whether there are an increasing number of E2E test failures in the CI pipeline
- [x] The summary of results discusses raw numbers and next steps for analysis

**Comment by CBonade** [comment]
https://docs.google.com/spreadsheets/d/1mFsYOxlcET3rVJd-iyzFahLHQPC33Jhm8eU-vfc1dCM/edit#gid=0

Breakdown of all our support requests, with summarized count by issue and by person that filed them. Overall data does not suggest lots of Cypress failures leading to support requests, and the ones that did, 4/5 were user error.

**Comment by holdenhinkle** [comment]
Google sheet - E2E failures against `main` since April 1st - https://docs.google.com/spreadsheets/d/1dZ1KqaSe3jrqzzMHdRw3g_icELQdU0NVn84l2s0up9k/edit#gid=0

**Comment by pjhill** [comment]
We're going to look into a bit more data regarding Q1 as well tomorrow, so I'm moving this back to `in progress`.

**Comment by pjhill** [comment]
We have collected all the data that we need. Thanks for grabbing all of this!
