### ISSUE TITLE
[CST] Mock list of claims

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#42401]
## Value Statement
**_As a_ developer**
**_I want to_ be able to easily mock endpoints in the Claims Status tool**
**_So that_ I can focus on the work assigned, instead of spending time trying to get the elements I'm working on to show up** 

---
## Background Context
- Claims status tools doesn't load data for users when developing locally, so things like viewing a list of claims or viewing the details of a claim is not possible without making modifications to either `vets-api` or doing some sort of mocking in `vets-website`. Currently there are some instructions for mocking claim details in the frontend code, but there isn't anything in place for mocking a list of claims.

## Acceptance Criteria
- [ ] Instructions should be included for mocking a list of claims in the claims status tool

## Open Questions
* Since there are a variety of ways to mock data when working with `vets-website` and `vets-api`, one of the big questions that remains is what is the best way to accomplish this?

## Tasks
- [x] Import a list of claims from `src/applications/claims-status/tests/e2e/fixtures/mocks/claims-list.json` into the action creator responsible for fetching a list of claims
- [x] Add code to `src/applications/claims-status/actions/index.jsx#getClaimsV2` to use the mock json instead of making an API call
- [x] Document the method used so that others can easily do this as well

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
