### ISSUE TITLE
Launch publicly viewable report of external service SLOs

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4240]
## Product Outline

[Request Timing Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/request-timing(SLO)/request-timing.md)

## High Level User Story/ies
As a developer , I need to know how long it takes for requests from the frontend to be returned from all vets-api and external services so I can understand and escalate potential problem areas to business leaders.

As leadership, I need to know what external services the platform relies on that are not meeting our expectations so that I can escalate those issues to the responsible teams for resolution.

## Hypothesis or Bet
If we expose this data, we will have a better understanding of bottlenecks on the front end and be able to push back on external services to improve the experience for the user.

## VSP OKR
O4: All of the Platform's KPIs are easily measured and shared openly.

## Definition of done
- [ ] A product proposal has been submitted to business
- [ ] Timing for each stage of the requests coming from the front end are recorded
- [ ] Timing from each stage of external services are recorded
- [ ] Both the above data points are available to be utilized in a front end to create a visualization to identify problem areas.

**Comment by drorva** [comment]
Requested changes:
* As before, have a summary on top of the report. Should be the uptime for each service.
* The colors for uptime should be:
  * > 99.9: green
  * < 99.5 > 99: yellow
  * < 99: red
* Latency
  *  < 1000: green
  * > 1000 < 2000 yellow
  * > 2000 red
We're starting with a somewhat generous outlook, and hopefully will be able to tighten the standards as we progress.
