### ISSUE TITLE
[FE] My VA Audit UX Improvements: Update 30 day conditional in Claims and Appeals Section

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42407]
## Background
Based on our audit we want to remove the condition and text for "within the last 30 days" in the Claims and Appeals section of My VA.

## Tasks
- [ ] Remove "within the last 30 days" text from the Claims and Appeals section (Angela will have new design)
- [ ] Remove 30 day conditional logic within the claims and appeals section
- [ ] validate

## Acceptance Criteria
- [ ] The text "You have no claims or appeals" shows regardless of if the user has had claims or appeals within the last 30 days

## Resources
- [design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42196)

**Comment by ericasauv09** [comment]
We may end up adding more to this or combining with other claims & appeals section updates
