### ISSUE TITLE
GA4 - VFS Team Meetings (Round 1)

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42432]
## Issue Description
As part of the GA4 migration we need to meet with individual VFS teams to discuss the following:

- New GA4 event structure changes (walk through confluence docs)

- Review their custom GTM events (are they tracking custom events that could be supported by a design/form system component and if so how do we move them to those)

- Determine requrirements for GA4 (can we deprecate some custom tags and/or reports no longer needed)

- Review front end code implementation needs

- Answer any questions/concerns they may have.

---
## Tasks
As part of this ticket we will complete 6 of the 21 VFS teams meetings
- [ ] [enter team name]
- [ ] [enter team name]
- [ ] [enter team name]
- [ ] [enter team name]
- [ ] [enter team name]
- [ ] [enter team name]

## Acceptance Criteria
- [ ] We have met with 6 VFS teams.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Close - duplicate
