### ISSUE TITLE
[FE] Candidate Address Modal - Confirmation Screen

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4244]
## User Story: 

As a designer i need to upload the final UX steps of getting through the states of validation all the way to the confirmation stage. 
  
## Tasks 

_The steps that must be done by the team to complete the acceptance criteria_ 

- [x] Upload all the states to be accounted for in the user flow

- [ ] Make sure confirmation page is added and validated

- [ ] Validate on staging that confirmation page is added and all states are accounted. 
  

## Acceptance Criteria: 

_The requirements that must be met in order to mark this user story as completed_ 

- [ ] This is validated on staging

**Comment by artistgreen** [comment]
Scenario 1:

If the address the user enters is a good address (rates 80% or over in confidence score), there are no UX states - it will save to the profile.

**Comment by artistgreen** [comment]
Scenario 2:

User enters address

![Override - Suggestions](https://user-images.githubusercontent.com/53535009/70831448-980aea80-1dc0-11ea-9e71-e567f686364a.png)


----------

**Comment by artistgreen** [comment]
Scenario 3:

**Override with no suggestions**

1.  User enters address

![Override - No suggestions](https://user-images.githubusercontent.com/53535009/70832293-bd98f380-1dc2-11ea-9418-752ad6aa4f23.png)

----------

2.  User can select their entered address and continue.  User can edit their entered address, clicking this will take them to the previous screen with the form. User can cancel.

(address selected by default)

![Override - No suggestions 2](https://user-images.githubusercontent.com/53535009/70832410-02248f00-1dc3-11ea-8c8a-0c05ce44019e.png)

----------

3.  User can update their address.  User can cancel.

![Override - No suggestions 3](https://user-images.githubusercontent.com/53535009/70832456-27b19880-1dc3-11ea-8619-fa18b827295f.png)

----------

4.  Profile screen displays 'We're working...' messaging

![Override - No suggestions 4](https://user-images.githubusercontent.com/53535009/70832492-35671e00-1dc3-11ea-8724-892e813bf530.png)

----------

5.  Updated address appears in Mailing Address section

![Override - No suggestions 5](https://user-images.githubusercontent.com/53535009/70832528-4879ee00-1dc3-11ea-8a82-b73897b00010.png)

**Comment by artistgreen** [comment]
### **Scenario:  No override with suggestions**

**Comment by artistgreen** [comment]
### **Scenario:  No override with no suggestions**

1.  User enters address

![No Override - Suggestions](https://user-images.githubusercontent.com/53535009/70834116-7eb96c80-1dc7-11ea-9014-938fd457b92c.png)

----------

2.  User can select an address suggestion and continue. User can edit their entered address, clicking this will take them to the previous screen with the form. User can cancel.

Copy for modal:  We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered.

![No Override - No suggestions 2](https://user-images.githubusercontent.com/53535009/70834176-b0323800-1dc7-11ea-901f-c173d51805e7.png)

----------

**Comment by artistgreen** [comment]
### **Scenario:  Add missing unit number with override**

1.  User enters address

![Override - Suggestions](https://user-images.githubusercontent.com/53535009/70836190-795f2080-1dcd-11ea-9931-53f2bb17cc7a.png)

----------

2.  User can select their entered address and continue. User can edit their entered address, clicking this will take them to the previous screen with the form. User can cancel.
(address selected by default)

Copy for modal:
It looks like your address is missing a unit number. Please edit your address to add a unit number. If you don't have a unit number and the address you entered below is correct, please select Continue.

![Add missing unit number with override 2](https://user-images.githubusercontent.com/53535009/70836466-36ea1380-1dce-11ea-8753-cdb28c9f5448.png)

----------

3.   User can update their address. User can cancel.

![Add missing unit number with override 3](https://user-images.githubusercontent.com/53535009/70836569-8af4f800-1dce-11ea-8982-d2165a68a47c.png)

----------

4.  Profile screen displays 'We're working...' messaging

![Add missing unit number with override 4](https://user-images.githubusercontent.com/53535009/70836584-9811e700-1dce-11ea-860b-5ef7ec46412c.png)

----------

5.  Updated address appears in Mailing Address section

![Add missing unit number with override 5](https://user-images.githubusercontent.com/53535009/70836599-a4963f80-1dce-11ea-9c5b-ece85d1efc9c.png)

----------

**Comment by artistgreen** [comment]
### **Scenario:  Add missing unit number without override**

1.  User enters their address

**Comment by artistgreen** [comment]
### **Edit bad unit number with override**

1.  User enters address

![Edit bad unit number with override](https://user-images.githubusercontent.com/53535009/70840864-77a05780-1de3-11ea-961d-311b8d6ae9cd.png)

-----------

2.  User can select their entered address and continue. User can edit their entered address, clicking this will take them to the previous screen with the form. User can cancel.

Copy for modal:  We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number. If your unit number is already correct, please continue with the address you entered below.


![Edit bad unit number with override 2](https://user-images.githubusercontent.com/53535009/70840868-82f38300-1de3-11ea-92ca-aa6792510301.png)

----------

3.  User can update their address. User can cancel.

![Edit missing unit number with override 3](https://user-images.githubusercontent.com/53535009/70840914-eed5eb80-1de3-11ea-972f-e5bed70d4748.png)

----------

4.  Profile screen displays 'We're working...' messaging


![Edit missing unit number with override 4](https://user-images.githubusercontent.com/53535009/70840919-01502500-1de4-11ea-9803-0008a98e0378.png)

----------

5.  Updated address appears in Mailing Address section


![Edit missing unit number with override 5](https://user-images.githubusercontent.com/53535009/70840930-12993180-1de4-11ea-8cb9-217ed5def0d4.png)

----------

**Comment by artistgreen** [comment]
### **Edit bad unit number without override**

1.  User enters address


![Edit bad unit number with override](https://user-images.githubusercontent.com/53535009/70841020-e3cf8b00-1de4-11ea-96d3-c58b361adc1e.png)

----------

2.  User can edit address, clicking this will take them to the previous screen with the form. User can cancel.

Copy for modal: We couldn’t verify your address with the U.S. Postal Service because it’s missing a unit number. Please edit your address below to add a unit number.


![Edit bad unit number without override 2](https://user-images.githubusercontent.com/53535009/70841025-f3e76a80-1de4-11ea-9783-d4497d843069.png)

**Comment by Samara-Strauss** [comment]
Closed this in favor of more clearly defining the work in another ticket.
