### ISSUE TITLE
Create / Update Architecture Diagram for EKS Infrastructure

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42453]
## Description
Supporting architecture diagrams need to be updated/created to include EKS deployment info

---
## Tasks
- [x] Create / update EKS infrastructure diagram

## Acceptance Criteria 
- [x] EKS infrastructure architecture diagram exists and is accurate

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Closing.
