### ISSUE TITLE
Create / Update Architecture Diagram for End-to-end Request Flow in EKS-deployed Vets-API

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42450]
## Description
Supporting architecture diagrams need to be updated/created to include EKS deployment info

---
## Tasks
- [x] Create / update end-to-end request flow diagram for vets-api in relation to the EKS-based deployment

## Acceptance Criteria 
- [x] End-to-end request flow architecture diagram exists and is accurate

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Creating a new diagram in lucid app following the architecture style on the [reverse proxy service doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy)
