### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 6/20

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42466]
## Issue Description
We need to swap out the videos in the stories section of the CLP to the 2 Veterans to these two Veterans:

Patricia Victor: https://www.youtube.com/watch?v=Dcnx5fOY268
John McAllister: https://www.youtube.com/watch?v=X2c7NMAWgHM

**Drupal Page:** Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Documentation for how to swap videos:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

---
## Tasks
- [x] Replace text and videos 
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! Patricia Victor and John McAllister were added in.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by megzehn** [comment]
Reviewed and published. Over to you, @RLHecht!

**Comment by RLHecht** [comment]
Thanks all! This is live and I created a new ticket for the next time. Closing!
