### ISSUE TITLE
Host to execute load test on vets-api

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#42465]
## Description
Requesting a host with dedicated IP address to push load against `vets-api` staging server for measuring `check-in` rails engine performance.
 
## Background/context 
Check-in Experience team is looking for executing performance testing on vets-api/check-in rails engine in staging environment.  vets-api has a throttling limit set in [rack_attack](https://github.com/department-of-veterans-affairs/vets-api/blob/111cec9c8dd3264beab30d711e0bc0f783f686b0/config/initializers/rack_attack.rb#L50-L52) to avoid malicious attack.  

Current setting allows 10 requests per minute from an IP address.  Performance testing requires 10 requests per second based on check-in load estimation (more details in [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/performance-testing/website-api-perf-testing.md)).   Rack attack provides a workaround for adding a specific list of IP address as safelist_ip to overcome the limitation.  

Spinning up a host with dedicated IP enables us to safelist the IP address in rack_attack and push the load to the staging server.

---
## Tasks
- [ ] Host with dedicated IP address

## Acceptance Criteria 
- [ ] Check-in Experience team able to run load test on staging vets-api/check-in rails engine

---
### Reminders
- [ ] [patient-check-in team](https://github.com/orgs/department-of-veterans-affairs/teams/patient-check-in)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40552 Reference

**Comment by oseasmoran73** [comment]
Hi @kanchanasuriya 

As I previously mentioned, we do not give static/dedicated IP addressed. That being said, I can provide a range of IPs that the performance load test can spin up on. I believe you said that is acceptable, but wanted to double check if this is still the case?

**Comment by kanchanasuriya** [comment]
Sure @oseasmoran73, a range of IPs would definitely work as well.

**Comment by oseasmoran73** [comment]
@kanchanasuriya Great! I will provide that in a minute. I accidentally closed the page 😅
