### ISSUE TITLE
Edit 3 R&S articles from Community Care content author

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#42470]
## Story

As a Community Care content author, I need a review of resources and support content before publishing in Drupal.

## What's needed

- Editorial review (managing editor, copy editor) of pages as they're ready. We'll likely need 2 rounds of reviews for each page: 1 prior to SME review and 1 after the author incorporates any SME feedback.
- Provide pre-publication checklist review and feedback to content authors.
- This work will be ongoing. We'll want to discuss and establish a cadence for this. For example, we can set a goal of reviewing 2 pages per week.

Content author Kelly Farmer submitted 3 R&S articles for review.

Pages to review:
- [ ] [Getting urgent care at VA](http://preview-prod.vfs.va.gov/preview?nodeId=49848)
- [ ] [File for reimbursement of non-VA prescription and medical expenses](http://preview-prod.vfs.va.gov/preview?nodeId=49844)
- [ ] [Does VA cover Indian Health Service or Tribal health care?](http://preview-prod.vfs.va.gov/preview?nodeId=49836)

Word docs she built the Drupal pages from:
[https://app.zenhub.com/files/133843125/06c6be74-de0c-4754-a362-aca17c84e574/download](https://app.zenhub.com/files/133843125/06c6be74-de0c-4754-a362-aca17c84e574/download)

[https://app.zenhub.com/files/133843125/4532223b-b43b-48e5-b28e-71180c18eaf4/download](https://app.zenhub.com/files/133843125/4532223b-b43b-48e5-b28e-71180c18eaf4/download)

[https://app.zenhub.com/files/133843125/bb35bdfa-2c6e-4602-91a3-bbc0ccfa7656/download](https://app.zenhub.com/files/133843125/bb35bdfa-2c6e-4602-91a3-bbc0ccfa7656/download)

## Tasks
- [x] Edit (Laura)
- [x] Review and finalize edits and update Drupal article (Danielle)
- [x] Copyedit - **hold as draft** (Megan)
- [x] Work with community care team to send to SMEs (Danielle)
- [x] Incorporate any changes from SMEs (Kelly - CC team)
- [x] Publish (Megan)

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ,
I did a first pass on these 3 articles, and I'd love to have a checkin with you before we pass them along to make sure I'm doing the right level of editing for this process. 
- [Tribal health R&S.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9751037/Tribal.health.R.S.docx)
- [Urgent care R&S.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9751039/Urgent.care.R.S.docx)
- [File a reimbursement claim R&S.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9751040/File.a.reimbursement.claim.R.S.docx)

And a general style question — do we use "non-VA" to refer to in-network community care providers?

**Comment by megzehn** [comment]
Thanks, @DanielleThierryUSDSVA! I copy edited these and made some minor changes that we discussed during our check-in ("adding "community care" before providers only at the beginning, and tweaking the lead-in before the bullet list on the [urgent care page](http://preview-prod.vfs.va.gov/preview?nodeId=49848)). 

They are still in drafts!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @megzehn!

**Comment by laurwill** [comment]
We published these 3 pages as a batch along with the [4 CC pages in this ticket](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/50573) — Danielle confirmed via slack that SMEs had seen and signed off on all 7 pages.

Closing this ticket.
