### ISSUE TITLE
[FE] Audit E2E tests and add axeCheck calls to non-compliant files

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#42477]
Warning message viewable in my IDE as of today:

> Cypress E2E tests must include at least one axeCheck call. Documentation for adding checks and understanding errors can be found here: https://depo-platform-documentation.scrollhelp.site/developer-docs/A11y-Testing.1935409178.html

## Tasks
- [ ] Determine if this is still an issue. Find what is flagging (eslint?) and run locally.
- [ ] Add axeCheck calls to any components that are missing them
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
This ticket was opened during a blip where this warning message was being displayed on unit tests as well as E2E tests.

I have audited our E2E files and all test files look to be compliant.

The only test files which do not have axeCheck calls are our screenshot test suites, which are not actually testing anything, and therefore don't need this check.
