### ISSUE TITLE
Certificate of Eligibility | Design/UX review of loan history page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42488]
## Value Statement

**_As a_** Veteran filing out the Certificate of Eligibility form
**_I want the_** collapsed card information to be clear
**_So that_** I can see the full address and correctly formatted date

## Background Context

When more than one VA-backed loan is added (rare situation?), I don't see the full address (address line 2) and the date range is shown with "XX" for the day of the month. This may be confusing to some users if the address line 2 includes an apartment number and the "XX" may not be clear - see the attached screenshot

<details><summary>VA loan history page</summary>

![A collapsed VA backed loan card us not including the street address line 2, and the date is showing 01/XX/2015 - 01/XX/2020 as a date range for a loan](https://user-images.githubusercontent.com/136959/172471065-edef55fe-39d2-4561-b912-1c28d169c689.png)</details>

## Acceptance Criteria

- When more than one VA-backed loan is displayed, the address and date range are displayed in an easy-to-understand format

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Revisit after Joe's review.

**Comment by jsokohl** [comment]
Working on a design pattern--researching the VADS to see what's usable. Also, looking in the virtual attic for files that'll help

**Comment by saderagsdale** [comment]
Blocker: @jsokohl cannot find the source code for the design. This effort needs design work and light research to understand the date formatting choice. 

AC: Determine how to represent home loans if there's more than one.

**Comment by jerekshoe** [comment]
I don't know where the original source files are for COE, but I do have the uxpin link in case you guys don't already have it:
https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139511607/specification/sitemap

**Comment by jerekshoe** [comment]
Also FYI: the original designer was making all of his edits in UXPin so even if we had the source files they wouldn't be up to date with the UXPin prototype

**Comment by jsokohl** [comment]
Got that—just need the editable source. Thanks. 

joe
Joe Sokohl
1.804.873.6964

**Comment by saderagsdale** [comment]
@jsokohl Are we going to rebuild the design docs so we can move forward?

**Comment by saderagsdale** [comment]
@jsokohl Updated the AC. Let me know if that is clear enough. When ready for review, you can add a link to designs in the ticket.

**Comment by saderagsdale** [comment]
@jsokohl Looking for some guidance on this ticket. Do you consider this a launch blocker?

**Comment by jsokohl** [comment]
it is a requirement. Let's roll into the next sprint.

**Comment by Mottie** [comment]
Fixed in [#21969](https://github.com/department-of-veterans-affairs/vets-website/pull/21969)

<img width="572" alt="COE loan page showing a collapsed card with a date range of 01/2022 - 01/2022 and an open card showing February 2022 in both the closing date and paid off date form elements" src="https://user-images.githubusercontent.com/136959/185443832-410a5b87-b165-4124-be3e-3ba957679114.png">

Please feel free to close this ticket if y'all don't think we need to do anything else.

**Comment by saderagsdale** [comment]
@jsokohl Can you take a look and let me know your thoughts (see Robin's comment above)?

**Comment by jsokohl** [comment]
It's great we have the same month issue solved! Nice. 

I still need to provide the design solution for the multiple loans. This image shows only one loan.

**Comment by Mottie** [comment]
The image actually includes multiple loans, both with the same closing date & paid off date.

**Comment by saderagsdale** [comment]
@jsokohl good to close?

**Comment by jsokohl** [comment]
No, not yet. So sorry--I am doing a version where the edit button opens the loan details under the loan address,

**Comment by jsokohl** [comment]
So...here's how I'd do it. Note that the spacing and alignment here are FPO--I didn't get pixel perfect.

The Edit CTA  should open a form with the gray box, as you've already wonderfully coded, @Mottie The issue is, how does the Veteran signal that they've completed that action? How do they recover from it? And how do they understand differentiation if there are multiple existing loans?

Take a look first at this drawing, which shows a state after the Veteran has entered this step and begun to fill out the blank form that appears onEntry.
![Existing Loan First View](https://user-images.githubusercontent.com/73672031/186809168-015a4dc4-0fe3-405d-bfaf-12c172c804b6.png)

That's great...and then going to the next screen would save the details of that loan. What if they return though to the page and want to edit a loan? That's what this next sketch supposes:

![Editing an Existing Loan](https://user-images.githubusercontent.com/73672031/186809282-67163406-6bf2-47df-b5c1-b8a3ea9e885d.png)

I've used the Update/Cancel pattern that's in the component library. 

Also, note that I've added the 2nd line of an address as well as I've stacked the address, which would be a more recognizable date format. Hope this helps and isn't too weird.
FYI @saderagsdale

**Comment by Evafloyd** [comment]
This seems like a good solution to me. Thanks for keeping me in the loop!

**Comment by saderagsdale** [comment]
@Mottie Hey - Hey there - what are next steps on this ticket? Looks like it's been in "validate" for the full sprint.

**Comment by Mottie** [comment]
Currently, each loan card only includes a "Remove" button. We'd need to update the card to include the "Update" and "Cancel" button. If I recall correctly, this would only require including a single option, so it should be a quick change.

**Comment by Mottie** [comment]
Oops, I misspoke... there is no method to "Cancel" changes. Adding the show save button option results in this view:

<img width="566" alt="loan history card with an update primary button and a secondary remove button at the bottom" src="https://user-images.githubusercontent.com/136959/188897422-4367356d-1d62-4535-9949-38c2e66c32c3.png">

**Comment by jsokohl** [comment]
Can it not use the Update and Cancel that I'd designed?

**Comment by Mottie** [comment]
Adding a "Cancel" button would require a global platform change, unless we copy and modify that field component; but we would then need to determine if _all_ array-type patterns, like this loan history page
