### ISSUE TITLE
Remove virtual agent chatbot react widget from Contact Us page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42484]
## Issue Description
Once the virtual agent chatbot is available to 100% of users, we need to remove the react widget we have on the [Contact us](https://www.va.gov/contact-us/) page and put the content directly into Drupal. 

We will wait until the chatbot's PM gives us the go-ahead because even when it's at 100% of users they are going to monitor the traffic to determine if it needs to be bumped down again. 

Content to add to Drupal:

![Screen Shot 2022-06-21 at 8.38.15 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/99407bfc-4de4-425a-bf88-e8dad79ee748)

Link to chatbot: https://www.va.gov/contact-us/virtual-agent/

## Tasks
- [x] Assess where chatbot link should be moved and surrounding content (Aliyah
- [x] Review (Laura)
- [x] OCTO-DE review (Beth)
- [x] Remove widget and add content to Drupal (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish page (Megan)

## Acceptance Criteria
- [x] Chatbot content is now in Drupal and live on the site

**Comment by ianpsant** [comment]
Content note: Within the bot itself, in order to make it clear this is an AI bot and not a live person on the other side of the screen, we are now referring to our product as VA chatbot and not VA virtual agent. So the existing content would be:

> ! VA chatbot
>
> You can also use our chatbot to get information about VA benefits and services.
>
> -> Go to the VA chatbot

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the slack comment from Ian about placement on the page. He's worried it might get buried in that Explore section and the chatbot usage will decrease. Do you want to assess the page and see where else it might make sense to place this and the content we would use? Then we can have Laura review and pass to Danielle for her final approval. 

Also noting again that when we pull this into Drupal we will start calling it the VA chatbot instead of the virtual agent. Thanks!

I think we were hoping that it would be it's own section similar to "Contact us online through Ask VA" or "Call us" or "Contact your local VA facility" since it is a communication channel. That and we're worried about the link being buried and chatbot usage decreasing. The authenticated version has been live since May 9 and people can check their claim status by logging in via the chatbot. Appeals should be releasing in the next week or two.

**Comment by LucianaAlexanderMorais** [comment]
@RLHecht @ianpsant Why can't we follow directly after AVA's placement on the Contact Us page?

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! Adding in my doc with three options for chatbot language and two options for placement. There is one question for you re: a "Note" 

This is ready for you when you have a moment!

[Remove virtual agent chatbot react widget from Contact Us page_AB_July 5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9048159/Remove.virtual.agent.chatbot.react.widget.from.Contact.Us.page_AB_July.5.docx)

**Comment by laurwill** [comment]
Thanks Aliyah! 

@LucianaAlexanderMorais we agree with making this a new H2 underneath the Ask VA H2 — here's our proposed text:

**Ask our chatbot a question**
Our chatbot can help you find information about VA benefits and services. The chatbot won't connect you with a person, but it can show you where to go on [VA.gov](http://va.gov/) to find answers to some common questions.

We also wanted to confirm: Does the bot have an official name, like "VA Chatbot"? 
Let us know if you have feedback or questions on the suggested text!

**Comment by LucianaAlexanderMorais** [comment]
@laurwill @ianpsant Thank you! The text is fine, and the bot currently does not have a name. We will schedule removal of the extra Expand all - thank you for helping us with this!

**Comment by RLHecht** [comment]
Thanks all! @aliyahblackmore You can go ahead and remove the widget and add this approved text to the page.

**Comment by ianpsant** [comment]
@RLHecht @aliyahblackmore We're removing the widget, but also recreating it in Drupal and we can control whenever we want to sunset it, right? And of course adding the approved text page.

**Comment by RLHecht** [comment]
@ianpsant I think I'm a little confused. I thought our team is supposed to remove the react widget that's currently on the Contact us page and replace it with content and a link to the chatbot directly in Drupal also on the Contact us page. Should we be doing something different?

**Comment by laurwill** [comment]
Hi @ianpsant! Sorry for the confusion — we're now recommending that we remove the alert completely and replace it with the new H2 "Ask our chatbot a question." We aim to use those info alerts only for a limited time, so this will transition the chatbot into the evergreen page content. And since we're locating the new H2 just under Ask VA, it will still appear close to the top of the page. Let us know if you have any questions or feedback about this approach!

**Comment by ianpsant** [comment]
We're currently exploring, working with leadership, on moving the chatbot off it's own page to the bottom right corner of VAgov, where most people expect a chatbot to be located. As such, we were hoping to have the Info Alert box at the top of Contact Us until October. We'd also be able to get some analytics on how many people would click on the Info Alert link vs the Section link. Would there be any issues in keeping the Info Alert box longer? Happy to set up a meeting to discuss.

**Comment by laurwill** [comment]
Hi @ianpsant , thanks for this update — we don't see any issue with keeping the alert until October. We can update the language in the alert instead of replacing it with the new H2 section. 

Just to confirm, do you mean comparing analytics from before and after we take the alert down in October? We weren't planning to have both the alert and the H2 section live on the page at the same time.

**Comment by laurwill** [comment]
Hi @ianpsant , great! If you'd like, we can update the alert text to use some of the approved language now — like:

**VA chatbot**
You can also use our chatbot to get information about VA benefits and services. The chatbot won't connect you with a person, but it can show you where to go on [VA.gov](http://va.gov/) to find answers to some common questions.
> Go to the chatbot

**Comment by ianpsant** [comment]
@laurwill Yes, the updated text in the alert would be great!

**Comment by laurwill** [comment]
Great! @aliyahblackmore you can go ahead and make the changes to the alert in Drupal.

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! This is ready for you to copy edit!

http://preview-prod.vfs.va.gov/preview?nodeId=8472

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore :) 

@RLHecht, this is now published!

**Comment by RLHecht** [comment]
These changes are now live. Closing ticket.

**Comment by laurwill** [comment]
Thanks for confirming this approach over slack, Ian! We'll move ahead with this change.
