### ISSUE TITLE
Certificate of Eligibility | Add mock data to use with testing

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42489]
## Value Statement

**_As someone_** testing the Certificate of Eligibility online form, locally or in staging, 
**_I want the_** mock data so I can prefill the form quickly & easily
**_So that_** I can evaluate the form at any step quickly and easily

## Background context

The Certificate of Eligibility form does not include any mock data, so I wouldn't be able to paste in the mock data into the [save in progress menu](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress-menu) to quickly prefill and jump to any page within the form.

In addition, this data would allow end-to-end testing of the COE, once the app is available in published, but not publicly available, to production. As well as the testing of data transformers possibly needed prior to submission - we're still awaiting a submit endpoint API.

## Tasks

- [ ] Add mock data for COE
- [ ] Add tests, as appropriate

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
