### ISSUE TITLE
[design] Notice of Disagreement | Add V2 form changes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42492]
## Value statement

**_As a Veteran_** filling out an online Notice of Disagreement form
**_I want to_** be able to request an extension, or appeal a VHA denial, which is available on the paper form
**_So that_** I can fill out the online form instead of filling out a paper form

## Background contexts

The [Notice of Disagreement paper form](https://www.va.gov/vaforms/va/pdf/VA10182.pdf) includes two checkboxes in part 3, box 11 which allow the Veteran to 1. request an extension, and 2. appeal a VHA denial specifically; and add additional comments to an attachment.

<details><summary>Part III, Box 11 and instructions from PDF</summary>

<img width="1133" alt="Checkbox with text stating 'Check here if you are including a request for an extension of time to file the VA Form 10182 due to good cause and then attach additional sheets explaining why you believe there is good cause for the extension.' and a second checkbox with 'Check here if you are appealing a denial of benefits by the Veterans Health Administration (VHA)'" src="https://user-images.githubusercontent.com/136959/172487497-7547aaf7-5342-40d5-b171-d833b53bc629.png">

<img width="1161" alt="Instruction page stating: 'Extension Requests Check the box in Part III, Block 11, if you are including a request for an extension of time to file the VA Form 10182 due to good cause and attach additional sheets indicating why you believe there is good cause for the extension'" src="https://user-images.githubusercontent.com/136959/172487493-7c3aa329-9afb-4cdd-9da2-5068b43aa461.png"></details>

[Lighthouse API v2 schema](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/config/schemas/v2/10182.json)) has already been updated to include 3 fields:

- Extension request (`true` or `false`; yes or no radio)
- Extension reason (string with max length of 2300; text box)
- Appeal of VHA denial (`true` or `false`; yes or no radio)

## Tasks

- [x] Design a pages to include the Veterans choices for extension request and reason 
- [x] Design a page to include the Veterans choice for appealing a VHA denial
- [x] Content review of pages

## Definition of done

- [x] All tasks complete

**Comment by saderagsdale** [comment]
@Mottie this has the COE label on it. Is that accurate?

**Comment by Mottie** [comment]
Oops, no. This is for NOD. Thank you!

**Comment by saderagsdale** [comment]
Dupe: https://github.com/department-of-veterans-affairs/va.gov-team/issues/43646

**Comment by eileen-coforma** [comment]
@saderagsdale Is there a reason we're keeping this open, if it's a dupe for #42493 ?

**Comment by saderagsdale** [comment]
@eileen-coforma I think this is for the frontend work and #42493 is for the backend work. Correct, @Mottie?

**Comment by eileen-coforma** [comment]
If that's the case, I need to move my comments over.

Draft designs: https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/6863DCFF-CAA2-4BAD-BE68-F2D584466FFB/canvas

**Questions:**
- What is considered 'good cause' for extension? I can't find any more information about it.
- What does it mean to appeal a VHA denial? Is the process any different for veterans? That information is not part of the form.

I found reference to 'good cause' under [BVA](https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/) with examples. Including it as an option for copy in draft design.

**Comment by Mottie** [comment]
This ticket is for the design, #42493 is the frontend ticket.

**Comment by saderagsdale** [comment]
Thanks for clarifying @Mottie

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie 
Alejandro came back with feedback from the board. One edit the board has asked for is to provide the ability for the veteran to upload documents to support their extension request. 

Is this doable, and will this add to scope?

**Comment by saderagsdale** [comment]
@eileen-coforma  cc @Mottie 

This was the exact language Alejandro sent back on behalf of the board: _"Page 2 of the PDF includes the screen showing the text box in which the Veteran/appellant can type out why they believe there is good cause, but will they also be provided the opportunity to attach and submit any documents in support of the extension request, if needed? We recommend providing the ability to submit evidence in support of the extension request.”_

I responded to the email to ask if this is truly necessary to get the essential changes to the form into production. We can build just about anything, but I am going to avoid adding on scope unless we have a user-validated reason. I want to hear from Veterans and the business before deciding they need the ability to upload documentation.

**Comment by Mottie** [comment]
Uploading is already included, but is only currently available if the Veteran chooses to upload evidence. We could relatively easily add an additional page to upload _more_ documents, but how can we assure that they only upload extension-related documents.
