### ISSUE TITLE
BE | Profile | Migrate Military Info | Feature Flag @ 25%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42491]
## Background

Military Information is being migrated from eMIS to VA Profile. Before fully releasing we need to deploy to 25% of users so that the changes are visible in Production and can be monitored for a few days.

## Tasks

- [x] Update feature flags to make Military Information changes visible in Production for 25% of users
- [x] Smoke test on Prod
- [x] Validate on Prod with PM and PO

## Acceptance Criteria

- [x] Feature flags updated to make Military Information changes visible in Production for 25% of users
- [x] Smoke tested on Prod
- [x] Validated on Prod with PM and PO

**Comment by Samara-Strauss** [comment]
I doubt we'll be ready to do this by the 5th, but just noting that I'd like to be here for launch and I am out the 5th and 6th. Please don't launch anything without me.

**Comment by tpharrison** [comment]
Turned on 25% of users on 8/9.

**Comment by Samara-Strauss** [comment]
I updated the project and product outlines to reflect this launch. Congratulations!
