### ISSUE TITLE
Take content out of tables on MGIB-SR rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42495]
## Issue Description
In continuing our effort to remove unnecessary tables from our pages for accessibility reasons, we need to take the content out of the tables on our draft Montgomery Gi Bill Selected Reserve rates page. 

Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=5449 

## Tasks
- [ ] Remove content from tables and put into rich text field (Katherine)
- [ ] Edit changes (Laura)
- [ ] Copyedit (Megan)
- [ ] OCTO-DE review (Beth)

## Acceptance Criteria
- [ ] Content taken out of tables and put into rich text
