### ISSUE TITLE
Deprecate sample recruiting email for card sort

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#42506]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

Assignee: 
Peer Reviewer:

## Description
Update after meeting with Brian (Perigean), Shane, and Clayton.
-Guidance should be that Perigean creates the unmoderated emails, current/previous guidance has been that researchers draft.

There is some guidance on VA github for [sample recruiting email for card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/sample-recruitment-email-template.md).

There might also be guidance on the research checklist and on the unmoderated research pages of Platform.

## Artifacts Needing Updates
- [sample recruiting email for card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/sample-recruitment-email-template.md).
- ~Platform page for research checklist~
- Platform page for [unmoderated research](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies#PlanningUnmoderatedStudies-Settingupanunmoderatedstudy)

## Tasks
- [x] Check if recruiting email is referred to on any Platform pages
- [x] mark the GH page as deprecated
- [x] communicate change

## Acceptance Criteria
- [x] Platform Website: has been updated to indicate that Perigean creates the recruitment email, researchers do not.
- [x] GH page [sample recruiting email for card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/sample-recruitment-email-template.md) has been updated
- [x] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue

- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.
