### ISSUE TITLE
Move  sample recruiting email for card sort to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#42505]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

- Intended Audience: VFS teams
- Desired Outcome: guidance lives on Platform as SOT 
- Due Date: 

## Description

There is some guidance on VA github for [sample recruiting email for card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/sample-recruitment-email-template.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## Artifacts Needing Updates
- New section of info on Platform for sample recruiting email

## Tasks
- [ ] Decide where on Platform this information should live, possibly on [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies)
- [ ] after information migrated mark the GH page as deprecated

## Acceptance Criteria
- [ ] Platform Website: has been updated to include sample recruiting email for card sort
- [ ] GH page [sample recruiting email for card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/sample-recruitment-email-template.md) has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
It looks like when this ticket was created it duplicated see also ticket [42506](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/42506)
Closing this one
