### ISSUE TITLE
Move Paperwork Reduction Act (PRA) guidance to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#42503]
## User Story
As a VFS researcher, I want all the important guidance I need in one location, that I know to be source of truth,  so I don't have to hunt for it and so that I know that I'm getting the latest guidance.

As Platform Governance Team, I want make sure researchers have access to important information on Platform, since it is source of truth for research guidance.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
Unmoderated research requires adhering to PRA, a legal requirement. There is [PRA guidance on VA github ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-paperwork-reduction-act.md), but if this guidance is important enough for VFS researchers to reference, it's important enough to be on Platform as the source of truth.

## Impacted Artifacts
[PRA guidance on VA github ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-paperwork-reduction-act.md)

## Tasks
- [x] Decide where on Platform this information should live (@naomimarcussen can help)
- [x] Create new page on Platform Website/Research
- [x] Mark the GH page as deprecated [following this guidance](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1397194753/Deprecate+a+page+in+GitHub)
- [x] Validate that all links in the new page are working. Any links that point to gh pages should be redirected to Platform Website (if applicable)
 - [x] share new PRA guidance in #research-ops channel in Slack

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams are able to refer to Platform Website for PRA information
- [x] VFS teams are redirected to Platform Website/research when visiting the deprecated PRA gh page
- [x] @naomimarcussen has peer reviewed and approved this ticket

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@naomimarcussen my [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2394030081/42503+-+Cheryl+Draft+-+Paperwork+Reduction+Act+PRA+guidance) is ready for your review I believe.  Please feel free to make any/all recommendations, and I will implement soonest.  I have validated all the links on the page.  Some of the links needed updating, and I have done that as well.

**Comment by CherylEvans** [comment]
@allison0034 Once Naomi has given her seal of approval, I will tag you for peer review.  :-)

**Comment by allison0034** [comment]
The draft page looks good. Can you link the PR for the deprecated GH page?

**Comment by CherylEvans** [comment]
@allison0034 According to the guidance for deprecating a page, I can't do the PR until I publish the page.  Now that you've given the thumbs up on the draft page, it will hopefully publish today.  Once I verify, I will post a link to the PR on here.

**Comment by CherylEvans** [comment]
@allison0034 The [new page](https://depo-platform-documentation.scrollhelp.site/research-design/paperwork-reduction-act-pra) has been published and I created a [pull request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/48008) with the deprecation message and link to new page.  Ready for your review. :-)

**Comment by allison0034** [comment]
@CherylEvans looks great and now I know how to deprecate a GH page lol

**Comment by CherylEvans** [comment]
@allison0034 Thank you for your review!  I followed the guidance, so it was pretty easy. lol.  Thank goodness for documentation! :-)

**Comment by CherylEvans** [comment]
Announcement made in Research-ops channel.
