### ISSUE TITLE
[FE] [STAGING APPT TOOL] Allow setting the "needs insurance review" flag on test patients

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#42518]
## User Story

As a CIE tester, I want to have a button to set the "needs insurance review" so that I can more easily test different check-in scenarios.

## Background

https://dsva.slack.com/archives/C022AC2STBM/p1654705163673209?thread_ts=1654101435.587749&cid=C022AC2STBM

## Tasks
- [x] Add APIs to get the insurance flag status and "unclear" the flag
- [x] Update mocks
- [ ] Update UI to allow seeing the current status and toggling between cleared and uncleared
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Per Shawn Adams, this is currently a "nice to have" but will become more important if we start offering insurance review or the like as part of the patient experience.

**Comment by acrollet** [comment]
From @shanemelliott :

Ok, if you send "R" for the second piece like:
```curl --location --request POST 'https://staging.vista-api.va.gov/api/v1/xrpc/xcte' \
--header 'Authorization: Bearer {{access_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
  "context" : "SDECRPC",
  "rpc" : "VTEXT ADD BUFFER",
  "jsonResult" : "FALSE",
  "parameters" : ["237","R"]
}'
```
It will reset the insurance.  Not intuitive to caall Add buffer to actually remove, but was the easiest.

**Comment by acrollet** [comment]
I took care of the back-end but wasn't able to get as far as the UI, I've discussed with @brianseek and @brdunfield and one of them will likely pick this up next week.
