### ISSUE TITLE
[FE] [STAGING APPT TOOL] Allow viewing/updating test patient mobile phone number

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#42519]
## User Story
As a CIO tester, I want to view/update the phone number associated with my test patient so that I can create check-in/pre-check-in links.

## Tasks
- [ ] User can view patient mobile phone number
- [ ] User can update patient mobile phone number
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
