### ISSUE TITLE
Add link to comparison chart on VR&E pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42531]
## Issue Description
Stakeholder Peter Granato asked us to link to a benefit.va.gov chart comparing different education benefits and rates somewhere prominently within VR&E. 

The link to add: https://www.benefits.va.gov/GIBILL/comparison_chart.asp#ctable

He asked if we could link to it either on the [main VR&E page](https://www.va.gov/careers-employment/vocational-rehabilitation/) or on the [VR&E eligibility page](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) where we mention Post-9/11 information. 

As background, he said that we should be linking to the table instead of creating content of our own because the table gets updated and edited often. 

We should review the table and determine where the best placement on VR&E should be and confirm with Beth before we make the updates in Drupal. 

## Tasks
- [x] Assess request and determine best placement (Aliyah)
- [ ] Review suggestion (Laura)
- [x] Get Beth's confirmation
- [x] Add new content and link in Drupal (Aliyah)
- [x] Edit changes (Laura)
- [x] Copyedit (Megan)
- [x] OCTO-DE review (Beth)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholder that changes are live (Randi/Laura)

## Acceptance Criteria
- [x] Link to table is live on the site

**Comment by aliyahblackmore** [comment]
Hi @bethpotts! 

I did a review of this and determined that it would not be best to put this on the main VR&E page because this information is more closely related to eligibility. Also, the links on the main page all lead to current VA pages and because this is a legacy link, it seems it would be best not to link this on a main page.  

It would be best to place this on the VR&E eligibility page!

Before deciding if the link would fit under the H2 "If I’m eligible for GI Bill benefits, can I get paid the Post-9/11 GI Bill subsistence rate for my VR&E program?" (that section mentions post Post-9/11 GI Bill information).  **A set of clarifying questions below**:

This legacy page with the chart instructs veterans to "Use the chart below to compare the education benefits available through the following programs." 

Because this chart lists multiple programs (i.e. Post-9/11 GI Bill, Montgomery GI Bill, etc.), would a veteran be going to this page to view and compare the benefits of different programs to know what benefits are available to them? **Or** would they only be viewing his page to see what VR&E benefits are available to them (assuming that this would likely be the case because the main page is specific to VR&E)? **Or**, lastly, would they only be viewing this page to see what Post-9/11 GI bill benefits are available to them (because the original stakeholder request does suggest linking it in the Post-9/11 GI bill section)? 

Thank you!

**Comment by aliyahblackmore** [comment]
Updating here that Beth replied to the above questions via Slack and should be linked under header "What kind of VR&E services can I get. I will add this in on Drupal and pass to Laura.

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you!  Beth has already reviewed/gave the okay for the placement of this. The link was placed on the VR&E eligibility page under the **"What kind of VR&E services can I get?"** and under the bullet point **"Post-secondary education and training at a college, vocational, technical, or business school"**

Preview link: 
http://preview-prod.vfs.va.gov/preview?nodeId=726

**Comment by RLHecht** [comment]
This link is now live. Closing ticket!
