### ISSUE TITLE
Data QA - Sitewide Homepage Search

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42539]
## Issue Description
This is an internal ticket for the data QA portion of the [Sitewide Homepage Search](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41512).

---
## Tasks
- [ ] Add QA table to this ticket for tracking.
- [ ] QA data

## Acceptance Criteria
- [ ] When data QA has been completed and signed off on for relaase.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathan-epstein13** [comment]
QA : VA Homepage | Ticket #41512 - Sitewide Search Dashboard (VA Homepage) |  
-- | -- | --
Highlights |   |  
Chart title | Assets | Pass / Fail
Successful searches | [Event Label = onsite-search-results-click/, Total events -  page is www.va.gov](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22onsite-search-results-click%22,0%5D%5D&_r.drilldown=analytics.eventLabel:onsite-search-results-click/) | 🟢 PASS
Search funnel | [Event Label = view_search_results/, Total events - page is www.va.gov/](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D,%5B0,%22analytics.eventLabel%22,%22EQ%22,%22view_search_results%22,0%5D%5D/) | 🟢 PASS
Search refinement rate | BigQuery metric (SUM(`refinement`) / count(distinct concat(`session_id`, `hit_number`))*1.0 | 🟢 PASS
  |   |  
Task Completion |   |  
Chart title | Assets | Pass / Fail
Search click rate | BigQuery metric/ custom metric  ((COUNT(DISTINCT CASE WHEN `event_label`= 'onsite-search-results-click' THEN CONCAT(`session_id`, `hit_number`) END)/COUNT(DISTINCT CASE WHEN `event_label` = 'view_search_results' THEN CONCAT(`session_id`, `hit_number`) END)) as search_click_rate) | 🟢 PASS
Clicks by position | BigQuery metric - CASE WHEN `search_results_position` <= 2 THEN '1st or 2nd'                                           WHEN `search_results_position` > 2 AND `search_results_position` <= 5 THEN '3rd - 5th'                                           WHEN `search_results_position` > 5 THEN '6th or more'                                    END as Click_rate_by_position, | 🟢 PASS
Results clicked | GA Metric |  Blocker
  |   |  
Ease of use (search abandonment) |   |  
Chart title | Assets | Pass / Fail
Searched sessions | [Sessions tab of report ](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/i7oh1eVtRKGdRuBIDIEyJg/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_r.tabId=2114/)|  Blocker
Abandoned sessions | BigQuery metric |  Blocker
Search abandonment rate | BigQuery metric |  Blocker
Abandonment rates by most common search terms | BigQuery metric |  Blocker
  |   |  
Ease of use (search refinement) |   |  
Chart title | Assets | Pass / Fail
Refinement rate | BigQuery metric - SUM(`refinement`) / count(distinct concat(`session_id`, `hit_number`)) | 🟢 PASS
Search sessions by number of refinements | BigQuery metric sum(refinement) as total_refinements,  ( CASE WHEN `total_refinements` = 0 then '0 refinements'        WHEN `total_refinements` = 1 then '1 refinement'        WHEN `total_refinements` = 2 then '2 refinements'    WHEN `total_refinements` > 2 then '3 or more'    END , Total sessions = COUNT(DISTINCT `session_id`) | 🟢 PASS (total sessions)
No results found | BigQuery metric (COUNT(DISTINCT CASE WHEN `results_returned` = 'No Search Results Returned' THEN CONCAT(`session_id`, `hit_number`) END)/COUNT(DISTINCT CASE WHEN `event_label` = 'view_search_results' THEN CONCAT(`session_id`, `hit_number`) END)) as No_results_found | 🟢 PASS
  |   |  
Findability |   |  
Chart title | Assets | Pass / Fail
Top pages viewed before searching | GA Metric |  Blocker
Total search users | [Users tab of report](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/i7oh1eVtRKGdRuBIDIEyJg/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_r.tabId=1147/) | 🟢 PASS
Avg. searches per user | BigQuery metric - COUNT(DISTINCT CASE WHEN `event_label` = 'view_search_results' THEN CONCAT(`session_id`, `hit_number`) END) / COUNT(DISTINCT `user`) | 🟢 PASS
Search users by device | [Device tab of report](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/i7oh1eVtRKGdRuBIDIEyJg/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_r.tabId=1147/) | 🟢 PASS
Top browsers types used to search | [Browser tab of report](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/i7oh1eVtRKGdRuBIDIEyJg/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_r.tabId=1147/) | 🟢 PASS

**Comment by michelle-dooley** [comment]
Adding [slack convo](https://dsva.slack.com/archives/C01S78V4AUA/p1655417793352449) for reference.

**Comment by jonathan-epstein13** [comment]
Task Completion|   |  
-- | -- | --
Chart title | Assets | Pass / Fail
Results clicked | BigQuery metric - selectsearch_result_chosen_title as results_chosen,  count(distinct concat(session_id, hit_number)) as total_eventsfrom `vsp-analytics-and-insights.vsp_sites.vw_search_last_week` where   search_scope = 'All VA.gov'  and event_label = 'onsite-search-results-click'  and previous_page in ('www.va.gov/','www.va.gov/index')-- Customize to spot-check different result totals  --and search_result_chosen_title = 'Manage your VA debt'  group by search_result_chosen_title  order by total_events desc | 🟢 PASS


</body>
</html>





Findability |   |  
-- | -- | --
Chart title | Assets | Pass / Fail
Top pages viewed before searching | BigQuery metric selectdate,previous_page,search_scope,count(distinct concat(session_id, hit_number)) as total_events,from `vsp-analytics-and-insights.vsp_sites.vw_search_last_week` where   search_scope = 'VA Homepage'  --and previous_page LIKE 'www.va.gov/search/%'    and event_label = 'view_search_results'  --and previous_page in ('www.va.gov/','www.va.gov/index')  --and search_result_chosen_title = 'VA travel pay reimbursement'group by date,previous_page,search_scopeorder by date desc; | 🟢 PASS

**Comment by jonathan-epstein13** [comment]
Ease of use (search abandonment) |   |  
-- | -- | --
Chart title | Assets | Pass / Fail
Searched sessions | BigQuery metric - selectCOUNT (DISTINCT `session_id`) as search_sessions,from `vsp-analytics-and-insights.vsp_sites.vw_search_last_week` where   search_scope = 'VA Homepage'  and event_label = 'view_search_results'  order by search_sessions desc | 🟢 PASS

**Comment by michelle-dooley** [comment]
@chloedotbrown thanks for identifying and fixing the ETL. I do not think it warrants a communication as long as the dictionary is in sync.  If we get questions then we can communicate it out but I don't think we will.

@jonathan-epstein13 just let us know once you have been able to complete this last bit of QA

**Comment by jonathan-epstein13** [comment]
@michelle-dooley the last QA that I need help with was the abandonment section and @chloedotbrown was able to help with that BQ side of things. so we are good to go. I can post the entire QA-GA to the [ticket#41512 ](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/department-of-veterans-affairs/va.gov-team/41512) What are your thoughts @chloedotbrown ?
