### ISSUE TITLE
Profile | Sprint 77 | June 29 - July 12

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42538]
## PTO/OOO/Unavailable

- **Christina**: July 4 -12
- **Sharon**:  July 1, July 5 -7 
- **Tom**: 
- **Mark**: July 7-8
- **Samara**: July 5 - 6
- **Adam**: 
- **Liz**:  PTO July 8, running My VA UAT July 1-7

## Sprint Priorities
- Complete final work for Personal Information Revisions
- Roll-out Change Address messaging

## For Review

- [x] [Epic] Profile alert UX improvements #30735 (Adam to review)
- [x] New Forms Library (Sharon will work with Mark to create a ticket for a POC)

### PM - Sharon
- [x] #43682 Epic to capture follow-up from UAT

### FE - Adam

- [x] #34290 Button url update
- [x] #40351 Update links

### BE - Tom
- [x] #43654 Remove FF 

### BE - Tom
- [x] #43755 GA support for endpoints

### PM - Sharon
- [x] #42090 Launch readiness/phased roll-out

### FE - Adam

- [x] #42494 Release to 25% 
- [x] #43613 Release to 50% (targeted 7/7)
- [ ] #43614 Release 100% (targeted 7/11)

### PM - Sharon
- [ ] #42706 Con't prep for staging review cycle work (release plan, Privacy review, QA etc) - carry-over
- [ ] #42265 Set up dashboard analytics carry-over

### FE - Mark
- [x] #43632 Update GA tags

### FE - Adam
- [x] #43291 Bug

### Design - Christina
- [x] #42965 Research sessions (carried over to next sprint)

### Design - Liz
- [x] #43489 Default opt-in discovery

### BE - Tom
- [x] #43491 Default opt-in indicator discovery

### FE - Adam
- [x] #43206 Update list of facilities that have prescription SMS texts (awaiting validation)

### PM - Sharon
- [x] #43623 Analytics worksheet

### FE - Mark
- [x] #43019 FF documentation
- [x] #43018 Documentation
- [ ] #41529 Update DD screens with "save" message
- [x] #36951 Update adt'l component

### BE - Tom
- [x] #11837 documentation - add error codes for dd

### Design - Liz
- [x] #43750 Contact Info documentation (con't to Sprint 78)

**Comment by Samara-Strauss** [comment]
### Address Change messaging

@SKasimow we will likely be able to launch this to 100% this sprint. We can do 25% today, 50% when I'm back on Thursday, and if all looks good, 100% the following Monday.

### Military info

Can you please create a ticket for the UAT so we can track comments and results? Otherwise, there's no record that we did this.

**Comment by SKasimow** [comment]
@Samara-Strauss - #43609 for Military internal UAT.

If all goes well we'd be able to release Change Address messaging to 100% on Tues 7/5 (Mon is holiday).

**Comment by SKasimow** [comment]
Got it - added the dates in epic ^
