### ISSUE TITLE
[FE] Add Round 2 Spanish Translation Key/Values

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42545]
## Question
How are we going to get these into the product and be able to show for final approval to the State Department without having them viewable in Production?

## Tasks
- [ ] [FE] Add [Round 2 Spanish Translations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/LS-2022-0117400-SPA-FINAL_check-in-translations-round-2.json)
- [ ] Generate screenshots for workflow documents to submit to the State Department
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Draft PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/21632

I'll work on generating screenshots tomorrow morning when the review environment is available.

**Comment by acrollet** [comment]
@loripusey @niradatta1 here are the spanish round 2 screenshots - please let me know if any additional screenshots are needed:

[Round 2 screenshots](https://app.zenhub.com/files/133843125/3151dcdb-e4b3-496d-8d7c-326a2cc2ac5c/download)

**Comment by acrollet** [comment]
I've documented my process for generating the screenshots here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations
