### ISSUE TITLE
VA Notify - Internal Ticket for Tracking 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42541]
## Issue Description
Internal team ticket for tacking VA Notify dashboard update request.

Data Lead:  Julie
Domo Lead:  Pavan
Support:  Chloe & Michelle

---
## Tasks
- [ ] _What work is necessary for t

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pavanhothi** [comment]
Added new landing page URLs to BQ view per the [KPI Dashboard Product Details](https://docs.google.com/spreadsheets/d/1tci1KS0WnpHX2cws4TeCbctqZyAaKYWVAAaxW7QRvP4/edit#gid=1310190768) doc for ticket [#42378](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42378). Data is updated in Domo now as well. Created new card for the new campaign landing  page. Will add to dashboard after @jonathan-epstein13 is able to do a QA on the data and card.

**Comment by pavanhothi** [comment]
@jonathan-epstein13 FYI new landing page campaign name is "10-10 EZ Resume Application"

**Comment by jonathan-epstein13** [comment]
Here is the [GA segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220603&_u.date01=20220607&_.useg=usermI5NS-jwRNiwqRQVfNhzvg&overview-graphOptions.primaryConcept=analytics.totalVisitors&overview-graphOptions.clearCompareConcept=true/) to correlate to the [card](https://va-gov.domo.com/kpis/details/1741264313) @pavanhothi created. Looks to line up pretty well. @jennaouellet maybe you can take a quick look to see if this segment makes sense. (I know I see a total of 51 users in GA vs 52 (unique) users in Domo in the period of 1/3/22-1/7/22.)

Couple things I noticed:

- The campaign(s) attached to the URL (https://va.gov/health-care/apply/application/resume) are _not_ labeled '10-10 EZ Resume Application" in GA, as you can see [here](https://analytics.google.com/analytics/web/?authuser=0#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20220603&_u.date01=20220607&_.useg=usermI5NS-jwRNiwqRQVfNhzvg&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.campaign&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fhealth-care~2Fapply~2Fapplication~2Fresume~2F/), so maybe we need to reach out in regards to that? (I know the campaign is in BQ, so we have that covered.)
- Also I noticed the URL https://va.gov/my-va/ was added to the [VANotify google doc](https://docs.google.com/spreadsheets/d/1tci1KS0WnpHX2cws4TeCbctqZyAaKYWVAAaxW7QRvP4/edit#gid=1310190768) wondering if this was a landing page also attached to this specific campaign or it was for something else?

**Comment by pavanhothi** [comment]
Thanks for the feedback @jonathan-epstein13! 

- So the campaign name ("10-10 EZ Resume Application") attached to the new [URL](https://va.gov/health-care/apply/application/resume) in Domo was purposely named that way by me by making an edit in the BQ view. This was done because prior to that change, we were getting two different campaign names populating for the same new URL, the ones which you pointed out are showing up in [GA](https://analytics.google.com/analytics/web/?authuser=0#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20220603&_u.date01=20220607&_.useg=usermI5NS-jwRNiwqRQVfNhzvg&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.campaign&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fhealth-care~2Fapply~2Fapplication~2Fresume~2F/). So I edited the campaign name for consistency, and chose this specific name since that was what they had the form name listed as in the [Google doc](https://docs.google.com/spreadsheets/d/1tci1KS0WnpHX2cws4TeCbctqZyAaKYWVAAaxW7QRvP4/edit#gid=1310190768). I'll comment on their ticket to ask and confirm if this campaign name works for them. 
- I also noticed the second URL they had listed on the Google doc, which I found to be completely unrelated to the new Form/campaign. My understanding was that it is a new URL to be added, but it is not attached to this new campaign. I added it in the BQ view also, just did not attach it to the new campaign name if that makes sense. I can comment on their ticket to inquire and confirm this as well. 
- I can experiment with a new single larger graph in Domo so that we don't need to keep adding all these new cards to that section. I will update again once I have something created for you to take a look at and QA.

**Comment by pavanhothi** [comment]
Just got a reply back on the main ticket. Looks like they are good with the campaign name we have created. And looks like the second URL was related to a different campaign as we had thought. 
Will update now once I create a new single larger graph card.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/42378#issuecomment-1150464628

**Comment by pavanhothi** [comment]
@jonathan-epstein13 just shared out the new single [card](https://va-gov.domo.com/kpis/details/1119696283) I created with all five (four current and one new) of the the VANotify landing pages on it. Please let me know what you think. Thank you!

**Comment by michelle-dooley** [comment]
@pavanhothi - I like the all in one graph approach I guess my only struggle is when there is no landing page filter selected it is hard to read with such different scales between them. 
With that said I don't know how often or at all they will view all together or if they will only be looking by campaign filter which is a much easier to read view. 

@chloedotbrown - what do you think?  

@jonathan-epstein13 - are we good with QA or do we still need @jennaouellet to weigh in?

**Comment by jonathan-epstein13** [comment]
@michelle-dooley working on making sure the landing page section matches up to what is in GA. I might need @jennaouellet to just confirm I have the correct segments in place. The design QA is finished and the new card with the filter campaign runs smoothly.

**Comment by jonathan-epstein13** [comment]
@michelle-dooley working on making sure the landing page section matches up to what is in GA. I might need @jennaouellet to just confirm I have the correct segments in place. The design QA is finished and the new card with the filter campaign runs smoothly.

**Comment by jonathan-epstein13** [comment]
**GA-QA (Landing Pages)**
Findability |   |  
-- | -- | --
Chart title | Assets | Pass / Fail
Claims & Appeals - VANotify users | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS
Manage VA Debt - VANotify users | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS
VA Profile - VANotify users | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS
Add or Remove Dependents - VANotify users | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS
Apply for VA Healthcare | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS
Avg. session per user for VANotify source | BigQuery metric | 🟢 PASS
Bounce rate for VANotify sessions | [Custom segment](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20220605&_u.date01=20220611&_.useg=usermI5NS-jwRNiwqRQVfNhzvg,userQDwZeoJwS0uB3OGquwqDCA,userSdxbnk5lR1a5zHVK1dySdg&overview-graphOptions.clearCompareConcept=true&overview-graphOptions.primaryConcept=analytics.bounceRate) | 🟢 PASS

**Comment by michelle-dooley** [comment]
@jonathan-epstein13 @chloedotbrown @pavanhothi - so is this one complete then, are we ready to let the VANotify team their updates have made?
