### ISSUE TITLE
Certificate of Eligibility | Add Cypress e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42549]
## Value Statement

**_As a_** frontend developer, 
**_I want to_** include end-to-end tests for the Certificate of Eligibility form
**_So that_** I can rest assured that the form works from start to end and is accessible

## Background context

The Certificate of Eligibility form does not include any end-to-end testing. It usually isn't added until after the frontend work has completed and all endpoints have been established, but we can still add the tests prior to production release.

## Tasks

- [ ] Add Cypress e2e tests for COE
- [ ] Include accessibility checks in tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
