### ISSUE TITLE
[bug] Higher-Level Review | Submission Failures

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#42547]
## What happened?
Veterans are unable to successfully submit a request for a higher-lever review. They are experiencing a variety of issue with accessing and submitting the form, including:

- "Page unresponsive. You can continue to wait for the page to become responsive or exit the page."_
- The form is not displaying as an option to complete. 
- A user cannot access the form from his CAC.
- The page freezes frequently.

Both the **Kimberely Daniels** (Contact Center) and **Kelly Lein** (Lighthouse team) have received feedback about this issue.

## Specs
- Browsers: Chrome, Edge
- Devices: Desktop, Laptop, Mobile

## Tasks

- [x] Get PII from Kimberley
- [x] Confirm if we can replicate

## Open Questions
- Are the submission issues a result of API outages?
- Are there any reports that show outages or failed submissions?

## Acceptance Criteria
- [x] Veterans are able to access form 20-0996 on all compatible browsers and devices.
- [x] Veterans are able to submit form 20-0996 on all compatible browsers and devices.
- [x] If the system returns a timeout error, Veterans are shown an error message with clear explanation and instructions.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

## Fix
Some users in production have contestable issues that are marked as failed DTA(Duty to Assist) records.  The DTA contestable issues records are missing expected fields and were causing the front end HLR javascript code to enter an infinite loop on the HLR introduction page, essentially, the page is stuck and the users can't get past it and are unable to complete the rest of the form's pages and they are unable to submit the HLR.  The front end added code to ignore the DTA contestable issues with this ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44803

**Comment by saderagsdale** [comment]
Additional notes from Kimberely Daniels (Contact Center team):

> Case
> 
> 07135169
> 
> Case Notes
> 
> Veteran is calling in because he is trying to submit a high level request review but he is not able too. It freezes as it is loading . It wont let him click anything not will it finish loading.
> veteran has tried using his mobile device and his computer. veteran did clear and cache and cookies.
> 
>  
> 
> Case
> 
> 07160117
> 
> Case Notes
> 
> Veteran is calling in because he is trying to submit a high level request review but he gets stuck on certain spots.
> Veteran goes through a couple of questions asked and somehow it takes him back to the homeless question.
> Veteran is using a computer and google chrome as his browser.
> 
>  
> 
> Case
> 
> 07438249
> 
> Case Notes
> 
> PII Verified. Veteran called in concerning not being able to apply for Higher Level Review when the Veteran starts the process for the website to connect his previous claims. The Veteran receives the error message "Page unresponsive you can continue to wait for the page to become responsive or exit the page." The Veteran has tried to apply at different times over the last three days. Escalating to Tier 2 tech support for further assistance [XXXXXXXXX@aol.com](mailto:XXXXXXXXX@aol.com)
> 
>  
> 
> Case
> 
> 07663125
> 
> Case Notes
> 
> the veteran cannot submit a higher level review due to the error "page unresponsive"
> 
>  
> 
> Case
> 
> 07442281
> 
> Case Notes
> 
> The Veteran has been trying to submit a Higher Level Review and he has tried to clear cookies and different browsers. When he tries to select the option nothing happens. He has been trying for a couple of weeks. He is wondering if this is a known issue.
> 
>  
> 
> 
> Case
> 
> 07301601
> 
> Case Notes
> 
> caller is logging in with a CAC, and is checking his claim or appeal status, as he checks the appeal process, and is requesting a higher level review, and he is requesting the higher level review online, and when he does that the he gets a blue box but he cant click it to start the review. He has tried edge and chrome, and is on a government computer.
> 
>  
> 
> Case
> 
> 07084207
> 
> Case Notes
> 
> Veteran is trying to fill out the form 20-0996
> for a higher level review but cannot access it. He is able to login but when he choose the form 20-0996 to fill it out on the website will not come up. Tried to clear cache and cookies and tried his computer, phone and iPad all with the same results.
> Escalated to Tier 2
> 
>  
> 
> 
> Case
> 
> 07584298
> 
> Case Notes
> 
> Veteran called about trying to file a higher level review on [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) but when trying to access the application it freezes. Veteran states he has been trying for over 2 weeks and still receives the issue. Advised to clear cache and cookies but he received an error stating page is unresponsive. Escalated tier 2.
> 
>  
> 
> Case
> 
> 07248878
> 
> Case Notes
> 
> caller is stating that he cannot get past the phone number on the higher level review paperwork he is filling out online, it will not let him go forward, chrome is the browser and history has been cleared.
> 
>  
> 
> 
> Case
> 
> 07162237
> 
> Case Notes
> 
> Veteran calling regarding getting a higher level review on [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) the page pulls up but the form does not. I walked the Veteran through finding the form 20-0996 for a higher review. When we got to the page it doe snot load the online tool. I walked the Veteran through how to clear his cache and cookies. I then had the Veteran try to log into [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) and use the Online tool again and it still just kept spinning
> 07135169
> 
> Case Notes
> 
> Veteran is calling in because he is trying to submit a high level request review but he is not able too. It freezes as it is loading . It wont let him click anything not will it finish loading.
> veteran has tried using his mobile device and his computer. veteran did clear and cache and cookies.
> 
>  
> 
> Case
> 
> 07160117
> 
> Case Notes
> 
> Veteran is calling in because he is trying to submit a high level request review but he gets stuck on certain spots.
> Veteran goes through a couple of questions asked and somehow it takes him back to the homeless question.
> Veteran is using a computer and google chrome as his browser.
> 
>  
> 
> Case
> 
> 07438249
> 
> Case Notes
> 
> PII Verified. Veteran called in concerning not being able to apply for Higher Level Review when the Veteran starts the process for the website to connect his previous claims. The Veteran receives the error message "Page unresponsive you can continue to wait for the page to become responsive or exit the page." The Veteran has tried to apply at different times over the last three days. Escalating to Tier 2 tech support for further assistance [XXXXXXXXX@aol.com](mailto:XXXXXXXXX@aol.com)
> 
>  
> 
> Case
> 
> 07663125
> 
> Case Notes
> 
> the veteran cannot submit a higher level review due to the error "page unresponsive"
> 
>  
> 
> Case
> 
> 07442281
> 
> Case Notes
> 
> The Veteran has been trying to submit a Higher Level Review and he has tried to clear cookies and different browsers. When he tries to select the option nothing happens. He has been trying for a couple of weeks. He is wondering if this is a known issue.
> 
>  
> 
> 
> Case
> 
> 07301601
> 
> Case Notes
> 
> caller is logging in with a CAC, and is checking his claim or appeal status, as he checks the appeal process, and is requesting a higher level review, and he is requesting the higher level review online, and when he does that the he gets a blue box but he cant click it to start the review. He has tried edge and chrome, and is on a government computer.
> 
>  
> 
> Case
> 
> 07084207
> 
> Case Notes
> 
> Veteran is trying to fill out the form 20-0996
> for a higher level review but cannot access it. He is able to login but when he choose the form 20-0996 to fill it out on the website will not come up. Tried to clear cache and cookies and tried his computer, phone and iPad all with the same results.
> Escalated to Tier 2
> 
>  
> 
> 
> Case
> 
> 07584298
> 
> Case Notes
> 
> Veteran called about trying to file a higher level review on [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) but when trying to access the application it freezes. Veteran states he has been trying for over 2 weeks and still receives the issue. Advised to clear cache and cookies but he received an error stating page is unresponsive. Escalated tier 2.
> 
>  
> 
> Case
> 
> 07248878
> 
> Case Notes
> 
> caller is stating that he cannot get past the phone number on the higher level review paperwork he is filling out online, it will not let him go forward, chrome is the browser and history has been cleared.
> 
>  
> 
> 
> Case
> 
> 07162237
> 
> Case Notes
> 
> Veteran calling regarding getting a higher level review on [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) the page pulls up but the form does not. I walked the Veteran through finding the form 20-0996 for a higher review. When we got to the page it doe snot load the online tool. I walked the Veteran through how to clear his cache and cookies. I then had the Veteran try to log into [VA.gov](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fva.gov%2F&data=05%7C01%7C%7C9f684d0d542c418a695508da4974af6a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637903062747611973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=94S07lCANl9sz%2FwSv3z9xDRK%2BdFXQIv9GdyQcQGjNwM%3D&reserved=0) and use the Online tool again and it still just kept spinning

**Comment by saderagsdale** [comment]
Additional notes from Kelly Lein (Lighthouse team):

OAR has been working with Veterans on feedback from their claim experience and we have gotten comments referencing issues that Claimants are having with the va.gov website. The comments below have been from the past month and a half. These come directly from the survey calls. The calls are broken up into two categories: Navigation and Functionality. The functionality complaints are where people had issues submitting claims and the others about navigating the website.

**SURVEY Comments**

- Website function: “When I filed for the HLR the form I tried to submit the information online.  When I went to submit, it went into a spin and stated it could not be processed I did it three times. I ended up having to fax in the form.”

- Website Function: Claimant stated he tried to submit his HLR claim and it froze. He went on daily to check and he was finally able to submit it after three weeks.

- Website Function: "The form was just not user friendly." Veteran then intimated his older claims and the process. I tried to load information. I requested an activation code when I signed in. It took 6 hours for me to receive the activation code to my cell phone." 

- Website Navigation: Veteran stated his attorney helped him file. Veteran intimated he went on the website to see the process and stated it took him some time to find the information he needed in regards to the process. Even when he found it, he intimated he still did not have a clear understanding of what to expect.

- Website Navigation: The website is not set up as optimal as he would like. He recommended following the ebenefits website template.

- Website Navigation: “Hard to find the information on the website”

- Website Navigation: “Basically on the website it's a bunch of information,  so you have to dig for it. I think you should have something telling Veterans what to look for.”

- Website Navigation: “At first I went on the website and couldn't find the information. There are no resources in my community so I started asking Veteran friends. The Higher-Level Review looked like the best option so I went with it. I then got in touch with a VSO and they explained everything to me."

- Website Navigation: “My complaint is rather mundane. I think the website needs a better interface.”

- Website Navigation: “Make the website a little more user-friendly."/ Veteran reiterated the website and it's functionality/ “I think make the information more easily accessible on the website, took some time to find what I needed."

**Comment by Mottie** [comment]
I took a quick look at this ticket. There are actually 10 cases (20 show above includes duplicates), I believe most of these issues may not be a problem since we just made a change that removes older code, and the "we couldn't load your issues" alert no longer exists.

**Comment by saderagsdale** [comment]
@Mottie A few diagnostic questions. Should we...

1. Ask for more info from either Kelly or Kimberley?
2. Keep this open until we hear from Kelly and Kimberley on the advice you shared? 
3. Ask for any logging from Lighthouse?
4. Are there completed code fixes we can attach to this ticket?
5. Are there new code fixes we can implement resolve to address these things?

Just want to make sure we've explored it thoroughly before closing.

**Comment by Mottie** [comment]
I don't know if the change that was added today will fix the problem. Michel will help us out tomorrow and look at the backend and logs to see if there is anything we can find and fix.

1. Ask for more info from either Kelly or Kimberley? Let's wait and see
2. Keep this open until we hear from Kelly and Kimberley on the advice you shared? Yes please
3. Ask for any logging from Lighthouse? Let's keep this open for now & reach out if we find something they can assist us with.
4. Are there completed code fixes we can attach to this ticket? I'm not sure if the code fix I am referencing (removal of HLR v1 code) is related, but it is possible
5. Are there new code fixes we can implement resolve to address these things? We need to figure out the problem first

**Comment by Mottie** [comment]
Continuing investigation on other HLR failures found on the backend. Most of the submission failures don't include enough data, so Michel is going to send me data on a few and I'll test them to determine the problem.

**Comment by Mottie** [comment]
Investigating failures is taking longer than expected. Our backend engineer is not able to share the data with me. We are no longer permitted to use Keybase, and sending the data in a VA.gov email as text or as an attachment doesn't allow copying that over on to my work computer. We're going to need to redact the PII before sharing it by other means, and that takes a while.

**Comment by saderagsdale** [comment]
@Mottie can you add a severity to this based on the number of users impacted?

**Comment by Mottie** [comment]
@michelpmcdonald and I discussed this. Last time we checked (about a week ago), we haven't seen any new issues impacting users. Michel thinks we should keep this high on our priority list (sev-1), but we're going to revaluate the submission problems first thing in the morning, and then make a determination.

**Comment by michelpmcdonald** [comment]
On the backend, not seeing any new issues related to HigherLevelReviews.show in Personal Information Logs, lowing to sev3.

**Comment by saderagsdale** [comment]
@Mottie @michelpmcdonald what is the recommended course of action for this ticket? Can we close this?

**Comment by michelpmcdonald** [comment]
@saderagsdale I think we should reach reach out to the contact center Kimberely Daniels and ask if there are any new reports in the last week.  We were not able to reproduce, but we attempted a few fixes to what we thought might be causing the issue...

**Comment by Mottie** [comment]
I'd like to hear from @Kimberley2019 before closing this ticket.

**Comment by saderagsdale** [comment]
Requested PII on 7/18 in the thread linked above.

**Comment by Kimberley2019** [comment]
@saderagsdale I sent a VA email with the requested information.  Please confirm receipt.

**Comment by saderagsdale** [comment]
@michelpmcdonald @Mottie Hey both - Kimberley sent over PII related to this ticket yesterday. Was the info she shared the right data to help you diagnose the root cause of this issue?

**Comment by Mottie** [comment]
> I sent a VA email yesterday (7/18) with the requested information. Please confirm receipt.

We got the emails. I've included @jerekshoe in the claim status tool related tickets.

**Comment by michelpmcdonald** [comment]
@Kimberley2019 @saderagsdale I have not received any va emails that reference the cases listed in this ticket.

I did find an email for a case that seems to be the same one(frozen HLR page), it is case 07845494.

We did find the issue for case 07845494(fix on the way soon), but I need more similar cases, the cases listed above seem to fit the bill, so someone please send me pii(icn is great) va emails for the cases this ticket references so we can confirm.

**Comment by michelpmcdonald** [comment]
@Kimberley2019 - I think we solved this one.....can someone ask the vets that reported this issue to try again ?
Here is my consolidated list of cases sourced from this ticket and the va emails sent:

Cases sourced from this ticket's description, these all seem to sound  like the user is stuck on the HLR introduction page and their issues should be resolved:
07135169, 07160117, 07438249, 07663125, 07442281, 07301601, 07084207, 07584298, 07162237, 07135169, 07438249, 07663125, 07442281, 07301601, 07084207, 07584298, 07162237

Cases sourced from emails, these were not originally included in this ticket:
07845494, 
07260366 and 07163832(sam user, email refs both cases)
Email that has no case#, how do we ID ?????? email sent at 07/20/2022 3:11 PM initials CWH
07485958
07845494
07771984

These(ticket) cases are **NOT** related to the fix as far as I can tell(user is getting past introduction page):

07248878 - caller is stating that he cannot get past the phone number on the higher level review paperwork

07248878 - caller is stating that he cannot get past the phone number on the higher level review paperwork he is filling out online, it will not let him go forward, chrome is the browser and history has been cleared.

07160117 - Veteran is calling in because he is trying to submit a high level request review but he gets stuck on certain spots.
Veteran goes through a couple of questions asked and somehow it takes him back to the homeless question.

**Comment by Kimberley2019** [comment]
I will review the information above and report back any findings.

**Comment by Kimberley2019** [comment]
@michelpmcdonald the information you need:

- Email that has no case#, how do we ID ?????? email sent at 07/20/2022 3:11 PM initials CWH
                               - Case 07629732

**Comment by Kimberley2019** [comment]
The cases below have been contacted asking if their issue has been resolved.  Asked callers only to respond if they are NOT able to complete their task.  Salesforce cases have been updated with the email that was sent.
07135169, 07160117, 07438249, 07663125, 07442281, 07301601, 07084207, 07584298, 07162237

From: VA Technical Support
 Sent: Monday, August 1, 2022 12:26 PM
 Subject: VA.gov Benefits - HLR Issues DO NOT REPLY ALL
 Importance: High

**Comment by saderagsdale** [comment]
@Mottie @michelpmcdonald Do we roll this into the next sprint or take a different action with this ticket?

**Comment by Mottie** [comment]
I vote we close it and open a new ticket if the problem persists.

**Comment by saderagsdale** [comment]
@Mottie Go for it.
