### ISSUE TITLE
Procure new platform-api subdomain(s)

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#42553]
## Product Outline
[CIT Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)

## High Level User Story/ies
As a developer, I need to procure the new *platform-api.va.gov subdomain(s) so I can prepare the pathways necessary to decouple vets-api from Lighthouse.

## Hypothesis or Bet
If we procure the new *platform-api.va.gov subdomains, teams that use vets-api as an endpoint can begin testing and using them in their respective environments (dev, staging, sandbox, and production.)

## OKR
The *platform-api.va.gov subdomains have been procured and enabled for handoff to use in all environments.

### What must be true in order for you to consider this epic complete? 

- [x] *platform-api.va.gov subdomains submitted to VA Domain Registry.
- [x] *platform-api.va.gov subdomains submitted to ESECC. 
- [x] Internal DNS configured for all *platform-api.va.gov subdomains.
- [x] TLS/SSL certificates purchased for all *platform-api.va.gov subdomains.
- [x] ESECC approval.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by alwerner** [comment]
Closing as complete.
