### ISSUE TITLE
Conduct Research on Confluence Exports

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#42564]
## Issue Description
There are a few issues that we need to research to provide the best possible product to VFS teams. Namely, does Confluence have any expanded capabilities to interact with the displayed data?

---
## Tasks
- [ ] Research if there is a way to 'filter' the columns or products on the product list
- [ ] IF YES - Is there a way to define presets and link them on a page, to have a set of links for various use cases on a single page

## Acceptance Criteria
- [ ] We have a clear answer on what is possible for both research tasks

**Comment by rsmithadhoc** [comment]
For answering _"does Confluence have any expanded capabilities to interact with the displayed data?"_, the answer is "No, not really" but I provided a few other options on [Research on Confluence Exports](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2224422942/Research+on+Confluence+Exports).

**Comment by pjhill** [comment]
The Confluence plugin marketplace is lovely, but the idea of [paying 60-120 bucks](https://marketplace.atlassian.com/apps/27447/table-filter-and-charts-for-confluence?tab=pricing&hosting=cloud) a month for our userbase to have access to filterable tables is probably a non-starter.

**Comment by pjhill** [comment]
I think we may be going with [Option 2](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2224422942/Research+on+Confluence+Exports#Options-considered), but this will take some discussion. Thanks for the write-up of the comparison -- this is awesome!
