### ISSUE TITLE
Create My VA Redirect feature flag

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42578]
## Issue Description
Create a Flipper feature flag that will be used on the FE to control the redirect to My VA page

## Tasks
- [x] Create the feature flag `my_va_redirect` in vets-api
- [x] Create the feature flag `my_va_redirect` in vets-website

## Acceptance Criteria
- [x] Visiting the `/flipper/feature` in vets-api displays the `my_va_redirect` flag
