### ISSUE TITLE
Modify the AuthApp for the My VA Redirect work

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42579]
## Issue Description
This body of work will modify the AuthApp component to control the redirect under the appropriate conditions:
- If user is on the homepage and the `my_va_redirect` flag is enabled, redirect user to `/my-va` endpoint
- If user is on any other page besides the homepage, redirect user normally in the same flow (aka redirect to whichever page they were on before sign in)

## Tasks
- [x] Ensure above requirements are created in code

## Acceptance Criteria
- [x] Verify redirects on the homepage when the feature toggle is enabled, redirects to My VA page
- [x] Verify redirects on any other page besides the homepage, redirect as appropriate
