### ISSUE TITLE
Add Collaboration Cycle Office Hours to General Orientation slide deck

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42574]
## User Story
As a new VFS team member, I want to be made aware of the Collaboration Cycle office hours so that I can attend if I have a question about Collaboration Cycle.

- Intended Audience: VFS teams
- Desired Outcome: CC office hours referenced in General Orientation slide deck
- Due Date: 

## Description
The Collaboration Cycle office hours are not widely attended. It is assumed that many VFS team members are not aware of the office hours. If we add the Collaboration Cycle office hours to the General Orientation slide deck when we initially communicate Collaboration Cycle, then VFS teams will be more likely to attend.

## Artifacts Needing Updates
[General Orientation for VA.gov Platform - slide deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit?usp=sharing)

## Tasks
- [ ] Add a slide with details on the Collaboration Cycle office hours

## Acceptance Criteria
- [ ] VFS teams now learn of the Collaboration Cycle office hours in the General Orientation session
---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
@chaseakirby this is complete. Check out the deck for review, slide 47

**Comment by chaseakirby** [comment]
@shiragoodman Slide looks good to me! I like the adding of the slack support workflow as well.
