### ISSUE TITLE
[Design] MyHealth - Secure Messaging - Design unauth FAQ page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42587]
## Tasks
- [ ] Design unauth FAQ desktop and mobile pages
- [ ] Update PO and PM on Slack when ready to review
- [ ] Add link to mockups to this ticket.

## Acceptance Criteria
- [ ] Design unauth FAQ desktop and mobile pages
- [ ] Update PO and PM on Slack when ready to review
- [ ] Add link to mockups to this ticket.

**Comment by MarciMcGuire** [comment]
@mpeterz when you have a chance would you mind adding an estimate to this ticket?  Thank you!

**Comment by mpeterz** [comment]
I designed the unauth Messages FAQs pages for desktop and mobile, so they are done except for content, which is [#42428](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42428).
