### ISSUE TITLE
Collaboration Cycle for Auth Exp My VA -- My VA Redirect

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42582]
### VFS team name
Authenticated Experience My VA

### Product name
My VA

### Feature name
My VA Redirect

### GitHub label for product
my-va-dashboard, my-va-redirect

### GitHub label for feature
my-va-redirect

*Per conversation with @Samara-Strauss @ajakabcin and @shiragoodman on 6/9/2022 at 2:30pm ET, it was determined that the Design Intent and Midpoint Review touchpoints would not be necessary for this initiative as there are no design changes. 

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?
week of 6/13

### Will your work result in visible changes to the user experience?
Yes

### Are you doing research with VA.gov users?
No

### Will your work involve changes to...
Other

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?
Yes

### Do you need to capture any additional analytics or metrics?
No

### Product outline
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-redirect#my-va-redirect-initiative-brief

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.
- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below
- [x] IA intake request: #42634

</details>

### Contact Center Review
**NOTE: We started this initiative prior to the transition to the new collab cycle process, so our contact center review ticket can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45091**

<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
**NOTE: We started this initiative prior to the transition to the new collab cycle process, so our staging review ticket and all artifacts are linked here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45379**
<details open>
  <summary>Toggle Staging Review</summary>
 
##### VFS actions 
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Add or update all requested artifacts below **at least four days before** the scheduled Staging Review
  
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- Release plan with the "Planning" sections completed:              
- Staging URL and staging test user information:                   
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**QA artifacts**

[Learn more about QA artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-artifacts.1906999390.html)

- Product test cases/test plan in TestRail with test execution logs: 
- [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12): 
- [Summary (Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14): 
  
**Accessibility artifacts**
  
- [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc):  **(Preferred)** OR, 
- Document in your product folder that indicates all required checks from the [how to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) doc are complete: 
- List of known issues with links to tickets (when applicable)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [X] Meeting date/time: Aug 19, 2:00 pm et
- [x] Create feedback tickets and link to this epic
  - [ ] Design feedback provided
  - [ ] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [x] Respond to feedback tickets
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] Update the VFS product information section with the product’s launch date and production URL after it has gone live

</details>

### Privacy, Security, Infrastructure Readiness Review
**NOTE: We started this initiative prior to the transition to the new collab cycle process, so our privacy and security readiness review ticket and all artifacts are linked here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/545**
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/545

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by ajakabcin** [comment]
A few additional notes to add:

1. While we do not plan to perform any user research on this feature, we do plan to perform UAT.
2. We are partnering with the Identity team on this work who will be implementing the redirect for us and setting up the feature flag for us to do a phased rollout when the time comes.

**Comment by AGarcia-Clarity** [comment]
👋  @ajakabcin 

PRs are up from the Identity team, just waiting on approval & merging
- [Redirect to My VA on vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/21378)
- [Addition of `my_va_redirect` feature flag](https://github.com/department-of-veterans-affairs/vets-api/pull/10057)

**Comment by ajakabcin** [comment]
thank @AGarcia-Clarity! we're so excited, looking forward to checking it out on staging soon!

cc @Samara-Strauss @ericasauv09

**Comment by Samara-Strauss** [comment]
Great, thank you @AGarcia-Clarity ! Let us know when that work is in staging. And it looks like everything is behind a feature flag, so there is no concern about this going to prod prematurely, correct?

**Comment by AGarcia-Clarity** [comment]
> Great, thank you @AGarcia-Clarity ! Let us know when that work is in staging. And it looks like everything is behind a feature flag, so there is no concern about this going to prod prematurely, correct?

@Samara-Strauss That is correct, unless the `my_va_redirect` feature flag is enabled it will not prematurely go to production.

**Comment by Samara-Strauss** [comment]
Just took a look at this on staging. It's gorgeous 😍 . I have validated the following:

- In staging, logging in from the homepage redirects to My VA.
- In staging, logging in from a page that *is not* the homepage lands you back on that page (as expected).
- No changes in prod behavior (as expected, but worth confirming).

**Comment by ajakabcin** [comment]
We started this initiative prior to the new collab cycle ticket process, however I've linked to the appropriate tickets in the body of this ticket. All work is complete so closing this issue out. Thank you!
