### ISSUE TITLE
[FE] MyHealth:  Configure Government-Supplied Equipment

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42597]
## Tasks
- [ ] Design unauth FAQ desktop and mobile pages
- [ ] Update PO and PM on Slack when ready to review
- [ ] Add link to mockups to this ticket.

## Acceptance Criteria
- [ ] Design unauth FAQ desktop and mobile pages
- [ ] Update PO and PM on Slack when ready to review
- [ ] Add link to mockups to this ticket.
