### ISSUE TITLE
Collaboration Cycle for [Authenticated Experience, My VA, Audit UX Improvements]

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42601]
### VFS team name

Authenticated Experience

### Product name

My VA

### Feature name

My VA Audit UX Improvements

### GitHub label for product

my-va-dashboard

### GitHub label for feature

my-va-audit

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

June 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools and applications

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline
- [My VA audit UX improvements outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit#project-outline-my-va-audit-updates-and-documentation)
- [My VA full product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#product-outline-my-va) (additional reference for My VA)

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

</details>

 ### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**
As discussed in our initial kick-off our team conducted an audit of all functionality and conditional states of My VA earlier this year. We came away with a series of improvements that create a more consistent user experience for Veterans. The changes will also do a better job of surfacing benefits that are available to Veterans that they might now be aware of. Finally, these changes will make it easier for our team to manage and scale My VA over time . These improvements include, but are not limited to:

- Persistently showing all sections because we determined it's confusing to have sections show as loading and then disappear as it doesn't let people know what might be available to them, not to mention the poor a11y experience of that.
- Standardize loading and error states across sections as we are currently not handling consistently
- Simplify conditional states while still keeping a necessary level of personalization. The conditional states have become more difficult to manage as the page has grown at no real determined benefit to the user. 

- [X] Whiteboard sketch or other lo-fi prototypes or wireframes

**User who is LOA3 but does not have any open claims or health care through VA:**
[Desktop Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/64D300F9-9076-4101-9FAA-1E264422070A)
[Mobile Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/325276E8-9D9D-4401-86AF-615EAE883678)

**User who is LOA3 and has an open claim and VA health care:**
[Desktop Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/F7C698CF-2B34-437A-98FF-618E420C279F)
[Mobile Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/5BD3762E-790F-42CB-96E2-FE7D6BCE7A72)

**LOA1 user with no applications started:** (Same as current)
[Desktop Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/1365C416-1D79-4AE7-AF80-279AAD519844)

- [ ] User flow - N/A
- [ ] Research plan - N/A
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: September 26 at 3:30pm ET
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
  - [ ] Research has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/HAJFFFR7T10AtBjrd6jQEsY5IG9-IqQo3gX-PHq4MBZ2_VhW9k04A9dYni0oMYSI.S58zCHEa7wVQ7z-L)
  - Password: *2zz@Kna
  
##### VFS actions

- [x] Respond to feedback tickets

 
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] [Link to the Sitewide Content and IA Intake Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48155)

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**
Provide links or documents for the following:

- [ ] [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit)
- [ ] Sketch Files: 
[User with claims and appeals and health care](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/D3CE5EC9-6925-4086-A1C5-2370E93073CB)
[User with no claims or appeals or health care](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/E6ADDE2C-0D24-484F-A829-CEA239BD56E6)
[LOA1 state](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/5B50B211-EE03-4796-8AEA-284AF040C31F)
[Error states](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/36FD1008-AA20-4E81-BCAF-FFBAE0F4070F)

- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/research/MyVA-audit-research-plan.md) 
- [ ] Conversation guide: **Has not been created yet**
 
**Content artifacts**
  
- [ ] Your product’s content source of truth: 
We document content specs within our FE documentation. Links for each section:
[Claims and appeals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md)
[Health care](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md)
[Education and training](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/education-and-training-FE-documentation.md)
[Saved applications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md)
[LOA1 state](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): N/A

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [ ] Link to test cases/test plan in TestRail (draft OK): 
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: Monday, October 24, 2022 at 3:30pm ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
  - [ ] QA has completed the review
  - [ ] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - [Recording URL](https://adhocteam-us.zoom.us/rec/share/DSbAQNMx4UFWZXqNXHx9ma_-vBJGkBmgIPKQJSMmaFipIHubNSab6zbnfJo7vx6H.gA8vAqjtJlYA9J_K?startTime=1666639951000)
  - Password: `K*6+7*v1`
  
##### VFS actions
  
- [ ] Respond to feedback tickets
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket - #50621 

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below
- [x] #55302

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/launch-materials/my-va-audit-improvements-release-plan.md)
- Staging URL: https://staging.va.gov/my-va
- [Test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md)
- [Test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit-a11y.md) (A11y format)

**Content artifacts**
We document content specs within our FE documentation. Links for each section:

- [Claims and appeals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md)
- [Health care](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md)
- [Outstanding Debts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md) (though no changes were made to this section since the review and launch of "Payment info v2" in Q4 2022)
- [Benefit Payments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md) (though no changes were made to this section since the review and launch of "Payment info v2" in Q4 2022)
- [Education and training](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/education-and-training-FE-documentation.md)
- [Benefit application drafts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md)
- [LOA1 state](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md)
  
**QA artifacts**
- [x] [My VA Audit UX Improvements - QA Artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/tests/e2e)
- [x] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/tests)

  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/launch-materials/my-va-audit-improvements-a11y-staging-review-prep.md)
- [x] #54648
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: **Thursday, March 9, 2023 at 2:00PM Eastern**
- [ ] Create feedback tickets and link to this epic
  - [x] Design feedback provided
  - [ ] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/-_6vegXXsC8QzJhQ0Anz0IVRcK_cdQVosz6BTwWOwQRlxFVH0SE2eGWliZ_LfjMV.ubdnHjMAKPD1_jBX
  - Password: =kae&8f5
  
##### VFS actions
  
- [ ] Respond to feedback tickets
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Update the VFS product information section with the product’s launch date and production URL after it has gone live

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/747)

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by ericasauv09** [comment]
We do not need new analytics but will need to make adjustments potentially to our current analytics

**Comment by aagosto90** [comment]
Added links to design artifacts to design intent toggle

**Comment by mtcA6** [comment]
This launched I'm closing this out
