### ISSUE TITLE
[Design] Wireframes and Wording for Content to Explain when Pre-Check-in Expires

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42619]
## User Story
As a Veteran, I would like to know when I can Pre-Check-in until so that I will know how long I have to do it.

## Description
Need wireframe and wording for where to display information that tells the Veteran when their Pre-Check-in link expires.

NOTE: Working in the health questionnaire could be used and it has already been tested; see @kristenmcconnell 

## Tasks
- [ ] Finalize detailed mockup and callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
