### ISSUE TITLE
[DataDog Migration] Test dual-shipping in BRD

### ISSUE THREAD

**Issue by jsgarmon** [department-of-veterans-affairs/va.gov-team#42611]
## Description
Following recommendations from #42452 , test a new build of vets-api in BRD.

## Background/context 
Part of #23513 

---
## Tasks
- [ ] make config changes on a branch, and run a build from that branch
- [ ] deploy vets-api dev using test build
- [ ] confirm metrics are being shipped to new dd account

## Acceptance Criteria 
- [ ] seeing metrics from dev in new dd account

**Comment by jsgarmon** [comment]
Added config changes to datadog and built a test image. See changes here:
https://github.com/department-of-veterans-affairs/devops/compare/jsg/23513

Deployed a dev vets-api server from this test build and can see two endpoints:
![image](https://user-images.githubusercontent.com/47490730/173085234-5e34830f-7605-409f-8c5c-e03f7cc6b9e2.png)

Some metrics are coming in to https://vagov.ddog-gov.com/, but not all:
![image](https://user-images.githubusercontent.com/47490730/173086233-9d29e0f8-c3bb-448d-9567-83e7400453ca.png)

**Comment by ElijahLynn** [comment]
hi @jsgarmon, we are about to migrate over and @jhouse-solvd mentioned to check the status of this ticket to see if this is working. Did https://github.com/department-of-veterans-affairs/devops/pull/11416 get it working?
