### ISSUE TITLE
Add Analytics-Request label to Platform Orientation template

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#42631]
## User Story
As a Analytics & Insights team member, I want proper labeling on the orientation template so that we can track request for our reporting.

- Intended Audience: Analytics & Insights Team
- Desired Outcome: Updated labeling for reporting
- Due Date: N/A

## Description
Michelle Dooley reached out requesting that we add the "analytics-request" label to the Platform Orientation template so that they can track and automate their reporting of requests.

## Artifacts Needing Updates
[Platform Orientation Template
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)

## Tasks
- [x] Add "analytics-request" label to Platform Orientation template

## Acceptance Criteria
- [x] GitHub Template: Platform Orientation has been updated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [x] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by shiragoodman** [comment]
PR approved. I merged into master.

**Comment by shiragoodman** [comment]
@michelle-dooley FYI
