### ISSUE TITLE
Issue when performing terraform plan in environment/dvp-staging

### ISSUE THREAD

**Issue by evelez-va** [department-of-veterans-affairs/va.gov-team#42646]
## Who is the devops resource on your team?
_Please use their github username, if applicable (optional, please delete if unused)_

@azimzores @mramirez-va @evelez-va 
## Description

_What details are necessary for understanding the specific work or request tracked by this issue?_
 We're in the process of submitting a Pen Test for our DVP Infrastructure in DSVA. In order to do this we need to add some security groups, which we would do via the terraform in `environments/dvp-staging`. When trying to run a `terraform plan` from the master branch (before adding any new changes`) we're running into the following error:
```
Error: Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```
## Background/context 
Yearly required Pen Test, need to add the additional security groups to the `dvp-staging` infrastructure to allow the Pen Test Team access. 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_
To replicate:
```
git checkout master
git pull origin master
cd devops/environments/dvp-staging
terraform init
terraform plan
```

Tried disabling version 3.72.2 for the aws provider and got a bit further into the `plan` before running into the issue again. 
```
provider "aws" {
  version = ">= 2.70.0, != 3.17.0, != 3.28.0, !=3.72.2"
  region  = "us-gov-west-1"
}
```
---
## Tasks
- [ ] Determine root cause for issue
- [ ] Present solution

## Acceptance Criteria 
- [ ] Solution present that allows Lighthouse DevOps to successfully run `terraform plan` in the `dvp-*` environments. 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
@evelez-va : is this still an issue? I'm not able to reproduce this error from current master branch. If it is still an issue, please post the output of `terraform version` from within the `dvp-staging` directory.

**Comment by evelez-va** [comment]
@jsgarmon Have run into it a few times, but we are able to resolve it by removing the local terraform files, init, then plan/apply. I think it's good to close with that resolution.
