### ISSUE TITLE
[BE, FE] My VA Payment info: Investigate drop off in user activity

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42641]
## Background
As [reported in slack](https://dsva.slack.com/archives/C909ZG2BB/p1654803172853179) the payment info section is seeing a significant drop off in user activity.

- From May 25 - 31, View Payment History was the #2 most popular link and had 156K successful `GETs` [GA link](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/_u.date00=20220525&_u.date01=20220531/)
- From June 2 - 8 those numbers have dropped significantly - View Payment History isn't even in the top 10 interactions (where it has been since launch), searches for payment history are up, [GA link](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/_u.date00=20220602&_u.date01=20220608/) 
- `GETs` are way down to 68k 
- Interactions in general showing a sharp drop beginning May 31
![image (24)](https://user-images.githubusercontent.com/45603961/172933881-742c0724-4fe0-4362-a5e3-34926db41ac1.png)

## Tasks
- [ ] Investigate drop off in user activity to determine if there is something wrong with the feature
- [ ] Identify next steps if a problem is found with the feature
- [ ] Work with PM/APM to get additional tickets created as needed to complete any course of action identified

**Comment by Samara-Strauss** [comment]
Thanks for this, @tpharrison.

Next steps: We are actually going to have Mark look into a separate and also high priority issue with some Cerner functionality being broken in prod before coming back to the payment issue. However, @ajakabcin and I both think it's likely that something in [#39965 [FE] My VA - Payment info: remove 403 error msg when user has no payment history](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39965) inadvertently broke something, as the massive drop in payment history activity started occurring right after the update in #39965 went out. We'll have either Taylor or Mark start investigating on Monday.

**Comment by Samara-Strauss** [comment]
@tpharrison do you think we should change how we are handling analytics in GA in order to capture more accurate reporting? I can't tell if this means that we may be capturing duplicative or misleading data or not. What do you think?

**Comment by tpharrison** [comment]
Sorry for the late (and long) response.  I wanted to look into this a bit more before answering.

It's a bit confusing because we have Google Analytics, Prometheus, Grafana/Loki, Sentry, and Datadog.  Each show slightly different metrics, logs, and errors.  On top of this we have both the FE and BE sending data to these tools.  This can make it difficult to determine where to look when problems come up.

In general, when an issue (or possible issue) arises, we need to be able to quickly answer these questions:

1. Is the issue with VA.gov or an external system?
2. Is the issue application related or infrastructure related?
3. Is it related to the FE or BE?
4. Can we monitor this issue (or type of issue) going forward?

For this issue, which of the above questions have we been able to answer?  It appears to be FE related.  If so, do we need to collect more information about this error? Where do we send it?  I think the FEs will need to provide answers in this case.

I've started adding monitoring in Datadog this sprint and will continue to build on this over the next few sprints.  At some point, I'll need to coordinate with the FEs to make sure we know what events are being logged and where.  This will be a WIP but I'm hoping we can eventually have a streamlined process in place to track down issues quickly.
