### ISSUE TITLE
Add UAT research tech troubleshooting to Platform

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#42651]
## User Story
"As a researcher, a guide for troubleshooting research sessions with products in production would help when I run into an issue with UAT."

- Intended Audience: VFS
- Desired Outcome: add updated guidance to relevant documentation
- Due Date: 

## Description
Researchers have found a need to draft [their own troubleshooting documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/prod-testing-troubleshooting.md) when doing research with in production products, esp for UAT. This is guidance that Shane and Kevin agree would be great to have on Platform Website.

## New Artifacts 
New page for troubleshooting tech during UAT

## Tasks
- [x] Determine where this information should live on Platform Website/Research and Design
  - @shiragoodman's suggestion - possibly in the [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions) page?
  - [x] Create guidance as new child page under [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)
  - [x] Add [Platform Website footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro)to new pages
- [x] Determine if the [GH page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/prod-testing-troubleshooting.md) should be marked as deprecated, or otherwise linked to the new Platform page.
   - Contact @aagosto90 since she created the existing GH page and has maintained it
   - Notify her how she can suggest changes to the page once on Platform Website using the "Create an issue ticket to suggest changes to this page" bullet in the footer
- [x] Check for any known links to the GitHub version
  - [x] Update with new link to Platform Website

## Acceptance Criteria
- [ ] Platform Website: Troubleshooting for VA.gov Research Sessions in Prod has been created
- [ ] Platform Website: Troubleshooting for VA.gov Research Sessions in Prod is available for VFS teams to reference
- [ ] Angela understands the new location and how to suggest edits to the pages
- [ ] Any known links to GitHub documentation is updated to Platform Website link
- [ ] If GitHub is deprecated: Users are aware that the GitHub pages have been deprecated
- [ ] Updates have been Peer Reviewed by Governance Team member
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
Hi @aagosto90 , per this ticket, I am moving the [Troubleshooting for VA.gov Research Sessions in Prod](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/prod-testing-troubleshooting.md) to platform website. Once that is done, can I mark the original GH page as deprecated?

After the move is complete, you can suggest changes to the page once on Platform Website using the "Create an issue ticket to suggest changes to this page" bullet in the footer

**Comment by aagosto90** [comment]
Hi @allison0034, yes, that's fine! I'll share the new link with the other designers once it's on the platform website.

**Comment by allison0034** [comment]
@chaseakirby this is ready for review. 
[GH page](https://github.com/department-of-veterans-affairs/va.gov-team/pull/43500)
[Troubleshooting for VA.gov Research Sessions in Prod](https://depo-platform-documentation.scrollhelp.site/research-design/troubleshooting-for-va-gov-research-sessions-in-pr)

@aagosto90 [Troubleshooting for VA.gov Research Sessions in Prod](https://depo-platform-documentation.scrollhelp.site/research-design/troubleshooting-for-va-gov-research-sessions-in-pr)

**Comment by chaseakirby** [comment]
@allison0034 Looks good to me. I approved the PR and merged it in so closing this ticket.
