### ISSUE TITLE
Cleanup Cypress tests for Combined Debt Portal

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#42657]
## Issue Description
Portions of the Cypress tests for the combined debt portal can be shifted out into helpers to help tidy up and make the code more readable/useable. See Search [page object](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/search/tests/page-object/searchComponent.js) and [other tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/search/tests/e2e/01-required.cypress.spec.js) for inspiration. 

---
## Tasks
- [x] Update Cypress tests so they are cleaner and more manageable. 

## Acceptance Criteria
- [x] Cypress tests are more readable and better organized. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
PR is finally up! In code review, likely 0-1 point rollover while testing is complete. (in case of any change requests in feedback).
