### ISSUE TITLE
Parse delimiter characters out of FSR JSON

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#42659]
## Issue Description
The characters `|` and `^` are used as delimiters for the eventual CSV version of FSR requests and need to be parsed out of the initial JSON so as not to disrupt the format.

---
## Tasks
- [x] Parse characters out of JSON fields before VBS submission

## Acceptance Criteria
- [x] VBS submissions will not include `|` or `^`
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
