### ISSUE TITLE
Setup config for new VBS endpoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#42658]
## Issue Description
A new endpoint is available for the VBS service for FSR submission, set up the necesary configuration within settings and library to make this usable. 

---
## Tasks
- [ ] Update settings config
- [ ] Configure new route in library

## Acceptance Criteria
- [ ] The new VBS endpoint can be integrated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
