### ISSUE TITLE
Redeploy Jenkins Master with new Beats AMI

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#42653]
## Description
Include Beats agent installation and configuration in baseline images/build for all devices within platform so that all devices can send security logs to CSOC Splunk instance.

This is a high priority, as requirement comes from CIO that all devices report security logs to CSOC Splunk.

## Background/context 
CIO has a requirement that all devices in VA enterprise ship security logs to enterprise Splunk instance.  In order for that to happen, the Beats agent has to be installed and configured on all of our devices.  

ECSO provided [this link](https://github.ec.va.gov/AWS/vaec-cls-beats/tree/master/SSM) to an SSM script for installing and configuring the Beats agents.

Using SSM to install the agents, however, will not suffice in our environment as there would be a gap in log coverage between the time a machine is deployed to when the agent is installed, given that we re-deploy images frequently.  Would need to include the Beats agent installation in the baseline image/build.

## Tasks
- [ ] Beats agents need to be included and configured on all platform devices in order to send security logs to CSOC Splunk per CIO requirement.

## Acceptance Criteria 
- [ ] Beats agents is included and configured on all platform devices as part of baseline image or build.

## Deployment Tracking

- [ ] jenkins-master-vetsgov

**Comment by ph-One** [comment]
@troymosher
