### ISSUE TITLE
[CDP] Update existing debt-letters widget for CDP and investigate staging only page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#42655]
## Issue Description
Once static pages are complete we'll need widgets to navigate to the new combined debt portal /manage-debt-and-bills/summary page. 

[Drupal staging-only example (need ID*?)](https://github.com/department-of-veterans-affairs/content-build/pull/194/files)
[Widget xample](https://github.com/department-of-veterans-affairs/vets-website/pull/20978/files)

[(LOCAL only example)See previous manage-va-debt widget implementation](https://github.com/department-of-veterans-affairs/vets-website/pull/17859)

---
## Tasks
- [x] Add widgets for CDP 
- [x] Investigate loading Drupal page only in staging

## Acceptance Criteria
- [x] New widget has been added that directs to cdp summary page (currently `/manage-debt-and-bills/summary`)

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Bumping this ticket up to cover the scope change for needing to test with content-build locally
