### ISSUE TITLE
[Design] Modify Poster to have Text Option be Primary and QR Code Secondary

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42665]
## Problem Statement
As a Veteran, since I have a difficult time using a QR code either because I don't understand how to use them or I cannot get it to work on my phone, I would like to understand that I can simply text "check in" to a number to accomplish the same thing so that I know I have an alternative.

## Tasks
- [ ] Design a poster where the text option is primary and the QR code is secondary 
- [ ] Test the poster with Veterans (? do we need to do this?)
- [ ] Upload the poster to Git
- [ ] Notify all facilities that are using the poster of the changes
