### ISSUE TITLE
[Design] POSTER - Add Check-in Window Message to Poster

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42662]
## User Story
As a Veteran, I would like to understand when I can check-in for my appointment so that I will not get frustrated if I try to do it too early.

## Tasks
- [ ] Add verbiage to the poster to indicate when a Veteran can use their mobile device to check-in (i.e. no more than 30 minutes before and up to 15 minutes after the appointment)
    - 30 minutes is the priority
- [ ] Test the poster with Veterans (Is this needed?)
- [ ] Upload the poster to Git
- [ ] Notify all facilities that are using the poster of the changes (see [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1658412338303919))
