### ISSUE TITLE
[UX] POSTER - Create Guidelines for Poster Placement

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42672]
## Description
Some facilities are not putting their Poster in the best location within their facility that maximizes the potential for Veterans to see it. We need to create some recommendations/guidelines for the facilities to ensure they are displaying the posters in the best locations.

## Tasks
- [ ] Create recommendations and guidelines for poster replacement in clinics
- [ ] Upload the recommendations to Git
- [ ] Notify all facilities that are using the poster of the document
