### ISSUE TITLE
va-text-input: missing autocomplete assignment

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42686]
## Description

In the `va-text-input` web component, `autocomplete` is included as a property definition, but [`autocomplete` is not added to the input](https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-text-input/va-text-input.tsx#L185-L199).

```jsx
<input
  id="inputField"
  type={type}
  value={this.value}
  onInput={this.handleInput}
  onBlur={this.handleBlur}
  aria-describedby={describedBy}
  inputmode={inputMode}
  maxlength={this.maxlength}
  minlength={this.minlength}
  pattern={this.pattern}
  name={this.name}
  required={this.required || null}
  part="input"
/>
```

## Tasks

- [ ] Include `autocomplete` attribute on input
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by k80bowman** [comment]
@Mottie is this blocking any current or upcoming work for you?

**Comment by Mottie** [comment]
It is not blocking anything for me.
