### ISSUE TITLE
[Research] Determine if it is Feasible & Advisable to Increase the Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42683]
## User Story
As a Veteran, since I am asked or need to arrive up to 1 hour before my appointment time, I would like to be able to check-in for my appointment as soon as I arrive at the clinic so that I don't have to remember to do it later.

## Tasks
- [ ] Perform enough research to determine if this is a good idea
- [ ] Determine if stakeholders are ok with increasing the check-in window
- [ ] Present findings & recommendations to team
