### ISSUE TITLE
[DataDog] Configure agents deployed to EKS for dual shipping

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42685]
## Description
As part of the migration of DataDog to GovCloud, agents deployed to EKS need to be configured to send metrics to both instances at once. This gives us the ability to ensure that metrics are being shipped properly. 

## Background/context 
Please see parent epic for background 
Recent related issue: #42611 
DataDog [docs on dual shipping](https://docs.datadoghq.com/agent/guide/dual-shipping/?tab=metricsservicechecks) 

## Technical notes

Update each <env>/values-<env>.yaml in vsp-infra-application-manifests/apps/vsp-operations/datadog-agent with something like:

```
  useConfigMap:  true
  customAgentConfig:
    additional_endpoints:
      "https://vagov.ddog-gov.com":
      - apikey

    logs_config:
      use_http: true
      additional_endpoints:
      - api_key: "apiKey"
        Host: "https://vagov.ddog-gov.com"
        Port: 443
        is_reliable: true

```

---
## Tasks
- [ ] Update agents in dev to send to both instances 
- [ ] Update agents in utility to send to both instances 
- [ ] Test that metrics are going to the both instances 

## Acceptance Criteria 
- [ ] Metrics are shipping to app.datadoghq.com 
- [ ] Metrics are shipping to vagov.ddog-gov.com

**Comment by oseasmoran73** [comment]
Given there is dup ticket, closing out this one. See one referenced above by Matt
