### ISSUE TITLE
Debt Portal Edge Case - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#42688]
## Issue Description
This ticket is to track discover work to be completed as part of the [Debt Portal Edge Case](Edge Case - Benefits 2 - Combined Debt Portal)

---
## Tasks
- [x] We have reviewed product outline
- [x] We have review current Domo and GA reports
- [x] We have identified meaningful KPIs
- [ ] We have discussed with debt portal team their needs and recomendations.

## Acceptance Criteria
- [ ] When the above items have been complete.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
I'm still working on developing KPIs for Copay Balance and Benefit Debt portals - but here is the [WIP Discovery Spreadsheet](https://docs.google.com/spreadsheets/d/1GlcJ2rmmlA-K9uzaeiu9KoF-NantyP4xwYcLbn9JjlI/edit#gid=2091635579).

**Comment by chloedotbrown** [comment]
@michelle-dooley @jonathan-epstein13 and @pavanhothi 

The [KPI discovery spreadsheet](https://docs.google.com/spreadsheets/d/1GlcJ2rmmlA-K9uzaeiu9KoF-NantyP4xwYcLbn9JjlI/edit#gid=2091635579) for the Combined Debt Portal is ready for your review. You can find original ticket with resources in #42360. 

I'd love any feedback you have, especially regarding the following:

- Is anything vital missing?
- Any edits to KPI scoping? _(In general, they requested a lot of hit-level metrics where we might default to users... but there's a case to be made for either!)_
- Any changes you'd like to see in KPI framework categories?

When we're read to reach out to the Benefits 2 team for their input, I'd recommend hiding columns past E to make it less overwhelming to read. We'll also need to confirm some event actions flagged here, since they're past login, so we're not able to test for them ourselves.

Thanks so much!

**Comment by michelle-dooley** [comment]
@chloedotbrown @jonathan-epstein13 @pavanhothi - I'm going to schedule a quick meeting for us to go over together.

**Comment by michelle-dooley** [comment]
We have completed discovery.  @pavanhothi to work on mock up based on these findings and we will meet with Debt Portal team to go over.
