### ISSUE TITLE
[bug] 526ez | Prod support, resubmit 526 submission that failed out with VeteranRecordWsClientException

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#42699]
## Value Statement
**_As a_** system of record
**_I want to_** know when a user tries to re-submit a claim
**_So that_** re-submitting older versions of the claim do not cause processing confusion and slowdowns.

---
## Background Context
We have about 2000 526 claims that failed out due to an upstream system that EVSS 526 submissions depend on.  We need to resubmit those claims.

The specific error is found in Form526JobStatus table.

evss_err_key = 'gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException'
 
We don't want to resubmit older versions of the claims if the vet re-did the claim and resubmitted themselves.  My concern is that re-submitting older versions of the claim will cause processing confusion and processing slowdowns.

## Expected behavior
Error should be retryable (already in another ticket).

## Acceptance Criteria
- [ ] _Duplicative claims are not created due to resubmission._

## Tasks
- [ ] Talk to Chante about potential next steps.

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
Slack thread where I notified EVSS of the issue:
https://dsva.slack.com/archives/C8R3JS8BU/p1654533731456819

**Comment by saderagsdale** [comment]
I reached out via slack on 6/16.

**Comment by michelpmcdonald** [comment]
Just updating with the current status.

We are waiting to meet with Chante Lantos-Swett for advice on what to do with the ~2000 claims that hit this issue.

Technically speaking, we(vets-api 526 team) does have the ability to find the 526 submissions that hit this issue, but, if the user has self corrected(successfully resubmitted on their own, started over on a new claim and successfully submitted), I'm wondering what would happen if vets-api attempted to submit the older claim that hit the VeteranRecordWsClientException.
Can we just throw the potentially older claim across the wall and count on our downstream claim establishment system to "figure it out" appropertially ?
Is it possible that vets-api re-submitting these old claims will harm the vet is some way(create confusion and just generally slow the claim adjudication process down)

Is there anyway, given the old claim and it's issues, to pull the vets current issues(rated issues ?, issues from 'open'(don't know how to determine) claims) and determine if the issue(s) in the old failed claim have been established subsequent to the failed submission and we don't need to worry about the failed claim issue....

**Comment by saderagsdale** [comment]
@michelpmcdonald What do you recommend as the course of action for this ticket?

**Comment by michelpmcdonald** [comment]
We met with Chante Lantos-Swett, explained my concern re-submitting old claims.  In the meeting, she understood my concern, she did not have the answers, but she was going to try to find someone on her end to help us out.
Have not heard back from her yet

**Comment by michelpmcdonald** [comment]
closing, at this point, the newer claims that have hit this issue have been manually re-submitted as long as they did not have any attempted submits after the VeteranRecordWsClientException.

The fix to automatically resubmit the claims that hit this issue has been put it, so for the most part, we should not see any of theses as long as long as VeteranRecordWsClientException remains a temp issue and retrying will get around it.
