### ISSUE TITLE
[DataDog] Explore migrating resources from commercial to GovCloud instance 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42691]
## Description
As part of the migration to GovCloud, DataDog resources such as dashboards, private locations, etc will need to be moved or re-created in the new instance. DataDog provides tools for this purpose. We want to test these tools and provide guidance to other teams so that they can move resources as needed. 

## Background/context 

- Please see parent epic 

## Technical notes

- Let's focus on moving resources owned by the Platform Infrastructure team 
- The [datadog-sync-cli](https://github.com/DataDog/datadog-sync-cli) tool appears to have the functionality that we need 
- _The [dogmover.py](https://github.com/DataDog/Miscellany/tree/master/Dogmover) tool looks like it may also work, though the one above may be preferred_

---
## Tasks
- [x] Test moving the following types of resources from app.datadoghq.com to vagov.ddog-gov.com: 
  - [x] dashboards 
  - [x] synthetics_private_locations
  - [x] synthetics_tests
  - [x] _there may be more, please add to this list_
- [x] Try to see what Terraform gets us 
- [x] See if any dashboards can be removed 
- [x] Move the following resources from app.datadoghq.com to vagov.ddog-gov.com: 
  - [x] dashboards 
  - [x] synthetics_private_locations
  - [x] synthetics_tests

## Acceptance Criteria 
- [x] The following resources - owned by the Platform Infrastructure team - have been migrated to vagov.ddog-gov.com: 
  - [x] dashboards 
  - [x] synthetics_private_locations
  - [x] synthetics_tests

**Comment by jhouse-solvd** [comment]
It might be good to create a related ticket that documents the teams and dashboards to move. 

Here's an example of an isolated dashboard that could be moved (putting this here for note-keeping):

https://app.datadoghq.com/dashboard/4nh-vnd-jv5/vagov-auth-experience?from_ts=1655143854692&to_ts=1655230254692&live=true

**Comment by oseasmoran73** [comment]
> create a related ticket that documents the teams and dashboards to move

Are you referring us to document what dashboards pertain to which team? Or resources our team will be moving? If so, I disagree we should. We could if this is the direction we are moving forward, but in my mind, we should notify teams of end of life for original DD, provide document how to move their dashboards and responsibility falls on them. Thoughts @jhouse-solvd ?

**Comment by ianhundere** [comment]
> ...we should notify teams of end of life for original DD, provide document how to move their dashboards and responsibility falls on them.
agreed

**Comment by oseasmoran73** [comment]
private_locations new ones were created. No need to migrate

**Comment by oseasmoran73** [comment]
Beginning to compile of list of dashboards that Infra will migrate over. Once we have that going. We can then focus on migrating them over as code (in the near future)

**Comment by oseasmoran73** [comment]
TF code has been merged. Prior to migrating dashboards over, attempting to rewrite as code

**Comment by oseasmoran73** [comment]
Dashboard has been compiled into code and merged into datadog-gov. See other [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43000) for more details

Documentation has been distributed to teams to migrate resource

Closing out this ticket as infrastructure resources have all been migrated
