### ISSUE TITLE
PM | Staging Review | Profile Team | Bad Address Indicator (BAI)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42706]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] [Profile Information](https://staging.va.gov/profile/personal-information) and [Contact Information](https://staging.va.gov/profile/contact-information)
- [x] Staging users: [users 121 - 126](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

- [x] Product outline [is here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator)

- [x] Release plan with the "Planning" sections completed is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/product/release-plan.md)
 

### Content artifacts 

- [X] Your product’s content source of truth [Sketch files](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/p/B84818F9-2AB7-42E8-BFFD-0C0949B020A3/canvas)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/3361)
- [x] [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_id=5847&group_order=asc&display_deleted_cases=0)
- [x] [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/361)

- [x] Summary(Defects) 2 defects logged and are being addressed: #46036 #46065 
### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- See [#45262](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45262) No issues found.

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by CherylEvans** [comment]
No Content FB at this time.  Looks good.

**Comment by SKasimow** [comment]
@tlei123 - once you complete testing can you either add links to the QA section above or send to me to add?

**Comment by tlei123** [comment]
^ @SKasimow , yep.  Everything should be ready for ya tmrw (Tue) morning.  :)

**Comment by tlei123** [comment]
@ddzz , QA test-runs completed.  QA-artifacts links (except Summary (Defects) report) updated above in main description. 
 Once Summary (Defects) report gets successfully generated, I'll update that link too.

cc @SKasimow

**Comment by allison0034** [comment]
[Zoom recording](https://oddball-io.zoom.us/rec/share/w20g3fHvD21zTnNDxCw9HRf0I6ZleMc-OwMPlzdpWfc4NENKu8Y-KKQOC_F2n4x8.DckQlGM9lkifNdFj)
Passcode: #TT6x6?Z
