### ISSUE TITLE
Edit and check rates on $600 Buy-Up rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42705]
## Issue Description
As part of our larger effort for migrating the education rates pages to our modernized content, we have further work to do on the $600 Buy-Up rates page that's currently in draft in Drupal. 

We need to:
- Confirm the rates are correct and up to date
- Edit the page to align with the style we followed for Post-9/11 and both MGIB rates pages (this is both phrasing and bolding patterns)

Drupal page to work in: http://preview-prod.vfs.va.gov/preview?nodeId=5572
Source page with rates: https://www.benefits.va.gov/gibill/resources/benefits_resources/rates/600_buyup.asp

Other rates draft pages for comparison:
Post-9/11 GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=1009
MGIB-AD: http://preview-prod.vfs.va.gov/preview?nodeId=5355
MGIB-SR: http://preview-prod.vfs.va.gov/preview?nodeId=5449

## Tasks
- [x] Check rates (Katherine)
- [x] Edit for style and bolding patterns (Katherine)

## Acceptance Criteria
- [x] Rates have been checked and style and bolding patterns have been addressed
