### ISSUE TITLE
[CDP] Updates to icons in the cards' status sections 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#42708]
### Background

During the Combined Debt Portal's midpoint review, we received feedback that we should review the icons used in the debt and copay bill status cards to make sure they're being properly used within the context of each status. For example, some statuses use a warning icon while others use an informational icon.

Additionally, we reached out for accessibility guidance on alt text or screen reader only text to indicate what's being communicated for those icons 

### Solution

[The iconography](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/148550080/simulate/no-panels?mode=i) has been reviewed and the icons have been changed to an 'informational alert' for the following statuses/diary codes:
- 71
- 655, 817
- 212
- 681, 682
- 600, 601
- 811
- 801, 802, 803, 804, 809, 820
- 822
- 825
- 821

Additionally, we received the following accessibility feedback:
- The status icons need alternative text based on the icon's level of importance 
   - Informational icons should say 'informational' 
   - Warning icons should say 'important'

---
## Tasks
- [x] Update the icons in the outlined diary codes
- [x] Add alt text to the icons 

## Acceptance Criteria
- [x] The icons have incorporated the visual and accessibility feedback outlined above

**Comment by Dr-Pongo** [comment]
Icons updated, reviewing some missing dates for cards.

**Comment by Dr-Pongo** [comment]
changes have been merged
