### ISSUE TITLE
[FE] My VA: Revisit Health Care section logic on My VA 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42702]
## Background
As reported in #42650, the logic on the My VA dashboard was attempting to display _either_ the health care section  _or_ the cerner message, and because the header (including the spacing) of the health care section is part of the actual health care section, that's why the header disappears when the cerner message is displayed. 
![screencapture-localhost-3001-my-va-2022-06-10-11_01_58](https://user-images.githubusercontent.com/45603961/173136003-d4a82921-112b-43f2-8a42-c3a563db51a7.png)

Mark implemented a short term solution to address this issue, but we need a long term, more sustainable solution to address this issue.

---
## Tasks
- [x] Sync with Mark to understand his findings and proposed solution(s)
- [x] Document approach for long term fix
- [x] Work with APM to create ticket(s) for implementation of fix once determined

## Acceptance Criteria
- [x] We have a solution for a long term fix 

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Any team member
- How can this work be validated? confirm we have documentation of solution and tickets for implementation

**Comment by tmitchellgcio** [comment]
Discussed with Mark. It's a bit of code refactoring. It works as intended it's just not ideally written so this will need to be a refactor.

**Comment by tmitchellgcio** [comment]
To document the technicalities of this. It currently has multiple returns inside the component and it's not ideal so we need to refactor this to use a single conditional return.
