### ISSUE TITLE
Work in preparation for new COVID updates coming around 6/17

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42704]
## Issue Description
We will be getting new COVID-19 vaccine info possibly by 6/17 but it might not be until 6/21. These changes will have to do with approval for the primary vaccine series, which will mean updates to the main vaccine page, about vaccine page, and CLP. 

To be ready for these changes (which may be a last-minute scramble on 6/21) we need to audit these 3 pages to flag anywhere where we discuss vaccine options as places where we'll likely need to update content. 

Pages to look through:
- [Main vaccine page](https://www.va.gov/health-care/covid-19-vaccine/)
- [About vaccine page](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/)
- [Campaign landing page](https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/)

Once we've looked through the pages, we should compile a list to keep in this ticket for when Danielle is ready to make these changes.

There may be other prep work needed as well, which we can add to this ticket as it comes up. 

## Tasks
- [x] Audit the 3 pages listed above for areas where we discuss vaccine options
- [x] Attach doc or list out in this ticket

## Acceptance Criteria
- [x] We've identified the areas on the 3 pages where we may need to add new content to

**Comment by katherine-fung** [comment]
I found the following areas on the main vaccine page to potentially update pending new information about options for the primary vaccine series. I'm also attaching a PDF highlighting these sections:  

[https://app.zenhub.com/files/133843125/464320ec-82b7-4f7a-9f20-529529e4fcb9/download](https://app.zenhub.com/files/133843125/464320ec-82b7-4f7a-9f20-529529e4fcb9/download)

**Main vaccine page:** 

- "Latest updates on booster shots and additional doses" alert - flagged this in case we want to edit the alert to reflect the updates 

- "More information about who can get a vaccine" - flagged this section in case there are updates about who is eligible for the primary vaccine series 
 
- "Can eligible adolescents ages 12 to 17 get a COVID-19 vaccine at the VA?" - flagged this section in case we want to change this accordion item to reflect potential changes to the ages of children who are eligible, or add an accordion item 
 
- This section also says "The Pfizer-BioNTech is the only COVID-19 vaccine authorized for use in adolescents at this time" 
 
- "Data from clinical trials show that the 3 authorized COVID-19 vaccines..." 
 
- "How to get your first or second vaccine dose" - flagging this section, which references the "Pfizer-BioNTech and Moderna vaccines require 2 doses"  

- "FDA fact sheets" - flagging the list of 3 fact sheets for Pfizer-BioNTech, Moderna, Janssen 

- "Currently available COVID-19 vaccines" - flagging the list of Pfizer-BioNTech, Moderna, Janssen vaccines

- "What to expect after you get a COVID-19 vaccine" section - flagging the list of fact sheets for Pfizer, Moderna and Janssen vaccines

- "What to do if you a COVID-19 vaccine outside of VA" section - flagging reference to people needing 2 doses if they're getting Pfizer or Moderna

**Comment by katherine-fung** [comment]
**Areas for potential updates on "About COVID-19 vaccines page:** 

Attaching the highlighted PDF with comments: 

[https://app.zenhub.com/files/133843125/3bef4858-2134-45c9-ae7d-25b73e820e14/download](https://app.zenhub.com/files/133843125/3bef4858-2134-45c9-ae7d-25b73e820e14/download)

- "Vaccine effectiveness" section - flagging the sentence "Scientists studied the 3 Food and Drug Administration (FDA) approved or
authorized COVID-19 vaccines..."

- "COVID-19 safety during pregnancy" section - flagged 2 paragraphs that reference "mRNA... vaccines (Pfizer-BioNTech and Moderna)" 

- flagging "Data from clinical trials show that the 3 authorized COVID-19 vaccines are safe..." 

unrelated to the ticket, but I also highlighted a few mentions of scientists still studying the vaccines' protection against Omicron, in case there is new information we want to share

**Comment by katherine-fung** [comment]
**Areas for potential updates on campaign landing page:**

None regarding options for the primary vaccine series, but I highlighted a mention of scientists still studying the vaccines' protection against Omicron, in case there is new information we want to share

Highlighted PDF attached: 
[https://app.zenhub.com/files/133843125/55b904c0-ae93-4c4c-8e06-51d082b30118/download](https://app.zenhub.com/files/133843125/55b904c0-ae93-4c4c-8e06-51d082b30118/download)

**Comment by RLHecht** [comment]
Thank you @katherine-fung! @DanielleThierryUSDSVA I'm going to leave this ticket in validate for when you have the new info ready to update our pages.

**Comment by katherine-fung** [comment]
**"About COVID-19 vaccines" and campaign landing pages:** 

We don't discuss eligibility on these pages, so I don't think we need to add any notes here, but I do want to flag **one sentence on both pages** we may want to look at changing. The sentence is bolded in the following paragraph:  

When you get a COVID-19 vaccine, you help protect your family, friends, and community. When enough people in a community get the vaccine, the community builds up immunity to the virus. This makes it harder for the virus to spread from person to person. **_And it protects those who can’t get a vaccine (like small children)._** We call this “community immunity.”

**Main vaccines page:** 

Under the "Who can get a COVID-19 vaccine at VA" header 
- Flagging that we don't list adolescents ages 12 to 17 here, even though we say in an accordion below that we offer vaccines to them 

In the "Can eligible adolescents ages 12 to 17 get a COVID-19 vaccine at VA?" accordion
- Flagging that we should consider adding an accordion below this that says "Can eligible children under the age of 11 get a COVID-19 vaccine at VA?" 

In the "Currently available COVID-19 vaccines" accordion
Flagging that we list the vaccines along with the ages of people eligible to get the vaccines anywhere. Those ages should change with new pediatric approvals.

**Comment by RLHecht** [comment]
Update from planning meeting: We should be making some of these changes where we discuss age for vaccines. @DanielleThierryUSDSVA Is going to review our work to determine which updates to make.

We can keep this ticket open and make the changes with this in the next sprint.

**Comment by RLHecht** [comment]
Closing as completed
