### ISSUE TITLE
[Design] Create Final Wireframes for Adding Physical Location to Pre-Check-in & Check-in Screens

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42722]
## User Story
We need final wireframes for adding physical location field to displays of appointment information in **PRE-CHECK-IN AND CHECK-IN** applications

## Tasks
- [ ] Finalize detailed wireframes and callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by loripusey** [comment]
Closing as this was a duplicate of https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42723
