### ISSUE TITLE
[Research] Talk to VAOS & Mobile App Team regarding V2 Data Fields

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42721]
## Problem Statement
We need a design spike to talk to VAOS to better understand the V2 database changes.
We don't have a full understanding on how to prioritize the display of these data fields for Veterans. What combination of data would be good to display on Intro and Confirmation pages within Pre-check-in and Check-in.

## Background info
[Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259)
Wireframe exploration [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42030)

## Questions to Answer
- What is the timeframe for when the V2 data fields (type of care & doctor name) will be ready to consume by CHIP/vets-api
- What does the data look like for Type of Care field
- Did you do research w/ veterans on how to display the V2 data fields (type of care & provider name)

## Tasks
- [ ] Read through slack thread where Peter and Lauren discuss the research with Vets[Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259)
- [ ] Talk to VAOS team about their research & how they tested their designs for these V2 fields
- [ ] Talk to native mobile app team about their research & how they tested their designs for these V2 fields
- [ ] If we need to do additional research
      - [ ] Create a ticket to run a remote 5 sec impression test
      - [ ] Create a ticket to do a card sort study (potentially)
- [ ] Create ticket(s) for final wireframes design work for these 2 additional V2 fields (& other V2 fields if we are planning to add them)

**Comment by zach-park** [comment]
Tagging myself. @zach-park

**Comment by ytsaoca** [comment]
Quick summary of[ the Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259) Kristen started:

Can you only get those fields (provider name and type of care) for community care appointments?
Peter: The answer is not fully known. For example, we can't get Type of Care for appts scheduled in TMP (Telehealth Management Platform, one of many tools facilities use to schedule appts (telehealth specifically), but may be able to get it through other Telehealth appts. I'll pull on this thread some more and try to get you some clarity.

[wireframes](https://www.sketch.com/s/806417fd-3d64-4da6-9529-0eef4fd48e2e/a/eKeomZa/play)
 Lauren/Mobile - we're designing so the data can be shown if available. If it's not, we don't display it.

Our appts list update will start after v2 work is complete. We'll be going through

Peter: I think it's fine that we have different approaches - we'll get to build off of each other's work and research, which can only help us make all the things better.

**Comment by ytsaoca** [comment]
Quick summary of[ the Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1654611741698259) Kristen started:

Can you only get those fields (provider name and type of care) for community care appointments?
Peter: The answer is not fully known. For example, we can't get Type of Care for appts scheduled in TMP (Telehealth Management Platform, one of many tools facilities use to schedule appts (telehealth specifically), but may be able to get it through other Telehealth appts. I'll pull on this thread some more and try to get you some clarity.

[wireframes](https://www.sketch.com/s/806417fd-3d64-4da6-9529-0eef4fd48e2e/a/eKeomZa/play)
 Lauren/Mobile - we're designing so the data can be shown if available. If it's not, we don't display it.

Our appts list update will start after v2 work is complete. We'll be going through

Peter: I think it's fine that we have different approaches - we'll get to build off of each other's work and research, which can only help us make all the things better.

**Comment by ytsaoca** [comment]
Started [this thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1656018490406749) to understand V2 database changes and the final UI of VAOS and mobile wireframes.

**Comment by ytsaoca** [comment]
Started [this thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1656018490406749) to understand V2 database changes and the final UI of VAOS and mobile wireframes.

**Comment by ytsaoca** [comment]
VAOS UI https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=76%3A21478

**Comment by ytsaoca** [comment]
VAOS UI https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=76%3A21478

**Comment by ytsaoca** [comment]
Have[ this thread](https://dsva.slack.com/archives/CMNQT72LX/p1656095247858329) about  timeframe and the Type of Care formate. But, haven't get a response.

For the VAOS designs, next steps are running them through collab cycle then usability testing. Devs won't start on them until after v2 is launched
