### ISSUE TITLE
Audit FAQs page for outdated guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42736]
## User Story
As a Governance team member, I want to audit the FAQs page to identify any outdated guidance so that I can make modifications and ensure the guidance is accurate.

As a VFS team member, I want to review the FAQs page for guidance on any questions/concerns I may have so that I can get my questions answered without having to post a question on #vfs-platform-support.

Assignee: @jimuhh 
Peer Reviewer: @chaseakirby 

## Description
The FAQs page has not been updated or modified in a long time. There may be outdated guidance since the launch of the Collaboration Cycle Request template in May 2022. The purpose of this ticket is to audit the FAQs page, identify anything that is no longer accurate or needs clarification, and document the findings. Any changes needed to the FAQs page will be addressed in separate tickets.

## Impacted Artifacts
[FAQs Page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs)

## Tasks
- [x] Audit the FAQs page
- [x] Validate links are working
- [x] Capture anything that could be cause for concern.
- [x] Reviewed by Shira once initial audit has been completed to discuss what is still relevant
- [x] Document anything that needs to be updated/modified. 

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] We have identified necessary changes for the FAQs page
- [x] We have created new tickets for the Governance team to implement the necessary changes - #45085

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by jimuhh** [comment]
Copied existing [FAQ page into documentation draft](https://vfs.atlassian.net/l/cp/1sQwdMFL) and added comments.
