### ISSUE TITLE
Define SOP for handling support requests around E2E test failures

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#42738]
## Issue Description
In order to provide a consistent experience with our support of Cypress, we need to develop a standard operating procedure for members of QAS team to respond to support requests involving Cypress failures.

---
## Tasks
- [x] Create a step by step standard operating procedure
- [x] Publish the guide to our internal team Confluence space. There is no need for the SOP document to be available on the Platform Website
- [x] Ensure that the QAS team is aware of the SOP and knows to reference it when resolving Cypress test failures

## Acceptance Criteria
- [x] Cypress failure support SOP document is published to QAS team Confluence space
- [x] QAS team is aware of the SOP and knows to reference it when responding to a Cypress test failure support request

**Comment by holdenhinkle** [comment]
I posted a question in Platform Release Tools and learned that they have an SOP for unit tests - https://dsva.slack.com/archives/CQH357ZTP/p1656015362542629 I asked if they'd share a link to it. I'm thinking it might be a good idea for us to adopt their procedures (if we agree with them of course), so handling Unit Tests and E2E Tests Support Requests is kind of standardized for VFS teams.

Draft in Google Docs - https://docs.google.com/document/d/13ITY9lbFImDnu2XW9I8qJZ8jREP2Chebe3pTbQTZqmc/edit#

Confluence Doc - https://vfs.atlassian.net/wiki/spaces/TTT/pages/2241036753/SOP+for+Handling+Support+Requests+for+E2E+Test+Failures

**Comment by pjhill** [comment]
Thanks for creating this SOP. I suppose the next step is getting people to use it. How do you think we can encourage our team to follow this SOP when addressing support requests?

We could bookmark it in our public channel.
Any other ideas?

**Comment by holdenhinkle** [comment]
Perhaps I can mention the SOP at standup tomorrow morning? That might be more effective than just posting a note in our team's channel.

I added the link as a bookmark in our team's slack channel:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/de4b89db-741a-4075-b544-a54f28c9a694)

Hopefully that's showing up for everyone^

**Comment by vahuntera** [comment]
Please remove me from these emails

Arná Hunter
United States Army Veteran
COR Level 2
Financial Systems and Procedures Analyst
Travel Agency/Organization Program Coordinator (A/OPC)
National Cemetery Administration
NCA Financial Systems Oversight & Transformation (42F)

Cell:                 202-384-5360
E-Fax:             202-495-5537


How was my service?<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvaww.vashare.nca.va.gov%2Fsites%2FPPS%2FLists%2FICSS%2FNewForm.aspx&data=05%7C01%7C%7Cbaa4be48ccdf43bbb32f08da60542cd7%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637928211884383458%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TwTtm3YDn8pD5HcTxYmjiuIRgxIsrIznMZgvlqwWIi4%3D&reserved=0>


[Description: Description: ***@***.***
VA Core Values: Integrity Commitment Advocacy Respect Excellence
VA Core Characteristics: Trustworthy | Accessible | Quality | Innovative | Agile | Integrated



From: Holden Hinkle ***@***.***>
Sent: Thursday, July 14, 2022 1:54 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Define SOP for handling support requests around E2E test failures (Issue #42738)


Perhaps I can mention the SOP at standup tomorrow morning? That might be more effective than just posting a note in our team's channel.

I added the link as a bookmark in our team's slack channel:
<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fc86e4922c605f264dd18ec52cf1ccb772be58ad7a8b5d24c5b5939e8f91ff836%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566383562636465346634373634353835653866663832302f64653462383964622d373431612d343037352d623534342d613534663238633961363934&data=05%7C01%7C%7Caa16d2441a7540ae6a3e08da65c1c67a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637934180177185591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PCw7yHgJOJwxbHgzOIYIBUpNHk4lRhtYeQHmx04QE4U%3D&reserved=0>

Hopefully that's showing up for everyone^

-

**Comment by pjhill** [comment]
Pinning this is a good call. Thanks for wrapping this up!
