### ISSUE TITLE
Improve Quality of E2E Documentation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#42730]
## Issue Description
Review our current documentation and determine how we can improve and simplify our current set of Cypress documentation to provide better guidance to VFS teams. Currently, there are 8 sub-pages to the Cypress guidance. Is there any way to consolidate those pages? Is there any redundant information that can be removed? Is there any contradictory guidance given in the different documents?

---
## Tasks
- [x] Assess the existing Cypress documents for redundancy
- [x] Consolidate documentation on Cypress to present simplified and more coherent documentation to VFS teams

## Acceptance Criteria
- [ ] Cypress documentation is simpler and easier to use

**Comment by CBonade** [comment]
Did a fair bit of restructuring and rearranging today. A good chunk of sections seemed like they might be in the wrong doc for where they would need to be used. The document formerly known as the Setup doc contained one section about setup and numerous sections about writing tests, while we had an entirely separate doc about writing tests that had a good bit of overlapping information with the setup doc, but was also missing some of it. I took the writing-tests-related information from the setup doc and moved it to the writing tests doc, and then took the one section about setup and moved it to the parent Cypress test doc. I also removed dated information from a few docs.

My next step is combing the docs and checking the links, both for broken links and outdated ones. I've already started this process and made a number of link changes and will continue this process until all E2E docs have been reviewed.

**Comment by CBonade** [comment]
Dead link pruning complete. Fixed numerous links where either the cypress docs had moved pages, or the docs were linking to old doc pages we had moved. All should be current now.

**Comment by JoeTice** [comment]
@pjhill - Noticed that we don't have a link to the documentation in question within this ticket, probably should add that

**Comment by pjhill** [comment]
These were the documents that were updated as part of this effort:
1. https://vfs.atlassian.net/wiki/spaces/pilot/pages/1738965071/End-to-end+testing+with+Cypress
1. https://vfs.atlassian.net/wiki/spaces/pilot/pages/1870430211/Best+practices+for+using+Cypress
1. https://vfs.atlassian.net/wiki/spaces/pilot/pages/1868431439/Writing+an+end-to-end+test

**Comment by pjhill** [comment]
These updates look good. We may be addressing our documentation yet again in a future effort. But, this is good for now!
