### ISSUE TITLE
[FE] - Update direct deposit routing number invalid error message

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#42734]
**Use case:** User entered an invalid routing number

This is a unique use case in that it references a specific field within a form and this particular validation happens after submit. Typically, field specific validation happens on input with our form system.

Devs, IMO the best UX is to use an inline error message on the field, and jump (not scroll) users to this field when the error appears. [Here's a mock-up](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/v/n5K3pa/a/YGOQEkZ). Based on our previous conversation, additional technical discovery was needed to determine the LOE for this.

If you can do some quick discovery and learn this is not a big deal to implement, great! But if you learn it is indeed complex to do a custom inline error message post-submit, I have a back-up plan. [I mocked up a version](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/v/n5K3pa/a/ago74wq) that should be a fairly low LOE based on what we have today.

One thing that isn't represented in the mock-up is that we should not use animation to guide the user to this error message when it appears. Let's just use a jump-link behavior instead.

**Tasks**
- [x] Confirm the best UX option is not a low LOE
- [x] Let Liz know which route we are going so she can update the use case documentation
- [x] Update the existing error pattern accordingly

**Comment by adamwhitlock1** [comment]
I started looking into the 'best' UX solution further and found:

- Custom validation messages are supported out of the box with the existing form system, but these messages usually are displayed via a 'live' validation function that provides as-you-type validation instead of post submit error handling.
- There could be ways to fudge a validation function post submit through some escape hatches, but they are messy and would not be ideal.
- We can't customize the error display, so any css tweaks would need to be applied via sass overrides of some sort.

For the time being I think we should go the other route with the alert being updated and the scroll updated to not animate as a 'first round' update.

For the future, this section of fields would be a good place to work with the new forms library, and this is a prime example of where customizing things like validation errors and having them appear post submit would be much easier with the new system.

We have a POC ticket open to work on migrating a phone number field to the new system, so maybe after that, we could look at these fields and migrate them next.

I will begin updating the existing pattern and attach PRs for that work to this ticket.

**Comment by adamwhitlock1** [comment]
So upon updating the `PaymentInformationEditError` to use the va-alert this is what it looks like for the `hasInvalidRoutingNumberError` case:

CURRENT UI AFTER CODE CHANGES
![Screen Shot 2022-07-19 at 2.43.10 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/47356b36-e797-400d-83d8-a061499f4064)

VS:

ORIGINAL MOCKUP
![Screen Shot 2022-07-19 at 2.50.40 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/ed7a533f-1474-442e-99b9-363c156f6af5)


I noticed a couple things that I wanted to discuss @andaleliz 

- This alert is used for the general alert and all other failures for Direct Deposit, so all the other errors would look similar to this, with no heading, so wanted to make sure that is what we would want.
- The alert does appear below the bolded sub-heading of 'Account` and because of the structure of the components there isn't a way to easily move this alert about that subheading. In the design mockup the alert showed above this sub-heading
- The wording of the alert is different than the mockup. Should this be updated?

**Comment by andaleliz** [comment]
Thanks @adamwhitlock1, it's awesome to see your progress on this! I appreciate you checking with me on these things. 

>This alert is used for the general alert and all other failures for Direct Deposit, so all the other errors would look similar to this, with no heading, so wanted to make sure that is what we would want.

I _think_ so but maybe I'm missing something. Are there scenarios where there would be multiple of these alerts? Are there any concerns about the heading missing? 🤔 

>The alert does appear below the bolded sub-heading of 'Account` and because of the structure of the components there isn't a way to easily move this alert about that subheading. In the design mockup the alert showed above this sub-heading

The way you have it is correct! Something got wonky in the mock-ups and that alert should be _under_ the heading as you have it. I updated the mock-ups.

>The wording of the alert is different than the mockup. Should this be updated?

Yes, the mock-up reflects the latest copy approved by our content team.

I'll update the DD use case documentation accordingly too.  Thanks again!

**Comment by adamwhitlock1** [comment]
Okay perfect, I will update content per the mockup, and I'll update this ticket with screenshots of the other alerts that would be affected by this 'global' change. It would be the alerts for these cases:

```
hasRoutingNumberFlaggedError(errors)

hasInvalidRoutingNumberError(errors)

hasInvalidAddressError(errors)

hasInvalidHomePhoneNumberError(errors)

hasInvalidWorkPhoneNumberError(errors)
```

So I'll confirm that we are okay with updating these to a no headline / updated alert style UI and go from there

**Comment by andaleliz** [comment]
Yes, I think that's ok.  There may be differences in copy between what is currently in the alerts and what is in the mock-ups. If that's the case, go with the mock-up copy.  Thanks!

**Comment by adamwhitlock1** [comment]
Updated alert for routing number invalid

![InvalidRoutingNumber](https://user-images.githubusercontent.com/8332986/180267257-53826b17-f03c-4790-8452-d0b6f1451e9c.png)

**Comment by adamwhitlock1** [comment]
Here are what the other related alerts look like using this new alert design

PAYMENT RESTRICTION INDICATORS
![PaymentRestrictionIndicators](https://user-images.githubusercontent.com/8332986/180267329-2129f254-a109-48d7-94aa-7b1d941fd84d.png)

INVALID PHONE NUMBER (basically the same for work and home phone except for the phone type in the alert copy)
![InvalidWorkPhoneNumber](https://user-images.githubusercontent.com/8332986/180267384-f7f43171-977f-47d7-a537-f4b3c4d4591e.png)

INVALID ADDRESS
![InvalidAddress](https://user-images.githubusercontent.com/8332986/180267541-965f32f4-3230-4824-a16f-97bfabd0574a.png)

FLAGGED ROUTING NUMBER
![FlaggedRoutingNumber](https://user-images.githubusercontent.com/8332986/180267637-d426df9f-fd25-4a40-b7f0-075427017f9e.png)

**Comment by SKasimow** [comment]
I do!
