### ISSUE TITLE
[Design] - Profile: Clarify direct deposit address and phone number requirements

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#42746]
**Background**

In #41527 we came across error alerts that tell users they need to review their mailing address or phone number. Digging into those, we identified an opportunity to improve the UX for these alerts.

How might we provide more clear information up front about what is required so that people don't encounter these errors in the first place?

**Tasks**

- [x] sync with EVSS on these questions:
- Does the backend check for home, work, then address, in that order? The call center guide suggests that.
- What is driving this requirement for users to have these items valid in their profile?
  - Answer: This is an artifact of BGS and not actually a requirement for users. It's a technical gap in the implementation.
- Does this apply to both kinds of direct deposit payments that we support?
  - Answer: it does not.
- [x] Document findings in our [use case document](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/use-cases#validation)
- [x] Update Sketch files

**Comment by andaleliz** [comment]
@Samara-Strauss In your guidance to reach out in #evss-dev, you specifically referenced "comp + pen direct deposit." Does EVSS handle EDU DD too? I'm operating under the assumption that EDU has these same address/phone requirements and error messages.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! Given the [answer we got on Slack](https://dsva.slack.com/archives/C1VBAHWQL/p1655315448790239?thread_ts=1655224123.172169&cid=C1VBAHWQL), the address and phone number requirement is being imposed on users by BGS because of a technical gap - not because users actually need this information on file to update their direct deposit information.

It's not ideal to require this of people simply because the service being used for the update wasn't actually designed for this purpose. Is this something we can check with BGS about? According to Michael "To fix this, BGS would need to expose a new SOAP operation that only requires EFT data." I have no idea what the LOE for that would be.

Side note, I didn't realize BGS was even involved with comp+pen DD. Since that's the case, is it possible this impacts edu (and thus, the whole DD page) as well?

**Comment by Samara-Strauss** [comment]
Yes, we can get BGS involved. Not sure who, but we can try to ask about this.

We did not account for this use case with education, and it is potentially possible this affects that feature, though I'm not sure. The error rate for edu is much lower, so if it is effecting this integration, it's in extraordinarily small numbers.

**Comment by andaleliz** [comment]
Update: Samara sent an email out to the BGS team yesterday to start the conversation. Waiting to hear back.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss I've updated [our use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/validation-address-phone.md) with what we know so far. I'm waiting to hear back on a couple more details to document in the technical information section from the FE team, but I think this is ready for you to review now.

I asked Nichole from the Lighthouse team to send me a ticket number so I can follow along with the work to decouple the contact info from the EFT update. Once there's any movement there, we can make changes on our side and update our docs accordingly.
