### ISSUE TITLE
Research Optimizations for E2E Tests in the CI Workflow

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#42743]
## Issue Description
Are there any optimizations that we can make for Cypress execution time? At this point, we have looked into speeding up Cypress execution and made significant gains on the actual execution of Cypress, but the tasks that precede and follow the execution are highly variable in the amount of time they take to resolve. Sometimes this variability can cause the E2E tests to appear to take a much longer time. 

Some items that may be causing variable Cypress execution time and could be investigated -

* Downloading and installing dependencies
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/e5b0a9e0-5b6e-49d2-949f-a9209ea5eb41)
* Uploading build artifacts
* Ingesting test results

---
## Tasks
- [x] Identify areas of the Cypress execution task that could be optimized
- [x] Look for tasks in the CI workflow that are highly variable -- are any related to Cypress execution?
- [x] Compile the results of analysis
- [x] Create tickets to address areas that might be optimized and attach them to the [epic](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/42729)

## Acceptance Criteria
- [ ] CI workflow has been analyzed for tasks that might be optimized
- [ ] CI workflow task optimization work tickets have been created and linked to this [epic](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/42729)

**Comment by rsmithadhoc** [comment]
- Looked into the dependencies step, and it looks like most things are pulled from cache. I believe the bulk of this step's time is downloading (or uploading) around 800 MB, trying to identify if that is needed. 
- Still need to look into the other steps.

**Comment by rsmithadhoc** [comment]
- Most of the time downloading any required artifact is what takes the most time.
- However, there are some steps that use the same artifact and it downloads in a few seconds. I'm unsure why that is, but I will try running these diagnostics to see what it might reveal. https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs
- Have not seen anything else to potentially address.

**Comment by rsmithadhoc** [comment]
**Tasks with variability between runs**

For this task, I looked into tasks that showed variability between runs:

- Downloading and installing dependencies
- Uploading build artifacts
- Downloading build artifacts
- Ingesting test results

I believe the culprit for all of these being erratic in the time they take is uploading or downloading. Because we run our build, then upload the artifact via GitHub Actions, the artifact stays on GitHub. When we run Cypress jobs, those run on self-hosted runners (AWS), so downloading the artifact isn't as fast as it is for other jobs that use GitHub runners since it has to download it from GitHub instead of just accessing the artifact that was already stored.

For installing dependencies, there is a caching step which is taking most of the time on a download of the cache. When looking at this step for CI runs, it does successfully restore from cache for Cypress steps, but the cache file is ~900 MB. Other steps (such as Unit Tests), do the same thing but have a smaller cache ~400 MB. The cache keys are the same in the example runs I looked at, so I'm unsure why that is and if it is also related to E2E being run on self-hosted runners and downloading additional data. The cache's key is a hash of the `package-lock.json`, so it shouldn't change unless the dependencies do, so I'm not sure why the size would be different with the same key.

Since the Cypress tests are split up and run in parallel, it has to perform these steps for each job. The main way of sharing data between jobs is through artifacts and caching, which is already being done.

**Potential updates**

Here are some potential things we can do, but it isn't clear if these are going to improve performance at all, so these aren't strong recommendations and I have not created tickets.

- Run everything on the same runners (either GitHub or self-hosted).
    - Fetching the artifacts may be quicker but the tests themselves may be resource constrained, so I'm unsure if this would have an impact.
- Custom steps for self-hosted runners artifacts and cache.
    - Not exactly sure how it would work, but if we manually created an artifact and cache on AWS, then all jobs running on self-hosted runners would directly access those.
- Look deeper at caching, update to `actions/cache@v3.
    - This one is very generic because it looks like it is done correctly but the different sizes for the same cache seems strange.

**Comment by pjhill** [comment]
Thanks for that write-up. The suggestions at the end seem worth pursuing. The caching discrepancy is definitely puzzling. It seems like the footprint is roughly double. Perhaps the dependencies are accidentally being stored in the cache twice?

Customizing the caching action seems like THE angle to pursue.

Sorry for the tangent that I'm about to launch into, but you mentioned that to some extent our parallelization strategy means that we incur the caching cost 8 times (at the moment). The CMS team recently mentioned that they were looking into [Sorry Cypress](https://github.com/sorry-cypress/sorry-cypress) as a solution for their Cypress parallelization needs. I wonder if that's worth exploring for our use as well.
