### ISSUE TITLE
[PM] Onsite Notifications: Call Center Guide Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42750]
## Background
Before we go live with onsite notifications we need to update the call center guide with the appropriate information.

## Tasks
- [x] Update call center guide
- [x] Have APM/PM review (whoever didn't do the edits)
- [x] Send to Samara for review
- [x] Submit to [call center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) with product guide
- [ ] Once approved update the product guides versioning documentation found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md).

## Acceptance Criteria
- [ ] Call center guide is updated with onsite notification information and final version is stored in our team documentation

**Comment by ajakabcin** [comment]
Hi @Samara-Strauss here's the product guide for your review. We've made updates to the following sections:

1. Navigation (pg 7 - 12): Updated to cover the redirect to My VA post homepage login
2. Notifications (pg 8 - 21): New section for onsite notifications
3. Benefit payments and debts (pg 35): Updated to reflect the recent change we made around when the section appears. Recall we made the update to the code in [43568](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43568) so that if a user has debts but has never received payments we show the section. Previously we were not showing the section in this scenario.
4. Minor updates to spacing and formatting, adjusting figure numbers so they're all in order

Let me know if you have any edits and we'll get them squared away then send it off to the call center for review. 

Thank you!

[MyVA_ProductGuide_V4_071822.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9204262/MyVA_ProductGuide_V4_071822.docx)

**Comment by Samara-Strauss** [comment]
Left a few comments, but largely looks great! Thank you for getting this updated!

**Comment by ajakabcin** [comment]
Updated and submitted to call center #45091

**Comment by ajakabcin** [comment]
VEO accepted our latest version of the product guide with no edits. I've logged the final version as submitted with a summary of the version changes [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md) (includes updates for My VA redirect as well)
