### ISSUE TITLE
[FE] Payment Info MVP: Remove Feature Flipper in Staging

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42757]
## Background
After looking into [this bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42647). We found that the feature flipper was not on for some users in staging which was causing the Benefits, Payments, and Debts section to not show for some staging users. We want to remove this feature flipper in Staging for Benefits, Payments, and Debts so that the section always shows for all staging users.

## Tasks
- [ ] Remove Benefits, Payments, and Debts feature flipper in staging
- [ ] Update cypress tests
- [ ] Validate that all staging users with payments, and debts show the section

## Acceptance Criteria
- [ ] All staging users with benefits and payments see the Benefits, Payments, and Debts section

## Validation
- [ ] **Who can validate this issue?** FE dev
- [ ] **How do you validate this?** check the code that the feature flipper is removed; review cypress tests in code
