### ISSUE TITLE
2022 Q3 Console UI - Create Processes + Support for Future Features

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#42754]
## Problem Statement 
The documentation and tools available for teams adding functionality to the Platform Console are incomplete. This will be a problem after the Console UI team is no longer available to support the Console.

How might we provide tools and documentation that are easy to find, and make it efficient for Platform teams to build on the Console?

## Hypothesis or Bet
- These resources will enable Platform teams to build on the Console with minimal support from the team that manages the Console.
- These resources will make it easier for more Platform teams to add more functionality to the Console more quickly, resulting in accelerated growth of the number of Console features available to VFS teams.
- Teams (including new team members) will be able to easily and quickly locate these resources when they need them

## We will know we're done when... ("Definition of Done")
We have easy to find, comprehensive documentation to be included in the Console Playbooks (ex: Plugin Playbook) for all levels of Console integration for Platform services in a determined published digital location, including
- [x] Guidance for deciding what level of integration is needed and where the desired feature should live (e.g. in a Catalog view, a standalone page, or a personalized dashboard) - [Docs Here](https://platform-console-ui-utility.vfs.va.gov/docs/default/Component/platform-console-ui/plugins/plugin-overview/#alternatives-to-plugins)
- [x] How to add "level 1" integrations (links) to the Console (Vets API team & RTT)
- [x] How to use the embed plugin for "level 2" integrations (embedded views from other websites) - [Docs Here](https://platform-console-ui-utility.vfs.va.gov/docs/default/Component/platform-console-ui/plugins/plugin-overview/#level-1-simple-links)
  - [x] We have built a generic plugin for embedding views from other websites (level 2 integration) - [Docs Here](https://platform-console-ui-utility.vfs.va.gov/docs/default/Component/platform-console-ui/plugins/plugin-overview/#level-2-generic-embeds)
- [x] How to build a "level 3" integration (complete plugin), both custom and out-of-the-box/Backstage (Console UI Team & RTT) - [Plugin Overview Docs](https://platform-console-ui-utility.vfs.va.gov/docs/default/Component/platform-console-ui/plugins/plugin-overview/#level-2-generic-embeds)

## Known Blockers/Dependencies 
- Level 2 integration: we would either have to build a plugin, or would be provided by the Backstage community
- Platform leadership delays or does not determine where this documentation (ex: Plugin Playbook) should be published (Confluence? Console TechDocs? Github?)
- There will be limited time for teams to test out this documentation, the contract ending September 9 (Friday), 2022

## Projected Launch Date
Before September 9, 2022

### ... tested?

- [x] Identify a team to implement Level 1 integration, provide documentation, gather feedback + update process appropriately
- [x] Identify a team to implement Level 2 integration, provide documentation, gather feedback + update process appropriately
- [x] Identify a team to implement Level 3 integration, provide documentation, gather feedback + update process appropriately

### ... documented?

- [x] Level 1 integration (adding links) is documented
- [x] Level 2 integration (adding an embed) is documented
- [x] Level 3 integration (adding a plugin) is documented, and added to the Plugin Playbook

### ... measurable
- There will be no metrics associated with this initiative

### Documentation
(same as Definition of Done)
- Guidance for deciding what level of integration is needed and where the desired feature should live (e.g. in a Catalog view, a standalone page, or a personalized dashboard)
- How to add "level 1" integrations (links) to the Console
- How to use the embed plugin for "level 2" integrations (embedded views from other websites)
- How to build a "level 3" integration (complete plugin)  

### Testing
If possible within the limited time allowed before Septmber 9, 2022, teams who are available to review and test out documentation

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_
