### ISSUE TITLE
[FE, Design] My VA Payment Info: Update logic to look for all payment types (long term fix)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42759]
## Background
The benefit payments and debts section of My VA currently only looks for direct deposit payments. We need the payment code to account for all payment types, i.e. paper checks and direct deposit payments. We should also confirm if there are any other payment "types" that we should be accounting for here.

## Tasks
- [ ] Design: Update copy to be dynamic depending on payment type
- [ ] FE: Update code to show payments of all types within the benefit payments and debts section
- [ ] FE: Update code to show dynamic copy based on payment type
- [ ] Test thoroughly - making sure we're testing all payment types

## Acceptance Criteria
- [ ] Benefit payments and debts section displays properly for users with all payment types

**Comment by ajakabcin** [comment]
No longer needed - closing
