### ISSUE TITLE
Create FAQs content for MyHealth team

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42767]
## Issue Description
As part of the larger effort to move MyHealtheVet functionality to VA.gov, we are adding FAQ content around Secure Messaging. 

The FAQs we need to create answer content to can be found here:

https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/R1K8kbZ

The source material to craft the answers from can be found here:

https://www.va.gov/health-care/secure-messaging/

[https://app.zenhub.com/files/133843125/28058130-3d8c-42c6-ac05-ce1bde337f2d/download](https://app.zenhub.com/files/133843125/28058130-3d8c-42c6-ac05-ce1bde337f2d/download)

https://app.mural.co/signin-join-mural?returnUrl=%2Finvitation%2Fmural%2Fdepartmentofveteransaffairs9999%2F1654893985647%3Fsender%3Dmegpeters0505%26key%3De5d0aa4b-ac0f-488a-b8fb-c427c4d38e35&title=messages-FAQs-notes&viral=true

The original intake ticket for more background: #42428

When doing this content work, if we see that some of this FAQs content doesn't need to be there, we can flag this for Danielle. 

## Tasks
- [x] Write FAQs answers
- [ ] Review (Laura)
- [ ] Copy edit (Megan)
- [ ] Submit for OCTO-DE review in ticket #42768 (Megan)

## Acceptance Criteria
- [ ] FAQ content is ready for OCTO-DE review

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! Draft is ready for you. There are a few questions for you and potentially for SME. 

Happy to review together tomorrow, or on Wednesday, if you have a moment! 
[Secure Messaging FAQs_AB_7.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9086279/Secure.Messaging.FAQs_AB_7.7.docx)

**Comment by aliyahblackmore** [comment]
Update: Laura and I met with Randi last week  and the next step is to return back to the[ health care tool pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34123) ticket, create the secure messaging page, and then come back to this ticket!

**Comment by aliyahblackmore** [comment]
**Just updating this ticket:** Laura has the most recent version of the FAQs (that will be in the tool for stage 0) and we are tracking this work in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49690#issuecomment-1315792690)

**Comment by laurwill** [comment]
Hi @RLHecht — I think we can close this ticket. We added FAQs for phase 0 to the phase 0 landing page. Once that landing page gets retired, we'll need a new ticket to look at moving the secure messaging FAQs into Resources and support.

**Comment by RLHecht** [comment]
Sounds good. Closing!
