### ISSUE TITLE
Content review of 1095-B design component

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42760]
## Issue Description
The VA Profile team opened an intake request asking us to provide content support on a new component that they're adding to the 1095-B form. We need to review the content in the "How to opt in for paperless delivery only" alert provided in this PDF and rework it so that it's in VA.gov's style and meets our plain language standards.

[https://app.zenhub.com/files/133843125/f337e1ba-d8e8-4eea-8596-fb4943cd15a5/download](https://app.zenhub.com/files/133843125/f337e1ba-d8e8-4eea-8596-fb4943cd15a5/download)

Once we've rewritten the content and Laura has reviewed it, we will send to Danielle for her final review before passing back to the product team.

Original intake request: #42694

## Tasks
- [ ] Rework component
- [ ] Review (Laura)
- [ ] Copy edit (Megan)
- [ ] Send to Danielle for final review in ticket # (Megan)

## Acceptance Criteria
- [ ] Content is rewritten and ready for final OCTO-DE review

**Comment by katherine-fung** [comment]
@RLHecht  I have 2 questions about this. 

1. If someone chooses paperless delivery, how will they get the form online? Will they get the 1095-B emailed to them once a year, or will the form be available for download only? 

(One of the message options says: "If you would like to save paper and only get this form online when you need it, you can opt-in to paperless delivery by updating your delivery preferences in your profile.")  

2. Will choosing paperless delivery for the 1095-B affect the delivery preferences for any other communications?

**Comment by katherine-fung** [comment]
Carl replied:

If someone chooses paperless delivery, they will receive a yearly notification via email (or text) that their document is ready for download. The form will not be emailed to them. They will be sent the link to the 1095-B download page for self-service retrieval. Opting into paperless delivery means that they will no longer receive the paper version mailed.

1095-B will be a stand-alone preference. It will not affect any of their other communication preferences.

**Comment by katherine-fung** [comment]
This is the draft message for @laurwill to review: 

**Choose paperless delivery only**

By default, your 1095-B form is sent to you in the mail every year, and available for download online. If you want to stop getting the form in the mail, and download it from this page when you need it, you can choose paperless delivery in your preferences.  Your form will always be available for  download on this page. We'll email or text you once a year when your new form is ready.

Update your delivery preferences for 1095-B form

**Comment by laurwill** [comment]
Thanks @katherine-fung ! This is much clearer, and I think we got to an even more straightforward version over slack.

@megzehn , here's our suggested text for your copyedit. And when you pass to Danielle, can you also note that we're suggesting they use the **information alert** format for this content? That seems like a better fit, since this is sort of a tangent to the main purpose of the page.

**Choose paperless delivery**
We mail you a paper copy of your 1095-B form each year. If you want to stop getting paper forms, you can choose paperless delivery. We'll email or text you once a year when your new form is ready to download here.

Choose paperless delivery for your 1095-B form [link to preferences screen with delivery options]

**Comment by RLHecht** [comment]
@megzehn Just wanted to let you know that we switched up the process order here a bit because the 1095-B team wanted to come to Danielle's office hours to go over the content. I wanted to make sure she was OK with our direction, so I her the content in the above comment for her to review and she commented on it in her OCTO-DE review ticket (#42762). Once Laura is done with it she can let you know so that you can copyedit the more final version. Thanks!

**Comment by megzehn** [comment]
This looks good to me @laurwill. Thanks for passing it on!

**Comment by RLHecht** [comment]
Going to close this ticket as we've handed off the text to the product team and Danielle has reviewed in the other ticket. Thanks for your fast work on this, guys!
