### ISSUE TITLE
[FE] My VA Bug: Payment Info Conditional Logic Fixes

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42763]
## Background
The Benefits, Payments, and Debts Section of My VA is not showing for some users. My VA page is breaking completely for users who are sent paper checks. We found that this is caused by some conditional logic on the front end. We were checking for an account number for users that received paper checks and that was causing the page to crash when users tried to view their payment history. The Payments section was not showing at all for users who did not have multi factor authentication or direct deposit.

## Tasks
- [ ] Remove conditional logic to check for account numners for paper check recipients
- [ ] Remove conditional logic to check for MFA and Direct Deposit
- [ ] Update copy for both to say "We sent you a payment in the amount of X on X date."
- [ ] Validate fix

## Acceptance Criteria
- [ ] Users are able to view their payment history without issue

**Comment by Samara-Strauss** [comment]
[Assuming the FE dashboard is correct](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/), this deploy just went to staging, and I've validated the following use cases:

|Use case|User|Result|
|---------|------|------|
|User who has direct deposit sees the section and is unaffected by these updates| User 36| Pass|
|User who has paper checks sees the section. My VA no longer breaks| Users 82 & 230| Pass -- screenshot below|
|Removed additional gates for this section|Unable to validate, as I don't have a staging user for MHV or DS Logon who has payment info on their dashboard. Will need to validate this through prod analytics.|

**User who receives paper checks**

This test case passed. Screenshot for documentation.

![image](https://user-images.githubusercontent.com/34068740/173875348-e249999c-feac-4562-8272-8d6c001bc625.png)

**Comment by ajakabcin** [comment]
Confirmed as well on staging
