### ISSUE TITLE
[Design] - Profile: Clarify direct deposit fraud block

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#42775]
**Background**

In #41527 we came across error alerts that tell users their account has been flagged for fraud and they need to contact VA to get their account unblocked.

We have outstanding questions how this block works and have a meeting set up with the relevant team to learn more about how this works.  

**Tasks**

- [x] Meet with fraud team
- [ ] Learn how we might test this in staging
- [ ] Document findings in our [use case document](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/use-cases#flags)
- [ ] Update Sketch files

**Comment by andaleliz** [comment]
@SKasimow This should go into the next sprint since we are meeting w/ that team on 6/15

**Comment by andaleliz** [comment]
Update - we met w/ Adam on 6/15 and he's going to put this flag on his own account and let us know the results.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! @mdewey and I were able to see what was going on under the hood during our call with Adam today.  Mark dug into the code a bit after the call, and we learned that our code is not looking for the data they are sending in their API, so we aren't correctly displaying the fraud alert.   We're looking for this key `cnp.payment.flashes.on.record.message` but they're sending us this one `cnp.payment.generic.error.message`

We need to talk to a technical person who owns that API so we can understand exactly what our code needs to look for. Adam didn't seem to know but before I ask him if he can connect us with someone - do you know who that might be? I don't want to offend Adam if indeed it is him 😬 

We also talked about the possibility of gating profile when this flag is in place. Adam mentioned that a fraudster would still have access to a lot of information about the Veteran in the profile, even if they can't update direct deposit. We could prevent further damage to the Veteran if we don't provide any access.  Something to think about for the future.

For documentation purposes, here's what we're receiving from their API when a fraud flag is in place.
```
{
	"errors": [{
		"title": "Unprocessable Entity",
		"detail": "One or more unprocessable user payment properties",
		"code": "126",
		"source": "EVSS::PPIU::Service",
		"status": "422",
		"meta": {
			"messages": [{
				"key": "cnp.payment.generic.error.message",
				"severity": "ERROR",
				"text": "Generic CnP payment update error. Update response: Update Failed: GUIE50041&FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!! FILE: FABTInterfaceCreator.cpp LINE: 350This update is being elevated for additional review due to an Incident Flash associated with this Beneficiary: - An unexpected error was encountered. Please contact the System Administrator. Error is: GUIE50041&FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!! FILE: FABTInterfaceCreator.cpp LINE: 350This update is being elevated for additional review due to an Incident Flash associated with this Beneficiary:"
			}]
		}
	}]
}
```

**Comment by Samara-Strauss** [comment]
I added a note that the VA fraud team is separate from OCTO. Otherwise, the mockups that are linked look incorrect. The Desktop mockup links to the address/phone error state, and the mobile mockup links to the error that shows when we can't connect to the backend.

**Comment by andaleliz** [comment]
Ack! Sorry about those links - they've been fixed now. Note that the mock-ups I linked reflect what is happening today.  I also added an example of what the original design had, when the data was correct.
