### ISSUE TITLE
Pilot Datadog Logging

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#42770]
# 

## Issue Description

The Platform Identity team would like to pilot Datadog logging with the current FedRAMP VA instance. With the sign in service (SiS) releasing soon it has become ever more important that our team has a performant, reliable, and flexible logging and monitoring solution. Datadog has been a fantastic solution when setting up monitoring for our metrics for the SiS. Log searching, aggregation, analysis, and dashboarding however has been a struggle with Loki.

The Identity team wishes to assist and lead, where appropriate, the piloting of Datadog logging. We also want to ensure that logs remain going to their current locations, without a noticeable performance hit to the current logging solution, Loki.  We also plan to use the VA FedRAMP approved solution Datadog version to avoid any possible privacy concerns.

Some of the things we are concerned with when using Loki in the manner we require to support a high visibility production service:

- Logs can be delayed during ingest during high latency issues which if troubleshooting a production issue significantly delays the ability to resolve the issue
- Performance of searching through the logs prevent advanced queries from being run in an efficient manner
- Data analysis over long periods of time which do not have a metric created for them already is not feasible in Loki because the requests for the data timeout if they take too long
- Logs appear to not always be processed and may appear missing, we believe this may be due to a delay in log processing, but it is unclear. For example we will search for something in Loki then 20 minutes later we get more results for the previous query.
- The query language limits results to 5k which causes delays researching logs

---

## Tasks

- [x]  Define requirements for sending logs to VA Datadog
- [x]  Define performance for purposes of comparing log ingest, searching, aggregation, analysis, and dashboard creation:
     - [x] current performance of Loki
     - [x] performance of Loki after enabling dd logs
     - [x] performance of datadog (this will be with Loki in place)
- [x]  Enable / Deploy the enablement of Datadog logs
- [x]  Perform data analysis of Datadog logging
- [x]  Publish results of Datadog logging
- [x]  Determine if pilot should proceed to implementation phase

## Acceptance Criteria
- [x]  Enable Datalog Logs (logs sent to both Loki and Datadog without performance hit to Loki or vets-api servers)
- [x]  Datadog logging features realized
- [x]  Results of analysis published
- [x]  If we move forward with implementing Datadog logs across all envs, then a ticket should be created to deprecate Loki

CC: @codyreinold-usds @mchelen-gov @ph-One @little-oddball @ianhundere

**Comment by joeniquette** [comment]
Requested govcloud datadog access to Jared.Piimauna@ablevets.com:
Put in a ticket here: https://vajira.max.gov/servicedesk/customer/portal/1/DOTSD-16202

Start here for ticket creation: https://login.max.gov/cas/login?service=https%3A%2F%2Fvajira.max.gov%2Fservicedesk%2Fcustomer%2Fportal%2F1%2Fcreate%2F18

**Comment by ianhundere** [comment]
putting a ticket in now

**Comment by ianhundere** [comment]
i just chatted with Matt about this and we both believe it would be best to wait until dual-shipping is off to avoid sending logs to the non-gov instance.

**Comment by nsoutouras** [comment]
Waiting on Ops team

**Comment by ianhundere** [comment]
still waiting for dual shipping to be disabled in BRD.

**Comment by ianhundere** [comment]
no delete:
clusters
`arn:aws-us-gov:eks:us-gov-west-1:008577686731:cluster/dsva-vagov-dev-cluster`
`arn:aws-us-gov:eks:us-gov-west-1:008577686731:cluster/dsva-vagov-staging-cluster`
`arn:aws-us-gov:eks:us-gov-west-1:008577686731:cluster/dsva-vagov-utility-cluster`
`arn:aws-us-gov:eks:us-gov-west-1:008577686731:cluster/dsva-vagov-sandbox-cluster`
`arn:aws-us-gov:eks:us-gov-west-1:008577686731:cluster/dsva-vagov-prod-cluster`

lbs
`arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dvp-prod-*`
`arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/dsva-vagov-prod*`
`arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/net/static-ip-caseflow-prod-lb/9561f5d6cac64565`
`arn:aws-us-gov:elasticloadbalancing:us-gov-west-1:008577686731:loadbalancer/app/appeals-prod-*`

asgs
`arn:aws-us-gov:autoscaling:us-gov-west-1:008577686731:autoScalingGroup:27682372-350e-4408-acb8-797c079636a7:autoScalingGroupName/dsva-vagov-prod-*`

**Comment by ianhundere** [comment]
dual shipping has been disabled for all of BRD and we can go forward with enabling dd logging for dev in BRD. i'll begin this work on Monday.

**Comment by ianhundere** [comment]
finishing up with https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/41203 and then will start collecting baseline metrics for loki before i pull the trigger on enabling dd logs.

**Comment by ianhundere** [comment]
learning a bit about k6 to collect metrics from loki before / after enabling dd logs.

```
> k6 run k6_pract.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: k6_pract.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)


running (00m01.3s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m01.3s/10m0s  1/1 iters, 1 per VU

     data_received..................: 17 kB 13 kB/s
     data_sent......................: 438 B 336 B/s
     http_req_blocked...............: avg=267.83ms min=267.83ms med=267.83ms max=267.83ms p(90)=267.83ms p(95)=267.83ms
     http_req_connecting............: avg=24.56ms  min=24.56ms  med=24.56ms  max=24.56ms  p(90)=24.56ms  p(95)=24.56ms 
     http_req_duration..............: avg=29.56ms  min=29.56ms  med=29.56ms  max=29.56ms  p(90)=29.56ms  p(95)=29.56ms 
       { expected_response:true }...: avg=29.56ms  min=29.56ms  med=29.56ms  max=29.56ms  p(90)=29.56ms  p(95)=29.56ms 
     http_req_failed................: 0.00% ✓ 0        ✗ 1  
     http_req_receiving.............: avg=371µs    min=371µs    med=371µs    max=371µs    p(90)=371µs    p(95)=371µs   
     http_req_sending...............: avg=249µs    min=249µs    med=249µs    max=249µs    p(90)=249µs    p(95)=249µs   
     http_req_tls_handshaking.......: avg=41.01ms  min=41.01ms  med=41.01ms  max=41.01ms  p(90)=41.01ms  p(95)=41.01ms 
     http_req_waiting...............: avg=28.94ms  min=28.94ms  med=28.94ms  max=28.94ms  p(90)=28.94ms  p(95)=28.94ms 
     http_reqs......................: 1     0.766762/s
     iteration_duration.............: avg=1.3s     min=1.3s     med=1.3s     max=1.3s     p(90)=1.3s     p(95)=1.3s    
     iterations.....................: 1     0.766762/s
     vus............................: 1     min=1      max=1
     vus_max........................: 1     min=1      max=1
```

**Comment by ianhundere** [comment]
pr for k8s:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/651

**Comment by ianhundere** [comment]
having issues getting around the socks proxy (similar to when we were unable to run the logcli tool for loki and had to instead use curl w/ the socks5 hostname).

so instead, i'm going to get my metrics from curl like so:
```
> curl -w "@curl-format.txt" -o /dev/null -G -s --socks5-hostname localhost:2001 http://loki-prod.vfs.va.gov/loki/api/v1/query_range --data-urlencode 'query={app=~"vets-api-.+"}' --data-urlencode 'interval=60s' --data-urlencode 'batch=10' --data-urlencode 'direction=forward' --data-urlencode 'limit=1000'
     time_namelookup:  0.009762s
        time_connect:  0.097640s
     time_appconnect:  0.000000s
    time_pretransfer:  0.097717s
       time_redirect:  0.000000s
  time_starttransfer:  8.028111s
                     ----------
          time_total:  8.189741s
```

**Comment by ianhundere** [comment]
before enabling dd logs:
```
     time_namelookup:  0.008655s
        time_connect:  0.088089s
     time_appconnect:  0.000000s
    time_pretransfer:  0.088173s
       time_redirect:  0.000000s
  time_starttransfer:  0.213884s
     time_namelookup:  0.009164s
        time_connect:  0.088241s
     time_appconnect:  0.000000s
    time_pretransfer:  0.088359s
       time_redirect:  0.000000s
  time_starttransfer:  0.210844s
     time_namelookup:  0.009522s
        time_connect:  0.087240s
     time_appconnect:  0.000000s
    time_pretransfer:  0.087332s
       time_redirect:  0.000000s
  time_starttransfer:  0.218157s
     time_namelookup:  0.009201s
        time_connect:  0.102326s
     time_appconnect:  0.000000s
    time_pretransfer:  0.102418s
       time_redirect:  0.000000s
  time_starttransfer:  0.223854s
                     ----------
          time_total:  0.302538s
     time_namelookup:  0.009222s
        time_connect:  0.096706s
     time_appconnect:  0.000000s
    time_pretransfer:  0.096816s
       time_redirect:  0.000000s
  time_starttransfer:  0.224794s
                     ----------
          time_total:  0.302916s
     time_namelookup:  0.009681s
        time_connect:  0.087352s
     time_appconnect:  0.000000s
    time_pretransfer:  0.087551s
       time_redirect:  0.000000s
  time_starttransfer:  0.217167s
                     ----------
          time_total:  0.295097s
```

**Comment by ianhundere** [comment]
BRD MR has been merged: https://github.com/department-of-veterans-affairs/devops/pull/11625

**Comment by ianhundere** [comment]
bit of info in regards to rehydrating old logs:
https://www.datadoghq.com/blog/efficient-log-rehydration-with-datadog/

**Comment by ianhundere** [comment]
loki's response time after enabling dd logs in dev:
```
     time_namelookup:  0.016051s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.016459s

     time_namelookup:  0.008338s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.008665s

     time_namelookup:  0.008592s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.008934s

     time_namelookup:  0.009333s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.009677s

     time_namelookup:  0.008988s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.009356s

     time_namelookup:  0.007265s
        time_connect:  0.000000s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.007587s
```

**Comment by ianhundere** [comment]
lil to no difference at all ^

**Comment by ianhundere** [comment]
we can now use the logging option for the module i built :o)

**Comment by ianhundere** [comment]
many of the logs are getting incorrectly tagged. i'm auditing some of them and will use the following to "retag" them so they'll be defined appropriately (e.g. info, warning, error etc):
https://docs.datadoghq.com/logs/log_configuration/parsing

**Comment by ianhundere** [comment]
excluding logs from the observability namespace:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/76adc44a-6737-4319-83ed-0372693d5970)

**Comment by ianhundere** [comment]
wrapping up loose ends.

todo:
- audit logs
	- what else to exclude 
	- what is tagged correctly
	- what is not tagged correctly
- enable logs in other environments / enable autosync
- create pipeline config with grok parser
	- tf pipeline config

**Comment by ianhundere** [comment]
possibly delete the following namespaces in dev:
`sri-test`
`linkerd`
`internalapi`

**Comment by ianhundere** [comment]
enables dd logs for all other k8s envs:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/660

**Comment by ianhundere** [comment]
above pr is merged, will wait for exclusion of logs begin to show `external-secrets` and `cluster-autoscaler` are no longer being ingested:
https://vagov.ddog-gov.com/logs?query=%28kube_namespace%3Aexternal-secrets%20OR%20pod_name%3Acluster-autoscaler%29&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1658759240000&to_ts=1658759250000&live=false

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/65facfc4-554a-4ded-abfc-abc65cf27af0)
looks good, but going to trigger a scale up to see if the autoscaler is also ignored.

**Comment by ianhundere** [comment]
looks good, onto auditing logs to find anything that's tagged incorrectly (e.g. error, warning, info, etc)

**Comment by ianhundere** [comment]
excluding `sentry` namespace in `utility` env as they're quite chatty and also incorrectly tagged as errors throughout. more info in PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/663

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/507af0bd-bf99-485e-8a58-3e9b46dce1d6)looks good

**Comment by ianhundere** [comment]
argo logs are being tagged incorrectly

**Comment by ianhundere** [comment]
testing pipeline config:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/28d83258-4e87-466f-b6f7-d447429caa22)

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/131656dc-1667-4f75-b922-d5d74dba7d5f)
looks good

**Comment by ianhundere** [comment]
parsers to retag logs:
```
rule1 %{regex("\\w"):level}%{date("MMdd HH:mm:ss.SSSSSS"):timestamp}\s+%{number:logger.thread_id} %{notSpace:logger.name}:%{number:logger.lineno}\] %{data:msg}
rule2 %{data::keyvalue}
```

**Comment by ianhundere** [comment]
logs are being tagged correctly now:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/56fb9bb3-0793-4c41-8feb-3dfa82b4341a)

just need to tf the pipeline confg now

**Comment by ianhundere** [comment]
tf'd pipeline / testing to see if all is well:
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/4dcb8033-24d7-4259-98e9-2648e8feeed4)

**Comment by ianhundere** [comment]
fixed using heredoc syntax, but this is also a thing:
https://github.com/DataDog/terraform-provider-datadog/issues/1380
^ they work, but you have to remove them in order to update them.

this is also helpful for syntax:
https://github.com/DataDog/terraform-provider-datadog/issues/388

**Comment by ianhundere** [comment]
**Summary**
Logs have been enabled in BRD:
[PR](https://github.com/department-of-veterans-affairs/devops/pull/11625/files) / [ansible/build/roles/datadog/tasks/docker-agent.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/datadog/tasks/docker-agent.yml#L23) / [ansible/build/roles/datadog/defaults/main.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/datadog/defaults/main.yml#L20)
and EKS:
[apps/vsp-operations/datadog-agent/dev/values-dev.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/datadog-agent/dev/values-dev.yaml#L16)
**Changes**

**Additional Info**

**Comment by ianhundere** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47100
