### ISSUE TITLE
Content work on Claim Status Tool for when claim decision is ready

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42786]
## Issue Description
The Benefits-1 team asked for content support on the Claim Status Tool for when a claim decision is ready. 

Content block to work on:

<img width="1059" alt="cst_nod" src="https://user-images.githubusercontent.com/136959/172645074-4d600eae-c130-4556-aa22-8d8b5414d49f.png">

We've been asked to do the following:

1. Find and change the eBenefit link to a VA.gov destination
2. Update the content around the eBenefits link
3. Determine if these links are still appropriate:

-Find out how to reopen your claim: https://staging.va.gov/disability/how-to-file-claim/when-to-file/
-File for a VA disability increase: https://staging.va.gov/disability/how-to-file-claim/
-Learn more about filing an appeal: https://staging.va.gov/disability/file-an-appeal/ which redirects to https://staging.va.gov/decision-reviews/legacy-appeals/
-Apply for VA health care: https://staging.va.gov/health-care/how-to-apply/ 

Initial intake request for more background: #42507

## Tasks
- [x] Rework content
- [x] OCTO-DE review (Beth)
- [x] Send revised content to product team in initial intake request (Randi)

## Acceptance Criteria
- [x] Product team has approved revised content

**Comment by aliyahblackmore** [comment]
Updating here: Beth and I met today just to review the direction of the page. I'm pivoting from FMP to do some work on this for the last minutes of today and will continue tomorrow. Also noting that Beth gave an okay for this to be continued next week with Laura, but she did want to meet just to review questions etc.!

**Comment by aliyahblackmore** [comment]
Hi @Mottie ! We are wondering, where does the **"Find out how to reopen your claim"** link currently go?

**Comment by aliyahblackmore** [comment]
Update here: Passed along a draft to Beth via Slack with a few questions.

**Comment by Mottie** [comment]
> -Find out how to reopen your claim: https://staging.va.gov/disability/how-to-file-claim/when-to-file/

**Comment by aliyahblackmore** [comment]
Thanks @Mottie !

**Comment by aliyahblackmore** [comment]
Sharing draft doc here (was passed to Beth) and will review with Laura next week!
[Check your Claim Status Page.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8931197/Check.your.Claim.Status.Page.docx)

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore I like your approach. To answer your questions, instead of "VA toll-free hotline" or "VA call center" let's simplify to "us." And the text link "Check your VA claim or appeal status" is sufficient. I can explain more when I'm back. About both of these answers!

Here's some feedback, and I'd also like @laurwill to take a look, as I'm doing a quick review here:

**Your claim decision is ready** 

We finished reviewing your claim on September 17, 2021. You’ll receive a packet by mail that includes details of the decision on your claim.  

**Note:** Please allow 7 to 10 business days for your packet to arrive before contacting a VA call center. 

If you haven’t received your packet yet, you can check your claim decision online. 
[Check your VA claim or appeal status](https://www.va.gov/claim-or-appeal-status/) 

**Next steps**

**If you agree with your rating,** you don’t need to do anything else.

**If you have new evidence to submit** that shows your condition is service connected, you can ask us to reopen your claim.
[Learn more about Supplemental Claims](https://www.va.gov/decision-reviews/supplemental-claim/)

**If your condition has gotten worse since you filed your claim,** you can file a new claim for an increase in disability compensation.
[Learn more about how to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)

**If you disagree with the decision on your claim,** you can request a decision review. 
[Find out how to choose a decision review option](https://www.va.gov/resources/choosing-a-decision-review-option/)

**If you're not enrolled in VA health care,** you can apply now. 
[Apply for VA health care benefits]

**Comment by RLHecht** [comment]
@Mottie This work isn't completed yet—still needs to go through a few more reviews on our team. We'll post our final content in the initial intake request for you when we're done. Thanks!

**Comment by aliyahblackmore** [comment]
Hi @laurwill this is ready for you to review! I updated by initial word document with Beth's changes (I noted her changes using comments).

Also noting here a question/ask from Beth via Slack: 
"Should the links immediately follow the text rather than be bumped down a line (as is our general style)? The text is within the authenticated experiences and it will probably be good to tighten it up by bringing the links up."
[Check your Claim Status Page.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8954808/Check.your.Claim.Status.Page.docx)

**Comment by laurwill** [comment]
Thanks @aliyahblackmore ! I made a few more suggested edits in the doc and tightened up the link spacing as Beth suggested. Calling out 2 questions here:
- Could we suggest removing the "apply for health care benefits" link? The connection to claim decisions isn't quite clear, and I don't see that link included on other disability claim pages we're linking to. But I may be missing context here!
- I suggested changing the "reopen your claim" to "file a Supplemental Claim," since we don't seem to talk about "reopening" claims elsewhere — but want to confirm that that language isn't needed here.

Can you take a look at my changes, let me know if you have questions, and then pass back to Beth for a final review? Thank you!
[Check.your.Claim.Status.Page_LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8991669/Check.your.Claim.Status.Page_LW.docx)

**Comment by aliyahblackmore** [comment]
Thank @laurwill! Changes were accepted. 

Hi @bethpottsVADEPO - this is ready for your review! There are two comments in the document that need your attention: 

1. Regarding the change from "reopen your claim" to "file a Supplemental Claim" 
2. The "apply for health care benefits" link 
[Check.your.Claim.Status.Page_LW_June 27.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8994600/Check.your.Claim.Status.Page_LW_June.27.docx)

**Comment by bethpottsVADEPO** [comment]
Thanks for all the work on this @aliyahblackmore and @laurwill! 
1. Yes, I like this change. Thank you.
2. Let's leave the apply for HC benefits link. We often call out HC in this way. I understand why you raised this question. This is sort of a blobby bunch of text here--and it does feel a bit like apples and then an orange. If this text were in one of our templates, we'd do it differently. But I do think it's helpful to include even though it isn't as elegant as we'd like. We can discuss more in our Thursday meeting!

**Comment by RLHecht** [comment]
Thanks all! I gave the finalized content to to the product team in their initial intake request. Closing this ticket.
