### ISSUE TITLE
[Design] Create Final Wireframes for Adding Type of Care and Doctor's Name to Pre-Check-in & Check-in Appointment Display Screens

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42793]
## User Story
We need final wireframes for adding type of care and doctor's name fields to displays of appointment information in PRE-CHECK-IN AND CHECK-IN applications

## Tasks
- [ ] Determine what logic VAOS uses and go with their logic for displaying the information
- [ ] Finalize wireframes (4 pages, 2 in Pre-Check-in and 2 in Check-in)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] Add location label to the wireframes of CI and PCI

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by ytsaoca** [comment]
From the limited research we know from the mobile app and VAOS, they would put the order at:
Time
Type of care
Provider name
Facility
Clinic
Location
We follow the order of the mobile app and VAOS.

CI
https://share.goabstract.com/d8c2f34d-dbb1-4991-89d5-06c012ac009c
PCI
https://share.goabstract.com/51258fc0-ccb8-4bd1-903f-fd1981897ce4
