### ISSUE TITLE
[UX] Update Release Artifacts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42797]
## Description
Update various product assets, as necessary, based on changes to the product.

## Tasks
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [x] Update the Poster
- [x] Update user flow diagrams, as necessary
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov

## Acceptance Criteria
- [x] Product Guides are up-to-date (content & screenshots)
- [x] Poster is up-to-date
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [x] R&D articles are up-to-date

**Comment by benbrasso-agile6** [comment]
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/42028

**Comment by benbrasso-agile6** [comment]
@zach-park user flow diagrams for pre check in and check in should be updated. The update is, when there's a touchpoint that includes "time, clinic," it should change to "time, clinic, location"

For example: 

![Screen Shot 2022-08-01 at 11.54.32 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/c61b656b-f47d-4a2f-ad22-ef092edcc3e8)

Let me know when it's complete so I can grab the update from sketch/abstract.

**Comment by benbrasso-agile6** [comment]
Product guides updated in git - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md

I updated the user flow locally. But, Zach still needs to make the changes on his end.

**Comment by benbrasso-agile6** [comment]
No need to update Danielle or contact center

**Comment by zach-park** [comment]
The "Location" fields are added to the latest PCI user flows. It will be shown in the next mater merge.
Cc: @benbrasso-agile6

**Comment by zach-park** [comment]
Merged to the Abstract master branch. Collection links:

Landscape view version:
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=4d0369ce-7ad6-47b1-9bc3-c40521fe7ef7&mode=design

Portrait view version:
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?collectionLayerId=6419aab2-c5a1-43ec-b24e-10f95f0be244&mode=design
