### ISSUE TITLE
Launch Prep Tasks

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#42805]
# Description
In order to be able to launch synthetic monitors we need to finish a few tasks first. Let's complete the below tasks and launch!

Here're the Go / No Go notes: https://vfs.atlassian.net/wiki/spaces/AP/pages/2198700033/5+17+22+Office+Hours+Agenda+and+Notes

# Tasks
- [x] Remove the duplicates on the dashboard
- [x] Verify whether the free account issue is launch blocking
- [x] Prepare launch announcement text (For slack, and for GitHub discussion -- clear launch announcement text with Mike Chelen)
- [x] Decommission old monitors
- [x] Compile all action items from Go/No-go and verify that all action items have been completed
  - [x] Potentially link up synthetic monitoring docs
  - [x] Give more clarity to the heart rate monitor and what it's looking at
  - [x] Export monitors to terraform

# Acceptance Criteria
- [ ] All pre-launch tasks have been completed

**Comment by rjohnson2011** [comment]
I would also add 'Fix alerting based on browser changes' since this is now causing more triggers than desired.

**Comment by pjhill** [comment]
Right, I guess all that was wrapped up in that one little statement. To unpack it a bit more --
1. What are the implications of a single browser being monitored instead of 3?
2. Is there a fundamental problem with only verifying a single browser at a time?
3. What rule changes for alerting are necessary to keep the spirit of the monitoring/alerting?

**Comment by pjhill** [comment]
I've added the detailed action items list to the ticket summary.

**Comment by rjohnson2011** [comment]
I'll look into what effect the browser changes have made on the alerting. I can see for `VA.gov - login' which was failing this morning, was due to having 0 retries enabled. I changed the default retries to 2 for all the Managed by Terraform synthetic monitors, to cut down on false alerting, and go in sync with our initial approach to require 2 / 3 failures before triggering an alert.

**Comment by pjhill** [comment]
These tasks have all been completed.
