### ISSUE TITLE
[Bug] 526ez | Fix U.S. address submitted as APO, DPO or FPO

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#42804]
## Value Statement

**_As a_** frontend developer
**_I want to_** fix the interaction with the military base address interaction temporarily, until a more thorough review is done,
**_So that_** the Veteran doesn't get stuck with the City & State values for military bases when they uncheck the box

## Background Context

[A Report from the Pittsburgh Regional Office](https://dsva.slack.com/archives/C5AGLBNRK/p1654182876865439) stated:
> Veterans/claimants that reside within the United States are having instances of an APO, DPO, 
or FPO erroneously assigned at the time they submit a claim. 

This issue is to fix the problem occurring in form **21-526EZ only**. Other forms 21-686c, 21-674 (part of 686c), and 26-1880 (COE) may have similar issues, but will be handled in a separate ticket.

In form 526, when the "I live on a United States military base outside the United States" checkbox is checked:
- The Country select is disabled and set to "USA"
- The City text input is replaced by a select with Air/Army Post Office (APO), Fleet Post Office (FPO), and Diplomatic Post Office (DPO) choices
- And the State select options are replaced with Armed Forces Americas (AA), Armed Forces Europe (AE), and Armed Forces Pacific (AP) choices

**NOTE**: If choices are made, then the "I live on a United States military base outside the United States" is unchecked, the City will remain set to the APO, DPO or FPO value in the text input, and the State select will remain set as AA, AE or AP until the State is unselected and the City is changed

<details><summary>Address UX</summary>

![Clicking 'I live on a U S military base limits the city & state selection, after making selections, unchecking keeps the settings and limits what the user can type](https://user-images.githubusercontent.com/136959/171702229-9c4b5ed9-41a5-4b98-aa87-3cdbd7ce9a84.gif)</details>

This ticket will be for a temporary fix which restores the Veteran's previous City & State choices when the military base checkbox is unchecked. The full evaluation needed by UX/Design will be accomplished in https://github.com/department-of-veterans-affairs/va.gov-team/issues/42216.

## Tasks

- [ ] Restore the previously set City & State when the "I live on a military base" checkbox is unchecked
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie is this different than #42216?

**Comment by Mottie** [comment]
Based on the [Joe's comment in Slack regarding the checkbox interaction](https://dsva.slack.com/archives/C5AGLBNRK/p1655146149535639?thread_ts=1654182876.865439&cid=C5AGLBNRK), I wasn't sure if this was a final decision on the interaction. And since's he's OOO until June 27, and Matt was asking the status on this work, I went ahead and worked on a fix for 526.

**Comment by saderagsdale** [comment]
@Mottie I think #42120 is a dupe of #42216
