### ISSUE TITLE
Modify GA/Sentry logging for authentication

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#42808]
## Issue Description
Currently we have a vast number of confusion on the logs for Google Analytics when it comes to authentication.  This ticket is to fix and update what we want to capture on the FE as far as authentication metrics are concerned.

## Tasks
- [ ] Document the current GA logging for authentication
- [ ] Add logging and differentiation for OAuth
- [ ] Add logging and differentiation for SAML
- [ ] Add logging and differentiation for different Service Providers
- [ ] Add logging and differentiation for Unified Sign in Page
  - [ ] External redirects to MHV, Cerner, eBenefits, and Mobile(s)
  - [ ] Normal redirects to VA
- [ ] Add logging and differentiation for the normal sign in process (via Modal)
- [ ] Update the GA dashboard for VSP Identity team
  - [ ] Track attempted logins
    - [ ] by various CSP (MHV, DSL, ID.me, LGV)
    - [ ] by authentication method (OAuth, SAML/SSO)
    - [ ] by redirects (USiP, VA)
  - [ ] Track successful logins
    - [ ] by various CSP (MHV, DSL, ID.me, LGV)
    - [ ] by authentication method (OAuth, SAML/SSO)
    - [ ] by redirects (USiP, VA)

## Acceptance Criteria
- [ ] Identity team can accurately see GA data broken down into actionable information

**Comment by AGarcia-Clarity** [comment]
Closing in favor of other logging tools like Sentry.
