### ISSUE TITLE
Audit Governance Team Platform Website pages for old footer

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#42806]
## User Story
As a Platform user, I want to use a consistent Confluence footer on all Platform pages so that updates are easily propagated across all pages.

- Intended Audience: VFS Teams
- Desired Outcome: Updated footer has been applied to Governance Team pages
- Due Date: N/A

## Description
In #41010, we identified that some pages on Platform Website were missing the footer at the bottom of each page to submit feedback and request support, as well as some pages having the old style of footer that was static.
This ticket is to audit Platform Website to determine which pages have the static (text only) footer.

## Artifacts Needing Updates
[Collaboration Cycle Space](https://vfs.atlassian.net/wiki/spaces/CC/overview)
[Getting Started - Platform Orientation Space](https://vfs.atlassian.net/wiki/spaces/GS/pages/1877344532/Platform+Orientation)
[Research/Design Space pages](https://vfs.atlassian.net/wiki/spaces/RD/overview)

## Tasks
- [x] Review [Platform Website Guidelines on Page Footers](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro)
  - Notable quote from guidance: "The page footer doesn’t need to be embedded on navigational landing pages."
- Collaboration Cycle Space
  - [x] Review footers
  - <s>Touchpoints</s>
  - <s>Contact Us</s>
  - <s>Change Log</s>
  - [x] Update any static footers to new format
- Platform Orientation pages
  - [x] Review footers
  - [x] Update any static footers to new format
- Research/Design Space pages
  - [x] Review footers
  - <s>Using Zoom for research</s>
  - <s>iPhone: Start screen share</s>
  - <s>iPhone: Screen recording set-up</s>
  - <s>iPhone: Access chat</s>
  - <s>Android: Start screen share</s>
  - <s>Android: Stop screen share</s>
  - <s>Android: Share device audio</s>
  - <s>Best practice: Focus management</s>
  - <s>Best practice: Accessible links</s>
  - <s>Best practice: Buttons vs Links</s>
  - [x] Update any static footers to new format

## Acceptance Criteria
- [x] Platform Website pages needing updates have been identified
- [x] Platform Website footers have been updated to new format
- [ ] Stories have been created for updating Platform Website
- [ ] User Story need has been fulfilled

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by seanasewell** [comment]
@shiragoodman @chaseakirby Update! I made a list of all the pages that I found in my review in the task section of this issue. I added/updated the footer to all the pages. The strikethrough signifies that they have been added. It's ready for review. Let me know if I missed something. Thanks :)

**Comment by shiragoodman** [comment]
@seanasewell the updated pages look good to me. However I did notice that our "Contact Us" page was somehow dropped. I tagged you and @chaseakirby in the[ thread I started on the #platform-confluence slack channel. ](https://dsva.slack.com/archives/C01AS05BQ79/p1655844457077739)

This ticket can be closed. The Contact Us page is a new issue.
