### ISSUE TITLE
Scoping for Spanish Translation Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42818]
## Background
We are conducting user research and usability testing of the Spanish content for pre-check-in and check-in. Before executing on the research study, we need to scope the work. For instance, decisions need to be made regarding: 
Execution of study:  In-person, moderated or ;  remote, moderated?
Feasibility of Spanish translation support: Are we confident we can have a translator? 
Appointment types: Do we include telephone appointments, in-person or both? 

## Tasks
- [x] Create a list of scoping questions / conversation guide for staff member interview (Ya-ching and Nira to work in Google Doc asynch)
- [x] Share with Patrick/Stephen/Lori
- [ ] Identify staff-member/stakeholder who can speak to us about the Spanish speaking Veteran community, users etc.  (ya-ching to start)
- [x] Ask Stephen/Patrick to help coordinate this meeting
- [x] Reach out to Shane X (?) (and/or Perigean) about talking to Perigean directly on: (Nira to start)
    - translation resources
    - Feasibility of recruiting for this demographic
    - LEP spanish speakers, and/or;
    - bilingual speakers, and/or;
    - caregivers joining to serve as translators
    - Discussion with UX team on any learnings or recommendations 

## Stretch goal / task
- [ ] Schedule staff-member/stakeholder  (if we are able to identify a stakeholder)

## Acceptance Criteria
- [x] Recommendation on scope of the Spanish translated study (link to github page)
- [x] Meeting discussion with UX team

**Comment by niradatta1** [comment]
Our recommendation: Per discussion with UX and product, we plan on conducting user testing (with a content focus) of the Spanish experience with bilingual Veterans/caregivers in a remote, moderated study. This  allows us to focus on other themes/features/areas for the August on-site study. We'll decide on the details of that in the upcoming sprint. @kristenmcconnell @benbrasso-agile6 @loripusey

**Comment by niradatta1** [comment]
Ya-ching is still working with Stephen to identify a staff-member/stakeholder we can speak to. Since that was a task but not part of AC for this ticket, so closing this out.
