### ISSUE TITLE
Check for style consistency on DEA rates page and compare with other education rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42816]
## Issue Description
As part of the effort to migrate education rates pages to VA.gov, we need to ensure that the style is consistent across each of these new pages. 

We need to look at the Drupal draft of the DEA rates page and match bolding choices, enrollment status phrasing, and month range style to the other rates pages we've already worked on and made styling decisions about. 

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=5496

## Tasks
- [x] Edit page for style consistency as described above (Katherine)
- [x] Copyedit (Megan)
- [x] OCTO-DE review (Beth)

## Acceptance Criteria
- [x] Style on DEA rates page is consistent with other new education rates pages

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, thanks for making tweaks in Drupal! I took one more look. This page is now ready for you and stakeholders to review: http://preview-prod.vfs.va.gov/preview?nodeId=5496 

After that, we'll incorporate any feedback from the stakeholders and Megan will do a copyedit.

**Comment by RLHecht** [comment]
@megzehn With Beth OOO this week, she wants to keep this moving and be able to send to the stakeholders. Could you please do your copyedit and let me know when it's ready? Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! This is copyedited. A few notes: I changed cooperative to co-op, since that’s how we have it [on this page and on the side nav](http://preview-prod.vfs.va.gov/preview?nodeId=5572). That was the main change. 

Also, there are two statements that I think need to be reworked for PL. I'm not 100% clear on the meaning, so I'd need to get some clarification before suggesting an alternative version. I'm not sure if it makes sense to flag them for Beth or the stakeholder, but these are the statements:  

- “We may reduce 1 day of your entitlement for every monthly payment of $43.27. This is 1/30th of the full-time rate.”

- “We’ll charge your entitlement at the rate of 1 month for each $1,298.00 paid.”

**Comment by RLHecht** [comment]
This work is completed. Closing ticket.
