### ISSUE TITLE
Clarify post-staging tasks for VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42826]
## User Story
As a VFS team member, I want to understand what tasks are necessary for me to complete post-staging so that I can meet Platform expectations.

Assignee: @CherylEvans 
Peer Reviewer: @jimuhh 

## Description
The actions for VFS teams to follow post-Staging Review are not clear and currently include unnecessary steps. The purpose of this ticket is to modify the Staging Review code block in the Collab Cycle Kickoff - Moderator Responsibilities doc to:

1. Remove the unnecessary steps (sharing launch date and production url)
2. Add a step for the VFS team to submit a ticket with the VA 508 Office if they choose to launch with known accessibility issues (non-launch blocking issues only) - also ask them to share the SNoW ticket #
3. Provide guidance on when the VFS team can close the ticket

In addition, the "Done" pipeline in the Collab Cycle Reviews ZenHub board is no longer necessary. This ticket will also include:

1. Deleting the "Done" pipeline
2. Removing the reference to the "Done" pipeline in the Platform Website Resources page

## Impacted Artifacts
[Collaboration Cycle Kickoff Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[ZenHub Pipelines and their definitions](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources#Pipelines-and-their-definitions)
[Collaboration Cycle Reviews ZenHub Board](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board?repos=133843125)

## Tasks
- [x] Remove Done from [ZenHub Pipelines and their definitions](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources#Pipelines-and-their-definitions)
- [x] Delete checkbox "Update the VFS product information section with the product’s launch date and production URL after it has gone live" from [Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)
- [x] Add "Communicate known accessibility issues to the VA 508 Office via Audit Request." to the VFS Actions post meeting
  - [x] Add "Share ServiceNow ticket number here: ______" as a subbullet to VFS actions in the [Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)
- [x] Add checkbox instructing VFS teams to close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, as well as all post-Staging actions 

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams aren't asked to share their launch date and/or production URL
- [x] VFS teams understand they are responsible for closing the Collaboration Cycle Request ticket once in the Post Staging Review pipeline
- [x] VFS teams understand they are responsible for sharing known open Accessibility issues that will not be fixed prior to launch into Production with the VA 508 Office
- [x] The "Done" pipeline in the Collab Cycle Reviews ZenHub board has been removed and references to the pipeline have been removed from Platform Website

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@chaseakirby the team and I think this ticket may not be necessary, however I'd like your opinion. Lets discuss at our 1:1

**Comment by shiragoodman** [comment]
@chaseakirby per our conversation today, please modify this ticket so that we're deleting the Done pipeline and delete the last checkbox re: launch date and url. Add checkbox for, "Communicate known accessibility issues to teh VA 508 Office via Audit Request. Share ServiceNow ticket number here: ______"

**Comment by CherylEvans** [comment]
@jimuhh Ready for Peer Review

Updated All:

- Cheryl Draft - Copy of Collaboration Cycle Kickoff - Moderator Responsibilities: 

https://vfs.atlassian.net/wiki/spaces/PPST/pages/2289369089/Cheryl+Draft+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities

- https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources#Pipelines-and-their-definitions

- https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board?repos=133843125

**Comment by jimuhh** [comment]
Hi @CherylEvans 
For some reason, it's not letting me comment. Anyhoo, 

1. IMO it would be helpful if the intro briefly set the stage for new team members who might not be as familiar with the process. 
- Why are they doing this? 
- What value does this add to the collaboration cycle? 
- What is the "Kickoff Request?" How does someone receive one?
2. Is "moderator" the right word here? That implies some real-time interaction between participants instead of the asynchronous process described here.  
3. It would be helpful to start with a topic sentence to briefly describe the to end process, for example:

> To cook corn on the cob, you need to select fresh corn, cook it in a way that preserves flavor and serve it hot with just  the right mixture of butter and salt. 

...then go more granular in the steps that follow.

**Comment by CherylEvans** [comment]
@jimuhh My Tasks and AC are changes related to the SR Code Block only.  Thank you!

**Comment by CherylEvans** [comment]
@shiragoodman All Tasks and AC have been completed.  
Changes have been made to source page, Collaboration Cycle Kickoff - Moderator Responsibilities, SR Code Block: https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities
I will close ticket, once I ensure it has been published.

**Comment by CherylEvans** [comment]
@chaseakirby All tasks and peer review completed.  All AC met.
