### ISSUE TITLE
[FE] Implementing address validation modal confirmation screen

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4282]
# Background
Once a Veteran has completed updating their address information and it is successfully saved, the front end should present the user with a confirmation page. 

# Tasks
### Designer 
- [ ] Need to show the scenarios where the confirmation modal would/would not show up to the user. 
- [ ] Need to upload the screenshot to be implemented for the confirmation page.
- [ ] Developer will need the copy and screen shot for the confirmation window. 
- [ ] Upload/Define which scenarios show a confirmation window 

### Front End Dev 
- [ ] Implement the FE build of the confirmation page
- [ ] Validate with pm that the confirmation displays correctly

# Definition of done

- [ ] Confirmation screen has been built and is working on staging. 

## Confirmation screens

After someone sees one of the states of the validation screen above, there are two potential next steps:

1. They edit their address. This will take them back to the edit form.
2. They will either override the determination that their address was a problem, OR they will select a suggested address. Either way, they should move on to a **confirmation screen**. The are **two** states of the confirmation screen:

### Confirmation screen for flows with suggested addresses

- "Update" will close the form and save the new address; "Cancel" or "X" will close the form.
- "View suggested addresses" will take users back to the address validation screen.

**Copy**

### Confirmation screens for flows without suggested addresses

From this screen, "Update" will close the form and save the new address; "Cancel" or "X" will close the form.

**Copy**

**Comment by Justin-Pickett** [comment]
@artistgreen please upload the correct screenshots and copy to this ticket above for the the confirmation screen.

**Comment by artistgreen** [comment]
Confirmation screens
After someone sees one of the states of the validation screen above, there are two potential next steps:

They edit their address. This will take them back to the edit form.
They will either override the determination that their address was a problem, OR they will select a suggested address. Either way, they should move on to a confirmation screen. The are two states of the confirmation screen:
Confirmation screen for flows with suggested addresses
"Update" will close the form and save the new address; "Cancel" or "X" will close the form.
"View suggested addresses" will take users back to the address validation screen.
Copy

Confirmation screens for flows without suggested addresses
From this screen, "Update" will close the form and save the new address; "Cancel" or "X" will close the form.

Copy

**Comment by Justin-Pickett** [comment]
Team discussed removing the confirmation screen 12/19. Team determined we would not include the confirmation screen in the modal. Will be closing this ticket.
