### ISSUE TITLE
[Datadog] Set up dual shipping for eks agents

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#42824]
## Description
In order to have a smooth transition migrating to the dots datadog instance we are looking to ship metrics to the two separate datadog organizations for the time being.  

This is documented here https://docs.datadoghq.com/agent/guide/dual-shipping/?tab=metricsservicechecks#environment-variable-configuration

While there is a specific section for the helm chart, we will not be using this method since we do not want to store api keys within a configMap since it would need to be committed to the github repo as plaintext.  The alternative route we can take here is injecting the needed environment variables from an external secret.

---
## Tasks
- [ ] Create external secret that defines the new datadog endpoint and api key
- [ ] set all of the needed environment variables to said secret within the manifests
- [ ] redeploy the datadog agent

## Acceptance Criteria 
- [ ] metrics are being sent to both datadog organizations from eks

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Staging completed and confirmed working, will follow up with the remainder of the environments

**Comment by mleclerc00** [comment]
quick fix, dumb mistake causing argo to fail deploying the new manifests

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/87067cbcefff3a42a0b8c420ed43f65ec34866d6

**Comment by mleclerc00** [comment]
datadog agents in eks now dual shipping for all clusters

<img width="591" alt="image" src="https://user-images.githubusercontent.com/76792875/173667420-6328d608-bc58-438d-b7ea-f7db15acb59d.png">

**Comment by mleclerc00** [comment]
a few commits to fix processes/apm
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/ab99ce824e4427439f737eda74daadab6467f431
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/ea420bbcf5b4debc68d567f722c534012b35e254
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/19d0eb03cfd7fa1a7307a031be80b08d6bd9444b

https://vagov.ddog-gov.com/apm/traces
https://vagov.ddog-gov.com/process

**Comment by mleclerc00** [comment]
fix profiling/npm/orchestrator dual shipping 

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/9e2c9cff69420201e0b0a59065ba8eece572637c

**Comment by oseasmoran73** [comment]
Dual shipping was enabled during our DataDog transition.

Now that we have officially transitioned to DataDog-Gov, https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/43941 created to remove dual shipping linked

Per requirements, acceptance criteria has been met. Closing out ticket. Please feel free to reopen if you think otherwise
