### ISSUE TITLE
Review the flow for Address Validation Modal 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4283]
e# Background
Need to  review the the address validation flow.
# Tasks

- [ ]  Arthur confirm the functionality  on staging is accounted for. 
- [ ] Review the address validation flow and make sure all frontend states are accounted for
- [ ] If states are not accounted for, work with product manager to break down tickets to get all states implemented correctly.ë
# Definition of done

- [ ] Flow has been reviewed and verified to be complete by FE. If flow is not complete on staging, FE has worked with PM to get the necessary tickets created.

# Address validation design and copy

## Address validation screens

If a user changes their address from the VA.gov profile and that address triggers the address validation, we will put them through the address validation flow.

There are *eight* potential versions of the address validation screen:

### Validation is overridable and there are suggestions

- "Continue" will take users to the confirmation screen; "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Header:  Please confirm your address
Body: We couldn’t confirm your address with the U.S. Postal Service. Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it or choose a suggested address below.

![Override - Suggestions 2](https://user-images.githubusercontent.com/53535009/70937754-e1527880-2012-11ea-8356-e8662fe29ab6.png)

### Validation is overridable but there are NO suggestions

- "Continue" will take users to the confirmation screen; "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  Please confirm your address
Alert Body:  We couldn’t confirm your address with the U.S. Postal Service. Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, please edit it.

![Override - No suggestions 2](https://user-images.githubusercontent.com/53535009/70937920-38f0e400-2013-11ea-8504-f74f16af6777.png)

### Validation is NOT overrideable but there are suggestions

- "Continue" will take users to the confirmation screen; "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  We couldn't verify your address
Alert Body:  We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered or choose a suggested one below.

![No Override - Suggestions 2](https://user-images.githubusercontent.com/53535009/70938034-63db3800-2013-11ea-9ff1-2f390459bea4.png)

### Validation is NOT overrideable and there are NO suggestions

- "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  We couldn't verify your address
Alert Body:  We’re sorry. We couldn’t verify your address with the U.S. Postal Service, so we won’t be able to deliver your VA mail to that address. Please edit the address you entered.

![No Override - No suggestions 2](https://user-images.githubusercontent.com/53535009/70938153-9f760200-2013-11ea-96c7-8093370f2e7a.png)

### Add a unit number with override

- "Continue" will take users to the confirmation screen; "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  Please add a unit number
Alert Body:  It looks like your address is missing a unit number. Please edit your address to add a unit number. If you don't have a unit number and the address you entered below is correct, please select Continue.

![Add missing unit number with override 2](https://user-images.githubusercontent.com/53535009/70938337-f5e34080-2013-11ea-81f7-e7dc5acd7f0a.png)

### Add a unit number WITHOUT override

- "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  Please add a unit number
Alert Body:  We couldn’t verify your address with the U.S. Postal Service because it’s missing a unit number. Please edit your address below to add a unit number.

![Add missing unit number without override 2](https://user-images.githubusercontent.com/53535009/70938529-570b1400-2014-11ea-86aa-119df1a3b9ad.png)

### Edit a unit number with override

- "Continue" will take users to the confirmation screen; "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  Please update or confirm your unit number
Alert Body:  We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address to update the unit number. If your unit number is already correct, please continue with the address you entered below.

![Edit bad unit number with override 2](https://user-images.githubusercontent.com/53535009/70938586-799d2d00-2014-11ea-8964-87d92c2a2a6c.png)

### Edit a unit number WITHOUT override

- "Cancel" or "X" will close the form.
- "Edit address" will take them back to the Edit form.

**Copy:**
Alert Header:  Please update your unit number
Alert Body:  We couldn’t verify your address with the U.S. Postal Service because there may be a problem with the unit number. Please edit your address below to update the unit number.

![Edit bad unit number without override 2](https://user-images.githubusercontent.com/53535009/70938673-9cc7dc80-2014-11ea-92d9-cce77e15dd91.png)

~## Confirmation screens~

~After someone sees one of the states of the validation screen above, there are two potential next steps:~

~1. They edit their address. This will take them back to the edit form.~
~2. They will either override the determination that their address was a problem, OR they will select a suggested address. Either way, they should move on to a **confirmation screen**. The are **two** states of the confirmation screen:~

~### Confirmation screen for flows with suggested addresses~

~- "Update" will close the form and save the new address; "Cancel" or "X" will close the form.~
~- "View suggested addresses" will take users back to the address validation screen.~

~**Copy**~

~![No Override - Suggestion 3](https://user-images.githubusercontent.com/53535009/70939150-a4d44c00-2015-11ea-84b8-2cf2abd7e660.png)~

~### Confirmation screens for flows without suggested addresses~

~From this screen, "Update" will close the form and save the new address; "Cancel" or "X" will close the form.~

~**Copy**~

~![Add missing unit number with override 3](https://user-images.githubusercontent.com/53535009/70939197-c1708400-2015-11ea-9f9c-3cb5758010cb.png)~

**Comment by Justin-Pickett** [comment]
@artistgreen can you update this ticket with the appropriate screenshots and copy. Once this is completed we can get it ready to be handed off to FE.

**Comment by Justin-Pickett** [comment]
@artistgreen on 12//19 the team discussed and agreed on removing the confirmation screens to the above flow. Please let me or @Samara-Strauss know if you have any questions.  I will be removing the confirmation screens in this ticket.
