### ISSUE TITLE
Discovery for raising issues pre-meeting (aka communication expectations bw VFS & Platform)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42835]
## User Story
As a VFS team, I want a consistent communication method with the Governance team related to Collaboration Cycle.

As a Governance team, I want a defined location to discuss questions and issues with the VFS team prior to the meeting.

Assignee: @claytonzook 
Peer Reviewer: @briandeconinck 

## Description
With the recent release of our Collaboration Cycle Request ticket, we need to define our preferred method of communicating with VFS teams.
Currently our guidance in "How to provide feedback" still references commenting in the ticket. We'd prefer to not instruct VFS teams to comment in the ticket because:

- The ticket could easily become overwhelmed with too many comments
- The VFS team could attach artifacts and/or share links in the comments, making it difficult to find
- VFS team responses to questions from Governance team in the comments can sometimes be slow. We'd like more immediate, real-time responses, if/when necessary

Our ideal solution would include communication via Slack with our options being:

- utilizing the VFS teams existing Slack channel
- creating a temporary private Slack channel for this specific Collaboration Cycle Request
- utilizing the #vfs-platform-support thread that the VFS team member started when requesting the specific touchpoint meeting

We'd like to find out which of the above options the VFS team would prefer.

## Impacted Artifacts

- [Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2292776961/Collaboration+Cycle+Communications+Survey+Research+Plan)
- [Survey](https://dj540s05.optimalworkshop.com/questions/collabcyclecommunication)
(This is stored in Optimal workshop under Nancy Smith's Team in folder Governance Team)
- [Research findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2298249403/2022-07+Collaboration+Cycle+Communications+Survey+Research+findings)

## Tasks
- [x] Put together a [Research Plan](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1474560037/TEMPLATE+Platform+Research+Plan) for this study.
   - No need for a conversation guide as this will be an unmoderated study.
   - this is a small research study so this task should not take the entire sprint
- [x] Research Plan should include the following methodology:  Optimal Workshop survey.[ See thread](https://dsva.slack.com/archives/GNF5GSD9N/p1658155499853819) with @naomimarcussen for more details. 
- [x] Ideally, the questions in the Optimal Workshop survey should include:
   - If you needed to contact Governance team about your upcoming Design Intent/Midpoint Review/Staging Review, what is your preferred form of contact? (with multiple choice)
   - If Governance team needed to contact you about your upcoming Design Intent/Midpoint Review/Staging Review, what is your preferred form of contact? (with multiple choice)
- [x] Create Optimal Workshop survey
- [x] Research Plan and Optimal Workshop survey are both peer reviewed
- [x] Survey is shared with identified participants
- [x] Close survey after appropriate timeframe
- [x] Analyze results
- [x] Document findings using [Research findings template. ](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2029617251/TEMPLATE+Research+findings)
- [x] Create a new issue ticket for Governance team to implement the solution - #45080

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team has completed research with VFS to understand their communication preferences in Collaboration Cycle
- [x] A preferred communication channel has been identified and there is an issue ticket for implementation of the solution

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
@shiragoodman Tagging you since this ticket is changing to doing discovery/research

**Comment by shiragoodman** [comment]
Thoughts around questions for discovery:

1. You have scheduled your Design Intent and now have a question regarding the Collaboration Cycle process. Which is your _preferred approach_ for contacting Governance team?

- DM the person you think can help on Slack
- Ask in #vfs-platform-support
- Ask in #vfs-all-teams
- Comment on the Collab Cycle Request/Design Intent gh ticket

**Comment by briandeconinck** [comment]
@claytonzook This all looks good to me! All looks very straightforward.

**Comment by claytonzook** [comment]
@briandeconinck - Ready for peer review!

**Comment by briandeconinck** [comment]
@claytonzook This all looks great!
