### ISSUE TITLE
Review Collab Cycle Feedback for Staging template in gh

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42831]
## User Story
As a Governance team member, I want the Collab Cycle Feedback for Staging template to reference the Collaboration Cycle Request ticket to reduce potential confusion.

As a VFS team member, I want documentation to reference the Collaboration Cycle Request ticket so that I know templates are up to date.

Assignee: @allison0034 
Peer Reviewer: @seanasewell 

## Description
The Collab Cycle Feedback for Staging template references collab cycle touchpoint meeting epic and Feedback pipeline in the Platform directions section.
Both of these processes have been retired and should be removed from the template.

## Impacted Artifacts
[Collab Cycle Feedback for Staging - Platform Directions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md)

## Tasks
- [x] Remove "Link to collab cycle touchpoint meeting epic"
- [x] Add "Link to Collaboration Cycle Request epic"
- [x] Remove "Move to the Feedback pipeline on the Platform Product Support board"
- [x] Compare the template to the output of the Drafting Template
  - Note: Can use a recent staging review issue ticket for comparison
  - [x] Update template to match current Drafting Template output

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team reviewers have guidance to attach ticket to Collaboration Cycle Request epic
- [x] Governance team members understand that they do not need to move to the Feedback pipeline

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at planning
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@allison0034 correct. do not delete the "Platform directions" from the template. The DraftingTemplale doesn't need this section as it's generated thru the GitHub upload process, so the instructions aren't necessary.

@seanasewell I have added you as peer reviewer. Please let Allison or myself know if you have any questions.

**Comment by allison0034** [comment]
@seanasewell the [template pr](https://github.com/department-of-veterans-affairs/va.gov-team/blob/889dbae0a816308ea5751e6a05ad1f3a09f1e607/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md) is ready for your review.

**Comment by seanasewell** [comment]
@allison0034 Peer review complete. Looks good!

**Comment by allison0034** [comment]
@shiragoodman PR merged and ticket closed
