### ISSUE TITLE
Update Calendly directions for adding VFS team members to invite

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42849]
## User Story
As a VFS team member, I want instructions to invite my team so that I can complete scheduling and include relevant team members.

As a Governance team, I want pertinent VFS team members invited to touchpoints so that discussions and feedback is shared with relevant team members.

Assignee:
Peer Reviewer:

## Description
Our touchpoint instructions in the CC Request ticket instructs teams "Click "Add Guests" and enter the VFS meeting attendees email addresses"
Our Platform Website instructions ([Design Intent Instructions](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Attendees)) detail which VFS team members are required and others as applicable.

This ticket is to add details in Calendly for recommended team members to invite at time of scheduling.

## Impacted Artifacts
[Design Intent/Midpoint Review Calendly](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review?month=2022-07)
[Staging Review Calendly](https://calendly.com/collaboration-cycle/staging-review?month=2022-07)

## Tasks
- Design Intent/Midpoint Review Calendly
- [ ] Review Design Intent Invitees recommended on [Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Attendees)
- [ ] Review Midpoint Review Invitees recommended on [Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
- [ ] Add details to Calendly recommending which VFS team members to invite

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS teams are aware how and who to invite while creating the Calendly invite
- [ ] Our Governance team is confident that VFS teams have guidance on who to invite to touchpoint meetings

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@chaseakirby we discussed as a team and think that this ticket may not be necessary. I'd like to review with you before we close out completely.
