### ISSUE TITLE
Remove deprecated Design Intent, Midpoint Review, and Staging Review templates

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42846]
## User Story
As a VFS team member, I want only guidance for the Collaboration Cycle Request process to reduce confusion.

As a Governance team, I want to detail current touchpoint request process only when most teams are using the Collaboration Cycle Request process so that teams do not use the deprecated touchpoint templates.

Assignee: @CherylEvans 
Peer Reviewer: @it-harrison 

## Description
When we released the Collaboration Cycle Request ticket, we knew that it would take time for teams to complete their in progress Collaboration Cycles. 
We decided 3 months was an appropriate amount of time to have instructions for the new and old process so now we will remove the instructions for the old process referencing individual touchpoint tickets.

**11/17/2022 update:** It has been longer than 3 months and VFS teams are still using the old DI, MPR and SR templates. It is confusing for VFS teams with 2 template options for each touchpoint, and Governance team would like to finally retire the old templates. Regardless of where VFS teams are in their Collab Cycle journey, all VFS teams will now be directed to use the Collaboration Cycle Request template. 

## Impacted Artifacts
[Design Intent - Request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent#Request)
[Midpoint Review - Request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review#Request)
[Staging Review - Request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review#Request)

## Tasks
- [x] Remove "For those who started the Collaboration Cycle process prior to May 26th, 2022" instructions for each touchpoint page.
- [x] Review all Collaboration Cycle pages on Platform Website for any references to the 2 different paths. Flag any mentions and add to this ticket for updates.
- [x] Delete the Design Intent github template
- [x] Delete the Midpoint Review github template
- [x] Delete the Staging Review github template
- [x] Create Change history post notifying VFS teams that all touchpoint requests must now be made through the Collaboration Cycle Request template. Include link to Zenhub Collaboration Cycle Reviews board so VFS teams are easily able to locate open tickets.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are able to follow guidance for the Collaboration Cycle Request ticket.
- [x] All VFS teams are scheduling touchpoints via the Collaboration Cycle Request ticket.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@it-harrison [DI Pull Request ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/50134)
[Staging Review Pull Request ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/50135)
[MPR Pull Request ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/50136)

**Comment by CherylEvans** [comment]
@it-harrison Here is my [Draft ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2446131201/42846+-+Cheryl+Copy+of+Copy+of+Change+history+2)for the change history log, for you to review. :-)

**Comment by it-harrison** [comment]
> @it-harrison Here is my [Draft ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2446131201/42846+-+Cheryl+Copy+of+Copy+of+Change+history+2)for the change history log, for you to review. :-)
Looks good, Cheryl - I added one comment.

**Comment by CherylEvans** [comment]
@it-harrison Will you review the [Staging Review Pull Request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/50135) please? :-)
