### ISSUE TITLE
Implement automated Slack notifications for when Collab Cycle Request ticket is created

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#42853]
## User Story
As a Governance team member, I want automated notifications when a Collaboration Cycle Request ticket is created so that I can review and respond quickly.

As a VFS team member, I want the Governance team to automatically be notified so that I can reduce the amount of steps to request a kickoff review.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
For the MVP launch of the Collaboration Cycle Request ticket # 41201 we included a required checkbox detailing "Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel." so that VFS teams knew that they needed to post in slack and so that the information would be available after submitting the YAML template.
Brian researched the capability of automating Slack notifications and GitHub integrations and [summarized his findings in a comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41201#issuecomment-1125208076). We decided as a team that this was outside the scope of MVP and should be added after launch.

## Impacted Artifacts
- [Platform-Collaboration-Cycle Slack channel](https://dsva.slack.com/archives/G01DXP10GCA)
- [New - Managing GitHub-to-Slack Notifications Documentation
](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2294448280/Draft+Brian+-+Managing+GitHub-to-Slack+Notifications)
- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Subscribe the Platform-Collaboration-Cycle channel to GitHub notifications
- [x] Unsubscribe from all other GitHub notifications
- [x] Subscribe to Collaboration Cycle Request Yaml issues only
- [x] Create documentation detailing how to subscribe and unsubscribe from notifications
- [x] Remove step from Kickoff Moderator Responsibilities to post in platform-collaboration-cycle slack channel

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Members of Platform-Collaboration-Cycle channel are notified of newly created CC Requests
- [x] Slack is able to display GitHub notifications in Platform-Collaboration-Cycle

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
Subscribed #platform-collaboration-cycle to the desired notifications. Will watch to see if it works as intended when the next request is submitted!

**Comment by shiragoodman** [comment]
@briandeconinck maybe we could speed the process along and submit a TEST ticket. What do you think?

**Comment by briandeconinck** [comment]
@shiragoodman Yep, I can do a test ticket. Coming through in a few minutes...

**Comment by briandeconinck** [comment]
@allison0034 This is ready for peer review. I have:
- Enabled Slack notifications in #platform-collaboration-cycle
- Created [documentation on how to subscribe/unsubscribe](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2294448280/Draft+Brian+-+Managing+GitHub-to-Slack+Notifications)
- Removed Step 8 from the [CC Kickoff Moderator Responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

For reference, this was the now-removed Step 8:
> Step 8
>
> Post in the #platform-collaboration-cycle channel on Slack:
> 
> “Collaboration Cycle Request - Team Name - Product Name - Feature Name submitted. Design Intent Pending.” where the blue italicized text is a link to the Collaboration Cycle Request ticket.

**Comment by allison0034** [comment]
@briandeconinck this looks good to me!
