### ISSUE TITLE
[bug] Notice of Disagreement | Make NOD submissions retryable 

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#42869]
## Value Statement
**_As a_** system of record
**_I want to_** automatically retry submitting a notice of disagreement form
**_So that_** submissions don't fail due to planned or unplanned maintenance. 

---
## Background context
Need to add more words, but consider making HLR\NOD user submissions retryable sidekiq queued jobs, like 526 submissions.

The current lighthouse endpoint we use to submit HLRs and NODs is pretty reliable, but the upstream va "systems of record" they rely on are sometimes down for maintenance, both planned and unplanned. 

We already have some common code avail for sidekiq job tracking, see vets-api 526 submission worker inheritance and mix-ins to see how the shared jobtracker code work.

Also, might want to look at the current lighthouse NoD endpoint internals to make sure they don't already have a retry method in place(for example, perhaps they are already using sidekiq, but they don't have wait long enough between retries).

For HLRs, vets-api submission errors are stored in a table called personal information log, so when looking at this ticket, might want to have a look at that just to see how many HLR are not being submitted.:

```
ps = PersonalInformationLog.where( "error_class LIKE '%HigherLevelReviewsController#create%'").order(Arel.sql("data ->'user'->>'icn' ASC"), :updated_at); nil
```

## Acceptance Criteria
- [ ] _When a NoD submission is interrupted due to planned or unplanned maintenance, it is stored as a queued job and successfully submitted later._

## Out of scope
Other submission forms. 

## Tasks
- [ ] Make these participate in sidekiq.

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Related to #21326

**Comment by saderagsdale** [comment]
Break into smaller tickets.

**Comment by saderagsdale** [comment]
Related to #21326 and #42976

**Comment by saderagsdale** [comment]
Needs FE details.
