### ISSUE TITLE
[FE, PM] My VA Redirect: Launch to 25% of Users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42876]
## Background
Once we have completed staging review and QA for the My VA Redirect initiative we will be ready to launch to 25% of VA.gov users.

## Tasks
- [x] Flip feature flag on for 25% of users
- [ ] Monitor Analytics post launch

## Acceptance Criteria
- [ ] 25% of VA.gov users in Production are redirected to MyVA from the login on the VA.gov homepage

**Comment by ajakabcin** [comment]
Tentatively scheduled for week of 8/29

**Comment by ajakabcin** [comment]
Redirect enabled for 25% of production users this morning at around 9:30 am 👍
