### ISSUE TITLE
[FE, PM] My VA Redirect: Launch Feature for All Users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42881]
## Background
Once we have completed staging review and QA for the My VA Redirect initiative we will be ready to launch to 100% of VA.gov users.

## Tasks
- [X] Flip feature flag on for 100% of users
- [x] Monitor Analytics post launch

## Acceptance Criteria
- [x] All VA.gov users in Production are redirected to MyVA from the login on the VA.gov homepage

**Comment by ajakabcin** [comment]
Tentatively scheduled for week of 9/12
