### ISSUE TITLE
Upload PDF versions of FSR VHA requests to S3

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#42884]
## Issue Description
S3 is the standard implementation within vets-api to upload and store files, in this case FSR PDFs we have generated. Two options to look at:

- [Uploader](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/uploaders/form1010cg/poa_uploader.rb) class to be used by a [model](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form1010cg/attachment.rb)
- [Worker](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/form1095/new1095_bs_job.rb) to be triggered upon PDF generation

We will implement a worker, with the idea to move FSRs to a model based implementation in future state

---
## Tasks
- [ ] Create S3 bucket to deliver PDFs
- [ ] Add sidekiq worker to upload to S3
- [ ] Call worker when a PDF is generated

## Acceptance Criteria
- [ ] When an FSR PDF is generated after submission, the resulting file is upload to S3
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Accidental duplicate of #42882
