### ISSUE TITLE
[FE, PM] My VA Redirect: Launch Feature to 50% of Users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42880]
## Background
Once we have completed staging review and QA for the My VA Redirect initiative we will be ready to launch to 50% of VA.gov users.

## Tasks
- [ ] Flip feature flag on for 50% of users
- [ ] Monitor Analytics post launch

## Acceptance Criteria
- [ ] 50% of VA.gov users in Production are redirected to MyVA from the login on the VA.gov homepage

**Comment by tmitchellgcio** [comment]
Deployed to 50% as of 9/6
