### ISSUE TITLE
Placeholder Console UI Q3: Transition Plan for Console at the end of Q3 2022

### ISSUE THREAD

**Issue by lhelmer** [department-of-veterans-affairs/va.gov-team#42894]
## Problem Statement 
How might we make sure Platform teams picking up the work of Console UI after Q3 2022 are able to continue working on certain aspects of the Console?

## Hypothesis or Bet
If we document the Console's process and implementation using Playbook documentation, we will prepare the Platform Teams for taking over this work.

## We will know we're done when... ("Definition of Done")
Creating playbooks for: 
- [ ] Write documentation for Console Plugin Playbook @jchapin @sdk-irl + any other devs
- [ ] Write documentation Console Onboarding Playbook @rbsingleton @JChabuk @lhelmer 
- [ ] Write documentation for User Feedback Playbook (GA+Medallia) @lhelmer 
- [ ] Write documentation for Performance reporting Playbook @jchapin 
- [ ] Write documentation  for Design System Playbook

## Known Blockers/Dependencies 
Testing may be limited if platform teams are unable to participate in giving feedback for our Playbook documentation.

## Projected Launch Date
End of Q3 2022

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platforminitiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] User feedback of Console Plugin Playbook
- [ ] User feedback of Console Onboarding Playbook
- [ ] User feedback of Console User Feedback Playbook (GA+Medallia)
- [ ] User Feedback of Performance reporting Playbook
- [ ] User Feedback of Design System Playbook

### ... documented?

- [ ] Console Plugin Playbook (multiple documents)
- [ ] Console Onboarding Playbook (multiple documents)
- [ ] Console User Feedback Playbook (GA+Medallia) (multiple documents)
- [ ] Console Performance reporting Playbook (multiple documents)

- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _Console Product Playbooks_
* **Product Outline**: _link to Product Outline_

### Testing

- [ ] User feedback of Console Plugin Playbook
- [ ] User feedback of Console Onboarding Playbook
- [ ] User feedback of Console User Feedback Playbook (GA+Medallia)
- [ ] User Feedback of Performance reporting Playbook
- [ ] User Feedback of Design System Playbook

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by jchapin** [comment]
@lhelmer @ActualAbby it's possible to relate GitHub issues to each other simply by putting the URL after the checklist item. That will also automatically check the item off when the issue is closed. This is cleaner than re-tagging users.

<img width="804" alt="Screen Shot 2022-06-17 at 12 33 12 PM" src="https://user-images.githubusercontent.com/116142/174339874-5bc468b0-a564-4723-a941-02770a06945f.png">

<img width="893" alt="Screen Shot 2022-06-17 at 12 33 19 PM" src="https://user-images.githubusercontent.com/116142/174339879-66a7a436-5397-48b3-b074-23401a92eb16.png">

**Comment by sdk-irl** [comment]
LInked epics for each Playbook. Still attaching tickets to sub epics
