### ISSUE TITLE
Staging Review [Public Websites - IE11 Deprecation Alert]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#42893]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

***Note: I'm not sure a synchronous meeting is required due to the very small scope of the change (adding a banner for ie11 users). Please review the included details and let me know if you want me to schedule a meeting.*** (Wes)

**VFS Product Manager**
- [ ]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [ ]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [ ]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

***Per discussion with Dave Conlon, we did not 

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information

**Review instance for PR:**
~~http://40d20fe5333904eacbe11453217418ba.review.vetsgov-internal/~~
~~https://http://e987b020a95d585d61b0f2beec7b5cf2.review.vetsgov-internal/ (as of 6/16 10:45 am; not sure why it changed)~~
http://12c1ab764b2f5ea5e5311f72783084d8.review.vetsgov-internal/

NO Test user is necessary – but you must be using Internet Explorer to see the banner.

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/ie11-deprecation-banner/product-outline.md) 
 
  

- [ ] Release plan with the "Planning" sections completed 

 

### Content artifacts 

- [x] Your product’s [content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41914)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] List of known issues

     •	Issue 1
     •	Issue 2
     •	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by ddzz** [comment]
@wesrowe Were you able to get a review instance working for this change? The updated link in the description doesn't work.

**Comment by wesrowe** [comment]
@ddzz, I have a support ticket going in slack for this; sorry about the bad url. This is my first time working with Review Instances for code PRs.

**Comment by shiragoodman** [comment]
@wesrowe please keep us posted. Due to the short turnaround time, we may have to push this to Tuesday if not resolved today (since Monday is a holiday).

**Comment by shiragoodman** [comment]
Meeting Recording:
https://oddball-io.zoom.us/rec/share/B6JI3JZ7wotpDG0e4sr8PymmmqZnYPFqkWzph_bjwoBEtaYFzIonAejrqYKWHE_K.EmtkMd-pijSGS3ET

Access Passcode: WE26M5e+
