### ISSUE TITLE
CST: Notifications

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#42905]
## Value Statement
**_As a_** veteran
**_I want to_** be alerted when key details related to my claim change or there's a new action item I need to take
**_So that_** I don't have to keep visiting the CST constantly and hitting "refresh", I can just go to the tool when it has something new to tell me. 

---
## Background Context
The VA Notify team technically sends out notifications for different VA teams, but the list segmentation, logic, and criteria is set by each individual team (there is no CRM or marketing tool where these things are set). Whatever solution we come up with has to involve defining and coding the triggers and logic for when these messages get sent and how content will change for each use case. 

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
