### ISSUE TITLE
Audit education benefit pages and R&S articles for rates mentions

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42900]
## Issue Description
Now that we are migrating the education rates pages to VA.gov, we need to record where we discuss rates or link to legacy rates pages on our other pages so that we can update these once our pages are published. We want our rates pages to be the single source of truth and do not want to have to update information in multiple places each year when there are new rates.

Example: [This page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/) has a dollar figure under "What benefits can I get?"

We need to look at:
- Education benefit detail pages
- Education R&S articles (including [this one](http://preview-prod.vfs.va.gov/preview?nodeId=44718) in draft)

We should create a list in this ticket of pages we will need to update or change. There will be a separate ticket to complete the work once our pages are live. 

## Tasks
- [x] Audit education pages (benefit detail and R&S) for rates mentions and links
- [x] Create list of pages where we need to make updates to content or links

## Acceptance Criteria
- [x] We have a list of pages to update once our education rates pages are live

**Comment by megzehn** [comment]
Here's a list of articles that mentions education benefit rates or links to the legacy education benefit rates table. 

I looked in the [Education section of the site, using the left navigation](https://www.va.gov/education/) and the [Education and Training part of R&S. ](https://www.va.gov/resources/education-and-training/)

**Education Rates mentions and links:** 

[ ] https://www.va.gov/education/benefit-rates/

[ ] https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/

[ ] https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/

 [ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training/

 [ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance/
 (Doesn’t link to legacy table, but gives a $$ figure)

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/
(Doesn’t link to legacy table, but gives a $$ figure)

 [ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs/

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/co-op-training/

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/

[ ] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/

 [ ] https://www.va.gov/education/survivor-dependent-benefits/

 [ ] https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/
(Doesn’t link to legacy table, but gives a $$ figure)

 [ ] https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/

[ ] https://www.va.gov/education/other-va-education-benefits/stem-scholarship/

[ ] https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/
(Doesn’t link to legacy table, but gives a $$ figure)

 **R&S pages**

[ ] https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/

[ ] https://www.va.gov/resources/how-va-education-benefit-payments-affect-your-taxes/
(Maybe? This discusses $$, but it doesn’t link to a legacy table)

[ ] https://www.va.gov/resources/how-we-determine-your-post-911-gi-bill-coverage/

[ ] https://www.va.gov/resources/will-i-have-to-pay-back-the-gi-bill-benefits-i-used-if-i-fail-a-class/
 (Under related information)

**Comment by megzehn** [comment]
@RLHecht this is ready for your review

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you create a ticket for the next sprint, if you haven't already, for making the changes to these pages identified in the audit? The team will have to wait to make the link fixes until the new rates pages are live, and probably even the ones that require some rewriting don't make sense to get started on until then since those will also need the nodes for the new rates pages to link to. This is work that might be brought into this sprint, but we're not sure yet.
