### ISSUE TITLE
Add Sessions/SiS attribute to session_data serializer

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#42907]
## Issue Description
The `vets-website` frontend needs to be able to query the `vets-api` backend to determine whether a user has been authenticated through `sessions_controller`/IAM or `sign_in_controller`/SIS. A new attribute should be added to the user profile's `session_data` to provide this information.

## Tasks
- [x] add `auth_broker` parameter to user_identity `sign_in` hashes, with values of `ial` & `sis`
- [x] pull `auth_broker` information from the user_identity when serializing user information in `app/servifes/users/profile.rb`
- [x] update related user spec factories to include new attribute
