### ISSUE TITLE
CST: File Upload Experience

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#42901]
## Value Statement
**_As a_** veteran
**_I want to_** know when it's important to upload files, be able to upload files, and know when uploading files fails
**_So that_**  my claim can be processed as quickly as possible with the highest chance of receiving an outcome favorable to me. 

---
## Background Context

Currently large files sometimes "fail out" after it gets parked in S3, but there's no way for an end user to know. Also, the request to upload additional information isn't easily discovered by end users. 

## Acceptance Criteria
- [ ] Upload action items are discoverable by most users
- [ ] There is a clear mechanism for notifying users when uploading documents fails, both at the time of entry and if downstream services fail to send information to VA
- [ ] Type of documentation matches each use case

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
