### ISSUE TITLE
CST: Improve claims status information

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#42904]
## Value Statement
**_As a_** veteran
**_I want to_** have a better understanding of where my claim sits in the overall process, receive information about decision timing (when I'll have a decision), and know when to take action on items related to my claim
**_So that_** I can manage my own expectations around when I might get disability income and/or take actions that might help move my claim along in the process.

---
## Background Context
-Research: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/SummaryCSTresearchOct2021/Summary%20CST%20Research%2C%20Oct%202021.pdf

Users desired:

- clear action items associated with claim
- clear, defined steps about where the claim was in the overall process
- better verification that VA actually received documents
- detailed time estimates

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
