### ISSUE TITLE
[Datadog] Setup private locations in ddgov instance

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#42908]
## Description
In order to run synthetic tests in the new ddgov datadog organization we will need to setup some private locations attached to it.  There is no way to migrate the current private locations to the new org so we will need to start fresh.  The private locations allow us to run synthetic tests against resources that are only reachable within the VA network.

There are two components to this

- creating the private locations in datadog ui itself https://docs.datadoghq.com/getting_started/synthetics/private_location/#create-your-private-location

- using the private location helm chart to deploy the configurations generated in the step above https://github.com/DataDog/helm-charts/tree/main/charts/synthetics-private-location

---
## Tasks
- [ ] create private locations within the datadog ui to generate configurations per private location
- [ ] deploy each configuration per environment with the datadog private location helm chart

## Acceptance Criteria 
- [ ] Private locations show up within datadog as an option for running synthetic tests

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
