### ISSUE TITLE
[Beats agent] Investigate reports of duplicate logs being sent to CSOC

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42917]
## Description
@joeniquette received a question from the CLS folks around the current logging sent to CSOC via the beats agent. They said yesterday that the logs sent took up about 40% of all bandwidth resources. 

Their question is: "It appeared that the auditd log was going crazy.  When you guys create your images do you clean the old logs off the system before redeploying? If that is not the case it could be that when you guys redeploy it's gathering all of the audit logs on all of the systems. resulting in non-needed logs/duplicate logs."

## Background/context 
Related issue: 
- #40935 
- #41791 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Investigate the possibility that duplicate logs are being sent due to the way the images are built/deployed
- [ ] Implement a fix for the issue 

## Acceptance Criteria 
- [ ] Ensure that duplicate logs are not being sent to CSOC 
- [ ] Confirm with Joe Niquette, CLS, or others as needed

**Comment by jhouse-solvd** [comment]
We discussed this as a team today. We've been troubleshooting other high-priority support issues that appear related to the Beats agent installation. Some instances (GitHub Actions runners for example) experience failure due to exhaustion of resources potentially caused or exacerbated by the Beats agent. 

We have not yet had the bandwidth to troubleshoot this specific issue. Please let us know if it needs to be prioritized over other existing issues.

**Comment by ph-One** [comment]
Implemented additional log cleanup and redeployed EKS instances. Other AMIs (GitHub Runners, etc) already had this implemented. https://github.com/department-of-veterans-affairs/devops/pull/11484/files
