### ISSUE TITLE
[FE & Design] My VA Payment Info: Audit technical functionality

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#42911]
## Background
We've come across a few issues recently with this section on My VA and discovered there's quite a bit of confusion within the team as to how this section _should_ be functioning in its current _v1_ state. While we are actively working on _v2_ of the section, we still need to understand the current state of the feature so we can continue to accurately diagnose issues and understand when it's not functioning the way it should. This is critical for the long term growth and usability of the section.

## Tasks
- [x] (Design) Document (in the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)) when and for whom the feature shows
- [x] (FE & Design) Audit/review the code of the Benefit Payments and Debts section of My VA to determine how it is _currently_ functioning, specifically **when does it show and for whom**
- [x] Schedule a meeting with the team to review your findings 

## Acceptance Criteria
- [x] The FE documentation is updated with an explanation of how the product is currently functioning in terms of when and for whom the feature shows
- [x] The team has met and reviewed the documentation to determine if changes are needed and what next steps should be
