### ISSUE TITLE
[Vets-API / EKS] Ability to run rails console in dev

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#42921]
## Description
As a platform team developer, I need the ability to run the rails console that I can troubleshoot application behavior

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1655300551091939

---
## Tasks
- [ ] Platform-infrastructure needs to come to a decision on how we want to provide the ability for developers to reach the rails console in EKS-deployed vets-api and implement a solution

## Acceptance Criteria 
- [ ] Decision made on a path forward
- [ ] Solution implemented to give developers the ability to troubleshoot application behavior via the rails console in at least the lower environments

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Possible candidate for #43549

**Comment by jhouse-solvd** [comment]
Please see this epic for follow-up on this work: 

https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/43549

Closing this issue.
