### ISSUE TITLE
 Design | Profile | BAI | Recruiting

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42925]
## Background

This outlines the tasks for the recruiting effort for BAI.

## Tasks
- [ ] Add ticket to research repo
- [ ] Share research plan and conversation guide with Shane and Clayton for approval and recruiting
- [ ] Make any revisions needed to research plan and conversation guide

## Acceptance Criteria
- [ ] Ticket has been added to repo
- [ ] Research plan and conversation guide has been shared with Shane and Clayton for approval and recruiting
- [ ] Any revisions needed have been made to research plan and conversation guide

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@cgednalske - I've updated the ticket; can you point when you have a chance?
