### ISSUE TITLE
[Design] Travel Pay: Create Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42936]
## User Story
As a Veteran, I would like to be able to submit a BT reimbursement claim so that I can get reimbursed.

## Tasks
- [ ] Create final wireframes and callouts for the Beneficiary Travel MVP
  - [ ] Add OMB, Expiration Date and Estimated Burden to the design. ([Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1660138758818239))
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Abstract Collection
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## UX/UI Deliverable
- [x] [Wireframes in Ccollection](https://share.goabstract.com/cd14def3-a950-48df-94b0-904c52ca4850)
- [x] [Clickthrough link](https://share.goabstract.com/cd14def3-a950-48df-94b0-904c52ca4850?collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&mode=design&present=true)

**Comment by benbrasso-agile6** [comment]
@loripusey per [this slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1660138758818239), we are not adding OMB, Expiration Date, etc. Do we still need to do this? Or should it be removed from tasks and AC?

**Comment by benbrasso-agile6** [comment]
@zach-park the wireframes should reflect what I've represented in [Prototype D](https://app.mural.co/t/vfscie8528/m/vfscie8528/1658844568873/93ba988aed6312d43533b8feaed365529b836332?sender=u83bc52d7fa73658f84f27755). Meet with you in a couple hours to discuss.

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 UX reviewed and incorporated the feedback. Collection link attached in the AC.

**Comment by benbrasso-agile6** [comment]
@loripusey I would say we can close this ticket
