### ISSUE TITLE
[Design] Create Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42941]
## User Story
As a Veteran, when I do Pre-Check-in, I would like to be able to see all of my upcoming appointments so that will understand what appointments I have.

## Description
A wireframes set will be delivered with the technical specifications needed for engineering to implement said feature.

## Tasks
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
