### ISSUE TITLE
Update education benefit pages and R&S articles with links to new rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42946]
## Issue Description
We audited our education benefit pages and education R&S articles to flag references to rates or links to legacy rates pages. Now that our VA.gov education rates pages are live, we need to implement these changes. 

The audit was completed in Ticket #42900.

## Tasks
- [ ] Update links and make content changes determined in audit ticket
- [ ] Copyedit with pre-publishing checklist (Megan)
- [ ] Publish pages (Megan)

## Acceptance Criteria
- [ ] Live pages now have links and references to our modernized education rates pages

**Comment by RLHecht** [comment]
Closing this ticket as I made a new one not realize we already had one and put more info into that one!
