### ISSUE TITLE
[BE] Determine the Type of Appointment and Make it Available to the Frontend

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42948]
## NOTE
We will use stop codes to determine if an appointment is a phone or in-person appointment

## Tasks
- [ ] [BE] Determine the Type of Appointment and Make it Available to the Frontend

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
