### ISSUE TITLE
CST: Decision Letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#42954]
## Value Statement
**_As a_** veteran
**_I want to_** be able to download my decision letter
**_So that_** I don't have to wait for it to arrive in the mail (or if I lose it) to use it to apply for other benefits or provide it to my representative so we can take follow up actions to pursue a disagreement pathway. 

---
## Background Context
- We've reviewed research suggesting this is a popular feature request from veterans
- There were some legal ambiguities around providing this in the past, but there is now a willingness to pursue this solution approach. 

[Feature Brief](https://docs.google.com/document/d/1RMy84KMu7mzaQznhD5vn4Q18oVlWsBYwP3hixqF3INY/edit#heading=h.p4oi2c4bhjpq)

@michelpmcdonald did some technical discovery into this some time ago. His results are explained in this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/29082#issuecomment-1015560303

## Acceptance Criteria
- [ ] _A veteran can successfully download their decision letter as soon as it's available_
- [ ] _There is a means of making salient to the veteran that a decision letter is now available to download_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Would this need to go through the collaboration cycle assuming minimal design changes.

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
#29082 related

**Comment by jacobworrell** [comment]
@michelpmcdonald Thanks. I mentioned this idea to Matt and it seems like there are more political and legal blockers to doing this than actual tech-blockers, but seems like those blockers may come down soon.

**Comment by samcoforma** [comment]
@jacobworrell just following up on the idea of us reaching out to Michel Palmer on this to get an idea of updating those filenames so they include claim ids. Should this be an action item for the next sprint?
