### ISSUE TITLE
[FE] My VA: Update Cerner Copy

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#42953]
## Background
Currently the copy for Cerner users reads "For VA Spokane health care or VA Walla Walla health care or VA Central Ohio health care or Roseburg (Oregon) VA health care or White City health care..." however we would like to change it to "For VA Spokane health care, VA Walla Walla health care, VA Central Ohio health care, Roseburg (Oregon) VA health care, or White City health care..." We believe this is a better design for our users.

## Tasks
- [x] Update copy to replace "or" with ","-  "VA Spokane health care, VA Walla Walla health care, VA Central Ohio health care, Roseburg (Oregon) VA health care, or White City health care..."
- [x] Validation by team (Angela, PM)
- [ ] Push to Production

## Acceptance Criteria
- [ ] New copy for Cerner users has commas instead of "or"

**Comment by aagosto90** [comment]
Validated by me @tmitchellgcio @ajakabcin @ericasauv09 ! I also updated the Sketch doc to have not bolded commas so these match perfectly now.
