### ISSUE TITLE
Confirm and implement IA and urls for new education rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42952]
## Issue Description

When getting our new education rates pages ready to publish, we need Mikki to confirm the urls, breadcrumbs and their placement in the left nav.

Once she has confirmed these, we should use this ticket to make sure these are set up on the new pages.

**NOTE: What's listed here in the issue description isn't up to date. Use the H1s, urls, and left nav labels in Mikki's comment below.**

**H1:** Current VA education rates
**url:** https://www.va.gov/education/benefit-rates/
**Left nav label:** Benefit rates

**H1:** Post-9/11 GI Bill (Chapter 33) rates
**url:** /education/benefit-rates/post-9-11-rates/
**Left nav label:** Post-9/11 GI Bill rates

**H1:** Montgomery GI Bill - Active Duty (Chapter 30) rates
**Url:** https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/
**Left nav label:** MGIB-AD rates

**H1:** Montgomery GI Bill - Selected Reserve (Chapter 1606) rates
**Url:** https://www.va.gov/education/benefit-rates/montgomery-reserve-rates
**Left nav label:** MGIB-SR rates

**H1:** Montgomery GI Bill $600 buy-up program rates
**Url:** https://www.va.gov/education/benefit-rates/600-buy-up-rates
**Left nav label:** $600 buy-up program

**H1:** Survivors' and Dependents' Educational Assistance (Chapter 35) rates
**Url:** https://www.va.gov/education/benefit-rates/dea-rates
**Left nav label:** Survivor and dependents rates

**H1:** Fry Scholarship rates
**Url:** https://www.va.gov/education/benefit-rates/fry-scholarship-rates
**Left nav label:** Fry Scholarship rates

**H1:** Post-9/11 GI Bill monthly housing allowance
**Url:** https://www.va.gov/education/benefit-rates/monthly-housing-allowance-rates
**Left nav label:** Monthly housing allowance rates

**H1:** Post-9/11 GI Bill Resident Rate Requirements 
**Url:** https://www.va.gov/education/benefit-rates/resident-rate-requirements/
**Left nav label:** Resident rate requirements

**H1:** Apply to restore your GI Bill benefits
**Url:** https://www.va.gov/education/benefits-restoration
**Left nav label:** Apply to restore GI Bill benefits
**Note from old ticket:** This page is the last page within the "Manage Benefits" spoke.

**H1:** Compare VA education benefits
**Url:** https://www.va.gov/education/compare-education-benefits/
**Left nav label:** Compare education benefits
**Note from old ticket:** This page will be the last page within the "More Resources" spoke (it will replace the current redirect to the legacy page).

**Note:** We can't set menu items (left nav content) until we are ready to publish a page.

## Tasks
- [x] Confirm urls and left nav content (Mikki)
- [ ] Update pages if needed 

## Acceptance Criteria
- [x] All education rates pages have correct urls and left nav content

**Comment by RLHecht** [comment]
@mnorthuis Can you also let us know the order these rates pages should be in? They'll all be listed on the main "Current VA education rates" page and I want to make sure we have them in the right order.

**Comment by mnorthuis** [comment]
Here is my feedback, please let me know if you have any questions or want to discuss. I posted the original info from above, and put edited versions below.  Sorry for the use of the strikeout, it feels so harsh!  
- I updated a few URLs for some keywords, revisions are below
- I updated a few left nav labels to more closely match the H1, revisions are below...some of them are longer, but we should aim for as close to the H1 as possible since the left nav acts as a menu for assistance tech users.  
- Question: we don't use dashes in the title of the MGIB programs on the benefit pages, so I left them out here, if that is changing all-around, please revise as needed.
- Question:  Could the housing allowance rates could be combined in with the Post 9/11 rates rather than a separate page?  If we keep it, I moved it up the list to keep it with Post 9/11 rates.  
- These 2 pages should move to R&S since they are supplemental content and not benefits that a Veteran has to apply for. Actual URLs will then match the H1 of the page.
  - Resident rate requirements
  - Compare education benefits
- If the restore benefits page is a manage task, the URL should be framed up with an action word similar to the H1. Revision to that is in the updates below

H1: Current VA education _[benefit]_ rates  _(Can we add "benefit" to this H1?)_
url: /education/benefit-rates/
~Left nav label: Benefit rates~
Revised left nav label: Education benefit rates

H1: Post-9/11 GI Bill (Chapter 33) rates
url: /education/benefit-rates/post-9-11-rates/
Left nav label: Post-9/11 GI Bill rates

H1: Post-9/11 GI Bill monthly housing allowance
~Url: /education/benefit-rates/monthly-housing-allowance-rates~
Revised URL: /education/benefit-rates/post-9-11-monthly-housing-allowance
~Left nav label: Monthly housing allowance rates~
Revised left nav label: Post-9/11 GI Bill monthly housing allowance

H1: Montgomery GI Bill - Active Duty (Chapter 30) rates _(Remove dash?)_
Url: /education/benefit-rates/montgomery-active-duty-rates/
~Left nav label: MGIB-AD rates~  
Revised left nav label: Montgomery GI Bill Active Duty rates

H1: Montgomery GI Bill - Selected Reserve (Chapter 1606) rates _(Remove dash?)_
~Url: /education/benefit-rates/montgomery-reserve-rates~  
Revised URL: /education/benefit-rates/montgomery-selected-reserve-rates
~Left nav label: MGIB-SR rates~ 
Revised left nav label: Montgomery GI Bill Selected Reserve rates

H1: Montgomery GI Bill $600 buy-up program rates
~Url:  /education/benefit-rates/600-buy-up-rates~
Revised URL: /education/benefit-rates/montgomery-600-buy-up-rates
~Left nav label: $600 buy-up program~
Revised left nav label: Montgomery GI Bill $600 buy-up program rates

H1: Survivors' and Dependents' Educational Assistance (Chapter 35) rates
Url: /education/benefit-rates/dea-rates
~Left nav label: Survivor and dependents rates~
Revised left nav label: Survivors' and Dependents' Education Assistance rates

H1: Apply to restore your GI Bill benefits
~Url: /education/benefits-restoration~
Revised URL: /education/apply-to-restore-gi-bill-benefits
Left nav label: Apply to restore GI Bill benefits
Note from old ticket: This page is the last page within the "Manage Benefits" spoke.


Suggested order for the left nav for the benefits rates pages:
Education benefits rates
- Post-9/11 GI Bill rates
- Post-9/11 GI Bill Monthly housing allowance
- Montgomery GI Bill Active Duty rates  
- Montgomery GI Bill Selected Reserve rates
- Montgomery GI Bill $600 buy-up program rates
- Survivors' and Dependents' Education Assistance rates

**Comment by RLHecht** [comment]
Thanks, @mnorthuis 

Yes, we should remove the dashes for the MGIB pages (they aren't currently in the Drupal node but they were still in the older versions I copied over from the old tickets. 

@bethpottsVADEPO Please see Mikki's other question about combining the housing allowance rates with the Post-9/11 page.

Also want to confirm about moving those 2 pages to R&S. If so, @katherine-fung can open new Drupal nodes with the R&S template when she begins her edits on those pages.

**Comment by mnorthuis** [comment]
@RLHecht - @bethpottsVADEPO and I talked about the housing allowance rates, and that will stay as a separate as it is laid out above. 

We also agreed that the housing requirements and compare page would go to R&S, although I think you are doing that work separately. 

Let me know if there's anything missing!

**Comment by mnorthuis** [comment]
@RLHecht @bethpottsVADEPO Do we need a ticket to redirect the legacy rates pages, or are we leaving the legacy rates pages alone?

**Comment by RLHecht** [comment]
@mnorthuis Could you add the url and IA placement info here for the new Fry rates page now that we're taking it out of the Post-9/11 page? Thanks!

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I'm going to update this ticket with slightly adjusted H1s for a couple of the pages since I realized this ticket isn't up to date. There are a lot of tickets out there having to do with rates. I think this one makes the most sense as far as where you'll put your IA recommendations that we talked through the other day for past and future rates.

**Comment by mnorthuis** [comment]
I updated the URLs and left nav labels [in my comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42952#issuecomment-1156924652), as well as the left nav order. 
- Beth solidifed the H1s above
- The URLs use whatever name the H1 leads with - for most that is the common name (i.e. Post-9/11 GI Bill), but for DEA it's the chapter number. 
- The left nav labels for the current rates pages should match what the H1 is...they may be a bit long, but that gets the full accurate name of the rates in the left nav.
- The order of the left nav has the Veteran programs first, followed by the dependent programs

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I updated your comment above as well to start the convo about **past rates** H1s/urls.

**Comment by RLHecht** [comment]
@mnorthuis I'm setting up the redirect ticket and have a question about the Post-9/11 and Fry rates pages. Would [the legacy page](https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080122.asp) that lists both types of rates redirect to our Post-9/11 page and nothing will redirect to the new Fry page?

**Comment by mnorthuis** [comment]
@RLHecht Yes, that is the best we can do for the redirect.  You could consider a sentence on the Post-9/11 page that tells visitors about the separate Fry page, but ultimately the rates are exactly the same.  Our new Fry page will just ensure that visitors know where to go if that is what they are looking for.

**Comment by RLHecht** [comment]
@megzehn When we are ready to set up the urls [this comment](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/42952#issuecomment-1156924652) is where we have all the correct H1s and urls as well as the correct left nav order.

**Comment by bethpottsVADEPO** [comment]
@megzehn I clicked on Randi's link in the above comment and it didn't jump to Mikki's comment, so I'm [trying again here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42952#issuecomment-1156924652) to take you to where the updated IA info is.

**Comment by RLHecht** [comment]
These pages are published so urls and IA work is complete. Closing!
