### ISSUE TITLE
Design | Profile | BAI | Usability testing sessions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42965]
## Background

Conduct Bad Address Indicator UAT with Veterans

## Tasks
- [x] Download final participant list from Perigean
- [x] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [x] Conduct scheduled research sessions
- [x] Debrief research sessions w/team
- [x] Download recordings
- [x] Download notes from Perigean

## Acceptance Criteria

- [x] Complete research sessions with Veterans
- [x] Complete all tasks

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@cgednalske - this ticket will be for Sprint 77; please point when you have a chance. LMK if you have any edits/additions.
