### ISSUE TITLE
[DataDog Migration] Document onboarding instructions

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42960]
## Description
As part of the migration of DataDog to GovCloud, users need instructions on how to get access to the new instance. 

## Background/context 
- Max.gov Jira request form https://vajira.max.gov/servicedesk/customer/portal/1/create/18

---
## Tasks
- [x] Create documentation in Confluence that provides instructions for onboarding 

## Acceptance Criteria 
- [x] Documentation exists in Confluence with... 
   - [x] Overview of process 
   - [x] Link to Max.gov Jira request form
   - [x] Explanation of Okta->DataDog access

**Comment by jhouse-solvd** [comment]
**Documentation** [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance)

_However, I'm not yet confident that sending users to Max.Gov is the best approach._ Several users, myself included, encounter an error when trying to log in to Max.Gov Jira to request access to DataDog.

I've sent an email to see if there's any help that the DOTS team can provide, or if each user needs to contact Max.Gov for support directly. 

Alternatively, if there is another method for submitting a request (ie, via email), we will update the documentation to reflect that.

**Comment by jhouse-solvd** [comment]
Moving this to review. 

I plan to discuss this w/ the Platform Infrastructure team on 6/16. Once finalized, I'd like to share the instructions with Platform (and VFS?) users as soon as possible.

**Comment by jhouse-solvd** [comment]
@mchelen-gov @little-oddball 

We want to share info w/ Platform Crew teams so that they can get access to DataDog GovCloud. We’ve hesitated to share b/c we want it to happen smoothly, but we also want them to get access as soon as possible. 

_w/out too much backstory:_ 

- **DOTS manages access to Okta+DataDog**
- DOTS provided a [link to Max.Gov Jira that allows users to request access](https://vajira.max.gov/servicedesk/customer/portal/1/create/18)
- We wrote up [instructions in Confluence](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance), but...
- Several team members (myself included) encounter an **error when using the link provided by DOTS**
- In order not to delay the process further, Jared from DOTS said... 
  - `"Please have them email me directly and I'll make sure they're able to get in!"`

Do you have any objection to asking Platform Crew users to email Jared directly? This might not be the process for gaining access to DataDog in the future, but it might be the best available approach at this point in time. 

cc: @ph-One

**Comment by mchelen-gov** [comment]
> * Several team members (myself included) encounter an **error when using the link provided by DOTS**

@jhouse-solvd What is the error with accessing Jira, are you able to login to max.gov?

**Comment by jhouse-solvd** [comment]
We will finalize onboarding instructions today 6/17, and John will share them in #platform-infrastructure and x-post to #platform-team 

[(link to Slack thread)](https://dsva.slack.com/archives/CJYRZK2HH/p1655494972231319)

**Comment by jhouse-solvd** [comment]
We will finalize onboarding instructions today 6/17, and John will share them in #platform-infrastructure and x-post to #platform-team 

[(link to Slack thread)](https://dsva.slack.com/archives/CJYRZK2HH/p1655494972231319)

**Comment by jhouse-solvd** [comment]
Documentation has been updated [HERE](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance)

Closing this issue.
