### ISSUE TITLE
[DataDog] Document guidance for migrating resources to a new organization (GovCloud instance)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42961]
## Description
As part of the migration of DataDog to GovCloud, users need guidance on how to migrate resources to the new instance. 

## Background/context 
_See_ #42691 

---
## Tasks
- [x] Create documentation in Confluence that provides guidance to Platform (and VFS) teams  

## Acceptance Criteria 
- [x] Documentation exists in Confluence with... 
   - [x] Overview of migration process  
   - [x] Technical details that explain using datadog-sync-cli
   - [x] Explanation of migrating specific resource types

**Comment by jhouse-solvd** [comment]
We've started a couple of documents that are currently a work in progress: 
- [Migrate DataDog resources to a new organization](https://vfs.atlassian.net/wiki/spaces/OT/pages/2235859230/Migrate+DataDog+resources+to+new+instance)
- [Migrate DataDog to DDog-Gov](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236416007/Migrate+Datadog+to+DDog-Gov)

Let's see how we can merge or link these together?

**Comment by jhouse-solvd** [comment]
We're planning to have this documentaiton finalized by Tuesday 6/21

@jsgarmon is going post in https://dsva.slack.com/archives/CJYRZK2HH/p1655494972231319 letting folks know that we will provide migration instructions on Tuesday, 6/21

**Comment by oseasmoran73** [comment]
Documentation is live and has been shared with teams. Includes the following:

- Document on how to get started
- Where to obtains keys
- Migrate dashboard, synthetic_global_variables, synthetic_tests

Feedback is going on this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43094)

Closing ticket as AC has been met. Please feel free to reopen as needed
