### ISSUE TITLE
PM | Profile | Military Migration | Track Successful and Failed Retrievals 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42968]
## Background

As we migrate from eMIS to VA Profile for military info (service history) we want to be able to monitor the performance of this new endpoint and be able to identify and address any issues early.

## Tasks
- [x] Create a widget in Google Analytics that captures the successful and failed retrievals for military service history 
- [x] Work with BE on best way to test in production prior to launch (if possible)

## Acceptance Criteria
- [ ] Confirm traffic is being captured and displayed

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Use: /v0/profile/service_history or /profile/service_history
