### ISSUE TITLE
[Design] MyHealth - Design message landing page for auth users without health care

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#42977]
## Issue Description
As a secure messaging user, I need a mobile and desktop message landing page for authorized users who do not have health care benefits

---
## Tasks
- [ ] Design auth without healthcare message landing page for desktop
- [ ] Design auth without healthcare message landing page for mobile
- [ ] Drop link to mockups into a comment on this ticket
- [ ] Drop a note into #mhv_on_vagov in Slack when you are ready for Tracey to review

## Acceptance Criteria
- [ ] Mobile and desktop initial designs will be complete and ready for review by design lead and product owner.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
