### ISSUE TITLE
Discovery: DLC Customer Service Representative Interviews

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#4297]
## User Story or Problem Statement
As a UX Designer, I need conduct interviews with DLC Customer Service Representatives with knowledge of prosthetic socks customers so I can understand the sock portion of MDT's userbase.

## Tasks
- [x] Schedule Sessions with DLC / Jeff (1 hour)
- [x] Conduct interviews (2 hours)
- [x] Transcribe & upload notes to GH (1 hour)

## Acceptance Criteria
- [ ] Interviews completed
- [ ] Notes in GH

## Next Steps
- Synthesis

## Blockers
- DLC scheduling issues

**Comment by rebeccawalsh** [comment]
Here are the transcripts and takeaways from the two DLC customer service interviews we had this week:

- [Interview 1 - 12/18](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/meetings/20191218-DALC-customer-service-representative.md)
- [Interview 2 - 12/19](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/meetings/20191219-DALC-customer-service-representative.md)
