### ISSUE TITLE
Discovery: Rudimentary Personas

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#4298]
## User Story or Problem Statement
As a UX Designer, I need to create rudimentary personas so I can share these artifacts with my team prior to the feature scoping activity.

## Tasks
- [x] Meet with designers to discuss synthesized findings and determine intended persona archetypes (2 hours)
- [x] Create rudimentary persona documents (1 hour)

## Acceptance Criteria
- [x] Rough outline of personas uploaded to GH

## Next Steps
- Create higher fidelity personas

## Blockers
- N/A

**Comment by rileyorr** [comment]
@wygonikGCIO & @rebeccawalsh: The first draft personas can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/discovery-nov19/personas.md). This document also contains user scenarios associated with each persona.
