### ISSUE TITLE
[FRONTEND] Content Adjustment for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4300]
## Story
As an end user of the Rated Disabilities Tool page, I want to have concise, clear and consistent language so that I can better understand what the tool page's information is trying to convey.

## Considerations
These are comments from Peggy that will make the content consistent with the latest style changes.

## Tasks
Referring to the latest Rated Disabilities page [mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL) and [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] Add a short intro to help users understand what they are reading (combined ratings vs. individual ratings), and update the titles to read:
H1: **Your VA disability ratings**
H2: **Your combined disability rating**
*Note that H1 is plural, and H2 is not*
Add new intro  copy: **"This is your rating for multiple conditions."**
- [x] Update box copy (as we've heard in recent research that some people don't understand what "pending" means) to: **"This rating doesn’t include any disabilities for your claims that are still in process."**
- [x] Rewrite H2 head to say Individual ratings to tie in more closely with the H1. So this header would become: 
H2: **Your individual ratings** 
New intro copy: **"This is your rating for a single condition."**
- [x] In the right rail, update the last sentence under the header "How did I get this rating?" to: 
**"…and information from other sources, like federal agencies."** 
- [x] In the right rail, under the header "Learn about VA disability ratings," rewrite to make more active voice: 
**"To learn how we determined your combined VA disability rating, use our disability rating calculator and ratings table."**
- [x] The link "About VA Disability ratings" should be sentence-cased: **"About VA disability ratings"**  

Referring to the latest Rated Disabilities 400 error handling [mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/4255c799-245e-4df0-90bb-7cec66dfc218/RD-Screen-Tool-3) and [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] For the blue error message, just remove "We're sorry." from the beginning of the first sentence for the error message in the TCDR location. 
Title: **We don't have a disability rating on file for you**
Message body copy would start: **"We can't find a disability rating for you..."**   

Referring to the latest Rated Disabilities 500 error handling [mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/5973de59-34ae-46ce-8aca-e41d8f73f3d6/RD-Screen-Tool-4) and [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- For the red error message, please add **“the”** before VA.gov help desk in the body of the message
The sentence should read: **"...please call the VA.gov help desk..."**  

Referring to the latest Rated Disabilities 400 error handling [mockup](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/f934fd6e-0eaa-4bb5-b098-a5e65a0cf19a/RD-Screen-Tool-6) and [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- For the blue error message, just remove "We're sorry." from the beginning of the first sentence for the error message in the individual ratings location. 
Message body copy would simply start: **"We can't find a disability rating for you..."** 

- [x] Update e2e tests 

## Acceptance Criteria
- [ ] A PR for these changes has been submitted.

**Comment by sporeboy** [comment]
Rated Disabilities Content Edits from 12/20 (per Peggy Gannon)

Your combined disability rating and Your individual ratings section will not have intro copy below their headers.

Right Sidebar, top paragraph: add comma after “sources” so the line reads:
“…and information from the sources, like federal agencies.”

Right Sidebar, middle paragraph: move “VA” to before “combined” so the line reads:
“…how we determined your VA combined disability rating.”

Combined rating 400 alert: make header read:
“We don't have a combined disability rating on file for you"
And make the first sentence in the paragraph read:
"We can't find a combined disability rating for you."

**Comment by cohnjesse** [comment]
@sporeboy Just made these updates and pushed to the branch, let me know if it looks like it's good to go and I can merge to master.
