### ISSUE TITLE
[Contact Center team] Clear backlog of support tickets for VA Benefits Team 1

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#43002]
## Value Statement
**_As a_** member of the support team
**_I want to_** respond to all open support tickets that Veterans are experiencing
**_So that_** clear the backlog of support tickets for benefits team 1

---
## Background Context
The contact center team has over 546 open tickets related to benefits. We need to clear this backlog by updating all tickets. 

## Tasks
- [ ] _Instruct Kimberley to close tickets that are inactive (no response since 5/1/2022)._
- [ ] _Review and respond to all Zenhub issues that @saderagsdale is tagged in._
- [ ] _Update the instructions for the contact center and send to Kimberley_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
