### ISSUE TITLE
[DESIGN] Content Adjustment for Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4301]
## Story
As an end user of the Rated Disabilities Tool page, I want to have concise, clear and consistent language so that I can better understand what the tool page's information is trying to convey.

## Considerations
These are comments from Peggy that will make the content consistent with the latest style changes.

## Tasks
Referring to [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] Add a short intro to help users understand what they are reading (combined ratings vs. individual ratings), and update the titles to read:
H1: **Your VA disability ratings**
H2: **Your combined disability rating**
*Note that H1 is plural, and H2 is not*
~~Add new intro  copy: **"This is your rating for multiple conditions."**~~
- [x] Update box copy (as we've heard in recent research that some people don't understand what "pending" means) to: **"This rating doesn’t include any disabilities for your claims that are still in process."**
- [x] Rewrite H2 head to say Individual ratings to tie in more closely with the H1. So this header would become: 
H2: **Your individual ratings** 
~~New intro copy: **"This is your rating for a single condition."**~~
- [x] In the right rail, update the last sentence under the header "How did I get this rating?" to: 
**"…and information from other sources, like federal agencies."** 
- [x] In the right rail, under the header "Learn about VA disability ratings," rewrite to make more active voice: 
**"To learn how we determined your combined VA disability rating, use our disability rating calculator and ratings table."**
- [x] The link "About VA Disability ratings" should be sentence-cased: **"About VA disability ratings"**  

Referring to [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] For the blue error message, just remove "We're sorry." from the beginning of the first sentence for the error message in the TCDR location. 
Title: **We don't have a disability rating on file for you**
Message body copy would start: **"We can't find a disability rating for you..."**   

Referring to [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] For the red error message, please add **“the”** before VA.gov help desk in the body of the message
The sentence should read: **"...please call the VA.gov help desk..."**  

Referring to [Peggy's comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4104):
- [x] For the blue error message, just remove "We're sorry." from the beginning of the first sentence for the error message in the individual ratings location. 
Message body copy would simply start: **"We can't find a disability rating for you..."**   

## Acceptance Criteria
- [x] The Rated Disabilities mockup reflects these changes.

**Comment by sporeboy** [comment]
Content revised per feedback from Peggy. Revisions here: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/90b2e033-e56a-4634-91ff-b694b46d2097/RD-Screen-Tool-FINAL

**Comment by jason-gcio** [comment]
Looks good @sporeboy, nice job.
