### ISSUE TITLE
FE | Profile | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43018]
## Background

Describe the issue background and scope

## Tasks
- [ ] Compile a list of the data we ingest within  Profile
- [ ] Research which system provides this data

## Acceptance Criteria
- [ ] Create an overview including technical diagram based on findings
- [ ] Review during a live stand-up
- [ ] Post to Github technical folder

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @mdewey - I started a ticket for documentation; please add/edit as needed.

Also, is this something you want to have included in current sprint 76 or next one?
