### ISSUE TITLE
Staging Review [Modernized Check-in Team - Patient Check-in (Pre-Check-in and Mobile Check-in)]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43016]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
      - Scheduled for June 28 at 11:30 am ET
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
    - [x] [Instructions for Creating Appointments and Testing in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md)
- [x]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [x] Update Staging Review ticket with the product’s launch date after it has gone live.
- [x] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
    - [Instructions for Testing in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md)

- [x] Product outline 
     - [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product#readme)
     - [Product Guides](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product/product-guides)
  

- [x] Release plan with the "Planning" sections completed 
    - [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/Check-in%20Release%20Plan.md)
 

### Content artifacts 

- [x] Your product’s content source of truth
    - [English](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/check-in/locales/en/translation.json)
    - [Spanish](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/check-in/locales/es/translation.json) 
- [X] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
   - NA
### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [X] Product test cases/test plan in TestRail with test execution logs 
    - [Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/qa/test-cases.md)
- [X] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
   - NA
- [X] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 
  - NA

### Accessibility artifacts 

- [x] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 
  - NA
- [x] List of known issues
 - [Known Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/known-issues.md)

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
@loripusey in order to do a Staging Review, we need the following things:
1. Update this ticket with the requested artifacts. If you don't have all, that's fine. Please provide what you have. We need to have access to the Patient Check-in tool in order to validate it meets our Platform standards.
2. Schedule a Staging Review. Follow the instructions under the Scheduling heading.

Feel free to reach out to me if you have questions. Thanks!

**Comment by loripusey** [comment]
- @acrollet @benbrasso-agile6 @brianseek We are scheduled to do a Staging Review on Tuesday, June 28 for the Platform Collaboration Cycle team. Please take a look at the Artifacts section of this ticket as we will need to get these items (if available) and add links to this ticket for these items. 
- I will take care of the staging url (with instructions for the Staging Tool), Product Outline, and Release Plan 
- Can the three of you start rounding up the other artifacts?
Thanks

**Comment by shiragoodman** [comment]
Confirming that this Staging Review is scheduled for 6/28 at 11:30am ET

**Comment by CherylEvans** [comment]
@loripusey Hi Lori, I was communicating with SWC regarding the upcoming Staging Review, and they recommended I request from your team, links to any SWC intake requests for my reference. They indicated that there have been different intake requests for different pieces of this product, so perhaps your team can determine which may be most relevant to this review, and provide them for me to assist in my review.  I am on vacation next week, so am trying to complete my review by EOD tomorrow.  I appreciate your input and assistance.  Thank you!!

**Comment by loripusey** [comment]
Each test patient is linked to someone's personal mobile phone. How many people need to access the applications in staging? Someone can use my test patient (Thirty), let me know how many others you need and I'll borrow some.

**Comment by shiragoodman** [comment]
hey @loripusey  - we have 7 folks on our team who will be testing this. I will tag them here:

1. @briandeconinck  - Accessibility
2. @seanasewell  - Design
3. @allison0034  - Design
4. @CherylEvans  - Content
5. @jimuhh  - Information Architecture
6. @claytonzook  - Research
7. @ddzz - Quality Insurance

Than you for helping to coordinate! If 7 are not available, our designers and content folks can do their review using screen shots (which our other team members can supply). Please let me know.

**Comment by allison0034** [comment]
Hi @loripusey, I apologize if this was made clear in the product outline, but I have a couple questions.

1. Can Veterans currently access check in on a mobile device?
2. Have there been any design changes since it last came through the [collab cycle 8/21](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28859#issuecomment-911034270)?

My assumptions is you are just removing the kiosks, but I want to be sure. Thank you!

**Comment by loripusey** [comment]
1. Yes, Veterans use the Patient Check-in features on their mobile device.  
2. There may have been some minor tweaks to the design but I believe it is largely the same
@allison0034

**Comment by loripusey** [comment]
Assigned test patients to specific user roles (see above); follow these [instructions ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md)for testing on a computer; note that none of these test patients are tied to anyone's mobile phone number

**Comment by allison0034** [comment]
No design feedback, thank you!
