### ISSUE TITLE
Refine research expectations re: where to store research documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43020]
## User Story
As an individual supporting VA.gov, I want to be sure that all VFS teams follow the same guidance for storing research artifacts and documentation so that I know where to find specific research, regardless of which team did the research or what product it is for.

As a VFS team researcher, I want to know where I should store all artifacts and documentation related to my teams research initiative so that I can be sure I'm storing everything in the appropriate place.

Assignee: @CherylEvans 
Peer Reviewer: @claytonzook 

## Description
New VFS teams have been storing their research artifacts and documentation in different places. Because research can and should be used by any VFS team, it is important that all VFS teams store their research artifacts and documentation in GitHub under the appropriate product folder. This allows any VFS, OCTO and/or Platform team member to find any research that was previously performed.

How might we inform new VFS teams of the expectations for storing and saving research artifacts and documentation?

## Artifacts Impacted
[Design & Research Orientation Deck](https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.g5ce7a4246a_0_64)
[Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist)

## Tasks
- [x] Schedule meeting with Naomi to discuss ticket.
- [x] Research Checklist: Make a research folder bullet point:  This should change so the new folder created is product/research/[YYYY-MM-research-name] so that each research project for a product or feature has it's own folder. - Clayton (from research-ops meeting)
- [x] Potentially bullet point detailing levels and multiple research projects (topics) to avoid image formatting on Platform Website
  - Following naming convention of research repo
- [x] Research Checklist: Specifically the guidance on the research checklist Planning for Research section. The existing guidance should be updated to not include the creation of a readme file. Instead the guidance should be "since Github requires a document in a new folder, go ahead and create a document that will be your research plan (research-plan.md)." - Clayton (from research-ops meeting) 
  - Simplify language and use GitHub terminology
- [x] Design & Research Orientation Deck: Communicate research storage expectations in the Design & Research Orientation deck - Shira
  - Add [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) link.  Slide 14, Step 2
- [x] Research Checklist: Add clear instructions "you need to store your conversation guide and research plan in this repo"

- [x] Announcements
  - Research slack channel
  - Monday meeting

## New Tickets
- [x] Create a "GitHub How-to" page for those that are not familiar with creating/managing files and folders in Github.
Add a checklist item to the Platform Orientation template under the "Get set up for your practice area heading", subheading "General Practice Area" pointing them to the new Platform Website guidance.
Ticket [#46002](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/46002)
  
## Acceptance Criteria
- [x] VFS teams are informed in Platform Orientation: Research & Design Sessions that research needs to be saved in GitHub under the appropriate product folder.
- [x] VFS teams are able to reference guidance on Platform Website for how to store research guidance and documentation in GitHub under the appropriate product folder.

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by claytonzook** [comment]
Do we need to modify what already exists on the [Platform Research Checklist page](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-1.Planningforresearch)

"Create a research folder in your product's folder on GitHub (Add file > create new file > product/research/README.md). All project related research & elements should live in this folder..."

**Comment by naomimarcussen** [comment]
@claytonzook I think that line in the checklist is pretty clear. It might be helpful to 
- link to a "Github how-to" page (I don't think one currently exists) for those that are not familiar with creating/managing files and folders in Github. 

- link to a document explaining why we "design in the open" and examples of what those things are. We have this [guidance on sensitive documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md), but I believe @sshein you had a FAQ or something with a good explanation for designers and researchers?

**Comment by sshein** [comment]
hi! yeah that all makes sense. My [FAQ is more around slack and why we use slack in the open](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/onboarding/vsa-slack-guidance.md#Frequently-Asked-Questions) but that could be worked in somehow?

**Comment by claytonzook** [comment]
We had a discussion in the research ops meeting this afternoon that relates to this ticket. Some decisions that we'd like to move on (or add to tech-debt)

1. Specifically the guidance on the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) Planning for Research section. The existing guidance should be updated to not include the creation of a readme file. Instead the guidance should be "since Github requires a document in a new folder, go ahead and create a document that will be your research plan (research-plan.md)." 

2. That first checkbox/bullet point should change so the new folder created is product/research/[YYYY-MM-research-name] so that each research project for a product or feature has it's own folder.

@chaseakirby - should we we integrate either of these into this ticket and/or what would make more sense as a new ticket?

**Comment by chaseakirby** [comment]
@claytonzook - I think that these tasks make sense in this ticket. I think that those tasks are spot on to accomplish the second Acceptance Criteria listed in the ticket and we knew that we would have to update the tasks after meeting with Naomi and having discussions.
Do we think that the first AC of informing people in Platform Orientation is relevant still? It sounds like we may not need it if we are adding instructions to the checklist.

**Comment by shiragoodman** [comment]
@chaseakirby I do specify in the General Orientation session that research docs needs to be saved in the product folder on GitHub. IIRC, the goal was to ensure that the Design & Research Orientation reflects the same.

**Comment by chaseakirby** [comment]
@shiragoodman Ah thanks Shira! 
I updated that AC to note it is for the Research & Design Orientation Session.

**Comment by CherylEvans** [comment]
@claytonzook Since GH does require the document for folder creation, should "Make a research folder" and "Create a research plan" be individual bullets/tasks in the Research Checklist?

**Comment by CherylEvans** [comment]
@claytonzook @chaseakirby Hi Clayton.  I am working through this ticket with assistance from Chase, and this is what we have come up with for the [Research Checklist](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2305359873/Cheryl+Draft+-+Copy+of+Research+Checklist).  Not ready for an official Peer Review yet, simply want to get your thoughts before I proceed.  Thank you, Clayton! :-)

**Comment by claytonzook** [comment]
@CherylEvans I left some comments for consideration on the confluence doc

**Comment by CherylEvans** [comment]
@claytonzook Thank you for your input, Clayton.  I am reworking it now! :-)

**Comment by CherylEvans** [comment]
@claytonzook Hi Clayton.  I made the appropriate changes, but left a question on the [Research Checklist](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2305359873/Cheryl+Draft+-+Copy+of+Research+Checklist).  Thank you!

**Comment by claytonzook** [comment]
@CherylEvans Thanks for the work on this ticket! I think everything looks good other than publishing and announcing.

**Comment by CherylEvans** [comment]
@claytonzook Hey there.  Wanted to complete the ticket, but need to confer with Chase on the new tickets they need to be created first.  Once he and I talk about this tomorrow, and create the associated tickets, it will be ready for a final peer review.  Thank you for all of your guidance on this issue, Clayton.  As always, it is very much appreciated!!

**Comment by CherylEvans** [comment]
@claytonzook @chaseakirby [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) has been published. 
Announcement has been made in #design and #research-ops slack channels.
Github Research Location
Effective today, Platform Team has updated preferred location of team’s research folder(s) in Github
Impact: For any new research, your team should use updated guidance on where to store research
Updates have been made to Research Checklist
Questions:  Please post any questions in thread, and/or tag 
@Clayton Zook
 or 
@Cheryl Evans

**Comment by CherylEvans** [comment]
@chaseakirby Ticket [#46002](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/46002) created.
All tasks complete.  User story fulfilled.
