### ISSUE TITLE
[FE] [BUG] [SPIKE] login fields error state is sometimes set on initial load

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43038]
## User Story
As a Veteran, I do not wish to see fields highlighted in red when I first load the app, so that I do not think something has gone wrong.
 
## Background

We're noticing that the last name/last 4 fields often start off in the error state:

![Screen Shot 2022-06-16 at 1.01.19 PM.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/7ef4a257-cbd2-4284-b8d4-9dfd4174cac9)

## Tasks
- [ ] [FE] Investigate cause and either resolve (if low loe and due to how we use the DS component) or file a follow-on issue (in our queue or DS queue)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Closed as duplicate of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/956
