### ISSUE TITLE
[bug] Notice of Disagreement | Some user-supplied PDF files are rejected, page dimension exceeds 21x21

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#43037]
## Value Statement
**_As a_** Veteran
**_I want to_** upload properly formatted files before submitting a claim
**_So that_** all files I share are submitted and can be reviewed by the NOD board. 

---
## Background Context
Lighthouse has reported that some pages within pdf files that users attach to their NODs exceed the "physical printed" limit of 21" x 21" and the files are being rejected and they don't make it to the VA-NOD board. The user impact is that:
- The file they intended the VA to review does not make it to the VA.  
- No direct notification is provided to the vets
- The burden is currently on the vet to review the NOD once it shows up in the Claim Status tool, remember the files they attempted to submit, and look at the claim detail  file page and confirm that all their files are listed.
- Here's a Slack [thread](https://dsva.slack.com/archives/CSKKUL36K/p1655315131790789) with Lighthouse 

Impact: 30 NOD file uploads out of 743 total uploads hit this issue, vets are not automatically notified of the rejected file, the only current recourse they have is to look at the NOD in Claim Status Tool and notice that one or more of the evidence files they attempted to upload did not make it. Reattempts to upload the same file will also fail out.

## Acceptance Criteria
- [ ] Veterans are notified if files attached to NOD submissions are rejected due to file size.

## Designs and Build Notes
- Add here

## Open questions
- Add here

## Tasks
- [x] Decide if presenting the user a message and preventing the upload is the best choice
- [ ] Decide where(FE or BE) we attempt to detect the error
- [x] Come up with the words to present to the vets 

## Definition of Ready
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Possible solutions:
1. At the point the vet attempts to upload the file while they are in the middle of creating the NOD, error right then and there, inform the vet of the issue.  
The problem with that is words and actions. For the most part even if we can come up with an understandable message, it's hard coming up with something that the vets can do to correct the file themselves.  I'd say most vets are not going to know how to shrink the PDF page(s) sizes nor do they have any software that would allow them to do it.

2. The other option is for us to attempt to shrink the pages.  In the [thread](https://dsva.slack.com/archives/CSKKUL36K/p1655315131790789), Nichole Harris covered some past attempts to auto shrink the page(s) and why they did not pan out.  For the most part readability and legal compliance.

**Comment by thehastingsp** [comment]
This looks like it will be researched by the lighthouse team and may be able to be configured on the back end.

**Comment by saderagsdale** [comment]
@thehastingsp for this issue i think we decided to hold off and not take any action while LH investigates, correct?

**Comment by michelpmcdonald** [comment]
Still waiting on LH to research the possibility of automatically shrinking the pages that are too big.

**Comment by thehastingsp** [comment]
I've opened a [content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44006) on the error messaging for consideration within the larger upload context.

**Comment by michelpmcdonald** [comment]
Just a quick update, Lighthouse is actively working on a PDF validation endpoint service.  We pass LH a PDF, and they check it to make sure it's valid(size, no owner password, etc) and return and violations.  It's still in development, but they are making moves:
https://dsva.slack.com/archives/C5AGLBNRK/p1659637485424969

**Comment by saderagsdale** [comment]
@saderagsdale delete AC2

**Comment by michelpmcdonald** [comment]
I would consider **not** waiting for LH to complete their file validation endpoint.

Vets-api already has a few PDF client libraries that seem to offer ways to check the PDF's page dimensions.
It seems approachable to add a PDF dimension check in vets-api now(right where vets-api already checks for\unlocks password protected PDFs), and rip the page dim check out after LH completes their PDF validation endpoint.

@jerekshoe - (throwin you under the bus here), I think Jerek already had a quick look at the current PDF libs in vets-api and had some ideas on how to check the PDF dimensions using the current libs.

**Comment by thehastingsp** [comment]
content team has provided the following error message for this ticket. For context, I've also created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45470) to clarify upload guidance that we should make consistent across claims & appeals forms @saderagsdale 

"We're sorry. We couldn't upload your file. One or more pages in your PDF are too big."

**Comment by michelpmcdonald** [comment]
Just got out of a meeting with Lighthouse, very very tentatively, kelly estimates 2 more sprints until LH PDF file validation endpoint will be available for testing, so something like ~5 weeks, I just wanted to ~bracket that estimated timeframe.

**Comment by saderagsdale** [comment]
@michelpmcdonald thank youuuu

**Comment by saderagsdale** [comment]
@saderagsdale write a pt 2 ticket.

**Comment by kylesoskin** [comment]
On this point:
> Decide where(FE or BE) we attempt to detect the error

This should really be checked both places. 

Additionally, from the linked slack thread it sounds like the solution that was decided might have been to have lighthouse just send the file through downstream as-is and NOT check dimensions as the downstream service MAY already handle that. 

This will need more discovery.

**Comment by thehastingsp** [comment]
@kylesoskin do you see the error messaging we want to provide while we work out the technical solution? 
""We're sorry. We couldn't upload your file. One or more pages in your PDF are too big."

**Comment by kylesoskin** [comment]
@thehastingsp The error in the screenshot is in 

https://github.com/department-of-veterans-affairs/vets-website/blob/0d38b0e6edd941d0ae691d8ad77503adf6c251fd/src/platform/forms-system/src/js/utilities/file/checkTypeAndExtensionMatches.js

I do not see anything for the PDF too big message.

**Comment by thehastingsp** [comment]
Can we change the message @kylesoskin or are we constrained by what comes back to us?

**Comment by kylesoskin** [comment]
The one in the screenshot or the one that we will eventually show for a PDF that is too big? 

Either way the answer is "yes". That screenshot is from staging, and also for supplemental claims upload. It could be different for NODs uploads (it shouldnt be, but could be) but regardless it can be whatever, in either case.

Either would be a front-end change that @Mottie would probably deal with, or maybe @data-doge as a first issue to get into the code.

**Comment by michelpmcdonald** [comment]
Just kind of FYI, I think this PR is the start of the LH PDF file validation endpoint:
[PR 10523](https://github.com/department-of-veterans-affairs/vets-api/pull/10523)

**Comment by jerekshoe** [comment]
In the case of NOD, most error messaging for PDFs comes from vets-api currently. I can't speak to other applications
![Screen Shot 2022-09-06 at 2 35 32 PM](https://user-images.githubusercontent.com/13838621/188723361-f1367831-e072-42b7-a942-fb234b06f54b.png)

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_attachment.rb#L48

**Comment by Mottie** [comment]
@kylesoskin We don't really want to do this type of detection on the front-end. If we did decide to do that, we'd have to [import an almost 4MB PDF library](https://www.google.com/search?q=size+of+pdf.js) so we can get access to the page size of _every page_ within the document. Since the backend already includes a PDF library, and a method to return errors to the frontend, I think the backend should handle this.

**Comment by kylesoskin** [comment]
It looks like the easiest and quickest fix will be to implement a back-end check via the shared pdf check from @michelpmcdonald comment's PR.

**Comment by saderagsdale** [comment]
@kylesoskin Yes, confirming that Lighthouse is indeed working on an endpoint to check this on the backend. That should be completed in their next sprint. 

On the front end, we are responsible for error messaging that gives users guidance on what to do if their evidence does not upload, captured in #46330.

**Comment by kylesoskin** [comment]
@saderagsdale we may not need an exposed api endpoint. That would be nice, but the existing `PDFUtilities::PDFValidator` shared lib class will also work and is usable now/already merged and ready to be used from the looks of it. 

In that validator the checks are hard-coded, so we should confirm the reqs in it are the same as ours, but assuming they are that should be fine to use.

**Comment by Mottie** [comment]
The frontend does do the following file (not just PDFs) size checks before uploading:
- File size less than max allowed
- File extension and mime-type matches
- Password-protected PDFs get tested for encryption, and if positive, it will ask for a password before attempting upload

**Comment by saderagsdale** [comment]
@kylesoskin I'm going to move this to the product baclog while you're on leave. I think for this we're waiting on the endpoint that Lighthouse estimated would be done soon, correct?

**Comment by saderagsdale** [comment]
Closing this one. We can make a new one for working with Michael Taylor to get all limitations lifted.
