### ISSUE TITLE
Standardize Platform Github Teams structure

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#43048]
### Description

Currently the organization and hierarchy of Github Teams used by Platform and VFS teams is inconsistent and confusing. The structure and permissions of these teams should be standardized to increase ease of use, reduce confusion, and improve confidence of accurate permissions.

### Tasks
- [x] Create RFC for proposed GH team structure https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/27
- [x] Create [`va.gov-platform-teams`](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-platform-teams) nested under [`vets.gov-write`](https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-write)
- [x] #44529
- [x] #44979
- [ ] #44980
- [ ] Platform onboarding docs are updated so that new team members are added to their GH team

### Acceptance Criteria
> - [ ] TODO (ensure this gets over to the Epic): No individual users in [vets.gov-write](https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-write/members) team other than maintainers.

- [ ] Create new Epic to outlines the purpose and the remaining work to be completed for this item
- [ ] Ensure the RFC has been updated and all comments resolved, etc. to cover the proposed approach

### Subject Areas

- [x] Product
- [ ] Design
- [X] Engineering
- [ ] OCTO-DE

**Comment by jjulian** [comment]
A couple potential additions to your checklist:
- [ ] new team members are added to `va.gov-platform-teams` when they are added to the github org
- [ ] `va.gov-platform-teams` provides Write access to general-use repositories such as va.gov-team, and va.gov-platform-architecture

**Comment by mchelen-gov** [comment]
> * [ ]  new team members are added to `va.gov-platform-teams` when they are added to the github org

@jjulian  Yup, although they should be added to their specific team rather than overall `va.gov-platform-teams`

> * [ ]  `va.gov-platform-teams` provides Write access to general-use repositories such as va.gov-team, and va.gov-platform-architecture

Most necessary perms should be inherited from `vets.gov-write`, are there any other perms that should be added to all Platform teams?

**Comment by jjulian** [comment]
> Most necessary perms should be inherited from `vets.gov-write`, are there any other perms that should be added to all Platform teams?

I don't think so, most important is allowing new org members to immediately open issues and PRs on va.gov-team and va.gov-platform-architecture

**Comment by mchelen-gov** [comment]
> > Most necessary perms should be inherited from `vets.gov-write`, are there any other perms that should be added to all Platform teams?
> 
> I don't think so, most important is allowing new org members to immediately open issues and PRs on va.gov-team and va.gov-platform-architecture

Ok cool, yup `va.gov-team` write perms are inherited from `vets.gov-write` and `platform-architecture` allows write access from `all-va`.

**Comment by karlbrown-va** [comment]
Would it be worth renaming `vets.gov-write` or would that break too many things?

**Comment by andreahewitt-odd** [comment]
@mchelen Should we standardize maintainers on the teams?

**Comment by TPurple** [comment]
Tagging @kjduensing and @jhouse-solvd, as we just got out of a meeting where we discussed GitHub team hierarchies and permissions structures.

**Comment by mchelen-gov** [comment]
Draft RFC: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/27
