### ISSUE TITLE
[FE] Update staging appt tool lambda to make demographics calls directly to CW

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43046]
## Background

CHIP have updated their confirm-demographics endpoint to require a UUID, which we don't have when using the staging tool to reset demographics. We should be able to fix the error message by instead calling CW directly.
  
## Tasks
- [ ] [FE] Update staging appt tool lambda to make demographics calls directly to CW
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
