### ISSUE TITLE
Add "Using Assistive Technology in Zoom" Link to "How to use Zoom for User Research"

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#43044]
## User Story
As a researcher, I want clear and updated guidance for using Assistive Technology in Zoom on Platform, so I have a single source of truth.

- Intended Audience: VFS
- Desired Outcome: Add updated guidance to Platform
- Due Date: N/A

Assignee: @CherylEvans 
Peer Reviewer: @jimuhh 

## Description
In ticket #40879, the new page [Research with Assistive Technology Users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) was created and added to the Research and Design section of Platform Website. We want to make sure that researchers know this page exists, so we'd like to include a link to it in the [How to use Zoom for User Research](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-use-zoom-for-user-research) page. 

## New Artifacts 
N/A

## Artifacts Needing Updates
[How to Use Zoom for User Research](https://vfs.atlassian.net/wiki/spaces/RD/pages/1652392082/How+To+Use+Zoom+for+User+Research)  source page

## Tasks
- [x] In the "Things to know during a feedback session" section, add a 4th bullet that says:
>  If you are planning to do research with a participant using assistive technology, please review the [Research with Assistive Technology Users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) guidance to ensure you're prepared.

## Acceptance Criteria
- [x] Researchers who are planning to use Zoom for research studies are easily able to find guidance for working with assistive technology users.

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by CherylEvans** [comment]
@shiragoodman Hi Shira.  Can you provide me with some additional details for this ticket please.  I know I created it at your direction, but now am a bit confused with regard to what page is to be linked to what.  I think it is this page: Research with Assistive Technology Users, https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users 
(Source page:) https://vfs.atlassian.net/wiki/spaces/PPST/pages/2242871321/Draft+Brian+-+Research+with+Assistive+Technology+Users) that is to be linked to How to use Zoom for User Research, but not sure.  I am sorry but I can't remember the particulars, and don't want to link to something that is not correct.  So my question is, do I link the page I created to Brian's page, or vice versa? Apologies in advance!! Thanks, Shira!

**Comment by shiragoodman** [comment]
@CherylEvans  - I updated the ticket. Please review and let me know if that answers your questions.

**Comment by CherylEvans** [comment]
@jimuhh Good morning Jim!  I included the Introduction we discussed from your ticket, as well as the link I added, in accordance with ticket 43044:
My Draft: https://vfs.atlassian.net/wiki/spaces/PPST/pages/2282717192/Cheryl+Draft+-+Copy+of+How+To+Use+Zoom+for+User+Research
Will you please peer review and let me know if this works for you?  Thank you!

**Comment by jimuhh** [comment]
@CherylEvans Looks good! Thanks!

**Comment by CherylEvans** [comment]
@shiragoodman All AC met, and once changes are published, will close ticket.

**Comment by chaseakirby** [comment]
@jimuhh Hey Jim, can you please delete [this comment](https://vfs.atlassian.net/wiki/spaces/RD/pages/1652392082/How+To+Use+Zoom+for+User+Research?focusedCommentId=2297561114) on the How to Use Zoom for User Research? Platform Content will flag any source pages that have comments.

**Comment by jimuhh** [comment]
@chaseakirby Done and done.

**Comment by CherylEvans** [comment]
@shiragoodman All Tasks completed, AC met, and verified published, on PW.
