### ISSUE TITLE
[FE] [Tech Debt] Create shared CSS file

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#43045]
## User Story
As a developer, I want shared code between check-in and pre-check-in to be in a single place, versus being duplicated and maintained in multiple places.

## Tasks
- [x] [FE] Create shared CSS file
- [x] Move shared CSS into the new file
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
