### ISSUE TITLE
Evaluate/Learn when each comm. channel should be used.  (Slack, Platform, Confluence)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43054]
## Issue Description
Discover what communications channels are currently intended for which audiences and which information.

---
## Tasks
- [x] Determine which information/audience is intended for Confluence site (noting that some teams cannot access this channel)
- [x] Determine which information/audience is intended for Platform site
- [x] Determine which information/audience is intended for Slack

## Acceptance Criteria
- [x] List/spreadsheet/mural with groupings and Channels

**Comment by tayism** [comment]
[Started drafting a page for this yesterday.](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2240381053/Evaluation+on+Communication+channels+Slack+Platform+Confluence)

**Comment by steel36** [comment]
Think it's useful to add Github discussions as a section in this ticket?

**Comment by tayism** [comment]
Ready for review.
