### ISSUE TITLE
[Design] Create Prototype to Test with Users

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43069]
## User Story
- As a [role], I want to [what] so that I can [do something].

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

## Description
> What will the team get at the end of this ticket?
A wireframes set for [feature name] will be delivered with the technical specifications needed for engineering to implement said feature.

## Tasks
> this is a list of design tasks that are needed for this ticket
- [ ] Finalize detailed mockup and callouts of [feature name](link to prototype)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] %Add any additional Tasks%

## Acceptance Criteria
> when is the ticket done
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
- [ ] %Add any additional Acceptance Criteria%

**Comment by benbrasso-agile6** [comment]
Notes from 7/8 meeting @loripusey @kristenmcconnell 

Notes on MVP: 

Only mileages from home. For example, no carpool, no submitting new address, etc. Chester Peyton is the PM for BTSSS and also is very knowledgeable. He can answer this better, but I think something like 70% - 80% of claims are mileage only.

If additional expenses need to be submitted, then kick them to the travel office or BTSSS. 

Do we need to check if Veteran is eligible? No. Might want to include something on confirmation, like, your claim will be reviewed, etc. 

Open questions: 

Can we ensure someone doesn't get presented with submitting reimbursement twice for one trip? Although, Stephen brought up a point about two locations in the same day. We may need to ask clerks about this.
