### ISSUE TITLE
Update TestRail Ingest System (TestRail => BigQuery => DOMO)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#43071]
## Issue Description
The TestRail ingest system has been broken for many months due to a bug in TestRail's API with the `users` endpoint, causing the _Manual Functional Testing_ dashboard in DOMO to be down (there hasn't been any data to display). On 6/15/2022 we discovered that the API issue has been resolved. It is important to get the TestRail ingest system working again so the DOMO _Manual Functional Testing_ dashboard displays data again.

In addition, it appears that other changes have been made to a number of other API endpoints our ingest system consumes, also causing the ingest system to fail.

---
## Tasks
- [x] Update the dashboard data ingest system to accommodate all changes made the TestRail API endpoints the ingest system consumes.
- [x] Verify that all graphs in the _Manual Functional Testing_ DOMO dashboard display data correctly
  - [x] Fix any _Manual Functional Testing_ graphs that are broken as a result of the ingest system being updated

## Acceptance Criteria
- [x] The _Post TestRail Data to BigQuery_ job in the `qa-standards-dashboard-data` repo runs successfully
- [x] All graphs in the _Manual Functional Testing_ dashboard display data correctly

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/144

**Comment by holdenhinkle** [comment]
A number of updates were made to the TestRail API and lots of them aren't reflected in the API docs. Unfortunately, updating the TestRail ingest is like playing Whac-A-Mole; one issue is fixed, then another one arises.

I updated the retry action this job uses which was causing the job to immediately fail. It appears the action moved from the `nick-invision` GitHub org to the `nick-fields` GitHub org.

In addition, TestRail’s api is constantly throttling us because we’re only allowed to make 180 requests per minute. Every time it does, it makes us wait an arbitrary number of seconds before we’re allowed to make another request. So we’re often waiting `n` number of seconds before making the next request. So I quickly coded a feature that throttles our requests, preventing us from making more than 180 requests per minute.

This job already takes a long time to run (usually over an hour). And I think lots of that is idle time, while we’re waiting to be able to make the next request. I’m hoping this will speed up the job.

**Comment by holdenhinkle** [comment]
I spent the day discovering new, undocumented fields, making updates to the schema, rerunning the job, etc. etc.. And I realized last night that these undocumented fields are probably custom fields. I'll check with Peter about that on Tuesday.

I finally got a successful run late last night - https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/runs/6944826429?check_suite_focus=true YAY!

I also realized that my request throttle feature isn't going to work. Throttling API requests is usually done on the API/server side, as opposed to the client side. The API is operating within a different 1-minute time window than we are, so my throttle feature will always be out of sync with it. I could experiment with making less than 180 requests per minute (like 160 requests per minute) in an attempt to sort of fit into their time window. I'm not sure that would work; just thinking as I type.

**Comment by holdenhinkle** [comment]
I tried setting the number of requests per minute to 160 (instead of 180) and had another successful run, this time with 12 `API Rate Limit Exceeded` errors, as opposed to ~50 in the last run.

**Comment by holdenhinkle** [comment]
I'm going to refactor the throttle system to only send requests every 333ms, which is almost 180 requests per minute,  and see how that works.

**Comment by holdenhinkle** [comment]
All of the Manual Functional Testing graphs in DOMO are working now:

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/026128e5-71bd-4394-94f8-06e89fafc418)

**Comment by holdenhinkle** [comment]
It took 2 retries for this job to run successfully - https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/runs/6948857110?check_suite_focus=true

The first 2 runs failed with this error:
```
{ message: 'Unexpected token < in JSON at position 0' }
Error: Cannot read property 'results' of undefined
Error TypeError: Cannot read property 'results' of undefined
    at Object.getRows (/home/runner/work/qa-standards-dashboard-data/qa-standards-dashboard-data/src/testrail/service.js:145:27)
    at async Object.results (/home/runner/work/qa-standards-dashboard-data/qa-standards-dashboard-data/src/testrail/createTable.js:152:23)
    at async run (/home/runner/work/qa-standards-dashboard-data/qa-standards-dashboard-data/src/testrail/index.js:14:21)
error Command failed with exit code 1.
```

I think I should test that the response body is valid `json` and make the request again if it's not.

I'm going to try my new approach to throttling requests -- just make them every 333 ms.

**Comment by holdenhinkle** [comment]
New throttling approach works. But that `'Unexpected token < in JSON at position 0'` error keeps popping up here and there.

Gonna try testing that response is valid JSON...

**Comment by holdenhinkle** [comment]
I'm pretty sure that the `Unexpected token < in JSON at position 0` is occurring because `html` is being returned sometimes instead of `json`.  

I'm running the job again, looking for when this happens:

```
      if (
        data &&
        data.response &&
        data.response.headers &&
        data.response.headers['content-type'] &&
        data.response.headers['content-type'] !==
          'application/json; charset=utf-8'
      ) {
        console.log('OTHER CONTENT-TYPE HEADER!');
        console.log(data.response.headers['content-type']);
        console.log('data: ', data);
      }
```

It only happens sometimes; some run are successful, while some runs fail do to this error.

This is taking way to long:-(

**Comment by holdenhinkle** [comment]
Just did another run with that flaky error. This is taking way too long. Runs take over an hour.

I'm gonna call this done and move it to review. I'm keeping some of my `console.log`s so I can monitor this job closely.

**Comment by pjhill** [comment]
Hooray, thanks for sticking to this and getting ingest going again!
