### ISSUE TITLE
Collaboration Cycle for [Modernized Check-in, Patient Check-in, Beneficiary Travel]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43074]
### VFS team name

Modernized Check-in

### Product name

Patient Check-in

### Feature name

Beneficiary Travel

### GitHub label for product

HCE-Checkin

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

June 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Other

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md#beneficiary-travel-enhancement)
[Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/initiative-echeckin-with-travel-claim-submission.md)

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add all requested artifacts below **at least two days before** the scheduled Design Intent
  
**Design Intent artifacts**
What is travel pay? VA travel pay reimbursement pays eligible Veterans and caregivers back for mileage and other travel expenses to and from approved health care appointments.

An initial discovery sprint about travel reimbursement and the current [BTSSS system](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) was completed by 18F. One of their recommendations was to "Integrate the BT claim process into the VA’s mobile check-in project roadmap." As a result, they proposed the following [user flow](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/a/1KJKYlw), which involved sending an SMS after an appointment to start the travel pay workflow. They also created this [high-fidelity Sketch prototype](https://www.sketch.com/s/f055a969-7909-4a63-9bb8-1dcbed216a42/prototype/a/C317FBAB-2F9D-4782-A0BA-A64422FB2F85).

18F handed off their work to the check-in team. We started by asking "does filing for travel pay really need to happen after the appointment (18F's proposal) or could it happen at the time of check-in?" We set off to answer this question by completing a technical spike and speaking more with [travel clerks](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/travel-reimbursement). Though numerous conversations, we determined that travel pay could occur at the time of check-in, so we stepped back and created a new series of user flows.

[Here is a link to check-in's user flow exploration with the pros, cons, and impacts to scope for each option.](https://app.zenhub.com/files/133843125/42a6c45c-0ca4-479b-b371-794eeb26bee9/download) Since the creation of this user flow document, the team has learned even more about scope and technical constraints. Some of the current constraints include only being able to file claims for mileage and first time travel pay users will not be able to utilize this feature, because their direct deposit is not set up. We are also continuing to explore if/how eligibility is checked within BTSSS. Our current guess is there is no check. As a result, we narrowed down the user flows to [one](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/a/kaPaz5A) (listed below).

- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] [Proposed MVP User flow](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/a/kaPaz5A). 
- [ ] Research plan
- [x] Any other artifacts you have so far
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: July 25 at 3:30pm ET
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
  - [x] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/ZxeKQ6NnFclqaoiG4CpgHw9gGYcJFwNU8rgbTGCCOF3_PzsCWcSGGPAuWY4nIuxu.ljgX8A3IOgpzlgA2)
  - Password: H6@Ceh?6
  
##### VFS actions

- [x] Respond to feedback tickets
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below

[Content feedback (Word)](https://app.zenhub.com/files/133843125/f8cbacfe-c566-45f6-af51-3211eae9eac3/download)

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add or update all requested artifacts below **at least two days before** the scheduled Midpoint Review
  
**Midpoint Review artifacts**
Provide links or documents for the following:

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md#beneficiary-travel-enhancement)
- [x] [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/initiative-echeckin-with-travel-claim-submission.md)
- [x] [Finalized design prototype or mockup](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/p/8BFD4E55-F0CC-4A7C-B729-7182D20396FC/canvas) (Note: There is no need to review the first four pages within the prototype. Please start on the 5th page and proceed to subsequent pages. E.g., skip the log in and pre-registration questions and begin with pages related to travel pay.)

- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test/research-plan.md) 
- [x] [Conversation guides](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test#conversation-guides) <br><br>

- [Veteran research synthesis (Mural)](https://app.mural.co/t/vfscie8528/m/vfscie8528/1661533294973/772d372cc95132227efcf5b3391ed1a02e41e7df?sender=u83bc52d7fa73658f84f27755)
- [Veteran research participant responses](https://app.zenhub.com/files/133843125/09baaa07-e405-44bb-9a71-f1f9d6ed7e54/download)
- [VA research repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/163#issuecomment-1208087851)
 
**Content artifacts**
  
- [x] [Your product’s content source of truth](https://app.zenhub.com/files/133843125/ce540c02-bcb9-4cfb-be47-43083fd0f197/download)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): <br>

[Prototype D User Flow (I.e., no need to review the other prototype option user flows in this Mural)](https://app.mural.co/t/vfscie8528/m/vfscie8528/1658844568873/93ba988aed6312d43533b8feaed365529b836332?sender=u83bc52d7fa73658f84f27755) 

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [x] Link to test cases/test plan in TestRail (draft OK): [eCheck-in with Travel: MVP](https://dsvavsp.testrail.io/index.php?/suites/view/2134&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: September 27th at 11am ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [ ] IA has completed the review
  - [x] Content has completed the review
  - [x] QA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/JoFcyU29S5x_ISo4Vcb0arZyU4di8cjQZt-nDe0TQv5UA3D5z2fNfQKQuQzCfIqK.0dEF2wd3zXjqIP1w)
  - Password: tt$00m=*

  
##### VFS actions
  
- [x] Respond to feedback tickets
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
Not needed
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
    - [Contact center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51394)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Add or update all requested artifacts below **at least four days before** the scheduled Staging Review
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
  
**Staging Review artifacts**
  
Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- Release plan with the "Planning" sections completed: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/check-in-travel-release-plan.md             
- Staging URL and staging test user information:                   

Staging can be accessed on 5/22 from 2:15pm - 3:15pm ET. Additional instructions provided in [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1684347737265739). 

[Sketch design](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6) for reference. 

**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) https://dsvavsp.testrail.io/index.php?/plans/view/4435
- [x] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan) https://dsvavsp.testrail.io/index.php?/plans/view/4249
- [x] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) https://dsvavsp.testrail.io/index.php?/reports/view/410
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) https://dsvavsp.testrail.io/index.php?/reports/view/409
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)

day-of: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/day-of/tests/e2e
pre-check-in: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/pre-check-in/tests/e2e
shared: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/tests/e2e/pages

- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  

| Application | Lines | Functions | Statements | Branches | Link |
| - | - | - | - | - | - |
| Day-of | 92% | 90% | 92% | 66% | [application folder](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in) ( unit tests are co-located with components, pages) |
| Pre-check-in | 67% | 63% | 67% | 56% | [application folder](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in) ( unit tests are co-located with components, pages) |
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

https://github.com/department-of-veterans-affairs/va.gov-team/issues/58572
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: **Thursday, May 25th at 130 pm ET**

- [ ] Create feedback tickets and link to this epic
  - [ ] Design feedback provided
  - [ ] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/Aaq4X1qBlVO36V9hp2gvK_cr86H0m_IpNaBj-08IDd-OeTp9idCt3JuI73qQBC9H.usgT4lAYlFc5cv1b
  - Password: KtR%%K5G
  
##### VFS actions
  
- [ ] Respond to feedback tickets
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Update the VFS product information section with the product’s launch date and production URL after it has gone live

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
    - [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/967)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by loripusey** [comment]
Thanks @shiragoodman, I may end up having to reschedule this review. The team is blocked on staging test data and I am trying to find out when we anticipate becoming unblocked. If we don't have an answer by tomorrow then I will move the staging review.

**Comment by loripusey** [comment]
@shiragoodman Can you please cancel our Staging Review that was scheduled for Dec. 15? With our blockers, I will need to push this out. I will schedule in Calendly when I have a better idea of when we will be ready.  Thanks.
cc: @mdewey @benbrasso-agile6 @acrollet

**Comment by loripusey** [comment]
Closing because last [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59132)has been closed
