### ISSUE TITLE
[task] QA and Bug Processes

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#43077]
## Value Statement
**_As a_** team lead
**_I want to_** improve our QA and bug procedures
**_So that_** we can better maintain our product throughout delivery.

---
## Background Context
This ticket covers various tasks related to improving our approach to QA and support requests. 

## Tasks
- [ ] _Reach out to the QA team and get their recommendations for team QA._
- [ ] _Get input from the engineers about the QA recommendations._
- [ ] _Create a list of "middleware" items that can be moved to Lighthouse to reduce our need to depend on BGS and VBMS teams._
- [ ] _Revise the template of instructions that Kimberley from the Contact Center shared and send back to her._

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@cohnjesse I dropped this ticket in for the tasks we talked about yesterday. Okay to put this in progress?
