### ISSUE TITLE
Design | Profile | BAI | Pilot 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43097]
## Background

Tasks needed in support of upcoming UAT research project for BAI

## Tasks
- [ ] Schedule pilot(s)
- [ ] Change display name of Perigean Zoom account to "Christina (Moderator)"
- [ ] Run pilot
- [ ] Debrief pilot
- [ ] Revise conversation guide

## Acceptance Criteria
- [ ] Pilot complete
- [ ] Conversation guide revised as needed
- [ ] Any bugs ironed out before sessions begin

**Comment by SKasimow** [comment]
Hi @cgednalske - I added this ticket for a pilot.

**Comment by SKasimow** [comment]
@cgednalske - is this ready to be closed?
