### ISSUE TITLE
[Tech debt] Remove `va-button-primary` class from supported apps

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43098]
## Value Statement

**_As a_** front end developer
**_I want to_** make sure we're following the design recommendations for button & link styles
**_So that_** the styles match the current design

## Background Context

The [design system team announced that the `va-button-primary` class name has been deprecated](https://dsva.slack.com/archives/C5HP4GN3F/p1655474318840829), and needs to be removed. This class adds the green color to primary (blue) buttons. Their [recommendations to change the current button are documented in the design docs](https://design.va.gov/components/button/#links-vs-buttons). This is done on a case-by-case basis.

An audit of our squad's apps shows the following apps include this class:
- [HLR form start button](https://staging.va.gov/decision-reviews/higher-level-review/) (injected in static page)
  - Verify with the content team that the "Request a Higher-Level Review" action link is being rendered within the content page, and not the injected `WizardLink` component
  - If it's not being used (it shouldn't be), we can **remove the `WizardLink` and `createHLRApplicationStatus` files**. The latter file may be imported within the `static-pages` folder, so that'll need to be removed as well

- [526 wizard start button](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/start)
  - The `formStartButton` link should be **changed to action link** (this replaces all 526 wizard buttons)
  - <details><summary>526 wizard screenshot</summary>

    
    <img width="696" alt="526 wizard showing No selected for active duty, and I'm filing a claim for a new condition (etc) selected with a green button stating 'File a disability claim online'" src="https://user-images.githubusercontent.com/136959/174401113-303385f0-af3d-463e-8d04-8161be2f5ed9.png"></details>

- [Letters app download letter button](https://staging.va.gov/records/download-va-letters/letters/letter-list)
  - 3 button states: sucess, failure and default are all set to show the green button in the [`DownloadLetterLink.jsx` file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/letters/components/DownloadLetterLink.jsx#L40-L68)
  - <details><summary>Multiple download letter buttons</summary>

    
    <img width="710" alt="green download letter button shown in 2 letter sections" src="https://user-images.githubusercontent.com/136959/174401851-0049a3a9-56be-427a-a9da-6fb244cf5548.png"></details>
  - We may need to discuss this with design - making all these buttons blue instead of green (removing the `va-button-primary` class will accomplish this. **Maybe turn these into download links with an icon?**

- COE access links (possibly to be used on this [home loans page](https://staging.va.gov/housing-assistance/home-loans/))
  - Links in the [`COEAccess.js` file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/coe-access/COEAccess.js#L12-L18) need to be **changed to action links**
  - These links are injected into the COE static page, which doesn't appear to be used yet

## Tasks

- [ ] Remove HLR static page react component, if possible
- [ ] Update 526 wizard start buttons into action links
- [ ] Update letters app download buttons
- [ ] Change COE buttons into action links
- [ ] Add tests, as appropriate

## Acceptance Criteria

- [ ] All tasks complete
- [ ] All tests passing
