### ISSUE TITLE
[DataDog] Migration to GovCloud: Feedback and technical issues 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#43094]
## Description
As part of the migration to GovCloud, Platform Crew teams will be migrating resources that they own. Resources such as monitors, dashboards, and synthetic tests will be migrated from the current commercial instances to the new GovCloud instance. 

This issue will be used to track feedback and technical issues that they may encounter during the migration. 

## Background/context 
_See_ #23513

---
## Tasks
- [x] Capture issues from Platform Crew teams that arise during the process of migrating resources to the new GovCloud instance

## Acceptance Criteria 
- [x] All feedback and technical issues have been addressed
- [x] Additional issues have been created as needed to follow up on specific issues

**Comment by ElijahLynn** [comment]
CMS Team Here: We are going to need help migrating over, I think. Per this [Slack thread](https://dsva.slack.com/archives/CJYRZK2HH/p1655494972231319) we will gather a list of resources to migrate and post it here.

**Comment by ElijahLynn** [comment]
CMS: We are tracking the migration in this issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9540.

**Comment by joeniquette** [comment]
VA Identity team is working through the import. Currently we are experiencing issues with imported synthetic tests being imported with only one step instead of all the steps. Also we noticed that the configured global variables for each test was not added into each test but the global variable appears available in the list of global variables.

**Comment by oseasmoran73** [comment]
> CMS: We are tracking the migration in this issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9540.

Jumped on a call w/ Elijah and showed him synthetic_test migrated from Terraform (that live in our DevOps repo). Clarified that his team is responsible for migrating dashboards and other resources. Provided `API_KEY` and `APP_KEYS` needed to do so in private Slack DM

**Comment by oseasmoran73** [comment]
> VA Mobile team is in the same boat as the CMS team. I'm working on compiling a list to share as well.

Excellent! Teams are responsible for migrating over their own resources. Documentation has been provided (still needs bit fine tuning) but should help you start getting the ball rolling. I will be adding URL to SSM Param store to get `API_KEYS` and `APP_KEYS`, but please do reach out for any questions or roadblocks!

**Comment by oseasmoran73** [comment]
> VA Identity team is working through the import. Currently we are experiencing issues with imported synthetic tests being imported with only one step instead of all the steps. Also we noticed that the configured global variables for each test was not added into each test but the global variable appears available in the list of global variables.

Very odd. I verified that global configuration have been imported successfully. I suspect since @ianhundere tried to do both at the same time, rather than importing global variables first, then synthetic_tests afterwards.

I have provided Joe `API_KEYS` and `APP_KEYS` to reimport synthetic test. It most likely will require to delete them from DD-GOV. If you run into issue Joe, do let us know and we will help where we can!

**Comment by jsgarmon** [comment]
> Will vagov.ddog-gov.com require folks who work at external companies, IE Ad Hoc, to log into the CAG first before they can access this new server?

No, CAG access is not required to access the Okta site. If you don't have access to ablebets Okta, please follow instructions here: https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance

**Comment by oseasmoran73** [comment]
> The synthetic tests which contain a config for an mfa global variable appear to be failing to be added, error message

Any objection with me deleting that single dashboard (with that source ID) from GUI and reimporting? Curious as towards why it is failing to import

> Also, none of my synthetic tests appear to have any of the recorded browser test steps in them.

I looked at the same one with the ID and confirm that no browser. Did you edit the location?

**Comment by hdjustice** [comment]
Hello all, I set up the Okta login, but when I access the new datadog instance from there, my team's dashboard is not there.  I searched all over, but the "1010 Health Apps" dashboard is not listed anywhere.  I cannot access the **[old Datadog instance dashboard](https://app.datadoghq.com/dashboard/8it-wik-f5q/vsa-1010-team?from_ts=1650559897083&to_ts=1650563497083&live=true)**, so I am blocked from getting to the metrics we need.  Can anyone help me?
cc @markfallows

**Comment by jsgarmon** [comment]
Hi @hdjustice: did anyone on the 1010 team migrate your dashboards over?

**Comment by hdjustice** [comment]
Hi @jsgarmon - it doesnt look like it.  I will see what I can find out.  Thank you!

**Comment by hdjustice** [comment]
Hi @jsgarmon - Our 1010 dashboard did not migrate over, Would you or someone on the team be able to advise how we should do this?
I looked through the previous ticket #23513 and didn't see any resources that would tell us how.  Thanks!
cc @lihanli

**Comment by jsgarmon** [comment]
This is the "1010 Health Apps" dashboard?

**Comment by lihanli** [comment]
@jsgarmon that's right, we also have alerts tagged with `team: vsa1010`, not sure if that's the right spelling but i don't have access anymore to check it

**Comment by oseasmoran73** [comment]
> alerts tagged with team: vsa1010

@lihanli Are you referring to synthetic tests?

**Comment by lihanli** [comment]
@oseasmoran73 yes

**Comment by hdjustice** [comment]
Thank you so much @lihanli and @oseasmoran73 !

**Comment by oseasmoran73** [comment]
@hdjustice @lihanli Migration via CLI has been done. See output below for more details. Please confirm they have been migrated over correctly. We highly recommend having them as code via Terraform like we have it in our [repo](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog)

```
2022-07-06 11:58:37,392 - INFO - Syncing resource: monitors
2022-07-06 11:58:37,665 - INFO - Finished syncing monitors: 4 successes, 0 errors
2022-07-06 11:58:37,665 - INFO - Syncing resource: dashboards
2022-07-06 11:58:37,991 - INFO - Finished syncing dashboards: 1 successes, 0 errors
```

**Comment by oseasmoran73** [comment]
I think that should wrap up this ticket. Thank you everyone for being patient and collaborating with us during the process! Should you run into any issues, please feel free to reach out us via #vfs-platform-support channel.

Closing ticket
