### ISSUE TITLE
Migrate to New Datadog Instance

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43104]
## User Story

VA.gov platform is migrating to a new Datadog instance. We need to ensure that the synthetic monitors and dashboards we are using in the current Datadog instance are migrated to the new instance before the current instance is decommissioned on 6/30.

## Expected Behavior

Existing Datadog monitors and dashboards have been migrated to the new instance with identical functionality.

## Tasks
- [x] Configure Terraform to publish the synthetic monitors to the new instance of Datadog
- [x] Test the monitors hosted in the new instance of Datadog
- [x] Migrate / recreate the synthetic monitor dashboard for all monitors owned by QAS team

## Acceptance Criteria

- [x] The 4 VA.gov production synthetic monitors are setup and running in the new Datadog instance
- [x] The TUD production synthetic monitor is setup and running in the new Datadog instance
- [x] The dashboard that summarizes the synthetic monitors owned by the QAS team is configured and shared with the same people in the new Datadog instance

**Comment by rbeckwith-oddball** [comment]
1. Terraform code is confirmed as working in the new DataDog instance.
2. Monitors have been tested and confirmed as working in new DataDog
3. Migration of the monitors had already been performed since the code lived within the Devops repo
4. The monitors are setup and running in the new DataDog instance.
  a. May need to check if we want to modify the browers that we use for testing, since we had to modify everything to only use 1 for the previous version of DataDog which we migrated from.
5. The TUD production synthetic monitor is working, but had to be modified to allow the certificate issue since the Terraform code doesn't properly set it.
6. [The dashboard](https://vagov.ddog-gov.com/dashboard/g57-gf3-2fc/platform-production-synthetic-monitors?from_ts=1656511784422&to_ts=1656515384422&live=true) is configured and shared with the same people as the old.

**Comment by pjhill** [comment]
Excellent, thanks for running through that! I think we can peel off the issue with the TUD certificate as tech debt that we will pay down in a future effort. @rbeckwith-oddball -- would you please create a new ticket with a summary of that issue and throw it in the backlog?

**Comment by rbeckwith-oddball** [comment]
I technically have a work-around for the issue, but it's not ideal or pretty.

**Comment by pjhill** [comment]
Is that TUD ticket created somewhere? Would you please link it form here when you get a chance?
