### ISSUE TITLE
Improve Communications Playbook via Streamlining of Workflow and Clarification of steps

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43106]
## Problem Statement 
The MVP of the Communications Playbook established some primary guidance on how and where to communicate information across the Platform.  However, it remains somewhat confusing in format and steps.  We intend to improve upon its clarity, add a step-by-step template, and perform additional research to inform recommendations.

## High Level User Stories
As a Platform team member, I want to know what steps to follow to communicate important information to Platform and VFS teams.

As an OCTODE lead, I want to know what channel(s) are to be used for communication of important information

## Hypothesis or Bet
By improving the clarity of the recommended paths, and providing a communication template, Platform teams will more successfully be able to utilize the playbook.

## Known Blockers/Dependencies 
There are various opinions on the optimal communication channels for specific information.  We will need to research these and justify the resultant choice(s).

## Definition of Done
- [x] The existing form of the playbook will be modified to streamline instructions and clarify steps.  
- [x] A new communication template will be created to aid in these steps. 
- [x] The proper communication channels will be incorporated and clearly explained. 
- [x] The playbook is added to the [Platform Initiative Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-initiative.md)

## Projected Launch Date 
Thursday, 8/4/22

### ... tested?

- [x] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [x] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [x] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [x] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool

### ... measurable

- [x] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [x] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [x] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: Change Communication Playbook
* **[Product Outline](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1956020286/Product+Outline+-+Platform+Communications+Playbook)**: 
* **[User Guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2277277697/Welcome+to+the+Change+Communication+Playbook)**: 

### Testing

* **Usability test**: N/A
* **Manual QA**: N/A 
* **Automated tests**: N/A

### Measurement

* **[Success metrics](https://vfs.atlassian.net/wiki/spaces/AP/pages/2226356277/Q3+2022+Crew+Teams+-+OKR+Tracking#Service-Design-Team)**: 
* **[Release plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1956020286/Product+Outline+-+Platform+Communications+Playbook#Release-Plan)**:
