### ISSUE TITLE
Discovery: Discovery Readout Meeting

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#4311]
## User Story or Problem Statement
As a UX designer participating in a discovery sprint, I need to present discovery findings to the team in order to inform them and the product planning going forward.

## Tasks (Hours)
- [ ] Schedule readout meeting (1 hour)
- [ ] Present readout to the team (1 hour)
- [ ] (If necessary) Make any edits to discovery sprint readout (1 hour)

## Acceptance Criteria
- [ ] Readout Scheduled with team
- [ ] Readout occurred
- [ ] (If necessary) Edits made

## Next Steps
- Design

## Blockers / Dependencies
- N/A

**Comment by leahkeeler** [comment]
already happened
