### ISSUE TITLE
Link Platform Office Hours calendar in Collab Cycle/Resources

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43126]
## User Story
As a VFS team member, I want to be able to see and sign up for Collaboration Cycle Office Hours so that I easily get help when I need it.

- Intended Audience: VFS teams
- Desired Outcome: 
- Due Date: 

Assignee: @allison0034 
Peer Reviewer: @jimuhh 

## Description
@naomimarcussen created a [Platform Office hours page](https://calendly.com/platform-office-hours?month=2022-06&date=2022-06-21) in Calendly, making it easy for VFS teams to sign up for office hours with a Platform team. We'd like to link this page within our Collaboration Cycle/ Resources page on Platform Website, making it easy for VFS teams to sign up for office hours. VFS teams will also have an event added to their calendar making it easy for them to remember and attend. In addition, Governance team can see who signed up for office hours, allowing us time to prepare for who is planning on coming.

This should replace the current office hours sign up that is live on the Collaboration Cycle/ Resources page on Platform Website.

## Artifacts Needing Updates
[Resources page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources#Meetings-and-Office-Hours-in-Google)
## Tasks
- [x] Add link to Calendly office hours on Resources page
- [x] Add link to Calendly office hours on Contact Us page
- [x] Remove existing link to office hours

## Acceptance Criteria
- [x] VFS Teams are able to sign up for Collaboration Cycle office hours via Calendly link
- [x] VFS teams are able to sign up for Collaboration Cycle office hours on the Contact Us page

---

## Related Governance Team Resources
_For additional information and guidance to complete tasks, please see links below._
[Documentation Update Guidance for GitHub templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2047868956/Guidance+for+updating+GitHub+Issue+templates) <br />
[Documentation Update Guidance for Platform Website pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089091115/Guidance+for+updating+Platform+Website+pages) <br />
[Documentation Update Guidance for Confluence pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2089222173/Guidance+for+updating+Confluence+pages) <br />
[Guidelines for Governance Team Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1127219219/Guidelines+for+Team+spaces) <br />
[Guidelines for Platform Products and Services Confluence Space](https://vfs.atlassian.net/wiki/spaces/AP/pages/1321140361/Guidelines+for+Platform+Products+and+Services+space) <br />
[Description of Platform Website spaces and content](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization) <br />

---
## How to configure this issue
- [ ] **Ensure that story is attached to appropriate Iniative (if not tech debt)** (what body of work is this a part of?)
- [ ] Ensure that any additional labels are added ('tech-debt', 'collaboration-cycle')
- [ ] Ensure that story is in the correct pipeline (Backlog, Planned, In Progress, Review/QA, Closed)
- [ ] Ensure that assignees are correct so you receive all updates/comments on the ticket

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby after reviewing the [current resources page,](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) I do not think we want to replace the link under meetings and office hours in google. That is still the same, it allows users to view office hours and touchpoints.

Instead I added a link under the scheduling calendars in Calendly. 

Let me know your thoughts, I still need a peer review before you approve.

[Copy of resources](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2255454219/Copy+of+Resources+43126)

**Comment by shiragoodman** [comment]
@allison0034 i am supportive of you not removing the link under meetings and office hours in google. I agree that should stay.

This is out of scope slightly, but can you remove "in Calendly" from "Scheduling Calendars in Calendly"? I don't think the last 2 words are necessary. We'll remove the links to DI/MPR and Staging in another ticket.

**Comment by shiragoodman** [comment]
Could you review the "Contact Us" page? I think there may be an opportunity to link the Platform Office Hours link on that page too.

**Comment by allison0034** [comment]
@shiragoodman yes! What do you think of this [contact us page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2255847425/Copy+of+Contact+us+43126)?

**Comment by shiragoodman** [comment]
Have a question for one of our practice area specialists? Come to our weekly Office Hours listed in the [platform office hours calendar.](https://calendar.google.com/calendar/embed?src=c_7iurst2mk3hdhfuto5u7lemgbk%40group.calendar.google.com&ctz=America%2FNew_York)

Is this link supposed to go to the Calendly Platform Office hours link?

**Comment by allison0034** [comment]
@shiragoodman nope it was supposed to go [here](https://calendly.com/platform-office-hours). I have updated it.

**Comment by shiragoodman** [comment]
@allison0034 changes to both the Resources page and Contact Us page look good. Please update source pages and verify changes have been published after tomorrows scroll viewport run.

**Comment by allison0034** [comment]
@jimuhh pleas peer review [resources](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) and [contact us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) pages have the changes. @shiragoodman once he approves you can close.

**Comment by jimuhh** [comment]
@allison0034: Everything on these two pages looks good. Couple of **very** minor questions...

1. on [resources](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) I notice we're displaying job titles and team members like so:
Fish Farmer: Joe Doaks
without any bolding or alignment to distinguish the two. Is that our standard pattern for this?
2. on [resources](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) we list IA Lead: Mikki Northuis. Is that her job title now that she's on Octode?
Thanks!

**Comment by shiragoodman** [comment]
@jimuhh regarding your questions:

1. yes, its always been our standard pattern. I'm open to suggestions for changing it though.
2. Mikki has been listed as "IA Lead" for a long time. That's not new. However, we likely will have to change it when she does take on her new role with OCTO. I'll create a ticket. Thanks!

**Comment by shiragoodman** [comment]
@allison0034 Looks good. Please update the tasks/AC above, then you can close.
