### ISSUE TITLE
[EKS] Migrate metrics server deployment to k8s-sigs helm chart

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#43130]
## Description
While working on the datadog migration and attempting to make sure all metrics are going to the new datadog org.  I noticed that the metrics server integration wasn't pulling back any metrics.  https://vagov.ddog-gov.com/screen/integration/59/kubernetes-metrics-server?from_ts=1655824831563&to_ts=1655828431563&live=true

This would be a nice to have and shouldn't take too long to fix.

The problem I found is that it doesn't seem like the bitnami helm chart has any real options for opening up a prometheus endpoint in their deployment.  https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/values.yaml

Whereas the kubernetes-sigs does
https://github.com/kubernetes-sigs/metrics-server/blob/2efcd9fe23d41e20660d06eaf15619db25b900ed/charts/metrics-server/values.yaml#L111

---
## Tasks
- [x] Modify the metrics server Chart.yaml to pull the kubernetes sigs helm chart
- [x] Replace the values.yaml file with the one provided by kubernetes sigs
- [x] Update the metrics server infra repo to build and push the kubernetes sigs image to ecr
- [x] Update the metrics server infra repo to update the correct manifest image references

## Acceptance Criteria 
- [x] Mretics server is deployed using the kubernetes sigs helm chart and has a prometheus endpoint available to scrape
- [x] The datadog dashboard is being populated with metrics

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
