### ISSUE TITLE
Expand understanding of Slack as used for comms.

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43146]
## Issue Description
Discover and document what slack channels are currently intended for which audiences and which information.  The following guidance doc contains the most prevalent ones.

Maybe incorporate the use of templates, i.e.:

"I need to x so use channel y"

[Guidance](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1927610461/Review+of+current+state+of+Platform+communications#Slack-communications) from earlier SDT research
---
## Tasks
- [x] Determine which information/audience is intended for specific Slack channels
- [x] Add content to Airtable [base](https://airtable.com/invite/l?inviteId=invzDn9veGSFmmzV9&inviteToken=9d0649c02a681db836a64b5c27a7148e909bb8ebbbdf27333c8bdf0096d156d5&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

## Acceptance Criteria
- [x] List/spreadsheet/mural with groupings and Channels

**Comment by tayism** [comment]
If we survey folks on what they use for communication, it would be helpful to add a question about "Role". I am wondering if we will see any through-lines to Role and the types of communication channels folks use. Do they change at the practice level?

**Comment by tayism** [comment]
A general outline of how Platform uses Slack and some descriptions of channels [here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1891893282/Using+Slack)

**Comment by twoangstroms** [comment]
@tayism Can you expand on your comment above? Do you mean "Role" as in Engineer/Designer/etc.? And can you explain that last question?

**Comment by tayism** [comment]
@twoangstroms Role could be better defined as persona here -- designer, fe eng, be eng, pm, etc.

I am wondering if certain channels are used more often by a certain persona. For example, I have heard through the ether that #vfs-all-teams is used most by PMs, but it would be helpful to have some data around this, and other channels as well. I think if we include a question in our later polls/surveys it would be important to include a question about "What is your role", like we do in the satisfaction survey.

**Comment by tayism** [comment]
I did an initial scan of the listed channels in the Airtable and added a checkbox column “Need”. After looking through it, I started to lean toward channels that had some combination of community/support/practice. 

I agree with the sentiment earlier discussed in our sync that team channels need not be included in what we are trying to learn here.

**Comment by twoangstroms** [comment]
Thanks -- that's very helpful thinking.
