### ISSUE TITLE
Confirm and implement IA and urls for new education pages (non-rates)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43155]
## Issue Description
This issue is to keep track of the H1s, left nav labels, and urls of the new education pages we are publishing once the modernized rates pages are live.

Mikki has already reviewed and approved these in ticket #42952 but we are separating out the non-rates education pages from the rates pages.

H1: Apply to restore your GI Bill benefits
Revised URL: /education/apply-to-restore-gi-bill-benefits
Left nav label: Apply to restore GI Bill benefits
Note from old ticket: This page is the last page within the "Manage Benefits" spoke.

Resident rate requirements
This will be an R&S page so H1 determines url

Compare education benefits
This will be an R&S page so H1 determines url

Once we create the 2 R&S pages we should note the H1s here. 

## Tasks
- [ ] Confirm urls and left nav content (Mikki)
- [ ] Update pages if needed

## Acceptance Criteria
- [ ] All education non-rates pages have correct urls and left nav content

**Comment by mnorthuis** [comment]
This looks good @RLHecht, do you need anything else from me?

**Comment by mnorthuis** [comment]
@RLHecht @bethpottsVADEPO  Do we need to also implement redirects on the old legacy pages once these are in place?

www.benefits.va.gov/gibill/post911_residentraterequirements.asp
www.benefits.va.gov/GIBILL/comparison_chart.asp

**Comment by RLHecht** [comment]
@mnorthuis we are ready to publish the compare education benefits page later this afternoon. I have the placement for the left nav but we're also now adding a link to the hub landing page under the More resources section. Where should we place it?

**Comment by bethpottsVADEPO** [comment]
@RLHecht I think we can close this ticket. Want to double check me on that?

**Comment by RLHecht** [comment]
Resident rate requirements and Apply to restore your GI Bill benefits are still draft pages that we haven't finished working on. @bethpottsVADEPO should we move this to the backlog or create a new ticket to track those 2 when we're ready?

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you mind closing this one and creating a new ticket for us to assess what's next with:

**H1: Post-9/11 GI Bill Resident Rate Requirements**
URL: https://www.va.gov/education/benefit-rates/resident-rate-requirements/
Preview link: https://preview-prod.vfs.va.gov/preview?nodeId=1006
Left nav label: Resident rate requirements

**H1: Apply to restore your GI Bill benefits**
URL: /education/apply-to-restore-gi-bill-benefits
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=5573
Left nav label: Apply to restore GI Bill benefits
Note from old ticket: This page is the last page within the "Manage Benefits" spoke.

Make a note that we need to take this page into consideration too: https://www.va.gov/resources/in-state-tuition-rates-under-the-veterans-choice-act/
