### ISSUE TITLE
Prep questions for VFS team members

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43157]
## Issue Description
Get feedback from VFS - how do they receive or expect to receive information? (also an introduction of sorts to working w/ team)

Form could take Optimal Workshop survey or Slack poll, etc.

https://dsva.slack.com/archives/C02QN5J3FK6/p1658246368681459?thread_ts=1658243570.365569&cid=C02QN5J3FK6

Questions:
Can we and should we move to a unified channel for communication? #38946
---
## Tasks
- [x] Identify potential participants (likely engineers, PMs)
- [x] prep questions or poll (how do you expect to hear about things, how would you like to hear about things if you could choose)

## Acceptance Criteria
- [x] Prepared question guide, poll, or survey

**Comment by twoangstroms** [comment]
[Possible reference list?](https://airtable.com/appZlF01Fn19x3Ty0/tblIeeEMmzDkuYX06/viwuijxmMi2E4rAc8?blocks=hide)
