### ISSUE TITLE
Conduct VFS poll

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43156]
## Issue Description
Get feedback from VFS - how do they receive or expect to receive information? (also an introduction of sorts to working w/ team)

## User Story
As a SDT member, I want to know how VFS users prefer to get their communications, currently or possibly, so that we can determine how to recommend or create communication channels.

## Tasks
- [x] Launch poll in predetermined channels 
- [x] Gather feedback via poll

## Acceptance Criteria
- [x] List of preferred comm channels

**Comment by gopixelsgo** [comment]
Poll was launched 7/20/22 in [#vfs-all-teams](https://dsva.slack.com/archives/CE4304QPK/p1658333543607519) and cross-posted in [#vfs-engineers](https://dsva.slack.com/archives/C01UB5A823V/p1658333952392739)

Responses are being synthesized in [this Mural.](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658410214268/bea416f552aead3b47501d9f94ef930de7116cef?sender=u311209e67c8c21a1b37a8167)
