### ISSUE TITLE
[FE] Use curly quotations marks consistently

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43159]
## Background

The VA design system specifies that [curly quotation marks should be used instead of straight quotation marks](https://design.va.gov/content-style-guide/punctuation#quotation-marks).

## Tasks
- [ ] [FE] Ensure that all content uses curly quotation marks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
