### ISSUE TITLE
Data QA - Document Standardized Dashboard GA Equivalents

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43169]
## Issue Description
As part of the Data QA processes documentation we need to complete the [Data QA - Standardized Dashboard GA Equivalents](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents) subpage under "How to Data QA Domo dashboards" section in Confluence

---
## Tasks
- [ ] Complete any missing GA Equivalent and GA Assets sections
- [ ] Confirm current sections are update to date and accurate
- [ ] Add any new sections as applicable

## Acceptance Criteria
- [ ] Documentation has been completed and reviewed by the team.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathan-epstein13** [comment]
[Search QA-GA Template](https://docs.google.com/spreadsheets/d/1eX3D6p3Dw2unntfVuNyZup_1qPORhxs3aaukoJTDMbc/edit#gid=0)
[Forms QA-GA Template](https://docs.google.com/spreadsheets/d/1_pjD3Hvv5KtDF45oz3G8xbET1D-CSaL88pX-iyGVwX4/edit#gid=0)
[Content QA-GA Template](https://docs.google.com/spreadsheets/d/10ntfDxR2OKxPJ0FI6gCzoyHu1XfbW1-uKKSH1F8ZfOc/edit#gid=0)

These are the templates ready for QA. I have a few blockers that I am working on (probably involve more in depth BQ metrics) I'll do my best to find the solution(s).
