### ISSUE TITLE
Acquire SSL certificates for new platform-api domains

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#43160]
## Issue Description
SSL certificates for the new domains need to get purchased and validated. The steps for obtaining new, publicly signed SSL certificate are [outlined in this document](https://vfs.atlassian.net/wiki/spaces/OT/pages/1644625921/Obtain+or+Renew+Publicly+Signed+SSL+Certificates).

---
## Tasks
- [x] Install SSLMate and set up locally
- [x] Email Edge Security Operations team (NOCNetworkEdgeOperations@va.gov) to alert them to look out for validation email
- [x] Once validated, download the new certificates

## Acceptance Criteria
- [x] Four SSL certificates for the new *platform-api.va.gov domains have been acquired
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
