### ISSUE TITLE
Create nginx configuration file for new platform-api domains

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#43161]
## Issue Description
The reverse proxy (nginx) needs to have configuration to correctly route the four new `*platform-api.va.gov` domains to the respective vets-api versions in the different environments. The configuration details will largely be based on the existing configuration for the `*api.va.gov` domains. 

---
## Tasks
- [x] Create new Nginx configuration file for the new domains
- [x] Discuss details of configuration file with domain experts
- [x] Leave the unknown parts blank (e.g. SSL cert details)

## Acceptance Criteria
- [x] Nginx configuration file exists on WIP branch
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
