### ISSUE TITLE
BQ - Form User Completion Connector - Decommission "form_name" field

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43170]
## Issue Description
The BQ - Standard Forms User Completion connector didn't get its join conditions updated when the Forms Funnel table changed the name of the form_name field in use to form_name1. In the future, I think we should decommission the current form_name field which contains the version name, and use the one we're actually using in that name. It's not being used anywhere, and this is the second data issue its caused.

---
## Tasks
- [x] Decommission "form_name" field for the new "form_name1" field
- [x] QA data to ensure updates are as expected

## Acceptance Criteria
- [x] The above tasks have been complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Hi! I'm going to wait until Monday to close ticket to make absolutely certain that datasources update correctly, but I believe this task is complete. Documenting process below:

### Issue
The cause of this issue was that when Julie had been experimenting with form/version tables, the previous form name field had been changed to the less intuitive `form_name1` while `form_name` was given to a unformatted concatenation of form and version that was used in BigQuery grouping/join conditions, but not brought in to Domo. However, because it was the more intuitive and previous name for our forms filters, on several occasions it was not changed to `form_name1` in Domo queries, leading to incorrect/incomplete production data on the Forms dashboard. While we need to keep the grouping logic in BQ, the naming convention needed to be changed to something that would make these mistakes less likely.

### Scope of change
Because we had already reverted **vw_forms_engagement** views to their previous versions after the late May Forms dashboard error, the only BigQuery views needing changes were **vw_forms_funnel** and **vw_forms_funnel_last_week**. In both cases, I changed the new, concatenated `form_name` to `form_full_version` and removed `form_name1` aliasing to return the original field to its original name.

On the Domo side, the [Standard Forms Funnel](https://va-gov.domo.com/datasources/432a85a7-5581-4e80-8601-dc13c9654436/details/overview) and [Standard Forms User Completion](https://va-gov.domo.com/datasources/ce60393c-d983-4b22-8884-b8941dbaeb8b/details/overview) data connectors both reference the **funnels** BigQuery views. This did not require a backfill, but I changed both intake fields to pull in `form_name` instead of `form_name1` (and then aliasing to `form_name`).

### QA
To make sure the updated script ran correctly, I created a temporary BQ view of the last_week data with corrected naming conventions. I then build two new test Domo connectors with the adjusted queries, referencing the test BQ view, so as not to impact the production data if there were any errors. Both data sources ran without any errors. 

Then, I compared filtered the production data sources for the last week of data and compared them against the test Domo datasets, checking for:

- same row count
- same number of columns
- same number of nulls per column

### Next steps
Everything looked great, so I brought over changes to the production version of BigQuery views and Domo datasets. As part of my final check on Monday, I'll delete these tests to clean up our workspace.

**Comment by chloedotbrown** [comment]
Update successful. Deleted test datasets/views in BQ and Domo. Closing ticket.
