### ISSUE TITLE
Fixes Sign in Service bugs

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#43174]
## Issue Description
There are two minor issues 1.) The API side has changed the Sign in Service URL from a type parameter to a query parameter to reduce the number of URLs needing to be parsed and 2.) Fixes a minor bug with the Unified Sign in Page (USiP) redirecting with Google Analytics' client id parameter.

## Tasks
- [x] Changing the Google Analytics `client_id` to `ga_client_id` to not interfere with the Sign in Service OAuth `client_id`
- [x] Changes the <CSPs> parameter type to be a query parameter `?type=idme`

## Acceptance Criteria
- [x] When signing in the Google Analytics tracking id is passed in as the `ga_client_id` query parameter
- [x] The Sign in Service URL is `https://<environment>/v0/sign_in/authorize?type=<CSP>`
