### ISSUE TITLE
[Investigate] Reserved Instances

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#43173]
## Description
Reserved instances used to be used here a long time ago for more cost efficiency. Perhaps after we migrate to EKS fully or when our AWS account gets separated out (further divide with us and other services with full operations teams)

## Background/context 
Old scripts removed in https://github.com/department-of-veterans-affairs/devops/pull/11443, but dropping here for awareness

---
## Tasks
- [ ] Investigate potential cost savings of leveraging reserved instances within AWS

## Acceptance Criteria 
- [ ] Investigation / cost-analysis completed for potentially reserving EC2 instances
- [ ] Decision made on moving forward
- [ ] Reserved instances being leveraged for cost efficiency (pending team decision / prioritization)

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
