### ISSUE TITLE
My VA Redirect current page bug

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#43171]
## Issue Description
Fixes a bug in the My VA Redirect body of work in which the redirect does not allow the `.current-page` class to be added to the My VA link in the menu.  This bug occurs because the `postLogin=true` query parameter is appended after a successful login and the mega menu link data does a one-to-one strict equality match.

## Tasks
- [x] Update the `flagCurrentPageInTopLevelLinks` method to not use strict equality
- [x] Ensure tests pass as expected

## Acceptance Criteria
- [x] Using the My VA redirect (aka signing in on the homepage)
