### ISSUE TITLE
[TIMEBOXED] [FE] [SPIKE] "Definition" is being read by screen readers after each definition list item

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43176]
## Timebox
Timeboxed to 1/2 day

## Background

Jose Beltran reported the following:

> I tried this morning and I was able to get to the link. I did my first run and I did not find any accessibility issue yet. But, when I am swiping right on the fields that already contain input from the test account. Talk back says “definition” each time. Just curious why it’s doing that?
 > Device OS: Android
> Model: Galaxy S21

I asked for clarification and he said:

> My apologies Adrian for not being clear. Every pre-populated field that is associated with the test data. For example,
after the text Any Street is read, talk back also says definition. When I swipe to the next element Home address and talk back reads Not available, talk back says definition and so forth. I saw this behavior throughout all the form screens.

@brianseek mentioned that the platform accessibility team recommended using definition lists in this situation.

## Tasks
- [x] Sync with platform accessibility team to see if this is expected behavior and/or if they have a specific recommendation (use this [channel](https://dsva.slack.com/archives/CBU0KDSB1) and choose collab cycle as the team)
- [x] Implement recommendations and/or create follow-on ticket
- [ ] Sync with UX & product on how best to ensure that the app is reviewed with a screen reader on a periodic basis
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
VFS platform support slack thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1656707060469079

**Comment by acrollet** [comment]
I will sync with @briandeconinck next Thursday to demo and discuss.

**Comment by acrollet** [comment]
@briandeconinck and I just met and he has some recommendations that he is going to write up. Once they're received I'll add a ticket or tickets to the backlog and we can close this out.

**Comment by acrollet** [comment]
I've created https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44145 to implement the recommendations we've been given.
