### ISSUE TITLE
[Research] My VA Redirect: Synthesize findings from UAT/usability testing 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43188]
## Background
Once UAT/usability sessions are complete we'll need to synthesize and review our findings to determine if any changes are needed to the feature before proceeding to our next steps with this engagement.

## Tasks
- [x] Synthesize findings
- [x] Create write up
- [x] Review/share with team

## Acceptance Criteria
- [ ] Findings have been documented and reviewed with team
- [ ] We have a clear list of action items (as needed) and path forward for next steps toward launch

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** ________
- **_How can this work be validated?_** __________

**Comment by ajakabcin** [comment]
Bumping out to next sprint to allow for time to resolve issues with redirect not appearing consistently for all users when the feature flag is enabled

**Comment by andaleliz** [comment]
Here's [the mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1659364841359/d8cd5e9bff56277bacd9acec59670c1f6f121612?sender=lizlantz1528) I'm using to capture notes, and the [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/topline-summary.md) I'll finish up over the weekend for review on Monday.

I'm not planning on doing verbatim transcription but am capturing important quotes on the Mural board.

**Comment by andaleliz** [comment]
Hi @ajakabcin @Samara-Strauss and @ericasauv09 - [here's the topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/topline-summary.md).  I set up a time for us to review Monday morning, but if for some reason you can't make it, I would be very appreciative if you can review and drop feedback here before EOD.

I'm wondering which type of final report will be most useful to the team.  I can add more detail to this topline summary (based on feedback, we can determine what we need to fill out), or I can create a more in-depth research report.  It's kind of a gray area to me since this was a hybrid UAT/Usability session and there aren't any code or design bugs we need to fix as a result. What are your thoughts?

**Comment by andaleliz** [comment]
@ajakabcin I think your instinct is a good one - that's the same sense I got in terms of where he's used to going now.  He clearly understood that My VA was his personalized page when he saw it though, so hopefully that retraining won't be too much of a hurdle.

I've added details to the report and moved it to [a doc called "research findings"](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/research-findings.md) so it'll be clear in 6 months what we did (topline summaries can be pretty drafty sometimes).  

I also added a recommendations section that captures what we discussed yesterday, including digging into the view lab and test results link.

@Samara-Strauss @ajakabcin and @CatherineHughes202 please let me know if you have any further edits. If not I'll go ahead and close this out.

**Comment by Samara-Strauss** [comment]
This looks great to me!

**Comment by andaleliz** [comment]
Awesome! Hearing no other feedback, I'll close this out. Thanks for your review everyone!
