### ISSUE TITLE
[Design] Payment info V2: Update designs for Midpoint review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43189]
## Background
We received some feedback from IA/content regarding terminology in v2 of our payment info designs. We're going to make these updates (mostly copy related) in advance of our Midpoint review scheduled for tomorrow (6/23). Original slack thread [here](https://dsva.slack.com/archives/C909ZG2BB/p1655917987470259) for reference.

## Tasks
- [x] Change the current heading on the "Bills and payments" section to "Debt and payments"
- [x] Change the "Outstanding bills" heading to "Recent unpaid debt"
- [x] Change the link for "Manage your VA bills" to "Manage your VA debt" to match the H1 on that landing page
- [x] Change the link for "Manage your direct deposit" to "Manage your direct deposit information" since the user isn't managing the deposits, just the information about deposits

## Acceptance Criteria
- [x] Make updates as outlined in the tasks above
- [x] Notify PM when complete so we can update the link(s) in the Midpoint review ticket
- [x] Review research artifacts (plan, prototype and convo guide) to make updates there to be consistent with changes made above

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1655917987470259)

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** review designs, research materials and prototype to confirm updates have been made
