### ISSUE TITLE
[Research] My VA Redirect: Conduct UAT/usability testing 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43187]
## Background
We need to conduct UAT/usability testing on the My VA redirect feature. According to the test plan (link tk), we will conduct this plan in production. 

## Tasks
- [ ] Coordinate with FE dev to ensure feature flag works properly prior to testing sessions
- [ ] Conduct UAT/usability sessions

## Acceptance Criteria
- [ ] Sessions are conducted/complete

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ NA
- _How can this work be validated?_ NA

**Comment by andaleliz** [comment]
Despite not meeting all recruiting criteria we requested (we had no LOA1 users, and only 1 screenreader), we feel that we've answered our research questions for the purposes of UAT and ended the study after 10 sessions.
