### ISSUE TITLE
[Research] Payment info v2: Kick off research recruiting

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43192]
## Background
We need to submit all research artifacts for v2 payment info and onsite notification design component.

## Tasks
- [x] Submit materials to research repo
- [x] Message research ops in slack to let them know you've submitted the materials
- [x] Perform any followup tasks that research team requests

## Acceptance Criteria
- [x] Materials are submitted and recruiting for our study has started

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** NA
- **_How can this work be validated?_** NA

**Comment by ajakabcin** [comment]
Depending on feedback from midpoint review scheduled for 6/23 we may be able to move this up/bring it into the current sprint cc @aagosto90  and @ericasauv09

**Comment by ajakabcin** [comment]
Due to feedback from Midpoint Review we need to push next steps with research out to a later sprint.
