### ISSUE TITLE
[Design] OnSite Notifications: Update research artifacts to include onsite notification component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43190]
## Background
We're including the onsite notification component that Angela has designed to the next round of research on v2 of the payment info section. We need to update all research artifacts to include the component.

## Tasks
- [x] Update the research plan
- [x] Update the prototype
- [x] Update the conversation guide
- [x] Request review from team

## Acceptance Criteria
- [x] Updates are made and reviewed by team

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Any team member
- How can this work be validated? review research materials and prototype to confirm updates have been made.

**Comment by aagosto90** [comment]
These updates are all done but we will postpone reviewing as a team until we meet to review updated v2 designs

**Comment by ajakabcin** [comment]
@ericasauv09 let's move this to the next sprint to align review of these with review of v2 payment info designs. I'll update the sprint and milestone fields here if you could add to 78 epic. Thank you!
