### ISSUE TITLE
SiS Documentation Improvements Pt 2

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#43207]
## Issue Description
Various tasks to improve SiS documentation in Postman and Github, second part. Part 1 is #41521

---
## Tasks
- [x] update documentation to explain Postman authentication
- [x] add optional `state` param to authorize/callback routes for mobile
- [x] Update `refresh_token`/`access_token`/`info_token`/`anti_csrf_token` from a successful `token` & `refresh` response
- [x] Clear token values from a successful `revoke` response

**Comment by bramleyjl** [comment]
After further investigation I'v concluded that creating some sort of automated end-to-end authentication for Postman is probably impossible. The authentication process relies on multiple form submissions and while I discovered [Postman Interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en) as a useful tool there does not seem to be any sort of automated URL filtering & parameter capturing capabilities; the tool is designed to function in a debugging context.

As such I decided instead to simply update the documentation to guide a user on how to authenticate via web browser and then copy the vets-api generated `code` into Postman's `auth_code` param, which will let them use the post-authentication routes, starting with `/token`, on the Postman client.
