### ISSUE TITLE
[Research] Payment info v2: Synthesize usability testing findings

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43209]
## Background
Once usability testing is complete on v2 of payment info + onsite notification component, we'll need to synthesize and review our findings to determine if any changes are needed before proceeding to our next steps.

## Tasks
- [x] Synthesize findings
- [x] Create write up
- [x] Review/share with team

## Acceptance Criteria
- [x] Findings have been documented and reviewed with team
- [x] We have a clear list of action items (as needed) and path forward for build on v2 of payment info and experimental design process for the onsite notifications component

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** NA
- **_How can this work be validated?_** NA

**Comment by aagosto90** [comment]
[Topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/research-findings.md) and [research findings deck](https://docs.google.com/presentation/d/1d3DXPIAXbG2kF3pl8U1tYfqXQLmc23MzWYJ8i2hUhOU/edit#slide=id.ge360b30891_0_527)
