### ISSUE TITLE
[PM] My VA Redirect: Contact center guide updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43210]
## Background
Before we go live with the My VA redirect we need to update the call center guide with the appropriate information.

## Tasks
- [x] Update call center guide
- [x] Have APM/PM review (whoever didn't do the edits)
- [x] Send to Samara for review
- [x] Submit to [call center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) with product guide
- [ ] Once approved update the product guides versioning documentation found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md).

## Acceptance Criteria
- [ ] Call center guide is updated with onsite notification information and final version is stored in our team documentation

**Comment by ajakabcin** [comment]
Updates to the product guide include the redirect as well as onsite notifications (#42750)

**Comment by ajakabcin** [comment]
Submitted to Samara for review as noted in [42750](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42750#issuecomment-1197499742)

**Comment by ajakabcin** [comment]
Updated and submitted to call center #45091

**Comment by ajakabcin** [comment]
VEO accepted our latest version of the product guide with no edits. I've logged the final version as submitted with a summary of the version changes [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md) (includes updates for onsite notifications as well)
