### ISSUE TITLE
[FE] My VA Redirect: Support UAT/usability testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43211]
## Background
We will need our FE dev to manage the feature toggle on production for our UAT/usability testing of the My VA redirect feature. 

_Since we will be enabling the feature for specific individuals participating in the study, if you are unable to attend sessions please plan ahead to provide a backup who can both enable/disable the feature flag and provide support to the researcher during these sessions._

## Tasks
- [ ] Work with the designer leading the sessions to ensure feature flag works properly prior to the testing sessions: enable to feature for individual team members on production and have them confirm it
- [ ] Provide technical troubleshooting support during the research sessions (should any issues come up)

## Acceptance Criteria
- [ ] Sessions are conducted/complete

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)_** any team member
- **_How can this work be validated?_** In advance of usability/UAT sessions (including the pilot session) test the feature flag _on production_ to confirm that you can successfully enable and disable the feature. Test with multiple team members.

**Comment by ajakabcin** [comment]
Bumping out to next sprint to allow for time to resolve issues with redirect not appearing consistently for all users when the feature flag is enabled

**Comment by tmitchellgcio** [comment]
Everything now seems to pass just fine when testing. Had issues with the CI process, but they are fixed for now. This can likely be validated on http://8ee3ad362a8f5cec045b10abb3437c0c.review.vetsgov-internal/ @ajakabcin @ericasauv09

**Comment by ericasauv09** [comment]
@tmitchellgcio  did you mean to comment this on #44533 ?
