### ISSUE TITLE
Supplemental Claims | Build out framework

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43219]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Supplemental Claims form template
**_So that_** we can coordinate with team members on the design and flow of the form

## Background Context

The Supplemental Claims (SC) form (20-0995) is in the process of being structured, and having an online framework would help the team coordinate, evaluate and optimally design the online form.

## Acceptance Criteria

- [ ] Build the SC framework
- [ ] Prevent framework from being seen in production

## Tasks

- [ ] [Build form template using the Yeoman generator](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application)
  - Set the rootUrl to `/decision-reviews/supplemental-claim/request-supplemental-claim-form-20-0995` for now
  - Title to `Request a Supplemental Claim`
  - Description to `VA Form 20-0995 (Supplemental Claim)`
  - OMB control number to `2900-0862`
  - Respondent burden to `15` minutes
  - Expiration date to `4/30/2024`
  - Blank form template
- [ ] Add form to content build registry (if not already added)
- [ ] Set up rootUrl in devops
- [ ] Add feature flag
- [ ] Add form ID to platform constants

## Definition of done

- [ ] All tasks complete
- [ ] SC form framework visible locally & in staging only

**Comment by Mottie** [comment]
A feature flag has not yet been added, but everything else is done and ready for code review
