### ISSUE TITLE
[BE] [TECH DEBT] Authentication does not work on review environments with Safari

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43212]
Time Boxed to 1 day

## Background

While testing @randomsync's [changes to make authentication work on review environments](https://github.com/department-of-veterans-affairs/vets-api/pull/10082), we noticed that it still does not work on Safari. We believe this might be happening because we do not send a cookie `Domain`, and Safari treats non-standard TLDs (such as `vetsgov-internal`) differently. ([ref](https://stackoverflow.com/questions/62023857/sharing-cookies-across-test-sub-domains-in-safari-13-not-possible))

Any solution must ensure that authentication regressions are not introduced in production, and would ideally only change the behavior for review environments.

## Tasks
- [ ] [BE] **_insert backend  work_**

## Acceptance Criteria
- [ ] check-in and pre-check-in function on review environments with Safari
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by brianseek** [comment]
Opened platform support request: https://dsva.slack.com/archives/CBU0KDSB1/p1670367002044829

**Comment by brianseek** [comment]
This seems to be not a big enough priority for the devOps team at the moment. This will just have to be a known issue when testing on review instances. See prod support thread for more details. Closing for now.
