### ISSUE TITLE
Contact Center Tickets

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#43222]
## Value Statement
**_As a_** Contact Center team 
**_I want to_** clear the Zenhub backlog of open support tickets
**_So that_** I can transition support tickets to Salesforce. 

---
## Background Context
This epic covers support tickets related to benefits-team-1. The Contact Center is moving their support portal into Salesforce. 

## Acceptance Criteria
- [ ] All tickets are properly assigned, responded to, and closed. 

## Tasks
- [ ] Review tickets with @cohnjesse 
- [ ] Decide on best course of action for each
- [ ] Notify Kimberley

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
@saderagsdale thank you for getting this together.  It appears that all the previous ZH tickets are listed here.  Please advise how we can be of assistance.
