### ISSUE TITLE
10-10EZ: Registration Path MVP

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#43221]
## Description
It has been decided to run an experiment to determine the Veteran use case/need for a Registration Only path online within the 10-10EZ form.  We will be targeting Veterans who have a 40% or less disability rating that may want to seek care for their service connected disability only (all other ailments would be seen by a private doctor).  Please review the [Experiment Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Reg%20Only%20experiment%20proposal.md) for more details.

If it is determined that there is enough interest and traffic to indicate a need to provide the Registration Only pathway online within the first 30 days, we will run a research interview plan with Veterans to help us decide on how best to present the pathway in an easy-to-understand and transparent way within the EZ form.  This new pathway will be an iteration and new Epic.

### Resources
- [Registration Only folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration)
- [10-10EZ Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Health%20Care%20Application%20-%20Product%20Outline.md)
- [Registration Only - Experiment Proposal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Reg%20Only%20experiment%20proposal.md)
- [UX resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/ux/readme.md)
- [MVP Figma designs](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3025-106249&node-type=CANVAS&t=M889KfkZE75RoW3h-0)
- [Mural - Discovery board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?sender=u5ad49c107baa41137f271007)
- [Mural overall folder](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670613238628?folderUuid=eb1cd9df-3cca-4008-9d32-29c42520a4ba)
- [Figma Designs - early iteration options](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=86-36817&mode=design&t=CC8P8lyEeGsdJei8-0)
- [VHA Directive (amended January 10, 2023)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Registration%20and%20Enrollment%20directive%20-%201601A_01(1)_D_2020-07-07.pdf)

**Problems**
- The current Online 10-10EZ application can only be used for enrollment purposes.
- This is a directive from the stakeholders to provide a "registration" pathway online
- Veterans who cannot qualify for VA health care enrollment must register for specific health care services, but this process is not available online, only by paper application

**Outcomes for MVP - Definition of Done**
By running this experiment, we will determine whether there is a Veteran experience use case/need for a registration pathway on the online 10-10EZ

```[tasklist]
### Tasks
- [ ] #79634
- [ ] #81928
- [ ] #80831
- [ ] #89214
- [ ] #81932
- [ ] #80832
- [ ] #67133
- [ ] #81103
- [ ] #81104
- [ ] #81115
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91901
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91896
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91898
- [ ] #91373
- [ ] #91374
- [ ] #89738
- [ ] #72311
- [ ] #67390
```
