### ISSUE TITLE
Cloud Isolation - Procure platform-api subdomains

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43237]
## Problem Statement 
In order to use a new domain for vets-api, the new *platform-api.va.gov subdomains will need to be procured for all environments (dev, staging, sandbox, and prod.)

How might we optimize the request process so that we can minimize the time spent on procurement?

## Hypothesis or Bet
Requesting all domains simultaneously will accelerate the ability to launch the new platform-api subdomain. 

## We will know we're done when... ("Definition of Done")
- [x] Requests have been registered and submitted using proper protocols.
- [x] ESECC is approved.
- [x] All requested subdomains have verifiable, internal and public DNS records.
- [x] All public subdomains are accompanied by security certificates.

## Known Blockers/Dependencies 
ESECC adjudication process.

## Projected Launch Date
July 19, 2022. (Sprint 21/82)

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. **NA**
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching **NA**
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD **NA**

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide) **NA**
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0) **NA**
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool **NA. May require updating in Q4 or later.**
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings) **NA**

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. **NA**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). **NA**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. **NA**

### Documentation
* **`PRODUCT_NAME`**: Cloud Isolation Team
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525
* **User Guide**: [Hostname Specifications Doc](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2283339976/Guide%3A+Hostname+Specifications+-+Cloud+Isolation)

### Testing

* **Usability test**: NA
* **Manual QA**: [Curl commands](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525/Product+Outline+-+Cloud+Isolation#Manual-Domain-Resolution-Tests%3A)
* **Automated tests**: [Datadog Tests](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3Acit%22%29)

### Measurement

* **Success metrics**: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
* **Release plan**: [Hostname Transition Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/52a7afdd00f396d1727aed4869382f963d348531/platform/engineering/infrastructure/hostname_transition_plan.md)

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by alwerner** [comment]
@mchelen-gov Status update: Started

We need you to add this to the Digital-Experience-Product board.

**Comment by alwerner** [comment]
@mchelen-gov Status update: Completed

We need this added to the Digital-Experience-Product board.
