### ISSUE TITLE
Investigate Branch Protection for Cypress with No Code Change PRs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43236]
# Description
Currently, pull requests submitted to `vets-website` that do no contain code changes do not trigger Cypress E2E tests to execute. In turn, the branch protection check that requires a passing Cypress test is not satisfied. Users need to be able to submit changes without code such as READMEs and not be stopped from merging by branch protection.

# Tasks
- [x] Examine branch protection rules in GH
- [x] Develop a strategy for dealing with changes that don't require Cypress tests to run

# Acceptance Criteria
- [x] `vets-website` pull requests that do not contain code changes are permitted to merge by branch protection rules

**Comment by holdenhinkle** [comment]
I chatted with Darius about this:

> It seems to be a bug in GitHub’s branch protection
> 
> The “fix” for that branch protection task is to always run the Cypress jobs in CI but skip every step when no tests are selected
> 
> At least, that’s the only fix I can think of.

This is just for running tests against main.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/21681

**Comment by holdenhinkle** [comment]
Currently, no-code PRs (branches that only update `.md` files) can't be merged because of a bug in GitHub's branch protection. This bug requires the `cypress-tests` job to always run, but currently, it only runs when tests are selected.

The proposed fix is to always run the `cypress-tests` job and skip each step in the job if no tests are selected.

## Testing done
I confirmed that the `cypress-tests` job still runs as expected. After this branch is merged, I'll try submitting a no-code PR to confirm that this fix works and that the PR can be merged.

---

I'm waiting for Platform Release Tools to approve the PR.

**Comment by holdenhinkle** [comment]
^PR was merged.

Testing merging a no-code PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/21686

**Comment by holdenhinkle** [comment]
Before (can't merge)
https://github.com/department-of-veterans-affairs/vets-website/pull/21684 
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/af1185e1-210a-4007-a8a1-0a2e409fb44e)

Now (can merge)
https://github.com/department-of-veterans-affairs/vets-website/pull/21686
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/079c6ce7-e9d8-4ee1-a13d-1d5550e12e81)

This is complete.

**Comment by holdenhinkle** [comment]
There wasn't a need to merge that PR to test that this was fixed. I closed the PR and deleted the branch.

**Comment by pjhill** [comment]
Excellent solution, thanks for completing this!
