### ISSUE TITLE
Write query to build data set

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43245]
## User Story
As a Governance team member, I want to write a query that will return the desired data so that it can be used to populate our data set.

Assignee:
Peer Reviewer:

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] _Placeholder task_

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Iniative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [ ] When brought into a sprint, move to the Planned pipeline.
- [ ] When brought into a sprint, add assignee and specify Peer Reviewer.
