### ISSUE TITLE
Cloud Isolation - Enabling upstream requests

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43240]
## Problem Statement 
Because the Lighthouse API Gateway (Apigee) will eventually be hosted by another cloud provider, we need a comprehensive strategy for routing vets-api requests that make subsequent external calls. 

How might we reroute upstream requests in a way that does not disrupt either the Lighthouse migration timeline or a Platform team's ability to use the new vets-api subdomain(s)?

## Hypothesis or Bet
We need to interrogate and potentially change any configuration settings that uses the api.va.gov hostname to ensure that all routes continue to work.

## We will know we're done when... ("Definition of Done")
- [x] The inventory of settings and routes that use the api.va.gov hostname have been investigated, updated. and tested.
- [x] Working example of an application that uses vets-api with Lighthouse as an upstream dependency, e.g., Facilities API. 

## Known Blockers/Dependencies 
NA

## Projected Launch Date
August 30, 2022 (Sprint 25/86)

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. **NA**
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching **NA**
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD **NA**

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide) **NA**
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0) **NA**
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool **NA**
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings) **NA**

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. **NA**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). **NA**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch.  **NA**

### Documentation
* **`PRODUCT_NAME`**: Cloud Isolation Team
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525
* **User Guide**:  [Spreadsheet of updated settings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/52a7afdd00f396d1727aed4869382f963d348531/platform/engineering/infrastructure/vets_api_upstream_settings.xlsx)

### Testing

* **Usability test**: NA
* **Manual QA**: NA
* **Automated tests**: [Datadog Tests](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3Acit%22%29)

### Measurement

* **Success metrics**: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
* **Release plan**: NA

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by alwerner** [comment]
@mchelen-gov Status update: Started

We need you to add this to the Digital-Experience-Product board.

**Comment by alwerner** [comment]
@mchelen-gov Status update: Complete
