### ISSUE TITLE
Domo training

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43244]
## User Story
As a Governance team member, I want to learn about Domo so that I can understand how to navigate the tool.
As a Governance team member, I want to learn about Domo so that am familiar with the tools capabilities. 
As a Governance team member, I want to learn about Big Query so that I can understand how it interfaces and connects with Domo.
As a Governance team member, I want to review the Analytics & Insights guidance and documentation on Domo and BigQuery so that I am following the Platform recommendations.

Assignee: full team

## Description
With the team reorg in 2022, teams needed to have all the necessary skills within their team and request support as needed from other teams.
Sarah started work on DOMO in ticket #34739 creating a "Total Issues by Product" dashboard within DOMO. 
We anticipate using DOMO for our automated health metrics to support 2022 Q3 Objective 3 - Implement Health Metric Dashboards for the Overall Platform and Platform Teams.
This ticket is to learn more about DOMO as a team to allow us to create cards and understand future capabilities of DOMO for future enhancements.

## Tasks
- [x] All Team Members have reviewed the [Platform Health Metrics: Domo Training](https://docs.google.com/presentation/d/1by4IPQlU6f1HR2OieyEXZ2tyoS5W72Vwx_7qPbVAb7Y/edit#slide=id.p) deck and the [training session recording](https://drive.google.com/file/d/1I3hR5MSXuqyto9Ml-Wn13ud1CmKQlLAA/view):
  - [x] Shira
  - [x] Allison
  - [x] Brian
  - [x] Cheryl
  - [ ] ~~Clayton~~
  - [x] Jim
  - [ ] ~~Sean~~
- [x] All team members have [access to DOMO](https://vfs.atlassian.net/wiki/spaces/AT/pages/1543602218/Creating+dashboards+in+Domo#1.-Getting-edit-access-to-Domo-%26-BigQuery)
  - [x] Shira
  - [x] Allison
  - [x] Brian
  - [x] Cheryl
  - [ ] ~~Clayton~~
  - [ ] Jim
  - [ ] ~~Sean~~

## Acceptance Criteria
- [x] Governance team members have access to Domo
- [x] Governance team members have reviewed all training materials

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
FYI I changed the 2nd task to "All teams have access to DOMO" and removed Big Query. You do not need access to BigQuery at this time.

**Comment by CherylEvans** [comment]
@shiragoodman Understood!
