### ISSUE TITLE
Define Collaboration Cycle Request data set

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43246]
## User Story
As a Governance team member, I want to know and understand the attributes of the desired data to be analyzed so that I can get help from Analytics & Insights team to write a query and build the data set.

Assignee: @shiragoodman 
Peer Reviewer: @briandeconinck 

## Description
The first step in building a Domo dashboard is to import data from our source. Since the data for our dashboard is in GitHub, Analytics & Insights has recommended that we utilize BigQuery to extract the data and then import the data to Domo using the Domo Connectors. There are challenges to this, so Analytics & Insights has offered to help and requested that we submit a ticket using the [Analytics Internal - New Dataset Request Template.
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template)

The metric we want to measure using the defined data set is : ***Median length of time it takes a VFS team to move through Collaboration Cycle (kickoff to post-staging)**

The data set should be the Collaboration Cycle Request tickets. All Collaboration Cycle Request tickets should have the following labels:

-  `CC-Request`
- `collab-cycle-review`
- `collaboration-cycle`

## Tasks
- [x] Review the[ How to request a new dataset](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215576075/How+to+request+a+new+dataset) page in Confluence. 
- [x] Submit the [Analytics Internal - New Dataset Request Template.
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template) 
   - [x] Provide the Basic information
   - [x] Provide the data requirements
- [ ] Answer any questions that the A&I team may have
- [ ] Confirm data set is accurate

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] Collaboration Cycle Request data set is available in Domo

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
Closing this ticket. It was determined on 9/8 that we will be unable to calculate the proposed metric with GitHub data, and will need manual input. The governance team has decided to put this data set on hold, and instead, focus on building a dashboard using the existing data set of Staging Review issue tickets.
