### ISSUE TITLE
Offboarding of Sarah Koomson from Governance Team to Design System Team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43264]
## Description
Sarah Koomson will be transitioning from the Platform Governance Team to the Platform Design System team. This ticket is a list of tasks that need to be completed for the transition.

## Tasks
- [ ] Sarah has been removed from the #platform-governance-team Slack channel
- [x] [Governance team Confluence page](https://vfs.atlassian.net/wiki/spaces/PPST/overview) has been updated to remove Sarah
- [x] [Design System team Confluence page](https://vfs.atlassian.net/wiki/spaces/DST/overview) has been updated to remove "(part time)"
- [x] Platform Website/Collaboration Cycle/Contact Us page has been updated to remove Sarah
- [x] Platform Orientation - General Orientation deck has been updated to remove Sarah
- [ ] Ticket for Backup document responsibilities for Accessibility Reviews & Brian has been created
  - Shira discussed with Martha and consensus is to have VFS Accessibility specialist support (if they have one)
- [ ] Sarah has been removed from the following team meetings:
   - [x] Standup
   - [x] Refinement
   - [x] Planning
   - [x] Creation
   - [x] Retro
   - [x] Weekly Initiative Meeting
   - [x] Office Hours
- [x] Sarah has been removed from the following distribution lists:
   - [x] Design Intent DL
   - [x] Midpoint Review DL
   - [x] Staging Review DL 
- [ ] Initiative and tech-debt tickets assigned to Sarah have been closed or transferred
  - [ ] Check for any open PRs/documentation drafts
- [x] Sarah has been removed from [GitHub platform-governance-team](https://github.com/orgs/department-of-veterans-affairs/teams/platform-governance-team)

## Acceptance Criteria
- [ ] Sarah has no outstanding tasks on Governance Team
- [ ] Sarah is able to fully support Design System Team

## How to prepare this issue
- [ ] Attach story to appropriate Iniative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [ ] When brought into a sprint, move to the Planned pipeline.
- [ ] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
@shiragoodman I added that after our 1:1 this morning about creating a "Who will be a backup and instructions" document for when Brian is out of office. I left it vague due to the ongoing discussion whether Sarah will cover all reviews or not.

**Comment by shiragoodman** [comment]
@chaseakirby thank you! I talked to @artsymartha68 about this yesterday and she agreed that it would be best to get the VFS teams accessibility specialist (if they have one) to help. I have it on my to-do list to create a ticket for handling this.

**Comment by shiragoodman** [comment]
@chaseakirby can you complete the items above that you own (ie meetings)? thanks!

**Comment by chaseakirby** [comment]
@shiragoodman I removed Sarah from most of the meetings but I think that you still own Sprint Creation (it must have been one we missed transferring or intentionally kept yours).
I also updated our Confluence space and Platform Website.

**Comment by shiragoodman** [comment]
Sarah has been removed from Sprint Creation meeting. I will follow through on the remaining actions. Thanks!
