### ISSUE TITLE
CST Notifications Technical Discovery Kick-off

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43267]
## Value Statement
**_As a_** product manager
**_I want to_** understand what it would take to develop a notifications feature
**_So that_**  I can determine whether pursuing the value it would create would be worth the cost.

---
## Background Context
Purpose described in associated epic

## Acceptance Criteria
- [ ] _Answer open questions we have for VANotify team_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- What exactly is the infrastructure our team would need to build specifically? 
- Where does our work end and VANotify's work begin? 
- How would we segment send lists by criteria? 
- What criteria could we use to create a segment to get claim status notification? 
- Does this work need to go through the collaboration cycle? 
- What is the level of effort required? 
- What could be accomplished in a single sprint? 

## Tasks
- [ ] _Arrange meeting with VANotify_
- [ ] _Frame goals for VANotify_
- [ ] _Consolidate list of open questions and add to this ticket_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
