### ISSUE TITLE
[Research] Onsite Notifications: Create UAT research plan and convo guide

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43277]
## Background
We need to prepare UAT research documents for the Onsite Notifications initiative. For this we will recruit internal veterans and staff with disabilities. We will not use Perigean for recruiting because of complications and/or confusion that could occur from initiating a debt notification for the general public.

## Tasks
- [x] Create UAT research plan
- [x] Create UAT conversation guide
- [x] Touch base with VA Notify team in biweekly sync meeting or async to discuss UAT plans

Note: there is a folder in GH already created for onsite notifications (MVP) UAT materials: [UAT folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications/mvp/UAT)

## Validation
- [x] Send links to team to let them review asynchronously
- [x] Have another designer review research plan and conversation guide

**Comment by Samara-Strauss** [comment]
These mostly look good to me, but we do need to make it clear to people **before** the UAT session that we are adding a debt notification to their account, but that this is just for testing purposes and they do not actually have any debts (that we know of). Given that we need to inform people of what we are doing before the session, this might make it so we can't really ask some of the usability questions like "Why do you think you might come to have this notification showing in your account?" because the reason the notification is showing in their account is for testing purposes and not actually because they have a new debt. Let me know if you want to talk about how this might change the script or how we frame things when recruiting.

**Comment by aagosto90** [comment]
Thank you for reviewing @Samara-Strauss ! Yes definitely agree when recruiting I'll make it clear to participants what we are testing and that it's not a real debt. I agree that given I have to explain all of that, the very hypothetical question you pointed out is probably not needed. I'll take that part out.

**Comment by ajakabcin** [comment]
Looks great! 👍
