### ISSUE TITLE
Add Observer process guidance for joining a research session

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#43287]
## User Story
As a researcher, I want clear guidance on how observers should enter the session so that research participants feel safe and empowered.
As a research participant, I want to understand the purpose of observers in research sessions so that I can give an informed response to observer related questions.

Assignee: @claytonzook 
Peer Reviewer: @jimuhh

## Description
Splitting this ticket from #41630 due to research being conducted to determine best practice for advising how observers enter sessions and advising the research participant(s).

We want to clarify that it's not just for research that requires heightened sensitivity and not just a consideration, but it's official guidance for researchers to hold observers in the waiting room for all research until AFTER the participant agrees to have additional folks join on the VA side.

See [this research-ops slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1652889118717619)

## Impacted Artifacts
- Platform Pages
   - [Observer guidelines > Attendee etiquette](https://vfs.atlassian.net/wiki/spaces/RD/pages/1622311177/Observer+guidelines)
   - [Moderator Guidance on Observers > Protocol for adding observers to a session ](https://vfs.atlassian.net/wiki/spaces/RD/pages/2244378625/Moderator+Guidance+on+Observers#Protocol-for-adding-observers-to-a-session)
   - [Research Safety page > Creating a safe space for participants > limit number of observers](https://vfs.atlassian.net/wiki/spaces/RD/pages/2143649793/Research+Safety+and+Emergency+Exit+Strategies#Creating-a-safe-space-for-participants)
- [convo guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
- [research findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2323448145/2022-+07+Observer+Protocol+Research+Combined+Findings)
- [Change announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2240151605/Draft+-+Change+announcement+for+Ticket+41630+on+Observer+Guidelines)

## Tasks
- [x] Conduct research to determine recommended approach
- [x] Get observer research back from researchers who included as part of a study
     - [x] Christina - [2022-06 Profile Bad Address Indicator (BAI) Usability Study](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/141)
     - [x] Liz - [2022-07 My VA Redirect UAT](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/144)
     - [x] Ben - [2022-08 Travel Reimbursement MVP Remote Usability Test for Patient Check In (PCI)](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/163)
     - [x] Angela - [2022-07 Benefit Payments and Debts Usability Study](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/160)
     ~- [ ] Patrick Onesty - 2022-06-24 MCT VHA Virtual Agent Research~
- [x] Draft [research findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2323448145/2022-+07+Observer+Protocol+Research+Combined+Findings)
- [x] Present to research ops group
  - [x] Receive approval to add guidance
- [x] Determine what changes/additions should be made to which pages/templates. List pages/templates below with proposed changes/additions per document.
  - [x] [Observer guidelines > Attendee etiquette](https://vfs.atlassian.net/wiki/spaces/RD/pages/1622311177/Observer+guidelines)
   - [x] [Moderator Guidance on Observers > Protocol for adding observers to a session ](https://vfs.atlassian.net/wiki/spaces/RD/pages/2244378625/Moderator+Guidance+on+Observers#Protocol-for-adding-observers-to-a-session)
   - [x] [Research Safety page > Creating a safe space for participants > limit number of observers](https://vfs.atlassian.net/wiki/spaces/RD/pages/2143649793/Research+Safety+and+Emergency+Exit+Strategies#Creating-a-safe-space-for-participants)
  - [x] [convo guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
      - update Intro section to include new observer protocol 
   - [x] [Change announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2240151605/Draft+-+Change+announcement+for+Ticket+41630+on+Observer+Guidelines) drafted
- [x] Changes have been communicated in #research Slack channel
- [x] Changes have been communicated in Design+ Monday meeting
- [x] Ask Perigean to default their Zoom accounts to have waiting room turned on

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Shane and/or Kevin have approved the proposed changes
- [x] Researchers should have clear guidance to provide to observers when joining a research session

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
@claytonzook Hey Clayton, I took a stab at pulling out the observer guidance from #41630. Please review and if it looks good then we can remove it from that ticket (just didn't want to lose anything)

**Comment by claytonzook** [comment]
@chaseakirby I think this largely covers it.

I think we'll also want updates on [the research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-5.Conductsessions) with this

I don't think these updates make sense for the current [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Observers). While the page name sounds like a good place for this, I have not figured out a good way to add to this to the content of this page the way it's currently structured. We can chat more this afternoon, but I think this page probably needs a larger rework before it can do what we need it to do.

**Comment by claytonzook** [comment]
@jimuhh This one is ready for review

**Comment by jimuhh** [comment]
Hi @claytonzook I'm looking for the artifacts I need to review but the links take me to archived Confluence pages. Could you point me to what I need to review? Thanks!

**Comment by claytonzook** [comment]
@jimuhh Sorry about that. All the relevant artifacts, with updated links, are in the Artifact section now. I also updated their links in the checklist section
