### ISSUE TITLE
Profile | BAI | Missing "saved" message 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43291]
## Background

During some early prod testing of the BAI, we noticed that if a user wants to "confirm" that their existing address is correct (which they would do by clicking on the edit button followed by the update button), we do not display the "Update saved" message. 

This also applies to all of the editable fields on the Contact Information page: mailing address, home address, work number, phone number and mobile number.

### User Story

As a user with a BAI alert
IF
I click the edit button on the Mailing address field
AND
do not make any changes to my address
THEN
I click the "update" button, I should see a success message "Update saved"

## Tasks
- [ ] Add tasks here that must be completed

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] Deploy to Staging behind feature flag
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production and re-test

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@adamwhitlock1 - mark is ok with you taking this :)

**Comment by adamwhitlock1** [comment]
I updated this and have merged the code. it is ready to validate. What is the process for getting a user in staging to actually have the BAI on their profile (not forcing it to appear via the feature flag)?

**Comment by SKasimow** [comment]
Confirmed: tested with user 5 and received the "Update saved" message
