### ISSUE TITLE
Draft github workflows section of playbook

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#43297]
## Story
As an engineer who wants to leverage recommended tools for CI/CD I would like guidance on how to use github workflows so that I can can automate my pipelines, therefor the guide should include resources on getting started with this. 

## Acceptance Criteria 
- [x] Link to useful github documentation about how to use workflows.
- [x] Describe different tasks that can be accomplished with github workflows (running tests, building projects, etc)
- [x] Give example workflows.

**Comment by ewilson-adhoc** [comment]
Closing as finished.
