### ISSUE TITLE
Profile | Sprint 78 (July 13 - July 26)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43296]
## PTO/OOO/Unavailable

- **Christina**: 
- **Sharon**:  
- **Tom**: 
- **Samara**: 7/18
- **Adam**: 
- **Liz**:  7/21, and 1/2 day on 7/25 and 7/26.

## Sprint Priorities
- Bad address indicator: Research summary and design updates
- Documentation: Contact info and Military info
- Forms system updates: Discovery and scoping
- Military info: UAT and start launch (pending VA Profile being ready)

## Notes:
- New sign-in flow may impact sprint - tbd.

### FE - Adam
- [x] #43482 Remove FF 

### Design - Christina
- [ ] #43713 Update sketch files (carry over to sprint 79)

### BE - Tom
- [x] #44082 Discovery re limitations and LOE for Preferred name (UAT issue).

### BE - Tom
- [x] #43582 eMIS deprecation

### PM - Sharon
- [x] #42968  Analytics to check for successful/failed retrievals of military info 

### FE - Adam
- [x] #44075 FE GA tags

### BE - Tom
- [x] #44232 Documentation

### PM - Sharon
- [ ] #42706 Con't prep for staging review cycle work (release plan, QA etc)
- [ ] #42265 Analytics (carry over to sprint 79)
- [x] #43388 QA Use Cases

### FE - Adam
- [x] #44310

### Design - Christina

- [x] #42965 Research sessions
- [ ] #43384 Full research report (carry-over)
- [x] #43439 User flow doc
- [x] #43383 Topline summary

### FE - Adam
- [ ] #43727 Phone number field (carry-over to Sprint 79)

## Change Address Messaging Prompt
- [x] #44230 Analytics Bug/Turn off FF toggle at 50%
- [x] #44380 Analytics ticket for custom event

### BE - Tom
- [x] #44193 Sign on issues
- [x] #44249 Test BGS prod access

### FE - Adam
Stretch goal:
- [x] #42734 dd routing number/invalid error message 

### Design - Liz
- [x] #43750 Contact documentation

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - I need to catch up with the folks that were ooto today but wanted to share this draft for Sprint 78. Please lmk if you have any questions or feedback.
