### ISSUE TITLE
[FE, PM] Onsite Notifications: Launch onsite notifications to 50% of users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43293]
## Background
Following successful completion of https://github.com/department-of-veterans-affairs/va.gov-team/issues/43288 we'll continue with the phased launch of the Notification Preferences feature, moving to 50% of users.

## Tasks
- [x] Flip feature flag to launch for 50% of users
- [x] Monitor analytics post launch

## Acceptance Criteria
- [ ] Onsite Notifications is live for 50% of users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Analytics, and screenshot of feature flipper showing 50%

**Comment by tmitchellgcio** [comment]
Set to 50% as of about 1130am today
