### ISSUE TITLE
[FE] Onsite Notifications: Clean up any code post 100% launch

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43301]
## Background
Once onsite notifications has been successfully launched to 100% of users we want to go back and review the code to determine if there is any tech debt that needs to be addressed.

## Tasks
- [x] Remove feature flipper flag
- [x] Review to determine what code may need to be cleaned up
- [x] Implement adjustments to code based on what was found in the review

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Ensure feature still works as expected post clean up

**Comment by tmitchellgcio** [comment]
Looks like it just needs some testing and flag cleanup. PR soon

**Comment by tmitchellgcio** [comment]
@ajakabcin not really anything to validate here as long as tests are passing and it's merged which it is. Tests were adjusted to no longer account for the feature flag so with your approval this can be closed

**Comment by ajakabcin** [comment]
Awesome - thank you @tmitchellgcio - closing
