### ISSUE TITLE
[FE, PM] Onsite Notifications: Launch Onsite Notifications to 100% of users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43300]
## Background
Following successful completion of https://github.com/department-of-veterans-affairs/va.gov-team/issues/43293 we'll continue with the phased launch of the Notification Preferences feature, moving to 100% of users

## Tasks
- [x] Turn feature flipper on for 100% of users
- [x] PM update release plan and documentation with launch details
- [x] Monitor analytics post launch

## Acceptance Criteria
- [ ] Onsite Notifications is live for 100% of users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ monitor analytics post launch and verify with Prod users. Provide screenshot of feature flipper being set to 100%

**Comment by ajakabcin** [comment]
Release plan and project outline updated with launch dates and key dates, respectively
