### ISSUE TITLE
Adds OAuth errors in the FE

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#43310]
## Issue Description
Add the error codes for OAuth related errors on the FE and update the AuthApp

## Tasks
- [x] Create a lookup table of the possible OAuth errors
- [x] Create documentation as necessary for the errors as documented in this ticket #42478
- [x] Update AuthApp to create errors as necessary depending on string lookup
- [x] Add the Request ID to the AuthApp page (

## Acceptance Criteria
- [x] Stuff is good
