### ISSUE TITLE
[Research] My VA Audit UX Improvements: Create Preliminary Research Plan

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43319]
## Background
We need to create a plan for conducting user research for our My VA Audit initiative. This does not have to be a formal research plan like we typically do since we will be rolling out the audit improvements in phases, however this can be a preliminary research plan to decide how we will conduct research later in the process. 

Some things to consider include: 
- Do we need to test in code? 
- If so, how do we plan on doing this (prod, code-pen or equivalent, staging)? 
- Make sure the method serves our objectives. We can include these thoughts in our formal research plan when we are ready.

## Tasks
- [ ] Create preliminary research plan draft
- [ ] Discuss ideas for testing and capabilities with team (30 min meeting)

## Acceptance Criteria
- [ ] Draft of research plan exists in GH
