### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 7/4

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43329]
## Issue Description
We need to swap out the videos in the stories section of the CLP to these 2 Veterans:

**Robert Bonner:** https://www.youtube.com/watch?v=wMVj5kYn8ps
**Ronald Pipkins:** https://www.youtube.com/watch?v=jpykh5DMZb8

**Drupal Page:** Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Documentation for how to swap videos:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [x] Replace text and videos
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you/saved as a draft! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
I published these changes and created a new ticket for next time. Moving to validate and will close once these are live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
