### ISSUE TITLE
GA4 - Implementation Wrap Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43326]
## Problem Statement 
Google will be sunsetting Universal/360 Analytics in October 2023 and will discontinue any tracking and historical data management at that time.  Their new tool Google Analytics 4 (GA4) will replace their current product and will change how events and parameters work on Google Analytics. We need to understand what changes we will need to implement in order to keep up with accurately reporting user metrics and keeping VFS teams informed of any analytics changes that may occur.

How might we integrate Google's latest Google Analytics4/Google Tag Manager updates safely and accurately?

## Hypothesis or Bet
If we research and implement Google Analytics 4 updates, then we can get more scalable GA data to VFS teams.

## We will know we're done when... ("Definition of Done")
We have migrated from Google UA/360 are actively utilizing GA4 to all data tracking, tagging and reporting.

## Known Blockers/Dependencies

- Translating/updating custom GTM tags

## Projected Launch Date
October 2023

## Launch Checklist
- [ ] GA4 updates have been tested in staging
- [ ] GA4 has been updated in Prod 
- [ ] KPI dashboards and monthly reports reflect updated GA4 data
- [ ] Internal GTM/GA documentation is updated
- [ ] Platform Website GTM/GA documentation is updated
- [ ] Updates have been announced to VFS teams

 ### Is this service / tool / feature...

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: [GA4 Discovery - WIP](https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/WIP+-+GA4+discovery)
* **Product Outline**: [GTM Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1905066142/Google+Tag+Manager+product+outline)  _- Needs to be updated based on this work_
* **User Guide**: [GA and GTM User Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-and-Google-Tag-Manager.1857978529.html#GoogleAnalyticsandGoogleTagManager-GoogleTagManager) _- Needs to be updated based on this work_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement
* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)
