### ISSUE TITLE
[PM] My VA: Documentation Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43320]
## Background
To improve our documentation for My VA we want to review existing documentation and make updates as necessary. Samara provided thoughts [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40862#issuecomment-1128093147) on how we can improve our current documentation.

## Tasks
- [x] Review current documentation, note any areas that need updating
- [x] Determine standards/how we want our documentation to be moving forward
- [x] Share documentation standards with team

**Comment by ericasauv09** [comment]
what should our documentation be/look like? vs. What do we actually have today?
