### ISSUE TITLE
[PM] Profile 2.0: Handoff project to Tressa

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4332]
## User Story:
As a new member of the team, I need to be onboarded to the project I will be working on so I have the relevant background and know how to get started.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] 1:1 Knowledge transfer with Tressa  (1 hour)
- [x] Hand off Sketch files

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [x] Samara and Tressa regroup to discuss this work
- [x] Tressa has what she needs to start ramping up on this work
