### ISSUE TITLE
Sprint 11 Objectives - 12/18 - 12/31  (Christmas Holiday)

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4333]
### Time off this sprint

*Sprint is 8 days with 12/24 and 12/25 holiday*

- Arthur: Dec 19, 23 – 26; 6 days of availability
- Brad: Dec 18, 24, 25,31; 6 days of availability
- Erik: Dec 23 – 25; 7 days of availability
- Justin: Dec 24 – 27; 6 days of availability
- Lihan: 24 – 31; 4 days of availability
- Samara: Dec 23 – Dec 27; 5 days of availability
- Tressa No time off; 24th-27th 6 days of availability 

### [Sprint Capacity Planning Excel](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/Capacity%20Planning%20-%20Sprint%2011.xlsx)

Talk with team about  - either canceling grooming altogether or move to Dec 23. Also, Sprint planning for Sprint 12 should be moved to Jan 2.

### Sprint order of priorities

1. Get address validation ready for QA
2. Direct deposit updates
3. Create a plan for APO/FPO/DPO build + ticket writing

### Direct Deposit

**Erik**

- [x]  Ramp up to 100% #3969
- [x] FE for routing number error #4109
- [x] Remove direct deposit feature flag #2009

### Address validation

To the best of our ability, this sprint's objective is to make sure all existing bugs are fixed/updates are implemented and ready for QA. **Note**: Having the feature fully ready for QA depends on VA Profile fixing some issues on their end. We can not be ready for QA without them. We'll consider the objective met here if things remain open only as a result of the VA Profile dependency.

- [ ]  Use only candidate api for address validation api #4060
- [x] Address validation: Continue, Cancel, and X buttons are broken #4205
- [x] Address validation: Copy is missing a period #4211
- [x]  Validation Keys do not work to override addresses in the profile #4245
- [x]  Do not show the user any suggestions that are not "CONFIRMED" as deliverable #4250
- [x] The address validation modal remembers the last option you selected between opens and closes #4264
- [x] User should see the address they entered when going back to edit their address #4271
- [ ] Sometimes we get validation keys but can't force the addresses through #4278
- [x] Review the flow for Address Validation Modal #4283
- [x] 1st attempt to force an overridable address works, 2nd+ fail #4327
- [x] In some cases picking a suggested address from the API will not work. #4328
- [x] In some cases address updates fail because we make a POST call instead of a PUT #4246
- [x] Address selection radio button isn't visible #4373
 
### APO/FPO/DPO 

**Arthur and Justin**

- [x] Ticket creation for application updates #4374
  - Figure out how to organize tickets for benefit teams in a clear way.
  - Create and assign tickets to Benefit and Memorials teams 1 & 2 for the recommended application updates.

Brad 

- [x] FE profile update #4386

### Onboarding Tressa

**Tressa**

- [x] General Onboarding #4086

**Samara**

- [x] Team intro
- [x]  Handoff of Profile 2.0 #4332

## Sprint 10 Retro 
![Screen Shot 2020-01-02 at 9.57.35 AM.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/8aeef806-9fd8-4220-a755-9a27e1121a79)
