### ISSUE TITLE
[Epic] My VA Payment Info MVP

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43337]
## Product Outline
MVP of the benefit payments & debts section (commonly referred to as the "payment info section") creates a section on My VA for Veterans to see information about recently received payments from or debts owed to the VA.

[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#feature-payment-and-debt-info-on-the-my-va-dashboard)

## Collab Cycle:
- [x] Collab Cycle kickoff #33468 
- [x] Design Intent #33477 
- [x] Sitewide Content & IA intake request #34015, #38181
- [x] Research Review - [#64 My VA Payment Information usability](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/64)
- [x] Analytics Request #37589, #38739
- [x] Midpoint Review #34549
- [x] Staging Review #38376, #35149
- [x] Privacy, Security, Infrastructure Readiness Review [**#434 Privacy, Security, Infrastructure readiness review**](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/434)

**Comment by Samara-Strauss** [comment]
Can we close this @ajakabcin?
