### ISSUE TITLE
[Product] CST: Now, Then, Later Roadmap 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43342]
## Value Statement
**_As a_** product manager
**_I want to_** keep stakeholders aware of what we're focusing on to meet our objectives through CST
**_So that_**  expectations are managed and they can support our mutual goals. 

## Acceptance Criteria
- [ ] _Reviewed by squad_
- [ ] _Reviewed and approved by Matt Self_

## Designs and Build Notes
- Add here

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
