### ISSUE TITLE
[Platform Collaboration] Clarify roles and responsibilities for DevOps resources on platform teams 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#43347]
## Description
The Platform Infrastructure team believes that DevOps resources on other teams should have the responsibility to build and deploy infrastructure components that they will own and maintain. It seems that this expectation has not yet been documented and communicated clearly. There is a need to have this expectation clarified across platform teams. The Platform's ability to manage infrastructure effectively is dependent on it. 

## Background/context 

- There has been some discussion about forming a working group or community of practice to better engage DevOps resources across platform crew teams 
- Part of the platform re-org was to create cross-functional teams that include DevOps resources
- The goal of cross-functional teams is that they can work effectively/independently
- DevOps resources on other platform teams should have the ability and responsibility of managing infrastructure resources that are specific to their team
- Mike Chelen thinks this would be good to discuss this at a leadership level 

---
## Tasks
- [x] Discuss at a leadership level and determine the next steps 

## Acceptance Criteria 
- [x] An issue is created to allow DevOps resources on other teams to have the permission to manage the resources that their team owns
- [x] There is a follow-up issue to establish a venue for working with the Platform Infrastructure team to improve DevOps tools and capabilities

**Comment by little-oddball** [comment]
Definitely would be great to discuss. Additionally, would be good to get some specific instances for context.

**Comment by jhouse-solvd** [comment]
Based on some feedback from a recent conversation: 

It's possible that "own and maintain" may not apply to some teams, _e.g. Platform Security._ There are services or features - _that may be required as a part of ATO compliance, or that may be recommended based on other guidelines_ - that they do not intend to build or maintain. 

Some services or features that the Platform Security team recommends could end up being owned by another team; either one that currently exists or has yet to be formed. 

In this case...

- Is the Platform Infrastructure team intended to assume responsibility for DevOps-related tasks? 
- Is the Platform Infrastructure team expected to be the default and/or primary resource for teams that do not have a DevOps resource?

This would be good to add to the leadership conversation. :)

**Comment by little-oddball** [comment]
Good stuff, thank you for adding! IMO, those help a lot and are good conversation items.

**Comment by jhouse-solvd** [comment]
Part of the implementation of this is happening in #45254

**Comment by jhouse-solvd** [comment]
This ticket can be closed. Please see the follow-up issues in my previous comment.
