### ISSUE TITLE
[CDP] Both Zero alert message showing when one endpoint errors and the other has zero balance

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#43340]
## Issue Description
While on user 80, the debt card should show an empty state. However, it’s currently showing a 404 alert
Should be showing one error message and one empty state message, instead showing both are zero. 

---
## Tasks
- [ ] Adjust error message logic for one error and one zero balance alert

## Acceptance Criteria
- [ ] Alerts are correctly rendering
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
