### ISSUE TITLE
Example application(s) with Lighthouse dependency 

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43341]
## Product Outline
[CIT Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)

## High Level User Story/ies
As a developer on a team that uses vets-api to make upstream Lighthouse requests, I need a working, reference example of an application that makes a request to vets-api, and which also has an upstream dependency on Lighthouse, so that I have a clear understanding of the implementation of the new *platform-api.api.gov and forward proxy port routes.

## Hypothesis or Bet
By providing an illustrative example(s), development teams can use it as the basis for changing vets-api to implement route updates in their applications.

## OKR
The routing of upstream Lighthouse requests has been enabled for handoff for use in all environments.

## Definition of done
- [x] Guide for vets-api requests with Lighthouse as an upstream dependency – in all environments (dev, staging, sandbox, and production.)

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by alwerner** [comment]
Guide: https://docs.google.com/spreadsheets/d/111t6f4V3eCVkaKoBIxXi54_HlkPT-54qKShfRjl-iMs/edit?usp=sharing

**Comment by alwerner** [comment]
Closing this as complete. All known settings have been updated per: https://docs.google.com/spreadsheets/d/111t6f4V3eCVkaKoBIxXi54_HlkPT-54qKShfRjl-iMs/edit?usp=sharing. Exception: Identity callbacks will occur closer to the future release. See:  https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/46
