### ISSUE TITLE
File upload page is out of date with VA design system guidance

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#43349]
## What happened?
The file upload page does not follow [VA design system guidance for file uploads](https://design.va.gov/patterns/forms/file-upload) including:
- Having a descriptive title e.g. "Upload your death certificate" instead of "Document upload"
- Directions on how to upload a file
- Focus management 

<img width="782" alt="Screen Shot 2022-06-24 at 12 34 36 PM" src="https://user-images.githubusercontent.com/14154792/175586852-495ad53d-dffb-4537-bc1b-6e0699e31839.png">

<img width="609" alt="Screen Shot 2022-06-24 at 12 49 06 PM" src="https://user-images.githubusercontent.com/14154792/175605489-9254b907-2a73-49d9-8fc6-e55647579c39.png">

### Focus management on iphone VoiceOver
Post upload, focus is lost. There also appears to be an error where the upload box becomes no longer reachable.
- :30, the file is uploaded, but no aural update is provided to the user; someone could wait endlessly trying to figure out if something was actually uploaded
- :34, the file is uploaded, but the user can't actually access it for a bit; unsure why this issue exists (see :42 for more). I tried to reach it via right swipe and down swipe (form controls), and it eventually worked I think on a right swipe (line by line). It occurred again the second time I attempted an upload.

https://user-images.githubusercontent.com/14154792/175956643-2fd1158d-db24-4c8f-a4a0-b8700237c616.MP4

I recommend further testing with @AngelaFowler82 

## Steps to Reproduce
- URL: https://staging.va.gov/burials-and-memorials/application/530/documents
- Test User _(if applicable)_:

## Desired behavior
- File upload page should follow VA design system guidance
- We should consider splitting up the two file uploads into two separate pages (as opposed to one)

## Acceptance Criteria
- [x] File upload page follows VA design system guidance
- [ ] Focus is managed through all file upload interactions
- [ ] A QA review has been done on the page to stress test undesirable uploads/scenarios

**Comment by joshkimux** [comment]
Note here, @AngelaFowler82 confirmed the focus issue as well where the file is no longer discoverable by swiping on VoiceOver iOS post upload

**Comment by fiorella-io** [comment]
With the new Burial redesign, we've fixed this issue. Upload will appear on a single page, so we've split it as suggested. I've checked off the first item in the acceptance criteria section. The other two are technical asks. 

Designs:
- [Death certificate](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/el8bx3W)
- [DD2014](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/OeW2Mwq)
- [Transportation](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/DE8VWA2)
- [Additional evidence](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/AZVYgmM)
