### ISSUE TITLE
Consider changes to survey delivery method

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43348]
## Issue Description
Consider survey delivery method.  Should this change? How?

-Do we have any examples we can share with folks about an improvement made possible as a result of their comments?
-How can we recruit those that have 'power' to help influence participation (Leadership, OCTO-DE, etc)
-Would more direct appeals or appeals to team leaders --> team members drive engagement?
-is it time for a chatbot / SMS?

(there may be an earlier mural with some of these ideas)

-Should we also consider an alternate way to gather feedback? For instance, if I have an issue, I'd prefer the ability to speak to it when I encounter it. But it may not feel big enough to be a "feature". perhaps there can be somewhere I can submit some pain point or frustration with complete anonymity
Probably would need to be located on the Platform documentation site

-Also, can we combine advantages of anonymity with upsides of clarity:  a la anonymous submissions, but a dropdown that lets you identify your role???

## Goal
We'd like to garner more responses and greater diversity of feedback so that we can provide better stats. How might we alter the delivery and recruitment of the survey?

## Tasks
Ideas added to the [brainstorming Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1670425982791/73444dea1fcc7259fffe0ba33eaa44fd9e573a9b?sender=u311209e67c8c21a1b37a8167):
- [x] Taylor  
- [x] Dan  
- [x] Bryan 
- [x] Nicole   
- [x] Team Discussion 1 - review options as a team
- [x] Team Discussion 2 - review options as a team

Prioritize ideas:
- [x] Taylor  
- [x] Dan  
- [x] Bryan 
- [x] Nicole   

## Acceptance Criteria
- [x] decisions are [documented](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2463760385/Customer+Insight+Survey+Delivery+Method+workshop+results)

**Comment by steel36** [comment]
Added ticket 47564's idea to this ticket since they converge.
