### ISSUE TITLE
Discovery ticket- DLC endpoints

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4335]
## User Story:
As a Back-end, I need so that I can.

## Tasks

- [ ] create endpoints
- [ ] provided DLC with schema and URL, and URL format
- [ ] set up meeting with DLC, Joe, Amen, Maherial- (nick)

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Front-end approves enpoints
- [ ]
