### ISSUE TITLE
[VA Notify Team Inquiry] 21P-530 Confirmation of submission success and other questions

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#43353]
## Value Statement
**_As a_** VA Notify product manager
**_I want to_** understand status changes for successful 21P-530 application submissions
**_So that_** I can assess how to implement email confirmation notification functionality. 

---
## Background Context
VA Notify Strike team is working on adding email confirmation notifications to Veterans when they have submitted their applications. Matt mentioned 21P-530 might be another good candidate. We have a few questions for you and your team.

## Open questions
- Our team took a dive into that form and wanted to verify if we have the right status change for successful submissions. Should the trigger be placed in app/controllers/v0/burial_claims_controller.rb after the claim is successfully saved? This controller is called once the user submits the 21P-530 form. We also have an instance of the User at this point and if the claim is not saved successfully we don't need to send the confirmation email.
- Is there a current notification being sent?
- Is there specific messaging we need to include in the email?
- Were should the user be sent to check the status of their application?

## Tasks
- [ ] _Assign to a backend developer for review_
- [ ] _Send an update to Megan Siddle, product manager for the VA Notify team_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megansiddle** [comment]
Hi @saderagsdale! We wanted to start looking into the next form. These are our questions for the 21P-530 form.
