### ISSUE TITLE
Front-end DLC end points

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4336]
## User Story:
As a ___Front-end developer_______, I need _to have access to DLC endpoints_________ so that I can ___retrieve veterans data (socks or hearing aid item)_______.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Determine if the environment is correctly set up
- [x] Confirm end points match DLC & Vets-API

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Get request is completed without errors. 
- [ ] Post request will update DLC's data

## Next Steps
- Build the table using DLC's veteran data

## Blockers
- DLC end point needs to be established

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
