### ISSUE TITLE
Cloud Isolation - Release Plan Documentation

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43374]
## Problem Statement 
In preparation for the eventual migration of the new Lighthouse API Gateway (Apigee) to GCP, the CIT is creating new pathways for vets-api requests, including new *platform-api.va.gov subdomains for vets-api requests and new forward proxy ports for routing vets-api requests with upstream Lighthouse dependencies.

How might we ease the path for teams that use vets-api endpoints to transition to using the new *platform-api.va.gov subdomains and the new forward proxy port?

## Hypothesis or Bet
Hand off of Release Plan documentation which can educate teams on how to deploy the new platform-api.va.gov hostname.

## We will know we're done when... ("Definition of Done")
Operational documentation has been added to Confluence:
- [x] Specifications on platform-api subdomains.
- [x] Guide for using platform-api subdomains to route to vets-api.
- [x] Guide for vets-api routing with upstream Lighthouse requests.
- [x] Diagrammatic flows for new routes.
- [x] Submit and present RFC to AWG. 

## Known Blockers/Dependencies 
NA

## Projected Launch Date
August 30, 2022

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. **NA. No user-facing features.**
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching **NA**
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD **NA**

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide). **NA. May be required in Q4 or later**
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0) **NA**
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [x] Internal-facing: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool. **NA**
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings) **NA**

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it. **NA. No measurable artifacts.**
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose). **NA**

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. **NA**

### Documentation
* **`PRODUCT_NAME`**: Cloud Isolation Team
* **Product Outline**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525
* **User Guide**: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2244083715/Operational+Documentation

### Testing

* **Usability test**: NA
* **Manual QA**: NA
* **Automated tests**: NA

### Measurement

* **Success metrics**: See [Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)
* **Release plan**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/52a7afdd00f396d1727aed4869382f963d348531/platform/engineering/infrastructure/hostname_transition_plan.md

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [x] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by alwerner** [comment]
@mchelen-gov Status update: Started

We need you to add this to the Digital-Experience-Product board.

**Comment by alwerner** [comment]
@madebydna Changed this to "Release Plan Documentation".

**Comment by alwerner** [comment]
@mchelen-gov Status update: Complete
