### ISSUE TITLE
[Design] My VA Payment Info: Revisit Design

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43376]
## Background
Based on our extensive feedback during the midpoint review we have decided to revisit the design of the Payment Info version 2. The feedback was documented [here](https://docs.google.com/spreadsheets/d/1Gm6ikUEJyrf2W_CPDzW7SEht-Uovz0D71mixtOsKhZY/edit#gid=0). Once we have redesigned we can proceed with the rest of the Collab Cycle.

## Tasks
- [ ] Revisit Payment Info v2 design
- [ ] Make any necessary updates
- [ ] Review with team

**Comment by aagosto90** [comment]
@ajakabcin @ericasauv09 @Samara-Strauss @tmitchellgcio (optional) @andaleliz 
Hey all! I thought we might be able to do this as an async touchbase on Github instead of gathering us all in another meeting (but I will do that if necessary) as people are out on random days this week.

I met with Danielle today and she really liked the idea of us separating out these two sections and naming them something clear and informal, especially if it can help avoid any confusion for veterans. What we settled on for now to test is "Debts that you owe VA" and "Payments we've made to you". We liked using "Debts" and "Payments" at the beginning of each title since that's formally what we refer to these things as, but to make it even more clear, we tack on the extra language so there would hopefully be as little confusion as possible about what the difference between the two is. She referenced language in [this link](https://www.va.gov/resources/va-debt-management/) in the "Why do I owe money to the VA?" accordion. The term "owe" is one she's been recommending to teams that could work for us here.

Let me know what you all think and whether we feel we're ready to take this to another midpoint review. Thank you!

 ![Screen Shot 2022-07-05 at 3.32.03 PM.png](https://images.zenhubusercontent.com/61f2dbbca50e2e3e2b4d0a11/f2f01b2d-6731-403c-9cdf-ef4bad22a5d6)

**Comment by andaleliz** [comment]
Hey Angela! I think this is a solid direction, to split them both out, and use this kind of verbiage. It's much clearer and I think will reduce the cognitive load people have to use to parse through payments and debts when they're mixed.

**Comment by Samara-Strauss** [comment]
Great work, and thank you for this! Agree with Liz's comments above. 

- Can we see what this looks like within the context of the whole page?
- Can you ask Danielle if "Payments VA has made to you" will work? I want it to be clear who "we" is, and it would also mirror "Debts you owe the VA".
- Assuming this is the design we take into research, I'd like us to evaluate whether we should combine debts and copays into one block, or whether people prefer them to be separate. We'll want to assess whether people understand the difference between debts and copays, and we'll especially want to make sure we have participants who receive health care and might pay copays so we can leverage their input on how they pay copays currently.
- Also, re: combining debts and copays -- how many veterans owe debts, and how many owe copays? This might help us figure out if we should combine the two and which one is more common (my guess is copays, but I am genuinely unsure if that's the case).

**Comment by ajakabcin** [comment]
Completed review with team, moving on to our second midpoint review with these revisions.
