### ISSUE TITLE
Determine ideation of product features

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4338]
## User Story:
As a _____UX designer_____, I need _list of research items_____ so that I can __to validate x________.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] create the format for the meeting
- [ ] host meeting
- [ ] document in GH
- [ ] etc

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] Testable Outcome Y
- [ ] Testable Outcome Z

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
closing - work complete
