### ISSUE TITLE
Design | Profile | BAI | Full Research Findings Summary

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43384]
## Background

Complete summary for UAT

## Tasks
- [x] Create summary including recommendations

## Acceptance Criteria
- [x] Publish summary and Sharon with PO and PM
- [ ] Post to Github research folder

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow - the [full findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/research/findings-summary.md) is ready for your review! If you're both available tomorrow (Wed), is it helpful to meet and go over the recommendations I've made (specifically for the confirm-related content) before I'm out on Thursday? If there's anything to talk through it'd be great to touch base before Samara's PTO next week. 😃

**Comment by Samara-Strauss** [comment]
Hey Christina! Thanks for this. I'm only available at 4:00 ET this afternoon. Otherwise, I am booked from 1 - 5 ET today.

**Comment by cgednalske** [comment]
If it's not too soon and you're both available (also want to be sure to give you enough time to look over the doc in the first place!), I could meet anytime after 11:45am before our retro/planning at 1pm, say 12pm EST? I can move this scheduling convo to our Slack channel as that might be easier to arrange.
