### ISSUE TITLE
Request internal DNS resolution for new domains

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#43389]
## Issue Description
The new `*platform-api.va.gov` domains will NOT automatically be available from locations within the VA network. While external connectivity is first priority, we also need the domains to resolve internally. The reason for this is that the VA has "Split DNS" implemented, which means that there are different DNS servers resolving DNS from within the network than outside of the network (i.e. external/public facing DNS):

1. Public users will resolve DNS on va.gov domains using the VA F5 devices as the authoritative DNS servers.
2. Internal VA users (CAG, GFE on VPN) will resolve DNS on va.gov domains using the VA domain controllers (which are essentially Windows servers) as the authoritative DNS servers

To enable internal DNS resolution, the  "VA Active Directory/Domain Controller team" will need to add a set of CNAMEs that point to the domains to the appropriate load balancers. We need to submit a Service Now (SNOW)/YourIT request to have these CNAMEs set up.

---
## Tasks
- [x] Submit YourIT ticket explaining the request
- [x] Monitor ticket status
- [x] Confirm CNAMES are set up on VA internal network

## Acceptance Criteria
- [x] Internal DNS resolution works for all domains
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
