### ISSUE TITLE
Letters | Fix download button a11y

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43386]
## Value Statement

**_As a_** screenreader user
**_I want to_** know that the download process is occurring after I activate the "Download letter" button
**_So that_** I know something happened after I use the button

## Background Context

Within the letters app accordions are "Download letter" buttons. They are buttons instead of a download link because they are generated by an API after the Veteran uses the button. Once the letter is generated it is automatically downloaded. The processing time may vary, and the only "visual" indication is a disabled "Download letter" button with "Downloading..." text.

<details><summary>Download commissary letter interaction</summary>

![On the VA letters app page, the Commissary letter accordion is expanded and then the green (soon to be blue) "download letter" button is clicked and it immediately becomes disabled and shows "Downloading..." as the button text. After a short period of time, a success alert with the header "Your letter has successfully downloaded" and content of "if you want to download your letter again, please press the button below". And the Download letter button is enabled again.](https://user-images.githubusercontent.com/136959/175694094-7134c185-6f0d-49ae-8445-be6367c4588c.gif)</details>

From the accessibility recommendations:
- The disabled download button may be replaced by a visual spinner, text or combination. Screen readers don't read disabled form elements. Use `aria-live` or `aria-busy`
- Change the text to something like "Create letter"
- Shift focus to the success/error alert upon completion
- Determine if the letters can be pre-generated, then download links can be used and there's less of a delay while the letter is being generated

## Tasks

- [ ] Determine if the letters can be generator upon app load
- [ ] If downloadable, switch to links; if not, add busy indicator
- [ ] Shift focus to alert
- [ ] A11y review of changes
- [ ] Add tests
- [ ] Test with a screenreader 

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
- [ ] Get a11y expert to review

**Comment by saderagsdale** [comment]
@jacobworrell think this is for the letters app? Moving to an icebox spot.
