### ISSUE TITLE
[BE] Update specs for physical location

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43411]
## User Story
As a Veteran, when I am using Patient Pre-Check-in to complete pre-check-in tasks for my appointment, I would like to see the physical location for my in-person appointments so that I understand where my appointment is and will know that I am in the right place.

The clinicLocation is a pass through, so this ticket is to update the specs with the current data we get from LoROTA.

## Background info
Slack [thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1653665302561659)

## User Workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the physical location for each in-person appointment
  
## Tasks
- [ ] Update specs
- [ ] [BE] Make the physical location available to the frontend

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging
