### ISSUE TITLE
[Design] Notice of Disagreement Design and Usability

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4341]
## High Level User Story/ies
As a researcher/designer on the Benefits and Memorials team, I need to conduct user research of the Notice of Disagreement prototypes so I can identify any design needs that are recommended by the users.

## Full project epic #2140

- [ ] Create research plan & kickoff recruiting #4342
- [ ] Initial design mockups based on Lighthouse initial research
- [ ] Recruit for research sessions / schedule research sessions
- [ ] Create conversation guide 
- [ ] Conduct research sessions 
- [ ] Discovery synthesis
- [ ] Discovery Research readout
