### ISSUE TITLE
Fix broken link Getting Started/Welcome/Information Architecture

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43421]
## User Story
As a VFS team member, I want to be able to find the information I'm looking for on Platform Website and not encounter broken or invalid links.

Assignee: @claytonzook 
Peer Reviewer: @allison0034 

## Description
There is a broken link on the [Getting Started/Welcome/Information Architecture page](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome#Welcome-Informationarchitecture) under Here are the best practices for writing URLs. The page should link to this [URL standards page](https://design.va.gov/content-style-guide/url-standards) on the VA.gov Design System site. 

## Impacted Artifacts
Getting Started/Welcome/Information Architecture page](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome#Welcome-Informationarchitecture)

## Tasks
- [ ] Update link on Welcome page to direct to URL Standards on VA.gov Design System

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS team members are able to access URL standards from the Platform Website Welcome page

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by claytonzook** [comment]
Ready for peer review @allison0034 

Note: I did a quick look at some other links on this Welcome page and found found a couple that lead to deprecated GH pages which then link back to an appropriate PW page. It's out of scope for this ticket, but since there were a couple clear, easy wins, I replaced a couple GH links I found with the PW links that were applicable replacements while I'm working on this page. All the links I edited included 
- The link under IA, as described in this ticket
- The last link under Engineering heading
- The link under Analytics and Insights
- The link under QA

@chaseakirby Also on this same Welcome page several other links are broken with no clear link to replace. This page probably requires a full content audit on the links and then someone to find appropriate replacement links as needed. If this page is fully managed by our team, probably means a new ticket. If other team(s) manage content on this page, they might appreciate a notification of our findings.

**Comment by allison0034** [comment]
@claytonzook can you link the pages in your comment above? Also, I am still getting a 404 for the [here are the best practices for writing URLs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/url-guidelines.md). My assumption is your changes have not been pushed to PW since those are only done on T/TH around noon.

**Comment by claytonzook** [comment]
@allison0034  - those other links that I changed below. And yeah, on second thought probably not 100% ready for peer review until the publish today.

2. [Last link under Engineering](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome#Welcome-Engineering) > "Here's what to expect, and how to request a code review"
3. [The link under Analytics and Insights](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome#Welcome-Analyticsandinsights) > "Here's what to expect, and how to request an Analytics review"
4. [The link under QA](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome#Welcome-QA) > "Here's how to QA your solutions"

**Comment by shiragoodman** [comment]
@claytonzook afaik, we don't own the whole page. Only the sections that are relevant to our teams practice areas: Product, Design, Content, IA, accessibility, and QA (although QA Standards team might own that one). I am going to confirm this with leadership.

**Comment by allison0034** [comment]
@claytonzook these all look good!
