### ISSUE TITLE
GA4:  Configure GTM Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43429]
## Issue Description
Configure VFS team required custom event tags in GA4.

[GA4 Event Configuration Tracker](https://docs.google.com/spreadsheets/d/1XDceQQVK6IGOl8R1OzhbncSc1Hrs37IEyQblW_Spk-Y/edit#gid=1403781092)
[GA4 Configuration Meeting Recording](https://drive.google.com/file/d/1Ui3F5w46bVVSDZmFgPdcLasH9_RFJReU/view?usp=sharing)

---
## Tasks
- [x] Register event parameters in prod & non-prod (Pavan)
- [x] Configure event tags in tag manager (Jenna & Jonathan)

[GA4 Planning](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=0)

## Acceptance Criteria
- [x] When all of the event tags have been configured and are ready for hand off to FEs

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
