### ISSUE TITLE
GA4:  Configure GTM Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43430]
## Issue Description
Configure VFS team required custom event tags in GA4.

---
## Tasks
- [ ] Configure custom event tags in GTM based on VFS team requirements
[GA4 Planning](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=0)

## Acceptance Criteria
- [ ] When all of the [GTM events](https://docs.google.com/spreadsheets/d/1oi85RaKDAxN141kZoKTOPuQWW_7w1dTc0523ZMPGW2I/edit#gid=2039504303&fvid=655039043) have been configured in GTM
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
