### ISSUE TITLE
Design | Auth Profile | Create User Flow for BAI

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43439]
## Background

We will be creating user flows that depict the screen flows and logic used for our features/functionality. This ticket is for the creation of a user flow in support of the Bad Address indicator.

## Tasks
- [ ] Create a wireframe depicting user journey from seeing the bad address alert to successfully update along with possible issues that may be encountered.

## Acceptance Criteria
- [ ] Review wireframe with PO and PM 
- [ ] Walk through with team at a stand-up
- [ ] Add to sketch file

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - can you take a look at this ticket and let me know if there are any act'l tasks or AC we should include? I also parked in Sprint 77 for now.

Also can you point it?

Once this is in good shape I will do the other ones change address messaging and contact info.

**Comment by cgednalske** [comment]
Reassigning to @andaleliz to fit within her Contact info documentation work.

**Comment by andaleliz** [comment]
[User flow created in Sketch](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/7yPo0rZ)
