### ISSUE TITLE
[Design] Work with LightHouse and Board on NOD Business Process Flow

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4344]
## User Story:
As a designer, I need to review the NOD business process flow with the board stakeholders so that I can ensure I am moving in the right direction with my designs.

## Tasks
- [x] Identify stakeholder names
- [x] Schedule call with stakeholders
- [x] Document/discuss/understand process flow

## Acceptance Criteria:
- [x] Meeting scheduled
- [x] Review/update our process document

**Comment by kevinstachura** [comment]
Before doing this, we need to align with the Lighthouse team on which stakeholders to communicate with on this and establish a collective understanding before reaching out to the board. My prediction is that this will occur the upcoming sprint, making it appropriate to move into next sprint for completion.

**Comment by kevinstachura** [comment]
We have yet to meet with the board to fully confirm that our design complements the business process. We can close this ticket after we confirm uniformity for business process + online process.

**Comment by vhenry07** [comment]
Closing complete, visa Lighthouse & C&A research.
