### ISSUE TITLE
Independently Verify Google Lighthouse Plugin Accuracy

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43455]
# Description
Google Lighthouse scores for a given URL hosted on the platform should be consistent regardless of what tool triggers the audit. Compare the Google Lighthouse scores generated by the Backstage plugin with the scores from the audit generated in GHA both in aggregate and for individual products / catalog entries.

# Tasks
- [x] Grab scores from GHA
- [x] Grab scores from Backstage plugin
- [x] Run a one-off individual scan of the Platform using Google Lighthouse
- [x] Compare scores to ensure parity

# Acceptance Criteria
- [x] Google Lighthouse audit results generated from the Backstage plugin match the results from Google Lighthouse audits generated from GHA and independently

**Comment by rbeckwith-oddball** [comment]
All the audits I ran with the locally setup installation returned matching results as seen in the GHA and BigQuery data. If one wishes to follow the instructions created [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2298216500/Google+Lighthouse+Plugin) and verify as well, then this should be considered as done.

**Comment by pjhill** [comment]
Google Lighthouse Performance scores vary depending on what machine is executing the audit. So, for example, the Platform Console hosted Google Lighthouse plugin will depend on a service that is running on Platform Console infrastructure. If that infrastructure is bogged down, or differs substantially from the runners then the performance score will be different. Additionally, networking plays a part in the score.
