### ISSUE TITLE
Acquire Permissions to Install and Configure Plugins in Platform Console

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43450]
# Description
In order to be able to install and configure a plugin from the Backstage marketplace in Platform Console, we expect to require some level of elevated privileges in Platform Console.

# Tasks
- [x] Determine what permissions are required
- [x] Create an account for Platform Console use (if you don't already have one)
- [x] Work with Console UI team and Access Management team to ensure that your account has the appropriate permissions
- [x] Verify sufficient access to install and configure a plugin

# Acceptance Criteria
- [x] Access required to install and configure a plugin from the Backstage marketplace is known
- [x] Developer's account has the required access

**Comment by pjhill** [comment]
Hey sorry for the delay -- 
* You answered that first question on your own, but yeah, at this time we are just looking to get that Google Lighthouse plugin installed. There may be more later
* Have you figured out exactly what permissions are required to do the installation? If you have then please list those out in this ticket so others on the team can repeat the process or make the same request.
* AFAIK, no one has prior experience with installing a plugin from the marketplace aside from maybe someone on the Platform Console teams.

**Comment by JoeTice** [comment]
@rbeckwith-oddball - if this is done, please comment on it and mark it as closed

**Comment by pjhill** [comment]
Permissions have been acquired and installation and configuration has been completed locally. Those changes are being collected into a PR now, but no additional permissions are required.
