### ISSUE TITLE
Install and Configure Google Lighthouse Plugin in Platform Console

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43452]
# Description
The Backstage [marketplace](https://backstage.io/plugins) has a [Google Lighthouse plugin](https://github.com/backstage/backstage/tree/master/plugins/lighthouse) which we will be able to install and configure for use in the Platform Console.

# Tasks
- [x] Run through the installation steps defined in the plugin [README](https://github.com/backstage/backstage/tree/master/plugins/lighthouse#getting-started)
- [x] Configure the plugin to [integrate with the catalog](https://github.com/backstage/backstage/tree/master/plugins/lighthouse#integration-with-the-catalog) where possible
- [x] Get the plugin working using the Node Express [instructions](https://github.com/spotify/lighthouse-audit-service#as-an-express-app) 
- [ ] Update the [documentation](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2298216500/Google+Lighthouse+Plugin) for installing and configuring the Google Lighthouse plugin in the Platform Console once the solution is finalized

# Acceptance Criteria
- [x] Google Lighthouse plugin displays a list of audits:
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/783539d1-0e9e-4143-a0d7-bae41812e9ff)
- [x] Google Lighthouse plugin displays the details for an individual audit:
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/b0fe9dd7-588e-4c17-a9f5-5638b8f0f270)
- [ ] Google Lighthouse plugin is available in the production Platform Console app

**Comment by rbeckwith-oddball** [comment]
Are we intending to create any plugins or components ourselves, or is this only going to be limited to installing the Lighthouse plugin?

**Comment by rbeckwith-oddball** [comment]
- [Slack thread](https://dsva.slack.com/archives/C03NECF9NMV/p1658436279589509)
- [Issue tracking](https://github.com/department-of-veterans-affairs/platform-console-ui/issues/706) on their side
- [Document](https://platform-console-ui-utility.vfs.va.gov/docs/default/Component/platform-console-ui) I was provided

**Comment by rbeckwith-oddball** [comment]
It looks like there isn't a way of installing this without setting up my machine for local development. Following the setup instructions from the document. Should ideally have my environment setup by Monday with the potential for a PR later on Monday or early Tuesday.

**Comment by rbeckwith-oddball** [comment]
Links used for setting up local environment:
- [Setting up the platform consolue ui](https://platform-console-ui-dev.vfs.va.gov/docs/default/Component/platform-console-ui/getting-started/setting-up-the-platform-console-ui/)
- [Installing dependencies](https://platform-console-ui-dev.vfs.va.gov/docs/default/Component/platform-console-ui/getting-started/configure-dependencies/)
- [Running tests](https://platform-console-ui-dev.vfs.va.gov/docs/default/Component/platform-console-ui/getting-started/running-tests/)
- [Platform Consolue UI Repo](https://github.com/department-of-veterans-affairs/platform-console-ui)
  - See [plugins](https://github.com/department-of-veterans-affairs/platform-console-ui/tree/main/plugins) directory

**Comment by rbeckwith-oddball** [comment]
Got keycloak and Postgres installed and setup. It was a bit of work since I had versions installed specific to `tud`. Will be attempting to install the plug-in manually around lunch today.

**Comment by rbeckwith-oddball** [comment]
The platform console UI has been setup. Ran into some hiccups with `backstage` persistent storage, but should be properly configured now. Have to follow the steps / procedures from [here](https://backstage.io/docs/plugins/) to finish up.

**Comment by rbeckwith-oddball** [comment]
The Lighthouse plugin was one of the more complicated plugins I encountered. Using the details from previous tests in BigQuerey for comparison, it looks like there might already be a Lighthouse audit service we may be using. In which case, some of the settings will need to be modified to use that service instead of installing another one via docker on the instance actually running the platform-console.

We'll need some further details before I consider it safe to submit a PR for [this branch](https://github.com/department-of-veterans-affairs/platform-console-ui/tree/rb/qas/backstage-lighthouse-plugin) - Mainly if we want lighthouse to be installed as a service on the machine that runs platform-console, or do we already have a lighthouse audit service we should use instead? This would only be a minor tweak to the settings in the `.yaml` file.

**Comment by rbeckwith-oddball** [comment]
The creation of the catalog file isn't quite working the way the documents lead me to believe, but this should be a quick fix / implementation when finding out what the deal is. I'll likely check-in on Monday's meeting just to make sure everything is clear.

**Comment by pjhill** [comment]
Putting this back into `In Progress` for now since there are a few more tasks to complete before the ticket is wrapped.

**Comment by rbeckwith-oddball** [comment]
@ericvoshall - sorry for the delayed response, I was out last week. The Google Lighthouse plugin requires the [Lighthouse Audit Plugin](https://github.com/spotify/lighthouse-audit-service) to run. You can see the changes to the Docker file [here](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/54a3ee9ce1408e0d26d02e61e76ae00ca86ad456/development/docker-compose.yml#L23). 

Is there something specific to do in order to get the the service steup as a container for production or staging, or will something pick up the changes in the `docker-compose.yml` file?

You can also see that it needs postgres auth stuff to setup the audit tables as well as save audit results.

**Comment by rbeckwith-oddball** [comment]
I was able to get the lighthouse audit service to run as an express app, but the lighthouse plugin itself fails to recognize the `baseUrl` setting.![lighthouse_update1.png](https://images.zenhubusercontent.com/61265d854c842ee6052dd62e/a55f5bfa-f35a-4f57-a6c3-855550573d2b)
- I ran the program through `strace` and verified that the `lighthouse.baseUrl` setting is present at runtime, and should be accessible.
- The **only** way I was able to work around this issue was by modifying the lighthouse node module: 
`node_modules/@backstage/plugin-lighthouse/index.esm.js`.

```

 30   static fromConfig(config) {
 31     return new LighthouseRestApi(config.getString("lighthouse.baseUrl"));
 32   }
```

to become
```

 30   static fromConfig(config) {
 31     try {
 32       return new LighthouseRestApi(config.getString("lighthouse.baseUrl"));
 33     } catch (err) {
 34       return new LighthouseRestApi('http://127.0.0.1:4008/lighthouse');
 35     }
 36   }
```
![lighthouse_update2.png](https://images.zenhubusercontent.com/61265d854c842ee6052dd62e/7a1b7014-9dca-45ad-ae3e-67d1dcc74668)
Unless something was changed that alters the scope of `Config` objects and not being able to see certain variables?

### Problem
Node modules aren't included in the git commits, so I'm not sure of what to do in order to resolve this.

**Comment by rbeckwith-oddball** [comment]
@ericvoshall - the git commit check informed me that the yarn dependency wasn't properly linked in the backend. `yarn add...` seems to have worked. The code is committed as [rb/qas/backstage-lighthouse-plugin-express](https://github.com/department-of-veterans-affairs/platform-console-ui/tree/rb/qas/backstage-lighthouse-plugin-express "Lighthouse Express App") if you want to look over it anyhow.

**Comment by rbeckwith-oddball** [comment]
Excellent @ericvoshall! Final question: what should the base URL for production and / or utility be set to? I can see that `app-config.production.yaml` would be the location to update the production value, but I'm not sure where we would update the utility version for the baseUrl.

**Comment by rbeckwith-oddball** [comment]
The PR has been submitted  https://github.com/department-of-veterans-affairs/platform-console-ui/pull/849

**Comment by rbeckwith-oddball** [comment]
The PR has been submitted  https://github.com/department-of-veterans-affairs/platform-console-ui/pull/849

**Comment by rbeckwith-oddball** [comment]
The automated tests are having some issues that are being investigated now.

**Comment by rbeckwith-oddball** [comment]
The automated tests have now passed after a few false positives were skipped (confirmed as false by platform-console team). Eric has merged the code and it should be in the dev environment within the next 10-15 minutes.

**Comment by rbeckwith-oddball** [comment]
It merged, new tweak had to be pushed since the lighthouse `baseUrl` apparently isn't used internally. Now the platform-console team needs to do something with their manifest files to get the port open.

**Comment by rbeckwith-oddball** [comment]
They were able to find a way to proxy the request instead of having to open an external port. The issue being encountered now is:

```
{
  "auditId": "14a3893e-dd77-4e2f-9299-e103984e812e",
  "level": "error",
  "message": "failed to launch puppeteer browser.\nError: Failed to launch the browser process! spawn /home/node/app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
  "service": "lighthouse-audit-service",
  "url": "https://platform-console-ui-dev.vfs.va.gov"
}
```

But I was able to verify that the file actually exists, so they are investigating further.
```

~/app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux $ stat /home/node/app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
  File: /home/node/app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
  Size: 325132000       Blocks: 635032     IO Block: 4096   regular file
Device: 10000ah/1048586d        Inode: 2770546     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    node)   Gid: ( 1000/    node)
Access: 2022-08-18 13:48:15.000000000 +0000
Modify: 2022-08-18 13:48:15.000000000 +0000
Change: 2022-08-18 13:59:56.113871298 +0000
```

**Comment by rbeckwith-oddball** [comment]
I realized at this point, the plug-in is a service / system-level installation. I realized I was writing documentation for installation of the plug-in, but now that the code has been merged, there shouldn't be any additional steps needed to get the plug-in running locally or in development. So, nobody should technically have to go through this again. The documentation made more sense to me when I thought the plug-in was going to be user level. I can still publish the system install, but didn't know if it seemed unnecessary to anyone else.

**Comment by pjhill** [comment]
Recording the process to get it merged is still important for future plugin installation. This was partially intended to trailblaze for subsequent installation of plugins from the Backstage plugin marketplace if anything relevant pops up.

Is there any documentation that would be helpful for ongoing maintenance of the plugin? Updating it to a new version? Altering the configuration?

**Comment by rbeckwith-oddball** [comment]
The most up-to-date / relevant documentation can be found at [Google Lighthouse Plugin - Confluence](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2298216500/Google+Lighthouse+Plugin).

As it currently stands, the plugin is configured and enabled, but doesn't function properly for self-signed certificates. Further investigation and discussions with Eric lead us to believe that there isn't a method of working around this issue at the moment, but installing the VA certs into he container may rectify the issue (which is something the platform console is doing).
![lighthouse_issue1.png](https://images.zenhubusercontent.com/61265d854c842ee6052dd62e/c52746de-f897-469a-bb94-a4b99c572258)

**Comment by rbeckwith-oddball** [comment]
## Update
Installing the certificates in the local containers has rectified the issue with the self-signed certificate errors when running an audit against some of our websites.

**Comment by pjhill** [comment]
Looking good in `dev`. We can discuss a plan to promote this to the prod equivalent `utility` environment in the future.
