### ISSUE TITLE
Document Installation, Configuration, and Use of Google Lighthouse Plugin

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43457]
# Description
We need to ensure that the installation, configuration, and use of the Google Lighthouse plugin in backstage is reproducible. We will collect all information for this plugin into a single document hosted in Confluence under our QAS team space.

# Tasks
- [x] Create a Google Lighthouse Backstage Plugin Operational Guide
- [x] Add information to the guide about any customization apart from the [standard plugin installation](https://github.com/backstage/backstage/blob/master/plugins/lighthouse/README.md) and configuration required that will help Platform maintainers to re-create the setup of the plugin
- [x] Add information about what platform needs to know in order to successfully operate the Google Lighthouse plugin in the Platform Console

# Acceptance Criteria
- [x] A Google Lighthouse Backstage Plugin Operational Guide exists in the QAS team Confluence space
- [x] The operational guide contains information that enables Platform personnel to recreate the installation, configuration, and operation of the Google Lighthouse plugin in the Platform Console

**Comment by rbeckwith-oddball** [comment]
Confluence documentation can be found [here](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2298216500/Google+Lighthouse+Plugin)

**Comment by pjhill** [comment]
Thanks for writing up the installation process and results. That Confluence page looks great!
