### ISSUE TITLE
Define content writing strategy for console

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43463]
## Problem Statement
The Spike teams' contract ends on Sept 11th, which means their last working day is Sept. 9th and there will be no centralized console team with a dedicated writer. 

## HMW
How might we assist in promoting excellent content in Console? Do we need to? Is that this team's job? 

## Hypothesis
If we spend time figuring out the content strategy for console at the beginning of Q3, we won't be scrambling when the spike teams leave in September. 

If we provide some oversight or guidance of the content in Console, VFS teams will have a better experience using it. 

## User Story
As a platform team building a new feature onto the Console,
I need to ensure micro copy in new parts of the user interface being added to the Console are carefully considered,
so that the Console follows the same tone and style guidance consistent to the Platform.

## OKR
2022 Q3 Platform Objective 4 Transition products and services from Spike teams

## Definition of done

- [x] Content strategy for console has been identified 
- [x] Content strategy decision has been documented
- [x] Content Strategy has been signed off on by leadership (contract and OCTODE)
- [x] Content strategy has been introduced to teams contributing to the console

## Initiative Summary/Takeaways

- Platform Content team met internally and sought out information from other stakeholders (leadership, Console UI, Release Tools, etc.) to learn more about the Console, its intended purpose, stakeholders, its anticipated future and more.
- Once the spike teams' contract ends, the Platform Content team wishes to continue to review micro copy needs for the Console in the future, as needed.
- However, we anticipate a drastic decrease in the need for this kind of support, as the Console is being deprioritized in future quarters.
- This makes the Platform Content team's level of involvement in the Console low.
- In the event that another Platform team **does** add new features/functionality to the Console, **we recommend that a "micro copy review" is part of their project's definition of done.**
- This process would alert the Platform Content team of any pages the team can review and make any recommended micro copy suggestions that follow the Platform's tone and style guidance.
- A product outline, recommended copy review workflow have been documented to reflect this.
- Related work: Assisting Console UI with bringing any new content onto the Platform website, as needed.

## Known blockers, dependencies or risks
- WORKFLOW DEFINED DEPENDENCY: New features/functionality built onto Console are unlikely, as Console is being deprioritized in Q4
- RISK: The defined copy review workflow is dependent on teams, such as Release Tools, ensuring they add the Platform Content team's review as part of their definition of done.

## Product Outline
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2267676673/Product+outline+-+console+content+support+services

Copy review workflow: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1658930919439/6f43924874384e4b82557b1ad53b278a5247997f?invited=true&sender=u9d01ee38af217e4877e75660
