### ISSUE TITLE
[FE] [APPT SCHEDULER] [BUG] Last appointment of the day shows incorrect duration

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43479]
## Background

![image (29).png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/2b4eaf58-849a-4b5e-8063-6b1931eebf02)

Shawn thinks that it's probably assuming a duration until the end of VistA-displayable time.

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Appointment durations are correct
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
@acrollet this issue seems to have gone away with the multi-day fix. Here is a screenshot from the same clinic:
![image.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/fd557320-6348-4646-9e38-280afa2f9fd5)

I think this one can be closed. What do you think?

**Comment by acrollet** [comment]
I agree! We can always re-open if it crops up again.
