### ISSUE TITLE
Tests for platform-api routes to vets-api

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43478]
## Product Outline
[CIT Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)

## High Level User Story/ies
As a developer, I need to create tests which verify the pathway of the *platform-api.va.gov subdomain(s) to vets-api, so I can be confident that the route is working in all environments (dev, staging, sandbox, and production.)

## Hypothesis or Bet
By implementing manual and automated tests for each *platform-api.va.gov route to vets-api, we can monitor the health of each route.

## OKR
The *platform-api.va.gov subdomains have been procured and enabled for handoff to use in all environments.

### What must be true in order for you to consider this epic complete? 

- [x] Reproducible, manual browser test(s) which validates the route of the *platform-api.va.gov subdomains to vets-api in each environment (dev, staging, sandbox, and production.)
- [x] Passing Datadog test(s) which confirms the route to vets-api in each environment (dev, staging, sandbox, and production.)

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by alwerner** [comment]
@madebydna Please review this Epic for accuracy.

**Comment by alwerner** [comment]
Closing as complete. Datadog test link: https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3Acit%22%29
