### ISSUE TITLE
[Usability Testing] Decision Review Research Plan

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4347]
## User Story or Problem Statement
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and user testing recruitment needs. 

## Goal
_A completed research plan sent to Perigean for user testing recruitment_

## Objectives or Key Results this is meant to further
- User testing to validate the Decision Review process and uncover gaps, improvements, and pain points

## Tasks
- [x] _Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)_
- [x] _Review research plan with design team_
- [ ] _Obtain approval from Andrea Schneider_
- [ ] _Send research plan to Perigean_
- [ ] _Add research plan to GH_

## Acceptance Criteria
- [ ] Research plan has been created

**Comment by kevinstachura** [comment]
Research Plan has been created!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/research/website-research/research-plan.md

@AZSchneider would you be so kind as to review and suggest edits or approve as is? Thank you!!
