### ISSUE TITLE
[FE] [APPT SCHEDULER] [FEATURE] Display appointment IEN when viewing appointment details

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#43480]
## User Story
As a developer, I wish to know the appointment IEN after creating an appointment, so that I can create pre-check-in links for non-staging environments.

  
## Wireframes
(excuse the trackpad drawing)

![image (30).png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/a99c8029-d5b2-4b61-85de-312a13c7f7b1)

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Appointment IEN is displayed when viewing appt details
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
validated in live application, moving to closed
