### ISSUE TITLE
Research | Notification Preferences | Default Opt-in

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43489]
## Background

Currently, VA Notify supports the option for a business line to choose whether to default users to **opt-in** to a notification.

We need to take a closer look and understand what the impacts are for us from a design as well as technical perspective.

- What type of notifications are eligible for a default opt-in?
- How do we convey the different notification types to users (user opt-in vs default opt-in)?
- How can a user opt-out of a default opt-in?
- How do other websites approach this? Are there any best practices" we should consider?

Further reading on [of our notification page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/display-notes.md)

## Tasks
- [x] Determine what Design changes would be required to make the above enhancement.
- [x] Determine what Front End changes would be required to make the above enhancement.
- [ ] Create a mock-up(s) of what screen may look like with this option and how we should to communicate default opt-ins vs standard opt-ins to users

 ## Acceptance Criteria
- [ ]  Schedule a discovery review session with Samara & Sharon to discuss findings, level of effort and recommended next steps
- [ ] Create a rough mock outlining recommendation

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
This looks good to me. One additional question I have is whether we are required to show the difference between when a user has opted in themselves and when they have been opted in by default. In theory, a default opt-in and user opt-in could look exactly the same -- we just show that someone is receiving a notification. However, since we are government, I'm unsure of whether we have to differentiate between default opt-in and user opt-in, especially given that the old VANotify team seemed to suggest we did need to make this kind of distinction.

**Comment by andaleliz** [comment]
@Samara-Strauss I'll ask the VA Notify team about that requirement. One of my main questions right now is how does this new data point in the API change the documentation Mark wrote above? Perhaps that is what the task ` Determine what Front End changes would be required to make the above enhancement.` will cover? I think that needs to be a separate discovery/research ticket for the devs.

**Comment by andaleliz** [comment]
I've written up what I've learned so far and added it to[ our product docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/default-send/july-2022-notes.md). Meeting w the VA Notify team tomorrow to clarify a couple of things and then I can wrap this up.

**Comment by Samara-Strauss** [comment]
> I was curious if we still have the same KPIs as when we launched, and I noticed the product outline was updated in April and that we're not longer tracking the [same success metrics as we did when this was first launched](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/mvp-project-outline.md#measuring-success). 

I don't track KPIs indefinitely, given that eventually numbers are probably relatively steady if we're not actively making changes to a given page. 

> The alert on the page and the call outs on the radio buttons were designed to support those metrics. If we're no longer tracking those, I wonder if we can revisit having those on the page. It would clean up the UI if we could eliminate those.

I don't think we need to make immediate changes here, at least, it's not as much of a priority as documentation or the accessibility audit I want us to do when time allows. Feel free to create a ticket for the backlog to look into this, but I wouldn't plan on it more immediately.

**Comment by andaleliz** [comment]
We met yesterday and determined we'll hold off on any further design tasks for this initiative. There is likely FE and BE work needed - @SKasimow can you go ahead and make tickets for those per our convo yesterday?

I went ahead and [created a ticket for the backlog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44229), assigned to me, Christina, and Sharon since it needs to be prioritized and we don't know which designer will work on it when we get to it.
