### ISSUE TITLE
BE | Discovery | Notification Preferences | Default Opt-in

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43491]
## Background

Currently, VA Notify supports the option for a business line to choose whether to default their notifications to **opt-in** .

We need to take a closer look and understand what the impacts are for us from a design as well as technical perspective.

Further reading on [of our  notification page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/frontend/display-notes.md)

## Tasks
- [x] Identify what information we receive in the back-end
- [x] Note if there is anything missing or would be obstacles to implementing 

## Acceptance Criteria
- [x] Document findings and recommendations and share with PO and PM

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by tpharrison** [comment]
Hi @SKasimow - can we discuss this when you have some time?  I just want to make sure I understand the intent.  Thanks!

**Comment by SKasimow** [comment]
@tpharrison yes absolutely! I have a few things I need to catch up with you on. Think we might cover this at planning mtg but if not, will add to my list

**Comment by tpharrison** [comment]
@SKasimow @Samara-Strauss 

VA Profile has added a _Default Send Indicator_ flag to each Communication Item per each associated Communication Channel.  This flag will need to be included in the data returned from the vets-api so its available to the FE.

I've created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43910) to document the necessary BE work.

Let me know if you have any questions.
