### ISSUE TITLE
Q3 -- Task: Release activities

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43499]
## Definition of done

- [x] Product Outline is created
- [x] Decide with PO if we need to do usability testing - Usability testing will be planned for Q4, as discussed with PO during check-in: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2085093522/Content+Mike+Chelen+running+notes
- [x] There is a communication plan for releasing this
- [x] Go/no-go has been completed
- [x] Any issues from go/no-go have been addressed

**Comment by vbellissimo** [comment]
Completed

Product repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/platform-website
Actual establishment of the processes of how our team supports other teams with content requests (just not documented)
Product outline for the Platform website, as a product: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2064613465/Platform+website+product+outline
A styleguide: https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide
User guide/"how-to" documentation of the process for platform publishing guidelines: https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines
Not completed

DONE - Product outline for our team's content support services, as a product (content deploy and website footer/"suggest changes to this page")
User guide/"how-to" documentation of the process to request content support from our team (website footer/"suggest changes to this page")
Communications plan for content support services
Usability testing for the process to request content support from our team nor the Platform website as a product
End to end manual QA or UAT for the process to request content support from our team nor the Platform website as a product
Not added to the list of VSP products (Joe Tice=new list): https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0
Partner with Service Design team to post on #vsp-service-design for external communication
Go/no-go with leadership
Clearly defined success metrics (I recommend this is skipped on this initiative/epic, as it is being address as a separate initiative/epic).
Not applicable

Automated testing running in CI/CD

**Comment by vbellissimo** [comment]
Closing this roll-over initiative per conversation with PO (Mike Chelen) during sync on 7/27/22; Also presented this review as part of Go/No-Go on 7/19/22.
