### ISSUE TITLE
Discovery: What tool(s) do we want to utilize to capture the Platform Website KPIs

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43496]
## High Level User Story/ies
As a member of the Platform Content team, I need the space to do discovery about what tools we can use and others are using so I can capture the Platform Website KPIs.

## OKR
2022 Q3 Platform Objective 3: Implement health metric dashboards for the overall platform and platform teams#43034

## Definition of done

- [x] Team has engaged Analytics and Insights to figure out what tools should be used to capture analytics on Platform Website
- [x] Team has explored confluence options for analytics if identified KPIs are around data that can only be retreived from confluence (for example, least recently updated documention) 
- [x] Team has sign off from PO on the tools decisions
- [x] Team has identified and refined the tasks associated with implementing the tool(s) in ZH
