### ISSUE TITLE
Identify KPIs for Platform Website in Priority Order

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43495]
## High Level User Story/ies
As a Platform team contributing to platform website, I need access to analytics about the documentation I'm providing to VFS teams so I can make decisions about where to iterate.

## OKR
2022 Q3 Platform Objective 3: Implement health metric dashboards for the overall platform and platform teams#43034

## Definition of done

- [x] KPIs are identified
- [x] KPIs are prioritized in order from most important to least (to inform discovery)
- [x] KPIs all have a clear way to use the metric to make decisions (Just because we can get the number -- why do we want to get that number and how will platform teams leverage it)
