### ISSUE TITLE
Communication and Documentation: Platform Website Analytics

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43498]
## Task
Park of each initiative is communicating and documenting the changes. This epic will capture all the tasks associated with documentation and communication of the platform website analytics

## OKR
2022 Q3 Platform Objective 3: Implement health metric dashboards for the overall platform and platform teams#43034

## Definition of done
- [x] Content team has gathered feedback from 1-2 Platform teams about how helpful the metrics identified are to them
- [x] Content team has gathered feedback from 1-2 Platform teams about how easy it is to access this data
- [x] Platform teams know how to access Platform website data and analytics
