### ISSUE TITLE
Health Metrics -- Define Platform Content Team's Health Metrics

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43494]
## Problem Statement
Over the last year, the Platform Content team has changed drastically in it's product offering. This time last year Platform Website barely existed and Platform's documentation was still scattered across the repos. Now that things have settled a bit, we need to figure out what metrics this team needs to collect so we can look toward those to make data-informed product decisions. 

## HMW
How might we start on our journey of health metric maturity so we can start making data-informed decisions 

## Hypothesis or Bet
If we spent the time laying the foundation for collecting health metrics, we will be in a better position to start collecting that data and building out dashboards in future iterations. 

## OKR
2022 Q3 Platform Objective 3: Implement health metric dashboards for the overall platform and platform teams

## Definition of done

- [x] Health Metrics for the Platform Content Team have been identified -- Discovery Session
- [x] Health metrics have been validated with OCTODE (Mike Chelen, then Ray Wang)
- [x] Health Metrics have been discussed with Analytics and insights (to help with how to collect/display the data)
- [x] Roadmap has been created on how to collect the KPIs/health metrics
- [x] Internal documentation is updated to reflect these health metrics the team should rally behind and the processes for checking in on them

**Artifacts:** https://vfs.atlassian.net/wiki/spaces/CIT/pages/2284584976/2022+Q3+Platform+Content+Team+s+Health+Metrics
