### ISSUE TITLE
My VA: Sprint 83 (9/21/22 - 10/4/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43504]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Onsite notifications - launch to 25% and possibly 50%
2. Payments V2 - Complete FE dev, prep for QA, submit analytics request
3. Audit - complete design intent, FE documentation

PTO
- _Ad Hoc Internal mtg all day 10/3 and morning of 10/4_
- Erica: 10/3-10/7
- Angela: 10/3-10/5

## On-site Notifications (#30611)
**PM**
- [ ] #43281
- [ ] ~#43288~
- [ ] ~#43293~ 

**FE**
- [ ] ~#43288~
- [ ] ~#43293~
- [ ] #47571

## My VA Redirect (#41223)
**FE**
- [x] #47291

## My VA Payment Info V2 (#43332)
**PM**
- [ ] ~#45967~
- [ ] ~#45966~
- [ ] #45929 *from previous sprint*

**Research/Design**
- [x] #45969 _from previous sprint_

**FE**
- [x] #45861 _from previous sprint_
- [x] #45864 _from previous sprint_
- [x] #45866 _from previous sprint_
- [x] #47288 _from previous sprint_
- [x] #47428
- [x] #47470
- [x] #47722

## My VA Payment Info MVP (#43337)
**FE**
- [ ] #45453 _from previous sprint_

## My VA Audit UX Improvements (#41934)
**PM**
- [x] #46991 

**Design/Research**
- [x] #46991 
- [ ] #47314
- [ ] #47313

**FE**
- [x] #47362
