### ISSUE TITLE
My VA: Sprint 85 (10/19/22 - 11/1/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43508]
## Priorities

1. Onsite Notifications - Launch to 100%, monitor post launch analytics, documentation updates
2. Payment Info V2 -  Complete QA, resolve any QA findings, Staging review prep
3. My VA Audit - Continue FE development (Health care section), create conversation guide, midpoint review

## On-site Notifications (#30611)
**PM**
- [x] #43300
- [ ] #45008

**Design/Research**
- [x] #48389
- [x] #48725

**FE**
- [x] #43300
- [ ] #48382

**BE**
- [x] #48383

## My VA Payment Info V2 (#43332)
**PM**
- [x] #47615 _from previous sprint_
- [ ] #47703 _from previous sprint_
- [ ] #45929 _from previous sprint_
- [x] #45967 _from previous sprint_

**Design**
- [x] #48461
- [x] #42329
- [x] #48605

**FE**
- [x] #48468
- [x] #48605

## My VA Audit UX Improvements (#41934)
**PM**
- [x] #47453 _from previous sprint_
- [x] #47616 _from previous sprint_

**Design/Research**
- [x] #48243
- [x] #47453 _from previous sprint_
- [x] #48718
- [x] #48718 
- [ ] #48701
- [ ] #48706 
- [ ] #48709  
- [ ] #48710

**FE**
- [x] #47522 _from previous sprint_
- [ ] #47523
- [ ] #48705 
- [ ] #48710

## My VA 2.0 General Enhancements (#31611)

**FE**
- [x] #48002
- [x] #48038 _from previous sprint_

**Comment by ericasauv09** [comment]
[Sprint Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/my-va/sprints-81-90.md#sprint-85-1019---111)

**Comment by ajakabcin** [comment]
In terms of priorities and order of operations, let's proceed with this plan to start the sprint:

**For design/research priorities, @aagosto90 here are your tickets to proceed with:**
1. Knock out the alternate design for overpayment debts so that when we hear back from Samara on how to proceed, Taylor can pick up the FE work (#48461)
2. Continue with the conversation guide for the audit UX improvements research (#48243)
3. Documentation updates for onsite notifications (#48389)
4. Pending outcome of content review and midpoint review of audit UX improvements, may need to adjust this to account for any feedback from those sessions that require changes

**For FE priorities, @tmitchellgcio here are your tickets to proceed with:**
1. Wrap up the claims and appeals error message bug (#48038)
2. When design is ready (and when we hear back from Samara), pickup the FE work on the overpayment debt card design (#48468)
3. While waiting for overpayment debt card design, see if you can knock out #48002 
4. Triage/address any issues found in validation of the new claims and appeals section
5. Health care section audit improvements (#47523)
6.  Documentation updates for onsite notifications - may need to shuffle this depending on Tom's availability (#48382)  

cc @ericasauv09
