### ISSUE TITLE
My VA: Sprint 86 (11/2/22 - 11/15/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43509]
## Priorities

1. Payments V2 - Address any issues found in QA, Complete Staging Review and any updates that come out of Staging Review, potentially hold UAT go/no go
2. Audit - Continue FE development, implement updates from Midpoint Review
3. Onsite Notifications - Finish Documentation

PTO
- Samara: 11/11 (Federal holiday - Veterans' Day)
- Taylor: 11/11
- Erica: 11/4 & Jury Duty on 11/10
- AJ: 11/4
- Angela: 11/11

## On-site Notifications (#30611)
**PM**
- [x] #45008

**Design**
- [x] #49189 

**FE**
- [x] #43301
- [x] #48382 _from previous sprint_
- [x] #49256

## My VA Payment Info V2 (#43332)
**PM**
- [x] #47869 (#48603)
- [x] #47233
- [x] #47703 _from previous sprint_
- [ ] #45929 _from previous sprint_

**Research/Design**
- [x] #48993

**FE**
- [x] #48792
- [x] #48812
- [x] #48810
- [x] #48809
- [x] #49463

**BE**
- [ ] #49689

## My VA Audit UX Improvements (#41934)
**Design/Research**
- [x] #48706 _from previous sprint_
- [x] #48701 _from previous sprint_
- [x] #49088
- [ ] #48699 
- [ ] #49390

**FE**
- [x] #49513 
- [x] #48705 _from previous sprint_
- [x] #47523 _from previous sprint_

## My VA 2.0 General Enhancements (#31611)
- [ ] #47956
- [ ] #41202

**Comment by ericasauv09** [comment]
[Samara's Sprint Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/my-va/sprints-81-90.md#sprint-86-112---1115)

**Comment by ajakabcin** [comment]
In terms of priorities and order of operations, let's proceed with this plan to start the sprint:

**For design/research priorities, @aagosto90 here's a roadmap to follow:**

1. Wrap up onsite notifications use case documentation and hand off for review (#49189)
2. Audit UX improvements design work (in no specific order): #49088], #48706, and #48701 
3. Review/share audit UX improvement designs with respective teams #48699 
4. Submit research review for payment info v2 (only after staging review is complete and we have the go ahead) #48993 
5. Begin My VA use case documentation #49196 

**For FE, @tmitchellgcio here is your plan:**
1. Review the two data related bugs from payment info v2 QA: #48809 and #48810 (if they are quick to resolve proceed with fixing them, if not touch base with the team in slack for next steps)
2. Fix #48812 
3. Wrap up the health care section UX improvement updates - #48382 , #48705 , #47523 (if you're able to now please try to link the PR to all those since it's one PR across several tickets, thank you!)
4. Analytics implementation/updates and validation on payment info v2 #48792 
5. `isCerner` deprecation + drupal adoption #47956 
6. Pick back up with the audit UX updates - small copy ticket #48704 
7. Onsite notifications code cleanup (lowest priority - may roll to next sprint depending on payment info v2 staging review findings) - #48704 
8. We are also on standby with VAOs waiting for them to give us the go-ahead to remove the feature flap on the next appointments API (Mark did this for us back in the spring - it's done just waiting for the sign to release) - #41202 

cc @ericasauv09
