### ISSUE TITLE
My VA: Sprint 84 (10/5/22 - 10/18/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43507]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Launch Onsite Notifications to 25% and 50%
2. Payments V2 - QA, request analytics, prepare for staging review, begin preparing for privacy review
3. Audit -  begin FE build, Midpoint review prep, research planning

PTO
- Federal holiday: Indigenous People's Day/Columbus Day 10/10 (Samara out)
- Erica: 10/5-10/7
- AJ: 10/10
- Taylor: 10/10
- Angela: 10/13

## On-site Notifications (#30611)
**PM**
- [x] #43281 _from previous sprint_
- [x] #43288 _from previous sprint_
- [ ] #43293 _from previous sprint_

**FE**
- [x] #43288 _from previous sprint_
- [ ] #43293  _from previous sprint_

## My VA Payment Info V2 (#43332)
**PM**
- [x] _Internal testing_
- [x] #45966 _from previous sprint_
- [ ] #45929 _from previous sprint_
- [ ] ~#45967~
- [ ] ~#47615~
- [ ] ~#47703~ 

**Research/Design**
- [x] #47763
- [x] #47887

**FE**
- [ ] ~_Any follow up tickets from QA_ (for reference: [QA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47208))~
- [x] #47764
- [x] #47902
- [x] #47868
- [x] #45453
- [x] #48195
- [x] #48236

**BE** 
- [x] #47440

## My VA Audit UX Improvements (#41934)
**PM**
- [ ] #47453
- [ ] #47616

**Design/Research**
- [x] #47314 _from previous sprint_
- [x] #47668 _from previous sprint_
- [ ] #47453 _from previous sprint_
- [x] #47313 47313

**FE**
- [ ] #47522 

## My VA - Health care + Cerner facility updates (#39141)
**FE** 
- [x] #46419

**Comment by ericasauv09** [comment]
[Samara's Sprint Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/my-va/sprints-81-90.md#sprint-84-105---1018)

**Comment by ajakabcin** [comment]
@aagosto90  and @tmitchellgcio, because we have a lot of moving parts and some dependencies this sprint, I'm highlighting the order of operations for you two here:

**For Taylor**
1. Close out [47868](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47868) (payment info v2 bug) and [45453](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45453) (403 error)
2. [46419](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46419) - Drupal discovery + isCerner
3. [47764](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47764) - updates to copay card design and logic (dependent on Angela design work - won’t be ready until tomorrow afternoon at the earliest)
4. [47522](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47522) - Claims and appeals updates (Audit UX)
 _If time permits and documentation is ready: move on to Health care section updates ([47523](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47523) Audit UX)_

**For Angela**
1. [47763](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47763) - Update copay designs asap so Taylor can do the FE work
2. [47453](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47453) - Content review of Audit UX improvements
3. [47314](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47314) - Audit UX improvements FE documentation (health care > Education > etc.)
4. [47668](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47668) - design updates on LOA1 cta on identity verification (audit UX)

Additionally, if there are any findings from QA we'll need to triage and prioritize accordingly.

cc @ericasauv09 and @Samara-Strauss
