### ISSUE TITLE
Update current education pages to point to new modernized rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43502]
## Issue Description
In a previous ticket we audited our education pages (both benefit detail pages and R&S articles) for links to legacy rates pages as well as one-off mentions of rates. Now that we're publishing our modernized rates pages, we need to implement these changes and updates. 

For some, we will just need to change the link, but for others we may need to rewrite content. 

For background, the original ticket of the audit is #42900. 

These changes can't go live until we've published the new rates pages. We can make the updates and save as draft until then. 

Here is the list of pages we found that need to be worked on:

**Education Rates mentions and links:** 

- [x] https://www.va.gov/education/benefit-rates/
**Note from Beth:** A new page appears to have been [created in drupal](http://preview-prod.vfs.va.gov/preview?nodeId=1007). We'll want to copy and paste the content from that page into the [existing rates landing page](http://preview-prod.vfs.va.gov/preview?nodeId=938). DONE

- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/
**Note from Beth:** Replace link to legacy rates page with a link to the new MGIB-AD rates page.

- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance/
 (Doesn’t link to legacy table, but gives a $$ figure)

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/
(Doesn’t link to legacy table, but gives a $$ figure)

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/co-op-training/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/

- [x] https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/

- [x] https://www.va.gov/education/survivor-dependent-benefits/

- [x] https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/
(Doesn’t link to legacy table, but gives a $$ figure)

- [x] https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/

- [x] https://www.va.gov/education/other-va-education-benefits/stem-scholarship/

- [x] https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/
(Doesn’t link to legacy table, but gives a $$ figure)

- [x] https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/buy-up/

 **R&S pages**

- [x] https://www.va.gov/resources/gi-bill-and-other-va-education-benefit-payments-faqs/

- [ ] https://www.va.gov/resources/how-va-education-benefit-payments-affect-your-taxes/
(Maybe? This discusses $$, but it doesn’t link to a legacy table)

- [x] https://www.va.gov/resources/how-we-determine-your-post-911-gi-bill-coverage/

- [x] https://www.va.gov/resources/will-i-have-to-pay-back-the-gi-bill-benefits-i-used-if-i-fail-a-class/
 (Under related information) 

- [x] http://preview-prod.vfs.va.gov/preview?nodeId=44718 (draft)

## Tasks
- [x] Update links
- [x] Identify duplicate content that we can delete (and rewrite surrounding text) 
- [x] Review (Laura)
- [x] OCTO-DE review of content changes (Beth)
- [x] Final copyedit with pre-publishing checklist (Megan)
- [x] Publish pages (Megan)

## Acceptance Criteria
- [x] All links to education rates on site now point to our modernized pages 
- [x] No education pages have specific rates mentioned besides the rates pages.

**Comment by katherine-fung** [comment]
Can we confirm the groups that are eligible for tutorial assistance? These 2 pages ([page 1](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000073491/Part-3-Chapter-10-Tutorial-Assistance?query=tutor%20assistance) and [page 2](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000073801/Sub-Chapter-10-Tutorial-Assistance-Program?query=tutor%20assistance))
say that people receiving benefits under Chapters 30, 32, 33 and 35 are eligible. 

I updated the page to include "spouses and children getting benefits through... DEA" and "spouses and children getting transferred benefits." Is this accurate? Are any of these groups also eligible? 
- active service members 
- spouses and children getting benefits through the Fry Scholarship 

Do we want to be more general and say "Qualified dependents" instead of specifying the programs?

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thanks for your work on this so far. Let's check in next week when you all are back from your retreat about doing a working session once or twice to go through the pages and look at what you're proposing would change.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung There is content on some of these education pages that's now covered in the new rates pages instead. This ticket doesn't specifically identify this task. Can you add that in?: identify duplicate content that you can delete (and rewrite surrounding text).

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO, I will!

**Comment by katherine-fung** [comment]
Hi @RLHecht, as part of this ticket, I updated the Chapter 35 rates page to show the new 2023 rates: 

http://preview-prod.vfs.va.gov/preview?nodeId=5496 
(source: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100122.asp) 

I also cloned the 2022 page so we have one modernized past rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=49484

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

Thanks for reviewing these pages with me today! I made updates to most of the pages based on what we discussed. 

Here are 2 pages that need more review from you: 

- https://prod.cms.va.gov/node/924/revisions/view/304347/684493/visual_inline - This is the page that didn't really have any content. I linked to the revision comparison so you can see the proposed changes. 

- https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ - I've updated the links on this page, but wanted to merge and clean up the "Get more information" section and the "More helpful information section." I just wanted to check with you about this, because there's a paragraph "GI Bill® is a registered trademark..." Do we need to keep this?

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I'll just make several comments in this ticket as I have time to respond to your questions.

1/ Independent and distance learning. I like the way you brought this page in alignment with the layout and text on our other similar pages. But for now, since we don't have time to run it all past SMEs in EDU, let's revert back to the very short page and simply add a link to MHA (the new R&S page that's still in draft form). Go ahead and take out the end of the sentence that talks about 50% of the national average, so end with: "...we'll pay you a housing allowance." 

You can get rid of the link that's live on that page now and replace it with the R&S link.

Thanks!

**Comment by bethpottsVADEPO** [comment]
@RLHecht  For ^^ this above page, Independent and distance learning, would you create a ticket for you to get stakeholder approval of the changes Katherine suggested? You and Katherine can handle this. Start with an email to Tammy, and cc Cinda. Just explain that in the course of the rates work, you noticed that this page didn't have much on it and you'd like to provide some more information to Veterans. You can send them the preview link (and the live page link for reference would probably be helpful). Make sure you say that the updates were pretty straightforward, but you want to have their eyes on it to make sure all the additions are accurate. 

@katherine-fung 
2/ Post-9/11 GI Bill page: I made updates to this page over the weekend. Take a look and let me know if what I did resolves your questions/suggestions or if I missed anything. I did remove a huge block of text that now lives on the MHA page that's in draft (no yet published).

**Comment by katherine-fung** [comment]
Thank @bethpottsVADEPO! 

1. I reverted the "Independent and distance learning" page and added a link for the R&S article for MHA. 

2. Thanks so much for those edits to the Post-9/11 GI Bill page. Based on those changes [and changes to the MGIB pages], I went back to a few of the other pages and added "Other information you may need" link teasers. 

3. I came across a few other things. 
- On the Survivors’ and Dependents’ Educational Assistance page  [https://prod.cms.va.gov/node/950/latest] , there are 2 broken links to learn more about "special restorative training" and "special vocational training." I can't find another page on va.gov that explains either of these programs. Is it ok to remove these broken links from the page without replacing them? We do briefly explain these programs on the DEA page itself. 

Screenshot for reference 
![special restorative training.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/5c5697b8-d784-4ff4-82e9-f86bad53c9c1)

- On the National Call to Service Program page [https://prod.cms.va.gov/node/946/latest]. we may want to remove the link to the PDF about the program in the "How can I get more information?" section. The information in the PDF is already on the page.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thank you for 1/ and 2/

3/ 
- Yes, thank you for removing those links. Are those the other edu pages you worked on a while back that I waiting for my review?
- You can leave that link to the PDF for now.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO  

3/ 
Great, thank you! And no, those broken links have nothing to do with the other pending education pages from a while back at all.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO @RLHecht - 

Here's the link for the past Post-9/11 GI Bill rates page for 2022: 
http://preview-prod.vfs.va.gov/preview?nodeId=49728 

Just a heads up - for the "Past rates" section on this 2022 page, I linked to legacy pages showing rates for the 3 years prior (2018, 2019, and 2020). If we're not linking to legacy pages at all, I can take that section out.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Let's try to find time to check in on all this work either Friday or early next week. You can let me know which day works for you! We'll have to revisit at least this page now that we won't be publishing the monthly housing allowance page: Independent and distance learning. I'll have to catch you up on that!

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! I just sent you a meeting invite for Monday.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @katherine-fung Before we publish these pages (probably not same day as all the rates pages), let's make sure there aren't still any links to the draft R&S MHA page (the one we aren't publishing at this time). If we were linking to it anywhere, we can instead link to the Post-9/11 GI Bill page that has the MHA info. We can jump link to that H2.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO @RLHecht @megzehn, 

These pages are ready for copy edit. 

I double checked the links on the pages. I removed links to the unpublished MHA R&S page from a few pages. I also removed a link to the unpublished DEA vs. Fry R&S page.

**Comment by RLHecht** [comment]
These pages have all been published except for the Independent and distance learning one, which Katherine noted needs to go to stakeholders first. I'll confirm that the jump links are working once the pages are live.

**Comment by katherine-fung** [comment]
I reverted 2 of these pages to draft changes that still need stakeholder approval. 

 - Survivors’ and Dependents’ Educational Assistance page [https://prod.cms.va.gov/node/950]

- VA education benefits for survivors and dependents
 [https://www.va.gov/education/survivor-dependent-benefits/]

**Comment by katherine-fung** [comment]
Hi @RLHecht and @laurwill, 

@bethpottsVADEPO and I discussed the "Independent and distance learning" page last week. We're going to send it to stakeholders after the tool pages and new rates pages are done, maybe in January. 

Could we start a new ticket for getting changes to the independent and distance learning approved? 

This is the live page: 
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/ 

This is the draft: https://prod.cms.va.gov/node/924/revisions/684493/view 

The changes add more information and make the page match the format of other education pages. 

If this page is the only issue holding up this larger education pages ticket, we can make a new ticket for the independent and distance learning page, and close this ticket.

**Comment by RLHecht** [comment]
Thanks @katherine-fung I opened up a new ticket #50883 for the independent and distance learning page. I'll close out this ticket!
