### ISSUE TITLE
[BE] Make Doctor's Name and Type of Care Fields Available to Frontend

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43513]
## User Story
As a Veteran, when I am using Patient Pre-Check-in to complete pre-check-in tasks for my appointment, I would like to see the name of the Doctor I will be seeing (or speaking with) for my in-person or phone appointment so that I understand to whom I will be speaking.

## Background info
Refer to [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/telephone/research-findings.md#9-veterans-suggested-a-variety-of-features-or-appointment-information-to-add-to-the-experience)

## User Workflow
- Given I
    - Have verified my identity in the Pre-Check-in application and completed contact confirmation,
- When I
    - See my list of appointments for today
- Then I
    - See the name of the Doctor and the Type of Care for my in-person or phone appointments

## Tasks
- [ ] [BE] Make Doctor's Name and Type of Care Fields Available to Frontend

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
Will need CHIP work @loripusey

**Comment by loripusey** [comment]
talk to Christ horton about this one
@loripusey
