### ISSUE TITLE
Audit Staging Review issue tickets with "Other" category

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43517]
## User Story
As a VFS team member, I want to know the complete list of VA.gov Experience Standards that I must adhere to so that I can ensure that my product is ready for Staging Review.

As a Governance team member, I want to make sure the VA.gov Experience Standards list is as accurate as possible so that when I find an issue during a Staging Review, I know what VA.gov Experience Standard it is in violation of and no longer have to use the "Other" category.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
As of 6/28/2022, the Governance team has flagged [26 issues ](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3ACC-Dashboard+label%3ACCIssue00.00) with the Category of "Other" stating the issue, "No VA.gov Experience Standard for the issue found." This category/issue is used as a catch-all so that Governance team members can still flag their concerns at a Staging Review, even if there isn't a VA.gov Experience Standard that fits the issue found perfectly.

However, since 26 issues have accumulated, it would make sense that we now audit those issues to see if:

1. They could've been mapped to a more appropriate, already documented VA.gov Experience Standard, OR
2. There is a gap in the VA.gov Experience Standards that must be addressed (AKA create a new standard)

## Impacted Artifacts
[Platform Website: VA.gov Experience Standard](https://vfs.atlassian.net/wiki/spaces/CC/pages/1683980311/VA.gov+experience+standards)
[Drafting Template Source](https://docs.google.com/spreadsheets/d/1IkIX7CgbFneFvlia1r9mYD8QU7uML5HWILkM7qsxizs/edit#gid=333168944)

## Tasks
- [x] Create a [working document](https://docs.google.com/spreadsheets/d/1A9pw-k4AKErWQhFJjBDmKgCfH80lrFvHLyQpnE1ByO0/edit#gid=0) to review the "Other" issues. Capture the following:
   - GitHub issue #
   - Date of ticket
   - Governance team reviewer
   - Governance team reviewer practice area
   - 1 sentence summary of issue found
   - Possible VA.gov Experience Standard (if applicable)
- [x] Share on #platform-governance-team Slack channel and ask for team review. If your practice area opened the "Other" issue, confirm the following:
   - 1 sentence summary is accurate
   - If there is a Possible VA.gov Experience Standard, confirm that the summary and Possible VA.gov Experience align. If not, comment on the ticket with your thoughts/opinion
   - If there is NOT a Possible VA.gov Experience Standard, review the VA.gov Experience Standards list and validate that there is not a Va.gov Experience Standard that aligns with the summary. If there is a VA.gov Experience Standard that aligns, comment on the ticket with your thoughts/opinion
- [x] If any "Other" issues _almost_ align to the existing VA.gov Experience Standard, comment in the working document. It may be best to modify the existing VA.gov Experience Standard.
- [x] If anything needs OCTO escalation, share on #platform-collaboration-cycle Slack channel
- [x] Once team is in agreement for the issues with aligned Possible VA.gov Experience Standards, update the labels on the ticket:
   - remove label `CCIssue00.00`
   - add the appropriate new label `CCIssue.XX.YY`per [VA.gov Experience Standards labels guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket#AnatomyofaStagingReviewIssueticket-VA.govExperienceStandardslabels)
   - Update the Platform Issue section in the ticket with the appropriate new name per [Platform Issue guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket#AnatomyofaStagingReviewIssueticket-PlatformIssue)
   - Comment on the ticket:

> This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssueXX.YY "Name of issue". No VFS action is needed.
- [x] If there is no Possible VA.gov Experience Standard listed for the issue, then it is likely than a new VA.gov Experience Standard will be created. No action is needed on the Github ticket. Create individual issue tickets (for Governance team to address) for each new VA.gov Experience Standard and link them all below: 

   - #45369
   - #45343
   - #45371
  - #45372
Note: it is possible that there may not need to be 1 new standard for each issue that doesn't currently have a VA.gov Experience Standard to map back to. 2 "Other" issues may have the same summary which would mean only 1 new issue ticket is needed for Governance team.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] We have reviewed all "Other" tickets and either reassigned them to an appropriate VA.gov Experience Standard or created a ticket in our backlog for the creation or update of a new VA.gov Experience Standard.
- [x] VFS teams are notified if/when their existing issue tickets have been reassigned  a new VA.gov Experience Standard

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@allison0034 User Story and AC have been met.  Peer review complete.
