### ISSUE TITLE
Create a main landing for Comm. Playbook

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43519]
## Issue Description
Create a "cover page" for Playbook (a landing / intro page) instead of the current confusing space on arrival

[This](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1962606620/Platform+communications+playbook) is currently the closest thing to a landing.

Also: potentially use this "cover page" as a shareable resource for other teams to use for their own offerings.

## Story:  
As a user who thinks they may need to communicate something, I need a landing that orients me and walks me through the main communication checkpoints, culminating in an offered template so that I can easily create a Communication Plan.

**Format of Unified landing:** (established in #43882 per Team Discussion)
Greeting
Explanation of why there's a playbook and what it should accomplish
Brief sections on What, Where and When to communicate
"I Need To..." template options that link out to respective templates. (guidance would be for user to copy template to their space and then customize).

---
## Tasks
- [x] Determine what the design of page should be
- [x] Create MVP of landing

## Acceptance Criteria
- [x] MVP of landing is created.

**Comment by steel36** [comment]
Reviewed initial format of page.  Dan and I discussed potential directions to consider, particularly trying to streamline it.  There are questions as to whether there should be supplemental pages to address those who may have additional desire for insight.

**Comment by twoangstroms** [comment]
Also moved child pages in the "Comm Playbook..." child pages. Will make two draft pages ("Test") to see how the different models work out in practice.

**Comment by twoangstroms** [comment]
Created a draft page centered around use cases/user stories. First building cases/stories and structure; second step is to fill in specifics of channels and unique processes per case/story: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2273542145/Welcome+to+the+Platforms+Communication+Playbook+User+Story+Organization

**Comment by twoangstroms** [comment]
Working copy of revision after workshop: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2277277697/Welcome+to+the+Platforms+Communication+Playbook+Revision

**Comment by twoangstroms** [comment]
Ready for review (with a few comments already) at https://vfs.atlassian.net/wiki/spaces/SDT/pages/2277277697/Welcome+to+the+Change+Communication+Playbook+Revision
