### ISSUE TITLE
[BE] Make Doctor's Name and Type of Care Fields Available to Frontend

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43512]
## User Story
As a <user>, I want to <do something> so that I can <accomplish a goal>

## Tasks
- [ ] [BE] **_insert backend  work_**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
