### ISSUE TITLE
My VA: Sprint 87 (11/16/22 - 11/29/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43510]
## Priorities

1. Payments V2 - complete UAT, address any findings, discuss what documentation needs to be updated; stretch goal launch go/no-go and launch to 25%
2. My VA Audit - Finish FE dev, analytics planning, document test cases 

PTO
_Federal holiday 11/24 - Thanksgiving_
- AJ: 11/18, 11/23, 11/25
- Angela: 11/23, 11/25
- Taylor: 11/20 -11/27
- Samara: 11/23 - 11/25
- Erica: 11/25

## My VA Payment Info V2 (#43332)
**PM**
- [ ] #45929 _from previous sprint_
- [x] #47236 
- [x] #47237

**Research/Design**
- [x] #49386
- [ ] #49387

**FE**
- [x] _Address any findings from UAT_
- [x] #49737
- [ ] #49398
- [x] #49663
- [x] #47237

**BE**
- [x] #49663
- [x] #49689

## My VA Audit UX Improvements (#41934)
**PM**
- [ ] #49534
- [ ] #49535

**Design/Research**
- [ ] #48699 _from previous sprint_

**FE**
- [x] #49514 
- [ ] #49558
- [ ] #47520
- [ ] #47521
- [ ] #47683 
- [ ] #49094

## On-site Notifications (#30611)
**PM**
- [x] #48644

## My VA 2.0 General Enhancements (#31611)
- [x] #47956 _from previous sprint_
- [ ] #41202

**Comment by ajakabcin** [comment]
Order of operations for the sprint :) 

**@aagosto90 for Research & Design**
1. Run UAT on payment info v2 (+rough synthesis, does not need to be perfect): 49386 & 49387
2. Review audit work with other teams: 48699
3. Wrap up saved apps designs: 49390
4. Assist with my va test case documentation as needed
5. My VA use case documentation as time permits

**@tmitchellgcio for FE**
1. Finish isCerner drupal migration: #47956 
2. Resolve Payment info v2 bug: #49398
3. Assist with UAT (ongoing throughout the sprint): #49737
4. _Address any findings in UAT_
5. Resume audit implementation:
 - copy updates #49514 and #49558
 - saved apps section #47520
 - explore va benes section #47521
 - education section #47683
 - full page error #49094
6. _Waiting for go-ahead from VAOs on next appointments API: #41202_
