### ISSUE TITLE
Adapt the templates used by RTT and DST into a more universal template

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43526]
## Issue Description
Review the templates we've seen in interviews and consulting work, and use the checklists as a starting point to shape into the needed CCP templates

Perhaps starting w/ Product/Process template, then removing non-needed items to create Info. Update version.

template [in development](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2185789450/Communication+Plan+Template)
[example](https://vfs.atlassian.net/wiki/spaces/FTT/pages/2172715060/Communication+Plan+-+Migrate+Primary+Branch+Names+in+Vets-Website+Content-Build+to+Main+39544) of completed checklist/template

## Problem Statement
Due to a receiving guidelines and principles instead of a specific plan format, each team is communicating in various means via various channels.  Our bet is that a template can create a universal format that teams can use to aid in consistency of communications, as well as becoming a repository (Via the Comm. Plan) for them to keep track of communication to-dos.

## Tasks
- [x] Determine what needs to be in the template
- [x] Prepare the Structure and Content for a Process or Product Change

## Acceptance Criteria
- [x] shareable template mvp exists for a Product or Process change

**Comment by twoangstroms** [comment]
@steel36 Could you add a link to the "checklist" above in the ticket, please?

**Comment by twoangstroms** [comment]
I now see a link in h2 or h3 "reference checklist" with the last word being a link, but that link just reloads the ZenHub ticket? Blaming the tool here.

**Comment by steel36** [comment]
Ugh.  There, now we should have both the stripped template and the "inspiration"

**Comment by steel36** [comment]
Spent some time working on the template this morning to get it to a better state.

**Comment by steel36** [comment]
Decision was made to not include Informational Changes, and thereby, no 2nd template is necessary anymore.
