### ISSUE TITLE
Where should the updated playbook live?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43529]
## Issue Description
Where should the updated playbook live? (who needs it and where makes the most sense)

## Problem Statement
We need to make sure we understand and agree who the primary or secondary users of the CCP will be so as to place it in a place that is logically accessed and accessible.

## Tasks
- [x] Determine who potential consumers are
- [x] Determine where the playbook should reside

## Acceptance Criteria
- [x] Location is determined

## Next Steps
In order to keep the Change Playbook and Principles, we intend to place them in separate locations, based on likelihood of engagement:
1) Change Communication Playbook:  Prod. Mgmt. Comm. of Practice / (existing Playbook landing)
2) Platform Communication Principles:  About the Platform / How we work /
