### ISSUE TITLE
Add playbook to Platform Initiative Template

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43533]
## Issue Description
Add direction to use CCP to Platform Initiative Template (per Andrea)

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-initiative.md

## User Story
As a Platform team member, I need the CCP to be included in the PIT so that I'm aware that it should be used for communicating change when I am working on an Initiative.

## Tasks
- [x] Learn what is needed to get playbook into PIT
- [x] Execute steps (once Playbook has been launched)

## Acceptance Criteria
- [x] Playbook is available on PIT

**Comment by tayism** [comment]
To make a change to the [Initiative Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-initiative.md), one simply needs to make the change and merge it into the main page (Github)

Now begs the question: Where do we want to place the CCP on the Initiative Checklist, and what should it say? (TBD)
