### ISSUE TITLE
Internal - Authenticated Exp - Edge Case Dashboard

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43535]
## Issue Description
This ticket is for internal team communications and tracking of work for the [Authenticated Experience Edge Case Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31302) request.

---
## Tasks

- [x] Create new datasets/view (Chloe)
- [x] Create the dashboards based on approved [mock up](https://github.com/department-of-veterans-affairs/va.gov-team/files/8993596/MyVA.Edge.Case.Dashboard.Mockup.pptx) (Pavan)
- [x] QA data and cards (Jonathan)

## Acceptance Criteria
- [ ] When the dashboard is complete
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
## Data QA
Created 3 new views in the vsp_sites folder in BigQuery. QA was conducted across full range of dates.

_Reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the count of distinct hit IDs. 

BQ view | Users & comparisons | API requests | Nav events by LOA
 -- | -- | -- | --
Row total | 36 | 26,917 | 37,080
Unique IDs | 36 | 26,917 | 37,080

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  'Users by month' as bq_view,
  count(*) as total_rows,
  count(distinct date) as total_uuid
from `vsp-analytics-and-insights.vsp_sites.vw_myva_users_comparisons`

union all

select 
  'API requests' as bq_view,
  count(*) as total_rows,
  count(distinct concat(date, api_type, api_outcome, device_category, browser)) as total_uuid
from `vsp-analytics-and-insights.vsp_sites.vw_myva_api_requests`

union all

select 
  'Navigation clicks' as bq_view,
  count(*) as total_rows,
  count(distinct concat(date, login_status, device_category, browser)) as total_uuid
from `vsp-analytics-and-insights.vsp_sites.vw_myva_nav_clicks_by_loa`
```
</details>

### Nulls
✅ **Passed!** No nulls across all data sources.

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  'Users by month' as bq_view,
  col_name, 
  count(1) as total_nulls
from `vsp-analytics-and-insights.vsp_sites.vw_myva_users_comparisons` t,
unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
group by col_name 

union all

select 
  'API requests' as bq_view,
  col_name, 
  count(1) as total_nulls
from `vsp-analytics-and-insights.vsp_sites.vw_myva_api_requests` t,
unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
group by col_name 

union all

select 
  'Navigation clicks' as bq_view,
  col_name, 
  count(1) as total_nulls
from `vsp-analytics-and-insights.vsp_sites.vw_myva_nav_clicks_by_loa` t,
unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
group by col_name 
```
</details>

### Completeness
✅ **Passed!** Checked row distributions date grouped by month. There are no values for API data before June 2021, but this corresponds with data in GA. Events seems to have been created after this point.

<details> 
  <summary>Expand for test code</summary>

```sql
with users as (
  select 
    year,
    month,
    count(*) as user_rows
  from `vsp-analytics-and-insights.vsp_sites.vw_myva_users_comparisons` 
  group by year, month
),

apis as (
  select 
    year,
    month,
    count(*) as api_rows
  from `vsp-analytics-and-insights.vsp_sites.vw_myva_api_requests`
  group by year, month
),

nav_events as (
  select 
    year,
    month,
    count(*) as nav_rows
  from `vsp-analytics-and-insights.vsp_sites.vw_myva_nav_clicks_by_loa` 
  group by year, month
)

select
  u.year,
  u.month,
  user_rows,
  api_rows,
  nav_rows
from users u
left join apis using (year, month)
left join nav_events using (year, month)
order by year, month

```
</details>

## Accuracy tests
QA was conducted against June 2022 data in GA.

_Reference: [QA for standardized dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents); [WIP Content QA spreadsheet](https://docs.google.com/spreadsheets/d/10ntfDxR2OKxPJ0FI6gCzoyHu1XfbW1-uKKSH1F8ZfOc/edit#gid=0)_


### Users and comparisons

Metric | Technical definition | Pass/Fail
-- | -- | :--: 
MyVA users (logged in) | Distinct count of users with LOA status is 1 or 3 where pagepath contains '/my-va' | ✅
MyVA users (all) | Distinct count of users where pagepath contains '/my-va' | ✅
Homepage logged-in users | Distinct count of users with LOA status is 1 or 3 with a pagepath = 'www.va.gov/' | ✅
All VA.gov users | Distinct count of users across website (no conditions) | ✅

### API requests

Metric | Technical definition | Pass/Fail
-- | -- | :--: 
Total events (top 3 event actions) | Total hits for most common API calls | ✅
Unique events (top 3 event actions) | Total sessions for most common API calls | ✅
Events by device type | Total and unique hits by device_category | ✅
Events by browser | Total and unique hits by top 3 browser types | ✅


### Navigation events by LOA

Metric | Technical definition | Pass/Fail
-- | -- | :--: 
Total events - logged in | Total hits where LOA is 1 or 3 and event_action = 'Navigation - Header - My VA - https://www.va.gov/my-va/' | ✅
Unique events - logged in | Total sessions where LOA is 1 or 3 and event_action = 'Navigation - Header - My VA - https://www.va.gov/my-va/' | ✅
Total events - unauthenticated | Total hits where no LOA present and event_action = 'Navigation - Header - My VA - https://www.va.gov/my-va/' | ✅
Unique events - unauthenticated | Total sessions where no LOA present and event_action = 'Navigation - Header - My VA - https://www.va.gov/my-va/' | ✅
Events by device type | Total and unique hits by device_category | ✅
Events by browser | Total and unique hits by top 3 browser types | ✅

**Comment by chloedotbrown** [comment]
## DOMO datasources
In general, I've given you more fields than were asked for, in case metric logic needs to change. However, I've updated the [KPI discovery spreadsheet](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=871242321) to make suggested beast mode calculations clear. 

If there's anything else you need, please let me know!

- **[BQ - MyVA users, comparisons by month](https://va-gov.domo.com/datasources/414f6558-2f16-4327-815e-7f32acfacd10/details/data/schema)**: Updates 1st of every month. View has filter to remove incomplete months if manually run min-month.
- **[BQ - MyVA API requests by status](https://va-gov.domo.com/datasources/ba47c9e9-61c8-4823-8867-dd80b55c7831/details/data/table)**: Updates every day.
- **[BQ - MyVA navigation clicks by LOA](https://va-gov.domo.com/datasources/f1593f5f-ea15-483d-ae63-80faca1c92ce/details/overview)**: Updates every day.

**Comment by pavanhothi** [comment]
@jonathan-epstein13 the following cards are ready for your QA while I complete work on some remaining cards:

- https://va-gov.domo.com/kpis/details/1781541056
- https://va-gov.domo.com/kpis/details/91399922
- https://va-gov.domo.com/kpis/details/1239321034
- https://va-gov.domo.com/kpis/details/1939877365
- https://va-gov.domo.com/kpis/details/436195540
- https://va-gov.domo.com/kpis/details/453630602
- https://va-gov.domo.com/kpis/details/1468166493

Please let me know if you have any questions. Thank you!

**Comment by jonathan-epstein13** [comment]
@pavanhothi thank you! I will take a look at these today.

**Comment by pavanhothi** [comment]
@jonathan-epstein13 here is the next batch of cards ready for your QA. I have 1 final card that I am completing and will have over to you shortly as well:

- https://va-gov.domo.com/kpis/details/1440312171
- https://va-gov.domo.com/kpis/details/407899653
- https://va-gov.domo.com/kpis/details/484982737
- https://va-gov.domo.com/kpis/details/113285425
- https://va-gov.domo.com/kpis/details/369117325
- https://va-gov.domo.com/kpis/details/715364496
- https://va-gov.domo.com/kpis/details/554570364
- https://va-gov.domo.com/kpis/details/256470240
- https://va-gov.domo.com/kpis/details/30512509

Please let me know if you have any questions. Thank you!

**Comment by pavanhothi** [comment]
@chloedotbrown Here is the [dataset request doc](https://docs.google.com/spreadsheets/d/1uv9aAd9_abMFXEAWrCO2kRSSkEmfIU2IIZT8_j9x774/edit#gid=0) for the final data source needed for the last MyVA card. Thank you in advance for your help and work on this! Please let me know if you have any questions at all.

**Comment by chloedotbrown** [comment]
Hey @pavanhothi - it seems like the data you need is actually in the existing dataset already? I'm guessing this request is based off the [KPIs section](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign#okrs--kpis) of the MyVA 2.0 Project Outline - unfortunately, since these are paraphrases of event actions, I can't be 100% sure of the match (the totals in the outline tables also don't exactly match the GA reports linked).

I'd recommend you reach out to AJ and the MyVA team to verify the full event actions they mean. I've created two resources for you - 1) a table of [my best guess](https://docs.google.com/spreadsheets/d/1uv9aAd9_abMFXEAWrCO2kRSSkEmfIU2IIZT8_j9x774/edit#gid=0) at the matching events on the 2nd tab of your request and pasted below and 2) a [searchable table card](https://va-gov.domo.com/kpis/details/692969475) with a quick filter so you can more easily check what's already in Domo.

Event requested | Event Action | In current data?
-- | -- | :--:
View claim | Dashboard - Navigation - View Button - View Claim | :white_check_mark:
Manage all your claims and appeals | Dashboard - Navigation - View Link - View All Your Claims and Appeals | :white_check_mark:
Schedule and view your appointments | Navigation - Link List - Health care - Schedule and view your appointments | :white_check_mark:
You have an unread messages | Navigation - Link List - Health care - You have n unread messages | :white_check_mark:
Refill and track your prescriptions | Navigation - Link List - Health care - Refill and track your prescriptions | :white_check_mark:
View all payments | Navigation. - Link List - Benefit payments and debts - View your payment history | :white_check_mark:
View all debts | Navigation - Alert Box - Link Click - warning - - (not set) - Manage your VA debt | :white_check_mark:
Manage direct deposit | Navigation - Link List - Direct deposit - Manage your direct deposit | :white_check_mark:
Request travel reimbursement | Navigation - Link List - Health care - Request travel reimbursement" | :white_check_mark:
(not included in request, but has high totals) | Navigation - Link List - Claims and appeals - Check your claim or appeal status | :white_check_mark:

**Comment by pavanhothi** [comment]
@chloedotbrown thank you for this info! I will reach out to AJ and MyVA team to confirm the full even actions they mean.

**Comment by jonathan-epstein13** [comment]
@chloedotbrown @pavanhothi 

Data QA is attached [here](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=1399156407). 
I made some notes and might need a second pair of eyes on some segments/reports, just to double check. Let me know what you both think.

Right now, I have a couple blockers on the following cards:
[MyVA search rankings](https://va-gov.domo.com/kpis/details/407899653) here is the [segment](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w177519031p176188361/_u.date00=20220601&_u.date01=20220630&_.useg=userXbupxiqOT8avTArkLJc7ow&explorer-table-dataTable.sortColumnName=analytics.searchUniques&explorer-table-dataTable.sortDescending=true&explorer-table.plotKeys=%5B%5D/) I was able to create, but number's don't match up on my end.
[VA.gov search rankings ](https://va-gov.domo.com/kpis/details/1440312171) here is the [segment ](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w177519031p176188361/_u.date00=20220601&_u.date01=20220630&_.useg=builtin1/) I was able to create, but number's don't match up on my end.

These might need to be done in BQ, which I'll check as well. If there is something I am missing, please let me know.

**Comment by chloedotbrown** [comment]
Hi @jonathan-epstein13 ! I've added notes in the far right column of your spreadsheet, but I'll add quick summaries below so there's a record here too. 

- **Count vs. Sum** - Given how the data is structured, all the cards you flagged with count vs. sum issues should be changed over to sum. For most if not all of these sets, data is being aggregated when we bring it into Domo. Therefore, the `COUNT()` function is just telling you how many rows there are. There is really no reason for us to _**ever**_ use the out-of-the-box count function in Domo. If we're working with event-level data, we should still be creating  a `COUNT(DISTINCT)` Beast Mode as a fail-safe. For anything coming in counted already, we should be summing those totals to get meaningful information. Jonathan - can you go ahead and make the changes wherever it's needed?
- **Search ranking comparisons** - We can actually do this without BQ, but with some different reports! The standardized search data this is based on is actually created from `event_actions`, not the regular "search term" data. This allows us to limit by type of search ("All VA.gov" vs. "Resources & Support," etc.) and whether or not typeahead was enabled. Also, you'll want to filter by the `event_label` so that you're only getting "view_search_results" and not counting the events where someone clicked on a link. I've made two reports and skimmed them - totals and order do seem to match the last month of data, but please go ahead and give them a closer read! Remember, GA totals may be a little lower, since there are usually a couple "Type Ahead Disabled" variations getting added to the search term totals.
  - [All VA search rank report ](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220701&_u.date01=20220731&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Search%20Results%20Returned%20~~%20Type%20Ahead%20(Enabled%7CDisabled)%20~~%20All%20VA.gov%20~~%22,0%5D,%5B0,%22analytics.eventLabel%22,%22EQ%22,%22view_search_results%22,0%5D%5D&explorer-table.secSegmentId=analytics.eventLabel&explorer-table.rowCount=50&explorer-table-dataTable.sortColumnName=analytics.uniqueEventsTrue&explorer-table-dataTable.sortDescending=true/)- (still unsampled) filters for All VA.gov search events of both Type Ahead statuses, view results event label only.
  - [MyVA search rank report](https://analytics.google.com/analytics/web/?authuser=0#/savedreport/gQSgAikUR7SH6_V_z4m4aA/a50123418w177519031p176188361/_u.date00=20220701&_u.date01=20220731&_r.dsa=1&2570-table.plotKeys=%5B%5D&2570-table.rowStart=0&2570-table.rowCount=25&_.advseg=&_.useg=&_.sectionId=/) - (custom report) filters for All VA.gov search events of both Type Ahead statuses, view results event label only AND had to occur on a page with a URL that contains "www.va.gov/my-va/"

If I've missed any questions or you have more, feel free to reach out!

**Comment by jonathan-epstein13** [comment]
Thank you for the feedback @chloedotbrown. I'll make those changes accordingly and post it here.

**Comment by pavanhothi** [comment]
@jonathan-epstein13 [here](https://va-gov.domo.com/kpis/details/524427146) is the final card for you to QA. Please let me know if there are any questions or issues with this card, or any of the previously completed cards as you are wrapping up your QA. Thank you for all your help on this!!

**Comment by jonathan-epstein13** [comment]
For internal reference: QA is complete [here ](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=1399156407)

**Comment by michelle-dooley** [comment]
Great, thanks @jonathan-epstein13 !!  @pavanhothi - please complete the dashboard set  up now.

**Comment by pavanhothi** [comment]
@jonathan-epstein13 @michelle-dooley [Here](https://va-gov.domo.com/page/1167851935?userId=850638298) is the link to the completed MyVA dashboard, ready for design QA. Please let me know if there are any questions. Thank you!

**Comment by michelle-dooley** [comment]
@pavanhothi - I completed the first round of QA.  Only found a couple things, see [Design QA worksheet](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=1373940932)

One thing I also noticed was that the date ranges were inconsistent between cards.  For example MyVA users:  Jul '19 - Jul '22 and % Successful GETs:  Jul '21 - Aug '22.  Not sure if that is a data constraint?  I noted the cards with different date ranges and what they are for reference under the QA table.

**Comment by michelle-dooley** [comment]
@pavanhothi - do you think you will be able to make these updates/explanations before Wednesday?  Would really like to close this one as part of current sprint.

**Comment by pavanhothi** [comment]
@michelle-dooley I have the following updates/explanations based on the QA:

- The titles of the cards always appear on all our dashboards when hovering over them, so this is fine
- Key GETS filter card interaction has been fixed so that the chart changes when selecting a filter from the drop down
- MyVA search rankings and VA.gov search rankings cards now have date ranges added (although due to the search ranking nature of the card, a "previous month" date filter is on both cards)
- Added not-current-month filters to the Medallia (user satisfaction) cards
- Some of the cards with date ranges as mentioned in QA do have different date ranges, but this is due to the use of different datasets with differing time periods of data across the cards on the dashboard

**Comment by michelle-dooley** [comment]
Great, think we are good on Design QA!!
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Test | Expected Behavior | Actual Behavior | Pass/Fail
-- | -- | -- | --
Dashboard title | Text fully readable, without errors |   | 🟢 PASS
Date filter | Every chart gets filtered for date and group by settings are changed |   |  
Section titles | Every section title & subtitle are spelled correctly |   | 🟢 PASS
Section resources | Links to How-to Guide + Data Dictionary (if available) |   | 🟢 PASS
Chart titles | Every chart title is fully readable, without errors, relevant to chart |   | 🟢 PASS
Chart descriptions | All chart descriptions are disabled, so nothing appears when hovering over title |   | 🟢 PASS
Hover text | All hover text "makes sense" and is spelled correctly |   | 🟢 PASS
Annotations | Every annotation "makes sense," is free of errors, and visible within text box |   | NA
Filter cards | Filter cards are easy to read and use |   | 🟢 PASS
Text box formatting | Every annotation and section title box shows all text, does not generate scroll bar |   | 🟢 PASS
Card interactions – filters | Clicking data point does not filter other cards |   | 🟢 PASS
Card interactions – card detail | Chart title opens card in new tab |   | 🟢 PASS
Card drillpaths | Card detail view filters to correct drillpath _(if using)_ |   | 🟢 PASS
Display settings – date units | Date grouping ("by week/month") appears under each title |   | 🟢 PASS
Display settings – multi-value gauges | Directionality of colors in period-over-period comparison makes sense |   | 🟢 PASS
Display settings – summary numbers | All non-multivalue gauge charts without a date axis show date range in summary number |   | 🟢 PASS
Related cards | In card detail view, all related card previews have been deleted |   | 🟢 PASS
Appendix | No charts or notecards appear in appendix below dashboard |   | 🟢 PASS


</body>
</html>

**Comment by chloedotbrown** [comment]
### MyVA Troubleshooting

Below is card-by-card response to Samara's notes and plan to remediate data issues and/or explain functionality to MyVA team.

- **CARDS: Percent of Logged in VA.gov users visiting the homepage & VA.gov users visiting MyVA**
  - **_Feedback:_** “Too low”
  - **_Causes:_**  Using different denominators - GA report they’re comparing it to is Modernized, not All VA, making the denominator about double the size. May also be confusion on month they think they're seeing in Domo (they sent all August comparisons when Domo is showing July).
    - Logged in users who visit homepage (July 2022): 15.9% for WBC //  9.0% for All Prod
    - VA.gov users who visit my VA (July 2022): 7.2% for WBC //   4.1% for All Prod
  - **_How to fix:_** Potentially mirror WBC view definition in the “All VA users” we’re comparing to in BQ. Explain cause of difference to team, verify they need/want modernized as comparison. Make sure they understand dates.
- **CARD: Total interaction clicks**
  - **_Feedback:_** “Not useful”
  - **_How to fix:_** Remove
- **CARDS: Successful GETs & Failed GETs**
  - **_Feedback:_**  “Too low” and “PoP changes too drastic”
  - **_Causes:_** Update cadence vs. filters - data updates by day, but unit of comparison is set “by week.” Samara was viewing a few days compared to a full week, explaining both the low totals and drastic changes.
  - **_How to fix:_** Temporarily added a filter that cuts off on Saturdays, like our standardized data sources. Could also add filter that excludes current week from these cards, or add rolling 7 vs. 14 grouping rules like AooA dashboard.
- **CARD: Key GETs**
  - **_Feedback:_** “seems too high for time period” and “might be showing for entire site”
  - **_Causes:_** Comparing incorrect time period (GA report shows 7/22/22, vs. 7/22/21 in the Domo version). The data DOES include events across entire website - but so does their GA card. We'll need to verify what they actually want here and correct query accordingly. For card issues, currently grouping successes and failures… should either add color as stacked bar chart OR create a concatenated type + outcome label for the y-axis instead.
  - **_How to fix:_** Explain time period difference. Clarify whether they want MyVA filter added (like they say) or not (like their comparison card is configured).
- **Key interaction events**
  - **_Feedback:_** “Totals are too high” and “think it’s showing all VA site”
  - **_Causes:_** “Showing all VA site” is incorrect - this is an existing datasource we inherited fro this project, but it has a `REGEXP_CONTAINS(hits.page.pagePath,r'(/my-va|/?next=/my-va).*')` filter on it. Suspect that the time period is unclear.
  - **_How to fix:_** Explain how to filter by date. Offer to default to “Most recent month,” etc.
- **CARD: Percent of MyVA logged in users**
  - **_Feedback:_** “Don’t understand what it is showing”, especially vs. % logged in users who 
  - **_Cause:_** Older data source, being calculated as (logged in visitors to MyVA pages) / (all visitors to MyVA pages). This may not match mental model for business logic.
  - **_How to fix:_** Verify this is useful to them - if not, convert to different metric or remove.
- **CARDS: Medallia (all 3)**
  - **_Feedback:_** Suspicious of data quality, since results from Intercept vs. Feedback survey are so different
  - **_Cause:_** There are some profile or other Auth Exp surveys slipping in here because of the VA Product = Authenticated Experience. But according to ETL history of runs, removing this doesn’t meaningfully change the total number of surveys. Lack of understanding on how surveys are administered / why one might be lower than the other
  - **_How to fix:_** Remove Auth Exp from ETL logic. Give some context of how each survey is administered. Encouraging them to continue working with Contact Center to dig into the free response section of these surveys to better understand discrepancies.

### Next Steps

- [ ] Adjustments to Medallia ETL
- [ ] Key GETs card updates
- [ ] Holistic look at update cadence, date grouping, and card-level date filter presets for "all time" charts.
- [ ] Compile list of questions + points of clarification for MyVA team meeting

**Comment by chloedotbrown** [comment]
## Changes made 

### Visualizations
- Changed all data sources able to make daily to update to data through yesterday.
- Converted user-based metrics to session based.
- Removed "VA.gov" from title to declutter.
- Added notes on data sources, update cadence, and date range to top of dashboard.
- Added device + browser filters to dashboard default settings.
- **Highlights section**
  - "Sessions where users visited MyVA" - now bar chart showing rolling 52 weeks, with projection bar of current week's data.
  - "Percent of all sessions on VA.gov" - combined former multi-value gauges showing percent of sessions visiting MyVA and the homepage to line chart by week.
  - Removed "Total interaction clicks" as requested by MyVA team.
- **Task completion**
  - "Successful / Failed GET events" - changed titles, switched grouping criteria from by week to rolling 7 day comparison to previous 7.
  - "Overall GET success rate" - changed title, switched default date range to last 7 days.
  - "Total GET events by type and outcome" - changed title, added "outcome" to series, percent of category that succeeded/failed in hover text. Switched default date range to last 7 days.
- **Ease of use**
  - Combined two click-related sections with small number of cards to same section.
  - "Top interaction clicks" - changed title, switched default date range to last 7 days.
  - "Unauthenticated clicks to MyVA" - now bar chart showing rolling 52 weeks, with projection bar of current week's data.


### Data sources

**Synched updates between 7-8am ET daily**
- MyVA navigation clicks by LOA
- MyVA API requests by status
- All MyVA Events by Day
- MyVA sessions and comparisons

**Other update schedules**
- Search rankings - every month, may take slightly longer to add final week's data due to Standardized Search update schedule.
- Medallia data - data owned by Contact Center team, appears to update weekly starting in August.

## Outstanding questions
We need to clarify metric definitions for the following:
- What is comparison denominator for "All VA users"? Discuss WBC vs. All Prod, differences and impacts.
- Verify switch to session-scoped metrics, such as "Sessions where users visited MyVA" or "Percent of all sessions..."
  - They can have the user-scoped versions back, but will have to understand tradeoffs in date flexibility / risk of errors in unique counts.
- Search rankings - what time period do they want to be able to group by? (i.e. Always only by quarter, month, etc.). If they need it flexible, would they be willing to lose the listed rankings?

**Comment by chloedotbrown** [comment]
Implemented all changed from yesterday's meeting and re-QA'ed affected cards. Have [shared updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31302#issuecomment-1241098114) with Samara and AJ in external ticket, along with some usage resources. 

Closing out the internal ticket, since I believe the bulk of this work is now complete!
