### ISSUE TITLE
Publicize the updates in ToT and Demo day

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43532]
## Issue Description
Publicize the updated offering on ToT, Demo, Slack

Should this channel be spoken of elsewhere, such as General Orientation?

## Tasks
- [x] Announce the new channel and its purpose in 8/23/22 ToT, encouraging adoption
- [x] Prepare updated offering demo for 8/31/22 Demo day (Dan)

## Acceptance Criteria
- [x] Demo prepared for Demo Day
- [x] New channel is publicized via ToT

**Comment by twoangstroms** [comment]
@steel36 Do we have updated dates for ToT and Demo we could put in this ticket?

**Comment by twoangstroms** [comment]
Demo deck in drafting: https://docs.google.com/presentation/d/1B5UWZixHIc9FzKZk0IdQbSDruSuYjWL7gli3n3WyVPc/edit#slide=id.p
