### ISSUE TITLE
Launch the updated Playbook

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43531]
## Issue Description
Make sure the Playbook is available and positioned correctly in the pre-determined location.

Decided in earlier worksession:
In order to keep the Change Playbook and Principles, we intend to place them in separate locations, based on likelihood of engagement:

Change Communication Playbook: Prod. Mgmt. Comm. of Practice / (existing Playbook landing)
Platform Communication Principles: About the Platform / How we work /

## Tasks
- [x] Launch the updated Playbook in Product Mgmt comm of practice space
- [x] Launch the updated Principles in comm of practice space
- [x] Launch the Change Comm. Plan as child page to Playbook
- [x] Launch the Change Comm Example as child page to Plan
- [x] Launch the Slack Change Announcement format as child to Plan

## Acceptance Criteria
- [x] Playbook is available to intended audience(s)

**Comment by steel36** [comment]
This will be pushed to next sprint due to Go/No Go cancellation
