### ISSUE TITLE
[Content][SMS] Revisions to "We don't have this phone number in our records" Wording

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43546]
# Description
A problem with the wording "We don't have this phone number in our records. Try again using a mobile phone that's in our records. If you need more help, ask a staff member or call us. Find our phone number: https://www.va.gov/find-locations/"

# Tasks 
- [x] Create new wording and Sletch mock-ups
    - Would a more helpful call to action (CTA )be to direct Veteran to staff since they are on-site already? May be more cumbersome to find a phone number. 
    - Modifications to shorten and improve voice/tone e.g. Please try again. 
- [x] Review wording options with content (Danielle)

# Acceptance Criteria
- [x] Make sure the final wording is documented in Sketch, the Sketch user flow document.
- [ ] Add part 1 to the va.gov portion of the source of truth documentation here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md
- [x] Message CHIP to let them know about what they have to update for part 2. Also, let them know that they will need to update their source of truth documentation.

**Comment by niradatta1** [comment]
Added proposed recommendation in review doc (row 2). Sent Slack message to Chris Horton[not sure why I can't tag him in this ticket?] for feedback. https://docs.google.com/spreadsheets/d/1Z_W57lCBcbFcTCwHkPcg_Ep5emfdm9ywSkyY-i47Nis/edit?pli=1#gid=0 'cc @loripusey @kristenmcconnell

**Comment by Hortonio** [comment]
@niradatta1  @loripusey apologies for the delay in my response. Reviewing the revisions for row 2 of doc, the new wording is much more thoughtful:

> Sorry, this phone number isn't in our records. Please try again. Or ask a staff member for help.

- Empathizing with the Veteran by offering a simple 'sorry' regarding the error
- Stating exactly what is known about the error and why it is occurring
- Providing instructions as to how to resolve the error and politely asking 'please' (instead of just commanding)

The only thing I might consider changing would be condensing the last two sentences into one:
"Please try again or ask a staff member for help."

Perhaps intentional to break into two sentences for easier comprehension? 

Either way, love the new wording!

**Comment by niradatta1** [comment]
@Hortonio Many thanks, Chris! Checked with site-wide content. Seems like the general approach is to split up the last statement after "please" into two sentences. 

I've gone ahead and updated this in our check-in user flow document. 

As a next step, would you be able to (1) add this to your backlog for implementation and (2) update your source of truth document?

**Comment by Hortonio** [comment]
@niradatta1 Sure (to both items)! Here is the corresponding CHIP ticket we will use for tracking these updates to messaging content: https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/1086

**Comment by niradatta1** [comment]
Thanks @Hortonio !

@loripusey @kristenmcconnell Merged the finalized user flow to Abstract. @zach-park will update to Sketch Cloud at end of this sprint.
