### ISSUE TITLE
My VA: Sprint 88 (11/30/22 - 12/13/22)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43551]
## Priorities

1. Payment Info V2 - Launch up to 100%, update documentation (product guide, use case and user flows)
2. My VA Audit - Finish FE dev, submit analytics request, create QA test cases
3. Prep for hand-off: PMs review backlog with Samara, Design review sketch files for handoff
4. Healthcare - launch Cerner/drupal updates (12/14)

PTO
- Taylor: 12/9

## My VA Payment Info V2 (#43332)
**PM**
- [x] #45929 _from previous sprint_
- [x] #47238
- [x] #47239

**Research/Design**
- [x] #49387 _from previous sprint_

**FE**
- [x] #49398 _from previous sprint_
- [x] #47238
- [x] #47239

## My VA Audit UX Improvements (#41934)
**PM**
- [ ] #49534 _from previous sprint_
- [x] #49535 
- [x] #47368

**Design/Research**
- [x] #48699 _from previous sprint_
- [ ] #49196

**FE**
_from previous sprint_
- [x] #49558 
- [x] #47520 
- [x] #47521 
- [x] #47683 

_new work_
- [x] #49844
- [x] #49774
- [x] #50556 

## My VA 2.0 General Enhancements (#31611)
**PM**
- [ ] #50039

**Design**
- [x] #50041

**FE**
- [x] #50173
- [x] #50043 
- [ ] #41202 
- [ ] #50561
- [ ] #50601

**Comment by ericasauv09** [comment]
[Samara's Sprint Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/my-va/sprints-81-90.md#sprint-88-1130---1213)

**Comment by ajakabcin** [comment]
@aagosto90 and @tmitchellgcio here is the order of operations for the sprint per our discussion in planning cc @ericasauv09 

**Research & Design**
1. Finish up UAT findings: #49387
2. Continue with audit changes review with other teams: #48699
3. Sketch file review/organization #50041
4. My VA post-audit use case documentation (if time permits) #49196

**FE**
1. Separate drupal implementation from audit work #50173 
2. Finish payment history error placement bug #49398
3. Complete audit tickets from previous sprint _before_ picking up any new audit tickets: #49558, #47520, #47521, #47683
4. Only if you have time and can complete the work by the end of the sprint: #49774 and #49844

On-going throughout the sprint:
- continue phased launch of payment info v2
- launch drupal implementation (remove feature flag when we're given the green light) #50043
- launch vaos v2 api (remove flag when we're given the green light) #41202

Let me know if you have any questions!
