### ISSUE TITLE
My VA: Sprint 89 (12/14/22 - 1/3/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43555]
## Priorities

1. Onboarding any new roles
2. Complete documentation for Payments V2
3. Finish test cases and prepare for QA for My VA Audit
4. Preliminary meeting to discuss Onsite Notifications V2

PTO
_Federal holiday 12/26: Christmas Day (observed)_
- AJ: 12/23
- Erica: 12/27
- Angela: 12/22-12/23
- Samara: 12/27
- Liz: 12/23-12/27

## On-site Notifications (#30611)
**PM**
- [ ] #48645
- [ ] Preliminary V2 discussion

## My VA Payment Info V2 (#43332)
**PM**
- [ ] #49197
- [x] #50744 

**Research/Design**
- [ ] #49197
- [x] #49196 _from previous sprint_
- [x] #50744 

**FE**
- [x] #50737 

## My VA Audit UX Improvements (#41934)
**PM**
- [ ] #49534 _from previous sprint_
- [ ] #50743 
- [ ] #50644 

**Design/Research**
- [ ] #50743 

**FE**
- [ ] #50743 

## My VA 2.0 General Enhancements (#31611)
**PM**
- [x] #50039 

**FE**
- [x] #50561 (waiting on validation)
- [x] #50601 (waiting on validation)
- [x] #41202
- [ ] #50643
