### ISSUE TITLE
[FE] Payment Info MVP: Show section when user has no payments but has outstanding debts

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43568]
## Background
As a result of #42911, we determined that there are some discrepancies between how we intended the payment info section to function, how it actually is functioning and the documentation of how it's supposed to function. 

We need to update the logic for when this section displays, specifically in the scenario when a user has never received payments but has an outstanding debt.

**Old logic**: show the section if we receive any information from the payment API.

**New logic**: show the section if we receive any information from the payment API _or_ if we receive information from the debt API _and_ the debt API is not _0_ 

The problem with the old (current logic implemented as of 6/28) is that a user could have outstanding debts but if they've never received payments then the section does not display for them.

The language has been updated in the [documentation](https://dsva.slack.com/archives/CBU0KDSB1/p1656433903829369?thread_ts=1656433220.481959&cid=CBU0KDSB1). We now need to make the change in our designs and in the code.

## Tasks
- [x] [FE] Update conditional logic on the Benefit payments & debts section to display per the following rules: 
> **Show the section if:**
> - We receive any information from the payment history API _or_
> - We receive any information from the debts API _and_ it does not equal 0.
>  
> **Do NOT show the section if:**
> - We don't receive any information from the payment history API _AND_
> - We don't receive any information from the debts API _OR_
> - We receive information from the debts API, and the debt equals 0.
- [x] Update code so that when a user has never received payments but they have outstanding debt(s) they only see the debt alert message (as per designs that will be linked in the comments when #43629 is complete)
- [x] Update code so that when a user has never received payments but they have outstanding debt(s) they do not see the secondary links (as per designs that will be linked in the comments when #43629 is complete)
- [x] [FE] Test and confirm locally with Angela before merging (due to the complexity of this logic let's check locally before going through the merge process) 
- [x] [FE] When ready for validation, tag the PO, PM and/or APM for validation

## Acceptance Criteria
- [x] Confirm that the functionality has been updated to reflect the rules outlined in the tasks.

## Validation
**Who can validate this ticket? (FE, BE, Design, PM)** any team member

**How can this work be validated?** 
- [ ] Log into staging and confirm the following scenarios are functioning as defined:
     - [x] A veteran who has received payments _**or**_ who has any outstanding debt sees the Benefit payments & debts section
     - [ ] A veteran who has **never** received payments but who has outstanding debts sees the Benefit payments and debts section. They only see the debt alert. They do not see the secondary links.

**Comment by aagosto90** [comment]
@tmitchellgcio Here's the [Sketch design](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/Qbqqj7G) for a user who has never received payments but has debt. We should show the section and only the debt alert.

**Comment by ajakabcin** [comment]
@ericasauv09 agreed. We'll probably need to ask the debt team to create some new debts for us, probably two birds one stone though with the onsite notification testing.

**Comment by ericasauv09** [comment]
ohhh ok - should we have taylor roll back then? Otherwise this will go to Prod tomorrow at 3pm
