### ISSUE TITLE
Configure SSL termination for each subdomain

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43569]
## Issue Description
The SSL certs for the new `*platform-api.va.gov` subdomains need to be installed to the reverse proxy and its load balancer. This requires adding and referencing the `*.crt` and `*chained.crt` files in the `devops` repo and and including the corresponding private keys as AWS Parameter Store secrets. 

---
## Tasks
- [x] Add PKs as AWS Parameter Store secrets
- [x] Add (chained) crt files to the devops repo
- [x] Add necessary configuration in Ansible and Terraform
- [x] Create PR and follow up on suggestions
- [x] Check that configs and certificates have ben created

## Acceptance Criteria
- [x] Certificates are installed and configured correctly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
