### ISSUE TITLE
[Research] Document & Review Travel Clerk Processes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43575]
## Background
After meeting with the travel clerks today, Ben and I still have further questions about the staff process. We gathered some more names of travel clerks to talk to at today’s meeting. We would like to set up a time to meet with them and we plan to change our approach with how we ask them questions. 

## Tasks
- [x] Review 18F's work and notes from first meeting with Travel Clerks
- [x] Set up a Mural documenting what we believe is Travel Clerk's current process
- [x] Set up review meeting with Travel Clerk's
- [x] Review the current process with Travel Clerk's to verify

**Comment by loripusey** [comment]
@kristenmcconnell @benbrasso-agile6 can you point this so we can pull it into the sprint tomorrow?

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell I marked it as a 5. Feel free to edit, etc.

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 Sounds good to me.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell, you and I talked about modifying this approach a bit. We would walk them through the prototypes, but ask some questions that surfaced in our meeting with Stephen on the MVP. Such as: 

Automatic vs. manual (this was something that Chris Johnston was bringing up)

Ask about percent of driving from home. Chester Peyton is the PM for BTSSS and also is very knowledgeable. He can answer this better, but I think something like 70% - 80% of claims are mileage only.

Could ask about how often people don't drive from home. 

If we didn't include adding expenses, could someone do that later in BTSSS for the same visit/claim? 

Ask about general eligibility? Or specifically, are all vets that have appts in VA facilities eligible? 

Can we ensure someone doesn't get presented with submitting reimbursement twice for one trip? Although, Stephen brought up a point about two locations in the same day. We may need to ask clerks about this.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell if you look on Page 4, I've added questions. Go ahead and take a look. 

There's a lot of questions. So, I need to figure out if/how this fits in WITH the prototype review. For now though, if you could focus on these new questions, that would be ideal. 

https://docs.google.com/document/d/1t_tiR1ctsYjlnfFIoTXcPkLKLm7IRnMYeaRCYXd3juY/edit?usp=sharing

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 I added a bunch of comments and suggestions to the Google doc. You are correct that there are a bunch of questions. Maybe the order of the study should be flipped. You would ask the questions first, then review the prototype if there is time. This looks really good.

**Comment by benbrasso-agile6** [comment]
There's too many questions to also go into the prototypes, so I stripped them out. I'll rethink it again on Monday. But, right now, it seems like too much 

https://docs.google.com/document/d/1t_tiR1ctsYjlnfFIoTXcPkLKLm7IRnMYeaRCYXd3juY/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
Completed https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/staff-facing/corpus-christi-in-person/conversation-guide.md
