### ISSUE TITLE
Set up forward proxy port to Kong in higher environments

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43577]
## Product Outline
[CIT Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)

## High Level User Story/ies
As a developer on a team that uses vets-api to make upstream Lighthouse requests, I should be able to use existing infrastructure for changing the route to the Lighthouse API Gateway.

## Hypothesis or Bet
By enabling a new port on the forward proxy, developers can use the forward proxy to route to Kong, and then switch the forward proxy configuration to point to Apigee once Lighthouse moves to its new infrastructure.

## OKR
The routing of upstream Lighthouse requests has been enabled for handoff for use in higher environments.

## Definition of done
- [ ] Forward proxy port is configured to point to Kong in each of the higher environments (staging, sandbox, and production.)

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
