### ISSUE TITLE
[FE] Payment Info MVP: Correct debt alert language

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43570]
## Background
As a result of #42911, we determined that there are some discrepancies between how we intended the payment info section to function, how it actually is functioning and the documentation of how it's supposed to function. 

We need to update the the copy in the debt alert to display appropriately when there are multiple debts or just one debt. Currently, the debt alert copy is as follows:

> You have 1 outstanding debts.
![Screen Shot 2022-06-28 at 4 43 48 PM](https://user-images.githubusercontent.com/45603961/176284026-f63e26e9-1186-4214-ade1-7cb81d2ef5dc.png)

If the user only has _one_ debt then the debt alert copy should read:

> You have 1 outstanding debt.

## Tasks
- [x] [Design] Update sketch files to show correct copy in the debt alert for a singular debt (if needed)
- [x] [FE] Update copy and logic in the debt alert to display "debt" when the user has one debt and "debts" when the user has multiple
- [x] [FE] Test and confirm locally with Angela 
- [ ] [FE] When ready for staging, tag the PM or APM for validation

## Acceptance Criteria
- [ ] Confirm that the debt alert copy is updated to handle single and plural debt scenarios.

## Validation
**Who can validate this ticket? (FE, BE, Design, PM)** any team member
**How can this work be validated?** 
- [ ] View the sketch files and check for the documented updates
- [ ] Log into staging and check that the debt alert is grammatically correct for a user with a single outstanding debt and a user with multiple outstanding debts. Note in the comments what test users you used.

**Comment by tmitchellgcio** [comment]
@ajakabcin @Samara-Strauss @ericasauv09 This is the deployed environment http://a154d7305ba9e43a79ab2d58a5f41625.review.vetsgov-internal/

You should be able to validate this on this link. This is the only way to validate before it reaches the main branch and automatically gets deployed to master so this may need to be the new way we have to handle validations.

**Comment by Samara-Strauss** [comment]
That link doesn't work for me, even on the VA network.

I am leaving in a few minutes for a doctor's appointment, so I'll check in on this tomorrow.

**Comment by tmitchellgcio** [comment]
It does require having SOCKS on. Not sure if that helps

**Comment by Samara-Strauss** [comment]
I don't have SOCKS access, unfortunately, and have not been able to get it due to not being able to install it on a GFE.

**Comment by tmitchellgcio** [comment]
@Samara-Strauss that's fine. I think @ajakabcin or @ericasauv09 should be able to get SOCKS access unless they aren't eligible for it for some reason.

**Comment by ericasauv09** [comment]
I tried getting SOCKS access a few weeks ago but ran into some issues so I gave up but I will try again

**Comment by ajakabcin** [comment]
For now let's do a screenshare to validate this and we'll work in parallel on our socks access

**Comment by tmitchellgcio** [comment]
I can create a video using OBS and attach it to the tickets for now if that's best
________________________________

**Comment by ericasauv09** [comment]
@ajakabcin @Samara-Strauss  - For when you both are back, Taylor reached out to some folks on the platform team and we learned that Staging is the recommended route for validation. As Vets API is only deployed once a day at 1pm ET we would have 24 hours to validate and rollback if needed before the next deployment. Eric Boehs on the console service team informed us that using review instances (as Taylor tried to do here) is not recommended as they are not reliable and do not replicate other environments effectively. See this [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1657132974782339) for more details. 

Taylor and I chatted and we have two options 1. Deploy these changed to staging after 1pm ET and validate, rollback if needed before 1pm the next day. 2. Taylor can create a feature flag so we can deploy to Staging and utilize the feature flag to ensure it is not live for users without having to worry about the 24hr time limit. Taylor has an idea to create 1 permanent feature flag for our team that can be used for all features but this option requires more work and each feature would later have to be removed from the flag after it is live for all users.

**Comment by Samara-Strauss** [comment]
> Taylor and I chatted and we have two options 1. Deploy these changed to staging after 1pm ET and validate, rollback if needed before 1pm the next day.

Since this is a small update, I think option 1 is best. We should reserve feature flags for projects or more complex functionality.

**Comment by ajakabcin** [comment]
I'm not sure if the deployment didn't work properly or if it still needs to be merged, but I'm still seeing "debts" when it should be debt. I just tested user 11 on staging, who has one debt and it reads "you have 1 outstanding debts"

![Screen Shot 2022-07-08 at 2 55 21 PM](https://user-images.githubusercontent.com/45603961/178054041-064585ad-17d9-4aec-b0f3-2cad8e090c59.png)

**Comment by ericasauv09** [comment]
@Samara-Strauss @ajakabcin for your awareness - deployment to Production is live each day at 3p et. To have any changes included in that deployment they need to be in Staging by 2pm et.

**Comment by Samara-Strauss** [comment]
Great, thank you for this!

**Comment by ajakabcin** [comment]
Confirmed correct language for user with 1 debt (user 1), also confirmed correct language for user with multiple debts (user 56). 

user 1
![Screen Shot 2022-07-11 at 2 35 18 PM](https://user-images.githubusercontent.com/45603961/178334620-b79d092d-37fb-40c0-94be-7428f7a81d50.png)

user 56
![Screen Shot 2022-07-11 at 2 37 41 PM](https://user-images.githubusercontent.com/45603961/178334671-17ab016d-2f4d-4fb3-95a1-d4d7fd939994.png)

Thanks @tmitchellgcio !
