### ISSUE TITLE
Configure platform-api subdomains

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43572]
## Product Outline
[CIT Product Outline](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2247131525)

## High Level User Story/ies
As a developer, I need to configure the new *platform-api.va.gov subdomains, so that they resolve to the correct vets-api endpoints in their respective environments.

## Hypothesis or Bet
Because each *platform-api.va.gov subdomain is configured in its own environment, each subdomain will require its own Nginx configuration and TLS/SSL certificates/termination.

## OKR
The *platform-api.va.gov subdomains have been procured and enabled for handoff to use in all environments.

### What must be true in order for you to consider this epic complete? 

- [x] Nginx is configured for each *platform-api.va.gov subdomain.
- [x] SSL/TLS has been installed and terminated for each subdomain in the appropriate locations.
- [x] Each *platform-api.va.gov subdomain resolves to its appropriate vets-api endpoint.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by alwerner** [comment]
Closing this as complete. cc: @madebydna
