### ISSUE TITLE
Manual route testing

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43573]
## Issue Description

Documented set of manual tests exist to confirm that the four new `*platform-api.va.gov` domains are correctly routed to their respective `vets-api` instances. Manual tests can include command-line tests (e.g. `curl`) or browser tests.

---
## Tasks
- [x] Manual test performed and documented for `https://dev-platform-api.va.gov`
- [x] Manual test performed and documented for `https://staging-platform-api.va.gov`
- [x] Manual test performed and documented for `https://sandbox-platform-api.va.gov`
- [x] Manual test performed and documented for `https://platform-api.va.gov`

## Acceptance Criteria
- [ ] All four domains had reproducible and documented manual tests performed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by madebydna** [comment]
There is currently a SNOW ticket to track a remaining SSL error in dev: INC23321981.

The functionality of the new domains at the two TIC gateways (GWN and GWW) can be tested like so:
```
# DEV
# This currently fails at GWN
curl --resolve dev-platform-api.va.gov:443:152.133.106.82 https://dev-platform-api.va.gov
curl: (35) LibreSSL SSL_connect: Connection reset by peer in connection to dev-platform-api.va.gov:443 
curl --resolve dev-platform-api.va.gov:443:152.131.101.82 https://dev-platform-api.va.gov
{"message":"Welcome to the va.gov API"}

# STAGING
curl --resolve staging-platform-api.va.gov:443:152.133.106.83 https://staging-platform-api.va.gov
{"message":"Welcome to the va.gov API"}
curl --resolve staging-platform-api.va.gov:443:152.131.101.83 https://staging-platform-api.va.gov
{"message":"Welcome to the va.gov API"}

#SANDBOX
curl --resolve sandbox-platform-api.va.gov:443:152.133.106.84 https://sandbox-platform-api.va.gov
{"message":"Welcome to the va.gov API"}
curl --resolve sandbox-platform-api.va.gov:443:152.131.101.84 https://sandbox-platform-api.va.gov
{"message":"Welcome to the va.gov API"

#PROD
curl --resolve platform-api.va.gov:443:152.133.106.81 https://platform-api.va.gov
{"message":"Welcome to the va.gov API"}
curl --resolve platform-api.va.gov:443:152.131.101.81 https://platform-api.va.gov
{"message":"Welcome to the va.gov API"}

```

cc: @mchelen-gov
