### ISSUE TITLE
Supplemental Claims | Add claimant type & name pages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43587]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Supplemental Claims form claimant pages
**_So that_** we can test the interaction of the page

## Background Context

The Supplemental Claims (SC) form (20-0995) is in the process of being structured, and the claimant type & name page is a known pattern which can be implemented before the design has been finalized.

Add:
- Claimant Type, radio & text input
  -  Veteran
  -  Veteran Spouse
  -  Veteran Child
  -  Veteran Parent
  -  Other (free text input)
- Claimant’s Name: (if other than Veteran’s): First, Middle & Last (required if type is spouse, child, parent or other)

## Tasks

- [ ] Add the Client type & name pages
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
[Slack Discussion on how to handle the "Other" radio without revealing the related text input ](https://adhoc.slack.com/archives/C039EAY655H/p1657202807280919) - more discussion is scheduled for 7/8/2022

**Comment by saderagsdale** [comment]
@thehastingsp @Mottie The blocker on this was all the non-Veteran claimant types right? Trying to see if we can unblock by just having the non-veteran claimant types sent to the manual form.

**Comment by Mottie** [comment]
I think the blocker is from Lighthouse? I think our initial app will only support Veteran's applying for a Supplemental Claim

**Comment by saderagsdale** [comment]
@Mottie So are we just informing Lighthouse that we won't be providing all the options available in their endpoint? Or does it require additional refinement to ask them to change something?

**Comment by Mottie** [comment]
We'll need to ask them to double/triple check that only the "veteran" claimant type that's working right now. If all types are supported, then we'll need to discuss what we're doing for initial launch. Adding a non-Veteran claimant type will make the form a bit more complicated and will require changing some of the already existing work.

**Comment by saderagsdale** [comment]
Discuss starting with Veteran role w/ LH.
