### ISSUE TITLE
Supplemental Claims | Add Address, email and phone entry page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43588]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Supplemental Claims form with pages
**_So that_** we can coordinate with team members on the design and flow of the form

## Background Context

The Supplemental Claims (SC) form (20-0995) is in the process of being structured, and adding the address, email and phone page. This may or may not be associated with the claimant. Will need to verify before implementing.

## Tasks

- [ ] Add the address, email & phone page
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
