### ISSUE TITLE
[Support] Implement Tracking for Provider Profile Pages

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#4358]
# Analytics Implementation or QA Request

## Goal 
Educate on impact of new VET TEC Provider pages

## Description
To track KPI interactions on [GIBCT provider profile pages](https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/).

## Acceptance Criteria
- [ ] Verify tracking when user engages with the "Program Name" radio button within the Approved Programs accordion
- [ ] Verify tracking when the user enters text into the Tuition & Fees text field
- [ ] Verify tracking when the user engages with the "Scholarships" text field

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] All QA completed

**Comment by jonwehausen** [comment]
Hi @amyknox, 

@nedierecel and I put our heads together and determined there's some additional tracking needs in order to support the [dashboard updates](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3043). 

We know we're in code freeze, but here are the DL requirements we will need a developer on: 

## Program Name Radio Button

- Render on each radio button click/toggle

![image](https://user-images.githubusercontent.com/48527022/71366708-d480d800-2570-11ea-9492-81aa9a3fbe7d.png)
**Datalayer Need**

```javascript
dataLayer.push({
   'event': 'gibct-form-change',
   'gibct-form-field': 'Program Name Radio Button',
   'gibct-form-value': <label_of_radio_button> //i.e 'Galvanize Data Science Immersive'
});
```

## Tuition and Fees Text Field
- **Render on the click away from the text field**
![image](https://user-images.githubusercontent.com/48527022/71366843-304b6100-2571-11ea-8b6f-6a52a138351b.png)


**Datalayer Need**
```javascript
dataLayer.push({
   'event': 'gibct-form-change',
   'gibct-form-field': 'Tuition & Fees Text Field',
   'gibct-form-value': <input text value> 
});
```

## Scholarships Text Field
- **Render on the click away from the text field**

![image](https://user-images.githubusercontent.com/48527022/71366937-71437580-2571-11ea-97e1-daa49bfb86a8.png)


**Datalayer Need**
```javascript
dataLayer.push({
   'event': 'gibct-form-change',
   'gibct-form-field': 'Scholarships Text Field',
   'gibct-form-value': <input text value> 
});
```

**Comment by amyknox** [comment]
Thanks @jonwehausen - I'll get someone on this Monday!

**Comment by jonwehausen** [comment]
Hi team, 

Do we have an update here on the DL needs? 

Thanks in advance. 

Best,
Jon Wehausen

**Comment by amyknox** [comment]
@jonwehausen - we were light on devs earlier this week.  Back in full force and this story has been prioritized.  I'll let you know when it's picked up.

**Comment by dmccurdybah** [comment]
Ready for BAH QA review on vets-website branch `bah-ct-tracking`

**Comment by delli-gatti-michael** [comment]
Local testing complete. Fields are tracked as expected. See screenshot below.

![Screen Shot 2020-01-08 at 7.44.42 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/414a2ba0-808f-4cc7-854e-bb9648953124)

**Comment by jonwehausen** [comment]
Hi @delli-gatti-michael,

Thanks for your help here. 

One observation -- I noticed the Program Name radio button click sometimes causes a simultaneous change in the "tuition and fees" text field as well. 

As it stands, would the scenario described above cause a DL push for Tuition and Fees as well?

**Comment by dmccurdybah** [comment]
Hi @jonwehausen, no the scenario you are describing does not cause a DL push for Tuition and Fees because it doesn't trigger the OnBlur event (which is how I read the "Render on the click away from the text field" in the AC)  Is this correct?

**Comment by jonwehausen** [comment]
Yes that is correct, just wanted to make sure of that! Thanks!

**Comment by jonwehausen** [comment]
@dmccurdybah or @delli-gatti-michael 

Could you give me a status update on this functionality being available in staging for QA? Thanks in advance 😄

**Comment by dmccurdybah** [comment]
@jonwehausen 

Here's the link to the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11430

We're waiting on an external review before we can merge it into master and get it on staging.

**Comment by dmccurdybah** [comment]
@jonwehausen 

The PR was approved and merged and this is now ready for testing on staging

**Comment by jonwehausen** [comment]
## QA Testing
CC: @nedierecel @amyknox 

@nedierecel, Do you think we should also pass the Tuition and Scholarship values as custom metrics to allow flexibility on doing aggregate calculations? 

### Program Name Radio Button ✅ 
- Firing when the user clicks on the radio buttons in the Program Name column (_if there's a Tuition & Fee for that Program, the Tuition and Fees text field will also change_)

#### Datalayer
![image](https://user-images.githubusercontent.com/48527022/72169001-4001dc80-339c-11ea-90d9-ec04fcc9c720.png)

#### Tag

![image](https://user-images.githubusercontent.com/48527022/72168283-d6cd9980-339a-11ea-9990-b96f00913fce.png)

### Tuition and Fees Text Field ✅ 
- Firing when the user manually changes the value within the "Tuition and Fees for program" field and clicks away 

#### Datalayer
![image](https://user-images.githubusercontent.com/48527022/72169177-9a9b3880-339c-11ea-9092-ad2a6ab86357.png)


#### Tag
![image](https://user-images.githubusercontent.com/48527022/72168739-bd791d00-339b-11ea-8b48-93d22599d0e8.png)

### Scholarships Text Field ✅ 
- Firing when the user manually changes the value within the "Scholarships (excluding Pell)" field and clicks away 

#### Datalayer
![image](https://user-images.githubusercontent.com/48527022/72169262-c3bbc900-339c-11ea-8c07-5ec65b1552a0.png)


#### Tag
![image](https://user-images.githubusercontent.com/48527022/72168861-003af500-339c-11ea-8a81-5aedea05ae00.png)

**Comment by jonwehausen** [comment]
@nedierecel In order to keep the door open to perform aggregate calculations on the dollar amounts inputted into Tuition and Scholarships, we're going to have @dmccurdybah do a small change to pass the input values as numbers rather than text strings.

This will enable us to easily pass as custom metric to perform calculations in the future.

**Comment by dmccurdybah** [comment]
PR for update of tuition and scholarship value datatypes

https://github.com/department-of-veterans-affairs/vets-website/pull/11453

**Comment by delli-gatti-michael** [comment]
The screenshot below shows the updated tuition and scholarship values

![Screen Shot 2020-01-10 at 2.38.33 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3a262912-8874-4dfc-a8d6-8c66397ab586)

**Comment by amyknox** [comment]
@jonwehausen & @nedierecel - wanted to flag something that @delli-gatti-michael brought to my attention... 

While the title of this story is "Implement tracking for **Preferred Provider** pages", the functionality and all discussion on this story has been for all providers (preferred and those without the preferred designation).  The implementation is also for all providers - which is what we need in this situation.  

LMK if you have any questions or a different understanding!

**Comment by jonwehausen** [comment]
Hi team, 

@dmccurdybah Thank you for your quick turnaround in making those adjustments! 

@amyknox Yes -- understood. This was my mistake in the original titling of the story but agree this is universal functionality for all providers. I've removed the word preferred from the title accurately reflect. 

Thanks,
Jon Wehausen

**Comment by amyknox** [comment]
Great @jonwehausen - thanks for updating the title.  That helps!!

**Comment by amyknox** [comment]
@jonwehausen - With PR 11453 (https://github.com/department-of-veterans-affairs/vets-website/pull/11453), it looks like this might be done.  Could you double check and LMK?  

Thanks!

**Comment by jonwehausen** [comment]
Hi @amyknox,

Datalayer looks great -- No other updates should be necessary from your team. 

@nedierecel, Did you want to take a final look prior to publish? See 

Key highlights include: 
- Custom metric 17 named "GIBCT - Profile Benefit Estimate" will store the values of tuition & fees, and scholarships dynamically
- The event action will not include the form value for tuition & fees and scholarships since already being passed in custom metric and to ease reporting load -- other form changes will include these values in the event action

### Tuition & Fees Example

![image](https://user-images.githubusercontent.com/48527022/72562281-08ea6a00-3879-11ea-8eb8-50a37adf35fe.png)

### Scholarships Example
![image](https://user-images.githubusercontent.com/48527022/72562685-f91f5580-3879-11ea-8e72-0da04ba63e0f.png)


### Program Name Example 

![image](https://user-images.githubusercontent.com/48527022/72562397-55ce4080-3879-11ea-9857-03a00274b9f4.png)

**Comment by jonwehausen** [comment]
Functionality has been published as of 1/22 AM.
