### ISSUE TITLE
[Design] - Profile: add headings back to alerts

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#43586]
**Background**

When we did the alert audit in Sept 2021, we worked with the content team and made recommendations to update the content and remove the heading from our full-width feedback alerts in profile (mainly generic errors)

Since then, the design system team has released updated guidance for these types of errors.  See the "unable to complete a user-initiated map, still able to proceed" guidance in the [messaging directory](https://design.va.gov/patterns/messaging-dictionary). We should update our mock-ups and FE code to align w/ the guidance.

**Tasks**
- [x] Update the Sketch mock-ups across all sections of profile to make sure that alerts using the full-width pattern have a heading, and align with the new guidance in the [messaging directory](https://design.va.gov/patterns/messaging-dictionary).
- [x] Track which mock-ups need to be updated so PM can translate to a FE ticket
- [x] Let PM know this is ready for FE implementation

**Comment by andaleliz** [comment]
Hi @SKasimow and @Samara-Strauss I created this maintenance ticket for profile based on the conversation in @mdewey's [PR for an alert update](https://github.com/department-of-veterans-affairs/component-library/pull/434) he worked on in May.  We'll need some PO/PM feedback on prioritization and which sprint this should go into.

We need to do some content and design updates in Sketch (Christina or I can do this) and then Mark or Adam can handle the FE updates.

**Comment by Samara-Strauss** [comment]
Thanks for this! Before we can prioritize this, it would be helpful to have an idea of scale/level of effort for both design and frontend. My assumption is that this ticket is more of an epic than a one-off short task that can be completed alongside other work, but let me know if that's incorrect. Thanks for being on top of things and getting this conversation started!!

**Comment by Samara-Strauss** [comment]
Great! So easy in terms of design. @SKasimow this would be a good ticket to review next week in grooming to talk over what might be involved from Adam or Mark. We can then figure out if this is something short and easy we can get into the backlog, or a larger effort that we need to prioritize among other work.

**Comment by SKasimow** [comment]
@Samara-Strauss - I've added to the epic for Sprint 78/grooming

**Comment by Samara-Strauss** [comment]
@SKasimow we don't need to include this in sprint 78 as of now. Let's get a clear idea of what this will involve for frontend before adding it to a sprint.

**Comment by SKasimow** [comment]
@Samara-Strauss -  I'll add it under a "note" section at the top of the ticket (just so I don't forget to bring it up).

**Comment by andaleliz** [comment]
Hey @SKasimow and team, I'm going to pull this into the current sprint for me since I have some 1095b things out for review.

**Comment by andaleliz** [comment]
## Notification settings
### Can't access 
- [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/pamgp9Z)
- [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/YLgz8O/a/dlxe9D9/r/pv0P7A)

## Contact information
### Can't access
- [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/zx2q52a)
- [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/OmlnY7p)

## Direct deposit
### 
- [mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/09y85M0)
-[desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/m19eRvV)

**Comment by SKasimow** [comment]
@andaleliz - I opened #45872 for the FE work. Will add it for next grooming.

**Comment by andaleliz** [comment]
Hi @SKasimow thanks for doing that! I went ahead and added more details + links to the description of that ticket, so it's all in one place. This task is done :)
