### ISSUE TITLE
Supplemental Claims | Add Veteran Info pages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43580]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Veteran info page in the Supplemental Claims form
**_So that_** we can get a sense of how the prefill will work in a Veteran's logged in state vs not-logged in (if needed?)

## Background Context

The Supplemental Claims (SC) form (20-0995) allows a claimant to add the Veteran information. We can't prefill this if the claimant is logged in to their own account and filling the form in for the Veteran. We need to add form elements and prefill them with the logged in user information, but also allow them to change it if they are not the Veteran. These details have yet to be firmly established, but we can still build the page

The page should include:
- Veteran first, middle & last name
- Veteran SSN and/or VA File Number
- Veteran Date of birth
- Veteran service number (?)

## Tasks

- [ ] Add the Veteran information page
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
