### ISSUE TITLE
OCTO-DE review and publishing of special benefits allowance page with content from tables reworked

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43589]
## Issue Description
As part of our work to make sure all VA.gov pages are 508 compliant, we've been removing content from tables that shouldn't be in tables and reworking the page.

We took content on the special benefit allowance rates page out of tables in ticket #42773

This ticket is for Beth's review of that work and any changes the content team needs to make. We'll also track stakeholder approval, the pre-publishing checklist and publishing in this ticket.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=990

Substantive edits made from original content:

- Adjusted the "payable August 1" note and nested it under the clothing allowance header, based on the [VA clothing allowance page](https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/) and this [ebenefits rates page](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000162183/2020-COLA-Rates). The live page applies this August 1 note to all 3 special benefits, but from these 2 sources, I believe it applies only to clothing allowance. **Flagging that we'll need to ask stakeholder to confirm this.**
- Removed the eligibility H2 and placed the link to "find out if you can get xyz" under each benefit header
- Moved the tangential "Learn about other special claims" link from that eligibility H2 into a More Info link

## Tasks
- [x] OCTO-DE review (Beth)
- [ ] Send to stakeholder for review (Randi/Laura)
- [ ] Apply changes to past rates pages (Katherine)
- [ ] Copyedit with pre-publishing checklist (Megan)
- [ ] Publish pages (Megan)

## Acceptance Criteria
- [ ] Page with changes is live on VA.gov

**Comment by bethpottsVADEPO** [comment]
@RLHecht @katherine-fung @laurwill Thanks for your work on this! I made some edits and would like to talk about just a few things in our next meeting (Katherine, if you're free during my next check-in with Randi and Laura, please join!):
1/ This line: "Rate changes are payable the August after they take effect. So the new clothing allowance rate is payable as of August 2022."
2/ My edit in the automobile allowance section that deleted "or adaptive equipment for your vehicle" (not sure why this got added in, so I just wanted to align on that--see if there was something I wasn't aware of!)
3/ My edits that change "we'll pay" to "we may pay"

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! I'll join today's check-in.

**Comment by RLHecht** [comment]
@katherine-fung Now that the 2023 rates are live we can go back to this. I think you'll need to revert to a previous version and input the 2023 rates.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Want to revert to the version with your tables work and we can move this forward this week?

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I've reverted to the non-table format, and added the 2023 rates info. This page is ready for review:  

http://preview-prod.vfs.va.gov/preview?nodeId=990 

Thanks!

**Comment by bethpottsVADEPO** [comment]
@katherine-fung thank you for the work you did on this. I have a couple questions:
- For the auto allowance amount, you have "up to" before the dollar figure. Where did you see that (it's not on the existing live page) and should we be using that same "up to" language for clothing allowance and Medal of Honor too?
- I think you intentionally left out this text: "Rate changes are payable the August after they take effect. So the new clothing allowance rate is payable as of August 2023." I'd love to clarify with SMEs what this means. It's confusing because of the effective date that we also have. How is the effective date different? I'm going to ask Elana to come to my next VBA check-in (next Wednesday) and see if she can clarify. I will find the answer to this one.

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! 

- I'm not sure how "up to" got added to the auto allowance figure. In the source doc for 2023 rates, there's no mention of "up to" for the amounts of any of the allowances. So it seems like "up to" may be inaccurate. But I should confirm that with the stakeholder. Is Elana the right person to email? 

- Yes, we took out the text about rate changes being payable the August after they take effect. We wanted to replace this with the line "Note: To get the clothing allowance, you need to apply and qualify by August 1. You'll receive the payment between September 1 and October 31." But that got edited out in later revisions. 

It would be great to get clarification from Elana - thanks for handling this! (And let me know if I should talk to her). 

I'll also put this here for context. [The VA clothing allowance eligibility page](https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/) says: 

"To get your yearly payment, you’ll need to qualify by August 1 of that year. You may be able to get more than one payment if you meet at least one of the requirements listed below."

"We collect applications throughout the year and hold them until the August 1 closing date."

**Comment by bethpottsVADEPO** [comment]
Thanks for the background on this @katherine-fung! I'll ask Elana this week. Nothing for you to do at this point.

**Comment by bethpottsVADEPO** [comment]
Update: Waiting for SMEs to review the preview page I sent Elana. She is our go-between, communicating with SMEs in disability comp about this.

**Comment by bethpottsVADEPO** [comment]
I've asked twice more if she's heard back from the SMEs she sent this to... and we're still in pause mode on this.

**Comment by bethpottsVADEPO** [comment]
@coforma-terry I got SME approval finally for the updates to this page, so you can create a ticket for Megan to copy edit and we'll bring it into an upcoming sprint. Thanks!
