### ISSUE TITLE
[UX] Capture Metrics to Measure Success

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43606]
## User Story
As the Modernized Check-in team, we would like to be able to measure the success of this Epic so that we can determine if we need to make adjustments to the feature.

## Tasks
- [ ] Decide what success looks like for the Epic
- [ ] Determine how we will measure success
- [ ] Create metrics to capture measurements
- [ ] Present to the ideas to the team
- [ ] Create follow-up ticket to monitor the metrics over time (what time period?)
