### ISSUE TITLE
PM | Profile | Military Info Migration | Internal UAT

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43609]
FE support for UAT sessions

## Tasks
- [x] Provide UAT participants with access to test feature
- [x] Ask internal veterans to review their military info and ensure it displays correct info for service
- [x] Open tickets for any issues discovered

## Acceptance Criteria
- [x] Provide UAT participants with access to test feature
- [x] Provide any support needed
- [x] Fix any release impacting bugs

## How to configure this issue

- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so
