### ISSUE TITLE
Review standards and Evaluate map types

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43615]
## Issue Description
Service Blueprints, Customer Journey Maps-- what part or all of these do we think would be the best style to establish as our standard for mapping out the Experience of VFS users who are trying to accomplish things?

Let's all review industry standards to prime our thinking for which pieces to keep and which to toss in our own mapping pursuits.

[Develop and Document Mapping Process - Landing](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2394161153/Develop+and+Document+Mapping+Process+-+Landing)

## Tasks

**Review industry best practices and definitions**:
[Journey maps vs service blueprints](https://blog.designcriticalthinking.com/journey-maps-vs-service-blueprints-b9a8613bb790)
[Service Blueprinting](https://www.nngroup.com/articles/service-blueprinting-faq/) (w/ comparisons to JM)
[NNgroup SB definition](https://www.nngroup.com/articles/service-blueprints-definition/)
[UX Mapping Types](https://www.nngroup.com/articles/ux-mapping-cheat-sheet/)
[Service Blueprinting](https://www.youtube.com/watch?v=ubKp3vRJIJg) (w/ impacts)
[How-to](https://www.lucidchart.com/blog/what-is-a-service-blueprint)

**Mapping Examples:**
VEO's [journey map work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/design/va-product-journey-maps)
Previous SDT [Service blueprints](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2090074524/Customer+Journey+Maps+and+Service+Blueprints)

**Additional considerations:**
Review the differences between XYZ maps. (ie: need CJM for pain points wayfinding)
Evaluate examples of different maps based on intended outcomes. ie: what does the team want to learn?
[Differences between JM & SB](https://blog.practicalservicedesign.com/the-difference-between-a-journey-map-and-a-service-blueprint-31a6e24c4a6c)

## Acceptance Criteria
- Each team member has reviewed the above materials and noted any stand out advantages and disadvantages of SB, CJM, etc.
- [x] Dan - [map notes](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1665162797423/d86290b0fed9f341346a210c605feccc8703ee30?sender=u4f7db1750f2355f805e60296)
- [x] Nicole - [sandbox, in progress](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1663678821316/2f76cd2db6dc98009345c85a6c6f9ad925bde46d?sender=u311209e67c8c21a1b37a8167)
- [x] Taylor - [map notes](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1665518263566/ba4e93022ff0f8f5888915a9f3a5997152c698b4?sender=u9ea6bd3ca12795949b606150)
- [x] Bryan - [notes](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1664561883010/92efc17035df1a8bbd9095f8faece291ca5b0160?sender=u4397b715dc3690a417b71483)
