### ISSUE TITLE
CST: Validation rules preventing upstream issues with submissions

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43611]
## Value Statement
**_As a_** veteran
**_I want to_** be able to successfully submit files through CST and not learn later that, despite being told by the application the files were successfully submitted, the files never arrived at their intended destination
**_So that_** my claim doesn't get delayed because I didn't take timely actions to ensure my files get to where they need to go.

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] _Validation rules prevent upstream errors with files_
- [ ] _Lighthouse team is informed about validation rules and has a chance to validate approach_

## Open questions
- What are some specific upstream errors we're running into that validation rules on the FE could prevent? 

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
