### ISSUE TITLE
Move and test setting mock value for debts to feature flag

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#43616]
## Issue Description
We want to be able to dynamically assign whether to use mock or DMC data for specified staging users

---
## Tasks
- [ ] Open PR that moves setting to feature flag
- [ ] Test both sets of data with different users

## Acceptance Criteria
- [ ] We can assign to user whether to use mock or DMC data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
