### ISSUE TITLE
Supplemental Claims | Add evidence pages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43628]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Supplemental Claims form with evidence pages similar to 526
**_So that_** we can coordinate with team members on the design and flow of the form

## Background Context

The Supplemental Claims (SC) form (20-0995) is in the process of being structured, and this work will add the evidence flow used by 526. This will allow the Veteran to add VA facilities, obtain private medical records and/or upload supporting evidence.

Note: most of this code can be copied directly from form 526. Required fields:
- Evidence upload
- Evidence start date
- Evidence end date
- Evidence location and name

[overall flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/supplemental-claims-flow.md)

```mermaid
flowchart TB
    EvidenceTypes -. VA .-> VAMR[VA medical records]
    EvidenceTypes -. Private<br>only .-> PrivateMrUploadQuestion{Private medical<br>records upload}
    EvidenceTypes -. Supporting<br>only .-> StatementsUploadQuestion{Supporting statements<br>and evidence upload}

    EvidenceSummary[Summary of evidence]
    VAMR -. done .-> EvidenceSummary
    PrivateMrUpload -. done .-> EvidenceSummary
    PrivateProvider -. done - this files<br>form 4142 .-> EvidenceSummary
    StatementsUpload -. done .-> EvidenceSummary

    VAMR -. Supporting<br>selected .-> StatementsUploadQuestion
    VAMR -. Private<br>selected .-> PrivateMrUploadQuestion
    VAMR -. Add facility .-> VAMR

    PrivateMrUploadQuestion -. yes .-> PrivateMrUpload[Upload]
    PrivateMrUpload -. upload another .-> PrivateMrUpload
    PrivateMrUploadQuestion -. no .-> PrivateProvider[Add provider]
    PrivateProvider -. add another .-> PrivateProvider

    StatementsUploadQuestion -. yes .-> StatementsUpload[Upload]
    StatementsUpload -. upload another .-> StatementsUpload

    PrivateMrUpload -. Supporting<br>selected .-> StatementsUploadQuestion
    PrivateProvider -. Supporting<br>selected .-> StatementsUploadQuestion
```

## Tasks

- [x] Add the evidence source path for VA & Private medical records
- [ ] Add upload supporting evidence path
- [ ] Add unit tests
- [x] Discuss document types with Lighthouse

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie @rocio-desantiago Any blockers on this one?
