### ISSUE TITLE
[Design] Payment Info MVP: Update designs to show section when user has no payments but has outstanding debts

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43629]
## Background
As a result of #42911, we determined that there are some discrepancies between how we intended the payment info section to function, how it actually is functioning and the documentation of how it's supposed to function. 

We need to update the logic for when this section displays, specifically in the scenario when a user has never received payments but has an outstanding debt.

**Old logic:** only show the section if we receive information from the payment API.

**New logic:** show the section if we receive any information from the payment API _OR_ if we receive information from the debt API _AND_ the debt API is not _0_ 

The problem with the old (current logic implemented as of 6/28) is that a user could have outstanding debts but if they've never received payments then the section does not display for them.

The language has been updated in the [documentation](https://dsva.slack.com/archives/CBU0KDSB1/p1656433903829369?thread_ts=1656433220.481959&cid=CBU0KDSB1). We now need to make the change in our designs and in the code.

**This is the design ticket to accompany the FE ticket (#43568).**

## Tasks
- [x] Update sketch files to show state when a user has not received a payment but does have outstanding debts 
     - [x] Only show the debt alert
     - [x] Remove secondary links in this use case
- [x] Post a link to the updated sketch files in the comments of this ticket and in #43568 and tag the FE dev/Taylor
- [x] Let FE dev/Taylor know that the designs are complete 

## Acceptance Criteria
- [ ] Confirm that the designs have been updated to reflect the rules outlined in the tasks.

## Validation
**Who can validate this ticket? (FE, BE, Design, PM)** any team member

**How can this work be validated?** 
   - [ ] View the sketch files and check for the documented updates
   - [ ] Check that the new designs have been posted to this ticket and #43568

**Comment by ajakabcin** [comment]
Confirmed updated designs in this sketch file. Thanks @aagosto90 !
