### ISSUE TITLE
[UX][Research] Monitor Metrics

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43631]
## Tasks
- [x] Decide on frequency to monitor the metrics for the Epic
- [x] Monitor the metrics
- [ ] Present to the team

**Comment by loripusey** [comment]
Can we close this one? Now that the MVP is complete, we are moving into more of a phased release phase, which is covered by our normal analytics goal. @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Sure. I was going to close this when I wrapped up the report for the Thurs presentation. But, yeah, you can close it now. That's fine.
