### ISSUE TITLE
FE | Profile | BAI | Update GA Tags 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43632]
## Background
After meeting with Analytics team, it was determined that the tags we were using for BAI needed to be updated. 
They will be providing the updated specs for us to use.

## Tasks
- [ ] Add updated tags from Analytics team

## Acceptance Criteria
- [ ] Test and confirm they are firing off
- [ ] Notify PM to create reporting

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so
