### ISSUE TITLE
Investigate the Customization of the GHA Caching Action

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43637]
# Description
The `actions/cache@v3` action appears to take variable amounts of time to complete. Is there a way to make the action more consistent and reliable?

# Tasks
- [ ] Answer some questions --
  - [x] Should we pursue the customization of the `actions/cache@v3` action?
  - [x] Should we pursue the creation of an entirely new custom action for caching our testing related artifacts?
  - [x] Are there recommended approaches for caching artifacts on self-hosted runners that are hosted in AWS? Is there a way to use fast storage that the self-hosted runners have access to in order to cache the build artifacts and dependencies? We probably aren't the only org who find themselves needing to host self-hosted runners for GHA.
  - [ ] How much more consistent do we expect the new approach to be?

# Acceptance Criteria
- [ ] Options for revising the GHA caching mechanism have been investigated
- [ ] Previous work from other organizations has been examined for use by our org
- [ ] A plan of action for revising caching has been defined

**Comment by rsmithadhoc** [comment]
# Cypress Job Caching

## Problem

- Downloading artifacts and cache in GitHub actions job are slow.
- It uses GitHub's packages `actions/upload-artifact`, `actions/download-artifact`, and `actions/cache`. These are needed because GHA starts with a clean machine with no dependencies for each job, assets don't stay around to use in future jobs. The way to pre-install dependencies is by using self-hosted runners, which we are doing.
- It appears to upload/download these assets to/from GitHub and because we are using self-hosted runners on AWS, these need to be downloaded each time.
  - Example artifact on GitHub: https://github.com/department-of-veterans-affairs/vets-website/runs/7154693102?check_suite_focus=true#step:6:1
  - Example cache on GitHub: https://github.com/department-of-veterans-affairs/vets-website/runs/7154693102?check_suite_focus=true#step:8:1
- There isn't a prescribed way to do this more efficiently, presumably since GitHub Actions, these packages, and self-hosted runners are relatively new.

## Possible Solutions

- Update the self-hosted runner image to install yarn dependencies on start-up.
  - We use `yarn --prefer-offline` in our job, so having packages on the machine may speed things up. We could then remove the usage of the GHA cache from the Cypress job.
  - It may become outdated if we run it on machine start-up and it runs indefinitely unless there is a way to build upon the machine's `node_modules` folder. But the core dependencies of `vets-website` will be there, so downloading additional packages should not take very long.
  - It wouldn't handle production build artifacts.
- Set up a Yarn offline mirror.
  - https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/
  - I'm not sure if this would work, it would need to have the offline cache stored on the self-hosted runner image.
  - It wouldn't handle production build artifacts.
- Custom step to store assets on AWS.
  - Unclear if this would provide many benefits. If it was stored on S3, each run of the job would still need to download it. It might be in the exact server location, but the benefit might not be great.

**Comment by pjhill** [comment]
All that remains is to come to a consensus for for the plan.

**Comment by rsmithadhoc** [comment]
> What can we measure the baseline of in order to verify that our effort to improve the situation is effective?

I think we can look at the time taken for Cypress E2E Tests steps "Download production build artifact" and "Install dependencies". Those run on each of the 8 parallelized test steps and typically take a similar amount of time, so the caching isn't really helping them. However, I don't know if there is a way of getting a collection of stats without manually viewing previous runs and recording how long it took.

**Comment by pjhill** [comment]
This investigation is complete. We have some good information to build a case for a change. Subsequent creation of a new more ideal solution will be addressed in a new ticket.
