### ISSUE TITLE
Interview Platform respondents and record learnings

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43648]
## Issue Description
Based on poll findings, ask more from those participants.  Evaluate their pain points, additional needs, magic wand ideas.

---
## Tasks
- [x] conduct pilot test
- [x] interview participants to glean pain points and potential new features
- [x] take notes of insights learned in interview sessions in [this mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1657304369813/72b75a57566e878cee858ff94a20def87db5bac7?sender=u9ea6bd3ca12795949b606150) (Dan)

## Acceptance Criteria
- [x] List of pain points
- [x] List of potential additional features

**Comment by tayism** [comment]
Adding @twoangstroms to this issue as a note-taker for the study.

**Comment by tayism** [comment]
[Working on recording our learnings here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/edit-v2/2276196387)
