### ISSUE TITLE
Notice of Disagreement | Design v2 field pages

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43646]
## Value Statement

**_As a_** Veteran
**_I want to_** be able to ask for an extension and include a reason, and show that my appeal is for a VHA denial, in my Notice of Disagreement online form
**_So that_** I can provide more information to the Board

## Background Context

Lighthouse has updated their endpoint to match the latest NOD form. Specifically 2 new pages will need to be added to the online form:
- Add an "extension request" yes/no radio question and an "extension reason" input so the Veteran can include a reason for the extension of their request.
- Add an "appeal of VHA denial " checkbox. The Veteran can specify that the NOD is specifically regarding a denial from the VHA

## Tasks

- [ ] Add a extension request & reason page
- [ ] Add a VHA denial checkbox page

## Definition of done

- [ ] All tasks complete
- [ ] Design reviewed & shared with the developers

**Comment by saderagsdale** [comment]
Dupe: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42492

**Comment by saderagsdale** [comment]
@Mottie this is a dupe of #42492, right? We can delete this?

**Comment by Mottie** [comment]
Oh yeah, this is a duplicate.
