### ISSUE TITLE
Assess new decision reviews FAQs sent from stakeholders

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43643]
## Issue Description
Stakeholder Autumn Paschke sent us a new approved version of decision reviews FAQs that she wants our team to add to VA.gov on our [decision reviews FAQs](https://www.va.gov/decision-reviews/faq/) page. 

We need to first review these FAQs to assess which ones should in fact be added. Some of these may already be addressed on our current pages or they might not be Veteran-facing. Some of the information might need to be added to an already existing FAQ.

We don't need to rewrite any of this into plain language at this stage.

Document to assess: [https://app.zenhub.com/files/133843125/602d6f31-3e93-4cd4-9bf2-a0c017ce9128/download](https://app.zenhub.com/files/133843125/602d6f31-3e93-4cd4-9bf2-a0c017ce9128/download)

## Tasks
- [ ] Read through document and assess what content should and shouldn't be added to our current page 
- [ ] Review assessment (Laura)
- [ ] Give feedback to Beth

## Acceptance Criteria
- [ ] FAQs have been assessed and our suggestions given to Beth

**Comment by laurwill** [comment]
Update: We met with Autumn and Lynn this week and came to an agreement not to repeat information in the FAQ that appears on other pages. Here are next steps from that meeting:
- I'll send Autumn and Lynn a more detailed list of where each duplicate Q&A appears in existing content
- I'll look at each new Q&A in more detail and pull out any new info to add to the FAQ page or other existing pages
- We'll move forward with the new "More info" box (and also look into additional cross-linking opportunities)
- We've opened a separate ticket to create a new R&S article around Duty to Assist — Autumn and Lynn let us know that this is a point of confusion, so we'll look into creating a single Q&A or multiple FAQ to surface these answers in search

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO , I finished going through the updated FAQ content in detail. And I now see that **all** of the FAQ content (not just the new sections SME added) falls into these 3 categories:
- Not Veteran-facing
- Covered on existing pages (or will be covered by draft updates to those pages)
- Covered by new draft FAQ on duty to assist

I've noted where each piece of information already appears on our pages and suggested updates to existing pages in Drupal to capture relevant new info. Here's the Word document with my mapping notes:
[Decision reviews FAQ.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9170036/Decision.reviews.FAQ.docx)

Here are previews of draft updates to existing pages. I tried to limit my updates to FAQ-related changes, but I ended suggesting some other changes in order for the FAQ updates to make sense. I noted changes in Drupal comments. (If I went overboard here, we can hold these updates for the full section review.)

- Choosing a decision review: http://preview-prod.vfs.va.gov/preview?nodeId=23290  
- Supplemental Claims: http://preview-prod.vfs.va.gov/preview?nodeId=23290  
- Higher-Level Reviews: http://preview-prod.vfs.va.gov/preview?nodeId=3003   
- Board Appeals: http://preview-prod.vfs.va.gov/preview?nodeId=3029
- After you request a decision review: 
- Manage your legacy VA appeal: 

Let's chat in our 3:30 about this!

**Comment by bethpottsVADEPO** [comment]
@laurwill I've made some edits to the pages you listed above. This all looks great and is ready for your communication back to the stakeholder. Thanks for moving it forward!
