### ISSUE TITLE
Supplemental Claims | Add certification & signature page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43640]
## Value Statement

**_As a_** benefits-team-1 member
**_We want to_** build out the Supplemental Claims form with pages
**_So that_** we can coordinate with team members on the design and flow of the form

## Background Context

The Supplemental Claims (SC) form (20-0995) is in the process of being structured, and this work will add a certification & signature page. There is also an "Alternate signer certification & signature page", but I don't think we need to add this second page until we're sure of the form flow. We may end up reusing this page instead of needing a second page.

[This is the form signature design pattern](https://design.va.gov/patterns/forms/signature). It isn't being used in any of the forms our team supports, but the pattern is used in a few other forms.

## Tasks

- [ ] Add the notice of certification & signature page
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
