### ISSUE TITLE
BE | Profile | Personal Info revisions | Remove BE Feature Flag Logic

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43654]
## Background
Now that we are 100% launched, we need to remove the BE FF `profile_show_demographics` used to phase the launch of the Personal info revisions.

## Tasks
- [x] Remove logic used for this feature flag
- [x] Remove feature flag from all environments

## Acceptance Criteria
- [x] Synch with Adam to remove on FE
- [x] Feature working in staging 
- [x] Feature working in production

**Comment by tpharrison** [comment]
@SKasimow @Samara-Strauss @adamwhitlock1 

I removed the BE feature flag for personal information.  I tested in staging and everything looks good.  I'll test it in production after today's daily deploy.

**Comment by Samara-Strauss** [comment]
Great, thank you!
