### ISSUE TITLE
My VA Redirect: Feature Not Working for some users in Staging and Production

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43660]
## Background
On 6/29 the My VA team was conducting UAT on the My VA Redirect initiative and found some issues with the feature flipper. We turned the feature on for all staging users and some Production users and the results were as follows:

**Production**:
- Taylor Mitchell turned the feature on for himself but was not seeing the redirect
- Samara turned the feature on for AJ, ~and she was not seeing the redirect~ _(update as of 6/29 at 2:36pm, her LOA3 account associated with her Ad Hoc email address was working properly with the redirect)_
- Samara turned the feature on for herself and she is seeing the redirect
- Samara turned the feature on for Liz Lantz and she is seeing the redirect

**Staging**:
- Taylor Mitchell confirmed the feature flag is on for all staging users
- Redirect works for test user 11
- Redirect works for test user 226
- Redirect works for test user 202
- Redirect works for test user 12
- ~Redirect does not work for test user 15~ (as of 7/6 3pm redirect is working for this user on staging)
- ~Redirect does not work for test user 21~ (as of 7/6 3pm redirect is working for this user on staging)
- ~Redirect does not work for test user 0~ (as of 7/6 3pm redirect is working for this user on staging)

## Tasks
- [x] Investigate why the feature flipper for My VA Redirect is inconsistent
- [x] Resolve the issue
- [x] Validate in staging and Production

.

**Comment by ajakabcin** [comment]
@joeniquette and @AGarcia-Clarity -  I tested some of these again and now test users 15, 21 and 0 are working with redirect on staging as intended. I'm not sure why that would be the case when it was turned on for all staging users last week. Is there perhaps a delay or cache happening somewhere?

cc @tmitchellgcio
