### ISSUE TITLE
NOD | Update to use v2 endpoint

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43669]
## Value Statement

**_As a_** Veteran
**_I want to_** be able to ask for an extension and include a reason, and show that my appeal is for a VHA denial, in my Notice of Disagreement online form
**_So that_** I can provide more information to the Board

## Background Context

Lighthouse has updated their endpoint to match the latest NOD form. Specifically 2 new pages will need to be added to the online form:
- Add an "extension request" yes/no radio question and an "extension reason" input so the Veteran can include a reason for the extension of their request.
- Add an "appeal of VHA denial " checkbox. The Veteran can specify that the NOD is specifically regarding a denial from the VHA

**Work dependent on design from https://github.com/department-of-veterans-affairs/va.gov-team/issues/43646**

## Tasks

- [ ] Add a extension request 
- [ ] Add extension reason page, only show if yes on extension request
- [ ] Add a VHA denial checkbox page
- [ ] Return `countryCodeISO2` instead of `countryName` to Lighthouse
- [ ] Update api endpoint
- [ ] Update schema
- [ ] Add form migration
- [ ] Add unit tests
- [ ] Update mock data
- [ ] E2e tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by eileen-coforma** [comment]
@saderagsdale Does this need to go into refinement?

**Comment by saderagsdale** [comment]
@eileen-coforma This is an old ticket and will need refinement. This was last worked by an engineer that's no longer on the team.

**Comment by Mottie** [comment]
Work completed, but associated with #62311
