### ISSUE TITLE
526 | Prevent save-in-progress redirect in non-production

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43678]
## Current behavior

In form 526, if the [save-in-progress menu](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-use-the-save-in-progress-m) is used to add mock data, the save-in-progress API (`v0/disability_compensation_in_progress_forms/21-526EZ`) includes `metadata` with a `returnUrl` set to `/disabilities/rated-disabilities"` - this ignores the set save-in-progress menu return url and you always end up on the rated disabilities page.

## Expected behavior

In a non-production environment, we need to test mock data and thus the save-in-progress API shouldn't change the existing `returnUrl` value. The user testing 526 locally, in staging.va.gov or in dev.va.gov would then be able to continue their form to the page they set in the save-in-progress menu.

## Background context

The save-in-progress menu previously had the expected behavior. When it changed to the current behavior is unknown, but it makes for testing 526 in a non-production environment more difficult.

## Tasks

- [ ] In the 526-specific save-in-progress controller, skip modifying the `returnUrl` in non-production environments
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
