### ISSUE TITLE
[Design] Create 3 Prototypes (Travel reimbursement)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43672]
## Tasks
- [x] Review 18F PCI sketch files 
- [ ] Review the BTSSS files (touch base with Ben) to make sure we understand all of the fields that are required (can also look at the API)
- [x] Recreate the work in Zach's sketch files
- [x] Make sure it fits with the Design System
- [x] Review and confirm content
- [x] Make a Sketch clickthrough

## AC
- we have a prototype to test with users

**Comment by zach-park** [comment]
Sketch.com/s/f055a969-7909-4a63-9bb8-1dcb

**Comment by niradatta1** [comment]
@zach-park and I have created content design recommendations. Next step: review for feedback with @DanielleThierryUSDSVA at office hours this sprint. Will iterate based on feedback and share with team when ready. 'cc @kristenmcconnell @loripusey @benbrasso-agile6

**Comment by niradatta1** [comment]
Reminder that we'll be taking this ticket into next sprint to finalize the designs and sign-off again with site-wide content team.
