### ISSUE TITLE
CST Validation Rules Technical Discovery

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43683]
## Value Statement
**_As a_** product manager
**_I want to_** understand what upstream issues could be resolved via FE data validation
**_So that_**  we can slice the CST Validation Rules epic into smaller, workable user stories 

---
## Background Context
Key information in epic associated with this ticket. 

## Acceptance Criteria
- [ ] _Upstream issues related to document submissions sent from CST identified_

## Designs and Build Notes
- Add here

## Out of scope
- Upstream problems with document acceptance with sources that are not CST

## Open questions
- What upstream issues with systems unable to accept documents and other user data can be solved with validation rules implemented at the application level? 
- What is the level of effort required to implement each opportunity identified? 

## Tasks
- [ ] _Invite Sam to Lighthouse weekly touchpoint (Jacob)_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jacobworrell** [comment]
@samcoforma did some digging into reasons upstream services will reject a pdf: 

- Uploaded documents cannot be larger than 21" x 21" page dimension
- The entire payload cannot exceed 5 GB (all files together)
- No single file in a payload can exceed 100 MB
- No passwords on the PDF (owner or user)
- PDF file type only

> Kelly Lein from Lighthouse also says: 
> You can always refer to our documentation here; https://dev-developer.va.gov/explore/benefits/docs/benefits?version=current
> Like you may have seen in other threads, the upstream systems we send the files to are fairly opaque as far as their validations.  We have asked for more details and the libraries they use to validate the PDFs and due to the way their contracts work they can’t/won’t share that information.  Premal is going to work on that though.
