### ISSUE TITLE
[BE] Add statsd metrics for Demographics Controller

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#43680]
## User Story
As a check-in team member, I want to be able to view the metrics associated with Demographics endpoint so I can have a better idea of its usage and performance

## Tasks
- [ ] [BE] Add statsd metric to the code
- [ ] update datadog dashboard to include the metric: https://vagov.ddog-gov.com/dashboard/zps-5fk-azw/check-in-vets-api?from_ts=1656458066506&to_ts=1656544466506&live=true

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
