### ISSUE TITLE
Remove action link and rework content on How to request a home loan COE page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43705]
## Issue Description

On our [How to request a VA home loan Certificate of Eligibility (COE) page](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) we need to remove the action link pointing to eBenefits. Once you click the link, it's not taking the user anywhere useful.

When we remove the link we also need to rework the content surrounding it so we're not saying "you can request your COE online right now."

For background, we are rolling out an online COE tool and will eventually have an action link point to that. But for now, we should only have the other options underneath (through LGY and by mail).

Beth also asked us to assess whether using the name of the LGY tool is needed or if it might be confusing since it's not spelled out.

Her note in the original intake request ticket: This isn't defined because it's the name of a tool (our Web LGY system). If LGY were standing alone in running text, we definitely would. Thank you for raising it though. I'll make a note to consider how we might reword the text. It might not be necessary to use the exact name of the tool. Will have the team assess!

## Tasks
- [ ] Remove action link and rework surrounding content
- [ ] Consider rewording LGY info
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Post in original intake ticket #43350 that changes are live (Randi)

## Acceptance Criteria
- [ ] Action link removed and text revised on live page

**Comment by aliyahblackmore** [comment]
Hi @laurwill - sharing my drafted content here! As noted in the doc, there are two questions that we just need some more info on!
[How to request a home loan COE page_AB_7.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9057814/How.to.request.a.home.loan.COE.page_AB_7.5.docx)

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! As discussed, the update was made in Drupal! 

Preview link: 
(http://preview-prod.vfs.va.gov/preview?nodeId=754)

I also wanted to flag something that I noticed re: the form and the mail option: 
The content around the mail option isn't in the scope of the request for this ticket, but I noticed that there could maybe be some more clarity around where the form should be mailed. When you go to the form, the instruction is to mail the form to the "regional loan center of jurisdiction on page 3."  Can we make any content suggestions here to something along the lines of "...mail it to your regional loan center listed on the form."

**Comment by laurwill** [comment]
Thanks Aliyah! Looks good, and I made a little tweak to that mailing address note as you suggested (split it into 2 sentences since it was getting a little long). @RLHecht , this is ready for you to review (in place of Beth.)

**Comment by RLHecht** [comment]
This looks good to me. @megzehn This is ready for you.

**Comment by megzehn** [comment]
This is published, @RLHecht!

Saving 2 questions/action items for the next time we work on this page: 

- Consider adding a sentence or finding a PL alternative for "guaranty of value" in this paragraph: 

"The lender will request a VA appraisal (assessment) of the house. An appraisal estimates the house’s market value at the time of inspection. An appraisal isn’t a home inspection or a **guaranty of value**."

- Consider moving this link somewhere in the related accordion right above it. Maybe. 

**“Find out how to request a COE as a surviving spouse”**
