### ISSUE TITLE
FE | Profile | New Forms Library POC

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#43727]
## Background

The Forms Library spike team has been working on a new version of the forms library that will enable any team to easily spin up and build any forms that are needed to support the products and features that serve Veterans on VA.gov.

We'd like to gain a better understanding of the level of effort and work needed to leverage this new library and identify any obstacles, by standing up a PoC. This will also help inform how we sequence the the additional fields that will need to be updated eventually.

Dev recommends starting with the phone number fields (**Mark** - should we pick one field such as "home" number or would "work" and "mobile" be part of the same effort?).

There have been several issues that we believe can be corrected with this effort including more specific error messaging and improvements for accessibility.

## Tasks
- [x] Add feature toggle for `profile_use_vafsc`
- [x] Add Home Phone field using new forms system
- [x] Create compatibility layer for transactions to use form system with transactions
- [x] Document any issues with VAFSC for Home Phone field
- [ ] Validate home phone field functionality in staging

## Acceptance Criteria
- [ ] Field allows updates to be made to form field

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
This will roll over as the transactional system and phone number logic is more complex than expected.

The branch for the current work is here:

https://github.com/department-of-veterans-affairs/vets-website/tree/Profile/43727/phone-number-using-new-forms-system

Work completed or partially finished
- Feature toggle created around using new forms system
- New 'edit view' component created to conditionally render forms with new VAFSC
- HomePhone component created using VAFSC
  - Field created with field validation for phone length and being required
  - Field edits trigger the modal shown when unsaved and another field is clicked on
  - Submission logic started
  - Redux actions dispatched to update field value and 'legacy' field state update for backwards compat

Work remaining:
- Transactional api call compatibility with VAFSC field
- Accessibility work specifically around focus management when entering edit mode
- Unit and E2E testing for new components and logic
- Error handling compatibility

**Comment by adamwhitlock1** [comment]
This field can now be validated in staging @SKasimow and @Samara-Strauss 

![formik-in-profile.gif](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/de835688-a2d2-4dd2-a28f-f5e5738638e5)

**Comment by adamwhitlock1** [comment]
Some things to note on this implementation.

Some styling tweaks need to be made:
 - The font is not correct for the text inside the field. It is defaulting to arial, and not the usual Source Sans Pro. The VAFSC team has been made aware of this issue and is investigating the cause.
 - some spacing may need to be adjusted

Validation concerns:
 - the old form system would validate the number when the field was blurred (mouse clicked off the field in some way). The new forms system validates after _every_ input, so while you are typing and the phone number doesnt have 10 digits the validation error displays. If we want to validate just on blur, then I will need to modify this to work and probably bring that up with the VAFSC for a unified approach to the approved method to do that.

**Comment by Samara-Strauss** [comment]
Validated this with user 36. Besides the font/spacing issues you already mentioned, everything looks good.

**Comment by SKasimow** [comment]
Nice work! I validated with user 107. 

Validating once user goes outside the field would be preferable...otherwise it looks like we are telling users they have an error before they complete their entry. Not a good UX.

**Comment by mtcA6** [comment]
Hey @adamwhitlock1 for work like this that's semi-completed that stalls, what's the process for cleaning this up so we don't have code behind feature flags that ends up not being utilized.

**Comment by adamwhitlock1** [comment]
We don't really have a process for this. The form system work _may_ get picked back up (at least that was the word on the street).

I think we will need to make a judgement call at some point to decide whether we just want to rip this all out, and I can take up the work if/when the new form system does get completed.
