### ISSUE TITLE
Inventory claims status data fields available via current vets-api end point

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43729]
## Value Statement
**_As a_** product manager
**_I want to_** know what possible types of data related to claims status are available via the current vets-api claims end point(s)
**_So that_** we can efficiently iterate our design, content, and development approaches and meet our product objectives.

---
## Background Context
- Add here

## Acceptance Criteria
- [x] _Fields currently being used by CST identified and documented_
- [x] _Fields not currently used but available via existing end points identified and documented_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value discription_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jacobworrell** [comment]
Update here: I am working with Kayla Wantanabe from the Lighthouse team to obtain the claims status data schema available. I expect her to respond before the end of the week.
