### ISSUE TITLE
Forms Dashboard:  Revised "Time to Complete" Metrics (continued)

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43737]
## Issue Description
This is a continuation of [ticket 31789](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31789) from Q2.  This will likely span multiple sprints.

We need to revised how we calculate time to complete metrics for the Forms Dashboard.  

---
## Tasks
- [ ] Revised calculations are defined and documented
- [ ] New calculations are QA'd and approved
- [ ] Forms dashboard has been updated with new calculations

## Acceptance Criteria
- [ ] Forms dashboard has been updated with new metrics
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AdamOye** [comment]
**Closing this ticket as part of backlog cleanup.**
This work is no longer prioritized, is outdated, or has been addressed elsewhere.
If this resurfaces as a need in the future, we can refile with updated context.
