### ISSUE TITLE
[UX] Submit Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43732]
## Tasks
- [ ] Create JSON file with new content to be translated
- [ ] Do a diff between the English json file and each non-English json file to ensure all keys that we need translated have been included in the new submission file
- [ ] Submit JSON file to the State Department

## Acceptance Criteria
- [ ] JSON file has been submitted to the State Department

**Comment by loripusey** [comment]
Following files sent to Randi Hecht on 10/18/2022 requesting translation from the State Department:
