### ISSUE TITLE
[Product] Send Workflow documents to State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43739]
## Tasks
- [x] Create workflow documents that contain sceenshots for the Epic/feature
- [x] Submit documents to the State Department

## Acceptance Criteria
- [x] Workflow documents have been submitted to Daniell Thierry and she will submit to the State Department

**Comment by loripusey** [comment]
Screenshots sent on 7/19/2022; waiting on QA from State Department
