### ISSUE TITLE
[Product] Send QA Workflows to State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43734]
## Tasks
- [ ] Create workflow documents that contain screenshots for the Epic/feature
- [ ] Submit documents to the Randi Hecht 

## Acceptance Criteria
- [ ] Workflow documents have been submitted to Randi Hecht for forwarding to the State Department

**Comment by loripusey** [comment]
QA [screenshots ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/spanish-round-3/Spanish%20-%20Round%203_2022-11-28_20-30-21.pdf)sent to Randi on 11/28/2022
