### ISSUE TITLE
[FE] My VA: Update Health Care Section Logic

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#43730]
## Background
Based on our analysis in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42702) we want to refactor the code for the Healthcare section on My VA. Mark had implemented a short term fix for this section but recommended a refactor since the code is not optimized.

## Tasks
- [x] Refactor the code to include one conditional return versus many
- [x] Validate
- [ ] Push change to Production

## Acceptance Criteria
- [ ] The Healthcare section is able to show the Cerner message and healthcare section header. The code is optimized to only include one conditional return.

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ FE, PM
- _How can this work be validated?_ Code review, validate functionality in staging

**Comment by tmitchellgcio** [comment]
@ajakabcin this is ready for validation. Remember we need someone with SOCKS access to validate this.
Environment: http://2b4517cc598538fb8e2c15397365c041.review.vetsgov-internal/

**Comment by ericasauv09** [comment]
was able to validate with user 81:<img width="1122" alt="Screen Shot 2022-07-07 at 14 13 53" src="https://user-images.githubusercontent.com/97113607/177841498-63a590a7-5980-4607-85bc-6878965a3c10.png">

**Comment by ericasauv09** [comment]
validated in Staging as well with the same user
