### ISSUE TITLE
Create Tickets  for each application team on the updates to the address form

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4374]
## Background:
In our ongoing effort to understand how the address form design can be impacted by other application teams, we need to create tickets to submit to the various teams backlogs for the work that has to be done on their end for Auth Exp team to fulfill the correct form updates.  Organize tickets for benefit teams in a clear way.
Create and assign tickets to Benefit and Memorials teams 1 & 2 for the recommended application updates.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Gain a general consensus we have gathered all the forms that will be impacted by this work. - Arthur/Justin/Samara
- [x] Create tickets to assign to Benefit and Memorials teams 1 & 2 for the recommended application updates. - Justin & Arthur
- [x] Regroup with team lead to discuss findings and information on how heavy of a lift this work will be and if our team will be responsible for the updates to the forms for other teams.- Team

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [x] Tickets have been created and properly assign to correct team backlogs for monitoring
- [x] Team has been updated on overall plan of action

**Comment by Samara-Strauss** [comment]
@Justin-Pickett @artistgreen hello! Thanks for putting together [this spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefits-applciations-list.md). I've reviewed it and wanted to get back to you on how I think you should organize tickets for the other teams who would be implementing the application updates:

1. Create a ticket for each benefit type:
- The disability application
- All of the education applications
  - Please include a clear list of all of the education applications in this ticket.
- All of the burial applications
  - Please list both of the burial applications in this ticket.
- The pension application
- The health care application
- The VA letters form
2. In that ticket, give some background on the APO/DPO/FPO work we did in the profile. You don't need to include profile screenshots or go into tons of detail, but background on this problem and the profile work is necessary to understand why we're making the suggestion that the benefit applications be updated. It's probably a good idea to link to the FE implementation ticket for the profile work so they have access to more info if they want it.
3. Include screenshots/explanations of how the address section needs to be updated. Given that the address form is similar in most applications (to the best of my knowledge), you don't need to create new mockups for each application. I would recommend outlining things similarly to how you have it [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3895#issuecomment-564366761).

Let me know if that is clear or not or if you have any questions. Once you have tickets drafted, please send them to me for review/approval. Note that you probably just need one template you can use for all the tickets. Just remember to take care to make sure you're addressing the right applications in the right tickets.

**Comment by Samara-Strauss** [comment]
@Justin-Pickett @artistgreen can I please see a draft of the ticket template you're creating for each application?

**Comment by Justin-Pickett** [comment]
@Samara-Strauss sure thing -  Below is a concept of how the tickets will be constructed for "each" benefit form that will be impacted by the changes for the APO/FPO/DPO work. Please let share you suggestions or thoughts on this approach. I will be working with @artistgreen to get each ticket groomed to house the appropriate info and mock ups needed for each ticket. 


## Background:  
Propose solution for how to handle military addresses in (Specific Benfefit) Application that use VA Profile data. 

## User Story: 

As a (team member of benefit team), I need propose a solution for how to handle military addresses in benefit applications that use VA Profile data. 

## Tasks 

The steps that must be done by the team to complete the acceptance criteria 

- [ ] Technical discovery –Identified form that  will be affected (attached link to specific benefit form) 

- [ ] Design mock ups – attached design mock up of specific form 

- [ ] Review with Benefits team 


## Design MockUps 
This is where the design mock ups will be uploaded

## Acceptance Criteria: 

The requirements that must be met in order to mark this user story as completed 

- [ ]  Design mock ups have been uploaded 

- [ ]  Review and approval from Benefits team or team member assigned to the ticket

**Comment by Samara-Strauss** [comment]
@Justin-Pickett @artistgreen 

1. @Justin-Pickett I have mentioned this before, but remember a user story should *NEVER* be from the perspective of the contractor doing the work. They are *ALWAYS* from the perspective of the end user on VA.gov, which is a veteran or service member in most cases unless specified otherwise. Please review with Adam or Mickin if you are unclear on how to do this.
2. I apologize if the ask for this ticket (4374) was not clear, but you were supposed to outline exactly what other teams needed to execute on this work, and I don't see that above. There wasn't proper background on our work or the work we need them to do, the user story wasn't a user story, the tasks/acceptance criteria are half for Arthur to add design mocks (which is NOT something you would include in a ticket for another team), and design mocks have not been added. The objective of these tickets is that other teams, as they have time, implement the APO/FPO/DPO updates to each benefit application, and I don't see that clearly outlined as a task or in the acceptance criteria. If were to get the above as someone on another team, I would have no idea what I was supposed to do with it or what my objective was. That's concerning to me.

If you all are feeling confused about what should be included in this and other tickets, please ask. I can only help as much as I know you have questions, but I'd like to not have to be so heavily involved in ticket writing going forward.

Otherwise, below are my edits. Please let me know if you have any questions or feedback.

-----

## User Story: 

As a person who lives on an overseas military base, I should not be able to list any other country besides the United States in my address in the VA.gov profile or on any VA benefit applications.

## Background:  

The authenticated experience team has been working on an update to the user profile that will allow for better error handling of overseas military base addresses ([details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4386#issuecomment-568466453)). This is the TL;DR: currently, all address forms on VA.gov allow people to enter a country other than the United States if a person lives on an overseas military base even though US military bases are technically considered to be in the United States no matter where they are on the map. The updates we are making to the profile will allow a person to indicate they live on an overseas military base, and it will also prevent a person who lives on an overseas military base from selecting a country other than the United States.

Our team recommends that similar updates be made to the address forms in each of the benefit applications. However, these application updates do not need to happen immediately, and the profile updates we made are not dependent on the benefit applications also being updated. Updates to the benefit applications can happen any time and can be triaged accordingly depending on the priority of other work.

## Design MockUps 

This is where the design mock ups will be uploaded

## Tasks 

The steps that must be done by the team to complete the acceptance criteria 

- [ ] Review this ticket
- [ ] If necessary, meet with members of the authenticated experience team to answer any questions
- [ ] Implement address updates for [form name/number]

## Acceptance Criteria: 

The requirements that must be met in order to mark this user story as completed 

- [ ]  Address section of [form name/number] has been updated to better handle APO/FPO/DPO addresses

**Comment by Samara-Strauss** [comment]
This ticket is not done as no tickets were ever created and no resolution happened with the other teams. Reassigning this to myself.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss  Oh sorry, i closed this one because I broke out the individual tickets for the various forms in their own tickets.  So I had closed this one. But we can leave it open.

**Comment by Samara-Strauss** [comment]
Can you link each ticket here?

**Comment by Justin-Pickett** [comment]
Sure thing. 

## Tickets for potential address modal form changes to be discussed with other teams

- [ ] #4537 - Disability forms
- [ ] #4540-  Education forms
- [ ] #4543-  Burial forms
- [ ] #4580 - Pension forms
- [ ] #4583 - Health Care forms
- [ ] #4584 - VA Records forms

**Comment by Samara-Strauss** [comment]
OK, thank you. I will take it from here.

**Comment by Samara-Strauss** [comment]
Latest update: created [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/apo-fpo-dpo/benefit%20application%20update%20proposal.md) to share with benefit teams PMs. Currently working to get a meeting set up with them to review before handing off tickets.

**Comment by Samara-Strauss** [comment]
I met with both apps teams and explained the task. Tickets have been updated and officially handed off. Closing!

**Comment by Mottie** [comment]
I was just assigned #4537 this sprint. It seems to me that it would make more sense to add a new global form component to handle these changes, and then have each form switch over to using it.

It would be far easier to change the forms to use a new component and update the unit & e2e tests than it would be to duplicate & make the same work consistent in 6 different forms. We would also need to update the build process in the `vets-json-schema` repository as well.

**Comment by Samara-Strauss** [comment]
@Mottie thanks for keeping me posted! How you go about updating the applications is up to you — my tickets weren't meant to be prescriptive of method but to show the desired end state.

Also, since this ticket is closed, we shouldn't be having further conversation here. Let's move this conversation elsewhere if it's necessary to continue.
