### ISSUE TITLE
Continuously improve Platform security posture and maintain ATO

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#43748]
## Problem Statement 
In order to maintain a VA Authorization to Operate (ATO), there are numerous scheduled monthly, quarterly, and annual authorization requirements that must be completed.  There is a considerable amount of security debt currently owed on these requirements as they have not been previously satisfactorily completed and in some cases not attempted.  Platform must not only conform to these routine authorization requirements, but also to the NIST control requirements that are part of the Risk Management Framework within the VA's Governance, Risk and Compliance tool, eMASS, in order to maintain and eventually renew our current ATO as part of the VA's Assessment and Authorization (A&A) process.  

As part of the effort to come into compliance with these routine authorization tasks and control requirements, Platform Security is looking to use this as an opportunity to not only participate in a compliance paperwork exercise, but to use the RMF process and authorization requirements as a guide to implement meaningful operational security process improvements in an effort to continuously elevate the Platform security posture.

## Hypothesis or Bet
As we continue to come further into compliance with routine authorization requirements and align our processes to meet the control requirements, not only will we position Platform for favorable adjudication of ATO renewal but will also elevate the actual operational security of the entire system along the way.

## We will know we're done when... ("Definition of Done")
Continuous monitoring and improvement of security posture is, by definition, never done.  

However, we have identified the following major tasks that are ongoing during this quarter as part of this effort, each linked to issues in our platform security repo that is not public due to the sensitive security content.

- [ ] [Annual WASA requirement performed, and findings remediated.]( https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/issues/department-of-veterans-affairs/platform-security/113)
- [ ] [Annual Pen Test requirement findings remediated.](https://github.com/department-of-veterans-affairs/platform-security/issues/109)
- [ ] [Annual DB scan requirement performed, and findings remediated.](https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/issues/department-of-veterans-affairs/platform-security/114)
- [ ] [Annual Security Testing requirement performed and findings remediated.](https://github.com/department-of-veterans-affairs/platform-security/issues/110)
- [ ] [Annual Application Threat Model requirement performed](https://github.com/department-of-veterans-affairs/platform-security/issues/115)
- [ ] [Quarterly SCCD scan requirement performed, and 90% compliance achieved](https://github.com/department-of-veterans-affairs/platform-security/issues/117)
- [ ] [Monthly Nessus scan requirement performed and findings remediated](https://github.com/department-of-veterans-affairs/platform-security/issues/142)
- [ ] [Implement SIEM](https://github.com/department-of-veterans-affairs/platform-security/issues/25)

## Known Blockers/Dependencies 
These efforts are dependent on the cooperation of relevant stakeholders, and we expect it will generate a considerable amount of effort needed to remediate findings once identified by various scans.

## Projected Launch Date
Ongoing

**Comment by gary-fallon** [comment]
This is a duplicate.
