### ISSUE TITLE
Create editing checklist for Vet Centers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43742]
## Issue Description
Now that the content team is reviewing Vet Center pages, we need to create a checklist  similar to our pre-publishing checklist to make sure content is clean and meets our plain language and VA.gov style standards. We should review this checklist before we pass to Jessica and Tiffany for their final review.

## Tasks
- [x] Create checklist (Megan/Randi)
- [x] Share list with Tiffany and Jessica to see if anything more should be added (Randi)
- [x] Post final checklist in Github (Randi

## Acceptance Criteria
- [ ] Checklist is created for our team to work from when reviewing Vet Centers

**Comment by RLHecht** [comment]
@megzehn I added more to the checklist in our Google doc. Can you take a look and if you think it's good I can put it in a word doc to share with Jessica and Tiffany. Thanks!

**Comment by RLHecht** [comment]
Posting our final version here, which I'm sharing with Jessica and team. [https://app.zenhub.com/files/133843125/1f64a330-1272-4ddf-a13f-2f6819eb52e0/download](https://app.zenhub.com/files/133843125/1f64a330-1272-4ddf-a13f-2f6819eb52e0/download)

**Comment by RLHecht** [comment]
I created this doc in github and added the 2 areas Tiffany mentioned: That the intro text shouldn't be changed and the What to bring section should be copied from the workbook. Thanks for all your work on this @megzehn Closing this ticket!
