### ISSUE TITLE
Update rate on NADL page--HOLD TO PUBLISH UNTIL 7/11

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43752]
## Issue Description
Stakeholder Raleigh Contreras informed us the interest rate for NADL is increasing effective July 11, 2022, to **5.25%**

We need to change this on the [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. We should publish this on 7/11. 

The rate is in the fourth bullet under the H2 Why might I want to get an NADL?

## Tasks
- [x] Update rate (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish page (Megan)
- [x] Alert stakeholder change is live (Randi)

## Acceptance Criteria
- [x] Rate is 5.25% as of July 11 on live site

**Comment by megzehn** [comment]
This has been copyedited and published. Over to you, @RLHecht!

**Comment by RLHecht** [comment]
Thanks all! This page is now live and I let the stakeholder know. Closing the ticket.
