### ISSUE TITLE
BE - Auth Profile - Military Info - Add data source field to service history for GA

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#43754]
## Background
The profile uses a feature toggle called `profile_get_military_info_from_vaprofile` that when flipped on will retrieve service history from VA Profile instead of eMIS.  When this toggle is flipped on for a percentage of users, it is difficult to determine in Google Analytics which external service the data was retrieved from.

Add a "data_source" field to the response that indicates which external service was called (VA Profile or eMIS).

## Tasks
- [ ] Add a `data_source` field to the `v0/profile/service_history` response.

## Acceptance Criteria
- [ ] When feature toggle is `on`, ensure that service history calls from the profile page have a data_source field of "VA Profile".
- [ ] When feature toggle is `off`, ensure that service history calls from the profile page have a data_source field of "eMIS".

**Comment by tpharrison** [comment]
@SKasimow - yep...probably due to the saving error.
