### ISSUE TITLE
BE - Auth Profile - Military Info - Add data source field to service history for GA

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#43755]
## Background
The profile uses a feature toggle called `profile_get_military_info_from_vaprofile` that when flipped on will retrieve service history from VA Profile instead of eMIS.  When this toggle is flipped on for a percentage of users, it is difficult to determine in Google Analytics which external service the data was retrieved from.

Add a "data_source" field to the response that indicates which external service was called (`api.va_profile` or `api.emis`).

## Tasks
- [x] Add a `data_source` field to the `v0/profile/service_history` response.

## Acceptance Criteria
In staging...
- [x] When feature toggle is `on`, ensure that service history calls from the profile page have a data_source field with a value of `api.va_profile`.
- [x] When feature toggle is `off`, ensure that service history calls from the profile page have a data_source field with a value of `api.emis`.

**Comment by tpharrison** [comment]
@adamwhitlock1 - based on our conversation yesterday, I added a `data_source` field to the service-history response that is returned from the vets-api (see above). Hopefully this helps visibility into which calls used eMIS vs VA Profile in GA. I verified in staging.

cc/ @mdewey @SKasimow @Samara-Strauss

**Comment by SKasimow** [comment]
#44075 is the FE ticket for this work and I slotted for Sprint 78.
