### ISSUE TITLE
[PM] My VA Redirect: Prep for and complete privacy/security review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#43768]
## Background
We need to prep for and submit our privacy and security review for the My VA redirect.

## Tasks
- [ ] Compile documentation outlined [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)
- [ ] Submit [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [ ] Complete any follow up tasks

## Acceptance Criteria
- [ ] Documentation prepped, ticket submitted

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ APM
- _How can this work be validated?_ confirm prep materials are documented/completed and ticket submitted

**Comment by ajakabcin** [comment]
duplicate ticket
