### ISSUE TITLE
Make corrections to Collaboration Cycle pages on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43774]
## User Story
As a VFS team member, I want to know that the Collaboration Cycle pages on Platform Website are correct and up to date so that I know I am following the latest guidance.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
Update "Contact Us" page
Update "Resources" page re: scheduling calendars in Calendly
Remove references to "kickoff" on non-Governance team owned Touchpoint pages

Note: This ticket is a merger of tickets #42814, #42815, and #42586. All tickets have been closed.

## Impacted Artifacts
[Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
[Resources](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources)
[Research Review touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781891143/Research+review)
[Sitewide Content and IA intake request touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/2124906551/Sitewide+Content+and+IA+intake+request)
[Analytics Request touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782120453/Analytics+request)
[Contact Center Review touchpoint](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317061/Contact+center+review)

## Tasks
- "Contact Us" page
   - [x] Refine "Questions" section (first 2 bullets) so it is up to date with Collaboration Cycle Request references (July 13 after speaking with Shira and Chase we are only changing the first bullet point)
- "Resources" page
   - [x] Remove links (not text) for DI/MPR Calendar and Staging Review calendar
   - [x] Modify instructional sentence to remove "use this" 
   - [x] Merge italicized content with instructional sentence
- Touchpoint pages
 - [x] Touchpoint pages needing modification:
    - [x] Research Review
    - [x] Sitewide Content and IA intake request
    - [x] Analytics Request
    - [x] Contact Center Review
 - [x] Update instructional sentence so that it references the Collaboration Cycle Request, not kickoff  

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] References to Collaboration Cycle Kickoff _ticket_ have been removed
- [x] VFS teams are only accessing and scheduling through their Collaboration Cycle Request template

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@briandeconinck please review the following page:

- [Resources](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources)

- [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)

- [Research Review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781891143/Research+review)

-  [Sitewide Content and IA intake request](https://vfs.atlassian.net/wiki/spaces/CC/pages/2124906551/Sitewide+Content+and+IA+intake+request)

 

- [Analytics Request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782120453/Analytics+request)

[ Contact Center Review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317061/Contact+center+review)

**Comment by briandeconinck** [comment]
This all looks good @allison0034!

**Comment by allison0034** [comment]
@shiragoodman @chaseakirby this will go live tomorrow.

**Comment by allison0034** [comment]
@shiragoodman confirmed these are live. Closing ticket.
