### ISSUE TITLE
[DISCOVERY] Determine if CDP is eligible for Datadog access and next steps

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#43779]
## Issue Description
We would like to setup a Datadog dashboard to track our services related to the combined debt portal (debts + medical copays). We have heard before platform was restricting datadog usage for certain products but we would like to revisit. Check with necessary contacts within platform to establish use case for Datadog and how to proceed with setting up the dashboard.

---
## Tasks
- [x] Followup with platform to discuss datadog connections
- [ ] If applicable, detail next steps

## Acceptance Criteria
- [x] We know whether we can continue with setting up datadog and how to proceed 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Recent updates from platform about DataDog:

* Migrated to new DataDog (GovCloud) account at the end of June, the old commercial account is no longer in use. 
    * [Additional Details](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/23513)
* They are currently identifying products that have mission-critical production needs
* Officially, the platform hasn't made Datadog available to VFS teams. But, there is planned initiative to do so
    * [Additional Details](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081)
    * We are still able to generate a ticket requesting access and outline our use case ([Example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43996))
