### ISSUE TITLE
Make corrections to Collab Cycle Request Template, post kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43773]
## User Story
As a Governance team member, I want to make sure that the Collaboration Cycle Request Template, post kickoff (AKA code blocks), provides correct and up to date guidance to VFS teams on the various Collaboration Cycle touchpoints so that the process is consistent and dependable for VFS teams.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
Continuity check: Refine VFS actions post-meeting
Continuity check: references to Platform Website touchpoint pages are included in the Collab Cycle Request template
Continuity check: Add specific verbiage for attaching artifacts only in the Artifacts section
Continuity Check: VFS actions consistent in each Gov team touchpoint

Note: This ticket is a merger of tickets #42850, #42832, #42827 and #42828. All tickets have been closed.

## Impacted Artifacts
[Collaboration Cycle Request Touchpoint Templates](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Draft - Collaboration Cycle Request Touchpoint Templates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2275901449/Cheryl+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Create draft document in Governance team Confluence space
   - [x] VFS actions before meeting (with reference to PW touchpoint page)
   - [x] VFS actions post meeting
   - [x] Artifacts (attaching artifacts in space provided and not linking in comments)
 - [x] Once approved, merge specific touchpoint instructions back in

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams see consistent instructions from touchpoint to touchpoint
- [x] VFS teams know they should not link artifacts in the comments section
- [x] VFS teams are able to easily reference the PW guidance for the specific touchpoint from their Collab Cycle Request ticket

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@CherylEvans correct. Your Draft should be of the CC Kickoff - Moderator Responsibilities doc. The various "code blocks" are what get integrated into the template. Right now, only Midpoint Review touchpoint page is referenced (and linked out) in the Midpoint Review section, however it's referenced in a way where we cannot repeat that language in Design Intent and Staging. So instead, let's find a new way to:

- guide the VFS team to review the Design Intent touchpoint pages (in the Design Intent section), 
- guide the VFS team to review the Midpoint Review touchpoint page (in the Midpoint Review section), and 
- guide the VFS team to review the Staging Review touchpoint page (in the Staging Review section) 

I am not sure why Refine VFS Actions post meeting was formatted as a link. It should not be linking to anything specific. I removed it.

**Comment by CherylEvans** [comment]
@shiragoodman Thank you for clarifying!  I should definitely finish tomorrow, and will tag Allison for peer review.

**Comment by CherylEvans** [comment]
@Allison Christman Hi Allison.  I am ready for you to review my changes, with regard to ticket 43773: ZenHub 
I added PW links to each touchpoint, and also added the needed verbiage to the each touchpoint’s Artifacts section.  Thank you!! :slight_smile: 
@Shira Goodman I wasn’t sure what specifically needed to change in the Post Meeting section.  Please advise.

**Comment by shiragoodman** [comment]
@CherylEvans right now, the VFS action post-meeting for DI, MPR and SR is, "Respond to feedback tickets." We don't want them to just respond. I think we can change it to, "Review feedback tickets and comment on the ticket if there are any questions or concerns."

**Comment by allison0034** [comment]
@CherylEvans can you please link the documents you changed/added?

**Comment by allison0034** [comment]
Is [this](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2275901449/Cheryl+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) the page I need to review? 

If so I have a quick question, we say...
 "Navigate to reference link:"
 for each touch point and they have to go to that link. Is there any reason why we tell them they need to go to that page? Looking at the directions they just go to that page and then do nothing.

**Comment by CherylEvans** [comment]
@allison0034 I linked it in the comments above, and I also linked my Draft in the Impacted Artifacts section, above.

**Comment by CherylEvans** [comment]
@allison0034 Prior to my edits, MPR was the only template that contained a reference to PW Touchpoint pages.  The link is being added for "reference" only, per the guidance in the ticket. I also added verbiage to each template with regard to artifacts: "Add all artifacts **ONLY** in the specific, designated practice area sections below.  **Do NOT add artifacts to Comments section**"

**Comment by shiragoodman** [comment]
looks good @CherylEvans . Closing!
