### ISSUE TITLE
Make corrections to Collaboration Cycle Request template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#43772]
## User Story
As a Governance team member, I want to make sure that the Collaboration Cycle Request template is free of errors so that VFS teams do not have issues when completing it.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
Remove governance-team label from request template
Add   "dynamic pages" to "Will your work involve changes to"   question

Note: This ticket is a merger of tickets #42807 and #42584. Both tickets have been closed.

## Impacted Artifacts
[Collab cycle Request yaml template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)
[Collab Cycle Kickoff PW page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+Cycle+Kickoff)

## Tasks
- Template:
- [x] Remove `governance-team `label from template
- [x] Change "tools and applications" under "Will your work involve changes to:" question to "Tools, applications and dynamic pages"
- Collab Cycle Kickoff page on PW:
- [x] Once label has been removed and PR approved and merged, update Collab cycle Request template link on [Collab Cycle Kickoff ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)page
- [x] Change "tools and applications" under "Will your work involve changes to:" question to "Tools, applications and dynamic pages"

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Collab Cycle Request tickets no longer show up on the Platform Governance Zenhub board
- [x] VFS teams have further clarification on tools, applications and dynamic pages

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
@CherylEvans I have tagged you on the [PR for updating the template](https://github.com/department-of-veterans-affairs/va.gov-team/pull/44099) and I've updated the CC Kickoff page for Platform website with the change to the dropdown option. I'll finish the last link update once the PR is merged and there's a new URL for the template.

Let me know if you need anything else from me!

**Comment by briandeconinck** [comment]
PR merged; link now updated on the Collaboration Cycle Kickoff page. Will be on Platform website when updates are published today.
