### ISSUE TITLE
Add content from the new draft education rates landing page into original rates landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43783]
## Issue Description
We currently have a draft version of a new education rates landing page in Drupal that we started when we were building out our modernized rates pages. We need to take this content (links to all our new modernized rates pages) and move it to the original Drupal education rates landing page. We would get rid of the old intro text and links to the legacy rates pages. We are doing this because we already have the url established and we want to keep the same Drupal node ID.

Our current landing page: https://www.va.gov/education/benefit-rates/
Draft version of new landing page: preview-prod.vfs.va.gov/preview?nodeId=1007

When we move these new links to the current page, we need to figure out a place for the Monthly Housing Allowance R&S page that was created. Since this is now not a rates page, it shouldn't go in the regular list. It might need to be added as a related link at the bottom of the page. Also note that the resident rate requirements page is not a rates page so shouldn't be linked on here. 

We will do a copyedit and publishing at a later date, not in this ticket.

## Tasks
- [x] Move content from draft landing page to our current landing page
- [x] Find a place for the MHA page
- [x] Review (Laura)
- [ ] Archive draft page so it doesn't get accidentally published

## Acceptance Criteria
- [ ] Links to our modernized rates pages are now on the original landing page

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's the draft page for review: https://prod.cms.va.gov/node/938/latest 

I moved the content over from the draft in Drupal, and added the MHA link in a new section under the rates pages. I'll check with you about whether you think this is the best place for it.

**Comment by katherine-fung** [comment]
Hi @laurwill - I'd like to move the MHA link down to the "Related Links" section. 

I did a search for standalone pages about the housing/books/supplies payments for education benefits besides the Post-9/11 GI Bill, and didn't find any. I saw those payments referenced on pages about the benefits overall, but not covered as standalone pages. 

i.e. https://prod.cms.va.gov/education/survivor-dependent-benefits/fry-scholarship

**Comment by laurwill** [comment]
Hey @katherine-fung , the MHA related link looks good! 

It looks like we currently have an older stub version of the Post 9/11 rates page linked here — are we also planning a similar content copy/paste for that page so that we don't lose the established URL? Or should we swap in the newer version that you worked on recently?

Also noting that the MGIB-AD page is an older version that our team hasn't touched. But I wasn't able to find a newer version of that page. 

Lmk if you want to chat about this! I might be missing background here.

**Comment by katherine-fung** [comment]
Thank you @laurwill! 

I just swapped in the URLs for the new Post-9/11 GI Bill and the MGIB-AD rates pages: 

Post-9/11 GI Bill: /post-911-gi-bill-chapter-33-rates

[in CMS: https://prod.cms.va.gov/post-911-gi-bill-chapter-33-rates]

MGIB-AD: /education/benefit-rates/montgomery-active-duty-rates 

[in CMS: https://prod.cms.va.gov/education/benefit-rates/montgomery-active-duty-rates]

Here's the preview of the new landing page again: http://preview-prod.vfs.va.gov/preview?nodeId=938

**Comment by laurwill** [comment]
Thanks Katherine! Looks good now.

I archived the other draft page, so I think we can close this out!
