### ISSUE TITLE
Replace the "Description" and "Available Online" columns with "First Issued On" and "Last Revision On" columns

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4378]
## User Story:
As a veteran, I need the search results of the Find VA Forms widget (visible at `https://dev.va.gov/find-va-forms-beta/`) to include "First Issued On" and "Last Revision On" columns so that I can see that information about each form.

_Note: The reason for swapping out these columns is that the forms database does not currently support the  "Related to" and "Available Online" columns. Once it does, we will likely add those columns back._

## Tasks
- [x] Remove the "Description" ("Related to") and "Available Online" columns from the results table
- [x] Add the "Issue date" and "Revision date" columns to the results table
- [x] The "Issue date" and "Revision date" fields are formatted to `MM-DD-YYYY`
- [x] Ensure the table can be sorted by the "Issued date" and "Revision date" columns

## Acceptance Criteria:
* The "Issue date" and "Revision date" fields are visible after performing a search on https://dev.va.gov/find-va-forms-beta/.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Karak888** [comment]
Validated and moving to close
