### ISSUE TITLE
TASK: Work though lauch checklist

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#43807]
AC: 
- [ ] Decide what tasks have been done
- [ ] Decide what tasks need to be done still (put in tickets for those)
- [ ] Decide what tasks you don't think are relevent for this work
