### ISSUE TITLE
[Design] Create Prototype to Test New Language Toggle & Wireframes for Spanish Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43805]
## Tasks
- [ ] Create prototype for toggle
- [x] Prepare screenshots for translation content testing (use the link Lori provided)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities

**Comment by niradatta1** [comment]
Leverage screenshots from the Mural @loripusey provided (link in this slack conversation) https://dsva.slack.com/archives/C022AC2STBM/p1658933534212459?thread_ts=1658932732.536059&cid=C022AC2STBM 'cc @ytsaoca

**Comment by sarahknoppA6** [comment]
this has been validated and can be closed.

**Comment by ytsaoca** [comment]
UX team feedback 
https://dsva.slack.com/archives/C036JKN5S3Y/p1660919285418479

**Comment by ytsaoca** [comment]
- [Check-in toggle prototypes](https://civicactions-brand.invisionapp.com/console/share/P357VEC6KQG)
- [Pre-check-in toggle prototypes](https://civicactions-brand.invisionapp.com/console/share/ZTE5DYKSARX)

**Comment by ytsaoca** [comment]
- [Check-in toggle prototypes](https://civicactions-brand.invisionapp.com/console/share/P357VEC6KQG)
- [Pre-check-in toggle prototypes](https://civicactions-brand.invisionapp.com/console/share/ZTE5DYKSARX)
