### ISSUE TITLE
Debt Portal Edge Case - Design

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#43812]
## Issue Description
This ticket is to track the design work to be completed as part of the [Debt Portal Edge Case request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42360) based on the findings from the [discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42688)

---
## Tasks
- [ ] Create mock up for dashboard based on findings from discovery ticket

## Acceptance Criteria
- [ ] We have completed a mock up and met with the Debt Portal team to review and get their approval to build based on our recommendations.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pavanhothi** [comment]
@chloedotbrown @michelle-dooley @jonathan-epstein13 [here](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit#slide=id.g13d5e39691c_0_0) is the mockup for reference before our meeting later today. Please let me know if there are any questions or issues accessing.

**Comment by chloedotbrown** [comment]
Hey @pavanhothi ! Here's some notes on the [Combined Debt Portal mockup](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit#slide=id.g13d5e39691c_0_385):

HIGHLIGHTS
- **Combined debt portal pageviews** 
  - _**Title:**_ Consider renaming, since this shows two different pageviews and title references only one of them. Suggest changing to "Landing page and combined portal pageviews", something similar. 
  - **_Chart style:_** Suggest flipping to horizontal bar chart so funnel relationship is clearer.
- **Click-thru rate to copay & benefit balances** - Because these are two rates are for different types of behavior on the same page, you might be able to combine the in the same chart and shown in a more visual way. I'd recommend playing around with [tree maps](https://domohelp.domo.com/hc/en-us/articles/360042925054-Tree-Map) and create categories for people who 1) click to copay balances, 2) click to benefit debt balances, 3) click to both balances, and 4) do not click through to either portal. Alternatively, we could try a [multi-radial progress gauge](https://domohelp.domo.com/hc/en-us/articles/4546378883863-Multi-Radial-Progress-Gauge) for the first 3 category.
  - _**Question for Debt team** - should this still be user-scoped? I could see sessions/pageviews also making sense, but we should verify with them._ 
- **Click-thru to payment sites** - Maybe try a [filled gauge](https://domohelp.domo.com/hc/en-us/articles/360042924554) or something else to make more visually engaging / differentiate from other click-thru rates in section.
- **Click-thru rate annotation** - I'd recommend removing and putting this information in the tooltip for charts. Payment sites CTR is rate of people across all portal pages who click through to the two payment sites, while the portal CTRs are just for people who click through from the Combined Portal. Trying to explain all that in an annotation would probably take up more real estate than we want to give it.

TASK COMPLETION
- **Click interactions vs. pageviews** - These don't seem different enough to split into separate sections, since the main distinction is event vs. page hits probably isn't going to mean much to our users. Recommend combining and changing title to "Payments & Details" or something similar.
- **Total link clicks** - These are important because they're _payment_ link clicks, not just links. Title of chart, subheading, and annotation below should all reflect that.
- **Copay letter downloads** - Can be deleted! Debt letters only exist for benefit balances - for copays, users click through to Details and then Statements. 
- **Pageview section** - Change heading to "Debt details and downloads" etc. Move Benefit Debt Letter downloads to this section. Play around with different ways to visualize detail views, statement views, and debt letter downloads besides gauges, so viewers can see trends over longer periods of time.

EASE OF USE
- **Section title** - "Depth of engagement" might be a better fit for this section, since we have "users" elsewhere in dashboard and exits/bounces would be covered by that term as well.
- **"How many users were there?"** - Combining 3 charts in this section into 2 in the style of [Search Funnels ](https://va-gov.domo.com/page/1964748112/kpis/details/780331409)card, one for Copay Portal -> Copay Details and one for Benefit Portal -> Benefit Details/Letters. This would provide the same information, but relationships may be more intuitive for viewers. Rename subheading to "Did users engage with their debt details?" etc.
- **"How many exits were there?"** - Remove annotation (info can be provided in tooltip). Change heading to something like "Did users abandon the portal?" etc.

FINDABILITY
- **"Landing page" language** - I should have done a better job translating this part of the discovery spreadsheet! This language makes sense to us, but I'm not sure it will resonate with the Debt team. Instead, I'd change the section title to "Finding the portal," the subheader to "What pages doe users visit most often before viewing the portal," filter to "Filter by portal," and card title to "Top pages viewed before visiting the portal".
- **Top browsers** - Tiny note, but to be consistent with our other dashboards, all bars should be set to the yellow color, rather than one color for each. This better handles when top browsers change and makes the card easier to read.

**Comment by pavanhothi** [comment]
@chloedotbrown @michelle-dooley @jonathan-epstein13 The [mockup](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit#slide=id.g13d5e39691c_0_0) has been updated based on the feedback provided. Please let me know if you have any questions. Thank you!

**Comment by michelle-dooley** [comment]
@pavanhothi - I made some updates to the [mock up deck](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit#slide=id.g13d5e39691c_0_0) and schedule a meeting on Thursday with Denise to go over.  I was going through their original request ticket and wonder if we should include some more trend data as referenced in their 1st gen dashboard maybe something similar to the [usage trends](https://va-gov.domo.com/page/426422632) on the content dashboard?!?  Or do we just direct them to drill down capes to see more details?  Just want to make it as easy as possible for them to get what they need since this product has a lot of eyes on it and its an edge case so we are free to include whatever/however makes most sense for them.  @chloedotbrown - do you have any thoughts on this?

**Comment by chloedotbrown** [comment]
@michelle-dooley Let's ask them what they prefer in today's meeting! We can demo how drillpath charts work, since the team might not have much experience with them, and see if they have a preference for viewing more trends-over-time style charts on the dashboard itself or by clicking through.

**Comment by michelle-dooley** [comment]
This ticket is complete.  The dataset portion of this request will be completed as part of #45142
