### ISSUE TITLE
[mDot] Update Cypress tests to use dynamic dates

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#43839]
## Issue Description
mDot Cypress tests are using fixed dates for the supply `lastOrderDate`, `nextAvailabilityDate`, and `prescribedDate` variables. Since we're using the platform provided `testForm` and packaging up the data with `createTestConfig`, it's difficult to put in dynamic dates for the `dataSets`. Investigate to see if we can feed dynamic dates (something within the valid date range) to the test so it doesn't need to be updated again. 

`createTestConfig` uses variable `dataSets` and cypress `cy.fixture(...)` to pull data from the json files and fills out the forms. 

---
## Tasks
- [ ] Investigate options to update the supply dates dynamically based on when the test is run
- [ ] Implement a fix so we don't need to update the dates again.

## Acceptance Criteria
- [ ] Cypress tests use dynamic dates and pass -OR- dates are just fixed and need to be updated every few years.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
