### ISSUE TITLE
Change Veterans Crisis Line phone number to new number in Drupal pages and style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43848]
## Issue Description

**This is a placeholder ticket with more details to follow.** 

As of July 16, you can use the three-digit 988 to reach the National Suicide Prevention Lifeline. This is also the new number for the Veterans Crisis Line. 

Once public websites completes their audit of our pages that mention the VCL, we need to update these in Drupal. 

We'll also need to check the style guide and update any mentions there.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! This is ready for you.
We were responsible for changing the number on three pages, pulled from the Airtable sheet.

### **Benefit Detail Page**

**Report harassment or sexual assault at VA**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34641

### **Resources and support Detail page**

**Choosing between urgent and emergency care**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=37196

**Helpful VA phone numbers** 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=8427

**Comment by aliyahblackmore** [comment]
Thanks, Randi! @megzehn these alerts are ready for you and I've added some notes on two of them.

**Get connected with mental health care**  
This is on the VA Mental health services page.  The header “Get connected with mental health care…” is the second alert on this page (as you noted Randi), but there is no Veteran Crisis Line phone number listed in this alert. The phone number is in the “How do I talk to someone right now?” alert, which we are also changing.

**How do I talk to someone right now?** 
https://prod.cms.va.gov/block/2

**How do I get help for a Veteran who’s in crisis?**
https://prod.cms.va.gov/block/24


**How to quickly get the help you need** 
Note: I accessed the link from the Airtable sheet (it doesn’t show on the Alert section of Drupal) and made the change. When I save the draft the next screen is “Access Denied.” Cc: @RLHecht wondering if this is because this is still a draft. Could you advise who I may need to be in touch with in order to get access?

**Comment by megzehn** [comment]
Thanks, @RLHecht and @aliyahblackmore! I'll update my progress via this checklist: 

**To review and publish on 7/18:** 

- [ ] Choosing between urgent and emergency care
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=37196

- [ ] Helpful VA phone numbers
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=8427

- [ ] Get connected with mental health care
Aliyah's notes: "This is on the VA Mental health services page. The header “Get connected with mental health care…” is the second alert on this page (as you noted Randi), but there is no Veteran Crisis Line phone number listed in this alert. The phone number is in the “How do I talk to someone right now?” alert, which we are also changing."

- [ ] How do I talk to someone right now?
https://prod.cms.va.gov/block/2

How do I get help for a Veteran who’s in crisis?
https://prod.cms.va.gov/block/24

**To review and NOT publish:** 

- [ ]  Report harassment or sexual assault at VA
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34641

- [ ] How to quickly get the help you need

**Comment by megzehn** [comment]
Hi! These are reviewed and published, but 2 notes: 

- For all of the alerts, ([How do I talk to someone right now?]([url](https://prod.cms.va.gov/block/2)) and 
  [How do I get help for a Veteran who’s in crisis?](https://prod.cms.va.gov/block/24)), I got a note after publishing that I'm not authorized to view the page. It also said the page was updated, so I think the changes are published, but could you just confirm, @RLHecht ?

- Echoing @aliyahblackmore 's comment re: **Get connected with mental health care.** 

The alert is the second alert on [VA Mental Health Services page](https://www.va.gov/health-care/health-needs-conditions/mental-health/), but it doesn't contain the crisis line. The line is listed in the first alert, which we're already changing (referenced above).  

Also, the Crisis Center line is mentioned further down the page, but the number is not listed (just linked to) 
![Screen Shot 2022-07-18 at 2.39.44 PM.png](https://images.zenhubusercontent.com/6268142534de80edf577caef/03049d0f-91e0-4b2a-a5e6-4dae3b13f542
)

I left as is, but @RLHecht let me know if you think we need to add in the number there. 

Thank you!!
