### ISSUE TITLE
[Alerting] Modifications to SiteLatencyCritical alert

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#43859]
## Description
SiteLatencyCritical is an alert that notifies the individual on-call for the Infrastructure team (DevOps Critical). [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#sitelatencycritical) lists a number of graphs to check to see where the problem could be coming from, but even if you have a suspicion of where and why the alert is going off, there's usually nothing to be done about it. The most that could be done is to tell a team, "hey, your service is extra slow" (but it's often hard to pinpoint a culprit). 

My recommendations:
1. To mitigate the annoyance asap, create a [Rule in PagerDuty](https://dsva.pagerduty.com/event-rules/services/P9OB1XS/rules/create/timing) that suppresses (or decreases the severity of) these alerts during non-business hours.
2. In order to understand `SiteLatencyCritical`, research what goes into making this alert trigger. 
3. What do `ComponentLatencyWarning`s have to do with `SiteLatencyCritical`? ([Example pd alert](https://dsva.pagerduty.com/incidents/Q3Y4QEAGMSSCOY).) If they are connected (the components firing lead to poor site latency), determine what can be done about those alerts (change the urgency from High to Low so they trigger a page? Assign GitHub Issues to other teams to make their component better?). Many of the components causing this latency are unknown. The component variable is blank. That should probably be fixed.

## Background/context 
This [past incidents](https://dsva.pagerduty.com/incidents/Q3F7QR6KYLD8E2/past) graph for `SiteLatencyCritical` shows that this alert has been more frequent in the last couple months:
![image](https://user-images.githubusercontent.com/10993987/177413378-471e2e5a-e378-41e0-9eba-0043e788c8fa.png)

This is the Prometheus source: 
```
sum(rate(nginx_http_request_duration_seconds_bucket{job="revproxy",le="2"}[1m])) / 
sum(rate(nginx_http_request_duration_seconds_count{job="revproxy"}[1m])) * 100 < 95
```

And these are the [past incidents](https://dsva.pagerduty.com/incidents/Q3Y4QEAGMSSCOY/past) for `ComponentLatencyWarning`:
![image](https://user-images.githubusercontent.com/10993987/177416185-8b64454a-4059-4551-81e9-34d871ec3ffa.png)
Source:
```
sum(rate(nginx_http_request_duration_seconds_bucket{
   app!~"ewis-apps|ewis",
   component!~"address|appeals|auth|claim_attachments|claim_documents|evss_claims|facilities|fhir|health_care_applications|letters|loan_guaranty|messaging|post911_gi_bill_status|prescriptions|search|ssoe_signin|user|vba_documents|vba_documents_content|profile|vaos|mobile.*",
   job="revproxy",le="2"}[1m])) 
BY (app, component) / sum(rate(nginx_http_request_duration_seconds_count{job="revproxy"}[1m])) 
BY (app, component) * 100 < 95
```

---
## Tasks
- [x] Address questions in "recommendations" section.

## Acceptance Criteria 
- [x] SLC is quieter and the root cause of the recent extra noise is being investigated by that team

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
The goal here is to look at @rmtolmach and the team's recommendations so that we can make this alert less noisy, more useful, and more actionable.

**Comment by rmtolmach** [comment]
Adding some thoughts. Haven't come up with actions yet. 

`SiteLatencyCritical` (SLC) tracks, at the highest level, the latency of va.gov. It is impacted by _many_ (77 by my count) components within the applications. I found that number by adding `by (app, component)` to the SLC query (which is basically what `ComponentLatencyWarning` is, but CLW ignores a number of apps and components). [Prometheus link](http://prometheus-prod.vfs.va.gov:9090/prometheus/graph?g0.range_input=1h&g0.expr=sum(rate(nginx_http_request_duration_seconds_bucket%7Bjob%3D%22revproxy%22%2C%20le%3D%222%22%7D%5B1m%5D))%20by%20(app%2C%20component)%20%2F%20sum(rate(nginx_http_request_duration_seconds_count%7Bjob%3D%22revproxy%22%7D%5B1m%5D))%20by%20(app%2C%20component)%20*%20100&g0.tab=0).

I have observed this week that our SLC metric is directly correlated to the latency of the `services` app. Every time I've gotten a page about SLC, the latency of `services` is way down. The following two screenshots are from the same time period:
This is the `SiteLatencyCritical` graph. `100` means _all_ requests were being served in < 2 sec. Our threshold for alerting is < 95%.
<img width="1654" alt="image (3)" src="https://user-images.githubusercontent.com/10993987/190697103-80b54c69-f478-4ff0-83e4-9dbb3668de2a.png">

This graph shows the latency off all the `apps` that make up SLC, but I selected `vanotify`, `services` and `{}` (which is the SLC metric). As you can see, `services` and `vanotify` drag down the red line. 
<img width="1592" alt="image (5)" src="https://user-images.githubusercontent.com/10993987/190697079-7093944c-3da4-4134-b5d2-55c795eb3b97.png">

The screenshots above are from earlier in the week. Below is from a period of instability yesterday evening. First graph is the components within the `services` app (with only the bad ones highlighted):
![Screen Shot 2022-09-16 at 1 50 19 PM](https://user-images.githubusercontent.com/10993987/190711984-84a0240d-77d5-4703-b732-c7773d9d991e.png)

This graph is the components within the `api` application. It's a lot 😳: 
![Screen Shot 2022-09-16 at 2 08 14 PM](https://user-images.githubusercontent.com/10993987/190712198-2a6f7eea-6e2c-4268-89a4-50344b09e829.png)

One thing I haven't looked into to is the _volume_. Some of these components might look dreadful, but could be having a negligible impact on the SLC numbers.

**Comment by rmtolmach** [comment]
It's possible https://github.com/department-of-veterans-affairs/devops/pull/12018 may have fixed this problem. The PR made temporary changes to `SiteLatencyCritical` while Lighthouse Infrastructure investigates `fhir`'s latency. They are tracking that work in https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/1832 (I don't have the perms to see it, but it's there 🤷). 

Before closing this issue, create follow-up issue or reminder to check back in on the Lighthouse infra team (original Slack thread in the comment above ☝️).

**Comment by rmtolmach** [comment]
Site latency has been modified and the alerts coming in from pager duty are fewer.
Created this issue to deal with follow-up:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/47765

Closing.
