### ISSUE TITLE
[DDOV] Create roles in DataDog-Gov

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#43861]
## Description
With the team migrating over to DataDog-Gov, this would be a good opportunity to define and create roles for teams. This will help once we onboard VFS teams

---
## Tasks
- [ ] Define roles for teams
- [ ] Implement roles

## Acceptance Criteria 
- [ ] Roles implemented and applied to teams

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
