### ISSUE TITLE
[FE] Implement APO/DPO/FPO form update and copy changes

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4386]
## Background 

Once a Veteran has clicked the checkbox on the 'Edit mailing address' form which will force United States to selected. On the 'Edit mailing address' form, User checks 'I live on a United States military base' and the Country field is forced to 'United States'.

# Tasks 

### Designer  

- [x] Need to show the scenario where the user would click to edit their mailing address  and click "I live on a United States military base" and the Country field is forced to  "United States".

- [x] Need to upload the screenshot to be implemented for the form. 

- [x] Developer will need the copy and screen shot for the form.  

- [x] Upload/Define which scenarios show "edit their mailing address"  

  

### Front End Dev  

- [ ] Implement the FE build of the check box updates for a veteran living on a United States military base. 

- [ ] Validate with Designer or PM that the form displays correctly and functionality works as intended.

  

## Definition of done 

- [ ] Form is updated and is working on staging.  

## UX Screen and Approved Copy

**Comment by Justin-Pickett** [comment]
@artistgreen please upload the UX Screenshots and approved copy for the changes to be implemented.

**Comment by artistgreen** [comment]
UX for Veterans with APO/FPO/DPO addresses:


- display a checkbox option with label "I live on a United States military base outside of the United States'
- display a helper text drop-down
- disable 'Country' field and display United States within the field
- Change 'City' field label to read 'APO/FPO/DPO' and change input text box to a drop down with the options: APO, FPO and DPO
- Reduce 'State' field options to: AA (Armed Forces Americas), AE (Armed Forces Europe) and AP (Armed Forces Pacific)

**Comment by artistgreen** [comment]
### Veteran edits their mailing address on their profile UX

**Checkbox label:  "I live on a United States military base outside of the United States"

Helper text label:  Learn more about military base addresses**

![DPO edit address 1](https://user-images.githubusercontent.com/53535009/71358918-a42d3f80-2558-11ea-8c52-5d82c6a2d32e.png)

**Comment by artistgreen** [comment]
### Veteran edits their mailing address on benefit application forms

If the Veteran has signed in to VA.gov they will see their benefit forms pre-filled with information from their profile.

Checkbox label: I live on a United States military base outside of the United States
Helper text label: Learn more about military base addresses

![Form 10-10EZ - domestic military base address 1](https://user-images.githubusercontent.com/53535009/71359711-7c8ba680-255b-11ea-8b9c-e2fa425b2d07.png)

----------

**Comment by artistgreen** [comment]
### User confirms address information on benefit forms

At the end of the workflow on benefit forms, an accordion Ui will display to allow Veterans to review/edit their information

![image](https://user-images.githubusercontent.com/53535009/71360461-fa50b180-255d-11ea-9a04-0d48f5171473.png)

----------

When the user opens the Veteran Info section they will see this:

![image](https://user-images.githubusercontent.com/53535009/71360475-06d50a00-255e-11ea-8d43-c57f6ce43f2d.png)

----------

When the user clicks the 'Edit' button for the Permanent address section to edit their address they will see this layout:

![Form 10-10EZ - veteran info edit](https://user-images.githubusercontent.com/53535009/71360603-67fcdd80-255e-11ea-934f-61d0872f9af5.png)

**Comment by Justin-Pickett** [comment]
@artistgreen I am confirming that all the necessary screens and flows are ready for this work to be started by @bradl3yC for implementing these front end changes. Please confirm as well. Thank you.

**Comment by artistgreen** [comment]
@Justin-Pickett  and @bradl3yC - Yes - this is ready for FE.  I added screens for both, the profile form and benefit forms on this ticket.

**Comment by artistgreen** [comment]
@Justin-Pickett @bradl3yC - I removed the benefit form screens - this ticket focuses on the profile form.

**Comment by erikphansen** [comment]
@artistgreen I was just reviewing the work @bradl3yC had done on this and wonder if we should remove the AA/AE/AP options from the `state` dropdown when the user has not selected the checkbox indicating that they are on an overseas military base.

**Comment by artistgreen** [comment]
@erikphansen - Good point -  I agree that we should remove those options from the state drop down if the checkbox for overseas military base is not checked.

**Comment by erikphansen** [comment]
@artistgreen We merged without that last change we talked about so that we could get it out on staging. And now that I've played more with the work Brad did I don't think we need to remove the AA/AE/AP states from the dropdown. The state dropdown only appears if the user has selected USA as their country (otherwise it becomes a text field). So keeping those options in the dropdown will simply give the use another way to enter a valid overseas base address; it won't prevent any sort of bad data entry by the user. But if you want to move forward with removing AA/AE/AP from the state dropdown, please make a ticket for that work.

**Comment by erikphansen** [comment]
@Justin-Pickett @artistgreen @Samara-Strauss this can be validated on staging now.

**Comment by Samara-Strauss** [comment]
Looks good to me at an initial glance! @artistgreen should more fully validate this work as the designer, then feel free to close out this ticket!
