### ISSUE TITLE
Collaboration Cycle for Benefits Team 1, Claim Status Tool, Download Decision Letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#43860]
### VFS team name

Benefits Team 1

### Product name

Claim Status Tool

### Feature name

Download Decision Letter

### GitHub label for product

claim-status-tool

### GitHub label for feature

download-decision-letter

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Sprint starting 7/13

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools and applications

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product%20Outline%20-%20Draft.docx

### Feature Outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST_%20Download%20Decision%20Letter%20Feature%20Brief%20-%20Draft.docx

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

</details>

 ## Recommended Collaboration Cycle touchpoints

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add all requested artifacts below **at least two days before** the scheduled Design Intent
  
**Design Intent artifacts**

- [x] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] User flow
- [ ] Research plan
- [ ] Any other artifacts you have so far

@shiragoodman Attached is a deck with some of the artifacts requested. When it comes to a research plan, we'd like to have a discussion with your team about possible approaches to UAT and then circle back with a deliverable that incorporates your feedback.
[Design Intent Review_ Decision Letter Download.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9168918/Design.Intent.Review_.Decision.Letter.Download.pdf)

I posted this originally in a comment on this ticket on 7/22/22 - JW
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: July 26th, 2022 / 11:30am – 12:00pm
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
  - [x] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/qt-06twwL5-PlJGS70ZtwFLyyEvoXd8h93KNZBAw0An2Wo4k3g2IBeVq7KgoWx67.OA5SaDGn43rO9CoV
  - Password: dFL5u^za
  
##### VFS actions

- [ ] Respond to feedback tickets
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] #46304

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add or update all requested artifacts below **at least two days before** the scheduled Midpoint Review
  
**Midpoint Review artifacts**
Provide links or documents for the following:

- [x] [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42954)
- [x] [Desktop prototype](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/prototype/a/775B3120-703A-47C3-8054-E2586037F1EA)
- [x] [Mobile prototype](https://sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/a/QbE4YZY/play)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/conversation-guide.md)
 
**Content artifacts**
  
- [ ] Your product’s content source of truth
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): 

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [ ] Link to test cases/test plan in TestRail (draft OK): 
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: 9/1 at 1:30pm ET

##### Platform actions

- [x] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
  - [x] QA has completed the review
  - [x] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/G5LU6-FFizBXNAk3WMNqJ7G53FuuqGFIeX6BQ2foNhQtDbyB44PFrpF2wQHHCbgd.ptsQRy5gNf0AJcH1
  - Password: Cv211@A7
  
##### VFS actions
  
- [ ] Respond to feedback tickets
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47760

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Add or update all requested artifacts below **at least four days before** the scheduled Staging Review
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
  
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- [Release plan with the "Planning" sections completed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Decision%20Letter%20Release%20Plan.md):              
- Staging URL and staging test user information:   
- URL: https://staging.va.gov/track-claims/your-claim-letters
-   [Test Credentials](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-cst-users.csv)             
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  

  
**Accessibility artifacts**
  
- [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc):  **(Preferred)** OR, 
- Document in your product folder that indicates all required checks from the [how to prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/developer-docs/How-to-prepare-for-an-accessibility-staging-review.1909293137.html) doc are complete: 
- List of known issues with links to tickets (when applicablee): All outstanding accesibility issues tracked [here](https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/department-of-veterans-affairs/vets-website/22576)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: November 10 at 1:30pm EST
- [ ] Create feedback tickets and link to this epic
  - [x] Design feedback provided
  - [x] Accessibility feedback provided
  - [x] IA feedback provided
  - [x] Content feedback provided
  - [x] QA feedback provided

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/OGbZh6ncFmHSypKDgJfnj_4IZlDpQhPDI2dMp9Cz9fh56A8BU4nEFmoK2vflogOa.1lDkn1lM2gV0E_QX)
  - Password: z%a6vZ+#
  
##### VFS actions
  
- [x] Respond to feedback tickets
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] Update the VFS product information section with the product’s launch date and production URL after it has gone live

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/630)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by jacobworrell** [comment]
@shiragoodman Attached is a deck with some of the artifacts requested. When it comes to a research plan, we'd like to have a discussion with your team about possible approaches to UAT and then circle back with a deliverable that incorporates your feedback. 
[Design Intent Review_ Decision Letter Download.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9168918/Design.Intent.Review_.Decision.Letter.Download.pdf)

**Comment by jimuhh** [comment]
Hi. Wondering if there might be a mobile '[wire flow](https://www.nngroup.com/articles/wireflows/)' for this API?

**Comment by skylerschain** [comment]
There isn’t a mobile version of this yet. Is that an issue for the review?

**Comment by jimuhh** [comment]
@skylerschain Not specifically. We do prefer a mobile-first methodology but can review other artifacts. The concern here was more in seeing a flow from screen to screen on a single document. That allows us to get a better sense of the interaction.

**Comment by skylerschain** [comment]
**Midpoint Review artifacts:**

- [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42954)
- [Desktop prototype](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/prototype/a/775B3120-703A-47C3-8054-E2586037F1EA) 
- Mobile prototype (WIP)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/conversation-guide.md)

**Comment by shiragoodman** [comment]
@skylerschain please link the Midpoint Review artifacts in the body of the ticket under "Midpoint review artifacts." This makes it easier for our team to locate what we need so we don't have to go searching through the comments. let me know if you have any questions - thanks!

**Comment by skylerschain** [comment]
Added mobile prototype to Midpoint Review artifacts.

**Comment by TiffanyPender** [comment]
Other than the [listed outstanding accessibility issues](https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/department-of-veterans-affairs/vets-website/22576), is there a completed accessibility TestRail template available for the upcoming staging review? 
cc: @shiragoodman

**Comment by jacobworrell** [comment]
HI there @TiffanyPender we did a lot of testing in TestRails, but this was our first time using the tool, so I discovered after a lot of testing that we didn't use the "Test Plan" feature. 

But you can see the tests we ran in the Overview section. So far every test ran is related to this new feature: https://dsvavsp.testrail.io/index.php?/projects/overview/59

Sorry if I missed this up, I just didn't know how to retroactively put previously conducted tests into a "Plan".

**Comment by TiffanyPender** [comment]
Perfect, thank you @jacobworrell! Can you please add in your TestRail link to the Staging Review artifacts?

**Comment by jacobworrell** [comment]
@TiffanyPender sure thing. I had previously already included a link to TestRails test cases in the QA section, but I added a link to the "Overview" in case it's more helpful.

**Comment by TiffanyPender** [comment]
Ok, got it! I was looking specifically at accessibility. Thanks for noting that, @jacobworrell.

**Comment by it-harrison** [comment]
@jacobworrell could you provide a link in the QA artifacts to demonstrate that you have E2E tests for this product? Could be a link to mochawesome from a CI run?
