### ISSUE TITLE
Update Traefik Ingress configuration in DEV

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#43868]
## Issue Description
As a user navigating the development environments of va.gov or the mobile app, I need vets-api requests to route to the appropriate endpoints in the EKS version of vets-api, so that I am able to reliably navigate its content and use its functional applications.

---
## Tasks
- [x] Add hostname to Traefik configuration

## Acceptance Criteria
- [x] Ensure vets-api is reached in the DEV environment.
---
## How to configure this issue
- [ ] ~~**Attached to a Milestone** (when will this be completed?)~~
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
