### ISSUE TITLE
FE Sign in Service Bugs

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#43875]
## Issue Description
This is a collection of bugs found in the FE concerning the Sign in Service after a user is authenticated which was included in this [Slack thread](https://dsva.slack.com/archives/C019S3NSSAD/p1656513996256509)

- Multiple refresh token requests (3x 403 errors made 3 separate requests to the `/refresh` endpoint)
- `/keepalive` was still being called in the AutoSSO component and subsequently removing the `hasSession` from local storage causing users to be signed out (even when the `vagov_info_token` existed)
- The `acr` values for the signup routes were not being parsed correctly and generated `acr=undefined` when the URL was generated

## Tasks
- [x] Removing multiple calls to the `/refresh` endpoint by checking the refresh expiration
- [x] Ensure the `/keepalive` call is not called (so AutoSSO is not invoked)
- [x] Fix the sessionTypeUrl function to update the `acr` parsed value

## Acceptance Criteria
- [x] The above bugs are fixed
