### ISSUE TITLE
[Platform Support Slackbot] Send automatic ephemeral message when a user posts in the platform-support slack channel

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#43881]
## Issue Description
Notify a user, with a message that can only be seen by them, when they post in the platform support channel without using the platform support slackbot `/support`

---
## Tasks
- [x] Update the message event listener to post an ephemeral message when a thread_ts is undefined (thread_ts is undefined for new posts within the channel)
- [x] Update documentation

## Acceptance Criteria
- [x] A user will be notified with a private (ephemeral) message if they post in the platform-support channel without using the support slack bot

**Comment by powellkerry** [comment]
**Test Cases**
_This is deployed to the test environment_

- [ ] When posting in the channel without the `/support` command you should get a messages asking you to use it and providing a link to documentation for more info.

**Comment by powellkerry** [comment]
Released August 9th
