### ISSUE TITLE
Launch Q3 Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43891]
## Issue Description
Launch Survey in typical manner.

---
## Tasks
- [x] Launch Survey in Optimal Workshop
- [x] Communicate its availability in relevant Slack channels

## Acceptance Criteria
- [x] Survey launched
- [x] Communicate its availability in relevant Slack channels

**Comment by tayism** [comment]
Live Q3 survey lives here: https://ows.io/qs/ue8i37p2

**Comment by steel36** [comment]
Removed Task & Criteria to post Survey in Slack (this is part of #43892)
