### ISSUE TITLE
Create internal documentation for building and maintaining YAML issue forms

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#43899]
## User Story
_"As a Governance team member, I want clear guidance on how YAML GitHub issue forms work, so that I can edit the Collaboration Cycle Request template and create new templates as needed."_

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
The [Collaboration Cycle Request issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2Cgovernance-team%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) is a [GitHub issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). Issue forms are defined by a YAML file.

YAML has its own strict syntax for structuring data, and GitHub's forms engine is looking for specific keywords when generating forms. Most of this is documented by GitHub, but a few details were discovered via trial-and-error when building the Collab Cycle Request form.

Documentation created should be a Confluence page in the Governance team space, with:
- Appropriate links to GitHub's documentation
- A short "how to" code example from the Collab Cycle Request form
- A tips/best practices section learned from building the Collab Cycle Request form

## Impacted Artifacts
Should not require editing any artifacts, just creation of new documentation. The [Collaboration Cycle Request YAML file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml) should be used as a reference.

## Tasks
- [x] Create documentation detailing YAML
   - Draft documentation: [Managing YAML GitHub Issue Forms](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2307752086/Draft+Brian+-+Managing+YAML+GitHub+Issue+Forms)

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team members are able to update and maintain the Collaboration Cycle Request template.
- [x] Governance team members are able to create new YAML templates

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
Ready for review @allison0034

**Comment by allison0034** [comment]
@briandeconinck this looks good to me. Confirm when it is live and then you can close the ticket. : )

**Comment by briandeconinck** [comment]
New team guidance is live: [Managing YAML GitHub Issue Forms](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2307752086/Managing+YAML+GitHub+Issue+Forms). Closing!
