### ISSUE TITLE
Close Survey, Synthesize results and update Mural boards

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43893]
## Issue Description
Quarterly survey synthesis and update to mural boards

---
## Tasks
- [x] Close Survey
- [x] Update Platform site and Confluence Site
- [x] Prep [synthesis Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661820546891/65263d534fddee99066fb8adf19d8d672ab98fe0?sender=u9ea6bd3ca12795949b606150)
- [x] Synthesize survey

## Acceptance Criteria
- [x] Customer Insights [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661820546891/65263d534fddee99066fb8adf19d8d672ab98fe0?sender=u9ea6bd3ca12795949b606150) updated

**Comment by tayism** [comment]
Voting to move this to next sprint as we continue pushing for more survey responses.

**Comment by tayism** [comment]
Survey synthesis scheduled 8/30/22.
