### ISSUE TITLE
Publicize the Q3 PS Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43892]
## Issue Description
Share survey's availability in Slack, ToT, and relevant group discussions every few days as needed to ensure participation.

# Make sure Content has updated Platform before linking to page

## Tasks
- [x] Share Survey in Slack
- [x] Share Survey in ToT

## Acceptance Criteria
- [x] Survey posted in Slack
- [x] Survey posted in ToT slides for active period
