### ISSUE TITLE
Update Template Names for DMC Notifications

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#43909]
## Issue Description
As we work to integrate additional VHA aspects into the debt portal it is imperative that we can distinguish VBA from VHA notifications for communication clarity. 

As a result we would like to update the names for our existing notifications. Outlined below are the current names and the desired changes which will support future growth for both VBA and VHA notifications. 

---
## Tasks
- Updated Campaign names for existing VA Notifications related to the Debt Portal
- Connect with VA Notify team as needed to ensure that analytics are consistent and no errors are introduced by the name change. 

## Desired Campaign Names
|Current Notification Campaign Name|Future Notification Campaign Name  |
|--|--|
|FSR Confirmation | Debt: (VBA) FSR Confirmation|
|debt notification | Debt: (VBA) Debt Letter Notification|

## Reference Information

Melanie Jones from the analytics team shared this via email. Adding for context.  

> This can be a little confusing because the Domo dashboard is pulling the "campaign" from a couple different sources. 
> For notification analytics like sent, open, failure reasons, campaign represents the email name in VA Notify. 
> For referral analytics, e.g. link clicks to landing pages, campaign represents the campaign value specified in the URL provided in the email body.
> If we need to add clarification to the email names that's definitely something we can do. I would recommend making the email names and URL campaign tags as descriptive as desired. Also, we can track billing separately once you are ready to create those VHA notifications.
> 
> I have an action to check if historical notification analytics will reflect updated email names. I can say for certain that referrals would not. Once those URL campaign names are tweaked it would only reflect analytics for link clicks that include the new name. The old campaign name would still show up with historic data.

## Acceptance Criteria
- [ ] Campaign names have been updated. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Hey @ScottyRJames I am going to add this one to the FSR Enhancement release so we can get this done. Now that VHA is part of the mix we will need to have the added clarity. Highlighting it for you since it might make sense to do this with the submission notification you are working on now.

**Comment by denisecoveyduc** [comment]
Updating this ticket to reflect our current understanding and requirements going forward. 

We are looking to change the TEMPLATE NAMES to the following: 

- **FSR Confirmation – VBA** (changed from FSR Confirmation)
- **FSR Confirmation – VHA** (Changed from VHA FSR Confirmation)
- **New Benefit Overpayment – VBA** (Changed from Debt Notification)
- **New Medical Copay - VHA** (Future Notification - reference only)

**Comment by ScottyRJames** [comment]
Here's what we learned from the analytics team about changing the template names

> You won't lose tracking of past data, but it may become slightly more confusing to sync template names with GA campaigns.
The data source that brings in your outgoing notification data runs a full replacement every day, so once the template names are updated, those should be reflected in your filter menu options, the "Delivery rate by template" table, etc.
The only place I could see your team running into issues is if some of the templates will have associated campaign name changes in GA also. Even if you make the updates in GA campaigns, the older data will still have the campaign name version that was recorded at the time. However, the landing page section has its own filter and the Opened Campaigns section doesn't respond to the template filter anyway, so it may not be an issue! Let me know if you have any other questions.

**Comment by ScottyRJames** [comment]
Rolling over due to no permissions to update template name -- will request change from Notify team

**Comment by denisecoveyduc** [comment]
@ScottyRJames is contacting the VA Notify team, moving to blocked until we hear from them. This is work the VA Notify team needs to do but we will track to ensure it is done.

**Comment by HeatherRienks** [comment]
@ScottyRJames to follow up with VA Notify team.

**Comment by HeatherRienks** [comment]
@ScottyRJames - FYI- @denisecoveyduc created ticket #54314 to work with VA Notify Team.

**Comment by denisecoveyduc** [comment]
Hey @ScottyRJames Jill and I discussed this and we would like to make one small adjustment to what is outlined above. 

- **Debt: FSR Confirmation – VBA** (changed from FSR Confirmation)
- **Debt: FSR Confirmation – VHA** (Changed from VHA FSR Confirmation)
- **Debt: New Benefit Overpayment – VBA** (Changed from Debt Notification)
- **Debt: New Medical Copay - VHA** (Future Notification - reference only)

cc: @HeatherRienks
