### ISSUE TITLE
Add react widget to housing COE landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43901]
## Issue Description
When the housing COE launches, it will be done incrementally. Because of this, we need to use a react widget on the landing page for the entry point. The page this will be on is [How to request a VA home loan Certificate of Eligibility (COE)](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/).

The benefits-team-1 product team will create the react widget, but we need to confirm the text is correct. What is in the react widget will only show to a set percentage of users while what is on the Drupal page will show to 100% of users. We may need to rework the content in the Drupal page to accommodate this.

Once the react widget is created and the COE is ready to launch, we need to add the widget to our Drupal page and publish. The product team will supply us with the react code to enter into Drupal.

When the tool is launched to 100% of users, we'll remove the react widget and add the content back into Drupal as well as set up all entry points. This work will be tracked in a different ticket. 

## Tasks
- [x] Reach out to product team for react widget (Randi)
- [x] Rework content for widget if needed (Randi)
- [x] Review new content (Laura)
- [x] OCTO-DE review (Beth)
- [x] Provide new content to product team (Randi)
- [x] Add react widget to landing page (Aliyah)
- [x] Final copyedit (Megan)
- [x] Publish page (Megan)
- [x] Create ticket to remove widget when tool is launched to 100% (Randi)

## Acceptance Criteria
- [x] React widget has correct content
- [x] Page is published with react widget for launch

**Comment by RLHecht** [comment]
@cohnjesse @saderagsdale Could you drop in a screen shot here of the react widget you created so we can confirm the text is correct? Also, we'll need the widget code once we're ready to add to Drupal. Thank you!

**Comment by cohnjesse** [comment]
@RLHecht It looks like our React widget has basically no content right now, it just changes where the link goes (eBenefits vs VA.gov) so we will need content for both what should be shown to folks inside the staged rollout and those outside it

**Comment by RLHecht** [comment]
@laurwill Can you look at the text I put in this doc for what is shown to those who see the action link and those who don't? Once it looks OK I can give it to the product team for the react widget. [https://app.zenhub.com/files/133843125/8f5fd1d1-f788-418d-bec2-0476db6d696f/download](https://app.zenhub.com/files/133843125/8f5fd1d1-f788-418d-bec2-0476db6d696f/download)

**Comment by RLHecht** [comment]
Putting this comment from Megan here from our closed ticket about other updates we want to make to this page when we add in the react widget: 

Consider adding a sentence or finding a PL alternative for "guaranty of value" in this paragraph:
"The lender will request a VA appraisal (assessment) of the house. An appraisal estimates the house’s market value at the time of inspection. An appraisal isn’t a home inspection or a guaranty of value."

Consider moving this link somewhere in the related accordion right above it. Maybe.
“Find out how to request a COE as a surviving spouse”

**Comment by laurwill** [comment]
Hi @RLHecht , here's the updated text with the "your" to "a" COE change:
[COE react widget.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9142739/COE.react.widget.docx)

**Comment by laurwill** [comment]
Hi @RLHecht , here's the react widget text with the "your" to "a" COE change.
[COE react widget_updated.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9150958/COE.react.widget_updated.docx)

**Comment by RLHecht** [comment]
@bethpottsVADEPO Do you want to take a look at this content before we have the product team create the react widget? We used the same language we have on the page now but adjusted for when there will be an online tool vs. not.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @laurwill Looks great! Thanks for moving this forward.

**Comment by RLHecht** [comment]
@cohnjesse The word doc that @laurwill posted above is good for you to use for the content. I put in there what should be visible to the percentage of users who do see the action link to the online tool and what should be visible if they aren't seeing it. Once we put that react widget on the page, we'll remove the repetitive content from Drupal when we're ready to publish it. Let me know if you need anything else from us. Just let us know what the react code is once you have it for us to add to Drupal. Thanks!

**Comment by RLHecht** [comment]
@cohnjesse Checking in on this again to see if you have the react code yet for us to add to our page.

**Comment by saderagsdale** [comment]
@jsokohl @scottymeyers Looping you in for context.

**Comment by scottymeyers** [comment]
Just drafted a pull request w/ the updated copy: https://github.com/department-of-veterans-affairs/vets-website/pull/21917

**Comment by saderagsdale** [comment]
@scottymeyers can you remind me if we've completed our part of this?

**Comment by RLHecht** [comment]
@saderagsdale Could your team give us the react widget code so that we can add it to our page and confirm the content is correct?

**Comment by saderagsdale** [comment]
@RLHecht Hi, looping @scottymeyers into your inquiry. He is working on this and can provide an update.

**Comment by RLHecht** [comment]
@scottymeyers @saderagsdale Checking in on this again if there're a react code to add the widget to our page. Thanks!

**Comment by Mottie** [comment]
So, the [React widget doesn't include an `h2`](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/coe-access/COEAccess.js#L15-L40) with the text "[How to request a COE](https://staging.va.gov/housing-assistance/home-loans/#how-to-request-a-coe)". Should it include that?

That's the only concern I have with the COE widget.

**Comment by RLHecht** [comment]
@Mottie We are adding the react widget to the current [COE landing page](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) in Drupal. This will be the entry point for the tool because because it's not launching to 100% of users to start, we need to have a way to show the action link and surrounding text to only a certain amount of people. 

If your team gives us the react widget code, we will add that into Drupal.

**Comment by Mottie** [comment]
The code for the react widget is contained within this [`createCOEAccess` code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/coe-access/createCOEAccess.js) - but I'm saying the content that is being rendered does not include an `h2`.

**Comment by Mottie** [comment]
And do we need IA to review the breadcrumb destinations?

**Comment by RLHecht** [comment]
@Mottie The Sitewide Content team is going to place the react widget on the [How to request a COE page](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) in Drupal. This will be the entry point for users to get to the tool. Once the tool is showing to 100% of users, we are going to remove the react widget from the page and put all the content back into Drupal, including the link to the tool. 

We will have the H2 "How do I request a COE" on the page, so it doesn't need to be in the react widget because it won't change depending on who sees it. In order for us to add the widget to the Drupal page, we need to put in a code and I'm not sure what that is. I am happy to jump on a call if this is easier to work out this way. 

Here's a screenshot of what I mean. 
<img width="786" alt="Screen Shot 2022-09-23 at 11 05 26 AM" src="https://user-images.githubusercontent.com/48728214/191992261-de80a4ab-432a-4a3c-8fe0-738842a281a4.png">

**Comment by Mottie** [comment]
Honestly, I don't know.

I _think_ it's up to a content developer to add a `data-widget-type` attribute, set to whatever widget type you want to name it, to one of the divs surrounding the content under the H2

<img width="1429" alt="how to request coe page with dev tools inspector open with a highlighted div which wraps all the how to request a coe content" src="https://user-images.githubusercontent.com/136959/191998596-1744e9c0-ebc0-48dd-9b8c-8ee3965a6900.png">

For example:

```html
<div data-entity-id="4999" data-widget-type="coe-cta">
   ...
</div>
```

**Comment by RLHecht** [comment]
@laurwill Can you look at this updated word doc for the react widget? I added back in the ebenefits information for the 75% of users who won't see the new online tool. 
[https://app.zenhub.com/files/133843125/e5d51500-610a-4ee6-8190-fab2140468e1/download](https://app.zenhub.com/files/133843125/e5d51500-610a-4ee6-8190-fab2140468e1/download)

**Comment by RLHecht** [comment]
Update: React widget code to add is: coe_access

**Comment by laurwill** [comment]
Thanks @RLHecht ! Content for react widget looks good — thanks for adding that back in.

**Comment by laurwill** [comment]
Spoke too soon! We just realized that this we can shorten the amount of content in the widget and keep more of it in Drupal.

Here's the updated content: 
[COE react widget content_updated 9.29.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9675819/COE.react.widget.content_updated.9.29.docx)

**Comment by RLHecht** [comment]
@Mottie Here's the new content for the widget: 
[COE.react.widget.content_updated.9.29.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9677796/COE.react.widget.content_updated.9.29.docx)

Let us know when it's ready and we'll add it to the page. Thank you!

**Comment by jaredcunha** [comment]
Hi @RLHecht I've submitted a [pull request with the updated content](https://github.com/department-of-veterans-affairs/vets-website/pull/22294):

**Comment by RLHecht** [comment]
@Mottie Yes, we realized we didn't need the rest of the content to be in the widget as the alternatives are still an option in either scenario.

**Comment by RLHecht** [comment]
@jaredcunha @Mottie I just added the react widget to our page to review. The "Request a COE on ebenefits" link needs to be an action link, like it is currently. The widget shows it as a text link. Could you please update?![Screen Shot 2022-10-25 at 12.46.23 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d73c1358-0a82-49ff-989a-2cbb49d9906f)![Screen Shot 2022-10-25 at 12.46.40 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/2e069853-39fe-461e-b13b-bf7222773100)

**Comment by Mottie** [comment]
Updated, thanks to @jerekshoe

**Comment by RLHecht** [comment]
I added this widget to the [eligibility page](https://www.va.gov/housing-assistance/home-loans/eligibility/) too, where we currently have an action link to eBenefits. Both of these pages are ready to publish when the product team gives us the go-ahead.

**Comment by RLHecht** [comment]
@Mottie Is there a set date for the incremental launch? We'll need to publish this page with the react widget as the entry point for the tool. Thanks!

**Comment by saderagsdale** [comment]
@RLHecht Hey Randi - yep, tentatively planning for January 4th, barring any issues in staging (we’ve continually run into challenges with staging in the past few weeks). @data-doge (Eugene) is working on release prep and can help answer questions.

**Comment by RLHecht** [comment]
Thanks. @data-doge Can you confirm that this widget is set to show one type of content to 25% of users and different content to 75% of users? For 25% of users we should be pointing to the new COE tool. For 75% of users we should be pointing them to eBenefits. We aren't able to confirm that in drupal. I want to make sure the widget was correctly created so that there is content in both versions.

**Comment by data-doge** [comment]
Hello @RLHecht! Yes, when we turn COE on for 25% of users, then that 25% segment of users will see a link that points to the new COE tool. The remaining 75% will see the old link to eBenefits. ([link](https://github.com/department-of-veterans-affairs/vets-website/blob/790f5b603e06ddfee4d445961b20ef366ce65a68/src/applications/static-pages/coe-access/COEAccess.js#L13)). Put another way, any user for which the new COE form is enabled will be directed to the new COE form, and vice-versa.

**Comment by RLHecht** [comment]
Perfect, thank you! Please let us know once you've launched to 25% so we can publish our 2 pages that have those entry points.

**Comment by data-doge** [comment]
Will do! 🤝

**Comment by Mottie** [comment]
@RLHecht We're launching COE to 25% tomorrow. While testing the static page today, we're not seeing the action link pointing to the VA COE page we built. Can we get this added now?

**Comment by RLHecht** [comment]
@Mottie Are you looking at the Drupal preview page? http://preview-prod.vfs.va.gov/preview?nodeId=754 The widget is set up in there. Right now it's showing for me the ebenefits link. I'm unable to see both sides of it.

**Comment by Mottie** [comment]
We were looking at production - https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/

DM me your va.gov login email and I'll add you so you can check

**Comment by Mottie** [comment]
In the Drupal preview page, I am seeing the expected `coe_access` widget rendering

**Comment by RLHecht** [comment]
@Mottie This wouldn't show live yet since the tool hasn't launched. We always publish the static page once the tool is live so we don't have a broken link on prod. So if your tool is launching in the morning, we can publish our pages once you give us the go ahead that it's up and running OK. In general it takes about 30 minutes from when we hit publish to once it's live.

**Comment by data-doge** [comment]
Hey @RLHecht @Mottie! Just jumping in here to clarify that we won't be launching to 25% tomorrow at 10am ET. We launched a small pilot limited to internal users today, and expect to run that pilot through the rest of this month, at least.

**Comment by saderagsdale** [comment]
@data-doge the feature flag is set to 0%, right?

**Comment by data-doge** [comment]
@saderagsdale Yep! We're at 0% right now.

@RLHecht Another clarification, if warranted. The COE form is already live on production, but behind a feature toggle. We are enabling the COE form for individual users during this pilot. So COE is in production and "live" for those individual users, and we're hoping to show this updated static page, for those individual users, using the coe feature toggle. Happy to get on a quick call if that would be helpful. Thanks!

**Comment by Mottie** [comment]
The app is live in production. With the feature flag off, you'll only see a WIP alert on this page - https://www.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction

**Comment by data-doge** [comment]
@RLHecht @Mottie Yep! We are all good to publish today 👍

**Comment by RLHecht** [comment]
@megzehn Can you do a final copyedit and publish these 2 pages? https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/ and https://www.va.gov/housing-assistance/home-loans/eligibility/

**Comment by Mottie** [comment]
@megzehn Sorry, I was looking at the Supplemental Claims ticket that you updated with document changes for that form. Were there any changes for COE? This is the form that we was released into a pilot today.

**Comment by megzehn** [comment]
Hi @Mottie -- no changes to the widget text for COE. I'm just reviewing the rest of the page now before publishing.

**Comment by megzehn** [comment]
Confirming these are now published!

**Comment by RLHecht** [comment]
These are live. Closing ticket.
