### ISSUE TITLE
BE - Auth Profile - Notification Preferences - Add Default Send Indicator (Opt-in)

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#43910]
## Background
VA Profile provides a _Default Send Indicator_ for each Communication Item (per each associated Communication Channel). 

In the case when a customer (Veteran) has not made their own permission selections in their VA.gov profile, this flag identifies whether to send or not to send a notification on the channel. 

The indicator will be _True_ or _False_ for each communication item.

If a VA customer makes changes to their communication permissions within their profile, the VA customer's permissions will take precedence over any default send configuration settings.

This ticket will add a `default_send_indicator` field to the communication items returned from the `GET /v0/profile/communication_preferences` endpoint so that the user will know which communication items they have been automatically "opted-in" for.

## Tasks
- [x] Retrieve `DefaultSendIndicator` from VA Profile `/communication/v1/communication-items` endpoint.
- [x] Include a `default_send_indicator` field with the data returned from the vets-api `GET /v0/profile/communication_preferences` endpoint.

## Acceptance Criteria
In staging, ensure that
- [x]   the vets-api returns a `default_send_indicator` of `true` for a communication item that has a `DefaultSendIndicator` of `true` in VA Profile.
- [x]  the vets-api returns a `default_send_indicator` of `false` for a communication item that has a `DefaultSendIndicator` of `false` in VA Profile.

**Comment by mtcA6** [comment]
@adamwhitlock1 so we know the default send is available in the BE, do we need to have a FE ticket to make use of that default information we're getting? 

CC: @mtcA6
