### ISSUE TITLE
Collaboration Cycle for [Benefits Team 1, Supplemental Claims Form 20-0995]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#43919]
staging ## VFS product information

### VFS team name

Benefits Team 1

### Product name

Supplemental Claims Form 20-0995

### Feature name

Supplemental Claims Form 20-0995

### GitHub label for product

Supplemental Claims

### GitHub label for feature

Supplemental Claims

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

6/29/2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/readme.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add all requested artifacts below **at least two days before** the scheduled Design Intent
  
**Design Intent artifacts**

- [Sketch files with flows and individual mobile first pages](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89)
- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims/Research)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/44414
- [Design folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims/design)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: July 28th at 1:30pm ET
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
  - [x] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/Q2R7bKgUaaXAtZ-OA-edsfYAALevZeIjwFJeD3mW0MnR7vZEgrk67-yMx4YTOwWa.hF5QMNpvgZ5pWAmy)
  - Password: YZ3LA.9F
  
##### VFS actions

- [x] Respond to feedback tickets
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Add or update all requested artifacts below **at least two days before** the scheduled Midpoint Review
  
**Midpoint Review artifacts**
Provide links or documents for the following:

- [x] [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims)
- [x] [Finalized design prototype or mockup](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676) 
- [x] [Research plan:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/MVP%20Usability%20Research/researchplan.md) 
- [x] [Conversation guide:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/MVP%20Usability%20Research/conversationguide.md) 
 
**Content artifacts**
- [x] Your product’s content source of truth: 
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): 

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [ ] Link to test cases/test plan in TestRail (draft OK): 
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: September 2 at 11:30 am ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
  - [ ] QA has completed the review
  - [x] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - [Recording URL](https://oddball-io.zoom.us/rec/share/Vei4O1EttOyPddXbiYMYIW_P200IhHEqh4gLS3iSABzHnsjFXOE1_mrnwUuwdtdu.v4kCwqul4tK_bCT8)
  - Password:^=14MpZD
  
##### VFS actions
  
- [x] Respond to feedback tickets
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket ([link here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50625))

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] [Link to the Contact Center review request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51452)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Add or update all requested artifacts below **at least four days before** the scheduled Staging Review
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
  
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- [Release plan with the "Planning" sections completed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/release-plan-draft.md)
- [Staging URL and staging test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Suppmental%20Claim%20Form%20Test%20User%20Information.md)

**Content artifacts**
- [x] [Content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [x] [Static landing page (in Drupal staging) for Supplemental Claims](http://preview-prod.vfs.va.gov/preview?nodeId=3011) - page exists in production but new updates made by Sitewide CAIA are in staging
  
**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- Regression test plan (The supplemental claim form doesn't have prior functionality to test because this is the first version of the product
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/4546)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/402)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/403) and [Github tracker epic for defects](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/appeals/995/tests/995-supplemental-claim.cypress.spec.js)
- [x] [Code coverage](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)  

  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: Thursday March 30th at 2 EST
- [x] [Slack thread request](https://dsva.slack.com/archives/CBU0KDSB1/p1679252799114569)

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/M_ICjrd2Vy2I2BLFB5QAV8ZHKcfSurBbSak9IEBhNJeAzMMxrfO9mrtG2JF1CX-u.CW9xflikcJIbh1tQ
  - Password: `0Wkc0q+H`
  
##### VFS actions
  
- [x] Respond to feedback tickets
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Update the VFS product information section with the product’s launch date and production URL after it has gone live

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] [ Link to the Readiness Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/678)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by saderagsdale** [comment]
@thehastingsp next steps are here for the collab cycle.

**Comment by thehastingsp** [comment]
Added design intent as an issue @allison0034 @saderagsdale

**Comment by saderagsdale** [comment]
@allison0034 the design assets are in the ticket Pam attached to this epic, just for awareness.

**Comment by allison0034** [comment]
@saderagsdale please link the assets under the "Design Intent artifacts" section. Let me know if you have any questions.

**Comment by saderagsdale** [comment]
@allison0034 Done. I added the artifacts to the "design Intent Artifacts" section. cc @thehastingsp

**Comment by saderagsdale** [comment]
@thehastingsp To initiate a midpoint review we have to update the midpoint review section of this ticket.

**Comment by thehastingsp** [comment]
Updated midpoint review section and added initial artifacts. Will follow up with conversation guide. Scheduled review for 9/2 at 11:30 ET.

**Comment by thehastingsp** [comment]
- [x] Content/IA process ticket[ is here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46818).

**Comment by saderagsdale** [comment]
Link to product directory ticket: https://github.com/department-of-veterans-affairs/product-directory/issues/659

**Comment by eileen-coforma** [comment]
Including a link to the preview for the sitewide Supplemental Claims intro page: http://preview-prod.vfs.va.gov/preview?nodeId=3011, which is an entry point to the form.

CC: @bethpottsVADEPO @katherine-fung
