### ISSUE TITLE
Supplemental Claims | Fix breadcrumbs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#43928]
## Description

The new Supplemental Claims form isn't including breadcrumbs. In the `content-build` repo, the entry for this form is missing the `"includeBreadcrumbs"` setting and the `"breadcrumbs_override"` should be defined _inside_ the `template`.

## Tasks

- [ ] Add `includeBreadcrumbs` property
- [ ] Move `breadcrumbs_override` setting inside the `template`

## Definition of done

- [ ] All tasks complete
- [ ] Breadcrumbs are showing up!
