### ISSUE TITLE
Create Vet Centers one-pager for newly published pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43924]
## Issue Description
Once we publish new Vet Center pages, we change the permissions for the content editors so they can publish their own changes going forward. To make sure these pages continue to meet our plain language standards and follow the VA.gov style guide, we need to provide editors with a one-pager of rules to keep in mind when updating their pages.

Once we create this, we will show it to Beth for feedback before sharing with Jessica and Tiffany.

## Tasks
- [x] Create one pager (Megan/Randi)
- [x] OCTO-DE review (Beth)
- [ ] Send to Jessica and Tiffany (Megan/Randi)

## Acceptance Criteria
- [ ] New Vet Center content publishers have a one-pager to use when updating their pages

**Comment by RLHecht** [comment]
@megzehn I've started a Google doc for this one-pager. Feel free to add to it or change anything I have. Once you're done I'll put in a Word doc for Beth to review. Thanks! 

https://docs.google.com/document/d/1mnQOEIfpUjyqcl7djoaB6WPeJjTcDDWohm8BlojfrOY/edit

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's our one-pager we want to start sending to Vet Centers once we've published their pages. Once you've approved it we'll send to Jessica for her review.

[https://app.zenhub.com/files/133843125/aa87f148-213b-43a2-97e6-fdc30e7fffc3/download](https://app.zenhub.com/files/133843125/aa87f148-213b-43a2-97e6-fdc30e7fffc3/download)

**Comment by RLHecht** [comment]
Moving to blocked while we wait for Jessica's feedback
