### ISSUE TITLE
[Design] Add Scenario to User Flow Documentation

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43927]
## Background
We need to add this [scenario ](https://dsva.slack.com/archives/C022AC2STBM/p1657128770816119)and wording to our user flow documentation and messaging source of truth. [Additional comments in Abstract](https://share.goabstract.com/3d58748e-1359-4a5c-afc6-c8514ddc2a73?collectionLayerId=b1a0274d-9416-4fad-a663-882770c0f7af&mode=design)

Scope:

CI:
- [x] Add a decision flo chart for "I'm here..."
Message: 
"We now offer mobile check-in instead of the "I am here" process. Please go to the clinic waiting room. We'll send you a link to check in on your smartphone soon. In the future, text "check in" to 53079 when you arrive."
- [x] Adding a text msg to CHIP
- [x] Simplify the screenshots to lofi wireframes

## Tasks
- [x] Add Scenario to User Flow Documentation

**Comment by sarahknoppA6** [comment]
per zach this is validated and can be closed.
