### ISSUE TITLE
Product Directory-YAML Form: Iterate on Form Usability

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#43925]
# Description
Several areas with opportunities for better usability were identified during usability testing. We will experiment with increasing form usability by focusing on three areas:
1. Refining the help text in the form
2. Adding links in the help text to resources that contain additional context or data
3. Increase the readability of the field descriptions by collapsing the information and segmenting it with horizontal rules

# Tasks
- [x] Review the current help text for each field
- [x] Propose improvements to help text where applicable
- [x] Provide links in the field help text to documentation and other resources that will add context or even provide the data
- [x] Use [collapsible details markdown formatting](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) to increase the readability of the form
- [x] Use horizontal rules to group and segment the help text and input fields for the form

# Acceptance Criteria
- [ ] Usability issues from the three key areas identified in the ticket have been addressed

**Comment by holdenhinkle** [comment]
Draft PR - https://github.com/department-of-veterans-affairs/product-directory/pull/318

**Comment by holdenhinkle** [comment]
Applicable links I gathered while we were discussing these updates during a meeting the other day:

- Updating form text with images and expanding sections:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown
- https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images

**Comment by holdenhinkle** [comment]
In order to see the changes made to the form yaml file, it has to be merged to main. I've been iterating on the form quite a bit and have merged a number of small branches.

Here's the way the form currently looks:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/fd1c5572-4dd4-41e2-aad8-4d675a63de98)

Here's an example of an expanded `field info` block:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/01009634-5aa7-4083-9810-74b6d8077149)

Here's an example of an expanded `field info` block with an random image, just to prove that we can add a image:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/f83ae3e7-03b7-40c9-8a07-0e888d75a7c4)

**Comment by holdenhinkle** [comment]
Here's the updated LOA field (change from text input to dropdown):
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/54fb8e85-b39f-45af-a2e0-cf6f2f1a1a13)

**Comment by holdenhinkle** [comment]
[Callout formatting](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) doesn't work :-(

```
# Overview

This form serves as a way to make a change to the VFS Product Directory.

# Instructions

{% warning %}

**Warning:**  
- :warning: Only enter values for fields that require a change. Empty fields will default to current values. :warning:

{% endwarning %}
  
{% note %}

**Note:**  
- Please be careful to follow the formatting guidelines provided to ensure there are no issues with the request
- If you have any questions, please contact us for guidance at: #platform-qa-standards in Slack

{% endnote %}

## Adding Features
Features are not currently supported by this form. If you have any requests to add features to your product, please file a support request with the QA Standards Team in [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1).

## After Submission
A comment will be added to this issue outlining the next steps. You will be notified of comments in accordance with your current GitHub notification settings.

### Additional Reference

[User Guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation)
[Product List](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2213216257/VFS+Product+Directory+TEMPORARY)
```

Here it is when rendered:

# Overview

This form serves as a way to make a change to the VFS Product Directory.

# Instructions

{% warning %}

**Warning:**  
- :warning: Only enter values for fields that require a change. Empty fields will default to current values. :warning:

{% endwarning %}
  
{% note %}

**Note:**  
- Please be careful to follow the formatting guidelines provided to ensure there are no issues with the request
- If you have any questions, please contact us for guidance at: #platform-qa-standards in Slack

{% endnote %}

## Adding Features
Features are not currently supported by this form. If you have any requests to add features to your product, please file a support request with the QA Standards Team in [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1).

## After Submission
A comment will be added to this issue outlining the next steps. You will be notified of comments in accordance with your current GitHub notification settings.

### Additional Reference

[User Guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation)
[Product List](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2213216257/VFS+Product+Directory+TEMPORARY)

**Comment by holdenhinkle** [comment]
Removed the `description` for each field:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/89fe0b6a-156c-439f-9ee0-79be13fff6f2)

**Comment by holdenhinkle** [comment]
This is complete!
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/1035793c-cf15-448e-a457-c518eb6912eb)

**Comment by pjhill** [comment]
This addresses usability significantly. This looks great now!
