### ISSUE TITLE
Product Directory-General: Conduct an audit of documentation and make corrections accordingly

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43929]
## Issue Description
The process for modifying an entry in the VFS Product Directory requires the use of a few pages that are all text heavy, and additionally do not use terminology consistently from one page to another. We need to conduct an audit to ensure that our documentation for this process is clear, concise and consistent.

Specific issues with consistency
- Use of the term VFS Product Directory
- Use of the terms Form/Issues

---
## Tasks
- [x] Review the 4 pages of our documentation:
   - [x] [VFS Product Directory Page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2220556289/User+Research+Product+List)
   - [x] [VFS Product Directory Help Document](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation)
   - [x] [VFS Product Directory User Guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/Updating+the+VA.gov+Product+Directory?atlOrigin=eyJpIjoiZjUwMWJmZjE1ODQ2NDM0M2JjYmMxMzExNDMwNzkxMWMiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)
   - [x] [YAML Form](https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=cbonade&labels=&template=update-product-request.yml&title=Product+Directory+Change+Request+for+%5BProduct+Name%5D)
- [ ] Document findings and recommendations in a Google Document

## Acceptance Criteria
- [ ] Review findings with QA Standards leadership, make tweaks as necessary
