### ISSUE TITLE
Product Directory: Change TestRail ID to TestRail URL

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43937]
## Issue Description

Based on some of the confusion that we saw in the usability tests, we believe that asking for the TestRail URL will cause less confusion with VFS teams.

---

## Tasks
- [x] Update the guidance in the form
  - In the guidance, be sure inform the user that the input is a URL, but the list will extract and display a unique TestRail project ID from the URL
- [x] Update the script that updates the list to process the URL into an ID
- [x] Update the help pages in Confluence

## Acceptance Criteria
- [x] The form contains guidance for the user to grab the correct URL from TestRail and informs the user how it will be used and displayed
- [x] TestRail project IDs are extracted from the URL and stored as integers in VFS Product Directory
- [x] VFS Product Directory help page contains information about the TestRail project URL / id

**Comment by CBonade** [comment]
This is completed. All testrail URLs that will contain the ID, have the ID as the last segment of the URL. On submission, the validation script pulls off the last segment of the URL and checks if it can be converted to an integer. If it cannot, it will reject the submission. If it passes validation, the last URL segment will then be added to the changes for the PR.

**Comment by pjhill** [comment]
I think the doc needs a quick update -- https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation

**Comment by pjhill** [comment]
Looks good, I mistakenly thought that the help document should be updated to change `testrail_project_id` to `testrail_project_url`, but that's not how this works.

Closing this out!
