### ISSUE TITLE
[Design] Profile 2.0: Onboarding for Tressa

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4393]
## Background

Tressa — let's use this ticket to track your onboarding to the Profile 2.0 project. We'll consider this done when you're ready to start working on the project.

## Tasks

- [x] Initial meeting with Samara to go over the Profile 2.0 project
- [x] Sign into staging and get super familiar with the profile and account pages/functionality
- [x] Read through [personalization 2.0 discovery writeup](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Personalization%202.0/Discovery%20%26%20Research/Personalization%202.0%20Discovery%20Summary%20%26%20Strategy.md)
- [x] Look through Sketch files (sent over Slack)
- [x] Come up with questions
- [x] Meet with Samara/whomever to get answers to questions

## Acceptance Criteria:

- [ ] All of the items in the checklist above are completed.

**Comment by Samara-Strauss** [comment]
Cc/ @Justin-Pickett just want you to know I created this for Tressa. Given how much time off I'm taking/Tressa is taking, we don't need to track this as part of Sprint 11. If this is done before Jan 2, great. If not, it will become part of Sprint 12 objectives.

**Comment by Justin-Pickett** [comment]
@Samara-Strauss okay sounds good.

**Comment by Samara-Strauss** [comment]
@tressaellen are we good to close this?

**Comment by tressaellen** [comment]
@Samara-Strauss Yep, we're all good to close this.
