### ISSUE TITLE
Product Directory: Expand repository fields

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43939]
## Issue Description
We need to collect three categories of repositories from the product teams:
1. front-end repo (Where is your front-end code living? We expect to see `vets-website` a lot.)
2. back-end repo (Where is your back-end code living? We expect to see `vets-api` a lot.)
3. other repositories -- this field will accept multiple repository names (This could be utilities maintained for the product, or other ancillary code that supports the product.)

---
## Tasks
- [x] Rename `repository` to `frontend_code_repository`
- [x] Add two extra columns to the schema
  - [x] `backend_code_repository` (string)
  - [x] `other_code_repositories` (array)
- [x] Update the form and the guidance in the form
- [x] Update the help pages in Confluence

## Acceptance Criteria
- [x] The product directory displays the `frontend_code_repository` as a column, the helper text references the correct field name, and the values previously listed under `repository` are now listed here
- [x] The product directory displays a column named `backend_code_repository`
- [x] The form displays a field named `backend_code_repository` and helper text is displayed in proximity to the field
- [x] The product directory displays a column named `other_code_repositories`
- [x] The form displays a field named `other_code_repositories` and helper text is displayed in proximity to the field
- [ ] Review guidance/documentation to ensure the change is reflected consistently across resources

**Comment by rsmithadhoc** [comment]
- PR created for this: https://github.com/department-of-veterans-affairs/product-directory/pull/338
- Once merged, there are a few tests that need to be done on the form and publish process.

**Comment by rsmithadhoc** [comment]
Setting for review:
- PR merged, test issue and PR worked as expected
  - https://github.com/department-of-veterans-affairs/product-directory/issues/342
  - https://github.com/department-of-veterans-affairs/product-directory/pull/343

**Comment by pjhill** [comment]
Looking good --
* 89 instances of FE
* 89 instances of BE
* 89 instances of other
* form updates look good
* repo fields listed in docs
