### ISSUE TITLE
Product Directory: Update product generator to use random UUID only

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43938]
## Issue Description
Currently, the [project generator](https://github.com/department-of-veterans-affairs/generator-vets-website) for `vets-website` allows a user to input a product ID, and in lieu of them doing so, will generate a random UUID. We'd like to remove the option to put in a custom one, and force a UUID automatically when new projects are created. Release tools will need to be looped in on these changes.

---

## Tasks
- [x] Notify release tools of intended goal
- [x] Remove option for users to input a custom ID on project generation

## Acceptance Criteria
- [ ] When a new project is generated it comes with a UUID already attached to the `productId` field.

**Comment by CBonade** [comment]
I've completed this update and it's just pending release tools approval to be merged in. Will update when I have a response from their team.

**Comment by CBonade** [comment]
This is merged into the master branch and release tools is handling updating the npm package registry

**Comment by pjhill** [comment]
The change is indeed merged and looks good -- thanks!
