### ISSUE TITLE
Product Directory-Attribute List: Review attributes internally with the Governance Team to ensure alignment

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43934]
## Issue Description
There was confusion around the meaning/intent of some fields in the VFS Product Directory. In order to resolve that, we should review our current uses of terminology in these areas, and discuss with the Governance team to determine if they have suggested changes that VFS teams may be more accustomed to.

Specific Issues:
- **Point of Contact** - Teams aren't sure who to add, and often want to add multiple people, which increases the risk of error
- **Business Owner** - Teams aren't sure what to put here, in most cases, they felt it was a person, usually their PO
- **Launch Date** - Was uncertainty about what launch date to use, if it was for the launch of an iteration, or the original launch date, the original launch date predates the person who was doing this, so they weren't sure what date it should be
- **Crew Lead** - People didn't know who this was, and ended up putting their Product Owner
- **Features** - Teams were confused by this process, the feature field is too complex to add effectively through a form, so it is shown, butt we don't let them modify - and instead ask them to submit a GitHub issue specifically for that - it seems like a bad process that will cause frustration
- **LOA** - Teams were confused by what this meant, they sometimes ended up at the right conclusion, but other times, for products that did not require authenticated users, they were still confused. Have you had any confusion or need for clarification on this?

---
## Tasks
- [x] Review the attribute list and make a list of specifics to discuss with the Governance Team
- [x] Review with governance team and document findings/decisions -- Be sure to include Joe Tice in the meeting

## Acceptance Criteria
- [x] Findings of the governance team review are documented and available for review

**Comment by rjohnson2011** [comment]
Had meeting with Governance team and documented notes here -> https://docs.google.com/document/d/13gwu8nUZsVb3wV0OvMLT537SyZx_oUQnIqCs9PeBkgg
