### ISSUE TITLE
Login Wizard Preliminary Research

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#43933]
## Issue Description
Perform a round of preliminary research around the Login Wizard. The goal is to obtain initial reactions to an early iteration of a clickable prototype as well as gain an understanding of how veterans and users typically address login issues.

---
## Tasks
- [ ] Build a research plan for the first round of usability testing
- [ ] Build a conversation guide for the usability testing
- [ ] Have the documents reviewed and approved by either Clayton Z or Shane S
- [ ] Initiate recruitment with Perigean

## Acceptance Criteria
- [ ] Has the research plan and conversation been approved?
- [ ] Has recruitment begun?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Closing due to weird ZenHub bugginess creating duplicate issues.
