### ISSUE TITLE
[Datadog] Disable dual shipping datadog BRD and EKS

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#43941]
## Description
Now that the old app.datadoghq.com account has been disabled by dots and we have migrated everything to the vagov.ddog-gov.com org we will need to disable dual shipping.

This will take some effort as the vagov.ddog-gov.com is currently configured as our dual shipping additional endpoint and we will need to set it as the main endpoint in our agent configs.

so Instead of what is laid out below 
https://docs.datadoghq.com/agent/guide/dual-shipping

All of the additional endpoints will be removed and we will need to make various changes in both EKS helm charts for all clusters and BRD ansible configs.

---
## Tasks
- [x] modify configs to make the datadog agents send to vagov.ddog-gov.com as its main endpoint with the appropriate api key in EKS 
- [x] Remove any dual shipping configurations in EKS
- [x] modify configs to make the datadog agents send to vagov.ddog-gov.com as its main endpoint with the appropriate api key in BRD 
- [x] Remove any dual shipping configurations in BRD

## Acceptance Criteria 
- [x] Datadog agents are only sending metrics to vagov.ddog-gov.com

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Confirmed working in staging
<img width="587" alt="image" src="https://user-images.githubusercontent.com/76792875/177833856-8c2384c0-d4cf-45f5-8220-45382393ad9b.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/76792875/177833892-4e34c915-9418-4cce-a869-1ef513ab4f17.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/76792875/177833942-ab6851d0-33d8-4b4c-b266-83ea84eb71c3.png">

**Comment by mleclerc00** [comment]
Confirmed working in remaining EKS clusters

DEV
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177842741-925dba43-a9c5-4155-853a-b1e14735396c.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177842805-3e60c72e-5e01-4070-b369-16c0e85f1a63.png">
![image](https://user-images.githubusercontent.com/76792875/177842921-d55366c4-39a8-47d0-ab38-28afbcb1106b.png)

SANDBOX
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177843225-d56b7da0-f69c-4991-8cbf-42526efa9dae.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177843263-1351ce41-2f05-47a2-b1f6-8102a6f3485a.png">
![image](https://user-images.githubusercontent.com/76792875/177843362-f43a6417-d7f2-47fd-9564-f3513c2ab8c9.png)

PROD
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177843679-e94f335c-1b9d-4060-8422-708169edb317.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177843743-9911a002-0c25-4712-85aa-8d5c61eaa56d.png">
![image](https://user-images.githubusercontent.com/76792875/177843843-6493cb9d-2537-4789-8b23-9434bd9141ef.png)

UTILITY
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177844237-5a77a1aa-1622-4645-866d-896c046857ea.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/76792875/177844284-8b414eb9-b13d-4642-8fa3-631971b4b233.png">
![image](https://user-images.githubusercontent.com/76792875/177844434-8aafe109-3911-431c-b3b5-2d28d8d5d76a.png)

**Comment by jbritt1** [comment]
BRD changes to datadog docker agent look good so far:

![image](https://user-images.githubusercontent.com/56260532/178786949-f7c9bd8f-e5a1-4fd8-ba6f-77a8f41f43ed.png)

**Comment by jbritt1** [comment]
RedHat package (non docker, binary) also looks good so far:

![image](https://user-images.githubusercontent.com/56260532/178787258-d8fd2eca-fcde-4dce-99b9-4d51006722a5.png)
