### ISSUE TITLE
Product Directory-User Guide: Update the user guide

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43947]
## Issue Description
Update the user guide to reflect the changes from [the audit](https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/43929), as well as a couple items that were identified in the usability studies

---
## Tasks
- [x] Update the tasks of this ticket to reflect the changes identified in the [documentation audit](https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/43929)
- [x] Add guidance on the naming of the GH issue in the YAML form
- [x] Add guidance on the Feature field

## Acceptance Criteria
- [x] All updates have been made and reviewed

**Comment by rjohnson2011** [comment]
Make minor modifications to the user guide based on notes from the conversation w/Joe. Finalizing the Changeable vs Closed attributes section.

**Comment by rjohnson2011** [comment]
Made requested changes after reviewing with Joe.
