### ISSUE TITLE
Product Directory: Update Help Documentation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#43942]
## Issue Description

The [VFS Product Directory Help Document](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation), will need some updates based on our usability testing, along with an audit that is being done to the documentation.

---

## Tasks
- [x] Add resulting changes from the [documentation audit ticket](https://app.zenhub.com/workspaces/sprint-board-qa-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/43929) for the [VFS Product Directory Help Document](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation)
- [x] Add guidance on POC being only one person

## Acceptance Criteria
- [x] All updates have been made and reviewed

**Comment by rjohnson2011** [comment]
Confusion surrounding POC being only one person is updated on the form as VFS PM.

**Comment by pjhill** [comment]
Thanks -- closing this one out.
