### ISSUE TITLE
Automate adding new products to the product directory based on manifests

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#43949]
## Issue Description
When a new product is added to vets-website, a manifest is generated that will contain a UUID under the `productId` field. We should check these UUIDs against the product directory, and any that are not included should be added to the list automatically. We then need to update the yaml template to include this product if a new one was added.

---
## Tasks
- [x] Add checking for new products to the daily automated product directory scan based on UUIDs in manifests that do not exist in our product directory already. 
- [x] If there are new products, add them to the list.
- [x] If new products were added, run the workflow to update the yaml list (should be able to add a workflow dispatch step to the existing workflow for this).

## Acceptance Criteria
- [x] New products added to vets-website are automatically added to the product directory.
---

**Comment by CBonade** [comment]
PR is open to solve this issue here. It adds the product id and name before the existing automated checks to ensure that the existing checks get populated accordingly. It additionally checks the manifest ID to ensure it is a 36 character ID (matches a valid UUID length) so we don't get any products added with an ID of "1" or the such.
