### ISSUE TITLE
Explore options to better display the full product directory

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#43951]
## Issue Description
The [product directory confluence page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2220556289/User+Research+Product+List) is very hard to look through as it spans many screen heights and widths. We need to experiment with ways to make this easier to digest. Some ideas we had for elements we can use:

~~Expand Boxes~~ (removed)
~~Defining column widths on the table~~ (removed)
- Making an individual page per product

---
## Tasks
- [x] Test out different strategies for cleaning up the appearance of the confluence product directory
- [x] Record findings on this ticket and discuss with team.
- [ ] Once a solution is agreed on, implement in the auto-page-generation script to ensure the product directory is generated in that fashion going forward.

## Acceptance Criteria
- [ ] The automatically generated product directory page in Confluence enables users to locate their products more quickly and easily
---

**Comment by rsmithadhoc** [comment]
Updated the branch linked above and working on:
- Table of contents in Confluence was tested and working.
- Working on generating unique filenames/paths and HTML to put on an individual page for each product. Ensuring that product updates will successfully regenerate the table of contents and page as to not leave any orphaned pages or break any links.
- I will look into a solution for splitting open/restricted fields since we will need some sort of config to store that.

**Comment by pjhill** [comment]
That draft PR is looking pretty great. I have a few questions about how this implementation is progressing --

1. How did you generate the pages for each product?
1. How will this solution deal with a new product being introduced to the product directory?
1. Given that each product's attributes is alone on a page now, it may not be the best formatting to display the attributes in a table. Have you explored any other formatting options? Depending on how you generated each product page this may be more or less painful :p

**Comment by rsmithadhoc** [comment]
> That draft PR is looking pretty great. I have a few questions about how this implementation is progressing --
> 
>     1. How did you generate the pages for each product?
> 
>     2. How will this solution deal with a new product being introduced to the product directory?
> 
>     3. Given that each product's attributes is alone on a page now, it may not be the best formatting to display the attributes in a table. Have you explored any other formatting options? Depending on how you generated each product page this may be more or less painful :p

1. To generate the pages: I looped over the product directory, converted each product to an HTML string representation, then wrote that string to an HTML file with the name of the product converted to param-case as the filename.
2. This will handle any new products added because it will either overwrite an existing page or create a new one.
    - It is currently set up to process the entire list each time it runs, so any products added will be captured in the resulting output. Example: If "My New Product" gets added, it will show up on the regenerated index, all other product pages would be regenerated and overwrite their existing files, but a new `my-new-product.html` would be created. 
    - It currently doesn't handle product deletion, a product being deleted would leave an orphaned HTML file (but this wouldn't affect the directory, it would just take up space). This could be solved by deleting any existing pages at the start of the process. Since it processes the whole list, all pages would be regenerated and the new resulting pages would have the latest information. This would also help clean up orphaned pages if a product name was edited.
3. I have not explored an alternative view to a table but I can look into it. It should be straightforward to change the display if we decide on something better, we'll still have to loop over the list and pull out the key/value pairs.

**Comment by pjhill** [comment]
Nice, thanks for the quick reply. Somehow I missed the bits where you were actually building the TOC and the product pages in that PR the first time I looked at it.

Re: 2 -- This sounds like a good solution. What impact would deleting all the product pages and recreating them each time have on something like Confluence's page history / diff functionality. One thing to consider (and that we haven't done good job discussing so far) with this solution is that eventually the product directory will be consumed on the Platform Website as rendered by the Scroll Viewport plugin. Scroll Viewport has a publishing mechanism where changed pages are queued up for publication. If we are re-creating the pages each time would Scroll Viewport detect that as a change for publication? What impact would that even have.  ... I have no answers, but these shouldn't be TOO hard to discover the answers to.

I just created [this ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/44477) about publication of the product directory to the Platform Website, so hopefully we can get some of this answered either under that ticket or here.

**Comment by pjhill** [comment]
As for displaying with something other than a table, it seems like that's almost a certainty at this point (sorry). Usability testing showed that users were not enthused about consuming this data in table form, and we should have been more up front with that information during the creation/refinement of this ticket. I haven't looked at the table rendered output in your PR yet, but it may be good enough to avoid the usability issues of for example quite tall columns to display the feature list.

**Comment by rsmithadhoc** [comment]
> Nice, thanks for the quick reply. Somehow I missed the bits where you were actually building the TOC and the product pages in that PR the first time I looked at it.
> 
> Re: 2 -- This sounds like a good solution. What impact would deleting all the product pages and recreating them each time have on something like Confluence's page history / diff functionality. One thing to consider (and that we haven't done good job discussing so far) with this solution is that eventually the product directory will be consumed on the Platform Website as rendered by the Scroll Viewport plugin. Scroll Viewport has a publishing mechanism where changed pages are queued up for publication. If we are re-creating the pages each time would Scroll Viewport detect that as a change for publication? What impact would that even have. ... I have no answers, but these shouldn't be TOO hard to discover the answers to.
> 
> I just created [this ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/44477) about publication of the product directory to the Platform Website, so hopefully we can get some of this answered either under that ticket or here.

For Confluence/Scroll Viewport, based on [Curt's message](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43951#issuecomment-1182415000) above, I was going the route of:

- Generating a table of contents, which would be stored in Confluence + platform website.
- Generating the individual HTML pages, which might be hosted elsewhere (GitHub Pages, AWS).

Which would avoid those questions around Confluence/Scroll Viewport, since we'd only be concerned with the table of contents in Confluence. But I think we'd need to establish which route we are going:

1. Table of Contents + All product pages are viewable in Confluence and the Platform website via Scroll Viewport.
2. Table of Contents viewable in Confluence and the Platform website via Scroll Viewport. All product pages are "viewable" on the Platform Website via an external link (to GitHub Pages or elsewhere).

Either one will work for what I'm building, I think we just need to decide before we can proceed, and then I can answer the original Confluence/Scroll Viewport question, if still applicable.

**Comment by rsmithadhoc** [comment]
> As for displaying with something other than a table, it seems like that's almost a certainty at this point (sorry). Usability testing showed that users were not enthused about consuming this data in table form, and we should have been more up front with that information during the creation/refinement of this ticket. I haven't looked at the table rendered output in your PR yet, but it may be good enough to avoid the usability issues of for example quite tall columns to display the feature list.

No problem, it was easy to add some alternatives to the display to compare them, here's an example
[10-10-cg.html.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/9124020/10-10-cg.html.zip).
 They aren't pretty since they are plain HTML, but they give something to discuss and iterate on.

**Comment by rsmithadhoc** [comment]
Per discussion with Joe and Peter, we are good to close this one out and proceed with new tickets for the approach that was decided on.
