### ISSUE TITLE
Explore format for the YAML-form-generated GitHub issue to reduce height.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#43953]
## Issue Description
In our user testing, many users did not see the follow-up step for creating an issue, as the issue that's created is very long resulting from displaying all the form entries. We should try and shorten this up so the user can see the follow-up comment, to avoid users becoming confused about the rest of the process. Try things such as collapsing the form input results,  or only keeping the form input results that had changed values.

---
## Tasks
- [x] Find a way to shorten the issue that is created from the GitHub issue form so the comment afterwards doesn't get lost.

## Acceptance Criteria
- [x] A short, concise issue is generated from our GitHub issue form.
- [x] The comment added by the workflow is visible on a 1000 pixel height
---

**Comment by CBonade** [comment]
The workflow has been altered to update the issue to a collapsed format before the follow-up comment is posted. Sometimes there is a delay based on GitHub runner availability, but also the follow up comment is delayed as well so I don't think it matters. It will always collapse this before the comment is posted.

**Comment by pjhill** [comment]
Nice, this looks great and makes the comment much more noticeable -- still no guarantees that it gets read!
