### ISSUE TITLE
Remove v1 Claim Status Tool code

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#43964]
## Value Statement
**_As a_** frontend developer,
**_I want to_** remove v1 CST code
**_So that_** the CST codebase is more manageable

---
## Background Context
- CST is currently on v2, but the v1 code is still in the codebase. This makes it harder to keep the codebase manageable; we have run into cases where we go to update components just to realize that they are no longer used
- Some code is marked with 'V2' i.e. `ClaimsListItemV2.jsx`

## Acceptance Criteria
- [x] CST v1 code has been removed

## Designs and Build Notes
- Add here

## Out of scope
- We will need to update v2 code to remove the version references, this should be done in a separate ticket

## Open questions
- Add here

## Tasks
- [ ] Determine which code is v1 related
- [ ] Remove v1 code

* https://github.com/department-of-veterans-affairs/va.gov-team/issues/45064
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/44849

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
- [ ] ddd
