### ISSUE TITLE
Update content-build linting and testing rules to WCAG 2.1

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#43989]
## Description

Currently, the rules used in `content-build` linting and testing are set to [`wcag2a, wcag2aa`](https://github.com/department-of-veterans-affairs/content-build/search?q=wcag2aa). Because the standard is [WCAG 2.1](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing), we should update these to [`wcag21a, wcag21aa`](https://github.com/dequelabs/axe-core/blob/a3d5cef612013ffe0db5383a4047508654444d3c/doc/API.md#axe-core-tags).

## Tasks

- [ ] Run linting and test with the updated rules to determine if there are issues to fix.
  - [ ] If there are issues to fix, document and communicate them to the appropriate team. Create a follow-up issue to check on this at a later date.
- [ ] Merge the change to the rules.

## Acceptance Criteria

- [ ] WCAG 2.1 rules have been enabled. If not possible, any issues are documented/communicated to their respective team and a follow-up issue to check up on it in the future has been created.

**Comment by rsmithadhoc** [comment]
- Rules updated.
- Ran unit, E2E, and daily a11y scan without issues.
- Want to run a couple more tests to ensure new rules are being picked up.

**Comment by rsmithadhoc** [comment]
- [PR](https://github.com/department-of-veterans-affairs/content-build/pull/1257) out for review.

**Comment by rsmithadhoc** [comment]
Merged in these changes.
