### ISSUE TITLE
[CDP] Investigate GA for payment options

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#43990]
## Issue Description
It would be helpful to track when users jump from the combined portal to a payment page (overview or deails page) to see if we can put the link in a more common place to make payment easier for those accustomed to the process.

---
## Tasks
- [ ] Investigate GA tracking options for payment links
- [ ] Include new GA 4(*?) tagging options.

## Acceptance Criteria
- [ ] Determine if this type of tracking is already done platform/pay side and if we can implement
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Closing as dupe of https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46078 per convo with @Dr-Pongo
