### ISSUE TITLE
Modify FRP to have SDT capture and post new submissions

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43998]
## Issue Description
Modify FRP to have SDT capture and post new submissions

User Guide on Platform: https://depo-platform-documentation.scrollhelp.site/support/submitting-a-feature-request

Internal user guide in Confluence:  https://vfs.atlassian.net/wiki/spaces/AP/pages/1909293082/Feature+request+process+-+User+guide+for+Platform+teams

[Questions/Considerations](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2332131664/Improvement+Thinking+Research)

---
## Tasks
- [x] Research Github automatic notification
- [x] Update Internal User Guide language
- [x] Update Platform Guide language
- [x] add info on frequency of review
- [ ] consider moving post to VSP-Pm's  (talk w/ team about this)

## Acceptance Criteria
- [x] Internal User Guide language reflects new direction
- [x] Updated Platform Guide language reflects new direction
- [x] Frequency of review is clear in Platform Documentation
