### ISSUE TITLE
Survey Post-research workshop

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#43997]
## Purpose
discuss and evaluate learnings from research sessions

## Tasks
- [ ] workshop the learnings
- [ ] identify potential changes to include in survey's makeup or delivery method

## Acceptance Criteria
- [ ] potential changes are documented
