### ISSUE TITLE
OCTO-DE review and stakeholder feedback for duty to assist R&S article + FAQ page updates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44011]
## Issue Description
We created a new R&S article about "duty to assist" for decision reviews. This work was being done in ticket #44010.

This ticket is for Beth's review of this work, submitting to stakeholders for feedback and incorporating any subsequent changes. 

## Tasks
- [x] OCTO-DE review (Beth)
- [x] Incorporate changes to Drupal file (Katherine)
- [x] Copyedit (Megan)
- [x] Send to stakeholders for feedback (Laura)
- [x] Post final content for publishing in ticket #44012 (Laura)

## Acceptance Criteria
- [x] Content is approved and ready for final copyedit and publishing

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I'm attaching a draft of the duty to assist R&S article here for your review: 

[Duty.to.assist.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9191967/Duty.to.assist.docx)

A few questions we had for you, which are also noted in the comments in the doc: 

1. We tried to adjust the H1 to be a bit more narrow than simply "VA's duty to assist," but let us know if this still sounds too broad!

2. We didn't capitalize "duty to assist" in the draft -- does that look right to you? We looked around and didn't see this consistently capped, and SMEs had it both capped and uncapped in the content they submitted. 

3. Beth: We saw the language below on the CCK law firm’s page about duty to assist. We’re wondering if duty to assist also includes a duty to inform: 

"VA must inform veterans what evidence is needed to prove service connection. If a veteran is missing key documents showing their current diagnosis or in-service event, VA is required to let them know. VA must explain what evidence the veteran needs to locate, and what evidence VA will obtain on their behalf."

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO ,

I'm piggybacking on this duty to assist R&S ticket with Shireen's request to retain the main decision reviews FAQ page, since they're closely related.

Here's a document where I've taken the approach we talked about to link to existing pages, rather than duplicating large chunks of information on the FAQ page. We can also suggest moving this page into R&S as part of this update.

[Decision review FAQ new approach.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9601435/Decision.review.FAQ.new.approach.docx)

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thanks so much for your work on this. Here's my feedback on the duty to assist article. You can build it out in drupal and we'll see how it looks! Thanks so much, and let me know if you have questions about what I did. Sometime I'd like to explain how I came back around to using the broader H1. Let's find time--it was a process! Also, I answered the above questions in the Word doc.
[https://app.zenhub.com/files/133843125/19eaf519-eefa-4b48-973d-ab09a800c125/download](https://app.zenhub.com/files/133843125/19eaf519-eefa-4b48-973d-ab09a800c125/download)

@laurwill Here's the FAQ, which I think works great. Let me know if you want to talk about any of my edits. When you communicate with Shireen, would you let her know that we'd like to move this FAQs article to R&S where all our other FAQs live?[https://app.zenhub.com/files/133843125/bb88135d-548b-4353-83b2-1baec1a4e70c/download](https://app.zenhub.com/files/133843125/bb88135d-548b-4353-83b2-1baec1a4e70c/download)

**Comment by bethpottsVADEPO** [comment]
@laurwill @katherine-fung Here's the placement criteria we'll run through for the new R&S page, just to get used to this process:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/resources-and-support-author-pilot/process.md

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I'm posting the previews for these pages here: 

Duty to assist: http://preview-prod.vfs.va.gov/preview?nodeId=49994

Decision reviews FAQs: http://preview-prod.vfs.va.gov/preview?nodeId=50010

As we discussed, I removed the line  "How long does each decision review option take?" from the decision reviews FAQs. Both pages are formatted as rich text due to the limitations of the multi FAQ template.

**Comment by laurwill** [comment]
Thanks so much Katherine! These look great. 

@megzehn could you do a copyedit of just the new Duty to assist page? We're going to get Shireen's approval on the FAQ direction before we spend more time editing that one.

Here's the page for copyedit (not publishing yet): http://preview-prod.vfs.va.gov/preview?nodeId=49994

**Comment by laurwill** [comment]
I sent these to Shireen — will update when we hear back

**Comment by laurwill** [comment]
Update: Autumn and Shireen sent feedback on both pages. We'll need to review and update the draft pages. They also suggested having Board appeals SMEs review those updates. 

[Decision Review FAQs -OAR Feedback 2DEC2022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10339307/Decision.Review.FAQs.-OAR.Feedback.2DEC2022.docx)

[Duty to Assist Page-OAR Feedback 2DEC2022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10339305/Duty.to.Assist.Page-OAR.Feedback.2DEC2022.docx)

**Comment by laurwill** [comment]
Hi @megzehn , thanks for looking these over before I send back to Autumn and Shireen today — here are the docs. Since there are a couple open questions, I'll wait to update all the related Drupal nodes and tag you for a final copyedit.
[ Decision reviews FAQs](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/EYZ0IEyrSE5Hjl5Q1e_INfIBe2mvOPNdDtvR8LuR3men3A?e=RuA29K)
[ Duty to assist](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/EQn97miRJnZKk6-jyDckakkB1FFZ2t7MMqKfhA_j9D54vg?e=w7KIxq)

Let me know if you have questions!

**Comment by megzehn** [comment]
Update for the ticket: I finished reviewing these and sent my Qs to Laura!

**Comment by laurwill** [comment]
Update:
Shireen sent back these Word docs with additional comments and edits. I pulled out 2 remaining questions and sent them via email.

@katherine-fung , I copied you on the email thread — if Shireen responds while I'm out and you have time, you could move ahead with reconciling the latest feedback and updating pages in Drupal. [https://app.zenhub.com/files/133843125/72f122c0-bb87-41db-bc16-a7c445dd00f2/download](https://app.zenhub.com/files/133843125/72f122c0-bb87-41db-bc16-a7c445dd00f2/download)[https://app.zenhub.com/files/133843125/a4acbcd3-6317-4a85-8623-cd77add91ec7/download](https://app.zenhub.com/files/133843125/a4acbcd3-6317-4a85-8623-cd77add91ec7/download)

**Comment by katherine-fung** [comment]
Hi @megzehn, 

These pages are ready for copy edit: 

- VA's duty to assist: 
http://preview-prod.vfs.va.gov/preview?nodeId=49994 

- Decision review FAQs: 
http://preview-prod.vfs.va.gov/preview?nodeId=50010

- Higher-Level Reviews: 
http://preview-prod.vfs.va.gov/preview?nodeId=3003

- After you request a decision review: 
http://preview-prod.vfs.va.gov/preview?nodeId=3008 

Thank you!! 

Note for future reference: We will hold off on updating/publishing the Board Appeals page until a full review later on. (no need to copy edit)

**Comment by megzehn** [comment]
Thank you, @katherine-fung! Confirming these went live today!
