### ISSUE TITLE
Final copyedit and publishing of "duty to assist" R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44012]
## Issue Description
We created a new R&S article about "duty to assist" in decision reviews. The content work was done in ticket #44010. 

This ticket is for the final copyedit with the pre-publishing checklist and publishing of the page.

## Tasks
- [x] Final copyedit with pre-publishing checklist (Megan)
- [x] Publish page (Megan)
- [x] Alert stakeholder that page is live (Randi/Laura)

## Acceptance Criteria
- [x] New article is live

**Comment by katherine-fung** [comment]
Hi [@megzehn](https://github.com/megzehn),

These pages are ready for copy edit:

VA's duty to assist:
http://preview-prod.vfs.va.gov/preview?nodeId=49994

Decision review FAQs:
http://preview-prod.vfs.va.gov/preview?nodeId=50010

Higher-Level Reviews:
http://preview-prod.vfs.va.gov/preview?nodeId=3003

After you request a decision review:
http://preview-prod.vfs.va.gov/preview?nodeId=3008

Thank you!!

Note for future reference: We will hold off on updating/publishing the Board Appeals page until a full review later on. (no need to copy edit)

**Comment by megzehn** [comment]
I copy edited and published these! CC @laurwill and @RLHecht for the next step of alerting stakeholders.

**Comment by RLHecht** [comment]
@megzehn this may already be on your list, but I think we need to add this article to the decision reviews section on the R&S landing page since right now there are only 3 articles

**Comment by megzehn** [comment]
Thanks so much, @RLHecht! Confirming I completed the post-publish steps as well and they're both now on the R&S landing page.

**Comment by RLHecht** [comment]
Thanks! Closing this ticket!
