### ISSUE TITLE
Confirm that all "Gulf War Illness" mentions on VA.gov use consistent and correct capitalization

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44017]
## Issue Description
Per our style guide, **Gulf War Illness** is capitalized. However, when we use the plural **Gulf War illnesses**, the I should not be capitalized. We need to make sure this is consistent across all of VA.gov's pages.

## Tasks
- [ ] Audit site for Gulf War Illness/Gulf War Illnesses/Gulf War illness/Gulf War illnesses
- [ ] Update any pages with incorrect capitalization
- [ ] Review changes
- [ ] Publish pages

## Acceptance Criteria
- [ ] Gulf War Illness/illnesses is capitalized correctly on live pages
