### ISSUE TITLE
Create new R&S article on "duty to assist"

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44010]
## Issue Description
Stakeholders Autumn Paschke and Lynn Thiem let us know that Veterans often have questions about "duty to assist" when talking about decision reviews. They recently provided new FAQs they wanted us to consider adding to our pages and there are 3 separate questions pertaining to "duty to assist." 

We discussed with them the idea of creating an R&S Q&A on this topic to address their concerns. The rest of the FAQs content is being handled in a separate ticket.

We need to create an R&S article with the information they provided and share with them before publishing. The content they provided will need to be reworked for plain language and to adhere to VA.gov's voice and style. 

FAQs provided: [https://app.zenhub.com/files/133843125/9502e2f2-02a7-4328-bb2f-f82a3bc88868/download](https://app.zenhub.com/files/133843125/9502e2f2-02a7-4328-bb2f-f82a3bc88868/download)

## Tasks
- [x] Draft new article (Katherine)
- [x] Review (Laura)
- [x] Give to Beth for OCTO-DE review in ticket #44011 (Katherine)

## Acceptance Criteria
- [x] Article is ready for OCTO-DE review

**Comment by laurwill** [comment]
Hey @katherine-fung ! You did **such** a great job with this — thank you for calling out your sources and questions so clearly! I already previewed most of my changes with you on zoom, but passing the doc over for you to review. Please let me know if you have questions about any of my edits.

Before we clean this up and post for Beth, could you also take a quick look at this [law firm resource](https://cck-law.com/blog/vas-duty-to-assist/) that covers Duty to Assist specifically for disability claims? Our page is broader, but we may want to see if they have any relevant explanations we'd want to include on our page. Let me know if you see anything in there you think we should try to cover! 
[Duty to assist.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9184384/Duty.to.assist.docx)

**Comment by katherine-fung** [comment]
@laurwill @RLHecht - I posted the draft in the [OCTO-DE review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44011) for Beth. We can close this ticket. Thanks!

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
