### ISSUE TITLE
[technical discovery] CST: In-line Decision Letter Content

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44019]
## Value Statement
**_As a_** veteran
**_I want to_** see decision letter content presented in-line within the CST itself
**_So that_** so that I can easily cut and paste information from that letter into other forms and applications.

---
## Acceptance Criteria
- [ ] _Body text of decision letter is clearly viewable to user within application_
- [ ] _Text appears along with the option to download pdf version of decision letter_
- [ ] _User has the ability to cut and paste body text_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- What are potential technical approaches we could take to extract text from a pdf and put it inline on a page? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
Findings:
* It is possible to extract the text content, but we won't be able to really emulate things like indents, paragraphs, or other syntax
* It's difficult to identify specific bits of text in the PDF, PDFs are more like graphics than text documents, every line is its own object as opposed to being tracked as sentences or paragraphs
* We don't have a PDF library of any sort in `vets-website` at the moment, and the only one that is really used in the javascript space would most likely make our bundle size quite a bit larger (would potentially impact load time for all of VA.gov)
* Decoding/extracting the text from a PDF is resource intensive, it's possible that it will be slow on mobile devices
