### ISSUE TITLE
OCTO-DE review, stakeholder feedback, and publishing of spousal inscription content changes 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44052]
## Issue Description
We made content changes to the [Veterans headstones, markers, and medallions](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) page in the "Spouse and other family members" accordion. We also added a new Q&A to the [Government headstones and markers FAQs](https://www.va.gov/resources/government-headstones-and-markers-faqs/) R&S article. This work was completed in ticket #44051. 

This ticket is for Beth's OCTO-DE review of this work, incorporating any stakeholder feedback and publishing these changes. 

## Tasks
- [x] OCTO-DE review (Beth)
- [x] Incorporate changes
- [x] Send to stakeholders for review (Randi/Laura)
- [x] Incorporate stakeholder feedback
- [x] Final copyedit with pre-publishing checklist (Megan)
- [x] Publish pages (Megan)
- [x] Notify stakeholders that changes are live (Randi)

## Acceptance Criteria
- [x] New content is live on VA.gov

**Comment by laurwill** [comment]
Hi @bethpotts , updates to these 2 pages are ready for you. As we discussed, we'll save the copyedit step for after your review.

**Veterans headstones:** http://preview-prod.vfs.va.gov/preview?nodeId=859  
- Added note about spousal inscriptions to the "spouse" accordion and linked to private burial page for full info
- Changed that accordion header from "spouses and other family members" to "spouses and dependent children" — we had "dependent children" on private burial page and SME confirmed this applies to children

**Burial in a private cemetery:** http://preview-prod.vfs.va.gov/preview?nodeId=2346
- Adjusted section about inscriptions for spouses and family members based on info from SME

And I haven't made any changes to the [Government headstones FAQ page](https://www.va.gov/resources/government-headstones-and-markers-faqs) yet, but we may want updates there as well. A couple questions first!
- At first I thought we could specify that this info only applies to Veterans headstones in government cemeteries. But does the section about inscriptions also apply to Veterans headstones in private cemeteries?
- Do we have content that describes inscriptions for spouses/children in government cemeteries? Like if a spouse or child is buried with the Veteran in their single family plot, do we describe the inscription options for that case?

**Comment by bethpottsVADEPO** [comment]
@laurwill @aliyahblackmore 
Veterans headstones: http://preview-prod.vfs.va.gov/preview?nodeId=859
"by request" didn't make sense to me with the framing of the rest of the sentence, so I rewrote that bit in the drupal file. You can go take a look. Let me know if you agree or have any concerns.

Burial in a private cemetery: http://preview-prod.vfs.va.gov/preview?nodeId=2346
Looks good!

[Government headstones FAQ page](https://www.va.gov/resources/government-headstones-and-markers-faqs)
Let's chat about these questions you have.

**Comment by bethpottsVADEPO** [comment]
@laurwill Thanks for the convo about the last couple of outstanding questions. Go ahead and have the stakeholder review what we did. Once you and he come to agreement, you can send the preview links to Lisa as an FYI. Thanks!

**Comment by laurwill** [comment]
Thanks Beth! I've sent these updates to Eric for review.

**Comment by laurwill** [comment]
Eric approved these updates on a call today. @megzehn , this is ready for final copyedit and publishing when you get back!

I'll email Lisa to let her know we worked with Eric on the changes and send her the preview links as an FYI.

**Comment by megzehn** [comment]
@laurwill and @RLHecht - FYI, I copyedited and published these 2 pages. Thanks!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
