### ISSUE TITLE
Content changes for spousal inscriptions on headstones, markers, and memorials

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44051]
## Issue Description
Stakeholder Lisa Hollenbeck asked us to make content changes around spousal inscriptions on headstones, markers, and memorials. These changes are on the [Veterans Headstones, Markers, and Medallions page](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) as well the R&S article [Government headstones and markers FAQ](https://www.va.gov/resources/government-headstones-and-markers-faqs/#can-i-choose-the-type-of-heads)

**On the headstones, markers, and medallions page**, in the "Spouses and other family members" accordion under eligibility, add the following information to the second paragraph:

“Spouses and family members buried in a private cemetery aren’t eligible for these memorial items.  However, spouses may be eligible to have their information (i.e., name, date of birth and date of death) inscribed on a headstone or marker if the Veteran died on or after October 1, 2019.”

**On the FAQs page,** add the following Q&A:

Can spousal information be inscribed on a Veteran’s headstone or marker when buried in a private cemetery?

Spousal information (i.e., name, date of birth, and date of death) and a term of endearment (if requested) can be inscribed on a Veteran’s headstone or marker if the Veteran died on or after October 1, 2019.  The spousal information will be inscribed on the back of an upright headstone and below the Veteran’s information on a flat marker. 

For Veterans who died prior to October 1, 2019 and upon request, VA will inscribe HUSBAND OF [name of non-Veteran spouse], WIFE OF [name of non-Veteran spouse], or SPOUSE OF [name of non-Veteran spouse] only below the Veteran’s information on an upright headstone and flat marker.  VA will not inscribe the spouse’s date of birth or death. 

We need to make plain language edits to these content changes and make sure they adhere to VA.gov's voice and style. When we add the new Q&A we also will need to add a link to it from the "More information" section on the headstones, markers, and medallions page. 

## Tasks
- [x] Add new content to benefit detail page (Aliyah)
- [x] Add new content to private burial page (Aliyah)
- [x] Review changes (Laura)
- [x] Post preview links for Beth to review in ticket #44052

## Acceptance Criteria
- [x] New spousal inscription information is ready for OCTO-DE review

**Comment by aliyahblackmore** [comment]
Update: passed an updated draft to Laura via slack

**Comment by laurwill** [comment]
Update: Beth suggested that instead of adding a single Q&A to the Government headstones page (which is specific to gov cemeteries, not private cemeteries), we adjust the section about inscriptions on the Burial in a private cemetery page to include this information and then link there from the brief content on the Headstones page.

We had a few questions to clarify first, so I sent these to Eric at NCA: 
- Our [Burial in a private cemetery page](https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/) covers inscriptions in private cemeteries for both spouses and dependent children—but the content you sent only mentions spouses. Does this benefit only apply to spouses now, or did you want to prioritize the information for spouses?
- That page also says that in addition to the requirement that the Veteran died after 2019, the spouse must be eligible for burial in a VA national cemetery to qualify for the inscription benefit. Does that requirement still apply?
- We noticed that VA.gov uses both “inscribe” and “engrave” in this content, and we’d like to pick one for consistency. Does NCA have a preference?

**Comment by laurwill** [comment]
Answers from Eric:
- Use "inscribe" throughout
- Benefit applies to "spouse or eligible dependent child"
- Eligibility for burial in a VA national cemetery does apply, for both spouses and children

@aliyahblackmore could you suggest updates to the H3 on the private burials page to include the new content? And please update all instances of "engrave" to "inscribe" on that page as well. Let me know if you have questions!

**Comment by aliyahblackmore** [comment]
Hi @laurwill - thanks for these answers to our questions! Attached is the drafted content included changes based on our call with Beth and the responses from Eric.  I've included a few comments and any last questions for you in the doc.
[Spousal inscriptions.AB.7.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9155118/Spousal.inscriptions.AB.7.20.docx)

**Comment by laurwill** [comment]
Thanks Aliyah! As we chatted, I shortened the content on the main "Veterans headstones" page and did some futzing on the private burials page to move some of the info into accordions. Beth said we could skip the copyedit and post for her review, so I'll put the Drupal files in her ticket!

**Comment by RLHecht** [comment]
Work is complete in this ticket. Closing!
