### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 7/18

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44053]
## Issue Description
We need to swap out the videos in the stories section of the CLP to these 2 Veterans:

**Patricia Victor:** https://www.youtube.com/watch?v=Dcnx5fOY268
**John McAllister:** https://www.youtube.com/watch?v=X2c7NMAWgHM

**Drupal Page:** Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Documentation for how to swap videos:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [x] Replace text and videos
- [x] Review and publish (Megan)
- [x] Create new ticket for next update (Randi)

## Acceptance Criteria
- [x] New videos and text are live on the page

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! 
http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
I published this page since Megan is out on vacation and created a new ticket. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
