### ISSUE TITLE
FE | PROFILE | Personal info Revisions | UAT |  Android Bug

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44079]
## Background

During UAT the FAQs and hint text appeared much larger than they should have for a participant using a specific Android mobile device.

## Tasks
- [x] Determine cause and fix for bug 

## Acceptance Criteria
- [x] Deploy fix to Staging behind feature flag
- [x] Notify Product Manager and Designer that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from the review & re-test & have re-validated
- [x] Deploy changes to Production and re-test

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
This display issue appears to be resolved. I checked on several different android browsers via browserstack, and could not replicate the issue. 

I also asked @mdewey to double check on his device (Samsung Galaxy Note 8) and he verified that he is no longer seeing the issue either.

Screenshot of issue not occuring:
![Screen Shot 2022-08-01 at 1.06.16 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/48b75737-644b-4bf7-9418-361ff3a8e77f)

**Comment by SKasimow** [comment]
Thanks...I'll close this out.
