### ISSUE TITLE
INTL - Sitewide Homepage Content copy

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#44072]
## Issue Description
Duplicate Content Dashboard and separate data source for Sitewide Homepage team. Cannot add to Standardized Content KPIs due to data size and existing latency issues (to be addressed in future tech debt ticket, likely once Data Engineer role filled). 

See #41503 for VFS-facing ticket.

---
## Tasks
**Data** @chloedotbrown 
- [x] Homepage data passes BigQuery QA
- [x] New BQ connected and backfilled in BQ

**Dashboard** @chloedotbrown 
- [x] Duplicate dashboard created (all new cards)
- [x] Card datasources individually changed
- [x] Beast modes replicated if necessary
- [ ] Filters/card configurations checked

**QA** @pavanhothi & @jonathan-epstein13 
- [ ] Design QA
- [x] Data QA

**Delivery** @chloedotbrown 
- [ ] Dashboard shared with "Default" group
- [ ] PM informed work complete on original ticket (#41503)

## Acceptance Criteria
- [ ] Duplicate version of Content Dashboard is created, QAed, and ready for use by Sitewide Homepage team.

**Comment by chloedotbrown** [comment]
## Data QA - in progress
Created a `TEST_last_week_homepage` view in the analytics_testing folder in BigQuery. This mirrors the logic in the current Domo Content Engagement connector query, but instead of joining with the content table, data is filtered to only pull in the homepage. Fields from the content table, such as `product` and `page_name`, are hard-coded.

_Reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the count of distinct hit IDs (combination of session and hit number).
Total rows | Unique IDs
 -- | -- 
243,557 | 243,557

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  count(*) as total_rows,
  count(distinct concat(session, hit_number)) as total_uuid
from`vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`;
```
</details>

### Nulls
🌀 **Edits needed.** Consistent with Content data patterns, but revealed issues in underlying view that will need to be addressed for both Content and Homepage dashboards. Include backfill of Content dataset in scope of this work.

Column | Null rate (content) | Null rate (homepage) | Explanation
 -- | -- | -- | -- 
`link_label` | 20% | 60% | ❗️Higher rate of scroll depth events, which have no `link_label` associated (used for engagement events only) 
`time_on_page` | 100% | 100% | ❗️Update on 6/9 to `page_title` coincides with this field being 100% null. Wrapping tech debt into this ticket.`link_label`. Found improvements for both views, consider for tech debt.
`mobile_brand` | 50% | 55% | Corresponds with `device_category` = desktop rates for each (values only available for mobile, tablet).
`mobile_model` | 50% | 55% | _(see above)_
`search_keyword` | 100% | 100% | Field not used, consider removing.
`page_name` | 69% | _null_ | Field hard-coded, no nulls expected.
`time_to_event` | 30% | 38% | Field not used in any cards or beast modes.



<details> 
  <summary>Expand for test code</summary>

```sql
with content_nulls as (
  select 
    col_name, 
    count(1) nulls_content,
    'a' as join_key
  from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_content` t,
  unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
  group by col_name 
),

content_all as (
  select 
    'a' join_key,
    count(*) as total_content
  from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_content`
),

pct_content as(
  select
    col_name,
    round((nulls_content/total_content), 2) as pct_content
  from content_nulls
  left join content_all using (join_key)
),

home_nulls as (
  select
    col_name, 
    count(1) nulls_home,
    'a' as join_key
  from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage` t,
  unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
  group by col_name 
),

home_all as (
  select 
    'a' join_key,
    count(*) as total_home
  from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
),

pct_home as(
  select
    col_name,
    round((nulls_home/total_home), 2) as pct_home
  from home_nulls
  left join home_all using (join_key)
)

select *
from pct_content
full join pct_home
  using (col_name)
```
</details>

### Completeness
✅ **Passed!** Checked row distributions for main filters to be used in new dashboard. 

<details> 
  <summary>Expand for test code</summary>

```sql
/**************************************
   NOTE: Highlight and run separately
**************************************/

-- Completeness test - Date
select 
  date,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
group by 1

-- Completeness test - Device
select 
  device_category,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
group by 1

-- Completeness test - Browser
select 
  browser,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
group by 1
order by 2 desc

-- Completeness test - Page title (multiple for language variations)
select 
  page_title,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
group by 1

-- Completeness test - Product (should be 1)
select 
  product,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_last_week_homepage`
group by 1

```
</details>

## Accuracy tests
Still under construction as of end of day July 8th. Will continue to update comment next week.

_Reference: [QA for standardized dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents); [WIP Content QA spreadsheet](https://docs.google.com/spreadsheets/d/10ntfDxR2OKxPJ0FI6gCzoyHu1XfbW1-uKKSH1F8ZfOc/edit#gid=0)_


### Highlights

Chart Title | Pass/Fail
-- | --
Usage trends |  
Unique users |  
Unique pageviews |  
Total clicks by device |  

### Task completion

Chart Title | Pass/Fail
-- | --
User interaction rate |  
Total interaction clicks |  
Avg. clicks per user |  
Interactions with most clicks |  

### Ease of use

Chart Title | Pass/Fail
-- | --
Avg. scroll depth distribution |  
Avg. minutes on page |  
Avg. scroll depth |  

### Findability

Chart Title | Pass/Fail
-- | --
Top pages previously viewed |  
Devices used to access the page |  
Top browsers used to access the page |

**Comment by chloedotbrown** [comment]
@michelle-dooley 

### Current completed work 
**Data**: Even after separating homepage data from the existing Content data source, the event-level data was still too large for Domo cards to process. Therefore, I've created 3 datasets of based on the `vw_content_engagement` view in BQ that transform the data enough to make it manageable while still allowing enough flexibility for accurate counts when filtering/grouping by dates. New datasets include:

- [BQ - Homepage Engagement - Session Summaries](https://va-gov.domo.com/datasources/ede13a36-4e8d-4456-a8ba-f9e30c2eb465/details/overview) - _supports 10 cards_
- [BQ - Homepage Engagement - Events by Day](https://va-gov.domo.com/datasources/df01bf0e-98c6-4604-8457-84c95be8de8f/details/overview) - _supports 3 cards_
- [BQ - Homepage Engagement - Previous Pageviews](https://va-gov.domo.com/datasources/90cd696d-84fa-40a8-b164-822d5a732d09/details/overview) - _supports 1 card_

**Dashboard:** WIP version of [Site-wide Homepage Engagement dashboard](https://va-gov.domo.com/page/80919003) is created, cards are connected to new data, and access has been granted to everyone on the Analytics team.

### Next steps
**Data**: During QA, I realized that the underlying `vw_content_engagement` page does not capture a significant portion of links on the homepage, such as "Zone One" or "Main Button" clicks. I suspect this is because these configurations primarily exist only on the homepage and therefore weren't included when Jason created the Content views originally. However, because I'm not 100% certain that making changes here won't impact all our other content products, I'm going to create a `vw_homepage_engagement` and '..._last_week` views in BQ and reconnect the 3 Domo datasources to them instead. 

In addition, I've [verified](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41503#issuecomment-1201895445) with Michelle M that, not only is it important to include this data, but it would really useful to them to be able to filter by location on page. Since this has taken so long to create and they'll now need their own view anyway, I've offered a different `engagement_type` taxonomy for their dashboard as a new feature. I don't think this will add much time on my end, but it will make the dashboard much more useful to the Homepage team. 

**Dashboard**: Once data is backfilled on the new view, I'll do the Data QA, since I've been working so closely with it and can integrate any changes needed quickly. However, it would great to give Design QA and any fixes needed to Jonathan or Pavan.

**Comment by chloedotbrown** [comment]
## Data QA checklist

_**Dates checked:** July 31 - August 6, 2022_

### Highlights
| Card title | Data assets | Pass / Fail |
|:-----------|:------------|:-----------:|
| Total sessions | Audience / Overview / Segment where page = homepage| Pass ✅ |
| Sessions w/ interactions | Queried daily GA tables in BQ | Pass ✅ |
| New vs. returning sessions | Queried daily GA tables in BQ | Pass ✅ |
| Sessions by device | Audience / Mobile / Overview / Segment where page = homepage | Pass ✅ |
| Total pageviews | Behavior / Site / All Pages | |

### Task completion
| Card title | Data assets | Pass / Fail |
|:-----------|:------------|:-----------:|
| Interaction rate | Queried daily GA tables in BQ | Pass ✅ |
| Total interactions by type | Depended on category - Queried daily GA tables in BQ or used Behavior / Events / Top events with page + event label filters | Pass ✅ |
| Total interactions (all) | Queried daily GA tables in BQ |Pass ✅ |
| Avg. interactions | Queried daily GA tables in BQ | Pass ✅|
| Top interactions | Custom report to check totals and event action order | Pass ✅|


### Ease of use
| Card title | Data assets | Pass / Fail |
|:-----------|:------------|:-----------:|
| Scroll depth distribution | Custom report to check totals | Pass ✅ |
| Avg. min on page | Queried homepage view in BQ | Pass ✅ |
| Avg. scroll depth | Queried homepage view in BQ |Pass ✅  |

### Findability
| Card title | Data assets | Pass / Fail |
|:-----------|:------------|:-----------:|
| Previous page | Queried homepage view in BQ |Pass ✅ |
| Top browsers used | Audience / Technology / Browser / Segment where page = homepage |Pass ✅ |

**Comment by chloedotbrown** [comment]
@pavanhothi - the [Site-wide Homepage Engagement dashboard](https://va-gov.domo.com/page/80919003?userId=1917693988) is ready for design QA. You can find instructions, markdown templates, and a spreadsheet version of the usability checklist [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard).

**This dashboard should have a more rigorous design QA than most**, given the risks of making a copy of an existing dashboard. In particular, please give extra attention to the following:

- **_Hover text_** - Make sure it matches metrics as defined in card titles, dashboard annotations, etc. rather than the original versions on the content dashboard, which may not be accurate.
- **_Drill path charts_** - I tried to double-check all of these, but it is still possible I've missed some and there are drill path charts connected to the original content data sources, instead of the new homepage ones. If this is the case, hover text will likely need to be updated as well.
- **_Implement changes_** - Usually we send things caught in QA back to the dashboard designer. However, for efficiency's sake, once you've completed and posted the 1st round of design QA, please go ahead and make the necessary changes yourself before re-checking. 

I'll start a thread in our team's Slack channel for any questions that may come up as you go!

**Comment by michelle-dooley** [comment]
@chloedotbrown and @pavanhothi - I have completed the 1st round of design QA, see below.  For the most part everything looked great!! I made some text edits where I could but there were a couple things I'm not sure how to do.  @pavanhothi - could you please take a look at the ones I marked failed and correct please.  Could you also please double check the drill paths, I think they are good but since Chloe called them out I think another set of eyes would be good.
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Test | Expected Behavior | Actual Behavior | Pass/Fail
-- | -- | -- | --
Dashboard title | Text fully readable, without errors |   | ✅
Date filter | Every chart gets filtered for date and group by settings are changed | The following cards do not update when the date selection is for any time perriod in current year:- Total pageviews- Total interactions- Avg interactions- Avg minutes on page- Avg scroll depth | ❌
Section titles | Every section title & subtitle are spelled correctly |   | ✅
Section resources | Links to How-to Guide + Data Dictionary (if available) |   | ✅
Chart titles | Every chart title is fully readable, without errors, relevant to chart |   | ✅
Chart descriptions | All chart descriptions are disabled, so nothing appears when hovering over title |   | ✅
Hover text | All hover text "makes sense" and is spelled correctly |   | ✅
Annotations | Every annotation "makes sense," is free of errors, and visible within text box |   | ✅
Filter cards | Filter cards are easy to read and use |   | ✅
Text box formatting | Every annotation and section title box shows all text, does not generate scroll bar |   | ✅
Card interactions – filters | Clicking data point does not filter other cards | Page filters at top:  When filtering on "device_category" it notes only one card affected and that appears to be true.  However the"browser" filter affects all cards - unsure if that is by design or not?  Should I test all filters in the drop down?  Wasn't 100% clear on this one. | ❌
Card interactions – card detail | Chart title opens card in new tab | The following cards open in current tab, not new tab- "Total interaction by type"- "Top interactions (drill in place)" | ❌
Card drillpaths | Card detail view filters to correct drillpath _(if using)_ |   | ✅
Display settings – date units | Date grouping ("by week/month") appears under each title |   | ✅
Display settings – multi-value gauges | Directionality of colors in period-over-period comparison makes sense |   | ✅
Display settings – summary numbers | All non-multivalue gauge charts without a date axis show date range in summary number |   | ✅
Related cards | In card detail view, all related card previews have been deleted |   | ✅
Appendix | No charts or notecards appear in appendix below dashboard |   | ✅


</body>
</html>

**Comment by pavanhothi** [comment]
@michelle-dooley thank you! I will go in and and make any necessary corrections. And I'll do another check on drill paths etc.

**Comment by pavanhothi** [comment]
@michelle-dooley @chloedotbrown I have completed design QA from my end. Some notes based on QA above:

- Date filter: I checked the filter exception and card interaction settings for the cards mentioned where they weren't filtering for date periods in current year; I found that the cards are being filtered, however for certain date periods selected the card data remains unchanged. For example, when selecting date period "This Month" the card data changes on all cards mentioned by Michelle in her QA, however when selecting "this Quarter" or "This Year" card data for these cards remains the same as when there is no date filter. Unclear if this is accurate or if the cards themselves need updating. I checked the Content dashboard for reference, and the case is the same over there for the same mentioned cards. 
- Card interactions- filters: I checked all cards filter settings and confirmed that clicking data points on any card does not filter any other cards except for the one which was clicked on, which is how it should be. Also tested the device category and browser filters at the top, and they both are filtering all cards as expected and should be.
- Card interactions- card detail: I corrected the "Total interaction by type" card so that it opens in a new tab now. For the "Top interactions (drill in place)" card I found that since it is a drill in place card, it's interaction settings are set to drill in place, and if I change the settings so that the card opens in a new tab, it appears to get rid of that drill in place interaction on the dashboard. I checked the content dashboard for reference and found that the drill in place card on there has the same interaction settings as this card and also does not open up in a new tab. 
- Drillpaths: I did a double check on the drillpaths and they are working and filtering correctly as we would expect them to. 

This looks great Chloe!

**Comment by michelle-dooley** [comment]
Thanks @pavanhothi 
@chloedotbrown - can you look into the following remaining items....

- Date filters:  the values for 'Total Pageviews', 'Total interactions', 'Avg interactions' and 'Avg minutes' do not change based on 'this year', 'this quarter' or any current year data range I use in the 'between' function.   
- Card interactions - card details:  'Top interactions (drill in place)' card does not open a new tab.  Not sure if that is by design as Pavan notes above or if that is something that needs to be fixed?  All others are good.
- Also noticed the 'Session trends' card is only updated through 7/31

**Comment by chloedotbrown** [comment]
Thanks @michelle-dooley and @pavanhothi ! Here are the final checks Michelle flagged:

- **Multi-value gauges responding to date filters** - These worked fine for me! They show the most recent `date part` per `date range` selected, so changing the range to any of the "This X" options wouldn't change the values - it'll be the most recent week for all of them. To test though, I used "Previous X" date filters and played around with the "Graph by" settings, which did change the values. I think we're good!
- **Card interactions** - Oops I meant to mention this was the one exception in my QA notes, but I forgot! Yes, this one is meant to drill in place rather than open in a new tab. However, if users click the title, they'll still be able to get to the card detail page if they want.
- **Session trends** - Ahh I think we've run into this issue before! When you group by week, the date shown on line graphs will be the 1st day of that week. In this case, 7/31 is the Sunday of the most recent week ending 8/6. So data is updating correctly, but it is confusing! I added a date range display in the summary number of this one so that readers don't have the same issue.

With that, I think we should be good for Design QA! Michelle, feel free to take a final look and let me know if this is good to close out and send to Michelle M?

**Comment by michelle-dooley** [comment]
Awesome!!  @chloedotbrown I thought that I might of not be been interpreting the multi-gauges correctly, thanks for clarifying!!  Sounds like we are good to sign off on this one, YAY!!  Please go ahead and let "other Michelle" :) know.

**Comment by chloedotbrown** [comment]
Perfect! Closing out this internal ticket in the meantime.
