### ISSUE TITLE
Add node_module Folder  Deletion Script  to Yarn Workspaces POC

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#44078]
Add node_module Folder  Deletion Script  to Yarn Workspaces POC

## Tasks

- [x] Script gives warning before delete process occurs
- [x] Only deletes directories named 'node_modules'
- [x] Only deletes target in the root directory of the  script, or under.
- [x] Documentation

**Comment by rmessina1010** [comment]
Completed.
