### ISSUE TITLE
Profile | Sprint 79 (July 27 - Aug 9)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44080]
## PTO/OOO/Unavailable

- **Christina**: July 28-29
- **Sharon**:  1/2 day July 29
- **Tom**: Aug 8
- **Samara**: Aug 1 - 5
- **Adam**: 
- **Liz**:  7/27-7/29
- **Taylor**: Aug 2 -3 

## Sprint Priorities
- Continue documentation work
- Internal UAT for Military Info
- BAI recommendations
- New forms library

### FE - Adam
- [x] #44079 Android bug (2 pts)

### Design - Christina
- [x] #43713 Sketch update (1 pt)

### PM - Sharon
- [x] #43609  internal UAT with  veterans (5 pts)

### BE - Tom
- [x] #42491 Set up feature flag for 25% (1 pt)
- [x] #45206 UAT Bug

### PM - Sharon
- [x] #44739 Release plan (2 pts)

### BE - Tom
- [x] #44712 Privacy + Security review (2 pts)

### Design - Christina
- [x] #43384 Research Findings
- [x] #45001 Content updates
- [x] #45002 UI updates

### FE - Adam
- [x] #43727 Phone number field (3 pts)

### FE - Taylor
- [ ] #31410 Update alerts when in editing and goes to another section (5 pts)
- [x] #31408 Update alerts when user hits "cxl" while editing (2pts)
- [ ] #31411 Update alert for disconnect app (3 pts)

### BE - Tom
- [x] #44885 Contact documentation (3 pts)
- [x] #44252 Tech Discovery/Sidekiq (3 pts)
- [x] #44928 Phone # extension bug (2 pts)

### Tom & Adam
- [x] #44771 **Discovery** Improve 400 range error responses (1 pt)
- [x] #44816 **Research** Japanese characters/bug (2 points)

**Comment by SKasimow** [comment]
@Samara-Strauss - here's an up-to-date version. Please lmk if you have any feedback. Thanks!

**Comment by Samara-Strauss** [comment]
Is Adam continuing the forms system work?

**Comment by adamwhitlock1** [comment]
@Samara-Strauss yep im still working on the forms system ticket for home phone field.

Here is an update on where I have made progress and what is remaining on that ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43727#issuecomment-1196793695

**Comment by Samara-Strauss** [comment]
Ah, sorry! I missed the forms work the first time I looked through the epic. I see it now. Sorry! Everything looks great.
