### ISSUE TITLE
Update Tools & Service page to reflect new content

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44088]
## Issue Description
Update Tools & Service page to reflect new content

---
## Tasks
- [x] Update Tools & Services page to reflect new content
- [x] Update Overview Tools & Services section to match
- [x] Verify operation of links

## Acceptance Criteria
- [x] Tools & Service page reflects new content
- [x] Overview pages's Tools & Service page reflects new content
- [x] Links are accurate and operational
