### ISSUE TITLE
Design | Profile | Personal Info Revisions | Update FAQ copy

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44084]
## Background
- Participants in our Personal information UAT mentioned a few items that they had expected or hoped to find in the Gender information dropdown. Determine if any additional information is needed in Gender identity FAQ. 

## Tasks
- [x] Review UAT feedback
- [x] Determine if any additional information is needed in Gender identity FAQ
- [ ] Add any new additions to content
- [ ] Review with Content

## Acceptance Criteria
- [x] Determine if any additional information is needed in Gender identity FAQ
- [ ] Add any new additions to content
- [ ] Review with Content
- [ ] Update mockups 
- [ ] Share with PM and PO

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
**Update:** Checking with Danielle on the possibility of a few small items of information to the Gender identity dropdown (along with the eventual link to the Resources & Support article) to possibly address the following participant feedback:

- 2/7 participants were concerned with VA visibility and would like more information on who can view this information.
- 3/7 participants wondered why the NCM would need to see gender identity, but did not have a negative view on this.
- 1 participant thought more information should be included for how to update their gender identity with their health care team and to define the “healthcare team.”

@SKasimow I've reached out to Danielle and hope to discuss this soon, but there's a good chance it will carry over past this sprint since it's not super pressing and will need to work into Danielle's timeline.

**Comment by SKasimow** [comment]
@cgednalske - thanks for the update. if it is still open at end of the sprint I'll carry it over to the next sprint

**Comment by cgednalske** [comment]
I spoke with Danielle about this and she agrees it would be helpful to add in a small amount of information clarifying a) why the National Cemetery Administration would have access to this and b) what exactly VA-wide records means. We have language for the first item, but she'll need more background on the second.

@Samara-Strauss do you happen to know what all is included when we say VA-wide records? Or if not, where we might find out? Danielle is not positive and would like to know more details before deciding how to define/clarify this.

**Comment by Samara-Strauss** [comment]
To re-iterate what we spoke about in standup:

Preferred name and gender identity information is ultimately stored in MPI, which can be accessed by VBA and NCA *if they choose*. Right now, I believe only VHA is accessing this information, but I can't guarantee that this will be the case forever. Hence, we included the copy on this being accessible VA-wide because it is not stored exclusively in the VA health record, and could be accessible by other business lines later on.

**Comment by cgednalske** [comment]
Exactly the info we needed 👍  Thanks so much @Samara-Strauss!

**Comment by cgednalske** [comment]
Hi @Samara-Strauss -- one follow-up question from Danielle: 
> Do staff members need to have a specific level of access to be able to access MPI data? That might be a good detail to work in to reassure folks that not any staff member from across VA can access their records.

**Comment by Samara-Strauss** [comment]
I don't think that anyone can access MPI. As far as I know, people can only access this data if they are accessing it from a system that is integrated with MPI. Example: I can't access MPI, neither can Danielle. So no, any old staff member can't access all veteran data. Things are definitely more secure than that.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- Below is Danielle's content suggestion based on what we know about VA-wide records access. She recommends removing the mention of VBA and NCA and focusing on the "secure access" element.

How do we feel about this approach?

**Suggested version:**

> [FAQ dropdown]
> What to know before you decide to share your gender identity:
> 
> [Expanded content]
> Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff who have secure access to the VA-wide records system can read this information.
> 
> We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.


**Previous version:**

> [FAQ dropdown]
> What to know before you decide to share your gender identity:
> 
> [Expanded content]
> Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information.
> 
> We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.

**Comment by Samara-Strauss** [comment]
>  But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff who have secure access to the VA-wide records system can read this information.

While I don't think it intends to, this sounds like any VA staff member can go into MPI and look at this data, and that's not true. Can we soften the language to something like the following?: 

> But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff outside of the health care system may be able to view this information.

**Comment by SKasimow** [comment]
I like this softer language too.

**Comment by cgednalske** [comment]
👍 Checking in with Danielle on that. I like the softer version as well. It works nicely to mention "outside of the health care system" seeing as the health care aspect is the primary focus of the background info we're providing.

**Comment by Samara-Strauss** [comment]
Looks great to me! Ship it! :D

**Comment by SKasimow** [comment]
@cgednalske let me know whenever the mocks are ready and I'll create a FE ticket for the change :)

**Comment by cgednalske** [comment]
@SKasimow the mockups have been updated! [Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/eKYxzDm) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/GmRgk3O)

**Comment by SKasimow** [comment]
@cgednalske - you rock! thanks! I'll close this one out and add mocks to the FE ticket.
