### ISSUE TITLE
BE? | Profile | Personal Info Revisions | UAT | Selection Already Made Bug

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44085]
## Background

During UAT, a gender identity selection was already made for 2 participants who had not yet visited the page. Although the selection can be changed the users will not be able to fully remove information once entered (go back to blank slate).

## Tasks
- [ ] Determine how Gender Identity fields were already selected for some users
- [ ] Detail what would be required to prevent this from occurring 

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Closing....health care systems and/or others may have gender info and pre-populate. WAD.
