### ISSUE TITLE
CST: file exceeds 5MB validation rule

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44093]
## Value Statement
**_As a_** veteran, if any single file (whether in a payload or submitted individually) I attempt to upload exceeds 5MB
**_I want to_** receive an error notification telling me that I can't upload the file
**_So that_** I don't think I successfully submitted it only to find out later the file was rejected.

---
## Background Context
-  See linked epic

## Acceptance Criteria
- [ ] User sees error message telling them why their file or file payload was rejected
- [ ] File is not submitted.

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
