### ISSUE TITLE
Implement Redux

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4409]
## User Story:
As a front end developer, I need to implement Redux into our app, so that our app’s data is accessible.

## Tasks

- [x] Meet with other devs to understand VA’s standard on Redux -3 hrs
- [x] Create and write code for Redux actions, api, types and reducer files - 3 hrs
- [ ] Test that we are able to use Redux - 1hr

## Acceptance Criteria:
- [ ] I should be able to see our application’s state and actions/reducers on Redux DevTools
- [ ] New code is in the [GH branch] (https://github.com/department-of-veterans-affairs/vets-website/tree/3614-discovery-mock-up-of-medical-device-tool)

## Next Steps
- #3830 and #3832
