### ISSUE TITLE
[Spike] CST: pdf locked with password type "owner" validation rule

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44094]
## Value Statement
**_As a_** veteran, if I attempt to upload a pdf locked with a password of type "owner"
**_I want to_** be given an error message that says I cannot upload that file
**_So that_** I don't think I successfully submitted it only to find out later the file was rejected.

---
## Background Context
-  See linked epic

There is evidence of pdfs making it through FE validation even though there's a pw type "owner".

## Acceptance Criteria
- [ ] User sees error message telling them why their file was rejected
- [ ] File is not submitted.

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- What are we doing currently to unlock user passwords? (Hypothesis: If a user pw is not present, we don't bother tying to unlock it)
- What opportunities might there be to implement a similar strategy for owner passwords?
- Should we just be automatically trying to unlock pdfs trying blank passwords? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
So I was looking at COE and noticed that when we upload files via the `/v0/claim_attachments` endpoint, they send back an error when there is a user password on the file

![Screen Shot 2022-07-13 at 11 50 59 AM](https://user-images.githubusercontent.com/13838621/178826959-7ad3dcb3-e347-4e7b-99b7-f2680a82140f.png)

This might give us an avenue to start exploring

**Comment by jacobworrell** [comment]
After talking to @jerekshoe diagnosing problems and solutions would be easier with an example of an owner pw protected pdf that went through. I'm going to send this over to him via va.gov email.

**Comment by jerekshoe** [comment]
Notes from discussion with @jacobworrell

## Findings
1) The issue that originated this ticket was with the NOD, not with CST, so I looked into the frontend and backend code for the app and from what I can tell it is:
   * Not checking for encryption on the frontend
   * Not prompting for a password in the frontend UI when an encrypted PDF is selected
   * Not attempting to decrypt PDFs that are encrypted on the backend
   * Sending encrypted PDFs to the downstream service (I'm pretty sure this is Lighthouse?)
2) CST doesn't have these issues because we are doing all 3 of the previously mentioned items
3) We are however not checking for the `Encrypt` flag properly (this is a sitewide issue, not specific to CST):
    * We are checking the first 256 bytes of each PDF for `Encrypt`, but `Encrypt` can show up at the end of the file; it doesn't have to be at the beginning
4) The pdf utility that we use in `vets-api` (`pdftk`) cannot handle AES256 encryption, so even if the correct password is supplied, we aren't able to decrypt it
5) If for any reason `vets-api` is not able to decrypt the PDF, the user is presented with an error alert prompting them to remove the encryption and re-upload their PDF

## Outcomes
1) NOD code needs to be updated to address the issues noted above
2) Might need to ask Lighthouse if they are checking to see if PDFs sent from `vets-api` are encrypted
3) `vets-website` code that checks PDF files for encryption needs to be updated to account for the fact that the `Encrypt` flag is not guaranteed to occur within the first 256 bytes of the PDF
