### ISSUE TITLE
CST: page dimension larger than 21 X 21 validation rule

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44090]
## Value Statement
**_As a_** veteran, if a pdf I upload has page dimension larger than 21" x 21"
**_I want to_** receive an error notification telling me that I can't upload the file
**_So that_** I don't think I successfully submitted it only to find out later the file was rejected.

---
## Background Context
-  See linked epic

Recommended Next Steps
- NOD fixes the validation issue on their end and we copy their approach

## Acceptance Criteria
- [ ] User sees error message telling them why their file was rejected.
- [ ] File is not submitted.

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- What implementation approaches might allow us to implement this in one Sprint? 
After some research, we recommend a BE validation approach because a feasible solution requires the file to be unencrypted. Currently, we unlock the PDF on the backend, run existing validation and then we could potentially validate page dimension criteria on the BE. 

- We know for NOD that page dimensions need to be less than 21" x 21", but we don't know how this applies to CST. We should discuss with Lighthouse what validation rules are needed for CST uploads

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
One possible solution path involves lighthouse research the possibility of auto-shrinking pages that are too large, they are researching this.

That being said, we could go ahead and add a Backend check and reject PDFs when one or more pages exceeds 21x21.  IF Lighthouse figures out a way to autoshirk, we could then remove and or modify(i mean at some point, if the page is really big, autoshrink might not work either)

**Comment by jacobworrell** [comment]
@Mottie we think it'd be best if NOD determined the solutions approach for NOD because that was the application that had the validation issue to begin with. We'd like to copy the approach you use on CST. 

cc @saderagsdale

**Comment by michelpmcdonald** [comment]
Some possible solutions:
https://stackoverflow.com/questions/9461500/how-to-determine-dimension-of-pdf-pages-with-ruby(we already have this gem in the project)
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_info.rb#L55 def page_size_inches (this is vets-api existing code we could use)

**Comment by pmclaren19** [comment]
We need to re-evaluate if this work still needs to be done now that we are moving to lighthouse. @jerekshoe please re-evaluate when you have a chance.
