### ISSUE TITLE
[Research] Create Research Plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44107]
## Description
- Create the research plan of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
- List out items...

## Tasks

- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria

- [x] Review research plan with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan to GitHub folder

**Comment by benbrasso-agile6** [comment]
https://docs.google.com/document/d/1j3IK984cZxChkzz54ju4vzeiJLmOLYC36ZPl956y1B4/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test/research-plan.md

**Comment by loripusey** [comment]
RP & CG look good!
