### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44108]
## Description
- Create the conversation guide of who we plan to test with, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- This research study should cover:
- List out items...

## Tasks

- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria

- [x] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize and conversation guide to GitHub folder

**Comment by benbrasso-agile6** [comment]
Making updates from Clayton (research ops team)
