### ISSUE TITLE
VA Performance Dashboard - Frontend work

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#44102]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a frontend engineer, I need accomplish these tasks  so I can launch the new VA  Performance Dashboard.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect users to view VA.gov usage and satisfaction data_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 
- [] I can see a front-end web application
- [] The design matches the older performance dashboard
- [] When I click the tabs at the top right of the page, the charts reflect the data from the past 12 months
- [] Each tab toggles to the corresponding chart data
- [] In the *services* section, each service displays total users for past 30 days
- [] In the *services* section, each service displays user satisfaction score for past 30 days
- [] In the *services* section, each service displays the amount of relevant transactions for past 30 days

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by clantosswett** [comment]
@ATMiddleton @aubreyarcangel this never really tracked any work. I would propose closing this.
