### ISSUE TITLE
[Research] Create Research Study Report

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44110]
## How to configure this issue
- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Labeled with HCE-Checkin, ux, research
- [ ] Prepend [Research] to the beginning of the ticket title
- [ ] Fill in User Stories
- [ ] Fill in Description
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

## User Story
- As a product team, we want to document and share the findings from [research study name].

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan and Conversation Guide]()
- Synthesis for this report completed in [ticket]().

## Description
A research report detailing findings and design recommendations from [research study name].

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [ ] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [ ] Conduct the [inclusive design analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/risk-documentation.md)

## Acceptance Criteria
- [ ] Post research report to GitHub as presentation and markup document
- [ ] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [ ] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with
    - [ ] Stakeholders (talk to Patrick about when to do this)
    - [ ] Team (either via Slack or Zoom meeting)
    - [ ] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by benbrasso-agile6** [comment]
Few more slides to add - https://docs.google.com/presentation/d/1Tm_QGLIMIYXbgseGGxSiYRN7oMj1jZHyq-ytAaM692E/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
Presentation 

https://docs.google.com/presentation/d/1Tm_QGLIMIYXbgseGGxSiYRN7oMj1jZHyq-ytAaM692E/edit?usp=sharing


Need to create the markdown in git and update the research repo ticket
