### ISSUE TITLE
[FE][bug] - Reloading app routes to VA 404

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#44113]
## Description
On stage and prod, if a page is reloaded the user gets routed to a generic VA 404 page. There could be something that we need to do with the platform level router, to identify all of our potential URLs. We may also want to pull in Mark's POC code for full auth, to allow the app to continue where it left off in the case of a reload.

## User Workflow
- Given I have logged in and started CI or PCI
- When I reload the page
- Then I expect to be on the same page and step of the process without needing to re-log-in

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Router works with all CIE pages
- [ ] Session continues if already in progress
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Updates on this issue: I started testing locally, but we have passing tests related to the issue and I couldn't reproduce. After testing on staging, I realized that the 404 issue occurs for pre-check-in, but not check-in. After more digging, I think the problem is that we're missing revproxy config specific to pre-check-in. I created a PR in the devops repo to resolve this:

https://github.com/department-of-veterans-affairs/devops/pull/11604

I also added an issue to request additions to the platform docs around this:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/44530


This doesn't yet resolve the full scope of the issue, because when reloading e.g. the appointment list page on staging, you get kicked back to the demographics confirmation page. Continuing to investigate/work on that use case.

**Comment by acrollet** [comment]
After further investigation, I've determined that we kick back to the confirmation pages because the answers are stored in ephemeral state that is not preserved on page refresh. Because this could potentially take a fairly significant change to resolve, I consider this out of scope of this bug ticket and I'm going to discuss potential solutions with @brdunfield and @brianseek tomorrow at our regular sync and we'll open a follow-on from there.
