### ISSUE TITLE
[PM, Design, FE, BE] 10-10EZ - Medicare Claim number: Perform QA run-through on new field

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#44116]
## Background
As per request from HEC team/Stacey Echols, the Medicare Claim number is needed by downstream systems to assist in billing processes and tracking.  This field will also be added to the paper form, which we will coordinate our release on 8/8.
We need to perform QA on the new field within the [Insurance Info - Medicare page](https://staging.va.gov/health-care/apply/application/insurance-information/medicare) and ensure we are appropriately capturing the "Medicare Claim Number".  This field is alpha-numeric and will have input validation for having exactly 11 characters.

**Note: We will not be validating this number against any Medicare database for valid coverage**

- See ticket #44112 for Backend details
- See [ticket #33561](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/33561) for content background, as well as the links below for designs:
     - The claim number field [now has an expandable info alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygw2kK8)
     - The [open expandable info](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/eKeE8dq)
     - The [closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbpzrqd) and [open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/wLqej1V) error states.

---

## Tasks
- [ ] Perform QA on the [Medicare page](https://staging.va.gov/health-care/apply/application/insurance-information/medicare) for the new Medicare Claim number field
     - [x] The question and field should be below the Medicare effective date question
     - [x] Check spelling
     - [x] Check accordion dropdown
     - [x] Check data input - positive and negative testing
     - [x] Check Review page to confirm the data is present
          - [x] Edit the data on the Review page
     - [x] Submit application and review with Backend for successful data capture
- [x] Run through testing with a screenreader 
- [x] Run through testing with tab-focus

## Acceptance Criteria
- QA has been completed successfully on the new Medicare Claim number field.

**Comment by hdjustice** [comment]
End2End testing was completed - see [email from Stephanie (ES Testing team)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Medicare%20Claim%20number/8-5-2022%20E2E%20Testing%20confirmation.md)

**Comment by hdjustice** [comment]
Ran through Medicare Claim number field page with NVDA - screenreader read each question and section as expected, matching the same structure as other pages with freeform fields
