### ISSUE TITLE
Update multiple inputs to reduce user confusion

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#44117]
## Issue Description
The LOA, OCTO Crew Lead and Business Owner fields should be updated in the form to supply more clarity to the user for what information is being requested here. Additionally, Business Owner should be titled "VA Business Owner" for better context.

---
## Tasks
- [x] Update the form text for "Business Owner" to read "VA Business Owner"
- [x] Update the form input for "VA Business Owner" to show available business owner options
- [x] Update the form input for "LOA" to show available options of 1-4.
- [x] Update the form text for "OCTO Crew Lead" to read "OCTO Crew"
- [x] Update the form input for "OCTO Crew" to show available OCTO crew options
- [x] Update the form text for "Team Point of Contact" to read "VFS PM"
- [x] Add "Owned" field to the form
- [x] Confirm validation still works for all changed fields
- [x] Update schema as necessary

## Acceptance Criteria
- [x] The title of VA Business owner displays for one of the inputs on the form.
- [x] The title of VFS PM displays for one of the inputs on the form.
- [x] The owned input exists on the form.
- [x] The title of OCTO Crew displays for one of the inputs on the form.
- [x] The VA Business Owner input is a dropdown with choices, taking away the free input from the user.
- [x] The LOA input is a dropdown with choices, taking away the free input from the user.
- [x] The OCTO Crew input is a dropdown with choices, taking away the free input from the user.
- [x] The validation script checks the new entries accordingly
- [x] The schema is up-to-date.

---

**Comment by CBonade** [comment]
Form is updated with dropdowns and term changes. Validation passed, ready for review!

**Comment by pjhill** [comment]
Looks good! We can circle back and clean up unit tests at the end of this round of changes.
