### ISSUE TITLE
[FE] Include Time Zone with Appointment Information in Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44137]
## User Story
As a Veteran who has to travel to a different time zone for my appointments, when I see a list of my appointments, I would like to know what time zone the appointment time is for, so that I will know when to show up.

## User Workflow
- Given I
    - Am using the Check-in application to check-in to my appointment
- When I
    - View my appointment information on the "Your appointments" page or on the "You're checked in" page
- Then I
    - See the time zone displayed for each appointment
  
## Wireframes
TBD

## Tasks
- [ ] [FE] Display Time Zone information with each appointment that is displayed to the user
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
