### ISSUE TITLE
MPI Service `add_person` error parsing

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#44144]
## Issue Description
This story will improve the MPI library's error response handling for failed `add_person` calls, parsing the response XML for attributes that will be included in vets-api's logs. A subsequent PR will also add this error parsing to `find_profile` MPI calls.
[Relevant Slack thread](https://dsva.slack.com/archives/C01CHAY3ULR/p1657552311694709)

---
## Tasks
- [x] parse MPI `add_person` error response for `acknowledgementDetail/text`
- [x] parse MPI `add_person` error response for `targetMessage/extension`
- [x] parse MPI `add_person` error response for `typeCode/code` (this might already be parsed)
- [x] included new error attributes into Sentry logging context
