### ISSUE TITLE
[FE] Update list semantics

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44145]
## Background

This is a follow-on from #43176 - existing definition lists need to be updated to be more semantically correct.

## Recommendations from Platform Accessibility Team

- For the demographic information (emergency contact, next of kin): Use an unordered list, ul/li . That should be sufficient structure for that data.
- For the appointment cards, make each appointment heading an h2 and make the facility and clinic information a p. Associate the p with the h2 using aria-describedby, which will associate the information currently in the dl with the heading when a screen reader user is navigating by headings. It will look something like this:
```
<h2 aria-describedby="some-unique-id">10:30am</h2>
<p id="some-unique-id">
     Facility: asdf<br />
     Clinic: ghjk
</p>
```

## Tasks
- [ ] demographic confirmation screens are updated to use unordered lists
- [ ] appointment cards are updated to use headings and `aria-describedby`
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
@sarahknoppA6 sorry, I should have pulled this back to in progress. We have picked up some changes since Bethany has been out.

**Comment by loripusey** [comment]
Validated @brianseek

**Comment by brianseek** [comment]
closing with validation
