### ISSUE TITLE
[AWS / IAM] Group/team policy creation for team-matsomoto

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#44147]
## Who is the devops resource on your team?
@mviterna

## Description

We need to create two new groups that mirror #team-matsumoto. The team names are #team-ninja-pigs and #team-caracal. 

## Background/context 
- team-matsomoto was split and will soon be decommissioned. 

## Technical notes

We need to make sure Kevin Cranmer is assigned to team-ninja-pigs, and Mark Viterna and Kristen Brown are assigned to team-caracal

---
## Tasks
- [x] Two groups created that mirror team-matsumoto

## Acceptance Criteria 
- [x] Existing access/functionality around groups must be maintained

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mviterna** [comment]
@ph-One I don't see any issues on the PR. Do we know which iam role has SQS and Redis Cluster views? I think we will need access to those. We need a dev SQS queue made, and we will need access to view and change the timeouts etc on it. Also, it would be nice to see the redis clusters, since we need to support that. We were asked to verify some things from devops one of our redis clusters, and we didn't have view access on those.

**Comment by oseasmoran73** [comment]
Relevant tickets

https://github.com/department-of-veterans-affairs/va.gov-team/issues/44419
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44488

@mviterna [PR](https://github.com/department-of-veterans-affairs/devops/pull/11590) Kyle linked. I see you noted yourself as a devops resource, what can we do to enable you? You can push/edit/modify the PR Kyle linked. If Terraform is the issue, the `vsp-bot` output gets attached per commit and you can view reference there

**Comment by mviterna** [comment]
@oseasmoran73 I apologize! I'll make the changes and push

**Comment by mviterna** [comment]
@oseasmoran73 I pulled it out of Draft, added an approved review, but I don't think I'm part of the VSP reviewer group, so I can't merge it

**Comment by oseasmoran73** [comment]
@mviterna No worries! Just trying to make sure the ball is rolling and don't leave you in the dark 😄 Yeah our team will review. Hoping to get around to it today if someone else on the team doesn't beat me

**Comment by mviterna** [comment]
@oseasmoran73 No worries! LMK if you need anything else from me

**Comment by oseasmoran73** [comment]
@mviterna Took a bit longer to review/apply, but PR got merged! Based off criteria. I think this ticket can be closed. Please feel free to reopen if you think it has not met.

Closing
