### ISSUE TITLE
[BE] Make Time Zone for Each Appointment Available to the Frontend

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44142]
## User Story
As a Veteran who has to travel to a different time zone for my appointments, when I see a list of my appointments, I would like to know what time zone the appointment time is for, so that I will know when to show up.

## Tasks
- [ ] [BE] Make Time Zone for Each Appointment Available to the Frontend

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
