### ISSUE TITLE
Identity Flag error handling BE to FE

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#44150]
# Description
Consolidating the authorize and callback error handling, add generic 500 error handling, and redirect errors to the SSOe front-end error page.

# Tasks
- [x] consolidate `handle_authorize_error` & `handle_callback_error` into `handle_pre_login_error`
- [x] consolidate `log_successful_authorize` & `log_successful_callback` into `log_pre_login_event`
- [x] add generic 500 error handling to `handle_pre_login_error`
- [x] add forwarding to SSOe front-end error page for errors on `authenticate` & `callback` routes for web clients
- [x] update SiS unit specs to test both web (error forwarding to vets-website) & mobile (return JSON error) behavior
