### ISSUE TITLE
[CDP] Migrating URL to manage-va-debt

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#44155]
## Issue Description
The base URL for the Combined Debt Portal is moving from `/manage-debt-and-bills` to `/manage-va-debt`. 

---
## Tasks
- [x] `content-build` registry needs to be updated with new URL
- [x] Update CDP `manifest.json` with new URL
- [x] Update all CDP breadcrumbs that have old URL references 
- [x] CDP ctaWidget has new URL so content can link correctly. 

## Acceptance Criteria
- [x] CDP is functioning normally under the new `/manage-va-debt/summary` URL
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
