### ISSUE TITLE
[PM, Design, FE, BE] 10-10EZ - American Indian question: Perform QA run-through on new question

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#44163]
## Background
The "American Indian" question is needed by downstream systems to ensure Veterans are placed into the correct priority group.  This field has already been added to the paper form, so this will bring the online application into line with it.

We need to perform QA on the new question following the *Race, Ethnicity, and Origin* question and ensure both that the question is functioning properly and the information is being transmitted to the Enrollment System.

See ticket #28973 for epic details.

---

## Tasks
- [x] Perform QA on the *American Indian* question
  - [x] The question should immediately follow the *Race, Ethnicity, and Origin* question
  - [x] Check spelling
  - [x] Check accordion dropdown
  - [x] Check that the question is required
    - [x] Confirm that users cannot proceed without answering the question
    - [x] Confirm that users can proceed by answering **Yes**
    - [x] Confirm that users can proceed by answering **No**
  - [x] Check Review page to confirm the data is present
    - [x] Check that the data can be edited on the Review page
    - [x] Confirm that users cannot remove their answer to the question
    - [x] Confirm that users can change their answer from **Yes** to **No** and still proceed
    - [x] Confirm that users can change their answer from **No** to **Yes** and still proceed
  - [x] Submit application and review with Backend for successful data capture
- [ ] Run through testing with a screenreader
- [ ] Run through testing with tab-focus

## Acceptance Criteria
- QA has been completed successfully on the new American Indian question.

**Comment by markfallows** [comment]
Updated task list with those that have been completed.

All that remains outstanding is screen reader and tab order.

**Comment by TiffanyPender** [comment]
I’m including a few accessibility feedback notes on the additional screen reader testing of the 10-10EZ form American Indian question in staging. Listed below are some items to consider. I’m using the feedback format, which may be helpful in determining priority. Feel free to reach out to myself or @AngelaFowler82 for questions or comments. 
CC: @davidakennedy @eli-oat (part of Shared Support team)

**The Positives**
- `aria-label="Breadcrumb"` is present and the use of `aria-current="page"` is used on the last item
- `aria-expanded` attribute is used for expandable-collapsible areas
- Use of natively interactive elements for expandable-collapsible areas, so there's a built-in way to focus it with a keyboard and it shows up in the screen reader rotor.
- Use of heading levels, including `<h1>` 
- There is a label associated with each radio input

----
**Feedback**
- **❗️ Must** for if the feedback must be applied:
  <br/>
- **⚠️ Should** if the feedback is best practice:
  - The current “Please provide a response” error messaging, plus the “* Required” visible text that is read by the screen reader is great, but also consider adding aria-required and aria-invalid on the wrapping element when an error is triggered.

- **✔️ Consider** for suggestions/enhancements:
  - The screen reader announces the visual breadcrumb indicators, >, as “angle quotation mark”. Consider using CSS to prevent screen reader announcement of these visual breadcrumb indicators that don’t add value to the content meaning. Alternatively, you could use the Font Awesome icons, similarly to how the checkmark icon is used on the expandable-collapsible area.
    - W3 breadcrumb css example
    - CSS chevron example using transform property
  - For the expandable-collapsible area of “You’re filling out a shortened application”, screen reader-only text of “Alert” is present and read aloud, even though there is no aria role attribute present. It may be good to get user feedback on their preference of hearing the word “alert” with this type of content. There may be consideration for alternative verbiage, such as “please note” or text that communicates relevant information that doesn’t need their immediate attention.
  - Consider making the `aria-describedby` on the BACK and CONTINUE buttons dynamic based on the user’s current step in the form progress. Currently they both point to the same `h2#nav-form-header` element (the step indicator text) on the same page.  Ideally, the `aria-describedby` should reflect the correct association. For example, if a user is at STEP 2 OF 3, and clicking the BACK button will take them to STEP 1 OF 3, the `aria-describedby` text should reflect that. In this current implementation, it is associated with the current page step progress. Usability testing may provide more insight from users on if this is a point of confusion.
