### ISSUE TITLE
Add Instructions to How To Provide Feedback guidance for removing governance-team label

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#44161]
## User Story
As a Governance team member, I want to ensure that feedback tickets do not have the `governance-team` label so that tickets do not populate on our ZenHub board.

Assignee: @seanasewell 
Peer Reviewer: @CherylEvans 

## Description
Ticket #42851 was created to remove the Feedback column and the `governance-team` label from the feedback templates.
Sean raised a condition where if the ticket is created from the Platform Governance Team ZenHub board, it will automatically add the `governance-team` label. This ticket is to add directions to remove the governance-team label if the reviewer does create the ticket from the ZenHub board.

## Impacted Artifacts
[How to Provide Feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to Provide Feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[Collab Cycle Feedback Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md#platform-directions)

## Tasks
- [x] Add bullet under [If you have feedback](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent#After-the-meeting) to remove the `governance-team` label (if and only if they create the ticket using the New Issue link from the Platform Governance Team board)
- [x] Add bullet under [If you have feedback](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review#After-the-meeting-or-asynchronous-review) to remove the `governance-team` label (if and only if they create the ticket using the New Issue link from the Platform Governance Team board)
- [x] Add bullet under [Platform Directions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md#platform-directions) to remove the `governance-team` label (if and only if they create the ticket using the New Issue link from the Platform Governance Team board)

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Instructions are provided for removing the `governance-team` label from future Feedback tickets
- [x] Reviewers are aware of the scenario that will automatically apply the `governance-team` label

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team and sized.
- [x] When brought into a sprint, move to the Planned pipeline.
- [x] When brought into a sprint, add assignee and specify Peer Reviewer.

**Comment by seanasewell** [comment]
@CherylEvans Ready for peer review!

**Comment by CherylEvans** [comment]
@seanasewell I just noticed something.  Don't publish yet please.

**Comment by CherylEvans** [comment]
@seanasewell I recommend changing "if and only if", to "only if"...Perhaps bold the word "only" for emphasis.

**Comment by chaseakirby** [comment]
@seanasewell I checked off the AC "Instructions are provided for removing the governance-team label from future Feedback tickets" since all three have been updated.
When I wrote this ticket, I added the AC "Reviewers are aware of the scenario that will automatically apply the governance-team label". Do we think that this is still relevant and should be posted somewhere? I recall us explaining how the governance-team label works with our ZenHub board on a team meeting briefly in mid-July.

**Comment by shiragoodman** [comment]
@chaseakirby Could you just add this to our standup agenda on Wednesday? we can notify folks then. I'm not too worried if people forget bc the impact to accidentally having `governance-team` label on a feedback ticket is minimal. If/when it's found, we'll just remove the label. nbd.
