### ISSUE TITLE
[SPIKE] Determine How Much of Blackbox Exporter Can Be Replaced with Datadog Synthetics

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#44173]
## Description
We currently have a commercial AWS account that has a sole purpose of running a tool known as Blackbox Exporter. It simulates user traffic and reachability to the site(s) and several endpoints to check for issues reaching va.gov and the like from the internet vs from within the same environment / VPC. 

With the addition and implementation of Datadog, it would be nice if we could replicate this functionality via synthetics and perhaps remove the need to maintain this tool and this separate commercial AWS account entirely.

## Background/context 
- Some brief conversation around it: https://dsva.slack.com/archives/CTYQL39FE/p1657631467108719

---
## Tasks
- [ ] Determine if we can have the same functionality in Datadog that the Blackbox Exporter provides

## Acceptance Criteria 
- [ ] Determination made on how/if we can rid ourselves of Blackbox Exporter as well as the commercial AWS account

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
This might be interesting to evaluate as part of #47025

cc: @ph-One
