### ISSUE TITLE
Update API documentation to be OpenAPI 3.0 standard compliant

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#4417]
## Problem
We are currently using OpenAPI 2.0, and OpenAPI 3.0 has been released some major updates.  It would be a worth while investigation to see if these updates are valuable to our application and what the feasibility of upgrading would be.

## VSP Q1 + Q2 2020 OKRs 
O5: All customers comply with the Platform's standards.

## Details and Notes

- There are rumors that Lighthouse is thinking of upgrading to OpenAPI 3.0.

**Comment by kfrz** [comment]
Lighthouse has merged changes to bring their work up to OAS3, and I definitely think we should make time for this effort in Q1 2020.

**Comment by kfrz** [comment]
Steps we should take for grooming this IMO:

- [ ] Proper discovery of our (non-DVP) endpoints to see the "lay of the land,"
- [ ] Ticket work required to: 
    - [ ] update swagger_blocks to 3.0
    - [ ] update api endpoint swagger docs to be OAS 3 compliant
