### ISSUE TITLE
Review, copy edit and publish new check COE status static landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44177]
## Issue Description
Once the COE tool launches to 100%, we need to publish the new static landing page we created for Check the status of your VA home loan COE. We'll also need to set up the url and breadcrumbs.

Preview link of new page: preview-prod.vfs.va.gov/preview?nodeId=44020

IA info to work from: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

## Tasks
- [x] Review (Laura) 
- [x] Final copyedit (Megan)
- [x] Set up url and left nav (Megan)
- [x] Publish page (Megan)

## Acceptance Criteria
- [x] New static landing page is live on the site

**Comment by laurwill** [comment]
Thanks @RLHecht ! The Check COE status page looks good to me — I just added TTY to a phone number. 

I also reviewed the IA work linked above, and I had one question: Are we planning any mention (or an entry point) to the new Check COE status tool from the [How to request COE page](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/)? Once we remove the react widget, the page will link to the new "Request COE" online form, but it won't mention the new tool to check COE status and download COE.

**Comment by mnorthuis** [comment]
Here's a link to the original IA request with some conversation that may be helpful: https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/23573

**Comment by RLHecht** [comment]
@megzehn This is ready for you to do a copy edit on. We are doing a staging review for this on 2/10, so ideally this would be finalized by Monday or Tuesday. We can't publish until the form launches. Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! I reviewed this and left it in drafts for now.

**Comment by RLHecht** [comment]
@megzehn The product team is launching the COE tool to 100% midday 2/16, so we can publish this new page late afternoon tomorrow. The IA guidance is linked at the top of the ticket for the url and left nav placement.

**Comment by RLHecht** [comment]
This is now live. Closing ticket.
