### ISSUE TITLE
[FE] Swap Date Control for New Design System's Memorable Date Control

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44189]
## User Story
As a team, we would like to use the new DS date control so that we are using the most up-to-date control.
 
## Tasks
- [ ] [FE] Swap Date Control for New Memorable Date Control
- [ ] Test the control in a review environment and communicate any issues to the DS team
    - Does all the same validation that we have in place still work?
- [ ] Monitor the check-in and pre-check-in numbers to ensure it is not dropping % wise
- [ ] Notify Shawn Adams when available on staging
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by loripusey** [comment]
@acrollet is this one in progress?
cc: @sarahknoppA6

**Comment by loripusey** [comment]
We had said that we were targeting 7/26 to release LoROTA (minus delete), so that is at the top of the list

**Comment by acrollet** [comment]
ok, I'll sync with @brianseek and one of us will pick it up

**Comment by loripusey** [comment]
Talked to Brian, he's going to finish Location and thinks he can get this to a PR by EOS

**Comment by brianseek** [comment]
@loripusey this has been merged and should show up on stage to test later today.

Here is a gif of it in action:
![date-flow.gif](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/28feb9cd-dd0d-4600-8b58-73b888614e3d)

**Comment by brianseek** [comment]
Will test on Monday morning before feature flip on prod.

**Comment by brianseek** [comment]
@loripusey I tested this on stage with @acrollet today and everything looks good. Is this ticket good to close?

**Comment by loripusey** [comment]
Yes, good to close
