### ISSUE TITLE
Update api-va.gov to platform-api-va.gov [Cloud Isolation Team]

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#44186]
[TBD - Problem Statement, Objective, Goal] 

[Cloud Isolation Team Epic ](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538)

### Product Checklist 
<details>
  <summary>Toggle Product Checklist</summary>

## Product
- [ ] Initiative Summary
- [ ] Release Plan
- [ ] Update product guide

### VSP Collaboration Cycle
- [ ] Project Kickoff
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging Review
- [ ] Privacy & Security Review
- [ ] Full Accessibility & 508 Audit
</details>

### UX Design Checklist 
<details>
  <summary>Toggle UX Design Checklist</summary>

  
##### Complete this checklist for all new projects. Capture responses in [TBD]. Also note: “we don’t know” is a perfectly valid answer.

[ ] What do we know?
[ ] What is the problem statement?
[ ] Who is the target user?
[ ] Is there a list of questions and assumptions?
[ ] What other information exists (existing research, metrics, etc.)?

[ ] Where does this come from?
[ ] Who surfaced the issue/problem/opportunity?
[ ] Is this in, or related to items in, the [Product/Design Wishlist](https://docs.google.com/document/d/1Cwe6CViDPME9lt6puMs9KBIqT8wZ2NNoMCXR1dEdZUU/edit#heading=h.iwlf7nqnidb)?

[ ] Who is driving this?
[ ] Is this led by product, UX, or another group?
[ ] Who are the stakeholders?

[ ] What value does this bring?
[ ] What (generally) value does product, UX, engineers, and/or stakeholders expect this will bring target users?
[ ] How do we expect to measure success?

[ ] How does this fit into the bigger picture?
[ ] OCTO goals
[ ] [VAOS OKRs and KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/vaos-kpis.md)
[ ] Planning the project/initiative
[ ] What are we calling the initiative?

What’s our confidence level in our understanding of the problem and solution (if one exists)? Based on what we know are we confident that we could:
[ ] Start speccing a solution?
[ ] Start designing potential solutions?
[ ] Start planning research activities?

Based on our understanding of the problem, and our confidence, what should we do next?
[ ] Commit to next steps
[ ] Document the plan
[ ] Does the documentation exist?
[ ] Problem statement
[ ] Background information
[ ] Larger projects: 
[ ] Initiative doc
[ ] Epic to track work
[ ] UX project plan ticket

All projects:
[ ] Add** project to UX initiative planner
[ ] UX creates discovery, design, spec tickets in the [VAOS Product/Design Board (Zenhub)](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/board?labels=vaos-product-design&repos=33202667,62409417,133843125,66304117) as needed
</details>

### Engineering Checklist 
<details>
  <summary>Toggle Engineering Checklist</summary>

</details>

**Comment by ldelacosta** [comment]
No longer need this initiative. Closing the epic. cc: @JRRoof
