### ISSUE TITLE
[BE] Onsite Notifications: Update Diagram of Onsite Notification Flow

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#44188]
## Background
In order for us to understand all the connections and how a notification makes it onto My VA we want to document the full end to end flow. A diagram was made [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34543). However, we would like a more detailed back end diagram that includes the various connections that are being made on the backend to make this flow possible. This will be an official document that can be referenced to ensure we understand how a notification makes it onto My VA.

## Tasks
- [ ] Create flow documentation in GIT that identifies connections between VA.gov, VA Notify, and DMC (i.e. how debts are added, which trigger notifications in VA notify, which trigger onsite notifications on My VA)
- [ ] Create a diagram to indicate testing/lower environment connection points (i.e. DMC's test environment connecting to VA Notify's staging environment, and DMC's pre-prod environment connecting to VA.gov staging environment*) 

 _*Note: these are the connections as of 7/13. As of 7/14, DMC was actually going to make changes to this so check with Scott James to confirm the end result. See [slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1657811029485509?thread_ts=1656612974.703669&cid=CPE4AJ6Q0) for additional info._

## Acceptance Criteria
- [ ] A document is created in GIT that outlines how onsite notifications appear on My VA in production and staging (i.e. how debts are added, which trigger notifications in VA notify, which trigger onsite notifications on My VA).
- [ ] A document is created in GIT that outlines the environment connections 

## Validation
- _Who can validate this ticket?_ (FE, BE, Design, PM)? PM
- _How can this work be validated?_ ensure the documentation is in the proper GIT repo, contains all the info outlined above and is easy enough for someone with little context to understand

**Comment by tpharrison** [comment]
@ajakabcin @ericasauv09 @Samara-Strauss - I've added an "Onsite Notification Technical Overview" document to the sensitive repo.  You can link to it from [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/onsite-notifications/README.md#technical-overview).  There are some areas that I'm not very familiar with, so I just tried to document them to the best of my knowledge - so some updates/changes may be needed.

Once you've reviewed the document, I'd like to ask Scott James, Melanie Jones, and Kyle MacMillan to review the document as well.

**Comment by Samara-Strauss** [comment]
Hey @tpharrison! Thank you for this! Can you actually link to that document from [our product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/vagov-notifications#backend)? The one you linked your document from is the VANotify outline. We should probably figure out how to reconcile those over time, but we haven't yet.

**Comment by tpharrison** [comment]
@Samara-Strauss - The link has been moved.  I also updated the link in my comment above.
