### ISSUE TITLE
Update life insurance PDF links for VGLI and FSGLI

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44183]
## Issue Description
Stakeholder Steve Fital sent us new links to PDFs we currently point to on our VGLI and FSGLI pages. We need to update these to avoid broken links. Instead of pointing directly to the PDFs, we are now going to point to a landing page so that we don't need to update our link each time the PDF changes. This also means we'll have to adjust the wording on the link and remove (PDF) from the end.

For the [VGLI page](https://www.va.gov/life-insurance/options-eligibility/vgli/):
New link: https://www.benefits.va.gov/INSURANCE/forms/180.htm

For the [FSGLI page](https://www.va.gov/life-insurance/options-eligibility/fsgli/):
New link: www.benefits.va.gov/INSURANCE/forms/8283a.htm.

## Tasks
- [ ] Update links on page
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish page (Megan)
- [ ] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [ ] New links are live on the site

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! Sharing my proposed link text here before updating in Drupal!

### **Proposed link text**

**VGLI page** 

Get SGL-180 to download 

**FSGLI page**

Get SGLV 8283A to download


### **Some notes regarding the form titles on the landing pages vs. the PDFs:**

- The landing page for the VGLI page has "SGL-180," and this is also on the bottom right corner of the PDF form.  The url ending, however, has "SGLV-180." Flagging this in case there needs to be a change here.

- In addition, though outside of the scope of our ticket request, there is another PDF linked on the [VGLI page ](https://www.va.gov/life-insurance/options-eligibility/vgli/) VA page that is formatted slightly different than other forms linked on the page. The full application name is included in the link text vs. the form name (that we usually place in parenthesis). Wanted to flag this as a potential content change as well. Happy to make this change if given an okay!

Sharing a screen capture here:


<img width="692" alt="Screen Shot 2022-07-18 at 6 20 23 PM" src="https://user-images.githubusercontent.com/102090263/179628155-63ad2e15-f67c-493c-95bf-647e0d043e73.png">

**Comment by laurwill** [comment]
Thanks for these excellent questions, @aliyahblackmore ! I emailed Steve to confirm the correct form name, but I agree that we should align with the PDF and landing page text here. You can go ahead and update with your proposed link text. And please make that suggested change to the SGLV 8714 form as well — I think these should all be consistent!

**Comment by laurwill** [comment]
Spoke too soon! Steve just replied that the form itself is labeled wrong — it should be SGLV 180. Please include the "V," and he'll update the form and the landing page on their end. Thanks!

**Comment by aliyahblackmore** [comment]
Thanks Laura! Hi @megzehn ! This is ready for you to review. 

The final updates on Drupal:

**For VGLI page**

[Get SGLV 180 to download](https://www.benefits.va.gov/INSURANCE/forms/SGLV-180.pdf)
http://preview-prod.vfs.va.gov/preview?nodeId=769

I also made a text change to the SGLV 8714 link. Included in comment above - the link included the full title of the form, so I changed to SGLV 8714.

**For FSGLI page**

[Get SGLV 8283A to download](http://www.benefits.va.gov/INSURANCE/forms/8283a.htm).)
http://preview-prod.vfs.va.gov/preview?nodeId=765

**Comment by megzehn** [comment]
These are now published! CC @RLHecht. Thanks, all!
