### ISSUE TITLE
[Research] Payment Info V2: Update research artifacts

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#44195]
## Background
The conversation guide, research plan and prototype have been created for the Payment Info version 2 however, we now need to update these artifacts in order to move forward with our research for this initiative. 

## Tasks
- [x] Update [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/conversation-guide.md)
- [x] Update [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/research-plan.md)
- [x] Update [prototype](https://www.sketch.com/s/5b39a70d-f5f1-421f-b2d6-f988cc56d7c3)
- [x] Review updates with team

## Acceptance Criteria
- [x] All artifacts are updated for conducting research
