### ISSUE TITLE
Tree test revised left navigation for Research and Design page on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44196]
## User Story
As a researcher, designer or team stakeholder on the VA Platform, I want to easily identify the

- Guidelines
- Resources
- Practical tips
- And VA-specific constraints

...that may affect my team's research and design practice on VA platform

Assignee:
@jimuhh 
Peer Reviewer:
@claytonzook 

## Description
This revised navigation is based on results from an unmoderated card sort (ticket #39779 ), along with feedback from VA Platform team stakeholders. It includes proposed new content, revisions to existing content and new categories for both. 

The purpose of this tree test is to evaluate the findability and discoverability of the actionable information that VA researchers and their team colleagues need to succeed at research with VA participants. 

## Impacted Artifacts
[Research and Design Page on Platform](https://depo-platform-documentation.scrollhelp.site/research-design/)

## Tasks
- [x] _Convert [spreadsheet data](https://docs.google.com/spreadsheets/d/1NwzEZLDbsRnM9lbBxn_jiftwn5XkvzCu69VNC8au7Uk/edit#gid=1862257273) to csv formatted for Optimal Workshop_
- [x] _Create new tree test in Optimal_
- [x] _Generate testable navigation tree from csv data_ 
- [x] _Write 5-7 findability tasks_
- [x] _Share test with researchers_
- [x] _Analyze results against success criteria_
- [x] Write and share top-line summary of results
- [x] Identify well-performing categories and areas for improvement. 

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria

- [x] IA assigns the navigation schema a **pass** or **fail** grade based on  KPIs, including 
- overall success rate
- direct success rate, 
- time on task 
- [x] IA presents findings 

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@jimuhh FYI - this ticket will need to be updated before we can begin work. It is also blocked until we complete #39779

**Comment by jimuhh** [comment]
@shiragoodman OK, I wrote out the task details. LMK what you think.

**Comment by jimuhh** [comment]
Sample Research Tree Test Tasks

1. You are planning a research study would like to find the standard VSP research plan template. Where would you find that?
2. You are planning a VA mobile site would like to collect Veteran feedback by means of a survey. Where would you find information on the VA rules for doing that? 
3. Two stakeholders on the product team have asked to sit in on your next moderated user test. Where can you find a link to a document describing how they should behave during a session?
4. You are planning a usability test with a user of assistive technology and would like to know how long to schedule it for. Where would you find that information?
5. You are conducting a mobile usability test in Zoom on iPhone and would like to give the participant instructions for showing you what's on their screen. Where would you find this?
6. You're conducting your first moderated research study with Veterans and would like to find out how to get participants. How would you do that?
7. How do find out how to gracefully and compassionately terminate a research session with a Veteran who appears to be traumatized by the questions?

**Comment by claytonzook** [comment]
@jimuhh I think this is a good list. While I'd love to ask some questions about the Research Checklist specifically, since most of that content is duplicated on other pages that would be difficult. So I have nothing to add to this list.

I do have a couple minor edits on 1, 2, and 3, my key:
[word add]
{wording change}

1. You are planning a research study [and] would like to find the standard VSP research plan template. Where would you find that?

2. You are planning a VA mobile site [and] would like to collect Veteran feedback by means of a survey. Where would you find information on the VA rules for doing that?

3. Two stakeholders on the product team have asked to sit in on your next moderated {usability} test. Where can you find a link to a document describing {their role and responsibilities} during a session?

**Comment by shiragoodman** [comment]
my 2 cents - remove all instances to "VSP". Use "platform" instead or just remove all together.

**Comment by jimuhh** [comment]
@shiragoodman @claytonzook Sounds good. I'm back online so I'll get this going tomorrow.

**Comment by chaseakirby** [comment]
@jimuhh Hey Jim, I like the tasks that you have outlined.
I do have a couple of thoughts for Acceptance Criteria to make this easier to validate once we are done.
- For "5-15 users complete the test", I think this would fit better underneath Tasks as "Conduct tree test with 5-15 users" since this will be a task to achieve the AC.
- For AC: "IA has examined and evaluated:...", does that directly correlate to Task: "Analyze results against success criteria"?
- I really like the "IA assigns the navigation schema a pass or fail grade based on these KPIs. I think we should also add an Acceptance Criteria along the lines of "Results and Synthesis of tree test are shared with Research group (probably a more fitting name here) and Platform Content team" to give clear indication for peer reviewing of the outputs expected.

**Comment by jimuhh** [comment]
@chaseakirby Good idea. I'll make those edits.

**Comment by chaseakirby** [comment]
Note for future surveys. Please note which Optimal account you are creating the survey under. @jimuhh

**Comment by jimuhh** [comment]
Hi @claytonzook Here's the [raw data results from the tree test](https://docs.google.com/spreadsheets/d/1vn_uAw9wJ1QB7vpWwj_ySJ4stfwU1Yt8Bp6BEjSZhzg/edit?usp=sharing). Overall pretty good. I have some hypotheses about the reasons some of the less successful tasks.

**Comment by claytonzook** [comment]
Thanks for this work Jim! Some nice results. I'm looking forward to seeing the top line summary, and/or presentation of the results.

I'll add a couple of my thoughts to things you've already been thinking about. 
- For task 1, I think we currently have the templates linked from a couple different pages, so we may want to continue that.
- I'd suggest that for task 2, participants might have latched onto the word "mobile" in the question causing less uniformity there.
- For task 8, perhaps we should link Disability Etiquette page from Research with Assistive Technology Users?

**Comment by jimuhh** [comment]
Hi @claytonzook Those are very close to my conclusions. 

- I thought for task 1, another findability solution would be adding a page that was **just** UXR templates and artifacts 
- For task #2, I think the term "mobile" **did** influence behavior. But we may also want a more explicit category title such as, "unmoderated tests and surveys," since a survey is s somewhat different animal than a first click test. 
- for number 8, that link would be a good idea. But we also might consider rolling those two pages together and making the etiquette part available by anchor link.

**Comment by jimuhh** [comment]
Findings [are here.](https://vfs.atlassian.net/l/cp/QGKJt5X1)
