### ISSUE TITLE
Discovery: Develop a backup strategy for generating downtime notifications when vets-api is not available

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4422]
# Overview 

- an AWS migration requires downtime of vets-api (likely downtime: 10 minutes, max downtime: 2 hours) 
- changes need to be made to vets-website to properly inform veterans about the downtime 
  - downtime notifications do not support the required scope, messaging, or behavior 
  - downtime notifications rely on vets-api for their display state 

# Desired behavior 

- [ ] schedule display of notification 24 hours before downtime 
- [ ] schedule display of notification during downtime 
- [ ] disable display of notification (manual or scheduled?)
- [ ] disable starting new forms during downtime 
- [ ] disable continuing forms (save in progress from profile) during downtime 
- [ ] disable login during downtime 

_copy and locations TBD- may be displayed on all pages, on specific applications, or specific pages_

# Technical overview (WIP)

- [configuring current Downtime Notification component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/)
  - Downtime Notification component controls both display and status fetching behavior (`/maintenance_windows` service)
  - configured with list of providing services- full list [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/DowntimeNotification/config/externalServices.js)
  - displays when `/maintenance_windows` returns matching service 
- signin modal uses [ExternalServicesError component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/external-services/ExternalServicesError.jsx) 

# Tasks / Dependencies (Responsible)

- [ ] Document examples of current display behavior (FE)
- [ ] Determine copy for downtime messages (content)
- [ ] Determine what react components we are going to reuse and how (FE)
- [ ] Determine placement for downtime messages (PM)
- [ ] Determine triggers for downtime messages (FE / PM)
- [ ] Create test plan (QA)

# Notes  

- Since the downtime notifications are currently driven by vets-api (which will be down) we will need an alternate way to trigger their display 
  - from an external non-vets-api service / data file 
  - from an internal data file (requires up to 30 minutes to change / build), or
  - based on predetermined window
- Ideally we create something that can be easily used in the future i.e. time permitting, try not to hack this together.

**Comment by brandonrapp** [comment]
@ricetj - Hey TJ - We are working through supporting new downtime notifications and we need some devops support.

We have 2 requests for your team.

1.  We  need to know what kind of response to expect from /maintenance_windows and /backend_statuses during the downtime. we will handle a failure and a !response.ok  (non-200s status) by falling back to the hard coded downtime. this should cover the typical possibilities but i want to make sure they’re not going to do something weird


1. we need to test this behavior in staging once the FE stuff is in place. once we have the FE stuff in place, I suggest we take vets-api down in dev in the manner it will be on production.

**Comment by nwalke** [comment]
@brandonrapp I can help get those statuses tonight.  Can you list the full dev and staging URLs I should be hitting?

**Comment by rianfowler** [comment]
@nwalke here you go. i threw in the curl commands from chrome just in case. 

# Maintenance windows 

## Dev 

- status calls: 
  - https://dev-api.va.gov/v0/maintenance_windows/
  - https://dev-api.va.gov/v0/backend_statuses 
- [test page](https://dev.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States)
  - click sign in to trigger backend_statuses call 
- curl commands from chrome: 

OPTIONS
```
curl 'https://dev-api.va.gov/v0/maintenance_windows/' -X OPTIONS -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: https://dev.va.gov' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Access-Control-Request-Headers: source-app-name,x-key-inflection' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://dev.va.gov/find-locations' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' --compressed
```

```
curl 'https://dev-api.va.gov/v0/backend_statuses' -X OPTIONS -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: https://dev.va.gov' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Access-Control-Request-Headers: source-app-name,x-key-inflection' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://dev.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' --compressed
```
GET (shouldn't fire but just in case): 
```
curl 'https://dev-api.va.gov/v0/maintenance_windows/' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Source-App-Name: facilities' -H 'Origin: https://dev.va.gov' -H 'X-Key-Inflection: camel' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://dev.va.gov/find-locations' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: api_session=nXcyM%2BYVAd4e0S7gX%2FR6pKQ6R4vtKmZh%2FjaC45fcOKVR%2B0GqYwIjX1cNIZtcUmZRnzRrjVdfOt29LdjxIw%3D%3D--maztjXYJp5shCdly--2Z3rSlZ5l%2FJwYg2P0Aajug%3D%3D' --compressed
```

```
curl 'https://dev-api.va.gov/v0/backend_statuses' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Source-App-Name: facilities' -H 'Origin: https://dev.va.gov' -H 'X-Key-Inflection: camel' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://dev.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: api_session=fd0AuQFp6sFUARad12VdORFG5tQd8p1wOq8m2u3aoBFKBhSkKzPLTgDw%2BAolD3o9FLdxrQfmH7%2FM57BJHg%3D%3D--%2Bq2vyriTa2cO9BEq--B779Yb09Ik4KMyINPjrRzA%3D%3D; TS016f4012=0119a2687f269cafd270ebc81a1506abc4fcd3a7e09cd1b0febd9dc28aacc1c87516ea4589364278d493217204934748c5df3aed9bb2b499041fc57fe1b7c0528e85989e18' --compressed
```

## Staging 

- status calls: 
  - https://staging-api.va.gov/v0/maintenance_windows/
  - https://staging-api.va.gov/v0/backend_statuses
- [test page](https://staging.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States)
- curl commands from chrome:

OPTIONS

```
curl 'https://staging-api.va.gov/v0/maintenance_windows/' -X OPTIONS -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: https://staging.va.gov' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Access-Control-Request-Headers: source-app-name,x-key-inflection' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://staging.va.gov/find-locations/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' --compressed
```

```
curl 'https://staging-api.va.gov/v0/backend_statuses' -X OPTIONS -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: https://staging.va.gov' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Access-Control-Request-Headers: source-app-name,x-key-inflection' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://staging.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' --compressed
```

GET

```
curl 'https://staging-api.va.gov/v0/maintenance_windows/' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Source-App-Name: facilities' -H 'Origin: https://staging.va.gov' -H 'X-Key-Inflection: camel' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://staging.va.gov/find-locations/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: api_session=l7fQ3%2FFJVU38%2BF%2F%2Fah80%2FfxrouqHUL1cVnaUQ26c1UcP4UDc%2Fo9OMF4hvXVgFwwi4oJcZJNST6F4df8z%2Fw%3D%3D--otk6RSrY%2FCLCWfFp--j5ii2Cdfqvg4XU0LzClpiw%3D%3D; TS016f4012=01c8917e48f8a49897e8ca686dc702269da9e3f23f91784241961e4b496261bd89a3c3c47f6ff773cb5e8729ca7b10703bf9a32e7ff426169e828b8b65734dbda7bcef067f' --compressed
```

```
curl 'https://staging-api.va.gov/v0/backend_statuses' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Source-App-Name: facilities' -H 'Origin: https://staging.va.gov' -H 'X-Key-Inflection: camel' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://staging.va.gov/find-locations/?zoomLevel=4&page=1&address=3900%20Road%2C%20Coffeyville%2C%20Kansas%2067337%2C%20United%20States&facilityType=all&serviceType&location=37.04%2C-95.64&context=Coffeyville%2C%20Kansas%2067337%2C%20United%20States' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: api_session=52slJCZ4QsfTb1cPFiNP9QZjnBbt0stk5NHDgMlBFV1NSdC0SWMx3bSsB7KnO5FGW2IL4CgkoHWxgwJcSg%3D%3D--0BMuBDARMgva2den--UXi3EYuFIBLOL2s9%2Bo1a%2Fw%3D%3D; TS016f4012=01c8917e48a672637919f6c3f79987d52463dc68d391784241961e4b496261bd89a3c3c47fc2e5f36f4577595a98959eb26eb5b0cc83d1d91d99fada783a581c7c0c931d25' --compressed
```

**Comment by brandonrapp** [comment]
@nwalke - If you could post your findings here in this ticket, we would greatly appreciate it!

**Comment by nwalke** [comment]
@rianfowler awesome, thank you!
@brandonrapp will do!

**Comment by nwalke** [comment]
The actual VPC move happens so quickly I didn't even have time to watch dev.  I scripted the above commands before I did staging and captured this output while it was unavailable: https://gist.github.com/nwalke/66fcc92c8f4e44458dc7ba5ea6e0bafd

**Comment by rianfowler** [comment]
@nwalke Thanks- very helpful. We'll need to make some tweaks to react to this response. 

@johnpaulashenfelter if you look at the example above, we're getting a 200 on an internal server error. We may want to follow-up on this later- it's generally easier for FE if we get accurate HTTP status codes (e.g. I'd expect a 500 in this instance)
