### ISSUE TITLE
[Design] 10-10CG - Mulesoft Ph 2: Content to encourage email input

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#44238]
## Background
As part of the Submission page content revision to align with MuleSoft Phase 2 (queuing), the main communication from the Caregiver team will be through email channels.  We want to add content around the email fields within the application to encourage email input (i.e. how useful it would be to communicate).

See **[CG meeting notes from 7/8/22](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Meeting%20Notes/7-8-22%20CG%20Stakeholder%20Touchbase.md)**

## Tasks
- [ ] Create content for the Contact pages within the CG application to encourage email input from the Veteran and Caregiver(s)
- [ ] Propose to the team and PO
- [ ] Provide link to mock-up for FE development

## Acceptance Criteria
- Contact pages that request an email address from the Veteran and Caregiver(s) include some information about how it would be useful for communication, encouraging input.

## Content and design mockups

The updated content, and links to where it can be found, are below:

- The messaging associated with email input fields is adapted from 1010EZ content, and VA / content team input:
     - "**Note:** Including an email address on your application is optional, but it helps us contact you faster if we need to follow up with you. If you don’t include an email address, we’ll use your phone and address to contact you. We’ll always mail you a copy of our decision on your application."

- [Veteran information page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/bgVej79)
- [Primary Family Caregiver page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wLzGlyq)
- [Secondary Family Caregiver page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/QbY2Eo1)

- The following new page headings are also included in this update, on their respective pages:
     - "Veteran contact information"
     - "Primary Family Caregiver contact information"
     - "Secondary Family Caregiver contact information"

**Comment by hdjustice** [comment]
@nicko-amida - Hey there, I created this ticket for us to think about adding some info around the email fields on how it would be used for communications.  This isnt an immediate need, but something we should think about before October.
cc @markfallows

**Comment by markfallows** [comment]
Emails for:
- Veteran
- Primary Caregiver (if applicable)
- Secondary Caregiver 1 (if applicable)
- Secondary Caregiver 2 (if applicable)

Questions:
- [ ] Does the email notification go to all provided emails?
  - Or does it go to the person who's officially _signing_ the document?
    - If so, what happens if there's a Veteran email and not a Caregiver email for the person signing?

**Comment by nicko-amida** [comment]
@hdjustice Closing this issue and creating a front-end ticket with the updates! See the "Content and design mockups" section I added above.

**Comment by hdjustice** [comment]
Hi @nicko-amida - Did we do the updates with the recent Privacy officer suggestions that we got from Caitlin?  If not, do we have advisement as to why their version is not what we want to display?

**Comment by nicko-amida** [comment]
@hdjustice I sent a more detailed message on Slack, but I'll include any additional updates here.
