### ISSUE TITLE
FE | Profile | Change Address Prompt Modal | GA Bug

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44230]
## Background

The GA widget is showing a modal event capture that includes other messaging info along with PII.

## Tasks
- [x] Turn off Feature Toggle until resolved
- [x] Investigate how PII is being captured and reported thru GA and options to fix
- [x] Explore whether there are options to remove the "not set" text to make reports easier to read.

## Acceptance Criteria
- [x] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Moving some comments from #44310 since it was a dupe to this ticket:

Per @adamwhitlock1 
>The feature toggle responsible for showing the UI that is tied to these GA events has been turned off, so that no more information is reported to GA in this regard.

A couple things that I am noting from investigating this.

The problematic data seems to be getting sent in the place that {{ clickText }} is being sent in the GA code
Since this is automated and not something that is sent in by any of our team's FE code, I dont know how we would specifically mitigate this
We are using the newish va-modal component instead of the legacy React based component, and I would be curious if this could be an issue revolving around that new web component.
I've also tried reproducing this event in any way and cant seem to
The only thing that I can possibly think to do at this point would be to revert our code to use the old VaModal React Component instead of the web component and open a ticket with the design systems team / analytics team to investigate the component events further and to mitigate this issue if possible for any future usage.

**Comment by SKasimow** [comment]
@adamwhitlock1 - are there any downsides to using the old VAModal React component?

Also, I think Mark used the new modal component for BAI; can you check?

**Comment by adamwhitlock1** [comment]
@SKasimow I would say we can close this as it is handles on the analytics team and didnt require any extra action from us.
