### ISSUE TITLE
BE | Profile | Military Info | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44232]
## Background

Complete documentation for Military information used in profile.

## Tasks
- [ ] Add BE documentation for Military Info in the private repo
- [ ] Link to the documentation from the public repo
- [ ] Make necessary updates to existing documentation (incorporate feedback and update broken links)

## Acceptance Criteria
- [ ] Add BE documentation for Military Info in the private repo
- [ ] Link to the documentation from the public repo
