### ISSUE TITLE
BE - Auth Profile - Direct Deposit - Test BGS Production Access

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#44249]
## Background
There have been latency issues with BGS-related services over the past couple of months.  The latency occurs for a few hours and then the response times return to normal.  I have requested temporary production access with intent of making a BGS request in production during the next period of latency.  

The purpose of this ticket is to familiarize myself with the process of making a BGS request in production so that a request can be re-run quickly the next time the latency occurs.  This will allow us to collect more data around this recurring issue.

## Tasks
- [x] Make a read-only request against a BGS endpoint in staging.
- [x] Make a read-only request against a BGS endpoint in production.

## Acceptance Criteria
- [x] Record the response time of the request.
