### ISSUE TITLE
[BE] Make appointment time zone available to the frontend

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44242]
## User Story
As a Veteran who travels to a clinic outside of my time zone, I would like to see the time zone for my appointments so that I understand what time I need to show up for my appointment.

## Tasks
- [ ] [BE] Make appointment time zone available to the frontend

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
