### ISSUE TITLE
[Research] My VA Redirect: Update Research Artifacts and Begin Recruiting

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#44256]
## Background
We are ready to begin UAT again for the My VA Redirect initiative so we want to review the existing research documentation (conversation guide, research plan, etc) to ensure we are ready to submit for recruiting. Once everything is ready we can begin the recruiting process. Actual UAT will not start until August.

## Tasks
- [x] Update existing My VA Redirect research artifacts where needed
- [ ] Submit for recruiting

## Acceptance Criteria
- [ ] Artifacts are ready and recruiting has been submitted

## Resources

- notes from Samara: We should accommodate for people who don't get redirected and ask them questions about My VA and whether they would rather land there or the homepage. However, if the redirect doesn't work, we should try other email addresses first just in case that's the issue and not the redirect (this would be for DS Logon or MHV only, as we can see the email address people use to sign in with for ID.me or [Login.gov](http://login.gov/)). I would say we should try 1 or 2 other email addresses first (if people even have that many), and then we should feel free to move on to the questions about My VA.
In our meeting with identity folks the other day, we logged in with an LOA1 user (they should/do get redirected just like LOA3 users), and Joe Niquette (also a veteran) suggested we include LOA1 accounts in our research since the redirect experience for them may not be as valuable as it is for LOA3 users. I forget if we disqualify folks based on whether they are LOA1 right now, but I think we should include some questions in our convo guide in case people log in and are LOA1. Is the redirect valuable for them (My VA basically just shows a prompt to verify their identity)? Would they rather land on the homepage? How could we make My VA more valuable in this case?

**Comment by andaleliz** [comment]
@Samara-Strauss, @ericasauv09 and @ajakabcin I've updated the[ research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/research-plan.md), and [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/UAT/conversation-guide.md) with the following updates:

**Research Plan**
---
- added criteria to recruit some LOA1 users. Hoping we can get at least 2 to participate, so I've requested 4.  I asked about the amount of LOA1 vs LOA3 users on VA.gov [in the identity channel](https://dsva.slack.com/archives/CSFV4QTKN/p1658256828193619) to make sure this is a reasonable request. If I'm way off, I'll update these numbers to be more representative of what we'd see.
- Updated dates and times
- Added Michelle and Cindy to observer list

**Conversation guide**
----
- added prompts to try additional email addresses if redirect doesn't work out
- added notes to skip to task 3 if redirect doesn't work
- added some questions for LOA1 users to elicit conversation around the value of My VA

----

I'm planning on submitting this to kick off recruiting by Monday afternoon. Since I've got PTO on Friday and most of Monday, it would be wonderful if you could let me know you've reviewed this, and share any edits by Friday.  Thanks so much!

**Comment by andaleliz** [comment]
I learned from the identity team that in the past month, LOA1 accounts account for 30% of ID.me logins, and **73%** of login.gov logins! That login.gov number is surprising to me - anyone else?

It would really complicate the recruiting criteria if we try to align participants with what we see on the site, but we can figure that out if we think it's necessary. I personally don't - I think as long as we can talk to 3 LOA1 users we can get a sense of how this redirect works for them.

**Comment by ajakabcin** [comment]
Looks great Liz thank you!

**Comment by Samara-Strauss** [comment]
I've reviewed all the materials, and they all look good to me. There are a lot of recruiting must-haves, so, as usual, we'll need to see if Perigean has any trouble recruiting based on our criteria. If not, great! If so, we can talk about how to adjust accordingly.

**Comment by Samara-Strauss** [comment]
@ajakabcin ☝️ I think you posted this in the wrong ticket

**Comment by ajakabcin** [comment]
Woops yeah jumped the gun on that sorry for confusion - though that is the draft release plan for my va redirect in case anyone wants to look ahead 😆

**Comment by andaleliz** [comment]
I've gone ahead and submitted the request to kick of recruiting, letting them know we're giving a little more than a week since I'll be on PTO.  Let's do this!! :)
