### ISSUE TITLE
Supplemental Claims | Add to the existing "service"

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44255]
## Value Statement

**_As a_** developer
**_We want to_** add Supplemental Claims to the `DecisionReview::Service` service
**_So that_** I have the setup needed to send and receive data and handle networking.

## Background Context

This is the lowest level code we have in vets-apis, it is responsible for making remote rest calls to lighthouse, it handles all the networking, sending the Supplemental Claims data to lighthouse, and receiving the results. The existing service is called DecisionReview::Service(vets-api/lib/decision_review/service.rb) and already has create_higher_level_review, create_notice_of_disagreement.  So add create_supplemental_claim and get_supplemental_claims.

## Tasks

- [ ] Add `create_supplemental_claim`
- [ ] Add add `get_supplemental_claims`

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@michelpmcdonald I created this ticket based on our conversation about backend infrastructure for the supplemental claims forms. Does this make sense, or does it need edits?
