### ISSUE TITLE
PHM:  Create Domo Training Materials/Deck

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#44257]
## Issue Description

As part of the Q3 Platform Health Metrics objective the Analytics team will create and conduct Domo training.  This training with differ than current training that focuses on how to access/use Domo dashboards this training will more in depth including how to access your data and how to create dashboards/cards.

Items to cover in training:
- Data connectors
- Card building (analyzer interface, card types, beast modes)
- Dashboard builds and configurations

---
## Tasks
- [x]  Create deck
- [x] Record session
- [ ] Post to platform website

## Acceptance Criteria
- [x] Training deck is complete and ready to present in training
---
## How to configure this issue
- [ x **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
@michelle-dooley Sharing this [working outline](https://docs.google.com/document/d/1asG1va6eJxgOhkUIajLE4oYE4kjTWfXUGk6tsoVUrHU/edit#) for the Domo training. I tried to put this in the order of things most people would likely be doing to things the fewest number of people would likely be doing. What do you think - is anything missing?

**Comment by michelle-dooley** [comment]
@chloedotbrown - started a [deck](https://docs.google.com/presentation/d/1by4IPQlU6f1HR2OieyEXZ2tyoS5W72Vwx_7qPbVAb7Y/edit#slide=id.p), didn't get very far but at least its a starting point to build from.

**Comment by chloedotbrown** [comment]
@michelle-dooley - Finished edits to the [PHM Domo training deck](https://docs.google.com/presentation/d/1by4IPQlU6f1HR2OieyEXZ2tyoS5W72Vwx_7qPbVAb7Y/edit#slide=id.p). If it looks good on your end, want to add it to website and close out ticket? And if not - let me know what changes would be helpful. Thanks!

**Comment by chloedotbrown** [comment]
@michelle-dooley - Here's a link to the [training video](https://drive.google.com/file/d/1I3hR5MSXuqyto9Ml-Wn13ud1CmKQlLAA/view?usp=sharing) on our drive (currently still processing, but I believe Google link should work). It came in at about an hour, but hopefully folks can skip around if they want/need to. Hope it works!

**Comment by chloedotbrown** [comment]
Here's a [link](https://www.youtube.com/watch?v=5UWDocKCMb4&list=PL0QW9C65TdUVzgPFMASgplGQzfmdZjHSE) to the YouTube version of the Domo training, broken up into 5 parts by topic and organized into a playlist.
