### ISSUE TITLE
BE - Auth Profile - Technical Discovery - Sidekiq Background Processing

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#44251]
## Background
Sidekiq is an open source job scheduler written in Ruby. Sidekiq jobs execute the background processes for the VA.gov application.  As a backend engineer, I'll need an understanding of Sidekiq and how it is configured and used to support VA.gov processes.

## Tasks
- [ ] Review Sidekiq features and functionality.
- [ ] Get access to Sidekiq Administration Tool.

## Acceptance Criteria
- [ ] Understand how Sidekiq works and how it is used.
- [ ] Granted access to Sidekiq Administration Tool.
- [ ] Add/update any necessary documentation.

**Comment by SKasimow** [comment]
@tpharrison - think this is a dupe to #44252 and can be closed. Something similar was happening to me earlier where it said my ticket wasn't created so I hit "submit" again and ended up with 2 tickets.

**Comment by SKasimow** [comment]
closing...dupe to #44252
