### ISSUE TITLE
Supplemental Claims | Create a new Supplemental Claims controller

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44262]
## Value Statement

**_As a_** developer
**_We want to_** create a Supplemental Claims controller
**_So that_** the application knows what to do with input provided by claimants.

## Background Context

This can be modeled after the existing HigherLevelReviewsController and NoticeOfDisagreementsController. Add methods for both `create` and `show`.

## Tasks

- [ ] Create the controller
- [ ] Add routes in config/routes
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@michelpmcdonald need some help filling in tasks for this one. Do we need to include a sample of the model for higher level review, or notice of disagreement?
