### ISSUE TITLE
Supplemental Claims | Create New Supplemental Claims Sidekiq worker

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44261]
## Value Statement

**_As a_** developer
**_We want to_** make submitting a supplemental claim a queued worker job
**_So that_** submissions automatically retry if they fail due to services being down.

## Background Context

This will make vets-api reliable. The idea with queued work job is that they able to retry the SC submit multiple times.  So if the Lighthouse SC service(or any services lighthouse depends on are "down"), the queued worker service will eat the error and try again later.  It waits longer and longer between each retry, for example, 526 submissions retry 14 times over a period of 3 days.  We have tickets to make NODs and HLRs sidekiq jobs also, because that was not done for those slices.  

## Tasks

- [x] Create New Supplemental Claims Sidekiq worker

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@michelpmcdonald I also created this ticket based on our conversation about backend infrastructure for the supplemental claims forms. Does this make sense, or does it need edits?

**Comment by saderagsdale** [comment]
@michelpmcdonald and @scottymeyers will add tasks to this ticket.

**Comment by saderagsdale** [comment]
@michelpmcdonald @scottymeyers Hey both. Please add tech tasks to this ticket.

**Comment by scottymeyers** [comment]
Currently, we're first making the request to Lighthouse, and then, we get the response and use the ID from it to create an **AppealSubmission** record, which simply stores the `user_uuid`, `type_of_appeal` and the `submitted_appeal_uuid` in our database. There is an **InProgressForm** which tracks the form state up until submission, and then it's destroyed.

Our intended reference, 526,  first creates a **SavedClaim::DisabilityCompensation::Form526AllClaim** record, and then uses the id from that record in the submission flow. Since the **SavedClaim** stores the form data, we're then able to easily access it during the submission flow.

So in order to make Supplemental Claims and all Decision Review services retry-able, we'll need to gut things a bit.

We could:
1. Save an **AppealSubmission** before making the request to Lighthouse, changing the `submitted_appeal_uuid` to be nil, and adding/saving to a `form_data` column, then kick off the worker, and on success, update that record's `submitted_appeal_uuid` with that `uuid`. I'm not sure of the implications of continuing to store that form information.
2. We could also derive a new class or model from **SavedClaim**, similar to 526, which saves the form data for us, and use that in the submission flow. We'd still need to add a `workflow_complete` column to an **AppealSubmission**, or set the `submitted_appeal_uuid`, on success.

I think the second scenario makes the most sense, but is there any reason I shouldn't use a SavedClaim for Decision Review? @michelpmcdonald would love to get your perspective on this when you're available.

**Comment by saderagsdale** [comment]
Will work with Kyle on it.

**Comment by kylesoskin** [comment]
Have started on this. Progress can be tracked in this branch: https://github.com/department-of-veterans-affairs/vets-api/compare/feature/ksoskin/make_suplimental_claim_retryable

**Comment by michelpmcdonald** [comment]
> Currently, we're first making the request to Lighthouse, and then, we get the response and use the ID from it to create an **AppealSubmission** record, which simply stores the `user_uuid`, `type_of_appeal` and the `submitted_appeal_uuid` in our database. There is an **InProgressForm** which tracks the form state up until submission, and then it's destroyed.
> 
> Our intended reference, 526, first creates a **SavedClaim::DisabilityCompensation::Form526AllClaim** record, and then uses the id from that record in the submission flow. Since the **SavedClaim** stores the form data, we're then able to easily access it during the submission flow.
> 
> So in order to make Supplemental Claims and all Decision Review services retry-able, we'll need to gut things a bit.
> 
> We could:
> 
> 1. Save an **AppealSubmission** before making the request to Lighthouse, changing the `submitted_appeal_uuid` to be nil, and adding/saving to a `form_data` column, then kick off the worker, and on success, update that record's `submitted_appeal_uuid` with that `uuid`. I'm not sure of the implications of continuing to store that form information.
> 2. We could also derive a new class or model from **SavedClaim**, similar to 526, which saves the form data for us, and use that in the submission flow. We'd still need a marker to determine if the submission was successful,  so add a `workflow_complete` column to an **AppealSubmission**, or set the `submitted_appeal_uuid`, on success.
> 
> I think the second scenario makes the most sense, but is there any reason I shouldn't use a SavedClaim for Decision Review? @michelpmcdonald would love to get your perspective on this when you're available.

I know we kicked this around in a few different conversations.  I think either approach would work.  For the second path(ie modeling it after 526 submissions) there are two tables in play:

Form526Submission: This represents the submission, it holds the user's raw form data(JSON) and the authorization security headers EVSS requires when submitting a 526(SSN, EDIPI, Name, stuff like that).  The general flow is that the sidekiq worker is provided a From526Submission ID, the sidekiq worker uses the From526Submission ID to grab the database record.  Getting repetitive here, but the record has all the info to make a call to EVSS 526 Submission endpoint, so once the worker has the record(Model), the worker uses the Model to make the call to EVSS.  This record holds the final result of the submission in a field named workflow complete.
Form526JobStatus: This represent the results of the sidekiq remote calls.  To Submit a 526 and it's supporting user provided files, multiple EVSS calls are used.  For example, one call to establish the claim, one EVSS file upload call per file, and then a few subforms are also submitted, so there are multiple Form526JobStatus records per Form526Submission.  Currently, in  Form526JobStatus, the status, error_class and error_message hold the last results from the call to EVSS and the bgjob_errors field(JSONB) holds the history of all the attempted calls.

I think for Supp Claims, NODs, and HLRs, there is only one call made to lighthouse, contrasted agains the 5 or so calls 526s make to completely establish a claim.  Since there is only one call, to me, it seems reasonable to just have one table to hold both the raw user submitted from data and auth headers and the results of the last call.  Also, I would add a table like Form526JobStatus.bgjob_errors that holds the results of each call attempt(Remember the whole point of using sidekiq to submit appeals is to be able to retry failed calls, might as well store that run history)

**Comment by kylesoskin** [comment]
Currently trying to get some info on an invalid response from lighthouse to complete this ticket.

**Comment by kylesoskin** [comment]
Have to confirm with I think @scottymeyers or @Mottie as to what the front-end needs/wants back.

It looks like we are possibly relying on the submission to validate the input (based off the test and `spec/support/vcr_cassettes/decision_review/SC-CREATE-RESPONSE-422_V1.yml`). since this is getting sidekiq queued for submission, the front-end needs to do this validation prior to allowing the submission since submission now will have no context of the result of the submission (it just plops it in the queue). 

Otherwise the user will think it is submitted, but the sidekiq job will always fail.

**Comment by saderagsdale** [comment]
Huddle with @kylesoskin @thehastingsp.
