### ISSUE TITLE
Authenticate and test integration with VHA SharePoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44279]
## Issue Description
Brian and the VHA SharePoint team will be adding our app to be an authenticated service to POST PDFs to their folder repository. Once we have these credentials in hand we need to test this connection is working as intended. 

---
## Tasks
- [ ] Receive authentication credentials from VHA
- [ ] Test connection to SharePoint with credentials

## Acceptance Criteria
- [ ] We can verify a secure connection with VHA SharePoint via API
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
