### ISSUE TITLE
Generate and submit mock FSR requests to VBS staging

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44272]
## Issue Description
As part of end to end testing with the Huron servers we need to submit a handful of various FSR requests to POST to the VBS staging endpoint
---
## Tasks
- [ ] Create reusable method to generate FSR request
- [ ] Submit FSR payloads to VBS staging

## Acceptance Criteria
- [ ] VBS has received multiple FSR payloads
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
