### ISSUE TITLE
Create MCP endpoint for VBS to submit new statement data

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44275]
## Issue Description
As part of MCP notifications, we need to have an exposed callback endpoint for VBS to submit to vets api to trigger events to VA Notify

---
## Tasks
- [x] New controller method to accept new data
- [x] Build method to handle statement data for when we know structure

## Acceptance Criteria
- [x] VBS can begin testing our callback with new statements
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
