### ISSUE TITLE
[DISCOVERY] Architect new structure of FSR 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44281]
## Issue Description
Currently FSRs are tied to both DMC and User SSN and do not have a saved state. We will need to have a new architecture to refactor off of that decouples these relationships and has a long-term storage solution for each FSR request

---
## Tasks
- [x] Determine best solution to store FSRs
- [x] Generate new architecture diagram that represents new structure

## Acceptance Criteria
- [x] We know how to move forward with refactoring FSR 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Determined to transition FSR and other debt products to new Rails engine
