### ISSUE TITLE
[AWS/AMI/GHA] Replace ubuntu-packer AMI with platform minimal AMI

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#44317]
## Description

Now that the new AMI has been, we should begin placing them in all Github Actions runners. These include EC2 spun from ASG & On-demand runners

## Technical notes
Infrastructure issues detected will be handled by infrastructure
Application specific issues detected will be handled by respective repo owner

---
## Tasks
- [x] Apply new AMI to content-build on-demand runners
- [x] Apply new AMI to ASG's
  - [x] va-virtual-agent
  - [x] vets-website
  - [x] content-build
  - [x] testing-tools
  - [x] vets-api

## Acceptance Criteria 
- [x] packer-ubuntu AMI deprecated
- [x] platform minimal AMI applied to ASG and on-demand runners

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44318

**Comment by jhouse-solvd** [comment]
per Kyle's comment above: It would be good to break these out into individual tickets so that we can keep the tasks moving.

**Comment by oseasmoran73** [comment]
Will verify if there are any `packer-ubuntu` instances that are still up and address accordingly

**Comment by oseasmoran73** [comment]
Looks like there is no an easy way to check (to my knowledge at least). That being said, I did check the ASG LT to see if it has and we are good to go! 

Closing this ticket out
