### ISSUE TITLE
[AWS][GHA] On-demand runners do not have an IAM rold

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#44320]
## Description

On-demand runners when spun up do not have IAM role. This is because it the forked repository does not have an option to pass in role

## Background/context 

Will be helpful for teams to SSH into and look at logs

## Technical notes

Allow a variable in Github Action to pass in role and apply accordingly

---
## Tasks
- [ ] Variable to apply IAM role
- [ ] IAM role applied correctly in AWS
  - [ ] Error handle if incorrect IAM role is passed

## Acceptance Criteria 
- [ ] IAM role applied to on-demand runner
- [ ] User it able to SSH to on-demand runner

**Comment by jhouse-solvd** [comment]
@oseasmoran73 has offered to reach out to @rmessina1010 & @laineymajor on the release tools team to discuss what's needed. (we believe this is a nice-to-have feature, and not mission-critical at this time).
