### ISSUE TITLE
[SPIKE] Investigate Better Way to Mark Old Backlog Items and Stale / Auto_close

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#44328]
## Description
Old tickets in backlog

## Background/context 
https://dsva.slack.com/archives/CTYQL39FE/p1657740419342799

## Technical notes
Perhaps https://github.com/actions/stale?

---
## Tasks
- [ ] Old backlog items marked as stale, closed if not immediately important

## Acceptance Criteria 
- [ ] Investigation complete on if we can/want to use a form of automation for marking very old stale items as such and closing if not still relevant

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mchelen-gov** [comment]
We have GHA stale enabled for access requests, this could be updated to include any other desired labels: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/stale-ops-access-requests.yml

**Comment by jbritt1** [comment]
> We have GHA stale enabled for access requests, this could be updated to include any other desired labels: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/stale-ops-access-requests.yml

Agreed, seems like we could just expand it.
