### ISSUE TITLE
Create forward proxy port to Kong in Staging environment

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#44322]
## Issue Description
As a developer, I need to open up a new forward proxy port to Kong in the Staging environment, so that when the new Lighthouse gateway becomes available, I can pivot the port to point to Apigee.

---
## Tasks
- [ ] Create entry in the forward proxy config file in Staging environment.

## Acceptance Criteria
- [ ] The Staging forward proxy address with port 4492 resolves to Kong.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
