### ISSUE TITLE
Create forward proxy port to Sandbox in Dev environment

### ISSUE THREAD

**Issue by alwerner** [department-of-veterans-affairs/va.gov-team#44327]
## Issue Description
As a developer, I need to open up a new forward proxy port to Sandbox in the Dev environment, so that calls from vets-api using the `sandbox-api.va.gov` domain continue working once it becomes an external API call.

---
## Tasks
- [ ] Create entry in the forward proxy config file in Dev environment that points to Sandbox

## Acceptance Criteria
- [ ] The Dev forward proxy address with port <TBD> resolves to Sandbox.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
