### ISSUE TITLE
Update /internal/auth routes in vets-api to use fwdproxy

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44339]
## Issue Description

The `/internal/auth` domain is used by Lighthouse for OAuth token validation. It will be accessible only from the existing `api.va.gov` domains but not from the new`*platform-api.va.gov` ones. 

One instance in which vets-api makes use of this route (via an API call to `api.va.gov`) has been found in the context of the Claims API. This will need to be updated to use the fwdproxy address instead. 

See code in `modules/claims_api/app/controllers/concerns/claims_api/ccg_token_validation.rb`.

---
## Tasks
- [ ] Update related settings to use the fwdproxy address
- [ ] Confirm that the code works with automated or manual tests 

## Acceptance Criteria
- [ ] Setting converted in all environments and confirmed to be working
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
**Part** of this is completed - the addition of the staging setting, pointing at `https://staging-api.va.gov/internal/auth` - is done in https://github.com/department-of-veterans-affairs/devops/pull/11626/files

This was completed by the Lighthouse team after getting agreement from Beau Grantham and Derek Brown. 

Updating that to go via forward proxy can happen via a bulk change later.
