### ISSUE TITLE
[Platform Website] Document roster requirement for AWS and SOCKS access

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#44332]
## Description
Anyone requesting SOCKS or AWS access is checked against the VFS roster or Platform roster. This requirement is not documented anywhere, so sometimes users are confused. Let's write up something for the Platform website [Request access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) page, and/or its sub-page, [Accessing Internal Tools (via SOCKS Proxy)](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy). Wording can be taken from this bot's message [here](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/pst-amt-roster-check.yml#L118-L120). See that link for links to the rosters.

## Background/context 
Requirement came from [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40655#issuecomment-1113500394).
This requirement has caused confusion, like in this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/42885#issuecomment-1170041324. People have opened support requests in Slack [like this one](https://dsva.slack.com/archives/CBU0KDSB1/p1657207853024979). A link to the docs would have resolved that quickly.

---
## Tasks
- [x] Platform website is updated as needed

## Acceptance Criteria 
- [x] New content is verified on the Platform website
- [x] Notify AMT and SRE teams that this requirement is now documented on the Platform Website so they can link to it if people ask questions.

**Comment by rmtolmach** [comment]
Docs: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page

**Comment by rmtolmach** [comment]
✅ Drafts reviewed by Oseas. 
✅ I updated these confluence pages with the changes:
* https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy
* https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools

🕙 Changes will go live on Thursday. 

✅ deleted draft pages from  [Platform Website Drafts](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).

I will close this issue when the changes are live.

**Comment by rmtolmach** [comment]
Changes are live and AMT & SRE teams notified of the updates https://dsva.slack.com/archives/CJYRZK2HH/p1659038130209179
