### ISSUE TITLE
Investigate and update the use of /oauth2 in vets-api

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44337]
## Issue Description

cc @patrickvinograd 
The `api.va.gov/oauth2` route will continue to be served by Lighthouse, and as such, will not be supported under the new `*platform-api.va.gov` domains. There are several references to the route in vets-api, some of which use the `api.va.gov` domain, while others use fwdproxy address under port 4475, which is the gateway to Lighthouse. The configured upstream for port 4475 is currently `*api.va.gov`. 

References to `*api.va.gov/oauth2` will continue to work until Lighthouse has migrated their API gateway to Apigee. To ensure that `/oauth2` route will continue to be functional after the Lighthouse migration, we should update references to use the forward proxy under port 4475. The fwdproxy port is expected to work even after the LH migration.

One complication is that the setting `Settings.lighthouse_health_immunization.access_token_url` points to the sandbox environment in dev and staging. The setting doesn't exist in sandbox. It's not (easily) possible to use a fwdproxy url in a different environment, so the options are to:
- either create a fwdproxy port to sandbox in dev and staging
- or create environment-specific API keys for dev and staging 

Here is a table to summarize the use of the `api.va.gov/oauth2` route based on the vets-api settings file in different environments:

| Setting                                         | fwdproxy 4475 | API domain | API domain matches ENV                                    |
|-------------------------------------------------|---------------|------------|-----------------------------------------------------------|
| oicd.smart_launch_url                           | YES           | NO         | n/a                                                       |
| oicd.issued_url                                 | YES           | NO         | n/a                                                       |
| oicd.opaque_clients.route                       | NO            | YES        | YES                                                       |
| lighthouse_health_immunization.access_token_url | NO            | YES         | dev --> sandbox; sandbox doesn't exist; staging --> sandbox |

---
## Tasks
- [x] Convert `oicd.opaque_clients.route` to use fwdproxy with port 4475
- [x] Investigate and resolve the Lighthouse health immunization cross-env API use and convert to fwdproxy route

## Acceptance Criteria
- [x] Settings have been updated as appropriate
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
My assertion is that we should add additional forward proxy routes in dev and staging that point to sandbox, and the mobile API should use those.

The `Settings.oidc` ones should map dev-dev, staging-staging, because those are Lighthouse using itself, so the intent is for an environment to be self contained.

The mobile app one is, from lighthouse's perspective, an external team, and external teams are supposed to use sandbox-api because that's the environment that they keep stable for external teams. And it's just happenstance that both these things are in the same Rails application.

**Comment by madebydna** [comment]
`oidc.opaque_clients.route` is not used for network request. 
`lighthouse_health_immunization.access_token_url` has been addressed in #44660
