### ISSUE TITLE
[FE] - Text inputs missing red line in error state

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#44335]
## Description
When in error state the text inputs in the validate form get their red line clipped off. This is due to having less padding in the main container at mobile sizes. Also when in error, the labels seem to have extra margin.

## Tasks
- [ ] Consult with UX on options (i.e. more padding on container, add an additional container around inputs on error, etc)
- [ ] Surface issue with design system team via the platform support slack channel.
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
Related bug ticket for DS: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1055

**Comment by brianseek** [comment]
@loripusey this has been merged and should be good to validate on stage later today or Monday

**Comment by loripusey** [comment]
will do

**Comment by loripusey** [comment]
validated, looks good!
![image](https://user-images.githubusercontent.com/86678742/179292412-92b376c7-a004-4c03-acb8-e5dd4a022fa2.png)

**Comment by brianseek** [comment]
thanks Lori! closing with validation.
