### ISSUE TITLE
[Spike] See if Amazon EKS Anywhere is a fit for local development

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#44336]
## Background/Request
_What details are necessary for understanding the specific work or request tracked by this issue?_

Recent article [Getting started with Amazon EKS Anywhere on Bare Metal](https://aws.amazon.com/blogs/containers/getting-started-with-eks-anywhere-on-bare-metal/) explains how to run on-premises Kubernetes clusters with- or without virtualization.

### Goal

Determine if a local development EKS Anywhere cluster can be setup to resemble those dev and prod EKS clusters in the AWS cloud.

### Requirements to Consider

Dev and other EKS clusters in the AWS cloud run Traefik for Kubernetes ingress controller and ArgoCD for CI/CD GitOps.

---

## Tasks
- Answer the following questions:
  - Q1. What are the steps for setting up a local development cluster of Amazon EKS Anywhere?
  - Q2. Does this local cluster of Amazon EKS Anywhere resemble the Dev environment in AWS cloud for VETS-API?

## Time Box

2 days

## Definition of Done
- [x] Tasks are complete
- [x] Research and recommendations are documented in this ticket

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of)

**Comment by ewilson-adhoc** [comment]
Putting this under the microservices playbook epic -- since if this worked this would have been useful for local development.
