### ISSUE TITLE
[FE] [BUG] "Too late for check-in" message shown when patient is in a later timezone

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44331]
## User Story
As a patient, I want to be able to use the app when my phone's timezone doesn't match the facility's timezone, so that I can check in for my appointments.

## How to reproduce

- Using staging, create an appointment in the check-in window
- Set your computer/device timezone to Atlantic Time Zone (Halifax, Canada works)

![Image from iOS.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/a44300d2-c841-456b-b2a2-38e56a0e2491)

## Tasks
- [ ] ensure check-in button is shown even if user's time is later than the facility timezone
- [ ] add test case(s)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by loripusey** [comment]
@acrollet just curious, was this something you discovered yourself or did it come to us from something that was reported?

**Comment by acrollet** [comment]
@loripusey this was reported here: https://dsva.slack.com/archives/C02UP02HHGX/p1657739770123959

**Comment by acrollet** [comment]
Confirmed that a "normal" check-in worked on staging:
![Screen Shot 2022-07-14 at 10 16 52](https://user-images.githubusercontent.com/101649/179029543-3b24abe5-4560-4c2f-a737-67eff24bf678.png)
![Screen Shot 2022-07-14 at 10 16 44](https://user-images.githubusercontent.com/101649/179029546-1384b0d6-f4c7-4bf1-825a-0b44209a230c.png)
