### ISSUE TITLE
PII Audit in GA Tracking

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#44350]
## What happened?
PII is coming through on a GA report, trying to determine where/how that is happening and resolve.  See slack chain for details:  https://dsva.slack.com/archives/CBU0KDSB1/p1657733956010719

Audit all GA event action reports to see if PII may be coming through from other sources.

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jennaouellet** [comment]
Adding in the steps I'll be taking here:

## Acceptance Criteria
- [ ] Configure or utilize an existing event and provide dataLayer to be manually pushed by dev

- [ ] QA implementation once in staging

- [ ] Delete user using the Google API 

- [ ] Modify GTM custom JavaScript tag that scrubs PII to do additional checks for incoming PII

- [ ] QA and publish updated GTM container

For checkpoint 1, I've recommended utilizing an existing event like api_call that requires no GTM configuration to get up and running for faster turnaround. If the existing events are not suitable, we will configure a new event and QA/publish. 

@michelle-dooley because we aren't currently set up with the Google API and will need to make changes to the JavaScript and QA everything thoroughly - I'd put this at an 8.

**Comment by SKasimow** [comment]
We reviewed GA further this morning and noted that the modal for session ending soon also seems to have PII data showing up in the reports from a variety of sites across VA.gov. I can share this with you if you are not seeing.

**Comment by jennaouellet** [comment]
I requested a user deletion via the Google API for the first instance we found, which can take up to 72 hours to reflect in GA. We can repeat this process for other impacted users if the user event data was indeed removed. There is a possibility that only user-specific metrics like device type/location, etc. are deleted when using the API. If that is the case, we will need to delete full days' worth of all event actions. This will not delete the events (so reporting will still reflect accurate event counts) but all event actions for the day will get redacted. I'm continuing to monitor GA to see if the API deleted the user's events and if not we will discuss options for data deletion. CC @michelle-dooley 

I've made changes to the modal click text variable so it redacts text blocks that exceed a specific character limit, since the instances of PII I found were all long text blocks.

We are QAing the change now and will publish to GTM once it's confirmed to be working as expected. CC @jonathan-epstein13

**Comment by SKasimow** [comment]
Hi @jennaouellet - just to make sure I'm following, the plan is to:

- confirm that the impacted users we found are deleted via the API
- if not all PII info is deleted you will have to look at deleting full days of event actions
- the modal click text variable change will redact text blocks going forward

Are you able to tell how long this has been occurring and the cause?

Thank you for the update! 

cc/ @Samara-Strauss @adamwhitlock1

**Comment by jennaouellet** [comment]
Hi all,

I've confirmed that we can utilize the Google API to remove users and their events without requesting deletion of an entire day of event action data. I've removed the first case we found and will continue removing users as we audit the property. 

Yesterday we published the change to GTM that will redact text blocks longer than 50 characters in the click text field for modal interactions. This will eliminate issues where the entire page contents are being passed into GA, while also preserving valid link texts. During our audit, I will adjust other components that are potentially displaying similar behavior.

I'm unsure on the cause of this, though it may be that the component isn't being used as intended based on feedback in the Slack thread. With the adjustments to GTM, the modal event can be continued to be used as it is now without risk of PII. If you'd like to keep the existing modal code and tagging, then we will not create an additional custom event.

I will send over another update once we've finished auditing and have removed other users with PII.

**Comment by Samara-Strauss** [comment]
Thank you for all of this! I am relieved to hear the PII has been removed from GA.

> I'm unsure on the cause of this, though it may be that the component isn't being used as intended based on feedback in the Slack thread. With the adjustments to GTM, the modal event can be continued to be used as it is now without risk of PII. If you'd like to keep the existing modal code and tagging, then we will not create an additional custom event.

I *think* the team would like the custom event regardless of the update to not pull in more than 50 characters worth of data to GA. Is that correct @SKasimow @adamwhitlock1?

**Comment by adamwhitlock1** [comment]
We would like to get the Custom Event set up for the Profile team, just so that we could implement some tracking outside of the standard events for behaviour in the future. Thanks!

**Comment by SKasimow** [comment]
Hi @jennaouellet - I am still seeing the original PII examples we reported. Do you have an eta on when it might all be cleared out? We want to turn the feature back on once it's ok to do so. Thanks!

**Comment by jennaouellet** [comment]
Hi @SKasimow! I'm still cleaning up PII found prior to our release. No new PII should be coming in through the click texts, and we've also created a new event you can switch to if you'd like. 

I will continue updating this ticket as we remove the existing PII.

**Comment by michelle-dooley** [comment]
@SKasimow - all known PII has been removed so we are closing this ticket but we will continue to monitor.
