### ISSUE TITLE
Gain access to Console

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44353]
## Issue Description
Each team member needs to step through getting access to the Console.

Login instructions: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2098004015/Logging+into+the+Platform+Console+-+Instructions

---
## Tasks
- [x] Review guidance on Console access
- [x] Attempt to step through process

## Acceptance Criteria
- [x] Bryan has access to Console
- [x] Taylor has access to Console
- [x] Dan has access to Console

- Nicole has access to Console (still blocked w/ general email access issues.  Will continue to pursue independently)

**Comment by twoangstroms** [comment]
I'm blocked on this at Step 1:

"If you have SOCKS proxy access, you can visit directly.
OR you can log into the CAG desktop and copy the URL into a browser there."

I do not have SOCKS proxy access, and just yesterday IT was trying to help my access CAG -- this requires the PIV card and VA.gov email address process to be completed. Currently seeing only error messages from the VA side, and their support system was down today (have an incident ticket). Will call again on Monday.

**Comment by steel36** [comment]
I made it all of the way to the point of getting onto a CAG desktop, did the LOGIN step, logged in to login.gov there, went through both checks, and then clicked "Continue".  

At that point it tells me "sorry developeraccess failed".  I tried it twice, same result.

**Comment by tayism** [comment]
I'm also getting stuck at the login.gov sign in page after using the Console website Login button.

DEVELOPERACCESS: We are sorry... Authentication failed

Perhaps due to not yet having access to the console, from the ticket I created earlier I assume. I will try again tomorrow.

**Comment by twoangstroms** [comment]
That was the farthest I got, too. I was on the phone with Ad Hoc IT and they said at that point, you have to call VA support (number on the portal page) or use the online chat… which requires a va.gov <http://va.gov/> email address. So I’m going to call again tomorrow.


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

**Comment by tayism** [comment]
I now have access.

**Comment by twoangstroms** [comment]
I found that if you get to the modal "Cannot complete your request" loop in the Citrix app (and you have to use Chrome to get to it), it's due to you account having been disabled. A call to Enterprise Service Desk (ESD) at 1-855-673-4357 can resolve that, and you just need to keep trying until the re-enabling propagates.
