### ISSUE TITLE
Upgrade ArgoCD to latest version

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#44371]
## Description

We would like to get on the latest version of ArgoCD to stay on top of things, but also use the `exec` feature that was recently included. This will allow teams to shell into pods (permissions will need to be granted, which will be created in a separate ticket) similar to how teams are able to SSH into EC2 instances

---
## Tasks
- [x] Review ArgoCD documentation to ensure no breaking changes
- [x] Upgrade ArgoCD to latest version

## Acceptance Criteria 
- [x] ArgoCD still working as intended
- [x] Infrastructure taem is able use exec terminal via GUI

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/51
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/52
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/53
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/55
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/56

**Comment by rmtolmach** [comment]
Thanks for documenting this, @oseasmoran73.

**Comment by jhouse-solvd** [comment]
Attached to [Application Hosting and Deployment] Provide developers with tools to troubleshoot in EKS #43549
