### ISSUE TITLE
Create GA Events to track DOB and SSN completion and failures

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#44383]
## Background

Need to be able to track login attempts with DOB and SSN, separately. 

Need to be able to track login successes with DOB and SSN, separately. 

## Tasks

- [x] Discuss approach to implementation with UX. Determine if we're already capturing this data for existing SSN. 
- [x] Agree on GA event names for DOB. 
- [x] Share approach with design system team via slack (include Patrick) and Shawn Adams, etc. 
- [x] Add GA events
- [x] Merge
- [x] Adjust GA CIE Custom Dashboard, if needed, to pull in new events
- [x] Add to research repo
- [x] Monitor the metrics
    - Shut of if "bad"
    - Open to everyone if "good"
- [x] Notify DS of final result

## AC

- [x] Merged with main
- [x] Verify in VA GA that events are firing, which should be available day of merge
- [x] Verify VA GA events are appearing in GA CIE Custom Dashboard, if applicable 
- [x] Notify design system team that metrics are in place ([slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1657638640123359))
- [x] Communicate performance and recommendations with DS team, [Danielle and Randi from content team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46817), Patrick and Shawn Adams, etc.
- [x] Add to research repo

**Comment by benbrasso-agile6** [comment]
@loripusey @acrollet agree we need to pull this into Sprint / In Progress?

**Comment by acrollet** [comment]
Agree, I've found an approach to use the existing api call events and update the labels to include ssn4/dob so we can split things out. Will be submitting a PR soon.

**Comment by benbrasso-agile6** [comment]
@acrollet you want to catch up on this tomorrow? FYI @loripusey

Consider event names: 

{category} / PCI-verify-DOB-start / pre-check-in
{category} / PCI-verify-DOB-fail / pre-check-in
{category} / PCI-verify-DOB-success / pre-check-in

{category} / PCI-verify-DOB-start / check-in
{category} / PCI-verify-DOB-fail / check-in
{category} / PCI-verify-DOB-success / check-in

{category} / PCI-verify-DOB-start / pre-check-in
{category} / PCI-verify-DOB-fail / pre-check-in
{category} / PCI-verify-DOB-success / pre-check-in

{category} / PCI-verify-SSN-start / pre-check-in
{category} / PCI-verify-SSN-fail / pre-check-in
{category} / PCI-verify-SSN-success / pre-check-in

{category} / PCI-verify-SSN-start / check-in
{category} / PCI-verify-SSN-fail / check-in
{category} / PCI-verify-SSN-success / check-in

{category} / PCI-verify-SSN-start / pre-check-in
{category} / PCI-verify-SSN-fail / pre-check-in
{category} / PCI-verify-SSN-success / pre-check-in

How performance would be measured: 

PCI-verify-DOB-fail / PCI-verify-DOB-start = % total fails for DOB and also look at 
PCI-verify-DOB-success / PCI-verify-DOB-start = % total successful log ins for DOB

and compare those with

PCI-verify-SSN-fail / PCI-verify-SSN-start = % total fails for SSN and also look at 
PCI-verify-SSN-success / PCI-verify-SSN-start = % total successful log ins for SSN

...for reference. 

Criteria for success:

Check hourly if fails for DOB are significantly lower than fails for SSN, then stop use and rethink.

If fails for DOB are in similar range of fails for SSN for 5-7 days, then increase usage of DOB for log in.

**Comment by loripusey** [comment]
Makes sense

**Comment by benbrasso-agile6** [comment]
@loripusey who all needs to be made aware of our plan for testing DOB from the product side? Is it just Shawn Adams or are there others? I want to get a communication out, so just thinking about who needs to be included.

**Comment by loripusey** [comment]
Shawn Adams, Jason Woodman, Dore Mobley, Patrick, Steven

**Comment by loripusey** [comment]
Are you constructing something? I was going to present it when I made the release announcement, but maybe a preemptive email would be good.

**Comment by benbrasso-agile6** [comment]
I think what I'm planning on is, 1) first communicate with just the DS folks about how we plan to track their component, and then 2) I'll give you the message to communicate to that group. 

We also need to make Danielle and Randi aware and in the know on progress from the content team. Maybe they could be included with Shawn, etc.

**Comment by benbrasso-agile6** [comment]
@loripusey  This is what I wrote to the DS Team just now. I'm going to post something similar to this ticket to let Danielle's team know - https://github.com/department-of-veterans-affairs/va.gov-team/issues/44692#issuecomment-1192685707



Hello :wave: Design System Team,

We are planning to release the memorable date component into Patient Check In next week. Our plan is to test the new memorable date component with 10% (~500 per day) of users initially, while the other 90% will verify their identification to Patient Check In using their last name, last 4 of their SSN, which does not use the memorable date component.

Our goal is to ensure that the new identify verification method (e.g., memorable date) is as successful as the existing method (e.g., last name, last 4 SSN). However, it's worth noting that this "test" is an apple to oranges comparison since the data a Veteran uses to verify will be different. But, we think the comparison is still relevant.

What we wanted to do is alert you of our planned release of the component, but also include you in the conversation about tracking success. Here's how we intend to track success and performance:

% failed of memorable date component for Pre Check In
% failed of memorable date component for Check In
% success of memorable date component for Pre Check In
% success of memorable date component for Check In

And, we'll compare those same numbers to the existing identification method for the same date range.

Our plan is to check on this data hourly. If the new memorable date component's performance is significantly less than the existing method, then we'll stop using it and evaluate next steps.

However, if the performance is in a similar range compared to the existing method for 5-7 days, then we'll expand it to more users.

We'd like to get your thoughts, feedback or questions on any of the above. Monday would be ideal. Thanks!!

**Comment by benbrasso-agile6** [comment]
Added new widget into the GA Custom Dashboard

https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/_u.dateOption=last7days/

![Screen Shot 2022-08-01 at 2.46.19 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/3dccb232-2146-47d5-91b1-b3b93358a91e)

**Comment by benbrasso-agile6** [comment]
@acrollet take a look

We are planning to release the memorable date component into Patient Check In next week. Our plan is to test the new memorable date component with 10% (~500 per day) of users initially, while the other 90% will verify their identification to Patient Check In using their last name, last 4 of their SSN, which does not use the memorable date component.

Our goal is to ensure that the new identify verification method (e.g., memorable date) is as successful as the existing method (e.g., last name, last 4 SSN). However, it's worth noting that this "test" is an apple to oranges comparison since the data a Veteran uses to verify will be different. But, we think the comparison is still relevant.

What we wanted to do is alert you of our planned release of the component, but also include you in the conversation about tracking success. Here's how we intend to track success and performance:

% failed of memorable date component for Pre Check In
% failed of memorable date component for Check In
% success of memorable date component for Pre Check In
% success of memorable date component for Check In

And, we'll compare those same numbers to the existing identification method for the same date range. From 7/27/2022 - 8/2/2022, the existing identification method resulted in the following performance: 

9% failed of memorable date component for Pre Check In
7% failed of memorable date component for Check In
90% success of memorable date component for Pre Check In
93% success of memorable date component for Check In

On the first evening (e.g., 1-2 hours of check-ins) we will monitor performance. If the memorable date component is not within 1-2% of how the existing identification method is performing, then we will stop showing the memorable date component to Veterans. 

If the memorable date component is within 1-2% of how the existing identification method is performing, then we will continue to increase usage based on the following schedule: 

8/5 10%
8/8 20%
8/9 40%
8/10 60%
8/11 80%
8/12 100%

If at any point during those days the memorable date component drops out of a 1-2% difference, then we will move the % back to 0 and discuss.

Increases will happen at approximately 530 pm EST to avoid making updates at the same time as the back-end team, which makes updates around 3-4 pm EST.

**Comment by sarahknoppA6** [comment]
cc @loripusey

**Comment by acrollet** [comment]
This plan is good by me.

**Comment by loripusey** [comment]
LGTM!

**Comment by benbrasso-agile6** [comment]
@acrollet @loripusey is someone picking up the responsibilities and monitoring on this ticket with Adrian out next week? I can of course help.

**Comment by loripusey** [comment]
What work needs to be done to get the DOB events for "validating-user" to show up in GA?
@benbrasso-agile6 @acrollet

**Comment by acrollet** [comment]
@loripusey that work is already done. @brianseek would you be willing to pick this up? I'm free most of today to sync and show you how it's set up. 🙂

**Comment by benbrasso-agile6** [comment]
Agreed. I think this ticket now is more about the day of and daily monitoring. As well as changing the % each day.

**Comment by benbrasso-agile6** [comment]
8/14-8/20

Pre check in 

29314 started 
27034 success (92%)
2107 failed (7%)

Day of 

9701 started 
9144 success (94%)
541 failed (6%)

**Comment by benbrasso-agile6** [comment]
@niradatta1 @kristenmcconnell 

Aug 19 - Aug 25 for SSN 

Pre check in started 31,226 total events
Pre check in success 27,980 total events (90%)
Pre check in failed 3,060 total events (10%)

Day of started 9,468 total events 
Day of success 8,701 total events (92%)
Day of failed 759 total events (8%)

**Comment by benbrasso-agile6** [comment]
9/6

**Date of Birth**

Pre check in started 132
Pre check in success 110 (83%)
Pre check in failed 20 (15%)

(Day of check in looks to be our testing potentially)
Day of started 12
Day of success 12 (100%)

**SSN**

Pre check in started 6,972
Pre check in success 6,428 (92%)
Pre check in failed 514 (7%)

Day of started 1,992
Day of success 1,883 (95%)
Day of failed 102 (5%)

**Takeaways**

- DOB successful attempts were 9% lower than SSN (for pre check in)
- DOB failed attempts were 8% higher than SSN (for pre check in)
- Continue with 10% of Veterans for today and continue monitoring with a larger volume of Veterans

**Comment by benbrasso-agile6** [comment]
9/7 (as of 12:52pm ET)

Note: GA has some lag time in compiling this data

**SSN**

Pre check in started 3,276
Pre check in success 3,053 (93%)
Pre check in failed 202 (6%)

Day of started 1,088
Day of success 1,032 (95%)
Day of failed 51 (5%)

**DOB**

Pre check in started 658
Pre check in success 338 (51%)
Pre check in failed 309 (47%)

Day of started 134
Day of success 122 (91%)
Day of failed 11  (8%)

DOB success and failures for pre-check-in today does not look great, compared to SSN. Will provide another update in an hour or so. We may want to brainstorm a response/plan of action if it does not improve. E.g., whether to continue as is or make changes. Worth noting, day of for DOB looks great.

**Comment by benbrasso-agile6** [comment]
[Direct link to GA to view ID Authentication success and failures](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20220920&_u.date01=20220920&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=-validating-user-/)

**Comment by benbrasso-agile6** [comment]
9/21

DOB

Pre check in (16% failed, 83% success)

436 
365 success (84%)
69 failed (16%)

Day of 

108
89 success (82%)
18 failed (17%)

SSN (7% failed, 93% success)

Pre check in 

6600
6121 success (93%)
463 failed (7%)

Day of 

2008
1879 success (94%)
124 failed (6%)

Continue with 10% for additional day.

**Comment by benbrasso-agile6** [comment]
9/22


DOB (51% success, 47% failed) 

Pre check in 

792 started
457 success (58%)
313 failed (40%)

Day of 

455 started
175 success (38%)
275 failed (60%)

SSN (92% success, 7% failed) 

Pre check in 

4457 started
4078 success (91%)
350 failed (8%)

Day of 

1864 started
1765 success (95%)
96 failed (5%)

Continue with 10% over the weekend.

**Comment by benbrasso-agile6** [comment]
Update: We identified a couple validation bugs (in memorable date component or our implementation or both) that could explain the failure rate. We're turning the feature off for now and are investigating. Will follow up.

**Comment by loripusey** [comment]
Closing this; now that the date component bugs have been addressed, let's track the metrics in this [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47345)

**Comment by benbrasso-agile6** [comment]
10/11

![Screen Shot 2022-10-12 at 9.36.30 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/5b316fd2-a7f1-4e9a-80b1-4586c8175eed)

**Comment by benbrasso-agile6** [comment]
10/12

![Screen Shot 2022-10-13 at 9.14.36 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/64eca36f-1e02-4801-8d2e-984874439049)

**Comment by benbrasso-agile6** [comment]
10/13

![Screen Shot 2022-10-14 at 9.23.44 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/8f685344-8881-44b3-bd27-824fe696ab61)

**Comment by benbrasso-agile6** [comment]
@loripusey @acrollet suggestion:

Monday 50%
Tuesday 70%
Wednesday 90%
Thursday 100%

**Comment by loripusey** [comment]
sounds like a good plan

**Comment by benbrasso-agile6** [comment]
10/14-16

![Screen Shot 2022-10-17 at 9.15.05 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/24c4a091-29e2-4698-b8f5-d22b1c88ed83)

**Comment by benbrasso-agile6** [comment]
10/7

![Screen Shot 2022-10-18 at 9.28.00 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/24591334-a6b4-4b60-8236-71fbbdf51585)

**Comment by benbrasso-agile6** [comment]
@loripusey I will need to commit this to the VA research repo next sprint. Maybe re-mark this as a 2. 

CC @kristenmcconnell

**Comment by benbrasso-agile6** [comment]
10/18 

![Screen Shot 2022-10-19 at 9.21.04 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/58162ec8-6e77-4068-9427-81a80d7f8f6e)

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/188

**Comment by benbrasso-agile6** [comment]
Added to research repo and messaged in Slack thread. Closing
