### ISSUE TITLE
VAEC - Migrate vets.gov to VA Enterprise Cloud

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#444]
## User Story and Problem Statement
As a VSP Ops team member, I need to move our current setup to the VAEC, so that we are in aliment with VA policy. 

### High Level User Story/ies or Description: 
We need to move the vets.gov hosting from our current hosting model with our own networking and CSR's to connect back to the VA network into the VA's Transit VPC model (also called VAEC and VA Enterprise Cloud). 

### Pain Points being addressed:
- Addressing concerns from the VA
- Everything is on the VAEC

## VSP OKRs 
O3: Stability and resiliency of the Platform's systems and teams continue to improve.	

## Goals
Move everything to the VAEC

## Measuring Success (KRs/KPIs)
- [VSP KR] Increase in customer NPS

**Comment by ricetj** [comment]
(May 14 2018)# VAEC migration risks

| Risks | Impact | Mitigation |
| --- | --- | --- |
| Package Installations | High | |
| Run-time OperationalAPI Interactions | | |
| Ability to Use S3 Endpoints | | |
| Ability to Expose Sentry and Grafana to Team | | |
| Jenkins Setup and Capabilities | | |
| Access to Review Instances | Low | |
| Cutover Risk | | |
| Ability to Use AWS CloudWatch Logs | | |

## Package Installation

An important difference between VAEC and the old model that we know of is that machines in VAEC have no Internet access outside of what's provided through the TIC. This introduces a bit of unknown into the project because we don't know for certain what package/source repositories will be blocked up-front. A partial list of services we are concerned about accessing:

- rubygems
- sidekiq enterprise repo
- Amazon Linux repos
- EPEL
- GitHub -- this has a decently large list of API calls
- Dockerhub
- ClamAV updates
- CVE lookups during CI runs
- npm
- bintray (for Kong install)
- Jenkins yum repo

### Package Installation Mitigation

A possible mitigation to this could be to use a public bake subnet that's outside of this and deploy those instances using AMI's.

## Run-time Operational API Interactions

- PagerDuty
- AWS
- Slack
- ClamvAV updates (purposely duplicated as this is a frequently-updated component)

## Ability to Use S3 Endpoints

The Vets-API and deployment tooling use S3 for a lot of things. If we were to lose the ability to do S3 endpoints and have to route all this traffic out through the TIC, that would introduce a really large amount of latency and require significant effort to re-design.

## Ability to Expose Sentry and Grafana to Team

Sentry and Grafana are exposed to the team via a SOCKS proxy that we run. If we are unable to use this method going forward, we'll need to re-design how access to these tools work for developers.

We can possibly expose these via the TIC. A concern that I'd have about exposing Jenkins and Sentry in particular is that they are quite sensitive. Jenkins controls production environments and Sentry may contain PII. My biggest concern is keeping these tools up-to-date and avoiding security issues caused by bad configuration.

### Grafana and Sentry Mitigation

A possible mitigation to the security concerns could be using something like the [ngx-oauth plugin](https://github.com/jirutka/ngx-oauth) to keep authentication away from being an application-level concern for these tools.

## Jenkins Setup and Capabilities

The utility VPC today is able to "peer" with other VPC's to allow Jenkins to SSH into machines running in dev, staging, and production to perform maintenance tasks on our behalf. As the new spoke VPC setup is understood, we will no longer have this ability to do so directly. The BRD tooling is designed to accommodate some level of this, but some pieces will have to be re-designed. Namely, the ability to update a configuration in place goes away (something we rely upon heavily for monitoring and revproxy setup in dev).

We also will lose access to do some of the security checks directly that we normally do every day to ensure we are always in a passing state for Nessus scans.

### Jenkins Setup Mitigation

I know that Appeals has been using a Jenkins instance in each envioronment (dev, staging, prod). Passing information between these instances could potentially be challenging and definitely is a bit of a re-design of what we do today.

## Access to Review Instances

Access to review instances is granted today by the SOCKS proxy. While we have talked about exposing these publicly and have buy-in from a lot of people, this would have to be done on a tight timeline with other all of the other changes.

## Cutover Risk

A lot of the concern in this section is around whether or not we have the ability to peer the old VPC's with the new ones we stand up. If we cannot launch application instances in the new VPC that reach back to the old VPC to access the production database, this migration becomes a large "cutover" event which carries a much larger risk.

Having the ability to peer the VPC's temporarily will give us the flexibility to isolate changes and make this migration happen in smaller, more easily test-able chunks.

## Ability to Use AWS CloudWatch Logs

CloudWatch Logs flow will now need to cross through the TIC as VPC Endpoints for this service is not available in GovCloud yet. There's a good amount of risk here that this could get flagged if it has content that the TIC does not like.

**Comment by ricetj** [comment]
(May 15 2018) # Open Questions

We have a setup of what I think are some pretty fundamental questions as we go through the discovery phase of this migration. Answering these will drive a good amount of the risk assessment above on the project as a whole.

- Can we still use the VPC Endpoints feature for S3 access? Yes
- How does access to Sentry and Grafana work in Appeals today? Do you expose them publicly? If so, do they become subject to additional security and compliance processes? Both have an intranet URL; 
- Your Strongswan implementation exists to support access between old VPCs and the new spoke VPC's during the migration process, correct? What is the status on this? We believe this to be pivotal to a lot of the cutover risks. -- "temporary", but that's how things go in tech and government. Investigating Openswan which has better support on AL.
- Can we do a utility network the same way we do today? If not, where do we run these "utility"-like services like Jenkins and cloudwatch-exporter? Where does Appeals keep these services? Yes, but we'd need to do VPN or have no internet.
- Currently, Nessus is only in staging on an instance deployed by us. Will there be a need for us to continue to manage an agent on our networks? Will these networking changes open up all environments for scanning? -- Unknown. Ideal is Nessus centrally, but not there today. No Nessus scanning in VAEC today. Keep using old Nessus box for ATO.
- Would it be possible for us to continue using a public subnet (with an IGW) to build bake instances since they do not actually run a service? No
- What does Appeals use for centralized logging? Has it been tested in the Spoke VPC? AWS CloudWatch Logs; does flow through TIC
- Since this is a contract issue, will we still have access to the test GovCloud account? what about the commercial account where we run the external monitoring? Unkown
- Does access to everything in VAEC need to use PIV authentication? If so, how do we bring on new developers without a long wait? -- VPN access being forced creates the requirement anyway. SSH and AWS console auth are both in question. Not triggered by migration to VAEC.
- Currently, we use jumpboxes to access our instances and internal tools. Will they need to go away? If so, how will we be able to access our systems after the change?
- Can we get access to VA DNS from our spokes? We do a lot of scary trickery using HAProxy on our "forward proxy" instances for our backend VA connections because we currently can't access the internal VA DNS, it would be great to get access to that so we could simplify backend connections. -- Yes, but we may not want to use it. ESCCB's tied to IP addresses, recommend either hard-code hostnames to IP or custom DNS. Use it for validation, but not rely on it for production access.
- GovCloud now has 3 AZ's. Any reason to not utilize all of them as part of this migration? All good with 3.

**Comment by ricetj** [comment]
(Jun 13 2018)
Upload of migration plan doc that we have so far:

# Vets.gov migration to VAEC plan

## Preparation

- ~Create new VPC's with CIDR blocks from VA~
- ~Peer VPC's with VA hub~
- ~Setup new Forward Proxies in new VPC's and verify connectivity~
- ~File ESCCB requests for backends we connect with - Craig working on this~
- ~Decide on hosting for revproxy - ALB - Wyatt to validate, if not fall back to ELB~
- ~File ESCCB request for revproxy changes~
- Decide on utility access
- ~CSR license renewal~

## Migrate backend VA traffic to Direct Connect

- ~Establish monitoring criteria for cutover~
- ~Stand up new Forward Proxies~
- ~Cut over services one at a time as we establish - links and test~
- ~Tear down old Forward Proxies~

## Migrate user facing traffic to Direct Connect

- ~Establish monitoring criteria for cutover~
- ~Discovery on using ELB with Revproxies~
- ~Stand up new Reverse Proxies to test connectivity~
  - S3
  - Vets-app
  - GIDS
  - Sentry
  - Jenkins
  - API Gateway
- ~Request NSOC to change backend IP's to new Revproxies~
- ~Tear down old Reverse Proxies~

## Everything Else

### apps -- vets-api, GIDS, Sentry, Grafana

- GIDS is similar to vets-api, but might be a good one to go first
- Discovery on options for databases move to new VPC
  - Redis and Postgres - the harder pieces in this category
  - options for cutover -- snapshot and stand up new, or replicate and promote to primary
  - can we put site into read-only mode?
- Stand up new ELB and deploy ASG's - do we want to change to ALB?
- Test, cutover backend in revproxy
- Tear down old stuff

### Internal tool access

These two are big unknowns for us today -- we may or may not be able to still have jumpboxes, battle is being fought by Alan and Aaron

- Jumpbox - check in with Alan on status
- SOCKS proxy

- Prometheus - decide on what to do with the utility (GAE, CWE, Blackbox)
- Jenkins - single master with swarm nodes in each environment; separate jenkinss in each environment - deploy into dev and use peering -- find out whether or not this is going to violate some policy
- Sentry - dev, staging, prod instances
- Grafana - put into dev

**Comment by ricetj** [comment]
(June 20 2018)
Open questions that we have:

- [ ] where are we at with jumpbox progress within VA?
- [ ] is there any policy stipulating that we can't have Jenkins master in dev or staging that reaches into production to manage machines? Similarly, can we use one central Grafana that accesses all the Prometheii?
- [ ] any reason that we can't go with ALB's from the TIC (F5)?

**Comment by jhouse-solvd** [comment]
@ricetj - Still relevant?

**Comment by ricetj** [comment]
> @ricetj - Still relevant?

something that needs to be done as part of the infra recommit's migration.
