### ISSUE TITLE
[Design] - Update mock-ups in address validation alerts

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#44407]
**Background**

In 2021, we proposed improvements to the address validation UX ([ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30258) and [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-validation/designs/2021-alert-updates/README.md)).

We decided to hold off on this work once we realized the modal-on-modal UX a user could encounter with the address change modal feature.  

Since we don't have a timeline on exploring a long term solution, we should still update the content.  There's also some accessibility issues we need to address (buttons that look like links).

We don't need to have the content reviewed again since nothing has changed since our last content review of this work

**Tasks**

- [x] In Sketch, update the address validation mock-ups with warning alerts to use the copy from [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-validation/designs/2021-alert-updates/README.md) (which is in Sketch too)
- [x] Make sure there are no buttons that look like links in the alerts
- [x] Let PM know work is ready for FE

**Comment by andaleliz** [comment]
@SKasimow this is complete and ready for FE.  Their task will be to update the heading and body copy in the current alerts for 4 address validation use cases:

1. Suggested address found
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/rbJ5V77)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/4a3Wp3q)

2. Address not found, no suggestion found
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/nRj5oKd)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/3OrW1bw)

3. Missing unit number
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/qeJ4aVV)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WKmL09n)

4. Bad unit number
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/Jn9jQMe)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/QbJeZR7)


One thing to note is that we still have an accessibility violation in place for all of these use cases - there is an "Edit address" button under the user-entered address, which looks like a link instead of a button.

Addressing that is out of scope for this ticket, and will be part of the larger effort of finding a long term solution for address validation + address change messaging. I think it would be great to track how many people click those "Edit address" links that look like buttons so we can figure out whether or not people are actually using them.

Currently, they have the same GA event label as the main edit button, `Profile - Edit Link - Mailing Address`. I wonder if we can update the label so we can distinguish these links from the main edit button.  That would be a FE task. Maybe we can call it `Profile - Validation Edit Link - Mailing Address`?  

FYI @adamwhitlock1 

Design work is complete, so closing this one out.

**Comment by SKasimow** [comment]
Thanks - I'll open a ticket for FE work and add to backlog/sprint planning.
