### ISSUE TITLE
Remove Mikki from Collaboration Cycle documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44402]
## User Story
As a VFS team member, I want to be able to rely on the point of contacts listed on Platform Website so that I know I'm contacting the right people.

Assignee: @allison0034 
Peer Reviewer: @seanasewell 

## Description
Mikki Northuis will have a new position with OCTO starting in July and won't be supporting Collaboration Cycle the same way that she was previously. We need to remove her name from our guidance.

Known instances of Mikki's name:

- [Contact Us page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
- DraftingTemplate

## Tasks
- [x] Remove Mikki from known instances
- [x] Review other Platform Website and/or Confluence documentation to see if Mikki's name is listed elsewhere
- [x] If identified elsewhere, document artifact above and ensure Mikki's name is removed.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Mikki Northuis has been removed from Collaboration Cycle documentation

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@seanasewell please review [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)

**Comment by seanasewell** [comment]
@allison0034 I reviewed the Contact Us page. Looks good!
