### ISSUE TITLE
Convert `Telephone` to `va-telephone`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#44400]
## Background
We are using the `Telephone` react component in the `AppealHelpSidebar` component. We should be using the `va-telephone` web-component instead

## Considerations
The linter option to automatically migrate the `Telephone` component doesn't convert the vanity part of the pattern properly. We need to make sure that we use the `vanity` property, which should be set to `VETS`

## Tasks
- [x] Convert `Telephone` component to `va-telephone`

## Acceptance Criteria
- [x] `Telephone` component is updated to `va-telephone`
- [x] Vanity is still being used
