### ISSUE TITLE
Update documents on Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44404]
## Issue Description
The stakeholder for the [Print your VA Welcome Kit](https://www.va.gov/welcome-kit/) has uploaded some revised PDFs into Drupal and needs us to update the links on the page. 

Our Welcome Kit page is different from our other pages where we point to PDFs because we host these within Drupal in the assets folder. You'll notice the links look different with an icon. VEO doesn't have editing privileges in Drupal so we still need to make the page revisions for them. 

The new PDFs that we need to change links to are:

“Your VA Kit in black and white”
“Your VA kit in color”
“Get started with mental health services”
“Get started with health services for women Veterans”

Here are directions for making updates to the page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/making-updates-to-welcome-kit.md

## Tasks
- [ ] Update PDF links
- [ ] Review changes (Megan)
- [ ] Publish (Megan)
- [ ] Alert stakeholder that changes are live (Randi)

## Acceptance Criteria
- [ ] New PDF links are live on the site

**Comment by RLHecht** [comment]
I uploaded the new PDFs and added them to the page. We need to publish these on Monday since the changes have to do with the Veterans Crisis Line. @megzehn Can you please look at this on Monday morning and publish? The only difference is the 4 links mentioned above. Thanks!

**Comment by megzehn** [comment]
reviewed and published - thanks @RLHecht!
