### ISSUE TITLE
[FE][a11y] VoiceOver reads addresses twice before continuing

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#44418]
When navigating the application using VoiceOver:
- When VoiceOver is automatically reading the page, it reads the entire address twice (once per line of the address)
- When manually navigating through the page using VoiceOver and arrow keys, the first line of the address takes two arrow presses to move past.
  
## Tasks
- [ ] Determine the cause of this behaviour
- [ ] Implement a fix so that behaviour no longer occurs
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Addresses are read only once by VoiceOver
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
