### ISSUE TITLE
[ArgoCD] Grant permissions to resources using Github Teams

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#44415]
## Description

As we continue to move to eks, one of the main tools being used is ArgoCD.  In order to give developers the proper insight into their applications, they will need to access Argo and its resources.  Along with this comes the responsibility of our team to define the appropriate projects and permissions structure.

Knowing the challenges and downfalls we face with our current infrastructure, this is a great opportunity to take on a new approach compared to how it was done in BRD. Rather than managing by team, we will manage by application.  

[Slack](https://dsva.slack.com/archives/CTYQL39FE/p1657830740267929) for additional details from thread

From a hierarchy perspective, the application will be the highest. Each application will have their respective github teams per environment and role, such as `vetsapi-dev-ro` and `vetsapi-dev-rw`.

When the admin of the team submits an onboarding request the following will occur:
- Infrastructure team:
  - Create a new Github Team per cluster per role
  - Assigns admin to the new team
  - Infra ties back the GitHub team to the appropriate project and permissions in ArgoCD

The requester will then be responsible for adding teams/members to this parent team once infrastructure has onboarded the application.  If these GitHub teams can be adopted across all of our applications and resources it should make access management much more transparent 

## Tasks
- [x] make `autosync_enabled` `true` by default (possibly in the GH action) unless explicitely `false` in [vsp-infra-argocd/blob/main/chart/values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml#L4) - accounted for in https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/.github/utils/reorg_projects.py#L14
- [x] Create a github action to add a project from [vsp-infra-argocd/blob/main/chart/values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml#L4) to [vsp-infra-application-manifests/blob/main/apps/argocd-apps/dev/values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/argocd-apps/dev/values.yaml) https://github.com/department-of-veterans-affairs/va.gov-team/issues/45098 - resolved by https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/.github/workflows/add_project_to_manifest.yaml

## Acceptance Criteria
- [x] There is a read-only (RO) GitHub team for a given application 
- [x] There is a read-write (RW) GitHub team for a given application 
- [x] A user in the RO team can see all of the applications running in ArgoCD
- [x] A user in the RW team can 
  - [x] perform RO operations 
  - [x] execute a terminal/shell into the application

**Comment by jhouse-solvd** [comment]
In a conversation with @ph-One on 8/1, we decided that this is in a good MVP state. However, there should be a follow-up task to validate this work. We think that Vets-API could be a good candidate.

**Comment by ph-One** [comment]
Creating follow-on task for removing default readonly. Only makes sense to change the default policy in a separate story.
