### ISSUE TITLE
Issue connecting to Test DMC from Staging fwdproxy

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44429]
## Who is the devops resource on your team?

@ScottyRJames 

## Description
Our team is working on downgrading our connection to the DMC external service in staging from their preprod environment to their test environment per their request and running into issues from the staging specific environment (dev connection works)

PR that made transition: https://github.com/department-of-veterans-affairs/devops/pull/11577

## Technical notes
When I ssh into the dev fwdproxy I'm able to get a successful connection

```
$ curl -v gateway.test.dmc.va.gov:8443
* Rebuilt URL to: gateway.test.dmc.va.gov:8443/
*   Trying 10.225.84.179...
* TCP_NODELAY set
* Connected to gateway.test.dmc.va.gov (10.225.84.179) port 8443 (#0)
> GET / HTTP/1.1
> Host: gateway.test.dmc.va.gov:8443
> User-Agent: curl/7.61.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host gateway.test.dmc.va.gov left intact
curl: (52) Empty reply from server
```

But when I ssh into the staging fwdproxy the connection times out to the same endpoint

```
$ curl -v gateway.test.dmc.va.gov:8443
* Rebuilt URL to: gateway.test.dmc.va.gov:8443/
*   Trying 10.225.84.179...
* TCP_NODELAY set
* connect to 10.225.84.179 port 8443 failed: Connection timed out
* Failed to connect to gateway.test.dmc.va.gov port 8443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to gateway.test.dmc.va.gov port 8443: Connection timed out
```

---
## Tasks
- [ ] Need assistance understanding why this connection refuses in the staging environment

## Acceptance Criteria 
- [ ] Our application is able to be connected to Test DMC from Dev and Staging

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by zachclarity** [comment]
Issue is not on our end.   Research showed:  [Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1657893196554389)

Staging fwdproxy has connectivity to this server as shown by the traceroute.  There is likely something blocking the http request on their end.
The -I flag for traceroute forces it to use icmp which clearly isn’t getting blocked (edited) 




[Matt Leclerc](https://app.slack.com/team/U01JU1PATRN)
  [11 minutes ago](https://dsva.slack.com/archives/CBU0KDSB1/p1657899314183459?thread_ts=1657893196.554389&cid=CBU0KDSB1)
given similar configurations between forward proxy in dev and staging there really isn’t anything different between the two aside from them living in different vpcs


[Scott James](https://app.slack.com/team/U02ES294HFZ)
  [< 1 minute ago](https://dsva.slack.com/archives/CBU0KDSB1/p1657899954882219?thread_ts=1657893196.554389&cid=CBU0KDSB1)
Thank you for checking on this 
[@matt leclerc](https://dsva.slack.com/team/U01JU1PATRN)
! I suspected it might be on their configuration.  I'll follow up with their engineers
