### ISSUE TITLE
[FE] Implement vista RPC to allow resetting demographics

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44431]
## User Story
As a CIE team member, I want to reset demographics confirmations so that I can test the deomgraphics confirmation screen on staging without waiting 7 days.

## Background

Clinician workflow retrieves the latest demographics confirmation timestamp from VistA, so even if confirmations are reset in CW, the most recent timestamp is returned by VistA when initiating checkin, and we can't see the demographics confirmations page. @shanemelliott [has provided RPCs](https://dsva.slack.com/archives/C02G6AB3ZRS/p1657832743405499) to allow setting this in VistA

## Tasks
- [x] Update staging tool to call VistA as well as CW for demographics confirmations resets
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] After resetting demographics confirmations in the staging tool, the demographics confirmation screen is shown while checking in
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
completed and released.
