### ISSUE TITLE
Design | Profile | Contact Info User Flow

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44459]
## Background

We will be creating user flows that depict the screens and logic used for our features/functionality. This ticket is for the creation of a user flow in support of the "contact info" feature.

## Tasks
- [ ] Create a wireframe depicting user journey for Contact Info including successfully/unsuccessfully updating mailing  address/home address and phone number information.

## Acceptance Criteria
- [ ] Review wireframe with PO and PM 
- [ ] Walk through with team at a stand-up
- [ ] Add to sketch file

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Close as dupe to Contact Info ticket
