### ISSUE TITLE
Midpoint Review [Auth Exp My VA, Payment Info section v2 (round 2)]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#44469]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [x] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [X] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [ ] Product outline: [see "V2: updating payments and debts to address usability issues (May 2022 - current)"](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#v2-updating-payments-and-debts-to-address-usability-issues-may-2022---current). _Please note this our second midpoint review on this feature. Our new designs incorporate the "must" feedback from our first midpoint review, documented in #43068._
- [ ] Finalized design prototype or mockup: [desktop](https://www.sketch.com/s/5b39a70d-f5f1-421f-b2d6-f988cc56d7c3/prototype/a/C420F965-7F88-4A6E-A886-36385E9B7C82), [mobile](https://www.sketch.com/s/5b39a70d-f5f1-421f-b2d6-f988cc56d7c3/prototype/a/A4FB6758-495D-4468-95CE-9876FF97782C)
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/research-plan.md)
- [ ] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/conversation-guide.md)

### Content artifacts 

- [x] Your product’s content source of truth (see design links above)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable) - NA
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) [Payment info v2 test cases -- WIP](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md#my-va---benefit-payments-and-debts-v2-use-cases-and-users----wipdraft)

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by ajakabcin** [comment]
Please note this is our second midpoint review on this feature. The updated designs (links coming soon) address all the "must" feedback shared with the team during our first review. Ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43068).

**Comment by CherylEvans** [comment]
No Content FB at this time.  Looks great!

**Comment by jimuhh** [comment]
No IA feedback at this time. Thank you for your work on this!

**Comment by shiragoodman** [comment]
Meeting Recording:
https://oddball-io.zoom.us/rec/share/s1ByNJ8plaJBhKXk3ea6hvMpriVKQdYcvzCOigB8cKrBJtuNCQNlx79R6UQai_c.JsHDhon6Fwv6X-s7

Access Passcode: 01M&W?&+

**Comment by ajakabcin** [comment]
Closing out - no remaining open issues
