### ISSUE TITLE
Refine Attendees section of Platform Website

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#44467]
## User Story
As a VFS team member, I want to understand who I should invite to Collaboration Cycle meetings so that I can ensure necessary members of my team attend.

Assignee: @briandeconinck 
Peer Reviewer: @claytonzook 

## Description
The Attendees sections of each touchpoint on Platform Website break VFS participants into two sections; required and when applicable.
We also already invite some people listed in their section already, i.e. OCTO-DE Design lead in Midpoint Review.
This is not clear and can be confusing to VFS teams. The VFS Attendees section should state:

1. Who from VFS teams should be included in the touchpoint
2. That it is the VFS teams responsibility to ensure those folks are invited

We no longer want to note "Optional" or "when applicable"
We can use [Analytics Request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782120453/Analytics+request#Attendees) as an example.

For Platform Attendees, we also want to remove "(when applicable)" as it is not valuable information.

## Impacted Artifacts
[Design Intent Attendees](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent#Attendees)
[Midpoint Review Attendees](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review)
[Staging Review Attendees](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review#Attendees)

**[Draft edits for all three pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2308440106/Draft+Brian+-+Touchpoint+Attendees)**

## Tasks
- [x] Determine best way to communicate VFS attendees
For Design Intent, Midpoint Review and Staging Review:
   - [x] Revise Attendees section to clearly list VFS participants
   - [x] Remove any duplicates that we are already inviting
   - [x] Remove all references to "(when applicable)" and "(optional)"
   - [x] Note that it is the VFS teams responsibility to include their team members to the touchpoint

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams are able to easily understand who should attend touchpoint meetings
- [x] VFS teams understand that it is their responsibility to invite their team and any other SMEs supporting their team

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
@claytonzook This is ready for peer review. Two quick notes:
- Rather than creating three draft pages for the three touchpoints, I've just created one page containing the three sections being edited for this issue. That seemed easier/tidier to me.
- I've removed mentions of analytics, who don't participate in these touchpoints and have their own touchpoint. I'm assuming they were left over from previous iterations of the collab cycle but maybe Shira or Chase can confirm when they're back.

**Comment by claytonzook** [comment]
@briandeconinck Overall looks good! I do have a point for further consideration that I marked as a comment in Confluence

**Comment by briandeconinck** [comment]
@claytonzook I reorganized the Design Intent section a bit based on your feedback. Thoughts?

**Comment by briandeconinck** [comment]
@claytonzook The attendee sections are now updated on the live pages in Confluence (will be live on Platform website after the next publishing cycle). Do you mind taking a quick look to verify I didn't have any copy/paste catastrophes?

- Design Intent Attendees
- Midpoint Review Attendees
- Staging Review Attendees

**Comment by briandeconinck** [comment]
Noting here that @claytonzook gave his 👍 in Slack this morning. Closing as complete!

**Comment by briandeconinck** [comment]
@shiragoodman forgot to tag you on this, this one is closed as of Monday afternoon
