### ISSUE TITLE
Test process for creating a confluence page and publishing it into Platform Website

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44477]
# Description
Given that the product directory will be hosted in the Platform Website, we need to understand where we will publish the directory to, from what Confluence space it will be published, what the product directory looks like when rendered in Scroll Viewport, and what the publishing schedule will be.

# Tasks
- [x] Work with content and IA team to determine from where in Confluence we should publish the product directory 
- [x] Work with content and IA team to determine where we should publish the product directory to (given the IA of the platform website)
- [x] Work with content and IA team to define a publishing schedule for product directory. Best case scenario for us is that Scroll Viewport publishes our updated Confluence document each time it is updated. Minimal acceptable scenario for us is that the product directory is published once per day.
- [x] Verify that the product directory is rendered correctly by Scroll Viewport and that it is no less usable than when it is rendered Confluence

# Acceptance Criteria
- [x] Content and IA has approved the Confluence space from which product directory will be published
- [x] Content and IA has approved the location to which the product directory is published in Platform Website
- [x] If there are updates to the product directory then they are published to the Platform Website at least once per day 
- [x] Product directory usability is at least as good in Scroll Viewport as it is in Confluence

**Comment by rsmithadhoc** [comment]
- Set up a test Confluence with Scroll Viewport trial, table of contents and product pages look good.
![image.png](https://images.zenhubusercontent.com/62222b1c8a8a2d232882a99b/b3c90ad2-3524-4233-bb96-b077feba7936)
![image.png](https://images.zenhubusercontent.com/62222b1c8a8a2d232882a99b/2fba89c4-7dd9-4c70-b163-e769ae7d3f1c)
- The pages are ready to go into the Confluence space for the platform website. However, I noticed that there are failing unit tests (likely due to recent format changes), which will prevent the auto-publish since those need to pass for it to publish. I will be looking into getting these fixed.

**Comment by rsmithadhoc** [comment]
- Publishing to https://vfs.atlassian.net/wiki/spaces/GS/pages/2294120662/VFS+Product+Directory
- The only thing left is the Scroll Viewport deployment to https://depo-platform-documentation.scrollhelp.site/getting-started/, which will happen this afternoon.
- Going to set this for review for now since the pages were tested in Scroll Viewport. If there's any adjustments from the content team, I'll move back to in progress.

**Comment by pjhill** [comment]
This has changed based on feedback from other Platform teams and stakeholders. But, the original scope of this work was completed as it was specified.
