### ISSUE TITLE
[FE] Automatically check for hard-coded strings in codebase

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44476]
## Background

We need to be certain that all text shown to users is run through the translation system so that it can be translated to alternate languages. It would be good to have a check run on CI to help us ensure we don't miss anything when adding new code.

## Implementation

It's worth looking for existing github actions, also there may be helpful pointers in the https://github.com/lokalise/i18n-ally codebase.

## Tasks
- [ ] Create automated check for hard-coded strings
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] A CI tasks detects hard-coded strings and blocks merges when it finds any
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
Platform team mentioned that it could be possible to have our own app specific commit hooks once we roll out yarn workspaces. For now I'm going to close this ticket with the updates to our ticket template and we can revisit with our workspaces setup.
