### ISSUE TITLE
Q3 2022 QAS - Discovery: QA on VA.gov

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44486]
## Problem Statement 
There is currently no clear and comprehensive understanding of the state of QA on the platform, which creates confusion around what issues or pain points are causing the most frustration, and makes it difficult to prioritize what work would have the biggest positive impact on VFS teams and their work.

How might we gain a better understanding of QA on the platform, and have a better awareness of the pain points that hinder the work of VFS teams?

## Hypothesis or Bet
We believe that by conducting a thorough discovery effort, we will have better insight into how teams are conducting QA on the platform currently, what limitations and frustrations are holding them back, and use this to inform a better approach to QA on the platform.

## We will know we're done when... ("Definition of Done")
* Define personas for user journeys through the QA process
* Create comparative user journey maps for top persona(s) (Which compare 'current' user journeys to 'ideal' user journeys)
* A distilled and synthesized list of pain points that is surfaced by this discovery

## Known Blockers/Dependencies 
_No known blockers_

## Projected Launch Date
Q3 2022

- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)
