### ISSUE TITLE
[FE] 1010EZ - Add Sentry Logging of Veteran Name, SSN, DOB to Transform Submit when Values are Missing

### ISSUE THREAD

**Issue by lzapson** [department-of-veterans-affairs/va.gov-team#44489]
## Issue Description
Add Sentry vets-website Logging of Veteran Name, SSN, DOB to Transform Submit when Values are Missing; as we are still seeing a small number of these issues on the vets-api side. This can be used to see if we can match the issues seen on vets-api with vets-website.

## Tasks
- [x]  Add sentry logging to transform submit to the hca form.
- [x]  remove sentry logging from facility page.

## Acceptance Criteria
- [ ] validate Sentry vets-website is logging form information with missing Veteran Name, SSN or DOB.
