### ISSUE TITLE
[DOC] Internal Documentation for Reverse Proxy

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#44484]
## Description
As Platform-Infrastructure team members, we need an internal document that explains the policies, requirements, and processes around Reverse Proxy deployments

## Background/context 
- https://dsva.slack.com/archives/C03KT515C0H/p1657895772196909

## Technical notes
- Not subject to OOB deployment process
- Currently deployed via Jenkins

---
## Tasks
- [ ] Internal documentation needed for Reverse Proxy deployment specifics

## Acceptance Criteria 
- [ ] Document created for internal use that discusses Reverse Proxy specifics and deployment process

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
