### ISSUE TITLE
Develop format for survey to send to teams (to fill in info)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44495]
## Issue Description
Develop a format that we could disseminate to have Teams "fill-in" needed info

## Tasks
- [x] Workshop [async questions](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661285060802/05f57943b62626bd6c66226b20f7f5abfc01bd36?sender=u311209e67c8c21a1b37a8167)
- [x] [Research plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2339143681/System+Service+Overview+Map+Research+Plan) (Taylor)
- [x] Develop survey to be filled out

## Acceptance Criteria
- [x] Survey is developed

**Comment by twoangstroms** [comment]
@tayism I added a bunch (maybe too many) fields to the "First survey" tab in the Airtable. My thinking was this was one way to cover the Part 1 questions we converged on in the [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661285060802/05f57943b62626bd6c66226b20f7f5abfc01bd36?sender=u4f7db1750f2355f805e60296). Alway easy to hide fields if this makes it too long!

**Comment by tayism** [comment]
@twoangstroms I reviewed this and it makes sense to me. 

Doesn't look like there is any way to break the first question into different parts design-wise, where we ask about each product/service. I added a bit more context to some of the descriptions of these questions, in hopes that participants have enough so as to not get lost on what we are asking for.

I also piloted the form once more and found it would be helpful to pre-fill all the team names under the "Team" question/drop-down.

**Comment by twoangstroms** [comment]
@tayism Looking into [this about conditional fields](https://support.airtable.com/docs/conditional-form-fields) so maybe we can structure it as 

1. Personal/team info
2. List team's product
3. Does your team have another product?
3a. If Yes, these questions
3b. If No, don't see more questions
4. Anything we missed?

**Comment by twoangstroms** [comment]
Note to all about Form creation/testing in Airtable: if you want to check how your form creation will look when shared, use the "Open Form" button:

![Screen Shot 2022-08-26 at 9.05.10 AM.png](https://images.zenhubusercontent.com/622ba3fd325cb66ad49f3f28/3792ecaf-3c69-4872-82ce-7ecb4bdfa5bd)

**Comment by twoangstroms** [comment]
Added the conditional formatting to ["First survey"](https://airtable.com/shrcL2E95MX3zE4m6)

**Comment by twoangstroms** [comment]
Updated Airtable form to @gopixelsgo notes in Mural
