### ISSUE TITLE
Prep to Meet w/ Platform teams to learn remaining information about their Tools/Services

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44497]
## Issue Description
Prep to Meet w/ Platform teams to learn remaining information about their Tools/Services.  Use the developed script and Data Repository.

## User Story
As an SDT member, I want to meet w/ Platform teams so that I can capture the needed information for mapping their Tools and Services

## Additional questions:
-What do you consider to be the most critical/essential services you offer?

## Tasks
- [x] Create recruitment plan
- [x] [Synthesize poll results](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662738850194/12bb42b1bfc190990b0f04bbe0c6acde41d64e56?sender=u9ea6bd3ca12795949b606150)
- [x] [Draft research questions](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2354250226/Draft+Mapping+Interview+Questions)
- [x] [Create note-taker board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662511366310/448e9d31493253029f678d4c432116f3184d5b89?sender=u9ea6bd3ca12795949b606150)

## Acceptance Criteria
- [ ] Conversation guide is complete
