### ISSUE TITLE
Wireframe: Veteran information

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4449]
## User Story:
As a Veteran I need to be able to review my personal information on the VA.gov so that I can confirm that the hearing aid information from the DLC is my information.

## Tasks
- [ ] Design a screen element that displays the correct veteran information : name, SSN, Address, Phone # and email#
- [ ] Design a screen that enables the veteran to edit their address. 
- [ ] Attend ideation/whiteboard meeting.
- [ ] Meet with the BAM2 Team and/or DLC team to confirm the design address the items in the Content inventory

## Acceptance Criteria:

Given: That the veteran has correctly logged in to their VA account
When: The MDT screen is displayed
Then: The veteran's contact information is correctly and clearly displayed.

- [ ] A screen displaying all the required personal elements from the [Content Inventory page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/content-inventory.md).
- [ ]  Confirm design with DLC

## Next Steps
- Create a Lo-Fi Prototype

## Blockers
- Confirming design element with DLC
- Meeting with DLC
