### ISSUE TITLE
Revise subheads on Change your GI BIll school or program

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44491]
## Issue Description
Stakeholder Cinda Quattrini let us know the [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/) page is causing confusion and lots of calls to the education call center. She asked us to rework the H3s under the H2 "How do I request changes to my GI Bill or other VA education benefits?" to the following:

1995 header: If you’re a Veteran, service member, or dependent using Transfer of Entitlement benefits (chapter 33)

5495 header: If you’re a dependent of a Veteran or service member using Dependents’ Educational Assistance (chapter 35) or Fry Scholarship (chapter 33)

We should put these on the page and see if the H3s become too long and adjust if necessary. 

## Tasks
- [x] Update page in Drupal 
- [x] Review changes (Laura)
- [x] OCTO-DE review (Beth)
- [x] Send to stakeholders for approval (Laura)
- [x] Final copyedit (Megan)
- [x] Publish page (Megan)
- [x] Notify stakeholder changes are live (Beth/Randi)

## Acceptance Criteria
- [x] Live page has updated subheads

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I changed the headers to become:  

- If you’re a Veteran or service member

- If you're a dependent using transferred Post-9/11 GI Bill benefits

- If you’re a dependent using Dependents’ Educational Assistance or Fry Scholarship benefits

For clarity, I separated the first proposed header "If you’re a Veteran, service member, or dependent using Transfer of Entitlement benefits (chapter 33)" into 2 headers. 

I also changed "Transfer of Entitlement" to say "transferred Post-9/11 GI Bill benefits." If we want to keep this, is "transferred" ok to say because it's in passive? 

For length, I took out the phrase after dependent... "of a Veteran or service member." I also took out the reference to chapter xx benefits. 

Here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=939

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I like the way you adjusted the headers here. I just tweaked the intro before the headers slightly and used H4s instead of bullets. That seems more consistent with other pages. I also made similar changes to the "By mail" section at the bottom of the page. 

@bethpotts , we've [updated this page](http://preview-prod.vfs.va.gov/preview?nodeId=939), but we have a few questions for you:
- The form for Veterans/service members lists "transfer of entitlement," but the [form for DEA and Fry changes ](https://www.vba.va.gov/pubs/forms/VBA-22-5495-ARE.pdf) also mentions Post-9/11 GI Bill. Do the forms themselves need an update to avoid confusion here?
- We assumed that a Veteran or service member wouldn't ever be using transferred benefits. But could this happen if a child or spouse using transferred benefits then becomes a service member?
- You can currently only transfer post-9/11 benefits—but “transferred education benefits" be more evergreen in case this changes?
- Secondary action links for the online forms? 
- Mailing instructions say "office that’s in the same region as your school.” Could we specify new or old school, for cases where a school change is the reason for the request? I'm guessing it's the new school?

And finally, these updates would trigger updates to 2 related forms library pages — should we check with Dave before adjusting these?
- https://www.va.gov/find-forms/about-form-22-1995/
- https://www.va.gov/find-forms/about-form-22-5495/

**Comment by laurwill** [comment]
@katherine-fung , see answers to those questions in bold above — could you take a look at the 2 forms library pages I linked there and suggest any related updates in Drupal? That way Beth can review all at once.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

The drafts of the Change your GI Bill school or program page, and the corresponding form pages, are ready for your review: 

1. VA Form 22-1995 form page: 
http://preview-prod.vfs.va.gov/preview?nodeId=5977

2. VA Form 22-5495 page: 
http://preview-prod.vfs.va.gov/preview?nodeId=5979

3. Change your GI Bill school or program page:
http://preview-prod.vfs.va.gov/preview?nodeId=939

We have one question about this page. We say "Transferred Post-9/11 GI Bill benefits." Should we use the more general/evergreen phrase "transferred education benefits" instead, in case you can transfer other types besides Post 9/11 in the future?

Thank you!

**Comment by bethpottsVADEPO** [comment]
@katherine-fung @laurwill Love this solution for what could have been too-long H3s!

Let's keep it as is for now. When I turn back to transfer of entitlement work, I'll assess this language here. 

Go ahead and have the stakeholder review! And thanks so much.

**Comment by laurwill** [comment]
Sent to Cinda for review!

**Comment by laurwill** [comment]
Cinda suggested tweaking the "Follow these instructions" line above dependents headers to clarify that the instructions are in that same section. We added "instructions **here**" and sent back, along with the question above about which regional office to use if you're changing schools.

**Comment by RLHecht** [comment]
Moving to blocked until we hear back from the stakeholder.

**Comment by laurwill** [comment]
Hi @megzehn , Cinda just responded and approved our changes — you can do a final copyedit and publish these updates.

http://preview-prod.vfs.va.gov/preview?nodeId=939

**Comment by megzehn** [comment]
Thanks, @laurwill!  I will check these off as they are copyedited and published:

- [ ] VA Form 22-1995 form page:
http://preview-prod.vfs.va.gov/preview?nodeId=5977

- [ ] VA Form 22-5495 page:
http://preview-prod.vfs.va.gov/preview?nodeId=5979

- [ ] Change your GI Bill school or program page:
http://preview-prod.vfs.va.gov/preview?nodeId=939

**Comment by megzehn** [comment]
Update: these 3 have been copyedited and published.

**Comment by megzehn** [comment]
@laurwill these are now copyedited and published. Does this go to you to notify stakeholders? Thanks!

**Comment by laurwill** [comment]
Thanks Megan! I notified the stakeholder. Closing this out.
