### ISSUE TITLE
Create FAQ for Support Topics and remove/update Topics

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44506]
# Description

There is some confusion on the use of topics in the Support Bot.

# Tasks

- [x] Add a Topic for AWS Login/Password to the Support Bot
- [x] Add a Topic for Datadog Access to the Support Bot
- [x] Add a Topic for Windows 11 Setup to the Support Bot.
- [ ] Create a confluence document with the topic and a detail description when to use that topic.

# Acceptance Criteria
- [x] Support Bot Topics updated
- [ ] FAQ topics document added to Confluence 
- [ ] FAQ topics document added to Dev Documentation under General FAQs section on Scrollview port website.

**Comment by alyssagallion** [comment]
@jknipes I think all of our documentation thus far is complete for support bot right? And then when we create edits to the process we'll update documentation. Checking to see if we can close this!

**Comment by jknipes** [comment]
@alyssagallion Yes, I would agree - closing.
