### ISSUE TITLE
Wireframe: Order Confirmation page

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4450]
## User Story:
As a Veteran, I need to make sure my order went through so that I can have peace of mind.

## Tasks
- [ ] Design a page that confirms the order.
- [ ] Meet with the BAM2 Team and/or DLC team to confirm the design address the items in the Content inventory

## Acceptance Criteria:
Given: That the veteran has correctly completed an order
When: The submit button is clicked
Then: A Order confirmation page is displayed with the correct items that the veteran has ordered.

- [ ] A screen displaying all the required elements for a content page [Content Inventory page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/content-inventory.md).
- [ ]  Confirm design with DLC

## Next Steps
- Create a Lo-Fi Prototype

## Blockers
- Confirming design element with DLC
- Meeting with DLC
