### ISSUE TITLE
Consult PO for mapping desirables

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44504]
## Issue Description
What does our PO think is desirable for outcomes or features of the mapping project?  What does he/she want to get from it?

---
## Tasks
- [x] Prep [discussion](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2387607553/9+27+22-+PO+PM+Sync) during sync
- [x] Secure outcome/requirements that OCTO sees as desirable

## Acceptance Criteria
- [x] OCTO outcome/scenario/requirements documented
