### ISSUE TITLE
Develop and document the mapping process

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44501]
## Issue Description
Document the mapping process, expanding upon the major phases developed in Issue [45606](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/45606).

Should result in an internal guide that a SDT member can follow.

## Tasks
- [x] Workshop Phases-to-specifics details
- [x] Spell out specific steps within each phase to accomplish a completed map
- [x] Refine w/ team input
- [x] Shape raw steps into a crude guide in [Confluence](https://vfs.atlassian.net/l/cp/szWWFLku) 

## Acceptance Criteria
- [x] Guide structure and basic contents are decided
