### ISSUE TITLE
Assess need for R&S on SS disability vs VA disability

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#44518]
## Issue Description
Claudia Cuccia from the Social Security Administration requested that we add a PDF fact sheet about the difference between SS disability and VA disability to VA.gov. [https://app.zenhub.com/files/133843125/1a352c7b-c82b-490d-8667-e87e72e86503/download](https://app.zenhub.com/files/133843125/1a352c7b-c82b-490d-8667-e87e72e86503/download)

We need to find out if there's a need for this content (like a large volume of questions coming in to call centers). We also need to decide if adding content about a non-VA benefit makes sense. If this seems helpful to Veterans, we'll consider creating an R&S similar to [How are pension and disability different?](https://www.va.gov/resources/how-are-pension-benefits-and-disability-compensation-different/)

---
## Tasks
- [ ] Assess whether to create a new R&S page (Laura)
- [ ] If yes, draft content based on PDF 
- [ ] Review content (Laura)
- [ ] Copyedit content (Megan)
- [ ] Post for Beth to review (Megan)

## Acceptance Criteria
- [ ] Content is ready for Beth to review OR we've told Claudia we don't recommend adding this content
---

**Comment by RLHecht** [comment]
Update: Laura meeting with Contact Center team on 8/9 to get more info.

**Comment by laurwill** [comment]
Update: I met with Jason and Ervin from contact center team, and they helped me search within all calls/questions related to disability going back 2 years. I didn't find anything related to the difference between VA disability and SSDI.

I responded to Claudia from SSA to let her know that since we can't find any data on this, we won't be able to prioritize new content on this topic at this time. 

Closing this out.
