### ISSUE TITLE
VFS Product Directory: Create Table of Contents & Product List Pages in Confluence

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44520]
## Issue Description
With a path selected for how we'll create the VFS Product Directory pages, we now need to define exactly what these pages will look like - both the Table of Contents page, and the individual product pages. This ticket will include defining what the pages will look like and the dynamic creation of them in Confluence.

---
## Tasks
- [x] Create a mockup Table of Contents page in our Confluence space for review of layout/text
- [x] Create a mockup Product page in our Confluence space for review of layout/text, this will be used as a template for creating the product pages
- [x] Create the Table of Contents in our Confluence space, ensuring that it will be updated once a day, when products are added to the VFS Product Directory
- [x] Create an individual Product Page based on the template, page should update either once a day, or as updates are made
- [x] Create ALL product pages based on the template, page should update either once a day, or as updates are made

## Acceptance Criteria
- [ ] Mockups have been reviewed and approved by QAS
   - [ ] Mockups have been reviewed and approved by Content Team
- [ ] Final TOC and Product pages are publishing as intended

**Comment by rsmithadhoc** [comment]
- Updated [draft PR](https://github.com/department-of-veterans-affairs/product-directory/pull/380) with the core functionality to publish individual product pages to Confluence.
- Generated an [example page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2283143392/Product+Directory+TEMPORARY) in our Confluence space to get feedback on.
- There are some bugs to fix and more testing to do on it.

**Comment by rsmithadhoc** [comment]
- Updated [draft PR](https://github.com/department-of-veterans-affairs/product-directory/pull/380) with more fixes: arrays, lists, excluded fields, unit tests
- Published V3 of [example page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2283143392/Product+Directory+TEMPORARY) in our Confluence space to get feedback.
- To-do:
  - 1 more unit test to fix.
  - Check with the team on how we should handle large comma-separated lists. These are strings in our product directory source file, should they be an array of strings like `endpoints_consumed` is? This would make the display output consistent and easier for others to parse.

**Comment by rsmithadhoc** [comment]
- [PR](https://github.com/department-of-veterans-affairs/product-directory/pull/380) out for review.
- I consulted with the team on lists in the product directory and they are looking into changing the underlying format. This will solve the issue of the long comma-separated lists with no space in the output.
