### ISSUE TITLE
[BE] pass appointment.stationNo property through

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44524]
## Background

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1658160955602039

We'd like to have the `stationNo` property available to make unique IDs with the stationNo-appointmentIen combination. Having the station number available could also enable future informational displays for veterans.

## Tasks
- [ ] pass `stationNo` property through to the frontend
- [ ] update rspec
- [ ] cache data / code cleanup if necessary

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
