### ISSUE TITLE
Wireframe: DLC contact information

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4452]
## User Story:
As a Veteran I need to be able to easly find the contact # of the DLC so that if I have trouble with my order I can call someone to assit me.

## Tasks
- [ ] Design a screen element that displays the DLC contact information for Call Center rep. 
- [ ] Design a screen element that displays the DLC email.
- [ ] Design a screen element that displays the DLC hours of Call Centers operations 
- [ ] Attend ideation/whiteboard meeting.
- [ ] Meet with the BAM2 Team and/or DLC team to confirm the design address the items in the Content inventory

## Acceptance Criteria:
Given: That the veteran has correctly logged in to their VA account
When: The MDT screen is displayed
Then: The DLC's contact information is correctly and clearly displayed.

- [ ] A screen displaying all the required DLC contact information from the [Content Inventory page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/content-inventory.md).
- [ ]  Confirm design with DLC

## Next Steps
- Create a Lo-Fi Prototype

## Blockers
- Confirming design element with DLC
- Meeting with DLC
