### ISSUE TITLE
SEO Keywords

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4453]
## User Story:
As a __Veteran I need to easily search and find the Medical Device Tool's url_______ so that I can _easily order my items _________.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Meet with IA & Content team to define best URL name for the medical device tool
- [ ] Meet with IA & Content team to define best SEO keywords for the medical device tool
- [ ] Define the Linking Strategy with IA and Content team.

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] A list of SEO keywords has been vetted by DLC and Veterans
- [ ] Documentation in the GH of list of SEO Keywords
- [ ] Confirm URL name with DLC

## Next Steps
- Provided information to the Dev team for unit testing

## Blockers
- Confirming URLname with DLC
- Meeting with DLC 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
