### ISSUE TITLE
Validate claims api attributes currently used in CST for EVSS to Lighthouse migration

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44539]
## Value Statement
**_As a_** member of the Lighthouse team
**_I want to_** make sure we are migrating only the attributes needed to run the current CST application 
**_So that_** we don't unnecessarily build things nobody is actually using.

---
## Background Context
Lighthouse has summarized the list of attributes they are considering removing [here](https://docs.google.com/document/d/1Fczjn1ql6tZ2Vpv2vhprrPKC8gISPEEGJLa9CDqdnLg/edit#heading=h.1yrizxy4piwq)

After speaking with Kayla from Lighthouse team, it is clear that removing attributes from the migration would require less effort than having to add select attributes now and having to remove them later. As part of our review, we can also identify  attributes that we think show promise to be added into future builds. 

## Acceptance Criteria
- [x] _Determine whether each attribute is currently being used in the CST application_
- [x] _If an attribute is in use, identify what part of the end user experience it affects_
- [x] _Annotate attached document to verify which fields should be migrated and which should not_

## Designs and Build Notes
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jacobworrell** [comment]
@samcoforma @sortizsh  Kayla has validated your responses, so closing out this ticket. We'll create a new ticket if they come up if they want us to review more attributes in the future.
