### ISSUE TITLE
[FE] My VA: Update Healthcare conditional code

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#44533]
## Background
After conducting research for [this ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26603) we determined that we need to update the conditional code for the healthcare section to check for va.Profile.mhv.AccountState = "OK" or "Multiple" and show the healthcare section if those are present. Otherwise, if "NONE" or "Deactivated" are present we should not show the healthcare section.

## Tasks
- [x] Make code updates
- [x] Confirm with APM/PM that we are good to push to Staging for validation
- [x] APM/PM completes validation

## Acceptance Criteria
- [ ] Healthcare section shows appropriately for users with va.Profile.mhv.AccountState = "OK" or "Multiple". 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ PM or Design
- _How can this work be validated?_ Ensure the Healthcare section shows for the appropriate users via Staging. List of test users is  located [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md).

**Comment by tmitchellgcio** [comment]
Everything now seems to pass just fine when testing. Had issues with the CI process, but they are fixed for now. This can likely be validated on http://8ee3ad362a8f5cec045b10abb3437c0c.review.vetsgov-internal/ [@ajakabcin](https://github.com/ajakabcin) [@ericasauv09](https://github.com/ericasauv09)

**Comment by ericasauv09** [comment]
validated with user 41 (had healthcare) and user 272 (did not have healthcare). @tmitchellgcio I think we should be good to push this to staging after 2pm ET today unless @ajakabcin has any objections. I can validate in staging once that is ready.
