### ISSUE TITLE
Rationalize all API domain references within vets-api

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#44538]
## Overview
In the scope of the cloud isolation team's work of isolating api.va.gov traffic between VA.gov and Lighthouse, we are verifying places where vets-api is configured to reference itself. Most critically, we are making sure the mappings between lower environments are consistent and make sense. 

* In general one would expect dev to map to dev, staging to staging, etc. 
* But, in places where VA.gov is essentially an external consumer of Lighthouse, then it should be configured to use the Lighthouse sandbox environment, because that is the stable lower environment that Lighthouse provides to external teams.

### 1. VA.gov-only use cases 
**These should align by environment and use the new \*-platform-api.va.gov domain (dev-dev, staging-staging)**
* These values have no connection to Lighthouse, hence are self-contained within VA.gov. The sandbox environment is not relevant.
* To decouple from Lighthouse, these should be updated to use \*-platform-api.va.gov. 
* Many of these values are authentication callback endpoints (SAML or OAuth), and will require that sign in partners (ID.me, SSOe, Login.gov) update their partner configurations.

- [x] Update authentication callback endpoints in vets-api across all environments. [**#44618**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44618)
- [x] Update HealthQuest facilities endpoint configuration to use new platform API endpoint. [**#44620**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44620)

### 2. Lighthouse-only use cases 
**These should align by environment and use existing \*-api.va.gov domain (dev-dev, staging-staging)**
* These are essentially internal component connections within Lighthouse, and hence should remain internally consistent within an environment. 
* Examples: VBA Documents location rewrite, internal token validation URL
* Lighthouse retains \*-api.va.gov so these values should continue using that URL
* _Possible Exception_: Values that need to be matched up against an Okta-issued token may need to use `sandbox-api.va.gov` because that authorization server is shared by all lower environments and issues tokens with `sandbox-api.va.gov` as the audience value to be validated.

- [x] Configure `token_validation.url` in staging environment (currently missing). [**#44339**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44339)
- [x] Update or confirm `oidc.isolated_audience` config values in dev and staging. **No ticket needed.**

### 3. VA.gov-> Lighthouse use cases 
**These should use sandbox-api, because VA.gov is effectively an external consumer of Lighthouse.** 
* Examples: facility locator use of Lighthouse facilities API, VA.gov use of address validation API
* _Possible Exception_: If a VA.gov application is consuming both Lighthouse and non-Lighthouse data, it's possible that it would need to connect to a different Lighthouse environment in order to maintain data consistency. 

- [x] Update VA.gov dev `lighthouse.facilities_url` to point to sandbox-api. [**#44623**](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/44623)
- [x] Update VA.gov appeals application decision_review setting to point to sandbox-api. [**#44622**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44622)
  ** (Unless it would cause a data conflict)

### 4. In all above cases, network requests should be routed via the forward proxy
* Once the above environment mappings are aligned, then we additionally want to route requests between VA.gov and Lighthouse via the forward proxy. 
* Since dev and staging will have a mix of outbound requests from items (2) and (3) above, the forward proxies in those environments will need to have both a port pointing to the `{dev,staging}-api.va.gov` endpoint and a port pointing to the `sandbox-api.va.gov` endpoint. 

- [x] Configure forward proxy port for sandbox-api.va.gov in dev and staging environments. [**#44326**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44326), [**#44327**](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44327) 
- [x] Update vets-api configuration pointing at \*-api.va.gov to use dev/staging/sandbox forward proxy ports as needed. 

### 5. Non-network requests (token validation values, callbacks) remain intact
* `*-api-va.gov is used in several places as a magic string such as the `audience` value in an OAuth token. These should be preserved and **not** updated to use forward proxy host, because they do not represent network requests made by vets-api. 
* Examples: `vba_documents.location.replacement`, `oidc.opaque_clients.route`, `oidc.isolated_audience.*` These only need updating if the currently configured value in cases of environment mis-alignment. **No tickets needed.**

### 6. Third party application directory 
* VA.gov has a frontend application component that lists apps, and it invokes the Lighthouse apps API (services/v0/apps). 
* At first glance this looks like a case of VA.gov using Lighthouse as an upstream dependency (type 3 above)
* But, if this is primarily used by Lighthouse to manage itself, then maybe it is just a Lighthouse-only use case (type 2).

- [x] Confirm or update `directory.url`to point to sandbox-api in dev and staging.

**Comment by alwerner** [comment]
RFC #46: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/46

**Comment by alwerner** [comment]
Closing as complete. cc: @madebydna
