### ISSUE TITLE
[Design] Create Final Wireframes & Content for Presenting Check-in Information to Veteran Upon Completing Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44548]
## Background
This was a recommendation that came out of the [Bay Pines research study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/bay-pines-in-person-uat).
(Collab/review with @niradatta1 on content)

## User Story
As a Veteran, when I complete Pre-Check-in, I would like to understand what I need to do for day-off Check-in so that I don't skip it or get confused about what to do.

## Tasks
- [x] Finalize detailed mockup and callouts 
    - Idea was to add a link to Danielle's (Support) page that talks about how to check-in (Kristen to provide the link)
    - Wording of link is important
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## Wireframe link (In-progress)
[Abstract](https://share.goabstract.com/93220b74-2548-445a-912d-e544adbd9cd0?collectionLayerId=ecf4ff0f-2b18-423f-aed9-6da2bd9499ee&mode=design): https://share.goabstract.com/93220b74-2548-445a-912d-e544adbd9cd0?collectionLayerId=ecf4ff0f-2b18-423f-aed9-6da2bd9499ee&mode=design

**Comment by benbrasso-agile6** [comment]
I had recommended this as part of the Bay Pines findings. Let me know if you'd like some more context.

**Comment by loripusey** [comment]
@zach-park please plan on getting with @benbrasso-agile6  on this to talk through.

**Comment by benbrasso-agile6** [comment]
Here's what I'd recommend for IN PERSON... 

Add a link for... 

Find out how to check in on the day of your appointment

Add it directly below the following...

<img width="291" alt="Screen Shot 2022-08-25 at 10 42 49 AM" src="https://user-images.githubusercontent.com/101129355/186695924-a58a792d-af96-4472-b2ab-72ea4f5a66ea.png">

Then, I think the text links below that need to be updated. I think the only one should be...

Sign in to manage your appointments

There should be no travel pay link. 

@niradatta1 @kristenmcconnell Does all of that sound right? Also, this recommendation is built on the assumption that you can only ever do pre check in for one appointment at a time. Is that assumption true? Reason being, if Veterans can complete pre check in for an in person appt and a telephone appt at the same time, then we need to add something around "in person" to that link title. It could be, "Find out how to check in on the day of your appointment for in-person visits." But, that also opens a can of what terminology is the VA using to describe in person vs telephone appts. It's always something... let me know your thoughts. 

If a Veteran is doing pre check in for a telephone appointment only, I don't recommend adding this link to the confirmation page.

**Comment by kristenmcconnell** [comment]
Currently, pre-check-in can involve multiple in-person appointments at once. A telephone and in-person will not occur within one pre-check-in. Stephen asked if we should change this in the future to have one pre-check-in for all appointments within one day. But, that isn't the case right now. Therefore, I think we are ok with your above suggestion. 

You are suggesting that we add the link within the blue box? I think that make sense, because it is essentially part of the "what do I do next?" instructions that we have in the blue box. This looks good to me.

@zach-park Here is the [actual URL](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) for the resources and support page that this link will go to.

**Comment by benbrasso-agile6** [comment]
I am NOT suggesting that we add the link in the blue box. I am suggesting to add it as a link below the blue box. The reason I suggested this is because I'm not sure of the rules around two different statements in that blue box. It would likely not be seen if it's the second sentence. @kristenmcconnell

**Comment by benbrasso-agile6** [comment]
1. blue box
2. text link for Find out how to check in on the day of your appointment
3. text link for Sign in to manage your appointments

**Comment by kristenmcconnell** [comment]
Ok about the blue box. From a design system perspective, I believe it is up to us if it should be in the blue box or not. There is nothing saying that it can't be in there. That said, I do understand the concern that it won't be seen if it is part of the second sentence. Though, I'm not sure if having it outside the box will solve that concern either. I defer to others on that.

**Comment by loripusey** [comment]
@zach-park Can you add a link to the wireframe(s) in this ticket please? Thanks.
cc: @kristenmcconnell @sarahknoppA6

**Comment by zach-park** [comment]
@loripusey , [the link](https://share.goabstract.com/d536019c-6b8b-4a06-bbc9-9d0502d5c277?collectionLayerId=1f4c0452-0fe6-4973-85c9-483029c6a506&mode=design) is attached in the AC area.

**Comment by benbrasso-agile6** [comment]
That doesn't look like the right wireframe to me. Is it?

**Comment by zach-park** [comment]
Sorry, the link is updated.

**Comment by loripusey** [comment]
Thanks @zach-park; is anyone tagged to validate it? Looks fine to me.

**Comment by zach-park** [comment]
@loripusey I haven't had a chance to validate it yet. I'll be meeting with Nira on Friday. And we should be able to validate it during that review.

**Comment by loripusey** [comment]
Sounds good @zach-park , I'd like to implement this next sprint.
