### ISSUE TITLE
Integrate Must, Should, and Consider Framework for Feedback into Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44545]
## User Story
As a VFS team member, I want to understand how to interpret feedback received in the Collaboration Cycle Design Intent and Midpoint Review, so I can make educated decisions for the success of my teams product on VA.gov.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
In ticket #41625, the Must, Should, and Consider framework for feedback was drafted, approved by Governance team and approved by OCTO-DE practice area leads. Now we must integrate that feedback into VFS-facing guidance on Platform Website, and into the feedback templates. The purpose of this ticket is to ensure VFS teams are aware of the Must, Should, and Consider Framework for Feedback and can easily access it on Platform Website.

## Impacted Artifacts
[Platform Website: Design Intent - Outcome](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent#Outcome)
[Platform Website: Midpoint Review - Outcome](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review#Outcome)
[GitHub: Collab Cycle Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md)
New page for Must, Should, and Consider Framework for Feedback

## Tasks
- [x] Identify where the Must, Should, and Consider Framework for Feedback should live on Platform Website/Collaboration Cycle
   - Shira's 2 cents: I liken this to be similar to the VA.gov Experience Standards. May the Must, Should, and Consider and the VA.gov Exp Stds page can live on level 2, with an appropriate level 1 heading. Or, maybe the Must, Should and Consider is important enough to be it's own level 1 in the left nav

**Note:** all tasks following are dependent on the Must, Should, and Consider Framework for Feedback being published on Platform Website. We must publish on Platform Website before we can complete any of the other tasks as we need the url to link correctly.

- [x] Create draft pages to update the "Outcome" section of both the Design Intent touchpoint page and Midpoint Review touchpoint page to link out to the Must, Should, and Consider Framework for Feedback. Ensure both pages referenced the guidance consistently.
- [x] Create a PR to update the Collaboration Cycle Feedback gh template.
   - [x] Remove the existing definitions for must, should and consider.
   - [x] Include link to Must, Should, and Consider Framework for Feedback, instructing VFS teams to review link for guidance on how to interpret feedback included within the ticket (wordsmith as needed)
- [x] Create draft page for Change History Log (@shiragoodman can help with this if needed)
- [x] Once all of the above is published/shared, post on #vfs-all-teams Slack channel (@shiragoodman can help with this)

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams know how to interpret feedback received in the Design Intent and Midpoint Review
- [x] VFS teams can easily reference the Must, Should and Consider Framework for Feedback in their feedback tickets received at Design Intent and Midpoint Review
- [x] VFS teams are aware that must feedback, if not addressed, could result in a launch-blocking issue at Staging Review
- [x] VFS teams have been notified of the the new Must, Should, Consider guidance per [Platform Communication Playbook](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1808203819/Platform+communications+playbook+-+Principles)

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@CherylEvans this is ready for your review:
[Design intent](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2297692197/44545+Copy+of+Design+intent)
[Midpoint review](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2298019846/44545+Copy+of+Midpoint+review)
[Change history](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2297692210/44545+Copy+of+Change+history)
[PR](https://github.com/department-of-veterans-affairs/va.gov-team/blob/6a42b44cec09e22987132e2cb1b4d670f2dfbde1/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md)

**Comment by CherylEvans** [comment]
@allison0034 I placed the article "the" in front of Governance team on [Change history](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2297692210/44545+Copy+of+Change+history) page.  I only added in a few places where needed.  Hope you don't mind. Peer review is complete, looks great!!

**Comment by allison0034** [comment]
Not at all... thank you!
