### ISSUE TITLE
Update note on Post-9/11 GI Bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44543]
## Issue Description
Stakeholder Tammy Hurley asked us to update a note on the [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) page. For the note under the H2 "How much monthly housing allowance (MHA) can I get?" she provided this text: 

**Note:** Starting August 1, 2022, GI Bill students who are pursuing a program of education while on active duty for 30 consecutive days or more, will no longer receive a Monthly Housing Allowance (MHA) from VA, as they will receive a Basic Allowance for Housing (BAH) from the Department of Defense instead.

We currently have a note in this section (about MHA payments going back to the online rate as of June 2), so we need to assess how best to add this information before we put it on the page. 

We also need to review the note for plain language and to make sure it adheres to VA.gov's voice and style. 

## Tasks
- [x] Assess how best to incorporate note on the page 
- [x] Add content to Drupal page
- [x] Review (Laura)
- [x] OCTO-DE review (Beth)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish page (Megan)

## Acceptance Criteria
- [x] New note is on live page

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! Attached is a doc with some changes to the above content. I'd like to chat through placement for this content on the page, as I'm not sure that is should be a note (because it seems to be something that needs more immediate attention)! Looking forward to reviewing soon! 
[Update note on Post-911 GI Bill page_AB_7.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9160373/Update.note.on.Post-911.GI.Bill.page_AB_7.20.docx)

**Comment by aliyahblackmore** [comment]
As suggested by Beth, I added the following (in bold) proposed content to Drupal.  After reviewing in standup and with Beth, the content is included above the current "Note" under the MHA section.

**If you’re a GI Bill student on active duty and in school for 30 continuous days or more (all at once, without a break), you’ll get a BAH from the Department of Defense (DoD) instead of an MHA. This starts on August, 1, 2022.**

Preview link:  http://preview-prod.vfs.va.gov/preview?nodeId=935

@laurwill this is ready for you to review.

**Comment by laurwill** [comment]
Thanks Aliyah! I like where you landed with this.
- I reordered sentence to place the "continuous" emphasis on the days of active duty, which I think is the key piece here. 
- I also tried "This change applies as of August 1, 2022" to be slightly more evergreen. 
- I went back and forth about bolding the date — I think here the bolding wasn't as helpful, since there are no next steps the Veteran/service member needs to take (where the bold date in the COVID note is helpful because they might need to take an action after that date.) 
- To shorten the text, I also tried taking out "GI Bill student" — the whole page is about GI Bill, so we may not need that detail here.

@bethpotts , ready for you to take a look! http://preview-prod.vfs.va.gov/preview?nodeId=935

**Comment by bethpottsVADEPO** [comment]
@laurwill @aliyahblackmore This placement works! The only change I'd like you to make is to move the date to the start of the long sentence: "Starting August 1, 2022, if you're enrolled in school while on active duty..."

It does make a long sentence longer, but let's do it just for the rest of this month. Would you let the SMEs know that you'll remove the date on that date? We don't generally keep dates in text like this unless there's some compelling reason to do so. Just think about it in terms of value to the Veteran. Do they care when things changed or just that they'll get a BAH rather than an MHA. 

It's just this one addition above the existing **Note**, right? Making sure I didn't miss any other change/addition..

**Comment by aliyahblackmore** [comment]
Thanks @bethpottsVADEPO ! Yes, this was the only addition here. 

I made the change so that the sentence begins with "Starting August 1, 2022..." 

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=935

@laurwill this is ready.  Passing this to @RLHecht to copy edit!  See Beth's note above re: removing the date after August 1.

**Comment by RLHecht** [comment]
Just published this page. Moving to validate and I'll let the stakeholder know once it's live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
