### ISSUE TITLE
CST: See request for C&P exam

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44540]
## Value Statement
**_As a_** veteran who has recently submitted a disability claim
**_I want to_** be able to easily see C&P exam requests within the CST and take action to get one scheduled
**_So that_**  my claim can continue moving through the process and I can receive a decision as quickly as possible. 

---
## Background Context
- Currently, a request for C&P exam is basically just a note in claim detail. It's not made a salient detail a veteran should definitely pay attention to despite it being one of the main actions a veteran can take to ensure their claim doesn't get roadblocked. 

## Acceptance Criteria
- [ ] _When an exam is requested it is one of the most salient pieces of information to the user via the tool UI_
- [ ] _Provide clear directions and links to VAOS so the veteran can schedule their exam_
- [ ] _Provide language that contextualizes the need for an exam within the claims journey (why it's important, what the VA is going to do with the information)_
- [ ] _Passes accessibility audit_
- [ ] _Analytics set up to track conversions from CST to VAOS scheduling_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Is there a claims api attribute just for C&P exams? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
