### ISSUE TITLE
Measure Impact of E2E Tests on VFS Engineer Experience

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44566]
# Description
In order to assess the impact that E2E tests are having on VFS engineer experience we need the following data collected into our data warehouse-- 

* Number of hours VFS engineers spent blocked by end-to-end tests
* The time it takes for a CI workflow to complete
* VFS engineer sentiment toward CI
* VFS engineer sentiment toward e2e testing

Each raw measurement should be warehoused in BigQuery.

Transformation and visualization should take place in Domo.

# Tasks
- [x] ~Collect number of hours VFS engineers _potentially_ spent blocked by failing e2e tests~ WE DISCUSSED THIS IN DETAIL AND DECIDED NOT TO PURSUE THIS METRIC BECAUSE THE RESULT WOULD ONLY BE A GUESS. INSTEAD WE'RE TRACKING E2E FAILURES AGAINST MAIN.
- [x] Collect the time it takes for e2e tests to complete
- [x] Collect the most recent survey data related to VFS engineer sentiment about CI
- [x] Collect the most recent survey data related to VFS engineer sentiment about e2e testing

# Acceptance Criteria
- [ ] The time it takes VFS engineers to observe, diagnose, and resolve issues with e2e tests is available in BigQuery
- [ ] The VFS engineer sentiment from VFS surveys is available in BigQuery

**Comment by holdenhinkle** [comment]
Google doc with notes - https://docs.google.com/document/d/1baekOdZ5sorzoICc1NRYu1ER-EjtjiYlvqx5EGhnTSg/edit#

GitHub actions api docs - https://docs.github.com/en/rest/actions

**Comment by holdenhinkle** [comment]
e2e failure tracking spreadsheet for main branch in vets-website - https://docs.google.com/spreadsheets/d/1UEN5K3OmY8sVS-KaAZSvJSy0ssv-YemT3oPtwZZaNRs/edit#gid=0

**Comment by holdenhinkle** [comment]
Peter and I refined the sheet together. Darius said it looks good.

I got this sheet connected to BQ:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/82f03752-6e64-4c60-83ca-ebd8600ce37d)

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ede8b27a-1092-49b0-9eb1-9cc0972d539e)

**Comment by holdenhinkle** [comment]
I had to select 'Anyone with link' so DOMO can read the Google sheet - 
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/e1a593e1-9dee-4842-ad03-29dc5f7cab9a)

I'll check with Analytics about that tomorrow. Perhaps there's an address I can share the sheet with instead.

**Comment by holdenhinkle** [comment]
Possible DOMO visualizations:

- Number of failures per day and number of failure_reasons (runner, GitHub actions, other, etc.) per day
- Number of e2e_errors (memory, list communication, etc.) per day
- Average number of retries per day

What about looking at apps/spec files/examples (tests)?

**Comment by holdenhinkle** [comment]
DOMO
Failures against main dashboard - https://va-gov.domo.com/page/899154111

Failure reasons by day:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/4135b9d2-d35e-4a88-82ff-4dbe29f54f09)

**Comment by holdenhinkle** [comment]
Retry attempts per day:
![image](https://user-images.githubusercontent.com/9326247/180452413-f433e8f0-6175-42cf-b0f9-62c15bf7886c.png)

**Comment by holdenhinkle** [comment]
All visualizations are complete:
![image](https://user-images.githubusercontent.com/9326247/180570903-6b172cf7-0581-4130-bf54-06093ddc76a1.png)

Review the query for this on Monday - `Number of failures per day and number of failure_reasons (runner, GitHub actions, other, etc.) per day`

**Comment by holdenhinkle** [comment]
I created a new BQ table called `e2e_failure_tracker_main_errors` that syncs to the `e2e_errors` sheet:
![image](https://user-images.githubusercontent.com/9326247/180571425-02e71d9f-4ee0-4497-855f-4e8b0cfd2b5a.png)

![image](https://user-images.githubusercontent.com/9326247/180571169-5c16b5c2-329d-4862-8942-41d4a6874c9a.png)

So we can create graphs like:
![image](https://user-images.githubusercontent.com/9326247/180571372-fc31f9fe-ceee-45e7-af0f-55caa8054e19.png)

**Comment by holdenhinkle** [comment]
Here's the VFS survey data regarding Platform for Q1 and Q2:

- 2022 - https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1645655432415/26f1766bc490b410bff347eb2d97e4904d090f79?sender=302066bc-6019-4142-9bc3-71ea21b81f91
- q1 - https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1645571236979/08f59565966ee0e213128c95d374a3d9baeb78e6?sender=c57ce896-b410-4377-94a4-87aec65e1a5a
- q2 - https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1654536055645/667377508f107d1b1c830167f2807d90d6c0eb18?sender=0e3bbfd5-939f-4e3f-b660-8e08491ce440

I searched the documents for the following keywords and couldn't find anything about CI, E2E tests, Cypress tests, etc.:

- test
- e2e
- cypress
- github
- actions

There's nothing to graph.

**Comment by holdenhinkle** [comment]
We're tracking the time it takes to run E2E tests in DOMO already - https://va-gov.domo.com/page/1232474697
