### ISSUE TITLE
Measure Volume of Support Related to E2E Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44564]
# Description
In order to assess the volume of support requests related to end-to-end tests we need to measure the following --

* Total number of support requests assigned to Quality Assurance Standards team
* The topic of each support request assigned to QAS team
* The number of support requests caused by e2e test failures
* The number of support requests caused by e2e test flakiness in the CI workflow

Each raw measurement should be warehoused in BigQuery.

Transformation and visualization should take place in Domo.

# Tasks
- [x] Collect the total number of support requests assigned to QAS
- [x] Categorize the support requests assigned to QAS

# Acceptance Criteria
- [x] The number and percentage of support requests assigned to QAS team related to e2e testing are warehoused in BigQuery

**Comment by CBonade** [comment]
Support requests catalogued here: https://docs.google.com/spreadsheets/d/1mFsYOxlcET3rVJd-iyzFahLHQPC33Jhm8eU-vfc1dCM/edit#gid=1819982195

Stored in BigQuery here: https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sqa_standards_support_data
