### ISSUE TITLE
Measure E2E Test Impact on CI Workflow

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44563]
# Description
In order to assess the impact of end-to-end tests on the continuous integration workflow hosted in GitHub Actions we need to measure various key data --

* Total number of workflows that fail
* Category of the cause of the workflow failure
* Number of workflows that fail due to e2e tests
* Number of workflows that fail due to flaky e2e tests

Each raw measurement should be warehoused in BigQuery.

Transformation and visualization should take place in Domo.

# Tasks
- [x] Collect the total number of CI workflow failures
- [ ] Collect the cause of CI workflow failures
- [ ] Categorize the cause of CI workflow failures

# Acceptance Criteria
- [ ] CI workflow failure data is available for analysis in BigQuery

**Comment by rjohnson2011** [comment]
Created a schema in BigQuery ['Github Workflows](https://console.cloud.google.com/bigquery?ws=!1m28!1m3!8m2!1s145052845255!2s701613877b0b42baa5ff413ef33f2f80!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3scypress_test_suite_executions!1m4!1m3!1salert-arbor-307717!2sbquxjob_36cd0444_18211828698!3sUS!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3scypress_test_results!1m3!8m2!1s145052845255!2sd1bc65fe43504b2c8998c58d21f35f82!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sgithub_workflows&pli=1&authuser=1&project=alert-arbor-307717&sq=145052845255:d1bc65fe43504b2c8998c58d21f35f82)' to hold the workflow data for ingestion. 
Used to Octokit Github API to [list all workflows runs for a repository](https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository).
The response is an array like the following:
```
    {
      id: 2713738730,
      name: 'E2E Tests',
      node_id: 'WFR_kwLOAfqh686hwF3q',
      head_branch: 'main',
      head_sha: 'deae0c27151425fc5bb8f2c3f2fd9e1f9bee8f21',
      path: '.github/workflows/e2e-tests.yml',
      run_number: 1650,
      event: 'workflow_run',
      status: 'completed',
      conclusion: 'failure',
      workflow_id: 19698069,
      check_suite_id: 7464907551,
      check_suite_node_id: 'CS_kwDOAfqh688AAAABvPFzHw',
      url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730',
      html_url: 'https://github.com/department-of-veterans-affairs/vets-website/actions/runs/2713738730',
      pull_requests: [],
      created_at: '2022-07-21T18:00:46Z',
      updated_at: '2022-07-21T18:45:15Z',
      actor: [Object],
      run_attempt: 1,
      referenced_workflows: [],
      run_started_at: '2022-07-21T18:00:46Z',
      triggering_actor: [Object],
      jobs_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730/jobs',
      logs_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730/logs',
      check_suite_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/check-suites/7464907551',
      artifacts_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730/artifacts',
      cancel_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730/cancel',
      rerun_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/runs/2713738730/rerun',
      previous_attempt_url: null,
      workflow_url: 'https://api.github.com/repos/department-of-veterans-affairs/vets-website/actions/workflows/19698069',
      head_commit: [Object],
      repository: [Object],
      head_repository: [Object]
    },
```
This response contains the status of the workflow (completed/pending/failure) but does not include the specific error message. To get this requires [downloading workflow logs](https://docs.github.com/en/rest/actions/workflow-runs#download-workflow-run-attempt-logs), which returns a URL with a path to a .zip file. When this is uncompressed, each workflow is a separate .txt file with the complete workflow logs. 
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/90b337e0-33f7-4f46-b399-527ff0a4514d)
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/17c977ec-c234-4205-bef0-cc206dac6cc8)

**Comment by rjohnson2011** [comment]
A proposal accounting for the additional complexities listed above to fully complete the ticket has been drafted here -> https://docs.google.com/document/d/1uinjsWTc4hpfBFTXIZrOd3_uSxZDIcHl_DAIjsFq884/edit#

**Comment by rjohnson2011** [comment]
Modified the shape data for the `workflows.js` file which inherits from the `GIthub` class in the `dashboard-data` repo to pull from the Octokit API and populate BigQuery. Modified the `main.yml` and `package.json` files to create a new yarn command to populate the Workflows BigQuery table. Working on getting a passing Github Action workflow to populate this schema.

**Comment by rjohnson2011** [comment]
Working through getting the Github Workflows API ingestion method to populate BigQuery with workflow data. Received a few errors that reached out to the team on our Slack channel to discuss and resolve ('Table has wrong region', 'Error importing row'). 
I was getting an error when trying to populate 100 rows into BigQuery, my suspicion is one of the rows has a null property on a required field. I attempted to populate the first row and it worked correctly, so the issue seems to be with the data rather than the ingestion method. Working on resolving this issue and fully populating the table today.

**Comment by rjohnson2011** [comment]
Modified the ingestion mechanism to successfully insert all ~67,000 rows into the github_workflows table in BigQuery. Working on querying the resulting workflow data and displaying this via a Domo chart.

**Comment by rjohnson2011** [comment]
Created a BigQuery query to pull conclusions from the Github Workflows API and graph into a pie chart in Domo, using Success, Failure, Cancelled.

The chart is available on Domo here -> https://va-gov.domo.com/page/-100000/kpis/details/1154149621

**Comment by rjohnson2011** [comment]
PR created for Github Workflows ingestion mechanism which completes first acceptance criteria -> https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/149

To fully automate error data from logs there is a report above with tickets involving that effort.

**Comment by pjhill** [comment]
Adding some notes here:
- The visual we have here is awesome.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/96a62479-057a-4758-9e3b-1a39db982326)
- It looks like we still need to collect and categorize the cause of the failures.

I'm going to break off the piece about collecting and categorizing failures into a separate ticket, so we can close this ticket.
