### ISSUE TITLE
Measure E2E Test Characteristics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44562]
# Description
In order to assess the basic characteristics of E2E tests on the platform, we need to be able to measure them. Currently, we are interested in platform-wide data regarding --

* Number of test spec files
* Average number of tests per spec file
* ~Average execution time for tests~
* ~Average number of lines of code covered by a test~

Each raw measurement should be warehoused in BigQuery.

Transformation and visualization should take place in Domo.

# Tasks
- [x] Collect the count of test spec files
- [x] Collect the number of tests contained in each test spec file
- [ ] ~Collect the execution time for each test~
- [ ] ~Collect the number of lines of code covered by each test~

# Acceptance Criteria
- [x] Data for the count of test spec files is stored in BigQuery
- [x] Data for the number of tests contained in each test spec is stored in BigQuery
- [ ] ~Data for the time to execute each test is stored in BigQuery~
- [ ] ~Data for the number of lines of code that each test covers is stored in BigQuery~

**Comment by ddzz** [comment]
Two metrics, number of E2E test files and average execution time for tests, are already being tracked in BigQuery and Domo.

**Comment by ddzz** [comment]
Code coverage does not work in the dispatched E2E workflow, possibly due to the upgrade to Cypress 10. I'm trying to find a fix.

**Comment by ddzz** [comment]
I've been unable to fix the issue with generating code coverage reports for Cypress tests. The issue appears to be that the memory requirements for the Webpack build have increased over time and now exceed what self-hosted runners can handle. Increasing runner memory did not fix the issue. This is a deeper issue with the Webpack build that is likely outside the scope of our team.

The average number of tests per spec file can be calculated using existing data in BigQuery and Domo. More granular data would likely require modifying our reporting tools to capture this.

**Comment by holdenhinkle** [comment]
I graphed the average number of tests per spec file per day:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/5de94c0b-3330-400f-9783-e841eb8621e3)

**Comment by holdenhinkle** [comment]
Distribution of Number of Tests in Each Spec File, Per Day

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/4b98761e-6bc0-408c-8eee-b41e6e266d8a)[image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/65f58cd2-c33e-4196-83b9-7b755b0beb24)

**Comment by holdenhinkle** [comment]
The following items could not be completed due to the reasons noted:
* Average execution time for tests
   * REASON: Most tests are recorded as taking 0 seconds to complete
* Average number of lines of code covered by a test
   * REASON: From what I've been told, there are memory issues preventing us from running code coverage reports

**Comment by pjhill** [comment]
Hooray, thanks for getting these measured and visualized!
