### ISSUE TITLE
Visualize E2E Test Characteristics

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44571]
# Description
Given the data available regarding e2e test characteristics we need to visualize several key measurements for the platform. We intend to be able to identify trends in the end-to-end test suite characteristics. We would like to be able to answer questions like --
1. Are there more test specs being added to the suite over time?
~2. How long does it take to execute the test suite over time?~
~3. How in-depth is the end-to-end test suite?~

# Tasks
- [x] Create a dashboard for platform-wide visuals of end-to-end test suite characteristics
- [x] Visualize the number of test spec files processed by CI workflow over time
- [x] Visualize the average number of tests per test spec file over time
- [x] Visualize the average execution time per test over time
- [ ] ~Visualize the average number of lines of code covered per test over time~

* Consider grouping the `over time` visuals into a single line chart

# Acceptance Criteria
- [x] A dashboard containing key characteristics of the end-to-end test suite over time is publicly available.

**Comment by holdenhinkle** [comment]
Dashboard link - https://va-gov.domo.com/page/1232474697?userId=1184725726

Visualize the number of test spec files processed by CI workflow over time
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ebeceb8d-ed32-439a-a7f7-b745809221cc)

Visualize the average number of tests per test spec file over time
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/6563757b-6821-4a64-89f2-1eb0005c7760)

The following can't be done:
Visualize the average number of lines of code covered per test over time
=> i've been told there's a memory issue with code coverage right now

**Comment by holdenhinkle** [comment]
My query is grabbing the correct data. To verify:

This:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/894b4e4f-b2c7-4770-b5fa-61744cbbb36b)

Corresponds to this:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/9b5cb7fd-d6d1-4cbd-a075-be7a01988614)

**Comment by holdenhinkle** [comment]
The query:
```SQL
SELECT DATE(runs.start) AS date,product_directory.product_name, results.file, title, AVG(duration) AS duration
FROM `vsp-analytics-and-insights.vsp_testing_tools.cypress_test_suite_executions` AS runs
JOIN `vsp-analytics-and-insights.vsp_testing_tools.cypress_test_results` AS results
ON runs.id = results.cypressTestSuiteExecutionsId
JOIN `vsp-analytics-and-insights.vsp_testing_tools.vfs_product_directory` AS product_directory 
ON results.product_id = product_directory.product_id
LEFT JOIN UNNEST(results.suites) suites_level_1
LEFT JOIN UNNEST(results.tests) tests_level_1
LEFT JOIN UNNEST(suites_level_1.suites) suites_level_2
LEFT JOIN UNNEST(suites_level_1.tests) tests_level_2
LEFT JOIN UNNEST(suites_level_2.suites) suites_level_3
LEFT JOIN UNNEST(suites_level_2.tests) tests_level_3
LEFT JOIN UNNEST(suites_level_3.suites) suites_level_4
LEFT JOIN UNNEST(suites_level_3.tests) tests_level_4
LEFT JOIN UNNEST(suites_level_4.tests) tests_level_5,
UNNEST([tests_level_1.duration, tests_level_2.duration, tests_level_3.duration, tests_level_4.duration]) AS duration,
UNNEST([tests_level_1.title, tests_level_2.title, tests_level_3.title, tests_level_4.title]) AS title
WHERE duration IS NOT NULL AND duration > 0 AND title IS NOT NULL AND results.product_id IS NOT NULL
GROUP BY date, product_name, results.file, title
ORDER BY date DESC, product_name, results.file, title;
```

**Comment by holdenhinkle** [comment]
## Visualize the average execution time per test over time

Approach:
Make the following drill-down graph series:
graph or list of products
=> graph or list of specs
=> => graph or list of tests
=> => => graph of time it takes to execute each test by day, over some time period

Here's the link to the top-level table - https://va-gov.domo.com/kpis/details/1230795134

The card lives on the E2E Dashboard page, at the bottom - https://va-gov.domo.com/page/1232474697

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/085a60fd-3d11-48bd-99d6-c07d5f192c79)

**Comment by holdenhinkle** [comment]
This ticket is done.

**Comment by pjhill** [comment]
This data is super neat. I think this will come in quite handy while assessing test specs as a platform or if we can get this data into the hands of the product teams contributing the test specs. I expect teams to take more active roles in managing their Cypress execution times as we shift over to continuous deployment strategies.
