### ISSUE TITLE
Visualize Volume of Support Related to E2E Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44572]
## Issue Description
Given the data available regarding support requests related to E2E Tests, visualize aspects of the data in Domo.

One goal from these visuals is to help identify trends over time. Consider visualizing these measurements separately and together over time. Trend lines might be useful.

## Tasks
- [x] Create a dashboard for platform-wide visuals regarding the characteristics of support requests related to end-to-end tests
- [x] Visualize Total number of support requests assigned to quality assurance team
- [x] Visualize topic of each support request assigned to QAS team
- [x] Visualize number of support requests caused by e2e test failures
- [x] Visualize number of support requests caused by e2e test flakiness in the CI workflow

# Acceptance Criteria
- [x] A dashboard visualizing support requests related to QA standards and e2e tests for the entire platform is publicly available

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/233509314

Dashboard is here! Made 7 cards I thought were useful. Totally open to any feedback on visualizing them differently or adding additional ones.

**Comment by pjhill** [comment]
This is great, and can be used to guide a lot of discussion about what we support and how we support it. Thanks for these visuals!
