### ISSUE TITLE
Add introductory sentence to Resources page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44577]
## User Story
As a VFS team member, I want to know what the various Collab Cycle resources are so that I understand how best to use them if/when I navigate to the Platform Website Resources page. 

Assignee: @jimuhh 
Peer Reviewer: @CherylEvans 

## Description
Platform Content blocked the launch of our revised Resources page because it does not include any introductory text. Per @laucon, "We feel the document needs an introductory sentence to explain what these resources are for."

## Impacted Artifacts
[Resources page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/1764491265/Resources)

## Tasks
- [ ] Create a Resources draft page
- [ ] Add an introductory sentence explaining the various CC resources
- [ ] Submit for peer review

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] The Collaboration Cycle Resources page on Platform Website has an introductory sentence explaining what these resources are for.

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by jimuhh** [comment]
[Intro added. ](https://vfs.atlassian.net/wiki/spaces/PWD/pages/1764491265/Resources)

**Comment by CherylEvans** [comment]
@jimuhh Peer reviewed and approved, after verbiage change.

**Comment by CherylEvans** [comment]
@jimuhh Peer review box checked!  :-)

**Comment by jimuhh** [comment]
AC checked.
