### ISSUE TITLE
Visualize Impact of E2E Tests on CI Workflow

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44575]
# Description
Given the data available regarding CI workflow impact, visualize aspects of the data in Domo.

# Tasks
- [ ] Create a dashboard for platform-wide visuals of the impact from e2e testing in CI workflows
- [ ] Visualize total number of workflow executions vs. failures
- [ ] Visualize categorized causes for workflow failures
- [ ] Visualize number of workflows failing due to persistently failing e2e tests, flaky e2e tests, total workflow failures

# Acceptance Criteria
- [ ] A dashboard containing end-to-end testing impact on CI workflow is publicly available in Domo
- [ ] The **CI Workflow Impact** dashboard contains visuals for:
  - [ ] Total of workflow executions vs. failed executions
  - [ ] Categorized workflow failure causes over time
  - [ ] Total workflow failures vs. failures from e2e tests vs. failures from flaky e2e tests

**Comment by JoeTice** [comment]
An individual dashboard is no longer needed for this, and will be instead reflected on the [overall dashboard](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/44690)
