### ISSUE TITLE
Visualize AWS Infrastructure Impact on E2E Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#44573]
## Issue Description

Given the data available regarding E2E test impact on AWS infrastructure, visualize aspects of the data in Domo.

---
## Tasks
- [ ] Create a dashboard for platform-wide visuals of E2E Test impact on AWS infrastructure
- [ ] Visualize CPU use time by self hosted runners during Cypress execution
- [ ] Visualize Memory usage by self hosted runners during Cypress execution
- [ ] Visualize associated cost with operating self-hosted runners

* Consider visualizing these measurements over time in order to help identify trends

# Acceptance Criteria
- [ ] A dashboard containing E2E test impact on AWS infrastructure for the entire platform is publicly available

**Comment by CBonade** [comment]
After some feedback, the scope of this changed a bit to visualizing the impact of infrastructure on the CI workflow. This is covered by #44946. Recommend closing

**Comment by JoeTice** [comment]
An individual dashboard is no longer needed for this, and will be instead reflected on the [overall dashboard](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/44690)
