### ISSUE TITLE
Ensure touchpoint labels are added to Collab Cycle Request tickets via Operational docs

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44580]
## User Story
As a Governance team member, I want to make sure the appropriate labels are added to the Collab Cycle Request tickets when the specific touchpoint is held so that we can easily query and find completed Collaboration Cycle touchpoints.

Assignee: @seanasewell 
Peer Reviewer: @chaseakirby 

## Description
Prior to the launch of the Collaboration Cycle Request template, Design Intent templates had the `design-intent` label, Midpoint Review had the `midpoint-review` label, and Staging Reviews had the `staging-review` label. These labels, in conjunction with the `collab-cycle-review` allow us to easily query and see the completed Collaboration Cycle touchpoints.

The purpose of this ticket is to modify our Collaboration Cycle operational process (aka Moderator Responsibilities) for Design Intent, Midpoint Review, and Staging Review so that we add the appropriate label when the review is scheduled.

## Tasks
- [x] Modify the Moderator Responsibilities doc for Design Intent so there is a step to add the `design-intent` label to the teams Collaboration Cycle Request ticket with the review is scheduled.
- [x] Modify the Moderator Responsibilities doc for Midpoint Review so there is a step to add the `midpoint-review` label to the teams Collaboration Cycle Request ticket with the review is scheduled.
- [x] Modify the Moderator Responsibilities doc for Staging Review so there is a step to add the `staging-review` label to the teams Collaboration Cycle Request ticket with the review is scheduled.
- [x] View the [Collaboration Cycle Reviews Zenhub board](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board)
   - [x] Review every ticket on the board (excluding the test tickets in the Closed pipeline that were used for our usability testing)
   - [x] If the ticket has had a Design Intent meeting or has one scheduled, add the `design-intent` label
   - [x] If the ticket has had a Midpoint Review meeting or has one scheduled, add the `midpoint-review` label
   - [x] If the ticket has had a Staging Review meeting or has one scheduled, add the `staging-review` label

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Operational docs are updated to add `design-intent` label when Design Intent is scheduled
- [x] Operational docs are updated to add `midpoint-review` label when Midpoint Review is scheduled
- [x] Operational docs are updated to add `staging-review` label when Staging Review is scheduled
- [x] All Collaboration Cycle Request tickets that have been created since May 26, 2022 have been updated to reflect the appropriate labels.

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by seanasewell** [comment]
@shiragoodman Once a ticket moves from Design Intent to Midpoint Review, is the design-intent label removed and replaced with the midpoint-review label? Or is the midpoint-review label just added to the ticket along with the pre-existing design-intent label?

**Comment by shiragoodman** [comment]
@seanasewell just added! The goal will be that we can see at a glance what touchpoints occurred for the product.

**Comment by shiragoodman** [comment]
@seanasewell i modified this ticket to clarify the Tasks. The correct labels are now added. Please review and let me know if you have any other questions. thanks!

**Comment by seanasewell** [comment]
@briandeconinck Ready for peer review. Note that MR Moderator Responsibilities doc has synchronous and asynchronous sections. I added label instructions to both.

**Comment by chaseakirby** [comment]
@seanasewell The operational documents look good!
For the ZenHub board, I think that the touchpoint labels should only be added at the "Scheduled" pipeline, right now ticket #42601 has the Design Intent label while still Awaiting Design Intent Scheduling.
I believe this is across the board currently for other tickets as well.

**Comment by seanasewell** [comment]
@chaseakirby I got a little label happy. I made the updates. Good catch!

**Comment by chaseakirby** [comment]
@seanasewell It happens to the best of us!
I removed a couple of other midpoint-review labels from Claims Status Tools and VAOS.
This looks good to me! I have checked the AC have been met so this ticket looks ready to close.
