### ISSUE TITLE
Add introductory sentence to Disability Etiquette page

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#44581]
## User Story
As a VFS team member, I want to know how interacting with research participants with disabilities may differ from other participants so that I understand how best to use the recommendations on the Platform Website Disability Etiquette page. 

Assignee: @jimuhh 
Peer Reviewer: @briandeconinck 

## Description
Platform Content blocked the launch of the Disability Etiquette page (child page of [Conducting Research Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/conducting-research-sessions)) because it does not include any introductory text. Per @laucon, "We feel the document needs an introductory sentence to explain what the document is about."

## Impacted Artifacts
[Disability Etiquette page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2261254165/Disability+Etiquette)

## Tasks
- [x] Create a Disability Etiquette draft page
- [x] Add an introductory sentence explaining the purpose of the Disability Etiquette page
- [x] Submit for peer review

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] The Disability Etiquette page on Platform Website has an introductory sentence explaining what the page is for.

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by jimuhh** [comment]
@briandeconinck Added draft of intro paragraph to [Disability Etiquette page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2261254165/Disability+Etiquette)
LMK if you think this is the right direction.

**Comment by briandeconinck** [comment]
@jimuhh I like this a lot. Two suggested changes:

> Whether or not you have a disability that shows, it’s likely that at some point in your life you've experienced, or someday will experience, the uncomfortable sensation of having other people judge you, categorize you, and assume wrong things about you based on your age, sex, height, skin color, identified gender or other feature.

Consider simplifying this to "... judge you, categorize you, and assume wrong things about you based on their perceptions of you" or something similar. Since these are disability etiquette guidelines, I'm thinking mentioning other attributes and identities might muddle things a little. And since it's a pretty long sentence already, trimming it down a little should help with readability.

> Nobody likes feeling reduced to the sum of someone else’s preconceptions, and people with disabilities feel this way far too often.

Consider dropping the second half of this sentence ("and people with disabilities..."). I think the message is clear without it, and we don't want to overcorrect and project too much onto our disabled research participants. Some of them might not feel this way, and we don't want researchers assuming that they do! 

I also fixed two typos I spotted. Otherwise this is great!

**Comment by jimuhh** [comment]
Thank @briandeconinck If you would like to trim and edit it into the form you think better, I have zero problem with that. I'm used to being edited 😁

**Comment by jimuhh** [comment]
Hi @briandeconinck. I edited the first paragraph as per your reccos.

**Comment by briandeconinck** [comment]
This looks great @jimuhh!
