### ISSUE TITLE
Analytics & Insights Orientation - September

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#44588]
## Issue Description
As part of new VFS team member orientation the Analytics & Insights team will complete a monthly orientation the first Thursday of the month.  Team can sign up for the on the [Collaboration Cycle Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_7iurst2mk3hdhfuto5u7lemgbk@group.calendar.google.com&ctz=America/Chicago).

---
## Tasks
- [ ] Conduct [Platform Analytics & Insights Orientation](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71)

## Acceptance Criteria
- [ ] Training completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Completed.
