### ISSUE TITLE
Analytics Implementation or QA Support for Find VA Forms

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4458]
# Analytics Implementation or QA Request

## Description
- Is this request for Google Analytics implementation or QA?

This is a request for determining GA events that should be captured for our upcoming content page (which also contains a React widget) for searching VA forms. 

The Epic for this work is here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/1632, and the ticket for the front-end devs to implement analytics is here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/3606. The "beta" version of the page is here - https://dev.va.gov/find-va-forms-beta/?q=test.

- Who is this request for?
    - Jennifer Lee, Kara Kemahli
    
- What team/project is this work for?
    -  VSA Public Websites Team (#vsa-public-websites on DSVA Slack)
    
- Provide the Domain where Google Analytics needs to be implemented
    - dev.va.gov in the beginning, but all environments 
   
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - We're hoping to launch this the week of January 13th, 2020.

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - Only one URL. We're currently working with `www.va.gov/find-va-forms` but this could change. After the form is submitted to perform a search, the user's query will be reflected in the address bar. So if you search `test`, then the url path will be `/find-va-forms-beta/?q=test`.
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - We're also interested in tracking the link clicks throughout the rest of the page , such as under `Top tasks for frequently downloaded VA forms`.

> Please leave the following blank

## Acceptance Criteria
- [ ] Review why _gaLinker is appended when it is the same domain, which should resolve PDF Download trigger not working
- [ ] QA has been completed
- [x] Query to capture search terms is established in staging and then production
- [ ] Reports shared with VSA Public Websites team

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@ncksllvn Thanks for looping us in. I tweaked the acceptance criteria to include a few items we need to tackle on our end. For your reference:

1. Capturing the search term - Since `q` has been used as another search parameter, this is already established. If you think the parameter might change, please let us know and we can update before launch. 

- For Public Websites Team Analysis: Once live, the [Behavior>Search Usage report will populate with a report like so:](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w178298118p184600834/_u.date00=20190901&_u.date01=20191230&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22find-va-forms%22,0%5D%5D). This is an example of the test data already populating in Dev

2. Tracking interactions with PDF forms - This is also configured, but we need to make some tweaks to it as it's not currently capturing.

@jonwehausen For reference, the _gaLinker is being appended to clicks from https://dev.va.gov/find-va-forms-beta/?q=test to a specific form. Because the form is no longer ending in `pdf`, the RegEx for the File Download trigger isn't working.

3. Top Tasks tracking - I inspected the CSS but have less familiarity than you and Jon. Is this a common style component? Once we know, we can then craft the dataLayer requirements. 

Thanks!

**Comment by jonwehausen** [comment]
Hi @nedierecel , 

### **Regarding No. 2**

- I was seeing PDF download events for all of the forms listed in the table on that [page](https://dev.va.gov/find-va-forms-beta/?q=test). Could you clarify a bit more where the break is occuring? 

### **Regarding No. 3**
Sure -- The top tasks component is considered '[Featured content](https://design.va.gov/components/featured-content)' according to the design system and we've used a DL standard for these prior. 
![image](https://user-images.githubusercontent.com/48527022/71682572-17eff900-2d5e-11ea-9cd2-0e26c79f3fc0.png)

**Comment by nedierecel** [comment]
Thanks @jonwehausen - For #1, can you please attempt to download file 10-0137? 

Both the link click and click did not trigger the File Download:
![image](https://user-images.githubusercontent.com/24525739/71686942-9f436980-2d6a-11ea-83ad-08dd4d8d274c.png)

**Comment by jonwehausen** [comment]
Hi @ncksllvn, 

### #2
Nedie and I identified a fix within GTM that will resume PDF download tracking on forms listed here. We are going to break-off the gaLinker caveat into a separate bug. 

### #3
For the featured content clicks (blue boxes at the bottom of the page), this is DL requirements we will need: 
```javascript
dataLayer.push({
  'event': 'nav-featured-content-link-click', 
  'featured-content-header': 'File a VA Disability claim' //dynamically populate with header text
});
```

**Comment by jonwehausen** [comment]
Hi @ncksllvn , 

Can you confirm if your team has capacity to deliver the dataLayer push outlined above in #3? 

Thanks in advance.

**Comment by ncksllvn** [comment]
We definitely have bandwidth! 

Those "Top tasks" do have a lot in common with Featured Content, but I think it's being considered as a new component (maybe a "card") rather than Featured Content.

I learned recently that those links under VA Form Number won't download the PDF. Instead, they'll link to a "Forms Details" page, like `/forms/101020`, and that page will contain the actual download. Sorry, I didn't understand that part before.

**Comment by jonwehausen** [comment]
Hi @ncksllvn,

Thanks for the updates! Resurfacing some of Slack conversation highlights here. 

- Regarding the PDF downloads -- we have this globally set site-wide to pickup for when ```.pdf``` is surfaced in the click URL so shouldn't need any adjustment there. 

- ```q``` is configured as the site search parameter in prod so we will have insight into common searches
- As for the featured content distinction -- per our Slack convo, let's keep these guys identified as featured content and thus utilizing the DL push outlined below: 

```javascript
dataLayer.push({
  'event': 'nav-featured-content-link-click', 
  'featured-content-header': 'File a VA Disability claim' //dynamically populate with header text
});
```

Keep us posted on when we're ready for QA. 
cc: @nedierecel @joanneesteban

**Comment by ncksllvn** [comment]
@jonwehausen implemented! Should be updated at https://staging.va.gov/find-va-forms-beta/ any minute.

**Comment by jonwehausen** [comment]
Thanks @ncksllvn !

The DL pushes look good and events are staged 👍 

DataLayer | Event [GTM Preview]
------------ | -------------
![image](https://user-images.githubusercontent.com/48527022/72900776-7faeb980-3cf6-11ea-8295-5b479822541f.png) | ![image](https://user-images.githubusercontent.com/48527022/72900816-935a2000-3cf6-11ea-8ce4-48d36c0a58de.png)
![image](https://user-images.githubusercontent.com/48527022/72900988-e7fd9b00-3cf6-11ea-88d1-8e0dc3f070c4.png) | ![image](https://user-images.githubusercontent.com/48527022/72901600-129c2380-3cf8-11ea-8c90-e0c3c9ebd6cb.png) | 
![image](https://user-images.githubusercontent.com/48527022/72901754-51ca7480-3cf8-11ea-9b8f-c989a7856fb8.png) | ![image](https://user-images.githubusercontent.com/48527022/72901695-32cbe280-3cf8-11ea-93e6-37d6de89ca3f.png)

CC: @nedierecel

**Comment by jonwehausen** [comment]
@nedierecel I've consolidated this story and 3238 into one GTM workspace since they both update the Navigation Action Lookup table. 

[See workspace here. ](https://tagmanager.google.com/?authuser=0#/container/accounts/144676348/containers/2214120/workspaces/746)

**Comment by Karak888** [comment]
Closing as analytics team has this in their Pipeline @nedierecel - if anything further is needed from us please reach out. We have added our Find a vA Forms epic for tracking and visiblity!  Thanks
