### ISSUE TITLE
Content review of 10-10CG confirmation page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44599]
## Issue Description
The 10-10CG team asked us to do a content review of the confirmation page for their form. They needed to make updates to more accurately inform applicants about the post-submission timeline in anticipation of some downstream processing changes that they'll be making.

Content to review: [https://app.zenhub.com/files/133843125/85f6e8a2-2ad1-4d68-9ec6-66999d9cc6f1/download](https://app.zenhub.com/files/133843125/85f6e8a2-2ad1-4d68-9ec6-66999d9cc6f1/download)

Here's a screenshot of what it will look like: https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/rbv4gDx

Original intake request ticket for more background: #44510

We need to edit this copy for plain language and to make sure it adheres to VA.gov's style guide. 

Once we have completed the work, we'll post it in the intake ticket for the product team.

## Tasks
- [x] Edit confirmation page
- [x] Review changes (Laura)
- [x] OCTO-DE review (Danielle)
- [x] Final copyedit (Megan)
- [x] Post updated content in ticket #44510 (Megan)

## Acceptance Criteria
- [x] Approved content has been past to product team

**Comment by katherine-fung** [comment]
Hi @laurwill, this draft is ready for your review: 

[https://app.zenhub.com/files/133843125/7be1edb4-3c08-4ffd-bcab-5a15a1692b67/download](https://app.zenhub.com/files/133843125/7be1edb4-3c08-4ffd-bcab-5a15a1692b67/download)

**Comment by katherine-fung** [comment]
Hi @laurwill. Here's an updated version of the draft: 

https://dvagov-my.sharepoint.com/:w:/g/personal/katherine_fung_va_gov/EUx1ig7efM5NgrP0uTnZoFEBt4N3S3yowC71n1LdOjRD4Q?e=7QmYlB 

I incorporated new information from the product team. 

(For reference, the product team said: 

So, we learned that both the phone and the mail may be used when there is no email address present. They weren't exactly clear about it, because it seems like there isn't an explicit set of steps they follow, but it sounds like it's a contact method hierarchy: email (if present), then phone, then mail. Official correspondence and application decisions are still always sent via mail, though.

@ hdjustice @ batemapf Please correct me if I'm wrong but, I think the initial email response is automated, so that's why it shows up within a fixed time frame, but the phone call/mail isn't, so doesn't necessarily have a fixed time frame. For phone calls in general, however, the VA is supposed to get back to you within 3 business days, I believe.)

**Comment by katherine-fung** [comment]
@laurwill - attaching a local non-sharepoint version of the doc to download! 

[https://app.zenhub.com/files/133843125/11c9c675-f63f-4492-8497-100cacad958e/download](https://app.zenhub.com/files/133843125/11c9c675-f63f-4492-8497-100cacad958e/download)

**Comment by laurwill** [comment]
Thanks so much Katherine! And thanks for hopping on zoom to look at the updates together.

@DanielleThierryUSDSVA , do you want to take a look at the doc with our questions before Megan copyedits, in case you have larger changes you'd like us to make? As we chatted, we can also draft similar text updates to the [10-10EZ confirmation page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxvza3r) once we have suggested text for this one.

[10-10CG confirmation page.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9352631/10-10CG.confirmation.page.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @laurwill! Changes/comments attached. I'll send you a slack to talk through these so we can get this over to the team asap. Thanks!
[10-10CG confirmation_dt](https://app.zenhub.com/files/133843125/80ca4824-401f-4d83-96aa-ca2863718ba7/download
)

**Comment by laurwill** [comment]
Thanks so much Danielle, and thanks for chatting through on slack! 

@megzehn , here's the doc for your copyedit — the doc was getting a bit crowded so I cleaned up, but you can look at the version Danielle uploaded in the previous comment if you want to see tracked changes. 
[10-10CG confirmation page.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9425580/10-10CG.confirmation.page.docx)

Once you're done, I'll pass to the design team with a few notes. Thank you!

**Comment by laurwill** [comment]
Hi again @megzehn , since I'm offline this afternoon, if you finish your copyedit could you go ahead and post the doc in the [ intake ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44510) for this request? Here's a comment you can post with the document: 

Thanks for your patience as we reviewed this confirmation page content! Here’s our suggested text. We made some updates for site style, like:
- Using “we” instead of Caregiver Support Program/Caregiver Support Coordinator
- Keeping the alert at the top more brief and moving info about what happens next to the separate H2
- Swapping an instance of the long form name for plainer “your application information” language

We also wondered if a green success alert might be a good fit for the "Thank you" text at the top, rather than an info alert.

Please let us know if you’d like to chat about any of our suggested changes! We’d be happy to discuss.

**Comment by megzehn** [comment]
Thank you so much, @laurwill!! I copyedited the doc and sent over the updated doc on the intake ticket. Posting it here as well (with very minor tweaks). 

[10-10CG.confirmation.page_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9427571/10-10CG.confirmation.page_copyedited.docx)

**Comment by laurwill** [comment]
Thanks Megan! Closing this out.
