### ISSUE TITLE
Create and Launch Research Survey: QA on VA.gov

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44595]
## Issue Description
Create research survey in optimal workshop to obtain VFS sentiment on various aspects of QA on VA.gov.

---
## Tasks
- [x] Gather topics/question suggestions from the team
- [x] Gather topics/question suggestions from PO
- [x] Review w/ Naomi & Chelen
- [x] Enter into Optimal workshop

## Acceptance Criteria
- [x] Survey is approved and has been launched

**Comment by JoeTice** [comment]
Survey was launched 8/11
