### ISSUE TITLE
Add Novavax vaccine information to relevant COVID-19 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44607]
## Issue Description

Once Novavax passes final CDC ACIP approval, we'll need to add information about it to our vaccine pages. We already did an audit of our COVID-19 pages in ticket #42704 to identify places where it makes sense to do so. 

When we make these updates, we should also consider making the age eligibility updates also noted in that previous ticket. 

## Tasks
- [ ] Add new vaccine info to COVID pages
- [ ] Copyedit (Megan)
- [ ] Publish pages (Megan)
- [ ] Send finalized content to translation team (Randi)

## Acceptance Criteria
- [ ] Novavax information is live on the site

**Comment by RLHecht** [comment]
Here is the new content that we need to add to our COVID pages. @laurwill do you want to take a look through before we have someone add the changes to Drupal in case we need to send this back for plain language edits?

[https://app.zenhub.com/files/133843125/892b60d3-be50-4d9a-b804-47eae2c43e64/download](https://app.zenhub.com/files/133843125/892b60d3-be50-4d9a-b804-47eae2c43e64/download)

[https://app.zenhub.com/files/133843125/2926ec4a-6054-4706-9776-358189b02d2d/download](https://app.zenhub.com/files/133843125/2926ec4a-6054-4706-9776-358189b02d2d/download)

**Comment by laurwill** [comment]
Hi @katherine-fung , updates for the main COVID vaccine page are ready for you. Changes are theoretically tracked, but I saw a couple of untracked ones in another doc, so could you compare against live site to be certain
[Main vaccine page.LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9269485/Main.vaccine.page.LW.docx)

Let me know if you have questions! After you update Drupal, you can pass to Megan for copyedit.

We'll have updates for the "about" page later today after we get approval for a couple edits.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

This page is ready for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=11463 

Melissa flagged the link for this text as not working: "Learn more about COVID-19 vaccines during pregnancy or breastfeeding" [https://va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine#vaccines-during-pregnancy-or-b]

Can you confirm in your review? It's a jump link - I can see that page/section in Drupal preview, but the URL isn't working for me either, and I wasn't sure if we need to do something special/different with the URL. 

Thanks!!

**Comment by RLHecht** [comment]
@katherine-fung Here is the word doc with edits to update the About page with. Once you're done you can pass this to Megan as well. Thanks!

[https://app.zenhub.com/files/133843125/3de35e29-2e31-4207-922f-3b0ee4e5c57e/download](https://app.zenhub.com/files/133843125/3de35e29-2e31-4207-922f-3b0ee4e5c57e/download)

**Comment by megzehn** [comment]
Hi @katherine-fung - the jump link looks correct! 

The "www" is missing in this link you pasted (https://va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine#vaccines-during-pregnancy-or-b). Since we link to the node in the CMS, that shouldn't be an issue. The jump link seems to be working on the [existing live page as well.](https://www.va.gov/health-care/covid-19-vaccine/) And I double checked that we didn't edit the H2 text, so the jump link should remain intact.  

I'm not sure if Melissa was looking at a preview of the new page in the CMS, but all internal links (that link to the node) show an error there, so that could be the issue. 

Separately, confirming that I reviewed all the changes on nodeId=11463 and published them. Thanks @katherine-fung. CC @RLHecht

**Comment by katherine-fung** [comment]
Hi @megzehn, the "About COVID-19 vaccines" page is ready for you: 

http://preview-prod.vfs.va.gov/preview?nodeId=34627 

Note: The copy in the "You should get a COVID-19 vaccine even if you’ve had COVID-19 before" accordion diverges slightly from the Word doc, per Randi and Laura. We will say the following for now, and confirm with Danielle on Monday: 
 
"Data from clinical trials show that the authorized COVID-19 vaccines are safe in people who’ve been infected with the virus that causes COVID-19 in the past."

**Comment by megzehn** [comment]
I reviewed changes and published this on Friday p.m.

**Comment by megzehn** [comment]
moving this over to validate, @RLHecht!
