### ISSUE TITLE
Supplemental Claims | Get issues in the legacy appeals process

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44610]
## Value Statement

**_As a_** system
**_I want to_** fetch issues in the legacy appeals process 
**_So that_** claimants select those issues when they are filing a supplemental claim.

## Background Context

When claimants select issues for review, they may choose issues that are currently in the legacy appeals process. These issues need to be visible for the claimant to select, and they also need to be moved into the new decision review process, as per the Appeals Modernization Act.

The backend will copy the pattern used by the Higher-Level Review contestable issues endpoint:
- Get contestable issues from [`/contestable_issues/supplemental_claims`](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) (HLR uses an older endpoint)
- Get legacy issues from [`/legacy_appeals`](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current)
- Then combine the results such that the frontend receives the legacy appeals summary as the last data entry, as in this example:

    <details><summary>Example combined contestable & legacy issues</summary>

    
    ```json
    {
      "data": [{
        "id": null,
        "type": "contestableIssue",
        "attributes": {
          "ratingIssueReferenceId": "142894",
          "ratingIssueProfileDate": "2021-03-12",
          "ratingIssueDiagnosticCode": "5260",
          "ratingIssueSubjectText": "Ankylosis of knee",
          "ratingIssuePercentNumber": "10",
          "description": "Service connection for Ankylosis of knee is granted with an evaluation of 10 percent effective December 2, 2020.",
          "isRating": true,
          "latestIssuesInChain": [{
            "id": null,
            "approxDecisionDate": "2021-03-12"
          }],
          "decisionIssueId": null,
          "ratingDecisionReferenceId": null,
          "approxDecisionDate": "2021-03-12",
          "rampClaimId": null,
          "titleOfActiveReview": null,
          "sourceReviewType": null,
          "timely": true
        }
      }, {
        "id": "35",
        "type": "legacyAppeal",
        "attributes": {
          "issues": [{
            "summary": "Service connection, benign ear neoplasm"
          }, {
            "summary": "New and material evidence to reopen claim for service connection, impairment of knee"
          }, {
            "summary": "Service connection, migraines"
          }],
          "veteranFullName": "Cara Bartlett",
          "decisionDate": "2021-10-17T00:00:00.000Z",
          "latestSocSsocDate": "2021-09-18T00:00:00.000Z"
        }
      }]
    }
    ```
    </details>

## Tasks

- [ ] The backend combines the contestable & legacy issue endpoints from Lighthouse
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie @rocio-desantiago I'm working on the tickets we discussed in our last refinement session. Can you help me list the tasks and background context for this issue?
