### ISSUE TITLE
Update vets-api auth callback URLs to use new API domain

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44618]
## Issue Description
The auth callback URL settings fall into the ["VA.gov-only" category of API domain references](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538) within vets-api. 

To ensure that they continue to work correctly after the Lighthouse migration, they would need to be updated to using the _new_ vets_api urls, `*platform-api.va.gov`.

The identified settings are:
- `idme.redirect_url`
- `logingov.redirect_url`
- `logingov.inherited_proofing_url`
- `saml_ssoe.callback_url`

These settings exist in dev, staging, and production.

---
## Tasks
- [ ] Settings updated and tested in dev env
- [ ] Settings updated and tested in staging env
- [ ] Settings updated and tested in prod env

## Acceptance Criteria
- [ ] All settings changed and tested in all relevant environments.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
All of these are owned by the @department-of-veterans-affairs/vsp-identity team.
And, each one involves a partner configuration with the corresponding identity broker or credential provider (ID.me/Login.gov/SSOe) - the relevant partner will need to add `platform-api.va.gov` (or per-env variant) as a supported callback URL, and only then can vets-api can begin specifying that in the SAML or OAuth request. 

So this will require a bunch of coordination and should be managed by the identity team.

**Comment by joeniquette** [comment]
thanks @patrickvinograd we can certainly jump in to help. @madebydna when this can go live can you please schedule something with us so we can coordinate the code change.

**Comment by madebydna** [comment]
@joeniquette, I think this ticket is actionable right now. Do you have office hours, or what would be the best way of setting up a meeting with your team to discuss this?

**Comment by alwerner** [comment]
@joeniquette Given that we don't have a timeline for the actual release, should we close this ticket? CIT will be wrapping up on Sept. 9. Maybe duplicate it for your backlog?

cc: @madebydna

**Comment by joeniquette** [comment]
Sounds good!
