### ISSUE TITLE
Translation work for PACT Act content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44612]
## Issue Description

Once we have finalized content for PACT Act information, we need to send this to our translators and create new Drupal nodes with the translated content.

When the new translated pages are ready to publish, we may need to work with Public Websites for any front-end work they might need to do. I'll add more tasks once we get more information about publishing new translated pages.

## Tasks
- [x] Send content to translation team (Randi)
- [x] Build Spanish page in Drupal (Aliyah)
- [x] Review Spanish page against Word doc and English page (Megan)
- [x] Build Tagalog page in Drupal (Aliyah) 
- [x] Review Tagalog page against Word doc and English page (Megan)
- [x] 3 new Spanish questions
- [x] QA review for Spanish
- [x] 3 new Tagalog questions
- [x] QA review for Tagalog

## Acceptance Criteria
- [x] Translated PACT Act pages are live on the site

**Comment by jilladams** [comment]
@RLHecht @DanielleThierryUSDSVA for PW work on this in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9918, can you clarify how many pages we should expect to come in this first round? We thought just one but want to make sure.

**Comment by RLHecht** [comment]
Yes, it would be just one FAQs page to start. Though the English version is set up as individual Q&A nodes in Drupal.

**Comment by jilladams** [comment]
Hiya - midsprint checkin: how are you all feeling about the likelihood of these translations being ready this week?

**Comment by RLHecht** [comment]
@jilladams We just got in the Spanish translation so will be able to start putting that into Drupal now. 

@aliyahblackmore could you please flow this into Drupal as a R&S detail page?

[https://app.zenhub.com/files/133843125/d6d73052-02f7-4009-b647-75849b1fa986/download](https://app.zenhub.com/files/133843125/d6d73052-02f7-4009-b647-75849b1fa986/download)

**Comment by aliyahblackmore** [comment]
Thank @RLHecht ! 
Hi @megzehn the Spanish page is ready for you! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=48330


### A few notes: 

- The Spanish "Call to Action" links text exceeded the chararcter limit. Randi flagged this with Danielle adn confirmed that I should include those links under the text of the first H2 question **"¿Qué es la Ley PACT y cómo afectará mis beneficios y cuidado de la salud de VA?"**
- In the page intro, "De igual forma," should we left as is.
- There were a few instances of numbers being spelled out on the translation doc.  I changed those to numerals so that they are in line with the [English version ](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/#getting-benefits)of the page, as well as with the [VA style guide!](https://design.va.gov/content-style-guide/numbers)
- Under the Accordion "¿Qué nuevas ubicaciones presuntas del agente naranja añadirá VA?" you'll notice that there isn't a comma before "al." Though in English this is the case, this wouldn't be the case in Spanish; I did a quick double check in google translate as well and got "al" without the comma before.
- Under the H2 "Getting Benefits" on the English page, there were some changes to the text under accordion " What if VA denied my claim but now considers my condition presumptive?" and it is now  "...we'll review the claim again." This wasn't initially in the doc sent to translators so Danielle/Randi flagged that this should be changed and will be reviewed by the translation team. I was given the okay to change the Spanish text which is now,  "...volveremos a revisar la reclamación." cc: @RLHecht 
- Also flagging for consistency/style. Is there specific style to follow when the translated text has an acronym that will not be the same as the English version? CHAMPVA is an example. The translated text doesn't include an acroynym but has the English text after.  _**"Cuidado de la salud a través del Programa Médico y de Salud Civil del Departamento de Asuntos de los Veteranos (Civilian Health and Medical Program of the Department of Veterans Affairs, CHAMPVA) Puede calificar si es el sobreviviente o dependiente de un veterano con una discapacidad relacionada con el servicio."**_ I left this as is for the time being but wondering if this would be correct? cc: @megzehn and @RLHecht 
- There are two instances where the Spanish translation combines sentences. In the accordion "¿Qué pasa si mi fecha de alta o liberación fue antes del 1 de octubre de 2013?" The text on the Spanish page is  "La inscripción es gratuita **y** es posible que el cuidado proporcionado también sea gratuito." The text on the English page is "Enrollment is free. **And** your care may be free as well." The last accordion "¿Qué pasa si VA rechazó mi reclamación de compensación por dependencia e indemnización (DIC) y creo que ahora que soy elegible?" and last sentence is " Es posible que podamos reevaluar su reclamación, pero no tiene que esperar a que nos pongamos en contacto con usted para volver a solicitarla." The English version is, "We may be able to reevaluate your claim. **But** you don’t need to wait for us to contact you before you reapply." I am leaving the Spanish version as is for the time being, but I'm wondering if this would need to be changed to match the English version?

**Comment by megzehn** [comment]
Thanks @aliyahblackmore - great flags and questions. I went ahead and left the Spanish translation as is, but I think we should revisit the acronym question for future translations. This is now published. Thanks!

**Comment by RLHecht** [comment]
@aliyahblackmore We got the QA back from the translation team. A few things to change:

1. They translated those CTAs with new content we gave them. Can you see if they now fit as the action links and if so, remove the 2 links you put it at the bottom of that first Q&A? The are:

Presentar una solicitud de discapacidad (en inglés)
Solicitar cuidado de la salud (en inglés)

2. The change we made for "we'll review your claim again" looked good to them. 

3. For the two instances where you noted that they combined two short sentences, they gave us new edits for the first example to keep the sentences simple and to make sure they are grammatically correct in Spanish. The second one we should leave as they translated it.

For the enrollment is free one it should be changed to: La inscripción es gratuita. Es posible que el cuidado proporcionado también sea gratuito.

There are also more changes they made in this Word doc that we will need to address: 

[LS-2022-0118163 -LQM v.1 Notes-es_8.10.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9308878/LS-2022-0118163.-LQM.v.1.Notes-es_8.10.22.docx)

For their comments about lowercasing words that we had capped, I am sending an email letting them know that a lot of these (Supplemental Claims, Veterans) are our style so would want to keep capitalized. I'll let you know their response.

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht ! 

1. As discussed the CTA text is still longer than the character limits, so I've left the links in the text.

2. Re: the comment on lowercasing words that we capped, I left it as is for the time being and I'll wait until they reply to you. 

3. There were comments in the doc about changing "On this page" and "Related information," but those can't be changed as they are part of the CMS. I left them as is. 

Will standby for their reply re: uppercasing/lowercasing.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=48330

**Comment by RLHecht** [comment]
Thanks, @aliyahblackmore I heard back from the translators and we should leave terms lowercase in the Spanish version as they noted instead of following our English content style guide. I think that just means we need to go back in and lowercase Supplemental Claims since Veterans should already be lowercase throughout. 

Thanks for nothing the "on this page" and "related information" components. The "On this page" is a bug that PW was looking into. @jilladams I don't know if you have any more info on that.

@megzehn This is ready for you to review again and publish.

**Comment by aliyahblackmore** [comment]
Wonderful! Thanks, Randi! 

@megzehn this is ready for you! 

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=48330

**Comment by DanielleThierryUSDSVA** [comment]
I'm just going through PACT Act related tickets and was really struck by the thoughtfulness in this ticket. I wanted to say thank you to you all, and especially to @aliyahblackmore, for putting so much care into the Spanish content. As we move into multilingual content, it's absolutely critical that we keep quality at the core of this work just as we do with our English content. Thank you for your dedication to that. The care and thoughtfulness of this team truly shines through in all that you do.

**Comment by megzehn** [comment]
Great reminder, @DanielleThierryUSDSVA! And I echo your comments on @aliyahblackmore 's thoughtfulness. 

The Spanish updates look good. They are now published.

**Comment by RLHecht** [comment]
Update: I sent the translation team the three new questions added to the page. @aliyahblackmore we added a jump link to the intro on the English page, which points people to the survivors section. Once these new questions come back and we add them to the Spanish page (and eventually Tagalog page), we should create the jump link on the translated pages too. Thanks!

**Comment by RLHecht** [comment]
@aliyahblackmore Here are the Tagalog translations ready for you! 

[https://app.zenhub.com/files/133843125/8429330f-12c7-4d33-bb3a-fccbc1109342/download](https://app.zenhub.com/files/133843125/8429330f-12c7-4d33-bb3a-fccbc1109342/download)

[https://app.zenhub.com/files/133843125/561d4ee4-3a31-4a72-85ea-61b4cf7a5dce/download](https://app.zenhub.com/files/133843125/561d4ee4-3a31-4a72-85ea-61b4cf7a5dce/download)

**Comment by aliyahblackmore** [comment]
Got started on the Tagalog page today and will add in the jump link to the survivors section, as you mentioned.  Thanks, Randi!

**Comment by aliyahblackmore** [comment]
Hi @megzehn! The Tagalog page, including the new content, is ready for you! 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=48613

**A few notes:** 

1. As Randi mentioned, we [needed to add](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44612#issuecomment-1213334298) "and their survivors" to the page intro, with a jump link to the "Information for the survivors" section. I add this text in and the jump link. The Tagalog text, based on the use of survivor later on the page, is, "at ang kanilang mga naulila"

2. Like the Spanish page, the CTA text was too many characters. I added the links in the first H2, after the text as advised by Randi.

3. In the first H2 **"Ano ang PACT Act at paano nito maaapektuhan ang aking mga benepisyo at pangangalaga sa VA?"** PACT Act (the full name) is first in English and the Tagalog is in parenthesis after. I left this as is for the time being. This format is different from the Spanish page, so I will ask the translator if this is a preference due to how this would read in Tagalog, etc. If not, perhaps this should match the style on the Spanish page, so there's consistency.

4. There are a few instances of words/terms that are still in English. They were in the translation document as they are on the page. For example there may be a statement like, _**"Idinagdag namin ang 5 bagong lokasyong ito sa listahan ng mga presumptive location:"**_ I left them as is for the time being, but will just double check with the translators when I send them an email with the live link to do the quality assurance (QA) check.  My assumption here is that there may not be a direct translation, but if that's the case I wonder if there is any style guidance on how to make that clearer.

5. The new changes to the PACT act page were added in and they are in these sections: 

**"Kailan ko maaasahan ang desisyon ng VA tungkol sa aking PACT Act claim?"

"Makakakuha ba ng kabayarang kompensasyon ang mga naulila ng mga Beterano alinsunod sa PACT Act?"**

**"Ano pa ang ibang mga benepisyo sa VA na eligible ang mga naulila?"** 

And the text for the Related information link was included

**"Mga benepisyo sa VA para sa mga asawa, dependent, naulila, at kapamilyang caregiver (sa Ingles)"**

**Comment by megzehn** [comment]
Thanks for these great flags and questions, @aliyahblackmore! 

I copyedited it against the latest translation version we have, and went ahead and published it as is for now. Happy to make tweaks later if needed.

**Comment by aliyahblackmore** [comment]
Thanks @megzehn! Live page was sent back to the translators for the QA review!

**Comment by aliyahblackmore** [comment]
Update 8/23: Translators replied to the Tagalog QA review email and they said that everything looks great! 
[Tracker ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/translation-work/pact-act-translation-tracker.md) was updated. We are still waiting for the new Spanish content.

**Comment by RLHecht** [comment]
Hi @aliyahblackmore Here is the new Spanish content to add to the page.

Thanks!

[https://app.zenhub.com/files/133843125/ab952269-ed75-4072-abc8-de57e1c7e657/download](https://app.zenhub.com/files/133843125/ab952269-ed75-4072-abc8-de57e1c7e657/download)

**Comment by megzehn** [comment]
Changes look good, @aliyahblackmore! 

I'm not sure about the em dashes, so I think it's a great idea to flag that for the QA review. 

This is now published. Thanks again! 

CC @RLHecht

**Comment by RLHecht** [comment]
Update: Email the State Department translation team on 9/20 to confirm if this is good to close.

**Comment by RLHecht** [comment]
@aliyahblackmore We just got back the QA for the Spanish content. Can you please make the changes they recommended with the em dashes and omitting the words. You don't have to worry about the "on this page" and the "related information" sections since those are global components. I'll let them know that isn't something we can change right now. [https://app.zenhub.com/files/133843125/a40edde3-2639-433d-99b2-f783fc989179/download](https://app.zenhub.com/files/133843125/a40edde3-2639-433d-99b2-f783fc989179/download)

**Comment by aliyahblackmore** [comment]
Thank @RLHecht ! This is ready. 
**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=48330

As discussed, I added in their recommended commas and removed the "a los." 
"On this page" and "Related information" were left as is in English, as those are components that we can't edit on Drupal.

**Comment by RLHecht** [comment]
Thanks Aliyah! I reviewed and published.

**Comment by RLHecht** [comment]
This is live. Closing!
