### ISSUE TITLE
Update HealthQuest facilities endpoint configuration to use new platform API endpoint

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44620]
## Issue Description
The HealthQuest facilities endpoint setting falls into the ["VA.gov-only" category of API domain references](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538) within vets-api. The `hqva_mobile.lighthouse.url` and `hqva_mobile.lighthouse.host` settings fall into the "VA.gov --> Lighthouse" category

The (`hqva_mobile.facilities.url`) endpoint essentially uses the Lighthouse facilities API by way of the vets-api's `facilities_api` route. To ensure that the endpoint continues to work correctly after the Lighthouse migration, it would need to be updated to the _new_ vets_api url, `*platform-api.va.gov`. The other endpoints need to be routed through the forward proxy.

This setting exists in dev, staging, and production.

**Note:** According to Mark Dewey, the Clipboard app/Health Questionnaire is currently not used in production. We agreed to make all appropriate changes at once, and he will test them on his end once they are deployed. 

---
## Tasks
- [x] Setting updated and tested in dev env
- [x] Setting updated and tested in staging env
- [ ] Setting updated and tested in prod env

## Acceptance Criteria
- [ ] All settings changed and tested in all relevant environments.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alwerner** [comment]
@madebydna Is this in prod? It's not checked in the AC.
