### ISSUE TITLE
Update LH Address Validation API endpoint configurations to use fwdproxy

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44624]
## Issue Description
The Address Validation API settings fall into the ["VA.gov —> Lighthouse“ category of API domain references](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538) within vets-api. 

To ensure that they continue to work correctly after the Lighthouse migration, they would need to be updated to using the forward proxy, either on port `4475`, if the URL setting matches the environment (e.g. sandbox and prod), or `4492` if the URL setting is in dev or staging and uses the Lighthouse Sandbox environment. 

The identified settings are:
- `va_profile.address_validation.hostname`

These settings exist in dev, staging, and production. 
---
## Tasks
- [ ] Settings updated and tested in dev env
- [ ] Settings updated and tested in staging env
- [ ] Settings updated and tested in prod env
- [ ] Formalize DD tests for all environments

## Acceptance Criteria
- [ ] All settings changed and tested in all relevant environments.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
