### ISSUE TITLE
Update vets-api's Decision Review endpoint configurations to use fwdproxy

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44622]
## Issue Description
The Decision review settings fall into the ["VA.gov —> Lighthouse“ category of API domain references](https://app.zenhub.com/workspaces/cloud-isolation-team---platform-spike-teams-623237db716f9b001d4e16aa/issues/department-of-veterans-affairs/va.gov-team/44538) within vets-api. 

To ensure that they continue to work correctly after the Lighthouse migration, they would need to be updated to using the forword proxy, either on port 4475, if the URL setting matches the environment (e.g. sandbox and prod), or port `4492` if the URL setting is in dev or staging and uses the **Lighthouse Sandbox** environment. 

The identified settings are:
- `decision_review.url`
- `decision_review.v1.url`

These settings exist in dev, staging, sandbox, and production. Note that the dev settings currently use the dev environment and will need to be updated to sandbox.

---
## Tasks
- [ ] Settings updated and tested in dev env
- [ ] Settings updated and tested in staging env
- [ ] Settings updated and tested in sandbox env
- [ ] Settings updated and tested in prod env

## Acceptance Criteria
- [ ] All settings changed and tested in all relevant environments.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
