### ISSUE TITLE
[Terraform / AWS] enabled_metrics disabled unexpectedly for aws_autoscaling_group

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#44638]
## Description
When the `tf plan` was run locally for this PR: https://github.com/department-of-veterans-affairs/devops/pull/11582, there was an odd output (partially seen in https://github.com/department-of-veterans-affairs/devops/pull/11582#issuecomment-1189574604). `enabled_metrics` were being removed from the following Auto Scaling Groups
```
dsva-vagov-utility-eks-node-group-main-dsva-vagov-utility-cluster
dsva-vagov-vets-website-gha-runners-asg
dsva-vagov-vets-api-gha-runners-asg
dsva-vagov-content-build-gha-runners-asg
dsva-vagov-va-virtual-agent-gha-runners-asg
dsva-vagov-devops-gha-runners-asg
```
More info in this Slack thread:
https://dsva.slack.com/archives/CTYQL39FE/p1658266871119189

## Background/context 
Terraform `aws_autoscaling_group` docs for `enabled_metrics`: https://registry.terraform.io/providers/hashicorp/aws/3.74.2/docs/resources/autoscaling_group#enabled_metrics

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [x] Are these metrics used?

## Acceptance Criteria 
- [ ] If the metrics are used, re-add them.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
For these ASGs:
```
dsva-vagov-utility-eks-node-group-main-dsva-vagov-utility-cluster
dsva-vagov-vets-website-gha-runners-asg
dsva-vagov-vets-api-gha-runners-asg
dsva-vagov-content-build-gha-runners-asg
dsva-vagov-va-virtual-agent-gha-runners-asg
dsva-vagov-devops-gha-runners-asg
```
These are the metrics that are no longer enabled:
```
 "GroupAndWarmPoolDesiredCapacity",
 "GroupAndWarmPoolTotalCapacity",
 "GroupDesiredCapacity",
 "GroupInServiceCapacity",
 "GroupInServiceInstances",
 "GroupMaxSize",
 "GroupMinSize",
 "GroupPendingCapacity",
 "GroupPendingInstances",
 "GroupStandbyCapacity",
 "GroupStandbyInstances",
 "GroupTerminatingCapacity",
 "GroupTerminatingInstances",
 "GroupTotalCapacity",
 "GroupTotalInstances",
 "WarmPoolDesiredCapacity",
 "WarmPoolMinSize",
 "WarmPoolPendingCapacity",
 "WarmPoolTerminatingCapacity",
 "WarmPoolTotalCapacity",
 "WarmPoolWarmedCapacity",
```

Do we use any of these metrics for our scaling policies? Looks like no. https://github.com/department-of-veterans-affairs/devops/pull/9567, from last year, adds a new CloudWatch metric called `github-runners` which tracks the number of offline, busy, and available runners. That metric can be seen in the [CloudWatch UI](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~'github-runners~'RunnersOffline~'repo~'devops)~(~'.~'RunnersBusy~'.~'.)~(~'.~'RunnersAvailable~'.~'.))~region~'us-gov-west-1);query=~'*7bgithub-runners*2crepo*7d*20github-runners). Those metrics are still being collected, which is good because those metrics determine how the github runner ASGs scale. We can safely say that removing the metrics listed above did not have an impact on scaling ✅.

Are these metrics used anywhere else, like in Grafana or Datadog?  
I searched for these metrics in Datadog and found that the `Warm*` metrics appeared for about a day and a half (before I disabled them, presumably). But many of the `Group*` metrics were not impacted by my disabling. Here is a screenshot of some of them in datadog:
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/10993987/180853462-0741285a-aa9f-437f-afcc-03887b48ed1e.png">

[This dashboard](https://grafana.vfs.va.gov/d/tAxjiwG7z/github-runners?orgId=1&from=now-7d&to=now) was the only one in Grafana I could find related to runners. No impact ✅ 
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/10993987/180860782-e4542eff-d3c0-4e35-8ac0-a8c3440ac921.png">

I don't think these metrics were used. Their being disabled is still a mystery.
