### ISSUE TITLE
[cFSR] Debt and Copay Selections update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#44637]
## Issue Description
As a part of the Combined FSR update, the debt selection page is being updated to provide clarity on debts and copays being selected and minimizing extra noise on the page. 

[UXPin for updates](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150718130/comment/sitemap,comments?mode=i )

<details><summary>Existing solution: (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/11b0e347-8b5b-49e8-9936-9c39460227b7)
</details>

---
Updated solution:

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/0b0b5f89-8f2c-4c45-b304-52fbf8b4fee4)

---
## Tasks
- [ ] Remove card UI component and add checkbox selections with additional subtext information. 
- [ ] Include copays in checkbox list for selection.  
- [ ] Update cypress tests if necessary

## Acceptance Criteria
- [ ] New debt selection page matched design and is functioning

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
