### ISSUE TITLE
Modify expose headers for error handling

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#44630]
## Description
When a user encounters an error during the authentication phase and the contact center team is unable to determine the cause of the bug the Identity team is usually tasked with uncovering the issue.  Searching without specific information like time & ICN is time consuming and doesn't always help when troubleshooting across devices. The Request ID is sent with each authenticated request to the API, by exposing this Request ID, teams will be able to filter through data and logs to find context on why an error was displayed to the user.

## Tasks
Frontend
- [x] Update the AuthApp to display the Request ID on the page below the Error Code
- [x] Update the AuthApp to display a time when the error occured
Backend
- [x] Update the config/application.rb to explicitly expose the `X-Request-Id` headers to vets-website
General
- [x] Update Sign in Troubleshooting documentation to include references to this Request ID

## Acceptance Criteria
- [x] When an authentication error is returned on the AuthApp, I can see a Request ID and the time
