### ISSUE TITLE
[cFSR] Trailers, campers, and boats page redesign

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#44642]
## Issue Description
To simplify the form a little and only capture necessary data we need to remove existing list loop for adding trailers, campers, and boats and replace with single radio button and total estimated value of all trailers, campers, and boats. 

[UXPin Preview](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145355886/comment/sitemap,comments?mode=i )

Updated total value page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/5b818118-d408-4e33-b6f5-e9e013347d4a)

---
## Tasks
- [ ] Remove unnecessary list loop 
- [ ] Add new radio button and numeric input pages to replace
- [ ] Update Cypress tests as necessary 

## Acceptance Criteria
- [ ] Household assets trailers, campers, and boats page matches design and is functional
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Back to in progress for addtl work per convo with Andrew and Scott. Attempting to use feature flag and fix transform but feature flag may not be possible due to FSR being a giant page within an app of pages?
