### ISSUE TITLE
[cFSR] Benefit debt resolution option update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#44640]
## Issue Description
Debt resolution/relief options are being updated and moving away from the radio button card components and moving to a more concise selection process

Include resolution explainer page prior to relief option selection
[UX Pin for resolution explainer](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789024/comment/sitemap,comments?mode=i )

Remove existing radio button card components and replace with standard radio button options with additional subtext information. 
Add secondary pages based on these radio button selection to collect necessary information and continue to next selected debt. 
[UXPin for new selection options](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789115/comment/sitemap,comments?mode=i)
 
Updated Selection page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/46e94af6-b0b0-491f-a5e4-b717412de004)

---
## Tasks
- [x] Include resolution explainer page prior to relief option selection
- [x] Remove existing radio button card components and replace with standard radio button options

## Acceptance Criteria
- [x] Debt resolution/relief options match design and function appropriately 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
