### ISSUE TITLE
[cFSR] Copay debt resolution option update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#44641]
## Issue Description
Debt resolution/relief options are being updated and moving away from the radio button card components and moving to a more concise selection process and we need to include separate options for copays
Remove existing radio button card components and replace with standard radio button options with additional subtext information. 
Add secondary pages based on these radio button selection to collect necessary information and continue to next selected debt. 
[UXPin for copay relief options](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150667633/comment/sitemap,comments?mode=i)

New selection page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/b6960d29-b39a-451e-b6c0-335d751bb92f)

---
## Tasks
- [ ] Add standard radio button options with additional subtext information. 
- [ ] Add secondary pages based on these radio button selection to collect necessary information and continue to next selected debt.

## Acceptance Criteria
- [ ] Copay resolution/relief options match design and function appropriately
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Lowered to 5 again per convo with Andrew as this ticket will encompass UI and basic behavior. The combining of data and conditionalizing will live in a separate ticket.
