### ISSUE TITLE
Changes to Forms Funnel Logic & QA

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#44652]
## Issue Description

Changing the forms funnel dataset logic to remove cross-join.  

Slack thread for reference:  https://dsva.slack.com/archives/C01S78V4AUA/p1658275108835939

---
## Tasks
- [x] Update logic
- [x] QA
- [x] Backfill data

## Acceptance Criteria
- [x] Domo cards will be updated based on new dataset
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Confirming that the following changes have been made:

- Cross join changed to inner join in both backfill and last week views
- New `step_is_optional` field added to all forms with best guesses filled out based on totals
- New card filter added to Exit rate form so that only mandatory steps are shown and actual differences are easier to see. The card title now reflects this also.

QA was completed on the front end of this backfill, since Jonathan compared the test dataset to GA totals.

For next steps - I'd recommend we reach out to the teams with forms on our dashboards to 1) confirm any funnel changes and 2) confirm mandatory/optional step designations. But since that's out of the scope of this current ticket, I'll close this out as it's complete.
