### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#44651]
# Description
VA.gov needs to implement the ability to present users with Terms and Conditions, store that they've been accepted for that user, and re-present them if/when they're updated.

# Acceptance Criteria
- [ ] On sign-in, check if user has previously accepted the current Terms and Conditions
- [ ] If yes, do not present
- [ ] If no, present
- [ ] On acceptance, forward user to where they were going
- [ ] If user doesn't accept do not log them in and redirect to VA.gov (may change)

# Outstanding questions
- [ ] Where are we storing acceptance?
- [ ] Where are we storing the actual terms and conditions?
- [ ] Does the user need to be re-presented when the terms change? (can add later)

# Considerations
- Needs to be part of sign-in service
- May need to be launched before sign-in service using existing system (IAM)
