### ISSUE TITLE
Supplemental Claims | Add JSON schema to Vets repo

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44674]
## Value Statement

**_As a_** system
**_I want to_** add the JSON schema for supplemental claims to the Vets schema repo 
**_So that_** I can store and display data related to the supplemental claims form.

## Background Context

The scope of this ticket covers the schema, swagger documentation, and tests.

## Tasks

- [x] Add schema to Vets repo (frontend or backend)
- [x] Complete swagger documentation (backend)
- [x] Write tests (frontend, testing in vets-json-schema repo)
- [x] Update vets-json-schema _version_ in vets-website repo

## Definition of done

- [x] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@scottymeyers can you update/move this to the right swim lane?
