### ISSUE TITLE
Vista [Appointment Request Changes/Direct Scheduling]/Acheron Service Integration]

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#44673]
Scheduling Manager will be shutting down starting 11/21/2022. VAOS FE will send VA appointment request using Acheron (new service). 

### Product Checklist 
<details>
  <summary>Toggle Product Checklist</summary>

## Product
- [X] [VAOS Service Integration - Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/vaos-service-integration/vaos-service-integration-initiative-brief.md)
- [X] [Release Plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/vaos-service-integration/vaos-service-integration-release-plan.md)
- [ ] Update product guide

### VSP Collaboration Cycle - `N/A`
- [ ] Project Kickoff
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging Review
- [ ] Privacy & Security Review
- [ ] Full Accessibility & 508 Audit
</details>

### UX Design Checklist 
<details>
  <summary>Toggle UX Design Checklist</summary>
  
##### Complete this checklist for all new projects. 

[Discovery doc](https://docs.google.com/document/d/1sXI5JvGlNQBUSgGrn6-1ug62htpIYWlD0GWGc9_ciqw/edit#heading=h.d1wvfqscdl80)

- [x] What do we know?
* BE changes driven by the shift from SM to VSE GUI, and Acheron changes, might require changes to the VAOS request flow.

- [ ] What is the problem statement?
* None yet

- [x] Who is the target user?
* MSAs who process requests. These changes may affect the data they receive from VAOS requests, and/or their workflow.
* Veterans who submit requests through VAOS may have fewer options for communication preferences (especially traveling Veterans).

- [x] Is there a list of questions and assumptions?
* Yes. See discovery doc.

- [x] What other information exists (existing research, metrics, etc.)?
* See discovery doc.

- [ ] Where does this come from?
* Changes made due to 

- [x] Who surfaced the issue/problem/opportunity?
* The BE team at PI Q3 2022

- [ ] Is this in, or related to items in, the [Product/Design Wishlist](https://docs.google.com/document/d/1Cwe6CViDPME9lt6puMs9KBIqT8wZ2NNoMCXR1dEdZUU/edit#heading=h.iwlf7nqnidb)?

- [x] Who is driving this?
* VAOS is driving the discovery effort.

- [x] Is this led by product, UX, or another group?
* Currently VAOS P/D/E
* This will likely be broken up into separate technical and design efforts

- [x] Who are the stakeholders?
* BE team and FE team stakeholders

- [x] What value does this bring?
* These changes allow the BE team to decomission Scheduling Manager.

- [x] What (generally) value does product, UX, engineers, and/or stakeholders expect this will bring target users?
* MSAs will have one fewer system to manage appointments

- [ ] How do we expect to measure success?
* We don't know yet.

How does this fit into the bigger picture?
- [ ] OCTO goals
- [ ] [VAOS OKRs and KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/vaos-kpis.md)
- [ ] Planning the project/initiative
- [x] What are we calling the initiative?
* VistA Appointment Request Changes / Acheron Service Integration

What’s our confidence level in our understanding of the problem and solution (if one exists)? Based on what we know are we confident that we could:
- [ ] Start speccing a solution? **Low**
- [ ] Start designing potential solutions? **Low**
- [x] Start planning research activities? **High** - we started a discovery effort.

Based on our understanding of the problem, and our confidence, what should we do next?
- [ ] Commit to next steps
- [ ] Document the plan

Does the documentation exist?
- [ ] Problem statement
- [ ] Background information
Larger projects: 
- [ ] Initiative doc
- [ ] Epic to track work
- [ ] UX project plan ticket
All projects:
[ ] Add** project to UX initiative planner
[ ] UX creates discovery, design, spec tickets in the [VAOS Product/Design Board (Zenhub)](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/board?labels=vaos-product-design&repos=33202667,62409417,133843125,66304117) as needed
</details>

### Engineering Checklist 
<details>
  <summary>Toggle Engineering Checklist</summary>

- [X] Project Description.
- [X] Are UI designs/ specs available/ready? If yes, attach specs. (We are assuming the design specs have been approved by the accessibility team if they're ready) 
* See Design Specs

- [X] Are there any deadlines that need to be met? 
* 11/21/22 

- [X] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first) 
* Yes, we will need a feature toggle (similar to v2next) 

- [X] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
* Yes, Acheron 

- [ ]  Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

**Comment by ldelacosta** [comment]
No additional work is needed. Closing out the epic.
