### ISSUE TITLE
Supplemental Claims | Choose Benefit Type

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44670]
## Value Statement

**_As a_** user
**_I want to_** select the benefit type for which I am filing a supplemental claim 
**_So that_** I can choose the right pathway for filing.

## Background Context

MVP of supplemental claims will support disability compensation. All other benefit types will need to be filed using the paper process.

The [design of the benefit type question](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/0454C07B-0B34-46F7-9287-200FD43F78D5/canvas#Version) is similar to the previous wizard pattern used by the Higher-Level Review form, but it shows a single question per page.
- The questions will be displayed on the `/start`, similar to a wizard
- Navigating through the questions will keep the Veteran on the `/start` url, but upon changing, the H1 will be focused to indicate to the screen reader that the content has changed

## Tasks

- [ ] Copy the HLR wizard pattern, but maintain one question per page
- [ ] Ensure the selected benefit type is included in the contestable issues API call, _after_ the Veteran enters the flow of the form
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie need some help writing out the tasks/AC for this one too.

**Comment by Mottie** [comment]
@thehastingsp Where does the back button lead to? We were guessing it would go back to the "Decision reviews and appeals" page (same as the breadcrumb link).

**Comment by saderagsdale** [comment]
@Mottie @rocio-desantiago What's the status on this one? Want to make sure it's not blocked.

**Comment by Mottie** [comment]
Not blocked, still actively working on this ticket. It should be done today or early tomorrow.
