### ISSUE TITLE
[FE] Create Cypress screenshot scripts

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#44682]
## Description
Set up a custom cypress command that takes a screenshotName variable to create screenshots. From the spike ticket, it was determined that waits are useful to keep cypress from moving on while making the screenshot. Something between 1000ms to 5000ms will be needed. Tune this to find optimal wait time. Another finding from the spike ticket is that smooth scrolling can cause an issue. Here is a code example for a headstart on the command:
```
   // Disable smooth scrolling
    cy.get("html, body").invoke(
      "attr",
      "style",
      "height: auto; scroll-behavior: auto;"
    );
  // Create screenshot
    cy.screenshot('[screenshotName]');
  // Wait while screenshot is created
    cy.wait(2000);
```
It may be needed to sandwich this with cy.wait, but test that out. The other part of this would be to create an env variable to wrap the command in. Then to create the screenshots we would call it from the command line like `yarn cy:run --env screenshot=true` this will keep the screenshots from being run in CI. The last part of this would be to add our command everywhere we want a screenshot.  I would start with happy path tests and errors, then see what is missing. Make sure to update README to describe how to get screenshots.

## Tasks
- [ ] Create cypress command
- [ ] Utilize env variable
- [ ] Add screenshot command where needed to existing tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Running cypress with --env screenshot=true results in screenshots being created in root cypress/screenshots directory

**Comment by brianseek** [comment]
Closing since no validation needed after code review. Did create follow up ticket to create cypress tests for phone appointments: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44896
