### ISSUE TITLE
Content changes to Yellow Ribbon Program page - HOLD TO PUBLISH UNTIL 8/1

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44691]
## Issue Description

Stakeholder Terry Warren let us know that one of the last changes from the Colmery Act goes into effect on August 1, 2022, for active-duty service members in the Yellow Ribbon Program. 

He sent suggested edits for the blue featured content box on the [Yellow Ribbon Program](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/) page. We need to revise for plain language and so that it adheres to VA.gov style standards.

Content to add to page: [https://app.zenhub.com/files/133843125/b69ec800-5376-42ad-8355-69620fad74f8/download](https://app.zenhub.com/files/133843125/b69ec800-5376-42ad-8355-69620fad74f8/download)

## Tasks
- [x] Rework content and add to Drupal page
- [x] Review (Laura)
- [x] OCTO-DE review (Beth)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish page (Megan)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] Updated eligibility content is live on the site

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! As mentioned earlier, I went ahead and put these changes on Drupal to get this moving along.  I am suggesting that the text be broken up in to two bullet points to break up the content 

- You're currently an active-duty service member who served for at least 36 months, **or**

- You're a spouse using the transferred benefits of an active-duty service member who served for at least 36 months

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=936

A few questions came up while making this change and I'll plan to amend the text once there's more clarity on the following:

- I want to clarify this line (I flagged this on Slack and Randi mentioned it may be a question for stakeholders): 
**“… if you’re a spouse using the transferred benefits of an active-duty service member who meets these qualifications.”** 

Is “qualifications” referring to the whole bulleted list or is this saying that they must be the spouse of an active-duty service member who qualifies at the 100% level? Is “who meets these qualifications” – meaning an active-duty service member who qualifies at the 100% level? 

- Because the H3 at the top of the blue box says, “You must qualify for the Post-9/11 GI Bill at the 100% benefit level,” does this also need to be re-stated in this new bullet point? Since the H3 comes before the list point does it mean that for the bullet points you qualify at the 100% level? This comes before “And at least one of these must be true."

OR

-Is there a difference with the 100% level in this section pertaining to current active-duty members, because it doesn’t say “benefit level?”  Is the 100% level that someone reaches if they "served on active duty for at least 36 months.” This is what is in parenthesis after the current statement on the page: "if you’re currently an active-duty service member who qualifies at the 100% level (you already served on active duty for at least 36 months)."

- If you’re the spouse of an active-duty service member, does the same apply – that the service member must have served 36 months? Or is it only that they must qualify at the 100% level?

- For the 36 months in this section, does the same rule apply as the first bullet point in this blue box, that the months must be “either all at once or with breaks in service?”

- I took a look at the [Transfer your Post-9/11 GI Bill benefits page](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) for a bit more context about transferring benefits to a spouse or (as listed earlier in this list) a dependent child.   From this page under the H2 “When can I transfer benefits?” and then under “Spouses” it says that they (spouses) don’t “qualify for the monthly housing allowance while you’re on active duty.” Is this something that will end up being changed on the page because of these new guidelines for Veterans on active duty?

- Similar to the bullet point on dependent children and transferred benefits, do we need to link to the [transfer benefit page](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) in regards to spouses of active duty members?

**Comment by aliyahblackmore** [comment]
Thanks @laurwill!

Hi @bethpotts - content changes are ready for you on Drupal. 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=936


**We just have two questions for you:** 

1. For the 36 months in this section, does the same rule from the first bullet point in this blue box apply? The rule that the months must be “either all at once or with breaks in service."

2. I took a look at the [Transfer your Post-9/11 GI Bill benefits page](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) for a bit more context about transferring benefits to a spouse or (as listed earlier in this list) a dependent child. From this page under the H2 “When can I transfer benefits?” and then under “Spouses” it says that they (spouses) don’t “qualify for the monthly housing allowance while you’re on active duty.” We are wondering if this is something that will end up being changed on the page because of these new guidelines for Veterans on active duty?

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore 
1. Great Q for the stakeholder--whether we should add text about "all at once or with breaks in service" to the new bullet about spouses. I'd add to that--should it also say "on active duty" as the first bullet does. 
2. I think you're asking whether changes are needed to the transfer benefits page. If you are, I can ask about that in the transfer of entitlement work I'm doing separately. Is the question whether spouses will in fact qualify for MHA with rules changing? I'm not sure I'm understanding...

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore Were those 2 bullets (about spouses and Fry) the only changes to the bulleted list? Then the other update was to remove the Note and the "Starting August 1" blurb?

It looks good to me!

**Comment by aliyahblackmore** [comment]
Thanks @bethpottsVADEPO ! Yes, those were the only two changes here.  
And re: my second question - yes, I was asking if changes will be needed on the transfer benefits page, but realizing now that the info isn't necessary for this work!  

**Hey @laurwill - this is the amended question for the stakeholders:**

For the 36 months in this section, does the same rule from the first bullet point in this blue box apply? The rule that the months must be “either all at once or with breaks in service."  Should it also say "on active duty" as the first bullet does?

**Comment by laurwill** [comment]
Thanks Aliyah! I sent these questions to the stakeholder.

**Comment by laurwill** [comment]
Terry responded:
Yes, it is active duty time. For your awareness, Guard and Reserve members must be on active duty orders to accumulate time.
And does it need to be all at once, or can they have breaks in service? This comes back to the status of the Guard / Reserve member as they would have breaks in periods of active duty time as they go from AD orders but then return to their Guard status and then two years later go back on AD orders.

I adjusted the Drupal file and sent to Terry as an FYI.

@RLHecht , this page is ready for your copyedit tomorrow—we'll plan to publish first thing Monday morning.
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=936

**Comment by RLHecht** [comment]
This page is ready to publish on Monday for either me or @megzehn. I did a final copyedit of the new content and changed an outdated link in an accordion. It was pointing to an old benefits.va.gov page from 2018 so it's now pointing to the find a Yellow Ribbon tool page instead.

**Comment by RLHecht** [comment]
I published these changes this morning. Moving to validate and will close once it's live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
