### ISSUE TITLE
FE | Profile | Home/Mailing Address Text Update

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44697]
## Background

The staging alert with a checkbox to update home to match mailing address needs to be updated to match the Sketch mock-ups. 
- Currently, staging says "My home address is the same as my mailing address"
- We need to change this text to match the Sketch mock which says "Use my mailing address for my home address". 

## Tasks
- [x] Update the text for the home/mailing address alert to match the Sketch mock-up [here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/jgJoPJW)

## Acceptance Criteria
- [ ] Deploy change to Staging behind feature flag
- [ ] Notify Product Manager when the change is ready to be validated on Staging
- [ ] If no issues found, deploy changes to Production 
 
 
## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
We can validate this now

**Comment by SKasimow** [comment]
Updated Ticket to say: Use my mailing address as my home address (previously said "for my..."

**Comment by SKasimow** [comment]
@adamwhitlock1 - validated staging matches the mock.
