### ISSUE TITLE
Update smartphone check-in R&S article to align with new identity verification method

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44692]
## Issue Description

Patient Check In is switching the identity verification method from last name, last 4 SSN to last name, DOB on or around 7/26. We need to update content and screen shots on the [How to check in with your smart phone for some VA appointments](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) to reflect this change. 

We should hold off on publishing the changes until we've confirmed the date this switch goes into effect.

## Tasks
- [x] Get new screenshot from product team (Randi)
- [x] Update content and screenshot in Drupal page 
- [x] Review changes (Laura)
- [x] OCTO-DE review (Danielle)
- [x] Final copyedit with pre-publishing checklist (Randi)
- [x] Publish page (Randi)

## Acceptance Criteria
- [x] New content and screenshot are live on the site

**Comment by RLHecht** [comment]
@benbrasso-agile6 Could you add a screenshot here of the new check-in with DOB instead of the last four SSN? We'll add it to the Drupal page and adjust the language. Thanks!

**Comment by benbrasso-agile6** [comment]
![Verify Identity for check in](https://user-images.githubusercontent.com/101129355/180227670-85575beb-0a52-4ac0-834e-bee0104220e2.png)

![Verify Identity for pre check in](https://user-images.githubusercontent.com/101129355/180227688-6753c87a-4d9c-4542-9184-e25219e5960a.png)

**Comment by katherine-fung** [comment]
Hi @laurwill, I changed the instructions to say date of birth, and added the new screenshots. 

The preview is here: http://preview-prod.vfs.va.gov/preview?nodeId=44490

**Comment by benbrasso-agile6** [comment]
@RLHecht I was mentioning to @DanielleThierryUSDSVA this morning that we will be launching/testing the new log in method with ~10% of Veterans initially around 7/26 to verify it's working as intended. Approximately after 1-7 days of successful log ins with DOB, we will switch it to 100% of Veterans. We will keep this team in the know on this progress.

**Comment by RLHecht** [comment]
Thanks @benbrasso-agile6 

@katherine-fung I asked Danielle what we should do when they are testing it with the 10% and before it goes to 100%. She said we should make the language something like "either date of birth or SSN" and then we'll update it again once it goes live to 100% of users. For the screenshot, she said to either leave what's in there or remove it. Since we don't have a screen shot for each step, I think it's OK if we want to take it out for now. @laurwill what do you think?

**Comment by benbrasso-agile6** [comment]
If you need other screenshots, let me know.

**Comment by katherine-fung** [comment]
Hi @laurwill @RLHecht - I removed the screenshots and put in new language, as we discussed. 

The preview is here: http://preview-prod.vfs.va.gov/preview?nodeId=44490

**Comment by benbrasso-agile6** [comment]
Here is our updated launch plan, FYI: 

We are planning to release the memorable date component into Patient Check In next week. Our plan is to test the new memorable date component with 10% (~500 per day) of users initially, while the other 90% will verify their identification to Patient Check In using their last name, last 4 of their SSN, which does not use the memorable date component.

Our goal is to ensure that the new identify verification method (e.g., memorable date) is as successful as the existing method (e.g., last name, last 4 SSN). However, it's worth noting that this "test" is an apple to oranges comparison since the data a Veteran uses to verify will be different. But, we think the comparison is still relevant.

What we wanted to do is alert you of our planned release of the component, but also include you in the conversation about tracking success. Here's how we intend to track success and performance:

% failed of memorable date component for Pre Check In
% failed of memorable date component for Check In
% success of memorable date component for Pre Check In
% success of memorable date component for Check In

And, we'll compare those same numbers to the existing identification method for the same date range.

Our plan is to check on this data hourly for the first day. If the new memorable date component's performance is significantly less than the existing method, then we'll stop using it and evaluate next steps.

However, if the performance is in a similar range compared to the existing method for 5-7 days, then we'll expand it to more users.

In either scenario, we will communicate these updates with you. If you have any questions, comments or concerns on any of the above, please let me know. Thanks!

**Comment by katherine-fung** [comment]
Update from Ben about the launch date for the test: "As of this morning, we are pushing out a bit. 8/4, which is next Thursday." 

cc @laurwill @DanielleThierryUSDSVA for awareness

**Comment by RLHecht** [comment]
@benbrasso-agile6 Are you still planning to start this on 8/4? Just confirming when we should be publishing our changes.

**Comment by benbrasso-agile6** [comment]
Yes. Will communicate if something changes.

**Comment by benbrasso-agile6** [comment]
@RLHecht targeting 530pm Thursday

**Comment by laurwill** [comment]
Thanks @katherine-fung , I just removed the comma in that sentence and added "either." @megzehn this is ready for you to copyedit and publish tomorrow!

**Comment by benbrasso-agile6** [comment]
@RLHecht release being delayed. when I have the new date, I will provide an update.

**Comment by benbrasso-agile6** [comment]
@RLHecht still deciding on a new date. But, it is looking like it is not this or next week. Will update more when I have it.

**Comment by RLHecht** [comment]
Thanks for keeping us in the loop @benbrasso-agile6 !

**Comment by benbrasso-agile6** [comment]
@RLHecht 8/23 is the new proposed date

**Comment by benbrasso-agile6** [comment]
@RLHecht this is not launching tomorrow. New date TBD. Will provide new date when I have it.

**Comment by benbrasso-agile6** [comment]
@RLHecht 8/31 is the new planned release date

**Comment by benbrasso-agile6** [comment]
@loripusey I'll be out of the office on 9/6. Can you communicate with Randi here once we push this release? Or change the date?

**Comment by loripusey** [comment]
Will do

**Comment by benbrasso-agile6** [comment]
@RLHecht this was released last night. The feature is being shown to 10% of Veterans currently. Will provide updates as we increase the %.

**Comment by RLHecht** [comment]
This has been published. Moving to validate and will close once live on the site. I'll create a new ticket for the backlog to update the language for once the feature is showing to 100% of Veterans. Thanks again for all the communication on this @benbrasso-agile6 !

**Comment by RLHecht** [comment]
This is live! Closing. I opened up ticket #46817 for the work we'll need to do once this change is at 100%.
