### ISSUE TITLE
[Design] Profile 2.0: Initial design explorations

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4469]
## User Story:

As a user, I need to be able to easily find and manage my personal information.

## Tasks

In Sprint 12, Tressa will revisit the initial Profile 2.0 designs created by Samara. 

- [x] Initial design explorations/vision - 16 hours - 20 hours
- [x] Share initial proposal with Samara, get feedback, and make updates -  3 - 4 hours

## Acceptance Criteria:

- [x] Initial design explorations are complete, have been shared with Samara, and are ready to share with the larger design/auth exp. team.

**Comment by Justin-Pickett** [comment]
Discovery happening. Could possibly expand into sprint 13. We'll keep this ticket updated accordingly.

**Comment by Samara-Strauss** [comment]
Gonna split this out into a couple tickets to track progress over the next sprint.

**Comment by Samara-Strauss** [comment]
New goal for this ticket is just design explorations. In Sprint 13, the goal is to share the designs with the larger team (design/auth. exp) and to have a final, final proposal at the end of the sprint. In Sprint 14, the goal is to produce all states and start research planning if there is time.

**Comment by Samara-Strauss** [comment]
This is complete. Sprint 13 work will be tracked in #4759.
