### ISSUE TITLE
[FE] [BUG] Many requests are being made to the pre-check-in controller without a token

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44705]
## Background

There is a recent jump in errors reported in GA and vets-api logs that appears to be caused by a large increase in requests made without a token.

Slack thread with more information: https://dsva.slack.com/archives/C02G6AB3ZRS/p1658354894000699

## Tasks
- [x] Investigate cause and resolve or create follow-on issues
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
Troubleshooting call scheduled for tomorrow at 1500 ET

**Comment by acrollet** [comment]
After investigating with @brdunfield @brianseek @randomsync @kanchanasuriya we determined that this is a pre-existing bug in the pre-checkin app that was uncovered by the work in #44113 to allow page refreshes to hit the pre-checkin app. Created #44798 to resolve the bug.
