### ISSUE TITLE
[Build] Resolution of "stuck" state when submitting 526

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4471]
## User Story:
As a system user, I need to be able to finish submitting my 526 form even if it ends in an error so that I am not left wondering if my form was submitted when the submit button was clicked but remained grayed out for an endless period of time.

## Background:
Original Ticket #3700
- In order to prevent this process from getting stuck, I think adding a timer for about 10 (or more) seconds that then automatically aborts would prevent this "stuck" state. In addition, we could output some essential data to the console log, so that we can better troubleshoot this problem when it happens in production. This output will contain PII, but it will be permanently erased if the user closes the tab or reloads the page.

More background: This situation occurred during a shared screen session with a veteran. When the submit became "stuck", the submit button turned gray and never resolved (we waited several minutes). After instructing the user to open the network tab of the Chrome developer tools, we noted that no network call was made. Which seems to be is a very unlikely, yet perplexing situation.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_

Idea:
> Add a reject timer to the submit form. After 30 seconds, abort the submit and notify the user that there was a problem; additionally, relevant data will be output to the console log.
>
> If the user notes this problem does not resolve, they may contact the help desk who will in turn set up a meeting with the development team to observe the issue. This is where the console log may prove to be valuable.

- [x] Discuss the problem & possible solutions with the other developers
- [ ] Implement the idea

## Acceptance Criteria:
- [ ] Submit process aborts (the promise rejects) after 30 seconds.
