### ISSUE TITLE
Walk through what we have to see what needs to change

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44741]
## User Story
As a next step in the Team's discovery work regarding supporting Check-in on public devices, we would like to walk through the current Check-in application to identify what would need to change in order to use it on a public device.

## Tasks
- [ ] Schedule a team meeting (include Mark Dewey)
- [ ] Demo the Check-in application
- [ ] Discuss & document what would need to change 
- [ ] Decide on next steps
- [ ] Create follow-on tickets
