### ISSUE TITLE
Walk through what we have to see what needs to change

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44740]
## User Story
As a next step in the Team's discovery work regarding supporting Check-in on public devices, we would like to walk through the current Check-in application to identify what would need to change in order to use it on a public device.

## Tasks
- [x] Schedule a team meeting (include Mark Dewey)
- [x] Demo the Check-in application
- [x] Discuss & document what would need to change 
- [x] Decide on next steps
- [x] Create follow-on tickets

**Comment by loripusey** [comment]
@sarahknoppA6 did you set up this meeting? I don't see it on the calendar.
