### ISSUE TITLE
FE | Profile | BAI | Feature Flag - release to 100%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44759]
## Background

We would like to increase the release from plan  50% to 100% of users so that these changes are visible in Production  to everyone.

## Tasks

- [ ] Update feature flags to make BAI alert visible in Production for 100% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to make changes visible in Production for 100% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO
