### ISSUE TITLE
Update Fry Scholarship rates on education benefits for survivors and dependents page-HOLD TO PUBLISH 8/1

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44757]
## Issue Description

The Fry Scholarship rates change as of August 1, 2022. We need to update these on our [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page and publish on 8/1. 

Source material with new rate information: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080122.asp

Note that in Drupal we currently have a revised draft of this page that hasn't been approved yet. We will need to revert to an older version that has the charts and put in these new rates. Once we publish the page on 8/1, we should revert to the last revision of the new page, put in the updated rate information, and keep as a draft for when we eventually publish this reworked page.

## Tasks
- [x] Set last version with tables and approved content as current revision
- [x] Update rates for August 1, 2022
- [x] Review (Laura)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Publish (Megan)
- [x] Set last version of page without tables to current revision
- [ ] Update rates for August 1, 2022 and keep as draft

## Acceptance Criteria
- [x] New rates are live on the site

**Comment by katherine-fung** [comment]
Hi @laurwill, I reverted to the version of this page that preceded the unpublished changes, and updated the rates to reflect the 2022 amounts. 

Here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=984 

Source page for DEA rate: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100122.asp 
  
Source page for Fry Scholarship rate: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080122.asp

(the page doesn't mention Fry scholarship, but this other landing page links to it: https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp)

**Comment by laurwill** [comment]
Hi @katherine-fung ! The Fry rates look good. For DEA, that linked page doesn't say the date the rates change — did we confirm we're supposed to change the DEA rate as well?

**Comment by katherine-fung** [comment]
Hi @laurwill, thank you for catching that!! You're right, the new DEA rate doesn't go into effect until 10/1/22, according to this tables page: 

https://benefits.va.gov/GIBILL/resources/benefits_resources/rate_tables.asp#ch35

I've changed the DEA rate back to the rate that will be in effect on 8/1/22 ($1,298). 

Here's the updated preview: 

http://preview-prod.vfs.va.gov/preview?nodeId=984

**Comment by laurwill** [comment]
Thanks Katherine! Looks good. 

@megzehn this is ready for pre-pub/publish on Monday morning!

**Comment by megzehn** [comment]
Thanks! I copyedited this, and the updated rate looks good. 

@RLHecht, FYI, I reverted back to Beth's version for the latest draft, but I don't see where to add the updated rates in that version. I left that task unchecked. 

http://preview-prod.vfs.va.gov/preview?nodeId=984

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
