### ISSUE TITLE
[VA Notify Team Inquiry] 40-10007 Confirmation of submission success and other questions

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#44754]
## Value Statement
**_As a_** VA Notify product manager
**_I want to_** understand status changes for successful 40-10007 application submissions
**_So that_** I can assess how to implement email confirmation notification functionality. 

---
## Background Context
VA Notify Strike team is working on adding email confirmation notifications to Veterans when they have submitted their applications. Matt mentioned 40-10007 might be another good candidate. We have a few questions for you and your team.

## Open questions
- Our team took a dive into that form and wanted to verify if we have the right status change for successful submissions. Should the trigger be placed:

      def create
        @form = ::Preneeds::BurialForm.new(burial_form_params)
        validate!(Common::HashHelpers.deep_transform_parameters!(burial_form_params) { |k| k.camelize(:lower) })

        resource = client.receive_pre_need_application(@form)
        ::Preneeds::PreneedSubmission.create!(
          tracking_number: resource.tracking_number,
          application_uuid: resource.application_uuid,
          return_description: resource.return_description,
          return_code: resource.return_code
        )
        # confirmation email goes here
        clear_saved_form(FORM)
        render json: resource, serializer: ReceiveApplicationSerializer
      end

- Is there a current notification being sent?
- Were should the user be sent to check the status of their application?

## Tasks
- [x] _Assign to a backend developer for review_
- [ ] _Send an update to Megan Siddle, product manager for the VA Notify team_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megansiddle** [comment]
Hey @jacobworrell! I just wanted to check in on the status of this form and whether the trigger information here looks correct.

**Comment by sortizsh** [comment]
@samcoforma  can you add notes on the bug here and link https://github.com/department-of-veterans-affairs/va.gov-team/issues/45170

**Comment by samcoforma** [comment]
I was able to track down the 500 error happening upon form submission in staging to this line. It's throwing the error when trying to retrieve the attached file. I haven't been able to determine what's causing this yet due to local environment setup issues: [https://github.com/department-of-veterans-affairs/vets-api/blame/5a12ae8f3861e8998[…]0259d867e671167b/app/models/preneeds/preneed_attachment_hash.rb](https://github.com/department-of-veterans-affairs/vets-api/blame/5a12ae8f3861e8998c4a266d0259d867e671167b/app/models/preneeds/preneed_attachment_hash.rb#L28)

**Comment by samcoforma** [comment]
These are the errors as logged in Sentry:

- http://sentry.vfs.va.gov/organizations/vsp/issues/684/?environment=staging&query=&statsPeriod=14d
- http://sentry.vfs.va.gov/organizations/vsp/issues/14761/?environment=staging&project=3&query=&statsPeriod=14d

**Comment by megansiddle** [comment]
Hey @samcoforma! While the bug is getting looked at...can you confirm that we have the right placement for the confirmation email alert trigger?

**Comment by jacobworrell** [comment]
@megansiddle We are scheduling a discussion with EOAS and will update you on the outcome of that discussion. Thank you for your patience.

**Comment by samcoforma** [comment]
@megansiddle The placement for the notification code looks correct here. Let me know how it goes, and if you need anymore help with that.

**Comment by megansiddle** [comment]
Thanks for the confirmation!

**Comment by MichelleDieudonne** [comment]
Memorials Self-Service Jira Work Item: https://jira.devops.va.gov/browse/MBMS-38498

**Comment by MichelleDieudonne** [comment]
@jacobworrell We are requesting that this item be closed because email confirmations are coming through so this is resolved.  Please let us know if you have any questions.
