### ISSUE TITLE
FE | Profile | BAI | Feature Flag - release to 25%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44758]
## Background

A new bad address alert is targeted for release soon. Before releasing to everyone, we plan to roll-out to 25% of users so that these changes are visible in Production and can be monitored for a few days.

## Tasks

- [x] Update feature flags to make BAI alert visible in Production for 25% of users
- [x] Smoke test on Prod
- [x] Validate on Prod with PM and PO

## Acceptance Criteria

- [x] Feature flags updated to make changes visible in Production for 25% of users
- [x] Smoke tested on Prod
- [x] Validated on Prod with PM and PO

**Comment by adamwhitlock1** [comment]
@SKasimow BAI is released to prod at 25%. Monitoring sentry and will see GA analytics start coming through tomorrow.
