### ISSUE TITLE
FE | Profile | BAI | Feature Flag - release to 50%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44760]
## Background

Before releasing to everyone, we want to increase the phased roll-out from from 25% of users to 50% so that these changes are visible in Production and can be monitored for a few days.

## Tasks

- [ ] Update feature flags to make BAI alert visible in Production for 50% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to make changes visible in Production for 50% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO

**Comment by SKasimow** [comment]
## Background

Before releasing to everyone, we want to increase the phased roll-out from from 25% of users to 50% so that these changes are visible in Production and can be monitored for a few days.

## Tasks

- [ ] Update feature flags to make BAI alert visible in Production for 50% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to make changes visible in Production for 50% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO
