### ISSUE TITLE
Run the attached SQL script on the dsva-vagov-sentry RDS instance

### ISSUE THREAD

**Issue by azeez-salu** [department-of-veterans-affairs/va.gov-team#44763]
## Who is the devops resource on your team?
@azeez-salu 

## Description
_To fulfill the annual database scan. The DB scan team has requested that we run the attached script on the RDS instances that are listed below to add a user needed to scan the DB._
- VPC: vpc-84a444e0 - dsva-vagov-utility-vpc
- RDS: dsva-vagov-sentry_

[CreateUserPostgreSQL_AWS_RDS_CSOC.sql.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/9163070/CreateUserPostgreSQL_AWS_RDS_CSOC.sql.zip)

NOTE: The password will need to be changed in the script.

---
## Tasks
- [ ] _Please run the attached sql script on the RDS Instance listed above_
- [ ] Verify that the user is successfully created.

## Acceptance Criteria 
- [ ] _Successfully run the attached SQL script on the listed RDS Instance to create the user_

### Reminders
- [ ] Platform Security
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
Hey @azeez-salu! Thanks for submitting this request. We are discussing as a team and will follow up with the next steps before next sprint.

**Comment by jhouse-solvd** [comment]
@azeez-salu - I worked with @oseasmoran73 to write up some [high-level instructions that should help you to run the commands](https://vfs.atlassian.net/wiki/spaces/OT/pages/2299527204/Connect+to+and+RDS+instance+to+run+a+script) that you need on the database(s) in question. ☺️ 

Please have a look and let us know if you have any questions. And, feel free to stop into Platform Infrastructure Office Hours on M/W/F @ 1300 ET. The Zoom link can be found in the #platform-infrastructure channel in DSVA Slack. 

We're happy to help point you in the right direction or provide additional guidance. 

_(the above has also been copied to #44763 & #44762)_

cc: @ph-One @little-oddball @td-usds

**Comment by little-oddball** [comment]
@troymosher @azeez-salu where are we on this?

**Comment by troymosher** [comment]
@little-oddball same as #44764 this can be closed.

**Comment by little-oddball** [comment]
Can y'all get the tasks checked off/modified if needed and close it up?

**Comment by troymosher** [comment]
Closing ticket, work is being tracked in [this issue](https://github.com/department-of-veterans-affairs/platform-security/issues/114)
