### ISSUE TITLE
[Technical Discovery] Investigate how C&P requests are pulled into CST

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#44777]
## Value Statement
**_As a_** delivery team
**_I want to_** understand exactly how the CST displays information related to C&P (compensation and pensions) exam
**_So that_** we can understand how to leverage the existing api architecture and/or make suggestions for adding additional attributes related to C&P exams.

---
## Background Context
- When a veteran checks out claim details, they can see when a C&P exam has been requested, but we don't understand what data attributes are being relied upon to provide that information. 

## Acceptance Criteria
- [ ] _Open questions answered_
- [ ] _Understanding attributes relied upon to provide C&P info to users_
- [ ] _Technical assessment of using C&P exam requests as a unique object in CST that we can use to provide users with action items related to that exam request (on ramps to scheduling exams)_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Are there any attributes related to C&P exams specifically?
- What feasible opportunities might there be to make unique action items related to C&P exams available in CST? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sortizsh** [comment]
please consult with @jerekshoe  on this

**Comment by Evafloyd** [comment]
**Putting this on hold for now**
Notes from call Jacob, Jerek

Jacob says they've already done some investigation

- Feel there is a better way for the VA to make the request for the veteran to the C&P exam and make 
- C&P exam: when the veteran submits the claim, once it goes through an initial review by the claims processer, every veteran applying for disability needs the C&P exam; its done by a physician the VA chooses, trying to determine if the veterans conditions exist and if they are because of service-related, objective 3rd party that is a primary input in determining a rating. One of those steps, you can't skip. There isn't a substitute. 
- The CST, seems like an opportunity space, letting vet know when they're available to schedule one, and allowing the vet to take the necessary steps to get it scheduled. 
- It now feels like this opportunity is lower, a call with Paul Schute, there is a notes doc in our shared drive; we had the assumption that it was happening through VAS (va online scheduling tool) to schedule the exam; you can't schedule it through the tool. There isn't a web or digital tool to schedule the exam. They get a letter in the mail that say, we'll call you. Terrible experience. Jacob has a personal story, over a decade ago, the people try to schedule couldn't get a hold of him and they rejected his claim. 
- There are huge deficiencies, but there are fewer opportunities than we had hoped. We'd need broader changes in the way VA.
- This is a known moment that matters and a pinpoint. Important we stay on top of this, make sure we understand the VA's service map. 
- Seems like a great opportunity for OKRs around speed. 
- What is shown in CST today? There is a block that shows but isn't helpful in moving forward
- There is a gap between the decision letter and the digital world
- the only design that shows this is in the context of COVID because to decide, you need to come to this exam and we can't schedule in person. We don't know if that is what you still see now. **Putting this high on priority, to not show the message**. 
- Skyler is curious if other teams are working on this? The C&P exam is such an important part of the journey.
