### ISSUE TITLE
**Discovery** FE/BE - Auth Profile - Telemetry - Improve 400-Range Error Responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#44771]
## Background
Most vets-api endpoints return a 403 error when a user cannot be authorized.  

For example, when the profile page is loaded, the service history endpoint is always called.  For users that have an EDIPI (military history), the call should succeed and return a 200 code.  For users with no EDIPI (no military history), the authorization check will fail and the vets-api endpoint will return a 403 code.

_The **HTTP 403 Forbidden** response status code indicates that the server understands the request but refuses to authorize it._

While this is the correct response, based on how VA.gov is designed, this approach can cause a significant amount of chatter/noise in the analytics/telemetry tools.

The purpose of this ticket is to determine if we can establish a better process for handling error-related communications areas/patterns - particularly with regard to metrics and error logging.

## Tasks
- [x] Review and identity any profile-related endpoints are causing confusion or unnecessary telemetry noise.
- [x] Discuss different approaches on how to improve the information contained in 400-range responses from the vets-api.
- [x] Discuss different approaches for logging/monitoring 400-range responses from the vets-api.

## Acceptance Criteria
For error-related communications between vets-website and vets-api...
- [x] Determine a process for monitoring/logging 400-range errors.
- [x] Determine a consistent error message pattern for 400 and 500 range errors.
- [x] Create tickets for any endpoints that need to be updated.

**Comment by tpharrison** [comment]
@adamwhitlock1 - we can discuss this next sprint.

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/44771?planning-poker) with ZenHub @adamwhitlock1

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/44771?planning-poker) with ZenHub @tpharrison

**Comment by SKasimow** [comment]
@adamwhitlock1 @tpharrison - should I include this ticket in Sprint 79?

**Comment by tpharrison** [comment]
@SKasimow - that fine.  Adam and I will discuss some strategies and create tickets for the work.

**Comment by SKasimow** [comment]
@tpharrison ok I changed the title to reflect this as a "discovery" ticket.

**Comment by tpharrison** [comment]
Based on our discussion...

## Problem

When the Profile page loads, the following calls are made from the FE to the vets-api:
```
- /v0/user
- /v0/disability_compensation_form/rating_info
- /v0/mhv_account
- /v0/profile/full_name
- /v0/profile/personal_information
- /v0/profile/service_history
- /v0/ppiu/payment_information
- /v0/profile/ch33_bank_accounts
- /v0/profile/status/
```

This strategy results in extra traffic between the FE and BE API.  The extra calls fall into two groups:

#### 1. Unauthorized Requests

When the FE calls one of the above API endpoints to retrieve or modify data on behalf of a user, the request must pass an authorization check.  This authorization check is different for each endpoint and is based on the user having some combination of associated identifiers.  

For example, most endpoints require that the user have LOA3.  Some require an EDIPI, while others require an ICN.  

If authorization fails for a request, the API will usually send a 403 response.  This results in thousands of requests with 403 responses each day.  Each 403 response is logged in our telemetry/observability tools (Sentry, GA, Loki, etc.) creating a significant amount of data and noise.

#### 2. Unnecessary Requests

These are calls that are made even if the user never views the results.  

For example, when the profile page loads, only the personal information is displayed (by default).  However, requests are made for all of the other sections of profile (contact, notification, military, direct deposit, etc.).  These calls are unnecessary If the user never actually navigates to these other sections.

## Proposed Solution
To address the issues listed above, we should reduce the amount of extra requests that the profile page makes to the vets-api.  Reducing these extra requests will:

- reduce the load on vets-api servers.
- reduce the amount of errors logged to Sentry.
- provide more realistic BE metrics (more closely correlated to user actions).
- make it easier for our team to identity when actual errors do occur.

Here are two ways we can reduce requests:

#### 1. User Claims
First, when the initial page loads, the API will pass the FE “user claims”.  These claims will inform the FE which endpoints the user is authorized to call.  This will help reduce and possibly eliminate unauthorized requests to API endpoints.

A possible user claims may look something like this:
```
user_claims: {
  can_access_personal_info: true,
  can_access_has_contact_info: true,
  can_access_military_info: false,
  can_access_direct_deposit_info: false,
  can_access_notification_settings: true
}
```

If one of the above is `false` then the UI will not attempt to make the API call when the user requests the data.

#### 2. JIT Requests
Second, instead of calling all endpoints upfront when the profile page loads, each endpoint will be called as needed.  

For example, the endpoint required to display contact information will not be called until the user clicks the “Contact Information” link.

## Possible Concerns
Like any solution, there are potential concerns that need to be acknowledged:
1. The user claims must be accurately reflect the authorization rules for a user.  If for some reason, the claims become out of sync with the actual authorization rules, the user will not have access to data they are authorized to access.
2. Calling endpoints as needed may cause delays for the user.  Endpoint (such as BGS-related endpoints) are subject to periodic latency issues.  Calling these endpoints upfront may be alleviating some wait times since in some cases the data will be loaded ahead of the user requesting the data.

## Next Steps
Let's discuss this at our next sprint planning session.

If the team agrees with these next steps, we'd like to create tickets for modifying how/when the military service history endpoints are called.  This is a good representative endpoint and will allow us to test our theory without any significant risk.
