### ISSUE TITLE
[FE] Onsite Notifications: Remove code that triggers an error message when we cannot connect to the notifications API

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#44785]
## Background
When we are unable to connect to the API that determines whether a notification should be displayed or not we are supposed to show an error. We want to change this so that instead of an error when we can't connect to the API, the notifications section simple does not appear.

---
## Tasks
- [x] Remove code that triggers an error to display when we can't connect to the API
- [x] Add conditional logic so that the section simply does not display when we can't connect to the API
- [x] Test

## Acceptance Criteria
- [ ] When we can't connect to the API that determines whether we should show an notification or not, the notifications section does not display

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Work with a dev (and possibly VA notify) to create a "disconnect" between VA.gov and the API that determines whether VA.gov should show a notification

## Resources
- [Slack conversation](https://dsva.slack.com/archives/C909ZG2BB/p1658502230064079) for reference

**Comment by tmitchellgcio** [comment]
Only thing I can think of for validating this since we can't simply force an error on staging is to use the tests for validation. I have adjusted the test that looks for the error in the notification section after an error has occurred to now verify that the section does not show up when an initial error has occurred.
