### ISSUE TITLE
[BRD] GHA that checks newly committed ssm parameters exist

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#44781]
## Description
Since we have moved to a self serve approach for parameter store, there needs to be some guardrails in place to make sure when people add ssm parameters that they actually exist.  

In the scenario that they don't, it can cause failures as we saw with vets-api which is undesirable.  It is also not efficient to be checking these manually for every pull request.

## Background/context 
https://dsva.slack.com/archives/C30LCU8S3/p1658430898452319

https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameter.html

---
## Tasks
- [x] capture any ssm parameter values added or changed in a PR
- [x] run `aws ssm get-parameter --names <list of parameters>`
- [x] If any parameters don't exist they will be listed in the `InvalidParameters` array
- [x] comment back to PR if any parameters are invalid

## Acceptance Criteria 
- [ ] No PRs can be merged if a invalid parameter exists
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
<img width="1818" alt="image" src="https://user-images.githubusercontent.com/76792875/180831233-0c24e55f-371e-4545-b6a7-3429269f2ede.png">

merged and closed
