### ISSUE TITLE
[BRD] Set retry limit for vets-api docker container restart on error

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#44784]
## Description
In the scenario that bad code or configs do make it into vets-api and the docker container fails to start due to errors, this will create an endless loop of said docker container attempting to restart itself.  

Where this showed to be a problem is during a failed deployment of vets-api which resulted in our redis system taking an extreme amount of load and ultimately becoming unreachable.  With redis unreachable we were unable to serve any traffic from the healthy asg that still existed.

Using the `on-failure[:max-retries]` option should mitigate this.

https://docs.docker.com/config/containers/start-containers-automatically/

https://dsva.slack.com/archives/C30LCU8S3/p1658430898452319

---
## Tasks
- [ ] Set flag for max retries on vets-api docker container in the appropriate ansible deploy configs

## Acceptance Criteria 
- [ ] Vets-api won't endlessly retry to restart if there are bad configs or code deployed which won't allow us to ddos our redis instances 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
There does not appear to be any `--restart` policy on the vets-api containers.

https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-prod.yml#L77
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-worker-vagov-prod.yml#L68

This PR proposed the idea, but it was closed out without merging, https://github.com/department-of-veterans-affairs/devops/pull/10948/files

**Comment by jhouse-solvd** [comment]
@ph-One - Is there any coordination needed to implement this? It's listed as a follow-up action item to [this post-mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/6ed26d02ee29792ecaf02ba8def02e7b3e95b117/Postmortems/2022/2022-07-21%20Vet-API%20Failure%20Retries%20Invalid%20AWS%20Parameter.md). Let me know when it would be good to take on?

**Comment by ph-One** [comment]
This can be closed. The idea of restricting container restarts came from me bc I thought the restart policy was set on the service, which is not the case. The current behavior is that if the container errors out, it does not restart.
