### ISSUE TITLE
[FE] [BUG] erroneous API calls made when refreshing pre-checkin

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#44798]
## Background

This is a follow-on from #44705 - when refreshing after validating pre-checkin, the browser sends a GET session request with token `undefined`, briefly goes to the error page, and then returns to the previous page. We should skip the error-y part :-)

## Tasks
- [ ] calls are not made with an undefined token
- [ ] app correctly re-loads the current page when refreshing
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
Fix does not appear to have addressed the issue. Moving back to Current Sprint so we can start brainstorming again.

**Comment by acrollet** [comment]
To clarify, @brdunfield's fix addressed the issue in the ticket, but we found an additional issue when directly loading the `complete` page without a valid session.

**Comment by acrollet** [comment]
Placing this in validate, we'll check back in GA on Wednesday and if errors have fallen back to normal levels we'll know this is done.

**Comment by acrollet** [comment]
I just ran through a test pre-checkin on staging and also verified that successful pre-checkins are continuing on prod.

**Comment by acrollet** [comment]
As of yesterday errors have fallen to approximately the same ratio of errors to successful pre-checkins as day-of checkin. Closing this as complete. 

![Screen Shot 2022-08-04 at 08.32.23.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/2455e0fd-3cf0-4fd5-b009-75e657f27596
)
