### ISSUE TITLE
Create VFS-Change-Announcements Only type of channel

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44793]
## Issue Description
We found from our Discovery that there is high interest in keeping announcements in Slack, and further interest in a new Announcements Only sort of channel.
- We could name it to reflect that it is for Change Announcements only
- Users would be directed to post there only in the predetermined format from the Comm. Plan, keeping the format consistent and more easily scannable.
- Conversation would be limited to threads of the original posts only, limiting overall posts and a high level of scroll to get to items of interest.
- Some moderation may be required, moving non-announcement posts to VFS-all-teams, for instance

## User Story
As a VFS team member, I would like to both be alerted to and be able to easily locate announcements that are related to Product Changes, Process Changes, or Informational Changes, so that I can be notified of changes that are relevant to me.

## Tasks
- [x] Determine what to call the channel (vfs-change-announcements)
- [x] Speak with Andrea to determine if we can create this channel, how to spread its adoption, and thoughts on who would moderate it
- [x] Check with PO to verify that new channel resonates as a team capability and approach
- [x] Create the channel (Bryan/Ray)
- [x] Edit the Topic and Description
- [x] Adjust settings to allow posting by all
- [x] Add relevant bookmarks (i.e. Change comm plan, Slack post format, Change comm landing, etc)
- [x] Create a pinned post for the channel that outlines the best practices/rules for posting, and any expectations we have of contributors and audience
- [x] Clean up posts about maintenance (changes to topic, etc.)

## Acceptance Criteria
- [x] Channel is created and setup w/ customizations

## Post-Change steps
- [ ] Monitor the new channel to check adoption

**Comment by twoangstroms** [comment]
From Eunice Garcia: "there are a few admins that have access to approving requests in this channel. So far I am the only COR on the VA/OCTO side and normally approve any contractors requesting to be added on the channel (part of the onboarding process on this end).
There is no hard rule against creating a new channel but I would run it be the PM first. We have so many channels that are created and then no one maintains that channel and become rogue."

"I would go for it. Just make sure there is someone maintaining that channel and keeping mind of all information posted is FOIAble, if that makes sense."

**Comment by twoangstroms** [comment]
From Andrea on how to spread adoption: 

- Discovery readout at office hours
- Present to the leadership team

**Comment by steel36** [comment]
additional justification:  users expect announcements to find them, hence a dedicated channel where these would ping users, and be findable later.

**Comment by steel36** [comment]
Removed tasks/criteria to announce new channel.  We'll reserve that for the rollout of the updated Playbook

**Comment by twoangstroms** [comment]
Set channel posting to:

"Posting permissions
Everyone can post
Everyone can reply to messages
No one can use @channel or @here mentions"

(On the last: the channel and here toggle come as a package. Best practices would suggest to keep them off.)

Documentation on how to change these settings: https://slack.com/help/articles/360004635551-Manage-channel-posting-permissions-#business+-and-enterprise-grid-plans-1
