### ISSUE TITLE
Confirm Form Funnel Steps with VFS Teams 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#44808]
## Issue Description

As a follow up to ticket #44652 we are going to reach out to VFS teams to confirm we have the most up to date funnel steps and confirm which steps are mandatory vs optional to ensure we are displaying the correct funnels for each product on the Forms dashboard.
---
## Tasks
- [x] Reach out to the following teams currently on the forms dashboard to confirm the steps in their funnel
     - [x] 1010 CG - _needs to be updated (see below)_
     - [x] 1010 EZ - _needs to be updated (see below)_
     - [x] 20-0996 Higher Level Review
     - [x] 21-526EZ Original Disability Form
     - [x] 22-1995 Request for Change of Program - _No changes_
     - [x]  28-1900 Ch31 
     - [x] 5655 Financial Status Report - _no changes_

## Acceptance Criteria
- [ ] When we have reached out to teams and forms funnels updates have been provided (as applicable).
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
1010EZ needs to be updated based on [these funnel steps](https://docs.google.com/spreadsheets/d/14Jxyh7oTS94eClXWbwhDMp_M5EhrkJEcoHt0wpzA1qI/edit#gid=0)

**Comment by michelle-dooley** [comment]
1010CG needs to be updated based on [these funnel steps](https://docs.google.com/spreadsheets/d/1TrqoUUE9YqhYZb6pR2W6UoLg_H_Lbi-UuxNN5MI-vZ0/edit#gid=649068577)  - see yellow highlights
