### ISSUE TITLE
Update apps API's directory.url setting to forward proxy address

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44801]
## Issue Description
The Apps API setting in vets-api is used for a listing of third-party apps. The route `v0/apps` makes a client call to `/services/apps/v0` which first gets routed through Kong but is implemented as an engine in vets-api. 

To ensure that the setting continues to work correctly after the Lighthouse migration, it would need to be updated to using the forward proxy address and an appropriate port. ~It is not clear if dev and staging should use the sandbox environment or their own environment.~ All environments should use the `4475` port in the fwdproxy. The API keys that Kong checks differ from each other in the different environments.

The identified settings are:
- `directory.url`

This setting exist in dev, staging, sandbox, and production. 

---
## Tasks
- [x] Settings updated and tested in dev env
- [x] Settings updated and tested in staging env
- [x] Settings updated and tested in sandbox env
- [ ] Settings updated and tested in prod env

## Acceptance Criteria
- [ ] All settings changed and tested in all relevant environments.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
