### ISSUE TITLE
<Accessible 1095-B MVP> x Staging Review Accessibility Checklist

### ISSUE THREAD

**Issue by tameracorson** [department-of-veterans-affairs/va.gov-team#44811]
## Acceptance Criteria
- Complete required accessibility checklist items for staging review:
  - [ ] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)
  - [ ] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - Conduct axe browser scan, and document or address issues found
  - [ ] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - Ensure end-to-end tests - including the axe check, pass
  - [ ] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - Check color pairing for proper contrast
    - Check for colorblindness issues
  - [ ] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc
    - Repeat for 300%
    - Repeat for 400%
  - [ ] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - Navigate all pages and core functionality with keyboard only
  - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)
    - Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox
- [ ] Check off items as they are completed

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Attach to Collab Cycle Epic**
- [ ] **Labeled with Team**

**Comment by tameracorson** [comment]
Axe scan document https://docs.google.com/document/d/11IzSmGRaE4IcqtbLq9lTPPq4SwryvCEQ7uMoTovUgeI/edit

**Comment by tameracorson** [comment]
Notes from Dan Smith 8/9/22:
Ticket: 44811 - Staging Review Accessibility Checklist - Dan Update:
6/7 Tasks complete.
Last Remaining task is "Axe Scans in end-to-end tests"
Try to find where the E2E tests need to live / who owns them. Will look for an existing end to end test that should cover similar behavior to the widget.
Finished the Keyboard Navigation Testing
Finished the MacOS voice-over + Safari testing. (Fair Warning)... it doesn't behave the same in Chrome, however, that doesn't appear to be a required "Browser" for MacOS. Safari is the only noted necessary VoiceOver listed browser for Mac.
The Screen reader can't hit the "Options" and the text next to them in Chrome.
Will continue to dig more into the Cypress End-To-End Testing details.

**Comment by DanSmithSC** [comment]
#### There are 2 Axe Scan "For Review"

1) The "We couldn't download your form" view.
- "Issue Description":
 - Ensure that links with the same accessible name serve a similar purpose.
 
This a "Review" note - Not necessarily an issue. It's just designated as an automatically flagged note.   
There's a 2nd TTY aria-label in the footer. The aria labels differ slightly. It appears to have the same purpose, but got flagged.
Could potentially just copy the aria-label and href info from the footer if they're supposed to be identical. 

Element in the Footer:
`<a aria-label="TTY: 7 1 1." href="tel:+1711">TTY: 711</a>`

Element in the 1095-B Widget:
`<a aria-label="TTY: 7 1 1" href="tel:711">TTY: 711</a>`

2) "Choose your file format and download your document
 - "Issue Description":
 - Ensures all ARIA attributes have valid values
  
  Element Location: `#\31 095-download-options-0`
  Element Source: 
    `<input id="1095-download-options-0" name="1095-download-options" type="radio" aria-describedby="Option 1: P D F Document (best for printing)" value="pdf" checked="">`
  
The Axe Prompt to solve the issue is states: 
    ```
    Fix the following: 
    ARIA attribute element ID does not exist on the page or is a descendant of a different shadow DOM tree: aria-describedby="Option 1: P D F Document (best for printing)"
    ```
This Axe Scan Warning will throw for whatever Download Option is selected. If you have the second "Text File" option selected the scan will flag this element instead.

**Comment by DanSmithSC** [comment]
Starting work on E2E Cypress Testing - E2E Tests are last remaining task.

**Comment by tameracorson** [comment]
@DanSmithSC I see that the box for E2E axe scan was checked.  Is there something you can drop here to show this work, so I can check the last box?

**Comment by DanSmithSC** [comment]
Above is an E2E Test play through of a scenario which shows no Accessibility Scan Issues are present. 
![Screen Shot 2022-08-12 at 8 57 29 AM](https://user-images.githubusercontent.com/994827/184358543-3d725c80-b1c8-4104-b539-63441e0d8ff9.png)

Below is my pull request for adding some end to end tests that satisfy the last task. 
https://github.com/department-of-veterans-affairs/vets-website/pull/21919
