### ISSUE TITLE
[FE/BE] Profile: Investigate what types of characters are acceptable in the address form 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#44816]
### Background

On Friday, July 22, I was made aware that there **might** be an issue with the contact information form in the profile. Someone from VA Profile pulled me into an email thread where there was an example of a veteran who lived in Japan entering Japanese characters into the contact information form. This address was accepted by VA.gov/VA Profile, but it caused issues with mail printing down the line, resulting in invalid hexadecimal characters (not English or Japanese) that made it impossible to decipher what the actual address is. This resulted in the veteran not being able to receive their benefit payments via paper check.

Here is a screenshot of the symbols that resulted in one of the systems with all identifying info removed:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/34068740/180803230-78692965-c100-4656-b72e-d1528b63d2f9.png">

I've forwarded the email thread with all the details to keep identifying information out of Github.

### Tasks

The goal of this ticket is to investigate what VA.gov will accept in the address field, and to figure out if there is any way we can limit what we accept to the English alphabet and system-friendly symbols. 

- [ ] Determine if we accept Japanese characters, or any other characters/symbols from other languages.
- [ ] If we do, determine if there is any way to limit what we accept on the frontend.
- [ ] If there is any way to limit what we accept on the frontend, regroup with the team if there are any design updates needed (eg. copy for error messages).

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/44816?planning-poker) with ZenHub @adamwhitlock1

**Comment by tpharrison** [comment]
@SKasimow @Samara-Strauss 

@adamwhitlock1 and I discussed this and we will each have a ticket to add this validation rule to the FE and BE (mine is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45051)).  

The FE will restrict the phone ext field to 6 digits, but in the case where a request does make it to the vets-api, validation will be in place to reject the request.

**Comment by SKasimow** [comment]
@tpharrison thanks Tom - I added your ticket onto the Sprint 80 epic
