### ISSUE TITLE
Profile Team | Sprint 81 | 8/24 - 9/6 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44832]
## PTO/OOO/Unavailable

- **Adam**: 8/29-9/2 ![image.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/f179ec7c-a31f-48bd-a12c-7fa1d8be8ce9)
- **Christina**: 9/2
- **Sharon**:  9/2 
- **Tom**: 9/2
- **Samara**: 1/2 day 9/1, 9/2
- **Liz**:  

**Note** 9/5 Labor Day 

## Sprint Priorities
- Bad Address Indicator - contact center guide/checkpoint
- Continue various Profile documentation reviews & updates
- Accessibility doc [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/accessibility/accessibility-audit-updates.md)

---

#### Design - Christina
- [x] #45800 Update CC guide with new alerts (3 pts)
- [x] #45807 Plan UAT (3 pts)

#### PM - Sharon
- [x] #42706 Schedule Staging Review (1 pt)
- [x] #44330 Contact center explanatory text updates and CC review touchpoint (3 pts)

#### FE - Adam
- [x] #45905 Bug to update font color for system error (unplanned work) (1 pt)
- [x] #46065 Update checkmark color (unplanned work) (1 pt)

#### FE - Adam
- [x] #44934 FE doc for Personal Info (1 pt)
- [x] #44935 FE doc for Contact info (3 pts)

#### BE - Tom
- [x] #45525 BE documentation Notification Preferences - carry-over from Sprint 80 (3 pts)
- [x] #45828 Logging & Metrics documentation (3 pts)

#### Design - Liz
- [x] #45856 Documentation for Military info (3 pts)
- [x] #45891 Documentation for Notification Preferences (3 pts)

#### BE - Tom
- [x] #46087 Discovery - open-ended service history (1 pt)

#### Design - Christina
- [x] #11053 Add DD214 (3 pts)

#### FE - Adam
- [x] #45263 Limit Phone # Extensions to 6-digits (1 pt)
- [x] #44697 Text Update (1 pt)

#### BE - Tom
- [x] #45822 Selectively calling vets-api endpoints for a user (3 pts)

#### Design - Liz
- [x] #27979 Sign in information improvement(3 pts)
- [x] #46149 Update Military alerts (2 pts)

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - I've made some updates to the sprint plan including adding in Military documentation (Liz); the other ones planned for this sprint include: Adam (Personal, Contact and Outages) and Tom for Connected apps (Tom has already worked on Military and Personal).  Christina is working on Personal Info in the current sprint (Sprint 80). 

Also added in a ticket for Liz/Research for 1095B.

**Comment by SKasimow** [comment]
- "Iceboxed" 1095B Notification Preferences tickets.
- Added ticket for documentation of Notification Preferences (#45891)
