### ISSUE TITLE
Profile Team | Sprint 80 | August 10 - August 23 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44831]
## PTO/OOO/Unavailable

- **Christina**: 8/19
- **Sharon**:  8/12 & 8/19
- **Tom**:  
- **Samara**: 8/12
- **Adam**: 
- **Liz**:  8/10 - 8/12

## Sprint Priorities

- Continue roll-out of Military info --> VA Profile
- Begin Notification Preferences/1095B work
- Complete Design and FE updates for BAI
- Create feature flag for DD

------

#### PM - Sharon

- [x] #44739 Complete release plan (1 pt)
- [x] #45481 Update Use Cases (1 pt)

#### Design - Christina
- [x] #45184 Content Revisions

#### FE - Adam
- [x] #45366 UI updates (2 pts)
- [x] #45262 Foundational Accessibility testing (2 pts)

(**Note**: once UI and content updates are finalized, we'll need to update QA/Use Cases, sketch files, and complete FE work)

#### BE - Tom
- [x] #45274 50% deployment (1 pt)
- [x] #45275 100% deployment (1 pt)

#### FE - Adam
- [x] #45093 Add Custom Event for GA tracking (1 pt)
- [x] #45194 Re-deploy to 50% (1 pt)

#### Design - Liz
- [x] #45073 Initial mocks & content (5 pts)
- [x] #45074 Create confirmation email (2 pts)
- [x] #45075 Send mocks and email to 1095b/legal team for review (3 pts)

#### Product - Sharon
- [x] #45294 Create Epic (1 pt)
- [x] #45260 Collab Cycle kick-off (1 pt)

#### Design - Christina
- [x] #44083 UAT/Hint Text
- [ ] #44084 UAT/FAQs Content (rolling over to Sprint 81)
- [x] #45761 Messaging for validation of ASCII only character set (2 pts)

#### Design - Christina
- [x] #44917 Personal info/Design documentation (3 pts)

#### BE - Tom
- [x] #[45525](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/45525) BE documentation Notification Preferences (3 pts) (rolling over to Sprint 81) 
#### FE - Adam
- [x] #45488 FF for Direct Deposit weekend outage
- [x] #45512 Implement new messaging for DD weekend outage
- [x] #45595 Remove FF for DD
- [x] #45061 Add feature toggle for payment notification (2 pts) (Needs validation)
- [x] #45400 Restrict character access (2 pts)

#### Design - Christina
- [x] #45487 Create DD error messaging
- [x] #45257 6 digit extensions (1 pt)
- [x] #45761 Messaging for validation of ASCII only character set

#### BE - Tom
- [x] #45323 Restrict character access (2 pts) 

#### Design - Liz
- [x] #43586  Add heading back into UI alerts (3 pts)

#### BE - Tom
- [x] #45051 (2 pts)
- [x] #45992 (misc unplanned work)
