### ISSUE TITLE
[EKS] GitHub Action that checks that newly committed SSM parameters exist (application-manifests repo)

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#44830]
## Description
**This is complete for the `devops` repo at this time, but we should likely extend this check to the application-manifests repo as well.**

Since we have moved to a self-service approach for parameter store, there needs to be some guardrails in place to make sure when people add ssm parameters that they actually exist.  

In the scenario that they don't, it can cause failures as we saw with vets-api which is undesirable.  It is also not efficient to be checking these manually for every pull request.

## Background/context 
https://dsva.slack.com/archives/C30LCU8S3/p1658430898452319

https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameter.html

---
## Tasks
- [ ] capture any ssm parameter values added or changed in a PR
- [ ] run `aws ssm get-parameter --names <list of parameters>`
- [ ] If any parameters don't exist they will be listed in the `InvalidParameters` array
- [ ] comment back to PR if any parameters are invalid

## Acceptance Criteria 
- [ ] No PRs can be merged if a invalid parameter exists
---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Adding all relevant PR's (including testing)
https://github.com/department-of-veterans-affairs/devops/pull/11687
https://github.com/department-of-veterans-affairs/devops/pull/11686
https://github.com/department-of-veterans-affairs/devops/pull/11684
https://github.com/department-of-veterans-affairs/devops/pull/11683
https://github.com/department-of-veterans-affairs/devops/pull/11682
https://github.com/department-of-veterans-affairs/devops/pull/11680

**Comment by oseasmoran73** [comment]
Adding [Slack](https://dsva.slack.com/archives/CTYQL39FE/p1658855006249359) thread

**Comment by jbritt1** [comment]
Think this is complete with the flipping of the switch to make this a required check for all pull requests going forward.

**Comment by jbritt1** [comment]
Closing per some internal discussion: https://dsva.slack.com/archives/CTYQL39FE/p1658957326935579
