### ISSUE TITLE
EMIS deprecation: Disable Pre-fill

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#44853]
## Description
The external service EMIS is being deprecated. EMIS is an external service integrated into vets-api and appears to be heavily engrained into the vets-api codebase. **All of the EMIS deprecation is due August 15.**

As part of the form pre-fill feature, EMIS `military_information` is pre-filled for the veteran. 
More information on [how military info is prefilled here](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP). We should be sure to disable the military_information pre-fill feature before the cutoff date. The date was originally September 30th, but we may have until the end of Q4 2022.

Also see:
1. [EMIS deprecation discovery](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation)
2. [Prioritization](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2274426885/EMIS+deprecation+prioritization)
3. [EMIS pre-fill impact](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2286714883/EMIS+Pre-fill+Impact+WIP)

## Acceptance Criteria
- [ ] EMIS pre-fill is removed/commented out
- [ ] Tests are updated
- [ ] A plan to migrate from EMIS to VaProfile for military_information is documented/tickets opened

**Comment by laineymajor** [comment]
@holdenhinkle @little-oddball 
TT1 is reviewing the backlog to pickup a ticket for next sprint... looking at this one, the team is wondering if this should be an entire project?
If questions about this @LindseySaari @RachalCassity

**Comment by little-oddball** [comment]
@laineymajor - what would the LOE of the work be? Can the tasks related be isolated and insulated?

**Comment by laineymajor** [comment]
This is a large piece of work and needs to be broken out into an epic with supporting tickets... circle back with @LindseySaari when she returns from OOO

**Comment by laineymajor** [comment]
Can we build upon what they've done, or do we need to start from scratch? Hopefully we can build on what they have.

**Comment by laineymajor** [comment]
Rebecca met with Lindsey... 
1. needs to get vets-api setup locally on new computer
2.

**Comment by LindseySaari** [comment]
Syncing with Rebecca and Holden after standup today

**Comment by laineymajor** [comment]
Recap of sync yesterday:
- screen share with rebecca
- some pairing
- holden reviewed the [doc](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2264694838/EMIS+Deprecation#EMIS-More-Broadly) lindsey created re eMIS work
- began working in the branch locally
- holden continuing to get up to speed

**Comment by laineymajor** [comment]
Reference #61658 as that's a dupe

**Comment by laineymajor** [comment]
This needs to be moved to next sprint as we are still resolving bugs.
