### ISSUE TITLE
Add information on the VA 508 Office Audit process to Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#44877]
## User Story
As a VFS team member, I want to understand the steps and process taken by the VA 508 Office when my team submits our product for audit so that I can ensure our product is fully ready for review and be aware of the many steps the VA 508 Office takes to perform the audit. 

Assignee:
Peer Reviewer:

## Description
At the monthly VA 508 Office meeting on Wednesday 7/20, Chris Walker (our VA 508 Office representative) shared the steps his team takes when a product is submitted for audit. @artsymartha68 took notes of the conversation and shared with Governance team. The notes are below:

> Chris: audit for GI comparison tool underway
> - Launched a while ago
> - Brian was transitioning in
> - Education tools are under VBA contracts – contractual problems, other ones as well
> - A11y is the reason we can even look at their stuff
> - Chris: the sooner you can get them to him the better
> - A lot of things we do wait till they’re in production before the audit comes in
> - We find the critical stuff so far down the road
> - Teams have disbanded
> - Haven’t found anything critical in a while for OCTO teams
> - Shira: comes as a shock that they have to submit to 508 office
> - Validation statement is a requirement to ship – hard bc it must be in production? – happy to get pre-prod though
> - Not a preference for prod – would like to be in pre-prod
> - Encourage audit before they launch
> - As long as we have access to the eval system we can get in there and access the code, has been problematic in the past – Chris is OK with waiting till production
> - Don’t want to be a toll gate
> - Audit sometimes takes 5 weeks for the audit
> - Shira: right not we request after the internal audit, share known a11y issues, we have the lower severity issues list. What if we asked them to submit the audit before they launch. Could be a 5 week turnaround. Can be part of our process to at least get the request number. Could be a requirement to launch.
> - Chris. Not sure it would help a lot if they don’t ship on time. We usually tell them to wait. Will verify code is there, 5-10 minutes usage, what is the scope how it works. Make notes. If critical defects, send it back right away. If OK then send to full auditing team, a few weeks later. Double check their results. Then give the audit process back.
> - Shira: hopeful we can have better comms about the status, a nudge to the team

## Impacted Artifacts
New page linked from 508 audit page

## Tasks
- [ ] Set up meeting with Chris Walker
- [ ] Document the VA 508 process for audit
- [ ] Communicate to VFS teams on Platform Website (Shira's 2 cents: update the actual audit page)

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS teams are aware of the VA 508 office process for an audit

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.
