### ISSUE TITLE
[FE] Onsite Notifications: Analytics Implementation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#44881]
## Background
Once we receive the necessary information from the analytics and insights platform team we can implement the front end configuration to implement analytics for onsite notifications.

Taxonomy to implement tracking if notifications are present or not for users without them clicking anything. You will need only need to fill in api-name , api-status.

```
{
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'started',
}
```

An example would be :
```
{
     event: 'api_call',
     api-name: 'Onsite notifications',
     api-status: 'not delivered',
}
```

## Tasks
- [ ] Complete code changes
- [ ] Request validation from analytics team

## Acceptance Criteria
Analytics implementation is ready for onsite notifications and we are able to track the following metrics through GA:
- [x] Whether onsite notifications are present or not without the users having to click anything
- [x] Clicks to view/manage all debts
- [x] Clicks on the dismiss button
- [x] When the dismiss fails
- [x] When notifications fail on VA.gov (we need to know when we are unable to display notifications)

## Validation
**- _Who can validate this ticket? (FE, BE, Design, PM)?_** Analytics team member
**- _How can this work be validated?_** Tag the analytics team in this ticket and in slack (vfs-platform-support, or ask a PM for assistance) to request that they review the implementation

**Comment by ajakabcin** [comment]
@tmitchellgcio taxonomy to implement tracking on whether notifications are present or not (without the user having to click anything) provided below:

Per [Jonathan's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41730#issuecomment-1195916408), you will need only to fill in _api-name , api-status_ :

{
     event: 'api_call',
     api-name: 'View Claims and Appeals',
     api-status: 'started',
}

**Comment by tmitchellgcio** [comment]
Hey interesting thing. I thought I may not have implemented this and it looks like I have. I've been following a previous pattern we had for API calls so I kinda forgot I have those in the pattern I use. I have it checking `GET on-site notifications` and if it's `successful` or if it `failed` and then I have it checking `PATCH dismiss on-site notification` with successful or failed already as well. I don't have one for `started` if we need that.

**Comment by tmitchellgcio** [comment]
@jonathan-epstein13 This is ready to be validated. Do you guys validate this in production or staging?

**Comment by jonathan-epstein13** [comment]
@tmitchellgcio we validate in staging. Can you send over the exact staging URL? Or should I just use the staging.va.gov/manage-va-debt/ URL and navigate to where you want me to validate? Just making sure.

**Comment by ajakabcin** [comment]
@jonathan-epstein13 notifications will be on My VA so staging.va.gov/my-va. You can see which test users should have notifications [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-onsite-notification.md#test-users-for-end-to-end-testing-with-dmc). Let us know if you're not seeing them though, we may need to have VA Notify re-send them.

**Comment by jonathan-epstein13** [comment]
@ajakabcin sounds good! I'll post to the ticket [here](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/department-of-veterans-affairs/va.gov-team/41730)
I see these test users below:
![image](https://user-images.githubusercontent.com/91892981/183150379-7466336c-2ed6-4c20-a282-23b4306a457f.png)

**Comment by ajakabcin** [comment]
confirmed with analytics that tracking is working as intended
