### ISSUE TITLE
FE | Profile | Update UI Alerts for Address Validation Use Cases

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44886]
## Background
 
We need to update the heading and body copy in the current alerts for 4 address validation use cases: (see ticket #44407 for adt'l background).

## Tasks

- [x] 1. Suggested address found
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/rbJ5V77)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/4a3Wp3q)

- [x] 2. Address not found, no suggestion found
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/nRj5oKd)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/3OrW1bw)

- [x] 3. Missing unit number
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/qeJ4aVV)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WKmL09n)

- [x] 4. Bad unit number
- [Desktop mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/Jn9jQMe)
- [Mobile mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/QbJeZR7)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & have re-validated

**Comment by SKasimow** [comment]
@adamwhitlock1 - can you review/point?

**Comment by Samara-Strauss** [comment]
Moving to sprint 85 to account for sprint 83 tickets rolling over into sprint 84.

**Comment by Samara-Strauss** [comment]
Moving to sprint 85 to account for sprint 83 tickets rolling over into sprint 84.

**Comment by adamwhitlock1** [comment]
@SKasimow this is ready to validate on staging.

**Comment by Samara-Strauss** [comment]
This looks right to me. I think the non-override cases in the code are from uses cases we had prior to launch but decided to nix before launch.

**Comment by SKasimow** [comment]
Closing...
