### ISSUE TITLE
[Postmortem 2022-07-21 Follow-up] Clarify the Incident Response and Notification Process for Major outages

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#44897]
# Description

Changes to [this file ](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2) affected Vets-Api in Production.  

We have a number of Action Items for [Postmortem on Vets-Api Major incident.](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/post-mortem/7-21-22-vets-api-outage/Postmortems/2022/2022-07-21%20Vet-API%20Failure%20Retries%20Invalid%20AWS%20Parameter.md)

# Tasks:

- NOTE: These tasks were taken from [Notes from Open House Meeting.](https://vfs.atlassian.net/wiki/spaces/AP/pages/2286813220/7+26+22+Office+Hours+Agenda+and+Notes)

### [Postmortem Updates Tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/post-mortem/7-21-22-vets-api-outage/Postmortems/2022/2022-07-21%20Vet-API%20Failure%20Retries%20Invalid%20AWS%20Parameter.md)

- [x] Add announcement in Vfs-platform-support to timeline
- [x] Add more details to the “what happened” section. Add details about how this occurred. The environment variable existed in lower environments but not in production. (see [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44897#issuecomment-1205682232); should be added to post-mortem)
  - [x] Add to post-mortem
- [x] Need to include that right now it takes 30-40 minutes to rebuild Vets-API 
- [x] Add event to timeline about communication about errors still being received for login attempts on VA.Gov
- [x] Add Clarification on How to [Identify the Incident Commander.](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook#Incident-commander)
### Tasks To Perform based on Postmortem

- [x] Understand how this happened: See #45165 for follow-up investigation
  - Investigate potential points of failure in the deployment process that aren’t yet identified 
  - What happened with the incident response? 
  - How can we limit the impact to Redis (or other related infrastructure services) due to a misconfigured deployment?
- [x] Make it clear in [internal documentation who the incident commander](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook) is and what their role is in an incident like this. 
  - ie, Steps of notification → TLS, Vendor leadership, OCTODE Platform leadership, OCTODE leadership (Chris and Charles, PMO group – Erika and Julie – if you don’t know them ask @Andrea Hewitt) 
- [x] Clarify communication process and expectations for outages: OCTO, VFS, Platform, End User, Other VA group, etc.

- [x] Figure out how to ensure parity between environments 
   - ..[Open Issue for creating a Chaos Environment.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39839)
   - How do we account for configuration differences in different environments? 

- [x] Expand the [incident response playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook) to include a scenario that mirrors what happened here. 

- [x] Update[ VFS Developer Incident Management Document](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45157).  
 
- [x] Issue(s) to enhance the effectiveness of PagerDuty alerting for Incidents should be added to Post-mortem action items 
  - See #43749 
  - [x] Add to post-mortem

- [x] Decide if new the new GitHub Action check should block PRs that reference invalid SSM Parameter Store values

**Comment by zachclarity** [comment]
This [alert document](xhttps://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) needs updating and linkages to playbooks for responding to each alert.

**Comment by zachclarity** [comment]
Group action items with update postmortem and other tasks follow-on @zachclarity

**Comment by jhouse-solvd** [comment]
_RE: Add more details to the “what happened” section. Add details about how this occurred. The environment variable existed in lower environments but not in production._

There are Vets-API environment variables supplied by SSM Parameter Store values. Those values existed in the development and staging environments. And the connection created by those parameters had been established and validated in those environments. These changes were performed days or weeks prior to the change that took place in production. 

However, when Vets-API was deployed, the values for the production environment did not exist in the SSM Parameter Store path referenced by the code.

**Comment by jhouse-solvd** [comment]
_RE:  Add event to timeline about communication about errors still being received for login attempts on VA.Gov_

Please see [post-mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/527/files), 2022-07-21 5:15pm ET...

**Comment by jhouse-solvd** [comment]
_RE: Decide if new the new GitHub Action check should block PRs that reference invalid SSM Parameter Store values_

This was made a blocking check on new pull requests to the devops GitHub repository per Clint's request _(See #44781 for more info)_

**Comment by zachclarity** [comment]
> 

[Updated in Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/post-mortem/7-21-22-vets-api-outage/Postmortems/2022/2022-07-21%20Vet-API%20Failure%20Retries%20Invalid%20AWS%20Parameter.md#why-did-it-happen).

**Comment by jhouse-solvd** [comment]
@zachclarity - Please create a task for 'make it clear who the incident commander is...' and link here?

**Comment by zachclarity** [comment]
Added how to [identify who the Incident Commander.](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/va.gov+incident+playbook#Incident-commander)

**Comment by zachclarity** [comment]
Follow action items linked.
