### ISSUE TITLE
[FE] Create cypress tests to get screenshots of phone appointments

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#44896]
## Description
Add happy and error path cypress tests for pre-check-in phone appointments. Include screenshots and add a screenshot spec file to generate screenshots.

## Tasks
- [ ] Create PCI phone appointment happy path tests
- [ ] Create PCI phone appointment error path tests
- [ ] Add screenshot for every unique page
- [ ] Create screenshot spec file to run needed tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
Closing with code review, no further validation needed.
