### ISSUE TITLE
[FE] Cancel an Appointment - UI

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44902]
## User Story
As someone who uses the Staging Tool to create appointments in VistA staging, I would like to be able to cancel an appointment so that I can test affected functionality.

## Background
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1658787144382739)

## Tasks
- [ ] [FE] Create frontend UI for cancelling an appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
