### ISSUE TITLE
[task] Certificate of Eligibility | Write Test Scripts

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#44908]
## Value Statement
**_As a_** team
**_We want to_** create UAT testing scripts for the Certificate of Eligibility workflow
**_So that_** we know which use cases to test and how to test them. 

---
## Background Context
UAT testing will be completed by squad 2. As such, each team member involved in testing needs to know how to test each use case. 

## Designs and Build Notes
- Documentation in [max.gov](https://portal.max.gov/portal/home) (need your PIV to login and review)
- [CoE in staging](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction) on va.gov
- [Use cases and for workflow](https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/screen/475bb5b9-8551-41f9-9b1e-236b052316e0/?fullscreen) for CoE
- [Prototype](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap)
- [Link to use cases documentation](https://drive.google.com/file/d/18YBVkk7qbnqIdBG8ttWxXQdfHZjrYXB8/view)
- [UAT Testing plan](https://docs.google.com/document/d/1-74nQNxmJ-5xKUMK6V-NFii1LPvuwYWupsHABMCd0b0/edit)

## Out of scope
- The scope of this ticket does not cover design or code changes.

## Tasks
- [ ] _Write scripts for each use case that we are testing._
- [ ] _Review internally with squad 2 testers._
- [x] _Confirm that lower environments and LGY service is setup for testing._
- [ ] _Confirm that testers have access to the test environment._
- [ ] _Block calendar time for testing as a team._
- [ ] _Document testing in Github._

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@jsokohl @scottymeyers FYI I wrote a placeholder for this.

**Comment by jsokohl** [comment]
awesome!

**Comment by saderagsdale** [comment]
@sortizsh @jsokohl Can we schedule a review session for mid next week so we can check progress on this task?

**Comment by sortizsh** [comment]
Can you attach your file here?

**Comment by jsokohl** [comment]
https://docs.google.com/spreadsheets/d/1mU2Q2Lg4U5tVA3pc2eGwGelc3pNs4k3mWPPlnrlEwyc/edit?usp=sharing

**Comment by saderagsdale** [comment]
@jsokohl Is this task completed? Looking to understand if this is carrying over into the new sprint or getting closed.

**Comment by jsokohl** [comment]
I still need to confirm scripting for the `check status `portion of COE and then run it by the dev team. So one last sprint.

**Comment by saderagsdale** [comment]
@scottymeyers Can you link the ticket this depends on?

**Comment by jsokohl** [comment]
@saderagsdale This ticket can be closed and marked as completed. Also, the UAT itself can be closed
