### ISSUE TITLE
[FE] Update UI for System Generated Notifications

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44906]
## Wireframes
TBD

## Tasks
- [ ] [FE] Update all system-generated notifications based on the wireframes
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
