### ISSUE TITLE
Design | Personal Info | Product Outline Design Documentation 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44917]
## Background

We need to audit, update and/or create design documentation for Personal information. Good examples can be found within Direct deposit or Contact info features which have recently been updated.

## Tasks
- [x] Update and/or create use cases for this feature
- [x] Create user flows
- [ ] Create/update screen mocks and text

## Acceptance Criteria
- [ ] Post to appropriate sections of GitHub and sketch
- [ ] Check that links from product outline are up to date

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss -- the [Personal info documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information) has been updated to follow Liz's new structure (also synced with her for a review as well). The user flow is included in the design section. 

Let me know your thoughts on any further changes that might be needed!

**Comment by Samara-Strauss** [comment]
### [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/use-cases#readme)

- In terms of validation, I think we should have a section on what happens if there is an error when saving.

Are there other notable errors we should be showing?

### [User needs to add or update personal information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/add-edit-personal-info.md)

- I made a a few updates here for clarity.

**Comment by Samara-Strauss** [comment]
> So far we haven't documented those in other sections, but I can certainly add it if it's helpful to have that represented.

Ah, interesting! I thought we had. Can you add them here? It can't hurt to have it.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss! So actually the error that appears when the update fails is already something we include in the [add/edit use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/add-edit-personal-info.md/#saving-information) under "Save error: information can’t be saved," but the heading size was smaller than the others, so it was difficult to find. I completely overlooked it! I've changed that to the same heading size so it's easier to locate. 

Also realized we already have a "[removing information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/add-edit-personal-info.md/#removing-information)" section there too, so I added the related in-line alert information there as well.

**Comment by Samara-Strauss** [comment]
AH, ok, that works! Sorry I missed that. We should be good to go, then.

**Comment by cgednalske** [comment]
@Samara-Strauss awesome! No problem. I missed it too, even after working on it 😄

**Comment by cgednalske** [comment]
@SKasimow this was done a while back but not closed. Is it ok if we close it now?
