### ISSUE TITLE
Decision reviews FAQs: stakeholder approval and publishing changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44911]
## Issue Description
Now that we've gone through the decision reviews FAQs given to us by stakeholders, we need to send them back our assessment for what questions should be added to existing pages or if any new questions need to be created. 

The original work was completed in ticket #43643

Once the stakeholders have approved our changes, we need to do a final copyedit and publish the revised pages.

## Tasks
- [x] Send assessment to stakeholder (Laura)
- [x] Incorporate feedback onto Drupal pages (Laura)
- [x] OCTO-DE review (Beth)
- [x] Final copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholders that changes are live (Laura)

## Acceptance Criteria
- [x] Updates are on live pages with stakeholder approval

**Comment by laurwill** [comment]
Just noting that I sent our assessment and draft updates to the relevant Drupal pages to Autumn and Lynn, waiting to hear back.

**Comment by laurwill** [comment]
Update: We've made 2 rounds of edits to these page updates based on feedback from Autumn and Shireen. Shireen let us know that removing the FAQ page isn't an option at this time. So we'll plan to go ahead with copyedit and publishing of the related page updates, and I'll also assess how to update the FAQ page to incorporate the new questions. 

I'll post back here when we have final approval to copyedit/publish the related pages.

**Comment by laurwill** [comment]
@megzehn , Shireen approved our changes to the following pages. You can copyedit and publish when you have time next week. For your awareness, we're planning a more complete content review of these pages in the near future — these were just initial fixes related to updated content sent by stakeholders.

- Choosing a decision review: http://preview-prod.vfs.va.gov/preview?nodeId=23290
- Higher-Level Reviews: http://preview-prod.vfs.va.gov/preview?nodeId=3003
- Board Appeals: http://preview-prod.vfs.va.gov/preview?nodeId=3029
- After you request a decision review: http://preview-prod.vfs.va.gov/preview?nodeId=3008
- Manage your legacy VA appeal: http://preview-prod.vfs.va.gov/preview?nodeId=3102

Noting that we already published changes to Supplemental Claims page, since Autumn had approved and we were adding a new PACT alert. But that page is also part of this batch of updates.

@RLHecht , we'll also need to open a new ticket for updates to the FAQ page — I'll plan to post suggested approach and edits to that page next week.

**Comment by RLHecht** [comment]
These pages are now all published. @laurwill you can let the stakeholders know!

**Comment by RLHecht** [comment]
Closing out this ticket. Laura will open a new one for the other pieces to this!

**Comment by laurwill** [comment]
Reopening to capture 1 more related request from Shireen. 

@katherine-fung , could you add this link to the "More info" section on the [Claim status page](https://www.va.gov/claim-or-appeal-status/)?

[Choosing a decision review option](https://www.va.gov/resources/choosing-a-decision-review-option/)
Find out what to do if you disagree with a VA decision.

Then you can tag me to prepub/publish. Thank you!

**Comment by katherine-fung** [comment]
Hey @laurwill, this is ready for review: http://preview-prod.vfs.va.gov/preview?nodeId=711

**Comment by laurwill** [comment]
Thanks! I published and notified the stakeholder. Closing this out!
