### ISSUE TITLE
[Jenkins] Ability to manually trigger deploys in lower environments (for Vets-api, et al)

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#44913]
## Who is the devops resource on your team?
@madebydna 

## Description
I wanted to request permissions to manually trigger Jenkins deploys for certain applications (mostly `vets-api`, but perhaps also `fwdproxy` and `revproxy`). The permissions could be restricted to the lower environments only, if possible. I'm asking for this, because I will have a number of small PRs coming up, in which I will need to change a single (or small number of) settings, and would need to have that change deployed in order to test it. It might be more efficient if I could perform those deploys myself, instead of asking a member of the Infra team to do it for me. 

## Background/context 
This is in context of updating `vets-api` settings to prepare for the Lighthouse migration according to [this spreadsheet](https://docs.google.com/spreadsheets/d/111t6f4V3eCVkaKoBIxXi54_HlkPT-54qKShfRjl-iMs/)

---
## Tasks
- [x] Grant permission to trigger Jenkins deploys for vets-api in dev, staging, and sandbox
- [x] Grant permission to trigger Jenkins deploys for revproxy in dev, staging, and sandbox
- [x] Grant permission to trigger Jenkins deploys for fwdproxy in dev, staging, and sandbox
- [x] Tutorial or walkthrough on how to trigger deploys, and how to revert them if needed

## Acceptance Criteria 
- [x] In case of request approval, permissions for Jenkins deploys granted to @madebydna in lower envs
- [x] Tutorial/walkthrough of Jenkins dashboard on how to trigger and revert deploys

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@madebydna - How soon will you need this ability?

**Comment by madebydna** [comment]
I'd need this ability pretty much only in the short term, as in the next 6 weeks as our work will be wrapping up after that.

**Comment by jhouse-solvd** [comment]
@madebydna - We'll take a look at this today and follow up before the next sprint begins.

**Comment by jhouse-solvd** [comment]
@madebydna - This work is scheduled for the sprint that begins tomorrow. We'll follow up as needed to clarify requirements. We may also need leadership approval to grant the permissions that you are seeking. But, we'll work through those together. :)

**Comment by jhouse-solvd** [comment]
We weren't able to pick this up during the last sprint. But, we are picking it back up this sprint. We apologize for the delay.

**Comment by rmtolmach** [comment]
✅ Granted Andrea the following permissions on `vets-api-server-dev` and `staging`, `revproxy-dev` and `staging`, `fwdproxy-dev` and `staging`. 
![Screen Shot 2022-08-22 at 2 27 04 PM](https://user-images.githubusercontent.com/10993987/185999327-61ead51f-c384-4203-a67b-f049bd41a6f4.png)

✅ Explained how to replay last successful build (and confirmed she had those permissions).
![image](https://user-images.githubusercontent.com/10993987/186000410-66ae2ab5-fa01-4dc8-9221-68b06368b7a8.png)

✅ Set up a reminder in #vsp-operations-internal to remove access.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/10993987/186000993-334d3dfb-a2e6-4035-90d2-45609e876798.png">

**Comment by rmtolmach** [comment]
Update: the seed job overwrites the changes manually made to the configuration, so the changes do not persist. We opened https://github.com/department-of-veterans-affairs/va.gov-team/issues/46249 to fully resolve this, but we've hit some complications resolving that. So in the meantime, @madebydna, please comment in #platform-infrastructure for any deploys we can do for you.
