### ISSUE TITLE
FSR Streamlined Waiver + Wizard Design Discovery

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#44923]
## Issue Description
Design discovery to learn more about Wizard experience currently in the FSR and the changes needed/recommended going forward. 

---
## Tasks

Wizard
- [x] Learn more about what the FSR Wizard is. What is is intended to do, how it is used etc.  
- [x] Identify what improvements/changes are needed going forward. Is the primary change moving to the  one question per page format or is it more extensive? 
- [x] Sync with contact on the design system/form system team to determine how they can help with design work or define who owns wizard experience.  

Streamlined
- [x] Explore opportunities for wizard to be combined with streamlined waiver  ([Discovery Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/streamlined_waiver/discovery))
- [x] Review VHA decision tree and income calculator spreadsheet
- [x] Prepare questions for VHA SME discussion

## Acceptance Criteria
- [x] Understanding of next steps and establish GitHub issues for work that is required 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Helpful links regarding the wizard:

- [Gov.uk -Help users to check a service is suitable](https://design-system.service.gov.uk/patterns/check-a-service-is-suitable/)
- [Depreciated Wizard Pattern](https://design.va.gov/patterns/wizards#status)
- [Draft of New Pattern](https://design.va.gov/patterns/forms/sub-task)
- [A11Y issues/solutions](https://docs.google.com/document/d/12MctcX8uGg5iKEl8BedXWpsz1wSQY7ZPxW741RhHqsQ/edit?usp=sharing)
