### ISSUE TITLE
OCTO-DE review of 2 Foreign Medical Program pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44926]
## Issue Description
Now that our team has created 2 new pages for the Foreign Medical Program, we need an OCTO-DE review on the work. Once Danielle has looked at this, we will make edits, build the pages in Drupal, and send to stakeholders for approval. 

Our original work can be tracked in ticket #42044

We can update these tasks as necessary. We will create a separate ticket for final steps and publishing once we have stakeholder approval.

## Tasks
- [x] OCTO-DE review (Danielle)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Send to stakeholders (Danielle)

## Acceptance Criteria
- [x] Final content has been sent to stakeholders for approval

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ,
Here are the 2 FMP pages for your review.
FMP main page: 
[FMP.08.08.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9282429/FMP.08.08.22.docx)

FMP claims page: 
[FMP Claims.08.08.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9282432/FMP.Claims.08.08.22.docx)

Several questions called out for you and the SMEs — let us know if you'd like to chat or want us to adjust things!

**Comment by laurwill** [comment]
Hi @megzehn , here are 3 FMP pages ready for your copyedit:
- Foreign Medical Program: http://preview-prod.vfs.va.gov/preview?nodeId=50826  
- How to file an FMP claim: http://preview-prod.vfs.va.gov/preview?nodeId=49685
- Getting care through FMP: http://preview-prod.vfs.va.gov/preview?nodeId=50969 

Danielle will send these to SMEs next for review, so you can leave in drafts for now.

And a style note: We want to consistently use "service-connected **condition**" on these pages. So if you see any instances of "service-connected disability" lurking about, please change!

And @DanielleThierryUSDSVA , here are some FMP-related questions for SMEs:
- FMP registration and claim forms include an email address. Does FMP encourage Veterans to send these forms by email? (We usually don't recommend sending personal or medical information over email.)
- Is fax still a preferred way to send FMP forms?
- Is payment within 145 days the estimate for all FMP claims, or only for vaccine claims?
- Other types of VA appeals are now in the modernized "decision reviews" process, but it seems FMP has a separate appeals process. Can you confirm if "appeal" is still the right term for FMP?
- Could we provide more detail about the specific types of gender-affirming care and family planning services that FMP doesn't cover?

**Comment by megzehn** [comment]
Thanks, @laurwill!!

I copy edited these 3 pages. I'm also curious about the answer to your question about "appeal" vs "decision review." I left as appeal for now. 

Just as an FYI, I'm still confirming the correct aria label and href styling for the international numbers, so I'll revisit those in the pre-pub step when we get there.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @megzehn!

**Comment by DanielleThierryUSDSVA** [comment]
@laurwill @RLHecht This is with SMEs so if you want, we can close this issue and open another for the next steps. Thanks!

**Comment by RLHecht** [comment]
I just created a new ticket (#50748) for next steps, including opening a collab cycle ticket. Closing!
