### ISSUE TITLE
Sprint 12 Objectives

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4492]
## Sprint 12 (1/2 - 1/14)

Note: Code freeze still in effect 1/2 - 1/3.

### Time off

Sprint 12 is 9 days with the New Year's Day holiday.

### Order of priorities

**Required to meet sprint objectives**

1. Get address validation ready for QA
2. Design exploration for Profile 2.0 & Initial technical discovery questions for Profile 2.0
3. Write APO/FPO/DPO tickets for benefits and memorials teams
4. Get eBenefits to confirm removal of direct deposit

**Not required to meet sprint objectives**

Only move on to these if there's time.

1. 508/Accessibility tickets

### Address validation

To the best of our ability, this sprint's objective is to make sure all existing bugs are fixed/updates are implemented and ready for QA. **Note**: Having the feature fully ready for QA depends on VA Profile fixing some issues on their end. We can not be ready for QA without them. We'll consider the objective met here if things remain open only as a result of the VA Profile dependency.

**Necessary code fixes**

- [x] Use only candidate api for address validation api #4060
- [ ] Sometimes we get validation keys but can't force the addresses through #4278
  - **Note**: Blocked until VA Profile makes a fix.
- [x] Raise address confidence threshold from 80 to 90 #4468
- [x] Address suggestion bug #4487
- [x] Disable "update" button if no address is selected #4483
- [ ] Update for address validation where there is only one option #4632

**Enhancements**

- [x] Log "bad" addresses a veteran tries to save #4481
- [x] Show spinner when talking to address validation API #4485
- [ ] Make "edit address" text clickable in address validation alert texts #4484

**QA**

- [x] Go/No-go for QA
 - update as we get more info. Coordinate with Tze when we get more info from VA profile and we have had a chance to get this going. 
### Direct deposit

- [x] Confirm that eBenefits is removing direct deposit from the site in 1/29 release #3967
 
### APO/FPO/DPO

- [ ] Ticket creation for application updates #4374

### Profile 2.0

- [x] Tressa to complete onboarding to the project [#4393](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4393)
- [x] Profile 2.0: Initial design explorations #4469
- [x] Answer initial technical discovery questions #2455

### Monitoring, maintenance, bug fixes, hardening, 508, etc.

(Only move onto this work if all FE work is done for APO/FPO/DPO and address validation)

- [x] [KEYBOARD]: Text Appointments - Focus must return to Edit button when modal dialog is closed #2427
- [ ] [SCREENREADER]: Text Appointments - Focus must be managed when users press Delete in the modal dialog #2430
- [ ] [ZOOM]: Text Appointments - Need a space between input and label in modal window #2435
