### ISSUE TITLE
List Loop Discovery

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#44922]
## Issue Description
Design Discovery for List Loop Enhancements. 

---
## Tasks
- [x] Watch Recording of Riley showing UX Prototype  
- [ ] Review UX Improves to understand what changes are we making
- [ ] Review [Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/readout.md#are-veterans-able-to-easily-use-the-new-list-loop-component) that describes why these changes are important and why original List loop implementation wasn’t successful  [Example: User Research showed confusion, Accessibility Issues, etc.]

## Acceptance Criteria
- [ ] General understanding of the list loop changes planned for the FSR experience. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
I looked through my notes and here are some bullets I have regarding why the initial version of the list loops proved to be unsuccessful: 


- Veterans thought they could only choose from the options that are presented
- Veteran’s did not realize they could type a free form
- From an accessibility perspective the list loop was not accessible. 

Hope it's helpful. I will add more if I find other comments.

**Comment by denisecoveyduc** [comment]
Shifted tasks to #29976 and will complete the work as part of this discovery
