### ISSUE TITLE
Gather workflow logs for each failure and parse errors

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44939]
## Issue Description
Once we've strategized an approach to getting the workflow logs ( #44936 ), we want to implement this strategy. Fetch the logs, store them, and implement parsing based on a set of rules, starting with parsing all errors in the logs and storing the errors.

---
## Tasks
- [ ] Implement planned automation of fetching logs.
- [ ] Automate storing of fetched logs into BigQuery
- [ ] Develop script that parses out error messages from the logs. Make the ruleset flexible enough to be added to or changed over time without breaking the script.
- [ ] Automate the running of the script and storage of those error messages in their own table. This may require additional GitHub Actions workflows/jobs/steps.

## Acceptance Criteria
- [ ] Logs are fetched and stored from GitHub CI workflows.
- [ ] Logs are stored in BigQuery
- [ ] Error messages are parsed from logs and stored in BigQuery
- [ ] The script runs in an automated fashion and captures every workflow.

**Comment by rjohnson2011** [comment]
In the process of writing a script to parse error logs in Javascript that will be plugged into CI via Curt's work. Expected return will be the test step where the error takes place, the error, and the filename.

**Comment by rjohnson2011** [comment]
Pushed a branch with the initial parsing work, planning on hooking up with CI.

**Comment by rjohnson2011** [comment]
Took a look at the CI workflow of downloading and importing logs. Recognized an omission in the request for `octokit.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/logs'`. According to the docs, this response should include a `location` with a URL that redirects to a downloadable zip of the logs. Instead, only an `arrayBuffer` of data is returned, which according to all team attempts is not usable. When I made the same request back in July, I specifically remember the URL being returned.
I opened a support request with the Github Actions team about why the URL is not present in the response.

**Comment by pjhill** [comment]
@rjohnson2011 -- Thanks for these updates. Before we start to implement the solution, please update the research ticket with your exploration of the relevant GHA API endpoints and attempts to retrieve and parse logs. Once we have a design for the automated system in place, we can resume this ticket with a more fleshed out set of implementation details.

**Comment by rjohnson2011** [comment]
Extended the parseLogs to retrieve the latest workflow failure through a BigQuery query. After this, hand off the `run_id` from the JavaScript environment into the bash environment in GHA to run the CLI command. 

Noticed an issue with the Github Actions workflow table so going to resolve that before continuing work on the parse logs.

**Comment by rjohnson2011** [comment]
Created BigQuery schema & table yesterday with the table `github_workflow_errors`. Created a new BigQuery function to upload data to the new table. Successfully got a demo of hardcoded entries to update a row on the table from the parseLogs function.

Working on passing the run_id, error name, error message, and error path today. Also spoke with Curt regarding a refactor to trigger the workflow on every run of E2E test failures rather than a daily cron job. Will be making that refactor.

**Comment by rjohnson2011** [comment]
Working on refining the parse error logs for when multiple errors are present on the same log. Previous logs only had 1 error, so extending the function to find and parse for multiple failures on the same log.

After this is complete, will deprecate the cron job invocations in favor of an on E2E tests workflow trigger which checks for failures.

**Comment by rjohnson2011** [comment]
Revised the parseLogs function to iterate over multiple errors on the same page. Added additional functionality to remove duplicates from being pushed in the logs. Need to make one more modification to show the error category in the error message (i.e. AssertionError). After this working on the E2E workflow trigger and testing.

**Comment by rjohnson2011** [comment]
Extended the parseLogs function to iterate over all errors in any given logs report and upload each to BQ. Currently testing this out of various E2E run failures. Chatted with Curt about using the workflow_run approach to invoke on CI and may start with my initial daily CRON approach since workflow_run would involve using the `vets_website` repo and involves a PR through Release Tools.

**Comment by rjohnson2011** [comment]
Was able to successfully query the run_id of E2E failures from BQ and pass the ID to the GH CLI tool to download the logs then run the parseLogs functions. Now working on testing the parseLogs function through various failures over the last 30 days and making sure results upload to a BQ table successfully.

**Comment by rjohnson2011** [comment]
Extending some additional build error categorizations for error logs in the past 30 days and uploading them to BQ. Refactoring code to prepare for a PR.

**Comment by rjohnson2011** [comment]
Added additional error handling and ran against the last 20 errors. These errors are up on the `github_workflow_errors` table in BigQuery:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/72466113/188655941-4668fe84-da5f-4629-bc6e-4e1af4004ed1.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/72466113/188656016-0c135012-266e-4c5e-9bd8-d11c1bb7571c.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/72466113/188656083-d707c9ae-ea54-4e70-ad76-dd378f57f4ad.png">

**Comment by rjohnson2011** [comment]
Working on creating a PR, in the meantime did some additional refactors to the frequency of the CRON job and passing the run id.
