### ISSUE TITLE
Research retrieval and parsing of workflow logs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44936]
## Issue Description
We need to come up with a good way to retrieve, store, and parse the logs for GitHub actions workflows. As GitHub does not store error messages on the workflow object, we'll need to be able to parse out error messages for visualization purposes.

Docs for retrieving logs are located here: https://docs.github.com/en/rest/actions/workflow-runs#download-workflow-run-attempt-logs

---
## Tasks
- [ ] Figure out the best way to automate retrieving the logs
- [ ] Determine the best way to store these logs in BigQuery. Ideally, we'd store the entire logs in case we need to reference historical runs.
- [ ] Determine how to create a script that can parse based on a ruleset of what we're looking for. These should be uploaded to a separate table in BQ, for each type of data we're looking for.

## Acceptance Criteria
- [ ] We have a clear strategy where logs are being retrieved from GitHub automatically for every workflow.
- [ ] We have a clear strategy where logs are being stored in our data warehouse.
- [ ] We have a clear strategy where logs are able to be parsed by a potentially ever-changing ruleset.

**Comment by pjhill** [comment]
@rjohnson2011 -- is investigating why the GHA endpoints are not returning a link to an archive containing the logs.

**Comment by pjhill** [comment]
@cbonade -- please add context for prior work and investigation into retrieving and decoding the logs.

**Comment by CBonade** [comment]
The main guidance GitHub gives for retrieving logs focuses on jobs. However, retrieving logs one at a time in each job would require repetitive code that is not ideal for what we are trying to do. The same endpoint is available to retrieve logs as an entire workflow:

```/repos/OWNER/REPO/actions/workflow/run_id/logs```

This endpoint returned an Array Buffer containing all the data encoded in Bytes. None of the normal decoding methods for Bytes worked here as it either just reproduced the same bytes, or when it did "decode" it, it was little bits of readable text mixed in a whole bunch of random characters that were not readable. No actual log was to be found in this mess and I could not figure out a way to make it readable. When I came up short, I paired separately with both Holden and Peter, but they additionally were not able to figure it out.

In further research I came across another possibility and spoke with Peter about the possibility of foregoing storing the whole logs in favor only retrieving the error messages. I found this endpoint here:

```gh run view --job job-id --log-failed```

Per their documentation, this would return a log of only steps involved in any failure. I passed this along to Ryan as he was taking over from here as I moved on to another task.

**Comment by rjohnson2011** [comment]
In the process of evaluating the new GH endpoint mentioned above by Curt and attempting to retrieve and parse logs.

**Comment by rjohnson2011** [comment]
Was successfully able to view the logs using the alternative Github CLI command through Github Actions. Proceeded add additional steps to GHA to download the logs to a file, then import those logs using the Javascript `parseLogs` file. 
Working on refining the parsing script to successfully parse the error message and upload the errors to BigQuery.

**Comment by rjohnson2011** [comment]
Continued work on parsing mechanism to refine the starting index of the error logs that needed to be pulled, altering the amount of data that is sliced, then removing unnecessary logging information using regex methods. Now the parseLogs is successfully pulling the error message from the GHA workflow, see 
`run src/github` in the following workflow: https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/runs/7981164362?check_suite_focus=true
```
Error Step:  1) Check In Experience -- Run Cypress tests Confirmation display -- Run Cypress tests refreshes appointment data when pressing the browser back button: Run Cypress tests  Assertion
Error msg:  Timed out retrying after 4000ms: expected 0 to equal 1 Run Cypress tests at Context.eval 
Error path http://localhost:3001/__cypress/tests?p=src/applications/check-in/day-of/tests/e2e/confirmation-display/confirmation
```

Today I will be working on adding an additional step to make a call to find erroring workflows, grabbing that run ID, then running the CLI call on that specific run.

**Comment by rjohnson2011** [comment]
As the blocker of the API call is resolved by the Github CLI, the research phase is complete.
