### ISSUE TITLE
Generate Rails engine for debts API

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44938]
## Issue Description
As part of the refactor to separate out our debt services we will add our code to a engine/module microservice approach. This will allow for us to isolate our code a little better and also associate code ownership

---
## Tasks
- [ ] Run generator to add new engine
- [ ] Add boilerplate for our debt endpoints

## Acceptance Criteria
- [ ] We have a rails engine that we can add to for debts endpoints
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
ZenHub duplicate
