### ISSUE TITLE
[Parameter Store] Transmit and store keys for the My Education Benefits app (in production)

### ISSUE THREAD

**Issue by wchoiva** [department-of-veterans-affairs/va.gov-team#44931]
## Who is the devops resource on your team?
@bradbergeron-us 

## Description
The new My Education Benefits app will need to communicate with the Digital GI Bill (DGIB) services developed by AFS. These services are hosted outside VA.gov and will use JWT tokens to grant access to the Vets-API services that connect to them.

## Background/context 
This was already done for non-prod environments (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/31317). 
Key was transmitted to @mydesignrocks from wonchoi on prior request via keybase but can be retransmitted if needed. Please let us know.

## Technical notes
prod-va.crt and prod-va.key are referenced in 

- ansible/deployment/config/vets-api-worker-vagov-prod.yml 
- ansible/deployment/config/vets-api-server-vagov-prod.yml

```
  - dest: /srv/vets-api/secret/dgi-prod.key
    content: "{{ lookup('aws_ssm_custom', '/dsva-vagov/vets-api/prod/dgi/dgi-prod') }}"
  - dest: /srv/vets-api/secret/production/dgi-prod.crt
    src: ../deployment/config/vets-api/vbms/dgi-prod.crt
```

---
## Tasks
- [x] Make a path in parameter store
- [x] Get the keys from them ie (Transmit keys via Keybase) / Use previously provided keys (prod-va.crt and prod-va.key)
- [x] Verify that Vets-API can use the keys in prod

## Acceptance Criteria 
- [ ] The My Education Benefits API on vets-API must have access to the uploaded JWT keys to generate JWT tokens that will allow communication with the DGIB third-party services in production

**Comment by ph-One** [comment]
Please have @bradbergeron-us (the listed devops resource) create a pull request for these changes in the devops repository. They will need to create a new ssm parameter store entry. Examples can be found from existing parameters, e.g., https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-dev/ssm_parameters.tf#L26

**Comment by jbritt1** [comment]
Closing, this is taken care of for this particular request. There is an ongoing conversation however about how the team can get a person or some personnel on their team AWS access so they can self-service the management of secrets better https://dsva.slack.com/archives/CBU0KDSB1/p1658870650803659
