### ISSUE TITLE
FE | Profile | Contact Info | Front-end Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#44935]
## Background

Review of Contact Info product section in GitHub and add/update relevant FE documentation.
Linke [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information)

## Tasks
- [x] Add analytics documentation on what events we are firing and where in the code they come from.
- [x] Document Api calls and how they are set up in the FE code
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
Frontend documentation has been updated here:

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/contact_information/frontend_documentation.md

I'm not sure it is exactly 'sensitive' in nature, but wanted to colocate it with the backend docs. Closing
