### ISSUE TITLE
Separate VHA FSR submissions per station

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44944]
## Issue Description
VHA wants to receive separate FSR requests per station/facility to better isolate, we need to take into account the selected debts/statements to do this.

---
## Tasks
- [x] Assure we have access to the selected debts
- [ ] Create multiple requests per station

## Acceptance Criteria
- [ ] We send a single request per station selected 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
