### ISSUE TITLE
Refactor the FSR endpoints and logic to be moved into the debts API module

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44949]
## Issue Description
Once we have a debts api module available to add code we have ownership over it makes to start this refactor with the FSR endpoints.

---
## Tasks
- [ ] Create FSR services 
- [ ] Add FSR controllers
- [ ] Update business logic

## Acceptance Criteria
- [ ] We have exposed FSR endpoints within the debts api module
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over to S87 due to other tickets taking precedent

**Comment by ScottyRJames** [comment]
Rolling over due to priority of [#49993](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49993)

**Comment by denisecoveyduc** [comment]
This is being pushed based as VBMS Audit (#49993) and contract documentation has been prioritized

**Comment by kjsuarez** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/12560
