### ISSUE TITLE
Display CI Errors in Domo

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#44946]
## Issue Description
We have collected all of our errors and stored them in BQ. Next, visual representation of the errors should be loaded into Domo.

---
## Tasks
- [ ] Visually represent CI error categories in Domo.
- [ ] Visually represent CI error messages in Domo.
- [ ] Visually represent a breakdown of all infrastructure-related errors in Domo.

## Acceptance Criteria
- [ ] We can easily see all error context for our CI workflow at a glance in Domo.

**Comment by pjhill** [comment]
The visuals described here were worked on under the `Measure` ticket [here](https://app.zenhub.com/workspaces/quality-assurance-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/44563).

Closing this ticket as complete for the narrower scope now defined in 44563. We will create a new ticket for the additional effort to categorize the failures if we eventually clear that roadblock.
