### ISSUE TITLE
Add new database table for FSR submissions

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44940]
## Issue Description
We need to persist and add new fields to our 5655 FSR form for individual submissions. As of right now we only keep track of individual user submissions. This is best done using a DB table. 

---
## Tasks
- [ ] Run DB migration with new FSR schema
- [ ] Create ActiveRecord model to reference table

## Acceptance Criteria
- [ ] We are able to store FSRs in our Rails DB
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
