### ISSUE TITLE
Remove duplicate entries in style guide word list and confirm list is in alphabetical order

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#44955]
## Issue Description
A user let us know that we have duplicate entries for "suicide" in the style guide word list. There are a few other entries that are also duplicates that should be removed:
- [x] Suicide
- [x] Veterans Service Organization
- [x] Veterans Service Representative

Some of the entries are also out of alphabetical order. The list above may not be all of the entries that repeat, so we need to look through the word list and remove any others. 

## Tasks
- [x] Remove duplicate entries from word list 
- [x] Revise word list so that it is in alphabetical order

## Acceptance Criteria
- [x] Word list doesn't contain duplicate entries
- [x] Word list is in alphabetical order

**Comment by megzehn** [comment]
Incorporated these changes in this PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1617

**Comment by bethpottsVADEPO** [comment]
@megzehn I made a comment in the PR. You can merge when ready.

**Comment by megzehn** [comment]
Thanks, Beth! This PR merged, so I'll go ahead and close this one out.
