### ISSUE TITLE
[DISCOVERY] Determine best authentication approach for MCP notifications endpoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#44950]
## Issue Description
We need a way to authenticate the VBS external service to connect to the new statements endpoint. Possible options include validating via API key or using a JWT approach.

---
## Tasks
- [ ] Connect with platform and other engineers to evaluate possible authentication methods

## Acceptance Criteria
- [ ] We know how to implement authentication with VBS for the new statements endpoint 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
ZenHub duplicate
