### ISSUE TITLE
[FE] | 10-10CG | Remove feature toggle for Same Address feature

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#44954]
## Description
We utilized a feature toggle to control the rollout of the "Same Address as Veteran" feature in the Caregivers application. Now that we have rolled out the feature to 100% of users and verified usage, we can remove the toggle from the codebase.

## Tasks
- [ ] Remove feature flag `can_autofill_10_10cg_address` from the flipper toggle
- [ ] Remove check for `can_autofill_10_10cg_address` in application code

## Acceptance Criteria
- [] Feature flag has been removed from the code and the feature is open to all users
