### ISSUE TITLE
[RESEARCH] Review and determine approximate LOE for creation of remaining VISN 4 Sites [PO]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4495]
## User Story or Problem Statement
As a Product Owner, I need to know the approximate level of effort needed, so I can apply the approapiate resources and time in completing the stories needed to complete the product at hand. 

## Goal
_Complete a LOE analysis and spread sheet to determine resources and resource types required to complete the Product in the alotted timeline_

## Objectives or Key Results this is meant to further
- _Full product creation_
- _Document resources and resource types_

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Spreadsheet with Resource types and estimated LOE
- [x] Number of milestones and estimated LOE for each
- [x] Velocity required to complete all milestones listed
- [x] Summary and spread sheet submitted to Program Manager for review with customer

## Acceptance Criteria
_Complete written content meeting playbook criteria for the following Health Services:_
* Spreadsheet with Resource types and estimated LOE
* Number of milestones and estimated LOE for each
* Velocity required to complete all milestones listed
* Summary and spread sheet submitted to Program Manager for review with customer
