### ISSUE TITLE
Deprecate Loki

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#44968]
## Description
The [Datadog log pilot](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/42770) was successful. A decision should be made to remove loki due to the issues it causes with:
- suspected added latency to vets-api
- required resources to maintain loki from an aws and personnel perspective
- Loki has short comings which datadog solves for, such as querying over large sets of data quickly

## Tasks
- [ ] Obtain buy-in from OCTODE to move VFS teams into Datadog

## Acceptance Criteria
- [ ] Move VFS teams into datadog OR back into cloudwatch
- [ ] Inform VFS teams of decision
- [ ] Assist VFS teams with transition
- [ ] Remove Loki infrastructure
- [ ] Maintain loki related log backups for the required retention, ensure logs can be retrieved if ever needed - TEST and confirm

**Comment by andreahewitt-odd** [comment]
Closing because the work is captured here: https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/issues/department-of-veterans-affairs/va.gov-team/50379
