### ISSUE TITLE
[GTM Implementation Support] Education - How to Apply Wizard Tracking

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#4497]
# Analytics Implementation or QA Request

## Description
As an education benefits SME, I want to be able to understand how users are engaging with form wizards -- specifically here the [how to apply wizard. ](https://staging.va.gov/education/how-to-apply/)

## Resources + Notes
- Latest InvisionApp here: https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens
- Launch Date: March 13, 2020

## Acceptance Criteria
- [ ] Verify toggling of the radio buttons found within the first question "_Are you applying for a new benefit or updating your current education benefits?_" fires a DL push and event tag with each change
- [ ] Verify answers to other radio buttons for subsequent questions are tracked on form completion (_form completion = Apply Now click_) 
- [ ] Verify a DL push, and event tag is fired on clicks on links contained within the STEM Scholarship instructions when shown
- [ ] Verify ```null``` is passed into dataLayer variables for questions that are not answered 
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@nedierecel Let's connect on these items

At a high level, here's what I'm thinking for requirements: 
- I don't think it's worth it at this time to retroactively re-purpose CDs 46-49 for this functionality, mainly for simplicity. 
- Would like to get your thoughts on the DL variable naming convention I have below
- Setup each question as it's own CD predominantly with answers Yes or No (converted within GTM)
- Given Amy's notes [here](https://dsva.slack.com/archives/GRWB92H7X/p1578495583006600), it sounds like we will also want to identify stem applicants and Learn More modals. 

### Fired when the user click 'Apply Now' or is given the 'you're not eligible' message
```javascript
dataLayer.push({
   'event': 'edu-eligibility-wizard-apply-now', //or edu-eligibility-wizard-not-eligible 
   'edu-applyingForNewBenefits': //true, false, extend with scholarship
   'edu-claimingForSelf': //true or false
   'edu-vetTecCourses': //true or false
   'edu-transferedBySponsor': //true, false, no with scholarship
   'edu-sponsorUnavailable': //true, false
   'edu-sponsorTransferredBenefits': //true, false
   'edu-callToServiceBenefit': //true or false
   'edu-stemScholarshipApplicant': //true or false
});
```

| Custom Dimension  | DL value |
| ------------- | ------------- |
| Education Wizard - New Benefits Application  | edu-applyingForNewBenefits  |
| Education Wizard - Claiming Benefits for Oneself | edu-claimingForSelf |
| Education Wizard - Applying For Vet Tec Courses | edu-vetTecCourses |
| Education Wizard - Benefits Transferred By Sponsor | edu-transferedBySponsor |
| Education Wizard - Sponsor Unavailable | edu-sponsorUnavailable |
| Education Wizard - Call to Service Benefit Claim | edu-callToServiceBenefit |
| Education Wizard - STEM Scholarship Applicant | edu-stemScholarshipApplicant |

**For the Learn More modals, here's what I suggest:** 
```javascript
dataLayer.push({
   'event': 'edu-learn-more', 
   'edu-modal-displayed': //header of modal
});
```

**Comment by nedierecel** [comment]
@jonwehausen Thanks for sending and confirming receipt. 

That makes sense we can't apply retroactively. Wonder if any of these new CDs can be used moving forward as global ones (e.g. claimingForSelf) in other product areas. It might be interesting to run this across the platform tools teams to see if they know of any global form questions that are commonly asked. 

For the Learn More modal, do you want to insert a sample value, or are you scraping this?

**Comment by jonwehausen** [comment]
Hi @nedierecel , 

Thanks for our talk today. I have updated my earlier comment with our latest requirement needs. 

@amyknox Would you mind giving my [above comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4497#issuecomment-572172085) a look to confirm? 

**Additional question** -- we were planning on re-using custom dimension "Education - STEM Scholarship Applicant" to correspond with when the user is applying with the STEM Scholarship. Would this correspond with the selection of the third option in the first question? Want to make sure we are accounting for any plans to modify / add questions. 
![image](https://user-images.githubusercontent.com/48527022/72092878-3ebfa980-32e1-11ea-80f8-73b0c02dfd5c.png)

Feel free to notate any additional questions not yet covered above as well.

**Comment by amyknox** [comment]
@jonwehausen 
One thing that we discussed that I don't see specifically called out is that we're planning on a couple clarifying questions for the STEM scholarship to help applicants gauge if they're actually eligible to apply.  We had talked about tracking whether they start down that path then back out. I don't know enough about GA to know if what you've proposed above makes that possible. If so, great. If not, can we add it? 

At this point, we're still planning on having the 3rd question be the STEM one, but it won't be the one that triggers the appearance of the Apply Now button.  That'd be a subsequent question in the flow.

**Comment by jonwehausen** [comment]
Hi @amyknox, 

Thanks for your note here. Yes let's get that updated above. 

At this time, could you provide a context of what those additional questions will ask and we will update the above specifications to reflect?

Thanks

**Comment by amyknox** [comment]
@jonwehausen - want to be sure you're aware we're still in discovery WRT the additional questions. Topics they may cover are listed below but the # and sepcific text of the questions are conceptual 

Additional Wizard Questions re: STEM Scholarship
- field of study
- exhaution of benefits
- benefit program

**Comment by jonwehausen** [comment]
Hi @amyknox , 

Understood - thanks for the notice and the context. 

I've went ahead and updated the above comment with dataLayer variables for those 3 questions. 

Can you confirm if these too will be yes/no answers?

**Comment by amyknox** [comment]
@jonwehausen - the questions we end up deploying will _probably_ be yes/no.  We will have a much better idea by the end of next week

**Comment by jonwehausen** [comment]
Hi @amyknox,

Wanted to touchbase here - has there been more discussion on refining the additional questions verbiage discussed prior? 

Thanks,
Jon Wehausen

**Comment by amyknox** [comment]
@jonwehausen - we are in the process of re-testing the education routing wizard and application early this week.  Final content for the wizard will come out of this effort.

**Comment by amyknox** [comment]
@jonwehausen - This is where we landed with the Wizard.  

The 3 options on the first question of the wizard aren't going to change.  The language on #3 may change a little but the intent and all routing will be the same.  That is... 
1) Apply for a new benefit
2) Update current benefits
3) [apply to extend benefits with] STEM scholarship.

If the user selects option #3, they'll see conditional content with a question: Based on the eligibility requirements above, do you still want to apply for this scholarship?   Y/N

**If yes,** they're directed to the 22-1995 form.
**If no** they see: Learn what other education benefits you may be eligible for on the [GI Bill eligibility page](https://www.va.gov/education/eligibility/). 

We'll want to track those people who first say yes then change their mind after seeing the eligibility criteria.
Here's the screen in the testing prototype showing that view:  
https://bahdigital.invisionapp.com/share/CHIACQ9ZB75#/screens/296030122

**Comment by jonwehausen** [comment]
Hi @amyknox,

Nedie and I were able to confirm the Developer Requirements above in the comments section. 

When your team is ready to begin the DL portion, the requirements are ready to go. 

Thanks,
Jon Wehausen

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11760

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-28 at 11.09.16 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c940b942-7a9a-4685-b186-ef59dfb4b71f)
![Screen Shot 2020-02-28 at 11.11.16 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8077a38c-f867-4666-9a8b-fb7f1996f00e)
![Screen Shot 2020-02-28 at 11.11.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8b04d3ce-d99a-4d5e-9632-0487b90e9300)
![Screen Shot 2020-02-28 at 11.13.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e7e7f8d3-cbc3-48b5-b9bf-362d250050ac)
![Screen Shot 2020-02-28 at 11.15.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cfb8e148-2a8b-4f14-ba69-6a2ab40ca878)
![Screen Shot 2020-02-28 at 11.15.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/92268b8c-e15d-4608-ae52-db31f77244a0)
![Screen Shot 2020-02-28 at 11.19.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/40747701-db29-400f-94ba-eda7c0937e79)
![Screen Shot 2020-02-28 at 11.19.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/94d63efd-7683-4e85-90f0-de2dc085488b)
![Screen Shot 2020-02-28 at 11.20.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/58b44b60-aaed-463c-9a4f-d28bef4f3156)
![Screen Shot 2020-02-28 at 11.20.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/280ebddb-fde7-49b2-9a58-710d7306b69e)
![Screen Shot 2020-02-28 at 11.24.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/78bc76a8-a6b8-49e0-b5f2-d09872b41bfa)

**Comment by sonntag-adam** [comment]
@jonwehausen, @nedierecel, @amyknox

**Comment by jonwehausen** [comment]
Thank you @sonntag-adam for your work & documentation here! It's very much appreciated. 

We will verify the DL as well as in-tandem with the QA testing of our tag management solution.   

Stay tuned for another follow-up with our QA results.

**Comment by jonwehausen** [comment]
Hi @sonntag-adam,

At first look, we have a couple tweaks: 
- If we could modify the event push on the "_Are you applying for a new benefit..._" first radio button to be the following (_notice the DL variable name and order change -- this has been updated in the requirements post as well_) : 
```javascript
dataLayer.push({
  'event': 'edu-howToApply-formChange', //remain consistent for all toggling
  'edu-form-field': 'benefitUpdate', //remain consistent for all toggling
  'edu-form-value': 'new' //dynamically populate according to selection -- other examples are 'Update', or 'STEM Scholarship'
});
```
- In addition, if we could modify the taxonomy on the instruction links to be (_also updated in requirements above_) : 
```javascript
dataLayer.push({
   'event': 'edu-navigation', 
   'edu-action': 'check-remaining-benefits' //or 'stem-scholarship', 'see-approved-stem-programs'
});
```
Appreciate you making these corrections -- apologies for not including in original. 

Thanks,
Jon Wehausen

**Comment by elder-joseph** [comment]
Hey @jonwehausen , thanks for the feedback here. I'll go ahead and make these changes.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-03 at 11.05.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a3d21aff-9e57-46e9-a7d5-2e6428f3cfe6)
##
![Screen Shot 2020-03-03 at 11.00.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a3ae5d1e-4252-43f9-a91e-b5bf7b56558c)

**Comment by sonntag-adam** [comment]
@jonwehausen, @nedierecel, @amyknox

**Comment by jonwehausen** [comment]
Hi @sonntag-adam,

Thanks for making these corrections! 

@nedierecel and I would like to now verify within staging alongside our tag management implementation when your team is ready to push. 

Thanks,
Jon Wehausen

**Comment by sonntag-adam** [comment]
@nedierecel, @amyknox, @jonwehausen. This has been merged into staging.

**Comment by jonwehausen** [comment]
Thanks for the notice @sonntag-adam! Will be QAing today.

**Comment by jonwehausen** [comment]
## QA Testing - 3/10/2020

#### ✔️ Custom Dimension Mapping
- Verifies the custom dimension index values within GTM match GA custom dimension index values
![image](https://user-images.githubusercontent.com/48527022/76352963-510c9280-62e6-11ea-8599-bb1c436981e8.png)


#### ✔️ First Question Radio Button Toggle
- Verifies on-click the appropriate Event Action and Event Label 
![image](https://user-images.githubusercontent.com/48527022/76353095-84e7b800-62e6-11ea-9a80-af052d2688ab.png)

#### ✔️ STEM Scholarship Link Clicks
- Verifies the appropriate Event Action and Label for each of the link clicks within the STEM scholarship instructions
![image](https://user-images.githubusercontent.com/48527022/76353793-c036b680-62e7-11ea-83b7-75904513b583.png)


### Apply Now Submission Scenarios
- All screenshots occur when 'Apply Now' has been clicked
- Lines showcase the question answers and how they map to custom dimension values
- "Unanswered" populates for those questions that are **NOT** answered at time of 'Apply now' click

![image](https://user-images.githubusercontent.com/48527022/76353633-7057ef80-62e7-11ea-8f27-37443fd46e9f.png)

![image](https://user-images.githubusercontent.com/48527022/76353652-78b02a80-62e7-11ea-9439-b2cbe4c016b7.png)

![image](https://user-images.githubusercontent.com/48527022/76353674-836abf80-62e7-11ea-9cd5-31d781c7cd56.png)

![image](https://user-images.githubusercontent.com/48527022/76353695-8fef1800-62e7-11ea-8a44-693482bf074d.png)

**Comment by jonwehausen** [comment]
@nedierecel Please see above for examples of QA

**Comment by nedierecel** [comment]
Thanks @jonwehausen - Confirming receipt and validating the CDs against your screenshots. I'll post again with thumbs up that it's good to publish.

**Comment by nedierecel** [comment]
#### STEM Navigation Links - NEEDS UPDATE

@jonwehausen For the `edu-navigation` events, can you please check the "Event Action" for all 3 links? They are coming in as "Undefined"

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/cd2b496e-1cc5-4c7c-8f60-c7ea2ede8584)

####  Toggles to Radio Button - PASSED

**New Benefit**
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b609450d-0514-4860-a125-c822d1770c16)

**Update Benefit**
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/ed716110-3022-4ce9-a18a-bd6753321526)

**STEM**
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/c3b083da-7f3a-43f2-9142-a9f2b945421f)

#### Apply Now Submissions
Custom dimension slots indicated in parentheses

**Situation 1**  

| Question | Value | Google Analytics Dimension | Passed |
| --- | --- | --- | --- |
| Applying for Benefit | New | dimension64 | Passed | 
| Claim for Self | Yes | dimension65 | Passed |
| Claim Natl. Call to Service | Yes | dimension66 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/6f23ab60-a8fe-4e17-90bc-ee1fe7a00c2a)

**Situation 2** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | New | dimension64 |Passed | 
| Claim for Self | Yes | dimension65 | Passed |
| Claim Natl. Call to Service | No | dimension66 | Passed |
| Apply for VET TEC | Yes | dimension67 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/fea0de15-94e3-4334-8096-c25d2e0761d8)

**Situation 3** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | New | dimension64 | Passed | 
| Claim for Self | Yes | dimension65 | Passed |
| Claim Natl. Call to Service | No | dimension66 | Passed |
| Apply for VET TEC | No | dimension67 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b6be94ba-af49-470f-82b1-10d5b3ffb77a)

**Situation 4** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | Update | dimension64 | Passed | 
| Transferred Benefits | No | dimension69 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/155063e4-bfd8-4cc0-bcc7-a48257d26a90)

**Situation 5** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | Update | dimension64 | Passed | 
| Transferred Benefits | Yes | dimension69 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/5272edbf-89db-4b27-b309-75e2273efca8)

**Situation 6** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | Update | dimension64 | Passed | 
| Transferred Benefits | no - with scholarship | dimension69 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/cee29e41-0c1f-4a5b-98b0-7f2047cb3569)

**Situation 7** 

| Question | Value | Google Analytics Dimension | Passed or Not |
| --- | --- | --- | --- |
| Applying for Benefit | stem-scholarship | dimension64 | Passed | 
| Want to apply for STEM | yes | dimension49 | Passed |

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/bb8199bd-7394-4f0f-aca9-54fab741c000)

**Comment by nedierecel** [comment]
@jonwehausen and @amyknox  

The remaining QA items show that the navigation elements are all correct, as well as the form submissions I outlined in earlier QA session. Changes are ready to be published in Google Tag Manager. 

#### Navigation Elements - PASSED
See the following:
1. Edith Nourse Rogers
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/4ad47f3d-1797-4915-9f92-c044bdbf7ecc)

2. Check remaining benefits:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/136ebd94-0ea7-4a4f-8a79-e37be1ca66bd)

3. See approved STEM:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/755fdd58-00a5-4add-9261-7efec768dabd)

Expected behavior - this should also generate a PDF event, as seen here:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/a7960400-9e1e-4ee2-a60a-4e14e4ac39a1)

**Comment by desireeturner** [comment]
@nedierecel can we go ahead and close this issue out now that you've confirmed everything is as expected? Thank you!

**Comment by nedierecel** [comment]
@jonwehausen I'll let @jonwehausen give thumbs up on closing when it's all published to Google Tag Manager. Thanks!

**Comment by jonwehausen** [comment]
@desireeturner @nedierecel 

Confirming this has been published!
