### ISSUE TITLE
[Platform Support / SRE] Provide a summarized list of escalations to the Platform Infrastructure team on a weekly basis

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#44976]
## Description
It would be helpful for the Platform Infrastructure team to receive a consolidated list of escalations (from #vfs-platform-support to #-temp-platform-support-tier2) that happen on a weekly basis. Then, the Platform Infrastructure team could analyze those escalations to identify...

Did the issue need to be escalated? if not, why?

- insufficient documentation
- insufficient tooling or access
- wrong team

From there, we could say "oh look, 25 issues came up about AWS that had insufficient docs and tooling"... let's focus on improving those next week/month/quarter.

## Background/context 
- [2022-03-03 Proposal for tiered support model (WIP)](https://vfs.atlassian.net/wiki/spaces/OT/pages/2108588306/2022-03-03+Proposal+for+tiered+support+model+WIP)
- [SRE / Infra] Dedicated channel for escalation of platform support issues #42337
- [2022-07-27 Feedback: Dedicated channel for escalation of platform support issues](https://vfs.atlassian.net/wiki/spaces/OT/pages/2291892307/2022-07-27+Feedback+Dedicated+channel+for+escalation+of+platform+support+issues)

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] The Platform Infrastructure team receives a weekly report in Confluence that summarizes escalations with links to the escalation in Slack

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by zachclarity** [comment]
Current List of [Escalation Related Issues ](https://vfs.atlassian.net/wiki/spaces/SRE/pages/2273706783/Operations+Escalation+Process+and+Review+June+2022)

**Comment by little-oddball** [comment]
Determined OBE
