### ISSUE TITLE
Additional Evidence Documents don't display after upload

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4498]
## User Story:
As a Back-end Engineer on the Benefits and Memorials team, I need to confirm that the additional evidence documents are being properly uploaded within the Claim Status Tool so that I can identify and fix any issues that exist.

## Original Bug Ticket
#3909

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Test upload jobs
- [x] Test S3 clean up routine
- [x] Retrieve claim details via console on staging
- [x] Meet with EVSS to verify uploads

## Acceptance Criteria:
- [x] Additional evidence on the Claim Status Tool is uploading properly

**Comment by SMLuthi** [comment]
Reposted to this ticket since the other one was closed:

@YanaRoy @AZSchneider @ricetj I wanted to give an update on this since I've been working on this all day.

First of all, I want to describe the current procedure on how documents are uploaded and how they are retrieved. All claims are retrieved from an EVSS Service (appropriately named `EVSS::ClaimsService`) and stored in a database table (per user). This is done when a user navigates to the claims page which lists all the documents. These table entries are always updated (both when navigating to the base claims page or the claim details page) since the updates are asynchronous jobs (which is why it takes a bit before anything is displayed).

Furthermore, documents are uploaded via the `EVSS::DocumentsService` which is another asynchronous job. When a veteran selects a file to upload and submits the api will first upload the file to an S3 bucket where we store it locally. The job will then be kicked off where it will retrieve the document from S3, attempt to upload it to the document service, and then, if successful, remove the file from our S3 bucket.

I have tested this entire process by hand and monitored the S3 bucket, the upload job, and what we get back from the claims call... and i've determined that the files are being uploaded correctly to EVSS but the claim data we get back from them does not include them. For example, heres claim data for a claim that i've submitted multiple files and whose upload jobs succeeded (which can be verified since the files do not exist in the S3 bucket anymore):

```
[{"appeal_possible"=>"No",
  "attention_needed"=>"No",
  "base_end_product_code"=>"400",
  "benefit_claim_type_code"=>"400PREDSCHRG",
  "claim_consolidatable"=>true,
  "claim_phase_dates"=>
   {"current_phase_back"=>false,
    "ever_phase_back"=>false,
    "phase_change_date"=>"10/08/2019"},
  "claim_status"=>"PEND",
  "claim_tracked_items"=>{},
  "consolidated_tracked_items_list"=>[],
  "date"=>"02/01/2020",
  "dbq_list"=>[],
  "decision_notification_sent"=>"No",
  "development_letter_sent"=>"No",
  "end_product_code"=>"407",
  "id"=>"600167902",
  "latest_evidence_recd_date"=>"11/29/2012",
  "new_evidence_received"=>false,
  "past_est_claim_date"=>false,
  "past_evidence_due_date"=>false,
  "past_phase_est_date"=>false,
  "program_type"=>"CPL",
  "status"=>"UNDER REVIEW",
  "status_changed"=>false,
  "status_type"=>"Compensation",
  "submitter_application_code"=>"VBMS",
  "submitter_role_code"=>"VBA",
  "vba_document_list"=>[],
  "waiver5103_submitted"=>false,
  "wwd"=>[],
  "wwr"=>[],
  "wwsnfy"=>[]}]
```

Im not familiar with all these fields or what they represent but I assume `vba_document_list` *should* contain the list of uploaded documents(?) as well as `latest_evidence_recd_date` should contain todays date since I uploaded evidence(?).

Regardless, at this point the EVSS sustainment team *must* become involved to see how they are associating and tracking this evidence on their side. Hopefully, the evidence is being submitted correctly by then but is just not being retrieved correctly so no data loss is occurring.

In any case, I will attempt to setup a meeting next week so we can correspond and hopefuly solve this quickly.

**Comment by SMLuthi** [comment]
I have met with the EVSS Sustainment team and have debugged the issue.

First of all, its been verified that the document upload process currently in place is working correctly. Veterans have not lost their uploaded files as VBMS is receiving them via EVSS.

The issue lies solely in our not being able to display the files. It turns out we are not using the correct endpoint for retrieving claim details. We are hitting `vbaClaimStatusService/getClaimDetailById` when, apparently, we should be hitting `vbaClaimStatusService/getClaimDetailWithDocsById`. The former retrieves claim details but omits all files (due to, I assume, the call taking longer as users can have A LOT of files in the system) and the latter retrieves all the information. Essentially, to make our claim service tool work correctly, we will need to update our `UpdateClaimFromRemoteJob` to take advantage of this other endpoint. This has been verified by testing on a staging account via a Vets API server box. I will include a sample response retrieved for user `vets.gov.user+100@gmail.com`

```
{"appeal_possible"=>"No",
 "attention_needed"=>"No",
 "base_end_product_code"=>"110",
 "benefit_claim_type_code"=>"110LCOMP",
 "claim_consolidatable"=>false,
 "claim_phase_dates"=>
  {"current_phase_back"=>true,
   "ever_phase_back"=>true,
   "latest_phase_type"=>"Claim Received",
   "phase_change_date"=>"01/30/2015",
   "phase_max_est_date"=>"02/02/2015",
   "phase_min_est_date"=>"01/31/2015",
   "phase_type_change_ind"=>"71"},
 "claim_tracked_items"=>
  {"never_received_from_others_list"=>[],
   "never_received_from_you_list"=>[],
   "received_from_others_list"=>[],
   "received_from_you_list"=>[],
   "still_need_from_others_list"=>[],
   "still_need_from_you_list"=>[]},
 "consolidated_tracked_items_list"=>[],
 "contention_list"=>[],
 "date"=>"01/30/2015",
 "dbq_list"=>[],
 "decision_notification_sent"=>"Yes",
 "development_letter_sent"=>"No",
 "end_product_code"=>"110",
 "id"=>"600021017",
 "jurisdiction"=>"St. Petersburg",
 "mailing_address"=>
  {"address_line1"=>"Regional Office",
   "address_line2"=>"PO Box 1437",
   "address_line3"=>"",
   "city"=>"St. Petersburg",
   "state"=>"FL",
   "zip"=>"33731"},
 "max_est_claim_date"=>"09/10/2016",
 "min_est_claim_date"=>"11/12/2015",
 "new_evidence_received"=>false,
 "past_est_claim_date"=>true,
 "past_evidence_due_date"=>false,
 "past_phase_est_date"=>false,
 "program_type"=>"CPL",
 "status"=>"PEND",
 "status_changed"=>false,
 "status_type"=>"Compensation and Pension",
 "temp_jurisdiction"=>"National Work Queue",
 "vba_document_list"=>
  [{"allow_download"=>true,
    "corporate_document_id"=>120158,
    "document_id"=>"{B1212A1D-A8C2-4F9D-9B95-37DADD334CB0}",
    "document_size"=>0,
    "document_type_code"=>"L034",
    "document_type_id"=>"45",
    "document_type_label"=>"Military Personnel Record",
    "file_name"=>"coolcoolcool.pdf",
    "mime_type"=>"application/pdf",
    "original_file_name"=>"coolcoolcool.pdf",
    "receipt_date"=>1578636000000,
    "receipt_date_formatted"=>"01/10/2020",
    "remove_me"=>false,
    "source"=>"Vets.gov",
    "submitter"=>
     {"first_name"=>"NORMAN", "last_name"=>"MILLS", "person_id"=>"600085565"},
    "upload_date"=>1578684206000,
    "veteran"=>
     {"file_number"=>"796228919",
      "first_name"=>"NORMAN",
      "last_name"=>"MILLS"}},
   {"allow_download"=>true,
    "corporate_document_id"=>104420,
    "document_id"=>"{C1F86CFD-FF88-48BF-B7C1-D3E2D4DD142F}",
    "document_size"=>0,
    "document_type_code"=>"L070",
    "document_type_id"=>"80",
    "document_type_label"=>"Photographs",
    "file_name"=>
     "115413 - EVSS_SQA_SOAPUI_803873_VbaDocumentService_documentId_Document Download_Mock Response_VAenv_Database Table Event Validation_SUCCESS.pdf",
    "mime_type"=>"application/pdf",
    "original_file_name"=>
     "115413 - EVSS_SQA_SOAPUI_803873_VbaDocumentService_documentId_Document Download_Mock Response_VAenv_Database Table Event Validation_SUCCESS.pdf",
    "receipt_date"=>1496293200000,
    "receipt_date_formatted"=>"06/01/2017",
    "remove_me"=>false,
    "source"=>"EBN",
    "submitter"=>
     {"first_name"=>"NORMAN", "last_name"=>"MILLS", "person_id"=>"600085565"},
    "upload_date"=>1496341260000,
    "veteran"=>{"file_number"=>"796228919"}},
   {"allow_download"=>true,
    "corporate_document_id"=>104419,
    "document_id"=>"{537C4673-563B-45DB-87E1-55DF845472AA}",
    "document_size"=>0,
    "document_type_code"=>"L450",
    "document_type_id"=>"450",
    "document_type_label"=>"STR - Dental - Photocopy",
    "file_name"=>"test test.pdf",
    "mime_type"=>"application/pdf",
    "original_file_name"=>"test test.pdf",
    "receipt_date"=>1496293200000,
    "receipt_date_formatted"=>"06/01/2017",
    "remove_me"=>false,
    "source"=>"EBN",
    "submitter"=>
     {"first_name"=>"NORMAN", "last_name"=>"MILLS", "person_id"=>"600085565"},
    "upload_date"=>1496341258000,
    "veteran"=>{"file_number"=>"796228919"}},
...
```
