### ISSUE TITLE
[PM] My VA Redirect: Prepare for Privacy Review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#44985]
## Background
Need to prep for and complete privacy and security review

## Tasks
- [x] Gather artifacts
- [x] Submit [request](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [x] Create tasks as needed to address any follow up items

## Acceptance Criteria
- [x] Privacy and security review is complete

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ NA
- _How can this work be validated?_ NA

## Resources
- [Background info on privacy review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`vsa-authenticated-exp`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Project** (`onsite-notifications`, `My VA`, etc.)
- [ ] **Add Assignees** (who will do this work?)
- [ ] **Add effort** (or needs-grooming tag)

**Comment by ajakabcin** [comment]
Submitted [545](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/545) to the sensitive repo

**Comment by ajakabcin** [comment]
Approved from security team!
