### ISSUE TITLE
Create Comm. Plan for this initiative

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#44981]
## Issue Description
Create Comm. Plan for this initiative & consider end-to-end experience of using Playbook as 1st user

Step through the entire arc:

1) Were things where you expected as you became aware of them?
2) did you understand where you were in the arc?
3) did you accomplish your goal?
4) did it ask too much of you?

## Tasks
- [x] create your plan as intended
- [x] document any issues encountered (or correct them)

## Acceptance Criteria
- [x] Change Communication Plan for this initiative is complete
