### ISSUE TITLE
[FE] Update local mock data to match stage data

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#44999]
## Description 
In order to use the automated screen shots for product guides, we want the mock data to more closely match real data. The first step we want to make is to update the clinic data to match what is in Cardio 1 in stage. The next step will be to update the veteran data.

Veteran data is TBD. @benbrasso-agile6 to add more details on veteran data

## Tasks
- [ ] Update mock data to match Cardio 1 from stage
- [ ] Update cypress tests to reflect the new mock data
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
@benbrasso-agile6 these data updates that we met about are ready for validation. Attached are a full set of generated screenshots to review.[https://app.zenhub.com/files/133843125/26eb0f6a-79a5-400f-9b2b-ab3087613761/download](https://app.zenhub.com/files/133843125/26eb0f6a-79a5-400f-9b2b-ab3087613761/download)

**Comment by benbrasso-agile6** [comment]
Look good, Brian

**Comment by brianseek** [comment]
thanks Ben, closing ticket
