### ISSUE TITLE
Perform Live UAT for Rated Disabilities (Phase 2)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4499]
## Goal 
Prior to release, we want to make sure that the feature we created is what was intended and expected by the end user.

## Tasks
Put the feature in front of real users for them to see their own data
- Push RD to production behind a gated environment using Flipper

- [ ] Recruit users and walk them through user stories used to make the product
- [ ] Solicit feedback from that

## Acceptance Criteria
- [ ] Feedback has been obtained and a plan for implementation has been put into set
