### ISSUE TITLE
[epic] 526ez | Create a comprehensive solution for errors

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#44994]
# User Story
As a Veteran I want to have confidence that when I submit a 526 form that the VA will handle the submission correctly or let me know if they can't so that I can take further steps.

## Background
Ever since the Benefits 1 team took on the 526 form there has been a lot of failed submissions. On top of the failed submissions we have an archaic way of discovering those failures and then dealing with them that leaves us trying to influence other teams to fix systems we do not own. Furthermore when our submissions fail completely we do not notify the Veteran about it which both puts greater pressure on us to resolve the issues and does not empower to Veteran to take further action if needed.

We need to develop a comprehensive solution to these errors that accomplishes the following -

- Allows us to monitor failures with the 526 in a way that does not require special access beyond what typical engineers receive.
- If there is a failure in submitting the 526 to external systems, we need to fall back to filling out a PDF for the Veteran and sending that through central mail to the VA on the Veteran's behalf.
- If both the normal form submission fails AND the PDF submission fails we need to send an email to the Veteran alerting them of the failure with steps they can take to get the benefits they need.

## Acceptance criteria
- [x] We can now monitor the 526 submission failures in Sentry with no special access
- [x] If a 526 submission to EVSS fails we then fill out a PDF for the veteran and send it to the VA through Central Mail
- [ ] If both the form submission to EVSS and the PDF submission fail we alert the Veteran via email # We dont actually know if we want to do this
