### ISSUE TITLE
 Design | Profile | BAI | UI Updates based on research sessions

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45002]
## Background

User research for the BAI project revealed some confusion amongst users wrt steps they should take to confirm that an existing mailing address is correct.

## Tasks
- [x] Validate proposed UI changes with Accessibility
- [x] Re-locate the "confirm" instructions from the primary instructions (larger alert) and move to the smaller alert in the mailing address field within an act'l drop-down component 

## Acceptance Criteria
- [x] UI confirmed with Accessibility
- [ ] Mocks reviewed with PO and PM

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@cgednalske please review and let me know if there are any additions. Can you add points as well? Thanks!

**Comment by cgednalske** [comment]
**Accessibility feedback from DK:** no major concerns with using the additional info component (dropdown) within the alert. 

We should be good to start adding this component! @SKasimow @adamwhitlock1 

**Notes on focus:** 
- From Angela's earlier feedback: From the jump link in the main alert, focus should be placed directly on the mailing address Edit button in the read only state. (It should not automatically open the edit field.)
- Remaining questions: After selecting Edit, is helpful to then place focus on the smaller alert in the edit state to make sure screen reader users are aware of the "Review your address" instructions and additional dropdown component? Waiting to hear DK's thoughts on this.

**Comment by SKasimow** [comment]
@cgednalske - that's good news! I'll open a ticket for Adam. Can you send me the link to the updated sketch mock we should use now (I'll note content is still being determined).

**Comment by cgednalske** [comment]
@SKasimow here are the [updated mocks](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/p/B84818F9-2AB7-42E8-BFFD-0C0949B020A3/canvas)! (The **Bad address indicator high-fi mockups** in the top row)

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss -- I think this can be closed unless either of you have concerns with the UI. 

So you don't have to go through all the mockups above, here's the [additional info component added](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v8jw5bQ) + the [expanded version](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/YG309Dv) screens specifically.

**Comment by Samara-Strauss** [comment]
This looks good to me! We're good to close.
