### ISSUE TITLE
Design | BAI | Update Messaging Content 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45001]
## Background

Describe the issue background and scope

## Tasks
- [x] Consult with Content lead on revising the BAI alerts on Contact Info page to be clearer to users (per research session feedback)
- [x] Check that recommended changes are supportable for both the design system components and front-end
- [ ] Change "Review your **A**ddress" text to "Review your **a**ddress".

## Acceptance Criteria
- [ ] Review recommended language with PO and PM

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - let me know if this looks ok if if there is anything we should add to tasks/AC. thanks!

**Comment by cgednalske** [comment]
Hi @SKasimow and @Samara-Strauss! Here are the mockups for the [additional info component added](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v8jw5bQ) + the [expanded version](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/YG309Dv) with the approved content from Danielle. 

We're still confirming a few small things that I'll touch base with you on tomorrow for an official review 😃 - but we're very close!

@SKasimow fyi for the third task listed above, looks like the designs are already correct, so I think the "Review your Address" to "Review your address" change is just in the code.

**Comment by cgednalske** [comment]
@SKasimow -- content updates are completely finalized now! Here are the mockups for [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v8jw5bQ) and [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/DPaz7ry) starting at the Contact info page alerts.

**Comment by Samara-Strauss** [comment]
This looks good to me! Thank you!

**Comment by SKasimow** [comment]
Yay! Thanks @cgednalske
