### ISSUE TITLE
Remove react widget from COE page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45014]
## Issue Description
Once the online COE is launched to 100%, we need to remove the react widget on the [How to request a VA home loan COE](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) page and put the content back into Drupal. The content should match what's in the react widget when a user can access the action link. 

Content to use: [https://app.zenhub.com/files/133843125/d3771b6b-bed7-41ba-a7eb-e172eaa004b3/download](https://app.zenhub.com/files/133843125/d3771b6b-bed7-41ba-a7eb-e172eaa004b3/download)

## Tasks
- [x] Remove react widget
- [x] Add content back into Drupal
- [x] Copyedit (Megan)
- [x] Publish using the day-of checklist (ticket #45015)

## Acceptance Criteria
- [x] All content is in Drupal with no react widget on page

**Comment by RLHecht** [comment]
@megzehn this is ready for you as part of the COE launch work.

**Comment by megzehn** [comment]
Thank you, @RLHecht! I reviewed and published this page.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
