### ISSUE TITLE
Supplemental Claims | Add unit tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#45011]
## Value Statement

**_As a_** front end developer
**_We want to_** add unit tests for all the Supplemental Claims code
**_So that_** we can ensure that the code is throughly tested and meets all quality and best practice standards

## Background Context

The Supplemental Claims (SC) form (20-0995) is still in the process of being structured; but once the design and details have been finalized, while the frontend changes are being implemented, we'll need to verify that all completed code is throughly unit tested

## Tasks

- [ ] Add unit tests for all SC components
- [ ] Add unit tests for all SC utility functions
- [ ] Add unit tests for page rendering

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
