### ISSUE TITLE
Supplemental Claims | Connect frontend to API

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#45010]
## Value Statement

**_As a_** front end developer
**_We want to_** connect the frontend to the new vets-api Supplemental Claim API
**_So that_** we can get form prefill data, contestable issues and submissions to work

## Background Context

Once the Supplemental Claims (SC) form (20-0995) backend API has completed it's connection to Lighthouse's API, we need to update the frontend code to:
- pull in the form's prefill/save-in-progress data
- get contestable issues for Supplemental Claims
- transform the form data to match the expected submit schema

## Tasks

- [x] Connect prefill/save-in-progress API
- [x] Set up prefill transformer
- [x] Connect contestable issues API
- [x] Set up contestable issues filtering (remove 1 year limit, if still in place)
- [ ] Set up submit transformer
- [ ] Connect to submit API
- [ ] Add unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
