### ISSUE TITLE
Supplemental Claims | Add end-to-end tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#45012]
## Value Statement

**_As a_** front end developer
**_We want to_** add end-to-end (e2e) tests for all the Supplemental Claims pages
**_So that_** we can ensure that the code is throughly tested and meets all quality and best practice standards

## Background Context

The Supplemental Claims (SC) form (20-0995) is still in the process of being structured; but once the design and details have been finalized, while the frontend changes are being implemented, we'll need to verify that all completed code is throughly tested with e2e tests

## Tasks

- [ ] Add e2e test for SC happy-path
- [ ] Add e2e test for full SC flow & branches
- [ ] Add keyboard-only e2e test
- [ ] Add mock data for testing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
