### ISSUE TITLE
COE launch: Day-of checklist

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45015]
## Issue Description
This ticket is a checklist for what to do when the online COE tool launches to 100%. 

We need to update the landing page with content in Drupal instead of the react widget, add the entry points, and publish the new Check COE status landing page.

## Tasks
- [x] Publish landing page with react widget removed (ticket #45014)
- [x] Publish [eligibility page](https://www.va.gov/housing-assistance/home-loans/eligibility/) with react widget removed 
- [x] Publish new check COE landing page (ticket #44177)
- [x] Publish Find a form 26-1880 page
- [x] Add entry points (ticket #28677)
- [x] Review and publish eligibility page (moved NADL location in blue box)

## Acceptance Criteria
- [x] 2 landing pages are live
- [x] Entry points are showing on live site

**Comment by RLHecht** [comment]
This work is all complete. Closing ticket.
