### ISSUE TITLE
[design] Supplemental Claims | Evidence upload flow

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#45023]
## Value Statement
**_As an experience designer_**
**_I want to_** design an evidence upload flow
**_that_**  supports the likelihood of favorable decisions. 

---
## Background Context
- Supplemental Claims evidence upload walks the user through several decisions, some of which need additional form support. 

1. What type of evidence?
- VA Medical Record
- Private Medical Record (if yes, authorization via form 4142 or 4142a is needed)
- Other (form 4138 would be helpful here, but not sure we can surface it inline)

We aim to design a flow that presents a clear question and answer conversation with the user that educates and supports their decisions to upload the right type of evidence, within the parameters accepted, and clearly identified and understood to support a favorable outcome. 

## Designs and Build Notes
- The goal is to work within the form system list and loop pattern, but identify opportunities to improve and iterate. 

## Out of scope
- New form system patterns and experimentation are not intended to be in scope for this effort. However, if an opportunity arises to improve multiple forms, we may pursue it. 

## Open questions
- When introducing other forms, do we need to move to more pages to avoid really long mobile experiences. 

## Tasks
- [x] _Sketch design of baseline list and loop experience_
- [x] _Content review_
- [x] _Lighthouse collab to understand 4142 and 4138 impact_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
[Sketch file with proposed evidence upload flow](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89) can be found here. [Content ticket is in progress](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45470) to update the PDF upload language.

**Comment by thehastingsp** [comment]
This ticket can be closed as we've resolved flow issues. Tickets for [PDF upload copy here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45470) and [prototyping here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45600).
