### ISSUE TITLE
Thumbnail mapping

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4502]
## User Story:
As a __ Desigenr_______, I need ____thumbnail map____ so that I can _have a better understanding of what steps Veteran's take when ordering an item from the Medical Device tool_________.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Create thumbnail maps (low fidelity wires presented in a flow) - 40 hours per designer - Riley & Becca

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
Given: That the DLC objective is to great a User's process flow
When:   The team has a understanding of what steps are need/required to complete a order
Then:: The team can complete a thumbnail mapping exerices

## Next Steps
-wireframe

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rebeccawalsh** [comment]
The first iteration of thumbnail mapping and outcomes can be found in github here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/thumbnail-mapping/README.md
