### ISSUE TITLE
[bug] Certificate of Eligibility | VA loan number field should be a text input field

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#45026]
## Value Statement
**_As a_** user
**_I want to_** enter the correct VA loan number on my Certificate of Eligibility application
**_So that_** I can submit my application without errors that may result in an undesired outcome.

---
## Background Context

<details><summary>Issue Summary from Josh</summary>

No validation exists for the VA loan number field which can afford situations like this where a Veteran can submit a negative number. Context from @scottymeyers:

> the LGY service didn’t provide us with any validation information. It’s just “string”, “boolean”, etc. We’ve tried pressing for min/max lengths and stuff, but they didn’t provide any additional information to us.

We may be interested in seeing if there's any baseline validation we can try like preventing negative numbers. @jsokohl are you familiar with any other rules we could place here from the research you conducted?

https://user-images.githubusercontent.com/14154792/181587366-067e3c79-5940-42fb-b210-431485528ada.mov

![image](https://user-images.githubusercontent.com/14154792/181586577-fec031ad-d6a7-4fd1-ba0b-96316ebc668f.png)</details>

## Updated acceptance criteria
- [ ] Answer the following outstanding questions:
  - [ ]  What are the different ways in which Veterans identify a loan number? (e.g. Loan identification number, loan identifier, loan account number)
    - [ ]  Are these all referring to the same thing or different things? If they are different things, could we explain that difference to the user or provide validation so they don't accidentally submit the wrong number?
  - [ ] What is (if any) the standard format of a VA loan number? Has it changed over history (e.g. 8 characters to 12 characters)
    - [ ] If it has _always_ been the same standard, we should validate for those standards accordingly
    - [ ] If the VA loan number only contains numbers, use the number input field; otherwise, use the text input field
- [ ] Submission accepts both dashes and spaces

## Designs and Build Notes
- Do we need a design for the edits we discussed? 

## Tasks
- [ ] TBD

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Update AC @saderagsdale

**Comment by saderagsdale** [comment]
@joshkimux @jsokohl Is the AC appropriate for this issue? Also, do we need a design snapshot for the fix we discussed?

**Comment by joshkimux** [comment]
@saderagsdale sorry for the late reply, this looks wonderful! Some notes:

The form field type is the [number input (VA design system)](https://design.va.gov/components/form/number-input) I believe, which is desired (@jsokohl to confirm). 
- We could use the `min` and `max` attribute to trigger validation if users enter a value below 0 (or whatever is the typical range for VA loan numbers).
- We should probably also do some research on what the expected range of values are in order to write more helpful error messages when validation occurs.

I don't think we need a design snapshot, but we probably need a list of error messages. @jsokohl would love your wisdom here.

**Comment by jsokohl** [comment]
We should allow for dashes (hyphens, ok). Ideally the app will just strip those items out if not needed. I strongly suggest not putting hint text in, either -- let's let the software comply with the user, rather than the other way around.

**Comment by joshkimux** [comment]
Awesome! A couple more clarifying questions (just in case):
- is the LIN the same as the loan number we're addressing in this ticket? @jsokohl 
- I _think_ what you're saying with `let's let the software comply with the user, rather than the other way around` is that we shouldn't rely on hint text to get the user to have a perfect input on their first try; instead, we should flexibly accept dashes or no dashes. Absolutely onboard with that. I should have clarified my intent for hint text. I intended on it being used as a way to help users remember what _kind_ of number they should be looking for. e.g. something along the lines of "Your loan number will be 12 numbers and you can find it [xyz]" Is that still strongly undesired? If so, I trust your expertise here, just want to check!
- The number input accepts dashes! Do we know how SSN's are handled on VA.gov? There might be work already done similar to this before.

**Comment by jerekshoe** [comment]
So I looked, and for SSN, we accept input with or without dashes. We remove the dashes (this includes ones at the beginning of the text input) when we store the value, so the form submission won't include dashes. We can probably do something similar for VA loan number.

**Comment by jsokohl** [comment]
We should allow for dashes (hyphens, ok). Ideally the app will just strip those items out if not needed. 

Rethinking this ticket--IMO the field shouldn't be restricted to a number field with concepts of negativity or positivity. It's merely an identifier. To that end, I now think we should call this Not a Bug. I"m happy with adding the hint text if you think it's advisable, @joshkimux -- but, again, we're forcing users to comply with the implementation model, and that's generally a Bad Thing. Sometimes it's unavoidable, but especially for this field, where (as far as I've been able to determine) the loan number can vary in length, perhaps we don't need to mention the length. 

Let's do use the same approach as @jerekshoe mentioned--very cool!

**Comment by joshkimux** [comment]
@jsokohl I've updated the acceptance criteria and the name of the ticket to reflect these changes 🥳 , feel free to update the title/description to what you believe to be most appropriate.

> we're forcing users to comply with the implementation model, and that's generally a Bad Thing

I agree that focusing users to comply with an implementation model is a bad thing 💯 

To be even more specific, I was curious to get your thoughts on:
- if there are any rules related to this submission out of our control. In the same way we don't allow users to submit 8 or 10 digit social security numbers, are there any similar rules we can't control (SSN's are 9 digits) but can help guard the user from any mistakes? This bit in the earlier doc led me to (mistakenly) believe that there were rules we could account for: `The VA LIN must be numeric and 12 digits in length.` But it looks like that isn't the case `where (as far as I've been able to determine) the loan number can vary in length, perhaps we don't need to mention the length`. 
- if Veterans are quickly familiar with what their loan number is and where to find it (particularly in account for folks with long covid, cognitive disabilities, TBI, etc)

Apologize if my framing seemed like something I was advising; I meant to frame this as a question as you're our content lead 🙇

**Comment by jsokohl** [comment]
@joshkimux sorry to be late in responding. Some answers to your bullets:

- As far as I know, VA loan numbers do differ in length. I've not found alphanumeric ones, but, hey--they could exist, amirite? 
- I can say with a fair degree of certainty that Veterans have no idea where there loan number is nor where to find it. It's on a piece of paper in their basement in a box, probably. Think about the term for most VA loans as being 30-year loans. However, calling this item the VA loan number is better than a VA LIN, simply because, over the years, it's a field (and an identifier) that has changed. I reviewed my loan number (and had to descend into musty repositories) and found it to be called a Loan account number. 

Hope that helps!

**Comment by Mottie** [comment]
I found this [LGY document through a Google search](https://www.benefits.va.gov/WARMS/docs/admin26/m26_01/M261_Chapter%206%20-%20Miscellaneous%20FINAL.docx) that explicitly describes the VA loan ID number (LIN)

![The VA LIN is comprised of the following 12 digits with three hyphens to separate the four categories of the 12 digits, for example XX-XX-X-XXXXXXX](https://user-images.githubusercontent.com/136959/185145280-4536d210-2943-4d2c-a26f-df7375afd31a.png)

Note: I had to open the word document on a Windows computer to get the formatting to work right. Here is the full text

<details><summary>Full LIN details</summary>


![Overly detailed description of the VA loan ID number describing what each digit represents](https://user-images.githubusercontent.com/136959/185145918-ac3cc2ba-ff21-4148-baff-0c9eacc32fc0.png)</details>

**Comment by jsokohl** [comment]
Here's a screenshot from a WebLGY document that shows the numbers as samples:
![LIN example](https://user-images.githubusercontent.com/73672031/185149893-ff76132c-2915-4e3f-bc23-073d2b9500c8.png)

This comes from a [streamline refinance PDF](https://benefits.va.gov/HOMELOANS/documents/docs/order_irrrl.pdf).

I would suggest that we allow for numbers with or without hyphens or spaces, and that we do check for the number of numbers. If the numbers don't match the 12 digits, then we show an error message (something like "The loan number should be 12 numbers.").

I do know that my loan identifier was I think eight numbers. Maybe there's a difference between what LGY uses and what a Veteran sees? At this point, I say we go with what we know. I would suggest a change to the AC.

**Comment by Mottie** [comment]
I'm working on this now, and I was planning on changing the input into a text input and only allow numbers & dashes. There won't be any other restrictions like number of digits. Sound good?

**Comment by joshkimux** [comment]
That sounds great as an intermediary solution to me @Mottie 🥳

**Comment by joshkimux** [comment]
@jsokohl I updated the AC; hint text depends on if we're certain that the loan number is 12 numbers as it seemed like there were still outstanding questions around the consistency of the length

**Comment by jsokohl** [comment]
@joshkimux Gotcha!

**Comment by Mottie** [comment]
The fix to make the loan number field into a text input and allow dashes (but not at the beginning) and spaces has been merged. It [should be available for testing in staging soon](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/)

**Comment by joshkimux** [comment]
https://user-images.githubusercontent.com/14154792/185693958-e1f9e8a5-7e5d-487e-8d73-d64d9b5160f2.mov

@Mottie It looks like error will still be triggered when you start the field with a 1, not sure what's causing it though :(

**Comment by joshkimux** [comment]
Bumping this, [we got a response from the content team here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46233#issuecomment-1234787963)

```
We heard back from our stakeholder — he reached out to 2 SMEs, and I'm pasting their responses below. Key takeaways from my reading:

LIN and loan identifier are the same, but loan account number is different and more tied to the lender
loan numbers are always 12 digits (numbers only)
Let us know if you need more info here!

First response:
“I would say Loan Account number would be more of a reference to the lender’s loan number which is variable. It could help us track down a loan nonetheless but the term “loan identification number” or LIN or the loan identifier I would expect to mean the same thing.

VA Loan numbers always take the format: xx-xx-x-xxxxxxx the first two sets of digits are jurisdictional locators (ex: 40-40 means New Mexico) the middle digit tells us what kind of loan it is (direct, guaranteed, refunded, partial claim) and the last seven digits are the identifier.”

Second response:
“The VA loan number from VA (sometimes shortened to LIN) is in this format xx-xx-x-xxxxxxx. No letters, just numbers and is the LIN number in VA records. At a time before computers, we would sometimes see the last seven digits and the state afterwards when the number was hand written instead of the full 12 digits. (xxxxxxx NM for Heather’s New Mexico example) Also, while generally loans in the past 20 plus years have had the same two digits begin a loan number (40-40-x-xxxxxxx), some LINs previously had the same number of digits; however, when there was more than one VA office in a state (CA, TX, or NY for example) the LIN will have a different XX and XX to begin the loan number and define the office location. The state would be the first two numbers and is consistent with what is used now. I don’t remember an office code for the second set of numbers, but they are rare now as most of these loans would be paid in full.”
```

**Comment by saderagsdale** [comment]
@jsokohl @Mottie hi both. What are next steps for this? Looks like Josh got back with some feedback from content peeps.

**Comment by jsokohl** [comment]
Thanks to @joshkimux for sussing this out. 

We know that we can in effect ignore spaces and dashes. We can say, with some confidence, that all loan numbers (for this data field) are 12 numbers. My recommendation? We let them enter anything they want to. If we want to count for 12 numbers and ignore those spaces and dashes in the field, then we can give them the error message, "A loan number contains 12 numbers." That would be my recommendation.

**Comment by saderagsdale** [comment]
@jsokohl Can you ping me when you've had a chance to finalize this?

**Comment by jsokohl** [comment]
@saderagsdale Sure.

1. Add hint text after the label and before the field.
2. Hint text is "This number is 12 numbers long."
3. If the user enters more than or fewer than 12 numbers, display the message, "Please check that your VA loan number is 12 numbers long."

That's my recommendation. 
- If @joshkimux agrees, then @Mottie can enter the items.
- If @joshkimux doesn't agree, then let's go with his solution.

**Comment by joshkimux** [comment]
Looks good! Thanks so much @jsokohl and @saderagsdale 🥳

**Comment by Mottie** [comment]
Finished up work on this, it should be available in staging to test later today.

**Comment by joshkimux** [comment]
<img width="281" alt="Screen Shot 2022-09-19 at 10 58 17 AM" src="https://user-images.githubusercontent.com/14154792/191048353-5df13208-7ddc-4bea-9cc5-69ca59746b31.png">
<img width="419" alt="Screen Shot 2022-09-19 at 10 58 27 AM" src="https://user-images.githubusercontent.com/14154792/191048382-ac6156cd-5d03-4f61-976f-4cd167e90807.png">

Looks great @Mottie !! 🥳 
The only thing here that _might_ be of interest is someone could submit the same loan number twice. Highly unlikely (I hope)?

**Comment by joshkimux** [comment]
If that's out of scope for this or too specific, we can close this out; I'm not sure what the minimum level is required from a QA perspective to launch for cases like these

**Comment by saderagsdale** [comment]
@joshkimux good catch! It wasn't part of this ticket but a worthy consideration. @Mottie do you agree that this is good validation to put in place?

**Comment by Mottie** [comment]
Yeah, I think we should check that the numbers are unique.

**Comment by jsokohl** [comment]
If we do that, then we need to be clear that _one_ of the numbers might be wrong--we don't know if the first one is errant, or the second one, right? 

"**This number matches one you've already entered.**"

Something like that.

**Comment by saderagsdale** [comment]
@Mottie should we ticket this separately?

**Comment by Mottie** [comment]
naw, we can work off of this one.

**Comment by saderagsdale** [comment]
@Mottie cool beans. I think that's the last step for this before closing it. Let me know if you agree.

**Comment by Mottie** [comment]
VA loan number unique validation is now in place in staging. It will detect duplicates and will ignore dashes & spaces.

**Comment by joshkimux** [comment]
Thanks so much @Mottie , let's close this out 🥳
