### ISSUE TITLE
[BUG] Validation prevents users from submitting a loan that was closed and paid off within the same month

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#45028]
## Value Statement
**_As a_** user
**_I want to_** enter dates when my loan was opened and closed
**_So that_** I can let the VA know when my loan was closed.

---
## Background Context

<details><summary>Issue Summary from Josh</summary>

![image](https://user-images.githubusercontent.com/14154792/181587691-3e5479ed-ff31-4b7f-81c8-b9fe2e7647d9.png)

This may or may not be a bug depending on the intent. If it's impossible for a Veteran to pay off a loan within the same month, we can close this out. Would love your help here @jsokohl !

Joe confirmed this could theoretically be done through a cash payout. Thus, Joe recommended it shouldn't be an error but a warning instead e.g. "Usually the payoff date is in a different month."</details>

## Acceptance Criteria
- [ ] _Users can enter the same month and year under "closing date of your loan"._
- [ ] _When a user enters the same month and year under "closing date of your loan" they are advised on the implications of this input._

## Designs and Build Notes
- Need a design and content ticket.

## Tasks
- [ ] _Update the validation to allow for same month and year loan closure._
- [ ] _Create logic to trigger a warning message when a user enters the same month and year for loan closure._

**Comment by saderagsdale** [comment]
@saderagsdale Add AC

**Comment by saderagsdale** [comment]
@jsokohl To provide updated language and/or design.

**Comment by saderagsdale** [comment]
@saderagsdale @jsokohl needs a content ticket

**Comment by scottymeyers** [comment]
Potentially create a rule which displays a warning for same month closing & pay off:

https://design.va.gov/components/alert

**Comment by jerekshoe** [comment]
This might not be the direction that you guys go, but if you want to allow the closing date and the paid off date to be the same without an error, you can add a 4th argument of `true` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/9f9c55d8/src/applications/lgy/coe/form/config/chapters/loans/loanHistory.js#L56-L60)

**Comment by jerekshoe** [comment]
Also, not sure if this is helpful, but we use a pattern similar to the suggested one for Burials. If the deceased veterans' 'Date of burial' is more than 2 years in the past we show an alert that looks like this:
![Screen Shot 2022-08-04 at 3 09 48 PM](https://user-images.githubusercontent.com/13838621/182943364-9e1d6a20-2a53-414c-9df6-9b98a2b5bc7a.png)

The code we use to make this work with the form system is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/9f9c55d/src/applications/burials/config/form.js#L267-L280)

**Comment by jsokohl** [comment]
I'm wondering though if that's the right representation. https://design.va.gov/patterns/messaging-error-messages indicates to me that you would have a bar on the left of the message box, I think. On the other hand, https://design.va.gov/components/alert seems to enable some sort of variation (standard vs. box with icon vs. box with no icon). Also, since this message indicates you cannot proceed, it seems that it's an error, not a warning (and, thus, would be red/pink).

**Comment by jerekshoe** [comment]
This one is using the `va-alert` component from the design system (the second link you included). This warning does not prevent you from proceeding with the form, you can continue to fill it out

**Comment by jerekshoe** [comment]
My intent wasn't specifically to advocate for this specific representation, just to point out a place where we do something similar and the code we use to do it. If a better alternative is found, it might also be good to look at updating the burials form to match the new representation

**Comment by joshkimux** [comment]
@jsokohl this might be something talking about with the platform or design system team 😄 

That particular pattern actually isn't an error as it depends on if the Veteran is applying for a non-service connected allowance. It's a separate issue, but I think it was a bandaid solution to not being able to branch out the form. That being said, it would technically work in this particular instance (thanks for finding this @jerekshoe ). 

That being said, I agree there are more alternatives to explore! Might I also place on the table the additional information pattern with a question "What if my loan was paid within the same month?" which could expand out to provide more details without the need of dynamic content being added into the page?

**Comment by saderagsdale** [comment]
@jsokohl I updated the content of the ticket. This one is in queue for design and content ticket. Can you share a status on it?

**Comment by jsokohl** [comment]
I think it's a technical status--from a design standpoint, it shouldn't be an error. To @joshkimux question--that could be something later, but let's fix the technical case of the error being thrown if dateOfPayoff=dateOfClosing

**Comment by Mottie** [comment]
ixed in [#21969](https://github.com/department-of-veterans-affairs/vets-website/pull/21969)

<img width="572" alt="COE loan page showing a collapsed card with a date range of 01/2022 - 01/2022 and an open card showing February 2022 in both the closing date and paid off date form elements" src="https://user-images.githubusercontent.com/136959/185443832-410a5b87-b165-4124-be3e-3ba957679114.png">

**Comment by joshkimux** [comment]
Confirmed this has been fixed 🥳
