### ISSUE TITLE
[CDP] Consolidate pages and surface important links

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#45037]
## Issue Description
[Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-findings.md)

---
## Tasks
- [x] Review content and user flow and assess whether pages can be consolidated 
- [x] Review design and whether important statement information and a pay link can appear sooner to users

## Acceptance Criteria
- [x] _Create user workflow
- [x] _Create wireframes

**Comment by josephrlee** [comment]
Closing this out as the VBA payment history work (#86996) satisfies this ticket. 

cc: @mgleo , @denisecoveyduc , @Tom-Davis , @dhill802 , @charlottecesana
