### ISSUE TITLE
[Sentry legacy] Identify which resources need to be cleaned up to sunset this service

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45030]
## Description
In order to properly sunset Sentry legacy infrastructure, we need to identify which resources still exist. 

## Background/context 
- #16156 

---
## Tasks
- [ ] Look at the code base and understand if the Sentry resources are tied back to BRD or EKS
- [ ] Look in AWS for legacy Sentry resources to determine which ones are related to BRD and can possibly be cleaned up 
  - [ ] EC2
  - [ ] Parameter Store
  - [ ] Security groups 

## Acceptance Criteria 
- [ ] A detailed list of resources exists is attached to this issue so that we can use the list when cleaning up resources 
- [ ] Additional issues have been created to track the clean-up of resources 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
