### ISSUE TITLE
[CDP] Make 'Other VA debt' link more prominent

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#45038]
## Issue Description
[Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/usability-apr-2022/research-findings.md)

---
## Tasks
- [x] Review VA Design system, Debt, and Copay detail pages and determine whether the 'Other VA debt' link can be more prominent
- [x] On Debt detail page, link to Copay page as "Copay" rather than "Other VA Debt"

## Acceptance Criteria
- [x] Figma mockups have been updated
- [x] Production has been updated

**Comment by josephrlee** [comment]
The [VBA](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=84-18119&t=czRL7lmw6xmREZ1z-11) and [VHA](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4361-49823&t=czRL7lmw6xmREZ1z-11) summary pages have been updated based on the findings.

@denisecoveyduc, here are the changes I've made:

|         | Before | After |
| ------- | ------ | ----- |
| VBA  |  <img width="721" alt="VBA copay bills before" src="https://github.com/user-attachments/assets/b8332aef-fa73-4d24-8137-28dc24751372" /> | ![VBA Copay bills after](https://github.com/user-attachments/assets/20d62206-a4e3-4177-8b6b-789028d34ce4) |
| VHA | <img width="710" alt="VHA debt before" src="https://github.com/user-attachments/assets/514eacff-5b17-4f65-9087-6c58f664e9b1" /> | ![VHA debt after](https://github.com/user-attachments/assets/831304f9-fb73-4562-b135-69f2a944c251) | 

cc: @mgleo @charlottecesana

**Comment by denisecoveyduc** [comment]
That is much cleaner and easier to read! I love it! Great work @josephrlee
