### ISSUE TITLE
[A11y Maintenance Audit] New VA.gov Mobile Header

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#45040]
# [A11y Maintenance Audit] New VA.gov Mobile Header

## Coverage

This maintenance audit will cover:

### Unauth Header
- [x] VoiceOver, Safari, iPhone
- [x] Macbook, Chrome, Keyboard, Magnification
- [ ] ??

### Auth Header
- [ ] VoiceOver, Safari, iPhone
- [ ] Macbook, Chrome, Keyboard, Magnification
- [ ] ??

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements

**Comment by laflannery** [comment]
Closing  - this was opened for practice
