### ISSUE TITLE
Add Instructions to How to Provide Feedback guidance for removing CC-Request label

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45067]
## User Story
As a Governance team member, I want to ensure that feedback tickets do not have the `CC-Request` label so that tickets do not populate on our Collaboration Cycle Reviews ZenHub board or slack notifications.

Assignee: @CherylEvans 
Peer Reviewer: @jimuhh 

## Description
When creating feedback tickets in the Collaboration Cycle Reviews ZenHub board, it will automatically add the 'CC-Request' label. This will cause feedback tickets to display on the ZenHub board and also notify us in slack with the integrations completed in #42853. We want to add guidance to remove this label so that our board and slack only show relevant tickets.

Remove `governance-team` label as well

## Impacted Artifacts
[How to Provide Feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to Provide Feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[Collab Cycle Feedback Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md#platform-directions)

## Tasks
- [x] Add bullet under [If you have feedback](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent#After-the-meeting) to remove the `CC-Request` label (if and only if they create the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- [x] Add bullet under [If you have feedback](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review#After-the-meeting-or-asynchronous-review) to remove the `CC-Request` label (if and only if they create the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- [x] Add bullet under [Platform Directions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md#platform-directions) to remove the `CC-Request` label (if and only if they create the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- [x] Remove `governance-team` label as well

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Instructions are provided for removing the `CC-Request` label from future Feedback tickets
- [x] Reviewers are aware of the scenario that will automatically apply the `CC-Request` label

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@jimuhh Completed all tasks.  Changes should be published today.  [PR link 47989](https://github.com/department-of-veterans-affairs/va.gov-team/pull/47989)
I will squash and merge once you complete your review.  Thank you Jim!

**Comment by CherylEvans** [comment]
[PR 47989](https://github.com/department-of-veterans-affairs/va.gov-team/pull/47989) Squashed and merged.
