### ISSUE TITLE
FE | Profile | Create Feature Toggle for Payment Notification 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45061]
## Background

Feature toggle is required for the upcoming payment notification.

## Tasks
- [ ] Create feature flag in support of the upcoming payment notification
- [ ] Implement at 100% to prevent this from showing in prod [slack convo](https://dsva.slack.com/archives/C7TE0PFTL/p1659046478528999)

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@adamwhitlock1 - I'm moving this to look at for Sprint 80

**Comment by adamwhitlock1** [comment]
Here is a quick screenshot of the toggle and verifying that it is indeed turned off in staging and prod at this time.

![Screen Shot 2022-08-24 at 11.36.28 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/dded938a-3b10-4b67-a5cd-e5cb829e1ede)

**Comment by Samara-Strauss** [comment]
Thank you! Update from VA Profile is that they have created a ticket to turn this back on for us. They'll let us know once the work is done.
