### ISSUE TITLE
[Design] Notification preferences: Create confirmation email for every time someone updates their 1095B notification preference

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#45074]
### Background

We are working in partnership with the 1095B team, VANotify, and VA Profile to add a notification preference which will allow people to opt into and out of a mailed copy of their 1095B (proof of health care) tax form. If people opt out of the mailed copy of their 1095B, they are opting into downloading a copy from VA.gov. The ticket for working on the actual preference is #45073.

As part of this work, we need to send a confirmation email every time someone updates their 1095B notification preference. **There is an open question out to the 1095B team as to whether we need to send a confirmation email every time someone updates this setting, or only if people opt out of the mail option**. This ticket is to work on a draft of the confirmation email so we can get it over to the 1095B legal team ASAP for feedback.

### Tasks

- [x] Draft email for when someone updates their 1095B notification preference
- [x] Review content with Danielle or another content person
- [ ] Share with auth experience team and 1095B team for feedback
- [ ] Iterate as needed

**Comment by andaleliz** [comment]
The 1095-B stated their preference is for an email to be sent any time a change is made to this setting.

Basing this off the "contact info updated" confirmation email we send, I've drafted this.  Thoughts @Samara-Strauss ?

---

[subject]

Your IRS 1095-B tax form paperless delivery setting has changed

[email]

Your IRS 1095-B tax form paperless delivery setting has changed. We’re sending this email to confirm that your 1095-B form [will/won't] be mailed to you. You'll always be able to [download your 1095-B tax document from VA.gov] (link to download page).

If you made this update, you don’t need to take any action.

Don’t remember updating this information?

This could mean that someone is trying to access your account.

Call us right away at 800-827-1000. We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. If you have hearing loss, call TTY: 711. We can help you protect your bank account information and prevent fraud.

Go to your VA.gov profile

**Comment by Samara-Strauss** [comment]
1. Is it possible to define what they changed their setting to in the email? If you haven't already, we should validate that we could show that kind of conditional logic with VANotify.
2. Is the bit about "If you made this update...." in our other profile emails?

**Comment by andaleliz** [comment]
>Is it possible to define what they changed their setting to in the email? If you haven't already, we should validate that we could show that kind of conditional logic with VANotify.

I was attempting to do that with the `[will/won't]` portion of the email, but I'll point that out to Danielle and see if a brainstorm for a better way to make that clear.  

We use conditional logic to show what people changed for other profile emails, so I think it's possible, but I started a [Slack thread](https://dsva.slack.com/archives/C010R6AUPHT/p1660075409889399) to confirm.

>Is the bit about "If you made this update...." in our other profile emails?

Yes, I took that from the copy we use in the "contact information has been updated" email.

**Comment by Samara-Strauss** [comment]
Great, thank you!

Personally, I think the "If you made this update, you don’t need to take any action." copy could be improved. I'm not sure why each sentence is on a different line. Probably something to check with Danielle, and if we update the formatting of that part of the email, we can go back and change it in the other profile emails as well.

**Comment by andaleliz** [comment]
@Samara-Strauss when I confirmed with Melanie that VA Notify can support dynamic content, she let me know the 1095-B team has already drafted copy for both emails [in this thread](https://dsva.slack.com/archives/C010R6AUPHT/p1660076369744639?thread_ts=1660075409.889399&cid=C010R6AUPHT).  

I'm not sure how to proceed if they've already written this up. I know they have a relationship with the content team to get their work reviewed/approved. Can you please advise?

> I'm not sure why each sentence is on a different line.

If I remember correctly, it's something to do with readability and the nature of the statements. I did work on that email with Danielle, but I'll double check with her in this round of review.

**Comment by Samara-Strauss** [comment]
I'm so sorry, @andaleliz. I had no idea they already had email copy drafted. When you are back, can you check in with the 1095B team about this? It's unclear to me whether that copy has been reviewed with our content folks or not and how "done" it is. It's also unclear to me whether we actually need two emails, or whether they would be amenable to using 1 with dynamic content. Let's definitely talk to them about this.

**Comment by andaleliz** [comment]
No problem @Samara-Strauss not your fault! I know we want to avoid duplicating efforts.

I mentioned Tamara and Tracey in [this slack thread](https://dsva.slack.com/archives/C02TUH5U3HS/p1660578125170849); will post updates here.

**Comment by andaleliz** [comment]
Latest update:
- Based on what I learned in the Slack thread above, I went ahead and drafted and email, which I then reviewed with Danielle. I put the final copy in [a markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/1095B-preference/content/confirmation-email.md) since it needs to be reviewed by several people.
- I've [sent the draft to VA Notify](https://dsva.slack.com/archives/C010R6AUPHT/p1660778336072479?thread_ts=1660075409.889399&cid=C010R6AUPHT) to confirm whether or not this should be 1 or two templates.
- I think this is ready for review for the 1095B team once I get confirmation from VA Notify.

@Samara-Strauss, please let me know if you have any changes to what I have in that markdown file.  Danielle and I decided we didn't need to include that bit about "If you made this update...." for this email, since it's not really a security risk.

I also asked her about the sentences on multiple lines in the other emails.  She said the first sentence should definitely be on it's own line, but we could go ahead and combine the 2nd and 3rd sentence on one line if we felt strongly about it. I personally do not feel strongly about it, but we can update the other emails if you do.

**Comment by Samara-Strauss** [comment]
The email looks good to me, and I don't have any feedback.

Since the 1095B work is being put on hold until next year, we can close this ticket and pursue review of the email copy when we pick up this work again.

**Comment by andaleliz** [comment]
That sounds good to me. I've updated our [markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/1095B-preference/content/confirmation-email.md) w/ all the latest info I have, and included a "next step" to make it easier for us to pick up where we left off next year.
