### ISSUE TITLE
Close out ESECC Request

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#45078]
## Issue Description
The ESECC request for the four new `*platform-api.gov` domains is currently in the status "Approved for Implementation." To wrap things up, we want to make sure the request is fully closed out. In order to do that we have to identify the correct party or parties to make that change and request it to be completed. Alternatively, we might be able to close it out ourselves.

---
## Tasks
- [ ] Identify who needs to close out request
- [ ] Close ESECC request or have it closed by someone else

## Acceptance Criteria
- [ ] ESECC request is in a "closed" status
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
