### ISSUE TITLE
[Design] Notification preferences: Initial 1095B preference mockup

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#45073]
### Background

We are working in partnership with the 1095B team, VANotify, and VA Profile to add a notification preference which will allow people to opt into and out of a mailed copy of their 1095B (proof of health care) tax form. If people opt out of the mailed copy of their 1095B, they are opting into downloading a copy from VA.gov.

**Requirements**

- We must add a new preference for the 1095B to notification preferences. This preference must have two options that describe the following (this is not intended as exact copy):
  - Send me a copy of my 1095B by mail.
  - Do not mail me a copy of my 1095B. I will download a copy of it from VA.gov. I also understand I will receive an email yearly letting me know my 1095B is available.
- We must make it clear that people can change this preference any time. [Being explicit about this seems to be a requirement from the 1095B team](https://dsva.slack.com/archives/C02TUH5U3HS/p1658933063191909?thread_ts=1658931650.076399&cid=C02TUH5U3HS).
- We must make sure people have an email on file to change this preference since the digital download will have automated emails associated with it.
- Every time someone changes this preference, we need to send them a confirmation email that acknowledges they have changed this preference. **Question for the 1095B team -- do we need to only send an email if someone opts out of mail? Or any time they change this setting?** #45074 

**Other things to think about**

- Should this go in the "Your health care" group, or does it need its own group?
- We need to get this to the 1095B legal team ASAP so we can get feedback from them, so working with content as soon as we can would be great.
- Speaking of legal, there are possibly other things they will ask us to mention in the UI, but the requirements above are all we are aware of as of now.

### Tasks

- [x] Create initial mockups
- [x] Work with content
- [x] Share with auth experience team and 1095B team for feedback
- [x] Iterate as needed

**Comment by andaleliz** [comment]
@Samara-Strauss have there been any discussions around adding content about the 1095B + this new preference elsewhere on VA.gov, with a link to notification settings to update it if they don't want to have it mailed? My gut says it's not going to be intuitive for people to look for this kind of thing under "profile > notification settings" but maybe it doesn't matter if people are directed there from other places related to the form.

**Comment by Samara-Strauss** [comment]
@andaleliz yes -- there is going to be a separate page where people can download the 1095B, and it will direct them to the profile to manage their settings.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss and @SKasimow I explored some different ways to present content and want to share [this initial mock-up](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/8ydMW9Y). I think the additional info component is the best route for providing all the necessary information, and Christina's recent research shows that people do use this component to look for more info when they have questions.  I also explored using hint text ([example](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/7yjMn7p)) and the featured content components ([example](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/ygjnlGL)) before I realized people may not know what the form is. It feels like a lot to me without that content. 

Based on the meetings you've had, do you have any idea if having the required text inside an expandable component will fly?

**Comment by Samara-Strauss** [comment]
This looks like a good start to me!  

**Questions**

1. What do you plan on including in the "Learn about paperless delivery of form 1095-B" dropdown?

**Comments**

1. Unfortunately, we have very little insight from the 1095B team on what might actually be required by the legal team, so I'm hopeful the additional info component will work, but I am not sure. The only way we're going to know is if we send it to their legal team for feedback. When we do, we should also draft what we intend to show in each additional info component.
2. I think we should link to the page where people can download their 1095B form. The 1095B team should have a draft of that page if you want to see it.

**Comment by andaleliz** [comment]
Awesome, thanks for the quick feedback. Below is what I've drafted for the "learn about paperless delivery" dropdown. Danielle hasn't reviewed it yet, but I'm going to see if perhaps Christina can review it with her in office hours on Thursday to keep things moving.

>With paperless delivery, you can [download your form 1095-B from VA.gov](link). The form will not be mailed to you. We’ll send you an email every year when it’s available to download. You can update this setting anytime.

I included a link inside the dropdown; do you think it needs to be more obvious?

For the "learn about 1095-B" dropdown, I'm thinking I can use the intro copy + note [from the 1095 team's draft](https://user-images.githubusercontent.com/22205441/157481078-e45140dc-4b02-4fdc-ba38-6b179a648b78.png).

**Comment by Samara-Strauss** [comment]
Got it! OK, this copy looks good to me. IMO, I think the "Learn about paperless delivery copy" could be pulled out of the additional info component, but that is my opinion and we can validate where we should put it in testing. Otherwise, I think this is great.

**Comment by andaleliz** [comment]
@Samara-Strauss my first instinct was to pull that copy out, but then it felt like there may be a disconnect between the `<label>` and the radio `<input>` elements. Let's test it with the copy out and see what people say. I'll update the mock.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss - here's where we landed after the content review with Danielle:

- [No email on file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/JnEgDg9)
- [Email on file ](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/prototype/a/D6132FAB-A080-427A-B689-140449CF3453)(zoom in and click on additional info component to see expanded content)

Danielle recommended to put all content inside of a single additional info component, instead of 2 like I had in a previous version. 

I'm holding off on creating the desktop mock-ups until we get this approved by the 1095-B stakeholders, to minimize the amount of places any updates have to be made. Let me know if you think it's better to have them see that though and I can definitely make it.

Unfortunately, I don't think I'll be able to make the sync tomorrow to present this work (I have a dr. appt and they have no other available times tomorrow). If you're good with this, and the mobile version - should I just ping the team on Slack to have them review it?

**Comment by Samara-Strauss** [comment]
These look good to me! Great job, @andaleliz!

And yes, I think you can ping the team via Slack and let them know you won't be in today's meeting today. FWIW, I was having trouble zooming in on the "Email on File" mockup, and I'm not sure why. Is there a way to make that easier for the team to review?

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss ! I pinged the team on [this thread](https://dsva.slack.com/archives/C02TUH5U3HS/p1660659206137749) to get the review going.

Also I was able to move things around a bit and can join the call for the first 20 minutes, at least :)

**Comment by andaleliz** [comment]
The 1095B reviewed these designs and didn't have any design changes.  Their PM said in [this slack thread](https://dsva.slack.com/archives/C02TUH5U3HS/p1660765414367859?thread_ts=1660659206.137749&cid=C02TUH5U3HS):
>The next step on Opt-in designs would logically be legal review.   We usually have a business owner brief with designs to socialize and get feedback.  Since we did not see Opt-in being at this point yet and a new team is taking 1095-B.  Let me ask our VA-PO to see how she would like this to proceed.

>So, this would be the flow.   Waiting on word from our VA-PO, she coordinates with HEC for Business owner updates.   Not sure who will own business owner brief and legal (us, profile, or the new team onboarding 7 Sept).   Please stand by

Since the legal review is the next step, and covered in #45075, I'm going to close this out.

**Comment by andaleliz** [comment]
Adding links to mock-ups so we have everything in one place if we need to refer back to them:

- [User has an email on file, additional info component is closed
](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WK8xJy8)
- [User has an email on file, additional info component is open](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/ygjKLao) (this is where the required info can be found)
- [User doesn’t have an email on file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/5zZvbp/a/JnEgDg9/r/8vJ2m8)
