### ISSUE TITLE
[FE] Combine appointment data mock generation to work for both apps

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#45089]
## Description
Currently we are building mocks for appointment data in multiple places. This ticket is to combine that to be generic enough for both apps.

## Tasks
- [ ] combine appointment mock payload
- [ ] Update e2e tests to match text and creation
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
