### ISSUE TITLE
FE | Profile | Implement Custom Event for Change Address Messaging Modal

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45093]
## Background

We want to use a custom event for the "Change Address" messaging modal to have more control over tracking and the reporting view.  [Sketch file here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/EL2Kvm2)

This is what we advised Analytics we wanted to track:

> - Event: 'int-profile-custom' (or something of that nature)
> - Title: text we can pass in for title or other identifying info 
> - Status: text for status state or of data specific to event
> 

This is the guidance we received from the Analytics team (per ticket #44380)

> Below you will see the new event created for the Modal (profile_modal). 
> 
> dataLayer:
> ```
> {
>      event: 'profile_modal',
>      modal-status: '<status>',
>      modal-primaryButtonText: ‘<text>’,
>      modal-title: ‘<title>’
> }
> 
> ```
> Here are example values of how it can look: 
> modal-title: Address Update
> modal-status: Open, Closed
> modal-primaryButtonText: Yes, No
> 
> 
> How to find in reporting:
> 
> Event Category: Interaction
> Event Action: Status: {{DL - modal-status}} - Title: {{DL - modal-title}} - Click Text: {{DL - modal-primaryButtonText}}
> Event Label: profile_modal
> 

## Tasks
- [ ] Set up custom event as follows:
- Event Category: Interaction
- Event Action: Status: {{Link Click} - Title: {{Change Mailing Address}} - Click Text: {{Yes, No}}
- Event Label: profile_modal (edited)

## Acceptance Criteria
- [ ] Confirm event is firing correctly in staging
- [ ] Test with PM behind FF in production
- [ ] Add to Contact Info Product outline [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#analytics)

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
This has been deployed and can now be verified in the GA dashboard. Widget will need to be updated to filter by the new action formatting though.

**Comment by SKasimow** [comment]
Closing...widget has been updated/verified.
