### ISSUE TITLE
PM | Profile | Audit & Update Notification Preferences 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45099]
## Background
---

As part of effort to add and update to existing Profile documentation, the [Notification Preferences](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences) needs to be audited to identify any missing or outdated information.

## Tasks
---
- [x] Review existing Notification Settings feature which should include (at minimum) the following sections:<p>

*  Title
* Date last updated
* Table of contents
* Points of contact (POCs)
* Overview -- this should include details that Liz is currently housing in the "feature overview" section to minimize confusion (or we should rename one of these sections to clarify the purpose)
*  User problem statements
*  Analytics or Measuring success
    - This section should link to any relevant GA reports
    - If we are actively tracking metrics for something, we'll show that here
*  Projects
*  Backend
    - Including how to access and test the feature, error handling and codes, technical diagrams, info about the supporting backend system, any backend metrics we are tracking (eg. latency)
* Frontend
     - Includes GA events firing and where in the code they live, API calls made and how set up in FE code, mapping of error codes to alert messages for that feature
* Design and UX
     - Includes links to use case documentation, user flows, and Sketch files
---
## Acceptance Criteria
- [x] Update broken link to VA Profile in Product outline
- [x] Update LOA1 screen in staging use case
- [x] Verify staging use cases are still valid
- [x] Update the LOA1 screenshot
- [x] Update the screenshot for when user isn't enrolled in healthcare (need from Liz)
- [x] Remove outdated MVP FE documentation 
- [x] Add into various product outlines when/if an event triggers an email confirmation

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - I've updated the product outline for [Notification Settings](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences) . 

- I've also reviewed the use cases but not sure how to test with a cerner user [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#test-cases-for-notifications---feature-eligibility) ?

- Also, was this [document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences-a11y.md) done to make test cases more accessible? 

- Lastly, the mocks go to a UX Pin file and some are slightly out-of-date; will talk to Liz about replacing with Sketch file versions.

**Comment by Samara-Strauss** [comment]
I cleaned up a couple things in the outline, but otherwise looks good.

> Also, was this [document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences-a11y.md) done to make test cases more accessible?

Yes, as screen reader users can't easily navigate the tables we normally create for staging user test cases.

> Lastly, the mocks go to a UX Pin file and some are slightly out-of-date; will talk to Liz about replacing with Sketch file versions.

Great, sounds good! Thanks!
