### ISSUE TITLE
[ARGO][GHA] Create workflow to upgrade ArgoCD

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#45094]
## Description

Infrastructure team has manually been check argo repository and upgrading if there is a version different. It would be nice to have a workflow automated that will check on our behalf.

While I do believe that the manual involvement of actual upgrading should still be required, having all files modified in advance would alleviate us falling massively behind in version and potentially creating tech debt

---
## Tasks
- [x] Create Github Action workflow to upgrade argocd
  - [x] Get correct values

## Acceptance Criteria 
- [x] PR gets created with upgraded filse modified

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
