### ISSUE TITLE
[ArgoCD] GitHub Action to add projects across repos

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#45098]
## Description
As part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/44415, we should have an action that takes whatever `project` that was added in [vsp-infra-argocd/chart/values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml#L4) and adds it to [vsp-infra-application-manifests/apps/argocd-apps/<ENV>/values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/argocd-apps/dev/values.yaml)

## Background/context 
There will be many projects added and we don't want to be updating both repos manually. 

## Technical notes
* Will this run on every PR, or every push to main, or some other time?
* Do we want to the bot to commit the changes directly to `main`, or do we want the bot to open a PR for us that we review and merge manually?

---
## Tasks
- [ ] Clarify details of the Action
- [ ] Create and merge Action

## Acceptance Criteria 
- [ ] Action is merged and tested

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
My idea so far on this workflow:
```
# When:
  # on any PR made to the vsp-infra-argocd repo
# What:
  # check vsp-infra-argocd/chart/values.yaml to see if a new 'project' has been added
  # How:
    # Checkout this repo using actions/checkout@v2
    # Do some diffing on the file to get the values (project and environment). OR download the files using curl like Oseas does here: https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/.github/workflows/update-argocd-version.yml#L27
# What:
  # Inject the project name into the right spot of vsp-infra-application-manifests/apps/argocd-apps/<ENV>/values.yaml
  # How:
    # Checkout vsp-infra-application-manifests repo using actions/checkout
    # Configure AWS creds using aws-actions/configure-aws-credentials@v1
    # Grab bot token from Param Store using marvinpinto/action-inject-ssm-secrets@latest
    # Install yq
    # Use some fancy yq commands.
# What:
  # Make commit to main repo of vsp-infra-application-manifests
  # How:
    # Add and commit as the bot using EndBug/add-and-commit@v7
```

**Comment by rmtolmach** [comment]
Working ✅ 
Action kicked off: https://github.com/department-of-veterans-affairs/vsp-infra-argocd/actions/runs/2890944163

Commit to main: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/67c9e089ad84c6b915710077cbe780d7fce50680
