### ISSUE TITLE
Create Automation NPM Token for Semantic-Release on @department-of-veteran-affars/va-forms-system-core

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va.gov-team#45092]
## Who is the devops resource on your team?
- @bjmccotter7192

## Repository
- [@department-of-veterans-affairs/va-forms-system-core](https://github.com/department-of-veterans-affairs/va-forms-system-core)

## Slack Thread
- [DSVA Support Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1659114039832959)

## Description
Looking to get a new NPM Token created in the VA NPM Organization that is of type `Automation` which will allow `@semantic-release/npm` to upgrade package.json version automatically (tied to Github Release) and publish NPM package to npmjs.com. 

## Background/context 
Our team was using an NPM token already for `yarn npm publish` action but that token is of type `Publish`. When trying to merge my changes to semantic-release today, the pipeline ended up failing because the Token was of the wrong type (needed to be of type `Automation`).

Went back to my personal NPM package (outside of VA and Ad Hoc repos), created new Tokens inside of my personal NPM account, and did some investigating around the different types of tokens and got one to work properly using the `Automation` type.

This is what led me to this request, I also didn't want to request a change to `VA_VSP_BOT_NPM_TOKEN` because I didn't know if it was being used by other application teams.

### Current Version
```yaml
- name: Publish build artifacts to NPM
      run: yarn npm publish --access public --tolerate-republish
      env:
        YARN_NPM_AUTH_TOKEN: ${{ env.VA_VSP_BOT_NPM_TOKEN }}
```

### Broken Version
```yaml
- name: Run npx semantic-release, create Github Release, and Publish NPM package
      run: npx semantic-release
      env:
        YARN_NPM_AUTH_TOKEN: ${{ env.VA_VSP_BOT_NPM_TOKEN }}
        GH_TOKEN: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
```

### Example Proposed Fix Version
```yaml
- name: Run npx semantic-release, create Github Release, and Publish NPM package
      run: npx semantic-release
      env:
        SEMANTIC_NPM_TOKEN: ${{ env.VA_VSP_BOT_SEMANTIC_NPM_TOKEN }}
        GH_TOKEN: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
```

---
## Tasks
- [ ] Add Automation NPM Token to VA npmjs.com (ex. SEMANTIC_NPM_TOKEN)
- [ ] Add token value to new VA_VSP_BOT token in secret store (ex. VA_VSP_BOT_SEMANTIC_NPM_TOKEN)
- [ ] Copy value of NPM Token into `SEMANTIC_NPM_TOKEN` secret in `@department-of-veteran-affairs/va-forms-system-core`
- [ ] Reach out to me so I can update the npm-publish.yml file with new VA_VSP_BOT token name OR could update yourself (no preference either way)

## Acceptance Criteria 
- [ ] Token is used to build and push newly version NPM package to NPM successfully

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Synced with BJ via [Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1659719303907189?thread_ts=1659114039.832959&cid=CBU0KDSB1). Looks like the permissions being asked as working as intended. Closing ticket. Feel free to reopen as needed BJ
