### ISSUE TITLE
Add Yarn Workspace to vets-website [base]

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#45101]
## Issue Description

Implement Yarn Workspaces within `vets-website`, creating a *worktree*--root workspace-- and laying the groundwork for treating `src/application` and `src/platform` subdirectories as future workspaces.

## Tasks
 - [x] Create and set up `package.json` file in root directory
 - [x] Update root `package.json` file (create `workspace` and `nohoist` fields)
 - [x]  Switch `.babelrc` to `babel.config.json` and adjust as needed 
 - [x]  Adjust webpack as needed 
 - [x] Test yarn install (check  `node_modules` directories and symlinks)
 - [x] Test existing scripts and CI --  All should no different from prior to yarn install
 - [x] Run In-browser test and document here
       https://docs.google.com/spreadsheets/d/1SB31FJ3E6KPMDx3BODE02bc8hL97-M12ABwyDBzJMxg/edit#gid=0

## Dependencies
None

## Acceptance Criteria
- [x]  A yarn *worktree* will be added to the `vets-website` repo
- [x]  No changes to CI or workflow should be necessary

**Comment by rmessina1010** [comment]
Archival. Work completed.
Closing issue.

**Comment by rmessina1010** [comment]
Closing issue.
