### ISSUE TITLE
Convert platform/landing-pages to yarn workspace

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#45102]
## Issue Description
Set up `platform/landing-pages` as a yarn workspace.

## Tasks
 - [ ] Create and set up `package.json` file 
 - [ ] repo root `package.json` file (register in `workspace` and update`nohoist` fields)
 - [ ] Create and populate `exportsFile.js`
 - [ ]  Adjust `babel.config.json`  as needed 
 - [ ]  Adjust webpack as needed 
 - [ ] Test `yarn install` (check  `node_modules` directories and symlinks)
 - [ ] Test existing scripts and CI --  All should work no different from prior to yarn install
 - [ ] Run In-browser test and document here https://docs.google.com/spreadsheets/d/1WW2DPSZ7uNvJQpZJrrwbhEvA0qG6Qm1MSeUR6Y7EWEQ/

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- [ ]  A yarn *workspace* will be added to  `platform/landing-pages` repo
- [ ]  No changes to CI or workflow should be necessary
- [ ]  Passes browser tests

**Comment by rmessina1010** [comment]
(duplicate-closed- see:https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45103)
