### ISSUE TITLE
Revise navigation for Research and Design based on results of tree test

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45107]
## User Story
As a researcher, designer, or team stakeholder on the VA Platform, I want to easily find resources that may affect my team's research and design practices on VA Platform.

Assignee: @jimuhh 
Peer Reviewer: @CherylEvans 

## Description
Ticket #44196 was to perform quick research asking 5-7 questions regarding findability on Platform Website for Research and Design. This ticket is to implement the findings.

## Impacted Artifacts
[Research and Design Page on Platform](https://depo-platform-documentation.scrollhelp.site/research-design/)

## Tasks
- [x] Reorganize Research and Design Pages to align to results of findability study
   - [x] Submitting navigation request changes to Platform Content for review/approval
- [x] Create tech-debt tickets for potential improvements that fall outside the scope of reorganization
- [x] Announce changes to VFS teams following the Platform Communication Playbook

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS team members are able to find important information quicky
- [ ] Platform team members are able to navigate Platform Website and provide links to resources

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@naomimarcussen We had Clayton listed as a reviewer for this ticket (in addition to Cheryl). Once complete, would you be able to take a look and make sure it's implemented as expected? Please and thank you!

**Comment by naomimarcussen** [comment]
I'm happy to review. If you need any help doing the work, I'm happy to help with that as well.

**Comment by jimuhh** [comment]
Hi @naomimarcussen. I've submitted the new schema to Platform Confluence Not having Clayton around to draft some of the new top-level pages throws a bit of a monkey wrench into things= but I did my best to adapt. 
**See below:**
Research: Overview	
	Research Overview
Research: Planning and recruiting	
	Planning and recruiting
	Planning and recruiting checklist
	Planning Moderated studies
	Planning Unmoderated studies
	Recruting participants
Research: Conducting sessions	
	Conducting Research Sessions
	Conducting sessions checklist
	Pilot participant guidelines
	Observer Guidelines
	Safety and Emergency Exit
	Tech set-up checklist
	Recording research sessions
Research: Mobile sessions	
	iPhone: Start screen share
	iPhone: Stop screen share
	iPhone: Screen recording set-up
	iPhone: Access chat
	Android: Start screen share
	Android: Stop screen share
	Android: Share device audio
Research: Assistive technology sessions	
	Research with Assistive Technology Users
	Testing with screen readers
	Disability Etiquette

**Comment by jimuhh** [comment]
@naomimarcussen See schema below...

```
Research: Overview	
	Research Overview
Research: Planning and recruiting	
	Planning and recruiting
	Planning and recruiting checklist
	Planning Moderated studies
	Planning Unmoderated studies
	Recruting participants
Research: Conducting sessions	
	Conducting Research Sessions
	Conducting sessions checklist
	Pilot participant guidelines
	Observer Guidelines
	Safety and Emergency Exit
	Tech set-up checklist
	Recording research sessions
Research: Mobile sessions	
	iPhone: Start screen share
	iPhone: Stop screen share
	iPhone: Screen recording set-up
	iPhone: Access chat
	Android: Start screen share
	Android: Stop screen share
	Android: Share device audio
Research: Assistive technology sessions	
	Research with Assistive Technology Users
	Testing with screen readers
	Disability Etiquette
```

**Comment by jimuhh** [comment]
But I've submitted the schema to [Vicki at Platform Confluence](https://dsva.slack.com/archives/C01AS05BQ79/p1663005991534549?thread_ts=1660847635.434509&cid=C01AS05BQ79)

**Comment by naomimarcussen** [comment]
@jimuhh Thank you for this! I'll work on organizing our content according to this schema in the Platform website drafts space in Confluence. As for the new pages, I'll give it a go but I would love some help from the Platform content team.

**Comment by jimuhh** [comment]
@naomimarcussen -- It looks like most of the "to-dos" on [this spreadsheet](https://docs.google.com/spreadsheets/d/1vn_uAw9wJ1QB7vpWwj_ySJ4stfwU1Yt8Bp6BEjSZhzg/edit?usp=sharing) are accounted for. The only remaining ones were going to be adding a page specifically about surveys, w/ focus on PRA and privacy concerns. Clayton was going to do that. I can ask in VA research channel and have a go on stubbing one out.

**Comment by CherylEvans** [comment]
@shiragoodman @jimuhh Given your comment Jim, is this ready for peer review?  If you don't mind, will you provide a link for all your drafts that I need to review? Also, I am a little confused.  Have these changes already been made to the Platform Website?  I see that the announcement was made, and that is why I am confused.  Please advise.  I have also requested access to the Google sheets referenced above.  Sorry for all of the questions, I simply want to perform an accurate and complete review.

**Comment by jimuhh** [comment]
@CherylEvans Sorry if I didn't clarify. The remaining tasks here would be covered by the tech debt tickets I'll be creating. And yes, the changes have.been made to platform website.

**Comment by jimuhh** [comment]
@CherylEvans So yeah, I don't know how much peer review is left to complete.

**Comment by CherylEvans** [comment]
@jimuhh It's all good!  Thank you for sharing the doc with me.  In as much as I understand what was to be accomplished with this ticket, I think everything looks good.  There were a lot of moving parts with this ticket for sure.  :-)

**Comment by naomimarcussen** [comment]
@jimuhh That would be great for you to take a stab at a page specific to surveys! I imagine it'll be similar (in regards to the PRA content) to the [Planning Unmoderated Studies](https://vfs.atlassian.net/wiki/spaces/RD/pages/1904738369/Planning+Unmoderated+Studies).

**Comment by jimuhh** [comment]
@naomimarcussen, @shiragoodman  I am going to check off the remaining tasks and create a backlog ticket for the surveys page.
