### ISSUE TITLE
Convert platform/landing-pages to yarn workspace

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#45103]
## Issue Description
Set up `platform/landing-pages` as a yarn workspace.

## Tasks
 - [x] Create and set up `package.json` file 
 - [x] repo root `package.json` file (register in `workspace` and update`nohoist` fields)
 - [x] Create and populate `exportsFile.js`
 - [x]  Adjust `babel.config.json`  as needed 
 - [x]  Adjust webpack as needed 
 - [x] Test `yarn install` (check  `node_modules` directories and symlinks)
 - [x] Test existing scripts(`yarn test`)  and CI --  All should work no different from prior to yarn install
 - [x] Run In-browser test and document here https://docs.google.com/spreadsheets/d/1WW2DPSZ7uNvJQpZJrrwbhEvA0qG6Qm1MSeUR6Y7EWEQ/

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- [x]  A yarn *workspace* will be added to  `platform/landing-pages` repo
- [x]  Passes unit tests  
- [x]  No changes to CI or workflow should be necessary
- [x]  Passes browser tests

**Comment by rmessina1010** [comment]
Completed.
