### ISSUE TITLE
[Usability Testing] Decision Review: User Interview Conversation Guide

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4511]
## User Story
As a UX designer, I need to create a user testing conversation guide so I can ensure that all necessary questions are documented in one place and can be referenced during user interviews.

## Goal
_A document to serve as a user interview conversation guide._

## Objectives or Key Results this is meant to further
- This furthers the discovery effort to understand more about the product being built and identify needs and pain points.

## Tasks
- [x] _Create conversation guide (according to template if provided)_
- [x] _Review conversation guide with design team & PM_
- [x] _(Optional) Review conversation guide with content team, IA team for additional questions that could be beneficial_
- [x] _Make edits to conversation guide if necessary_

## Acceptance Criteria
- [x] Conversation guide has been completed

## Next Steps
Send both research plan and conversation guide to Lauren Alexanderson for approval and scheduling with Perigean.

**Comment by kevinstachura** [comment]
Sent note to Public Websites team to review with comments - may have to make edits if they return with comments (none as of yet).

Though this ticket has been satisfied, it's important to note that it still requires sign off from VA. Will reach out to @AZSchneider when she returns as a final review and to get it verified. Then will need to send to Lauren to initiate with Perigean.
