### ISSUE TITLE
EMIS deprecation: Map military_info from EMIS to VaProfile

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45122]
## Issue Description
The auth experience/VaProfile team has an [existing feature toggle to pull SOME military_information from VaProfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/profile/service_histories_controller.rb#L37). The current Emis integration pulls [ALL of this veteran related information](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/emis_redis/military_information.rb#L38-L56) from eMIS. [Called here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L213-L215). We should find a way to map the current info to information in VaProfile. It's possible to use some of the work the auth experience team did, but they use a very limited subset. See [VaProfile swagger docs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L213-L215).

Also see the current [Emis Models](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/emis/models) used to map attributes to a given model

---
## Tasks
- [ ] Document where to get pull current attributes from
- [ ] Document anything that isn't a 1:1 mapping
- [ ] Document a migration path

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laineymajor** [comment]
this is a dupe, but it is now linked to it's twin :)
