### ISSUE TITLE
[Platform Collaboration] Establish DevOps Community of Practice

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45129]
## Description
The Platform Infrastructure team is working with Platform Engineering Leadership to establish a DevOps Community of Practice (CoP). Things like format, agenda, invites, and goals are needed before the CoP begins

## How might we... 
- engage DevOps expertise across various platform crew teams? 
- better understand the needs of various teams using the platform’s delivery infrastructure? 
- meet regularly to discuss important topics related to DevOps work on the VA.gov platform? 

## Background/context 
- We are currently targeting CoP kickoff in early Q4, 2022 
- [Guidelines for Community of Practice spaces](https://vfs.atlassian.net/wiki/spaces/AP/pages/1391067277/Guidelines+for+Community+of+Practice+spaces)
- [GOAL: Implement DevOps community of practice](https://vfs.atlassian.net/wiki/spaces/OT/pages/2201255944/GOAL+Implement+DevOps+community+of+practice)
- [Notes from 2022-07-15: DevOps CoP discussion](https://vfs.atlassian.net/wiki/spaces/OT/pages/2273411104/2022-07-15+DevOps+CoP+discussion)

---
## Tasks
- [ ] Decide on goals for the meeting _(some ideas below)_ 
  - spread knowledge around architecture and tooling
  - promote adoption of tools and services
  - strengthen collaboration and relationships 
  - promote accountability with action items 
  - _byproduct: clarify RACI_
- [ ] Decide on a schedule _(idea: poll interested parties)_
- [ ] Decide on the invite list _(idea: probably platform w/ Identity & CMS for now)_
- [ ] Decide on the agenda for the meeting (some ideas below) 
  - discuss architecture and tooling 
  - highlight upcoming infrastructure changes 
  - identify the status of ongoing DevOps work
  - identify blockers between teams 
  - poll: “Are there any DevOps topics that you’re interested in learning more about? or that infra could present?” 
- [ ] Figure out how to share the responsibility of keeping the community active 

## Definition of Done
- [ ] The DevOps CoP space has been created in Confluence
- [ ] The first meeting for the DevOps CoP has been scheduled
- [ ] The following has been established before the first meeting: 
  - [ ] Goals
  - [ ] Schedule
  - [ ] Invite list
  - [ ] Agenda
  - [ ] Duties 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
It would be great to walk through the mural board that was created to organize thoughts for the CoPs.
