### ISSUE TITLE
Cancelation discovery

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#45124]
## Background
VAOS displays both appointments canceled by the Veteran and facility. Questions often arise as to why we show these. 

Generally our answer is that Veterans need to understand when a facility cancels the appt, because notifications are lacking. The same answer applies to Veteran-canceled appts. Additionally, Veterans use the VAOS appts list to verify their appts, so it needs to be a complete source of truth.

The goal of this discovery is to evaluate our assumptions and provide a clearer understanding of why Veterans may or may not need this information

## Todo

- [ ] Desk research - collect comments and background on cancelation into mini-report: - @outerpress
- [ ] Ask product for canceled metrics
- [ ] Ask for requirements around canceled appts
- [ ] Aggregate Veteran feedback (ask Kay)

**Comment by outerpress** [comment]
Duplicate of #45125
