### ISSUE TITLE
[Technical discovery] Form 8940: Review BAH documentation in GH 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4513]
## User Story:
As a Front-end engineer on the Benefits and Memorials Team, I need to review the code written for form 8940 by Booz Allen team so that I can make sure it is in working order.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Locate GH folder
- [ ] Review code for 8940
- [ ] Identify gaps that need to be updated/completed

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* The code for 8940 has been reviewed

**Comment by ndsprinkle** [comment]
I have finished my code analysis, research into the functionality of the online form, and conducted a design review meeting for the 8940 form.

The online 8940 form functions as it should and covers all the fields that are present in the physical 8940 form. There is a dedicated page regarding unemployability that instructs the veteran on how to fill out the 8940 form (and 4192) with options to use the online disability application (526) or print out the physical form and submit manually.

The design for the 8940 form was also seen as satisfactory. There were a few small instances of areas that could potentially be improved, but nothing that would hinder the veteran's ability to properly fill out the form. If any design work is deemed important enough for improvement, separate spin off stories will be created.

The code for 8940 is also up to par for our team and follows expected form standards. All pages for the form are contained within `src/applications/disability-benefits/all-claims/config/8940/index.js` inside of the `vets-website` repository.
