### ISSUE TITLE
Debt Portal Edge Case - Data

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#45142]
## Issue Description
The Debt Portal edge case dashboard will require new datasets to complete.  

[mock up deck](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit#slide=id.g13d5e39691c_0_0)
[KPI worksheet](https://docs.google.com/spreadsheets/d/1GlcJ2rmmlA-K9uzaeiu9KoF-NantyP4xwYcLbn9JjlI/edit#gid=2091635579)

---
## Tasks
- [x] Complete the dataset request form - Pavan
- [x] Review request form, answer questions, confirm alignment on data needs - Chloe & Pavan
- [x] Create new datasets - Chloe
- [x] QA data in BQ - Chloe

## Acceptance Criteria
- [ ] The datasets needed to complete this edge case will be created and ready to use in the new dashboard configuration.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pavanhothi** [comment]
@chloedotbrown here is the completed [dataset request form](https://docs.google.com/spreadsheets/d/1k39V_sJBonAUju7AdwLf_1VAd3gSWeUp5u0KSECpfEk/edit#gid=0). Please let me know if you have any questions or need anything else. Thank you!

**Comment by chloedotbrown** [comment]
Hey @pavanhothi - six datasets seems like a lot for this. We also shouldn't be doing any unique user counts that would be aggregated on the dashboard - for those metrics to be calculated accurately, the data has to be brought in at a less processed level, with the actual `user_id` fields still there.

I'll take this request form as a starting point and look back at the KPI spreadhseet and mockup to make sure I've got a complete list of all the fields needed, but I'll iterate on the actual data models to get us what we need.

**Comment by chloedotbrown** [comment]
## Data QA - complete
Created a `vw_debt_portal_last_week` view in the analytics_testing folder in BigQuery. 
_Conducted on 9/4 to 9/10 data._


_Reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the count of distinct hit IDs (combination of session and hit number). 

Total rows | Unique IDs
 -- | -- 
 47,903 | 47,903 

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  count(*) as total_rows,
  count(distinct hit_id) as total_uuid
from `vsp-analytics-and-insights.analytics_testing.vw_debt_portal_last_week`;
```
</details>

### Nulls
✅ **Passed!** All null rates had reasonable explanations consistent with other dataset stats or GA validation

Column | Null rate  | Explanation
 -- | -- | -- 
`bounces` | 100% | ✅ Consistent with GA bounce hits (59)
`event_label` | 97% | ✅ Consistent with total pageview hits (46,412)
`event_action` | 97% | _(see above)_
`exit_page` | 87% | ✅ Consistent with GA exits (6,083 vs. 6,082)
`entrance_page` | 87% | ✅ Consistent with GA entrances (6,315 vs. 6,314)
`seconds_on_page` | 16% | ✅ Consistent with combination of events and exit pageviews (7,523 vs. 7,528)
`prev_page_url` | 13% | ✅ Consistent with GA entrances (6,314)
`prev_page_name` | 13% | _(see above)_ 
`next_page_url` | 13% | ✅ Consistent with GA exits (6,034 vs. 6,082)
`next_page_name` | 13% | _(see above)_     

<details> 
  <summary>Expand for test code</summary>

```sql
with debt_nulls as (
  select
    col_name, 
    count(1) total_nulls,
    'a' as join_key
  from `vsp-analytics-and-insights.analytics_testing.vw_debt_portal_last_week` t,
    unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
  group by col_name 
),

debt_all as (
  select 
    'a' join_key,
    count(*) as total_rows
  from `vsp-analytics-and-insights.analytics_testing.vw_debt_portal_last_week`
)

select
  col_name,
  total_nulls,
  round((total_nulls/total_rows), 2) as pct_null
from debt_nulls
left join debt_all using (join_key)
order by total_nulls desc
```
</details>

### Completeness
✅ **Passed!** Checked row distributions for pageviews and events.

<details> 
  <summary>Expand for test code</summary>

```sql
/**************************************
   NOTE: Highlight and run separately
**************************************/

# Check all pages in table are present
select 
  page_name,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.vw_debt_portal_last_week`
where hit_type = 'PAGE'
group by 1
order by 2 desc

# Check all events in table are present
select 
  page_name,
  event_name,
  event_type,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.vw_debt_portal_last_week`
where hit_type = 'EVENT'
group by 1,2,3
order by 4 desc

```
</details>

## Accuracy tests
_Conducted on 9/4 to 9/10 data._

_Reference: [QA for standardized dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents); [WIP Content QA spreadsheet](https://docs.google.com/spreadsheets/d/10ntfDxR2OKxPJ0FI6gCzoyHu1XfbW1-uKKSH1F8ZfOc/edit#gid=0)_


### Pageviews

Page | BQ | GA| Pass/Fail
-- | -- | -- | :--: 
Static Debt Page | 25,253 | 25,247 | ✅
Combined Debt Portal | 7,565 | 7,565 | ✅
Debt Balances | 6,565 | 6,565 | ✅
Debt Details | 4,344 | 4,344 | ✅
Download Debt Letters | 1,305 | 1,305 | ✅
Copay Balances | 553 | 553 | ✅
Copay Balance Details | 564 | 564 | ✅
Copay HTML statement | 263 | 263 | ✅

### Events

Page | Event | BQ | GA| Pass/Fail
-- | -- | -- | -- | :--: 
Copay Balance Details | Pay on Pay.gov | 63 | 63 | ✅
Copay Balances | Pay on Pay.gov | 45 | 45 |  ✅
Copay HTML Statements | Download copay statement | 38 | 38 | ✅
Debt Balances | Pay on Pay.va.gov | 6 | 6 | ✅
Debt Details | Pay on Pay.va.gov | 227 | 227 | ✅
Download Debt Letters | Letter Downloaded - First Demand Letter | 472 | 472 | ✅
Download Debt Letters | Letter Downloaded - Second Demand Letter | 84 | 84 | ✅
Download Debt Letters | Letter Downloaded - Third Demand Letter | 46 | 46 | ✅
Download Debt Letters | Letter Downloaded - Debt Disagreement/Dispute | 5 | 5 | ✅
Download Debt Letters | Letter Downloaded - Debt Increase Letter | 22 | 22 | ✅
Download Debt Letters | Letter Downloaded - Waiver Grant Letter | 2 | 2 | ✅
Static page | Pay on Pay.va.gov | 1,224 | 1,224 | ✅
Static page | Pay on Pay.gov | 153 | 153 | ✅

**Comment by chloedotbrown** [comment]
Here's the new [Combined Debt Portal dataset](https://va-gov.domo.com/datasources/9b0bfc0b-db16-40ab-bc5e-eea8e2973e2d/details/overview) in Domo. I've set it to update every day, since that worked so well for MyVA and the data is relatively small. I'll continue checking the Domo update settings as I continue building cards on the next ticket. But for now, finally closing this one out!
