### ISSUE TITLE
Redux DevTools Bug

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4514]
## User Story:
As a front end developer, I want to see my Redux action dispatched in Redux DevTools, when I click on a checkbox,  so that I know the Redux state has been updated correctly.

## Tasks
- [ ] Identify what is causing my Redux DevTools to crash when the action is dispatched - 3 hour(s) - Mahariel
- [ ] Implement solution/ work around - 1 hour(s) - Mahariel

## Next Steps
- [ ] Identify what is causing my Redux DevTools to crash when the action is dispatched - 3 hour(s) - Mahariel
- [ ] Implement solution/ work around - 1 hour(s) - Mahariel

## Acceptance Criteria:
Given that I am building an MVP to include checkboxes
When I click on the checkbox
Then I should see the action dispatched in Redux DevTools

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
