### ISSUE TITLE
INTL - Chatbot Edge Case - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#45159]
## Issue Description
This ticket is to track discovery work to be completed as part of the [Virtual Agent/Chatbot Edge Case Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45133)

---
## Tasks
- [x] Review [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/Virtual_Agent_Product_Outline_Phase2.pdf), [chatbot staging](https://staging.va.gov/contact-us/virtual-agent/) and [Contact Us page](https://www.va.gov/contact-us/) resources provided by team
- [ ] Review current Domo and GA reports
- [ ] Identify meaningful KPIs and creating tracking sheet
- [ ] Review findings/recommendation with chatbot team

## Acceptance Criteria
- [ ]  When the above items have been completed and we are ready to present finding to Chatbot team.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
[Covid Chatbot dashboard](https://va-gov.domo.com/page/986858114) for reference/ideas.

**Comment by michelle-dooley** [comment]
Meeting with team on 10/12 to discuss MVP requirements.  As discussed internally any metrics that require chatlog data will need to be part of v2 after a data engineer in onboarded.

_notes from slack for reference:
As for the Chatlogs, that's data we'd need to be able to bring in BQ to be able to create many of these metrics. However, the amount of NLP work needed to actually do that is going to require
- cleaning potential PII before bringing it into the warehouse
- bringing that data into someplace I can access it with R instead of SQL (which we haven't done before)
- a lot of exploring / testing to model topics correctly, identify patterns, etc._

**Comment by michelle-dooley** [comment]
The work for this ticket is complete based on information provided.  We are waiting on additional details from the team and will begin a design ticket for that work when ready.
