### ISSUE TITLE
Research Vets-Api Incidents related to failures of External Services and Puma/Sidekiq calls.

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#45165]
# Description

There have been a number of incidents related to failure of external services utilized in the Vets-Api Process and the SRE team needs to understand all of the points of failure.

Examples: 
- [Param Change Issue Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1659459403319599)
- [Vet-API Latency Issue Slack Channel](https://dsva.slack.com/archives/C03STQZ40DQ)

# Tasks

- [ ] Identify Issues Related to [Vets-API Latency issues](https://dsva.slack.com/archives/C03STQZ40DQ)
- [ ] Identify the key points of failure related to Sidekiq and Puma calls.
- [ ] Identify the deploy parameters used by Vets-Api that can cause failed deployments to PROD.
- [ ] Identity any other key points of failure in the Vets-Api that can impact users.
- [ ] Additional Tasks from [Vets-API Latency Research Meeting](https://docs.google.com/document/d/1CgGQYjR8_wKSX3S2V4zLbrOCkv0YDUlowro7JvIPzwk/edit).

# Acceptance Criteria

- [ ] Created Confluence Document or Github Doc with points of failure list and an action plan to resolve and track.

**Comment by zachclarity** [comment]
There have be more issues and we need to identify changes that impact the network latency.

**Comment by oseasmoran73** [comment]
Closing as user is no longer in org and task is incomplete. See #3853 & #48538 for how to reduce
