### ISSUE TITLE
VA.gov Experience Standards - Expand information available to VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#45160]
## Problem Statement 

~~The MVP of the VA.gov Experience Standards was released in July of 2021. The initial release included basic information for VFS teams to be reactive in addressing identified issues. Now that the standards have been in use for over 1 year, Governance team has recognized that VFS teams would benefit from a deeper set of standards, including a severity scale so VFS teams can understand when an issue classified as "depends" severity would become launch-blocking vs. when it would be non-launch blocking. Some other standards could also benefit from references to supporting materials (VA.gov Design System, WCAG), and additional guidance on how to meet the standard. The goal of this iteration is to allow VFS teams to be more proactive in ensuring they're meeting the Platform standards.~~

**Revised problem statement 6/29/2023 (#59547):** Governance team members have been using the VA.gov Experience Standards since July 2021. The current standards are very silo'd across practice area, have varying levels of specificity, include gaps and duplication of coverage, and are not communicated or understood in a meaningful way. This makes it very challenging for Governance team members to locate the applicable standard, apply the standards consistently from Staging Review to Staging Review, and in turn, makes it challenging for OCTO leadership to interpret the Staging Review data over time. By restructuring our VA.gov Experience Standards to take on the lens of user experience, and communicate clearly what the problem is for the user, we are confident that the Governance experience will greatly improve wrt application of the standards to VFS products, VFS teams will more easily and confidently understand the challenge the Veteran faces in the current product state, and OCTO leadership will be able to measure meaningful data across VA.gov products.

## Hypothesis or Bet
If we restructure the VA.gov Experience Standards to focus VFS teams on the Veteran experience, then we more easily find the applicable standards for VFS Staging Reviews.

If we restructure the VA.gov Experience Standards to address gaps and duplicate coverage, then we will be more consistent and aligned with how we communicate to VFS teams.

If we address the standards being silo'd across practice area, then VFS teams will interpret their findings as experience issues, not a practice-area specific issue.

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*

- [x] We have recategorized the existing VA.gov Experience Standards to focus on the user experience.
- [x] We have renamed and/or rewritten a subset of standards to improve the clarity.
- [x] We have deleted/archived unused and/or irrelevant standards.
- [x] We have organized the standards in a way that allows for ease of use amongst Governance team members.
- [x] We have communicated the standards to VFS teams so they are easily understood and referenceable 
- [x] We have piloted the new experience standards with 3 VFS teams
- [ ] We have introduced a process for Governance team members to provide feedback once new standards are in use (To be addressed in ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/63510)

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
October 1, 2023

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
Thoughts from the team on 6/1:
- I don’t have a good process for searching the standards / going through them to find a good fit when I identify issues.
- find an issue first, and then try to match to a standard. 
- # of areas where we don't have great coverage
- for example: wasn't sure how to respond to "clear my filters" button (used Missing User Scenario)
- standards are very practice area driven, not UX as a whole
- we need to do a deep dive into the exp stds and look at 1 by 1. bigger? smaller? what needs to change?
- some are hyper specific, some are much more broad
- only 1 exp std that mentions "breadcrumbs"
- do VFS teams know or care about the VA.gov Experience standards?
- are there VFS teams that reference the exp stds that utilize them now? are there teams being proactive? 
- DS standards - guideline vs. UI. 04.07
- if something breaks multiple standards, link to multiple standards

**Comment by humancompanion-usds** [comment]
The team is about to launch a pilot. One issue we need to solve for is the lack of IA principles and guidance in the Design System. We're working with Mikki on that topic.

@shiragoodman - Can you provide any details I missed? Thanks.

**Comment by shiragoodman** [comment]
@humancompanion-usds Our IA specialist has mapped the old IA standards to the new standards and documented the gaps and areas for concern. Details can be found in ticket #73149. We have also created a ticket for drafting the IA principles in ticket  #73684

**Comment by shiragoodman** [comment]
Changes launched 4/22. We will follow up on how the new process is going via ticket #63510.

**Comment by humancompanion-usds** [comment]
@erinrwhite and I announced this to all Designers this past Monday. We're going to attend a similar meeting for Front-end developers, which I will setup. I'm waiting on hearing from Matt Self on how to reach Product folks.

**Comment by shiragoodman** [comment]
@humancompanion-usds I also announced the changes in the Team of Teams meeting on 4/23, however it was not as in depth as the overview you and Erin did with designers. The Team of Teams meeting is mostly product and delivery folks.
