### ISSUE TITLE
Pre-Need |  Testing EOAS integration

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#45170]
## Value Statement
**_As a_** developer
**_I want to_** test the communication between the va.gov and the EOAS in the cloud
**_So that_** I know the application is working properly before pushing to production.

---
## Background Context
This is a request from Kristi Adams (Kristi.Adams@va.gov). As part of the Cloud migration process, the EOAS application is also getting migrated to the cloud. Kristi's team wants to work with us to test the communication between the va.gov and the EOAS in the cloud..

Below are the Cloud BETA environment EOAS webservices URL. 

- https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
- https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Open questions
- Add here

## Tasks
- [ ] _Schedule a testing session with Kristi's team._
- [ ] _Task_
- [ ] _Task_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelpmcdonald** [comment]
EOAS provided 8 endpoints to test in staging


These endpoints return service 'metadata' WSDL service descriptions, so they are not the actual endpoint vets-api will call in staging(we would call an endpoint something like.....\createPreneedsRequest)but they are a good start just to make sure vets-api has access to the endpoint from our staging env.

6 of the endpoints worked, two did not:

Single Sign-on:
Dev:
https://ssodev.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl - failed, doc not found errror
https://ssodev.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL - failed, doc not found error

BETA:
https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

 
Non Single Sign-on:
Dev:
https://dev.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://dev.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL
BETA:
https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

**Comment by sortizsh** [comment]
Sam, can you point EOAS team where the error lives and what it is?

**Comment by samcoforma** [comment]
Left a note about what I've found so far here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/44754#issuecomment-1212384077

**Comment by arul-palani** [comment]
Hi,
I am from the AWS MBS Legacy system. 
Are there any updates implementing the AWS EOAS webservices URL on your system? Please let us know so that we can setup a session to test the communication between the two systems through webservices

**Comment by jacobworrell** [comment]
@arul-palani we'd like to set up some time with your team to conduct some testing and also discuss some next steps related to some of the end point links we haven't fully addressed. We'd want @jerekshoe to be involved in those conversations and he's on PTO until Thursday. Would your team be available sometime Friday this week?

**Comment by arul-palani** [comment]
@jacobworrell thank you. Friday works for us. Please send us an invite

**Comment by jerekshoe** [comment]
Hey @arul-palani, I'm noticing that in the fwdproxy configuration we have the primary port set to `8110`. Will this be the case for the new service as well? [fwdproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L143)

**Comment by arul-palani** [comment]
Hi @jerekshoe 
In AWS the Webservices access is through the DNS registered URLs, so there is no any visible port in the URL. You will need to update the fwdproxy config accordingly

https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

**Comment by jerekshoe** [comment]
@arul-palani I should be able to change those URLs shortly, just wanted to give you a heads up though that I am getting 500 errors when I curl them. I'm not seeing issues when curling these ones however:
https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://beta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

**Comment by arul-palani** [comment]
@jerekshoe i am checking these urls. I will update you asap

**Comment by arul-palani** [comment]
@jerekshoe now the SSO urls are working fine. 

https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedApplicationPort?wsdl
https://ssobeta.cem.vaec.va.gov/eoas_SOA/PreNeedsServicePort?WSDL

**Comment by arul-palani** [comment]
Hi Jerek/Jacob
Today "Rhonda Jones" attempted to enter Preneed case via staging and she got an error, please see the attached screenshot. This issue seems in the PreNeed application, could you please help fixing this issue? So that we can proceed with the testing
![1](https://user-images.githubusercontent.com/70866042/189397339-40f78b5a-9d52-4f4e-a767-86e86cabef8d.png)

**Comment by jacobworrell** [comment]
If we need to re-write code, we'll need to identify precisely what needs to be changed. Resolution requires us to do some investigating on our end and possibly clarifying focus with Platform team.
