### ISSUE TITLE
[PM, FE] 10-10EZ Short Form: Re-launch Short Form to 100% population

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#45175]
## Background
Due to a [production issue](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Short%20Form/7-29-22%20-%20Prod%20Issue%20with%20Short%20Form.md) where Short Form automatic processing failures could not be manually registered due to missing Military Service information, we are re-launching the Short Form feature to production at 100%

## Tasks
- [ ] Update feature toggle to 100% population in production environment
- [ ] Check-in with Joshua Faulkner & team for the week following the re-launch
- [ ] Monitor logs and analytics for any issues, errors or failures

## Acceptance Criteria
- 100% of Short Form eligible applicants will be able to complete the short form flow successfully
- The Enrollment system will be able to automatically process successful submissions
- The Enrollment system will be able to route automatic process failures through the manual registration workflow, generating a 10-10EZ PDF with all application data entered.

**Comment by hdjustice** [comment]
This was done on 10/31/22
