### ISSUE TITLE
[Development] Finalize va.gov integrations with the lighthouse changes 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4517]
## User Story:
As a Back-end engineer, I need to finalize va.gov integrations with the Lighthouse team's changes so that I can ensure they are aligned.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Identify changes to be made after lighthouses most recent update
- [x] Remove legacy appeal endpoint integration
- [x] Update other endpoints if necessary
- [x] Update exceptions in exceptions.en.yml
- [x] Update testing infrastructure

## Acceptance Criteria:
* All integrations align between va.gov and lighthouse

**Comment by SMLuthi** [comment]
This work has been completed. Its sitting in a PR waiting for approval.
