### ISSUE TITLE
[FE] [SPIKE] How might we make our mock APIs stateful?

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#45182]
## Problem statement

Our mocks do not retain any state, so when we check into an appointment locally and then go to the appointment list, the change is not reflected. Also, when reloading, we do not continue the session and get kicked back to the verification page.

## Questions to Answer
- Is there a package/tool available in vets-website that will let us (relatively) easily add state to our mocks?
- Once yarn workspaces is available, would it make more sense to use a different mocks tool? (such as the one we're using for the staging appt tool)

## Tasks
- [ ] [FE] do the spiky thing
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled
