### ISSUE TITLE
[Technical Discovery] Forms 4192: Review BAH documentation in GH 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4518]
## User Story:
As a Front-end engineer on the Benefits and Memorials Team, I need to review the code written for forms 4192 by Booz Allen team so that I can make sure it is in working order.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Locate GH folder
- [ ] Review code for 4192
- [ ] Identify gaps that need to be updated/completed

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* The code for 4192 has been reviewed

**Comment by ndsprinkle** [comment]
I have finished my code analysis, research into the functionality of the online form, and conducted a design review meeting for the 4196 form.

The online 4196 form is as expected and uses detailed images to guide the user through filling out the physical 4196 form. This is different than the 8940 form in that we require the veteran to fill out the physical form. This is because the form requires another party to fill out portions of the form.. There is a dedicated page regarding unemployability that instructs the veteran on how to fill out the 4196 form (and 8940) with options to use the online disability application (526) or print out the physical form and submit manually.

The design for the 4196 form was also seen as satisfactory. The guide to filling out the 4196 form short and to the point, but details all aspects of the physical form up to our standards.

The code for 4196 is also up to par for our team and follows expected form standards. All pages for the form are contained within `src/applications/disability-benefits/all-claims/config/4196/index.js` inside of the `vets-website` repository. This form in particular contains steps of several images as opposed to containing steps of fields like in 8940.
