### ISSUE TITLE
[FE] [BUG] clinic appointments are shown for the next 2 days

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#45189]
## Background

From Shawn Adams:

> not urgent; noticed that the staging appts utility shows earlier times after the end of clinic but because the buttons are selectable I'm thinking it's showing "tomorrows" clinic

![image (31).png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/84dc4bb9-c05c-4ff4-b9b8-0b3d1d39e549)

I verified that our API call is getting appointments from the current and next day.

## Tasks
- [ ] [FE] fix api params or CIE lambda to resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brianseek** [comment]
Validated during FE sync moving to closed
