### ISSUE TITLE
FE | Profile | Address Change Prompt | Re-deploy to 50%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45194]
## Background

Once we have the go-ahead from Analytics that PII issue is resolved, we need to re-deploy this feature to 50% of users so that the changes are visible in Production and can be monitored for a few days.

## Tasks

- [ ] Update feature flags to make Address Change modal visible in Production for 50% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to make changes visible in Production for 50% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO

**Comment by SKasimow** [comment]
Closing...updated 8/23
