### ISSUE TITLE
[PM] 10-10EZ - American Indian: Perform End-to-End Testing With Enrollment Team

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45190]
## Background
The "American Indian" question is needed by downstream systems to ensure Veterans are placed into the correct priority group.  This field has already been added to the paper form, so this will bring the online application into line with it.

We need to work with the Enrollment Team to perform end-to-end testing on the application and ensure the proper information is being received by the Enrollment System and that they can generate a 10-10EZ PDF from the data that's submitted.

See ticket #28973 for epic details.

---

## Tasks
- [ ] Perform end-to-end testing with the Enrollment Team
- [ ] Ensure that automatic processing occurs as expected
- [ ] Ensure that, in the event of an automatic processing failure, a 10-10EZ PDF can be generated from the data submitted
- [ ] Ensure that, in the event of an automatic processing failure, the 10-10EZ PDF has the appropriate data for the *American Indian* question

**Comment by markfallows** [comment]
Presented changes in staging to the Enrollment System testing team.  Received [**email from Stephanie Baldwin**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Medicare%20Claim%20number/8-5-2022%20E2E%20Testing%20confirmation.md) that testing is complete and applications successfully transmitted as expected.


>Baldwin, Stephanie D.
>Aug 5, 2022, 5:18 PM (3 days ago)
>to Joshua, Cassandra,, Lihan, me, VHA
>
>Hello All,
>
>BSO Functional Testing Unit completed UAT to confirm Veteran Online Applications have updated required fields of the 10-10 EZ form:
>
>Insurance Information_Medicare:
>- Veterans are required to provide Medicare Part A (hospital insurance) response.
>- Veterans are required to enter Date and Medicare claim number (30 character max) response when Medicare is marked yes.
>- Explanation of inquiry displays.
>
>Veteran Information_American Indian or Alaskan Native:
>- Veterans can self-report/select American Indian or Alaskan Native race, ethnicity, or origin on VOA application.
>- Veterans are required to provide a response to determine if recognized as an American Indian or Alaska Native by any tribal, state, or federal law or regulation.
>- Explanation of inquiry displays.
>
>Note: Veteran Online Application is pointed to SQA VES environment.  PR approval process is required to change the >environment to Pre-Prod (estimated 1 week process).  Testers were granted SQA access and testing was completed in >SQA environment. 
>
>SQA VES uses Spokane as the preferred facility, all tests were assigned to Spokane to confirm expected results.
>
>Testers confirmed that all online applications successfully transmitted to SQA enrollment system.
>
>Thank you,
>Stephanie D. Baldwin
>Program Analyst, Functional Testing Unit
>Business Support Office, VHA Member Services
>Stephanie.Baldwin@va.gov
