### ISSUE TITLE
[Design] NOD: Conduct Design Review of Design Intent

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4519]
## User Story:
As a designer on the BaM team, I need to conduct a review of the design intent for Notice of Disagreement with the VSP team so that I can ensure I am following the design principals identified by VSP.

## Design Intent
https://app.mural.co/t/vsa8243/m/vsa8243/1574193061780/6424902fd07999e3388f34a872ebdc1c62450f63

## Tasks
- [ ] Schedule review of Design Intent
- [ ] Conduct review of Design Intent
- [ ] Create ticket to update Design Intent (if needed)

## Acceptance Criteria:
- [ ] Design intent has been reviewed
- [ ] Necessary tickets for updates have been created

**Comment by kevinstachura** [comment]
Before doing this, we need to properly align with the Lighthouse team to determine a shared understanding of scope, moving forward. My prediction is that this will occur the upcoming sprint, making it appropriate to move into next sprint for completion.

**Comment by vhenry07** [comment]
Closing as this work will be completed under a new ticket.
