### ISSUE TITLE
[DD] Create Infrastructure dashboard Overview

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#45202]
## Description

Create a dashboard of infrastructure resources to display at-a-glance if the platform is healthy. This will help determine if issues are at the infra level [or the application layer]. This should be high-level and point towards the issue without displaying the issue in the Overview -- answers, "is {{ this }} working?"

## Background/context

As we are trying to move away from infrastructure owning and maintaining everything, this will help identify Infrastructure related issues vs application related.

## Technical notes
- https://vagov.ddog-gov.com/dashboard/dyi-wbv-6mk/platform-infrastructure?from_ts=1660132849153&to_ts=1660136449153&live=true
- [Slack](https://dsva.slack.com/archives/CTYQL39FE/p1659469063212839?thread_ts=1659468533.605349&cid=CTYQL39FE)

---
## Tasks
- [x] Rev Proxy health is displayed
- [x] Fwd Proxy health is displayed
- [x] EKS Dev Nodes
- [x] EKS Stage Nodes
- [x] EKS Sandbox Nodes
- [x] EKS Utility Nodes
- [x] EKS Prod Nodes
- [x] Traefik Is Healthy (running)
  - [x] Dev
  - [x] Staging
  - [x] Prod
  - [x] Utility
  - [x] Sandbox
- [x] EKS Node Pressures
- [x] If CPU throttling is happening (a possible indicator that scaling is not correctly taking place)
  - [x] Restrict only to infra-provided services (e.g., traefik, datadog, etc)
- [x] Count of pods booted for OOM
  - [x] Restrict only to infra-provided services (e.g., traefik, datadog, etc)

## Acceptance Criteria 
- [x] EKS Nodes are monitored
- [x] Rev Proxies are monitored
- [x] Fwd Proxies are monitored
- [ ] Infra-provided services are monitored

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
We may want to break this down

**Comment by jhouse-solvd** [comment]
@ph-One or @oseasmoran73 - Looks like some good work has been done so far. Should this live in the backlog for now? or...

**Comment by ph-One** [comment]
We should break off those last two unfinished tasks and create them as separate tickets; they can be worked on concurrently (thus separate tickets). Once we have those tickets, let's close this.

**Comment by ph-One** [comment]
Added CPU Throttling and OOM metrics to the dashboard. Closing this out
