### ISSUE TITLE
Add Product Directory Update Action to Staging Review and Kickoff

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45201]
## User Story
As a VFS PM, I want clear guidance for how to update the Product Directory so that I am able to provide updates and verify information.

As a QA Standards team member, I want VFS PMs to update the Product Directory so that our process can run and load data mapped to their manifest file.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
QA Standards is ready to roll-out the Product Directory. They would like to leverage the Collaboration Cycle to request that teams verify their information in the directory. For existing products, VFS teams can verify their product information at any time, however for new products, this needs to be late enough in the process that code has been written so that the manifest file is generated.
After walking through the Collaboration Cycle process as is and slack discussions, we determined that it would make the most sense to include two actions for VFS teams to Verify their entry in the Product Directory - at Collaboration Cycle Kickoff and at Staging Review. 
This will allow the QA Standards Teams process to run and process data that will run test cases.
Chase met with Curt and Peter on 8/2 to discuss and determine best location for this checkbox, [Slack thread](https://dsva.slack.com/archives/G01DXP10GCA/p1659378891322149).
[Pending Go/No-Go Platform Website: VFS Product Directory page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory)

## Impacted Artifacts
[Collaboration Cycle Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)
[Platform Website: Collaboration Cycle Kickoff](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+Cycle+Kickoff)
[Collaboration Cycle Request - Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)
[Deprecated Staging Review Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md)
[Platform Website Staging Review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review)
[Previously Created CC Request Tickets at Earlier Touchpoints (Currently 9 tickets)](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board?repos=133843125)

## Tasks
- [x] Add "If your product is already on VA.gov, please verify your product information in the Product Directory" checkbox to VFS Product Information section of yaml template (PR 46798)
- [x] Add guidance to Platform Website: Collaboration Cycle Kickoff for new checkbox
  - [x] Link to QA Standards Teams documentation for how to verify their entry [Cheryl Draft - Copy of Collaboration Cycle Kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2355658753/45201+-+Cheryl+Draft+-+Copy+of+Collaboration+Cycle+Kickoff)
Staging Review:
- [x] Add "Please verify your product information in the Product Directory" checkbox to the VFS actions section of the Staging Review Code Block
  - [x] Link to QA Standards Teams documentation for how to verify their entry [Cheryl Draft - Collaboration Cycle Request - Staging review code block](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2355658765/45201+-+Cheryl+Draft+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) 
- [x] Add "Please verify your product information in the Product Directory" checkbox to the VFS actions section of the deprecated Staging Review template (PR 46804)
  - [x] Link to QA Standards Teams documentation for how to verify their entry
- [x] Add guidance for Platform Website: Staging Review for new checkbox [Cheryl Draft - Copy of Staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2355429405/45201+-+Cheryl+Draft+-+Copy+of+Staging+review)
  - [x] Link to QA Standards Teams documentation for how to verify their entry
- [x] Update open Collaboration Cycle Request tickets with checkbox [Previously Created CC Request Tickets at Earlier Touchpoints (Currently 9 tickets)](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board?repos=133843125)
- [ ] ~~Announce change to Staging Review~~ 9/13 update: Gov team decided it is not necessary to post updates to Slack as QAST had already announced that VFS teams would begin to see the Product Directory integrated into their Collab Cycle touchpoints.
  - Need to determine appliable channels

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to verify product information in the Product Directory within the Collaboration Cycle process
- [x] QA Standards Team has a defined touchpoint that they can expect teams will verify their information in the Product Directory

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by chaseakirby** [comment]
@pjhill @CBonade This is the draft ticket with tasks that I listed in slack. Please let me know if you see anything else that you would like to include!
Also, if you can provide a link to the starting point for VFS teams then I can add that to the sub bullets.
@shiragoodman FYI

**Comment by shiragoodman** [comment]
@chaseakirby [per this Slack thread](https://dsva.slack.com/archives/G01DXP10GCA/p1659378891322149), I'd also like to make sure there's an opportunity for VFS teams to update the product directory at Collab Cycle kickoff... _only if their product is already on VA.gov_. Chase can you please update the ticket to reflect this? Thank you!

**Comment by shiragoodman** [comment]
User guide: https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-guides
depo-platform-documentation.scrollhelp.sitedepo-platform-documentation.scrollhelp.site

Product Directory: https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory

**Comment by CherylEvans** [comment]
@briandeconinck I believe I am ready for peer review.  I have attached all my drafts in the tasks section, along with PR numbers, etc.  I wasn't sure where I was supposed to place the verbiage in the CC Kickoff and Staging review, so I made my best guess as to where they should go.

**Comment by briandeconinck** [comment]
@CherylEvans Quick update on this ticket from looking at it yesterday, and from a discussion at stand-up today.

1. I made a few changes to the Yaml version where your syntax wasn't quite right. Nothing to be worried about -- it's a confusing and very different way of structuring information! The main thing is that a checkbox needs to have both a prompt (the question being answered) and a label (the text to the right of the checkbox that "answers" the question). I've tweaked it a little to have both sets of text. Take a look and please feel free to edit!
2. At stand-up today, Shira said she wanted to check in with the QA Standards PM to see if they want us to demo it before launching, because they maintain the product list. So we'll hold off on actually merging the changes and making them live until @shiragoodman says otherwise.

**Comment by CherylEvans** [comment]
@briandeconinck Thank you so much for making the changes!!  :-) 
I will wait until I hear from Shira before I merge, or publish anything.  Thanks again!

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Sounds good.  I will move forward with merging and publishing.  I have one question.  What channels should I announce this to in Slack?  I will tag both you and Brian once this is published, and changes finalized in the templates.

**Comment by shiragoodman** [comment]
@CherylEvans I'm not sure if we actually need to announce anything in Slack, or in our Change Log. When QAST rolled out the new Product Directory 2 weeks ago, they said in their announcement that, "VFS Teams will begin to encounter the VFS Product Directory in the coming weeks during Collaboration Cycle touchpoints." So I think we're good. No need to post to Slack. I'll update the ticket.[ See Joe's Slack post here.](https://dsva.slack.com/archives/C03R5SBELQM/p1661898497288979)

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Sounds good!!  I will proceed with publishing and squash and merge.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Sounds good!!  I will proceed with publishing and squash and merge.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck All task edits have been published to Platform Website.  PRs have been squashed and merged.  All other tasks completed.  The User Story has been satisfied.
