### ISSUE TITLE
Convert platform/polyfills to yarn workspace

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#45216]
## Issue Description
Set up `platform/polyfills` as a yarn workspace.

## Tasks
 - [] Create and set up `package.json` file 
 - [] repo root `package.json` file (register in `workspace` and update`nohoist` fields)
 - [] Create and populate `exportsFile.js`
 - []  Adjust `babel.config.json`  as needed 
 - []  Adjust webpack as needed 
 - [] Test `yarn install` (check  `node_modules` directories and symlinks)
 - [] Test existing scripts(`yarn test`)  and CI --  All should work no different from prior to yarn install
 - [ ] Run In-browser test and document here https://docs.google.com/spreadsheets/d/1k44ACCMka89E9rCZVCD89nQ8eYaz1EPBDCndfoH11gM/edit#gid=0

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- []  A yarn *workspace* will be added to  `platform/polyfills` repo
- []  Passes unit tests  
- []  No changes to CI or workflow should be necessary
- [ ]  Passes browser tests
