### ISSUE TITLE
QA for Mobile Implementation of SiS

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#45212]
## Issue Description
In this ticket, we will test the end to end user flow and functionality of SiS routes with the mobile app. Using the Test Flight application a QA build of the app will be used to spot potential bugs and provide feedback.

--- 
## Tasks
- [ ] Use the app to log in to a test user account. 
- [ ] Leave a logged in user idle for 15 minutes and then check if user is still logged in.
- [ ] Log out of test user's account and verify that session has been ended. 

## Acceptance Criteria
- [ ] A user should be able to log in to the app without error.
- [ ] A user should stay logged in when idle for up to 15 minutes.
- [ ] A user should be able to sign out of their VA account.

**Comment by nsoutouras** [comment]
Tested 8/3/22, refresh token not being used.  Sent back to mobile team for fix and waiting for new app.

**Comment by nsoutouras** [comment]
Tested, feedback sent to mobile.
