### ISSUE TITLE
[EPIC] MHV to VA.gov - Medical Records Discovery

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#45213]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a product team, I need to understand the current medical records landscape so I can start defining how we will achieve parity on VA.gov.

## Hypothesis or Bet
**If** we gain an understanding of how the current Medical Records product works, the stakeholder needs, regulations, competition, and data **then** we expect to be well-prepared to start defining what the new product will look like on VA.gov

## OKR
_Which Objective / Key Result does this epic push forward?_
Objective 1: Improve Veteran Experience

### We will have completed the user stories listed below

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

## Stories to Create
- [ ] Identify stakeholders (decision makers vs. SMEs)
- [ ] Interview stakeholders
- [ ] Map data
- [ ] Determine regulations
- [ ] Analyze competitive landscape
- [ ] ...
