### ISSUE TITLE
Fix sign in service logout mechanism on FE

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#45229]
## Issue Description
Ensure sign out with Sign in Service works as expected

## Tasks
- [x] Change the Sign out in the PersonalizationDropdown from a button to a link
- [x] Update all instances of the Sign in Service `logout` to use a generated link instead of a button interaction
- [x] Update the Redux actions to log a user out

## Acceptance Criteria
- [x] All logouts using the Sign in Service will redirect
- [x] eAuth logouts are unaffected
