### ISSUE TITLE
Create high-fi wireframes for Yellow Ribbon MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#4522]
## User Story:
As a developer, I need high fidelity screens so that I know which design system components to leverage for this product, and which components I need to build.

As a designer/researcher, I need screens that can create a reasonably realistic experience so that I can test our ideas and see how users react to our solution.

## Tasks
_The steps that must be done by the designer to complete the acceptance criteria_

### Mobile
- [ ] Search page - 1 hour
- [ ] Results page layout, with and without sticky footer - 1 hour
- [ ] Card layout, 2 button variations - 1.25 hours
- [ ] Create 10 cards for first page of results, + 3 with `added` state - 1 hour
- [ ] Comparison screen - 2 hours
- [ ] Create `Compare By` and `Sort by` menus - .5 hours

### Desktop
- [ ] Search page - .25 hours
- [ ] Results page layout, with and without sticky footer - .5 hour
- [ ] Card layout, 2 button variations - .75 hour
- [ ] Update 10 cards for first page of results, + 3 with `added` state - .75 hour
- [ ] Comparison screen - .75 hour

### Handoff
- [ ] Update AC in dev tickets to align with screens and provide links - 1 hour

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* All screens uploaded to InVision
* Dev tickets updated with links and AC

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
[Mobile hi-fi](https://vsateams.invisionapp.com/share/XBVON0YMJ4Y) 

[Desktop](https://vsateams.invisionapp.com/share/X5VOMBG2YP4)
