### ISSUE TITLE
[Research] MyHealth - Secure messaging - Define goals for Medical Records user testing

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#45238]
## Issue Description
Define goals for initial Medical Records user testing.  Refer to Meg's notes, Mural boards and [assets](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/assets) to determine what questions have already been answered.
---
## Tasks
- [ ] Questions that need answers and goals for our initial round of Medical Records testing will be compiled

## Acceptance Criteria
- [ ] A list of questions and goals for Medical Records user testing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
