### ISSUE TITLE
[Research] MyHealth - Secure Messaging - Determine goals for next round of Secure Messaging research

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#45234]
## Issue Description
Based on the outcome of the first round of usability testing, determine what additional questions need to be answered, or existing answers need further exploration.

---
## Tasks
- [ ] Determine questions and goals for next round of Secure Messaging research

## Acceptance Criteria
- [ ] A draft list of questions will be created and shared with the team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
Please see [round 2 research plan for further conversation ticket](https://app.zenhub.com/workspaces/mhv-to-vagov-top-level-view-62619a987d74510018ecc546/issues/department-of-veterans-affairs/va.gov-team/47406)
