### ISSUE TITLE
Add GA events to language toggle

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#45230]
## Tasks

- [ ] Add GA events
- [ ] Merge to main
- [ ] Verify firing in GA
- [ ] Add widget in GA dashboards

## AC

- [ ] Events are firing in GA
- [ ] GA Dashboards are updated and pulling in new events

## Notes

Adrian, maybe like this: 

API Request - preCheckIn-lang-toggle-english
API Request - preCheckIn-lang-toggle-spanish

API Request - day-of-lang-toggle-english
API Request - day-of-lang-toggle-spanish

**Comment by benbrasso-agile6** [comment]
@acrollet @loripusey added this ticket for us to track the existing language toggle

Assume FE can pick this up whenever there is time. Up to you guys.

**Comment by brianseek** [comment]
Opened issue with analytics team for events: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45701

**Comment by brianseek** [comment]
tracking code is merged.

**Comment by brianseek** [comment]
Validated the new update for event tracking of the toggle works in stage. Keeping this in validate until @benbrasso-agile6 has time to observe it in prod.

**Comment by benbrasso-agile6** [comment]
@brianseek [this is why I think we maybe can control the action value a bit more](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45701#issuecomment-1224564489)

then, we could use the label to populate the url the event took place on... maybe

but, if we can't customize that action value... the approach you showed me earlier works just the same
