### ISSUE TITLE
[Application Hosting and Deployment] Validate GitHub teams permissions for ArgoCD (with a service/team)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45255]
## Description
The Platform Infrastructure team has been working to provide access to ArgoCD resources using GitHub teams. This work should be validated by selecting an example application and team to ensure that the permissions model meets their needs. 

## Background/context 
- Argo is using GitHub Teams to manage access to deployments
- The team naming structure is `<app>-<env>-{ro,rw}`

## Technical notes
- Not all automation may be in place for this yet, so manual adjustments may be required
- Vets-API in EKS dev would be the best team candidate for this

---
## Tasks
- [x] Create an Argo GitHub Team for vets-api
- [x] Add user(s) to the `*-ro` team and verify they cannot modify resources nor access the terminal
- [x] Add user(s) to the `*-rw` team and verify that they _can_ modify resources and access the terminal

## Acceptance Criteria 
- [ ] Feedback has been requested from the team using these permissions to access resources in ArgoCD

**Comment by ph-One** [comment]
Closing. This was tested with Lindsey from Console Services. When given RO access she was unable to access the term, and with RW access she could. General excitement.
