### ISSUE TITLE
Design | Profile | Limit Phone # Extensions to 6-digits

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45257]
## Background

VA Profile has requested that we limit the number of digits we accept in the Contact Information/phone number field's extension section to no more than 6 digits (home, work, mobile).

## Tasks
- [x] Determine how we should inform users of the 6 digit max for extensions (eg: before entering any data or after they attempt to enter more than 6 digits)
- [x] Create mock depicting recommended approach
- [ ] Review with Content team to create appropriate messaging  

## Acceptance Criteria
- [ ] Mocks reviewed and approved
- [ ] FE solution is documented
- [ ] Sketch files are updated 
- [ ] Let PM know when ready for FE implementation

**Comment by SKasimow** [comment]
@cgednalske - ok made updates reflecting this is active ticket and in sprint 80!

**Comment by cgednalske** [comment]
@SKasimow I checked with accessibility and the approach of adding text (6 digit maximum) next to the label is the right way to go 👍 Mockups will be done shortly!

**Comment by cgednalske** [comment]
@SKasimow here are the mockups for the Extension 6-digit maximum ([desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v83zmGQ) & [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/52gvqGx)). Noting that accessibility confirmed that adding text next to the label is the ideal, no-magic solution for letting the user know there is a limit before they reach that limit.

The content says "6 digits maximum" following our "25 characters maximum" example in Preferred name, but if we are not sure about this format I can take this to Danielle's office hours next week.

**Comment by SKasimow** [comment]
@cgednalske - I think this looks good and to your point matches how we communicated character limits for Preferred name. I'll tee up for Adam.
