### ISSUE TITLE
[Application Hosting and Deployment] Validate Helm template MVP (by deploying a service with it)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45253]
## Description
The Platform Infrastructure team has been working to develop an MVP of a standardized template that can be used for deploying applications to EKS using ArgoCD. The template should be validated by using it to deploy a service. 

## Background/context 
- See parent epic 

## Technical notes
- The service used to deploy should be one that touches as many areas of the helm chart as possible
  - A good candidate would be httpbin

---
## Tasks
- [ ] Decide on a service to deploy
- [ ] Deploy the service using the standardized Helm template
- [ ] Include at least one helm test (Argo will not automatically run these, but it should be there as an example)

## Acceptance Criteria 
- [ ] The MVP service is using the helm template
- [ ] The MVP service is deployed using ArgoCD
- [ ] The MVP service is accessible through ingress

**Comment by jhouse-solvd** [comment]
@ph-One - Please clarify tasks and acceptance criteria and assign team members. :)

**Comment by jhouse-solvd** [comment]
@ph-One and I chatted about this and think that it might be replaced w/ a new ticket to **‘provide process/instructions for creating a chart’**

_more to come as we move into the next sprint..._

**Comment by jhouse-solvd** [comment]
This is no longer needed. But, we are developing a basic Helm template in #46184

This issue can be closed.
