### ISSUE TITLE
[AWS/IAM] Develop MVP of permissions boundary for Platform DevOps personnel

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45254]
## Description
DevOps personnel from Platform Crew, Identify, and CMS teams need the ability to create and manage infrastructure resources related to the applications that they deploy and maintain. 

The Platform Infrastructure team will develop a baseline permission boundary policy that allows those teams to safely manage resources without risk of privilege escalation or other unintended consequences. Development of the policy should include automated testing as part of the Acceptance Criteria. 

## Background/context 
- Related to #43802 

## Technical notes
- [WIP PR](https://github.com/department-of-veterans-affairs/devops/pull/11595/files) provided by @ianhundere & @ph-One 
---
## Tasks
- [x] Decide on the maximum ceiling of permissions for the "<team-name>-devops" IAM group
  - [x] For teams, we can start w/: QAST, Release Tools, ~Platform Security~, and Identity
  - [x] For affected users, see PR
  - [x] Chat with affected users before and after implementing the policy, ie "We're activating a new DevOps security policy on X date. Let us know if you're unable to perform any critical tasks". 
- [x] Modify the PR as needed to reflect the decisions above 
- [x] Merge the PR
- [x] Make sure the Terraform is applied correctly 

## Acceptance Criteria 
- [x] There is a permissions boundary policy in place that allows teams to manage the resources that they own
- [x] The new policy has been communicated to affected teams and users 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
cc: @little-oddball & @td-usds for awareness

**Comment by jhouse-solvd** [comment]
@troymosher - Let us know if you have any input or guidance for this. We want to be sure that this would make sense from a security policy standpoint. And, I'm happy to provide additional context if needed.

**Comment by troymosher** [comment]
@jhouse-solvd my input would be fairly general, scope the perms to the least amount necessary for them to accomplish what they need, ensure they follow a consistent process of doing things that infra expects of them, etc.  Once documented and fleshed out we can review for specific compliance, etc.

**Comment by ianhundere** [comment]
just to reiterate, the current iteration of the permbound is primarily just avoiding escalated privilege. we may wanna disable things such as `cloudtrail:StopLogging`, but i think this is a good starting point.

**Comment by jhouse-solvd** [comment]
For example, I'm on a DevOps resource on "Team A". 

- allow all 
- explicit deny on specific paths in parameter store related to operations and infrastructure, such as:
  - can't create users in AWS 
  - managing DevOps secrets 
- explicit deny on production 


Part of the work to implement this policy is moving personnel from the "vsp-operations" IAM group and into a more suitable "vsp-devops" IAM group.

**Comment by jhouse-solvd** [comment]
Follow-up ticket: 
- [ ] Discuss automation to validate that policy is applied correctly, ie "Can I do... ?" 
- [ ] Create a new ticket to address the automation (if needed) 

Acceptance Criteria
- [ ] There is automated testing to ensure that users cannot elevate privileges beyond the boundary of the policy

**Comment by jhouse-solvd** [comment]
@jbritt1 - Please move to "In Progress" as time allows. ☺️

**Comment by jbritt1** [comment]
```
 Decide on the maximum ceiling of permissions for the "-devops" IAM group
 For teams, we can start w/: QAST, Release Tools, Platform Security, and Identity
 For affected users, see PR
 Chat with affected users before and after implementing the policy, ie "We're activating a new DevOps security policy on X date. Let us know if you're unable to perform any critical tasks".
```

Conversation started with affected users here: https://dsva.slack.com/archives/C040CF55H0A/p1662651695243959

**Comment by jbritt1** [comment]
Pull request has been modified, approved, applied, and merged. We did change one thing up in that @ianhundere needs the ability to interact with production a bit longer as one of the main folks supporting the vets-api traffic split (slack thread where that was discussed and decided upon: https://dsva.slack.com/archives/C040CF55H0A/p1662651695243959). That being said, the scope of this body of work is likely complete at this time with the understanding that we will have to circle back and update Ian's permissions after the vets-api traffic split initiative is over.
