### ISSUE TITLE
[Application Hosting and Deployment] Automate the synchronization of ArgoCD GitHub teams using Infrastructure-as-Code

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45256]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/context 
_Any additional context for the reader to know, if applicable (optional, please delete if unused)_ 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
This one needs more discussion and possibly broken down into a ticket-per-workflow. Holding a call at 2pm ET today to go over this with the team.

**Comment by oseasmoran73** [comment]
Linking [Create GitHub Teams that Grant ArgoCD Permissions](https://vfs.atlassian.net/wiki/spaces/OT/pages/2306408539/Create+GitHub+Teams+that+Grant+ArgoCD+Permissions)

**Comment by jbritt1** [comment]
Other relevant commits: https://github.com/department-of-veterans-affairs/va.gov-team/commits/master/.github/workflows/ops-application-onboarding-form.yml

**Comment by jhouse-solvd** [comment]
This is no longer relevant. Please see #44415
