### ISSUE TITLE
FE | Profile |Limit Phone # Extensions to 6-digits 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45263]
## Background

VA Profile has requested that we limit the number of digits we accept in the Contact Information/phone number field's extension section to no more than 6 digits (home, work, mobile).

## Tasks
- [x] Limit character field to 6 digits maximum
- [x] Add user messaging re the limitation per these mocks: [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v83zmGQ) & [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/52gvqGx)
- [x] Conduct Unit tests 
- [x] E2E tests cover current code and regression
- [x] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests show 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production

**Comment by SKasimow** [comment]
@adamwhitlock1 - I added mocks with messaging to this ticket so bump up points if needed.

**Comment by adamwhitlock1** [comment]
@SKasimow this can be validated now and should work appropriately.

**Comment by SKasimow** [comment]
@adamwhitlock1  - validated with user 123. Looks good!
