### ISSUE TITLE
Form System | File upload issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#45266]
## Description

When uploading a password-protected PDF file, the form system `FileField` is used to display the password input and "Add password" button. If an incorrect password is entered, an "Upload a new file" and "cancel" button are added below the "Add password" button.

The screenshots are from the Notice of Disagreement form, but it may apply to all uploads.

The following issues need to be fixed:
- All `<button>` elements should be replaced by the [`<va-button>` web component](https://design.va.gov/storybook/?path=/docs/components-va-button--primary)
- The "Add password" button is a styled green button, but the green button was recently deprecated, so we'll need to [switch the green button to a secondary button style](https://dsva.slack.com/archives/C0NGDDXME/p1659542018161409?thread_ts=1659540711.229269&cid=C0NGDDXME)

  <img width="562" alt="Notice of Disagreement card showing a PDF that requires a password. A password input is shown with a green 'Add password' button below, and a 'Delete file' secondary button below that button" src="https://user-images.githubusercontent.com/136959/182684320-2008408f-7ce4-4930-ab9b-bf701cff59d8.png">

- When an incorrect password is provided, and the "Add password" button is used, the "Delete file" button is replaced by an "Upload a new file" primary button and a "Cancel" secondary button. The "Cancel" button should have a white background (possibly fixed by switching to `va-button`?)

    <img width="549" alt="Notice of Disagreement upload card showing an error due to an incorrect password for a locked PDF being entered. There is a green 'Add password' button below, and now a 'Upload a new file' primary button next to a 'cancel' secondary button in a row below the add password button" src="https://user-images.githubusercontent.com/136959/182684318-00ea3931-5975-4a76-9a00-b8c9c258674e.png">

- The "Required" label needs to be fixed - remove the extra wrapping parentheses and extra asterisk.

## Tasks

- [ ] Use `<va-button>` everywhere
- [ ] Change "Add password" to a secondary style
- [ ] Fix "Cancel" button style
- [ ] Fix "Required" label
- [ ] Add tests (as needed)

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Duplicate of #46083
Fixed in [#21998](https://github.com/department-of-veterans-affairs/vets-website/pull/21998)
