### ISSUE TITLE
BE | Profile | Migrate Military Info | Feature Flag @ 100%

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45275]
## Background

Military Information is being migrated from eMIS to VA Profile. Before fully releasing we need to deploy to 100% of users so that the changes are visible in Production and can be monitored for a few days.

## Tasks

- [ ] Update feature flags to make Military Information changes visible in Production for 100% of users
- [ ] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to make Military Information changes visible in Production for 100% of users
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO
