### ISSUE TITLE
[BE] Add feature toggle to allow temporarily avoiding calling the LoROTA DELETE endpoint

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#45308]
check_in_experience_lorota_deletion_enabled

## User Story
As a CHIP engineer, I want to temporarily have access to LoROTA entries so that I can more effectively debug systemic issues.

## Background

CHIP asked that we add a feature flag (perhaps `check_in_experience_lorota_deletion_enabled`) defaulted to ON that prevents the LoROTA delete endpoint from being called when OFF. This would be to allow more easily debugging issues if we see the DELETE endpoint being called and don't think it should be.

## Tasks
- [ ] add feature flag
- [ ] prevent endpoint from being called when disabled (or enabled, depending on the name)

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
