### ISSUE TITLE
[Design] Create Final Wireframes (VAOS appointment information display)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45316]
## User Story
As a Veteran, I would like to see appointment information displayed in a consistent manner across VA applications so that I don't have to search for the information that I need and I know it will be in the same place regardless of what application I use.

[Timing from VAOS in slack thread
](https://dsva.slack.com/archives/C02GXKL8WM6/p1666793760764209?thread_ts=1666715801.647569&cid=C02GXKL8WM6)

[Proposal on how check-in can become more consistent with VAOS.](https://app.zenhub.com/files/133843125/90eff2e0-5d39-4380-97d1-8a42e569d9f0/download)

VAOS modality language in the list and instructions on details pages - [screen files](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1194%3A66663), ticket [48448](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/48448)

[VAOS desktop
](https://www.figma.com/proto/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?page-id=2161%3A54658&node-id=2206%3A58367&viewport=-2793%2C1820%2C0.27&scaling=min-zoom&starting-point-node-id=2206%3A58367&show-proto-sidebar=1)

[VAOS mobile
](https://www.figma.com/proto/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?page-id=2161%3A54658&node-id=2206%3A58505&viewport=-2793%2C1820%2C0.27&scaling=min-zoom&starting-point-node-id=2206%3A58505&show-proto-sidebar=1)

[VAOS aria labels
](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1725%3A67727)

[VAOS research findings (markdown)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-appts-list-usability/research-findings.md)

[Kristen's research findings markdown for appt prioritization within pre check in and check in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-09-checkin-appointment-info-prioritization/Appointment%20Information%20Prioritization%20Research%20Report.pdf)

[Appt detail page specs (Figma)](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=2%3A4&t=ETL9SS4dfFzlsOgM-0)
 
## Tasks
- [x] Create final mockups with callouts for these pages
    - Pre-Check-in:  Landing page
    - Pre-Check-in:  Completed pre-check-in page
    - Check-in:  Select an appointment page (ensure modality type is included) 
    - Check-in:  Completed check-in page (ensure modality type is included) 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud

## Deliverable
- Pre-check-in: https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId&mode
- Check-in: https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
@zach-park @kellysmith1008 I'm going to schedule some time for us to sync on this ticket for monday. In the meantime, please start to review the links/artifacts in the description of this ticket

**Comment by kellysmith1008** [comment]
[Started an analysis mural](https://app.mural.co/t/civicactions3117/m/civicactions3117/1669224357606/afb20755927310a458aa2ee6515ec586340e34c3?sender=u4f51c3ab811a3cc570d34701) to affinitize the results. Will try and finish the VAOS research today

**Comment by benbrasso-agile6** [comment]
There are/will be a few if/then's around when content shows for pre-check-in vs. check-in and for in-person vs. phone. Might be good to schedule a meeting with engineers prior to this ticket being worked on too much by engineers. @loripusey @sarahknoppA6 want me to go ahead and schedule?

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 @kellysmith1008 @kristenmcconnell , the links to the wireframes are attached in the AC area, and they are ready for PO review now.

**Comment by benbrasso-agile6** [comment]
I messaged earlier in this thread about setting up a meeting. I’ll do that now.

**Comment by loripusey** [comment]
@zach please address @benbrasso-agile6 's comments. I'd like for this to be ready to turn over to engineering for implementation by 12/16 at the latest.  Thanks.
@benbrasso-agile6
