### ISSUE TITLE
[FE] Implement New Appointment Details Feature

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45319]
## User Story
As the VA, we would like the presentation/display of appointment information to be consistent across VA applications so that the Veteran will see the information in the same way each time they access it on a different application.
 
## Wireframes
[Annotations](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design&sha=9d6460d6657fc90361f4ef65dc8c165e9298fab3)
[See wireframes in this ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45316)

## Tasks
- [ ] [FE] Implement New Appointment Details Feature
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by benbrasso-agile6** [comment]
dupe
