### ISSUE TITLE
Request vfs-platform-support statistics for Support Questions

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45322]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] Reach out to Zach Lewis (owner of Slack support workflow on #vfs-platform-support) to see if we can get a list of questions VFS teams have asked on that channel
- [ ] Potential Task: Reach out to Platform Content for page visit statistics

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.
