### ISSUE TITLE
Document daily accessibility scan details and monitoring steps

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#45321]
## Description

The daily accessibility scan is currently monitored by our subject matter expert (Darius), but we want to share that responsibility with more people. To do that, we need to share and document information.

## Tasks

- [x] Meet with Darius to review the scan and monitoring steps.
- [x] Turn notes into a Confluence guide.

## Acceptance Criteria

- [ ] A Confluence guide is created for learning the details of the scan and steps to monitor/troubleshoot if a failure occurs.

**Comment by rsmithadhoc** [comment]
- Met with Darius to share knowledge of the scan.
- Took notes that I am working on converting into a Confluence page.

**Comment by rsmithadhoc** [comment]
- Added the [Confluence guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2306703395/How+to+Monitor+the+Daily+Accessibility+Scan) for this, ready for review.

**Comment by rsmithadhoc** [comment]
@ddzz I created [this guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2306703395/How+to+Monitor+the+Daily+Accessibility+Scan) if you want to take a quick look at it if you get a chance. Feel free to make any modifications, thanks!

**Comment by pjhill** [comment]
This is great, thanks so much for whipping up a document!
