### ISSUE TITLE
SPIKE: Review IET transition doc

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#45328]
Description
The IET team would like us to review [this doc](https://github.com/department-of-veterans-affairs/pst-iet-team.documentation/pull/1) for accuracy.

**Tasks**
- [x] Read the doc
- [x] Give feedback if necessary 

**How to configure this issue**
- [ ] Attach a Milestone
- [x] Story points
- [x] Sprint assigned if pulling into sprint
- [ ] Epic assigned
- [x] Team label assigned

**Comment by LindseySaari** [comment]
### Just a couple of notes:
The deploy/automation process for new apps to EKS and Argo is changing. Notes below:


#### [Deploying a micro service](https://github.com/department-of-veterans-affairs/pst-iet-team.documentation/tree/main/Microservice%20Deploy%20Playbook#deployment-to-production-or-utility) 
- This should include the new steps/procedure that the Infra team has just created for creating a new app in Argo, which you use [this issue for](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-promotion%2Coperations&template=application-promotion.yml&title=Application+to+Promote%3A+%5Bapplication-name%5D)
    - Additionally, instead of the main.jsonnet entry, apps should be added to the values.yaml for each helm chart. Examples prod apps values.yaml https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/argocd-apps/prod/values.yaml

- Should mention something about helm in here — we would like to use reusable helm charts vs vanilla manifest files and avoid copy/paste


#### Microservice Migration Plan:
- [This link leads to a 404](https://github.com/department-of-veterans-affairs/pst-iet-team.documentation/blob/main/main/Microservice%20Deploy%20Playbook/playbook-dockerizing.md)
- [This also leads to a 404](https://github.com/department-of-veterans-affairs/pst-iet-team.documentation/blob/main/Microservice%20Migration%20Plan/playbook-deprecation.md)
