### ISSUE TITLE
[BE] Implement Feature Status query by FLIPPER_ID cookie

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#45332]
## User Story
As a veteran, I want to see consistent behavior when the feature is partially dialed up so that I will not lose trust in app with random behavior

## Tasks
- [ ] Implement `check_in_flipper.enabled?` with `actor_type` to check feature status by `FLIPPER_ID` cookie
- [ ] Modify application_controller to get `FLIPPER_ID` cookie
- [ ] Modify Session model to store `FLIPPER_ID` cookie
- [ ] Modify Service layer to access `check_in_flipper.enabled?`
- [ ] Change Client layer to access `check_in_flipper.enabled?`
- [ ] Consume `check_in_flipper.enabled?` in SessionsController
- [ ] Add rspec for the changes

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
