### ISSUE TITLE
[BE] Investigate on Consistent Feature Status for Conditional Toggles

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#45331]
## Background
Currently `vets-api/check_in` uses `Flipper.enabled?(feature_name)` to get the feature status defined in `Features.yml`.  This works well when the feature is enabled 100% for all the requests.  But, when the feature gets dialed up 50% of the time, `Flipper.enabled?(feature_name)` switches between on/off status and disrupts check-in E2E workflow. (Reference [slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1659550303508079))

**Note:** Decision made to have a reusable implementation based on FLIPPER_ID cookie as features might be delivered incrementally to smaller traffic moving forward
 
## Tasks
- [ ] Dive further into Flipper.enabled? api provided in Flipper gem
- [ ] Investigate Flipper configuration in vets-api
- [ ] Come up with proposals for possible ways of querying feature status by the cookie  

## Acceptance Criteria
- [ ] Have a final approach decided for supporting conditional toggles

**Comment by kanchanasuriya** [comment]
`vets-website` uses [vets-api/FeatureTogglesController](https://github.com/department-of-veterans-affairs/vets-api/blob/0eea7171b6eccc61ef244fa6325094f94b6a18f1/app/controllers/v0/feature_toggles_controller.rb#L4-L4) endpoint with `FLIPPER_ID` cookie to query if the feature enabled or disabled.  

Currently, `vets-api/check-in` module uses `Flipper.enabled?` API from Flipper gem to identify the feature status. `Flipper.enabled?` with only the feature name as a parameter works well for 100% feature dial-up.  For partial dial-ups, every time `Flipper.enabled?` called, it switches between ON/OFF state.  To make the feature status consistent across the session for partial dial-ups, `Flipper.enabled?` must be used with a string that is constant across the session. 

With `vets-website` sending `FLIPPER_ID` cookie, vets-api/check-in module controller can get the `FLIPPER_ID` cookie that is consistent across sessions. By passing `FLIPPER_ID` cookie as a constant string to `Flipper.enabled?` API, `vets-api` would provide consistent feature toggle status during partial dial-ups.
