### ISSUE TITLE
Content Revisions for "View Dependents" Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4534]
## Goal
Update content (text and/or links) on the View Dependents page per Content Team's direction, so that the page aligns with the VA.gov content style guide.

## Tasks
- [x] Present View Dependents revisions to Content Team (Peggy)
- [x] Receive and incorporate [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4702) into the View Dependents screen design

## Acceptance Criteria
- [x] Mockups for "View Dependents" are updated to reflect content changes, and they are available to Frontend Engineering for implementation.

**Comment by sporeboy** [comment]
Copy Revisions made. Review here: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/61211510-a9de-477c-950c-ae7fe5d2ce65/View-Dependents-2I beleive the green button should have some indication that the user will be going to the eBenefits site; will follow-up with Peggy on that point.
