### ISSUE TITLE
Remove eBenefits links from 3 housing pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45341]
## Issue Description

We recently removed an action link pointing to eBenefits on the [How to request a COE](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) page because it was pointing to a blank page. This work was completed in ticket #43705

We also have an eBenefits link on these 3 pages that does the same thing:
- [Eligibility requirements for VA home loans](https://www.va.gov/housing-assistance/home-loans/eligibility/)
- [Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/)
- [How to apply for a specially adapted housing grant](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/)

We'll need to rework content on the page similar to what we did on the COE page and remove the button/action link. 

## Tasks
- [x] Rework content and remove link on 3 pages (Aliyah)
- [x] Review work (Laura)
- [x] Copyedit with pre-publishing checklist (Megan)
- [x] Post for product team to review (Laura)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Buttons/action links removed from live pages

**Comment by aliyahblackmore** [comment]
Update 8/10: Will make direct changes in Drupal tomorrow. I created a word doc with the changed content and included some flags on certain areas!

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! This is ready for you! 

I wanted to go ahead and remove the eBenefits links on Drupal and make the content changes on Drupal!
As I was reworking this a few questions came up, so I am attaching my word doc (which also reflects the changes), for you to review!  

[Eligibility requirements for VA home loans](https://www.va.gov/housing-assistance/home-loans/eligibility/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=753

[Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=750

[How to apply for a specially adapted housing grant](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=751

**Word document with changes and comments/questions:** 
[Remove eBenefits links on 3 pages_AB_8.10.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9312122/Remove.eBenefits.links.on.3.pages_AB_8.10.docx)

**Comment by laurwill** [comment]
Thanks @aliyahblackmore for your thorough work here! Here are some notes from my review:
- In node 753, I changed "your COE" to "a COE" in the header to match the "how to request" page.
- Thanks for flagging those questions about how "through your lender" works when VA is the lender! I chatted with Beth, and we're going to move forward with this language for now and open a [ticket in the backlog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45742) of this epic to look into this. Appreciate you digging into this. 
- In node 750, I tried reorganizing the instructions a bit to make the "if you have trouble accessing the form" piece apply to both mail and in person, as you suggested. See what you think! I think this would also solve the related question you had about the placement of that phone number in the in person section. If you think this makes sense, could you apply these changes to node 751? And of course let me know if you see an issue with my changes!
- Also saw your comment about ordering mail/in person options — I think we default to mail before in person, since that's usually more convenient. Though if there's ever a reason that in person seems like the more convenient option, we could consider reordering.

**Comment by aliyahblackmore** [comment]
Thanks for this @laurwill ! The reorganization of the instructions in node 750 look great to me. And I agree, it solves my related questions re: the phone number placement. I applied those changes to 751 and I went ahead and removed the link ["Learn more about how to apply for a housing grant"](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/) as it would just link to node 751. 

Hi @megzehn - these links are ready for you to copy edit! The only ask is to **hold** on publishing, as Laura will confirm something with Beth a bit later today!  

[Eligibility requirements for VA home loans](https://www.va.gov/housing-assistance/home-loans/eligibility/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=753

[Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=750

[How to apply for a specially adapted housing grant](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=751

Also, as mentioned to you Laura, these are my notes on the Find VA locations tool after doing a bit more research in relationship to the steps on the Disability housing grant page, node 750. If there is any change, noting here that it would also  need to be made on node 751.

**Notes:**

For in person form drop off, we instruct Veterans to find their VA regional office. Just to be sure the process/steps were accurate I wanted to try it out. I did a search to find a VA regional office using the [ Find VA locations ](https://www.va.gov/find-locations )tool. 

I'm wondering what a Veteran should put in the search or if we should specify? 

When I select “VA Benefits” as the facility type and “VA home loan help” as the service type, no results show. I tried zip codes in NY and also tried out Virginia and “No results found” comes up. When I set the service type to “All VA benefit services” I then see the various regional offices in NY. 

There is also a legacy page with a [list of regional offices](https://www.benefits.va.gov/benefits/offices.asp)

Mostly, I wonder if extra steps should be given for the VA location tool because someone may not know what to search in order to populate the different facilities or would it be feasible to link to the [regional offices](https://www.benefits.va.gov/benefits/offices.asp) page that already exists?

**Comment by aliyahblackmore** [comment]
Update regarding the Find VA locations tool and facilities: 

I was in touch with the facilities team (Friday morning) and they replied with some more insights on how the tool is populating information:

The facilities folks got back to us and there may be a follow up question for stakeholders re: whether or not all regional offices offer "home loan" services and if bringing the application in person is considered a “home loan service?”

On person did some digging and asked this question (which I think is great):

"How is VA Home Loan Assistance being defined? If Veterans are being told to bring an application into any regional office, is that saying all regional offices offer home loan assistance?

At the moment there are only 22 locations that show as offering the home loan services via the VA locations finder tool. So the question may be: Is bringing in a Specially Adapted Housing grant application to a regional office considered a home loan assistance service? **OR** Can this application be turned in at all/any regional office?

Someone else also added that there is an underlying issue re: the data source for benefit services per facility not be particularly robust (for example: only the 22 facilities are tagged as offering VA loan help). They also noted that better understanding how these services should be mapped is part of the scope for the modernized VBA regional office pilot.

**Comment by laurwill** [comment]
Noting that we'll offer the mail option only for now, and open a new ticket to investigate the facility locator situation.

**Comment by aliyahblackmore** [comment]
Thanks Laura! 

Hi @megzehn these are ready for you! As discussed, the "In person" option was removed from the housing grant pages for the time being. 

[Eligibility requirements for VA home loans](https://www.va.gov/housing-assistance/home-loans/eligibility/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=753

[Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=750

[How to apply for a specially adapted housing grant](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=751

**Comment by laurwill** [comment]
Hi @megzehn , just noting that you can copyedit these but hold on publishing. We'll post them in another ticket for the product team to review before we publish. Thank you!

**Comment by megzehn** [comment]
Thanks, @laurwill. I reviewed the changes and left in draft status for now.

**Comment by laurwill** [comment]
Thanks Megan! I posted in the related ticket, and I'll update when we're good to publish.

**Comment by laurwill** [comment]
Hi @megzehn , Sade and Matt confirmed over slack that this is all good  — you can go ahead and pub these 3 pages.

**Comment by megzehn** [comment]
Thanks, @laurwill. These are all published now! Over to you @RLHecht.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
