### ISSUE TITLE
[FE] Add logic to not display physical location field for telephone appts

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#45344]
## User Workflow
When we display a phone appt in pre check in, do not show the physical location field label or value. Even if we have the physical location value, do not show it to the Veteran. It's too confusing to show for telephone appts.  

This assumes we don't ever show telephone appts during check in. But, that's something to verify. 
  
## Tasks
- [ ] [FE] Update logic/code 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by sarahknoppA6** [comment]
@ytsaoca @zach-park to validate that no physical location shows for pre check in for telephone appts

**Comment by acrollet** [comment]
This has been merged and will go out with tomorrow's deploy.
