### ISSUE TITLE
Get rid of MHV accounts in usercontroller

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45352]
This ticket does not state to remove MHV accounts from VA.gov

## Description
MHVAccounts are used in the following ways in vets-api:
* directly through the `mhv_account` resource route to the MHVAccount controller/model
* through the User model's usage of the `MHVAccount` model
* indirectly through its relationship to `TermsAndConditionsController`

## Tasks
- [x] remove mhv_account resource, controller, & model
- [x] remove terms_and_conditions controller

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by bramleyjl** [comment]
Waiting for the frontend PR to remove the remaining calls to this resource before working on removing it from vets-api.

https://dsva.slack.com/archives/C019S3NSSAD/p1670613044332899

**Comment by bramleyjl** [comment]
Question re: `remove related Sidekiq jobs`, the only MHV account related ones are the mhv_logging `audit_login_job` & `audit_logout_job`. It doesn't look like any of this code actually leverages the `MHVAccount` model, just the `user.mhv_correlation_id`. Is this code coming out, or are there other Sidekiq jobs I'm unaware of?
