### ISSUE TITLE
Investigate EVSS account creation in SSOe AfterLoginActions

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45359]
## Description
In SSOe authentication `AfterLoginActions` we queue up an EVSS job even before EVSS may be required. We may be able to queue the EVSS job less 

## Tasks
- [ ] Do we need to call EVSS `create_user_account` for every SSOe login?
  - [ ] can we obtain information needed (existing account) from MPI or SSOe identity headers?
- [ ] if EVSS needs to be called on every authentication, do we need to implement similar logic for SiS?

**Comment by bramleyjl** [comment]
```
irb(main):018:0> client.get_current_info
=> #<Faraday::Response:0x00005575eb7f6e60 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"cnp_address"=>{"bank_account_nbr"=>"", "bank_name"=>"", "bank_routing_nbr"=>"", "can_be_validated_by_group_one"=>false, "confirm_bank_account_nbr"=>"", "confirm_bank_routing_nbr"=>"", "corp_rec_found_ind"=>"N", "dd_eft"=>false, "direct_express"=>false, "done_with_group_one"=>false, "email_addr_exst_ind"=>"", "email_effective_date"=>"", "has_payment"=>false, "mail_addr_exst_ind"=>"N", "mail_address_country_code"=>"", "mail_address_effective_date"=>"", "mail_address_group_one_valid_address"=>false, "mail_address_street3"=>"", "mail_address_suggested_address_line1"=>"", "mail_address_suggested_city"=>"", "mail_address_suggested_state"=>"", "mail_address_suggested_zipcode"=>"", "mail_address_type"=>"ADDRESS_DOMESTIC", "masked_bank_account_number"=>"", "masked_bank_routing_number"=>"", "payment_address_city"=>"", "payment_address_country"=>"", "payment_address_country_code"=>"", "payment_address_effective_date"=>"", "payment_address_po"=>"", "payment_address_postal_code"=>"", "payment_address_state"=>"", "payment_address_street1"=>"", "payment_address_street2"=>"", "payment_address_street3"=>"", "payment_address_type"=>"", "payment_address_zipcode"=>"", "payment_information_filled"=>false, "payments_received_ind"=>false, "phone_num_exst_ind"=>"N", "phone_number_filled"=>false, "primary_phone_area_nbr"=>"", "primary_phone_effective_date"=>"", "primary_phone_ext_nbr"=>"", "primary_phone_nbr"=>"", "pymnt_addr_exst_ind"=>"N", "secondary_ext_nbr"=>"", "secondary_phone_area_nbr"=>"", "secondary_phone_effective_date"=>"", "secondary_phone_nbr"=>"", "secondary_phone_number_filled"=>false, "veteran_name"=>"Mark Polarbear"}, "info"=>{"bank_account_nbr"=>"", "bank_name"=>"", "bank_routing_nbr"=>"", "can_be_validated_by_group_one"=>false, "confirm_bank_account_nbr"=>"", "confirm_bank_routing_nbr"=>"", "corp_rec_found_ind"=>"N", "dd_eft"=>false, "direct_express"=>false, "done_with_group_one"=>false, "email_addr_exst_ind"=>"", "email_effective_date"=>"", "has_payment"=>false, "mail_addr_exst_ind"=>"N", "mail_address_country_code"=>"", "mail_address_effective_date"=>"", "mail_address_group_one_valid_address"=>false, "mail_address_street3"=>"", "mail_address_suggested_address_line1"=>"", "mail_address_suggested_city"=>"", "mail_address_suggested_state"=>"", "mail_address_suggested_zipcode"=>"", "mail_address_type"=>"ADDRESS_DOMESTIC", "masked_bank_account_number"=>"", "masked_bank_routing_number"=>"", "payment_address_city"=>"", "payment_address_country"=>"", "payment_address_country_code"=>"", "payment_address_effective_date"=>"", "payment_address_po"=>"", "payment_address_postal_code"=>"", "payment_address_state"=>"", "payment_address_street1"=>"", "payment_address_street2"=>"", "payment_address_street3"=>"", "payment_address_type"=>"", "payment_address_zipcode"=>"", "payment_information_filled"=>false, "payments_received_ind"=>false, "phone_num_exst_ind"=>"N", "phone_number_filled"=>false, "primary_phone_area_nbr"=>"", "primary_phone_effective_date"=>"", "primary_phone_ext_nbr"=>"", "primary_phone_nbr"=>"", "pymnt_addr_exst_ind"=>"N", "secondary_ext_nbr"=>"", "secondary_phone_area_nbr"=>"", "secondary_phone_effective_date"=>"", "secondary_phone_nbr"=>"", "secondary_phone_number_filled"=>false, "veteran_name"=>"Mark Polarbear"}, "user_poa_info_available"=>true} @url=#<URI::HTTPS https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4431/wss-common-services-web-11.6/rest/vsoSearch/11.6/getCurrentInfo> @request=#<Faraday::RequestOptions timeout=15, open_timeout=15, write_timeout=15> @request_headers={"va_eauth_csid"=>"DSLogon", "va_eauth_authenticationmethod"=>"DSLogon", "va_eauth_pnidtype"=>"SSN", "va_eauth_assurancelevel"=>"3", "va_eauth_firstName"=>"Mark", "va_eauth_lastName"=>"Polarbear", "va_eauth_issueinstant"=>"2023-01-05T21:39:05Z", "va_eauth_dodedipnid"=>"1013590059", "va_eauth_birlsfilenumber"=>"796104437", "va_eauth_pid"=>"13367440", "va_eauth_pnid"=>"141557840", "va_eauth_birthdate"=>"1950-10-04T00:00:00+00:00", "va_eauth_authorization"=>"{\"authorizationResponse\":{\"status\":\"VETERAN\",\"idType\":\"SSN\",\"id\":\"141557840\",\"edi\":\"1013590059\",\"firstName\":\"Mark\",\"lastName\":\"Polarbear\",\"birthDate\":\"1950-10-04T00:00:00+00:00\"}}", "va_eauth_authenticationauthority"=>"eauth", "va_eauth_service_transaction_id"=>"vagov-3b6f0df3-18e5-4224-ac66-190ab36b5f67", "User-Agent"=>"Faraday v0.17.5", "Content-Type"=>"application/json", "Content-Length"=>"0"} @ssl=#<Faraday::SSLOptions verify=true, ca_file="/etc/pki/ca-trust/source/anchors/va.pem", client_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=staging.vets.gov,O=vets.gov>, issuer=#<OpenSSL::X509::Name CN=vets.gov,O=vets.gov>, serial=#<OpenSSL::BN:0x00005575eb7cf1a8>, not_before=2016-09-16 03:00:44 UTC, not_after=2026-09-14 03:00:44 UTC>, client_key=#<OpenSSL::PKey::RSA:0x00005575eb821868>, version=:TLSv1_2> @response=#<Faraday::Response:0x00005575eb7f6e60 ...> @response_headers={"date"=>"Thu, 05 Jan 2023 21:44:52 GMT", "server"=>"Apache", "strict-transport-security"=>"max-age=31536000 ; includeSubDomains", "cache-control"=>"no-cache, no-store, max-age=0, must-revalidate", "pragma"=>"no-cache", "content-type"=>"application/json", "expires"=>"0", "x-content-type-options"=>"nosniff", "x-xss-protection"=>"1; mode=block", "x-frame-options"=>"DENY", "via"=>"1.1 pint.ebenefits.va.gov:444", "vary"=>"Accept-Encoding,User-Agent", "content-encoding"=>"gzip", "x-ua-compatible"=>"IE=Edge", "content-length"=>"524"} @status=200 @reason_phrase="OK" @custom={:duration=>2024.286809}>>
```

```
irb(main):018:0> client.get_rating_info
=> #<EVSS::DisabilityCompensationForm::RatingInfoResponse:0x00005575f476b6b8 @disability_decision_type_name="Service Connected", @service_connected_combined_degree=100, @user_percent_of_disability=100, @status=200, @metadata={}, @errors_hash={}, @original_attributes={:status=>nil, :disability_decision_type_name=>"Service Connected", :service_connected_combined_degree=>100, :user_percent_of_disability=>100}>
```

```
irb(main):020:0> client.create_user_account
=> #<Faraday::Response:0x00007f26f94994a0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"last_login_time"=>1672954745000, "user_account_id"=>105953} @url=#<URI::HTTPS https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4431/wss-common-services-web-11.6/rest/persistentPropertiesService/11.6/createUserAccount> @request=#<Faraday::RequestOptions timeout=15, open_timeout=15, write_timeout=15> @request_headers={"va_eauth_csid"=>"DSLogon", "va_eauth_authenticationmethod"=>"DSLogon", "va_eauth_pnidtype"=>"SSN", "va_eauth_assurancelevel"=>"3", "va_eauth_firstName"=>"Mark", "va_eauth_lastName"=>"Polarbear", "va_eauth_issueinstant"=>"2023-01-05T21:39:05Z", "va_eauth_dodedipnid"=>"1013590059", "va_eauth_birlsfilenumber"=>"796104437", "va_eauth_pid"=>"13367440", "va_eauth_pnid"=>"141557840", "va_eauth_birthdate"=>"1950-10-04T00:00:00+00:00", "va_eauth_authorization"=>"{\"authorizationResponse\":{\"status\":\"VETERAN\",\"idType\":\"SSN\",\"id\":\"141557840\",\"edi\":\"1013590059\",\"firstName\":\"Mark\",\"lastName\":\"Polarbear\",\"birthDate\":\"1950-10-04T00:00:00+00:00\"}}", "va_eauth_authenticationauthority"=>"eauth", "va_eauth_service_transaction_id"=>"vagov-3b6f0df3-18e5-4224-ac66-190ab36b5f67", "User-Agent"=>"Faraday v0.17.5", "Content-Type"=>"application/json", "Content-Length"=>"0"} @ssl=#<Faraday::SSLOptions verify=true, ca_file="/etc/pki/ca-trust/source/anchors/va.pem", client_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=staging.vets.gov,O=vets.gov>, issuer=#<OpenSSL::X509::Name CN=vets.gov,O=vets.gov>, serial=#<OpenSSL::BN:0x00007f26f9494798>, not_before=2016-09-16 03:00:44 UTC, not_after=2026-09-14 03:00:44 UTC>, client_key=#<OpenSSL::PKey::RSA:0x00005575eb821868>, version=:TLSv1_2> @response=#<Faraday::Response:0x00007f26f94994a0 ...> @response_headers={"date"=>"Thu, 05 Jan 2023 21:47:45 GMT", "server"=>"Apache", "strict-transport-security"=>"max-age=31536000 ; includeSubDomains", "cache-control"=>"no-cache, no-store, max-age=0, must-revalidate", "pragma"=>"no-cache", "content-length"=>"65", "content-type"=>"application/json", "expires"=>"0", "x-content-type-options"=>"nosniff", "x-xss-protection"=>"1; mode=block", "x-frame-options"=>"DENY", "via"=>"1.1 pint.ebenefits.va.gov:444", "vary"=>"User-Agent", "x-ua-compatible"=>"IE=Edge"} @status=200 @reason_phrase="OK" @custom={:duration=>643.6549070000001}>>
```

**Comment by bramleyjl** [comment]
Traditional EVSS requirement attributes: edipi.present? && ssn.present? && participant_id.present?

**Comment by bramleyjl** [comment]
#evss_devs chat: https://dsva.slack.com/archives/C1VBAHWQL/p1672955835860989

**Comment by bramleyjl** [comment]
This changed caused errors from [queued `CreateAccountJob`s in Sidekiq](http://sentry.vfs.va.gov/organizations/vsp/issues/?project=3&query=is%3Aunresolved+CreateUserAccountJob&statsPeriod=14d). The backup of re-failing jobs [was detected and resolved](https://dsva.slack.com/archives/CSFV4QTKN/p1674048391842449); I'll check the Sentry logs again in 24 hours to confirm that the problem has been completely resolved.
