### ISSUE TITLE
Create a User Flow Diagram for "View Dependents" Screen

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4536]
## Goal
Present viable options of various user flows within VA.gov to the proposed "View Dependents" page. Outline suggested inbound links from VA.gov to proposed "Dependents" screen.

## Tasks
- [x] Research existing VA.gov content pages, including authenticated pages
- [x] Create diagram illustrating various user flows
- [x] Consult with other VSA/VSP teams/members for input and/or validation 

## Acceptance Criteria
- [x] Create a high-level thumbnail view of various user flows to the proposed "View Dependents" page; present to IA for feedback and/or approval

## Next Steps
- Incorporate feedback
- Consider any frontend changes
- Discuss unauthenticated page with **vsa-public-websites**

**Comment by sporeboy** [comment]
Researched VA.gov for potential inbound links to "View Dependents" page. Candidates include:

VA.gov Home / included with Disability links / goes to unauthenticated state or landing page
Mega dropdown / under Get disability benefits / goes to unauthenticated state or landing page 
MyVA / in section "Manage benefits of request records"
VA.gov/disability/add-remove-dependent
VA.gov/disability/eligibilty
VA.gov/disability/how-to-file-claim
VA.gov/disability/

**Comment by sporeboy** [comment]
Outbound links from the View Dependents page:

Home
VA.gov/disability/add-remove-dependent
VA.gov/disability/get-help-filing-claim
www.eBenefits.VA.gov/ebenefits/about/feature?feature=dependent-compensation

**Comment by sporeboy** [comment]
![View_Dependents_User_Paths_1.png](https://images.zenhubusercontent.com/5d6ec7967521390001c3e794/17a5b36c-55a4-43da-8c41-dd92152f614c)
