### ISSUE TITLE
Discovery: Review long running jobs to identify potential issues

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45360]
- [x] EVSS group contact Rachal can provide: Rachal did this, "Mark"
- Mark Viterna has helped with VBADocuments::UploadStatusUpdater issues

## Description
Look for potential issues in long running jobs. eg EVSS

## Tasks
- [ ] Investigate long running EVSS sidekiq jobs

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by npeterson54** [comment]
Removing from Console Services

**Comment by joeniquette** [comment]
@npeterson54 I assume your removing this because sidekiq was determined to not be an issue for our vets-api latency discovery?

**Comment by rjohnson2011** [comment]
### Discovery Findings

There were **52** sidekiq jobs that took over an hour to run in the past week, which contains a total of 5 different jobs.

Of these, **EVSS::DocumentUpload** takes the top spot for the longest running job at 3 hours 39 minutes, and occurred a total of 14 times.

The 2nd longest running job is **EVSS::DisabilityCompensationForm**, which came a close second at 3 hours 14 minutes, and had a total of 18 instances taking over an hour to run.

Another serious offender is the **BGS::SubmitForm686cJob**, taking up to 2 hours 50 minutes to run, with a total of 12 instances.

*Together, these top three sidekiq jobs account for 85% of the longest running jobs in the past week.*

Rounding out the final 1 hour+ process jobs is **VRE::Submit1900Job** (6 instances, up to 2 hours) and **SubmitForm674Job** (5 instances, up to 1 hour 51 mins).


#### Source
https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aproduction%20service%3Avets-api-sidekiq%20%40duration%3A%3E%3D30s&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanType=service-entry&start=1664808365737&end=1665413165737&paused=false


> Oct 05 02:05:42.117	vets-api-sidekiq	EVSS::DocumentUpload	3 h 39 min	
Oct 05 02:26:31.463	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	3 h 14 min	
Sep 30 18:05:14.010	vets-api-sidekiq	BGS::SubmitForm686cJob	2 h 50 min	
Oct 05 01:31:50.739	vets-api-sidekiq	EVSS::DocumentUpload	2 h 46 min	
Oct 04 02:34:46.062	vets-api-sidekiq	EVSS::DocumentUpload	2 h 44 min	
Sep 30 18:05:01.112	vets-api-sidekiq	BGS::SubmitForm686cJob	2 h 39 min	
Oct 06 13:51:10.880	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	2 h 28 min	
Oct 06 12:05:42.197	vets-api-sidekiq	BGS::SubmitForm686cJob	2 h 14 min	
Oct 06 12:06:15.501	vets-api-sidekiq	BGS::SubmitForm686cJob	2 h 7 min	
Sep 30 18:05:50.192	vets-api-sidekiq	BGS::SubmitForm686cJob	2 h 6 min	
Oct 04 14:59:30.513	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	2 h 6 min	
Sep 30 18:03:24.242	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitForm526AllClaim	2 h 3 min	
Oct 06 12:04:21.821	vets-api-sidekiq	VRE::Submit1900Job	2 h 0 min	
Oct 06 00:43:14.781	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	2 h 0 min	
Oct 06 12:04:21.711	vets-api-sidekiq	VRE::Submit1900Job	1 h 59 min	
Oct 06 12:06:16.291	vets-api-sidekiq	BGS::SubmitForm674Job	1 h 51 min	
Sep 30 18:03:56.468	vets-api-sidekiq	VRE::Submit1900Job	1 h 43 min	
Oct 06 12:05:50.936	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 41 min	
Sep 30 18:05:11.880	vets-api-sidekiq	BGS::SubmitForm674Job	1 h 40 min	
Sep 30 18:05:22.623	vets-api-sidekiq	BGS::SubmitForm674Job	1 h 40 min	
Oct 06 12:06:16.400	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 40 min	
Sep 30 18:05:10.744	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 40 min	
Sep 30 18:03:56.783	vets-api-sidekiq	VRE::Submit1900Job	1 h 34 min	
Oct 05 04:25:37.996	vets-api-sidekiq	EVSS::DocumentUpload	1 h 31 min	
Sep 30 18:06:03.934	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 24 min	
Oct 06 04:43:57.932	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 23 min	
Sep 30 18:05:55.464	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 22 min	
Oct 03 14:35:16.101	vets-api-sidekiq	EVSS::DocumentUpload	1 h 22 min	
Oct 02 22:39:53.298	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 21 min	
Sep 30 18:05:14.030	vets-api-sidekiq	BGS::SubmitForm674Job	1 h 19 min	
Sep 30 18:05:18.750	vets-api-sidekiq	BGS::SubmitForm686cJob	1 h 19 min	
Oct 02 22:42:18.561	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 18 min	
Oct 06 12:04:12.279	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitForm526AllClaim	1 h 18 min	
Oct 06 12:04:19.080	vets-api-sidekiq	VRE::Submit1900Job	1 h 17 min	
Oct 02 22:35:01.942	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 15 min	
Oct 06 12:04:12.276	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitForm526AllClaim	1 h 15 min	
Oct 05 05:23:32.095	vets-api-sidekiq	EVSS::DocumentUpload	1 h 14 min	
Oct 04 20:17:27.659	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 13 min	
Oct 05 23:19:36.886	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 12 min	
Oct 05 05:58:25.771	vets-api-sidekiq	EVSS::DocumentUpload	1 h 10 min	
Oct 05 07:45:25.768	vets-api-sidekiq	EVSS::DocumentUpload	1 h 9 min	
Oct 03 21:17:45.566	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 8 min	
Oct 03 21:01:06.520	vets-api-sidekiq	EVSS::DocumentUpload	1 h 8 min	
Oct 05 21:03:15.817	vets-api-sidekiq	EVSS::DocumentUpload	1 h 8 min	
Oct 03 20:59:29.358	vets-api-sidekiq	EVSS::DocumentUpload	1 h 4 min	
Sep 30 16:08:36.017	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 4 min	
Oct 05 11:16:07.998	vets-api-sidekiq	EVSS::DocumentUpload	1 h 3 min	
Oct 03 22:05:26.522	vets-api-sidekiq	EVSS::DocumentUpload	1 h 3 min	
Sep 30 16:06:56.878	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 2 min	
Oct 03 21:13:36.775	vets-api-sidekiq	EVSS::DocumentUpload	1 h 0 min	
Oct 05 10:08:09.860	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 0 min	
Oct 01 01:19:42.476	vets-api-sidekiq	EVSS::DisabilityCompensationForm::SubmitUploads	1 h 0 min

**Comment by rjohnson2011** [comment]
Closing this ticket out to focus on additional tickets involving individual long-running jobs.
