### ISSUE TITLE
Perform audit for Sign in components (screen readers)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#45368]
## Issue Description
Conduct research into the current accessibility of VA.gov in relation to the difficulty of signing in with a screen reader.  [Another research study uncovered issues with screen readers and users authenticating](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/research/findings-summary.md) on VA.gov while researching the Profile page.

## Tasks
- [ ] Conduct preliminary accessibility scans using WAVE & AxE Developer Tools for an audit of the Identity components
- [ ] Speak with UX about the above findings to see if more research is required
- [ ] Create tickets from UX & A11y findings

## Acceptance Criteria
- [ ] An epic is created to for accessibility issues for VA.gov

**Comment by joeniquette** [comment]
will come back to this after other tasks completed.
