### ISSUE TITLE
FE | Auth Profile | BAI | Update UI

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45366]
## Background

Based on the research sessions we decided to make some slight changes to the UI and content to improve user's experience, particularly if the address shown is correct and they just need to "confirm".

**Note**   we are awaiting guidance on focus behavior (see ticket #45002 for specifics) and will update this ticket once feedback has been provided by accessibility folks.

Additionally, a second ticket to update the content will be created since that is not yet finalized.

## Tasks
- [ ] Update UI based on sketch file [here](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/v8jw5bQ) and [here (expanded version)](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/YG309Dv)
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Added final mocks with content.

**Comment by adamwhitlock1** [comment]
@SKasimow this is live in staging and I was able to see the new content

![Screen Shot 2022-08-16 at 11.31.26 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/11114834-657a-4573-8353-98db60676625)

**Comment by SKasimow** [comment]
@adamwhitlock1 - I confirmed as well using account #123; looks good!  Closing...
