### ISSUE TITLE
Create new VA.gov experience standard 11.23 Focus moves to the appropriate place after action.

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#45371]
## User Story
As a Governance team member, I want to make sure the VA.gov Experience Standards list is as accurate as possible so that when I find an issue during a Staging Review, I know what VA.gov Experience Standard it is in violation of and no longer have to use the "Other" category.

Assignee:
Peer Reviewer:

## Description
During the VA.gov experience standard "other" audit #43517, we discovered that we need to create new standards. This will allow us to map "other" issues to current standards.

## Impacted Artifacts
[VA.gov experience standard](https://vfs.atlassian.net/wiki/spaces/CC/pages/1683980311/VA.gov+experience+standards) 
Drafting template

## Tasks
- [ ] Create new standard (Assistive tech and device support 11.23 Focus moves to the appropriate place after action.)
- [ ] Check with accessibility for...
  - [ ] WCAG reference
  - [ ] Practice areas involved
  - [ ] Launch blocking
- [ ] Add new standard to...
  - [ ] Source of Truth
  - [ ] Copy of VA.gov Experience Standards (for team use)
  - [ ] VFS Facing: Platform Website
  - [ ] VFS Facing: Confluence
  - [ ] Drafting template
- [ ] Notify OCTO, share on #platform-collaboration-cycle Slack channel
- [ ] Update the labels on the ticket #30029, #43525, #43972:
  - remove label CCIssue00.00
  - add the appropriate new label CCIssue.XX.YYper VA.gov Experience Standards labels guidance
  - Update the Platform Issue section in the ticket with the appropriate new name per Platform Issue guidance
  - Comment on the ticket:
This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssueXX.YY "Name of issue". No VFS action is needed.

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] A new VA.gov experience standard 11.23 has been created and available to VFS/Governance teams
- [ ] Existing tickets assigned to the "other" category that now apply to the updated standard have been relabeled.

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.
