### ISSUE TITLE
[Development] Overseas military addresses: Update 526 disability form

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4537]
## User Story: 

As a person who lives on an overseas military base, I should not be able to list any other country besides the United States in my address in the VA.gov profile or on any VA benefit applications.

## Background:  

The authenticated experience team has made an update to the user profile that will allow for better error handling of overseas military base addresses ([details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4386#issuecomment-568466453)). This is the TL;DR: prior to the changes we made in the profile, all address forms on VA.gov allowed people to enter a country other than the United States if a person lives on an overseas military base even though US military bases are technically considered to be in the United States no matter where they are on the map. The updates we made to the profile allow a person to indicate they live on an overseas military base and prevent them from selecting a country other than the United States.

Our team recommends that similar updates be made to the address forms in each of the benefit applications. However, these application updates do not need to happen immediately, and the profile updates we made are not dependent on the benefit applications also being updated. Updates to the benefit applications can happen any time and can be triaged accordingly depending on the priority of other work.

## Design MockUps 

Below are the designs for how to adapt the address field for each benefit application. Please note:

1. The example shown is for the health care application. While each benefit application shows the address field at different points in the process, I believe all applications do have at least one address field. We will not be providing separate mockups for each individual application, so please let us know if you have specific questions about how our proposal would fit into your application.
2. If there is more than one address field in a benefit application, only the Mailing Address (or equivalent) field needs to be updated to match the designs below.

### Address field within the application

**UX**

- Add a checkbox to the mailing/permanent address field that allows people to indicate they live on an overseas military base.
- If the box is unchecked, the address form can be filled in normally and the UX doesn't change.
- However, if someone does check the box indicating they live on an overseas military base, we need to make the following updates: 
  - Default the Country field to "United States" and disable the Country menu so the user can not select another country.
  - Change "City" to "APO/FPO/DPO". This field remains required. The only options in this menu should be APO, FPO, DPO.
  - In the "State" menu, please remove all other states except Armed Forces America (AA), Armed Forces Europe (AE), and Armed Forces Pacific (AP).
  
**Copy**

- **Checkbox label**: I live on a United States military base outside of the United States
- **Helper text label**: Learn more about military base addresses
- **Helper text field**: The United States is automatically chosen as your country if you live on a military base outside of the country.

When the user arrives at the address page and they check the box indicating that they live on a US military base outside of the US, they will see this:

![Form 10-10EZ - outside US military base address 1](https://user-images.githubusercontent.com/53535009/70589522-e68c6f00-1b9d-11ea-99a0-2c018607e958.png)

Same screen with helper text visible:

![Form 10-10EZ - outside US military base address 2](https://user-images.githubusercontent.com/53535009/70589553-fb690280-1b9d-11ea-8b4a-fb06a40a5b1e.png)

### Review Application

If the benefit application you are working on has a Review Application page, the designs below outline how the address field would need to change to accomodate overseas military addresses.

When the user opens the Veteran Info section they will see this:

![Form 10-10EZ  Review step - accordion veteran info](https://user-images.githubusercontent.com/53535009/70590524-007b8100-1ba1-11ea-9357-2c01caa7d7d9.png)

When the user clicks the 'Edit' button for the Permanent address section to edit their address they will see this layout:

![Form 10-10EZ - veteran info edit](https://user-images.githubusercontent.com/53535009/70590410-9fec4400-1ba0-11ea-8bd7-d05230371e74.png)

## Tasks 

The steps that must be done by the team to complete the acceptance criteria 

- [ ] Review this ticket
- [ ] If necessary, meet with members of the authenticated experience team to answer any questions
- [ ] Implement address updates for 526 Disability application

## Acceptance Criteria: 

The requirements that must be met in order to mark this user story as completed 

- [ ]  Address section of the 526 Disability application has been updated to better handle APO/FPO/DPO addresses

**Comment by luke-gcio** [comment]
@erikphansen Thanks for taking one for the team and getting this done on your end.  Let us know when we can ctrl-v ctrl-c!

**Comment by ndsprinkle** [comment]
@luke-gcio This should be wrapped up to demo tomorrow, but I'd still like to spend some time verifying the form submits the proper data still.

**Comment by ndsprinkle** [comment]
@luke-gcio This is not completely ready for demo. There is still some missing functionality that I have been discussing with Erik and Robin to try to figure out what the issue is. The main issue deals with the conditional disabling of fields.

**Comment by ndsprinkle** [comment]
@luke-gcio A pull request has been created that currently implements all requested features. The PR has some failing tests, so those still need to be fixed. Additionally, I want to verify all data is still being sent appropriately to the back end considering a new field was added and a few had their values changed.

**Comment by ndsprinkle** [comment]
@luke-gcio The tests mentioned above have been fixed and various linting errors have also been corrected. I would also still like to add a new test or two for testing the newly added checkbox and functionality and still need to verify the data as mentioned above.

**Comment by ndsprinkle** [comment]
@luke-gcio All tests have been fixed/written and I have verified that the data submitted only contains the appropriate values. Once the PR is sent to the global front end team and approved, this ticket will be complete.
