### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45387]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the conversation guide for testing with users

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalized conversation guide to GitHub folder
