### ISSUE TITLE
Notification Letter | Adding notification letter link to CST landing page for logged in users

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45397]
## Value Statement
**_As a_** veteran who has submitted a claim, when I visit the CST
**_I want to_** see a link to the notification letter page on the very first page if I have a notification letter available to view
**_So that_**  I can click to the notification letter page and download the decision letter associated with that claim

---
## Background Context
We have reviewed our design approach with the Collaboration Cycle team. Design approach can be found [here](https://docs.google.com/presentation/d/1LyZbIS4at7bGCQv9cEQaTOiXypDpYqykl8c6j2FSMN0/edit?usp=sharing). 

## Acceptance Criteria
- [ ] Link is added when veteran has at least one notification letter available.
- [ ] Content language inviting users to click has been workshopped and reviewed with appropriate content teams
- [ ] Passes accessibility standards

## Designs and Build Notes
- @skylerschain please add here.

## Out of scope
- Add here

## Open questions

Will the call request to see if there are existing notifications  reduce application performance? If so, by how much? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
