### ISSUE TITLE
Feature Toggle Review/Refactoring

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45395]
## Description
We should revisit the current feature toggle implementation to see if there is any way to improve. Feature toggles currently utilize Redis (Elasticache) and see [~30,000 get commands per second](https://vagov.ddog-gov.com/screen/integration/149/aws-elasticache-redis?tpl_var_cluster_id=%2A&from_ts=1659963690347&to_ts=1659967290347&live=true) during business days/hours. This is due to the high number of calls to the `FeatureToggles#index` endpoint, which currently returns ALL feature toggles for a given request. 

### Background Information 
We should review this endpoint to see if there is any room for improvement. Currently the vets-website does not have any uniformity when it comes to feature toggle key names (some are snake_case and some are camelCase). Additionally, the index action returns ALL toggles due to an IE11 character limit ([See comments and PR](https://github.com/department-of-veterans-affairs/vets-api/pull/6645)). Do we even support IE11 anymore?

Other notes:
1. We currently have ~200 feature toggles. These should be reviewed for any "dead" toggles
2. The prod redis instance sees 30x more get commands than any of the other envs (due to feature toggle calls)
3. While reviewing vets-api latency issues, it doesn't appear that Redis calls are a factor. Elasticache supports up to 65k concurrent connections. 
4. See the [`FeatureToggles#index` APM board](https://vagov.ddog-gov.com/apm/resource/vets-api/rack.request/415c7727b5c3f8e1?query=env%3Aproduction%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22V0%3A%3AFeatureTogglesController%23index%22&env=production&maxPercentile=95&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&start=1659964490817&end=1659968090817&paused=false)
5. Does 1 query = 1 connection? If so, feature toggles hold about half of the connections for a given second if Elasticache can support 65k concurrent connections?

## Tasks
- [ ] Review Feature Toggles for improvements

## Acceptance Criteria
- [ ] TODO

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by RachalCassity** [comment]
Currently making a list of unused Feature Toggles

**Comment by RachalCassity** [comment]
[Feature Toggle Discovery ](https://vfs.atlassian.net/wiki/spaces/BTT/pages/2315878528/Feature+Toggle+Discovery)

**Comment by af-manish** [comment]
Story created for comparison too: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/46156

**Comment by joeniquette** [comment]
completed from the perspective of what can be done without engineer interaction.

@little-oddball @pjhill Thoughts on messaging teams that still have these around and are "still being called" but likely just need to be merged in as real code instead of feature toggle code? Probably should spin a new ticket for that.

**Comment by pjhill** [comment]
Based on Rachal's document, it looks like there are around 57 feature toggles that have valid routes. Are you discussing the idea of nudging teams to merge and remove those feature toggles? We would only want to nudge teams with particularly old feature toggles. I'm thinking this is a quality issue related to improper application of the SDLC that VA.gov proposes.

It should be quite doable to use the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) to reach out to the PMs responsible for each corresponding product and ask them to take action.

We may want to start by updating the [Feature toggles documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles), to indicate feature toggles should have a limited lifespan and maybe even propose a number for that limited lifespan like... 60 days.

**Comment by joeniquette** [comment]
Yea thats exactly what I was thinking Peter. Set a timeline of how long a toggle should live for, with the expectation that the code is now officially ready to be "permanent" and get rid of the flipper part of it. It should always only be seen as a temporary integration solution. 60 days seems fair to me. Anyone who currently has feature toggles over this time period I think we should message them and get them to modify their code to no longer depend on the feature toggle component of it.

**Comment by pjhill** [comment]
> @pjhill any updates on the "standard flipper timeline" work you planned to do? And any team reach out completed yet?

- Given the prioritization of QAS work toward the end of the team's existence, we were unable to make any headway on a playbook for handling this work or specifically address the list of aging feature toggles.
- Given the current list of communities of practice, I think that maybe the work of addressing a lack of clean-up in feature toggles would fall to the back-end COP.
- If in the future there is a quality assurance COP then I think a decent case could be made for the monitoring and clean-up of feature toggles to be a QA issue. I'm not sure how that work would be prioritized, but it seems reasonable that any QA COP members currently on the support team might be able to use the previously assembled list and a playbook to work on resolving the issues with some of these aging feature toggles.

**Comment by npeterson54** [comment]
Removing tech team 3 label

**Comment by rjain21** [comment]
Adding to Watchtower SRE Program board. Lets partner together if this becomes a priority.
