### ISSUE TITLE
Notification Letters | Listing Section

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45398]
## Value Statement
**_As a_** veteran who has submitted a claim
**_I want to_** have access to a specific section of va.gov that contains a list view of my notification letters
**_So that_**  I can know where to find my notification letters if I ever need them

---
## Background Context
We have reviewed our design approach with the Collaboration Cycle team. Design approach can be found [here](https://docs.google.com/presentation/d/1LyZbIS4at7bGCQv9cEQaTOiXypDpYqykl8c6j2FSMN0/edit?usp=sharing). 

## Acceptance Criteria

- [x] Conforms to approved designs 
- [x] Passes accessibility standards
- [x] Users able to see all of their decision letters in list view
- [x] Pagination is included when the list of Notifications is of considerable size
- [x] Decision letters sorted in reverse chronological order
- [x] All relevant [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Decision%20Letter%20Use%20Cases.md) tested

## Designs and Build Notes
- [Design file](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas) 
- PLEASE NOTE: This design is subject to change as we do another iteration in the next sprint. It should mostly be content and small visual tweaks, nothing major. But please keep that in mind. Also I will add more screens as needed. 
- Sam/Jerek: Let's discuss next week what you need for handoff and figure out the best process for that.

## Out of scope
- Add here

## Tasks
- [x]  Determine whether this functionality lives in letters app or in CST
- [x]  Understand what document types can be pulled from end point attributes
- [x]  Determine if we can identify decision letters only and narrow list to just those

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by skylerschain** [comment]
Added link to design files. 

PLEASE NOTE: This design is subject to change as we do another iteration in the next sprint. It should mostly be content and small visual tweaks, nothing major. But please keep that in mind. Also I will add more screens as needed. 

Sam/Jerek: Let's discuss next week what you need for handoff and figure out the best process for that.

**Comment by jacobworrell** [comment]
Feature toggles currently not working due to platform issues. This is a blocker for a staging deployment. 
Working to resolve a participant ID issue, @samcoforma to try and resolve error showing up in Sentry, will determine whether affected account is usable

@jacobworrell to create ticket for pagination
Also need an error message for people who try to access page who are unauthorized
