### ISSUE TITLE
[Research] Synthesize Research

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45390]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
Analyzing the videos and notes from [research study name] to create findings and design recommendations.

## Reference Materials
- Review [research checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/lead-researcher-checklist.md)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [ ] Decide on analysis methodology (affinity diagramming, etc.)
- [ ] Involve appropriate team members in analysis activity/meetings
- [ ] Review all participant session notes and videos
- [ ] Do analysis

## Acceptance Criteria
- [ ] Post synthesis documents to GitHub
- [ ] Write top-line summary (optional if daily summaries were sent out)
