### ISSUE TITLE
Design Intent Review of "Add Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4539]
## Goal
Present "View Dependents" screen layout to Design community.

## Task
- [ ] Schedule time with **Shawna, Jennifer Strickland, **and** Emily W.** for review and feedback of  latest mockup for the "View Dependents." 
- [ ] Gather and incorporate feedback to ensure consistent application of design system components. Troubleshoot potential design/development related issues. 
- [ ] Communicate concerns regarding design/research constraints or roadblocks.
- [ ] Upload buttons (2) are included

## Acceptance Criteria
- [ ] Scheduled for _________: conduct review session with **Shawna, Jennifer Strickland, **and** Emily W.**

## Next Steps
- [ ] Incorporate feedback and prepare another presentation as needed.

**Comment by sporeboy** [comment]
Currently refining screen layouts to address:

- Combined workflows/radio button strategy
- Condensed 'location' fields (country/city, state/county, state/city, country/county)
- Upload buttons/feature in workflows requiring documentation

**Comment by sporeboy** [comment]
The Platform review process is under revision: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md#designreviews

Per this outline, we should Slack Emily W and Crystabel R (done!) to schedule a design intent review. If this is not per the latest process, I will create a ticket to get the review scheduled.

**Comment by sporeboy** [comment]
The XD intended for review: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/
