### ISSUE TITLE
Notification Letters Page

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45399]
## Value Statement
**_As a_** veteran who has submitted a claim, when I navigate to the Navigation Letter section of CST
**_I want to_** be able to see a list of all Notification Letters for claims I've submitted sorted in reverse chronological order
**_So that_**  I can determine which file is likely the one I need to download for the purposes of providing the information to representatives

---
## Background Context
We have reviewed our design approach with the Collaboration Cycle team. Design approach can be found [here](https://docs.google.com/presentation/d/1LyZbIS4at7bGCQv9cEQaTOiXypDpYqykl8c6j2FSMN0/edit?usp=sharing). 

## Acceptance Criteria
- [ ] Notification Letter section exists on its own URL
- [ ] Conforms to approved designs 
- [ ] Notification Letters sort in reverse chronological order
- [ ] All notification letters in a veteran's e-folder are visible to the end users
- [ ] Passes accessibility standards
- [ ] Configure google analytics to track events

## Designs and Build Notes
- @skylerschain please add here.

## Out of scope
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
