### ISSUE TITLE
Notification Letters | Link to notification letter page from claims details

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45401]
## Value Statement
**_As a_** veteran who has at least one open claim, when I navigate to the claims details view for a claim
**_I want to_** be provided a link to the notification's letter page 
**_So that_**  I can click to the notification letter page and download the decision letter associated with that claim.

---
## Background Context
We have reviewed our design approach with the Collaboration Cycle team. Design approach can be found [here](https://docs.google.com/presentation/d/1LyZbIS4at7bGCQv9cEQaTOiXypDpYqykl8c6j2FSMN0/edit?usp=sharing). 

## Acceptance Criteria
- [x] Link is added to claims details for any claim as long as veteran has at least one notification for any claim available
- [x] If there is no notification letter available for any claim, a link to the notification's letter page does not appear. 
- [x] Content language inviting users to click has been workshopped and reviewed with appropriate content teams
- [x] Passes accessibility standards

## Designs and Build Notes
- @skylerschain please add here.

## Out of scope
- We cannot tie specific claims to specific letters at this time.

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
