### ISSUE TITLE
[Research] Create Research Plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45406]
## Questions
- Will this be moderated or not?

## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria
- [x] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalize research plan to GitHub folder

**Comment by kristenmcconnell** [comment]
Started a [draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/appointment-info-hierarchy/research-plan.md) based off of an unmoderated card sort completed by the Mobile App team.

**Comment by kristenmcconnell** [comment]
Sent out for [review](https://dsva.slack.com/archives/C02GXKL8WM6/p1660936504835519) by the check-in UX group first. @loripusey Let me know if you have feedback as well. Will send to Stephen after I get feedback from everyone else.

**Comment by loripusey** [comment]
@kristenmcconnell Study looks good, let me know when the surveys are ready to review.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell looks good, nice work. Couple comments to consider: 

- Research Goals - Might be beneficial to mention which fields are new vs. existing. Although, doesn't really matter for the purpose of this research. 
- Research Goals - For clarity, "Ultimately, we would like to determine what appointment data as well as the hierarchy of the data displayed within day of check-in and pre-check-in." Maybe try, "Ultimately, we would like to determine what appointment data is important to Veterans and how they rank its important relative to each data point." I think it was just missing something referencing Veterans.  
- Research Questions - Should we add a scenario for cancelled appointments? I don't think we need to. What you have is thorough enough. 
- Methods + Tools - Do Veterans have to complete all 4 scenarios? 
- There's a couple mentions of card sort through out. Is this a card sort or a survey? Maybe worth updating.

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 Regarding cancelled appointments, I'm going to look at VAOS's old studies on cancelled appointments. For now, I believe that it might be enough to evaluate canceled appointments as a status within the 4 main scenarios. Depending upon what I find during my review, I could see my mind changing and 2 canceled scenarios being added.

You ask a good question about if we need to show all 4 scenarios to every Veteran. I was going to set up the survey, try it out, and see how long it really is. Based upon that, I'll adjust our recruiting numbers and might break apart check-in and pre-check-in, so one Veteran answers questions about 2 scenarios. I'm just a little worried about doing that (if it isn't necessary), because it would mean recruiting 126 participants for this study to get 60 completes (30 per study).

I updated the plan with all of your other suggestions. They were great. Thank you.

**Comment by kristenmcconnell** [comment]
Moved the research folder due to new guidelines from research ops: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2022-08-appointment-info-hierarchy
