### ISSUE TITLE
[Research] Create Recruitment Email

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45407]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the recruitment email for conducting an unmoderated study with users

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create recruitment email 

## Acceptance Criteria
- [x] Review recruitment email with team (particularly product, Kristen, and Patrick)
- [x] ~~Hand off finalized recruitment email to Perigean~~ I will do this after the survey is actually created, so I'll count it in the survey ticket.

**Comment by kristenmcconnell** [comment]
Since the study will be unmoderated, this ticket mainly deals with creating a recruitment email and not a conversation guide.

**Comment by loripusey** [comment]
Updated title & description to reflect that this is to create a recruitment email

**Comment by kristenmcconnell** [comment]
I created a draft [email](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/veteran-facing/appointment-info-hierarchy/recruitment-email.md) based off of Cindy Merrill's previous work. However, I started to think about how Perigean was going to use this email to recruit while also successfully identifying which cohort a participant belongs in. I talked to Cindy. Apparently, she was under the impression that cohorts had to be defined based on potential participants’ responses to specific questions in Perigean’s/OCTO-DE’s recruitment survey. I had planned on different cohorts that don't exist in that survey, such as have you had a medical appointment within the last 12 months and check-in preference. I now need to reach out to research-ops to find out if Perigean will recruit for the types of co-horts that I imagined.

**Comment by kristenmcconnell** [comment]
Started this [Slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1661536553534509?thread_ts=1661201089.995819&cid=C0216PL32HJ) with research ops about the use of screener questions within unmoderated studies. I also asked if these emails are needed if Perigean allows additional screener questions anyway. If they allow for the additional screener questions, then it should be the same process as remote studies and we shouldn't need to create these emails.

**Comment by kristenmcconnell** [comment]
I moved this [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2022-08-appointment-info-hierarchy) due to new guidance from research ops. I also slightly updated the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-08-appointment-info-hierarchy/research-plan.md) based upon my conversation with research ops. I found out that you can create your own screener groups within the recruitment email(s); otherwise, you must use the information from the sign-up questionnaire to create your cohorts. Therefore, I changed some of our cohorts. With these changes to the research plan, we only needed one [recruitment email](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-08-appointment-info-hierarchy/recruitment-email.md). All of this is ready for review, @benbrasso-agile6 and @loripusey.

I will also be providing research ops with some feedback, because I updated our research plan to their template and ran into some questions.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell looks all good to me. Thanks!

Couple comments about the email:

Can they populate the person's name in "Hello {name},"

Wonder if we need something that says, "on your desktop or smartphone," within the sentence below: 

The VA.gov team at the Department of Veterans Affairs is conducting research to learn what appointment information, such as provider name or clinic address, is most important to you when checking in for a medical appointment or completing pre-check-in prior to your appointment.

Instead of "interested" in the sentence below, maybe change to something like, "You must also be willing to participate in our online survey..."

You must also be interested in participating in an online survey to help us understand your preferences.

For the following sentence, might want to include a cut off date. E.g., complete by XX or at your earliest convenience. 

The survey should take you about 15 minutes to complete on your computer, tablet, or smartphone. You can do it whenever it's convenient for you.

Do they know how much the gift card is? If not, I'd maybe recommend we say how much it is.

**Comment by kristenmcconnell** [comment]
Besides those items, I updated the recruitment email with your suggestions, Ben. Thanks.

**Comment by kristenmcconnell** [comment]
Slack message to [research ops](https://dsva.slack.com/archives/C0216PL32HJ/p1661971500798439) again
