### ISSUE TITLE
[PM] Onsite Notifications: Prepare for & Complete Staging Review

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45417]
## Background
Need to prep for and complete staging review

## Tasks
- [x] Gather artifacts
- [x] Submit [request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D)
- [x] Create tasks as needed to address any follow up items

## Acceptance Criteria
- [x] Staging review is scheduled and completed

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ NA
- _How can this work be validated?_ NA

## Resources
- [Background info on staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) _Note: we started this initiative prior to May 26 2022 which is the cutoff for switching to the new/current collab cycle request format_

**Comment by ericasauv09** [comment]
Submitted #45610. Updating artifacts

**Comment by ericasauv09** [comment]
Staging Review scheduled for 9/1

**Comment by ericasauv09** [comment]
Platform created 4 tickets based on Staging review feedback. None are blockers for go live.
