### ISSUE TITLE
[PM] Onsite Notifications: Prepare for & Complete Privacy Review

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45418]
## Background
Need to prep for and complete privacy and security review

## Tasks
- [x] Gather artifacts
- [x] Submit [request](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [x] Create tasks as needed to address any follow up items

## Acceptance Criteria
- [x] Privacy and security review is complete

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ NA
- _How can this work be validated?_ NA

## Resources
- [Background info on privacy review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)

**Comment by ericasauv09** [comment]
Submitted [#547](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/547), Tom is filling out BE questions

**Comment by ericasauv09** [comment]
Closing as privacy team had no security concerns
