### ISSUE TITLE
[PM] My VA Redirect: Submit QA Request

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45419]
## Background
Before we can proceed with launching the Redirect we need to submit a [QA request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=QA%2C+PTEMS%2C+qa-test-plan&template=ptems-qa-test-plan.md&title=%5BProduct%2FFeature%5D+PTEMS-QA+Test+Plan) to Tze so he can conduct QA for us.

## Tasks
- [x] Fill out [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=QA%2C+PTEMS%2C+qa-test-plan&template=ptems-qa-test-plan.md&title=%5BProduct%2FFeature%5D+PTEMS-QA+Test+Plan) and submit
- [x] Coordinate/work with Tze on any additional questions or artifacts he needs

## Acceptance Criteria
- [x] Tze has all the artifacts and information he needs to begin QA on the My VA Redirect feature

**Comment by ajakabcin** [comment]
test cases are [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-my-va-redirect.md) and ticket submitted - #45450
