### ISSUE TITLE
Translation work for new Novavax content on COVID-19 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45423]
## Issue Description
We added content on our main [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) and [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) pages. We sent this content to the translation team and will need to update our Spanish and Tagalog pages when they are sent back.

Note that in some places we removed content rather than needed new translations so we'll need to make sure we remove that content from the updated pages. 

Attaching here the docs that we worked off of for the English changes so we can refer to them for any sentences that were removed.

[https://app.zenhub.com/files/133843125/ec3314ac-1998-4cb6-8670-e136747c5949/download](https://app.zenhub.com/files/133843125/ec3314ac-1998-4cb6-8670-e136747c5949/download)

[https://app.zenhub.com/files/133843125/04d24dff-50ce-41cd-8e4e-f414f8891bf2/download](https://app.zenhub.com/files/133843125/04d24dff-50ce-41cd-8e4e-f414f8891bf2/download)

## Tasks
- [x] Update main vaccine page in Spanish (Aliyah)
- [x] Update main vaccine page in Tagalog (Aliyah)
- [x] Update About vaccines page in Spanish (Aliyah)
- [x] Update About vaccines page in Tagalog (Aliyah)
- [x] Review and publish main vaccine page in Spanish (Megan)
- [x] Review and publish main vaccine page in Tagalog (Megan)
- [x] Review and publish About vaccines page in Spanish (Megan)
- [x] Review and publish About vaccines page in Tagalog (Megan)

## Acceptance Criteria
- [x] Main vaccine page is live with changes in Spanish and Tagalog
- [x] About vaccines page is live with changes in Spanish and Tagalog

**Comment by aliyahblackmore** [comment]
Update 8/12: Started on this today, almost done with the "Vacunas contra COVID-19 en el VA" page!

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! The COVID-19 Vaccines at VA page is ready for you! 
Preview link: 

**A few notes and flags:** 

1. I noticed on the live English page that in the accordion "Which Veterans are eligible for a vaccine?" that this sentence is different from what is on the [doc sent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45423#issue-1332205650) to the translator and, as a result, what is in the Spanish translation:

 _**This also includes Veterans who live or travel outside of the U.S. and are eligible for the VA Foreign Medical Program. 

[Learn more about the VA Foreign Medical Program](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp)**_

The Spanish is the following:

**Esto también incluye a los Veteranos que viven o viajan fuera de los Estados Unidos y son elegibles para el [Programa Médico Extranjero del VA (en inglés)](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp?_ga=2.51062817.928792723.1631552662-314929476.1617377368)** 

cc: @RLHecht is this a sentence that we should send back to the translator or okay to use Google translate?  We need to translate "[Learn more about the VA Foreign Medical Program](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp)" I looked for this earlier on the page and there is another bullet point for learning more about FMP but,  similarly, it hasn't been translated.  Later on the page there is "Learn more," (Más información) so can swap out and adjust the translation if okay.

2. There were some small changes made to lower vs. upper case throughout the page, that weren't on the doc.
3. I removed an extra ")" that was in the H2 **"Quién puede recibir la vacuna COVID-19 en VA"**
4. Under accordion **"Dónde ofrecemos las vacunas COVID-19"** the links **"[Encuentre otros proveedores de vacunas en sus alrededores en el sitio web del buscador de vacunas de los CDC](https://www.vaccines.gov/)"** and "[Obtenga más información sobre cómo obtener la vacuna de la COVID-19 de un proveedor comunitario](https://www.va.gov/COMMUNITYCARE/providers/COVID-19_Guidance.asp?_ga=2.224321944.2024097743.1660579378-532203590.1658844127)" both lead to pages that are in English.  I added in "(en inglés)." 
5. Under the same accordion the link **"[Descargue nuestra tarjeta de información de facturación de farmacia (PDF)](http://efaidnbmnnnibpcajpcglclefindmkaj/https:/www.va.gov/COMMUNITYCARE/docs/programs/Pharmacy-Billing-Flyer.pdf)"** is also in English. Because we have "PDF" in parenthesis, wondering if there is style guidance for also including "(en inglés)" after?  I left without for the time being and happy to change if there is guidance/a suggestion here!
6. In the accordion **"Qué debe decirle a su proveedor de atención médica antes de recibir la vacuna de la COVID-19"** all of the links to fact sheets are also English pages/documents. Depending on guidance on having two parenthesis on a link (see question number 5), will change this!
7.  In the accordion **"Vacunas contra el COVID-19 actualmente disponible,"** on the live English page there are some new changes to this text. This was sent to the translators but is _not_ in the document that was sent back to us. Should we have this translated by them? cc: @RLHecht  For the time being, I edited the age requirements based on the current text pattern. We still need to translate **"The Janssen vaccine is only recommended for people unable to take the other COVID-19 vaccines."**

**Comment by aliyahblackmore** [comment]
Hi @megzehn the Spanish About COVID-19 Vaccines page is ready for you. 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=36461

I made the additions from the translated doc and also removed the accordion "Las vacunas son una forma importante de detener la propagación de nuevas variantes de coronavirus," as that is no longer on the live English page.

Will stand by for the Tagalog pages!

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! 

- I’ll echo your comments on nodeId=16359 that there were some missing translations at the end. It stopped at this line: “Visite el sitio web de los CDC para obtener más información sobre las vacunas de las COVID-19 y las reacciones alérgicas.” Thank you for improvising and finding those translations from other places in the text! 

- For node=34627, just a heads up that I didn’t see a translation for this minor tweak: “mRNA COVID-19 vaccines don’t change your DNA” (We added mRNA to the English version). Based on other translations, I’m thinking it might be “de las vacunas de la COVID-19 de ARNm,” but I didn’t want to add something that was wrong, so I left it as is for now. 

Otherwise, these are copyedited and look good to me. @RLHecht, let me know if they're good to go, and I'll get them published. 

Thank you!

**Comment by RLHecht** [comment]
@aliyahblackmore Here are the new translations for Tagalog as well as the missing Spanish and Tagalog ones. Thanks!
[https://app.zenhub.com/files/133843125/e389ae40-8ab3-42fb-81a9-51b62da8af26/download](https://app.zenhub.com/files/133843125/e389ae40-8ab3-42fb-81a9-51b62da8af26/download)

[https://app.zenhub.com/files/133843125/7fda5ca4-7b54-4807-8265-98af4f1c0042/download](https://app.zenhub.com/files/133843125/7fda5ca4-7b54-4807-8265-98af4f1c0042/download)

[https://app.zenhub.com/files/133843125/3eeff0ce-2dce-4942-9583-ac385e94ad10/download](https://app.zenhub.com/files/133843125/3eeff0ce-2dce-4942-9583-ac385e94ad10/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! Changes for both COVID-19 Spanish pages are ready for you!

[COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine-esp/)
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16359
**Note:** In the last accordion of the page "Qué hacer si recibe una vacuna COVID-19 fuera de VA" I removed [Puede enviar una foto de su tarjeta de registro de vacunación a su proveedor de VA a través de la mensajería segura (en inglés)](https://www.va.gov/health-care/secure-messaging)" as this is no longer on the live English page.

About COVID-19 Vaccines](https://www.va.gov/health-care/covid-19-vaccine-esp/about-covid-19-vaccine-esp/) 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=36461

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! The Tagalog COVID-19 vaccines at VA page is ready for you! Some notes/flags are included here.
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**### Notes and flags:**
1.	Similar to the Spanish page, on the English page accordion "Which Veterans are eligible for a vaccine?" there is a sentence that is different from what is on the [doc sent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45423#issue-1332205650) to the translator and, as a result, what is in the Tagalog translation:

"This also includes Veterans who live or travel outside of the U.S. and are eligible for the VA Foreign Medical Program.
[Learn more about the VA Foreign Medical Program](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp)"
The current Tagalog text is this:
Lahat ng Beterano (kabilang ang mga Beteranong nakatira o bumiyahe sa labas ng U.S. at karapat-dapat para sa [VA Foreign Medical Program (sa English)](https://www.va.gov/COMMUNITYCARE/programs/veterans/fmp/index.asp))
I went ahead and pulled “Learn more…” from another part of the page to edit this section. I also changed this in This link text also needed to be updated in H2 "Sino ang makakakuha ng bakuna laban sa COVID-19 sa VA.”
The new link text is: “Mas alamin ang sa VA Foreign Medical Program (sa English)”
This is something to flag for the QA review cc: Randi.
2.	Removed “[Maaari kayong magpadala ng litrato ng talaan ng bakuna sa inyong tagapangalaga sa VA sa pamamagitan ng garantisadong ligtas na mensahe (sa English)](http://preview-prod.vfs.va.gov/health-care/secure-messaging)” as this is no longer on the live English page.
3.	In the Featured Content box, I removed the text after “Latest Updates.” This wasn’t in the translation sent back to us, but I used google translated for this smaller change and to be sure I was deleting the correct words. CC: Randi, we can flag this when we send this over for the QA review!
4. “Second Booster Updates” didn’t come back in the translation. Just in following the pattern of language, it seems like it would be similar to  “Update sa pangunahing bakuna.” I left this as is on the page for the time being, but included this in the compiled word document and wondering if this may be something to flag for the translators. cc: @RLHecht 
5. In accordion “ Dapat ba akong magpabakuna para sa COVID-19 kung nagka-COVID-19 na ako?” added in “Yes.” I pulled this translation from another place on the page. Removed “Kung tumanggap kayo ng passive antibody therapy para gamutin ang COVID-19, kailangan ninyong maghintay nang hindi bababa sa 90 araw bago magpabakuna para sa COVID-19” as this is no longer on the live English page.
6. In the same accordion this was not translated in the document sent to us as this was recently added to the live English page: “Eligible adolescents ages 12 to 17 can now get a Moderna, Novavax, or Pfizer-BioNTech vaccine at VA facilities that provide these vaccines.”  The text on the current Tagalog live page includes Pfizer-BioNTech vaccine, so I included Moderna and Novavax and then pulled “o” from another part of the page for “or.” Randi sent this text to Jacob this afternoon and I flagged that I left in my change for the time being.
7. In this same accordion, “Ang mga bakunang Pfizer-BioNTech at Moderna ay ang tanging mga bakunang COVID-19 na awtorisadong gamitin sa mga kabataan sa ngayon,” was sent back to us in the translation, but this is no longer on the live English page. I am leaving this in for the time being. Randi sent over the new translation for the new sentence “Not all VA health facilities…” 
8. Under H2 How to get a COVID Vaccine at VA the live English page lists “The Moderna, Novavax, and Pfizer-BioNTech vaccines require 2 doses to be effective” in this order. In the translation the order is “Pfizer-BioNTech, Moderna, at Novavax.” Wondering if we should match the order in the translation (perhaps due to how it may be understood or grammar rules for Tagalog) or if we should match to what is on the live English page. I’ve left this to match the translation for the time being but this may be a question for the translation team! Cc: @RLHecht 
9. Removed the hyperlink from “Kung kayo ay nakalista sa pangangalaga ng kalusugan ng VA at magpupunta kayo sa isang lokasyon ng pangangalaga ng komunidad para magpabakuna para sa COVID-19, i-download ang aming pharmacy information card (PDF) (sa English)” and put it after the text to be in line with VA style/the live English page.
10. In the accordion “Ano ang sasabihin mo sa nangangalaga ng iyong kalusugan bago ka magpabakuna laban sa COVID-19” we got back this from the translator: [Fact sheet ng FDA Novavax COVID-19 na bakuna (PDF)](https://www.fda.gov/media/159898/download).  I noticed that there is a different text/language pattern for the other fact sheet links that already exist on the page. I went ahead and changed the other link text to match what we just received back from the translator for the Novavax link. I also noticed that the FDA Fact Sheet PDF (in Tagalog) is using “Fact Sheet” as well.  If this should be changed back let me know, cc: @RLHecht .  If not, maybe we should just flag this section for the translators and ask if using the same text for all links would work. 
11.	In the same accordion, we are missing translation of “ But you may be able to receive a different type of COVID-19 vaccine,” so this is missing for the time being.
12.	In the accordion “Mga kasalukuyang magagamit na bakuna laban sa COVID-19” the sentence “ The Janssen vaccine is only recommended for people unable to take the other COVID-19 vaccines” was not translated.  There is a similar sentence on the About COVID-19 vaccines page which I added in here, from the “About COVID-19 Vaccines” page. That sentence is “The Janssen (Johnson & Johnson) vaccine should only be an option for people who are unable to receive other COVID-19 vaccines.” Cc: @RLHecht wondering if we should have this translated to match the exact words on the live English page? “recommended” and “should only be an option” could have different meanings.
13.	In this same accordion, I updated “3” to “4” and changed the age for Novavax to “12.” The age requirement was recently updated on the live English page and was sent over the translator today. I am leaving this change in for the time being and will edit if sentence structure needs to change at all.
14.	The Novavax Fact sheet link included in the translation leads to an English page. I did a search online and found this FDA Novavax doc and included it. I just want to be sure that this is the link that we should use here. https://www.fda.gov/media/159898/download. This link was placed on two places on this page.  cc: Randi.
15.	In accordion “Ano ang aasahan mo matapos mabakunahan laban sa COVID-19” the links for the Fact sheets were pulled from earlier on this page. Again, I changed the link language to match the newest Tagalog translation for the Novavax fact sheets, for consistency.
16.	In accordion “Ano ang gagawin kung ikaw ay nabakunahan laban sa COVID-19 sa labas ng VA” I added in Novavax  in sentence “Dapat ninyong malaman na kahit Pfizer-BioNTech o Moderna na bakuna ang natanggap ninyo, kailangan ninyo ng 2 dosis.” I matched the list order to what is on the live English page but, as mentioned above, if it’s determined that the order should be the same as what’s on the translation, I’ll change this back!

**Comment by aliyahblackmore** [comment]
Hi @megzehn the About COVID-19 Vaccines page is ready for you!
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=36427

**Notes/Flags:** 

1. The sentence "Ngunit hindi dapat ito maging hadlang para kayo ay magpabakuna kasama na rin ang magpabooster ngayon." is missing the em dash, which is on the live English page. I left the text as is, but wondering if this should be left as is or if it can (in terms of Tagalog grammar) match what is on the English page. The English sentence is "But that shouldn’t prevent you from getting your vaccine—including your booster—now."  cc: @RLHecht 
2. This sentence "Mabilis na tumutugon ang FDA at CDC kung ipinapakita ng datos na makakaapekto ang bakuna sa kalusugan kahit na pambihira ito." is also missing an em dash, which is on the live English page. I left the text as is for now, but wondering if this should match what is on the live English page. The English sentence is "The FDA and CDC respond right away if data shows a vaccine may cause health problems—no matter how rare." cc: @RLHecht 
3. "Serious safety problems are rare" is slightly different in Tagalog. Using Google translate, “Bihira ang problema na may kinalaman sa matinding kaligtasan” translates to “Rarely is the problem related to extreme safety.”  Wondering if this would be considered the same thing/the accurate translation for the English text and if we should double check this with the translators. I’m leaving this as is for the time being. cc: @RLHecht 
4. "Pregnant people also have an increased risk of preterm birth." This sentence may have changed after we sent content to translators and isn’t something included in what they sent back to us.  The current Tagalog sentence is “Mataas rin ang panganib na mapaanak ng kulang sa buwan.” And translates to “There is also a high risk of giving birth prematurely.” This still needs to be translated, but I’ve left in this current sentence for the time being.
5. "The FDA approved or authorized COVID-19 vaccines don’t have ingredients that we know to be harmful people who are pregnant or to a developing fetus."  This wasn’t translated. Using google translate the current Tagalog sentence translates to “The FDA has approved and authorized vaccines against COVID-19 that do not contain, as far as we know, pregnant women or those they are carrying." I am leaving this as is for the time being but we need a translation of this. Also, "ingredients" is missing from the translated sentence that is currently on the page.
6. **_Not within the scope_** of this ticket but one Flag on language on the English page. In the bullet point starting with “Experts believe that COVID-19 vaccines are safe for people who are pregnant or planning to become pregnant and their babies..” there is the use of people who are pregnant, but later in the same bullet point “harm to pregnant women” is used. An earlier bullet point also uses “people who are pregnant.” Flagging this as I’m wondering if this should be changed to "people who are pregnant" to be consistent and to be more inclusive language? Cc: @RLHecht and @megzehn 
7. "Experts believe that COVID-19 vaccines are safe for people who are pregnant or planning to become pregnant and their babies." This wasn’t translated.   Also, if the remaining text in this bullet is updated based on the previous flag, we would need to have the rest translated as well, for both Tagalog and Spanish! cc: @RLHecht 
8. Experts believe that COVID-19 vaccines are safe for people who are breastfeeding and their babies. Early safety data for mRNA COVID-19 vaccines (Pfizer-BioNTech and Moderna) suggest that there are no increased risks to people who breastfeed or chestfeed. You do not have to delay or stop breastfeeding to get the vaccine." This also needs to be translated. I left the text as is for the time being.
9. "Data from clinical trials show that the authorized COVID-19 vaccines are safe in people who’ve been infected with the virus that causes COVID-19 in the past." This needs to be translated. I left the current sentence as is for the time being.
10. "Patuloy na sinusubaybayan ng FDA ang mga bakuna laban sa  COVID-19 kahit naaprubahan na." translates to "Watch this." Flagging as this is sighted language. Wondering if Google translate is giving an inaccurate translation of this, but if not should we have the translators give us "Watch this" instead? cc: @RLHecht 
11. "Your body then makes antibodies in response" This needs to be translated. I've left as is for the time being!

**Comment by megzehn** [comment]
Thank you for all of your careful edits, @aliyahblackmore! You have such a good eye. 

Confirming here that all pages have been reviewed and published. I also pasted some notes, broader discussion Qs, and specific follow-up questions for translators.
______________________

**Re: [COVID-19 Vaccines at the VA](http://preview-prod.vfs.va.gov/preview?nodeId=16413)** 

@aliyahblackmore, I support and second your changes for these. Thank you for documenting them -- super helpful. I added a few thoughts for some of the items you brought up. 

1. Re: the FMP link — I recently made this formatting change on the English version to align with our updated linking standards (giving links their own line). I'll double check with Randi that we want to do it for the English and translated versions. For now, I left your solution as is for all pages - thanks!

3. Re: “Second Booster Updates” Since there have been more updates to this section since we first sent the doc, I don't think an updated translation will be relevant or needed anymore. But correct me if I'm missing something, Aliyah. 

7. Re: the order the vaccines listed. I suspect this doesn't change the meaning, but this is probably worth a broader conversation (i.e. should we always error on the side of what the translation team provides, or is it OK to make small tweaks for consistency?)

9. Re: changing fact sheet style wording. I think what you did makes sense. Thank you! Also agree that this is worth a broader conversation. 

10. Re: missing translation. Good catch. I added that paragraph below to a list of things we may want to clarify with the translation team. 

11. Re: Good point re: "recommended" and "only an option." I think since we have that version on the other page, we should be OK? Thanks for finding it and adding it here. 

13. Re: Novavax fact sheet in Tagalog, thanks for finding and adding that! It looks like the current link to Moderna is also in English. 

____________________

**Re: [About COVID-19 Vaccines](http://preview-prod.vfs.va.gov/preview?nodeId=36427)** 

1-3. Re: Em dashes and Google translate, I'd error on the provided translation. 

4-5. The existing versions seem like a plausible translation for those sentences. Assuming we got them from a translator, I'd leave them. (I don't trust Google translate!) 

6. Great flag! I think this is worth revisiting on the English version. 

7-11. Were those sentences edited since the last version was translated? I didn't notice them changing when I compared revisions, so I assume the existing versions are all OK. 

____________________

**General translation discussion Qs:** 

- How should we address new translations for words/phrases/paragraphs that differ from prior translations? 
- Which formatting style guide standards does it make sense to apply? Which should we ignore? (Thinking specifically on things like capitalization, commas before quotes, em-dashes etc.)   
- How do we want to deal with outdated translations? Do we attempt making reasonable changes with what we have available? Or wait?
- Other thoughts on improving our process? 


**Things to possibly confirm with translators and/or @RLHecht:** 

- Is this [Tagalog Novavax fact sheet](https://www.fda.gov/media/160243/download) the best counterpart for [this English one](https://www.fda.gov/media/159898/download)? 
Is this [Tagalog Moderna fact](https://www.fda.gov/media/144713/download) sheet the best counterpart [for this English one](https://www.fda.gov/media/144713/download)? 

- It doesn't seem like this last part of the paragraph got translated. Could they confirm the full paragraph? 
"Kung nagkaroon ka ng matinding reaksyong alerhiya sa anumang sangkap sa isang bakuna sa COVID-19, hindi ka dapat muling kumuha ng parehong bakuna para sa COVID-19. **But you may be able to receive a different type of COVID-19 vaccine.**"

**Comment by RLHecht** [comment]
Closing this out!
