### ISSUE TITLE
Set up documentation to track gaps in recruiting

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#45425]
## User Story
As a VFS researcher, I want to know that where the gaps on in requested recruitment demographics and actual recruited participants so that I can better understand our research practice 

As a Perigean recruiter, I want to track gaps in requests vs actual recruitment so that I make sure that expectations are being met so that VFS studies are successful.

As a Governance Team/OCTO research reviewer, I want to make sure that we are tracking gaps in requests and actual recruitment so that we can ask Perigean to adjust if needed, and show VFS researchers where we are being successful.

Assignee:
Peer Reviewer:

## Description
We have previously looked back at a subset of past studies to analyze how successful VFS researcher recruitment criteria is being met. We found some items that Perigean can work on, we also found items that either VFS or researcher reviewers can work on or clarify so that we can ensure we are successfully filling recruitment requests.

This ticket is to set up continued tracking, so we can check in the future to see if we are increasing success.

## Impacted Artifacts
New - tracker

## Tasks
- [ ] Develop a new artifact that tracks requests vs actual recruitment

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
