### ISSUE TITLE
CST | Create Inventory of files related to EVSS service

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#45427]
## Value Statement
**_As a_** developer working on the Claim Status Tool
**_I want to_** know which files are related to claims within the EVSS service
**_So that_** I know what which files will be involved when migrating from EVSS to Lighthouse

---
## Background Context
The EVSS Service is being used for other applications outside of CST, so we need to be able to discern which files are related to CST and which aren't. 

## Acceptance Criteria
- [ ] A list of files related to CST has been created

## Open questions
- How do we deal with other services that are calling the same code as CST
- What level of detail should we go to. Only at the service level, also including claims controller / other files, etc.

## Tasks
- [ ] Create a list of files related to CST

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
