### ISSUE TITLE
CST | Create new set of betamocks

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#45428]
## Value Statement
**_As a_** developer
**_I want to_** have a reliable set of mock data
**_So that_** I can test a variety of scenarios on the frontend

---
## Background Context
Lighthouse has been proposing changes to the API for claims from what EVSS currently returns. We need to make sure that the betamocks reflect those changes. This would also be a good opportunity for us to make sure that we have betamocks for all of the scenarios that we would like to be able to test on the frontend

## Acceptance Criteria
- [ ] New betamocks have been created

## Designs and Build Notes
- Add here

## Tasks
- [ ] Create a new set of betamocks

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
