### ISSUE TITLE
CST | Create a new set of VCR cassettes

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#45430]
## Value Statement
**_As a_** developer
**_I want to_** have a reliable set of vcr cassettes
**_So that_** I can create tests that will ensure that our API endpoints are working correctly

---
## Background Context
Lighthouse has been proposing changes to the API for claims from what EVSS currently returns. We need to make sure that the VCR cassettes reflect those changes. This would also be a good opportunity for us to make sure that we have VCR cassettes for all of the scenarios that we would like to be able to test on the backend

## Acceptance Criteria
- [ ] New VCR cassettes have been created

## Designs and Build Notes
- Add here

## Tasks
- [ ] Create a new set of VCR Cassettes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
