### ISSUE TITLE
Certificate of Eligibility | Betamocks

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/va.gov-team#45433]
## Value Statement

**_As a_** developer
**_We want to_** mimic the experience of using the application locally through betamocks.
**_So that_** we can speed up development time and ensure the experience is working as flawlessly as possible.

## Background Context

The LGY service lives behind a proxy that we're unable to make requests against locally when using the website. So in order to mimic the experience of the applications, we should mock all of the potential requests we can make against the service to ensure we're correctly handling all of the various scenarios.

## Tasks
- [x] add betamocks for common requests and add the service to the beta mocks service table in `vets-api-mockdata`
- [x] add this service to the beta mocks config on `vets-api`
- [x] coordinate between squad 1 and 2 to ensure we've covered all of our bases

## Definition of done
- [x] All tasks complete
- [x] All tests passing
