### ISSUE TITLE
Burials forms changes for address modal 

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4543]
## User Story: 

As a person who lives on an overseas military base, I should not be able to list any other country besides the United States in my address in the VA.gov profile or on any VA benefit applications.

## Background:  

The authenticated experience team has been working on an update to the user profile that will allow for better error handling of overseas military base addresses ([details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4386#issuecomment-568466453)). This is the TL;DR: currently, all address forms on VA.gov allow people to enter a country other than the United States if a person lives on an overseas military base even though US military bases are technically considered to be in the United States no matter where they are on the map. The updates we are making to the profile will allow a person to indicate they live on an overseas military base, and it will also prevent a person who lives on an overseas military base from selecting a country other than the United States.

Our team recommends that similar updates be made to the address forms in the 21P-530 Burial Benefits application and 40-10007 Pre-need Burial benefits application. However, this application update do not need to happen immediately, and the profile updates we made are not dependent on the benefit applications also being updated. Updates to the listed Burial Benefits applications can happen any time and can be triaged accordingly depending on the priority of other work.

## Design MockUps 

This is where the design mock ups will be uploaded :

21P-530 Burial Benefits application
40-10007 Pre-need Burial benefits application

## Tasks 

The steps that must be done by the team to complete the acceptance criteria 

- [ ] Review this ticket
- [ ] If necessary, meet with members of the authenticated experience team to answer any questions
- [ ] Implement address updates for [form name/number]

## Acceptance Criteria: 

The requirements that must be met in order to mark this user story as completed 

- [ ]  Address section of [form name/number] has been updated to better handle APO/FPO/DPO addresses

**Comment by Samara-Strauss** [comment]
UPDATE: If you decide to incorporate this into the burial benefits forms, please see the latest implementation of this work and adjust the design and copy accordingly.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/11043#issuecomment-666655878
