### ISSUE TITLE
Create and publish monkeypox R&S article 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45455]
## Issue Description
We need to create a new R&S article about monkeypox vaccines, testing and other important information. Once we have content, we'll need to get it approved before publishing. 

Will add more tasks as I know them. 

---
## Tasks
- [x] Create Drupal page with content (Danielle)
- [x] Copyedit (Megan)
- [x] Update with any changes from stakeholders

## Acceptance Criteria
- [x] New monkeypox R&S article is live on the site

**Comment by megzehn** [comment]
Thanks @RLHecht. 

@DanielleThierryUSDSVA, I copyedited nodeId=48302.

Thank you for putting this together!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @megzehn!

**Comment by RLHecht** [comment]
This page is now live! Closing ticket.
