### ISSUE TITLE
[FE] Payment info MVP: 403 error message appearing for users incorrectly

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45453]
## Background
Unfortunately we are still seeing the same 403 error tied to the benefit payments and debts section for users in production. We're seeing this error on users who have never had payments or debts with the VA, so there's no reason for us to be even attempting to show them the payment info section. (Screenshot below under resources)

Recall that we saw this before in #39965 and then we thought we resolved it in #42763. 

## Tasks
- [x] Determine the cause for this 
- [x] Correct the issue

## Acceptance Criteria
- [ ] the 403 error message does not appear for users who have never had payments or debts with the VA

## Validation
**- _Who can validate this ticket? (FE, BE, Design, PM)?_** Any team member
**- _How can this work be validated?_** ....

## Resources
![Screen Shot 2022-08-04 at 12 12 08 PM](https://user-images.githubusercontent.com/45603961/183510680-d1d6011f-5954-4270-9a22-41512214b092.png)

**Comment by tmitchellgcio** [comment]
From our findings today we discovered we need the following items to be eligible to contact BGS
- ICN
- Social
- ParticipantId

If we can't verify the user has this information and we call the api then we will get a 403. This is still relevant on the new and old design because the error comes from the API. If there is an error state in either design then we will be showing an error so what we need to do is check if they are eligible to call the API to avoid the error state. This does not determine whether or not we show the section. It's entirely different logic.

Our options are:
-Call the API and if there is a 403 ignore it and show no error state, but this causes more strain on the API and we want to lower that. 
-We are calling a lot of APIs that may already have this information so we need to check if we can locate this data from the APIs we are already pulling
-Tom will create an API that checks if they are eligible to contact BGS and if they are then we can trigger the API call. If they are not then we treat it as if it came back as an empty array

**Comment by tmitchellgcio** [comment]
I have checked the APIs available to us as well as the data pulled in for the user profiles. I don't see these three ids anywhere. I don't expect to see the social, but the other two I thought I might find. I think @tpharrison has the best idea to resolve this issue so I think it will be blocked until an API is approved to check this information.

**Comment by tpharrison** [comment]
@tmitchellgcio I wrote up our findings under ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/45684#issuecomment-1218515377.

Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/45871 outlines the BE work for adding the user claims data.

cc/ @ajakabcin @ericasauv09

**Comment by ajakabcin** [comment]
Hi @tmitchellgcio - what's the status of this now that Tom has completed #45871? Thanks!

**Comment by tmitchellgcio** [comment]
Increasing the points because I keep having to switch off of it and the flag means it brings extra complications that need to be handled

**Comment by tmitchellgcio** [comment]
The main issue is it's a flag and currently we know the way we are checking it now does not work so right now if the flag is undefined then we have to check our old incorrect ways.

**Comment by ajakabcin** [comment]
Discussed next steps in grooming today:

1. @tmitchellgcio to discuss e2e testing with another FE dev to see best practice
2. @tmitchellgcio and PM's to discuss with @tpharrison feasibility of turning feature flag on for the BE piece of this fix so we can proceed with testing and fix

**Comment by tmitchellgcio** [comment]
Tested E2E with both cases of the flag being on and the flag being off

**Comment by ajakabcin** [comment]
Confirmed with user 11 and 21 that we're not seeing the error at the top of page

**Comment by tmitchellgcio** [comment]
Since this is confirmed @ajakabcin should we get @tpharrison to turn on the feature in prod? I believe he said the feature is not flipped in prod

**Comment by ajakabcin** [comment]
@tmitchellgcio yes - I'll follow up in slack

**Comment by ajakabcin** [comment]
Reopening this - seeing user 11 again in staging with the error at the top of the page. Confirmed yesterday that user 11 was correctly only showing the alert within the benefit payments section, but now it's displayed within the section and at the top of the page again:
![Screen Shot 2022-10-04 at 3 13 48 PM](https://user-images.githubusercontent.com/45603961/193907531-2a9c5f36-5e65-4947-8d59-14cb753e3392.png)

**Comment by ajakabcin** [comment]
It appears that the backend feature flag was turned off and that's why we were seeing the error again incorrectly on staging with user 11. We'll do one last confirmation on staging with the flag turned on and then hopefully be able to call this done. Slack reference [here](https://dsva.slack.com/archives/C909ZG2BB/p1664910844431049)

**Comment by ajakabcin** [comment]
Confirmed in production my LOA3 account is no longer incorrectly showing an error about my financial information (as a non-veteran with no financial relationship with the VA, there's no reason for My VA to attempt to show my financial info or to return an error an attempting to do so)
![Screen Shot 2022-10-05 at 2 43 10 PM](https://user-images.githubusercontent.com/45603961/194137906-fc48f397-692e-41a9-bc26-5586f863b3d6.png)
