### ISSUE TITLE
[Design] Payment Info V2: Front End Implementation Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45477]
## Background
Once we have completed the design updates for the Payment V2 initiative we need to create documentation for the FE engineer to implement the design changes.

## Tasks
- [x] Create FE implementation documentation
- [x] Share with FE engineer

## Acceptance Criteria
- [x] Documentation for the FE engineer on the new design is complete

**Comment by aagosto90** [comment]
@tmitchellgcio FE documentation is complete for [outstanding debts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md) and [benefit payments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md). They are two separate docs since now these are different sections on My VA that are not dependent on each other. Let me know if you review them if you have any questions, or we can always discuss things as you're implementing in the next sprint.
