### ISSUE TITLE
[Design]Payments Info V2 : Design Updates from Research Feedback

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45475]
## Background
Based on the user feedback we received during usability testing, we want to revisit the design of the Payments and Debts section on My VA. We heard that most users preferred the different types of debts i.e. "copays" and "Debts" broken out into separate sections. We also heard that the red font for debts was alarming and triggering for some users. Finally, we heard that the "updated" date was unnecessary or unhelpful for most users.

## Tasks
- [x] Develop designs for various scenarios on desktop and mobile. i.e "no copays" or "no debts" on these platforms
- [x] Remove the red and green colors from payments and debts amounts
- [x] Determine if we should eliminate the updated dates and replace them with more useful information
- [x] Design should include "copays" and "debts" broken out as separate amounts
- [x] Mock up the benefit payments design for a user who receives paper checks
- [x] Review updates with team

## Acceptance Criteria
- [x] Design updates for Payments and Debts section are complete

**Comment by ajakabcin** [comment]
Thank you @aagosto90 - super helpful to have for comparison
