### ISSUE TITLE
[Design, FE] My VA Redirect: Compile/Execute accessibility tests for Staging Review

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45478]
## Background
As part of our preparation for the staging review we need to perform accessibility tests for My VA Redirect. This will be a joint effort from Design and FE to perform these tests and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review) documentation for reference. 

Additional reference: examples of same tests/process done for staging reviews of [My VA 2.0 launch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/accessibility-test-prep.md) and [notification preferences](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/staging-review/accessibility-test-prep.md) 

## Tasks
- [x] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-redirect/launch-materials/my-va-redirect-a11y-staging-review-prep.md)
- [x] PM/APM to assist as needed and track progress in staging review artifact documentation

## Acceptance Criteria
- [x] Accessibility tests are ready for Staging Review

**Comment by tmitchellgcio** [comment]
These tests are already in the repo and they seem to be passing as expected. I don't believe this needs validation as the tests are passing and there isn't a way to validate it any further as the tests are triggered for every single pull request.

**Comment by tmitchellgcio** [comment]
I am not sure how to really test this as it's a redirect and not part of anything that needs to be read to anyone and it doesn't have anything visual to show the reader. I can't currently write tests as I would expect they would be flaky with the way the flipper works. Once the flipper is not a part of this I believe we can write a test for it, but it would only test the myva page which we have a lot of tests already written about so I believe a test here would be redundant.

**Comment by aagosto90** [comment]
@tmitchellgcio Agreed; some of these tests (actually arguably all of them) are not concerns for the redirect. I'll mark this as N/A on the [chart](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/identity-personalization/my-va/my-va-redirect/launch-materials/my-va-redirect-a11y-staging-review-prep.md) and outline that we already have done e2e tests on My VA. CC: @ajakabcin @ericasauv09

**Comment by ajakabcin** [comment]
Thank you @tmitchellgcio and @aagosto90! I believe we're good to go here. Appreciate your work on this!
