### ISSUE TITLE
[Design] Onsite Notifications: Design Updates From Research Feedback

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45474]
## Background
Based on the feedback we received during usability testing we have want to revisit the onsite notifications design and make some updates. Two major observations were that the date font was too light and difficult to see, and most users did not know that they could dismiss the notifications.

## Tasks
- [x] Update the date font on the notifications to be darker
- [x] Explore options for the "dismiss" design including:
      - Adding a "dismiss" link instead of an "X"
      - Creating a toast/snack bar design for the notification
      - Can we potentially have the notification dismiss on its own, rather than relying on the user to do so?
- [x] Review design updates with team, if necessary

## Acceptance Criteria
- [x] New designs are proposed for the notification section on My VA
