### ISSUE TITLE
SSOe Session Timeout bug

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#45471]
## Description
There is a minor bug found in the `expireSession` method in which the redirect is not conditionalized and essentially redirects to the wrong URL (i.e. IAM using SiS logout URLs).  This impacts a large part of Sentry errors calling for "missing tokens" when a Users session expired.

## Tasks
- [x] Update the `SessionTimeoutModal` to expire the session conditionally

## Acceptance criteria
- [x] The `expireSession` method is called conditionally depending on the `authBroker`

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
