### ISSUE TITLE
[FE] My VA - Health Care section: Cleanup code post launch of Next Appointment API v2

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45480]
## Background
After the next appointment v2 api is launched in coordination with VAOs (see #40115 and #41202 for reference) we'll need to do some code cleanup.

## Tasks
- [ ] Remove feature toggle from staging and prod (`profile_use_vaos_v2_api`)
- [ ] Update cypress tests if needed

## Acceptance Criteria
- [ ] Toggle is removed
- [ ] Tests are updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ FE dev
- _How can this work be validated?_ confirm toggle is removed and tests are updated

## Resources
- #40115
- #41202

**Comment by adamwhitlock1** [comment]
I have validated that feature toggle is removed and code around it is cleaned up. Tests have also been updated. You are good to close this @ajakabcin 🚀

**Comment by ajakabcin** [comment]
Closing per Adam's comments
