### ISSUE TITLE
FE | Profile | Build FF for Direct Deposit Maintenance Period

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45488]
## Background

During the upcoming maintenance window running from Friday 8/12 8:30 PM ET until Sunday 8/14 12:30 PM ET we'll need to leverage a feature flag that prevents 100% of users from accessing this feature.

In lieu of showing the direct deposit feature we will post an explanatory message for users.

## Tasks

- [x] Update feature flags to prevent all users from accessing the direct deposit feature between Friday 8/12 8:30 PM ET until Sunday 8/14 12:30 PM ET 
- [x] Smoke test on Prod
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags updated to prevent all users from accessing direct deposit feature
- [ ] Smoke tested on Prod
- [ ] Validated on Prod with PM and PO

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/45488?planning-poker) with ZenHub @adamwhitlock1

**Comment by Samara-Strauss** [comment]
Re: Feature flag timing -- since we are not working during the downtime window (starts at 8:30 ET on Friday and ends mid-day Sunday), I think it's ok to flip the feature flag EOD Friday and turn the feature back on on Monday. How does this sound?

**Comment by SKasimow** [comment]
Sounds good to me (I am also onto on Fri)

**Comment by adamwhitlock1** [comment]
Feature was put up, and worked as expected. We also complete the maintenance, so it has also been turned off as it is no longer needed. We will keep the component though so that it can be used in future
