### ISSUE TITLE
[Design] | 10-10EZ | Discovery | Improve user experience on Yes/No questions

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#45483]
## Description
During some screenreader user testing for the 10-10EZ form, it was brought up that on some of the Yes/No questions, we start the page with a semi-unrelated paragraph that caused confusion about where you are in the form. The suggestion was to either have the question, then the explaining paragraph (in an additional info component), then the choices OR start the page with a title that gives context to the explanation content.

## Screenshot(s)
![Screen Shot 2022-08-09 at 1.09.29 PM.png](https://images.zenhubusercontent.com/62054990e6d52fbafd985d41/8e96c102-b58d-46ba-ad1d-38f147bca996)

## Tasks
- [x] Review all Yes/No questions in the EZ form
- [ ] Identify content that can be placed within additional info component

## Acceptance Criteria
- [ ] Flow of content is not confusing to users utilizing screenreader

**Comment by jessicastump** [comment]
### Yes/No Questions Found on Form: 
1. Veteran Information > (adding American Indian question page) 
Mailing Address (home different than mailing)
2. VA Benefits > Current Compensation Question, Pension 
4. (Review updates to new household section in design phase)
	4.1 Current = Financial Information Question
	4.2 Current = Spouse’s Information (2 yes/no questions at bottom of form)
	4.3 Current = Dependent Questions
5. Insurance Information > 5.1 Medicaid/5.2 Medicare/5.3 Health Insurance, Contact to Schedule Appointment Question

### Designs
Some design examples for possible approaches to solve this accessibility issue with yes/no questions:
- [Placing content in an additional info component (v001)](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/3ya5vd/a/GmKKw5E)
- [Adding a headline (v002)](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/3ya5vd/a/YGelG4E)

### Next steps

- [ ] Review with 1010 team 
- [ ] Seek accessibility review/guidance on designs

**Comment by jessicastump** [comment]
1. Looking at design system guidance around [form overview](https://design.va.gov/components/form/#with-additional-info) and structure and [additional information component ](https://design.va.gov/components/additional-info#revealing-helpful-background-information-in-a-form) which mentions this being a last resort if possible... 
2. Going back through the audit when the Additional Information component is used on pages VA Benefits and Insurance section page it is placed BETWEEN label and radio buttons and always is the question "Why we ask for this information?"
3. It is currently used consistently in layout order

Should this be moved to before or after the label/question to meet current design system guidance? Is one option more accessible?

**Comment by hdjustice** [comment]
Notes from refinement 2/1/23:
Could consider spacing, drawing it closer to the label to be part of it.. 
Possibly adjust text color to be less saturated than the label..

**Comment by davidakennedy** [comment]
@jessicastump and I chatted about this and we came to this recommendation:

Leave this as is for now. It's a known issue that the form title as a h1 on every page causes accessibility issues for screen reader users. I believe that's the main issue here, and would be improved if the h1 and page title were the same as the question being asked. See #36116 for this coming up in an accessibility audit. Also, the new Forms team is planning on doing usability testing a changed header for forms. See #55121. The new header would be [something like this page](https://staging.va.gov/health-care/appointment-check-in/error?error=no-token).

Moving the additional info components and/or changing the color of the text doesn't address the root problem. So if we wait here for an improved solution upstream in the design system, it might be a better outcome.

**Comment by hdjustice** [comment]
Thank you both for this!  It is great that the main issue is being addressed by a couple of other avenues.  Since the issue stems from something we don't have a whole lot of control over, I agree with the recommendation to watch these other tickets and implement a better solution overall.  Are there any feelings on whether we close this, or put it in the Icebox so we can refer back to it?

**Comment by hdjustice** [comment]
Closing this ticket, created #55518 and placed in Icebox to revisit
