### ISSUE TITLE
Design | Profile | Messaging for DD Maintenance Window

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45487]
## Background

During the upcoming maintenance window running from Friday 8/12 8:30 PM ET until Sunday 8/14 12:30 PM ET we'll need to leverage a feature flag that prevents 100% of users from accessing this feature.

In lieu of showing the direct deposit feature we will need to create and post an explanatory message for users.

## Tasks

- [x] Create a mock-up for what we should show in place of DD during maintenance window leveraging this design and copy [Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmkvxJL) and [Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/pa3zdeZ) 

**Note**-  as of 8/10, waiting on content approval

## Acceptance Criteria

- [x] Review with PM and PO
- [x] Finalize and post to sketch file for future reference

**Comment by SKasimow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VFT-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/45487?planning-poker) with ZenHub @cgednalske

**Comment by cgednalske** [comment]
Here are the mockups for [Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmkvxJL) and [Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/pa3zdeZ) - just waiting on content approval 👍

**Comment by SKasimow** [comment]
Looks good - thanks!
