### ISSUE TITLE
Create, review, and publish PACT Act CLP

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45494]
## Issue Description
Now that the PACT Act has become law, we need to create a campaign landing page in conjunction with OPIA with important information for Veterans.

The content can be added to this Drupal page: 

preview-prod.vfs.va/gov/preview?nodeId=48333

We need to confirm if CLP urls are auto-generated or we need to add one manually. If it's manual we'll need to confirm the correct url. 

## Tasks
- [ ] Add content to Drupal node
- [ ] Copyedit
- [ ] SME review
- [ ] Final copyedit with pre-publishing checklist
- [ ] Publish page

## Acceptance Criteria
- [ ] New CLP is live on the site

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA ! This page has been updated with the FAQs. I've also included some notes and flags. All FAQs fit on this page.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=48333

### Notes/Flags: 

1. I’ve left this page title with the war era. In my comment on the “burn pits” CLP, I mentioned determining whether we should use the era across each page (where applicable) or if we should name the exposure? I am leaving this page title as is.  Again, I believe that the era may be more recognizable as that is also on the PACT Act R&S page.
2. Similar to the survivors and burn pits CLPs, I’ve put in the link to File a Disability Claim as the Primary Call to Action link, but wondering if there is any insight on whether this should instead link to Health Care?
3. I removed the dash between “Vietnam” and “era” in the page title.
4. I’ve added in the image that you provided (via Slack) with this alt text: Photo of a person in a crowd wearing a garrison cap that says “Vietnam,” and their right hand is next to their forehead. Their body is turned away from the camera.” Please feel free to flag any changes on this alt text. The image file was uploaded to the media library and the “Section” was set to “OPIA landing page.”  **I have three questions on this image and alt text:** **First,** the 2:1 aspect ratio for the image (required for the header image) results in the photo being a bit blocked off by the page title and intro text. The image is also a tiny bit pixelated. Anything for us to do here?  **Second**, for the alt text, should we refer to the “person” as a Veteran, assuming that they are? **Third**, for this image alt text, I did a search online to name the specific type of headwear. I found a  infographic that lists two different types of Army Garrison caps. I’ve added in “Garrison Cap” for the time being but wonder if this would be referred to as a [“side cap” or “flight cap](https://en.wikipedia.org/wiki/Side_cap)” instead? I’ll plan to flag this in our standup tomorrow! cc: @RLHecht 
6.	Again, I added in a page intro for the time being: “This page will help answer your questions about the PACT Act and Vietnam era Veterans.” Again, I’m suggesting that this intro be updated once OPIA has added in their content.
