### ISSUE TITLE
[BE] Modify LoROTA Security Update changes with FE payload to support Partial Dial-up

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#45490]
## Description
As part of LoROTA Security Updates changes, vets-api should rely on payload from front-end to use DOB vs SSN in auth_params for LoROTA endpoint call

## Tasks
- [ ] [BE] Modify code logic to check dob/ssn from front-end payload
- [ ] [BE] Remove feature flag check
- [ ] [BE] rspec

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya is this still needed?
