### ISSUE TITLE
[BE] Modify LoROTA security update changes with FE Payload to support Partial Dial-Up

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#45491]
## Description
As part of LoROTA security update changes, vets-api should rely on FE payload to send dob or ssn as auth_params to Lorota endpoint

## Tasks
- [ ] [BE] Remove feature flag check for Lorota security update changes 
- [ ] [BE] Implement FE payload check to get dob/ssn
- [ ] [BE] rspec

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by sarahknoppA6** [comment]
case dependency on lorota fix should be in staging. this can now be validated

**Comment by kanchanasuriya** [comment]
Verified in staging with lowercase last name and authentication succeeds without any issues.
