### ISSUE TITLE
[FE] Update accordion content when Veteran starts pre check in for phone appt after 15 mins past appointment

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#45492]
## Description 

This is what's in staging now for the following scenario: Start pre-check-in for a phone appt after 15 minutes past their appointment time

![Screen Shot 2022-08-09 at 2.47.00 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/f9682c47-73c9-4f11-a0f3-d8286a766e6f)
 
The "How can I update my information?" accordion needs to use this content: 

![Screen Shot 2022-08-09 at 12.14.40 PM (1).png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/454e50f7-0bad-498e-872c-2eba48b8ed34)

Nothing else should change except for the accordion text. 

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Once complete, should pass this off to design to update their files 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)
- [ ] Will need to update product guides

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
Does not currently appear to be an issue in staging or locally.
