### ISSUE TITLE
Create Conversation Guide for "686c Submission Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4549]
## Goal  
We want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users we will be communicating with.

## Considerations
Conversation guides are usually incorporated into Research Plans but because they are large enough, we seperate them.  Both are considered deliverables.

## Task
- [x] Coordinate with @mnorthuis on some of the questions to ask in the conversation guide
- [x] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-conversation-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [x] Conversation Guide has been sent to Shawna for review

**Comment by sporeboy** [comment]
Initial draft of Conversation Guide for 686 usability testing sent to Shawna for review. Feedback in process of being incorporated.

**Comment by sporeboy** [comment]
Link to current draft: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-conversation-guide.md

**Comment by mnorthuis** [comment]
I don't believe the initial research on the View Dependents work included any task on findability on va.gov, so if at all possible, it would be extremely helpful to understand where participants would look for this feature on va.gov - home page top task boxes, top nav, search, or a specific hub?
