### ISSUE TITLE
Address Go / No-go Issues from 8/9

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#45509]
# Description
As a result of the Go / No-go meeting on 8/9, there are several tasks that we need to accomplish in order to achieve a "go" at the meeting on 8/16.
8/9 meeting notes are [here ](https://vfs.atlassian.net/wiki/spaces/AP/pages/2286813233/8+9+22+Office+Hours+Agenda+and+Notes)for reference.

# Tasks
- [x] Update VFS Product Directory documentation to link to the Platform Website published version
   * https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Platform+Documentation "here" in the "making changes to the list" section list item number 1.
   * https://vfs.atlassian.net/wiki/spaces/TTT/pages/2311946314/VFS+Product+Directory+Term+Glossary "product directory" in the intro
   * https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/VFS+Product+Directory+-+User+Guide "this reference page" link
- [x] @Cbonade UPDATED: There should be no links or references to Confluence in the glossary or VFS instructions
- [x] @Cbonade Split out the documentation so that specific audiences get the information that they need
  * Glossary
  * VFS instructions
  * Platform instructions
- [x] @CBonade : Update VFS Product Directory User Guide with information on where we want them to access the list (both human and machine versions)
  * This should refer users to BigQuery for a machine readable version. JSON data is processed before being stored in BigQuery, and BQ represents a more usable version of the data.
- [x] @rsmithadhoc: Detail the exact steps we will take working with Governance team in order to launch VFS Product Directory
- [x] Prepare a launch announcement for Slack and GitHub Discussions

# Acceptance Criteria
- [ ] All No-go issues have been addressed

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Documentation docs are updated. Tried to keep it brief to avoid pages of words. Just let me know if it needs to be more explanatory.

**Comment by CBonade** [comment]
The documentation has been split into 3 documents accordingly:

VFS-level documentation: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/VFS+Product+Directory+-+User+Guide
Platform-level documentation: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Platform+Documentation
Term Glossary: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2311946314/VFS+Product+Directory+Term+Glossary

All relevant links have been updated aside to links that are meant to go to the platform website published list, as it does not yet exist

**Comment by CBonade** [comment]
All references to confluence have been removed from VFS-facing documentation

**Comment by rsmithadhoc** [comment]
- Put in a [support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1660155602090979) to Governance to get some questions answered. After that, I'll have what I need to detail the steps.

**Comment by rsmithadhoc** [comment]
**Steps to take with Governance to launch the Product Directory:**

- [ ] Publish the centralized Product Directory
    - [ ] [Confluence](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory) 
    - [ ] Platform Website
- [ ] Update Confluence documentation with correct links to the Platform Website once it is pubishded
- [ ] Provide documentation and Product Directory links to Governance
    - [Confluence Directory](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory)
    - [Confluence Documentation](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Platform+Documentation)
    - Platform Website (Link TBD after publishing)
- [ ] Archive the [old product list](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) and it's Confluence space used by Governance

**Governance**

- [ ] Update the Collab Cycle to include steps for updating a product entry ([Ticket #45201](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/45201))

Version for easier copying/pasting:
```
- [ ] Publish the centralized Product Directory
    - [ ] [Confluence](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory) 
    - [ ] Platform Website
- [ ] Update Confluence documentation with correct links to the Platform Website once it is pubishded
- [ ] Provide documentation and Product Directory links to Governance
    - [Confluence Directory](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2294120662/VFS+Product+Directory)
    - [Confluence Documentation](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VA.gov+Product+Directory+Platform+Documentation)
    - Platform Website (Link TBD after publishing)
- [ ] Archive the [old product list](https://vfs.atlassian.net/wiki/spaces/VAProducts/overview) and it's Confluence space used by Governance

**Governance**

- [ ] Update the Collab Cycle to include steps for updating a product entry ([Ticket #45201](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/45201))
```
