### ISSUE TITLE
FE | Profile | Build Alert Component for Direct Deposit Maintenance Window

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45512]
## Background

Implement new messaging for DD maintenance window:
[Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/GmkvxJL) 
[Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/pa3zdeZ)

**Note: as of 8/10 waiting for final content approval
## Tasks
- [ ] Implement newly created maintenance message to display instead of DD feature during maintenance period.
- [ ] Put behind FF and test in staging

## Acceptance Criteria
- [ ] Notify PO and PM that the change is ready to be validated on Staging
- [ ] Deploy changes to Production using feature flag

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
We built out the alert, validated and also used it this weekend. It is now pulled down since maintenance on the system is complete.
