### ISSUE TITLE
COE | Rework COE download code

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#45515]
## Background
Move away from storing COE retrieved from LGY in S3, and instead pass it straight to the frontend client

## Context
Currently in order to download a COE, we retrieve the COE from LGY, put it into S3, then return the URL to the S3 bucket to the frontend client. The frontend then attaches that URL to the download link that shows up on the Introduction and Status pages if the veterans' COE status is `AVAILABLE` or `ELIGIBLE`. We should instead take the COE retrieved from LGY and pass the data straight to the frontend client. This would allow us to avoid having to configure S3 locally and would be less resource intensive.

## Other Info
* Currently the S3 buckets we put the COE:
    * Expire after 24 hours
    * Have no way to be traced back to the user
 * This means that every time the veteran visits the Introduction or Status pages or hits refresh on them, a new S3 link is created. 

## Tasks
- [x] Update the COE controller in `vets-api` to return the COE instead of storing it in S3
- [ ] Remove Redux code related to `downloadURL`
- [ ] Update `href` for COE download link to `v0/coe/download_coe`

## Definition of done
- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@scottymeyers Can you add an estimate?
