### ISSUE TITLE
Notification letters | reverse chronological sort

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45534]
## Value Statement
**_As a_** veteran who navigates to the notification letter section of va.gov in search of notification letters
**_I want to_** see a list of my notification letters sorted in reverse chronological order
**_So that_**  I can easily see the most recent ones

---
## Background Context
We have reviewed our design approach with the Collaboration Cycle team. Design approach can be found [here](https://docs.google.com/presentation/d/1LyZbIS4at7bGCQv9cEQaTOiXypDpYqykl8c6j2FSMN0/edit?usp=sharing). 

## Acceptance Criteria

- [ ] Conforms to recent designs 
- [ ] Passes accessibility standards
- [ ] Shows all notification letters in e-folder of type "decision letter" at minimum
- [ ] Each notification letter is easily distinguished from another visually even if the file name is the same

## Designs and Build Notes
- @skylerschain please add here.

## Out of scope
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
