### ISSUE TITLE
Create record upon FSR Submission

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#45548]
## Issue Description
Once model and DB structure is in place, we need the functionality to create an associated record when an FSR is submitted.

---
## Tasks
- [ ] Call new record once FSR submission goes through

## Acceptance Criteria
- [ ] We are creating records in the DB with the associated model for FSR submissions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
