### ISSUE TITLE
[Design, FE] Onsite Notifications: Compile/Execute accessibility tests for Staging Review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45543]
## Background
As part of our preparation for the staging review we need to perform accessibility tests for My VA Redirect. This will be a joint effort from Design and FE to perform these tests and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review) documentation for reference. 

Additional reference: examples of same tests/process done for staging reviews of [My VA 2.0 launch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/accessibility-test-prep.md) and [notification preferences](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/staging-review/accessibility-test-prep.md) 

## Tasks
- [ ] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/launch-materials/onsite-notifications-mvp-a11y-staging-review-prep.md)
- [ ] PM/APM to assist as needed and track progress in staging review artifact documentation

## Acceptance Criteria
- [ ] Accessibility tests are ready for Staging Review

**Comment by tmitchellgcio** [comment]
These tests are already in the repo and they seem to be passing as expected. I don't believe this needs validation as the tests are passing and there isn't a way to validate it any further as the tests are triggered for every single pull request. Did manual AXE checking and so did @aagosto90. AXE showed there are no critical issues on the My VA page including the notifications and payments and debts. I don't believe there is anything further we can do, but will wait for confirmation before we close this.

**Comment by aagosto90** [comment]
Thanks @tmitchellgcio I added that comment to the [chart](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/launch-materials/onsite-notifications-mvp-a11y-staging-review-prep.md). All mandatory tests are complete and passed; I'm still messing around with the screen reader test though and trying to make sure the notification can be dismissed. I might need help from the a11y team. We shouldn't let this hold anything up since it's optional but I'm going to figure out how it works. CC: @ajakabcin @ericasauv09

**Comment by ajakabcin** [comment]
@tmitchellgcio and @aagosto90 amazing - thank you both so much for your work on this!

**Comment by ajakabcin** [comment]
Closing this as we have the required tests but @aagosto90 feel free to keep trying to additional optional tests!
