### ISSUE TITLE
[DISCOVERY] Determine source of GMT Threshold data and appropriate access points

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#45552]
## Issue Description
As part of the streamlined waiver portion of the Combined FSR product we will need access to GMT threshold data to calculate initial approval.

---
## Tasks
- [ ] Meet with POC for ownership of data
- [ ] Discover current access
- [ ] Determine best location for future VODA access

## Acceptance Criteria
- [ ] We can move forward with acquiring GMT data and sourcing it
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
