### ISSUE TITLE
Open Security Review Process for VHA SharePoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#45551]
## Issue Description
Since SharePoint is a new integration with possible security concerns we need to open the security review process soon to authenticate the workflow (VA.gov portal -> VHA SharePoint).

---
## Tasks
- [ ] Acquire ATO boundary from VHA
- [ ] Build architecture diagram of SP interaction
- [ ] Open security review ticket with desired info

## Acceptance Criteria
- [ ] The review process is underway for our SharePoint upload feature
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
