### ISSUE TITLE
[Spike] Eligibility Event Tracker in VAOS 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45583]
## Request
The product team will be migrating the tracking events from Google Analytics 360 to GA4. We will need to review the list of events in VAOS and determine which tracking event we will migrate or sunset for VAOS. There are currently 77 events in Google Analytics. We are requesting assistance from the FE engineering team to understand how the eligibility event trackers are designed. 

### Goal
To [document the definition of the eligibility events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/%5Bdraft%5Dvaos-analytics-definitions.md) for VAOS

### Requirements to Consider
Research the tracking in VAOS and document in the ticket. 

---

## Tasks
- Answer the following questions:
  - Q1: Please describe the following tracking events for eligibility: 
  - [x] `vaos-eligibility-direct-available-clinics-failed`
  - [x] `vaos-eligibility-direct-check-past-visits-failed`
  - [x] `vaos-eligibility-direct-no-matching-past-clinics-failed`
  - [x] `vaos-eligibility-direct-supported-failed`
  - [x] `vaos-eligibility-request-exceeded-outstanding-requests-failed`
  - [x] `vaos-eligibility-request-past-visits-failed`
  - [x] `vaos-eligibility-request-supported-failed`
  - [x] `vaos-eligibility-supported-facilities-failed`
  

## Time Box
4 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jenniemc** [comment]
Documented tracking events for eligibility on [VAOS Analytics page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/%5Bdraft%5Dvaos-analytics-definitions.md)

**Comment by ldelacosta** [comment]
Documentation has been updated. Closing out the ticket.
