### ISSUE TITLE
FE | Profile | Remove DD Feature Flag 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45595]
## Background

The maintenance window is expected to run from Friday 8/12 8:30 PM ET until Sunday 8/14 12:30 PM ET and we will use a FF to prevent access to DD during this timeframe. 

Once completed, we can remove the FF.

## Tasks

- [ ] Remove the  feature flags that prevented all users from accessing the direct deposit feature between 
- [ ] Validate on Prod with PM and PO

## Acceptance Criteria

- [ ] Feature flags removed
- [ ] Confirm with PM and PO DD is available in production
- [ ] Validated on Prod with PM and PO
