### ISSUE TITLE
Medallia - Establish Implementation Guidelines & Strategy

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4559]
## High Level User Story
As a VFS team, I need to understand how Medallia will support veteran user survey analytics on my applications so I can track the health and growth of my products.

As VSP Analytics & Insights, I need to understand how Medallia will be implemented and determine the strategy behind the new survey tool so that I can determine how to add the metrics to the Product Support Tool, implement Medallia on VA.gov, and disseminate the strategy to VFS teams as a part of our analytics support.

## Problem Statement
The VEO is implementing VSignals across the VA, and Medallia will replace ForeSee as the user satisfaction collection platform. VFSs need a way to collect product specific data, and we also need a way to collect customer satisfaction and trust for the entirety of VA.gov.

How might we implement Medallia and integrate user satisfaction and trust collection with our services on VSP?

## Hypothesis/(es)
**If**  we work with VSA leadership to determine Medallia implementation and strategy **then**  we expect to begin actually implementing Medallia on VA.gov and tracking product specific user sentiment.

### VSP Objectives
O3: Teams building products for Veterans use qualitative and quantitative user data to build and refine tools and services.

### VSP Key Results
- Increase VA.gov user satisfaction (via Foresee, Medallia, or similar) from 65% to 68%
- 2 weekly communications to teams highlighting VFS qualitative research or VFS quantitative data

## KPIs
- Number of VFSs tracked using Medallia
- VA.gov customer satisfaction

## We will know we're done when
We have VFS guidelines for implementing Medallia and we have Medallia "set up" on VA.gov:
- [ ] FE code is implemented, and Analytics & Insights can set up surveys on the web interface
- [ ] Analytics & Insights can pull reports on the web interface & has an API connection
- [ ] OMB & OPIA survey requirements are live on VA.gov
- [ ] Teams that currently have "five star" comment cards on ForeSee have live Medallia surveys 

## Details & Notes
VSP Analytics & Insights will work with Jeff Barnes and VSA leadership on discovery.

### Links
- [Historical ForeSee information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/foresee)
- [Medallia Rollout Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/medallia/medallia-rollout.md)

### Product Outline
[Medallia Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/medallia-product-outline.md)

## Communication
- Team that owns this super epic: Analytics & Insights
- Teams contributing to this super epic: FE Tools for implementation. Content & IA for content QA. Product Support & Content & IA for updates to the collaboration cycle.

> ## Assumptions
> - VSA and VSP work together to determine best practices and the process by which Medallia surveys are tracked 
> - VSP will Medallia implementation
> - VSP has the resources to maintain Medallia implementation
> 
> ## Goals
> Determine specific ownership of Medallia tasks. Determine what implementation [Insights Super Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4460) will look like.
> 
> ### Areas for Discovery
> TBD - will work with VSA.
> 
> ## Definition of Done
> - [ ] Discovery roadmap published
> - [ ] Implementation AC and ROE published
> - [ ] Strategy published

**Comment by jwoodman5** [comment]
This is done. Closing.
