### ISSUE TITLE
[Investigate] Lighthouse-UX-Toolkit

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#45594]
## Description
Is this project still ongoing? If not, we need to find out and clean up the resources.

## Background/context 
This was a project a while back, but not seeing a lot of movement from it. [Repository](https://github.com/department-of-veterans-affairs/lighthouse-ux-toolkit) last updated back in October of last year.

---
## Tasks
- [x] Find out if the project is currently ongoing
- [x] Remove resources if not currently ongoing

## Acceptance Criteria 
- [x] IaC cleaned up and resources removed for this project
- [x] Service accounts, secrets, credentials purged

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jbritt1** [comment]
Dropped a couple feelers in Slack:
 - https://dsva.slack.com/archives/C013VCQKSE7/p1660230908129799
 - https://dsva.slack.com/archives/C03FECE9K/p1660230205472669

**Comment by jbritt1** [comment]
Manually removed all remaining Parameter Store values.
