### ISSUE TITLE
Quality check Research Repo cards in the "complete" column

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#45597]
## User Story
As OCTO and Platform we want research to be consistent so that past findings are easier to sort through in order to find relevant data, making it more likely that researchers utilize relevant past findings.

As VFS researcher, I want looking through past research to be as easy as possible so it takes less time to look up relevant past findings that may be useful to my team's product

Assignee: @claytonzook 
Peer Reviewer:

## Description
Currently there is not QA for completed research. In order to ensure standardization and to correct potential issues with research repo cards, we must QC the repo cards that are presently there to ensure Labels are applied properly, Findings are added in a standardized way, and that other relevant information, like links to research folders, have been added.

## Impacted Artifacts
[Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)

## Tasks
- [ ] Decide what the standardized repo card in the completed column should look like
   - Are labels checked? By what metric?
   - Order of content in the card? Findings first?
   - Check links to artifacts? Anything else?
   - Who corrects?
   - What to do if a card is majorly deficient, not enough information, etc? What if the researcher is not currently available or no longer with VA?
- [ ] Clayton and Kaylen (contact through Kevin) decide how to split the QC work
- [ ] Look through and standardize the 88 cards presently in the "complete" column of the Research Repo by the metrics decided in the first task here

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] Research Repo QC round complete
- [ ] Researchers have an easier time looking through past research

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.
