### ISSUE TITLE
Add info about dollar amounts with cents to the style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45598]
## Issue Description

The Sitewide Content team iterated on the way we display dollar amounts with cents in running text and in tables and we need to add this information to the style guide. 

When we have a dollar amount that does not have cents in running text, we will not add .00.

When we have a dollar amount that doesn't have cents in a table or a list, we will add .00

This is to avoid extra noise in running text and so that it's not easily misread.

Example:

Full-time enrollment: $407.00
3/4-time enrollment: $305.00
1/2-time enrollment: $203.00
Less than 1/2-time enrollment: $101.75

We'll charge your entitlement at the rate of 1 month for each $2,150 paid.

We need to add this entry to our style guide.

## Tasks
- [ ] Add entry to style guide (Megan)
- [ ] Review PR (Beth)
- [ ] Notify style guide working group
- [ ] Alert design system council in comment in this ticket once page is live (Megan)

## Acceptance Criteria
- [ ] Style guide is live with updated information

**Comment by mistymg** [comment]
@laurenvocke-va Don't mind me. Just found another old style guide ticket. Assigning to you, putting in your epic/backlog for if/when we address it.
