### ISSUE TITLE
[design] Supplemental Claims | MVP Prototype

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#45600]
## Value Statement
**_As a_** Veteran
**_I want to_** test a working prototype of the MVP Supplemental Claims flow
**_So that_** I can share feedback on the usability of the design and content.

---
## Background Context
- Before we build the Supplemental Claim flow, we want to understand how Veterans will interact with it by conducting usability testing. 

## Designs and Build Notes
- [Prototype WIP here](https://www.figma.com/file/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676)

## Out of scope
- Working code

## Tasks
- [x] _Build the prototype_
- [x] _Share internally_
- [x] _Share with SMEs and Matt_
- [x] Share with collab cycle for midpoint review

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
[Work in progress in Figma here](https://www.figma.com/file/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676).

**Comment by thehastingsp** [comment]
The initial prototype is done. We will iterate as needed and capture that work in separate tickets based on midpoint review feedback and ongoing testing.
