### ISSUE TITLE
Update bereavement counseling page to include info about Vet Centers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45609]
## Issue Description
Vet Center stakeholders asked us to make updates to the [bereavement counseling](https://www.va.gov/burials-memorials/bereavement-counseling/) page to include specific information and links to Vet Centers. There suggested updates are in this word doc:

[https://app.zenhub.com/files/133843125/65013b04-9d2c-491d-b8f4-e47a2c97fd1b/download](https://app.zenhub.com/files/133843125/65013b04-9d2c-491d-b8f4-e47a2c97fd1b/download)

We need to review and edit for plain language and send a revised Word doc with the edits to our burials and memorials stakeholders for their approval first before we can make the changes. 

Once they've approved, we can update in Drupal and go through our regular editorial process. 

## Tasks
- [x] Edit content for plain language and update Drupal node (Aliyah)
- [x] Review changes (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to Vet Center stakeholders (Randi/Laura)
- [x] Send to NCA stakeholders (Randi/Laura)
- [x] Final copyedit (Megan)
- [x] Publish

## Acceptance Criteria
- [x] Updated page is live on the site

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! The drafted text is ready for you in this word document with a few comments and questions! 
I applied changes to the text provided by the stakeholder (under each screen capture).  

Also, as mentioned, I wanted to get this in Drupal just to get a better idea of the flow of the page. 
This is the preview link: (http://preview-prod.vfs.va.gov/preview?nodeId=854)
[Bereavement Counseling_AB_Draft_8.16.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9397216/Bereavement.Counseling_AB_Draft_8.16.docx)

**Comment by laurwill** [comment]
Thanks @aliyahblackmore ! 

Here's the Word doc with my responses in blue:
[Bereavement.Counseling_LW edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9478730/Bereavement.Counseling_LW.edits.docx)

And here's the updated Drupal file: 
http://preview-prod.vfs.va.gov/preview?nodeId=854

See what you think of my edits! You can pass to Megan for copyedit if it looks good to you, and happy to chat about anything!

**Comment by aliyahblackmore** [comment]
Thanks @laurwill ! These edits look good to me.

@megzehn this is ready for you to copy edit!

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=854

**Comment by RLHecht** [comment]
Update: I copyedited and published this page since the Vet Center team was asking for this to be live ASAP. We sent a preview link to the NCA stakeholders just for awareness. Once the page is live we can follow up with Tiffany and Jessica about adding more detail to the kinds of services they provide, which was a question we were going to ask when sending for a review.

**Comment by RLHecht** [comment]
This is live. Closing ticket.
