### ISSUE TITLE
[Process Improvement] Need Better Way of Tracking Offboarded Teams/Projects

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#45603]
## Description
We need a better way of tracking project ownership and when a team/project offboards from the platform

## Background/context 
`lighthouse-ux-toolkit was cancelled most likely around October, 2021 and we are removing pieces of infrastructure for it in August, 2022. Several other examples of this, but this one is the most recent. 

---
## Tasks
- [ ] Improvements need to be made to processes including but not limited to 
  - [ ] EKS onboarding requests checked against VFS team roster (similar to AWS access requests)
  - [ ] VFS team offboarding should be connected with EKS offboarding

## Acceptance Criteria 
- [ ] Improvements made to current processes to account for this scenario

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
One way we can improve (but it a bit out of our wheel house) is if Corey (or whoever owns Slack, DOTS?) can get metrics on usage (not online, because it can potentially be an outliar). E.g.: If a user has not sent messages within the last 45 days or so. We can have it two ways:

1. Slack ping message for us to manually verify that they are no longer part of the project
2. Create an offboard ticket and then we can punt to PM to verify (it will take some investigation)

I know it is not a priority on our board,, but the idea just came to mind and dumping it here before I forget
