### ISSUE TITLE
Notification Letter | Configure an environment to sync with staging data and test connect_VBMS service

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#45604]
## Issue Description
We are able to interact with the `efolder` vets-api endpoint currently via staging and dev VA.gov instances. In order to properly develop our own solution for getting "Notification Letters" from the eFolder, we need to be able to connect our local environments to VBMS's staging environment. 

Once we successfully configure our local environments, we will begin testing the end point in staging

---
## Tasks
- [x] Engineers fill out issue description
- [x] Create AWS Access request tickets for @samcoforma and @jerekshoe
- [x] AWS Access granted
- [x] Determine the process for configuring local environments to sync with staging data
- [x] Execute process for configuring test environment
- [x] Create a test prototype that helps us understand what the end point can return and what it can't return

## Acceptance Criteria
- [ ] Local environments are ready to begin prototyping notification letter interface using end point data from staging. 
- [ ] Test prototype created that clearly shows on a web page all attributes returned by end point under different test scenarios.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
I was granted AWS access on Friday (8/26). From there I was able to:
* Complete AWS account configuration
* Make calls to EVSS (Staging environment) directly from my local vets-api
* Grab a list of claims for a staging user
* Grab the claim details for a staging user
* Determine that the document list provided as part of a claim has an identifier that can be used to grab the document in question from the veterans eFolder
