### ISSUE TITLE
Reduce timeouts to 30 seconds in vets-api

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45619]
## Description
Where possible, we should limit timeouts to 30 seconds within vets-api

## Tasks
- [ ] Add a timeout 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue

- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by joeniquette** [comment]
Eric implemented timeouts, closing.
