### ISSUE TITLE
API Gateway Permissions for Support Slackbot Lambda

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#45612]
## Who is the devops resource on your team?
@gperlangeli 

## Description
A lambda has been created to host the platform support slackbot. This is a proof of concept to see if the support slackbot can be hosted in a lambda (this will need to be scripted in terraform if it is determined that this is a viable solution). The lambda needs an API Gateway trigger to be called by the slack application.

When I try to create the API Gateway I get the following error.
![console amazonaws-us-gov com_lambda_home_region=us-gov-west-1](https://user-images.githubusercontent.com/1776069/184221168-2022fa2b-9c96-44e6-b796-e4c903f53d95.png)

## Technical notes
I can make a PR in the devops project terraform/environments/global/iam_policies.tf but I am unsure of the permissions and resources that need to be added.

If there are policies that need to be attached to the vsp_sre user group I do not have permissions to attach them.

---
## Tasks
- [ ] Create an API Gateway (REST) for the platform-sre-test-support-slackbot lambda (either by granting permissions or by working with someone who has permissions)

## Acceptance Criteria 
- [ ] An API Gateway (REST) is created for the platform-sre-test-support-slackbot lambda

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
@powellkerry : the preferred way to create _any_ AWS resource is to write Terraform code for it (or, if it's managed in EKS and we have an operator for it, use a manifest). This code can live in a slackbot specific repo, or in the devops repo under `terraform/applications`. You might find this a helpful resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api

We can either apply the code for you, or grant you permission to apply. The second option might be preferable if you need to test and iterate, but either way, this change should be linked to a PR so we can track who, when, and why of each resource that is created.

**Comment by powellkerry** [comment]
This application has been moved to the Heroku enterprise account. This ticket is no longer needed.
