### ISSUE TITLE
Midpoint Review Sitewide Facilities, Lovell VAMC/TRICARE pages

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-team#45628]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [x]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [x] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [ ] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.

## Artifacts

Provide links or documents for the following: 

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-initiative-brief.md) 
 
- [x] [Finalized design prototype or mockup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/LovellSwitcherDesign.docx)
- [x] [Research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-research-plan.md)
 
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-conversation-guide.md#conversation-guide) 

- [x] [Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-research-finding.md#lovell-federal-experience---research-findings)

**Previous related reviews:** 

- [January 2022 Design intent #34483](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34483)
- [March 2022 Design intent #38196](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38196)
- [IA review #38735](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37835)

### Content artifacts 

- [x] Your product’s [content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell_sitemap.xlsx)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRaiProduct)
- [ ] Link to test cases/test plan in TestRail (draft OK) 

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman , @chaseakirby

**Comment by dsinla** [comment]
Currently scheduled for Thursday Aug 25, 2022 ⋅ 10:30am – 11am (Pacific Time - Los Angeles)
@dsinla will request to move earlier - ideally 8/17, 8/18, 8/19

**Comment by davidmpickett** [comment]
Added the Lovell sitemap as a Content Artifact

**Comment by dsinla** [comment]
Async Midpoint Review Sitewide Facilities, Lovell VAMC/TRICARE - has been rescheduled
Mon 8/22 3:30PT/12:30 ET
**NOTE:** There is an asynchronous review. No meeting will take place

**Comment by dsinla** [comment]
All artifacts added:

-  Product outline
-  Finalized design prototype or mockup
-  Research plan
-  Conversation guide
-  Research Findings

**Comment by JQuaggles** [comment]
I'm closing this.
