### ISSUE TITLE
Review HAProxy backend statsd to fix it

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45621]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by ericboehs** [comment]
I don't recall what this one was about. Feel free to re-open with more details though.
