### ISSUE TITLE
Clear NOD in progress form after successful submission

### ISSUE THREAD

**Issue by michelpmcdonald** [department-of-veterans-affairs/va.gov-team#45633]
## Value Statement
**_As a_** user
**_I want to_** not be able to submit the same NOD multiple times
**_So that_** my processing time won't be delayed by duplicate nod submissions

---
## Background context
Currently, after successfully submitting a NOD, the users in progress NOD form is not deleted.  When returning to the NOD form in the website, users are presented with a banner informing them that their previously submitted NOD is still "in-progress", even though it has been successfully submitted:

![image](https://user-images.githubusercontent.com/865014/184363158-392b6745-cb4f-4495-a85b-a3f7a51c68bf.png)

Some users are then re-submitting the in-progress NOD again, leading to duplicate NOD submissions that the NOD board has to deal with.
This is causing problems for the NOD board, each NOD request seems to be a somewhat formal "legal" request, and the closing duplicate request is causing extra work for the NOD board(Judges\Lawyers)

This is a pretty hot issue.  To address I added code to safely delete the users in-progress NOD form after a successful NOD submission.

## Acceptance Criteria
- [x] User no longer sees sucessfully submitted NODs as still in-progress
## Tasks
- [x] After sucessfully submitting a NOD, delete the NODs in-progress-form

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
