### ISSUE TITLE
[FE] 10-10CG Email encouragement and content updates

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#45665]
## Description

- This work follows from the [1010CG email encouragement issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44238): a short message encouraging users to include an email in their application is being associated with email fields on the 1010CG.
- Additional small content updates detailed below, along with links to mockups
- Any questions: @nicko-amida (designer)

## Tasks

1) Add the email encouragement message to each of the following 1010CG pages:

"**Note:** Including an email address on your application is optional, but it helps us contact you faster if we need to follow up with you. If you don’t include an email address, we’ll use your phone and address to contact you. We’ll always mail you a copy of our decision on your application."

- [ ] The [Veteran information page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/bgVej79)
- [ ] The [Primary Family Caregiver page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wLzGlyq)
- [ ] The [Secondary Family Caregiver page](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/QbY2Eo1)
- [ ] Ensure the same message appears in the same place if a user adds a 2nd Secondary Family Caregiver

2) Update the page sub-headings on the following pages (linked):

- [ ] Update "Contact information" to ["Veteran contact information"](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/bgVej79)
- [ ] Update "Contact information" to ["Primary Family Caregiver contact information"](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wLzGlyq)
- [ ] Update "Contact information" to ["Secondary Family Caregiver contact information"](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/QbY2Eo1)

## Acceptance Criteria

- [ ] Each 1010CG page with an email input field has the encouragement message
- [ ] Each page's "Contact information" heading is updated to be specific to the page

**Comment by longmd** [comment]
Closing as duplicate
