### ISSUE TITLE
Verify page does not detect if user is verified

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#45676]
## Description
The `/verify` page does not currently detect if a user is already verified within the User model.  A user would have to navigate directly the `/verify` page in order to complete the process.

## Tasks
- [x] Create additional checks if a `user.profile.verified` evaluates to true and if they are redirect them
- [x] Verify all instances of links to the `/verify` page

## Acceptance Criteria
- [x] The Verify page should not allow verified users on the page
