### ISSUE TITLE
Medallia Data Displays on New Dashboard

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45671]
## Issue Description
_To add display Medallia data on the new performance dashboard, we need to figure out how to best extract, transform, and load that data. We will test this on a mock dashboard._

---
## Tasks
- [ ] _Explore data from Medallia_
- [ ] _Write code for the ETL_
- [ ] _Get data ready for display_

## Acceptance Criteria
- [ ] _Medallia data is ready to be displayed in a mock performance dashboard_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
De-prioritized on 8/24.

**Comment by ATMiddleton** [comment]
Performance dashboard was transitioned away from Veteran Support
