### ISSUE TITLE
[Alerting] Evaluate ApplicationErrorRateCritical

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#45683]
## Description
Determine if the `ApplicationErrorRateCritical` alert should be notifying the DevOps Critical group. Oftentimes, the alert is not actionable for the Platform Infrastructure team. This alert was added in 2017 and could use revisiting. Can we break it up into a few different alerts so it's not so all-encompassing? Can we silence the alert during non-business hours? Can we change the priority of the alert? If this is a metric we _do_ need to keep tabs on, who is responsible for keeping an eye on it?

## Background/context 
* Link to one of the alerts in #oncall: 
https://dsva.slack.com/archives/C30LCU8S3/p1660402315487859
* Link to the code where this alert lives: 
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/application.rules#L6
* An 18 hour period of instability on Aug. 13, 2022 prompted this ticket. The cause was likely a PROD Corp Database update that effected many systems, including VBMS, EVSS, and BGS, which is where we were seeing errors. 
* Something to keep in mind is that we want to migrate away from Prometheus to Datadog. 

[Past incidents](https://dsva.pagerduty.com/incidents/Q190O33GH48Q80/past) graph shows an increase over the past few months. HOWEVER, it's slightly misleading because it includes `ApplicationErrorRateCritical` and `SiteLatencyCritical` in the data.
![image](https://user-images.githubusercontent.com/10993987/184919460-ad7373f3-71ff-4b2c-8974-afa59c93875c.png)

---
## Tasks
- [x] Evaluate alert
- [x] Come up with action items
- [ ] Create revproxy alert in datadog (and remove from application.rules)
- [ ] break up ApplicationErrorRateCritical based on what team the alert should go to.
- [ ] _warn_ on 5%, _page_ on 10% or higher.
- [ ] Figure out if there are any SLAs associated with the 5% metric (serving > 5% `5xx` errors). If there are, we probably can't just _warn_ on 5%.
- [x] Notify teams of the new alerting routes. 

## Acceptance Criteria 
- [ ] ApplicationErrorRateCritical has been modified, or the alerting around that error is changed. 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
Steps taken:
* Changed the Prometheus query into a Datadog query
proometheus:
`IF sum(rate(nginx_http_request_duration_seconds_count{job="revproxy", status=~"5..", app!~"ewis-apps|ewis|services|oauth-proxy"}[1m])) by (app) / sum(rate(nginx_http_request_duration_seconds_count{job="revproxy"}[1m])) by (app) 100 > 5`
Datadog:
`per_minute(sum:openresty.nginx_http_request_duration_seconds.count{status:5* AND app NOT IN (ewis,ewis-apps,services,oauth-proxy) AND deployment_name:revproxy} by {app}) / per_minute(sum:openresty.nginx_http_request_duration_seconds.count{deployment_name:revproxy} by {app}) * 100 > 5`
* Changed the Datadog query to _only_ alert on revproxy:
`per_minute(sum:openresty.nginx_http_request_duration_seconds.count{status:5*,app:,deployment_name:revproxy} by {app}) / per_minute(sum:openresty.nginx_http_request_duration_seconds.count{deployment_name:revproxy} by {app}) * 100 > 5`
* Made an [Infrastructure dashboard](https://vagov.ddog-gov.com/dashboard/nuw-4mb-jwu?from_ts=1661962951416&to_ts=1661966551416&live=true) to show queries we migrate to datadog. The query listed above is in the dashboard. 
* New Datadog metric defined in `terraform/environments/datadog/catalog` directory. See initial commit of that work here: https://github.com/department-of-veterans-affairs/devops/commit/95eab6561a1e246e1c3f3347348ca5e6edde49c4
* Tested the `message` workflow from the commit ☝️ in the [Datadog Monitors UI](https://vagov.ddog-gov.com/monitors/create/metric)
```
    {{#is_alert}} 
      Revproxy served {{ value }}% 5xx errors. Should be less than 5%.
      @slack-Digital_Service__VA-oncall
      @pagerduty-Reverse_Proxy
    {{/is_alert}}
```
 `@pagerduty-Reverse_Proxy` says, "use the pd integration (in dd) to create this alert. The impacted service is Reverse Proxy". (The [Reverse Proxy service](https://dsva.pagerduty.com/service-directory/PNIIQQ7/activity) already existed in pd, but I had to connect it to dd in the [integrations section](https://vagov.ddog-gov.com/integrations/pagerduty).) 
I triggered the alert and confirmed that it made its way to PagerDuty and alerted JSG and also showed up in #oncall in Slack.
Here's the pd incident: https://dsva.pagerduty.com/incidents/Q3FI23A9K9HWQE
[Link to message in #oncall](https://dsva.slack.com/archives/C30LCU8S3/p1661968007083999) + screenshot:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/10993987/187787494-04528cfc-e975-4076-81d1-6d740feacf1f.png">

None of the steps taken so far will stop the unactionable `ApplicationErrorRateCritical` alerts.

**Comment by rmtolmach** [comment]
Marking as closed since https://github.com/department-of-veterans-affairs/devops/pull/11884 was merged and tested.
