### ISSUE TITLE
[BE] Payment Info MVP: Investigate 403 error 

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45684]
## Background
 As discussed in [This Slack Thread](https://dsva.slack.com/archives/C909ZG2BB/p1660332734117669) Taylor investigated why users are seeing a 403 error on My VA under the Payments and Debts section in Production. This is happening for users who have never had payments or debts with the VA and therefore should not see this section or error at all. During Taylor's investigation he asked if a Backend engineer can dig into the logic for this section to determine why we are seeing a 403 returned from the api instead of an empty array.

Related to #45453.

## Tasks
- [ ] Dig into the backend logic for Payments and Debts to determine why we are seeing the 403 error returned
- [ ] Determine fix (if related to BE)
- [ ] Resolve bug
- [ ] Validate (PM)

## Acceptance Criteria
- [ ] The 403 error does not return for users who have never had payments or debts with the VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ PM
- _How can this work be validated?_ Ensure users with no payments or debts are not seeing this error

**Comment by tpharrison** [comment]
@ericasauv09 @tmitchellgcio 

The `/v0/profile/payment_history` endpoint returns a `403` response if the user is unauthorized to make the request.  The `403 Forbidden` response status code is a standard HTTP code indicating that the server understands the request but refuses to authorize it.

The authorization check for payment history requires the user to have the following IDs:
- ICN
- SSN
- Participant ID (VBA CORP PID)

If the user does not have all of the above IDs listed, the authorization check will fail and the `403` response is returned to the client:
```
{ 
  title: "Forbidden", 
  detail: "User does not have access to the requested resource",
  code: "403", 
  … 
}
```

This behavior has not changed and is consistent with how unauthorized requests are handled by the vets-api (and most APIs in general).

### Questions
1. Are there any cases in which a user is receiving a 403-forbidden, but shouldn't be?  If so, I'll need to look at the IDs associated with the user to determine why.
2. If the error message just started showing within the past few months, could it be due to changes with how responses are handled on the FE (since the BE authorization check has not changed)?  

### Short-Term Fix
Since 403 errors are being returned for unauthorized requests (and should be), the best short-term fix is to change how the FE handles 403 responses.

### Long-Term Fix
Taylor mentioned that it would be useful for the FE to know whether it *should* call an endpoint on behalf of a user (before actually calling it). This is a better long-term strategy.  Adam Whitlock and I have already been discussing an approach for addressing this in the profile area and I think it will benefit the My VA page as well.  See [this discussion](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44771#issuecomment-1206744816) for more details.

If the approach outlined in the linked discussion seems like a good approach, we can discuss it further.

**Comment by ericasauv09** [comment]
Thank you @tpharrison for digging in. The main issue here is that this is happening for users who should not be seeing the Payments and Debts section at all because they do not have any previous payments or debts with the VA. In this case I think we were expecting the API to return an empty array since the user has no payment or debt history (@tmitchellgcio correct me if i'm wrong). If this is an authorization issue though I am confused why this only happening with users who do not have payments/debts and not all users? 

I will see if its possible to get some user IDs where this issue is occurring as well so we can dig in further.

**Comment by tpharrison** [comment]
Thanks @ericasauv09.  Can someone give me a walkthrough at some point so I better understand the context and make sure I'm looking at the right endpoints?

**Comment by ericasauv09** [comment]
yes absolutely @tpharrison , ill set up some time with myself and Taylor so we can discuss this.

**Comment by ericasauv09** [comment]
Tom, Taylor, AJ and myself met this morning to discuss this issue and possible resolutions. The probable cause of this is that in order to call the BGS API to retrieve payment history we need to have 3 user IDs (ICN, SSN, Participant ID). These IDs authenticate the call and allow us to get a response back from the API. Without these IDs we will get a 403 (forbidden) response. This is not necessarily an issue specific to whether a user has payment history or not, but instead an issue of not having the proper IDs for the user which prevents us from making a successful call to the BGS API.

To resolve we should check for these IDs before making a call to the BGS API. This will reduce the number of API calls we make which will also reduce load on the BGS API. It will also prevent us from receiving that 403 response. Taylor is going to dig into the code and see if we have those IDs available to check prior to making any calls. If the IDs are not available to us Tom can create an API that will inform us whether or not a certain user has those IDs present. This will require us to make a call to Tom's API however, it will still prevent us from making an unnecessary call to the BGS API which will result in a 403 without those IDs present.

On the front end this means the user should see nothing in the Payments and Debts section if they do not have those IDs or if they do not have payment/debt history.

**Comment by tpharrison** [comment]
## Background

Currently, when the MyVA dashboard page loads, a request (Step 1) to get payment history data is always sent to vets-api.

The following diagram illustrates the basic flow of data when a "successful" request is made for a user's payment history data:

![payment_request_success](https://user-images.githubusercontent.com/653787/185247379-74079dd7-3416-4c73-a75e-16ae3e6dabb3.png)


 
The vets-api does not store this data, so when it receives this request, it in turn make a call to BGS to get the data.  Before calling BGS, it makes sure that the user is authorized to make the call (Step 2).  For this particular request, the authorization rule is to check for the presence of an ICN, SSN, and Partipant ID.  All of these must be present for the request to be made to BGS.

In the diagram above, the request is successful and returns a status `200 OK`.

The following diagram illustrates the basic flow of data when an "unsuccessful" request is made for a user's payment history data:

![payment_request_failure](https://user-images.githubusercontent.com/653787/185247443-375e6388-4763-4f4e-8d16-3a28d2149391.png)



In the diagram above, the user did not pass the authorization required to make the request to BGS.  When this happens, the vets-api will return a `403 Forbidden` response to the vets-website.

The 403 error is not an issue specific to whether a user has payment history or not.  In this case, the issue is that the user does not have the proper IDs (ICN, SSN, Particpant ID) to make a request to the BGS API.

## Issue
The payment history endpoint should be returning a 403 response when the authorization check fails.

However, the issue here is that the payment history endpoint is called whenever the My VA page loads (for every user).  Because of this, we are seeing a much higher rate of 403 errors in responses and logs than we would expect to see.

## Resolution
The solution is to avoid making payment history requests for users that shouldn't be making them.

To resolve this issue, the vets-api will pass claims data to the vets-website that informs it whether or not a payment history request should be made on behalf of the user.  This claims data will be need to be available when the My VA page loads. 

Once the vets-website has this information, it can determine whether the user should be able to access payment information or not __before making the request__.

This will reduce the number of API calls made to the vets-api servers.  It should also eliminate 403 responses (except in legitimate edge cases).

The following diagram illustrates the workflow when the user claims authorize the user to make the request for payment-history:

![payment_request_has_claims](https://user-images.githubusercontent.com/653787/185247513-3f931933-6df6-432e-b391-367486fd3a21.png)



If the user claim data does not authorize a user to access payment-history, the user will not be able to view the Payments and Debts section and no request will be made for payment-history data.

The following diagram illustrates this case:

![payment_request_no_claims](https://user-images.githubusercontent.com/653787/185247561-c55a693c-8ead-4055-8c51-0bcccacf8f8b.png)



## Next Steps
When the My VA page loads, an initial request is made to `v0/user`.  This endpoint returns information about the logged in user.

Currently, this response does not contain enough information to allow the vets-website to determine whether a user can access payment-history. 

User claims data will be added to this response that informs the client whether or not the payment-history request should be made.

Ticket [#45871](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45871) outlines the BE work for adding the user claims data.
