### ISSUE TITLE
Testing ClamAV via File Upload

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#45699]
## Description
ClamAV was extracted to its own container and we need to test this new functionality 

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [x] _Attach a Milestone_
- [x] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by laineymajor** [comment]
@ericboehs do you have updates re this work? Just making sure we have the most up-to-date information before taking this on...

Thanks!

**Comment by ericboehs** [comment]
It's been a while since I worked on this but I'll try to be useful here.

ClamAV is used for file uploads to Vets API (I think files uploaded directly to S3 also go through this after upload). ClamAV is a linux process that runs in the same docker container (in BRD). Vets API sends files to be checked over a local network socket. There's also a process that updates the virus signatures (freshclamd).

Running these three processes in the same container isn't how Docker was designed to be used. As we transition to k8s, this process needed to be extracted. In our k8s branch, the ClamAV processes [have been extracted](https://github.com/department-of-veterans-affairs/vets-api/commit/f6c3b3146dc50bf4f2ff78ca0e83f30554e48144) but this code/changed functionality still needs to be reviewed end to end.

I'd suggest finding a place in the frontend where we can test uploading two different file types (e.g. PDF and JPG) and also test direct upload vs S3 upload. I don't have any suggestions for these locations.

**Comment by laineymajor** [comment]
@rmessina1010 @jhonnyoddball  any direction on the following:
I'd suggest finding a place in the frontend where we can test uploading two different file types (e.g. PDF and JPG) and also test direct upload vs S3 upload. I don't have any suggestions for these locations.

Thanks!

**Comment by LindseySaari** [comment]
@Will Huang may be a good resource for testing this

**Comment by jhonnyoddball** [comment]
I'd probably recommend: `src/platform/utilities/`
Maybe an `uploads` folder in there

**Comment by considerable** [comment]
as per https://fedoraproject.org/wiki/QA:Testcase_ClamAV , this file must trigger ClamAV for an alarm:

`curl -s http://www.eicar.org/download/eicar.com  -o eicar.txt`
