### ISSUE TITLE
WASA finding

### ISSUE THREAD

**Issue by troymosher** [department-of-veterans-affairs/va.gov-team#45709]
## Description
Received WASA results from the NSOC, there was only 1 low finding of "The web application discloses sensitive information about itself and its infrastructure."   See [WASA results](https://app.zenhub.com/files/133843125/d5016c60-f5d6-4bcc-819c-3bcc21c32557/download) for full details.

## Background/context 
WASA scan is an annual ATO requirement. In order to complete the requirement, would need a clean WASA scan.

## Technical notes
Research finding and remediate if possible.

---
## Tasks
- [ ] Research and remediate finding if possible, or provide justification as to why it cannot be remediated.

## Acceptance Criteria 
- [ ] Finding is remediated, or justification provided as to why it cannot be.  
- [ ] Receive a clean WASA scan as validation after remediation.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
`more_clear_headers 'Server';` needs added to openresty's configuration

**Comment by jhouse-solvd** [comment]
@ph-One and I chatted w/ @oseasmoran73 today. he's gonna pick this up and take a look. he'll reach out with questions as they arise.

**Comment by jhouse-solvd** [comment]
@oseasmoran73 - Can you move to 'In progress' when you have a chance? Thank you!

**Comment by oseasmoran73** [comment]
@troymosher Changes been applied to dev & staging. @troymosher Per acceptance criteria, can we get another WASA scan to validate?

Moving to the review column

**Comment by troymosher** [comment]
@oseasmoran73 yep, we will request one from the CSOC, it may take a few weeks to get results.
