### ISSUE TITLE
Preferred dates design explorations

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#45719]
## Overview
In the VA direct scheduling flow, [Veterans pick a date to indicate the date they would prefer an appointment.](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=160%3A34403)

![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/f5b5c76a-a754-45fc-ab3f-ae7dc6959901)

Facilities use this as a performance measure, calculating the time between the date the patient wants the appointment, and the date they get in. 

The current interaction relies on dropdowns, which are more difficult to use than entering a date directly.

## Work

Consider design improvements to help ease of use. Some options:
* Use the Memorable Date interaction
* Present the Veteran with a list of options for when they'd want their appointment (this week, in the next two weeks, next month or later, etc) with an "other" option that would let them enter a specific date

**Tasks**
- [x] Create a design concept with a few different approaches 
- [x] Note open questions and assumptions
- [x] Present to team to choose path

**Links to Explorations**
  - [Design File](https://www.figma.com/file/8R1EbX8EdPwgye1LzqW5c4/Preferred-Appointment-Date?node-id=0%3A1)
   - [Radio buttons only](https://www.figma.com/proto/8R1EbX8EdPwgye1LzqW5c4/Preferred-Appointment-Date?page-id=2%3A4&node-id=2%3A4&viewport=637%2C2361%2C0.3&scaling=min-zoom&starting-point-node-id=501%3A10118&show-proto-sidebar=1)
   - [Date Readout](https://www.figma.com/proto/8R1EbX8EdPwgye1LzqW5c4/Preferred-Appointment-Date?page-id=2%3A4&node-id=501%3A12000&viewport=637%2C2361%2C0.3&scaling=min-zoom&starting-point-node-id=501%3A12000&show-proto-sidebar=1)
   - [Green Alert Feedback](https://www.figma.com/proto/8R1EbX8EdPwgye1LzqW5c4/Preferred-Appointment-Date?page-id=2%3A4&node-id=501%3A7996&viewport=637%2C2361%2C0.3&scaling=min-zoom&starting-point-node-id=501%3A7996&show-proto-sidebar=1)
   - [Editable Date Input](https://www.figma.com/proto/8R1EbX8EdPwgye1LzqW5c4/Preferred-Appointment-Date?page-id=2%3A4&node-id=501%3A2272&viewport=637%2C2361%2C0.3&scaling=min-zoom&starting-point-node-id=501%3A2272&show-proto-sidebar=1)
