### ISSUE TITLE
Address Cypress Issues with Element Visibility Between FF and Chome

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#45713]
# Description
Design System team seemingly uncovered an issue with Cypress in their pull request [here](https://github.com/department-of-veterans-affairs/vets-website/pull/21925).

# Tasks
- [x] Propose a modification to the test spec to work around the visibility issue
- [x] Assess whether a new version of Chrome or FF results in identical behavior.
- [x] Assess whether a new version of Cypress resolves the issue.
- [x] Register an issue with Cypress if one doesn't exist that covers the issue.
- [x] Look into alternate solutions

# Acceptance Criteria
- [ ] Chrome and Firefox behave identically with regard to being able to click the `Cancel` element in the modal

**Comment by rsmithadhoc** [comment]
- It ended up being a CSS issue, details here https://dsva.slack.com/archives/CBU0KDSB1/p1660675921836659?thread_ts=1660580679.052349&cid=CBU0KDSB1
