### ISSUE TITLE
FE | Profile | Create Documentation for Handling System Outages/Maintenance

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45722]
## Background

Document how we will handle planned/unplanned outages or maintenance that result in a feature(s) not being available to the user for a period of time including the use of feature flags and special messaging.

## Tasks
- [ ] Create document outlining process to follow for planned/unplanned outages that affect the Profile or features within the Profile.

## Acceptance Criteria
- [ ] Review with team for feedback
- [ ] Post in Github and add link from {Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
I update the docs for this here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/engineering-docs/profile-service-maintenance-outage-procedures.md

I also added it to the product outline in the Frontend section. Should be able to close now

**Comment by SKasimow** [comment]
Thanks!
