### ISSUE TITLE
Document How to Monitor, Log, and Visualize E2E Failures

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#45720]
# Description
We need to establish a process for rotating the responsibility of monitoring the [status-vets-website](https://dsva.slack.com/archives/C02V265VCGH) channel. We also need to create a playbook that describes the responsibilities of the person monitoring the channel.

# Tasks
- [x] Create a document in QAS team Confluence space that describes the responsibilities of the team member monitoring the `status-vets-website` channel
- [x] Add information to the document that describes the actions that the responsible team member should take when notification of failed E2E tests is sent to the channel

# Acceptance Criteria
- [x] A process for rotating responsibility among QAS team members is available in our QAS team Confluence space
- [x] The document describes the responsibilities of the monitoring team member
- [x] The document describes the actions to take when a notification of failed E2E tests is sent to the channel

**Comment by holdenhinkle** [comment]
Google doc - https://docs.google.com/document/d/1aEirBRPXFKUZJ_f7_i2Z9m12DA9ytjhHTLTIcs7am54/edit#

**Comment by holdenhinkle** [comment]
The draft is complete. Curt is proof reading it. Peter will later. Once it's good, I'll copy/pasta it into confluence.

**Comment by holdenhinkle** [comment]
Curt read it and made a couple of suggestions that I implemented.

Here's the confluence doc - https://vfs.atlassian.net/wiki/spaces/TTT/pages/2330198071/How+to+Track+E2E+Failures+Against+Main

**Comment by pjhill** [comment]
I added some comments to the document. Holden resolved all the comments. This looks good to go!
