### ISSUE TITLE
Performance Dashboard Updated Manually with Medallia Data

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45728]
## Issue Description
_ForeSee is being sunset unexpectedly on 8/26. In order to keep the Performance Dashboard useful and relevant, we need to replace the ForeSee survey data with Medallia Survey data manually. This will happen on Sept. 2nd after we have received the monthly data delivery from Medallia on Sep. 1st.This is the _general_ direction we intended to go anyways, it is just happening sooner than expected._

---
## Tasks
- [ ] _Update (survey) satisfaction data manually on the Performance Dashboard with Medallia satisfaction scores._
- [ ] _Ensure other data updates (GA) continue to occur as they have historically_

## Acceptance Criteria
- [ ] _The Performance Dashboard is updated manually with Medallia survey satisfaction scores._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
