### ISSUE TITLE
Create YAML Custom Data Request Template 

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45729]
## Issue Description
_Teams have been requesting custom/qualitative support and survey data occasionally and we need a formal process for receiving and addressing these requests._

---
## Tasks
 - [x] _Use the previously created requirements outline to create a functional YAML template to be used by qualitative/custom data requestors_

## Acceptance Criteria
- [x] _A YAML template exist with all necessary fields and information for users to be able to submit a request for (qualitative/custom) support or survey data_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 

Here is the URL to create a custom survey ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5&labels=VSP-contact-center&template=request-custom-survey.yml&title=Request+Custom+Survey

Note: I don't believe there is an option for a date field, so I used a standard text input. Let me know what other content you want on the top or bottom of this, I just stuck with the input fields for now.

**Comment by ianMcCullough-ob** [comment]
[YAML Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/qualitative-data-request.yml)

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 we good to closet this?

**Comment by jwoodman5** [comment]
Yessir, all good. Closing.
