### ISSUE TITLE
YAML Data and Survey Request Template Requirements

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45739]
## Issue Description
_Teams have been requesting custom Medallia surveys and custom/qualitative support/survey data occasionally and we need a formal process for receiving and addressing these requests. This issue accounts for gathering the requirements to develop the template._

---
## Tasks
- [x] _Create an outline with requirements for a custom survey and data request templates, separately_

## Acceptance Criteria
- [x] _Separate outlines exists with all necessary fields and information for users to be able to submit a request for a custom survey or custom/qualitative data._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Here's some relevant links:

[Issue template folder →](https://github.com/department-of-veterans-affairs/va.gov-team/new/master/.github/ISSUE_TEMPLATE)
[Syntax for issue forms documentation →](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Creating a YAML ticket →](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Comment by jwoodman5** [comment]
[Custom Survey Request Requirements](https://docs.google.com/document/d/1qH57eTlxouBPLTltAApIaBeY1KXHWlevYvvV4wCENPg/edit)
