### ISSUE TITLE
Create YAML Custom Survey Request Template

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45732]
## Issue Description
_Teams have been requesting custom Medallia surveys occasionally and we need a formal process for receiving and addressing these requests._

---
## Tasks
- [x] _Use the previously created requirements outline to create a functional YAML template to be used by custom survey requestors_

## Acceptance Criteria
- [x] _A YAML template exist with all necessary fields and information for users to be able to submit a request for a custom survey._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Survey request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5&labels=VSP-contact-center&template=request-custom-survey.yml&title=Request+Custom+Survey)

[Sample ticket created from survey](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/department-of-veterans-affairs/va.gov-team/45758)

**Comment by ianMcCullough-ob** [comment]
Note: I don't believe there is an option for a date field, so I used a standard text input. Let me know what other content you want on the top or bottom of this, I just stuck with the input fields for now.

**Comment by jwoodman5** [comment]
BTW, @ianMcCullough-ob, this is AWESOME! Let's walk through it during out 1:1. Are we able to drop this in a column/category other than icebox when a user submits?

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 Looks like I might be able to get a new ticket to appear in a specific column using github actions. [Here's some documentation](https://github.com/marketplace/actions/add-new-issue-to-column) on that.

It's a bit over my head, but I bet I can tackle it in another sprint if we want to close this ticket out and open a new one for later.

**Comment by ianMcCullough-ob** [comment]
This is that ticket I was talking to you about @aubreyarcangel

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 we good to close this?

**Comment by jwoodman5** [comment]
Yessir. all good. Closing.
