### ISSUE TITLE
User Journey Map User Research - Recruitment

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45734]
## Issue Description
_To further our research of the support user journey, we need to recruit users to conduct interviews with._

---
## Tasks
- [x] _Finish Review with Design Team [https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/130](url)_
- [x] _Approval to move forward with request to Pernigan_

## Acceptance Criteria
- [x] _Recrutiment will be completed for VA Caller user journey research_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
Update task with link to Review to Design Team.

**Comment by manalo-soco** [comment]
Link to Clayton's comment: 
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/130#issuecomment-1224050186

**Comment by jwoodman5** [comment]
@manalo-soco Feel free to do the honors of checking that last box and closing this out. Nice work making this happen!
