### ISSUE TITLE
Build Data Table for Performance Dashboard Calculations

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45733]
## Issue Description
_To support updating the Performance Dashboard manually with Medallia satisfaction scores, we need these scores calculated and stored somewhere, in this case, DOMO._

---
## Tasks
- [x] _Create a new table in DOMO to host Medallia satisfaction scoring data_
- [x] _Identify correct product URLs/Directories to segment satisfaction data by and apply as segment filters in table_
- [x] _Create calculation for overall and product specific satisfaction scores and display in table_
- [x] _Make table available internally to contact center team members_

## Acceptance Criteria
- [x] _Medallia Satisfactions scores are calculated by product (URLs/directories) in the same manner as existing segments on the Performance dashboard_
- [x] _Medallia satisfaction scores are visible within a (private/internal) table in DOMO_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Reached out to Sarkis about getting a monthly export that gets sent out on the 1st of the month. This will eliminate any lag created by the weekly reports.

**Comment by ianMcCullough-ob** [comment]
URLs for the cards:

Health Care
www.va.gov/health-care
/health-care/apply
/schedule-view-va-appointments
/covid19screen
/health-care/covid-19-vaccine/stay-informed/form/


Disability
www.va.gov/disability
www.va.gov/track-claims/
/file-disability-claim-form-21-526ez/
/view-disability-rating/


Education
www.va.gov/gi-bill|www.va.gov/education
/gi-bill-comparison-tool
/application/1990/
/application/1990e/
/application/1995/
/apply-for-vettec-form-22-0994
/application/5490/
/application/5495/
/application/1990n/
/education/submit-school-feedback
/education/gi-bill/


Burials & Memorials
www.va.gov/burials
/pre-need/form-10007
/application/530/


Pension & Fiduciary
www.va.gov/pension
/application/527ez/


Profile & Records
www.va.gov/profile|www.va.gov/records
www.va.gov/profile/
www.va.gov/profile/
/download-va-letters

**Comment by ianMcCullough-ob** [comment]
[Monthly Data Dataset](https://va-gov.domo.com/datasources/c2cdf24a-a65a-42e1-985c-3f284ce1585f/details/overview)

[Monthly Sat Score DOMO Dash](https://va-gov.domo.com/page/748365253)

**Comment by ianMcCullough-ob** [comment]
Utilized the table to launch data this AM
