### ISSUE TITLE
Login Wizard Research Readout

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45735]
## Issue Description
_We recently completed user research sessions for the login self-service prototype we created. This issues covers completing the research readout from those sessions._

---
## Tasks
- [x] _Write the research readout from the login self-service tool user research sessions._

## Acceptance Criteria
- [x] _Research readout from login self-service user research is complete and posted in Confluence._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@ianMcCullough-ob Can you please link to your research readout in confluence? Thanks.

**Comment by ianMcCullough-ob** [comment]
@jwoodman5 I learned that veteran-facing research needs to be housed in GitHub, so I [linked it here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/login-self-service-tool/research/research-findings.md).
