### ISSUE TITLE
Translate core health care "get benefit" content into Spanish

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#45745]
## Story

As a Veteran with limited English proficiency, I need the core benefit information for VA health care in my primary language.

We are starting with 3 health care pages for Spanish translation:

- [Eligibility for health care](https://www.va.gov/health-care/eligibility/)
- [How to apply](https://www.va.gov/health-care/how-to-apply/)
- [After you apply](https://www.va.gov/health-care/after-you-apply/)

## Tasks

- [x] Send a word count and links to pages to State Department for estimate.
- [x] Prep content for translation (Danielle/Randi)
- [x] Send content to translators (Randi)
- [x] Upload content into new Drupal nodes (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish pages (Megan)
- [x] Send live links to translators for QA (Randi)
- [ ] Alert PW to add language tab to top of page once QA complete (Randi)

## Acceptance criteria

- [ ] Health care content in Spanish is live on the site

**Comment by RLHecht** [comment]
We sent this to the translation team on 12/2. Translators said we should be getting this back by 12/16. Moving to blocked until we have content for Drupal.

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the content back from the translators to create new Drupal pages with: 

[https://app.zenhub.com/files/133843125/1b6b8ade-3d97-484e-944a-22197aef5fc2/download](https://app.zenhub.com/files/133843125/1b6b8ade-3d97-484e-944a-22197aef5fc2/download)

**Comment by aliyahblackmore** [comment]
**Update here:** 

I started on this work and will come back to this the week of Jan. 3!

**Comment by aliyahblackmore** [comment]
**Update here:** I only have one page left in this work. Was pulled in to another task today so will pick this up tomorrow morning!

**Comment by aliyahblackmore** [comment]
Hi @megzehn - these three new pages are ready for you! 

Elegibilidad para el cuidado de la salud de VA
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=52134

### Notes: 

1. Do we need a menu link for these pages?
2. Using the current page to see if language is matching but actually asked Randi for the Word doc to see if it matches that – since these changes may not have been made to the Live English page yet.
3. “Prestó servicio antes del 7 de septiembre de 1980.” Has a period added on the end, though we don’t have one on the live English page. Curious to know if this was added due to any Spanish grammar rules. I removed this for the time but could we confirm with the translators? Cc: Randi
4. There were also periods on the other H3s in the featured content box I removed this for the time being on the Spanish page to match the live English page. Could we flag this with them as well?
5. For the question “Is there anything that will make me more likely to get these benefits?” The bulleted list has some language in parenthesis after POW, “por sus siglas en inglés” which means something along the lines of “by it’s acronym in English.” This wasn’t included on the doc that we sent to them – I left this in for the time being but wondering if there’s any need to rework this at all to better match VA style standard or if there was a reason that they included this?
6. Under “O bien, debe haber prestado servicio en cualquiera de estos lugares durante la época de la Guerra de Vietnam:” I removed the periods from these bullet points. 
7. In the second question I replaced “dos” with “2”
8. Does the Application link need to be in a react widget? I included it as an action link without any code for the time being. Also, should we include “en ingles” at the end the link. I haven’t seen parenthesis on action links across the VA site, so happy to adjust this if needed. CC: Randi 
9. Link to new “How to apply page” for “Learn more about how to apply” after it’s created.
10. The translators us “hora del este” instead of ET. I’ve left this as is, but wondering if this is a question for their team re: style?
11. For these acronyms - OEF/OIF/OND- do we need to add “por sus siglas en ingles?” as well here? 
12. For the last accordion “Creo que puedo tener una discapacidad relacionada con el servicio. ¿Puedo recibir compensación por discapacidad (pagos mensuales)?” I included the link to the Spanish version of this page ( to be published) so I took out “in English.”

__________________________________

Cómo solicitar cuidado de la salud de VA
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=52414

### Notes: 

1. In the text above the bulleted list, the live English page is using bullet points, but the English doc sent doesn’t have bullet points. I think we’d want to leave in these bullet, but if this was a change for translation purposes – happy to add this back in. 
2. In the featured content box there is some directional language – this is on the source of truth word doc and live page as well. I’ve left the Spanish translation as is – but thinking that we’d need to get rid of “below” on the live English page. The Spanish translation uses “indicada,” which I believe translates to “indicates.” 
3. We link to the new Spanish eligibility page here – I added in the node.
4. The action link for the application – does this need a react widget and do we need to put “(in English)” at the end of the link?  I haven’t seen parenthesis on action links – happy to adjust if needed. I’ve left this as is.
5. Removed the periods after the H3s for How to apply – wondering if there is a Spanish grammar rule for added those in – they aren’t in the word doc that we sent to them.
6. In sentence “**U** obtenga ayuda del Departamento de Asuntos de los Veteranos de su estado" I noticed that U was used here for “or” – that’s because U is used when the next word has an “o” sound. 
7. Once this page is live, I believe we’ll need to remove the drop down in the application section with the Spanish instructions.
8. In question “What happens after I apply,” I linked to the new Spanish page that I created.

__________________________________

Después de solicitar beneficios de cuidado de la salud
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=53192

### Notes:

1. In the accordion “¿Qué pasa si necesito ver a un médico antes de mi cita programada? There was a period added to the last bullet point. I removed this to match the English document. Wondering if that was needed at all? 
2. Where necessary, I included “en ingles” in the hyperlink.
3. In accordion “¿Cómo puedo obtener más información sobre mis beneficios y acceso a los servicios?” I added a period after "hora del este."
4. In some more recent translations "por sus siglas..." has been used alongside acronyms. Do we need this here?

**Comment by megzehn** [comment]
Thanks so much, @aliyahblackmore! 

Update re: the acronyms OEF/OIF/OND within the eligibility page (your question #11), I'm asking Ana to translate this line, so we can add it below the OEF/OIF/OND sentence and get the “por sus siglas en ingles" part somewhere in there.

"OEF/OIF/OND refers to Operation Enduring Freedom, Operation Iraqi Freedom, or Operation New Dawn."

**Comment by megzehn** [comment]
@RLHecht -- confirming that these 3 pages have been copy edited and published!

http://preview-prod.vfs.va.gov/preview?nodeId=52134
http://preview-prod.vfs.va.gov/preview?nodeId=52414
http://preview-prod.vfs.va.gov/preview?nodeId=53192


A couple of notes for reference: 

- I changed the action link on the eligibility page to direct to the **How to apply** page in Spanish, after [discussing with Danielle](https://dsva.slack.com/archives/C03MP8MEPCN/p1675365034261219) and Aliyah, and getting a new translation from Ana. 

- Also, whenever we linked to Form 10-10EZ, I changed it to [this jump link](https://www.va.gov/find-forms/about-form-10-10ez/#related-forms-and-instructions) as Danielle recommended, so that it directs users to the Spanish PDF.

**Comment by RLHecht** [comment]
These pages are all live and I've sent the links to the translators. I'll open a separate ticket for any changes we'll need to make based on their QA. Closing!
