### ISSUE TITLE
Look into how Web LGY works when VA is the lender

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#45742]
## Issue Description

We recently removed an action link pointing to eBenefits on 2 COE-related pages. Aliyah noted that we say you can get a COE "through your lender," but for some loans VA is the lender. 
- [Eligibility requirements for VA home loans](https://www.va.gov/housing-assistance/home-loans/eligibility/)
- [How to request a home loan COE](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/)

We'll need to look into whether the language on these pages needs to change to reflect how this process works when VA is the lender. 

## Tasks
- [ ] Look into whether wording needs to change in "through your lender" section (Aliyah)
- [ ] Reach out to stakeholder for more info (Laura)
- [ ] Make updates if needed (Aliyah)
- [ ] Copyedit with prepub if needed (Megan)
- [ ] Publish if needed (Megan)

## Acceptance Criteria
- [ ] Wording is updated if needed

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
