### ISSUE TITLE
Update Medallia ETLs in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#45741]
## Issue Description
_To support the new file structure from the S3 file used to further automate the Medallia data update process, we need to update the ETLs in DOMO to conform_

---
## Tasks
- [x] _Update Medallia ETLs in DOMO to conform to new file structure_

## Acceptance Criteria
- [x] _Medallia dashboards can be successfully update with new Medallia data file loads_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
@ianMcCullough-ob I think this is done. If you agree, you can close it. Thanks.
