### ISSUE TITLE
Update Form Funnel Steps for VFS Teams with Changes

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#45753]
## Issue Description
As part of #44652 we reached out to VFS teams to confirm their current form funnel steps for the Forms KPI Dashboard.  For this ticket we will update those form funnels for the teams with changes.

---
## Tasks
[ ] 1010 CG - [updated funnel steps](https://docs.google.com/spreadsheets/d/1TrqoUUE9YqhYZb6pR2W6UoLg_H_Lbi-UuxNN5MI-vZ0/edit#gid=649068577)
[ ] 1010 EZ - [updated funnel steps](https://docs.google.com/spreadsheets/d/14Jxyh7oTS94eClXWbwhDMp_M5EhrkJEcoHt0wpzA1qI/edit#gid=0)
[ ] 20-0996 Higher Level Review - pending feedback
[ ] 21-526EZ Original Disability Form - pending feedback
[ ] 28-1900 Ch31 - pending feedback

## Acceptance Criteria
- [ ] When the forms dashboard has been updated based on changes (as applicable).
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@chloedotbrown to update Confluence steps and meet with @pavanhothi to provide direction so he can make the updates.

**Comment by chloedotbrown** [comment]
@pavanhothi and I did an hour-long training on this today (see recording [here](https://drive.google.com/file/d/1-Sc1kUxZuZePpqrLVDNezUOF8mtvId27/view?usp=sharing)). I've also added a [whole new section](https://vfs.atlassian.net/wiki/spaces/AT/pages/1510408350/How+to+-+Loading+a+new+funnel+to+the+Forms+KPI+Dashboard#Checking-optional-steps) with test code in Confluence to make it easier for us to easily check whether the `is_optional` designation is correct.

**Comment by michelle-dooley** [comment]
If we do not hear back on 3 Benefit 1 team funnels we will run test to mark if steps are optional and mark in BQ accordingly based on changes implemented as part of these updates.

**Comment by chloedotbrown** [comment]
I ran [Optional Step Tests](https://vfs.atlassian.net/wiki/spaces/AT/pages/1510408350/How+to+-+Loading+a+new+funnel+to+the+Forms+KPI+Dashboard#Checking-optional-steps) for the funnels we currently have on file for the 3 forms that haven't been updated yet - all passed with no changes needed.

@pavanhothi is currently running new funnels backfill. Once that's complete and Domo queries have been reset for weekend updates, we should be good to go.  @michelle-dooley up to you whether you want to close then or wait to see if we hear back from other folks!

**Comment by pavanhothi** [comment]
@chloedotbrown @michelle-dooley Domo backfills are complete, and queries have been reset for weekend updates!
