### ISSUE TITLE
Add guidance for out of team scope Collaboration Cycle findings

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45755]
## User Story
I am a Governance team member trying to present my findings at Staging Review but the VFS team has identified that the finding is either not in scope or not their problem because it's not part of the iteration or they are not the team accountable for addressing the issue which makes me feel frustrated and that I've burdened the VFS team.

Assignee: @seanasewell 
Peer Reviewer: @briandeconinck 

## Description
In Staging Review workshop, two tickets were identified related to confusion over how to handle feedback out of scope for the iteration or not the VFS team's responsibility.

## Problem Statements
[Mural Workshop List](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=u5d556df3430960096c525037)

## Impacted Artifacts
[How to reassign tickets, or close invalid or duplicate staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1862139961/How+to+reassign+tickets+or+close+invalid+or+duplicate+staging+review+tickets)

## Tasks
- [x] Review How to reassign tickets, or close invalid or duplicate staging review tickets
- [x] Determine if any changes need to be made for who takes the action

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team members understand our process for reassigning tickets to other teams
- [x] Governance team members understand our process for out of scope tickets

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by seanasewell** [comment]
@chaseakirby I added the following copy to the intro paragraph...

> An example where reassigning a GitHub issue ticket to another team might occur is if a Governance team member provided feedback that is out of scope or does pertain to the product/feature in review. 

I think the document does a good job at referencing when to reassign a ticket to a **different team** but what if the issue should be assigned to their team? The feedback might be out of scope for the product/feature that's currently in review but what if it should be assigned to them but just not in context to what they are currently working on. Do they just reassign the ticket to themselves? Isn't it already assigned to them? Would they just move it to their backlog or something? How does that process work? If so, should we add those instructions to the document so that they know that is an outcome that might exist?

**Comment by chaseakirby** [comment]
@seanasewell (and @shiragoodman when she is back) My understanding is that yes, the ticket is already assigned to them.
I would imagine that we recommend that they move the ticket to their backlog (their workflows most likely already do that if their ZenHub board uses their team label) and should be prioritized in discussions with their Product Owners for future releases.
I think that is definitely instructions we should add so that they understand that we will still create those tickets but they can work to figure out when they should be implemented.

**Comment by seanasewell** [comment]
@shiragoodman A new peer reviewer needs to be reassigned to this ticket. It is ready for review.

I updated the structure of the document a little bit to incorporate a scenario where an issue ticket might pertain to the product/feature in review but is out of scope. My assumption is that they wouldn't want to reassign the issue ticket to another team or outright close it. So I added a section to accommodate this scenario with a solution to move the ticket to their own backlog so that they maintain visibility of the issue that was captured by our team.

**Comment by shiragoodman** [comment]
@briandeconinck replaced Chase Kirby as peer reviewer

**Comment by briandeconinck** [comment]
@seanasewell I think this looks good! All three scenarios are straightforward.

**Comment by seanasewell** [comment]
@shiragoodman This has been peer reviewed. I am going to close the ticket.
