### ISSUE TITLE
Add question to determine scope of changes in Collaboration Cycle Request

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45757]
## User Story
I am a Governance team member trying to document issues I am finding in the Staging Review but I am not sure what's in scope because the VFS team has shared the complete product without specified boundaries which makes me feel confused, unsure, and hesitant.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
In Staging Review workshop, we identified one sticky note; Not always sure what's in-scope vs what's not when finding an issue

## Problem Statements
[Mural Workshop List](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=u5d556df3430960096c525037)

## Impacted Artifacts
[45757 - Allison - Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2334228481/45757+-+Allison+-+Staging+Review+-+Moderator+Responsibilities) Schedule Review/Step 7
[45757 - Allison Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2334588929/45757+-+Allison+Midpoint+Review+-+Moderator+Responsibilities) Schedule: Synchronous Review/Step 7 & Schedule: Asynchronous Review/Step 6
[45757 - Allison - Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2334228513/45757+-+Allison+-+Design+Intent+-+Moderator+Responsibilities) Schedule Review/Step 7
[Midpoint/Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)

## Tasks
 - [x] Create new script for replying to cc request in Slack 
  - [x] Include information about scope (what pages are we reviewing)
  - [x] Include information linking artifacts
- [x] Add script to staging review moderator Schedule/Step 7.
- [x] Add script to midpoint review moderator Schedule/Step 7.
- [x] Add script to midpoint review moderator Schedule: Asynchronous Review/Step 6.
- [x] Add script to design intent moderator Schedule/Step 7 (will not include scope bc design intents are typically limited on artifacts)
- [x] Update Code Blocks to note changes that we need to review in artifacts 
- [x] Sync with Cheryl #45796

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS team members have a place to communicate the scope of the midpoint and staging review
- [x] Governance team members understand the scope of the midpoint and staging review

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@briandeconinck this is ready for your review.

**Comment by briandeconinck** [comment]
@allison0034 I think this all looks good!

**Comment by allison0034** [comment]
@shiragoodman I updated added instructions for VFS to look at their actions in the ticket and put it in a table so it is similar to the readable script and closed the ticket.

- [Design intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

- [Midpoint review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)

- [Staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)
