### ISSUE TITLE
Add Instructions for teams to invite product owners and a11y support

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45754]
## User Story
I am a VFS team member trying to schedule my team's staging review but I sometimes forget to add a11y/product owners to the invite because I am unclear on who adds those specific people which makes me feel frustrated.

Assignee: @briandeconinck 
Peer Reviewer: @jimuhh 

## Description
In the Staging Review workshop, we identified two related issues; VFS teams not inviting their a11y support people and their product owners.

## Problem Statements
[Mural Workshop List](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=u5d556df3430960096c525037)

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities - Code Blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Add subbullet to "Click "Add Guests" and enter the VFS meeting attendees email addresses" saying "Invite respective people, this includes accessibility support and product owners"
  - NOTE: Keep the text light.
  - [x] Design Intent Code Block
  - [x] Midpoint Review Code Block
  - [x] Staging Review Code Block
- [x] Review if additional guidance should be added to Platform Website touchpoint pages

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS teams understand they are responsible for inviting a11y support and product owners

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
@jimuhh Ready for peer review. Since it's been a while, here's the quick overview!

Goal of the ticket is to remind VFS teams to invite everyone they're supposed to invite to touchpoint meetings, especially accessibility support and product owners.

I've added the sub-bullet "Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders" to three code blocks:
- [Design Intent code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block)
- [Midpoint Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Midpoint-Review-code-block)
- [Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)

Additional guidance on meeting attendees was already added to the [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent), [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review), and [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) pages on the platform website in another ticket. This line should be concise-but-consistent with that guidance.

Happy to make adjustments as needed. Thanks!

**Comment by jimuhh** [comment]
Reviewed and confirmed. Thanks @briandeconinck!

**Comment by briandeconinck** [comment]
@shiragoodman closing this issue as complete!
