### ISSUE TITLE
Design | Profile | Messaging for Invalid Characters (non-ASCII)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45761]
## Background

We need to limit the  character set for mailing and home addresses to ASCII only. The error message for users will be shown in-line immediately after a user moves focus off one of the address fields.

## Tasks
- [x] Create mock depicting recommended approach
- [x] Review with Content team to create appropriate messaging  

## Acceptance Criteria
- [x] Mocks reviewed and approved
- [ ] FE solution is documented
- [x] Sketch files are updated 
- [ ] Let PM know when ready for FE implementation

**Comment by cgednalske** [comment]
Hi @SKasimow and @adamwhitlock1  -- Here are the [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/zx4KgMl) and [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/ygvQP7o) mockups with the approved content.

**Comment by SKasimow** [comment]
Thanks Christina!

@adamwhitlock1 I added mocks to your ticket so you'd have it all together.

**Comment by SKasimow** [comment]
Closing
