### ISSUE TITLE
[AWS / IAM] Group/team policy update for Ninja-Pigs

### ISSUE THREAD

**Issue by aaronhietpas** [department-of-veterans-affairs/va.gov-team#45765]
## Who is the devops resource on your team?
@aaronhietpas 

## Description

Need to add group lighthouse-ninja-pigs to existing users.

## Background/context 
- team-matsomoto was split into two teams, one being ninja-pigs. Existing team members need this new group added to the user.

## Technical notes
- Once users are added to new team and verified that everything looks good, new ticket can be created to remove matsumoto.

---
## Tasks
- [] Add lighthouse-ninja-pigs to users "Aaron.Hietpas", "David.Lennon" and "Nichole.Harris", 

## Acceptance Criteria 
- [] Existing access/functionality around groups must be maintained
- [] Group is added to the 3 users.

---
### Reminders
- [] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
Listed users added to lighthouse-ninja-pigs.
