### ISSUE TITLE
[FE] [SPIKE] Investigate how to parallelize feature toggle and session calls

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#45775]
## Background
When initially loading the app, we first make a call to the vets-api feature toggles endpoint, parse the response, and only then call the check-in sessions endpoint. Let's see if we can parallelize the calls.

## Tasks
- [ ] [FE] Investigate parallelizing the calls & implement, if this is possible
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
Spike findings:
- Feature toggles endpoint call is done site-wide, and synchronously, so in it's current state, we are not technically able to run this call in parallel with anything else. Options to fix are:
  - Significantly divesting ourself from site-wide shared code (which we are somewhat in progress of looking into)
  - Seeing if it would be possible to pull this call / client into our own code-bas, and bypassing the shared version. If this is possible, we could run the call asynchronously
- What we _can_ do short-term, however, is allow our site to be interactable while we're waiting for the getSessions call to complete. What this means is that veterans can be filling in their login credentials while this call is completing, rather than waiting the extra ~2s for the form to appear. We should also add a guardrail that does not allow people to submit the form until the getSession call has come back.

I will be implementing the short term solution as part of this ticket. We can consider splitting out the longer term solutions into a separate spike to investigate further.
