### ISSUE TITLE
Review Sidekiq K8s Failing Jobs

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45778]
## Description
The `EVSS::CreateUserAccountJob` is failing with the error `ArgumentError: Unable to uniquely identify request! Please check your services config. Matched endpoints: [[]]`. This job failure should be investigated and it's possible that it's related to betamocks. [See retries.](https://dev-api.va.gov/sidekiq/retries)

## Tasks
- [ ] Investigate `EVSS::CreateUserAccountJob` failures

## Acceptance Criteria
- [ ] Failed `EVSS::CreateUserAccountJob` jobs are completing successfully

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_
