### ISSUE TITLE
[FE] - Append a URL Param for Error Type

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#45777]
## Description
Our error pages could give a little more info for both the user and analytics purposes.

One idea was to append a URL param with an error type i.e. ?error=bad-token

## Tasks
- [ ] Append a URL param with an error type i.e. ?error=bad-token
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by brdunfield** [comment]
At one point I had partially implemented this functionality (which was later removed as it wasn't necessary for what we were trying to do)

Link to that PR in case it helps whoever's picking this up:
https://github.com/department-of-veterans-affairs/vets-website/pull/20895/files

**Comment by brdunfield** [comment]
@benbrasso-agile6 For validation starting tomorrow, we just want to see an 'error' parameter (with a variety of values) on the error page in google analytics. We shouldn't have any more just generic error page visits without an error parameter.

e.g.
`/error?error=bad-token`

If this isn't clear or doesn't make sense with what's in GA let me know and we can sync.

**Comment by benbrasso-agile6** [comment]
In production?

**Comment by brdunfield** [comment]
Either staging or production works for me. I wasn't sure if we had GA in staging!

**Comment by benbrasso-agile6** [comment]
this is on prod. i can run it again tomorrow, but this is what's in there now

![Screen Shot 2022-08-30 at 5.41.32 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/9c5cfebf-ba22-4e13-bdaf-e85f738f0a68)

this is day of check in

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20220830&_u.date01=20220830&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22health-care~2Fappointment-check-in~2Ferror%22,0%5D%5D&explorer-table.plotKeys=%5B%5D/

**Comment by benbrasso-agile6** [comment]
From today in prod

![Screen Shot 2022-08-31 at 9.44.56 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/dcbcec8c-2d2f-4cdd-b838-13f676b94284)

**Comment by benbrasso-agile6** [comment]
Should we still be expecting the /error/ page without a param?

**Comment by brdunfield** [comment]
No, we shouldn't. Since the deploy went out later in the day though it makes sense that's mostly what we still saw.
It might be possible that we'll see a few /error/ pages as folks re-open their browsers with old versions, but those should trail off with time!

**Comment by benbrasso-agile6** [comment]
@brdunfield I am still seeing /error/. But, I think I recommend closing this ticket. I will start a new one for us once I get a mmoment to think through /error/ and the no token one.

**Comment by brdunfield** [comment]
Sounds good! Closing for now
