### ISSUE TITLE
Sidekiq EKS configmap updates

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45776]
## Description
The [settings.yml file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2) for the dev environment will need to be migrated over to a configmap for Sidekiq in K8s. The [vets-api k8s deployment also uses the same values](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-tools-backend/vets-api/dev/settings-configmap.yaml), but has been found to be of sync with what is currently in the devops repo. The settings should be reviewed for correctness. Additionally, we should try to use helm chart values where applicable and utilize parameter store instead of the legacy credstash. 

## Tasks
- [ ] Review settings.yml
- [ ] Sync vets-api and sidekiq (k8s) settings
- [ ] Update accordingly

## Acceptance Criteria
- [ ] Sidekiq configmap is up to date

## How to configure this issue
- [ ] _Attach a Milestone_
