### ISSUE TITLE
Determine desired outcomes and measurements

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#45783]
## Issue Description
Clarify users, use cases. Ask how might we know we're collecting and presenting useful information?

Mural: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1660596741123/1be9a695e25cf1cda7fd73336d62de3295bf4d62?sender=u4f7db1750f2355f805e60296

## Tasks
- [x] What would be the desired user outcomes?
- [x] How might we measure these outcomes?
- [x] Lightweight personas for consumers of this map?

## Acceptance Criteria
- [x] Document outlining problems to address, users, outcomes, measurement of outcomes
