### ISSUE TITLE
Implement HPA for k8s Sidekiq

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45780]
## Description

HPA (Horizontal Pod Autoscaling) should be improved for the k8s Sidekiq deployment. We want to scale based on queue size and not basic metrics such as CPU. The infra team is discussing, enabling scaling based on any exposed metric [KEDA as seen here](https://medium.com/swlh/scaling-sidekiq-workers-on-kubernetes-with-keda-6515c4ca8df4).

### Notes

- The KEDA operator will create a custom control loop that will allow for scaling to the desired replica count based on custom metrics exposed by the application (or DataDog). The basic K8s resources cannot be used because it does not allow scaling based on metrics that the application defines. The KEDA operator will use a CRD, the ScaledObject to create an HPA and scale based on Redis/Sidekiq queue size (the custom business logic).

## Tasks
- [ ] Investigate Keda
- [ ] Implement Scaling using KEDA
- [ ] Remove the existing HPA used by Sidekiq

## Acceptance Criteria
- [ ] Sidekiq k8s workers are scaling properly via queue size

**Comment by LindseySaari** [comment]
puma HPA based on custom metrics up and running in dev 🎉 

![Screen Shot 2022-11-17 at 12.35.00 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/37df6b9f-1e3a-4245-be22-9711e1eef7ed)
