### ISSUE TITLE
Clean up Feature Flags

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45787]
## Tasks
Clean up the following feature flags:
- check_in_experience_translation_day_of_enabled
- check_in_experience_translation_pre_check_in_enabled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
