### ISSUE TITLE
Console UI needs a Sentry auth token for API requests

### ISSUE THREAD

**Issue by mhaley37** [department-of-veterans-affairs/va.gov-team#45789]
## Description
The Console UI app integrates with VSP organization of [Sentry](sentry.vfs.va.gov/) by using the API to retrieve issues.  This process works but is using a user-based auth token (with my user).  

While this works, it is not recommended because of:
![image](https://user-images.githubusercontent.com/2686352/184955467-e5f3e3d7-2f62-4baf-9d7a-a1c6e3c3d1f4.png)

Per [Sentry docs](https://docs.sentry.io/api/auth/) auth tokens can also be associated with an _organization_ account.  This would be a better approach.

---
## Tasks
- [ ] Create a new _organization_ account based auth token for the Console UI to interact with sentry.  This token only needs access to the VSP org, and only `event:read` scope. 

## Acceptance Criteria 
- [ ] Token can be used to authenticate against the [list-project-issues](https://docs.sentry.io/api/events/list-a-projects-issues/) API endpoint, for the VSP org.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
@mhaley37 I followed the link you posted regarding creating auth token. Are there any specific perms that you require? I presume this is only for read, correct?

**Comment by mhaley37** [comment]
Hi @oseasmoran73 , yes, we'll need `event:read` permissions for the vsp organization, that should be it.
Thanks

**Comment by oseasmoran73** [comment]
@mhaley37 Sweet! I think we have a couple of options here: looks into the integration doc you linked or potentially adding `va-vsp-bot` as a user + in your project, have token created and pass over securely. Just thinking out loud. Will do some research on our end as towards which approach will be taken.

For full transparency, I like to do a bit of investigation (primarily asking questions to understand requirement), but once it gets picked up in the upcoming sprint, should we have additional questions we will def reach out

**Comment by mhaley37** [comment]
No longer needed.
