### ISSUE TITLE
K8s Sidekiq Liveness/Readiness probes

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45782]
## Description
We will want to include Liveness/Readiness probes for the K8s Sidekiq pods. This will ensure that pods are ready and able to serve requests properly. We can most likely run something like `ps aux | grep sidekiq` to ensure that Sidekiq is up and running, but there could be other possibilities. 

## Tasks
- [ ] Investigate Liveness/Readiness Solution
- [ ] Implement Liveness/Readiness Solution

## Acceptance Criteria
- [ ] Liveness/Readiness is functioning properly upon pod creation

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_
