### ISSUE TITLE
Onboard Sidekiq dev to Argo

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45784]
## Description
The new K8s Sidekiq offering will need to be onboarded to Argo. The operations team has a new onboarding process for K8s applications that differs from the previous jsonnet approach. 

## Tasks
- [x] Ask infra for Onboarding Docs
- [x] Implement config to onboard app to argo

## Acceptance Criteria
- [x] Sidekiq K8s exists in Argo

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_
