### ISSUE TITLE
Implement K8s Sidekiq 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#45785]
## Description
Similar to the k8s vets-api application, the sidekiq deployment will need to live in the k8s environment. The vets-api-server won't be able to process background jobs without this

## Tasks
- [x] Sidekiq is running in dev
- [x] Sidekiq is running in staging
- [x] Sidekiq is running in prod
- [x] Ensure ECR push and image tag update are synced properly

## Acceptance Criteria
- [x] Sidekiq is running in all envs in the k8s clusters
