### ISSUE TITLE
[SPIKE] [FE] Look into refactoring Error pages to make them less opaque

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#45795]
## Description
Our error pages are all handled from various internal states and data checking. This can make it difficult to tell how different error pages are reached, and difficult to make data about error pages visible to external processes like analytics.

This spike is meant to brainstorm ways we could refactor our error page(s) to make them both more understandable from a code perspective, and more exposed to analytics.

In a recent update, an error type string has been added to the reducer. The error component is now setting the max-validation error message based on error value. This should be extended to all types of errors. This would involve setting the error type string wherever we are routing to error pages. Also we may want to setup an object that matches error types to error messages/headings.

It would be nice to also explore ways to locally test different error states. In the case of the max-validation error page, we need to get a 410 code from the validation endpoint. Is there away to make this easy to do?

## PoC

We decided to go with a phased approach as tackling this all in one go would be a very large refactor. 

### Phase One

[issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50222)

Store all errors as strings in Redux state. ie. dispatch the setError action when an error occurs, usually in a side effect like an API call.
```dispatch(setError('bad-token'));```

Create a higher order component to wrap the application and handle errors by routing the application to the error page. Later this could include more robust error reporting using GA, Sentry or Datadog. This also give us the flexibility to create other side effects like add more information to the state object for more complicated error messaging.
```
    useEffect(
      () => {
        if (error) {
          goToErrorPage(error);
        }
      },
      [error],
    );
```

The router utility `goToErrorPage` will use the error string to add a query string to the url for GA tracking. This gives us more flexibility to get creative with the URL parameters. 

Replace utility functions like `appointmentWasCanceled` in the Error page for pre check in with a check against the error string in the Redux store. `if( error === 'appointment-cancelled')`

### Phase Two

Improve Readability of the error handling code, specifically the code on the pre check in Error page. 

One possibility would be to let each sub component handle the logic of what to display given the error from the store. For example, we could create a component for the va-alert called VaErrorAlert and let that handle it's display logic based on the error code from the store. 

The how to links and accordion provide an additional challenge due to the amount of logic present in those components already and their wide use for other pages of the app. We should create alternate versions of those components just for the error page and create dumb components that take props and replace the ones used in other areas of the app so that we don't duplicate markup.

## Tasks
- [ ] Create issues for phases
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] FE team signed off on approach
