### ISSUE TITLE
Update artifact language to clarify linking artifacts in ticket

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45796]
## User Story
I am a Governance team member supporting the Collaboration Cycle trying to complete my review of the VFS product but I don't have access to the necessary artifacts because VFS teams don't provide the information I need and/or don't validate access which makes me feel super frustrated, angry and annoyed.

Assignee: @CherylEvans 
Peer Reviewer: @seanasewell 

## Description
Sticky notes identified in Staging Review workshop
![image.png](https://images.zenhubusercontent.com/619d1b3396a3389c5e2dd17f/da9b8b51-f5ce-40a3-a098-21db0a500bd0)

## Problem Statements
[Mural Workshop List](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=u5d556df3430960096c525037)

## Impacted Artifacts
[Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)
Potentially [Platform Website Staging Review touchpoint page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review)
[45757 - Allison - Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2334228481/45757+-+Allison+-+Staging+Review+-+Moderator+Responsibilities)

## Tasks
- [x] Staging Review Code Block: Change VFS Action "Add all artifacts **ONLY**..." to "Link all artifacts **ONLY**"
- [x] Consider VFS action checkbox: "I confirm the environment is available and test users have been provided"
- [x] Evaluate where to instruct teams "Do not comment on this ticket, please update the Staging Review section of the ticket or discuss in slack" (Please wordify)
- [x] Evaluate updating script
- [ ] Evaluate updating headings in CC Request ticket - SG: can ignore for now.
- [x] Review 45757 - Allison - Staging Review - Moderator Responsibilities Schedule/Step 7 for consistency 

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS team members understand where to link artifacts
- [x] VFS teams understand that we do not want comments on the ticket

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@seanasewell I have made the following edits, and am ready for your review.
[Platform Website Staging Review touchpoint page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2343600150/Cheryl+Draft+-+Copy+of+Staging+review), added the following verbiage to the Moderator script: "Do not make responses or comments on the issue ticket, instead please update the Staging Review section of the Collaboration Cycle Request ticket or discuss in the appropriate Slack channel."
[Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block), I added the following: "Link all artifacts **ONLY** in the Staging Review artifacts, practice area section below.  **Do NOT add artifacts to Comments section**" Specifically, the word "link" was added, as well as "the Staging Review artifacts, practice area section below".  This was changed for specificity, as well as simplicity. 
[Staging Review Code Block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block), Checkbox "I confirm the environment is available and test users have been provided." has been added.

I also need more clarification on task: **Evaluate updating headings in CC Request ticket.**  
@shiragoodman  Can we discuss the specifics for this task?

**Comment by seanasewell** [comment]
@CherylEvans 

I know that this doesn't fall in your lap to fix but since you are working in [Platform Website Staging Review touchpoint page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2343600150/Cheryl+Draft+-+Copy+of+Staging+review), I noticed that "non- launch-blocking" has an extra space in it. It's in the sentence above the one you edited.

For the checkbox "I confirm the environment is available and test users have been provided", would it make more sense to use the word "working", "accessible", or "reviewable" rather than "available". Maybe even a phrase like "I confirm the testing environment can be accessed and that test users have been provided". 

Everything else looks good to me!

**Comment by CherylEvans** [comment]
@shira @seanasewell I made the typo correction you recommended, Sean.  I have made all of the changes to the source pages, and will close ticket once I ensure that all changes have been published.  Thank you!

**Comment by CherylEvans** [comment]
@shiragoodman Tasks completed, AC met, and changes published.  Closing ticket and moving to "closed" pipeline.
