### ISSUE TITLE
Design | Profile | BAI | Internal UAT planning

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45807]
Plan for internal UAT sessions. This is based on assumption that VA Profile will support modifying a few internal Profile team member's accounts for testing purposes.

## Tasks
- [ ] Provide VA Profile with UAT participants info
- [x] Outline and review what UAT participants should test
- [ ] Notify PM to open tickets for any issues discovered

## Acceptance Criteria
- [ ] UAT participants have access to test feature
- [ ] Provide any support needed

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow! Here are the materials for BAI UAT - [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/uat/research-plan.md) and [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/uat/conversation-guide.md). The convo guide is included as a basic outline / check list - so we make sure to go over everything before updating/confirming and causing the alerts to go away. I figured it might be a pain to reinstate those mid-UAT. 

Speaking of reinstating alerts, one thing I'm still working out with Tom is noted under Observers/Participants in the Research Plan. In case we need to, Tom believes he would be able to re-add or fix the BAI flags on our accounts if needed without going back to VA Profile, but he is checking on that. I've noted that if he is not able to do that we might need to see about having someone from VA Profile present or on standby in case we need assistance.

**Comment by SKasimow** [comment]
@cgednalske - this looks great!

**Comment by Samara-Strauss** [comment]
@cgednalske this all looks great to me! Thanks for being so thorough even though these sessions are internal. Given that they are internal, I don't believe you need to submit this stuff to Shane for review. I think we can just say the materials are good to go, and we are ready to move on to testing.

Also, given that it looks like the convo guide does have some structure, you might want to go ahead and schedule short sessions with each of us and let everyone know not to mess with the BAI before your session with them if they happen to see it when logging into their account. I don't want your testing to accidentally get messed up.

**Comment by cgednalske** [comment]
Great! Thank you both!

@Samara-Strauss sounds good 👍  I think you're right that we don't need to submit to Shane. I can double check, but I'd be surprised if we do. Also that reminds me - we touched on this briefly in standup, but I'm wondering your thoughts as well. Currently, I have a combined session to go through each account with us all in attendance to observe any possible issues. Would it be more helpful and better for schedules to have a short session per person as you've mentioned above? I had defaulted to something combined but could definitely see either working well depending on if we want everyone in attendance or not.

**Comment by Samara-Strauss** [comment]
@cgednalske I think how you want to navigate testing is up to you. If you want to do a group session, that works. If you think individual sessions would be easier to manage, that works as well. Totally up to you.

**Comment by cgednalske** [comment]
@Samara-Strauss Ok, great! I'll keep it at one longer session with everyone then. That way if Tom will be standing by to manage the flags (if it turns out that is possible), he won't need to attend so many + we'll have more eyes present in case of issues. 👍  

Best case scenario, I'll aim for Friday if no tickets come from the staging review. Just saw you'll be out most of next week, so if it needs to be later in the sprint, do you prefer I schedule it for when you are back and fully available (next Friday for example)?

**Comment by Samara-Strauss** [comment]
>  so if it needs to be later in the sprint, do you prefer I schedule it for when you are back and fully available (next Friday for example)?

Yes please!

**Comment by cgednalske** [comment]
@SKasimow this has been open for a bit, but I don't think it needs to be. Do you think we can close it?

**Comment by SKasimow** [comment]
Yes!
