### ISSUE TITLE
[FE] 10-10EZ - Medicare Claim number: Determine solution to "required" attribute for bug

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#45802]
## Background
We received an email from Tarsha stating that applicants are getting blocked from proceeding through the 10-10EZ at the Medicare effective date page.
It was quickly determined that, although the field itself was hidden to 75% of applicants, the 'requirement' to complete the field was not.  This caused the page to fail due to missing information.  

## Tasks

- [x] Turn feature toggle to 100% to mitigate impact to applicants
- [x] Determine permanent solution to allow "required" attribute to sit behind the feature toggle with the code
- [x] Test solution with positive and negative scenarios to ensure the feature toggle is effective

## Acceptance Criteria
- The Medicare Claim Number field will remain as a required field, however the field and the 'required' attribute will be hidden behind the feature toggle so that it may be launched in a phased manner, without blocking applicants from moving forward through the 10-10 EZ.

**Comment by hdjustice** [comment]
Duplicate ticket to #45803.  closing
