### ISSUE TITLE
[FE] [SPIKE] Investigate page load slowness week of July 26

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#45811]
## Background

@benbrasso-agile6 posted performance numbers showing a pretty bad week july 26 -> aug 1 in slack: https://dsva.slack.com/archives/C02G6AB3ZRS/p1659450354659879

## Tasks
- [ ] [FE] Investigate issue 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

**Comment by acrollet** [comment]
@loripusey I've spent a good deal time on this so I created this issue to track.

**Comment by acrollet** [comment]
Wrapped up investigation, summary and actions taken copied in from slack: https://dsva.slack.com/archives/C02G6AB3ZRS/p1660688785487609?thread_ts=1659450354.659879&cid=C02G6AB3ZRS


Summary:

It appears that the higher figures were driven by one really bad day, and maybe even one really bad hour or sample. It may have been coincident or caused by vets-api issues, but I haven’t been able to confirm that with the data/tools available. Zooming out, we don’t see an overall downward performance trend.

Actions taken:

- The FE team (and @Mark Dewey [He/Him]) now have access to speedcurve to help identify areas for improvement
- I’ve added synthetic monitors for check-in and pre-check-in landing page response times to the check-in [datadog dashboard](https://vagov.ddog-gov.com/dashboard/zps-5fk-azw/check-in-vets-api?from_ts=1660673778222&to_ts=1660688178222&live=true)
- I’ve identified an [actionable improvement](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/45775) for initial page load performance which we’ll be picking up soon
- Gently [pushed](https://dsva.slack.com/archives/CBU0KDSB1/p1660688704063239?thread_ts=1660332627.568389&cid=CBU0KDSB1) on the workspaces implementation timeline
