### ISSUE TITLE
Design | Profile | Notification Preferences 1095B | Design Intent

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45814]
### Background

The next step in the Collab Cycle touchpoint for Notification Preferences - 1095B is the Design Intent (based on the feedback from the Collab cycle kick-off [#45798](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45798))

Note: all requested artifacts should be posted at least two days before the scheduled Design Intent.
Artifacts should be placed in the specific, designated practice area sections below. 

---
#### Tasks: Design Intent Artifacts
- [x]  Whiteboard sketch or other lo-fi prototypes or wireframes
   - [User has an email on file, additional info component is closed](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WK8xJy8)
   - [User has an email on file, additional info component is open](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/ygjKLao)
   - [User doesn’t have an email on file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/5zZvbp/a/JnEgDg9/r/8vJ2m8)
- [ ]  User flow
- [ ]  Research plan
- [ ]  Any other artifacts you have so far

#### Acceptance Criteria

- [ ] Create all necessary artifacts and add links to this ticket for each
- [ ] Let PM know when ready to schedule Design Intent meeting
- [ ] Review feedback tickets and comment on the ticket as needed and/or if there are any questions or concerns

**Comment by andaleliz** [comment]
@SKasimow thanks for creating this! Any idea when we're thinking of doing research for this? I see "research plan" as part of the artifacts. I can go ahead and create that this sprint if we want to include it in the design intent.  

I'm on the fence about whether or not we should get sign off from the 1095b legal review _before_ design intent, or if we should just go ahead and get the design reviewed with the disclaimer that the content might change? The only major thing I can see changing is that the legal team will say we can't hide that content in an additional info component.  If that's the case, then we'll need to explore something pretty different from what we have now.

**Comment by mtcA6** [comment]
Since the design intent is closed I'm going to close this ticket out as well. If/when we pick this work up next year we'll create new tickets. I'm going to leave the epic and the research plan tickets open.
