### ISSUE TITLE
Swap bullets on Life Insurance Dividend Payment Options page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#45821]
## Issue Description

Steve asked us to change 2 bullets on the [Life Insurance Divided Payment Options](https://www.va.gov/resources/life-insurance-dividend-payment-options/) page. 

Under Option 7, he asked us to swap the bullets to:
- A direct deposit of money into your bank account, or
- A U.S. Treasury check mailed to you (in limited situations)

This is due to an effort by treasury to make all payments EFT. 

---
## Tasks
- [ ] Update bullets in Drupal with any tweaks needed for site style (Katherine)
- [ ] Review & send to stakeholder if needed (Laura)
- [ ] Copyedit with prepub checklist (Megan)
- [ ] Publish (Megan)
- [ ] Notify stakeholder change is live (Laura)

## Acceptance Criteria
- [ ] Page is live with updated bullets

**Comment by katherine-fung** [comment]
Hi @laurwill, I swapped these bullets under Option 7 per the stakeholder request: 

http://preview-prod.vfs.va.gov/preview?nodeId=15062 

I also tweaked Option 2 and Option 3 because they included incomplete phrases preceding bulleted lists. 

I converted the bulleted list under Option 3 to plain copy, because it was a list of facts, rather than a series of related things.

**Comment by laurwill** [comment]
Thank you Katherine! Your changes look great, I just tweaked one of the list intros slightly. I also updated the 2021 interest rates in option 3 with 2022 rates provided by stakeholder, and adjusted a couple of links to follow current site style.

@megzehn , this is ready for copyedit, and we can go ahead and publish if the new bullet in Option 7 looks good to you. If we change the wording on that, I'll want to send to Steve to approve. Lmk if you have questions!

http://preview-prod.vfs.va.gov/preview?nodeId=15062

**Comment by megzehn** [comment]
This page is now copyedited and published. Over to you, @laurwill!

**Comment by RLHecht** [comment]
I let Steve know these changes are live. Closing this ticket!
