### ISSUE TITLE
**Discovery** BE | Profile | Notification Preferences 1095B

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45826]
## Background
In preparation for 1095B backend work...

## Tasks
- [ ] Identify technical POC at VA Profile.
- [ ] Determine environment availability for testing (with data) and timelines.
- [ ] Discuss any API changes/updates (version or schema).
