### ISSUE TITLE
[cFSR] Updating resolution options with validation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#45837]
## Issue Description
Resolution options needs custom validation for options selection in conjunction with the checkbox for the waiver specifically. Resolution comments also needs currency validation that is customized to be less than the current balance. 

---
## Tasks
- [ ] Fix resolution options page validation so there must be a selection
  - [ ] validation must include checkbox for waiver selection
- [ ] Fix resolution comment validation to be valid currency and less than current balance. 

## Acceptance Criteria
- [ ] Custom validation/requirements set for new resolution options and comments. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
