### ISSUE TITLE
Consider Playbook landing as containing all comms resources

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#45833]
## Question:
How can we make the Playbook a clearer landing for teams to find and seek out when they need comms guidance?

## Tasks
- [x] Consider naming of our resources
- [x] Consider positioning of our resources
- [x] Generate copy and layout for proposed landing
- [x] Review w/ team for consideration

## Acceptance Criteria
- [x] Agreed upon approach, finalized layout
