### ISSUE TITLE
[PM] 10-10CG - Review Updated PoA Verbiage

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#45830]
## Background

In late July, the CG Stakeholders received approval to accept general Power of Attorney documents, even without any medical stipulation.  With changes to which documents are acceptable for signing as a representative, stakeholders have provided us with a new set of verbiage to use on the pages that reference medical content.  This verbiage needs to be reviewed internally before being implemented.

### Page 1
**Original**: A representative must have legal authority to make medical decisions for the Veteran.  If you choose this option, we'll ask you to upload a document that proves you have this authority.
- **Suggested**: A representative must have legal authority to make decisions for a Veteran.  If you choose this option, we'll ask you to upload a document that proves you have this authority.

**Original**: We can only accept a document that proves you have legal authority to make medical decisions for the Veteran.  This type of document is sometimes called a medical proxy or medical power of attorney.
We can't accept a marriage certificate, driver's license, or release of information form.  We also can't accept a general or financial power of attorney without a medical stipulation.  Uploading a document that we can't accept may delay the application process.
- **Suggested**: We can only accept a document that proves you have legal authority to make decisions for the Veteran.  We can't accept a marriage certificate, driver's license, or release of information form.  Uploading a document that we can't accept may delay the application process.

**Original**: A representative with legal authority to make medical decisions for the Veteran
- **Suggested**: A representative with legal authority to make decisions for the Veteran

### Page 2
**Original**: We can only accept a document that proves you have legal authority to make medical decisions for the Veteran.  This type of document is sometimes called a medical proxy or medical power of attorney.
- **Suggested**: We can only accept a document that proves you have legal authority to make decisions for the Veteran.

**Original**: Choose a document that we can accept (like a medical proxy or medical power of attorney).  Don't upload a marriage certificate, driver's license, or release of information form.  And don't upload a general or financial power of attorney without a medical stipulation.  Uploading a document that we can't accept may delay the application process.
- **Suggested**: Choose a document that we can accept (such as a valid Power of Attorney, legal guardianship, or similar legal documentation).  Don't upload a marriage certificate, driver's license, or release of information form.  Uploading a document that we can't accept may delay the application process.

**Original**: It's easy to upload the wrong file by mistake.  We want to make sure that we review the right document (like a medical proxy or medical power of attorney).  This will help speed up your application process.
- **Suggested**: It's easy to upload the wrong file by mistake.  We want to make sure that we will review the right document (such as a valid Power of Attorney, legal guardianship order, or similar legal documentation).  This will help speed up your application process.

## Tasks
- [x] Review current designs and create mockup with suggested changes
- [x] Review the changes with the Content team/Danielle Theirry
- [x] Update mockup with agreed advice from Content team
- [x] Present to PMs/team for agreements

## Acceptance Criteria
- A completed design update with new language that no longer requires a medical stipulation for acceptable documentation on the Sign as a Rep pages.

**Comment by jessicastump** [comment]
This was reviewed during the weekly content meeting today. Danielle suggested a couple of minor edits:
1. There was an instance on page 1 “a Veteran” changed to “the Veteran”
2. (such as a valid Power of Attorney, legal guardianship, or similar legal documentation) was adjusted to (such as…or other legal document). This was also added to page 1, additional info component content area.

Sketch file links below (Desktop): 
[Representative Docs: Page 1](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/4bV4Px/a/dlREeJZ/)
[Representative Docs: Page 2](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/4bV4Px/a/bgky1WV)
[Representative Docs: Page 3(upload file check page)](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/4bV4Px/a/PG82w48/r/rdQj3A)

**Comment by hdjustice** [comment]
This looks perfect!  Thank you @jessicastump!
