### ISSUE TITLE
Group Peer Review of Practice Area Operational Guidance

### ISSUE THREAD

**Issue by chaseakirby** [department-of-veterans-affairs/va.gov-team#45839]
## User Story
As a Governance team member, I want to review other practice area's operational guidance so that I understand the process they take for each review.

Peer Reviewer: All

## Description
Last sprint we created first draft of practice area operational guidance, we will review each other's and suggest any changes as well take this time to understand the other practice areas and where we may note extra coordination (if needed).

## Problem Statements
[Mural Workshop List](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1658842757076/f68e85e021f855dfecf67be0a8663874b3129996?sender=u5d556df3430960096c525037)

## Impacted Artifacts
[How to complete an accessibility review for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2059763776/How+to+complete+an+accessibility+review+for+Staging+Review)
[How to complete a Content review for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302836931/How+to+complete+a+Content+review+for+Staging+Review)
[How to complete an IA review for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302312688/How+to+complete+an+IA+review+for+Staging+Review)
[How to complete a Design review for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302869722/How+to+complete+a+design+review+for+Staging+Review)

## Tasks
- [x] Review the 4 impacted artifacts in Confluence and comment on anything that is concerning (eg. does not align across practice areas, expectations of what a specific practice area should be doing, gaps, overlaps, inconsistencies, etc.)
- [x] Check your name in the box below to indicate you have completed your review

## Peer Review
- [x] All Governance team members review each practice area guidance
  - [x] Allison
  - [x] Brian
  - [x] Cheryl
  - [ ] ~~Clayton~~
  - [ ] Jim
  - [x] ~~Sean~~
  - [ ] Shira

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@shiragoodman I looked at all the documents and made some comments. I agree with Cheryl, that these are all written in different tones and there are some areas that can be the same.

- How we list the steps
- If the first step is always to open the staging ticket and review artifacts, it should be written the same
- Most talk about documenting in the drafting template, this can also be the same.

**Comment by jimuhh** [comment]
@allison0034 Agreed. When the instructions aren't practice-area specific, we ought to standardize them. Perhaps we should set up a mtg to review the different directions people wrote, pick out the bits we like best and then mash them up into a single standard set of instructions?

**Comment by shiragoodman** [comment]
@jimuhh @allison0034 right now, don't worry too much about the flow. I'm more concerned about the content in the guidance. I want you to be critical when reading the guidance outside your practice area. For example, if I were a content specialist reviewing the accessibility guidance, I would ask myself, "Does this match my expectations of what is included in an accessibility review?" "Where are the overlaps between content and accessibility?" "I had thought a11y would do XXX, but I don't see that documented anywhere"
