### ISSUE TITLE
Resolve Documentation Comments from Content Team Feedback

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#45847]
# Description
The content team has reviewed our documentation for the Product Directory and we have some feedback and comments to resolve as a result.

# Tasks
- [ ] 
- [ ] Resolve comments on the [Platform Documentation](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2193359369/VFS+Product+Directory+-+Platform+Documentation?atlOrigin=eyJpIjoiMGEwOTM2MTA3YmQ2NGYyNGJhMDZhNDMxNjAyNzgxNzIiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)
- [ ] Resolve comments on the [Term Glossary](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2311946314/VFS+Product+Directory+Term+Glossary?atlOrigin=eyJpIjoiZDQ3OTM4ZmJjOWQ0NDBmMGFmYjgyNDhjYmRhODU3MDMiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)
- [ ] Resolve comments on the [User Guide](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2194374767/VFS+Product+Directory+-+User+Guide?atlOrigin=eyJpIjoiNDBmN2VhODdkNjI5NDY4NjkxYzAwYWZkMjYyYTA0OWYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)

# Acceptance Criteria
- [ ]

**Comment by rsmithadhoc** [comment]
- [PR](https://github.com/department-of-veterans-affairs/product-directory/pull/421) to update product page text.
- Updated all other pages.
- Only thing left is to find where to put the glossary on the platform website and if we want to house it in that Confluence space. We could make a copy of it, but then we would have two spots with the same content to maintain.

**Comment by rsmithadhoc** [comment]
- Created [platform website drafts](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2333278213/VFS+Product+Directory+Guides) for the guides. Running by Joe and content before those get published to the platform website.

**Comment by rsmithadhoc** [comment]
- Feedback was addressed and pages were published.
- Unfortunately, the guide pages were blank due to the Page Include macro not working as expected.
- I will update those pages to have the content be on the docs pages in Getting Started. I will remove the pages that were being embedded so that we don’t have two places with duplicate info to update.
- More feedback to address as well https://dsva.slack.com/archives/C01AS05BQ79/p1661285915254529?thread_ts=1661284944.199339&cid=C01AS05BQ79

**Comment by rsmithadhoc** [comment]
- https://vfs.atlassian.net/wiki/spaces/GS/pages/2333278213/VFS+Product+Directory+Guides pages now contain the content instead of a page include
- https://vfs.atlassian.net/wiki/spaces/GS/pages/2294120662/VFS+Product+Directory and product page feedback addressed
- Awaiting the platform website deploy but setting this for review
