### ISSUE TITLE
[AWS / IAM] Group/team policy updates related to team Matsumoto

### ISSUE THREAD

**Issue by aaronhietpas** [department-of-veterans-affairs/va.gov-team#45845]
## Who is the devops resource on your team?
@aaronhietpas 

## Description
Need to update IAM AWS configs related to lighthouse-matsumoto due to team no longer existing.

## Background/context 
- Team Matsumoto was split into two teams, ninja-pigs and caracal. Members of this IAM group need to be moved to either new team or have the group removed.
- lighthouse-matsumoto group needs to be removed because team no longer exists.
- lighthouse-developers-2 policy may need to be removed, if VSP ops determines it needs to be. It currently may be redundant/unused due to new policies created for ninja-pigs and caracal

## Technical notes
- Move users to correct teams, or remove lighthouse-matsumoto. Remove lighthouse-matsumoto group. Possibly remove lighthouse-developers-2 policy as it is copied into the new policies for caracal and ninja-pigs.

---
## Tasks
- [x] Add lighthouse-caracal and remove lighthouse-matsumoto for users "Mark.Viterna" and "Kristen.Brown"
- [x] Remove lighthouse-matsumoto from "Kevin.Cranmer" (not on teams Ninja-Pigs or Caracal)
- [x] Remove lighthouse-matsumoto group
- [x] Determine if lighthouse-developers-2 policy is needed, and possibly remove.

## Acceptance Criteria 
- [x] Correct groups are assigned to above users.
- [x] lighthouse-matsumoto group is removed.
- [x] (Optional) Remove policy lighthouse-developers-2

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jsgarmon** [comment]
Work completed in PR above.
