### ISSUE TITLE
Update QAS Team Support Bot Participation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#45851]
# Description

We need to work with the SRE team to update the support bot with new categories for help that includes at least

# Tasks
- [x] Ingest Support Bot request data from the Google Sheet to BigQuery
- [x] Ingest Support Bot category data from the Google Sheet to BigQuery
- [x] Update Support Bot categories to include --
  * "Test Failure"
  * "Tool Access"
  * "Test Accounts / Data"
  * "CI Error"

# Acceptance Criteria
- [x] Support bot data is available in BigQuery
- [x] Updated categories that cover our common support requests are available in the support bot via Slack

**Comment by holdenhinkle** [comment]
Re New Categories (or `Topics` as the Support Bot calls them) to Add:
"Test Failure" - ADD
"Tool Access" - `Testing Tools` already exists
"Test Accounts / Data" - `Test Accounts` already exists
"CI Error" - ADD

For reference, here are the currently active topics:
```text
Access Request
App Logging/Monitoring
App Setup
Collab Cycle
Design System
Design System
Environments
Failed Deployment
Forms
Google Analytics/Domo
Off-Cycle Deployment
Orientation/Onboarding
Pipeline
Review Instance
Security
SOCKS
Something Else
Test Accounts
Testing Support Form
Testing Tools
va.gov - Incident
```

Currently, the following keywords are triggering the link to the following document:
- Keywords: 
`cypress`,`e2e`,`end-to-end`,`end to end`
- Document: https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress

**Comment by holdenhinkle** [comment]
The following column names in the main Platform Support Responses sheet will have to be renamed to make BigQuery happy (column names can't start with numbers and can only contain letters and underscores):

FROM
```text
Was documentation referenced or provided to user?
Documentation URL
Was add'l support required in thread after URL provided?
Was a ticket created?
Ticket URL
Comments
Time to First Response (calculated)
```



TO
```text
WasDocumentationReferencedOrProvidedToUser
DocumentationURL
WasAddlSupportRequiredInThreadAfterURLProvided
WasATicketCreated
TicketURL
Comments
TimeToFirstResponseCalculated
```

**Comment by holdenhinkle** [comment]
BigQuery table created  - https://console.cloud.google.com/bigquery?authuser=1&project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3splatform_support_requests

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/532d1c57-cf09-4d98-b195-7aefe9435abe)

**Comment by holdenhinkle** [comment]
I'm getting an error when refreshing refreshing the view on the automatically added ASDF sheet:
> Query failed
> BigQuery error: Dry run query timed out. Some common causes for this are accessing too many tables, or too many partitions for partitioned tables, or too many files matched for external tables.

I submitted a help request.

When I try querying the data from BQ I also get an error:
`SELECT * FROM vsp-analytics-and-insights.vsp_testing_tools.platform_support_requests`

> Error while reading table: vsp-analytics-and-insights.vsp_testing_tools.platform_support_requests, error message: Found corrupted data while opening file. File: /gdrive/home/Platform Support Responses

**Comment by holdenhinkle** [comment]
Hmm... I just found this error:

> Delegate access
> You do not have permission to delegate access for this BigQuery project

**Comment by holdenhinkle** [comment]
I submitted a support request with Analytics - https://dsva.slack.com/archives/CBU0KDSB1/p1661265903503319

**Comment by holdenhinkle** [comment]
I recreated the table in BigQuery, I deleted column M from the Google sheet which was empty (i just noticed this this afternoon and thought maybe that was the issue), but, alas, I'm stilling getting the same errors as yesterday.

The error that stands out to me is the one I get when trying to run a query in BQ:
> Error while reading table: vsp-analytics-and-insights.vsp_testing_tools.platform_support_responses, error message: Found corrupted data while opening file. File: /gdrive/home/Platform Support Responses

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/1baa8ebb-4f35-4249-8da3-41083520f2b3)

Perhaps some of the data in that sheet can't be read? I see an emoji or two in the text. I just Googled '_saving emoji to bigquery google sheet_' and found this - https://stackoverflow.com/questions/52199674/big-query-do-not-accept-emoji

**Comment by holdenhinkle** [comment]
I downloaded the sheet as a csv, created a new sheet and imported the csv. I then created a new table in BQ called `platform_support_responses_holden` and connected it to the new sheet.

Same errors :-(
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/d66121d4-acac-4347-bf40-13cc21d9b2f6)

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ebf19ac1-01dc-4e5e-a728-276286485dee)

**Comment by holdenhinkle** [comment]
I just tried letting BQ create the table schema automatically and got the same 'corruption' error:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/9a5f80b8-7ca5-4ae9-934c-a5fc12178c34)

**Comment by holdenhinkle** [comment]
I tried recreating the table, this time with all `string` types. Before, all columns where type `string` except for columns with dates and times which were type `datetime`.

Still didn't work:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/a56129bb-fbf1-4e2d-82a5-c77a8b4c0f3e)

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/794ee662-fd64-4e82-96d6-32392fcc361b)

**Comment by holdenhinkle** [comment]
I deleted all by 400 rows, thinking maybe there's too much data (~4k rows). That didn't work.

I deleted all but 1 row. That didn't work.

I deleted all rows. That didn't work.

I deleted unused columns. That didn't work.

**Comment by holdenhinkle** [comment]
I paired with Peter and we (he) figured it out. After selecting 'Drive' in the 'Create Table from' field, I went with the 'Avro' file format which was then auto-selected upon me selecting 'Drive'. The file format should be 'Google Sheet'. I've successfully done this before a few times, and showed Curt how to do it, but... my brain.

**Comment by holdenhinkle** [comment]
responses table:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/4d897606-3153-4a8a-9f4a-d2c75aabfacf)

topics table:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/4e901580-951d-45c8-9d61-17c2ad37d4fb)

**Comment by holdenhinkle** [comment]
I updated Topics:

```
Add
Test Failure

--

Deactivate 
Test Accounts

Add 
Test Accounts / Data

--

Add
CI Error

--

Deactivate
Testing Tools

Add
Tool Access
```

** I asked Kerry to make the updates to the `Topics` sheet for me because it's locked. I coped the existing sheet and updated it so Kerry can easily make the changes if he's okay with them.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/3b162066-40f8-4188-b0f7-08ea4a932054)

**Comment by holdenhinkle** [comment]
Kerry made the updates.
