### ISSUE TITLE
[FE] Payment Info V2: Copay card implementation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45866]
## Background
For the next iteration on payment info we are creating two distinct sections on My VA (Outstanding debts and Benefit payments) where previously only one section existed on this topic (Benefit payments and debts). **This ticket specifically is to create the copay card within the "Outstanding debts" section on My VA.**

[Outstanding debts frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#outstanding-debts-frontend-documentation)

## Tasks
- [x] Create the copay card per specs outlined in the [copays card UX specs section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#copays-card).

## Acceptance Criteria
- [x] The designs for copay cards for [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/DAB1B489-950A-4378-B784-0E4980F44A1E) and [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/EEFBF469-F7B6-4087-9EB4-FE6DE1EE2A12) adhere to the general specs outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#copays-card)
- [x] A user sees the copays card when they have copays in the debt portal that do not equal 0
- [x] A user does not see the copays card when there are no copays in the debt portal, or their copay total equals 0
- [x] Content for the copay card matches what is outlined in the [content section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#content-1) of FE documentation, including total copay amount, number of outstanding copays, due date, and a link to "Manage your VA bills" which links to `https://www.va.gov/manage-va-debt/your-debt`
- [x] When a user has **no debts and no copays** they see text that reads "You have no outstanding debts or copay bills" and they see a link to "Learn about VA debt" that `links to https://www.va.gov/resources/va-debt-management/`, as implemented in #45865

## Validation
**_Who can validate this ticket? (FE, BE, Design, PM)?_**
 PM, Design

**_How can this work be validated?_** 
1. Select a test user in staging 
2. Confirm designs/specs of copays card match documentation linked in this ticket
3. To confirm data accuracy, compare the user's copay card on My VA to the debt portal on staging (https://www.staging.va.gov/manage-va-debt/your-debt)

**Comment by tmitchellgcio** [comment]
Currently I am in the testing phase here to be sure we are testing for all scenarios. The frontend code is complete as far as I know, but a test could prove otherwise.

**Comment by tmitchellgcio** [comment]
Code complete. 0 effort left

**Comment by ericasauv09** [comment]
validated "user has 1 copay" with user 11: ![Screen Shot 2022-09-30 at 10.21.01.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/802ba775-d753-4486-8982-29aabdd59f17)

validated "user has no copays" with user 0: ![Screen Shot 2022-09-30 at 10.25.22.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/5795a626-acf4-4330-aaaa-856ec5cfd1f6)

user 36 has multiple copays but the amount is not matching what is shown in the debt portal - opened ticket #47722 to look into this. 

closing this ticket since we validated and have another ticket to resolve the one outstanding issue.
