### ISSUE TITLE
[FE] Payment Info V2: Benefit payments Secondary links and error states

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45864]
## Background
This ticket is to implement the front end changes needed based on Angela's [FE implementation document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md). 

This ticket is to: 
1. Update display logic/design for users who have not received payments in the past 30 days
2. Update designs for the direct deposit link and the view your payment history link
3. Implement error states for benefit payments section

## Tasks
- [x] Update Direct Deposit link design
- [x] Update Payment History link Design
- [x] Update error state (payment history API call fails) for [Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/268A4DAB-EB9D-49B5-AA3F-FEDBDB797E4A)
- [x] Update error state (payment history API call fails) for [Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/D56012A2-DBE1-49DD-A5D5-95D01ABB4DFA)

## Acceptance Criteria
- [x] Designs are updated appropriately for users who have no received payments in the last 30 days, direct deposit link and payment history link are updated as well as designs for errors states

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ PM, Design
- _How can this work be validated?_ Validate design updates in staging

**Comment by tmitchellgcio** [comment]
Effort left is about a 2.

**Comment by ericasauv09** [comment]
validated with user 39 (has never had payments): ![Screen Shot 2022-09-30 at 10.43.19.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/4242ae75-40ad-4702-a4ed-07d56b35ecb6)

user 0 (has not had any payments in the last 60 days): ![Screen Shot 2022-09-27 at 10.21.35.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/c3dfd119-fad3-4dc0-bb9e-36b1431dcfd4)

user 11 (error state): ![Screen Shot 2022-09-30 at 11.10.59.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/88ccc08f-2872-47ca-91ea-e14f4aeb3b05)
