### ISSUE TITLE
[FE] Payment Info V2: Outstanding debts section + debt card implementation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45865]
## Background
For the next iteration on payment info we are creating two distinct sections on My VA (Outstanding debts and Benefit payments) where previously only one section existed on this topic (Benefit payments and debts). This ticket specifically is to:

1. Create the "Outstanding debts" section on My VA 
2. Create the debt card/details within

[Outstanding debts frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#outstanding-debts-frontend-documentation)

## Tasks
- [x] Create a new "Outstanding debts" section on My VA (separate from the newly revised "Benefit payments" section) as a section that always shows for LOA3 users 
- [x] Create the debt card per specs outlined in the [debts card UX specs section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#ux-specs).
- [x] Implement logic so that when a user has **no debts and no copays** they see text indicating as such (per specs [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#if-a-user-has-no-outstanding-debts-or-copay-bills)) and see the secondary link to "learn about VA debt" (per specs [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#learn-about-va-debt-link))

## Acceptance Criteria
- [x] The "Outstanding debts" section displays for all LOA3 users. 
- [x] The design for debt cards for [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/639F4902-A32D-4454-87E5-4BD2E50E578E) and [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/B3352077-2620-4C5B-9208-2B57CD6CFAC5) adhere to the general specs outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#debts-card)
- [x] A user sees the debts card when they have open/unpaid debts in the debt portal that do not equal 0
- [x] A user does not see the debts card when there are no debts in the debt portal, or their debt total equals 0
- [x] Content for the debt card matches what is outlined in the [content section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#content) of FE documentation, including total debt amount, number of outstanding debts, last updated date, and a link to "Manage your VA debt" which links to `https://www.va.gov/manage-va-debt/your-debt`
- [x] When a user has **no debts and no copays** they see text that reads "You have no outstanding debts or copay bills" and they see a link to "Learn about VA debt" that links to `https://www.va.gov/resources/va-debt-management/`

## Validation
**_Who can validate this ticket? (FE, BE, Design, PM)?_**
 PM, Design

**_How can this work be validated?_** 
1. Select a test user in staging 
3. Confirm designs/specs of "Outstanding debts" section and debts card match documentation linked in this ticket
4. To confirm data accuracy, compare the user's "Outstanding debts" section on My VA to the debt portal on staging (https://www.staging.va.gov/manage-va-debt/your-debt)

**Comment by tmitchellgcio** [comment]
Currently I am in the testing phase here to be sure we are testing for all scenarios. The frontend code is complete as far as I know, but a test could prove otherwise.

**Comment by tmitchellgcio** [comment]
Code complete. 0 effort left

**Comment by ericasauv09** [comment]
no debt: validated with user 36
has 1 debt: validated with user 11
has multiple debts: validated with user 1 
All matched data in the debt portal
