### ISSUE TITLE
[Design] Merge Conflicts within Abstract

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#45862]
# Description
During initial Abstract usage, it was determined the merge conflicts can occur. We need to better understand how Abstract handles these conflicts and how the check-in UX plan to deal with them.

# Tasks
- [ ] Create a very small mock wireframe merge conflict scenario in Abstract
- [ ] Zach and Ya-ching meet with test out what the conflict looks like in Abstract, then decide how to deal with it.
- [ ] Test for both (1) parallel and (2) nested branches in hierarchical locations.

# Acceptance Criteria
- [ ] If applicable, document the new UX process somewhere on GitHub

**Comment by ytsaoca** [comment]
Discussion takeaways: 

- Abstract can only pick an artboard if import new version from master.

- If it's a small change, create a new branch and merge back to the master after editing. If it's a large change (like a new function) after finishing the design, remember to sync with other designers and edit what was updated in the master to that branch and then merge to the master.

'cc @zach-park
