### ISSUE TITLE
[FE] Payment Info V2: Benefit payments Card Updates Implementation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45861]
## Background
Now that we have completed our Payments and Debts V2 design updates we are ready for the front end implementation. This ticket is to complete the front end updates for the payment card. This is the card that shows the users recent benefit payment information. Angela's FE Implementation Document is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md). We also want the payments section (now separated from debts) to be showing always for all LOA3 users.

## Tasks
- [x] Change conditional logic so the payments section is always showing for every LOA3 user
- [x] Update payment card for [Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/222D00A6-3BFD-4D99-9FCB-A9CE2766E78A) and [Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/1CA9530C-0A0F-4CF6-9597-D76F83143B45) for direct deposit users
- [x] Update payment card for [Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/1FEFF140-7526-42A2-9D64-959E152ED415) and [Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/38CB47EF-6A94-44CD-B0F8-F6FE999C933D) for paper check users
- [x] Ensure card is shown for users who have received a payment in the last 30 days, and does NOT show for users who have NOT received a payment in the last 60 days
- [x] Update Feature flag

## Acceptance Criteria
- [x] The payment section is showing for all LOA3 users. The designs for payment cards for mobile and desktop have been updated appropriately. The payment card only shows for users who have received a payment int the last 60 days
- [x] Updates for [Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/977354F4-360B-4287-B9CD-CE28DC8444A0) for users who have not received a payment in the past 60 days
- [x] Updates for [Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/95A46294-248D-407C-8557-8C6A35C02315) for users who have not received a payment in the past 60 days

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ PM, Design
- _How can this work be validated?_ Review design updates in staging, ensure payment section shows for all LOA3 users. Check the payment history link to ensure the payment amounts are accurate.

**Comment by tmitchellgcio** [comment]
Currently I am in the testing phase here to be sure we are testing for all scenarios. The frontend code is complete as far as I know, but a test could prove otherwise.

**Comment by tmitchellgcio** [comment]
Effort left is about a 2

**Comment by ericasauv09** [comment]
validated with user 80 (has payments): ![Screen Shot 2022-09-30 at 10.34.21.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/1c86c02e-c71a-444a-b97c-42c52e53b71f)

and user 39 (has never had payments: ![Screen Shot 2022-09-30 at 10.43.19.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/59bd431d-8317-4b9c-aa57-27a2530069a8)

and user 0 (has had payments in the past but not in the last 60 days: ![Screen Shot 2022-09-30 at 10.44.57.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/656f0ed3-308f-4fef-a27a-c348933e3d88)
