### ISSUE TITLE
[FE] Payment Info V2: Create feature flag for payment info v2

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45867]
## Background
For the next iteration on payment info we are creating two distinct sections on My VA (Outstanding debts and Benefit payments) where previously only one section existed on this topic (Benefit payments and debts). This ticket specifically is to create the feature flag needed for the new "Outstanding debts" and "Benefit payments" sections on My VA.

## Tasks
- [ ] Create the feature flag 
- [ ] ...

## Acceptance Criteria
- [ ] New feature flag exists in the /flipper/feature
- [ ] Feature flag effectively toggles the feature on and off

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Dev
- **_How can this work be validated?_** Visit flipper feature and confirm feature flag is there, confirm it works

**Comment by ajakabcin** [comment]
Ticket not needed - feature flag will be updated in #45861
