### ISSUE TITLE
Design | Profile | Notification Preferences 1095B | Create Research Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45860]
## Issue Description

As part of the the Notification Preferences for 1095B , we'll need to recruit Veterans to review screen mock-ups and validate that our user interface is intuitive and useful. 

See [platform research plan reference documents](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/README.md) for guidance

---
## Tasks
- [ ] Write a research plan to recruit Veterans to review Notification Preferences for 1095B mock-ups  [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [ ] Send the research plan to PO and PM for review 
- [ ] Implement updates as needed
