### ISSUE TITLE
Supplemental Claims MVP Research 

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#45873]
This epic will hold all the tickets related to Supplemental Claims MVP research. 

Tasks:

- [x] Draft research plan
- [x] Draft conversation guide
- [x] Ticket research review
- [x] Schedule midpoint review
- [x] Determine schedule and recruiting plan
- [x] Conduct pilot session
- [x] Conduct research sessions
- [x] Synthesize findings
- [x] Generate research report
- [x] Share research readout

**Comment by thehastingsp** [comment]
fyi [research sessions](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/176) are set to kick off with a pilot 9/19 and first session 9/22.

**Comment by thehastingsp** [comment]
closing this epic. [research folder is here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims/Research/MVP%20Usability%20Research).
