### ISSUE TITLE
FE | Profile | Add Headings Back Into Alerts

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45872]
## Background

Per ticket [#43586](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/43586) we need to add headings back into the alerts we show when something goes wrong and we can't show anything on the page.

We can use the same message in the alert on all pages and simplify maintenance in the future.

---

[heading]
This page isn't available right now

[body]
We're sorry. Something went wrong on our end. Refresh this page, or try again later.

---
Here are links to the individual mocks.  **If there's an orange button at the top that says "See latest version" please click that to see the newest version.  At the time of this writing, the text wouldn't update, so please refer to the copy above if the the mock-up has different content.**

### Personal information
- [mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/R1jyjvz)
- [desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/1KdVdJw)

### Connected apps
- [mobile](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/m1e0rnw)
- [desktop](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/Gme8GqL)

### Notification settings
- [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/pamgp9Z)
- [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/YLgz8O/a/dlxe9D9/r/pv0P7A)

### Contact information
- [mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/zx2q52a)
- [desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/OmlnY7p)

### Direct deposit
- [mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/09y85M0)
- [desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/m19eRvV)

### Military history
(this may just be a copy change)
- [mobile](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/dl2vRJE)
- [desktop](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/8yoRyd3)

## **Tasks**

- [ ] Add headings into the alerts shown in the mock-ups listed above using the full-width pattern and content provided
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## **Acceptance Criteria**

- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

**Comment by andaleliz** [comment]
In the sketch files, I didn't see this type of alert present for account security or military history, so there wasn't anything to update. 

Is there a possible use case for those sections where we wouldn't be able to show anything on the page, @adamwhitlock1? If so, we should use the same alert on the other pages, and I can add them to the Sketch files.

**Comment by SKasimow** [comment]
@adamwhitlock1 - can you review/point when you have a chance?

**Comment by jcatergovy** [comment]
@cgednalske @SKasimow ready for validation in staging

**Comment by jcatergovy** [comment]
@SKasimow @cgednalske ready for validation in staging

**Comment by cgednalske** [comment]
@jcatergovy @SKasimow --- @andaleliz probably has a much better idea of the design for this one. Liz, do you want to check it out? 🙂

**Comment by jcatergovy** [comment]
Personal Information:
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/fcc7f68c-488b-435a-bf17-3f50a3585e8e)

Notification Settings::
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/6fd42fae-c61c-47a0-9ccd-8a86c89b4b65)

Military Information:
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/cb5ab8af-599e-4d18-b2f6-ebe324c7000b)

Direct Deposit:
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/899f656f-f530-41a8-872f-9c4c98979139)

I'll have the other three up shortly

**Comment by andaleliz** [comment]
The alerts under the heading look correct, but I'm not sure about the other alert above the `h1` - why is that displaying? We should never have both alerts at the same time.

**Comment by SKasimow** [comment]
@adamwhitlock1 - re-assigning to you; can you take a look?

**Comment by adamwhitlock1** [comment]
I can take a look. After our discussion today in standup Liz mentioned that this is a legacy alert that should be removed now that we are not gating  the direct deposit page. We should close this ticket and create a new issue around removing the first alert profile wide.

**Comment by adamwhitlock1** [comment]
I can take a look. After our discussion today in standup Liz mentioned that this is a legacy alert that should be removed now that we are not gating  the direct deposit page. We should close this ticket and create a new issue around removing the first alert profile wide.

**Comment by adamwhitlock1** [comment]
I'm going to close this ticket, see my previous comment about removing the main alert, and there was a ticket created to evaluate its usage and formulate a plan for removal here:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/51902
