### ISSUE TITLE
Grafana - root_url switch to https

### ISSUE THREAD

**Issue by calquisola** [department-of-veterans-affairs/va.gov-team#45885]
## Who is the devops resource on your team?
@calquisola  and @iriteshp are the devops resource on our team. 

## Description
We have integrated Grafana and Login.gov through Keycloak with this [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/669), however we are having redirect issues with Login.gov

We need to the update the root_url setting in Grafana to https:
`grafana.ini:`
`    server:`
`       root_url: "http://grafana.vfs.va.gov"`

The root_url is the redirect URL use by grafana when you login with a 3rd party Idp (e.g. [login.gov](http://login.gov/), github).
[Login.gov](http://login.gov/) doesn't like "http" which causes the redirect issues.

> **_NOTE:_**  Updating the root_url to https will break the current Github OAuth. To avoid this, we need to update the Grafana's GIthub OAuth application redirect URL to https also. 

## Technical notes
This is our [ticket](https://app.zenhub.com/workspaces/access-management---platform-spike-team-61a8e04a925132001416247c/issues/department-of-veterans-affairs/va.gov-team/37859) for Grafana and Keycloak integration. 

We got a Grafana [proof of concept](https://grafana-amt-test.vfs.va.gov/login) for this one .

We can find our Grafana proof of concept configuration [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-amt/grafana/values-dev.yaml). 

---
## Tasks
- [x] update the root_url to "https://grafana.vfs.va.gov" in grafana's application [manifest](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/grafana/values.yaml)
- [x] update the Grafana's GIthub Oauth application callback url to "https://grafana.vfs.va.gov/login/github".  You can create an [issue](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=general+issue%2Cuser-created&template=general-request.yml&title=General+Request%3A+%5Btitle%5D)  with the VA Github team for this one or message them in slack (#github_information)

(we're just switching grafana's Oauth settings to https)

## Acceptance Criteria 
- [ ] Github OAuth works the same way after switching to https
- [ ] Login.gov redirects without issue after authenticating to Grafana

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
In chatting w/ AMT & Platform Infra during office hours on 8/19, one thing we'll need to change is the callback URL for the GitHub OAuth app.

**Comment by jhouse-solvd** [comment]
@ph-One - Take a look and approve if you're okay with this.

**Comment by calquisola** [comment]
@jhouse-solvd , we have deployed this change. 

We don't see any issues so far.
