### ISSUE TITLE
Terms and Conditions - eAuth Implementation

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#45895]
# Description
VA.gov and its affiliated partners are working to implement a single, unified set of Terms and Conditions.  As part of this work, we will need to work to ensure that these are properly implemented on VA.gov via the existing eAuth solution.  Full details of the Terms and Conditions rollout can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/terms%20and%20conditions

# Acceptance Criteria (on sign-in)
- [ ] On sign-in, check if user has accepted current Terms and Conditions
- [ ] If user has not, present Terms and Conditions for acceptance
- [ ] If user has accepted, do not present current Terms and Conditions
- [ ] If user accepts, forward them to where they were going
- [ ] If user does not accept, prevent log-in

# Acceptance Criteria (on new Terms and Conditions)
- [ ] When Terms and Conditions are updated, all users are presented with the new version via the above workflow

# Acceptance Criteria (record keeping and auditing)
- [ ] _Currently waiting for details from John on how these are audited_

# Current Status
Presently, we are waiting for the terms and conditions text to be finalized, as well as for the OCC to decouple their existing solution from Cerner.  Once this is done, IAM can implement it with SSOe and we can verify it works.  Longer term, we will want to roll this into our Sign-in Service (Associated Epic: 45896).
