### ISSUE TITLE
Establish Discovery Criteria & Roadmap for Medallia 

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4590]
## Problem Statement
How might we map out discovery for Medallia so that we can determine goals, objectives, and corresponding work for Platform and Applications?

## Goal
Determine the body of work for Medallia strategy and implementation discovery.

## Objectives or Key Results this is meant to further
- Work with VSA Leadership and Jeff Barnes to start discovery on Medallia strategy and implementation.

## Acceptance Criteria
- [ ] Goals outlined
- [ ] Responsibilities outlines
- [ ] Phased rollout or roadmap

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[VSA Strategy Doc:](https://docs.google.com/document/d/1KCvHwlIaoEzpg9xjUsGu1raEORXh1jJKyWULi7jZMUw/edit)

**VSP Next Steps:**
1. Set up meeting with Henna
2. Determine how Medallia functions
3. Determine any Strategy blockers or pivots from implementation 
4. Use Strategy to define implementation requirements

**Comment by joanneesteban** [comment]
Next Platform Steps outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4649). Closing this issue.
