### ISSUE TITLE
Modify the signup method for SiS

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#45907]
## Issue Description
Modifies the `signup` authentication method to ensure Sign in Service signup links references the correct `type={properType}`.  This ticket will effectively track the body of work transforming each signup from `logingov_signup` and `idme_signup` to `logingov` and `idme` respectively.

---
## Tasks
- [x] Transform the `signup` function
    - [x] SiS Version: `{csp}_signup` => `{csp}` (only Login.gov and ID.me)
    - [x] IAM version: `{csp}_signup` remains the same

## Acceptance Criteria
- [x] SiS Version: The signup link should look like `v0/sign_in/authorize?type={csp}` (`idme` and `logingov`)
- [x] IAM Version: The signup link should look like `v1/sessions/{csp}_signup/new` (`idme` and `logingov`)
