### ISSUE TITLE
[PM] Payment Info V2: Contact Center Guide Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45929]
## Background
Before we go live with Payment Info V2 we need to update the call center guide with the appropriate information.

## Tasks
- [x] Update call center guide
- [x] Have APM/PM review (whoever didn't do the edits)
- [x] Send to Samara for review
- [x] Submit to [call center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) with product guide
- [x] Once approved update the product guides versioning documentation found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md).

## Acceptance Criteria
- [x] Call center guide is updated with Payment Info V2 information and final version is stored in our team documentation

**Comment by ajakabcin** [comment]
Submitted call center ticket - #49621

**Comment by ajakabcin** [comment]
Guide was reviewed and approved by the contact center team - waiting for final approval from VEO but otherwise good to go. I'll update our [records page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md) when that team sends me back the final copy with all links updated.

**Comment by ajakabcin** [comment]
Final version received yesterday afternoon - uploaded to our [records](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md). Closing!
