### ISSUE TITLE
[FE] Onsite Notifications: Support UAT

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45924]
## Background
We will need our FE dev to manage the feature toggle on production for our UAT of the Onsite Notifications feature. 

_Since we will be enabling the feature for specific individuals participating in the study, if you are unable to attend sessions please plan ahead to provide a backup who can both enable/disable the feature flag and provide support to the researcher during these sessions._

## Tasks
- [ ] Work with the designer leading the sessions to ensure feature flag works properly prior to the testing sessions: enable to feature for individual team members on production and have them confirm it
- [ ] Provide technical troubleshooting support during the research sessions (should any issues come up)

## Acceptance Criteria
- [ ] Sessions are conducted/complete

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)_** any team member
- **_How can this work be validated?_** In advance of usability/UAT sessions (including the pilot session) test the feature flag _on production_ to confirm that you can successfully enable and disable the feature. Test with multiple team members.

**Comment by ajakabcin** [comment]
No longer needed
