### ISSUE TITLE
[Platform Collaboration] Create Slack channel for Platform DevOps communication 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#45927]
## Description
As a byproduct of the recent re-organization and the restructuring of the operations/infra team, it's challenging to communicate effectively with other DevOps personnel on the platform.

Having a dedicated Slack channel to coordinate DevOps personnel across Platform (w/ Identity, CMS) teams would be helpful. We think the channel should be private for now, and/or be restricted to specific teams/members.

This might also dovetail nicely with the forthcoming DevOps Community of Practice.

## Background/context 
- [Relevant post in #platform-team gauging interest](https://dsva.slack.com/archives/CJRQ85PQB/p1646933320571259)
- Share DevOps expertise 
- Remove silos for DevOps personnel across platform teams 
- Coordinate Devops engineers in a single place to share solutions and strategies surrounding platform DevOps tools 
- PR approvals (e.g. devops repo)
- General questions about DevOps tools
- Collaborate on infra best practices
- We don't want the channel to be confused with another venue for requesting support from the Platform Infrastructure team
- The following Slack channels exist for other dedicated purposes (see below):  
  - #platform-infrastructure - for platform-wide infrastructure-specific discussions 
  - #platform-architecture - for platform-wide architecture discussions that aren't specifically about infrastructure 
  - #devops-deploys - for observability of deployments; mostly automated notifications 
  - #devops-alerts - for observability of services; mostly automated notifications 

---
## Tasks
- [x] Decide on invites to the channel 
- [x] Set a clear purpose for the channel 
  - [x] Description 
  - [x] Guidelines
  - [x] Links to other channels (see above) 
- [x] Communicate new channel purpose to invitees

## Acceptance Criteria 
- [x] A new Slack channel has been created: #platform-devops
- [x] Platform DevOps personnel have been invited to the channel
- [x] The new channel and purpose have been communicated 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ianhundere** [comment]
[here's the list of people](https://github.com/department-of-veterans-affairs/devops/blob/aa529b152ec125030b1f3680da6606561f51b77b/terraform/environments/global/iam_users.tf)

anyone with `operations` or `devops`

**Comment by jhouse-solvd** [comment]
For platform, cms, identity teams, I think we would restrict it to the following groups ([from the list that](https://github.com/department-of-veterans-affairs/devops/blob/aa529b152ec125030b1f3680da6606561f51b77b/terraform/environments/global/iam_users.tf) @ianhundere shared)

- vsp-devops
- vsp-identity 
- vfs-cms-infrastructure

**Comment by jhouse-solvd** [comment]
We should have something like: 

> NOTE: For active support, please visit #vfs-platform-support and/or follow the Incident Response Playbook

We should also make this channel private to avoid VFS teams from joining.

**Comment by jhouse-solvd** [comment]
[This document](https://vfs.atlassian.net/wiki/spaces/OT/pages/2345664686/Purpose+of+platform-devops) captures the purpose of the channel.

**Comment by jhouse-solvd** [comment]
Initial invites have been sent. Please reach out if there are additional people to be added. Thank you!
