### ISSUE TITLE
[PM] Payment Info V2: Request QA

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45925]
## Background
Submit formal QA request for the Payments Info V2 project.

## Tasks
- [x] Update Test Cases
- [x] Meet with Tze (if needed)
- [x] Submit [QA Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=Shared+Support+Team%2C+QA%2C+PTEMS%2C+qa-test-plan&template=ptems-qa-test-plan.md&title=%5BProduct%2FFeature%5D+PTEMS-QA+Test+Plan) for QA to occur in sprint 84 (which starts 10/5)

## Acceptance Criteria
- [x] QA Request is submitted

**Comment by ericasauv09** [comment]
[Link to current test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md)

**Comment by ericasauv09** [comment]
Tze is good with not meeting and just submitting the Test Plan ticket when we are ready

**Comment by ericasauv09** [comment]
Submitted [QA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47208)
