### ISSUE TITLE
[Research] Onsite Notifications: Conduct UAT 

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45923]
## Background
We need to conduct UAT on the Onsite Notifications feature. 

## Tasks
- [ ] Coordinate with FE dev to ensure feature flag works properly prior to testing sessions
- [ ] Conduct UAT/usability sessions

## Acceptance Criteria
- [ ] Sessions are conducted/complete

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ NA
- _How can this work be validated?_ NA

**Comment by ajakabcin** [comment]
test plan documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/UAT/internal-testing-plan.md)

**Comment by aagosto90** [comment]
Here's a (very brief) [doc of UAT findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/UAT/Onsite-notifications-internal-UAT-findings.md) @ajakabcin @ericasauv09
