### ISSUE TITLE
[FE] Payment Info V2: Implement recent payment functionality for Payment Info Section (30 days)

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45931]
## Background
Now that we have completed our Payments and Debts V2 design updates we are ready for the front end implementation. This ticket is to complete the front end updates for the payments section. We want to update the design for users who have  not received a payment in the past 30 days Angela's FE Implementation Document is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md). 

## Tasks
- [ ] Updates for [Desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/977354F4-360B-4287-B9CD-CE28DC8444A0) for users who have not received a payment in the past 30 days
- [ ] Updates for [Mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/95A46294-248D-407C-8557-8C6A35C02315) for users who have not received a payment in the past 30 days

## Acceptance Criteria
- [ ] Users who have received multiple payments will only see the most recent one on My VA under the benefit payments section. The designs for users who have not received a recent payment are updated.

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ PM, Design
- _How can this work be validated?_ Validate in staging

**Comment by ajakabcin** [comment]
Duplicate ticket - functionality will be implemented in #45861
