### ISSUE TITLE
[FE] Payment Info V2: Error state for outstanding debts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#45943]
## Background
For the next iteration on payment info we are creating two distinct sections on My VA (Outstanding debts and Benefit payments) where previously only one section existed on this topic (Benefit payments and debts). **This ticket specifically is to implement error states in the "Outstanding debts" section on My VA.** 

- [Outstanding debts frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#outstanding-debts-frontend-documentation)

## Tasks
- [x] Using the [error alert component](https://design.va.gov/storybook/?path=/docs/components-va-alert--error), implement logic to handle scenarios when the debt api or copay api call fails in the outstanding debts section, [per specs here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#error-states)
- [x] The text for error message will read "We're sorry. We can't access your payment history right now. We're working to fix this problem. Please check back later."
- [x] When the payment API errors, by default we will show the payment history and direct deposit secondary links so that the user doesn't hit a dead end.

## Acceptance Criteria
- [x] When the debt or copay api call fails, the user sees an error message under the Outstanding debts section header, that reads: "We're sorry. We can't access some of your information right now. We're working to fix this problem. Please check back later." They also see a secondary link to "Learn about VA debt" which links to `https://www.va.gov/resources/va-debt-management/`

## Validation
**_Who can validate this ticket? (FE, BE, Design, PM)?_**
 PM, Design with assistance from a dev

**_How can this work be validated?_** 
_need to document process for triggering an error state_

**Comment by tmitchellgcio** [comment]
Currently I am in the testing phase here to be sure we are testing for all scenarios. The frontend code is complete as far as I know, but a test could prove otherwise.

**Comment by tmitchellgcio** [comment]
Code complete. 0 effort left

**Comment by ericasauv09** [comment]
validated with user 21
