### ISSUE TITLE
Profile Team | Sprint 82 | 9/7 - 9/20 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45959]
## PTO/OOO/Unavailable

- **Adam**: 9/13
- **Christina**: 
- **Sharon**: off-line for GovCIO Training: 9/12 AM and 9/14 PM
- **Tom**: 
- **Samara**: off-site 12pm Mon 9/12, Tues 9/13 and Wed 9/14
- **Liz**:  1/2 day 9/20, 9/21 and 9/22.

**Note:** 9/8 Staging Review for BAI
~- Possible internal UAT 9/9~

## Sprint Priorities
- Complete BAI Staging Review and UAT
- Finish up product documentation
- Begin Accessibility Audit work
---

#### PM - Sharon
- [x] #42706 Staging  Review
- [x] #46364 Setup GA widget (once FE work completes) (1 pt)

#### Design - Christina
- [x] #46801 Staging Review
- [x] #46802 Staging Review

#### FE - Adam
- [x] #46968 Screen updates  (1 pt)
- [x] #46320 GA Custom Events (2 pts)
- [x]  #46799 Staging Review
- [x] #46800 Staging Review

#### FE - Adam
- [x] #45722 Document process for outages/maintenance windows (2 pts)

#### Design - Christina
- [x]  #46315 Documentation for Account Security 

#### PM - Sharon
- [x] #45099 Audit/Update Notification Preferences Feature (3 pts)

#### PM + Design
- [x] #46417  Accessibility Audit Plan (for review)

#### Design - Liz
- [x] #46876 Mock for DD/FAQ
- [x] #46788 Content

#### FE - Adam
- [x] #44534 Fix phone number read-out (2 pts)

#### BE - Tom
- [x] #46343 (5 pts)

#### FE - Adam
- [x] #46388 Military address bug (2 pts)
- [x] #46451 Prescription shipment (1 pt)

#### BE - Tom
- [x] #46474 Add Profile Claims to User Response (2 pts)
- [ ] #46724 Handle missing service history end date (3 pts)
- [x] #46807 Military bug
- [x] #46582 Github - Move file (1 pt)

#### Design - Christina
- [ ] #46564 Update FAQ content for DD214 (1 pt)

**Comment by Samara-Strauss** [comment]
This is way too much work for Adam, so let's talk about what we can move to next sprint.

**Comment by Samara-Strauss** [comment]
I did not have us launching bad address indicator next sprint, though we can if we are ready. If we are, please add a launch go/no-go.

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - I've removed the documentation tickets from this sprint and will be meeting with Adam on Tues 9/6 to point his tickets and see if the workload is balanced.

**Comment by Samara-Strauss** [comment]
Sounds good. We can consider launch a stretch goal. I had it slated for sure in the following sprint, but there's no need to wait if we are ready.

**Comment by Samara-Strauss** [comment]
For bad address indicator, there should be a ticket for Christina to run internal UAT assuming there are no issues coming out of the staging review.

Otherwise, this looks good.
