### ISSUE TITLE
PM | Profile |**Discovery**Notification Settings | UI Updates | Analytics

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45958]
## Background

Before we update the UI on the Notification Settings page shown to users before they set any preferences, we'd like to understand what we track today and establish a baseline to make sure we don't negatively impact metrics.

## Tasks
- [x] Determine what tracking is in place today for Notification Settings
- [ ] Establish a performance baseline for the past 12 months

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Tracking in place for Notification Settings today can be found [here](https://analytics.google.com/analytics/web/#/dashboard/LcYXUwF2Q8SQ59WQX6OTsw/a50123418w177519031p184624291/_u.date00=20220801&_u.date01=20220821/) and includes:

- Total visits
- Radio button selections
- Succesful saves
