### ISSUE TITLE
FE | Profile | Notification Settings | UI Updates

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#45957]
## Background

Before users set notification preferences they are presented with an alert and additional messaging under each notification option.

- Specifically, they will see an alert that begins" Select your notification options"
- Within each notification there is a message to "Select an option."

These are no longer necessary and removing would clean up the UI [see ticket #44229](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/44229)

## Tasks
- [x] Update UI based on sketch file [Desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/JnL7n1b) and [Mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8z08VJ)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

**Comment by adamwhitlock1** [comment]
@SKasimow This is up on staging and ready to validate. You no longer see the alert or the input messaging, so the notifications section would look something similar to:

![Screen Shot 2022-09-20 at 3.48.19 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/c02cc19b-4ddf-479f-b189-c00ca2a5374c)

**Comment by SKasimow** [comment]
@adamwhitlock1 - testing with user 36; after I added a mobile number and went back to the Notification settings, the Applications, claims etc notification was already checked whereas appt reminders was not. I removed and added a mobile number on this account previously so don't know if there was some "muscle memory" turning up here but wanted to double-check with you:

![Screen Shot 2022-09-20 at 6 34 03 PM](https://user-images.githubusercontent.com/74627978/191376894-4e8ffc42-2784-4837-b958-1b0c96b5feb9.png)

**Comment by adamwhitlock1** [comment]
My guess is that the notification was previously set, and since the mobile number was probably removed previously, then you just didnt see that particular notification with its corresponding value set.

**Comment by SKasimow** [comment]
I tested again using a different account and the notification was not pre-set so think we can close this ticket.
