### ISSUE TITLE
Docker/hybrid setups should use docker volume for db data

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#45955]
## Description
We have multiple developers on the health apartment teams using Windows for whom the docker and hybrid vets-api setups don't work as provided. docker-compose.yml and docker-compose.deps.yml both have the Postgres image mount a local directory for db data:
```
   volumes:
      - ./data:/var/lib/postgresql/data:cached
```
This unfortunately does not work on Windows (using Docker via WSL). It results in a permissions error:
```
2022-07-27 16:44:26.443 UTC [49] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
```
There's no easy workaround - chmod'ing the directory doesn't do anything, it has to do with the users under which docker vs. postgres are running in WSL/Docker. 

What does work is using a Docker volume instead of a mounted local dir:
```
   volumes:
      - db-data:/var/lib/postgresql/data:cached
```

I think this may have been the original intent, because there is already a `db-data` volume defined at the bottom of docker-compose.yml, that is otherwise not referenced!

Suggestion is to update both docker compose files to use that volume. This will impact existing users, who would need to repeat their database setup steps and if they had any meaningful data in postgres, it would be wiped out. 

_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] Update docker-compose.yml and docker-compose-deps.yml to use Docker volume
- [ ] Communicate the need for existing users to repeat database setup steps once they've picked up this change. 

## Acceptance Criteria
- [ ] Docker and hybrid setups work without workarounds for developers on all OS platforms. 

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_
