### ISSUE TITLE
[PM] Payment Info V2: QA Go/No Go

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45966]
## Background
We need to confirm that we are ready to submit the feature forward for formal QA. 

## Tasks
- [x] Ensure feature is done
- [x] Review the feature and functionality
- [x] Complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/QA/payment-info-v2-QA-go-nogo.md) with the team
