### ISSUE TITLE
[Research] Payment Info V2: Create UAT Plan and Conversation Guide

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#45969]
## Background
We need to prepare UAT research documents for the Payments and Debts V2 initiative. This includes creating the research plan and conversation guide.

## Tasks
- [x] Create UAT research plan
- [x] Create UAT conversation guide

Note: there is a folder in GH already created for payment info UAT materials: [UAT folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/uat)

## Validation
- [x] Send links to team to let them review asynchronously
- [x] Have another designer review research plan and conversation guide

**Comment by aagosto90** [comment]
Draft of [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/uat/v2-UAT-research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/uat/v2-UAT-conversation-guide.md) are ready for review! Please take a look when you can but no rush since we're carrying this ticket into next sprint and I will get another designer or two to review as well. @Samara-Strauss @ajakabcin @ericasauv09

**Comment by Samara-Strauss** [comment]
### Research plan

My usual feedback with recruiting: While I understand we want to make sure testing is done with representative populations, and that all research isn't just done with 55+ white dudes, it feels like some of the demographic requests are arbitrary, especially given that I can't think of meaningful reasons why they would affect the main thing we are testing -- whether our code works or not.

So, these are my suggestions for how to loosen up recruiting requirements:

- I'd remove the LGBTQ requirement altogether. Remember, this is extraordinarily sensitive information for people to disclose. We should only be asking for this if it has a meaningful impact on what we are testing (ie. the new preferred name and gender identity fields we just added to the profile). Otherwise, I don't think we should ever make this a requirement, especially for UAT where we are mostly testing our code, not our users.
- The race breakdown feels arbitrary to me. Again, I realize we don't want 12 white dudes showing up to any of our research sessions, but instead of plugging in random numbers to fields, you could put something like "no more than 6" in the "white" field, which will guarantee we'll get a more diverse sample without making arbitrary specifications about racial breakdown. Again, if there are specific and clear reasons to talk to certain numbers of people in certain groups, great, but it doesn't feel like that reasoning exists here.

And one other thing not related to demographics:

- I see that you specified in the screener that we need people with education/comp & pen payments OR with debts, but then under "Benefits", those fields aren't selected at all. Do you think this will cause confusion for Perigean? I want to make sure that they don't miss the payments/debts requirement, as that is the single most important recruiting criteria we have.

### Convo guide

Looks good to me!

**Comment by ericasauv09** [comment]
Everything looks great to me, thanks Angela!

**Comment by Samara-Strauss** [comment]
All of this sounds good to me. Thank you @aagosto90!

> when I submit I'll tell the research ops team that it's our first try using the recruitment tables and the most important criteria for us is still in our screener questions

Totally agreed. I know the recruitment tables are new, so let's just keep an eye on this. If we feel like we don't get the right folks for the research because screener questions were overlooked, this would be good feedback to share with the research team.
