### ISSUE TITLE
Content support for Login.gov messaging for failure to identity proof

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#45978]
## Issue Description
The Login.gov team reached out that they needed our team's support in drafting language to users when they fail to identity proof. They provided us draft content that we need to rework for plain language and so that it matches VA.gov's voice and style.

More background from the email request: We are not explicitly recommending ID.me out of the gate if a user can’t proof with Login.gov. We want to send them back to the VA and remind them that other options exist, since many users already have another credential. If they don’t, we can recommend ID.me. 

Here is the content they provided: 

Thank you for contacting Login.gov

We understand you are experiencing issues with identity verification.
Login.gov cannot verify your identity at this time.
Please visit VA.gov and click sign in, where you can select another option, such as MHV, ID.me, or DS Logon. If you don’t already have one of these options, you can create an ID.me account.

## Tasks
- [x] Revise content (Aliyah)
- [x] Review (Laura)
- [x] Review (Danielle)
- [x] Send back to stakeholder (Laura)

## Acceptance Criteria
- [ ] Content is PL and VA.gov style standards and has been sent back to stakeholder

**Comment by aliyahblackmore** [comment]
Thanks for collaborating on this @laurwill ! 
Hi @DanielleThierryUSDSVA the language is here:

**You can’t sign in with [Login.gov](https://login.gov/) right now**

We’re sorry. We can’t verify your identity at this time. 

Go back to [VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/issues/va.gov) and sign in with your existing **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **ID.me** account now.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @aliyahblackmore @laurwill! 

This is great. I have some recommended tweaks to add (and thank you again, @laurwill for chatting through these via slack):

## We can't sign you in with Login.gov right now
We’re sorry. We can't verify your identity through Login.gov right now. We need to make sure it's you before we can give you access to your personal information.

### What you can do now
Go back to VA.gov. Try to sign in with your existing ID.me, DS Logon, or My HealtheVet account. If you don’t have any of these accounts, you can create a free ID.me account.

Reasons for tweaks for shared awareness:

- Shifted to "We can't sign you in" vs. "You can't sign in" in the header. It's a little softer and shifts the blame for the error to us rather than the Veteran.
- Added reference to "through Login.gov" to the 2nd sentence in the message just to reinforce that it's a problem with Login.gov and not all sign-in methods.
- Added a brief sentence to frame why identify verification is important to help try to ease some frustration around not being able to sign in. Thank you for your collaboration on this line, Laura!
- Added a "What you can do now" h3 like we have in some error messages just to break that out and make it clear that the Veteran can take action.
- Broke up the "Go back" and "sign in" sentences just to shorten a bit and added "Try to" because they may encounter a similar issue.
- Removed "now" from ID.me sentence since we're telling them that they need to go back first.

**Comment by DanielleThierryUSDSVA** [comment]
Revised based on updated info that this is an email, not an error message:


Subject line: Thank you for contacting Login.gov

Email content:

We’re sorry to learn that you couldn't sign in to VA.gov with your Login.gov account. 

We couldn't verify your identity through Login.gov. We need to make sure it's you before we can give you access to your personal information on VA.gov.

**What you can do now:**

Go back to VA.gov. Try to sign in with your existing ID.me, DS Logon, or My HealtheVet account. If you don’t have any of these accounts, you can create a free ID.me account.

[Optional: Add a line about contacting Login.gov by phone if that would be helpful in this situation].

**Comment by laurwill** [comment]
Thanks Danielle! 

@jrahaghi1 , this suggested email content is ready for you (see previous post above). Let us know if you need anything else!

And if you decide a line about contacting Login.gov would be helpful, VA style for this would be something like:

Or call us at [number]. We're here [Monday through Friday, 8:00 a.m. to 9:00 p.m. ET (or whatever the contact hours are)].

**Comment by jrahaghi1** [comment]
Thanks, Danielle and Laura. Let me know how the change on access reads. Its small but I want to make it clear Login.gov does not control access to account information at VA. 


Subject line: Thank you for contacting Login.gov

Email content:

We’re sorry to learn that you couldn't sign in to VA.gov with your Login.gov account.

We couldn't verify your identity through Login.gov. We need to assure the VA it's you before you can sign into VA.gov and gain access to your account.

What you can do now:

Go back to VA.gov. Try to sign in with your existing ID.me, DS Logon, or My HealtheVet account. If you don’t have any of these accounts, you can create a free ID.me account.

[Optional: Add a line about contacting Login.gov by phone if that would be helpful in this situation].

**Comment by laurwill** [comment]
Hi @jrahaghi1 , I see your concern there — how about this? 

- We need to make sure it's you before you can sign in to VA.gov and access your personal information.

Avoids implying that Login.gov controls VA account info, but keeps the more plain language "make sure it's you". Let us know what you think!

**Comment by RLHecht** [comment]
@jrahaghi1 Do you have everything you need now? Curious if we can close this ticket. Thanks!

**Comment by jrahaghi1** [comment]
Yes we can close this, thanks!

[signature_1209364430]
John rahaghi
OFFICE OF THE CTO | DIGITAL EXPERIENCE
***@***.******@***.***>


From: Randi Hecht ***@***.***>
Sent: Tuesday, September 20, 2022 8:12 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Rahaghi, John ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Content support for Login.gov messaging for failure to identity proof (Issue #45978)


@jrahaghi1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjrahaghi1&data=05%7C01%7C%7C6c7d407f06074776670b08da9b1a98a7%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992835797171338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BJjhDbFezP5y6LyuOpu2jlEU33WCTaM0UFvqn6o9P34%3D&reserved=0> Do you have everything you need now? Curious if we can close this ticket. Thanks!

-
