### ISSUE TITLE
MyHealth - Assist with onboarding new MHV team for Pharmacy

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#45984]
## Issue Description
The team that will be building Pharmacy on VA.gov has not worked on VA.gov before and will need some assistance with getting onboarded and acclimated to the environment.

---
## Tasks
- [ ] Introduce the team to the [Onboarding Documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/team-onboarding/product-team-onboarding.md)

## Acceptance Criteria
- [ ] The new team will have access to a quick guide that hits the highlights of how to get onboarded.
- [ ] The new team will have information on where to go if they have questions beyond basic onboarding.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
