### ISSUE TITLE
[cFSR] Vehicle cost displaying incorrectly with comma 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#45983]
## Issue Description
When a comma is entered for a dollar amount the value being displayed shows incorrectly:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/4ba2cd91-7fd9-428d-b22a-a376cec883c1)

Entered Values for above:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/daaa8adb-db00-4c4f-9d3d-87e063f83d63)

---
## Tasks
- [ ] Identify issue with currency display
- [ ] Identify other locations where currency is being incorrectly displayed

## Acceptance Criteria
- [ ] Currency is displaying accurately when user enters a comma

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Fixed with [#41721](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/41721)
