### ISSUE TITLE
MyHealth - Pharmacy - Evaluate constraints that may be created by Cerner taking over Clinician Portal

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#45980]
## Issue Description
At the start of this project, it was understood that the legacy MyHealtheVet team would continue to manage the Clinician Portal used by Clinicians to review patient information (records, prescriptions) and read/reply to messages sent to them by patients.  In mid-August 2022, the core team learned that Cerner would eventually be taking over the Clinician Portal.  We will need to understand the ramifications of this change including interfaces, data constraints, feature constraints, and the implications of straddling two different systems during a years-long rollout.

---
## Tasks
- [ ] Review Cerner Clinician Portal for Pharmacy-related information
- [ ] Document differences between data available through VistA vs. Cerner
- [ ] Document how these differences might impact the features we are able to offer
- [ ] Store this information in the project documents

## Acceptance Criteria
- [ ] We will have a document that explains how the data from Cerner differs from the data in VistA and how that could impact the design and functionality of the Pharmacy tool for MyHealth on VA.gov 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
