### ISSUE TITLE
BE - Auth Profile - Misc - Unplanned Work

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#45992]
## Background
This ticket is a placeholder for any unplanned work that comes up in the sprint.

## Tasks
- [x] Investigate address validation issue in staging ([support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1660845694006739))
- [x] Investigate missing end date on military history for test user ([slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1660829024465739))
- [x] Investigate 403 response code for My VA payment history calls (https://github.com/department-of-veterans-affairs/va.gov-team/issues/45684).

**Comment by tpharrison** [comment]
@SKasimow This is my unplanned work ticket.

**Comment by SKasimow** [comment]
Thanks @tpharrison
