### ISSUE TITLE
[cFSR] bug - Combined FSR failing to submit when no debt is selected

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46008]
## Issue Description
FSR is failing to submit if only copay and do debt is selected

---
## Tasks
- [ ] Fill out submission object using new array when feature flag is true

## Acceptance Criteria
- [ ] FSR submits if only copay is selected (no debt)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
19/26 we think the work is done for this but waiting to validate. Validation is slow because of staging user issues @Dr-Pongo

**Comment by Dr-Pongo** [comment]
[Duplicate issue](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46009)
