### ISSUE TITLE
Update PDF for burials benefits on Welcome Kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46004]
## Issue Description
Stakeholder Justin Hoffmann uploaded a new PDF into Drupal that we need to add to our [Welcome Kit](https://www.va.gov/welcome-kit/) page. The new PDF should replace the one that is currently linked to for "Apply for burial in a VA national cemetery and for memorial products (PDF)."

The PDF can be found in the media section of Drupal under PDFs. [Here is documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/making-updates-to-welcome-kit.md) about how the file should be named before we add it to the page.

## Tasks
- [x] Add PDF to Welcome Kit page (Aliyah)
- [x] Review (Megan)
- [x] Publish page (Megan)
- [ ] Notify stakeholder that page is live (Randi/Laura)

## Acceptance Criteria
- [ ] Page is live with new PDF

**Comment by aliyahblackmore** [comment]
Thanks Randi! 

@megzehn this is ready for you! 
The PDF was already in the media library with the correct file name: "burials-and-memorials-guide.pdf."
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=716

**A flag/note:**
I noticed at the bottom of the new PDF that the "last updated" date is 08/03/2021. Just flagging this in case the year should be 2022.

**Comment by laurwill** [comment]
Hi @aliyahblackmore ,
Thanks for flagging the date issue! Justin sent an updated PDF with a 2022 date. Can you upload this one instead, and then post for Megan to publish?
[burials-and-memorials-guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9418247/burials-and-memorials-guide.pdf)

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! This is ready for you!

The new PDF doc with the 8/3/22 date was added to the media library and updated on the Welcome Kit page. 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=716

**A note:** 
There is an ongoing Drupal bug (chatted a bit with the CMS team) regarding more than one file upload with the same name and the original file. To get around this bug and to avoid there being a number ending on the URL/PDF name, the file name was changed to **"burials-and-memorials-quick-start-guide.pdf**" This is also in alignment with PDF file names for other documents on the welcome kit page.

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! Changes look good. This has been published. 

Over to you @laurwill to alert the stakeholder. 

CC @RLHecht

**Comment by laurwill** [comment]
Thanks both! This change is live and I've notified Justin. Closing out.
