### ISSUE TITLE
Assess and add relevant content to the C&P exam page.

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46001]
## Issue Description
Stakeholder Heather Osborne reached out to discuss adding more FAQs to our current [VA claim exam](https://www.va.gov/disability/va-claim-exam/) page. We need to assess the FAQs she provided and compare them with what is on the current page as well as determine which ones are Veteran facing.

Once we've assessed the new FAQs and determined which ones to add, we need to edit the content for plain language and to meet VA.gov style standards.

Document to assess: [https://app.zenhub.com/files/133843125/21c9b1c8-5219-47bc-b7b9-446189c93086/download](https://app.zenhub.com/files/133843125/21c9b1c8-5219-47bc-b7b9-446189c93086/download)

Update: Heather's team went through the doc and marked up which ones needed to be added and tried to keep the style consistent with what we currently have on the page. We should use this doc when adding in the content to the Drupal page: [https://app.zenhub.com/files/133843125/351490ea-d6f9-4cc7-a95f-8baf18a53c53/download](https://app.zenhub.com/files/133843125/351490ea-d6f9-4cc7-a95f-8baf18a53c53/download)

## Tasks
- [x] Assess document for new Veteran-facing questions to add (Laura)
- [x] Rework identified FAQs in plain language and VA.gov style (Katherine)
- [x] Review new content (Laura)
- [x] Add to Drupal
- [x] Copyedit (Megan)
- [x] Send to stakeholder for review (Laura)
- [x] Final copyedit with pre-publishing checklist (Megan)
- [x] Publish changes (Megan)

## Acceptance Criteria
- [x] New FAQs are live on the page

**Comment by laurwill** [comment]
Hi @katherine-fung , thanks for taking on this claim exams page — I did a pass through the document Heather sent over and made some notes in blue highlight about how we can approach certain sections. See what you think, and of course let me know if you disagree with my take on anything!

[Claim exam page updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9447562/Claim.exam.page.updates.docx)

For next steps, you can do a plain language edit of the new sections and combine questions where possible — we don't want the page to balloon too much in size, but we can add new content that's actually Veteran-facing. 

Heather added screenshots of the live page to this doc, and in several places we'll want to stick with what's currently on the page instead of taking the edit. You can either track changes to Heather's content, or copy in the live content and track smaller updates to that. Whichever you think is easiest! And let me know if you want to hop on zoom to talk about anything.

**Comment by katherine-fung** [comment]
Hi @laurwill! The draft is ready for your review: 

[https://app.zenhub.com/files/133843125/e15ed5bf-e91f-458d-9d65-bd0e75dfb062/download](https://app.zenhub.com/files/133843125/e15ed5bf-e91f-458d-9d65-bd0e75dfb062/download)

When we’re referring to the contract company, should we say “vendor” or “contractor” or other?

**Comment by laurwill** [comment]
Thank you so much @katherine-fung ! 

Since we're a bit crunched for time, I made my edits directly in Drupal to move this along for copyedit. Could you find a time for us to chat tomorrow about the changes, and we can compile a list of notes and questions for the stakeholder together?

@megzehn , the claim exam page is ready for you in http://preview-prod.vfs.va.gov/preview?nodeId=914

**Comment by laurwill** [comment]
Just noting I sent this to Heather for review.

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's the Drupal page with updates based on the stakeholders' feedback: 

https://prod.cms.va.gov/node/914/latest 

The site I mentioned earlier for filing Privacy Requests online (https://vapal.efoia-host.com/) - I signed in, and I couldn't figure out how the Privacy Request works, so email seems like the easiest way to submit a request online.

**Comment by laurwill** [comment]
Thanks @katherine-fung ! Heather confirmed that we can just use the mail and in-person submission options for that form. 

@megzehn, this is ready for a copyedit — just for the revisions. Let me know if you want to chat about anything! http://preview-prod.vfs.va.gov/preview?nodeId=914

**Comment by megzehn** [comment]
Thanks @laurwill, I reviewed this and made some minor tweaks.

**Comment by RLHecht** [comment]
Moving to blocked until we get back from stakeholders

**Comment by laurwill** [comment]
Hi @megzehn ,

We're still waiting on final approval to publish, but all the actual content has been approved — I think you could go ahead with the final copyedit and prepub checklist, and just hold on publishing until I hear back from Heather (likely later today). Thanks!

**Comment by laurwill** [comment]
Hi @megzehn , we got the green light here — you can go ahead and do your final pass/prepub/publish. Thank you!

**Comment by megzehn** [comment]
This is now published!!! Thank you, @laurwill! 

CC @RLHecht

**Comment by laurwill** [comment]
Amazing! I notified Heather. We can close this out.

**Comment by RLHecht** [comment]
Closing!
