### ISSUE TITLE
Promote Sidekiq to EKS higher envs

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46014]
## Description
vets-api Sidekiq has been deployed to the EKS dev environment. We should be sure to promote to higher environments as well since vets-api-server is currently running in dev, staging and production

## Tasks
- [ ]  Add manifest files for Sidekiq k8s in staging and prod
- [ ] Review sandbox - Not running vets-api-server
- [ ] Promote to sandbox

## Acceptance Criteria
- [ ] Sidekiq is running in EKS higher envs

**Comment by LindseySaari** [comment]
This is a dup
