### ISSUE TITLE
[BE] Ignore traffic from Synthetic monitor when reporting to StatsD

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#46021]
## User Story
As a CIE internal stakeholder, I want to view accurate metrics in DataDog that reflect actual veteran usage

In DataDog [vet-api dashboard](https://vagov.ddog-gov.com/dashboard/zps-5fk-azw/check-in-vets-api?from_ts=1660460400000&to_ts=1661065140000&live=false), we noticed a sudden drop in day of check-in completion % last Tuesday (Aug 16th). This was due to the synthetic monitors in DataDog. We need to determine a way to ignore this traffic when reporting to statsd. The Synthetic monitor adds a [particular header](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:7d53e9e6327b4984b20a32e38ef43fcc/?display=top5&environment=production&field=url&field=issue&name=Errors+by+URL&project=3&query=event.type%3Aerror+has%3Aurl+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fcheck_in%2Fv2%2Fsessions%2F12345678-1234-1234-1234-0123456789ae&sort=-url&statsPeriod=24h&widths=-1&widths=-1) `Sec-Datadog` to indicate that it's sent by DataDog. We can look into using it to ignore this traffic.

https://dsva.slack.com/archives/C02UP02HHGX/p1661171617986999

## Tasks
- [ ] [BE] Determine a way to ignore the statsd reporting based on the header
- [ ] [BE] Implement the change

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
