### ISSUE TITLE
[EKS][ARGO] Migrate datadog-agent to new app-of-apps

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#46023]
## Description

We need to migrate out current deployments from jsonnet over to new helm app of apps

---
## Tasks
- [x] Migrate dev
- [x] Migrate staging
- [x] Migrate sandbox
- [x] Migrate utility
- [x] Migrate prod

## Acceptance Criteria 
- [x] Up and running for dev
- [x] Up and running for staging
- [x] Up and running for sandbox
- [x] Up and running for utility
- [x] Up and running for prod

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/commit/9a2a7f235d74e5d7d338ca1d4a75f2656a752ae3
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/commit/46d9ee7553dce23bef001880c73588998e0e7be3
https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/90
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/709
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/710
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/700
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/699
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/697

**Comment by oseasmoran73** [comment]
Due to port conflict, delete the daemon set, then deployment for previous namesapce
