### ISSUE TITLE
Sidekiq Alive 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46025]
## Description
Using the [sidekiq_alive](https://github.com/arturictus/sidekiq_alive) gem, we can add health checking probes for liveness and readiness probes. Additionally, we can do a graceful shutdown of the workers.

## Tasks
- [ ] Add entry for readiness probes
- [ ] Add entry for liveness probes
- [ ] Add graceful shutdown for sidekiq processes

## Acceptance Criteria
- [ ] Probes functionality is working in k8s
- [ ] Graceful termination of workers 

## How to configure this issue
- [x] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_
