### ISSUE TITLE
Collaboration Cycle for Sitewide Facilities VBA Regional Offices 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-team#46029]
### VFS team name

Sitewide Facilities

### Product name

VBA Regional Offices 

### Feature name

Site Modernization (?)

### GitHub label for product

[Regional Offices](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/Regional%20office) 

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

July 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/README.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1772

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by jilladams** [comment]
Mid point review scheduled Tues 8/1 3:30p ET. 
Notified CC team: https://dsva.slack.com/archives/CBU0KDSB1/p1690233223006099

**Comment by jilladams** [comment]
Noting from [Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1702934828958529?thread_ts=1699289451.944039&cid=CBU0KDSB1):  We've gotten approval to use Tugboat as the Staging environment for Staging Review for this product, likely in January. 

Per Shira: 
> Please provide all artifacts at least 5 days in advance of the Staging Review. This is just 1 additional day from the 4 days we typically request (and what Calendly is set for). I'd like to make sure the team has time to familiarize themselves with the tool, troubleshoot if needed, and/or ask questions if there's any challenges.

> Please be very clear within the Staging Review artifacts section what the scope of work is and which pages should be included for review. Not knowing this information can increase the amount of time we spend reviewing, and can lead to us reviewing pages outside of the scope of the changes the VFS team is making. I imagine this could also be a challenge with a new tool.

**Comment by xiongjaneg** [comment]
Staging review has been rescheduled in the Calendly from 1:30pm ET, Thursday, March 21, 2024 to 1:30pm ET, Thursday, March 28, 2024 as we're doing additional testing. Thank you!

**Comment by jilladams** [comment]
For awareness: we've updated the Tugboat URL in the Staging Review artifacts section, due to an issue with Tugboat today. Thanks!

**Comment by CherylEvans** [comment]
@jilladams I can't open either of the Drupal Source of Truth documents. Can you help with this?

**Comment by jilladams** [comment]
@CherylEvans apologies, those are behind Drupal login. 2 PDFs attached here capture the contents of those 2 pages: 
[VBA Centralized Content - Drupal source of truth as of 6-27-24.pdf](https://github.com/user-attachments/files/16018767/VBA.Centralized.Content.-.Drupal.source.of.truth.as.of.6-27-24.pdf)
[VBA Services taxonomy - Drupal source of truth as of 6-27-24.pdf](https://github.com/user-attachments/files/16018768/VBA.Services.taxonomy.-.Drupal.source.of.truth.as.of.6-27-24.pdf)

**Comment by CherylEvans** [comment]
@jilladams Thank you, that's perfect!!

**Comment by CherylEvans** [comment]
@jill<img width="1746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15e76ea68920dbe12a74a677db314268335fa547/VBA%20Regional%20Office%20Time%20Zones.png" alt="VBA Regional Office Time Zones.png" />
adams 
 Hi Jill. I’m reviewing the artifacts for the Staging review next week (VBA Regional Offices) and have a question. I re-watched the Midpoint review and noted that your intention for Office hours was to include 2 separate time listings for each day due to the office closing for an hour for lunch. You would also add time zones (ET, CT, MT) for each geographical office location. Please advise. I’ve attached a screenshot. Thanks, Jill.

**Comment by jilladams** [comment]
We were tracking that as a Consider piece of feedback. We do have a ticket to track the concept ([#17421](ttps://github.com/department-of-veterans-affairs/va.gov-cms/issues/17421)), but haven't scoped it into our MVP right now due to the extended delay on the project, and needing to ship MVP / fast follow with some improvements. 

cc @davidmpickett @mmiddaugh to keep me honest, and @Agile6MSkinner for awareness. ([#17421](ttps://github.com/department-of-veterans-affairs/va.gov-cms/issues/17421) is in the [Service Locations improvements across products epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17350), which isn't scoped into the remainder of VBA PIlot / National work currently, so I did just add it to the National epic )

**Comment by davidmpickett** [comment]
@jilladams My understanding from previous decisions by @mmiddaugh and Jane was that this new hours functionality was out of scope for MVP (including National), but could go in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17782

**Comment by CherylEvans** [comment]
@jilladams Thank you, Jill. I appreciate your quick response! :-)

**Comment by jilladams** [comment]
@mmiddaugh Staging Review FYI: 5 high level findings (4 a11y, 3 of which are already ticketed on our side), nothing launch blocking. 🎉

**Comment by jilladams** [comment]
Security review ticket is filed: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1772

**Comment by Agile6MSkinner** [comment]
508 audit ticket submitted. SNOW: REQ29858122

**Comment by Agile6MSkinner** [comment]
Contact Center Review Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93253

**Comment by jilladams** [comment]
Because Zenhub is likely going away, Sitewide may hit our Github Projects issue cap (1200), and may not be able to port all our issues in right away, logging which issues in this ZH epic are still open, so we can later build parent/child relationships in GHP as needed: 

* #76780

**Comment by Agile6MSkinner** [comment]
Final constituent ticket for analytics was closed, so I am closing the epic.
