### ISSUE TITLE
Certificate of Eligibility | Check and add necessary e2e tests for COE Form 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46034]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the COE code has e2e testing coverage
**_So that_** we can ensure we're releasing a quality product

## Background Context

The COE form is getting closer to release, we need to ensure all important flows have e2e test coverage, including keyboard-only testing

## Tasks

- [ ] Review e2e tests for COE
- [ ] Add e2e tests for missing flows
- [ ] Add keyboard-only e2e tests
- [ ] Check and add necessary e2e tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing
