### ISSUE TITLE
Certificate of Eligibility | Add unit tests for COE form app

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46032]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the COE form code has unit testing coverage
**_So that_** we can ensure we're releasing a quality product

## Background Context

The COE form app is getting closer to release, we need to get code coverage up to around 80% (or more) - it is currently around [26.6% coverage for the form](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)

## Tasks

- [ ] add unit tests for COE status
- [ ] Check all tests passing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@sortizsh split into two.

**Comment by sortizsh** [comment]
companion to https://github.com/department-of-veterans-affairs/va.gov-team/issues/46290
