### ISSUE TITLE
Remove obsolete feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46044]
## Value Statement

**_As a_** developer
**_We want to_** clean up unused feature flags
**_So that_** we can ensure that when the flags are removed, it doesn't effect our forms

## Background Context

Several [apps include feature flags that need to be investigated and removed](https://docs.google.com/spreadsheets/d/1WAA8Xxpq9zmuQl-lyId4kgKVt3tXY3Cm4QG3vOqKgxA/edit#gid=0):

- `form10182_nod` - Notice of Disagreement production flag - no longer used, needs to be removed
- `omni_channel_link` - Claim Status Tool - Discuss status with Omni channel team
- `show526_wizard` - Form 526 - no longer used, needs to be removed
- `va_view_dependents_access` - Dependency verification app - need to investigate & discuss with team before removing

## Tasks

- [ ] Remove un-needed feature flags in forms
- [ ] Update mock data
- [ ] Update platform feature flags code
- [ ] Check unit tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38842
