### ISSUE TITLE
Review and update rates table headings with more descriptive language

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46060]
## Issue Description

We learned there's a 508 issue on our rates pages where screen readers can't decipher what is in a table based on the headings because they aren't descriptive enough. We already made changes to the compensation rates page in ticket #46043. We now need to look at our other rates pages to make similar updates to table headings.

Pages to look at:
- [ ] Disability rates
- [ ] Pension rates
- [ ] Health care rates

If there are headings for tables that aren't descriptive enough for a screen reader to know what the table is specifically showing, we need to add that to the headings. If we make updates to a current rates page, we need to make sure we are also updating the past rates pages.

## Tasks
- [ ] Review rates pages
- [ ] Update pages
- [ ] Review changes (Laura)
- [ ] Copyedit changes (Megan)
- [ ] Publish changes (Megan)

## Acceptance Criteria
- [ ] Rates pages have descriptive headings above tables

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
