### ISSUE TITLE
[CDP] Remove cross app references 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46079]
## Issue Description
Release Tools is working on a script that prevents cross app imports from being added to apps, so we need to remove cross app references while we work on a deprecation plan for the old `medical-copays` and `debt-letters`. 

---
## Tasks
- [ ] Remove any cross app references from `medical-copays`
- [ ] Remove any cross app references from `debt-letters`
- [ ] Remove any cross app references from `combined-debt-portal`
- [ ] Check for any cross app references from `FSR`

## Acceptance Criteria
- [ ] No more cross app references for benefits related applications.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
[#22046](https://github.com/department-of-veterans-affairs/vets-website/pull/22046) covered removing references to/from CDP to prep for getting it added to the allow list. This ticket will track the remainder of that work and removing the rest of mcp/debt-letters references as well

**Comment by Dr-Pongo** [comment]
This tasked turned out to be more than expected, but FSR and debt-letters can't be added to the allow list for continuous deploy until after all cross app references are removed. Future FSR work to replace the `static-pages` wizard references will hopefully fix this issue. 

Currenty working on a solution for `debt-letters` by removing `personalization` references.

**Comment by Dr-Pongo** [comment]
Marking this as complete for now. The other references can be removed/updated in a future effort when addressing more specific apps
