### ISSUE TITLE
[CDP] Updating analytics

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46078]
## Issue Description
Analytics team is looking to track navigation through CDP, and we may need to add some custom analytic options since it appears as though GA isn't picking up the events from `react-router-dom` Links between pages. 

[Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1660856406670359)

---
## Tasks
- [ ] Investigate analytic options for tracking navigation in CDP
- [ ] Implement analytics for tracking and update [spreadsheet](https://docs.google.com/spreadsheets/d/1uShRq2no_W37foQ7QiBZ9M_tOhszI-lfjqM_KjnCm4E/edit#gid=0) with event information

## Acceptance Criteria
- [ ] GA analytics is tracking CDP navigation
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
