### ISSUE TITLE
Streamlined Waiver + Wizard Design User Flow Draft

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#46088]
## Issue Description
User flow for Streamlined Waiver and Wizard

---
## Tasks
- [x] Create user flow for Streamlined Waiver
- [x] Create user flow for Wizard

## Acceptance Criteria
- [x] [Link user flow document](https://miro.com/welcomeonboard/SVhYSTFKUnNrb1RhYTlxZnVjYU1FaGJmT0pXRk9OQ05PSDJkWGo1NVVxWEZYQkpXTkZUVjc1VjJKVkdXRTl4YnwzMDc0NDU3MzUzNTA5NjYxMTE1?share_link_id=739525534636)
