### ISSUE TITLE
PDF password component fixes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46083]
## Description

When a password-protected PDF is uploaded, the `ShowPdfPassword` component is rendering a "required" label with extra parentheses and an asterisk
<img width="554" alt="required Input label with the required text wrapped in extra parentheses and an asterisk" src="https://user-images.githubusercontent.com/136959/186020079-7e8879b9-a743-4a62-b09b-5ffa233eba62.png">

Updating the component to use component-library web components will fix this issue. It will also change the green (deprecated) button into a blue "Add password" button.

## Tasks

- [ ] Update React components in`ShowPdfPassword` to use web-components
- [ ] Update tests

## Acceptance criteria

- [ ] All tasks complete
- [ ] All tests passing
