### ISSUE TITLE
Discovery - Auth Profile - Military Service - Open-ended service history episode

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#46087]
## Background
It is possible for a veteran to have an open-ended military service episode that is missing an end date.  If an end date is missing, the termination code can be used to determine whether the episode is valid or if a data integrity issue exists. [More details here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#business-rules).

The purpose of this ticket is to determine how to handle and display open-ended military service episodes.

## Tasks
- [x] Determine how to handle and display a military episode that is missing an end date with a termination code of "W".
- [x] Determine how to handle and display a military episode that is missing an end date with a termination code not equal to "W" (data issues).

## Acceptance Criteria
- [x] Create FE and BE tickets for the work.

**Comment by tpharrison** [comment]
@SKasimow - related to this convo - https://dsva.slack.com/archives/C909ZG2BB/p1660829024465739.

**Comment by SKasimow** [comment]
@tpharrison - I added to the new sprint (sprint 81 starting today); lmk if not the right spot.
