### ISSUE TITLE
Migrate vets-api-server dev to helm chart

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46093]
## Description
The `vets-api-server ` dev app is currently a native k8s deployment, not using helm. We are migrating to a helm structure for uniformity.  

## Tasks
- [x]  Create helm chart
- [x] Migrate existing manifests to use helm
- [x] Remove existing code from `vsp-backend-tools/apps/`

## Acceptance Criteria
- [ ] vets-api-server dev is running in argo

**Comment by LindseySaari** [comment]
https://app.zenhub.com/workspaces/platform-console-services-6221189e9d589600144196ca/issues/department-of-veterans-affairs/va.gov-team/46093

**Comment by LindseySaari** [comment]
PR Here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/758
