### ISSUE TITLE
Promote sidekiq higher envs to EKS

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46097]
## Description
Sidekiq background workers for higher envs need to be added to our EKS cluster. We'll also need to shut down BRD Sidekiq as part of this process so they're not working the same queue.

## Tasks
- [x] Write helm chart for Sidekiq deployments
- [x] Apply and verify the deployment w/ an Infra member
- [x] Sidekiq is onboarded in argo
- [x] Shut down BRD workers and test jobs and workers in k8s

## Acceptance Criteria
- [x] jobs and workers are properly running in staging and prod clusters
