### ISSUE TITLE
[BE] Get  Error Message when Pre-Check-in Link Used when there is no UUID Match

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#46107]
## User Story
As a Veteran, if I visit a Pre-Check-in link and there is no UUID available that matches my link, then I would like to know that I cannot continue so that I don't have to log in and then find out that I cannot continue.

## Wireframes/Content
See [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/46155)

## Tasks
- [ ] [BE]  If the refresh_precheckin call fails in SessionsController#GET, return an appropriate error back to the website

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync can this be closed?
