### ISSUE TITLE
Update OIDC Charon endpoint in staging

### ISSUE THREAD

**Issue by madebydna** [department-of-veterans-affairs/va.gov-team#46119]
## Issue Description
Change the `oidc.charon.endpoint` setting in staging to a forward proxy address that points to the Lighthouse server in sandbox. The setting doesn't exist in dev or sandbox, and in production, we already use the forward proxy address.

To complete this task, we need to open a new port in the forward proxy that points to sandbox from staging.
---
## Tasks
- [x] Create new forward proxy port that points to sandbox from staging
- [x] Change `oidc.charon.endpoint` setting to use the new port

## Acceptance Criteria
- [x] Fwdproxy port opened and functional
- [x] `oidc.charon.endpoint` setting changed to use the new port
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
