### ISSUE TITLE
Streamlined Waiver SME Questions

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#46113]
## Issue Description
Compile list of questions for SMEs

---
## Tasks
- [x] Draft [list of questions](https://miro.com/app/board/uXjVPeJqY_E=/?openNotes)
- [x] Send meeting invite or email to SMEs

## Acceptance Criteria
- [x] Questions emailed or meeting scheduled

**Comment by mgleo** [comment]
Meeting scheduled Friday, September 9, 2022 at 11:30am
