### ISSUE TITLE
[FE] Display Error Message when Pre-Check-in Link Used when there is no UUID Match

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46116]
## User Story
As a Veteran, if I visit a Pre-Check-in link and there is no UUID available that matches my link, then I would like to know that I cannot continue so that I don't have to log in and then find out that I cannot continue.

## User Workflows
- Given I
    - Have a Pre-Check-in link for which there is no UUID
- When I
    - Click the link
- Then I
    - See an error message page instead of a login page

## Wireframes/Content
See [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/46155)

## Tasks
- [ ] [FE] Show error message to user before they verify their identity

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
DO NOT show the new "Find out how to check in on the day of your appointment" link for this new eror

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/fd12cb28-30aa-47ab-858b-bebc789e1c01)

**Comment by loripusey** [comment]
Final decision:
- This main message
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/194dcdc7-7aa6-4da2-be19-77621f0f5423)
- With this blue box
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/e3fc49f7-e2dc-4d4b-a68c-062236dd7e01)
- And no "How to Check-in....." link

**Comment by loripusey** [comment]
@zach-park can you update the wireframes to match the final decision?

**Comment by zach-park** [comment]
@loripusey @brianseek , here is the updated wireframe per discussion:
https://share.goabstract.com/db9517dc-1a98-4de1-8d2e-54dad13552f2?collectionLayerId=35543ba6-4f62-4261-b2af-033282668ddf&mode=design

**Comment by brianseek** [comment]
@loripusey to validate once backend part merged

**Comment by brianseek** [comment]
Moving this back to In progress. The error code will be 500 instead of 401.

**Comment by brianseek** [comment]
Update for 500 error is merged. @loripusey this should be good to review on stage.

**Comment by loripusey** [comment]
validated on staging, looks good!
