### ISSUE TITLE
Discovery sprint 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4611]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/product-outlines/Service-centric-deployment-initiative-outline.md)

## High Level User Story/ies
As a team developing on VA.gov, I want to have a stable platform that allows my team and others to grow at our rate, empowering us to develop using best practices, so that we can create and expand upon great services for our Veterans.

## Definition of done
- [x] conduct interviews 
- [x] Gather findings  
- [ ] Report out findings 
- [ ] Road map 

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
