### ISSUE TITLE
Add team members to flipper admin list

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#46125]
## Background
Need to add some of our team members to the flipper admin list
Users to add:
* @samcoforma 
* @scottymeyers
* @jacobworrell
* @jerekshoe 

## Task
- [x] Get team member ID.me emails
- [x] Add users to flipper admin list

## Acceptance Criteria
- [x] Users added to flipper admin list
