### ISSUE TITLE
Sidekiq UI Release Plan

### ISSUE THREAD

**Issue by FHiatt** [department-of-veterans-affairs/va.gov-team#46139]
## Problem
We would like to release a standalone instance of Sidekiq UI where we reduce the complexity by enabling a standalone (microservice) deployment capability. This will make for a smooth transition of the Sidekiq UI microservice to other teams (e.g. Console Services).

## Acceptance
- [x] The actual deployment instance of Sidekiq UI in production.
 - [x] Usability test this release introduces no usability changes. 
 - [x] ... and issues discovered in usability testing have been addressed.
 - [x] End-to-end manual QA or UAT is complete, to validate there are no high-severity issues before launching
- [x] (if applicable) New functionality has thorough, automated tests running in CI/CD
... documented?
- [x] New documentation is written pursuant to our documentation style guide
- [x] Product is included in the List of VSP Products 
- [x] Internal-facing: there's a Product Outline https://vfs.atlassian.net/wiki/spaces/IET/pages/2315354142/Product+Outline+-+Sidekiq+UI+Q3+2022
- [x] To Do External-facing: a User Guide on Platform Website exists for this product/feature tool https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs
- [x] (if applicable) Post to #vsp-service-design for external communication about this change (e.g. customer-facing meetings) not applicable – no customer facing change
... measurable
- [x] (if applicable) This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
- [x] This change has an accompanying VSP Initiative Release Plan.
https://app.zenhub.com/workspaces/integration-experience---platform-spike-team-61f18a64735e8e0015911cf7/issues/department-of-veterans-affairs/va.gov-team/40061
When you're ready to launch...
- [x] We are planning on making an announcement in the platform team channel this is not a VFS related change. Configure your communication to teams about your work using the Change Communication Guide. 
- [x] 8/23/2022 - Conduct a go/no-go when you're almost ready to launch.https://vfs.atlassian.net/wiki/spaces/AP/pages/2334588943/8+23+22+Office+Hours+Agenda+and+Notes

**Comment by ewilson-adhoc** [comment]
https://github.com/department-of-veterans-affairs/access-management-integration/issues/154 <- created this request to set up the keycloak infrastructure.

**Comment by andreahewitt-odd** [comment]
@FHiatt you're supposed to use the release plan template found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-release-plan.md) that is linked to in our [initiative template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-initiative.md)
