### ISSUE TITLE
Create new COVID facility status messages

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46153]
## Issue Description
David from Sitewide Facilities asked us to help create new COVID status messages to replace the current facility status messages. See [intake ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774#issuecomment-1225113777).

---
## Tasks
- [ ] Draft new messages
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Review (Danielle)
- [ ] Pass to Sitewide Facilities in their ticket

## Acceptance Criteria
- [ ] Approved messages are posted in Sitewide Facilities ticket

**Comment by laurwill** [comment]
My mistake! This is a duplicate. Closing now.
