### ISSUE TITLE
[Design] Create Final Wireframes: Error message page instead of a login page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46155]
## User Story
As a Veteran, if I visit a Pre-Check-in link and there is no UUID available that matches my link, then I would like to know that I cannot continue so that I don't have to log in and then find out that I cannot continue.
(Collab/review with @niradatta1 on content)

## User Workflows
- Given I
    - Have a Pre-Check-in link for which there is no UUID
- When I
    - Click the link
- Then I
    - See an error message page instead of a login page

## Tasks
- [x] Create final mockups with callouts 
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Wireframe (In-progress)
https://share.goabstract.com/d536019c-6b8b-4a06-bbc9-9d0502d5c277?collectionLayerId=1f4c0452-0fe6-4973-85c9-483029c6a506&mode=design

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by zach-park** [comment]
Tagging @niradatta1-zz

**Comment by zach-park** [comment]
@niradatta1-zz testing

**Comment by benbrasso-agile6** [comment]
Is this the wireframe we want for this? https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a?collectionLayerId=5649ca71-4284-41cf-9301-f5cdcd14e101&mode=design

**Comment by zach-park** [comment]
@benbrasso-agile6 Yes, minus the telephone appt copy. 
@brianseek @loripusey, regarding the infobox in the no uuid error page, it looks like the wireframe wasn’t up-to-date, and got carried over to this ticket. I'll update both.

**Comment by benbrasso-agile6** [comment]
Sorry, we can't complete pre check in

blue box message includes content for telephone and in person 

no link for find out how to check in

**Comment by zach-park** [comment]
Reference ticket link: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46116#issuecomment-1252583509
