### ISSUE TITLE
FE | Profile | Military Info | Update Alert w/ Blue Border

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46150]
## Background

The additional information component "What if my military service information doesn't look right?" has an expandable section _without_ a side border however, the design calls for a border:

### **Production:**
![Screen Shot 2022-08-23 at 8 56 18 AM](https://user-images.githubusercontent.com/8332986/186196807-ba9ca64d-2cd5-46c8-b808-ac8dd072af53.png)

--- 
### **DESIGN:**
<img width="700" alt="Screen Shot 2022-08-23 at 9 18 58 AM" src="https://user-images.githubusercontent.com/8332986/186196918-c4d890f5-bd97-44d8-81a0-25b40e39d5e0.png">

---

## Tasks
- [x] Update the code to add the blue border as shown in the design mock above
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

**Comment by Samara-Strauss** [comment]
Removing @adamwhitlock1 as an assignee, though Adam may need to support John as-needed. I just didn't want this cluttering Adam's board since he has a full sprint already for sprint 84.

**Comment by jcatergovy** [comment]
@SKasimow There's a line of code that intentionally disables the border on this element.  I want to wait till everyone's back tomorrow to see if there's a good reason for this before I commit my changes and push to staging.
