### ISSUE TITLE
[cFSR] Text Updates to Enhanced FSR UXPin

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#46160]
## Issue Description

Text Updates to Enhanced FSR UXPin 

---
## Tasks
- [x] Make updates to UXPin

## Acceptance Criteria
- [x] Text updates made to UXPin

___

List of updates:

- [x] **[Add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842696/comment/sitemap?mode=i)** - [Add Platform's new date component](https://design.va.gov/components/form/date-input) (This front-end update was already made)
- [x] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - add "TSP"
- [x] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - clarify brokerage account for stocks and bonds? _Other stocks and bonds (not in your retirement accounts)_
- [x] **[Wizard intro](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768)** - "...need help with _debt related to VA benefits or health care copays._"
- [x] **[Trailers, campers, boats](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*wfldoq*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/145355861/comment/sitemap)** "Estimated value of _all of_ your..."
- [x] **[Vehicle value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965)** - "This includes vehicles with a loan."
- [x] **[Real estate value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*uewksx*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/146385053/comment/comments,sitemap)** - "This includes properties with a mortgage."
