### ISSUE TITLE
Manifest image tag updates for Sidekiq

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46166]
## Description
** BLOCKED UNTIL SIDEKIQ IS PROMOTED TO HIGHER ENVS

Upon push to EKS master (currently the k8s branch), the image tag for the sidekiq deployments should be updated. Since we've moved to helm, the image tag can be found in the values.yaml file per deployment. 

## Tasks
- [x] Update GHA to push image tag for sidekiq (all envs)
- [x] Verify that the va-vsp-bot commits the new image tag
- [x] Verify auto sync works properly in Argo for each app

## Acceptance Criteria
- [x] Image tag auto updates and argo can properly sync the app
