### ISSUE TITLE
Configure/update GA Events

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#46171]
## Tasks 

- [ ] Document what events we want to track 
- [ ] Document category, action, labels
- [ ] Document in Git
- [ ] Update/configure events in the code   
- [ ] Confirm working in prod
- [ ] Set up widget or widgets in CIE GA Dashboard to bring forward those events
- [ ] Share CIE GA Dashboard with CIE Team 

## AC

- [ ] Documented in Git
- [ ] Confirm working in prod
- [ ] Share CIE GA Dashboard with CIE Team

**Comment by benbrasso-agile6** [comment]
@brianseek review and update tasks and AC, if necessary

**Comment by brianseek** [comment]
Waiting for @benbrasso-agile6 final analysis to start any dev work on this one. Here are the existing events:

API call - all api calls (Working as expected)
Back button/Back to appointments - (needs to have nav prefix added)
Check-in button - (needs a prefix to work, maybe nav, maybe something custom)
Demographics - (needs a prefix to work, maybe nav, maybe something custom)
Emergency Contact -(needs a prefix to work, maybe nav, maybe something custom)
Next of Kin - (needs a prefix to work, maybe nav, maybe something custom)
Landing page - (needs a prefix to work - not sure which existing category works might need custom, or maybe the new url error-params makes this redundant)
Day of Appointments page - refresh-appointments-button-clicked (needs a prefix to work, maybe nav, maybe something custom)

**Comment by benbrasso-agile6** [comment]
API Calls - Ben to maybe evaluate these or work backwards from what we want to track first - https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last7days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:API%20Calls&_.useg=userhW7DdmRMTe68loSjpKLxGQ/

Back buttons, yes
Go back to appointments, yes 

Check-in button, no (we already have this in API Request)

Demographics, yes (use Nav)

EC, yes (use Nav)

Next of Kin, yes (use Nav) 

Landing page, no

Day of Appointments page, yes (use Nav) 

Travel pay, which is on the day of confirmation page, yes (use Nav) 

Sign in link which is located in the accordion on the confirmation for pre check in "How can I updated my information", yes

**Comment by benbrasso-agile6** [comment]
https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=0

**Comment by brianseek** [comment]
@benbrasso-agile6 this is ready to validate when you are back in office. Bethany brought up a good question in the PR for this. 

> Do we want to differentiate between check-in and pre-check-in on the yes/no demographics page clicks? Currently both are being logged with identical events.

My reply back was that I think you are looking these up in context of the URLs for those specific apps. Also that we weren't currently doing it for other events. Let me know if you think we should add that to the event.

**Comment by benbrasso-agile6** [comment]
@brianseek I would close this ticket for now. I'll need @loripusey to create a new ticket for me to review this work. I think the next steps are as follows: 

1) Use chrome extension to document events in the google spreadsheet
2) Add descriptions in the spreadsheet for what is actually being tracked for each event. Talk to Brian, as needed. 
3) Determine if we need to distinguish check in vs pre check in the Event values
4) Update GA Dashboard widget names to be more descriptive of what they're actually tracking

**Comment by loripusey** [comment]
Here the new [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/46781)
