### ISSUE TITLE
repair and move review instances to staging

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4617]
## Product Outline
[link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/review-instances/product-outline.md)

## User Story or Problem Statement

As a VFS developer, I need to access backend VA services in lower environments that are more consistent with production. The services exposed to us are of varying quality in the dev environment (and mocking enabled on some) which makes them problematic to use. By switching to run review instances inside the staging environment, we believe we can make this experience better for developers.

## Goal

Allow developers to connect to staging backends in VFS by switching review instances to run in the staging environment.

## Objectives or Key Results this is meant to further

- 5. Ensure VSP scalability through increased self-service tooling and documentation				"

## Acceptance Criteria

- [x] Review instances are in staging with a similar configuration to the staging-api.va.gov instances

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@wyattwalter add more details.

**Comment by wyattwalter** [comment]
@benniemosher The review instance configuration is pretty old and I'm sure there'll be a ton of potential tech debt we can cleanup. I think we could do the move of these instances into the staging environment and do a time-boxed cleanup for the remainder of the sprint to avoid falling into this trap.

I think the major pieces that have to be touched:

- make sure we have an SG and appropriate rules for the SOCKS proxy to reach the new instances in vetsgov-staging
- review-instance-create role will need to change to point at a different network
- review-instance-configure role will need a majority of the work, I suspect
- I don't think the internal zone configuration needs to be updated -- seems to just check for a `slug` tag on instances
- suspect review-instance-cleanup.yml will need some work as well to make sure the new ones aren't ignored by cleanup task

**Comment by wyattwalter** [comment]
It turns out that authentication is completely busted for review instances and may have been for some time. Looking at evidence so far, it seems that these instances haven't really been used by anyone for a while. Our current theory is that if we make them more accessible and obvious that they're there that they will start to see some more usage.

I'm going to spin off a separate ticket and ask for some help in getting authentication working again, we'll continue to get the backend services setup so they can be reached and try to refine the process for provisioning in the meantime.

**Comment by wyattwalter** [comment]
We should also take this on as well: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3121

**Comment by wyattwalter** [comment]
This work keeps expanding, but I have been sharing updates out and there's agreement that the expansion is well worth it.

I made this an epic to split off separate tasks. I feel like I'm probably missing stuff right now, but will add tickets as I discover more.
