### ISSUE TITLE
[FE] - Add Clinic IEN to Clinic label in CIE staging tool

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#46186]
## Description
Add clinic IEN anywhere we show the label.

Slack thread reference: https://dsva.slack.com/archives/C02G6AB3ZRS/p1661361687487339

## Tasks
- [ ] Update clinic label to include IEN
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
This is deployed and working. @acrollet when you get a chance can you also confirm?
