### ISSUE TITLE
Promote vets-api-server and sidekiq to Sandbox

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46182]
## Description
vets-api-server and sidekiq are being running via k8s for dev, staging and prod. We will also need sandbox deployments for both applications. Additionally, we should be mindful of the settings.yml because sandbox may have additional or different values since it's used for Lighthouse SLA's.

## Tasks
- [x] Create helm charts for vets-api-server sandbox
- [x] Create helm charts for sidekiq sandbox
- [x] Diff the settings.yml file between BRD and EKS for server and sidekiq
- [x] Fix any mismatched settings/update references or add to parameter store
- [x] Open an [app promotion form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-promotion%2Coperations&template=application-promotion.yml&title=Application+to+Promote%3A+%5Bapplication-name%5D) for vets-api-server sandbox
- [x] Open an [app promotion form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-promotion%2Coperations&template=application-promotion.yml&title=Application+to+Promote%3A+%5Bapplication-name%5D) for sidekiq sandbox

## Acceptance Criteria
- [ ] vets-api Server and worker are functioning properly in EKS for the sandbox environment

**Comment by laineymajor** [comment]
We cannot have sidekiq running as it runs off the same queue as BRD. Need to brainstorm on this.

**Comment by laineymajor** [comment]
Duplicate of the manifest files ticket. Closing.
