### ISSUE TITLE
[Application hosting and deployment] Develop 'hello world' Helm template

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#46184]
## Description
When a new application is being onboarded to ArgoCD and EKS, there needs to be a Helm chart in place. 

## Background/context 
- Please see parent initiative for more information 
- The application onboarding automation checks to see if a helm chart exists for the application 
  - If it does exist, do nothing
  - If it does not exist, create a 'hello world' Helm chart 
---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] A basic, 'hello world' Helm template will be provided for new applications that do not yet have a Helm chart 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by jhouse-solvd** [comment]
@mleclerc00 - @ph-One and I created a basic issue for this work. feel free to modify and link PRs.

**Comment by jhouse-solvd** [comment]
Follow-up issue to write user-facing documentation here: #46554

**Comment by oseasmoran73** [comment]
Created secondary [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46845)
