### ISSUE TITLE
Campaign landing page template - design, build, launch, and learn

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4621]
## Campaign landing page template - design, build, launch, and learn
This is a new epic for creating a campaign landing page template. This rolls up to the [super epic for tier 2 content templates](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/2281). 

[CLP template product repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates)

[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates#campaign-landing-page-template-mvp-10---product-outline)

**Problem statement:** 
Many benefit-adjacent tier 2 content are not support content, product/top task content, or evergreen office content. 
- It may also have audiences other than Veterans (for example: local governments, Congress, VSOs, medical researchers). 
- It may also be of a time based nature, like a particular campaign (#BeThere) or a new legislation change (MISSION Act).
This category of content could be better served as a campaign landing page. 

- [x] MVP FE design template
- [x] Build FE template
- [x] Design intent ([ticket here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6704))
- [x] Document use cases and "commonalities" (e.g. new components which are re-usable, including Learning Center)
- [x] Build Drupal AX (authoring experience) model
- [x] Create "internal" prototype to test the the Drupal AX
- [x] [Build front-end template](https://docs.google.com/document/d/1euEecCA615iI2vexnMnQB4l_aLk1irxOOV7_tpPY6gk/edit#) 
- [x] Determine IA and URL approach (including building into the CMS governance experience) ([ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16813))
- [ ] Work with at least two VA stakeholder groups to build CLP prototypes (staging-only)
- [ ] Determine and build CMS governance
- [X] Request Analytics Tracking ([ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16749))
- [X] Request KPI Dashboard ([ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18315))
- [x] Build in analytics tracking on page (build in default tracking of primary and secondary buttons; page links; downloads)
- ~[ ] Launch w/MVP pilot in production~
- [x] Accessibility review
- [x] Launch with a business stakeholder to pilot the AX
- [ ] Socialize w/ VA businesses (concept, guidance; CMS training & onboarding)

**Comment by jenniferlee-dsva** [comment]
Current subtasks:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2839

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3582

**Comment by jenniferlee-dsva** [comment]
Design intent and accessibility check-in requested: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6704

**Comment by rtwell** [comment]
files uploaded [in the design WIP folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/design-wip), in the product folder here

**Comment by rtwell** [comment]
![CLP-Maximal-markup](https://user-images.githubusercontent.com/12564977/77205114-8b3a1900-6aca-11ea-818c-22a288c4aade.png)
![CLP-Maximal-mobile](https://user-images.githubusercontent.com/12564977/77205123-8f663680-6aca-11ea-8414-a1b3c87a7223.png)
![CLP-Maximal-no-images](https://user-images.githubusercontent.com/12564977/77205126-8ffecd00-6aca-11ea-826f-85b6a5fe2d8b.png)
![CLP-Maximal](https://user-images.githubusercontent.com/12564977/77205130-912ffa00-6aca-11ea-9244-887c511bbe76.png)
![CLP-required sections-no-images](https://user-images.githubusercontent.com/12564977/77205138-942aea80-6aca-11ea-933f-9970d11daa65.png)
![CLP-required sections](https://user-images.githubusercontent.com/12564977/77205141-94c38100-6aca-11ea-8a0f-aa2cd3c5daeb.png)

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx @johnhashva @rtwell - The CLP template is ready to be built as a Drupal product. We're decoupling this template work from the suicide prevention-specific campaign content pilot, as we cannot wait until next fiscal year to build this template to be used by VA. 

So this work should now focus on building this template as a product in the CMS and all of the associated parts (CMS governance, IA and URL strategy and CMS governance, FE default analytics, etc.)

Thank you!

**Comment by FranECross** [comment]
Closing as completed
