### ISSUE TITLE
Certificate of Eligibility | Remove obsolete feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46228]
## Description

Certificate of Eligibility copied some code from platform that still has a feature flag in the code that have been removed, and need to be cleaned up: `request_locked_pdf_password`

Related to #38842

## Tasks

- [ ] Remove feature flag code in COE/platform
- [ ] Update tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Closed as already done as part of [#22083](https://github.com/department-of-veterans-affairs/vets-website/pull/22083)
