### ISSUE TITLE
[FE] Refactor skipped test to work more consistently

### ISSUE THREAD

**Issue by brdunfield** [department-of-veterans-affairs/va.gov-team#46239]
## Background
We received a PR review request to skip one of our tests that often fails CI. We have asked in the PR as part of our review for more information to help troubleshoot. We should refactor the test in question based on this feedback so that it passes consistently.

Blocked until we receive a response.

PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/22022#pullrequestreview-1085817474

## Tasks
- [ ] Determine if the test needs to be refactored
- [ ] [FE] Fix test, if necessary
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Test passes CI consistently

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
platform support request for more info: https://dsva.slack.com/archives/CBU0KDSB1/p1662059907577239

**Comment by brdunfield** [comment]
CI run where test failed:
https://github.com/department-of-veterans-affairs/vets-website/runs/8003842765?check_suite_focus=true#step:9:1081

**Comment by acrollet** [comment]
This test was fixed by Darius Dzien.
