### ISSUE TITLE
[VA Notify Team Inquiry] Chapter 36 Confirmation of submission success and other questions

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#46244]
## Value Statement
**_As a_** VA Notify product manager
**_I want to_** understand status changes for successful Chapter 36 application submissions
**_So that_** I can assess how to implement email confirmation notification functionality. 

---
## Background Context
VA Notify Strike team is working on adding email confirmation notifications to Veterans when they have submitted their applications. Chapter 36 is the next form our team would like to tackle. We have a few questions for you and your team.

## Open questions
- Our team took a dive into that form and wanted to verify if we have the right status change for successful submissions. Should the trigger be placed:

module V0
  class EducationCareerCounselingClaimsController < ClaimsBaseController
    def create
      load_user
      claim = SavedClaim::EducationCareerCounselingClaim.new(form: filtered_params[:form])

      unless claim.save
        StatsD.increment("#{stats_key}.failure")
        Raven.tags_context(team: 'vfs-ebenefits') # tag sentry logs with team name
        raise Common::Exceptions::ValidationErrors, claim
      end

      claim.send_to_central_mail!
      # send mail here

      Rails.logger.info "ClaimID=#{claim.confirmation_number} Form=#{claim.class::FORM}"
      clear_saved_form(claim.form_id)
      render(json: claim)
    end

We will need to isolate the call to claim.send_to_central_mail! inside a separate sidekiq job to make sure the request to create claim does not keep the user waiting on the frontend. Inside this Sidekiq job will send the claim to central mail and then send the confirmation email.

- Were should the user be sent to check the status of their application?

## Tasks
- [ ] _Assign to a backend developer for review_
- [ ] _Send an update to Megan Siddle, product manager for the VA Notify team_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megansiddle** [comment]
https://dsva.slack.com/archives/C5AGLBNRK/p1661462376664959?thread_ts=1661453631.941429&cid=C5AGLBNRK Looks to be all resolved! Thanks!
