### ISSUE TITLE
Automate fwdproxy and revproxy deploys in lower environments

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#46249]
## Description
In [Jenkins](http://jenkins.vfs.va.gov/job/deploys/), put the fwdproxy-dev/staging and revproxy-dev/staging deploys on cron jobs so the `dev` environments run at the top of the hour and the `staging` environments run once a day.

## Background/context 
It's not uncommon for people to ask us to re-deploy fwdproxy or revproxy so they can test their changes. Redirect PRs are an example of when this would be handy (https://github.com/department-of-veterans-affairs/devops/pull/11843).

## Technical notes
I believe a change is needed to [seed_job.groovy](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy).

---
## Tasks
- [ ] Make the change
- [ ] Test the change
- [ ] Notify people who would be interested in this change and/or update docs to reflect this change.

## Acceptance Criteria 
- [ ] Tasks are complete

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
