### ISSUE TITLE
[Documentation] Update Platform Website Documentation with how to install VA Internal Certificates

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#46242]
## Description
Need some documentation that goes over accepting the VA Internal Certificates in browsers

## Background/context 
https://dsva.slack.com/archives/C03KT515C0H/p1661448796553339

---
## Tasks
- [ ] Documentation updated for how to accept the VA internal SSL certificates

## Acceptance Criteria 
- [ ] Documentation updated with requested information

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mchelen-gov** [comment]
This is to prevent users from experiencing SSL errors when visiting `*.vfs.va.gov` URLs such as https://grafana.vfs.va.gov/

**Comment by jbritt1** [comment]
Recent support request: https://dsva.slack.com/archives/CBU0KDSB1/p1661446730480909

**Comment by acrollet** [comment]
Popping my head in to say that this is a recurring issue, just talked to a group of VA.gov devs that were unaware that VA internal certs are even A Thing...
