### ISSUE TITLE
[Ongoing Service] 2022 Q3 - Contact Center Support

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46265]
## Problem Statement 
* VA.gov user need support for issues they encounter while trying to complete tasks on VA.gov. Our team is responsible for tier 2 and tier 3 support for issues originating from call to the VEO contact center (White House Hotline/VA411) and tier 2 AskVA (AVA) support for issues submitted through the AVA online portal. 
* For each product or service on VA.gov there needs to be a comprehensive user guide for support personnel to use while assistance Veterans with issues using that product or service. We provide reviews of product guides for VFS teams in the collaboration cycle to ensure relevance, adherence to VA.gov standards and plain language best practices.

How might we help Veterans find solutions to the issues they encounter on VA.gov.

## Hypothesis or Bet
* If we provide efficient and effective support for Veterans using VA.gov, we will get fewer return calls.
* If we provide efficient and effective support for Veterans using VA.gov, Veteran satisfaction will increase.

## Definition of Done
We will know we're done when when Veterans no longer experience issues on VA.gov; we will never be done, but will work to be better.

### Documentation
* **`Contact Center Support`**
* **[Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1791983795/Contact+Center+Tier+II+III+Support+Product+Outline)** 
* **[User Guide](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1859780742/How-to+Use+Contact+Center+Data+on+DOMO)**

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [ ] **N/A** Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)
