### ISSUE TITLE
Review content for new "Notification letters" page pre-testing

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46268]
## Issue Description
Skyler requested our content review for a new "Notification letters" page the Benefits Team 1 is planning to test with Veterans. 

Links:
- [Intake ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45908)
- [draft content in Sketch](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/prototype/a/775B3120-703A-47C3-8054-E2586037F1EA)
- [Initial IA work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ben1-letters.md) 

---
## Tasks
- [x] Review draft content (Laura)
- [x] OCTO review (Beth)
- [x] Copyedit (Katherine)
- [x] Pass to product team (Laura)

## Acceptance Criteria
- [x] Approved content is posted in intake ticket

**Comment by laurwill** [comment]
Hi @bethpotts , 
I reviewed the draft content for this page and made some suggested updates. Want to look at this together in our check-in today?
[Notification letters content review.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9433355/Notification.letters.content.review.docx)

**Comment by laurwill** [comment]
@DanielleThierryUSDSVA , collecting some notes for our chat here:
- Product team said the priority items for content review are the new Notification letters page and the info alert on the Claim status tool page. This content is going into testing, so there'll be another opportunity to review before it's final. Beth and I had talked about focusing on labels for now, but here's my working doc where I had made some initial edits and questions: 
[Notification.letters.content.review LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9456816/Notification.letters.content.review.LW.docx)
- "Notification letters" is meant to be a broader category for any communications about claims/appeals/decision reviews, not only decision letters
- Beth said stakeholders had been moving towards "decision notices" at one point, but "decision letters" seems to be the most commonly searched term in semrush — I didn't find any results for "VA decision notices" or "VA notification letters" or some other variants I tried, but "VA decision letters" returns this:
![image](https://user-images.githubusercontent.com/104158104/187548272-ecf23fbc-1cfe-40eb-984f-f56c5b3b172c.png)
- I'm wondering how much we want to mirror the "Download VA benefit letters" page — the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-08-Decision-Letter-Download/conversation-guide.md) for this upcoming research has participants comparing the 2

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO , 
An update on this tool content for you:
- Mikki provided [initial IA recs here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ben1-letters.md). The current plan is to add an H2 section and sign-in widget for the new "Claim letters" tool to this existing [Download VA letters page](https://www.va.gov/records/download-va-letters/). 
- We talked with Skyler about changing the label from "Notification letters" to "Claim letters" or "Claim status letters" or something similar, to avoid confusion with other types of notifications from VA
- I made some content updates for the priority pages for testing in this document — would you like to take a look, or we could look in our checkin today? 
[Notification.letters.content.review.LW.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9497832/Notification.letters.content.review.LW.docx)

**Comment by laurwill** [comment]
Thanks so much for reviewing @bethpottsVADEPO ! I made the last few updates we talked about yesterday — leaving the label as "Claim letters" for now, and I'll add some notes for Skyler about that when I pass it off.

@RLHecht , this doc is ready for a copyedit, and then I'll pass to Skyler in the intake ticket!
[Notification.letters.content.review.LW-BP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9536394/Notification.letters.content.review.LW-BP.docx)

**Comment by katherine-fung** [comment]
Thanks @laurwill! I'm posting the document back with 2 small changes. 

Noting here that you're checking with the product team about the way we refer to the app for iPhone and Android users. 

[Notification.letters.content.review.LW-BP-KF.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9536663/Notification.letters.content.review.LW-BP-KF.docx)

**Comment by laurwill** [comment]
Thank you Katherine! This is all set — I've posted in the intake ticket and we can close this out.
