### ISSUE TITLE
Update Chapter 30 rates in draft Drupal page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46275]
## Issue Description
We have a draft Drupal node for Chapter 30 education rates, as part of the education rates migration. These rates have changed, and we need to update and copyedit the rates to send back to stakeholders today. 

Here's the PDF with the new rates: 
[https://app.zenhub.com/files/133843125/252b30[https://app.zenhub.com/files/133843125/c676109b-630a-4e31-9fbc-76b43832d396/download]

Change rates in this Drupal node, but don't publish: http://preview-prod.vfs.va.gov/preview?nodeId=5355 

---
## Tasks
- [ ] Update rates in Drupal (Katherine & Aliyah)
- [ ] Copyedit updated rates and leave as draft (Megan)
- [ ] Post for Beth to send to stakeholder (Megan)

## Acceptance Criteria
- [ ] Updated draft rates page is with stakeholder

**Comment by katherine-fung** [comment]
duplicate ticket. I'm going to close this
