### ISSUE TITLE
Update Chapter 30 rates in draft Drupal page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46276]
## Issue Description
We have a draft Drupal node for Chapter 30 education rates, as part of the education rates migration. These rates have changed, and we need to update and copyedit the rates to send back to stakeholders today. 

Here's the PDF with the new rates: 
[https://app.zenhub.com/files/133843125/252b30[https://app.zenhub.com/files/133843125/c676109b-630a-4e31-9fbc-76b43832d396/download]

Change rates in this Drupal node, but don't publish: http://preview-prod.vfs.va.gov/preview?nodeId=5355 

---
## Tasks
- [x] Update rates in Drupal (Katherine & Aliyah)
- [x] Copyedit **updated rates only** and leave as draft (Laura)

## Acceptance Criteria
- [x] Updated draft rates page is with stakeholder

**Comment by katherine-fung** [comment]
Hi @megzehn, 

This page is ready for copy edit: http://preview-prod.vfs.va.gov/preview?nodeId=5355 

@aliyahblackmore and I went through the PDF with the new rates and updated the page accordingly (thank you Aliyah!). We had some style questions, and also wanted to note a few things for your review: 

- The PDF says these new rates take effect October 1, 2022, but does not say when they last until. We're assuming they're good until September 30, 2023 (similar to the duration of rates for past years). 

- In the section "MGIB-AD rates if you served at least 3 continuous years (without a break) on active duty" -> "For institutions of higher learning," we changed "Between 1/4-time and 3/4-time enrollment" to "Between 1/4-time and 1/2-time enrollment." This is to reflect the PDF. 

We did the same for the section "MGIB-AD rates if you served between 2 and 3 years on active duty" -> "For institutions of higher learning" 

- In the "For correspondence training" section, we put: "We'll pay for 55% of the approved charges." On [other pages](http://preview-prod.vfs.va.gov/preview?nodeId=5449), we describe what correspondence training is. 
 
For example: 
"We’ll pay for 55% of the approved charges for distance-learning courses that you complete by mail, online, or in some other way." 

Should we change the sentence to something similar?

- The PDF for the new rates notes that payments for flight training are for programs "consisting exclusively of flight training." We didn't note this on the page - should we? 
 
- The section for Vietnam Veterans with remaining entitlement includes the headers "Correspondence training" and "Flight training." The other sections use "**For** correspondence training" and "**For** flight training." For consistency, which style should we use? 

- The PDF with new rates doesn't list flight training or correspondence training payments for Vietnam Veterans with remaining entitlement, but last year's rates did have them. We left this section as is. We may need to check with Beth to confirm what changes, if any, to make here. Let us know if you think so too.

**Comment by laurwill** [comment]
Thank you both so much for prioritizing this! 
I answered your Qs in bold above.

@bethpotts , I checked the rates against the Drupal page — all set to return to stakeholder.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO @RLHecht, 

I cloned the 2022 MGIB-AD rates, so it's now a new page: 
http://preview-prod.vfs.va.gov/preview?nodeId=49445 

I added a link for the modernized 2022 page on the current MGIB-AD rates page. 

I did the same for the 2022 MGIB-SR rates, per Beth's note in the revision log. The new 2022 MGIB-SR rates page is: 
http://preview-prod.vfs.va.gov/preview?nodeId=49449 

I added a link for the modernized 2022 page on the current MGIB-SR rates page. 

FYI, neither of the new pages have been copyedited.
