### ISSUE TITLE
FE | Profile | Direct Deposit Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46282]
## Background

Review DD product section in GitHub and add/update relevant FE documentation.

## Tasks
- [x] Add analytics documentation on what events we are firing and where in the code they come from.
- [x] Document Api calls and how they are set up in the FE code
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to

## Acceptance Criteria
- [x] Analytics documentation on what events we are firing and where in the code they come from added
- [x] Document Api calls and how they are set up in the FE code added
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to completed

**Comment by adamwhitlock1** [comment]
I have published the docs for the Direct Deposit FE work here

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/direct_deposit/frontend_documentation.md

Will close now
