### ISSUE TITLE
Continuous Deployment: Release Plan v2

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#46284]
## Phase I: Usability testing
- [ ] Usability testing complete ([tested](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29142) in lower environments)
- [ ] Issues discovered have been addressed.
- [ ] End-to-end [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) complete

### Planning:
- Desired number of users: 37 apps currently without cross-app imports
- The group(s) from which you'll recruit test users: VFS who have apps with NO cross-app imports
- How you'll recruit test users: Identify good candidate among VFS teams (must regularly submit PRs on app, app must not have cross-app dependencies, we must have reliable method communication with the VFS team). We will send tickets to all app teams for an option to opt OUT of continuous deployment
- How you'll give users access to the product: Theo Bentum will add an attribute to the apps on the allowlist who do not opt OUT of CD
- How you'll measure your "Success" criteria? Number of OOB deployments will reduce over time. Number of apps utilizing CD.

## Phase 2: Go Live!

- [ ] **Aug 29, 2022**
Send eligible app teams the 'terms and conditions' ticket so they have the opportunity to opt out within 2 weeks.
Apps need to respond by Sept 7, 2022 as to if they will opt IN or OUT of CD.
- [ ] **Sept 6, 2022**
PR for the following changes is merged on Sept 6, in preparation for CD.
**Apps that are part of daily deploy (ALL APPS)**
    1. There will no longer be a 1-hour delay to daily production deploy. 
    2. There will no longer be an advance Slack message about the daily production deploy 1 hour in prior to said deploy; the deployment status 
         notification will still occur.
    3. Code cutoff time has been changed from 2:00PM ET to 3:00PM ET as the 60min deployment wait will be removed.
- [ ] **SEPTEMBER 12, 2022**
Apps that remain opted IN to CD will begin using CD. 

### Planning:

- Desired launch date: September 12
- Post-launch KPI 1: Number of apps in CD (Check on Sept 12)
- Post-launch KPI 2: Number of OOB deployments (Baseline measure from the month of August)

### 1-week results:

- Number of unique apps eligible:
- Post-launch KPI 1 actual (Number of apps in CD):
- Post-launch KPI 2 actual (OOB deployments):
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique apps: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?
