### ISSUE TITLE
[Design] 10-10EZ - American Indian question: Update the dropdown info content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#46295]
## Background
In 2021, the Healthcare Enrollment Center (HEC) team requested to have a question added to both the Online and Paper version of the 10-10EZ form.  The language was reviewed with HEC and Tribal Affairs.  
In October 2021, the language below was approved by HEC team.  
In preparation for the August 8, 2022 release, the HEC team wanted the Online version to match the Paper version question language of "Are you an Indian?".
Since we had already gone through reviews and approvals, we did not want to change the question language.  

After speaking with Tribal Affairs, the language that we currently have in Staging is sufficient.  The only thing that was in question was the Information dropdown where it states "You live in an urban area and you meet at least one of these requirements" - There does not seem to be any requirement mentioned in the legislature about having to be in an "urban area". (Reference [25 USC 1603-13a](https://www.ihs.gov/sites/ihcia/themes/responsive2017/display_objects/documents/home/USCode_Title25_Chapter%2018.pdf) for definitions)  The definition of "Indian" and "Urban Indian" have the same criteria.

We agreed that we could take that sentence out, and have one list of criteria and a Veteran would only need to meet one item to be considered an American Indian or Alaska Native. 

I also confirmed with Dene' and researched GH folders -  The only tie to the "urban area" - Dene' mentioned that the original form question mentioned "urban center" and the word "center" was changed to "area" per the Tribal Affairs request at the time.  
The Paper form is not mentioning "urban center" or "urban area", and with the advisement from Travis Trueblood with Tribal Affairs, we can remove that reference and consolidate the criteria into one list.  

<details>
<Summary>Click on this dropdown for the **Dropdown language only**.  The top explanation and question remain unchanged</Summary>

> 
> What it means to be recognized as an American Indian or Alaska Native
>
>For the purposes of this application, we consider this to mean that one of these descriptions is true for you:
> 
> - You’re a member of a Federally recognized Indian tribe, or
> - The Secretary of the Interior considers you to be an Indian for any purpose, or
> - You’re eligible for Indian Health Service (including as a California Indian, Eskimo, Aleut, or another Alaska Native)**, or**
>
> ~Or~
> 
> ~You live in an urban area and you meet at least one of these requirements:~
> 
> - You’re a member or the first- or second-degree descendant of a tribe, band, or other organized group of Indians (including a tribe, band, or group terminated after 1940 or one that’s recognized by the state where you live), or
> - You’re an Eskimo, Aleut, or another Alaska Native, or
> - ~The Secretary of the Interior considers you to be an Indian for any purpose, or~
> - An official regulation from the Secretary of Health and Human Services considers you an Indian for any purpose
> 
> We’ve based these descriptions on the Indian Health Care Improvement Act (IHCIA), U.S.C. regulations 1603(13) and 1603(28).
> 
> [Learn more about the IHCIA on the Indian Health Service website](https://www.ihs.gov/ihcia/)

</details>

## Post-content review PO Meeting feedback change 9/2/22
Per a conversation with Patrick, Danielle Thierry, Lauren and the team, we reviewed the statute, the online form and the paper form. After some discussion about the definitions and how we may not be able to keep our current language, Danielle suggested that we may revise the question to have something like:
- A list of the definitions from the statute
- The question stating "Is at least one of these true for you?" 
       - This would allow us to reference the actual statute language (with minor plain language adjustments) and still collect the same information.

This was better received by the audience and decided to move forward with this plan. Danielle will look at the statute language and see where we might adjust to plain language words for clarity.

## Tasks
- [x] Update the content on the design
     - removing the sentence that references "urban area" and create one single list of criteria
     - removing the duplicate criteria line item
- [x] Send update to Heather so the Tribal Affairs team can take a quick look
### Post-Feedback tasks
- [x] Consult with Danielle Thierry on revision of the page, rearranging of the content. (see the Post-content review info above)
- [x] Update content on design to revise the question and dropdown information (info will probably be pulled out of dropdown)
- [x] Send update to the team for review
- [x] Create ticket for Frontend to update content in the code

## Acceptance Criteria
- Design is updated with the latest advisement and is shared with the team and HEC leadership

**Comment by hdjustice** [comment]
Sent email Monday 8/29/22 to HEC Team with the feedback from Travis Trueblood and Christie Prairie Chicken, explaining the change to the information section that we will make.  

>Hello and good morning all,
>
>I was able to speak last week with Travis Trueblood and Dr. Christie Prairie Chicken with Tribal Health and Veterans Care on the language of the online version of the American Indian question.
>
>The response was positive, and no changes were requested on the question itself. 
>We did review the Information dropdown content as well, and there was one small change requested there, as we were referring to a requirement that was not totally accurate.  We are removing a conditional statement and a duplicate bullet point, consolidating the criteria into one list.
>This update will be completed in the next week or so, and we will inform this audience before deploying to production.
>
>If there are any questions, please let us know.
>Thank you all for your input and patience while we make sure we are doing the right thing for our Veterans!

**Comment by jessicastump** [comment]
Here are links to the updated design files:

- [Race, Ethnicity & Origin - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/DPpAeka)
- [American Indian - Additional Info Closed - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/l1Ya9KV) 
- [American Indian - Additional Info Open - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/agl3Y4p)

- [Race, Ethnicity & Origin - Mobile](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/aglln95)
- [American Indian - Additional Info Closed - Mobile](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/agllD8r) 
- [American Indian - Additional Info Open - Mobile](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/AxoonK5)

**Comment by hdjustice** [comment]
Thanks @jessicastump!  This looks good. I will send over to Tribal health folks for a quick look too.

**Comment by hdjustice** [comment]
@klawyer @batemapf - Jessica updated the mockups to show how the update on the American Indian question page will look with the edited information dropdown.
- [American Indian - Additional Info Open - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/agl3Y4p)

**Comment by hdjustice** [comment]
Editing this ticket to reflect a revision of the American Indian question.
Per a conversation with Patrick, Danielle Thierry, Lauren and the team, we reviewed the statute, the online form and the paper form.  After some discussion about the definitions and how we may not be able to keep our current language.  
Danielle suggested that we may revise the question to say something like a list of the definitions from the statute and the question stating "Is at least one of these true for you?"  This would allow us to reference the actual statute language (with minor plain language adjustments) and still collect the same information.
This was better received by the audience and decided to move forward with this plan.  Danielle will look at the statute language and see where we might adjust to plain language words for clarity.

**Comment by jessicastump** [comment]
Here is the revised [Sketch design mockup ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kaqkZeg) utilizing the updated language provided. 
[PDF file](https://app.zenhub.com/files/133843125/45f9c248-fae9-4f5a-9393-747b721b39f2/download)

**Comment by jessicastump** [comment]
Opened FE Ticket: [[FE] 10-10EZ - American Indian question content updates #47128
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47128)
