### ISSUE TITLE
Certificate of Eligibility | Add unit tests for COE status app

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#46290]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the COE status code has unit testing coverage
**_So that_** we can ensure we're releasing a quality product

## Background Context

The COE status app is getting closer to release, we need to get code coverage up to around 80% (or more) - it is currently around [19% coverage for the status app](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)

## Tasks

- [ ] Add unit tests to increase code coverage to at least 80% to 90%
- [ ] Check all tests passing

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by sortizsh** [comment]
companion to https://github.com/department-of-veterans-affairs/va.gov-team/issues/46032
