### ISSUE TITLE
Introduce process for updating VFS Team Roster information

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46301]
## User Story
As a VFS team member, I want to notify Platform of changes to my role, team, personal information, etc. so that the VFS team roster can be updated appropriately.

Assignee:
Peer Reviewer:

## Description
The Platform Orientation process allows Platform to collect information about new team members which is captured in the [VFS Team Roster.](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) However, it is possible that team members may transfer teams, change their role, change their github information, etc. and Platform does not currently have a way to capture those changes without asking the VFS team member to complete the Platform Orientation ticket again. This ticket will implement a new solution for VFS team members to notify Platform of changes to their:

- role
- last name
- first name (?)
- organization (?)
- email
- VFS team
- github handle
- preferred pronouns

## Tasks
- [ ] _Placeholder task_

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] VFS teams know how to notify Platform of changes to their captured information

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
This ticket was discussed at Governance team refinement in January 2024 and was determined to be no longer relevant to the team.
