### ISSUE TITLE
Create R&S page on VA disability vs. SSDI

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46305]
## Issue Description
Claudia from Social Security Administration asked us to add content to VA.gov explaining the difference between VA disability and Social Security disability. 

We couldn't find internal VA data related to frequency of Veterans asking this question, but semrush shows a search volume in the 200s for several related key phrases. 

We'll plan to draft a new R&S page in early Q4 to explain the difference between these 2 benefits (might be similar to this [R&S on pension vs disability](https://www.va.gov/resources/how-are-pension-benefits-and-disability-compensation-different/)). 

We'll base our content on this PDF from Claudia:[https://app.zenhub.com/files/133843125/9ef51976-f971-49b7-a10c-1828a9796584/download](https://app.zenhub.com/files/133843125/9ef51976-f971-49b7-a10c-1828a9796584/download)

---
## Tasks
- [ ] Draft R&S page 
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to Claudia for feedback (Laura)
- [ ] Update as needed
- [ ] Copyedit w/ prepub checklist (Megan)
- [ ] Publish (Megan)
- [ ] Notify Claudia page is live (Laura)

## Acceptance Criteria
- [ ] New R&S page is live

**Comment by laurwill** [comment]
Hey @katherine-fung , this is a non-urgent writing task that you can jump into whenever you have time. I have the background on this, so let me know whenever you'd like to chat!

**Comment by laurwill** [comment]
Hey @katherine-fung , nice work on this! Here's the word doc with the notes we talked about on zoom. I'll take another look after you update! And if it feels like it's getting long, we can turn the bolded "va disability" and "ssdi" intros into H2s — we can make this a detail page instead of a single Q&A to allow for more characters and formatting.
[ssdi vs va disability.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9823168/ssdi.vs.va.disability.docx)

**Comment by katherine-fung** [comment]
Hi @laurwill, 

posting this back for us to review over Zoom! 
[https://app.zenhub.com/files/133843125/2bf1014c-6667-453f-b9ca-df1c7e61694f/download](https://app.zenhub.com/files/133843125/2bf1014c-6667-453f-b9ca-df1c7e61694f/download)

**Comment by katherine-fung** [comment]
Hi @laurwill, 

posting this back for us to review over Zoom! 
[https://app.zenhub.com/files/133843125/2bf1014c-6667-453f-b9ca-df1c7e61694f/download](https://app.zenhub.com/files/133843125/2bf1014c-6667-453f-b9ca-df1c7e61694f/download)

**Comment by katherine-fung** [comment]
Hi @laurwill - I don't know if you've started reviewing this yet, but I was tweaking my note about VA disability and SSI and I realized I never defined SSI. 

Posting with a tweak: 

Note: VA disability payments don’t affect SSDI payments. But VA disability payments could affect eligibility and payments for another Social Security disability program called Supplemental Security Income (SSI). The SSI program counts VA disability payments as income. The higher your income, the lower the SSI payments you may qualify for. 

[https://app.zenhub.com/files/133843125/54e01fe4-0e61-4b0b-8b92-7fc734e81904/download](https://app.zenhub.com/files/133843125/54e01fe4-0e61-4b0b-8b92-7fc734e81904/download)

**Comment by katherine-fung** [comment]
Hi @laurwill - thanks for reviewing this page with me! I'm posting it back with an external CTA for SSDI: 

http://preview-prod.vfs.va.gov/preview?nodeId=51017

**Comment by laurwill** [comment]
Thanks so much @katherine-fung ! I made these final tweaks:
- Adjusted CTAs to be "learn more" about each benefit, and removed links for more info in the first 2 sections
- Adjusted intro to specify that if you have a service-connected disability that prevents you from working, you may be eligible for both benefits
- Adjusted income limit bullet in SSDI section to more closely match how SSA describes this limit
Let me know if you have questions about anything I changed!

@megzehn , this new R&S page is ready for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=51017

**Comment by megzehn** [comment]
Hi @laurwill! 

I reviewed this, and it looks good to me. I just made a minor tweak in the second paragraph. Let me know if you have any issues!

**Comment by laurwill** [comment]
Hey @megzehn , Beth suggested a slightly different structure for this page, so I made a few adjustments. Could you copyedit the updates? Sorry to send this to you twice! I think the easiest thing would be to compare revisions to make sure I didn't introduce any errors.

**Comment by megzehn** [comment]
Hi @laurwill, I reviewed the changes and they look good!

**Comment by laurwill** [comment]
Thanks Megan! I sent this to Claudia, our SSA contact, for an accuracy review. I'll update when we hear back — moving this to blocked for now.

**Comment by laurwill** [comment]
I followed up, no response yet, still blocked.

**Comment by laurwill** [comment]
Just kidding! Claudia (original contact at SSA) just responded — she's left that team, but copied in 2 new contacts Tim Grieb and Tameka Taylor to review the draft and get back to us.

**Comment by laurwill** [comment]
Very very belated update here: @bethpotts thanks for offering to pick up this work, I just forwarded you the response from SSA (which I meant to reply to and completely lost track of for far too long, my apologies). 

They suggested some changes and I had updated the [Drupal node](http://preview-prod.vfs.va.gov/preview?nodeId=51017) with edits for site style — mostly minor stuff, but this bullet is different enough that we might want an accuracy check? 

![Image](https://github.com/user-attachments/assets/a6e1d8a4-753c-47d5-8a00-22b81b648fce)

Let me know if you need anything else!
