### ISSUE TITLE
Publicize new announcements channel to encourage adoption

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46303]
## Issue Description
Publicize the new vfs-change-announcements channel

## Tasks
- [x] Publicize the updated offering to Platform PMs
- [x] Announce the new channel and its purpose in Slack (vfs-all-teams), encouraging adoption

## Acceptance Criteria
- [x] New channel is publicized through intended channels
