### ISSUE TITLE
Update language on headstones, markers, and medallions page to make eligibility requirements clearer

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46316]
## Issue Description
NCA stakeholders reached out to ask us to update a section of the [Veteran headstones, markers, and medallions](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/) page to make the eligibility requirements clearer.

In the 2 "Veterans and active-duty service members" accordions, they are asking to make "before" and "after" more distinct. They wanted these terms capitalized and underlined but are now aware that isn't in our style guide. We need to find another way to make this information clearer. 

Note that these changes need to be applied for both of the accordions with that same header.

While we are making changes to this page, we also need to fix an accessibility issue. Each of the accordions for the 2 different sections (headstone, grave marker, or niche marker and medallions) are labeled the same. We need to make these more distinct so that it isn't confusing with a screen reader.  

## Tasks
- [x] Adjust content for clearer understanding + update accordion labels (Laura/Katherine)
- [x] Review (Beth)
- [x] Copyedit (Randi)
- [x] Send to stakeholders for review (Laura)
- [x] Final copyedit (Megan)
- [x] Publish page (Megan)

## Acceptance Criteria
- [x] Language is adjusted
- [x] Accessibility issue fixed

**Comment by laurwill** [comment]
Hi @katherine-fung ,
Here's the word doc we were futzing in during standup with a suggested approach to the before/after headers.
[Headstone edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9479584/Headstone.edits.docx)

Could you update the Drupal node and see how it looks? 

Then we also need to adjust the duplicate accordion headers on this page — could you see if you can suggest a solution there?

**Comment by katherine-fung** [comment]
@laurwill, 

What do you think of adjusting the accordion headers like so?

H2: Eligibility for a headstone, grave marker, or niche marker

Review eligibility requirements for:

Accordion header: Veterans and active-duty service members **who qualify for a headstone or marker**
Accordion header: National Guard members and Reservists who qualify for a headstone or marker
Accordion header: Spouses and dependent children who qualify for a headstone or marker

**Comment by laurwill** [comment]
Thanks @katherine-fung! Goodness this is tricky. Just documenting here that I tried 2 alternatives and both introduced new problems so I walked them back:
- Combining the 2 sets of accordions into a single eligibility section and specifying headstone vs. medallion in the accordion labels 
- Making the service types regular H3s and using accordions for service dates under Veterans/service members

I think the current organization may be the best we can do at this time. For the accordion label additions, I'd like to avoid introducing "qualify" since rest of page uses "eligible." I tried adding just "(for a headstone or marker)" or "(for a medallion)" — see what you think of that approach. We can also pull this up in standup today and see if there's a better solution!

**Comment by laurwill** [comment]
@RLHecht , this is ready for copyedit!

http://preview-prod.vfs.va.gov/preview?nodeId=859

And collecting notes for delivery:
- We found that it was challenging to highlight the "before" and "after" elements in those headers using the current structure. We also needed to update the accordion headers so that we wouldn't have identical accordions on the page, which can be confusing for screen readers. So we made some larger changed to the page structure — combined the headstone and medallion eligibility sections, and reorganized the information in the 2 accordion sections for Veterans and service members. 
- On the live page under Veterans and service members for medallions, there's a note that says "Any service member who died while serving on active duty is eligible, regardless of when they served." This seems to contradict the rest of the information in this section, which says service members need to meet requirements by service date. Can you confirm which is correct? We've left this note out of the updated page for now, but we can adjust as needed.

**Comment by RLHecht** [comment]
@laurwill I copyedited and this is now ready for you to send back to stakeholders!

**Comment by laurwill** [comment]
Thanks @RLHecht ! Confirming that I sent this to Eric at NCA.

**Comment by laurwill** [comment]
Update: Eric approved our changes! But he let us know that the note about service members being eligible regardless of when they served is correct for the medallions section, so we'll need to update. I adjusted in Drupal, but also asked him whether that note also applies to headstones. I'll update again when we hear back.

**Comment by laurwill** [comment]
Eric confirmed that service members don't need to meet requirements specific to when they served for either headstones or medallions — I adjusted in Drupal and sent back to Eric for a final accuracy review.

**Comment by laurwill** [comment]
Eric hasn't flagged any more accuracy concerns here, so I think we can move ahead with a final copyedit, @megzehn !

**Comment by megzehn** [comment]
Update: This has been reviewed! Holding until we get the green light to publish.

**Comment by laurwill** [comment]
Hey @megzehn ! We got the green light from stakeholders — you can publish this one whenever you have a moment!

**Comment by megzehn** [comment]
Thanks @laurwill! Confirming that this is now published. 

CC @RLHecht

**Comment by laurwill** [comment]
Thank you! I let the stakeholder know. @RLHecht we can close this one out!

**Comment by RLHecht** [comment]
Thanks all! Closing

**Comment by RLHecht** [comment]
Noting that after we published a stakeholder reached out about the medallions accordion. We reworked the bullets to make the requirements clearer, got their approval and published the page.
