### ISSUE TITLE
Updates on main COVID-19 vaccine page for Novavax approval for age 12 and older

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46319]
## Issue Description
We made changes to the main [COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/) page to reflect that Novavax is approved for ages 12 and over.

We need to copyedit these changes and publish once approved as well as get the new content translated in both Spanish and Tagalog.

## Tasks
- [x] Update English page with new content (Danielle)
- [x] Copyedit (Megan)
- [x] Publish changes (Megan)
- [x] Send text to translators and open translation ticket (Randi)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by RLHecht** [comment]
These changes are live. Going to close and we can track the translations in a separate ticket.
