### ISSUE TITLE
Design | Profile | Account Security | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46315]
## Background

We need to audit, update and/or create design documentation for the Account Security section of the Profile located [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security). Good examples can be found within Direct deposit or Contact info features which have recently been updated.

## Tasks
- [x] Update and/or create use cases for this feature
- [x] Create user flows
- [x] Create/update screen mocks and text

## Acceptance Criteria
- [x] Post to appropriate sections of GitHub and sketch
- [x] Check that links from product outline are up to date

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow [Account security documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security) - This is all updated save a couple questions around our "Not in MPI" alert. There are a few discrepancies with the alerts that are in our designs vs. staging. 

I think Liz may have done some recent work on this, so waiting to make these last changes until I can sync with her and confirm if these updates are need in the documentation/mockups or in staging.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss @SKasimow! So Liz did not work on this previously and neither the designs nor staging versions completely follow the pattern. I'll need to check with Danielle to confirm what the content should be and then can update that alert accordingly in our Sketch file and user flow.

**Comment by cgednalske** [comment]
A couple notes:

- We have a [separate ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47350) open to work on these updates to Account security alerts.
- I've synced with Danielle on this and went to her office hours this morning. The content is more complicated than she had hoped, so I'll be opening a new content ticket for her to delve into this further.

**Comment by cgednalske** [comment]
@SKasimow because we have the other ticket open and will soon have a content ticket open as well, I think we can close this.

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow - could you take a look when you have a chance and make sure the documentation is all set (other than the alert updates coming up)? Thanks!

**Comment by Samara-Strauss** [comment]
Hey @cgednalske -- I'm so sorry I haven't had a chance to look at this. It's on my radar for tomorrow.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss - thanks so much for this thorough feedback! Some responses to your questions/edits below:

> ### Account security: User needs to complete tasks
> 
> I believe users can do these things even if they are LOA1. Can you validate this? This would change how we categorize this page.

Ah, interesting! I didn't realize that might be the case. Will do 👍 

> > The link will bring the user to the website where they manage their account (either Login.gov,DS Logon, MyHealtheVet, or ID.me).
> 
> Can you check in with Liz about this? I think we changed how this works slightly since DSLogon and MHV don't actually require a user to add an email address.

Liz and I talked through this earlier and she said this should be correct - with the language now saying "manage your account" rather than an action related to updating the user's email, but I will double check with her to make sure 👍 

>**Images** 
> - For the 2FA images, you show what it looks like when the task is complete, but not what the prompt to add 2FA looks like. Can you add that?
> - For 2FA mobile images, this links to a bunch of desktop mockups.
> - For Terms and conditions, you show what it looks like when the task is complete, but not what the prompt to review terms and conditions looks like. Can you add that?

Absolutely can add what you've mentioned above, I might write up a ticket to keep track of these updates as I think our files might missing quite a few things when we factor in the alerts + the LOA3 screen for when tasks aren't complete that you mention below.

Mobile link has been updated ✅  - thanks for catching that!

> ### Something has gone wrong and VA.gov can’t match user information with our records
> 
> This links directly to a Sketch file and not a page. Can you add a short page for this? Actually, is this supposed to link to [Account security: VA.gov can’t access records](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/system-cant-access-records.md)? If not, that's OK, it's just not clear to me if this page is supposed to cover the "something went wrong" use case as well.

This is where there are still questions for the alerts. This one in particular - the "not in MPI alert" significant content discrepancies between design and staging. For now I've not added the use case yet as we work through this with Danielle. And then there's a different alert - "can't access system/MPI connection error" - that I found in staging, but not in the designs. This one looks to be clear and up-to-date but was missing in the design, so the use case is already included. 

[This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47350) goes more in to detail about this, and I'll add some questions for you over there. 

> ### High-level flow with screenshots
> 
> This is missing screenshots of what it looks like for LOA3 if tasks aren't complete (noting that verifying identity will obviously always be complete for LOA3).

Will add that as well along with those you've mentioned above.

> ### General feedback
> 
> Since we have a page on what it looks like if people need complete tasks, I think we should also have a page on what it looks like if all tasks are already completed. Or, we should clarify the title of the "needs to complete tasks" page to clearly cover both use cases, as it's not clear from looking at the list that you'll see the "completed" version of the page within the "needs to complete tasks" page. Let me know if you have questions/thoughts about that.

I'm not sure I'm following this one. Are you saying that in addition to having a "needs to complete tasks" use case, it'd be helpful to have a "tasks completed" use case as well? **OR** that we could change the name of the "needs to complete tasks" use case to something like "view and complete tasks" - to demonstrate that tasks _will_ be completed within the same use case? Did I get that right?

**Comment by Samara-Strauss** [comment]
> Liz and I talked through this earlier and she said this should be correct - with the language now saying "manage your account" rather than an action related to updating the user's email, but I will double check with her to make sure 👍

OK, thank you for confirming!

> Absolutely can add what you've mentioned above, I might write up a ticket to keep track of these updates as I think our files might missing quite a few things when we factor in the alerts + the LOA3 screen for when tasks aren't complete that you mention below.

Sounds good! Thanks!

> This is where there are still questions for the alerts....

OK, thank you for clarifying this. I'll look for your questions in the other ticket.

> I'm not sure I'm following this one. Are you saying that in addition to having a "needs to complete tasks" use case, it'd be helpful to have a "tasks completed" use case as well? OR that we could change the name of the "needs to complete tasks" use case to something like "view and complete tasks" - to demonstrate that tasks will be completed within the same use case? Did I get that right?

Sorry I wasn't clear initially! You are correct -- I am saying that we should **either** have a "tasks completed" use case as well **OR** change the name of the "needs to complete tasks" use case to something like "view and complete tasks". I'll leave the final solution up to you.

**Comment by SKasimow** [comment]
Hola! Sorry I didn't have a chance to look at this sooner. 

It looks like the T+C's are conditional for LOA3 users. If that's true, can we note under what conditions they appear/don't appear?

**Comment by cgednalske** [comment]
@Samara-Strauss ok, great - thanks for the additional details! 

@SKasimow going to double check some of this with Adam, but I believe T+C always appears for LOA3 users but not for LOA1 - though everything else appears for LOA1. Other than updates I've just made to the [user flow](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/C518EEE8-2115-4CE4-B50A-5DD7E8410A18/canvas), is there anywhere else you were thinking to note these conditions?

**Comment by SKasimow** [comment]
@cgednalske - I think it would be good to add a line or two into the Product Outline/Overview section. I can do that once Adam confirms behavior.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss -- Except for the ongoing work on the alerts, everything else you mentioned above should be updated now:

- For LOA1, I've confirmed with Adam that users can complete 2-factor authentication and view follow the sign-in information, but they cannot view terms and conditions. This is reflected in the Sketch files, user flow, and now a new [use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/complete-tasks-loa1.md).
- For LOA3, Adam found that whether or not terms and conditions shows depends on a few factors including if the user is LOA3 and if they have a MHV account. This has been reflected in the [main use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/complete-tasks-loa3.md).
- I confirmed with Liz that the current language for the sign in information is accurate. 
- Questions around alerts and related use cases continued in the other [Account security alert ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47350#issuecomment-1258618897). 
- [High-level flow](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/C518EEE8-2115-4CE4-B50A-5DD7E8410A18/canvas) - the screens you mentioned above have been added or updated. They should all be accounted for now.
- General feedback - Regarding the main use case for LOA3, I've gone with the second solution: combining the two use cases and changing the name to reflect both - "[user views and completes tasks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/complete-tasks-loa3.md)." Let me know if this works!

Think that's it!

@SKasimow -- I created the additional use case for LOA1 to emphasize that terms and conditions are not included (bullet point #1 above), but you can definitely go ahead and add that where you mentioned as well if it will be helpful.

**Comment by SKasimow** [comment]
Thanks - will review tomo

**Comment by Samara-Strauss** [comment]
All of this sounds good and looks great! Thanks, @cgednalske!!

**Comment by SKasimow** [comment]
Hi @cgednalske - this looks good; nice job!  I think you have the T+C's covered well within the use cases. Any objection if I add this to the "Problem Statement" section:

> Agree to terms and conditions for medical information

Also, thought it would be helpful to provide a link to the Identity product outline  for more information and background - so I've added a link :)

**Comment by cgednalske** [comment]
Awesome, thank you both for reviewing! 

@SKasimow no objection at all - go right ahead 👍

**Comment by SKasimow** [comment]
Thanks - will close this out now.
