### ISSUE TITLE
Look into facility locator issue for home loan services

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#46325]
## Issue Description
In this [ticket related to removing eBenefits links](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45341#issuecomment-1220908708), Aliyah discovered an issue with the facility locator.

We need to look into:
- Whether the locator tool is offering enough/the correct locations for home loan services
- Whether Veterans can hand in applications for Specially Adapted Housing Grants and other home loan-related documents at any regional center, or only a center that's tagged for home loan services

Then we'll decide whether to add the in person submission option back to the Specially Adapted Housing Grant page. 
---
## Tasks
- [ ] Continue looking into issue with facility locator (Aliyah)
- [ ] Reach out to stakeholder with Qs (Randi/Laura)
- [ ] Update SAH pages if needed (Aliyah)
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] SAH page is live with in-person option, or we've decided not to add it back
