### ISSUE TITLE
FE | Profile | BAI | Update GA to use Custom Event

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46320]
## Background

We want to use a custom event for the BAI messaging alerts in order to have more control over tracking and the reporting view.

We meed to be able to track the following:

- count of BAI alerts viewed on personal info page
- count of link clicks from alert on personal info page
- count of BAI alerts viewed on contact info page
~- count of link clicks from contact info page~

## Tasks
- [x] Set up custom event as follows: 
- Event Category: Interaction
- Event Action: Status: {{BAI Views} - Title: {{Personal Info}}- Click Text: {{None}}
- Event Action: Status: {{BAI Link Click} - Title: {{Personal Info}} - Click Text: {{Go to your Contact Information to review your address}}
- Event Action: Status: {{BAI Views} - Title: {{Contact Info}}- Click Text: {{None}}
~- Event Action: Status: {{BAI Link Click} - Title: {{Contact Info}} - Click Text: {{Review and update your mailing address}}~
- Event Label: profile_modal 

## Acceptance Criteria
- [x] Confirm event is firing correctly in staging
- [ ] Test with PM behind FF in production
- [ ] Add to Contact Info Product outline [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#analytics)

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@adamwhitlock1 - will we still capture the number of views for the sole alert that will be on Contact info page?
Also, I'll update the ticket to cross-out what is no longer applicable.

**Comment by adamwhitlock1** [comment]
I've been able to validate in staging through data slayer for these events. @SKasimow I think this should be good to close out if it is showing up in your widgets.

![Screen Shot 2022-09-20 at 12.57.26 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/0c2a71fb-0d4f-4f41-9f40-534e9e7110da)

![Screen Shot 2022-09-20 at 12.57.04 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/4308565f-10f1-4fc6-817b-761806ecced8)

![Screen Shot 2022-09-20 at 12.56.49 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/d9512ef6-f5f9-401e-bf07-902c04bb2b5b)

I'm still having a hard time logging into prod today due to the vets-api latency issues, but the same events should happen on prod when a user with the feature toggle visits the relevant pages.

**Comment by SKasimow** [comment]
I set up the widget and pointed to staging environment. Think everything is in order; this is what I am seeing:
![Screen Shot 2022-09-20 at 6 54 04 PM](https://user-images.githubusercontent.com/74627978/191378974-a4efc941-45d2-495f-988b-a6ff06ea0084.png)
