### ISSUE TITLE
Spanish translation work for Novavax being approved for ages 12 and over

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46322]
## Issue Description
We recently made updates to the main COVID-19 page that the Novavax vaccines is approved for children 12 and over. We need to get this new content translated in both Spanish and Tagalog. 

This ticket is to track the Spanish pages. 

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Spanish page (Aliyah)
- [x] Copyedit Spanish page (Randi)
- [x] Publish Spanish page (Randi)

## Acceptance Criteria
- [x] New content is live on Spanish page

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the translated content:

[https://app.zenhub.com/files/133843125/56bcfcec-10e6-4ca2-a2b3-99ca7d23c25f/download](https://app.zenhub.com/files/133843125/56bcfcec-10e6-4ca2-a2b3-99ca7d23c25f/download)

**Comment by aliyahblackmore** [comment]
Thanks, Randi! 

Hi @megzehn this is ready for you! Just noting here that for the time being we are **only** making changes to what was highlighted in the translation document, though there are some instances of other content being translated that we didn't request.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
I copyedited this and published. Moving to validate!

**Comment by RLHecht** [comment]
Closing as this is live
