### ISSUE TITLE
Certificate of Eligibility | Feature Toggle

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#46328]
## Value Statement
**_As a_** developer
**_I want to_** add a feature toggle to the Certificate of Eligibility
**_So that_** I can incrementally release the form to our user base.

---
## Background Context
There is a toggle, but it's only being used for the static page React widget (the action link that gets injected into the static page). We need to change the code so that the introduction page doesn't do anything if that feature flag is turned off.

## Tasks
- [ ] Show COE apps (form & status) when `coe_access` feature is enabled
- [ ] Ensure React widget (injected into the static page) also renders when feature is enabled 
- [ ] Add unit tests

## Acceptance Criteria
- [ ] All tasks complete 
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@saderagsdale @Mottie update with AC and tech tasks.
