### ISSUE TITLE
FE Testing for VerifyApp

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#46331]
## Issue Description
Create a robust unit test suite for VerifyApp and components within.  

## Tasks
- [ ] VerifyApp renders properly
- [ ] VerifyApp appropriately renders loading indicator
- [ ] VerifyApp displays correct verification buttons for logged in users
- [ ] VerifyApp redirects accordingly
- [ ] VerifyButton renders with correct policy
- [ ] VerifyButton updates state properly

## Acceptance Criteria
- [ ] Unit test suite created for VerifyApp and components within.
