### ISSUE TITLE
Cut over traffic to EKS for staging

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#46337]
## Description
Since the dev, staging and prod vets-api deployments (server and sidekiq) are now running in EKS, we should now point the traffic to EKS.

## Tasks
- [ ] Point traffic to EKS for staging
- [ ] Point traffic to EKS for production using conditional header like we do in dev

## Acceptance Criteria
- [ ] Staging traffic is being directed to EKS deployment

**Comment by laineymajor** [comment]
@laineymajor move to new epic (TT1)

**Comment by laineymajor** [comment]
migration complete
