### ISSUE TITLE
Notice of Disagreement | pt. 2 error messaging for when PDF files are rejected due to page dimension

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#46330]
## Value Statement
**_As a_** Veteran
**_Given that_** my Notice of Disagreement submission has failed to attach the evidence I selected
**_I want to_** understand how to submit evidence separately
**_So that_** I can share evidence before my 90-day deadline.

---
## Background Context
This is a follow-up to work initially done in #43037. The scope of this problem is to provide guidance (via error messaging) to claimants in scenarios when they successfully submit a NoD, but the attached evidence fails to upload. 

## Acceptance Criteria
- [ ] _Claimants know how to submit evidence when it fails to upload with their NoD._

## Open questions
- Add here

## Tasks
- [ ] _Discuss with Paul Schute (should we recommend QuickSubmit to claimants?). _

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
