### ISSUE TITLE
Implement HPA for vets-api Puma (all 4 environments)

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#46336]
## Description

HPA (Horizontal Pod Autoscaling) should be improved for the k8s vets-api-serveer deployment. We want to scale based on puma backlog and not basic metrics such as CPU. The infra team is discussing, enabling scaling based on any exposed metric [KEDA as seen here](https://medium.com/swlh/scaling-sidekiq-workers-on-kubernetes-with-keda-6515c4ca8df4).

### Notes
- The KEDA operator will create a custom control loop that will allow for scaling to the desired state based on custom metrics. The basic K8s resources cannot be used because of the custom scaling business logic. The KEDA operator will make use of a CRD, the ScaledObject to create a HPA and scale based on Puma queue size (the custom business logic).

We can most likely pull Datadog metrics for the Puma backlog to scale based on [the Datadog trigger.](https://keda.sh/docs/2.8/scalers/datadog/)

## Tasks
- [x] Investigate Keda
- [ ] Implement Puma Backlog Scaling using KEDA
- [ ] Remove the existing HPA used by Puma

## Acceptance Criteria
- [ ] vets-api-server can scale based on puma backlog

**Comment by LindseySaari** [comment]
It appears that we can use[ Datadog metrics](https://www.datadoghq.com/blog/autoscale-kubernetes-datadog/#add-a-datadogmetric-resource-to-your-hpa) CRD's to scale on custom metrics
