### ISSUE TITLE
Explore a GHA workflow to vet new/changed Cypress tests for flakiness

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#46338]
## Issue Description
In order to prevent flaky tests from interfering with the Continuous Integration workflow, we need to research techniques for automatically detecting, flagging, and quarantining flaky e2e tests.

---
## Tasks
- [x] Consider a 100 execution loop to verify there is no flakiness present in new tests
- [x] Consider tracking a "flaky" flag that either quarantines flaky tests or explicitly allows non-flaky tests (or both?)
- [x] Consider a dispatched workflow that runs after CI
- [x] Consider an on-demand workflow with parameters to take a specific test spec or branch and detect flakiness through repeated execution
- [x] Consider using these approaches to test flakiness in the test suite outside of CI
- [x] Consider ways to improve flakiness detection to cover all cases of flakiness in the E2E test suite
- [x] Consider ways to automatically disable a test if failures exist
  - [x] Consider ways to generate an action item/ticket that notifies a VFS team based on disabled tests

## Acceptance Criteria
- [x] Document findings and offer suggested implementation for detecting and isolating flaky tests before they are integrated into `vets-website` is detailed in this ticket or in a document linked in this document

**Comment by JoeTice** [comment]
Want to timebox this to 2-3 days

**Comment by CBonade** [comment]
Things we tried to get this concept working:

- Run a loop on the step in GHA: This is not possible in GHA
- Duplicate the list of specs that Cypress is fed the number of times we need it: Turns out, Cypress has built-in de-duping so if the spec already ran, it will not run again.
- Config option to repeat tests: There is no Cypress config option to repeat tests irregardless of status, only on failure.
- Prescribed method of repeating: This seems to be putting a loop right in each spec file, which does not seem efficient for this method.

What did end up working though, is putting the loop inside the script file around the command to invoke cypress. This will only run each spec once per invocation, but will invoke Cypress as many times as the loop is set for. In our initial test of this we set it to 5 and while one partial of Cypress timed out due to our github actions timeout being set to only 40 minutes, we did get a nice set of results that are grouped together in one mochawesome report. The timeout can be adjusted up to 24 hours at a maximum (due to token expiration), so this can be adjusted to allow more runs.

Our current planned approach looks like the following:

- Run this scan once a week
- Any tests that fail at all will be considered flaky. These should be flagged in a list of test specs with a boolean value of true or false for current flakiness
- Using this flakiness flag, we need to find a way to disable or skip these tests in test selection - likely solution is a disallow list that gets checked every time test selection runs.
- Tests can be removed from the disallow list if their test is fixed before the next time this scan runs
- YAML forms can be used to run workflows with conditional values. We can add a manual trigger for the workflow based on a yaml form where a test spec can be submitted at any time to be tested for flakiness and reenabled if passed

**Comment by pjhill** [comment]
Outstanding questions --
1. How do we notify teams that a test has been moved to the disallow list?
2. How do we deal with orphaned products?
3. How do teams re-examine their disallowed tests?

**Comment by pjhill** [comment]
Tasks for research have been completed -- please update the POC ticket with the plan you've described here and what changes are made as you start to write code.
