### ISSUE TITLE
Disable BRD jenkins deploy job

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#46335]
## Description
Currently, the vets-api server and worker instances for BRD are deployed to dev and staging on every merge to master. We should disable this behavior in favor of the containers running in EKS. 

## Tasks
- [ ] Disable Jenkins deploy job for dev
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/46337
- [ ] Disable Jenkins deploy job for staging

## Acceptance Criteria
- [ ] Vets API traffic and jobs are solely processed by EKS
- [ ] Dev/Staging BRD instances are no longer running/deployed

**Comment by laineymajor** [comment]
Need to double-check that this has been completed for dev.
Need to add this step/ticket for the other environments.

**Comment by laineymajor** [comment]
Closing. This is duplicative of another ticket created by TT1.
