### ISSUE TITLE
Update Support bot to better reflect Cypress/E2E resources

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#46340]
## Issue Description
Given the new resources we have available for troubleshooting Cypress issues in CI and addressing flakiness, let's update the support bot keywords and articles to route incoming support requests to the correct documentation on Platform website.

---
## Tasks
- [x] Update the support bot to detect additional keywords
- [x] Update the support bot to direct those keywords to more specific documents than the general documents we currently link to

## Acceptance Criteria
- [x] Support bot detects keywords about Cypress / end-to-end related topics and links the submitter to the most specific document available

**Comment by rsmithadhoc** [comment]
This is ready for review:

- I updated the [support bot spreadsheet](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535) with links to guides.
- I got a preliminary look at it from Kerry on SRE. One thing I wanted to do was if they selected a team and topic, output a result regardless of the text. Example: QA Standards, Test Failure, "it's broken, can you help?" doesn't match any keywords but would output Cypress troubleshooting. Unfortunately, that isn't possible with the current logic and would show up for anyone selecting "Test Failure", regardless of team. Kerry said it would be a good addition and would make a ticket for it. For now, I have those saved on a [separate spreadsheet](https://docs.google.com/spreadsheets/d/1zEeLlfy9oopWWbywHVyysGNg2BaFOWP1OEfGxQx3ADs/edit#gid=0) so we can add that when that logic is in place.
- I did a couple of tests in Slack
  - https://dsva.slack.com/archives/CBU0KDSB1/p1662573790689709
  - https://dsva.slack.com/archives/CBU0KDSB1/p1662573976127539

**Comment by pjhill** [comment]
This is great! Thanks for adding these so thoughtfully. That sounds like a helpful feature request with SRE team as well.
