### ISSUE TITLE
BE | Profile | Create + Document Error Codes

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46343]
## Background

Currently we have some info on error codes and error messaging sprinkled throughout our GitHub Profile section but would like to build a repository that houses this information across the product portfolio and includes error codes, messaging, end-points screenshots and the like. This is information will be helpful to everyone on the team and improve our ability to quickly identify and rectify issues.

As a first step we plan to compile info available through the back-end.

## Tasks
- [x] Create a table that shows the following information for each section of the Profile section
     - End-points called
     - Error codes returned
     - Description of error code

## Acceptance Criteria
- [x] Create in a shareable file (ie Google docs)
- [x] Let PM know when completed and ready for review with FE

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by tpharrison** [comment]
@SKasimow @adamwhitlock1 

I've shared the [google doc](https://docs.google.com/document/d/1WbqcNVq32XTb3D0WiYStCiBDSFQYoLQeJm0yV2kjt0o/edit?usp=sharing) with both of you.  Please review when you get a chance and provide feedback.  I'll convert it to a MD file and add it to a repo after you've had a chance to review. Thanks!
