### ISSUE TITLE
Update VFS-facing documentation to include how to guides

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#46341]
## Issue Description
We need to ensure that 'how-to' guides targeting VFS teams as the audience are available on the Platform Website to address common issues with Cypress / E2E testing on the platform. For example,
* Developing an e2e test spec locally
* Removing flakiness from an e2e test spec
* Addressing a failing e2e test spec in `main`
* Addressing a failing e2e test spec in your branch

---
## Tasks
- [x] Refer to Content Team's guidance/best practices documentation to inform our approach to documentation - follow up with conversations as needed
- [x] Verify that how-to documents are available for common issues with Cypress
- [x] Verify that the documents are well-named and collected into a common area on the platform website
- [x] If a document is not available for a specific topic then we need to create that document and publish it

## Acceptance Criteria
- [ ] A collection of 'how-to' documents for common e2e / Cypress issues is available on the Platform website for VFS teams to use

**Comment by rsmithadhoc** [comment]
In reading through our documentation, I believe everything is organized and well covered. It also follows the [Platform website guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) as far as I can see. Searching "Cypress" on the Platform Website comes up with relevant results and they can easily navigate to other pages in the side bar. I may make some small updates to make things clearer, but the bulk of the information is there. We have an issue to better show more targeted guides with the support bot auto responses, which should help in discovering these as well.

We have guides for the specific things mentioned in the issue:

- Developing an e2e test spec locally
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-an-end-to-end-test
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/best-practices-for-using-cypress
- Removing flakiness from an e2e test spec
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/flaky-test-management-in-cypress
- Addressing a failing e2e test spec in main/Addressing a failing e2e test spec in your branch
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-troubleshoot-a-cypress-failure
        - I think this one might need an update specifically for tests passing in a branch then failing on main, it may need to wait until https://app.zenhub.com/workspaces/quality-assurance-standards-613a3f47e06ba00013d05eed/issues/department-of-veterans-affairs/va.gov-team/41647 since that is meant to research this issue.

To Do:

- Small clarity updates.
- Update for test failing in branch vs. main once that research has been done.

**Comment by rsmithadhoc** [comment]
This is ready for review.
- Updated [How to troubleshoot a Cypress failure](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2273771547/How+to+troubleshoot+a+Cypress+failure) with a section for tests failing in a branch vs. main and getting that branch up to date with main.
- List of guides updated, mostly minor updates to wording/formatting. I feel we had everything covered/organized that we wanted to. With updates to support bot responses, hopefully these will be more visible.
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/2273771547/How+to+troubleshoot+a+Cypress+failure
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/1870430218/Flaky+test+management+in+Cypress
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/1868431439/Writing+an+end-to-end+test
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/1870430211/Best+practices+for+using+Cypress

**Comment by pjhill** [comment]
Thanks for updating the usual suspects. We should be able to route most support requests through these documents going forward!
