### ISSUE TITLE
[FE] Configure PagerDuty to Automatically Trigger the Downtime Component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46354]
## User Story
As a Veteran, when Pre-Check-in or Check-in are not available for me to use because of a system problem or outage, I want to know so that I don't waste my time trying to use the applications.

## Tasks
- [ ] [FE] Configure PagerDuty to react to when vets-api, chip-api, or lorota-api are not available
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
