### ISSUE TITLE
Profile Team | Sprint 83 | Sept 21 - Oct 4 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46358]
## PTO/OOO/Unavailable

- **Adam**: 
- **Christina**:   10/3 - 6
- **Sharon**:  
- **Tom**:  Oct 3 - 4
- **Samara**: 
- **Liz**:  Oct 3 - 4
- **Erica**: Oct 3 - 7
- **John**:

(Ad Hoc Team meetings 10/3 - 10/4)

---
#### For 9/28 Backlog Grooming meeting:
- Groom #46195 (Aria Label)
- Groom [#43481](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/43481) DD Fraud Alerts
- Balance of Accessibility tickets - #46756

## Sprint Priorities

- Complete UAT and start phased roll-out for BAI
- Finish our product documentation (in the home stretch!)
- Accessibility improvements
---
#### Design - Christina
- [x] #46700 Conduct UAT* (3 pts)

#### PM - Sharon
- [x] #45099 Notification Settings (just need to review use cases)

#### Design - Christina
- [x] #46918 Documentation for Connected Apps (2 pts)
- [ ] #47350 Update MPI error alerts (2 pts)

#### FE - Adam
- [x]  #46282 Documentation for DD (2 pts)
- [x] #46323 Documentation for Military Info (1 pt) - moved to sprint 84
- [x] #46324 Documentation for Notification Settings (2 pts)

#### BE - Tom
- [x] #47040 Documentation for Notification Settings

#### Design - Liz
- [x] #47136 Research Plan
- [x] #47378 Conduct research for "One thing per page"
- [ ] #47381 Complete Synthesis & Deliver Final Report

#### FE - Adam
- [ ] #47003 New modal (related to #46614) (2 pts)

###  Error Matrix

TBD
#### BE - Tom
- [ ] #40762 Remove eMIS code (2 pts)
- [ ] #46744 Add "Service Academy" dates (3 pts)

#### FE - Adam
- [ ] #31403 Update alert for identity verification (2 pts)

#### BE - Tom
- [x] #46822 Update VFS Directory (1 pt)
- [ ] #47331 Doc for moving Github files (2 pts)
- [x] #47332 Move error doc to repo (1 pt)

#### FE - John
- [x] #46278 Update Gender FAQs (1 pt)
- [x] #30051 Update direct deposit edit button style (1 pt)

**Comment by SKasimow** [comment]
Hey @jcatergovy I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by SKasimow** [comment]
All open/unchecked tickets have been moved to Sprint 84...closing
