### ISSUE TITLE
Performance Dashboard Tech Debt

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46368]
## Issue Description
_The Performance Dashboard was built by a spike team several years ago and has not been properly maintained. While still mostly functional, it does have occasional issues which will like become worse due tech debt which has not been addressed. We are now the primary owners of this dashboard and need to address some of the high priority tech debt in order to ensure it is usable._

---
## Tasks
- [ ] _fill in tasks here_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
No imminent breaking tech debt. Deprioritizing and moving to icebox.

**Comment by ATMiddleton** [comment]
Another team has assumed responsibility for the Performance Dashboard
