### ISSUE TITLE
Support User Journey Map - Research Readout 

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#46366]
## Issue Description
_To better understand the support user journey, we need to synthesize research from interviews and finalize the research readout with recommendations_

---
## Tasks
- [x] Completion of research readout in PDF form
- [x] Readout has listed findings and recommendation/next steps for Support User Journey Map

## Acceptance Criteria
- [x] _Research Readout completed and reviewed internally_
- [x] _Upload to repo_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
@starlow00 @ianMcCullough-ob
Can either review the readout here (please comment, and ask any needed clarifying questions)
https://docs.google.com/presentation/d/163mLnusetiv2dLGKdqaQMg1giqFDBi6nUMfNrVp1UUo/edit#slide=id.g15a3ec28c1f_0_8


cc: @clantosswett @Kimberley2019 @jwoodman5

**Comment by starlow00** [comment]
@manalo-soco This looks good, Mike. I have 2-3 comments on the file that relate to images. The edit went well. Excited to see this continue!

**Comment by manalo-soco** [comment]
Uploaded readout to repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/research/Q2-2022/VA_Caller
