### ISSUE TITLE
Analytics Implementation or QA Support for Facilities Team - QR Code tracking

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-team#46365]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

## Description

A few VAMC facilities are testing a QR code, that would allow Law Enforcement agents to quickly access local phone number/resources.  It was reported that Law Enforcement can easily misplace or lose paper resources. The request to analytics is:

What tags need to be embedded/appended into a URL that includes an anchor link `(like this https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an` ) so we can clearly track the number of people who arrived via the QR code.

From [Slack convo](https://dsva.slack.com/archives/CBU0KDSB1/p1661561988393779)

> I'm asking from the point of view of a new URL.  If we plan ahead, how can we encode the proper analytics tags into a URL to specifically track it in the future?  I don't know how overall campaigns are managed now, but I can imagine that this might lay the foundation for future QR codes? So we can think beyond this specific example for how this might apply in the general sense.  Just guessing but I'm sorta proposing something like:
> ?campaignType=QRCode&campaignLabel=LawEnforcement

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Sitewide Facilities]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an]
    
- **When is the launch date?**
    - [TBD]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_

Not sure how to best describe this - we want to clearly track arrivals to a specific anchor link, which can't be tracked right now.  What can be encoded in the URL to surface arrivals on the anchor link in GA? 
    

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jonathan-epstein13** [comment]
Hello @dsinla. The taxonomy for tracking for the QR code (URL in the future) will include the 
`?campaignType=QRCode&campaignLabel=LawEnforcement `as a baseline. I am right now trying to see how we generally track campaigns and will attach the taxonomy for this type of tracking. 

The taxonomy will need to be implemented on the FE of your team, and then we can QA it  and makes sure it is tracking, once the QR code (URL) is live/staging. Let us know if you have any questions.

cc:  @michelle-dooley

**Comment by dsinla** [comment]
Thanks @jonathan-epstein13  and @michelle-dooley 
Regarding timeline, when do you think you will have the recommended syntax? 
I'm not sure what you mean by 'implemented by the FE of your team" - from my understanding we will create the URL in the syntax that you specify - that gets encoded into a QR code.  Other than that, is there any other engineering that will need to happen to properly track arrivals from the QR code to an anchor-link URL like  `https://www.va.gov/wilmington-health-care/contact-us/#support-for-law-enforcement-an`  Thanks!

**Comment by michelle-dooley** [comment]
@dsinla - Unfortunately Jonathan is no longer on the team so I am taking this over.  Let me dig into this a bit and get back to you.

**Comment by dsinla** [comment]
@michelle-dooley  Sorry to hear that. Thanks for jumping on this.
To summarize, we want to provide to VAMCs in the field a syntax for tracking direct arrivals from the use of a QR code. What GA tags do we encode in the URL to easily surface in the Analytics 360 console? 
I'm not sure of the convention, but I would imagine there would be two values along the lines of `CampaignLabel = VAMCQRCode `(so we can grab all values for this particular QR code campaign across all locations), and `LocationID = GreaterLA `so we can get stats for a particular location.  The LocationID would be equivalent to the final value in this URL:

`www.va.gov/greater-los-angeles-health-care/locations/antelope-valley-va-clinic/`

Or said a different way, we'd like to 
1. Easily get stats for all locations for this QR Code campaign
2. Grab stats for individual locations we specify 

Also we'd want to provide regular reports to VAMC Leadership to track this data.

Happy to talk more when you've familiarized yourself with the issue.

**Comment by michelle-dooley** [comment]
@dsinla - so you can use the [Campaign URL Buidler](https://ga-dev-tools.web.app/campaign-url-builder/) to create the url with the embedded campaign parameters.  Once these are created we can track via Campaign reports in GA.  

utm_source=qrcode
utm_medium=referral
utm_campaign=vamc_qrcode

Once you create the url send to me and I will test it.

**Comment by dsinla** [comment]
Taking a question to Office Hours 

https://www.va.gov/greater-los-angeles-health-care/locations/west-los-angeles-va-medical-center/
https://www.va.gov/**system**/locations/**facility**/
https://www.va.gov/*/locations/*/

**Comment by michelle-dooley** [comment]
@dsinla - thanks for meeting and notes above.  I will continue to look into this but at first glance I do the utm_campaign parameters coming through with the page url in GA so that is start... https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/explorer-table.filter=utm_campaign&explorer-table.plotKeys=%5B%5D

**Comment by dsinla** [comment]
Thanks @michelle-dooley , that seems promising. If I understand your search, you're really just searching for the string "utm_campaign" in the URL.  You're not executing any report specific to a campaign?  Thanks for continuing to explore.

I have updated the [Problem Statement ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46365#issuecomment-1278085073) above and, hopefully, expressed the request more clearly.

**Comment by michelle-dooley** [comment]
@dsinla - so the utm_campaign in the url will come ins as "Campaign" name in GA that you filter/report on.  Here is an example of [report]( https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.date00=20221001&_u.date01=20221018&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=500&explorer-table.secSegmentId=analytics.campaign&explorer-table.advFilter=%5B%5B0,%22analytics.pageTitle%22,%22BW%22,%22Contact%20Us%22,0%5D%5D&explorer-segmentExplorer.segmentId=analytics.pageTitle/) that is filtered to facility contact us pages.  You can see the campaign code which is (not set) for most (b/c they weren't part of a campaign) that would be populated with 'vamc_qrcode' or whatever you call it the utm_campaign field.  So I think you should be good on your reporting needs.  Let me know if you have any questions.

**Comment by dsinla** [comment]
@michelle-dooley Can you verify if it's possible to provide GA access for individual VA.gov employees who want to monitor and produce reports on this data?
