### ISSUE TITLE
Support User Journey Map - Interviews

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46360]
## Issue Description
_To better understand the support user journey, we need to interview users._

---
## Tasks
- [x] Completion of all scheduled interviews (10 total scheduled)
- [x] Capture and documentation of user interviews

## Acceptance Criteria
- [x] _Notes for summary and quick synthesis within notetaking document_ 
- [x] _Notetaking of all interviewee's answers within notetaking document_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
Document link: https://docs.google.com/spreadsheets/u/1/d/1PApm4Khz6ku3kaRjLcCZQVUlSWLhHUY1bdRQS2GiZLQ/edit?usp=drive_web&ouid=106137766750466696414

**Comment by manalo-soco** [comment]
Completed research interviews and then all documentation is google link above.
