### ISSUE TITLE
Participate in Informal Interviews with Staff at Cerner Sites

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46377]
## Ask from Stephen
Check in at Cerner sites - some people working with us on data mapping offered to set up logistics for informal interviews with staff at Cerner sites.  i really think having you all on those interviews (or even running them if you are willing!) would be greatly beneficial.  You have been living research for check in at VistA sites and have deep insights into how the staff are thinking, feeling and working, and that frame of reference I think will be greatly beneficial to understanding the staff experience at Cerner sites.   Of course we do not have a story for this (yet) and it might not go through the full review process like a more official UX study might, and I think that is ok for this (but will make sure leadership is aware and supports).  i see this as the first step in understanding what future research at Cerner facilities might focus on.   So, sorry for the novella, just thinking while typing.

First focus for interviews: patient tracking

## Tasks
- [x] Create interview questions
- [x] ~~Meet with MSA~~ Never received a meeting invite and they wanted to hold this interview before a meeting on September 1.
- [x] ~~Write-up notes from discussion~~

## Acceptance Criteria
- [x] ~~Notes are posted somewhere that Stephen identifies~~

**Comment by kristenmcconnell** [comment]
[Slack thread ](https://dsva.slack.com/archives/C02GXKL8WM6/p1661865456583969)about Cerner Patient Tracking Interview Questions

**Comment by kristenmcconnell** [comment]
Since they wanted to hold the interview prior to the meeting today and I never received an invite, I'm going to close this ticket.
