### ISSUE TITLE
User Survey Best Practices

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46373]
## Issue Description
_With more team expressing interest in custom surveys, we need to have general guidance to help them better understand use cases and best practices._

---
## Tasks
- [ ] _Create a draft of best practices and guidance for Medallia user surveys_

## Acceptance Criteria
- [ ] _A draft of Medallia best practices and guidance is complete and published in Confluence_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
