### ISSUE TITLE
Console UI Custom Survey Coordination

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46372]
## Issue Description
_As the primary point of contact for Medallia on the VA.gov Platform, our team helps other VA teams interested in implementing a Medallia Surveys by providing guidance to the teams and coordination with the VSignals Medallia technical team. In this case, we are coordinate the creation of the new survey along with implementation guidance for the Console UI team, who will be serving a survey internally to VFS teams._

---
## Tasks
- [x] _Request new custom Survey from Medallia tech team_
- [ ] _Provide Medallia survey script to Console UI team_
- [ ] _Provide Console UI team with general guidance on where the script should be injected_
---

## Custom Survey Questions/Answers
1. How would you rate your experience on the Console today? [1 to 5]
2. What feedback do you have about the Platform Console? [open-text]

## Acceptance Criteria
- [ ] _A new custom survey has been created for the Console UI team_
- [ ] _The Console UI team has been provide the implementation script for their survey_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
The survey has been created and we have been provided with implementation details, however, this is being deprioritized due to the Console UI team being deprecated and remaining teams having higher priorities to focus on. Moving to Icebox.

Per Medallia Tech Team:
We would need Dev Team to embed the environment scripts to the particular console’s in question – otherwise the surveys will not show on the console.

---
Support - https://platform-console-ui-utility.vfs.va.gov/support
Home page - https://platform-console-ui-utility.vfs.va.gov/homepage

---
Per your request, please find below Medallia Digital embed scripts that will need to be placed for each of the environment (testing vs production).

Staging/Testing:
<script type="text/javascript" src="https://resource.digital.voice.va.gov/wdcvoice/5/onsite/embed.js" async></script>

Production:
<script type="text/javascript" src="https://resource.digital.voice.va.gov/wdcvoice/2/onsite/embed.js" async></script>

Note the only difference is the property ID within the script, please ensure Dev Team places the correct script in the appropriate website/environment.

We will halt this task as it is now deprioritized, please let us know when you would like us to proceed (post embedding of the scripts above).

**Comment by ATMiddleton** [comment]
Veteran Support has expanded the task of offering Custom Surveys to VFS teams and will combine this ticket with #75141
