### ISSUE TITLE
New YAML Requests Land in Current Sprint Column

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46371]
## Issue Description
_We created new YAML templates for custom survey requests and qualitative data requests. by default, these new requests will land in our Zenhub icebox. In order to stay on top of these requests, it would be ideal for them to land in our `Current Sprint` column so they can be addressed in a timely manner_

---
## Tasks
- [ ] _TBD pending some discovery by our engineer_

## Acceptance Criteria
- [ ] _New Custom Survey Requests and Qualitative Data Request submitted via our new YAML templates land in the Current Sprint column in Zenhub._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
How is the contact center board populated?
Is there a way to automate putting an issue in a pipeline based on labels?

**Comment by ianMcCullough-ob** [comment]
Options

1. Leave it as it is
2. Create a new workspace so we can try and utilize workflows
3. GitHub action that is minimally used but can drop it in specific pipeline
4. GitHub action that uses Slack, may be easier to implement and easier to get approved.

Will proceed with V1 right now will recurring calendar events to remind to check icebox.
