### ISSUE TITLE
Support Reporting Sub-Categories Audit

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#46370]
## Issue Description
_Not all teams on VA.gov are able to view support data (easily) related to their products/features on VA.gov due to lacking sub-category options in Salesforce where support issues are generated by (VEO) tier1 agents. We need to identify gaps in categories/sub-categories in order to provide more comprehensive, relevant support issue data to teams building on VA.gov_

---
## Tasks
- [x] _Use VFS product directory to compare with Salesforce sub-categories and identify gaps_
- [ ] _Reach out to Product Managers from each team we have any uncertainty about to identify category/sub-category gaps_
- [ ] _Document recommended new categories/sub-categories within comments in this story_

## Acceptance Criteria
- [ ] _All VFS teams and known VA.gov products have been reviewed/considered against existing Salesforce categories/sub-categories_
- [ ] _Gaps in Salesforce categories/sub-categories and recommended new additions to Salesforce have been documented within this story._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jwoodman5** [comment]
New Sub-category: Supplemental Claim
Team: Benefits 1

New Sub-category: Decision Letters
Team: Benefits 1

**Comment by ianMcCullough-ob** [comment]
Here's an [old document](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2105049246/DOMO+Product+Mapping) showing current case sub-category mapping

**Comment by ianMcCullough-ob** [comment]
[VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
[VFS Product Directory User Guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

**Comment by ianMcCullough-ob** [comment]
[Mural categorizing VFS products](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1663001325794/f9df6c06db29a48fe9afe44d0dacd65bf7f53693?sender=u683996861c7842a72dea8966)

**Comment by jwoodman5** [comment]
We will use the products and categories represented in this Mural to strategize how we can best improve with so many products and the likelihood that not all could be singularly added to SF and represented successfully through tier 1.
