### ISSUE TITLE
FE | Profile | Contact Info | Military Address Bug

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46388]
## Background

A bug was discovered with using a military base address outside of the US.

Steps to reproduce:

- Check "I live on a United States military base outside of the United States." for mailing address
- Save the address. Save is successful.
- Go back to edit the mailing address. 
- **Issue 1:** "I live on a United States military base outside of the United States." is no longer checked, when it should still be checked and persist.
- **Issue 2:** Missing text underneath check box that starts with "U.S. military bases are considered..."
- **Issue 3:** The form should display with the military address format (include "APO/FPO/DPO" vs "City) unless the box is unchecked. 

Additional Info:

- **Mock** [mobile example](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/R1vgV1y)
- (Design ticket #37490)

## Tasks
- [ ] Update FE code to address the 2 issues noted above
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Deploy to Staging behind feature flag

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Deploy changes to Production using feature flag

**Comment by adamwhitlock1** [comment]
Came up with a couple things:

The FE is sending the correct payload for address updates in general with the `addressType` as `OVERSEAS MILITARY`, but it does not appear as it is being saved that way and is instead being returned from vets-api as a `DOMESTIC` address.

Initial Request Payload:

![Screen Shot 2022-09-08 at 10.46.21 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/76f10a78-4320-42f2-ac86-5dcec16b27d8)

Response for user after saving an update or loading profile for the first time:

![Screen Shot 2022-09-08 at 10.49.56 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/3685122a-a018-4caf-a181-effa5b17c8f9)

As a precaution I looked up a verified military base postal code and info from here to use with the test update: https://www.mfia.state.mi.us/olmweb/ex/foc/350X4.pdf

I think at this point we may need to look at the BE / vets-api / va profile to see why it may not be saving as it was sent. @tpharrison do you have any ideas at first glance why this could be happening?

**Comment by adamwhitlock1** [comment]
@SKasimow I will leave this open for now, but we should track the issue via Tom's ticket and I'll close this once we make sure there isn't work required on the FE.

**Comment by tpharrison** [comment]
@adamwhitlock1  - The vets-api is sending the correct data to VA Profile, but before saving the record, VA Profile runs through some validation checks and will coerce data elements.  VA Profile is unable to verify the address used above, so it ends up changing the address type from "Overseas Military" to "Domestic" - even if the override flag is set to _true_. 

When using a valid overseas military address (such as the one below), everything seems to work property.  The "I live on a United States military base outside of the United States." checkbox remains checked.

```
Unit 1 Box 1000
APO
Armed Forces Pacific (AP)
96205
```

I'm in discussions with Ian McEwan from the VA Profile team to try and determine how to resolve this.

**Comment by SKasimow** [comment]
Closing and will have this added as an item for upcoming VA Profile meeting.
