### ISSUE TITLE
Content review of "Need help" section for Supplemental Claims tool

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46394]
## Issue Description
Benefits team 1 asked us to review the content currently in the "Need help" section at the bottom of each page of the Supplemental Claims tool. We need to edit for plain language and so that it follows VA.gov style. Once we're finished we should post the final content in the intake request ticket: #46384

Text provided:

Need Help?
If you have questions or need help filling out this form, please call our MYVA411 main information line at 800-698-2411 and select 0. We’re here 24 hours a day, 7 days a week.
If you have hearing loss, call TTY: 711.

## Tasks
- [x] Edit text (Katherine)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Provide product team with finalized content in intake request ticket (Katherine)

## Acceptance Criteria
- [x] Content has been edited to adhere to VA.gov style and plain language standards

**Comment by katherine-fung** [comment]
Hi @laurwill, here's the draft of this message. Let me know what you think.  

"Need Help?

If you need help with this form, please call us at 1-800-698-2411 (TTY:711) and select 0. We’re here 24 hours a day, 7 days a week."

I removed "our MYVA411 main information line" because it seemed unnecessary, and directed people straight to the actual phone number. 

Note: The original message also appears on several other tool/sign-in pages.

https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start  

https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction

**Comment by RLHecht** [comment]
@megzehn This is ready for you!

**Comment by megzehn** [comment]
Thanks for bringing this one to the huddle today @laurwill. Confirming here that I shared this on #46384

Ready to validate @RLHecht

**Comment by RLHecht** [comment]
Thanks all! Closing this one out!
