### ISSUE TITLE
Understand How to Create Data Recording of a BGS Service

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#4639]
## Goal
Send a sample request to BGS (_using a service we currently have access to as an example_), and record the response.  We will need to understand how this is done in order to do future development and for local development and testing, as we do not have access to BGS services from our local development environment.

## Considerations
- Need to follow up with the Lighthouse team as I believe this does not use the current betamocks process.
- `vets-api` does not use betamocks, per se, to test BGS services but this new process is similar.
- Currently only applicable to `findDependentsByPtcpntId` as that is all we know today

## Tasks
- [x] Schedule some time with Charley
- [x] Connect to dev or staging box
- [x] Send request to a service we currently have access to
- [x] Record/save the response

## Acceptance Criteria
- [x] Create a json file from the response to be used as mock data
