### ISSUE TITLE
Resolve Outstanding JSON Issues

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4640]
_merged with 3506_

## Goal
Preceding ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4494

The frontend form for the 686c needs to have a 1-1 mapping to the paper form, via the JSON file generated from `vets-json-schema`. The above ticket should be completed prior to undertaking work on this one. 

_Goal from 3506_
As a frontend engineer, I want to get the Dependents submitted form data structure to match, and ensure that the the JSON file reconciles appropriately without a validation error in order for the previous teams work to function properly.

Once #4494 is complete, a step-through audit of the current 686 should be done to ensure form fields map correctly. This may include adding or removing fields.

## Considerations
- In order to get the form 686 work from the Rainbows team working on staging we need to fix the form's submitted data structure so that it both matches the shape of the JSON schema for the back end AND is valid for the VA form system. This validity is determined by our schema object rules found [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects). 
- When submitting the rainbows team form 686 there is a validation error at the end of the form shown in the Redux form state object. This error is not coming from the validation of the data entered into the form but rather from the shape of the data structure in comparison to the shape of the JSON schema for the form. We need to determine where the inconsistencies are, aided by notes from the previous front end engineer on the project Erik Hansen, so that we can determine a path forward to fixing them.
  - [Notes from Erik Hansen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/NotesFromErikHansen.md)
- This ticket was amended to incorporate the investigative work in [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3505) ticket.
- This is a link to the JSON Schema docs - https://json-schema.org/understanding-json-schema/reference/object.html#properties.  (Should come in handy, since more and more it seems we're going to be rebuilding the specific part of the 686c schema concerning location.)

## Tasks
- [ ] Compare data structures
- [ ] Document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/3506-summary.md) in GitHub inconsistencies between the form submission data shape and the shape of the JSON schema for the form.
- [ ] Make sure that fields line up with schema

## Acceptance Criteria
- [ ] The shape of the form data on submission matches the shape of the JSON schema object for the back end
- [ ] No schema invalidations errors get thrown when clicking the submit button

## Things to Check:
- Server error when attempting to submit. (422 unprocessable entity)
- Attempting to submit doesn’t update the corresponding status in the form object
