### ISSUE TITLE
[FE] Design and content updates to 1010CG confirmation

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#46408]
## Description

This work continues from the #44510 content review. The final design/content updates Sketch file is here:

- [1010CG confirmation page design/content updates](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/rbv4gDx)

See the older version of the confirmation page, content to copy/paste, and details below.

<details><summary>Old vs New CG confirmation page</summary>

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/a06df627-0882-46fb-853d-8a09ddbb5952)

</details>

## Tasks

- [x] **Update success alert heading and body content**
     - *[H3:]* Thank you for completing your application
     - *[Body:]* Once we’ve successfully received you application, we’ll contact you to tell you what happens next in the application process.

- [x] **Update featured content card**
     - *[H3:]* Your application information
     - *[H5:]* Veteran’s name
     - *[H5:]* Date you applied
     - *[H5:]* Confirmation for your records
     - *[Body:]* You can print this confirmation page for your records. You can also download your completed application as a PDF. 
     - *[Download link:]* Download your completed application (PDF)

- [x] **H2 heading 1**
     - *[H2:]* What to expect next
     - *[Body:]* We’ll contact you soon to tell you what happens next in the application process: If you gave us your email address, we’ll contact you by email within 24 hours. Make sure to check your inbox and your spam or junk folder. If you didn’t give us your email address, we’ll contact you by phone or mail. Note: If you’re not eligible for this program, you may still be eligible for other types of caregiver support.

- [x] **H2 heading 2**
     - *[H2:]* What to do if you have questions now
     - *[Body:]* Connect with a Caregiver Support Coordinator. Our coordinators can answer questions about your application. They can also tell you more about programs and services for caregivers. Find your local Caregiver Support Coordinator. Or call us at 855-260-3274. We’re here Monday through Friday, 8:00 a.m. to 10:00 p.m. ET, and Saturday, 8:00 a.m. to 5:00 p.m. ET. Learn more about caregiver support
     - *[Link:]* [Find your local Caregiver Support Coordinator](https://www.caregiver.va.gov/support/New_CSC_Page.asp)
     - *[Link:]* [Learn more about Caregiver support](https://www.caregiver.va.gov/)

## Acceptance Criteria

- [ ] Updated success alert
- [ ] Updated featured content
- [ ] Updated headings and body content

**Comment by hdjustice** [comment]
@longmd - Can you take a look at this ticket and see if there is anything else needed here?  I just remembered we didn't get a chance to talk about today at Grooming.  Thanks!

cc @markfallows

**Comment by longmd** [comment]
@hdjustice , everything looks good from my end. No questions or additional info to gather.

**Comment by nicko-amida** [comment]
@longmd Late update: the green success alert should now say "Thank you for completing your application" [I updated the task above]

**Comment by longmd** [comment]
This is on hold until 09/22
