### ISSUE TITLE
Issue survey, track responses

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46404]
## Issue Description
Develop a format that we could disseminate to have Teams "fill-in" needed info

## Tasks
- [x] add section to [Research plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2339143681/System+Service+Overview+Map+Research+Plan) to prep messaging/ask, as well as track participants and response in [Airtable](https://airtable.com/appbYNZ8PkZY7o9vs/tblXHp3UQAcjuotNa/viwNjGJl7am1QN2yD?blocks=hide)
- [x] Send survey to Platform teams

## Acceptance Criteria
- [x] Survey is sent out
- [x] platform teams' responses are gathered

**Comment by gopixelsgo** [comment]
[Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1b1tgFCkBPzMzj1AxgfwDyrFfGUNxOJ8rSF-hInH40gk/edit#gid=0) I used to organize and track communication about and responses to the survey. @tayism - this contains context that will help with your next steps.
