### ISSUE TITLE
PM + Design | Profile | Accessibility Audit Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46417]
## Background

Need to gather all open accessibility issues and identify any additions so we can begin working through these  in upcoming sprints and be compliant.

## Tasks
- [x] Identify all open accessibility tickets and make sure they are labeled correctly (SK)
- [x] Compile open tickets into one document (CG)
- [x] Meet with Accessibility team and review document of open issues and how to partner (LL)
- [x] Accessibility team provides input on prioritization and identifies any issues not already accounted for (LL)
- [x] Set up team grooming session to review each item, identify how to address and rate severity/complexity (SK)
- [x] Update/clarify existing tickets and create any new tickets as needed (SK + ES)
- [x] Prioritize tickets (SS + SK)
- [ ] Collab kickoff  (SK)

## Acceptance Criteria
- [ ] Add what must occur for this issue to be considered complete

**Comment by SKasimow** [comment]
@Samara-Strauss - I took the outline you started for the Accessibility Audit in Sprint 82 and expanded. Could you take a look and let me know if there is anything else I should add or change for "Tasks"?

**Comment by Samara-Strauss** [comment]
Looks good!
