### ISSUE TITLE
[FE] My VA Health care: Drupal familiarization (deprecation of 'isCerner' flag)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#46419]
## Background
The public websites team is planning to deprecate the Cerner hard coded data process by EOY (2022) in favor of a Drupal-driven API. We need to familiarize ourselves with this API and determine what we'll need to do on My VA to ensure the Cerner alerts function properly for Veterans.

## Tasks
- [x] Review documentation found [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for)
- [x] If needed, meet with public websites team
- [x] Document path forward for adoption/implementation of this API and deprecation of the isCerner hard coded flag

## Acceptance Criteria
- [ ] We have a documented path forward for what need to do to be compliant with this upcoming change

## Validation
**- _Who can validate this ticket? (FE, BE, Design, PM)?_** _________
**- _How can this work be validated?_** ____________

**Comment by ericasauv09** [comment]
API will be released on 12/1.

**Comment by tmitchellgcio** [comment]
We shouldn't need to meet the team. Seems fairly straightforward and well documented. They basically made a drop in replacement but I will want to do some testing on it when I implement it and we will need to replace every instance we are using it so I believe we will need another ticket with an effort of 3. The selectors we are currently using will be changed to use the drupal source of truth connectors
