### ISSUE TITLE
Create, review, and publish PACT Act CLP: Gulf War and post-9/11 Veterans (burn pits)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46410]
## Issue Description
Now that the PACT Act has become law, we need to create a campaign landing page in conjunction with OPIA with important information for Veterans. This specific CLP is for PACT Act info for Gulf War and post-9/11 Veterans.

The format should be the following:
• What is PACT Act
• What is presumptive
• The audience-specific eligibility Q&As
• The “getting benefits” Q&As

The content can be added to this Drupal page: 

http://preview-prod.vfs.va.gov/preview?nodeId=48973

We need to confirm if CLP urls are auto-generated or we need to add one manually. If it's manual we'll need to confirm the correct url. 

## Tasks
- [x] Add content to Drupal node
- [ ] Copyedit
- [ ] SME review
- [ ] Final copyedit with pre-publishing checklist
- [ ] Publish page

## Acceptance Criteria
- [ ] New CLP is live on the site

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA I've added in the FAQs to this page. 
The amount of questions surpassed 10, so I have left out the last question (When can I expect VA to make a decision on my PACT Act claim?” could not be included?

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
