### ISSUE TITLE
Investigate Lighthouse Changes to BGS Services

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#4641]
## Goal  
I need to understand the latest changes within `vets-api` related to BGS services and how they are initialized.  The Lighthouse team has informed us that they are making updates to the current process.  This will give us a better understanding of how `vets-api` is integrating with BGS (_which is still a WIP_) and the changes that are being made currently.

## Tasks
- [x] Trace through Lighthouse's changes to `vets-api` and, if needed,
- [x] Schedule a meeting with Charley re: Lighthouse's latest updates

## Acceptance Criteria
- [x] Define and document in GitHub the latest changes to `vets-api` related BGS services.
