### ISSUE TITLE
Create, review, and publish PACT Act CLP: survivors

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46414]
## Issue Description
Now that the PACT Act has become law, we need to create a campaign landing page in conjunction with OPIA with important information for Veterans. This specific CLP is for PACT Act info for survivors.

The format should be the following:
• What is PACT Act
• What is presumptive
• The audience-specific eligibility Q&As
• The “getting benefits” Q&As

The content can be added to this Drupal page: 

http://preview-prod.vfs.va.gov/preview?nodeId=48974

We need to confirm if CLP urls are auto-generated or we need to add one manually. If it's manual we'll need to confirm the correct url. 

## Tasks
- [x] Add content to Drupal node
- [ ] Copyedit
- [ ] SME review
- [ ] Final copyedit with pre-publishing checklist
- [ ] Publish page

## Acceptance Criteria
- [ ] New CLP is live on the site

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you!

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=48974

Not outlined in the scope of this ticket but two notes, as Randi mentioned I could go in and work on other areas (like the page intro):

I added in a sentence for the time being, but wonder if it may be best to wait until the other content has been added by OPIA to better frame the page intro! Will ask in tomorrow's standup. 

I also thought a bit about what would be best for the Primary Call to Action link (at the beginning of the page).  My thought is that it should be " File a disability claim online" that is on the PACT Act R&S page. But I'm wondering if there may be a preference for it to be "Apply for VA health care" I put in "File a disability claim online" for the time being.

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
