### ISSUE TITLE
New platform page for research methods

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#46418]
## User Story
As a VFS researcher, I want guidance on which research methods work well in a given situation, this can help prompt me or otherwise guide me to the best research method.

As Platform Governance Team, I want to make sure researchers can find all important guidance on Platform.

Assignee:
Peer Reviewer:

## Description
The [research plan template > methods section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md#method) does have a quick overview. However, the [Platform Research Methods](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1472888866/Platform+Research+Methods) is something to aspire for VFS facing guidance.

## Impacted Artifacts
new platform page: Research Planning > Research Methods

## Tasks
- [ ] Decide what, if not everything, from [Platform Research Methods](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1472888866/Platform+Research+Methods) applies to VFS teams
- [ ] Transfer relevant information to a new Platform page, including links to relevant 18F and NN/g pages

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
