### ISSUE TITLE
Document feedback that we know is out of scope

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46421]
## User Story
As a Governance team member I want to have a consistent process for documenting my out of scope findings at Staging Review* so that VFS teams receive feedback in a consistent and reliable manner.

Assignee: @allison0034 
Peer Reviewer: @jimuhh 

## Description
There are occasions where Governance team is aware that the feedback we are providing is out of scope for the VFS teams iteration of the product. However, Platform's OCTO leadership has stated that all identified issues need to be called out (whether they are part of the iteration or not). Because of this, we would like to ensure that when feedback is known to be out of scope, we communicate that to the VFS team.

## Impacted Artifacts
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review)

## Tasks
- [x] Update [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) to give specific guidance for how out of scope feedback should be documented.
- [x] If unsure on syntax, reach out to #platform-governance-team Slack channel for team input

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Out of scope feedback for Staging Review is documented consistently

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@allison0034 @jimuhh  - Sean was originally assigned as peer reviewer on this ticket. Jim, since you still have 2 other tickets that are higher LOE, I have moved you to peer reviewer and added Allison as assignee. If there are any questions, please let me know.

**Comment by jimuhh** [comment]
Sorry I missed this notification, Allison. Approved.

**Comment by allison0034** [comment]
@shiragoodman closing

**Comment by shiragoodman** [comment]
@allison0034 I was reviewing the updates to this and I'm not sure this is 100% complete. I see the changes for "If you identified feedback that was out of scope and know the correct team" and "If you identified feedback that was out of scope and do not know the correct team", but what about when the feedback is out of scope for the product. For example, we review the MyVA changes yesterday... what if the feedback is for the same product but not within the current scope/iteration the team is working on? I don't think either of these options apply. Let me know if you'd like to discuss.
