### ISSUE TITLE
[FE] DOB validation issues in Safari

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#46422]
## Description
Entering a malformed date(2 digit year, etc) and then clicking Continue, does not result in a validation message staying on the screen in Safari. In all browsers the bad validation state still allows the form to be submitted as well. 

It may be worth evaluating removing our custom validation and relying on just the out of the box validation that comes with the component. 

(Slack conversation)[https://dsva.slack.com/archives/C02GXKL8WM6/p1661888408385459]

## Tasks
- [ ] [FE] - make validation state stay visible in Safari
- [ ] [FE] - make sure that a bad validation state stops the page from making an api call with bad data.
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
