### ISSUE TITLE
[FE] 10-10CG Update PoA Verbiage

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#46423]
## User Story

As a caregiver completing the form and selecting that I have legal authority to make decisions for the Veteran, it is clear what type of documents can be uploaded to prove that authority. 

- [[PM] 10-10CG - Review Updated PoA Verbiage #45830](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45830)

## Related Documentation

**Desktop**
- [Step 4 Start - Additional Info Closed - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx4YeLW)
- [Step 4 Start - Additional Info Open - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlREeJZ)
- [Step 4 Upload Before - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/bgky1WV)
- [Step 4 Upload Confirm - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/PG82w48)

**Mobile**
- [Step 4 Start - Additional Info Closed - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/DPpxwGa)
- [Step 4 Start - Additional Info Open - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/m17xepw)
- [Step 4 Upload Before - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgwxOzW)
- [Step 4 Upload Confirm - Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZOExqzv)

## Description

The content needs to be updated in various places in the CG form under step 4/application signature (representative documents) to remove any references to medical stipulation required. 

## Tasks
**Page 1**
- [ ] Update content on [Step 4 Start - Additional Info Closed ](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx4YeLW) with:
> A representative must have legal authority to make decisions for the Veteran. If you choose this option, we'll ask you to upload a document that proves you have this authority.
- [ ] Update content inside of Additional Info component: [Step 4 Start - Additional Info Open](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlREeJZ) with:
> We can only accept a document that proves you have legal authority to make decisions for the Veteran (such as a valid Power of Attorney, legal guardianship order, or other legal document). We can't accept a marriage certificate, driver's license, or release of information form. Uploading a document that we can't accept may delay the application process.
- [ ] Update content of radio component: [Step 4 Start - Additional Info Open](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlREeJZ) with:
> A representative with legal authority to make decisions for the Veteran

**Page 2 (upload file flow)**
- [ ] Update content on page: [Step 4 Upload Before](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/bgky1WV) with:
> We can only accept a document that proves you have legal authority to make decisions for the Veteran.
> **Don’t have the right type of document?** Go back to the last screen. The Veteran will need to sign the application for themselves.
> ### How to upload your document
> - Choose a document that we can accept (such as a valid Power of Attorney, legal guardianship order, or other legal document). Don't upload a marriage certificate, driver's license, or release of information form. Uploading a document that we can't accept may delay the application process.
> - Save a scanned copy or photo of the entire document on your device. We can’t accept a cover or signature page without the rest of the document.
> - Format the file as a .pdf, .jpg, .jpeg, or .png. Be sure the file is 10MB or less in size.

- [ ] Update content on upload check/confirmation page: [Step 4 Upload Confirm](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/PG82w48) with:
> #### Check your upload before you continue ####
> It's easy to upload the wrong file by mistake. We want to make sure that we will review the right document (such as a valid Power of Attorney, legal guardianship order, or other legal document). This will help speed up your application process.
Check the file name. If it’s not the right file, you can delete it and upload another one before you continue.

- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

This is complete when the content is updated to what was provided by the stakeholders and reviewed by the Content team. Provided in Sketch file documentation and new content listed under tasks.

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the feature

**Comment by jessicastump** [comment]
Duplicate of #46424
