### ISSUE TITLE
[GH Workflow] Mark Issues and PRs Stale

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46436]
## Description
Issues and Pull Requests older than 90 days need a "stale" label applied. This will provide the initial list for infrastructure Drop Parties.

## Background/context 
- There are issues/pull requests that are old, and potentially no longer relevant
- Helps to prevent issues/pull requests from slipping through the cracks

## Technical notes
- https://github.com/actions/stale is a GH Action that can be used for this
- This can be a single workflow

---
## Tasks
- [x] Create a new "stale" label, if one does not already exist
- [x] Create a GH Action Workflow that add a "stale" label to PRs older than 90 days
- [x] Create a GH Action Workflow that add a "stale" label to Issues older than 90 days

## Acceptance Criteria 
- [ ] Issues and Pull Requests older than 90 days have a "stale" label applied

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Might be a bit of an [issue](https://github.com/actions/stale#operations-per-run) for `issues` as we may potentially run into github api rates. I don't think it will be an issue for PRs (at least in devops repo, infra-app-manifest... any others?)


But something to consider

**Comment by oseasmoran73** [comment]
GHA works for PRs and Issues. Closing this ticket as acceptance criteria has been met
