### ISSUE TITLE
[FE] Notification preferences: Add facilities to prescription shipment gate

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#46451]
### Background

Justin Wowk (VEText product manager) emailed me to let me know that two new facilities have been added to the Rx shipment notifications:

- Miami (546)
- Omaha (636)

We need to add these facilities to the gate that determines who sees the prescription shipment notification preference.

### Tasks

- [x] Add Miami and Omaha to the list of facilities that see the prescription shipment notification preference.
- [x] Double check list (attached) to make sure no other facilities are missing.

[vetext_rxSites.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9462322/vetext_rxSites.xlsx)

### Acceptance criteria

- [x] New facilities have been added to the prescription shipment notification preference.
- [x] I don't think there is a way to validate this through a specific user, so you can just test locally and let us know when this work is complete.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss this is done and will go out with today's daily deploy.

According to the provided XLSx spreadsheet the facilities that are changing are as follows:

Added:
'546', // MIAMI VAMC
'636', // VA NWIHS, OMAHA DIVISION
'673', // TAMPA FL VAMC
'695', // MILWAUKEE VAMC

Removed:
'605', // VA Loma Linda Healthcare System
'608', // Manchester VA Medical Center (Manchester, NH)

**Comment by adamwhitlock1** [comment]
Going to close this as there seems to be no further action needed at this time.
