### ISSUE TITLE
Review AMT documentation 

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#46453]
## Description
AMT is transitioning off of the console, we are taking a lot of what they worked on. 
## Tasks
- [x]  Read the docs :https://vfs.atlassian.net/l/cp/b2zpPZA0

## Acceptance Criteria
- [x] feedback given or questions asked

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by RachalCassity** [comment]
Looks good to me.
