### ISSUE TITLE
Remove references to old Product Directory

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46476]
## User Story
As a Platform team member, I want to direct VFS teams to the current Product Directory, and not the old, outdated product directory so that VFS teams can validate their product information in the correct place.

Assignee: @seanasewell 
Peer Reviewer: @allison0034 

## Description
QA Standards team launched the new VA.gov Product Directory on 8/30/2022. This means that the old directory is no longer valid and all references to it in Governance team products should be removed.

New Product Directory: https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory
Old Product Directory: https://vfs.atlassian.net/wiki/spaces/VAProducts/overview

## Impacted Artifacts
[New VFS Team gh template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
Others?

## Tasks
- [x] Search Platform Website for references to Product Directory. If any are found, document them here:
- This page references the product directory but the link in it has been updated to reflect where the new product directory is located. https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-guides
- References a google sheet. https://depo-platform-documentation.scrollhelp.site/support/incident-management
- References old product directory. https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket
- [x] In the [New VFS Team gh template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D), remove old link to Platform Directory and update with new link.
- [x] Update the gh template to reference the QA standards instructions for how to update the Product Directory
- [x] Reach out to @andreahewitt-odd and ask if we should 1) add deprecation message to old product directory or 2) archive old product directory

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams are no longer directed to the old VA.gov Product Directory
- [x] VFS teams are now directed to the new VA.gov Product Directory
- [x] Old product directory has been deprecated and/or archived

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@shiragoodman I am closing this as the work is complete
