### ISSUE TITLE
BE - Auth Profile - Add Profile Claims to User Response

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#46474]
## Background
The Profile page automatically makes requests to multiple vets-api endpoints. In many cases these requests result in 403 error responses due to the user not being authorized to make the request.

These requests can be reduced or eliminated by selectively calling the vets-api for a user. In order for the FE to be more selective when making vets-api calls on behalf of a user, it must have know which endpoints the user is authorized to call. This information will be passed to the FE from the v0/user endpoint.

## Tasks
- [ ] Add claim for `/v0/profile/personal_information`
- [ ] Add claim for `/v0/disability_compensation_form/rating_info`
- [ ] Add claim for `/v0/profile/ch33_bank_accounts`
- [ ] Add claim for `/v0/profile/communication_preferences`
- [ ] Add claim for `/v0/profile/connected_applications`

## Acceptance Criteria
- [ ] Claims for all the above endpoints are included in the `v0/user` response.
