### ISSUE TITLE
Workshop on research desirables for Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46483]
## Issue Description
We've discussed conducting research w/ VFS team members to better understand why they aren't completing the survey, as well as what might be more useful to include in it.
Discuss what we want to accomplish with this research.

Perhaps low stakes conversations with Team Leads/Members about why the survey may not be engaged with so much

## Tasks
- [ ] Capture key questions for use in Conversation guide
- [ ] Identify roles and individuals to learn from

## Acceptance Criteria
- [ ] key questions are documented
- [ ] key research sources are established
