### ISSUE TITLE
Consider potential changes to Survey format

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46482]
## Issue Description
Discuss ideas for how to alter the survey such that we gain more useful insights:

-Consider altering frequency (might be too frequent to get people to continually invest their time)
-Should we build out more detailed questions?
-Should we create more refined sections of questions (onboarding, repo pulling, etc) to garner more numerous and detailed responses?
-What is the rate of completion from newer team members? How are we serving these folks? Should survey include a "how long have you been here" question? (Or range)

## Tasks
- [x] [Consider potential changes that can add useful insights](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2451439661/Potential+changes+to+Customer+Insight+Survey+format)
- [x] Schedule session with team
- [x] Discuss with team 

## Acceptance Criteria
- [x] Decisions/directions on items
