### ISSUE TITLE
Brainstorm map concepts

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#46484]
## Issue Description
Everyone will sketch some ideas for the format/structure of the map

## Previous ticket's questions and references:
Questions to evaluate:
How do we make it easily consumable while also making it comprehensive?
What are the top / most important pieces of information to map?
Consider multiple iterations dependent upon needs/consumer
How do we map out "reports to"?
How do we map out Platform-Platform and Platform-VFS links/bridges?

-Gaps
-connections
-Perhaps visually: how to make sure connections are clear? and rightly represented?
-rollup for customers of each product on a team

Note: teams tend not to talk/think about who their customers are. May be able to surface these voids

Concepts Mural: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661266120803/aa3069d80fc9a3137a519fe3def0f42d1b27bff7?sender=u4397b715dc3690a417b71483

Correlation Mural:
https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661278901419/0c0f38ec98df4b2e188625688eae505e53f08f63?sender=u4397b715dc3690a417b71483

Data reference: https://airtable.com/appbYNZ8PkZY7o9vs/tblXHp3UQAcjuotNa/viwNjGJl7am1QN2yD?blocks=hide

## Tasks
- [x] Schedule workshop
- [x] Sketch ideas (Taylor)
- [x] Sketch ideas (Nicole)
- [x] Sketch ideas (Dan)
- [x] Sketch ideas (Bryan)
- [x] Meet to discuss and refine

## Acceptance Criteria
- [ ] Concepts and resulting questions are [documented](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662051199435/0ccbdef4e1eeb8f0daa7d7ec9607225aa4c064f9?sender=u4397b715dc3690a417b71483)
