### ISSUE TITLE
Supplemental Claims | pt. 2 Make submissions retryable

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46505]
## Value statement

**_As a_** Veteran that had just submitted an Supplemental Claim form
**_I want to_** know that my submission was successful, and if not immediately successful, it should keep retrying and show me a message
**_So that_** I know my submission was successful, or that the system will continue trying to submit my form when the service doesn't accept my form right away.

## Background content

The current Lighthouse endpoint we use to submit a SC is pretty reliable, but the upstream VA "systems of record" Lighthouse relies on is sometimes down for maintenance, both planned and unplanned. The backend work to retry submissions has already been complete (https://github.com/department-of-veterans-affairs/va.gov-team/issues/44261)

For form 526, the confirmation page will show a "It's taking longer than expected" message after about 30 seconds.

## Acceptance criteria

- [ ] When a SC is submitted, it should show a success message if immediately successful
- [ ] When a SC is submitted, it should show a message telling the Veteran that we're still trying if not immediately successful

## Tasks

- [ ] Update confirmation page to show a success message when immediately successful
- [ ] Update confirmation page to show a message, like "it's taking longer than we expected" when not immediately successful

**Comment by thehastingsp** [comment]
@kylesoskin @Mottie and I huddled and concluded we should support these 3 scenarios, as solving for retryable errors adds complexity and makes it potentially difficult for users to recover from the error. We also think we will see a clearer signal of error from submission failures, than if we have to parse through retries. Language to be confirmed, but here are the scenarios we decided we should support:

Scenarios: 
1. **SUCCESS:** comes back successful, we confirm submission with ID, link them to claim status to follow their claim. 
2. **FORM ERROR:** Inline errors that prevent submission.
3. **SUBMISSION ERROR:** We’re sorry. Your application didn’t go through. Please try submitting again. (language to be confirmed)
