### ISSUE TITLE
Notice of Disagreement | pt. 2 Make submissions retryable

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46507]
## Value statement

**_As a_** Veteran that had just submitted a NOD form
**_I want to_** know that my submission was successful, and if not immediately successful, it should keep retrying and show me a message
**_So that_** I know my submission was successful, or that the system will continue trying to submit my form when the service doesn't accept my form right away.

## Background content

The current Lighthouse endpoint we use to submit an NOD is pretty reliable, but the upstream VA "systems of record" Lighthouse relies on is sometimes down for maintenance, both planned and unplanned. The backend work to retry submissions has already been complete (https://github.com/department-of-veterans-affairs/va.gov-team/issues/42869)

For form 526, the confirmation page will show a "It's taking longer than expected" message after about 30 seconds.

## Acceptance criteria

- [ ] When a NOD is submitted, it should show a success message if immediately successful
- [ ] When a NOD is submitted, it should show a message telling the Veteran that we're still trying if not immediately successful

## Tasks

- [ ] Update confirmation page to show a success message when immediately successful
- [ ] Update confirmation page to show a message, like "it's taking longer than we expected" when not immediately successful

**Comment by eileen-coforma** [comment]
Touch based with @Mottie on this and he and @kylesoskin thinks this is unnecessary since Lighthouse has a better track record than EVSS. Might not be the best use of our time.
