### ISSUE TITLE
Add Treatment Specialty to CC details

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#46513]
PPMS has a "Treatment Specialty" field that indicates the type of care a CC doctor provides. [Here's the full list of possible options for that field.](https://app.zenhub.com/files/133843125/6c2b7cad-5809-47ef-b133-474f77c78338/download)

**Note that this doesn't replace "Type of care." This is a new field.**

**Assumptions** 
- Treatment Specialty shows only for CC appointments.
- Treatment Specialty is a good indicator of type of care
- Treatment Specialty only makes sense in the context of a provider. We will always show the Treatment specialty alongside a provider's name.
- We will not show Treatment specialty in the CC request flow.
- Treatment Specialty will show for booked CC appointments that are upcoming, past, or canceled 

**Questions**
Q. Will Treatment Specialty show for requests?
A. No, this information will not be added to the request flow or CC requests.

Q. Will we ever get back a Treatment Specialty without a Provider Name? Or vice versa?
A. No, both are required fields in the workflow where they are added.

Q. Are Treatment Specialties data used for other purposes? Some of the options seem to refer to facilities:
    - Clinic/Center - Ambulatory Surgical
    - Skilled Nursing Facility
    - Pharmacy - Home Infusion Therapy Pharmacy
A. CC schedulers add the Treatment specialty each time they create a new appointment. The data in the field is part of a standard used for other purposes.

**Preliminary design**
This may change during the design process. Here's how the new field might show in a booked CC appointment

---

### CC Booked-Future

**FORM TITLE**

n/a

**PAGE HEADER**

```
{appointment date} at {appointment time}
```

**PAGE DESCRIPTION**

none

**PAGE CONTENT**

```
Type of care: {Type of Care}

Community care
{Provider name}
Specialty: {treatment specialty}

{Provider address}
Directions

Main phone: {phone number}
TTY: 711

You shared these details about your concern
{Booking note}
```

```Add to calendar```

```Print```

```
Need to make changes?

Contact this provider if you need to reschedule or cancel your appointment.
```

[Current CC appt copy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#cc-booked-future)

### Tasks

- [x] Mockup designs with treatment specialty added for the CC Booked, Past, and Canceled details pages.

### Deliverables

- [x]  Mobile/Tablet/Desktop screens - [design file](https://www.figma.com/file/HxgPrBFb7RoVtkVXL5CYZJ/Add-Treatment-Specialty-to-CC-details?node-id=13%3A33)

### Post dev tasks
To be done after dev work is complete (see blocking ticket)
- [ ] Update design templates

**Comment by outerpress** [comment]
@Cieramaddox to update templates

**Comment by outerpress** [comment]
Treatment specialty is showing in CC appointments, closing
