### ISSUE TITLE
Supplemental Claims | Update 5103 page design

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#46512]
## Value Statement

**_As a_** front-end developer
**_We want to_** make sure the Supplemental Claims 5103 acknowledgement page matches the design
**_So that_** the Veteran has a clear understanding of the purpose of this page

## Background Context

The Supplemental Claims (SC) form (20-0995) 5103 acknowledgement page has some basic placeholder text and it is not clear why the acknowledgement is required. The updated design should help clarify that.

[Design](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/9872C53A-62DB-47BB-87D4-3480519D4B45/canvas)

## Tasks

- [ ] Update the 5103 acknowledgement page
- [ ] Add/update unit tests as needed

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
Hold until after Pam approves content changes.

**Comment by thehastingsp** [comment]
This is done and [referenced here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48399)

**Comment by saderagsdale** [comment]
@Mottie I'm going to combine this ticket with #48399, it's basically a dupe.
