### ISSUE TITLE
Alphabetize product list by product name on update

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#46523]
## Issue Description
The product directory should be alphabetized by product when it's updated. This will keep both our form and our published list on the platform website organized.

---
## Tasks
- [x] Change product directory update script to alphabetize the json object by product name when making changes.

## Acceptance Criteria
- [x] The published product directory lists products in alphabetical order
- [x] The yaml form dropdown has all products in alphabetical order
---

**Comment by CBonade** [comment]
Confirmed by adding a Z to the front of the first product in the list as a requested update. It was moved to the last product in the list.

**Comment by pjhill** [comment]
Thanks for taking care of this issue! I didn't verify this myself because I didn't want to introduce noise at the moment, but if there are tweaks that we need to continue to make we can address that in a new ticket.
