### ISSUE TITLE
Research LOA1 DSlogon attempts

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#46528]
# Description
During our second test of Sign-in Service, we saw a handful of LOA1 DSLogon attempts.  This shouldn't be possible as LOA1 DSlogon users shouldn't exist in Prod.  

# Tasks
- [x] Reach out to ID.me to get the UUID's for these users
- [ ] Determine what happened
- [ ] Ticket for any fixes needed

**Comment by joeniquette** [comment]
Sent to IDme to ask whats going on

**Comment by joeniquette** [comment]
We have some information back from IDme but its inconclusive, followed up with more questions on 9/6.

**Comment by joeniquette** [comment]
Test ran yesterday showed 7 DSLogon users who are coming back as LOA1. Will send the report to IDme.

**Comment by joeniquette** [comment]
Send report to IDme on 10/21/22

**Comment by joeniquette** [comment]
no updates from IDme yet

**Comment by joeniquette** [comment]
IDme was give a contact for DSlogon on 11/10 to attempt to get to the bottom of why we are seeing loa1 accounts.
