### ISSUE TITLE
Fix Mochawesome video paths

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#46522]
## Issue Description
Mochawesome video paths have become incorrect due to an unknown change. The videos no longer load correctly. We need to diagnose what changed to cause this and correct the error.

---
## Tasks
- [x] Diagnose issue with Mochawesome report video paths.
- [x] Correct the error and ensure videos load on the report.

## Acceptance Criteria
- [x] Mochawesome reports contain accurate videos of failures that are easily viewable.

**Comment by pjhill** [comment]
To-do -- In the future, our Cypress version upgrade test should include verification that the videos are available in the Mochawesome report.

**Comment by pjhill** [comment]
I spot checked a couple. Looking good. [Here's an example](https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-cypress-reports/8685b332-737e-4aae-89f6-3d1874083047.html) of a functioning video playback.
