### ISSUE TITLE
Review Copy for Debt Collection Relief Extension

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#46526]
## Issue Description
VA has extended temporary hardship suspension for benefits debt to December 31, 2022. 

- [VA Press Release](https://www.va.gov/OPA/PRESSREL/pressrelease.cfm?id=5817)
- [Military Times Article](https://www.militarytimes.com/veterans/2022/08/30/va-extends-debt-collection-relief-until-the-end-of-2022/)

Our DMC stakeholders have asked us to review the debt portal and associated pages on va.gov to ensure there is no mention of the previous September 30, 2022 date. 

> Could you have your team take a peek at the site, ensuring there aren’t any dates listed for 9/30/22, since we did extend the hardship suspension to 12/31/2022.
> 
> Two examples, which do not have a date (which is fine) are:
> [VA COVID-19 Debt Relief Options For Veterans And Dependents | Veterans Affairs](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Fresources%2Fva-covid-19-debt-relief-options-for-veterans-and-dependents%2F&data=05%7C01%7Cdenise.coveyduc%40govcio.com%7C5543178d23974aa6fb9208da8b91c17d%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637975755373611091%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X%2B98xTaVU3n9m9kk437Pd03tKvDr7PtOJXynEjDDQIA%3D&reserved=0)
> [Student FAQs: COVID-19 Information Affecting Education Benefits for Students - Education and Training (va.gov)](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbenefits.va.gov%2FGIBILL%2FCOVID19EducationBenefits.asp&data=05%7C01%7Cdenise.coveyduc%40govcio.com%7C5543178d23974aa6fb9208da8b91c17d%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637975755373611091%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L8F3wnjrQiJEaQtN8Ujz%2Fq6WG7Cxx2yjcnyWYHAoGb0%3D&reserved=0)

---
## Tasks
- [x] Review site and identify any instances of September 30, 2022 date that needs to be changed

## Acceptance Criteria
- [x] Document changes required
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by briepipitone** [comment]
The site has been reviewed and I found not references to the September 30, 2022 date.
