### ISSUE TITLE
Fix duplicated package_dependencies in the publish step

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#46531]
## Issue Description

The `package_dependencies` field is duplicating entries when it is published to Confluence.
![image.png](https://images.zenhubusercontent.com/62222b1c8a8a2d232882a99b/39e75355-e4b5-41f1-9509-f6fb7efb7c19)

## Tasks

- [x] Correct the bug in the publish step.
- [x] Ensure other lists output are correct as well.

## Acceptance Criteria

- [x] Packages are not duplicated in the published list.

**Comment by rsmithadhoc** [comment]
This is all set, ready for review:

- https://github.com/department-of-veterans-affairs/product-directory/pull/442
- https://vfs.atlassian.net/wiki/spaces/GS/pages/2350121126/10-10CG

**Comment by pjhill** [comment]
Looking good live on the Platform Website!
