### ISSUE TITLE
Explore removing whitespace from array fields for product directory update submissions

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#46530]
## Issue Description
We had a product directory update come in where the endpoints_consumed field had a ton of extra space causing it to fail validation. We should explore if any arrays need spacing at all, and if they don't, removing all whitespace in array fields when the product directory is updated.

---
## Tasks
- [x] Check if any array fields need spaces allowed
- [x] If not, add removing white space to the array processing on a product directory update.

## Acceptance Criteria
- [x] The product directory can be updated without random extra spacing in array fields.
---

**Comment by CBonade** [comment]
Tested this with an array with deliberate space in it. Spaces were removed on the update.

**Comment by pjhill** [comment]
Bug fixed -- noice!
