### ISSUE TITLE
[Application Hosting and Deployment] Document how to promote an application to higher environments (EKS) 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#46549]
## Description
Platform Crew developers that are deploying applications to EKS need documentation that explains how to promote an application from dev to higher environments. 

## Background/context 
- See parent epic
- Existing docs 
  - [Promote an Application in the EKS Infrastructure (as a Platform Crew team)](https://vfs.atlassian.net/wiki/spaces/OT/pages/2324037840/Promote+an+Application+in+the+EKS+Infrastructure+as+a+Platform+Crew+team)
  - [Onboard a New Application to the EKS Infrastructure (as a Platform Crew team)](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594142/Onboard+a+New+Application+to+the+EKS+Infrastructure+as+a+Platform+Crew+team)

---
## Tasks
- [ ] Create documentation that outlines the process of promoting an application from dev to high envs

## Acceptance Criteria 
- [ ] Documentation exists in Confluence with the following: 
  - [ ] 1-2 sentence overview of what the document contains
  - [ ] Step-by-step instructions for Platform Crew team members to follow 
  - [ ] Links to resources (such as forms, code, repos, and workflows) needed to follow the instructions

**Comment by jhouse-solvd** [comment]
Documentation [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2324037840/Promote+an+Application+in+the+EKS+Infrastructure+as+a+Platform+Crew+team)

**Comment by jhouse-solvd** [comment]
It appears that the "Promote an application..." doc (linked above) needs to be refined. There have been recent improvements to the process that are not yet reflected in the document. 

Additionally, there is a link to the promotion form from the "Onboard a new..." doc (linked above). That form link should probably be moved to the promotion doc. And the onboard doc can just link to the promotion doc.

**Comment by jhouse-solvd** [comment]
@jsgarmon - Can you take this one on? Let me know if you need any more info.

**Comment by jsgarmon** [comment]
I've updated [the doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/2324037840/Promote+an+Application+in+the+EKS+Infrastructure+as+a+Platform+Crew+team) with the current process, to the best of my knowledge. Others may want to take look and add edits.

**Comment by jhouse-solvd** [comment]
Thanks, @jsgarmon! We'll take a look.

**Comment by jhouse-solvd** [comment]
Looks good. This issue can be closed.
