### ISSUE TITLE
Discovery: App level timeout for Vets API

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#46546]
Controller requests should timeout after a pre-defined duration (e.g. 60 seconds).

## Tasks
- [x] Investigate rack-timeout as an option
- [x] Create related tasks for implementation of determined solution

## Acceptance Criteria
- [x] Related tasks created
- [ ] A timeout solution is determined

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

## Issues
[Adding rack-timeout gem](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46635)
[Lowering client timeouts to 60s](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46646)
