### ISSUE TITLE
Update broken link on Review and pay your copay bill page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46543]
## Issue Description

A recent SiteImprove report showed a broken link on the [Review and pay your copay bill](https://www.va.gov/health-care/pay-copay-bill/) page. 

In the accordion "How can I get help to understand my patient statement?" the link to "Download our guide to understanding your VA patient statement (PDF") is not working. We are reaching out to a health care stakeholder to find a new link but Danielle said we should remove the link for now.

## Tasks
- [ ] Remove broken link (Randi)
- [ ] Reach out to stakeholder (Randi)
- [ ] Update with new link
- [ ] Copyedit (Megan)
- [ ] Publish page (Megan)

## Acceptance Criteria
- [ ] Broken link is removed
- [ ] New PDF link is on live page
