### ISSUE TITLE
[Application Hosting and Deployment] Document how to connect to applications for troubleshooting (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#46553]
## Description
Platform Crew developers that are deploying applications to EKS with ArgoCD need documentation that explains how to connect to a running application for the purposes of troubleshooting. 

## Background/context 
- See parent epic 
- [Access/Exec into Pods Deployed to EKS via ArgoCD](https://vfs.atlassian.net/wiki/spaces/OT/pages/2269052931/Access+Exec+into+Pods+Deployed+to+EKS+via+ArgoCD)

---
## Tasks
- [x] Create documentation that outlines how to connect to a running application inside of EKS (ie 'exec into a pod') 

## Acceptance Criteria 
- [x] Documentation exists in Confluence with the following: 
  - [x] 1-2 sentence overview of what the document contains
  - [x] Step-by-step instructions for Platform Crew team members to follow 
  - [x] Links to resources (such as forms, code, repos, and workflows) needed to follow the instructions

**Comment by jbritt1** [comment]
Covered by https://vfs.atlassian.net/wiki/spaces/OT/pages/2269052931/Access+Exec+into+Pods+Deployed+to+EKS+via+ArgoCD
