### ISSUE TITLE
[MVP] [FE] Add a Manual Trigger in PagerDuty to Trigger the Downtime Component 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46559]
## User Story
As a Veteran, when Pre-Check-in or Check-in are not available for me to use because of a system problem or outage, I want to know so that I don't waste my time trying to use the applications.

## Tasks
- [FE] Add pager duty services for day-of and pre-check-in
- [] Document how to trigger a downtime notification and the details around the notifications
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
4 services have been set up in PagerDuty:

- Staging: Pre-check-in
- Staging: Day of Check-in
- Pre-check-in
- Day of Check-in

The services can be found here: https://dsva.pagerduty.com/service-directory?direction=asc&query=&sort_by=name&team_ids=PPW0SBU

The staging instances are to be used for dev, stage, and any review environments.  The others are for production only.

To put an app in maintenance mode. Click into the service in PagerDuty. Click the `+ Add a Maintenance Window` link.
![Screen Shot 2022-09-19 at 10.33.41 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/f21fcc58-bc6e-4d8a-ad3a-1961b31e3437)

Fill out the details and click the `Create Maintenance Window` button:
![Screen Shot 2022-09-19 at 10.35.12 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/57c3fae7-b546-46b9-8032-97bc89f84582)

To remove the maintenance window, visit the maintenance window management page at https://dsva.pagerduty.com/service-directory/maintenance-windows?team_ids=mine

Find the window you wish to end and click the `Update` button. On the pop-up for, click the `End Now` button:
![Screen Shot 2022-09-19 at 10.37.23 AM.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/d93fd7aa-2260-42d0-86c0-dce52dda3c99)

**Comment by brianseek** [comment]
One thing to note, we are using PagerDuty differently than other teams. Most implementations define the external services that the application depends on as services. These services have integrations that can trigger incidents and maintenance windows. None of the check-in dependent services are currently in PagerDuty. In the future, we may want to set those up in pager duty.

For this MVP, we have the actual applications (pre-check-in & check-in) defined as services so that we  can manually put them in maintenance mode. There are no integrations setup for these services in PagerDuty.

**Comment by brianseek** [comment]
@loripusey & @acrollet, here as some basic details on the implementation in PagerDuty to review.

**Comment by loripusey** [comment]
validated
