### ISSUE TITLE
[Application Hosting and Deployment] Document how to use the 'Hello World' helm template

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#46554]
## Description
Platform Crew developers that are deploying applications to EKS need documentation that explains how to manage Helm charts for their application. 

## Background/context 
- See parent epic 
- [How to build a Helm chart for the EKS infrastructure (as a Platform Crew team)](https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/How+to+build+a+Helm+chart+for+the+EKS+infrastructure+as+a+Platform+Crew+team)

---
## Tasks
- [ ] Create documentation that outlines how Helm charts are used on the VA.Gov Platform application hosting and deployment infrastructure 

## Acceptance Criteria 
- [x] Documentation exists in Confluence that contains the following: 
  - [x] 1-2 sentence overview of what the document contains
  - [x] How the helm chart is created and used for application deployments (brief) 
  - [x] Explanation of the key manifests of the 'Hello World' Helm template, e.g. the usage of:
    - [x] Deployment 
    - [x] Ingress
    - [x] Service 
    - [x] Environment variables 
  - [x] Links to resources (such as forms, code, repos, and workflows) needed to follow the instructions

**Comment by jhouse-solvd** [comment]
good overview resource to add to doc: https://helm.sh/docs/topics/charts/#the-chart-file-structure

**Comment by jhouse-solvd** [comment]
Follow-up issue to write user-facing documentation here: #46554

**Comment by rmtolmach** [comment]
Document created. Please review. https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/How+to+build+a+Helm+chart+for+EKS

**Comment by jhouse-solvd** [comment]
This is looking good! We can iterate based on developer feedback. Closing.
