### ISSUE TITLE
Update Platform Guidance on Unmoderated research

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#46568]
## User Story
"As a researchers, I want to know how to deal with abandoned respondents and other details around recruitment, so that I am working with recruitment in a way that benefits my study

As Platform Governance Team, I need to be able to point to guidance to answer questions and make sure that guidance can be found by product teams.

Assignee:
Peer Reviewer:

## Description
Some questions about how recruiting for unmoderated studies works was recently discussed in a [research-ops slack](https://dsva.slack.com/archives/C0216PL32HJ/p1661954911175199).
The points included 
- how to deal with abandoned tests
   - Recruiters (Perigean) does not track.
   - Researcher should not give Perigean that respondent's test code as a "complete." If they do Perigean will understand that as a completed test/task and process their payment.
   - Instead researchers should send recruiting team a list of codes that have been abandoned in order to reach out to the individuals to go back and complete the survey. 
   - abandoned test participants should not be marked "no show" as they would be for moderated studies. "There may be many reasons why the do not complete (including technology fails) , or why the abandon (we've seen cases where the form itself caused participants to not enter codes)."
- how to deal with blow throughs
   - "If we have a clear cut case of "blowing through the test", we can mark candidates as Do Not Invite to UNMOD."
   - to be decided (likely by Kevin H) - how to deal with "If the research team determines that a completed survey is not valid, how do we approach compensation?
We will need to be very careful with this issue, as we do not want to get into a position of offending the participants or debating whether they thoughtfully completed."compensation for blow throughs
- how to replace recruits that have multiple abandons
   - as long as their participant code was not submitted as "complete" they can be replaced
   -  the study may need to be extended to allow for additional screening and recruiting

## Impacted Artifacts
- [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies)
- although it may make more sense to create a new page since this is more aligned with conducting research vs planning.

## Tasks
- [ ] Figure out where this information needs to live - new page or existing
- [ ] Draft information in Confluence 
- [ ] Publish to Platform
- [ ] Announce in research-ops (and possibly design) Slack channel

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.
