### ISSUE TITLE
[DataDog] Log Retention

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46562]
## Description
Understand what options we have for storing DataDog logs older than 29 days.

## Background/context 
> ... the DOTS team has seen a spike in the number of logs that are being stored in DataDog. Typically we advise consumers of Datadog to move their logs at day 29 to avoid incurring additional fees from the vendor. Based on our research you currently have 1.29B logs stored in DataDog. Is there any chance your team could get these moved from Datadog into a longer storage solution ...

## Technical notes
- Possible options could be S3 or Glacier

---
## Tasks
- [ ] Understand what long-term storage options are available for DataDog logs

## Acceptance Criteria 
- [ ] Hold a team meeting to discuss your findings

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ianhundere** [comment]
this work as been completed, please refer to the following ticket for more info:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/42770
