### ISSUE TITLE
Design | Military Info | Update FAQ for DD214

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46564]
## Background

We're adding a link for DD214 ("Request your military records") in the profile under "Military information":

[Desktop](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/g0YO03a) & [Mobile](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/DPDA8Wk) mocks.

The Content team is in the process of reviewing the language for the expanded FAQ; based on this review we may need to update the mocks.

(Reference ticket #11053)

## Tasks
- [x] Work with Content and determine what changes are needed for the DD214 FAQ
- [x] Make updates to the mocks if needed

## Acceptance Criteria
- [ ] Provide updated mocks for PM and PO to review

**Comment by SKasimow** [comment]
@cgednalske - I'm going to assign this to next sprint so we track but if Content team can't address by then, we can just move it further out.

**Comment by SKasimow** [comment]
Hi @cgednalske - would you be able to take this to the next office hours so we can finalize?

**Comment by cgednalske** [comment]
@SKasimow - sure! I can check in with Danielle via message and see if it's something she wants to work through during content hours or if she can address asynchronously. I don't think this is a super high priority - just something on her list she wants to revisit/fix - but I'll work on moving it along. 

But this doesn't block anything with the link we're adding (finalized in the [earlier ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11053)), so we can absolutely can move forward with that without these FAQ changes if we haven't already.

**Comment by cgednalske** [comment]
Hi @SKasimow -- this has been updated with Danielle's suggestions. Here are the mockups for [Desktop](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/8aYYx8/a/25Da5yp) and [Mobile](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/vqxxa8/a/AxGmVg5). Note: both the question itself and the dropdown info have changed.

Btw I'm aware that the phone numbers need to show the underline for links, but Sketch isn't allowing me to do that right now. It's super finicky with font styles and sometimes does/sometimes doesn't allow it. So I'm working on getting that worked out, but I think we can move forward in the meantime with that noted so Adam and John know to use the link style.

**Comment by cgednalske** [comment]
@SKasimow One more note from Danielle: she thinks the TTY number we have listed might not be correct and should be checked. Is that something we can check out?

Here's what we have right now:
Contact the DMDC at 800-538-9552 (TTY: 866-363-2883)

**Comment by SKasimow** [comment]
Hi @cgednalske - re: the 711 question, I thought we just show "711" as we do elsewhere in profile and va.gov site.

For example, in the VA footer it looks like this:
![Screen Shot 2022-10-28 at 6 38 22 PM](https://user-images.githubusercontent.com/74627978/198746627-10a01213-d956-4263-8d04-678622a85c64.png)

Do you know why this message also needs an 800#?

**Comment by cgednalske** [comment]
That sounds right to me as well. At least that's how it seems to be elsewhere from what I've seen too. No I'm not sure why there was something there with the 800 number. Below is what it was before any of these content changes, where the format mentioned the number a couple of times. I wonder if it was sort of an accidental combo of TTY and the regular number that went under the radar. 🤔 

<img width="714" alt="Screen Shot 2022-10-27 at 8 10 44 AM" src="https://user-images.githubusercontent.com/79372956/198752382-6d761668-4be1-42b3-b3a6-ca2d7a509e01.png">

**Comment by SKasimow** [comment]
I also suspect it may have been an accidental combination bc all the user needs to do is dial 711. Much easier/quicker than an 800 #.

While looking at other messaging, I also noticed that we have a "+711" on "how to fix an error in your name or dob". Do you happen to have any background on why there is a "+" sign on alert below?

In either case, I can ask Samara about it when I meet with her on Monday and see if she has more info.

![Screen Shot 2022-10-28 at 9 00 43 PM](https://user-images.githubusercontent.com/74627978/198754789-20c6dbca-367c-4828-a0a2-6ffe2395d923.png)

**Comment by SKasimow** [comment]
Closing...FE opened #48782
