### ISSUE TITLE
Remove references to Chase Kirby

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46596]
Assignee: @allison0034 
Peer Reviewer: @shiragoodman 

## Description
Chase Kirby departed Governance team on 8/19. He is mentioned as a Governance team member on Platform Website, Confluence and Github templates. All mentions of him need to be removed.

## Impacted Artifacts
[Collab Cycle Request gh template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)
[Design Intent gh template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ccc1e33971be8efdf8654cc01d03e0088fad63ef/.github/ISSUE_TEMPLATE/design-intent-collaboration.md)
[Midpoint Review gh template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ccc1e33971be8efdf8654cc01d03e0088fad63ef/.github/ISSUE_TEMPLATE/midpoint-review.md)
[Staging Review gh template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/staging-review.md)
Distributions lists ; va.gov-design-intent@oddball.io; va.gov-midpoint-review@oddball.io; va.gov-staging-review@oddball.io
[PW Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

## Tasks
- [x] Review Platform Website and Confluence documentation and capture anywhere Chase is mentioned. Link all references above in Impacted Artifacts.
- [x] Remove all references to Chase Kirby

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] Chase Kirby is no longer referenced as a member of Platform and/or Governance team

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@allison0034 this looks good to me! I think you can close.
