### ISSUE TITLE
Clean Up VFS Team Roster Team Names

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#46593]
## Issue Description
We need to make sure all the team names on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) match what we have on the [VFS KPI dashboard backlog](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit?pli=1#gid=1660978947) (as applicable)

Team names in question:
AFS Education
Automated Benefits Delivery
Benefits Delivery
By Light
Check-in Experience
Clinical Decision Support
Content & Localization
DVSA
EDU Gov Team
EVSS Strategy/Documents
GOVCIO VFEP
Health Apps with Octo
MBMS
MBS
MEB
Ninja Pigs
Platform Engineering
PTEMS/Share Support
Quokka
TBD
VA VSP Design System
VA.gov Securing Messaging Convergence
Veteran Facing Education Products
VSA Shared Support

---
## Tasks
- [ ] Go through each person listed as being on one of the team listed above and determine what team they are on as the team name has probably changed (is it one of the other teams listed that aligns with our list or is the team they are listed as on correct and we are just not tracking it for the dashboard)
- [ ] Do this by looking in slack for their team information or other internal systems where that information may be.  If you cannot figure out from there you can always reach out.
- [ ] It is also possible some of these people are no longer with us, if that is the case please remove them altogether.

## Acceptance Criteria
- [ ] Up to date list
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
