### ISSUE TITLE
[cFSR] Content Updates with addition of Copays

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#46590]
## Issue Description
Text Updates to Enhanced FSR UXPin 
---
## Tasks
- [x] Compile list of text updates notes from UXPin/GH
- [x] Discuss updates with Danielle Thurs @ 11am
- [x] Make text updates

## Acceptance Criteria
- [x] Text updates approved by Danielle
- [x] Text updates made on UXPin

_____
## List of updates to make:
- [x] [Content page  - Update header text and "follow these steps"](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap,comments/6269a7cd2646a200cab4adb4?mode=i)
- [ ] [Content page - Empty states when copay is added](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021573/comment/sitemap/6269a66c7daf52008cab8d3c?mode=i) -To be discussed in the future
- [x] [Wizard - include text to include copays](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768/comment/sitemap,comments/6269a69dd9d272014e412eff?mode=i)

**Comment by mgleo** [comment]
Jill, Danielle, and Mikki have made comments on [UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571?mode=vid)

**Comment by denisecoveyduc** [comment]
Text updates are happening as part of #47339
