### ISSUE TITLE
Create instructions to access PagerDuty

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#46592]
### User Story
As a VFS team member,
I need to understand what the process is for gaining access to PagerDuty,
so that I know how to request access from the Platform team.

### Tasks

- [ ] Read through the Slack conversations below
- [ ] Identify a technical subject matter expert from the Platform for this topic; This could be a question for the #vfs-platform-support team.
- [ ] Ask them to create high-level instructions for "how to get access to PagerDuty"
- [ ] Ask them where in the IA of the Platform website this makes sense to live under.

- For example, a child page to this page? https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools
- Or perhaps the instructions are short so it simply is stated in the existing PagerDuty content of the page above?

- [ ] Review their written instructions and edit them as needed
- [ ] Place new content in the appropriate place in Confluence, make it ready for deploy

### Other Info
Slack conversations for context:

- https://dsva.slack.com/archives/CBU0KDSB1/p1658512387291239
- https://dsva.slack.com/archives/CBU0KDSB1/p1662057939793069
- https://dsva.slack.com/archives/CJRQ85PQB/p1662126382713709
