### ISSUE TITLE
Staging Review [Digital Health Platform - Device Connection]

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#46594]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [x]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [x] Respond to Platform feedback tickets.
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [x] Update Staging Review ticket with the product’s launch date after it has gone live.
- [x] Close Staging Review ticket when the review is complete and the product has launched.
- [x] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
- Staging URL: https://staging.va.gov/health-care/connected-devices
- VA.gov SSO Test Users: Test User Dashboard (TUD): https://tud.vfs.va.gov/
- Fitbit Test Users: please create your own test account/s

- [x] Product outline: [Digital Health Platform Device Connection Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-platform/README.md) 
 
  

- [x] Release plan with the "Planning" sections completed: [Digital Health Platform Device Connection Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-platform/product/release-plan.md) 

 

### Content artifacts 

- [ ] Your product’s content source of truth
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): 
**Mockups in Midpoint Review GitHub Ticket**
[Midpoint Review [Digital Health Platform, MVP] #43787](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43787)
**DHP MVP Demo**
https://user-images.githubusercontent.com/104447526/178034526-ee7673d4-5e54-480d-9ae2-ac56209134a2.mov

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Product test cases/test plan in TestRail with test execution logs 
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) 
- [ ] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14) 
- Please note that the Digital Health Platform's QA process includes automated test and all work is manually QA’d

### Accessibility artifacts 

- [ ] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). **(Preferred)** OR, 

- [ ] List of known issues

     •	Issue 1
     •	Issue 2
     •	Issue 3

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman , @chaseakirby

**Comment by robbie1226** [comment]
Please let me know if I unknowingly left anything out that's required for the Staging Review meeting.

**Comment by robbie1226** [comment]
Updated to include a link to the demo and to more explicitly call out the link to our Midpoint Review GitHub ticket which includes mockups, and the demo.

**Comment by ddzz** [comment]
@robbie1226 Are there any QA artifacts available?

**Comment by robbie1226** [comment]
@ddzz here's a link to our directory where all our automated tests live
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/dhp-connected-devices/tests

here's a link to our tests for vets-api
https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/dhp_connected_devices/spec

here's a link to the last vets-api test coverage run
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3045925658/jobs/4908192264

**Comment by ddzz** [comment]
No QA feedback, looks good!

**Comment by allison0034** [comment]
Hi @robbie1226 , we confirmed you do need to submit a [508 audit](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). Please let me know if you have any other questions.

Also, no design feedback : )

**Comment by reblg** [comment]
Hi! Apologies if this was shared somewhere else and I missed it, but is there a description / ticket of the Launch Blocking Accessibility issue that Brian shared on Friday?

**Comment by allison0034** [comment]
@reblg both tickets should be linked to the epic. [Here is Brians ticket](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/department-of-veterans-affairs/va.gov-team/47164).

**Comment by shiragoodman** [comment]
Zoom recording: https://oddball-io.zoom.us/rec/share/yrkXkLOgXpQ-TCGXi7sag-vaByk4ROF6-7gg8b-svMnwaurvSFVK2CL004kGhZLh.B3A_RK4u5P62eEkv 
Passcode: Fg64Tz=b

**Comment by reblg** [comment]
> Hi @robbie1226 , we confirmed you do need to submit a [508 audit](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). Please let me know if you have any other questions.
> 
> Also, no design feedback : )

Is the 508 Audit a pre-launch touchpoint or a post-launch touchpoint?

**Comment by allison0034** [comment]
@reblg it is done after, when the product is live?

**Comment by robbie1226** [comment]
@allison0034 during the Staging Review meeting we were asked to address. Please see below for details. 

**Accessibility Issue:** Resolved
[ZenHub Ticket](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/department-of-veterans-affairs/va.gov-team/47164) describing the issue.

**Breadcrumbs:** Not Required
The [IA Design for Connected Devices GitHub document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-connected-devices.md) created by the IA team following our meeting with them states that breadcrumbs are not needed.

**Comment by robbie1226** [comment]
**Product’s launch date:** 10/14/2022 behind a feature toggle

**Comment by robbie1226** [comment]
Submitted audit request to the VA 508 Office. Ticket no. REQ8126792

**Comment by robbie1226** [comment]
The 508 Accessibility Audit was successfully completed. The audit report stated "Audit conducted under [va.gov](http://va.gov/). Audit conducted the Week of November 26th found no 508 defects."

**Comment by robbie1226** [comment]
I am closing this ticket as the Device Connection page is live in production (behind a toggle) and all After Meeting tasks have been completed.
