### ISSUE TITLE
Replace `virtus` library with `dry-types`

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#466]
## User Story
As an engineer I want to replace the `virtus` library with `dry-types` so that our app's performance and maintainability is improved

## Background
[`dry-types` documentation](https://dry-rb.org/gems/dry-types/)
[`Virtus`](https://github.com/solnic/virtus) is no longer under development.  It's last update was over 2 years ago.
`dry-types` is the successor to `virtus`.  It is actively being developed and recently reached version `1.0.0`.

It claims  that it is
>Roughly 6-10 x faster than Virtus

## Approach
Given how closely the concerns track, this should _not_ be worked on while #465 is actively being worked on.

Given the large number of `virtus` models in our codebase, this work should be completed cautiously across multiple pull requests.

## Acceptance Criteria
- [x] add `dry-types` gem
- [ ] replace `virtus` attributes with `dry-types`
- [ ] remove `virtus` gem

**Comment by kfrz** [comment]
I think we should consider opening an RFC and discussing `sorbet` for static typing, it's coming alongside MRI types in ruby 3.0

**Comment by johnpaulashenfelter** [comment]
The amount of code to rewrite here is pretty large, especially with the way we use Virtus to magically initialize objects in `super` calls.

I think its worth some actual discovery -- writing some code w/ dry-types and some with sorbet and some without any external dependencies at all -- just to see what kind of effort is involved.

**Comment by johnpaulashenfelter** [comment]
Closing for lack of progress. Definitely will come up again in some form :)
