### ISSUE TITLE
[FE] Content/design updates for 10-10EZ confirmation page

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#46612]
## Description

This work is related to the 1010CG content review (#44510) - content team feedback can also be applied to the 10-10EZ confirmation page. The final design/content updates Sketch file is here:

- [10-10EZ confirmation page design/content updates](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dlRpem2)

See the older version of the confirmation page, content to copy/paste, and details below.

<details><summary>Old vs New EZ confirmation page</summary>

<img width="857" alt="image" src="https://user-images.githubusercontent.com/81988788/188710719-f9bf4d3c-6f53-48f4-b81a-2d9a49f00edd.png">

</details>

## Tasks

- [ ] Update green success alert
     - *[H3:]* Thank you for completing your application for health care
     -  *[Body:]* Once we’ve successfully received your application, we’ll contact you to tell you what happens next in the application process.
- [ ] Update featured content
     - *[H3:]* Your application information
     - *[H5:]* For Veteran
     - *[H5:]* Date you applied
     - *[H5:]* Confirmation for your records
     - *[Body:]* You can print this confirmation page for your records.
     - *[Button:]* Print this page
- [ ] Update H2 and body content
     - *[H2:]* What to do if you have questions now
     - *[Body:]* If we haven’t contacted you within a week after you submitted your application, please don’t apply again: Please call our toll-free hotline at  877-222-8387. We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
     - *[Link:]* [Learn more about what happens after you apply](https://www.va.gov/health-care/after-you-apply/)
- [ ] Move "How can I check the status of my application?" section
     - [There are no current content changes to this section]
- [ ] Move "How will I know if I'm enrolled in VA health care?
- [ ] Update the link content under "How will I know..." heading
     - *[Link:]* [Learn more about what happens after you apply](https://www.va.gov/health-care/after-you-apply/) 

## Acceptance Criteria

- [ ] Added success alert and content
- [ ] Updated feature content and links
- [ ] Updated H2 headings
- [ ] Updated body content and links

**Comment by nicko-amida** [comment]
@longmd I updated this to remove the "24hrs" stuff about email. Mockup was updated to reflect this.

**Comment by longmd** [comment]
This is on hold until 09/22.
