### ISSUE TITLE
Merge `platform/testing`  to main

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#46625]
## Issue Description
Merge `platform/testing` to main; completing handoff

## Tasks 
 - [ ] Complete In-browser test and document here https://docs.google.com/spreadsheets/d/1z2vxweOvWZF8twqKz7U27DWlBOn0fUGH-S_y638V8xM/edit#gid=0

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- [ ]  CodeOwner approval of  https://github.com/department-of-veterans-affairs/vets-website/pull/22069
- [ ]  Passes browser tests

**Comment by rmessina1010** [comment]
Completed.
