### ISSUE TITLE
Merge `platform/site-wide` to main

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#46624]
## Issue Description
Merge `platform/site-wide` to main; completing handoff

## Tasks 
 - [x] Complete In-browser test and document here https://docs.google.com/spreadsheets/d/1RNH6t-r_vnDxHbd65T1apdCmyCsyJGZORl0ctUfNxv4/edit#gid=0

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- [x]  CodeOwner approval of  https://github.com/department-of-veterans-affairs/vets-website/pull/22050
- [x]  Passes browser tests

**Comment by rmessina1010** [comment]
Completed.
