### ISSUE TITLE
Merge  `platform/forms-system` to main

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#46622]
## Issue Description
Merge  `platform/forms-system` to main; completing handoff

## Tasks 
 - [ ] Complete In-browser test and document here https://docs.google.com/spreadsheets/d/1o2FqxXrASbm_6PlpOsI0v2POwOcmxHPC7G6ya6gWSSo/edit#gid=0

## Dependencies
[Add Yarn Workspace to vets-website (base) #45101](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/45101)

## Acceptance Criteria
- [ ]  CodeOwner approval of  https://github.com/department-of-veterans-affairs/vets-website/pull/21982
- [ ]  Passes browser tests

**Comment by rmessina1010** [comment]
Completed
