### ISSUE TITLE
Implement rack-timeout gem for Vets API

### ISSUE THREAD

**Issue by jeremyhwu** [department-of-veterans-affairs/va.gov-team#46635]
## Description
Add rack-timeout gem to set a global timeout on the rack level for all controller requests.

## Tasks
- [x] Add and configure rack-timeout gem

## Acceptance Criteria
- [x] Rack timeout is merged to master
- [x] Requests in prod are still working as expected

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by ericboehs** [comment]
This went live with the last deploy.
