### ISSUE TITLE
[spike] Supplemental Claims | Technical Discovery

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#46632]
## Value Statement
**_As a_** team
**_We want to_** understand how data will flow through the supplemental claim workflow
**_So that_** we can map end-to-end experience from a data perspective.

---
## Background Context
- The scope of this effort is intended to help us understand how data makes it's way from the frontend to the database. 

## Tasks
- [x] Review the existing lighthouse end-points and document any deltas in our design and their endpoints.
- [x] Document the data formats that we are collecting on the front end. 
- [x] Confirm we AT LEAST support minimum fields from [doc] (https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) (we do)
- [x] Confirm we support ALL fields from [doc](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) (we do not, but we do not need to, we are not implementing all features of the LH api)
- [x] Document how we will map the front-end to the back-end request that goes to lighthouse (data flow diagram).

## Out of scope
- Code work

## Open questions

- [x] Should supplemental claims be retriable? (no, not right now at least)
- [x] Is adding the contention code of the claim a requirement for MVP/initial release? (No, but if it is easy enough we can add it)
- [ ] Do denied claims have a contention code associated with them, or only established/granted claims? 
- [x] Does claim status tool support supplemental claims already? If not, is that a condition of MVP/initial release? (It does. It is not a condition of MVP though anyways)

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kylesoskin** [comment]
### Notes/References, will be appended to

Current lighthouse endpoint (switch to v1 from v0 once on page)

https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/supplemental_claims/createSupplementalClaim

**Comment by kylesoskin** [comment]
Question: Does our front-end account for, and accept (via a checkbox/agree and continue) the 5103 acknoledgement? 

_Submits an appeal of type Supplemental Claim. This endpoint is the same as submitting [VA form 200995](https://www.vba.va.gov/pubs/forms/VBA-20-0995-ARE.pdf) via mail or fax directly to the Board of Veterans’ Appeals.

Note about the 5103 Notice of Acknowledgement

The 5103 Notice regarding new & relevant evidence must be acknowledged when the issue(s) being contested is a Disability Compensation issue. The notice can be found here: http://www.va.gov/disability/how-to-file-claim/evidence-needed. If the issue(s) being submitted are Disability Compensation and 'No' is selected, the API will return an error. Please ensure the Veteran reviews the content about the 5103 Notice at the link above.

Supplemental Claims submitted via other avenues that do NOT select 'Yes' for the 5103 Notice are subject to a 30 day suspense so the 5103 Notice can be mailed to the Veteran._

**Comment by sortizsh** [comment]
4142 and 4142A exist in 526 and can be reused hopefully. Create the PDF, attach as addition to a SC. 
4138 will need to be new code and will be a similar process.

**Comment by saderagsdale** [comment]
@kylesoskin Moving this to the sprint backlog while you're on leave.

**Comment by kylesoskin** [comment]
![supp claims diagram [internal] .jpg](https://images.zenhubusercontent.com/62067253500f33af56810776/506c827e-c511-44e3-b450-51b1d0a81600)

**Comment by kylesoskin** [comment]
Need to meet with @saderagsdale to determine which items in the "Definition of Ready" have been completed before closing

**Comment by saderagsdale** [comment]
@kylesoskin If we haven't already, can we store this in github?
