### ISSUE TITLE
[spike] Claims | Contention Classification

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#46634]
## Value Statement
**_As a_** team
**_We want to_** understand the feasibility and technical constraints related to classifying contentions
**_So that_** we can determine if the [proposed solutions](https://docs.google.com/document/d/1YevJPb4vkej6d1kIAelPaT4glrTgFyxm_pQGjNXdrdA/edit#) are viable.

---
## [Background Context](https://docs.google.com/document/d/1YevJPb4vkej6d1kIAelPaT4glrTgFyxm_pQGjNXdrdA/edit#)
VA.gov-submitted claims for new and worsened conditions do not get established with a contention classification, which means that the claim is established in an error state. As a result, Veteran Service Representatives (VSRs) must take additional steps in VBMS to set the classification for each contention. 

Additionally for claims for increase, VSRs need to manually associate the increase claim with the previously rated disability.

## Tasks
- [x] Understand how classification data is mapped and flows through the claim experience for the two use cases defined in the problem brief. 
- [x] Determine the best way to manage and store this data.
- [x] Document our findings and recommendation to the automation and lighthouse teams.

## Documents
- [Contention Classification brief](https://docs.google.com/document/d/1YevJPb4vkej6d1kIAelPaT4glrTgFyxm_pQGjNXdrdA/edit#) written by the automation team.
- [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1661967405058949) of classification mapping documents.

## Open questions
- [x] For increases and supplemental claims, we are submitting to lighthouse, who already has some amount of this info (or can get it), would it be better for us to submit as-is, and see if Lighthouse team can tack this info (that it already has or can get) along with where it sends to downstream? 
- [x]  Do denied claims have a contention code associated with them, or only established/granted claims?
- [x] Is it possible LightHouse is already sending along this information and it is just not being properly processed or received? 
- [x] How reliable are the currently set codes for existing claims? Claims have (or may have) changed over time? Do those get updated with changes? For example, for a test user I see a claim `"diagnosticCode": 5260,` `"name": "Allergies due to Hearing Loss",`, however, that diagnostics code currently maps to `5260 | Leg, limitation of flexion. `. It is also possible that the `name` fields is what the user typed (irrelevant) and that the diagnosticCode is what is accurate. But we are not sure of that either. 

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kylesoskin** [comment]
### Notes/References, will be appended to

Existing lighthouse contention search api method (plain-text matching, NOT any of the step 3 fuzzy matching as far as I can tell)

https://staging-api.va.gov/v0/disability_compensation_form/suggested_conditions?name_part=heart

Existing api method to get all rated disabilities FOR AN AUTHENTICATED USER, comes back with contention codes

https://staging-api.va.gov/v0/disability_compensation_form/rated_disabilities

Example return 

```
{
  "data": [
    {
      "id": "166",
      "type": "disability_contentions",
      "attributes": {
        "code": 1670,
        "medicalTerm": "choroiditis",
        "layTerm": "inflammation of parts of the eye"
      }
    },
    {
      "id": "183",
      "type": "disability_contentions",
      "attributes": {
        "code": 1840,
        "medicalTerm": "conjunctivitis",
        "layTerm": "pinkeye"
      }
    },
    {
      "id": "185",
      "type": "disability_contentions",
      "attributes": {
        "code": 1860,
        "medicalTerm": "corneal opacities",
        "layTerm": " eye disorder from cornea scars"
      }
    },
    ...
    ...

```

**Comment by kylesoskin** [comment]
Some new information...

EVSS does a string search on the name of disability coming in and will swap with whatever matches from BRD data (updated every 15mins). So the RRD thing they implemented will never work.

What needs done to fix this for all classifications:

Plan

things to do first
- [ ] Get correct mappings
- [ ] make a branch 
	- [ ] LH BRD update to new codes
	- [ ] [Disabilities.js ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/content/disabilityLabels.js) updated to same codes
	- [ ] Revert RRD Stuff? Possibly
- [ ] Merge/PR
- [ ] Coordinate release somehow/plan release



Release plan
- [ ] Feature toggle, disable all claims submissions
- [ ] Release (have to make first) MR That does the following
	- [ ] LH BRD update to new codes
	- [ ] Disabilities.js updated to same codes
	- [ ] Revert RRD Stuff? Possibly
- [ ] Manual EVSS update (15 min thing, or just wait 15+ mins)
- [ ] feature toggle all claims back on

**Comment by kylesoskin** [comment]
Make front-end pull BRD pull each time, later. Just change BRD data and hard-coded list for now, quickest path forwards.

**Comment by saderagsdale** [comment]
@kylesoskin Moving this to the sprint backlog while you're on leave.
