### ISSUE TITLE
Lower timeouts for all clients to 60 seconds

### ISSUE THREAD

**Issue by jeremyhwu** [department-of-veterans-affairs/va.gov-team#46646]
## Description
Rack-timeout will enforce a global timeout of 65 seconds for all requests when it is added. Client timeouts should be lowered to 60 seconds so that they can attempt to handle timeouts gracefully on their own rather than relying on the thread level exceptions raised by rack-timeout.

## Tasks
- [ ] Change all client timeouts to 60s or lower

## Acceptance Criteria
- [ ] Timeouts have been lowered 60s

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by laineymajor** [comment]
@ericboehs reassigning to y'all... feels like this is more in your wheel house

**Comment by npeterson54** [comment]
Closing this one out, not something we are working on for now.
