### ISSUE TITLE
[cFSR] Confirmation page resolution option display

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46643]
## Issue Description
Confirmation page on FSR needs to show selected copay resolutions for submitted fsr

---
## Tasks
- [ ] Update confirmation page for cFSR resolution options. 

## Acceptance Criteria
- [ ] Selected copays and their resolution options are showing on the confirmation page once a combined FSR is submitted
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
