### ISSUE TITLE
Implement Feedback From Design Intent Review for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4664]
## Goal
Implement feedback received for "View Dependents" from Design Intent Review and triage based on scope and domain, starting with Design.

## Tasks
- [x] Review, respond and triage items from feedback
- [x] Assess next steps for each

## Acceptance Criteria
- [x] Each item has been implemented and/or addressed in the "View Dependents" mockup

## Notes from Design Intent Review:
_Accessibility Notes/Jennifer Strickland_

**- What is the context/purpose for each page? What is the purpose of the person using this page?**
The "View Dependents" page is where a Veteran can view their dependents, see whether the dependent is associated with an award or not, and take action.

**Page 1**
**- I wonder if the right rail content would be helpful an the Additional Info show/hide component above the "Dependents on your award" heading. At a minimum, that they collapse into that area on mobile. Mobile and screenreader users are unlikely to access that information in context, if at all.** 
These have context with the page overall.  For accessibility, we want to trend away from show/hide toggle buttons.

**- Have you considered diagramming the flow of how the Veteran gets to this?** 
Yes, this was done in issue [#4536](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4536)

**- What purpose does the grey background serve? Are you establishing a pattern for items to be presented within the grey containers? Concerned about longer vertical spacing, increasing effort for those on mobile, with mobility issues, or cognition (on mobile). Since nothing is interactive today, there's no concern for erring with an accidental touch while scrolling -- but for future state, if actions are added may be something to keep in mind. Recovery from errors can be tough for mobility-challenged. If the future vision is for these items to include interactive actions, this grey card-like pattern makes sense, and the spacing helps to avoid erring.**
Use of grey and card components over all in general were a design system decision and relayed to us.

**- The information itself seems like it could be tabular. For a semantic alternative to a table, a dl would work.**
Yes, we spoke about this briefly and think we can implement that pretty easily like we did with Rated Disabilities.   

**- The green button - is that the primary action for this page? Or, is it a secondary action? Would the primary CTA on this page be to view the data? If it is the primary action, "Go to eBenefits" would be the button text, intro'd with "to add a dependent or change a dependent's status".**

**This action may not need be a button: https://marcysutton.com/links-vs-buttons-in-modern-web-applications**

**https://uxplanet.org/7-basic-rules-for-button-design-63dcdf5676b4 - this looks less like a button and more like a callout.**

**The VA design system would lead me to think this should not be a button, and instead be presented as a link: https://design.va.gov/components/buttons#guidance**
**_"Generally, use primary buttons for actions that go to the next step and use secondary buttons for actions that happen on the current page."_ As well as, _"Button labels should be as short as possible…"_.**
This is part of the page template used across the site but the button here is going to take the user back to eBenefits until we get the rest of it moved.

**Page 2 - loading & error states** 
**- The right rail content seems out of context here. Possible to load with the relevant content?**
Right Rail item 1 is addressing when these actions should be taken - when there is a change in status.
Right Rail item 2 is addressing how to get help.
Right Rail item 3 is addressing where to ask questions.

**Page 3 - end state / future, 686 brought into va.gov - Thinking ahead**
**- Apply to add depend — not sure about context and placement, seems it might fit better under the Dependents on your award heading**
The `apply to add dependent` button is to both bring in a new dependent and/or adjust existing statuses so the button language may change.  We should note that the button color may change as well given the other uses across the site.  It's efficacy being in the on awards section is diminished as they are already on award, and dependents not on an award might not be able to be added.  We feel having it at the top makes the most sense at this point. 

**- Options available to Change Status - how complex is the interaction? Is it necessary to put them in a next step? Might the options be presented here, and then confirmed?**
No, the interaction involves bringing the user into the 686 form itself.

**Page 4 - My VA, authexdp / Future State**
**- Green button - is this the primary action on the page? Consider this might be an additional info show/hide.**
MyVA page is outside our scope, but the other one sends the user to eBenefits as of right now.

**- What is the X Remove for?** 
This allows the user to remove that panel but we did not design this page.  This is in our mockup to show a potential inbound link.

_Trevor's accessibility feedback from design intent review 1/3/2019:_

**Page 2 of 8**
**- Was there a sentiment to show the entire social security number? The previous iteration X'ed out all of the number except last four. Maybe I'm reading too much, but I trend toward private, and don't like to expose things like SSN/EIN unless it's user-initiated.**
⭐️ Good idea, we agree and will move towards that.

**- Dependents... feels like an `<h2>` and the persons' names should be `<h3>` so we get a good nesting going on.**
⭐️ Yes, agreed: title is `<h1>`, Dependents is `<h2>` and the person's name is `<h3>`.  We will make sure that convention is followed in staging.

**- Sidebar headings should be `<h3>` on first glance. These aren't nested inside the `<h2>` so they should be presented after them in screen reader Heading menus.**
Ok. These are separate React components that should be `<h3>` and will behave as expected (display at the end on mobile)

**Page 4 of 8**
**- When the loading indicator drops out (data is returned) we could set focus on the first paragraph block. I think the `<h1>` should already have announced to screen readers, so the next logical thing is the "Below is the information we have..." block.**
⭐️ Got it, will bring it up with Frontend.

**Pages 5 and 6 of 8**
**- We will want these alerts to announce themselves to the page right away when they're presented. If they're not available on first load, IE, they come back with the API error code, we will probably want to break in with a `role="alert"` so the screen reader breaks in and reads them.**
**- If these alerts are part of the initial page load, we may not need to interrupt the regular page read. User testing with assistive technology users will help guide us to the right balance.**
⭐️ Got it, will bring it up with Frontend. We will also consider `aria-live-assertive` and `aria-live-polite` tags.

**Page 7**
**- `Remove` link will need an `aria-label` or `<span class="sr-only">` text to describe what we're removing. This is for screen readers, so when users focus the link, they'll hear "Remove Disability Compensation benefit" instead of "Remove..." with no context.**
This on MyVA page and out of our scope.  Again, we included this page to describe an inbound page.

**Page 8**
**- `Change Status` link will need an `aria-label` or `<span class="sr-only">` text to describe what we're changing. This is for screen readers, so when users focus the link, they'll hear "Change Status for Pat Smith".**
⭐️ Got it, will bring it up with Frontend.

**Comment by sporeboy** [comment]
Actionable input implemented in View Dependents design. https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/
