### ISSUE TITLE
[Research] Prep Tasks - VA.gov homepage redesign iteration - usability 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#46654]
## High Level User Story/ies
As a Veteran, I need a quick and efficient way to navigate VA.gov that supports doing top tasks. This research initiative will validate the September 2022 iteration of the redesigned VA.gov homepage. 

## Tasks

- [x] Share research plan and conversation guide with Shane for approval and recruiting
- [x] Organize observer sign-up sheet and communicate with observer list (@mmiddaugh)
- [x] Make note-taking spreadsheet--for places with multiple links (e.g., health care in Popular and benefit hub), track how many people used which one
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots
- [x] Send thank you notes to pilot participants
- [x] Revise conversation guide
- [x] Send instructions to observers (@mmiddaugh)
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [x] Other tasks as needed

## Acceptance Criteria

- [ ] Completed prep tasks in support of research actions

**Comment by cindymerrill** [comment]
Scheduled 2 pilots

**Comment by cindymerrill** [comment]
All ready to conducts pilots on Monday

**Comment by cindymerrill** [comment]
All prepared for research sessions next week
