### ISSUE TITLE
[Research] Draft conversation guide - VA.gov homepage redesign iteration - usability

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#46653]
## Issue Description
Based on the research plan created in #46662, produce a conversation guide in support of the moderated usability of the September 2022 iteration of the redesigned homepage

## Tasks

- [x] Draft conversation guide
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback

## Acceptance Criteria

- [x] Initial conversation guide drafted
- [x] Share with PM/PO for review
- [x] Draft conversation guide available for review and use in Veteran User Recruitment for this initiative.

**Comment by cindymerrill** [comment]
Finished drafting [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/2022-09-redesign-usability-round2/conversation-guide.md), shared with a UX team member and Michelle for review.

**Comment by cindymerrill** [comment]
Updated per feedback from Michelle, then shared with PO Dave to review.

**Comment by cindymerrill** [comment]
Reviewed and approved.
