### ISSUE TITLE
[Design] "Need Help" content audit and wireframe update

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#46650]
## Tasks
- [ ] Audit and verify the "Need Help" content in all user flow: PCI in-person, PCI telephone, CI. 
- [ ] Collab with content team (e.g., Danielle)
- [ ] Update wireframes
- [ ] Create a FE bug ticket if needed

**Comment by loripusey** [comment]
@zach-park is this ticket still needed since we just recently updated the Needs Help section?
cc: @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Ya-ching had some findings from the spanish research study that could warrant some improvements. I would keep this in the backlog. Moving forward, it's less about an audit and more about improvements. It's a carryover from [this ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48394).

**Comment by loripusey** [comment]
ok, thanks, I'm assuming we should wait until Ya-Ching is back from being out to pull in

**Comment by loripusey** [comment]
no longer needed, closing
