### ISSUE TITLE
Move FSR API submission logic to background job

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#46667]
## Issue Description
The increased amount of API requests (VBS + SharePoint) have increased the latency once an FSR is submitted for the combined experience. Ideally these operations will run in the background while what the client needs (PDF URL) is provided right away.

---
## Tasks
- [ ] Move API submissions to worker
- [ ] Call worker from model

## Acceptance Criteria
- [ ] FSR Submission requests have reduced latency
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over to sprint 83 due to incoming requests and VBMS incident work

**Comment by ScottyRJames** [comment]
Rolling over due to complex background worker testing to assure no prod breakages

**Comment by ScottyRJames** [comment]
Need FE changes to account for lack of statuses - will be resolved with [49110](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/49110)
