### ISSUE TITLE
[Research] Draft research plan - VA.gov homepage redesign iteration - usability 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#46662]
## Issue description
This research initiative will evaluate the success of the September 2022 redesign iteration for the VA.gov homepage toward the following desired user outcomes

- Veterans, caregivers, family members, survivors and service members are able to access tools and processes quickly and easily to learn about and manage their benefits
- Veterans, caregivers, family members, survivors and service members have increased access to self-service tools through an elevated login funnel

## Background
The current VA.gov website was launched in 2018 and needed to be revisited, informed by 
- [Baseline Wayfinding Research on VA.gov | June 2021](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/home-page/research#baseline-wayfinding-research-on-vagov--april-2021)
- [Veteran Top Tasks UNMODERATED Survey | July 2022](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-findings.md#veteran-top-tasks-unmoderated-survey-findings)

Research was conducted in August 2022 to validate the usability of a redesigned version. These [findings from VA.gov Home Page Redesign Usability Testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-findings.md) were used to iterate on the redesign. The purpose of this current research cycle is to validate this latest design. 

## Goal
This research is to validate the new design elements in this latest iteration. 

## Primary areas of focus
For this research cycle, we are primarily interested in areas which have changed in this iteration. They will be examined in context with elements from the entire homepage, header or footer, because they may also provide a path for task completion. 

## Research questions
The following questions will be answered in the context of task-based scenarios:

Are participants able to easily and quickly initiate tasks from the homepage **using their smartphone**?
Does the homepage support **participants using assistive tech** in completing their tasks?

### Tasks should relate to the following (at a minimum)
- Login
- Signup CTA
- At least one task not displayed in the Common task list
- News 

### Recruitment  
Recruitment should be similar to that used for the VA.gov Home Page Redesign Usability Testing in August 2022, except 
- a smaller number of total participants will be needed
- stronger emphasis on participants using screenreaders and other assistive tech
- stronger emphasis on participants using their smartphones to access VA.gov 

### Observers
Invitations to observe research sessions will be extended to various stakeholders on the Web Governance Board (coordinated by Dave/Chris J/Michelle)

## Tasks

- [x] Draft research plan
- [x] Share plan with a UX team member, PM, PO, and incorporate their feedback

## Acceptance Criteria 

- [x] Initial research plan drafted
- [x] Share with PM/PO for review
- [x] Draft research plan available for review and use in Veteran User Recruitment for this initiative.

**Comment by cindymerrill** [comment]
Finished initial draft and shared with Michelle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/2022-09-redesign-usability-round2/research-plan.md

**Comment by cindymerrill** [comment]
Updated per feedback from Michelle, then shared with PO Dave to review.

**Comment by cindymerrill** [comment]
Reviewed and approved.
