### ISSUE TITLE
Return PDF details upon FSR submission

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#46671]
## Issue Description
To support the feature of a Veteran being able to download their PDF, we need to change the response value for the create route. The API can either immediately return a file object or the ID of the submission to fetch later.

---
## Tasks
- [x] Decide what's best approach for API return
- [x] Add PDF details to return

## Acceptance Criteria
- [ ] The PDF download feature is maintained for the combined experience 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over to sprint 83 due to incoming requests and VBMS incident work
