### ISSUE TITLE
Generate staging API key for VBS 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#46675]
## Issue Description
For VBS to authenticate with VA.gov we need to generate an api key for them to include with the request and securely transfer it to them.

---
## Tasks
- [ ] Generate API key
- [ ] Pass key to VBS team

## Acceptance Criteria
- [ ] VBS has new API key
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
