### ISSUE TITLE
Determine structure of new MCP statements

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#46677]
## Issue Description
Communicate with VBS to determine what the JSON body will look like for new MCP statements 

---
## Tasks
- [ ] Discuss options with VBS 
- [ ] Assure app will support JSON structure

## Acceptance Criteria
- [ ] We know what the request JSON body will look like for new MCP statements
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
