### ISSUE TITLE
[eFSR] Veteran Contact Information Enhancement

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46673]
## Issue Description
Update contact information page so editing takes user to new page and back to view page when updated. 
[Mockup reference](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150957712/specification/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/6370bee3-1e03-4c3b-944b-45dbc4957442)

---
## Tasks
- [ ] Add "page jump" functionality for phone number
- [ ] Apply functionality to email and mailing addresses

## Acceptance Criteria
- [ ] Veteran contact information page matches mockup and is functional. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Sliding back to the ready column with contract change. The following branch has the updated contact information pages that update the profile information, but still needs to be updated with user/e2e testing. Form data also needs to be updated with profile contact info when updated, or pulled from profile during the transform step, so the latest data is used on submission.

**Comment by HeatherRienks** [comment]
@Dr-Pongo - any updates on this?  Thx!

cc:  @denisecoveyduc

**Comment by Dr-Pongo** [comment]
@HeatherRienks Sill a WIP! Mocking and testing the profile data locally has been a challenge for me, but I'll expect my PR to be in by the end of the day!

**Comment by HeatherRienks** [comment]
@Dr-Pongo - any update on this? Thx!

cc: @denisecoveyduc

**Comment by Dr-Pongo** [comment]
PR with changes has been merged!
