### ISSUE TITLE
Authenticate VBS on new statement route

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#46676]
## Issue Description
Once VBS has API key to include with their requests for new statements we need to authenticate them.

---
## Tasks
- [ ] Store key to match against
- [ ] Validate in controller

## Acceptance Criteria
- [ ] The new statements route is app authenticated 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over to S83, work is done but need to fix test.
