### ISSUE TITLE
[cFSR] Dependents page enhancements 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46685]
## Issue Description
Remove existing dependents list loop and implement new input number of functionality. 
[Mockup reference](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022114/specification/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/cd3868ab-b7d7-4714-87ff-a0d74f41ffb6)

---
## Tasks
- [ ] Update dependents page with FSR enhancements

## Acceptance Criteria
- [ ] New dependents page(s) are functioning as anticipate, and match mockup
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
a duplicate of #46686
