### ISSUE TITLE
[cFSR] Add FSR Enhancement Feature Flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46689]
## Issue Description
FSR enhancement effort will need to be thoroughly tested before going live, so we need to implement a flag to show/hide these features separate from the existing combined FSR flag. 

---
## Tasks
- [ ] Implement new feature flag for FSR Enhancements

## Acceptance Criteria
- [ ] New feature flag is implemented 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Closing, was completed on 9/7/2022.
