### ISSUE TITLE
[eFSR] Vehicle Page Enhancements

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46688]
## Issue Description
This design should follow [Mini Summary styled input](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=87471762-a55a-4514-88d1-4cb4b90f7fb6) but include the New Vehicle addition page design:

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/5aa6844b-5f1d-4734-95cd-9b6ace4a0370)

Remove existing vehicles list loop and implement new input number of functionality
[Previous mockup reference](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965/specification/sitemap?mode=i)

---
## Tasks
- [ ] Add the following pages:
  - [ ] Mini Summary page
  - [ ] New Vehicle inputs
- [ ] Show list in final review page
- [ ] Update efsr specific e2e testing
  - [ ] Include item removal and addition

## Acceptance Criteria
- [ ] Page matches design and functionality
- [ ] All new and existing tests are passing
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Updated post midpoint review and discussion with design!
