### ISSUE TITLE
Design | Profile | BAI |Conduct UAT

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46699]
## Background

We need to conduct an internal UAT/usability testing for  BAI. We will conduct this plan in production using the Profile teams production accounts.

## Tasks
- [ ] Conduct UAT/usability sessions

## Acceptance Criteria
- [ ] Sessions are conducted/complete
- [ ] Complete summary of findings
