### ISSUE TITLE
Design | Profile | BAI | Conduct UAT

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46700]
## Background

We need to conduct an internal UAT/usability testing for  BAI. We will conduct this plan in production using the Profile teams production accounts.

## Tasks
- [x] Conduct UAT/usability sessions
- [x] Complete summary of findings

## Acceptance Criteria
- [x] Sessions are conducted/complete
- [x] Summary of findings is complete

**Comment by cgednalske** [comment]
Hi @SKasimow -- closing this! 

And linking to our UAT [findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/uat/uat-findings.md) and [notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/uat/UAT-Notes.md).
