### ISSUE TITLE
[Design] My VA Audit: Review Nametag Design and Logic

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#46714]
## Background
Review the Nametag section design on My VA. Determine if there is any logic that can be simplified or designs that can be revisited. 

## Tasks
- [x] Review Nametag design and logic
- [x] If any updates are needed, provide information to PM/APM to create follow up tickets
- [x] Determine what (if anything) needs to be done in relation to [#389](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/389)

**Comment by aagosto90** [comment]
I don't think that we can or should simplify the logic for the name tag any further...my only question is @tmitchellgcio is there ever a scenario where we can't tell if the user has a disability rating? In the audit we only accounted for if the user has a disability rating but we can't show it so we show a link for "View disability rating" ![Screen Shot 2022-09-19 at 2.03.53 PM.png](https://images.zenhubusercontent.com/61f2dbbca50e2e3e2b4d0a11/dbe1265f-8c9c-487e-877b-ae8977a5ba9c)

**Comment by tmitchellgcio** [comment]
In the event we can't tell, like an error or something it just gives the View disability rating link. It's basically default. I think even mine says it and I have no disability. I can double check
