### ISSUE TITLE
[UX] Update Product Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46723]
## Description
Update various product artifacts, as necessary, based on the feature release.

## Tasks
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [x] Update the Poster
- [x] Update user flow diagrams, as necessary
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov

## Acceptance Criteria
- [x] Product Guides are up-to-date (content & screenshots)
- [x] Poster is up-to-date
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/qeOEgjk)
- [x] R&D articles are up-to-date

**Comment by benbrasso-agile6** [comment]
Documents in drive - https://drive.google.com/drive/folders/1Tzs3clWp_PtTg5GKcMrCdgR1B-Ob58Ne

Published pre check in guide to git - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md

**Comment by benbrasso-agile6** [comment]
@loripusey i'm moving this to closed

**Comment by benbrasso-agile6** [comment]
@zach-park see comments here about user flows - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/46721

**Comment by zach-park** [comment]
The user flows is updated on [abstract collection](https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?sectionId=4d7e94e4-99ca-4cbd-a8f2-84f7d22589e9) and [sketchcloud](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/dlPpYa9). 
@benbrasso-agile6 , @loripusey 

![Pre-check-in user flow (Read-only) for user guide.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/88b3aa7a-912e-437a-81d4-9bd5bb71b4b3)

**Comment by benbrasso-agile6** [comment]
@zach-park were you not doing anything with an annotation that was discussed here 

https://dsva.slack.com/archives/C042CTX201F/p1662992203002289

**Comment by benbrasso-agile6** [comment]
I'll need to re-add the error pages to product guides when I get a moment

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 , the user flow is updated to include the link text for appointment confirmation steps: 
https://share.goabstract.com/2b4102c7-cca4-40d6-9cd2-add6ab199478?sectionId=4d7e94e4-99ca-4cbd-a8f2-84f7d22589e9

**Comment by benbrasso-agile6** [comment]
Looks good thanks

**Comment by benbrasso-agile6** [comment]
Made a couple small tweaks to pre check in product guide. [Published to Git ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md)
