### ISSUE TITLE
BE - Auth Profile - Military Service - Handle missing service history end date

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#46724]
## Background
It is possible for a veteran to have an open-ended military service episode that is missing an end date.  If an end date is missing, the termination code can be used to determine whether the episode is valid or if a data integrity issue exists. [More details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46087).

## Tasks
When military episode is missing an end date with a termination code not equal to "W":

- [ ] The API should return an error message with the military episode.
- [ ] Log the error in Sentry.

## Acceptance Criteria
- [ ] Test the scenario with a missing service end date and a termination code not equal to 'W'.
