### ISSUE TITLE
Determine new content for footer link to Access to Care page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46732]
## Issue Description
Public Websites was asked to change a link in the footer and we need to provide them with new text for the link.

The current link is **VA health care providers** under the VA resources section.

That link should now point to this page: https://www.accesstocare.va.gov/, which means the text should be updated. 

Once we have our final content, we should have Danielle review before posting in the intake request ticket. 

## Tasks
- [x] Rework text for link (Katherine)
- [x] Review (Laura)
- [x] OCTO-DE review (Danielle)
- [x] Post final content in intake request ticket #46237

## Acceptance Criteria
- [x] Public Websites has final text for new link in footer

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, 

The team brainstormed a few options for Public Websites' request.   They're asking us for footer link text that would point to [](https://www.accesstocare.va.gov/) (instead of the current link to https://www.accesstocare.va.gov/OurProviders). 

We wanted to get your input since this is related to health care. 

Here are the ideas for link text we threw out this morning. Let me know your thoughts.  
 
- VA health care performance data

- Access and quality data 

- VA health care data 

- VA health care performance

- VA facility performance 

- Quality of VA care

**Comment by DanielleThierryUSDSVA** [comment]
Hi @katherine-fung! Thank you for this. Following up from our slack conversation.

I think we could go with this:

VA health care access and quality

Reasons:

- We definitely need "health care" in there so it's clear this is health care-specific and not broader VA.
- We need to align with the main keywords of the page's H1 ("access" and "quality") and I think we want both so that we're not implying that it's one or the other.
- While "data" is a key component, there's also other information (like provider search) so I want to make sure we're not implying it's only data. I thought about "information" but I think that's just too long. So I think we're okay without any such word.

Thoughts?

**Comment by katherine-fung** [comment]
Those are great points, @DanielleThierryUSDSVA. I think "VA health care access and quality" works well. 

Thanks so much for your input on this one! I'll update Laura, and post the wording in the intake ticket.

**Comment by RLHecht** [comment]
Thanks so much, Katherine! Closing.
