### ISSUE TITLE
Do we need to change 15 mins after appt time to 10 mins

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#46743]
## Description 

In talking about the idea of redirecting pre check in to day of check in, we started to talk about when to do this. E.g., 30 mins before and 15 mins after. But, @benbrasso-agile6 brought up the point that maybe we decided to change the 15 minutes to sooner to take into account the time it takes a Veteran to complete check in. We had been talking about changing it to 12 or 13 minutes. However, @acrollet noticed that this was changed to 10 mins quite some time ago. 

So, the question is, 1) are the above assumptions correct, and if so, 2) is it worth updating all of our design and product artifacts to reflect 10 mins after vs. 15 mins after. It might make sense to keep communicating the 15 mins, which gives Veterans a "5 min buffer." 

Something to think about. 

[Here's more information about changing it to 10 mins](https://github.com/department-of-veterans-affairs/chip/blob/28ca395c31d838358a6502e3cb01edbf8d125c65/layers/utilities/nodejs/dateTimeFormatters.js#L11
)

## Tasks

- [x] Read the ticket referenced
- [x] Confirm assumptions here are all correct
- [x] Make decision 
- [x] Create tickets and/or identify next steps 

## AC

- [x] Tickets read
- [x] Decision made 
- [x] Ensure all CIE team knows the decision (to avoid this popping up again)
- [x] Create tickets or identify next steps, if needed

**Comment by benbrasso-agile6** [comment]
Decision: CHIP is currently set to 10 mins to take into account the time it takes to complete the check in process for the Veterans. Therefore, let's keep this as is.
