### ISSUE TITLE
BE - Auth Profile - Military Service - Include Academy Attendance

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#46744]
## Background
Currently, the profile military history does not include military academy attendance.  This data is available from VA Profile.

## Tasks
- [x] Update the `/v0/profile/service_history` endpoint to include military academy attendance in the response.
- [x] Add feature flag for displaying military academy attendance.
- [x] Create test user that has military academy attendance records.

## Acceptance Criteria
- [x] Test user with military academy attendance in staging environment.
- [x] Have Michael Richard test his account in production to make sure his academy attendance is displayed.

**Comment by tpharrison** [comment]
@Samara-Strauss @SKasimow 

VA Profile returns military academy episodes and military service episodes in separate lists.  I'm assuming that we want everything combined into a single chronological list.  Just want to make sure.

**Comment by Samara-Strauss** [comment]
Yes, a single list works for me.

Do we have a staging user for testing? If not, we'll likely need VA Profile to help us set up one. They'll be amenable to do that, I'm sure, though they are out for PI planning next and likely wouldn't get to it until after that.

**Comment by tpharrison** [comment]
@Samara-Strauss @SKasimow

I spoke with Nate Paulus from VA Profile and he gave me some staging users that have academy episodes.  However, all of the academy episodes have values like 'Army', 'Navy, 'Coast Guard'.  I would expect to see things like "U.S. Military Academy", "U.S. Naval Academy", etc.  

I asked Nate if this is something we need to worry about in production and he directed me to Dan Ramunda who confirmed that we'll probably see the same data in production.  Here is his response...

> _So if you are pulling the ServiceAcademyBio, you will see the same data in production.  The data field passed to us from DoD is the branch of service. An academy assignment is a certain type of record combined with the members whole military history.  So my assumption is that if it is a service academy type record and we have the military branch, they did not feel the need to name the academy.  If you are using that bio, then perhaps you can use the service branch to “calculate” the academy?_

This seems like it will be confusing for end users.  For example, a veteran might see "Army" instead of "U.S. Military Academy".  I'm not planning to add any "calculations" or "mappings" at this point.  I think a better approach is to wait and see what kind of data is in production.  There will be a feature flag on this so maybe we can test it in production with Michael Richard's account since we know he attended the Air Force Academy.

**Comment by SKasimow** [comment]
@tpharrison - I agree with this approach

**Comment by Samara-Strauss** [comment]
@tpharrison can you share which staging users you are using to check this? 

Also, I am OK with testing with Mike's data and seeing what he says about it. I personally think it's fine and better than having nothing, but we should definitely do some user testing with Mike to confirm.

**Comment by tpharrison** [comment]
@Samara-Strauss @SKasimow 

The following users have academy attendance records:
- User 100
- Users 121 - 124

There is a feature flag called `profile_show_military_academy_attendance` that needs to be turned on to view academy attendance.

Academy attendance records are returned in the same list with military service records.  Each service history record has a `service_type` field that is either `Academy Attendance` or `Military Service` to distinguish.  

The values for an academy record look like `Army`, `Navy`, `Marines`, `Air Force`, and `Coast Guard` so until the FE is updated, you won't be able to tell the `service_type` when viewing the profile; you'll have to inspect the JSON response.  These values will be the same in production, so we'll need to discuss how best to display whether a record is military service or academy attendance.

I've asked for the list of possible values and here is what was sent (includes military and academy):
- Army
- Navy
- Marine Corps
- Air Force
- Coast Guard
- Space Force
- Foreign Army
- Foreign Navy
- Foreign Marine Corps
- Foreign Air Force
- Foreign Coast Guard
- Office of the Secretary of Defense
- Public Health Service (PHS)
- Commissioned Corps of the National Oceanic and Atmospheric Administration
- Not applicable
- Unknown

If we decide to add mapping, I can map a subset of the above values for academy attendance records and for the rest append `Academy` or something like that.  Or we can just display the service type.

Here is what I can map so far....
```
Army        -> U.S. Military Academy (USMA)
Navy        -> U.S. Naval Academy (USNA)
Air Force   -> U.S. Air Force Academy (USAFA)
Coast Guard -> U.S. Coast Guard Academy (USCGA)
```

@SKasimow - Can you set up a time to meet with Michael Richard so we can see what his history looks like in production?

**Comment by Samara-Strauss** [comment]
Thanks for this, @tpharrison! Can you clarify what the plan is at this point? Do we need to bring in a designer to help decide next steps? It sounds like there are a few things we could do. Are we waiting to see what Mike Richard sees before determining next steps?

**Comment by tpharrison** [comment]
@Samara-Strauss I think we should get a designer involved.  We don't need to wait to see what displays for Mike Richard.

**Comment by Samara-Strauss** [comment]
OK, you and @SKasimow should talk about what questions we need a designer to answer so we can get Liz or Christina involved when they have bandwidth. @SKasimow once you and Tom chat about designer needs, can you add a ticket to the backlog? If Liz or Christina has bandwidth in this upcoming sprint, great! If not, let's schedule for the following sprint.

**Comment by SKasimow** [comment]
Yes...will meet with Tom when he returns.

**Comment by Samara-Strauss** [comment]
Now that my brain is back online and no long in Friday-mode, I've had time to do a little more thinking about this. I want to make sure that we *should* pursue this work, not just that we can. Here is what I understand so far:

- Right now, we get `service_type`, but we don't distinguish between `Academy Attendance` or `Military Service`. Going forward, we have the opportunity to do that.
- However, even if we turn on `profile_show_military_academy_attendance` what we get back from the backend doesn't give us meaningful frontend data so that the user could easily distinguish between academy or military service information. So, we may get back `Academy Attendance = Army` or  `Military Service = Army`, but what the user sees is just going to be akin to what we have now regardless of `service_type`, eg. something like  `United States Army [Dates]`. 
- So, we need to add some sort of translation in order to be able to show meaningful data re: academy attendance. Is that correct?
- Question: How reliably can we translate the military academy information into the right data? I'm aware of the 5 major academies, but there are other military colleges, so I wasn't sure if that could potentially be included in that data.

Mostly, at this point, I want to make sure we fully understand the problem and what we would need to do in order to make sure  this work is worth the level of effort.

**Comment by Samara-Strauss** [comment]
@tpharrison did you mean to close this ticket?

**Comment by tpharrison** [comment]
@Samara-Strauss - oops!  sorry moved over the wrong ticket.

I understand your concerns.  We should probably discuss this tomorrow, but here are my answers in the meantime...  

> So, we need to add some sort of translation in order to be able to show meaningful data re: academy attendance. Is that correct?

Yes - it looks that way.  If not mapping, then at least show a visual that indicates whether the record is academy attendance or military service.

> Question: How reliably can we translate the military academy information into the right data? I'm aware of the 5 major academies, but there are other military colleges, so I wasn't sure if that could potentially be included in that data.

I think this depends on the VA Profile team.  The mapping I outlined above only includes mappings for what I know so far.  We'll need to speak with the VA Profile team to see if they can provide mappings for the other values.  If we end up deciding on this approach, the effort should be about 2-3 points.

**Comment by tpharrison** [comment]
@Samara-Strauss The list above is the complete list of possible values according to Nate Paulus.  The list is used for both academy attendance and military service.  For academy attendance records, he confirmed that the following values could be mapped but wasn't sure about the rest of the values in the list.

```
Army        -> U.S. Military Academy (USMA)
Navy        -> U.S. Naval Academy (USNA)
Air Force   -> U.S. Air Force Academy (USAFA)
Coast Guard -> U.S. Coast Guard Academy (USCGA)
```

For example - if the record is of type "academy attendance" and the value is "Army", we can map the value to "U.S. Military Academy (USMA)".

I'll follow up with Nate this morning to confirm the list and possible mappings and let you know what he says.

**Comment by Samara-Strauss** [comment]
> I'll follow up with Nate this morning to confirm the list and possible mappings and let you know what he says.

Thank you! Keep us posted. Once you've confirmed, I think we can make a final decision about how to proceed. And thanks for your patience in helping me process this and make sure I understand what we are working with.

**Comment by tpharrison** [comment]
I asked Dan Ramunda about mapping the values that are in VADIR.  His response....

> _Hi Tom - there is no mapping in VADIR.  We have very little information from DoD regarding academy attendance, and what you see in the Bio is all we get.  The data in production only maps to the four top mappings you list above. I don't know what else we could do._

**Comment by tpharrison** [comment]
I enabled the feature flag for Michael Richard in production and @SKasimow and I had him screen share his service history.  We were expecting to see his academy attendance from the Air Force, instead, no records were returned.

MIchael is going to verify his service history records in VADIR so we can determine what he should be seeing.

**Comment by Mottie** [comment]
[Lighthouse's Benefits Reference Data](https://dsva.slack.com/archives/C8R3JS8BU/p1649702827450209?thread_ts=1649700446.433219&cid=C8R3JS8BU) endpoint (`https://api.va.gov/services/benefits-reference-data/v1/service-branches`) provides a "more thorough" list of service branches

```json
[
  { "code": "AAC", "description": "Army Air Corps or Army Air Force" },
  { "code": "AF ACAD", "description": "Air Force Academy" },
  { "code": "AF", "description": "Air Force" },
  { "code": "AFR", "description": "Air Force Reserves" },
  { "code": "ANG", "description": "Air National Guard" },
  { "code": "AR", "description": "Army Reserves" },
  { "code": "ARMY", "description": "Army" },
  { "code": "ARNG", "description": "Army National Guard" },
  { "code": "CG ACAD", "description": "Coast Guard Academy" },
  { "code": "CG", "description": "Coast Guard" },
  { "code": "CGR", "description": "Coast Guard Reserves" },
  { "code": "MC", "description": "Marine Corps" },
  { "code": "MCR", "description": "Marine Corps Reserves" },
  { "code": "MM", "description": "Merchant Marine" },
  { "code": "N ACAD", "description": "Naval Academy" },
  { "code": "NAVY", "description": "Navy" },
  { "code": "NOAA", "description": "National Oceanic & Atmospheric Administration" },
  { "code": "NR", "description": "Navy Reserves" },
  { "code": "OTH", "description": "Other" },
  { "code": "PHS", "description": "Public Health Service" },
  { "code": "SF", "description": "Space Force" },
  { "code": "USMA", "description": "US Military Academy" },
  { "code": "WAC", "description": "Women's Army Corps" }
]
```

**Comment by Samara-Strauss** [comment]
@tpharrison is it a safe assumption that we would not be able to leverage the lighthouse information since our integration is through VA Profile?

**Comment by tpharrison** [comment]
@Samara-Strauss I don't think we'll be able to use this, but I will review the code (just out of curiosity).
