### ISSUE TITLE
Add new rates on Veterans burial allowance page-HOLD TO PUBLISH UNTIL 10/1/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46767]
## Issue Description
We need to add two new rates on the [How to apply for a Veterans burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) to go live on October 1, 2022. 

In the table under the H2 "What are the burial allowance amounts for a non-service-connected death?" we need to add a new row at the top showing the following:

If the Veteran died on or after Oct. 1, 2022: $300 burial allowance; $893 for a plot 

In the table under the H2 "What are the burial allowance amounts for a non-service-connected death if the Veteran was hospitalized by VA at the time of their death?" we need to add a new row at the top showing the following: 

If the Veteran died on or after Oct. 1, 2022: $893 burial allowance; $893 for a plot 

**These changes should go live 10/1/22**

Also note that there are current draft changes on this page that aren't ready to go live yet, so we'll need to revert to a past version to add this information in. Then once the page is published, we can add in the draft content again with these new rates as well and keep as a draft.

## Tasks
- [ ] Revert to a previous version 
- [ ] Update rates
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Revert to draft with unsaved changes and add in this content 
- [ ] Alert stakeholder changes are live (Randi)

## Acceptance Criteria
- [ ] Changes are live on the site
- [ ] The most recent draft version contains these new rates plus previous content that hasn't been approved yet

**Comment by aliyahblackmore** [comment]
Noting here that this page was **reverted to the 1/13/22 at 12:45pm version** (confirmed by Randi). Changes will be made to this version!

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! 

I reverted to the **1/13/22 at 12:45pm version** (confirmed by Randi) and updated the rates on that version.

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=864

**Comment by megzehn** [comment]
@RLHecht - this page is now published! 

http://preview-prod.vfs.va.gov/preview?nodeId=864

FYI, I haven't reverted the page back yet, because I wasn't 100% sure which version we wanted.

**Comment by RLHecht** [comment]
@aliyahblackmore could you revert to the draft that was originally the most recent before you made your changes? And then make sure to update that with the new content on the page? Thanks!

**Comment by aliyahblackmore** [comment]
Just updating here that this is on hold!

**Comment by megzehn** [comment]
Confirming that this has been copy edited and published! Thanks, @aliyahblackmore and @RLHecht!
