### ISSUE TITLE
Move Everything to EKS/Sunset old BRD

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#46779]
## Problem Statement 
EKS has been stated to be a pillar of the architecture approach that Platform is to build upon. It has been an ongoing effort for > ~12 months with progress being made in implementation and migration. The lack of priority leading to completion is prohibiting other improvements and capabilities that would provide a more rich and stable experience for development teams as well as end users. The completion of this initiative removes the current need to straddle the BRD and EKS line and move towards a more scalable and manageable approach to supporting the platform. Additionally, EKS provides the platform opportunities to innovate away from the monolithic approach currently in place and open doors to other architectures and technology stacks. This move also paves the way to address an improved maintenance model and CI/CD pipeline.

## User Impact
*How many users are being affected? What kind of user (VFS engineer vs. VFS designer)? What is this blocking those people from doing? What would fixing this problem allow the impacted users to do faster/better?*

## Where was this problem reported?
*Is it something that came to light because it was mentioned in many support requests? Was it found in research? Was it a theme of the satisfaction survey?*

## How well do we understand the problem?
*It’s ok if you don’t know but any context would be helpful if it is known. Is the problem that a previously agreed upon infrastructure decision is keeping us from utilizing a industry standard feature in our pipeline? Is the problem that OCTODE no longer has a research resource so we can’t support research in Collab Cycle anymore?*

## What is the acceptance criteria?
What services are on EKS? 
What needs to be sunset? 

## How should we measure success?
*What are the key performance indicators? What do we expect solving this problem to impact? How should we measure the impact (both where should we pull the data from and what should the calculation be)? Do we need to start the project by defining baselines or do they exist somewhere?* 

## TODOs
- [ ] Convert this issue to an epic

**Comment by mchelen-gov** [comment]
For this to cover the entire EKS migration effort, the AC needs to include deprecation of legacy BRD systems.

**Comment by andreahewitt-odd** [comment]
More standard well defined delivery format

**Comment by andreahewitt-odd** [comment]
Where this was reported: Platform has said our BRD isn't as robust or up to modern standards. Lots of overhead with maintaining current BRD.

**Comment by andreahewitt-odd** [comment]
Link to previous initiatives in "How well do we understand the problem?"

**Comment by andreahewitt-odd** [comment]
Add ac about jenkins

**Comment by andreahewitt-odd** [comment]
Edit AC to say vets-api is running on EKS in production

**Comment by laineymajor** [comment]
We've been including our notes from the meeting, and other questions/topics to cover, in [this confluence doc](https://vfs.atlassian.net/wiki/spaces/~834775922/pages/2374533369/VSP+Backend+Migration+to+EKS).

**Comment by laineymajor** [comment]
The name of this project was narrowed to 'vets-api' specifically. We are still planning to complete a discovery to better understand what is remaining on BRD (looking ahead at future work), but I want to make sure we are on the same page that this project is now narrowed from 'move everything to EKS' -> 'move **VETS-API** to EKS'. Making sure this scoping is accurate @td-usds @andreahewitt-odd @LindseySaari

**Comment by LindseySaari** [comment]
> The name of this project was narrowed to 'vets-api' specifically. We are still planning to complete a discovery to better understand what is remaining on BRD (looking ahead at future work), but I want to make sure we are on the same page that this project is now narrowed from 'move everything to EKS' -> 'move **VETS-API** to EKS'. Making sure this scoping is accurate @td-usds @andreahewitt-odd @LindseySaari

Yes, the scoping sounds accurate to me!

**Comment by laineymajor** [comment]
@td-usds can you endorse this epic? We'll then add it to the platform roadmap. Thanks! 
@andreahewitt-odd for visibility

**Comment by td-usds** [comment]
Linking in #43345

**Comment by laineymajor** [comment]
Updating AC to match the following, as reviewed with PO:
- [ ] Discovery for ['everything' remaining on BRD](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)
- [ ] `Vets-API` is running EKS on dev and handling dev traffic
- [ ] `Vets-API` is running EKS on staging and handling staging traffic
- [ ] `Vets-API` is running EKS on sandbox and handling sandbox traffic
- [ ] `Vets-API` is running EKS on production and handling production traffic
- [ ] The `Vets-API` specific portion of the BRD, including Jenkins, has been deprecated and replaced with GitHub Actions that tie into the delivery model for `Vets-API` on EKS
- [ ] A VFS team is able to deploy their own containerized workloads all the way through into EKS production, if they so choose, with their production traffic being handled by that deployment
- [ ] List of tests that can be automated post-release

**Comment by laineymajor** [comment]
Vets-apI migration with EKS to production began on April 4, 2023, with the target completion date of June 2, 2023. 
- Tech team 1 is currently ahead of schedule with the migration (~35% of prod traffic running in EKS)
- Working to resolve some slight latency issues that were noticed upon migrating feature toggles.

**Successfully Migrated:**
`/v0/search`
search type ahead
coverband
sidekiq.ui
`/v0/welcome`
Flipper UI
BGS `/debts`
BGS `/debt_letters`
BGS `/profile/ch33_bank_accounts `
BGS `/profile/payment_history `
`users#show `
`v0/sessions `
`v0/signin`
Sidekiq
Feature toggles [working to fix slight latency issues before proceeding to additional routes]

**Next up! Dates are estimates**
April 10 - /facilities_api/* 
April 10 - /v1/facilities/va
April 11 - Mobile routes, beginning with more latent routes
April 10/11 - Lighthouse

**Comment by annekerr49** [comment]
Schedule has been updated and looking to be complete in early May

**Comment by laineymajor** [comment]
We are at around 70% migrated to EKS.[https://app.zenhub.com/files/133843125/64865a5e-df89-40fc-9d2f-f440f314cbe2/download](https://app.zenhub.com/files/133843125/64865a5e-df89-40fc-9d2f-f440f314cbe2/download)

**Comment by laineymajor** [comment]
All AC have been met:
One note: added health checks so we can continue to monitor pod readiness
