### ISSUE TITLE
Improve Preview Environments for VA.gov Products

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#46783]
## Preview Environment Milestone Details

<details>
  <summary> Click to expand/Milestone 1 Scope & Feature List </summary>

### [Milestone 1: Proof of Concept](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47582) ###

**STATUS: Done** 

- **Planned Scope**
  - A proof of concept that demonstrates the potential for Preview Envr
- **Results**
  - **Proof of Concept** — Succeeded
  - **Support a WASA Scan**—Failed—We submitted the request for a WASA scan with the Milestone 1 Preview environment. ESECC told us that before the scan could be performed, there were a number of pre-requisite steps that needed to be completed, including resolving code scanning issues..

</details>

---

<details>
  <summary> Click to expand/Milestone 2 Scope & Feature List </summary>

### [Milestone 2: Unauthenticated PE Behind Socks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78082) ###

**STATUS: Done** 

- **Planned Scope**
  - A functional preview environment focused on allowing preview and testing of unauthenticated experiences. This includes a basic interface and can support usability testing.

- **Results**
  - Functional Preview Environment MVP—Succeeded
  - Allows testing of unauthenticated experiences—Succeeded
  - Support Usability Testing—Succeeded
  - *NEW* Support a WASA Scan—Failed—Not part of the planned scope of MS2, we were unexpectedly contacted by ESECC during development. They said we could proceed with the WASA scan request, with the understanding of addressing the previously called-out code-scanning and dependabot issues in the future. We resubmitted our request based on this, and as we proceeded further into the review, they said that they would need us to have authentication in place before they could perform the review.

</details>

---

<details>
  <summary> Click to expand/Milestone 3 Scope & Feature List </summary>

### [Milestone 3: Review Instance Replacement Candidate](https://github.com/orgs/department-of-veterans-affairs/projects/1459/views/7?pane=issue&itemId=83972003&issue=department-of-veterans-affairs%7Cva.gov-team%7C78084) ###

This milestone finalizes the core infrastructure for a complete Review Instance Replacement, and as such is the largest milestone of the initiative. When complete, this will enable the retirement of Review Instances, reducing costs and support issues while significantly improving development efficiency.

**STATUS: In Progress** 

- **Planned Scope**
  - Finalized infrastructure- Finalize complete infrastructure framework for the Review Instance Replacement Candidate
  - Implement authentication - Enable secure access for team members to use mock/staging test data behind SOCKS
  - Integrated external system connections allow for realistic testing
  - Developer tooling enhancements, including terminal access and improved workflows for use
  - Value: When complete, this will allow Review Instances to be potentially retired and removed from the our processes, reducing costs, support issues, and improving efficiency.

</details>

---

<details>
  <summary> Click to expand/Milestone 4 Scope & Feature List </summary>

### [Milestone 4: Publicly Accessible Preview Environments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78392) ###

Milestone 4 is currently scoped to include all critical path items that would block the ability to make Preview Environments publicly accessible. 

**STATUS: Not Started** 

- **Planned Scope**
  - Includes all prioritized features and polish
  - Supports User Acceptance Testing
  - Is publicly accessible

</details>

---

## Problem Statement 
The current approach to review instances has limitations that cause frustration for VFS teams and VA stakeholders in their efforts to test and preview their products. Examples of those limitations include the required use of SOCKS proxy which involves a level of technical fluency in its setup and use that most non-developers don’t possess, it also limits the tooling that can be used to conduct QA in review instances. Other limitations include that review instances are available for a limited window of time, they cannot be used to test on real mobile devices, and the developer workflow for preview of products that require combinations of multiple repositories is difficult. Additionally, review instances can only point to preprod/Staging environment so they cannot easily be configured to test against lower environments or synthetic data. Finally, better documentation and training on how to use review instances properly and fully would improve the experience.

*How might we make it easier for VFS teams and VA stakeholders to preview their features before it makes it to production (especially as we move to a model of continuous deployment)?*

## Hypothesis Statement
We believe that by implementing a new Preview Environment system on our new architecture that doesn't require SOCKS proxy, supports authentication, and provides feature parity with legacy Review Instances, we will achieve improved testing capabilities for VFS teams and VA stakeholders which will result in higher satisfaction rates, reduced support requests, increased usage of preview environments, better quality assurance before production deployments, and lower overall costs. 

---

## What is the acceptance criteria?
- [ ] Preview environments provide a mechanism for teams to test their new code combined with a snapshot of the va.gov  website
- [ ] Preview Environments can be configured to utilize SOCKS access when appropriate
- [ ] Preview Environments can be configured to be publicly accessible without SOCKS access.
- [ ] Preview Environments exist under the new EKS infrastructure
- [ ] Preview Environments are well-documented for users
- [ ] Users can test unauthenticated experiences
- [ ] Users can test authenticated experiences with Dev/Mock configs/data
- [ ] Users can test authenticated experiences with Staging configs/data
- [ ] Links to preview environments can be shared with team members and testers
- [ ] Full stack implementation with complete [va.gov](http://va.gov/) functionality
  - [ ] vets-website
  - [ ] content-build
  - [ [ Vets-api
- [ ] Preview environments demonstrate reliable/stable performance
- [ ] Support for testing features across repositories
- [ ] Terminal access for developers to troubleshoot issues
- [ ] Branch selection flexibility (including default branch override)
- [ ] Streamlined workflow for manually creating and managing preview environments
- [ ] Support for viewing and diagnosing errors/logs
- [ ] Functional login system for test user credentials
- [ ] Ability to configure preview environments for different test scenarios
- [ ] Support for usability testing and user acceptance testing sessions with stakeholders and/or veteran end users
- [ ] Support for automated testing within preview environments
- [ ] Provide monitoring/dashboard for overall Preview Environment usage and adoption
- [ ] Provide monitoring/dashboard for individual Preview Environment usage
- [ ] Documented process for reporting/resolving issues, and making feature requests
- [ ] Error rate monitoring to ensure reliability
- [ ] User satisfaction measurement mechanism

---

<details>
  <summary> Click to expand/collapse Preview Environment Background/Context </summary>

## Where was this problem reported?
*This problem has been reported everywhere (support requests, research, satisfaction survey). It's a common theme in the satisfaction survey [quarter to quarter](https://vfs.atlassian.net/wiki/spaces/AP/pages/1523580945/Customer+Satisfaction+Survey).*

## What do we *not* know about the problem space?
- How best to handle environment creation in the context of multiple repositories. Should they be created by PR within individual repo (such as `vets-website` and `vets-api`) or should there be a centralized repo that creates Preview Environments?
- Is there a network path that allows off-network (non-SOCKS) access while also connecting to preprod external integrations?
- If not, is there a minimal functionality that needs to be mocked to allow testing use cases?
- What authN/authZ systems are available and accessible to majority of VFS team members, POs, and stakeholders?
- What tools and application hosting systems (Codespaces, Tugboat, EKS, etc) are available and what limitations do they have?

## What (if any) research or discovery has been done?
Satisfaction survey [quarter to quarter](https://vfs.atlassian.net/wiki/spaces/AP/pages/1523580945/Customer+Satisfaction+Survey)
[VFS team's testing experience study - findings Q3 2022](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2344910881/Research+Results+QA+on+va.gov+-+Phase+1)
[VFS team's testing experience study - synthesis board Q3 2022](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1661381384653/8c7773959d0fea5aafc9136b114c61c5418638a6?sender=andreahewitt6355)

## Important Project Links
- [Project board](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/board?repos=133843125)
- [Confluence space](https://vfs.atlassian.net/wiki/spaces/TT4/overview)

## Technical Requirements
 - [ ] Does not rely on legacy BRD infrastructure (Jenkins)

## Not included in the AC
- [ ] Provisioning of test data or users in external systems
- [ ] Creation of external system mocks. *
- [ ] Preview Environments are created by PR
- [ ] Preview Environments are paused when not in use

**Note: may be affected by "Is there a network path that allows off-network (non-SOCKS) access while also connecting to preprod external integrations?"*

## How should we measure success?
- Fewer instances of Platform's testing ecosystem as a negative theme on the customer satisfaction survey
- Decline in support requests around review instances (need to start capturing baseline early) @JoeTice @pjhill 
- Increase in usage of preview environments (need to start capturing baseline early) @JoeTice @pjhill 
- Error rate and reliability of preview environments (actual equation for this will be reliant on implementation details)
- Take the pieces of the QA health survey that are relevant to review instances and compare to the recently completed survey
- 
## Projected Launch Date
Q3 2025

## High Level Milestone Status
| Epics | Scope | Status | Est Delivery | Notes |
| --------- | ----- | ------ | ------------ | ----- |
| [MS 1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47582) | Proof of Concept/WASA Scan | Complete | Jan 2024 | Proof of concept completed, could not support WASA scan |
| [MS 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78082) | MVP & Usability Tests | Complete | Jul 2024 | MVP Completed for unauthenticated experiences, usability testing completed, findings incorporated into future milestones |
| [MS 3](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78084)/ [MS3 UAT](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78086) | Review Instance Replacement Candidate | In Progress | Q2 2025 | Milestone 3 features are in development. Additional staffing being added to this effort, Mar 2025. |
| [MS 4](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78392) / [MS4 UAT](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78482) | Publicly Available Preview Environments | Not Started | Est Q3/Q4 2025 | Milestone 3 features are in development. Additional staffing being added to this effort, Mar 2025. |

**Comment by mchelen-gov** [comment]
Let's scope this to creation of preview environments. Preview environments should allow:
- Selected versions of codebases based on branches (i.e. `feature/xyz` from `vets-website` + `feature/xyz` from `vets-api`)
- Configuration of environment settings such as environment variables
- Ability to share access with non-developers (PM, designers, stakeholders, etc)
- Underlying infrastructure should not be based on legacy BRD

**Comment by JoeTice** [comment]
A few questions...

- The problem statement mentions '_there has been concern raised and incidents occurring due to environment promotion and the ability to reliably test_' - can you expand on the concerns and incidents that are being referred to here?
- Are there other specific 'areas of focus' that stand out to you as areas that could or should be considered as areas to improve, either in the near term or long term?
- In 'What is the acceptance criteria?' - Is access to previewing code in review instances limited in any way?
- In 'Not included in the AC' - Can you expand on what you mean on 'promotion of code throughout requirements'? And on why you don't think tht should be part of the acceptance criteria for this?
- In the additional comments from @mchelen-gov 
   - The comment calls out `vets-website` & `vets-api` - do we want to call out selected versions from other repositories?
   - Is there a reason that you want to scope this only to the creation of preview environments?
   - Can you provide some specific examples or use cases around the configuration of environment settings?

**Comment by andreahewitt-odd** [comment]
Does this only involve manual testing or automated testing too? Does this also include tooling to make automated tests? Potentially both

**Comment by andreahewitt-odd** [comment]
Are we conflating QA with review?

**Comment by andreahewitt-odd** [comment]
VFS teams aren't comfortable doing testing in a lower environment because they don't have the same data in dev and review instances.

**Comment by andreahewitt-odd** [comment]
We need to change the context to reviewing and testing in review instances -- what do we need to do for that piece to be effective. Getting data and information that is closely aligned to prod, easy access for anyone on the team.

**Comment by mchelen-gov** [comment]
How well do we understand the problem?
- Question: how should environments be created

**Comment by andreahewitt-odd** [comment]
QA health survey -- success metrics could be a portion of that so we can compare.

**Comment by andreahewitt-odd** [comment]
Change to: Increase in usage of review instances

**Comment by andreahewitt-odd** [comment]
Measurements of success might be affected by implementation details.

**Comment by andreahewitt-odd** [comment]
track usage in staging review - how often can we use these revised review instances

**Comment by andreahewitt-odd** [comment]
General bugginess of spinning up review instances -- will be dependent on implementation details.

**Comment by mchelen-gov** [comment]
^ success metric: error rate and reliability of preview environments

**Comment by mchelen-gov** [comment]
> * Configuration of environment settings such as environment variables
For MVP, can be accomplished by allowing developer terminal access.

> * Mocks for external services and data can be configured
For MVP, can be accomplished with existing developer tooling *if* we are able to connect to Staging/Preprod external services

**Comment by mchelen-gov** [comment]
@JoeTice 
> A few questions...
> 
> * The problem statement mentions '_there has been concern raised and incidents occurring due to environment promotion and the ability to reliably test_' - can you expand on the concerns and incidents that are being referred to here?
The example I am aware of is code being deployed to Staging for testing purposes, which was inadvertently released to Production

> * Are there other specific 'areas of focus' that stand out to you as areas that could or should be considered as areas to improve, either in the near term or long term?
Next steps for this project might be to build out more ready to use mocks for external services.

> * In 'What is the acceptance criteria?' - Is access to previewing code in review instances limited in any way?
Updated AC.

> * In 'Not included in the AC' - Can you expand on what you mean on 'promotion of code throughout requirements'? And on why you don't think tht should be part of the acceptance criteria for this?
I'm not clear on this, so it has been removed from AC.

> * In the additional comments from @mchelen-gov
>   
>   * The comment calls out `vets-website` & `vets-api` - do we want to call out selected versions from other repositories?
This should include all repos necessary to build a working VA.gov, likely that will involve `content-build` and some others.

>   * Is there a reason that you want to scope this only to the creation of preview environments?
Yes, because this specific piece of tooling is the farthest "left" in the development and QA process.

>   * Can you provide some specific examples or use cases around the configuration of environment settings?
No, so I changed the AC to allow developer terminal access.

**Comment by mchelen-gov** [comment]
@andreahewitt-odd
> they cannot preview products that require combinations of multiple repositories. 

This can be done, however it is a more complex workflow: https://depo-platform-documentation.scrollhelp.site/developer-docs/using-review-instances-to-preview-changes#Usingreviewinstancestopreviewchanges-Manualcreation

> Additionally, review instances don’t update when pushes are made to PRs and rely on mocked data/services so are not as useful as they could be.

This is incorrect, RI are redeployed on pushes and are pointed to Staging/Preprod environments per [docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/review-instances#Reviewinstances-ExternalServiceCallsvsMockedData).

Updated issue to reflect this.

**Comment by andreahewitt-odd** [comment]
@JoeTice @pjhill See Chelen's comments per your information around the problem statement ^

**Comment by annekerr49** [comment]
@pjhill  please can you give us a status update on this item?

**Comment by JoeTice** [comment]
![previewenvironments_20230103.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/75749a79-e570-40da-9934-c5836e9a3fb7)

**Comment by JoeTice** [comment]
Link to a documented plan in mural developed in Nov of 2022 that lays out the planned scope of MVP - [mural link](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666011911859/c0bf24d69db1638ccb56bf090acc1487ea9431c7?sender=uc4d00ea50beebdfad05a4846)

**Comment by JoeTice** [comment]
Team of Teams Slide: 4/11/23

![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/d0059b38-637f-46c4-88f6-a3a6a68ecc92)

**Comment by JoeTice** [comment]
Update: 4/18/23
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/ab40a938-5a42-4633-9017-77ad8409ce12)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/3a6e03a1-9977-406b-94ca-e5c4a743a505)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/c9828639-44ce-4d3f-8177-a6321fe8ae0e)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/459d5666-c81d-4fe6-8074-adb7edb517c0)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/22ef8c77-a80e-4c16-a160-1bf1845fc4cb)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/e503e4aa-50d0-494c-ab58-a4a372db7253)

**Comment by annekerr49** [comment]
No match for roadmap-DMC

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/9f4efd4c-61af-4914-a9cf-5d8f60c56066)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/fc37f0e7-63ab-41fa-88b9-d2c506950306)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/f126d7f6-cf80-4b28-939d-eeac601c9843)

**Comment by JoeTice** [comment]
![image.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/50126c8e-4a87-4359-9cc1-aec2719b2e86)

**Comment by EricaRobbins** [comment]
@JoeTice / @andreahewitt-odd - did this ship yet? If not, do you have a new Target Delivery Date?

**Comment by JoeTice** [comment]
Not yet, our next target milestone is April 2024

**Comment by AparnaNittalaUSDS** [comment]
Updated the target delivery date to Nov 30, 2024 based on the [Milestone 4](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/78482) (final testing for publicly accessible preview environment).

**Comment by annekerr49** [comment]
With Aparna leaving are we still on track to complete this effort in November?

**Comment by EWashb** [comment]
@jwoodman5 @andreahewitt-odd we need an update on this. If this ticket is too old for the current scope, let's either heavily edit or create a new one. I would like to see our milestones very well fleshed out here and is being tracked at the OCTO level. 

Perhaps this may even be a duplicate ticket at this point?

**Comment by EWashb** [comment]
@JoeTice @jwoodman5 can I get an update on this?

**Comment by jwoodman5** [comment]
@EWashb Message sent in slack and will have this updated accordingly.

**Comment by EWashb** [comment]
@jwoodman5 can I get an update on this before Wednesday? If we have another ticket I should be tracking instead you can link it here and I will clean up

**Comment by jwoodman5** [comment]
@EWashb [Here](https://github.com/orgs/department-of-veterans-affairs/projects/1459/views/7?pane=issue&itemId=83972003&issue=department-of-veterans-affairs%7Cva.gov-team%7C78084) is where the current work is being tracked at the epic level.
