### ISSUE TITLE
[cFSR] [bug] - Sentry error for numeric input fix

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#46792]
## Issue Description
Sentry is picking up on an issue where a `replaceAll` method is acting on an undefined object. 
`TypeError: undefined is not an object (evaluating 'e.replaceAll')`

This is most likely due to a fix that was put in place to handle commas in number input fields. 

---
## Tasks
- [ ] Update transform function so `replaceAll` has null checks to avoid the error. 

## Acceptance Criteria
- [ ] No longer receiving errors when values are null/empty

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
