### ISSUE TITLE
BE - Auth Profile - Contact Information - Address type not updating

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#46807]
## Background
A bug was discovered with using a military base address outside of the US.  The issue seems to be occurring in the BE code (either vets-api or VA Profile).   See ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/46388#issuecomment-1240972226 for more details.

## Tasks
- [x] Determine the cause of the issue.
- [ ] Document and apply fix.

## Acceptance Criteria
- [ ] Test in staging.
