### ISSUE TITLE
Publish Staging environment need-to-know info in VFS-facing space

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46816]
## User Story
 I am a VFS team member engaging in the Collaboration Cycle trying to complete my Staging Review but I'm not familiar with the limitations of Governance team accessing the various pre-production environments because there is no instructions for me to follow.

Assignee: @CherylEvans 
Peer Reviewer: @it-harrison 

## Description
In ticket #39530 and #46814, we documented the need-to-know info for Governance team preparing for Staging Review. We have published this information in an operational space (for Governance team use) and now need to publish in VFS-facing guidance on Platform Website. It is possible that the guidance will include additional information that is critical for VFS teams to know. 

## Tasks
- [x] Create a new page for this information to live. New page title TBD by assignee, but new page should live as a child page under Staging Review. See below screenshot.
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/faf9d862-af38-409d-8156-5a3af033de48)
- [x] Sitewide Public Websites team has recently published guidance for VFS teams on how to do a dark launch - see [Publish a CMS page only to Staging (using EntityQueue) in order to stage CMS + content-build + vets-website for viewing off of VA network ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#3-publish-a-cms-page-only-to-staging-using-entityqueue-in-order-to-stage-cms--content-build--vets-website-for-viewing-off-of-va-network). This guidance should be referenced in the new page.
   - Note: If Governance team has questions/concerns about this process, please reach out to Jill Adams on the #sitewide-public-websites Slack channel. [See thread.](https://dsva.slack.com/archives/C52CL1PKQ/p1663726139231149)
- [x] Link/reference this new page in the Staging Review touchpoints page.
   - Shira's 2 cents: I think it would make most sense to link this under Product Artifacts, where there's already a note about providing correct access information. Possibly rewrite the note.
- [x] Once published, create new Change History post notifying VFS teams of this new guidance on staging environments. Follow Platform communication playbook.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams ensure they are providing Governance team with everything they need for testing the VFS product in Staging Review. 

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian.  I have created a [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2388262920/46816+-+Cheryl+Draft+Copy+of+Staging+Environment+Guidance+for+VFS+teams) for the first assigned task above.  I have linked the page from the 2nd assigned task, into my new draft document.  I won't be able to complete the other tasks until you approve my draft page, and it is published in the location that Shira indicated in task 1.  If you have any questions, comments, or concerns, please dm me anytime and we can discuss.  Thanks Ian! :-)

**Comment by it-harrison** [comment]
@CherylEvans your draft page for the first assigned task looks good!

**Comment by CherylEvans** [comment]
@it-harrison I have created my [final page](https://vfs.atlassian.net/wiki/spaces/CC/pages/2396094469/Staging+Environment+Guidance+for+VFS+teams) and moved to its appropriate location.  I have referenced the new page on the [Staging review touchpoint page](https://vfs.atlassian.net/wiki/spaces/CC/pages/edit-v2/1810137181) under Product artifacts.

**Comment by CherylEvans** [comment]
@it-harrison All tasks are completed, and acceptance criteria has been satisfied.  Announcement made in Slack vfs-all-teams channel.
- [Staging Environment Guidance for VFS teams](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams)
- [Staging review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
