### ISSUE TITLE
Publish Staging environment need-to-know info in Operational space

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46814]
## User Story
 I am a Governance team member supporting the Collaboration Cycle trying to access the VFS teams' pre-production product in order to complete my Staging Review but I don't know the barriers and/or steps to take to access the various pre-production environments because there is no documented guidance for accessing said environments.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
In ticket #39530, we documented the need-to-know info for both Governance teams and VFS teams preparing for Staging Review. We now need to publish this information in an operational space (for Governance team use).

## Tasks
- [x] Wordsmith
- [x] Refine and update the document so that it flows well and is easy to understand/read.
- [x] Relocate to live alongside other Staging Review operational docs.
- [x] Link new guidance in [How to document feedback for Staging Review ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review)

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team has the information they need for accessing the various pre-production environments in preparation of a CC Staging Review

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@CherylEvans this sounds good to me. I think either title would be fine

**Comment by shiragoodman** [comment]
Here's my 2 cents. "Staging" is the name of a very specific environment for VA.gov Platform. It is an exact replica of the live/production VA.gov. Ideally, we should be holding our Staging Review with VFS teams in this environment, however it's not always possible for VFS teams. I don't think we want to refer to "Drupal/Static Content" or "review instances" as "Staging environments" because they're not! They're different environments. They're alternatives to the "Staging" environment. Does that make sense?

**Comment by shiragoodman** [comment]
When we say "staging", we're being very specific about where the code is available for testing/review. You may have noticed in the GH tickets, that I have referred to the other alternatives as "pre-production" environments. I want to make sure we're very careful with our language

**Comment by CherylEvans** [comment]
@shiragoodman @allison0034 I've made the changes per Shira's input.  Let me know what you think.

**Comment by allison0034** [comment]
@CherylEvans I agree with what @shiragoodman is saying. I almost wonder if it might be better to go by this outline:

- Types of staging reviews

  - Unauthenticated staging environment 
  - Authenticated staging environment 
  - Drupal/static content
  - Review instances

- Alternatives for Staging review per practice area

Also is it normal to have the ":" after each bullet?

**Comment by allison0034** [comment]
Looks good except I would put "Alternatives for Staging review per practice area" as its own bullet, it is different than the ones above it, does that make sense? So the same as "Types of staging reviews"

**Comment by CherylEvans** [comment]
@allison0034 I see what you are saying, but an "**Alternative**..." is still technically a **type** of Staging environment.  I think it is appropriate for it to fall under Types of Staging environments.  Make sense? :-)

**Comment by CherylEvans** [comment]
@allison0034 @shiragoodman Also, with the task "Relocate to live alongside other Staging Review operational docs.", I'm thinking it makes sense to reside under this umbrella in this [location](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1978859531/Staging+Review). Thoughts?

**Comment by shiragoodman** [comment]
I'm going to let you 2 figure this out. I trust you both! I do have one last comment - yes, there are types of "staging" environments but then there's also THEE "Staging environment" which is a very specific environment. So be careful how you word things.

**Comment by CherylEvans** [comment]
@allison0034 I moved it to the [location](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2377875498/Staging+Environment+Guidance) I thought made the most sense, reference my comment above, and slightly changed the verbiage to what I hope is a "happy medium" solution.  :-) 
Let me know your thoughts, and I can give it a tweak if necessary.

**Comment by CherylEvans** [comment]
@allison0034 Just linked the new guidance in your [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2372861953/46421+-+Allison+-+How+to+document+feedback+for+Staging+Review) "How to document feedback for Staging Review".  Hopefully, your okay with the placement and verbiage. :-)

**Comment by allison0034** [comment]
@CherylEvans looks great!

**Comment by CherylEvans** [comment]
@allison0034 Thank you!! :-)

**Comment by CherylEvans** [comment]
@shiragoodman Closing this issue.
