### ISSUE TITLE
VBMS Letter Debt Portal Audit 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#46824]
## Issue Description
On September 7, 2022  it was identified when VBMS updated the third demand letter (1214 form) additional Veteran data was shared on some letters from 08/17 to 09/06. This is one of a few letters Veterans can access when they have a VBA overpayment in the debt portal. A toggle switch has been added to production which enables the team to turn off access to the letters until the issue is resolved.

To understand the impact this issue has caused an audit needs to be done to provide estimates of the number of Veterans who accessed their letters during the time period, determine the identities for those Veterans that accessed and identify the number of  Veterans who downloaded the 1214 form document  

---
## Tasks
Provide estimates for the following:

- [x]  The # of Veterans that have accessed their letters during the time period ( **Estimated Completion 9/9**)
- [x] Identities for those Veterans that accessed (**Estimated Completion 9/13- 9/14**)
- [x] Identify number of  Veterans who downloaded the 1214 form document  (**Estimated Completion: TBD; Still under evaluation**)

## Acceptance Criteria
- [ ] Summarize and report on findings 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
