### ISSUE TITLE
[Beats] Investigate Agents Not Connecting

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46825]
## Description
Beats agents do not always connect to the CLS

## Background/context 
- https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/40935

## Technical notes
- Beats agents are installed
- Some instances will timeout trying to connect upstream

---
## Tasks
- [ ] Investigate why the beats agents are not always connecting
- [ ] Create follow-on ticket(s) if there is work to do for the infrastructure team

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
