### ISSUE TITLE
Remove references to Clayton Zook and Sean Sewell

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46837]
Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
Clayton Zook and Sean Sewell departed the Governance team on 9/7/2022. Their names will need to be removed from all Governance team guidance, documentation and templates.

## Impacted Artifacts
- [x] Governance Team Roster
- [x] Design Intent, Midpoint Review and Staging Review distribution lists
- [x] Platform Website/Collab Cycle/Contact Us
   - [x] [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
   - [x] [Research Checklist](https://vfs.atlassian.net/wiki/spaces/RD/pages/1958773011/Research+Checklist)

## Tasks
- [x] Review Platform Website and Confluence and locate all instances where Sean and/or Clayton's name are mentions. Document all pages where their name is mentioned above in Impacted Artifacts.
- [x] Remove Sean and Clayton from all Impacted artifacts listed above.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Sean and Clayton have been removed from all Governance team guidance and documentation

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
Looks good!

**Comment by briandeconinck** [comment]
@shiragoodman closing this issue!

**Comment by briandeconinck** [comment]
Wait -- re-opening until Platform website changes publish, just to be safe.

**Comment by briandeconinck** [comment]
Platform website changes published, *actually* closing this one now. @shiragoodman
