### ISSUE TITLE
Task: Change wording of sentence in alert box

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4683]
## User Story:
As a content editor, I need to ensure all pages adhere to our style guide so there is consistency across the brand.

In the alert box on the below pages, change the sentence "Start a confidential Veterans Chat" to "Start a confidential chat." @peggygannon I made this change in the alerts section in Drupal. It's not on the below individual pages.

- https://www.va.gov/family-member-benefits/
- https://www.va.gov/health-care/schedule-view-va-appointments/
- https://www.va.gov/disability/eligibility/ptsd/

## Tasks

- [x] Changes made - 1 hour(s) - @RLHecht 
- [ ] Review and publish - 1 hour(s) - @peggygannon 

## Acceptance Criteria:

* Live site shows update correctly

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@peggygannon I slacked Kevin W. about this. I see that you published the page and the edits are showing in Drupal in the alert area so I'm not sure why it's not showing on the live site. I'll let you know when I hear back.

**Comment by RLHecht** [comment]
@peggygannon In order for this to show correctly on the site, the alert needs to be changed from draft to published so this is ready for you to review and publish.

**Comment by RLHecht** [comment]
@peggygannon Can you please review and publish this? See the comment above this one that the alert needs to be changed to publish as well. Thanks!

**Comment by peggygannon** [comment]
@RLHecht I've changed the alert to "publish." I'll validate this tomorrow to see if the change got pushed to live site.

**Comment by peggygannon** [comment]
@RLHecht howdy! I just checked/validated the crisis alert and it's correct on
 https://www.va.gov/health-care/schedule-view-va-appointments/
https://www.va.gov/disability/eligibility/ptsd/


But I just realized the alert on family-member-benefit is worded slightly different and is a different alert. sorry, I need to go in and "publish" that 2nd alert.

**Comment by RLHecht** [comment]
These updates are validated on the live site. Closing issue.
