### ISSUE TITLE
[GitHub Action] Separate EKS AMI Build and Launch Template Update

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46834]
## Description
Building an EKS AMI and updating the launch template needs to be separate, or a flag added to prevent updating launch templates when unnecessary.

## Background/context 
- When testing the workflow, the launch template was updated unintentionally
- No reason for updating the LT to be tightly coupled with an AMI build

## Technical notes

---
## Tasks
- [ ] Update the EKS AMI build workflow to allow separation of building an AMI and updating the LT

## Acceptance Criteria 
- [ ] EKS AMI can be built independently of updating the launch template
- [ ] The launch template can be updated independently of building an AMI

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
