### ISSUE TITLE
[EKS,AWS] Upgrade EKS AMI to 1.23

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46840]
## Description
EKS AMI needs to be updated to version 1.23

## Background/context 
- We are currently running 1.22

## Technical notes
- 1.22 EOL May 2023

---
## Tasks
- [ ] Packer definition is updated to use EKS 1.23
- [ ] Review and update documentation, https://vfs.atlassian.net/wiki/spaces/OT/pages/1824588018/Packer

## Acceptance Criteria 
- [ ] New EKS 1.23 AMI is built
- [ ] Documentation is up-to-date
