### ISSUE TITLE
[EKS,AWS] Upgrade EKS AMI to 1.24

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46841]
## Description
EKS AMI needs to be updated to version 1.24

## Background/context 
- We are currently running 1.23

## Technical notes
- 1.23 EOL October 2023

---
## Tasks
- [ ] Packer definition is updated to use EKS 1.24
- [ ] Review and update documentation, https://vfs.atlassian.net/wiki/spaces/OT/pages/1824588018/Packer

## Acceptance Criteria 
- [ ] New EKS 1.24 AMI is built
- [ ] Documentation is up-to-date
