### ISSUE TITLE
[Application Hosting and Deployment] Enhancing 'Hello World' template

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#46845]
## Description

As a user who has minimal to no experience with Helm, it would be nice to see those files within `templates` directory to learn and modify to build on top of app being onboarded

## Background/context 

The first iteration of hello-world template has been developed and deployed. That being said, when the application gets uploaded into `vsp-infra-app`, it does not show all the layouts (ingress,external-dns, etc), within the template directory (is it abstracted and can be seen in Argo UI)

## Technical notes

[Helm chart file structure](http://jenkins.vfs.va.gov/job/utility/job/cert-expiry-scanner/671/console) -- template should be prepopulated with the information given

---
## Tasks
- [x] Update Github Action
- [x] Update Helm template
- [x] Test out changes are reflecting accordingly in Argo

## Acceptance Criteria 
- [x] Updated template works as expected

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
PRs have been merged to reflect new enhancement. Closing ticket
