### ISSUE TITLE
Task: Lowercase "benefit letters" in react widget

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#4685]
## User Story:
As a content editor, I need to ensure all pages adhere to our style guide so there is consistency across the brand.

Maintaining consistency with sentence casing, the header in the below react widget needs to be lowercased. @ncksllvn Could you please make this change since I don't have access to the react widgets? 

![Screen Shot 2020-01-08 at 1.54.55 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d7f9a1de-8062-4f82-8638-6a58fce81f59)

## Tasks

- [ ] Lowercase "benefit letters" in the alert box header  - x hour(s) - @ncksllvn 
- [ ] Review and publish - 1 hour(s) - @RLHecht 

## Acceptance Criteria:

* Live site shows all updates correctly

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
Confirmed this is OK on live page. Closing ticket.
