### ISSUE TITLE
[SPIKE][Helm,GHA] Hello World Helm Chart Template Files

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46865]
## Description
Users are not at the level needed to create their helm charts efficiently, and as a result, we should dump the entire hello-world helm chart (`templates/` and all) into the manifest repo for them, versus only the Chart.yml.

## Background/context 
- Today we create a helm chart that is nothing but a wrapper that has a dependency on hello-world
- Providing the raw template files for the user is going to increase adoption / lower the bar for onboarding to EKS

---
## Tasks
- [x] Evaluate which GitHub Action workflows need to be updated
- [x] Create follow-on stories for any actual work taking place so we can prioritize, if needed

## Acceptance Criteria 
- [x] An application onboarding to EKS without an existing helm chart is provided with the hello-world chart as a starting point within the manifest repo

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/820

**Comment by oseasmoran73** [comment]
See PR's associated as well as enhance hello world template ticket. Closing
