### ISSUE TITLE
Remove online form link from Spanish 10-10ez forms page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46874]
## Issue Description

When making some updates to COVID pages, we learned that when someone searches for the Spanish version of the 10-10ez form, a link for an online tool (written in Spanish) was coming up but it's linking to the English tool because there's no Spanish online tool currently. 

After some research by Public Websites, we learned the fix for this is to remove the online tool section and link from the Spanish find a form page. Note that this page is currently archived and should stay archived. 

Slack thread for more background: https://dsva.slack.com/archives/C52CL1PKQ/p1662145182310979

![Screen Shot 2022-09-09 at 3.27.48 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/6314ca0b-9d4c-4fbe-ae5f-e964cbe9e583) 

Preview page: preview-prod.vfs.va.gov/preview?nodeId=5745

## Tasks

- [x] Remove content for online tool from Spanish 10-10ez find a form page (Randi)
- [ ] Review (Laura/Megan)
- [x] Archive page (Laura/Megan)

## Acceptance Criteria
- [x] The online form no longer shows when searching for the 10-10ez form in Spanish

**Comment by RLHecht** [comment]
This is now fixed after removing it and rearchiving the page. Closing this!
