### ISSUE TITLE
Spanish translation work for updated booster shots (booster shots page)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46879]
## Issue Description

We made updates to our [COVID boosters page](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) on 9/9/22 about updated booster shots. We need to update our Spanish page with the new translated copy.

Copy of word doc that was sent: [https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download](https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Input content on Spanish page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live Spanish page is updated with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content from the translators: 
[https://app.zenhub.com/files/133843125/6b13ed8e-7038-4ebf-9654-a7a4d60ef3f2/download](https://app.zenhub.com/files/133843125/6b13ed8e-7038-4ebf-9654-a7a4d60ef3f2/download)

**Comment by aliyahblackmore** [comment]
Thanks, Randi! 

@megzehn This page is ready for you! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34408

**Notes/Flags:**

1. In the featured content box the sentence “ An updated booster will protect you even more against COVID-19.” is missing the end of the sentence, “against COVID-19.” My thought is that it would be “contra el COVID-19” but I’m not sure if this would have a different meaning, as “contra el COVID-19” is used earlier in a different sentence that has a slightly different meaning OR if this would be fine as is. Could we have them re-translate this sentence or make the addition, if this is needed? Cc: @RLHecht 
2. Noting that this translation uses “influenza” for “flu” instead of “gripe.” We’ve gotten “gripe” back before and it exists on the main COVID-19 page. Wondering if we can confirm with the translators which would best, so that we can be consistent across the pages moving forward? Cc: @RLHecht 
3. In the H3 “If you’re a Veteran who received care through VA” and “If you don’t receive care through VA or if you received your primary vaccine series outside of VA” the bullet is missing text, that we didn’t send to translation. These sentences are on the live English page, “Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.” Not sure if this should go out or if this was already sent over. Cc: @RLHecht 
4. The link for “COVID-19 Testing at VA” leads to an English page/there isn’t a translated version of this page. I’ve added in "(en inglés)" after the link text.

**Comment by megzehn** [comment]
Thanks @aliyahblackmore! This is now published. 

1. I think it's probably OK as is, based on the context. 
2. Great flag re: gripe/influenza. @RLHecht said she was going to mention this to the translators. 
3. Randi said this was a new update and will come back in a future translation. 
4. Thank you!!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
