### ISSUE TITLE
[FE] Updating Router with 4 Placeholder Pages 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46889]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Wireframes
[wireframes](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/317eadfed9ad31e217b0541fd9e84781be0f8e3c/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9FA13519-4BE9-4119-943E-5A1366B3E7A2?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&mode=design&present=true)

## Tasks
- [ ] [FE] Updating Router with 4 Placeholder Pages 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by brianseek** [comment]
Moving to closed since this is dev setup only.
