### ISSUE TITLE
Tagalog translation work for updated booster shots (coronavirus FAQs page)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46884]
## Issue Description
We made updates to our coronavirus FAQs page on 9/9/22 about updated booster shots. We need to update our Tagalog page with the new translated copy.

Copy of word doc that was sent: [https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download](https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download)

## Tasks
- [x] Send text to translators (Randi)
- [ ] Input content on Tagalog page (Aliyah)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Live Tagalog page is updated with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the word doc back from the translators: 

[https://app.zenhub.com/files/133843125/271c30fc-060f-43b0-90cd-5a090c695763/download](https://app.zenhub.com/files/133843125/271c30fc-060f-43b0-90cd-5a090c695763/download)

**Comment by aliyahblackmore** [comment]
Thanks, Randi! 

Hi @megzehn this is ready for you!

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16475

Note/Flags: 

1. In accordion “Makakakuha ba ako ng bakuna para sa COVID-19 sa VA?” I edited the FMP language to match what we have on the English pages. I pulled the Tagalog translation from the English page.
2. In accordion “**Maaari ba akong makakuha ng makabagong booster na iniksyon ng COVID-19 sa VA?**” (Can I get an updated booster shot at VA?) the sentence that starts with, “Parehong magbibigay-proteksyon ang makabagong” does have that dash between “magbibigay” and “proteksyon.” Just flagging this as a match to what was sent back to us!
3. In accordion “**Makakakuha ba ako ng libreng kit para pansariling pagsusuri para sa COVID-19 sa VA?**” removed text that is no longer on the live English page.
4. In accordion “**Ano ang dapat kong gawin kung mayroon akong mga sintomas ng COVID-19?**” adjusted the Annie header to match the live English page.
5. In accordion “**Ano ang kailangan kong malaman tungkol sa mga tipan at sangguni sa pangangalagang komunidad?**” the text “If you have concerns about rescheduling your appointment, send a secure message to your VA provider.” Is missing from the page. We are waiting to get this back in the new batch of translations.
6. I initially planned to update the content for the TTY and outside of the U.S. numbers that we reviewed with Beth, but realized that this a longer sentence (not just a matter of removing punctuation). I left in the original language. CC: @RLHecht - can we have the sentence translated in Tagalog:  If you’re outside the U.S., call +1-612-713-6415.  
And again, this change hasn’t been made to the live English page.

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore!

Confirming this page has been published. CC @RLHecht.
