### ISSUE TITLE
Tagalog translation work for updated booster shots (booster shots page)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46882]
## Issue Description
We made updates to our booster shots page on 9/9/22 about updated booster shots. We need to update our Tagalog page with the new translated copy.

Copy of word doc that was sent: [https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download](https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Input content on Tagalog page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live Tagalog page is updated with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content from the translators 

[https://app.zenhub.com/files/133843125/e2f0d0c2-ad1e-4014-aa2a-6010aa18a94d/download](https://app.zenhub.com/files/133843125/e2f0d0c2-ad1e-4014-aa2a-6010aa18a94d/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you!  
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34394

Notes/Flags: 

1. In the featured content box, the H2 “Bakit mahalagang makibalita patungkol sa inyong bakuna laban sa COVID-19” was already on the page, but I just did a double check and the English is “Why it’s important to get informed about your vaccine against COVID-19.” Just flagging this, though I’m assuming that perhaps this translation should remain as is. cc: Randi
2. Just flagging that the translation “Kailan makukuha ang makabagong booster na iniksyon,” came up as “When will the booster be available.” This may be an instance of google translate being off. I was checking this just to be sure this matched English (due to document formatting). I added this in as it was sent to us for the time being, but wondering if this would be something to flag. cc: @RLHecht 
3. Removed “Kung Janssen (J&J) ang natanhhap na bakuna as this is no longer on the live English page. 
4. Also removed header starting with “Kailan kayo…” as it is no longer on the live English page. 
5. In the H3 “If you’re a Veteran who received care through VA” and “If you don’t receive care through VA or if you received your primary vaccine series outside of VA” the bullet is missing text, that we didn’t send to translation. These sentences are on the live English page “Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.” Not sure if this should go out or if this was already sent over. Cc: @RLHecht 
6. The sentences “In the natural state, your body is exposed to thousands of germs. Your body then makes antibodies in response” are combined in the Tagalog translation. This already existed on the page and I’m assuming this should stay as is. Just noting in case the pattern seemed misaligned when you’re looking at the English and Tagalog text. 
7. Added “(sa English)” to the COVID-19 testing link in the More helpful information section.

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! Confirming here that this page has been published. CC @RLHecht 

Echoing point number 5, I think this line was added after the translations were sent, so we'll need to add it next time! 

“Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.” 

For 1, 2, & 6, I agree we should leave the translations as they are. For 3, 4, and 7 -- that's great!! Thanks for making those changes and noting them!

**Comment by RLHecht** [comment]
Closing!
