### ISSUE TITLE
Tagalog translation work for updated booster shots (main vaccines page)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46881]
## Issue Description
We made updates to our [main vaccine page ](https://www.va.gov/health-care/covid-19-vaccine/ )on 9/9/22 about updated booster shots. We need to update our Tagalog page with the new translated copy.

Copy of word doc that was sent: [https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download](https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Input content on Tagalog page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live Tagalog page is updated with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content from the translators: [https://app.zenhub.com/files/133843125/a0eaa6d5-ea4d-4104-8f91-1f8600a0156d/download](https://app.zenhub.com/files/133843125/a0eaa6d5-ea4d-4104-8f91-1f8600a0156d/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Notes/flags:** 
1. As stated on the Spanish page, the sentence “Basahin ang pahinang ito upang malaman kung paano makakakuha ng iyong bakunang COVID-19 sa VA” translates to “Read this page…” Wondering if we need to have this changed at all to match what is on the live English page, “Find out..”
2. In the featured content box, Novavax was spelled as “Novivax” in the translated doc. I edited this, as I believe this was a typo.
3. When I selected the link for “Learn how to get your primary COVID-19 vaccine”(Alamin kung paano makakuha ng unang bakuna ng COVID-19) on the live English page, it jumped to the H2 “Who can get a COVID-19 vaccine at VA.” I added in the jump link to this section, but I’m wondering if the jump link on the live English page would instead go to “How to get a COVID-19 Vaccine at VA?” I’ve left this as is for now, to match the jump link on the English page, but I wonder if the link on the English page should be pointing to the “How” H2 instead.
4. In the featured content info box the link “Alamin kung paano masuri para sa COVID-19 sa pamamagitan ng VA” leads to an English page. I added in “(sa English)”
5. In H2 “How to get a COVID-19 vaccine at VA” and H3 “How to get your first or second vaccine dose” I removed the bullet “Kung hindi kayo nagpapagamot sa VA, hinihikayat namin kayong magpa-register o magparehistro kahit na 1 oras bago kayo magtungo sa mga klinikang hindi kailangan ng appointment. Makakatipid ka sa oras pagdating mo” as this is no longer on the live English page.
6. Removed sentence “Nag-aalok din kami ng mga karagdagang dosis ng bakuna sa ilang partikular na grupo ng mga taong may mahinang immune system batay sa mga rekomendasyon ng CDC” as this is no longer on the live English page.

**Comment by megzehn** [comment]
This is now published! CC @RLHecht 

Thanks @aliyahblackmore for your careful work! 

And in response to your Qs...  

1. I think this is OK as is. 
2. Great catch!! Thanks for changing it. 
3. Good question. I left as is for now in case it's intentional, but I'll bring this up in standup. 
4 - 6. Amazing! Thank you for doing that.

**Comment by RLHecht** [comment]
This is live. Closing!
