### ISSUE TITLE
Spanish translation work for updated booster shots (FAQs page)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#46880]
## Issue Description
We made updates to our coronavirus FAQs page on 9/9/22 about updated booster shots. We need to update our Spanish page with the new translated copy.

Copy of word doc that was sent: [https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download](https://app.zenhub.com/files/133843125/d37a1766-c906-4c22-ab23-1fea6e405a8e/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Input content on Spanish page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live Spanish page is updated with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content from the translators: 
[https://app.zenhub.com/files/133843125/c704cb8b-8d61-4551-b515-54d6ccf1e8bd/download](https://app.zenhub.com/files/133843125/c704cb8b-8d61-4551-b515-54d6ccf1e8bd/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn - this is ready for you! I did  scan of the page as well and removed any text that is no longer on the live English page and made a few other small changes.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=14580

**Notes/Flags:** 
1. In accordion “¿Puedo ahora recibir la vacuna contra COVID-19 en el VA?” changed the text about FMP to match what is on the main COVID-10 page. 
2. Changed “dos” to  “2” in the text that we got back.  
3. In accordion “¿Puedo obtener kits de autoprueba para COVID-19 gratuitos a través del VA?” removed this text as it is no longer on the live English page: Cada hogar en los EE.UU. puede solicitar kits de autoprueba gratuitos (también llamados pruebas en el hogar). [Pida sus kits de autoprueba para COVID-19 gratuitos en COVID.gov](https://www.covid.gov/tests) Si necesita ayuda para pedir sus pruebas, llame al [800-232-0233](tel:+18002320233) (TTY: [888-720-7489](tel:8887207489)). 
4. In accordion “¿Qué debo hacer si tengo síntomas de COVID-19?” the Header level for the text on the Annie service didn’t match the live English page. I believe that this is a H4 level. I change this.
5. In accordion “¿Necesito usar una mascarilla en un centro de salud del VA o en un Vet Center?” bolded “Esto es lo que debo saber” to match style of English page.
6. In accordion, “¿Qué debo saber sobre las citas y remisiones de atención comunitaria? This is missing from the page “If you have concerns about rescheduling your appointment, send a secure message to your VA provider.” Not sure if this is something new for translation, but wanted to flag just in case. CC: @RLHecht
7. Throughout the page, when Monday and Friday were not at the beginning of the sentence, I made this lowercase. In Spanish, the days of the week are not usually capitalized, unless at the beginning of a sentence. This was the case on various parts of the page, with the exception of a few areas that used lower case previously.
8. In accordion “Que pasa si no puedo pagar mi deuda del VA ya existente”, I made the change to the sentence with the overseas telephone number to match the format that I suggested/we discussed today (10/3 re: an alert) to avoid the double parenthesis.  This wasn’t already on the live English page, so happy to remove this change if needed!

**Comment by megzehn** [comment]
Thanks @aliyahblackmore! Your changes all make sense to me. 

I'll echo that the line below is missing, for when we send the next round of update requests. Although I don't think it's a super high-priority need, since there's a link that directly follows for people to send a secure message to their provider. 

In accordion, “¿Qué debo saber sobre las citas y remisiones de atención comunitaria? This is missing from the page “**If you have concerns about rescheduling your appointment, send a secure message to your VA provider.**”

**Comment by megzehn** [comment]
@RLHecht this is now published and ready for validation. Thanks!

**Comment by RLHecht** [comment]
This is now live. Closing!
