### ISSUE TITLE
[BE] Create Service Object to Submit a Travel Reimbursement Claim to BTSSS API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46891]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [ ] [BE] Create Service Object to Submit a Travel Reimbursement Claim to BTSSS API

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by sarahknoppA6** [comment]
this can be closed- will be validated in a batch
