### ISSUE TITLE
[Design] Travel Pay: Update Final Wireframes with Finalized Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46892]
## Tasks
- [x] Create the content
-  [x] Update Final Wireframes with [Finalized Content](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit)

## Deliverable:
Wireframes and prototypes are updated with the final content:
- [x] [Wireframe link](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2)
- [x] [Prototype link](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/prototype/a/1A834D3B-A6B1-4B5E-A0CB-9C11FF0238D5) (Link updated on 9/20/2022 6:00 PM ET)

**Comment by benbrasso-agile6** [comment]
I need to review and make updates to the [draft](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit?usp=sharing) as a result of our conversation with BTS3 API Team. I also got some initial feedback from the UX team. 

And, I need to determine timing from Danielle on when she can review from a plain language and VA.gov standards perspective. Will meet with them tomorrow to see how much time they'll need.

**Comment by benbrasso-agile6** [comment]
Updated [content](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit?usp=sharing). Meeting with Danielle tomorrow morning.

**Comment by benbrasso-agile6** [comment]
@loripusey take a look at [Prototype D user flow here](https://app.mural.co/t/vfscie8528/m/vfscie8528/1658844568873/93ba988aed6312d43533b8feaed365529b836332?sender=u83bc52d7fa73658f84f27755)

You think it's worth showing that during the MVP meeting next week? Might be useful to demonstrate, 1) our look up for one or more appts, and 2) that the Veteran waits in the waiting room after the check in.

**Comment by loripusey** [comment]
Looks good, I do think it's worth showing the user flow before we dive into the actual prototype.

**Comment by benbrasso-agile6** [comment]
@zach-park danielle will get feedback back to me by monday or tuesday, which should give time to flow the updated copy in by the thursday meeting

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 , ready for review now.

**Comment by loripusey** [comment]
Looks great! I love the updated content. I added the content to the Spanish [spreadsheet](https://docs.google.com/spreadsheets/d/1xv63kaIR_UMq1bssSleMODXEV14OOGwfcL41rBBWhwk/edit#gid=14407571)

**Comment by benbrasso-agile6** [comment]
@zach-park added one comment for you zach in abstract, thanks

**Comment by benbrasso-agile6** [comment]
@loripusey there's a paragraph on the "is this your home address" page that needs to be added. I have been keeping the content up to date here as well - https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit?usp=sharing

**Comment by loripusey** [comment]
Let me know when the update happens and I'll add it to the spreadsheet.

**Comment by zach-park** [comment]
@benbrasso-agile6 @loripusey updated the "Did yopu travel from your..." page.

**Comment by benbrasso-agile6** [comment]
Thanks. Did it get republished to sketch prototype yet? Or, is there a lag?

**Comment by zach-park** [comment]
@benbrasso-agile6 , my oversight. I only pushed it to the abstract master branch. published to sketch cloud now.
