### ISSUE TITLE
[BE] Create Service Object to Connect to BTSSS Authentication API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46890]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [ ] [BE] Build service object

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
