### ISSUE TITLE
[EKS] Update datadog agent helm chart to 3.x

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#46906]
## Description
In the most recent update of datadog agent helm chart to 3.x they have replaced the need for a separate kube state metrics deployment in favor of kube state metrics core https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#migration-from-kubernetes_state-to-kubernetes_state_core

The biggest issue with this change is the fact that they have deprecated some of the metric tags as seen here https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#tags-removal

This means that any monitor or dashboard referencing these tags will need to be aligned with the newly collected tag names.

I believe the best approach here is to leverage the ability they provided to run both legacy kube state metrics and the new kube state metrics core at the same time while the migration of dashboard and monitor tags is tackled.

https://github.com/DataDog/helm-charts/blob/7133a61ab47d46f9cec0592b5bd07718ba05ca32/charts/datadog/values.yaml#L123-L139

---
## Tasks
- [ ] update datadog agent keeping both the legacy and new kube state metrics collecting data
- [ ] go through all the monitors and dashboards in datadog and update any legacy tags to the new tags
- [ ] once confirmed that all the monitors and dashboards have been updated, disable the legacy kube state metrics

## Acceptance Criteria 
- [ ] datadog agent and helm chart versions are updated and the datadog dashboards/monitors are still receiving the appropriate data

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mleclerc00** [comment]
Doing some initial leg work to find all of the deprecated tags that will need to be fixed, I used the following command to get each dashboard as json which will allow me to grep through and find the ones that need to change

```
curl -k -X GET "https://<dd_url>/api/v1/dashboard" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}" \
| jq '.dashboards[].id' \
| xargs -I{} sh -c \
'curl -k -X GET "https://<dd_url>/api/v1/dashboard/{}" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}" > "{}"'
```

**Comment by mleclerc00** [comment]
Cluster agent and node agent both updated and seem to be working.  Will verify that metrics are still going to datadog as expected and roll out to the remaining environments.
<img width="747" alt="image" src="https://user-images.githubusercontent.com/76792875/189977545-08a6f34e-e6c0-4bdd-b4f9-61204b125fa6.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/76792875/189977805-30fdd8be-8ca1-4c61-8dd8-99623d65919a.png">

**Comment by mleclerc00** [comment]
All dashboards have been scrubbed for deprecated tags, moving on to monitors

**Comment by mleclerc00** [comment]
Monitors updated, removing legacy kube state metrics from dev

**Comment by mleclerc00** [comment]
staging
<img width="711" alt="image" src="https://user-images.githubusercontent.com/76792875/190217229-e0dde4f5-1f19-4a8f-82d3-6c748f2fd21d.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/76792875/190217377-5bbf28ef-6bb4-4942-815f-7826df2a96e9.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/76792875/190217435-7b69bbb4-f4e2-489e-a268-5c3c7ccda154.png">

**Comment by mleclerc00** [comment]
utility
<img width="711" alt="image" src="https://user-images.githubusercontent.com/76792875/190228494-9082da26-a1a8-4a1b-a816-779afdd345de.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/76792875/190249276-bdc8c81f-5f44-4deb-b248-5533b2e2d73e.png">

**Comment by mleclerc00** [comment]
sandbox
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190251828-879c7a9b-bb61-4ce6-8cb6-542a69bf02e9.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190251893-801646e2-9635-49d5-81be-9a22dafddeec.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190251941-31417acd-2501-41e3-9819-c3780348dd12.png">

**Comment by mleclerc00** [comment]
prod
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190252137-27228d84-a0e1-40cc-a6cc-3e9b943a6ebf.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190252195-ccde23b2-9e5d-4678-b9dc-f8ee8e4c262a.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/76792875/190252701-3a8818f1-8698-4dde-9345-edf4e102e86a.png">
