### ISSUE TITLE
Design | Profile | Documentation for Connected Apps

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#46918]
## Background

We need to audit, update and/or create design documentation for the Connected Apps section of the Profile.  Good examples can be found within Direct deposit or Contact info features which have recently been updated.

## Tasks
- [x] Update and/or create use cases for this feature
- [x] Create user flows
- [x] Create/update screen mocks and text

## Acceptance Criteria
- [x] Post to appropriate sections of GitHub and sketch
- [x] Check that links from product outline are up to date

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- the [Connected apps documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/connected-apps) is ready for your review! In particular, could you take a look at the "can't display connected apps" use case? I referenced the documentation from the other sections, but I'm not sure if this is different due to us not directly handling the apps. 

Also there are some files/images Tom moved over that I haven't touched - didn't want to risk breaking important links - but let me know if you prefer to have those in a different or new file.

**Comment by Samara-Strauss** [comment]
> Connected apps: User views, connects, and disconnects apps

This is actually not accurate -- users can only connect apps through a third part interface (think giving Apple Health access to your VA data from the Apple Health app). Users can only view and disconnect apps from the profile, so "connect" needs to be removed from everywhere it's mentioned in this use case.

> Connect apps

You can entirely remove this section since it's redundant with "View apps".

> View Connected apps
> Go [staging.va.gov/profile/account-security](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/use-cases/staging.va.gov/profile/account-security)
> Log in with any [staging user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv).

I think you should divide this into users who do and don't have apps connected. I don't know all users with connected apps, but it looks like user 36 has a bunch connected. I would venture a guess and say most users do not have apps connected.

> could you take a look at the "can't display connected apps" use case? I referenced the documentation from the other sections, but I'm not sure if this is different due to us not directly handling the apps.

TBH, you probably need Adam to look in the code to confirm this. I'm sorry. There's no way to confirm this from the frontend.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss, this all sounds good. I had included that the user needs to go elsewhere to actually connect apps, but if it's better to remove all of that completing that works for me! 👍

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow -- I reorganized the main [use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/use-cases/view-and-disconnect-apps.md) by apps connected vs. no apps connected, and will check with Adam about the "can't display connected apps" use case, though I imagine that won't be confirmed until we're both back next week. Let me know if you see anything else that needs updating. Thanks!

**Comment by Samara-Strauss** [comment]
The new organization of that use case looks great! Very intuitive way to organize things.

> I imagine that won't be confirmed until we're both back next week. 

Totally fine! We'll come back to this when you're back from your trip.

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow Adam confirmed that what's represented in the use case is indeed what he sees in the code 👍  Unless there's anything else you can think of, I believe we're all set to close this out!

**Comment by SKasimow** [comment]
Awesome! Closing
