### ISSUE TITLE
Move GIDs to Forward Proxy

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#4692]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet

If we move GIDs behind the forward proxy then we will have more insight into GIDs health and better separation between vets-api and GIDs.

## OKR

Be able to absorb large changes in traffic and load patterns, outliers, and services are more isolated.

## Definition of done
*What must be true in order for you to consider this epic complete?* 

All traffic from vets-api to GIDs must go through the forward proxy and corresponding documentation is updated.

- [ ] Forward Proxy HAproxy template supports plain tcp backends https://github.com/department-of-veterans-affairs/va.gov-team/issues/4693
- [ ] Create GIDs backend in Forward Proxy configuration https://github.com/department-of-veterans-affairs/va.gov-team/issues/4694
- [ ] Update vets-api config to point GIDs connections to new Forward Proxy backend https://github.com/department-of-veterans-affairs/va.gov-team/issues/4695

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
