### ISSUE TITLE
List and Define Quality Assurance Standards

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#46937]
## Issue Description
In order to release Quality Assurance Standards to VFS Product Teams for use on the VA.gov platform, we need to list and define the standards against which products will be evaluated.

## Tasks
- [x] List the standards that platform will use to assess products
- [x] Define each standard

## Acceptance Criteria
- [x] A list of QA standards and the definitions is available in this ticket

**Comment by JoeTice** [comment]
Initial in progress set defined here: https://vfs.atlassian.net/wiki/spaces/TTT/pages/edit-v2/2126544949

**Comment by JoeTice** [comment]
Final version of standards available here: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2126544949/QA+Standards+Team+-+QA+Standards

**Comment by pjhill** [comment]
We have a list of standards. We are working through the definition and publication of documentation supporting the QA standards in other tickets.
