### ISSUE TITLE
Update forward proxys HAproxy template to support non tls backends

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#4693]
## User Story:
Currently the [template used to generate haproxy configuration](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy/haproxy.conf.j2#L96) for the forward proxy don't support backends that don't use TLS. 

GIDs currently doesn't use https so in order for the forward proxy have a GIDs backend we need to update the template to support plain TCP backends.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Create new interface type in the template
- [x] Test

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* [ ] 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
