### ISSUE TITLE
[FE] [TECH DEBT] Fix flaky browser navigation E2E test

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#46949]
## Background

https://github.com/department-of-veterans-affairs/vets-website/pull/22174

## Tasks
- [ ] [FE] investigate, reproduce and fix test failure
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
This was [fixed](https://github.com/department-of-veterans-affairs/vets-website/commit/59067808dbedea5cb4ae4a843694bd4d48edaff8) by Darius Dzien.
