### ISSUE TITLE
Add Forward Proxy Backend for GIDS

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#4694]
## User Story:
Once https://github.com/department-of-veterans-affairs/va.gov-team/issues/4693 is complete, add configuration in each Forward Proxy environment to create new GIDS backend.

## Tasks

For each environment:

- [x] Choose a port for the new GIDs backend -- 4464
- [x] Update terraform to create new listener
- [x] Update haproxy configuration to include GIDS backend
- [x] Open GIDS security group for fwdproxy

## Acceptance Criteria:

GIDS is reachable through the Forward Proxy in all environments.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
