### ISSUE TITLE
Create VFS-facing Documentation for QA Standards

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#46940]
# User Story
Prior to launching QA Standards we need to document how VFS teams will interact with the standards, what the standards are, and where teams can check their level of achievement with the standards. The standards themselves can be found here: https://vfs.atlassian.net/wiki/spaces/TTT/pages/2126544949/QA+Standards+Team+-+QA+Standards

# Tasks
- [x] Consult the Platform Content team for placement and structure of the document in Platform Website
- [x] Create a document to be published to the platform website for use by VFS teams
- [x] Ensure that the document for use by VFS teams contains all information that a VFS team needs

# Acceptance Criteria
- [x] QA Standard documentation is published on the Platform website

**Comment by rsmithadhoc** [comment]
- Started a [Confluence page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2375909428/Quality+assurance+standards) for the platform website docs.
- Looking up/putting together instructions for checking each metric and how to get it fixed.

**Comment by rsmithadhoc** [comment]
Hi @pjhill,

- I added a draft for https://vfs.atlassian.net/wiki/spaces/PWD/pages/2375909428/Quality+assurance+standards. I wasn't entirely sure of some of the TestRail/Domo reports since I don't have access to that (and probably not worth getting it with the upcoming team switch), but I followed existing documentation and linked to that where appropriate. 
  - Can you review and make sure I got those correct?
- This will live under https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-and-accessibility-testing right above the **Best practices for QA testing** in the page hierarchy. I'll move it over there for platform site publishing once you have had a chance to take a look.

Thanks!

**Comment by pjhill** [comment]
Moved this page to the location for publishing today hopefully.

**Comment by rsmithadhoc** [comment]
Thanks @pjhill, looks like that was published successfully: https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards, so I will close this out.
