### ISSUE TITLE
Point vets-api GIDs connection to Forward Proxy

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#4695]
## User Story:
Once https://github.com/department-of-veterans-affairs/va.gov-team/issues/4694 is done, update vets-api configuration to point to forward proxy.

For example in dev change [this line](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2#L71) to point to the forward proxy.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Update configuration to point to forward proxy
- [ ] Rollout change to vets-api dev then staging then production

## Acceptance Criteria:

Vets-api connects to GIDs through the Forward Proxy.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
