### ISSUE TITLE
[EKS,Helm,Dev] Switch to ExternalSecrets Operator

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46954]
## Description
The ExternalSecrets that we currently use in Kubernetes has been deprecated. We need to switch over to using the Operator version (another helm chart).

## Background/context 
- Our installation of ExternalSecrets has been deprecated
- Using the Operator is now the official way to install ExternalSecrets

## Technical notes
- https://github.com/external-secrets/kubernetes-external-secrets/commit/bf4b502155674acd19a2dbe5db3cb4838ce9450a
- Existing ExternalSecret manifests will require updating in follow-on tickets
- https://external-secrets.io/v0.6.0-rc1/guides/getting-started/#installing-with-helm

---
## Tasks
- [ ] Install the Operator version of the ExternalSecrets

## Acceptance Criteria 
- [ ] The new Operator for ExternalSecrets is installed into EKS Dev

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
The external secrets datadog alert might need to be modified along with this change. https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/external-secrets.yaml
