### ISSUE TITLE
[SPIKE,EKS] Convert ExternalSecrets Format

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#46965]
## Description
The format of ExternalSecret manifests needs to be converted from the deprecated version to the one supported by the Operator.

## Background/context 
- Old version of ExternalSecrets was deprecated
- Format for manifest has changed

## Technical notes

---
## Tasks
- [ ] Create tickets per cluster, per namespace for the work that is needed for converting formats 

## Acceptance Criteria 
- [ ] Tickets have been created for the work needed, per cluster, per namespace

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
Relates to https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/46954

**Comment by ph-One** [comment]
- Install Operator
	- Dev
	- Utility
	- Staging
	- Sandbox
	- Prod
- Update ExternalSecret Manifests
	- Dev NS
		- datadog-agent
		- datadog-gov-private-location
		- default
		- gibct-data-service
		- keycloak
		- keycloak-next
		- observability
		- pghero
		- platform-cms
		- platform-console-ui
		- platform-pst-amt
		- platform-pst-iet
		- revproxy
		- sidekiq
		- vets-api-server
		- vets-api-sidekiq-ui
		- vsp-tools-backend
	- Utility NS
		- argocd
		- datadog-agent
		- datadog-gov-private-location
		- keycloak
		- observability
		- platform-console-ui
		- sentry
		- sentry-test
		- vsp-tools-backend
	- Staging NS
		- datadog-agent
		- datadog-gov-private-location
		- gibct-data-service
		- keycloak
		- observability
		- platform-console-ui
		- sidekiq
		- vets-api-server
		- vets-api-sidekiq-ui
		- vsp-tools-backend
	- Sandbox NS
		- datadog-agent
		- datadog-gov-private-location
		- gibct-data-service
		- keycloak
		- observability
		- platform-console-ui
		- sidekiq
		- vets-api-server
		- vets-api-sidekiq-ui
		- vsp-tools-backend
	- Prod NS
		- datadog-agent
		- datadog-gov-private-location
		- gibct-data-service
		- observability
		- vets-api-server
		- vets-api-sidekiq-ui
		- vsp-tools-backend
- Uninstall Old ExternalSecrets Chart
	- Dev
	- Utility
	- Staging
	- Sandbox
	- Prod
