### ISSUE TITLE
Add Cypress-axe to End-to-end testing with Cypress

### ISSUE THREAD

**Issue by mgifford** [department-of-veterans-affairs/va.gov-team#46963]
### Description

So this page [End-to-end testing with Cypress ](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress)really should include Cypress-axe. There are just so many ways to build in axe testing to evaluate dynamic elements of a page. 

### Relevant URLs
- https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress
- https://www.npmjs.com/package/cypress-axe

---- 

## User Story
As a VFS team member, I want to access Cypress-axe from the End-to-End testing with Cypress page so that I am able to atake full advantage of axe testing.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
See description above. This request came from the Platform Content team.

## Impacted Artifacts
- https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress
- https://www.npmjs.com/package/cypress-axe

## Tasks
- [x] Integrate cypress-axe into the End-to-end testing with Cypress page
- [x] Request peer review from @pjhill 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Cypress-axe has been added to the End-to-end testing with Cypress page

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by taylojill** [comment]
Hello @pjhill and @JoeTice The ticket came in through the Platform website footer. Let me know if you have any questions or need assistance. Thanks, Jill

**Comment by taylojill** [comment]
Hi @shiragoodman! I noticed the governance team label was added. Let us know if we can assist in any way.
cc @vbellissimo

**Comment by pjhill** [comment]
We do require the use of axe checks in Cypress test specs. That requirement is listed [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-an-end-to-end-test#Writinganend-to-endtest-End-to-endtestsconventions). Although the use of axe is not discussed at the top level document pointed to in this feedback, it _is_ discussed in the context of accessibility testing and in the best practice documents for Cypress use on the platform.

**Comment by it-harrison** [comment]
@CherylEvans this is available for [peer review here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2429321222/Copy+of+End-to-end+testing+with+Cypress). I added to the paragraph above "Initial Setup"

**Comment by it-harrison** [comment]
Hi @pjhill can you take a look [at this page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2429321222/Copy+of+End-to-end+testing+with+Cypress) and see if my additions address the concerns of this ticket? I added to the paragraph above "Initial Setup"

**Comment by CherylEvans** [comment]
@it-harrison Your introductory paragraph was good, but it was written in passive voice.  In accordance with VA Standards we always write in active voice.  I rewrote it in active voice without changing the meaning or content.  I have replaced your text with the new active voice text.  Please take a look and let me know what you think.  :-)

**Comment by it-harrison** [comment]
thanks for your help @CherylEvans, looks good to me!
