### ISSUE TITLE
Remove existing cards and create new card(s)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#46983]
## User Story
As a Governance team member, I want to build out a card in Domo that shows the mean, median and/or mode of close rate in Collab Cycle Staging Review issue tickets so that Platform can identify areas of improvement for Collab Cycle.

Assignee: @shiragoodman 
Peer Reviewer: @briandeconinck 

## Description
The Collab Cycle Dashboard has 2 cards that are not accurate and/or reliable. A new data set has been defined, however it is not in use in the form of cards within the dashboard. The purpose of this ticket is to remove the 2 outdated cards (Total Issues by team, Total issues by Status) and create a new card(s) that shows the mean days to close a Staging Review issue ticket, the median days to close a Staging Review issue ticket, and the mode days to close a Staging Review issue ticket.

## Impacted Artifacts
- [Collab Cycle Dashboard](https://va-gov.domo.com/page/1340527018?userId=1646566899)
- [Data set](https://va-gov.domo.com/datasources/0375917b-befc-4057-b3f9-15eba2c78f2e/details/overview)

## Tasks
- [x] Transfer Owner of dashboard from Ryan Johnson to Shira Goodman
   - [see Slack thread](https://dsva.slack.com/archives/C01CHAY3ULR/p1663685700180559)
- [x] Delete 2 existing cards
- [x] Create new card with mean, median and mode
   - Note: Mode is challenging to calculate, so waiting for feedback from A&I team. Instead, I've added minimum and maximum.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] The Collaboration Cycle dashboard no longer shows the outdated cards
- [x] The Collaboration Cycle dashboard shows the mean, median and mode of days to close Staging Review issue tickets
   - Rather than displaying mode (not available in Domo), displaying mean, median, min, and max.

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
[Collaboration Cycle Dashboard](https://va-gov.domo.com/page/1340527018?userId=1646566899)

**Comment by shiragoodman** [comment]
@briandeconinck please let me know your feedback by EOD, if possible. I'd like to close this before the sprint ends.

**Comment by briandeconinck** [comment]
@shiragoodman Review complete, this looks good for an MVP. Some quick thoughts for future enhancements:

- You mentioned this before, but not having axis labels is a huge pain. It may be worth adding some extra text above the graph making it more explicit what each axis is communicating.
- In office hours, Chloe mentioned the option of cutting off the tail end of the graph and then noting somewhere "[X tickets] were excluded because [y]". I feel like that could be helpful with a cutoff of... maybe 365 days? Maybe 250 days? That would only exclude a small handful of tickets but would give the rest of them some breathing room and slightly more granularity.

**Comment by shiragoodman** [comment]
> @shiragoodman Review complete, this looks good for an MVP. Some quick thoughts for future enhancements:
> 
> * You mentioned this before, but not having axis labels is a huge pain. It may be worth adding some extra text above the graph making it more explicit what each axis is communicating.
 - For the sake of closing out the ticket, I am going to leave it as a histogram for now, but I think I'll look into setting it up as a bar graph with clearly defined buckets. I love your percentage recommendation below!
> * In office hours, Chloe mentioned the option of cutting off the tail end of the graph and then noting somewhere "[X tickets] were excluded because [y]". I feel like that could be helpful with a cutoff of... maybe 365 days? Maybe 250 days? That would only exclude a small handful of tickets but would give the rest of them some breathing room and slightly more granularity.
 - Agreed. The reason I changed it back was bc I couldn't figure out how to add a note stating that this excluded tickets older than 365 days. I think if we pivot toward the bar graph with the recommendations you made below, it'll be much clearer. We can add a category for tickets that have been open greater than 1 year.
> * I'm not sure how easy it would be to calculate and display this in Domo, but I'll also suggest displaying percentage of tickets closed within 14 days, 3 months, and 6 months. Those would be nice at-a-glance numbers, and even though they wouldn't directly match the sprint/quarterly planning calendars it divides things into time periods OCTO and Platform have some intuition around.
 - I 100% agree and plan on doing this! Writing up the ticket now
