### ISSUE TITLE
[FE] Update the Confirmation Page Based on Answers

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47008]
## User Story
As a Veteran, I would like an easy way to submit my travel re-imbursement so that I can get reimbursed in a timely fashion.

 
## Wireframes
[Wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/85692fe586bc5aa126dea09a02c24d5e0f9c6e4d/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/FCAB398B-8F73-41D1-B642-651A35820B47?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&mode=design&present=true)

## Tasks
- [ ] [FE] Store the answers
- [ ] [FE] Update the Confirmation Page Based on Answers
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by loripusey** [comment]
@acrollet who can validate this? can't access staging right now

**Comment by acrollet** [comment]
@brianseek you've tested this work, can you validate that it meets the ACs?

**Comment by brianseek** [comment]
I think the screenshots from [this ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47705)also validates this
