### ISSUE TITLE
Remove references to Troy Mosher and other individuals in Collab Cycle documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47000]
Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
Troy Mosher departed the team on 9/7. He is mentioned as a resource in the[ Privacy, Security, Infrastructure Readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) page as well as the [Contact Us ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)page. 

**Note:** Per Platform [Content principles](https://vfs.atlassian.net/wiki/spaces/AP/pages/2017001494/Content+principles), Platform teams should, "Avoid using the names of specific individuals, teams, or contracts. Use the Platform and team-focused pronouns like “you,” “we,” and “our” instead.”[ See Slack thread.](https://dsva.slack.com/archives/CJRQ85PQB/p1662997964626149)

The Contact Us page should be the ONLY page within the Collaboration Cycle that lists individuals names. This ticket will also include an audit of the Collaboration Cycle pages to identify and remove references to other individuals.

## Impacted Artifacts
- [Privacy, security, infrastructure readiness review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317101/Privacy+security+infrastructure+readiness+review)
- [Contact us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)

## Tasks
- [x] Audit Collab Cycle pages for individuals names (minus Contact Us page)
- [x] Any page with an individuals name, document and link above with their name (Impacted Artifacts)
- [x] Remove references to Troy. Replace Troy's name with Clint Little on Contact Us page
- [x] Fix Thomas' name (it should not be a link) on Contact Us. Remove him from the P&S page.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Troy Mosher references are removed from Platform Website
- [x] VFS teams know that Clint Little is the point of contact, along with Thomas, for the P&S review
- [x] Individuals are not mentioned by name on Platform Website, excluding Contact Us

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
@allison0034 This is ready for peer review. I'm 95% certain there aren't any other pages in the Collab Cycle section that has people's names -- but maybe do a quick check to verify!

**Comment by allison0034** [comment]
@briandeconinck looks good!
