### ISSUE TITLE
[FE] Update Each of the 4 Pages to Include the Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47007]
## User Story
As a Veteran, I would like an easy way to submit my travel re-imbursement so that I can get reimbursed in a timely fashion.
 
## Wireframes
[Wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/8f5b89443b598f5e21e03d1c56102adff6b710c8/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/7FA4D20D-4E94-4716-9D4A-C3190ECA2962?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&mode=design&present=true)

## Tasks
- [ ] [FE] Add Content to each of the 4 pages
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey / @zach-park  / @benbrasso-agile6 This is now testable on stage, but the feature needs to be flipped first. Let me know if you need help with that when you go to validate.

**Comment by zach-park** [comment]
@brianseek, could you either help with the feature flip or share the screenshots? Thank you!

**Comment by brianseek** [comment]
@zach-park here are some screenshots [https://app.zenhub.com/files/133843125/5619f016-8f08-45de-a24b-fbfaf93e7ee0/download](https://app.zenhub.com/files/133843125/5619f016-8f08-45de-a24b-fbfaf93e7ee0/download)

**Comment by zach-park** [comment]
@brianseek , they look really good. One small tweak though... The padding between the divider and the primary button should be greater. Please refer to the [attached link here](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=58e50209-6952-489c-b1e1-a1e23160fc77&mode=design) as reference. 

<img width="314" alt="Day-of-check-in--travel-pay--address-question2" src="https://user-images.githubusercontent.com/91493630/193946759-dbb48995-23c4-4a75-b09f-f27077284596.png">

**Comment by brianseek** [comment]
@zach-park agreed, I had this right at one point but maybe screwed it up in a rebase. Looks like the margin-top class is added twice where one is supposed to be the bottom. We can add that to the content changes that are coming in the next sprint

**Comment by brianseek** [comment]
added it to a task here: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47705

**Comment by loripusey** [comment]
closing as validated
