### ISSUE TITLE
[SPIKE,Ticket Creation] Helm Chart Upgrades

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47006]
## Description
Create tickets for Helm charts that need upgraded

## Background/context 
- Part of maintaining a Kubernetes platform is keeping supporting services up to date

## Technical notes

---
## Tasks
- [ ] Create ticket per helm chart, per environment
  - [ ] argo-events: 1.13.0 -> 2.0.4
  - [x] aws-node-termination-handler: 0.19.2 -> 0.19.2 :white_check_mark:
  - [ ] cert-manager: v1.4.0 -> v1.9.1
  - [x] cluster-autoscaler: 9.21.0 -> 9.21.0 :white_check_mark:
  - [ ] datadog: 2.35.3 -> 3.0.1
  - [ ] external-dns: 6.2.3 -> 6.8.2
  - [ ] goldilocks: 6.1.0 -> 6.2.0
  - [ ] grafana: 6.8.4 -> 1.0.4 :question:
  - [ ] keycloak: 16.0.5 -> 10.0.0 :question:
  - [ ] keycloak: 17.0.2 -> 10.0.0 :question:
  - [ ] kubernetes-external-secrets: 8.1.3 -> 8.5.5
  - [ ] loki-distributed: 0.33.1 -> 0.56.7
  - [ ] metrics-server: 3.8.2 -> 6.1.2 :question:
  - [ ] promtail: 3.6.0 -> 6.3.0 ????
  - [ ] sentry: 11.4.0 -> 15.2.1 :question:
  - [ ] sorry-cypress: 1.6.3 -> 1.7.6
  - [ ] synthetics-private-location: 0.14.1 -> 0.15.1
  - [ ] traefik: 10.15.0 -> 10.24.2

## Acceptance Criteria 
- [ ] Tickets are created per helm chart, per environment

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ph-One** [comment]
Using a one-liner for the initial scans and then analyzing diffs from there. Not the best way, but efficient and good enough to get started

```
find . -name Chart.yaml \
| xargs -I{} yq -r '.' {} \
| jq -r '.dependencies[] | .name + " " + .repository + " " + .version' \
| sort \
| uniq \
| awk '{print "echo vsp:" $3 "; helm repo add " $1 " " $2 "; helm search repo " $1 " -o json"}' \
| xargs -I{} sh -c "{} | jq -r '.[0].version'"
```
