### ISSUE TITLE
[DESIGN] 10-10CG Sketch File “Source of Truth” and Documentation 

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#47005]
### Background:
Update the existing Sketch file to being a source of truth to match staging/production including all pages (both desktop and mobile versions), states, errors and annotations. Add a page to keep master templates. Add a page and create a wireflow of the entire application. 

#### Naming Conventions
**Pages:**
Create Pages named consistently with numbers/wording used on progress tracker in form. 1-VeteranInformation, 2-PrimaryCaregiver for placement of staging/production artboards.
Keep existing pages in file as to not break any links in GH.
In future: Name Pages with conventions: Common Name-EPIC or ISSUE number Example: FacilitiesRedesign-E12345
**Artboards:**
CommonName-Size-{url}-State
Examples: Demographics-Desktop-{vet-1}-STAGING or Demographics-Mobile-{vet-1}-Issue12345

_Don’t change names or delete old pages this will break any existing links out there in closed tickets or conversations._   

### User Story: 
As a designer/PM it is clear what file should be the master source of truth (what is approved and in staging) as well as a clear trail to follow to find references of past work. 

### Tasks Ideas: 	
- [x] Meet with a goal to revise these tasks, discuss questions, decide on conventions, etc. and adjust description of this ticket.
- [x] 	Check design system Sketch file to copy out layout pages with grids (tip from orientation session)
- [x] Create a Templates Page in the Sketch file and create desktop and mobile templates that include padding and vertical spacing details. Keep all components and type styles in the templates page linked to the master VA Design System file. 
- [x] 	Create a Wireframe Page, the overall map of product that will show the pages in the form, fields included and flow. 
- [x] 	Create new Pages by section of form (_Veteran Information_ for example) and create artboards for each page/state within that section that aligns with staging. Include mobile designs. 

### Acceptance Criteria:
The Sketch file is a reliable source of truth doc that includes pages that aligns with staging/production and the VA Design System. There are naming conventions and patterns established to add new design iterations and explorations to the file.

**Comment by hdjustice** [comment]
@hdjustice add epic

**Comment by jessicastump** [comment]
These tasks have all been completed and the Sketch file does contain mock-ups in desktop and mobile of all main pages in the form. 

Recommend to open other tickets for tasks around error messages or annotations as needed. Closing this ticket.
