### ISSUE TITLE
[FE]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47010]
## User Story
As a Veteran, I would like an easy way to submit my travel re-imbursement so that I can get reimbursed in a timely fashion.

## User Workflow
- Given I
    - Am using eCheck-in to check in for an appointment
- When I
    - Answer the "Is this statement true for you?" question
- Then I
    - See a new page that asks me if I I travelled from this address
  
## Wireframes
[Wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/85692fe586bc5aa126dea09a02c24d5e0f9c6e4d/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/A9ABCDE2-27D1-43CD-93E4-AA6B8621688F?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&mode=design&present=true)

## Tasks
- [ ] [FE] **Create page to allow user to answer the question**
    - Should display the user's home address (permanent address?)
    - Should not show for cancelled or telephone appointments
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
