### ISSUE TITLE
Meet w/ Platform teams for remaining info about their Tools/Services

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47018]
## Issue Description
Meet w/ Platform teams to learn remaining information about their Tools/Services.  Use the developed script and Data Repository.

## User Story
As an SDT member, I want to meet w/ Platform teams so that I can capture the needed information for mapping their Tools and Services

## Additional questions:
-What do you consider to be the most critical/essential services you offer?

## Tasks
- [x] Schedule Technical Platform teams
- [x] Schedule Support Platform teams
- [x] Adjust/create conversation guide for each Platform team
- [x] Meet with each individual Platform team

## Acceptance Criteria
- [x] remaining Data of interest is captured for every team.

**Comment by steel36** [comment]
How does this get affected by the reshuffle and potential dissolution of specialized Platform teams?

**Comment by tayism** [comment]
Reached out to those folks who will be moving to 'project teams' first:

- Infrastructure
- Platform CMS
- Console Services
- Release Tools* (did not complete survey)
- QA Standards

**Comment by tayism** [comment]
[Conversation guide for RTT](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2370797638/Service+Mapping+Conversation+Guide+-+RTT)

[Note taking board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1662511366310/448e9d31493253029f678d4c432116f3184d5b89?sender=u9ea6bd3ca12795949b606150)
