### ISSUE TITLE
[FE] Make API Call after Travel Questions have been Answered

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47011]
## User Story
As a Veteran, I would like an easy way to submit my travel re-imbursement so that I can get reimbursed in a timely fashion.

## Tasks
- [ ] [FE] Make API Call after Travel Questions have been Answered
   - Consider how it fits with confirm demographics calls
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
test once on stg. leaving in validate

**Comment by sarahknoppA6** [comment]
per Adrian, we can call this validated.
