### ISSUE TITLE
[BE] Add Configuration for Authentication

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47014]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [ ] [BE] Add Configuration for Authentication

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Created PR https://github.com/department-of-veterans-affairs/devops/pull/12049 for development environment

**Comment by kanchanasuriya** [comment]
Application manifest PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/926
