### ISSUE TITLE
Create Google Lighthouse Plugin User Guide

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#47012]
## Issue Description
In order to get VFS teams using the Google Lighthouse plugin we need to publish a user guide to the Platform Website.

## Tasks
- [ ] Consult Content team about where to publish this document
- [ ] Create a rough draft of a VFS team facing document that explains the use of the Google Lighthouse plugin
- [ ] Collect feedback from the team
- [ ] Create a final draft of the document
- [ ] Publish the document to Platform Website

## Acceptance Criteria
- [ ] A Google Lighthouse User Guide document is available on the Platform Website
