### ISSUE TITLE
Centralize Monitoring: Set up monitoring and alerting for key platform services (Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47025]
## Problem Statement 
Monitors and alerts are spread across multiple systems. This negatively impacts the platform's ability to respond to incidents and support issues. And, leads to a confusing monitoring experience for platform operators. Additionally, maintaining multiple monitoring systems increases administrative overhead. 

## Background / context 
- Prometheus is the Platform's legacy monitoring solution
  - connects to PagerDuty, Slack, and other communication channels 
  - Deprecated in favor of Datadog
- There are still many monitors (rulesets) configured in Prometheus 
- Prometheus alerts are configured using Alertmanager
- The Alertmanager configuration is [here](https://github.com/department-of-veterans-affairs/devops/blob/6c39b47bb019ef14bbe560a6d64e622329265613/ansible/deployment/config/prometheus/alertmanager.yml.j2)
- Datadog is the Platform's centralized monitoring solution 
  - Note: Datadog is provided by VA OIT DevOps (DOTS) 

## How might we... 
- Centralize the platform's monitoring and alerting systems? 
- Provide operators with tools to respond to incidents and support issues more effectively?  
  - Make alerts more actionable for support personnel? 
- Improve the quality of life for on-call personnel? 

## Hypothesis or Bet

This initiative should...
- Provide a single source for metrics, monitoring, and alerting related to key platform services 
- Simplify the Platform's monitoring and alerting system _(and associated tooling)_   
- Prepare the Platform to deprecate Prometheus 

## We will know we're done when... ("Definition of Done")
- [ ] Key platform components and services (listed below) have the following in Datadog: 
  - [ ] Dashboard
  - [ ] Monitors
  - [ ] Alerts 
- [ ] Key Platform components and services include
  - [ ] AWS
  - [ ] Network
  - [ ] CI/CD
  - [ ] Utilities
  - [ ] EKS Infra
  - [ ] External services that the platform depends on
- [ ] Operational documentation is updated (or created) 
  - [ ] to inform support and incident response personnel on where to find monitors and alerts
  - [ ] that identifies all components and services (in Confluence) (note: can use Mural board to populate)
- [ ] Monitors and alerts in Prometheus that are no longer needed have been identified and documented
- [ ] There is a follow-up initiative to deprecate Prometheus

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
December 31, 2022 

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by jhouse-solvd** [comment]
In speaking with Kyle, we should prioritize "top-tier" monitors to know which are the most important. 

Monitors, rulesets, alerts, metrics, etc should be listed in sequential order and then issues created to tackle them one-by-one.

**Comment by mchelen-gov** [comment]
Is there internal documentation that needs to be created or updated?

**Comment by jhouse-solvd** [comment]
> Is there internal documentation that needs to be created or updated?

updated definition of done

**Comment by jhouse-solvd** [comment]
@ph-One and I were thinking that we may need to re-examine PagerDuty teams and services in light of the recent team restructuring.

**Comment by jhouse-solvd** [comment]
It might be better to scope this work to focus on Alertmanager rules related to critical monitors, ie "devops-critical" and "vsp-engineers-critical" (added to background context above)

**Comment by jhouse-solvd** [comment]
**How this initiative is broken down:** 
- Epics exist for major platform components and services
- Epics contain individual issues for sub-components and services
- Issues are scoped to set up a dashboard, monitors, and alerts for the service/thing to be monitored

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Can you add this initiative to the DE product board?  It is currently in progress.
