### ISSUE TITLE
Profile Team | Sprint 84 | Oct 5 - 18 (draft)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47028]
## PTO/OOO/Unavailable

- **Adam**: 
- **Christina**:  Oct 5
- **Sharon**:  
- **Tom**: 
- **Samara**: 
- **Liz**:  

## Sprint Priorities

---

#### FE - Adam
- [ ] PLACEHOLDER

#### FE - Adam
- [ ] #44532 Update Phone #'s to Correct Error Responses (3 pts)
- [ ] #21587 Tech debt (1 pt)
- [ ] #32963 Text falling outside container (2 pts)
- [ ] #44886 Update UI Alerts for Address Validation Use Cases
- [ ] #43481 Fraud alerts
- [ ] #47477 Military/Alert updates
- [ ] #47473 Remove Feature Flags for Notifications

#### FE - John
- [ ] #46150 Alert - add blue border (1 pt)
