### ISSUE TITLE
[PM] Payment Info V2: UAT Go/No Go

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47037]
## Background
Schedule and hold UAT go/no go before proceeding with UAT

## Tasks
- [ ] Schedule Go/no go
- [ ] Complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/uat/v2-go-nogo.md)
- [ ] Perform any follow up actions if needed

**Comment by ericasauv09** [comment]
closing as this is a duplicate ticket
