### ISSUE TITLE
INTL - Debt Portal Edge Case - Domo Dashboard Build

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47033]
## Issue Description
This is an internal tracking ticket for the [Debt Portal Edge Case Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42360)

This work item is to take the data from [Debt Portal - Data Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45142) and build the Domo Cards/Dashboards.

---
## Tasks
- [x] Build cards
- [x] Configure dashboard

## Acceptance Criteria
- [x] When dashboard is available for QA testing.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
@michelle-dooley - First draft of the [Combined Debt Portal dashboard](https://va-gov.domo.com/page/1976847942) is ready for review! I made some deviations from the mockup, so maybe we can discuss in grooming tomorrow before official design QA in case you have any notes. Thanks!

**Comment by chloedotbrown** [comment]
Data QA of dashboard is complete per #47399 .

@michelle-dooley - I didn't have time to do a pre-QA for design, but I think it's fine to barrel on ahead while I'm out. I'll just expect to come back to a to-do list of things I missed in the build!

**Comment by michelle-dooley** [comment]
@chloedotbrown - unfortunately I did not get to this while you were out, GA issues I need to figure out took all my time.  This is on my list today.
