### ISSUE TITLE
Field Mapping Based on Workflow: Section II - "Add Spouse"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4703]
## Goal
Ensure that each field required in the 21-686c paper form is cross-checked for accuracy and properly represented in the VA.gov form with either 1:1 coverage or material field coverage.  

## Considerations
Some fields will simply transfer exactly, where others will collect information differently (e.g. addresses using individual fields vs. single field entry). The paper form has a potentially non-linear flow; whereas the VA.gov form system requires linear, or looped data entry.

## Tasks
- [ ] Break-out fields in paper form to visualize relationships of required information  
- [ ] Confirm all required data is collected within digital workflow
- [ ] Identify paper form fields by number in the mapped workflow

## Acceptance Criteria
- [ ] Fields for this section are confirmed and accounted for; fields are mapped to digital workflow by number

**Comment by sporeboy** [comment]
VA 21-686c Paper form mapped to VA.gov implementation here: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/
