### ISSUE TITLE
[PM] | Launch Readiness | BAI

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47032]
### **Description:** 

As we get closer to being ready to release BAI, there are several tasks that need to be completed before we begin a phased roll-out.

### **Tasks:** 

- [x] Test GA widget
- [x] Conduct Internal UAT
- [x] Go/No Go call: [Launch Readiness doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/product/launch-go-no-go.md)
- [x] Release 25% and monitor for 3-5 days
- [ ] Release to 50% and monitor for 3-5 days
- [ ] Release to 100%

FYI: ([Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/product/release-plan.md))

**Comment by SKasimow** [comment]
Release at 25% today. Will use other release tickets to con't tracking so closing this now.
