### ISSUE TITLE
BE | Profile | Documentation. for Notification Settings

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47040]
## Background

Create a document that provides an overview of the back-end services and systems that support the Profile Notification settings information page.

## Tasks
- [ ] Add documentation for Notification settings information

## Acceptance Criteria
- [ ] Share documentation to the team for review and feedback
- [ ] Add link to documentation from Notification settings product outline

**Comment by tpharrison** [comment]
Hi @SKasimow - I think this is already done.  The BE document is [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/notification_settings/backend_documentation.md) and is linked to from [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#backend).

**Comment by SKasimow** [comment]
@tpharrison - ok thanks; I will close this out
