### ISSUE TITLE
Centralize Logging and Monitoring

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#47043]
## Problem Statement 
Currently:
- Logging and metrics are spread across multiple systems making them difficult to correlate by Platform and VFS teams
- Multiple systems have to be maintained by Platform creating maintenance overhead 

How might we consolidate logging and metrics as much as possible to allow ease of traceability?
How might we reduce the number and variety of systems that must be maintained?

## User Impact
*How many users are being affected? What kind of user (VFS engineer vs. VFS designer)? What is this blocking those people from doing? What would fixing this problem allow the impacted users to do faster/better?*
- Platform and VFS engineers are blocked from accurately understanding and debugging applications
- Platform and VFS engineers are blocked from developing and enhancing monitors and alerts

## Where was this problem reported?
*Is it something that came to light because it was mentioned in many support requests? Was it found in research? Was it a theme of the satisfaction survey?*

Reported frequently in Postmortems and support issues from both Platform and VFS teams

## How well do we understand the problem?
*It’s ok if you don’t know but any context would be helpful if it is known. Is the problem that a previously agreed upon infrastructure decision is keeping us from utilizing a industry standard feature in our pipeline? Is the problem that OCTODE no longer has a research resource so we can’t support research in Collab Cycle anymore?*

We have a good understanding of the technical problem space and have identified potential solutions.
Areas which need further investigation:
- What are our log retention requirements, how do these affect migration, deprecation or sunset?
- What roles and permissions are needed by VFS teams to effectively leverage logging and metrics system?

## What is the acceptance criteria?
*This should be written in a way that no one can interpret it differently. It should be written from a user impact perspective. A good acceptance criteria isn’t “We built a new service to allow VFS teams to deploy on their own” it’s “A VFS team member is provided with all the information and resources needed to deploy their code without Platform intervention.” Above all else, acceptance criteria should be testable, simple/straightforward, written in the perspective of the user and specific to the item they are supporting with no outside dependencies.*

- [x] A single centralized system provides:
  - [x] Logging
  - [x] Metrics
  - [x] Alerting
- [x] System is accessible to Platform and VFS users
- [x] Users have sufficient permissions to effectively use tools, without risk of causing negative impact to other users
- [ ] Legacy logging and metric systems are deprecated
  - [ ] Access by VFS and Platform teams is disabled
  - [ ] Alerts to other systems (Slack, PagerDuty) are disabled
  - [ ] Documentation is removed
  - [ ] Timeline for sunset of systems is created
  - [ ] Work item for sunset of legacy systems is created
- [x] Documentation exists for usage by Platform and VFS teams
- [x] Onboarding and offboarding processes exist and are documented

## How should we measure success?
*What are the key performance indicators? What do we expect solving this problem to impact? How should we measure the impact (both where should we pull the data from and what should the calculation be)? Do we need to start the project by defining baselines or do they exist somewhere?* 
- How many incoming alerts can be resolved using system
- How many VFS support requests can resolved using system 
- How many legacy systems are deprecated

## TODOs
- [x] Convert this issue to an epic
- [x] Assign project team name
- [x] Identify this project's OCTO and Vendor key POCs
- [ ] Identify specific VFS teams to be part of this project's acceptance
- [ ] Identify project target end date
- [x] Conduct project kickoff meeting
- [ ] Develop and implement project communication plan

**Comment by andreahewitt-odd** [comment]
@mchelen-gov Looks good but I'm struggling to understand the success metrics. What does "Resolved" mean? Can you walk me through an example of both?

**Comment by mchelen-gov** [comment]
> @mchelen-gov Looks good but I'm struggling to understand the success metrics. What does "Resolved" mean? Can you walk me through an example of both?

- Alert generated -> Received by oncall -> Debug with data in observability tool -> Resolve alert
- VFS support request for information -> Point to data available in observability tool -> Resolve support request

Do these examples make sense?

**Comment by laineymajor** [comment]
Problem: We do not currently have an automated way of tracking data re vets-website CDs.

Having the CI pipeline feature in Datadog would allow us to track number of vets-website CDs, and create an automated dashboard to measure this data within Datadog.

**Comment by jhouse-solvd** [comment]
Thoughts from refinement 9/22/22: 

- Can we give some examples of maintenance? 
- Can we give some examples of correlation? 
- How might we capture alerting fatigue / quality-of-life for operators in the problem statement? 
- To stay true to scope: avoid over-optimization, before the primary goal of centralizing (MVP)
- Are there security and compliance requirements that consider? 
- What are the areas of uncertainty (ie different needs of various teams) that we have? 
- Future: It would be good to standardize logs
- Clarify assumption: Can we grant VFS users access to Datadog through DOTS? 
- For Datadog for VFS teams: There should be clear documentation for usage and support 
- It would be good to clarify the difference between **deprecation and sunset**
- Deprecation means that we are in a position to say: "this is no longer the tool to use" 
  - Platform Website updated to remove the legacy product(s)
  - Support no longer offered for the legacy product(s)  
- Sunset means we are ready to fully decommission the system and turn it off 
- We don't yet know what the blockers are to turning it off

**Comment by annekerr49** [comment]
[https://app.zenhub.com/files/133843125/b78aaf6a-6c51-4f7b-8ba5-e3940335968f/download](https://app.zenhub.com/files/133843125/b78aaf6a-6c51-4f7b-8ba5-e3940335968f/download) @andreahewitt-odd

**Comment by jhouse-solvd** [comment]
[Datadog] Set up monitors and alerts for AWS #47541

**Comment by jhouse-solvd** [comment]
This was accidentally closed. Re-opened.

**Comment by mchelen-gov** [comment]
@jhouse-solvd 
> Thoughts from refinement 9/22/22:
> 
> * Can we give some examples of maintenance?
- Installing security updates
- Scaling infrastructure
- Performing onboarding & offboarding
- Debugging issues

> * Can we give some examples of correlation?
- Metrics show CPU usage spiking at 1:23, what events are occurring in logs at that time?
- See postmortems for additional examples

> * How might we capture alerting fatigue / quality-of-life for operators in the problem statement?

The part of that problem being addressed here specifically is friction of moving across different observability systems.

> * To stay true to scope: avoid over-optimization, before the primary goal of centralizing (MVP)

:+1: 

> * Are there security and compliance requirements to consider with respect to logs or metrics data (e.g. retention/archival)?

Added to section "How well do we understand the problem?" please feel free to expand.

> * What are areas of uncertainty (ie different needs of various teams) that might exist (e.g. use cases, support, access to tools)?

Added to section "How well do we understand the problem"

> * Future: It would be good to standardize logs
> * Clarify assumption: Can we grant VFS users access to Datadog through DOTS?

Yes, however we need to define roles and permissions.

> * Datadog for VFS teams: Documentation for usage and support should be part of AC
> * It would be good to clarify the difference between **deprecation and sunset**
> * **Deprecation** means that we are in a position to say: _"this is no longer the tool to use"_
>   
>   * Platform Website updated to remove the legacy product(s)
>   * Support no longer offered for the legacy product(s)
> * **Sunset** means we are ready to fully decommission the tool and turn it off
Clarified in AC.

> * What are the **blockers** to _deprecation_? to _sunset_?

**Comment by jhouse-solvd** [comment]
Should we rename this project to "Centralize Logging and Monitoring"? _just a thought_

For the most part, metrics are collected across all systems. However, those metrics should be used to create monitors that provide value to platform operators. With those in place, it's possible to "centralize monitoring" by empowering operators to rely on a single source of truth.

**Comment by jhouse-solvd** [comment]
There's info in #47100 relevant to centralized logging, and what type of tooling is needed moving forward.

**Comment by mchelen-gov** [comment]
> Should we rename this project to "Centralize Logging and Monitoring"? _just a thought_
> 
> For the most part, metrics are collected across all systems. However, those metrics should be used to create monitors that provide value to platform operators. With those in place, it's possible to "centralize monitoring" by empowering operators to rely on a single source of truth.

@jhouse-solvd Yup, we could generalize this as centralized observability, which consist of logging, metrics, and alerts. I revised the AC slightly to explicitly call out alerting in addition to logging and metrics:
> A single centralized system provides:
> Logging
> Metrics
> Alerting

**Comment by jhouse-solvd** [comment]
See #42770 for relevant work related to logging w/ Datadog.

**Comment by jhouse-solvd** [comment]
@mchelen-gov - Can you add this project to the DE product board?  It is currently in progress.

**Comment by jhouse-solvd** [comment]
Question from @ericboehs - Does the AC include 'application exceptions'? (ie Sentry) 

We think that would be its own project, but would be good to get some additional clarity for that into the roadmap.

**Comment by mchelen-gov** [comment]
> Question from @ericboehs - Does the AC include 'application exceptions'? (ie, Sentry) 
> 
> We think that would be its own project but it would be good to get some additional clarity for that into the roadmap. 

It doesn't include runtime application error / real user tracking (Sentry) at this time. I agree that would be a good follow up.

**Comment by jhouse-solvd** [comment]
UPDATE 1/31 (also shared during weekly Team of Teams meeting)

**Monitoring for VFS teams: Read-only (RO) access to Datadog - beginning February 21** 

We’re excited to announce the upcoming release of Read-only (RO) access to Datadog for VFS Teams beginning February 21, 2023!

**What’s included in the upcoming release?** 

- VFS Team members will be able to access Datadog and view dashboards and monitors. 
- Documentation will be made available on the Platform Website covering the following topics: 
  - Datadog overview - Welcome, here’s what to expect
  - Dashboards and monitors - a list of pre-configured dashboards with health and performance data for major backend applications (ie Vets-API and related services) with accompanying explainer info!
  - How to request access to Datadog (for new VFS Team members, post-release) 

**How will VFS teams get access?** 
- As part of this release, we plan to invite existing VFS team members in bulk. 
  - VFS team members can expect to receive an invite to Okta from DOTS the week of 2/21
  - VFS team members will launch Datadog from DOTS Okta 
  - Note: DOTS Okta is the single-sign-on solution used to access tools provided by DOTS
- After this release, new VFS team members will request access to Datadog through the Platform Website or through #vfs-platform-support

**What do VFS teams need to do before then?** 
- Nothing at this time. :) However, please let us know of any issues or concerns through issue #33081. 
- Stay tuned for additional updates in upcoming Team of Teams meetings and Slack!

cc: @mchelen-gov

**Comment by mchelen-gov** [comment]
@jhouse-solvd Do we have an example to use of logs which are appearing in Loki but not DD?

**Comment by mchelen-gov** [comment]
Reference: logging pilot https://github.com/department-of-veterans-affairs/va.gov-team/issues/42770

**Comment by annekerr49** [comment]
Last status update  longer than 30 days.

**Comment by jhouse-solvd** [comment]
**Project status update 4/18:**
_Note: This update was shared during Team of Teams on 4/18_

**Datadog: Platform Monitors and Alerts using Infrastructure as Code (IaC)**  

- We’re developing a process and guidance for deploying Datadog resources using IaC (ie, Terraform)
- This helps ensure that important dashboards and monitors are not inadvertently modified or deleted 
- And will help us provide a framework for VFS and Platform teams to automate the creation of dashboards, monitors, and alerts (and backup their Datadog configuration)
- We’ll also provide documentation in the with instructions, guidance, and best practices for deploying monitors via code
- Feel free to checkout [issue #56046 in the va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56406) and stay tuned for more!  

**Datadog: Write access for VFS Teams… next steps!**

- We’re writing up a [separate project](#55777 ) to capture the work needed to offer write access to VFS Teams
- We feel it wise to make this a project with a definition of done that’s distinct from Platform-facing observability work 
- The project will be shared with VFS users and stakeholders in the next couple of weeks to gather feedback 
- OCTO and Platform leadership will help us prioritize the project and come up with an estimated release timeline soon    

**Reminder: Datadog for VFS Teams support** 

- If you need access to Datadog, please visit [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) on the Platform Website
- Or, submit a support request in #vfs-platform-support on DSVA Slack

cc: @mchelen-gov @npeterson54 @ph-One

**Comment by npeterson54** [comment]
All remaining AC will be moved into new projects and this is ready to close out.  The 3 proposed projects can be found [here](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2576711753/20230324+Platform+Monitoring+Roadmap+Discussion)
