### ISSUE TITLE
GA4:  Design System Components - Testing & Validation

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47047]
## Issue Description
Design System team will be implementing the FE code for their components.  We will work with the team to test those tags/triggers to ensure they are working as expected and we are not missing anything.

[GA4 events](https://docs.google.com/spreadsheets/d/1XDceQQVK6IGOl8R1OzhbncSc1Hrs37IEyQblW_Spk-Y/edit#gid=1403781092)

[GA4 Planning doc](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=0)

---
## Tasks
- [ ] Frontend code is implemented (dependency)
- [ ] QA/validation against UA
- [ ] Confirm all components configured and tracking
- [ ] Make changes as applicable.

Web Components:
- [ ] va-on-this-page
- [ ] va-promo-banner
- [ ] 

## Acceptance Criteria
- [ ] When all components have been implemented and tested.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
va-on-this-page and va-promo-banner have been implemented and tested.  

va-promo-banner:  working as expected, continue testing on other pages
va-on-this-page:  not pulling in click_text as expected, ticket submitted with GA to determine why

**Comment by michelle-dooley** [comment]
[Component tracking worksheet](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=2089299676)
