### ISSUE TITLE
[Discovery] Lighthouse API for CDW data

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47069]
## Issue Description
We understand that payment data is available on the Corporate Data Warehouse "CDW" and that lighthouse might be able to establish an API for the debt portal to collect this data.  

---
## Tasks
- [ ] Reconnect with Light house team (Kelly Lein & Dave Mazik) to define path forward to establish API. They have a standing weekly meeting we can join to kick off discussions. 

## Previous Discussions: 

**Kelly Lein:** _"I started a conversation with some of our API teams that interface with CDW (Veteran Health APIs and Facilities API) and we confirmed that we do not currently pull this data.  It does sound up our alley though so please reach out to @Dave Mazik if you’d like to talk about adding this to our Roadmap."_

**Dave Mazik:**  Dave said..  "_I think this could be 1 of the following requests.  To make sure I point you in the right direction, could you help me see which one(s) it might be:_

1. You have a team that is going to build this API somewhere in VAEC but want to make it available on Lighthouse.
2. You have a team that wants to build an API to onboard to Lighthouse and have it live in a Lighthouse VAEC/AWS account/instance.
3. You want the Lighthouse team to build this API."

We requested option 3 and he said the lighthouse team needed a bit more information regarding the APIs we need and they would do a bit of thinking it and get back to us. 

## Acceptance Criteria
- [ ] Determined next steps and identify path forward
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Work will continue in #47391
