### ISSUE TITLE
FE | Profile | Sign-in updates for MHV and DS logon users

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47070]
## Background

In #27979 Design confirmed with the Identity team that there isn't a sign in email address for MHV or DS Logon users so showing a prompt for these users to "view or edit" their sign-in email address is mis-leading/confusing.

Currently we have this prompt showing in 2 places:

1) **Account security** page 

2) **Contact information** page

This ticket is to complete the front end work associated with design updates. Because there isn't a sign in email address for MHV or DS logon users, we will **hide the sign in email conditionally ** for these users when viewing the **Contact info** page. We will also update the copy on the **Account security** page to reduce confusion for these users. 

The new mocks are linked in the Task section. The changes to the current page can be viewed in the comments section.

## Tasks
- [x] Conditionally hide the "sign in email" section on the contact information page for MHV or DS logon users ([mock up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/PG822vj))
- [x] Replace the word "email address" with "information" in the Sign-in email section of the Account Security page along with the content that follows ([mock up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/v/89kmvO/a/3OYm1ew/r/qjKyb3))
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
 - [ ] Validate Changes in Staging (PM or Design)

## Acceptance Criteria

- [x] "Sign in Email" section does not show in the contact information page for MHV or DS logon users
- [x] In the account security page under sign-in, the copy is changed in several places to read "information" instead of "email address" and matches the mock-up 
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Validate in staging using an MHV or DS logon
- What updates need to be made (e.g. product outline, use cases, contact center guide) 
     - Sketch files
     - User flows
     - Contact Center guide
     - Check product outline

## Associated Tickets
- #26950

**Comment by SKasimow** [comment]
**Contact information page**
![Section to Hide on Contact Page.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/eb2b1838-d3db-4bbd-8c6c-19a5cfa445d6)

**Comment by SKasimow** [comment]
**Contact information page** changes needed:
![Section to Hide on Contact Page.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/eb2b1838-d3db-4bbd-8c6c-19a5cfa445d6)

**Comment by adamwhitlock1** [comment]
This can be validated @mtcA6 I will get with you to validate if you would like, otherwise logging into staging with an MHV or DSLogon user you should be able to see my changes now in staging.

**Comment by mtcA6** [comment]
@adamwhitlock1 i see MHV users on the list are there DS logon users?

**Comment by adamwhitlock1** [comment]
there is one DSLogon user that actually works :(

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/ds-logon-lower-env-test-accounts.md

At the bottom there is `sofia.mckibbens` and even her login doesn't _really_ seem to work fully as the contact info doesn't seem to load correctly at all, but the acttount security section shows the correct updated UI, and I think that works for validating this. I just checked it out and it looks like this:

![Screenshot 2023-06-07 at 8.13.45 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/a4c10949-e575-4811-97a1-e2c77e534901)
