### ISSUE TITLE
Standard Monkeypox Vaccine Template (I-0001436 + I-0001437)

### ISSUE THREAD

**Issue by ahicksfearless** [department-of-veterans-affairs/va.gov-team#47075]
- [x] Draft a Standard Monkeypox Vaccine Template 

- [x] Review with Justin & Shane

- [x] Message cannot imply any condition, such as saying they are high risk or identified as a candidate

- [x] Includes the facilities phone number to call

- [x] Should not explain what Monkeypox is

Intake Numbers
[I-0001436](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvapm.lightning.force.com%2Flightning%2Fr%2Fa1d3d000000pUdJAAU%2Fview&data=05%7C01%7C%7C5d49750acee2425be7bf08dba591dde3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638285818128737910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nQEVVN8gM9PTwnYcEHp%2BV7%2FNGbky%2FVedpzw2p8L7yyY%3D&reserved=0)
[I-0001437](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvapm.lightning.force.com%2Flightning%2Fr%2Fa1d3d000000pd2rAAA%2Fview&data=05%7C01%7C%7C5d49750acee2425be7bf08dba591dde3%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638285818128737910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xD6e%2BL9vEH9VV%2FZ4BKjKCg3vu%2FgWHPEzlZyNwOUMvpg%3D&reserved=0)

**Comment by jwowk** [comment]
Template created and made available using Ad-Hoc tool for interested sites:

The VA would like to notify you that the vaccine approved for prevention of Smallpox and Monkeypox is now available.
It is given as a two-dose series, 28 days apart. For more information or to schedule an appointment, call 305-575-7250.

Please reply STOP to end messages.
