### ISSUE TITLE
Updates to RFC Artifacts

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#47090]
### Description

In a recent Arch. Working Group meeting there was discussion on improvement / refinement of the RFC process now that we have been working with it for some time. The main items to address are:

**Tasks**
- [ ] Add a checklist to the PR template
  - [ ] Comment date has been lapsed
  - [ ] Comments have been resolved
  - [ ] Content from comments have been incorporated into body of document
- [ ] Use GitHub Actions to add round robin assignment for assignee
- [ ] Add new or update columns to the Arch Board
  - [ ] Change Ready column to Open or Open For Comment
  - [ ] Add column named Ready For Review
  - [ ] Add column named Approved or Ready To Merge
- [ ] Update README for RFC with definition/purpose of the columns

### Acceptance Criteria

- [ ] Checklist has been added to RFC template
- [ ] Arch WG Board has been updated with column changes
- [ ] Documentation located in README has column information added

### Subject Areas

- [ ] Product
- [ ] Design
- [X] Engineering
- [X] OCTO-DE
