### ISSUE TITLE
Remove research support in VFS-facing DI and MPR guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47105]
## User Story
As a VFS team member, I want to know what practice area feedback I'll receive at Design Intent and Midpoint Review so that I am able to better prepare for those touchpoints and manage my teams expectations.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
Due to Clayton Zook's departure on Wednesday 9/7, Governance team is no longer able to provide research-focused feedback at the Design Intent or the Midpoint Review. Because of this, we need to update our VFS-facing guidance on Platform Website so that VFS teams are not expecting to receive feedback.

In addition, because Clayton is no longer involved in the Research Review, OCTO-DE is once again the Owner of the Research Review touchpoint. This ticket will also ensure that VFS-facing guidance is updated to show that Governance team is not involved in the Research Review touchpoint.

## Impacted Artifacts
Touchpoints page - [Platform Practice area table](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints)
[Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
[Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
Image from [CC homepage](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Review Platform Website/Collaboration Cycle and identify all the areas where we specify that research feedback is provided at DI and MPR
   - Note: Research Review is still part of the Collab Cycle. So references to research support are ok, it just needs to be removed at specific touchpoints.
- [x] Link all impacted pages above in the "Impacted Artifacts" section
- [x] Ensure all references to research support are removed from Design Intent guidance
- [x] Ensure all references to research support are removed from Midpoint Review guidance
- [x] Note: If changes are made to either the DI or MPR script, the script needs to be modified on Platform Website AND in the Moderator Responsibilities docs

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams do not expect to receive research feedback at Design Intent and/or Midpoint Review
- [x] VFS teams understand that OCTO-DE, not Governance team, is the Owner of the Research Review touchpoint

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by allison0034** [comment]
@shiragoodman I noticed "Note: Research Review is still part of the Collab Cycle. So references to research support are ok, it just needs to be removed at specific touchpoints." Does that mean delete the [research review page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review)? I assumed that would stay where it is, but we would remove any references to research feedback in DI, MR and SR.

**Comment by shiragoodman** [comment]
@allison0034 Do not delete the Research Review page. The note was there to imply that the Research Review is still part of Collab Cycle. VFS teams will no longer receive research support ad DI or MPR (aka the specific touchpoints). Make sense?

**Comment by allison0034** [comment]
Yes... that is what I wanted to confirm, thank you

**Comment by allison0034** [comment]
@shiragoodman why do we need to remove the Image from [CC homepage](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)?

**Comment by shiragoodman** [comment]
@allison0034 we don't need to remove it, just edit it. Right now there's an asterisk next to Research Review, but there shouldn't be bc we no longer have a team member that supports that touchpoint. The image is just a screenshot from the General orientation slidedeck, so feel free to fix the slide deck, take the screenshot and upload it to the CC Overview page.

**Comment by allison0034** [comment]
@briandeconinck this is ready for review. The image on the CC homepage is waited to be updated with the next confluence update. For now you can view it [here](https://vfs.atlassian.net/wiki/spaces/CC/overview). The asterisk is removed from Research Review

**Comment by briandeconinck** [comment]
@allison0034 One thing I noticed: The [Research Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) still says the owners are "Governance Team and OCTO Research Lead." I think Governance should be removed, right?

**Comment by allison0034** [comment]
@briandeconinck I removed it. [Research review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781891143/Research+review)

**Comment by briandeconinck** [comment]
@allison0034  Perfect. Everything else looks good to me!
