### ISSUE TITLE
PowerBI reporting updates based on user feedback - 1st iteration #1158

### ISSUE THREAD

**Issue by Cmjones233** [department-of-veterans-affairs/va.gov-team#47107]
FROM CHIP ZENHUB

**Problem Statement / Objective**
Based on the user interviews with stakeholders and staff, we have decided on a first iteration of updates based on this feedback.

1. Quality of life filter improvements
      A. Expand clinic dropdown to see full name of clinic
      B. Add option to filter by location/site
      C. Add option to filter by clinic group/type
2. Table page with graph breakdown
      A. Segmented graph based on filters applied (reflection of other pages, no new info)
      B. Includes breakdown of clinic/station names in visual representation
13.Definitions Page
      A. Glossary of all terms used for reference (EX: Completed Check-in = Veteran successfully checked in to appointment)

Link to UX research findings (Interviews completed, full documentation still in progress)

**Task**
Complete 1st iteration of PowerBI reporting updates based on user feedback

**Acceptance criteria**
- [x] Quality of life filter improvements have been completed
     - [x]  Clinic dropdown width has been expanded to see full name of clinic
     - [x] Option to filter by location/site has been added
     - [x] Option to filter by clinic group/type has been added
- [x] Table page with graph breakdown has been added
     - [x]  Includes segmented graph based on filters applied (reflection of other pages, no new info)
     - [x]  Includes breakdown of clinic/station names in visual representation
- [x]  Definitions page has been added
     - [x] Includes glossary of all terms used for reference (EX: Completed Check-in = Veteran successfully checked in to appointment)
- [ ] Stakeholder approval for posting changes has been received
- [ ] Changes have been deployed to production shared PowerBI link

Dev Notes
(_Any additional development details_)

Product Notes
(_Any additional product details_)

Pull Request Link
(_Link to pull request for this ticket_)

Other Links
(_Any relevant links)_

**Comment by Cmjones233** [comment]
completed this portion. Pitch deck on new card
