### ISSUE TITLE
[FE] Add New Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47115]
## User Story
As a Veteran, I would like to know that if I wait more than 15 minutes in the waiting room I should talk to an MSA just in case I am not checked in.
 
## Wireframes
See this ticket

## Tasks
- [ ] [FE] **Add content**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
