### ISSUE TITLE
Service Design support 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47119]
## Purpose
This supports upcoming research, mapping discussions and creation, and exploring the impacts of the shift to project-centric to our in-progress mapping work. 
## Tasks
- [x] Assist @tayism with Platform team interviews as needed 
- [x] Assist @twoangstroms with our mapping workshop(s) as needed 
- [x] Organize examples of end-to-end journey mapping
- [x] Schedule sharing session
- [x] Demonstrate and discuss mapping examples internally

## Acceptance Criteria
- [x] Tasks (TBD) completed for Platform team interviews 
- [x] Tasks (TBD) completed for the Mapping workshop(s) 
- [x] Examples of end-to-end journey mapping edited and prepped for sharing
- [x] Mapping examples demoed and discussed internally
