### ISSUE TITLE
[FE] Day-of Check-in: Add Content for 15-minute Wait Message to Confirmation Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47116]
## Wireframes
[wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/9164ff31-83ec-41c5-8841-169077282e59/commits/0db2f1608417d8c6c664f509ee0de6885ca7bc96/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/43283FE4-5CEF-4571-9FD0-DDC85FE19503?collectionId=e34f4cad-7268-4a1d-86e7-29e8ec02c1f8&collectionLayerId=f8da92d8-569a-4dd5-a2a9-eeebeeb33370&mode=design)

## Tasks
- [ ] [FE] Add "If you wait more than 15 minutes, tell a staff member." so the end of the Day-of Check-in Confirmation Page message in the blue box for an in-person appointment only
- [ ] Add to (or make sure its in the) [translation doc](https://docs.google.com/spreadsheets/d/1xv63kaIR_UMq1bssSleMODXEV14OOGwfcL41rBBWhwk/edit#gid=14407571)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
