### ISSUE TITLE
[UX] Update Product Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47117]
## Description
Update various product artifacts, as necessary, based on the feature release.

## Tasks
- [x] Update the PCI Product Guide, including content and screenshots
- [x] Update the CI Product Guide, including content and screenshots
- [x] Update the Poster
- [x] Update user flow diagrams, as necessary
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov

## Acceptance Criteria
- [x] Product Guides are up-to-date (content & screenshots)
- [x] Poster is up-to-date
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm)
- [x] R&D articles are up-to-date

**Comment by benbrasso-agile6** [comment]
posted to git - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md

**Comment by benbrasso-agile6** [comment]
@zach-park in the user flows, on the last square, can you update the wording to read: 

We'll come get you from the waiting room when it's time for your appointment to start. If you wait more than 15 minutes, tell a staff member. 

Here's a link to the user flow in abstract: 
https://share.goabstract.com/3d58748e-1359-4a5c-afc6-c8514ddc2a73?collectionLayerId=aeda98c5-f71f-487d-b70e-8297d0d59866&mode=design

CC @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 once that's updated, we can re-add that user flow in the day of check in product guide.

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 , [user flow is updated](https://share.goabstract.com/3d58748e-1359-4a5c-afc6-c8514ddc2a73?collectionLayerId=aeda98c5-f71f-487d-b70e-8297d0d59866&mode=design).

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @zach-park I've updated the product guides and posted to git - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md

**Comment by benbrasso-agile6** [comment]
Nice work
