### ISSUE TITLE
Certificate of Eligibility | Update to web components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#47111]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the COE components are updated to the latest recommendations
**_So that_** we can ensure we're releasing a quality product

## Background Context

The COE form contains a few React components that need to be updated to use web components, including, but not limited to:
- OMB → `va-omb-info`
- Telephone → add `tty` prop
- Download link →`va-link`
- TextInput → `va-text-input`

## Tasks

- [ ] Update components as needed
- [ ] Update unit & e2e tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Most components have been updated, with the exception of the `FileInput` which was not updated because of unit testing problems. I will close this ticket and open a new one once `va-file-input` is updated to allow testing
