### ISSUE TITLE
[FE] 10-10EZ - American Indian question content updates

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#47128]
## User Story

Update the content on the American Indian page to reflect the approved direction that aligns the statute and the paper form with online standards.

## Related Documentation

- [[Design] 10-10EZ - American Indian question: Update the dropdown info content #46295
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46295)

SKETCH FILES
- [Desktop Mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kaqkZeg)

## Description

> If any of these descriptions are true for you, you may not need to pay a copay for care or services.
> Are any of these descriptions true for you? (*Required)

> - You’re a member—or the first- or second-degree descendant of a member—of a tribe, band, or other organized group of Indians, including those terminated since 1940 and those recognized now or in the future by the state you live in (note: this applies whether or not you live on or near a reservation), or
> - You’re an Eskimo or Aleut or other Alaska Native, or
> - You’re considered by the Secretary of the Interior to be an Indian for any purpose, or
> - You’re determined to be an Indian under regulations put into effect by the Secretary of the Interior, or
> - You meet any of these descriptions and you live in an urban center (a community that the Secretary of the Interior has determined has a large enough urban Indian population with unmet health needs to warrant assistance under title V of the Indian Health Care Improvement Act, or IHCIA)

> [Learn more about the IHCIA on the Indian Health Service website](url)

## Tasks
- [ ] Update content on : 1Veteran Information > American Indian page
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by longmd** [comment]
@hdjustice / @markfallows , the content update for this is available in staging.

**Comment by hdjustice** [comment]
Confirmed new American Indian page is in Staging, and updated per new design.

![image](https://user-images.githubusercontent.com/92328831/192000833-467b07d1-4d6b-46c1-8f1f-d5a25bce9c16.png)


Confirmed that the question appears on the Review page and can be successfully edited and saved

![image](https://user-images.githubusercontent.com/92328831/192000995-5fe46f4a-d0c8-4b0a-b564-99d709c9a304.png)

![image](https://user-images.githubusercontent.com/92328831/192001312-d4210624-0c0a-4191-880e-ace5fcffc573.png)
