### ISSUE TITLE
Design | Profile | Research Artifacts | Profile editing evaluation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47136]
## Background

As a designer/researcher for the Profile Team, I want to be able to understand how a Veteran currently interacts with the address validation/editing flow so that I can create a more accurate description of what needs to be further developed or iterated upon.

One consideration we want to explore is whether moving from _in-line editing_ to _one-per-page_ editing will improve this flow, which has been noted as being especially difficult for screen readers.

## Tasks
- [x] Document  a research plan [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) and conversation guide
- [x] Send materials to PO and PM for review 
- [ ] Implement updates as needed

## Acceptance Criteria
- [ ] The research plan and conversation guide are submitted for recruiting kick off

**Comment by andaleliz** [comment]
Hi @SKasimow and @Samara-Strauss - here are the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/conversation-guide.md) for our upcoming research.

The conversation guide is a little lighter than normal, because I'm going to try to let the participants go through the contact page on their own as much as possible rather than prescribe exactly what to do. I want to try to get to "natural" behavior as much as possible, and ask questions during critical moments or when they're all done. My goal is get them to edit 3 pieces of contact information so we can evaluate how easily they can do this all from one page.

I also put together [a very basic prototype](https://codepen.io/surfbird/full/vYjxQWy) that we can review at the end of the session, if we have time with people. It's a concept of what one thing per page could look like, just to aid a conversation of whether or not this is an improvement.

I'll submit this for recruiting once we are all aligned the plan and guide. Thanks in advance for your review!

**Comment by SKasimow** [comment]
Looks good to me @andaleliz!

**Comment by Samara-Strauss** [comment]
### Research plan

This looks good to me! A few thoughts on recruiting:

- I would be less restrictive on the sex breakdown, given that (obviously) most veterans are men, meaning that's going to be a much larger pool of folks with cognitive issues or disabilities. I wouldn't request more than a 50/50 split, or make it a secondary requirement.
- I would also be less strict on the racial breakdown, unless there are good reasons to assume an even split among different racial groups and not including white veterans with cognitive issues or disabilities will have a big impact on our findings. 
- Idk if we need to be so restrictive with education level, since someone could have a college degree and still need assistive tech or have trouble using our forms due to a disability. But I'll leave that up to you to change or not. That could be one thing we could relax if we have difficulty recruiting.

To be clear, I'm all for recruiting a diverse group and understand we don't want a homogenous sample, but I also want Perigean to be able to recruit and for us to be mindful about what is absolutely necessary for this study. In this case, our primary focus is recruiting folks who need assistive tech, so let's be flexible where we need to be.

### Conversation guide

#### First Task: Update contact information - 10 minutes

- For address validation, make sure that changing one digit in the zip code of an otherwise correct address will trigger this flow. Address validation works off of confidence scores, and sometimes, it will allow you to save an address that is not correct but is so close that it's likely correct. Maybe you've already tried this, but just wanted to call it out in case.

#### Third Task: Reverse any unwanted changes in contact information - 5 minutes

Should we do this second so people aren't worried that their info will be left incorrect?

#### Fourth Task: Review prototype - 5 minutes

The difference between this and what we have now is really subtle since it's a rough prototype. I almost missed it myself. I'll be interested to see if people even notice a difference (maybe it'll be really obvious to screen reader users!).

**Comment by andaleliz** [comment]
Thanks so much for the feedback and careful review! These are all really good call outs. I updated the recruiting criteria to be less restrictive, and I'll monitor closely to see if we need to relax it even more. I've also updated the conversation guide to change the whole address, and moved the reversal of changes immediately after the address update. 

Yes, it'll be really interesting to see what people say about the prototype! Not confident we'll have time in sessions for it, but you never know.

I'll go ahead and submit this to kick off recruiting!
