### ISSUE TITLE
Design | Profile | Research Plan | "One Per Page"

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47137]
## Issue Description
As part of the the Personal Information Revision project, we'll need to recruit Veterans to review the personal information mock-ups so we can validate that our user interface is intuitive and useful. 

See [platform research plan reference documents](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/README.md) for guidance

---
## Tasks
- [x] Write a research plan to recruit Veterans to review personal information mock-ups  [research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [x] Send the research plan to Samara and Marci for review 
- [x] Implement updates as needed

## Acceptance Criteria
- [x] The research plan is uploaded to our [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information/personal-information-revision/research) in GitHub,  and linked in this ticket
