### ISSUE TITLE
Create and edit description and other needed info for the About VA Form VA10091 page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47143]
## Issue Description
We need to add more information to the [About VA Form VA10091](https://www.va.gov/find-forms/about-form-10091/) landing page, writing a description for the "When to use this form" section that matches the style of other Find a Form landing pages. When doing this work, we should also determine if any other fields on the page should be added or updated (related forms and instructions, helpful links related to the form).

The previous content team has worked on other find a form pages you can look at for reference. This was done in ticket #22726. You can also look at live Find a Form pages. 

## Tasks
- [ ] Write description for form page
- [ ] Review (Laura)
- [ ] OCTO-DE review (Beth)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] The live VA Form VA10091 landing page now has a "when to use this form" section and any other pertinent information

**Comment by katherine-fung** [comment]
Hi @laurwill, some context about this form - I looked around va.gov and it seems that you should use this form if you're 
1. a vendor/provider getting paid by VA or 
2. you're a Veteran or caretaker getting travel pay from VA. 

It's a weird grouping, and it doesn't apply to direct deposit for Veterans for other types of payments they would get. 

Here's the draft language: 


**Related to:** VACO, travel pay, community care 
**Form last updated:** March 2022

H2: When to use this form 

Use VA Form VA10091 to set up direct deposit from VA, or to update your direct deposit information if one of these is true for you:  

- You're a vendor with VA, or  
- You're filing a claim for VA travel pay reimbursement

[Downloadable PDF section - no change]

Helpful links related to VA Form VA10091

**[VA travel pay reimbursement](https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/)**
Find out if you’re eligible for reimbursement and how to file a claim.

**[Payments for community care providers](https://www.va.gov/COMMUNITYCARE/revenue_ops/provider_payments.asp)*
Find out how to get payments for care you provide to a Veteran or a Veteran's family member.

**Comment by bethpottsVADEPO** [comment]
@laurwill I have a question out to Dave C. asking if we need to run this by any stakeholder. He's out today but back on Monday, so we should hear back then.

**Comment by laurwill** [comment]
Thanks @katherine-fung ! Good questions. We chatted with Beth yesterday and confirmed some answers here:
- It's okay to include use cases for non-Veteran audiences on form pages
- We wouldn't link to the legacy page here — we'd aim to keep people on the main site

Here's the text with a few suggested updates:

- Listed Veteran audience before vendor audience, added "caregiver", and specified "community care provider" instead of "vendor" — we can run this by stakeholder next week (see Beth's note above)
- Changed "related" to "Health care" since that seems to be the most relevant option
- Removed legacy page link and added the "how to set up direct deposit" page in addition to main travel pay page

Could you go ahead and update the form page in Drupal? Let me know if you have questions!

Related to: Health care
Form last updated: March 2022

H2: When to use this form

Use VA Form VA10091 to set up direct deposit with VA if one of these is true for you:
- You're a Veteran or caregiver filing a claim for VA travel pay reimbursement, **or**
- You're a community care provider filing a claim for reimbursement from VA

[Downloadable PDF section - no change]

H3: Helpful links related to VA Form VA10091

[VA travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)
Find out if you’re eligible for travel pay reimbursement and how to file a claim.

[How to set up direct deposit for VA travel pay reimbursement](https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/)
Find out how to set up direct deposit so we can deposit your travel pay reimbursement directly into your account.

**Comment by katherine-fung** [comment]
Hi @laurwill, this page is ready for you when we hear back about whether there's a stakeholder who should review this: 

http://preview-prod.vfs.va.gov/preview?nodeId=5771 

Thanks!

**Comment by laurwill** [comment]
Thanks Katherine! Just documenting here that Beth is in touch with Dave C about potentially adding an additional form link on this page — will update when we know more.

**Comment by bethpottsVADEPO** [comment]
@laurwill @katherine-fung I added to the issue description and tasks to include part of the ask not yet captured here: the link to the portal where users can sign up for direct deposit. I'm not sure yet if we're going to frame it as a portal for vendors or also direct Veterans there. Both can use it. But currently, there's no messaging addressing Veterans on the main page of the portal. So this will be a disjointed experience for them. I'm considering and will talk to Dave C. today about this and whether we perhaps ask the stakeholder to update their portal with some Veteran-facing language.

**Comment by bethpottsVADEPO** [comment]
@laurwill @katherine-fung I added to the issue description and tasks to include part of the ask not yet captured here: the link to the portal where users can sign up for direct deposit. I'm not sure yet if we're going to frame it as a portal for vendors or also direct Veterans there. Both can use it. But currently, there's no messaging addressing Veterans on the main page of the portal. So this will be a disjointed experience for them. I'm considering and will talk to Dave C. today about this and whether we perhaps ask the stakeholder to update their portal with some Veteran-facing language.

**Comment by bethpottsVADEPO** [comment]
Update for you @laurwill @katherine-fung for awareness: I'm meeting tomorrow with a couple OCTO people about this to make a call on whether or not to link to the portal from the form detail page.

**Comment by katherine-fung** [comment]
Update from Beth on 9/19/24: 

"This stalled out because there were some SMEs on the HC side who we needed to check with and I think that never happened. Thank you for flagging for me. I will figure out what's next. No need for you to dig into it right now."

**Comment by laurenvocke-va** [comment]
@DanielleThierryUSDSVA @RLHecht @bethpottsVADEPO to review this!
