### ISSUE TITLE
Create a Content Review Process for Platform Website

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47153]
_**Note:** This is NOT a project to update the content on the Platform website. This project is meant to identify content SMEs and establish a process for other Platform teams on how to review content, identify what needs to be updated, and work with the Platform Content team to deploy changes._

## High Level User Story/ies

As a Platform Content team,
We need to create a content review process that helps maintain the quality and accuracy of the website,
So that VFS teams continue to use the Platform website as the primary source of truth for documentation.

As a VFS team member,
I want to feel confident the Platform website content is up-to-date, relevant and accurate,
So that I can keep using the website as a source of truth.

As a Platform Content team,
We need to identify content SMEs across the website,
So that we can align on how to collaborate with them during a content review process.

As a Platform content SME,
I need to know when, how often to review content on the Platform website, and how to collaborate with the Platform Content team,
so that the content (especially technical content) is as relevant, accurate and up-to-date as possible for VFS team members.

## Hypothesis or Bet

**If** we establish a set of content review guidelines and process for other Platform teams,
**then** the content of the Platform website will be more up-to-date, relevant and accurate for VFS team members to use.

**If** we establish a set of content review guidelines and process for other Platform teams,
**then** VFS teams will trust the Platform website content more as the primary source of truth.

## Definition of done

- [x] We will have a way to find a Platform knowledge subject matter expert (SME) for all sections of the Platform website.
- [x] Recommended review and editorial guidelines are defined for Platform teams.
- life cycle/review frequency (how often content owner should review pages)
- review checklist (review content accuracy, missing content, launch blocking issues, style guide best practices, etc.)
- collaboration & feedback mechanism (confluence comments)
- process to establish content SME for new pages (our team reviews during deployment reviews)
- [x] A process is established for how content SMES will collaborate with our team (the Platform content team) to review and/or update content.

## OKRs

- Fewer support tickets will be submitted from VFS team members with questions about missing or inaccurate technical content on the Platform website. 

- Content on the Platform website will be updated more regularly by other Platform teams and reflected here: https://vfs.atlassian.net/wiki/spaces/AP/pages/2372141343/Platform+website+data+and+analytics

## Risks

- The Platform is unable to identify content subject matter experts for specific areas of the Platform website.
- The Platform is unable to assign content owners/reviewers for technical content on the Platform website.
- Platform teams that own parts of the Platform website content struggle and/or are unable to commit to following a content review process due to other priorities.

## Artifacts

- [Product Outline](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2739044584/Product+outline+-+Platform+website+content+review+process) (Confluence)
- [Content review process ideas and team notes](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2739044584/Product+outline+-+Platform+website+content+review+process) (Confluence)
- [Content review process visual workflow](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1692649886268/57be867d361253b13264164785c2b77f64f20fe6?sender=u9d01ee38af217e4877e75660) (Mural)
- [Where to source data about content last-edited information](https://vfs.atlassian.net/wiki/spaces/AP/pages/2372141343/Platform+website+data+and+analytics) (Confluence)
- [Example of how to organize prioritized content before presenting to other Platform SMEs](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing) (Google Sheets)

## Running ideas/thoughts

- Do some pages need maintenance more than others?
- Do we set expiration dates?
- Do expiration dates come from Confluence?
- Cards in platform teams' backlog? Something that the Platform Content team maintains?
- How to best work with us to review their content? For example, staggering the content types to prevent Platform Content from reviewing all teams' content at once.
- Leverage this Platform website editing data: https://vfs.atlassian.net/wiki/spaces/AP/pages/2319712309/Platform+website+edits+volume+Research+and+design 
- Assigning ownership of pages in Confluence: https://support.atlassian.com/confluence-cloud/docs/transfer-ownership-of-your-page-to-another-person/
- How to navigate to from a Platform website page to its corresponding version in Confluence: https://help-cloud.k15t.com/scroll-viewport/navigate-from-article-in-site-directly-to-confluen
- Leverage Platforms support editing data
- Leverage recent [Platform website insights](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2) and [Mural solutioning](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1687271252027?sender=u9d01ee38af217e4877e75660&key=794e4ef1-0f9b-4fa9-a5ae-a145aeacd98a) ideas
- Leverage [office hours feedback](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2684289025/6+27+23+Office+Hours+feedback+about+Platform+website+research) from leadership
-  Confluence page review reminder plugin: https://marketplace.atlassian.com/apps/1221018/page-reminders-for-confluence?tab=overview&hosting=datacenter

**Comment by vbellissimo** [comment]
Definition of done has been met. Officially closing this epic.
