### ISSUE TITLE
[Development] HLR URL Changes Based on IA Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#4718]
## Purpose

As a veteran, I need to be able to find things so the breadcrumbs and URLs need to be correct.

## What we need to do
Based on the comment from the IA review (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3822#issuecomment-561305881), we need to make URL updates.  The following is the updates that are copied from the IA review.

### Structure, Breadcrumbs & URLs
- Pages shown in site map here: https://app.moqups.com/Rnc4BDEKrA/view/page/a4dc7a719
- The new form will live under the Decision Reviews “branch”.

**PAGE:** “Request a Higher-Level Review” content page
- Existing page
- No change to URL:  https://www.va.gov/decision-reviews/higher-level-review/
- Modify breadcrumb: remove “Request a” from breadcrumb
	- Current: Home > VA decision reviews and appeals > Request a Higher-Level Review 
	- Revised: Home > VA decision reviews and appeals > Higher-Level Reviews 
- Recommend modification to page title:  remove “Request a” from page title so it is not confused with the actual request form which currently shows the same title. 

**PAGE:** “Request a Higher-Level Review” online form
- New online form
- Base URL: https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Breadcrumb: Home > VA decision reviews and appeals > Higher-Level Reviews > Request a Higher-Level Review
- Subsequent pages will add on to the above URL using short and simple labels, i.e. /introduction/, /veteran-details/, etc.

**PAGE:** “After you request a decision review” content page
- Existing page
- No change to URL: https://www.va.gov/decision-reviews/after-you-request-review/
- No change to breadcrumb: Home > VA decision reviews and appeals > After you request a decision review

### Navigation and Entry Points: 
**Top Nav, Header and Footer**
-	No additional options to be added to the top nav, header or footer
-	Consider changing the “File an Appeal” link and label within the top nav (under Disability fly-out) to prioritize the Decision Review process over the legacy appeals process
o	Change the link label to incorporate the “Decision Review” language – i.e. “Appeal or Request a Decision Review” or “Request a Decision Review or Appeal” (discuss with writer to finalize)
o	Change the links to go to the main Decision Review page instead of the legacy appeals page in disability: https://www.va.gov/decision-reviews/
**Add Left Nav**
-	Add a left nav component to the Decision Reviews content area as either part of this work, or as follow up work, to improve navigation within this section of content.  
-	Include a link to this new online form as a child of the Higher-Level Review content page
-	Left nav was defined for this area previously but should be reviewed and revised as needed based on the addition of this option : https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16360
-	
**Disability Hub**
-	Change the existing “File an Appeal” option to include the Decision Review language – i.e. “File an Appeal or Request a Decision Review” (discuss with writer to finalize)
-	Change the link to go to the main Decision Review page instead of the legacy appeals page in disability: https://www.va.gov/decision-reviews/

**Other Entry Points:**
-	From within Disability content
o	Entry point from “File a VA disability appeal” page already exists and should remain as is: https://www.va.gov/disability/file-an-appeal/
-	From main Decision Reviews page
o	The main Decision Reviews landing page contains a link to the HLR content page and a PDF download - replace the pdf link with a link to the online form, or add a link to the online form within the content so both options are available. 

**Crosslinking**
- None at this time  

### Redirects
- Not aware of any redirects needed at this time.  If any redirects are needed, please submit a Redirect Request at least 2 weeks in advance per the [Redirect Request Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md).   

## Tasks
- [ ] Structure, Breadcrumbs & URL changes are made
- [ ] Navigation and Entry Point changes are made
- [ ] Check to make sure no redirects are needed
- [ ] Testing - Luke Note: Can we add details as to what kind of testing we need to do?

## Acceptance Criteria
- [ ] URLs are updated
- [ ] Tested

**Comment by Mottie** [comment]
Reopened per Mikki, "the [current] root `/disability-benefits/` is invalid and the HLR doesn't belong in disability anyway"
