### ISSUE TITLE
Rework Supplemental Claims static page to match VA.gov style

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47188]
## Issue Description

We are reworking the decision reviews section to make sure the static pages match the voice and style of VA.gov. These pages were originally put on the site without much collaboration from the Sitewide Content and IA team. We need to make sure it meets our plain language standards and follows the same patterns as our other benefit detail pages.

This ticket is for the [Supplemental Claims](https://www.va.gov/decision-reviews/supplemental-claim/) page. 

## Tasks
- [x] Rework page (Katherine)
- [ ] Review (Laura)
- [ ] Post in ticket #47190 for Beth to review (Laura) 

## Acceptance Criteria
- [x] Page is ready for OCTO-DE review

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I'm posting the working draft of the Supplemental Claims page here: 

http://preview-prod.vfs.va.gov/preview?nodeId=3011 

Since we last met with Danielle to talk about this page, I've moved around some of the content to get the "How do I file a Supplemental Claim?" section higher. 

- The "You'll need this information to file your claim" section is now further down on the page, under "How to file" 

- The live page currently directs people filing Supplemental Claims for pension/survivors benefits to send their forms to different PO boxes based on their state. Based on previous edits we did on another page related to these addresses, we think there is just one address now. But we will need to confirm this with the stakeholder. 

- There is a "What's new and relevant evidence?" section that explains the evidence requirement. A jump link near the top of the page goes to this section. The decision reviews FAQ page also needs to link to the "What's new and relevant evidence" section. 

Let me know if you want to talk through the page or any other potential edits more. Thanks!

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I'm posting the working draft of the Supplemental Claims page here: 

http://preview-prod.vfs.va.gov/preview?nodeId=3011 

Since we last met with Danielle to talk about this page, I've moved around some of the content to get the "How do I file a Supplemental Claim?" section higher. 

- The "You'll need this information to file your claim" section is now further down on the page, under "How to file" 

- The live page currently directs people filing Supplemental Claims for pension/survivors benefits to send their forms to different PO boxes based on their state. Based on previous edits we did on another page related to these addresses, we think there is just one address now. But we will need to confirm this with the stakeholder. 

- There is a "What's new and relevant evidence?" section that explains the evidence requirement. A jump link near the top of the page goes to this section. The decision reviews FAQ page also needs to link to the "What's new and relevant evidence" section. 

Let me know if you want to talk through the page or any other potential edits more. Thanks!

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I've updated the Supplemental Claims draft as we've discussed: http://preview-prod.vfs.va.gov/preview?nodeId=3011

For the instructions under "By mail" and "In person," I've delineated the steps using "Step 1," "Step 2," and "Step 3." I thought this would clarify the instructions, while working well with screenreaders -- let me know if you have other thoughts about how we might approach this. 

Thanks!

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I dug up these Veteran comments that Autumn (who you'll meet on Monday) sent to me back when we first talked about how we could improve the DR pages. Attaching here, and you may want to also attach it to the tickets you'll work on for HLR and Board Appeals for background info.
[https://app.zenhub.com/files/133843125/bd1a70b0-4304-4124-85f7-ef15631522d9/download](https://app.zenhub.com/files/133843125/bd1a70b0-4304-4124-85f7-ef15631522d9/download)

**Comment by katherine-fung** [comment]
Hi  @bethpottsVADEPO -- 

I was thinking of the SME's feedback about the Supplemental Claims page.

In the "Is a Supplemental Claim the right decision review option for me?" alert, what do you think of saying:

"A Supplemental Claim might be the right choice if you meet both of these requirements." [currently says: "is the right choice"]
...
Note: You can also request a Board Appeal if you have new evidence. A Veterans Law Judge at the Board of Veterans’ Appeals will review your case, but it will take longer to get a decision. [currently says: "Note: You can also request a Board Appeal if you have new evidence, but it will take longer to get a decision."]

**Comment by bethpottsVADEPO** [comment]
@katherine-fung 
1/ That's a great suggestion! Let's use "may" though since that aligns with our voice and the meaning is a bit more positive/definitive than "might." From what I've read on the distinction between the two, the word "may" implies that this is likely the right choice whereas "might" implies that it's unlikely the right choice. Sort of like, this might or might not be the right choice, which isn't very helpful-sounding to me. It's definitely an incredibly nuanced distinction! But I'd use "may."

2/ Yes, that's exactly what the SME was asking for. Thank you!
--------------
Sometime this week, would you update this ticket with notes from the meeting with stakeholders? Doesn't have to be detailed since you already updated the drupal file. Just note here the main points from the meeting and outstanding questions or things we'll circle back to, like: 

- Updates to the average time to complete a Supplemental Claim box (and other specific edits/updates we discussed)
- Next steps and who is responsible for each one: following up to get additional info from Shireen that she promised, meeting with disability comp, then sending the preview link to both business lines for a final thumbs up

Thanks!

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! I've updated the alert, and I'll update this ticket with notes after today's backlog grooming.

**Comment by katherine-fung** [comment]
Notes from last Monday's meeting: 

- Shireen does want us to mention the Board Appeal alternative in the "Is a Supplemental Claim the right decision review option for me?" note. She asked that we mention the benefit of that option (that a judge will review the case).

- Shireen provided the average time it took it to complete a SC as of 10/2/22. She says the team can provide this information every month. 

Next steps: 
- Shireen will check with the pension business line about the mailing address for pension/survivors' benefit claims. 

- We'll set up a meeting with disability comp folks to review this page with them. 

- We'll send the draft page to Shireen's team and the disability comp SME and review any changes they propose.

**Comment by katherine-fung** [comment]
Notes from last Monday's meeting: 

- Shireen does want us to mention the Board Appeal alternative in the "Is a Supplemental Claim the right decision review option for me?" note. She asked that we mention the benefit of that option (that a judge will review the case).

- Shireen provided the average time it took it to complete a SC as of 10/2/22. She says the team can provide this information every month. 

Next steps: 
- Shireen will check with the pension business line about the mailing address for pension/survivors' benefit claims. 

- We'll set up a meeting with disability comp folks to review this page with them. 

- We'll send the draft page to Shireen's team and the disability comp SME and review any changes they propose.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Do you think you could put together a few screen shots to show what we're proposing to change on the page? Probably easiest to do this in a Word doc. I thought I'd introduce you to Paul Shute in disability comp so you can send the screen shots directly to him and he can see what you're doing. He can decide if he wants to meet or if that's enough for him to give us a thumbs up or feedback. 

You could just draw a box around a section (the blue box or an H2) and point to new text with arrows, with a little description of what changed ("minor plain language changes. However you want to go about it is fine--just throwing out some ideas! Would be good to make it clear where there is new/changed content; call out instances where we moved content to a new location on the page ("How long does a Supplemental Claim take?"); and explain why we changed wording where it's more than just PL tweaks (the most significant probably being "Is a Supplemental Claim the right decision review option...?" since we are trying to help with confusion about which form to fill out). 

One change I wanted to suggest in the blue box: Adding those links back in for fiduciary claims and contested claims. Would you try adding those after the 2 bullets, wording like this?:
Learn about your options for a fiduciary claim
Learn about your options for a contested claim

(disclaimer... unless I'm forgetting something and Shireen didn't want those links there??)

Thanks!

**Comment by katherine-fung** [comment]
Update 11/1: I emailed Paul with a draft of the changes, and he says the changes will be helpful to Veterans. He doesn't have any other edits. He also looped in Alejandro Mendiolaflores on his team. 

Alejandro will run the draft by the team developing supplemental claims applications, to make sure the draft and the online tool align with each other.

**Comment by RLHecht** [comment]
Moving to blocked while we wait to hear back from stakeholders

**Comment by katherine-fung** [comment]
I've sent this page back to the product team and am awaiting further feedback from them/user testing. 

---

Noting that we've had several conversations with the product team between December and January, and updated the page to reflect changes to Supplemental Claims for the PACT Act. 

The updates include: 
- no longer saying we require new and relevant evidence
- removing the section "What's new and relevant evidence?"
- more details about qualifying with a presumptive condition

After an update from the product team last week, we are saying "new and relevant" evidence on the page, and defining it in running copy. 

cc @RLHecht

**Comment by RLHecht** [comment]
Closing out this ticket. We can open a new one if we need to make more changes after usability testing.

**Comment by katherine-fung** [comment]
Documenting here that we made a number of changes per user and stakeholder feedback in February and March: 

- we added a link for "Learn about contested claims" to the contested claim bullet point (3/31/23)
- we added information about how to file for increased compensation 
- we added the section "What we mean by 'new and relevant' evidence"
- for the version of the widget with the online tool, we changed the header "For disability compensation" to "File online for a disability compensation claim" 
- we removed "Option 1... 2... 3" from the non-online options

**Comment by katherine-fung** [comment]
Documenting here that we made a number of changes per user and stakeholder feedback in February and March: 

- we added a link for "Learn about contested claims" to the contested claim bullet point (3/31/23)
- we added information about how to file for increased compensation 
- we added the section "What we mean by 'new and relevant' evidence"
- for the version of the widget with the online tool, we changed the header "For disability compensation" to "File online for a disability compensation claim" 
- we removed "Option 1... 2... 3" from the non-online options
