### ISSUE TITLE
[DESIGN] Household design iteration

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#47197]
## Description

As a continuation of #44888, the household info section is nearing completion. I demo'd the updates to the team, and requested specific feedback from the design team about the design.

- [Household section mockups](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)

<details><summary>Original dependents list design</summary>

![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/98a1e4a0-178c-4afa-8e71-5d7e184956dc)

</details>
<br>

**Dependents flow feedback**
Iterate on the dependents design, incorporating design review feedback as appropriate. Feedback to consider:
- Callout card/box may be too high; consider more horizontal layout
- Consider not using headings (ie. "Relationship")
- Consider a two-step "edit" flow: click "edit", then make additional choices
- Consider using buttons rather than links
- Removal flow needs two-step confirmation
- Consider check-in team's modal design
- Cancel confirmation for adding/editing a dependent

## Tasks

- [x] More compact box/card design
- [x] Buttons instead of links
- [x] Two-step confirmation flow for editing and removal
- [x] Modal design for removal confirmation
- [x] Cancel confirmation for adding/editing dependent
- [x] Determine if spousal/dependent info gets used if no financial info is given
- [x] Reorder questions based on above ^
- [x] Additional onboarding copy for start of household section
- [x] Updated spousal and dependent sub-headings

## Acceptance Criteria

- [x] An updated dependents list design, ready for collab cycle review
- [x] Updated household flow, based on spouse/dependents financial information
- [x] Determine correct question order based on info needed

**Comment by nicko-amida** [comment]
Here's the [updated household information flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas), with pre-collab cycle feedback incorporated.
