### ISSUE TITLE
Audit for pages missing login.gov mention and add where needed

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47192]
## Issue Description
We recently discovered there are still benefit detail and R&S pages that don't list login.gov as an option for sign-in (with MyHealtheVet, DS Logon, and ID.me). We need to do an audit of our pages and add it as an option wherever it's missing.

Pages to update: 
- [x] https://www.va.gov/claim-or-appeal-status/
- [x] https://www.va.gov/resources/claim-status-tool-faqs/
- [x] https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/
- [x] https://www.va.gov/resources/ask-va-replaces-iris-and-the-gi-bill-help-portal/

**Note:** It's also missing from [this page](https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/), but we may retire this so we shouldn't spend time adding and providing new screenshots.  

## Tasks
- [ ] Do audit (Public Websites)
- [x] Add login.gov to pages where needed
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] All VA.gov pages list login.gov as an option for sign-in.

**Comment by RLHecht** [comment]
Update: After meeting with the CMS team, we learned there isn't a current functionality in the audit tool to search for words on Drupal pages other than in the intro. We will need to do a manual audit using search and clicking around on the site.

**Comment by RLHecht** [comment]
Update: In grooming we discussed asking Public Websites to do a search so we can ensure we are finding all instances.

**Comment by laurwill** [comment]
Update on content guidance here: 
- Login.gov also needs "verified" account 
- We'll put the accounts in the order from the sign-in block consistently
- We'll edit the line on some pages that says you can create an ID.me account "on VA.gov"

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I've added login.gov to these pages: 

Check your VA claim or appeal status 
http://preview-prod.vfs.va.gov/preview?nodeId=711 

Post-9/11 GI Bill Statement of Benefits 
http://preview-prod.vfs.va.gov/preview?nodeId=3007 

The following pages are multiple FAQ R&S pages, so I updated the single FAQs to add login.gov: 

[Claim status tool FAQs](https://www.va.gov/resources/claim-status-tool-faqs/)
preview-prod.vfs.va.gov/preview?nodeId=8504
preview-prod.vfs.va.gov/preview?nodeId=8521
preview-prod.vfs.va.gov/preview?nodeId=8514
preview-prod.vfs.va.gov/preview?nodeId=9276 

[Ask VA replaces IRIS and the GI Bill Help Portal](https://www.va.gov/resources/ask-va-replaces-iris-and-the-gi-bill-help-portal/)
preview-prod.vfs.va.gov/preview?nodeId=34312
preview-prod.vfs.va.gov/preview?nodeId=35507
preview-prod.vfs.va.gov/preview?nodeId=34513

**Comment by laurwill** [comment]
Thanks Katherine! These look great — I just made a couple tweaks for consistency on the last 2 pages:
- Bolded account types 
- Made order consistent in paragraphs as well as lists
- Added full returns before link text and shortened one long link

@megzehn , these are ready to copyedit and publish!

**Comment by laurwill** [comment]
Also noting here that we may want to make more significant changes to this [Privacy and security page](https://www.va.gov/resources/privacy-and-security-on-vagov/) to incorporate Login.gov — we'll check in with Danielle about this next week.

**Comment by megzehn** [comment]
Thank you! The changes look good. I will check these off as they get published. 

Check your VA claim or appeal status
- [ ] http://preview-prod.vfs.va.gov/preview?nodeId=711

Post-9/11 GI Bill Statement of Benefits
- [ ] http://preview-prod.vfs.va.gov/preview?nodeId=3007

The following pages are multiple FAQ R&S pages, so I updated the single FAQs to add login.gov:

Claim status tool FAQs
- [ ] preview-prod.vfs.va.gov/preview?nodeId=8504
- [ ] preview-prod.vfs.va.gov/preview?nodeId=8521
- [ ] preview-prod.vfs.va.gov/preview?nodeId=8514
- [ ] preview-prod.vfs.va.gov/preview?nodeId=9276

Ask VA replaces IRIS and the GI Bill Help Portal
- [ ] preview-prod.vfs.va.gov/preview?nodeId=34312
- [ ] preview-prod.vfs.va.gov/preview?nodeId=35507
- [ ] preview-prod.vfs.va.gov/preview?nodeId=34513

**Comment by megzehn** [comment]
Confirming these are all published, @RLHecht!

**Comment by RLHecht** [comment]
Closing this out. Will open a new ticket if/when we find more instances of pages to add Login.gov to.
