### ISSUE TITLE
Refactor signup & verify authentication utilities

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#47202]
## Description
Current there are a couple different options to generate the following URL `[api-env]/v1/sessions/<csp>_signup_<verified>/new` for the Sessions Controller using authentication components.  They are `signup` and `verify` (along with their respective link generating functions.

Because these 2 functions do similar work the thought is to refactor and reduce it down to a single function `signupOrVerify` so that the code is DRY.

## Tasks
- [x] Refactor `authentication/utilities.js` for the following
  - [x] Combine `signup` and `verify` into a single method => `signupOrVerify`
  - [x] Can generate links or do redirects
  - [x] Can generate URLs for SAML or OAuth
  - [x] Properly tested with unit tests

## Acceptance Criteria
Using the `signupOrVerify` method I can:
- [x] Generate a SAML URL for
  - [x] Login.gov (LOA1) `v1/sessions/logingov_signup/new`
  - [x] Login.gov (LOA3) `v1/sessions/logingov_signup_verified/new`
  - [x] ID.me (LOA1) `v1/sessions/idme_signup/new`
  - [x] ID.me (LOA3) `v1/sessions/idme_signup_verified/new`
- [x] Generate an OAuth URL for
  - [x] Login.gov (LOA1) `v0/sign_in/?oauth=true&acr=min&type=logingov`
  - [x] Login.gov (LOA3) `v0/sign_in/?oauth=true&acr=ial2&type=logingov`
  - [x] ID.me (LOA1) `v0/sign_in/?oauth=true&acr=min&type=idme`
  - [x] ID.me (LOA3) `v0/sign_in/?oauth=true&acr=loa3&type=idme`
