### ISSUE TITLE
[FE] [TECH DEBT] - Add utils for unit test boiler plate

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#47230]
## Description
There are a lot of things that we could clean up in our unit tests. Below is a list of things that we should try to move to a util or helper:
- init state (There is already part of this setup for the scheduledMaintenceWindow)
- Mock router
- I18n Provider and store Provider

## Tasks
- [ ] [FE] evaluate areas in unit tests to turn into helpers or utils
- [ ] [FE] create utils
- [ ] [FE] replace repeated setup and code with util
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
duplicates #47229
