### ISSUE TITLE
[FE] Payment Info V2: Post-launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47243]
## Background
Once the Outstanding debts and Benefit payments sections have been successfully launched to 100% of users we want to go back and review the code to determine if there is any tech debt that needs to be addressed.

Additionally, there were some conflicting conditionals found via #58543 - so we need to remove those. Notes [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58543#issuecomment-1555232177).

## Tasks
- [x] Remove feature flipper flag from staging and production (`show_payment_and_debt_section`), both the FE code and the API
- [x] Remove conditionals causing some user to see the old payment info (combined) section (details [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58543#issuecomment-1555232177))
- [x] Review to determine what additional code may need to be cleaned up
- [x] Implement adjustments to code based on what was found in the review
- [x] Update cypress tests if needed

## Acceptance Criteria
- [ ] Toggle is removed in FE code and API
- [ ] Conditionals are removed (all users are seeing _only_ v2 of payment info - ie two separate debt and benefit sections)
- [ ] Tests are updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ FE dev, PM
- _How can this work be validated?_ 
      1. Verify toggle is removed from FE code
      2. Verify toggle is removed from API
      3. PM to verify in analytics that we're only seeing engagement on `Navigation - Link List - Benefit payments - Review your payment history` (See [57991](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57991) for full details)

**Comment by adamwhitlock1** [comment]
Looks like we still need to remove the toggle from the vets-api, as I am still seeing it present in the code.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml#L784

**Comment by ajakabcin** [comment]
@allisonlu I'm going to roll this to sprint 12 to wrap up the last bit Adam referenced above

**Comment by ajakabcin** [comment]
moved back to in progress to address API code

**Comment by allisonlu** [comment]
> Looks like we still need to remove the toggle from the vets-api, as I am still seeing it present in the code @allisonlu, did you have plans to spool up a PR to remove from the api?
> 
> https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml#L784

🤦‍♀️ thanks for catching that @adamwhitlock1. I got this confused with our conversation about the other existing feature toggle a few weeks back and kept thinking "I'll get back to this". Just opened a PR!

**Comment by allisonlu** [comment]
Woo! confirmed that it's gone on staging: https://staging-api.va.gov/flipper/features

**Comment by ajakabcin** [comment]
Yaaaaasssss! I'll take a look at production domo
