### ISSUE TITLE
[Application Hosting and Deployment] Document how projects are used to manage permissions

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47248]
## Description
Platform operators and developers deploying applications to EKS need to understand how application projects (AppProjects) are used to provide permissions to users and groups. 

## Background/context 
- See parent epic 
- Application projects "AppProjects" are configured using Helm templates and ArgoCD
- Automation connects AppProjects with GitHub teams to define read-only and read-write permissions (RO/RW)
- Existing doc: [Manage ArgoCD AppProjects for applications in EKS [WIP]](https://vfs.atlassian.net/wiki/spaces/OT/pages/2293563476/Manage+ArgoCD+AppProjects+for+applications+in+EKS+WIP)

---
## Tasks
- [x] Create documentation that outlines how AppProjects are used with ArgoCD and GitHub teams 

## Acceptance Criteria 
- [x] Documentation exists in Confluence that contains the following: 
  - [x] 1-2 sentence overview of what the document contains
  - [x] How AppProjects are managed and what they do (brief) 
  - [x] Explanation of the key elements of AppProject configurations and permissions 
   - [x] Project, application name, environment 
    - [x] Permissions, ie 
    - [x] GitHub teams users and groups 
  - [x] Links to resources (such as forms, code, repos, and workflows) as needed

**Comment by jhouse-solvd** [comment]
@jbritt1 started this document previously and I did a little re-write today: 

https://vfs.atlassian.net/wiki/spaces/OT/pages/2293563476/Manage+ArgoCD+AppProjects+for+applications+in+EKS+WIP

This is ready for review.

**Comment by jbritt1** [comment]
Removed the WIP label and the portion about TBD automation to create GitHub teams as that is complete and has been verified as working numerous times.

**Comment by jbritt1** [comment]
Added note about the doc being mostly educational, since our automation does all of the leg work discussed therein and links to both the onboarding and promotion form templates.

**Comment by jhouse-solvd** [comment]
Doc [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2293563476/Manage+ArgoCD+AppProjects+for+applications+in+EKS+WIP)

Closing
