### ISSUE TITLE
Login Self-Service Tool Mobile Prototype

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#47252]
## Issue Description
_We need a mobile version of the self-service login troubleshooting tool for testing._

---
## Tasks
- [x] _Create self-service login troubleshooting tool _mobile_ prototype_

## Acceptance Criteria
- [x] _Mobile prototype of the self-service login troubleshooting tool_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Mobile prototype](https://sketch.com/s/cbb5c762-39e4-47bb-af88-22e693a4cb51/a/PGa4KJW/play)
