### ISSUE TITLE
Research Readout - Support User Journey Map

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#47254]
## Issue Description
_With our phase 1 research sessions completed, we need to draft the research readout._

---
## Tasks
- [ ] _Draft the research readout for the support user journey map research (phase 1)_

## Acceptance Criteria
- [ ] _Support user journey map research readout is drafted_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
@jwoodman5  Should we consolidate this with the one I made last Thursday? 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/46366

**Comment by jwoodman5** [comment]
@manalo-soco I must some (administrative) updates to that one and will delete this. Closing.
