### ISSUE TITLE
Create new Fry rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47260]
## Issue Description

As we've been creating our modernized education rates pages, we put the Fry Scholarship information on the Post-9/11 Chapter 33 rates page because the numbers are the same. We now want to separate the 2 audiences so we need to create a separate Fry Scholarship rates page. 

When creating the new page it should be very similar to the Post-9/11 page but will need to adjust wording like "You served on active duty..." to "The Veteran or member of the Selected Reserve served on active duty..." We also need to take out the mention of Fry in the intro of the Post-9/11 page. Before beginning on the work, check in with Beth, who has other suggestions on how to write up the page. 

Draft of Post-9/11 page to work form: http://preview-prod.vfs.va.gov/preview?nodeId=10019

## Tasks
- [x] Create new Fry Scholarship rates page (Aliyah)
- [x] OCTO-DE review (Beth)
- [ ] Copyedit (Megan)

## Acceptance Criteria
- [x] New Fry Scholarship rates page created and ready for stakeholder approval

**Comment by aliyahblackmore** [comment]
Hi @laurwill - the Fry Scholarship rates page is ready for you!
Preview link:

I had a chat with Beth yesterday (9/20) and wanted to just add in some of the notes for your awareness/context: 

- Beth had a few questions about certain benefits and whether they apply for the Fry Scholarship – if they do not, those sections would be pulled/removed from the page. We are leaving the content as is for the time being (aside from changing language around Fry Scholarship etc.). Beth is still waiting (as of morning of 9/21 ) for the SME to reply. Some of the questions are: Do recipients qualify for all benefits? Do recipients get 100% or nothing.
- Beth mentioned that the language, whether the benefit is not for Veterans but their family, can some times get a bit crowded. She mentioned looking at that and making suggested changes where applicable. 

I included some more of my research and notes in this Word doc for reference. I didn't want the ticket text to get too crowded. 

[Fry Scholarship rates page notes_9.20_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9619011/Fry.Scholarship.rates.page.notes_9.20_AB.docx)


### 
Some other quick notes/flags: 

- In H2 “Eligibility for 100% Post-9/11 GI Bill Benefits” - with the text regarding the Veteran or member of the Selected Reserve replacing “service member” in the bullet, this gets a bit crowded.  Beth mentioned on our call (9/20) that this could happen and suggested seeing if there could be a work around. I went ahead and made a change here so that each bullet point doesn’t begin with “the Veteran or member of the Selected Reserve” and I added “They” to the start of each bullet point. Open to thoughts here!
- There were a few instances of “you” on the page that I went ahead and replaced, as the “you” may have been pertaining to the Veteran or Selected Reserve member. For example, in the H2 that was originally “**Eligibility for a percentage of benefits if you served less than 36 months**.” When I replaced “you” with “the Veteran or member of the Selected Reserve” that felt a bit too crowded. I replaced the “you” with “they” for the time being, but wonder if “they” is too distant or vague here. Open to thoughts on this – mostly I wanted to move away from a crowded header!
- In the accordion **“Money to help you move from a highly rural area”** there is a mention of this being a Post-9/11 GI Bill grant. Wondering if this can be referred to as a Fry Scholarship grant on this page. I’ve left this as is for the time being.  **A question for the stakeholder:** Can this money to help a spouse/child move from a highly rural area be called a Fry Scholarship grant, or would it only be called a Post-9/11 GI Bill grant?
- Question for stakeholder: for the covered tests, they are only covered if approved by the GI Bill – again, wondering if this is an instance of leaving in GI Bill or is there another approval process for Fry Scholarship recipients?  It seems that the [Fry Scholarship is an expansion ](https://www.va.gov/SURVIVORS/FAQs.asp#FAQ1) of the GI Bill to children and spouses, so it seems that this approval process may be the same.  I’ve left the text as is for the time being. 
- Question for stakeholder: because the Fry Scholarship is an [expansion of the Post-9/11 GI Bill](https://www.va.gov/SURVIVORS/FAQs.asp#FAQ1), want to flag and confirm, can the GI comparison Tool also be used for Fry Scholarship recipients?

**Comment by aliyahblackmore** [comment]
Hi @laurwill ! I made some updates to this page based on some responses from the stakeholder (via Beth).
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=49549

**For reference, the stakeholder confirmed these things:** 

- Fry scholars always get 100% of the benefit. So you can remove those 2 sections about (first H2) getting 100%of the benefits and (second H2) getting a percentage of the full benefit. * **Noting** here that the H2 was "How much of the full benefit can you get" and the H3s were regarding getting 100% of the benefits and getting a percentage of the full benefit. I removed these headers and content.
- Keep the accordions for 1/ money for on-the-job training and apprenticeships and 2/ relocation costs if they live in a highly rural area 

**A few questions here (that I've edited):**  

- In the accordion **“Money to help you move from a highly rural area”** there is a mention of this being a Post-9/11 GI Bill grant. The text is “You may be eligible for this Post-9/11 GI Bill rural grant…” I went ahead and changed **“this”** to **“the”** as this is not the Post-9/11 GI Bill page. I have two questions here. **First,** because we are saying that someone “may” be eligible for this grant, is there any information available that we could link to in this accordion that provides more details about how someone would go about applying for this grant OR is this a grant that a scholar would automatically be considered for/would receive?  **Second**, because this is the Fry Scholarship page, want to confirm that this would still be referred to as the Post-9/11 GI Bill rural grant or would this be called a Fry Scholarship rural grant?  Because this scholarship is an [expansion](https://www.va.gov/SURVIVORS/FAQs.asp#FAQ1) of the Post-9/11 GI Bill, I believe that this grant name would remain the same, but wanted to be sure!
- For the “Added payments” accordion, want to confirm, are Fry Scholars eligible for these payments?
- For the covered tests, they are only covered if approved by the GI Bill – again, want to confirm that the GI Bill would be the approval process that a Fry Scholar would also be going through or there another approval process for Fry Scholars? The Fry Scholarship is an “[expansion](https://www.va.gov/SURVIVORS/FAQs.asp#FAQ1)” of the GI Bill so it seems that this approval process may be the same . I’ve left the text as is for the time being!
- Last, because we removed the sections that included text that was, “Veterans and member of the Selected Reserve”(the suggested text in this ticket), wondering if there needs to be any mention at all, on this page, of **who** Fry Scholars should be and a cross link to the [Fry Scholarships page](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/), which has more information about the benefit? If there doesn’t need to be a mention of who the scholarship is for, I would suggest that we cross link to the Fry Scholarships page so that there is a reference for more information – this could be in the “How to contact us…” section.

**Comment by laurwill** [comment]
Hi @bethpottsVADEPO , as we chatted, reassigning this to you for review.

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore Thank you for being so thorough with this! I made some edits and passed questions to the SME.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO @aliyahblackmore, 

I'm putting the link for past 2022 Fry Scholarship rates here: https://prod.cms.va.gov/past-rates-2022-fry-scholarship-rates 

If we need to update the past rates page once we hear back from the stakeholder on our questions, I can make those changes. Thanks!

**Comment by RLHecht** [comment]
Closing out. Copyediting will be done before publishing all the rates pages.
