### ISSUE TITLE
Create VFS Facing Documentation for E2E Reliability Improvements

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47262]
## Issue Description
VFS teams need information for how to engage with elements of the reliability improvements made for this initiative that affect them.

## Tasks
- [x] Need to create VFS-facing documentation for how to use the E2E Stress Test
- [x] Verify that support and playbook documentation has the most up-to-date guidance given current functionality

## Acceptance Criteria
- [x] A new document describing how to interact with the E2E stress test from a VFS team perspective is available on the Platform Website

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/2273771547/How+to+troubleshoot+a+Cypress+failure Troubleshooting playbook updated here.

https://vfs.atlassian.net/wiki/spaces/pilot/pages/2379120641/E2E+Stress+Test+and+Allow+List Stress test docs

https://vfs.atlassian.net/wiki/spaces/pilot/pages/2372895484/Currently+Disallowed+Cypress+Test+Specs+on+VA.gov Disallow list

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TTT/pages/2241036753/Procedure+for+E2E+Test+Failure+Support+Requests Internal support request playbook also updated.

**Comment by pjhill** [comment]
Awesome -- thanks for getting these documents updated and in place ahead of the launch!
