### ISSUE TITLE
Fix Confluence API key for SOCKS roster check

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#47277]
## Description
To be able to check the Platform roster in Confluence during a github action, @kylesoskin created an API key and put it in parameter store at [/dsva-vagov/pst-amt/confluencebasicauth](https://console.amazonaws-us-gov.com/systems-manager/parameters/dsva-vagov/pst-amt/confluencebasicauth/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:%2Fdsva-vagov%2Fpst-amt%2Fconfluencebasicauth). This was working fine until Kyle changed teams and his permissions changed and suddenly the github action isn't able to make the API call. Failing on [this line](https://github.com/department-of-veterans-affairs/devops/blob/master/scripts/pst-access-management/check_roster.rb#L52) and when I printed `JSON.parse(response.read_body)` and ran it locally, this is what I saw:
```
{"message"=>"Current user not permitted to use Confluence", "statusCode"=>403}
```
From Kyle Soskin: "Any account with confluence read access should be able to generate an API key. I didn't know the API was mine, I thought they were namespaces to the confluence org or team or whatever but guess I was wrong and it was tied to my account"
From jbritt: "I think we need to see if we can get some kind confluence service account vs using individual’s tokens."

## Background/context 
First noticed this problem in https://github.com/department-of-veterans-affairs/va.gov-team/issues/47035

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Fix bug so GitHub action can check the Platform roster in Confluence.

## Acceptance Criteria 
- [ ] PR merged and tested

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
Plan outlined in the thread linked in previous comment:

1. use [vagovdevops@va.gov](mailto:vagovdevops@va.gov) to get a new confluence account.
2. save the confluence login credentials in AWS param store
3. create the API token from the new confluence account
4. Save token in AWS param store
5. use token!
