### ISSUE TITLE
Staging -Reconfigure configmap and env variables

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#47289]
### Description
The configmap and env variables need to be re-configured in the dev k8 files to fix the embedded url errors.

### Tasks
- [x]  Update settings-configmap.yaml
- [x]  Add ENV variables to deployment.yaml
- [x]  Add ENV variables to deployment-bgs-evss.yaml
- [x]  Clean up unused variables in secrets.yaml
- [x]  Create db-migrate-job
- [ ]  Remove secrets in parameter store
