### ISSUE TITLE
[Bug] Payment Info V2: Copays Bug in Staging

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47288]
## Background
When trying to validate the recent changes to the Benefit Payment and Debts sections we noticed that My VA would not load for user 80. We believe this is a paper check user so we wanted to verify that there is not any issues with paper check users. Taylor investigated and found we were showing the latest copay amount and not the total amount of copays owed. 

## Tasks
- [x] Update code to include total copay amount and not just the latest copay amount
- [x] Push changes to staging
- [x] Validate in Staging with user 80

## Acceptance Criteria
- [x] Copay card under Outstanding Debts should show total amount of all copays owed.

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  PM
- _How can this work be validated?_  Log in with User 80 and ensure total copay amount is accurate.

**Comment by ericasauv09** [comment]
validated that user 80 is working now, user 36 has multiple copays that are mismatching the information shown in the debt portal. Opened #47722 to look into that issue. Closing this ticket since we have another one open to resolve this bug.![Screen Shot 2022-09-30 at 10.33.00.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/821c4ead-0b23-476b-912c-a268b014255c)
