### ISSUE TITLE
Reconfigure dev k8's config mapping

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#47281]
### Description
The configmap and env variables need to be re-configured in the dev k8 files to fix the embedded url errors.

### Tasks
- [ ] Update settings-configmap.yaml
- [ ] Add ENV variables to deployment.yaml
- [ ]  Add ENV variables to deployment-bgs-evss.yaml
- [ ] Clean up unused variables in secrets.yaml
