### ISSUE TITLE
Design | Profile | Screenreader Accessibility Issue | Account Security

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47299]
## Background
The Accessibility team informed us that when navigating by heading on the Account Security page, it is easy to skip all the main fields when using a screenreader. Recommendation is to update the headings to improve the page. 

> Recommendation from Angela: "You can put the email address change at the top under H1 under an H2 and then another that says completed tasks (H2) - or put the email part somewhere else and then get rid of the rest"

## Tasks
- [x] Explore alternative options to improve accessibility for screen readers on the Account Security page
- [ ] Review design options with accessibility 
- [ ] Review design options with FE 
- [x] Review design options with PM and PO 
- [ ] Create new sketch files/update existing ones where applicable
  

## Acceptance Criteria
- [ ] Approvals received
- [ ] Documentation updated
- [ ] Notify PM that it is ready for FE implementation

**Comment by cgednalske** [comment]
Hi @Samara-Strauss! I have a couple questions about the terms and conditions on Account security. 

What is the background on why we include that prompt/field on this page? It seems entirely healthcare related, so I'm wondering about the placement and how it applies to the rest of Profile info or tools. 

Also, does a user needs to have 2-factor authentication setup to use the healthcare tools we refer to? 

Thanks so much!

**Comment by Samara-Strauss** [comment]
The T&C doesn't really have another place to live, so it remains in the profile. It's a vestige from the old days when profile and account settings used to be separate. 

Right now, most health care tools live on MHV, so the answer to whether people need 2FA to access them is maybe. MHV has a totally different way they handle accounts and LOA. However, I would imagine that when the health tools move over to VA.gov, people will need to be LOA3 to use them, and that means they will also have 2FA if they are accessing VA.gov with ID.me or Login.gov.

**Comment by cgednalske** [comment]
@Samara-Strauss ok thanks - that's super helpful! I might have some more follow-up questions on this later, but for now that's perfect. 👍

**Comment by SKasimow** [comment]
Hi - let's close this out and get a new ticket opened for this. 

@ericasauv09 - could you create a ticket for "part 2" and ping me when you have the ticket # so I can add to Sprint 87? Thx!
