### ISSUE TITLE
[Application Hosting and Deployment] Service topology diagram

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47294]
## Description
Developers, operators, and stakeholders need information that explains key service components. 

## Background/context 
- Complementary micro-services are deployed along with a primary application (app)
- Micro-services support each app with built-in operational capabilities
- Services, in this context, contain 
  - app _(ie, one that provides functionality to end-users)_
  - supporting micro-services for add'l capabilities, e.g.
    - metrics monitoring
    - secrets management
    - external DNS resolution 
- See parent epic 

---
## Tasks
- [ ] Provide a diagram that explains the major components of services deployed to EKS

## Acceptance Criteria 

- [ ] Diagram exists in Confluence that explains service topology (1 for deployment cluster, 1 for tooling/utility cluster)
  -  [ ] Traefik / Ingress
  -  [ ] Datadog agents
  -  [ ] Cert manager
  -  [ ] External DNS
  -  [ ] External Secrets
  -  [ ] Metrics server
  -  [ ] Cluster auto-scaler
- [ ] Links to resources (such as forms, code, repos, and workflows) as needed

**Comment by jhouse-solvd** [comment]
#duplicate of #47294 (which is more up-to-date)
