### ISSUE TITLE
[Application Hosting and Deployment] Provide service topology diagram (EKS)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47293]
## Description
Developers, operators, and stakeholders need information that explains key service components. 

## Background/context 
- Complementary micro-services are deployed along with a primary application (app)
- Micro-services support each app with built-in operational capabilities
- Services, in this context, contain 
  - app _(ie, one that provides functionality to end-users)_
  - supporting micro-services for add'l capabilities, e.g.
    - metrics monitoring
    - secrets management
    - external DNS resolution 
- See parent epic 

---
## Tasks
- [ ] Provide a diagram that explains the major components of services deployed to EKS

## Acceptance Criteria 
- [ ] Diagram exists in Confluence
- [ ] Links to resources (such as forms, code, repos, and workflows) as needed

**Comment by jhouse-solvd** [comment]
duplicate of $47292
