### ISSUE TITLE
[FE] My VA Redirect: Post launch code cleanup

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47291]
## Background
**UPDATE 5/16/23:** re-opening this ticket as the work was not fully completed. In this case, the feature flag needed to be removed from FE code and API code, but was only removed from FE.

Now that the Redirect feature has been live for over a week we can proceed with removing the feature flag and conducting any other post launch code cleanup that is needed. Today (9/20) there were some Prod issues with va.gov overall. Before we remove the feature flag we should ensure these issues have been resolved and things are stable.

## Tasks
- [X] Remove feature flag from FE code for Redirect (`my_va_redirect`)
- [x] Remove feature flag from API code for Redirect (`my_va_redirect`)

## Acceptance Criteria
- [ ] Redirect feature flag is removed from FE and API code and no longer visible on feature flipper

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** FE dev
- **_How can this work be validated?_** confirm toggle is removed and tests are updated

**Comment by tmitchellgcio** [comment]
Merged waiting on staging deployment

**Comment by ajakabcin** [comment]
Re-opening this ticket as it wasn't fully completed. The flag was removed from FE code but not from the API code.

**Comment by adamwhitlock1** [comment]
Can confirm that PR was merged and feature toggle is no longer present in yml file.

**Comment by allisonlu** [comment]
^ same

**Comment by adamwhitlock1** [comment]
There is probably the need to ask platform to manually remove the toggle as well from the production database. There is supposed to be a _job_ that cleans out any removed toggles from the related DB table, but there appears to be a bug, so that job does not run at a regular cadence anymore.

Here is a thread from someone that requested such a thing in the past. https://dsva.slack.com/archives/CBU0KDSB1/p1677688205187279

This should probably be the final stem in this process in general, until the bug is sorted out.

**Comment by ajakabcin** [comment]
awesome thanks all!

@dellerbie can you put a request in to the vfs-platform-support channel to get the flag taken down (if it doesn't come down through normal process). I'd reference the thread Adam posted above.
