### ISSUE TITLE
[Design] My VA Audit UX Improvements: Preliminary research strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47313]
## Background
We need to determine our strategy for conducting usability testing on our latest designs of the audit improvements on My VA. We don't need to have a formal research plan doc written up at this point but we should determine our high level goals and exactly how we'll test (i.e. in code or with a prototype)

## Tasks
- [x] Craft a draft plan for how we will conduct this round of research 
- [x] Determine high level goals of this round of research
- [x] Discuss proposal with team

## Acceptance Criteria
- [x] (Nice to have) initial draft plan exists in GH (note this does not need to be a formal research plan at this stage, but can be the start of it/an outline)

**Comment by aagosto90** [comment]
@Samara-Strauss @andaleliz @ajakabcin @ericasauv09 
I updated this [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/research/MyVA-audit-research-plan.md) according to our conversation a couple weeks back. We wanted to narrow down the main goals and questions because it wasn't focused enough on the high levels goals of this research and also wanted to extend the sessions to 60 minutes. Please take a look when you can and let me know if you think the updated research goals are in line with what we're all expecting to find out from this study. Thank you!

**Comment by Samara-Strauss** [comment]
The research goals look good/more scoped to me!

**Comment by andaleliz** [comment]
>Please take a look when you can and let me know if you think the updated research goals are in line with what we're all expecting to find out from this study. 

Yes! I think this is much stronger and more concise.
