### ISSUE TITLE
Toggle VBMS Letter Downloads on

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47318]
## Issue Description
VBMS Letter Incident resulted is the team adding a feature toggle and turning the download feature off on the debt portal.  Feature can be turned back on once the audit has been completed and DMC Leadership approves. 
 
Related Audit issue #[46824](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46824)
---
## Tasks
- [ ] Get approval from DMC Leadership to toggle download feature back on 
- [ ] Toggle download feature back on for Veterans to access letter downloads

## Acceptance Criteria
- [ ] Letters are available for Veterans to download on the debt portal 
---

**Comment by denisecoveyduc** [comment]
Oct 7 - received word from Jill Anderson (DMC) that we can turn VBMS letter download back on. @ScottyRJames did so at 3:30pm EST.
