### ISSUE TITLE
[discovery] Supplemental Claims | Homeless Flash

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#47326]
## Value Statement
**_As a team_**
**_We want to_** understand the complexity of adding a homeless flash to the supplemental claim form
**_So that_** we understand the effort required to deliver this value opportunity.

---
## Background Context
Before building this into the form, we need to understand how it is built, recognized, and maintained.

## Acceptance Criteria
- [ ] We understand why this checkbox isn't on the Supplemental Claim form
- [ ] We understand how a homeless flash is built and recognized by adjudicators
- [ ] We understand the relationship with the Veteran profile (if any)
- [ ] We've documented our proposed approach

## Out of scope
- Code work

## Open questions
- How can we best indicate a homeless flash is needed to adjudicators when it isn't a checkbox on an SC?
- How can a user reverse that decision if it isn't in their profile. We need to ask that upstream question of profile api.

## Tasks
- [ ] Discuss open questions with Alejandro
- [ ] Confirm whether or not OMB impacts this
- [ ] Discuss open questions with the profile team
- [ ] Ask Premal Shah or Kayla Watanabe to provide the right contact in BGS for the service call so we know how it works
- [ ] Talk to adjudicators recommended by Alejandro (Davide Eckert and Angela Moritz)

**Comment by saderagsdale** [comment]
@thehastingsp added a ticket for our line of questioning into the homeless flash. Alejandro's answers to our questions:

-  I talked to the lighthouse team about the Homeless flash and they told me that they use BGS to write that service call, and Premal Shah or Kayla Watanabe can provide you the right contact in BGS for the service call.
- I don’t know a specific reason why the homeless selection isn’t on the form; likely something that would be included on the next version.
- The “homeless” flash is applied to the Veteran’s corporate record and is visible up front for adjudicators. A service call to write into the corporate record table for flashes from the front-end would be the best scenario.  Feasibility would have to be assessed with BGS contact.
- Denied issues have diagnostic codes associated with them and an a disability decision code associated with them.
- Here is a table I received for EP 040 disability decisions:
(see original email)
- We can add additional questions to the interview process without OMB approval; the opposite, however – isn’t true.  We can’t remove questions/opportunities to respond to things on the form through the online application.
- I can work on the SME listing to include folks from OAR, but for now – you can feel free to reach out to Davide Eckert and Angela Moritz and interview them.
