### ISSUE TITLE
[task] Google Analytics form audit for 526ez and HLR

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#47329]
## Value Statement
**_As a_** team
**_We want to_** audit our form dashboard funnels for 526ez and HLR
**_So that_** we have the most update to date version of the funnels as we know things changes.

---
## Background Context
The Analytics team has asked us to audit our dashboard funnels to ensure that nothing has changed. 

## Tasks
- [ ] Complete the [Form Product Details](https://docs.google.com/spreadsheets/d/1dt84R0tWB-E-RuV-jyaCXRVPacC97ds0qAW1DiBoWik/edit#gid=981224988) tab for the 526ez
- [ ] Complete the [Form Product Details](https://docs.google.com/spreadsheets/d/1dt84R0tWB-E-RuV-jyaCXRVPacC97ds0qAW1DiBoWik/edit#gid=981224988) tab for HLR
- [ ] Share any changes with Michelle Dooley
