### ISSUE TITLE
[cFSR] UXPin Text Updates

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47337]
## Issue Description
User flow for Streamlined Waiver and Wizard

---
## Tasks
- [] Update [UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571?mode=vid) as noted on comments. Danielle may add additional comments through 9/26
- [ ] Document text updates made

## Acceptance Criteria
- [ ] UXPin Updated
- [ ] List of updates is created

**Comment by denisecoveyduc** [comment]
This is a duplicate
