### ISSUE TITLE
[cFSR] UXPin Text Updates

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47339]
## Issue Description
User flow for Streamlined Waiver and Wizard

---
## Tasks
- [x] Update [UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571?mode=vid) as noted on comments. Danielle may add additional comments through 9/26
- [x] Document text updates made

## Acceptance Criteria
- [x] UXPin Updated
- [x] List of updates is created

--
List of updates:
- Global - new breadcrumb text: Home  ›  Manage your VA debt   ›  Request financial help (VA Form 5655)
- Global - new header: Request help with VA debt for overpayments and copay bills
- Global: Need Help? section: change "VA debt" to "VA debt related to benefit overpayments" 
Make sure to include the "TTY:' in the aria label too.
- [Content page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap,comments/6323aa77c7744d006bb3fe16?mode=vid) - "Follow these steps to request help" remove "with VA debt or bills"
- [Content page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap,comments/6323aa77c7744d006bb3fe16?mode=vid) - Change "Take any needed next steps to resolve the debt or bill" to "Take any needed next steps to resolve the overpayment or copay bill"
- [Wizard](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768/comment/sitemap,comments/6323b520ade9f600d5f929e2?mode=vid) - "This form is for Veterans or service members who need help with debt related to VA _benefit overpayments or health care copays_."
- [Employment history- add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842696/comment/sitemap,comments?mode=vid) - "...past 2 years..." change "two" to "2" per style guide
- [Employment history- current job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842697/comment/sitemap,comments) - "...past 2 years..." change "two" to "2" per style guide
- [Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these"
- [Spouse's information](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868491/comment/sitemap,comments/6330c84b673ecf00f65275ef) - Change "regarding your request" to "on your request"
- [Spouse Employment history- add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868494/comment/sitemap,comments/6330c8665989df009e748725) - "...past 2 years..." change "two" to "2" per style guide
- [Spouse Employment history- current job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868495/comment/sitemap,comments/6330c88f1e9dd2004d0bf014) - "...past 2 years..." change "two" to "2" per style guide
- [Spouse's Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these"
- [Add a credit card bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145377492/comment/sitemap,comments/6330caca660304002288c5c5?mode=vid) - change "bill's" to "bill"
- [Housing expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022052/comment/sitemap,comments/6330ca8c8b556b003b931c4b?mode=i) Change "the following expenses" to"these expenses" 
- [Monetary assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084977/comment/sitemap,comments/6330c943e6ed8d007267d225?mode=i) - Change "the following" to"these" 
- [Utility bills](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145111152/comment/sitemap,comments/6330caa7f6cbe90097241cd5?mode=i) - Change "the following" to"these" 
- [Dependents](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022115/comment/sitemap,comments/6330c92e7468f2005c0dacfa?mode=i) - remove "below"
- [Other assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084980/comment/sitemap,comments/6330ca46657884008c544c59?mode=i) - remove the ( ) around this s
- [Add a medical bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482544/comment/sitemap,comments/6330cb1eddb307014e208c85) Change "one medical bill below" to "one medical bill here"
- [Other debt selection](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482546/comment/sitemap,comments/6330cb84681b28013416e68f) - Change "debt below" to "debt here"
- [Debt selection](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150718130/comment/sitemap,comments/63245bcae3ace701293483da) Change "$amount debt" to "$amount overpayment"
- [Real estate](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146385053/comment/sitemap,comments/6330c98ea2db6a007203aebd) - Change "regarding your request" to "on your request". Delete "in order". 
- [Resolution option benefit debt](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789115/comment/sitemap,comments?mode=i) - Change "we will" to "we'll". Change "you're unable to" to "can't" for simplicity and active voice. 
- [Resolution option copay](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150667633/comment/sitemap,comments?mode=i) - Change "we will" to "we'll". Change "you're unable to" to "can't" for simplicity and active voice.
- [Review Page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487560/comment/sitemap,comments) - Change "Please click on" to "Select"
- [Confirmation](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487721/comment/sitemap,comments/6330cde2ddb307014e208c86) - Change to: Login.gov, ID.me, DS Logon, or My HealtheVet. Change "Once you're signed in" to "After you sign in"

**Comment by mgleo** [comment]
Question: [Resolution options](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789115/comment/sitemap,comments/632486e6a0c0110051a8bbb1?mode=i) Accept, Approve, or Receive?

Additional comments were made during demo on 10/4/22

**Comment by denisecoveyduc** [comment]
Let's follow up with the content team on the change for the resolution option word above. Are the rest ready to be handed to FE now @mgleo? If so let's set up a quick sync with @OptionSelect and @Dr-Pongo to discuss so we can move these forward.

**Comment by mgleo** [comment]
Yes, everything documented in the list above has been updated on UXPin.

**Comment by denisecoveyduc** [comment]
@mgleo I will close this one out since the changes look good but let's sync up with @Dr-Pongo and @OptionSelect on how they like to do design>dev handover.  
cc: @briepipitone
