### ISSUE TITLE
[FE] [BUG] Loading message references pre-check-in on day-of

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#47347]
## Background

To reproduce:

Go to `/health-care/appointment-check-in/error?error=bad-token` and refresh the page. You will see the message "Checking the Pre-check-in status".

## Tasks
- [ ] A message appropriate to day-of is shown, or a more generic message is used
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey with the appSet HOC and data persistence stuff, it looks like this issue no longer exists. Can you validate that you also don't see this behavior and close?

**Comment by loripusey** [comment]
validated in staging & prod; no longer see the bug
