### ISSUE TITLE
[eFSR] Content changes

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#47357]
## Issue Description
Update content changes to reflect what the mockups show. 
[Design ticket reference](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46160)

---
## Tasks
- [x] Confirm which feature flag this should be behind.
- [x] **[Add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842696/comment/sitemap?mode=i)** - [Add Platform's new date component](https://design.va.gov/components/form/date-input) (This front-end update was already made)
- [ ] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - add "TSP"
- [ ] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - clarify brokerage account for stocks and bonds?
- [x] **[Wizard intro](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768)** - "...need help with _debt related to VA benefits or health care copays._"
- [x] **[Trailers, campers, boats](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*wfldoq*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/145355861/comment/sitemap)** "Estimated value of _all of_ your..."
- [ ] **[Vehicle value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965)** - "This includes vehicles with a loan."
- [ ] **[Real estate value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*uewksx*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/146385053/comment/comments,sitemap)** - "This includes properties with a mortgage."
List of updates:
- [ ] Global - new breadcrumb text: Home  ›  Manage your VA debt   ›  Request financial help (VA Form 5655)
- [ ] Global - new header: Request help with VA debt for overpayments and copay bills
- [ ] Global: Need Help? section: change "VA debt" to "VA debt related to benefit overpayments" 
Make sure to include the "TTY:' in the aria label too.
- [x] [Content page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap,comments/6323aa77c7744d006bb3fe16?mode=vid) - "Follow these steps to request help" remove "with VA debt or bills"
- [x] [Content page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021571/comment/sitemap,comments/6323aa77c7744d006bb3fe16?mode=vid) - Change "Take any needed next steps to resolve the debt or bill" to "Take any needed next steps to resolve the overpayment or copay bill"
- [x] [Wizard](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768/comment/sitemap,comments/6323b520ade9f600d5f929e2?mode=vid) - "This form is for Veterans or service members who need help with debt related to VA _benefit overpayments or health care copays_."
- [x] [Employment history- add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842696/comment/sitemap,comments?mode=vid) - "...past 2 years..." change "two" to "2" per style guide
- [x] [Employment history- current job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842697/comment/sitemap,comments) - "...past 2 years..." change "two" to "2" per style guide
- [ ] [Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these"
- [x] [Spouse's information](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868491/comment/sitemap,comments/6330c84b673ecf00f65275ef) - Change "regarding your request" to "on your request"
- [x] [Spouse Employment history- add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868494/comment/sitemap,comments/6330c8665989df009e748725) - "...past 2 years..." change "two" to "2" per style guide
- [x] [Spouse Employment history- current job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868495/comment/sitemap,comments/6330c88f1e9dd2004d0bf014) - "...past 2 years..." change "two" to "2" per style guide
- [ ] [Spouse's Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these"
- [ ] [Add a credit card bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145377492/comment/sitemap,comments/6330caca660304002288c5c5?mode=vid) - change "bill's" to "bill"
- [ ] [Housing expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022052/comment/sitemap,comments/6330ca8c8b556b003b931c4b?mode=i) Change "the following expenses" to"these expenses" 
- [ ] [Monetary assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084977/comment/sitemap,comments/6330c943e6ed8d007267d225?mode=i) - Change "the following" to"these" 
- [ ] [Utility bills](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145111152/comment/sitemap,comments/6330caa7f6cbe90097241cd5?mode=i) - Change "the following" to"these" 
- [x] [Dependents](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022115/comment/sitemap,comments/6330c92e7468f2005c0dacfa?mode=i) - remove "below"
- [x] [Other assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084980/comment/sitemap,comments/6330ca46657884008c544c59?mode=i) - remove the ( ) around this s
- [ ] [Add a medical bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482544/comment/sitemap,comments/6330cb1eddb307014e208c85) Change "one medical bill below" to "one medical bill here"
- [ ] [Other debt selection](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482546/comment/sitemap,comments/6330cb84681b28013416e68f) - Change "debt below" to "debt here"
- [x] [Debt selection](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150718130/comment/sitemap,comments/63245bcae3ace701293483da) Change "$amount debt" to "$amount overpayment"
- [ ] [Real estate](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146385053/comment/sitemap,comments/6330c98ea2db6a007203aebd) - Change "regarding your request" to "on your request". Delete "in order". 
- [x] [Resolution option benefit debt](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789115/comment/sitemap,comments?mode=i) - Change "we will" to "we'll". Change "you're unable to" to "can't" for simplicity and active voice. 
- [x] [Resolution option copay](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150667633/comment/sitemap,comments?mode=i) - Change "we will" to "we'll". Change "you're unable to" to "can't" for simplicity and active voice.
- [x] [Review Page](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487560/comment/sitemap,comments) - Change "Please click on" to "Select"
- [ ] [Confirmation](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487721/comment/sitemap,comments/6330cde2ddb307014e208c86) - Change to: Login.gov, ID.me, DS Logon, or My HealtheVet. Change "Once you're signed in" to "After you sign in" *Controlled by Platform :(*

## Acceptance Criteria
- [ ] All content changes match markup
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
related to the copy changes captured on #47339

**Comment by OptionSelect** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/22435
Initial set of work.

Rest of the stuff in ticket looks like itll just happen as we do efsr for the remaining pages but Ill keep ticket open in case to not miss anything

**Comment by OptionSelect** [comment]
Closing per convo with Denise for cleanliness, will make new ticket for remaining EFSR forthcoming changes.

**Comment by denisecoveyduc** [comment]
@OptionSelect When it's ready could you just add that new ticket number here for tracking purposes?
