### ISSUE TITLE
Edit existing unmoderated studies page to focus on surveys

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#47353]
## User Story
_"As a new UX researcher at VA, I want to understand and follow VA guidelines for using surveys, so that I can get reliable results while following PRA rules and respecting veterans' privacy."_

Assignee: 
Peer Reviewer:

## Description
Rename and rewrite existing unmoderated surveys page on Platform/Research to shift to focus to special requirements of using surveys at VA

## Impacted Artifacts
[Planning Unmoderated Surveys](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies) page on Platform/Research

## Tasks
- [ ] _Create copy of unmoderated page in [Platform Website Drafts](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980)_
- [ ] Rewrite/edit page to stress special considerations of using unmoderated studies on VA projects.
- [ ] Notify peer reviewer of changes
- [ ] Make accepted changes
- [ ] Submit for publication.

## Peer Review
- [ ] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
- [ ] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [ ] Add User Story, description, tasks, and Acceptance Criteria
- [ ] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [ ] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [ ] Ticket has been sized as a team.
- [ ] Ticket has been assigned to a Sprint.
- [ ] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
@naomimarcussen this ticket was discussed at our refinement meeting in January 2024. Since Governance no longer has a researcher on our team, this is no longer relevant for us. I am removing the Governance label, however we may still want to make the recommended changes to the Research pages on Platform Website.

**Comment by naomimarcussen** [comment]
After reviewing the page, very minor changes were made to the [Planning unmoderated research](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies#Planningunmoderatedstudies-FollowingthePaperworkReductionAct(PRA)inyourresearch) page based on feedback from researchers who have recently conducted a survey.

Changes:
Under Setting up an unmoderated study:
- Create the study implement (the card sort or tree test) in Optimal Workshop 
-- should add "survey" into the list in parentheses
-  Generate a separate link to the study in Optimal Workshop for each recruitment cohort
-- The word "token" should be changed to "tag" in b, c, and d

Under Tips for conducting unmoderated studies:
- Abandonment is much higher for unmoderated research
-- add to the end: "as compared to moderated studies"
- Note that Optimal Workshop is not accessible to users with screen readers
-- This isn't true of all of Optimal Workshop but only some types of studies: card sort, tree test, and first click testing. Optimal Workshop's survey tool IS supposed to be accessible to screen readers, though an accessibility specialist should test it to be sure.
- Do not attempt a multi-party unmoderated study
-- What is this? I'm not familiar with this phrase. I think it should be defined so everyone understands what it means. 
-- This statement was removed
