### ISSUE TITLE
DESIGN | Profile | Account security | Update MPI error alerts

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#47350]
## Background

Account security staging and mockups are showing slightly different alerts for MPI errors. Both versions do not completely follow current content guidance.

### Staging:

Not in MPI
![Image 2 - staging - not in mpi](https://user-images.githubusercontent.com/79372956/191548257-c6c3b4e4-a85a-463c-b1aa-39ab5182fd07.png)

**MPI connection error**
![Image 3 - staging - MPI connection error](https://user-images.githubusercontent.com/79372956/191548278-4b27f535-1ae4-4304-b47f-68cd3a697065.png)

### Mockups: ([Sketch files](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc))

**_Note: Currently no alert for MPI connection error_**

**Not in MPI**
<img width="634" alt="Image 1 - Sketch file - Not in MPI" src="https://user-images.githubusercontent.com/79372956/191548114-aeed4515-5aa5-4be0-9b43-201f994436ab.png">

## Tasks
- [ ] Work with Danielle to determine content updates
- [ ] Update alerts in mockups
- [ ] Alert PM and PO of changes
- [ ] Update Account security documentation / contact center guide images

## Acceptance Criteria
- [ ] Content has been approved by Danielle
- [ ] Mockups have been updated
- [ ] PM and PO notified of changes
- [ ] Documentation updated

**Comment by cgednalske** [comment]
Hi @Samara-Strauss! So a few initial questions about all of this. We have two different sets of alerts going on that you see above. One is for a general "MPI connection error" and one appears when we can't match the records in the MPI - called "Not in MPI" error. Both are in staging, but only the second alert type was in our designs. 

### Alert #1 - MPI connection error:

From talking to Danielle, it sounds like the first type of alert (general MPI connection error) found in staging is accurate and in line with the error message in the rest of profile, so I've added it to our designs. Does this sound right to you?

### Alert #2 - Not in MPI:

We had more questions around this second alert for when we are unable to match records in the MPI. Danielle confirmed that the staging version is outdated because it mentions the help desk, but the designs also seem a bit off. Wondering if you have some additional background on the alert overall. 

Here are my initial questions:

1. My understanding is that this appears after identity has been verified, but we still can't match the records for some reason. Could you confirm that this is correct and do you happen to know or more around the specifics of why the alert appears?

2. When talking through this with Danielle, our biggest question was why the messaging is centered on health and benefit tools, which doesn't seem to fit with the phrasing in the rest of profile (I.e. "We can't give you access to health and benefits tools..."). I also checked with Liz and she was not sure why this was the case. Do you know if there is a reason for this wording?  

3. As far as what the Veteran can do about this, is going to the nearest VA medical center indeed the right process? Some questions also came up about this. In comparison, a somewhat similar alert in Military information (below) has different guidance.

<img width="692" alt="Screen Shot 2022-09-26 at 9 08 29 AM" src="https://user-images.githubusercontent.com/79372956/192326845-fd5fc0e1-10ed-46e8-8efa-bce47e79fa0c.png">


Thanks so much! Any additional info is super helpful in getting the language straightened out with Danielle.

**Comment by Samara-Strauss** [comment]
> From talking to Danielle, it sounds like the first type of alert (general MPI connection error) found in staging is accurate and in line with the error message in the rest of profile, so I've added it to our designs. Does this sound right to you?

Yes, that looks right to me.

> My understanding is that this appears after identity has been verified, but we still can't match the records for some reason. Could you confirm that this is correct and do you happen to know or more around the specifics of why the alert appears?

I'm so sorry, but I honestly do not remember creating this alert, which I realize is unhelpful. We definitely would only be able to show something like this to LOA3 users, and it sounds correct that this would show to LOA3 people who aren't showing up in MPI.

> When talking through this with Danielle, our biggest question was why the messaging is centered on health and benefit tools, which doesn't seem to fit with the phrasing in the rest of profile (I.e. "We can't give you access to health and benefits tools..."). I also checked with Liz and she was not sure why this was the case. Do you know if there is a reason for this wording?

I have no recollection of why this specific copy was chosen, but it can certainly be changed.

> As far as what the Veteran can do about this, is going to the nearest VA medical center indeed the right process? Some questions also came up about this. In comparison, a somewhat similar alert in Military information (below) has different guidance.

TBH I have no idea what people should do if they aren't in MPI. The military info alert is in reference to a different system, so we can't give the same guidance for the MPI alert as the military info alert. I can ask in the identity channel if there is anything someone could do if we detected they weren't in MPI.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss! This is all really helpful - and good to know there's not any specific reasoning that you know of for some of the wording. 

And just saw your question for the identity team - thanks so much for checking in with them!

**Comment by Samara-Strauss** [comment]
@cgednalske This copy works, but I'm wondering -- do we already have a similar error elsewhere in the profile? I'm so sorry I can't remember the specific scenario, but I think we might have something that exists that's close enough to this. Basically, I'm wondering if we can repurpose an existing error instead of adding a new one. The answer may be no (which is fine), but would you mind looking through our existing documentation on error states for each profile product to see if there's anything we have already that might fit this use case?

> A remaining question to explore is if/how this applies to caregivers and dependents. Do you happen to know if caregivers and dependents are also in MPI? If they might also see this alert, we'll need to confirm this messaging works for them too.

Yes, everyone who has ever had an interaction with the VA is in MPI. You and I are both in MPI (otherwise, we wouldn't be able to use the profile in production). However, keep in mind that we don't differentiate formally between user types on the site, so a caregiver or dependent won't see separate error states or functionality.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss! I've looked through everything in our Sketch files and contact center documentation guide and rounded up all the relevant alerts. I didn't find anything that matched up with what we're needing - details below - so it's looking like a custom message might be the way to go. However, I think there might be opportunities to streamline some of these alerts in general. 

The closest alert to what we're working on here are still the two Account security alerts we started from. Other than those, the most similar alert is for the **Military info** (for matching records), but there are significant differences with what the issue is and what the Veteran/user can do to resolve it. So we don't have anything completely in line with the Account security situation, due to the error itself beginning the process of resolving the issue. 

<img width="550" alt="Screen Shot 2022-10-11 at 10 34 34 AM" src="https://user-images.githubusercontent.com/79372956/195160755-4b53f3cd-2a60-4e2e-a479-1ebceae9e558.png">

Then there are other Military info alerts that are about accessing, not matching, so they don't quite match up either. Rather, these match up with the other Account security alert we have for a general MPI error.

<img width="553" alt="Screen Shot 2022-10-11 at 10 35 08 AM" src="https://user-images.githubusercontent.com/79372956/195160873-f39d67b8-35f1-4e0c-92a0-6223ed99eb5e.png">

All other relevant alerts are for general backend errors where we similarly can't access information, rather than not being able to match records. But these often mention something being wrong, which Danielle had hoped to stay away from.

<img width="528" alt="Screen Shot 2022-10-11 at 10 36 07 AM" src="https://user-images.githubusercontent.com/79372956/195161050-3d8b2352-cc34-41d1-b8ac-14aa45a96141.png">

So it's looking like a custom message is needed here. Are you ok with moving forward with something like the wording Danielle proposed the other week? And regardless, I'll check with her about "try again later" vs "check back soon," as I'm seeing both throughout. 

Overall, while going through all of this, I've noticed the language varies slightly throughout Profile alerts and might not match recent guidance. For example, "please" is used in a few places, though I know this is something we're now asked to avoid. There are also a few different versions of similar instructions, like what I mentioned with  "please try again later" and "please refresh this page or try again later" vs. "please check back soon." Sometimes we say "something went wrong" and sometimes we don't. It might be worth doing a brief content audit to take a look at them and update some of the language across the board.

**Comment by Samara-Strauss** [comment]
Yep, the original messaging you all worked on sounds fine. Ideally, we'd streamline these across sections so we don't have these slight wording differences, but that's low priority compared to other work.

**Comment by cgednalske** [comment]
Ok, sounds good. Will move forward with the original messaging and leave those other differences as they are for now. 😃 Thanks!

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- Danielle had one more minor change for this - now updated 👍 Here's the mockups for the [Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/AxG3GRz) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/jgY3M2G) versions. If all looks good, I can add a new screenshot to the contact center guide. 

@SKasimow would you mind re-sharing the Google Doc version of the guide with me so I can make sure I'm working on the latest version?

**Comment by cgednalske** [comment]
@adamwhitlock1 here's the alert change we're talking about 😃

**Comment by Samara-Strauss** [comment]
Also, if this error occurred, would we be able to show that version of the nametag? I would imagine we wouldn't be able to show military branch or disability rating if we can't verify their identity.

**Comment by SKasimow** [comment]
@cgednalske - just want to make sure I'm following this thread so I can create a front-end ticket. Can you confirm the following:

- We only need to update the alert for when a user is not found in MPI
- The update to this alert should read:
![Screen Shot 2022-10-14 at 4.01.19 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/1a6514a8-f1cb-4cb1-afc0-68c11fbc3e88)

- If above is correct, did the Identity team provide more guidance? It doesn't seem like telling user to try again later will resolve  -- unless the Identity team advised a retry.

**Comment by cgednalske** [comment]
> I am so sorry if I already asked this, but are we sure we'd see the 2-factor authentication prompt if this error occurred?

@Samara-Strauss No problem! Yep - confirmed with Adam while doing the documentation that 2-factor identification always shows - even for LOA1, so yes that would still show. It's terms and conditions that sometimes doesn't show. Here's what Adam confirmed shows for both this and the general MPI error alert (note: first alert still has the old wording).

<img width="948" alt="Screen Shot 2022-10-14 at 1 13 38 PM" src="https://user-images.githubusercontent.com/79372956/195939730-96a572cf-a22b-4baa-b2d5-202be278c1c7.png">

> It looks like there's a formatting issue in the blue box on this mockup, both for desktop and mobile.

Oh so glad you noticed this! Not sure what happened there - maybe a change due to a library update. Will make sure that's fixed.

> Also, if this error occurred, would we be able to show that version of the nametag? I would imagine we wouldn't be able to show military branch or disability rating if we can't verify their identity.

That's an excellent questions so I'll sync with Adam to check. My understanding was that this alert behaves the same way as our general MPI error alert. Do we know what happens to the nametag if that alert appears? No changes to the nametag are documented in the designs, but that might have a similar situation. 
In general, if there is a difference to the nametag, is that something we want to start documenting in the Sketch files too? I don't believe I've ever come across any mockups with different info in the nametag.

**Comment by cgednalske** [comment]
@Sharon -- yep! And because they are so similar I should specify for @adamwhitlock1  that out of the two alerts he found it's the 1st "Not in MPI" one that needs to be updated:

<img width="664" alt="Screen Shot 2022-10-14 at 1 27 34 PM" src="https://user-images.githubusercontent.com/79372956/195939651-b3df58c1-fedb-4547-8e32-8e4a052978d7.png">

> If above is correct, did the Identity team provide more guidance? It doesn't seem like telling user to try again later will resolve this -- unless the Identity team advised a retry.

It does actually, which is what is so bizarre about it. This alert itself sets off the process of resolving it. There's some more info on this further up in this chain and in [this thread](https://dsva.slack.com/archives/CSFV4QTKN/p1664225557501919).

**Comment by cgednalske** [comment]
Actually I'll just ask @adamwhitlock1 right here so it's documented for all of us! 😄  

Adam, are you able to tell what happens to the nametag information when either of the above errors are shown? Samara has a great point that military info and disability rating seem like they would not be shown if records can't be matched or accessed.

**Comment by SKasimow** [comment]
@cgednalske - thanks for the slack thread; that surprised me but is good news!

**Comment by Samara-Strauss** [comment]
> That's an excellent questions so I'll sync with Adam to check. My understanding was that this alert behaves the same way as our general MPI error alert. Do we know what happens to the nametag if that alert appears? 

Someone would have to confirm, but if we can't match someone in MPI, we likely can't match their records to show things like military info or disability rating. TBH, I'm not 100% sure if we'd be able to show their full name, or if it would be more like the LOA1 nametag that shows the email address.

> No changes to the nametag are documented in the designs, but that might have a similar situation.

LOA1 nametag should be different.

> In general, if there is a difference to the nametag, is that something we want to start documenting in the Sketch files too? I don't believe I've ever come across any mockups with different info in the nametag.

Yes, we should document if there is a substantial and known difference in the nametag based on circumstances, like the LOA1 nametag being just the email address because we can't determine someone's name, military info, or disability rating.

**Comment by cgednalske** [comment]
Actually [Angela's audit](https://app.mural.co/t/vsa8243/m/vsa8243/1648129585496/d22080eb307aac8bda5ba1153e013a386b7f1396?sender=u28f508d646c449cc1afe4873) of the nametag nicely outlines most of the different use cases! 🎉  It does not include LOA1, but this situation seems like it would fit with the last version: **LOA3 - no branch of service**. 

<img width="695" alt="Screen Shot 2022-10-17 at 9 38 46 AM" src="https://user-images.githubusercontent.com/79372956/196234412-0c8086f1-bab8-415c-85e3-f990fb842f30.png">


In my (very minimal) LOA3 account, I have a Military information error alert saying that my records can't be matched, and then my nametag is the same as the **LOA3: no branch of service** above. Would it make sense that this situation with the Account security alert uses the same nametag? This is my impression as it seems like full name relies on if ID verification has been complete and would still show.

**Comment by Samara-Strauss** [comment]
> In my (very minimal) LOA3 account, I have a Military information error alert saying that my records can't be matched, and then my nametag is the same as the LOA3: no branch of service above. Would it make sense that this situation with the Account security alert uses the same nametag? This is my impression as it seems like full name relies on if ID verification has been complete and would still show.

TBH, I am not sure. Being able to connect to MPI and not having a military branch of service is very different than not being able to connect to MPI at all. I really would think the nametag would not even be able to show the full name if we couldn't connect to MPI, but we'd need to confirm.

**Comment by SKasimow** [comment]
Hi @cgednalske - think it makes sense to include this with the Nametag ticket you opened. Should I target that for Sprint 86?

**Comment by SKasimow** [comment]
@cgednalske - can you provide the link to the updated sketch file we should use to make the updates?

**Comment by cgednalske** [comment]
@SKasimow if it fits in the sprint plan and is enough of a priority, I'm good with that going in Sprint 86 👍  

In that case, mockups are the same as those listed above, but they're kind of buried now, so here they are again 🙂: [Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/AxG3GRz) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/jgY3M2G)

**Comment by SKasimow** [comment]
Thank you!

**Comment by cgednalske** [comment]
@SKasimow can we close this? Should all be complete.

**Comment by SKasimow** [comment]
Yup! And for reference the corresponding FE ticket in backlog is: #48501
