### ISSUE TITLE
[eFSR] Content changes

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#47356]
## Issue Description
Update content changes to reflect what the mockups show. 
[Design ticket reference](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46160)

---
## Tasks
- [ ] Confirm which feature flag this should be behind.
- [ ] **[Add a job](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842696/comment/sitemap?mode=i)** - [Add Platform's new date component](https://design.va.gov/components/form/date-input) (This front-end update was already made)
- [ ] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - add "TSP"
- [ ] **[Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977)** - clarify brokerage account for stocks and bonds?
- [ ] **[Wizard intro](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021768)** - "...need help with _debt related to VA benefits or health care copays._"
- [ ] **[Trailers, campers, boats](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*wfldoq*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/145355861/comment/sitemap)** "Estimated value of _all of_ your..."
- [ ] **[Vehicle value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965)** - "This includes vehicles with a loan."
- [ ] **[Real estate value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*uewksx*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/146385053/comment/comments,sitemap)** - "This includes properties with a mortgage."

## Acceptance Criteria
- [ ] All content changes match markup
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
This has been resolved and anything remaining will be addressed as part of #48446
