### ISSUE TITLE
Audit Wireframes to Identify Inconsistencies with Production

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47366]
## Tasks
- [x] UX QA intro
- [ ] Analyze all production-level wireframes to identify inconsistencies with what's in Staging
    - Refer the Product Guides & User Flows for all user cases that need to be tested
- [ ] Document the inconsistencies

**Comment by benbrasso-agile6** [comment]
I didn't see this in Abstract for check in

<img width="726" alt="Screen Shot 2022-10-07 at 1 11 08 PM" src="https://user-images.githubusercontent.com/101129355/194613679-921d32ef-3803-41bc-995d-121e46b3a168.png">

**Comment by benbrasso-agile6** [comment]
Also, I didn't see a wireframe for "confirm emergency contact" in master.

**Comment by zach-park** [comment]
@loripusey here is the spreadsheet that captures the audit details that @kellysmith1008 and I put together: 
https://docs.google.com/spreadsheets/d/1vr5m0tfqAtCtBFLMvn54aU9bdWhxR7GRxNkZzw42G10/edit#gid=0

**Comment by loripusey** [comment]
@zach-park I added a few questions and a comment to the spreadsheet.

**Comment by kellysmith1008** [comment]
@loripusey I responded in the spreadsheet to one of the questions about the facility name but posting here too for reference. Screen readers read all caps as individual letters, not as full words. You can "program" screen readers to read common acronyms as words - NASA, UNESCO, etc - but I don't know how that translates to individual facilities.

**Comment by loripusey** [comment]
Thanks @kellysmith1008 , I created a [bug](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47874) about a week ago to address this issue.

**Comment by zach-park** [comment]
@loripusey , yes. The audit task is complete.
