### ISSUE TITLE
[PM] My VA Audit UX Improvements: Submit analytics request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47368]
## Background
As part of the VSP Collaboration Cycle and development of the My VA audit improvements, we need to submit an [analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) to track new items and revise naming conventions on existing tags.

Guidance [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html).

## Tasks
- [x] Touch base with Samara on details to ensure our KPIs and user interactions are defined 
- [x] Submit [Analytics Implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) ticket.
- [x] Attend Analytics Office Hours to review request

**Comment by ericasauv09** [comment]
Submitted #[50621](ttps://github.com/department-of-veterans-affairs/va.gov-team/issues/50621)

**Comment by ericasauv09** [comment]
analytics team confirmed that any existing links that we are updating the copy on will now have new events in GA. i.e. "View your payments" was changed to :"Review you payments" and now has a new GA event. We will have to document all the old vs new events and when looking at data historically we will have to check both events if we want to see metrics around a particular link.
