### ISSUE TITLE
mod rewrites should use 301 not 302

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#47375]
## Issue Description
Currently when a request is made for path on va.gov like this one "https://www.va.gov/education/how-to-apply"  there is a rewrite of the url to make it "https://www.va.gov/education/how-to-apply/"   because that route is what serves the index.hml file that mimics the look of a path based site.
The rewrite, which is also a redirect, should return a 301  "permanently moved" not a 302 "temporary move".  This does have some SEO impact and also triggers some semi-false alarms in some site scanning tools.

Currently it returns a 302 
![image](https://user-images.githubusercontent.com/5752113/191592093-9c6593bb-38c5-48f2-ba1f-bef554e5d0e5.png)

[Related Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1641491496017900)

---
## Tasks
- [ ] Change the rewrite rule(s) on va.gov to return a 301 rather than a 302 response.

## Acceptance Criteria
- [ ] Visiting a path via a request without a trailing slash ( "https://www.va.gov/education/how-to-apply"), should result in a 301 response as the path is rewritten to include the slash ( "https://www.va.gov/education/how-to-apply/").
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by swirtSJW** [comment]
Interesting and possibly related https://stackoverflow.com/questions/30090254/aws-s3-forces-302-redirects-when-url-has-no-trailing-slash-need-301s
