### ISSUE TITLE
Design | Profile | Conduct Research for "One thing per page"

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47378]
## Description 

Conduct "one thing per page" design conceptPersonal with Veterans

## Tasks 
- [ ] Download final participant list from Perigean
- [ ] Print conversation guide
- [ ] Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [ ] Conduct scheduled research sessions
- [ ] Debrief research sessions w/team
- [ ] Post debrief/updates on slack
- [ ] Debrief research sessions into note-taking spreadsheet
- [ ] Download recordings
- [ ] Download notes from Perigean
- [ ] Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

## Acceptance Criteria
- [ ] Above tasks completed and ready to conduct research sessions

**Comment by andaleliz** [comment]
Yep, this can be closed out!

**Comment by Samara-Strauss** [comment]
WOOO! Congratulations! 🎉
