### ISSUE TITLE
Design | Profile | Research | Synthesize data and produce final report

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47381]
## Background

As a Researcher, I want to synthesize the results from my sessions with Veterans and deliver the final report of my findings so that we can determine whether we should go forward with implementation for "One thing per page" design.

## Tasks
- [x] Review all participant session notes and recordings
- [x] Synthesize research results
- [x] Compile final report
- [ ] Present findings to team and discuss recommendations 

## Acceptance Criteria
- [x] Post synthesis documents to Github
- [x] Write top-line summary

**Comment by andaleliz** [comment]
Hi @Samara-Strauss, @SKasimow @cgednalske @adamwhitlock1 @tpharrison and @jcatergovy - I have a [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/topline-summary.md) published for your initial review. Please have a look and let me know your thoughts! The intro to the doc highlights the purpose of it, and what kind of feedback is important to call out. If you feel like I'm missing something you observed, or there is a particular thing you want me to pay special attention to when I go through in-depth synthesis, please post it in the comments by EOD Monday.  Thank you!

We have one session left, with a screen reader, so that may impact the findings. Still felt it was worthwhile to compile these observations while they're fresh.

**Comment by Samara-Strauss** [comment]
Thanks for this, @andaleliz! In the formal report, we should definitely call out that we did not see differences among people who used screen readers or magnification and people who did not.

**Comment by andaleliz** [comment]
FYI @Samara-Strauss and @SKasimow I updated the title of this ticket to include the whole synthesis, instead of just starting it. I've estimated based on that.

**Comment by andaleliz** [comment]
Latest update:
- [Draft of final report created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md) (not yet ready for review)
- [Mural board affinity mapping](https://app.mural.co/invitation/mural/vsa8243/1664275463723?sender=lizlantz1528&key=19066bf4-337c-4dcb-8196-34268562e07f) ~ 65% complete

**Comment by andaleliz** [comment]
I'm still making progress! This is taking longer than normal since we had such a large participant pool.  Next time, I'm going to schedule a day between the 2nd and 3rd days so we can cancel last-day sessions if we've met our goal without violating the late cancel guidelines.

Affinity mapping is complete and I hope to have the report out for review tomorrow.

**Comment by SKasimow** [comment]
Sounds good!

**Comment by andaleliz** [comment]
@Samara-Strauss and @SKasimow The [findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md) has been peer-reviewed and is now ready for your eyes!

In the key findings and recommendations section, I plan to add links back to relevant points in the document, but will hold off until we're done with any edits since links are dependent on wording.

I realize this is a dense report. Any suggestions on how to make it more digestible are much appreciated!

**Comment by SKasimow** [comment]
Thanks @andaleliz - I'm going to read tomorrow with fresh eyes :)

**Comment by Samara-Strauss** [comment]
@andaleliz this is great! Let's discuss recommendations maybe Monday? I don't see anything that's problematic, just want to make sure we have a chance to review and talk about what we might pursue next sprint.

**Comment by SKasimow** [comment]
Hi @andaleliz - agree! Nice job compiling and summarizing the sessions!!

I can see if everyone can stay on for an extended stand-up on Monday if that's a good place to do a team review.

**Comment by andaleliz** [comment]
I'm going to close this ticket in favor of #47646, since it's duplicative of our planning steps. I created a separate ticket for the research readout steps too (#48274)

**Comment by andaleliz** [comment]
Yes! I sent out a calendar invite. Thanks :)
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
adhoc.team
<https://www.google.com/url?q=https%3A%2F%2Fadhoc.team%2F&sa=D&sntz=1&usg=AFQjCNE4MGCYSFhDl_lZwwTif1R0KYNm0w>
|
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>
@adhocteam
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>

**Comment by SKasimow** [comment]
Hi @ericasauv09 - links to research recommendations are above
