### ISSUE TITLE
Survey Feedback Text Analysis Report

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#47383]
## Issue Description
We will create a new text analysis/sentiment report in Medallia for at least one VFS team/product and provide insights to them.

---
## Tasks
- [ ] Build report in Medallia
- [ ] Share report with relevant team

## Acceptance Criteria
- [ ] _Emerging trends report is created in Medallia for 1 VFS team_
- [ ] _Emerging trends report is delivered to respective VFS team_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
I generated a few reports within the Emerging Trends tab in Medallia and exported them as PDFs, PPTs and excels. I'm not very pleased with any of the results. I'd like to meet with Sarkis to review the emerging trends a bit more and see if there is something I'm missing or get recommendations from him on how to generate reports.

**Comment by ianMcCullough-ob** [comment]
Additional drawbacks:

- The emerging trends highlight general sentiments based on results. It is not built to analyze results based on key terms, it is built to identify general issues.
- Searching for key terms does not produce results that contain that explicit term, but a list of results that may have overlapping terms.
- The downloaded report can list the same response multiple times with a different keyword associated with each listing, making results hard to digest and skews result volume.

cc @jwoodman5

**Comment by jwoodman5** [comment]
Based on Ian's findings ^, we have decided not to use this report option in Medallia to deliver _meaningful_ insights to VFS teams. We will research additional reporting options in our next sprint. Closing.
