### ISSUE TITLE
Content updates to Veteran ID card pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47388]
## Issue Description
Stakeholder Melissa Rebstock asked us to make minor changes to references to the Veteran Identification Card to include the word "digital." The changes are on the following pages:

- [Types of Veteran ID cards](https://www.va.gov/records/get-veteran-id-cards/)
- [How to apply for a Veteran ID card](https://www.va.gov/records/get-veteran-id-cards/vic/)

The changes are in this word doc: [https://app.zenhub.com/files/133843125/cb5fccd9-8f3c-4eb9-bbb3-d583dbe13c67/download](https://app.zenhub.com/files/133843125/cb5fccd9-8f3c-4eb9-bbb3-d583dbe13c67/download)

We need to make sure all changes match VA.gov style and adhere to plain language standards. 

We told the stakeholder we would publish these changes anytime before **9/27**.

## Tasks
- [x] Update VIC pages
- [x] Review (Laura)
- [x] Copyedit
- [x] Publish
- [x] Notify stakeholder that changes are live

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by katherine-fung** [comment]
Hi @laurwill, 

The draft changes are ready for review: 

Types of Veteran ID Cards page: 
http://preview-prod.vfs.va.gov/preview?nodeId=473 

How to apply for a digital Veteran ID Card: 
http://preview-prod.vfs.va.gov/preview?nodeId=474 

A few more thoughts: 

- Should we explain the new format of the card anywhere? That it's going to be a type of file (whatever the file format is - I can clarify with Melissa) and that Veterans can show it on their phone and other devices? 

- I'm wondering if we need to call out the shift from physical card to digital ID anywhere, as a note or something? Melissa says: "We’ve been processing cards as digital only from an administrative standpoint since 9/16. We sent notices out to all Veterans with a pending application that the change was coming and we’ve had a banner on the VIC site letting users know that as of 9/16 we were going digital." 

I don't see a banner, but maybe she's referring to a different site. I can clarify this with her. 

- I will confirm with Melissa that the old physical cards are still valid. 

- Do you want me to reach out to Mikki about the new h1 for the "How to apply" page and ask if we'll need a re-direct?

**Comment by katherine-fung** [comment]
Possible note for Types of Veteran IDs page, under paragraph 1 of the "Digital Veteran ID" section: 

Note: As of September 2022, all new VICs are digital. Older physical cards are still valid. If you have a physical card, you can keep using it to show that you're a Veteran and get discounts at businesses.

**Comment by laurwill** [comment]
Thanks so much @katherine-fung !

As we chatted, we're doing a more minimal round of initial edits here to meet today's deadline — adding "digital" to the card descriptions along with a note about the switch. Thanks for that note suggestion! I think that's a much clearer solution to help Veterans understand what's changing. 

I've sent the previews to Melissa ahead of publishing later today — and I'll open a new ticket to pick up the other (very good!) changes you worked on in Drupal. We'll want to give stakeholders more time to review a full reworking of the page, so we'll get to that after these priority updates. 

@megzehn , these 2 pages are ready for copyedit and publishing by COB today, but let's hold on publishing until after 3pm, in case Melissa responds with feedback. 
- Types of ID Cards: http://preview-prod.vfs.va.gov/preview?nodeId=473 
- How to apply: http://preview-prod.vfs.va.gov/preview?nodeId=474

**Comment by laurwill** [comment]
Hi again @megzehn , Melissa approved the changes, so you can publish when you're done with the edits. Let me know if you want to chat about anything!

**Comment by megzehn** [comment]
Thanks, @laurwill! I reviewed the changes and published these 2 pages.

**Comment by laurwill** [comment]
Changes are live and I notified Melissa. @RLHecht we can close this out and I'll open a backlog ticket to pick up less urgent content changes to this page!

**Comment by RLHecht** [comment]
Thanks! Closing

**Comment by laurwill** [comment]
Reopening this ticket due to a request from Tanekwa to update this page — a Veteran reached out to the call center for help using the online VIC request tool. The Veteran reported that these instructions were missing from the VIC page, but we'll need to talk with Melissa to confirm whether these requirements apply: 
- The request has to be submitted using Chrome.
- The photo has to have a background that is “plain” white or beige with no door frames, etc.
- The photo has to be a certain size and no larger.

I'll email Melissa to figure out what updates we may need here.

**Comment by laurwill** [comment]
Whoops I reopened the wrong one! Closing this again
