### ISSUE TITLE
Medallia Data Automation POC for New Performance Dashboard

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#47384]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _Develope a POC data pipleline for Medallia data to be displayed on the new performance dashboard_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@aubreyarcangel - will meet with DevOps and identify requirements

**Comment by ATMiddleton** [comment]
@aubreyarcangel - will meet with DevOps and identify requirements

**Comment by ATMiddleton** [comment]
Blocker
Dev Ops resource - Submit ticket for support - large backlog (Aubrey will create requirements and submit formal request)
