### ISSUE TITLE
Update Collaboration Cycle Docs to Reflect QA Standards

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47394]
## Issue Description
In order to get QA Standards incorporated into the Collaboration Cycle, we need to ensure that Collaboration Cycle documentation is updated to include them. Governance team has provided a list of the documents that would need to be updated:

**VFS Facing**
- [x] https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review
- [x] https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review 
- [x] https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team%2C+staging-review&template=staging-review.md&title=Staging+Review+[Team+Name+-+Feature+Name]
  - _This template will be deprecated by the end of the year._
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2C+collaboration-cycle%2C+governance-team%2C+midpoint-review&template=midpoint-review.md&title=Midpoint+Review+[Team+Name%2C+Feature+Name]
  - _This template will be deprecated by the end of the year._

**Operational**
- [x] https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities
  - _Specifically, the Midpoint Review and the Staging Review code blocks_
- [x] https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities
  - _Likely just the script will need to be modified._
- [x] https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review
- [x] https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities
  - _Likely just the script will need to be modified._

---
## Tasks
- [x] Review each document and update accordingly
- [ ] Peer review all updates
- [ ] Send to Governance team to review/approve
- [ ] Post to Platform Website

## Acceptance Criteria
- [ ] Document updates have been completed, reviewed and approved by Governance team

**Comment by CBonade** [comment]
https://docs.google.com/document/d/1bQ-qm406cZVfk7lSTF0YdZ15Jx9NpFJAGUNfiUeYyus/edit

Initial thoughts here. There's not much here, tbh. Most of these documents it would be roped in within the area that already requests for QA feedback. A couple of docs need the standards added as requested QA artifacts but i don't see much past that.

**Comment by JoeTice** [comment]
I discussions w/ Shira, she said she did not need us to make updates to the Collab Cycle Docs
