### ISSUE TITLE
Analytics Internal - Dashboard Data QA - Debt Portal

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47399]
# Request a data QA for new dashboards, cards, and products

## What this form is for
As we roll out the VANotify edge case dashboard, we need to make sure that our data is accurate and trustworthy. 

---
## Resources
- [Combined Debt Portal dashboard](https://va-gov.domo.com/page/1976847942)
- [Dashboard Build ticket](https://va-gov.domo.com/page/1976847942)
- [Debt Portal Edge Case Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42360)
- [Data Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45142)
- [Mock up](https://docs.google.com/presentation/d/1J53tdRJugf5C8MQjYiKWcGwsr73xyQBGLTggqO8jUn8/edit?usp=sharing)
- **Confluence instructions:** [How to data QA a Domo dashboard](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/How+to+Data+QA+Domo+dashboards)

---
## Tasks
- [x] Verify that data formats are correct
- [x] Validate the data is what is expected (does the info collected measure what it's supposed to measure and does it align with GA?)
- [x] Identify & document invalid values
---
## Acceptance Criteria
- [x] The data on the new dashboard, card, or for a new product in Domo has accurate and trustworthy. The dashboard is ready to be shared with stakeholders.

**Comment by chloedotbrown** [comment]
Data QA is completed! Didn't include the Medallia data, since I QA'ed it initially during ETL creation.

[Here is the spreadsheet documenting the process](https://docs.google.com/spreadsheets/d/1VPaI-8d5_D0sJM5s7kyJQxeHCfiZtU6TWC-90QEOUCU/edit#gid=0). There were a few instances where percentage-differences where higher than usual, but they were either due to very small numbers off by 1 (traffic from Combined Debt Portal to Form 5655) or limitations in GA reporting to recreate Domo metrics (total bounces).

@michelle-dooley - feel free to close ticket if it looks good to you!
