### ISSUE TITLE
[EKS,Helm] Clean up Vets-API Helm Chart

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47393]
## Description
The vets-api Helm chart contains samples and mismatching values.

## Technical notes
- ExternalDNS does not match allowed Rules in IngressRoute
- Sample code for splitting traffic is not needed

---
## Tasks
- [ ] Match ExternalDNS values to IngressRoutes
- [ ] Allow both va.gov and vfs.va.gov domains in IngressRoutes
- [ ] Remove traffic splitting sample code

## Acceptance Criteria 
- [ ] Service is reachable via vfs.va.gov domain
- [ ] Sample traffic splitting code is cleaned up
---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
