### ISSUE TITLE
Usability testing Epic, HMI team

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47396]
## High Level User Story
As a Veteran, I need to be able to find, organize, and reply to my messages, so I can effectively communicate with and manage my messages.

## Goals
_What outcome(s) do we want to see?_ 
- A list of confirmations on the current design iterations
- A list of issues to be addressed in a future design iteration

## Issues to create within this Epic

```
- [ ] Create research plan
- [ ] Recruit for research sessions/Schedule research sessions
- [ ] Create conversation guide
- [ ] Conduct Usability Testing Sessions
- [ ] Synthesis - should be conducted as a team, led by researcher.
- [ ] Research Readout

**Comment by rbsingleton** [comment]
Not sure why the edits to this ticket are being saved as separate tickets... closing this ticket as it's duplicated elsewhere.
