### ISSUE TITLE
Break up funding for VA Notify requests

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47390]
## Issue Description
Combined FSR submission confirmation emails need to be billed to the appropriate department (VBA vs VHA). Work with department teams and VA Notify to configure these templates to be billed separately.

---
## Tasks
- [x] Work with teams to figure out structure
- [x] Update templates and submission code to match

## Acceptance Criteria
- [ ] cFSR submissions bill the correct department
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Rolling this one over to Sprint 84. Combined FSR bug fixes took priority.
