### ISSUE TITLE
[DISCOVERY] Work with Lighthouse team to determine real time data next steps

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47391]
## Issue Description
We've identified Lighthouse as a valuable resource to fetch real time CDW data from. Need to understand how we can progress. Background information can be found on #47069

---
## Tasks
- [x] Reach out to Lighthouse contact
- [x] Draft plan

## Acceptance Criteria
- [x] We know how to move forward with Lighthouse
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Previous discovery can be found on issue #47069

**Comment by denisecoveyduc** [comment]
Met with Lighthouse team during biweekly touchpoint on September 29th. Next meeting is October 4th. Will device a plan and next steps after that secondary meeting.

**Comment by denisecoveyduc** [comment]
Awaiting on meeting with Chintan Patel

**Comment by HeatherRienks** [comment]
@denisecoveyduc to follow up on December email.

**Comment by denisecoveyduc** [comment]
Updates:
12/16/2022: Adam Foster said "I just wanted to circle back and make sure you knew that we have not forgotten about you.  We’re still in the review/approval process.  We won’t have an answer before the end of the year.  I’ll send you an update of where things stand in mid-January.  If any further details surface or you have any questions, please feel free to reach out."

1/10/2023: Denise followed up via email; awaiting response. 

1/25/2023: Denise followed up via email a second time; awaiting response. 
The Debt Resolution Team is hopeful that the Lighthouse Health API team will be able to add the following information to the Health API for us to pick up and use in the user's debt portal experience.

- Payment information on medical copay– (Understanding of when Veteran makes a payment (incremental or full) on medical copay
- Status of a medical copay debt – (Understanding when a debt has been suspended/ referred to treasury/ put on a repayment plan)
- New medical copay statement - (Understanding when there is a new copay statement available for the Veteran. Although we need to validate how CDW treats debts that are awaiting coding/insurance)

Once this information is available via the API the debt design team will need to review user experience changes.

**Comment by denisecoveyduc** [comment]
As of 1/25 the Lighthouse team is still sizing this effort.

Adam said via email  "_We’re still making progress.  I don’t have a design or timeline for you yet, but we’re working towards that.  I will certainly reach out when we have questions or we make additional progress._"

We will give them some time since our team is not ready to move forward with this work anyways. Denise will follow up as we get closer to implementation time.

**Comment by denisecoveyduc** [comment]
Feb 10- Closing this one out since initial discussion with the Lighthouse team has been initiated. The Lighthouse team is currently sizing the efforts and will come back to us when they have a better understanding of next steps. For now the discovery work is complete.

**Comment by HeatherRienks** [comment]
@denisecoveyduc created ticket #xxx to track the Lighthouse efforts.
