### ISSUE TITLE
[FRONT-END] Transfer LEBANON, PA "STORIES" from legacy web site to NEW Drupal pages [FE-ENGINEER]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4739]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local stories, news releases and Events, so I best know and utilize services in my local medical system.

## Goal
_Move legacy stories, news releases, and events from legacy websites over to new CMS system_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience by moving existing stories into new format_
- _Reduce Click through count by_Highlighting top stories_

## Tasks
_Complete moves from legacy websites to CMS Stories, News Releases, and Events to include:_
- [x] Create profiles for Authors of the stories "PAO/POC for site".
- [x] Move content "Exactly" as is and validate dates/publication of story.
- [x] Pull and modify image from story to be loaded in story and meet new CMS standards.
- [x] Validate and document preview page to send to respective PAO for review.

## Acceptance Criteria

* Create profiles for Authors of the stories "PAO/POC for site".
* All stories (Not to exceed last 24 months) have been transfered to NEW CMS for web system.
* Move content "Exactly" as is and validate dates/publication of story.
* Pull and modify image from story to be loaded in story and meet new CMS standards.
* Validate and document preview page to send to respective PAO for review.
