### ISSUE TITLE
[Research] MHV to VA.gov: Secure Messaging: Usability testing Epic

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47397]
## High Level User Story
As a Veteran, I need to be able to find, organize, and reply to my messages, so I can effectively communicate with and manage my messages.

## Goals
_What outcome(s) do we want to see?_ 
- A list of confirmations on the current design iterations
- A list of issues to be addressed in a future design iteration

## Issues to create within this Epic
- [ ] Create research plan ([ticket 47406](https://app.zenhub.com/workspaces/mhv-to-vagov-secure-messaging-core-team-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/47406))
- [ ] Recruit for research sessions/Schedule research sessions
- [ ] Create conversation guide ([ticket 47408](https://app.zenhub.com/workspaces/mhv-to-vagov-secure-messaging-core-team-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/47408))
- [ ] Conduct Usability Testing Sessions
- [ ] Synthesis - should be conducted as a team, led by researcher.
- [ ] Research Readout

**Comment by rbsingleton** [comment]
@rbsingleton and @jonathanjnelson will collaborate on research plan and conversation guide, and will help with navigating research governance and recruitment. By Light will lead data collection and synthesis.

**Comment by MarciMcGuire** [comment]
This work has been completed.
