### ISSUE TITLE
Create conversation guide and recruitment table for round 2 usability testing

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47409]
## Description
We need to create a conversation guide and recruitment table for Secure Messaging round 2 usability testing. 

## Tasks
- [ ] Create a conversation guide for usability testing in both desktop and mobile environments
- [ ] Create a recruitment table to guide Perigean in recruiting participants
- [ ] Help By Light to pilot test the conversation guide when the prototype is finished
- [ ] Submit conversation guide and recruitment table for review with Research Plan
