### ISSUE TITLE
[Research] Create research plan for Round 2 usability testing

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47405]
## Description
We need to create a research plan for Secure Messaging round 2 usability testing. 

## Tasks
- [ ] Use [Platform Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [ ] Create research plan
- [ ] Ask By Light, @jonathanjnelson, and others as appropriate to review and provide feedback
- [ ] Submit research plan for approval after convo guide has been piloted

**Comment by rbsingleton** [comment]
Duplicates 47406.
