### ISSUE TITLE
[Research] MyHealth: Secure Messaging: Create research plan for round 2 usability testing

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47406]
## Description
We need to create a research plan for Secure Messaging round 2 usability testing. 

## Tasks
- [x] Use [Platform Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [x] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/SecureMessaging_Round1_Usability/usability_testing_round2.md)
- [x] Ask By Light, @jonathanjnelson, and others as appropriate to review and provide feedback
- [ ] Submit research plan for approval after convo guide has been piloted

**Comment by rbsingleton** [comment]
Research plan here (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/SecureMessaging_Round1_Usability/usability_testing_round2.md)
