### ISSUE TITLE
[Research] MyHealth: Secure Messaging: Create conversation guide and recruitment table for round 2 usability testing

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47408]
## Description
We need to create a conversation guide and recruitment table for Secure Messaging round 2 usability testing. 

## Tasks
- [ ] Create a conversation guide for usability testing in both desktop and mobile environments
- [ ] Create a recruitment table to guide Perigean in recruiting participants
- [ ] Help By Light to pilot test the conversation guide when the prototype is finished
- [ ] Submit conversation guide and recruitment table for review with [Research Plan](https://app.zenhub.com/workspaces/mhv-to-vagov-secure-messaging-core-team-614de421e25eb20013d1ee70/issues/department-of-veterans-affairs/va.gov-team/47406)

**Comment by MarciMcGuire** [comment]
@rbsingleton ByLight team has largely taken ownership of this, right?  Should I leave this open for support?

**Comment by rbsingleton** [comment]
@MarciMcGuire - I'm going to be supporting Anne in navigating review from VA research ops - like submitting the plan/ convo guide, adhering to SOPs, etc. So let's leave it open for the moment.
