### ISSUE TITLE
Add Yarn Workspace to VSF vaos

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#47413]
## Description
Adds Yarn Workspaces  to vaos app in vets website

## Original issue(s)
---

## Testing done
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [ ] Visual Web Test:  link  pending 

## Tasks For check-in team to do
- [ ]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [ ]  If required, add` nohoist`  dependencies to root `package.json`
- [ ]  If required , add scripts
- [ ]   Visual Test  link pending
- [ ]  Approve PR

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [ ] Testing done completed
- [ ]  Tasks For check-in team to do

**Comment by rmessina1010** [comment]
PR approval/changes pending [https://github.com/department-of-veterans-affairs/vets-website/pull/22251](https://github.com/department-of-veterans-affairs/vets-website/pull/22251)

**Comment by rmessina1010** [comment]
VAOS has notified me that they are ready to to install,  however this ticket has gone stale. Closing and opening new ticket to start fresh.
