### ISSUE TITLE
Make enhancements to the DraftingTemplate and DraftingTemplate guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47417]
## User Story
I am a Governance team member supporting the Collaboration Cycle trying to provide my feedback for Staging Reviews in the Drafting Template but because it is difficult to add screenshots after an issue is generated, I sometimes add them incorrectly, or I am unable to add them at all, which makes me feel inept, and unprepared.

I am a Governance team member supporting the Collaboration Cycle trying to provide my feedback for Staging Reviews in the Drafting Template but it is easy to forget to complete all parts of the Drafting Template because there is a lot going on in the Drafting Template and it can be hard to navigate which makes me feel embarrassed and frustrated.

I am a Governance team member involved in the Collaboration Cycle trying to enter my feedback at a staging review but it is hard to read/enter feedback because the layout of the column is narrow and does not have a lot of white space which makes me feel anxious I might miss something.

I am a Governance Team member offering feedback for a Staging Review trying to fill out the Drafting Template but automations don't always work because they need to be fixed which makes me feel frustrated.

Assignee: @shiragoodman @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
The DraftingTemplate is the google Sheets template that Governance team members use for documenting their feedback at Staging Review. The DraftingTemplate has several benefits:

1. It allows Governance team members to document their findings in a shared space, closed off to VFS teams. 
2. It allows Governance team members to see what other team members have documented.
3. It allows like feedback to be merged so the resulting issue ticket has input from all applicable team members.
4. It transforms the feedback from Google Sheets to a CSV in gh markdown format, allowing for easy upload/generation of the issue tickets.

However, there are challenges the team faces with the DraftingTemplate, including:

1. Adding images is not possible,
2. The way Gov team communicates that there are images to be added is inconsistent.
3. The layout of the DraftingTemplate is hard to read.
4. Some of the automations are broken.
5. The DraftingTemplate is complex and difficult to navigate.

## Impacted Artifacts
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review)
[DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)
   - This is a new guidance doc that currently communicated the purpose of the DraftingTemplate (as seen above) and where to find it. What other helpful information should the Outline include?
   - Ideally this document and the _How to document feedback for Staging Review_ should work together cohesively. The DraftingTemplate Outline should be focused on the specifications of the tool, and the How to guidance should be focused on how to use the tool to document feedback.

## Tasks
- [X] Shira and Cheryl to meet to discuss challenges with current DraftingTemplate and guidance
- [x] Shira to get input from team on:
   - [x] Modifying DraftingTemplate to show available VA.gov Exp Stds by practice area (ie Cheryl would choose 'content' as step 1 and then only be able to select the stds that impact content)
   - [x] Merging feedback - is this something useful and should we continue to use?
- [x] Cheryl to get input from team on:
   - [x] Preference for adding images/screenshots 
Example of how images will be linked: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/sound%20of%20music.jpg

- [ ] Shira to connect with Allison, Brian and Jim to get their individual feedback on the DraftingTemplate challenges

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [ ] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Governance team members know how to include images by following the DraftingTemplate guidance
- [x] Governance team members are no longer challenged by the layout of the DraftingTemplate
- [x] All automations in the DraftingTemplate work as expected
- [x] Governance team members are able to easily navigate and use the tool
- [x] The DraftingTemplate guidance is clear and easy to follow

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Here is the first rough [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2396619099/47417+-+Cheryl+Draft+-+Staging+Review+Drafting+Template+Guidance) that shows the user how/where to add images to GH.  Number 4 is a work in progress with regard to previewing images.  This is what I found on the net, but when I tried the practical application, I had to go through several more steps to download it to my computer before I could see the image.  I added some verbiage under number one, regarding naming conventions, in the event that we aren't able to preview images from the actual repository.  Make sense?  Let me know what you think.  Thanks in advance!

**Comment by CherylEvans** [comment]
@briandeconinck Thank you so much for your thoughtful comments. :-)

- I borrowed these examples from another document, but agree it is important that we maintain a consistent naming convention within the GH repo to avoid confusion.  I will work on this!

- Yes, that is correct.  You add the image in the GH repo, and then add the GH repo image link to the Drafting Template.  This does seem odd, since all images are going to exist in the same GH repo.  Let me clarify this with Shira.  If we include a direct link to the file itself in the template, does that negate the need for the GH repo?  

- With regard to number 4, Shira had mentioned in our standup that it would be nice to be able to "preview" the image from the GH repo.  I tried to find something on the net, but this is what I came up with.  I always preferred creating an Images folder in the ST, and adding images there.  I think we need more discussion around this.

**Comment by CherylEvans** [comment]
@shiragoodman Please review my edits to the [Drafting Template Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline) when you have a chance.

**Comment by CherylEvans** [comment]
@shiragoodman Please also review [How to document feedback for a Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review), step 3 and 8.  I have added the links and verbiage for adding images, and referencing the Drafting Template Outline as well.

**Comment by shiragoodman** [comment]
@CherylEvans i finished reviewing the DraftingTemplate outline and made some comments. Please make the changes, and then I'll finish it up. There's clearly a lot here that I need to provide input on re: the other tabs of the spreadsheet.

Looking at the How to document feedback for Staging Review next!

**Comment by shiragoodman** [comment]
@CherylEvans I made some comments in the How to document feedback for Staging Review, as well as the How to add images draft. Please take a look and let me know if you have questions

**Comment by shiragoodman** [comment]
@CherylEvans @briandeconinck I created ticket #49603 per our discussion on Thursday 11/10. This ticket will be treated as a tech-debt ticket, with changes to the Staging Review guidance to follow as a separate (not yet created) ticket. 

@CherylEvans for this ticket, please remove all DraftingTemplate guidance from the How to document feedback for Staging Review doc, add it to the DraftingTemplate outline, and add a Warning (or note? you decide) message to the top of the  How to document feedback for Staging Review letting our team know that we acknowledge that this guidance is difficult to follow and we will be addressing at a later date. 

Please let me know if you have any questions! Thank you both.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Please review my [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2421227555/47417+-+Cheryl+Draft+Copy+of+How+to+document+feedback+for+Staging+Review) How to document feedback for Staging Review.  I incorporated all of Shira's recommended changes that were made on the [source page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review), and will copy the draft page to the source page once you both review.  I am including a [link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline) to the DraftingTemplate Outline page as there were edits made to it as well.  Please reach out if you have any questions or concerns. :-)

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Please make all recommendations for How to document feedback for Staging Review to my Draft page as opposed to the source Page.  Thanks in advance! :-)

**Comment by shiragoodman** [comment]
@CherylEvans I did a review of the How to document feedback for Staging review (draft!) and the DraftingTemplate Outline and made comments to both. I think once changes are made, pending Brian's review, they should be good to publish and we can close out this ticket. Please also publish the Image guidance.

I acknowledge that the DraftingTemplate guidance is not complete. I am going to create a ticket for next sprint for me to finish it out. FYI @briandeconinck

**Comment by CherylEvans** [comment]
@shiragoodman I re-read your earlier comments, and published to the designated area.  Everything should be good to go now and everything in its appropriate location.  Once you and @briandeconinck look it over, I will close the ticket.
