### ISSUE TITLE
Add Yarn Workspace to VFS burials 

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#47414]
## Description
Adds Yarn Workspaces  to burials  app in vets website

## Original issue(s)
---

## Testing done
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [ ] Visual Web Test:  link  pending 

## Tasks For check-in team to do
- [ ]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [ ]  If required, add` nohoist`  dependencies to root `package.json`
- [ ]  If required , add scripts
- [ ]   Visual Test  link pending
- [ ]  Approve PR

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [ ] Testing done completed
- [ ]  Tasks For check-in team to do

**Comment by rmessina1010** [comment]
PR approval/changes pending
https://github.com/department-of-veterans-affairs/vets-website/pull/22250

**Comment by CBonade** [comment]
Moving to backlog awaiting confirmation of ownership of this product.

**Comment by MichelleDieudonne** [comment]
@CBonade Are you still looking for an owner for this, or did you find one?  Self-Service looked at this and we can't see how it could be ours since we don't work on the burial application, but it was on my list to continue to follow up since we were asked if we worked on this form and if this item belonged to us.

**Comment by MichelleDieudonne** [comment]
@JoeTice Do you have an answer to our question above?

**Comment by rmessina1010** [comment]
Burials app is not being actively maintained.  Closing.
