### ISSUE TITLE
[COE] Add betamocks for document upload

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#47418]
## Background Context
We have betamocks in place for all calls to LGY except for `/eligibility-manager/api/eligibility/document`. This probably got overlooked on accident, so we should make sure to add it now.

## Acceptance Criteria
- [x] Betamocks have been added for file uploads via standalone uploader

## Tasks
- [x] Add betamocks for file uploads to LGY to `vets-api-mockdata` repo
- [x] Update `config/betamocks/services_config.yml` in `vets-api` repo
