### ISSUE TITLE
Add Yarn Workspace to VSF lgy

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#47415]
## Description
Adds Yarn Workspaces  to lgy app in vets website

## Original issue(s)
---

## Testing done
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [ ] Visual Web Test:  link  pending 

## Tasks For lgy team to do
- [ ]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [ ]  If required, add` nohoist`  dependencies to root `package.json`
- [ ]  If required , add scripts
- [ ]   Visual Test  link pending
- [ ]  Approve PR

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [ ] Testing done completed
- [ ]  Tasks For check-in team to do

**Comment by rmessina1010** [comment]
PR approval/changes pending
https://github.com/department-of-veterans-affairs/vets-website/pull/22252

**Comment by rmessina1010** [comment]
PR changes/approval in progress
https://github.com/department-of-veterans-affairs/vets-website/pull/22251

**Comment by rmessina1010** [comment]
Made updates correcting the export type on platform static-data and forms to be named , instead of a default object. (https://github.com/department-of-veterans-affairs/vets-website/pull/24214)

**Comment by rmessina1010** [comment]
Created a new pull request for setting up yarn workspaces in lgy/coe,  https://github.com/department-of-veterans-affairs/vets-website/pull/24251
Performed initial configuration.

**Comment by rmessina1010** [comment]
Passes unit test, locally.
CHOMA_SEED=j9iu7Dgk9W yarn test:unit

**Comment by rmessina1010** [comment]
Handed off to LGY team  and awaiting response /completion of tasks  for merging.

**Comment by rmessina1010** [comment]
The lgy team is not yet wont be able  perform  their dependency checks/visual testing before the end of this sprint.  Synched  branch to keep it from going stale and I am chunking off that part/merging to main as a separate ticket, and closing this issue. 

Further work here:
https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/58941

**Comment by rmessina1010** [comment]
The lgy/coe team deemed yarn workspaces as not necessary  to their needs.  workspaces was NOT installed.  Closing ticket and PRs (without merging) , as completed.
