### ISSUE TITLE
[EPIC] MHV to VA.gov: MR: General: Generative Research

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47411]
## Goals
- The purpose of this research is to gain insight into user needs and goals related to medical records, users' emic understandings of medical records-related terms, and how these needs, goals, and understandings influence their behaviors.

## Issues to create within this Epic
- [x] Create research plan and conversation guides - [ticket 47739](https://app.zenhub.com/workspaces/mhv-to-vagov-medical-records-core-team-62e98e7a18446f858064d979/issues/department-of-veterans-affairs/va.gov-team/47739)
- [x] Recruit for research sessions/Schedule research sessions - [ticket 48549](https://app.zenhub.com/workspaces/mhv-to-vagov-medical-records-core-team-62e98e7a18446f858064d979/issues/department-of-veterans-affairs/va.gov-team/48549)
- [x] Create research assets - [ticket 48547](https://app.zenhub.com/workspaces/mhv-to-vagov-medical-records-core-team-62e98e7a18446f858064d979/issues/department-of-veterans-affairs/va.gov-team/48547)
- [x] Conduct Discovery Research Sessions - [ticket 48683](https://app.zenhub.com/workspaces/mhv-to-vagov-medical-records-core-team-62e98e7a18446f858064d979/issues/department-of-veterans-affairs/va.gov-team/48683)
- [ ] Discovery Synthesis, Research Readout, Strategy session  - [ticket 49648](https://app.zenhub.com/workspaces/mhv-to-vagov-medical-records-core-team-62e98e7a18446f858064d979/issues/department-of-veterans-affairs/va.gov-team/49648)

```
