### ISSUE TITLE
Refine VFS guidance on the VA 508 Office Audit

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47421]
## User Story
As a VFS team member, I want to know if/when I have to submit an audit request with the VA 508 Office so that I can be certain I am doing what I am required to do.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
In a recent Staging Review, Governance team recognized that the guidance we give to VFS teams on if/when they need to submit an audit request to the VA 508 Office was unclear. 

All VFS teams are required to submit a VA 508 Office Audit request, whether accessibility issues were found during the Staging Review or not. If VFS teams have known accessibility issues and are choosing to launch to production with those issues unresolved, they are asked to communicate those to the VA 508 Office when they submit the audit request.  

_(Is further clarification needed on what should be communicated to the VA 508 Office? Maybe check with @artsymartha68 and Chris Walker about creating a simple template that could quickly and easily communicate to the VA 508 Office a) if a11y issues were found during Platform Collaboration Cycle Staging Review, b) current state of a11y issues)_

VFS teams likely also need guidance on how to identify if an issue is an accessibility issue or not.

## Impacted Artifacts
- Instructions for [how to request a 508 Office audit](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest)
- [Collab Cycle kickoff moderator instructions, Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block), after meeting VFS actions
- [Staging Review - Moderator Responsibilities, during meeting moderator script](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#Step-4.3)

## Tasks
- [x] Determine what information VFS teams should submit to the 508 Office (that would make the 508 Office most happy)
   - [x] Validate with Chris Walker
- [x] Update instructions for how to request a 508 Office audit
   - **Note:** The instructions on Platform website for navigating through the yourIT website are no longer accurate and need to be updated.
  - [Draft changes to the Audit Request section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2409431334/47421+-+Request+support+from+the+VA+508+office)
- [x] Update instructions for VFS team actions after Staging Review (CC ticket code block)
  - [Draft change to code block](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2411298823/47421+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+Staging+Review+code+block+only)
- [x] Update during-meeting moderator script for Staging Review
  - [Draft update to moderator script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2411888641/47421+-+Staging+Review+-+Moderator+Responsibilities+during+meeting+moderator+script+only)
- [ ] Publish changes to Platform website and internal documentation

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] All VFS teams are directed to submit a VA 508 Office Audit post Staging Review.
- [x] VFS teams with known accessibility issues know to communicate said issues to the VA 508 Office when they submit their audit request.
- [x] VFS teams know how to identify if an issue is an accessibility issue.

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by briandeconinck** [comment]
@allison0034 This should be ready for PR. I'm not super confident in the change I made to the staging review code block and would be interested in any suggestions. Teams shouldn't request a 508 Office audit until after the product is launched, which didn't fit super cleanly into the order of tasks. Tried to make it make sense, happy to try something different.

**Comment by allison0034** [comment]
@briandeconinck you put it as an item to check off in the list of things to do... I do not know if you can be more clear lol. Peer request done!

**Comment by briandeconinck** [comment]
Documentation updated, with Platform website changes pending. Will close when published!

**Comment by briandeconinck** [comment]
Platform website updates were published, closing this ticket.
