### ISSUE TITLE
[Application Hosting and Deployment] Overview and high-level workflow diagram

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47422]
## Description
Developers, operators, and stakeholders need information that gives an overview of the system and its major components. 

## Tasks
- [x] Provide a diagram that explains 
  - [x] the major components of the system
  - [x] high-level workflow for using the system

## Acceptance Criteria 

- [x] Diagram exists in Confluence that provides an overview of the system and workflow 
  -  [x] Form-based interface (GitHub issues)
  -  [x] Software repositories (GitHub; GitOps?)
  -  [x] CI/CD Tools (GitHub Actions, ArgoCD)
  -  [x] Container Registry (ECR)
  -  [x] Container orchestration (EKS)
  -  [x] Deployment Management (troubleshooting, etc)

**Comment by jhouse-solvd** [comment]
This diagram is coming together nicely. I'll tidy it up and request feedback to make sure it's useful. 
- [WIP in Confluence](https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+infrastructure+architecture+diagrams#Overview-and-high-level-workflow)
- [Lucid app template](https://lucid.app/lucidchart/9a0f24d4-2ecc-4b13-9031-c05b1893038f/edit?invitationId=inv_a1ff54e2-935a-4a09-b686-9200936e9aef&page=0_0#)

**Comment by jhouse-solvd** [comment]
This is a good first iteration. Feedback welcome!

**Comment by jhouse-solvd** [comment]
This is a good first iteration. Feedback welcome!
