### ISSUE TITLE
Certificate of Eligibility | Status uploader should support password-protected PDFs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#47436]
## Value Statement

**_As a_** Veteran
**_I want to_** be able to upload a password-protected PDF into the COE status app when it asks me to upload a missing document
**_So that_** the uploader doesn't appear to accept my password-protected PDF without asking me for a password

## Background Context

The COE form does allow the Veteran to upload password-protected PDFs, but the status app does not include this support. Jerek informed me that the backend is also missing a method to accept a password and unlock the PDF.

Note: File mime type & extension type checks are also missed

## Tasks

- [ ] Support password-protected PDFs in the COE status app
- [ ] Support password-protected PDFs in the backend `v0/coe/document_upload` endpoint
- [ ] Add tests

## Definition of done

- [ ] All tasks complete
- [ ] All tests passing

**Comment by tblackwe** [comment]
@fred-khoury-oddball Can you please take a look at this issue, determine if it is still relevant, and if so, size the effort to resolve?

**Comment by fred-khoury-oddball** [comment]
@tblackwe  i sure will on it now.

**Comment by tblackwe** [comment]
closing in favor of 52022
