### ISSUE TITLE
[FRONT-END] Transfer ALTOONA, PA "STORIES" from legacy web site to NEW Drupal pages [FE-ENGINEER]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4743]
## User Story or Problem Statement
As a Veteran Web user, I need to be able to review and read all the featured and historic stories listed for ALTOONA, PA website so I can review stories and events that impact my Veteran Journey.

## Goal
_Efficient and clear content describing local Internship and Fellowship Page?_

## Objectives or Key Results this is meant to further
* Content for VISN 4 websites has been loaded by April 3rd.
* All pages have been accounted for from legacy pages.

## Resources - Tools - Documentation
[Altoona legacy Stories Page](https://www.altoona.va.gov/features/index.asp)
[Required VAMC WebPage Listing and Drupal Example](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Completed transfer of story in order chronologically so they apear in order_
- [ ] Select two stories to be featured 1st and 2nd place_
- [ ] Select and upload images for each story so they fit standards of Drupal page_

## Acceptance Criteria
* All stories (Not to exceed last 24 months) have been transfered to NEW CMS for web system
* Pages are previewable and URL can be provided
* Images, one for each story, have been loaded and can be previewed correctly
