### ISSUE TITLE
[FE] Pass Users to Check-in when Access Pre-Check-in Link on Day of Appointment INSIDE Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47445]
## User Story
As a Veteran, when I click on my Pre-Check-in link on the **day of my appointment** and **INSIDE** the check-in window because I think that this is how I need to check-in, I would like to be allowed to check-in so that I don't have to figure out how to check-in by texting "check in" or scanning the QR code.

## User Flow
- Given I
    - Have a Pre-Check-in link that was sent to me and for which there is still a UUID in LoROTA
- When I
    - Click on my Pre-Check-in link on the **day of my appointment** and **INSIDE** the check-in window (i.e. up to 30 minutes before my appointment and no more than 15 minutes after my appointment)
- Then 
    - I am automatically taken to the Check-in application's identity verification page where I can enter my last name and DOB 

## Dependent CHIP Work
- Would need to a new endpoint to initiate a check-in w/o a text from the Veteran and give us back a new UUID so we can re-direct the user to Check-in with the new UUID

## Tasks
- [ ] Change the workflow to match the user flow above
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
