### ISSUE TITLE
[PM, Design] My VA Audit UX Improvements: Submit sitewide content/IA request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47453]
## Background
As part of the VSP Collaboration Cycle and development of the My VA audit improvements, we need to submit a [sitewide content review request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)

Guidance [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request).

## Tasks
- [x] Prep/gather artifacts
- [x] Submit [request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [x] Attend meeting if requested
- [x] Pending feedback from content, make any necessary updates to test cases and mockups

**Comment by ericasauv09** [comment]
Draft ticket created [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48155)

**Comment by ericasauv09** [comment]
Content/IA should have feedback for us by tomorrow afternoon
