### ISSUE TITLE
[FE] [BUG] Submission loop on DOB validation form

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#47464]
## To Reproduce

(reproduced on mac OS + google chrome)

- go to dob validation form
- enter a last name
- type a full date such as "01012020" into the month field
- press enter

The browser will continually resubmit the form and call the API.

Need to also test the scenario when user hits Enter button instead of clicking "Continue" button, sometimes that results in the loop happening even though the correct date was entered

## Tasks
- [ ] [FE] fix infinite resubmission
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
