### ISSUE TITLE
[FSR - PI3/23] Collaboration Cycle for [Benefits Team 2 - FSR- Enhancements]

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47462]
site## VFS product information

### VFS team name

Benefits Team 2

### Product name

Financial Status Report (FSR)

### Feature name

FSR Enhancements

### GitHub label for product

FSR

### GitHub label for feature

FSR Enhancements

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

FSR MVP launched on November 16, 2021. We are now enhancing and updating the experience. 

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/fsr_enhancements/product_outline.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [ ] User flow
- [ ] Research plan
- [x] Any other artifacts you have so far

- [Miro board with Option 1 & 2 mockups and user flow](https://miro.com/welcomeonboard/MlExdmU1blFYWXJHTERkbUUyb3g1OXdjcnNPNjk3WXI5clZwcVdHZndtejRhSzljSmh1Q2xQU1R5UVc0MUpSSHwzMDc0NDU3MzUzNTA5NjYxMTE1fDI=?share_link_id=420983226112)

- Option 1: Add Additional Living Expense with yes/no page
- Option 2: Add Additional Living Expense with button
 
(_[Experimental Design List Loop ticket for reference](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1187)_)
 
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: September 27 - 11:30am EST
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
  - [ ] Research has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/crLcdcz8ghvJ5WK7MWkRvS0peSaFuB3rf_OmF_ajB1rmwkzSlxyh9a4djBLILr_Z.hkc0DodByxBEXnnt)
  - Password: QyfA5.Sn
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/56447
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [x] Finalized design prototype or mockup - [Mural board with designs and user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?sender=ua78f969c4cddcbfe56b27885)
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth: 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): 

**IA artifacts**

- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [ ] Link to test cases/test plan in TestRail (draft OK): 
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: January 17 2023 at 11am EST

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [ ] Content has completed the review
  - [ ] QA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/rS5QrvuPdAtxt5KJwPzUhf7-Fgt6rB5SizEKDo4gMqWzhVt23VBK8VTGNhxUqBsd.zGWyXxg9dZL2EJpP
  - Password: H9#byuj*
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

Analytics Request code block

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- [x] Release plan with the "Planning" sections completed             Release plan template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md
https://github.com/department-of-veterans-affairs/va.gov-team/issues/59799https://github.com/department-of-veterans-affairs/va.gov-team/issues/59799
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59807

- [x] [Staging URL](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)
- [x] Specify which pages are included in the review: **All pages excluding Wizard and Review Page**
- [x] Staging test user information: **User 228** 
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable) https://github.com/department-of-veterans-affairs/va.gov-team/issues/56447
  
**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
Link here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/56447

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
Link here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/financial-status-report/tests/e2e
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
- [x] [Heuristic Analysis](https://docs.google.com/presentation/d/1CWREIS5t-8wPJaHIpQCKJNYn9jluuslE/edit#slide=id.p1)

  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
Link here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59390
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: **Friday, June 9 at 11:45AM Eastern**
- [x] [Slack thread with VFS team ](https://dsva.slack.com/archives/CBU0KDSB1/p1685986939761529)
- [ ] Create feedback tickets and link to this epic
  - [ ] Design feedback provided
  - [x] Accessibility feedback provided
  - [x] IA feedback provided
  - [x] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/VtzBCIVk9QUFi8cRxh_OrpWCT5nVGL1kqxqO-9kc1QiCVp6VTRgc1dBzjkppKHMo.2y9BpBQuLnj8G4lx)
  - Password: `@kyM+xk3`
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Communicate known accessibility issues to the VA 508 Office via Audit Request. (NONE - after the post release audit any new discoveries will be added as future work)
  - [ ] Share ServiceNow ticket number here: ______
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, as well as all post-Staging actions
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
link to PSIRR: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1033

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by HeatherRienks** [comment]
FYI

**Comment by josephrlee** [comment]
Here's a link to the Content Intake request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/56447

**Comment by HeatherRienks** [comment]
Here is a link to the E2E testing: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/financial-status-report/tests/e2e

**Comment by HeatherRienks** [comment]
@Tom-Davis -FYI

**Comment by Tom-Davis** [comment]
Thanks, following.

**Comment by Tom-Davis** [comment]
@HeatherRienks @denisecoveyduc closing as all items are now complete and accounted for.
