### ISSUE TITLE
Certificate of Eligibility | Improve status document upload UX

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#47469]
## Value Statement

**_As a_** screen reader user that needs to upload a document to the COE status page
**_We want the_**  upload experience to be straightforward and accessible
**_So that_** the instructions make sense and I don't get confused on next steps, or error messages

## Background Context

[Design document](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140741546/specification/sitemap)

The COE status app has some UX & a11y issues:
- Choosing a document type is _required_ before using "Upload your document"
  - if not done first, it allows the user to choose a file, but then shows an error
  - The error is shown above the button, when it should be shown above the select
  - This select really should be moved up into the gray box that appears after a file has been selected
- Submit files button is always visible, and in close proximity to the "Upload your document" button
- After "submit files" is used, the success message now includes the files that were just uploaded, this is missing in the design
- We direct the Veteran to read their notification letter to determine which documents need to be uploaded, but the design shows a list - was this not possible?

## Tasks

- [ ] Get UX review of this behavior
- [ ] Update design
- [ ] Determine if this upload functionality could be moved to a separate page?
- [ ] Fix a11y issues

## Definition of done

- [ ] All tasks complete

**Comment by sortizsh** [comment]
Not launch blocker, can go in future sprint.

**Comment by ohgreatkate** [comment]
synching with additional teams to ensure not creating duplicative or contradictory work. REF: https://sketch.com/s/b3237bfe-9e5c-4b5d-a958-66632d9a7fe3

**Comment by ohgreatkate** [comment]
iteration 3 had been reviewed by Josh Kim for accessibility and feedback was given by stake holders - should be our starting place to review feedback previously provided in Sketch file.

**Comment by fiorella-io** [comment]
Based on my talk with Kate:
-  The UXpin links in this ticket are the latest file
- the Sketch was started by someone and it is exploratory and has not been approved
- Eugene and Sade had worked on COE, possible contacts if we have any questions
- [ ] I can check stagging and see if some of these things have been fixed, if not
- [ ] I can create files to adjust the errors listed in this ticket


@steele-lm Since these accessibility issues were identified last year, should we request an accessibility maintenance audit to see if there are any new items that need to be addressed?

**Comment by fiorella-io** [comment]
After checking staging, the first bullet has been fixed. 
- You don't have to select the type of document first after you upload a document, then you select the type of document
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanNxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--176baa20fd773dd15238678e63f20c59dbde2eab/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBandxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f122bfa6a179219a9e952011033bb678df6fb77/image.png)

**Comment by fiorella-io** [comment]
I did get this weird error when I got logged out. I think we can fix the error messaging. It shouldn't be an inline error but a page error saying you've been logged out
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2NxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1dea40ffd61c67d66c63b7389293ee0602b6a99a/image.png)

**Comment by fiorella-io** [comment]
**Second bullet:** Submit files button is always visible and in close proximity to the "Upload your document" button
I don't see a "Submit file" button. There are "Back" and "Continue" buttons at the bottom of the page.

**Comment by fiorella-io** [comment]
It looks like my claim was approved 🫠. I'm going to need to request a stagging user whose COE claim was not approved and it needs more evidence.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEowIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ea2fa0b3efcf08909c78defd33edff945bcae57/image.png)

**Comment by fiorella-io** [comment]
A [request has been submitted](https://dsva.slack.com/archives/CBU0KDSB1/p1694036247374759) to get a staging user for this scenario.

**Comment by sortizsh** [comment]
we are still waiting on a test user to be created per comment above
