### ISSUE TITLE
Add Postgres Monitoring in Datadog

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#47463]
- [DD Amazon RDS](https://docs.datadoghq.com/integrations/amazon_rds)
- [Setting Up Database Monitoring for Amazon RDS managed Postgres](https://docs.datadoghq.com/database_monitoring/setup_postgres/rds/?tab=postgres10)

## Description

Create monitor for Postgres in Datadog

## Tasks
- [x] Identify all Postgres instance we want to metrics on
  - [x] dev
  - [x] dev-sample
  - [x] prod-2
  - [x] sandbox
  - [x] staging 
- [x] Create dashboard/monitor for instances

## Acceptance Criteria
- [x] Monitors are available to team & platform crew

**Comment by oseasmoran73** [comment]
Modifying information to pertain to vets-api. Found here https://vagov.ddog-gov.com/dashboard/qfr-rtt-hhu?tpl_var_env%5B0%5D=prod&tpl_var_env%5B1%5D=vagov-prod&from_ts=1665589532598&to_ts=1665593132598&live=true
