### ISSUE TITLE
[FE] [BUG] 4 digit year not required for DOB validation

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#47465]
## To Reproduce

(reproduced on mac OS + google chrome & mobile)

- go to dob validation form
- enter a last name
- enter the month and day
- press "Continue"

The browser will submit the form. This also works with 1, 2 and 3 digits in the year field, at least some of the time.

## Tasks
- [ ] [FE] a 4-digit year is always required to submit the form
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
