### ISSUE TITLE
FE | Profile | Military Info | Alert Updates

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47477]
## Background

We need to update 2 alerts in the Military Info section of the Profile. See #46149 if additional background is needed.

## Tasks
- [x] Show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/Pbl3eP/a/zxvZ4Le/r/nqJnRW) when we get a successful response from the API and user is not a Veteran
- [x] Show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/52vgV88) when we get a 403, regardless of Veteran status
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [x] Deploy to Staging behind feature flag

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Staging
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE] 
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by Samara-Strauss** [comment]
Removing @adamwhitlock1 as an assignee, though Adam may need to support John as-needed. I just didn't want this cluttering Adam's board since he has a full sprint already for sprint 84.

**Comment by SKasimow** [comment]
@jcatergovy - I set up a staging account as a non-veteran to test this scenario:

>- [ ] Show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/Pbl3eP/a/zxvZ4Le/r/nqJnRW) when we get a successful response from the API and user is not a Veteran

...but this is what I see:

![Screen Shot 2022-10-27 at 8 58 19 PM](https://user-images.githubusercontent.com/74627978/198426704-dc87e482-3be4-4d0c-bcf9-17ccd61877bd.png)

Let's touch base tomo; may be there is a  problem with the account I set-up?

**Comment by SKasimow** [comment]
Hi @jcatergovy - just need some small text changes circled below (should be "Monday through Friday" and "8am to 8pm

![Screen Shot 2022-10-28 at 9 00 43 PM](https://user-images.githubusercontent.com/74627978/199132043-977cc946-7a42-4823-876a-3e7b5198130b.png)

**Comment by SKasimow** [comment]
@jcatergovy @adamwhitlock1 - I can't verify the 2nd scenario:

> - Show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/52vgV88) when we get a 403, regardless of Veteran status

Can you trigger it on local machine and grab a screenshot?

**Comment by SKasimow** [comment]
Hi @jcatergovy - are you able to make the changes I noted above?
And question on how to verify scenario 2 (comment above)?

**Comment by jcatergovy** [comment]
@SKasimow fixed the grammar issue in the first modal mentioned above as well as one I just caught in the 403 error (screenshot here) ![NotInDeers.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/8873904f-2300-4d55-990f-9f857c8f251b)

**Comment by SKasimow** [comment]
Woot-woot! I'll re-test in a bit - just finishing something up

**Comment by SKasimow** [comment]
@jcatergovy  - still seeing the same text without corrections. Is it pending a PR merge? I am using vets10 if you want to look at staging.

**Comment by SKasimow** [comment]
@jcatergovy - the 403 alert looks good; just needs some minor tweaks as noted below:

- the heading of the alert show have a lowercase i: information 
- the phone numbers need a space the TTY should be in parens.

![Staging Alert with edits.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/8553bbd1-9592-4f56-90ca-281204b15df4)

**Comment by jcatergovy** [comment]
Fixed, let me know if anything else stands out @SKasimow 
![47477.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/93485e7e-9d5f-4fb2-aba2-43a9798a639f)

**Comment by SKasimow** [comment]
@jcatergovy - also, still need tweaks for the first scenario:

>for first scenario when we get a successful response from the API and user is not a Veteran we show [this alert](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/Pbl3eP/a/zxvZ4Le/r/nqJnRW) 

> Just need some small text changes circled below (should be "Monday through Friday" and "8:00 a.m. to 8:00 p.m. ET.")

![Staging alert](https://user-images.githubusercontent.com/74627978/199132091-aefa95a8-20bd-4935-a5b4-a254830057d5.png)

**Comment by jcatergovy** [comment]
@SKasimow Changes have been made and PR is out.  I'll let you know as soon as it's ready for testing in Staging.

**Comment by SKasimow** [comment]
@jcatergovy - should I re-test now?

**Comment by SKasimow** [comment]
ran into merge conflicts; have Adam review before overriding

**Comment by SKasimow** [comment]
@jcatergovy - for documentation purposes, can you send me the final screenshot for the 403 error? I had noted some changes on the last version I saw and just want to included the final version in this ticket. Thanks!

**Comment by Samara-Strauss** [comment]
If there have been copy changes, can you make sure they also make it into #49835? We are using the 403 error copy for the `NoServiceHistoryAlert`.

**Comment by SKasimow** [comment]
I'll add the link to the sketch file in #49835 as reference.
