### ISSUE TITLE
FE | Profile | Remove Feature Flags for Notifications

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47473]
## Background

We need to remove 2 old feature flags in all environments as they are no longer needed.

## Tasks
- Remove the FE code used for the feature flags below:
- [ ] `profile_notification_settings`features`
- [ ] `profile_show_receive_text_notifications `
- [ ] Remove the flag from local, staging, and prod environments using the Flipper UI
- [ ] Update/cleanup Cypress tests

## Acceptance Criteria
- [ ] confirm in feature toggle admin that these no longer appear

**Comment by SKasimow** [comment]
@adamwhitlock1 - Samara came across some old feature flags that should be removed. She provided me with the actual links to the FF doc but I don't have access to the doc; let me know if the info I put in the ticket is sufficient for you to know what to remove.

**Comment by SKasimow** [comment]
@adamwhitlock1 @jcatergovy I updated the tasks and AC; let me know if this works.

**Comment by Samara-Strauss** [comment]
Moving to sprint 85 to account for sprint 83 tickets rolling over into sprint 84.
