### ISSUE TITLE
[FE] My VA Payment info v2: Update text when there are no debts and copays or payments to show

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47470]
## Background
After looking at the content for when there are no debts or copays to show and when there are no benefit payments to show, we realized the copy is inconsistent.

## Tasks
- [x] When there are no debts or copays to show, update copy in the "Outstanding debts" section to read "You have no overpayment debts or copays to show."
- [x] When there are no benefit payments to show, update copy in the "Benefit payments" section to read "You have no recent payments to show."
- [x] PM or Design Validate Changes

## Acceptance Criteria
- [x] When user has no debts and no copays to show, copy reads "You have no overpayment debts or copays to show."
- [x] When user has no recent payments to show, copy reads "You have no recent payments to show."

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  PM or design
- _How can this work be validated?_  Log in with User 0 and ensure copy is updated per acceptance criteria

## Resources
**Current state:**
![Screen Shot 2022-09-23 at 4 03 40 PM](https://user-images.githubusercontent.com/45603961/192048376-ddf39853-a395-4a28-95e7-b1b4826e18b2.png)

**Desired state:**
![Screen Shot 2022-09-23 at 4 03 40 PM copy](https://user-images.githubusercontent.com/45603961/192049147-629a6c1e-7c6b-4d93-83d9-ab41f19a69cf.png)

**Comment by ericasauv09** [comment]
validated with user 0 ![Screen Shot 2022-09-27 at 10.21.35.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/adc5b731-c441-4178-afa7-dbc07b6746c2)
