### ISSUE TITLE
[UX] Update Design Artifacts for Release - Travel pay

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47488]
## Description
Update sketch wireframes so that they match what we are releasing and prepare them for merging to Abstract main and VA Sketch Cloud.

Create and update check in user flow that includes travel pay. Add to product guide for check in. 
- Update the appointment list with the new card design
- Update the confirmation page with the new card design

## Tasks
- [ ] Validate that final sketches match what we are pushing to production
     - [ ] Update sketches if they don't match but what we are pushing is correct
     - [ ] Notify FE if there was something missed and the sketches are correct
- [ ] Prepare Abstract collection so that it can be merged when we go to production

**Comment by loripusey** [comment]
@zach-park are all of the design artifacts ready for when we go to production?
cc: @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
I don't believe any work has started on updating the user flow diagrams for travel pay. Have they?

**Comment by benbrasso-agile6** [comment]
@loripusey we'll want to roll this ticket (mainly, user flow diagrams for product guides) and the product guides ticket (in progress + needs user flows + needs submit to contact center) over to next sprint

FYI @kellysmith1008 @zach-park 

UX team is meeting on thurs to discuss changes more

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 @loripusey , the travel pay version of user flows is ready for review:
https://share.goabstract.com/fe2f01a4-894d-4339-b4cc-cf5b902da20e?collectionLayerId&mode

**Comment by kellysmith1008** [comment]
Thanks, @zach-park! I'll add this to the travel pay documentation

**Comment by benbrasso-agile6** [comment]
I will plan to give the workflow a review today or tomorrow

**Comment by benbrasso-agile6** [comment]
@zach-park I think it looks great! One thing, @kellysmith1008, if it's too large to include in the product guide, then I would look to remove some of the content in the travel questions and content from the travel skip scenarios. 

Great work

**Comment by benbrasso-agile6** [comment]
I'm going to move this back into product backlog until this epic is ready for production release, which may be at least a few weeks from now

**Comment by zach-park** [comment]
Hey @kellysmith1008 , just curious, (since the user flows is very tall now as @benbrasso-agile6 mentioned) were you able to fit the user flows ok into the product guide? Please let me know if there's anything I can do. Thank you!

**Comment by kellysmith1008** [comment]
Hey @zach-park !
I was able to fit it all in just fine - thanks for verifying!

**Comment by benbrasso-agile6** [comment]
@loripusey I actually think we may need to update our travel wireframes to utilize the design updates from our VAOS work. We should think about how this change affects are timing of design testing, for example. Something to talk more about tomorrow. (Maybe I'm thinking about it backwards.)

**Comment by loripusey** [comment]
what design updates affect the travel pages themselves? I would think that when each feature gets merged to the main Abstract branch that the main branch would then reflect both features

**Comment by benbrasso-agile6** [comment]
Probably worth some discussion. 

But, for example, if we were to push the travel branch to master, the travel branch does not reflect the new appt design changes. ([Example](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=bbf2ae3b-a0fc-4ce5-a4bc-52c0fa60f0af&mode=design&sha=latest).)Therefore, the travel branch needs to be first updated in sketch and abstract. Again, I think we can use this ticket to do that, but it may be more work than we typically expect for this type of ticket.

I can kick it around during our ux team sync today.

**Comment by loripusey** [comment]
I think this depends on how the "merging" happens; I know how this merging happens from a code standpoint but I don't know how it is handled from an Abstract standpoint

**Comment by benbrasso-agile6** [comment]
Consensus was that this work would need to happen in sketch, and is not a simple "merge" via Abstract

**Comment by loripusey** [comment]
Can someone create the necessary tickets then? Or add the work to this ticket and increase the points as necessary?

**Comment by sarahknoppA6** [comment]
this needs updating with the new card design- also need to know about updating the user guide

**Comment by sarahknoppA6** [comment]
Zach and Ya-ching to sync on this ticket- will follow up at UX refinement tomorrow to discuss if any follow on tix are needed.

**Comment by loripusey** [comment]
@zach-park @ytsaoca are we going to finish this ticket this sprint?
cc @benbrasso-agile6 @sarahknoppA6

**Comment by ytsaoca** [comment]
@loripusey Yes. It will be finished.

**Comment by ytsaoca** [comment]
@benbrasso-agile6 @zach-park 
Mockups for review: https://share.goabstract.com/5cdc7c4a-53ea-4456-b4bc-1029fa03b055?collectionLayerId&mode

BTW, size of the artboards in the master and this travel pay branch are still the large version. I think it's better to prioritize that resize ticket or it will be hard to create/merge wireframes.

'cc @loripusey

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by loripusey** [comment]
closing as it seems this has been validated
