### ISSUE TITLE
Publicize the Q4 Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47493]
## Issue Description
Share survey's availability in Slack, ToT, and relevant group discussions every few days as needed to ensure participation.

# Make sure Content has updated Platform before linking to page

## Tasks
- [x] Share Survey in Slack
- [x] Add Survey announcement to ToT slide (and share)

## Acceptance Criteria
- [x] Survey posted in Slack
- [x] Survey posted in ToT slides for active period
- [x] Survey reminders are posted in Slack (all-teams, and practice channels)
- [x] Survey reminders are sent via DM to small groups
