### ISSUE TITLE
Launch Q4 Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47494]
## Issue Description
Launch Survey as directed on the [How-To](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey) page.

## Tasks
- [x] Launch Survey in Optimal Workshop
- [x] Update Platform Survey page in Confluence
- [x] Update Platform Survey site page

## Acceptance Criteria
- [x] Survey is [live](https://ows.io/qs/c17d4rwr)
- [x] Platform Survey site page is updated
- [x] Confluence Survey page is updated
