### ISSUE TITLE
Determine potential intake features (landing page, submission process) where teams can request our assistance for mapping.

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47499]
## Issue Description
Determine potential intake features (landing page, submission process) where teams can request our assistance for mapping.  

Possibilities:  This could be a form for submission, a page that explains how to kickoff a request, Google Form, etc

Here's an example from Platform Content:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2262794259/Request+Platform+website+content+support

Determine the necessary parameters/details a team would need to provide to make the request
[Here's a research intake form example from Taylor](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2417524758/Research+Intake+Document+DRAFT)

[Brainstorming document](https://vfs.atlassian.net/wiki/spaces/~622b5b63932f0f00716bdfd6/pages/2416869398/Mapping+intake+portal+brainstorming)

[Mural for process brainstorming](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666886472220/c097801ce764cd7e763461f50646f57f2e1c6f9d?sender=u4f7db1750f2355f805e60296)

[Brainstorming for features per phase of intake](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666717963461/d232a78b0b1304f152652d821f54172a76853172?sender=u4f7db1750f2355f805e60296)

## Tasks
- [x] Brainstorm potential intake portals and considerations
- [x] Draft the necessary parameters/details a team would need to provide to make the request

## Acceptance Criteria
- [x] Landing page(s) decided upon
- - [x] VA Platform/Support/Submit a mapping request
- - [x] SDT Confluence space
- [x] Intake tool/process decided upon
