### ISSUE TITLE
Determine and document location for maps

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47498]
## Issue Description
Determine and document where resultant maps should live 
-Should this reside in the [existing SB space](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2090074524/Customer+Journey+Maps+and+Service+Blueprints) w/i SDT's Confluence space?
-Should it be a more developed landing?

Who would need to know or access what, when? presumably Platform users and leadership.  Eventually possibly VFS team members.

## Tasks
- [x] [Evaluate user(s)](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666284387263/a00bc79670add9968206d55eed0ce3d0e40a7afa?sender=u9ea6bd3ca12795949b606150)
- [x] Determine optimal locations
- [x] Prepare location

## Acceptance Criteria
- [x] Location is prepared

**Comment by tayism** [comment]
Question to bring up to the team about showing current state maps: how do we know when a map is considered 'out of date'? How can we build this into our process for iterative work?
