### ISSUE TITLE
[FE] [TECH DEBT] Remove lodash dependency

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#47496]
## Background

We use lodash in one place in our app - right now it doesn't matter because the dependency is pulled in anyway. At such time as all vets-website apps have been migrated to workspaces, we should check if it's possible to remove the dependency and no longer include lodash in our bundle.

## Tasks
- [x] remove lodash dependency
- [ ] submit PR to remove lodash from global dependencies
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
