### ISSUE TITLE
Close Survey, Synthesize results and update Mural boards

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47492]
## Issue Description
Quarterly survey synthesis and update to mural boards

---
## Tasks
- [x] Close Survey
- [x] Update Platform site and Confluence Site
- [x] Prep synthesis Mural board
- [x] Schedule workshop for team synthesis
- [x] Synthesize survey

## Acceptance Criteria
- [x] Customer Insights Mural
