### ISSUE TITLE
Prepare the Mapping template in Mural

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47497]
## Issue Description
Establish the form of the template that will be used for mapping exercises.  This Template should align w/ the guide.

### The goal is to have a general template that can be used for the combined work of CJM and SB, possessing all desirable swim lanes and stages. 
Once a team becomes involved in a specific mapping effort, irrelevant items or unneeded lanes and stages can be removed/augmented.

### References
[Desirables ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1665517968025/7f0b6ae502331974299f47ba1ca6a24c63dc5c12?sender=u4397b715dc3690a417b71483)mural

PCT's highly fluid [SB](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1667572086605/baafb3f79f8f8cf074b784a3e3087517b84b4fdb?sender=u4397b715dc3690a417b71483)

Workshop [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666623990109/dba477fdf13b9e403ef4e67d39d246c973dd6b29?sender=u4397b715dc3690a417b71483)

Main swimlanes and SB [definitions](https://www.nngroup.com/articles/service-blueprints-definition/)

## Tasks
- [x] Prepare [template](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1668607683892/7508585ac527f963289ed64cf76220c20ede7e16?sender=u4397b715dc3690a417b71483) for Service Blueprint work
- [x] Refine w/ team input

## Acceptance Criteria
- [x] Map Template is created
- [x] Map Template has the desired swim lanes for highlighting Paint points, Potential improvements, etc
- [ ] Map Template allows for the steps specified in the "[guide](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/department-of-veterans-affairs/va.gov-team/44501)".

**Comment by steel36** [comment]
@gopixelsgo I removed the "blocker"; it appeared to be an incorrect Initiative association.
