### ISSUE TITLE
Design | Profile | Direct Deposit | Update Additional Info Component

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#47505]
## Background

Adam pointed out in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22263#issuecomment-1258236551) that the design for the additional info component in Direct Deposit differs slightly from how the component works visually:

- Blue line is now a darker shade in the web component / design system
- Blue line also extends to the bottom of the content, but in the design it is just extending alongside the check image.

**Staging/Prod:**
![Screen Shot 2022-09-26 at 9.23.43 AM.png](https://images.zenhubusercontent.com/61843a671a4b5e02e1517a62/08dbb191-435d-4666-95c4-153a56fa9e0b)

## Tasks
- [x] Update component in DD Sketch files 
- [x] Make sure all libraries are up-to-date in Sketch files

## Acceptance Criteria
- [x] DD Sketch files updated
- [x] All Sketch libraries updated

**Comment by andaleliz** [comment]
The sketch file has been updated, and I also updated the library. @cgednalske I'm assuming the library updates in the task refer to just the DD sketch file but lmk if I'm wrong. Thanks!
