### ISSUE TITLE
[SSL Certificates] Operational documentation for edge cases 

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#47508]
## Description

There are certain SSL's that are more complex than others. It would be nice to document these edge cases (if not all as it may be useful to keep track of historical context, as well as point of contact)

## Background/context 

With recent [PR](https://github.com/department-of-veterans-affairs/devops/pull/11987), it was a bit difficult to test than how normally it is done. Had to gather some historical context from [slack](https://dsva.slack.com/archives/CBU0KDSB1/p1595957489199300?thread_ts=1594051260.248200&cid=CBU0KDSB1)

---
## Tasks
- [x] Create centralize documentation for certs in confluence
  - [x] Provide certificate name/information
  - [x] Provide last known Point of Contact / Team information
  - [x] Notes (slack channels, PRs, how to test, etc.)

## Acceptance Criteria 
- [x] Infra/Ops know where to find documentation

**Comment by oseasmoran73** [comment]
Created couple pages under:

How do I > Manage SSL Certificates > [Cert_name]. Open to feedback on how we should structure

**Comment by jhouse-solvd** [comment]
I nested those docs [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2390622213/Details+for+certain+SSL+Certificates)

@jbritt1 - Would love for you to review the docs that Oseas created and close this out if it looks good.

**Comment by jbritt1** [comment]
Updated https://vfs.atlassian.net/wiki/spaces/OT/pages/2384265224/Renew+SSL+Certificate+for+vagov-mobile-app-api-server- last know PR link to one that included the additional setting in the vets-api configs https://github.com/department-of-veterans-affairs/devops/pull/12006

**Comment by jbritt1** [comment]
Reviewed the docs mentioned with one slight tweak. Rest looks great to me! I imagine we will start wanting to create more of these to track the ever-growing nuance(s) of some of these SSL certs. That may need to be its whole own epic though because we manage a ton of them... so for the scope of this particular issue I would consider it good to close.

**Comment by oseasmoran73** [comment]
A thought came to mind. @jhouse-solvd @ph-One is the expectation with the new re-org that the technical team will be in charge of updating certs?

**Comment by jhouse-solvd** [comment]
@oseasmoran73 I believe so. @ph-One - Can you clarify based on chats w/ Clint? 

"is the expectation with the new re-org that the technical-support team will be in charge of updating certs?"
