### ISSUE TITLE
Step through a test case

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47501]
## Issue Description
Try out our new mapping process on a test case of our choosing

## Tasks
- [ ] Step through the process as a team
- [ ] Note areas that are problematic

## Acceptance Criteria
- [ ] The experience of the walk through is documented with pain points captured

##  Pivot
We're going to use  actual upcoming mappings for iteration purposes instead of an invented test case
