### ISSUE TITLE
Publicize new offering

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47503]
## Issue Description
Decide if now is the right time, and if so, publicize mapping services

## Tasks
- [ ] publicize in ToT
- [ ] publicize in Demo

## Acceptance Criteria
- [ ] new offering has been publicized in ToT
- [ ] new offering has been publicized in Demo
