### ISSUE TITLE
[FE] My VA Audit UX Improvements: "Claims and appeals" Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47522]
## Background
This is the front end implementation ticket for the My VA "Claims and Appeals" section. Design prototypes and documentation to be added later. Additionally, because this will be the first FE ticket in this initiative, it will include work to create the feature flag for the entire feature.

[Claims and appeals frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md)

1. Update logic so section always displays for all LOA3 users regardless of whether the user has an open claim or not
2. If user has no open claim (or claim closed within 60 days), then display text "You have no claims or appeals to show"; also show secondary link "learn how to file a claim"
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#if-a-user-does-not-have-an-open-claim-or-appeal-or-a-claim-or-appeal-closed-in-the-last-60-days)
3. If a user has an open claim, then we show the claims detail card with the latest status update, also show secondary link "Manage all claims and appeals"
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#claims-and-appeals-status-card)
4. If a user has a closed claim within the last 60 days, we show the claims detail card; also show secondary link "Manage all claims and appeals"
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#manage-all-claims-and-appeals-link)
5. During the My VA audit we found that some text on staging does not match what is in Production. Under the Claims and Appeals section, staging has the language "Check your Claims and Appeals Status" it should say "Manage All Claims and Appeals."
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#manage-all-claims-and-appeals-link)

## Tasks
- [x] Copy old code/component to create new version
- [x] Create new feature flag for all My VA audit improvements
- [x] Implement changes to Claims and appeals section in new version
- [x] Test
- [x] Move ticket to validate 

## Acceptance Criteria
- [x] Implementation on staging matches Claims and appeals designs and FE documentation

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ compare designs and FE documentation to staging, validate data between open or recently closed claims to ensure current status and claims detail display

## Resources
- optional: links, screenshots, etc.

**Comment by tmitchellgcio** [comment]
Just deployed. Give this maybe 30 min or so to reach staging

**Comment by ericasauv09** [comment]
@tmitchellgcio is this feature on for all users in Staging? For a few users I am only seeing an error instead of the claims and appeals section and I don't see a Claims and Appeals section at all for user 10 - i thought all LOA3 users should see the section.

**Comment by ericasauv09** [comment]
Looks like the new changes don't match exactly with the sketch files - this is for user 15:
Sketch file ![Screen Shot 2022-10-24 at 14.37.37.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/22b228ca-5c13-4dcf-a6e0-64cd7d96b631)

Staging:
![Screen Shot 2022-10-24 at 14.36.24.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/92ca3c84-5e27-45df-b9d3-485921e835cb)

**Comment by ericasauv09** [comment]
validated #1 with multiple users 

validated #2 with user 41:![Screen Shot 2022-10-26 at 16.58.06.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/0b7ad665-acf1-47f1-b34d-3ac293e034d9) 

validated #3 with user 36: ![Screen Shot 2022-10-26 at 16.54.09.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/6ed3c303-ff50-4aaf-9093-ba703d7c59c7)

validated #4 with user 15:
![Screen Shot 2022-10-26 at 17.00.48.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/ddfbc9b9-bf5f-4fcb-b70b-52658de3bff8)

validated #5 with multiple users
