### ISSUE TITLE
Review published QA Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47529]
## User Story
As a new QA Specialist supporting the Governance team, I want to understand the current state of the Quality Assurance Standards so that I may be able to help define a plan for upholding them in the Collaboration Cycle.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
The QA Standards team published the QA Standards the week of 9/26/2022. The purpose of this ticket is to review the QA standards, develop an understanding of them and identify anything that may be concerning as Governance team defines a process for upholding the QA Standards in the Collaboration Cycle. Concerning things may include anything ambiguous or unclear, any gaps or missing information, any words or language that is not properly defined, any contradictions, any questions that arise, etc.

## Impacted Artifacts
[QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)

## Tasks
- [x] Review the QA Standards guidance on Platform Website
- [x] Document anything concerning (see definition in Description) below:
   - (insert list here)
- [x] Note: all documented items will be evaluated and prioritized in upcoming tickets. We will determine if these are problems we can resolve within the Governance team or if we will need support from the QA Standards team members.

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] QA Specialist has an understanding of the new QA Standards
- [x] We have a documented list of concerns to evaluate and prioritize

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by it-harrison** [comment]
Issues / Questions on QA Standards:

- Regression Test Plan, Test Plan, Unit Test Coverage, and Lighthouse Accessibility Rating areas use the word _must_ in their Description columns; however, none of these areas are required for product launch. Therefore, changing the word _must_ to _should_ is recommended to avoid confusion as to whether these elements are blockers for launching a new product.
- For all Areas except E2E Test Participation, how will the Remediation Plan be operationalized? When and how are the teams warned?
- For the E2E Test Participation area, the timing mentioned in the Remediation Plan is unclear; does the 30 days start at the Staging Review? Further, the text suggests that the team can release to production during this 30 day period even though they have no E2E tests. Is this right? Or should all launches be blocked?
- Several Areas mention that teams need to use TestRail but this has not a requirement previously.
- Why is there a discrepancy between Regression Test Plan and Test Plan areas with respect to the Violation Description text, i.e. which point in the Collab Cycle that the respective plan is checked for?
- The Description for the Traceability Reports area could be tightened up a bit - the Coverage for References bullet should not be split into two bullet points. Also, it would be nice to indicate precisely what the Co drage for References and Summary _are_, a report of some kind.

**Comment by shiragoodman** [comment]
Other concerns:

- Security Level: warning implies that Platform will continue to check for this QA standard, when (at this time) we will only be verifying at Staging Review
- Agree with @it-harrison 's concerns re: the Remediation Plan. Platform Governance will NOT be periodically checking in so this field should be modified
- Link to QA Product Dashboard guide should be removed as it points to Confluence
- [Frontend support dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/lighthouse-performance-report/) (used for validating the Lighthouse Accessibility rating) is not complete. Unsure if we should have this as a standard if it can't be used/applicable to all VA.gov products
- Review 'How to check for compliance and address remediation' for E2E test participation. Unsure if it makes sense for a non-techie (like me)
- The 'How to check for compliance and address remediation' for Regression Test Plan, Test Plan and Traceability Reports is very basic and 100% specific to TestRail. How do we validate if the VFS team does not use TestRail?
