### ISSUE TITLE
[FE] My VA Audit UX Improvements: "Saved applications" updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47520]
## Background
This is the front end implementation ticket for the My VA "Applications In Progress" section.

[Frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md)

1. LOA3: the section name "Apply for VA benefits" (H2) changes to to "Saved applications"
2. LOA3: Eliminate H3 title
3. LOA3: "what benefits does VA offer?" collapsible menu stays, moves directly beneath H2 "Saved applications" header
4. LOA1 users - no changes

## Tasks
- [x] Implement changes to "Saved applications" section in new version
- [x] Test
- [x] Move ticket to validate 

## Acceptance Criteria
- [ ] Implementation on staging matches "Saved applications" designs and FE documentation

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ compare designs and FE documentation to staging, validate all data instances where appropriate for accuracy

**Comment by ericasauv09** [comment]
Putting back to in progress to resolve issues mentioned in this [thread](https://dsva.slack.com/archives/C909ZG2BB/p1670009304508129)
1. There is an ">" missing after "Continue your application"
2. Copy for no applications state is incorrect, should be "you have no saved applications to show."
3. "Saved Applications" should be changed to "Saved applications", applications is not capped.

**Comment by ericasauv09** [comment]
Saw this with user 20 - spacing between the "What benefits does VA offer?" drop down and "You have no saved applications to show." text should be adjusted to match the sketch files: 
(Screenshot from Staging) https://files.slack.com/files-pri/T03FECE8V-F04DUC4C2N7/screen_shot_2022-12-05_at_15.29.29.png
( Sketch file) https://files.slack.com/files-pri/T03FECE8V-F04DUF9T78S/screen_shot_2022-12-05_at_15.29.47.png

**Comment by tmitchellgcio** [comment]
Looks like that's not possible. It's coming from the way va-additional-info works. Check the profile page and see the spacing underneath How to update your legal name and How to fix an error in your name or date of birth.
