### ISSUE TITLE
[FE] My VA Audit UX Improvements: "Explore VA benefits" updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47521]
## Background
This is the front end implementation ticket for the My VA "Explore VA benefits" section. Design prototypes and documentation to be added later. 

1. For LOA3 users, remove this section 

## Tasks
- [x] Implement changes to "Explore VA benefits" section in new version - remove from LOA3 state
- [x] Test
- [x] Move ticket to validate 

## Acceptance Criteria
- [x] "Explore VA benefits" section no longer appears for LOA3 users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ compare designs and FE documentation to staging

**Comment by ericasauv09** [comment]
validated with users 10,15 and 20: 
![Screen Shot 2022-12-02 at 14.20.01.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/28c14a14-4f1a-4537-b421-b9477d37b4ab)
