### ISSUE TITLE
[FE] My VA Audit UX Improvements: "Health care" Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47523]
## Background
This is the front end implementation ticket for the My VA "Healthcare" section.

[Frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md)

1. Update logic so section always displays for all LOA3 users regardless of whether they have healthcare through VA or not
2. For users who don't have healthcare through VA, display text that reads "You have no healthcare information to show"; secondary link immediately below the text for "Learn how to apply for VA healthcare"
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-does-not-have-va-health-care)
3. For users with healthcare through VA, appointment card displays any upcoming appointment regardless of time (i.e. removing 30 day limitation on "next appointment"); only shows soonest upcoming appointment.
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#next-appointment-card)
4. For users with healthcare through VA who don't have any upcoming appointments show text "you have no upcoming appointments to show", and a link to schedule and manage your appointments
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-has-va-health-care-but-does-not-have-any-upcoming-appointments-scheduled)
5. For users with healthcare through VA, the secondary link for "Get your VA medical records" needs to be updated to "Get your VA medical records and lab test results"
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#get-your-va-medical-records-and-lab-and-test-results-link)
6. For users with healthcare through VA, maintain existing logic for messaging
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-has-unread-messages-from-a-health-care-providers)
7. Section header should read "Health care" (not have a capital C like it currently does)

## Tasks
- [x] Implement changes to Health care section in new version
- [x] Test
- [x] Move ticket to validate 

## Acceptance Criteria
- [ ] Implementation on staging matches Health care designs and FE documentation

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ compare designs and FE documentation to staging, validate data between next appointment details and appointments in online scheduling to ensure data accuracy

**Comment by ajakabcin** [comment]
@tmitchellgcio @ericasauv09 @aagosto90  - I'm slotting this for next sprint (85), however if documentation is ready for this implementation and Taylor completes other FE work for sprint 84, this would be the next ticket to pick up in the Audit UX improvements FE work.

**Comment by tmitchellgcio** [comment]
Just pushed give it 30min to an hour to hit staging

**Comment by ericasauv09** [comment]
@tmitchellgcio I was validating this with user 41 in Staging and I saw that the message style does not match what is in the Sketch files:

Here's what's in the sketch file:
![Screen Shot 2022-11-03 at 16.31.56.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/34f7707a-bd0c-4dd9-9471-7608192d2889)

And here's what is showing for user 41:
![Screen Shot 2022-11-03 at 16.32.55.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/dec11b6c-2e00-406d-ad98-16dae2a5ec72)

Also @aagosto90 The sketch file that is linked in the FE documentation still says "view" instead of "review" so I'm not sure if that link is bad or needs to be updated?

**Comment by tmitchellgcio** [comment]
The notifications style hasn't changed yet. That's next sprint

**Comment by ericasauv09** [comment]
ahh yea forgot about that - thank you!

**Comment by ericasauv09** [comment]
1. Validated no healthcare scenario with user 10: ![Screen Shot 2022-11-08 at 10.03.18.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/0da40dcf-c523-4397-96fe-ec673ae8dc8e)

2. Validated user with an appointment with user Judy Morrison: ![Screen Shot 2022-11-08 at 10.05.35.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/4e9ef09c-bf17-4da9-83d3-90ea1937aa6f)

3. Validated no appointments or messages scenario with user 262: ![Screen Shot 2022-11-08 at 10.08.24.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/05aba895-7201-48fa-ac57-4ff43a8b0398)

4. Validated user who has messages with user 41: ![Screen Shot 2022-11-08 at 10.11.39.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/f5f20c00-ebce-4d0b-9935-35e140233b47)
