### ISSUE TITLE
Evaluate QA's role in the Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47534]
## User Story
As a Governance team member, I want to show how it has not been beneficial for QA to provide feedback at the Midpoint Review so that we can make a decision, with approval from OCTO, to remove QA from the Midpoint Review touchpoint.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
Now that QA's role in the Staging Review is to communicate to VFS teams how they are adhering to the QA Standards for VA.gov Platform, the role for QA at the Midpoint Review seems less critical. Historically, VFS teams have not yet begun to prepare their QA testing artifacts by the time the Midpoint Review takes place, so the QA on Governance team just ends up repeating themselves each review, telling the team that they'll be asked to uphold the QA Standards at Staging and points them to the QA guidance on Platform Website. It is obsolete and Governance team would like to request that QA no longer be a required attendee at the Midpoint Review. 

## Impacted Artifacts
N/A

## Tasks
- [x] Review feedback for the last 10 Midpoint Review's and document what feedback was communicated
   - ie we're trying to see how frequently we communicate the same message
   - @shiragoodman can help you find the last 10 MPR's if needed

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have made a case to remove QA from the Midpoint Review and presented the information to OCTO for approval

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket transitioned from initiative #47517 to #39845.

**Comment by it-harrison** [comment]
@shiragoodman here is a [draft of my findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2502852633/Review+of+recent+Midpoint+Review+QA+feedback).

**Comment by shiragoodman** [comment]
@it-harrison this is perfect. Thank you. I am going to close this out and create a ticket for escalating this issue.
