### ISSUE TITLE
Audit QA guidance on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47532]
## User Story
As a QA specialist supporting Governance team via the Collab Cycle, I want to be aware of any existing QA guidance relevant to supporting the QA Standards so that I can be sure to reference it when completing my reviews, and potentially point VFS teams to it when providing feedback.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
QA Standards team use to manage all QA guidance and documentation on Platform Website. The purpose of this ticket is to identify any guidance that may be helpful for VFS teams to be made aware of when going through the Collaboration Cycle, useful for the Governance team QA specialist in ensuring that the QA Standards are met at Staging review and identify anything outdated, irrelevant and/or incorrect QA guidance

## Impacted Artifacts
[Audit Log](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2453667860/47532+-+Audit+of+QA+artifacts)

## Tasks
- [x] Create an audit log in the Governance team Confluence space / Documentation Drafts. The audit log should include the following columns:

1. Title of guidance (with url link)
2. Current or out of date
3. Useful for the Governance team QA specialist in ensuring that the QA Standards are met at Staging review (yes or no)
4. Update, Archive or Leave As-is

- [x] Add every QA related page from Platform Website to a new row of the table
- [x] Populate columns 1-4. Column 5 will be completed later.
- [x] Once complete, follow the following guidance to populate column 5:

Scenario # | Column 2 | Column 3 | Column 4 | 
| -------- | -------- | -------- | -------- |
|a|current or out of date |no| archive|
|b|current| yes| leave as-is|
|c|out of date |yes |update |

- [x] For rows that fit scenario a, archive all pages. 
- [x] For rows that fit scenario b, no changes are needed to the guidance, however the page should be linked to from the _How to complete a QA review for Staging review touchpoint_ guidance, specifically the _Use VA approved reference Guides_ section
- [x] For rows that fit scenario c, create a backlog ticket using the Governance team template and link to it under Column 4. We will link this guidance to the _How to complete a QA review for Staging review touchpoint_ guidance in the newly created ticket.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All Platform Website QA guidance has been reviewed
- [x] We have identified guidance that will be helpful for Governance QA to complete the Staging Review
- [x] We have identified QA guidance in need of updates

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison What is the status of this? I see you moved to In Progress, but I don't see any updates in the Audit Log.

**Comment by it-harrison** [comment]
Hi @briandeconinck a [draft of the audit](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2453667860/47532+-+Audit+of+QA+artifacts) is now available.

**Comment by briandeconinck** [comment]
@it-harrison I've finished reviewing and agree with your assessment for each page. One quick note that it looks like Shira expected anything labeled as a "no" in Column 3 would be archived, but you're mostly leaving them as-is. But I think you're right to leave them, since they're useful for VFS teams even if they're not useful for you.

I think this looks good and can be closed out.

**Comment by shiragoodman** [comment]
Late to the party, but I'm also okay with the "no" docs not being archived (for now). We can address at a later date.
