### ISSUE TITLE
Create QA template for Staging Review and draft instructions for completing template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47536]
## User Story
As a Governance team member supporting QA in the Collaboration Cycle, I want to create a gh template for communicating to VFS teams at Staging Review if they have met or not met the QA Standards so they can address launch-blocking issues and modify their QA artifacts to meet the Platform QA standards.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
VFS teams (on 1/9/2023) will be asked to uphold the QA standards and will be evaluated on whether or not they've met those standards at the Collaboration Cycle Staging Review. Governance team needs a consistent, repeatable way of communicating adherence to the QA standards, and it should be in alignment with how the remaining Governance team members communicate adherence to the VA.gov Experience Standards - AKA a github issue template. 

Unlike the VA.gov Experience Standards, since there are only 5 QA standards, the new github issue template will include all 5 QA standards and will notify the VFS teams if they have met or not met each QA standard.

This ticket will also include creating/modifying operational guidance for the Governance QA to follow when completing the new template. 

## Requirements for the template

1. The template should include a link to the QA Standards on Platform Website
2. The template should reference all 5 QA Standards 
3. The template should include a unique GitHub label
4. The template should include the same "General Information" as the issue tickets for the VA.gov Experience Standards:
   - VFS team name
   - VFS product name
   - VFS feature name
   - Point of Contact/Reviewers (from Governance team)
5. The template should include some of the same labels as the issue tickets for the VA.gov Experience Standards:
   - `collab-cycle-feedback`
   - `QA`
   - `staging`
   - `launch-blocking` (if standard QA4 is not met)
   - VFS team name gh label
   - VFS product name gh label
6. The template should be linked as a child ticket to the Collab Cycle Request ticket for appropriate VFS team/VFS product/VFS feature
7. The template should include space for the Governance QA to indicate whether or not each standard was met or not met
8. The template should include "VFS Guidance" appropriate for QA. 
   - The guidance for the VA.gov Experience Standards tickets states:
```
VFS Guidance
- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.
```
9. **Should the template also include space for Governance QA to provide additional details? and/or a recommendation to the VFS team?**
10. **What else?**

## Impacted Artifacts
[How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint)

## Tasks
- [x] Create a draft gh template in your personal GH space that meets the above requirements
- [x] Share with Peer Reviewer for feedback
- [x] Share with Shira for feedback
- [x] Once template has been approved, work on updating the [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint) guidance.
   - Keep in mind that QA can document issues on the VFS process side (aligned with the QA standards) or the VFS product side (aligned with the VA.gov Experience standards). The operational guidance should reflect that and provide a process for our Governance QA to follow supporting both.
-  [x] Publish QA Github template to va.gov-team repo as an issue template

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has a template for communicating QA standards adherence to VFS teams at Staging Review
- [x] Governance team has modified guidance to follow when completing the QA standards review at Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@it-harrison Third bullet under VFS Guidance should read: Some feedback provided may be out of scope for your iteration of the product; however, Platform's OCTO leadership has stated that all identified issues need to be documented, and it is still your responsibility to resolve the issue.
Third bullet under VFS Guidance should read: If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. The Governance team will research and will follow up.

**Comment by it-harrison** [comment]
Hi @shiragoodman [the draft template](https://github.com/it-harrison/qa-template/issues/new/choose) is ready for you to take a look.

**Comment by shiragoodman** [comment]
@it-harrison here is my feedback:

1. I'm not sure I like the solution "Check the box if the standard is satisfied or not." I think that could get confusing. (Does the checked box mean I met the standard or didn't meet the standard?). Even though the instruction is clear, lets make it dummy proof. I would prefer to see each standard as it's own H3 heading, with the standard id in parentheses, then the following checkboxes below:
   - [ ] Standard has been met
   - [ ] Standard has not been met
2. Again, the sentences, "For each Standard Area below, check the corresponding box if the product satisfies the standard. If not, leave a note explaining why the requirements of the Standard Area have not been met." are a bit confusing. This is written from your perspective as QA for Governance team. However, the ticket is intended FOR the VFS team. This is a bit unclear... Are they leaving a note explaining why the requirements have not been met or are you? I know it's you, but it should be written for the VFS team, helping them understand how to interpret your ticket.
3. If you do want to provide instructions for yourself to follow, I'd recommend using the comment syntax, so it shows up in the Write/Edit mode, but not when it's published for the VFS team. `<!-- This is comment and won't be rendered! -->`
4. I'm unsure of the purpose of "Recommendation and additional information". If a standard is not met, I'd imagine you'd provide details below the standard, not in a separate section. I don't think this is necessary.
5. The steps in "VFS Guidance" are exactly what's in the VA.gov Experience Standards tickets. I'm not sure if this makes sense for QA. For example, "Close the ticket when the issue has been resolved or validated by your Product Owner" - this is talking singular issue when you could find violations in all 5. Can you update this guidance to what would be preferred actions for the VFS team? If you're not sure, let me know and we can discuss.
6. I'd really like to see 2 completed tickets for reference. 1 with all QA standards being met and 1 with none of the 5 QA issues being met. What would a completed ticket look like? I think that will help you understand how to write/modify your [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint) guidance. You can just use dummy data (VFS Team 123, VFS Product ABC, etc.)

Let me know if you'd like to discuss any of my feedback further.

**Comment by it-harrison** [comment]
Hi @CherylEvans I have updated the [issue template](https://github.com/it-harrison/qa-template/issues/new/choose) to take Shira's comments into account. Also, as per Shira's request, I created an example ticket [where all the QA standards are not met](https://github.com/it-harrison/qa-template/issues/1), and an example of a ticket [where all the QA standards are met](https://github.com/it-harrison/qa-template/issues/2). Thanks!

**Comment by CherylEvans** [comment]
@it-harrison Did you address Shira's concerns with #5 in her comments?  I see "Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards." is still in use.  
Other than that, it looks like you have answered all of the questions.

**Comment by it-harrison** [comment]
@shiragoodman have updated the [issue template](https://github.com/it-harrison/qa-template/issues/new/choose) to take Shira's comments into account. Also, I created an example ticket [where all QA standards are not met](https://github.com/it-harrison/qa-template/issues/1), and an example of a ticket [where the QA Standards are met] (https://github.com/it-harrison/qa-template/issues/2). I'm a little unsure of how to instruct VFS teams when to close the ticket (your point 5). I left it ambiguous because I didn't want to say "close when all standards have been met" since the teams are not required to meet all the standards.

**Comment by shiragoodman** [comment]
thanks @it-harrison.

Re: when to close the ticket, I like what you have. We can always change later on if needed.

I would remove the last 2 bullets under VFS Guidance. I can't imagine a situation where 1) your QA feedback would be out of scope for the VFS team or 2) anything documented NOT being the responsibility of the VFS team. I can't recall a single instance where VFS teams weren't responsible and accountable for their own QA.

1 minor request - please add a section break after the unit test coverage section, before the VFS Guidance.

I still need to review your 2 example tickets. I will get back to you soon.

**Comment by shiragoodman** [comment]
Ok here's my feedback on the example tickets, now that I've seen them in use:

- I'm not sure the bullet, "Explanation of failure to meet standard (if applicable)" with the input from you on the same line is very readable. I think I'd breeze right by it as all the text sort of blends. Maybe we could make "Explanation of failure to meet standard (if applicable)" and H5 (or even just bold) with your input on a new line below. I don't think it makes sense for it to be a bullet at all though.
- I don't think the current title works. When you use this template, it won't just be "qa feedback", it'll be you evaluating the VFS teams adherence to the QA standards. The ticket title should read, "QA Standards - VFS Team - VFS Product"
- on that same note, I'm not sure the `qa-collab-cycle-feedback` label is a good choice. Instead, lets use `QA-standards`
- We want to make sure the "Point of Contact/Reviewers" includes your name, your practice area and your gh handle. Just like how it's written on the VA.gov Exp Std tickets. This should be in your operational guidance.
- In example 1 where not all the QA standards are met, the E2E Test Participation is also not met, which is a launch blocker. In this scenario, we need to add the `launch-blocking` label. This should be in your operational guidance.
- Thank you for not adding the VFS team and VFS product labels in your examples (no need to flag those teams) but make your operational guidance includes adding those labels.
- Again thank you for not adding this to the Collab Cycle Request epic (not even sure if you could since this is still in your private repo) but we also want to make sure your operational guidance includes adding the QA feedback ticket as a child ticket to the epic.

**Comment by it-harrison** [comment]
Hi @CherylEvans I have updated the [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2448588875/Copy+of+How+to+complete+a+QA+review+for+Staging+review+touchpoint). Heads up: I am still struggling a bit with the "Use VA approved Reference Guides" section.

**Comment by shiragoodman** [comment]
@it-harrison - I think it is okay to leave the "Use VA approved Reference Guides" section blank or nonexistent for now. However, when you begin ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/47532, if there are any resources uncovered there that will help you complete your QA Staging review, then they should be added to that list. I am going to update the AC for ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/47532 to reflect this.

**Comment by it-harrison** [comment]
Hi @CherylEvans here are the final artifacts to meet the acceptance criteria:
* [new QA template in va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+QA-standards%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product)
* updated [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint)
Thanks!

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian.  I am done with my review.  Everything looks good.  I made some stylistic changes to [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint).  Feel free to publish. :-)
