### ISSUE TITLE
Launch QA standards within the Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47535]
Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
The QA Standards will be upheld in the Collaboration Cycle beginning 1/9/2023. The purpose of this ticket is to ensure Governance team has completed all required steps for rolling out the standards.

## Tasks
- [x] The QA Standards template has been moved to the va.gov-team repo
- [x] The Staging Review touchpoint page has been updated with the updated requested QA artifacts
- [x] All Collaboration Cycle request tickets in the Collaboration Cycle Reviews board have been updated to reflect the new Staging Review/QA artifacts (ie what is in the Staging Review code block)
- [x] The moderator script for Staging Review has been modified to reflect the new QA standards and how feedback will be received by the VFS team.
- [x] Change history post for 1/9/2023 has been drafted and approved by @shiragoodman 
- [x] Announcement made on Slack per [Platform Communications Playbook](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2165473911/Platform+Communications+Playbook)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The QA Standards are upheld in the Collaboration Cycle

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Hi @shiragoodman I drafted a [change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2471919624/Copy+of+Change+history+-+QA+Standards+Enforcement+Announcement) for this ticket.

**Comment by shiragoodman** [comment]
Thanks @it-harrison . I'll take a look and make changes. Since you're OOO this week, I will work with @briandeconinck to get the remaining tasks completed and this ticket closed out. I did add another task re: the moderator script. This should be launched and taken care of when you're back in the office next week!

**Comment by shiragoodman** [comment]
@briandeconinck will work on updating the moderator script for Staging Review.

**Comment by briandeconinck** [comment]
[Draft changes for the moderator script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2474607053/47535+-+Draft+QA+changes+to+moderator+script+for+Staging+Review), with a couple of comments to look at @shiragoodman.

**Comment by shiragoodman** [comment]
@briandeconinck I made some comments on the script. Please take a look and respond.

**Comment by shiragoodman** [comment]
@briandeconinck I made changes to[ Ian's change history post. ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2471919624/Copy+of+Change+history+-+QA+Standards+Enforcement+Announcement)Would you also take a look and let me know if you have any concerns? I mirrored some of the language from the script.

**Comment by briandeconinck** [comment]
@shiragoodman [Script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2474607053/47535+-+Draft+QA+changes+to+moderator+script+for+Staging+Review) updated per your comments.

Re: the confusing part at the end, that was actually all straight from what's currently on Platform website, unedited. I think I already had that tab open so I copy/pasted the script from there instead of finding it in the moderator instructions. Turns out they've drifted apart a bit.

Once you're good with the script I can update in both places and get them back in sync.

**Comment by briandeconinck** [comment]
@shiragoodman I think the change history post looks good. Everything seems clear to me.

**Comment by shiragoodman** [comment]
@briandeconinck the script looks great. Thank you for making the changes!

Would you be able to move forward with publishing the script and change history post by 3pm ET today? The date on the change history post should remain 1/9/2023. LMK if you have any questions.

**Comment by briandeconinck** [comment]
- [Staging Review moderator responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities) updated with new script
- [Staging Review touchpoint page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review) updated with new script, should be published to Platform website this afternoon
- [Change history page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1846870032/Change+history) updated with the announcement dated 1/9, should be published to Platform website this afternoon

@shiragoodman I think we're good to go!

**Comment by shiragoodman** [comment]
woo hoo! Thanks Brian. Can you also take care of closing this once all pages above are live on PW? Thank you!

**Comment by briandeconinck** [comment]
Pages are now live on Platform website! Closing this as complete.

**Comment by shiragoodman** [comment]
happy to see this closed, but sadly we'll have to reopen it :/ I added a new task to make the announcement via Slack on Monday 1/9. I will take care of this @briandeconinck

**Comment by shiragoodman** [comment]
Announcement for Slack:

Attention: VFS teams and everyone participating in Collaboration Cycle
**VA.gov Platform QA Standards are now being enforced in the Collaboration Cycle Staging Review.** 
Today, 1/9/2023, Governance team will be validating that all QA Standards are met when teams engage in the Collaboration Cycle Staging review. 
Impact:  All VFS teams preparing for Staging Review must present artifacts demonstrating that all QA Standards are met.

Documentation:  [Change history post from 1/9/2023](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history#Changehistory-January9,2023), [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review), [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)

Questions:  Please post any questions in thread or reach out to Governance team via #vfs-platform-support
