### ISSUE TITLE
[Datadog] Set up monitors and alerts for AWS services

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47541]
## Product Outline
[Monitoring using DataDog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Monitoring+using+DataDog)

## High-Level User Story/ies
As a VA.Gov Platform Operator, I need monitoring for AWS services to help maintain the availability of platform services _(and their dependencies)_. 

## Hypothesis or Bet
_Thoughts:_ Platform operators should be able to
- acknowledge issues more quickly 
- respond to issues with better information 
- address issues proactively 

_Note: Can we tighten these up and measure specific outcomes?_

## Tech notes
- Datadog: [Platform Monitors and Alerts dashboard](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts?from_ts=1665677627710&to_ts=1665681227710&live=true)

### What must be true in order for you to consider this epic complete? 

**Dashboards exist for the following AWS services:** 
- [x] Auto Scaling Groups (ASGs)
- [x] EC2 Instances
- [x] Elasticache
- [x] RDS
- [x] Storage

Note: Multiple services can be displayed on the same dashboard, _ie there does not need to be a dashboard for every service, but that service should be represented on a dashboard_. 

**Monitors exist for the following AWS services:** 
- [x] Auto Scaling Groups (ASGs)
- [x] EC2 Instances
- [x] Elasticache
- [x] RDS
- [x] Storage

**Alerts exist for the following AWS services:** 
- [x] Auto Scaling Groups (ASGs)
- [x] EC2 Instances
- [x] Elasticache
- [x] RDS
- [x] Storage

Note: Alerts should be routed to the appropriate channel/personnel based on the alert's severity.

**Comment by jhouse-solvd** [comment]
Kyle had a great idea to separate this epic: 
- Monitors w/ alerts sent to Slack
- Monitors w/ _critical_ alerts sent to PagerDuty

**Comment by jhouse-solvd** [comment]
@ph-One to create S3 issues (USE/RED) and attach them here
