### ISSUE TITLE
[Datadog] Set up monitors and alerts for Network Load Balancers

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47542]
## Product Outline
[Monitoring using DataDog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593917/Monitoring+using+DataDog)

## High-Level User Story/ies
As a VA.Gov Platform Operator, I need monitoring for Network components and services to help maintain the availability of platform services _(and their dependencies)_. 

## Hypothesis or Bet
_Thoughts:_ Platform operators should be able to
- acknowledge issues more quickly 
- respond to issues with better information 
- address issues proactively 

_Note: Can we tighten these up and measure specific outcomes?_

## Tech notes
- Datadog: [Platform Monitors and Alerts dashboard](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts?from_ts=1665677627710&to_ts=1665681227710&live=true)

### What must be true in order for you to consider this epic complete? 

**Dashboards exist for the following:** 
- [ ] Internal gateways
- [ ] External gateways
- [ ] Load balancers (ALB / ELB)
- [ ] Reverse Proxy (revproxy)
- [ ] Forward Proxy (fwdproxy)

Note: Multiple services can be displayed on the same dashboard, _ie there does not need to be a dashboard for every service, but that service should be represented on a dashboard_. 

**Monitors exist for the following:** 
- [ ] Internal gateways
- [ ] External gateways
- [ ] Load balancers (ALB / ELB)
- [ ] Reverse Proxy (revproxy)
- [ ] Forward Proxy (fwdproxy)

**Alerts exist for the following:** 
- [ ] Internal gateways
- [ ] External gateways
- [ ] Load balancers (ALB / ELB)
- [ ] Reverse Proxy (revproxy)
- [ ] Forward Proxy (fwdproxy)

Note: Alerts should be routed to the appropriate channel/personnel based on the alert's severity.

**Comment by jhouse-solvd** [comment]
Some synthetics were recently added to test TIC Gateway, see [here](https://github.com/department-of-veterans-affairs/devops/pull/12174). Those synthetics might help satisfy some of what we are looking to monitor as part of this epic.

**Comment by jhouse-solvd** [comment]
This epic is waiting on a few minor updates to #47980, identified during a recent review. 

Once that issue is closed, this epic can be closed as well.

**Comment by jhouse-solvd** [comment]
This epic is nearly complete. Ryan is making a few adjustments to #47980 based on team feedback. Once the team has had a chance to review, we will close this out.
