### ISSUE TITLE
[ANALYTICS] Create new "ALTOONA, PA" Health Services content "LIST & PLAYBOOK" [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4755]
## User Story or Problem Statement
As a Content writer and Business Analyst, I need to know the specific details regarding the Health Services Provided and Content requirements, so I can document and create the Health Services listing correctly.

## Goal
_Complete a content spreadsheet following using the Pittsburgh, PA pilot design tab as a reference source_

## Objectives or Key Results this is meant to further
- _Reduction in page count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[VISN_4_Content_Stack](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[VA.gov_Medical_Center_Map_Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)

## Tasks
_Complete written health services content playbook criteria for the following Health Services:_
- [ ] Validated listing of all Health Services provided in System
- [ ] Validated list of Health Services provided by Facilies in the System
- [ ] Content Playbook referencing all Health Services by Tab
- [ ] Final draft document is reviewed and submitted for product artifact in Github

## Acceptance Criteria

* Validated listing of all Health Services provided in System
* Validated list of Health Services provided by Facilies in the System
* Content Playbook referencing all Health Services by Tab
* Final draft document is reviewed and submitted for product artifact in Github
