### ISSUE TITLE
Enable SiS by default in staging and below

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#47565]
## Description
This body of work should ensure that the Sign in Service is enabled by default for the staging and below environments

## Tasks
- [x] Staging environment has `sign_in_service_enabled` enabled (On)
- [x] Dev environment has `sign_in_service_enabled` enabled (On) by default * see `config/features.yml`
- [x] Localhost follows the same environment setup as dev
