### ISSUE TITLE
Determine which service is being used to pull in IDES claims

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#47562]
## Issue Description
Kayla from Lighthouse said she received some more info from Michael Harlow regarding those IDES claims (EP 689). According to him, EVSS is actually not returning them anymore in their test environment, because they were already removed upstream. However, they do appear in staging on VA.gov, so it seems that the CST may be getting them from a different source. 

It seems like Benefits Team 1, Squad 1 will have to investigate which service is actually pulling in IDES claims.

---
## Tasks
- [x] Determine which service is being used to pull in IDES claims.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
I was able to pull the claim referenced in the email from Kayla up
User email: vets.gov.user+127@gmail.com
Claim details URL: https://staging.va.gov/track-claims/your-claims/600323190/status
