### ISSUE TITLE
Consider tracking of Insight data & making Recommendations

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#47563]
## Problem Statements
The SDT wants to know results shared from the Platform Survey are having being used.
If the results are being used, how might we measure what effect they're having on teams? Are teams making changes? If so, what are the outcomes?
The SDT would like to know if our presentation of results are easily comprehensible by recipient teams.
How can we make it easier for teams let SDT know what they do with the insights?

## Issue Description
How could we present insight data to make it trackable over time?  (The goal is to see if Insights are being acted on sufficiently)
How best to represent insights visually?  
Can synthesis result in identification of where insights should exist on a Platform Environment Map?
Do teams go back and look at results after the release? That is, does the survey have persistent utility?
This is likely to become more critical as OCTO reviews project to pursue

### Further, should we begin making more of a Recommendations output artifact, since many of these are no longer fixed teams that are consulting these insights?
The PO is interested in the SDT getting into the recommendations business for the Platform & even leadership.

[Previous work ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2066677817/Customer+Insight+Tracking+2021)in similar vein

**[Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1670611930463/77a5cde7076947728c2f4df2104c56c0910547c7?sender=u4f7db1750f2355f805e60296) for brainstorming and sense making**

## Tasks
- [x] Evaluate the questions above
- [x] Discuss preferred options w/ team

## Acceptance Criteria
- [x] Document decisions and action items
