### ISSUE TITLE
Conduct Stakeholder Interviews

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47572]
There is a need to understand stakeholder expectations through OCTO, Platform and VFS user groups.

---
## Tasks
- [x] Draft stakeholder interview questions and research plan
- [x] Recruit and schedule stakeholder interviews
- [x] Conduct stakeholder interviews and record notes
- [x] Document findings and recommendations

## Acceptance Criteria
- [x] Recommendations have been made based on stakeholder input

**Comment by pjhill** [comment]
Stakeholder Interview Guide draft has been created [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2396094503/Stakeholder+Interview+Guide).

**Comment by JoeTice** [comment]
Made update to the confluence page to provide more of the background and goals of this ticket

**Comment by pjhill** [comment]
Interviews are approximately 33% complete -- the remainder are being scheduled for this week.

**Comment by JoeTice** [comment]
User Research Interviews are now nearly 90% done, final interview is currently scheduled for Monday afternoon.

**Comment by JoeTice** [comment]
Last interview was conducted today - 10/25

**Comment by pjhill** [comment]
Interviews have been completed. Interview feedback is available [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2396094503/Preview+Environment+Stakeholder+Interview+Guide).

Interview feedback has been used to inform our understanding of the user flows defined in the [Define User Flows](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/47590) ticket.
