### ISSUE TITLE
Create RFC for new approach to Review Instances

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47575]
## Issue Description
We will document the planned approach to Review Instances based on the combination of our discovery, stakeholder input and research.

---
## Tasks
- [x] Draft RFC document & format
- [x] Conduct internal review w/ the team
- [x] Conduct review w/ Platform Engineering Lead
- [x] Publish the document and broadcast for comments

## Acceptance Criteria
- [x] RFC is posted and available for comments

**Comment by pjhill** [comment]
Collecting feedback from platform engineering lead

**Comment by pjhill** [comment]
PR created and #platform-architecture has been notified -- https://dsva.slack.com/archives/C0229UT3HSR/p1668803882388399

**Comment by pjhill** [comment]
Closing this ticket as the RFC has been created. We will resolve comments / issues under a separate ticket until the end of the comment period.
