### ISSUE TITLE
Research implementing Review Instances in EKS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47584]
## Issue Description
Review instances should no longer be hosted in the legacy BRD setup. We expect our new preview environment to be hosted in EKS. Additionally, we expect workflows generating the preview environments to be moved from Jenkins to more modern tools already at use on the Platform such as Tugboat or GitHub Actions.

---
## Tasks
- [x] Assess the methodology by which the review instances are created currently
- [x] Understand the capabilities available with EKS (by reading docs, etc.)
- [x] Sync up with former Infrastructure team to understand the current EKS landscape
- [x] Read and summarize prior work regarding EKS on the Platform
- [x] Create a plan to apply known Platform methods to create preview environments in EKS
- [x] Write up findings in a Confluence document in the Test Team 4 Discovery section.

## Acceptance Criteria
- [x] Relevant EKS capabilities have been enumerated
- [x] A plan to implement preview environments in EKS exists in Confluence

**Comment by rmtolmach** [comment]
Met with Kyle today. Added more findings to document ^^.

**Comment by rmtolmach** [comment]
Moving to "review" column.

**Comment by pjhill** [comment]
Thanks so much for this analysis. I think we have the groundwork to begin to define a more detailed proposed system architecture for our preview environment system. We may continue to have discussion and additional questions spurred by your document.
