### ISSUE TITLE
Establish Tracking of Success Metrics

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47581]
## Issue Description
In order to monitor whether the proposed solution is having the intended impact, we will want to establish baselines and methods to automatically track the identified success metrics. These baselines will need to be established based around the current system in place.

## To-do
Add list of success metrics that will be tracked as a result of this effort

---
## Tasks
- [x] Implement a new support bot category to track issues with review instances
- [x] Add tracking to keep account of how many review instances have been launched
- [x] Add tracking to capture users interacting with review instances
- [x] Implement tracking of errors with spinning up review instances

- [x] (STRETCH) Implement tracking on current system showing how often branches besides main are used from multiple sources.

## Acceptance Criteria
- [x] We have implemented tracking methods
- [x] We have baseline measurements for all success metrics
- [x] We have ongoing tracking methods active for success metrics

**Comment by CBonade** [comment]
Turns out, there was already a review instance support bot category! Topics are managed in this google sheet: https://docs.google.com/spreadsheets/u/1/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit?ts=609eca70#gid=0

**Comment by CBonade** [comment]
We've hit some speed bumps in implementing our tracking of success metrics. The best way we found to approach this would be to have Jenkins trigger a GitHub actions workflow, with an event payload showing the success or failure of launching a review instance along with some details of the instance itself. The GitHub action would then take the information from the Jenkins dispatch and use it to create a log entry that gets uploaded to BigQuery and stored. This would allow us to track all of the remaining above metrics.

The problem is, using the GitHub API to trigger a GHA workflow, requires a GitHub auth token. The token doesn't appear to be easily available for use in any obvious way and we're currently fairly limited on devops support so that area of this work is on hold for the time being until we come up with a devops support route.

I went past that and created the GHA workflow that will be able to upload the events and confirmed that this event makes it to BigQuery with all the appropriate information. All that's left to do is replace the hard-coded event info with the info that comes from Jenkins when we get that piece working.

**Comment by CBonade** [comment]
Numerous vets-website and qa-standards-dashboard-data PRs have already been merged in the process of getting this up and running. The devops PR to make this the default behavior for the review instances is now open and awaiting review here: https://github.com/department-of-veterans-affairs/devops/pull/12109

It remains to be seen as this runs and with review instances not currently running properly if these work exactly how we want them to. However, the one metric I am not sure we can track is capturing user interaction with the review instances. I'll revisit that one tomorrow to see. 

All of these data points are stored in `vsp-analytics-and-insights.vsp_testing_tools.review_instance_status_log` in BigQuery. We have everything we need (in theory) in each of these rows to satisfy the requests above aside from the one metric already discussed. You can visit the table here:  https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sreview_instance_status_log

**Comment by CBonade** [comment]
Usage metrics were able to be tracked by pulling the access logs from the EC2 instances themselves. Simply, if the log has anything in it at all, a user has accessed it. Otherwise, it's empty. This is done in the devops repository via a GitHub actions workflow that runs every 12 hours (11:30am, 11:30pm) and captures all active EC2 instances in a list. Then using that list of IDs, it fetches the access log for each and checks if they have contents. The array of IDs and Log Lengths is then passed to a script in our old QA Standards Dashboard Data repository, where a script stores it in BigQuery using our existing BigQuery mechanisms. This was the last metric that tracking was needed to be set up on.

**Comment by pjhill** [comment]
Nice -- data warehouse is filling up!
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/80e94dca-0652-453b-a02e-30d773ba5317)
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/499c212b-5d75-49d0-8534-ff6cf21a6158)

Given the tiny sample size we are at about 20% of review instances being accessed which is an interesting baseline metric.

Thanks for collecting all of this data. It's going to be incredibly valuable as we start working on our solution and when we are ready to release to users!
