### ISSUE TITLE
[ANALYTICS] Create new Health Services content "LIST & PLAYBOOK" for VISN 4 Medical Systems [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4758]
## VAMC - Product Outline
[VAMC-upgrade Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Story
As a Veteran Web User, I need clear, concise, and instructional language on all VISN 4 Medical System web sites,  so I quickly get to where I want, the data I require, and the support I need. 

## VAMC-Upgrade KPI met with this EPIC
_These tasks support the load of CONTENT from legacy to NEW web systems prior to Milestone date for VISN 4._

## Definition of Done 
- [ ] Validated list of all SYSTEM and FACILITY Health Services_
- [ ] Validated PLAYBOOK of Health Services Content requires listed by tab documented and archived for the following sites:_
* Altoona
* Butler
* Coatesville
* Erie
* Lebanon
* Philadelphia
* Wilkes-Barre
* Wilmington

- [ ] _Archived in Github and/or SharePoint for review by Product Lead and PAOs
