### ISSUE TITLE
Research how Review Instances could be outside of SOCKS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47585]
## Issue Description
For preview environments, there is a desire to be able to share links to those environments to a wider audience, which includes team members who are non-technical. Those team members have expressed frustration with navigating SOCKS access, so we would like to determine how preview environments could be done without SOCKS as a requirement, and identify what additional limitations would result from this change.

- What features/limitations exist in our current preview environment approach that includes SOCKS access?
- Identify which of those features/limitations would change if SOCKS were not part of the solution. (If multiple approaches might provide different options and have different strengths/weaknesses - constrain this to the 3 best options)

---
## Tasks
- [x] Generate a research document in the [Platform Tech Team 4 Confluence space](https://vfs.atlassian.net/wiki/spaces/TT4/overview)
- [x] Populate the document with research and potential approaches
- [x] Review research doc and review as a team to finalize recommended approaches

## Acceptance Criteria
- [x] We have documented the best options based on our research
- [x] We have recommended an optimal course of action for how to approach preview environments without SOCKS

**Comment by jbritt1** [comment]
Relevant ATO control around publicly accessible content: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/ATO/controls/AC/Readme.md

**Comment by jbritt1** [comment]
Currently, Review Instances are routed to via a bind/named configuration that lives specifically in the SOCKS proxy EC2 instance using a "vetsgov-internal" zone https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jumpbox/templates/vetsgov.named.conf.j2.

**Comment by jbritt1** [comment]
One _potential_ avenue for publicly accessible review instance URLs could be by leveraging the reverse proxy. A working example of that at this time would be the Pact Broker service. One can see here how that configuration works: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_website_server.conf.j2#L98-L116.

This allows a non-SOCKS-required route to reach the Pact Broker via https://dev.va.gov/_vfs/pact-broker

**Comment by rmtolmach** [comment]
> Relevant ATO control around publicly accessible content: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/ATO/controls/AC/Readme.md

Here's the relevant section:

### 18.0 Publicly Accessible Content
#### Publicly Accessible Content (AC-22.1)

18.1 Va.gov designates individuals authorized to post information onto a publicly accessible information system.

18.2 Va.gov trains authorized individuals to ensure that publicly accessible information does not contain nonpublic information.

18.3 Va.gov and the Communications team (which includes reps from VBA, VHA, NCA, OPIA, and Sec office) reviews the proposed content of publicly accessible information for non-public information prior to posting onto Va.gov.

18.4 Va.gov reviews the content on the publicly accessible organizational information system for non-public information at least quarterly.

18.5 Va.gov removes non-public information from the publicly accessible organizational information system, if discovered.

**Comment by rmtolmach** [comment]
Notes are in https://vfs.atlassian.net/wiki/spaces/TT4/pages/2391343120/Preview+Environments+outside+of+SOCKS

* We met with Jeremy today. Meeting with Faith tomorrow.

**Comment by rmtolmach** [comment]
Based on the research done by Jeremy and myself and conversations with the PM, team lead, and the ATO lead, and the write-up in confluence (link in previous comment☝️) , I am going to mark this ticket as closed.

**Comment by pjhill** [comment]
Thanks for the analysis! This is great, and the [Recommended Approach](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2391343120/Preview+Environments+outside+of+SOCKS#Recommended-approach) is a good summary.  I think this is about as far as this ticket can go, and it ticks off the two AC.

The proposed architecture that avoids SOCKS access requirements will be worked under a subsequent ticket.
