### ISSUE TITLE
Explore improvements to how Review Instances are updated

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47589]
## Issue Description
In order to assess the ability of review instances to respond as expected to changes, we need to understand how they are currently functioning under certain scenarios.
1. What happens when a user pushes a commit to a pull request that has generated a review instance?
1. What happens when a user pushes a commit to a branch that has generated a review instance?
1. What happens when a user runs the Jenkins task to deploy a specific `vets-api` branch to their review instance after it was already created?

---
## Tasks
- [x] Assess the current state of workflows when relevant code is changed
- [x] Brainstorm potential missing workflows to handle additional code changes
- [x] Define and diagram all scenarios for which preview environment updates should occur

## Acceptance Criteria
- [x] Workflows to handle deploying changes to preview environments given certain events have been defined in a Confluence document

**Comment by CBonade** [comment]
Evaluation of workflows has been completed and diagrams created of the existing workflows. Thoughts will be added to a confluence doc tomorrow.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2407137393/Current+and+Proposed+Review+Instance+Update+Scenarios

Thoughts in confluence doc linked here.

**Comment by pjhill** [comment]
Thanks for that write-up -- looking good! This should serve as a good reference for the baseline behaviors from current review instances. We may not re-create all the same behaviors in the new preview environment, but this is valuable information to have going forward.
