### ISSUE TITLE
Milestone 1 - Preview Environment (For WASA): Create & Document MVP

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47582]
## Update 2024
In Mid 2023, we shifted the approach and architecture that we were using on this effort, to make better use of the latest Infrastructure that was now available. As a result - the scope of this milestone shifted, and tasks/AC were adjusted accordingly. The scope of this milestone became to create a Preview Environment that could support a WASA scan, to begin navigating down that path.

## High Level User Story
As the Preview Environment development team and Platform/OCTO Leadership, we need to create a working MVP of Preview Environments so that we can get the necessary approvals for making Preview Environments public, we need to validate that it works properly, and makes things easier for teams by addressing the known pain points identified in the Project Ticket

---
## Tasks
- [x] Create a working MVP
~- [ ] Get approval for Preview Environments to live at a public location on the network~
~- [ ] Document the use, and support of Preview Environments~

## Acceptance Criteria
- [x] Preview Environment MVP is functional without any major issues
~- [ ] Necessary documentation exists and has been reviewed and finalized~
~- [ ] Usability sessions have been conducted and research properly recorded~
- [x] A research readout has been conducted
- [x] Results are logged in as tickets as appropriate for any MVP/Post-MVP Improvements
