### ISSUE TITLE
[Design] Profile 2.0: Settle on final design direction

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4759]
## User Story:

As a user, I need to be able to easily find and manage my personal information.

## Tasks

In Sprint 13, Tressa will take the initial design explorations from Sprint 12 and: 

- [x] Share proposal with larger design team, get feedback, and make updates
- [x] Share proposals with auth. exp. team, get feedback, and make updates
- [x] Work with Ryan on the navigation #4843
- [x] Settle on final design proposal 

## Acceptance Criteria:

- [x] There is a final design proposal for profile 2.0 for both desktop and mobile. 

All designs/states do NOT need to be done. These can be produced in Sprint 14.

**Comment by tressaellen** [comment]
Here are the mockups I've made so far - please let me know if you have any further feedback.


![Mobile 4.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f1444460-4acc-4054-9052-c9e8f2a1848e)![Mobile 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/82fb152e-0a8e-4a6e-966f-f967f6765f70)![Mobile 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/5c52498b-9d7e-4808-b24b-30d83ef5696e)![Mobile 3.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/c0f0182e-3be1-4e19-943d-8fb546d961fe)![Option 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/36f8143e-0c2a-4946-a2c9-15e41acfcf0d)![Option 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/db5b3db0-9507-4913-ac76-c1fd2ea237d5)![Option 3.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/07da6c24-db30-4b62-b342-dfa28a04837b)
