### ISSUE TITLE
Define User Flow for Using Review Instances

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#47590]
## Issue Description
We need to understand how users are currently engaging in the use of review instances. We will document and diagram each unique user flow.

- How does a user come to require the use of a review instance?
- How does a user start using a review instance?
- How does a user complete their responsibilities in a review instance?
- How does a user indicate they no longer need a review instance?

---
## Tasks
- [x] Discover all unique user flows currently supported by review instances
- [x] Generate a diagram for user flows based on the current approach to Review Instances
- [x] Publish the user flow diagrams to Confluence
- [x] Review approach w/ Platform Engineering Lead
- [x] Review approach w/ PO

## Acceptance Criteria
- [ ] All required user flows for preview environments has been defined and diagramed in a Confluence document

**Comment by JoeTice** [comment]
User flow diagrams are being documented [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666011911859/c0bf24d69db1638ccb56bf090acc1487ea9431c7?sender=uc4d00ea50beebdfad05a4846) - and will be published to Confluence when finished
