### ISSUE TITLE
[EPIC] MHV to VA.gov: Medications: UX Research and Discovery

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#47608]
## :star2: High Level User Story
As a UX lead, I need to understand the intersection of pharmacy and medical records, business rules, related legislation, key stakeholders, and existing issues that need to be resolved so I can document, synthesize and provide context and guidance to the delivery teams.

## :star2: Goals
Have a good understanding of the background, current state, future state, and who needs to be included when planning the VA.gov version of Pharmacy. as well as how these intersect with Medical Records

## :star2: Tasks
- [ ] Conduct interviews with internal stakeholders
- [ ] Document discovery findings
- [ ] Synthesize discovery findings
- [ ] Provide a read-out of key findings, recommendations to the Ad Hoc and ByLight MHV teams
