### ISSUE TITLE
GA4:  VFS FE Code - Testing

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47604]
## Issue Description
VFS  teams will be implementing the FE code for their custom events.  We will work with the teams to test those tags/triggers to ensure they are working as expected and we are not missing anything.

VFS Team:
- [ ] Benefits 2
- [ ] 

[GA4 events](https://docs.google.com/spreadsheets/d/1XDceQQVK6IGOl8R1OzhbncSc1Hrs37IEyQblW_Spk-Y/edit#gid=1403781092)

[GA4 Planning doc](https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=0)

---
## Tasks
- [ ] Frontend code is implemented (dependency)
- [ ] QA/validation against UA
- [ ] Confirm all components configured and tracking
- [ ] Make changes as applicable.

## Acceptance Criteria
- [ ] When all VFS teams code has been implemented and tested.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnny-jesensky-adhoc** [comment]
This epic was created for the first pass at the GA4 migration. We eventually handled custom events by having teams self-identify them through [this audit form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D).

 All submitted custom events have been implemented in GA4, under the Github label of _custom events_. Marking this as _**Done**_.

FYI @jestutt
