### ISSUE TITLE
Discovery: Vets-API from BRD to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#47627]
## Product Outline
Vets-API ([work in progress](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2409005202/Product+Outline+Vets-API))

## High Level User Story/ies
As a team focused on migrating VETS-API to EKS, I need a better understanding of 
a) what remains on BRD [moved to future sprint due to change in resources]
b) the confines of EKS (security)
c) any potential areas of process consolidation/standardization
so we can confidently proceed with the migration of VETS-API to EKS.

## Hypothesis or Bet
If we have a better understanding of what remains on BRD and the confines of EKS, we will be able to more appropriately plan the migration.

## OKR
Vets-API to EKS

## Definition of done
- [x] Conclusive list to present to Platform Leadership to answer: [What remains on BRD [scoped to vets-api server and worker]?](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)
- [x] Conclusive list to present to Platform Leadership to answer: [What are the security concerns with moving vets-api to EKS?](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)
- [x] Conclusive list to present to Platform Leadership to answer: [Where can we better standardize the migration process?](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
