### ISSUE TITLE
Logic for display of Community Care name 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4762]
## User Story:
As a Veteran, I need the facilities returned in search results to be accurately named so that I can find the location quickly and easily.

## Tasks
NOTE: This is not a new query and the data fields are already present. This issue is simply to reference a particular field ("ProviderType") and use it to inform the field which will be used for the Facility name to be displayed. 

- [x] Change logic in query for community care to reference "ProviderType" (found in second round trip, ProviderLocator)
- [x] On the backend, set the Facility name to "CareSite iIf "ProviderType" = "GroupPracticeOrAgency"
- [x] On the backend, set the Facility name to "ProviderName" if  "ProviderType"  "Individual.
- [x] Add round trip on Facility Detail page so this change is also reflected on the associated facility detail page.

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9c3f79ba-eb55-44c0-b583-aba33f13b481)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/779a2664-a1a9-470d-8927-b0c1a6087408)

## Example: 
As found below, "ProviderType" = "GroupPracticeOrAgency" so Facility name should be displayed as "Desert FootHills Dental"

`"@odata.context": "https://dws.ppms.va.gov/v1.0/$metadata#Collection(PpmsDataWebService.Models.ProviderLocatorResult)",

  "value": [

    {

      "Miles": 13.909,

      "Minutes": 22.667,

      "ProviderName": "DESERT FOOTHILLS DENTAL",

      "ProviderSpecialty": "Clinic/Center - Dental",

      "SpecialtyCode": "261QD0000X",

      "PreferredMeansReceivingReferralHSRM": false,

      "PreferredMeansReceivingReferralSecuredEmail": false,

      "PreferredMeansReceivingReferralMail": false,

      "PreferredMeansReceivingReferralDirectMessaging": false,

      "PreferredMeansReceivingReferralFax": false,

      "HPP": "Unknown",

      "CareSite": "Desert FootHills Dental",

      "CareSiteAddress": "1422 E. Chandler Blvd. Suite 110 Phoenix, AZ 85048",

      "CareSiteAddressStreet": "1422 E. Chandler Blvd. Suite 110",

      "CareSiteAddressCity": "Phoenix",

      "CareSiteAddressState": "AZ",

      "CareSiteAddressZipCode": "85048",

      "CareSitePhoneNumber": "(480) 460-1911",

      "WorkHours": null,

      "ProviderGender": "NotSpecified",

      "ProviderNetwork": "Veteran Care Agreement",

      "NetworkId": null,

      "ProviderAcceptingNewPatients": false,

      "ProviderPrimaryCare": false,

      "QualityRanking": null,

      "ProviderIdentifier": "1356811772",

      "Latitude": 33.3054645459,

      "Longitude": -112.0533827974

    }`
`  "@odata.context": "https://dws.ppms.va.gov/v1.0/$metadata#Providers",

  "value": [

    {

      "ProviderIdentifier": 1356811772,

      "ProviderIdentifierType": "Npi",

      "Name": "DESERT FOOTHILLS DENTAL",

      "ProviderType": "GroupPracticeOrAgency", ...
`

## Acceptance Criteria:
 - [x] When Facility Type = "Non-VA health", "Urgent care" or "In-VA-network urgent care pharmacies" and "ProviderType" = "GroupPracticeOrAgency", then the Facility name displayed in search results should be value found in "CareSite"
 - [x] When Facility Type = "Non-VA health", "Urgent care" or "In-VA-network urgent care pharmacies" and "ProviderType" = "GroupPracticeOrAgency", then the Facility name displayed on the associated Facility Detail page should be value found in "CareSite"
 - [x] When Facility Type = "Non-VA health", "Urgent care" or "In-VA-network urgent care pharmacies" and "ProviderType" = "Individual", then the Facility name displayed in search results should be value found in "ProviderName" 
 - [x] When Facility Type = "Non-VA health", "Urgent care" or "In-VA-network urgent care pharmacies" and "ProviderType" = "Individual", then the Facility name displayed on the associated Facility Detail page should be value found in "ProviderName"

    

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
