### ISSUE TITLE
Profile Team | Sprint 84 | Oct 5 - 18

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47647]
## PTO/OOO/Unavailable

- **Adam**: Oct 6 + 10
- **Christina**:  Oct 5 + 6
- **Sharon**:  Oct 10
- **Tom**:  Oct 10
- **Samara**:  Oct 10
- **Liz**:  
- **Erica**:
- **John** Oct 11

**Note:** Oct 10 - Columbus Holiday

## Sprint Priorities
- BAI Release
- Accessibility work
- Finish documentation

---
#### PM - Sharon
- [x] #47032 Launch Readiness Go/No Go

#### FE - Adam
- [x] #44758 Release to 25%* (1 pt)
- [x] #44760 Release to 50%* (1 pt)

#### Design - Christina
- [x] #47350 Update MPI error alerts (2 pts) (moving to Sprint 85)
- [x] #46918 Connected apps (3 pts)

#### FE - Adam
- [x]  #46282 Documentation for DD (2 pts)
- [x] #46323 Documentation for Military Info (1 pt)

#### Design - Christina
- [x] #47266 Nametag discovery work (defect-3) (Moving to Sprint 85)

#### Design - Liz
- [x] #47381 Complete Synthesis & Deliver Final Report (8 pts)
- [x] #47646 Post-research (3 pts)

#### FE - Adam
- [x] #46731 Multiple validation errors are not read out to screen-readers (defect-1) (5 pts)
- [ ] #47003 New modal (related to #46614) (2 pts) - (awaiting accessibility validation)

#### BE - Tom
- [x] #40762 Remove eMIS code (2 pts)
- [x] #46744 Add "Service Academy" dates (3 pts)
- [x] #47929 Military Service History | Identify all fields (2 pts)

#### PM - Sharon
- [x] #43481 Fraud alerts (research and clarify ticket)

#### FE - Adam
- [x] #31403 Update alert for identity verification (2 pts)
- [x] #31408 Alert update (button colors) (1 pt)

#### FE - John
- [x] #30051 Update direct deposit edit button style (1 pt)
- [x] #46150 Alert - add blue border (1 pt)
- [x] #46935 Update  Modal (Are you sure?) (1 pt)

#### BE - Tom
- [x] #47651 BGS caching (2 pts)
- [x] #47331 Doc for moving Github files (2 pts)
- [x] #48192 Database Queries (1 pt)
#### Design - Liz
- [x] #47755 Update Alert Style for Home Phone
