### ISSUE TITLE
Update R&S page for school closures due to natural disaster

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#47657]
## Issue Description
Stakeholder Tammy asked us to update the [What if my school closes due to a natural disaster?](https://www.va.gov/resources/what-if-my-school-closes-temporarily-because-of-a-natural-disaster/) R&S page. They provided a Word doc with updates in a table, but we'll find a way to update without using a table. 

[https://app.zenhub.com/files/133843125/be6d1635-0f95-4ded-ac33-58711d4a5c43/download](https://app.zenhub.com/files/133843125/be6d1635-0f95-4ded-ac33-58711d4a5c43/download)

---
## Tasks
- [x] Update Drupal page (Katherine)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Send to stakeholders Tammy, Terry, Ricardo in email chain (Laura)
- [x] Prepub & publish (Megan)

## Acceptance Criteria
- [x] Updates to R&S article are live

**Comment by laurwill** [comment]
Hi @katherine-fung , if you have time to work on this today, that would be great! The character limit on single Q&As will be a limiting factor here — see if you can work within the template, and if not we can discuss.

Here are some bulleted talking points from stakeholders, in case these have helpful info not in the Word doc table: 
- If your school is, or was, temporarily closed due to a natural disaster, you’ll continue to get your education benefit payments through the end of the current term or for up to 4 weeks, whichever comes first
- Students using Chapter 33 (Post-9/11 GI Bill)  should continue to verify their enrollment as if the school did not close, doing this will ensure that benefits are not affected.
- Students Using Chapter 30 or 1606 (Montgomery GI Bill) should continue to verify their attendance  as if the school did not close, doing this will ensure that benefits are not affected. Students may verify their attendance, using the [WAVE website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gibill.va.gov%2Fwave&data=05%7C01%7C%7C0710f54935584f3f3ba308da9ca4c161%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637994528673148092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wKR7rd3e8DIopiHwGhjltYSusf%2BiEQz9IpAFaVOq%2BKU%3D&reserved=0) or by calling 1-877-823-2378.
- Students using Chapter 35 (Survivors and Dependents Educational Assistance Program):  No further action is necessary to continue to receive benefits.
- If your school remains open, but you are unable to attend (i.e., if you had to relocate as a result of the natural disaster), VA is unable to continue GI Bill benefit payments. When you are no longer pursuing classes, your school must report the termination to VA as soon as possible.
- Please contact our Education Call Center at 1-888-442-4551 (Mon. – Fri., 7 a.m. to 6 p.m. CST) for any questions about your GI Bill benefits. If you’re unable to contact us by phone, you can send us a secure inquiry through [Ask VA](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fask.va.gov%2F&data=05%7C01%7C%7C0710f54935584f3f3ba308da9ca4c161%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637994528673148092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3wWG07Q1DivCd7NDCFtuv2yQUA2KY%2Bp5jRrt9q8twDc%3D&reserved=0).

**Comment by katherine-fung** [comment]
Hi @laurwill - I added the update about having to verify your enrollment in the Post-9/11 GI Bill to the page. 

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=14968 

-Due the character limit, I put the "How to verify enrollment" info for the Post-9/11 GI Bill and the MGIB in the "Related links" section. 

I tried to put this info in the body of the Q&A and take out the contact info from the body instead - see screenshot. (the contact info is already at the bottom of the page in the "Need help?" section), but I ran into trouble with the character limit. I still wonder if the how to verify information should be prioritized in the body. 

![natural disasters alt.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/375e1cfb-8710-4936-b38c-f57a77e54aa4 )

- there are 2 sentence fragments in the body, followed by colons. Could we leave these as exceptions to our usual rule of having full sentences due to the character limit?

**Comment by katherine-fung** [comment]
Update: I took the approach of putting the "how to verify" info in the body - http://preview-prod.vfs.va.gov/preview?nodeId=14968

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I agree that we want the verify enrollment links in the body, since those are key next steps. I did some editing to try to fit that and the contact info into the character count — see what you think of these updates. I went back and forth between bolding the "take these steps" intro vs. bolding the beginning of each bullet. I think this is more helpful, but let me know if you disagree.
http://preview-prod.vfs.va.gov/preview?nodeId=14968

If this looks good to you, could you throw aria labels on the phone numbers/TTY and pass to Megan for a copyedit? Thank you!

**Comment by katherine-fung** [comment]
Thanks @laurwill! 

@megzehn - this is ready for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=14968

Since there was one instance of 711 in the copy, I didn't repeat on another phone number 4 lines down. If that's not right, please let me know. 

Thanks!

**Comment by megzehn** [comment]
Hi @katherine-fung - this looks good to me. 

Noting in the ticket that we struggled to fit in the hours for the phone number, so we left that off. 

CC @RLHecht

**Comment by laurwill** [comment]
Thanks @katherine-fung and @megzehn ! I see you were able to fit in the hours after all — I just made one more tiny tweak so that the Ask VA link was closer to the "contact us online" option in that last paragraph. 

I've sent this to stakeholders for review.

**Comment by laurwill** [comment]
Hey @katherine-fung ,
Stakeholders have 1 more piece of info for us to fit into this page: Chap 35, DEA, recipients attending a Non-College Degree, of NCD, program is required to verify monthly with either the ECC or by submitting VA Form 22-8979 -[http://www.vba.va.gov/pubs/forms/VBA-22-8979-ARE.pdf](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.vba.va.gov%2Fpubs%2Fforms%2FVBA-22-8979-ARE.pdf&data=05%7C01%7C%7C480bcd5f38674c01661108daa6455e1a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638005114109575682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oP%2B%2FNtwydZTdzFqM1B6koI781%2Fh4tnUBc474Z3ilPlA%3D&reserved=0) DEA recipients attending Institutions of Higher Learning, or IHLs, are not required to do this process.

Could you:
- Remove the general contact info at the bottom of the article entirely to free up character count (I ran this by Beth, and while it's not ideal, we can do this when we really need the characters)
- Adjust the DEA bullet or add a second bullet to capture the new info
- See if that form is in the VA form library and link there if so

Thank you!

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=14968 

I made some other tweaks to get more characters 
(in first bulleted list:
took out "your" in "your payments," took out "will" in "payments will..." 
in second bulleted list: 
took out "continue to" in "continue to verify...") 

I added a new bullet for DEA participants who need to verify. I got the ECC phone number from this page: https://www.va.gov/resources/gi-bill-wave-faqs/ 

I went back and forth between referring to the DEA participants who don't need to verify as: 
"all other DEA participants" and "DEA participants enrolled in college degree programs."

For the first option, I figure all DEA participants have to fall in one camp of needing to verify or the other (though we would confirm with stakeholder). Character-wise, it's also shorter than saying DEA participants in college degree programs. 

But I also find the idea of a "non-college degree program" confusing, so I wonder if the second option helps people understand that a little more clearly. This infographic sort of explains the difference: https://benefits.va.gov/gibill/docs/isaksonroe/1010_ncd_vs_IHL_infographic.pdf

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's the preview: http://preview-prod.vfs.va.gov/preview?nodeId=14968 

I made some other tweaks to get more characters 
(in first bulleted list:
took out "your" in "your payments," took out "will" in "payments will..." 
in second bulleted list: 
took out "continue to" in "continue to verify...") 

I added a new bullet for DEA participants who need to verify. I got the ECC phone number from this page: https://www.va.gov/resources/gi-bill-wave-faqs/ 

I went back and forth between referring to the DEA participants who don't need to verify as: 
"all other DEA participants" and "DEA participants enrolled in college degree programs."

For the first option, I figure all DEA participants have to fall in one camp of needing to verify or the other (though we would confirm with stakeholder). Character-wise, it's also shorter than saying DEA participants in college degree programs. 

But I also find the idea of a "non-college degree program" confusing, so I wonder if the second option helps people understand that a little more clearly. This infographic sort of explains the difference: https://benefits.va.gov/gibill/docs/isaksonroe/1010_ncd_vs_IHL_infographic.pdf

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I agree that specifying college degree and non-college degree is clearer.
I adjusted to free up some characters so we could get back some of the words we cut — I think it was starting to sound a little choppy. I removed "participants" and put the "continue to verify enrollment" piece in the list intro instead of the bullets. 

Want to take a look and see if you think this update works? http://preview-prod.vfs.va.gov/preview?nodeId=14968

**Comment by katherine-fung** [comment]
Thanks @laurwill! These changes look great.

**Comment by laurwill** [comment]
Great! I sent back to Terry for approval.

**Comment by laurwill** [comment]
Approved! @megzehn this is ready for a final copyedit and publishing — this can happen tomorrow if you have more urgent edits going today.

**Comment by RLHecht** [comment]
This is live. Closing ticket!
