### ISSUE TITLE
Update Collaboration Cycle guidance for IA and Research

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47655]
## User Story
As an IA support person for Sitewide crew, I want to be included in the Collaboration Cycle touchpoints so that I may provide IA support and guidance to VFS teams.

As a Governance team member, I want to make sure Collaboration Cycle guidance includes the names of the people I'll be working with so that I know who I'll be receiving support from.

Assignee: @allison0034 
Peer Reviewer: @jimuhh 

## Description
Mikki Northuis (@mnorthuis ) is the OCTO IA Lead and has been asked to be included in the Collaboration Cycle process. Her backfill, Joni Chan, will also need to be included.

The purpose of this ticket is to add Mikki and Joni to the appropriate Collaboration Cycle touchpoints, update Operational guidance (if needed) to reference Mikki as the OCTO IA lead, and update any VFS-facing guidance on Platform Website to reference Mikki as the OCTO IA lead.

In addition, since the departure of the Governance team UX Researcher, the Research Review touchpoint is now managed 100% by OCTO Research lead, Shane Strassberg. The Contact Us page will need to be updated to reflect that his team (team name?) supports the Collaboration Cycle. 

## Impacted Artifacts
[Contact us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
Design Intent distribution list
Midpoint Review distribution list

## Tasks
- [x] Add Joni and Mikki to the Design Intent distribution list
- [x] Add Joni and Mikki to the Midpoint Review distribution list
- [x] Check with Mikki to see how she would like her role defined on the Contact us page
- [x] Check with Shane to see how he would like his role defined on the Contact us page
   -  Shira's 2 cents: Since both Shane and Mikki are OCTO practice area leads without a team, maybe it would just make sense to add a new heading to the page where we list ALL OCTO practice area leads. Include Martha, Matt, Beth, and Danielle as well.  "OCTO practice area leads supporting the Collaboration Cycle". It might make sense to then change the SWC leads from Beth and Danielle to Randi since she is the PM.

- [x] Share updated Contact Us design with OCTO leads for their review/approval via #platform-collaboration-cycle channel on Slack

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] Sitewide crew IA support are included in the Collaboration Cycle
- [x] VFS teams know who supports the Collaboration Cycle

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [x] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by mnorthuis** [comment]
FYSA @heyjoni

**Comment by mnorthuis** [comment]
@shiragoodman Agree with your approach above and confirmed with Beth and Danielle.  Here is who should be listed under the Sitewide Content and IA section:

Project manager: Randi Hecht
Managing editor: Laura Willwerth
Information Architect (IA): Joni Chan

Beth, Danielle, and myself (and other OCTO leads) can be listed under the OCTO leads section.

**Comment by allison0034** [comment]
@jimuhh this is ready for a peer review. You can see the changes on the [copy contact us page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2391048193/Copy+of+Contact+us) and once you approve I will move to production. You can check the emails by using the group emails in an email.

**Comment by jimuhh** [comment]
Hi @allison0034 Sounds good. i'm waiting to board return flight at Orlando but will look into it tomorrow AM.

**Comment by jimuhh** [comment]
Looks good @allison0034!

**Comment by allison0034** [comment]
@shiragoodman before I publish to platform website, should I replace Jim's name with Sara Sterkenburg?

**Comment by shiragoodman** [comment]
@allison0034 not yet. We'll have to update again in a couple weeks when Jim departs
