### ISSUE TITLE
Create R&S page for O*NET Interest Profiler

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#47658]
## Issue Description
- On September 27, we completed [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47212#issuecomment-1260936163) to remove CareerScope from VA.gov because we're no longer offering access to that service.
- We set up a temporary redirect to this [Veteran employment resources](https://www.va.gov/careers-employment/veteran-resources/) page
- Now we need to create a standalone R&S article about [ONET Interest Profiler](https://www.mynextmove.org/explore/ip) to serve as the permanent replacement for the CareerScope page. This should be a very brief article describing the ONET tool and how Veterans can use it to explore careers that align with their interests. 

Here's some language from stakeholders about the resource:
<img width="640" alt="Screen Shot 2022-09-28 at 10 51 20 AM" src="https://user-images.githubusercontent.com/104158104/192812191-f631cffa-3296-441f-b270-ba450a3e3631.png">

---
## Tasks
- [x] Create R&S article in Drupal (Katherine or Aliyah)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Send to stakeholders Tammy, Terry, and Ricardo (Laura)
- [x] Prepub checklist & publish (Megan)
- [x] Create redirect ticket for PW team to set the permanent redirect (Laura)

## Acceptance Criteria
- [x] New R&S is live
- [ ] CareerScope URL is redirecting to new R&S

**Comment by katherine-fung** [comment]
Hi @laurwill, here's the preview link for this R&S article: 

http://preview-prod.vfs.va.gov/preview?nodeId=49817

**Comment by laurwill** [comment]
Thanks @katherine-fung !
Could you try adjusting to:
-  get "O*NET Interest Profiler" into the H1
-  mention the switch from CareerScope in the intro

ONET has some search volume so it makes sense to keep it in the title, and I think "take a career assessment" sounds like we might offer several options for assessments, or like it's an official VA resource. I also started adjusting to make the ONET link a regular link instead of a CTA — I think we only use CTAs for VA resources, not for external resources like ONET. 

Let me know if you want to chat as you're updating!

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Thanks for chatting with me as I updated the draft! Here's the updated page for your review: 

http://preview-prod.vfs.va.gov/preview?nodeId=49817

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I made all the links to other resources nodes and made the careerscope reference an alert as we discussed in standup. I also added a sentence about how long the process takes, based on info stakeholders sent previously. I'm going to confirm with Beth that the length of this page is okay, and then we can send for approval.

**Comment by laurwill** [comment]
Hi @megzehn , 
This page is ready for a copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=49817
Let me know if you have any Qs! Thanks. And noting that we'll send this to stakeholders before publishing.

**Comment by megzehn** [comment]
Thanks @laurwill! I copy edited this page and left it in drafts. 

It looks good to me!

**Comment by laurwill** [comment]
Thanks Megan! I sent this to stakeholders for review.

**Comment by laurwill** [comment]
Approved! 

@megzehn , you can go ahead and prepub/publish this whenever you have a moment.

**Comment by RLHecht** [comment]
This is complete! Closing.
