### ISSUE TITLE
Staging Review [Benefits Team 1 - Certificate of Eligibility]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#47656]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Request per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule a meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before the scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [x]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.
- [x]  Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [x] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] [Staging URL](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction) and [staging test-user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Certificate%20of%20Eligibility%20Test%20User%20Information.md)

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/README.md) 
 
  

- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/Test%20and%20Launch/Release%20Plan.md) with the "Planning" sections completed 

### Content artifacts 

- [x] Your product’s [content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/research-design/sourceofcontenttruth.md)
- [x] [Add react widget to housing COE landing page #43901](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43901)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] [Product test cases/test plan](https://docs.google.com/spreadsheets/d/1mU2Q2Lg4U5tVA3pc2eGwGelc3pNs4k3mWPPlnrlEwyc/edit#gid=1710602769)
- [x] CoE [Unit Tests](https://drive.google.com/file/d/1z9U6jXgJPzA48wlmtlSIzghejg7P6UFo/view?usp=sharing) and [E2E Tests](https://docs.google.com/document/d/1X8r-X75-3VozEK1Z90Xav1MrJ3jflriad8F1H7tl9ig/edit)
- [x] Summary (Defects) reports: [Certificate of Eligibility | Launch #40978](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40978)

### Accessibility artifacts 

- [x] [[A11y Cursory Audit] Certificate of Eligibility (CoE) Form #44914](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44914)

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman

**Comment by shiragoodman** [comment]
@saderagsdale I wanted to confirm with you before you continue -is this work that was started by the former eBenefits team? Loan Guarantee: Certificate of Eligibility? Here is there [Design Intent ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23484)and [Midpoint Review ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24947)tickets for reference.

**Comment by saderagsdale** [comment]
@shiragoodman Hey there! Yes, this is the work that was started by the former team. From what I could find in the handoff documentation, they had completed the midpoint review and were next up for QA and analytics reviews. Is that accurate?

**Comment by shiragoodman** [comment]
@saderagsdale yes, it looks like all they completed was the 2 I linked above. Are you picking up right where they left off or are you making changes to their design?

**Comment by saderagsdale** [comment]
@shiragoodman Picking up where they left off. No big design changes.

**Comment by shiragoodman** [comment]
sounds good @saderagsdale ! Please remember to post in #vfs-platform-support when you're ready to schedule. Thanks!

**Comment by it-harrison** [comment]
hi @saderagsdale just a reminder to add QA artifacts, ideally 4 business days before review.

**Comment by shiragoodman** [comment]
Meeting recording: https://oddball-io.zoom.us/rec/share/gCe-Es-1i3qzbXbpCY2nhdbeUYUMdxEXkdGJKyh-W6C4brLz6noczT5v_R7ugNoO.8hltFXITW8dx4qS1
Passcode: &3NXQq?4
