### ISSUE TITLE
[FE] | Profile | Scroll to top of field after successful update

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#47666]
## User Story

- As a mobile user, I should be able to update a field, then have that field still be visible once the update is completed and not have to scroll to that field.

## Description

When fields are updated on mobile (specifically noticeable for addresses) the field itself is sometimes not visible after a successful updates. We should make sure that the field is scrolled into view after every update action is executed.

## Tasks

- [x] Scroll to updated field after update succeeds or fails

## Acceptance Criteria

- [x] Field is scrolled into view on mobile after updating
- [x] Passes Accessibility checks using axe

**Comment by SKasimow** [comment]
@adamwhitlock1 - is this additional work or did the work in #48011 fix the scrolling issue across the board?

**Comment by adamwhitlock1** [comment]
I'm having a hard time reproducing this issue locally or through browserstack. I will continue to test this, but considering this over a year old it may not be an issue any more, or may have been a false flag that I reported.

**Comment by adamwhitlock1** [comment]
Was able to reproduce this exclusively on iPhone or via Safari on mac. Getting PR for this ready for review now.

**Comment by adamwhitlock1** [comment]
Confirmed fix on staging and prod via safari and iphone. Closing
