### ISSUE TITLE
[Design] My VA Audit UX Improvements: Updates to LOA1 Call to Action

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47668]
## Background
We need to update the alert for identity verification based on design intent feedback. The Platform team informed us there is a lot alert fatigue on Va.gov in general so they recommend not using the yellow styling and maybe using a blue styling instead.

## Tasks
- [x] Review design for LOA1 users "verify your identity alert"
- [x] Share design updates with team

## Acceptance Criteria
- [x] New design for LOA1 users to verify their identity is complete

**Comment by aagosto90** [comment]
I updated this design to the alert style in the pattern library that's now being used for identity verification and sign in prompts, which is green. We can include this view in the collab cycle steps going forward to make sure we're on the right track.

[Link to Sketch artboard](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/32BCF55D-35A5-4A17-9F37-3DCA903B7A50)
