### ISSUE TITLE
[Wizard] Update FSR Wizard to add Copay Path

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#47662]
## Issue Description
Copy needs to be added for the Copay path on the Wizard

---
## Tasks
- [x] Meeting with Sitewide content to discuss various solutions and path forward
- [x] Mockups Design with initial draft content and new structure
- [x] Validate copy with Sitewide Content 
- [x] Validate copy with SME
- [x] Approve final copy with Sitewide Content 

## Acceptance Criteria
- [x] Designs are complete
- [x] Design to Dev handover for implementation

**Comment by denisecoveyduc** [comment]
Oct 6 - Wizard was just updated (see below) to better reflect the addition of copays. In discussions with Danielle she agrees that we need to think about how to make that link more prominent. Maybe we have two H2 Headers - one to point directly to the form.. and another to highlight wizard in the event they aren't sure if it is the correct form for them. 

We (Danielle, Denise, @mgleo and @briepipitone)  plan to meet on October 17th to discuss further. 

## Oct 6 Wizard Page Update
![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/144e54ae-4ef3-46e4-8107-05a27b01d9a2)

**Comment by denisecoveyduc** [comment]
Oct 17 - we are planning to meet with Danielle (Sidewide Content ) to discuss this and the wizard changes. Should have a path forward as a result of that discussion.

**Comment by mgleo** [comment]
Add [primary action link style](https://design.va.gov/components/link/action) to _Request help with VA Form 5655_

![Screenshot 2023-02-07 at 10.39.57 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/7b920763-9e53-4739-be2a-af4f3fcac792)

**Comment by josephrlee** [comment]
Marking this closed as we will be deprecating the wizard and moving it outside of the FSR. 

The copay paths will be turned into a complete a subtask pattern with this epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72709 

cc: @Tom-Davis @dhill802 @mgleo @denisecoveyduc
