### ISSUE TITLE
Spanish translation work for booster/flu shot content on main vaccines page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47670]
## Issue Description
We made changes to the featured content box and the flu shot question on 9/23/22. We need to send this text to the translators and update our Spanish page with the translated content.

## Tasks
- [ ] Send content to translators (Randi)
- [ ] Update page with translated content (Aliyah)
- [ ] Copyedit
- [ ] Publish

## Acceptance Criteria
- [ ] Spanish live page has new content

**Comment by RLHecht** [comment]
Old ticket. Closing.
