### ISSUE TITLE
Spanish translation work for booster/flu shot content on boosters page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47671]
## Issue Description
We made updates about booster shots and flu vaccines to our COVID-19 boosters page on 9/23/22 and 10/17. We need to send this content to translators and update the Spanish page.

Updated word doc sent to translators: [https://app.zenhub.com/files/133843125/f47b3fdc-fd00-49fa-b927-4751728bedae/download](https://app.zenhub.com/files/133843125/f47b3fdc-fd00-49fa-b927-4751728bedae/download)

## Tasks
- [x] Send content to translators (Randi)
- [x] Update Spanish page (Aliyah)
- [x] Copyedit Spanish page
- [x] Publish page

## Acceptance Criteria
- [x] New translated content is live on the site

**Comment by RLHecht** [comment]
@aliyahblackmore I believe all this content is now on the live page. I'm going to close this but please reopen if that's not the case. Thanks!
