### ISSUE TITLE
Tagalog translation work for booster/flu shot content on COVID-19 boosters page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47673]
## Issue Description
We made updates to the booster and flu content on the booster vaccine page on 9/23/22 and 10/17. We need to update our Tagalog page with the same content.

Updated Word doc sent to translators: 
[https://app.zenhub.com/files/133843125/df8e52d3-23e9-41a1-82a1-ef9bd97b20ce/download](https://app.zenhub.com/files/133843125/df8e52d3-23e9-41a1-82a1-ef9bd97b20ce/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Tagalog page (Aliyah)
- [x] Copyedit 
- [x] Publish

## Acceptance Criteria
- [x] Tagalog boosters page is live with changes

**Comment by RLHecht** [comment]
Update: I emailed the translation team 11/29 to check on this.
