### ISSUE TITLE
Add expandable alert for hurricane debt relief 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47674]
## Issue Description
DMC would like to add a pop up on the debt portal alerting Veterans that they are offering debt suspension for benefit debts for 90 days.

![image.png](https://images.zenhubusercontent.com/614a1fef81dbf0d12d8dd5ac/9e6546b9-1ac2-4867-adf7-7bac838a3414)

---
## Tasks
- [ ] Add expandable alert to summary page
- [ ] Add content shown in screenshot

## Acceptance Criteria
- [ ] We have an alert available to Veterans detailing hurricane relief
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
