### ISSUE TITLE
Tagalog translation work for booster/flu shot content on main vaccines page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47672]
## Issue Description
We made updates on booster content and flu vaccines to our main COVID-19 page. We need to send the text to translators and update the Tagalog page. 

## Tasks
- [ ] Send content to translators (Randi)
- [ ] Update Tagalog page (Aliyah)
- [ ] Copyedit page 
- [ ] Publish

## Acceptance Criteria
- [ ] Tagalog main page is live with updates

**Comment by aliyahblackmore** [comment]
**11/2 update here:**
Just noting that we still need these translations back. We went ahead and added in and made edits to the page based on the 10/21 updates that we received on 11/2 -  but we need to add these once we get them.

**Comment by RLHecht** [comment]
Update: Emailed translators about this on 11/29.

**Comment by RLHecht** [comment]
Old ticket. Closing.
