### ISSUE TITLE
[FE] My VA Audit UX Improvements: Education and Training Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47683]
## Background
This ticket is to implement the FE development work based on the new designs for the Education and Training section of My VA.

[Frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/education-and-training-FE-documentation.md)

1. Create new section for "Education and training" after "Benefit payments" and before "Saved applications"
2. Always show section for LOA3 users, LOA1 never sees this section
3. Three secondary links always appear on the left side immediately below the header
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/education-and-training-FE-documentation.md#learn-how-to-apply-for-va-education-benefits-link)

## Tasks
- [x] Create new "Education and training" section in new code version
- [x] Ensure GI Bill and GI Bill Statement of Benefits is capitalized as per design (this was content feedback)
- [x] Test
- [x] Move ticket to validate 

## Acceptance Criteria
- [x]  "Education and training" section matches designs and FE documentation

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ compare designs and FE documentation to staging

**Comment by tmitchellgcio** [comment]
Just merged please give this about 30min to an hour to be deployed to staging

**Comment by ericasauv09** [comment]
validated with users 15 and 20: ![Screen Shot 2022-12-05 at 15.38.45.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/2932a7a7-5c66-4dfe-9b2a-71f4b85cc51a)
