### ISSUE TITLE
GA4:  BQ Data Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47698]
### Description
GA4 data will need to be brought in BQ same as UA data is today.  We need to understand how to do that, the differences between the 2 datasets and how to manage to that (what are the downstream implications, if any at alll?)

**Resources:**
- [[UA→GA4] Events in Google Analytics 4 vs Universal Analytics](https://support.google.com/analytics/answer/11091422?hl=en&ref_topic=12154439,12153943,2986333,&sjid=14761028565028366082-NC&visit_id=638427385828147845-1851749412&rd=1)
- [[UA→GA4] Universal Analytics versus Google Analytics 4 data](https://support.google.com/analytics/answer/9964640?hl=en&ref_topic=12154439,12153943,2986333,&sjid=14761028565028366082-NC&visit_id=638427385828147845-1851749412&rd=1#zippy=%2Cin-this-article)
- [[UA] BigQuery Export schema](https://support.google.com/analytics/answer/3437719?hl=en)
- [[GA4] BigQuery Export schema](https://support.google.com/analytics/answer/7029846?hl=en)
- [How to set up BigQuery linking in your Google Analytics 4 property](https://www.ga4bigquery.com/tutorial-how-to-set-up-bigquery-linking-in-your-google-analytics-4-property-ga4/)
- [[UA→GA4] Possible reasons for conversion differences in GA4 vs. UA](https://support.google.com/analytics/answer/13672281?sjid=14761028565028366082-NC)

### Tasks
- [x] Determine and document how current UA data in pulled into BQ.
- [x] Identify and document differences in data models and how that might impact Domo dashboards (i.e. what is the new data model likely going to look like, that we'll need to do some transformation to match)
- [x] Determine if/how we can use both the legacy and the new GA datasets in conjunction for reporting historical trends once we migrate.
- [ ] Create initial version/shell of new data model for GA4.
- [x] Document gaps in understanding, and next steps in the form of new Zenhub cards coming out of this ticket.

### Acceptance Criteria

- [x] Current data structure within BQ has been documented.
- [ ] Requirements for new targeted GA4 dataset have been documented.
- [x] Findings from tasks have been documented in the spike findings section.
- [x] New Zenhub cards that will allow for next steps have been created in the _**Backlog**_.

---
### Spike Findings

- UA data is pushed to BigQuery from GA.  It will be the same for GA4.
- The legacy UA and new GA4 datasets will be combined in the BigQuery VIEWs used to supply data to Domo so historical trend reporting will not be impacted.
- The only significant impact to the reporting model will happen if any UA attributes are deprecated.  As yet none have been identified.
- The primary differences in the data model are a shift from hit based tracking in UA to event based tracking in GA4 which really is just a shuffling of the attributes names.  An Item of note is that the user ids will be reset but they are not guaranteed to be consistent currently in UA as they are cookie based.  Also the determination of what constitutes a session and its duration are calculated using a different method in GA4 than UA.
- The custom events will have to be configured in GA4 to match what we currently have in UA, we need to document if any of the model changes impact our ability to recreate the UA custom events in GA4.

**Comment by jestutt** [comment]
@dorseypa1 Here's the list of [GA UA Custom Definitions - (All VA.gov Website Data [Production]](https://docs.google.com/spreadsheets/d/1X5EjZRMJwXyGCxEWA57knO6PL94IHqoNlhtKQm6oXPM/edit?usp=sharing).

Let me know if there are any questions.

**Comment by dorseypa1** [comment]
Documents

GA UA Custom Definitions - (All VA.gov Website Data [Production] - https://docs.google.com/spreadsheets/d/1X5EjZRMJwXyGCxEWA57knO6PL94IHqoNlhtKQm6oXPM/edit#gid=0

Domo Datasets - (From last years Audit by Michelle)
https://docs.google.com/spreadsheets/d/1xKhWfWV5S6j-EkoovxJyIBFZK2ttNG1AhtZPuYma9Ik/edit#gid=570253223

Google Documentation on UA -> GA4 migration
https://support.google.com/analytics/answer/9964640?hl=en&ref_topic=12154439,12153943,2986333,&sjid=14761028565028366082-NC&visit_id=638427385828147845-1851749412&rd=1#zippy=%2Cin-this-article

https://support.google.com/analytics/answer/11091422?hl=en&ref_topic=12154439,12153943,2986333,&sjid=14761028565028366082-NC&visit_id=638427385828147845-1851749412&rd=1

https://support.google.com/analytics/answer/3437719?hl=en

https://support.google.com/analytics/answer/7029846?hl=en#zippy=%2Cevent%2Cuser

https://support.google.com/analytics/answer/9358801?hl=en&ref_topic=9359001

**Comment by johnny-jesensky-adhoc** [comment]
Spike findings have been documented in the ticket. Moving this to **_Done_** -  **note**, there are some tasks, that make more sense to include in next sprint, specifically the two tickets we are pulling into next sprint:

**- GA4: Data Mapping Prep - Create GA4 Views in BigQuery#75520**
- [ ]   Create initial version/shell of new data model for GA4.

**- GA4: Perform audit of fields and Beastmode calculations in Standardized Domo KPI Dashboards#47699** 
 
- [ ] Requirements for new targeted GA4 dataset have been documented.

Have enough discovery to take some iterative steps on this.

FYI @dorseypa1
