### ISSUE TITLE
Certificate of Eligibility | Document display and download on COE status page

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#47693]
## Issue Description

In conversation, Robin raised a number of points regarding how we display documents, and download documents, on the [COE status page](https://staging.va.gov/housing-assistance/home-loans/check-coe-status/your-coe). I will enumerate these points below. Because these points are closely related to each other, and because some of these points may not generate any follow-up actions, I am creating only one issue.

### Point 1: `GET /documents` endpoint returns irregular and unpredictable data

See Appendix 1 below. 

First, [`mime_type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) should be `application/pdf`, but here, `mime_type` appears to be a file name that is often, but not always, in the format of a uuid. On the front end, we are currently pulling a document's file extension from this `mime_type`, not because it's a good idea, but because this is the only attribute that consistently includes a file extension. 

Second, `document_type` is sometimes a description of the document, and sometimes `pdf`. If `document_type` consistently returned `document_type`, then we could rely on it instead of `mime_type`. But since it does not, we cannot. If we could rely on `document_type` then we would not have to [hardcode the file type on the front end](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/lgy/coe/status/components/DocumentList/ListItem.jsx#L10) (but see Point 2).

Third, although `description` does seem to contain a description of the document (e.g. "Discharge or separation papers (DD214)"), it sometimes returns `null`. On the front end, we rely on `description` to render a header for each document. If there is no `description`, then we do not render a header. I'm assuming this is not something we want.

We might be responsible for the problems with `document_type` and `description`. See https://github.com/department-of-veterans-affairs/vets-api/blob/0e1c7ab3b1e27478ec5dc5c3dbae20632ed2785c/app/controllers/v0/coe_controller.rb#L92. 

Next steps:
- [x] Look through our code to see if we are in any way contributing to these strange responses. 
    - We are not. This strange data is coming directly from LGY. In User 228's case, the data returned looks fine (aside from mime_type) up until Sept 22, 2022. Then, on Sept 26, 2022, we start getting null `description`s and `documentType` being set to what was formerly `description`.

**UPDATE (12/23/2022):** We can expect mime_type to return the filename with extension. Though strange, we can still rely on it to consistently return the file extension, so we will. `document_type` describes the "kind" of document, e.g. "COE Application First Returned Letter", and `description` is the vet's free text description of a document they uploaded during the COE form if they chose document_type "other." We are currently using `description` to "tag" documents as vet-uploaded attachments or not, to allow us to display only service-issued notification letters on the COE status page. See https://github.com/department-of-veterans-affairs/vets-api/pull/11338. Since that PR was merged, LGY has started setting `document_type` to `Veteran Correspondence` for vet-uploaded attachments. This means that in the future, we can rely on `document_type` for filtering purposes, rather than by adding a tag in the `description` field. That is a tech-debt ticket for the future, that I plan on drafting later.

### Point 2: Does LGY's `GET /document/#{id}/file` endpoint always return PDFs -- even when the file was originally uploaded as a non-PDF (e.g. JPEG)?

In the COE flow, we are able to upload PDFs and non-PDFs (e.g. JPEGs). Given that, when we consume the `GET /document/#{id}/file` endpoint, do we always get a PDF back? Or, do we get the original file type? Currently, we [hardcode the filetype as PDF on the front end](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/lgy/coe/status/components/DocumentList/ListItem.jsx#L10). If it were possible to download non-PDFs, then we would have to stop hardcoding the filetype, and would need to have a reliable way to determine the file type of each document (see Point 1).

Next steps:
- [x] Test whether this an uploaded JPEG is downloadable as a JPEG, or as a PDF. 
    - LGY returns the same file type that we upload.
- [x] Verify expectations with LGY.
- [x] Modify our code to open non-PDF filetypes.
    - UPDATE: There's actually no need to do this because we decided to only show notification letters on the COE status page, and all notification letters are PDFs.

### Point 3: Is it acceptable that the download links for COE files on [the COE status page](https://staging.va.gov/housing-assistance/home-loans/check-coe-status/your-coe) do not have a descriptive filename?

Currently, the download links for files on this page have the following format: `Download Notification Letter <MMDDYYYY> (PDF)`, where `MMDDYYYY` is the date that the file was uploaded. This means that files uploaded on the same day will have download links with identical text. See Appendix 2 below. If we could rely on `description` (see Point 1 above), then we could provide more detailed link text. And while the headers for each file _could_ be used to distinguish between the links, such headers only exist when description is not `null` (See Point 1 above).

Next steps:
- [ ] ~~Decide whether download links on the COE status page should have a descriptive filename.~~

**UPDATE (1/4/2023)** IMHO, this is not important right now. In https://github.com/department-of-veterans-affairs/va.gov-team/issues/51471, we ensure that each document has a title viewable on the page. This adequately distinguishes between documents. I don't think there's any material value in repeating that distinction in the download link. Though if this issue is raised as a problem later, I can create a separate ticket.

### Point 4: Is it acceptable for downloaded files to have a non-descriptive filename?

Currently, when a file is downloaded, its filename is the numeric ID of the document (e.g. "23923455.pdf"). Do we want filenames to be more descriptive than that?

Next steps:
- [ ] ~~Decide whether we want filenames to be more descriptive than a numeric ID.~~

**UPDATE (1/4/2023)** IMHO, this is not important right now, especially given in light of https://github.com/department-of-veterans-affairs/va.gov-team/issues/51471. The user is free to rename the file however they like. Additionally, with recent changes on LGY's end, we may actually get more descriptive filenames from them going forward anyways. If this is raised as a problem later, I can create a separate ticket for it.

### Point 5: Do we want downloaded PDFs to open in the browser, or to be downloaded directly to the user's computer?

Currently, downloaded files open in the browser (i.e. they open up as a new window, or a new tab). If we want, we can download them directly to the user's computer (i.e. the browser will download the file into the user's downloads folder).

Next steps:
- [x] Decide how we want files to be downloaded.
    - See https://github.com/department-of-veterans-affairs/vets-website/pull/22964

### Appendix

**Appendix 1: `GET /documents` response for vets.gov.user+228@gmail.com** 

```json
{
  "data": {
    "attributes": [
      {
        "id": 23923523,
        "document_type": "Discharge or separation papers (DD214)",
        "create_date": 1664222643000,
        "description": null,
        "mime_type": "{B7E9A4EA-34AE-4D36-909B-DBDB73D53477}.pdf"
      },
      {
        "id": 23923522,
        "document_type": "Discharge or separation papers (DD214)",
        "create_date": 1664222568000,
        "description": null,
        "mime_type": "{B7E9A4EA-34AE-4D36-909B-DBDB73D53477}.pdf"
      },
      {
        "id": 23923455,
        "document_type": "pdf",
        "create_date": 1663869444000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "download_coe (2).pdf"
      },
      {
        "id": 23923335,
        "document_type": "pdf",
        "create_date": 1663607822000,
        "description": "Annual retirement points",
        "mime_type": "{990CCDD6-5EFD-4F75-934B-C7CCFF195372}.pdf"
      },
      {
        "id": 23923334,
        "document_type": "pdf",
        "create_date": 1663607820000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{7E728520-8689-481E-9246-E3026972857D} (2).pdf"
      },
      {
        "id": 23923132,
        "document_type": "pdf",
        "create_date": 1663190283000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{52AE947E-D86B-4205-99F8-84057D6A21F2}.pdf"
      },
      {
        "id": 23923131,
        "document_type": "pdf",
        "create_date": 1663190281000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{B7E9A4EA-34AE-4D36-909B-DBDB73D53477}.pdf"
      },
      {
        "id": 23923129,
        "document_type": "pdf",
        "create_date": 1663186918000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{B7E9A4EA-34AE-4D36-909B-DBDB73D53477}.pdf"
      },
      {
        "id": 23923128,
        "document_type": "pdf",
        "create_date": 1663185928000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{AC326C48-9EAB-45C5-B83F-3DCB17495707}.pdf"
      },
      {
        "id": 23923127,
        "document_type": "pdf",
        "create_date": 1663185926000,
        "description": "Discharge or separation papers (DD214)",
        "mime_type": "{990CCDD6-5EFD-4F75-934B-C7CCFF195372}.pdf"
      }
    ]
  }
}
```

**Appendix 2: COE status page**

<img width="721" alt="Screen Shot 2022-09-21 at 11 16 38 AM" src="https://user-images.githubusercontent.com/7520103/192903881-6add78e2-f32a-4c93-b302-79634f786cd6.png">

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@data-doge Are we facing any unintended consequences if we release with point #2 as is today?

**Comment by data-doge** [comment]
@saderagsdale Sorry for the delayed response here. I tested this recently. When a user uploads a picture, they are unable to view it thereafter, because our download link is hardcoded to expect a PDF.

**Comment by Mottie** [comment]
Reported to LGY, they will discuss with their developer. Likely to be a mock data issue.

**Comment by Mottie** [comment]
Merged in work to make download links download the PDF directly

**Comment by data-doge** [comment]
@saderagsdale I think we can close this ticket. If you `CMD + F` for "UPDATE", you can see my reasoning. Let me know what you think!
