### ISSUE TITLE
GA4:  New Report Development & Training

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47697]
## Issue Description
GA4 reports and reporting functionality are different than current UA reporting.  We will need to work with VFS teams to develop new GA4 reports that provide the detailed information they need and are getting from current UA reports.  As part of the development work we will provide training resources to the VFS teams.

---
## Tasks
By VFS team:
- [ ] Audit current GA reports and determine what needs to be replicated vs sunset
- [ ] Develop new reports 
- [ ] Test & Validate
- [ ] Release

## Acceptance Criteria
- [ ] When all VFS teams current reporting needs have been implemented in GA4.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket out, as was creating factoring an older GA4 transition workflow. This will still be tracked at the epic level [here](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/53417), but broken out more granularly. 

FYI @jestutt
