### ISSUE TITLE
GA4: Perform audit of fields and Beastmode calculations in Standardized Domo KPI Dashboards

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47699]
### Description
As part of the GA4 migration we will need to assess the impact to our standardized Domo KPI dashboards, and which cards, or calculations we'll need to update and/or rework to reflect the differences in the GA4 data model.

**Artifact:** [DOMO Inventory Spreadsheet ](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=0)

To _**maximize impact,**_ we will be taking a look at our standardized dashboards, which will affect the greatest number of VFS Teams.:
- Content KPIs
- Search KPIs
- Form KPIS

### Tasks
_For each of the standardized dashboards, (Content, Search, Forms)_
- [x]  Inventory list of charts used
- [x]  Document BeastMode calculations feeding each of the the charts.
- [x]  For each BeastMode, identify columns/names, (what Domo is looking for from the data)
- [x] Document findings in an artifact, referenced [here](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=)
- [x]  Share findings with rest of the team, through the linked artifact

## Acceptance Criteria
- BeastMode calculations have been identified and listed for the following:
- [x] Content KPIs dashboard
- [x] Search KPIs dashboard
- [x] Form KPIs dashboard
- [x] Fields that make up BeastMode calculations have been identified

**Comment by johnny-jesensky-adhoc** [comment]
This [spreadsheet artifact](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=0) has all information needed for our three, primary, standardized reports (Forms, Search, Content). We will also be gathering information on _**Owner**_, and _**Last Updated**_ fields on our list of Domo Dashboards.

This has met all of the AC, so marking this as _Done_.

FYI @Blivaditis
