### ISSUE TITLE
[FE] Update Content for All Travel Pages based on Platform Feedback

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47705]
## Wireframes
[Wireframes](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/ecc65d23-3ae2-47cb-9a52-8ab4fa9dab29/commits/eab82af147bca0e28ee00e3734ee9290f1b77efb/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9B61B462-73BA-45CF-ABA4-215FD07B6D5A?collectionId=90b54a54-d2ee-4fae-ad07-73114aa02714&collectionLayerId=6311c53e-ab0c-484a-9e09-8ddcd43532a1&mode=design)

## Tasks
- [x] [FE] **update content** per the wireframes (needs help section is in another ticket)
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [x] Update relevant documentations (readme and use cases)
- [x] fix margin on address from the comments here: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47007 (Also please check for the mixed Spanish language)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by brianseek** [comment]
@zach-park this is ready to validate. Note that the footer (Need Help) section is in another ticket.
See attached screenshots:[https://app.zenhub.com/files/133843125/3ca62cb1-48a7-482b-b923-e4bf95982da5/download](https://app.zenhub.com/files/133843125/3ca62cb1-48a7-482b-b923-e4bf95982da5/download)

**Comment by loripusey** [comment]
Couple issues:
1. Travel from home address screen - wireframe says "here" but code says "below"
    ![image](https://user-images.githubusercontent.com/86678742/195410989-473f3623-5ac2-48bb-be99-7f3388d2e06e.png)
    ![image](https://user-images.githubusercontent.com/86678742/195410938-becef288-d633-4e70-81c1-24908b145ac0.png)

2. Couldn't file claim - wireframe title is different from code
    ![image](https://user-images.githubusercontent.com/86678742/195411268-008b5a0b-655f-49e3-9274-b5fb39129c67.png)
    ![image](https://user-images.githubusercontent.com/86678742/195411323-12b86030-a97d-49b2-aff0-e639ab123145.png)

**Comment by brianseek** [comment]
thanks @loripusey I'll get a quick follow on PR for those!

**Comment by zach-park** [comment]
@brianseek , here is the[ link to the UX audit comment](https://share.goabstract.com/7494e56c-7da9-4de2-b863-512c0ab2f5e7) regarding them. Overall they look really great. Most comments were related to the content for the "Need Help?" section and the "Go to another appointment" link (which we discussed today). Thank you!

**Comment by benbrasso-agile6** [comment]
Left a comment here, re: Need Help section https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/ecc65d23-3ae2-47cb-9a52-8ab4fa9dab29/commits/90732b6508a978917b6f99e6508545537517a979/files/a5e6b375-5806-423f-b89c-94ca0a001c3c/layers/9EC66113-FD31-4500-8ACD-19EDA61662AD?commentId=5511bfbd-4e85-4db6-90f7-d7cafb783621

**Comment by benbrasso-agile6** [comment]
Looks nice

**Comment by brianseek** [comment]
@loripusey / @zach-park  Here are the updated screens[https://app.zenhub.com/files/133843125/a789954b-971c-45c1-98f1-8fd5b33eb436/download](https://app.zenhub.com/files/133843125/a789954b-971c-45c1-98f1-8fd5b33eb436/download)

**Comment by loripusey** [comment]
validated. @zach-park can you take a look as well?

**Comment by benbrasso-agile6** [comment]
The couple that we were talking about late yesterday were: 

1. https://share.goabstract.com/5c39328b-c6c1-452f-93f8-390b3698dd82?mode=design&sha=d1bbc36f2c43a6aa4bca0685e667bf07b092eed5 Change h1 to: You're checked in. And we received your travel claim. 

2. https://share.goabstract.com/4ab2a1a6-d54a-4e52-81b9-f218ddba2311?mode=design&sha=d1bbc36f2c43a6aa4bca0685e667bf07b092eed5 In the yellow box, add the word "travel" immediately before the word "reimbursement." So, it should read, "... travel reimbursement claim for you now."

**Comment by loripusey** [comment]
@brianseek do you want a new ticket for the 2 new changes or do you want to just do it as part of this ticket?

**Comment by zach-park** [comment]
Looks nice. Thank you!

**Comment by loripusey** [comment]
I'm closing this ticket and moving the above 2 changes to a new ticket. @brianseek @benbrasso-agile6

**Comment by loripusey** [comment]
I've moved the changes to this [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48237). @brianseek feel free to pull it into this sprint or we can wait for next sprint, I'll leave it up to you.
