### ISSUE TITLE
[Research] My VA Audit UX Improvements: Submit for research review/begin recruitment

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47708]
## Background
We need to submit all research artifacts for my va audit UX improvements research/usability testing.

Pre-requisites:
- [x] Dev needs to be complete
- [x] Research plan/documentation needs to be complete

## Tasks
- [x] Submit materials to research repo
- [x] Message research ops in slack to let them know you've submitted the materials
- [x] Perform any followup tasks that research team requests
- [x] Let PM/APM know so they can make sure the [collab cycle epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601) is updated as needed

## Acceptance Criteria
- [x] Materials are submitted and recruiting for our study has started

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** NA
- **_How can this work be validated?_** NA

**Comment by ajakabcin** [comment]
Reopening to track research review submission

**Comment by aagosto90** [comment]
@ajakabcin I updated the collab cycle ticket by just checking off that we had completed the research review process, so closing this ticket
