### ISSUE TITLE
[DESIGN] 1010EZ Introduction page variations

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#47707]
## Description

The introduction page of the 1010EZ looks different depending on the status of the user: whether they are authenticated, not authenticated, or verified. We need mockups to match these states.

## Tasks

**Authenticated pages**

- [x] Authenticated user that has already applied for healthcare
- [x] Authenticated user that has not been verified
- [x] Authenticated user with in progress application
- [x] Authenticated user new application
- [x] Authenticated prefill notice
- [x] Authenticated application not accepted
- [x] Authenticated application loading page
- [x] Authenticated downtime alert page

**Unauthenticated pages**

- [x] Unauthenticated user new application
- [x] Unauthenticated downtime alert page
- [x] Unauthenticated application loading page

## Acceptance Criteria

- [x] Confirm the intro page variations with engineering team
- [x] Mockups for each page variation
- [x] Pages are updated to current design system standards

**Comment by nicko-amida** [comment]
@lzapson The [introduction page variations are her](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/0C3B7020-8169-4FF2-AB5C-AF52BC4E34C2/canvas) This includes the list of alerts for the "application not approved" codes.
