### ISSUE TITLE
[FE] | 10-10EZ | Add GA event tag to track short form usage

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#47706]
## Description
Our VFS product owners and stakeholders would like to track how many Veterans are entering the short form flow of the application. This will allow them to compare that volume to how many of those went on to complete and submit the application. With two possible methods for entering the short form flow, event tags will be needed at both entry points to track when the Veteran enters this flow.

**Information box for Authenticated with >50% disability rating**

- ![image](https://user-images.githubusercontent.com/92328831/193352010-ca413430-5612-4ae0-b00b-4a18012c95ef.png)

**Confirmation alert for Unauthenticated/Authenticated with no disability rating**
- ![image](https://user-images.githubusercontent.com/92328831/193351376-2c8d9747-bb30-487b-9a9f-f39b5566897e.png)

## Tasks
- [ ] Add event tag to the authenticated short form alert to track those who qualify based on their disability rating
- [ ] Add event tag to the service-connected confirmation alert to track those who are unauthenticated or don't have a disability rating associated with their VA profile
- [ ] PM confirms event is trackable in Google Analytics

## Acceptance Criteria
- [ ] Short form entry is able to be tracked and compared with total short forms submitted

**Comment by longmd** [comment]
Confirmed the event is being called in the browser for authenticated users with rating of 50% or higher.

![Screen Shot 2022-09-30 at 9 49 03 AM](https://user-images.githubusercontent.com/6738544/193284346-939c6617-a8c4-45e5-9e23-41b3c44af936.png)

**Comment by longmd** [comment]
Confirmed the event is being called in the browser for unauthenticated users when confirmation of service-connected pay is acknowledged.

<img width="1433" alt="Screen Shot 2022-09-30 at 9 52 51 AM" src="https://user-images.githubusercontent.com/6738544/193285172-3581ea27-a760-4ff3-8f0b-4a0568d50c1a.png">

**Comment by longmd** [comment]
@hdjustice , per the previous comments and screenshots above. I have confirmed the events are being recorded in the correct locations.

**Comment by hdjustice** [comment]
Ticket #47780 opened for the Analytics team
