### ISSUE TITLE
[FE] Payment Info V2: (Bug) Copays card not Matching Debt Portal data

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47722]
## Background
When logging into Staging with user 36 we see that the user has 3 copays totaling $324.22. However, when clicking on "Manage your VA Bills" and taken to the copay debt portal the user only has 2 copays listed totaling $106.42. We need to investigate and determine if this is an issue with our implementation and why there is a mismatch in the data.

User 36 Copay Card:
<img width="905" alt="Screen Shot 2022-09-29 at 16 02 18" src="https://user-images.githubusercontent.com/97113607/193130706-710b45f8-7d87-4a78-958c-7769428b765c.png">

User 36 Copay portal:
<img width="826" alt="Screen Shot 2022-09-29 at 16 03 30" src="https://user-images.githubusercontent.com/97113607/193130906-42a38746-e609-472f-b7d3-670b6384bbfb.png">

## Tasks
- [ ] Investigate why user 36's copay data is not matching
- [ ] Implement resolution/fix (or if we need to work with copay team)
- [ ] PM to validate fix with user 36

## Acceptance Criteria
- [ ] User's copay card information matches what is shown in the debt portal

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ log into staging with user 36 and ensure the copay information matches the data in the debt portal. Validate using other Staging users as well such as 39, 11, and 16

**Comment by tmitchellgcio** [comment]
I believe this needs to be discussed with the copay team. Two of the copays are from the same facility and they are trying to separate the copays by facility, but the way they are doing it is only pulling the first one and ignoring the second. I doubt this is intended on their end and if it is it will be very confusing to anyone looking at the page coming from our link. They aren't totaling the amount for the facilities just getting the first one for each.
