### ISSUE TITLE
[Application Hosting and Deployment] Documentation for updating Kubernetes manifest

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#47725]
## Description
The next step after https://vfs.atlassian.net/wiki/spaces/OT/pages/2350645620/Build+a+Helm+chart+for+EKS should be explaining how to add automation to keep the Kubernetes manifest up-to-date when a new version of the app's container is pushed to ECR.
[Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/update-manifests.yaml).

## Background/context 
This used to be part of the onboarding checklist, but we took it out of there since this will happen after their app is onboarded. 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Create document within this space https://vfs.atlassian.net/wiki/spaces/OT/pages/2348909545/Manage+applications+in+EKS
- [ ] Add a link as "next steps" to the previous step

## Acceptance Criteria 
- [ ] Document has been reviewed and published. 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
