### ISSUE TITLE
Collaboration Cycle - Define partnership with Sitewide: Shared Support

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47726]
## Problem Statement 
*In a couple of sentences, describe the Who, What, Why, and Where of the challenge / pain point you seek to address.*

In September 2022, due to funding not getting renewed, the Platform lost an accessibility specialist who was the backup for the accessibility specialist on Governance team supporting the Collaboration Cycle. The Sitewide: Shared Support team has 3 accessibility specialist who will serve as backup for the Collaboration Cycle. **The first purpose of this epic is to get the accessibility specialists on Shared Support trained in the Collaboration Cycle Staging Review so they can fill in if/when needed.**

In addition, the Sitewide: Shared Support team has had a limited number of teams they are able to provide support for. Platform leadership has decided to expand the number of teams they can work with by allowing them to "piggy back" off of the Collaboration Cycle. **The second purpose of this epic is to determine how best to integrate/introduce Shared Support into the Collaboration Cycle so they can embed with VFS teams and provide necessary, more hands-on accessibility support.** 

## Hypothesis or Bet
If we train Shared Support on the Collaboration Cycle Staging Review, then Governance team accessibility specialists will not be burdened.
If we introduce/integrate Shared Support in the Collaboration Cycle, then VFS teams will receive more dedicated accessibility support, meaning more accessible products on VA.gov.

## We will know we're done when... ("Definition of Done")

- [x] Shared Support accessibility specialists can fill in for Governance team accessibility in the Collaboration Cycle Staging Review.
- [x] VFS teams are able to receive dedicated accessibility support from the Shared Support team.

## Known Blockers/Dependencies 
N/A

## Projected Launch Date
November 8, 2022

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by eli-oat** [comment]
@shiragoodman I've been working on a way to summarize some of what we've spoken about. I've tried to summarize that here -- this is probably better served as a document one day, but wanted to share here for initial review. 

*** 

A document describing how the Governance Team and Shared Support work together through the Collab Cycle. 

Shared Support’s role within the Collab Cycle is to **identify and help to resolve issues**, **not raise issues under the Collab Cycle itself.** 

The difference here is primarily semantic, but an important one: 

- Governance Team members are at Collab Cycle meetings to raise issues, e.g. “this is a blocking issue and must be fixed.”
- Shared Support team members are there to say “we’ve noticed this issue, and that is something we can assist you in resolving.”

The Collab Cycle is a launch dependency; VFS delivery teams must go through it in order to release a product or feature to production. Interacting with Shared Support isn’t a launch dependency. Shared Support’s role is auxiliary. Shared Support is a team available to provide support on an as-needed basis in a few key areas -- namely Accessibility, IA, Content, and QA. 

As-needed is left to the discretion of both the individual VFS delivery teams as well as to the Governance team who, through the Collab Cycle, may suggest or request that teams seek the assistance of Shared Support to address a specific issue or set of issues.

VFS delivery teams are welcome to invite any member of Shared Support to a Collab Cycle touchpoint meeting. Specialists from Shared Support may choose to attend Collab Cycle touchpoint meetings for teams that they’ve been collaborating with. Shared Support may be called on by the Governance team to participate in a Collab Cycle touchpoint meetings on an as-needed basis.

**Comment by shiragoodman** [comment]
@eli-oat I like what you've documented above, but I think there could be a few tweaks to better refine the subtle differences between our teams roles.

Can I set up a meeting for us to chat later this week? I will be documenting the remaining tickets/work for this initiative and I think it would be best to review in person and ensure we're on the same page. Lmk

**Comment by eli-oat** [comment]
Yes, absolutely @shiragoodman -- it was my intention that this be a very preliminary first draft. Sorry if I wasn't clear about that!
