### ISSUE TITLE
[Application Hosting and Deployment] Update application onboarding checklist 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#47732]
## Description
The application onboarding checklist should be updated to reflect the new process. There are various steps that are no longer needed, and there is new documentation to better guide users through the process. 

## Background/context 
- Previous form [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=devops%2C+eks%2C+infrastructure%2C+infrastructure-request%2C+operations&template=kubernetes-onboarding-template.md&title=%5BInsert+app+name+here%5D+-+Application+onboarding+infrastructure+request)

---
## Tasks
- [ ] Update the form with clarified instructions and checklist items 

## Acceptance Criteria 
- [ ] The form is updated on GitHub 
  - [ ] Name: "Application Onboarding Requirements Checklist" 
  - [ ] Unnecessary checklist items removed 
  - [ ] Guidance updated 

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
