### ISSUE TITLE
Generative Research for Medical Records: Research Plan and Conversation Guides

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#47739]
## 🌟 Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## 🌟 Description
The purpose of this research is to gain insight into user needs and goals related to medical records, users' emic understandings of medical records-related terms, and how these needs, goals, and understandings influence their behaviors.

## 🌟 Tasks
- [x] Create new folder for this specific test in this [overall research folder]().
- [x] Create research plan 
- [x] Create conversation guide

## :star2: Acceptance Criteria
- [x] Review research plan and conversation guide with team
- [x] Post finalize research plan to [GitHub folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2022-10_Generative-research/2022-10-medical-records-research-plan.md)
- [x] Get approval from Shane Strassberg to move forward with recruitment - [ticket #186](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/186)

People to be included: @jonathanjnelson @coultonbunney-usds @Jenny-yw
