### ISSUE TITLE
Add "decision reviews" to claim status tool

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#47744]
## Issue Description
Shireen asked us to incorporate decision reviews into the [Check your VA claim or appeal status](https://www.va.gov/claim-or-appeal-status/) landing page and online tool. 

We'll need to coordinate with the product team(s) currently working with this tool content, and with Mikki/Joni on IA considerations for changing the H1. 

**Update:** This ticket is for the work in the tool and we'll open a separate ticket to update the landing page.

---
## Tasks
- [x] Do SEO research on "decision reviews" (Laura)
- [x] Review tool and suggest updates to headers and other instances of "claims and appeals"
- [x] Pass to product team

## Acceptance Criteria
- [ ] Tool content updated

**Comment by RLHecht** [comment]
@bethpottsVADEPO ^^

**Comment by laurwill** [comment]
Updates here: Shireen asked about timing for this and it looks like the product team has started adding this term to the tool. 

Next steps:
- Ask Mikki if we can make an exception and go 2 characters over the H1 limit here
- Ask product team where they are exactly with this change
- Decide if this is a Megan task

**Comment by laurwill** [comment]
@mnorthuis we need to add "decision review" to the claim status tool landing page. 

"Check your VA claim, appeal, or decision review status" is 2 characters over the H1 limit. Could we make an exception here?

**Comment by mnorthuis** [comment]
It may result in the title being truncated in some search result pages, but should be ok.  

The intro paragraph and meta description should also be updated on this page to reflect the changes.

**Comment by RLHecht** [comment]
Update: We can try test user 228 for getting into the tool.

**Comment by laurwill** [comment]
Hi @jacobworrell , 
We're updating the static landing page for the CST to add "decision reviews," and we'd like to coordinate with your team to make parallel changes inside the authenticated tool content. This change was requested by OAR partners. 

I looked through the tool in staging and suggested adding it in a handful of places. Here's a word doc with the suggested changes: [Updates to add decision reviews to CST](https://app.zenhub.com/files/133843125/d640bb37-82f7-4eec-8706-b62a3ac9136d/download)

We also have a question out to OAR SMEs about a piece of content in the tool that seems to reference legacy appeals — we may need to update that content to reference decision reviews instead. We'll update here when we get an answer back. 

Let me know if you have any questions or want to chat about this!

**Comment by laurwill** [comment]
Hi @jacobworrell , SMEs confirmed last question and I updated the file. See if this link works for you: 
[Updates to add decision reviews to CST 5.30.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11602510/Updates.to.add.decision.reviews.to.CST.5.30.23.docx)

**Comment by jerekshoe** [comment]
**Update:** I have merged most of the changes outlined in the word doc above, however from what I could tell there were some changes at the end of the list around error messaging that I didn't update because the component that displays the error message that needed updated was part of the MyVA dashboard and not the CST. My team doesn't own the dashboard so the team that does own it will need to make that change. The screenshots below highlight all of the changes I made:
|         | Before | After |
| ------- | ------ | ----- |
| Desktop |<img width="743" alt="Screenshot 2023-07-10 at 3 14 15 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/13838621/4160ef88-cfb9-4b23-8743-e0b19dfd50f1">|<img width="743" alt="Screenshot 2023-07-10 at 2 36 48 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/13838621/c3c6cbf1-15fa-4d76-8b45-f0c90dae6581">|

**Comment by laurwill** [comment]
Thanks @jerekshoe ! We'll open a new ticket for My VA team to update that error message. I'll close this one out.
