### ISSUE TITLE
FE | Profile | Bug | Update Alert Style for Contact Info Alerts

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47757]
## Background

During research sessions for our accessibility audit we found that there is one alert on Profile that does not match the other alert stylings we use. This is a problem for continuity but also because a mobile user was not able to zoom in on this alert. We need to update the design for this alert to be displayed in a background only alert like the others on Profile.

This applies to the home, work and mobile phone number fields as well as home address and mailing address.

Here is the alert: 
![image](https://user-images.githubusercontent.com/97113607/193327178-63dabc82-8fd2-4536-9c2b-029ead50302b.png)

When creating the mock-up, we also realized the error alert that displays in edit mode is slightly out of date with our content guidelines.  Instead of "please check back later", we should say "Try again later." Mock-up below:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/55992116/195820017-1b2474c1-502e-4466-a651-ab6aba5f5cb1.png">

## Tasks
- [ ] Update code to reflect the new alert designs (applies to home, work and mobile phone numbers as well as mailing address and home address)
- [ ] Update alert to reflect new copy as show in mock above
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] New alert for all phone # fields and address fields on Contact info page matches new designs
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Design. PM
- How can this work be validated? Test that new alert matches expected design
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #47755

**Comment by andaleliz** [comment]
Added mock-ups to this ticket and updated the description. I noticed a related change that needs to be made and have added that to this ticket as well.

**Comment by SKasimow** [comment]
Updated ticket to reflect the update to error alert applies to all phone number fields - home, mobile and work.

**Comment by SKasimow** [comment]
Connectivity issue causes this alert.

**Comment by SKasimow** [comment]
@jcatergovy @adamwhitlock1 - I wasn't able to trigger this alert by turning off my wi-fi but assume this also applies to "contact email"; can someone confirm and I will add to ticket. Thanks!

**Comment by SKasimow** [comment]
@jcatergovy - would Adam be able to help?

**Comment by jcatergovy** [comment]
@SKasimow I'll reach out to him on this ASAP

**Comment by SKasimow** [comment]
@jcatergovy - hi - any luck?

**Comment by SKasimow** [comment]
@jcatergovy @adamwhitlock1 - should I carry this over to Sprint 86? Or, can we close this out and open a new ticket to specifically address the unexpected scenario we reviewed earlier today?

**Comment by jcatergovy** [comment]
@cgednalske Let me know how the formatting looks on this one ![47757.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/91514794-60d4-4662-b336-00176fd9077f)

**Comment by cgednalske** [comment]
Hi @jcatergovy! Wasn't completely sure about this, but synced with Liz to confirm and the placement should be right above the Edit button like it is with our success alert (below). 

<img width="643" alt="Screen Shot 2022-11-04 at 10 02 21 AM" src="https://user-images.githubusercontent.com/79372956/200033629-afcefe0f-7720-45d1-8b0c-5f0104ef509d.png">

For the content, we also discussed this and it sounds like we should use the same content as our regular error alerts like below. The guidance has changed a bit recently so the old one is out of date. Let me know if you have questions on either one of these 🙂 

<img width="417" alt="Screen Shot 2022-11-04 at 10 04 44 AM" src="https://user-images.githubusercontent.com/79372956/200034383-20f11afd-eae5-4313-a3f5-15915f86aa9e.png">

**Comment by jcatergovy** [comment]
@cgednalske I went over this with @adamwhitlock1 and placing this error between the address and the Edit/Remove buttons is a bigger lift.  We would need to move the existing component into a different component with its corresponding logic and update tests.  I can push with the new alert appearing below the buttons or above the address today and we can make a new ticket for moving it to the desired location or we can close this out as is and roll it all into one new ticket.  How would  you like to proceed?

**Comment by cgednalske** [comment]
@jcatergovy Hmm.. Design system guidance does say to place this sort of error directly below the affect information/component (address), so if possible we should probably stick with this placement below the address and above the button - also because it follows our regular pattern. If we don't, I suppose there's the chance it could get flagged down the road as not following the guidance. 😐

**Comment by jcatergovy** [comment]
@SKasimow I concur.  I'll close this branch and we can make a new one when we open the new ticket.

**Comment by jcatergovy** [comment]
@SKasimow I concur.  I'll close this branch and we can make a new one when we open the new ticket.

**Comment by SKasimow** [comment]
@ericasauv09 - could you create the new ticket for this work?

**Comment by ericasauv09** [comment]
Created #49550
