### ISSUE TITLE
Updating URLs that link to VHA FSR

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47758]
## Issue Description
There combined debt portal is complex and has many different routes to the electronic FSR experience. We have discovered pathways that aren't routing to the onlineFSR/ waiver submission process. 

---
## Tasks
- [x] Validate that following pathways to the electronic FSR from copay cards and detailed pages. 

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/72393866/193938805-2531f0de-1982-4137-abbb-bbdb6ea5efc5.png">

## Acceptance Criteria
- [x] Update link from the copay details card to the online FSR experience. 
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@OptionSelect Can you add an estimate to this one? I am going to add screenshots and close it since I know this has been done. Thanks.
