### ISSUE TITLE
FE | Profile | Contact Information | Validation for Emojis in email addresses

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47754]
## Background
As noted in [this thread](https://dsva.slack.com/archives/C909ZG2BB/p1664386601195079) we discovered that emojis can be used in email addresses. Similar to the validation rules for addresses we should disallow non-ascii characters

## Tasks
- [ ] Add form validation for non ascii characters
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Anyone
- How can this work be validated? test validation of an emoji email address
- What updates need to be made (e.g. product outline, use cases, contact center guide)
