### ISSUE TITLE
Design | Profile | [Project]| [Issue Name]

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47755]
## Background

During research sessions for our accessibility audit we found that there is one alert on Profile that does not match the other alert stylings we use. This is a problem for continuity but also because a mobile user was not able to zoom in on this alert. We need to update the design for this alert to be displayed in a background only alert like the others on Profile.

Here is the alert: 
![image](https://user-images.githubusercontent.com/97113607/193327178-63dabc82-8fd2-4536-9c2b-029ead50302b.png)

## Tasks
- [ ] Create new mock up design for this alert
- [ ] Add new design mockup to FE ticket linked [here]()
  

## Acceptance Criteria
- [ ] New design is created to replace the old style alert shown above

**Comment by SKasimow** [comment]
@andaleliz - is this something I can add to your board for the current sprint?

**Comment by andaleliz** [comment]
Yep!

**Comment by SKasimow** [comment]
thanks -- here it comes :)

**Comment by SKasimow** [comment]
Thanks Liz!
