### ISSUE TITLE
[Design] Payment Info V2: Update Copay Card Design and Logic

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47763]
## Background
After speaking with the benefits-team-2 we learned that the debts portal only shows the most recent copays owed at each facility. They have no way of knowing if the user has paid off their copay therefore, they only show the most recent copay owed and do not include additional copays that may exist for that user. Since My VA is showing all copays and aggregating them we need to update our designs and logic to match the debt portal so we are consistent between the two pages for our users. This [Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1664557969007349) explains the background for this ticket as well.  

## Tasks
- [x] Update copay card design and logic to only include most recent copays owed at each facility.
- [x]  Update FE documentation
- [x] Share with team

## Acceptance Criteria
- [x] New design and logic for copay card is created

**Comment by aagosto90** [comment]
Met with My VA team on 10/7 to discuss limitations of copay data and decide a path forward. We agreed to not show a dollar amount total for copays since there is currently no way to access the data that shows how much of a statement is actually still due in real time. The updated designs will show the number of copay statements that a user has and link to the copay balances page. It will also have an "updated on" date instead of a "due by" date which will be the most recent date that any copay statement a user has has been updated.

Updated designs and [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md) for outstanding debts copay cards.
