### ISSUE TITLE
Collaboration Cycle for [10-10 Health Apps, 10-10EZ, Household Information Optimization]

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#47766]
### VFS team name

10-10 Health Apps

### Product name

10-10EZ

### Feature name

Household Information Optimization

### GitHub label for product

1010-ez

### GitHub label for feature

household-info-optimization

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

05/2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/ReadMe.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

 ## Recommended Collaboration Cycle touchpoints

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

- [x] [Whiteboard sketch or other lo-fi prototypes or wireframes](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- [x] [User flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR0pl7W)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Plan.md)
- [x] Any other artifacts you have so far
  - [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Conversation%20Guide.md) 
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: October 14, 11:30am
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/_EZrNARAhrT1MIDxLeAu8jJbkBfrCvCni7p5fNHQD-k0zZn4V-AkZJ1tVHPDjsyN.cGKklTQwmBGNXR6b)
  - Password: T=2hW2H2
  
##### VFS actions

- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below
     - [Ticket #48245](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/48245)

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [x] Finalized design [UXPin prototype](https://preview.uxpin.com/6a98bfd8c3a76816b8695fbdc6883bd477610024#/pages/159024257/simulate/no-panels) or [Sketch mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- [x] Specify which pages are included in the review 
**Authenticated flow**:  The updated section starts on page 13.
**Unauthenticated flow**: The updated section starts on page 17.
     - Financial Disclosure
     - Marital Status
     - Spouse information
     - Spouse residence
     - Dependents
     - Dependents information
     - Additional Dependents
     - Veteran Annual Income
     - Spouse Annual Income
     - Previous year's deductible expenses

- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Conversation%20Guide.md)
 
**Content artifacts**
  
- [x] Your product’s content source of truth: [10-10EZ - Online Pages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ%20-%20Online%20pages.pdf)
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): N/A

**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
     - [Ticket #48245](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/48245) for Sitewide Content and IA feedback

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): [10-10EZ Regression test plan](https://dsvavsp.testrail.io/index.php?/runs/view/4303&group_by=cases:section_id&group_order=asc)
- [ ] Link to test cases/test plan in TestRail (draft OK): 
- [x] [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases%20-%20Alternate.md)
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: **November 28, 3:00pm ET**

##### Platform actions

- [x] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
  - [x] QA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/CdeVWZawZI-et346dZ0ZME9wASy8Jcv7FWNSsLi2-n6XSe0Bm2gmtrIPBPf4olY.hVGRnwqN4UJYOmo0
  - Passcode: Hf8v+.^t

  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
     - [x] #62679 

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
     - Experimental design has already been reviewed with DSC - [ticket #1565](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1565)
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts**
  
- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Product/Household%20section%20optimization%20-%20Release%20Plan.md) with the "Planning" sections completed  
- [x] [Staging URL](https://staging.va.gov/health-care/apply/application/introduction)
- [x] Specify which pages are included in the review      
     -  All pages within Step 4 Household Financial Information
          - Once you have reached the Medicaid question, you have completed the Household Financial Information section
- [x] [Staging test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZ-household-section-optimization.md) 
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [N/A] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA ticket #48245](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48245) feedback you received, including an IA review document or intake form.
     - [x] [Additional content feedback implemented #57959](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959)
     - [x] Experimental design has already been reviewed with DSC - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1565

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/plans/view/4298)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/runs/view/4540)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/418)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/417)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51645#issuecomment-1587758183) (provide a link to the product’s code)
- [x] [Code coverage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51645#issuecomment-1587761206)  
- **This is our first time creating reports in TestRail**

  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58694).
  
##### Platform actions
- [x] VFS Team Slack Support Request Thread: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1687978463134919)
- [x] Meeting date/time: **Thursday, July 13th at 1:30pm ET**

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/ql2Hw6twpvP-d77-65Z-ZLiOp82U0wj85lkkAsZBtLP8dx7Cz0B7b9z8rxcO3ElH.EuwbxuzBZkBs4zFe)
  - Password: `gK$K!K8K`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Communicate known accessibility issues to the VA 508 Office via Audit Request.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, as well as all post-Staging actions
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
     - [Ticket #1048](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1048)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by hdjustice** [comment]
Closing ticket - all Collab Cycle tickets have been addressed and the feature has been launched successfully!
